ET: Legacy: src/renderer2/tr_surface.c File Reference
tr_surface.c File Reference
THIS ENTIRE FILE IS BACK END!
#include "tr_local.h"
Functions
void Tess_EndBegin ()
Tess_EndBegin.
void Tess_CheckOverflow (int verts, int indexes)
Tess_CheckOverflow.
void Tess_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color, float s1, float t1, float s2, float t2)
Tess_AddQuadStampExt.
void Tess_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color)
Tess_AddQuadStamp.
void Tess_AddQuadStampExt2 (vec4_t quadVerts[4], const vec4_t color, float s1, float t1, float s2, float t2, qboolean calcNormals)
Tess_AddQuadStampExt2.
void Tess_AddQuadStamp2 (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2.
void Tess_AddQuadStamp2WithNormals (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2WithNormals.
void Tess_AddTetrahedron (vec4_t tetraVerts[4], const vec4_t color)
Tess_AddTetrahedron.
void Tess_AddCube (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCube.
void Tess_AddCubeWithNormals (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCubeWithNormals.
void Tess_UpdateVBOs (uint32_t attribBits)
Update the default VBO to replace the client side vertex arrays.
void Tess_InstantQuad (vec4_t quadVerts[4])
Tess_InstantQuad.
static void Tess_SurfaceSplash (void)
Tess_SurfaceSplash.
static void Tess_SurfaceSprite (void)
Tess_SurfaceSprite.
static void VectorArrayNormalize (vec4_t *normals, unsigned int count)
The inputs to this routing seem to always be close to length = 1.0 (about 0.6 to 2.0) This means that we don't have to worry about zero length or enormously long vectors.
static void Tess_SurfacePolychain (srfPoly_t *p)
Tess_SurfacePolychain.
void Tess_SurfacePolybuffer (srfPolyBuffer_t *surf)
Tess_SurfacePolybuffer.
void Tess_SurfaceDecal (srfDecal_t *srf)
Decal surfaces.
static void Tess_DrawCurrent ()
Tess_DrawCurrent.
static void Tess_SurfaceFace (srfSurfaceFace_t *srf)
Tess_SurfaceFace.
static void Tess_SurfaceGrid (srfGridMesh_t *srf)
Tess_SurfaceGrid.
static void Tess_SurfaceTriangles (srfTriangles_t *srf)
Tess_SurfaceTriangles.
static void Tess_SurfaceFoliage (srfFoliage_t *srf)
Tess_SurfaceFoliage.
static void Tess_SurfaceBeam (void)
Tess_SurfaceBeam.
static void Tess_DoRailCore (const vec3_t start, const vec3_t end, const vec3_t up, float len, float spanWidth)
Tess_DoRailCore.
static void Tess_DoRailDiscs (int numSegs, const vec3_t start, const vec3_t dir, const vec3_t right, const vec3_t up)
Tess_DoRailDiscs.
static void Tess_SurfaceRailRings (void)
Tess_SurfaceRailRings.
static void Tess_SurfaceRailCore (void)
Tess_SurfaceRailCore.
static void Tess_SurfaceLightningBolt (void)
Tess_SurfaceLightningBolt.
static void Tess_SurfaceMDV (mdvSurface_t *srf)
Tess_SurfaceMDV.
static void Tess_SurfaceMD5 (md5Surface_t *srf)
Tess_SurfaceMD5.
static void Tess_SurfaceAxis (void)
Draws x/y/z lines from the origin for orientation debugging.
static void Tess_SurfaceEntity (surfaceType_t *surfType)
Entities that have a single procedurally generated surface.
static void Tess_SurfaceBad (surfaceType_t *surfType)
Tess_SurfaceBad.
static void Tess_SurfaceFlare (srfFlare_t *surf)
Tess_SurfaceFlare.
static void Tess_SurfaceVBOMesh (srfVBOMesh_t *srf)
Tess_SurfaceVBOMesh.
void Tess_SurfaceVBOMDVMesh (srfVBOMDVMesh_t *surface)
Tess_SurfaceVBOMDVMesh.
static void Tess_SurfaceVBOMD5Mesh (srfVBOMD5Mesh_t *srf)
Tess_SurfaceVBOMD5Mesh.
static void Tess_SurfaceSkip (void *surf)
Tess_SurfaceSkip.
Variables
void(* rb_surfaceTable [SF_NUM_SURFACE_TYPES])(void *)
Detailed Description
THIS ENTIRE FILE IS BACK END!
backEnd.currentEntity will be valid.
Tess_Begin has already been called for the surface's shader.
The modelview matrix will be set.
It is safe to actually issue drawing commands here if you don't want to use the shader system.
Definition in file tr_surface.c.
Function Documentation
void Tess_AddCube (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCube.
Parameters
[in] position
[in] minSize
[in] maxSize
[in] color
Definition at line 358 of file tr_surface.c.
Referenced by R_InitUnitCubeVBO(), R_LoadNodesAndLeafs(), R_SetupLightFrustum(), RB_RenderDebugUtils(), RenderEntityOcclusionVolume(), and RenderLightOcclusionVolume().
void Tess_AddCubeWithNormals (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCubeWithNormals.
Parameters
[in] position
[in] minSize
[in] maxSize
[in] color
Definition at line 411 of file tr_surface.c.
Referenced by RB_RenderDebugUtils().
void Tess_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color)
Tess_AddQuadStamp.
Parameters
[in] origin
[in] left
[in] up
[in] color
Definition at line 199 of file tr_surface.c.
Referenced by AutospriteDeform(), RB_DrawSun(), Tess_SurfaceSplash(), and Tess_SurfaceSprite().
void Tess_AddQuadStamp2 (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2.
Parameters
[in] quadVerts
[in] color
Definition at line 294 of file tr_surface.c.
Referenced by R_SetupLightFrustum(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderLightOcclusionVolume(), and Tess_AddCube().
void Tess_AddQuadStamp2WithNormals (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2WithNormals.
Parameters
[in] quadVerts
[in] color
Definition at line 304 of file tr_surface.c.
Referenced by Tess_AddCubeWithNormals().
void Tess_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color, float s1, float t1, float s2, float t2)
Tess_AddQuadStampExt.
Parameters
[in] origin
[in] left
[in] up
[in] color
[in] s1
[in] t1
[in] s2
[in] t2
Definition at line 109 of file tr_surface.c.
Referenced by DeformText(), RB_RenderDebugUtils(), and Tess_AddQuadStamp().
void Tess_AddQuadStampExt2 (vec4_t quadVerts[4], const vec4_t color, float s1, float t1, float s2, float t2, qboolean calcNormals)
Tess_AddQuadStampExt2.
Parameters
[in] quadVerts
[in] color
[in] s1
[in] t1
[in] s2
[in] t2
[in] calcNormals
Definition at line 214 of file tr_surface.c.
Referenced by Tess_AddQuadStamp2(), and Tess_AddQuadStamp2WithNormals().
void Tess_AddTetrahedron (vec4_t tetraVerts[4], const vec4_t color)
Tess_AddTetrahedron.
Parameters
[in] tetraVerts
[in] color
Definition at line 314 of file tr_surface.c.
Referenced by RB_RenderDebugUtils().
void Tess_CheckOverflow (int verts, int indexes)
Tess_CheckOverflow.
Parameters
[in] verts
[in] indexes
Definition at line 64 of file tr_surface.c.
Referenced by RB_Draw2dPolys(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), Tess_AddQuadStampExt(), Tess_AddQuadStampExt2(), Tess_AddTetrahedron(), Tess_DoRailDiscs(), Tess_MDM_SurfaceAnim(), Tess_SurfaceAxis(), Tess_SurfaceDecal(), Tess_SurfaceFace(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), Tess_SurfaceMD5(), Tess_SurfaceMDV(), Tess_SurfacePolybuffer(), Tess_SurfacePolychain(), and Tess_SurfaceTriangles().
static void Tess_DoRailCore (const vec3_t start, const vec3_t end, const vec3_t up, float len, float spanWidth) static
Tess_DoRailCore.
Parameters
[in] start
[in] end
[in] up
[in] len
[in] spanWidth
Todo:
: use quad stamp?
Definition at line 1492 of file tr_surface.c.
Referenced by Tess_SurfaceLightningBolt(), and Tess_SurfaceRailCore().
static void Tess_DoRailDiscs (int numSegs, const vec3_t start, const vec3_t dir, const vec3_t right, const vec3_t up) static
Tess_DoRailDiscs.
Parameters
[in] numSegs
[in] start
[in] dir
[in] right
[in] up
Definition at line 1562 of file tr_surface.c.
Referenced by Tess_SurfaceRailRings().
static void Tess_DrawCurrent () static
Tess_DrawCurrent.
Definition at line 954 of file tr_surface.c.
Referenced by Tess_SurfaceFace(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), and Tess_SurfaceTriangles().
void Tess_EndBegin ()
Tess_EndBegin.
Definition at line 52 of file tr_surface.c.
Referenced by Tess_CheckOverflow(), Tess_DrawCurrent(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFlare(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), and Tess_SurfaceVBOMesh().
void Tess_InstantQuad (vec4_t quadVerts[4])
Tess_InstantQuad.
Parameters
[in] quadVerts
Definition at line 558 of file tr_surface.c.
Referenced by RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RB_ShowImages(), and Render_lightVolume().
static void Tess_SurfaceAxis (void) static
Draws x/y/z lines from the origin for orientation debugging.
Definition at line 2080 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
static void Tess_SurfaceBad (surfaceType_t * surfType) static
Tess_SurfaceBad.
Parameters
surfType - unused
Definition at line 2180 of file tr_surface.c.
static void Tess_SurfaceBeam (void) static
Tess_SurfaceBeam.
Todo:
rewrite without glBegin/glEnd
Todo:
rewrite without glBegin/glEnd
Definition at line 1408 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
void Tess_SurfaceDecal (srfDecal_t * srf)
Decal surfaces.
Parameters
[in] srf
Definition at line 912 of file tr_surface.c.
static void Tess_SurfaceEntity (surfaceType_t * surfType) static
Entities that have a single procedurally generated surface.
Parameters
surfType - unused
Definition at line 2136 of file tr_surface.c.
static void Tess_SurfaceFace (srfSurfaceFace_t * srf) static
Tess_SurfaceFace.
Parameters
[in] srf
Definition at line 973 of file tr_surface.c.
static void Tess_SurfaceFlare (srfFlare_t * surf) static
Tess_SurfaceFlare.
Parameters
[in] surf
Definition at line 2191 of file tr_surface.c.
static void Tess_SurfaceFoliage (srfFoliage_t * srf) static
Tess_SurfaceFoliage.
Parameters
[in] srf
Todo:
: r1?
Todo:
: r1?
Definition at line 1248 of file tr_surface.c.
static void Tess_SurfaceGrid (srfGridMesh_t * srf) static
Tess_SurfaceGrid.
Parameters
[in] srf
Definition at line 1067 of file tr_surface.c.
static void Tess_SurfaceLightningBolt (void) static
Tess_SurfaceLightningBolt.
Definition at line 1701 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
static void Tess_SurfaceMD5 (md5Surface_t * srf) static
Tess_SurfaceMD5.
Parameters
[in] srf
Definition at line 1890 of file tr_surface.c.
static void Tess_SurfaceMDV (mdvSurface_t * srf) static
Tess_SurfaceMDV.
Parameters
srf
Definition at line 1744 of file tr_surface.c.
void Tess_SurfacePolybuffer (srfPolyBuffer_t * surf)
Tess_SurfacePolybuffer.
Parameters
[in] surf
Definition at line 861 of file tr_surface.c.
static void Tess_SurfacePolychain (srfPoly_t * p) static
Tess_SurfacePolychain.
Parameters
[in] p
Definition at line 766 of file tr_surface.c.
static void Tess_SurfaceRailCore (void) static
Tess_SurfaceRailCore.
Definition at line 1668 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
static void Tess_SurfaceRailRings (void) static
Tess_SurfaceRailRings.
Definition at line 1634 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
static void Tess_SurfaceSkip (void * surf) static
Tess_SurfaceSkip.
Parameters
surf - dummy function for SF_SKIP
Definition at line 2373 of file tr_surface.c.
static void Tess_SurfaceSplash (void) static
Tess_SurfaceSplash.
Definition at line 633 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
static void Tess_SurfaceSprite (void) static
Tess_SurfaceSprite.
Definition at line 662 of file tr_surface.c.
Referenced by Tess_SurfaceEntity().
static void Tess_SurfaceTriangles (srfTriangles_t * srf) static
Tess_SurfaceTriangles.
Parameters
srf
Definition at line 1158 of file tr_surface.c.
static void Tess_SurfaceVBOMD5Mesh (srfVBOMD5Mesh_t * srf) static
Tess_SurfaceVBOMD5Mesh.
Parameters
[in] srf
Definition at line 2298 of file tr_surface.c.
void Tess_SurfaceVBOMDVMesh (srfVBOMDVMesh_t * surface)
Tess_SurfaceVBOMDVMesh.
Parameters
[in] surface
Definition at line 2249 of file tr_surface.c.
static void Tess_SurfaceVBOMesh (srfVBOMesh_t * srf) static
Tess_SurfaceVBOMesh.
Parameters
[in] srf
Definition at line 2225 of file tr_surface.c.
void Tess_UpdateVBOs (uint32_t attribBits)
Update the default VBO to replace the client side vertex arrays.
Parameters
[in] attribBits
Definition at line 461 of file tr_surface.c.
Referenced by BuildCloudData(), DrawSkyBox(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RE_StretchRaw(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), and Tess_InstantQuad().
static void VectorArrayNormalize (vec4_t * normals, unsigned int count) static
The inputs to this routing seem to always be close to length = 1.0 (about 0.6 to 2.0) This means that we don't have to worry about zero length or enormously long vectors.
Parameters
[in] normals
[in] count
Definition at line 709 of file tr_surface.c.
Referenced by Tess_SurfaceMDV(), and Tess_SurfacePolychain().
Variable Documentation
void(* rb_surfaceTable[SF_NUM_SURFACE_TYPES])(void *)
Initial value:
=
{
    (void (*)(void *))Tess_SurfaceBad,
    (void (*)(void *))Tess_SurfaceSkip,
    (void (*)(void *))Tess_SurfaceFace,
    (void (*)(void *))Tess_SurfaceGrid,
    (void (*)(void *))Tess_SurfaceTriangles,
    (void (*)(void *))Tess_SurfaceFoliage,
    (void (*)(void *))Tess_SurfacePolychain,
    (void (*)(void *))Tess_SurfacePolybuffer,
    (void (*)(void *))Tess_SurfaceDecal,
    (void (*)(void *))Tess_SurfaceMDV,
    (void (*)(void *))Tess_MDM_SurfaceAnim,
    (void (*)(void *))Tess_SurfaceMD5,
    (void (*)(void *))Tess_SurfaceFlare,
    (void (*)(void *))Tess_SurfaceEntity,
    (void (*)(void *))Tess_SurfaceVBOMesh,
    (void (*)(void *))Tess_SurfaceVBOMD5Mesh,
    (void (*)(void *))Tess_SurfaceVBOMDMMesh,
    (void (*)(void *))Tess_SurfaceVBOMDVMesh
}
Definition at line 2378 of file tr_surface.c.