ET: Legacy: src/renderer2/tr_model.c File Reference
tr_model.c File Reference
Model loading and caching.
#include "tr_local.h"
Functions
qboolean R_LoadMD3 (model_t *mod, int lod, void *buffer, int bufferSize, const char *name)
R_LoadMD3.
qboolean R_LoadMDC (model_t *mod, int lod, void *buffer, int bufferSize, const char *name)
R_LoadMDC.
qboolean R_LoadMDM (model_t *mod, void *buffer, const char *name)
R_LoadMDM.
static qboolean R_LoadMDX (model_t *mod, void *buffer, const char *name)
R_LoadMDX.
qboolean R_LoadMD5 (model_t *mod, byte *buffer, int bufferSize, const char *name)
qboolean R_LoadPSK (model_t *mod, byte *buffer, int bufferSize, const char *name)
model_t * R_GetModelByHandle (qhandle_t hModel)
R_GetModelByHandle.
model_t * R_AllocModel (void)
R_AllocModel.
qhandle_t RE_RegisterModel (const char *name)
Loads in a model for the given name.
void RE_BeginRegistration (glconfig_t *glconfigOut)
RE_BeginRegistration.
void R_ModelInit (void)
R_ModelInit.
void R_Modellist_f (void)
R_Modellist_f.
static int R_GetTag (mdvModel_t *model, int frame, const char *_tagName, int startTagIndex, mdvTag_t **outTag)
R_GetTag.
int RE_LerpTagQ3A (orientation_t *tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char *tagNameIn)
RE_LerpTagQ3A.
int RE_LerpTagET (orientation_t *tag, const refEntity_t *refent, const char *tagNameIn, int startIndex)
RE_LerpTagET.
int RE_BoneIndex (qhandle_t hModel, const char *boneName)
RE_BoneIndex.
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
R_ModelBounds.
Detailed Description
Model loading and caching.
Definition in file tr_model.c.
Function Documentation
model_t* R_AllocModel (void)
R_AllocModel.
[in] R_AllocModel
Returns
Definition at line 74 of file tr_model.c.
model_t* R_GetModelByHandle (qhandle_t hModel)
R_GetModelByHandle.
Parameters
[in] hModel
Returns
Definition at line 53 of file tr_model.c.
static int R_GetTag (mdvModel_t * model, int frame, const char * _tagName, int startTagIndex, mdvTag_t ** outTag) static
R_GetTag.
Parameters
[in] model
[in] frame
[in] _tagName
[in] startTagIndex
[out] outTag
Returns
Definition at line 651 of file tr_model.c.
Referenced by RE_LerpTagET(), and RE_LerpTagQ3A().
qboolean R_LoadMD3 (model_t * mod, int lod, void * buffer, int bufferSize, const char * modName)
R_LoadMD3.
Parameters
[in,out] mod
[in] lod
[in,out] buffer
bufferSize - unused
[in] modName
Returns
Definition at line 423 of file tr_model_md3.c.
Referenced by RE_RegisterModel().
qboolean R_LoadMD5 (model_t * mod, byte * buffer, int bufferSize, const char * name)
Referenced by RE_RegisterModel().
qboolean R_LoadMDC (model_t * mod, int lod, void * buffer, int bufferSize, const char * modName)
R_LoadMDC.
Parameters
[in,out] mod
[in] lod
[in,out] buffer
bufferSize - unused
[in] modName
Returns
Definition at line 364 of file tr_model_mdc.c.
Referenced by RE_RegisterModel().
static qboolean R_LoadMDM (model_t * mod, void * buffer, const char * name)
R_LoadMDM.
Parameters
[in,out] mod
[in,out] buffer
[in] name
Returns
Definition at line 1536 of file tr_model.c.
Referenced by RE_RegisterModel().
static qboolean R_LoadMDX (model_t * mod, void * buffer, const char * name) static
R_LoadMDX.
Parameters
[in,out] mod
[out] buffer
[in] name
Returns
Definition at line 340 of file tr_model.c.
Referenced by RE_RegisterModel().
qboolean R_LoadPSK (model_t * mod, byte * buffer, int bufferSize, const char * name)
Referenced by RE_RegisterModel().
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
R_ModelBounds.
Parameters
[in] handle
[out] mins
[out] maxs
Definition at line 945 of file tr_model.c.
void R_ModelInit (void)
R_ModelInit.
Definition at line 536 of file tr_model.c.
void R_Modellist_f (void)
R_Modellist_f.
Definition at line 557 of file tr_model.c.
void RE_BeginRegistration (glconfig_t * glconfigOut)
RE_BeginRegistration.
Parameters
[out] glconfigOut
Definition at line 490 of file tr_model.c.
int RE_BoneIndex (qhandle_t hModel, const char * boneName)
RE_BoneIndex.
Parameters
[in] hModel
[in] boneName
Returns
Definition at line 911 of file tr_model.c.
Referenced by GetRefAPI(), and RE_LerpTagET().
int RE_LerpTagET (orientation_t * tag, const refEntity_t * refent, const char * tagNameIn, int startIndex)
RE_LerpTagET.
Parameters
[in,out] tag
[in] refent
[in] tagNameIn
[in] startIndex
Returns
Todo:
: retval is reassigned before used, does it was intended ?
Definition at line 750 of file tr_model.c.
Referenced by GetRefAPI().
int RE_LerpTagQ3A (orientation_t * tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char * tagNameIn)
RE_LerpTagQ3A.
Parameters
[in,out] tag
[in] handle
[in] startFrame
[in] endFrame
[in] frac
[in] tagNameIn
Returns
Note
Unused
Todo:
: retval is reassigned before used, does it was intended ?
Definition at line 695 of file tr_model.c.
qhandle_t RE_RegisterModel (const char * name)
Loads in a model for the given name.
Parameters
[in] name
Returns
Zero will be returned if the model fails to load. An entry will be retained for failed models as an optimization to prevent disk rescanning if they are asked for again.
Todo:
: catch shader case earlier and avoid i/o (mod code?)
Definition at line 100 of file tr_model.c.