ET: Legacy: src/renderer2/tr_world.c File Reference
tr_world.c File Reference
#include "tr_local.h"
Functions
static qboolean R_CullSurface (surfaceType_t *surface, shader_t *shader, int *frontFace)
Tries to back face cull surfaces before they are lighted or added to the sorting list.
static qboolean R_LightSurfaceGeneric (srfGeneric_t *face, trRefLight_t *light, byte *cubeSideBits)
R_LightSurfaceGeneric.
static void R_AddInteractionSurface (bspSurface_t *surf, trRefLight_t *light)
R_AddInteractionSurface.
static void R_AddWorldSurface (bspSurface_t *surf, int decalBits)
R_AddWorldSurface.
static void R_AddBrushModelSurface (bspSurface_t *surf, shader_t *customShader, int fogIndex)
R_AddBrushModelSurface.
void R_AddBSPModelSurfaces (trRefEntity_t *ent)
R_AddBSPModelSurfaces.
static void R_AddLeafSurfaces (bspNode_t *node, int decalBits)
R_AddLeafSurfaces.
static void R_RecursiveWorldNode (bspNode_t *node, int planeBits, int decalBits)
R_RecursiveWorldNode.
static void R_RecursiveInteractionNode (bspNode_t *node, trRefLight_t *light, int planeBits)
R_RecursiveInteractionNode.
static bspNode_t * R_PointInLeaf (const vec3_t p)
R_PointInLeaf.
static const byte * R_ClusterPVS (int cluster)
R_ClusterPVS.
qboolean R_inPVS (const vec3_t p1, const vec3_t p2)
R_inPVS.
static void R_MarkLeaves (void)
Mark the leaves and nodes that are in the PVS for the current.
static void DrawLeaf (bspNode_t *node, int decalBits)
DrawLeaf.
static qboolean InsideViewFrustum (bspNode_t *node, int planeBits)
InsideViewFrustum.
static void IssueOcclusionQuery (link_t *queue, bspNode_t *node, qboolean resetMultiQueryLink)
IssueOcclusionQuery.
static void IssueMultiOcclusionQueries (link_t *multiQueue, link_t *individualQueue)
IssueMultiOcclusionQueries.
static GLint ResultAvailable (bspNode_t *node)
ResultAvailable.
static void GetOcclusionQueryResult (bspNode_t *node)
GetOcclusionQueryResult.
static void PullUpVisibility (bspNode_t *node)
PullUpVisibility.
static void TraverseNode (link_t *distanceQueue, bspNode_t *node)
TraverseNode.
static void BuildNodeTraversalStackPost_r (bspNode_t *node)
BuildNodeTraversalStackPost_r.
static qboolean WasVisible (bspNode_t *node)
WasVisible.
static qboolean QueryReasonable (bspNode_t *node)
QueryReasonable.
static void R_CoherentHierachicalCulling ()
R_CoherentHierachicalCulling.
void R_AddWorldSurfaces (void)
R_AddWorldSurfaces.
void R_AddWorldInteractions (trRefLight_t *light)
R_AddWorldInteractions.
void R_AddPrecachedWorldInteractions (trRefLight_t *light)
R_AddPrecachedWorldInteractions.
Function Documentation
static void BuildNodeTraversalStackPost_r (bspNode_t * node) static
BuildNodeTraversalStackPost_r.
Parameters
[in,out] node
Definition at line 1926 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static void DrawLeaf (bspNode_t * node, int decalBits) static
DrawLeaf.
Parameters
[in] node
[in] decalBits
Definition at line 1373 of file tr_world.c.
Referenced by BuildNodeTraversalStackPost_r().
static void GetOcclusionQueryResult (bspNode_t * node) static
GetOcclusionQueryResult.
Parameters
[in,out] node
Definition at line 1751 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static qboolean InsideViewFrustum (bspNode_t * node, int planeBits) static
InsideViewFrustum.
Parameters
[in] node
[in] planeBits
Returns
Definition at line 1431 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static void IssueMultiOcclusionQueries (link_t * multiQueue, link_t * individualQueue) static
IssueMultiOcclusionQueries.
Parameters
[in] multiQueue
[in] individualQueue
Definition at line 1621 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static void IssueOcclusionQuery (link_t * queue, bspNode_t * node, qboolean resetMultiQueryLink) static
IssueOcclusionQuery.
Parameters
[in] queue
[in,out] node
[in] resetMultiQueryLink
Definition at line 1543 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static void PullUpVisibility (bspNode_t * node) static
PullUpVisibility.
Parameters
[in] node
Definition at line 1802 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static qboolean QueryReasonable (bspNode_t * node) static
QueryReasonable.
Parameters
[in] node
Returns
Definition at line 1988 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static void R_AddBrushModelSurface (bspSurface_t * surf, shader_t * customShader, int fogIndex) static
R_AddBrushModelSurface.
Parameters
[in,out] surf
[in] customShader
[in] fogIndex
Definition at line 398 of file tr_world.c.
Referenced by R_AddBSPModelSurfaces().
void R_AddBSPModelSurfaces (trRefEntity_t * ent)
R_AddBSPModelSurfaces.
Parameters
[in,out] ent
Definition at line 428 of file tr_world.c.
Referenced by R_AddEntitySurfaces().
static void R_AddInteractionSurface (bspSurface_t * surf, trRefLight_t * light) static
R_AddInteractionSurface.
Parameters
[in,out] surf
[in] light
Definition at line 263 of file tr_world.c.
Referenced by R_RecursiveInteractionNode().
static void R_AddLeafSurfaces (bspNode_t * node, int decalBits) static
R_AddLeafSurfaces.
Parameters
[in] node
[in] decalBits
Definition at line 553 of file tr_world.c.
Referenced by R_AddWorldSurfaces(), R_MarkLeaves(), and R_RecursiveWorldNode().
void R_AddPrecachedWorldInteractions (trRefLight_t * light)
R_AddPrecachedWorldInteractions.
Parameters
[in] light
Definition at line 2507 of file tr_world.c.
Referenced by R_AddLightInteractions().
void R_AddWorldInteractions (trRefLight_t * light)
R_AddWorldInteractions.
Parameters
[in] light
Definition at line 2484 of file tr_world.c.
Referenced by R_AddLightInteractions().
static void R_AddWorldSurface (bspSurface_t * surf, int decalBits) static
R_AddWorldSurface.
Parameters
[in,out] surf
[in] decalBits
Definition at line 336 of file tr_world.c.
Referenced by DrawLeaf(), and R_AddLeafSurfaces().
void R_AddWorldSurfaces (void)
R_AddWorldSurfaces.
Definition at line 2395 of file tr_world.c.
static const byte* R_ClusterPVS (int cluster) static
R_ClusterPVS.
Parameters
[in] cluster
Returns
Definition at line 832 of file tr_world.c.
Referenced by R_inPVS(), and R_MarkLeaves().
static void R_CoherentHierachicalCulling () static
R_CoherentHierachicalCulling.
wasVisible && !clipsNearPlane)
Definition at line 2002 of file tr_world.c.
Referenced by R_AddWorldSurfaces().
static qboolean R_CullSurface (surfaceType_t * surface, shader_t * shader, int * frontFace) static
Tries to back face cull surfaces before they are lighted or added to the sorting list.
This will also allow mirrors on both sides of a model without recursion.
Parameters
[in] surface
[in] shader
[out] frontFace
Returns
Definition at line 132 of file tr_world.c.
Referenced by R_AddBrushModelSurface(), and R_AddWorldSurface().
qboolean R_inPVS (const vec3_t p1, const vec3_t p2)
R_inPVS.
Parameters
[in] p1
[in] p2
Returns
Definition at line 853 of file tr_world.c.
static qboolean R_LightSurfaceGeneric (srfGeneric_t * face, trRefLight_t * light, byte * cubeSideBits) static
R_LightSurfaceGeneric.
Parameters
[in] face
[in] light
[out] cubeSideBits
Returns
Definition at line 234 of file tr_world.c.
Referenced by R_AddInteractionSurface().
static void R_MarkLeaves (void) static
Mark the leaves and nodes that are in the PVS for the current.
Definition at line 1234 of file tr_world.c.
Referenced by R_AddWorldSurfaces().
static bspNode_t* R_PointInLeaf (const vec3_t p) static
R_PointInLeaf.
Parameters
[in] p
Returns
Definition at line 794 of file tr_world.c.
Referenced by R_inPVS(), and R_MarkLeaves().
static void R_RecursiveInteractionNode (bspNode_t * node, trRefLight_t * light, int planeBits) static
R_RecursiveInteractionNode.
Parameters
[in,out] node
[in] light
[in] planeBits
Definition at line 693 of file tr_world.c.
Referenced by R_AddWorldInteractions().
static void R_RecursiveWorldNode (bspNode_t * node, int planeBits, int decalBits) static
R_RecursiveWorldNode.
Parameters
[in] node
[in] planeBits
[in] decalBits
Definition at line 606 of file tr_world.c.
Referenced by R_AddWorldSurfaces().
static GLint ResultAvailable (bspNode_t * node) static
ResultAvailable.
Parameters
[in] node
Returns
Definition at line 1731 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static void TraverseNode (link_t * distanceQueue, bspNode_t * node) static
TraverseNode.
Parameters
[in] distanceQueue
[in] node
Definition at line 1871 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().
static qboolean WasVisible (bspNode_t * node) static
WasVisible.
Parameters
[in] node
Returns
Definition at line 1974 of file tr_world.c.
Referenced by R_CoherentHierachicalCulling().