ET: Legacy: src/renderer2/tr_mesh.c File Reference
tr_mesh.c File Reference
Triangle model functions.
#include "tr_local.h"
Functions
static void R_CullMDV (mdvModel_t *model, trRefEntity_t *ent)
R_CullMDV.
int R_ComputeLOD (trRefEntity_t *ent)
R_ComputeLOD.
static shader_t * GetMDVSurfaceShader (const trRefEntity_t *ent, mdvSurface_t *mdvSurface)
GetMDVSurfaceShader.
void R_AddMDVSurfaces (trRefEntity_t *ent)
R_AddMDVSurfaces.
void R_AddMDVInteractions (trRefEntity_t *ent, trRefLight_t *light)
R_AddMDVInteractions.
Detailed Description
Triangle model functions.
Definition in file tr_mesh.c.
Function Documentation
static shader_t* GetMDVSurfaceShader (const trRefEntity_t * ent, mdvSurface_t * mdvSurface) static
GetMDVSurfaceShader.
Parameters
[in] ent
[in] mdvSurface
Returns
Definition at line 213 of file tr_mesh.c.
Referenced by R_AddMDVInteractions(), and R_AddMDVSurfaces().
void R_AddMDVInteractions (trRefEntity_t * ent, trRefLight_t * light)
R_AddMDVInteractions.
Parameters
[in] ent
[in] light
Definition at line 368 of file tr_mesh.c.
Referenced by R_AddEntityInteractions().
void R_AddMDVSurfaces (trRefEntity_t * ent)
R_AddMDVSurfaces.
Parameters
[in,out] ent
Definition at line 260 of file tr_mesh.c.
Referenced by R_AddEntitySurfaces().
int R_ComputeLOD (trRefEntity_t * ent)
R_ComputeLOD.
Parameters
[in] ent
Returns
Definition at line 142 of file tr_mesh.c.
static void R_CullMDV (mdvModel_t * model, trRefEntity_t * ent) static
R_CullMDV.
Parameters
[in] model
[in,out] ent
Definition at line 44 of file tr_mesh.c.
Referenced by R_AddMDVSurfaces().