ET: Legacy: src/renderer2/tr_light.c File Reference
tr_light.c File Reference
#include "tr_local.h"
Functions
void R_AddBrushModelInteractions (trRefEntity_t *ent, trRefLight_t *light)
Determine which dynamic lights may effect this bmodel.
static void R_SetupEntityLightingGrid (trRefEntity_t *ent, vec3_t forcedOrigin)
R_SetupEntityLightingGrid.
void R_SetupEntityLighting (const trRefdef_t *refdef, trRefEntity_t *ent, vec3_t forcedOrigin)
Calculates all the lighting values that will be used by the Calc_* functions.
void R_SetupLightOrigin (trRefLight_t *light)
R_SetupLightOrigin.
void R_SetupLightLocalBounds (trRefLight_t *light)
R_SetupLightLocalBounds.
void R_SetupLightWorldBounds (trRefLight_t *light)
R_SetupLightWorldBounds.
void R_SetupLightView (trRefLight_t *light)
R_SetupLightView.
void R_SetupLightFrustum (trRefLight_t *light)
R_SetupLightFrustum.
void R_SetupLightProjection (trRefLight_t *light)
R_SetupLightProjection.
qboolean R_AddLightInteraction (trRefLight_t *light, surfaceType_t *surface, shader_t *surfaceShader, byte cubeSideBits, interactionType_t iaType)
R_AddLightInteraction.
static int InteractionCompare (const void *a, const void *b)
Compare function for qsort()
void R_SortInteractions (trRefLight_t *light)
R_SortInteractions.
static void R_IntersectRayPlane (const vec3_t v1, const vec3_t v2, cplane_t *plane, vec3_t res)
R_IntersectRayPlane.
static void R_AddPointToLightScissor (trRefLight_t *light, const vec3_t world)
R_AddPointToLightScissor.
static void R_AddEdgeToLightScissor (trRefLight_t *light, vec3_t local1, vec3_t local2)
R_AddEdgeToLightScissor.
void R_SetupLightScissor (trRefLight_t *light)
Recturns the screen space rectangle taken by the box. (Clips the box to the near plane to have correct results even if the box intersects the near plane)
byte R_CalcLightCubeSideBits (trRefLight_t *light, vec3_t worldBounds[2])
R_CalcLightCubeSideBits.
void R_SetupLightLOD (trRefLight_t *light)
R_SetupLightLOD.
void R_SetupLightShader (trRefLight_t *light)
R_SetupLightShader.
void R_ComputeFinalAttenuation (shaderStage_t *pStage, trRefLight_t *light)
R_ComputeFinalAttenuation.
int R_CullLightPoint (trRefLight_t *light, const vec3_t p)
R_CullLightPoint.
int R_CullLightTriangle (trRefLight_t *light, vec3_t verts[3])
R_CullLightTriangle.
int R_CullLightWorldBounds (trRefLight_t *light, vec3_t worldBounds[2])
R_CullLightWorldBounds.
Function Documentation
static int InteractionCompare (const void * a, const void * b) static
Compare function for qsort()
Parameters
[in] a
[in] b
Returns
Definition at line 1100 of file tr_light.c.
Referenced by R_SortInteractions().
void R_AddBrushModelInteractions (trRefEntity_t * ent, trRefLight_t * light)
Determine which dynamic lights may effect this bmodel.
Parameters
[in] ent
[in] light
Todo:
: do more culling?
Definition at line 43 of file tr_light.c.
Referenced by R_AddEntityInteractions().
static void R_AddEdgeToLightScissor (trRefLight_t * light, vec3_t local1, vec3_t local2) static
R_AddEdgeToLightScissor.
Parameters
[in,out] light
[in] local1
[in] local2
Definition at line 1239 of file tr_light.c.
Referenced by R_SetupLightScissor().
qboolean R_AddLightInteraction (trRefLight_t * light, surfaceType_t * surface, shader_t * surfaceShader, byte cubeSideBits, interactionType_t iaType)
R_AddLightInteraction.
Parameters
[in,out] light
[in] surface
[in] surfaceShader
[in] cubeSideBits
[in] iaType
Returns
Definition at line 1001 of file tr_light.c.
Referenced by R_AddBrushModelInteractions(), R_AddInteractionSurface(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_AddPolygonInteractions(), and R_AddPrecachedWorldInteractions().
static void R_AddPointToLightScissor (trRefLight_t * light, const vec3_t world) static
R_AddPointToLightScissor.
Parameters
[in,out] light
[in] world
Definition at line 1205 of file tr_light.c.
Referenced by R_AddEdgeToLightScissor().
byte R_CalcLightCubeSideBits (trRefLight_t * light, vec3_t worldBounds[2])
R_CalcLightCubeSideBits.
Parameters
[in] light
[in] worldBounds
Returns
Definition at line 1535 of file tr_light.c.
Referenced by R_AddBrushModelInteractions(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_CalcInteractionCubeSideBits(), and R_LightSurfaceGeneric().
void R_ComputeFinalAttenuation (shaderStage_t * pStage, trRefLight_t * light)
R_ComputeFinalAttenuation.
Parameters
[in] pStage
[in] light
Definition at line 1821 of file tr_light.c.
Referenced by Render_lightVolume().
int R_CullLightPoint (trRefLight_t * light, const vec3_t p)
R_CullLightPoint.
Parameters
[in] light
[in] p
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Note
Unused
Definition at line 1840 of file tr_light.c.
int R_CullLightTriangle (trRefLight_t * light, vec3_t verts[3])
R_CullLightTriangle.
Parameters
[in] light
[in] verts
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 1869 of file tr_light.c.
Referenced by UpdateLightTriangles().
int R_CullLightWorldBounds (trRefLight_t * light, vec3_t worldBounds[2])
R_CullLightWorldBounds.
Parameters
[in] light
[in] worldBounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 1895 of file tr_light.c.
Referenced by R_AddBrushModelInteractions(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_CullLightTriangle(), R_LightSurfaceGeneric(), and R_RecursiveAddInteractionNode().
static void R_IntersectRayPlane (const vec3_t v1, const vec3_t v2, cplane_t * plane, vec3_t res) static
R_IntersectRayPlane.
Parameters
[in] v1
[in] v2
[in] plane
[out] res
Definition at line 1189 of file tr_light.c.
Referenced by R_AddEdgeToLightScissor().
void R_SetupEntityLighting (const trRefdef_t * refdef, trRefEntity_t * ent, vec3_t forcedOrigin)
Calculates all the lighting values that will be used by the Calc_* functions.
Parameters
[in] refdef
[in,out] ent
[in] forcedOrigin
Note
R_SetupEntityLightingGrid deals with forcedOrigin
Definition at line 303 of file tr_light.c.
static void R_SetupEntityLightingGrid (trRefEntity_t * ent, vec3_t forcedOrigin) static
R_SetupEntityLightingGrid.
Parameters
[in,out] ent
[in] forcedOrigin
Definition at line 178 of file tr_light.c.
Referenced by R_SetupEntityLighting().
void R_SetupLightFrustum (trRefLight_t * light)
R_SetupLightFrustum.
Parameters
[in,out] light
Definition at line 575 of file tr_light.c.
Referenced by R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightLocalBounds (trRefLight_t * light)
R_SetupLightLocalBounds.
Parameters
[in,out] light
Definition at line 448 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightLOD (trRefLight_t * light)
R_SetupLightLOD.
Parameters
[in,out] light
Definition at line 1702 of file tr_light.c.
Referenced by R_AddLightInteractions().
void R_SetupLightOrigin (trRefLight_t * light)
R_SetupLightOrigin.
Parameters
[in,out] light
Note
Needs finished transformMatrix
Definition at line 409 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightProjection (trRefLight_t * light)
R_SetupLightProjection.
Parameters
[in,out] light
Todo:
?
Todo:
: I don't like hacking the matrix like this, but all attempts to use
Definition at line 830 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightScissor (trRefLight_t * light)
Recturns the screen space rectangle taken by the box. (Clips the box to the near plane to have correct results even if the box intersects the near plane)
recoded from Tenebrae2
Parameters
[in,out] light
Definition at line 1296 of file tr_light.c.
Referenced by R_AddLightInteractions().
void R_SetupLightShader (trRefLight_t * light)
R_SetupLightShader.
Parameters
[in,out] light
Definition at line 1779 of file tr_light.c.
Referenced by R_AddLightInteractions().
void R_SetupLightView (trRefLight_t * light)
R_SetupLightView.
Parameters
[in] light
Definition at line 541 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightWorldBounds (trRefLight_t * light)
R_SetupLightWorldBounds.
Parameters
[in] light
Note
Needs finished transformMatrix
Definition at line 532 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SortInteractions (trRefLight_t * light)
R_SortInteractions.
Parameters
[in] light
Definition at line 1141 of file tr_light.c.
Referenced by R_AddLightInteractions().