ET: Legacy: src/renderer2/tr_backend.c File Reference
tr_backend.c File Reference
#include "tr_local.h"
#include "../renderercommon/tr_public.h"
Macros
#define DRAWSCREENQUAD() Tess_InstantQuad(RB_GetScreenQuad())
#define DRAWVIEWQUAD() Tess_InstantQuad(backEnd.viewParms.viewportVerts)
#define ROTSCALE 0.725f
#define COSAN mx + (float)(cos(angle) * mw)
#define SINAN my + (float)(sin(angle) * mh)
Enumerations
enum renderDrawSurfaces_e { DRAWSURFACES_WORLD_ONLY, DRAWSURFACES_ENTITIES_ONLY, DRAWSURFACES_ALL }
Functions
static void RB_Hyperspace (void)
A player has predicted a teleport, but hasn't arrived yet.
static void SetViewportAndScissor (void)
SetViewportAndScissor.
static void RB_SafeState (void)
RB_SafeState.
static void RB_SetGL2D (void)
RB_SetGL2D.
static vec4_t * RB_GetScreenQuad (void)
RB_GetScreenQuad.
void RB_SetViewMVPM (void)
Set the model view projection matrix to match the ingame view.
static void RB_RenderDrawSurfaces (qboolean opaque, int drawSurfFilter)
RB_RenderDrawSurfaces.
static void Render_lightVolume (interaction_t *ia)
Render_lightVolume.
static int MergeInteractionBounds (const mat4_t lightViewProjectionMatrix, interaction_t *ia, int iaCount, vec3_t bounds[2], qboolean shadowCasters)
Helper function for parallel split shadow mapping.
static void RB_RenderInteractions ()
RB_RenderInteractions.
static void RB_RenderInteractionsShadowMapped ()
RB_RenderInteractionsShadowMapped.
void RB_RenderScreenSpaceAmbientOcclusion ()
RB_RenderScreenSpaceAmbientOcclusion.
void RB_RenderDepthOfField ()
RB_RenderDepthOfField.
void RB_RenderGlobalFog ()
RB_RenderGlobalFog.
void RB_RenderBloom ()
RB_RenderBloom.
void RB_RenderRotoscope (void)
RB_RenderRotoscope.
void RB_CameraPostFX (void)
RB_CameraPostFX.
static void RB_CalculateAdaptation ()
RB_CalculateAdaptation.
static void RenderLightOcclusionVolume (trRefLight_t *light)
RenderLightOcclusionVolume.
static void IssueLightOcclusionQuery (link_t *queue, trRefLight_t *light, qboolean resetMultiQueryLink)
IssueLightOcclusionQuery.
static void IssueLightMultiOcclusionQueries (link_t *multiQueue, link_t *individualQueue)
IssueLightMultiOcclusionQueries.
static int LightOcclusionResultAvailable (trRefLight_t *light)
LightOcclusionResultAvailable.
static void GetLightOcclusionQueryResult (trRefLight_t *light)
GetLightOcclusionQueryResult.
static int LightCompare (const void *a, const void *b)
LightCompare.
void RB_RenderLightOcclusionQueries ()
RB_RenderLightOcclusionQueries.
static void RenderEntityOcclusionVolume (trRefEntity_t *entity)
RenderEntityOcclusionVolume.
static void IssueEntityOcclusionQuery (link_t *queue, trRefEntity_t *entity, qboolean resetMultiQueryLink)
IssueEntityOcclusionQuery.
static void RB_RenderHDRResultToFrameBuffer ()
RB_RenderHDRResultToFrameBuffer.
static void IssueEntityMultiOcclusionQueries (link_t *multiQueue, link_t *individualQueue)
IssueEntityMultiOcclusionQueries.
static int EntityOcclusionResultAvailable (trRefEntity_t *entity)
EntityOcclusionResultAvailable.
static void GetEntityOcclusionQueryResult (trRefEntity_t *entity)
GetEntityOcclusionQueryResult.
static int EntityCompare (const void *a, const void *b)
EntityCompare.
void RB_RenderEntityOcclusionQueries ()
RB_RenderEntityOcclusionQueries.
void RB_RenderBspOcclusionQueries ()
RB_RenderBspOcclusionQueries.
void RB_CollectBspOcclusionQueries ()
RB_CollectBspOcclusionQueries.
static void RB_RenderDebugUtils ()
RB_RenderDebugUtils.
static void RB_RenderViewFront (void)
RB_RenderViewFront.
static void RB_RenderView (void)
RB_RenderView.
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
RE_StretchRaw.
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
RE_UploadCinematic.
const void * RB_SetColor (const void *data)
RB_SetColor.
const void * RB_StretchPic (const void *data)
RB_StretchPic.
const void * RB_Draw2dPolys (const void *data)
RB_Draw2dPolys.
const void * RB_RotatedPic (const void *data)
RB_RotatedPic.
const void * RB_StretchPicGradient (const void *data)
RB_StretchPicGradient.
const void * RB_DrawView (const void *data)
RB_DrawView.
const void * RB_DrawBuffer (const void *data)
RB_DrawBuffer.
void RB_ShowImages (void)
Draw all the images to the screen, on top of whatever was there. This is used to test for texture thrashing.
static void RB_ColorCorrection ()
RB_ColorCorrection.
static void RB_PostProcess ()
RB_PostProcess.
static void RB_CountOverDraw ()
RB_CountOverDraw.
const void * RB_SwapBuffers (const void *data)
RB_SwapBuffers.
const void * RB_RenderToTexture (const void *data)
RB_RenderToTexture.
const void * RB_Finish (const void *data)
RB_Finish.
void RB_ExecuteRenderCommands (const void *data)
This function will be called synchronously if running without smp extensions, or asynchronously by another thread.
Variables
backEndData_t * backEndData
the second one may not be allocated
backEndState_t backEnd
Macro Definition Documentation
#define COSAN mx + (float)(cos(angle) * mw)
Referenced by RB_RotatedPic().
#define DRAWSCREENQUAD () Tess_InstantQuad(RB_GetScreenQuad())
Definition at line 42 of file tr_backend.c.
Referenced by RB_ColorCorrection().
#define DRAWVIEWQUAD () Tess_InstantQuad(backEnd.viewParms.viewportVerts)
Definition at line 43 of file tr_backend.c.
Referenced by RB_CameraPostFX(), RB_RenderBloom(), RB_RenderDepthOfField(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderRotoscope(), and RB_RenderScreenSpaceAmbientOcclusion().
#define ROTSCALE 0.725f
Referenced by RB_RotatedPic().
#define SINAN my + (float)(sin(angle) * mh)
Referenced by RB_RotatedPic().
Enumeration Type Documentation
enum renderDrawSurfaces_e
Enumerator
DRAWSURFACES_WORLD_ONLY
DRAWSURFACES_ENTITIES_ONLY
DRAWSURFACES_ALL
Definition at line 155 of file tr_backend.c.
Function Documentation
static int EntityCompare (const void * a, const void * b) static
EntityCompare.
Parameters
[in] a
[in] b
Returns
Definition at line 3814 of file tr_backend.c.
Referenced by RB_RenderEntityOcclusionQueries().
static int EntityOcclusionResultAvailable (trRefEntity_t * entity) static
EntityOcclusionResultAvailable.
Parameters
[in] entity
Returns
Definition at line 3736 of file tr_backend.c.
Referenced by RB_RenderEntityOcclusionQueries().
static void GetEntityOcclusionQueryResult (trRefEntity_t * entity) static
GetEntityOcclusionQueryResult.
Parameters
[in,out] entity
Definition at line 3761 of file tr_backend.c.
Referenced by RB_RenderEntityOcclusionQueries().
static void GetLightOcclusionQueryResult (trRefLight_t * light) static
GetLightOcclusionQueryResult.
Parameters
[in] light
Definition at line 3101 of file tr_backend.c.
Referenced by RB_RenderLightOcclusionQueries().
static void IssueEntityMultiOcclusionQueries (link_t * multiQueue, link_t * individualQueue) static
IssueEntityMultiOcclusionQueries.
Parameters
[in] multiQueue
[in] individualQueue
Definition at line 3646 of file tr_backend.c.
Referenced by RB_RenderEntityOcclusionQueries().
static void IssueEntityOcclusionQuery (link_t * queue, trRefEntity_t * entity, qboolean resetMultiQueryLink) static
IssueEntityOcclusionQuery.
Parameters
[in] queue
[in,out] entity
[in] resetMultiQueryLink
Definition at line 3547 of file tr_backend.c.
Referenced by RB_RenderEntityOcclusionQueries().
static void IssueLightMultiOcclusionQueries (link_t * multiQueue, link_t * individualQueue) static
IssueLightMultiOcclusionQueries.
Parameters
[in] multiQueue
[in] individualQueue
Definition at line 2986 of file tr_backend.c.
Referenced by RB_RenderLightOcclusionQueries().
static void IssueLightOcclusionQuery (link_t * queue, trRefLight_t * light, qboolean resetMultiQueryLink) static
IssueLightOcclusionQuery.
Parameters
[in] queue
[in] light
[in] resetMultiQueryLink
Definition at line 2932 of file tr_backend.c.
Referenced by RB_RenderLightOcclusionQueries().
static int LightCompare (const void * a, const void * b) static
LightCompare.
Parameters
[in] a
[in] b
Returns
Definition at line 3161 of file tr_backend.c.
Referenced by RB_RenderLightOcclusionQueries().
static int LightOcclusionResultAvailable (trRefLight_t * light) static
LightOcclusionResultAvailable.
Parameters
[in] light
Returns
Definition at line 3076 of file tr_backend.c.
Referenced by RB_RenderLightOcclusionQueries().
static int MergeInteractionBounds (const mat4_t lightViewProjectionMatrix, interaction_t * ia, int iaCount, vec3_t bounds[2], qboolean shadowCasters) static
Helper function for parallel split shadow mapping.
Parameters
[in] lightViewProjectionMatrix
[in] ia
[in] iaCount
[in,out] bounds
[in] shadowCasters
Returns
Definition at line 618 of file tr_backend.c.
Referenced by RB_RenderInteractionsShadowMapped().
static void RB_CalculateAdaptation () static
RB_CalculateAdaptation.
Definition at line 2679 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_CameraPostFX (void)
RB_CameraPostFX.
Definition at line 2602 of file tr_backend.c.
Referenced by RB_RenderView().
void RB_CollectBspOcclusionQueries ()
RB_CollectBspOcclusionQueries.
Todo:
: don't know if it should done like this,
Todo:
: issueOcclusionQuery is never used
Todo:
: j is neither incremented not used,
Todo:
: issueOcclusionQuery is never used
Definition at line 4110 of file tr_backend.c.
Referenced by RB_RenderViewFront().
static void RB_ColorCorrection () static
RB_ColorCorrection.
Definition at line 6869 of file tr_backend.c.
Referenced by RB_PostProcess().
static void RB_CountOverDraw () static
RB_CountOverDraw.
Definition at line 6924 of file tr_backend.c.
Referenced by RB_SwapBuffers().
const void* RB_Draw2dPolys (const void * data)
RB_Draw2dPolys.
Parameters
[in] data
Returns
Definition at line 6508 of file tr_backend.c.
const void* RB_DrawBuffer (const void * data)
RB_DrawBuffer.
Parameters
[in] data
Returns
Definition at line 6781 of file tr_backend.c.
const void* RB_DrawView (const void * data)
RB_DrawView.
Parameters
[in] data
Returns
Definition at line 6754 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
void RB_ExecuteRenderCommands (const void * data)
This function will be called synchronously if running without smp extensions, or asynchronously by another thread.
RB_ExecuteRenderCommands.
Parameters
[in] data
Definition at line 7026 of file tr_backend.c.
const void* RB_Finish (const void * data)
RB_Finish.
Parameters
[in] data
Returns
Definition at line 7010 of file tr_backend.c.
static vec4_t* RB_GetScreenQuad (void) static
RB_GetScreenQuad.
Returns
Definition at line 128 of file tr_backend.c.
static void RB_Hyperspace (void) static
A player has predicted a teleport, but hasn't arrived yet.
Definition at line 48 of file tr_backend.c.
Referenced by RB_RenderViewFront().
static void RB_PostProcess () static
RB_PostProcess.
Definition at line 6896 of file tr_backend.c.
Referenced by RB_SwapBuffers().
void RB_RenderBloom ()
RB_RenderBloom.
Todo:
Definition at line 2400 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderBspOcclusionQueries ()
RB_RenderBspOcclusionQueries.
Definition at line 4032 of file tr_backend.c.
Referenced by RB_RenderViewFront().
static void RB_RenderDebugUtils () static
RB_RenderDebugUtils.
Definition at line 4212 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderDepthOfField ()
RB_RenderDepthOfField.
Definition at line 2229 of file tr_backend.c.
Referenced by RB_RenderViewFront().
static void RB_RenderDrawSurfaces (qboolean opaque, int drawSurfFilter) static
RB_RenderDrawSurfaces.
Parameters
[in] opaque
[in] drawSurfFilter
Definition at line 167 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderEntityOcclusionQueries ()
RB_RenderEntityOcclusionQueries.
Todo:
: never read
Definition at line 3838 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderGlobalFog ()
RB_RenderGlobalFog.
Todo:
: fog->fogParms.density?!.. density dont seem to get any value?!
Definition at line 2292 of file tr_backend.c.
Referenced by RB_RenderViewFront().
static void RB_RenderHDRResultToFrameBuffer () static
RB_RenderHDRResultToFrameBuffer.
Definition at line 3599 of file tr_backend.c.
Referenced by RB_RenderViewFront().
static void RB_RenderInteractions () static
RB_RenderInteractions.
Definition at line 805 of file tr_backend.c.
Referenced by RB_RenderInteractionsShadowMapped(), and RB_RenderViewFront().
static void RB_RenderInteractionsShadowMapped () static
RB_RenderInteractionsShadowMapped.
Definition at line 1035 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderLightOcclusionQueries ()
RB_RenderLightOcclusionQueries.
Definition at line 3185 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderRotoscope (void)
RB_RenderRotoscope.
Definition at line 2561 of file tr_backend.c.
Referenced by RB_RenderViewFront().
void RB_RenderScreenSpaceAmbientOcclusion ()
RB_RenderScreenSpaceAmbientOcclusion.
Definition at line 2181 of file tr_backend.c.
Referenced by RB_RenderViewFront().
const void* RB_RenderToTexture (const void * data)
RB_RenderToTexture.
Parameters
[in] data
Returns
Definition at line 6989 of file tr_backend.c.
static void RB_RenderView (void) static
RB_RenderView.
Definition at line 6153 of file tr_backend.c.
Referenced by RB_DrawView().
static void RB_RenderViewFront (void) static
RB_RenderViewFront.
Todo:
add non EXT_framebuffer_blit code
Definition at line 5784 of file tr_backend.c.
Referenced by RB_RenderView().
const void* RB_RotatedPic (const void * data)
RB_RotatedPic.
Parameters
[in] data
Returns
Definition at line 6566 of file tr_backend.c.
static void RB_SafeState (void) static
RB_SafeState.
Definition at line 82 of file tr_backend.c.
Referenced by RB_RenderInteractionsShadowMapped().
const void* RB_SetColor (const void * data)
RB_SetColor.
Parameters
[in] data
Returns
Definition at line 6392 of file tr_backend.c.
static void RB_SetGL2D (void) static
RB_SetGL2D.
Definition at line 96 of file tr_backend.c.
void RB_SetViewMVPM (void)
Set the model view projection matrix to match the ingame view.
Definition at line 143 of file tr_backend.c.
Referenced by RB_CameraPostFX(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), and Render_lightVolume().
void RB_ShowImages (void)
Draw all the images to the screen, on top of whatever was there. This is used to test for texture thrashing.
Also called by RE_EndRegistration
Definition at line 6805 of file tr_backend.c.
const void* RB_StretchPic (const void * data)
RB_StretchPic.
Parameters
[in] data
Returns
Definition at line 6411 of file tr_backend.c.
const void* RB_StretchPicGradient (const void * data)
RB_StretchPicGradient.
Parameters
[in] data
Returns
Definition at line 6664 of file tr_backend.c.
const void* RB_SwapBuffers (const void * data)
RB_SwapBuffers.
Parameters
[in] data
Returns
Definition at line 6947 of file tr_backend.c.
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
RE_StretchRaw.
Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Todo:
FIXME: not exactly backend Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
Definition at line 6216 of file tr_backend.c.
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
RE_UploadCinematic.
Parameters
w - unused
h - unused
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Definition at line 6350 of file tr_backend.c.
static void Render_lightVolume (interaction_t * ia) static
Render_lightVolume.
Parameters
[in] ia
Todo:
gl_volumetricLightingShader->SetUniform_ShadowMatrix(light->attenuationMatrix);
Definition at line 477 of file tr_backend.c.
Referenced by RB_RenderInteractions(), and RB_RenderInteractionsShadowMapped().
static void RenderEntityOcclusionVolume (trRefEntity_t * entity) static
RenderEntityOcclusionVolume.
Parameters
[in] entity
Definition at line 3463 of file tr_backend.c.
Referenced by IssueEntityMultiOcclusionQueries(), and IssueEntityOcclusionQuery().
static void RenderLightOcclusionVolume (trRefLight_t * light) static
RenderLightOcclusionVolume.
Parameters
[in] light
Definition at line 2782 of file tr_backend.c.
Referenced by IssueLightMultiOcclusionQueries(), and IssueLightOcclusionQuery().
static void SetViewportAndScissor (void) static
SetViewportAndScissor.
Definition at line 67 of file tr_backend.c.
Referenced by RB_RenderViewFront().
Variable Documentation
backEndState_t backEnd
Definition at line 40 of file tr_backend.c.
backEndData_t* backEndData
the second one may not be allocated
Definition at line 39 of file tr_backend.c.