ET: Legacy: src/renderer2/tr_bsp.c File Reference
tr_bsp.c File Reference
Loads and prepares a map file for scene rendering.
#include "tr_local.h"
Macros
#define LIGHTMAP_SIZE 128
#define EQUAL_EPSILON 0.001
#define RADIUS_MULTIPLICATOR 1
#define HASHTABLE_SIZE 7919
#define HASH_USE_EPSILON
#define HASH_XYZ_EPSILON 0.01f
#define HASH_XYZ_EPSILONSPACE_MULTIPLIER 1.f / HASH_XYZ_EPSILON
#define CUBES_MINIMUM_DISTANCE 200.0f
Functions
static void HSVtoRGB (float h, float s, float v, float rgb[3])
HSVtoRGB.
static void R_ColorShiftLightingBytes (byte in[4], byte out[4])
R_ColorShiftLightingBytes.
static void R_ColorShiftLightingFloats (const vec4_t in, vec4_t out)
R_ColorShiftLightingFloats.
float R_ProcessLightmap (byte *pic, int in_padding, int width, int height, byte *pic_out)
R_ProcessLightmap.
static int QDECL LightmapNameCompare (const void *a, const void *b)
LightmapNameCompare.
void LoadRGBEToFloats (const char *name, float **pic, int *width, int *height, qboolean doGamma, qboolean toneMap, qboolean compensate)
LoadRGBEToFloats.
void LoadRGBEToHalfs (const char *name, unsigned short **halfImage, int *width, int *height)
LoadRGBEToHalfs.
static void LoadRGBEToBytes (const char *name, byte **ldrImage, int *width, int *height)
LoadRGBEToBytes.
static void R_LoadLightmapsInternal (lump_t *l, const char *bspName)
R_LoadLightmapsInternal.
static void R_LoadLightmapsExternal (lump_t *l, const char *bspName)
R_LoadLightmapsExternal.
static void R_LoadLightmaps (lump_t *l, const char *bspName)
R_LoadLightmaps.
void RE_SetWorldVisData (const byte *vis)
This is called by the clipmodel subsystem so we can share the 1.8 megs of space in big maps...
static void R_LoadVisibility (lump_t *l)
R_LoadVisibility.
static shader_t * ShaderForShaderNum (int shaderNum)
ShaderForShaderNum.
static void SphereFromBounds (vec3_t mins, vec3_t maxs, vec3_t origin, float *radius)
Creates a bounding sphere from a bounding box.
static void FinishGenericSurface (dsurface_t *ds, srfGeneric_t *gen, vec3_t pt)
Handles final surface classification.
static void ParseFace (dsurface_t *ds, drawVert_t *verts, bspSurface_t *surf, int *indexes)
ParseFace.
static void ParseMesh (dsurface_t *ds, drawVert_t *verts, bspSurface_t *surf)
ParseMesh.
static void ParseTriSurf (dsurface_t *ds, drawVert_t *verts, bspSurface_t *surf, int *indexes)
ParseTriSurf.
static void ParseFoliage (dsurface_t *ds, drawVert_t *verts, bspSurface_t *surf, int *indexes)
Parses a foliage drawsurface.
static void ParseFlare (dsurface_t *ds, drawVert_t *verts, bspSurface_t *surf, int *indexes)
ParseFlare.
int R_MergedWidthPoints (srfGridMesh_t *grid, int offset)
R_MergedWidthPoints.
int R_MergedHeightPoints (srfGridMesh_t *grid, int offset)
R_MergedHeightPoints.
static void R_FixSharedVertexLodError_r (int start, srfGridMesh_t *grid1)
R_FixSharedVertexLodError_r.
static void R_FixSharedVertexLodError (void)
This function assumes that all patches in one group are nicely stitched together for the highest LoD. If this is not the case this function will still do its job but won't fix the highest LoD cracks.
static int R_StitchPatches (int grid1num, int grid2num)
R_StitchPatches.
static int R_TryStitchingPatch (int grid1num)
This function will try to stitch patches in the same LoD group together for the highest LoD.
static void R_StitchAllPatches (void)
R_StitchAllPatches.
static void R_MovePatchSurfacesToHunk (void)
R_MovePatchSurfacesToHunk.
int BSPSurfaceCompare (const void *a, const void *b)
Compare function for qsort()
static void CopyVert (const srfVert_t *in, srfVert_t *out)
CopyVert.
static void R_CreateClusters ()
R_CreateClusters.
static void R_CreateWorldVBO ()
R_CreateWorldVBO.
static void R_CreateSubModelVBOs ()
R_CreateSubModelVBOs.
static void R_LoadSurfaces (lump_t *surfs, lump_t *verts, lump_t *indexLump)
R_LoadSurfaces.
static void R_LoadSubmodels (lump_t *l)
R_LoadSubmodels.
static void R_SetParent (bspNode_t *node, bspNode_t *parent)
R_SetParent.
static void R_LoadNodesAndLeafs (lump_t *nodeLump, lump_t *leafLump)
R_LoadNodesAndLeafs.
static void R_LoadShaders (lump_t *l)
R_LoadShaders.
static void R_LoadMarksurfaces (lump_t *l)
R_LoadMarksurfaces.
static void R_LoadPlanes (lump_t *l)
R_LoadPlanes.
static void R_LoadFogs (lump_t *l, lump_t *brushesLump, lump_t *sidesLump)
R_LoadFogs.
void R_LoadLightGrid (lump_t *l)
R_LoadLightGrid.
qboolean setProjTargetOrigin (char *lightDefs, char *targetname, trRefLight_t *light)
Parses all ents again and sets origin from given targetname null_info ent.
void resetRefLight (trRefLight_t *light)
Resets a static light to default values.
void R_LoadLights (char *lightDefs)
This is extracting classname light and lightJunior entities from bsp into s_worldData.lights.
void R_LoadEntities (lump_t *l)
R_LoadEntities.
qboolean R_GetEntityToken (char *buffer, size_t size)
R_GetEntityToken.
static void R_PrecacheInteraction (trRefLight_t *light, bspSurface_t *surface)
R_PrecacheInteraction.
static qboolean R_PrecacheGenericSurfInteraction (srfGeneric_t *surf, shader_t *shader, trRefLight_t *light)
R_PrecacheGenericSurfInteraction.
static void R_PrecacheInteractionSurface (bspSurface_t *surf, trRefLight_t *light)
R_PrecacheInteractionSurface.
static void R_RecursivePrecacheInteractionNode (bspNode_t *node, trRefLight_t *light)
R_RecursivePrecacheInteractionNode.
static void R_RecursiveAddInteractionNode (bspNode_t *node, trRefLight_t *light)
R_RecursiveAddInteractionNode.
int R_ShadowFrustumCullWorldBounds (int numShadowPlanes, cplane_t *shadowPlanes, vec3_t worldBounds[2])
R_ShadowFrustumCullWorldBounds.
static interactionVBO_t * R_CreateInteractionVBO (trRefLight_t *light)
R_CreateInteractionVBO.
static int InteractionCacheCompare (const void *a, const void *b)
Compare function for qsort()
static int UpdateLightTriangles (const srfVert_t *verts, int numTriangles, srfTriangle_t *triangles, shader_t *surfaceShader, trRefLight_t *light)
UpdateLightTriangles.
static void R_CreateVBOLightMeshes (trRefLight_t *light)
R_CreateVBOLightMeshes.
static void R_CreateVBOShadowMeshes (trRefLight_t *light)
R_CreateVBOShadowMeshes.
static void R_CreateVBOShadowCubeMeshes (trRefLight_t *light)
R_CreateVBOShadowCubeMeshes.
static void R_CalcInteractionCubeSideBits (trRefLight_t *light)
R_CalcInteractionCubeSideBits.
void R_PrecacheInteractions ()
R_PrecacheInteractions.
unsigned int VertexCoordGenerateHash (const vec3_t xyz)
VertexCoordGenerateHash.
vertexHash_t ** NewVertexHashTable (void)
NewVertexHashTable.
void FreeVertexHashTable (vertexHash_t **hashTable)
FreeVertexHashTable.
vertexHash_t * FindVertexInHashTable (vertexHash_t **hashTable, const vec3_t xyz, float distance)
FindVertexInHashTable.
vertexHash_t * AddVertexToHashTable (vertexHash_t **hashTable, vec3_t xyz, void *data)
AddVertexToHashTable.
void GL_BindNearestCubeMap (const vec3_t xyz)
GL_BindNearestCubeMap.
void R_FindTwoNearestCubeMaps (const vec3_t position, cubemapProbe_t **cubeProbe1, cubemapProbe_t **cubeProbe2, float *distance1, float *distance2)
R_FindTwoNearestCubeMaps.
void R_SaveCubeProbes (const char *filename, byte *pixeldata, int width, int height)
This is saving our cube probes to special uncompressed pixeldata tga rgb format.
qboolean R_LoadCubeProbe (int cubeProbeNum, int totalCubeProbes, byte *cubeTemp[6])
This is loading a single cube (6 probes) from our file into cubeTemp.
void R_BuildCubeMaps (void)
R_BuildCubeMaps.
void RE_LoadWorldMap (const char *name)
Called directly from cgame.
Variables
static world_t s_worldData
static int s_lightCount
static growList_t s_interactions
static byte * fileBase
static int c_vboWorldSurfaces
static int c_vboLightSurfaces
static int c_vboShadowSurfaces
Detailed Description
Loads and prepares a map file for scene rendering.
A single entry point: void RE_LoadWorldMap(const char *name);
Definition in file tr_bsp.c.
Macro Definition Documentation
#define CUBES_MINIMUM_DISTANCE 200.0f
Definition at line 8041 of file tr_bsp.c.
Referenced by R_BuildCubeMaps().
#define EQUAL_EPSILON 0.001
Definition at line 2959 of file tr_bsp.c.
#define HASH_USE_EPSILON
Definition at line 7618 of file tr_bsp.c.
#define HASH_XYZ_EPSILON 0.01f
Definition at line 7621 of file tr_bsp.c.
Referenced by FindVertexInHashTable().
#define HASH_XYZ_EPSILONSPACE_MULTIPLIER 1.f / HASH_XYZ_EPSILON
Definition at line 7622 of file tr_bsp.c.
Referenced by VertexCoordGenerateHash().
#define HASHTABLE_SIZE 7919
Definition at line 7617 of file tr_bsp.c.
Referenced by FreeVertexHashTable(), NewVertexHashTable(), and VertexCoordGenerateHash().
#define LIGHTMAP_SIZE 128
Definition at line 735 of file tr_bsp.c.
Referenced by R_LoadLightmapsInternal().
#define RADIUS_MULTIPLICATOR 1
Definition at line 4913 of file tr_bsp.c.
Referenced by R_LoadLights(), and resetRefLight().
Function Documentation
vertexHash_t* AddVertexToHashTable (vertexHash_t ** hashTable, vec3_t xyz, void * data)
AddVertexToHashTable.
Parameters
[in,out] hashTable
[in] xyz
[in] data
Returns
Definition at line 7750 of file tr_bsp.c.
Referenced by R_BuildCubeMaps().
int BSPSurfaceCompare (const void * a, const void * b)
Compare function for qsort()
Parameters
[in] a
[in] b
Returns
Definition at line 2900 of file tr_bsp.c.
Referenced by R_CreateSubModelVBOs(), and R_inPVS().
static void CopyVert (const srfVert_t * in, srfVert_t * out) static
CopyVert.
Parameters
[in] in
[out] out
Definition at line 2933 of file tr_bsp.c.
Referenced by R_CreateSubModelVBOs(), and R_CreateWorldVBO().
vertexHash_t* FindVertexInHashTable (vertexHash_t ** hashTable, const vec3_t xyz, float distance)
FindVertexInHashTable.
Parameters
[in] hashTable
[in] xyz
[in] distance
Returns
Definition at line 7702 of file tr_bsp.c.
Referenced by R_BuildCubeMaps().
static void FinishGenericSurface (dsurface_t * ds, srfGeneric_t * gen, vec3_t pt) static
Handles final surface classification.
Parameters
ds
gen
pt
Definition at line 1128 of file tr_bsp.c.
Referenced by ParseFace(), ParseFoliage(), ParseMesh(), and ParseTriSurf().
void FreeVertexHashTable (vertexHash_t ** hashTable)
FreeVertexHashTable.
Parameters
[in] hashTable
Todo:
: check this..
Definition at line 7678 of file tr_bsp.c.
Referenced by R_ShutdownImages().
void GL_BindNearestCubeMap (const vec3_t xyz)
GL_BindNearestCubeMap.
Parameters
[in] xyz
Definition at line 7783 of file tr_bsp.c.
static void HSVtoRGB (float h, float s, float v, float rgb[3]) static
HSVtoRGB.
Parameters
[in] h
[in] s
[in] v
[out] rgb
Definition at line 60 of file tr_bsp.c.
Referenced by R_ProcessLightmap().
static int InteractionCacheCompare (const void * a, const void * b) static
Compare function for qsort()
Parameters
[in] a
[in] b
Returns
Definition at line 6208 of file tr_bsp.c.
Referenced by R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), and R_CreateVBOShadowMeshes().
static int QDECL LightmapNameCompare (const void * a, const void * b) static
LightmapNameCompare.
Parameters
[in] a
[in] b
Returns
Definition at line 256 of file tr_bsp.c.
Referenced by R_LoadLightmapsExternal().
static void LoadRGBEToBytes (const char * name, byte ** ldrImage, int * width, int * height) static
LoadRGBEToBytes.
Parameters
[in] name
[out] ldrImage
[out] width
[out] height
Definition at line 657 of file tr_bsp.c.
Referenced by R_LoadLightmapsExternal().
void LoadRGBEToFloats (const char * name, float ** pic, int * width, int * height, qboolean doGamma, qboolean toneMap, qboolean compensate)
LoadRGBEToFloats.
Parameters
[in] name
[out] pic
[out] width
[out] height
[in] doGamma
[in] toneMap
[in] compensate
Todo:
XMap2's output is 255 times too high
Definition at line 349 of file tr_bsp.c.
Referenced by LoadRGBEToBytes().
void LoadRGBEToHalfs (const char * name, unsigned short ** halfImage, int * width, int * height)
LoadRGBEToHalfs.
Parameters
name - unused
halfImage - unused
width - unused
height - unused
Note
not implemented
Definition at line 645 of file tr_bsp.c.
Referenced by R_LoadLightmapsExternal().
vertexHash_t** NewVertexHashTable (void)
NewVertexHashTable.
Returns
Definition at line 7665 of file tr_bsp.c.
Referenced by R_BuildCubeMaps().
static void ParseFace (dsurface_t * ds, drawVert_t * verts, bspSurface_t * surf, int * indexes) static
ParseFace.
Parameters
[in] ds
[out] verts
[out] surf
[out] indexes
Definition at line 1149 of file tr_bsp.c.
Referenced by R_LoadSurfaces().
static void ParseFlare (dsurface_t * ds, drawVert_t * verts, bspSurface_t * surf, int * indexes) static
ParseFlare.
Parameters
[in] ds
verts - unused
[out] surf
indexes - unused
Definition at line 1755 of file tr_bsp.c.
Referenced by R_LoadSurfaces().
static void ParseFoliage (dsurface_t * ds, drawVert_t * verts, bspSurface_t * surf, int * indexes) static
Parses a foliage drawsurface.
Parameters
[in] ds
[out] verts
[out] surf
[out] indexes
Definition at line 1643 of file tr_bsp.c.
Referenced by R_LoadSurfaces().
static void ParseMesh (dsurface_t * ds, drawVert_t * verts, bspSurface_t * surf) static
ParseMesh.
Parameters
[in] ds
[out] verts
[out] surf
Definition at line 1325 of file tr_bsp.c.
Referenced by R_LoadSurfaces().
static void ParseTriSurf (dsurface_t * ds, drawVert_t * verts, bspSurface_t * surf, int * indexes) static
ParseTriSurf.
Parameters
[in] ds
[out] verts
[out] surf
[out] indexes
Definition at line 1427 of file tr_bsp.c.
Referenced by R_LoadSurfaces().
void R_BuildCubeMaps (void)
R_BuildCubeMaps.
Todo:
: this doesn't create cubes on important locations
Todo:
: don't use every grid position
Todo:
connect cubeProbe with gridPoint
Definition at line 8046 of file tr_bsp.c.
Referenced by R_BuildCubeMaps_f(), and RE_LoadWorldMap().
static void R_CalcInteractionCubeSideBits (trRefLight_t * light) static
R_CalcInteractionCubeSideBits.
Parameters
[in] light
Definition at line 7413 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
static void R_ColorShiftLightingBytes (byte in[4], byte out[4]) static
R_ColorShiftLightingBytes.
Parameters
[in] in
[out] out
Definition at line 115 of file tr_bsp.c.
Referenced by ParseFoliage(), R_LoadLightGrid(), R_LoadLightmapsInternal(), and R_ProcessLightmap().
static void R_ColorShiftLightingFloats (const vec4_t in, vec4_t out) static
R_ColorShiftLightingFloats.
Parameters
[in] in
[out] out
Definition at line 146 of file tr_bsp.c.
Referenced by ParseFace(), ParseMesh(), and ParseTriSurf().
static void R_CreateClusters () static
R_CreateClusters.
Definition at line 2964 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static interactionVBO_t* R_CreateInteractionVBO (trRefLight_t * light) static
R_CreateInteractionVBO.
Parameters
[in,out] light
Returns
Definition at line 6179 of file tr_bsp.c.
Referenced by R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), and R_CreateVBOShadowMeshes().
static void R_CreateSubModelVBOs () static
R_CreateSubModelVBOs.
Definition at line 3565 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_CreateVBOLightMeshes (trRefLight_t * light) static
R_CreateVBOLightMeshes.
Parameters
[in] light
Definition at line 6331 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
static void R_CreateVBOShadowCubeMeshes (trRefLight_t * light) static
R_CreateVBOShadowCubeMeshes.
Parameters
[in] light
Definition at line 7018 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
static void R_CreateVBOShadowMeshes (trRefLight_t * light) static
R_CreateVBOShadowMeshes.
Parameters
[in] light
Definition at line 6629 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
static void R_CreateWorldVBO () static
R_CreateWorldVBO.
Todo:
move this to somewhere else?
Definition at line 3153 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
void R_FindTwoNearestCubeMaps (const vec3_t position, cubemapProbe_t ** cubeProbe1, cubemapProbe_t ** cubeProbe2, float * distance1, float * distance2)
R_FindTwoNearestCubeMaps.
Parameters
[in] position
[out] cubeProbe1 // nearest
[out] cubeProbe2 // 2nd nearest
Definition at line 7848 of file tr_bsp.c.
Referenced by BindCubeMaps(), R_CreateWorldVBO(), and RB_RenderDebugUtils().
static void R_FixSharedVertexLodError (void) static
This function assumes that all patches in one group are nicely stitched together for the highest LoD. If this is not the case this function will still do its job but won't fix the highest LoD cracks.
Definition at line 2085 of file tr_bsp.c.
static void R_FixSharedVertexLodError_r (int start, srfGridMesh_t * grid1) static
R_FixSharedVertexLodError_r.
Parameters
[in] start
[in] grid1
Note
never sync LoD through grid edges with merged points!
Todo:
FIXME: write generalized version that also avoids cracks between a patch and one that meets half way?
Definition at line 1859 of file tr_bsp.c.
qboolean R_GetEntityToken (char * buffer, size_t size)
R_GetEntityToken.
Parameters
[out] buffer
[in] size
Returns
Definition at line 5616 of file tr_bsp.c.
qboolean R_LoadCubeProbe (int cubeProbeNum, int totalCubeProbes, byte * cubeTemp[6])
This is loading a single cube (6 probes) from our file into cubeTemp.
Parameters
[in] number of cube probe
[in] total cube probes
[in,out] cubeTemp
Definition at line 7957 of file tr_bsp.c.
Referenced by R_BuildCubeMaps().
void R_LoadEntities (lump_t * l)
R_LoadEntities.
Parameters
[in] l
Todo:
: bypass r_ambientScale in R_SetupEntityLighting so map maker can set ambient scale for entities?
Definition at line 5439 of file tr_bsp.c.
static void R_LoadFogs (lump_t * l, lump_t * brushesLump, lump_t * sidesLump) static
R_LoadFogs.
Parameters
[in] l
[in] brushesLump
[in] sidesLump
Definition at line 4483 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
void R_LoadLightGrid (lump_t * l)
R_LoadLightGrid.
Parameters
[in] l
Definition at line 4643 of file tr_bsp.c.
static void R_LoadLightmaps (lump_t * l, const char * bspName) static
R_LoadLightmaps.
Parameters
[in] l
[in] bspName
Definition at line 1006 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadLightmapsExternal (lump_t * l, const char * bspName) static
R_LoadLightmapsExternal.
Parameters
l - unused
[in] bspName
Definition at line 806 of file tr_bsp.c.
Referenced by R_LoadLightmaps().
static void R_LoadLightmapsInternal (lump_t * l, const char * bspName) static
R_LoadLightmapsInternal.
Parameters
[in] l
bspName - unused
Definition at line 741 of file tr_bsp.c.
Referenced by R_LoadLightmaps().
void R_LoadLights (char * lightDefs)
This is extracting classname light and lightJunior entities from bsp into s_worldData.lights.
Parameters
[in] lightDefs FIXME: check parser for missing keys FIXME: Inspect lightJunior (is there a need to assign these to models?) FIXME: spotlights targets FIXME: sun spotlight
FIXME: this might be optimized by more preparsing (f.e. store info_null ents for spotlights at the first time of parsing (we do a full parse of ent def string twice in R_LoadLights and for each target in setProjTarget ...)
classname light:
fade light radius target targetname _anglescale
For scaling angle attenuation. Use a small value (< 1.0) to lessen the angle attenuation, and a high value (> 1.0) for sharper, more faceted lighting. _color _deviance
Radius within which additional samples will be placed. _filter;_filterradius
"_filterradius" "32" – will filter lightmaps created by this light by 32 world units _samples
Makes Q3map2 replace the light with several smaller lights for smoother illumination. Values of 4 or so will be adequate.(where "#" is distance in world units for point/spot lights and degrees for suns) _sun angle?!
{ "target" "t514" "radius" "128" "angle" "0" "_color" "1.000000 0.690196 0.384314" "light" "100" "origin" "-2340 3234 1426" "fade" ".9" "classname" "light" }
classname lightJunior:
fade light radius
Todo:
add 1 dummy light so we don't trash the hunk memory system ...
Todo:
: light: ANGLE, NONLINEAR, Q3MAP_NON-DYNAMIC
Todo:
: lightJunior: ANGLE, NEGATIVE_POINT, NEGATIVE_SPOT, NONLINEAR
Todo:
Todo:
Todo:
: inspect (has to be set on spotlight ..., target?!)
Definition at line 5003 of file tr_bsp.c.
Referenced by R_LoadEntities().
static void R_LoadMarksurfaces (lump_t * l) static
R_LoadMarksurfaces.
Parameters
[in] l
Definition at line 4410 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadNodesAndLeafs (lump_t * nodeLump, lump_t * leafLump) static
R_LoadNodesAndLeafs.
Parameters
[in] nodeLump
[in] leafLump
Definition at line 4196 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadPlanes (lump_t * l) static
R_LoadPlanes.
Parameters
[in] l
Definition at line 4439 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadShaders (lump_t * l) static
R_LoadShaders.
Parameters
[in] l
Definition at line 4377 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadSubmodels (lump_t * l) static
R_LoadSubmodels.
Parameters
[in] l
Definition at line 4071 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadSurfaces (lump_t * surfs, lump_t * verts, lump_t * indexLump) static
R_LoadSurfaces.
Parameters
[in] surfs
[in] verts
[in] indexLump
Definition at line 3987 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_LoadVisibility (lump_t * l) static
R_LoadVisibility.
Parameters
[in] l
Definition at line 1034 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
int R_MergedHeightPoints (srfGridMesh_t * grid, int offset)
R_MergedHeightPoints.
Parameters
[in] grid
[in] offset
Returns
true if there are grid points merged on a height edge
Definition at line 1824 of file tr_bsp.c.
int R_MergedWidthPoints (srfGridMesh_t * grid, int offset)
R_MergedWidthPoints.
Parameters
[in] grid
[in] offset
Returns
true if there are grid points merged on a width edge
Definition at line 1792 of file tr_bsp.c.
static void R_MovePatchSurfacesToHunk (void) static
R_MovePatchSurfacesToHunk.
Definition at line 2854 of file tr_bsp.c.
static qboolean R_PrecacheGenericSurfInteraction (srfGeneric_t * surf, shader_t * shader, trRefLight_t * light) static
R_PrecacheGenericSurfInteraction.
Parameters
[in] surfT
shader - unused
[in] light
Returns
Definition at line 5939 of file tr_bsp.c.
Referenced by R_PrecacheInteractionSurface().
static void R_PrecacheInteraction (trRefLight_t * light, bspSurface_t * surface) static
R_PrecacheInteraction.
Parameters
[in,out] light
[in] surface
Definition at line 5638 of file tr_bsp.c.
Referenced by R_PrecacheInteractionSurface().
void R_PrecacheInteractions ()
R_PrecacheInteractions.
Definition at line 7494 of file tr_bsp.c.
Referenced by RE_LoadWorldMap().
static void R_PrecacheInteractionSurface (bspSurface_t * surf, trRefLight_t * light) static
R_PrecacheInteractionSurface.
Parameters
[in,out] surf
[in] light
Definition at line 5955 of file tr_bsp.c.
Referenced by R_RecursivePrecacheInteractionNode().
float R_ProcessLightmap (byte * pic, int in_padding, int width, int height, byte * pic_out)
R_ProcessLightmap.
Parameters
[in] pic
[in] in_padding
[in] width
[in] height
[out] pic_out
Returns
maxIntensity
Todo:
: check range)
Definition at line 185 of file tr_bsp.c.
static void R_RecursiveAddInteractionNode (bspNode_t * node, trRefLight_t * light) static
R_RecursiveAddInteractionNode.
Parameters
[in,out] node
[in] light
Definition at line 6061 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
static void R_RecursivePrecacheInteractionNode (bspNode_t * node, trRefLight_t * light) static
R_RecursivePrecacheInteractionNode.
Parameters
[in,out] node
[in] light
Definition at line 5994 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
void R_SaveCubeProbes (const char * filename, byte * pixeldata, int width, int height)
This is saving our cube probes to special uncompressed pixeldata tga rgb format.
Optimize: - Remove the alpha channel (25% less data)? or use pixel intensity in the alpha channel?
Parameters
[in] filename
[in] data
[in] width in pixels
[in] height in pixels
Definition at line 7913 of file tr_bsp.c.
Referenced by R_BuildCubeMaps().
static void R_SetParent (bspNode_t * node, bspNode_t * parent) static
R_SetParent.
Parameters
[in,out] node
[in] parent
Definition at line 4137 of file tr_bsp.c.
Referenced by R_LoadNodesAndLeafs().
int R_ShadowFrustumCullWorldBounds (int numShadowPlanes, cplane_t * shadowPlanes, vec3_t worldBounds[2])
R_ShadowFrustumCullWorldBounds.
Parameters
[in] numShadowPlanes
[in] shadowPlanes
[in] worldBounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Note
Unused
Definition at line 6134 of file tr_bsp.c.
static void R_StitchAllPatches (void) static
R_StitchAllPatches.
Definition at line 2816 of file tr_bsp.c.
static int R_StitchPatches (int grid1num, int grid2num) static
R_StitchPatches.
Parameters
[in] grid1num
[in] grid2num
Returns
Definition at line 2116 of file tr_bsp.c.
static int R_TryStitchingPatch (int grid1num) static
This function will try to stitch patches in the same LoD group together for the highest LoD.
Only single missing vertice cracks will be fixed.
Vertices will be joined at the patch side a crack is first found, at the other side of the patch (on the same row or column) the vertices will not be joined and cracks might still appear at that side.
Parameters
[in] grid1num
Returns
Definition at line 2771 of file tr_bsp.c.
void RE_LoadWorldMap (const char * name)
Called directly from cgame.
RE_LoadWorldMap.
Parameters
[in] name
Todo:
: this is sort of silly. I'm going to do a general cleanup on fog stuff
Todo:
: causes missing vbo error on radar (maps with portal sky or foliage)
Definition at line 8635 of file tr_bsp.c.
void RE_SetWorldVisData (const byte * vis)
This is called by the clipmodel subsystem so we can share the 1.8 megs of space in big maps...
Parameters
vis
Definition at line 1025 of file tr_bsp.c.
void resetRefLight (trRefLight_t * light)
Resets a static light to default values.
Parameters
[in]
Definition at line 4920 of file tr_bsp.c.
Referenced by R_LoadLights().
qboolean setProjTargetOrigin (char * lightDefs, char * targetname, trRefLight_t * light)
Parses all ents again and sets origin from given targetname null_info ent.
Definition at line 4785 of file tr_bsp.c.
Referenced by R_LoadLights().
static shader_t* ShaderForShaderNum (int shaderNum) static
ShaderForShaderNum.
Parameters
[in] shaderNum
Returns
Definition at line 1078 of file tr_bsp.c.
Referenced by ParseFace(), ParseFlare(), ParseFoliage(), ParseMesh(), and ParseTriSurf().
static void SphereFromBounds (vec3_t mins, vec3_t maxs, vec3_t origin, float * radius) static
Creates a bounding sphere from a bounding box.
Parameters
mins
maxs
origin
radius
Definition at line 1112 of file tr_bsp.c.
Referenced by FinishGenericSurface().
static int UpdateLightTriangles (const srfVert_t * verts, int numTriangles, srfTriangle_t * triangles, shader_t * surfaceShader, trRefLight_t * light) static
UpdateLightTriangles.
Parameters
[in] verts
[in] numTriangles
[in] triangles
[in] surfaceShader
[in] light
Returns
Todo:
?
Definition at line 6245 of file tr_bsp.c.
Referenced by R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), and R_CreateVBOShadowMeshes().
unsigned int VertexCoordGenerateHash (const vec3_t xyz)
VertexCoordGenerateHash.
Parameters
[in] xyz
Returns
Definition at line 7630 of file tr_bsp.c.
Referenced by AddVertexToHashTable(), FindVertexInHashTable(), GL_BindNearestCubeMap(), and R_FindTwoNearestCubeMaps().
Variable Documentation
int c_vboLightSurfaces static
Definition at line 48 of file tr_bsp.c.
Referenced by R_CreateVBOLightMeshes(), R_CreateVBOShadowMeshes(), and R_PrecacheInteractions().
int c_vboShadowSurfaces static
Definition at line 49 of file tr_bsp.c.
Referenced by R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), and R_PrecacheInteractions().
int c_vboWorldSurfaces static
Definition at line 47 of file tr_bsp.c.
Referenced by R_PrecacheInteractions().
byte* fileBase static
Definition at line 45 of file tr_bsp.c.
Referenced by R_LoadEntities(), R_LoadFogs(), R_LoadLightGrid(), R_LoadLightmapsInternal(), R_LoadMarksurfaces(), R_LoadNodesAndLeafs(), R_LoadPlanes(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_LoadVisibility(), and RE_LoadWorldMap().
growList_t s_interactions static
Definition at line 44 of file tr_bsp.c.
int s_lightCount static
Definition at line 43 of file tr_bsp.c.
Referenced by R_PrecacheInteractions(), R_PrecacheInteractionSurface(), R_RecursiveAddInteractionNode(), and R_RecursivePrecacheInteractionNode().
world_t s_worldData static
Definition at line 42 of file tr_bsp.c.
Referenced by R_LoadEntities(), R_LoadLightGrid(), and RE_LoadWorldMap().