ET: Legacy: src/renderer2/tr_shade_calc.c File Reference
tr_shade_calc.c File Reference
#include "tr_local.h"
Macros
#define WAVEVALUE(table, base, amplitude, phase, freq) ((base) + table[(int64_t)((((phase) + tess.shaderTime * (freq)) * FUNCTABLE_SIZE)) & FUNCTABLE_MASK] * (amplitude))
Functions
static float * TableForFunc (genFunc_t func)
TableForFunc.
float RB_EvalWaveForm (const waveForm_t *wf)
Evaluates a given waveForm_t, referencing backEnd.refdef.time directly.
float RB_EvalWaveFormClamped (const waveForm_t *wf)
RB_EvalWaveFormClamped.
static float GetOpValue (const expOperation_t *op)
GetOpValue.
float RB_EvalExpression (const expression_t *exp, float defaultValue)
RB_EvalExpression.
void RB_CalcDeformVertexes (deformStage_t *ds)
RB_CalcDeformVertexes.
void RB_CalcDeformNormals (deformStage_t *ds)
Wiggle the normals for wavy environment mapping.
void RB_CalcBulgeVertexes (deformStage_t *ds)
RB_CalcBulgeVertexes.
void RB_CalcMoveVertexes (deformStage_t *ds)
A deformation that can move an entire surface along a wave path.
void DeformText (const char *text)
Change a polygon into a bunch of text polygons.
static void GlobalVectorToLocal (const vec3_t in, vec3_t out)
GlobalVectorToLocal.
static void AutospriteDeform (void)
Assuming all the triangles for this shader are independant quads, rebuild them as forward facing sprites.
static void Autosprite2Deform (void)
Autosprite2 will pivot a rectangular quad along the center of its long axis.
qboolean ShaderRequiresCPUDeforms (const shader_t *shader)
ShaderRequiresCPUDeforms.
void Tess_DeformGeometry (void)
Tess_DeformGeometry.
void RB_CalcTexMatrix (const textureBundle_t *bundle, mat4_t matrix)
RB_CalcTexMatrix.
Variables
int edgeVerts [6][2]
Macro Definition Documentation
#define WAVEVALUE (table, base, amplitude, phase, freq) ((base) + table[(int64_t)((((phase) + tess.shaderTime * (freq)) * FUNCTABLE_SIZE)) & FUNCTABLE_MASK] * (amplitude))
Definition at line 38 of file tr_shade_calc.c.
Referenced by RB_CalcDeformVertexes(), RB_CalcMoveVertexes(), and RB_EvalWaveForm().
Function Documentation
static void Autosprite2Deform (void) static
Autosprite2 will pivot a rectangular quad along the center of its long axis.
Definition at line 842 of file tr_shade_calc.c.
Referenced by Tess_DeformGeometry().
static void AutospriteDeform (void) static
Assuming all the triangles for this shader are independant quads, rebuild them as forward facing sprites.
Definition at line 752 of file tr_shade_calc.c.
Referenced by Tess_DeformGeometry().
void DeformText (const char * text)
Change a polygon into a bunch of text polygons.
Parameters
[in] text
Definition at line 667 of file tr_shade_calc.c.
static float GetOpValue (const expOperation_t * op) static
GetOpValue.
Parameters
[in] op
Returns
Todo:
?
Definition at line 117 of file tr_shade_calc.c.
Referenced by RB_EvalExpression().
static void GlobalVectorToLocal (const vec3_t in, vec3_t out) static
GlobalVectorToLocal.
Parameters
[in] in
[out] out
Definition at line 741 of file tr_shade_calc.c.
void RB_CalcBulgeVertexes (deformStage_t * ds)
RB_CalcBulgeVertexes.
Parameters
[in] ds
Definition at line 615 of file tr_shade_calc.c.
void RB_CalcDeformNormals (deformStage_t * ds)
Wiggle the normals for wavy environment mapping.
Parameters
[in] ds
Definition at line 583 of file tr_shade_calc.c.
void RB_CalcDeformVertexes (deformStage_t * ds)
RB_CalcDeformVertexes.
Parameters
[in,out] ds
Definition at line 475 of file tr_shade_calc.c.
void RB_CalcMoveVertexes (deformStage_t * ds)
A deformation that can move an entire surface along a wave path.
Parameters
[in] ds
Definition at line 641 of file tr_shade_calc.c.
void RB_CalcTexMatrix (const textureBundle_t * bundle, mat4_t matrix)
RB_CalcTexMatrix.
Parameters
[in] bundle
[in] matrix
Definition at line 1076 of file tr_shade_calc.c.
Referenced by R_ComputeFinalAttenuation().
float RB_EvalExpression (const expression_t * exp, float defaultValue)
RB_EvalExpression.
Parameters
[in] exp
[in] defaultValue
Returns
Definition at line 244 of file tr_shade_calc.c.
Referenced by R_ShaderExp_f(), RB_CalcTexMatrix(), and Render_lightVolume().
float RB_EvalWaveForm (const waveForm_t * wf)
Evaluates a given waveForm_t, referencing backEnd.refdef.time directly.
Parameters
[in] wf
Returns
Definition at line 81 of file tr_shade_calc.c.
Referenced by RB_CalcDeformVertexes(), RB_CalcTexMatrix(), and RB_EvalWaveFormClamped().
float RB_EvalWaveFormClamped (const waveForm_t * wf)
RB_EvalWaveFormClamped.
Parameters
[in] wf
Returns
Definition at line 95 of file tr_shade_calc.c.
qboolean ShaderRequiresCPUDeforms (const shader_t * shader)
ShaderRequiresCPUDeforms.
Parameters
[in] shader
Returns
Definition at line 967 of file tr_shade_calc.c.
Referenced by R_AddBSPModelSurfaces(), R_AddWorldSurface(), R_CreateSubModelVBOs(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_inPVS(), RB_RenderInteractionsShadowMapped(), Tess_DeformGeometry(), Tess_SurfaceFace(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), and Tess_SurfaceTriangles().
static float* TableForFunc (genFunc_t func) static
TableForFunc.
Parameters
[in] func
Returns
Todo:
Definition at line 45 of file tr_shade_calc.c.
Referenced by RB_CalcDeformVertexes(), RB_CalcMoveVertexes(), and RB_EvalWaveForm().
void Tess_DeformGeometry (void)
Tess_DeformGeometry.
Definition at line 997 of file tr_shade_calc.c.
Variable Documentation
int edgeVerts[6][2]
Initial value:
=
{
    { 0, 1 },
    { 0, 2 },
    { 0, 3 },
    { 1, 2 },
    { 1, 3 },
    { 2, 3 }
}
Definition at line 829 of file tr_shade_calc.c.