ET: Legacy: src/renderer2/tr_local.h File Reference
tr_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qfiles.h"
#include "../qcommon/qcommon.h"
#include "../renderercommon/tr_common.h"
#include "../renderercommon/tr_public.h"
#include "tr_extra.h"
#include "tr_glsldef.h"
Data Structures
struct screenRect_s
struct link_s
struct trRefLight_s
struct trRefEntity_t
A trRefEntity_t has all the information passed in by the client game, as well as some locally derived info.
struct orientationr_t
struct vertexHash_s
struct image_s
struct BufferImage_s
struct FBO_s
struct VBO_s
struct IBO_s
struct shaderTable_s
struct opstring_t
struct expOperation_t
struct expression_t
struct waveForm_t
struct deformStage_t
struct texModInfo_t
struct textureBundle_t
struct stencil_s
struct shaderStage_t
Shifts.
struct skyParms_t
struct fogParms_t
struct shader_s
struct growList_t
struct shaderProgram_s
struct shaderProgramList_s
struct uniformInfo_s
struct uniformValue_s
struct programInfo_s
struct decalProjector_s
struct corona_s
struct trRefdef_t
Holds everything that comes in refdef_t, as well as the locally generated scene information.
struct skinSurface_t
skins allow models to be retextured without modifying the model file
struct skinModel_t
struct skin_s
struct fog_t
struct viewParms_t
struct drawSurf_s
struct interactionCache_s
struct interactionVBO_s
struct interaction_s
struct shadowState_t
struct srfPoly_s
struct srfPolyBuffer_s
struct srfDecal_s
struct srfFlare_s
struct srfVert_t
struct srfTriangle_t
struct srfGeneric_s
struct srfGridMesh_s
struct srfSurfaceFace_t
struct srfTriangles_t
misc_models in maps are turned into direct geometry by xmap
struct foliageInstance_t
struct srfFoliage_t
struct srfVBOMesh_s
struct srfVBOMD5Mesh_s
struct srfVBOMDMMesh_s
struct srfVBOMDVMesh_s
struct bspSurface_s
struct decal_s
struct bspNode_s
struct bspModel_t
struct bspGridPoint_t
struct world_t
struct mdvFrame_t
struct mdvTag_t
struct mdvTagName_t
struct mdvXyz_t
struct mdvNormTanBi_t
struct mdvSt_t
struct mdvSurface_s
struct mdvModel_s
struct md5Weight_t
struct md5Vertex_t
struct md5Surface_t
struct md5Bone_t
struct md5Model_s
struct mdmTagIntern_t
struct mdmSurfaceIntern_s
struct mdmModel_s
struct md5Channel_t
struct md5Frame_t
struct md5Animation_s
struct psaAnimation_t
struct skelAnimation_t
struct skelTriangle_t
struct model_s
struct frontEndCounters_t
struct glstate_t
The renderer front end should never modify glstate_t.
struct backEndCounters_t
struct backEndState_t
all state modified by the back end is seperated from the front end state
struct cubemapProbe_t
struct trGlobals_t
Most renderer globals are defined here. backend functions should never modify any of these fields, but may read fields that aren't dynamically modified by the frontend.
struct trPrograms_s
struct stageVars
struct shaderCommands_s
struct renderCommandList_t
struct setColorCommand_t
struct drawBufferCommand_t
struct subImageCommand_t
struct swapBuffersCommand_t
struct endFrameCommand_t
struct stretchPicCommand_t
struct poly2dCommand_t
struct drawViewCommand_t
struct renderToTextureCommand_t
struct screenshotCommand_t
struct videoFrameCommand_t
struct renderFinishCommand_t
struct backEndData_t
All of the information needed by the back end must be contained in a backEndData_t.
Macros
#define GL_INDEX_TYPE GL_UNSIGNED_INT
#define BUFFER_OFFSET(i) ((char *)NULL + (i))
#define MAX_SHADERS (1 << 12)
#define SHADERS_MASK (MAX_SHADERS - 1)
#define MAX_SHADER_TABLES 1024
#define MAX_SHADER_STAGES 16
#define MAX_OCCLUSION_QUERIES 4096
#define MAX_FBOS 64
#define MAX_VISCOUNTS 5
#define MAX_VIEWS 10
#define MAX_SHADOWMAPS 5
#define CALC_REDUNDANT_SHADOWVERTS 0
#define HDR_ENABLED() ((r_hdrRendering->integer && glConfig2.textureFloatAvailable && glConfig2.framebufferObjectAvailable && glConfig2.framebufferBlitAvailable))
#define REF_CUBEMAP_SIZE 32
#define REF_CUBEMAP_STORE_SIZE 1024
#define REF_CUBEMAP_STORE_SIDE (REF_CUBEMAP_STORE_SIZE / REF_CUBEMAP_SIZE)
#define REF_CUBEMAPS_PER_FILE (REF_CUBEMAP_STORE_SIDE * REF_CUBEMAP_STORE_SIDE)
#define MAX_EXPRESSION_OPS 32
#define TR_MAX_TEXMODS 4
#define MAX_SHADER_DEFORMS 3
#define MAX_SHADER_DEFORM_PARMS (1 + MAX_SHADER_DEFORMS + MAX_SHADER_DEFORMS * 8)
#define MAX_IMAGE_ANIMATIONS 16
#define LIGHTMAP_2D -4
#define LIGHTMAP_BY_VERTEX -3
#define LIGHTMAP_WHITEIMAGE -2
#define LIGHTMAP_NONE -1
#define ATTR_DECL
#define MACRO_ENUM
#define UNIFORM_ENUM
#define MAX_UNIFORM_VALUES 64
#define TEX_DECL
#define SHADER_PROGRAM_T_OFS(x) ((size_t)&(((shaderProgram_t *)0)->x))
#define MAX_SKIN_SURFACES 256
Max surfaces per-skin.
#define MAX_PART_MODELS 7
#define MAX_FACE_POINTS 64
#define MAX_PATCH_SIZE 64
max dimensions of a patch mesh in map file
#define MAX_GRID_SIZE 65
max dimensions of a grid mesh in memory
#define MAX_DECAL_VERTS 10
worst case is triangle clipped by 6 planes
#define MAX_WORLD_DECALS 1024
#define MAX_ENTITY_DECALS 128
#define CONTENTS_NODE -1
#define WORLD_MAX_SKY_NODES 32
#define MD5_IDENTSTRING "MD5Version"
#define MD5_VERSION 10
#define MAX_MOD_KNOWN 2048
#define MAX_ANIMATIONFILES 4096
#define MAX_LIGHTMAPS 256
#define MAX_SKINS 1024
#define MAX_DRAWSURFS 0x10000
#define DRAWSURF_MASK (MAX_DRAWSURFS - 1)
#define MAX_INTERACTIONS MAX_DRAWSURFS * 8
#define INTERACTION_MASK (MAX_INTERACTIONS - 1)
#define FOG_TABLE_SIZE 256
#define DEFAULT_FOG_EXP_DENSITY 0.5
#define FUNCTABLE_SIZE 4096
% 1024
#define FUNCTABLE_SIZE2 12
% 10
#define FUNCTABLE_MASK (FUNCTABLE_SIZE - 1)
#define MAX_GLSTACK 5
#define GLCOLOR_WHITE 1.0f, 1.0f, 1.0f, 1.0f
#define GLCOLOR_BLACK 0.0f, 0.0f, 0.0f, 1.0f
#define GLCOLOR_RED 1.0f, 0.0f, 0.0f, 1.0f
#define GLCOLOR_GREEN 0.0f, 1.0f, 0.0f, 1.0f
#define GLCOLOR_BLUE 0.0f, 0.0f, 1.0f, 1.0f
#define GLCOLOR_NONE 0.0f, 0.0f, 0.0f, 0.0f
#define GL_CheckErrors() GL_CheckErrors_(__FILE__, __LINE__)
#define GLSTACK_MVPM glState.modelViewProjectionMatrix[glState.stackIndex]
#define GLSTACK_PM glState.projectionMatrix[glState.stackIndex]
#define GLSTACK_MVM glState.modelViewMatrix[glState.stackIndex]
#define MODEL_MATRIX backEnd.orientation.transformMatrix
#define ImageCopyBackBuffer(image) R_ImageCopyBack(image, 0, 0, image->uploadWidth, image->uploadHeight)
#define MAX_MULTIDRAW_PRIMITIVES 1000
#define MAX_RENDER_COMMANDS (0x40000 * 8)
was 0x40000
#define MIN_POLYS 4096
#define MIN_POLYVERTS 8192
#define MAX_POLYS 16384
was 4096
#define MAX_POLYVERTS 32768
was 8192
#define MAX_DECAL_PROJECTORS 128
includes decal projectors that will be culled out, hard limited to 32 active projectors because of bitmasks.
#define MAX_USED_DECAL_PROJECTORS 32
#define MAX_DECALS 1024
#define DECAL_MASK (MAX_DECALS - 1)
#define MAX_POLYBUFFERS 4096
#define SelectTexture(tex) GLSL_SelectTexture(trProg.selectedProgram, tex)
#define SetUniformBoolean(uniformNum, value) GLSL_SetUniformBoolean(trProg.selectedProgram, uniformNum, value)
#define SetUniformInt(uniformNum, value) GLSL_SetUniformInt(trProg.selectedProgram, uniformNum, value)
#define SetUniformFloat(uniformNum, value) GLSL_SetUniformFloat(trProg.selectedProgram, uniformNum, value)
#define SetUniformFloat5(uniformNum, value) GLSL_SetUniformFloat5(trProg.selectedProgram, uniformNum, value)
#define SetUniformVec2(uniformNum, value) GLSL_SetUniformVec2(trProg.selectedProgram, uniformNum, value)
#define SetUniformVec3(uniformNum, value) GLSL_SetUniformVec3(trProg.selectedProgram, uniformNum, value)
#define SetUniformVec4(uniformNum, value) GLSL_SetUniformVec4(trProg.selectedProgram, uniformNum, value)
#define SetUniformMatrix16(uniformNum, value) GLSL_SetUniformMatrix16(trProg.selectedProgram, uniformNum, value)
#define SetUniformFloatARR(uniformNum, value, size) GLSL_SetUniformFloatARR(trProg.selectedProgram, uniformNum, value, size)
#define SetUniformVec4ARR(uniformNum, value, size) GLSL_SetUniformVec4ARR(trProg.selectedProgram, uniformNum, value, size)
#define SetUniformMatrix16ARR(uniformNum, value, size) GLSL_SetUniformMatrix16ARR(trProg.selectedProgram, uniformNum, value, size)
#define SelectProgram(program) Ren_LogComment("SelectProgram called: (%s:%d)\n", __FILE__, __LINE__); GLSL_SelectPermutation(program)
#define SetMacrosAndSelectProgram(program, ...) GLSL_SetMacroStates(program, NUMARGS(__VA_ARGS__), ## __VA_ARGS__); SelectProgram(program)
#define GL_JOIN()
#define R2_TIMING(rule) if (r_speeds->integer == rule)
#define R2_TIMING_SIMPLE() if (r_speeds->integer)
Typedefs
typedef unsigned int glIndex_t
typedef struct screenRect_s screenRect_t
typedef cplane_t frustum_t[6]
typedef struct link_s link_t
typedef struct trRefLight_s trRefLight_t
A trRefLight_t has all the information passed in by the client game, as well as some locally derived info.
typedef struct vertexHash_s vertexHash_t
Useful helper struct.
typedef struct image_s image_t
typedef struct BufferImage_s BufferImage_t
typedef struct FBO_s FBO_t
typedef struct VBO_s VBO_t
typedef struct IBO_s IBO_t
typedef struct shaderTable_s shaderTable_t
typedef struct stencil_s stencil_t
Shifts.
typedef struct shader_s shader_t
typedef struct shaderProgram_s shaderProgram_t
typedef struct shaderProgramList_s shaderProgramList_t
typedef struct uniformInfo_s uniformInfo_t
typedef struct uniformValue_s uniformValue_t
typedef struct programInfo_s programInfo_t
typedef struct decalProjector_s decalProjector_t
typedef struct corona_s corona_t
typedef struct skin_s skin_t
typedef struct drawSurf_s drawSurf_t
typedef struct interactionCache_s interactionCache_t
An interactionCache is a node between a light and a precached world surface.
typedef struct interactionVBO_s interactionVBO_t
typedef struct interaction_s interaction_t
An interaction is a node between a light and any surface.
typedef struct srfPoly_s srfPoly_t
typedef struct srfPolyBuffer_s srfPolyBuffer_t
typedef struct srfDecal_s srfDecal_t
typedef struct srfFlare_s srfFlare_t
typedef struct srfGeneric_s srfGeneric_t
typedef struct srfGridMesh_s srfGridMesh_t
typedef byte fcolor4ub_t[4]
foliage surfaces are autogenerated from models into geometry lists by q3map2
typedef struct srfVBOMesh_s srfVBOMesh_t
typedef struct srfVBOMD5Mesh_s srfVBOMD5Mesh_t
typedef struct srfVBOMDMMesh_s srfVBOMDMMesh_t
typedef struct srfVBOMDVMesh_s srfVBOMDVMesh_t
typedef struct bspSurface_s bspSurface_t
typedef struct decal_s decal_t
typedef struct bspNode_s bspNode_t
typedef struct mdvSurface_s mdvSurface_t
typedef struct mdvModel_s mdvModel_t
typedef struct md5Model_s md5Model_t
typedef struct mdmSurfaceIntern_s mdmSurfaceIntern_t
typedef struct mdmModel_s mdmModel_t
typedef struct md5Animation_s md5Animation_t
typedef struct model_s model_t
typedef struct trPrograms_s trPrograms_t
typedef byte color4ub_t[4]
typedef struct stageVars stageVars_t
typedef struct shaderCommands_s shaderCommands_t
Enumerations
enum deferredShading_t { DS_DISABLED = 0, DS_STANDARD }
enum cullResult_t { CULL_IN = 0, CULL_CLIP, CULL_OUT }
enum frustumBits_t {
FRUSTUM_LEFT = 0, FRUSTUM_RIGHT, FRUSTUM_BOTTOM, FRUSTUM_TOP,
FRUSTUM_NEAR, FRUSTUM_FAR, FRUSTUM_PLANES = 6, FRUSTUM_CLIPALL = 0 | 1 | 2 | 4 | 8 | 16
}
enum {
CUBESIDE_PX = (1 << 0), CUBESIDE_PY = (1 << 1), CUBESIDE_PZ = (1 << 2), CUBESIDE_NX = (1 << 3),
CUBESIDE_NY = (1 << 4), CUBESIDE_NZ = (1 << 5), CUBESIDE_CLIPALL = 1 | 2 | 4 | 8 | 16 | 32
}
enum {
IF_NONE, IF_NOPICMIP = BIT(0), IF_NOCOMPRESSION = BIT(1), IF_ALPHA = BIT(2),
IF_NORMALMAP = BIT(3), IF_RGBA16F = BIT(4), IF_RGBA32F = BIT(5), IF_LA16F = BIT(6),
IF_LA32F = BIT(7), IF_ALPHA16F = BIT(8), IF_ALPHA32F = BIT(9), IF_DEPTH16 = BIT(10),
IF_DEPTH24 = BIT(11), IF_DEPTH32 = BIT(12), IF_PACKED_DEPTH24_STENCIL8 = BIT(13), IF_LIGHTMAP = BIT(14),
IF_RGBA16 = BIT(15), IF_RGBE = BIT(16), IF_ALPHATEST = BIT(17), IF_DISPLACEMAP = BIT(18)
}
enum filterType_t { FT_DEFAULT = 0, FT_LINEAR, FT_NEAREST }
enum wrapType_t {
WT_REPEAT = 0, WT_CLAMP, WT_EDGE_CLAMP, WT_ZERO_CLAMP,
WT_ALPHA_ZERO_CLAMP
}
enum BuffetType_t { DEFAULT = 0, DIFFUSE, NORMAL, SPECULAR }
enum vboUsage_t { VBO_USAGE_STATIC = 0, VBO_USAGE_DYNAMIC }
enum shaderSort_t {
SS_BAD, SS_PORTAL, SS_ENVIRONMENT, SS_OPAQUE,
SS_DECAL, SS_SEE_THROUGH, SS_BANNER, SS_FOG,
SS_UNDERWATER, SS_BLEND0, SS_BLEND1, SS_BLEND2,
SS_BLEND3, SS_BLEND6, SS_STENCIL_SHADOW, SS_ALMOST_NEAREST,
SS_NEAREST, SS_BAD = 0, SS_PORTAL, SS_ENVIRONMENT_FOG,
SS_OPAQUE, SS_ENVIRONMENT_NOFOG, SS_DECAL, SS_SEE_THROUGH,
SS_BANNER, SS_FOG, SS_UNDERWATER, SS_WATER,
SS_FAR, SS_MEDIUM, SS_CLOSE, SS_BLEND0,
SS_BLEND1, SS_BLEND2, SS_BLEND3, SS_BLEND6,
SS_ALMOST_NEAREST, SS_NEAREST, SS_POST_PROCESS, SS_BAD,
SS_PORTAL, SS_ENVIRONMENT, SS_OPAQUE, SS_DECAL,
SS_SEE_THROUGH, SS_BANNER, SS_FOG, SS_UNDERWATER,
SS_BLEND0, SS_BLEND1, SS_BLEND2, SS_BLEND3,
SS_BLEND6, SS_STENCIL_SHADOW, SS_ALMOST_NEAREST, SS_NEAREST
}
enum genFunc_t {
GF_NONE, GF_SIN, GF_SQUARE, GF_TRIANGLE,
GF_SAWTOOTH, GF_INVERSE_SAWTOOTH, GF_NOISE, GF_NONE = 0,
GF_SIN, GF_SQUARE, GF_TRIANGLE, GF_SAWTOOTH,
GF_INVERSE_SAWTOOTH, GF_NOISE, GF_NONE, GF_SIN,
GF_SQUARE, GF_TRIANGLE, GF_SAWTOOTH, GF_INVERSE_SAWTOOTH,
GF_NOISE
}
enum deform_t {
DEFORM_NONE, DEFORM_WAVE, DEFORM_NORMALS, DEFORM_BULGE,
DEFORM_MOVE, DEFORM_PROJECTION_SHADOW, DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2,
DEFORM_TEXT0, DEFORM_TEXT1, DEFORM_TEXT2, DEFORM_TEXT3,
DEFORM_TEXT4, DEFORM_TEXT5, DEFORM_TEXT6, DEFORM_TEXT7,
DEFORM_NONE = 0, DEFORM_WAVE, DEFORM_NORMALS, DEFORM_BULGE,
DEFORM_MOVE, DEFORM_PROJECTION_SHADOW, DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2,
DEFORM_TEXT0, DEFORM_TEXT1, DEFORM_TEXT2, DEFORM_TEXT3,
DEFORM_TEXT4, DEFORM_TEXT5, DEFORM_TEXT6, DEFORM_TEXT7,
DEFORM_SPRITE, DEFORM_FLARE, DEFORM_NONE, DEFORM_WAVE,
DEFORM_NORMALS, DEFORM_BULGE, DEFORM_MOVE, DEFORM_PROJECTION_SHADOW,
DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2, DEFORM_TEXT0, DEFORM_TEXT1,
DEFORM_TEXT2, DEFORM_TEXT3, DEFORM_TEXT4, DEFORM_TEXT5,
DEFORM_TEXT6, DEFORM_TEXT7
}
enum deformGen_t {
DGEN_NONE = 0, DGEN_WAVE_SIN, DGEN_WAVE_SQUARE, DGEN_WAVE_TRIANGLE,
DGEN_WAVE_SAWTOOTH, DGEN_WAVE_INVERSE_SAWTOOTH, DGEN_WAVE_NOISE, DGEN_BULGE,
DGEN_MOVE
}
deformVertexes types that can be handled by the GPU
enum deformType_t { DEFORM_TYPE_NONE = 0, DEFORM_TYPE_CPU, DEFORM_TYPE_GPU }
enum alphaGen_t {
AGEN_IDENTITY, AGEN_SKIP, AGEN_ENTITY, AGEN_ONE_MINUS_ENTITY,
AGEN_NORMALZFADE, AGEN_VERTEX, AGEN_ONE_MINUS_VERTEX, AGEN_LIGHTING_SPECULAR,
AGEN_WAVEFORM, AGEN_PORTAL, AGEN_CONST, AGEN_IDENTITY = 0,
AGEN_ENTITY, AGEN_ONE_MINUS_ENTITY, AGEN_NORMALZFADE, AGEN_VERTEX,
AGEN_ONE_MINUS_VERTEX, AGEN_WAVEFORM, AGEN_CONST, AGEN_CUSTOM,
AGEN_IDENTITY, AGEN_SKIP, AGEN_ENTITY, AGEN_ONE_MINUS_ENTITY,
AGEN_NORMALZFADE, AGEN_VERTEX, AGEN_ONE_MINUS_VERTEX, AGEN_LIGHTING_SPECULAR,
AGEN_WAVEFORM, AGEN_PORTAL, AGEN_CONST
}
enum colorGen_t {
CGEN_BAD, CGEN_IDENTITY_LIGHTING, CGEN_IDENTITY, CGEN_ENTITY,
CGEN_ONE_MINUS_ENTITY, CGEN_EXACT_VERTEX, CGEN_VERTEX, CGEN_ONE_MINUS_VERTEX,
CGEN_WAVEFORM, CGEN_LIGHTING_DIFFUSE, CGEN_FOG, CGEN_CONST,
CGEN_BAD = 0, CGEN_IDENTITY_LIGHTING, CGEN_IDENTITY, CGEN_ENTITY,
CGEN_ONE_MINUS_ENTITY, CGEN_VERTEX, CGEN_ONE_MINUS_VERTEX, CGEN_WAVEFORM,
CGEN_FOG, CGEN_CONST, CGEN_CUSTOM_RGB, CGEN_CUSTOM_RGBs,
CGEN_BAD, CGEN_IDENTITY_LIGHTING, CGEN_IDENTITY, CGEN_ENTITY,
CGEN_ONE_MINUS_ENTITY, CGEN_EXACT_VERTEX, CGEN_VERTEX, CGEN_ONE_MINUS_VERTEX,
CGEN_WAVEFORM, CGEN_LIGHTING_DIFFUSE, CGEN_FOG, CGEN_CONST
}
enum texCoordGen_t {
TCGEN_BAD, TCGEN_IDENTITY, TCGEN_LIGHTMAP, TCGEN_TEXTURE,
TCGEN_ENVIRONMENT_MAPPED, TCGEN_FIRERISEENV_MAPPED, TCGEN_FOG, TCGEN_VECTOR,
TCGEN_BAD = 0, TCGEN_IDENTITY, TCGEN_LIGHTMAP, TCGEN_TEXTURE,
TCGEN_ENVIRONMENT_MAPPED, TCGEN_FOG, TCGEN_VECTOR, TCGEN_BAD,
TCGEN_IDENTITY, TCGEN_LIGHTMAP, TCGEN_TEXTURE, TCGEN_ENVIRONMENT_MAPPED,
TCGEN_FIRERISEENV_MAPPED, TCGEN_FOG, TCGEN_VECTOR
}
enum acff_t {
ACFF_NONE, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, ACFF_MODULATE_ALPHA,
ACFF_NONE = 0, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, ACFF_MODULATE_ALPHA,
ACFF_NONE, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, ACFF_MODULATE_ALPHA
}
enum alphaTest_t { ATEST_NONE = 0, ATEST_GT_0, ATEST_LT_128, ATEST_GE_128 }
enum opcode_t {
OP_UNDEF, OP_IGNORE, OP_BREAK, OP_ENTER,
OP_LEAVE, OP_CALL, OP_PUSH, OP_POP,
OP_CONST, OP_LOCAL, OP_JUMP, OP_EQ,
OP_NE, OP_LTI, OP_LEI, OP_GTI,
OP_GEI, OP_LTU, OP_LEU, OP_GTU,
OP_GEU, OP_EQF, OP_NEF, OP_LTF,
OP_LEF, OP_GTF, OP_GEF, OP_LOAD1,
OP_LOAD2, OP_LOAD4, OP_STORE1, OP_STORE2,
OP_STORE4, OP_ARG, OP_BLOCK_COPY, OP_SEX8,
OP_SEX16, OP_NEGI, OP_ADD, OP_SUB,
OP_DIVI, OP_DIVU, OP_MODI, OP_MODU,
OP_MULI, OP_MULU, OP_BAND, OP_BOR,
OP_BXOR, OP_BCOM, OP_LSH, OP_RSHI,
OP_RSHU, OP_NEGF, OP_ADDF, OP_SUBF,
OP_DIVF, OP_MULF, OP_CVIF, OP_CVFI,
OP_BAD = 0, OP_LAND, OP_LOR, OP_GE,
OP_LE, OP_LEQ, OP_LNE, OP_ADD,
OP_SUB, OP_DIV, OP_MOD, OP_MUL,
OP_NEG, OP_LT, OP_GT, OP_LPAREN,
OP_RPAREN, OP_LBRACKET, OP_RBRACKET, OP_NUM,
OP_TIME, OP_PARM0, OP_PARM1, OP_PARM2,
OP_PARM3, OP_PARM4, OP_PARM5, OP_PARM6,
OP_PARM7, OP_PARM8, OP_PARM9, OP_PARM10,
OP_PARM11, OP_GLOBAL0, OP_GLOBAL1, OP_GLOBAL2,
OP_GLOBAL3, OP_GLOBAL4, OP_GLOBAL5, OP_GLOBAL6,
OP_GLOBAL7, OP_FRAGMENTSHADERS, OP_FRAMEBUFFEROBJECTS, OP_SOUND,
OP_DISTANCE, OP_TABLE
}
enum texMod_t {
TMOD_NONE, TMOD_TRANSFORM, TMOD_TURBULENT, TMOD_SCROLL,
TMOD_SCALE, TMOD_STRETCH, TMOD_ROTATE, TMOD_ENTITY_TRANSLATE,
TMOD_SWAP, TMOD_NONE = 0, TMOD_TRANSFORM, TMOD_TURBULENT,
TMOD_SCROLL, TMOD_SCALE, TMOD_STRETCH, TMOD_ROTATE,
TMOD_ENTITY_TRANSLATE, TMOD_SCROLL2, TMOD_SCALE2, TMOD_CENTERSCALE,
TMOD_SHEAR, TMOD_ROTATE2, TMOD_NONE, TMOD_TRANSFORM,
TMOD_TURBULENT, TMOD_SCROLL, TMOD_SCALE, TMOD_STRETCH,
TMOD_ROTATE, TMOD_ENTITY_TRANSLATE, TMOD_SWAP
}
enum {
TB_COLORMAP = 0, TB_DIFFUSEMAP = 0, TB_NORMALMAP, TB_SPECULARMAP,
MAX_TEXTURE_BUNDLES = 3
}
enum stageType_t {
ST_COLORMAP = 0, ST_DIFFUSEMAP, ST_NORMALMAP, ST_SPECULARMAP,
ST_REFLECTIONMAP, ST_REFRACTIONMAP, ST_DISPERSIONMAP, ST_SKYBOXMAP,
ST_SCREENMAP, ST_PORTALMAP, ST_HEATHAZEMAP, ST_LIQUIDMAP,
ST_LIGHTMAP, ST_COLLAPSE_lighting_DB, ST_COLLAPSE_lighting_DBS, ST_COLLAPSE_reflection_CB,
ST_ATTENUATIONMAP_XY, ST_ATTENUATIONMAP_Z
}
enum collapseType_t {
COLLAPSE_none = 0, COLLAPSE_genericMulti, COLLAPSE_lighting_DB, COLLAPSE_lighting_DBS,
COLLAPSE_reflection_CB, COLLAPSE_color_lightmap
}
enum stencilFunc_t {
STF_ALWAYS = 0x00, STF_NEVER = 0x01, STF_LESS = 0x02, STF_LEQUAL = 0x03,
STF_GREATER = 0x04, STF_GEQUAL = 0x05, STF_EQUAL = 0x06, STF_NEQUAL = 0x07,
STF_MASK = 0x07
}
StencilFuncs.
enum stencilOp_t {
STO_KEEP = 0x00, STO_ZERO = 0x01, STO_REPLACE = 0x02, STO_INVERT = 0x03,
STO_INCR = 0x04, STO_DECR = 0x05, STO_MASK = 0x07
}
StencilOps.
enum stencilShift_t { STS_SFAIL = 4, STS_ZFAIL = 8, STS_ZPASS = 12 }
Shifts.
enum cullType_t {
CT_FRONT_SIDED, CT_BACK_SIDED, CT_TWO_SIDED, CT_FRONT_SIDED = 0,
CT_BACK_SIDED, CT_TWO_SIDED, CT_FRONT_SIDED, CT_BACK_SIDED,
CT_TWO_SIDED
}
enum fogPass_t {
FP_NONE, FP_EQUAL, FP_LE, FP_NONE = 0,
FP_EQUAL, FP_LE, FP_NONE, FP_EQUAL,
FP_LE
}
enum shaderType_t { SHADER_2D = 0, SHADER_3D_DYNAMIC, SHADER_3D_STATIC, SHADER_LIGHT }
enum {
ATTR_INDEX_POSITION = 0, ATTR_INDEX_TEXCOORD0 = 1, ATTR_INDEX_TEXCOORD1 = 2, ATTR_INDEX_TANGENT = 3,
ATTR_INDEX_BINORMAL = 4, ATTR_INDEX_NORMAL = 5, ATTR_INDEX_COLOR = 6, ATTR_INDEX_BONE_INDEXES = 7,
ATTR_INDEX_BONE_WEIGHTS = 8, ATTR_INDEX_POSITION2 = 9, ATTR_INDEX_TANGENT2 = 10, ATTR_INDEX_BINORMAL2 = 11,
ATTR_INDEX_NORMAL2 = 12, ATTR_INDEX_COUNT = 13
}
enum {
GLS_SRCBLEND_ZERO = (1 << 0), GLS_SRCBLEND_ONE = (1 << 1), GLS_SRCBLEND_DST_COLOR = (1 << 2), GLS_SRCBLEND_ONE_MINUS_DST_COLOR = (1 << 3),
GLS_SRCBLEND_SRC_ALPHA = (1 << 4), GLS_SRCBLEND_ONE_MINUS_SRC_ALPHA = (1 << 5), GLS_SRCBLEND_DST_ALPHA = (1 << 6), GLS_SRCBLEND_ONE_MINUS_DST_ALPHA = (1 << 7),
GLS_SRCBLEND_ALPHA_SATURATE = (1 << 8), GLS_SRCBLEND_BITS, GLS_DSTBLEND_ZERO = (1 << 9), GLS_DSTBLEND_ONE = (1 << 10),
GLS_DSTBLEND_SRC_COLOR = (1 << 11), GLS_DSTBLEND_ONE_MINUS_SRC_COLOR = (1 << 12), GLS_DSTBLEND_SRC_ALPHA = (1 << 13), GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA = (1 << 14),
GLS_DSTBLEND_DST_ALPHA = (1 << 15), GLS_DSTBLEND_ONE_MINUS_DST_ALPHA = (1 << 16), GLS_DSTBLEND_BITS, GLS_DEPTHMASK_TRUE = (1 << 17),
GLS_POLYMODE_LINE = (1 << 18), GLS_DEPTHTEST_DISABLE = (1 << 19), GLS_DEPTHFUNC_LESS = (1 << 20), GLS_DEPTHFUNC_EQUAL = (1 << 21),
GLS_DEPTHFUNC_BITS, GLS_ATEST_GT_0 = (1 << 22), GLS_ATEST_LT_128 = (1 << 23), GLS_ATEST_GE_128 = (1 << 24),
GLS_ATEST_BITS, GLS_REDMASK_FALSE = (1 << 26), GLS_GREENMASK_FALSE = (1 << 27), GLS_BLUEMASK_FALSE = (1 << 28),
GLS_ALPHAMASK_FALSE = (1 << 29), GLS_COLORMASK_BITS, GLS_STENCILTEST_ENABLE = (1 << 30), GLS_DEFAULT = GLS_DEPTHMASK_TRUE
}
enum GLAttrDef { UNIFORM_DEF, UNIFORM_DEF }
enum {
GLSL_BOOL, GLSL_INT, GLSL_FLOAT, GLSL_FLOAT5,
GLSL_DOUBLE, GLSL_VEC2, GLSL_VEC3, GLSL_VEC4,
GLSL_MAT16, GLSL_FLOATARR, GLSL_VEC4ARR, GLSL_MAT16ARR
}
enum EGLCompileMacro { UNIFORM_DEF, UNIFORM_DEF }
enum uniform_t { UNIFORM_DEF, UNIFORM_DEF }
enum texture_def_t { UNIFORM_DEF, UNIFORM_DEF }
enum surfaceType_t {
SF_BAD, SF_SKIP, SF_FACE, SF_GRID,
SF_TRIANGLES, SF_FOLIAGE, SF_POLY, SF_MD3,
SF_MDC, SF_MDS, SF_MDM, SF_FLARE,
SF_ENTITY, SF_DISPLAY_LIST, SF_POLYBUFFER, SF_DECAL,
SF_NUM_SURFACE_TYPES, SF_MAX = 0xffffffff, SF_BAD = 0, SF_SKIP,
SF_FACE, SF_GRID, SF_TRIANGLES, SF_FOLIAGE,
SF_POLY, SF_POLYBUFFER, SF_DECAL, SF_MDV,
SF_MDM, SF_MD5, SF_FLARE, SF_ENTITY,
SF_VBO_MESH, SF_VBO_MD5MESH, SF_VBO_MDMMESH, SF_VBO_MDVMESH,
SF_NUM_SURFACE_TYPES, SF_MAX = 0x7fffffff, SF_BAD, SF_SKIP,
SF_FACE, SF_GRID, SF_TRIANGLES, SF_FOLIAGE,
SF_POLY, SF_MD3, SF_MDC, SF_MDS,
SF_MDM, SF_FLARE, SF_ENTITY, SF_DISPLAY_LIST,
SF_POLYBUFFER, SF_DECAL, SF_NUM_SURFACE_TYPES, SF_MAX = 0xffffffff
}
enum interactionType_t { IA_DEFAULT = 0, IA_SHADOWONLY, IA_LIGHTONLY }
enum smooth_flags {
FLAGS_SMOOTH_TRISURF = BIT(0), FLAGS_SMOOTH_MESH = BIT(1), FLAGS_SMOOTH_MD3 = BIT(2), FLAGS_SMOOTH_MD5 = BIT(3),
FLAGS_SMOOTH_MDC = BIT(4), FLAGS_SMOOTH_MDM = BIT(5), FLAGS_SMOOTH_PSK = BIT(6)
}
enum animType_t { AT_BAD = 0, AT_MD5, AT_PSA }
enum {
COMPONENT_BIT_TX = 1 << 0, COMPONENT_BIT_TY = 1 << 1, COMPONENT_BIT_TZ = 1 << 2, COMPONENT_BIT_QX = 1 << 3,
COMPONENT_BIT_QY = 1 << 4, COMPONENT_BIT_QZ = 1 << 5
}
enum modtype_t {
MOD_BAD, MOD_BRUSH, MOD_MESH, MOD_MDS,
MOD_MDC, MOD_MDM, MOD_MDX, MOD_BAD = 0,
MOD_BSP, MOD_MESH, MOD_MDM, MOD_MDX,
MOD_MD5, MOD_BAD, MOD_BRUSH, MOD_MESH,
MOD_MDS, MOD_MDC, MOD_MDM, MOD_MDX
}
enum ssFormat_t {
SSF_TGA = 0, SSF_JPEG, SSF_PNG, SSF_TGA = 0,
SSF_JPEG, SSF_PNG, SSF_TGA = 0, SSF_JPEG,
SSF_PNG
}
enum renderCommand_t {
RC_END_OF_LIST, RC_SET_COLOR, RC_STRETCH_PIC, RC_2DPOLYS,
RC_ROTATED_PIC, RC_STRETCH_PIC_GRADIENT, RC_DRAW_SURFS, RC_DRAW_BUFFER,
RC_SWAP_BUFFERS, RC_SCREENSHOT, RC_VIDEOFRAME, RC_RENDERTOTEXTURE,
RC_FINISH, RC_END_OF_LIST = 0, RC_SET_COLOR, RC_STRETCH_PIC,
RC_2DPOLYS, RC_ROTATED_PIC, RC_STRETCH_PIC_GRADIENT, RC_DRAW_VIEW,
RC_DRAW_BUFFER, RC_SWAP_BUFFERS, RC_SCREENSHOT, RC_VIDEOFRAME,
RC_RENDERTOTEXTURE, RC_FINISH, RC_END_OF_LIST, RC_SET_COLOR,
RC_STRETCH_PIC, RC_2DPOLYS, RC_ROTATED_PIC, RC_STRETCH_PIC_GRADIENT,
RC_DRAW_SURFS, RC_DRAW_BUFFER, RC_SWAP_BUFFERS, RC_SCREENSHOT,
RC_VIDEOFRAME, RC_RENDERTOTEXTURE, RC_FINISH
}
Functions
static ID_INLINE void InitLink (link_t *l, void *data)
InitLink.
static ID_INLINE void ClearLink (link_t *l)
ClearLink.
static ID_INLINE void RemoveLink (link_t *l)
RemoveLink.
static ID_INLINE void InsertLink (link_t *l, link_t *sentinel)
InsertLink.
static ID_INLINE qboolean StackEmpty (link_t *l)
StackEmpty.
static ID_INLINE link_t * StackTop (link_t *l)
StackTop.
static ID_INLINE void StackPush (link_t *sentinel, void *data)
StackPush.
static ID_INLINE void * StackPop (link_t *l)
StackPop.
static ID_INLINE void QueueInit (link_t *l)
QueueInit.
static ID_INLINE int QueueSize (link_t *l)
QueueSize.
static ID_INLINE qboolean QueueEmpty (link_t *l)
QueueEmpty.
static ID_INLINE void EnQueue (link_t *sentinel, void *data)
EnQueue.
static ID_INLINE void * DeQueue (link_t *l)
DeQueue.
static ID_INLINE link_t * QueueFront (link_t *l)
QueueFront.
void R_ModelInit (void)
R_ModelInit.
model_t * R_GetModelByHandle (qhandle_t hModel)
R_GetModelByHandle.
int RE_LerpTagQ3A (orientation_t *tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char *tagNameIn)
RE_LerpTagQ3A.
int RE_LerpTagET (orientation_t *tag, const refEntity_t *refent, const char *tagNameIn, int startIndex)
RE_LerpTagET.
int RE_BoneIndex (qhandle_t hModel, const char *boneName)
RE_BoneIndex.
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
R_ModelBounds.
void R_Modellist_f (void)
R_Modellist_f.
void R_SwapBuffers (int)
void R_RenderView (viewParms_t *parms)
A view may be either the actual camera view, or a mirror / remote location.
void R_AddMDVSurfaces (trRefEntity_t *ent)
R_AddMDVSurfaces.
void R_AddMDVInteractions (trRefEntity_t *ent, trRefLight_t *light)
R_AddMDVInteractions.
void R_AddNullModelSurfaces (trRefEntity_t *ent)
void R_AddBeamSurfaces (trRefEntity_t *ent)
void R_AddRailSurfaces (trRefEntity_t *ent, qboolean isUnderwater)
void R_AddLightningBoltSurfaces (trRefEntity_t *ent)
int BSPSurfaceCompare (const void *a, const void *b)
Compare function for qsort()
void R_AddPolygonSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
void R_AddPolygonBufferSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
void R_AddDrawSurf (surfaceType_t *surface, shader_t *shader, int lightmapNum, int fogNum)
R_AddDrawSurf.
void R_LocalNormalToWorld (const vec3_t local, vec3_t world)
R_LocalNormalToWorld.
void R_LocalPointToWorld (const vec3_t local, vec3_t world)
R_LocalPointToWorld.
cullResult_t R_CullBox (vec3_t worldBounds[2])
R_CullBox.
cullResult_t R_CullLocalBox (vec3_t bounds[2])
R_CullLocalBox.
int R_CullLocalPointAndRadius (vec3_t origin, float radius)
R_CullLocalPointAndRadius.
int R_CullPointAndRadius (vec3_t origin, float radius)
R_CullPointAndRadius.
int R_FogLocalPointAndRadius (const vec3_t pt, float radius)
R_FogLocalPointAndRadius.
int R_FogPointAndRadius (const vec3_t pt, float radius)
R_FogPointAndRadius.
int R_FogWorldBox (vec3_t bounds[2])
R_FogWorldBox.
void R_SetupEntityWorldBounds (trRefEntity_t *ent)
R_SetupEntityWorldBounds.
void R_RotateEntityForViewParms (const trRefEntity_t *ent, const viewParms_t *viewParms, orientationr_t *orientation)
Generates an orientation for an entity and viewParms. Does NOT produce any GL calls. Called by both the front end and the back end.
void R_RotateEntityForLight (const trRefEntity_t *ent, const trRefLight_t *light, orientationr_t *orientation)
Generates an orientation for an entity and light. Does NOT produce any GL calls. Called by both the front end and the back end.
void R_RotateLightForViewParms (const trRefLight_t *ent, const viewParms_t *viewParms, orientationr_t *orientation)
R_RotateLightForViewParms.
void R_SetupFrustum2 (frustum_t frustum, const mat4_t mvp)
Setup that culling frustum planes for the current view.
void R_SetupFrustum (void)
Setup that culling frustum planes for the current view.
qboolean R_CompareVert (srfVert_t *v1, srfVert_t *v2, qboolean checkST)
R_CompareVert.
void R_CalcNormalForTriangle (vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2)
R_CalcNormalForTriangle.
void R_CalcTangentsForTriangle (vec3_t tangent, vec3_t binormal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentsForTriangle.
void R_CalcTangentsForTriangle2 (vec3_t tangent, vec3_t binormal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
void R_CalcTangentSpace (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpace.
void R_CalcTangentSpaceFast (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpaceFast.
void R_CalcTBN (vec3_t tangent, vec3_t bitangent, vec3_t normal, const vec3_t v1, const vec3_t v2, const vec3_t v3, const vec2_t w1, const vec2_t w2, const vec2_t w3)
R_CalcTBN.
qboolean R_CalcTangentVectors (srfVert_t *dv[3])
R_CalcTangentVectors.
void R_CalcSurfaceTrianglePlanes (int numTriangles, srfTriangle_t *triangles, srfVert_t *verts)
R_CalcSurfaceTrianglePlanes calculates planeNormal.
float R_CalcFov (float fovX, float width, float height)
void R_DebugAxis (const vec3_t origin, const mat4_t transformMatrix)
R_DebugAxis.
void R_DebugBoundingBox (const vec3_t origin, const vec3_t mins, const vec3_t maxs, vec4_t color)
R_DebugBoundingBox.
void R_DebugPolygon (int color, int numPoints, float *points)
R_DebugPolygon.
void R_DebugText (const vec3_t org, float r, float g, float b, const char *text, qboolean neverOcclude)
R_DebugText.
void GL_Bind (image_t *image)
GL_Bind.
void GL_BindNearestCubeMap (const vec3_t xyz)
GL_BindNearestCubeMap.
void GL_Unbind ()
GL_Unbind.
void BindAnimatedImage (textureBundle_t *bundle)
BindAnimatedImage.
void GL_SetDefaultState (void)
GL_SetDefaultState.
void GL_SelectTexture (int unit)
GL_SelectTexture.
void GL_TextureMode (const char *string)
GL_TextureMode.
void GL_BlendFunc (GLenum sfactor, GLenum dfactor)
GL_BlendFunc.
void GL_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_ClearColor.
void GL_ClearDepth (GLclampd depth)
GL_ClearDepth.
void GL_ClearStencil (GLint s)
GL_ClearStencil.
void GL_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_ColorMask.
void GL_CullFace (GLenum mode)
GL_CullFace.
void GL_DepthFunc (GLenum func)
GL_DepthFunc.
void GL_DepthMask (GLboolean flag)
GL_DepthMask.
void GL_DrawBuffer (GLenum mode)
GL_DrawBuffer.
void GL_FrontFace (GLenum mode)
GL_FrontFace.
void GL_LoadModelViewMatrix (const mat4_t m)
GL_LoadModelViewMatrix.
void GL_LoadProjectionMatrix (const mat4_t m)
GL_LoadProjectionMatrix.
void GL_PushMatrix ()
GL_PushMatrix.
void GL_PopMatrix ()
GL_PopMatrix.
void GL_PolygonMode (GLenum face, GLenum mode)
GL_PolygonMode.
void GL_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Scissor.
void GL_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Viewport.
void GL_PolygonOffset (float factor, float units)
GL_PolygonOffset.
void GL_Clear (unsigned int bits)
GL_Clear.
void GL_State (uint32_t stateBits)
This routine is responsible for setting the most commonly changed state in Q3.
void GL_Cull (int cullType)
GL_Cull.
void GL_CheckErrors_ (const char *fileName, int line)
GL_CheckErrors_.
void RB_SetViewMVPM (void)
Set the model view projection matrix to match the ingame view.
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
RE_UploadCinematic.
void RE_BeginFrame (void)
Will be called once for each RE_EndFrame.
void RE_EndFrame (int *frontEndMsec, int *backEndMsec)
Returns the number of msec spent in the back end.
void RE_BeginRegistration (glconfig_t *glconfigOut)
RE_BeginRegistration.
void RE_LoadWorldMap (const char *name)
RE_LoadWorldMap.
void RE_SetWorldVisData (const byte *vis)
This is called by the clipmodel subsystem so we can share the 1.8 megs of space in big maps...
qhandle_t RE_RegisterModel (const char *name)
Loads in a model for the given name.
qhandle_t RE_RegisterSkin (const char *name)
RE_RegisterSkin.
void RE_Shutdown (qboolean destroyWindow)
RE_Shutdown.
qboolean RE_GetSkinModel (qhandle_t skinid, const char *type, char *name)
RE_GetSkinModel.
qhandle_t RE_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
RE_GetShaderFromModel.
qboolean R_GetEntityToken (char *buffer, size_t size)
R_GetEntityToken.
float R_ProcessLightmap (byte *pic, int in_padding, int width, int height, byte *pic_out)
R_ProcessLightmap.
model_t * R_AllocModel (void)
[in] R_AllocModel
void R_Init (void)
R_Init.
void R_SetColorMappings (void)
R_SetColorMappings.
void R_GammaCorrect (byte *buffer, int bufSize)
R_GammaCorrect.
void R_ImageList_f (void)
R_ImageList_f.
void R_SkinList_f (void)
R_SkinList_f.
void R_SubImageCpy (byte *dest, size_t destx, size_t desty, size_t destw, size_t desth, byte *src, size_t srcw, size_t srch, size_t bytes, qboolean in)
Copies between a smaller image and a larger image. Last flag controls is copy in or out of larger image.
const void * RB_TakeScreenshotCmd (const void *data)
RB_TakeScreenshotCmd.
void R_InitSkins (void)
R_InitSkins.
skin_t * R_GetSkinByHandle (qhandle_t hSkin)
R_GetSkinByHandle.
void R_DeleteSurfaceVBOs ()
void R_InitImages (void)
R_InitImages.
void R_ShutdownImages (void)
R_ShutdownImages.
int R_SumOfUsedImages (void)
R_SumOfUsedImages.
void R_ImageCopyBack (image_t *image, int x, int y, int width, int height)
R_ImageCopyBack.
image_t * R_FindImageFile (const char *imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char *materialName)
Finds or loads the given image.
image_t * R_FindCubeImage (const char *imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char *materialName)
Finds or loads the given image.
image_t * R_CreateImage (const char *name, const byte *pic, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateImage.
image_t * R_CreateCubeImage (const char *name, const byte *pic[6], int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateCubeImage.
image_t * R_AllocImage (const char *name, qboolean linkIntoHashTable)
R_AllocImage.
void R_UploadImage (const byte **dataArray, int numData, image_t *image)
R_UploadImage.
int RE_GetTextureId (const char *name)
RE_GetTextureId.
void R_InitFogTable (void)
R_InitFogTable.
float R_FogFactor (float s, float t)
This is called for each texel of the fog texture on startup and for each vertex of transparent shaders in fog dynamically.
qhandle_t RE_RegisterShader (const char *name)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
qhandle_t RE_RegisterShaderNoMip (const char *name)
RE_RegisterShaderNoMip.
qhandle_t RE_RegisterShaderLightAttenuation (const char *name)
For different Doom3 style light effects.
qhandle_t RE_RegisterShaderFromImage (const char *name, image_t *image, qboolean mipRawImage)
RE_RegisterShaderFromImage.
qboolean RE_LoadDynamicShader (const char *shadername, const char *shadertext)
load a new dynamic shader if shadertext is NULL, looks for matching shadername and removes it
shader_t * R_FindShader (const char *name, shaderType_t type, qboolean mipRawImage)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
shader_t * R_GetShaderByHandle (qhandle_t hShader)
When a handle is passed in by another module, this range checks it and returns a valid (possibly default) shader_t to be used internally.
shader_t * R_GetShaderByState (int index, long *cycleTime)
shader_t * R_FindShaderByName (const char *name)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
void R_InitShaders (void)
R_InitShaders.
void R_ShaderList_f (void)
Dump information on all valid shaders to the console A second parameter will cause it to print in sorted order.
void R_ShaderExp_f (void)
R_ShaderExp_f.
void R_RemapShader (const char *shaderName, const char *newShaderName, const char *timeOffset)
R_RemapShader.
void clipPortalPlane ()
clipping portal plane in world space
void GLSL_InitGPUShaders (void)
GLSL_InitGPUShaders.
void GLSL_CompileGPUShaders (void)
GLSL_CompileGPUShaders.
void GLSL_ShutdownGPUShaders ()
GLSL_ShutdownGPUShaders.
void GLSL_BindProgram (shaderProgram_t *program)
GLSL_BindProgram.
void GLSL_BindNullProgram (void)
GLSL_BindNullProgram.
void Tess_Begin (void(*stageIteratorFunc)(), void(*stageIteratorFunc2)(), shader_t *surfaceShader, shader_t *lightShader, qboolean skipTangentSpaces, qboolean skipVBO, int lightmapNum, int fogNum)
We must set some things up before beginning any tesselation, because a surface may be forced to perform a Tess_End due to overflow.
void Tess_End (void)
Render tesselated data.
void Tess_EndBegin ()
Tess_EndBegin.
void Tess_DrawElements ()
Tess_DrawElements.
void Tess_CheckOverflow (int verts, int indexes)
Tess_CheckOverflow.
void Tess_ComputeColor (shaderStage_t *pStage)
Tess_ComputeColor.
void Tess_StageIteratorDebug ()
Tess_StageIteratorDebug.
void Tess_StageIteratorGeneric ()
Tess_StageIteratorGeneric.
void Tess_StageIteratorShadowFill ()
Tess_StageIteratorDepthFill.
void Tess_StageIteratorLighting ()
Tess_StageIteratorLighting.
void Tess_StageIteratorSky ()
All of the visible sky triangles are in tess Other things could be stuck in here, like birds in the sky, etc.
void Tess_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color)
Tess_AddQuadStamp.
void Tess_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color, float s1, float t1, float s2, float t2)
Tess_AddQuadStampExt.
void Tess_AddQuadStampExt2 (vec4_t quadVerts[4], const vec4_t color, float s1, float t1, float s2, float t2, qboolean calcNormals)
Tess_AddQuadStampExt2.
void Tess_AddQuadStamp2 (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2.
void Tess_AddQuadStamp2WithNormals (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2WithNormals.
void Tess_AddTetrahedron (vec4_t tetraVerts[4], vec4_t const color)
Tess_AddTetrahedron.
void Tess_AddCube (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCube.
void Tess_AddCubeWithNormals (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCubeWithNormals.
void Tess_InstantQuad (vec4_t quadVerts[4])
Tess_InstantQuad.
void Tess_UpdateVBOs (uint32_t attribBits)
Update the default VBO to replace the client side vertex arrays.
void RB_ShowImages (void)
Draw all the images to the screen, on top of whatever was there. This is used to test for texture thrashing.
void R_AddBSPModelSurfaces (trRefEntity_t *ent)
R_AddBSPModelSurfaces.
void R_AddWorldSurfaces (void)
R_AddWorldSurfaces.
qboolean R_inPVS (const vec3_t p1, const vec3_t p2)
R_inPVS.
void R_AddWorldInteractions (trRefLight_t *light)
R_AddWorldInteractions.
void R_AddPrecachedWorldInteractions (trRefLight_t *light)
R_AddPrecachedWorldInteractions.
void R_ShutdownVBOs ()
R_ShutdownVBOs.
void R_ClearFlares (void)
R_ClearFlares.
void RB_AddFlare (void *surface, int fogNum, vec3_t point, vec3_t color, vec3_t normal, qboolean visible, qboolean isCorona)
This is called at surface tesselation time.
void RB_AddLightFlares (void)
RB_AddLightFlares.
void RB_RenderFlares (void)
Because flares are simulating an occular effect, they should be drawn after everything (all views) in the entire frame has been drawn.
void R_AddBrushModelInteractions (trRefEntity_t *ent, trRefLight_t *light)
Determine which dynamic lights may effect this bmodel.
void R_SetupEntityLighting (const trRefdef_t *refdef, trRefEntity_t *ent, vec3_t forcedOrigin)
Calculates all the lighting values that will be used by the Calc_* functions.
void R_SetupLightOrigin (trRefLight_t *light)
R_SetupLightOrigin.
void R_SetupLightLocalBounds (trRefLight_t *light)
R_SetupLightLocalBounds.
void R_SetupLightWorldBounds (trRefLight_t *light)
R_SetupLightWorldBounds.
void R_SetupLightView (trRefLight_t *light)
R_SetupLightView.
void R_SetupLightFrustum (trRefLight_t *light)
R_SetupLightFrustum.
void R_SetupLightProjection (trRefLight_t *light)
R_SetupLightProjection.
qboolean R_AddLightInteraction (trRefLight_t *light, surfaceType_t *surface, shader_t *surfaceShader, byte cubeSideBits, interactionType_t iaType)
R_AddLightInteraction.
void R_SortInteractions (trRefLight_t *light)
R_SortInteractions.
void R_SetupLightScissor (trRefLight_t *light)
Recturns the screen space rectangle taken by the box. (Clips the box to the near plane to have correct results even if the box intersects the near plane)
void R_SetupLightLOD (trRefLight_t *light)
R_SetupLightLOD.
void R_SetupLightShader (trRefLight_t *light)
R_SetupLightShader.
byte R_CalcLightCubeSideBits (trRefLight_t *light, vec3_t worldBounds[2])
R_CalcLightCubeSideBits.
int R_CullLightPoint (trRefLight_t *light, const vec3_t p)
R_CullLightPoint.
int R_CullLightTriangle (trRefLight_t *light, vec3_t verts[3])
R_CullLightTriangle.
int R_CullLightWorldBounds (trRefLight_t *light, vec3_t worldBounds[2])
R_CullLightWorldBounds.
void R_ComputeFinalAttenuation (shaderStage_t *pStage, trRefLight_t *light)
R_ComputeFinalAttenuation.
void R_SetFrameFog ()
R_SetFrameFog.
void RB_Fog (glfog_t *curfog)
RB_Fog.
void RB_FogOff ()
Allow disabling fog temporarily.
void RB_FogOn ()
RB_FogOn.
void RE_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
RE_SetFog.
void RE_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
RE_SetGlobalFog.
void RB_ProjectionShadowDeform ()
RB_ProjectionShadowDeform.
void R_InitSkyTexCoords (float heightCloud)
Called when a sky shader is parsed.
void RB_DrawSun (void)
RB_DrawSun.
srfGridMesh_t * R_SubdividePatchToGrid (int width, int height, srfVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
R_SubdividePatchToGrid.
srfGridMesh_t * R_GridInsertColumn (srfGridMesh_t *grid, int column, int row, vec3_t point, float loderror)
R_GridInsertColumn.
srfGridMesh_t * R_GridInsertRow (srfGridMesh_t *grid, int row, int column, vec3_t point, float loderror)
R_GridInsertRow.
void R_FreeSurfaceGridMesh (srfGridMesh_t *grid)
R_FreeSurfaceGridMesh.
int R_MarkFragments (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
R_MarkFragments.
qboolean R_CheckFBO (const FBO_t *fbo)
R_CheckFBO.
FBO_t * R_CreateFBO (const char *name, int width, int height)
R_CreateFBO.
void R_CreateFBOColorBuffer (FBO_t *fbo, int format, int index)
Framebuffer must be bound.
void R_CreateFBODepthBuffer (FBO_t *fbo, int format)
R_CreateFBODepthBuffer.
void R_CreateFBOStencilBuffer (FBO_t *fbo, int format)
R_CreateFBOStencilBuffer.
void R_AttachFBOTexture1D (int texId, int index)
R_AttachFBOTexture1D.
void R_AttachFBOTexture2D (int target, int texId, int index)
R_AttachFBOTexture2D.
void R_AttachFBOTexture3D (int texId, int index, int zOffset)
R_AttachFBOTexture3D.
void R_AttachFBOTextureDepth (int texId)
R_AttachFBOTextureDepth.
void R_CopyToFBO (FBO_t *from, FBO_t *to, GLuint mask, GLuint filter)
R_CopyToFBO.
void R_BindFBO (FBO_t *fbo)
R_BindFBO.
void R_BindNullFBO (void)
R_BindNullFBO.
void R_SetDefaultFBO (void)
R_SetDefaultFBO.
void R_InitFBOs (void)
R_InitFBOs.
void R_ShutdownFBOs (void)
R_ShutdownFBOs.
void R_FBOList_f (void)
R_FBOList_f.
VBO_t * R_CreateVBO (const char *name, byte *vertexes, int vertexesSize, vboUsage_t usage)
R_CreateVBO.
VBO_t * R_CreateVBO2 (const char *name, int numVertexes, srfVert_t *verts, uint32_t stateBits, vboUsage_t usage)
IBO_t * R_CreateIBO (const char *name, byte *indexes, int indexesSize, vboUsage_t usage)
R_CreateIBO.
IBO_t * R_CreateIBO2 (const char *name, int numTriangles, srfTriangle_t *triangles, vboUsage_t usage)
R_CreateIBO2.
void R_BindVBO (VBO_t *vbo)
R_BindVBO.
void R_BindNullVBO (void)
R_BindNullVBO.
void R_BindIBO (IBO_t *ibo)
R_BindIBO.
void R_BindNullIBO (void)
R_BindNullIBO.
void R_InitVBOs (void)
R_InitVBOs.
void R_VBOList_f (void)
R_VBOList_f.
void RE_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t *points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
Creates a new decal projector from a triangle.
void RE_ClearDecals (void)
Clears decals from the world and entities.
void R_TransformDecalProjector (decalProjector_t *in, vec3_t axis[3], vec3_t origin, decalProjector_t *out)
Transforms a decal projector.
qboolean R_TestDecalBoundingBox (decalProjector_t *dp, vec3_t mins, vec3_t maxs)
R_TestDecalBoundingBox.
qboolean R_TestDecalBoundingSphere (decalProjector_t *dp, vec3_t center, float radius2)
R_TestDecalBoundingSphere.
void R_ProjectDecalOntoSurface (decalProjector_t *dp, bspSurface_t *surf, bspModel_t *bmodel)
Projects a decal onto a world surface.
void R_AddDecalSurface (decal_t *decal)
Adds a decal surface to the scene.
void R_AddDecalSurfaces (bspModel_t *bmodel)
Adds decal surfaces to the scene.
void R_CullDecalProjectors (void)
Frustum culls decal projector list.
void R_InitNextFrame (void)
R_InitNextFrame.
void RE_ClearScene (void)
RE_ClearScene.
void RE_AddRefEntityToScene (const refEntity_t *ent)
RE_AddRefEntityToScene.
void RE_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
RE_AddPolyToScene.
void RE_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
RE_AddPolysToScene.
void RE_AddPolyBufferToScene (polyBuffer_t *pPolyBuffer)
RE_AddPolyBufferToScene.
void RE_AddDynamicLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
modified dlight system to support seperate radius and intensity
void RE_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
RE_AddCoronaToScene.
void RE_RenderScene (const refdef_t *fd)
Draw a 3D view into a part of the window, then return to 2D drawing.
void R_InitAnimations (void)
R_InitAnimations.
qhandle_t RE_RegisterAnimation (const char *name)
RE_RegisterAnimation.
skelAnimation_t * R_GetAnimationByHandle (qhandle_t hAnim)
R_GetAnimationByHandle.
void R_AnimationList_f (void)
R_AnimationList_f.
void R_AddMD5Surfaces (trRefEntity_t *ent)
R_AddMD5Surfaces.
void R_AddMD5Interactions (trRefEntity_t *ent, trRefLight_t *light)
R_AddMD5Interactions.
int RE_CheckSkeleton (refSkeleton_t *skel, qhandle_t hModel, qhandle_t hAnim)
Check if the skeleton bones are the same in the model and animation and copy the parentIndex entries into the refSkeleton_t.
int RE_BuildSkeleton (refSkeleton_t *skel, qhandle_t hAnim, int startFrame, int endFrame, float frac, qboolean clearOrigin)
RE_BuildSkeleton.
int RE_BlendSkeleton (refSkeleton_t *skel, const refSkeleton_t *blend, float frac)
RE_BlendSkeleton.
int RE_AnimNumFrames (qhandle_t hAnim)
RE_AnimNumFrames.
int RE_AnimFrameRate (qhandle_t hAnim)
RE_AnimFrameRate.
void R_MDM_AddAnimSurfaces (trRefEntity_t *ent)
R_MDM_AddAnimSurfaces.
void R_AddMDMInteractions (trRefEntity_t *ent, trRefLight_t *light)
R_AddMDMInteractions.
int R_MDM_GetBoneTag (orientation_t *outTag, mdmModel_t *mdm, int startTagIndex, const refEntity_t *refent, const char *tagName)
R_MDM_GetBoneTag.
void Tess_MDM_SurfaceAnim (mdmSurfaceIntern_t *surface)
Tess_MDM_SurfaceAnim.
void Tess_SurfaceVBOMDMMesh (srfVBOMDMMesh_t *surface)
Tess_SurfaceVBOMDMMesh.
void R_TransformWorldToClip (const vec3_t src, const float *cameraViewMatrix, const float *projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformWorldToClip.
void R_TransformModelToClip (const vec3_t src, const float *modelMatrix, const float *projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformModelToClip.
void R_TransformClipToWindow (const vec4_t clip, const viewParms_t *view, vec4_t normalized, vec4_t window)
R_TransformClipToWindow.
float R_ProjectRadius (float r, vec3_t location)
R_ProjectRadius.
qboolean ShaderRequiresCPUDeforms (const shader_t *shader)
ShaderRequiresCPUDeforms.
void Tess_DeformGeometry ()
Tess_DeformGeometry.
float RB_EvalWaveForm (const waveForm_t *wf)
Evaluates a given waveForm_t, referencing backEnd.refdef.time directly.
float RB_EvalWaveFormClamped (const waveForm_t *wf)
RB_EvalWaveFormClamped.
float RB_EvalExpression (const expression_t *exp, float defaultValue)
RB_EvalExpression.
void RB_CalcTexMatrix (const textureBundle_t *bundle, mat4_t matrix)
RB_CalcTexMatrix.
void R_LoadJPG (const char *filename, unsigned char **pic, int *width, int *height, byte alphaByte)
R_LoadJPG.
size_t RE_SaveJPGToBuffer (byte *buffer, size_t bufSize, int quality, int image_width, int image_height, byte *image_buffer, int padding)
Encodes JPEG from image in image_buffer and writes to buffer. Expects RGB input data.
void RE_SaveJPG (const char *filename, int quality, int image_width, int image_height, byte *image_buffer, int padding)
RE_SaveJPG.
void R_LoadPNG (const char *name, byte **pic, int *width, int *height, byte alphaByte)
The PNG loader.
void R_LoadBMP (const char *name, byte **pic, int *width, int *height, byte alphaByte)
R_LoadBMP.
void R_LoadTGA (const char *name, byte **pic, int *width, int *height, byte alphaByte)
R_LoadTGA.
void R_LoadPCX (const char *filename, byte **pic, int *width, int *height, byte alphaByte)
R_LoadPCX.
void RB_ExecuteRenderCommands (const void *data)
RB_ExecuteRenderCommands.
void * R_GetCommandBuffer (unsigned int bytes)
Make sure there is enough command space, waiting on the render thread if needed.
void R_IssuePendingRenderCommands (void)
Issue any pending commands and wait for them to complete. After exiting, the render thread will have completed its work and will remain idle and the main thread is free to issue OpenGL calls until R_IssueRenderCommands is called.
void R_AddDrawViewCmd (void)
R_AddDrawViewCmd.
void RE_SetColor (const float *rgba)
Passing NULL will set the color to white.
void RE_SetClipRegion (const float *region)
RE_SetClipRegion.
void RE_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
RE_StretchPic.
void RE_RotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
RE_RotatedPic.
void RE_StretchPicGradient (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float *gradientColor, int gradientType)
RE_StretchPicGradient.
void RE_2DPolyies (polyVert_t *verts, int numverts, qhandle_t hShader)
RE_2DPolyies.
const void * RB_TakeVideoFrameCmd (const void *data)
RB_TakeVideoFrameCmd.
void RE_TakeVideoFrame (int width, int height, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
RE_TakeVideoFrame.
void R_BuildCubeMaps (void)
R_BuildCubeMaps.
void R_FindTwoNearestCubeMaps (const vec3_t position, cubemapProbe_t **cubeProbe1, cubemapProbe_t **cubeProbe2, float *distance1, float *distance2)
R_FindTwoNearestCubeMaps.
void FreeVertexHashTable (vertexHash_t **hashTable)
FreeVertexHashTable.
void RE_RenderToTexture (int textureid, int x, int y, int w, int h)
RE_RenderToTexture.
void RE_Finish (void)
RE_Finish.
void LoadRGBEToFloats (const char *name, float **pic, int *width, int *height, qboolean doGamma, qboolean toneMap, qboolean compensate)
LoadRGBEToFloats.
void LoadRGBEToHalfs (const char *name, unsigned short **halfImage, int *width, int *height)
LoadRGBEToHalfs.
void Com_InitGrowList (growList_t *list, int maxElements)
Com_InitGrowList.
void Com_DestroyGrowList (growList_t *list)
Com_DestroyGrowList.
int Com_AddToGrowList (growList_t *list, void *data)
Com_AddToGrowList.
void * Com_GrowListElement (const growList_t *list, int index)
Com_GrowListElement.
int Com_IndexForGrowListElement (const growList_t *list, const void *element)
Com_IndexForGrowListElement.
void GLSL_VertexAttribsState (uint32_t stateBits)
GLSL_VertexAttribsState.
void GLSL_VertexAttribPointers (uint32_t attribBits)
GLSL_VertexAttribPointers.
void GLSL_SelectTexture (shaderProgram_t *program, texture_def_t tex)
GLSL_SelectTexture.
void GLSL_SetUniformBoolean (shaderProgram_t *program, int uniformNum, GLboolean value)
GLSL_SetUniformBoolean.
void GLSL_SetUniformInt (shaderProgram_t *program, int uniformNum, GLint value)
GLSL_SetUniformInt.
void GLSL_SetUniformFloat (shaderProgram_t *program, int uniformNum, GLfloat value)
GLSL_SetUniformFloat.
void GLSL_SetUniformDouble (shaderProgram_t *program, int uniformNum, GLdouble value)
GLSL_SetUniformDouble.
void GLSL_SetUniformFloat5 (shaderProgram_t *program, int uniformNum, const vec5_t v)
GLSL_SetUniformFloat5.
void GLSL_SetUniformVec2 (shaderProgram_t *program, int uniformNum, const vec2_t v)
GLSL_SetUniformVec2.
void GLSL_SetUniformVec3 (shaderProgram_t *program, int uniformNum, const vec3_t v)
GLSL_SetUniformVec3.
void GLSL_SetUniformVec4 (shaderProgram_t *program, int uniformNum, const vec4_t v)
GLSL_SetUniformVec4.
void GLSL_SetUniformMatrix16 (shaderProgram_t *program, int uniformNum, const mat4_t matrix)
GLSL_SetUniformMatrix16.
void GLSL_SetUniformFloatARR (shaderProgram_t *program, int uniformNum, float *floatarray, int arraysize)
GLSL_SetUniformFloatARR.
void GLSL_SetUniformVec4ARR (shaderProgram_t *program, int uniformNum, vec4_t *vectorarray, int arraysize)
GLSL_SetUniformVec4ARR.
void GLSL_SetUniformMatrix16ARR (shaderProgram_t *program, int uniformNum, mat4_t *matrixarray, int arraysize)
GLSL_SetUniformMatrix16ARR.
void GLSL_SetMacroState (programInfo_t *programlist, int macro, int enabled)
GLSL_SetMacroState.
void GLSL_SetMacroStates (programInfo_t *programlist, int numMacros,...)
GLSL_SetMacroStates.
void GLSL_SelectPermutation (programInfo_t *programlist)
GLSL_SelectPermutation.
void GLSL_SetRequiredVertexPointers (programInfo_t *programlist)
GLSL_SetRequiredVertexPointers.
void GLSL_SetUniform_DeformParms (deformStage_t deforms[], int numDeforms)
GLSL_SetUniform_DeformParms.
void GLSL_SetUniform_ColorModulate (programInfo_t *prog, int colorGen, int alphaGen)
GLSL_SetUniform_ColorModulate.
void GLSL_SetUniform_AlphaTest (uint32_t stateBits)
GLSL_SetUniform_AlphaTest.
Variables
shadowState_t shadowState
void(* rb_surfaceTable [SF_NUM_SURFACE_TYPES])(void *)
const float mdmLODResolutions [MD3_MAX_LODS]
refimport_t ri
int gl_filter_min
int gl_filter_max
trPrograms_t trProg
const mat4_t quakeToOpenGLMatrix
Convert from our coordinate system (looking down X) to OpenGL's coordinate system (looking down -Z)
const mat4_t openGLToQuakeMatrix
Inverse of quakeToOpenGL matrix.
const mat4_t quakeToD3DMatrix
const mat4_t flipZMatrix
const GLenum geometricRenderTargets []
int shadowMapResolutions [5]
int sunShadowMapResolutions [5]
backEndState_t backEnd
trGlobals_t tr
glconfig_t glConfig
outside of TR since it shouldn't be cleared during ref re-init
glconfig2_t glConfig2
glstate_t glState
outside of TR since it shouldn't be cleared during ref re-init
cvar_t * r_railCoreWidth
cvar_t * r_lodTest
cvar_t * r_wolfFog
cvar_t * r_noFog
cvar_t * r_forceAmbient
cvar_t * r_ambientScale
cvar_t * r_lightScale
cvar_t * r_debugLight
cvar_t * r_staticLight
static lights enabled/disabled
cvar_t * r_dynamicLightShadows
cvar_t * r_precomputedLighting
cvar_t * r_vertexLighting
cvar_t * r_compressDiffuseMaps
cvar_t * r_compressSpecularMaps
cvar_t * r_compressNormalMaps
cvar_t * r_heatHazeFix
cvar_t * r_noMarksOnTrisurfs
cvar_t * r_drawpolies
disable/enable world rendering
cvar_t * r_noLightScissors
cvar_t * r_noLightVisCull
cvar_t * r_noInteractionSort
cvar_t * r_extOcclusionQuery
cvar_t * r_extTextureNonPowerOfTwo
cvar_t * r_extDrawBuffers
cvar_t * r_extVertexArrayObject
cvar_t * r_extHalfFloatPixel
cvar_t * r_extTextureFloat
cvar_t * r_extStencilWrap
cvar_t * r_extStencilTwoSide
cvar_t * r_extDepthBoundsTest
cvar_t * r_extFramebufferObject
cvar_t * r_extPackedDepthStencil
cvar_t * r_extFramebufferBlit
cvar_t * r_extGenerateMipmap
cvar_t * r_collapseStages
cvar_t * r_specularExponent
cvar_t * r_specularExponent2
cvar_t * r_specularScale
cvar_t * r_normalScale
cvar_t * r_normalMapping
cvar_t * r_wrapAroundLighting
cvar_t * r_diffuseLighting
cvar_t * r_rimLighting
cvar_t * r_rimExponent
cvar_t * r_softShadows
cvar_t * r_shadowBlur
cvar_t * r_shadowMapQuality
cvar_t * r_shadowMapSizeUltra
cvar_t * r_shadowMapSizeVeryHigh
cvar_t * r_shadowMapSizeHigh
cvar_t * r_shadowMapSizeMedium
cvar_t * r_shadowMapSizeLow
cvar_t * r_shadowMapSizeSunUltra
cvar_t * r_shadowMapSizeSunVeryHigh
cvar_t * r_shadowMapSizeSunHigh
cvar_t * r_shadowMapSizeSunMedium
cvar_t * r_shadowMapSizeSunLow
cvar_t * r_shadowOffsetFactor
cvar_t * r_shadowOffsetUnits
cvar_t * r_shadowLodBias
cvar_t * r_shadowLodScale
cvar_t * r_noShadowPyramids
cvar_t * r_cullShadowPyramidFaces
cvar_t * r_cullShadowPyramidCurves
cvar_t * r_cullShadowPyramidTriangles
cvar_t * r_debugShadowMaps
cvar_t * r_noShadowFrustums
cvar_t * r_noLightFrustums
cvar_t * r_shadowMapLuminanceAlpha
cvar_t * r_shadowMapLinearFilter
cvar_t * r_shadowMapDepthScale
cvar_t * r_parallelShadowSplits
cvar_t * r_parallelShadowSplitWeight
cvar_t * r_stitchCurves
cvar_t * r_skipLightBuffer
cvar_t * r_showShadowVolumes
cvar_t * r_showShadowLod
cvar_t * r_showShadowMaps
cvar_t * r_showSkeleton
cvar_t * r_showEntityTransforms
cvar_t * r_showLightTransforms
cvar_t * r_showLightInteractions
cvar_t * r_showLightScissors
cvar_t * r_showLightBatches
cvar_t * r_showLightGrid
cvar_t * r_showOcclusionQueries
cvar_t * r_showBatches
cvar_t * r_showLightMaps
render lightmaps only
cvar_t * r_showCubeProbes
cvar_t * r_showBspNodes
cvar_t * r_showParallelShadowSplits
cvar_t * r_showDecalProjectors
cvar_t * r_vboFaces
cvar_t * r_vboCurves
cvar_t * r_vboTriangles
cvar_t * r_vboShadows
cvar_t * r_vboLighting
cvar_t * r_vboModels
cvar_t * r_vboVertexSkinning
cvar_t * r_vboSmoothNormals
cvar_t * r_vboFoliage
cvar_t * r_worldInlineModels
cvar_t * r_parallaxMapping
cvar_t * r_parallaxDepthScale
cvar_t * r_dynamicBspOcclusionCulling
cvar_t * r_dynamicEntityOcclusionCulling
cvar_t * r_dynamicLightOcclusionCulling
cvar_t * r_chcMaxPrevInvisNodesBatchSize
cvar_t * r_chcMaxVisibleFrames
cvar_t * r_chcVisibilityThreshold
cvar_t * r_chcIgnoreLeaves
cvar_t * r_hdrRendering
cvar_t * r_hdrMinLuminance
cvar_t * r_hdrMaxLuminance
cvar_t * r_hdrKey
cvar_t * r_hdrContrastThreshold
cvar_t * r_hdrContrastOffset
cvar_t * r_hdrLightmap
cvar_t * r_hdrLightmapExposure
cvar_t * r_hdrLightmapGamma
cvar_t * r_hdrLightmapCompensate
cvar_t * r_hdrToneMappingOperator
cvar_t * r_hdrGamma
cvar_t * r_hdrDebug
cvar_t * r_screenSpaceAmbientOcclusion
cvar_t * r_depthOfField
cvar_t * r_reflectionMapping
cvar_t * r_highQualityNormalMapping
cvar_t * r_bloom
cvar_t * r_bloomBlur
cvar_t * r_bloomPasses
cvar_t * r_rotoscope
cvar_t * r_cameraPostFX
cvar_t * r_cameraVignette
cvar_t * r_cameraFilmGrainScale
cvar_t * r_evsmPostProcess
cvar_t * r_recompileShaders
cvar_t * r_rotoscopeBlur
cvar_t * r_materialScan
cvar_t * r_smoothNormals
shaderCommands_t tess
backEndData_t * backEndData
the second one may not be allocated
Macro Definition Documentation
#define ATTR_DECL
Definition at line 1605 of file tr_local.h.
#define BUFFER_OFFSET (i) ((char *)NULL + (i))
Definition at line 54 of file tr_local.h.
Referenced by GLSL_SetUniform_ColorModulate(), GLSL_VertexAttribPointers(), Tess_DrawElements(), Tess_SurfaceFace(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), and Tess_SurfaceTriangles().
#define CALC_REDUNDANT_SHADOWVERTS 0
Definition at line 73 of file tr_local.h.
#define CONTENTS_NODE -1
Definition at line 2574 of file tr_local.h.
#define DECAL_MASK (MAX_DECALS - 1)
Definition at line 4797 of file tr_local.h.
#define DEFAULT_FOG_EXP_DENSITY 0.5
Definition at line 3320 of file tr_local.h.
Referenced by R_InitFogTable().
#define DRAWSURF_MASK (MAX_DRAWSURFS - 1)
Definition at line 3268 of file tr_local.h.
#define FOG_TABLE_SIZE 256
Definition at line 3318 of file tr_local.h.
Referenced by R_FogFactor(), and R_InitFogTable().
#define FUNCTABLE_MASK (FUNCTABLE_SIZE - 1)
Definition at line 3324 of file tr_local.h.
#define FUNCTABLE_SIZE 4096
% 1024
Definition at line 3322 of file tr_local.h.
#define FUNCTABLE_SIZE2 12
% 10
Definition at line 3323 of file tr_local.h.
#define GL_CheckErrors (void) GL_CheckErrors_(__FILE__, __LINE__)
Definition at line 4035 of file tr_local.h.
Referenced by EntityOcclusionResultAvailable(), GetEntityOcclusionQueryResult(), GetLightOcclusionQueryResult(), GetOcclusionQueryResult(), GLimp_InitExtensionsR2(), GLSL_BuildGPUShaderText(), GLSL_FinishGPUShader(), IssueEntityMultiOcclusionQueries(), IssueEntityOcclusionQuery(), IssueLightMultiOcclusionQueries(), IssueLightOcclusionQuery(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), LightOcclusionResultAvailable(), R_BindNullVBO(), R_CoherentHierachicalCulling(), R_CreateFBOColorBuffer(), R_CreateFBODepthBuffer(), R_CreateFBOPackedDepthStencilBuffer(), R_CreateFBOStencilBuffer(), R_CreateIBO(), R_CreateIBO2(), R_CreateVBO(), R_CreateVBO2(), R_InitFBOs(), R_InitVBOs(), R_LoadDDSImageData(), R_LoadLightmapsExternal(), R_UploadImage(), RB_CalculateAdaptation(), RB_CameraPostFX(), RB_CollectBspOcclusionQueries(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderDrawSurfaces(), RB_RenderEntityOcclusionQueries(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_RenderView(), RB_RenderViewFront(), RB_ShowImages(), RE_StretchRaw(), RE_UploadCinematic(), Render_lightVolume(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), ResultAvailable(), Tess_DeformGeometry(), Tess_InstantQuad(), Tess_UpdateVBOs(), and Upload32().
#define GL_INDEX_TYPE GL_UNSIGNED_INT
Definition at line 47 of file tr_local.h.
#define GL_JOIN ()
Definition at line 4913 of file tr_local.h.
Referenced by EntityOcclusionResultAvailable(), GetEntityOcclusionQueryResult(), GetLightOcclusionQueryResult(), LightOcclusionResultAvailable(), RB_CollectBspOcclusionQueries(), RB_RenderViewFront(), RB_SwapBuffers(), and RE_StretchRaw().
#define GLCOLOR_BLACK 0.0f, 0.0f, 0.0f, 1.0f
Definition at line 3994 of file tr_local.h.
Referenced by GL_SetDefaultState(), R_CoherentHierachicalCulling(), RB_DrawBuffer(), RB_RenderBloom(), and RB_RenderInteractionsShadowMapped().
#define GLCOLOR_BLUE 0.0f, 0.0f, 1.0f, 1.0f
Definition at line 3997 of file tr_local.h.
#define GLCOLOR_GREEN 0.0f, 1.0f, 0.0f, 1.0f
Definition at line 3996 of file tr_local.h.
#define GLCOLOR_NONE 0.0f, 0.0f, 0.0f, 0.0f
Definition at line 3999 of file tr_local.h.
Referenced by R_CoherentHierachicalCulling().
#define GLCOLOR_RED 1.0f, 0.0f, 0.0f, 1.0f
Definition at line 3995 of file tr_local.h.
#define GLCOLOR_WHITE 1.0f, 1.0f, 1.0f, 1.0f
Definition at line 3993 of file tr_local.h.
Referenced by RB_RenderInteractionsShadowMapped().
#define GLSTACK_MVM glState.modelViewMatrix[glState.stackIndex]
Definition at line 4042 of file tr_local.h.
Referenced by GL_LoadModelViewMatrix(), and GL_LoadProjectionMatrix().
#define GLSTACK_MVPM glState.modelViewProjectionMatrix[glState.stackIndex]
Definition at line 4038 of file tr_local.h.
Referenced by DrawTris(), GL_LoadModelViewMatrix(), GL_LoadProjectionMatrix(), R_CoherentHierachicalCulling(), RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RE_StretchRaw(), Render_lightVolume(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), and Tess_StageIteratorSky().
#define GLSTACK_PM glState.projectionMatrix[glState.stackIndex]
Definition at line 4040 of file tr_local.h.
Referenced by GL_LoadModelViewMatrix(), and GL_LoadProjectionMatrix().
#define HDR_ENABLED () ((r_hdrRendering->integer && glConfig2.textureFloatAvailable && glConfig2.framebufferObjectAvailable && glConfig2.framebufferBlitAvailable))
Definition at line 87 of file tr_local.h.
Referenced by R_CoherentHierachicalCulling(), R_CreateDeferredRenderFBOImages(), RB_RenderBloom(), RB_RenderGlobalFog(), RB_RenderViewFront(), and RE_AddRefEntityToScene().
#define ImageCopyBackBuffer (image) R_ImageCopyBack(image, 0, 0, image->uploadWidth, image->uploadHeight)
Definition at line 4102 of file tr_local.h.
Referenced by RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderDepthOfField(), RB_RenderGlobalFog(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_RenderViewFront(), and Render_lightVolume().
#define INTERACTION_MASK (MAX_INTERACTIONS - 1)
Definition at line 3271 of file tr_local.h.
Referenced by R_AddLightInteraction().
#define LIGHTMAP_2D -4
Definition at line 1336 of file tr_local.h.
#define LIGHTMAP_BY_VERTEX -3
Definition at line 1337 of file tr_local.h.
#define LIGHTMAP_NONE -1
Definition at line 1339 of file tr_local.h.
#define LIGHTMAP_WHITEIMAGE -2
Definition at line 1338 of file tr_local.h.
#define MACRO_ENUM
Definition at line 1678 of file tr_local.h.
#define MAX_ANIMATIONFILES 4096
Definition at line 3262 of file tr_local.h.
Referenced by R_AllocAnimation().
#define MAX_DECAL_PROJECTORS 128
includes decal projectors that will be culled out, hard limited to 32 active projectors because of bitmasks.
Definition at line 4794 of file tr_local.h.
#define MAX_DECAL_VERTS 10
worst case is triangle clipped by 6 planes
Definition at line 2193 of file tr_local.h.
#define MAX_DECALS 1024
Definition at line 4796 of file tr_local.h.
#define MAX_DRAWSURFS 0x10000
Definition at line 3267 of file tr_local.h.
#define MAX_ENTITY_DECALS 128
Definition at line 2195 of file tr_local.h.
#define MAX_EXPRESSION_OPS 32
Definition at line 1015 of file tr_local.h.
Referenced by ParseExpression(), and RB_EvalExpression().
#define MAX_FACE_POINTS 64
Definition at line 2160 of file tr_local.h.
#define MAX_FBOS 64
Definition at line 64 of file tr_local.h.
Referenced by R_CreateFBO().
#define MAX_GLSTACK 5
Definition at line 3326 of file tr_local.h.
Referenced by GL_PushMatrix(), and GL_SetDefaultState().
#define MAX_GRID_SIZE 65
max dimensions of a grid mesh in memory
Definition at line 2163 of file tr_local.h.
#define MAX_IMAGE_ANIMATIONS 16
Definition at line 1123 of file tr_local.h.
#define MAX_INTERACTIONS MAX_DRAWSURFS * 8
Definition at line 3270 of file tr_local.h.
Referenced by R_SortDrawSurfs().
#define MAX_LIGHTMAPS 256
Definition at line 3264 of file tr_local.h.
#define MAX_MOD_KNOWN 2048
Definition at line 3261 of file tr_local.h.
#define MAX_MULTIDRAW_PRIMITIVES 1000
Definition at line 4169 of file tr_local.h.
Referenced by Tess_DrawCurrent().
#define MAX_OCCLUSION_QUERIES 4096
Definition at line 62 of file tr_local.h.
Referenced by IssueEntityMultiOcclusionQueries(), IssueEntityOcclusionQuery(), IssueLightMultiOcclusionQueries(), IssueLightOcclusionQuery(), R_Init(), and RE_Shutdown().
#define MAX_PART_MODELS 7
Definition at line 1920 of file tr_local.h.
#define MAX_PATCH_SIZE 64
max dimensions of a patch mesh in map file
Definition at line 2162 of file tr_local.h.
#define MAX_POLYBUFFERS 4096
Definition at line 4799 of file tr_local.h.
#define MAX_POLYS 16384
was 4096
Definition at line 4790 of file tr_local.h.
#define MAX_POLYVERTS 32768
was 8192
Definition at line 4791 of file tr_local.h.
#define MAX_RENDER_COMMANDS (0x40000 * 8)
was 0x40000
Definition at line 4593 of file tr_local.h.
#define MAX_SHADER_DEFORM_PARMS (1 + MAX_SHADER_DEFORMS + MAX_SHADER_DEFORMS * 8)
Definition at line 1068 of file tr_local.h.
Referenced by GLSL_BuildShaderExtraDef(), and GLSL_SetUniform_DeformParms().
#define MAX_SHADER_DEFORMS 3
Definition at line 1067 of file tr_local.h.
#define MAX_SHADER_STAGES 16
Definition at line 60 of file tr_local.h.
#define MAX_SHADER_TABLES 1024
Definition at line 59 of file tr_local.h.
Referenced by GeneratePermanentShaderTable().
#define MAX_SHADERS (1 << 12)
Definition at line 56 of file tr_local.h.
#define MAX_SHADOWMAPS 5
Definition at line 69 of file tr_local.h.
Referenced by GLSL_BuildShaderExtraDef(), R_CreateShadowMapFBOImage(), R_InitFBOs(), and R_Register().
#define MAX_SKIN_SURFACES 256
Max surfaces per-skin.
This is an arbitry limit. Vanilla Q3 only supported 32 surfaces in skins but failed to enforce the maximum limit when reading skin files. It was possile to use more than 32 surfaces which accessed out of bounds memory past end of skin->surfaces hunk block.
Definition at line 1908 of file tr_local.h.
#define MAX_SKINS 1024
Definition at line 3265 of file tr_local.h.
#define MAX_UNIFORM_VALUES 64
Definition at line 1696 of file tr_local.h.
Referenced by GLSL_ParseDefinition().
#define MAX_USED_DECAL_PROJECTORS 32
Definition at line 4795 of file tr_local.h.
#define MAX_VIEWS 10
Definition at line 67 of file tr_local.h.
Referenced by R_LoadNodesAndLeafs(), R_RenderView(), and RE_Shutdown().
#define MAX_VISCOUNTS 5
Definition at line 66 of file tr_local.h.
Referenced by R_CreateClusters(), R_MarkLeaves(), R_ShutdownVBOs(), R_VBOList_f(), and RE_BeginRegistration().
#define MAX_WORLD_DECALS 1024
Definition at line 2194 of file tr_local.h.
#define MD5_IDENTSTRING "MD5Version"
Definition at line 2926 of file tr_local.h.
#define MD5_VERSION 10
Definition at line 2927 of file tr_local.h.
Referenced by R_LoadMD5(), and R_LoadMD5Anim().
#define MIN_POLYS 4096
Definition at line 4786 of file tr_local.h.
#define MIN_POLYVERTS 8192
Definition at line 4787 of file tr_local.h.
#define MODEL_MATRIX backEnd.orientation.transformMatrix
Definition at line 4044 of file tr_local.h.
Referenced by RB_RenderDebugUtils().
#define R2_TIMING (rule) if (r_speeds->integer == rule)
Definition at line 4914 of file tr_local.h.
Referenced by RB_RenderEntityOcclusionQueries(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), and RB_RenderViewFront().
#define R2_TIMING_SIMPLE () if (r_speeds->integer)
Definition at line 4915 of file tr_local.h.
Referenced by R_CoherentHierachicalCulling(), and RE_StretchRaw().
#define REF_CUBEMAP_SIZE 32
Definition at line 89 of file tr_local.h.
Referenced by R_BuildCubeMaps(), R_CreateColorCubeImages(), and R_LoadCubeProbe().
#define REF_CUBEMAP_STORE_SIDE (REF_CUBEMAP_STORE_SIZE / REF_CUBEMAP_SIZE)
Definition at line 91 of file tr_local.h.
Referenced by R_BuildCubeMaps(), and R_LoadCubeProbe().
#define REF_CUBEMAP_STORE_SIZE 1024
Definition at line 90 of file tr_local.h.
Referenced by R_BuildCubeMaps(), and R_LoadCubeProbe().
#define REF_CUBEMAPS_PER_FILE (REF_CUBEMAP_STORE_SIDE * REF_CUBEMAP_STORE_SIDE)
Definition at line 92 of file tr_local.h.
Referenced by R_LoadCubeProbe().
#define SelectProgram (program) Ren_LogComment("SelectProgram called: (%s:%d)\n", __FILE__, __LINE__); GLSL_SelectPermutation(program)
Definition at line 4905 of file tr_local.h.
#define SelectTexture (tex) GLSL_SelectTexture(trProg.selectedProgram, tex)
Definition at line 4892 of file tr_local.h.
Referenced by BindCubeMaps(), DrawTris(), R_CoherentHierachicalCulling(), RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_ShowImages(), RE_StretchRaw(), Render_lightVolume(), and Tess_SurfaceBeam().
#define SetMacrosAndSelectProgram (program, ...) GLSL_SetMacroStates(program, NUMARGS(__VA_ARGS__), ## __VA_ARGS__); SelectProgram(program)
Definition at line 4906 of file tr_local.h.
Referenced by DrawTris(), R_CoherentHierachicalCulling(), RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_ShowImages(), RE_StretchRaw(), Render_lightVolume(), Tess_StageIteratorSky(), and Tess_SurfaceBeam().
#define SetUniformBoolean (uniformNum, value) GLSL_SetUniformBoolean(trProg.selectedProgram, uniformNum, value)
Definition at line 4893 of file tr_local.h.
#define SetUniformFloat (uniformNum, value) GLSL_SetUniformFloat(trProg.selectedProgram, uniformNum, value)
Definition at line 4895 of file tr_local.h.
Referenced by BindCubeMaps(), DrawTris(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderRotoscope(), and Render_lightVolume().
#define SetUniformFloat5 (uniformNum, value) GLSL_SetUniformFloat5(trProg.selectedProgram, uniformNum, value)
Definition at line 4896 of file tr_local.h.
#define SetUniformFloatARR (uniformNum, value, size) GLSL_SetUniformFloatARR(trProg.selectedProgram, uniformNum, value, size)
Definition at line 4901 of file tr_local.h.
#define SetUniformInt (uniformNum, value) GLSL_SetUniformInt(trProg.selectedProgram, uniformNum, value)
Definition at line 4894 of file tr_local.h.
Referenced by GLSL_SetUniform_AlphaTest(), RB_RenderBspOcclusionQueries(), and RB_RenderDebugUtils().
#define SetUniformMatrix16 (uniformNum, value) GLSL_SetUniformMatrix16(trProg.selectedProgram, uniformNum, value)
Definition at line 4900 of file tr_local.h.
Referenced by DrawTris(), R_CoherentHierachicalCulling(), RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_ShowImages(), RE_StretchRaw(), Render_lightVolume(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), and Tess_StageIteratorSky().
#define SetUniformMatrix16ARR (uniformNum, value, size) GLSL_SetUniformMatrix16ARR(trProg.selectedProgram, uniformNum, value, size)
Definition at line 4903 of file tr_local.h.
Referenced by DrawTris().
#define SetUniformVec2 (uniformNum, value) GLSL_SetUniformVec2(trProg.selectedProgram, uniformNum, value)
Definition at line 4897 of file tr_local.h.
#define SetUniformVec3 (uniformNum, value) GLSL_SetUniformVec3(trProg.selectedProgram, uniformNum, value)
Definition at line 4898 of file tr_local.h.
Referenced by RB_RenderDebugUtils(), RB_RenderGlobalFog(), Render_lightVolume(), and Tess_StageIteratorSky().
#define SetUniformVec4 (uniformNum, value) GLSL_SetUniformVec4(trProg.selectedProgram, uniformNum, value)
Definition at line 4899 of file tr_local.h.
Referenced by clipPortalPlane(), DrawTris(), GLSL_SetUniform_ColorModulate(), IssueMultiOcclusionQueries(), R_CoherentHierachicalCulling(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), and RE_StretchRaw().
#define SetUniformVec4ARR (uniformNum, value, size) GLSL_SetUniformVec4ARR(trProg.selectedProgram, uniformNum, value, size)
Definition at line 4902 of file tr_local.h.
#define SHADER_PROGRAM_T_OFS (x) ((size_t)&(((shaderProgram_t *)0)->x))
Definition at line 1801 of file tr_local.h.
#define SHADERS_MASK (MAX_SHADERS - 1)
Definition at line 57 of file tr_local.h.
#define TEX_DECL
Definition at line 1704 of file tr_local.h.
#define TR_MAX_TEXMODS 4
Definition at line 1043 of file tr_local.h.
#define UNIFORM_ENUM
Definition at line 1690 of file tr_local.h.
#define WORLD_MAX_SKY_NODES 32
Definition at line 2702 of file tr_local.h.
Typedef Documentation
bspNode_t
bspSurface_t
BufferImage_t
Todo:
TODO: add this to the framebuffer structure
typedef byte color4ub_t[4]
Definition at line 4155 of file tr_local.h.
typedef struct corona_s corona_t
typedef struct decal_s decal_t
typedef struct decalProjector_s decalProjector_t
typedef struct drawSurf_s drawSurf_t
FBO_t
typedef byte fcolor4ub_t[4]
foliage surfaces are autogenerated from models into geometry lists by q3map2
Definition at line 2381 of file tr_local.h.
typedef cplane_t frustum_t[6]
Definition at line 132 of file tr_local.h.
typedef unsigned int glIndex_t
Definition at line 48 of file tr_local.h.
IBO_t
typedef struct image_s image_t
interaction_t
An interaction is a node between a light and any surface.
interactionCache_t
An interactionCache is a node between a light and a precached world surface.
interactionVBO_t
link_t
md5Animation_t
md5Model_t
mdmModel_t
mdmSurfaceIntern_t
mdvModel_t
mdvSurface_t
typedef struct model_s model_t
programInfo_t
screenRect_t
typedef struct shader_s shader_t
typedef struct shaderCommands_s shaderCommands_t
typedef struct shaderProgram_s shaderProgram_t
shaderProgramList_t
shaderTable_t
typedef struct skin_s skin_t
typedef struct srfDecal_s srfDecal_t
typedef struct srfFlare_s srfFlare_t
typedef struct srfGeneric_s srfGeneric_t
typedef struct srfGridMesh_s srfGridMesh_t
typedef struct srfPoly_s srfPoly_t
typedef struct srfPolyBuffer_s srfPolyBuffer_t
srfVBOMD5Mesh_t
srfVBOMDMMesh_t
srfVBOMDVMesh_t
srfVBOMesh_t
stageVars_t
stencil_t
Shifts.
trPrograms_t
trRefLight_t
A trRefLight_t has all the information passed in by the client game, as well as some locally derived info.
uniformInfo_t
uniformValue_t
VBO_t
vertexHash_t
Useful helper struct.
Enumeration Type Documentation
anonymous enum
Enumerator
CUBESIDE_PX
CUBESIDE_PY
CUBESIDE_PZ
CUBESIDE_NX
CUBESIDE_NY
CUBESIDE_NZ
CUBESIDE_CLIPALL
Definition at line 134 of file tr_local.h.
anonymous enum
Enumerator
IF_NONE
IF_NOPICMIP
IF_NOCOMPRESSION
IF_ALPHA
IF_NORMALMAP
IF_RGBA16F
IF_RGBA32F
IF_LA16F
IF_LA32F
IF_ALPHA16F
IF_ALPHA32F
IF_DEPTH16
IF_DEPTH24
IF_DEPTH32
IF_PACKED_DEPTH24_STENCIL8
IF_LIGHTMAP
IF_RGBA16
IF_RGBE
IF_ALPHATEST
IF_DISPLACEMAP
Definition at line 531 of file tr_local.h.
anonymous enum
Enumerator
TB_COLORMAP
TB_DIFFUSEMAP
TB_NORMALMAP
TB_SPECULARMAP
MAX_TEXTURE_BUNDLES
Definition at line 1125 of file tr_local.h.
anonymous enum
Enumerator
ATTR_INDEX_POSITION
ATTR_INDEX_TEXCOORD0
ATTR_INDEX_TEXCOORD1
ATTR_INDEX_TANGENT
ATTR_INDEX_BINORMAL
ATTR_INDEX_NORMAL
ATTR_INDEX_COLOR
ATTR_INDEX_BONE_INDEXES
ATTR_INDEX_BONE_WEIGHTS
ATTR_INDEX_POSITION2
ATTR_INDEX_TANGENT2
ATTR_INDEX_BINORMAL2
ATTR_INDEX_NORMAL2
ATTR_INDEX_COUNT
Definition at line 1496 of file tr_local.h.
anonymous enum
Enumerator
GLS_SRCBLEND_ZERO
GLS_SRCBLEND_ONE
GLS_SRCBLEND_DST_COLOR
GLS_SRCBLEND_ONE_MINUS_DST_COLOR
GLS_SRCBLEND_SRC_ALPHA
GLS_SRCBLEND_ONE_MINUS_SRC_ALPHA
GLS_SRCBLEND_DST_ALPHA
GLS_SRCBLEND_ONE_MINUS_DST_ALPHA
GLS_SRCBLEND_ALPHA_SATURATE
GLS_SRCBLEND_BITS
GLS_DSTBLEND_ZERO
GLS_DSTBLEND_ONE
GLS_DSTBLEND_SRC_COLOR
GLS_DSTBLEND_ONE_MINUS_SRC_COLOR
GLS_DSTBLEND_SRC_ALPHA
GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA
GLS_DSTBLEND_DST_ALPHA
GLS_DSTBLEND_ONE_MINUS_DST_ALPHA
GLS_DSTBLEND_BITS
GLS_DEPTHMASK_TRUE
GLS_POLYMODE_LINE
GLS_DEPTHTEST_DISABLE
GLS_DEPTHFUNC_LESS
GLS_DEPTHFUNC_EQUAL
GLS_DEPTHFUNC_BITS
GLS_ATEST_GT_0
GLS_ATEST_LT_128
GLS_ATEST_GE_128
GLS_ATEST_BITS
GLS_REDMASK_FALSE
GLS_GREENMASK_FALSE
GLS_BLUEMASK_FALSE
GLS_ALPHAMASK_FALSE
GLS_COLORMASK_BITS
GLS_STENCILTEST_ENABLE
GLS_DEFAULT
Definition at line 1521 of file tr_local.h.
anonymous enum
Enumerator
GLSL_BOOL
GLSL_INT
GLSL_FLOAT
GLSL_FLOAT5
GLSL_DOUBLE
GLSL_VEC2
GLSL_VEC3
GLSL_VEC4
GLSL_MAT16
GLSL_FLOATARR
GLSL_VEC4ARR
GLSL_MAT16ARR
Definition at line 1656 of file tr_local.h.
anonymous enum
Enumerator
COMPONENT_BIT_TX
COMPONENT_BIT_TY
COMPONENT_BIT_TZ
COMPONENT_BIT_QX
COMPONENT_BIT_QY
COMPONENT_BIT_QZ
Definition at line 3114 of file tr_local.h.
enum acff_t
Enumerator
ACFF_NONE
ACFF_MODULATE_RGB
ACFF_MODULATE_RGBA
ACFF_MODULATE_ALPHA
ACFF_NONE
ACFF_MODULATE_RGB
ACFF_MODULATE_RGBA
ACFF_MODULATE_ALPHA
ACFF_NONE
ACFF_MODULATE_RGB
ACFF_MODULATE_RGBA
ACFF_MODULATE_ALPHA
Definition at line 915 of file tr_local.h.
enum alphaGen_t
Enumerator
AGEN_IDENTITY
AGEN_SKIP
AGEN_ENTITY
AGEN_ONE_MINUS_ENTITY
AGEN_NORMALZFADE
AGEN_VERTEX
AGEN_ONE_MINUS_VERTEX
AGEN_LIGHTING_SPECULAR
AGEN_WAVEFORM
AGEN_PORTAL
AGEN_CONST
AGEN_IDENTITY
AGEN_ENTITY
AGEN_ONE_MINUS_ENTITY
AGEN_NORMALZFADE
AGEN_VERTEX
AGEN_ONE_MINUS_VERTEX
AGEN_WAVEFORM
AGEN_CONST
AGEN_CUSTOM
AGEN_IDENTITY
AGEN_SKIP
AGEN_ENTITY
AGEN_ONE_MINUS_ENTITY
AGEN_NORMALZFADE
AGEN_VERTEX
AGEN_ONE_MINUS_VERTEX
AGEN_LIGHTING_SPECULAR
AGEN_WAVEFORM
AGEN_PORTAL
AGEN_CONST
Definition at line 857 of file tr_local.h.
enum alphaTest_t
Enumerator
ATEST_NONE
ATEST_GT_0
ATEST_LT_128
ATEST_GE_128
Definition at line 927 of file tr_local.h.
enum animType_t
Enumerator
AT_BAD
AT_MD5
AT_PSA
Definition at line 3107 of file tr_local.h.
enum BuffetType_t
Enumerator
DEFAULT
DIFFUSE
NORMAL
SPECULAR
Definition at line 625 of file tr_local.h.
enum collapseType_t
Enumerator
COLLAPSE_none
COLLAPSE_genericMulti
COLLAPSE_lighting_DB
COLLAPSE_lighting_DBS
COLLAPSE_reflection_CB
COLLAPSE_color_lightmap
Definition at line 1189 of file tr_local.h.
enum colorGen_t
Enumerator
CGEN_BAD
CGEN_IDENTITY_LIGHTING
tr.identityLight
CGEN_IDENTITY
always (1,1,1,1)
CGEN_ENTITY
grabbed from entity's modulate field
CGEN_ONE_MINUS_ENTITY
grabbed from 1 - entity.modulate
CGEN_EXACT_VERTEX
tess.vertexColors
CGEN_VERTEX
tess.vertexColors * tr.identityLight
CGEN_ONE_MINUS_VERTEX
CGEN_WAVEFORM
programmatically generated
CGEN_LIGHTING_DIFFUSE
CGEN_FOG
standard fog
CGEN_CONST
fixed color
CGEN_BAD
CGEN_IDENTITY_LIGHTING
tr.identityLight
CGEN_IDENTITY
always (1,1,1,1)
CGEN_ENTITY
grabbed from entity's modulate field
CGEN_ONE_MINUS_ENTITY
grabbed from 1 - entity.modulate
CGEN_VERTEX
tess.vertexColors * tr.identityLight
CGEN_ONE_MINUS_VERTEX
CGEN_WAVEFORM
programmatically generated
CGEN_FOG
standard fog
CGEN_CONST
fixed color
CGEN_CUSTOM_RGB
like fixed color but generated dynamically, single arithmetic expression
CGEN_CUSTOM_RGBs
multiple expressions
CGEN_BAD
CGEN_IDENTITY_LIGHTING
tr.identityLight
CGEN_IDENTITY
always (1,1,1,1)
CGEN_ENTITY
grabbed from entity's modulate field
CGEN_ONE_MINUS_ENTITY
grabbed from 1 - entity.modulate
CGEN_EXACT_VERTEX
tess.vertexColors
CGEN_VERTEX
tess.vertexColors * tr.identityLight
CGEN_ONE_MINUS_VERTEX
CGEN_WAVEFORM
programmatically generated
CGEN_LIGHTING_DIFFUSE
CGEN_FOG
standard fog
CGEN_CONST
fixed color
Definition at line 876 of file tr_local.h.
enum cullResult_t
Enumerator
CULL_IN
completely unclipped
CULL_CLIP
clipped by one or more planes
CULL_OUT
completely outside the clipping planes
Definition at line 98 of file tr_local.h.
enum cullType_t
Enumerator
CT_FRONT_SIDED
CT_BACK_SIDED
CT_TWO_SIDED
CT_FRONT_SIDED
CT_BACK_SIDED
CT_TWO_SIDED
CT_FRONT_SIDED
CT_BACK_SIDED
CT_TWO_SIDED
Definition at line 1345 of file tr_local.h.
enum deferredShading_t
Enumerator
DS_DISABLED
traditional Doom 3 style rendering
DS_STANDARD
deferred rendering like in Stalker
Definition at line 81 of file tr_local.h.
enum deform_t
Enumerator
DEFORM_NONE
DEFORM_WAVE
DEFORM_NORMALS
DEFORM_BULGE
DEFORM_MOVE
DEFORM_PROJECTION_SHADOW
DEFORM_AUTOSPRITE
DEFORM_AUTOSPRITE2
DEFORM_TEXT0
DEFORM_TEXT1
DEFORM_TEXT2
DEFORM_TEXT3
DEFORM_TEXT4
DEFORM_TEXT5
DEFORM_TEXT6
DEFORM_TEXT7
DEFORM_NONE
DEFORM_WAVE
DEFORM_NORMALS
DEFORM_BULGE
DEFORM_MOVE
DEFORM_PROJECTION_SHADOW
DEFORM_AUTOSPRITE
DEFORM_AUTOSPRITE2
DEFORM_TEXT0
DEFORM_TEXT1
DEFORM_TEXT2
DEFORM_TEXT3
DEFORM_TEXT4
DEFORM_TEXT5
DEFORM_TEXT6
DEFORM_TEXT7
DEFORM_SPRITE
DEFORM_FLARE
DEFORM_NONE
DEFORM_WAVE
DEFORM_NORMALS
DEFORM_BULGE
DEFORM_MOVE
DEFORM_PROJECTION_SHADOW
DEFORM_AUTOSPRITE
DEFORM_AUTOSPRITE2
DEFORM_TEXT0
DEFORM_TEXT1
DEFORM_TEXT2
DEFORM_TEXT3
DEFORM_TEXT4
DEFORM_TEXT5
DEFORM_TEXT6
DEFORM_TEXT7
Definition at line 798 of file tr_local.h.
enum deformGen_t
deformVertexes types that can be handled by the GPU
Enumerator
DGEN_NONE
DGEN_WAVE_SIN
DGEN_WAVE_SQUARE
DGEN_WAVE_TRIANGLE
DGEN_WAVE_SAWTOOTH
DGEN_WAVE_INVERSE_SAWTOOTH
DGEN_WAVE_NOISE
DGEN_BULGE
DGEN_MOVE
Definition at line 824 of file tr_local.h.
enum deformType_t
Enumerator
DEFORM_TYPE_NONE
DEFORM_TYPE_CPU
DEFORM_TYPE_GPU
Definition at line 846 of file tr_local.h.
enum EGLCompileMacro
Enumerator
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Definition at line 1676 of file tr_local.h.
enum filterType_t
Enumerator
FT_DEFAULT
FT_LINEAR
FT_NEAREST
Definition at line 559 of file tr_local.h.
enum fogPass_t
Enumerator
FP_NONE
surface is translucent and will just be adjusted properly
FP_EQUAL
surface is opaque but possibly alpha tested
FP_LE
surface is trnaslucent, but still needs a fog pass (fog surface)
FP_NONE
surface is translucent and will just be adjusted properly
FP_EQUAL
surface is opaque but possibly alpha tested
FP_LE
surface is translucent, but still needs a fog pass (fog surface)
FP_NONE
surface is translucent and will just be adjusted properly
FP_EQUAL
surface is opaque but possibly alpha tested
FP_LE
surface is trnaslucent, but still needs a fog pass (fog surface)
Definition at line 1356 of file tr_local.h.
enum frustumBits_t
Enumerator
FRUSTUM_LEFT
FRUSTUM_RIGHT
FRUSTUM_BOTTOM
FRUSTUM_TOP
FRUSTUM_NEAR
FRUSTUM_FAR
FRUSTUM_PLANES
FRUSTUM_CLIPALL
Definition at line 120 of file tr_local.h.
enum genFunc_t
Enumerator
GF_NONE
GF_SIN
GF_SQUARE
GF_TRIANGLE
GF_SAWTOOTH
GF_INVERSE_SAWTOOTH
GF_NOISE
GF_NONE
GF_SIN
GF_SQUARE
GF_TRIANGLE
GF_SAWTOOTH
GF_INVERSE_SAWTOOTH
GF_NOISE
GF_NONE
GF_SIN
GF_SQUARE
GF_TRIANGLE
GF_SAWTOOTH
GF_INVERSE_SAWTOOTH
GF_NOISE
Definition at line 781 of file tr_local.h.
enum GLAttrDef
Enumerator
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Definition at line 1603 of file tr_local.h.
enum interactionType_t
Enumerator
IA_DEFAULT
lighting and shadowing
IA_SHADOWONLY
IA_LIGHTONLY
Definition at line 2070 of file tr_local.h.
enum modtype_t
Enumerator
MOD_BAD
MOD_BRUSH
MOD_MESH
MOD_MDS
MOD_MDC
MOD_MDM
MOD_MDX
MOD_BAD
MOD_BSP
MOD_MESH
MOD_MDM
MOD_MDX
MOD_MD5
MOD_BAD
MOD_BRUSH
MOD_MESH
MOD_MDS
MOD_MDC
MOD_MDM
MOD_MDX
Definition at line 3215 of file tr_local.h.
enum opcode_t
Enumerator
OP_UNDEF
OP_IGNORE
OP_BREAK
OP_ENTER
OP_LEAVE
OP_CALL
OP_PUSH
OP_POP
OP_CONST
OP_LOCAL
OP_JUMP
OP_EQ
OP_NE
OP_LTI
OP_LEI
OP_GTI
OP_GEI
OP_LTU
OP_LEU
OP_GTU
OP_GEU
OP_EQF
OP_NEF
OP_LTF
OP_LEF
OP_GTF
OP_GEF
OP_LOAD1
OP_LOAD2
OP_LOAD4
OP_STORE1
OP_STORE2
OP_STORE4
*(stack[top-1]) = stack[top]
OP_ARG
OP_BLOCK_COPY
OP_SEX8
OP_SEX16
OP_NEGI
OP_ADD
OP_SUB
OP_DIVI
OP_DIVU
OP_MODI
OP_MODU
OP_MULI
OP_MULU
OP_BAND
OP_BOR
OP_BXOR
OP_BCOM
OP_LSH
OP_RSHI
OP_RSHU
OP_NEGF
OP_ADDF
OP_SUBF
OP_DIVF
OP_MULF
OP_CVIF
OP_CVFI
OP_BAD
OP_LAND
OP_LOR
OP_GE
OP_LE
OP_LEQ
OP_LNE
OP_ADD
OP_SUB
OP_DIV
OP_MOD
OP_MUL
OP_NEG
OP_LT
OP_GT
OP_LPAREN
OP_RPAREN
OP_LBRACKET
OP_RBRACKET
OP_NUM
OP_TIME
OP_PARM0
OP_PARM1
OP_PARM2
OP_PARM3
OP_PARM4
OP_PARM5
OP_PARM6
OP_PARM7
OP_PARM8
OP_PARM9
OP_PARM10
OP_PARM11
OP_GLOBAL0
OP_GLOBAL1
OP_GLOBAL2
OP_GLOBAL3
OP_GLOBAL4
OP_GLOBAL5
OP_GLOBAL6
OP_GLOBAL7
OP_FRAGMENTSHADERS
OP_FRAMEBUFFEROBJECTS
OP_SOUND
OP_DISTANCE
OP_TABLE
Definition at line 939 of file tr_local.h.
enum renderCommand_t
Enumerator
RC_END_OF_LIST
RC_SET_COLOR
RC_STRETCH_PIC
RC_2DPOLYS
RC_ROTATED_PIC
RC_STRETCH_PIC_GRADIENT
RC_DRAW_SURFS
RC_DRAW_BUFFER
RC_SWAP_BUFFERS
RC_SCREENSHOT
RC_VIDEOFRAME
RC_RENDERTOTEXTURE
RC_FINISH
RC_END_OF_LIST
RC_SET_COLOR
RC_STRETCH_PIC
RC_2DPOLYS
RC_ROTATED_PIC
RC_STRETCH_PIC_GRADIENT
RC_DRAW_VIEW
RC_DRAW_BUFFER
RC_SWAP_BUFFERS
RC_SCREENSHOT
RC_VIDEOFRAME
RC_RENDERTOTEXTURE
RC_FINISH
RC_END_OF_LIST
RC_SET_COLOR
RC_STRETCH_PIC
RC_2DPOLYS
RC_ROTATED_PIC
RC_STRETCH_PIC_GRADIENT
RC_DRAW_SURFS
RC_DRAW_BUFFER
RC_SWAP_BUFFERS
RC_SCREENSHOT
RC_VIDEOFRAME
RC_RENDERTOTEXTURE
RC_FINISH
Definition at line 4765 of file tr_local.h.
enum shaderSort_t
Enumerator
SS_BAD
SS_PORTAL
mirrors, portals, viewscreens
SS_ENVIRONMENT
sky box
SS_OPAQUE
opaque
SS_DECAL
scorch marks, etc.
SS_SEE_THROUGH
ladders, grates, grills that may have small blended edges
SS_BANNER
in addition to alpha test
SS_FOG
SS_UNDERWATER
for items that should be drawn in front of the water plane
SS_BLEND0
regular transparency and filters
SS_BLEND1
generally only used for additive type effects
SS_BLEND2
SS_BLEND3
SS_BLEND6
SS_STENCIL_SHADOW
SS_ALMOST_NEAREST
gun smoke puffs
SS_NEAREST
blood blobs
SS_BAD
SS_PORTAL
mirrors, portals, viewscreens
SS_ENVIRONMENT_FOG
sky
SS_OPAQUE
opaque
SS_ENVIRONMENT_NOFOG
moved skybox here so we can fog post process all SS_OPAQUE materials
SS_DECAL
scorch marks, etc.
SS_SEE_THROUGH
ladders, grates, grills that may have small blended edges in addition to alpha test
SS_BANNER
SS_FOG
SS_UNDERWATER
for items that should be drawn in front of the water plane
SS_WATER
SS_FAR
SS_MEDIUM
SS_CLOSE
SS_BLEND0
regular transparency and filters
SS_BLEND1
generally only used for additive type effects
SS_BLEND2
SS_BLEND3
SS_BLEND6
SS_ALMOST_NEAREST
gun smoke puffs
SS_NEAREST
blood blobs
SS_POST_PROCESS
SS_BAD
SS_PORTAL
mirrors, portals, viewscreens
SS_ENVIRONMENT
sky box
SS_OPAQUE
opaque
SS_DECAL
scorch marks, etc.
SS_SEE_THROUGH
ladders, grates, grills that may have small blended edges
SS_BANNER
in addition to alpha test
SS_FOG
SS_UNDERWATER
for items that should be drawn in front of the water plane
SS_BLEND0
regular transparency and filters
SS_BLEND1
generally only used for additive type effects
SS_BLEND2
SS_BLEND3
SS_BLEND6
SS_STENCIL_SHADOW
SS_ALMOST_NEAREST
gun smoke puffs
SS_NEAREST
blood blobs
Definition at line 719 of file tr_local.h.
enum shaderType_t
Enumerator
SHADER_2D
surface material: shader is for 2D rendering
SHADER_3D_DYNAMIC
surface material: shader is for cGen diffuseLighting lighting
SHADER_3D_STATIC
surface material: pre-lit triangle models
SHADER_LIGHT
light material: attenuation
Definition at line 1390 of file tr_local.h.
enum smooth_flags
Enumerator
FLAGS_SMOOTH_TRISURF
FLAGS_SMOOTH_MESH
FLAGS_SMOOTH_MD3
FLAGS_SMOOTH_MD5
FLAGS_SMOOTH_MDC
FLAGS_SMOOTH_MDM
FLAGS_SMOOTH_PSK
Definition at line 2799 of file tr_local.h.
enum ssFormat_t
Enumerator
SSF_TGA
SSF_JPEG
SSF_PNG
SSF_TGA
SSF_JPEG
SSF_PNG
SSF_TGA
SSF_JPEG
SSF_PNG
Definition at line 4716 of file tr_local.h.
enum stageType_t
Enumerator
ST_COLORMAP
vanilla Q3A style shader treatening
ST_DIFFUSEMAP
ST_NORMALMAP
ST_SPECULARMAP
ST_REFLECTIONMAP
cubeMap based reflection
ST_REFRACTIONMAP
ST_DISPERSIONMAP
ST_SKYBOXMAP
ST_SCREENMAP
2d offscreen or portal rendering
ST_PORTALMAP
ST_HEATHAZEMAP
heatHaze post process effect
ST_LIQUIDMAP
ST_LIGHTMAP
ST_COLLAPSE_lighting_DB
diffusemap + bumpmap
ST_COLLAPSE_lighting_DBS
diffusemap + bumpmap + specularmap
ST_COLLAPSE_reflection_CB
color cubemap + bumpmap
ST_ATTENUATIONMAP_XY
ST_ATTENUATIONMAP_Z
Definition at line 1158 of file tr_local.h.
enum stencilFunc_t
StencilFuncs.
Enumerator
STF_ALWAYS
STF_NEVER
STF_LESS
STF_LEQUAL
STF_GREATER
STF_GEQUAL
STF_EQUAL
STF_NEQUAL
STF_MASK
Definition at line 1203 of file tr_local.h.
enum stencilOp_t
StencilOps.
Enumerator
STO_KEEP
STO_ZERO
STO_REPLACE
STO_INVERT
STO_INCR
STO_DECR
STO_MASK
Definition at line 1220 of file tr_local.h.
enum stencilShift_t
Shifts.
Enumerator
STS_SFAIL
STS_ZFAIL
STS_ZPASS
Definition at line 1235 of file tr_local.h.
enum surfaceType_t
Enumerator
SF_BAD
SF_SKIP
ignore
SF_FACE
SF_GRID
SF_TRIANGLES
SF_FOLIAGE
SF_POLY
SF_MD3
SF_MDC
SF_MDS
SF_MDM
SF_FLARE
SF_ENTITY
beams, rails, lightning, etc that can be determined by entity
SF_DISPLAY_LIST
SF_POLYBUFFER
SF_DECAL
decal surfaces
SF_NUM_SURFACE_TYPES
SF_MAX
ensures that sizeof(surfaceType_t) == sizeof(int)
SF_BAD
SF_SKIP
ignore
SF_FACE
SF_GRID
SF_TRIANGLES
SF_FOLIAGE
SF_POLY
SF_POLYBUFFER
SF_DECAL
decal surfaces
SF_MDV
SF_MDM
SF_MD5
SF_FLARE
SF_ENTITY
beams, rails, lightning, etc that can be determined by entity
SF_VBO_MESH
SF_VBO_MD5MESH
SF_VBO_MDMMESH
SF_VBO_MDVMESH
SF_NUM_SURFACE_TYPES
SF_MAX
ensures that sizeof(surfaceType_t) == sizeof(int)
SF_BAD
SF_SKIP
ignore
SF_FACE
SF_GRID
SF_TRIANGLES
SF_FOLIAGE
SF_POLY
SF_MD3
SF_MDC
SF_MDS
SF_MDM
SF_FLARE
SF_ENTITY
beams, rails, lightning, etc that can be determined by entity
SF_DISPLAY_LIST
SF_POLYBUFFER
SF_DECAL
decal surfaces
SF_NUM_SURFACE_TYPES
SF_MAX
ensures that sizeof(surfaceType_t) == sizeof(int)
Definition at line 2021 of file tr_local.h.
enum texCoordGen_t
Enumerator
TCGEN_BAD
TCGEN_IDENTITY
clear to 0,0
TCGEN_LIGHTMAP
TCGEN_TEXTURE
TCGEN_ENVIRONMENT_MAPPED
TCGEN_FIRERISEENV_MAPPED
TCGEN_FOG
TCGEN_VECTOR
S and T from world coordinates.
TCGEN_BAD
TCGEN_IDENTITY
clear to 0,0
TCGEN_LIGHTMAP
TCGEN_TEXTURE
TCGEN_ENVIRONMENT_MAPPED
TCGEN_FOG
TCGEN_VECTOR
S and T from world coordinates.
TCGEN_BAD
TCGEN_IDENTITY
clear to 0,0
TCGEN_LIGHTMAP
TCGEN_TEXTURE
TCGEN_ENVIRONMENT_MAPPED
TCGEN_FIRERISEENV_MAPPED
TCGEN_FOG
TCGEN_VECTOR
S and T from world coordinates.
Definition at line 900 of file tr_local.h.
enum texMod_t
Enumerator
TMOD_NONE
TMOD_TRANSFORM
TMOD_TURBULENT
TMOD_SCROLL
TMOD_SCALE
TMOD_STRETCH
TMOD_ROTATE
TMOD_ENTITY_TRANSLATE
TMOD_SWAP
TMOD_NONE
TMOD_TRANSFORM
TMOD_TURBULENT
TMOD_SCROLL
TMOD_SCALE
TMOD_STRETCH
TMOD_ROTATE
TMOD_ENTITY_TRANSLATE
TMOD_SCROLL2
TMOD_SCALE2
TMOD_CENTERSCALE
TMOD_SHEAR
TMOD_ROTATE2
TMOD_NONE
TMOD_TRANSFORM
TMOD_TURBULENT
TMOD_SCROLL
TMOD_SCALE
TMOD_STRETCH
TMOD_ROTATE
TMOD_ENTITY_TRANSLATE
TMOD_SWAP
Definition at line 1049 of file tr_local.h.
enum texture_def_t
Enumerator
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Definition at line 1702 of file tr_local.h.
enum uniform_t
Enumerator
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
UNIFORM_DEF
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Todo:
: these uniforms do not actually exist in the GLSL code!
Definition at line 1688 of file tr_local.h.
enum vboUsage_t
Enumerator
VBO_USAGE_STATIC
VBO_USAGE_DYNAMIC
Definition at line 659 of file tr_local.h.
enum wrapType_t
Enumerator
WT_REPEAT
WT_CLAMP
don't repeat the texture for texture coords outside [0, 1]
WT_EDGE_CLAMP
WT_ZERO_CLAMP
guarantee 0,0,0,255 edge for projected textures
WT_ALPHA_ZERO_CLAMP
guarante 0 alpha edge for projected textures
Definition at line 570 of file tr_local.h.
Function Documentation
void BindAnimatedImage (textureBundle_t * bundle)
BindAnimatedImage.
Parameters
[in] bundle
Definition at line 87 of file tr_gl.c.
Referenced by Render_lightVolume().
int BSPSurfaceCompare (const void * a, const void * b)
Compare function for qsort()
Parameters
[in] a
[in] b
Returns
Definition at line 2900 of file tr_bsp.c.
Referenced by R_CreateSubModelVBOs(), and R_inPVS().
static ID_INLINE void ClearLink (link_t * l) static
ClearLink.
Parameters
[in,out] l
Definition at line 172 of file tr_local.h.
Referenced by R_AddWorldSurfaces(), R_CoherentHierachicalCulling(), and RE_LoadWorldMap().
void clipPortalPlane ()
clipping portal plane in world space
Definition at line 453 of file tr_shade.c.
Referenced by Tess_StageIteratorSky().
int Com_AddToGrowList (growList_t * list, void * data)
Com_AddToGrowList.
Parameters
[in,out] list
[in] data
Returns
Definition at line 75 of file tr_growlist.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), AddTriangleToVBOTriangleList(), Com_AddToGrowList(), R_AllocImage(), R_BuildCubeMaps(), R_CreateClusters(), R_CreateIBO(), R_CreateIBO2(), R_CreateSubModelVBOs(), R_CreateVBO(), R_CreateVBO2(), R_inPVS(), R_LoadLightmapsExternal(), R_LoadLightmapsInternal(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteraction(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
void Com_DestroyGrowList (growList_t * list)
Com_DestroyGrowList.
Parameters
[in,out] list
Definition at line 62 of file tr_growlist.c.
Referenced by R_CreateClusters(), R_CreateSubModelVBOs(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteractions(), R_ShutdownImages(), R_ShutdownVBOs(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
void* Com_GrowListElement (const growList_t * list, int index)
Com_GrowListElement.
Parameters
[in] list
[in] index
Returns
Definition at line 125 of file tr_growlist.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), BindLightMap(), GL_BindNearestCubeMap(), GL_TextureMode(), R_AddWorldSurfaces(), R_BuildCubeMaps(), R_CreateClusters(), R_CreateSubModelVBOs(), R_FindTwoNearestCubeMaps(), R_ImageList_f(), R_inPVS(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteractions(), R_ShutdownImages(), R_ShutdownVBOs(), R_SumOfUsedImages(), R_VBOList_f(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderLightOcclusionQueries(), RB_ShowImages(), RE_GetTextureId(), and RE_RenderToTexture().
int Com_IndexForGrowListElement (const growList_t * list, const void * element)
Com_IndexForGrowListElement.
Parameters
[in] list
[in] element
Returns
Note
Unused
Definition at line 143 of file tr_growlist.c.
void Com_InitGrowList (growList_t * list, int maxElements)
Com_InitGrowList.
Parameters
[out] list
[in] maxElements
Definition at line 51 of file tr_growlist.c.
Referenced by Com_AddToGrowList(), R_BuildCubeMaps(), R_CreateClusters(), R_CreateSubModelVBOs(), R_InitImages(), R_InitVBOs(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteractions(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
static ID_INLINE void* DeQueue (link_t * l) static
DeQueue.
Parameters
[in,out] l
Returns
Definition at line 360 of file tr_local.h.
Referenced by IssueEntityMultiOcclusionQueries(), IssueLightMultiOcclusionQueries(), IssueMultiOcclusionQueries(), R_CoherentHierachicalCulling(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
static ID_INLINE void EnQueue (link_t * sentinel, void * data) static
EnQueue.
Parameters
[in,out] sentinel
[in] data
Definition at line 324 of file tr_local.h.
Referenced by IssueEntityMultiOcclusionQueries(), IssueEntityOcclusionQuery(), IssueLightMultiOcclusionQueries(), IssueLightOcclusionQuery(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), R_CoherentHierachicalCulling(), RB_RenderEntityOcclusionQueries(), RB_RenderLightOcclusionQueries(), and TraverseNode().
void FreeVertexHashTable (vertexHash_t ** hashTable)
FreeVertexHashTable.
Parameters
[in] hashTable
Todo:
: check this..
Definition at line 7678 of file tr_bsp.c.
Referenced by R_ShutdownImages().
void GL_Bind (image_t * image)
GL_Bind.
Parameters
[in,out] image
Definition at line 57 of file tr_backend.c.
void GL_BindNearestCubeMap (const vec3_t xyz)
GL_BindNearestCubeMap.
Parameters
[in] xyz
Definition at line 7783 of file tr_bsp.c.
void GL_BlendFunc (GLenum sfactor, GLenum dfactor)
GL_BlendFunc.
Parameters
[in] sfactor
[in] dfactor
Definition at line 210 of file tr_gl.c.
Referenced by GL_State().
void GL_CheckErrors_ (const char * fileName, int line)
GL_CheckErrors_.
Parameters
[in] fileName
[in] line
Definition at line 365 of file tr_init.c.
void GL_Clear (unsigned int bits)
GL_Clear.
Parameters
[in] bits
Definition at line 493 of file tr_gl.c.
Referenced by GL_SetDefaultState(), R_CoherentHierachicalCulling(), RB_DrawBuffer(), RB_Hyperspace(), RB_RenderBloom(), RB_RenderInteractionsShadowMapped(), RB_RenderViewFront(), and RB_ShowImages().
void GL_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_ClearColor.
Parameters
[in] red
[in] green
[in] blue
[in] alpha
Definition at line 228 of file tr_gl.c.
Referenced by GL_SetDefaultState(), R_CoherentHierachicalCulling(), RB_DrawBuffer(), RB_Fog(), RB_Hyperspace(), RB_RenderBloom(), RB_RenderInteractionsShadowMapped(), and RB_RenderViewFront().
void GL_ClearDepth (GLclampd depth)
GL_ClearDepth.
Parameters
[in] depth
Definition at line 245 of file tr_gl.c.
Referenced by GL_SetDefaultState().
void GL_ClearStencil (GLint s)
GL_ClearStencil.
Parameters
[in] s
Definition at line 259 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and RE_BeginFrame().
void GL_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_ColorMask.
Parameters
[in] red
[in] green
[in] blue
[in] alpha
Definition at line 276 of file tr_gl.c.
Referenced by GL_State().
void GL_Cull (int cullType)
GL_Cull.
Parameters
[in] cullType
Definition at line 160 of file tr_backend.c.
void GL_CullFace (GLenum mode)
GL_CullFace.
Parameters
[in] mode
Definition at line 293 of file tr_gl.c.
Referenced by GL_Cull(), and GL_SetDefaultState().
void GL_DepthFunc (GLenum func)
GL_DepthFunc.
Parameters
[in] func
Definition at line 307 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and GL_State().
void GL_DepthMask (GLboolean flag)
GL_DepthMask.
Parameters
[in] flag
Definition at line 321 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and GL_State().
void GL_DrawBuffer (GLenum mode)
GL_DrawBuffer.
Parameters
[in] mode
Definition at line 335 of file tr_gl.c.
Referenced by RB_DrawBuffer().
void GL_FrontFace (GLenum mode)
GL_FrontFace.
Parameters
[in] mode
Definition at line 349 of file tr_gl.c.
Referenced by GL_Cull(), and GL_SetDefaultState().
void GL_LoadModelViewMatrix (const mat4_t m)
GL_LoadModelViewMatrix.
Parameters
[in] m
Definition at line 363 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_DrawSun(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderEntityOcclusionQueries(), RB_RenderFlares(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_SetGL2D(), RB_SetViewMVPM(), RenderEntityOcclusionVolume(), and RenderLightOcclusionVolume().
void GL_LoadProjectionMatrix (const mat4_t m)
GL_LoadProjectionMatrix.
Parameters
[in] m
Definition at line 378 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_DrawSun(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_SetGL2D(), RB_SetViewMVPM(), and SetViewportAndScissor().
void GL_PolygonMode (GLenum face, GLenum mode)
GL_PolygonMode.
Parameters
[in] face
[in] mode
Definition at line 422 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and GL_State().
void GL_PolygonOffset (float factor, float units)
GL_PolygonOffset.
Parameters
[in] factor
[in] units
Definition at line 478 of file tr_gl.c.
Referenced by RB_RenderDebugUtils().
void GL_PopMatrix ()
GL_PopMatrix.
Definition at line 406 of file tr_gl.c.
Referenced by RB_CameraPostFX(), RB_DrawSun(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), and Render_lightVolume().
void GL_PushMatrix ()
GL_PushMatrix.
Definition at line 392 of file tr_gl.c.
Referenced by RB_CameraPostFX(), RB_DrawSun(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), and Render_lightVolume().
void GL_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Scissor.
Parameters
[in] x
[in] y
[in] width
[in] height
Definition at line 440 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_RenderDebugUtils(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_SetGL2D(), Render_lightVolume(), and SetViewportAndScissor().
void GL_SelectTexture (int unit)
GL_SelectTexture.
Parameters
[in] unit
Definition at line 92 of file tr_backend.c.
void GL_SetDefaultState (void)
GL_SetDefaultState.
Definition at line 843 of file tr_init.c.
void GL_State (uint32_t stateBits)
This routine is responsible for setting the most commonly changed state in Q3.
Parameters
[in] stateBits
Todo:
Definition at line 549 of file tr_gl.c.
void GL_TextureMode (const char * string)
GL_TextureMode.
Parameters
[in] string
Definition at line 145 of file tr_image.c.
void GL_Unbind ()
GL_Unbind.
Definition at line 76 of file tr_gl.c.
void GL_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Viewport.
Parameters
[in] x
[in] y
[in] width
[in] height
Definition at line 460 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RB_SetGL2D(), Render_lightVolume(), and SetViewportAndScissor().
void GLSL_BindNullProgram (void)
GLSL_BindNullProgram.
Definition at line 2905 of file tr_glsl.c.
Referenced by GLSL_BindProgram(), GLSL_CompilePermutation(), and GLSL_ShutdownGPUShaders().
void GLSL_BindProgram (shaderProgram_t * program)
GLSL_BindProgram.
Parameters
[in] program
Definition at line 2884 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation(), GLSL_SelectPermutation(), R_DebugGraphics(), and RB_SafeState().
void GLSL_CompileGPUShaders (void)
GLSL_CompileGPUShaders.
Definition at line 2776 of file tr_glsl.c.
Referenced by GLSL_restart_f(), and R_Init().
void GLSL_InitGPUShaders (void)
GLSL_InitGPUShaders.
Definition at line 2748 of file tr_glsl.c.
Referenced by GLSL_restart_f(), and InitOpenGL().
void GLSL_SelectPermutation (programInfo_t * programlist)
GLSL_SelectPermutation.
Parameters
[in] programlist
Definition at line 2546 of file tr_glsl.c.
void GLSL_SelectTexture (shaderProgram_t * program, texture_def_t tex)
GLSL_SelectTexture.
Parameters
[in] program
[in] tex
Definition at line 1621 of file tr_glsl.c.
void GLSL_SetMacroState (programInfo_t * programlist, int macro, int enabled)
GLSL_SetMacroState.
Parameters
[in,out] programlist
[in] macro
[in] enabled
Definition at line 2453 of file tr_glsl.c.
Referenced by GLSL_SetMacroStates().
void GLSL_SetMacroStates (programInfo_t * programlist, int numMacros, ...)
GLSL_SetMacroStates.
Parameters
[in] programlist
[in] numMacros
Definition at line 2501 of file tr_glsl.c.
void GLSL_SetRequiredVertexPointers (programInfo_t * programlist)
GLSL_SetRequiredVertexPointers.
Parameters
[in] programlist
Todo:
: implement this
Definition at line 2590 of file tr_glsl.c.
Referenced by DrawTris(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderLightOcclusionQueries(), and Tess_StageIteratorSky().
void GLSL_SetUniform_AlphaTest (uint32_t stateBits)
GLSL_SetUniform_AlphaTest.
Parameters
[in] stateBits
Definition at line 3039 of file tr_glsl.c.
void GLSL_SetUniform_ColorModulate (programInfo_t * prog, int colorGen, int alphaGen)
GLSL_SetUniform_ColorModulate.
Parameters
[in,out] prog
[in] colorGen
[in] alphaGen
Definition at line 2984 of file tr_glsl.c.
Referenced by DrawTris(), R_CoherentHierachicalCulling(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_ShowImages(), and RE_StretchRaw().
void GLSL_SetUniform_DeformParms (deformStage_t deforms[], int numDeforms)
GLSL_SetUniform_DeformParms.
Parameters
[in] deforms
[in] numDeforms
Definition at line 2921 of file tr_glsl.c.
Referenced by DrawTris(), and RB_RenderBspOcclusionQueries().
void GLSL_SetUniformBoolean (shaderProgram_t * program, int uniformNum, GLboolean value)
GLSL_SetUniformBoolean.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1641 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformDouble (shaderProgram_t * program, int uniformNum, GLdouble value)
GLSL_SetUniformDouble.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1734 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformFloat (shaderProgram_t * program, int uniformNum, GLfloat value)
GLSL_SetUniformFloat.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1703 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformFloat5 (shaderProgram_t * program, int uniformNum, const vec5_t v)
GLSL_SetUniformFloat5.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1860 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformFloatARR (shaderProgram_t * program, int uniformNum, float * floatarray, int arraysize)
GLSL_SetUniformFloatARR.
Parameters
[in] program
[in] uniformNum
[in] floatarray
[in] arraysize
Definition at line 1923 of file tr_glsl.c.
Referenced by GLSL_SetUniform_DeformParms().
void GLSL_SetUniformInt (shaderProgram_t * program, int uniformNum, GLint value)
GLSL_SetUniformInt.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1672 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformMatrix16 (shaderProgram_t * program, int uniformNum, const mat4_t matrix)
GLSL_SetUniformMatrix16.
Parameters
[in] program
[in] uniformNum
[in] matrix
Definition at line 1891 of file tr_glsl.c.
void GLSL_SetUniformMatrix16ARR (shaderProgram_t * program, int uniformNum, mat4_t * matrixarray, int arraysize)
GLSL_SetUniformMatrix16ARR.
Parameters
[in] program
[in] uniformNum
[in] matrixarray
[in] arraysize
Definition at line 1971 of file tr_glsl.c.
void GLSL_SetUniformVec2 (shaderProgram_t * program, int uniformNum, const vec2_t v)
GLSL_SetUniformVec2.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1766 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformVec3 (shaderProgram_t * program, int uniformNum, const vec3_t v)
GLSL_SetUniformVec3.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1798 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformVec4 (shaderProgram_t * program, int uniformNum, const vec4_t v)
GLSL_SetUniformVec4.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1829 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformVec4ARR (shaderProgram_t * program, int uniformNum, vec4_t * vectorarray, int arraysize)
GLSL_SetUniformVec4ARR.
Parameters
[in] program
[in] uniformNum
[in] vectorarray
[in] arraysize
Definition at line 1947 of file tr_glsl.c.
void GLSL_ShutdownGPUShaders ()
GLSL_ShutdownGPUShaders.
Definition at line 2849 of file tr_glsl.c.
Referenced by GLSL_restart_f(), and RE_Shutdown().
void GLSL_VertexAttribPointers (uint32_t attribBits)
GLSL_VertexAttribPointers.
Parameters
[in] attribBits
Todo:
: this occures on maps for unknown reasons (uje_marketgarden + r_wolffog and
Definition at line 3260 of file tr_glsl.c.
Referenced by GLSL_VertexAttribsState().
void GLSL_VertexAttribsState (uint32_t stateBits)
GLSL_VertexAttribsState.
Parameters
[in] stateBits
Definition at line 3066 of file tr_glsl.c.
Referenced by GLSL_SetRequiredVertexPointers(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_UpdateVBOs(), and TraverseNode().
static ID_INLINE void InitLink (link_t * l, void * data) static
InitLink.
Parameters
[in,out] l
[in] data
Definition at line 162 of file tr_local.h.
Referenced by EnQueue(), R_LoadNodesAndLeafs(), R_RecursiveAddInteractionNode(), and StackPush().
static ID_INLINE void InsertLink (link_t * l, link_t * sentinel) static
InsertLink.
Parameters
[in,out] l
[in] sentinel
Definition at line 211 of file tr_local.h.
Referenced by BuildNodeTraversalStackPost_r(), EnQueue(), R_RecursiveAddInteractionNode(), R_RecursiveWorldNode(), and StackPush().
void LoadRGBEToFloats (const char * name, float ** pic, int * width, int * height, qboolean doGamma, qboolean toneMap, qboolean compensate)
LoadRGBEToFloats.
Parameters
[in] name
[out] pic
[out] width
[out] height
[in] doGamma
[in] toneMap
[in] compensate
Todo:
XMap2's output is 255 times too high
Definition at line 349 of file tr_bsp.c.
Referenced by LoadRGBEToBytes().
void LoadRGBEToHalfs (const char * name, unsigned short ** halfImage, int * width, int * height)
LoadRGBEToHalfs.
Parameters
name - unused
halfImage - unused
width - unused
height - unused
Note
not implemented
Definition at line 645 of file tr_bsp.c.
Referenced by R_LoadLightmapsExternal().
static ID_INLINE qboolean QueueEmpty (link_t * l) static
QueueEmpty.
Parameters
[in] l
Returns
Definition at line 314 of file tr_local.h.
Referenced by IssueEntityMultiOcclusionQueries(), IssueLightMultiOcclusionQueries(), IssueMultiOcclusionQueries(), R_CoherentHierachicalCulling(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
static ID_INLINE link_t* QueueFront (link_t * l) static
QueueFront.
Parameters
[in] l
Returns
Definition at line 389 of file tr_local.h.
Referenced by IssueEntityMultiOcclusionQueries(), IssueLightMultiOcclusionQueries(), IssueMultiOcclusionQueries(), R_CoherentHierachicalCulling(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
static ID_INLINE void QueueInit (link_t * l) static
QueueInit.
Parameters
[in,out] l
Definition at line 292 of file tr_local.h.
Referenced by IssueEntityMultiOcclusionQueries(), IssueEntityOcclusionQuery(), IssueLightMultiOcclusionQueries(), IssueLightOcclusionQuery(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), R_CoherentHierachicalCulling(), R_PrecacheInteractions(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
static ID_INLINE int QueueSize (link_t * l) static
QueueSize.
Parameters
[in] l
Returns
Definition at line 304 of file tr_local.h.
Referenced by R_CoherentHierachicalCulling(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
void R_AddBeamSurfaces (trRefEntity_t * ent)
void R_AddBrushModelInteractions (trRefEntity_t * ent, trRefLight_t * light)
Determine which dynamic lights may effect this bmodel.
Parameters
[in] ent
[in] light
Todo:
: do more culling?
Definition at line 43 of file tr_light.c.
Referenced by R_AddEntityInteractions().
void R_AddBSPModelSurfaces (trRefEntity_t * ent)
R_AddBSPModelSurfaces.
Parameters
[in,out] ent
Definition at line 428 of file tr_world.c.
Referenced by R_AddEntitySurfaces().
void R_AddDecalSurface (decal_t * decal)
Adds a decal surface to the scene.
Parameters
[in,out] decal
Definition at line 924 of file tr_decals.c.
void R_AddDecalSurfaces (bspModel_t * bmodel)
Adds decal surfaces to the scene.
Parameters
[in] bmodel
Definition at line 974 of file tr_decals.c.
void R_AddDrawSurf (surfaceType_t * surface, shader_t * shader, int lightmapNum, int fogNum)
R_AddDrawSurf.
Parameters
[in] surface
[in] shader
[in] lightmapNum
[in] fogNum
Definition at line 2203 of file tr_main.c.
void R_AddDrawViewCmd (void)
R_AddDrawViewCmd.
Definition at line 231 of file tr_cmds.c.
Referenced by R_SortDrawSurfs().
qboolean R_AddLightInteraction (trRefLight_t * light, surfaceType_t * surface, shader_t * surfaceShader, byte cubeSideBits, interactionType_t iaType)
R_AddLightInteraction.
Parameters
[in,out] light
[in] surface
[in] surfaceShader
[in] cubeSideBits
[in] iaType
Returns
Definition at line 1001 of file tr_light.c.
Referenced by R_AddBrushModelInteractions(), R_AddInteractionSurface(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_AddPolygonInteractions(), and R_AddPrecachedWorldInteractions().
void R_AddLightningBoltSurfaces (trRefEntity_t * ent)
void R_AddMD5Interactions (trRefEntity_t * ent, trRefLight_t * light)
R_AddMD5Interactions.
Parameters
[in] ent
[in] light
Definition at line 1070 of file tr_animation.c.
Referenced by R_AddEntityInteractions().
void R_AddMD5Surfaces (trRefEntity_t * ent)
R_AddMD5Surfaces.
Parameters
[in] ent
Definition at line 940 of file tr_animation.c.
Referenced by R_AddEntitySurfaces().
void R_AddMDMInteractions (trRefEntity_t * ent, trRefLight_t * light)
R_AddMDMInteractions.
Parameters
[in] ent
[in] light
Definition at line 584 of file tr_animation_mdm.c.
Referenced by R_AddEntityInteractions().
void R_AddMDVInteractions (trRefEntity_t * ent, trRefLight_t * light)
R_AddMDVInteractions.
Parameters
[in] ent
[in] light
Definition at line 368 of file tr_mesh.c.
Referenced by R_AddEntityInteractions().
void R_AddMDVSurfaces (trRefEntity_t * ent)
R_AddMDVSurfaces.
Parameters
[in,out] ent
Definition at line 260 of file tr_mesh.c.
Referenced by R_AddEntitySurfaces().
void R_AddNullModelSurfaces (trRefEntity_t * ent)
void R_AddPolygonBufferSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
Definition at line 308 of file tr_scene.c.
void R_AddPolygonSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
Definition at line 118 of file tr_scene.c.
void R_AddPrecachedWorldInteractions (trRefLight_t * light)
R_AddPrecachedWorldInteractions.
Parameters
[in] light
Definition at line 2507 of file tr_world.c.
Referenced by R_AddLightInteractions().
void R_AddRailSurfaces (trRefEntity_t * ent, qboolean isUnderwater)
void R_AddWorldInteractions (trRefLight_t * light)
R_AddWorldInteractions.
Parameters
[in] light
Definition at line 2484 of file tr_world.c.
Referenced by R_AddLightInteractions().
void R_AddWorldSurfaces (void)
R_AddWorldSurfaces.
Definition at line 833 of file tr_world.c.
image_t* R_AllocImage (const char * name, qboolean linkIntoHashTable)
R_AllocImage.
Parameters
[in] name
[in] linkIntoHashTable
Returns
Definition at line 1451 of file tr_image.c.
Referenced by R_BuildCubeMaps(), R_CreateCubeImage(), R_CreateImage(), R_LoadDDSImageData(), and R_LoadLightmapsExternal().
model_t* R_AllocModel (void)
[in] R_AllocModel
Returns
[in] R_AllocModel
Returns
Definition at line 74 of file tr_model.c.
void R_AnimationList_f (void)
R_AnimationList_f.
Definition at line 868 of file tr_animation.c.
Referenced by R_Register().
void R_AttachFBOTexture1D (int texId, int index)
R_AttachFBOTexture1D.
Parameters
[in] texId
[in] index
Definition at line 314 of file tr_fbo.c.
void R_AttachFBOTexture2D (int target, int texId, int index)
R_AttachFBOTexture2D.
Parameters
[in] target
[in] texId
[in] index
Definition at line 331 of file tr_fbo.c.
Referenced by R_AttachColorBufferToFBO(), R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
void R_AttachFBOTexture3D (int texId, int index, int zOffset)
R_AttachFBOTexture3D.
Parameters
[in] texId
[in] index
[in] zOffset
Definition at line 354 of file tr_fbo.c.
void R_AttachFBOTextureDepth (int texId)
R_AttachFBOTextureDepth.
Parameters
[in] texId
Definition at line 369 of file tr_fbo.c.
Referenced by R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
void R_BindFBO (FBO_t * fbo)
R_BindFBO.
Parameters
[in] fbo
Definition at line 428 of file tr_fbo.c.
Referenced by R_CoherentHierachicalCulling(), R_CreateReadyFBO(), R_InitFBOs(), RB_CalculateAdaptation(), RB_RenderBloom(), RB_RenderInteractionsShadowMapped(), and RB_RenderViewFront().
void R_BindIBO (IBO_t * ibo)
R_BindIBO.
Parameters
[in] ibo
Definition at line 463 of file tr_vbo.c.
Referenced by IssueMultiOcclusionQueries(), IssueOcclusionQuery(), R_inPVS(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_CheckOverflow(), Tess_StageIteratorSky(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFace(), Tess_SurfaceFlare(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), Tess_SurfaceTriangles(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), Tess_SurfaceVBOMesh(), Tess_UpdateVBOs(), and TraverseNode().
void R_BindNullFBO (void)
R_BindNullFBO.
Definition at line 460 of file tr_fbo.c.
Referenced by R_BindFBO(), R_CoherentHierachicalCulling(), R_InitFBOs(), R_ShutdownFBOs(), RB_RenderBloom(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderViewFront(), and RB_SetGL2D().
void R_BindNullIBO (void)
R_BindNullIBO.
Definition at line 487 of file tr_vbo.c.
Referenced by R_InitVBOs(), R_inPVS(), R_ShutdownVBOs(), RB_PostProcess(), RE_EndFrame(), RE_LoadWorldMap(), and RE_RegisterModel().
void R_BindNullVBO (void)
R_BindNullVBO.
Definition at line 446 of file tr_vbo.c.
Referenced by R_InitVBOs(), R_ShutdownVBOs(), RB_PostProcess(), RE_EndFrame(), RE_LoadWorldMap(), and RE_RegisterModel().
void R_BindVBO (VBO_t * vbo)
R_BindVBO.
Parameters
[in] vbo
Definition at line 415 of file tr_vbo.c.
Referenced by IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_CheckOverflow(), Tess_StageIteratorSky(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFace(), Tess_SurfaceFlare(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), Tess_SurfaceTriangles(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), Tess_SurfaceVBOMesh(), Tess_UpdateVBOs(), and TraverseNode().
void R_BuildCubeMaps (void)
R_BuildCubeMaps.
Todo:
: this doesn't create cubes on important locations
Todo:
: don't use every grid position
Todo:
connect cubeProbe with gridPoint
Definition at line 8046 of file tr_bsp.c.
Referenced by R_BuildCubeMaps_f(), and RE_LoadWorldMap().
float R_CalcFov (float fovX, float width, float height)
byte R_CalcLightCubeSideBits (trRefLight_t * light, vec3_t worldBounds[2])
R_CalcLightCubeSideBits.
Parameters
[in] light
[in] worldBounds
Returns
Definition at line 1535 of file tr_light.c.
Referenced by R_AddBrushModelInteractions(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_CalcInteractionCubeSideBits(), and R_LightSurfaceGeneric().
void R_CalcNormalForTriangle (vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2)
R_CalcNormalForTriangle.
Parameters
[in] normal
[in] v0
[in] v1
[in] v2
Definition at line 138 of file tr_main.c.
Referenced by ParseTriSurf(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
void R_CalcSurfaceTrianglePlanes (int numTriangles, srfTriangle_t * triangles, srfVert_t * verts)
R_CalcSurfaceTrianglePlanes calculates planeNormal.
Parameters
[in] numTriangles
[in] triangles
[in] verts
Definition at line 598 of file tr_main.c.
void R_CalcTangentsForTriangle (vec3_t tangent, vec3_t binormal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentsForTriangle.
Parameters
[out] tangent
[out] binormal
[in] v0
[in] v1
[in] v2
[in] t0
[in] t1
[in] t2
Note
http://members.rogers.com/deseric/tangentspace.htm
Definition at line 163 of file tr_main.c.
Referenced by R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
void R_CalcTangentsForTriangle2 (vec3_t tangent, vec3_t binormal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
Referenced by ParseTriSurf().
void R_CalcTangentSpace (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpace.
Parameters
[out] tangent
[out] binormal
[out] normal
[in] v0
[in] v1
[in] v2
[in] t0
[in] t1
[in] t2
Definition at line 213 of file tr_main.c.
Referenced by ParseFace(), ParseTriSurf(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
void R_CalcTangentSpaceFast (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpaceFast.
Parameters
[out] tangent
[out] binormal
[out] normal
[in] v0
[in] v1
[in] v2
[in] t0
[in] t1
[in] t2
Definition at line 301 of file tr_main.c.
Referenced by Tess_SurfaceMDV(), and Tess_SurfacePolychain().
qboolean R_CalcTangentVectors (srfVert_t * dv[3])
R_CalcTangentVectors.
Parameters
[in,out] dv
Returns
Definition at line 540 of file tr_main.c.
Referenced by MakeMeshTangentVectors(), ParseFace(), and ParseTriSurf().
void R_CalcTBN (vec3_t tangent, vec3_t bitangent, vec3_t normal, const vec3_t v1, const vec3_t v2, const vec3_t v3, const vec2_t w1, const vec2_t w2, const vec2_t w3)
R_CalcTBN.
Parameters
[out] tangent
[out] bitangent
[out] normal
[in] v1
[in] v2
[in] v3
[in] w1
[in] w2
[in] w3
Note
http://www.terathon.com/code/tangent.html
Unused
Definition at line 388 of file tr_main.c.
qboolean R_CheckFBO (const FBO_t * fbo)
R_CheckFBO.
Parameters
[in] fbo
Returns
Definition at line 43 of file tr_fbo.c.
Referenced by R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
void R_ClearFlares (void)
R_ClearFlares.
Definition at line 101 of file tr_flares.c.
qboolean R_CompareVert (srfVert_t * v1, srfVert_t * v2, qboolean checkST)
R_CompareVert.
Parameters
[in] v1
[in] v2
[in] checkST
Returns
Definition at line 111 of file tr_main.c.
Referenced by MakeMeshTangentVectors(), and ParseTriSurf().
void R_ComputeFinalAttenuation (shaderStage_t * pStage, trRefLight_t * light)
R_ComputeFinalAttenuation.
Parameters
[in] pStage
[in] light
Definition at line 1821 of file tr_light.c.
Referenced by Render_lightVolume().
void R_CopyToFBO (FBO_t * from, FBO_t * to, GLuint mask, GLuint filter)
R_CopyToFBO.
Parameters
[in] from
[in] to
[in] mask
[in] filter
Todo:
add non EXT_framebuffer_blit code
Definition at line 391 of file tr_fbo.c.
Referenced by RB_RenderViewFront().
image_t* R_CreateCubeImage (const char * name, const byte * pic[6], int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateCubeImage.
Parameters
[in] name
[in] pic
[in] width
[in] height
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 1536 of file tr_image.c.
Referenced by R_CreateCubeRenderImage(), and R_FindCubeImage().
FBO_t* R_CreateFBO (const char * name, int width, int height)
R_CreateFBO.
Parameters
[in] name
[in] width
[in] height
Returns
Definition at line 102 of file tr_fbo.c.
Referenced by R_CreateReadyFBO(), and R_InitFBOs().
void R_CreateFBOColorBuffer (FBO_t * fbo, int format, int index)
Framebuffer must be bound.
Parameters
[in,out] fbo
[in] format
[in] index
Definition at line 152 of file tr_fbo.c.
Referenced by R_AttachColorBufferToFBO(), and R_InitFBOs().
void R_CreateFBODepthBuffer (FBO_t * fbo, int format)
R_CreateFBODepthBuffer.
Parameters
[in,out] fbo
[in] format
Definition at line 198 of file tr_fbo.c.
Referenced by R_InitFBOs().
void R_CreateFBOStencilBuffer (FBO_t * fbo, int format)
R_CreateFBOStencilBuffer.
Parameters
[in,out] fbo
[in] format
Definition at line 236 of file tr_fbo.c.
IBO_t* R_CreateIBO (const char * name, byte * indexes, int indexesSize, vboUsage_t usage)
R_CreateIBO.
Parameters
[in] name
[in] indexes
[in] indexesSize
[in] usage
Returns
Definition at line 281 of file tr_vbo.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), and R_InitVBOs().
IBO_t* R_CreateIBO2 (const char * name, int numTriangles, srfTriangle_t * triangles, vboUsage_t usage)
R_CreateIBO2.
Parameters
[in] name
[in] numTriangles
[in] triangles
[in] usage
Returns
Definition at line 335 of file tr_vbo.c.
Referenced by R_CreateSubModelVBOs(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_CreateWorldVBO(), R_InitUnitCubeVBO(), R_LoadNodesAndLeafs(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), and R_SetupLightFrustum().
image_t* R_CreateImage (const char * name, const byte * pic, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateImage.
Parameters
[in] name
[in] pic
[in] width
[in] height
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 1495 of file tr_image.c.
VBO_t* R_CreateVBO (const char * name, byte * vertexes, int vertexesSize, vboUsage_t usage)
R_CreateVBO.
Parameters
[in] name
[in] vertexes
[in] vertexesSize
[in] usage
Returns
Definition at line 46 of file tr_vbo.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), R_InitVBOs(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
VBO_t* R_CreateVBO2 (const char * name, int numVertexes, srfVert_t * verts, uint32_t stateBits, vboUsage_t usage)
Referenced by R_CreateSubModelVBOs(), R_CreateWorldVBO(), R_LoadNodesAndLeafs(), and R_SetupLightFrustum().
cullResult_t R_CullBox (vec3_t worldBounds[2])
R_CullBox.
Parameters
[in] worldBounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 624 of file tr_main.c.
Referenced by R_CullLocalBox(), R_CullMD5(), and R_CullMDV().
void R_CullDecalProjectors (void)
Frustum culls decal projector list.
Definition at line 1003 of file tr_decals.c.
int R_CullLightPoint (trRefLight_t * light, const vec3_t p)
R_CullLightPoint.
Parameters
[in] light
[in] p
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Note
Unused
Definition at line 1840 of file tr_light.c.
int R_CullLightTriangle (trRefLight_t * light, vec3_t verts[3])
R_CullLightTriangle.
Parameters
[in] light
[in] verts
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 1869 of file tr_light.c.
Referenced by UpdateLightTriangles().
int R_CullLightWorldBounds (trRefLight_t * light, vec3_t worldBounds[2])
R_CullLightWorldBounds.
Parameters
[in] light
[in] worldBounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 1895 of file tr_light.c.
Referenced by R_AddBrushModelInteractions(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_CullLightTriangle(), R_LightSurfaceGeneric(), and R_RecursiveAddInteractionNode().
cullResult_t R_CullLocalBox (vec3_t bounds[2])
R_CullLocalBox.
Parameters
[in] bounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 258 of file tr_main.c.
int R_CullLocalPointAndRadius (vec3_t origin, float radius)
R_CullLocalPointAndRadius.
Parameters
[in] origin
[in] radius
Returns
Definition at line 331 of file tr_main.c.
int R_CullPointAndRadius (vec3_t origin, float radius)
R_CullPointAndRadius.
Parameters
[in] origin
[in] radius
Returns
Definition at line 346 of file tr_main.c.
void R_DebugAxis (const vec3_t origin, const mat4_t transformMatrix)
R_DebugAxis.
Parameters
[in] origin
[in] transformMatrix
Definition at line 3016 of file tr_main.c.
void R_DebugBoundingBox (const vec3_t origin, const vec3_t mins, const vec3_t maxs, vec4_t color)
R_DebugBoundingBox.
Parameters
[in] origin
[in] mins
[in] maxs
[in] color
Note
from botlib
Definition at line 3056 of file tr_main.c.
void R_DebugPolygon (int color, int numPoints, float * points)
R_DebugPolygon.
Parameters
[in] color
[in] numPoints
[in] points
Definition at line 1776 of file tr_main.c.
void R_DebugText (const vec3_t org, float r, float g, float b, const char * text, qboolean neverOcclude)
R_DebugText.
Parameters
org - unused
r - unused
g - unused
b - unused
text - unused
neverOcclude - unused
Todo:
TODO: R_DebugText Unimplemented!
Parameters
[in] org
[in] r
[in] g
[in] b
[in] text
[in] neverOcclude
org - unused
r - unused
g - unused
b - unused
text - unused
neverOcclude - unused
Todo:
TODO: R_DebugText Unimplemented!
Definition at line 1815 of file tr_main.c.
void R_DeleteSurfaceVBOs ()
void R_FBOList_f (void)
R_FBOList_f.
Definition at line 948 of file tr_fbo.c.
Referenced by R_Register().
image_t* R_FindCubeImage (const char * imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char * materialName)
Finds or loads the given image.
Parameters
[in] imageName
[in] bits
[in] filterType
[in] wrapType
[in] materialName
Returns
NULL if it fails, not a default image.
Note
Fear the use of goto
Todo:
Todo:
: better fix - scale the image to proper dimension
Definition at line 2583 of file tr_image.c.
Referenced by ParseSkyParms(), and ParseStage().
image_t* R_FindImageFile (const char * imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char * materialName)
Finds or loads the given image.
Parameters
[in] imageName
[in] bits
[in] filterType
[in] wrapType
[in] materialName
Returns
NULL if it fails, not a default image.
Todo:
!!!
Todo:
: there are more cases for some models on vanilla maps!
Definition at line 2244 of file tr_image.c.
shader_t* R_FindShader (const char * name, shaderType_t type, qboolean mipRawImage)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
In the interest of not requiring an explicit shader text entry to be defined for every single image used in the game, three default shader behaviors can be auto-created for any image:
If type == SHADER_2D, then the image will be used for 2D rendering unless an explicit shader is found
If type == SHADER_3D_DYNAMIC, then the image will have dynamic diffuse lighting applied to it, as apropriate for most entity skin surfaces.
If type == SHADER_3D_STATIC, then the image will use the vertex rgba modulate values, as apropriate for misc_model pre-lit surfaces.
Parameters
[in] name
[in] type
[in] mipRawImage
Returns
Todo:
should be attenuationZImage
Todo:
: remove and add/merge r_genNormalMaps
Todo:
: image file name has to be including extension, we use tga - make this more generic one day
Todo:
: image file name has to be including extension, we use tga - make this more generic one day
Definition at line 5638 of file tr_shader.c.
shader_t* R_FindShaderByName (const char * name)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
Parameters
[in] name
Returns
Definition at line 3229 of file tr_shader.c.
void R_FindTwoNearestCubeMaps (const vec3_t position, cubemapProbe_t ** cubeProbe1, cubemapProbe_t ** cubeProbe2, float * distance1, float * distance2)
R_FindTwoNearestCubeMaps.
Parameters
[in] position
[out] cubeProbe1 // nearest
[out] cubeProbe2 // 2nd nearest
Definition at line 7848 of file tr_bsp.c.
Referenced by BindCubeMaps(), R_CreateWorldVBO(), and RB_RenderDebugUtils().
float R_FogFactor (float s, float t)
This is called for each texel of the fog texture on startup and for each vertex of transparent shaders in fog dynamically.
Parameters
[in] s
[in] t
Returns
A 0.0 to 1.0 fog density value.
Definition at line 2815 of file tr_image.c.
Referenced by R_CreateFogImage().
int R_FogLocalPointAndRadius (const vec3_t pt, float radius)
R_FogLocalPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
Note
Unused
Definition at line 767 of file tr_main.c.
int R_FogPointAndRadius (const vec3_t pt, float radius)
R_FogPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
Todo:
: non-normalized axis issues
Definition at line 782 of file tr_main.c.
Referenced by R_FogLocalPointAndRadius().
int R_FogWorldBox (vec3_t bounds[2])
R_FogWorldBox.
Parameters
[out] bounds
Returns
Definition at line 822 of file tr_main.c.
Referenced by R_AddBSPModelSurfaces(), R_AddMD5Surfaces(), R_AddMDVSurfaces(), and R_MDM_AddAnimSurfaces().
void R_FreeSurfaceGridMesh (srfGridMesh_t * grid)
R_FreeSurfaceGridMesh.
Parameters
[in] grid
Definition at line 400 of file tr_curve.c.
void R_GammaCorrect (byte * buffer, int bufSize)
R_GammaCorrect.
Parameters
[in,out] buffer
[in] bufSize
Definition at line 115 of file tr_image.c.
skelAnimation_t* R_GetAnimationByHandle (qhandle_t hAnim)
R_GetAnimationByHandle.
Parameters
[in] hAnim
Returns
Definition at line 850 of file tr_animation.c.
Referenced by RE_AnimFrameRate(), RE_AnimNumFrames(), RE_BuildSkeleton(), and RE_CheckSkeleton().
void* R_GetCommandBuffer (unsigned int bytes)
Make sure there is enough command space, waiting on the render thread if needed.
Parameters
[in] bytes
Returns
Definition at line 146 of file tr_cmds.c.
qboolean R_GetEntityToken (char * buffer, size_t size)
R_GetEntityToken.
Parameters
[out] buffer
[in] size
Returns
Definition at line 2543 of file tr_bsp.c.
model_t* R_GetModelByHandle (qhandle_t hModel)
R_GetModelByHandle.
Parameters
[in] hModel
Returns
Definition at line 53 of file tr_model.c.
shader_t* R_GetShaderByHandle (qhandle_t hShader)
When a handle is passed in by another module, this range checks it and returns a valid (possibly default) shader_t to be used internally.
Parameters
[in] hShader
Returns
Todo:
name
Todo:
name
Todo:
name
Definition at line 3649 of file tr_shader.c.
shader_t* R_GetShaderByState (int index, long * cycleTime)
skin_t* R_GetSkinByHandle (qhandle_t hSkin)
R_GetSkinByHandle.
Parameters
[in] hSkin
Returns
Definition at line 1914 of file tr_image.c.
srfGridMesh_t* R_GridInsertColumn (srfGridMesh_t * grid, int column, int row, vec3_t point, float loderror)
R_GridInsertColumn.
Parameters
[in,out] grid
[in] column
[in] row
[in] point
[in] loderror
Returns
Definition at line 601 of file tr_curve.c.
srfGridMesh_t* R_GridInsertRow (srfGridMesh_t * grid, int row, int column, vec3_t point, float loderror)
R_GridInsertRow.
Parameters
[in,out] grid
[in] row
[in] column
[in] point
[in] loderror
Returns
Definition at line 667 of file tr_curve.c.
void R_ImageCopyBack (image_t * image, int x, int y, int width, int height)
R_ImageCopyBack.
Parameters
[in] image
[in] x
[in] y
[in] width
[in] height
Definition at line 2211 of file tr_image.c.
void R_ImageList_f (void)
R_ImageList_f.
Todo:
Todo:
Definition at line 205 of file tr_image.c.
void R_Init (void)
R_Init.
Definition at line 1145 of file tr_init.c.
void R_InitAnimations (void)
R_InitAnimations.
Definition at line 71 of file tr_animation.c.
Referenced by R_Init().
void R_InitFBOs (void)
R_InitFBOs.
Definition at line 558 of file tr_fbo.c.
Referenced by R_Init().
void R_InitFogTable (void)
R_InitFogTable.
Definition at line 2798 of file tr_image.c.
Referenced by R_Init().
void R_InitImages (void)
R_InitImages.
Definition at line 1453 of file tr_image.c.
void R_InitNextFrame (void)
R_InitNextFrame.
Definition at line 67 of file tr_scene.c.
void R_InitShaders (void)
R_InitShaders.
Definition at line 4294 of file tr_shader.c.
void R_InitSkins (void)
R_InitSkins.
Definition at line 1895 of file tr_image.c.
void R_InitSkyTexCoords (float heightCloud)
Called when a sky shader is parsed.
Parameters
[in] heightCloud
Definition at line 882 of file tr_sky.c.
void R_InitVBOs (void)
R_InitVBOs.
Definition at line 550 of file tr_vbo.c.
Referenced by R_Init().
qboolean R_inPVS (const vec3_t p1, const vec3_t p2)
R_inPVS.
Parameters
[in] p1
[in] p2
Returns
Definition at line 709 of file tr_world.c.
void R_IssuePendingRenderCommands (void)
Issue any pending commands and wait for them to complete. After exiting, the render thread will have completed its work and will remain idle and the main thread is free to issue OpenGL calls until R_IssueRenderCommands is called.
Issue any pending commands and wait for them to complete. After exiting, the render thread will have completed its work and will remain idle and the main thread is free to issue OpenGL calls until R_IssueRenderCommands is called.
Definition at line 130 of file tr_cmds.c.
void R_LoadBMP (const char * name, byte ** pic, int * width, int * height, byte alphaByte)
R_LoadBMP.
Parameters
[in] name
[out] pic
[out] width
[out] height
alphaByte - unused
Definition at line 65 of file tr_image_bmp.c.
void R_LoadJPG (const char * filename, unsigned char ** pic, int * width, int * height, byte alphaByte)
R_LoadJPG.
Parameters
[in] filename
[out] pic
[out] width
[out] height
alphaByte - unused
Definition at line 101 of file tr_image_jpg.c.
void R_LoadPCX (const char * filename, byte ** pic, int * width, int * height, byte alphaByte)
R_LoadPCX.
Parameters
[in] filename
[out] pic
[out] width
[out] height
alphaByte - unused
Todo:
: should use bytes_per_line but original q3 didn't do that either
Definition at line 64 of file tr_image_pcx.c.
void R_LoadPNG (const char * name, byte ** pic, int * width, int * height, byte alphaByte)
The PNG loader.
Parameters
[in] name
[out] pic
[out] width
[out] height
alphaByte is not yet implemented
Definition at line 1650 of file tr_image_png.c.
void R_LoadTGA (const char * name, byte ** pic, int * width, int * height, byte alphaByte)
R_LoadTGA.
Parameters
[in,out] name
[out] pic
[out] width
[out] height
[in] alphaByte
Definition at line 55 of file tr_image_tga.c.
void R_LocalNormalToWorld (vec3_t local, vec3_t world)
R_LocalNormalToWorld.
Parameters
[in] local
[out] world
[in] local
[in] world
Definition at line 387 of file tr_main.c.
void R_LocalPointToWorld (vec3_t local, vec3_t world)
R_LocalPointToWorld.
Parameters
[in] local
[out] world
[in] local
[in] world
Definition at line 399 of file tr_main.c.
int R_MarkFragments (int numPoints, const vec3_t * points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t * fragmentBuffer)
R_MarkFragments.
Parameters
[in] numPoints
[in] points
[in] projection
[in] maxPoints
[in] pointBuffer
[in] maxFragments
[in,out] fragmentBuffer
Returns
Parameters
[in] numPoints
[in] points
[in] projection
[in] maxPoints
[in] pointBuffer
[in] maxFragments
[in] fragmentBuffer
Returns
Definition at line 342 of file tr_marks.c.
void R_MDM_AddAnimSurfaces (trRefEntity_t * ent)
R_MDM_AddAnimSurfaces.
Parameters
[in] ent
[in,out] ent
Definition at line 361 of file tr_animation_mdm.c.
int R_MDM_GetBoneTag (orientation_t * outTag, mdmModel_t * mdm, int startTagIndex, const refEntity_t * refent, const char * tagName)
R_MDM_GetBoneTag.
Parameters
[out] outTag
[in] mdm
[in] startTagIndex
[in] refent
[in] tagName
Returns
Definition at line 2537 of file tr_animation_mdm.c.
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
R_ModelBounds.
Parameters
[in] handle
[out] mins
[out] maxs
Definition at line 2200 of file tr_model.c.
void R_ModelInit (void)
R_ModelInit.
Definition at line 1872 of file tr_model.c.
void R_Modellist_f (void)
R_Modellist_f.
Definition at line 1896 of file tr_model.c.
float R_ProcessLightmap (byte * pic, int in_padding, int width, int height, byte * pic_out)
R_ProcessLightmap.
Parameters
[in] pic
[in] in_padding
[in] width
[in] height
[out] pic_out
Returns
maxIntensity
Todo:
: check range)
Todo:
: check range)
Todo:
: check range)
Definition at line 144 of file tr_bsp.c.
void R_ProjectDecalOntoSurface (decalProjector_t * dp, bspSurface_t * surf, bspModel_t * bmodel)
Projects a decal onto a world surface.
Parameters
[in] dp
[in] surf
[in] bmodel
Definition at line 817 of file tr_decals.c.
float R_ProjectRadius (float r, vec3_t location)
R_ProjectRadius.
Parameters
[in] r
[in] location
Returns
Definition at line 944 of file tr_main.c.
Referenced by R_ComputeLOD(), and R_SetupLightLOD().
void R_RemapShader (const char * shaderName, const char * newShaderName, const char * timeOffset)
R_RemapShader.
Parameters
[in] shaderName
[in] newShaderName
[in] timeOffset
[in] shaderName
[in] newShaderName
timeOffset
Definition at line 77 of file tr_shader.c.
void R_RenderView (viewParms_t * parms)
A view may be either the actual camera view, or a mirror / remote location.
Parameters
parms
[in] parms
Definition at line 1862 of file tr_main.c.
void R_RotateEntityForLight (const trRefEntity_t * ent, const trRefLight_t * light, orientationr_t * orientation)
Generates an orientation for an entity and light. Does NOT produce any GL calls. Called by both the front end and the back end.
Parameters
[in] ent
[in] light
[out] orientation
Definition at line 1063 of file tr_main.c.
Referenced by RB_RenderInteractionsShadowMapped().
void R_RotateEntityForViewParms (const trRefEntity_t * ent, const viewParms_t * viewParms, orientationr_t * orientation)
Generates an orientation for an entity and viewParms. Does NOT produce any GL calls. Called by both the front end and the back end.
Parameters
[in] ent
[in] viewParms
[out] orientation
Definition at line 1006 of file tr_main.c.
Referenced by IsMirror(), R_AddEntitySurfaces(), R_GetPortalOrientations(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), and SurfIsOffscreen().
void R_RotateLightForViewParms (const trRefLight_t * ent, const viewParms_t * viewParms, orientationr_t * orientation)
R_RotateLightForViewParms.
Parameters
[in] ent
[in] viewParms
[out] orientation
Definition at line 1129 of file tr_main.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), RB_RenderDebugUtils(), and RenderLightOcclusionVolume().
void R_SetColorMappings (void)
R_SetColorMappings.
Definition at line 1350 of file tr_image.c.
void R_SetDefaultFBO (void)
R_SetDefaultFBO.
Definition at line 475 of file tr_fbo.c.
Referenced by GL_SetDefaultState().
void R_SetFrameFog ()
R_SetFrameFog.
Todo:
: since this is the most common occurance, diff first and only set changes
Todo:
: since this is the most common occurance, diff first and only set changes
Todo:
: since this is the most common occurance, diff first and only set changes
Definition at line 619 of file tr_main.c.
Referenced by R_RenderView(), and SetFarClip().
void R_SetupEntityLighting (const trRefdef_t * refdef, trRefEntity_t * ent, vec3_t forcedOrigin)
Calculates all the lighting values that will be used by the Calc_* functions.
Parameters
[in] refdef
[in,out] ent
[in] forcedOrigin
Note
R_SetupEntityLightingGrid deals with forcedOrigin
Definition at line 303 of file tr_light.c.
void R_SetupEntityWorldBounds (trRefEntity_t * ent)
R_SetupEntityWorldBounds.
Parameters
[in] ent
Note
needs R_RotateEntityForViewParms
Definition at line 992 of file tr_main.c.
Referenced by R_CullMD5(), R_CullMDV(), and R_CullModel().
void R_SetupFrustum (void)
Setup that culling frustum planes for the current view.
Definition at line 843 of file tr_main.c.
Referenced by R_RenderView(), and R_SetupProjection().
void R_SetupFrustum2 (frustum_t frustum, const mat4_t mvp)
Setup that culling frustum planes for the current view.
Parameters
[out] frustum
[in] mvp
Definition at line 1535 of file tr_main.c.
Referenced by MergeInteractionBounds(), R_CalcLightCubeSideBits(), and R_RenderView().
void R_SetupLightFrustum (trRefLight_t * light)
R_SetupLightFrustum.
Parameters
[in,out] light
Definition at line 575 of file tr_light.c.
Referenced by R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightLocalBounds (trRefLight_t * light)
R_SetupLightLocalBounds.
Parameters
[in,out] light
Definition at line 448 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightLOD (trRefLight_t * light)
R_SetupLightLOD.
Parameters
[in,out] light
Definition at line 1702 of file tr_light.c.
Referenced by R_AddLightInteractions().
void R_SetupLightOrigin (trRefLight_t * light)
R_SetupLightOrigin.
Parameters
[in,out] light
Note
Needs finished transformMatrix
Definition at line 409 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightProjection (trRefLight_t * light)
R_SetupLightProjection.
Parameters
[in,out] light
Todo:
?
Todo:
: I don't like hacking the matrix like this, but all attempts to use
Definition at line 830 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightScissor (trRefLight_t * light)
Recturns the screen space rectangle taken by the box. (Clips the box to the near plane to have correct results even if the box intersects the near plane)
recoded from Tenebrae2
Parameters
[in,out] light
Definition at line 1296 of file tr_light.c.
Referenced by R_AddLightInteractions().
void R_SetupLightShader (trRefLight_t * light)
R_SetupLightShader.
Parameters
[in,out] light
Definition at line 1779 of file tr_light.c.
Referenced by R_AddLightInteractions().
void R_SetupLightView (trRefLight_t * light)
R_SetupLightView.
Parameters
[in] light
Definition at line 541 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_SetupLightWorldBounds (trRefLight_t * light)
R_SetupLightWorldBounds.
Parameters
[in] light
Note
Needs finished transformMatrix
Definition at line 532 of file tr_light.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
void R_ShaderExp_f (void)
R_ShaderExp_f.
Definition at line 6330 of file tr_shader.c.
Referenced by R_Register().
void R_ShaderList_f (void)
Dump information on all valid shaders to the console A second parameter will cause it to print in sorted order.
Definition at line 3668 of file tr_shader.c.
void R_ShutdownFBOs (void)
R_ShutdownFBOs.
Definition at line 902 of file tr_fbo.c.
Referenced by RE_Shutdown().
void R_ShutdownImages (void)
R_ShutdownImages.
Definition at line 3708 of file tr_image.c.
Referenced by RE_Shutdown().
void R_ShutdownVBOs ()
R_ShutdownVBOs.
Definition at line 598 of file tr_vbo.c.
Referenced by RE_Shutdown().
void R_SkinList_f (void)
R_SkinList_f.
Definition at line 1926 of file tr_image.c.
void R_SortInteractions (trRefLight_t * light)
R_SortInteractions.
Parameters
[in] light
Definition at line 1141 of file tr_light.c.
Referenced by R_AddLightInteractions().
srfGridMesh_t* R_SubdividePatchToGrid (int width, int height, srfVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
R_SubdividePatchToGrid.
Parameters
[in] width
[in] height
[in] points
Returns
Todo:
: also check midpoints of adjacent patches against the control points
Definition at line 719 of file tr_curve.c.
void R_SubImageCpy (byte * dest, size_t destx, size_t desty, size_t destw, size_t desth, byte * src, size_t srcw, size_t srch, size_t bytes, qboolean in)
Copies between a smaller image and a larger image. Last flag controls is copy in or out of larger image.
Parameters
[in,out] dest
[in] destx
[in] desty
[in] destw
[in] desth
[in,out] src
[in] srcw
[in] srch
[in] bytes
[in] in
Note
e.g. dest = Com_Allocate(4*4*channels); [________] [________] [________] [________] src = Com_Allocate(2*2*channels); [____] [____] R_SubImageCpy(dest, 0, 0, 4, 4, src, 2, 2, channels, qtrue); [____]___] [____]___] [________]
[________]
Definition at line 2548 of file tr_image.c.
Referenced by R_BuildCubeMaps(), and R_LoadCubeProbe().
int R_SumOfUsedImages (void)
R_SumOfUsedImages.
Returns
Todo:
FIXME: add this to R_ImageList_f output?
Returns
Todo:
FIXME: add this to R_ImageList_f output?
Definition at line 186 of file tr_image.c.
void R_SwapBuffers (int)
qboolean R_TestDecalBoundingBox (decalProjector_t * dp, vec3_t mins, vec3_t maxs)
R_TestDecalBoundingBox.
Parameters
[in] dp
[in] mins
[in] maxs
Returns
qtrue if the decal projector intersects the bounding box
Definition at line 461 of file tr_decals.c.
qboolean R_TestDecalBoundingSphere (decalProjector_t * dp, vec3_t center, float radius2)
R_TestDecalBoundingSphere.
Parameters
[in] dp
[in] center
[in] radius2
Returns
qtrue if the decal projector intersects the bounding sphere
Definition at line 479 of file tr_decals.c.
void R_TransformClipToWindow (const vec4_t clip, const viewParms_t * view, vec4_t normalized, vec4_t window)
R_TransformClipToWindow.
Parameters
[in] clip
[in] view
[out] normalized
[out] window
Definition at line 459 of file tr_main.c.
void R_TransformDecalProjector (decalProjector_t * in, vec3_t axis[3], vec3_t origin, decalProjector_t * out)
Transforms a decal projector.
Parameters
[in] in
[in] axis
[in] origin
[out] out
Note
Non-normalized axes will screw up the plane transform
Definition at line 403 of file tr_decals.c.
void R_TransformModelToClip (const vec3_t src, const float * modelMatrix, const float * projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformModelToClip.
Parameters
[in] src
[in] modelMatrix
[in] projectionMatrix
[out] eye
[out] dst
[in] src
[in] modelMatrix
[in] projectionMatrix
[in] eye
[out] dst
Definition at line 428 of file tr_main.c.
void R_TransformWorldToClip (const vec3_t src, const float * cameraViewMatrix, const float * projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformWorldToClip.
Parameters
[in] src
[in] cameraViewMatrix
[in] projectionMatrix
[in] eye
[out] dst
Definition at line 886 of file tr_main.c.
Referenced by R_AddPointToLightScissor().
void R_UploadImage (const byte ** dataArray, int numData, image_t * image)
R_UploadImage.
Parameters
[in] dataArray
[in] numData
[in] image
Todo:
: deal with frame buffer object? No mipmap for now ...
Definition at line 1021 of file tr_image.c.
Referenced by R_BuildCubeMaps(), R_CreateCubeImage(), and R_CreateImage().
void R_VBOList_f (void)
R_VBOList_f.
Definition at line 664 of file tr_vbo.c.
Referenced by R_Register().
void RB_AddFlare (void * surface, int fogNum, vec3_t point, vec3_t color, vec3_t normal, qboolean visible, qboolean isCorona)
This is called at surface tesselation time.
Parameters
[in] surface
[in] fogNum
[in] point
[in] color
[in] normal
[in] visible
Definition at line 128 of file tr_flares.c.
void RB_AddLightFlares (void)
RB_AddLightFlares.
Definition at line 245 of file tr_flares.c.
Referenced by RB_RenderFlares().
void RB_CalcTexMatrix (const textureBundle_t * bundle, mat4_t matrix)
RB_CalcTexMatrix.
Parameters
[in] bundle
[in] matrix
Definition at line 1076 of file tr_shade_calc.c.
Referenced by R_ComputeFinalAttenuation().
void RB_DrawSun (void)
RB_DrawSun.
Todo:
FIXME: sun should render behind clouds, so passing dark areas cover it up
Todo:
FIXME: sun should render behind clouds, so passing dark areas cover it up
Todo:
: todo: flare effect should render last (on top of everything else) and only when sun is in view (sun moving out of camera past degree n should start to cause flare dimming until view angle to sun is off by angle n + x.
Todo:
: todo: flare effect should render last (on top of everything else) and only when sun is in view (sun moving out of camera past degree n should start to cause flare dimming until view angle to sun is off by angle n + x.
Todo:
: todo: flare effect should render last (on top of everything else) and only when sun is in view (sun moving out of camera past degree n should start to cause flare dimming until view angle to sun is off by angle n + x.
Definition at line 945 of file tr_sky.c.
float RB_EvalExpression (const expression_t * exp, float defaultValue)
RB_EvalExpression.
Parameters
[in] exp
[in] defaultValue
Returns
Definition at line 244 of file tr_shade_calc.c.
Referenced by R_ShaderExp_f(), RB_CalcTexMatrix(), and Render_lightVolume().
float RB_EvalWaveForm (const waveForm_t * wf)
Evaluates a given waveForm_t, referencing backEnd.refdef.time directly.
Parameters
[in] wf
Returns
Definition at line 81 of file tr_shade_calc.c.
Referenced by RB_CalcDeformVertexes(), RB_CalcTexMatrix(), and RB_EvalWaveFormClamped().
float RB_EvalWaveFormClamped (const waveForm_t * wf)
RB_EvalWaveFormClamped.
Parameters
[in] wf
Returns
Definition at line 95 of file tr_shade_calc.c.
void RB_ExecuteRenderCommands (const void * data)
RB_ExecuteRenderCommands.
Parameters
[in] data RB_ExecuteRenderCommands.
[in] data
Definition at line 1526 of file tr_backend.c.
void RB_Fog (glfog_t * curfog)
RB_Fog.
Parameters
[in,out] curfog
Definition at line 44 of file tr_fog.c.
void RB_FogOff ()
Allow disabling fog temporarily.
Definition at line 104 of file tr_fog.c.
Referenced by RB_Fog(), and RB_FogOn().
void RB_FogOn ()
RB_FogOn.
Definition at line 121 of file tr_fog.c.
Referenced by RB_Fog().
void RB_ProjectionShadowDeform (void)
RB_ProjectionShadowDeform.
Note
for a projection shadow:
point[x] += light vector * (z - shadow plane) point[y] += point[z] = shadow plane
1 0 light[x] / light[z]
Definition at line 305 of file tr_shadows.c.
void RB_RenderFlares (void)
Because flares are simulating an occular effect, they should be drawn after everything (all views) in the entire frame has been drawn.
Because of the way portals use the depth buffer to mark off areas, the needed information would be lost after each view, so we are forced to draw flares after each view.
The resulting artifact is that flares in mirrors or portals don't dim properly when occluded by something in the main view, and portal flares that should extend past the portal edge will be overwritten.
Definition at line 480 of file tr_flares.c.
void RB_SetViewMVPM (void)
Set the model view projection matrix to match the ingame view.
Definition at line 143 of file tr_backend.c.
Referenced by RB_CameraPostFX(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), and Render_lightVolume().
void RB_ShowImages (void)
Draw all the images to the screen, on top of whatever was there. This is used to test for texture thrashing.
Also called by RE_EndRegistration
Definition at line 1322 of file tr_backend.c.
const void* RB_TakeScreenshotCmd (const void * data)
RB_TakeScreenshotCmd.
Parameters
[in] data
Returns
Definition at line 513 of file tr_init.c.
const void* RB_TakeVideoFrameCmd (const void * data)
RB_TakeVideoFrameCmd.
Parameters
[in] data
Returns
Definition at line 595 of file tr_init.c.
void RE_2DPolyies (polyVert_t * verts, int numverts, qhandle_t hShader)
RE_2DPolyies.
Parameters
[in] verts
[in] numverts
[in] hShader
Definition at line 258 of file tr_cmds.c.
void RE_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
RE_AddCoronaToScene.
Parameters
[in] org
[in] r
[in] g
[in] b
[in] scale
[in] id
[in] visible
Definition at line 488 of file tr_scene.c.
void RE_AddDynamicLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
modified dlight system to support seperate radius and intensity
Parameters
[in] org
[in] radius
[in] intensity
[in] r
[in] g
[in] b
hShader
flags - unused
Note
vanilla mods deliver 0 hShader only
Definition at line 498 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_AddPolyBufferToScene (polyBuffer_t * pPolyBuffer)
RE_AddPolyBufferToScene.
Parameters
[in] pPolyBuffer
Definition at line 329 of file tr_scene.c.
void RE_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int numPolys)
RE_AddPolysToScene.
Parameters
[in] hShader
[in] numVerts
[in] verts
[in] numPolys
Definition at line 220 of file tr_scene.c.
void RE_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
RE_AddPolyToScene.
Parameters
[in] hShader
[in] numVerts
[in] verts
Definition at line 141 of file tr_scene.c.
void RE_AddRefEntityToScene (const refEntity_t * ent)
RE_AddRefEntityToScene.
Parameters
[in] ent
Definition at line 382 of file tr_scene.c.
int RE_AnimFrameRate (qhandle_t hAnim)
RE_AnimFrameRate.
Parameters
[in] hAnim
Returns
Todo:
Unused ?
Definition at line 1654 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_AnimNumFrames (qhandle_t hAnim)
RE_AnimNumFrames.
Parameters
[in] hAnim
Returns
Todo:
Unused ?
Definition at line 1628 of file tr_animation.c.
Referenced by GetRefAPI().
void RE_BeginFrame (void)
Will be called once for each RE_EndFrame.
Definition at line 438 of file tr_cmds.c.
void RE_BeginRegistration (glconfig_t * glconfigOut)
RE_BeginRegistration.
Parameters
[out] glconfigOut
Definition at line 1847 of file tr_model.c.
int RE_BlendSkeleton (refSkeleton_t * skel, const refSkeleton_t * blend, float frac)
RE_BlendSkeleton.
Parameters
[in] skel
[in] blend
[in] frac
Returns
Definition at line 1586 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_BoneIndex (qhandle_t hModel, const char * boneName)
RE_BoneIndex.
Parameters
[in] hModel
[in] boneName
Returns
Definition at line 911 of file tr_model.c.
Referenced by GetRefAPI(), and RE_LerpTagET().
int RE_BuildSkeleton (refSkeleton_t * skel, qhandle_t hAnim, int startFrame, int endFrame, float frac, qboolean clearOrigin)
RE_BuildSkeleton.
Parameters
[out] skel
[in] hAnim
[in] startFrame
[in] endFrame
[in] frac
[in] clearOrigin
Returns
Todo:
: clear existing bones and bounds?
Definition at line 1348 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_CheckSkeleton (refSkeleton_t * skel, qhandle_t hModel, qhandle_t hAnim)
Check if the skeleton bones are the same in the model and animation and copy the parentIndex entries into the refSkeleton_t.
Parameters
[out] skel
[in] hModel
[in] hAnim
Returns
Definition at line 1254 of file tr_animation.c.
Referenced by GetRefAPI().
void RE_ClearDecals (void)
Clears decals from the world and entities.
Definition at line 367 of file tr_decals.c.
void RE_ClearScene (void)
RE_ClearScene.
Definition at line 100 of file tr_scene.c.
void RE_EndFrame (int * frontEndMsec, int * backEndMsec)
Returns the number of msec spent in the back end.
Parameters
[out] frontEndMsec
[out] backEndMsec
Definition at line 538 of file tr_cmds.c.
void RE_Finish (void)
RE_Finish.
Definition at line 608 of file tr_cmds.c.
qhandle_t RE_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
RE_GetShaderFromModel.
Parameters
[in] modelid
[in] surfnum
withlightmap set to '0' will create a new shader that is a copy of the one found on the model, without the lighmap stage, if the shader has a lightmap stage
Returns
A shader index for a given model's surface
Note
Only works for bmodels right now. Could modify for other models (md3's etc.)
Todo:
FIXME:
withlightmap is unused
Parameters
[in] modelid
[in] surfnum
withlightmap set to '0' will create a new shader that is a copy of the one found on the model, without the lighmap stage, if the shader has a lightmap stage - unused
Returns
a shader index for a given model's surface
Note
Only works for bmodels right now. Could modify for other models (md3's etc.)
Parameters
[in] modelid
[in] surfnum
withlightmap set to '0' will create a new shader that is a copy of the one found on the model, without the lighmap stage, if the shader has a lightmap stage
Returns
A shader index for a given model's surface
Note
Only works for bmodels right now. Could modify for other models (md3's etc.)
Todo:
FIXME:
withlightmap is unused
Definition at line 1654 of file tr_image.c.
qboolean RE_GetSkinModel (qhandle_t skinid, const char * type, char * name)
RE_GetSkinModel.
Parameters
[in] skinid
[in] type
[in] name
Returns
Parameters
[in] skinid
[in] type
[out] name
Returns
Definition at line 1617 of file tr_image.c.
int RE_GetTextureId (const char * name)
RE_GetTextureId.
Parameters
name
Returns
Definition at line 3739 of file tr_image.c.
Referenced by GetRefAPI().
int RE_LerpTagET (orientation_t * tag, const refEntity_t * refent, const char * tagNameIn, int startIndex)
RE_LerpTagET.
Parameters
[in,out] tag
[in] refent
[in] tagNameIn
[in] startIndex
Returns
Todo:
: retval is reassigned before used, does it was intended ?
Definition at line 750 of file tr_model.c.
Referenced by GetRefAPI().
int RE_LerpTagQ3A (orientation_t * tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char * tagNameIn)
RE_LerpTagQ3A.
Parameters
[in,out] tag
[in] handle
[in] startFrame
[in] endFrame
[in] frac
[in] tagNameIn
Returns
Note
Unused
Todo:
: retval is reassigned before used, does it was intended ?
Definition at line 695 of file tr_model.c.
qboolean RE_LoadDynamicShader (const char * shadername, const char * shadertext)
load a new dynamic shader if shadertext is NULL, looks for matching shadername and removes it
Parameters
[in] shadername
[in] shadertext
Returns
qtrue if request was successful, qfalse if the gods were angered
load a new dynamic shader if shadertext is NULL, looks for matching shadername and removes it
Parameters
[in] shadername
[in] shadertext
Returns
qtrue if request was successful, qfalse if the gods were angered
Definition at line 2996 of file tr_shader.c.
void RE_LoadWorldMap (const char * name)
RE_LoadWorldMap.
Parameters
[in] name RE_LoadWorldMap.
[in] name
Todo:
:(SA)this is sort of silly. I'm going to do a general cleanup on fog stuff
Todo:
: this is sort of silly. I'm going to do a general cleanup on fog stuff
Todo:
: causes missing vbo error on radar (maps with portal sky or foliage)
Todo:
:(SA)this is sort of silly. I'm going to do a general cleanup on fog stuff
Definition at line 2579 of file tr_bsp.c.
void RE_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t * points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
Creates a new decal projector from a triangle.
Projected polygons should be 3 or 4 points.
If a single point is passed in (numPoints == 1) then the decal will be omnidirectional omnidirectional decals use points[ 0 ] as center and projection[ 3 ] as radius pass in lifeTime < 0 for a temporary mark.
Parameters
[in] hShader
[in] numPoints
[in] points
[in] projection
[in] color
[in] lifeTime
[in] fadeTime
Todo:
: stale refdef time
Todo:
: support arbitrary projector st coordinates in trapcall)
Todo:
: stale refdef time
Todo:
: support arbitrary projector st coordinates in trapcall)
Todo:
: stale refdef time
Todo:
: support arbitrary projector st coordinates in trapcall)
Definition at line 151 of file tr_decals.c.
qhandle_t RE_RegisterAnimation (const char * name)
RE_RegisterAnimation.
Parameters
[in] name
Returns
Definition at line 749 of file tr_animation.c.
Referenced by GetRefAPI().
qhandle_t RE_RegisterModel (const char * name)
Loads in a model for the given name.
Zero will be returned if the model fails to load. An entry will be retained for failed models as an optimization to prevent disk rescanning if they are asked for again.
Parameters
[in] name
Returns
Parameters
[in] name
Returns
Zero will be returned if the model fails to load. An entry will be retained for failed models as an optimization to prevent disk rescanning if they are asked for again.
Todo:
: catch shader case earlier and avoid i/o (mod code?)
Todo:
: catch shader case earlier and avoid i/o (mod code?)
Todo:
: catch shader case earlier and avoid i/o (mod code?)
Definition at line 163 of file tr_model.c.
qhandle_t RE_RegisterShader (const char * name)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
This should really only be used for explicit shaders, because there is no way to ask for different implicit lighting modes (vertex, lightmap, etc)
Parameters
[in] name
Returns
Definition at line 3584 of file tr_shader.c.
qhandle_t RE_RegisterShaderFromImage (const char * name, image_t * image, qboolean mipRawImage)
RE_RegisterShaderFromImage.
Parameters
[in] name
[in] image
mipRawImage - unused
Returns
Definition at line 5930 of file tr_shader.c.
qhandle_t RE_RegisterShaderLightAttenuation (const char * name)
For different Doom3 style light effects.
Parameters
[in] name
Returns
Definition at line 6056 of file tr_shader.c.
Referenced by GetRefAPI(), and R_LoadLights().
qhandle_t RE_RegisterShaderNoMip (const char * name)
RE_RegisterShaderNoMip.
Parameters
name
Returns
Note
For menu graphics that should never be picmiped
RE_RegisterShaderNoMip.
Parameters
[in] name
Returns
Definition at line 3617 of file tr_shader.c.
qhandle_t RE_RegisterSkin (const char * name)
RE_RegisterSkin.
Parameters
[in] name
Returns
Todo:
: bspSurface not not have hash yet
Todo:
: bspSurface not not have hash yet
Definition at line 1727 of file tr_image.c.
void RE_RenderScene (const refdef_t * fd)
Draw a 3D view into a part of the window, then return to 2D drawing.
Rendering a scene may require multiple views to be rendered to handle mirrors.
Parameters
[in] fd
Definition at line 527 of file tr_scene.c.
void RE_RenderToTexture (int textureid, int x, int y, int w, int h)
RE_RenderToTexture.
Parameters
[in] textureid
[in] x
[in] y
[in] w
[in] h
Definition at line 580 of file tr_cmds.c.
void RE_RotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
RE_RotatedPic.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] angle
Definition at line 296 of file tr_cmds.c.
void RE_SaveJPG (const char * filename, int quality, int image_width, int image_height, byte * image_buffer, int padding)
RE_SaveJPG.
Parameters
[in] filename
[in] quality
[in] image_width
[in] image_height
[in] image_buffer
[in] padding
Definition at line 487 of file tr_image_jpg.c.
size_t RE_SaveJPGToBuffer (byte * buffer, size_t bufSize, int quality, int image_width, int image_height, byte * image_buffer, int padding)
Encodes JPEG from image in image_buffer and writes to buffer. Expects RGB input data.
Parameters
[out] buffer
[in] bufSize
[in] quality
[in] image_width
[in] image_height
[in] image_buffer
[in] padding
Returns
Definition at line 412 of file tr_image_jpg.c.
void RE_SetClipRegion (const float * region)
RE_SetClipRegion.
Parameters
[in] region
Definition at line 364 of file tr_cmds.c.
void RE_SetColor (const float * rgba)
Passing NULL will set the color to white.
Parameters
[in] rgba
Definition at line 193 of file tr_cmds.c.
void RE_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
RE_SetFog.
Parameters
[in] fogvar
[in] var1
[in] var2
[in] r
[in] g
[in] b
[in] density
Note
if fogvar == FOG_CMD_SWITCHFOG { fogvar is the command var1 is the fog to switch to var2 is the time to transition } else { fogvar is the fog that's being set var1 is the near fog z value var2 is the far fog z value rgb = color density is density, and is used to derive the values of 'mode', 'drawsky', and 'clearscreen' }
Todo:
: handle transition if there is no FOG_MAP fog
Definition at line 185 of file tr_fog.c.
Referenced by GetRefAPI(), ParseShader(), ParseShaderR1(), and RE_LoadWorldMap().
void RE_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
RE_SetGlobalFog.
Parameters
[in] restore flag can be used to restore the original level fog
[in] duration can be set to fade over a certain period
[in] r colour
[in] g colour
[in] b colour
[in] depthForOpaque is depth for opaque
Definition at line 386 of file tr_cmds.c.
void RE_SetWorldVisData (const byte * vis)
This is called by the clipmodel subsystem so we can share the 1.8 megs of space in big maps...
Parameters
[in] vis
vis
Definition at line 270 of file tr_bsp.c.
void RE_Shutdown (qboolean destroyWindow)
RE_Shutdown.
Parameters
[in] destroyWindow
Definition at line 1238 of file tr_init.c.
void RE_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
RE_StretchPic.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
Definition at line 228 of file tr_cmds.c.
void RE_StretchPicGradient (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float * gradientColor, int gradientType)
RE_StretchPicGradient.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] gradientColor
[in] gradientType
Definition at line 342 of file tr_cmds.c.
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Todo:
FIXME: not exactly backend
Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Todo:
FIXME: not exactly backend Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Todo:
FIXME: not exactly backend
Definition at line 832 of file tr_backend.c.
void RE_TakeVideoFrame (int width, int height, byte * captureBuffer, byte * encodeBuffer, qboolean motionJpeg)
RE_TakeVideoFrame.
Parameters
[in] width
[in] height
[in] captureBuffer
[in] encodeBuffer
[in] motionJpeg
Definition at line 630 of file tr_cmds.c.
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
RE_UploadCinematic.
Parameters
w - unused
h - unused
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Definition at line 924 of file tr_backend.c.
static ID_INLINE void RemoveLink (link_t * l) static
RemoveLink.
Parameters
[in,out] l
Definition at line 182 of file tr_local.h.
Referenced by DeQueue(), and StackPop().
qboolean ShaderRequiresCPUDeforms (const shader_t * shader)
ShaderRequiresCPUDeforms.
Parameters
[in] shader
Returns
Definition at line 967 of file tr_shade_calc.c.
Referenced by R_AddBSPModelSurfaces(), R_AddWorldSurface(), R_CreateSubModelVBOs(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_inPVS(), RB_RenderInteractionsShadowMapped(), Tess_DeformGeometry(), Tess_SurfaceFace(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), and Tess_SurfaceTriangles().
static ID_INLINE qboolean StackEmpty (link_t * l) static
StackEmpty.
Parameters
[in] l
Returns
Definition at line 225 of file tr_local.h.
static ID_INLINE void* StackPop (link_t * l) static
StackPop.
Parameters
[in] l
Returns
Definition at line 261 of file tr_local.h.
static ID_INLINE void StackPush (link_t * sentinel, void * data) static
StackPush.
Parameters
[in] sentinel
[in] data
Definition at line 246 of file tr_local.h.
static ID_INLINE link_t* StackTop (link_t * l) static
StackTop.
Parameters
[in] l
Returns
Definition at line 236 of file tr_local.h.
void Tess_AddCube (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCube.
Parameters
[in] position
[in] minSize
[in] maxSize
[in] color
Definition at line 358 of file tr_surface.c.
Referenced by R_InitUnitCubeVBO(), R_LoadNodesAndLeafs(), R_SetupLightFrustum(), RB_RenderDebugUtils(), RenderEntityOcclusionVolume(), and RenderLightOcclusionVolume().
void Tess_AddCubeWithNormals (const vec3_t position, const vec3_t minSize, const vec3_t maxSize, const vec4_t color)
Tess_AddCubeWithNormals.
Parameters
[in] position
[in] minSize
[in] maxSize
[in] color
Definition at line 411 of file tr_surface.c.
Referenced by RB_RenderDebugUtils().
void Tess_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color)
Tess_AddQuadStamp.
Parameters
[in] origin
[in] left
[in] up
[in] color
Definition at line 199 of file tr_surface.c.
Referenced by AutospriteDeform(), RB_DrawSun(), Tess_SurfaceSplash(), and Tess_SurfaceSprite().
void Tess_AddQuadStamp2 (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2.
Parameters
[in] quadVerts
[in] color
Definition at line 294 of file tr_surface.c.
Referenced by R_SetupLightFrustum(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderLightOcclusionVolume(), and Tess_AddCube().
void Tess_AddQuadStamp2WithNormals (vec4_t quadVerts[4], const vec4_t color)
Tess_AddQuadStamp2WithNormals.
Parameters
[in] quadVerts
[in] color
Definition at line 304 of file tr_surface.c.
Referenced by Tess_AddCubeWithNormals().
void Tess_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, const vec4_t color, float s1, float t1, float s2, float t2)
Tess_AddQuadStampExt.
Parameters
[in] origin
[in] left
[in] up
[in] color
[in] s1
[in] t1
[in] s2
[in] t2
Definition at line 109 of file tr_surface.c.
Referenced by DeformText(), RB_RenderDebugUtils(), and Tess_AddQuadStamp().
void Tess_AddQuadStampExt2 (vec4_t quadVerts[4], const vec4_t color, float s1, float t1, float s2, float t2, qboolean calcNormals)
Tess_AddQuadStampExt2.
Parameters
[in] quadVerts
[in] color
[in] s1
[in] t1
[in] s2
[in] t2
[in] calcNormals
Definition at line 214 of file tr_surface.c.
Referenced by Tess_AddQuadStamp2(), and Tess_AddQuadStamp2WithNormals().
void Tess_AddTetrahedron (vec4_t tetraVerts[4], const vec4_t color)
Tess_AddTetrahedron.
Parameters
[in] tetraVerts
[in] color
Definition at line 314 of file tr_surface.c.
Referenced by RB_RenderDebugUtils().
void Tess_Begin (void(*)() stageIteratorFunc, void(*)() stageIteratorFunc2, shader_t * surfaceShader, shader_t * lightShader, qboolean skipTangentSpaces, qboolean skipVBO, int lightmapNum, int fogNum)
We must set some things up before beginning any tesselation, because a surface may be forced to perform a Tess_End due to overflow.
Parameters
stageIteratorFunc
stageIteratorFunc2
[in] surfaceShader
[in] lightShader
[in] skipTangentSpaces
[in] skipVBO
[in] lightmapNum
[in] fogNum
Definition at line 369 of file tr_shade.c.
Referenced by RB_Draw2dPolys(), RB_DrawSun(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderFlare(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), SurfIsOffscreen(), Tess_CheckOverflow(), and Tess_EndBegin().
void Tess_CheckOverflow (int verts, int indexes)
Tess_CheckOverflow.
Parameters
[in] verts
[in] indexes
Definition at line 64 of file tr_surface.c.
Referenced by RB_Draw2dPolys(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), Tess_AddQuadStampExt(), Tess_AddQuadStampExt2(), Tess_AddTetrahedron(), Tess_DoRailDiscs(), Tess_MDM_SurfaceAnim(), Tess_SurfaceAxis(), Tess_SurfaceDecal(), Tess_SurfaceFace(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), Tess_SurfaceMD5(), Tess_SurfaceMDV(), Tess_SurfacePolybuffer(), Tess_SurfacePolychain(), and Tess_SurfaceTriangles().
void Tess_ComputeColor (shaderStage_t * pStage)
Tess_ComputeColor.
Parameters
[in] pStage
Todo:
Todo:
?
Todo:
?
Todo:
: rework/move to GL
Definition at line 2568 of file tr_shade.c.
Referenced by Render_lightVolume().
void Tess_DeformGeometry ()
Tess_DeformGeometry.
Definition at line 997 of file tr_shade_calc.c.
void Tess_DrawElements ()
Tess_DrawElements.
Definition at line 65 of file tr_shade.c.
Referenced by DrawSkyBox(), DrawTris(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RE_StretchRaw(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_InstantQuad(), and TraverseNode().
void Tess_End (void)
Render tesselated data.
Definition at line 3667 of file tr_shade.c.
Referenced by RB_Draw2dPolys(), RB_DrawSun(), RB_DrawView(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderFlare(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), RB_SwapBuffers(), Tess_CheckOverflow(), Tess_EndBegin(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), and Tess_SurfaceVBOMesh().
void Tess_EndBegin ()
Tess_EndBegin.
Definition at line 52 of file tr_surface.c.
Referenced by Tess_CheckOverflow(), Tess_DrawCurrent(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFlare(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), and Tess_SurfaceVBOMesh().
void Tess_InstantQuad (vec4_t quadVerts[4])
Tess_InstantQuad.
Parameters
[in] quadVerts
Definition at line 558 of file tr_surface.c.
Referenced by RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RB_ShowImages(), and Render_lightVolume().
void Tess_MDM_SurfaceAnim (mdmSurfaceIntern_t * surface)
Tess_MDM_SurfaceAnim.
Parameters
[in] surface
Todo:
: lerp the radius and origin
Todo:
Definition at line 1964 of file tr_animation_mdm.c.
void Tess_StageIteratorDebug ()
Tess_StageIteratorDebug.
Definition at line 2998 of file tr_shade.c.
Referenced by RB_RenderDebugUtils().
void Tess_StageIteratorGeneric ()
Tess_StageIteratorGeneric.
Todo:
: remove r_worldInlineModels?
Definition at line 3097 of file tr_shade.c.
Referenced by RB_Draw2dPolys(), RB_DrawSun(), RB_RenderDrawSurfaces(), RB_RenderFlare(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), SurfIsOffscreen(), Tess_Begin(), and Tess_StageIteratorSky().
void Tess_StageIteratorLighting ()
Tess_StageIteratorLighting.
Definition at line 3511 of file tr_shade.c.
Referenced by RB_RenderInteractions(), and RB_RenderInteractionsShadowMapped().
void Tess_StageIteratorShadowFill ()
Tess_StageIteratorDepthFill.
Note
Unused void Tess_StageIteratorDepthFill() { int stage;
Ren_LogComment("--- Tess_StageIteratorDepthFill(%s, %i vertices, %i triangles) ---\n", tess.surfaceShader->name, tess.numVertexes, tess.numIndexes / 3);
GL_CheckErrors();
Tess_DeformGeometry();
if (!glState.currentVBO || !glState.currentIBO || glState.currentVBO == tess.vbo || glState.currentIBO == tess.ibo) { Tess_UpdateVBOs(tess.attribsSet); }
set face culling appropriately GL_Cull(tess.surfaceShader->cullType);
set polygon offset if necessary if (tess.surfaceShader->polygonOffset) { glEnable(GL_POLYGON_OFFSET_FILL); GL_PolygonOffset(r_offsetFactor->value, r_offsetUnits->value); }
call shader function for (stage = 0; stage < MAX_SHADER_STAGES; stage++) { shaderStage_t *pStage = tess.surfaceStages[stage];
if (!pStage) { break; }
if (RB_EvalExpression(&pStage->ifExp, 1.0f) == 0.f) { continue; }
Tess_ComputeTexMatrices(pStage);
switch (pStage->type) { case ST_COLORMAP: { if (tess.surfaceShader->sort <= SS_OPAQUE) { Render_depthFill(stage); } break; } case ST_LIGHTMAP: { Render_depthFill(stage); break; } case ST_DIFFUSEMAP: case ST_COLLAPSE_lighting_DB: case ST_COLLAPSE_lighting_DBS: { Render_depthFill(stage); break; } default: break; } }
reset polygon offset glDisable(GL_POLYGON_OFFSET_FILL); } Tess_StageIteratorShadowFill
Definition at line 3436 of file tr_shade.c.
Referenced by RB_RenderInteractionsShadowMapped().
void Tess_StageIteratorSky ()
All of the visible sky triangles are in tess Other things could be stuck in here, like birds in the sky, etc.
Definition at line 992 of file tr_sky.c.
Referenced by Tess_Begin(), and Tess_SurfaceFace().
void Tess_SurfaceVBOMDMMesh (srfVBOMDMMesh_t * surface)
Tess_SurfaceVBOMDMMesh.
Parameters
[in] surface
Todo:
: lerp the radius and origin
Definition at line 2447 of file tr_animation_mdm.c.
void Tess_UpdateVBOs (uint32_t attribBits)
Update the default VBO to replace the client side vertex arrays.
Parameters
[in] attribBits
Definition at line 461 of file tr_surface.c.
Referenced by BuildCloudData(), DrawSkyBox(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RE_StretchRaw(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), and Tess_InstantQuad().
Variable Documentation
backEndState_t backEnd
Definition at line 38 of file tr_backend.c.
backEndData_t* backEndData
the second one may not be allocated
Definition at line 37 of file tr_backend.c.
const mat4_t flipZMatrix
Definition at line 79 of file tr_main.c.
Referenced by RB_RenderInteractionsShadowMapped().
const GLenum geometricRenderTargets[]
Definition at line 87 of file tr_main.c.
int gl_filter_max
Definition at line 41 of file tr_image.c.
int gl_filter_min
Definition at line 40 of file tr_image.c.
glconfig_t glConfig
outside of TR since it shouldn't be cleared during ref re-init
Definition at line 38 of file tr_init.c.
glconfig2_t glConfig2
Definition at line 41 of file tr_init.c.
Referenced by AddTriangleToVBOTriangleList(), DrawTris(), GetOpValue(), GL_TextureMode(), GLimp_CheckForVersionExtension(), GLimp_InitExtensionsR2(), GLimp_InitOpenGLContext(), GLSL_BuildShaderExtraDef(), GLSL_GetShaderHeader(), GLSL_LinkProgram(), GLSL_LoadShaderBinary(), GLSL_MissesRequiredMacros(), GLSL_SaveShaderBinary(), GLSL_VertexAttribPointers(), GLSL_VertexAttribsState(), R_AddEdgeToLightScissor(), R_AddLightBoundsToVisBounds(), R_AddLightInteraction(), R_AddLightInteractions(), R_AddMD5Interactions(), R_AddMD5Surfaces(), R_AddMDMInteractions(), R_AddWorldSurfaces(), R_AttachFBOTexture1D(), R_AttachFBOTexture2D(), R_AttachFBOTexture3D(), R_BindNullFBO(), R_CopyToFBO(), R_CreateBloomRenderFBOImage(), R_CreateContrastRenderFBOImage(), R_CreateDownScaleFBOImages(), R_CreateFBO(), R_CreateFBOColorBuffer(), R_CreatePortalRenderImage(), R_CreateReadyFBO(), R_CreateRenderImage(), R_CreateShadowCubeFBOImage(), R_CreateShadowMapFBOImage(), R_DoGLimpShutdown(), R_FBOList_f(), R_InitFBOs(), R_LoadDDSImageData(), R_LoadLightmapsExternal(), R_LoadLights(), R_MDM_AddAnimSurfaces(), R_SetDefaultFBO(), R_SetupLightScissor(), R_ShutdownFBOs(), R_UploadCompressedImage2D(), R_UploadImage(), RB_CollectBspOcclusionQueries(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderDrawSurfaces(), RB_RenderEntityOcclusionQueries(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderViewFront(), and Render_lightVolume().
glstate_t glState
outside of TR since it shouldn't be cleared during ref re-init
Definition at line 42 of file tr_init.c.
const float mdmLODResolutions[MD3_MAX_LODS]
Definition at line 40 of file tr_model_mdm.c.
Referenced by AddSurfaceToVBOSurfacesListMDM(), and RB_CalcMDMLodIndex().
openGLToQuakeMatrix
Inverse of quakeToOpenGL matrix.
convert from our right handed coordinate system (looking down X) to D3D's left handed coordinate system (looking down Z)
Definition at line 58 of file tr_main.c.
const mat4_t quakeToD3DMatrix
Definition at line 71 of file tr_main.c.
Referenced by R_RotateForViewer().
quakeToOpenGLMatrix
Convert from our coordinate system (looking down X) to OpenGL's coordinate system (looking down -Z)
Definition at line 46 of file tr_main.c.
Referenced by R_CalcLightCubeSideBits(), R_RotateForViewer(), R_SetupUnprojection(), RB_RenderDebugUtils(), and RB_RenderInteractionsShadowMapped().
cvar_t* r_ambientScale
Definition at line 146 of file tr_init.c.
cvar_t* r_bloom
Definition at line 278 of file tr_init.c.
Referenced by RB_RenderBloom().
cvar_t* r_bloomBlur
Definition at line 279 of file tr_init.c.
Referenced by RB_RenderBloom().
cvar_t* r_bloomPasses
Definition at line 280 of file tr_init.c.
Referenced by RB_RenderBloom().
cvar_t* r_cameraFilmGrainScale
Definition at line 285 of file tr_init.c.
Referenced by RB_CameraPostFX().
cvar_t* r_cameraPostFX
Definition at line 283 of file tr_init.c.
Referenced by RB_CameraPostFX().
cvar_t* r_cameraVignette
Definition at line 284 of file tr_init.c.
Referenced by RB_CameraPostFX().
cvar_t* r_chcIgnoreLeaves
Definition at line 258 of file tr_init.c.
Referenced by R_CoherentHierachicalCulling().
cvar_t* r_chcMaxPrevInvisNodesBatchSize
Definition at line 255 of file tr_init.c.
Referenced by R_CoherentHierachicalCulling().
cvar_t* r_chcMaxVisibleFrames
Definition at line 256 of file tr_init.c.
Referenced by QueryReasonable(), R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and WasVisible().
cvar_t* r_chcVisibilityThreshold
Definition at line 257 of file tr_init.c.
Referenced by R_CoherentHierachicalCulling(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
cvar_t* r_collapseStages
Definition at line 157 of file tr_init.c.
Referenced by CollapseStages().
cvar_t* r_compressDiffuseMaps
Definition at line 91 of file tr_init.c.
Referenced by ParseDiffuseMap().
cvar_t* r_compressNormalMaps
Definition at line 93 of file tr_init.c.
Referenced by ParseNormalMap().
cvar_t* r_compressSpecularMaps
Definition at line 92 of file tr_init.c.
Referenced by ParseSpecularMap().
cvar_t* r_cullShadowPyramidCurves
Definition at line 144 of file tr_init.c.
cvar_t* r_cullShadowPyramidFaces
Definition at line 143 of file tr_init.c.
Referenced by R_LightSurfaceGeneric().
cvar_t* r_cullShadowPyramidTriangles
Definition at line 145 of file tr_init.c.
cvar_t* r_debugLight
Definition at line 148 of file tr_init.c.
cvar_t* r_debugShadowMaps
Definition at line 146 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_depthOfField
Definition at line 275 of file tr_init.c.
Referenced by RB_RenderDepthOfField().
cvar_t* r_diffuseLighting
Definition at line 176 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_drawpolies
disable/enable world rendering
Definition at line 76 of file tr_init.c.
Referenced by R_AddPolygonSurfaces(), R_AddPolysToScene(), and RE_AddPolyBufferToScene().
cvar_t* r_dynamicBspOcclusionCulling
Definition at line 252 of file tr_init.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), R_AddWorldSurface(), R_AddWorldSurfaces(), R_CoherentHierachicalCulling(), R_MarkLeaves(), R_SetupLightScissor(), RB_CollectBspOcclusionQueries(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), and RB_RenderViewFront().
cvar_t* r_dynamicEntityOcclusionCulling
Definition at line 253 of file tr_init.c.
Referenced by RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), and RB_RenderViewFront().
cvar_t* r_dynamicLightOcclusionCulling
Definition at line 254 of file tr_init.c.
Referenced by RB_RenderDebugUtils(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), and RB_RenderLightOcclusionQueries().
cvar_t* r_dynamicLightShadows
Definition at line 88 of file tr_init.c.
Referenced by RE_AddDynamicLightToScene(), and RE_AddRefEntityToScene().
cvar_t* r_evsmPostProcess
Definition at line 287 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef(), R_CreateShadowCubeFBOImage(), R_CreateShadowMapFBOImage(), R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
cvar_t* r_extDepthBoundsTest
Todo:
: unused, no extern.
Definition at line 109 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extDrawBuffers
Definition at line 101 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extFramebufferBlit
Definition at line 112 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extFramebufferObject
Definition at line 110 of file tr_init.c.
cvar_t* r_extGenerateMipmap
Todo:
: unused, no extern.
Definition at line 114 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extHalfFloatPixel
Definition at line 103 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extOcclusionQuery
Definition at line 99 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extPackedDepthStencil
Definition at line 111 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extStencilTwoSide
Definition at line 107 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extStencilWrap
Definition at line 105 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extTextureFloat
Definition at line 104 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extTextureNonPowerOfTwo
Definition at line 100 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_extVertexArrayObject
Definition at line 102 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_forceAmbient
Definition at line 200 of file tr_init.c.
Referenced by R_LoadEntities(), R_SetupEntityLighting(), and RE_LoadWorldMap().
cvar_t* r_hdrContrastOffset
Definition at line 265 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_hdrContrastThreshold
Definition at line 264 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_hdrDebug
Definition at line 272 of file tr_init.c.
Referenced by RB_CalculateAdaptation().
cvar_t* r_hdrGamma
Definition at line 271 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_hdrKey
Definition at line 263 of file tr_init.c.
Referenced by LoadRGBEToFloats(), and RB_CalculateAdaptation().
cvar_t* r_hdrLightmap
Definition at line 266 of file tr_init.c.
Referenced by R_LoadLightmapsExternal().
cvar_t* r_hdrLightmapCompensate
Definition at line 269 of file tr_init.c.
Referenced by LoadRGBEToFloats().
cvar_t* r_hdrLightmapExposure
Definition at line 267 of file tr_init.c.
Referenced by LoadRGBEToFloats().
cvar_t* r_hdrLightmapGamma
Definition at line 268 of file tr_init.c.
Referenced by LoadRGBEToFloats().
cvar_t* r_hdrMaxLuminance
Definition at line 262 of file tr_init.c.
Referenced by RB_CalculateAdaptation().
cvar_t* r_hdrMinLuminance
Definition at line 261 of file tr_init.c.
Referenced by RB_CalculateAdaptation().
cvar_t* r_hdrRendering
Definition at line 260 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef(), R_CreateBloomRenderFBOImage(), R_CreateContrastRenderFBOImage(), R_CreateDownScaleFBOImages(), R_CreatePortalRenderImage(), R_InitFBOs(), R_LoadLightmapsExternal(), R_LoadLights(), RB_RenderDepthOfField(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderViewFront(), and Render_lightVolume().
cvar_t* r_hdrToneMappingOperator
Definition at line 270 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_heatHazeFix
Definition at line 94 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_highQualityNormalMapping
Definition at line 277 of file tr_init.c.
Referenced by ParseNormalMap().
cvar_t* r_lightScale
Definition at line 202 of file tr_init.c.
Referenced by R_LoadLights(), RE_AddDynamicLightToScene(), RE_AddRefEntityToScene(), and resetRefLight().
cvar_t* r_lodTest
Definition at line 71 of file tr_init.c.
cvar_t* r_materialScan
Definition at line 296 of file tr_init.c.
cvar_t* r_noFog
Definition at line 198 of file tr_init.c.
Referenced by RB_RenderGlobalFog().
cvar_t* r_noInteractionSort
Definition at line 85 of file tr_init.c.
Referenced by R_SortInteractions().
cvar_t* r_noLightFrustums
Definition at line 148 of file tr_init.c.
Referenced by R_AddBrushModelInteractions(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), and R_LightSurfaceGeneric().
cvar_t* r_noLightScissors
Definition at line 83 of file tr_init.c.
Referenced by R_SetupLightScissor().
cvar_t* r_noLightVisCull
Definition at line 84 of file tr_init.c.
Referenced by R_AddLightBoundsToVisBounds(), and R_AddLightInteractions().
cvar_t* r_noMarksOnTrisurfs
Definition at line 95 of file tr_init.c.
Referenced by R_MarkFragments().
cvar_t* r_normalMapping
Definition at line 174 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef(), GLSL_GetRequiredVertexAttributes(), LoadMap(), R_FindShader(), and Tess_UpdateVBOs().
cvar_t* r_normalScale
Definition at line 173 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_noShadowFrustums
Definition at line 147 of file tr_init.c.
cvar_t* r_noShadowPyramids
Definition at line 142 of file tr_init.c.
Referenced by R_CalcLightCubeSideBits().
cvar_t* r_parallaxDepthScale
Definition at line 250 of file tr_init.c.
cvar_t* r_parallaxMapping
Definition at line 249 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_parallelShadowSplits
Definition at line 154 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef(), R_SetupSplitFrustums(), and RB_RenderInteractionsShadowMapped().
cvar_t* r_parallelShadowSplitWeight
Definition at line 155 of file tr_init.c.
Referenced by R_SetupSplitFrustums().
cvar_t* r_precomputedLighting
Definition at line 89 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef(), ParseFace(), ParseMesh(), ParseTriSurf(), R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), R_CreateSubModelVBOs(), R_CreateWorldVBO(), R_inPVS(), and R_PrecacheInteractions().
cvar_t* r_railCoreWidth
Definition at line 53 of file tr_init.c.
Referenced by Tess_SurfaceRailCore().
cvar_t* r_recompileShaders
Definition at line 96 of file tr_init.c.
Referenced by GLSL_CompileGPUShaders(), and GLSL_LoadShaderBinary().
cvar_t* r_reflectionMapping
Definition at line 276 of file tr_init.c.
Referenced by GL_BindNearestCubeMap(), and R_BuildCubeMaps().
cvar_t* r_rimExponent
Definition at line 178 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_rimLighting
Definition at line 177 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_rotoscope
Definition at line 281 of file tr_init.c.
Referenced by RB_RenderRotoscope().
cvar_t* r_rotoscopeBlur
Definition at line 282 of file tr_init.c.
Referenced by RB_RenderRotoscope().
cvar_t* r_screenSpaceAmbientOcclusion
Definition at line 274 of file tr_init.c.
Referenced by RB_RenderScreenSpaceAmbientOcclusion().
cvar_t* r_shadowBlur
Definition at line 123 of file tr_init.c.
cvar_t* r_shadowLodBias
Definition at line 140 of file tr_init.c.
Referenced by R_SetupLightLOD().
cvar_t* r_shadowLodScale
Definition at line 141 of file tr_init.c.
Referenced by R_SetupLightLOD().
cvar_t* r_shadowMapDepthScale
Definition at line 153 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_shadowMapLinearFilter
Definition at line 150 of file tr_init.c.
Referenced by R_CreateShadowCubeFBOImage(), and R_CreateShadowMapFBOImage().
cvar_t* r_shadowMapLuminanceAlpha
Definition at line 149 of file tr_init.c.
cvar_t* r_shadowMapQuality
Definition at line 125 of file tr_init.c.
cvar_t* r_shadowMapSizeHigh
Definition at line 128 of file tr_init.c.
cvar_t* r_shadowMapSizeLow
Definition at line 130 of file tr_init.c.
cvar_t* r_shadowMapSizeMedium
Definition at line 129 of file tr_init.c.
cvar_t* r_shadowMapSizeSunHigh
Definition at line 134 of file tr_init.c.
cvar_t* r_shadowMapSizeSunLow
Definition at line 136 of file tr_init.c.
cvar_t* r_shadowMapSizeSunMedium
Definition at line 135 of file tr_init.c.
cvar_t* r_shadowMapSizeSunUltra
Definition at line 132 of file tr_init.c.
cvar_t* r_shadowMapSizeSunVeryHigh
Definition at line 133 of file tr_init.c.
cvar_t* r_shadowMapSizeUltra
Definition at line 126 of file tr_init.c.
cvar_t* r_shadowMapSizeVeryHigh
Definition at line 127 of file tr_init.c.
cvar_t* r_shadowOffsetFactor
Definition at line 138 of file tr_init.c.
cvar_t* r_shadowOffsetUnits
Definition at line 139 of file tr_init.c.
cvar_t* r_showBatches
Definition at line 224 of file tr_init.c.
Referenced by DrawTris().
cvar_t* r_showBspNodes
Definition at line 228 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showCubeProbes
Definition at line 227 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showDecalProjectors
Definition at line 230 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showEntityTransforms
Definition at line 217 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showLightBatches
Definition at line 221 of file tr_init.c.
Referenced by DrawTris().
cvar_t* r_showLightGrid
Definition at line 222 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showLightInteractions
Definition at line 219 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showLightMaps
render lightmaps only
Definition at line 225 of file tr_init.c.
Referenced by R_ProcessLightmap().
cvar_t* r_showLightScissors
Definition at line 220 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showLightTransforms
Definition at line 218 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showOcclusionQueries
Definition at line 223 of file tr_init.c.
Referenced by RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
cvar_t* r_showParallelShadowSplits
Definition at line 229 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_showShadowLod
Definition at line 214 of file tr_init.c.
Referenced by RB_RenderDebugUtils().
cvar_t* r_showShadowMaps
Definition at line 215 of file tr_init.c.
Referenced by RB_RenderInteractionsShadowMapped().
cvar_t* r_showShadowVolumes
Definition at line 213 of file tr_init.c.
cvar_t* r_showSkeleton
Definition at line 216 of file tr_init.c.
Referenced by R_CalcBones(), RB_RenderDebugUtils(), and Tess_MDM_SurfaceAnim().
cvar_t* r_skipLightBuffer
Definition at line 62 of file tr_init.c.
cvar_t* r_smoothNormals
Definition at line 298 of file tr_init.c.
Referenced by MakeMeshTangentVectors(), ParseTriSurf(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), and R_MDC_CreateVBO_Surfaces().
cvar_t* r_softShadows
Definition at line 122 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_specularExponent
Definition at line 170 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_specularExponent2
Definition at line 171 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_specularScale
Definition at line 172 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
cvar_t* r_staticLight
static lights enabled/disabled
Definition at line 87 of file tr_init.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), and R_PrecacheInteractions().
cvar_t* r_stitchCurves
Definition at line 187 of file tr_init.c.
Referenced by R_CreateSurfaceGridMesh(), and R_LoadSurfaces().
cvar_t* r_vboCurves
Definition at line 233 of file tr_init.c.
Referenced by Tess_SurfaceGrid().
cvar_t* r_vboFaces
Definition at line 232 of file tr_init.c.
Referenced by Tess_SurfaceFace().
cvar_t* r_vboFoliage
Definition at line 240 of file tr_init.c.
Referenced by Tess_SurfaceFoliage().
cvar_t* r_vboLighting
Definition at line 236 of file tr_init.c.
Referenced by R_AddPrecachedWorldInteractions(), and R_CreateVBOLightMeshes().
cvar_t* r_vboModels
Definition at line 237 of file tr_init.c.
Referenced by R_AddBrushModelInteractions(), R_AddBSPModelSurfaces(), R_AddMD5Interactions(), R_AddMD5Surfaces(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_AddMDVSurfaces(), and R_MDM_AddAnimSurfaces().
cvar_t* r_vboShadows
Definition at line 235 of file tr_init.c.
Referenced by R_AddPrecachedWorldInteractions(), R_CreateVBOShadowCubeMeshes(), and R_CreateVBOShadowMeshes().
cvar_t* r_vboSmoothNormals
Definition at line 239 of file tr_init.c.
cvar_t* r_vboTriangles
Definition at line 234 of file tr_init.c.
Referenced by Tess_SurfaceTriangles().
cvar_t* r_vboVertexSkinning
Definition at line 238 of file tr_init.c.
Referenced by GLimp_InitExtensionsR2().
cvar_t* r_vertexLighting
Definition at line 90 of file tr_init.c.
Referenced by ParseFace(), ParseMesh(), ParseTriSurf(), R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), R_CreateWorldVBO(), and R_PrecacheInteractions().
cvar_t* r_wolfFog
Definition at line 161 of file tr_init.c.
cvar_t* r_worldInlineModels
Definition at line 241 of file tr_init.c.
cvar_t* r_wrapAroundLighting
Definition at line 175 of file tr_init.c.
Referenced by GLSL_BuildShaderExtraDef().
void(* rb_surfaceTable[SF_NUM_SURFACE_TYPES])(void *)
Definition at line 1951 of file tr_surface.c.
refimport_t ri
Definition at line 50 of file tr_main.c.
int shadowMapResolutions[5]
Definition at line 95 of file tr_main.c.
Referenced by R_CreateShadowCubeFBOImage(), R_CreateShadowMapFBOImage(), R_InitFBOs(), R_Register(), and RB_RenderInteractionsShadowMapped().
shadowState_t shadowState
Definition at line 38 of file tr_shadows.c.
int sunShadowMapResolutions[5]
Definition at line 96 of file tr_main.c.
Referenced by R_CreateShadowMapFBOImage(), R_InitFBOs(), R_Register(), and RB_RenderInteractionsShadowMapped().
shaderCommands_t tess
Definition at line 217 of file tr_shade.c.
trGlobals_t tr
Definition at line 38 of file tr_main.c.
trPrograms_t trProg
Definition at line 135 of file tr_glsl.c.
Referenced by DrawTris(), R_CoherentHierachicalCulling(), RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_ShowImages(), RE_StretchRaw(), Render_lightVolume(), and Tess_StageIteratorSky().