ET: Legacy: src/renderer2/tr_shade.c File Reference
tr_shade.c File Reference
THIS ENTIRE FILE IS BACK END! This file deals with applying shaders to surface data in the tess struct.
#include "tr_local.h"
Data Structures
struct rgbaGen_s
Typedefs
typedef struct rgbaGen_s rgbaGen_t
Functions
void Tess_DrawElements ()
Tess_DrawElements.
static void BindLightMap ()
BindLightMap.
static void BindCubeMaps ()
BindDeluxeMap unused static void BindDeluxeMap(shaderStage_t *pStage) { image_t *deluxemap;.
bspGridPoint_t * LightgridColor (const vec3_t position)
static void BindTexture (image_t *image, image_t *defaultImage)
Binds a texture or the given default if image is NULL This is basically used to ensure a texture for GL_Bind.
static void DrawTris ()
Draws triangle outlines for debugging.
void Tess_Begin (void(*stageIteratorFunc)(), void(*stageIteratorFunc2)(), shader_t *surfaceShader, shader_t *lightShader, qboolean skipTangentSpaces, qboolean skipVBO, int lightmapNum, int fogNum)
We must set some things up before beginning any tesselation, because a surface may be forced to perform a Tess_End due to overflow.
void clipPortalPlane ()
clipping portal plane in world space
void SetLightUniforms (qboolean setLightColor)
static void Render_generic (int stage)
Render_generic.
static void Render_vertexLighting_DBS_entity (int stage)
Render_vertexLighting_DBS_entity.
static void Render_vertexLighting_DBS_world (int stage)
Render_vertexLighting_DBS_world.
static void Render_lightMapping (int stage, qboolean asColorMap, qboolean normalMapping)
Render_lightMapping.
static void Render_shadowFill (int stage)
Render_depthFill.
static void Render_forwardLighting_DBS_omni (shaderStage_t *diffuseStage, shaderStage_t *attenuationXYStage, shaderStage_t *attenuationZStage, trRefLight_t *light)
Render_forwardLighting_DBS_omni.
static void Render_forwardLighting_DBS_proj (shaderStage_t *diffuseStage, shaderStage_t *attenuationXYStage, shaderStage_t *attenuationZStage, trRefLight_t *light)
Render_forwardLighting_DBS_proj.
static void Render_forwardLighting_DBS_directional (shaderStage_t *diffuseStage, shaderStage_t *attenuationXYStage, shaderStage_t *attenuationZStage, trRefLight_t *light)
Render_forwardLighting_DBS_directional.
static void Render_reflection_CB (int stage)
Render_reflection_CB.
static void Render_refraction_C (int stage)
Render_refraction_C.
static void Render_dispersion_C (int stage)
Render_dispersion_C.
static void Render_skybox (int stage)
Render_skybox.
static void Render_screen (int stage)
Render_screen.
static void Render_portal (int stage)
Render_portal.
static void Render_heatHaze (int stage)
Render_heatHaze.
static void Render_liquid (int stage)
Render_liquid.
static void Render_fog_brushes ()
Render_fog_brushes - used to render fog brushes (not the fog)
static void Render_volumetricFog ()
Render_volumetricFog.
void Tess_ComputeColor (shaderStage_t *pStage)
Tess_ComputeColor.
static void Tess_ComputeTexMatrices (shaderStage_t *pStage)
Tess_ComputeTexMatrices.
static void SetIteratorFog ()
Set the fog parameters for this pass.
void Tess_StageIteratorDebug ()
Tess_StageIteratorDebug.
static ID_INLINE GLenum RB_StencilOp (int op)
RB_StencilOp.
static void RB_SetStencil (GLenum side, stencil_t *stencil)
RB_SetStencil.
void Tess_StageIteratorGeneric ()
Tess_StageIteratorGeneric.
void Tess_StageIteratorShadowFill ()
Tess_StageIteratorDepthFill.
void Tess_StageIteratorLighting ()
Tess_StageIteratorLighting.
void Tess_End ()
Render tesselated data.
Variables
shaderCommands_t tess
Detailed Description
THIS ENTIRE FILE IS BACK END! This file deals with applying shaders to surface data in the tess struct.
Definition in file tr_shade.c.
Typedef Documentation
typedef struct rgbaGen_s rgbaGen_t
Function Documentation
static void BindCubeMaps () static
BindDeluxeMap unused static void BindDeluxeMap(shaderStage_t *pStage) { image_t *deluxemap;.
if (tess.lightmapNum >= 0 && tess.lightmapNum < tr.deluxemaps.currentElements) { deluxemap = (image_t *) Com_GrowListElement(&tr.deluxemaps, tess.lightmapNum); } else { deluxemap = NULL; }
if (!tr.deluxemaps.currentElements || !deluxemap) { hack: use TB_NORMALMAP image when r_normalMapping is enabled and there is no deluxe map available if (r_normalMapping->integer && !tr.worldDeluxeMapping && pStage->bundle[TB_NORMALMAP].image[0] != NULL) { GL_Bind(pStage->bundle[TB_NORMALMAP].image[0]); } else { GL_Bind(tr.flatImage); } return; }
GL_Bind(deluxemap); } BindCubeMaps
Definition at line 183 of file tr_shade.c.
static void BindLightMap () static
BindLightMap.
Definition at line 127 of file tr_shade.c.
static void BindTexture (image_t * image, image_t * defaultImage) static
Binds a texture or the given default if image is NULL This is basically used to ensure a texture for GL_Bind.
Parameters
[in]
Definition at line 268 of file tr_shade.c.
void clipPortalPlane ()
clipping portal plane in world space
Definition at line 453 of file tr_shade.c.
Referenced by Tess_StageIteratorSky().
static void DrawTris () static
Draws triangle outlines for debugging.
Definition at line 280 of file tr_shade.c.
bspGridPoint_t* LightgridColor (const vec3_t position)
Definition at line 225 of file tr_shade.c.
static void RB_SetStencil (GLenum side, stencil_t * stencil) static
RB_SetStencil.
Parameters
[in] side
[in] stencil
Definition at line 3043 of file tr_shade.c.
static ID_INLINE GLenum RB_StencilOp (int op) static
RB_StencilOp.
Parameters
[in] op
Returns
Definition at line 3017 of file tr_shade.c.
static void Render_dispersion_C (int stage) static
Render_dispersion_C.
Parameters
[in] stage
Definition at line 1812 of file tr_shade.c.
static void Render_fog_brushes () static
Render_fog_brushes - used to render fog brushes (not the fog)
Note
This is required for any 'global' fog (see RB_RenderGlobalFog) If the brush limit (see comment below) is deactivated it will also render the 'volumetric' part of r_wolffog In other words:
gl_fogQuake3Shader does the r_wolffog fog 'wall' and fog brushes
gl_fogGlobalShader does the global volumetric fog (with static density see st.t = 0.6; in glsl)
Why this mix is done? Currently it's the best solution until we've figured out which old fog code (and cvar r_wolffog) to drop The old transition between volumetric fog and fog 'wall' was always looking bad gl_fogGlobalShader has got a more fluent transition which is looking much better and there is no real need for the fog 'wall'. It's recommended to disable r_wolffog - it just doing the ugly wall
side note: gl_volumetricFogShader might do the job for gl_fogGlobalShader
Sort out the trouble
Definition at line 2317 of file tr_shade.c.
static void Render_forwardLighting_DBS_directional (shaderStage_t * diffuseStage, shaderStage_t * attenuationXYStage, shaderStage_t * attenuationZStage, trRefLight_t * light) static
Render_forwardLighting_DBS_directional.
Parameters
[in] diffuseStage
attenuationXYStage - unused
attenuationZStage - unused
[in] light
Definition at line 1524 of file tr_shade.c.
static void Render_forwardLighting_DBS_omni (shaderStage_t * diffuseStage, shaderStage_t * attenuationXYStage, shaderStage_t * attenuationZStage, trRefLight_t * light) static
Render_forwardLighting_DBS_omni.
Parameters
[in] diffuseStage
[in] attenuationXYStage
[in] attenuationZStage
[in] light
Todo:
: don't bind testures for r_DebugShadowMaps
Definition at line 1206 of file tr_shade.c.
static void Render_forwardLighting_DBS_proj (shaderStage_t * diffuseStage, shaderStage_t * attenuationXYStage, shaderStage_t * attenuationZStage, trRefLight_t * light) static
Render_forwardLighting_DBS_proj.
Parameters
[in] diffuseStage
[in] attenuationXYStage
[in] attenuationZStage
[in] light
Definition at line 1367 of file tr_shade.c.
static void Render_generic (int stage) static
Render_generic.
Parameters
[in] stage
Definition at line 559 of file tr_shade.c.
static void Render_heatHaze (int stage) static
Render_heatHaze.
Parameters
[in] stage
Definition at line 1974 of file tr_shade.c.
static void Render_lightMapping (int stage, qboolean asColorMap, qboolean normalMapping) static
Render_lightMapping.
Parameters
[in] stage
[in] asColorMap
[in] normalMapping
Todo:
: and when surface has something environment mappy assigned..
Definition at line 887 of file tr_shade.c.
static void Render_liquid (int stage) static
Render_liquid.
Parameters
[in] stage
Definition at line 2163 of file tr_shade.c.
static void Render_portal (int stage) static
Render_portal.
Parameters
[in] stage
Definition at line 1934 of file tr_shade.c.
static void Render_reflection_CB (int stage) static
Render_reflection_CB.
Parameters
[in] stage
Definition at line 1698 of file tr_shade.c.
static void Render_refraction_C (int stage) static
Render_refraction_C.
Parameters
[in] stage
Definition at line 1772 of file tr_shade.c.
static void Render_screen (int stage) static
Render_screen.
Parameters
[in] stage
Definition at line 1897 of file tr_shade.c.
static void Render_shadowFill (int stage) static
Render_depthFill.
Parameters
[in] stage unused static void Render_depthFill(int stage) { shaderStage_t *pStage = tess.surfaceStages[stage]; vec4_t ambientColor; rgbaGen_t rgbaGen;
Ren_LogComment("--- Render_depthFill ---\n");
rgbaGen = getRgbaGenForColorModulation(pStage, tess.lightmapNum);
GL_State(pStage->stateBits);
SetMacrosAndSelectProgram(trProg.gl_genericShader, USE_ALPHA_TESTING, (pStage->stateBits & GLS_ATEST_BITS) != 0, USE_PORTAL_CLIPPING, backEnd.viewParms.isPortal, USE_VERTEX_SKINNING, glConfig2.vboVertexSkinningAvailable && tess.vboVertexSkinning, USE_VERTEX_ANIMATION, glState.vertexAttribsInterpolation > 0, USE_DEFORM_VERTEXES, tess.surfaceShader->numDeforms, USE_TCGEN_ENVIRONMENT, pStage->tcGen_Environment);
set uniforms
if (pStage->tcGen_Environment)
{
calculate the environment texcoords in object space SetUniformVec3(UNIFORM_VIEWORIGIN, backEnd.viewParms.orientation.viewOrigin); }
GLSL_SetUniform_AlphaTest(pStage->stateBits); GLSL_SetUniform_ColorModulate(trProg.gl_genericShader, rgbaGen.color, rgbaGen.alpha);
u_Color if (r_precomputedLighting->integer) { VectorCopy(backEnd.currentEntity->ambientLight, ambientColor); ClampColor(ambientColor); } else if (r_forceAmbient->integer) { ambientColor[0] = r_forceAmbient->value; ambientColor[1] = r_forceAmbient->value; ambientColor[2] = r_forceAmbient->value; } else { VectorClear(ambientColor); } ambientColor[3] = 1;
/
Todo:
? see u_AmbientColor in depthFill glsl SetUniformVec4(UNIFORM_COLOR, ambientColor); SetUniformVec3(UNIFORM_AMBIENTCOLOR, backEnd.currentEntity->ambientLight);
SetUniformMatrix16(UNIFORM_MODELMATRIX, backEnd.orientation.transformMatrix);
SetUniformMatrix16(UNIFORM_MODELVIEWPROJECTIONMATRIX, GLSTACK_MVPM);
if (glConfig2.vboVertexSkinningAvailable && tess.vboVertexSkinning)
{
    SetUniformMatrix16ARR(UNIFORM_BONEMATRIX, tess.boneMatrices, MAX_BONES);
}
u_DeformGen if (tess.surfaceShader->numDeforms) { GLSL_SetUniform_DeformParms(tess.surfaceShader->deforms, tess.surfaceShader->numDeforms); SetUniformFloat(UNIFORM_TIME, tess.shaderTime); }
if (backEnd.viewParms.isPortal) { clipPortalPlane(); }
bind u_ColorMap SelectTexture(TEX_COLOR); if (tess.surfaceShader->alphaTest) { GL_Bind(pStage->bundle[TB_DIFFUSEMAP].image[0]); SetUniformMatrix16(UNIFORM_COLORTEXTUREMATRIX, tess.svars.texMatrices[TB_DIFFUSEMAP]); } else { GL_Bind(tr.defaultImage); GL_Bind(pStage->bundle[TB_DIFFUSEMAP].image[0]); SetUniformMatrix16(UNIFORM_COLORTEXTUREMATRIX, matrixIdentity); }
GLSL_SetRequiredVertexPointers(trProg.gl_genericShader);
Tess_DrawElements();
GL_CheckErrors(); } Render_shadowFill
Parameters
[in] stage
Definition at line 1118 of file tr_shade.c.
static void Render_skybox (int stage) static
Render_skybox.
Parameters
[in] stage
Definition at line 1862 of file tr_shade.c.
static void Render_vertexLighting_DBS_entity (int stage) static
Render_vertexLighting_DBS_entity.
Parameters
[in] stage
Todo:
: && when surface has NOT assigned tcGen environment (because that will execute a reflection_cb stage).
Definition at line 636 of file tr_shade.c.
static void Render_vertexLighting_DBS_world (int stage) static
Render_vertexLighting_DBS_world.
Parameters
[in] stage
Definition at line 776 of file tr_shade.c.
static void Render_volumetricFog () static
Render_volumetricFog.
Note
see Fog Polygon Volumes documentation by Nvidia for further information
Definition at line 2471 of file tr_shade.c.
static void SetIteratorFog (void) static
Set the fog parameters for this pass.
Definition at line 2945 of file tr_shade.c.
void SetLightUniforms (qboolean setLightColor)
Definition at line 541 of file tr_shade.c.
void Tess_Begin (void(*)() stageIteratorFunc, void(*)() stageIteratorFunc2, shader_t * surfaceShader, shader_t * lightShader, qboolean skipTangentSpaces, qboolean skipVBO, int lightmapNum, int fogNum)
We must set some things up before beginning any tesselation, because a surface may be forced to perform a Tess_End due to overflow.
Parameters
stageIteratorFunc
stageIteratorFunc2
[in] surfaceShader
[in] lightShader
[in] skipTangentSpaces
[in] skipVBO
[in] lightmapNum
[in] fogNum
Definition at line 369 of file tr_shade.c.
Referenced by RB_Draw2dPolys(), RB_DrawSun(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderFlare(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), SurfIsOffscreen(), Tess_CheckOverflow(), and Tess_EndBegin().
void Tess_ComputeColor (shaderStage_t * pStage)
Tess_ComputeColor.
Parameters
[in] pStage
Todo:
Todo:
?
Todo:
?
Todo:
: rework/move to GL
Definition at line 2568 of file tr_shade.c.
Referenced by Render_lightVolume().
static void Tess_ComputeTexMatrices (shaderStage_t * pStage) static
Tess_ComputeTexMatrices.
Parameters
[in] pStage
Definition at line 2920 of file tr_shade.c.
void Tess_DrawElements ()
Tess_DrawElements.
Definition at line 65 of file tr_shade.c.
Referenced by DrawSkyBox(), DrawTris(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RE_StretchRaw(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_InstantQuad(), and TraverseNode().
void Tess_End (void)
Render tesselated data.
Definition at line 3667 of file tr_shade.c.
Referenced by RB_Draw2dPolys(), RB_DrawSun(), RB_DrawView(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderFlare(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), RB_SwapBuffers(), Tess_CheckOverflow(), Tess_EndBegin(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), and Tess_SurfaceVBOMesh().
void Tess_StageIteratorDebug ()
Tess_StageIteratorDebug.
Definition at line 2998 of file tr_shade.c.
Referenced by RB_RenderDebugUtils().
void Tess_StageIteratorGeneric ()
Tess_StageIteratorGeneric.
Todo:
: remove r_worldInlineModels?
Definition at line 3097 of file tr_shade.c.
Referenced by RB_Draw2dPolys(), RB_DrawSun(), RB_RenderDrawSurfaces(), RB_RenderFlare(), RB_RotatedPic(), RB_StretchPic(), RB_StretchPicGradient(), SurfIsOffscreen(), Tess_Begin(), and Tess_StageIteratorSky().
void Tess_StageIteratorLighting ()
Tess_StageIteratorLighting.
Definition at line 3511 of file tr_shade.c.
Referenced by RB_RenderInteractions(), and RB_RenderInteractionsShadowMapped().
void Tess_StageIteratorShadowFill ()
Tess_StageIteratorDepthFill.
Note
Unused void Tess_StageIteratorDepthFill() { int stage;
Ren_LogComment("--- Tess_StageIteratorDepthFill(%s, %i vertices, %i triangles) ---\n", tess.surfaceShader->name, tess.numVertexes, tess.numIndexes / 3);
GL_CheckErrors();
Tess_DeformGeometry();
if (!glState.currentVBO || !glState.currentIBO || glState.currentVBO == tess.vbo || glState.currentIBO == tess.ibo) { Tess_UpdateVBOs(tess.attribsSet); }
set face culling appropriately GL_Cull(tess.surfaceShader->cullType);
set polygon offset if necessary if (tess.surfaceShader->polygonOffset) { glEnable(GL_POLYGON_OFFSET_FILL); GL_PolygonOffset(r_offsetFactor->value, r_offsetUnits->value); }
call shader function for (stage = 0; stage < MAX_SHADER_STAGES; stage++) { shaderStage_t *pStage = tess.surfaceStages[stage];
if (!pStage) { break; }
if (RB_EvalExpression(&pStage->ifExp, 1.0f) == 0.f) { continue; }
Tess_ComputeTexMatrices(pStage);
switch (pStage->type) { case ST_COLORMAP: { if (tess.surfaceShader->sort <= SS_OPAQUE) { Render_depthFill(stage); } break; } case ST_LIGHTMAP: { Render_depthFill(stage); break; } case ST_DIFFUSEMAP: case ST_COLLAPSE_lighting_DB: case ST_COLLAPSE_lighting_DBS: { Render_depthFill(stage); break; } default: break; } }
reset polygon offset glDisable(GL_POLYGON_OFFSET_FILL); } Tess_StageIteratorShadowFill
Definition at line 3436 of file tr_shade.c.
Referenced by RB_RenderInteractionsShadowMapped().
Variable Documentation
shaderCommands_t tess
Definition at line 122 of file tr_shade.c.