ET: Legacy: src/renderer2/tr_image.c File Reference
tr_image.c File Reference
#include "tr_local.h"
Data Structures
struct textureMode_t
struct imageExtToLoaderMap_t
Macros
#define IMAGE_FILE_HASH_SIZE 4096
#define generateHashValue(fname) Q_GenerateHashValue(fname, IMAGE_FILE_HASH_SIZE, qtrue, qtrue)
#define FOG_S 256
#define FOG_T 32
#define DEFAULT_SIZE 128
#define ATTENUATION_XY_SIZE 128
Functions
void R_GammaCorrect (byte *buffer, int bufSize)
R_GammaCorrect.
void GL_TextureMode (const char *string)
GL_TextureMode.
int R_SumOfUsedImages (void)
R_SumOfUsedImages.
void R_ImageList_f (void)
R_ImageList_f.
static void R_ResampleTexture (unsigned *in, int inwidth, int inheight, unsigned *out, int outwidth, int outheight, qboolean normalMap)
Used to resample images in a more general than quartering fashion.
void R_LightScaleTexture (unsigned *in, int inwidth, int inheight, qboolean onlyGamma)
Scale up the pixel values in a texture to increase the lighting range.
static void R_MipMap2 (unsigned *in, int inWidth, int inHeight)
Operates in place, quartering the size of the texture Proper linear filter.
static void R_MipMap (byte *in, int width, int height)
Operates in place, quartering the size of the texture.
static void R_MipNormalMap (byte *in, int width, int height)
Operates in place, quartering the size of the texture.
static void R_HeightMapToNormalMap (byte *in, int width, int height, float scale)
R_HeightMapToNormalMap.
static void R_DisplaceMap (byte *in, byte *in2, int width, int height)
R_DisplaceMap.
static void R_AddNormals (byte *in, byte *in2, int width, int height)
R_AddNormals.
static void R_InvertAlpha (byte *in, int width, int height)
R_InvertAlpha.
static void R_InvertColor (byte *in, int width, int height)
R_InvertColor.
static void R_MakeIntensity (byte *in, int width, int height)
R_MakeIntensity.
static void R_MakeAlpha (byte *in, int width, int height)
R_MakeAlpha.
static void R_BlendOverTexture (byte *data, int pixelCount, byte blend[4])
Apply a color blend over a set of pixels.
void R_UploadImage (const byte **dataArray, int numData, image_t *image)
R_UploadImage.
image_t * R_AllocImage (const char *name, qboolean linkIntoHashTable)
R_AllocImage.
image_t * R_CreateImage (const char *name, const byte *pic, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateImage.
image_t * R_CreateCubeImage (const char *name, const byte *pic[6], int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateCubeImage.
static void R_LoadImage (char **buffer, byte **pic, int *width, int *height, int *bits, const char *materialName)
Loads any of the supported image types into a canonical 32 bit format.
static qboolean ParseHeightMap (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseHeightMap.
static qboolean ParseDisplaceMap (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseDisplaceMap.
static qboolean ParseAddNormals (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseAddNormals.
static qboolean ParseInvertAlpha (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseInvertAlpha.
static qboolean ParseInvertColor (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseInvertColor.
static qboolean ParseMakeIntensity (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseMakeIntensity.
static qboolean ParseMakeAlpha (char **text, byte **pic, int *width, int *height, int *bits, const char *materialName)
ParseMakeAlpha.
void * R_GetImageBuffer (int size, bufferMemType_t bufferType, const char *filename)
This is a hack to get the common imageloaders working properly.
void R_ImageCopyBack (image_t *image, int x, int y, int width, int height)
R_ImageCopyBack.
image_t * R_FindImageFile (const char *imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char *materialName)
Finds or loads the given image.
static ID_INLINE void R_SwapPixel (byte *inout, int x, int y, int x2, int y2, int width, int height)
R_SwapPixel.
static void R_Flip (byte *in, int width, int height)
R_Flip.
static void R_Flop (byte *in, int width, int height)
R_Flop.
static void R_Rotate (byte *in, int width, int height, int degrees)
R_Rotate.
void R_SubImageCpy (byte *dest, size_t destx, size_t desty, size_t destw, size_t desth, byte *src, size_t srcw, size_t srch, size_t bytes, qboolean in)
Copies between a smaller image and a larger image. Last flag controls is copy in or out of larger image.
image_t * R_FindCubeImage (const char *imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char *materialName)
Finds or loads the given image.
void R_InitFogTable (void)
R_InitFogTable.
float R_FogFactor (float s, float t)
This is called for each texel of the fog texture on startup and for each vertex of transparent shaders in fog dynamically.
static void R_CreateFogImage (void)
R_CreateFogImage.
static void R_CreateDefaultImage (void)
R_CreateDefaultImage.
static void R_CreateNoFalloffImage (void)
R_CreateRandomNormalsImage unused - see randomNormalsImage static void R_CreateRandomNormalsImage(void) { int x, y; byte data[DEFAULT_SIZE][DEFAULT_SIZE][4];.
static void R_CreateAttenuationXYImage (void)
R_CreateAttenuationXYImage.
image_t * R_CreateCubeRenderImage (const char *name, int color, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateCubeRenderImage.
image_t * R_CreateRenderImageSize (const char *name, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateRenderImageSize.
image_t * R_CreateRenderImage (const char *name, qboolean quat, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateRenderImage.
static void R_CreateContrastRenderFBOImage (void)
R_CreateContrastRenderFBOImage.
static void R_CreateBloomRenderFBOImage (void)
R_CreateBloomRenderFBOImage.
static void R_CreateCurrentRenderImage (void)
R_CreateCurrentRenderImage.
static void R_CreateDepthRenderImage (void)
R_CreateDepthRenderImage.
static void R_CreatePortalRenderImage (void)
R_CreatePortalRenderImage.
static void R_CreateOcclusionRenderFBOImage (void)
R_CreateOcclusionRenderFBOImage.
static void R_CreateDepthToColorFBOImages (void)
R_CreateDepthToColorFBOImages.
static void R_CreateDownScaleFBOImages (void)
R_CreateDownScaleFBOImages.
static void R_CreateDeferredRenderFBOImages (void)
R_CreateDeferredRenderFBOImages.
static void R_CreateShadowMapFBOImage (void)
R_CreateShadowMapFBOImage.
static void R_CreateShadowCubeFBOImage (void)
R_CreateShadowCubeFBOImage.
static void R_CreateColorCubeImages (void)
R_CreateColorCubeImages.
void R_CreateBuiltinImages (void)
R_CreateBuiltinImages.
void R_SetColorMappings (void)
R_SetColorMappings.
void R_InitImages (void)
R_InitImages.
void R_ShutdownImages (void)
R_ShutdownImages.
int RE_GetTextureId (const char *name)
RE_GetTextureId.
Variables
static byte s_intensitytable [256]
static unsigned char s_gammatable [256]
int gl_filter_min = GL_LINEAR_MIPMAP_NEAREST
int gl_filter_max = GL_LINEAR
image_t * r_imageHashTable [IMAGE_FILE_HASH_SIZE]
textureMode_t modes []
byte mipBlendColors [16][4]
static imageExtToLoaderMap_t imageLoaders []
Note that the ordering indicates the order of preference used when there are multiple images of different formats available.
static int numImageLoaders = sizeof(imageLoaders) / sizeof(imageLoaders[0])
Macro Definition Documentation
#define ATTENUATION_XY_SIZE 128
Definition at line 2967 of file tr_image.c.
Referenced by R_CreateAttenuationXYImage().
#define DEFAULT_SIZE 128
Definition at line 2879 of file tr_image.c.
Referenced by R_CreateBuiltinImages(), R_CreateDefaultImage(), and R_CreateNoFalloffImage().
#define FOG_S 256
Definition at line 2846 of file tr_image.c.
Referenced by R_CreateFogImage().
#define FOG_T 32
Definition at line 2847 of file tr_image.c.
Referenced by R_CreateFogImage().
#define generateHashValue (fname) Q_GenerateHashValue(fname, IMAGE_FILE_HASH_SIZE, qtrue, qtrue)
Todo:
: check if this fullpath shit is really needed for anything
Definition at line 48 of file tr_image.c.
Referenced by R_AllocImage(), R_FindCubeImage(), and R_FindImageFile().
#define IMAGE_FILE_HASH_SIZE 4096
Definition at line 44 of file tr_image.c.
Function Documentation
void GL_TextureMode (const char * string)
GL_TextureMode.
Parameters
[in] string
Definition at line 89 of file tr_image.c.
static qboolean ParseAddNormals (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseAddNormals.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[out] bits
[in] materialName
Returns
Definition at line 1702 of file tr_image.c.
Referenced by R_LoadImage().
static qboolean ParseDisplaceMap (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseDisplaceMap.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[out] bits
[in] materialName
Returns
Definition at line 1633 of file tr_image.c.
Referenced by R_LoadImage().
static qboolean ParseHeightMap (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseHeightMap.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[in,out] bits
[in] materialName
Returns
Definition at line 1579 of file tr_image.c.
Referenced by R_LoadImage().
static qboolean ParseInvertAlpha (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseInvertAlpha.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[out] bits
[in] materialName
Returns
Definition at line 1771 of file tr_image.c.
Referenced by R_LoadImage().
static qboolean ParseInvertColor (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseInvertColor.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[out] bits
[in] materialName
Returns
Definition at line 1811 of file tr_image.c.
Referenced by R_LoadImage().
static qboolean ParseMakeAlpha (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseMakeAlpha.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[out] bits
[in] materialName
Returns
Definition at line 1894 of file tr_image.c.
Referenced by R_LoadImage().
static qboolean ParseMakeIntensity (char ** text, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
ParseMakeIntensity.
Parameters
[in,out] text
[out] pic
[out] width
[out] height
[out] bits
[in] materialName
Returns
Definition at line 1851 of file tr_image.c.
Referenced by R_LoadImage().
static void R_AddNormals (byte * in, byte * in2, int width, int height) static
R_AddNormals.
Parameters
[in,out] in
[in] in2
[in] width
[in] height
Definition at line 819 of file tr_image.c.
Referenced by ParseAddNormals().
image_t* R_AllocImage (const char * name, qboolean linkIntoHashTable)
R_AllocImage.
Parameters
[in] name
[in] linkIntoHashTable
Returns
Definition at line 1451 of file tr_image.c.
Referenced by R_BuildCubeMaps(), R_CreateCubeImage(), R_CreateImage(), R_LoadDDSImageData(), and R_LoadLightmapsExternal().
static void R_BlendOverTexture (byte * data, int pixelCount, byte blend[4]) static
Apply a color blend over a set of pixels.
Parameters
[in,out] data
[in] pixelCount
[in] blend
Definition at line 961 of file tr_image.c.
Referenced by R_UploadImage().
static void R_CreateAttenuationXYImage (void) static
R_CreateAttenuationXYImage.
Definition at line 2972 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateBloomRenderFBOImage (void) static
R_CreateBloomRenderFBOImage.
Definition at line 3123 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
void R_CreateBuiltinImages (void)
R_CreateBuiltinImages.
Todo:
: we need a fake one for this as a specular, specular shouldnt be zero
Definition at line 3421 of file tr_image.c.
static void R_CreateColorCubeImages (void) static
R_CreateColorCubeImages.
Definition at line 3411 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateContrastRenderFBOImage (void) static
R_CreateContrastRenderFBOImage.
Definition at line 3108 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
image_t* R_CreateCubeImage (const char * name, const byte * pic[6], int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateCubeImage.
Parameters
[in] name
[in] pic
[in] width
[in] height
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 1536 of file tr_image.c.
Referenced by R_CreateCubeRenderImage(), and R_FindCubeImage().
image_t* R_CreateCubeRenderImage (const char * name, int color, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateCubeRenderImage.
Parameters
[in] name
[in] color
[in] width
[in] height
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 3015 of file tr_image.c.
Referenced by R_CreateColorCubeImages(), and R_CreateShadowCubeFBOImage().
static void R_CreateCurrentRenderImage (void) static
R_CreateCurrentRenderImage.
Definition at line 3142 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateDefaultImage (void) static
R_CreateDefaultImage.
Definition at line 2884 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateDeferredRenderFBOImages (void) static
R_CreateDeferredRenderFBOImages.
Definition at line 3251 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateDepthRenderImage (void) static
R_CreateDepthRenderImage.
Definition at line 3150 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateDepthToColorFBOImages (void) static
R_CreateDepthToColorFBOImages.
Todo:
which one should we use? Read up!
Definition at line 3181 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateDownScaleFBOImages (void) static
R_CreateDownScaleFBOImages.
Todo:
Clean up this mess some day ...
Definition at line 3198 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateFogImage (void) static
R_CreateFogImage.
Definition at line 2852 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
image_t* R_CreateImage (const char * name, const byte * pic, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateImage.
Parameters
[in] name
[in] pic
[in] width
[in] height
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 1495 of file tr_image.c.
static void R_CreateNoFalloffImage (void) static
R_CreateRandomNormalsImage unused - see randomNormalsImage static void R_CreateRandomNormalsImage(void) { int x, y; byte data[DEFAULT_SIZE][DEFAULT_SIZE][4];.
the default image will be a box, to allow you to see the mapping coordinates Com_Memset(data, 32, sizeof(data)); for (x = 0; x < DEFAULT_SIZE; x++) { for (y = 0; y < DEFAULT_SIZE; y++) { vec3_t n; float r, angle;
r = random(); angle = M_TAU_F * r; // / 360.0;
VectorSet(n, cos(angle), sin(angle), r); VectorNormalize(n);
VectorSet(n, crandom(), crandom(), crandom());
        data[y][x][0] = (byte) (128 + 127 * n[0]);
        data[y][x][1] = (byte) (128 + 127 * n[1]);
        data[y][x][2] = (byte) (128 + 127 * n[2]);
        data[y][x][3] = 255;
    }
}
tr.randomNormalsImage = R_CreateImage("_randomNormals", (byte *) data, DEFAULT_SIZE, DEFAULT_SIZE, IF_NOPICMIP, FT_DEFAULT, WT_REPEAT);
} R_CreateNoFalloffImage
Definition at line 2958 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateOcclusionRenderFBOImage (void) static
R_CreateOcclusionRenderFBOImage.
Definition at line 3173 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreatePortalRenderImage (void) static
R_CreatePortalRenderImage.
Definition at line 3158 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
image_t* R_CreateRenderImage (const char * name, qboolean quat, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateRenderImage.
Parameters
[in] name
[in] quat
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 3081 of file tr_image.c.
Referenced by R_CreateBloomRenderFBOImage(), R_CreateContrastRenderFBOImage(), R_CreateCurrentRenderImage(), R_CreateDeferredRenderFBOImages(), R_CreateDepthRenderImage(), R_CreateDepthToColorFBOImages(), R_CreateDownScaleFBOImages(), R_CreateOcclusionRenderFBOImage(), and R_CreatePortalRenderImage().
image_t* R_CreateRenderImageSize (const char * name, int width, int height, int bits, filterType_t filterType, wrapType_t wrapType)
R_CreateRenderImageSize.
Parameters
[in] name
[in] width
[in] height
[in] bits
[in] filterType
[in] wrapType
Returns
Definition at line 3053 of file tr_image.c.
Referenced by R_CreateDownScaleFBOImages(), R_CreateRenderImage(), and R_CreateShadowMapFBOImage().
static void R_CreateShadowCubeFBOImage (void) static
R_CreateShadowCubeFBOImage.
Definition at line 3361 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateShadowMapFBOImage (void) static
R_CreateShadowMapFBOImage.
Definition at line 3277 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_DisplaceMap (byte * in, byte * in2, int width, int height) static
R_DisplaceMap.
Parameters
[in,out] in
[in] in2
[in] width
[in] height
Definition at line 782 of file tr_image.c.
Referenced by ParseDisplaceMap().
image_t* R_FindCubeImage (const char * imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char * materialName)
Finds or loads the given image.
Parameters
[in] imageName
[in] bits
[in] filterType
[in] wrapType
[in] materialName
Returns
NULL if it fails, not a default image.
Note
Fear the use of goto
Todo:
Todo:
: better fix - scale the image to proper dimension
Definition at line 2583 of file tr_image.c.
Referenced by ParseSkyParms(), and ParseStage().
image_t* R_FindImageFile (const char * imageName, int bits, filterType_t filterType, wrapType_t wrapType, const char * materialName)
Finds or loads the given image.
Parameters
[in] imageName
[in] bits
[in] filterType
[in] wrapType
[in] materialName
Returns
NULL if it fails, not a default image.
Todo:
!!!
Todo:
: there are more cases for some models on vanilla maps!
Definition at line 2244 of file tr_image.c.
static void R_Flip (byte * in, int width, int height) static
R_Flip.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 2412 of file tr_image.c.
Referenced by R_FindCubeImage().
static void R_Flop (byte * in, int width, int height) static
R_Flop.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 2431 of file tr_image.c.
Referenced by R_FindCubeImage().
float R_FogFactor (float s, float t)
This is called for each texel of the fog texture on startup and for each vertex of transparent shaders in fog dynamically.
Parameters
[in] s
[in] t
Returns
A 0.0 to 1.0 fog density value.
Definition at line 2815 of file tr_image.c.
Referenced by R_CreateFogImage().
void R_GammaCorrect (byte * buffer, int bufSize)
R_GammaCorrect.
Parameters
[in,out] buffer
[in] bufSize
Definition at line 55 of file tr_image.c.
void* R_GetImageBuffer (int size, bufferMemType_t bufferType, const char * filename)
This is a hack to get the common imageloaders working properly.
R_GetImageBuffer.
Parameters
[in] size
[in] bufferType
[in] filename
Returns
Definition at line 1961 of file tr_image.c.
static void R_HeightMapToNormalMap (byte * in, int width, int height, float scale) static
R_HeightMapToNormalMap.
Parameters
[in,out] in
[in] width
[in] height
[in] scale
Definition at line 698 of file tr_image.c.
Referenced by ParseHeightMap().
void R_ImageCopyBack (image_t * image, int x, int y, int width, int height)
R_ImageCopyBack.
Parameters
[in] image
[in] x
[in] y
[in] width
[in] height
Definition at line 2211 of file tr_image.c.
void R_ImageList_f (void)
R_ImageList_f.
Todo:
Definition at line 172 of file tr_image.c.
void R_InitFogTable (void)
R_InitFogTable.
Definition at line 2798 of file tr_image.c.
Referenced by R_Init().
void R_InitImages (void)
R_InitImages.
Definition at line 3667 of file tr_image.c.
static void R_InvertAlpha (byte * in, int width, int height) static
R_InvertAlpha.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 864 of file tr_image.c.
Referenced by ParseInvertAlpha().
static void R_InvertColor (byte * in, int width, int height) static
R_InvertColor.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 884 of file tr_image.c.
Referenced by ParseInvertColor().
void R_LightScaleTexture (unsigned * in, int inwidth, int inheight, qboolean onlyGamma)
Scale up the pixel values in a texture to increase the lighting range.
Parameters
[in,out] in
[in] inwidth
[in] inheight
[in] onlyGamma
Definition at line 464 of file tr_image.c.
static void R_LoadImage (char ** buffer, byte ** pic, int * width, int * height, int * bits, const char * materialName) static
Loads any of the supported image types into a canonical 32 bit format.
Parameters
[in,out] buffer
[out] pic
[out] width
[out] height
[in,out] bits
[in] materialName
Definition at line 1990 of file tr_image.c.
static void R_MakeAlpha (byte * in, int width, int height) static
R_MakeAlpha.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 931 of file tr_image.c.
Referenced by ParseMakeAlpha().
static void R_MakeIntensity (byte * in, int width, int height) static
R_MakeIntensity.
Parameters
[in,out] in
width
height
Definition at line 906 of file tr_image.c.
Referenced by ParseMakeIntensity().
static void R_MipMap (byte * in, int width, int height) static
Operates in place, quartering the size of the texture.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 572 of file tr_image.c.
Referenced by R_UploadImage().
static void R_MipMap2 (unsigned * in, int inWidth, int inHeight) static
Operates in place, quartering the size of the texture Proper linear filter.
Parameters
[in] in
[in] inWidth
[in] inHeight
Definition at line 518 of file tr_image.c.
Referenced by R_MipMap().
static void R_MipNormalMap (byte * in, int width, int height) static
Operates in place, quartering the size of the texture.
Parameters
[in,out] in
[in] width
[in] height
Definition at line 626 of file tr_image.c.
Referenced by R_UploadImage().
static void R_ResampleTexture (unsigned * in, int inwidth, int inheight, unsigned * out, int outwidth, int outheight, qboolean normalMap) static
Used to resample images in a more general than quartering fashion.
This will only be filtered properly if the resampled size is greater than half the original size.
If a larger shrinking is needed, use the mipmap function before or after.
Parameters
[in,out] in
[in] inwidth
[in] inheight
[out] out
[in] outwidth
[in] outheight
[in] normalMap
Definition at line 349 of file tr_image.c.
Referenced by R_UploadImage().
static void R_Rotate (byte * in, int width, int height, int degrees) static
R_Rotate.
Parameters
[in,out] in
[in] width
[in] height
[in] degrees
Definition at line 2451 of file tr_image.c.
Referenced by R_FindCubeImage().
void R_SetColorMappings (void)
R_SetColorMappings.
Definition at line 3556 of file tr_image.c.
void R_ShutdownImages (void)
R_ShutdownImages.
Definition at line 3708 of file tr_image.c.
Referenced by RE_Shutdown().
void R_SubImageCpy (byte * dest, size_t destx, size_t desty, size_t destw, size_t desth, byte * src, size_t srcw, size_t srch, size_t bytes, qboolean in)
Copies between a smaller image and a larger image. Last flag controls is copy in or out of larger image.
Parameters
[in,out] dest
[in] destx
[in] desty
[in] destw
[in] desth
[in,out] src
[in] srcw
[in] srch
[in] bytes
[in] in
Note
e.g. dest = Com_Allocate(4*4*channels); [________] [________] [________] [________] src = Com_Allocate(2*2*channels); [____] [____] R_SubImageCpy(dest, 0, 0, 4, 4, src, 2, 2, channels, qtrue); [____]___] [____]___] [________]
[________]
Definition at line 2548 of file tr_image.c.
Referenced by R_BuildCubeMaps(), and R_LoadCubeProbe().
int R_SumOfUsedImages (void)
R_SumOfUsedImages.
Returns
Definition at line 150 of file tr_image.c.
static ID_INLINE void R_SwapPixel (byte * inout, int x, int y, int x2, int y2, int width, int height) static
R_SwapPixel.
Parameters
[in,out] inout
[in] x
[in] y
[in] x2
[in] y2
[in] width
height - unused
Definition at line 2380 of file tr_image.c.
Referenced by R_Flip(), and R_Flop().
void R_UploadImage (const byte ** dataArray, int numData, image_t * image)
R_UploadImage.
Parameters
[in] dataArray
[in] numData
[in] image
Todo:
: deal with frame buffer object? No mipmap for now ...
Definition at line 1021 of file tr_image.c.
Referenced by R_BuildCubeMaps(), R_CreateCubeImage(), and R_CreateImage().
int RE_GetTextureId (const char * name)
RE_GetTextureId.
Parameters
name
Returns
Definition at line 3739 of file tr_image.c.
Referenced by GetRefAPI().
Variable Documentation
int gl_filter_max = GL_LINEAR
Definition at line 42 of file tr_image.c.
int gl_filter_min = GL_LINEAR_MIPMAP_NEAREST
Definition at line 41 of file tr_image.c.
imageLoaders static
Initial value:
=
{
    { "png",  R_LoadPNG },
    { "tga",  R_LoadTGA },
    { "jpg",  R_LoadJPG },
    { "jpeg", R_LoadJPG },
    { "pcx",  R_LoadPCX },
    { "bmp",  R_LoadBMP }
}
Note that the ordering indicates the order of preference used when there are multiple images of different formats available.
Definition at line 1942 of file tr_image.c.
byte mipBlendColors[16][4]
Definition at line 979 of file tr_image.c.
textureMode_t modes[]
Initial value:
=
{
    { "GL_NEAREST",                GL_NEAREST,                GL_NEAREST },
    { "GL_LINEAR",                 GL_LINEAR,                 GL_LINEAR  },
    { "GL_NEAREST_MIPMAP_NEAREST", GL_NEAREST_MIPMAP_NEAREST, GL_NEAREST },
    { "GL_LINEAR_MIPMAP_NEAREST",  GL_LINEAR_MIPMAP_NEAREST,  GL_LINEAR  },
    { "GL_NEAREST_MIPMAP_LINEAR",  GL_NEAREST_MIPMAP_LINEAR,  GL_NEAREST },
    { "GL_LINEAR_MIPMAP_LINEAR",   GL_LINEAR_MIPMAP_LINEAR,   GL_LINEAR  }
}
Definition at line 75 of file tr_image.c.
int numImageLoaders = sizeof(imageLoaders) / sizeof(imageLoaders[0]) static
Definition at line 1952 of file tr_image.c.
Referenced by R_LoadImage().
image_t* r_imageHashTable[IMAGE_FILE_HASH_SIZE]
Definition at line 45 of file tr_image.c.
unsigned char s_gammatable[256] static
Definition at line 39 of file tr_image.c.
Referenced by R_GammaCorrect(), R_LightScaleTexture(), and R_SetColorMappings().
byte s_intensitytable[256] static
Definition at line 38 of file tr_image.c.
Referenced by R_LightScaleTexture(), and R_SetColorMappings().