ET: Legacy: src/renderer2/tr_main.c File Reference
tr_main.c File Reference
Main control flow for each frame.
#include "tr_local.h"
Functions
qboolean R_CompareVert (srfVert_t *v1, srfVert_t *v2, qboolean checkST)
R_CompareVert.
void R_CalcNormalForTriangle (vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2)
R_CalcNormalForTriangle.
void R_CalcTangentsForTriangle (vec3_t tangent, vec3_t binormal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentsForTriangle.
void R_CalcTangentSpace (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpace.
void R_CalcTangentSpaceFast (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpaceFast.
void R_CalcTBN (vec3_t tangent, vec3_t bitangent, vec3_t normal, const vec3_t v1, const vec3_t v2, const vec3_t v3, const vec2_t w1, const vec2_t w2, const vec2_t w3)
R_CalcTBN.
void R_CalcTBN2 (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v1, const vec3_t v2, const vec3_t v3, const vec2_t t1, const vec2_t t2, const vec2_t t3)
R_CalcTBN2.
qboolean R_CalcTangentVectors (srfVert_t *dv[3])
R_CalcTangentVectors.
void R_CalcSurfaceTrianglePlanes (int numTriangles, srfTriangle_t *triangles, srfVert_t *verts)
R_CalcSurfaceTrianglePlanes calculates planeNormal.
cullResult_t R_CullBox (vec3_t worldBounds[2])
R_CullBox.
cullResult_t R_CullLocalBox (vec3_t bounds[2])
R_CullLocalBox.
int R_CullLocalPointAndRadius (vec3_t origin, float radius)
R_CullLocalPointAndRadius.
int R_CullPointAndRadius (vec3_t origin, float radius)
R_CullPointAndRadius.
int R_FogLocalPointAndRadius (const vec3_t pt, float radius)
R_FogLocalPointAndRadius.
int R_FogPointAndRadius (const vec3_t pt, float radius)
R_FogPointAndRadius.
int R_FogWorldBox (vec3_t bounds[2])
R_FogWorldBox.
void R_LocalNormalToWorld (const vec3_t local, vec3_t world)
R_LocalNormalToWorld.
void R_LocalPointToWorld (const vec3_t local, vec3_t world)
R_LocalPointToWorld.
void R_TransformWorldToClip (const vec3_t src, const float *cameraViewMatrix, const float *projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformWorldToClip.
void R_TransformModelToClip (const vec3_t src, const float *modelMatrix, const float *projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformModelToClip.
void R_TransformClipToWindow (const vec4_t clip, const viewParms_t *view, vec4_t normalized, vec4_t window)
R_TransformClipToWindow.
float R_ProjectRadius (float r, vec3_t location)
R_ProjectRadius.
void R_SetupEntityWorldBounds (trRefEntity_t *ent)
R_SetupEntityWorldBounds.
void R_RotateEntityForViewParms (const trRefEntity_t *ent, const viewParms_t *viewParms, orientationr_t *orientation)
Generates an orientation for an entity and viewParms. Does NOT produce any GL calls. Called by both the front end and the back end.
void R_RotateEntityForLight (const trRefEntity_t *ent, const trRefLight_t *light, orientationr_t *orientation)
Generates an orientation for an entity and light. Does NOT produce any GL calls. Called by both the front end and the back end.
void R_RotateLightForViewParms (const trRefLight_t *ent, const viewParms_t *viewParms, orientationr_t *orientation)
R_RotateLightForViewParms.
void R_RotateForViewer (void)
Sets up the modelview matrix for a given viewParm.
static void SetFarClip (void)
SetFarClip.
static void R_SetupProjection (qboolean infiniteFarClip)
R_SetupProjection.
static void R_SetupUnprojection (void)
Create a matrix with similar functionality like gluUnproject, project from window space to world space.
void R_SetupFrustum (void)
Setup that culling frustum planes for the current view.
void R_SetupFrustum2 (frustum_t frustum, const mat4_t mvp)
Setup that culling frustum planes for the current view.
static void CopyPlane (const cplane_t *in, cplane_t *out)
CopyPlane.
static void R_SetupSplitFrustums (void)
R_SetupSplitFrustums.
void R_MirrorPoint (vec3_t in, orientation_t *surface, orientation_t *camera, vec3_t out)
R_MirrorPoint.
void R_MirrorVector (vec3_t in, orientation_t *surface, orientation_t *camera, vec3_t out)
R_MirrorVector.
void R_PlaneForSurface (surfaceType_t *surfType, cplane_t *plane)
R_PlaneForSurface.
static qboolean R_GetPortalOrientations (drawSurf_t *drawSurf, orientation_t *surface, orientation_t *camera, vec3_t pvsOrigin, qboolean *mirror)
entityNum is the entity that the portal surface is a part of, which may be moving and rotating.
static qboolean IsMirror (const drawSurf_t *drawSurf)
IsMirror.
static qboolean SurfIsOffscreen (const drawSurf_t *drawSurf, vec4_t clipDest[128])
Determines if a surface is completely offscreen.
static qboolean R_MirrorViewBySurface (drawSurf_t *drawSurf)
R_MirrorViewBySurface.
int R_SpriteFogNum (trRefEntity_t *ent)
See if a sprite is inside a fog volume.
void R_AddDrawSurf (surfaceType_t *surface, shader_t *shader, int lightmapNum, int fogNum)
R_AddDrawSurf.
static int DrawSurfCompare (const void *a, const void *b)
Compare function for qsort()
static void R_SortDrawSurfs (void)
R_SortDrawSurfs.
void R_AddEntitySurfaces (void)
R_AddEntitySurfaces.
void R_AddEntityInteractions (trRefLight_t *light)
R_AddEntityInteractions.
void R_AddPolygonInteractions (trRefLight_t *light)
R_AddPolygonInteractions.
void R_AddLightInteractions ()
R_AddLightInteractions.
void R_AddLightBoundsToVisBounds ()
R_AddLightBoundsToVisBounds.
void R_DebugAxis (const vec3_t origin, const mat4_t transformMatrix)
R_DebugAxis.
void R_DebugBoundingBox (const vec3_t origin, const vec3_t mins, const vec3_t maxs, vec4_t color)
R_DebugBoundingBox.
void R_DebugPolygon (int color, int numPoints, float *points)
R_DebugPolygon.
void R_DebugText (const vec3_t org, float r, float g, float b, const char *text, qboolean neverOcclude)
R_DebugText.
static void R_DebugGraphics (void)
Visualization aid for movement clipping debugging.
void R_RenderView (viewParms_t *parms)
A view may be either the actual camera view, or a mirror / remote location.
Variables
trGlobals_t tr
const mat4_t quakeToOpenGLMatrix
Convert from our coordinate system (looking down X) to OpenGL's coordinate system (looking down -Z)
const mat4_t openGLToQuakeMatrix
Inverse of quakeToOpenGL matrix.
const mat4_t quakeToD3DMatrix
const mat4_t flipZMatrix
const GLenum geometricRenderTargets []
int shadowMapResolutions [5] = { 2048, 1024, 512, 256, 128 }
int sunShadowMapResolutions [5] = { 2048, 2048, 1024, 1024, 1024 }
refimport_t ri
surfaceType_t entitySurface = SF_ENTITY
Detailed Description
Main control flow for each frame.
Definition in file tr_main.c.
Function Documentation
static void CopyPlane (const cplane_t * in, cplane_t * out) static
CopyPlane.
Parameters
[in] in
[out] out
Definition at line 1603 of file tr_main.c.
Referenced by R_SetupSplitFrustums().
static int DrawSurfCompare (const void * a, const void * b) static
Compare function for qsort()
Parameters
[in] a
[in] b
Returns
Definition at line 2235 of file tr_main.c.
Referenced by R_SortDrawSurfs().
static qboolean IsMirror (const drawSurf_t * drawSurf) static
IsMirror.
Parameters
[in] drawSurf
Returns
Todo:
: never read
Todo:
: never read
Definition at line 1924 of file tr_main.c.
Referenced by SurfIsOffscreen().
void R_AddDrawSurf (surfaceType_t * surface, shader_t * shader, int lightmapNum, int fogNum)
R_AddDrawSurf.
Parameters
[in] surface
[in] shader
[in] lightmapNum
[in] fogNum
Definition at line 2203 of file tr_main.c.
void R_AddEntityInteractions (trRefLight_t * light)
R_AddEntityInteractions.
Parameters
[in] light
Definition at line 2490 of file tr_main.c.
Referenced by R_AddLightInteractions().
void R_AddEntitySurfaces (void)
R_AddEntitySurfaces.
Definition at line 2385 of file tr_main.c.
Referenced by R_GenerateDrawSurfs(), and R_RenderView().
void R_AddLightBoundsToVisBounds ()
R_AddLightBoundsToVisBounds.
Definition at line 2842 of file tr_main.c.
Referenced by R_RenderView().
void R_AddLightInteractions ()
R_AddLightInteractions.
Todo:
Definition at line 2613 of file tr_main.c.
Referenced by R_RenderView().
void R_AddPolygonInteractions (trRefLight_t * light)
R_AddPolygonInteractions.
Parameters
[in] light
Definition at line 2570 of file tr_main.c.
void R_CalcNormalForTriangle (vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2)
R_CalcNormalForTriangle.
Parameters
[in] normal
[in] v0
[in] v1
[in] v2
Definition at line 138 of file tr_main.c.
Referenced by ParseTriSurf(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
void R_CalcSurfaceTrianglePlanes (int numTriangles, srfTriangle_t * triangles, srfVert_t * verts)
R_CalcSurfaceTrianglePlanes calculates planeNormal.
Parameters
[in] numTriangles
[in] triangles
[in] verts
Definition at line 598 of file tr_main.c.
void R_CalcTangentsForTriangle (vec3_t tangent, vec3_t binormal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentsForTriangle.
Parameters
[out] tangent
[out] binormal
[in] v0
[in] v1
[in] v2
[in] t0
[in] t1
[in] t2
Note
http://members.rogers.com/deseric/tangentspace.htm
Definition at line 163 of file tr_main.c.
Referenced by R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
void R_CalcTangentSpace (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpace.
Parameters
[out] tangent
[out] binormal
[out] normal
[in] v0
[in] v1
[in] v2
[in] t0
[in] t1
[in] t2
Definition at line 213 of file tr_main.c.
Referenced by ParseFace(), ParseTriSurf(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
void R_CalcTangentSpaceFast (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v0, const vec3_t v1, const vec3_t v2, const vec2_t t0, const vec2_t t1, const vec2_t t2)
R_CalcTangentSpaceFast.
Parameters
[out] tangent
[out] binormal
[out] normal
[in] v0
[in] v1
[in] v2
[in] t0
[in] t1
[in] t2
Definition at line 301 of file tr_main.c.
Referenced by Tess_SurfaceMDV(), and Tess_SurfacePolychain().
qboolean R_CalcTangentVectors (srfVert_t * dv[3])
R_CalcTangentVectors.
Parameters
[in,out] dv
Returns
Definition at line 540 of file tr_main.c.
Referenced by MakeMeshTangentVectors(), ParseFace(), and ParseTriSurf().
void R_CalcTBN (vec3_t tangent, vec3_t bitangent, vec3_t normal, const vec3_t v1, const vec3_t v2, const vec3_t v3, const vec2_t w1, const vec2_t w2, const vec2_t w3)
R_CalcTBN.
Parameters
[out] tangent
[out] bitangent
[out] normal
[in] v1
[in] v2
[in] v3
[in] w1
[in] w2
[in] w3
Note
http://www.terathon.com/code/tangent.html
Unused
Definition at line 388 of file tr_main.c.
void R_CalcTBN2 (vec3_t tangent, vec3_t binormal, vec3_t normal, const vec3_t v1, const vec3_t v2, const vec3_t v3, const vec2_t t1, const vec2_t t2, const vec2_t t3)
R_CalcTBN2.
Parameters
[out] tangent
[out] binormal
[out] normal
[in] v1
[in] v2
[in] v3
[in] t1
[in] t2
[in] t3
Note
Unused
Definition at line 439 of file tr_main.c.
qboolean R_CompareVert (srfVert_t * v1, srfVert_t * v2, qboolean checkST)
R_CompareVert.
Parameters
[in] v1
[in] v2
[in] checkST
Returns
Definition at line 111 of file tr_main.c.
Referenced by MakeMeshTangentVectors(), and ParseTriSurf().
cullResult_t R_CullBox (vec3_t worldBounds[2])
R_CullBox.
Parameters
[in] worldBounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 624 of file tr_main.c.
Referenced by R_CullLocalBox(), R_CullMD5(), and R_CullMDV().
cullResult_t R_CullLocalBox (vec3_t bounds[2])
R_CullLocalBox.
Parameters
[in] bounds
Returns
CULL_IN, CULL_CLIP, or CULL_OUT
Definition at line 691 of file tr_main.c.
int R_CullLocalPointAndRadius (vec3_t origin, float radius)
R_CullLocalPointAndRadius.
Parameters
[in] origin
[in] radius
Returns
Definition at line 707 of file tr_main.c.
int R_CullPointAndRadius (vec3_t origin, float radius)
R_CullPointAndRadius.
Parameters
[in] origin
[in] radius
Returns
Definition at line 722 of file tr_main.c.
void R_DebugAxis (const vec3_t origin, const mat4_t transformMatrix)
R_DebugAxis.
Parameters
[in] origin
[in] transformMatrix
Definition at line 3016 of file tr_main.c.
void R_DebugBoundingBox (const vec3_t origin, const vec3_t mins, const vec3_t maxs, vec4_t color)
R_DebugBoundingBox.
Parameters
[in] origin
[in] mins
[in] maxs
[in] color
Note
from botlib
Definition at line 3056 of file tr_main.c.
static void R_DebugGraphics (void) static
Visualization aid for movement clipping debugging.
Definition at line 3178 of file tr_main.c.
Referenced by R_RenderView().
void R_DebugPolygon (int color, int numPoints, float * points)
R_DebugPolygon.
Parameters
[in] color
[in] numPoints
[in] points
Definition at line 3111 of file tr_main.c.
void R_DebugText (const vec3_t org, float r, float g, float b, const char * text, qboolean neverOcclude)
R_DebugText.
Parameters
[in] org
[in] r
[in] g
[in] b
[in] text
[in] neverOcclude
Definition at line 3152 of file tr_main.c.
int R_FogLocalPointAndRadius (const vec3_t pt, float radius)
R_FogLocalPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
Note
Unused
Definition at line 767 of file tr_main.c.
int R_FogPointAndRadius (const vec3_t pt, float radius)
R_FogPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
Todo:
: non-normalized axis issues
Definition at line 782 of file tr_main.c.
Referenced by R_FogLocalPointAndRadius().
int R_FogWorldBox (vec3_t bounds[2])
R_FogWorldBox.
Parameters
[out] bounds
Returns
Definition at line 822 of file tr_main.c.
Referenced by R_AddBSPModelSurfaces(), R_AddMD5Surfaces(), R_AddMDVSurfaces(), and R_MDM_AddAnimSurfaces().
static qboolean R_GetPortalOrientations (drawSurf_t * drawSurf, orientation_t * surface, orientation_t * camera, vec3_t pvsOrigin, qboolean * mirror) static
entityNum is the entity that the portal surface is a part of, which may be moving and rotating.
Parameters
[in] drawSurf
[in] surface
[out] camera
[out] pvsOrigin
[out] mirror
Returns
qtrue if it should be mirrored
Definition at line 1766 of file tr_main.c.
Referenced by R_MirrorViewBySurface().
void R_LocalNormalToWorld (const vec3_t local, vec3_t world)
R_LocalNormalToWorld.
Parameters
[in] local
[in] world
Definition at line 863 of file tr_main.c.
void R_LocalPointToWorld (const vec3_t local, vec3_t world)
R_LocalPointToWorld.
Parameters
[in] local
[in] world
Definition at line 873 of file tr_main.c.
void R_MirrorPoint (vec3_t in, orientation_t * surface, orientation_t * camera, vec3_t out)
R_MirrorPoint.
Parameters
[in] in
[in] surface
[in] camera
[out] out
Definition at line 1672 of file tr_main.c.
void R_MirrorVector (vec3_t in, orientation_t * surface, orientation_t * camera, vec3_t out)
R_MirrorVector.
Parameters
[in] in
[in] surface
[in] camera
[out] out
Definition at line 1698 of file tr_main.c.
static qboolean R_MirrorViewBySurface (drawSurf_t * drawSurf) static
R_MirrorViewBySurface.
Parameters
[in] drawSurf
Returns
qtrue if another view has been rendered
Definition at line 2099 of file tr_main.c.
void R_PlaneForSurface (surfaceType_t * surfType, cplane_t * plane)
R_PlaneForSurface.
Parameters
[in] surfType
[out] plane
Definition at line 1716 of file tr_main.c.
float R_ProjectRadius (float r, vec3_t location)
R_ProjectRadius.
Parameters
[in] r
[in] location
Returns
Definition at line 944 of file tr_main.c.
Referenced by R_ComputeLOD(), and R_SetupLightLOD().
void R_RenderView (viewParms_t * parms)
A view may be either the actual camera view, or a mirror / remote location.
Parameters
[in] parms
Definition at line 3198 of file tr_main.c.
void R_RotateEntityForLight (const trRefEntity_t * ent, const trRefLight_t * light, orientationr_t * orientation)
Generates an orientation for an entity and light. Does NOT produce any GL calls. Called by both the front end and the back end.
Parameters
[in] ent
[in] light
[out] orientation
Definition at line 1063 of file tr_main.c.
Referenced by RB_RenderInteractionsShadowMapped().
void R_RotateEntityForViewParms (const trRefEntity_t * ent, const viewParms_t * viewParms, orientationr_t * orientation)
Generates an orientation for an entity and viewParms. Does NOT produce any GL calls. Called by both the front end and the back end.
Parameters
[in] ent
[in] viewParms
[out] orientation
Definition at line 1006 of file tr_main.c.
Referenced by IsMirror(), R_AddEntitySurfaces(), R_GetPortalOrientations(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), and SurfIsOffscreen().
void R_RotateForViewer (void)
Sets up the modelview matrix for a given viewParm.
Definition at line 1153 of file tr_main.c.
void R_RotateLightForViewParms (const trRefLight_t * ent, const viewParms_t * viewParms, orientationr_t * orientation)
R_RotateLightForViewParms.
Parameters
[in] ent
[in] viewParms
[out] orientation
Definition at line 1129 of file tr_main.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), RB_RenderDebugUtils(), and RenderLightOcclusionVolume().
void R_SetupEntityWorldBounds (trRefEntity_t * ent)
R_SetupEntityWorldBounds.
Parameters
[in] ent
Note
needs R_RotateEntityForViewParms
Definition at line 992 of file tr_main.c.
Referenced by R_CullMD5(), R_CullMDV(), and R_CullModel().
void R_SetupFrustum (void)
Setup that culling frustum planes for the current view.
Definition at line 1487 of file tr_main.c.
void R_SetupFrustum2 (frustum_t frustum, const mat4_t mvp)
Setup that culling frustum planes for the current view.
Parameters
[out] frustum
[in] mvp
Definition at line 1535 of file tr_main.c.
Referenced by MergeInteractionBounds(), R_CalcLightCubeSideBits(), and R_RenderView().
static void R_SetupProjection (qboolean infiniteFarClip) static
R_SetupProjection.
Parameters
[in] infiniteFarClip
Definition at line 1367 of file tr_main.c.
static void R_SetupSplitFrustums (void) static
R_SetupSplitFrustums.
Definition at line 1616 of file tr_main.c.
Referenced by R_RenderView().
static void R_SetupUnprojection (void) static
Create a matrix with similar functionality like gluUnproject, project from window space to world space.
Todo:
?
Definition at line 1467 of file tr_main.c.
Referenced by R_RenderView().
static void R_SortDrawSurfs (void) static
R_SortDrawSurfs.
Definition at line 2299 of file tr_main.c.
Referenced by R_RenderView().
int R_SpriteFogNum (trRefEntity_t * ent)
See if a sprite is inside a fog volume.
Parameters
[in] ent
Returns
Definition at line 2163 of file tr_main.c.
void R_TransformClipToWindow (const vec4_t clip, const viewParms_t * view, vec4_t normalized, vec4_t window)
R_TransformClipToWindow.
Parameters
[in] clip
[in] view
[out] normalized
[out] window
Definition at line 924 of file tr_main.c.
void R_TransformModelToClip (const vec3_t src, const float * modelMatrix, const float * projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformModelToClip.
Parameters
[in] src
[in] modelMatrix
[in] projectionMatrix
[in] eye
[out] dst
Definition at line 906 of file tr_main.c.
void R_TransformWorldToClip (const vec3_t src, const float * cameraViewMatrix, const float * projectionMatrix, vec4_t eye, vec4_t dst)
R_TransformWorldToClip.
Parameters
[in] src
[in] cameraViewMatrix
[in] projectionMatrix
[in] eye
[out] dst
Definition at line 886 of file tr_main.c.
Referenced by R_AddPointToLightScissor().
static void SetFarClip (void) static
SetFarClip.
Definition at line 1278 of file tr_main.c.
Referenced by R_SetupProjection().
static qboolean SurfIsOffscreen (const drawSurf_t * drawSurf, vec4_t clipDest[128]) static
Determines if a surface is completely offscreen.
Parameters
[in] drawSurf
clipDest - unused
Returns
Definition at line 1987 of file tr_main.c.
Referenced by R_MirrorViewBySurface().
Variable Documentation
surfaceType_t entitySurface = SF_ENTITY
entities that will have procedurally generated surfaces will just point at this for their sorting surface
Definition at line 102 of file tr_main.c.
const mat4_t flipZMatrix
Initial value:
=
{
    1, 0, 0,  0,
    0, 1, 0,  0,
    0, 0, -1, 0,
    0, 0, 0,  1
}
Definition at line 79 of file tr_main.c.
Referenced by RB_RenderInteractionsShadowMapped().
const GLenum geometricRenderTargets[]
Initial value:
=
{
    GL_COLOR_ATTACHMENT0_EXT,
    GL_COLOR_ATTACHMENT1_EXT,
    GL_COLOR_ATTACHMENT2_EXT,
    GL_COLOR_ATTACHMENT3_EXT
}
Definition at line 87 of file tr_main.c.
const mat4_t openGLToQuakeMatrix
Initial value:
=
{
    0,  -1, 0, 0,
    0,  0,  1, 0,
    -1, 0,  0, 0,
    0,  0,  0, 1
}
Inverse of quakeToOpenGL matrix.
convert from our right handed coordinate system (looking down X) to D3D's left handed coordinate system (looking down Z)
Definition at line 58 of file tr_main.c.
const mat4_t quakeToD3DMatrix
Initial value:
=
{
    0,  0, 1, 0,
    -1, 0, 0, 0,
    0,  1, 0, 0,
    0,  0, 0, 1
}
Definition at line 71 of file tr_main.c.
Referenced by R_RotateForViewer().
const mat4_t quakeToOpenGLMatrix
Initial value:
=
{
    0,  0, -1, 0,
    -1, 0, 0,  0,
    0,  1, 0,  0,
    0,  0, 0,  1
}
Convert from our coordinate system (looking down X) to OpenGL's coordinate system (looking down -Z)
Definition at line 46 of file tr_main.c.
Referenced by R_CalcLightCubeSideBits(), R_RotateForViewer(), R_SetupUnprojection(), RB_RenderDebugUtils(), and RB_RenderInteractionsShadowMapped().
refimport_t ri
Definition at line 98 of file tr_main.c.
int shadowMapResolutions[5] = { 2048, 1024, 512, 256, 128 }
Definition at line 95 of file tr_main.c.
Referenced by R_CreateShadowCubeFBOImage(), R_CreateShadowMapFBOImage(), R_InitFBOs(), R_Register(), and RB_RenderInteractionsShadowMapped().
int sunShadowMapResolutions[5] = { 2048, 2048, 1024, 1024, 1024 }
Definition at line 96 of file tr_main.c.
Referenced by R_CreateShadowMapFBOImage(), R_InitFBOs(), R_Register(), and RB_RenderInteractionsShadowMapped().
trGlobals_t tr
Definition at line 39 of file tr_main.c.