ET: Legacy: src/renderer2/tr_shader.c File Reference
tr_shader.c File Reference
Parsing and definition of materials/shaders from r2 materials folder.
#include "tr_shader.h"
Data Structures
struct infoParm_t
Functions
void R_RemapShader (const char *shaderName, const char *newShaderName, const char *timeOffset)
R_RemapShader.
static qboolean ParseVector (char **text, int count, float *v)
ParseVector.
static void GetOpType (const char *token, expOperation_t *op)
GetOpType.
static qboolean IsOperand (opcode_t oc)
IsOperand.
static qboolean IsOperator (opcode_t oc)
IsOperator.
static int GetOpPrecedence (opcode_t oc)
GetOpPrecedence.
static char * ParseExpressionElement (char **data_p)
ParseExpressionElement.
static void ParseExpression (char **text, expression_t *exp)
ParseExpression.
static unsigned NameToAFunc (const char *funcname)
NameToAFunc.
static int NameToSrcBlendMode (const char *name)
NameToSrcBlendMode.
static int NameToDstBlendMode (const char *name)
NameToDstBlendMode.
static genFunc_t NameToGenFunc (const char *funcname)
NameToGenFunc.
static int NameToStencilOp (const char *name)
NameToStencilOp.
void ParseStencil (char **text, stencil_t *stencil)
ParseStencil.
void ParseWaveForm (char **text, waveForm_t *wave)
ParseWaveForm.
qboolean ParseTexMod (char **text, shaderStage_t *stage)
ParseTexMod.
static qboolean ParseMap (shaderStage_t *stage, char **text, char *buffer, size_t bufferSize)
ParseMap.
qboolean LoadMap (shaderStage_t *stage, char *buffer)
LoadMap.
qboolean ParseStage (shaderStage_t *stage, char **text)
ParseStage.
void ParseDeform (char **text)
ParseDeform.
void ParseSkyParms (char **text)
ParseSkyParms.
void ParseSort (char **text)
ParseSort.
qboolean SurfaceParm (const char *token)
SurfaceParm.
void ParseSurfaceParm (char **text)
ParseSurfaceParm.
void ParseDiffuseMap (shaderStage_t *stage, char **text)
ParseDiffuseMap.
void ParseNormalMap (shaderStage_t *stage, char **text)
ParseNormalMap.
void ParseSpecularMap (shaderStage_t *stage, char **text)
ParseSpecularMap.
void ParseGlowMap (shaderStage_t *stage, char **text)
ParseGlowMap.
void ParseReflectionMap (shaderStage_t *stage, char **text)
ParseReflectionMap.
void ParseReflectionMapBlended (shaderStage_t *stage, char **text)
ParseReflectionMapBlended.
void ParseLightFalloffImage (shaderStage_t *stage, char **text)
ParseLightFalloffImage.
static char * FindGuideInGuideText (const char *guideName)
Scans the combined text description of all the shader template files for the given guide name.
static char * CreateShaderByGuide (const char *guideName, char *shaderText)
CreateShaderByGuide.
static qboolean ParseShader (char *_text)
The current text pointer is at the explicit text definition of the shader. Parse it into the global shader variable. Later functions will optimize it.
static void CollapseStages ()
CollapseStages.
static void SortNewShader (void)
Positions the most recently created shader in the tr.sortedShaders[] array so that the shader->sort key is sorted reletive to the other shaders.
static shader_t * GeneratePermanentShader (void)
GeneratePermanentShader.
void GeneratePermanentShaderTable (float *values, int numValues)
GeneratePermanentShaderTable.
static shader_t * FinishShader (void)
FinishShader.
qboolean RE_LoadDynamicShader (const char *shadername, const char *shadertext)
Load a new dynamic shader. If shadertext is NULL, looks for matching shadername and removes it.
static char * FindShaderInShaderText (const char *shaderName)
Scans the combined text description of all the shader files for the given shader name.
shader_t * R_FindShaderByName (const char *name)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
shader_t * R_FindShader (const char *name, shaderType_t type, qboolean mipRawImage)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
qhandle_t RE_RegisterShaderFromImage (const char *name, image_t *image, qboolean mipRawImage)
RE_RegisterShaderFromImage.
qhandle_t RE_RegisterShader (const char *name)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
qhandle_t RE_RegisterShaderNoMip (const char *name)
For menu graphics that should never be picmiped.
qhandle_t RE_RegisterShaderLightAttenuation (const char *name)
For different Doom3 style light effects.
shader_t * R_GetShaderByHandle (qhandle_t hShader)
When a handle is passed in by another module, this range checks it and returns a valid (possibly default) shader_t to be used internally.
void R_ShaderList_f (void)
Dump information on all valid shaders to the console A second parameter will cause it to print in sorted order.
void R_ShaderExp_f (void)
R_ShaderExp_f.
static int ScanAndLoadShaderFiles (void)
Finds and loads all .guide files, combining them into a single large text block that can be scanned for shader template names NOTE not used static void ScanAndLoadGuideFiles(void) { char **guideFiles; char *buffers[MAX_GUIDE_FILES]; char *p; int numGuides, i; char *oldp, *token; char **hashMem; int guideTextHashTableSizes[MAX_GUIDETEXT_HASH], hash, fileSum; unsigned int size; char filename[MAX_QPATH]; long sum = 0;.
static void CreateInternalShaders (void)
CreateInternalShaders.
static void CreateExternalShaders (void)
CreateExternalShaders.
void R_InitShaders (void)
R_InitShaders.
Variables
static char ** guideTextHashTable [MAX_GUIDETEXT_HASH]
static char ** shaderTextHashTable [MAX_SHADERTEXT_HASH]
static char * s_guideText
static char * s_shaderText
static int numMaterialFiles
static int numShaderFiles
const opstring_t opStrings []
infoParm_t infoParms []
Detailed Description
Parsing and definition of materials/shaders from r2 materials folder.
Note
R_FindShader is extended to read material from r1 scripts folder!
Definition in file tr_shader.c.
Function Documentation
static void CollapseStages () static
CollapseStages.
Todo:
?
Definition at line 4621 of file tr_shader.c.
Referenced by FinishShader().
static void CreateExternalShaders (void) static
CreateExternalShaders.
Definition at line 6994 of file tr_shader.c.
static void CreateInternalShaders (void) static
CreateInternalShaders.
Definition at line 6956 of file tr_shader.c.
static char* CreateShaderByGuide (const char * guideName, char * shaderText) static
CreateShaderByGuide.
Parameters
[in] guideName
[in,out] shaderText
Returns
Definition at line 3550 of file tr_shader.c.
Referenced by ParseShader().
static char* FindGuideInGuideText (const char * guideName) static
Scans the combined text description of all the shader template files for the given guide name.
Parameters
[in] guideName
Returns
NULL if not found otherwise it will return a valid template
Definition at line 3452 of file tr_shader.c.
Referenced by CreateShaderByGuide().
static char* FindShaderInShaderText (const char * shaderName) static
Scans the combined text description of all the shader files for the given shader name.
Parameters
[in] shaderName
Returns
NULL if not found, otherwise it will return a valid shader
Definition at line 5445 of file tr_shader.c.
Referenced by R_FindShader().
static shader_t* FinishShader (void) static
FinishShader.
Returns
A freshly allocated shader with all the needed info from the current global working shader
Definition at line 5058 of file tr_shader.c.
Referenced by R_FindShader(), and RE_RegisterShaderFromImage().
static shader_t* GeneratePermanentShader (void) static
GeneratePermanentShader.
Returns
Definition at line 4948 of file tr_shader.c.
Referenced by FinishShader().
void GeneratePermanentShaderTable (float * values, int numValues)
GeneratePermanentShaderTable.
Parameters
[in] values
[in] numValues
Definition at line 5012 of file tr_shader.c.
Referenced by ScanAndLoadShaderFilesR1().
static int GetOpPrecedence (opcode_t oc) static
GetOpPrecedence.
Parameters
[in] oc
Returns
Definition at line 331 of file tr_shader.c.
Referenced by ParseExpression().
static void GetOpType (const char * token, expOperation_t * op) static
GetOpType.
Parameters
[in] token
[out] op
Definition at line 213 of file tr_shader.c.
Referenced by ParseExpression().
static qboolean IsOperand (opcode_t oc) static
IsOperand.
Parameters
[in] oc
Returns
Definition at line 260 of file tr_shader.c.
Referenced by ParseExpression().
static qboolean IsOperator (opcode_t oc) static
IsOperator.
Parameters
[in] oc
Returns
Definition at line 301 of file tr_shader.c.
Referenced by ParseExpression().
qboolean LoadMap (shaderStage_t * stage, char * buffer)
LoadMap.
Parameters
[in,out] stage
[in] buffer
Returns
Todo:
:returning qfalse here if you dont have the new textures and r_materialscan is set to 3,
Todo:
& test)
Todo:
: image file name has to be including extension, we use tga - make this more generic one day
Todo:
: image file name has to be including extension, we use tga - make this more generic one day
Definition at line 1498 of file tr_shader.c.
Referenced by FinishShader(), ParseDiffuseMap(), ParseGlowMap(), ParseLightFalloffImage(), ParseNormalMap(), ParseReflectionMap(), ParseReflectionMapBlended(), ParseSpecularMap(), and ParseStage().
static unsigned NameToAFunc (const char * funcname) static
NameToAFunc.
Parameters
[in] funcname
Definition at line 836 of file tr_shader.c.
Referenced by ParseStage().
static int NameToDstBlendMode (const char * name) static
NameToDstBlendMode.
Parameters
[in] name
Returns
Definition at line 908 of file tr_shader.c.
Referenced by ParseStage().
static genFunc_t NameToGenFunc (const char * funcname) static
NameToGenFunc.
Parameters
[in] funcname
Returns
Definition at line 952 of file tr_shader.c.
Referenced by ParseTexMod(), and ParseWaveForm().
static int NameToSrcBlendMode (const char * name) static
NameToSrcBlendMode.
Parameters
[in] name
Returns
Definition at line 860 of file tr_shader.c.
Referenced by ParseStage().
static int NameToStencilOp (const char * name) static
NameToStencilOp.
Parameters
[in] name
Returns
Definition at line 988 of file tr_shader.c.
Referenced by ParseStencil().
void ParseDeform (char ** text)
ParseDeform.
Parameters
[in,out] text
Note
deformVertexes wave <spread> <waveform> <base> <amplitude> <phase> <frequency> deformVertexes normal <frequency> <amplitude> deformVertexes move <vector> <waveform> <base> <amplitude> <phase> <frequency> deformVertexes bulge <bulgeWidth> <bulgeHeight> <bulgeSpeed> deformVertexes projectionShadow deformVertexes autoSprite deformVertexes autoSprite2 deformVertexes text[0-7]
Definition at line 2843 of file tr_shader.c.
Referenced by ParseShader().
void ParseDiffuseMap (shaderStage_t * stage, char ** text)
ParseDiffuseMap.
Parameters
[in,out] stage
[in,out] text
Definition at line 3284 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
static void ParseExpression (char ** text, expression_t * exp) static
ParseExpression.
Parameters
[in,out] text
[out] exp
Definition at line 608 of file tr_shader.c.
Referenced by ParseStage(), and R_ShaderExp_f().
static char* ParseExpressionElement (char ** data_p) static
ParseExpressionElement.
Parameters
[in,out] data_p
Returns
Definition at line 368 of file tr_shader.c.
Referenced by ParseExpression().
void ParseGlowMap (shaderStage_t * stage, char ** text)
ParseGlowMap.
Parameters
[in,out] stage
[in,out] text
Definition at line 3363 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
void ParseLightFalloffImage (shaderStage_t * stage, char ** text)
ParseLightFalloffImage.
Parameters
[in,out] stage
[in,out] text
Definition at line 3427 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
static qboolean ParseMap (shaderStage_t * stage, char ** text, char * buffer, size_t bufferSize) static
ParseMap.
Parameters
stage - unused
[in,out] text
[out] buffer
[in] bufferSize
Returns
Definition at line 1456 of file tr_shader.c.
Referenced by ParseDiffuseMap(), ParseGlowMap(), ParseLightFalloffImage(), ParseNormalMap(), ParseReflectionMap(), ParseReflectionMapBlended(), ParseSpecularMap(), and ParseStage().
void ParseNormalMap (shaderStage_t * stage, char ** text)
ParseNormalMap.
Parameters
[in,out] stage
[in,out] text
Definition at line 3308 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
void ParseReflectionMap (shaderStage_t * stage, char ** text)
ParseReflectionMap.
Parameters
[in,out] stage
[in,out] text
Definition at line 3383 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
void ParseReflectionMapBlended (shaderStage_t * stage, char ** text)
ParseReflectionMapBlended.
Parameters
[in,out] stage
[in,out] text
Definition at line 3405 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
static qboolean ParseShader (char * _text) static
The current text pointer is at the explicit text definition of the shader. Parse it into the global shader variable. Later functions will optimize it.
Parameters
[in,out] _text
Returns
Todo:
Definition at line 3767 of file tr_shader.c.
Referenced by R_FindShader().
void ParseSkyParms (char ** text)
ParseSkyParms.
Parameters
[in,out] text
Note
skyParms <outerbox> <cloudheight> <innerbox>
Definition at line 3009 of file tr_shader.c.
Referenced by ParseShader().
void ParseSort (char ** text)
ParseSort.
Parameters
[in,out] text
Definition at line 3075 of file tr_shader.c.
void ParseSpecularMap (shaderStage_t * stage, char ** text)
ParseSpecularMap.
Parameters
[in,out] stage
[in,out] text
Definition at line 3339 of file tr_shader.c.
Referenced by ParseShader(), and ParseShaderR1().
qboolean ParseStage (shaderStage_t * stage, char ** text)
ParseStage.
Parameters
[in,out] stage
[in,out] text
Returns
Definition at line 1667 of file tr_shader.c.
Referenced by ParseShader().
void ParseStencil (char ** text, stencil_t * stencil)
ParseStencil.
Parameters
[in,out] text
[in,out] stencil
Definition at line 1026 of file tr_shader.c.
Referenced by ParseStage().
void ParseSurfaceParm (char ** text)
ParseSurfaceParm.
Parameters
[in,out] text
Definition at line 3271 of file tr_shader.c.
Referenced by ParseShader().
qboolean ParseTexMod (char ** text, shaderStage_t * stage)
ParseTexMod.
Parameters
[in,out] text
[in,out] stage
Returns
Definition at line 1218 of file tr_shader.c.
Referenced by ParseStage().
static qboolean ParseVector (char ** text, int count, float * v) static
ParseVector.
Parameters
[in,out] text
[in] count
[out] v
Returns
FIXME? genuine r2 ParseVector did use COM_ParseExt2 for this. Currently I don't know why this doesn't work for r1 revert to COM_ParseExt2 in r2?
Definition at line 124 of file tr_shader.c.
Referenced by ParseShader(), and ParseStage().
void ParseWaveForm (char ** text, waveForm_t * wave)
ParseWaveForm.
Parameters
[in,out] text
[out] wave
Definition at line 1166 of file tr_shader.c.
Referenced by ParseDeform(), and ParseStage().
shader_t* R_FindShader (const char * name, shaderType_t type, qboolean mipRawImage)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
In the interest of not requiring an explicit shader text entry to be defined for every single image used in the game, three default shader behaviors can be auto-created for any image:
If type == SHADER_2D, then the image will be used for 2D rendering unless an explicit shader is found
If type == SHADER_3D_DYNAMIC, then the image will have dynamic diffuse lighting applied to it, as apropriate for most entity skin surfaces.
If type == SHADER_3D_STATIC, then the image will use the vertex rgba modulate values, as apropriate for misc_model pre-lit surfaces.
Parameters
[in] name
[in] type
[in] mipRawImage
Returns
Todo:
should be attenuationZImage
Todo:
: remove and add/merge r_genNormalMaps
Todo:
: image file name has to be including extension, we use tga - make this more generic one day
Todo:
: image file name has to be including extension, we use tga - make this more generic one day
Definition at line 5638 of file tr_shader.c.
shader_t* R_FindShaderByName (const char * name)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
Parameters
[in] name
Returns
Definition at line 5580 of file tr_shader.c.
shader_t* R_GetShaderByHandle (qhandle_t hShader)
When a handle is passed in by another module, this range checks it and returns a valid (possibly default) shader_t to be used internally.
Parameters
[in] hShader
Returns
Todo:
name
Definition at line 6088 of file tr_shader.c.
void R_InitShaders (void)
R_InitShaders.
Definition at line 7010 of file tr_shader.c.
void R_RemapShader (const char * shaderName, const char * newShaderName, const char * timeOffset)
R_RemapShader.
Parameters
[in] shaderName
[in] newShaderName
timeOffset
Definition at line 56 of file tr_shader.c.
void R_ShaderExp_f (void)
R_ShaderExp_f.
Definition at line 6330 of file tr_shader.c.
Referenced by R_Register().
void R_ShaderList_f (void)
Dump information on all valid shaders to the console A second parameter will cause it to print in sorted order.
Definition at line 6107 of file tr_shader.c.
qboolean RE_LoadDynamicShader (const char * shadername, const char * shadertext)
Load a new dynamic shader. If shadertext is NULL, looks for matching shadername and removes it.
load a new dynamic shader if shadertext is NULL, looks for matching shadername and removes it
Parameters
[in] shadername
[in] shadertext
Returns
qtrue if request was successful, qfalse if the gods were angered
Definition at line 5335 of file tr_shader.c.
qhandle_t RE_RegisterShader (const char * name)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
This should really only be used for explicit shaders, because there is no way to ask for different implicit lighting modes (vertex, lightmap, etc)
Parameters
[in] name
Returns
Definition at line 5994 of file tr_shader.c.
qhandle_t RE_RegisterShaderFromImage (const char * name, image_t * image, qboolean mipRawImage)
RE_RegisterShaderFromImage.
Parameters
[in] name
[in] image
mipRawImage - unused
Returns
Definition at line 5930 of file tr_shader.c.
qhandle_t RE_RegisterShaderLightAttenuation (const char * name)
For different Doom3 style light effects.
Parameters
[in] name
Returns
Definition at line 6056 of file tr_shader.c.
Referenced by GetRefAPI(), and R_LoadLights().
qhandle_t RE_RegisterShaderNoMip (const char * name)
For menu graphics that should never be picmiped.
RE_RegisterShaderNoMip.
Parameters
[in] name
Returns
Definition at line 6025 of file tr_shader.c.
static int ScanAndLoadShaderFiles (void) static
Finds and loads all .guide files, combining them into a single large text block that can be scanned for shader template names NOTE not used static void ScanAndLoadGuideFiles(void) { char **guideFiles; char *buffers[MAX_GUIDE_FILES]; char *p; int numGuides, i; char *oldp, *token; char **hashMem; int guideTextHashTableSizes[MAX_GUIDETEXT_HASH], hash, fileSum; unsigned int size; char filename[MAX_QPATH]; long sum = 0;.
s_guideText = NULL; Com_Memset(guideTextHashTableSizes, 0, sizeof(guideTextHashTableSizes)); Com_Memset(guideTextHashTable, 0, sizeof(guideTextHashTable));
scan for guide files guideFiles = ri.FS_ListFiles("guides", ".guide", &numGuides);
Ren_Print("----- ScanAndLoadGuideFiles (%i files) -----\n", numGuides);
if (!guideFiles || !numGuides) { Ren_Developer("WARNING: no shader guide files found\n"); return; }
if (numGuides > MAX_GUIDE_FILES) { Ren_Warning("WARNING: ScanAndLoadGuideFiles: MAX_GUIDE_FILES reached\n"); numGuides = MAX_GUIDE_FILES; }
build single large buffer for (i = 0; i < numGuides; i++) { Com_sprintf(filename, sizeof(filename), "guides/%s", guideFiles[i]);
fileSum = ri.FS_ReadFile(filename, NULL); if (fileSum > 0) { sum += fileSum; } else { Ren_Drop("Couldn't load %s (single buffer)", filename); } } s_guideText = (char *)ri.Hunk_Alloc(sum + numGuides * 2, h_low);
load in reverse order, so doubled templates are overriden properly for (i = numGuides - 1; i >= 0; i–) { Com_sprintf(filename, sizeof(filename), "guides/%s", guideFiles[i]);
Ren_Developer("...loading '%s'\n", filename); sum += ri.FS_ReadFile(filename, (void **)&buffers[i]); if (!buffers[i]) { Ren_Drop("Couldn't load %s (buffer)", filename); // in theory this shouldn't occure anymore - see build single large buffer }
strcat(s_guideText, "\n"); p = &s_guideText[strlen(s_guideText)]; strcat(s_guideText, buffers[i]); ri.FS_FreeFile(buffers[i]); buffers[i] = p; COM_Compress(p); }
size = 0; for (i = 0; i < numGuides; i++) { Com_sprintf(filename, sizeof(filename), "guides/%s", guideFiles[i]);
COM_BeginParseSession(filename);
pointer to the first shader file p = buffers[i];
look for label while (1) { token = COM_ParseExt2(&p, qtrue); if (token[0] == 0) { break; }
if (Q_stricmp(token, "guide") && Q_stricmp(token, "inlineGuide")) { Ren_Warning("expected guide or inlineGuide found '%s'\n", token); break; }
parse guide name token = COM_ParseExt2(&p, qtrue);
Ren_Print("guide: '%s'\n", token);
        hash = generateHashValue(token, MAX_GUIDETEXT_HASH);
        guideTextHashTableSizes[hash]++;
        size++;
skip parameters token = COM_ParseExt2(&p, qtrue); if (Q_stricmp(token, "(")) { Ren_Warning("expected (found '%s'\n", token); break; }
while (1) { token = COM_ParseExt2(&p, qtrue);
if (!token[0]) { break; }
if (!Q_stricmp(token, ")")) { break; } }
if (Q_stricmp(token, ")")) { Ren_Warning("expected) found '%s'\n", token); break; }
skip guide body SkipBracedSection(&p);
if we passed the pointer to the next shader file if (i < numGuides - 1) { if (p > buffers[i + 1]) { break; } } } }
size += MAX_GUIDETEXT_HASH;
hashMem = (char **)ri.Hunk_Alloc(size * sizeof(char*), h_low);
for (i = 0; i < MAX_GUIDETEXT_HASH; i++) { guideTextHashTable[i] = hashMem; hashMem += guideTextHashTableSizes[i] + 1; }
Com_Memset(guideTextHashTableSizes, 0, sizeof(guideTextHashTableSizes));
for (i = 0; i < numGuides; i++) { Com_sprintf(filename, sizeof(filename), "guides/%s", guideFiles[i]);
COM_BeginParseSession(filename);
pointer to the first shader file p = buffers[i];
look for label while (1) { token = COM_ParseExt2(&p, qtrue); if (token[0] == 0) { break; }
if (Q_stricmp(token, "guide") && Q_stricmp(token, "inlineGuide")) { Ren_Warning("expected guide or inlineGuide found '%s'\n", token); break; }
parse guide name oldp = p; token = COM_ParseExt2(&p, qtrue);
Ren_Print("...hashing guide '%s'\n", token);
        hash                                                      = generateHashValue(token, MAX_GUIDETEXT_HASH);
        guideTextHashTable[hash][guideTextHashTableSizes[hash]++] = oldp;
skip parameters token = COM_ParseExt2(&p, qtrue); if (Q_stricmp(token, "(")) { Ren_Warning("expected (found '%s'\n", token); break; }
while (1) { token = COM_ParseExt2(&p, qtrue);
if (!token[0]) { break; }
if (!Q_stricmp(token, ")")) { break; } }
if (Q_stricmp(token, ")")) { Ren_Warning("expected) found '%s'\n", token); break; }
skip guide body SkipBracedSection(&p);
if we passed the pointer to the next shader file if (i < numGuides - 1) { if (p > buffers[i + 1]) { break; } } } }
free up memory ri.FS_FreeFileList(guideFiles); }
/** Finds and loads all .shader files, combining them into a single large text block that can be scanned for shader names
Returns
numShaderFiles/numMaterialFiles
Definition at line 6613 of file tr_shader.c.
static void SortNewShader (void) static
Positions the most recently created shader in the tr.sortedShaders[] array so that the shader->sort key is sorted reletive to the other shaders.
Note
Sets shader->sortedIndex
Definition at line 4925 of file tr_shader.c.
Referenced by GeneratePermanentShader().
qboolean SurfaceParm (const char * token)
SurfaceParm.
Parameters
[in,out] token
Returns
Note
surfaceparm <name>
Definition at line 3243 of file tr_shader.c.
Referenced by ParseShader(), ParseShaderR1(), and ParseSurfaceParm().
Variable Documentation
char** guideTextHashTable[MAX_GUIDETEXT_HASH] static
Definition at line 41 of file tr_shader.c.
Referenced by FindGuideInGuideText().
infoParm_t infoParms[]
Definition at line 3162 of file tr_shader.c.
int numMaterialFiles static
Definition at line 47 of file tr_shader.c.
Referenced by R_FindShader().
int numShaderFiles static
Definition at line 48 of file tr_shader.c.
Referenced by R_FindShader(), and ScanAndLoadShaderFilesR1().
const opstring_t opStrings[]
Definition at line 157 of file tr_shader.c.
Referenced by RB_EvalExpression().
char* s_guideText static
Definition at line 44 of file tr_shader.c.
Referenced by FindGuideInGuideText().
char* s_shaderText static
Definition at line 45 of file tr_shader.c.
Referenced by FindShaderInShaderText().
char** shaderTextHashTable[MAX_SHADERTEXT_HASH] static
Definition at line 42 of file tr_shader.c.
Referenced by FindShaderInShaderText().