ET: Legacy: src/renderer2/tr_curve.c File Reference
tr_curve.c File Reference
This file does all of the processing necessary to turn a raw grid of points read from the map file into a srfGridMesh_t ready for rendering.
#include "tr_local.h"
Functions
static void LerpSurfaceVert (srfVert_t *a, srfVert_t *b, srfVert_t *out)
LerpSurfaceVert.
static void Transpose (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE])
Transpose.
static void MakeMeshNormals (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE])
Handles all the complicated wrapping and degenerate cases.
static void MakeMeshTangentVectors (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], int numTriangles, srfTriangle_t triangles[SHADER_MAX_TRIANGLES])
MakeMeshTangentVectors.
static int MakeMeshTriangles (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], srfTriangle_t triangles[SHADER_MAX_TRIANGLES])
MakeMeshTriangles.
static void InvertCtrl (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE])
InvertCtrl.
static void InvertErrorTable (float errorTable[2][MAX_GRID_SIZE], int width, int height)
InvertErrorTable.
static void PutPointsOnCurve (srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], int width, int height)
PutPointsOnCurve.
static srfGridMesh_t * R_CreateSurfaceGridMesh (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], float errorTable[2][MAX_GRID_SIZE], int numTriangles, srfTriangle_t triangles[SHADER_MAX_TRIANGLES])
R_CreateSurfaceGridMesh.
void R_FreeSurfaceGridMesh (srfGridMesh_t *grid)
R_FreeSurfaceGridMesh.
srfGridMesh_t * R_SubdividePatchToGrid (int width, int height, srfVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
R_SubdividePatchToGrid.
srfGridMesh_t * R_GridInsertColumn (srfGridMesh_t *grid, int column, int row, vec3_t point, float loderror)
R_GridInsertColumn.
srfGridMesh_t * R_GridInsertRow (srfGridMesh_t *grid, int row, int column, vec3_t point, float loderror)
R_GridInsertRow.
Detailed Description
This file does all of the processing necessary to turn a raw grid of points read from the map file into a srfGridMesh_t ready for rendering.
The level of detail solution is direction independent, based only on subdivided distance from the true curve.
Only a single entry point: R_SubdividePatchToGrid(int width, int height, srfVert_t points[MAX_PATCH_SIZE*MAX_PATCH_SIZE])
Definition in file tr_curve.c.
Function Documentation
static void InvertCtrl (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE]) static
InvertCtrl.
Parameters
[in] width
[in] height
[in,out] ctrl
Definition at line 540 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().
static void InvertErrorTable (float errorTable[2][MAX_GRID_SIZE], int width, int height) static
InvertErrorTable.
Parameters
[out] errorTable
[in] width
[in] height
Definition at line 562 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().
static void LerpSurfaceVert (srfVert_t * a, srfVert_t * b, srfVert_t * out) static
LerpSurfaceVert.
Parameters
[in] a
[in] b
[out] out
Definition at line 53 of file tr_curve.c.
Referenced by PutPointsOnCurve(), R_GridInsertColumn(), R_GridInsertRow(), and R_SubdividePatchToGrid().
static void MakeMeshNormals (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE]) static
Handles all the complicated wrapping and degenerate cases.
Parameters
[in] width
[in] height
[in,out] ctrl
Definition at line 153 of file tr_curve.c.
Referenced by R_GridInsertColumn(), R_GridInsertRow(), and R_SubdividePatchToGrid().
static void MakeMeshTangentVectors (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], int numTriangles, srfTriangle_t triangles[SHADER_MAX_TRIANGLES]) static
MakeMeshTangentVectors.
Parameters
[in] width
[in] height
[in] ctrl
[in] numTriangles
[in] triangles
Todo:
: use more elegant way
Definition at line 278 of file tr_curve.c.
Referenced by R_GridInsertColumn(), R_GridInsertRow(), and R_SubdividePatchToGrid().
static int MakeMeshTriangles (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], srfTriangle_t triangles[SHADER_MAX_TRIANGLES]) static
MakeMeshTriangles.
Parameters
[in] width
[in] height
[in] ctrl
[out] triangles
Returns
Todo:
: use more elegant way
Definition at line 364 of file tr_curve.c.
Referenced by R_GridInsertColumn(), R_GridInsertRow(), and R_SubdividePatchToGrid().
static void PutPointsOnCurve (srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], int width, int height) static
PutPointsOnCurve.
Parameters
[in] ctrl
[in] width
[in] height
Definition at line 586 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().
static srfGridMesh_t* R_CreateSurfaceGridMesh (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], float errorTable[2][MAX_GRID_SIZE], int numTriangles, srfTriangle_t triangles[SHADER_MAX_TRIANGLES]) static
R_CreateSurfaceGridMesh.
Parameters
[in] width
[in] height
[in] ctrl
[out] errorTable
[in] numTriangles
[out] triangles
Returns
Definition at line 622 of file tr_curve.c.
void R_FreeSurfaceGridMesh (srfGridMesh_t * grid)
R_FreeSurfaceGridMesh.
Parameters
[in] grid
Definition at line 703 of file tr_curve.c.
srfGridMesh_t* R_GridInsertColumn (srfGridMesh_t * grid, int column, int row, vec3_t point, float loderror)
R_GridInsertColumn.
Parameters
[in,out] grid
[in] column
[in] row
[in] point
[in] loderror
Returns
Definition at line 915 of file tr_curve.c.
srfGridMesh_t* R_GridInsertRow (srfGridMesh_t * grid, int row, int column, vec3_t point, float loderror)
R_GridInsertRow.
Parameters
[in,out] grid
[in] row
[in] column
[in] point
[in] loderror
Returns
Definition at line 992 of file tr_curve.c.
srfGridMesh_t* R_SubdividePatchToGrid (int width, int height, srfVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
R_SubdividePatchToGrid.
Parameters
[in] width
[in] height
[in] points
Returns
Todo:
: also check midpoints of adjacent patches against the control points
Definition at line 719 of file tr_curve.c.
static void Transpose (int width, int height, srfVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE]) static
Transpose.
Parameters
[in] width
[in] height
[in,out] ctrl
Definition at line 98 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().