ET: Legacy: src/game/bg_sscript.c File Reference
bg_sscript.c File Reference
#include "../qcommon/q_shared.h"
#include "bg_public.h"
Macros
#define MAX_SCRIPTSPEAKERS 256
Functions
void BG_ClearScriptSpeakerPool (void)
BG_ClearScriptSpeakerPool.
int BG_NumScriptSpeakers (void)
BG_NumScriptSpeakers.
int BG_GetIndexForSpeaker (bg_speaker_t *speaker)
BG_GetIndexForSpeaker.
bg_speaker_t * BG_GetScriptSpeaker (int index)
BG_GetScriptSpeaker.
qboolean BG_SS_DeleteSpeaker (int index)
BG_SS_DeleteSpeaker.
qboolean BG_SS_StoreSpeaker (bg_speaker_t *speaker)
BG_SS_StoreSpeaker.
static qboolean BG_SS_ParseError (int handle, char *format,...)
BG_SS_ParseError.
static qboolean BG_SS_ParseSpeaker (int handle)
BG_SS_ParseSpeaker.
qboolean BG_LoadSpeakerScript (const char *filename)
BG_LoadSpeakerScript.
Variables
static bg_speaker_t scriptSpeakers [MAX_SCRIPTSPEAKERS]
static int numScriptSpeakers
Macro Definition Documentation
#define MAX_SCRIPTSPEAKERS 256
Definition at line 38 of file bg_sscript.c.
Referenced by BG_SS_StoreSpeaker().
Function Documentation
void BG_ClearScriptSpeakerPool (void)
BG_ClearScriptSpeakerPool.
Definition at line 46 of file bg_sscript.c.
Referenced by CG_RegisterSounds(), and G_InitGame().
int BG_GetIndexForSpeaker (bg_speaker_t * speaker)
BG_GetIndexForSpeaker.
Parameters
[in] speaker
Returns
Definition at line 65 of file bg_sscript.c.
Referenced by CG_ModifyEditSpeaker(), and CG_SpeakerEditor_Delete_KeyUp().
bg_speaker_t* BG_GetScriptSpeaker (int index)
BG_GetScriptSpeaker.
Parameters
[in] index
Returns
Definition at line 75 of file bg_sscript.c.
Referenced by CG_AddScriptSpeakers(), CG_RegisterSounds(), CG_RenderScriptSpeakers(), CG_SaveSpeakersToScript(), CG_SetActiveOnScriptSpeaker(), CG_ToggleActiveOnScriptSpeaker(), CG_UndoEditSpeaker(), CG_UnsetActiveOnScriptSpeaker(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), and G_ScriptAction_ToggleSpeaker().
qboolean BG_LoadSpeakerScript (const char * filename)
BG_LoadSpeakerScript.
Parameters
[in] filename
Returns
Definition at line 323 of file bg_sscript.c.
Referenced by CG_RegisterSounds(), and G_InitGame().
int BG_NumScriptSpeakers (void)
BG_NumScriptSpeakers.
Returns
Definition at line 55 of file bg_sscript.c.
Referenced by CG_AddScriptSpeakers(), CG_RegisterSounds(), CG_RenderScriptSpeakers(), CG_SaveSpeakersToScript(), CG_SpeakerEditorDraw(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), and G_ScriptAction_ToggleSpeaker().
qboolean BG_SS_DeleteSpeaker (int index)
BG_SS_DeleteSpeaker.
Parameters
[in] index
Returns
Definition at line 90 of file bg_sscript.c.
Referenced by CG_SpeakerEditor_Delete_KeyUp().
static qboolean BG_SS_ParseError (int handle, char * format, ...) static
BG_SS_ParseError.
Parameters
[in] handle
[in] format
Returns
Definition at line 128 of file bg_sscript.c.
Referenced by BG_LoadSpeakerScript(), and BG_SS_ParseSpeaker().
static qboolean BG_SS_ParseSpeaker (int handle) static
BG_SS_ParseSpeaker.
Parameters
[in] handle
Returns
Definition at line 155 of file bg_sscript.c.
Referenced by BG_LoadSpeakerScript().
qboolean BG_SS_StoreSpeaker (bg_speaker_t * speaker)
BG_SS_StoreSpeaker.
Parameters
[in] speaker
Returns
Definition at line 109 of file bg_sscript.c.
Referenced by BG_SS_ParseSpeaker(), CG_DumpSpeaker_f(), and CG_UndoEditSpeaker().
Variable Documentation
int numScriptSpeakers static
Definition at line 41 of file bg_sscript.c.
Referenced by BG_ClearScriptSpeakerPool(), BG_GetScriptSpeaker(), BG_NumScriptSpeakers(), BG_SS_DeleteSpeaker(), and BG_SS_StoreSpeaker().
bg_speaker_t scriptSpeakers[MAX_SCRIPTSPEAKERS] static
Definition at line 40 of file bg_sscript.c.
Referenced by BG_GetIndexForSpeaker().