ET: Legacy: src/game/bg_tracemap.c File Reference
bg_tracemap.c File Reference
Map tracemap view generation.
#include "g_local.h"
Data Structures
struct tracemap_s
Macros
#define MAX_WORLD_HEIGHT MAX_MAP_SIZE
#define MIN_WORLD_HEIGHT -MAX_MAP_SIZE
#define TRACEMAP_SIZE 256
Typedefs
typedef struct tracemap_s tracemap_t
Functions
void etpro_FinalizeTracemapClamp (int *x, int *y)
Re-clamp the points, because a rounding error can cause them to go outside the array.
qboolean BG_LoadTraceMap (char *rawmapname, vec2_t world_mins, vec2_t world_maxs)
BG_LoadTraceMap.
static void BG_ClampPointToTracemapExtends (vec3_t point, vec2_t out)
BG_ClampPointToTracemapExtends.
float BG_GetSkyHeightAtPoint (vec3_t pos)
BG_GetSkyHeightAtPoint.
float BG_GetSkyGroundHeightAtPoint (vec3_t pos)
BG_GetSkyGroundHeightAtPoint.
float BG_GetGroundHeightAtPoint (vec3_t pos)
int BG_GetTracemapGroundFloor (void)
BG_GetTracemapGroundFloor.
int BG_GetTracemapGroundCeil (void)
BG_GetTracemapGroundCeil.
int BG_GetTracemapSkyGroundFloor (void)
BG_GetTracemapSkyGroundFloor.
int BG_GetTracemapSkyGroundCeil (void)
BG_GetTracemapSkyGroundCeil.
Variables
static tracemap_t tracemap
static vec2_t one_over_mapgrid_factor
Detailed Description
Map tracemap view generation.
Definition in file bg_tracemap.c.
Macro Definition Documentation
#define MAX_WORLD_HEIGHT MAX_MAP_SIZE
Definition at line 42 of file bg_tracemap.c.
Referenced by BG_GetSkyGroundHeightAtPoint(), BG_GetSkyHeightAtPoint(), BG_GetTracemapGroundCeil(), BG_GetTracemapSkyGroundCeil(), and BG_LoadTraceMap().
#define MIN_WORLD_HEIGHT -MAX_MAP_SIZE
Definition at line 43 of file bg_tracemap.c.
Referenced by BG_GetGroundHeightAtPoint(), BG_GetTracemapGroundFloor(), BG_GetTracemapSkyGroundFloor(), and BG_LoadTraceMap().
#define TRACEMAP_SIZE 256
Definition at line 46 of file bg_tracemap.c.
Referenced by BG_LoadTraceMap().
Typedef Documentation
typedef struct tracemap_s tracemap_t
Function Documentation
static void BG_ClampPointToTracemapExtends (vec3_t point, vec2_t out) static
BG_ClampPointToTracemapExtends.
Parameters
[in] point
[out] out
Definition at line 813 of file bg_tracemap.c.
Referenced by BG_GetGroundHeightAtPoint(), BG_GetSkyGroundHeightAtPoint(), and BG_GetSkyHeightAtPoint().
float BG_GetGroundHeightAtPoint (vec3_t pos)
Definition at line 906 of file bg_tracemap.c.
Referenced by G_RunMissile().
float BG_GetSkyGroundHeightAtPoint (vec3_t pos)
BG_GetSkyGroundHeightAtPoint.
Parameters
[in] pos
Returns
Definition at line 879 of file bg_tracemap.c.
Referenced by CG_ParticleCheckVisible(), CG_ParticleGenerate(), and CG_ParticleRender().
float BG_GetSkyHeightAtPoint (vec3_t pos)
BG_GetSkyHeightAtPoint.
Parameters
[in] pos
Returns
Definition at line 847 of file bg_tracemap.c.
Referenced by artillerySpotterThink(), CG_ParticleGenerate(), G_AirStrikeThink(), G_RunMissile(), Weapon_Artillery(), and weapon_callAirStrike().
int BG_GetTracemapGroundCeil (void)
BG_GetTracemapGroundCeil.
Returns
Definition at line 950 of file bg_tracemap.c.
int BG_GetTracemapGroundFloor (void)
BG_GetTracemapGroundFloor.
Returns
Definition at line 937 of file bg_tracemap.c.
Referenced by G_RunMissile().
int BG_GetTracemapSkyGroundCeil (void)
BG_GetTracemapSkyGroundCeil.
Returns
Definition at line 976 of file bg_tracemap.c.
Referenced by weapon_callAirStrike().
int BG_GetTracemapSkyGroundFloor (void)
BG_GetTracemapSkyGroundFloor.
Returns
Definition at line 963 of file bg_tracemap.c.
Referenced by weapon_callAirStrike().
qboolean BG_LoadTraceMap (char * rawmapname, vec2_t world_mins, vec2_t world_maxs)
BG_LoadTraceMap.
< CGAMEDLL
Parameters
[in] rawmapname
[in] world_mins
[in] world_maxs
Returns
Todo:
: swap
Todo:
: swap
Todo:
: swap
Definition at line 584 of file bg_tracemap.c.
Referenced by CG_EffectParse(), and G_InitGame().
void etpro_FinalizeTracemapClamp (int * x, int * y)
Re-clamp the points, because a rounding error can cause them to go outside the array.
Parameters
[in,out] x
[in,out] y
Definition at line 991 of file bg_tracemap.c.
Referenced by BG_GetGroundHeightAtPoint(), BG_GetSkyGroundHeightAtPoint(), and BG_GetSkyHeightAtPoint().
Variable Documentation
vec2_t one_over_mapgrid_factor static
Definition at line 61 of file bg_tracemap.c.
Referenced by BG_GetGroundHeightAtPoint(), BG_GetSkyGroundHeightAtPoint(), BG_GetSkyHeightAtPoint(), and BG_LoadTraceMap().
tracemap_t tracemap static
Definition at line 59 of file bg_tracemap.c.