ET: Legacy: src/game/bg_misc.c File Reference
bg_misc.c File Reference
Both games misc functions, all completely stateless.
#include "../qcommon/q_shared.h"
#include "bg_public.h"
#include "../../etmain/ui/menudef.h"
Data Structures
struct colorTable_t
struct locInfo_s
Macros
#define DELAY_LOW 100
machineguns, tesla, spear, flame
#define DELAY_HIGH 100
mauser, garand
#define DELAY_PISTOL 100
colt, luger, sp5, cross
#define DELAY_SHOULDER 50
rl
#define DELAY_THROW 250
grenades, dynamite
#define DELAY_HW 750
heavy weapon
#define SETUP_MOUNTEDGUN_STATUS(ps)
Typedefs
typedef struct locInfo_s locInfo_t
Functions
qboolean BG_AkimboFireSequence (int weapon, int akimboClip, int mainClip)
BG_AkimboFireSequence.
gitem_t * BG_GetItem (int index)
BG_GetItem.
gitem_t * BG_FindItem (const char *pickupName)
BG_FindItem.
gitem_t * BG_FindItemForClassName (const char *className)
BG_FindItemForClassName.
qboolean BG_PlayerTouchesItem (playerState_t *ps, entityState_t *item, int atTime)
Items can be picked up without actually touching their physical bounds to make grabbing them easier.
qboolean BG_AddMagicAmmo (playerState_t *ps, int *skill, team_t teamNum, int numOfClips)
Setting numOfClips = 0 allows you to check if the client needs ammo, but doesnt give any.
qboolean BG_CanItemBeGrabbed (const entityState_t *ent, const playerState_t *ps, int *skill, team_t teamNum)
This needs to be the same for client side prediction and server use.
void BG_CalculateSpline_r (splinePath_t *spline, vec3_t out1, vec3_t out2, float tension)
BG_CalculateSpline_r.
qboolean BG_TraverseSpline (float *deltaTime, splinePath_t **pSpline)
BG_TraverseSpline.
qboolean BG_RaySphereIntersection (float radius, vec3_t origin, splineSegment_t *path, float *t0, float *t1)
BG_RaySphereIntersection.
void BG_LinearPathOrigin2 (float radius, splinePath_t **pSpline, float *deltaTime, vec3_t result, qboolean backwards)
BG_LinearPathOrigin2.
void BG_ComputeSegments (splinePath_t *pSpline)
void BG_EvaluateTrajectory (const trajectory_t *tr, int atTime, vec3_t result, qboolean isAngle, int splinePath)
BG_EvaluateTrajectory.
void BG_EvaluateTrajectoryDelta (const trajectory_t *tr, int atTime, vec3_t result, qboolean isAngle, int splineData)
For determining velocity at a given time.
void BG_GetMarkDir (const vec3_t dir, const vec3_t normal, vec3_t out)
Used to find a good directional vector for a mark projection, which will be more likely to wrap around adjacent surfaces.
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t *ps)
Handles the sequence numbers.
void BG_PlayerStateToEntityState (playerState_t *ps, entityState_t *s, int time, qboolean snap)
This is done after each set of usercmd_t on the server, and after local prediction on the client.
pathCorner_t * BG_Find_PathCorner (const char *match)
BG_Find_PathCorner.
void BG_AddPathCorner (const char *name, vec3_t origin)
BG_AddPathCorner.
splinePath_t * BG_Find_Spline (const char *match)
BG_Find_Spline.
splinePath_t * BG_AddSplinePath (const char *name, const char *target, vec3_t origin)
BG_AddSplinePath.
void BG_AddSplineControl (splinePath_t *spline, const char *name)
BG_AddSplineControl.
float BG_SplineLength (splinePath_t *pSpline)
BG_SplineLength.
void BG_BuildSplinePaths (void)
BG_BuildSplinePaths.
splinePath_t * BG_GetSplineData (int number, qboolean *backwards)
BG_GetSplineData.
int BG_MaxAmmoForWeapon (weapon_t weaponNum, const int *skill, int cls)
BG_MaxAmmoForWeapon.
void BG_AdjustAAGunMuzzleForBarrel (vec_t *origin, vec_t *forward, vec_t *right, vec_t *up, int barrel)
BG_AdjustAAGunMuzzleForBarrel.
void PC_SourceError (int handle, const char *format,...)
PC_SourceError.
qboolean PC_Float_Parse (int handle, float *f)
PC_Float_Parse.
qboolean PC_Color_Parse (int handle, vec4_t *c)
PC_Color_Parse.
qboolean PC_Vec_Parse (int handle, vec3_t *c)
PC_Vec_Parse.
qboolean PC_Point_Parse (int handle, vec2_t *c)
PC_Point_Parse.
qboolean PC_Int_Parse (int handle, int *i)
PC_Int_Parse.
qboolean PC_String_Parse (int handle, const char **out)
PC_String_Parse.
qboolean PC_String_ParseNoAlloc (int handle, char *out, size_t size)
Same as PC_String_Parse, but uses a static buff and not the string memory pool.
int BG_simpleWeaponState (int ws)
Multiview: Convert weaponstate to simpler format.
void trap_Cvar_Set (const char *var_name, const char *value)
trap_Cvar_Set
void BG_setCrosshair (char *colString, float *col, float alpha, const char *cvarName)
BG_setCrosshair.
void BG_InitLocations (vec2_t world_mins, vec2_t world_maxs)
BG_InitLocations.
char * BG_GetLocationString (float xpos, float ypos)
BG_GetLocationString.
qboolean BG_BBoxCollision (vec3_t min1, vec3_t max1, vec3_t min2, vec3_t max2)
BG_BBoxCollision.
int BG_FootstepForSurface (int surfaceFlags)
BG_FootstepForSurface.
int BG_SurfaceForFootstep (int surfaceFlags)
BG_SurfaceForFootstep.
Variables
skilltable_t skillTable [SK_NUM_SKILLS]
New skill table [0] = skill - [1] = skillNames - [2] = skillNamesLine1 - NOTE: Unused [3] = skillNamesLine2 - NOTE: Unused [4] = medalNames - NOTE: Unused [5] = skillLevels -.
sysMessage_t HQMessages [SM_NUM_SYS_MSGS]
vec3_t playerlegsProneMins = { -13.5f, -13.5f, -24.f }
vec3_t playerlegsProneMaxs = { 13.5f, 13.5f, -14.4f }
int numSplinePaths
splinePath_t splinePaths [MAX_SPLINE_PATHS]
int numPathCorners
pathCorner_t pathCorners [MAX_PATH_CORNERS]
weaponTable_t weaponTable [WP_NUM_WEAPONS]
New weapon table to store common weapon properties: [0] = weapon - reference [1] = item - [2] = team - [3] = skillBased - [4] = weapAlts - [5] = weapEquiv - the id of the opposite team's weapon (but not for WP_GPG40 <-> WP_M7 - see CG_OutOfAmmoChange). [6] = akimboSideArm - [7] = ammoIndex - type of weapon ammo this uses [8] = clipIndex - which clip this weapon uses. This allows the sniper rifle to use the same clip as the garand, etc. [9] = damage - returns 1 for no damage, return 0 for no explode on contact ... FIXME: some weapons are handled differently f.e. VERYBIGEXPLOSION [10] = spread - [11] = spreadScale - [12] = splashDamage - [13] = splashRadius - [14] = type - [15] = fireMode - [16] = attributes - [17] = zoomOut - [18] = zoomIn - [19] = zoomedScope - [20] = desc - [21] = indexWeaponStat - [22] = useAmmo - [23] = useClip - [24] = maxAmmo - max player ammo carrying capacity. [25] = uses - how many 'rounds' it takes/costs to fire one cycle. [26] = maxClip - max 'rounds' in a clip. [27] = reloadTime - time from start of reload until ready to fire. [28] = fireDelayTime - time from pressing 'fire' until first shot is fired. (used for delaying fire while weapon is 'readied' in animation) [29] = nextShotTime - when firing continuously, this is the time between shots [30] = grenadeTime - [31] = aimSpreadScaleAdd - [32] = maxHeat - max active firing time before weapon 'overheats' (at which point the weapon will fail for a moment) [33] = coolRate - how fast the weapon cools down. [34] = heatRecoveryTime - time from overheats until weapon can fire again [35] = switchTimeBegin - [36] = switchTimeFinish - [37] = altSwitchTimeBegin - [38] = altSwitchTimeFinish - [39] = knockback - [40] = weapRecoilDuration - [41] = weapRecoilPitch - [42] = weapRecoilYaw - [43] = className - [44] = weapFile - [45] = chargeTimeCoeff - [46] = mod - means of death. [47] = splashMod - splash means of death.
modTable_t modTable [MOD_NUM_MODS]
New weapon table for mod properties: [0] = mod - mean of death [1] = weaponIcon - [2] = isHeadshot - [3] = isExplosive - [4] = weaponClassForMOD - [5] = noYellMedic - don't yell medic [6] = obituaryKillMessage1 - [7] = obituaryKillMessage2 - [8] = obituarySelfKillMessage - [9] = obituaryNoAttackerMessage - [10] = modName - these are just for logging, the client prints its own messages [11] = defaultKillPoints - [12] = splashKillPoints - [13] = localizedKillPoints - [14] = isLocalisedDamage - [15] = indexWeaponStat -.
gitem_t bg_itemlist []
QUAKED item_***** (0 0 0) (-16 -16 -16) (16 16 16) SUSPENDED SPIN PERSISTANT DO NOT USE THIS CLASS, IT JUST HOLDS GENERAL INFORMATION. SUSPENDED - will allow items to hang in the air, otherwise they are dropped to the next surface. SPIN - will allow items to spin in place. PERSISTANT - some items (ex. clipboards) can be picked up, but don't disappear.
const char * eventnames [EV_MAX_EVENTS]
ranktable_t rankTable [2][NUM_EXPERIENCE_LEVELS]
New rank table [0] = names - rank name [1] = miniNames - mini rank name [2] = soundNames - sound to play on rank promotion.
const char * bg_fireteamNamesAllies [MAX_FIRETEAMS/2]
const char * bg_fireteamNamesAxis [MAX_FIRETEAMS/2]
const voteType_t voteToggles []
int numVotesAvailable = sizeof(voteToggles) / sizeof(voteType_t)
const int aReinfSeeds [MAX_REINFSEEDS] = { 11, 3, 13, 7, 2, 5, 1, 17 }
const weap_ws_t aWeaponInfo [WS_MAX]
const colorTable_t OSP_Colortable []
static locInfo_t locInfo
static char coord [6]
Detailed Description
Both games misc functions, all completely stateless.
Definition in file bg_misc.c.
Macro Definition Documentation
#define DELAY_HIGH 100
mauser, garand
Definition at line 95 of file bg_misc.c.
#define DELAY_HW 750
heavy weapon
Definition at line 99 of file bg_misc.c.
#define DELAY_LOW 100
machineguns, tesla, spear, flame
Definition at line 94 of file bg_misc.c.
#define DELAY_PISTOL 100
colt, luger, sp5, cross
Definition at line 96 of file bg_misc.c.
#define DELAY_SHOULDER 50
rl
Definition at line 97 of file bg_misc.c.
#define DELAY_THROW 250
grenades, dynamite
Definition at line 98 of file bg_misc.c.
#define SETUP_MOUNTEDGUN_STATUS (ps)
Value:
switch (ps->persistant[PERS_HWEAPON_USE]) {                \
    case 1:                                                 \
        ps->eFlags                    |= EF_MG42_ACTIVE;                       \
        ps->eFlags                    &= ~EF_AAGUN_ACTIVE;                     \
        ps->powerups[PW_OPS_DISGUISED] = 0;                 \
        break;                                              \
    case 2:                                                 \
        ps->eFlags                    |= EF_AAGUN_ACTIVE;                      \
        ps->eFlags                    &= ~EF_MG42_ACTIVE;                      \
        ps->powerups[PW_OPS_DISGUISED] = 0;                 \
        break;                                              \
    default:                                                \
        ps->eFlags &= ~EF_MG42_ACTIVE;                      \
        ps->eFlags &= ~EF_AAGUN_ACTIVE;                     \
        break;                                              \
    }
Definition at line 3635 of file bg_misc.c.
Referenced by BG_PlayerStateToEntityState().
Typedef Documentation
typedef struct locInfo_s locInfo_t
Function Documentation
qboolean BG_AddMagicAmmo (playerState_t * ps, int * skill, team_t teamNum, int numOfClips)
Setting numOfClips = 0 allows you to check if the client needs ammo, but doesnt give any.
if numOfClips is 0, no ammo is added, it just return whether any ammo CAN be added otherwise return whether any ammo was ACTUALLY added. WARNING: when numOfClips is 0, DO NOT CHANGE ANYTHING under ps.
Parameters
[in,out] ps
[in] skill
[in] teamNum
[in] numOfClips
Returns
Definition at line 2556 of file bg_misc.c.
Referenced by AddMagicAmmo(), and BG_CanItemBeGrabbed().
void BG_AddPathCorner (const char * name, vec3_t origin)
BG_AddPathCorner.
Parameters
[in] name
[in] origin
Definition at line 3863 of file bg_misc.c.
Referenced by SP_path_corner_2().
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t * ps)
Handles the sequence numbers.
Parameters
[in] newEvent
[in] eventParm
[out] ps
Definition at line 3613 of file bg_misc.c.
Referenced by G_AddPredictableEvent(), PM_AddEvent(), and PM_AddEventExt().
void BG_AddSplineControl (splinePath_t * spline, const char * name)
BG_AddSplineControl.
Parameters
[in,out] spline
[in] name
Definition at line 3932 of file bg_misc.c.
Referenced by SP_info_train_spline_main().
splinePath_t* BG_AddSplinePath (const char * name, const char * target, vec3_t origin)
BG_AddSplinePath.
Parameters
[in] name
[in] target
[in] origin
Returns
Definition at line 3902 of file bg_misc.c.
Referenced by SP_info_train_spline_main().
void BG_AdjustAAGunMuzzleForBarrel (vec_t * origin, vec_t * forward, vec_t * right, vec_t * up, int barrel)
BG_AdjustAAGunMuzzleForBarrel.
Parameters
[in,out] origin
[in] forward
[in] right
[in] up
[in] barrel
Definition at line 4160 of file bg_misc.c.
Referenced by aagun_fire(), and CG_CalcMuzzlePoint().
qboolean BG_AkimboFireSequence (int weapon, int akimboClip, int mainClip)
BG_AkimboFireSequence.
Parameters
[in] weapon
[in] akimboClip
[in] mainClip
Returns
'true' if it's the left hand's turn to fire, 'false' if it's the right hand's turn
Definition at line 2438 of file bg_misc.c.
Referenced by PM_Weapon(), PM_WeaponAmmoAvailable(), and PM_WeaponUseAmmo().
qboolean BG_BBoxCollision (vec3_t min1, vec3_t max1, vec3_t min2, vec3_t max2)
BG_BBoxCollision.
Parameters
[in] min1
[in] max1
[in] min2
[in] max2
Returns
Definition at line 4791 of file bg_misc.c.
Referenced by CG_TouchTriggerPrediction().
void BG_BuildSplinePaths (void)
BG_BuildSplinePaths.
Definition at line 3988 of file bg_misc.c.
Referenced by CG_Init(), CG_MapRestart(), and G_InitGame().
void BG_CalculateSpline_r (splinePath_t * spline, vec3_t out1, vec3_t out2, float tension)
BG_CalculateSpline_r.
Parameters
[in] spline
[out] out1
[out] out2
[in] tension
Definition at line 2743 of file bg_misc.c.
Referenced by BG_ComputeSegments(), BG_EvaluateTrajectory(), and BG_SplineLength().
qboolean BG_CanItemBeGrabbed (const entityState_t * ent, const playerState_t * ps, int * skill, team_t teamNum)
This needs to be the same for client side prediction and server use.
Parameters
[in] ent
[in] ps
[in] skill
[in] teamNum
Returns
false if the item should not be picked up.
Definition at line 2652 of file bg_misc.c.
Referenced by ETInterface::InterfaceSendMessage(), and Touch_Item().
void BG_ComputeSegments (splinePath_t * pSpline)
Definition at line 3000 of file bg_misc.c.
Referenced by BG_BuildSplinePaths().
void BG_EvaluateTrajectory (const trajectory_t * tr, int atTime, vec3_t result, qboolean isAngle, int splinePath)
BG_EvaluateTrajectory.
Parameters
[in] tr
[in] atTime
[out] result
[in] isAngle
[in] splinePath
Todo:
: local gravity...
Todo:
: local gravity...
Todo:
: case not handle
Definition at line 3030 of file bg_misc.c.
Referenced by aagun_think(), BG_PlayerTouchesItem(), CG_AddBloodElements(), CG_AddDebris(), CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), CG_AddEntityToTag(), CG_AddFragment(), CG_AddFuseSparkElements(), CG_AddMoveScaleFade(), CG_AddMovingTracer(), CG_AddSparkElements(), CG_AdjustPositionForMover(), CG_Beam_2(), CG_BloodTrail(), CG_CalcEntityLerpPositions(), CG_CalcViewValues(), CG_CheckEvents(), CG_ClipMoveToEntities(), CG_DynamiteTrail(), CG_GrenadeTrail(), CG_InterpolateEntityPosition(), CG_PlayerSeesItem(), CG_PyroSmokeTrail(), CG_ResetPlayerEntity(), CG_RocketTrail(), CG_TransitionEntity(), G_MoverTeam(), G_PredictBounceMissile(), G_PredictMissile(), G_RunEntity(), G_RunItem(), G_RunMissile(), G_ScriptAction_AbortMove(), G_ScriptAction_FaceAngles(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GotoMarker(), G_ScriptAction_Halt(), G_ScriptAction_SetRotation(), G_ScriptAction_SetSpeed(), G_ScriptAction_StopRotation(), mg42_think(), Props_Chair_Think(), and SetMoverState().
void BG_EvaluateTrajectoryDelta (const trajectory_t * tr, int atTime, vec3_t result, qboolean isAngle, int splineData)
For determining velocity at a given time.
Parameters
[in] tr
[in] atTime
[out] result
[in] isAngle - unused
[in] splineData - unused
Todo:
: local gravity...
Todo:
: local gravity...
Todo:
: phase is never read
Todo:
: case not handle
Definition at line 3332 of file bg_misc.c.
Referenced by CG_Missile(), CG_ReflectVelocity(), G_BounceItem(), G_BounceMissile(), G_MissileImpact(), and G_PredictBounceMissile().
pathCorner_t* BG_Find_PathCorner (const char * match)
BG_Find_PathCorner.
Parameters
[in] match
Returns
Definition at line 3843 of file bg_misc.c.
Referenced by BG_BuildSplinePaths(), G_ScriptAction_GotoMarker(), and G_ScriptAction_SetPosition().
splinePath_t* BG_Find_Spline (const char * match)
BG_Find_Spline.
Parameters
[in] match
Returns
Definition at line 3880 of file bg_misc.c.
Referenced by BG_BuildSplinePaths(), G_ScriptAction_FollowPath(), and G_ScriptAction_FollowSpline().
gitem_t* BG_FindItem (const char * pickupName)
BG_FindItem.
Parameters
[in] pickupName
Returns
Definition at line 2482 of file bg_misc.c.
Referenced by misc_spawner_think(), and props_locker_spawn_item().
gitem_t* BG_FindItemForClassName (const char * className)
BG_FindItemForClassName.
Parameters
[in] className
Returns
Definition at line 2502 of file bg_misc.c.
Referenced by G_CallSpawn().
int BG_FootstepForSurface (int surfaceFlags)
BG_FootstepForSurface.
Parameters
[in] surfaceFlags
Returns
Definition at line 4817 of file bg_misc.c.
Referenced by G_MissileImpact(), and PM_FootstepForSurface().
gitem_t* BG_GetItem (int index)
BG_GetItem.
Parameters
[in] index
Returns
Definition at line 2472 of file bg_misc.c.
Referenced by BG_CanItemBeGrabbed(), BG_InitWeaponStrings(), CG_EntityEvent(), CG_Item(), CG_ItemPickup(), CG_PickupItemText(), CG_RegisterItemSounds(), CG_RegisterItemVisuals(), G_DropItems(), G_DropWeapon(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
char* BG_GetLocationString (float xpos, float ypos)
BG_GetLocationString.
Parameters
[in] xpos
[in] ypos
Returns
Definition at line 4762 of file bg_misc.c.
Referenced by CG_BuildLocationString().
void BG_GetMarkDir (const vec3_t dir, const vec3_t normal, vec3_t out)
Used to find a good directional vector for a mark projection, which will be more likely to wrap around adjacent surfaces.
Parameters
[in] dir The direction of the projectile or trace that has resulted in a surface being hit
[in] normal
[out] out
Definition at line 3414 of file bg_misc.c.
Referenced by CG_GibPlayer(), and G_MissileImpact().
splinePath_t* BG_GetSplineData (int number, qboolean * backwards)
BG_GetSplineData.
Parameters
[in] number
[out] backwards
Returns
Definition at line 4049 of file bg_misc.c.
Referenced by BG_EvaluateTrajectory(), CG_AddLinkedEntity(), and G_TagLinkEntity().
void BG_InitLocations (vec2_t world_mins, vec2_t world_maxs)
BG_InitLocations.
Parameters
[in] world_mins
[in] world_maxs
Definition at line 4734 of file bg_misc.c.
Referenced by SP_worldspawn().
void BG_LinearPathOrigin2 (float radius, splinePath_t ** pSpline, float * deltaTime, vec3_t result, qboolean backwards)
BG_LinearPathOrigin2.
Parameters
[in] radius
[in,out] pSpline
[in] deltaTime
[out] result
[out] backwards - unused
Definition at line 2858 of file bg_misc.c.
Referenced by BG_EvaluateTrajectory(), CG_AddLinkedEntity(), and G_TagLinkEntity().
int BG_MaxAmmoForWeapon (weapon_t weaponNum, const int * skill, int cls)
BG_MaxAmmoForWeapon.
Parameters
[in] weaponNum
[in] skill
[in] class
Returns
Todo:
: this is class dependant, not ammo table
Definition at line 4077 of file bg_misc.c.
Referenced by Add_Ammo(), BG_AddMagicAmmo(), and ETInterface::GetCurrentAmmo().
void BG_PlayerStateToEntityState (playerState_t * ps, entityState_t * s, int time, qboolean snap)
This is done after each set of usercmd_t on the server, and after local prediction on the client.
Parameters
[in] ps
[out] s
[in] time
[in] snap
Definition at line 3661 of file bg_misc.c.
Referenced by _et_G_XP_Set(), CG_AddPacketEntities(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), clamp_playerbehindgun(), ClientEndFrame(), ClientSpawn(), ClientThink_real(), and TeleportPlayer().
qboolean BG_PlayerTouchesItem (playerState_t * ps, entityState_t * item, int atTime)
Items can be picked up without actually touching their physical bounds to make grabbing them easier.
Parameters
[in] ps
[in] item
[in] atTime
Returns
Definition at line 2525 of file bg_misc.c.
Referenced by G_TouchTriggers().
qboolean BG_RaySphereIntersection (float radius, vec3_t origin, splineSegment_t * path, float * t0, float * t1)
BG_RaySphereIntersection.
Parameters
[in] radius
[in] origin
[in] path
[out] t0
[out] t1
Returns
Definition at line 2827 of file bg_misc.c.
Referenced by BG_LinearPathOrigin2().
void BG_setCrosshair (char * colString, float * col, float alpha, const char * cvarName)
BG_setCrosshair.
Parameters
[in] colString
[in] col
[in] alpha
[in] cvarName
Definition at line 4678 of file bg_misc.c.
Referenced by CG_RegisterCvars(), CG_UpdateCvars(), UI_RegisterCvars(), and UI_UpdateCvars().
int BG_simpleWeaponState (int ws)
Multiview: Convert weaponstate to simpler format.
Parameters
[in] ws
Returns
Definition at line 4535 of file bg_misc.c.
Referenced by CG_DrawGunIcon().
float BG_SplineLength (splinePath_t * pSpline)
BG_SplineLength.
Parameters
[in] pSpline
Returns
Definition at line 3949 of file bg_misc.c.
Referenced by BG_BuildSplinePaths().
int BG_SurfaceForFootstep (int surfaceFlags)
BG_SurfaceForFootstep.
Parameters
[in] surfaceFlags
Returns
Definition at line 4872 of file bg_misc.c.
Referenced by CG_EntityEvent().
qboolean BG_TraverseSpline (float * deltaTime, splinePath_t ** pSpline)
BG_TraverseSpline.
Parameters
[in] deltaTime
[in,out] pSpline
Returns
Definition at line 2782 of file bg_misc.c.
Referenced by BG_EvaluateTrajectory().
qboolean PC_Color_Parse (int handle, vec4_t * c)
PC_Color_Parse.
Parameters
[in] handle
[out] c
Returns
Definition at line 4283 of file bg_misc.c.
Referenced by Asset_Parse(), ItemParse_outlinecolor(), MenuParse_outlinecolor(), and ParseColorRange().
qboolean PC_Float_Parse (int handle, float * f)
PC_Float_Parse.
Parameters
[in] handle
[out] f
Returns
Definition at line 4244 of file bg_misc.c.
Referenced by Asset_Parse(), CG_RectParse(), CG_RW_ParseClient(), ItemParse_backcolor(), ItemParse_bordercolor(), ItemParse_bordersize(), ItemParse_cvarFloat(), ItemParse_cvarFloatList(), ItemParse_elementheight(), ItemParse_elementwidth(), ItemParse_forecolor(), ItemParse_model_fovx(), ItemParse_model_fovy(), ItemParse_model_origin(), ItemParse_scrollColor(), ItemParse_sliderColor(), ItemParse_textalignx(), ItemParse_textaligny(), ItemParse_textscale(), ItemParse_tooltipalignx(), ItemParse_tooltipaligny(), MenuParse_backcolor(), MenuParse_bordercolor(), MenuParse_borderSize(), MenuParse_disablecolor(), MenuParse_fadeAmount(), MenuParse_fadeClamp(), MenuParse_focuscolor(), MenuParse_forecolor(), ParseColorRange(), PC_Color_Parse(), PC_Point_Parse(), PC_Rect_Parse(), PC_Vec_Parse(), and UI_LoadArenasFromFile().
qboolean PC_Int_Parse (int handle, int * i)
PC_Int_Parse.
Parameters
[in] handle
[out] i
Returns
Definition at line 4349 of file bg_misc.c.
Referenced by Asset_Parse(), BG_RAG_ParseAnimation(), BG_SS_ParseSpeaker(), CG_FindArenaInfo(), CG_LoadObjectiveData(), CG_ParseHUD(), CG_ParseHudComponent(), CG_RW_ParseClient(), CG_RW_ParseModModel(), CG_RW_ParseWeaponLinkPart(), ItemParse_align(), ItemParse_bitflag(), ItemParse_border(), ItemParse_columns(), ItemParse_elementtype(), ItemParse_feeder(), ItemParse_maxChars(), ItemParse_maxPaintChars(), ItemParse_model_angle(), ItemParse_model_animplay(), ItemParse_model_rotation(), ItemParse_origin(), ItemParse_ownerdraw(), ItemParse_ownerdrawFlag(), ItemParse_settingDisabled(), ItemParse_settingEnabled(), ItemParse_special(), ItemParse_style(), ItemParse_textalign(), ItemParse_textfont(), ItemParse_textstyle(), ItemParse_type(), ItemParse_visible(), ItemParse_voteFlag(), MenuParse_border(), MenuParse_execKeyInt(), MenuParse_fadeCycle(), MenuParse_fullscreen(), MenuParse_itemHotkeyMode(), MenuParse_onTimeout(), MenuParse_ownerdraw(), MenuParse_ownerdrawFlag(), MenuParse_style(), MenuParse_visible(), and UI_LoadArenasFromFile().
qboolean PC_Point_Parse (int handle, vec2_t * c)
PC_Point_Parse.
Parameters
[in] handle
[out] c
Returns
Definition at line 4327 of file bg_misc.c.
Referenced by CG_RW_ParseClient().
void PC_SourceError (int handle, const char * format, ...)
PC_SourceError.
Parameters
[in] handle
[in] format
Definition at line 4216 of file bg_misc.c.
Referenced by Item_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), Menu_Parse(), ParseColorRange(), PC_Float_Parse(), and PC_Int_Parse().
qboolean PC_String_Parse (int handle, const char ** out)
PC_String_Parse.
Parameters
[in] handle
[out] out
Returns
Definition at line 4407 of file bg_misc.c.
Referenced by Asset_Parse(), CG_FindArenaInfo(), G_LoadCampaignsFromFile(), ItemParse_asset_model(), ItemParse_asset_shader(), ItemParse_background(), ItemParse_cinematic(), ItemParse_contextMenu(), ItemParse_cvar(), ItemParse_cvarFloat(), ItemParse_cvarTest(), ItemParse_focusSound(), ItemParse_group(), ItemParse_name(), MenuParse_background(), MenuParse_cinematic(), MenuParse_name(), MenuParse_soundLoop(), PC_Int_Parse(), UI_LoadArenasFromFile(), and UI_LoadCampaignsFromFile().
qboolean PC_String_ParseNoAlloc (int handle, char * out, size_t size)
Same as PC_String_Parse, but uses a static buff and not the string memory pool.
Parameters
handle
out
size
Returns
Definition at line 4428 of file bg_misc.c.
Referenced by BG_ParseCharacterFile(), BG_SS_ParseSpeaker(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), CG_RW_ParseModModel(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLinkPart(), CG_RW_ParseWeaponSound(), G_configLoadAndSet(), and G_ParseSettings().
qboolean PC_Vec_Parse (int handle, vec3_t * c)
PC_Vec_Parse.
Parameters
[in] handle
[out] c
Returns
Definition at line 4305 of file bg_misc.c.
Referenced by BG_SS_ParseSpeaker(), and CG_RW_ParseClient().
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 122 of file cg_syscalls.c.
Referenced by BG_setCrosshair().
Variable Documentation
const int aReinfSeeds[MAX_REINFSEEDS] = { 11, 3, 13, 7, 2, 5, 1, 17 }
Definition at line 4496 of file bg_misc.c.
Referenced by CG_ParseReinforcementTimes(), and G_loadMatchGame().
const weap_ws_t aWeaponInfo[WS_MAX]
Initial value:
=
{
    { qfalse, "KNIF", "Knife"      },
    { qfalse, "KNKB", "Ka-Bar"     },
    { qtrue,  "LUGR", "Luger"      },
    { qtrue,  "COLT", "Colt"       },
    { qtrue,  "MP40", "MP 40"      },
    { qtrue,  "TMPS", "Thompson"   },
    { qtrue,  "STEN", "Sten"       },
    { qtrue,  "FG42", "FG 42"      },
    { qfalse, "PNZR", "Panzer"     },
    { qfalse, "BZKA", "Bazooka"    },
    { qfalse, "FLAM", "F.Thrower"  },
    { qfalse, "GRND", "Grenade"    },
    { qfalse, "MRTR", "Mortar"     },
    { qfalse, "GRWF", "Granatwerf" },
    { qfalse, "DYNA", "Dynamite"   },
    { qfalse, "ARST", "Airstrike"  },
    { qfalse, "ARTY", "Artillery"  },
    { qfalse, "STCH", "Satchel"    },
    { qfalse, "GRLN", "G.Launchr"  },
    { qfalse, "LNMN", "Landmine"   },
    { qfalse, "MG42", "MG 42 Gun"  },
    { qfalse, "BRNG", "Browning"   },
    { qtrue,  "GARN", "Garand"     },
    { qtrue,  "K-43", "K43 Rifle"  },
    { qtrue,  "SGRN", "Scp.Garand" },
    { qtrue,  "SK43", "Scp.K43"    },
    { qtrue,  "MP34", "MP 34"      }
}
Definition at line 4499 of file bg_misc.c.
Referenced by CG_DebriefingPlayerWeaponStats_Draw(), CG_parseBestShotsStats_cmd(), CG_parseTopShotsStats_cmd(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_topshotsParse_cmd(), G_CalcClientAccuracies(), and G_weaponRankings_cmd().
const char* bg_fireteamNamesAllies[MAX_FIRETEAMS/2]
Initial value:
=
{
    "Able",
    "Baker",
    "Charlie",
    "Dog",
    "Easy",
    "Fox",
}
Definition at line 4442 of file bg_misc.c.
Referenced by CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), and G_FireteamNumberForString().
const char* bg_fireteamNamesAxis[MAX_FIRETEAMS/2]
Initial value:
=
{
    "Anton",
    "Bruno",
    "Casar",
    "Dora",
    "Emil",
    "Fritz",
}
Definition at line 4453 of file bg_misc.c.
Referenced by CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), and G_FireteamNumberForString().
bg_itemlist
QUAKED item_***** (0 0 0) (-16 -16 -16) (16 16 16) SUSPENDED SPIN PERSISTANT DO NOT USE THIS CLASS, IT JUST HOLDS GENERAL INFORMATION. SUSPENDED - will allow items to hang in the air, otherwise they are dropped to the next surface. SPIN - will allow items to spin in place. PERSISTANT - some items (ex. clipboards) can be picked up, but don't disappear.
If an item is the target of another entity, it will not spawn in until fired.
An item fires all of its targets when it is picked up. If the toucher can't carry it, the targets won't be fired.
"notfree" if set to 1, don't spawn in free for all games "notteam" if set to 1, don't spawn in team games "notsingle" if set to 1, don't spawn in single player games "wait" override the default wait before respawning. -1 = never respawn automatically, which can be used with targeted spawning. "random" random number of plus or minus seconds varied from the respawn time "count" override quantity or duration on most items. "stand" if the item has a stand (ex: mp40_stand.md3) this specifies which stand tag to attach the weapon to ("stand":"4" would mean "tag_stand4" for example) only weapons support stands currently
Note
Important notes:
bg_itemlist has additional client members
Definition at line 521 of file bg_misc.c.
char coord[6] static
Definition at line 4754 of file bg_misc.c.
Referenced by BG_GetLocationString().
const char* eventnames[EV_MAX_EVENTS]
Definition at line 3467 of file bg_misc.c.
Referenced by BG_AddPredictableEventToPlayerstate(), CG_EntityEvent(), and Svcmd_EntityList_f().
sysMessage_t HQMessages[SM_NUM_SYS_MSGS]
Initial value:
=
{
    { "SYS_NeedMedic",         "_hq_need_medic",          "^7(HQ): ^3We need a Medic!"            },
    { "SYS_NeedEngineer",      "_hq_need_engineer",       "^7(HQ): ^3We need an Engineer!"        },
    { "SYS_NeedFieldops",      "_hq_need_fieldops",       "^7(HQ): ^3We need an Field Ops!"       },
    { "SYS_NeedCovertOps",     "_hq_need_covertops",      "^7(HQ): ^3We need an Covert Ops!"      },
    { "SYS_MenDown",           "_hq_men_down",            "^7(HQ): ^3We've lost most of our men!" },
    { "SYS_ObjCaptured",       "_hq_objective_captured",  "^7(HQ): ^3Objective captured!"         },
    { "SYS_ObjLost",           "_hq_objective_lost",      "^7(HQ): ^3Objective lost!"             },
    { "SYS_ObjDestroyed",      "_hq_objective_destroyed", "^7(HQ): ^3Objective destroyed!"        },
    { "SYS_ConstructComplete", "_hq_const_completed",     "^7(HQ): ^3Construction complete!"      },
    { "SYS_ConstructFailed",   "_hq_const_failed",        "^7(HQ): ^3Construction failed!"        },
    { "SYS_Destroyed",         "_hq_const_destroyed",     "^7(HQ): ^3Construction destroyed!"     },
}
Definition at line 69 of file bg_misc.c.
Referenced by CG_ServerCommand(), and G_GetSysMessageNumber().
locInfo_t locInfo static
Definition at line 4727 of file bg_misc.c.
modTable
New weapon table for mod properties: [0] = mod - mean of death [1] = weaponIcon - [2] = isHeadshot - [3] = isExplosive - [4] = weaponClassForMOD - [5] = noYellMedic - don't yell medic [6] = obituaryKillMessage1 - [7] = obituaryKillMessage2 - [8] = obituarySelfKillMessage - [9] = obituaryNoAttackerMessage - [10] = modName - these are just for logging, the client prints its own messages [11] = defaultKillPoints - [12] = splashKillPoints - [13] = localizedKillPoints - [14] = isLocalisedDamage - [15] = indexWeaponStat -.
Note
WIP
Todo:
FIXME: add client side properties
Definition at line 244 of file bg_misc.c.
int numPathCorners
Definition at line 90 of file bg_misc.c.
Referenced by BG_AddPathCorner(), BG_Find_PathCorner(), CG_MapRestart(), CG_RegisterGraphics(), G_InitGame(), and SP_path_corner_2().
int numSplinePaths
Definition at line 87 of file bg_misc.c.
Referenced by BG_AddSplinePath(), BG_BuildSplinePaths(), BG_Find_Spline(), BG_GetSplineData(), CG_MapRestart(), CG_RegisterGraphics(), and G_InitGame().
int numVotesAvailable = sizeof(voteToggles) / sizeof(voteType_t)
Definition at line 4493 of file bg_misc.c.
Referenced by G_voteFlags().
const colorTable_t OSP_Colortable[]
Initial value:
=
{
    { "white",    &colorWhite    },
    { "red",      &colorRed      },
    { "green",    &colorGreen    },
    { "blue",     &colorBlue     },
    { "yellow",   &colorYellow   },
    { "magenta",  &colorMagenta  },
    { "cyan",     &colorCyan     },
    { "orange",   &colorOrange   },
    { "mdred",    &colorMdRed    },
    { "mdgreen",  &colorMdGreen  },
    { "dkgreen",  &colorDkGreen  },
    { "mdcyan",   &colorMdCyan   },
    { "mdyellow", &colorMdYellow },
    { "mdorange", &colorMdOrange },
    { "mdblue",   &colorMdBlue   },
    { "ltgrey",   &colorLtGrey   },
    { "mdgrey",   &colorMdGrey   },
    { "dkgrey",   &colorDkGrey   },
    { "black",    &colorBlack    },
    { NULL,       NULL           }
}
Definition at line 4646 of file bg_misc.c.
pathCorner_t pathCorners[MAX_PATH_CORNERS]
Definition at line 91 of file bg_misc.c.
vec3_t playerlegsProneMaxs = { 13.5f, 13.5f, -14.4f }
Definition at line 85 of file bg_misc.c.
Referenced by CG_Player(), G_BuildLeg(), G_TestEntityPosition(), and PM_TraceLegs().
vec3_t playerlegsProneMins = { -13.5f, -13.5f, -24.f }
Definition at line 84 of file bg_misc.c.
Referenced by CG_Player(), G_BuildLeg(), G_TestEntityPosition(), and PM_TraceLegs().
rankTable
New rank table [0] = names - rank name [1] = miniNames - mini rank name [2] = soundNames - sound to play on rank promotion.
Definition at line 3803 of file bg_misc.c.
skillTable
Initial value:
=
{
    { SK_BATTLE_SENSE,                             "Battle Sense",  "Battle",       "Sense",        "Distinguished Service Medal", { 0, 20, 50, 90, 140 },},
    { SK_EXPLOSIVES_AND_CONSTRUCTION,              "Engineering",   "Engineering",  "",             "Steel Star",                  { 0, 20, 50, 90, 140 },},
    { SK_FIRST_AID,                                "First Aid",     "First",        "Aid",          "Silver Cross",                { 0, 20, 50, 90, 140 },},
    { SK_SIGNALS,                                  "Signals",       "Signals",      "",             "Signals Medal",               { 0, 20, 50, 90, 140 },},
    { SK_LIGHT_WEAPONS,                            "Light Weapons", "Light",        "Weapons",      "Infantry Medal",              { 0, 20, 50, 90, 140 },},
    { SK_HEAVY_WEAPONS,                            "Heavy Weapons", "Heavy",        "Weapons",      "Bombardment Medal",           { 0, 20, 50, 90, 140 },},
    { SK_MILITARY_INTELLIGENCE_AND_SCOPED_WEAPONS, "Covert Ops",    "Covert",       "Ops",          "Silver Snake",                { 0, 20, 50, 90, 140 },},
}
New skill table [0] = skill - [1] = skillNames - [2] = skillNamesLine1 - NOTE: Unused [3] = skillNamesLine2 - NOTE: Unused [4] = medalNames - NOTE: Unused [5] = skillLevels -.
Definition at line 56 of file bg_misc.c.
splinePath_t splinePaths[MAX_SPLINE_PATHS]
Definition at line 88 of file bg_misc.c.
Referenced by G_ScriptAction_FollowPath(), and G_ScriptAction_FollowSpline().
const voteType_t voteToggles[]
Initial value:
=
{
    { "vote_allow_config",                   CV_SVF_CONFIG                   },
    { "vote_allow_gametype",                 CV_SVF_GAMETYPE                 },
    { "vote_allow_kick",                     CV_SVF_KICK                     },
    { "vote_allow_map",                      CV_SVF_MAP                      },
    { "vote_allow_matchreset",               CV_SVF_MATCHRESET               },
    { "vote_allow_mutespecs",                CV_SVF_MUTESPECS                },
    { "vote_allow_nextmap",                  CV_SVF_NEXTMAP                  },
    { "vote_allow_referee",                  CV_SVF_REFEREE                  },
    { "vote_allow_shuffleteamsxp",           CV_SVF_SHUFFLETEAMSXP           },
    { "vote_allow_shuffleteamsxp_norestart", CV_SVF_SHUFFLETEAMSXP_NORESTART },
    { "vote_allow_swapteams",                CV_SVF_SWAPTEAMS                },
    { "vote_allow_friendlyfire",             CV_SVF_FRIENDLYFIRE             },
    { "vote_allow_timelimit",                CV_SVF_TIMELIMIT                },
    { "vote_allow_warmupdamage",             CV_SVF_WARMUPDAMAGE             },
    { "vote_allow_antilag",                  CV_SVF_ANTILAG                  },
    { "vote_allow_balancedteams",            CV_SVF_BALANCEDTEAMS            },
    { "vote_allow_muting",                   CV_SVF_MUTING                   },
    { "vote_allow_surrender",                CV_SVF_SURRENDER                },
    { "vote_allow_restartcampaign",          CV_SVF_RESTARTCAMPAIGN          },
    { "vote_allow_nextcampaign",             CV_SVF_NEXTCAMPAIGN             },
    { "vote_allow_poll",                     CV_SVF_POLL                     },
    { "vote_allow_maprestart",               CV_SVF_MAPRESTART               }
}
Definition at line 4463 of file bg_misc.c.
Referenced by G_voteFlags().
weaponTable
New weapon table to store common weapon properties: [0] = weapon - reference [1] = item - [2] = team - [3] = skillBased - [4] = weapAlts - [5] = weapEquiv - the id of the opposite team's weapon (but not for WP_GPG40 <-> WP_M7 - see CG_OutOfAmmoChange). [6] = akimboSideArm - [7] = ammoIndex - type of weapon ammo this uses [8] = clipIndex - which clip this weapon uses. This allows the sniper rifle to use the same clip as the garand, etc. [9] = damage - returns 1 for no damage, return 0 for no explode on contact ... FIXME: some weapons are handled differently f.e. VERYBIGEXPLOSION [10] = spread - [11] = spreadScale - [12] = splashDamage - [13] = splashRadius - [14] = type - [15] = fireMode - [16] = attributes - [17] = zoomOut - [18] = zoomIn - [19] = zoomedScope - [20] = desc - [21] = indexWeaponStat - [22] = useAmmo - [23] = useClip - [24] = maxAmmo - max player ammo carrying capacity. [25] = uses - how many 'rounds' it takes/costs to fire one cycle. [26] = maxClip - max 'rounds' in a clip. [27] = reloadTime - time from start of reload until ready to fire. [28] = fireDelayTime - time from pressing 'fire' until first shot is fired. (used for delaying fire while weapon is 'readied' in animation) [29] = nextShotTime - when firing continuously, this is the time between shots [30] = grenadeTime - [31] = aimSpreadScaleAdd - [32] = maxHeat - max active firing time before weapon 'overheats' (at which point the weapon will fail for a moment) [33] = coolRate - how fast the weapon cools down. [34] = heatRecoveryTime - time from overheats until weapon can fire again [35] = switchTimeBegin - [36] = switchTimeFinish - [37] = altSwitchTimeBegin - [38] = altSwitchTimeFinish - [39] = knockback - [40] = weapRecoilDuration - [41] = weapRecoilPitch - [42] = weapRecoilYaw - [43] = className - [44] = weapFile - [45] = chargeTimeCoeff - [46] = mod - means of death. [47] = splashMod - splash means of death.
Definition at line 154 of file bg_misc.c.