ET: Legacy: src/game/bg_animation.c File Reference
bg_animation.c File Reference
Incorporates several elements related to the new flexible animation system.
#include "../qcommon/q_shared.h"
#include "bg_public.h"
Data Structures
struct animConditionTable_t
Macros
#define MAX_ANIM_DEFINES 16
#define RESULT_SIZE 2
#define MAX_INDENT_LEVELS 3
Enumerations
enum animScriptConditionTypes_t { ANIM_CONDTYPE_BITFLAGS = 0, ANIM_CONDTYPE_VALUE, NUM_ANIM_CONDTYPES }
enum animScriptParseMode_t {
PARSEMODE_DEFINES = 0, PARSEMODE_ANIMATION, PARSEMODE_CANNED_ANIMATIONS, PARSEMODE_STATECHANGES,
PARSEMODE_EVENTS
}
Functions
long BG_StringHashValue (const char *fname)
BG_StringHashValue.
long BG_StringHashValue_Lwr (const char *fname)
BG_StringHashValue_Lwr.
void __attribute__ ((noreturn))
BG_AnimParseError.
static int BG_AnimationIndexForString (char *string, animModelInfo_t *animModelInfo)
BG_AnimationIndexForString.
int BG_IndexForString (char *token, animStringItem_t *strings, qboolean allowFail)
errors out if no match found
char * BG_CopyStringIntoBuffer (char *string, char *buffer, unsigned int bufSize, unsigned int *offset)
BG_CopyStringIntoBuffer.
void BG_InitWeaponStrings (void)
Builds the list of weapon names from the item list. This is done here rather than hardcoded to ease the process of modifying the weapons.
void BG_ParseConditionBits (char **text_pp, animStringItem_t *stringTable, int condIndex, int result[RESULT_SIZE])
Convert the string into a single int containing bit flags, stopping at a ',' or end of line.
qboolean BG_ParseConditions (char **text_pp, animScriptItem_t *scriptItem)
BG_ParseConditions.
static void BG_ParseCommands (char **input, animScriptItem_t *scriptItem, animModelInfo_t *animModelInfo, animScriptData_t *scriptData)
BG_ParseCommands.
void BG_AnimParseAnimScript (animModelInfo_t *animModelInfo, animScriptData_t *scriptData, const char *filename, char *input)
Parse the animation script for this model, converting it into run-time structures.
qboolean BG_EvaluateConditions (int client, animScriptItem_t *scriptItem)
BG_EvaluateConditions.
animScriptItem_t * BG_FirstValidItem (int client, animScript_t *script)
scroll through the script items, returning the first script found to pass all conditions
int BG_PlayAnim (playerState_t *ps, animModelInfo_t *animModelInfo, int animNum, animBodyPart_t bodyPart, int forceDuration, qboolean setTimer, qboolean isContinue, qboolean force)
BG_PlayAnim.
int BG_ExecuteCommand (playerState_t *ps, animModelInfo_t *animModelInfo, animScriptCommand_t *scriptCommand, qboolean setTimer, qboolean isContinue, qboolean force)
BG_ExecuteCommand.
int BG_AnimScriptAnimation (playerState_t *ps, animModelInfo_t *animModelInfo, scriptAnimMoveTypes_t movetype, qboolean isContinue)
Runs the normal locomotive animations.
int BG_AnimScriptEvent (playerState_t *ps, animModelInfo_t *animModelInfo, scriptAnimEventTypes_t event, qboolean isContinue, qboolean force)
BG_AnimScriptEvent.
char * BG_GetAnimString (animModelInfo_t *animModelInfo, int anim)
BG_GetAnimString.
void BG_UpdateConditionValue (int client, int condition, int value, qboolean checkConversion)
BG_UpdateConditionValue.
int BG_GetConditionValue (int client, int condition, qboolean checkConversion)
BG_GetConditionValue.
qboolean BG_GetConditionBitFlag (int client, int condition, int bitNumber)
BG_GetConditionBitFlag.
void BG_SetConditionBitFlag (int client, int condition, int bitNumber)
BG_SetConditionBitFlag.
void BG_ClearConditionBitFlag (int client, int condition, int bitNumber)
BG_ClearConditionBitFlag.
int BG_GetAnimScriptAnimation (int client, animModelInfo_t *animModelInfo, aistateEnum_t aistate, scriptAnimMoveTypes_t movetype)
BG_GetAnimScriptAnimation.
animation_t * BG_GetAnimationForIndex (animModelInfo_t *animModelInfo, int index)
BG_GetAnimationForIndex.
void BG_AnimUpdatePlayerStateConditions (pmove_t *pmove)
BG_AnimUpdatePlayerStateConditions.
Variables
static animScriptData_t * globalScriptData = NULL
static const char * globalFilename
static int numDefines [NUM_ANIM_CONDITIONS]
static char defineStrings [10000]
static unsigned int defineStringsOffset
static animStringItem_t defineStr [NUM_ANIM_CONDITIONS][MAX_ANIM_DEFINES]
static int defineBits [NUM_ANIM_CONDITIONS][MAX_ANIM_DEFINES][2]
static scriptAnimMoveTypes_t parseMovetype
static int parseEvent
static animStringItem_t weaponStrings [WP_NUM_WEAPONS]
animStringItem_t animStateStr []
static animStringItem_t animMoveTypesStr []
animStringItem_t animEventTypesStr []
animStringItem_t animBodyPartsStr []
static animStringItem_t animConditionPositionsStr []
static animStringItem_t animConditionMountedStr []
static animStringItem_t animConditionLeaningStr []
static animStringItem_t animConditionImpactPointsStr []
static animStringItem_t animEnemyTeamsStr []
static animStringItem_t animHealthLevelStr []
static animStringItem_t animFlailTypeStr []
static animStringItem_t animGenBitFlagStr []
static animStringItem_t animAIStateStr []
static animStringItem_t animConditionsStr [NUM_ANIM_CONDITIONS+1]
static animConditionTable_t animConditionsTable [NUM_ANIM_CONDITIONS]
static animStringItem_t animParseModesStr []
Detailed Description
Incorporates several elements related to the new flexible animation system.
This includes scripting elements, support routines for new animation set reference system and other bits and pieces.
Definition in file bg_animation.c.
Macro Definition Documentation
#define MAX_ANIM_DEFINES 16
Definition at line 58 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
#define MAX_INDENT_LEVELS 3
Definition at line 928 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
#define RESULT_SIZE 2
Definition at line 541 of file bg_animation.c.
Enumeration Type Documentation
enum animScriptConditionTypes_t
Enumerator
ANIM_CONDTYPE_BITFLAGS
ANIM_CONDTYPE_VALUE
NUM_ANIM_CONDTYPES
Definition at line 245 of file bg_animation.c.
enum animScriptParseMode_t
Enumerator
PARSEMODE_DEFINES
PARSEMODE_ANIMATION
PARSEMODE_CANNED_ANIMATIONS
PARSEMODE_STATECHANGES
PARSEMODE_EVENTS
Definition at line 908 of file bg_animation.c.
Function Documentation
void __attribute__ ((noreturn))
BG_AnimParseError.
Parameters
[in] msg
Definition at line 379 of file bg_animation.c.
Referenced by hash().
static int BG_AnimationIndexForString (char * string, animModelInfo_t * animModelInfo) static
BG_AnimationIndexForString.
Parameters
[in] string
[in] animModelInfo
Returns
Definition at line 404 of file bg_animation.c.
Referenced by BG_ParseCommands().
void BG_AnimParseAnimScript (animModelInfo_t * animModelInfo, animScriptData_t * scriptData, const char * filename, char * input)
Parse the animation script for this model, converting it into run-time structures.
Parameters
[in] animModelInfo
[in,out] scriptData
[in] filename
[in] input
Definition at line 937 of file bg_animation.c.
Referenced by CG_ParseAnimationFiles(), and G_ParseAnimationFiles().
int BG_AnimScriptAnimation (playerState_t * ps, animModelInfo_t * animModelInfo, scriptAnimMoveTypes_t movetype, qboolean isContinue)
Runs the normal locomotive animations.
Parameters
[in,out] ps
[in,out] animModelInfo
[in] movetype
[in] isContinue
Returns
1 if an animation was set, -1 if no animation was found, 0 otherwise
Definition at line 1524 of file bg_animation.c.
Referenced by PM_Footsteps(), and PmoveSingle().
int BG_AnimScriptEvent (playerState_t * ps, animModelInfo_t * animModelInfo, scriptAnimEventTypes_t event, qboolean isContinue, qboolean force)
BG_AnimScriptEvent.
Parameters
[in,out] ps
[in] animModelInfo
[in] event
[in] isContinue
[in] force
Returns
The duration in milliseconds that this model should be paused. -1 if no event found
Definition at line 1639 of file bg_animation.c.
Referenced by player_die(), PM_BeginWeaponChange(), PM_BeginWeaponReload(), PM_CheckJump(), PM_CheckLadderMove(), PM_CrashLand(), PM_FinishWeaponChange(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_MountedFire(), PM_Weapon(), ReviveEntity(), and Svcmd_Die().
void BG_AnimUpdatePlayerStateConditions (pmove_t * pmove)
BG_AnimUpdatePlayerStateConditions.
Parameters
[in] pmove
Definition at line 1933 of file bg_animation.c.
Referenced by PmoveSingle().
void BG_ClearConditionBitFlag (int client, int condition, int bitNumber)
BG_ClearConditionBitFlag.
Parameters
[in] client
[in] condition
[in] bitNumber
Definition at line 1820 of file bg_animation.c.
Referenced by BG_AnimUpdatePlayerStateConditions().
char* BG_CopyStringIntoBuffer (char * string, char * buffer, unsigned int bufSize, unsigned int * offset)
BG_CopyStringIntoBuffer.
Parameters
[in] string
[in] buffer
[in] bufSize
[in,out] offset
Returns
Definition at line 491 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
qboolean BG_EvaluateConditions (int client, animScriptItem_t * scriptItem)
BG_EvaluateConditions.
Parameters
[in] client
[in] scriptItem
Returns
qfalse if the set of conditions fails, qtrue otherwise
Definition at line 1265 of file bg_animation.c.
Referenced by BG_FirstValidItem().
int BG_ExecuteCommand (playerState_t * ps, animModelInfo_t * animModelInfo, animScriptCommand_t * scriptCommand, qboolean setTimer, qboolean isContinue, qboolean force)
BG_ExecuteCommand.
Parameters
[in,out] ps
[in] animModelInfo
[in] scriptCommand
[in] setTimer
[in] isContinue
[in] force
Returns
The duration of the animation, -1 if no anim was set
Todo:
: how to sync torso/legs anims accounting for transition blends, etc
Todo:
: how to sync torso/legs anims accounting for transition blends, etc
Definition at line 1470 of file bg_animation.c.
Referenced by BG_AnimScriptAnimation(), and BG_AnimScriptEvent().
animScriptItem_t* BG_FirstValidItem (int client, animScript_t * script)
scroll through the script items, returning the first script found to pass all conditions
Parameters
[in] client
[in] script
Returns
NULL if no match found
Definition at line 1318 of file bg_animation.c.
Referenced by BG_AnimScriptAnimation(), BG_AnimScriptEvent(), and BG_GetAnimScriptAnimation().
animation_t* BG_GetAnimationForIndex (animModelInfo_t * animModelInfo, int index)
BG_GetAnimationForIndex.
Parameters
[in] animModelInfo
[in] index
Returns
The animation_t for the given index
Definition at line 1918 of file bg_animation.c.
Referenced by CG_IsCrouchingAnim().
int BG_GetAnimScriptAnimation (int client, animModelInfo_t * animModelInfo, aistateEnum_t aistate, scriptAnimMoveTypes_t movetype)
BG_GetAnimScriptAnimation.
Parameters
[in] client
[in] animModelInfo
[in] aistate
[in] movetype
Returns
The locomotion animation index, -1 if no animation was found, 0 otherwise
Definition at line 1833 of file bg_animation.c.
Referenced by CG_PlayerAnimation().
char* BG_GetAnimString (animModelInfo_t * animModelInfo, int anim)
BG_GetAnimString.
Parameters
[in] animModelInfo
[in] anim
Returns
Definition at line 1702 of file bg_animation.c.
Referenced by CG_PlayerAngles().
qboolean BG_GetConditionBitFlag (int client, int condition, int bitNumber)
BG_GetConditionBitFlag.
Parameters
[in] client
[in] condition
[in] bitNumber
Returns
Whether the specified bit flag is set
Definition at line 1790 of file bg_animation.c.
Referenced by CG_PlayerAngles().
int BG_GetConditionValue (int client, int condition, qboolean checkConversion)
BG_GetConditionValue.
Parameters
[in] client
[in] condition
[in] checkConversion
Returns
Definition at line 1749 of file bg_animation.c.
Referenced by CG_PlayerAngles().
int BG_IndexForString (char * token, animStringItem_t * strings, qboolean allowFail)
errors out if no match found
Parameters
[in] token
[in] strings
[in] allowFail
Returns
Definition at line 457 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript(), BG_ParseCommands(), BG_ParseConditionBits(), and BG_ParseConditions().
void BG_InitWeaponStrings (void)
Builds the list of weapon names from the item list. This is done here rather than hardcoded to ease the process of modifying the weapons.
Definition at line 516 of file bg_animation.c.
Referenced by CG_RegisterGraphics(), and G_InitGame().
static void BG_ParseCommands (char ** input, animScriptItem_t * scriptItem, animModelInfo_t * animModelInfo, animScriptData_t * scriptData) static
BG_ParseCommands.
Parameters
[in] input
[in] scriptItem
[in] animModelInfo
[in] scriptData - unused
Todo:
: find the reason
Definition at line 779 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
void BG_ParseConditionBits (char ** text_pp, animStringItem_t * stringTable, int condIndex, int result[RESULT_SIZE])
Convert the string into a single int containing bit flags, stopping at a ',' or end of line.
Parameters
[in,out] text_pp
[in] stringTable
[in] condIndex
[out] result
Definition at line 549 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript(), and BG_ParseConditions().
qboolean BG_ParseConditions (char ** text_pp, animScriptItem_t * scriptItem)
BG_ParseConditions.
Parameters
[in] text_pp
[out] scriptItem
Returns
qtrue if everything went ok, error drops otherwise
Definition at line 684 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
int BG_PlayAnim (playerState_t * ps, animModelInfo_t * animModelInfo, int animNum, animBodyPart_t bodyPart, int forceDuration, qboolean setTimer, qboolean isContinue, qboolean force)
BG_PlayAnim.
Parameters
[in,out] ps
[in] animModelInfo
[in] animNum
[in] bodyPart
[in] forceDuration
[in] setTimer
[in] isContinue
[in] force
Returns
Definition at line 1371 of file bg_animation.c.
Referenced by BG_ExecuteCommand().
void BG_SetConditionBitFlag (int client, int condition, int bitNumber)
BG_SetConditionBitFlag.
Parameters
[in] client
[in] condition
[in] bitNumber
Definition at line 1809 of file bg_animation.c.
Referenced by BG_AnimUpdatePlayerStateConditions().
long BG_StringHashValue (const char * fname)
BG_StringHashValue.
Parameters
[in] fname
Returns
A hash value for the given string
Definition at line 320 of file bg_animation.c.
Referenced by BG_AnimationIndexForString(), BG_AnimParseAnimScript(), BG_IndexForString(), BG_InitWeaponStrings(), BG_RAG_ParseAnimation(), BG_SS_ParseSpeaker(), CG_ServerCommand(), checkpoint_spawntouch(), func_explosive_explode(), G_FindByTargetname(), G_ScriptAction_AlertEntity(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), G_ScriptAction_SetState(), G_ScriptAction_ToggleSpeaker(), G_SetTargetName(), G_SpawnGEntityFromSpawnVars(), and G_UseTargets().
long BG_StringHashValue_Lwr (const char * fname)
BG_StringHashValue_Lwr.
Parameters
[in] fname
Returns
A hash value for the given string (make sure the strings and lowered first)
Definition at line 358 of file bg_animation.c.
Referenced by G_Script_ActionForString(), G_Script_EventForString(), and G_Script_GetEventIndex().
void BG_UpdateConditionValue (int client, int condition, int value, qboolean checkConversion)
BG_UpdateConditionValue.
Parameters
[in,out] client
[in] condition
[in] value
[in] checkConversion
Definition at line 1718 of file bg_animation.c.
Referenced by BG_AnimScriptAnimation(), BG_AnimUpdatePlayerStateConditions(), CG_AnimPlayerConditions(), G_Damage(), player_die(), PM_FinishWeaponChange(), and PM_SetWaterLevel().
Variable Documentation
animStringItem_t animAIStateStr[] static
Initial value:
=
{
    { "RELAXED", -1 },
    { "QUERY",   -1 },
    { "ALERT",   -1 },
    { "COMBAT",  -1 }
}
Definition at line 237 of file bg_animation.c.
animStringItem_t animBodyPartsStr[]
Initial value:
=
{
    { "** UNUSED **", -1 },
    { "LEGS",         -1 },
    { "TORSO",        -1 },
    { "BOTH",         -1 },
    { NULL,           -1 },
}
Definition at line 146 of file bg_animation.c.
animStringItem_t animConditionImpactPointsStr[] static
Initial value:
=
{
    { "** UNUSED **",   -1 },
    { "HEAD",           -1 },
    { "CHEST",          -1 },
    { "GUT",            -1 },
    { "GROIN",          -1 },
    { "SHOULDER_RIGHT", -1 },
    { "SHOULDER_LEFT",  -1 },
    { "KNEE_RIGHT",     -1 },
    { "KNEE_LEFT",      -1 },
    { NULL,             -1 },
}
Definition at line 187 of file bg_animation.c.
animStringItem_t animConditionLeaningStr[] static
Initial value:
=
{
    { "** UNUSED **", -1 },
    { "RIGHT",        -1 },
    { "LEFT",         -1 },
    { NULL,           -1 },
}
Definition at line 178 of file bg_animation.c.
animStringItem_t animConditionMountedStr[] static
Initial value:
=
{
    { "** UNUSED **", -1 },
    { "MG42",         -1 },
    { NULL,           -1 },
}
Definition at line 170 of file bg_animation.c.
animStringItem_t animConditionPositionsStr[] static
Initial value:
=
{
    { "** UNUSED **", -1 },
    { "BEHIND",       -1 },
    { "INFRONT",      -1 },
    { "RIGHT",        -1 },
    { "LEFT",         -1 },
    { NULL,           -1 },
}
Definition at line 159 of file bg_animation.c.
animStringItem_t animConditionsStr[NUM_ANIM_CONDITIONS+1] static
Initial value:
=
{
    { "WEAPONS",        -1 },
    { "ENEMY_POSITION", -1 },
    { "ENEMY_WEAPON",   -1 },
    { "UNDERWATER",     -1 },
    { "MOUNTED",        -1 },
    { "MOVETYPE",       -1 },
    { "UNDERHAND",      -1 },
    { "LEANING",        -1 },
    { "IMPACT_POINT",   -1 },
    { "CROUCHING",      -1 },
    { "STUNNED",        -1 },
    { "FIRING",         -1 },
    { "SHORT_REACTION", -1 },
    { "ENEMY_TEAM",     -1 },
    { "PARACHUTE",      -1 },
    { "CHARGING",       -1 },
    { "SECONDLIFE",     -1 },
    { "HEALTH_LEVEL",   -1 },
    { "FLAILING_TYPE",  -1 },
    { "GEN_BITFLAG",    -1 },
    { "AISTATE",        -1 },
    { "SUICIDE",        -1 },
    { NULL,             -1 },
}
Definition at line 259 of file bg_animation.c.
animConditionTable_t animConditionsTable[NUM_ANIM_CONDITIONS] static
Initial value:
=
{
    { ANIM_CONDTYPE_BITFLAGS, weaponStrings                },
    { ANIM_CONDTYPE_BITFLAGS, animConditionPositionsStr    },
    { ANIM_CONDTYPE_BITFLAGS, weaponStrings                },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    animConditionMountedStr      },
    { ANIM_CONDTYPE_BITFLAGS, animMoveTypesStr             },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    animConditionLeaningStr      },
    { ANIM_CONDTYPE_VALUE,    animConditionImpactPointsStr },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    animEnemyTeamsStr            },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
    { ANIM_CONDTYPE_VALUE,    animHealthLevelStr           },
    { ANIM_CONDTYPE_VALUE,    animFlailTypeStr             },
    { ANIM_CONDTYPE_BITFLAGS, animGenBitFlagStr            },
    { ANIM_CONDTYPE_VALUE,    animAIStateStr               },
    { ANIM_CONDTYPE_VALUE,    NULL                         },
}
Definition at line 287 of file bg_animation.c.
animStringItem_t animEnemyTeamsStr[] static
Initial value:
=
{
    { "NAZI",    -1 },
    { "ALLIES",  -1 },
    { "MONSTER", -1 },
    { "SPARE1",  -1 },
    { "SPARE2",  -1 },
    { "SPARE3",  -1 },
    { "SPARE4",  -1 },
    { "NEUTRAL", -1 }
}
Definition at line 202 of file bg_animation.c.
animStringItem_t animEventTypesStr[]
Initial value:
=
{
    { "PAIN",                       -1 },
    { "DEATH",                      -1 },
    { "FIREWEAPON",                 -1 },
    { "FIREWEAPON2",                -1 },
    { "JUMP",                       -1 },
    { "JUMPBK",                     -1 },
    { "LAND",                       -1 },
    { "DROPWEAPON",                 -1 },
    { "RAISEWEAPON",                -1 },
    { "CLIMBMOUNT",                 -1 },
    { "CLIMBDISMOUNT",              -1 },
    { "RELOAD",                     -1 },
    { "REVIVE",                     -1 },
    { "DO_ALT_WEAPON_MODE",         -1 },
    { "UNDO_ALT_WEAPON_MODE",       -1 },
    { "DO_ALT_WEAPON_MODE_PRONE",   -1 },
    { "UNDO_ALT_WEAPON_MODE_PRONE", -1 },
    { "FIREWEAPONPRONE",            -1 },
    { "FIREWEAPON2PRONE",           -1 },
    { "RAISEWEAPONPRONE",           -1 },
    { "RELOADPRONE",                -1 },
    { "NOPOWER",                    -1 },
    { NULL,                         -1 },
}
Definition at line 118 of file bg_animation.c.
Referenced by Svcmd_Die().
animStringItem_t animFlailTypeStr[] static
Initial value:
=
{
    { "** UNUSED **", -1 },
    { "INAIR",        -1 },
    { "VCRASH",       -1 },
    { "HCRASH",       -1 },
    { NULL,           -1 },
}
Definition at line 221 of file bg_animation.c.
animStringItem_t animGenBitFlagStr[] static
Initial value:
=
{
    { "ZOOMING", -1 },
}
Definition at line 231 of file bg_animation.c.
animStringItem_t animHealthLevelStr[] static
Initial value:
=
{
    { "1", -1 },
    { "2", -1 },
    { "3", -1 },
}
Definition at line 214 of file bg_animation.c.
animStringItem_t animMoveTypesStr[] static
Definition at line 84 of file bg_animation.c.
animStringItem_t animParseModesStr[] static
Initial value:
=
{
    { "defines",           -1 },
    { "animations",        -1 },
    { "canned_animations", -1 },
    { "statechanges",      -1 },
    { "events",            -1 },
    { NULL,                -1 },
}
Definition at line 917 of file bg_animation.c.
animStringItem_t animStateStr[]
Initial value:
=
{
    { "RELAXED", -1 },
    { "QUERY",   -1 },
    { "ALERT",   -1 },
    { "COMBAT",  -1 },
    { NULL,      -1 },
}
Definition at line 74 of file bg_animation.c.
int defineBits[NUM_ANIM_CONDITIONS][MAX_ANIM_DEFINES][2] static
Definition at line 67 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript(), and BG_ParseConditionBits().
animStringItem_t defineStr[NUM_ANIM_CONDITIONS][MAX_ANIM_DEFINES] static
Definition at line 66 of file bg_animation.c.
char defineStrings[10000] static
Definition at line 64 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
unsigned int defineStringsOffset static
Definition at line 65 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
const char* globalFilename static
Definition at line 60 of file bg_animation.c.
Referenced by __attribute__(), and BG_AnimParseAnimScript().
animScriptData_t* globalScriptData = NULL static
Definition at line 56 of file bg_animation.c.
int numDefines[NUM_ANIM_CONDITIONS] static
Definition at line 63 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript().
int parseEvent static
Definition at line 70 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript(), and BG_ParseCommands().
scriptAnimMoveTypes_t parseMovetype static
Definition at line 69 of file bg_animation.c.
Referenced by BG_AnimParseAnimScript(), and BG_ParseCommands().
animStringItem_t weaponStrings[WP_NUM_WEAPONS] static
Definition at line 72 of file bg_animation.c.