ET: Legacy: src/game/bg_animgroup.c File Reference
bg_animgroup.c File Reference
Animation group code.
#include "../qcommon/q_shared.h"
#include "bg_public.h"
Macros
#define MAX_ANIMPOOL_SIZE 5 * MAX_MODEL_ANIMATIONS
Functions
void BG_ClearAnimationPool (void)
BG_ClearAnimationPool.
static animation_t * BG_RAG_FindFreeAnimation (const char *mdxFileName, const char *name)
static qboolean BG_RAG_ParseError (int handle, const char *format,...)
BG_RAG_ParseError.
static qboolean BG_RAG_ParseAnimation (int handle, animation_t *animation)
BG_RAG_ParseAnimation.
static qboolean BG_RAG_ParseAnimFile (int handle, animModelInfo_t *animModelInfo)
BG_RAG_ParseAnimFile.
qboolean BG_R_RegisterAnimationGroup (const char *filename, animModelInfo_t *animModelInfo)
BG_R_RegisterAnimationGroup.
Variables
static animation_t animationPool [MAX_ANIMPOOL_SIZE]
Detailed Description
Animation group code.
Definition in file bg_animgroup.c.
Macro Definition Documentation
#define MAX_ANIMPOOL_SIZE 5 * MAX_MODEL_ANIMATIONS
Definition at line 39 of file bg_animgroup.c.
Referenced by BG_RAG_FindFreeAnimation().
Function Documentation
void BG_ClearAnimationPool (void)
BG_ClearAnimationPool.
Definition at line 46 of file bg_animgroup.c.
Referenced by CG_RegisterGraphics(), and G_InitGame().
qboolean BG_R_RegisterAnimationGroup (const char * filename, animModelInfo_t * animModelInfo)
BG_R_RegisterAnimationGroup.
Parameters
[in] filename
[out] animModelInfo
Returns
Definition at line 291 of file bg_animgroup.c.
Referenced by CG_ParseAnimationFiles(), and G_ParseAnimationFiles().
static animation_t* BG_RAG_FindFreeAnimation (const char * mdxFileName, const char * name) static
Definition at line 60 of file bg_animgroup.c.
Referenced by BG_ClearAnimationPool(), and BG_RAG_ParseAnimFile().
static qboolean BG_RAG_ParseAnimation (int handle, animation_t * animation) static
BG_RAG_ParseAnimation.
Parameters
[in] handle
[in,out] animation
Returns
Definition at line 131 of file bg_animgroup.c.
Referenced by BG_RAG_ParseAnimFile().
static qboolean BG_RAG_ParseAnimFile (int handle, animModelInfo_t * animModelInfo) static
BG_RAG_ParseAnimFile.
Parameters
[in] handle
[in,out] animModelInfo
Returns
Definition at line 218 of file bg_animgroup.c.
Referenced by BG_R_RegisterAnimationGroup().
static qboolean BG_RAG_ParseError (int handle, const char * format, ...) static
BG_RAG_ParseError.
Parameters
[in] handle
[in] format
Returns
Definition at line 103 of file bg_animgroup.c.
Referenced by BG_R_RegisterAnimationGroup(), BG_RAG_ParseAnimation(), and BG_RAG_ParseAnimFile().
Variable Documentation
animation_t animationPool[MAX_ANIMPOOL_SIZE] static
Definition at line 41 of file bg_animgroup.c.