ET: Legacy: src/game/bg_character.c File Reference
bg_character.c File Reference
Character definition code.
#include "../qcommon/q_shared.h"
#include "bg_public.h"
Functions
static qboolean BG_PCF_ParseError (int handle, const char *format,...)
BG_PCF_ParseError.
qboolean BG_ParseCharacterFile (const char *filename, bg_characterDef_t *characterDef)
BG_ParseCharacterFile.
bg_character_t * BG_GetCharacter (int team, int cls)
BG_GetCharacter.
bg_character_t * BG_GetCharacterForPlayerstate (playerState_t *ps)
BG_GetCharacterForPlayerstate.
void BG_ClearCharacterPool (void)
BG_ClearCharacterPool.
bg_character_t * BG_FindFreeCharacter (const char *characterFile)
BG_FindFreeCharacter.
bg_character_t * BG_FindCharacter (const char *characterFile)
BG_FindCharacter.
Variables
bg_character_t alliedClassCharacters [NUM_PLAYER_CLASSES]
bg_character_t axisClassCharacters [NUM_PLAYER_CLASSES]
bg_character_t bg_characterPool [MAX_CHARACTERS]
qboolean bg_characterPoolInuse [MAX_CHARACTERS]
Detailed Description
Character definition code.
Definition in file bg_character.c.
Function Documentation
void BG_ClearCharacterPool (void)
BG_ClearCharacterPool.
Definition at line 230 of file bg_character.c.
Referenced by CG_RegisterGraphics(), and G_InitGame().
bg_character_t* BG_FindCharacter (const char * characterFile)
BG_FindCharacter.
Parameters
[in] characterFile
Returns
Definition at line 279 of file bg_character.c.
Referenced by CG_ConfigStringModified(), CG_RegisterGraphics(), and G_UpdateCharacter().
bg_character_t* BG_FindFreeCharacter (const char * characterFile)
BG_FindFreeCharacter.
Parameters
[in] characterFile
Returns
Definition at line 241 of file bg_character.c.
Referenced by CG_ConfigStringModified(), CG_RegisterGraphics(), and G_UpdateCharacter().
bg_character_t* BG_GetCharacter (int team, int cls)
BG_GetCharacter.
Parameters
[in] team
[in] cls
Returns
Definition at line 190 of file bg_character.c.
Referenced by CG_CharacterForClientinfo(), CG_CharacterForPlayerstate(), CG_DrawPlayerStatusHead(), CG_LimboPanel_GetCharacter(), CG_NewClientInfo(), CG_RegisterPlayerClasses(), CG_SetLerpFrameAnimationRateCorpse(), G_RegisterPlayerClasses(), and G_UpdateCharacter().
bg_character_t* BG_GetCharacterForPlayerstate (playerState_t * ps)
BG_GetCharacterForPlayerstate.
Parameters
[in] ps
Returns
Todo:
: add disguise?
Definition at line 207 of file bg_character.c.
qboolean BG_ParseCharacterFile (const char * filename, bg_characterDef_t * characterDef)
BG_ParseCharacterFile.
Parameters
[in] filename
[out] characterDef
Returns
Definition at line 76 of file bg_character.c.
Referenced by CG_RegisterCharacter(), and G_RegisterCharacter().
static qboolean BG_PCF_ParseError (int handle, const char * format, ...) static
BG_PCF_ParseError.
Parameters
[in] handle
[in] format
Returns
Definition at line 48 of file bg_character.c.
Referenced by BG_ParseCharacterFile().
Variable Documentation
bg_character_t alliedClassCharacters[NUM_PLAYER_CLASSES]
Definition at line 39 of file bg_character.c.
bg_character_t axisClassCharacters[NUM_PLAYER_CLASSES]
Definition at line 40 of file bg_character.c.
bg_character_t bg_characterPool[MAX_CHARACTERS]
Definition at line 224 of file bg_character.c.
qboolean bg_characterPoolInuse[MAX_CHARACTERS]
Definition at line 225 of file bg_character.c.
Referenced by BG_ClearCharacterPool(), BG_FindCharacter(), and BG_FindFreeCharacter().