ET: Legacy: src/game/bg_classes.c File Reference
bg_classes.c File Reference
#include "../qcommon/q_shared.h"
#include "bg_public.h"
Functions
bg_playerclass_t * BG_GetPlayerClassInfo (int team, int cls)
BG_GetPlayerClassInfo.
bg_playerclass_t * BG_PlayerClassForPlayerState (playerState_t *ps)
BG_PlayerClassForPlayerState.
qboolean BG_ClassHasWeapon (bg_playerclass_t *classInfo, weapon_t weap)
BG_ClassHasWeapon.
qboolean BG_WeaponIsPrimaryForClassAndTeam (int classnum, team_t team, weapon_t weapon)
BG_WeaponIsPrimaryForClassAndTeam.
const char * BG_ClassnameForNumber (int classNum)
BG_ClassnameForNumber.
const char * BG_ClassnameForNumberFilename (int classNum)
BG_ClassnameForNumberFilename.
const char * BG_TeamnameForNumber (team_t teamNum)
BG_TeamnameForNumber.
skillType_t BG_ClassSkillForClass (int classnum)
BG_ClassSkillForClass.
Variables
bg_playerclass_t bg_playerClasses [2][NUM_PLAYER_CLASSES]
skillType_t classskill [NUM_PLAYER_CLASSES] = { SK_HEAVY_WEAPONS, SK_FIRST_AID, SK_EXPLOSIVES_AND_CONSTRUCTION, SK_SIGNALS, SK_MILITARY_INTELLIGENCE_AND_SCOPED_WEAPONS }
Function Documentation
qboolean BG_ClassHasWeapon (bg_playerclass_t * classInfo, weapon_t weap)
BG_ClassHasWeapon.
Parameters
[in] classInfo
[in] weap
Returns
Definition at line 334 of file bg_classes.c.
Referenced by BG_WeaponIsPrimaryForClassAndTeam(), and CG_PlayerCanPickupWeapon().
const char* BG_ClassnameForNumber (int classNum)
BG_ClassnameForNumber.
Parameters
[in] classNum
Returns
Definition at line 401 of file bg_classes.c.
Referenced by CG_Class_f(), CG_IsClassFull(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_SendSetupMsg(), CG_RegisterPlayerClasses(), CG_VoiceChatLocal(), and G_RegisterPlayerClasses().
const char* BG_ClassnameForNumberFilename (int classNum)
BG_ClassnameForNumberFilename.
Parameters
[in] classNum
Returns
Definition at line 425 of file bg_classes.c.
Referenced by CG_Respawn().
skillType_t BG_ClassSkillForClass (int classnum)
BG_ClassSkillForClass.
Parameters
[in] classnum
Returns
Definition at line 532 of file bg_classes.c.
Referenced by CG_ClassSkillForPosition(), CG_DrawPowerUps(), CG_LimboPanel_RenderClassButton(), and CG_LimboPanel_RenderCounter_ValueForButton().
bg_playerclass_t* BG_GetPlayerClassInfo (int team, int cls)
BG_GetPlayerClassInfo.
Parameters
[in] team
[in] cls
Returns
Definition at line 303 of file bg_classes.c.
Referenced by BG_MaxAmmoForWeapon(), BG_PlayerClassForPlayerState(), CG_Class_f(), CG_GetSecondaryWeapon(), CG_LimboPanel_GetPlayerClass(), CG_NewClientInfo(), CG_PlayerClassForClientinfo(), CG_RegisterPlayerClasses(), G_RegisterPlayerClasses(), G_UpgradeSkill(), and SetWolfSpawnWeapons().
bg_playerclass_t* BG_PlayerClassForPlayerState (playerState_t * ps)
BG_PlayerClassForPlayerState.
Parameters
[in] ps
Returns
Definition at line 323 of file bg_classes.c.
Referenced by ClientSpawn().
const char* BG_TeamnameForNumber (team_t teamNum)
BG_TeamnameForNumber.
Parameters
[in] teamNum
Returns
Definition at line 508 of file bg_classes.c.
Referenced by CG_Respawn().
qboolean BG_WeaponIsPrimaryForClassAndTeam (int classnum, team_t team, weapon_t weapon)
BG_WeaponIsPrimaryForClassAndTeam.
Parameters
[in] classnum
[in] team
[in] weapon
Returns
Definition at line 360 of file bg_classes.c.
Referenced by G_CanPickupWeapon().
Variable Documentation
bg_playerclass_t bg_playerClasses[2][NUM_PLAYER_CLASSES]
Definition at line 38 of file bg_classes.c.
skillType_t classskill[NUM_PLAYER_CLASSES] = { SK_HEAVY_WEAPONS, SK_FIRST_AID, SK_EXPLOSIVES_AND_CONSTRUCTION, SK_SIGNALS, SK_MILITARY_INTELLIGENCE_AND_SCOPED_WEAPONS }
Definition at line 525 of file bg_classes.c.
Referenced by BG_ClassSkillForClass().