ET: Legacy: src/Omnibot/Common/BotExports.h File Reference
BotExports.h File Reference
#include "Functions_Bot.h"
#include "Omni-Bot_Types.h"
#include "Omni-Bot_Events.h"
#include "IEngineInterface.h"
Macros
#define OMNIBOT_API
Typedefs
typedef eomnibot_error(* pfnGetFunctionsFromDLL) (Bot_EngineFuncs_t *_pBotFuncs, int _size)
typedef eomnibot_error(* pfnGetClientFunctionsFromDLL) (IClientInterface **_pClientFuncs, int _version)
Functions
OMNIBOT_API eomnibot_error ExportBotFunctionsFromDLL (Bot_EngineFuncs_t *_pBotFuncs, int _size)
const char * OB_VA (const char *_msg,...)
eomnibot_error Omnibot_LoadLibrary (int version, const char *lib, const char *path)
void Omnibot_FreeLibrary ()
bool IsOmnibotLoaded ()
const char * Omnibot_ErrorString (eomnibot_error err)
const char * Omnibot_GetLibraryPath ()
const char * Omnibot_FixPath (const char *_path)
Variables
Bot_EngineFuncs_t g_BotFunctions
IEngineInterface * g_InterfaceFunctions
Macro Definition Documentation
#define OMNIBOT_API
Definition at line 26 of file BotExports.h.
Typedef Documentation
typedef eomnibot_error(* pfnGetClientFunctionsFromDLL) (IClientInterface **_pClientFuncs, int _version)
Definition at line 32 of file BotExports.h.
typedef eomnibot_error(* pfnGetFunctionsFromDLL) (Bot_EngineFuncs_t *_pBotFuncs, int _size)
Definition at line 30 of file BotExports.h.
Function Documentation
OMNIBOT_API eomnibot_error ExportBotFunctionsFromDLL (Bot_EngineFuncs_t * _pBotFuncs, int _size)
bool IsOmnibotLoaded ()
Referenced by Bot_Event_AddWeapon(), Bot_Event_ChatMessage(), Bot_Event_ClientConnected(), Bot_Event_ClientDisConnected(), Bot_Event_Death(), Bot_Event_EntityCreated(), Bot_Event_EntityDeleted(), Bot_Event_FireTeam_Proposal(), Bot_Event_FireTeam_Warn(), Bot_Event_FireTeamCreated(), Bot_Event_FireTeamDestroyed(), Bot_Event_FireWeapon(), Bot_Event_Healed(), Bot_Event_InviteFireTeam(), Bot_Event_JoinedFireTeam(), Bot_Event_KilledSomeone(), Bot_Event_LeftFireTeam(), Bot_Event_MortarImpact(), Bot_Event_PostTriggerMine(), Bot_Event_PreTriggerMine(), Bot_Event_RecievedAmmo(), Bot_Event_RemoveWeapon(), Bot_Event_ResetWeapons(), Bot_Event_Revived(), Bot_Event_Sound(), Bot_Event_Spectated(), Bot_Event_TakeDamage(), Bot_Event_VoiceMacro(), Bot_Interface_ConsoleCommand(), Bot_Interface_Shutdown(), Bot_Interface_Update(), Bot_Util_AddGoal(), Bot_Util_CheckForGoalEntity(), Bot_Util_SendTrigger(), and Omnibot_strncpy().
const char* OB_VA (const char * _msg, ...)
Referenced by Omnibot_strncpy().
const char* Omnibot_ErrorString (eomnibot_error err)
Referenced by Omnibot_strncpy().
const char* Omnibot_FixPath (const char * _path)
Referenced by Bot_Interface_Init(), ETInterface::GetLogPath(), and Omnibot_strncpy().
void Omnibot_FreeLibrary ()
Referenced by Bot_Interface_Shutdown(), and Omnibot_strncpy().
const char* Omnibot_GetLibraryPath ()
Referenced by ETInterface::GetBotPath(), and Omnibot_strncpy().
eomnibot_error Omnibot_LoadLibrary (int version, const char * lib, const char * path)
Referenced by Bot_Interface_Init(), and Omnibot_strncpy().
Variable Documentation
Bot_EngineFuncs_t g_BotFunctions
Referenced by Bot_Event_AddWeapon(), Bot_Event_ChatMessage(), Bot_Event_ClientConnected(), Bot_Event_ClientDisConnected(), Bot_Event_Death(), Bot_Event_EntityCreated(), Bot_Event_EntityDeleted(), Bot_Event_FireTeam_Proposal(), Bot_Event_FireTeam_Warn(), Bot_Event_FireTeamCreated(), Bot_Event_FireTeamDestroyed(), Bot_Event_FireWeapon(), Bot_Event_Healed(), Bot_Event_InviteFireTeam(), Bot_Event_JoinedFireTeam(), Bot_Event_KilledSomeone(), Bot_Event_LeftFireTeam(), Bot_Event_MortarImpact(), Bot_Event_PostTriggerMine(), Bot_Event_PreTriggerMine(), Bot_Event_RecievedAmmo(), Bot_Event_RemoveWeapon(), Bot_Event_ResetWeapons(), Bot_Event_Revived(), Bot_Event_Sound(), Bot_Event_Spectated(), Bot_Event_TakeDamage(), Bot_Event_VoiceMacro(), Bot_Interface_ConsoleCommand(), Bot_Interface_Shutdown(), Bot_Interface_Update(), Bot_Util_AddGoal(), Bot_Util_SendTrigger(), DeleteMapGoal(), Omnibot_strncpy(), and UpdateGoalEntity().
IEngineInterface* g_InterfaceFunctions
Referenced by Bot_Event_EntityCreated(), Bot_Event_Sound(), Bot_Interface_Init(), and Omnibot_strncpy().