ET: Legacy: src/cgame/cg_consolecmds.c File Reference
cg_consolecmds.c File Reference
Text commands typed in at the local console, or executed by a key binding.
#include "cg_local.h"
Functions
static void CG_Viewpos_f (void)
Debugging command to print the current position.
void CG_LimboMenu_f (void)
CG_LimboMenu_f.
static void CG_StatsDown_f (void)
CG_StatsDown_f.
static void CG_StatsUp_f (void)
CG_StatsUp_f.
static void CG_topshotsDown_f (void)
CG_topshotsDown_f.
static void CG_topshotsUp_f (void)
CG_topshotsUp_f.
static void CG_objectivesDown_f (void)
CG_objectivesDown_f.
void CG_objectivesUp_f (void)
CG_objectivesUp_f.
void CG_ScoresDown_f (void)
CG_ScoresDown_f.
void CG_ScoresUp_f (void)
CG_ScoresUp_f.
static void CG_Fade_f (void)
CG_Fade_f.
void CG_QuickMessage_f (void)
CG_QuickMessage_f.
void CG_QuickFireteamMessage_f (void)
CG_QuickFireteamMessage_f.
void CG_QuickFireteamAdmin_f (void)
CG_QuickFireteamAdmin_f.
static void CG_QuickFireteams_f (void)
CG_QuickFireteams_f.
static void CG_FTSayPlayerClass_f (void)
CG_FTSayPlayerClass_f.
static void CG_SayPlayerClass_f (void)
CG_SayPlayerClass_f.
static void CG_VoiceChat_f (void)
CG_VoiceChat_f.
static void CG_TeamVoiceChat_f (void)
CG_TeamVoiceChat_f.
static void CG_BuddyVoiceChat_f (void)
CG_BuddyVoiceChat_f.
static void CG_MessageMode_f (void)
CG_MessageMode_f.
static void CG_MessageSend_f (void)
CG_MessageSend_f.
static void CG_SetWeaponCrosshair_f (void)
CG_SetWeaponCrosshair_f.
static void CG_SelectBuddy_f (void)
CG_SelectBuddy_f.
static void CG_QuickSpawnpoint_f (void)
CG_QuickSpawnpoints_f.
void CG_AdjustAutomapZoom (int zoomIn)
CG_AdjustAutomapZoom.
static void CG_AutomapZoomIn_f (void)
CG_AutomapZoomIn_f.
static void CG_AutomapZoomOut_f (void)
CG_AutomapZoomOut_f.
static void CG_AutomapExpandDown_f (void)
CG_AutomapExpandDown_f.
static void CG_AutomapExpandUp_f (void)
CG_AutomapExpandUp_f.
static void CG_ToggleAutomap_f (void)
CG_ToggleAutomap_f.
static void CG_currentTime_f (void)
CG_currentTime_f.
void CG_autoRecord_f (void)
Dynamically names a demo and sets up the recording.
void CG_autoScreenShot_f (void)
Dynamically names a screenshot.
static void CG_vstrDown_f (void)
CG_vstrDown_f.
static void CG_vstrUp_f (void)
CG_vstrUp_f.
void CG_keyOn_f (void)
CG_keyOn_f.
void CG_keyOff_f (void)
CG_keyOff_f.
void CG_dumpStats_f (void)
CG_dumpStats_f.
static void CG_EditSpeakers_f (void)
CG_EditSpeakers_f.
static void CG_DumpSpeaker_f (void)
CG_DumpSpeaker_f.
static void CG_ModifySpeaker_f (void)
CG_ModifySpeaker_f.
static void CG_UndoSpeaker_f (void)
CG_UndoSpeaker_f.
void CG_ForceTapOut_f (void)
CG_ForceTapOut_f.
static void CG_CPM_f (void)
Shows a popup message.
static void CG_ResetMaxSpeed_f (void)
static void CG_TimerSet_f (void)
ETPro style enemy spawntimer.
static void CG_TimerReset_f (void)
ETPro style timer resetting.
static int CG_GetSecondaryWeapon (int weapon, team_t team, int playerclass)
CG_GetSecondaryWeapon.
qboolean CG_IsClassFull (int playerType, team_t team)
CG_IsClassFull.
qboolean CG_IsWeaponDisabled (weapon_t weapon)
Checks for heavy and rifle weapons.
static void CG_ClassMenu_f (void)
class change menu
static void CG_Class_f (void)
Sends a class setup message. Enables etpro like class scripts.
static void CG_TeamMenu_f (void)
team change menu
static void CG_ReadHuds_f (void)
CG_ReadHuds_f.
static void CG_PrintObjectiveInfo_f (void)
static void CG_ListSpawnPoints_f ()
qboolean CG_ConsoleCommand (void)
The string has been tokenized and can be retrieved with Cmd_Argc() / Cmd_Argv()
void CG_InitConsoleCommands (void)
Let the client system know about all of our commands so it can perform tab completion.
Variables
const char * aMonths [12]
qboolean resetmaxspeed = qfalse
static consoleCommand_t commands []
Detailed Description
Text commands typed in at the local console, or executed by a key binding.
Definition in file cg_consolecmds.c.
Function Documentation
void CG_AdjustAutomapZoom (int zoomIn)
CG_AdjustAutomapZoom.
Parameters
[in] zoomIn
Definition at line 182 of file cg_commandmap.c.
Referenced by CG_AutomapZoomIn_f(), CG_AutomapZoomOut_f(), and CG_QuickSpawnpoint_f().
static void CG_AutomapExpandDown_f (void) static
CG_AutomapExpandDown_f.
Definition at line 770 of file cg_consolecmds.c.
static void CG_AutomapExpandUp_f (void) static
CG_AutomapExpandUp_f.
Definition at line 789 of file cg_consolecmds.c.
static void CG_AutomapZoomIn_f (void) static
CG_AutomapZoomIn_f.
Definition at line 748 of file cg_consolecmds.c.
static void CG_AutomapZoomOut_f (void) static
CG_AutomapZoomOut_f.
Definition at line 759 of file cg_consolecmds.c.
void CG_autoRecord_f (void)
Dynamically names a demo and sets up the recording.
Definition at line 833 of file cg_consolecmds.c.
Referenced by CG_DrawActiveFrame(), and CG_DrawWarmup().
void CG_autoScreenShot_f (void)
Dynamically names a screenshot.
Definition at line 841 of file cg_consolecmds.c.
Referenced by CG_DemoClick(), and CG_DrawIntermission().
static void CG_BuddyVoiceChat_f (void) static
CG_BuddyVoiceChat_f.
Definition at line 531 of file cg_consolecmds.c.
static void CG_Class_f (void) static
Sends a class setup message. Enables etpro like class scripts.
Todo:
: handle missing case ?
Definition at line 1422 of file cg_consolecmds.c.
static void CG_ClassMenu_f (void) static
class change menu
Definition at line 1400 of file cg_consolecmds.c.
qboolean CG_ConsoleCommand (void)
The string has been tokenized and can be retrieved with Cmd_Argc() / Cmd_Argv()
Returns
Definition at line 2022 of file cg_consolecmds.c.
Referenced by vmMain().
static void CG_CPM_f (void) static
Shows a popup message.
Definition at line 1155 of file cg_consolecmds.c.
static void CG_currentTime_f (void) static
CG_currentTime_f.
Definition at line 822 of file cg_consolecmds.c.
static void CG_DumpSpeaker_f (void) static
CG_DumpSpeaker_f.
Definition at line 1014 of file cg_consolecmds.c.
void CG_dumpStats_f (void)
CG_dumpStats_f.
Definition at line 912 of file cg_consolecmds.c.
Referenced by CG_DrawIntermission().
static void CG_EditSpeakers_f (void) static
CG_EditSpeakers_f.
Definition at line 994 of file cg_consolecmds.c.
static void CG_Fade_f (void) static
CG_Fade_f.
Definition at line 292 of file cg_consolecmds.c.
void CG_ForceTapOut_f (void)
CG_ForceTapOut_f.
Definition at line 1147 of file cg_consolecmds.c.
Referenced by CG_ServerCommand().
static void CG_FTSayPlayerClass_f (void) static
CG_FTSayPlayerClass_f.
Definition at line 405 of file cg_consolecmds.c.
static int CG_GetSecondaryWeapon (int weapon, team_t team, int playerclass) static
CG_GetSecondaryWeapon.
Parameters
[in] weapon
[in] team
[in] playerclass
Returns
Definition at line 1258 of file cg_consolecmds.c.
Referenced by CG_Class_f().
void CG_InitConsoleCommands (void)
Let the client system know about all of our commands so it can perform tab completion.
Definition at line 2051 of file cg_consolecmds.c.
Referenced by CG_Init().
qboolean CG_IsClassFull (int playerType, team_t team)
CG_IsClassFull.
Parameters
[in] ent
[in] classIndex
[in] selectedTeam
Returns
Definition at line 1302 of file cg_consolecmds.c.
Referenced by CG_Class_f().
qboolean CG_IsWeaponDisabled (weapon_t weapon)
Checks for heavy and rifle weapons.
Parameters
[in] weapon
Returns
Note
FIXME: this function is based on G_IsWeaponDisabled which needs some rework.
Definition at line 1329 of file cg_consolecmds.c.
Referenced by CG_Class_f().
void CG_keyOff_f (void)
CG_keyOff_f.
Definition at line 900 of file cg_consolecmds.c.
Referenced by CG_DemoClick().
void CG_keyOn_f (void)
CG_keyOn_f.
Definition at line 881 of file cg_consolecmds.c.
Referenced by CG_SetInitialSnapshot().
void CG_LimboMenu_f (void)
CG_LimboMenu_f.
Definition at line 52 of file cg_consolecmds.c.
Referenced by CG_SetInitialSnapshot().
static void CG_ListSpawnPoints_f () static
Definition at line 1868 of file cg_consolecmds.c.
static void CG_MessageMode_f (void) static
CG_MessageMode_f.
say, team say, etc
Definition at line 560 of file cg_consolecmds.c.
static void CG_MessageSend_f (void) static
CG_MessageSend_f.
Definition at line 606 of file cg_consolecmds.c.
static void CG_ModifySpeaker_f (void) static
CG_ModifySpeaker_f.
Definition at line 1125 of file cg_consolecmds.c.
static void CG_objectivesDown_f (void) static
CG_objectivesDown_f.
Definition at line 173 of file cg_consolecmds.c.
void CG_objectivesUp_f (void)
CG_objectivesUp_f.
Definition at line 192 of file cg_consolecmds.c.
static void CG_PrintObjectiveInfo_f (void) static
Definition at line 1843 of file cg_consolecmds.c.
void CG_QuickFireteamAdmin_f (void)
CG_QuickFireteamAdmin_f.
Definition at line 353 of file cg_consolecmds.c.
void CG_QuickFireteamMessage_f (void)
CG_QuickFireteamMessage_f.
Definition at line 331 of file cg_consolecmds.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_Draw().
static void CG_QuickFireteams_f (void) static
CG_QuickFireteams_f.
Definition at line 378 of file cg_consolecmds.c.
void CG_QuickMessage_f (void)
CG_QuickMessage_f.
Definition at line 314 of file cg_consolecmds.c.
Referenced by CG_Debriefing_ChatButton_Draw(), and CG_Debriefing_QCButton_KeyDown().
static void CG_QuickSpawnpoint_f (void) static
CG_QuickSpawnpoints_f.
Definition at line 728 of file cg_consolecmds.c.
static void CG_ReadHuds_f (void) static
CG_ReadHuds_f.
Definition at line 1579 of file cg_consolecmds.c.
static void CG_ResetMaxSpeed_f (void) static
Definition at line 1184 of file cg_consolecmds.c.
static void CG_SayPlayerClass_f (void) static
CG_SayPlayerClass_f.
Definition at line 446 of file cg_consolecmds.c.
void CG_ScoresDown_f (void)
CG_ScoresDown_f.
Definition at line 211 of file cg_consolecmds.c.
Referenced by CG_DemoClick().
void CG_ScoresUp_f (void)
CG_ScoresUp_f.
Definition at line 280 of file cg_consolecmds.c.
Referenced by CG_DemoClick(), and CG_EventHandling().
static void CG_SelectBuddy_f (void) static
CG_SelectBuddy_f.
Definition at line 654 of file cg_consolecmds.c.
static void CG_SetWeaponCrosshair_f (void) static
CG_SetWeaponCrosshair_f.
Definition at line 643 of file cg_consolecmds.c.
static void CG_StatsDown_f (void) static
CG_StatsDown_f.
Definition at line 67 of file cg_consolecmds.c.
static void CG_StatsUp_f (void) static
CG_StatsUp_f.
Definition at line 109 of file cg_consolecmds.c.
static void CG_TeamMenu_f (void) static
team change menu
Definition at line 1562 of file cg_consolecmds.c.
static void CG_TeamVoiceChat_f (void) static
CG_TeamVoiceChat_f.
Todo:
? find a way to print this on screen
Definition at line 503 of file cg_consolecmds.c.
static void CG_TimerReset_f (void) static
ETPro style timer resetting.
Definition at line 1237 of file cg_consolecmds.c.
static void CG_TimerSet_f (void) static
ETPro style enemy spawntimer.
Definition at line 1192 of file cg_consolecmds.c.
static void CG_ToggleAutomap_f (void) static
CG_ToggleAutomap_f.
Definition at line 808 of file cg_consolecmds.c.
static void CG_topshotsDown_f (void) static
CG_topshotsDown_f.
Definition at line 128 of file cg_consolecmds.c.
static void CG_topshotsUp_f (void) static
CG_topshotsUp_f.
Definition at line 154 of file cg_consolecmds.c.
static void CG_UndoSpeaker_f (void) static
CG_UndoSpeaker_f.
Definition at line 1136 of file cg_consolecmds.c.
static void CG_Viewpos_f (void) static
Debugging command to print the current position.
Definition at line 42 of file cg_consolecmds.c.
static void CG_VoiceChat_f (void) static
CG_VoiceChat_f.
Definition at line 487 of file cg_consolecmds.c.
static void CG_vstrDown_f (void) static
CG_vstrDown_f.
Definition at line 849 of file cg_consolecmds.c.
static void CG_vstrUp_f (void) static
CG_vstrUp_f.
Definition at line 865 of file cg_consolecmds.c.
Variable Documentation
const char* aMonths[12]
Initial value:
=
{
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
}
Definition at line 813 of file cg_consolecmds.c.
Referenced by CG_currentTime_f(), and CG_scores_cmd().
consoleCommand_t commands[] static
Definition at line 1894 of file cg_consolecmds.c.
Referenced by CG_ConsoleCommand(), and CG_InitConsoleCommands().
qboolean resetmaxspeed = qfalse
Definition at line 1182 of file cg_consolecmds.c.
Referenced by CG_DrawSpeed(), and CG_ResetMaxSpeed_f().