ET: Legacy: src/cgame/cg_view.c File Reference
cg_view.c File Reference
Setup all the parameters (position, angle, etc) for a 3D rendering.
#include "cg_local.h"
Data Structures
struct plane_s
Some culling bits.
Macros
#define FOCUS_DISTANCE 400
#define STEP 20
#define WAVE_AMPLITUDE 1
#define WAVE_FREQUENCY 0.4
#define UNDERWATER_BIT 16
#define DEBUGTIME
Typedefs
typedef struct plane_s plane_t
Functions
void CG_TestModel_f (void)
Creates an entity in front of the current position, which can then be moved around.
void CG_TestGun_f (void)
Replaces the current view weapon with the given model.
void CG_TestModelNextFrame_f (void)
CG_TestModelNextFrame_f.
void CG_TestModelPrevFrame_f (void)
CG_TestModelPrevFrame_f.
void CG_TestModelNextSkin_f (void)
CG_TestModelNextSkin_f.
void CG_TestModelPrevSkin_f (void)
CG_TestModelPrevSkin_f.
static void CG_AddTestModel (void)
CG_AddTestModel.
void CG_Letterbox (float xsize, float ysize, qboolean center)
Sets the coordinates of the rendered window.
static void CG_CalcVrect (void)
CG_CalcVrect.
void CG_OffsetThirdPersonView (void)
CG_OffsetThirdPersonView.
static void CG_StepOffset (void)
CG_StepOffset.
void CG_KickAngles (void)
CG_KickAngles.
static void CG_ZoomSway (void)
Sway for scoped weapons. this takes aimspread into account so the view settles after a bit.
static void CG_OffsetFirstPersonView (void)
CG_OffsetFirstPersonView.
void CG_AdjustZoomVal (float val, int zoomOut, int zoomIn)
CG_AdjustZoomVal.
void CG_ZoomIn_f (void)
CG_ZoomIn_f.
void CG_ZoomOut_f (void)
CG_ZoomOut_f.
void CG_Zoom (void)
Check for scope wepon in use, and change if necessary - spec/demo scaling allowances or show a zoomed binoculars view .. (still not actively zooming in/out)
static int CG_CalcFov (void)
Fixed fov at intermissions, otherwise account for fov variable and zooms.
static void CG_UnderwaterSounds (void)
CG_UnderwaterSounds.
static void CG_DamageBlendBlob (void)
CG_DamageBlendBlob.
int CG_CalcViewValues (void)
Sets cg.refdef view values.
char * CG_MustParse (char **pString, const char *pErrorMsg)
CG_MustParse.
void CG_ParseSkyBox (void)
CG_ParseSkyBox.
void CG_ParseTagConnects (void)
CG_ParseTagConnects.
void CG_ParseTagConnect (int tagNum)
CG_ParseTagConnect.
void CG_DrawSkyBoxPortal (qboolean fLocalView)
CG_DrawSkyBoxPortal.
void CG_SetupFrustum (void)
qboolean CG_CullPoint (vec3_t pt)
CG_CullPoint.
qboolean CG_CullPointAndRadius (const vec3_t pt, vec_t radius)
CG_CullPointAndRadius.
static void CG_RenderLocations (void)
CG_RenderLocations.
void CG_ProcessCvars ()
CG_ProcessCvars.
void CG_SetupDlightstyles (void)
CG_SetupDlightstyles.
void CG_DrawActiveFrame (int serverTime, qboolean demoPlayback)
Generates and draws a game scene and status information at the given time.
Variables
static plane_t frustum [4]
Detailed Description
Setup all the parameters (position, angle, etc) for a 3D rendering.
Definition in file cg_view.c.
Macro Definition Documentation
#define DEBUGTIME
Definition at line 1961 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
#define FOCUS_DISTANCE 400
Definition at line 311 of file cg_view.c.
Referenced by CG_OffsetThirdPersonView().
#define STEP 20
Referenced by CG_KickAngles().
#define UNDERWATER_BIT 16
Definition at line 1143 of file cg_view.c.
Referenced by CG_UnderwaterSounds().
#define WAVE_AMPLITUDE 1
Definition at line 954 of file cg_view.c.
Referenced by CG_CalcFov().
#define WAVE_FREQUENCY 0.4
Definition at line 955 of file cg_view.c.
Referenced by CG_CalcFov().
Typedef Documentation
typedef struct plane_s plane_t
Function Documentation
static void CG_AddTestModel (void) static
CG_AddTestModel.
Definition at line 169 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
void CG_AdjustZoomVal (float val, int zoomOut, int zoomIn)
CG_AdjustZoomVal.
Parameters
[in] val
[in] type
Definition at line 826 of file cg_view.c.
Referenced by CG_ZoomIn_f(), and CG_ZoomOut_f().
static int CG_CalcFov (void) static
Fixed fov at intermissions, otherwise account for fov variable and zooms.
Returns
Definition at line 961 of file cg_view.c.
Referenced by CG_CalcViewValues().
int CG_CalcViewValues (void)
Sets cg.refdef view values.
Returns
Definition at line 1220 of file cg_view.c.
Referenced by CG_DrawActiveFrame(), and CG_Mover_PostProcess().
static void CG_CalcVrect (void) static
CG_CalcVrect.
Definition at line 245 of file cg_view.c.
Referenced by CG_CalcViewValues().
qboolean CG_CullPoint (vec3_t pt)
CG_CullPoint.
Parameters
pt
Returns
true if culled otherwise false
Definition at line 1730 of file cg_view.c.
Referenced by CG_ParticleRender().
qboolean CG_CullPointAndRadius (const vec3_t pt, vec_t radius)
CG_CullPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
Definition at line 1755 of file cg_view.c.
Referenced by CG_AddFlameSpriteToScene(), and CG_DrawMiscGamemodels().
static void CG_DamageBlendBlob (void) static
CG_DamageBlendBlob.
Definition at line 1156 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
void CG_DrawActiveFrame (int serverTime, qboolean demoPlayback)
Generates and draws a game scene and status information at the given time.
Parameters
[in] serverTime
[in] demoPlayback
Todo:
: this is a hack for the time being since a scripted "selectweapon" does
Definition at line 1978 of file cg_view.c.
Referenced by vmMain().
void CG_DrawSkyBoxPortal (qboolean fLocalView)
CG_DrawSkyBoxPortal.
Parameters
[in] fLocalView
Definition at line 1579 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
void CG_KickAngles (void)
CG_KickAngles.
Definition at line 424 of file cg_view.c.
Referenced by CG_OffsetFirstPersonView().
void CG_Letterbox (float xsize, float ysize, qboolean center)
Sets the coordinates of the rendered window.
Parameters
[in] xsize
[in] ysize
[in] center
Definition at line 209 of file cg_view.c.
Referenced by CG_CalcVrect().
char* CG_MustParse (char ** pString, const char * pErrorMsg)
CG_MustParse.
Parameters
[in] pString
[in] pErrorMsg
Returns
Definition at line 1453 of file cg_view.c.
Referenced by CG_ParseSkyBox(), and CG_ParseTagConnect().
static void CG_OffsetFirstPersonView (void) static
CG_OffsetFirstPersonView.
Definition at line 574 of file cg_view.c.
Referenced by CG_CalcViewValues().
void CG_OffsetThirdPersonView (void)
CG_OffsetThirdPersonView.
Definition at line 316 of file cg_view.c.
Referenced by CG_CalcViewValues().
void CG_ParseSkyBox (void)
CG_ParseSkyBox.
Definition at line 1467 of file cg_view.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseTagConnect (int tagNum)
CG_ParseTagConnect.
Parameters
tagNum
Definition at line 1545 of file cg_view.c.
Referenced by CG_ConfigStringModified(), and CG_ParseTagConnects().
void CG_ParseTagConnects (void)
CG_ParseTagConnects.
Definition at line 1531 of file cg_view.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_ProcessCvars ()
CG_ProcessCvars.
Definition at line 1815 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
static void CG_RenderLocations (void) static
CG_RenderLocations.
Definition at line 1779 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
void CG_SetupDlightstyles (void)
CG_SetupDlightstyles.
Definition at line 1200 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
void CG_SetupFrustum (void)
Definition at line 1696 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
static void CG_StepOffset (void) static
CG_StepOffset.
Warning
This causes a compiler bug on mac MrC compiler
Definition at line 406 of file cg_view.c.
Referenced by CG_OffsetFirstPersonView().
void CG_TestGun_f (void)
Replaces the current view weapon with the given model.
Definition at line 115 of file cg_view.c.
void CG_TestModel_f (void)
Creates an entity in front of the current position, which can then be moved around.
Definition at line 77 of file cg_view.c.
Referenced by CG_TestGun_f().
void CG_TestModelNextFrame_f (void)
CG_TestModelNextFrame_f.
Definition at line 125 of file cg_view.c.
void CG_TestModelNextSkin_f (void)
CG_TestModelNextSkin_f.
Definition at line 147 of file cg_view.c.
void CG_TestModelPrevFrame_f (void)
CG_TestModelPrevFrame_f.
Definition at line 134 of file cg_view.c.
void CG_TestModelPrevSkin_f (void)
CG_TestModelPrevSkin_f.
Definition at line 156 of file cg_view.c.
static void CG_UnderwaterSounds (void) static
CG_UnderwaterSounds.
Definition at line 1148 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
void CG_Zoom (void)
Check for scope wepon in use, and change if necessary - spec/demo scaling allowances or show a zoomed binoculars view .. (still not actively zooming in/out)
Definition at line 885 of file cg_view.c.
Referenced by CG_CalcFov().
void CG_ZoomIn_f (void)
CG_ZoomIn_f.
Definition at line 842 of file cg_view.c.
Referenced by CG_DemoClick(), and CG_ZoomRequired().
void CG_ZoomOut_f (void)
CG_ZoomOut_f.
Definition at line 864 of file cg_view.c.
Referenced by CG_DemoClick(), and CG_ZoomRequired().
static void CG_ZoomSway (void) static
Sway for scoped weapons. this takes aimspread into account so the view settles after a bit.
Definition at line 547 of file cg_view.c.
Referenced by CG_OffsetFirstPersonView().
Variable Documentation
plane_t frustum[4] static
Definition at line 1693 of file cg_view.c.
Referenced by MergeInteractionBounds(), R_CalcLightCubeSideBits(), R_SetupLightFrustum(), R_SetupLightLocalBounds(), R_SetupLightProjection(), R_SetupLightScissor(), RB_RenderDebugUtils(), and RenderLightOcclusionVolume().