ET: Legacy: src/cgame/cg_effects.c File Reference
cg_effects.c File Reference
These functions generate localentities, usually as a result of event processing.
#include "cg_local.h"
Data Structures
struct smokesprite_s
Macros
#define BLOOD_SPURT_COUNT 4
#define GIB_VELOCITY 75
#define GIB_JUMP 250
#define MAXJUNCTIONS 8
#define GIB_BLOOD_DOTS 3
#define MAX_SMOKESPRITES 512
#define SMOKEBOMB_SPAWNRATE 10
#define SMOKEBOMB_SMOKEVELOCITY ((640.f - 16.f) / 8) / 1000.f
#define SMOKEBOMB_STARTRADIUS 16
#define SMOKEBOMB_FINALRADIUS 640
Typedefs
typedef struct smokesprite_s smokesprite_t
Functions
void CG_BubbleTrail (vec3_t start, vec3_t end, float size, float spacing)
Bullets shot underwater.
localEntity_t * CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
Adds a smoke puff or blood trail localEntity.
localEntity_t * CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
CG_MakeExplosion.
void CG_AddBloodTrails (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddBloodTrails.
void CG_Bleed (vec3_t origin, int entityNum)
This is the spurt of blood when a character gets hit.
void CG_LaunchGib (centity_t *cent, vec3_t origin, vec3_t angles, vec3_t velocity, qhandle_t hModel, float sizeScale, int breakCount)
CG_LaunchGib.
void CG_LoseHat (centity_t *cent, vec3_t dir)
CG_LoseHat.
int CG_GetOriginForTag (centity_t *cent, refEntity_t *parent, const char *tagName, int startIndex, vec3_t org, vec3_t axis[3])
Places the position of the tag into "org".
void CG_GibPlayer (centity_t *cent, vec3_t playerOrigin, vec3_t gdir)
Generated a bunch of gibs launching out from the bodies location.
void CG_SparklerSparks (vec3_t origin, int count)
CG_SparklerSparks.
void CG_RumbleEfx (float pitch, float yaw)
CG_RumbleEfx.
void InitSmokeSprites (void)
InitSmokeSprites.
static smokesprite_t * AllocSmokeSprite (void)
AllocSmokeSprite.
static smokesprite_t * DeAllocSmokeSprite (smokesprite_t *dealloc)
DeAllocSmokeSprite.
static qboolean CG_SmokeSpritePhysics (smokesprite_t *smokesprite, const float dist)
CG_SmokeSpritePhysics.
qboolean CG_SpawnSmokeSprite (centity_t *cent, float dist)
CG_SpawnSmokeSprite.
void CG_RenderSmokeGrenadeSmoke (centity_t *cent, const weaponInfo_t *weapon)
CG_RenderSmokeGrenadeSmoke.
void CG_AddSmokeSprites (void)
CG_AddSmokeSprites.
Variables
static smokesprite_t SmokeSprites [MAX_SMOKESPRITES]
static int SmokeSpriteCount = 0
static smokesprite_t * firstfreesmokesprite
static smokesprite_t * lastusedsmokesprite
Detailed Description
These functions generate localentities, usually as a result of event processing.
Definition in file cg_effects.c.
Macro Definition Documentation
#define BLOOD_SPURT_COUNT 4
Definition at line 298 of file cg_effects.c.
Referenced by CG_Bleed().
#define GIB_BLOOD_DOTS 3
Definition at line 571 of file cg_effects.c.
Referenced by CG_GibPlayer().
#define GIB_JUMP 250
Definition at line 450 of file cg_effects.c.
Referenced by CG_GibPlayer(), and CG_LoseHat().
#define GIB_VELOCITY 75
Definition at line 449 of file cg_effects.c.
Referenced by CG_GibPlayer(), and CG_LoseHat().
#define MAX_SMOKESPRITES 512
Definition at line 877 of file cg_effects.c.
Referenced by AllocSmokeSprite(), and InitSmokeSprites().
#define MAXJUNCTIONS 8
Definition at line 570 of file cg_effects.c.
Referenced by CG_GibPlayer().
#define SMOKEBOMB_FINALRADIUS 640
Definition at line 882 of file cg_effects.c.
Referenced by CG_RenderSmokeGrenadeSmoke().
#define SMOKEBOMB_SMOKEVELOCITY ((640.f - 16.f) / 8) / 1000.f
Definition at line 880 of file cg_effects.c.
Referenced by CG_AddSmokeSprites(), and CG_RenderSmokeGrenadeSmoke().
#define SMOKEBOMB_SPAWNRATE 10
Definition at line 879 of file cg_effects.c.
Referenced by CG_RenderSmokeGrenadeSmoke().
#define SMOKEBOMB_STARTRADIUS 16
Definition at line 881 of file cg_effects.c.
Referenced by CG_RenderSmokeGrenadeSmoke().
Typedef Documentation
typedef struct smokesprite_s smokesprite_t
Function Documentation
static smokesprite_t* AllocSmokeSprite (void) static
AllocSmokeSprite.
Returns
Definition at line 926 of file cg_effects.c.
Referenced by CG_SpawnSmokeSprite().
void CG_AddBloodTrails (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddBloodTrails.
Parameters
[in] origin
[in] dir
[in] speed
[in] duration
[in] count
[in] randScale
Definition at line 265 of file cg_effects.c.
Referenced by CG_Bleed().
void CG_AddSmokeSprites (void)
CG_AddSmokeSprites.
Definition at line 1210 of file cg_effects.c.
Referenced by CG_DrawActiveFrame().
void CG_Bleed (vec3_t origin, int entityNum)
This is the spurt of blood when a character gets hit.
Parameters
[in] origin
[in] entityNum
Definition at line 304 of file cg_effects.c.
Referenced by CG_Bullet(), and CG_MissileHitPlayer().
void CG_BubbleTrail (vec3_t start, vec3_t end, float size, float spacing)
Bullets shot underwater.
Parameters
[in] start
[in] end
[in] size
[in] spacing
Definition at line 46 of file cg_effects.c.
Referenced by CG_Bullet(), CG_GrenadeTrail(), and CG_RocketTrail().
int CG_GetOriginForTag (centity_t * cent, refEntity_t * parent, const char * tagName, int startIndex, vec3_t org, vec3_t axis[3])
Places the position of the tag into "org".
Parameters
cent - unused
[in] parent
[in] tagName
[in] startIndex
[in,out] org
[in] axis
Returns
The index of the tag it used, so we can cycle through tag's with the same name
Definition at line 541 of file cg_effects.c.
Referenced by CG_BreathPuffs(), CG_Bullet(), CG_GibPlayer(), CG_LoseHat(), and CG_PlayerShadow().
void CG_GibPlayer (centity_t * cent, vec3_t playerOrigin, vec3_t gdir)
Generated a bunch of gibs launching out from the bodies location.
Parameters
[in,out] cent
[in] playerOrigin
[in] gdir
Definition at line 579 of file cg_effects.c.
Referenced by CG_EntityEvent().
void CG_LaunchGib (centity_t * cent, vec3_t origin, vec3_t angles, vec3_t velocity, qhandle_t hModel, float sizeScale, int breakCount)
CG_LaunchGib.
Parameters
[in] cent
[in] origin
[in] angles
[in] velocity
[in] hModel
[in] sizeScale
[in] breakCount
Definition at line 382 of file cg_effects.c.
Referenced by CG_GibPlayer().
void CG_LoseHat (centity_t * cent, vec3_t dir)
CG_LoseHat.
Parameters
[in] cent
[in] dir
Todo:
: origin of hat md3 is offset from center. need to center the origin when you toss it
Definition at line 457 of file cg_effects.c.
Referenced by CG_EntityEvent(), and CG_GibPlayer().
localEntity_t* CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
CG_MakeExplosion.
Parameters
[in] origin
[in] dir
[in] hModel
[in] shader
[in] msec
[in] isSprite
Returns
Definition at line 187 of file cg_effects.c.
Referenced by CG_BigExplosionImpact(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_MapMortarImpact(), and CG_SmallExplosionImpact().
void CG_RenderSmokeGrenadeSmoke (centity_t * cent, const weaponInfo_t * weapon)
CG_RenderSmokeGrenadeSmoke.
Parameters
[in,out] cent
[in] weapon
Definition at line 1081 of file cg_effects.c.
Referenced by CG_Missile().
void CG_RumbleEfx (float pitch, float yaw)
CG_RumbleEfx.
Parameters
[in] pitch
[in] yaw
Definition at line 807 of file cg_effects.c.
Referenced by CG_EntityEvent().
localEntity_t* CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
Adds a smoke puff or blood trail localEntity.
Parameters
[in] p
[in] vel
[in] radius
[in] r
[in] g
[in] b
[in] a
[in] duration
[in] startTime
[in] fadeInTime
[in] leFlags
[in] hShader
Returns
Todo:
It would be nice to have an acceleration vector for this as well. Big velocity vector with a negative acceleration for deceleration, etc. (breath could then come out of a guys mouth at the rate he's walking/running and it would slow down once it's created)
Definition at line 118 of file cg_effects.c.
Referenced by CG_BreathPuffs(), CG_Bullet(), CG_EntityEffects(), and CG_PyroSmokeTrail().
static qboolean CG_SmokeSpritePhysics (smokesprite_t * smokesprite, const float dist) static
CG_SmokeSpritePhysics.
Parameters
[in,out] smokesprite
[in] dist
Returns
Todo:
: use mins and max with smoke sprite minimum radius and then expand to max possible distance or real current sprite size?
Definition at line 995 of file cg_effects.c.
Referenced by CG_AddSmokeSprites(), and CG_SpawnSmokeSprite().
void CG_SparklerSparks (vec3_t origin, int count)
CG_SparklerSparks.
Parameters
[in] origin
[in] count
Note
Unused
Definition at line 769 of file cg_effects.c.
qboolean CG_SpawnSmokeSprite (centity_t * cent, float dist)
CG_SpawnSmokeSprite.
Parameters
[in,out] cent
[in] dist
Returns
Definition at line 1043 of file cg_effects.c.
Referenced by CG_RenderSmokeGrenadeSmoke().
static smokesprite_t* DeAllocSmokeSprite (smokesprite_t * dealloc) static
DeAllocSmokeSprite.
Parameters
[in,out] dealloc
Returns
Previous alloced smokesprite in list (or NULL when there are no more alloced smokesprites left)
Definition at line 957 of file cg_effects.c.
Referenced by CG_AddSmokeSprites(), and CG_SpawnSmokeSprite().
void InitSmokeSprites (void)
InitSmokeSprites.
Definition at line 907 of file cg_effects.c.
Referenced by CG_MapRestart(), and CG_RegisterGraphics().
Variable Documentation
smokesprite_t* firstfreesmokesprite static
Definition at line 901 of file cg_effects.c.
Referenced by AllocSmokeSprite(), and DeAllocSmokeSprite().
smokesprite_t* lastusedsmokesprite static
Definition at line 902 of file cg_effects.c.
Referenced by AllocSmokeSprite(), CG_AddSmokeSprites(), and CG_RenderSmokeGrenadeSmoke().
int SmokeSpriteCount = 0 static
Definition at line 900 of file cg_effects.c.
Referenced by AllocSmokeSprite(), DeAllocSmokeSprite(), and InitSmokeSprites().
smokesprite_t SmokeSprites[MAX_SMOKESPRITES] static
Definition at line 899 of file cg_effects.c.