ET: Legacy: src/cgame/cg_predict.c File Reference
cg_predict.c File Reference
#include "cg_local.h"
Macros
#define MAX_PREDICT_ORIGIN_DELTA_2 0.01f
#define MAX_PREDICT_VELOCITY_DELTA_2 0.01f
#define MAX_PREDICT_VIEWANGLES_DELTA 1.0f
Functions
void CG_BuildSolidList (void)
When a new cg.snap has been set, this function builds a sublist of the entities that are actually solid, to make for more efficient collision detection.
float CG_ClientHitboxMaxZ (entityState_t *hitEnt, float def)
Client-side hitbox prediction code modified for cgame.
static void CG_ClipMoveToEntities (const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask, qboolean capsule, trace_t *tr)
CG_ClipMoveToEntities.
void CG_Trace (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_Trace.
void CG_TraceCapsule (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_TraceCapsule.
void CG_TraceCapsule_World (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_TraceCapsule_World.
int CG_PointContents (const vec3_t point, int passEntityNum)
CG_PointContents.
static void CG_InterpolatePlayerState (qboolean grabAngles)
Generates cg.predictedPlayerState by interpolating between cg.snap->player_state and cg.nextFrame->player_state.
static void CG_TouchTriggerPrediction (void)
Predict push triggers and items.
int CG_PredictionOk (playerState_t *ps1, playerState_t *ps2)
CG_PredictionOk.
void CG_PredictPlayerState (void)
Generates cg.predictedPlayerState for the current cg.time cg.predictedPlayerState is guaranteed to be valid after exiting.
Variables
pmove_t cg_pmove
static int cg_numSolidEntities
static centity_t * cg_solidEntities [MAX_ENTITIES_IN_SNAPSHOT]
static int cg_numSolidFTEntities
static centity_t * cg_solidFTEntities [MAX_ENTITIES_IN_SNAPSHOT]
static int cg_numTriggerEntities
static centity_t * cg_triggerEntities [MAX_ENTITIES_IN_SNAPSHOT]
pmoveExt_t oldpmext [CMD_BACKUP]
const char * predictionStrings []
Detailed Description
This file generates cg.predictedPlayerState by either interpolating between snapshots from the server or locally predicting ahead the client's movement. It also handles local physics interaction, like fragments bouncing off walls.
Definition in file cg_predict.c.
Macro Definition Documentation
#define MAX_PREDICT_ORIGIN_DELTA_2 0.01f
Definition at line 705 of file cg_predict.c.
Referenced by CG_PredictionOk().
#define MAX_PREDICT_VELOCITY_DELTA_2 0.01f
Definition at line 707 of file cg_predict.c.
Referenced by CG_PredictionOk().
#define MAX_PREDICT_VIEWANGLES_DELTA 1.0f
Definition at line 708 of file cg_predict.c.
Referenced by CG_PredictionOk().
Function Documentation
void CG_BuildSolidList (void)
When a new cg.snap has been set, this function builds a sublist of the entities that are actually solid, to make for more efficient collision detection.
Definition at line 55 of file cg_predict.c.
Referenced by CG_SetInitialSnapshot(), and CG_SetNextSnap().
float CG_ClientHitboxMaxZ (entityState_t * hitEnt, float def)
Client-side hitbox prediction code modified for cgame.
Parameters
[in] hitEnt
def - unused
Returns
Definition at line 127 of file cg_predict.c.
Referenced by CG_ClipMoveToEntities().
static void CG_ClipMoveToEntities (const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask, qboolean capsule, trace_t * tr) static
CG_ClipMoveToEntities.
Parameters
[in] start
[in] mins
[in] maxs
[in] end
[in] skipNumber
[in] mask
[in] capsule
[in,out] tr
Todo:
: entity damage, see SV_ClipMoveToEntities
Definition at line 169 of file cg_predict.c.
Referenced by CG_Trace(), and CG_TraceCapsule().
static void CG_InterpolatePlayerState (qboolean grabAngles) static
Generates cg.predictedPlayerState by interpolating between cg.snap->player_state and cg.nextFrame->player_state.
Parameters
grabAngles
Definition at line 514 of file cg_predict.c.
Referenced by CG_PredictPlayerState().
int CG_PointContents (const vec3_t point, int passEntityNum)
CG_PointContents.
Parameters
[in] point
[in] passEntityNum
Returns
Definition at line 469 of file cg_predict.c.
Referenced by CG_AddDebrisElementsExtended(), CG_AddFragment(), CG_AddPlayerWeapon(), CG_AltWeapon_f(), CG_BreathPuffs(), CG_Bullet(), CG_CalcFov(), CG_CheckForCursorHints(), CG_DrawPlayerStatus(), CG_Effect(), CG_EntityEvent(), CG_GrenadeTrail(), CG_MachineGunEjectBrass(), CG_MissileHitPlayer(), CG_PanzerFaustEjectBrass(), CG_PlayerSplash(), CG_PredictPlayerState(), CG_PyroSmokeTrail(), and CG_RocketTrail().
int CG_PredictionOk (playerState_t * ps1, playerState_t * ps2)
CG_PredictionOk.
Parameters
[in] ps1
[in] ps2
Returns
Todo:
: use WP_NUM_WEAPONS instead ? we don't need to reach the max weapons, no ?
Todo:
: predict knife?
Definition at line 716 of file cg_predict.c.
Referenced by CG_PredictPlayerState().
void CG_PredictPlayerState (void)
Generates cg.predictedPlayerState for the current cg.time cg.predictedPlayerState is guaranteed to be valid after exiting.
For demo playback, this will be an interpolation between two valid playerState_t.
For normal gameplay, it will be the result of predicted usercmd_t on top of the most recent playerState_t received from the server.
Each new snapshot will usually have one or more new usercmd over the last, but we simulate all unacknowledged commands each time, not just the new ones. This means that on an internet connection, quite a few pmoves may be issued each frame.
OPTIMIZE: don't re-simulate unless the newly arrived snapshot playerState_t differs from the predicted one. Would require saving all intermediate playerState_t during prediction. (this is "dead reckoning" and would definately be nice to have in there
We detect prediction errors and allow them to be decayed off over several frames to ease the jerk.
Todo:
: clarify MG & Browning are locked in place too?
Definition at line 965 of file cg_predict.c.
Referenced by CG_DrawActiveFrame().
static void CG_TouchTriggerPrediction (void) static
Predict push triggers and items.
Definition at line 578 of file cg_predict.c.
Referenced by CG_PredictPlayerState().
void CG_Trace (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_Trace.
Parameters
[in] result
[in] start
[in] mins
[in] maxs
[in] end
[in] skipNumber
[in] mask
Definition at line 362 of file cg_predict.c.
Referenced by CG_AddBloodElements(), CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), CG_AddFragment(), CG_AddSparkElements(), CG_Bullet(), CG_CheckForCursorHints(), CG_Corona(), CG_Coronas(), CG_DrawOnScreenLabels(), CG_DumpSpeaker_f(), CG_FireFlameChunks(), CG_GibPlayer(), CG_InterpolatePlayerState(), CG_MoveFlameChunk(), CG_OffsetThirdPersonView(), CG_PredictLean(), CG_RenderSmokeGrenadeSmoke(), CG_ScanForCrosshairDyna(), CG_ScanForCrosshairEntity(), CG_ScanForCrosshairMine(), CG_ShakeCamera(), and CG_SmokeSpritePhysics().
void CG_TraceCapsule (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_TraceCapsule.
Parameters
[out] result
[in] start
[in] mins
[in] maxs
[in] end
[in] skipNumber
[in] mask
Definition at line 432 of file cg_predict.c.
Referenced by CG_PredictPlayerState().
void CG_TraceCapsule_World (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_TraceCapsule_World.
Parameters
[out] result
[in] start
[in] mins
[in] maxs
[in] end
skipNumber - unused
[in] mask
Definition at line 454 of file cg_predict.c.
Referenced by CG_PredictPlayerState().
Variable Documentation
int cg_numSolidEntities static
Definition at line 43 of file cg_predict.c.
Referenced by CG_BuildSolidList(), CG_ClipMoveToEntities(), and CG_PointContents().
int cg_numSolidFTEntities static
Definition at line 45 of file cg_predict.c.
Referenced by CG_BuildSolidList().
int cg_numTriggerEntities static
Definition at line 47 of file cg_predict.c.
Referenced by CG_BuildSolidList(), and CG_TouchTriggerPrediction().
pmove_t cg_pmove
Definition at line 41 of file cg_predict.c.
Referenced by CG_FinishWeaponChange().
centity_t* cg_solidEntities[MAX_ENTITIES_IN_SNAPSHOT] static
Definition at line 44 of file cg_predict.c.
centity_t* cg_solidFTEntities[MAX_ENTITIES_IN_SNAPSHOT] static
Definition at line 46 of file cg_predict.c.
centity_t* cg_triggerEntities[MAX_ENTITIES_IN_SNAPSHOT] static
Definition at line 48 of file cg_predict.c.
oldpmext
We need to keep pmext around for old frames, because Pmove() fills in some values when it does prediction. This in itself is fine, but the prediction loop starts in the past and predicts from the snapshot time up to the current time, and having things like jumpTime appear to be set for prediction runs where they previously weren't is a Bad Thing. This is my bugfix for #166.
Definition at line 908 of file cg_predict.c.
const char* predictionStrings[]
Definition at line 910 of file cg_predict.c.
Referenced by CG_PredictPlayerState().