ET: Legacy: src/cgame/cg_ents.c File Reference
cg_ents.c File Reference
Present snapshot entities, happens every single frame.
#include "cg_local.h"
Data Structures
struct cabinetTag_s
Macros
#define LS_FRAMETIME 100
#define DEFAULT_SPEAKER_RANGE 1250
#define DEFAULT_SPEAKER_VOLUME 255
#define SIMPLEITEM_ICON_SIZE 24.f
#define NUM_FRAME_PROPELLER 10
#define TIME_FRAME_PROPELLER (1000 / NUM_FRAME_PROPELLER)
#define MAX_CABINET_TAGS 6
Typedefs
typedef enum cabinetType_e cabinetType_t
typedef struct cabinetTag_s cabinetTag_t
Enumerations
enum cabinetType_e { CT_AMMO, CT_HEALTH, CT_MAX }
Functions
void CG_PositionEntityOnTag (refEntity_t *entity, const refEntity_t *parent, const char *tagName, int startIndex, vec3_t *offset)
Modifies the entities position and axis by the given tag location.
void CG_PositionRotatedEntityOnTag (refEntity_t *entity, const refEntity_t *parent, const char *tagName)
Modifies the entities position and axis by the given tag location.
void CG_SetEntitySoundPosition (centity_t *cent)
Also called by event processing code.
void CG_AddLightstyle (centity_t *cent)
CG_AddLightstyle.
void CG_GetWindVector (vec3_t dir)
Compute random wind vector for smoke puff.
static void CG_EntityEffects (centity_t *cent)
Add continuous entity effects, like local entity emission and lighting.
static void CG_General (centity_t *cent)
CG_General.
static void CG_Speaker (centity_t *cent)
Speaker entities can automatically play sounds.
qboolean CG_PlayerSeesItem (playerState_t *ps, entityState_t *item, int atTime, int itemType)
CG_PlayerSeesItem.
static int CG_PlayerCanPickupWeapon (int clientNum, weapon_t weapon)
CG_PlayerCanPickupWeapon.
static void CG_Item (centity_t *cent)
CG_Item.
static void CG_Smoker (centity_t *cent)
CG_Smoker.
static void CG_DrawLandmine (centity_t *cent, refEntity_t *ent)
static void CG_DrawMineMarkerFlag (centity_t *cent, refEntity_t *ent, const weaponInfo_t *weapon)
CG_DrawMineMarkerFlag.
void CG_RocketTrail (centity_t *ent, const weaponInfo_t *wi)
New trail effects.
void CG_ScanForCrosshairMine (centity_t *cent)
CG_ScanForCrosshairMine.
void CG_ScanForCrosshairDyna (centity_t *cent)
CG_ScanForCrosshairDyna.
static void CG_EntityFloatText (centity_t *cent, const char *text, int height)
CG_PlayerFloatText.
static void CG_Missile (centity_t *cent)
CG_Missile.
void CG_RunLerpFrame (centity_t *cent, clientInfo_t *ci, lerpFrame_t *lf, int newAnimation, float speedScale)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
static void CG_TrapSetAnim (centity_t *cent, lerpFrame_t *lf, int newAnim)
CG_TrapSetAnim.
static void CG_Trap (centity_t *cent)
CG_Trap.
static void CG_Corona (centity_t *cent)
CG_Corona.
static void CG_Explosive (centity_t *cent)
This is currently almost exactly the same as CG_Mover It's split out so that any changes or experiments are unattached to anything else.
static void CG_Constructible (centity_t *cent)
This is currently almost exactly the same as CG_Mover It's split out so that any changes or experiments are unattached to anything else.
static void CG_Mover (centity_t *cent)
CG_Mover.
void CG_MovePlane (centity_t *cent)
CG_MovePlane.
void CG_Mover_PostProcess (centity_t *cent)
CG_Mover_PostProcess.
void CG_Beam_2 (centity_t *cent)
New beam entity, for rope like stuff...
void CG_Beam (centity_t *cent)
Also called as an event.
static void CG_Portal (centity_t *cent)
CG_Portal.
static void CG_Prop (centity_t *cent)
CG_Prop.
void CG_Cabinet (centity_t *cent, cabinetType_t type)
CG_Cabinet.
void CG_SetupCabinets (void)
CG_SetupCabinets.
void CG_AdjustPositionForMover (const vec3_t in, int moverNum, int fromTime, int toTime, vec3_t out, vec3_t outDeltaAngles)
Also called by client movement prediction code.
static void CG_InterpolateEntityPosition (centity_t *cent)
CG_InterpolateEntityPosition.
void CG_CalcEntityLerpPositions (centity_t *cent)
CG_CalcEntityLerpPositions.
static void CG_ProcessEntity (centity_t *cent)
CG_ProcessEntity.
void CG_AddCEntity (centity_t *cent)
CG_AddCEntity.
qboolean CG_AddLinkedEntity (centity_t *cent, qboolean ignoreframe, int atTime)
CG_AddLinkedEntity.
qboolean CG_AddEntityToTag (centity_t *cent)
CG_AddEntityToTag.
qboolean CG_AddCEntity_Filter (centity_t *cent)
CG_AddCEntity_Filter.
void CG_AddPacketEntities (void)
CG_AddPacketEntities.
void CGRefEntityToTag (refEntity_t *ent, tag_t *tag)
CGRefEntityToTag.
void CGTagToRefEntity (refEntity_t *ent, tag_t *tag)
CGTagToRefEntity.
void CG_AttachBitsToTank (centity_t *tank, refEntity_t *mg42base, refEntity_t *mg42upper, refEntity_t *mg42gun, refEntity_t *player, refEntity_t *flash, vec_t *playerangles, const char *tagName, qboolean browning)
CG_AttachBitsToTank.
Variables
static animation_t multi_flagpoleAnims []
cabinetTag_t cabinetInfo [CT_MAX]
Detailed Description
Present snapshot entities, happens every single frame.
Definition in file cg_ents.c.
Macro Definition Documentation
#define DEFAULT_SPEAKER_RANGE 1250
Definition at line 215 of file cg_ents.c.
Referenced by CG_EntityEffects().
#define DEFAULT_SPEAKER_VOLUME 255
Definition at line 216 of file cg_ents.c.
Referenced by CG_EntityEffects().
#define LS_FRAMETIME 100
Definition at line 123 of file cg_ents.c.
Referenced by CG_AddLightstyle().
#define MAX_CABINET_TAGS 6
Definition at line 2181 of file cg_ents.c.
Referenced by CG_Cabinet(), and CG_SetupCabinets().
#define NUM_FRAME_PROPELLER 10
Definition at line 1778 of file cg_ents.c.
Referenced by CG_MovePlane().
#define SIMPLEITEM_ICON_SIZE 24.f
Definition at line 630 of file cg_ents.c.
Referenced by CG_Item().
#define TIME_FRAME_PROPELLER (1000 / NUM_FRAME_PROPELLER)
Definition at line 1779 of file cg_ents.c.
Referenced by CG_MovePlane().
Typedef Documentation
typedef struct cabinetTag_s cabinetTag_t
typedef enum cabinetType_e cabinetType_t
Enumeration Type Documentation
enum cabinetType_e
Enumerator
CT_AMMO
CT_HEALTH
CT_MAX
Definition at line 2174 of file cg_ents.c.
Function Documentation
void CG_AddCEntity (centity_t * cent)
CG_AddCEntity.
Parameters
[in,out] cent
Definition at line 2589 of file cg_ents.c.
Referenced by CG_AddCEntity_Filter(), and CG_AddPacketEntities().
qboolean CG_AddCEntity_Filter (centity_t * cent)
CG_AddCEntity_Filter.
Parameters
[in] cent
Returns
Definition at line 2895 of file cg_ents.c.
Referenced by CG_AddEntityToTag(), CG_AddPacketEntities(), and CG_AttachBitsToTank().
qboolean CG_AddEntityToTag (centity_t * cent)
CG_AddEntityToTag.
Parameters
[in,out] cent
Returns
Definition at line 2808 of file cg_ents.c.
Referenced by CG_AddCEntity_Filter().
void CG_AddLightstyle (centity_t * cent)
CG_AddLightstyle.
Parameters
cent
Definition at line 129 of file cg_ents.c.
Referenced by CG_EntityEffects().
qboolean CG_AddLinkedEntity (centity_t * cent, qboolean ignoreframe, int atTime)
CG_AddLinkedEntity.
Parameters
[in,out] cent
[in] ignoreframe
[in] atTime
Returns
Definition at line 2616 of file cg_ents.c.
Referenced by CG_AddCEntity_Filter(), CG_AddLinkedEntity(), and CG_AdjustPositionForMover().
void CG_AddPacketEntities (void)
CG_AddPacketEntities.
Definition at line 2923 of file cg_ents.c.
Referenced by CG_DrawActiveFrame().
void CG_AdjustPositionForMover (const vec3_t in, int moverNum, int fromTime, int toTime, vec3_t out, vec3_t outDeltaAngles)
Also called by client movement prediction code.
Parameters
[in] in
[in] moverNum
[in] fromTime
[in] toTime
[in] out
[in] outDeltaAngles
Definition at line 2334 of file cg_ents.c.
Referenced by CG_CalcEntityLerpPositions(), and CG_PredictPlayerState().
void CG_AttachBitsToTank (centity_t * tank, refEntity_t * mg42base, refEntity_t * mg42upper, refEntity_t * mg42gun, refEntity_t * player, refEntity_t * flash, vec_t * playerangles, const char * tagName, qboolean browning)
CG_AttachBitsToTank.
Parameters
[in,out] tank
[out] mg42base
[out] mg42upper
[out] mg42gun
[out] player
[out] flash
[in] playerangles
[in] tagName
[in] browning
Definition at line 3036 of file cg_ents.c.
Referenced by CG_Mover_PostProcess().
void CG_Beam (centity_t * cent)
Also called as an event.
Parameters
[in] cent
Definition at line 2004 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_Beam_2 (centity_t * cent)
New beam entity, for rope like stuff...
Parameters
[in] cent
Definition at line 1971 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_Cabinet (centity_t * cent, cabinetType_t type)
CG_Cabinet.
Parameters
[in] cent
[in] type
Definition at line 2248 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_CalcEntityLerpPositions (centity_t * cent)
CG_CalcEntityLerpPositions.
Parameters
[in] cent
Definition at line 2449 of file cg_ents.c.
Referenced by CG_AddCEntity(), CG_AddEntityToTag(), and CG_AddPacketEntities().
static void CG_Constructible (centity_t * cent) static
This is currently almost exactly the same as CG_Mover It's split out so that any changes or experiments are unattached to anything else.
Parameters
[in] cent
Definition at line 1610 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_Corona (centity_t * cent) static
CG_Corona.
Parameters
[in] cent
Definition at line 1502 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_DrawLandmine (centity_t * cent, refEntity_t * ent) static
Definition at line 1015 of file cg_ents.c.
Referenced by CG_Missile().
static void CG_DrawMineMarkerFlag (centity_t * cent, refEntity_t * ent, const weaponInfo_t * weapon) static
CG_DrawMineMarkerFlag.
Parameters
[in] cent
[out] ent
[in] weapon
Definition at line 1045 of file cg_ents.c.
Referenced by CG_Missile().
static void CG_EntityEffects (centity_t * cent) static
Add continuous entity effects, like local entity emission and lighting.
Parameters
[in,out] cent
Definition at line 222 of file cg_ents.c.
Referenced by CG_AddCEntity(), CG_AddEntityToTag(), and CG_AddLinkedEntity().
static void CG_EntityFloatText (centity_t * cent, const char * text, int height) static
CG_PlayerFloatText.
Parameters
[in] cent
[in] text
[in] height
Definition at line 1106 of file cg_ents.c.
Referenced by CG_Missile().
static void CG_Explosive (centity_t * cent) static
This is currently almost exactly the same as CG_Mover It's split out so that any changes or experiments are unattached to anything else.
Parameters
[in] cent
Definition at line 1569 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_General (centity_t * cent) static
CG_General.
Parameters
[in,out] cent
Definition at line 371 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_GetWindVector (vec3_t dir)
Compute random wind vector for smoke puff.
Parameters
[out] dir
Definition at line 349 of file cg_weapons.c.
Referenced by CG_AddLightstyle(), CG_Bullet(), CG_EntityEffects(), and CG_PyroSmokeTrail().
static void CG_InterpolateEntityPosition (centity_t * cent) static
CG_InterpolateEntityPosition.
Parameters
[in,out] cent
Todo:
? There are some cases when in Limbo mode during a map restart
Definition at line 2413 of file cg_ents.c.
Referenced by CG_CalcEntityLerpPositions().
static void CG_Item (centity_t * cent) static
CG_Item.
Parameters
[in] cent
Definition at line 647 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_Missile (centity_t * cent) static
CG_Missile.
Parameters
[in] cent
Todo:
: check FEATURE_EDV weapon cam (see else condition below)
Todo:
: anything to do/save for edv?
Definition at line 1121 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_MovePlane (centity_t * cent)
CG_MovePlane.
Parameters
[in] cent
Definition at line 1785 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_Mover (centity_t * cent) static
CG_Mover.
Parameters
[in,out] cent
Definition at line 1651 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_Mover_PostProcess (centity_t * cent)
CG_Mover_PostProcess.
Parameters
[in] cent
Definition at line 1885 of file cg_ents.c.
Referenced by CG_AddPacketEntities().
static int CG_PlayerCanPickupWeapon (int clientNum, weapon_t weapon) static
CG_PlayerCanPickupWeapon.
Parameters
[in] clientNum
[in] weapon
Definition at line 637 of file cg_ents.c.
Referenced by CG_Item().
qboolean CG_PlayerSeesItem (playerState_t * ps, entityState_t * item, int atTime, int itemType)
CG_PlayerSeesItem.
Parameters
[in] ps
[in] item
[in] atTime
itemType - unused
Returns
Todo:
: do this without AngleVectors.
Definition at line 587 of file cg_ents.c.
Referenced by CG_Item().
static void CG_Portal (centity_t * cent) static
CG_Portal.
Parameters
[in] cent
Definition at line 2042 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_PositionEntityOnTag (refEntity_t * entity, const refEntity_t * parent, const char * tagName, int startIndex, vec3_t * offset)
Modifies the entities position and axis by the given tag location.
Parameters
[in] entity
[in] parent
[in] tagName
[in] startIndex
[in] offset
Definition at line 47 of file cg_ents.c.
Referenced by CG_AddEntityToTag(), CG_AddFragment(), CG_AddPlayerWeapon(), CG_AttachBitsToTank(), CG_Cabinet(), CG_DrawPlayerHead(), CG_Item(), and CG_Player().
void CG_PositionRotatedEntityOnTag (refEntity_t * entity, const refEntity_t * parent, const char * tagName)
Modifies the entities position and axis by the given tag location.
Parameters
[in] entity
[in] parent
[in] tagName
Todo:
: allow origin offsets along tag?
Definition at line 77 of file cg_ents.c.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_AttachBitsToTank(), CG_GetBleedOrigin(), CG_MachineGunEjectBrass(), and CG_Player().
static void CG_ProcessEntity (centity_t * cent) static
CG_ProcessEntity.
Parameters
[in] cent
Note
All case aren't handle
Definition at line 2487 of file cg_ents.c.
Referenced by CG_AddCEntity(), CG_AddEntityToTag(), and CG_AddLinkedEntity().
static void CG_Prop (centity_t * cent) static
CG_Prop.
Parameters
[in] cent
Todo:
?)
Definition at line 2071 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_RocketTrail (centity_t * ent, const weaponInfo_t * wi)
New trail effects.
Parameters
[in,out] ent
wi - unused
Definition at line 476 of file cg_weapons.c.
Referenced by CG_DrawMineMarkerFlag(), CG_Missile(), and CG_RW_ParseClient().
void CG_RunLerpFrame (centity_t * cent, clientInfo_t * ci, lerpFrame_t * lf, int newAnimation, float speedScale)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
Parameters
[in] cent
[in] ci
[in,out] lf
[in] newAnimation
[in] speedScale
Definition at line 489 of file cg_players.c.
Referenced by CG_Trap().
void CG_ScanForCrosshairDyna (centity_t * cent)
CG_ScanForCrosshairDyna.
Mainly just a copy paste of CG_ScanForCrosshairMine
Parameters
cent
Definition at line 1421 of file cg_draw.c.
Referenced by CG_DrawMineMarkerFlag(), and CG_Missile().
void CG_ScanForCrosshairMine (centity_t * cent)
CG_ScanForCrosshairMine.
Parameters
[in] cent
Definition at line 1390 of file cg_draw.c.
Referenced by CG_DrawMineMarkerFlag(), and CG_Missile().
void CG_SetEntitySoundPosition (centity_t * cent)
Also called by event processing code.
Parameters
[in] cent
Definition at line 107 of file cg_ents.c.
Referenced by CG_CheckEvents(), and CG_EntityEffects().
void CG_SetupCabinets (void)
CG_SetupCabinets.
Definition at line 2311 of file cg_ents.c.
Referenced by CG_Init().
static void CG_Smoker (centity_t * cent) static
CG_Smoker.
Parameters
[in,out] cent
Todo:
: make this framerate independant?
Definition at line 981 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_Speaker (centity_t * cent) static
Speaker entities can automatically play sounds.
Parameters
[in,out] cent
Todo:
: use something other than clientNum...
Definition at line 562 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_Trap (centity_t * cent) static
CG_Trap.
Parameters
[in] cent
Todo:
Change from 'trap' to something else. 'trap' is a misnomer. it's actually used for other stuff too
Definition at line 1454 of file cg_ents.c.
Referenced by CG_ProcessEntity().
static void CG_TrapSetAnim (centity_t * cent, lerpFrame_t * lf, int newAnim) static
CG_TrapSetAnim.
Parameters
[in] cent
[in,out] lf
newAnim - unused
Definition at line 1431 of file cg_ents.c.
Referenced by CG_Trap().
void CGRefEntityToTag (refEntity_t * ent, tag_t * tag)
CGRefEntityToTag.
Parameters
[in] ent
[out] tag
Definition at line 2997 of file cg_ents.c.
Referenced by CG_AttachBitsToTank().
void CGTagToRefEntity (refEntity_t * ent, tag_t * tag)
CGTagToRefEntity.
Parameters
[in] ent
[out] tag
Definition at line 3013 of file cg_ents.c.
Referenced by CG_AttachBitsToTank().
Variable Documentation
cabinetTag_t cabinetInfo[CT_MAX]
Definition at line 2193 of file cg_ents.c.
animation_t multi_flagpoleAnims[] static
Initial value:
=
{
    { 0, "", 0,   1,   0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 0,   15,  0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 490, 15,  0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 20,  211, 211, 1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 255, 211, 211, 1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 235, 15,  0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 470, 15,  0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 510, 15,  0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 },
    { 0, "", 530, 15,  0,   1000 / 15, 1000 / 15, 0, 0, 0, 0, 0, 0 }
}
Definition at line 1410 of file cg_ents.c.