ET: Legacy: src/cgame/cg_event.c File Reference
cg_event.c File Reference
Handle entity events at snapshot or playerstate transitions.
#include "cg_local.h"
#include "../game/bg_local.h"
Data Structures
struct fxSound_s
Macros
#define POSSIBLE_PIECES 6
#define POSSIBLE_PIECES 6
Typedefs
typedef struct fxSound_s fxSound_t
Functions
void CG_StartShakeCamera (float param)
CG_StartShakeCamera.
void CG_Tracer (vec3_t source, vec3_t dest, int sparks)
CG_Tracer.
void CG_GetObituaryIcon (meansOfDeath_t mod, weapon_t weapon, qhandle_t *weaponShader, int *scaleShader)
CG_GetObituaryIcon.
static void CG_Obituary (entityState_t *ent)
CG_Obituary.
int CG_WeaponIndex (int weapnum, int *bank, int *cycle)
CG_WeaponIndex.
static void CG_ItemPickup (int itemNum)
A new item was picked up this frame.
void CG_PainEvent (centity_t *cent, int health, qboolean crouching)
Also called by playerstate transition.
void CG_PrecacheFXSounds (void)
CG_PrecacheFXSounds.
void CG_Explodef (vec3_t origin, vec3_t dir, int mass, int type, qhandle_t sound, int forceLowGrav, qhandle_t shader)
Made this more generic for spawning hits and breaks without needing a *cent.
void CG_RubbleFx (vec3_t origin, vec3_t dir, int mass, int type, sfxHandle_t sound, int forceLowGrav, qhandle_t shader, float speedscale, float sizescale)
CG_RubbleFx.
static sfxHandle_t CG_GetSoundFx (centity_t *cent)
CG_GetSfxSound.
void CG_Explode (centity_t *cent, vec3_t origin, vec3_t dir, qhandle_t shader)
The old cent-based explode calls will still work with this pass-through if (cent->currentState.angles2[0] || cent->currentState.angles2[1] || cent->currentState.angles2[2])
void CG_Rubble (centity_t *cent, vec3_t origin, vec3_t dir, qhandle_t shader)
CG_Rubble.
void CG_Effect (centity_t *cent, vec3_t origin, vec3_t dir)
Quake ed -> target_effect (0 .5 .8) (-6 -6 -6) (6 6 6) fire explode smoke debris gore lowgrav.
void CG_Shard (centity_t *cent, vec3_t origin, vec3_t dir)
CG_Shard.
void CG_ShardJunk (vec3_t origin, vec3_t dir)
CG_ShardJunk.
void CG_Debris (centity_t *cent, vec3_t origin, vec3_t dir)
Debris test.
void CG_MortarImpact (centity_t *cent, vec3_t origin)
CG_MortarImpact.
void CG_MortarMiss (centity_t *cent, vec3_t origin)
CG_MortarMiss.
void CG_PlayGlobalSound (centity_t *cent, int index)
CG_PlayGlobalSound.
void CG_AddBulletParticles (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddBulletParticles.
void CG_EntityEvent (centity_t *cent, vec3_t position)
An entity has an event value also called by CG_CheckPlayerstateEvents.
void CG_CheckEvents (centity_t *cent)
CG_CheckEvents.
Variables
static vec3_t OB_YELLOW = { 1.f, 1.f, 0.f }
static vec3_t OB_RED = { 1.f, 0.f, 0.f }
static fxSound_t fxSounds [FXTYPE_MAX]
Detailed Description
Handle entity events at snapshot or playerstate transitions.
Definition in file cg_event.c.
Macro Definition Documentation
#define POSSIBLE_PIECES 6
Definition at line 992 of file cg_event.c.
Referenced by CG_Explodef(), and CG_RubbleFx().
#define POSSIBLE_PIECES 6
Definition at line 992 of file cg_event.c.
Typedef Documentation
typedef struct fxSound_s fxSound_t
Function Documentation
void CG_AddBulletParticles (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddBulletParticles.
Parameters
[in] origin
[in] dir
[in] speed
duration - unused
[in] count
[in] randScale
Definition at line 5026 of file cg_weapons.c.
Referenced by CG_BulletImpact(), CG_EntityEvent(), CG_MeleeImpact(), and CG_PlayGlobalSound().
void CG_CheckEvents (centity_t * cent)
CG_CheckEvents.
Parameters
[in] cent
Definition at line 2874 of file cg_event.c.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionEntity().
void CG_Debris (centity_t * cent, vec3_t origin, vec3_t dir)
Debris test.
Parameters
[in] cent
[in] origin
[in] dir
Definition at line 1718 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_Effect (centity_t * cent, vec3_t origin, vec3_t dir)
Quake ed -> target_effect (0 .5 .8) (-6 -6 -6) (6 6 6) fire explode smoke debris gore lowgrav.
Parameters
[in] cent
[in] origin
[in] dir
Todo:
: don't do this here. only for testing
Todo:
: add eventParm & 64 and throw extended debris
Definition at line 1377 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_EntityEvent (centity_t * cent, vec3_t position)
An entity has an event value also called by CG_CheckPlayerstateEvents.
Parameters
[in] cent
[in] position
Todo:
: CHAN_LOCAL_SOUND ?
Todo:
: handle theses
Definition at line 1878 of file cg_event.c.
Referenced by CG_CheckEvents(), and CG_CheckPlayerstateEvents().
void CG_Explode (centity_t * cent, vec3_t origin, vec3_t dir, qhandle_t shader)
The old cent-based explode calls will still work with this pass-through if (cent->currentState.angles2[0] || cent->currentState.angles2[1] || cent->currentState.angles2[2])
Parameters
[in] cent
[in] origin
[in] dir
[in] shader
Todo:
: do this at spawn time rather than explode time so any new necessary shaders are created earlier
Definition at line 549 of file cg_event.c.
Referenced by CG_Effect(), and CG_EntityEvent().
void CG_Explodef (vec3_t origin, vec3_t dir, int mass, int type, qhandle_t sound, int forceLowGrav, qhandle_t shader)
Made this more generic for spawning hits and breaks without needing a *cent.
Parameters
[in] origin
[in] dir
[in] mass
[in] type
[in] sound
[in] forceLowGrav
[in] shader
Definition at line 1004 of file cg_event.c.
Referenced by CG_AddEmitter(), CG_AddFragment(), CG_Explode(), and CG_PrecacheFXSounds().
void CG_GetObituaryIcon (meansOfDeath_t mod, weapon_t weapon, qhandle_t * weaponShader, int * scaleShader)
CG_GetObituaryIcon.
Parameters
[in] mod
[in] weapon
[out] weaponShader
[out] scaleShader
Todo:
:
Definition at line 55 of file cg_event.c.
Referenced by CG_Obituary().
static sfxHandle_t CG_GetSoundFx (centity_t * cent) static
CG_GetSfxSound.
Parameters
[in] cent
Returns
Definition at line 512 of file cg_event.c.
Referenced by CG_Explode(), and CG_Rubble().
static void CG_ItemPickup (int itemNum) static
A new item was picked up this frame.
Parameters
[in] itemNum
Todo:
: this works fine for predicted pickups (when you walk over the weapon), but not for
Definition at line 327 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_MortarImpact (centity_t * cent, vec3_t origin)
CG_MortarImpact.
Parameters
[in] cent
[in] origin
Definition at line 1763 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_MortarMiss (centity_t * cent, vec3_t origin)
CG_MortarMiss.
Parameters
[in] cent
[in] origin
Definition at line 1778 of file cg_event.c.
Referenced by CG_EntityEvent().
static void CG_Obituary (entityState_t * ent) static
CG_Obituary.
Parameters
[in] ent
Todo:
FIXME: ... some MODs are not caught - check all!
MOD_CRUSH_X is selfkill only
Definition at line 124 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_PainEvent (centity_t * cent, int health, qboolean crouching)
Also called by playerstate transition.
Parameters
[in] cent
[in] health - unused
[in] crouching - unused
Definition at line 448 of file cg_event.c.
Referenced by CG_CheckLocalSounds(), and CG_EntityEvent().
void CG_PlayGlobalSound (centity_t * cent, int index)
CG_PlayGlobalSound.
Parameters
[in] cent
[in] index
Definition at line 1800 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_PrecacheFXSounds (void)
CG_PrecacheFXSounds.
Definition at line 491 of file cg_event.c.
Referenced by CG_RegisterSounds().
void CG_Rubble (centity_t * cent, vec3_t origin, vec3_t dir, qhandle_t shader)
CG_Rubble.
Parameters
[in] cent
[in] origin
[in] dir
[in] shader
Todo:
: do this at spawn time rather than explode time so any new necessary shaders are created earlier
Definition at line 584 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_RubbleFx (vec3_t origin, vec3_t dir, int mass, int type, sfxHandle_t sound, int forceLowGrav, qhandle_t shader, float speedscale, float sizescale)
CG_RubbleFx.
Parameters
[in] origin
[in] dir
[in] mass
[in] type
[in] sound
[in] forceLowGrav
[in] shader
[in] speedscale
[in] sizescale
Todo:
: need to look into this so that they fade out correctly
Definition at line 626 of file cg_event.c.
Referenced by CG_PrecacheFXSounds(), and CG_Rubble().
void CG_Shard (centity_t * cent, vec3_t origin, vec3_t dir)
CG_Shard.
Parameters
[in] cent
[in] origin
[in] dir
Note
We should keep this separate since there will be considerable differences in the physical properties of shard vrs debris. not to mention the fact there is no way we can quantify what type of effects the designers will potentially desire. If it is still possible to merge the functionality of cg_shard into cg_explode at a latter time I would have no problem with that but for now I want to keep it separate
Definition at line 1512 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_ShardJunk (vec3_t origin, vec3_t dir)
CG_ShardJunk.
Parameters
[in] origin
[in] dir
Definition at line 1667 of file cg_event.c.
Referenced by CG_EntityEvent().
void CG_StartShakeCamera (float p)
CG_StartShakeCamera.
Parameters
[in] p
Definition at line 3748 of file cg_draw.c.
Referenced by CG_EntityEvent().
void CG_Tracer (const vec3_t source, const vec3_t dest, int sparks)
CG_Tracer.
Parameters
[in] source
[in] dest
[in] sparks
Definition at line 6036 of file cg_weapons.c.
Referenced by CG_Bullet(), and CG_EntityEvent().
int CG_WeaponIndex (int weapnum, int * bank, int * cycle)
CG_WeaponIndex.
Parameters
[in] weapnum
[in,out] bank
[in,out] cycle
Returns
Definition at line 3441 of file cg_weapons.c.
Referenced by CG_FinishWeaponChange(), CG_ItemPickup(), CG_NextWeap(), CG_Obituary(), CG_PrevWeap(), CG_WeaponBank_f(), getNextWeapInBankBynum(), and getPrevWeapInBankBynum().
Variable Documentation
fxSound_t fxSounds[FXTYPE_MAX] static
Initial value:
=
{
    { 1, { -1, -1, -1 }, { "sound/world/boardbreak.wav",  NULL,                          NULL                          } },
    { 3, { -1, -1, -1 }, { "sound/world/glassbreak1.wav", "sound/world/glassbreak2.wav", "sound/world/glassbreak3.wav" } },
    { 1, { -1, -1, -1 }, { "sound/world/metalbreak.wav",  NULL,                          NULL                          } },
    { 1, { -1, -1, -1 }, { "sound/player/gib.wav",        NULL,                          NULL                          } },
    { 1, { -1, -1, -1 }, { "sound/world/debris1.wav",     NULL,                          NULL                          } },
    { 1, { -1, -1, -1 }, { "sound/world/stonefall.wav",   NULL,                          NULL                          } },
    { 1, { -1, -1, -1 }, { "sound/world/fabricbreak.wav", NULL,                          NULL                          } }
}
Definition at line 470 of file cg_event.c.
vec3_t OB_RED = { 1.f, 0.f, 0.f } static
Definition at line 46 of file cg_event.c.
Referenced by CG_Obituary().
vec3_t OB_YELLOW = { 1.f, 1.f, 0.f } static
Definition at line 45 of file cg_event.c.
Referenced by CG_Obituary().