ET: Legacy: src/cgame/cg_localents.c File Reference
cg_localents.c File Reference
Every frame, generate renderer commands for locally processed entities, like smoke puffs, gibs, shells, etc.
#include "cg_local.h"
Macros
#define MAX_LOCAL_ENTITIES 768
#define MAX_BUFFER 32768
Functions
location_t * CG_GetLocation (int client, vec3_t origin)
CG_GetLocation.
char * CG_GetLocationMsg (int clientNum, vec3_t origin)
CG_GetLocationMsg.
char * CG_BuildLocationString (int clientNum, vec3_t origin, int flag)
CG_BuildLocationString.
void CG_LoadLocations (void)
Report a location for the player. Uses placed nearby target_location entities.
void CG_InitLocalEntities (void)
This is called at startup and for tournement restarts.
void CG_FreeLocalEntity (localEntity_t *le)
CG_FreeLocalEntity.
localEntity_t * CG_FindLocalEntity (int index, int sideNum)
CG_FindLocalEntity.
localEntity_t * CG_AllocLocalEntity (void)
CG_AllocLocalEntity.
void CG_BloodTrail (localEntity_t *le)
Leave expanding blood puffs behind gibs.
void CG_FragmentBounceMark (localEntity_t *le, trace_t *trace)
CG_FragmentBounceMark.
void CG_FragmentBounceSound (localEntity_t *le, trace_t *trace)
CG_FragmentBounceSound.
void CG_ReflectVelocity (localEntity_t *le, trace_t *trace)
CG_ReflectVelocity.
void CG_AddEmitter (localEntity_t *le)
CG_AddEmitter.
void CG_Explodef (vec3_t origin, vec3_t dir, int mass, int type, qhandle_t sound, int forceLowGrav, qhandle_t shader)
Made this more generic for spawning hits and breaks without needing a *cent.
void CG_AddFragment (localEntity_t *le)
CG_AddFragment.
void CG_AddMovingTracer (localEntity_t *le)
CG_AddMovingTracer.
void CG_AddSparkElements (localEntity_t *le)
CG_AddSparkElements.
void CG_AddFuseSparkElements (localEntity_t *le)
CG_AddFuseSparkElements.
void CG_AddBloodElements (localEntity_t *le)
CG_AddBloodElements.
void CG_AddDebrisElements (localEntity_t *le)
CG_AddDebrisElements.
void CG_AddDebrisElementsExtended (localEntity_t *le)
CG_AddDebrisElementsExtended.
void CG_AddFadeRGB (localEntity_t *le)
CG_AddFadeRGB.
void CG_AddConstRGB (localEntity_t *le)
CG_AddConstRGB.
static void CG_AddMoveScaleFade (localEntity_t *le)
CG_AddMoveScaleFade.
static void CG_AddScaleFade (localEntity_t *le)
CG_AddScaleFade.
static void CG_AddFallScaleFade (localEntity_t *le)
CG_AddFallScaleFade.
static void CG_AddExplosion (localEntity_t *ex)
CG_AddExplosion.
static void CG_AddSpriteExplosion (localEntity_t *le)
CG_AddSpriteExplosion.
void CG_AddLocalEntities (void)
CG_AddLocalEntities.
Variables
localEntity_t cg_localEntities [MAX_LOCAL_ENTITIES]
localEntity_t cg_activeLocalEntities
localEntity_t * cg_freeLocalEntities
int localEntCount = 0
Detailed Description
Every frame, generate renderer commands for locally processed entities, like smoke puffs, gibs, shells, etc.
Definition in file cg_localents.c.
Macro Definition Documentation
#define MAX_BUFFER 32768
Definition at line 182 of file cg_localents.c.
Referenced by CG_LoadLocations().
#define MAX_LOCAL_ENTITIES 768
Definition at line 41 of file cg_localents.c.
Referenced by CG_InitLocalEntities().
Function Documentation
void CG_AddBloodElements (localEntity_t * le)
CG_AddBloodElements.
Parameters
[in,out] le
Todo:
: spawn a blood decal here?
Definition at line 1177 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddConstRGB (localEntity_t * le)
CG_AddConstRGB.
Parameters
[in] le
Definition at line 1429 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddDebrisElements (localEntity_t * le)
CG_AddDebrisElements.
Parameters
[in,out] le
Definition at line 1240 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddDebrisElementsExtended (localEntity_t * le)
CG_AddDebrisElementsExtended.
Parameters
[in,out] le
Todo:
: don't bounce at sky?
Definition at line 1326 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddEmitter (localEntity_t * le)
CG_AddEmitter.
Parameters
[in,out] le
Definition at line 694 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
static void CG_AddExplosion (localEntity_t * ex) static
CG_AddExplosion.
Parameters
[in] ex
Definition at line 1556 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddFadeRGB (localEntity_t * le)
CG_AddFadeRGB.
Parameters
[in] le
Definition at line 1410 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
static void CG_AddFallScaleFade (localEntity_t * le) static
CG_AddFallScaleFade.
This is just an optimized CG_AddMoveScaleFade For blood mists that drift down, fade out, and are removed if the view passes through them. There are often 100+ of these, so it needs to be simple.
Parameters
[in] le
Definition at line 1528 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddFragment (localEntity_t * le)
CG_AddFragment.
Parameters
[in,out] le
Todo:
: this is not quite right, because it'll become fps dependant - in a bad way.
Todo:
: limit local ent usage and cap this at N gib model ents in total for client? cvar? 0 = off, N = value
Definition at line 715 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddFuseSparkElements (localEntity_t * le)
CG_AddFuseSparkElements.
Parameters
[in,out] le
Definition at line 1145 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddLocalEntities (void)
CG_AddLocalEntities.
Todo:
merge with CG_AddDebrisElements
Definition at line 1640 of file cg_localents.c.
Referenced by CG_DrawActiveFrame().
static void CG_AddMoveScaleFade (localEntity_t * le) static
CG_AddMoveScaleFade.
Parameters
[in] le
Definition at line 1445 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddMovingTracer (localEntity_t * le)
CG_AddMovingTracer.
Parameters
[in] le
Definition at line 1047 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
static void CG_AddScaleFade (localEntity_t * le) static
CG_AddScaleFade.
For rocket smokes that hang in place, fade out, and are removed if the view passes through them. There are often many of these, so it needs to be simple.
Parameters
[in] le
Definition at line 1496 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
void CG_AddSparkElements (localEntity_t * le)
CG_AddSparkElements.
Parameters
[in,out] le
Definition at line 1062 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
static void CG_AddSpriteExplosion (localEntity_t * le) static
CG_AddSpriteExplosion.
Parameters
[in] le
Definition at line 1590 of file cg_localents.c.
Referenced by CG_AddLocalEntities().
localEntity_t* CG_AllocLocalEntity (void)
CG_AllocLocalEntity.
Will allways succeed, even if it requires freeing an old active entity
Returns
Definition at line 427 of file cg_localents.c.
Referenced by CG_AddBloodTrails(), CG_AddDebris(), CG_AddFragment(), CG_AddSparks(), CG_BubbleTrail(), CG_Debris(), CG_Effect(), CG_EntityEvent(), CG_Explodef(), CG_LaunchGib(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_MakeExplosion(), CG_PanzerFaustEjectBrass(), CG_RailTrail2(), CG_RubbleFx(), CG_Shard(), CG_ShardJunk(), CG_SmokePuff(), CG_SparklerSparks(), CG_SpawnTracer(), and CG_WaterRipple().
void CG_BloodTrail (localEntity_t * le)
Leave expanding blood puffs behind gibs.
Parameters
le
Definition at line 470 of file cg_localents.c.
Referenced by CG_AddFragment().
char* CG_BuildLocationString (int clientNum, vec3_t origin, int flag)
CG_BuildLocationString.
Parameters
[in] clientNum
[in] origin
[in] flag
Returns
Definition at line 135 of file cg_localents.c.
Referenced by CG_DrawFireTeamOverlay(), CG_GetPMItemText(), CG_ServerCommand(), and CG_VoiceChatLocal().
void CG_Explodef (vec3_t origin, vec3_t dir, int mass, int type, qhandle_t sound, int forceLowGrav, qhandle_t shader)
Made this more generic for spawning hits and breaks without needing a *cent.
Parameters
[in] origin
[in] dir
[in] mass
[in] type
[in] sound
[in] forceLowGrav
[in] shader
Definition at line 1004 of file cg_event.c.
Referenced by CG_AddEmitter(), CG_AddFragment(), CG_Explode(), and CG_PrecacheFXSounds().
localEntity_t* CG_FindLocalEntity (int index, int sideNum)
CG_FindLocalEntity.
Will allways succeed, even if it requires freeing an old active entity
Parameters
[in] index
[in] sideNum
Returns
Definition at line 405 of file cg_localents.c.
Referenced by CG_RailTrail2().
void CG_FragmentBounceMark (localEntity_t * le, trace_t * trace)
CG_FragmentBounceMark.
Parameters
[in,out] le
[in] trace
Definition at line 541 of file cg_localents.c.
Referenced by CG_AddFragment().
void CG_FragmentBounceSound (localEntity_t * le, trace_t * trace)
CG_FragmentBounceSound.
Parameters
[in] le
[in] trace
Definition at line 580 of file cg_localents.c.
Referenced by CG_AddDebrisElementsExtended(), and CG_AddFragment().
void CG_FreeLocalEntity (localEntity_t * le)
CG_FreeLocalEntity.
Parameters
le
Definition at line 378 of file cg_localents.c.
Referenced by CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddLocalEntities(), CG_AddMoveScaleFade(), CG_AddScaleFade(), CG_AddSparkElements(), and CG_AllocLocalEntity().
location_t* CG_GetLocation (int client, vec3_t origin)
CG_GetLocation.
Parameters
[in] client
[in] origin
Returns
Definition at line 57 of file cg_localents.c.
Referenced by CG_GetLocationMsg().
char* CG_GetLocationMsg (int clientNum, vec3_t origin)
CG_GetLocationMsg.
Parameters
[in] clientNum
[in] origin
Returns
Definition at line 110 of file cg_localents.c.
Referenced by CG_BuildLocationString().
void CG_InitLocalEntities (void)
This is called at startup and for tournement restarts.
Definition at line 357 of file cg_localents.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_LoadLocations (void)
Report a location for the player. Uses placed nearby target_location entities.
Definition at line 186 of file cg_localents.c.
Referenced by CG_Init().
void CG_ReflectVelocity (localEntity_t * le, trace_t * trace)
CG_ReflectVelocity.
Parameters
[in,out] le
[in] trace
Definition at line 649 of file cg_localents.c.
Referenced by CG_AddBloodElements(), CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), and CG_AddFragment().
Variable Documentation
localEntity_t cg_activeLocalEntities
Definition at line 45 of file cg_localents.c.
Referenced by CG_AddLocalEntities(), CG_AllocLocalEntity(), and CG_InitLocalEntities().
localEntity_t* cg_freeLocalEntities
Definition at line 46 of file cg_localents.c.
Referenced by CG_AllocLocalEntity(), and CG_FreeLocalEntity().
localEntity_t cg_localEntities[MAX_LOCAL_ENTITIES]
Definition at line 44 of file cg_localents.c.
Referenced by CG_InitLocalEntities().
int localEntCount = 0
Definition at line 49 of file cg_localents.c.
Referenced by CG_AllocLocalEntity(), CG_FindLocalEntity(), CG_FreeLocalEntity(), and CG_InitLocalEntities().