ET: Legacy: src/cgame/cg_info.c File Reference
cg_info.c File Reference
Display information while data is being loaded.
#include "cg_local.h"
Macros
#define COLOR_BG { 0.0f, 0.0f, 0.0f, 0.6f }
#define COLOR_BG_TITLE { 0.16f, 0.2f, 0.17f, 0.8f }
#define COLOR_BG_VIEW { 0.16f, 0.2f, 0.17f, 0.8f }
#define COLOR_BORDER { 0.5f, 0.5f, 0.5f, 0.5f }
#define COLOR_BORDER_TITLE { 0.1f, 0.1f, 0.1f, 0.2f }
#define COLOR_BORDER_VIEW { 0.2f, 0.2f, 0.2f, 0.4f }
#define COLOR_TEXT { 0.6f, 0.6f, 0.6f, 1.0f }
#define FONT_HEADER &cgs.media.limboFont1
#define FONT_SUBHEADER &cgs.media.limboFont1_lo
#define FONT_TEXT &cgs.media.limboFont2
#define GS_Y 10
#define GS_W 298
#define TS_X -80
#define TS_Y -60
#define TS_W 396
#define OBJ_X -80
#define OBJ_W 308
#define DH_X -22
#define DH_Y -60
#define DH_W 148
Functions
void CG_LoadingString (const char *s)
CG_LoadingString.
void CG_DrawInformation (qboolean forcerefresh)
Draw all the status / pacifier stuff during level loading.
void CG_ShowHelp_On (int *status)
CG_ShowHelp_On.
void CG_ShowHelp_Off (int *status)
CG_ShowHelp_Off.
void CG_DemoControlButtonRender (panel_button_t *button)
CG_DemoControlButtonRender.
qboolean CG_DemoControlButtonDown (panel_button_t *button, int key)
CG_DemoControlButtonDown.
qboolean CG_DemoControlButtonUp (panel_button_t *button, int key)
CG_DemoControlButtonUp.
void CG_DemoClick (int key, qboolean down)
Demo playback key catcher support.
void CG_GameStatsDraw (void)
CG_GameStatsDraw.
void CG_TopShotsDraw (void)
CG_TopShotsDraw.
void CG_ObjectivesDraw ()
CG_ObjectivesDraw.
void CG_DrawDemoControls (int x, int y, int w, vec4_t borderColor, vec4_t bgColor, int tSpacing, vec4_t bgColorTitle, vec4_t borderColorTitle, float hScale, float hScaleY, vec4_t hdrColor, int hStyle, fontHelper_t *hFont)
CG_DrawDemoControls.
void CG_DemoHelpDraw (void)
CG_DemoHelpDraw.
char * CG_getBindKeyName (const char *cmd, char *buf, size_t len)
CG_getBindKeyName.
void CG_DrawOverlays (void)
CG_DrawOverlays.
Variables
const vec4_t color_bg_title = COLOR_BG_TITLE
const vec4_t color_border1 = COLOR_BORDER
const vec4_t color_bg = COLOR_BG_VIEW
const vec4_t color_border = COLOR_BORDER_VIEW
panel_button_t demoSliderButton
panel_button_t demoRewindButton
panel_button_t demoPauseButton
panel_button_t demoFFButton
static panel_button_t * demoControlButtons []
Detailed Description
Display information while data is being loaded.
Definition in file cg_info.c.
Macro Definition Documentation
#define COLOR_BG { 0.0f, 0.0f, 0.0f, 0.6f }
Definition at line 39 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define COLOR_BG_TITLE { 0.16f, 0.2f, 0.17f, 0.8f }
Definition at line 40 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define COLOR_BG_VIEW { 0.16f, 0.2f, 0.17f, 0.8f }
Definition at line 41 of file cg_info.c.
#define COLOR_BORDER { 0.5f, 0.5f, 0.5f, 0.5f }
Definition at line 42 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define COLOR_BORDER_TITLE { 0.1f, 0.1f, 0.1f, 0.2f }
Definition at line 43 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define COLOR_BORDER_VIEW { 0.2f, 0.2f, 0.2f, 0.4f }
Definition at line 44 of file cg_info.c.
#define COLOR_TEXT { 0.6f, 0.6f, 0.6f, 1.0f }
Definition at line 45 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define DH_W 148
Definition at line 1611 of file cg_info.c.
Referenced by CG_DemoHelpDraw().
#define DH_X -22
Definition at line 1609 of file cg_info.c.
Referenced by CG_DemoHelpDraw().
#define DH_Y -60
Definition at line 1610 of file cg_info.c.
Referenced by CG_DemoHelpDraw().
#define FONT_HEADER &cgs.media.limboFont1
Definition at line 47 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define FONT_SUBHEADER &cgs.media.limboFont1_lo
Definition at line 48 of file cg_info.c.
Referenced by CG_GameStatsDraw(), and CG_TopShotsDraw().
#define FONT_TEXT &cgs.media.limboFont2
Definition at line 49 of file cg_info.c.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_ObjectivesDraw(), and CG_TopShotsDraw().
#define GS_W 298
Definition at line 827 of file cg_info.c.
Referenced by CG_GameStatsDraw().
#define GS_Y 10
Definition at line 826 of file cg_info.c.
Referenced by CG_GameStatsDraw().
#define OBJ_W 308
Definition at line 1174 of file cg_info.c.
Referenced by CG_ObjectivesDraw().
#define OBJ_X -80
Definition at line 1172 of file cg_info.c.
Referenced by CG_ObjectivesDraw().
#define TS_W 396
Definition at line 1037 of file cg_info.c.
Referenced by CG_TopShotsDraw().
#define TS_X -80
Definition at line 1035 of file cg_info.c.
Referenced by CG_TopShotsDraw().
#define TS_Y -60
Definition at line 1036 of file cg_info.c.
Referenced by CG_ObjectivesDraw(), and CG_TopShotsDraw().
Function Documentation
void CG_DemoClick (int key, qboolean down)
Demo playback key catcher support.
Parameters
[in] key
[in] down
Definition at line 324 of file cg_info.c.
Referenced by CG_KeyEvent().
qboolean CG_DemoControlButtonDown (panel_button_t * button, int key)
CG_DemoControlButtonDown.
Parameters
[in] button
[in] key
Returns
Definition at line 208 of file cg_info.c.
void CG_DemoControlButtonRender (panel_button_t * button)
CG_DemoControlButtonRender.
Parameters
[in] button
Definition at line 179 of file cg_info.c.
qboolean CG_DemoControlButtonUp (panel_button_t * button, int key)
CG_DemoControlButtonUp.
Parameters
button - unused
key - unused
Note
This function is empty and return always qfalse
Returns
Always qfalse
Definition at line 249 of file cg_info.c.
void CG_DemoHelpDraw (void)
CG_DemoHelpDraw.
Todo:
: Should compute this beforehand
Definition at line 1677 of file cg_info.c.
Referenced by CG_DrawOverlays().
void CG_DrawDemoControls (int x, int y, int w, vec4_t borderColor, vec4_t bgColor, int tSpacing, vec4_t bgColorTitle, vec4_t borderColorTitle, float hScale, float hScaleY, vec4_t hdrColor, int hStyle, fontHelper_t * hFont)
CG_DrawDemoControls.
Parameters
[in] x
[in] y
[in] w
[in] borderColor
[in] bgColor
[in] tSpacing
[in] bgColorTitle
[in] borderColorTitle
[in] hScale
[in] hScaleY
[in] hdrColor
[in] hStyle
[in] hFont
Definition at line 1629 of file cg_info.c.
Referenced by CG_DemoHelpDraw().
void CG_DrawInformation (qboolean forcerefresh)
Draw all the status / pacifier stuff during level loading.
Parameters
[in] forcerefresh
Todo:
: dynamic game server MOTD window
Definition at line 83 of file cg_info.c.
Referenced by CG_DrawActive(), CG_DrawActiveFrame(), trap_CM_LoadMap(), trap_R_LoadWorldMap(), trap_R_RegisterFont(), trap_R_RegisterModel(), trap_R_RegisterShader(), trap_R_RegisterShaderNoMip(), trap_R_RegisterSkin(), trap_S_RegisterSound(), and trap_TranslateString().
void CG_DrawOverlays (void)
CG_DrawOverlays.
Definition at line 2132 of file cg_info.c.
Referenced by CG_Draw2D().
void CG_GameStatsDraw (void)
CG_GameStatsDraw.
Todo:
: Should derive from CG_Text_Height_Ext
Todo:
: Should compute this beforehand
Definition at line 832 of file cg_info.c.
Referenced by CG_DrawOverlays().
char* CG_getBindKeyName (const char * cmd, char * buf, size_t len)
CG_getBindKeyName.
Parameters
[in] cmd
[out] buf
[in] len
Returns
Definition at line 1950 of file cg_info.c.
void CG_LoadingString (const char * s)
CG_LoadingString.
Parameters
[in] s
Definition at line 68 of file cg_info.c.
Referenced by CG_Init(), and CG_RegisterGraphics().
void CG_ObjectivesDraw ()
CG_ObjectivesDraw.
Todo:
: Should compute this beforehand
Definition at line 1179 of file cg_info.c.
Referenced by CG_DrawOverlays().
void CG_ShowHelp_Off (int * status)
CG_ShowHelp_Off.
Parameters
[in,out] status
Definition at line 156 of file cg_info.c.
Referenced by CG_DemoClick(), CG_dumpStats_f(), and CG_EventHandling().
void CG_ShowHelp_On (int * status)
CG_ShowHelp_On.
Parameters
[in,out] status
Definition at line 136 of file cg_info.c.
Referenced by CG_DemoClick(), CG_dumpStats_f(), CG_keyOn_f(), CG_SetInitialSnapshot(), and CG_UpdateCvars().
void CG_TopShotsDraw (void)
CG_TopShotsDraw.
Todo:
: Should compute this beforehand
Definition at line 1042 of file cg_info.c.
Referenced by CG_DrawOverlays().
Variable Documentation
const vec4_t color_bg = COLOR_BG_VIEW
Definition at line 53 of file cg_info.c.
const vec4_t color_bg_title = COLOR_BG_TITLE
Definition at line 51 of file cg_info.c.
Referenced by CG_DemoControlButtonRender().
const vec4_t color_border = COLOR_BORDER_VIEW
Definition at line 54 of file cg_info.c.
Referenced by CG_DemoControlButtonRender().
const vec4_t color_border1 = COLOR_BORDER
Definition at line 52 of file cg_info.c.
Referenced by CG_DemoControlButtonRender().
panel_button_t* demoControlButtons[] static
Initial value:
=
{
    &demoSliderButton,
    &demoRewindButton,
    &demoPauseButton,
    &demoFFButton,
    NULL
}
Definition at line 310 of file cg_info.c.
panel_button_t demoFFButton
Initial value:
=
{
    NULL,
    ">>",
    { 0,                       0,  0, 0 },
    { 3,                       0,  0, 0, 0, 0, 0, 0},
    NULL,
    CG_DemoControlButtonDown,
    CG_DemoControlButtonUp,
    CG_DemoControlButtonRender,
    NULL,
    0
}
Definition at line 296 of file cg_info.c.
panel_button_t demoPauseButton
Initial value:
=
{
    NULL,
    "||",
    { 0,                       0,  0, 0 },
    { 2,                       0,  0, 0, 0, 0, 0, 0},
    NULL,
    CG_DemoControlButtonDown,
    CG_DemoControlButtonUp,
    CG_DemoControlButtonRender,
    NULL,
    0
}
Definition at line 282 of file cg_info.c.
panel_button_t demoRewindButton
Initial value:
=
{
    NULL,
    "<<",
    { 0,                       0,  0, 0 },
    { 1,                       0,  0, 0, 0, 0, 0, 0},
    NULL,
    CG_DemoControlButtonDown,
    CG_DemoControlButtonUp,
    CG_DemoControlButtonRender,
    NULL,
    0
}
Definition at line 268 of file cg_info.c.
panel_button_t demoSliderButton
Initial value:
=
{
    NULL,
    NULL,
    { 0,                       0,  0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    NULL,
    CG_DemoControlButtonDown,
    CG_DemoControlButtonUp,
    CG_DemoControlButtonRender,
    NULL,
    0
}
Definition at line 254 of file cg_info.c.