ET: Legacy: src/cgame/cg_missionbriefing.c File Reference
cg_missionbriefing.c File Reference
#include "cg_local.h"
Functions
const char * CG_DescriptionForCampaign (void)
CG_DescriptionForCampaign.
const char * CG_NameForCampaign (void)
CG_NameForCampaign.
qboolean CG_FindCampaignInFile (const char *filename, const char *campaignShortName, cg_campaignInfo_t *info)
CG_FindCampaignInFile.
qboolean CG_FindArenaInfo (const char *filename, const char *mapname, arenaInfo_t *info)
CG_FindArenaInfo.
void CG_LocateCampaign (void)
CG_LocateCampaign.
void CG_LocateArena (void)
CG_LocateArena.
Function Documentation
const char* CG_DescriptionForCampaign (void)
CG_DescriptionForCampaign.
Returns
Definition at line 41 of file cg_missionbriefing.c.
Referenced by CG_LoadHudMenu().
qboolean CG_FindArenaInfo (const char * filename, const char * mapname, arenaInfo_t * info)
CG_FindArenaInfo.
Parameters
[in] filename
[in] mapname
[in] info
Returns
Definition at line 233 of file cg_missionbriefing.c.
Referenced by CG_LocateArena(), CG_LocateCampaign(), and CG_parseMapVoteListInfo().
qboolean CG_FindCampaignInFile (const char * filename, const char * campaignShortName, cg_campaignInfo_t * info)
CG_FindCampaignInFile.
Parameters
[in] filename
[in] campaignShortName
[in] info
Returns
Definition at line 62 of file cg_missionbriefing.c.
Referenced by CG_LocateCampaign().
void CG_LocateArena (void)
CG_LocateArena.
Definition at line 469 of file cg_missionbriefing.c.
Referenced by CG_Init(), and CG_parseMapVoteListInfo().
void CG_LocateCampaign (void)
CG_LocateCampaign.
Definition at line 423 of file cg_missionbriefing.c.
Referenced by CG_Init().
const char* CG_NameForCampaign (void)
CG_NameForCampaign.
Returns
Definition at line 50 of file cg_missionbriefing.c.
Referenced by CG_LoadHudMenu().