ET: Legacy: src/cgame/cg_weapons.c File Reference
cg_weapons.c File Reference
Events and effects dealing with weapons.
#include "cg_local.h"
Macros
#define BARREL_SMOKE_TIME 1000
Functions
static void CG_StartWeaponAnim (int anim)
CG_StartWeaponAnim.
static void CG_ContinueWeaponAnim (int anim)
CG_ContinueWeaponAnim.
void AddLean (vec3_t viewAngle, vec3_t point, float ammount)
Add leaning offset.
void CG_MachineGunEjectBrass (centity_t *cent)
CG_MachineGunEjectBrass.
static void CG_PanzerFaustEjectBrass (centity_t *cent)
Toss the 'used' panzerfaust casing (unit is one-shot, disposable)
void CG_GetWindVector (vec3_t dir)
Compute random wind vector for smoke puff.
void CG_PyroSmokeTrail (centity_t *ent, const weaponInfo_t *wi)
LT/FOPS pyro for marking air strikes.
void CG_RocketTrail (centity_t *ent, const weaponInfo_t *wi)
New trail effects.
static void CG_DynamiteTrail (centity_t *ent, const weaponInfo_t *wi)
CG_DynamiteTrail.
static void CG_GrenadeTrail (centity_t *ent, const weaponInfo_t *wi)
CG_GrenadeTrail.
void CG_RailTrail2 (vec3_t color, vec3_t start, vec3_t end, int index, int sideNum)
Re-inserted this as a debug mechanism for bullets.
void CG_RailTrail (vec3_t color, vec3_t start, vec3_t end, int type, int index)
CG_RailTrail.
static qboolean CG_ParseWeaponConfig (const char *filename, weaponInfo_t *wi)
Read information for weapon animations (first/length/fps)
static qboolean CG_RW_ParseError (int handle, const char *format,...)
CG_RW_ParseError.
static qboolean CG_RW_ParseWeaponLinkPart (int handle, weaponInfo_t *weaponInfo, modelViewType_t viewType)
CG_RW_ParseWeaponLinkPart.
static qboolean CG_RW_ParseWeaponLink (int handle, weaponInfo_t *weaponInfo, modelViewType_t viewType)
CG_RW_ParseWeaponLink.
static qboolean CG_RW_ParseViewType (int handle, weaponInfo_t *weaponInfo, modelViewType_t viewType)
CG_RW_ParseViewType.
static qboolean CG_RW_ParseModModel (int handle, weaponInfo_t *weaponInfo)
CG_RW_ParseModModel.
static qboolean CG_RW_ParseWeaponSound (int handle, weaponSounds_t *weaponSounds)
CG_RW_ParseWeaponSound.
static qboolean CG_RW_ParseSoundSurface (int handle, weaponSounds_t *weaponSound)
CG_RW_ParseSoundSurface.
static qboolean CG_RW_ParseImpactMark (int handle, weaponInfo_t *weaponInfo)
CG_RW_ParseImpactMark.
void CG_MeleeImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float *radius, int *markDuration)
CG_MeleeImpact.
void CG_BulletImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float *radius, int *markDuration)
CG_BulletImpact.
void CG_SmallExplosionImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float *radius, int *markDuration)
CG_SmallExplosionImpact.
void CG_BigExplosionImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float *radius, int *markDuration)
CG_BigExplosionImpact.
void CG_MapMortarImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float *radius, int *markDuration)
CG_MapMortarImpact.
void CG_DynamiteExplosionImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float *radius, int *markDuration)
CG_DynamiteExplosionImpact.
static qboolean CG_RW_ParseClient (int handle, weaponInfo_t *weaponInfo)
CG_RW_ParseClient.
static qboolean CG_RegisterWeaponFromWeaponFile (const char *filename, weaponInfo_t *weaponInfo)
CG_RegisterWeaponFromWeaponFile.
void CG_RegisterWeapon (int weaponNum, qboolean force)
CG_RegisterWeapon.
void CG_RegisterItemVisuals (int itemNum)
Registers models and icons for items of bg_itemlist (except weapons which are registered from *.weap file data)
qboolean CG_GetPartFramesFromWeap (centity_t *cent, refEntity_t *part, refEntity_t *parent, int partid, weaponInfo_t *wi)
Get animation info from the parent if necessary.
static void CG_SetWeapLerpFrameAnimation (weaponInfo_t *wi, lerpFrame_t *lf, int newAnimation)
May include ANIM_TOGGLEBIT.
void CG_ClearWeapLerpFrame (weaponInfo_t *wi, lerpFrame_t *lf, int animationNumber)
CG_ClearWeapLerpFrame.
static void CG_RunWeapLerpFrame (clientInfo_t *ci, weaponInfo_t *wi, lerpFrame_t *lf, int newAnimation, float speedScale)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
static void CG_WeaponAnimation (playerState_t *ps, weaponInfo_t *weapon, int *weapOld, int *weap, float *weapBackLerp)
Modified. this is now client-side only (server does not dictate weapon animation info)
static void CG_CalculateWeaponPosition (vec3_t origin, vec3_t angles)
CG_CalculateWeaponPosition.
static void CG_FlamethrowerFlame (centity_t *cent, vec3_t origin)
CG_FlamethrowerFlame.
static void CG_AddWeaponWithPowerups (refEntity_t *gun, int powerups, playerState_t *ps, centity_t *cent)
CG_AddWeaponWithPowerups.
void CG_AddPlayerWeapon (refEntity_t *parent, playerState_t *ps, centity_t *cent)
Used for both the view weapon (ps is valid) and the world modelother character models (ps is NULL) The main player will have this called for BOTH cases, so effects like light and sound should only be done on the world model case.
void CG_AddViewWeapon (playerState_t *ps)
Add the weapon, and flash for the player's view.
static qboolean CG_WeaponHasAmmo (weapon_t weapon)
Check weapon for ammo.
qboolean CG_WeaponSelectable (int weapon)
Check weapon is selectable.
int CG_WeaponIndex (int weapnum, int *bank, int *cycle)
CG_WeaponIndex.
static int getNextWeapInBank (int bank, int cycle)
Pass in a bank and cycle and this will return the next valid weapon higher in the cycle. if the weap passed in is above highest in a cycle (MAX_WEAPS_IN_BANK), this will safely loop around.
static int getNextWeapInBankBynum (int weapnum)
getNextWeapInBankBynum
static int getPrevWeapInBank (int bank, int cycle)
Pass in a bank and cycle and this will return the next valid weapon lower in the cycle. if the weap passed in is the lowest in a cycle (0), this will loop around to the top (MAX_WEAPS_IN_BANK-1) and start down from there looking for a valid weapon position.
static int getPrevWeapInBankBynum (int weapnum)
getPrevWeapInBankBynum
static int getNextBankWeap (int bank, int cycle, qboolean sameBankPosition)
Pass in a bank and cycle and this will return the next valid weapon in a higher bank. sameBankPosition: if there's a weapon in the next bank at the same cycle, return that (colt returns thompson for example) rather than the lowest weapon.
static int getPrevBankWeap (int bank, int cycle, qboolean sameBankPosition)
Pass in a bank and cycle and this will return the next valid weapon in a lower bank. sameBankPosition: if there's a weapon in the prev bank at the same cycle, return that (thompson returns colt for example) rather than the highest weapon.
void CG_FinishWeaponChange (int lastWeapon, int newWeapon)
CG_FinishWeaponChange.
void CG_AltWeapon_f (void)
For example, switching between WP_MAUSER and WP_SNIPERRIFLE.
void CG_NextWeap (qboolean switchBanks)
CG_NextWeap.
void CG_PrevWeap (qboolean switchBanks)
CG_PrevWeap.
qboolean CG_CheckCanSwitch (void)
CG_CheckCanSwitch.
qboolean CG_ZoomRequired (qboolean isNextWeap)
CG_ZoomRequired.
void CG_LastWeaponUsed_f (void)
CG_LastWeaponUsed_f.
void CG_NextWeaponInBank_f (void)
CG_NextWeaponInBank_f.
void CG_PrevWeaponInBank_f (void)
CG_PrevWeaponInBank_f.
void CG_NextWeapon_f (void)
CG_NextWeapon_f.
void CG_PrevWeapon_f (void)
CG_PrevWeapon_f.
void CG_WeaponBank_f (void)
Weapon keys are not generally bound directly('bind 1 weapon 1'), rather the key is bound to a given bank ('bind 1 weaponbank 1')
void CG_Weapon_f (void)
CG_Weapon_f.
void CG_OutOfAmmoChange (qboolean allowForceSwitch)
The current weapon has just run out of ammo, switch to another one.
void CG_MG42EFX (centity_t *cent)
CG_MG42EFX.
void CG_MortarEFX (centity_t *cent)
Right now mostly copied directly from Raf's MG42 FX, but with the optional addtion of smoke.
void CG_WeaponFireRecoil (int weapon)
CG_WeaponFireRecoil.
void CG_FireWeapon (centity_t *cent)
Caused by an EV_FIRE_WEAPON event.
void CG_AddSparks (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddSparks.
void CG_AddBulletParticles (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddBulletParticles.
void CG_AddDirtBulletParticles (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale, float width, float height, float alpha, qhandle_t shader)
CG_AddDirtBulletParticles.
void CG_RandomDebris (localEntity_t *le)
CG_RandomDebris.
void CG_AddDebris (vec3_t origin, vec3_t dir, int speed, int duration, int count, trace_t *trace)
CG_AddDebris.
void CG_WaterRipple (qhandle_t shader, vec3_t loc, vec3_t dir, int size, int lifetime)
CG_WaterRipple.
soundSurface_t CG_GetSoundSurfaceIndex (int surfFlags)
CG_GetSoundSurfaceIndex.
sfxHandle_t CG_GetRandomSoundSurface (weaponSounds_t *weaponSounds, soundSurface_t surf, qboolean forceDefault)
CG_GetRandomSoundSurface.
void CG_MissileHitWall (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, int sourceEnt)
Caused by an EV_MISSILE_MISS event, or directly by local bullet tracing.
void CG_MissileHitWallSmall (vec3_t origin, vec3_t dir)
CG_MissileHitWallSmall.
void CG_MissileHitPlayer (int entityNum, int weapon, vec3_t origin, vec3_t dir, int fleshEntityNum)
CG_MissileHitPlayer.
void CG_SpawnTracer (int sourceEnt, vec3_t pstart, vec3_t pend)
CG_SpawnTracer.
void CG_DrawTracer (const vec3_t start, const vec3_t finish)
CG_DrawTracer.
void CG_Tracer (const vec3_t source, const vec3_t dest, int sparks)
CG_Tracer.
qboolean CG_CalcMuzzlePoint (int entityNum, vec3_t muzzle)
CG_CalcMuzzlePoint.
void SnapVectorTowards (vec3_t v, vec3_t to)
SnapVectorTowards.
void CG_DrawBulletTracer (vec3_t pstart, vec3_t pend, int sourceEntityNum, int otherEntityNum)
Renders bullet tracers if tracer option is valid.
void CG_Bullet (int weapon, vec3_t end, int sourceEntityNum, qboolean flesh, int fleshEntityNum, int otherEntNum2, float waterfraction, int seed)
Renders bullet effects.
Variables
weapon_t weapBanksMultiPlayer [MAX_WEAP_BANKS_MP][MAX_WEAPS_IN_BANK_MP]
The new loadout for WolfXP.
static const soundSurfaceTable_t soundSurfaceTable [W_MAX_SND_SURF]
pmove_t cg_pmove
int weapBankSwitchOrder [MAX_WEAP_BANK_SWITCH_ORDER] = { 3, 2, 4, 1 }
Detailed Description
Events and effects dealing with weapons.
Definition in file cg_weapons.c.
Macro Definition Documentation
#define BARREL_SMOKE_TIME 1000
Todo:
: unused ?
Todo:
: move to top ?
Definition at line 2440 of file cg_weapons.c.
Referenced by CG_AddPlayerWeapon().
Function Documentation
void AddLean (vec3_t viewAngle, vec3_t point, float ammount)
Add leaning offset.
Parameters
[in] viewAngle
[out] point
[in] ammount
Definition at line 95 of file cg_weapons.c.
Referenced by CG_CalcMuzzlePoint().
void CG_AddBulletParticles (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddBulletParticles.
Parameters
[in] origin
[in] dir
[in] speed
duration - unused
[in] count
[in] randScale
Definition at line 5026 of file cg_weapons.c.
Referenced by CG_BulletImpact(), CG_EntityEvent(), CG_MeleeImpact(), and CG_PlayGlobalSound().
void CG_AddDebris (vec3_t origin, vec3_t dir, int speed, int duration, int count, trace_t * trace)
CG_AddDebris.
Parameters
[in] origin
[in] dir
[in] speed
[in] duration
[in] count
[in] trace
Todo:
: this is such a waste - change to (or even drop the multiplicator *2)
Todo:
: find better models and/or extend ...
Todo:
: make dependant from surface (snow etc and use related models/sounds) and or weapon
Todo:
: find a client cvar so purists can disable (see CG_AddLocalEntities)
Todo:
: find some other models
Todo:
: replace with surface related models
Definition at line 5124 of file cg_weapons.c.
Referenced by CG_BigExplosionImpact(), CG_DynamiteExplosionImpact(), CG_Effect(), CG_MissileHitWallSmall(), and CG_SmallExplosionImpact().
void CG_AddDirtBulletParticles (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale, float width, float height, float alpha, qhandle_t shader)
CG_AddDirtBulletParticles.
Parameters
[in] origin
[in] dir
[in] speed
[in] duration
[in] count
[in] randScale
[in] width
[in] height
[in] alpha
[in] shader
Definition at line 5057 of file cg_weapons.c.
Referenced by CG_BigExplosionImpact(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_MapMortarImpact(), and CG_SmallExplosionImpact().
void CG_AddPlayerWeapon (refEntity_t * parent, playerState_t * ps, centity_t * cent)
Used for both the view weapon (ps is valid) and the world modelother character models (ps is NULL) The main player will have this called for BOTH cases, so effects like light and sound should only be done on the world model case.
Parameters
[in] parent
[in] ps
[in,out] cent
Todo:
: this might be useful for other weapons too (move up?)
Definition at line 2450 of file cg_weapons.c.
Referenced by CG_AddViewWeapon(), and CG_Player().
void CG_AddSparks (vec3_t origin, vec3_t dir, int speed, int duration, int count, float randScale)
CG_AddSparks.
Parameters
[in] origin
[in] dir
[in] speed
[in] duration
[in] count
[in] randScale
Definition at line 4979 of file cg_weapons.c.
Referenced by CG_BulletImpact().
void CG_AddViewWeapon (playerState_t * ps)
Add the weapon, and flash for the player's view.
Parameters
[in] ps
Todo:
: ?
Todo:
: HACK dummy model to just draw something
Definition at line 3122 of file cg_weapons.c.
Referenced by CG_DrawActiveFrame().
static void CG_AddWeaponWithPowerups (refEntity_t * gun, int powerups, playerState_t * ps, centity_t * cent) static
CG_AddWeaponWithPowerups.
Parameters
[in] gun
powerups - unused
ps - unused
cent - unused
Todo:
cleanup ?
Definition at line 2429 of file cg_weapons.c.
Referenced by CG_AddPlayerWeapon(), and CG_AddViewWeapon().
void CG_AltWeapon_f (void)
For example, switching between WP_MAUSER and WP_SNIPERRIFLE.
Todo:
: This is a horrible way of doing it but theres not other way atm.
Todo:
: This is a horrible way of doing it but theres not other way atm.
Definition at line 3746 of file cg_weapons.c.
void CG_BigExplosionImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float * radius, int * markDuration)
CG_BigExplosionImpact.
Parameters
[in] weapon
[in] missileEffect
[in] origin
[in] dir
[in] surfFlags
[in,out] radius
[in,out] markDuration
Definition at line 5520 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseImpactMark().
void CG_Bullet (int weapon, vec3_t end, int sourceEntityNum, qboolean flesh, int fleshEntityNum, int otherEntNum2, float waterfraction, int seed)
Renders bullet effects.
Parameters
[in] end
[in] sourceEntityNum
[in] flesh
[in] fleshEntityNum
[in] otherEntNum2
[in] waterfraction
[in] seed
Todo:
Todo:
: AAGUN
Definition at line 6273 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_BulletImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float * radius, int * markDuration)
CG_BulletImpact.
Parameters
[in] weapon
[in] missileEffect
[in] origin
[in] dir
[in] surfFlags
[in,out] radius
[in,out] markDuration
Definition at line 5388 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseImpactMark().
qboolean CG_CalcMuzzlePoint (int entityNum, vec3_t muzzle)
CG_CalcMuzzlePoint.
Parameters
[in] entityNum
[in] muzzle
Returns
Definition at line 6072 of file cg_weapons.c.
Referenced by CG_Bullet(), CG_DrawActiveFrame(), and CG_EntityEffects().
static void CG_CalculateWeaponPosition (vec3_t origin, vec3_t angles) static
CG_CalculateWeaponPosition.
Parameters
[in] origin
[in] angles
Definition at line 2295 of file cg_weapons.c.
Referenced by CG_AddViewWeapon().
qboolean CG_CheckCanSwitch (void)
CG_CheckCanSwitch.
Returns
Definition at line 4293 of file cg_weapons.c.
Referenced by CG_LastWeaponUsed_f(), CG_NextWeapon_f(), CG_NextWeaponInBank_f(), CG_PrevWeapon_f(), CG_PrevWeaponInBank_f(), and CG_WeaponBank_f().
void CG_ClearWeapLerpFrame (weaponInfo_t * wi, lerpFrame_t * lf, int animationNumber)
CG_ClearWeapLerpFrame.
Parameters
[in] wi
[in,out] lf
[in] animationNumber
Definition at line 2130 of file cg_weapons.c.
Referenced by CG_RunWeapLerpFrame().
static void CG_ContinueWeaponAnim (int anim) static
CG_ContinueWeaponAnim.
Parameters
[in] anim
Definition at line 79 of file cg_weapons.c.
Referenced by CG_AddViewWeapon().
void CG_DrawBulletTracer (vec3_t pstart, vec3_t pend, int sourceEntityNum, int otherEntityNum)
Renders bullet tracers if tracer option is valid.
Parameters
[in] pstart
[in] pend
[in] sourceEntityNum
[in] otherEntityNum
Definition at line 6245 of file cg_weapons.c.
Referenced by CG_Bullet().
void CG_DrawTracer (const vec3_t start, const vec3_t finish)
CG_DrawTracer.
Parameters
[in] start
[in] finish
Definition at line 5980 of file cg_weapons.c.
Referenced by CG_AddMovingTracer(), and CG_Tracer().
void CG_DynamiteExplosionImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float * radius, int * markDuration)
CG_DynamiteExplosionImpact.
Parameters
[in] weapon
[in] missileEffect
[in] origin
[in] dir
[in] surfFlags
[in,out] radius
[in,out] markDuration
Definition at line 5662 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseImpactMark().
static void CG_DynamiteTrail (centity_t * ent, const weaponInfo_t * wi) static
CG_DynamiteTrail.
Parameters
[in] ent
wi - unused
Definition at line 548 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
void CG_FinishWeaponChange (int lastWeapon, int newWeapon)
CG_FinishWeaponChange.
Parameters
[in] lastweap
[in] newweap
Definition at line 3646 of file cg_weapons.c.
Referenced by CG_AltWeapon_f(), CG_EntityEvent(), CG_LastWeaponUsed_f(), CG_NextWeap(), CG_OutOfAmmoChange(), CG_PrevWeap(), CG_Respawn(), CG_TransitionPlayerState(), and CG_WeaponBank_f().
void CG_FireWeapon (centity_t * cent)
Caused by an EV_FIRE_WEAPON event.
Parameters
[in,out] cent
Todo:
: use numbers that are weapon specific
Definition at line 4817 of file cg_weapons.c.
Referenced by CG_EntityEvent().
static void CG_FlamethrowerFlame (centity_t * cent, vec3_t origin) static
CG_FlamethrowerFlame.
Parameters
[in] cent
[in] origin
Definition at line 2409 of file cg_weapons.c.
Referenced by CG_AddPlayerWeapon(), and CG_AddViewWeapon().
qboolean CG_GetPartFramesFromWeap (centity_t * cent, refEntity_t * part, refEntity_t * parent, int partid, weaponInfo_t * wi)
Get animation info from the parent if necessary.
Parameters
[in] cent
[out] part
[in] parent
[in] partid
[in] wi
Returns
Definition at line 2057 of file cg_weapons.c.
Referenced by CG_AddPlayerWeapon().
sfxHandle_t CG_GetRandomSoundSurface (weaponSounds_t * weaponSounds, soundSurface_t surf, qboolean forceDefault)
CG_GetRandomSoundSurface.
Parameters
[in] weapon
[in] surf
Returns
Definition at line 5335 of file cg_weapons.c.
Referenced by CG_EntityEvent(), and CG_MissileHitWall().
soundSurface_t CG_GetSoundSurfaceIndex (int surfFlags)
CG_GetSoundSurfaceIndex.
Parameters
[in] surfFlags
Returns
Definition at line 5314 of file cg_weapons.c.
Referenced by CG_EntityEvent(), and CG_MissileHitWall().
void CG_GetWindVector (vec3_t dir)
Compute random wind vector for smoke puff.
Parameters
[out] dir
Definition at line 349 of file cg_weapons.c.
Referenced by CG_AddLightstyle(), CG_Bullet(), CG_EntityEffects(), and CG_PyroSmokeTrail().
static void CG_GrenadeTrail (centity_t * ent, const weaponInfo_t * wi) static
CG_GrenadeTrail.
Parameters
[in,out] ent
wi - unused
Definition at line 572 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
void CG_LastWeaponUsed_f (void)
CG_LastWeaponUsed_f.
Definition at line 4389 of file cg_weapons.c.
void CG_MachineGunEjectBrass (centity_t * cent)
CG_MachineGunEjectBrass.
Parameters
[in] cent
Definition at line 112 of file cg_weapons.c.
Referenced by CG_FireWeapon(), and CG_RW_ParseClient().
void CG_MapMortarImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float * radius, int * markDuration)
CG_MapMortarImpact.
Parameters
[in] weapon
[in] missileEffect
[in] origin
[in] dir
[in] surfFlags
[in,out] radius
[in,out] markDuration
Definition at line 5594 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseImpactMark().
void CG_MeleeImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float * radius, int * markDuration)
CG_MeleeImpact.
Parameters
[in] weapon
[in] missileEffect
[in] origin
[in] dir
[in] surfFlags
[in,out] radius
[in,out] markDuration
Definition at line 5366 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseImpactMark().
void CG_MG42EFX (centity_t * cent)
CG_MG42EFX.
Parameters
[in] cent
Definition at line 4706 of file cg_weapons.c.
Referenced by CG_AddPlayerWeapon().
void CG_MissileHitPlayer (int entityNum, int weapon, vec3_t origin, vec3_t dir, int fleshEntityNum)
CG_MissileHitPlayer.
Parameters
[in] entityNum
[in] weapon
[in] origin
[in] dir
[in] fleshEntityNum
Definition at line 5881 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_MissileHitWall (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, int sourceEnt)
Caused by an EV_MISSILE_MISS event, or directly by local bullet tracing.
Parameters
[in] weapon
[in] missileEffect used to define what sort of effect to spawn
[in] origin
[in] dir
[in] surfFlags
[in] sourceEnt
Note
modified to send missilehitwall surface parameters
Definition at line 5744 of file cg_weapons.c.
Referenced by CG_Bullet(), CG_Effect(), CG_EntityEvent(), and CG_MissileHitPlayer().
void CG_MissileHitWallSmall (vec3_t origin, vec3_t dir)
CG_MissileHitWallSmall.
Parameters
[in] origin
[in] dir
Definition at line 5847 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_MortarEFX (centity_t * cent)
Right now mostly copied directly from Raf's MG42 FX, but with the optional addtion of smoke.
Parameters
[in] cent
Definition at line 4748 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_NextWeap (qboolean switchBanks)
CG_NextWeap.
Parameters
[in] switchBanks - curweap is the last in a bank, 'qtrue' means go to the next available bank, 'qfalse' means loop to the head of the bank
Definition at line 4005 of file cg_weapons.c.
Referenced by CG_NextWeapon_f(), and CG_NextWeaponInBank_f().
void CG_NextWeapon_f (void)
CG_NextWeapon_f.
Definition at line 4451 of file cg_weapons.c.
void CG_NextWeaponInBank_f (void)
CG_NextWeaponInBank_f.
Definition at line 4415 of file cg_weapons.c.
void CG_OutOfAmmoChange (qboolean allowForceSwitch)
The current weapon has just run out of ammo, switch to another one.
Parameters
[in] allowForceSwitch - enable on EV_NOAMMO and disable on EV_WEAPONSWITCHED
Definition at line 4600 of file cg_weapons.c.
Referenced by CG_EntityEvent().
static void CG_PanzerFaustEjectBrass (centity_t * cent) static
Toss the 'used' panzerfaust casing (unit is one-shot, disposable)
Parameters
[in] cent
Definition at line 279 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
static qboolean CG_ParseWeaponConfig (const char * filename, weaponInfo_t * wi) static
Read information for weapon animations (first/length/fps)
Parameters
[in] filename
[out] wi
Returns
Definition at line 730 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
void CG_PrevWeap (qboolean switchBanks)
CG_PrevWeap.
Parameters
[in] switchBanks - curweap is the last in a bank 'qtrue' - go to the next available bank 'qfalse' - loop to the head of the bank
Definition at line 4152 of file cg_weapons.c.
Referenced by CG_PrevWeapon_f(), and CG_PrevWeaponInBank_f().
void CG_PrevWeapon_f (void)
CG_PrevWeapon_f.
Definition at line 4483 of file cg_weapons.c.
void CG_PrevWeaponInBank_f (void)
CG_PrevWeaponInBank_f.
Definition at line 4433 of file cg_weapons.c.
void CG_PyroSmokeTrail (centity_t * ent, const weaponInfo_t * wi)
LT/FOPS pyro for marking air strikes.
Parameters
[in,out] ent
wi - unused
Definition at line 362 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
void CG_RailTrail (vec3_t color, vec3_t start, vec3_t end, int type, int index)
CG_RailTrail.
Parameters
[in] color
[in] start
[in] end
[in] type
[in] index
Definition at line 679 of file cg_weapons.c.
Referenced by CG_EntityEvent(), CG_Player(), and CG_TouchTriggerPrediction().
void CG_RailTrail2 (vec3_t color, vec3_t start, vec3_t end, int index, int sideNum)
Re-inserted this as a debug mechanism for bullets.
Parameters
[in] color
[in] start
[in] end
[in] index
[in] sideNum
Definition at line 627 of file cg_weapons.c.
Referenced by CG_Player(), and CG_RailTrail().
void CG_RandomDebris (localEntity_t * le)
CG_RandomDebris.
Parameters
[out] le
Definition at line 5079 of file cg_weapons.c.
Referenced by CG_AddDebris().
void CG_RegisterItemVisuals (int itemNum)
Registers models and icons for items of bg_itemlist (except weapons which are registered from *.weap file data)
Parameters
[in] itemNum
Note
Actually IT_AMMO & IT_TEAM have no visuals
Definition at line 1992 of file cg_weapons.c.
Referenced by CG_RegisterGraphics().
void CG_RegisterWeapon (int weaponNum, qboolean force)
CG_RegisterWeapon.
Parameters
[in] weaponNum
[in] force
Definition at line 1933 of file cg_weapons.c.
Referenced by CG_RegisterGraphics().
static qboolean CG_RegisterWeaponFromWeaponFile (const char * filename, weaponInfo_t * weaponInfo) static
CG_RegisterWeaponFromWeaponFile.
Parameters
[in] filename
[in] weaponInfo
Returns
Definition at line 1876 of file cg_weapons.c.
Referenced by CG_RegisterWeapon().
void CG_RocketTrail (centity_t * ent, const weaponInfo_t * wi)
New trail effects.
Parameters
[in,out] ent
wi - unused
Definition at line 476 of file cg_weapons.c.
Referenced by CG_DrawMineMarkerFlag(), CG_Missile(), and CG_RW_ParseClient().
static void CG_RunWeapLerpFrame (clientInfo_t * ci, weaponInfo_t * wi, lerpFrame_t * lf, int newAnimation, float speedScale) static
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
Parameters
ci - unused
[in] wi
[in,out] lf
[in] newAnimation
[in] speedScale
Definition at line 2147 of file cg_weapons.c.
Referenced by CG_WeaponAnimation().
static qboolean CG_RW_ParseClient (int handle, weaponInfo_t * weaponInfo) static
CG_RW_ParseClient.
Parameters
[in] handle
[in,out] weaponInfo
Returns
Definition at line 1394 of file cg_weapons.c.
Referenced by CG_RegisterWeaponFromWeaponFile().
static qboolean CG_RW_ParseError (int handle, const char * format, ...) static
CG_RW_ParseError.
Parameters
[in] handle
[in] format
Returns
Definition at line 912 of file cg_weapons.c.
Referenced by CG_RegisterWeaponFromWeaponFile(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), CG_RW_ParseModModel(), CG_RW_ParseSoundSurface(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLink(), CG_RW_ParseWeaponLinkPart(), and CG_RW_ParseWeaponSound().
static qboolean CG_RW_ParseImpactMark (int handle, weaponInfo_t * weaponInfo) static
CG_RW_ParseImpactMark.
Parameters
[in] handle
[in,out] weaponInfo
Returns
Definition at line 1334 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
static qboolean CG_RW_ParseModModel (int handle, weaponInfo_t * weaponInfo) static
CG_RW_ParseModModel.
Parameters
[in] handle
[in,out] weaponInfo
Returns
Todo:
: add more model formats?
Definition at line 1171 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
static qboolean CG_RW_ParseSoundSurface (int handle, weaponSounds_t * weaponSound) static
CG_RW_ParseSoundSurface.
Parameters
[in] handle
[in,out] weaponInfo
Returns
Definition at line 1284 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
static qboolean CG_RW_ParseViewType (int handle, weaponInfo_t * weaponInfo, modelViewType_t viewType) static
CG_RW_ParseViewType.
Parameters
[in] handle
[in,out] weaponInfo
[in] viewType
Returns
Definition at line 1082 of file cg_weapons.c.
Referenced by CG_RW_ParseClient().
static qboolean CG_RW_ParseWeaponLink (int handle, weaponInfo_t * weaponInfo, modelViewType_t viewType) static
CG_RW_ParseWeaponLink.
Parameters
[in] handle
[in] weaponInfo
[in] viewType
Returns
Definition at line 1038 of file cg_weapons.c.
Referenced by CG_RW_ParseViewType().
static qboolean CG_RW_ParseWeaponLinkPart (int handle, weaponInfo_t * weaponInfo, modelViewType_t viewType) static
CG_RW_ParseWeaponLinkPart.
Parameters
[in] handle
[in,out] weaponInfo
[in] viewType
Returns
Definition at line 941 of file cg_weapons.c.
Referenced by CG_RW_ParseWeaponLink().
static qboolean CG_RW_ParseWeaponSound (int handle, weaponSounds_t * weaponSounds) static
CG_RW_ParseWeaponSound.
Parameters
[in] handle
[in,out] weaponSounds
Returns
Definition at line 1237 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseSoundSurface().
static void CG_SetWeapLerpFrameAnimation (weaponInfo_t * wi, lerpFrame_t * lf, int newAnimation) static
May include ANIM_TOGGLEBIT.
Parameters
[in] wi
[out] lf
[in] newAnimation
Definition at line 2101 of file cg_weapons.c.
Referenced by CG_ClearWeapLerpFrame(), and CG_RunWeapLerpFrame().
void CG_SmallExplosionImpact (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, float * radius, int * markDuration)
CG_SmallExplosionImpact.
Parameters
[in] weapon
[in] missileEffect
[in] origin
[in] dir
[in] surfFlags
[in,out] radius
[in,out] markDuration
Definition at line 5462 of file cg_weapons.c.
Referenced by CG_RW_ParseClient(), and CG_RW_ParseImpactMark().
void CG_SpawnTracer (int sourceEnt, vec3_t pstart, vec3_t pend)
CG_SpawnTracer.
Parameters
[in] sourceEnt
[in] pstart
[in] pend
Todo:
: AAGUN
Definition at line 5914 of file cg_weapons.c.
Referenced by CG_DrawBulletTracer().
static void CG_StartWeaponAnim (int anim) static
CG_StartWeaponAnim.
Parameters
[in] anim
Definition at line 60 of file cg_weapons.c.
Referenced by CG_ContinueWeaponAnim().
void CG_Tracer (const vec3_t source, const vec3_t dest, int sparks)
CG_Tracer.
Parameters
[in] source
[in] dest
[in] sparks
Definition at line 6036 of file cg_weapons.c.
Referenced by CG_Bullet(), and CG_EntityEvent().
void CG_WaterRipple (qhandle_t shader, vec3_t loc, vec3_t dir, int size, int lifetime)
CG_WaterRipple.
Parameters
[in] shader
[in] loc
[in] dir - unused
[in] size
[in] lifetime
Definition at line 5284 of file cg_weapons.c.
Referenced by CG_BigExplosionImpact(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_MapMortarImpact(), and CG_SmallExplosionImpact().
void CG_Weapon_f (void)
CG_Weapon_f.
Definition at line 4581 of file cg_weapons.c.
static void CG_WeaponAnimation (playerState_t * ps, weaponInfo_t * weapon, int * weapOld, int * weap, float * weapBackLerp) static
Modified. this is now client-side only (server does not dictate weapon animation info)
Parameters
[in] ps
[in] weapon
[out] weapOld
[out] weap
[out] weapBackLerp
Definition at line 2265 of file cg_weapons.c.
Referenced by CG_AddViewWeapon().
void CG_WeaponBank_f (void)
Weapon keys are not generally bound directly('bind 1 weapon 1'), rather the key is bound to a given bank ('bind 1 weaponbank 1')
Definition at line 4516 of file cg_weapons.c.
Referenced by CG_Weapon_f().
void CG_WeaponFireRecoil (int weapon)
CG_WeaponFireRecoil.
Parameters
[in] weapon
Todo:
: add recoil for secondary weapons?
Definition at line 4779 of file cg_weapons.c.
Referenced by CG_FireWeapon().
static qboolean CG_WeaponHasAmmo (weapon_t weapon) static
Check weapon for ammo.
Parameters
weapon - the weapon to check for ammo
Returns
qtrue if the weapon has ammo or don't need ammo, else qfalse if weapon has no ammo left
GetWeaponTableData(weapon)->useAmmo
Definition at line 3385 of file cg_weapons.c.
Referenced by CG_WeaponSelectable().
int CG_WeaponIndex (int weapnum, int * bank, int * cycle)
CG_WeaponIndex.
Parameters
[in] weapnum
[in,out] bank
[in,out] cycle
Returns
Definition at line 3441 of file cg_weapons.c.
Referenced by CG_FinishWeaponChange(), CG_ItemPickup(), CG_NextWeap(), CG_Obituary(), CG_PrevWeap(), CG_WeaponBank_f(), getNextWeapInBankBynum(), and getPrevWeapInBankBynum().
qboolean CG_WeaponSelectable (int weapon)
Check weapon is selectable.
Parameters
weapon - the weapon to check if selectable
Returns
qtrue if the weapon is selectable, else qfalse if not
Definition at line 3408 of file cg_weapons.c.
Referenced by CG_AltWeapon_f(), CG_EntityEvent(), CG_FinishWeaponChange(), CG_LastWeaponUsed_f(), CG_NextWeap(), CG_OutOfAmmoChange(), CG_PrevWeap(), and CG_WeaponBank_f().
qboolean CG_ZoomRequired (qboolean isNextWeap)
CG_ZoomRequired.
Parameters
[in] isNextWeap
Returns
Definition at line 4364 of file cg_weapons.c.
Referenced by CG_NextWeapon_f(), CG_NextWeaponInBank_f(), CG_PrevWeapon_f(), and CG_PrevWeaponInBank_f().
static int getNextBankWeap (int bank, int cycle, qboolean sameBankPosition) static
Pass in a bank and cycle and this will return the next valid weapon in a higher bank. sameBankPosition: if there's a weapon in the next bank at the same cycle, return that (colt returns thompson for example) rather than the lowest weapon.
Parameters
[in] bank
[in] cycle
[in] sameBankPosition
Returns
Definition at line 3586 of file cg_weapons.c.
Referenced by CG_NextWeap().
static int getNextWeapInBank (int bank, int cycle) static
Pass in a bank and cycle and this will return the next valid weapon higher in the cycle. if the weap passed in is above highest in a cycle (MAX_WEAPS_IN_BANK), this will safely loop around.
Parameters
[in] bank
[in] cycle
Returns
Definition at line 3498 of file cg_weapons.c.
Referenced by CG_NextWeap(), CG_WeaponBank_f(), and getNextWeapInBankBynum().
static int getNextWeapInBankBynum (int weapnum) static
getNextWeapInBankBynum
Parameters
[in] weapnum
Returns
Definition at line 3518 of file cg_weapons.c.
Referenced by CG_NextWeap().
static int getPrevBankWeap (int bank, int cycle, qboolean sameBankPosition) static
Pass in a bank and cycle and this will return the next valid weapon in a lower bank. sameBankPosition: if there's a weapon in the prev bank at the same cycle, return that (thompson returns colt for example) rather than the highest weapon.
Parameters
[in] bank
[in] cycle
[in] sameBankPosition
Returns
Definition at line 3609 of file cg_weapons.c.
Referenced by CG_PrevWeap().
static int getPrevWeapInBank (int bank, int cycle) static
Pass in a bank and cycle and this will return the next valid weapon lower in the cycle. if the weap passed in is the lowest in a cycle (0), this will loop around to the top (MAX_WEAPS_IN_BANK-1) and start down from there looking for a valid weapon position.
Parameters
[in] bank
[in] cycle
Returns
Definition at line 3538 of file cg_weapons.c.
Referenced by CG_PrevWeap(), and getPrevWeapInBankBynum().
static int getPrevWeapInBankBynum (int weapnum) static
getPrevWeapInBankBynum
Parameters
[in] weapnum
Returns
Definition at line 3565 of file cg_weapons.c.
Referenced by CG_PrevWeap().
void SnapVectorTowards (vec3_t v, vec3_t to)
SnapVectorTowards.
Parameters
v
to
Definition at line 6221 of file cg_weapons.c.
Referenced by CG_Bullet(), Fire_Lead_Ext(), and G_DropItems().
Variable Documentation
pmove_t cg_pmove
Definition at line 41 of file cg_predict.c.
Referenced by CG_FinishWeaponChange().
soundSurfaceTable static
Initial value:
=
{
    { 0,           "default" },
    { 0,           "far",    },
    { SURF_METAL,  "metal",  },
    { SURF_WOOD,   "wood",   },
    { SURF_GRASS,  "grass",  },
    { SURF_GRAVEL, "gravel", },
    { SURF_GLASS,  "glass",  },
    { SURF_SNOW,   "snow",   },
    { SURF_ROOF,   "roof",   },
    { SURF_CARPET, "carpet"  },
    { 0,           "water",  },
    { 0,           "flesh"   }
}
Definition at line 1215 of file cg_weapons.c.
weapBanksMultiPlayer
Initial value:
=
{
    { 0,                   0,                    0,               0,               0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_KNIFE,            WP_KNIFE_KABAR,       0,               0,               0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_LUGER,            WP_COLT,              WP_AKIMBO_COLT,  WP_AKIMBO_LUGER, WP_SILENCER,    WP_SILENCED_COLT, WP_AKIMBO_SILENCEDCOLT, WP_AKIMBO_SILENCEDLUGER, 0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_MP40,             WP_THOMPSON,          WP_STEN,         WP_GARAND,       WP_PANZERFAUST, WP_FLAMETHROWER,  WP_KAR98,               WP_CARBINE,              WP_FG42, WP_K43, WP_MOBILE_MG42, WP_MOBILE_BROWNING, WP_MORTAR, WP_MORTAR2, WP_BAZOOKA, WP_GPG40, WP_M7, WP_MP34 },
    { WP_GRENADE_LAUNCHER, WP_GRENADE_PINEAPPLE, 0,               0,               0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_MEDIC_SYRINGE,    WP_PLIERS,            WP_SMOKE_MARKER, WP_SMOKE_BOMB,   0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_DYNAMITE,         WP_MEDKIT,            WP_AMMO,         WP_SATCHEL,      WP_SATCHEL_DET, 0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_LANDMINE,         WP_MEDIC_ADRENALINE,  0,               0,               0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { WP_BINOCULARS,       0,                    0,               0,               0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
    { 0,                   0,                    0,               0,               0,              0,                0,                      0,                       0,       0,      0,              0,                  0,         0,          0,          0,        0,     0       },
}
The new loadout for WolfXP.
Definition at line 42 of file cg_weapons.c.
Referenced by CG_OutOfAmmoChange(), CG_WeaponBank_f(), CG_WeaponIndex(), getNextBankWeap(), getNextWeapInBank(), getPrevBankWeap(), and getPrevWeapInBank().
int weapBankSwitchOrder[MAX_WEAP_BANK_SWITCH_ORDER] = { 3, 2, 4, 1 }
Definition at line 4594 of file cg_weapons.c.
Referenced by CG_OutOfAmmoChange().