ET: Legacy: src/cgame/cg_fireteams.c File Reference
cg_fireteams.c File Reference
#include "cg_local.h"
Functions
void CG_Fireteams_MenuTitleText_Draw (panel_button_t *button)
int CG_CountFireteamsByTeam (team_t t)
CG_CountFireteamsByTeam.
void CG_DrawFireteamsByTeam (panel_button_t *button, team_t t)
CG_DrawFireteamsByTeam.
int CG_CountPlayersSF (void)
CG_CountPlayersSF.
int CG_CountPlayersNF (void)
CG_CountPlayersNF.
int CG_PlayerSFFromPos (int pos, int *pageofs)
CG_PlayerSFFromPos.
int CG_PlayerNFFromPos (int pos, int *pageofs)
CG_PlayerNFFromPos.
void CG_DrawPlayerSF (panel_button_t *button, int *pageofs)
CG_DrawPlayerSF.
void CG_DrawPlayerNF (panel_button_t *button, int *pageofs)
CG_DrawPlayerNF.
void CG_Fireteams_MenuText_Draw (panel_button_t *button)
CG_Fireteams_MenuText_Draw.
void CG_Fireteams_Setup (void)
CG_Fireteams_Setup.
void CG_Fireteams_KeyHandling (int key, qboolean down)
CG_Fireteams_KeyHandling.
void CG_Fireteams_Draw (void)
CG_Fireteams_Draw.
void CG_QuickFireteamMessage_f (void)
CG_QuickFireteamMessage_f.
qboolean CG_FireteamCheckExecKey (int key, qboolean doaction)
CG_FireteamCheckExecKey.
Variables
panel_button_text_t fireteamTitleFont
panel_button_text_t fireteamFont
panel_button_t fireteamTopBorder
panel_button_t fireteamTopBorderBack
panel_button_t fireteamTopBorderInner
panel_button_t fireteamTopBorderInnerText
panel_button_t fireteamMenuItemText
panel_button_t * fireteamButtons []
const char * ftMenuRootStrings []
const char * ftMenuRootStringsMsg []
const char * ftMenuRootStringsAlphachars []
const char * ftMenuSoldierStrings []
const char * ftMenuSoldierStringsAlphachars []
const char * ftMenuSoldierStringsMsg []
const char * ftMenuMedicStrings []
const char * ftMenuMedicStringsAlphachars []
const char * ftMenuMedicStringsMsg []
const char * ftMenuEngineerStrings []
const char * ftMenuEngineerStringsAlphachars []
const char * ftMenuEngineerStringsMsg []
const char * ftMenuFieldOpsStrings []
const char * ftMenuFieldOpsStringsAlphachars []
const char * ftMenuFieldOpsStringsMsg []
const char * ftMenuCovertOpsStrings []
const char * ftMenuCovertOpsStringsAlphachars []
const char * ftMenuCovertOpsStringsMsg []
const char ** ftMenuStrings []
const char ** ftMenuStringsAlphachars []
const char ** ftMenuStringsMsg []
const char * ftOffMenuList []
const char * ftOffMenuListAlphachars []
const char * ftOnMenuList []
const char * ftOnMenuListAlphachars []
const char * ftLeaderMenuList []
const char * ftLeaderMenuListAlphachars []
Function Documentation
int CG_CountFireteamsByTeam (team_t t)
CG_CountFireteamsByTeam.
Parameters
[in] t
Returns
Definition at line 437 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
int CG_CountPlayersNF (void)
CG_CountPlayersNF.
Returns
Definition at line 548 of file cg_fireteams.c.
Referenced by CG_DrawPlayerNF(), CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), and CG_PlayerNFFromPos().
int CG_CountPlayersSF (void)
CG_CountPlayersSF.
Returns
Definition at line 512 of file cg_fireteams.c.
Referenced by CG_DrawPlayerSF(), CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), and CG_PlayerSFFromPos().
void CG_DrawFireteamsByTeam (panel_button_t * button, team_t t)
CG_DrawFireteamsByTeam.
Parameters
[in] button
[in] t
Definition at line 470 of file cg_fireteams.c.
Referenced by CG_Fireteams_MenuText_Draw().
void CG_DrawPlayerNF (panel_button_t * button, int * pageofs)
CG_DrawPlayerNF.
Parameters
[in] button
[in] pageofs
Definition at line 773 of file cg_fireteams.c.
Referenced by CG_Fireteams_MenuText_Draw().
void CG_DrawPlayerSF (panel_button_t * button, int * pageofs)
CG_DrawPlayerSF.
Parameters
[in] button
[in] pageofs
Definition at line 707 of file cg_fireteams.c.
Referenced by CG_Fireteams_MenuText_Draw().
qboolean CG_FireteamCheckExecKey (int key, qboolean doaction)
CG_FireteamCheckExecKey.
Parameters
[in] key
[in] doaction
Returns
Definition at line 1086 of file cg_fireteams.c.
Referenced by CG_CheckExecKey(), and CG_Fireteams_KeyHandling().
void CG_Fireteams_Draw (void)
CG_Fireteams_Draw.
Definition at line 1070 of file cg_fireteams.c.
Referenced by CG_Draw2D().
void CG_Fireteams_KeyHandling (int key, qboolean down)
CG_Fireteams_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 1059 of file cg_fireteams.c.
Referenced by CG_KeyEvent().
void CG_Fireteams_MenuText_Draw (panel_button_t * button)
CG_Fireteams_MenuText_Draw.
Parameters
[in] button
Definition at line 838 of file cg_fireteams.c.
void CG_Fireteams_MenuTitleText_Draw (panel_button_t * button)
Definition at line 341 of file cg_fireteams.c.
void CG_Fireteams_Setup (void)
CG_Fireteams_Setup.
Definition at line 1049 of file cg_fireteams.c.
Referenced by CG_RegisterGraphics().
int CG_PlayerNFFromPos (int pos, int * pageofs)
CG_PlayerNFFromPos.
Parameters
[in] pos
[in,out] pageofs
Returns
Definition at line 647 of file cg_fireteams.c.
Referenced by CG_DrawPlayerNF(), and CG_FireteamCheckExecKey().
int CG_PlayerSFFromPos (int pos, int * pageofs)
CG_PlayerSFFromPos.
Parameters
[in] pos
[in,out] pageofs
Returns
Definition at line 586 of file cg_fireteams.c.
Referenced by CG_DrawPlayerSF(), and CG_FireteamCheckExecKey().
void CG_QuickFireteamMessage_f (void)
CG_QuickFireteamMessage_f.
Definition at line 331 of file cg_consolecmds.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_Draw().
Variable Documentation
panel_button_t* fireteamButtons[]
Initial value:
=
{
    &fireteamTopBorderBack, &fireteamTopBorder, &fireteamTopBorderInner, &fireteamTopBorderInnerText,
    &fireteamMenuItemText,
    NULL
}
Definition at line 124 of file cg_fireteams.c.
panel_button_text_t fireteamFont
Initial value:
=
{
    0.2f,                    0.2f,
    { 0.6f,                  0.6f,0.6f,    1.f },
    ITEM_TEXTSTYLE_SHADOWED, 0,
    &cgs.media.limboFont2,
}
Definition at line 45 of file cg_fireteams.c.
panel_button_t fireteamMenuItemText
Initial value:
=
{
    NULL,
    NULL,
    { 16,                      153,  128, 12 },
    { 0,                       0,    0,   0, 0, 0, 0, 0},
    &fireteamFont,
    NULL,
    NULL,
    CG_Fireteams_MenuText_Draw,
    NULL,
    0
}
Definition at line 109 of file cg_fireteams.c.
panel_button_text_t fireteamTitleFont
Initial value:
=
{
    0.19f,                    0.19f,
    { 0.6f,                   0.6f, 0.6f,  1.f },
    0,                        0,
    &cgs.media.limboFont1_lo,
}
Definition at line 37 of file cg_fireteams.c.
panel_button_t fireteamTopBorder
Initial value:
=
{
    NULL,
    NULL,
    { 10,                     129,      204,     136 },
    { 1,                      255 / 2,  255 / 2, 255 / 2, 255 / 2, 1, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 53 of file cg_fireteams.c.
panel_button_t fireteamTopBorderBack
Initial value:
=
{
    "white",
    NULL,
    { 11,                     130,202, 134 },
    { 1,                      0,  0,   0, (int)(255 * 0.75), 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 67 of file cg_fireteams.c.
panel_button_t fireteamTopBorderInner
Initial value:
=
{
    "white",
    NULL,
    { 12,                     131, 200, 12 },
    { 1,                      41,  51,  43, 204, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 81 of file cg_fireteams.c.
panel_button_t fireteamTopBorderInnerText
Initial value:
=
{
    NULL,
    NULL,
    { 15,                           141,  200, 12 },
    { 0,                            0,    0,   0, 0, 0, 0, 0},
    &fireteamTitleFont,
    NULL,
    NULL,
    CG_Fireteams_MenuTitleText_Draw,
    NULL,
    0
}
Definition at line 95 of file cg_fireteams.c.
const char* ftLeaderMenuList[]
Initial value:
=
{
    "Disband",
    "Leave",
    "Invite",
    "Kick",
    "Warn",
    "Change privacy",
    "Change admin",
    NULL,
}
Definition at line 408 of file cg_fireteams.c.
Referenced by CG_Fireteams_MenuText_Draw().
const char* ftLeaderMenuListAlphachars[]
Initial value:
=
{
    "D",
    "L",
    "I",
    "K",
    "W",
    "P",
    "A",
    NULL,
}
Definition at line 420 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
const char* ftMenuCovertOpsStrings[]
Initial value:
=
{
    "Explore Area",
    "Destroy Objective",
    "Infiltrate",
    "Go Undercover",
    "Provide Sniper Cover",
    NULL
}
Definition at line 284 of file cg_fireteams.c.
const char* ftMenuCovertOpsStringsAlphachars[]
Initial value:
=
{
    "E",
    "D",
    "I",
    "U",
    "S",
    NULL
}
Definition at line 294 of file cg_fireteams.c.
const char* ftMenuCovertOpsStringsMsg[]
Initial value:
=
{
    "FTExploreArea",
    "FTSatchelObjective",
    "FTInfiltrate",
    "FTGoUndercover",
    "FTProvideSniperCover",
    NULL
}
Definition at line 304 of file cg_fireteams.c.
const char* ftMenuEngineerStrings[]
Initial value:
=
{
    "Destroy Objective",
    "Repair Objective",
    "Construct Objective",
    "Disarm Dynamite",
    "Deploy Landmines",
    "Disarm Landmines",
    NULL
}
Definition at line 224 of file cg_fireteams.c.
const char* ftMenuEngineerStringsAlphachars[]
Initial value:
=
{
    "D",
    "R",
    "C",
    "A",
    "L",
    "M",
    NULL
}
Definition at line 235 of file cg_fireteams.c.
const char* ftMenuEngineerStringsMsg[]
Initial value:
=
{
    "FTDestroyObjective",
    "FTRepairObjective",
    "FTConstructObjective",
    "FTDisarmDynamite",
    "FTDeployLandmines",
    "FTDisarmLandmines",
    NULL
}
Definition at line 246 of file cg_fireteams.c.
const char* ftMenuFieldOpsStrings[]
Initial value:
=
{
    "Call Air-Strike",
    "Call Artillery",
    "Resupply Squad",
    "Resupply Me",
    NULL
}
Definition at line 257 of file cg_fireteams.c.
const char* ftMenuFieldOpsStringsAlphachars[]
Initial value:
=
{
    "A",
    "T",
    "R",
    "S",
    NULL
}
Definition at line 266 of file cg_fireteams.c.
const char* ftMenuFieldOpsStringsMsg[]
Initial value:
=
{
    "FTCallAirStrike",
    "FTCallArtillery",
    "FTResupplySquad",
    "FTResupplyMe",
    NULL
}
Definition at line 275 of file cg_fireteams.c.
const char* ftMenuMedicStrings[]
Initial value:
=
{
    "Heal Squad",
    "Heal Me",
    "Revive Team Mate",
    "Revive Me",
    NULL
}
Definition at line 196 of file cg_fireteams.c.
const char* ftMenuMedicStringsAlphachars[]
Initial value:
=
{
    "H",
    "M",
    "R",
    "E",
    NULL
}
Definition at line 205 of file cg_fireteams.c.
const char* ftMenuMedicStringsMsg[]
Initial value:
=
{
    "FTHealSquad",
    "FTHealMe",
    "FTReviveTeamMate",
    "FTReviveMe",
    NULL
}
Definition at line 214 of file cg_fireteams.c.
const char* ftMenuRootStrings[]
Initial value:
=
{
    "Soldier",
    "Medic",
    "Engineer",
    "Field Ops",
    "Covert Ops",
    "General",
    "Attack",
    "Fall Back",
    NULL
}
Definition at line 133 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
const char* ftMenuRootStringsAlphachars[]
Initial value:
=
{
    "S",
    "M",
    "E",
    "F",
    "C",
    "G",
    "A",
    "B",
    NULL
}
Definition at line 159 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
const char* ftMenuRootStringsMsg[]
Initial value:
=
{
    "",
    "",
    "",
    "",
    "",
    "",
    "FTAttack",
    "FTFallBack",
    NULL
}
Definition at line 146 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey().
const char* ftMenuSoldierStrings[]
Initial value:
=
{
    "Cover Me",
    "Covering Fire",
    "Mortar",
    NULL
}
Definition at line 172 of file cg_fireteams.c.
const char* ftMenuSoldierStringsAlphachars[]
Initial value:
=
{
    "C",
    "F",
    "M",
    NULL
}
Definition at line 180 of file cg_fireteams.c.
const char* ftMenuSoldierStringsMsg[]
Initial value:
=
{
    "FTCoverMe",
    "FTCoveringFire",
    "FTMortar",
    NULL
}
Definition at line 188 of file cg_fireteams.c.
const char** ftMenuStrings[]
Initial value:
=
{
    ftMenuSoldierStrings,
    ftMenuMedicStrings,
    ftMenuEngineerStrings,
    ftMenuFieldOpsStrings,
    ftMenuCovertOpsStrings,
}
Definition at line 314 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
const char** ftMenuStringsAlphachars[]
Initial value:
=
{
    ftMenuSoldierStringsAlphachars,
    ftMenuMedicStringsAlphachars,
    ftMenuEngineerStringsAlphachars,
    ftMenuFieldOpsStringsAlphachars,
    ftMenuCovertOpsStringsAlphachars,
}
Definition at line 323 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
const char** ftMenuStringsMsg[]
Initial value:
=
{
    ftMenuSoldierStringsMsg,
    ftMenuMedicStringsMsg,
    ftMenuEngineerStringsMsg,
    ftMenuFieldOpsStringsMsg,
    ftMenuCovertOpsStringsMsg,
}
Definition at line 332 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey().
const char* ftOffMenuList[]
Initial value:
=
{
    "Apply",
    "Create",
    NULL,
}
Definition at line 380 of file cg_fireteams.c.
Referenced by CG_Fireteams_MenuText_Draw().
const char* ftOffMenuListAlphachars[]
Initial value:
=
{
    "A",
    "C",
    NULL,
}
Definition at line 387 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
const char* ftOnMenuList[]
Initial value:
=
{
    "Propose",
    "Leave",
    NULL,
}
Definition at line 394 of file cg_fireteams.c.
Referenced by CG_Fireteams_MenuText_Draw().
const char* ftOnMenuListAlphachars[]
Initial value:
=
{
    "P",
    "L",
    NULL,
}
Definition at line 401 of file cg_fireteams.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().