ET: Legacy: src/cgame/cg_spawnpoints.c File Reference
cg_spawnpoints.c File Reference
#include "cg_local.h"
Functions
void CG_Spawnpoints_MenuTitleText_Draw (panel_button_t *button)
void CG_Spawnpoints_MenuText_Draw (panel_button_t *button)
CG_Spawnpoints_MenuText_Draw.
void CG_Spawnpoints_Setup (void)
CG_Spawnpoints_Setup.
void CG_Spawnpoints_KeyHandling (int key, qboolean down)
CG_Spawnpoints_KeyHandling.
void CG_Spawnpoints_Draw (void)
CG_Spawnpoints_Draw.
qboolean CG_SpawnpointsCheckExecKey (int key, qboolean doaction)
CG_SpawnpointsCheckExecKey.
Variables
panel_button_text_t spawnpointsTitleFont
panel_button_text_t spawnpointsFont
panel_button_t spawnpointsTopBorder
panel_button_t spawnpointsTopBorderBack
panel_button_t spawnpointsTopBorderInner
panel_button_t spawnpointsTopBorderInnerText
panel_button_t spawnpointsMenuItemText
panel_button_t * spawnpointsButtons []
Function Documentation
void CG_Spawnpoints_Draw (void)
CG_Spawnpoints_Draw.
Definition at line 202 of file cg_spawnpoints.c.
Referenced by CG_Draw2D().
void CG_Spawnpoints_KeyHandling (int key, qboolean down)
CG_Spawnpoints_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 191 of file cg_spawnpoints.c.
Referenced by CG_KeyEvent().
void CG_Spawnpoints_MenuText_Draw (panel_button_t * button)
CG_Spawnpoints_MenuText_Draw.
Parameters
[in] button
Definition at line 141 of file cg_spawnpoints.c.
void CG_Spawnpoints_MenuTitleText_Draw (panel_button_t * button)
Definition at line 132 of file cg_spawnpoints.c.
void CG_Spawnpoints_Setup (void)
CG_Spawnpoints_Setup.
Definition at line 181 of file cg_spawnpoints.c.
Referenced by CG_RegisterGraphics().
qboolean CG_SpawnpointsCheckExecKey (int key, qboolean doaction)
CG_SpawnpointsCheckExecKey.
Parameters
[in] key
[in] doaction
Returns
Definition at line 213 of file cg_spawnpoints.c.
Referenced by CG_CheckExecKey(), and CG_Spawnpoints_KeyHandling().
Variable Documentation
panel_button_t* spawnpointsButtons[]
Initial value:
=
{
    &spawnpointsTopBorderBack, &spawnpointsTopBorder, &spawnpointsTopBorderInner, &spawnpointsTopBorderInnerText,
    &spawnpointsMenuItemText,
    NULL
}
Definition at line 123 of file cg_spawnpoints.c.
panel_button_text_t spawnpointsFont
Initial value:
=
{
    0.2f,                    0.2f,
    { 0.6f,                  0.6f,0.6f,    1.f },
    ITEM_TEXTSTYLE_SHADOWED, 0,
    &cgs.media.limboFont2,
}
Definition at line 45 of file cg_spawnpoints.c.
panel_button_t spawnpointsMenuItemText
Initial value:
=
{
    NULL,
    NULL,
    { 16,                      153,  128, 12 },
    { 0,                       0,    0,   0, 0, 0, 0, 0},
    &spawnpointsFont,
    NULL,
    NULL,
    CG_Spawnpoints_MenuText_Draw,
    NULL,
    0
}
Definition at line 109 of file cg_spawnpoints.c.
panel_button_text_t spawnpointsTitleFont
Initial value:
=
{
    0.19f,                    0.19f,
    { 0.6f,                   0.6f, 0.6f,  1.f },
    0,                        0,
    &cgs.media.limboFont1_lo,
}
Definition at line 37 of file cg_spawnpoints.c.
panel_button_t spawnpointsTopBorder
Initial value:
=
{
    NULL,
    NULL,
    { 10,                     129,      204,     136 },
    { 1,                      255 / 2,  255 / 2, 255 / 2, 255 / 2, 1, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 53 of file cg_spawnpoints.c.
panel_button_t spawnpointsTopBorderBack
Initial value:
=
{
    "white",
    NULL,
    { 11,                     130,202, 134 },
    { 1,                      0,  0,   0, (int)(255 * 0.75), 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 67 of file cg_spawnpoints.c.
panel_button_t spawnpointsTopBorderInner
Initial value:
=
{
    "white",
    NULL,
    { 12,                     131, 200, 12 },
    { 1,                      41,  51,  43, 204, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 81 of file cg_spawnpoints.c.
panel_button_t spawnpointsTopBorderInnerText
Initial value:
=
{
    NULL,
    NULL,
    { 15,                           141,  200, 12 },
    { 0,                            0,    0,   0, 0, 0, 0, 0},
    &spawnpointsTitleFont,
    NULL,
    NULL,
    CG_Spawnpoints_MenuTitleText_Draw,
    NULL,
    0
}
Definition at line 95 of file cg_spawnpoints.c.