ET: Legacy: src/cgame/cg_main.c File Reference
cg_main.c File Reference
Initialization and primary entry point for cgame.
#include "cg_local.h"
Data Structures
struct cvarTable_t
Macros
#define DEBUG_INITPROFILE_INIT
#define DEBUG_INITPROFILE_EXEC(f)
Functions
void CG_Init (int serverMessageNum, int serverCommandSequence, int clientNum, qboolean demoPlayback, int legacyClient, demoPlayInfo_t *info, int clientVersion)
Called after every level change or subsystem restart Will perform callbacks to make the loading info screen update.
void CG_Shutdown (void)
Called before every level change or subsystem restart.
qboolean CG_CheckExecKey (int key)
CG_CheckExecKey.
Q_EXPORT intptr_t vmMain (intptr_t command, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11)
This is the only way control passes into the module.
void CG_setClientFlags (void)
CG_setClientFlags.
void CG_RegisterCvars (void)
CG_RegisterCvars.
void CG_UpdateCvars (void)
CG_UpdateCvars.
void CG_RestoreProfile (void)
CG_RestoreProfile.
qboolean CG_execFile (const char *filename)
Try to exec a cfg file if it is found.
int CG_CrosshairPlayer (void)
CG_CrosshairPlayer.
int CG_LastAttacker (void)
CG_LastAttacker.
void QDECL CG_Printf (const char *msg,...)
CG_Printf.
void QDECL CG_DPrintf (const char *msg,...)
CG_DPrintf.
void QDECL CG_Error (const char *msg,...)
CG_Error.
void QDECL Com_Error (int code, const char *error,...)
Com_Error.
void QDECL Com_Printf (const char *msg,...)
Com_Printf.
const char * CG_Argv (int arg)
CG_Argv.
char * CG_generateFilename (void)
Generate standard naming for screenshots/demos.
int CG_cleanName (const char *pszIn, char *pszOut, int dwMaxLength, qboolean fCRLF)
Strip colors and control codes, copying up to dwMaxLength-1 "good" chars and nul-terminating.
int CG_findClientNum (const char *s)
CG_findClientNum.
void CG_printConsoleString (const char *str)
CG_printConsoleString.
void CG_LoadObjectiveData (void)
CG_LoadObjectiveData.
void CG_SetupDlightstyles (void)
CG_SetupDlightstyles.
static void CG_RegisterItemSounds (int itemNum)
The server says this item is used on this level.
void CG_RegisterGameSounds ()
CG_RegisterGameSounds.
static void CG_RegisterSounds (void)
Called during a precache command.
sfxHandle_t CG_GetGameSound (int index)
CG_GetGameSound.
static void CG_RegisterGraphics (void)
CG_RegisterGraphics.
static void CG_RegisterClients (void)
CG_RegisterClients.
const char * CG_ConfigString (int index)
CG_ConfigString.
int CG_ConfigStringCopy (int index, char *buff, size_t buffsize)
CG_ConfigStringCopy.
void CG_StartMusic (void)
CG_StartMusic.
void CG_QueueMusic (void)
CG_QueueMusic.
static qboolean CG_OwnerDrawHandleKey (int ownerDraw, int flags, int *special, int key)
CG_OwnerDrawHandleKey.
static int CG_FeederCount (int feederID)
CG_FeederCount.
static clientInfo_t * CG_InfoFromScoreIndex (int index, int team, int *scoreIndex)
CG_InfoFromScoreIndex.
static const char * CG_FeederItemText (int feederID, int index, int column, qhandle_t *handle, int *numhandles)
CG_FeederItemText.
static qhandle_t CG_FeederItemImage (int feederID, int index)
CG_FeederItemImage.
static void CG_FeederSelection (int feederID, int index)
CG_FeederSelection.
float CG_Cvar_Get (const char *cvar)
CG_Cvar_Get.
static int CG_OwnerDrawWidth (int ownerDraw, float scale)
CG_OwnerDrawWidth.
static int CG_PlayCinematic (const char *name, float x, float y, float w, float h)
CG_PlayCinematic.
static void CG_StopCinematic (int handle)
CG_StopCinematic.
static void CG_DrawCinematic (int handle, float x, float y, float w, float h)
CG_DrawCinematic.
static void CG_RunCinematicFrame (int handle)
CG_RunCinematicFrame.
void CG_LoadHudMenu (void)
CG_LoadHudMenu.
void CG_AssetCache (void)
CG_AssetCache.
char * CG_GetRealTime (void)
Real time stamp.
void QDECL CG_WriteToLog (const char *fmt,...)
CG_WriteToLog.
Variables
displayContextDef_t cgDC
itemDef_t * g_bindItem
qboolean g_waitingForKey
cg_t cg
cgs_t cgs
centity_t cg_entities [MAX_GENTITIES]
weaponInfo_t cg_weapons [MAX_WEAPONS]
vmCvar_t cg_centertime
vmCvar_t cg_bobup
vmCvar_t cg_bobpitch
vmCvar_t cg_bobroll
vmCvar_t cg_swingSpeed
vmCvar_t cg_shadows
vmCvar_t cg_gibs
vmCvar_t cg_draw2D
vmCvar_t cg_drawFPS
vmCvar_t cg_drawPing
vmCvar_t cg_lagometer
vmCvar_t cg_drawSnapshot
vmCvar_t cg_drawCrosshair
vmCvar_t cg_drawCrosshairInfo
vmCvar_t cg_drawCrosshairNames
vmCvar_t cg_drawCrosshairPickups
vmCvar_t cg_weaponCycleDelay
vmCvar_t cg_cycleAllWeaps
vmCvar_t cg_useWeapsForZoom
vmCvar_t cg_crosshairSize
vmCvar_t cg_crosshairX
vmCvar_t cg_crosshairY
vmCvar_t cg_crosshairHealth
vmCvar_t cg_teamChatsOnly
vmCvar_t cg_voiceChats
vmCvar_t cg_voiceText
vmCvar_t cg_drawStatus
vmCvar_t cg_animSpeed
vmCvar_t cg_drawSpreadScale
vmCvar_t cg_railTrailTime
vmCvar_t cg_debugAnim
vmCvar_t cg_debugPosition
vmCvar_t cg_debugEvents
vmCvar_t cg_errorDecay
vmCvar_t cg_nopredict
vmCvar_t cg_noPlayerAnims
vmCvar_t cg_showmiss
vmCvar_t cg_markTime
vmCvar_t cg_brassTime
vmCvar_t cg_letterbox
vmCvar_t cg_drawGun
vmCvar_t cg_cursorHints
vmCvar_t cg_gun_frame
vmCvar_t cg_gun_x
vmCvar_t cg_gun_y
vmCvar_t cg_gun_z
vmCvar_t cg_tracerChance
vmCvar_t cg_tracerWidth
vmCvar_t cg_tracerLength
vmCvar_t cg_tracerSpeed
vmCvar_t cg_autoswitch
vmCvar_t cg_fov
vmCvar_t cg_muzzleFlash
vmCvar_t cg_zoomStepSniper
vmCvar_t cg_zoomDefaultSniper
vmCvar_t cg_thirdPerson
vmCvar_t cg_thirdPersonRange
vmCvar_t cg_thirdPersonAngle
vmCvar_t cg_teamChatTime
vmCvar_t cg_teamChatHeight
vmCvar_t cg_stats
vmCvar_t cg_buildScript
vmCvar_t cg_coronafardist
vmCvar_t cg_coronas
vmCvar_t cg_paused
vmCvar_t cg_blood
vmCvar_t cg_predictItems
vmCvar_t cg_autoactivate
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t cg_wolfparticles
vmCvar_t cg_gameType
vmCvar_t cg_bloodTime
vmCvar_t cg_skybox
vmCvar_t cg_messageType
vmCvar_t cg_timescale
vmCvar_t cg_voiceSpriteTime
vmCvar_t cg_drawCompass
vmCvar_t cg_drawNotifyText
vmCvar_t cg_quickMessageAlt
vmCvar_t cg_descriptiveText
vmCvar_t cg_redlimbotime
vmCvar_t cg_bluelimbotime
vmCvar_t cg_antilag
vmCvar_t developer
vmCvar_t authLevel
vmCvar_t cf_wstats
vmCvar_t cf_wtopshots
vmCvar_t cg_autoAction
vmCvar_t cg_autoReload
vmCvar_t cg_bloodDamageBlend
vmCvar_t cg_bloodFlash
vmCvar_t cg_complaintPopUp
vmCvar_t cg_crosshairAlpha
vmCvar_t cg_crosshairAlphaAlt
vmCvar_t cg_crosshairColor
vmCvar_t cg_crosshairColorAlt
vmCvar_t cg_crosshairPulse
vmCvar_t cg_drawReinforcementTime
vmCvar_t cg_drawWeaponIconFlash
vmCvar_t cg_noAmmoAutoSwitch
vmCvar_t cg_printObjectiveInfo
vmCvar_t cg_uinfo
vmCvar_t demo_avifpsF1
vmCvar_t demo_avifpsF2
vmCvar_t demo_avifpsF3
vmCvar_t demo_avifpsF4
vmCvar_t demo_avifpsF5
vmCvar_t demo_drawTimeScale
vmCvar_t demo_infoWindow
vmCvar_t int_cl_maxpackets
vmCvar_t int_cl_timenudge
vmCvar_t int_m_pitch
vmCvar_t int_sensitivity
vmCvar_t int_ui_blackout
vmCvar_t cg_rconPassword
vmCvar_t cg_refereePassword
vmCvar_t cg_atmosphericEffects
vmCvar_t cg_drawRoundTimer
vmCvar_t cg_instanttapout
vmCvar_t cg_debugSkills
vmCvar_t cg_drawFireteamOverlay
vmCvar_t cg_drawSmallPopupIcons
vmCvar_t cl_demorecording
vmCvar_t cl_demofilename
vmCvar_t cl_demooffset
vmCvar_t cl_waverecording
vmCvar_t cl_wavefilename
vmCvar_t cl_waveoffset
vmCvar_t cg_recording_statusline
vmCvar_t cg_announcer
vmCvar_t cg_hitSounds
vmCvar_t cg_locations
vmCvar_t cg_spawnTimer_set
vmCvar_t cg_spawnTimer_period
vmCvar_t cg_logFile
vmCvar_t cg_countryflags
GeoIP.
vmCvar_t cg_altHud
vmCvar_t cg_altHudFlags
vmCvar_t cg_tracers
vmCvar_t cg_fireteamLatchedClass
vmCvar_t cg_weapaltReloads
vmCvar_t cg_simpleItems
vmCvar_t cg_automapZoom
vmCvar_t cg_drawTime
vmCvar_t cg_popupFadeTime
vmCvar_t cg_popupStayTime
vmCvar_t cg_popupFilter
vmCvar_t cg_popupBigFilter
vmCvar_t cg_graphicObituaries
vmCvar_t cg_fontScaleTP
vmCvar_t cg_fontScaleSP
vmCvar_t cg_fontScaleCP
vmCvar_t cg_fontScaleCN
vmCvar_t cg_optimizePrediction
vmCvar_t cg_debugPlayerHitboxes
vmCvar_t cg_quickchat
vmCvar_t cg_drawspeed
vmCvar_t cg_visualEffects
turn invisible (0) / visible (1) visual effect (i.e airstrike plane, debris ...)
static cvarTable_t cvarTable []
static const unsigned int cvarTableSize = sizeof(cvarTable) / sizeof(cvarTable[0])
static qboolean cvarsLoaded = qfalse
Detailed Description
Initialization and primary entry point for cgame.
Definition in file cg_main.c.
Macro Definition Documentation
#define DEBUG_INITPROFILE_EXEC (f)
Definition at line 2553 of file cg_main.c.
Referenced by CG_Init().
#define DEBUG_INITPROFILE_INIT
Definition at line 2552 of file cg_main.c.
Referenced by CG_Init().
Function Documentation
const char* CG_Argv (int arg)
CG_Argv.
Parameters
[in] arg
Returns
Definition at line 955 of file cg_main.c.
Referenced by CG_ConfigStringModified(), CG_ConsoleCommand(), CG_CPM_f(), CG_Debriefing_ParsePlayerKillsDeaths(), CG_Debriefing_ParsePlayerTime(), CG_Debriefing_ParseWeaponAccuracies(), CG_Debriefing_ParseWeaponStats(), CG_Fade_f(), CG_parseBestShotsStats_cmd(), CG_parseMapVoteListInfo(), CG_parseMapVoteTally(), CG_ParsePortalPos(), CG_ParseScore(), CG_ParseTeamInfo(), CG_parseTopShotsStats_cmd(), CG_ParseWeaponStats(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_scores_cmd(), CG_SelectBuddy_f(), CG_ServerCommand(), CG_TestModel_f(), CG_topshotsParse_cmd(), CG_VoiceChat(), CG_vstrDown_f(), CG_vstrUp_f(), CG_Weapon_f(), and CG_WeaponBank_f().
void CG_AssetCache (void)
CG_AssetCache.
Definition at line 2527 of file cg_main.c.
Referenced by CG_Init().
qboolean CG_CheckExecKey (int key)
CG_CheckExecKey.
Parameters
[in] key
Returns
Definition at line 2870 of file cg_main.c.
Referenced by vmMain().
int CG_cleanName (const char * pszIn, char * pszOut, int dwMaxLength, qboolean fCRLF)
Strip colors and control codes, copying up to dwMaxLength-1 "good" chars and nul-terminating.
Parameters
[in] pszIn
[out] pszOut
[in] dwMaxLength
[in] fCRLF
Returns
The length of the cleaned string
Definition at line 997 of file cg_main.c.
Referenced by CG_findClientNum(), CG_parseBestShotsStats_cmd(), CG_parseTopShotsStats_cmd(), CG_parseWeaponStats_cmd(), CG_printFile(), CG_scores_cmd(), and CG_topshotsParse_cmd().
const char* CG_ConfigString (int index)
CG_ConfigString.
Parameters
[in] index
Returns
Definition at line 2143 of file cg_main.c.
Referenced by CG_ChargeTimesChanged(), CG_ConfigStringCopy(), CG_ConfigStringModified(), CG_createMOTDWindow(), CG_Debriefing_FindWinningTeamForMap(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_ParseAwards(), CG_Debriefing_Startup(), CG_DebriefingTitle_Draw(), CG_DrawConnectScreen(), CG_DrawCrosshairNames(), CG_DrawFlag(), CG_DrawMapEntity(), CG_DrawScoreboard(), CG_DrawWarmup(), CG_dumpStats(), CG_Effect(), CG_EntityEvent(), CG_generateFilename(), CG_GetPMItemText(), CG_Init(), CG_LimboPanel_GetMaxObjectives(), CG_LimboPanel_RenderObjectiveText(), CG_LoadPanel_RenderCampaignPins(), CG_MapRestart(), CG_NewClientInfo(), CG_NewParticleArea(), CG_ObjectivesDraw(), CG_ParseFireteams(), CG_ParseFog(), CG_ParseGlobalFog(), CG_ParseLegacyinfo(), CG_ParseOIDInfo(), CG_ParseScreenFade(), CG_ParseServerinfo(), CG_ParseSkyBox(), CG_ParseSpawns(), CG_ParseSysteminfo(), CG_ParseTagConnect(), CG_ParseTeamXPs(), CG_ParseWarmup(), CG_ParseWolfinfo(), CG_PlayGlobalSound(), CG_QueueMusic(), CG_RegisterClients(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_SetConfigValues(), CG_SetupDlightstyles(), CG_ShaderStateChanged(), CG_SkillLevelsChanged(), CG_StartMusic(), CG_TeamRestrictionsChanged(), CG_TouchTriggerPrediction(), CG_UpdateSvCvars(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
int CG_ConfigStringCopy (int index, char * buff, size_t buffsize)
CG_ConfigStringCopy.
Parameters
[in] index
[out] buff
[in] buffsize
Returns
Definition at line 2159 of file cg_main.c.
Referenced by CG_LoadHudMenu().
int CG_CrosshairPlayer (void)
CG_CrosshairPlayer.
Returns
Definition at line 802 of file cg_main.c.
Referenced by vmMain().
float CG_Cvar_Get (const char * cvar)
CG_Cvar_Get.
Parameters
[in] cvar
Returns
Definition at line 2379 of file cg_main.c.
Referenced by CG_LoadHudMenu().
void QDECL CG_DPrintf (const char * msg, ...)
CG_DPrintf.
Parameters
[in] msg
Definition at line 864 of file cg_main.c.
static void CG_DrawCinematic (int handle, float x, float y, float w, float h) static
CG_DrawCinematic.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 2431 of file cg_main.c.
Referenced by CG_LoadHudMenu().
void QDECL CG_Error (const char * msg, ...)
CG_Error.
Parameters
[in] msg
Definition at line 900 of file cg_main.c.
Referenced by CG_ConfigString(), CG_Init(), CG_RegisterGraphics(), Com_Error(), and vmMain().
qboolean CG_execFile (const char * filename)
Try to exec a cfg file if it is found.
Parameters
[in] filename
Returns
Definition at line 753 of file cg_main.c.
Referenced by CG_Init(), and CG_Respawn().
static int CG_FeederCount (int feederID) static
CG_FeederCount.
Parameters
[in] feederID
Returns
Definition at line 2224 of file cg_main.c.
Referenced by CG_LoadHudMenu().
static qhandle_t CG_FeederItemImage (int feederID, int index) static
CG_FeederItemImage.
Parameters
feederID - unused
index - unused
Returns
Note
not yet implemented. referenced in cgDC.feederItemImage but return always 0
Definition at line 2346 of file cg_main.c.
Referenced by CG_LoadHudMenu().
static const char* CG_FeederItemText (int feederID, int index, int column, qhandle_t * handle, int * numhandles) static
CG_FeederItemText.
Parameters
[in] feederID
[in] index
[in] column
[out] handle
numhandles - unused
Returns
Definition at line 2294 of file cg_main.c.
Referenced by CG_LoadHudMenu().
static void CG_FeederSelection (int feederID, int index) static
CG_FeederSelection.
Parameters
[in] feederID
[in] index
Definition at line 2356 of file cg_main.c.
Referenced by CG_LoadHudMenu().
int CG_findClientNum (const char * s)
CG_findClientNum.
Parameters
[in] s
Returns
Definition at line 1027 of file cg_main.c.
char* CG_generateFilename (void)
Generate standard naming for screenshots/demos.
Returns
Definition at line 968 of file cg_main.c.
Referenced by CG_autoRecord_f(), and CG_autoScreenShot_f().
sfxHandle_t CG_GetGameSound (int index)
CG_GetGameSound.
Parameters
[in] index
Returns
Definition at line 1470 of file cg_main.c.
Referenced by CG_AddLightstyle(), CG_EntityEffects(), CG_EntityEvent(), CG_GetSoundFx(), CG_PlayGlobalSound(), and CG_Speaker().
char* CG_GetRealTime (void)
Real time stamp.
Returns
Definition at line 2889 of file cg_main.c.
Referenced by CG_WriteToLog().
static clientInfo_t* CG_InfoFromScoreIndex (int index, int team, int * scoreIndex) static
CG_InfoFromScoreIndex.
Parameters
[in] index
[in] team
[out] scoreIndex
Returns
Definition at line 2263 of file cg_main.c.
Referenced by CG_FeederItemText().
void CG_Init (int serverMessageNum, int serverCommandSequence, int clientNum, qboolean demoPlayback, int legacyClient, demoPlayInfo_t * info, int clientVersion)
Called after every level change or subsystem restart Will perform callbacks to make the loading info screen update.
Parameters
serverMessageNum
serverCommandSequence
clientNum
demoPlayback
legacyClient
info
clientVersion
Definition at line 2567 of file cg_main.c.
Referenced by vmMain().
int CG_LastAttacker (void)
CG_LastAttacker.
Returns
Definition at line 815 of file cg_main.c.
Referenced by vmMain().
void CG_LoadHudMenu (void)
CG_LoadHudMenu.
Definition at line 2449 of file cg_main.c.
Referenced by CG_Init().
void CG_LoadObjectiveData (void)
CG_LoadObjectiveData.
Definition at line 1085 of file cg_main.c.
Referenced by CG_MapRestart(), and CG_RegisterGraphics().
static qboolean CG_OwnerDrawHandleKey (int ownerDraw, int flags, int * special, int key) static
CG_OwnerDrawHandleKey.
Parameters
ownerDraw - unused
flags - unused
special - unused
key - unused
Returns
TODO: always true
Todo:
not yet implemented ? referenced in cgDC.ownerDrawHandleKey and return always true
Definition at line 2214 of file cg_main.c.
Referenced by CG_LoadHudMenu().
static int CG_OwnerDrawWidth (int ownerDraw, float scale) static
CG_OwnerDrawWidth.
Parameters
ownerDraw - unused
scale - unused
Returns
Note
Definition at line 2395 of file cg_main.c.
Referenced by CG_LoadHudMenu().
static int CG_PlayCinematic (const char * name, float x, float y, float w, float h) static
CG_PlayCinematic.
Parameters
[in] name
[in] x
[in] y
[in] w
[in] h
Returns
Definition at line 2409 of file cg_main.c.
Referenced by CG_LoadHudMenu().
void CG_printConsoleString (const char * str)
CG_printConsoleString.
Parameters
[in] str
Definition at line 1077 of file cg_main.c.
Referenced by CG_ServerCommand().
void QDECL CG_Printf (const char * msg, ...)
CG_Printf.
Parameters
[in] msg
Definition at line 832 of file cg_main.c.
Referenced by CG_findClientNum(), CG_Init(), CG_LoadObjectiveData(), CG_printConsoleString(), CG_RegisterCvars(), CG_RegisterGraphics(), CG_RestoreProfile(), and Com_Printf().
void CG_QueueMusic (void)
CG_QueueMusic.
Todo:
: \/ the values stored in here will be made accessable so
Definition at line 2189 of file cg_main.c.
Referenced by CG_ConfigStringModified().
static void CG_RegisterClients (void) static
CG_RegisterClients.
Definition at line 2119 of file cg_main.c.
Referenced by CG_Init().
void CG_RegisterCvars (void)
CG_RegisterCvars.
Definition at line 609 of file cg_main.c.
Referenced by CG_Init().
void CG_RegisterGameSounds ()
CG_RegisterGameSounds.
Definition at line 1279 of file cg_main.c.
Referenced by CG_RegisterSounds().
static void CG_RegisterGraphics (void) static
CG_RegisterGraphics.
This function may execute for a couple of minutes with a slow disk.
Todo:
: remove from shader def
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: no icon, add it ?
Todo:
: remove from shader def
Todo:
: remove from shader def
Todo:
: remove from shader def
Todo:
: remove from shader def
Todo:
: remove from shader def
Todo:
: add gfx/limbo/cm_jagdpanther?
Todo:
: remove from shader def
Todo:
find a better sound
Todo:
: temp models
Definition at line 1486 of file cg_main.c.
Referenced by CG_Init().
static void CG_RegisterItemSounds (int itemNum) static
The server says this item is used on this level.
Parameters
[in] itemNum
Definition at line 1266 of file cg_main.c.
Referenced by CG_RegisterSounds().
static void CG_RegisterSounds (void) static
Called during a precache command.
Todo:
: need a real sound for this
Definition at line 1303 of file cg_main.c.
Referenced by CG_Init().
void CG_RestoreProfile (void)
CG_RestoreProfile.
Definition at line 733 of file cg_main.c.
Referenced by CG_Init(), and CG_Shutdown().
static void CG_RunCinematicFrame (int handle) static
CG_RunCinematicFrame.
Parameters
[in] handle
Definition at line 2441 of file cg_main.c.
Referenced by CG_LoadHudMenu().
void CG_setClientFlags (void)
CG_setClientFlags.
Definition at line 773 of file cg_main.c.
Referenced by CG_RegisterCvars(), and CG_UpdateCvars().
void CG_SetupDlightstyles (void)
CG_SetupDlightstyles.
Definition at line 1200 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
void CG_Shutdown (void)
Called before every level change or subsystem restart.
Definition at line 2837 of file cg_main.c.
Referenced by vmMain().
void CG_StartMusic (void)
CG_StartMusic.
Definition at line 2170 of file cg_main.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
static void CG_StopCinematic (int handle) static
CG_StopCinematic.
Parameters
[in] handle
Definition at line 2418 of file cg_main.c.
Referenced by CG_LoadHudMenu().
void CG_UpdateCvars (void)
CG_UpdateCvars.
Definition at line 651 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
void QDECL CG_WriteToLog (const char * fmt, ...)
CG_WriteToLog.
Parameters
[in] fmt
Definition at line 2906 of file cg_main.c.
void QDECL Com_Error (int code, const char * error, ...)
Com_Error.
Parameters
[in] code - unused
[in] error
Note
FIXME: this is only here so the functions in q_shared.c and bg_*.c can link
Definition at line 920 of file cg_main.c.
Referenced by __attribute__(), BaseWindingForPlane(), BG_AddPathCorner(), BG_AddSplineControl(), BG_AddSplinePath(), BG_CanItemBeGrabbed(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), BG_GetAnimationForIndex(), BG_GetConditionBitFlag(), BotImport_HunkAlloc(), Cbuf_ExecuteText(), CG_LoadHudMenu(), checkDownloadName(), CheckWinding(), ChopWindingInPlace(), CIN_DecodeChunk(), CIN_DecodeQuadInfo(), CIN_DecodeQuadVQ(), CIN_GetCinematicByHandle(), CIN_HandleForCinematic(), CIN_PlayCinematic(), CIN_RunCinematic(), CL_AddReliableCommand(), CL_Cache_SetIndex_f(), CL_Cache_UsedFile_f(), CL_CGameBinaryMessageReceived(), CL_CgameSystemCalls(), CL_CheckForResend(), CL_ConfigstringModified(), CL_Connect_f(), CL_Disconnect_f(), CL_GetServerCommand(), CL_GetSnapshot(), CL_GetUserCmd(), CL_InitCGame(), CL_InitRef(), CL_InitUI(), CL_JoystickEvent(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PrintPacket(), CL_SetCGameTime(), CL_UISystemCalls(), CL_UpdateLevelHunkUsage(), ClipWindingEpsilon(), CM_AdjustAreaPortalState(), CM_AreasConnected(), CM_ClipHandleToModel(), CM_EdgePlaneNum(), CM_FindPlane(), CM_FindPlane2(), CM_FloodArea_r(), CM_GeneratePatchCollide(), CM_InlineModel(), CM_LeafArea(), CM_LeafCluster(), CM_LoadMap(), CM_PatchCollideFromGrid(), CM_SetBorderInward(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPatches(), CMod_LoadPlanes(), CMod_LoadShaders(), CMod_LoadSubmodels(), Com_InitUpdateDownloads(), COM_MatchToken(), COM_ParseExt2(), Com_SetupDownload(), Com_WWWDownload(), Cvar_Get(), Cvar_SetSafe(), Cvar_Update(), END_CHUNK(), Field_VariableSizeDraw(), FreeWinding(), FS_CheckFilenameIsMutable(), FS_CheckFilenameIsNotExecutable(), FS_CheckRequiredFiles(), FS_CL_ExtractFromPakFile(), FS_CopyFile(), FS_CreatePath(), FS_Delete(), FS_DeleteDir(), FS_FCloseFile(), FS_FileForHandle(), FS_FileIsInPAK(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileByMode(), FS_FOpenFileRead(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_fplength(), FS_FreeFile(), FS_FreeFileList(), FS_FTell(), FS_HandleForFile(), FS_ListFilteredFiles(), FS_Read(), FS_ReadFile(), FS_Rename(), FS_Seek(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_VerifyOfficialPaks(), FS_Write(), FS_WriteFile(), G_DropWeapon(), GLimp_DetectAvailableModes(), GLimp_Init(), GLimp_StartDriverAndSetMode(), IN_GrabMouse(), IN_Init(), Info_RemoveKey(), Info_RemoveKey_Big(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Info_ValueForKey(), Menus_ActivateByName(), MSG_Copy(), MSG_ReadBits(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReadDeltaSharedEntity(), MSG_WriteBits(), MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDeltaEntity(), MSG_WriteShort(), NET_SendPacket(), Netchan_Transmit(), PC_CopyToken(), PC_SourceError(), Q_GenerateHashValue(), Q_strcat(), Q_strncpyz(), R_PrintLongString(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_StartSoundEx(), S_Base_UpdateEntityPosition(), S_FindName(), S_GetSoundLength(), S_Init(), SafeFS_Write(), SCR_DrawScreenField(), SND_setup(), START_CHUNK(), SV_BotFreeClient(), SV_BuildClientSnapshot(), SV_ChangeMaxClients(), SV_DemoPlaybackError(), SV_DemoStopPlayback(), SV_DirectConnect(), SV_EmitPacketEntities(), SV_GameSystemCalls(), SV_GetConfigstring(), SV_GetServerinfo(), SV_GetUsercmd(), SV_GetUserinfo(), SV_InitGameProgs(), SV_LoadTag(), SV_QsortEntityNumbers(), SV_RestartGameProgs(), SV_SetBrushModel(), SV_SetConfigstring(), SV_SetConfigstringNoUpdate(), SV_SetUserinfo(), SV_Startup(), SV_SvEntityForGentity(), SV_TouchCGameDLL(), Sys_ListFiles(), Sys_OpenURL(), Sys_SendPacket(), Sys_SockaddrToString(), Sys_StartProcess(), UI_Init(), va(), VM_CallFunc(), VM_CallInterpreted(), VM_Create(), VM_PrepareInterpreter(), VM_Restart(), WRITE_2BYTES(), WRITE_4BYTES(), and WRITE_STRING().
void QDECL Com_Printf (const char * msg, ...)
Com_Printf.
Parameters
[in] msg
Definition at line 936 of file cg_main.c.
Referenced by __attribute__(), BG_AddPredictableEventToPlayerstate(), BG_AnimScriptAnimation(), BG_AnimScriptEvent(), BG_BuildSplinePaths(), BG_EvaluateConditions(), BG_GetMarkDir(), BG_PCF_ParseError(), BG_RAG_ParseError(), BG_SS_ParseError(), BG_SS_StoreSpeaker(), BG_StringHashValue(), Cbuf_AddText(), Cbuf_InsertText(), CG_getHudByNumber(), CG_HUD_ParseError(), CG_Hud_Setup(), CG_Init(), CG_LoadHudMenu(), CG_ParseHUD(), CG_ParseWeaponConfig(), CG_ReadHudScripts(), CG_RW_ParseError(), CG_RW_ParseModModel(), CG_SetHud(), CIN_ListCinematics_f(), CIN_PlayCinematic(), CIN_PlayCinematic_f(), CIN_ResetCinematic(), CIN_UploadCinematic(), CL_AdjustTimeDelta(), CL_CgameSystemCalls(), CL_Clientinfo_f(), CL_CloseAVI(), CL_Configstrings_f(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_DisconnectPacket(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_GenerateETKey(), CL_GetSnapshot(), CL_GlobalServers_f(), CL_Init(), CL_InitCGame(), CL_InitRef(), CL_KeyEvent(), CL_KeyState(), CL_LocalServers_f(), CL_MouseMove(), CL_OpenAVIForWriting(), CL_OpenedPK3List_f(), CL_OpenURL(), CL_PacketEvent(), CL_ParseDownload(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_Ping_f(), CL_PrintPacket(), CL_Rcon_f(), CL_Reconnect_f(), CL_ReferencedPK3List_f(), CL_RequestMotd(), CL_SendBinaryMessage(), CL_SendCmd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus_f(), CL_ServerStatusResponse(), CL_Shutdown(), CL_StartVideoRecording(), CL_SystemInfoChanged(), CL_UISystemCalls(), CL_UpdateGUID(), CL_Video_f(), CL_WavRecord_f(), CL_WavStopRecord_f(), CL_WriteAVIAudioFrame(), CL_WritePacket(), CL_WriteWaveClose(), CL_WriteWaveOpen(), ClientForString(), CM_AddFacetBevels(), CM_DrawDebugSurface(), CM_GridPlane(), Cmd_AddSystemCommand(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_List_f(), Cmd_RemoveCommand(), Cmd_RemoveCommandSafe(), Cmd_Vstr_f(), Com_BeginDownload(), Com_CheckAutoUpdate(), Com_Download_f(), Com_DownloadsComplete(), Com_GetAutoUpdate(), COM_ParseError(), Com_ParseInfos(), Com_sprintf(), Com_UnpackUpdatePackage(), Com_UpdateInfoPacket(), Com_WWWBadChecksum(), Com_WWWDownload(), Con_Dump_f(), CON_Init(), CON_Input(), Console_Key(), Cvar_Cycle_f(), Cvar_Get(), Cvar_List_f(), Cvar_Print(), Cvar_Print_f(), Cvar_Register(), Cvar_Reset_f(), Cvar_Restart_f(), Cvar_Set2(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Cvar_Validate(), Cvar_WriteVariables(), DB_BeginTransaction(), DB_Callback(), DB_CallbackVersion(), DB_CheckUpdates(), DB_Close(), DB_Create(), DB_CreateOrUpdateSchema(), DB_EndTransaction(), DB_ExecSQLCommand_f(), DB_Init(), DB_SaveMemDB(), DB_SaveMemDB_f(), DL_BeginDownload(), DL_DownloadLoop(), DL_GetString(), DL_InitDownload(), DL_write_function(), FS_CL_ExtractFromPakFile(), FS_ComparePaks(), FS_CopyFile(), FS_CreatePath(), FS_Dir_f(), FS_FileExists(), FS_Fileinfo_f(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_HomeRemove(), FS_InitFilesystem(), FS_NewDir_f(), FS_Path_f(), FS_PureServerSetLoadedPaks(), FS_Remove(), FS_Rename(), FS_Restart(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_TouchFile_f(), FS_Unzip(), FS_UnzipTo(), FS_VerifyOfficialPaks(), FS_Which(), FS_Which_f(), FS_Write(), FS_WriteFile(), G_ConfigError(), G_configLoadAndSet(), G_GetPlayerByNum(), GameType_Parse(), GetConfigString(), GLimp_CheckForVersionExtension(), GLimp_DetectAvailableModes(), GLimp_EndFrame(), GLimp_Init(), GLimp_InitExtensionsR2(), GLimp_InitOpenGLContext(), GLimp_ModeList_f(), GLimp_SetGamma(), GLimp_SetMode(), GLimp_StartDriverAndSetMode(), I18N_Init(), I18N_SetLanguage(), IN_Init(), IN_InitJoystick(), IN_KeyDown(), IN_PrintJoystickInfo_f(), IN_PrintKey(), IN_Shutdown(), Info_SetValueForKey(), Info_SetValueForKey_Big(), IRC_AttemptConnection(), IRC_Connect(), IRC_Display(), IRC_HandleCTCP(), IRC_HandleError(), IRC_Parser(), IRC_Say(), IRC_Thread(), IRCH_Nick(), IRCH_NickError(), IRCH_ServerError(), Key_Bind_f(), Key_Bindlist_f(), Key_Unbind_f(), LAN_AddServer(), LAN_GetServerAddressString(), LAN_GetServerCount(), LAN_GetServerInfo(), LAN_GetServerPing(), LAN_GetServerPtr(), LAN_LoadCachedServers(), LAN_RemoveServer(), LAN_SaveServersToFile(), main(), Menus_CloseByName(), MSG_PrioritiseEntitystateFields(), MSG_PrioritisePlayerStateFields(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReportChangeVectors_f(), MSG_WriteBigString(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), MSG_WriteString(), NET_AddLocalAddress(), NET_AdrToString(), NET_AdrToStringNoPort(), NET_CompareBaseAdrMask(), NET_Config(), NET_GetLocalAddress(), NET_GetPacket(), NET_Init(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), NET_OpenIP(), NET_OpenSocks(), NET_SendPacket(), NET_SetMulticast6(), NET_Sleep(), NetadrToSockadr(), Netchan_Process(), Netchan_Transmit(), Netchan_TransmitNextFragment(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ExpandDefine(), PC_SourceError(), PM_CorrectAllSolid(), PM_CrashLand(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_SlideMove(), PM_StepSlideMove(), PM_Weapon(), QInputbuf::QInputbuf(), R_PrintLongString(), RE_InitOpenGlSubsystems(), ROQ_UpdateCinematic(), S_AddLoopSounds(), S_AL_Init(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_FadeStreamingSound(), S_Base_Init(), S_Base_Reload(), S_Base_SoundInfo(), S_Base_SoundList(), S_Base_StartLocalSound(), S_Base_StartSoundEx(), S_Base_Update(), S_CodecLoad(), S_CodecOpenStream(), S_CodecUtilOpen(), S_DisplayFreeMemory(), S_Init(), S_LoadSound(), S_Music_f(), S_Play_f(), S_ReadChunkInfo(), S_ReadRIFFHeader(), S_StartStreamingSoundEx(), S_Stream_f(), S_UpdateStreamingSounds(), S_WAV_CodecLoad(), Script_ExecWolfConfig(), Script_WriteProfile(), SHOWNET(), SND_DeviceList(), SND_setup(), SNDDMA_Init(), SNDDMA_PrintAudiospec(), SNDDMA_Shutdown(), String_Report(), SV_AddEntToSnapshot(), SV_AddServerCommand(), SV_AreaEntities_r(), SV_CheckDownloadAllowed(), SV_CheckFallbackURL(), SV_ClientCommand(), SV_CloseAttackLog(), SV_ConnectionlessPacket(), SV_ConSay_f(), SV_Demo_Play_f(), SV_Demo_Record_f(), SV_Demo_Stop_f(), SV_DemoAutoDemoRecord(), SV_DemoCvarsRestore(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopPlayback(), SV_DemoStopRecord(), SV_DirectConnect(), SV_DoneDownload_f(), SV_DumpUser_f(), SV_ExecuteClientMessage(), SV_Frame(), SV_GameSystemCalls(), SV_GetPlayerByName(), SV_InitAttackLog(), SV_isClientIPValidToConnect(), SV_LoadTag(), SV_Map_f(), SV_MapRestart_f(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SV_NextDownload_f(), SV_PacketEvent(), SV_SectorList_f(), SV_SendBinaryMessage(), SV_SendClientIdle(), SV_SendClientSnapshot(), SV_SendServerCommand(), SV_Serverinfo_f(), SV_SetupDownloadFile(), SV_Shutdown(), SV_SpawnServer(), SV_Status_f(), SV_StopDownload_f(), SV_Systeminfo_f(), SV_UnlinkEntity(), SV_UpdateConfigStrings(), SV_Uptime_f(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteAttackLog(), SV_WWWDownload_f(), SVC_HashForAddress(), SVC_RemoteCommand(), Sys_Chmod(), Sys_DefaultHomePath(), Sys_Dialog(), Sys_ErrorDialog(), Sys_FOpen(), Sys_GameLoop(), Sys_ListFiles(), Sys_LoadDll(), Sys_LoadGameDll(), Sys_OpenURL(), Sys_PlatformInit(), Sys_SendPacket(), Sys_ShowIP(), Sys_StringToSockaddr(), Sys_TryLibraryLoad(), Sys_UnloadDll(), Sys_WritePIDFile(), Tinygettext_Error(), Tinygettext_Info(), Tinygettext_Warning(), trap_S_RegisterSound(), trap_TranslateString(), UI_Campaign_f(), UI_Init(), UI_ListCampaigns_f(), UI_ListFavourites_f(), UI_RegisterCvars(), UI_RemoveAllFavourites_f(), UI_RunMenuScript(), UI_SetActiveMenu(), UI_StopServerRefresh(), UpdateIPBans(), VM_CallFunc(), VM_CallInterpreted(), VM_Create(), VM_Indent(), VM_LoadSymbols(), VM_Restart(), VM_VmInfo_f(), VM_VmProfile_f(), and vmMain().
Q_EXPORT intptr_t vmMain (intptr_t command, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11)
This is the only way control passes into the module.
This must be the very first function compiled into the .q3vm file
Parameters
command
[in] arg0
[in] arg1
[in] arg2
[in] arg3
[in] arg4
[in] arg5
[in] arg6
[in] arg7 - unused
[in] arg8 - unused
[in] arg9 - unused
[in] arg10 - unused
[in] arg11 - unused
Returns
Definition at line 64 of file cg_main.c.
Variable Documentation
vmCvar_t authLevel
Definition at line 226 of file cg_main.c.
Referenced by CG_ParseServerinfo().
vmCvar_t cf_wstats
Definition at line 228 of file cg_main.c.
Referenced by CG_createStatsWindow().
vmCvar_t cf_wtopshots
Definition at line 229 of file cg_main.c.
Referenced by CG_createTopShotsWindow().
cg_t cg
Definition at line 119 of file cg_main.c.
Referenced by CG_ActivateEditSoundMode(), CG_AddAtmosphericEffects(), CG_AddBloodElements(), CG_AddBloodTrails(), CG_AddBufferedSoundScript(), CG_AddBufferedVoiceChat(), CG_AddCEntity(), CG_AddCEntity_Filter(), CG_AddDebris(), CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), CG_AddEmitter(), CG_AddEntityToTag(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFlameChunks(), CG_AddFlameSpriteToScene(), CG_AddFlameToScene(), CG_AddFragment(), CG_AddFuseSparkElements(), CG_AddLagometerFrameInfo(), CG_AddLagometerSnapshotInfo(), CG_AddLightstyle(), CG_AddLinkedEntity(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddMoveScaleFade(), CG_AddMovingTracer(), CG_AddOnScreenText(), CG_AddPacketEntities(), CG_AddPainTwitch(), CG_AddParticles(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddPMItem(), CG_AddPMItemBig(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddScriptSpeakers(), CG_AddSmokeJunc(), CG_AddSmokeSprites(), CG_AddSparkElements(), CG_AddSparkJunc(), CG_AddSparks(), CG_AddSpawnVarToken(), CG_AddSpriteExplosion(), CG_addString(), CG_AddTestModel(), CG_AddToTeamChat(), CG_AddTrailJunc(), CG_AddTrails(), CG_AddTrailToScene(), CG_AddViewWeapon(), CG_AdjustPositionForMover(), CG_AdjustZoomVal(), CG_AltWeapon_f(), CG_AnimPlayerConditions(), CG_AttachBitsToTank(), CG_AutomapExpandDown_f(), CG_AutomapExpandUp_f(), CG_Beam_2(), CG_Bleed(), CG_BloodTrail(), CG_BreathPuffs(), CG_BubbleTrail(), CG_BuddyVoiceChat_f(), CG_BuildLocationString(), CG_BuildSelectedFirteamString(), CG_BuildSolidList(), CG_Bullet(), CG_BulletImpact(), CG_CalcEntityLerpPositions(), CG_CalcFov(), CG_CalcMuzzlePoint(), CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_CalculateWeaponPosition(), CG_CalcViewValues(), CG_CalcVrect(), CG_CenterPrint(), CG_ChargeTimesChanged(), CG_CheckCanSwitch(), CG_CheckEvents(), CG_CheckForCursorHints(), CG_CheckLocalSounds(), CG_CheckPlayerstateEvents(), CG_Class_f(), CG_ClassMenu_f(), CG_ClassSkillForPosition(), CG_ClearHudHeadLerpFrame(), CG_ClearLerpFrame(), CG_ClearLerpFrameRate(), CG_ClearParticles(), CG_ClearWeapLerpFrame(), CG_ClientHitboxMaxZ(), CG_ClientInfoForPosition(), CG_ClipMoveToEntities(), CG_ColorForHealth(), CG_CommandCentreSpawnPointClick(), CG_CompasMoveLocationCalc(), CG_ConfigStringModified(), CG_ConsoleCommand(), CG_ContinueWeaponAnim(), CG_corona(), CG_Corona(), CG_Coronas(), CG_CountFireteamsByTeam(), CG_CountPlayersNF(), CG_CountPlayersSF(), CG_createMOTDWindow(), CG_createStatsWindow(), CG_createTopShotsWindow(), CG_DamageBlendBlob(), CG_DamageFeedback(), CG_DeActivateEditSoundMode(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatButton_KeyDown(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_GetSelectedClientInfo(), CG_Debriefing_InfoRequests(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_ReadyButton_Draw(), CG_Debriefing_ReadyButton_KeyDown(), CG_Debriefing_Startup(), CG_DebriefingPlayerList_Draw(), CG_DebriefingTitle_Draw(), CG_Debris(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoControlButtonDown(), CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DisguiseMapCheck(), CG_Draw2D(), CG_DrawActive(), CG_DrawActiveFrame(), CG_DrawActiveHud(), CG_DrawAutoMap(), CG_DrawBreathBar(), CG_DrawBulletTracer(), CG_DrawCenterString(), CG_DrawCompassIcon(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawDemoRecording(), CG_DrawDisconnect(), CG_DrawExpandedAutoMap(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlashBlend(), CG_DrawFlashDamage(), CG_DrawFlashFade(), CG_DrawFlashFire(), CG_DrawFlashZoomTransition(), CG_DrawFollow(), CG_DrawGrid(), CG_DrawGunIcon(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawLagometer(), CG_DrawLandmine(), CG_DrawLimboMessage(), CG_DrawLivesLeft(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMineMarkerFlag(), CG_DrawMiscGamemodels(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNewCompass(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), CG_DrawOnScreenLabels(), CG_DrawOverlays(), CG_DrawPing(), CG_DrawPlayerHead(), CG_DrawPlayerHealth(), CG_DrawPlayerHealthBar(), CG_DrawPlayerStatus(), CG_DrawPlayerStatusHead(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScopedReticle(), CG_DrawScoreboard(), CG_DrawSkills(), CG_DrawSkyBoxPortal(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawStaminaBar(), CG_DrawStatsDebug(), CG_DrawTeamInfo(), CG_DrawTimedMenus(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawTracer(), CG_DrawUpperRight(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeapHeat(), CG_DrawWeapRecharge(), CG_DrawWeapStability(), CG_DrawXP(), CG_DumpSpeaker_f(), CG_dumpStats_f(), CG_DynamiteTrail(), CG_EditSpeakers_f(), CG_Effect(), CG_EffectGust(), CG_EffectGustCurrent(), CG_EffectParse(), CG_EntityEffects(), CG_EntityEvent(), CG_EntOnFire(), CG_EventHandling(), CG_Explodef(), CG_Fade(), CG_Fade_f(), CG_FadeColor(), CG_FinishWeaponChange(), CG_FireFlameChunks(), CG_FireteamCheckExecKey(), CG_FireTeamForPosition(), CG_FireteamHasClass(), CG_FireTeamPlayerForPosition(), CG_Fireteams_MenuText_Draw(), CG_FireWeapon(), CG_FragmentBounceMark(), CG_FTSayPlayerClass_f(), CG_GameStatsDraw(), CG_General(), CG_getBindKeyName(), CG_GetPMItemText(), CG_GetSecondaryWeapon(), CG_GetTag(), CG_GetTeamColor(), CG_GetWeaponTag(), CG_GetWindVector(), CG_GrenadeTrail(), CG_initStrings(), CG_inSVCVARBackupList(), CG_InterpolateEntityPosition(), CG_InterpolatePlayerState(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_Item(), CG_ItemPickup(), CG_KeyEvent(), CG_keyOff_f(), CG_keyOn_f(), CG_KickAngles(), CG_LastWeaponUsed_f(), CG_LaunchGib(), CG_Letterbox(), CG_LimboMenu_f(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_ClassCount(), CG_LimboPanel_ClassIsDisabled(), CG_LimboPanel_Draw(), CG_LimboPanel_GetRealTeam(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_RealWeaponIsDisabled(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderMedal(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamCount(), CG_LimboPanel_TeamIsDisabled(), CG_LimboPanel_TeamIsFull(), CG_LimboPanel_WeaponCount(), CG_LimboPanel_WeaponPanel(), CG_ListSpawnPoints_f(), CG_LoadingString(), CG_LoadPanel_LoadingBarText(), CG_LoadPanel_RenderCampaignPins(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_MakeExplosion(), CG_MapRestart(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_Draw(), CG_MapVote_VoteButton_KeyDown(), CG_MapVoteList_Draw(), CG_MapVoteList_KeyDown(), CG_MessageMode_f(), CG_MG42EFX(), CG_Missile(), CG_MissileHitWall(), CG_ModifySpeaker_f(), CG_MortarEFX(), CG_MortarImpact(), CG_MortarMiss(), CG_MouseEvent(), CG_MoveFlameChunk(), CG_MovePlane(), CG_Mover(), CG_Mover_PostProcess(), CG_NewClientInfo(), CG_NextWeap(), CG_NextWeapon_f(), CG_Obituary(), CG_ObjectivePrint(), CG_objectivesDown_f(), CG_ObjectivesDraw(), CG_objectivesUp_f(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_OilSlickRemove(), CG_OutOfAmmoChange(), CG_PainEvent(), CG_PanzerFaustEjectBrass(), CG_ParseEntitiesFromString(), CG_ParseFireteams(), CG_ParseMapEntity(), CG_ParseScore(), CG_ParseScreenFade(), CG_ParseSkyBox(), CG_ParseSpawns(), CG_ParseSpawnVars(), CG_ParseWarmup(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBloodCloud(), CG_ParticleBubble(), CG_ParticleBulletDebris(), CG_ParticleCheckVisible(), CG_ParticleDirtBulletDebris_Core(), CG_ParticleDust(), CG_ParticleExplosion(), CG_ParticleGenerate(), CG_ParticleImpactSmokePuff(), CG_ParticleImpactSmokePuffExtended(), CG_ParticleRender(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), CG_ParticleSparks(), CG_PlayBufferedVoiceChats(), CG_Player(), CG_PlayerAmmoValue(), CG_PlayerAngles(), CG_PlayerFloatSprite(), CG_PlayerNFFromPos(), CG_PlayerSFFromPos(), CG_PlayerShadow(), CG_PlayerSprites(), CG_PlayGlobalSound(), CG_PlayPMItemSound(), CG_PlayVoiceChat(), CG_PMItemBigSound(), CG_PredictLean(), CG_PredictPlayerState(), CG_PrevWeap(), CG_PrevWeapon_f(), CG_printWindow(), CG_PriorityCenterPrint(), CG_ProcessCvars(), CG_ProcessEntity(), CG_ProcessSnapshots(), CG_Prop(), CG_PyroSmokeTrail(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickFireteams_f(), CG_QuickSpawnpoint_f(), CG_RailTrail2(), CG_ReadHuds_f(), CG_ReadNextSnapshot(), CG_ReflectVelocity(), CG_removeStrings(), CG_RenderLocations(), CG_RenderScriptSpeakers(), CG_RenderSmokeGrenadeSmoke(), CG_ResetEntity(), CG_ResetPlayerEntity(), CG_Respawn(), CG_RocketTrail(), CG_RubbleFx(), CG_RumbleEfx(), CG_RunHudHeadLerpFrame(), CG_RunLerpFrame(), CG_RunLerpFrameRate(), CG_RunLerpFrameRateCorpse(), CG_RunWeapLerpFrame(), CG_SayPlayerClass_f(), CG_ScanForCrosshairDyna(), CG_ScanForCrosshairEntity(), CG_ScanForCrosshairMine(), CG_ScoresDown_f(), CG_ScoresUp_f(), CG_ScreenFade(), CG_SelectBuddy_f(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetInitialSnapshot(), CG_SetLerpFrameAnimationRate(), CG_SetLerpFrameAnimationRateCorpse(), CG_SetNextSnap(), CG_SetupFrustum(), CG_SetViewanglesForSpeakerEditor(), CG_SetWeaponCrosshair_f(), CG_ShakeCamera(), CG_Shard(), CG_ShardJunk(), CG_ShowHelp_Off(), CG_ShowHelp_On(), CG_Smoker(), CG_SortedFireTeamPlayerForPosition(), CG_SortFireTeam(), CG_SoundPickOldestRandomSound(), CG_SparklerSparks(), CG_Spawnpoints_MenuText_Draw(), CG_SpawnpointsCheckExecKey(), CG_SpawnString(), CG_SpawnTracer(), CG_Speaker(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditorDraw(), CG_SpeakerEditorMouseMove_Handling(), CG_StartShakeCamera(), CG_StartWeaponAnim(), CG_StatsDebugAddText(), CG_StatsDown_f(), CG_StatsUp_f(), CG_StepOffset(), CG_SwingAngles(), CG_TeamRestrictionsChanged(), CG_TeamVoiceChat_f(), CG_TestGun_f(), CG_TestModel_f(), CG_TestModelNextFrame_f(), CG_TestModelNextSkin_f(), CG_TestModelPrevFrame_f(), CG_TestModelPrevSkin_f(), CG_TileClear(), CG_TimerReset_f(), CG_TimerSet_f(), CG_topshotsDown_f(), CG_TopShotsDraw(), CG_topshotsUp_f(), CG_TouchTriggerPrediction(), CG_TransformAutomapEntity(), CG_TransformToCommandMapCoord(), CG_TransitionEntity(), CG_TransitionPlayerState(), CG_TransitionSnapshot(), CG_Trap(), CG_UnderwaterSounds(), CG_UndoSpeaker_f(), CG_UpdateBufferedSoundScripts(), CG_UpdateFlamethrowerSounds(), CG_UpdatePMLists(), CG_UpdateSvCvars(), CG_Viewpos_f(), CG_VoiceChatLocal(), CG_WaterRipple(), CG_WeaponAnimation(), CG_WeaponBank_f(), CG_WeaponFireRecoil(), CG_WeaponHasAmmo(), CG_WeaponSelectable(), CG_windowAlloc(), CG_windowCleanup(), CG_windowDraw(), CG_windowFree(), CG_windowInit(), CG_WorldCoordToScreenCoordFloat(), CG_wstatsParse_cmd(), CG_Zoom(), CG_ZoomIn_f(), CG_ZoomOut_f(), CG_ZoomRequired(), CG_ZoomSway(), PmoveSingle(), SP_misc_gamemodel(), SP_trigger_objective_info(), SP_worldspawn(), trap_GetCurrentSnapshotNumber(), trap_S_StartSound(), trap_S_StartSoundEx(), trap_S_StartSoundVControl(), vmMain(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
vmCvar_t cg_altHud
Definition at line 315 of file cg_main.c.
Referenced by CG_DrawAutoMap(), CG_DrawNewCompass(), CG_DrawUpperRight(), and CG_SetHud().
vmCvar_t cg_altHudFlags
Definition at line 316 of file cg_main.c.
Referenced by CG_DrawGlobalHud(), CG_DrawPlayerStats(), and CG_DrawUpperRight().
vmCvar_t cg_animSpeed
Definition at line 151 of file cg_main.c.
Referenced by CG_RunLerpFrame(), CG_RunLerpFrameRate(), and CG_RunWeapLerpFrame().
vmCvar_t cg_announcer
Definition at line 304 of file cg_main.c.
Referenced by CG_DrawWarmup(), and CG_ParseWolfinfo().
vmCvar_t cg_antilag
Definition at line 222 of file cg_main.c.
Referenced by CG_ParseServerinfo().
vmCvar_t cg_atmosphericEffects
Definition at line 284 of file cg_main.c.
Referenced by CG_AddAtmosphericEffects().
vmCvar_t cg_autoAction
Definition at line 231 of file cg_main.c.
Referenced by CG_DrawActiveFrame(), CG_DrawIntermission(), and CG_DrawWarmup().
vmCvar_t cg_autoactivate
Definition at line 195 of file cg_main.c.
vmCvar_t cg_automapZoom
Definition at line 324 of file cg_main.c.
Referenced by CG_AdjustAutomapZoom(), CG_DrawAutoMap(), and CG_TransformAutomapEntity().
vmCvar_t cg_autoReload
Definition at line 232 of file cg_main.c.
Referenced by CG_MapRestart(), and CG_Respawn().
vmCvar_t cg_autoswitch
Definition at line 174 of file cg_main.c.
Referenced by CG_ItemPickup().
vmCvar_t cg_blood
Definition at line 192 of file cg_main.c.
Referenced by CG_Bleed(), CG_BloodTrail(), CG_Bullet(), CG_GibPlayer(), and CG_LaunchGib().
vmCvar_t cg_bloodDamageBlend
Definition at line 233 of file cg_main.c.
Referenced by CG_DamageBlendBlob().
vmCvar_t cg_bloodFlash
Definition at line 234 of file cg_main.c.
Referenced by CG_DrawFlashDamage().
vmCvar_t cg_bloodTime
Definition at line 204 of file cg_main.c.
Referenced by CG_Bullet(), CG_FragmentBounceMark(), and CG_GibPlayer().
vmCvar_t cg_bluelimbotime
Definition at line 220 of file cg_main.c.
Referenced by CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_DrawFollow(), CG_DrawMapEntity(), and CG_ParseServerinfo().
vmCvar_t cg_bobpitch
Definition at line 126 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_bobroll
Definition at line 127 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_bobup
Definition at line 125 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_brassTime
Definition at line 162 of file cg_main.c.
Referenced by CG_FireWeapon(), CG_MachineGunEjectBrass(), and CG_PanzerFaustEjectBrass().
vmCvar_t cg_buildScript
Definition at line 188 of file cg_main.c.
Referenced by CG_ParseVoiceChats(), and CG_ServerCommand().
vmCvar_t cg_centertime
Definition at line 124 of file cg_main.c.
Referenced by CG_DrawCenterString().
vmCvar_t cg_complaintPopUp
Definition at line 235 of file cg_main.c.
Referenced by CG_DrawVote(), and CG_ServerCommand().
vmCvar_t cg_coronafardist
Definition at line 189 of file cg_main.c.
Referenced by CG_Corona(), and CG_Coronas().
vmCvar_t cg_coronas
Definition at line 190 of file cg_main.c.
Referenced by CG_Corona(), and CG_Coronas().
vmCvar_t cg_countryflags
GeoIP.
Definition at line 313 of file cg_main.c.
Referenced by WM_DrawClientScore(), and WM_DrawClientScore_Small().
vmCvar_t cg_crosshairAlpha
Definition at line 236 of file cg_main.c.
vmCvar_t cg_crosshairAlphaAlt
Definition at line 237 of file cg_main.c.
vmCvar_t cg_crosshairColor
Definition at line 238 of file cg_main.c.
vmCvar_t cg_crosshairColorAlt
Definition at line 239 of file cg_main.c.
vmCvar_t cg_crosshairHealth
Definition at line 146 of file cg_main.c.
Referenced by CG_DrawCrosshair().
vmCvar_t cg_crosshairPulse
Definition at line 240 of file cg_main.c.
Referenced by CG_DrawCrosshair().
vmCvar_t cg_crosshairSize
Definition at line 143 of file cg_main.c.
Referenced by CG_DrawCrosshair(), and CG_SpeakerEditorDraw().
vmCvar_t cg_crosshairX
Definition at line 144 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawNoShootIcon(), and CG_SpeakerEditorDraw().
vmCvar_t cg_crosshairY
Definition at line 145 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawNoShootIcon(), and CG_SpeakerEditorDraw().
vmCvar_t cg_cursorHints
Definition at line 165 of file cg_main.c.
Referenced by CG_DrawCursorhint().
vmCvar_t cg_cycleAllWeaps
Definition at line 141 of file cg_main.c.
Referenced by CG_NextWeap(), and CG_PrevWeap().
vmCvar_t cg_debugAnim
Definition at line 154 of file cg_main.c.
Referenced by CG_RunLerpFrame(), CG_RunLerpFrameRate(), CG_RunLerpFrameRateCorpse(), CG_RunWeapLerpFrame(), CG_SetLerpFrameAnimation(), CG_SetLerpFrameAnimationRate(), CG_SetLerpFrameAnimationRateCorpse(), CG_SetWeapLerpFrameAnimation(), and CG_WeaponAnimation().
vmCvar_t cg_debugEvents
Definition at line 156 of file cg_main.c.
Referenced by CG_EntityEvent().
vmCvar_t cg_debugPlayerHitboxes
Definition at line 341 of file cg_main.c.
Referenced by CG_Player().
vmCvar_t cg_debugPosition
Definition at line 155 of file cg_main.c.
Referenced by CG_ResetPlayerEntity().
vmCvar_t cg_debugSkills
Definition at line 290 of file cg_main.c.
Referenced by CG_DrawStatsDebug(), and CG_StatsDebugAddText().
vmCvar_t cg_descriptiveText
Definition at line 217 of file cg_main.c.
Referenced by CG_DrawLimboMessage(), CG_DrawScoreboard(), and CG_DrawSpectatorMessage().
vmCvar_t cg_draw2D
Definition at line 131 of file cg_main.c.
Referenced by CG_Draw2D(), and CG_DrawFlashFade().
vmCvar_t cg_drawCompass
Definition at line 214 of file cg_main.c.
Referenced by CG_DrawAutoMap(), and CG_DrawNewCompass().
vmCvar_t cg_drawCrosshair
Definition at line 136 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawCrosshairNames(), and CG_SpeakerEditorDraw().
vmCvar_t cg_drawCrosshairInfo
Definition at line 137 of file cg_main.c.
Referenced by CG_DrawCrosshairNames().
vmCvar_t cg_drawCrosshairNames
Definition at line 138 of file cg_main.c.
Referenced by CG_DrawCrosshairNames(), and CG_PlayerSprites().
vmCvar_t cg_drawCrosshairPickups
Definition at line 139 of file cg_main.c.
Referenced by CG_Item().
vmCvar_t cg_drawFireteamOverlay
Definition at line 291 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawFPS
Definition at line 132 of file cg_main.c.
Referenced by CG_DrawFPS(), and CG_DrawUpperRight().
vmCvar_t cg_drawGun
Definition at line 164 of file cg_main.c.
Referenced by CG_AddViewWeapon(), and CG_CalcMuzzlePoint().
vmCvar_t cg_drawNotifyText
Definition at line 215 of file cg_main.c.
vmCvar_t cg_drawPing
Definition at line 133 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawReinforcementTime
Definition at line 241 of file cg_main.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
vmCvar_t cg_drawRoundTimer
Definition at line 286 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawSmallPopupIcons
Definition at line 292 of file cg_main.c.
Referenced by CG_DrawPMItems(), and CG_GetObituaryIcon().
vmCvar_t cg_drawSnapshot
Definition at line 135 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawspeed
Definition at line 350 of file cg_main.c.
Referenced by CG_DrawSpeed(), and CG_DrawUpperRight().
vmCvar_t cg_drawSpreadScale
Definition at line 152 of file cg_main.c.
Referenced by CG_DrawWeapStability().
vmCvar_t cg_drawStatus
Definition at line 150 of file cg_main.c.
Referenced by CG_Draw2D().
vmCvar_t cg_drawTime
Definition at line 326 of file cg_main.c.
Referenced by CG_DrawLocalTime(), CG_DrawTimersAlt(), and CG_DrawUpperRight().
vmCvar_t cg_drawWeaponIconFlash
Definition at line 242 of file cg_main.c.
Referenced by CG_DrawGunIcon().
centity_t cg_entities[MAX_GENTITIES]
Definition at line 121 of file cg_main.c.
Referenced by CG_AddEntityToTag(), CG_AddFlameToScene(), CG_AddLinkedEntity(), CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AdjustPositionForMover(), CG_AttachBitsToTank(), CG_BuildSolidList(), CG_Bullet(), CG_CalcMuzzlePoint(), CG_CalcViewValues(), CG_CalcVrect(), CG_CheckForCursorHints(), CG_CheckPlayerstateEvents(), CG_DisguiseMapCheck(), CG_DrawCrosshairNames(), CG_DrawFireTeamOverlay(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawNewCompass(), CG_DrawPowerUps(), CG_EntityEffects(), CG_EntityEvent(), CG_GetBleedOrigin(), CG_GetTag(), CG_GetWeaponTag(), CG_LoadClientInfo(), CG_MachineGunEjectBrass(), CG_MG42EFX(), CG_Mover_PostProcess(), CG_ParseTagConnect(), CG_Player(), CG_PlayerAmmoValue(), CG_PlayerAngles(), CG_PlayVoiceChat(), CG_PredictPlayerState(), CG_ScanForCrosshairEntity(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_SpawnTracer(), CG_TransitionPlayerState(), CG_TransitionSnapshot(), CG_ZoomIn_f(), and CG_ZoomOut_f().
vmCvar_t cg_errorDecay
Definition at line 157 of file cg_main.c.
Referenced by CG_CalcViewValues(), and CG_PredictPlayerState().
vmCvar_t cg_fireteamLatchedClass
Definition at line 318 of file cg_main.c.
Referenced by CG_DrawFireTeamOverlay().
vmCvar_t cg_fontScaleCN
Definition at line 337 of file cg_main.c.
Referenced by CG_DrawCrosshairNames().
vmCvar_t cg_fontScaleCP
Definition at line 336 of file cg_main.c.
Referenced by CG_Class_f(), CG_demoAviFPSDraw(), CG_DrawWarmup(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_SendSetupMsg(), CG_NewClientInfo(), CG_Obituary(), CG_ServerCommand(), CG_SpawnpointsCheckExecKey(), and CG_TouchTriggerPrediction().
vmCvar_t cg_fontScaleSP
Definition at line 335 of file cg_main.c.
Referenced by CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawScoreboard(), CG_DrawSpectatorMessage(), CG_DrawVote(), CG_removeStrings(), CG_windowDraw(), and CG_windowNormalizeOnText().
vmCvar_t cg_fontScaleTP
Definition at line 334 of file cg_main.c.
Referenced by CG_DrawDisconnect(), CG_DrawLagometer(), CG_DrawSpectator(), CG_DrawWarmup(), and CG_ServerCommand().
vmCvar_t cg_fov
Definition at line 175 of file cg_main.c.
Referenced by CG_AddViewWeapon(), CG_CalcFov(), and CG_DrawSkyBoxPortal().
vmCvar_t cg_gameType
Definition at line 203 of file cg_main.c.
Referenced by CG_Debriefing_FindWinningTeam(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Maps_KeyDown(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_DebriefingTitle_Draw(), CG_DrawLivesLeft(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_RenderCounter_NumRollers(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanelRenderText_NoLMS(), CG_LimboPanelRenderText_SkillsText(), CG_ParseServerinfo(), CG_TeamDebriefing_CalcXP(), WM_DrawClientScore(), WM_DrawClientScore_Small(), and WM_TeamScoreboard().
vmCvar_t cg_gibs
Definition at line 130 of file cg_main.c.
Referenced by CG_LaunchGib().
vmCvar_t cg_graphicObituaries
Definition at line 332 of file cg_main.c.
Referenced by CG_Obituary().
vmCvar_t cg_gun_frame
Definition at line 166 of file cg_main.c.
Referenced by CG_AddViewWeapon().
vmCvar_t cg_gun_x
Definition at line 167 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_gun_y
Definition at line 168 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_gun_z
Definition at line 169 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_hitSounds
Definition at line 305 of file cg_main.c.
Referenced by CG_CheckLocalSounds().
vmCvar_t cg_instanttapout
Definition at line 288 of file cg_main.c.
Referenced by CG_ServerCommand().
vmCvar_t cg_lagometer
Definition at line 134 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_letterbox
Definition at line 163 of file cg_main.c.
Referenced by CG_Letterbox().
vmCvar_t cg_locations
Definition at line 306 of file cg_main.c.
Referenced by CG_BuildLocationString(), CG_DrawActiveFrame(), CG_DrawFireTeamOverlay(), and CG_GetPMItemText().
vmCvar_t cg_logFile
Definition at line 311 of file cg_main.c.
vmCvar_t cg_markTime
Definition at line 161 of file cg_main.c.
Referenced by CG_AddMarks(), CG_BigExplosionImpact(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_Effect(), CG_MapMortarImpact(), CG_MeleeImpact(), CG_MissileHitWallSmall(), and CG_SmallExplosionImpact().
vmCvar_t cg_messageType
Definition at line 208 of file cg_main.c.
vmCvar_t cg_muzzleFlash
Definition at line 176 of file cg_main.c.
Referenced by CG_FireWeapon().
vmCvar_t cg_noAmmoAutoSwitch
Definition at line 243 of file cg_main.c.
Referenced by CG_EntityEvent().
vmCvar_t cg_noPlayerAnims
Definition at line 159 of file cg_main.c.
Referenced by CG_PlayerAnimation(), and CG_WeaponAnimation().
vmCvar_t cg_nopredict
Definition at line 158 of file cg_main.c.
Referenced by CG_DrawLagometer(), CG_EntityEvent(), CG_PredictPlayerState(), and CG_TransitionSnapshot().
vmCvar_t cg_optimizePrediction
Definition at line 340 of file cg_main.c.
Referenced by CG_PredictPlayerState().
vmCvar_t cg_paused
Definition at line 191 of file cg_main.c.
Referenced by CG_Draw2D(), CG_DrawScoreboard(), and CG_SpawnTrailJunc().
vmCvar_t cg_popupBigFilter
Definition at line 331 of file cg_main.c.
Referenced by CG_NewClientInfo().
vmCvar_t cg_popupFadeTime
Definition at line 328 of file cg_main.c.
Referenced by CG_DrawPMItems(), CG_DrawPMItemsBig(), and CG_UpdatePMLists().
vmCvar_t cg_popupFilter
Definition at line 330 of file cg_main.c.
Referenced by CG_CheckPMItemFilter().
vmCvar_t cg_popupStayTime
Definition at line 329 of file cg_main.c.
Referenced by CG_DrawPMItems(), CG_DrawPMItemsBig(), and CG_UpdatePMLists().
vmCvar_t cg_predictItems
Definition at line 193 of file cg_main.c.
vmCvar_t cg_printObjectiveInfo
Definition at line 244 of file cg_main.c.
Referenced by CG_ServerCommand().
vmCvar_t cg_quickchat
Definition at line 348 of file cg_main.c.
Referenced by CG_AltWeapon_f().
vmCvar_t cg_quickMessageAlt
Definition at line 216 of file cg_main.c.
Referenced by CG_ClassMenu_f(), CG_DrawFireteamsByTeam(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), CG_QuickFireteamMessage_f(), CG_QuickMessage_f(), and CG_TeamMenu_f().
vmCvar_t cg_railTrailTime
Definition at line 153 of file cg_main.c.
Referenced by CG_RailTrail2().
vmCvar_t cg_rconPassword
Definition at line 282 of file cg_main.c.
vmCvar_t cg_recording_statusline
Definition at line 302 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t cg_redlimbotime
Definition at line 219 of file cg_main.c.
Referenced by CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_DrawFollow(), CG_DrawMapEntity(), and CG_ParseServerinfo().
vmCvar_t cg_refereePassword
Definition at line 283 of file cg_main.c.
vmCvar_t cg_shadows
Definition at line 129 of file cg_main.c.
Referenced by CG_Player(), CG_PlayerShadow(), CG_PlayerSplash(), and Script_ConditionalScript().
vmCvar_t cg_showmiss
Definition at line 160 of file cg_main.c.
Referenced by CG_MapRestart(), CG_PredictionOk(), and CG_PredictPlayerState().
vmCvar_t cg_simpleItems
Definition at line 322 of file cg_main.c.
Referenced by CG_Item().
vmCvar_t cg_skybox
Definition at line 205 of file cg_main.c.
Referenced by CG_DrawSkyBoxPortal().
vmCvar_t cg_spawnTimer_period
Definition at line 309 of file cg_main.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
vmCvar_t cg_spawnTimer_set
Definition at line 308 of file cg_main.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
vmCvar_t cg_stats
Definition at line 187 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_swingSpeed
Definition at line 128 of file cg_main.c.
Referenced by CG_PlayerAngles().
vmCvar_t cg_teamChatHeight
Definition at line 186 of file cg_main.c.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
vmCvar_t cg_teamChatsOnly
Definition at line 147 of file cg_main.c.
Referenced by CG_ServerCommand(), and CG_VoiceChatLocal().
vmCvar_t cg_teamChatTime
Definition at line 185 of file cg_main.c.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
vmCvar_t cg_thirdPerson
Definition at line 179 of file cg_main.c.
Referenced by CG_DemoClick(), CG_DrawActiveFrame(), CG_FireFlameChunks(), and CG_OffsetThirdPersonView().
vmCvar_t cg_thirdPersonAngle
Definition at line 181 of file cg_main.c.
Referenced by CG_DemoClick(), and CG_OffsetThirdPersonView().
vmCvar_t cg_thirdPersonRange
Definition at line 180 of file cg_main.c.
Referenced by CG_DemoClick(), and CG_OffsetThirdPersonView().
vmCvar_t cg_timescale
Definition at line 210 of file cg_main.c.
Referenced by CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawActiveFrame(), and CG_DrawDisconnect().
vmCvar_t cg_tracerChance
Definition at line 170 of file cg_main.c.
Referenced by CG_Bullet().
vmCvar_t cg_tracerLength
Definition at line 172 of file cg_main.c.
Referenced by CG_AddMovingTracer(), CG_SpawnTracer(), and CG_Tracer().
vmCvar_t cg_tracers
Definition at line 317 of file cg_main.c.
Referenced by CG_Bullet(), and CG_DrawBulletTracer().
vmCvar_t cg_tracerSpeed
Definition at line 173 of file cg_main.c.
Referenced by CG_SpawnTracer().
vmCvar_t cg_tracerWidth
Definition at line 171 of file cg_main.c.
Referenced by CG_DrawTracer().
vmCvar_t cg_uinfo
Definition at line 248 of file cg_main.c.
vmCvar_t cg_useWeapsForZoom
Definition at line 142 of file cg_main.c.
Referenced by CG_ZoomRequired().
vmCvar_t cg_visualEffects
turn invisible (0) / visible (1) visual effect (i.e airstrike plane, debris ...)
Definition at line 352 of file cg_main.c.
Referenced by CG_AddDebris(), CG_AddLocalEntities(), and CG_MovePlane().
vmCvar_t cg_voiceChats
Definition at line 148 of file cg_main.c.
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_voiceSpriteTime
Definition at line 212 of file cg_main.c.
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_voiceText
Definition at line 149 of file cg_main.c.
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_weapaltReloads
Definition at line 320 of file cg_main.c.
Referenced by CG_AltWeapon_f().
vmCvar_t cg_weaponCycleDelay
Definition at line 140 of file cg_main.c.
Referenced by CG_AltWeapon_f(), and CG_CheckCanSwitch().
weaponInfo_t cg_weapons[MAX_WEAPONS]
Definition at line 122 of file cg_main.c.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_CalculateWeaponPosition(), CG_DrawFireTeamOverlay(), CG_DrawPlayerWeaponIcon(), CG_EntityEvent(), CG_FireWeapon(), CG_GetObituaryIcon(), CG_Item(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_MachineGunEjectBrass(), CG_Missile(), CG_MissileHitWall(), CG_PanzerFaustEjectBrass(), CG_Player(), CG_RegisterWeapon(), and CG_WeaponFireRecoil().
vmCvar_t cg_wolfparticles
Definition at line 201 of file cg_main.c.
Referenced by CG_AddParticleToScene().
vmCvar_t cg_zoomDefaultSniper
Definition at line 178 of file cg_main.c.
Referenced by CG_Zoom().
vmCvar_t cg_zoomStepSniper
Definition at line 177 of file cg_main.c.
Referenced by CG_ZoomIn_f(), and CG_ZoomOut_f().
displayContextDef_t cgDC
Definition at line 38 of file cg_main.c.
Referenced by CG_CommandCentreSpawnPointClick(), CG_Debriefing_Draw(), CG_DemoControlButtonDown(), CG_Draw2D(), CG_DrawActiveFrame(), CG_DrawDemoControls(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), CG_LimboPanel_Draw(), CG_LimboPanel_KeyHandling(), CG_ProcessSnapshots(), CG_SpeakerEditorDraw(), CG_Text_Height(), CG_Text_Paint(), CG_Text_PaintWithCursor(), CG_Text_PaintWithCursor_Ext(), CG_Text_Width(), and CG_windowDraw().
cgs_t cgs
Definition at line 120 of file cg_main.c.
Referenced by Ccg_Is43Screen(), Ccg_WideX(), Ccg_WideXoffset(), CG_AddBloodElements(), CG_AddDebris(), CG_AddDebrisElements(), CG_AddEmitter(), CG_AddFlameToScene(), CG_AddFragment(), CG_AddFuseSparkElements(), CG_AddLagometerSnapshotInfo(), CG_AddLineToScene(), CG_AddOnScreenText(), CG_AddPlayerWeapon(), CG_AddPMItemBig(), CG_AddRefEntityWithPowerups(), CG_AddSmokeSprites(), CG_AddSparks(), CG_AddToNotify(), CG_AddToTeamChat(), CG_AddTrailToScene(), CG_AddViewWeapon(), CG_AdjustFrom640(), CG_AttachBitsToTank(), CG_AutomapExpandDown_f(), CG_AutomapExpandUp_f(), CG_AutomapZoomIn_f(), CG_AutomapZoomOut_f(), CG_Beam(), CG_Beam_2(), CG_BigExplosionImpact(), CG_BloodTrail(), CG_BreathPuffs(), CG_BubbleTrail(), CG_BuddyVoiceChat_f(), CG_BuildLocationString(), CG_BuildSelectedFirteamString(), CG_Bullet(), CG_BulletImpact(), CG_CalcFov(), CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_CalcViewValues(), CG_CalcVrect(), CG_CharacterForClientinfo(), CG_CharacterForPlayerstate(), CG_ChatPanel_Setup(), CG_CheckForExistingAnimModelInfo(), CG_CheckLocalSounds(), CG_Class_f(), CG_ClassMenu_f(), CG_ClientInfoForPosition(), CG_CommandCentreSpawnPointClick(), CG_CommandMap_DrawHighlightText(), CG_CompasMoveLocationCalc(), CG_ConfigStringModified(), CG_Constructible(), CG_corona(), CG_Coronas(), CG_CountFireteamsByTeam(), CG_CountPlayersNF(), CG_CountPlayersSF(), CG_CPM_f(), CG_CurLayerForZ(), CG_DamageBlendBlob(), CG_Debriefing_Awards_Draw(), CG_Debriefing_CalcCampaignProgress(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatButton_Draw(), CG_Debriefing_ChatButton_KeyDown(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_Draw(), CG_Debriefing_FindWinningTeam(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_GetNextWeaponStat(), CG_Debriefing_GetSelectedClientInfo(), CG_Debriefing_InfoRequests(), CG_Debriefing_KeyEvent(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Maps_KeyDown(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_MouseEvent(), CG_Debriefing_NextButton_KeyDown(), CG_Debriefing_ParseAwards(), CG_Debriefing_ParsePlayerKillsDeaths(), CG_Debriefing_ParsePlayerTime(), CG_Debriefing_ParseWeaponAccuracies(), CG_Debriefing_ParseWeaponStats(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_ReadyButton_Draw(), CG_Debriefing_Scrollbar_KeyDown(), CG_Debriefing_ScrollGetCount(), CG_Debriefing_ScrollGetOffset(), CG_Debriefing_ScrollSetOffset(), CG_Debriefing_Shutdown(), CG_Debriefing_Startup(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_Debriefing_VoteButton_Draw(), CG_Debriefing_VoteButton_KeyDown(), CG_DebriefingPlayerList_Draw(), CG_DebriefingPlayerList_KeyDown(), CG_DebriefingPlayerWeaponStats_Draw(), CG_DebriefingTitle_Draw(), CG_DebriefingXPHeader_Draw(), CG_Debrieing_SetSelectedClient(), CG_Debris(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DescriptionForCampaign(), CG_DisguiseMapCheck(), CG_Draw2D(), CG_DrawActiveFrame(), CG_DrawAmmoCount(), CG_DrawAutoMap(), CG_DrawBinocReticle(), CG_DrawBorder(), CG_DrawBottom_NoScale(), CG_DrawBreathBar(), CG_DrawCenterString(), CG_DrawConnectScreen(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawDemoRecording(), CG_DrawDisconnect(), CG_DrawExpandedAutoMap(), CG_DrawField(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlag(), CG_DrawFlashBlend(), CG_DrawFlashFade(), CG_DrawFlashFire(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawGlobalHud(), CG_DrawGrid(), CG_DrawGunIcon(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawLagometer(), CG_DrawLandmine(), CG_DrawLimboMessage(), CG_DrawLivesLeft(), CG_DrawLocalTime(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMiscGamemodels(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNewCompass(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), CG_DrawOnScreenLabels(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPlayerHealthBar(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawPlayerStats(), CG_DrawPlayerStatusHead(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScopedReticle(), CG_DrawScoreboard(), CG_DrawSides(), CG_DrawSides_NoScale(), CG_DrawSkillBar(), CG_DrawSkills(), CG_DrawSkyBoxPortal(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawStaminaBar(), CG_DrawStatsDebug(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawTopBottom(), CG_DrawTopBottom_NoScale(), CG_DrawTracer(), CG_DrawUpperRight(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeapRecharge(), CG_DrawXP(), CG_dumpStats(), CG_dumpStats_f(), CG_DynamiteExplosionImpact(), CG_EditSpeakers_f(), CG_Effect(), CG_EffectParse(), CG_EntityEffects(), CG_EntityEvent(), CG_EventHandling(), CG_ExecuteNewServerCommands(), CG_Explode(), CG_Explodef(), CG_Explosive(), CG_Fade(), CG_FillRect(), CG_FireteamCheckExecKey(), CG_FireTeamForPosition(), CG_FireteamHasClass(), CG_FireTeamPlayerForPosition(), CG_Fireteams_MenuText_Draw(), CG_Fireteams_MenuTitleText_Draw(), CG_FireWeapon(), CG_FragmentBounceMark(), CG_FragmentBounceSound(), CG_FTSayPlayerClass_f(), CG_GameStatsDraw(), CG_General(), CG_GetBleedOrigin(), CG_GetLocation(), CG_GetLocationMsg(), CG_GetObituaryIcon(), CG_GetPMItemIcon(), CG_GetPMItemText(), CG_GetSecondaryWeapon(), CG_GetTag(), CG_GetWeaponTag(), CG_GibPlayer(), CG_GrenadeTrail(), CG_InitConsoleCommands(), CG_InitPMGraphics(), CG_IsOnFireteam(), CG_IsWeaponDisabled(), CG_Item(), CG_ItemPickup(), CG_KeyEvent(), CG_Letterbox(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_ClassCount(), CG_LimboPanel_ClassIsDisabled(), CG_LimboPanel_Draw(), CG_LimboPanel_Filter_Draw(), CG_LimboPanel_Filter_KeyDown(), CG_LimboPanel_GetClass(), CG_LimboPanel_GetRealTeam(), CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_GetSpawnPoint(), CG_LimboPanel_GetTeam(), CG_LimboPanel_Init(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_MinusButton_KeyDown(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_PlusButton_KeyDown(), CG_LimboPanel_RealWeaponIsDisabled(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCommandMap(), CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderCounter_GetShaders(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderLight(), CG_LimboPanel_RenderMedal(), CG_LimboPanel_RenderObjectiveBack(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_RequestWeaponStats(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_SetSelectedWeaponNum(), CG_LimboPanel_Setup(), CG_LimboPanel_SpawnPointButton_Draw(), CG_LimboPanel_SpawnPointButton_KeyDown(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_TeamCount(), CG_LimboPanel_TeamIsDisabled(), CG_LimboPanel_TeamIsFull(), CG_LimboPanel_WeaponCount(), CG_LimboPanel_WeaponLights(), CG_LimboPanel_WeaponLights_KeyDown(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LimboPanel_WeaponPanel_KeyUp(), CG_LoadLocations(), CG_LoadPanel_DrawPin(), CG_LoadPanel_RenderCampaignNameText(), CG_LoadPanel_RenderCampaignPins(), CG_LoadPanel_RenderCampaignTypeText(), CG_LoadPanel_RenderMissionDescriptionText(), CG_LocateArena(), CG_LocateCampaign(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_MapMortarImpact(), CG_MapRestart(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_Draw(), CG_MapVote_VoteButton_KeyDown(), CG_MapVoteList_Draw(), CG_MapVoteList_KeyDown(), CG_MessageMode_f(), CG_MG42EFX(), CG_Missile(), CG_MissileHitWall(), CG_MissileHitWallSmall(), CG_MortarEFX(), CG_MouseEvent(), CG_MovePlane(), CG_Mover(), CG_NameForCampaign(), CG_NewClientInfo(), CG_NewParticleArea(), CG_Obituary(), CG_ObjectivePrint(), CG_objectivesDown_f(), CG_ObjectivesDraw(), CG_objectivesUp_f(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_PanzerFaustEjectBrass(), CG_ParseAnimationFiles(), CG_parseBestShotsStats_cmd(), CG_ParseFireteams(), CG_ParseLegacyinfo(), CG_ParseMapEntity(), CG_parseMapVoteListInfo(), CG_parseMapVoteTally(), CG_ParseOIDInfo(), CG_ParsePortalPos(), CG_ParseReinforcementTimes(), CG_ParseScore(), CG_ParseScreenFade(), CG_ParseServerinfo(), CG_ParseServerVersionInfo(), CG_ParseSpawns(), CG_ParseSysteminfo(), CG_ParseTeamInfo(), CG_ParseTeamXPs(), CG_parseTopShotsStats_cmd(), CG_ParseWarmup(), CG_ParseWeaponStats(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_ParseWolfinfo(), CG_ParticleBloodCloud(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleSmoke(), CG_ParticleSparks(), CG_Player(), CG_PlayerAmmoValue(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PlayerCanPickupWeapon(), CG_PlayerNFFromPos(), CG_PlayerSFFromPos(), CG_PlayerShadow(), CG_PlayerSplash(), CG_PlayerSprites(), CG_PlayGlobalSound(), CG_PlayPMItemSound(), CG_PlayVoiceChat(), CG_PMItemBigSound(), CG_PredictPlayerState(), CG_printFile(), CG_PrintObjectiveInfo_f(), CG_PriorityCenterPrint(), CG_ProcessEntity(), CG_ProcessSnapshots(), CG_Prop(), CG_PyroSmokeTrail(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickFireteams_f(), CG_QuickSpawnpoint_f(), CG_RailTrail2(), CG_RandomDebris(), CG_ReadHuds_f(), CG_ReadNextSnapshot(), CG_removeStrings(), CG_RenderLocations(), CG_RenderScriptSpeakers(), CG_ResetPlayerEntity(), CG_Respawn(), CG_Rubble(), CG_RubbleFx(), CG_SaveSpeakersToScript(), CG_SayPlayerClass_f(), CG_ScanForCrosshairEntity(), CG_scores_cmd(), CG_ScoresDown_f(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetEntitySoundPosition(), CG_SetInitialSnapshot(), CG_SetLerpFrameAnimationRateCorpse(), CG_ShaderStateChanged(), CG_Shard(), CG_ShardJunk(), CG_SmallExplosionImpact(), CG_Smoker(), CG_SortedFireTeamPlayerForPosition(), CG_SortFireTeam(), CG_SortPlayersByXP(), CG_SoundLoadSoundFiles(), CG_Spawnpoints_MenuText_Draw(), CG_SpawnTracer(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditorDraw(), CG_SpeakerEditorMouseMove_Handling(), CG_StatsDebugAddText(), CG_StatsDown_f(), CG_StatsUp_f(), CG_TeamDebriefing_CalcXP(), CG_TeamDebriefingTeamSkillXP_Draw(), CG_TeamVoiceChat_f(), CG_TileClear(), CG_TimerReset_f(), CG_TimerSet_f(), CG_ToggleAutomap_f(), CG_topshotsDown_f(), CG_TopShotsDraw(), CG_topshotsParse_cmd(), CG_topshotsUp_f(), CG_TouchTriggerPrediction(), CG_Trap(), CG_UnderwaterSounds(), CG_UpdateFlamethrowerSounds(), CG_VoiceChatListForClient(), CG_VoiceChatLocal(), CG_WeaponAnimation(), CG_windowDraw(), CG_windowNormalizeOnText(), CG_Zoom(), SP_misc_gamemodel(), SP_worldspawn(), trap_S_StartSound(), trap_S_StartSoundEx(), trap_S_StartSoundVControl(), vmMain(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
vmCvar_t cl_demofilename
Definition at line 296 of file cg_main.c.
vmCvar_t cl_demooffset
Definition at line 297 of file cg_main.c.
vmCvar_t cl_demorecording
Definition at line 295 of file cg_main.c.
vmCvar_t cl_wavefilename
Definition at line 300 of file cg_main.c.
vmCvar_t cl_waveoffset
Definition at line 301 of file cg_main.c.
vmCvar_t cl_waverecording
Definition at line 299 of file cg_main.c.
qboolean cvarsLoaded = qfalse static
Definition at line 603 of file cg_main.c.
cvarTable_t cvarTable[] static
Definition at line 363 of file cg_main.c.
const unsigned int cvarTableSize = sizeof(cvarTable) / sizeof(cvarTable[0]) static
Definition at line 602 of file cg_main.c.
Referenced by CG_RegisterCvars(), and CG_UpdateCvars().
vmCvar_t demo_avifpsF1
Definition at line 250 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF2
Definition at line 251 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF3
Definition at line 252 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF4
Definition at line 253 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF5
Definition at line 254 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_drawTimeScale
Definition at line 255 of file cg_main.c.
Referenced by CG_demoTimescaleDraw().
vmCvar_t demo_infoWindow
Definition at line 256 of file cg_main.c.
Referenced by CG_keyOn_f(), and CG_SetInitialSnapshot().
vmCvar_t developer
Definition at line 224 of file cg_main.c.
Referenced by CG_CalcFov(), and Com_DPrintf().
itemDef_t* g_bindItem
Definition at line 50 of file ui_shared.c.
Referenced by Item_Bind_HandleKey(), Item_Bind_Paint(), Menu_HandleKey(), and vmMain().
qboolean g_waitingForKey
Definition at line 47 of file ui_shared.c.
Referenced by Item_Bind_HandleKey(), Menu_HandleKey(), Menu_HandleMouseMove(), and vmMain().
vmCvar_t int_cl_maxpackets
Definition at line 276 of file cg_main.c.
vmCvar_t int_cl_timenudge
Definition at line 277 of file cg_main.c.
vmCvar_t int_m_pitch
Definition at line 278 of file cg_main.c.
vmCvar_t int_sensitivity
Definition at line 279 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
vmCvar_t int_ui_blackout
Definition at line 280 of file cg_main.c.
Referenced by CG_DrawFlashFade().
vmCvar_t pmove_fixed
Definition at line 197 of file cg_main.c.
vmCvar_t pmove_msec
Definition at line 198 of file cg_main.c.