ET: Legacy: src/cgame/cg_newDraw.c File Reference
cg_newDraw.c File Reference
#include "cg_local.h"
Macros
#define CURSORHINT_SCALE 10
Functions
int CG_TrimLeftPixels (char *instr, float scale, float w, int size)
CG_TrimLeftPixels.
void CG_FitTextToWidth_Ext (char *instr, float scale, float w, int size, fontHelper_t *font)
CG_FitTextToWidth_Ext.
void CG_FitTextToWidth2 (char *instr, float scale, float w, int size)
CG_FitTextToWidth2.
void CG_FitTextToWidth_SingleLine (char *instr, float scale, float w, int size)
CG_FitTextToWidth_SingleLine.
void CG_DrawPlayerWeaponIcon (rectDef_t *rect, qboolean drawHighlighted, int align, vec4_t *refcolor)
CG_DrawPlayerWeaponIcon.
void CG_DrawCursorhint (rectDef_t *rect)
CG_DrawCursorhint.
float CG_GetValue (int ownerDraw, int type)
CG_GetValue.
qboolean CG_OwnerDrawVisible (int flags)
CG_OwnerDrawVisible.
void CG_DrawWeapStability (rectDef_t *rect)
Draw a bar showing current stability level (0-255), max at current weapon/ability, and 'perfect' reference mark probably only drawn for scoped weapons.
void CG_DrawWeapHeat (rectDef_t *rect, int align)
CG_DrawWeapHeat.
void CG_MouseEvent (int x, int y)
CG_MouseEvent.
void CG_EventHandling (int type, qboolean fForced)
CG_EventHandling.
void CG_KeyEvent (int key, qboolean down)
void CG_GetTeamColor (vec4_t *color)
CG_GetTeamColor.
void CG_RunMenuScript (char **args)
CG_RunMenuScript.
Macro Definition Documentation
#define CURSORHINT_SCALE 10
Definition at line 342 of file cg_newDraw.c.
Referenced by CG_DrawCursorhint().
Function Documentation
void CG_DrawCursorhint (rectDef_t * rect)
CG_DrawCursorhint.
Parameters
[in] rect
Note
cg_cursorHints.integer == 0: no hints 1: sin size pulse 2: one way size pulse 3: alpha pulse 4+: static image
Definition at line 355 of file cg_newDraw.c.
Referenced by CG_DrawActiveHud().
void CG_DrawPlayerWeaponIcon (rectDef_t * rect, qboolean drawHighlighted, int align, vec4_t * refcolor)
CG_DrawPlayerWeaponIcon.
Parameters
[in] rect
drawHighlighted - unused
[in] align
[in] refcolor
Definition at line 232 of file cg_newDraw.c.
Referenced by CG_DrawGunIcon().
void CG_DrawWeapHeat (rectDef_t * rect, int align)
CG_DrawWeapHeat.
Parameters
[in] rect
[in] align
Definition at line 580 of file cg_newDraw.c.
Referenced by CG_DrawGunIcon().
void CG_DrawWeapStability (rectDef_t * rect)
Draw a bar showing current stability level (0-255), max at current weapon/ability, and 'perfect' reference mark probably only drawn for scoped weapons.
Parameters
[in] rect
Definition at line 542 of file cg_newDraw.c.
Referenced by CG_DrawActiveHud().
void CG_EventHandling (int type, qboolean fForced)
CG_EventHandling.
Parameters
[in] type
[in] fForced
Definition at line 746 of file cg_newDraw.c.
Referenced by CG_ClassMenu_f(), CG_DeActivateEditSoundMode(), CG_FireteamCheckExecKey(), CG_KeyEvent(), CG_keyOff_f(), CG_keyOn_f(), CG_LimboMenu_f(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_KeyHandling(), CG_LimboPanel_SendSetupMsg(), CG_ModifyEditSpeaker(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickFireteams_f(), CG_QuickMessage_f(), CG_QuickSpawnpoint_f(), CG_Shutdown(), CG_SpawnpointsCheckExecKey(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditor_Ok_KeyUp(), CG_TeamMenu_f(), and vmMain().
void CG_FitTextToWidth2 (char * instr, float scale, float w, int size)
CG_FitTextToWidth2.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
Note
Unused
Definition at line 144 of file cg_newDraw.c.
void CG_FitTextToWidth_Ext (char * instr, float scale, float w, int size, fontHelper_t * font)
CG_FitTextToWidth_Ext.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
[in] font
Definition at line 83 of file cg_newDraw.c.
Referenced by CG_LimboPanel_RenderObjectiveText(), and CG_ObjectivesDraw().
void CG_FitTextToWidth_SingleLine (char * instr, float scale, float w, int size)
CG_FitTextToWidth_SingleLine.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
Note
Unused
Definition at line 205 of file cg_newDraw.c.
void CG_GetTeamColor (vec4_t * color)
CG_GetTeamColor.
Parameters
[out] color
Definition at line 962 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
float CG_GetValue (int ownerDraw, int type)
CG_GetValue.
Parameters
ownerDraw - unused
type - unused
Todo:
FIXME: what's this ??
Returns
Definition at line 521 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
void CG_KeyEvent (int key, qboolean down)
Definition at line 883 of file cg_newDraw.c.
Referenced by vmMain().
void CG_MouseEvent (int x, int y)
CG_MouseEvent.
Parameters
[in] x
[in] y
Definition at line 613 of file cg_newDraw.c.
Referenced by vmMain().
qboolean CG_OwnerDrawVisible (int flags)
CG_OwnerDrawVisible.
Parameters
flags - unused
Returns
Note
THINKABOUTME: should these be exclusive or inclusive..
Definition at line 532 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
void CG_RunMenuScript (char ** args)
CG_RunMenuScript.
Parameters
args - unused
Todo:
Unused function ?
Definition at line 989 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
int CG_TrimLeftPixels (char * instr, float scale, float w, int size)
CG_TrimLeftPixels.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
Returns
Note
Unused
Definition at line 47 of file cg_newDraw.c.