ET: Legacy: src/cgame/cg_commandmap.c File Reference
cg_commandmap.c File Reference
#include "cg_local.h"
Macros
#define AUTOMAP_ZOOM 5.159f
#define COMMANDMAP_PLAYER_ICON_SIZE 6
#define AUTOMAP_PLAYER_ICON_SIZE 5
#define CONST_ICON_NORMAL_SIZE 32.f
#define CONST_ICON_EXPANDED_SIZE 48.f
#define FLAGSIZE_EXPANDED 48.f
#define FLAGSIZE_NORMAL 32.f
#define FLAG_LEFTFRAC (25 / 128.f)
#define FLAG_TOPFRAC (95 / 128.f)
#define SPAWN_SIZEUPTIME 1000.f
Functions
void CG_TransformToCommandMapCoord (float *coord_x, float *coord_y)
CG_TransformToCommandMapCoord.
int CG_CurLayerForZ (int z)
CG_CurLayerForZ.
static qboolean CG_ScissorEntIsCulled (mapEntityData_t *mEnt, mapScissor_t *scissor)
CG_ScissorEntIsCulled.
static qboolean CG_ScissorPointIsCulled (vec2_t vec, mapScissor_t *scissor)
CG_ScissorPointIsCulled.
void CG_TransformAutomapEntity (void)
Calculate the scaled (zoomed) yet unshifted coordinate for each map entity within the automap.
void CG_AdjustAutomapZoom (int zoomIn)
CG_AdjustAutomapZoom.
void CG_ParseMapEntity (int *mapEntityCount, int *offset, team_t team)
CG_ParseMapEntity.
void CG_ParseMapEntityInfo (int axis_number, int allied_number)
CG_ParseMapEntityInfo.
static void CG_DrawGrid (float x, float y, float w, float h, mapScissor_t *scissor)
CG_DrawGrid.
void CG_DrawMapEntity (mapEntityData_t *mEnt, float x, float y, float w, float h, int mEntFilter, mapScissor_t *scissor, qboolean interactive, snapshot_t *snap, int icon_size)
CG_DrawMapEntity.
qboolean CG_DisguiseMapCheck (mapEntityData_t *mEnt)
CG_DisguiseMapCheck.
void CG_DrawMap (float x, float y, float w, float h, int mEntFilter, mapScissor_t *scissor, qboolean interactive, float alpha, qboolean borderblend)
CG_DrawMap.
void CG_DrawExpandedAutoMap (void)
CG_DrawExpandedAutoMap.
void CG_DrawAutoMap (float x, float y, float w, float h)
CG_DrawAutoMap.
int CG_DrawSpawnPointInfo (float px, float py, float pw, float ph, qboolean draw, mapScissor_t *scissor, int expand)
CG_DrawSpawnPointInfo.
void CG_DrawMortarMarker (float px, float py, float pw, float ph, qboolean draw, mapScissor_t *scissor, int expand)
CG_DrawMortarMarker.
qboolean CG_CommandCentreSpawnPointClick (void)
CG_CommandCentreSpawnPointClick.
void CG_CommandMap_SetHighlightText (const char *text, float x, float y)
CG_CommandMap_SetHighlightText.
void CG_CommandMap_DrawHighlightText (void)
CG_CommandMap_DrawHighlightText.
Variables
static mapEntityData_t mapEntities [MAX_GENTITIES]
static int mapEntityCount = 0
static qboolean expanded = qfalse
qboolean ccInitial = qtrue
static qboolean gridInitDone = qfalse
static vec2_t gridStartCoord
static vec2_t gridStep
static vec4_t clrBorderblend = { 0.f, 0.f, 0.f, 0.75f }
char cg_highlightText [256]
rectDef_t cg_highlightTextRect
Macro Definition Documentation
#define AUTOMAP_PLAYER_ICON_SIZE 5
Definition at line 517 of file cg_commandmap.c.
Referenced by CG_DrawMap().
#define AUTOMAP_ZOOM 5.159f
Definition at line 54 of file cg_commandmap.c.
Referenced by CG_DrawMap(), CG_DrawMapEntity(), and CG_DrawSpawnPointInfo().
#define COMMANDMAP_PLAYER_ICON_SIZE 6
Definition at line 516 of file cg_commandmap.c.
Referenced by CG_DrawMap().
#define CONST_ICON_EXPANDED_SIZE 48.f
Referenced by CG_DrawMapEntity().
#define CONST_ICON_NORMAL_SIZE 32.f
Referenced by CG_DrawMapEntity().
#define FLAG_LEFTFRAC (25 / 128.f)
Definition at line 1597 of file cg_commandmap.c.
Referenced by CG_DrawSpawnPointInfo().
#define FLAG_TOPFRAC (95 / 128.f)
Definition at line 1598 of file cg_commandmap.c.
Referenced by CG_DrawSpawnPointInfo().
#define FLAGSIZE_EXPANDED 48.f
Definition at line 1595 of file cg_commandmap.c.
Referenced by CG_DrawSpawnPointInfo().
#define FLAGSIZE_NORMAL 32.f
Definition at line 1596 of file cg_commandmap.c.
Referenced by CG_CommandCentreSpawnPointClick(), and CG_DrawSpawnPointInfo().
#define SPAWN_SIZEUPTIME 1000.f
Definition at line 1599 of file cg_commandmap.c.
Referenced by CG_DrawSpawnPointInfo().
Function Documentation
void CG_AdjustAutomapZoom (int zoomIn)
CG_AdjustAutomapZoom.
Parameters
[in] zoomIn
Definition at line 182 of file cg_commandmap.c.
Referenced by CG_AutomapZoomIn_f(), CG_AutomapZoomOut_f(), and CG_QuickSpawnpoint_f().
qboolean CG_CommandCentreSpawnPointClick (void)
CG_CommandCentreSpawnPointClick.
Returns
Definition at line 1907 of file cg_commandmap.c.
Referenced by CG_LimboPanel_KeyHandling().
void CG_CommandMap_DrawHighlightText (void)
CG_CommandMap_DrawHighlightText.
Definition at line 1972 of file cg_commandmap.c.
Referenced by CG_LimboPanel_RenderCommandMap().
void CG_CommandMap_SetHighlightText (const char * text, float x, float y)
CG_CommandMap_SetHighlightText.
Parameters
[in] text
[in] x
[in] y
Definition at line 1961 of file cg_commandmap.c.
Referenced by CG_DrawMapEntity(), and CG_DrawSpawnPointInfo().
int CG_CurLayerForZ (int z)
CG_CurLayerForZ.
Parameters
[in] z
Returns
Definition at line 61 of file cg_commandmap.c.
Referenced by CG_CommandCentreSpawnPointClick(), CG_DrawAutoMap(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), and CG_LimboPanel_Setup().
qboolean CG_DisguiseMapCheck (mapEntityData_t * mEnt)
CG_DisguiseMapCheck.
Parameters
[in] mEnt
Returns
Definition at line 1117 of file cg_commandmap.c.
Referenced by CG_DrawMap().
void CG_DrawAutoMap (float x, float y, float w, float h)
CG_DrawAutoMap.
Parameters
[in] x
[in] y
[in] w
[in] h
Definition at line 1493 of file cg_commandmap.c.
Referenced by CG_DrawNewCompass().
void CG_DrawExpandedAutoMap (void)
CG_DrawExpandedAutoMap.
Definition at line 1359 of file cg_commandmap.c.
Referenced by CG_DrawAutoMap(), and CG_DrawNewCompass().
static void CG_DrawGrid (float x, float y, float w, float h, mapScissor_t * scissor) static
CG_DrawGrid.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] scissor
Definition at line 310 of file cg_commandmap.c.
Referenced by CG_DrawMap().
void CG_DrawMap (float x, float y, float w, float h, int mEntFilter, mapScissor_t * scissor, qboolean interactive, float alpha, qboolean borderblend)
CG_DrawMap.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] mEntFilter
[in] scissor
[in] interactive
[in] alpha
[in] borderblend
Todo:
: the code above seems to do weird things to the next trap_R_DrawStretchPic issued.
Definition at line 1156 of file cg_commandmap.c.
Referenced by CG_DrawAutoMap(), CG_DrawExpandedAutoMap(), and CG_LimboPanel_RenderCommandMap().
void CG_DrawMapEntity (mapEntityData_t * mEnt, float x, float y, float w, float h, int mEntFilter, mapScissor_t * scissor, qboolean interactive, snapshot_t * snap, int icon_size)
CG_DrawMapEntity.
Parameters
[in] mEnt
[in] x
[in] y
[in] w
[in] h
[in] mEntFilter
[in] scissor
[in] interactive
[in] snap
[in] icon_size
(cgs.ccFilter & CC_FILTER_BUDDIES) &&
Todo:
: the map entity ME_PLAYER_DISGUISED is never defined here, so this is a bit hackish
Todo:
: this is churchill - add jagdpanther?
Todo:
: this is churchill - add jagdpanther?
Definition at line 535 of file cg_commandmap.c.
Referenced by CG_DrawMap().
void CG_DrawMortarMarker (float px, float py, float pw, float ph, qboolean draw, mapScissor_t * scissor, int expand)
CG_DrawMortarMarker.
Parameters
[in] px
[in] py
[in] pw
[in] ph
[in] draw - unused
[in] scissor - unused
[in] expand
Definition at line 1789 of file cg_commandmap.c.
Referenced by CG_DrawMap().
int CG_DrawSpawnPointInfo (float px, float py, float pw, float ph, qboolean draw, mapScissor_t * scissor, int expand)
CG_DrawSpawnPointInfo.
Parameters
[in] px
[in] py
[in] pw
[in] ph
[in] draw
[in] scissor
[in] expand
Returns
Definition at line 1612 of file cg_commandmap.c.
Referenced by CG_DrawMap().
void CG_ParseMapEntity (int * mapEntityCount, int * offset, team_t team)
CG_ParseMapEntity.
Parameters
[in] mapEntityCount
[in,out] offset
[in] team
Definition at line 217 of file cg_commandmap.c.
Referenced by CG_ParseMapEntityInfo().
void CG_ParseMapEntityInfo (int axis_number, int allied_number)
CG_ParseMapEntityInfo.
Parameters
[in] axis_number
[in] allied_number
Definition at line 280 of file cg_commandmap.c.
Referenced by CG_ServerCommand().
static qboolean CG_ScissorEntIsCulled (mapEntityData_t * mEnt, mapScissor_t * scissor) static
CG_ScissorEntIsCulled.
Parameters
[in] mEnt
[in] scissor
Returns
Definition at line 85 of file cg_commandmap.c.
Referenced by CG_DrawMapEntity().
static qboolean CG_ScissorPointIsCulled (vec2_t vec, mapScissor_t * scissor) static
CG_ScissorPointIsCulled.
Parameters
[in] vec
[in] scissor
Returns
Definition at line 121 of file cg_commandmap.c.
Referenced by CG_DrawMortarMarker(), and CG_DrawSpawnPointInfo().
void CG_TransformAutomapEntity (void)
Calculate the scaled (zoomed) yet unshifted coordinate for each map entity within the automap.
Todo:
: check value out of range before?
Definition at line 155 of file cg_commandmap.c.
Referenced by CG_AdjustAutomapZoom(), and CG_ParseMapEntityInfo().
void CG_TransformToCommandMapCoord (float * coord_x, float * coord_y)
CG_TransformToCommandMapCoord.
Parameters
[in] coord_x
[in] coord_y
Definition at line 48 of file cg_commandmap.c.
Referenced by CG_ParseSpawns().
Variable Documentation
qboolean ccInitial = qtrue
Definition at line 41 of file cg_commandmap.c.
Referenced by CG_EventHandling(), and CG_SetInitialSnapshot().
char cg_highlightText[256]
Definition at line 1952 of file cg_commandmap.c.
Referenced by CG_CommandMap_DrawHighlightText(), and CG_CommandMap_SetHighlightText().
rectDef_t cg_highlightTextRect
Definition at line 1953 of file cg_commandmap.c.
vec4_t clrBorderblend = { 0.f, 0.f, 0.f, 0.75f } static
Definition at line 1142 of file cg_commandmap.c.
Referenced by CG_DrawMap().
qboolean expanded = qfalse static
Definition at line 39 of file cg_commandmap.c.
Referenced by CG_CommandMap_SetHighlightText(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), and SV_Map_f().
qboolean gridInitDone = qfalse static
Definition at line 299 of file cg_commandmap.c.
Referenced by CG_DrawGrid().
vec2_t gridStartCoord static
Definition at line 300 of file cg_commandmap.c.
Referenced by CG_DrawGrid().
vec2_t gridStep static
Definition at line 300 of file cg_commandmap.c.
Referenced by CG_DrawGrid(), LightgridColor(), R_LoadLightGrid(), and R_SetupEntityLightingGrid().
mapEntityData_t mapEntities[MAX_GENTITIES] static
Definition at line 37 of file cg_commandmap.c.
int mapEntityCount = 0 static
Definition at line 38 of file cg_commandmap.c.
Referenced by CG_DrawMap(), CG_ParseMapEntityInfo(), and CG_TransformAutomapEntity().