ET: Legacy: src/cgame/cg_debriefing.c File Reference
cg_debriefing.c File Reference
#include "cg_local.h"
Macros
#define DB_RANK_X 213 + 4
#define DB_NAME_X DB_RANK_X + 28
#define DB_TIME_X DB_NAME_X + 150
#define DB_KILLS_X DB_TIME_X + 30
#define DB_DEATHS_X DB_KILLS_X + 24
#define DB_GIBS_X DB_DEATHS_X + 24
#define DB_SELFKILLS_X DB_GIBS_X + 24
#define DB_TEAMKILLS_X DB_SELFKILLS_X + 24
#define DB_TEAMGIBS_X DB_TEAMKILLS_X + 24
#define DB_XP_X DB_TEAMGIBS_X + 24
#define DH_HEADING_Y 60
#define PLAYERHEADER_SKILLS(number)
#define TDB_SKILL_TITLES_XP(number, title, x)
#define TDB_SKILL_AXIS_XP(number)
#define TDB_SKILL_ALLIES_XP(number)
#define DB_MAPNAME_X 15
#define DB_MAPVOTE_X (DB_MAPNAME_X + 200)
#define DB_MAPVOTE_Y (56 + 10)
#define DB_MAPVOTE_X2 (620 - 192 - 96 - 20)
#define DB_MAPVOTE_Y2 (326 + 30 - 192 - 16)
Functions
team_t CG_Debriefing_FindWinningTeam (void)
CG_Debriefing_FindWinningTeam.
team_t CG_Debriefing_FindOveralWinningTeam (void)
CG_Debriefing_FindOveralWinningTeam.
team_t CG_Debriefing_FindWinningTeamForPos (int pos)
CG_Debriefing_FindWinningTeamForPos.
int QDECL CG_SortPlayersByXP (const void *a, const void *b)
CG_SortPlayersByXP.
PLAYERHEADER_SKILLS (0)
PLAYERHEADER_SKILLS (1)
PLAYERHEADER_SKILLS (2)
PLAYERHEADER_SKILLS (3)
PLAYERHEADER_SKILLS (4)
PLAYERHEADER_SKILLS (5)
PLAYERHEADER_SKILLS (6)
TDB_SKILL_TITLES_XP (0,"Battle Sense", 0)
TDB_SKILL_TITLES_XP (1,"Engineer", 1)
TDB_SKILL_TITLES_XP (2,"Medic", 0)
TDB_SKILL_TITLES_XP (3,"Field Ops", 1)
TDB_SKILL_TITLES_XP (4,"Light Weapons", 0)
TDB_SKILL_TITLES_XP (5,"Soldier", 1)
TDB_SKILL_TITLES_XP (6,"Covert Ops", 0)
TDB_SKILL_TITLES_XP (7,"Total", 1)
TDB_SKILL_AXIS_XP (0)
TDB_SKILL_AXIS_XP (1)
TDB_SKILL_AXIS_XP (2)
TDB_SKILL_AXIS_XP (3)
TDB_SKILL_AXIS_XP (4)
TDB_SKILL_AXIS_XP (5)
TDB_SKILL_AXIS_XP (6)
TDB_SKILL_AXIS_XP (7)
TDB_SKILL_ALLIES_XP (0)
TDB_SKILL_ALLIES_XP (1)
TDB_SKILL_ALLIES_XP (2)
TDB_SKILL_ALLIES_XP (3)
TDB_SKILL_ALLIES_XP (4)
TDB_SKILL_ALLIES_XP (5)
TDB_SKILL_ALLIES_XP (6)
TDB_SKILL_ALLIES_XP (7)
qboolean CG_MapVoteList_KeyDown (panel_button_t *button, int key)
CG_MapVoteList_KeyDown.
qboolean CG_MapVote_VoteButton_KeyDown (panel_button_t *button, int key)
CG_MapVote_VoteButton_KeyDown.
void CG_MapVote_MultiVoteButton_Draw (panel_button_t *button)
CG_MapVote_MultiVoteButton_Draw.
void CG_MapVoteList_Draw (panel_button_t *button)
CG_MapVoteList_Draw.
void CG_MapVote_VoteButton_Draw (panel_button_t *button)
CG_MapVote_VoteButton_Draw.
qboolean CG_MapVote_MultiVoteButton_KeyDown (panel_button_t *button, int key)
CG_MapVote_MultiVoteButton_KeyDown.
void CG_Debriefing_ChatEdit_Draw (panel_button_t *button)
CG_Debriefing_ChatEdit_Draw.
void CG_Debriefing_ChatBox_Draw (panel_button_t *button)
CG_Debriefing_ChatBox_Draw.
void CG_ChatPanel_Setup (void)
CG_ChatPanel_Setup.
void CG_Debriefing_Startup (void)
CG_Debriefing_Startup.
void CG_Debriefing_Shutdown (void)
CG_Debriefing_Shutdown.
void CG_Debriefing_InfoRequests (void)
CG_Debriefing_InfoRequests.
qboolean CG_Debriefing_Draw (void)
CG_Debriefing_Draw.
qboolean CG_DebriefingPlayerList_KeyDown (panel_button_t *button, int key)
CG_DebriefingPlayerList_KeyDown.
int CG_Debriefing_GetNextWeaponStat (int pos)
CG_Debriefing_GetNextWeaponStat.
void CG_DebriefingPlayerWeaponStats_Draw (panel_button_t *button)
CG_DebriefingPlayerWeaponStats_Draw.
const char * CG_Debriefing_TimeToString (float msec)
CG_Debriefing_TimeToString.
void CG_DebriefingTitle_Draw (panel_button_t *button)
CG_DebriefingTitle_Draw.
void CG_DebriefingXPHeader_Draw (panel_button_t *button)
CG_DebriefingXPHeader_Draw.
void CG_DebriefingPlayerList_Draw (panel_button_t *button)
CG_DebriefingPlayerList_Draw.
const char * CG_Debriefing_FullRankNameForClientInfo (clientInfo_t *ci)
CG_Debriefing_FullRankNameForClientInfo.
const char * CG_Debriefing_RankNameForClientInfo (clientInfo_t *ci)
CG_Debriefing_RankNameForClientInfo.
void CG_Debriefing_ParseWeaponAccuracies (void)
CG_Debriefing_ParseWeaponAccuracies.
void CG_Debriefing_ParsePlayerTime (void)
CG_Debriefing_ParsePlayerTime.
void CG_Debriefing_ParsePlayerKillsDeaths (void)
CG_Debriefing_ParsePlayerKillsDeaths.
void CG_Debriefing_ParseWeaponStats (void)
CG_Debriefing_ParseWeaponStats.
void CG_Debriefing_ParseAwards (void)
CG_Debriefing_ParseAwards.
int CG_Debriefing_ScrollGetMax (panel_button_t *button)
CG_Debriefing_ScrollGetMax.
int CG_Debriefing_ScrollGetCount (panel_button_t *button)
CG_Debriefing_ScrollGetCount.
int CG_Debriefing_ScrollGetOffset (panel_button_t *button)
CG_Debriefing_ScrollGetOffset.
void CG_Debriefing_ScrollSetOffset (panel_button_t *button, int ofs)
CG_Debriefing_ScrollSetOffset.
void CG_Debriefing_ScrollGetBarRect (panel_button_t *button, rectDef_t *r)
CG_Debriefing_ScrollGetBarRect.
void CG_Debriefing_ScrollCheckOffset (panel_button_t *button)
CG_Debriefing_ScrollCheckOffset.
void CG_Debriefing_MouseEvent (int x, int y)
CG_Debriefing_MouseEvent.
void CG_Debriefing_Scrollbar_Draw (panel_button_t *button)
CG_Debriefing_Scrollbar_Draw.
qboolean CG_Debriefing_Scrollbar_KeyDown (panel_button_t *button, int key)
CG_Debriefing_Scrollbar_KeyDown.
qboolean CG_Debriefing_Scrollbar_KeyUp (panel_button_t *button, int key)
CG_Debriefing_Scrollbar_KeyUp.
void CG_Debriefing_KeyEvent (int key, qboolean down)
CG_Debriefing_KeyEvent.
void CG_Debriefing_PlayerSkills_Draw (panel_button_t *button)
CG_Debriefing_PlayerSkills_Draw.
void CG_Debriefing_PlayerHitRegions_Draw (panel_button_t *button)
void CG_Debriefing_PlayerACC_Draw (panel_button_t *button)
CG_Debriefing_PlayerACC_Draw.
void CG_Debriefing_PlayerHS_Draw (panel_button_t *button)
CG_Debriefing_PlayerHS_Draw.
void CG_Debriefing_PlayerXP_Draw (panel_button_t *button)
CG_Debriefing_PlayerXP_Draw.
void CG_Debriefing_PlayerTime_Draw (panel_button_t *button)
CG_Debriefing_PlayerTime_Draw.
void CG_Debriefing_PlayerMedals_Draw (panel_button_t *button)
CG_Debriefing_PlayerMedals_Draw.
void CG_Debriefing_PlayerRank_Draw (panel_button_t *button)
CG_Debriefing_PlayerRank_Draw.
void CG_Debriefing_PlayerName_Draw (panel_button_t *button)
CG_Debriefing_PlayerName_Draw.
clientInfo_t * CG_Debriefing_GetSelectedClientInfo (void)
CG_Debriefing_GetSelectedClientInfo.
void CG_Debrieing_SetSelectedClient (int clientNum)
CG_Debrieing_SetSelectedClient.
qboolean CG_Debriefing_ChatButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_ChatButton_KeyDown.
void CG_Debriefing_ReadyButton_Draw (panel_button_t *button)
CG_Debriefing_ReadyButton_Draw.
void CG_Debriefing_ChatButton_Draw (panel_button_t *button)
CG_Debriefing_ChatButton_Draw.
void CG_QuickMessage_f (void)
CG_QuickMessage_f.
qboolean CG_Debriefing_ReadyButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_ReadyButton_KeyDown.
qboolean CG_Debriefing_QCButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_QCButton_KeyDown.
qboolean CG_Debriefing_VoteButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_VoteButton_KeyDown.
qboolean CG_Debriefing_NextButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_NextButton_KeyDown.
void CG_Debriefing_VoteButton_Draw (panel_button_t *button)
CG_Debriefing_VoteButton_Draw.
void CG_Debriefing_NextButton_Draw (panel_button_t *button)
CG_Debriefing_NextButton_Draw.
void CG_Debriefing_ChatEditFinish (panel_button_t *button)
CG_Debriefing_ChatEditFinish.
float CG_Debriefing_CalcCampaignProgress (void)
CG_Debriefing_CalcCampaignProgress.
int CG_TeamDebriefing_CalcXP (team_t team, int mapindex, int skillindex)
CG_TeamDebriefing_CalcXP.
void CG_TeamDebriefingTeamSkillXP_Draw (panel_button_t *button)
CG_TeamDebriefingTeamSkillXP_Draw.
void CG_PanelButtonsRender_Button_Ext (rectDef_t *r, const char *text)
CG_PanelButtonsRender_Button_Ext.
void CG_PanelButtonsRender_Button (panel_button_t *button)
CG_PanelButtonsRender_Button.
void CG_PanelButtonsRender_Window_Ext (rectDef_t *r, const char *text, int align, int innerheight, float fontscale, int yofs)
CG_PanelButtonsRender_Window_Ext.
void CG_PanelButtonsRender_Window (panel_button_t *button)
CG_PanelButtonsRender_Window.
const char * CG_Debriefing_WinStringForTeam (team_t team)
CG_Debriefing_WinStringForTeam.
void CG_Debriefing_MissionTitle_Draw (panel_button_t *button)
CG_Debriefing_MissionTitle_Draw.
void CG_Debriefing_Awards_Draw (panel_button_t *button)
CG_Debriefing_Awards_Draw.
void CG_Debriefing_Maps_Draw (panel_button_t *button)
CG_Debriefing_Maps_Draw.
void CG_Debriefing_Mission_Draw (panel_button_t *button)
CG_Debriefing_Mission_Draw.
team_t CG_Debriefing_FindWinningTeamForMap (void)
CG_Debriefing_FindWinningTeamForMap.
qboolean CG_Debriefing_Maps_KeyDown (panel_button_t *button, int key)
CG_Debriefing_Maps_KeyDown.
void CG_Debriefing_TeamSkillHeaders_Draw (panel_button_t *button)
CG_Debriefing_TeamSkillHeaders_Draw.
void CG_Debriefing_TeamSkillXP_Draw (panel_button_t *button)
CG_Debriefing_TeamSkillXP_Draw.
void CG_parseMapVoteListInfo ()
CG_parseMapVoteListInfo.
void CG_parseMapVoteTally ()
CG_parseMapVoteTally.
Variables
panel_button_text_t debriefPlayerHeadingSmallerFont
panel_button_t debriefPlayerWeaponStatsHeader
panel_button_t debriefPlayerWeaponStatsNameHeader
panel_button_t debriefPlayerWeaponStatsShotsHeader
panel_button_t debriefPlayerWeaponStatsHitsHeader
panel_button_t debriefPlayerWeaponStatsKillsHeader
panel_button_t debriefPlayerWeaponStatsList
panel_button_t debriefPlayerWeaponStatsListScroll
panel_button_t debriefTitleWindow
panel_button_t debriefMissionTitleWindow
panel_button_t debriefMissionImage
panel_button_t debriefMissionMaps
panel_button_t debriefMissionAwardsWindow
panel_button_t debriefMissionAwardsList
panel_button_t debriefMissionAwardsListScroll
panel_button_t debriefMissionStatsWindow
panel_button_t debriefMissionStatsHeaders
panel_button_t debriefMissionStatsWinner
panel_button_t debriefMissionStatsLoser
panel_button_t debriefPlayerListWindow
panel_button_text_t debriefPlayerListFont
panel_button_t debriefHeadingRank
panel_button_t debriefHeadingName
panel_button_t debriefHeadingTime
panel_button_t debriefHeadingKills
panel_button_t debriefHeadingDeaths
panel_button_t debriefHeadingGibs
panel_button_t debriefHeadingSelfKills
panel_button_t debriefHeadingTeamKills
panel_button_t debriefHeadingTeamGibs
panel_button_t debriefHeadingXP
panel_button_t debriefPlayerList
panel_button_t debriefPlayerListScroll
panel_button_text_t debriefPlayerInfoFont
panel_button_t debriefPlayerInfoWindow
panel_button_t debriefPlayerInfoName
panel_button_t debriefPlayerInfoRank
panel_button_t debriefPlayerInfoMedals
panel_button_t debriefPlayerInfoTime
panel_button_t debriefPlayerInfoXP
panel_button_t debriefPlayerInfoACC
panel_button_t debriefPlayerInfoHS
panel_button_t debriefPlayerInfoHitRegions
panel_button_t * debriefPanelButtons []
panel_button_text_t teamDebriefTitleSmall
panel_button_text_t teamDebriefTitle
panel_button_t * teamDebriefPanelButtons []
panel_button_text_t chatPanelButtonFont
panel_button_t chatPanelWindow
panel_button_t chatPanelText
panel_button_t chatPanelNextButton
panel_button_t chatPanelVoteButton
panel_button_t chatPanelQCButton
panel_button_t chatPanelReadyButton
panel_button_t chatTypeButton
panel_button_t charPanelEditSurround
panel_button_t charPanelEdit
vec4_t clrTxtBck = { 0.6f, 0.6f, 0.6f, 1.0f }
panel_button_t mapVoteWindow
panel_button_text_t mapVoteFont
panel_button_t mapVoteHeadingName
panel_button_t mapVoteHeadingVotes
panel_button_t mapVoteNamesList
panel_button_t mapVoteNamesListScroll
panel_button_t mapVoteButton
panel_button_t mapVoteButton1
panel_button_t mapVoteButton2
panel_button_t mapVoteButton3
panel_button_t mapVoteBorder1
panel_button_t mapVoteBorder2
panel_button_t mapVoteBorder3
panel_button_t * chatPanelButtons []
panel_button_t * mapVoteButtons []
static vec4_t clrSelectedClient = { 1.f, 1.f, 1.f, 0.3f }
qhandle_t img
qhandle_t imgH
qhandle_t imgA
qhandle_t imgB
qhandle_t imgL
const char * awardNames [NUM_ENDGAME_AWARDS]
const int skillPositions [SK_NUM_SKILLS+1]
Macro Definition Documentation
#define DB_DEATHS_X DB_KILLS_X + 24
Definition at line 55 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_GIBS_X DB_DEATHS_X + 24
Definition at line 56 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_KILLS_X DB_TIME_X + 30
Definition at line 54 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_MAPNAME_X 15
Definition at line 928 of file cg_debriefing.c.
Referenced by CG_MapVoteList_Draw().
#define DB_MAPVOTE_X (DB_MAPNAME_X + 200)
Definition at line 929 of file cg_debriefing.c.
Referenced by CG_MapVoteList_Draw().
#define DB_MAPVOTE_X2 (620 - 192 - 96 - 20)
Definition at line 931 of file cg_debriefing.c.
Referenced by CG_MapVoteList_Draw().
#define DB_MAPVOTE_Y (56 + 10)
Definition at line 930 of file cg_debriefing.c.
Referenced by CG_MapVoteList_Draw(), and CG_MapVoteList_KeyDown().
#define DB_MAPVOTE_Y2 (326 + 30 - 192 - 16)
Definition at line 932 of file cg_debriefing.c.
Referenced by CG_MapVoteList_Draw().
#define DB_NAME_X DB_RANK_X + 28
Definition at line 52 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_RANK_X 213 + 4
Definition at line 51 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_SELFKILLS_X DB_GIBS_X + 24
Definition at line 57 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_TEAMGIBS_X DB_TEAMKILLS_X + 24
Definition at line 59 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_TEAMKILLS_X DB_SELFKILLS_X + 24
Definition at line 58 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_TIME_X DB_NAME_X + 150
Definition at line 53 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DB_XP_X DB_TEAMGIBS_X + 24
Definition at line 60 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
#define DH_HEADING_Y 60
Definition at line 61 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_KeyDown().
#define PLAYERHEADER_SKILLS (number)
Value:
panel_button_t debriefPlayerInfoSkills ## number = {      \
        NULL,                                       \
        NULL,                                       \
        { 24,                            136 + (number * 14), 12, 12 }, \
        { number,                        0,                   0,  0, 0, 0, 0, 0},  \
        &debriefPlayerInfoFont,          /* font     */  \
        NULL,                            /* keyDown  */  \
        NULL,                            /* keyUp    */  \
        CG_Debriefing_PlayerSkills_Draw,            \
        NULL,                                       \
        0,                                       \
    }
Definition at line 654 of file cg_debriefing.c.
#define TDB_SKILL_ALLIES_XP (number)
Value:
panel_button_t teamDebriefSkillXPText1_ ## number = {         \
        NULL,                                                   \
        NULL,                                                   \
        { 110 + (number * 65),             340,                  470, 200 },                \
        { 1,                               number,               0,   0, 0, 0, 0, 0},                        \
        &teamDebriefTitle,                 /* font     */                  \
        NULL,                              /* keyDown  */                      \
        NULL,                              /* keyUp    */                  \
        CG_TeamDebriefingTeamSkillXP_Draw,                      \
        NULL,                                                   \
        0,                                                   \
    }
Definition at line 754 of file cg_debriefing.c.
#define TDB_SKILL_AXIS_XP (number)
Value:
panel_button_t teamDebriefSkillXPText0_ ## number = {         \
        NULL,                                                   \
        NULL,                                                   \
        { 110 + (number * 65),             320,                  470, 200 },                \
        { 0,                               number,               0,   0, 0, 0, 0, 0},                        \
        &teamDebriefTitle,                 /* font     */                  \
        NULL,                              /* keyDown  */                      \
        NULL,                              /* keyUp    */                  \
        CG_TeamDebriefingTeamSkillXP_Draw,                      \
        NULL,                                                   \
        0,                                                   \
    }
Definition at line 740 of file cg_debriefing.c.
#define TDB_SKILL_TITLES_XP (number, title, x)
Value:
panel_button_t teamDebriefSkillXPText_ ## number = {          \
        NULL,                                                   \
        title,                                                  \
        { 100 + (number * 65),      304 - (x * 12),                 20, 200 },      \
        { 0,                        0,                              0,  0, 0, 0, 0, 0},                             \
        &teamDebriefTitleSmall,     /* font     */              \
        NULL,                       /* keyDown  */                      \
        NULL,                       /* keyUp    */                  \
        BG_PanelButtonsRender_Text,                             \
        NULL,                                                   \
        0,                                                   \
    }
Definition at line 717 of file cg_debriefing.c.
Function Documentation
void CG_ChatPanel_Setup (void)
CG_ChatPanel_Setup.
Todo:
: only active for gametype 6 ?
Definition at line 1497 of file cg_debriefing.c.
Referenced by CG_RegisterGraphics().
void CG_Debriefing_Awards_Draw (panel_button_t * button)
CG_Debriefing_Awards_Draw.
Parameters
[in] button
Definition at line 3467 of file cg_debriefing.c.
float CG_Debriefing_CalcCampaignProgress (void)
CG_Debriefing_CalcCampaignProgress.
Returns
Note
Unused
Definition at line 3141 of file cg_debriefing.c.
void CG_Debriefing_ChatBox_Draw (panel_button_t * button)
CG_Debriefing_ChatBox_Draw.
Parameters
[in] button
Definition at line 1420 of file cg_debriefing.c.
void CG_Debriefing_ChatButton_Draw (panel_button_t * button)
CG_Debriefing_ChatButton_Draw.
Parameters
[in] button
Definition at line 2972 of file cg_debriefing.c.
qboolean CG_Debriefing_ChatButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_ChatButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 2914 of file cg_debriefing.c.
void CG_Debriefing_ChatEdit_Draw (panel_button_t * button)
CG_Debriefing_ChatEdit_Draw.
Parameters
[in] button
Definition at line 1379 of file cg_debriefing.c.
void CG_Debriefing_ChatEditFinish (panel_button_t * button)
CG_Debriefing_ChatEditFinish.
Parameters
[in] button
Definition at line 3112 of file cg_debriefing.c.
qboolean CG_Debriefing_Draw (void)
CG_Debriefing_Draw.
Returns
Definition at line 1642 of file cg_debriefing.c.
Referenced by CG_DrawIntermission().
team_t CG_Debriefing_FindOveralWinningTeam (void)
CG_Debriefing_FindOveralWinningTeam.
Returns
Definition at line 3911 of file cg_debriefing.c.
Referenced by CG_Debriefing_FindWinningTeam(), CG_Debriefing_MissionTitle_Draw(), and CG_Debriefing_TeamSkillXP_Draw().
team_t CG_Debriefing_FindWinningTeam (void)
CG_Debriefing_FindWinningTeam.
Returns
Definition at line 3920 of file cg_debriefing.c.
Referenced by CG_Debriefing_Mission_Draw().
team_t CG_Debriefing_FindWinningTeamForMap (void)
CG_Debriefing_FindWinningTeamForMap.
Returns
Definition at line 3769 of file cg_debriefing.c.
Referenced by CG_Debriefing_MissionTitle_Draw().
team_t CG_Debriefing_FindWinningTeamForPos (int pos)
CG_Debriefing_FindWinningTeamForPos.
Parameters
pos
Returns
Definition at line 3794 of file cg_debriefing.c.
Referenced by CG_Debriefing_FindOveralWinningTeam(), CG_Debriefing_FindWinningTeam(), CG_Debriefing_Maps_Draw(), and CG_Debriefing_Mission_Draw().
const char* CG_Debriefing_FullRankNameForClientInfo (clientInfo_t * ci)
CG_Debriefing_FullRankNameForClientInfo.
Parameters
[in] ci
Returns
Definition at line 2010 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerRank_Draw().
int CG_Debriefing_GetNextWeaponStat (int pos)
CG_Debriefing_GetNextWeaponStat.
Parameters
[in] pos
Returns
Definition at line 1734 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerWeaponStats_Draw().
clientInfo_t* CG_Debriefing_GetSelectedClientInfo (void)
CG_Debriefing_GetSelectedClientInfo.
Returns
Definition at line 2871 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Debriefing_PlayerTime_Draw(), and CG_Debriefing_PlayerXP_Draw().
void CG_Debriefing_InfoRequests (void)
CG_Debriefing_InfoRequests.
Note
debriefing server commands are parsed in CG_ServerCommand() - CG_Debriefing_ServerCommand() has been removed
Definition at line 1578 of file cg_debriefing.c.
Referenced by CG_Debriefing_Draw().
void CG_Debriefing_KeyEvent (int key, qboolean down)
CG_Debriefing_KeyEvent.
Parameters
[in] key
[in] down
Definition at line 2503 of file cg_debriefing.c.
Referenced by CG_KeyEvent().
void CG_Debriefing_Maps_Draw (panel_button_t * button)
CG_Debriefing_Maps_Draw.
Parameters
[in] button
Definition at line 3516 of file cg_debriefing.c.
qboolean CG_Debriefing_Maps_KeyDown (panel_button_t * button, int key)
CG_Debriefing_Maps_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 3936 of file cg_debriefing.c.
void CG_Debriefing_Mission_Draw (panel_button_t * button)
CG_Debriefing_Mission_Draw.
Parameters
[in] button
Definition at line 3564 of file cg_debriefing.c.
void CG_Debriefing_MissionTitle_Draw (panel_button_t * button)
CG_Debriefing_MissionTitle_Draw.
Parameters
[in] button
Definition at line 3342 of file cg_debriefing.c.
void CG_Debriefing_MouseEvent (int x, int y)
CG_Debriefing_MouseEvent.
Parameters
[in] x
[in] y
Definition at line 2370 of file cg_debriefing.c.
Referenced by CG_MouseEvent().
void CG_Debriefing_NextButton_Draw (panel_button_t * button)
CG_Debriefing_NextButton_Draw.
Parameters
[in] button
Definition at line 3103 of file cg_debriefing.c.
qboolean CG_Debriefing_NextButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_NextButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3068 of file cg_debriefing.c.
void CG_Debriefing_ParseAwards (void)
CG_Debriefing_ParseAwards.
Definition at line 2127 of file cg_debriefing.c.
Referenced by CG_Debriefing_Awards_Draw(), and CG_Debriefing_ScrollGetCount().
void CG_Debriefing_ParsePlayerKillsDeaths (void)
CG_Debriefing_ParsePlayerKillsDeaths.
Definition at line 2086 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_ParsePlayerTime (void)
CG_Debriefing_ParsePlayerTime.
Definition at line 2053 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_ParseWeaponAccuracies (void)
CG_Debriefing_ParseWeaponAccuracies.
Definition at line 2038 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_ParseWeaponStats (void)
CG_Debriefing_ParseWeaponStats.
Definition at line 2105 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_PlayerACC_Draw (panel_button_t * button)
CG_Debriefing_PlayerACC_Draw.
Parameters
[in] button
Definition at line 2684 of file cg_debriefing.c.
void CG_Debriefing_PlayerHitRegions_Draw (panel_button_t * button)
Definition at line 2589 of file cg_debriefing.c.
void CG_Debriefing_PlayerHS_Draw (panel_button_t * button)
CG_Debriefing_PlayerHS_Draw.
Parameters
[in] button
Definition at line 2700 of file cg_debriefing.c.
void CG_Debriefing_PlayerMedals_Draw (panel_button_t * button)
CG_Debriefing_PlayerMedals_Draw.
Parameters
[in] button
Definition at line 2787 of file cg_debriefing.c.
void CG_Debriefing_PlayerName_Draw (panel_button_t * button)
CG_Debriefing_PlayerName_Draw.
Parameters
[in] button
Definition at line 2839 of file cg_debriefing.c.
void CG_Debriefing_PlayerRank_Draw (panel_button_t * button)
CG_Debriefing_PlayerRank_Draw.
Parameters
[in] button
Definition at line 2814 of file cg_debriefing.c.
void CG_Debriefing_PlayerSkills_Draw (panel_button_t * button)
CG_Debriefing_PlayerSkills_Draw.
Parameters
[in] button
Definition at line 2546 of file cg_debriefing.c.
void CG_Debriefing_PlayerTime_Draw (panel_button_t * button)
CG_Debriefing_PlayerTime_Draw.
Parameters
[in] button
Definition at line 2755 of file cg_debriefing.c.
void CG_Debriefing_PlayerXP_Draw (panel_button_t * button)
CG_Debriefing_PlayerXP_Draw.
Parameters
[in] button
Definition at line 2716 of file cg_debriefing.c.
qboolean CG_Debriefing_QCButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_QCButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3028 of file cg_debriefing.c.
const char* CG_Debriefing_RankNameForClientInfo (clientInfo_t * ci)
CG_Debriefing_RankNameForClientInfo.
Parameters
[in] ci
Returns
Definition at line 2025 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
void CG_Debriefing_ReadyButton_Draw (panel_button_t * button)
CG_Debriefing_ReadyButton_Draw.
Parameters
[in] button
Definition at line 2946 of file cg_debriefing.c.
qboolean CG_Debriefing_ReadyButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_ReadyButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3000 of file cg_debriefing.c.
void CG_Debriefing_Scrollbar_Draw (panel_button_t * button)
CG_Debriefing_Scrollbar_Draw.
Parameters
[in] button
Definition at line 2440 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent().
qboolean CG_Debriefing_Scrollbar_KeyDown (panel_button_t * button, int key)
CG_Debriefing_Scrollbar_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2463 of file cg_debriefing.c.
qboolean CG_Debriefing_Scrollbar_KeyUp (panel_button_t * button, int key)
CG_Debriefing_Scrollbar_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 2486 of file cg_debriefing.c.
void CG_Debriefing_ScrollCheckOffset (panel_button_t * button)
CG_Debriefing_ScrollCheckOffset.
Parameters
[in] button
Definition at line 2348 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent(), and CG_Debriefing_Scrollbar_Draw().
void CG_Debriefing_ScrollGetBarRect (panel_button_t * button, rectDef_t * r)
CG_Debriefing_ScrollGetBarRect.
Parameters
[in] button
[in,out] r
Definition at line 2321 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent(), CG_Debriefing_Scrollbar_Draw(), and CG_Debriefing_Scrollbar_KeyDown().
int CG_Debriefing_ScrollGetCount (panel_button_t * button)
CG_Debriefing_ScrollGetCount.
Parameters
[in] button
Returns
Definition at line 2211 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent(), CG_Debriefing_ScrollCheckOffset(), and CG_Debriefing_ScrollGetBarRect().
int CG_Debriefing_ScrollGetMax (panel_button_t * button)
CG_Debriefing_ScrollGetMax.
Parameters
[in] button
Returns
Definition at line 2188 of file cg_debriefing.c.
Referenced by CG_Debriefing_ScrollCheckOffset(), and CG_Debriefing_ScrollGetBarRect().
int CG_Debriefing_ScrollGetOffset (panel_button_t * button)
CG_Debriefing_ScrollGetOffset.
Parameters
[in] button
Returns
Definition at line 2271 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent(), CG_Debriefing_ScrollCheckOffset(), and CG_Debriefing_ScrollGetBarRect().
void CG_Debriefing_ScrollSetOffset (panel_button_t * button, int ofs)
CG_Debriefing_ScrollSetOffset.
Parameters
[in] button
[in] ofs
Definition at line 2294 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent(), and CG_Debriefing_ScrollCheckOffset().
void CG_Debriefing_Shutdown (void)
CG_Debriefing_Shutdown.
Definition at line 1568 of file cg_debriefing.c.
Referenced by CG_Draw2D().
void CG_Debriefing_Startup (void)
CG_Debriefing_Startup.
Definition at line 1518 of file cg_debriefing.c.
Referenced by CG_Debriefing_Draw().
void CG_Debriefing_TeamSkillHeaders_Draw (panel_button_t * button)
CG_Debriefing_TeamSkillHeaders_Draw.
Parameters
[in] button
Definition at line 3974 of file cg_debriefing.c.
void CG_Debriefing_TeamSkillXP_Draw (panel_button_t * button)
CG_Debriefing_TeamSkillXP_Draw.
Parameters
[in] button
Definition at line 4005 of file cg_debriefing.c.
const char* CG_Debriefing_TimeToString (float msec)
CG_Debriefing_TimeToString.
Parameters
[in] msec
Returns
Definition at line 1786 of file cg_debriefing.c.
Referenced by CG_Debriefing_MissionTitle_Draw(), and CG_DebriefingTitle_Draw().
void CG_Debriefing_VoteButton_Draw (panel_button_t * button)
CG_Debriefing_VoteButton_Draw.
Parameters
[in] button
Definition at line 3089 of file cg_debriefing.c.
qboolean CG_Debriefing_VoteButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_VoteButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3044 of file cg_debriefing.c.
const char* CG_Debriefing_WinStringForTeam (team_t team)
CG_Debriefing_WinStringForTeam.
Parameters
[in] team
Returns
Definition at line 3325 of file cg_debriefing.c.
Referenced by CG_Debriefing_Maps_Draw(), and CG_Debriefing_MissionTitle_Draw().
void CG_DebriefingPlayerList_Draw (panel_button_t * button)
CG_DebriefingPlayerList_Draw.
Parameters
[in] button
Definition at line 1908 of file cg_debriefing.c.
qboolean CG_DebriefingPlayerList_KeyDown (panel_button_t * button, int key)
CG_DebriefingPlayerList_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1703 of file cg_debriefing.c.
void CG_DebriefingPlayerWeaponStats_Draw (panel_button_t * button)
CG_DebriefingPlayerWeaponStats_Draw.
Parameters
[in] button
Definition at line 1753 of file cg_debriefing.c.
void CG_DebriefingTitle_Draw (panel_button_t * button)
CG_DebriefingTitle_Draw.
Parameters
[in] button
Note
Unused
Definition at line 1805 of file cg_debriefing.c.
void CG_DebriefingXPHeader_Draw (panel_button_t * button)
CG_DebriefingXPHeader_Draw.
Parameters
[in] button
Definition at line 1890 of file cg_debriefing.c.
void CG_Debrieing_SetSelectedClient (int clientNum)
CG_Debrieing_SetSelectedClient.
Parameters
[in] clientNum
Definition at line 2894 of file cg_debriefing.c.
Referenced by CG_Debriefing_GetSelectedClientInfo(), and CG_DebriefingPlayerList_KeyDown().
void CG_MapVote_MultiVoteButton_Draw (panel_button_t * button)
CG_MapVote_MultiVoteButton_Draw.
Parameters
[in] button
Definition at line 997 of file cg_debriefing.c.
qboolean CG_MapVote_MultiVoteButton_KeyDown (panel_button_t * button, int key)
CG_MapVote_MultiVoteButton_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1155 of file cg_debriefing.c.
void CG_MapVote_VoteButton_Draw (panel_button_t * button)
CG_MapVote_VoteButton_Draw.
Parameters
[in] button
Definition at line 1114 of file cg_debriefing.c.
qboolean CG_MapVote_VoteButton_KeyDown (panel_button_t * button, int key)
CG_MapVote_VoteButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 966 of file cg_debriefing.c.
void CG_MapVoteList_Draw (panel_button_t * button)
CG_MapVoteList_Draw.
Parameters
[in] button
Definition at line 1037 of file cg_debriefing.c.
qboolean CG_MapVoteList_KeyDown (panel_button_t * button, int key)
CG_MapVoteList_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 940 of file cg_debriefing.c.
void CG_PanelButtonsRender_Button (panel_button_t * button)
CG_PanelButtonsRender_Button.
Parameters
[in] button
Definition at line 3263 of file cg_debriefing.c.
Referenced by CG_Debriefing_NextButton_Draw(), CG_Debriefing_ReadyButton_Draw(), and CG_Debriefing_VoteButton_Draw().
void CG_PanelButtonsRender_Button_Ext (rectDef_t * r, const char * text)
CG_PanelButtonsRender_Button_Ext.
Parameters
[in] r
[in] text
Definition at line 3236 of file cg_debriefing.c.
Referenced by CG_Debriefing_ChatButton_Draw(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_VoteButton_Draw(), and CG_PanelButtonsRender_Button().
void CG_PanelButtonsRender_Window (panel_button_t * button)
CG_PanelButtonsRender_Window.
Parameters
[in] button
Definition at line 3315 of file cg_debriefing.c.
void CG_PanelButtonsRender_Window_Ext (rectDef_t * r, const char * text, int align, int innerheight, float fontscale, int yofs)
CG_PanelButtonsRender_Window_Ext.
Parameters
[in] r
[in] text
[in] align
[in] innerheight
[in] fontscale
[in] yofs
Definition at line 3277 of file cg_debriefing.c.
Referenced by CG_Debriefing_MissionTitle_Draw(), and CG_PanelButtonsRender_Window().
void CG_parseMapVoteListInfo (void)
CG_parseMapVoteListInfo.
Definition at line 4070 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_parseMapVoteTally (void)
CG_parseMapVoteTally.
Definition at line 4114 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_QuickMessage_f (void)
CG_QuickMessage_f.
Definition at line 314 of file cg_consolecmds.c.
Referenced by CG_Debriefing_ChatButton_Draw(), and CG_Debriefing_QCButton_KeyDown().
int QDECL CG_SortPlayersByXP (const void * a, const void * b)
CG_SortPlayersByXP.
Parameters
[in] a
[in] b
Returns
Definition at line 1979 of file cg_debriefing.c.
Referenced by CG_Debriefing_Draw().
int CG_TeamDebriefing_CalcXP (team_t team, int mapindex, int skillindex)
CG_TeamDebriefing_CalcXP.
Parameters
[in] team
[in] mapindex
[in] skillindex
Returns
Definition at line 3168 of file cg_debriefing.c.
Referenced by CG_Debriefing_TeamSkillXP_Draw(), and CG_TeamDebriefingTeamSkillXP_Draw().
void CG_TeamDebriefingTeamSkillXP_Draw (panel_button_t * button)
CG_TeamDebriefingTeamSkillXP_Draw.
Parameters
[in] button
Definition at line 3214 of file cg_debriefing.c.
PLAYERHEADER_SKILLS (0)
PLAYERHEADER_SKILLS (1)
PLAYERHEADER_SKILLS (2)
PLAYERHEADER_SKILLS (3)
PLAYERHEADER_SKILLS (4)
PLAYERHEADER_SKILLS (5)
PLAYERHEADER_SKILLS (6)
TDB_SKILL_ALLIES_XP (0)
TDB_SKILL_ALLIES_XP (1)
TDB_SKILL_ALLIES_XP (2)
TDB_SKILL_ALLIES_XP (3)
TDB_SKILL_ALLIES_XP (4)
TDB_SKILL_ALLIES_XP (5)
TDB_SKILL_ALLIES_XP (6)
TDB_SKILL_ALLIES_XP (7)
TDB_SKILL_AXIS_XP (0)
TDB_SKILL_AXIS_XP (1)
TDB_SKILL_AXIS_XP (2)
TDB_SKILL_AXIS_XP (3)
TDB_SKILL_AXIS_XP (4)
TDB_SKILL_AXIS_XP (5)
TDB_SKILL_AXIS_XP (6)
TDB_SKILL_AXIS_XP (7)
TDB_SKILL_TITLES_XP (0 , "Battle Sense" , 0)
TDB_SKILL_TITLES_XP (1 , "Engineer" , 1)
TDB_SKILL_TITLES_XP (2 , "Medic" , 0)
TDB_SKILL_TITLES_XP (3 , "Field Ops" , 1)
TDB_SKILL_TITLES_XP (4 , "Light Weapons" , 0)
TDB_SKILL_TITLES_XP (5 , "Soldier" , 1)
TDB_SKILL_TITLES_XP (6 , "Covert Ops" , 0)
TDB_SKILL_TITLES_XP (7 , "Total" , 1)
Variable Documentation
const char* awardNames[NUM_ENDGAME_AWARDS]
Initial value:
=
{
    "Highest Ranking Officer",
    "Highest Experience Points",
    "Most Highly Decorated",
    "Highest Fragger",
    "Highest Battle Sense",
    "Best Engineer",
    "Best Medic",
    "Best Field Ops",
    "Highest Light Weapons",
    "Best Soldier",
    "Best Covert Ops",
    "Highest Accuracy",
    "Highest Headshots Percentage",
    "Best Survivor",
    "Most Damage Given",
    "Most Gibs",
    "Most Selfkills",
    "Most Deaths",
    "I Ain't Got No Friends Award",
    "Welcome Newbie! Award",
}
Definition at line 3436 of file cg_debriefing.c.
Referenced by CG_Debriefing_Awards_Draw().
panel_button_t charPanelEdit
Initial value:
=
{
    NULL,
    "chattext",
    { 10 + 4 + 80 + 4 + 8,       SCREEN_HEIGHT - 34,             236, 16 },
    { 0,                         0,                              0,   0, 0, 0, 0, 0},
    &chatPanelButtonFont,
    NULL,
    NULL,
    CG_Debriefing_ChatEdit_Draw,
    CG_Debriefing_ChatEditFinish,
    0
}
Definition at line 913 of file cg_debriefing.c.
panel_button_t charPanelEditSurround
Initial value:
=
{
    NULL,
    NULL,
    { 10 + 4 + 80 + 4,           SCREEN_HEIGHT - 30,               252, 16 },
    { 0,                         0,                                0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Button,
    NULL,
    0
}
Definition at line 899 of file cg_debriefing.c.
panel_button_text_t chatPanelButtonFont
Initial value:
=
{
    0.20f,                 0.20f,
    { 1.f,                 1.f,              1.f,0.8f },
    0,                     ITEM_ALIGN_CENTER,
    &cgs.media.limboFont2,
}
Definition at line 793 of file cg_debriefing.c.
panel_button_t* chatPanelButtons[]
Initial value:
=
{
    &chatPanelWindow,       &chatPanelText,
    &chatPanelNextButton,   &chatPanelVoteButton,&chatPanelQCButton,  &chatTypeButton, &chatPanelReadyButton,
    &charPanelEditSurround, &charPanelEdit,
    NULL
}
Definition at line 1477 of file cg_debriefing.c.
panel_button_t chatPanelNextButton
Initial value:
=
{
    NULL,
    "MORE",
    { SCREEN_WIDTH - 10 - 60 - 4, SCREEN_HEIGHT - 30,                        60, 16 },
    { 0,                          0,                                         0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_NextButton_KeyDown,
    NULL,
    CG_Debriefing_NextButton_Draw,
    NULL,
    0
}
Definition at line 829 of file cg_debriefing.c.
panel_button_t chatPanelQCButton
Initial value:
=
{
    NULL,
    "QUICK CHAT",
    { SCREEN_WIDTH - 10 - 60 - 4 - 60 - 4 - 80 - 4,SCREEN_HEIGHT - 30,                                    80, 16 },
    { 0,                         0,                                                     0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_QCButton_KeyDown,
    NULL,
    CG_PanelButtonsRender_Button,
    NULL,
    0
}
Definition at line 857 of file cg_debriefing.c.
panel_button_t chatPanelReadyButton
Initial value:
=
{
    NULL,
    "READY",
    { SCREEN_WIDTH - 10 - 60 - 4 - 60 - 4 - 80 - 4 - 60 - 4,SCREEN_HEIGHT - 30,                                                  60, 16 },
    { 0,                           0,                                                                   0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_ReadyButton_KeyDown,
    NULL,
    CG_Debriefing_ReadyButton_Draw,
    NULL,
    0
}
Definition at line 871 of file cg_debriefing.c.
panel_button_t chatPanelText
Initial value:
=
{
    NULL,
    NULL,
    { 14,                      SCREEN_HEIGHT - 33,  SCREEN_WIDTH - 28, TEAMCHAT_HEIGHT },
    { 0,                       0,                   0,                 0, 0, 0, 0, 0   },
    NULL,
    NULL,
    NULL,
    CG_Debriefing_ChatBox_Draw,
    NULL,
    0
}
Definition at line 815 of file cg_debriefing.c.
panel_button_t chatPanelVoteButton
Initial value:
=
{
    NULL,
    "MAP VOTE",
    { SCREEN_WIDTH - 10 - 60 - 4 - 60 - 4,SCREEN_HEIGHT - 30,                             60, 16 },
    { 0,                          0,                                              0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_VoteButton_KeyDown,
    NULL,
    CG_Debriefing_VoteButton_Draw,
    NULL,
    0
}
Definition at line 843 of file cg_debriefing.c.
panel_button_t chatPanelWindow
Initial value:
=
{
    NULL,
    "CHAT",
    { 10,                        SCREEN_HEIGHT - 122,620, 112 },
    { 0,                         0,                  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 801 of file cg_debriefing.c.
panel_button_t chatTypeButton
Initial value:
=
{
    NULL,
    NULL,
    { 10 + 4,                     SCREEN_HEIGHT - 30,      80, 16 },
    { 0,                          0,                       0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_ChatButton_KeyDown,
    NULL,
    CG_Debriefing_ChatButton_Draw,
    NULL,
    0
}
Definition at line 885 of file cg_debriefing.c.
vec4_t clrSelectedClient = { 1.f, 1.f, 1.f, 0.3f } static
Definition at line 1902 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
vec4_t clrTxtBck = { 0.6f, 0.6f, 0.6f, 1.0f }
Definition at line 991 of file cg_debriefing.c.
Referenced by CG_Debriefing_Awards_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_VoteButton_Draw(), CG_PanelButtonsRender_Button_Ext(), and CG_PanelButtonsRender_Window_Ext().
panel_button_t debriefHeadingDeaths
Initial value:
=
{
    NULL,
    "Dth",
    { DB_DEATHS_X,             DH_HEADING_Y,          0, 0 },
    { 0,                       0,                     0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 393 of file cg_debriefing.c.
panel_button_t debriefHeadingGibs
Initial value:
=
{
    NULL,
    "Gib",
    { DB_GIBS_X,               DH_HEADING_Y,        0, 0 },
    { 0,                       0,                   0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 407 of file cg_debriefing.c.
panel_button_t debriefHeadingKills
Initial value:
=
{
    NULL,
    "Kll",
    { DB_KILLS_X,              DH_HEADING_Y,         0, 0 },
    { 0,                       0,                    0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 379 of file cg_debriefing.c.
panel_button_t debriefHeadingName
Initial value:
=
{
    NULL,
    "Name",
    { DB_NAME_X,               DH_HEADING_Y,       0, 0 },
    { 0,                       0,                  0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 351 of file cg_debriefing.c.
panel_button_t debriefHeadingRank
Initial value:
=
{
    NULL,
    "Rank",
    { DB_RANK_X,               DH_HEADING_Y,       0, 0 },
    { 0,                       0,                  0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 337 of file cg_debriefing.c.
panel_button_t debriefHeadingSelfKills
Initial value:
=
{
    NULL,
    "SK",
    { DB_SELFKILLS_X,          DH_HEADING_Y,              0, 0 },
    { 0,                       0,                         0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 421 of file cg_debriefing.c.
panel_button_t debriefHeadingTeamGibs
Initial value:
=
{
    NULL,
    "TG",
    { DB_TEAMGIBS_X,           DH_HEADING_Y,             0, 0 },
    { 0,                       0,                        0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 449 of file cg_debriefing.c.
panel_button_t debriefHeadingTeamKills
Initial value:
=
{
    NULL,
    "TK",
    { DB_TEAMKILLS_X,          DH_HEADING_Y,              0, 0 },
    { 0,                       0,                         0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 435 of file cg_debriefing.c.
panel_button_t debriefHeadingTime
Initial value:
=
{
    NULL,
    "Time",
    { DB_TIME_X,               DH_HEADING_Y,       0, 0 },
    { 0,                       0,                  0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 365 of file cg_debriefing.c.
panel_button_t debriefHeadingXP
Initial value:
=
{
    NULL,
    "XP",
    { DB_XP_X,                 DH_HEADING_Y,       0, 0 },
    { 0,                       0,                  0, 0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    NULL,
    NULL,
    CG_DebriefingXPHeader_Draw,
    NULL,
    0
}
Definition at line 463 of file cg_debriefing.c.
panel_button_t debriefMissionAwardsList
Initial value:
=
{
    NULL,
    NULL,
    { 215,                    44,   413, 220 },
    { ITEM_ALIGN_CENTER,      0,    0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_Debriefing_Awards_Draw,
    NULL,
    0
}
Definition at line 231 of file cg_debriefing.c.
panel_button_t debriefMissionAwardsListScroll
Initial value:
=
{
    NULL,
    NULL,
    { SCREEN_WIDTH - 10 - 8 - 16,DH_HEADING_Y,                          16, 206 },
    { 4,                         0,                                     0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_Scrollbar_KeyDown,
    CG_Debriefing_Scrollbar_KeyUp,
    CG_Debriefing_Scrollbar_Draw,
    NULL,
    0
}
Definition at line 245 of file cg_debriefing.c.
panel_button_t debriefMissionAwardsWindow
Initial value:
=
{
    NULL,
    "ROLL OF HONOR",
    { 213,                       30, 417, 240 },
    { ITEM_ALIGN_CENTER,         0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 217 of file cg_debriefing.c.
panel_button_t debriefMissionImage
Initial value:
=
{
    NULL,
    NULL,
    { 16,                      46,  186, 161 },
    { 0,                       0,   0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_Debriefing_Mission_Draw,
    NULL,
    0
}
Definition at line 189 of file cg_debriefing.c.
panel_button_t debriefMissionMaps
Initial value:
=
{
    NULL,
    NULL,
    { 12,                   210,  194, 60 },
    { 0,                    0,    0,   0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_Maps_KeyDown,
    NULL,
    CG_Debriefing_Maps_Draw,
    NULL,
    0
}
Definition at line 203 of file cg_debriefing.c.
panel_button_t debriefMissionStatsHeaders
Initial value:
=
{
    NULL,
    NULL,
    { 219,                              298,   405, 16 },
    { 0,                                0,     0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_Debriefing_TeamSkillHeaders_Draw,
    NULL,
    0
}
Definition at line 273 of file cg_debriefing.c.
panel_button_t debriefMissionStatsLoser
Initial value:
=
{
    NULL,
    NULL,
    { 219,                         330,   405, 16 },
    { 1,                           0,     0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_Debriefing_TeamSkillXP_Draw,
    NULL,
    0
}
Definition at line 301 of file cg_debriefing.c.
panel_button_t debriefMissionStatsWindow
Initial value:
=
{
    NULL,
    "MISSION STATS",
    { 213,                       280 - 6,417, 70 + 12 },
    { 0,                         0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 259 of file cg_debriefing.c.
panel_button_t debriefMissionStatsWinner
Initial value:
=
{
    NULL,
    NULL,
    { 219,                         314,   405, 16 },
    { 0,                           0,     0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_Debriefing_TeamSkillXP_Draw,
    NULL,
    0
}
Definition at line 287 of file cg_debriefing.c.
panel_button_t debriefMissionTitleWindow
Initial value:
=
{
    NULL,
    NULL,
    { 10,                        30,  198, 326 },
    { 0,                         0,   0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 175 of file cg_debriefing.c.
panel_button_t* debriefPanelButtons[]
Initial value:
=
{
    &debriefTitleWindow,
    &debriefPlayerListWindow,       &debriefPlayerList,                   &debriefPlayerListScroll,
    &debriefHeadingRank,            &debriefHeadingName,
    &debriefHeadingTime,            &debriefHeadingXP,                    &debriefHeadingKills,                &debriefHeadingDeaths,                &debriefHeadingGibs,                  &debriefHeadingSelfKills, &debriefHeadingTeamKills, &debriefHeadingTeamGibs,
    &debriefPlayerInfoWindow,       &debriefPlayerInfoName,               &debriefPlayerInfoRank,              &debriefPlayerInfoMedals,             &debriefPlayerInfoTime,               &debriefPlayerInfoXP,
    &debriefPlayerInfoACC,          &debriefPlayerInfoHS,
    &debriefPlayerInfoSkills0,
    &debriefPlayerInfoSkills1,
    &debriefPlayerInfoSkills2,
    &debriefPlayerInfoSkills3,
    &debriefPlayerInfoSkills4,
    &debriefPlayerInfoSkills5,
    &debriefPlayerInfoSkills6,
    &debriefPlayerInfoHitRegions,
    &debriefPlayerWeaponStatsHeader,&debriefPlayerWeaponStatsNameHeader,  &debriefPlayerWeaponStatsShotsHeader,&debriefPlayerWeaponStatsHitsHeader,  &debriefPlayerWeaponStatsKillsHeader,
    &debriefPlayerWeaponStatsList,  &debriefPlayerWeaponStatsListScroll,
    NULL
}
Definition at line 676 of file cg_debriefing.c.
panel_button_text_t debriefPlayerHeadingSmallerFont
Initial value:
=
{
    0.2f,                  0.2f,
    { 0.6f,                0.6f,0.6f,    1.f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 43 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoACC
Initial value:
=
{
    NULL,
    NULL,
    { 66,                        126,  0, 0 },
    { 0,                         0,    0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerACC_Draw,
    NULL,
    0
}
Definition at line 613 of file cg_debriefing.c.
panel_button_text_t debriefPlayerInfoFont
Initial value:
=
{
    0.2f,                  0.2f,
    { 0.6f,                0.6f,0.6f,    1.f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 505 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoHitRegions
Initial value:
=
{
    NULL,
    NULL,
    { 146,                              156,   0, 0 },
    { 0,                                0,     0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerHitRegions_Draw,
    NULL,
}
Definition at line 641 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoHS
Initial value:
=
{
    NULL,
    NULL,
    { 134,                      126,   0, 0 },
    { 0,                        0,     0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerHS_Draw,
    NULL,
    0
}
Definition at line 627 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoMedals
Initial value:
=
{
    NULL,
    NULL,
    { 66,                           84,  0, 0 },
    { 0,                            0,   0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerMedals_Draw,
    NULL,
    0
}
Definition at line 555 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoName
Initial value:
=
{
    NULL,
    NULL,
    { 14,                         56,  0, 0 },
    { 0,                          0,   0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerName_Draw,
    NULL,
    0
}
Definition at line 527 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoRank
Initial value:
=
{
    NULL,
    NULL,
    { 66,                         70,  0, 0 },
    { 0,                          0,   0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerRank_Draw,
    NULL,
    0
}
Definition at line 541 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoTime
Initial value:
=
{
    NULL,
    NULL,
    { 66,                         98,  0, 0 },
    { 0,                          0,   0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerTime_Draw,
    NULL,
    0
}
Definition at line 569 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoWindow
Initial value:
=
{
    NULL,
    "PLAYER STATS",
    { 10,                        30, 198, 326 },
    { 0,                         0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 513 of file cg_debriefing.c.
panel_button_t debriefPlayerInfoXP
Initial value:
=
{
    NULL,
    NULL,
    { 66,                       112,  0, 0 },
    { 0,                        0,    0, 0, 0, 0, 0, 0},
    &debriefPlayerInfoFont,
    NULL,
    NULL,
    CG_Debriefing_PlayerXP_Draw,
    NULL,
    0
}
Definition at line 583 of file cg_debriefing.c.
panel_button_t debriefPlayerList
Initial value:
=
{
    NULL,
    NULL,
    { DB_RANK_X,                 DH_HEADING_Y,         SCREEN_WIDTH - 10 - 8 - 16 - DB_RANK_X - 16, 292 },
    { 0,                         0,                    0,                                           0, 0, 0, 0, 0},
    &debriefPlayerListFont,
    CG_DebriefingPlayerList_KeyDown,
    NULL,
    CG_DebriefingPlayerList_Draw,
    NULL,
    0
}
Definition at line 477 of file cg_debriefing.c.
panel_button_text_t debriefPlayerListFont
Initial value:
=
{
    0.2f,                  0.2f,
    { 0.6f,                0.6f,0.6f,    1.f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 329 of file cg_debriefing.c.
panel_button_t debriefPlayerListScroll
Initial value:
=
{
    NULL,
    NULL,
    { SCREEN_WIDTH - 10 - 8 - 16,DH_HEADING_Y,                          16, 292 },
    { 0,                         0,                                     0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_Scrollbar_KeyDown,
    CG_Debriefing_Scrollbar_KeyUp,
    CG_Debriefing_Scrollbar_Draw,
    NULL,
    0
}
Definition at line 491 of file cg_debriefing.c.
panel_button_t debriefPlayerListWindow
Initial value:
=
{
    NULL,
    "PLAYERS",
    { 213,                       30, 417, 326 },
    { 0,                         0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 315 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsHeader
Initial value:
=
{
    NULL,
    "Weapon Stats",
    { 18,                      248,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &debriefPlayerHeadingSmallerFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 63 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsHitsHeader
Initial value:
=
{
    NULL,
    "Hits",
    { 118,                     262, 0, 0 },
    { 0,                       0,   0, 0, 0, 0, 0, 0},
    &debriefPlayerHeadingSmallerFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 105 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsKillsHeader
Initial value:
=
{
    NULL,
    "Kills",
    { 148,                     262,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &debriefPlayerHeadingSmallerFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 119 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsList
Initial value:
=
{
    NULL,
    NULL,
    { 18,                               262,  168, 80 },
    { 0,                                0,    0,   0, 0, 0, 0, 0},
    &debriefPlayerHeadingSmallerFont,
    NULL,
    NULL,
    CG_DebriefingPlayerWeaponStats_Draw,
    NULL,
    0
}
Definition at line 133 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsListScroll
Initial value:
=
{
    NULL,
    NULL,
    { 18 + 168,                  262,        16, 80 },
    { 1,                         0,          0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_Scrollbar_KeyDown,
    CG_Debriefing_Scrollbar_KeyUp,
    CG_Debriefing_Scrollbar_Draw,
    NULL,
    0
}
Definition at line 147 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsNameHeader
Initial value:
=
{
    NULL,
    "Name",
    { 18,                      262,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &debriefPlayerHeadingSmallerFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 77 of file cg_debriefing.c.
panel_button_t debriefPlayerWeaponStatsShotsHeader
Initial value:
=
{
    NULL,
    "Shots",
    { 78,                      262,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &debriefPlayerHeadingSmallerFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 91 of file cg_debriefing.c.
panel_button_t debriefTitleWindow
Initial value:
=
{
    NULL,
    NULL,
    { 10,                           4,  620, 22 },
    { 0,                            0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_Debriefing_MissionTitle_Draw,
    NULL,
    0
}
Definition at line 161 of file cg_debriefing.c.
qhandle_t img
Definition at line 2580 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerHitRegions_Draw().
qhandle_t imgA
Definition at line 2582 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerHitRegions_Draw().
qhandle_t imgB
Definition at line 2583 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerHitRegions_Draw().
qhandle_t imgH
Definition at line 2581 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerHitRegions_Draw().
qhandle_t imgL
Definition at line 2584 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerHitRegions_Draw().
panel_button_t mapVoteBorder1
Initial value:
=
{
    NULL,
    NULL,
    { DB_MAPVOTE_X2 - 10,     DB_MAPVOTE_Y - 12,                  620 - DB_MAPVOTE_X2 + 10, DB_MAPVOTE_Y2 - DB_MAPVOTE_Y - 4 },
    { 1,                      255,                                255,                      255, 40, 1, 0, 0                 },
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 1332 of file cg_debriefing.c.
panel_button_t mapVoteBorder2
Initial value:
=
{
    NULL,
    NULL,
    { DB_MAPVOTE_X2 - 10,     DB_MAPVOTE_Y2 - 10 + 2,                  620 - DB_MAPVOTE_X2 + 10, 370 - DB_MAPVOTE_Y2 - 2 - 10 },
    { 1,                      255,                                     255,                      255, 40, 1, 0, 0             },
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 1346 of file cg_debriefing.c.
panel_button_t mapVoteBorder3
Initial value:
=
{
    NULL,
    NULL,
    { 20,                     DB_MAPVOTE_Y - 12,  DB_MAPVOTE_X2 - 40 + 2, 370 - DB_MAPVOTE_Y - 10 + 2 },
    { 1,                      255,                255,                    255, 40, 1, 0, 0            },
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 1360 of file cg_debriefing.c.
panel_button_t mapVoteButton
Initial value:
=
{
    NULL,
    "^3VOTE",
    { DB_MAPNAME_X + 10,       296 - 10 + 2,             64, 16 },
    { 0,                       0,                        0,  0, 0, 0, 0, 0},
    NULL,
    CG_MapVote_VoteButton_KeyDown,
    NULL,
    CG_MapVote_VoteButton_Draw,
    NULL,
    0
}
Definition at line 1276 of file cg_debriefing.c.
panel_button_t mapVoteButton1
Initial value:
=
{
    NULL,
    "^3VOTE #1",
    { DB_MAPNAME_X + 10,            296 - 10 + 2,          64, 16 },
    { 0,                            0,                     0,  0, 0, 0, 0, 3},
    NULL,
    CG_MapVote_MultiVoteButton_KeyDown,
    NULL,
    CG_MapVote_MultiVoteButton_Draw,
    NULL,
    0
}
Definition at line 1290 of file cg_debriefing.c.
panel_button_t mapVoteButton2
Initial value:
=
{
    NULL,
    "^3VOTE #2",
    { DB_MAPNAME_X + 10,            296 + 10 + 2,          64, 16 },
    { 0,                            0,                     0,  0, 0, 0, 0, 2},
    NULL,
    CG_MapVote_MultiVoteButton_KeyDown,
    NULL,
    CG_MapVote_MultiVoteButton_Draw,
    NULL,
    0
}
Definition at line 1304 of file cg_debriefing.c.
panel_button_t mapVoteButton3
Initial value:
=
{
    NULL,
    "^3VOTE #3",
    { DB_MAPNAME_X + 10,            296 + 30 + 2,          64, 16 },
    { 0,                            0,                     0,  0, 0, 0, 0, 1},
    NULL,
    CG_MapVote_MultiVoteButton_KeyDown,
    NULL,
    CG_MapVote_MultiVoteButton_Draw,
    NULL,
    0
}
Definition at line 1318 of file cg_debriefing.c.
panel_button_t* mapVoteButtons[]
Initial value:
=
{
    &debriefTitleWindow,     &mapVoteWindow,    &mapVoteHeadingName, &mapVoteHeadingVotes,
    &mapVoteBorder1,         &mapVoteBorder2,   &mapVoteBorder3,
    &mapVoteNamesListScroll, &mapVoteNamesList, &mapVoteButton,
    &mapVoteButton1,         &mapVoteButton2,   &mapVoteButton3,
    NULL
}
Definition at line 1485 of file cg_debriefing.c.
panel_button_text_t mapVoteFont
Initial value:
=
{
    0.2f,                  0.2f,
    { 0.6f,                0.6f,0.6f,    1.f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 1212 of file cg_debriefing.c.
panel_button_t mapVoteHeadingName
Initial value:
=
{
    NULL,
    "Name",
    { DB_MAPNAME_X + 10,       DB_MAPVOTE_Y,               0, 0 },
    { 0,                       0,                          0, 0, 0, 0, 0, 0},
    &mapVoteFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 1220 of file cg_debriefing.c.
panel_button_t mapVoteHeadingVotes
Initial value:
=
{
    NULL,
    "Votes",
    { DB_MAPVOTE_X,            DB_MAPVOTE_Y,         0, 0 },
    { 0,                       0,                    0, 0, 0, 0, 0, 0},
    &mapVoteFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 1234 of file cg_debriefing.c.
panel_button_t mapVoteNamesList
Initial value:
=
{
    NULL,
    NULL,
    { DB_MAPNAME_X + 10,DB_MAPVOTE_Y,                 250, 17 * 12 },
    { 0,                0,                            0,   0, 0, 0, 0, 0},
    &mapVoteFont,
    CG_MapVoteList_KeyDown,
    NULL,
    CG_MapVoteList_Draw,
    NULL,
    0
}
Definition at line 1248 of file cg_debriefing.c.
panel_button_t mapVoteNamesListScroll
Initial value:
=
{
    NULL,
    NULL,
    { DB_MAPVOTE_X + 10 + 48,    DB_MAPVOTE_Y + 2,                      16, 17 * 12 },
    { 3,                         0,                                     0,  0, 0, 0, 0, 0},
    NULL,
    CG_Debriefing_Scrollbar_KeyDown,
    CG_Debriefing_Scrollbar_KeyUp,
    CG_Debriefing_Scrollbar_Draw,
    NULL,
    0
}
Definition at line 1262 of file cg_debriefing.c.
panel_button_t mapVoteWindow
Initial value:
=
{
    NULL,
    "MAP VOTE",
    { 10,                        30, 620, 326 },
    { 0,                         0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_PanelButtonsRender_Window,
    NULL,
    0
}
Definition at line 1198 of file cg_debriefing.c.
const int skillPositions[SK_NUM_SKILLS+1]
Initial value:
=
{
    0,
    55,
    110,
    150,
    200,
    250,
    290,
    330,
}
Definition at line 3958 of file cg_debriefing.c.
Referenced by CG_Debriefing_TeamSkillHeaders_Draw(), and CG_Debriefing_TeamSkillXP_Draw().
panel_button_t* teamDebriefPanelButtons[]
Initial value:
=
{
    &debriefTitleWindow,        &debriefMissionTitleWindow, &debriefMissionAwardsWindow, &debriefMissionImage,        &debriefMissionMaps, &debriefMissionAwardsList, &debriefMissionAwardsListScroll,
    &debriefMissionStatsWindow, &debriefMissionStatsWinner, &debriefMissionStatsLoser,   &debriefMissionStatsHeaders,
    NULL
}
Definition at line 786 of file cg_debriefing.c.
panel_button_text_t teamDebriefTitle
Initial value:
=
{
    0.28f,                 0.28f,
    { 1.f,                 1.f,  1.f,0.8f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 709 of file cg_debriefing.c.
panel_button_text_t teamDebriefTitleSmall
Initial value:
=
{
    0.24f,                 0.24f,
    { 1.f,                 1.f,              1.f,0.8f },
    0,                     ITEM_ALIGN_CENTER,
    &cgs.media.limboFont2,
}
Definition at line 701 of file cg_debriefing.c.