ET: Legacy: src/cgame/cg_limbopanel.c File Reference
cg_limbopanel.c File Reference
#include "cg_local.h"
Macros
#define SOUNDEVENT(sound) trap_S_StartLocalSound(sound, CHAN_LOCAL_SOUND)
#define SOUND_SELECT SOUNDEVENT(cgs.media.sndLimboSelect)
#define SOUND_FILTER SOUNDEVENT(cgs.media.sndLimboFilter)
#define MEDAL_PIC_GAP ((MEDAL_PIC_SIZE - (MEDAL_PIC_WIDTH * MEDAL_PIC_COUNT)) / (MEDAL_PIC_COUNT + 1.f))
#define MEDAL_PIC_COUNT 7.f
#define MEDAL_PIC_WIDTH 22.f
#define MEDAL_PIC_X 450.f
#define MEDAL_PIC_SIZE (630.f - MEDAL_PIC_X)
#define MEDAL_PIC(number)
#define TEAM_COUNTER_GAP ((TEAM_COUNTER_SIZE - (TEAM_COUNTER_WIDTH * TEAM_COUNTER_COUNT)) / (TEAM_COUNTER_COUNT + 1.f))
#define TEAM_COUNTER_COUNT 3.f
#define TEAM_COUNTER_WIDTH 20.f
#define TEAM_COUNTER_X 432.f
#define TEAM_COUNTER_SIZE (660.f - TEAM_COUNTER_X)
#define TEAM_COUNTER_BUTTON_DIFF (-24.f)
#define TEAM_COUNTER_SPACING 4.f
#define TEAM_COUNTER(number)
#define CLASS_COUNTER_GAP ((CLASS_COUNTER_SIZE - (CLASS_COUNTER_WIDTH * CLASS_COUNTER_COUNT)) / (CLASS_COUNTER_COUNT + 1.f))
#define CLASS_COUNTER_COUNT 5.f
#define CLASS_COUNTER_WIDTH 20.f
#define CLASS_COUNTER_X 435.f
#define CLASS_COUNTER_SIZE (645.f - CLASS_COUNTER_X)
#define CLASS_COUNTER_BUTTON_DIFF (-18.f)
#define CLASS_COUNTER(number)
#define FILTER_BUTTON(number)
#define LEFT_FRAME(shader, number, x, y, w, h)
#define LF_X1 64
#define LF_X2 416
#define LF_X3 440
#define LF_W1 (LF_X1 - 0)
#define LF_W2 (LF_X2 - LF_X1)
#define LF_W3 (LF_X3 - LF_X2)
#define LF_Y1 23
#define LF_Y2 375
#define LF_Y3 SCREEN_HEIGHT
#define LF_H1 (LF_Y1 - 0)
#define LF_H2 (LF_Y2 - LF_Y1)
#define LF_H3 (LF_Y3 - LF_Y2)
#define BRDRSIZE 4
#define MAX_ROLLERS 8
#define COUNTER_ROLLTOTAL (cg.time - button->data[4])
Functions
void CG_DrawBorder (float x, float y, float w, float h, qboolean fill, qboolean drawMouseOver)
CG_DrawBorder.
MEDAL_PIC (0)
MEDAL_PIC (1)
MEDAL_PIC (2)
MEDAL_PIC (3)
MEDAL_PIC (4)
MEDAL_PIC (5)
MEDAL_PIC (6)
TEAM_COUNTER (0)
TEAM_COUNTER (1)
TEAM_COUNTER (2)
CLASS_COUNTER (0)
CLASS_COUNTER (1)
CLASS_COUNTER (2)
CLASS_COUNTER (3)
CLASS_COUNTER (4)
FILTER_BUTTON (0)
FILTER_BUTTON (1)
FILTER_BUTTON (2)
FILTER_BUTTON (3)
FILTER_BUTTON (4)
FILTER_BUTTON (5)
FILTER_BUTTON (6)
FILTER_BUTTON (7)
FILTER_BUTTON (8)
LEFT_FRAME ("gfx/limbo/limbo_frame01", 1, 0, 0, LF_W1, LF_H1)
LEFT_FRAME ("gfx/limbo/limbo_frame02", 2, LF_X1, 0, LF_W2, LF_H1)
LEFT_FRAME ("gfx/limbo/limbo_frame03", 3, LF_X2, 0, LF_W3, LF_H1)
LEFT_FRAME ("gfx/limbo/limbo_frame04", 4, LF_X2, LF_Y1, LF_W3, LF_H2)
LEFT_FRAME ("gfx/limbo/limbo_frame05", 5, LF_X2, LF_Y2, LF_W3, LF_H3)
LEFT_FRAME ("gfx/limbo/limbo_frame06", 6, LF_X1, LF_Y2, LF_W2, LF_H3)
LEFT_FRAME ("gfx/limbo/limbo_frame07", 7, 0, LF_Y2, LF_W1, LF_H3)
LEFT_FRAME ("gfx/limbo/limbo_frame08", 8, 0, LF_Y1, LF_W1, LF_H2)
qboolean CG_LimboPanel_SpawnPointButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_SpawnPointButton_KeyDown.
qboolean CG_LimboPanel_BriefingButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_BriefingButton_KeyDown.
void CG_LimboPanel_SpawnPointButton_Draw (panel_button_t *button)
CG_LimboPanel_SpawnPointButton_Draw.
void CG_LimboPanel_BriefingButton_Draw (panel_button_t *button)
CG_LimboPanel_BriefingButton_Draw.
void CG_LimboPanel_NameEditFinish (panel_button_t *button)
CG_LimboPanel_NameEditFinish.
qboolean CG_LimboPanel_CancelButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_CancelButton_KeyDown.
qboolean CG_LimboPanel_PlusButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_PlusButton_KeyDown.
qboolean CG_LimboPanel_MinusButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_MinusButton_KeyDown.
void CG_LimboPanel_SendSetupMsg (qboolean forceteam)
CG_LimboPanel_SendSetupMsg.
qboolean CG_LimboPanel_OkButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_OkButton_KeyDown.
qboolean CG_LimboPanel_TeamButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_TeamButton_KeyDown.
void CG_LimboPanel_RenderTeamButton (panel_button_t *button)
CG_LimboPanel_RenderTeamButton.
qboolean CG_LimboPanel_ClassButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_ClassButton_KeyDown.
void CG_LimboPanel_ClassBar_Draw (panel_button_t *button)
CG_LimboPanel_ClassBar_Draw.
void CG_LimboPanel_RenderClassButton (panel_button_t *button)
CG_LimboPanel_RenderClassButton.
int CG_LimboPanel_GetMaxObjectives (void)
CG_LimboPanel_GetMaxObjectives.
qboolean CG_LimboPanel_ObjectiveText_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_ObjectiveText_KeyDown.
void CG_LimboPanel_RenderObjectiveText (panel_button_t *button)
void CG_LimboPanel_RenderObjectiveBack (panel_button_t *button)
CG_LimboPanel_RenderObjectiveBack.
void CG_LimboPanel_RenderCommandMap (panel_button_t *button)
CG_LimboPanel_RenderCommandMap.
qboolean CG_LimboPanel_RenderLight_GetValue (panel_button_t *button)
CG_LimboPanel_RenderLight_GetValue.
void CG_LimboPanel_RenderLight (panel_button_t *button)
CG_LimboPanel_RenderLight.
void CG_DrawPlayerHead (rectDef_t *rect, bg_character_t *character, bg_character_t *headcharacter, float yaw, float pitch, qboolean drawHat, hudHeadAnimNumber_t animation, qhandle_t painSkin, int rank, qboolean spectator, int team)
CG_DrawPlayerHead.
void CG_LimboPanel_RenderHead (panel_button_t *button)
CG_LimboPanel_RenderHead.
qboolean CG_LimboPanel_Filter_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_Filter_KeyDown.
void CG_LimboPanel_Filter_Draw (panel_button_t *button)
CG_LimboPanel_Filter_Draw.
void CG_LimboPanel_RenderSkillIcon (panel_button_t *button)
CG_LimboPanel_RenderSkillIcon.
qboolean CG_LimboPanel_WeaponLights_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_WeaponLights_KeyDown.
void CG_LimboPanel_WeaponLights (panel_button_t *button)
CG_LimboPanel_WeaponLights.
qboolean CG_LimboPanel_WeaponPanel_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_WeaponPanel_KeyDown.
qboolean CG_LimboPanel_WeaponPanel_KeyUp (panel_button_t *button, int key)
CG_LimboPanel_WeaponPanel_KeyUp.
void CG_LimboPanel_WeaponPanel_DrawWeapon (rectDef_t *rect, weapon_t weap, qboolean highlight, const char *ofTxt, qboolean disabled)
CG_LimboPanel_WeaponPanel_DrawWeapon.
void CG_LimboPanel_Border_Draw (panel_button_t *button)
CG_LimboPanel_Border_Draw.
void CG_LimboPanel_WeaponPanel (panel_button_t *button)
CG_LimboPanel_WeaponPanel.
void CG_LimboPanel_RenderCounterNumber (float x, float y, float w, float h, float number, qhandle_t shaderBack, qhandle_t shaderRoll, int numbuttons)
CG_LimboPanel_RenderCounterNumber.
int CG_LimboPanel_RenderCounter_ValueForButton (panel_button_t *button)
CG_LimboPanel_RenderCounter_ValueForButton.
int CG_LimboPanel_RenderCounter_RollTimeForButton (panel_button_t *button)
CG_LimboPanel_RenderCounter_RollTimeForButton.
int CG_LimboPanel_RenderCounter_MaxChangeForButton (panel_button_t *button)
CG_LimboPanel_RenderCounter_MaxChangeForButton.
int CG_LimboPanel_RenderCounter_NumRollers (panel_button_t *button)
CG_LimboPanel_RenderCounter_NumRollers.
qboolean CG_LimboPanel_RenderCounter_CountsDown (panel_button_t *button)
CG_LimboPanel_RenderCounter_CountsDown.
qboolean CG_LimboPanel_RenderCounter_CountsUp (panel_button_t *button)
CG_LimboPanel_RenderCounter_CountsUp.
qboolean CG_LimboPanel_RenderCounter_StartSet (panel_button_t *button)
CG_LimboPanel_RenderCounter_StartSet.
void CG_LimboPanel_RenderMedal (panel_button_t *button)
CG_LimboPanel_RenderMedal.
qboolean CG_LimboPanel_RenderCounter_IsReversed (panel_button_t *button)
CG_LimboPanel_RenderCounter_IsReversed.
void CG_LimboPanel_RenderCounter_GetShaders (panel_button_t *button, qhandle_t *shaderBack, qhandle_t *shaderRoll, int *numimages)
CG_LimboPanel_RenderCounter_GetShaders.
void CG_LimboPanelRenderText_NoLMS (panel_button_t *button)
CG_LimboPanelRenderText_NoLMS.
void CG_LimboPanelRenderText_SkillsText (panel_button_t *button)
CG_LimboPanelRenderText_SkillsText.
void CG_LimboPanel_RenderCounter (panel_button_t *button)
CG_LimboPanel_RenderCounter.
void CG_LimboPanel_Setup (void)
CG_LimboPanel_Setup.
void CG_LimboPanel_Init (void)
CG_LimboPanel_Init.
qboolean CG_LimboPanel_Draw (void)
CG_LimboPanel_Draw.
void CG_LimboPanel_KeyHandling (int key, qboolean down)
CG_LimboPanel_KeyHandling.
int CG_LimboPanel_GetSpawnPoint (void)
CG_LimboPanel_GetSpawnPoint.
team_t CG_LimboPanel_GetTeam (void)
CG_LimboPanel_GetTeam.
team_t CG_LimboPanel_GetRealTeam (void)
CG_LimboPanel_GetRealTeam.
int CG_LimboPanel_GetClass (void)
CG_LimboPanel_GetClass.
bg_character_t * CG_LimboPanel_GetCharacter (void)
CG_LimboPanel_GetCharacter.
bg_playerclass_t * CG_LimboPanel_GetPlayerClass (void)
CG_LimboPanel_GetPlayerClass.
int CG_LimboPanel_WeaponCount (int slotNumber)
CG_LimboPanel_WeaponCount.
qboolean CG_LimboPanel_IsValidSelectedWeapon (int slot)
CG_LimboPanel_IsValidSelectedWeapon.
void CG_LimboPanel_SetDefaultWeapon (int slot)
CG_LimboPanel_SetSelectedDefaultWeapon.
weapon_t CG_LimboPanel_GetSelectedWeapon (int slot)
CG_LimboPanel_GetSelectedWeapon.
void CG_LimboPanel_RequestWeaponStats (void)
CG_LimboPanel_RequestWeaponStats.
void CG_LimboPanel_RequestObjective (void)
CG_LimboPanel_RequestObjective.
void CG_LimboPanel_SetSelectedWeaponNum (int slot, weapon_t weapon)
CG_LimboPanel_SetSelectedWeaponNum.
int CG_LimboPanel_TeamCount (int weap)
CG_LimboPanel_TeamCount.
int ExtractInt (const char *src)
Convert a string to an integer.
int CG_LimboPanel_MaxCount (int playerCount, const char *variableString)
CG_LimboPanel_MaxCount.
qboolean CG_LimboPanel_RealWeaponIsDisabled (weapon_t weapon)
Checks for heavy and rifle weapons.
int CG_LimboPanel_ClassCount (team_t checkTeam, int classIndex)
CG_LimboPanel_ClassCount.
qboolean CG_LimboPanel_ClassIsDisabled (team_t selectedTeam, int classIndex)
CG_LimboPanel_ClassIsDisabled.
qboolean CG_LimboPanel_TeamIsFull (team_t checkTeam)
CG_LimboPanel_TeamIsFull.
qboolean CG_LimboPanel_TeamIsDisabled (team_t checkTeam)
CG_LimboPanel_TeamIsDisabled.
int CG_LimboPanel_FindFreeClass (team_t checkTeam)
CG_LimboPanel_FindFreeClass.
Variables
static team_t teamOrder [3]
static panel_button_text_t nameEditFont
static panel_button_text_t classBarFont
static panel_button_text_t titleLimboFont
static panel_button_text_t titleLimboFontBigCenter
static panel_button_text_t spawnLimboFont
static panel_button_text_t weaponButtonFont
static panel_button_text_t weaponPanelNameFont
static panel_button_text_t weaponPanelFilterFont
static panel_button_text_t weaponPanelStatsFont
static panel_button_text_t weaponPanelStatsPercFont
static panel_button_text_t objectivePanelTxt
static panel_button_t rightLimboPannel
static panel_button_t classBar
static panel_button_t classBarText
static panel_button_t filterTitleText
static panel_button_t playerLimboHead
static panel_button_t playerXPCounterText
static panel_button_t playerXPCounter
static panel_button_t playerSkillCounter0
static panel_button_t playerSkillCounter1
static panel_button_t playerSkillCounter2
static panel_button_t playerSkillIcon0
static panel_button_t playerSkillIcon1
static panel_button_t playerSkillIcon2
static panel_button_t spawnPointText
static panel_button_t spawnPointButton
static panel_button_t mapTimeCounter
static panel_button_t mapTimeCounter2
static panel_button_t mapTimeCounterText
static panel_button_t respawnCounter
static panel_button_t respawnCounterText
static panel_button_t limboTitleText
static panel_button_t playerSetupText
static panel_button_t skillsText
static panel_button_t weaponPanel
static panel_button_t weaponLight1
static panel_button_t weaponLight1Text
static panel_button_t weaponLight2
static panel_button_t weaponLight2Text
static panel_button_t weaponStatsShotsText
static panel_button_t weaponStatsShotsCounter
static panel_button_t weaponStatsHitsText
static panel_button_t weaponStatsHitsCounter
static panel_button_t weaponStatsAccText
static panel_button_t weaponStatsAccCounter
static panel_button_t weaponStatsAccPercentage
static panel_button_t commandmapPanel
static panel_button_t objectivePanel
static panel_button_t objectivePanelText
static panel_button_t objectivePanelTitle
static panel_button_t objectivePanelButtonUp
static panel_button_t briefingButton
static panel_button_t objectivePanelButtonDown
static panel_button_t okButtonText
static panel_button_t okButton
static panel_button_t cancelButtonText
static panel_button_t cancelButton
static panel_button_t nameEdit
static panel_button_t plusButton
static panel_button_t plusButtonText
static panel_button_t minusButton
static panel_button_t minusButtonText
static panel_button_t * limboPanelButtons []
static vec4_t clrRenderTeamButton2 = { 1.f, 1.f, 1.f, 0.4f }
static vec4_t clrRenderTeamButton4 = { 1.f, 0.f, 0.f, 0.75f }
static vec4_t clrRenderClassButton = { 1.f, 1.f, 1.f, 0.4f }
static vec4_t clrRenderClassButton2 = { 1.f, 1.f, 1.f, 0.75f }
static vec4_t clrRenderClassButton3 = { 1.f, 1.f, 1.f, 0.6f }
static vec4_t clrRenderClassButton4 = { 1.f, 0.f, 0.f, 0.5f }
static vec4_t clrDrawWeapon = { 1.f, 1.f, 1.f, 0.6f }
static vec4_t clrBackBorder = { 0.1f, 0.1f, 0.1f, 1.f }
static vec4_t clrBackBorder2 = { 0.2f, 0.2f, 0.2f, 1.f }
static vec4_t clrWeaponPanel = { 0.f, 0.f, 0.f, 0.4f }
static vec4_t clrWeaponPanel2 = { 1.f, 1.f, 1.f, 0.4f }
Macro Definition Documentation
#define BRDRSIZE 4
Definition at line 2461 of file cg_limbopanel.c.
Referenced by CG_DrawBorder().
#define CLASS_COUNTER (number)
Value:
static panel_button_t classCounter ## number = {     \
        NULL,                                   \
        NULL,                                   \
        { CLASS_COUNTER_X + CLASS_COUNTER_GAP + ((number) * (CLASS_COUNTER_GAP + CLASS_COUNTER_WIDTH)),302,                                                                                           CLASS_COUNTER_WIDTH, 14 }, \
        { 0,                         number,                                                                                        0,                   0, 0, 0, 0, 0},        \
        NULL,                        /* font       */              \
        NULL,                        /* keyDown    */                  \
        NULL,                        /* keyUp  */                  \
        CG_LimboPanel_RenderCounter,            \
        NULL,                                   \
        0,                                      \
    };                                          \
    static panel_button_t classButton ## number = {      \
        NULL,                                   \
        NULL,                                   \
        { CLASS_COUNTER_X + CLASS_COUNTER_GAP + ((number) * (CLASS_COUNTER_GAP + CLASS_COUNTER_WIDTH)) + (CLASS_COUNTER_BUTTON_DIFF / 2.f),266,                                                                                                                               CLASS_COUNTER_WIDTH - CLASS_COUNTER_BUTTON_DIFF, 34 },   \
        { 0,                             number,                                                                                                                            0,                                               0, 0, 0, 0, 0},        \
        NULL,                            /* font       */              \
        CG_LimboPanel_ClassButton_KeyDown,/* keyDown   */  \
        NULL,                            /* keyUp  */                  \
        CG_LimboPanel_RenderClassButton,        \
        NULL,                                   \
        0,                                      \
    }
Definition at line 251 of file cg_limbopanel.c.
#define CLASS_COUNTER_BUTTON_DIFF (-18.f)
Definition at line 250 of file cg_limbopanel.c.
#define CLASS_COUNTER_COUNT 5.f
Definition at line 245 of file cg_limbopanel.c.
#define CLASS_COUNTER_GAP ((CLASS_COUNTER_SIZE - (CLASS_COUNTER_WIDTH * CLASS_COUNTER_COUNT)) / (CLASS_COUNTER_COUNT + 1.f))
Definition at line 244 of file cg_limbopanel.c.
#define CLASS_COUNTER_SIZE (645.f - CLASS_COUNTER_X)
Definition at line 248 of file cg_limbopanel.c.
#define CLASS_COUNTER_WIDTH 20.f
Definition at line 246 of file cg_limbopanel.c.
#define CLASS_COUNTER_X 435.f
Definition at line 247 of file cg_limbopanel.c.
#define COUNTER_ROLLTOTAL (cg.time - button->data[4])
Definition at line 3030 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
#define FILTER_BUTTON (number)
Value:
static panel_button_t filterButton ## number = { \
        NULL,                               \
        NULL,                               \
        { 14,                      50 + ((number) * 30), 26, 26 },     \
        { number,                  0,                    0,  0, 0, 0, 0, 0},    \
        NULL,                      /* font       */          \
        CG_LimboPanel_Filter_KeyDown,/* keyDown    */              \
        NULL,                      /* keyUp  */              \
        CG_LimboPanel_Filter_Draw,          \
        NULL,                               \
        0,                                  \
    }
Definition at line 311 of file cg_limbopanel.c.
#define LEFT_FRAME (shader, number, x, y, w, h)
Value:
static panel_button_t leftFrame0 ## number = {   \
        shader,                             \
        NULL,                               \
        { x,                       y, w, h },                     \
        { 0,                       0, 0, 0, 0, 0, 0, 0},         \
        NULL,                      /* font       */          \
        NULL,                      /* keyDown    */              \
        NULL,                      /* keyUp  */              \
        BG_PanelButtonsRender_Img,          \
        NULL,                               \
        0,                                  \
    }
Definition at line 349 of file cg_limbopanel.c.
#define LF_H1 (LF_Y1 - 0)
Definition at line 375 of file cg_limbopanel.c.
#define LF_H2 (LF_Y2 - LF_Y1)
Definition at line 376 of file cg_limbopanel.c.
#define LF_H3 (LF_Y3 - LF_Y2)
Definition at line 377 of file cg_limbopanel.c.
#define LF_W1 (LF_X1 - 0)
Definition at line 367 of file cg_limbopanel.c.
#define LF_W2 (LF_X2 - LF_X1)
Definition at line 368 of file cg_limbopanel.c.
#define LF_W3 (LF_X3 - LF_X2)
Definition at line 369 of file cg_limbopanel.c.
#define LF_X1 64
Definition at line 363 of file cg_limbopanel.c.
#define LF_X2 416
Definition at line 364 of file cg_limbopanel.c.
#define LF_X3 440
Definition at line 365 of file cg_limbopanel.c.
#define LF_Y1 23
Definition at line 371 of file cg_limbopanel.c.
#define LF_Y2 375
Definition at line 372 of file cg_limbopanel.c.
#define LF_Y3 SCREEN_HEIGHT
Definition at line 373 of file cg_limbopanel.c.
#define MAX_ROLLERS 8
Definition at line 3029 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
#define MEDAL_PIC (number)
Value:
static panel_button_t medalPic ## number = {         \
        NULL,                                   \
        NULL,                                   \
        { MEDAL_PIC_X + MEDAL_PIC_GAP + ((number) * (MEDAL_PIC_GAP + MEDAL_PIC_WIDTH)),119,                                                                           MEDAL_PIC_WIDTH, 26 }, \
        { number,                  0,                                                                             0,               0, 0, 0, 0, 0},        \
        NULL,                      /* font       */              \
        NULL,                      /* keyDown    */                  \
        NULL,                      /* keyUp  */                  \
        CG_LimboPanel_RenderMedal,              \
        NULL,                                   \
        0,                                   \
    }
Definition at line 169 of file cg_limbopanel.c.
#define MEDAL_PIC_COUNT 7.f
Definition at line 165 of file cg_limbopanel.c.
#define MEDAL_PIC_GAP ((MEDAL_PIC_SIZE - (MEDAL_PIC_WIDTH * MEDAL_PIC_COUNT)) / (MEDAL_PIC_COUNT + 1.f))
Definition at line 164 of file cg_limbopanel.c.
#define MEDAL_PIC_SIZE (630.f - MEDAL_PIC_X)
Definition at line 168 of file cg_limbopanel.c.
#define MEDAL_PIC_WIDTH 22.f
Definition at line 166 of file cg_limbopanel.c.
#define MEDAL_PIC_X 450.f
Definition at line 167 of file cg_limbopanel.c.
#define SOUND_FILTER SOUNDEVENT(cgs.media.sndLimboFilter)
Definition at line 40 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Filter_KeyDown().
#define SOUND_SELECT SOUNDEVENT(cgs.media.sndLimboSelect)
Definition at line 39 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_MinusButton_KeyDown(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_OkButton_KeyDown(), CG_LimboPanel_PlusButton_KeyDown(), CG_LimboPanel_SpawnPointButton_KeyDown(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponLights_KeyDown(), and CG_LimboPanel_WeaponPanel_KeyDown().
#define SOUNDEVENT (sound) trap_S_StartLocalSound(sound, CHAN_LOCAL_SOUND)
Definition at line 37 of file cg_limbopanel.c.
#define TEAM_COUNTER (number)
Definition at line 199 of file cg_limbopanel.c.
#define TEAM_COUNTER_BUTTON_DIFF (-24.f)
Definition at line 196 of file cg_limbopanel.c.
#define TEAM_COUNTER_COUNT 3.f
Definition at line 192 of file cg_limbopanel.c.
#define TEAM_COUNTER_GAP ((TEAM_COUNTER_SIZE - (TEAM_COUNTER_WIDTH * TEAM_COUNTER_COUNT)) / (TEAM_COUNTER_COUNT + 1.f))
Definition at line 191 of file cg_limbopanel.c.
#define TEAM_COUNTER_SIZE (660.f - TEAM_COUNTER_X)
Definition at line 195 of file cg_limbopanel.c.
#define TEAM_COUNTER_SPACING 4.f
Definition at line 197 of file cg_limbopanel.c.
#define TEAM_COUNTER_WIDTH 20.f
Definition at line 193 of file cg_limbopanel.c.
#define TEAM_COUNTER_X 432.f
Definition at line 194 of file cg_limbopanel.c.
Function Documentation
void CG_DrawBorder (float x, float y, float w, float h, qboolean fill, qboolean drawMouseOver)
CG_DrawBorder.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] fill
[in] drawMouseOver
Definition at line 2472 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Border_Draw(), and CG_LimboPanel_WeaponPanel().
void CG_DrawPlayerHead (rectDef_t * rect, bg_character_t * character, bg_character_t * headcharacter, float yaw, float pitch, qboolean drawHat, hudHeadAnimNumber_t animation, qhandle_t painSkin, int rank, qboolean spectator, int team)
CG_DrawPlayerHead.
Parameters
[in] rect
[in] character
[in] headcharacter
[in] yaw
[in] pitch
[in] drawHat
[in] animation
[in] painSkin
[in] rank
[in] spectator - unused
[in] team
Definition at line 2016 of file cg_limbopanel.c.
Referenced by CG_DrawPlayerStatusHead(), and CG_LimboPanel_RenderHead().
void CG_LimboPanel_Border_Draw (panel_button_t * button)
CG_LimboPanel_Border_Draw.
Parameters
[in] button
Definition at line 2517 of file cg_limbopanel.c.
void CG_LimboPanel_BriefingButton_Draw (panel_button_t * button)
CG_LimboPanel_BriefingButton_Draw.
Parameters
[in] button
Definition at line 1202 of file cg_limbopanel.c.
qboolean CG_LimboPanel_BriefingButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_BriefingButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1155 of file cg_limbopanel.c.
qboolean CG_LimboPanel_CancelButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_CancelButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1239 of file cg_limbopanel.c.
void CG_LimboPanel_ClassBar_Draw (panel_button_t * button)
CG_LimboPanel_ClassBar_Draw.
Parameters
[in] button
Definition at line 1585 of file cg_limbopanel.c.
qboolean CG_LimboPanel_ClassButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_ClassButton_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1546 of file cg_limbopanel.c.
int CG_LimboPanel_ClassCount (team_t checkTeam, int classIndex)
CG_LimboPanel_ClassCount.
Parameters
[in] checkTeam
[in] classIndex
Returns
Definition at line 3856 of file cg_limbopanel.c.
Referenced by CG_IsClassFull(), and CG_LimboPanel_ClassIsDisabled().
qboolean CG_LimboPanel_ClassIsDisabled (team_t selectedTeam, int classIndex)
CG_LimboPanel_ClassIsDisabled.
Parameters
[in] selectedTeam
[in] classIndex
Returns
Definition at line 3894 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_FindFreeClass(), CG_LimboPanel_RenderClassButton(), and CG_LimboPanel_TeamButton_KeyDown().
qboolean CG_LimboPanel_Draw (void)
CG_LimboPanel_Draw.
Returns
Definition at line 3263 of file cg_limbopanel.c.
Referenced by CG_DrawActive().
void CG_LimboPanel_Filter_Draw (panel_button_t * button)
CG_LimboPanel_Filter_Draw.
Parameters
[in] button
Definition at line 2237 of file cg_limbopanel.c.
qboolean CG_LimboPanel_Filter_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_Filter_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2220 of file cg_limbopanel.c.
int CG_LimboPanel_FindFreeClass (team_t checkTeam)
CG_LimboPanel_FindFreeClass.
Parameters
[in] checkTeam
Returns
Definition at line 4006 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_TeamButton_KeyDown(), and CG_LimboPanel_TeamIsDisabled().
bg_character_t* CG_LimboPanel_GetCharacter (void)
CG_LimboPanel_GetCharacter.
Returns
Definition at line 3386 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderHead().
int CG_LimboPanel_GetClass (void)
CG_LimboPanel_GetClass.
Returns
Definition at line 3377 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_GetCharacter(), CG_LimboPanel_GetPlayerClass(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderLight_GetValue(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanel_SendSetupMsg(), and CG_LimboPanel_TeamButton_KeyDown().
int CG_LimboPanel_GetMaxObjectives (void)
CG_LimboPanel_GetMaxObjectives.
Returns
Definition at line 1770 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Draw(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_Setup(), and CG_LimboPanel_TeamButton_KeyDown().
bg_playerclass_t* CG_LimboPanel_GetPlayerClass (void)
CG_LimboPanel_GetPlayerClass.
Returns
Definition at line 3395 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassIsDisabled(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_WeaponCount(), and CG_LimboPanel_WeaponPanel().
team_t CG_LimboPanel_GetRealTeam (void)
CG_LimboPanel_GetRealTeam.
Returns
Definition at line 3368 of file cg_limbopanel.c.
Referenced by CG_CommandCentreSpawnPointClick(), CG_DrawMap(), CG_DrawSpawnPointInfo(), CG_LimboPanel_ClassIsDisabled(), and CG_LimboPanel_RenderCounter_ValueForButton().
weapon_t CG_LimboPanel_GetSelectedWeapon (int slot)
CG_LimboPanel_GetSelectedWeapon.
Returns
Definition at line 3577 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_RequestWeaponStats(), and CG_LimboPanel_WeaponPanel().
int CG_LimboPanel_GetSpawnPoint (void)
CG_LimboPanel_GetSpawnPoint.
Returns
Definition at line 3350 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_SpawnPointButton_Draw().
team_t CG_LimboPanel_GetTeam (void)
CG_LimboPanel_GetTeam.
Returns
Definition at line 3359 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_Draw(), CG_LimboPanel_GetCharacter(), CG_LimboPanel_GetMaxObjectives(), CG_LimboPanel_GetPlayerClass(), CG_LimboPanel_GetRealTeam(), CG_LimboPanel_RealWeaponIsDisabled(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderLight_GetValue(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_TeamCount(), CG_LimboPanel_WeaponLights(), CG_LimboPanel_WeaponLights_KeyDown(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_KeyDown(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_Init (void)
CG_LimboPanel_Init.
Definition at line 3253 of file cg_limbopanel.c.
Referenced by CG_RegisterGraphics().
qboolean CG_LimboPanel_IsValidSelectedWeapon (int slot)
CG_LimboPanel_IsValidSelectedWeapon.
Parameters
[in] slot
Returns
Definition at line 3461 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_KeyHandling (int key, qboolean down)
CG_LimboPanel_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 3316 of file cg_limbopanel.c.
Referenced by CG_KeyEvent().
int CG_LimboPanel_MaxCount (int playerCount, const char * variableString)
CG_LimboPanel_MaxCount.
Parameters
[in] playerCount
[in] variableString
Returns
Definition at line 3753 of file cg_limbopanel.c.
Referenced by CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_ClassIsDisabled(), and CG_LimboPanel_RealWeaponIsDisabled().
qboolean CG_LimboPanel_MinusButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_MinusButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1291 of file cg_limbopanel.c.
void CG_LimboPanel_NameEditFinish (panel_button_t * button)
CG_LimboPanel_NameEditFinish.
Parameters
button
Definition at line 1223 of file cg_limbopanel.c.
qboolean CG_LimboPanel_ObjectiveText_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_ObjectiveText_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1786 of file cg_limbopanel.c.
qboolean CG_LimboPanel_OkButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_OkButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1412 of file cg_limbopanel.c.
qboolean CG_LimboPanel_PlusButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_PlusButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1266 of file cg_limbopanel.c.
qboolean CG_LimboPanel_RealWeaponIsDisabled (weapon_t weapon)
Checks for heavy and rifle weapons.
Parameters
[in] weapon
Returns
Note
FIXME: this function needs some rework: count picked up opposite team weapons too see G_IsWeaponDisabled check: CG_LimboPanel_RealWeaponIsDisabled probably doesn't have to check for alt weapons they can't be selected
Definition at line 3783 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_SetSelectedWeaponNum(), CG_LimboPanel_Setup(), and CG_LimboPanel_WeaponPanel().
void CG_LimboPanel_RenderClassButton (panel_button_t * button)
CG_LimboPanel_RenderClassButton.
Parameters
[in] button
Definition at line 1665 of file cg_limbopanel.c.
void CG_LimboPanel_RenderCommandMap (panel_button_t * button)
CG_LimboPanel_RenderCommandMap.
Parameters
[in] button
Definition at line 1950 of file cg_limbopanel.c.
void CG_LimboPanel_RenderCounter (panel_button_t * button)
CG_LimboPanel_RenderCounter.
Parameters
[in] button
Note
This function is mental, i love it :)
Definition at line 3036 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup().
qboolean CG_LimboPanel_RenderCounter_CountsDown (panel_button_t * button)
CG_LimboPanel_RenderCounter_CountsDown.
Parameters
[in] button
Returns
Definition at line 2893 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
qboolean CG_LimboPanel_RenderCounter_CountsUp (panel_button_t * button)
CG_LimboPanel_RenderCounter_CountsUp.
Parameters
[in] button
Returns
Definition at line 2912 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
void CG_LimboPanel_RenderCounter_GetShaders (panel_button_t * button, qhandle_t * shaderBack, qhandle_t * shaderRoll, int * numimages)
CG_LimboPanel_RenderCounter_GetShaders.
Parameters
[in] button
[in] shaderBack
[in] shaderRoll
[in] numimages
Definition at line 2984 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
qboolean CG_LimboPanel_RenderCounter_IsReversed (panel_button_t * button)
CG_LimboPanel_RenderCounter_IsReversed.
Parameters
[in] button
Returns
Definition at line 2964 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
int CG_LimboPanel_RenderCounter_MaxChangeForButton (panel_button_t * button)
CG_LimboPanel_RenderCounter_MaxChangeForButton.
Parameters
[in] button
Returns
Definition at line 2829 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
int CG_LimboPanel_RenderCounter_NumRollers (panel_button_t * button)
CG_LimboPanel_RenderCounter_NumRollers.
Parameters
[in] button
Returns
Definition at line 2848 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
int CG_LimboPanel_RenderCounter_RollTimeForButton (panel_button_t * button)
CG_LimboPanel_RenderCounter_RollTimeForButton.
Parameters
[in] button
Returns
Definition at line 2790 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
qboolean CG_LimboPanel_RenderCounter_StartSet (panel_button_t * button)
CG_LimboPanel_RenderCounter_StartSet.
Parameters
[in] button
Returns
Definition at line 2932 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup().
int CG_LimboPanel_RenderCounter_ValueForButton (panel_button_t * button)
CG_LimboPanel_RenderCounter_ValueForButton.
Parameters
[in] button
Returns
Definition at line 2661 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderCounter_RollTimeForButton(), and CG_LimboPanel_Setup().
void CG_LimboPanel_RenderCounterNumber (float x, float y, float w, float h, float number, qhandle_t shaderBack, qhandle_t shaderRoll, int numbuttons)
CG_LimboPanel_RenderCounterNumber.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] number
[in] shaderBack
[in] shaderRoll
[in] numbuttons
Definition at line 2646 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderCounter().
void CG_LimboPanel_RenderHead (panel_button_t * button)
CG_LimboPanel_RenderHead.
Parameters
[in] button
Todo:
:
Definition at line 2171 of file cg_limbopanel.c.
void CG_LimboPanel_RenderLight (panel_button_t * button)
CG_LimboPanel_RenderLight.
Parameters
[in] button
Todo:
Need cleanup
Definition at line 1981 of file cg_limbopanel.c.
qboolean CG_LimboPanel_RenderLight_GetValue (panel_button_t * button)
CG_LimboPanel_RenderLight_GetValue.
Parameters
[in] button
Returns
Definition at line 1961 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderLight().
void CG_LimboPanel_RenderMedal (panel_button_t * button)
CG_LimboPanel_RenderMedal.
Parameters
[in] button
Definition at line 2950 of file cg_limbopanel.c.
void CG_LimboPanel_RenderObjectiveBack (panel_button_t * button)
CG_LimboPanel_RenderObjectiveBack.
Parameters
[in] button
Definition at line 1941 of file cg_limbopanel.c.
void CG_LimboPanel_RenderObjectiveText (panel_button_t * button)
Definition at line 1817 of file cg_limbopanel.c.
void CG_LimboPanel_RenderSkillIcon (panel_button_t * button)
CG_LimboPanel_RenderSkillIcon.
Parameters
[in] button
Definition at line 2255 of file cg_limbopanel.c.
void CG_LimboPanel_RenderTeamButton (panel_button_t * button)
CG_LimboPanel_RenderTeamButton.
Parameters
[in] button
Todo:
: There is no lock status transfer yet.
Definition at line 1475 of file cg_limbopanel.c.
void CG_LimboPanel_RequestObjective (void)
CG_LimboPanel_RequestObjective.
Definition at line 3615 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Draw(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_Setup(), and CG_MapRestart().
void CG_LimboPanel_RequestWeaponStats (void)
CG_LimboPanel_RequestWeaponStats.
Todo:
: Bleh?
Definition at line 3595 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponLights_KeyDown(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_SendSetupMsg (qboolean forceteam)
CG_LimboPanel_SendSetupMsg.
Parameters
[in] forceteam
Todo:
: handle all case ?
Definition at line 1314 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_OkButton_KeyDown(), CG_NewClientInfo(), and CG_ParseTeamXPs().
void CG_LimboPanel_SetDefaultWeapon (int slot)
CG_LimboPanel_SetSelectedDefaultWeapon.
Parameters
[in] slot
Definition at line 3524 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponPanel_KeyUp(), and CG_NewClientInfo().
void CG_LimboPanel_SetSelectedWeaponNum (int slot, weapon_t weapon)
CG_LimboPanel_SetSelectedWeaponNum.
Parameters
[in] number
Definition at line 3637 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_Setup (void)
CG_LimboPanel_Setup.
Definition at line 3179 of file cg_limbopanel.c.
Referenced by CG_EventHandling(), and CG_NewClientInfo().
void CG_LimboPanel_SpawnPointButton_Draw (panel_button_t * button)
CG_LimboPanel_SpawnPointButton_Draw.
Parameters
[in] button
Definition at line 1186 of file cg_limbopanel.c.
qboolean CG_LimboPanel_SpawnPointButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_SpawnPointButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1134 of file cg_limbopanel.c.
qboolean CG_LimboPanel_TeamButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_TeamButton_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1432 of file cg_limbopanel.c.
int CG_LimboPanel_TeamCount (int weap)
CG_LimboPanel_TeamCount.
Parameters
[in] weap weapon_t or -1
Returns
Definition at line 3657 of file cg_limbopanel.c.
Referenced by CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_ClassIsDisabled(), and CG_LimboPanel_RealWeaponIsDisabled().
qboolean CG_LimboPanel_TeamIsDisabled (team_t checkTeam)
CG_LimboPanel_TeamIsDisabled.
Parameters
[in] checkTeam
Returns
Definition at line 3976 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderTeamButton(), and CG_LimboPanel_TeamButton_KeyDown().
qboolean CG_LimboPanel_TeamIsFull (team_t checkTeam)
CG_LimboPanel_TeamIsFull.
Parameters
[in] checkTeam
Returns
Definition at line 3934 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_TeamIsDisabled().
int CG_LimboPanel_WeaponCount (int slotNumber)
CG_LimboPanel_WeaponCount.
Parameters
[in] slotNumber primary or secondary slot weapon
Returns
Definition at line 3405 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_WeaponPanel().
void CG_LimboPanel_WeaponLights (panel_button_t * button)
CG_LimboPanel_WeaponLights.
Parameters
[in] button
Definition at line 2311 of file cg_limbopanel.c.
qboolean CG_LimboPanel_WeaponLights_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_WeaponLights_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2288 of file cg_limbopanel.c.
void CG_LimboPanel_WeaponPanel (panel_button_t * button)
CG_LimboPanel_WeaponPanel.
Parameters
[in] button
Definition at line 2529 of file cg_limbopanel.c.
void CG_LimboPanel_WeaponPanel_DrawWeapon (rectDef_t * rect, weapon_t weap, qboolean highlight, const char * ofTxt, qboolean disabled)
CG_LimboPanel_WeaponPanel_DrawWeapon.
Parameters
[in] rect
[in] weap
[in] highlight
[in] ofTxt
[in] disabled
Definition at line 2410 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_WeaponPanel().
qboolean CG_LimboPanel_WeaponPanel_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_WeaponPanel_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2329 of file cg_limbopanel.c.
qboolean CG_LimboPanel_WeaponPanel_KeyUp (panel_button_t * button, int key)
CG_LimboPanel_WeaponPanel_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 2355 of file cg_limbopanel.c.
void CG_LimboPanelRenderText_NoLMS (panel_button_t * button)
CG_LimboPanelRenderText_NoLMS.
Parameters
[in] button
Definition at line 3005 of file cg_limbopanel.c.
void CG_LimboPanelRenderText_SkillsText (panel_button_t * button)
CG_LimboPanelRenderText_SkillsText.
Parameters
[in] button
Definition at line 3019 of file cg_limbopanel.c.
CLASS_COUNTER (0)
CLASS_COUNTER (1)
CLASS_COUNTER (2)
CLASS_COUNTER (3)
CLASS_COUNTER (4)
int ExtractInt (const char * src)
Convert a string to an integer.
Convert a string to an integer, with the same behavior that the engine converts cvars to their integer representation:
Integer is obtained from concatenating all the integers in the string, regardless of the other characters present in the string ("-" is the exception, of there is a "-" before the first integer, the number is turned into a negative)
If there are no integers in the string, return 0
Parameters
[in] src String to convert to an integer
Returns
Result of converted string to an integer
Note
Originates from q_shared.c
Definition at line 3713 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_MaxCount().
FILTER_BUTTON (0)
FILTER_BUTTON (1)
FILTER_BUTTON (2)
FILTER_BUTTON (3)
FILTER_BUTTON (4)
FILTER_BUTTON (5)
FILTER_BUTTON (6)
FILTER_BUTTON (7)
FILTER_BUTTON (8)
LEFT_FRAME ("gfx/limbo/limbo_frame01" , 1 , 0 , 0 , LF_W1 , LF_H1)
LEFT_FRAME ("gfx/limbo/limbo_frame02" , 2 , LF_X1 , 0 , LF_W2 , LF_H1)
LEFT_FRAME ("gfx/limbo/limbo_frame03" , 3 , LF_X2 , 0 , LF_W3 , LF_H1)
LEFT_FRAME ("gfx/limbo/limbo_frame04" , 4 , LF_X2 , LF_Y1 , LF_W3 , LF_H2)
LEFT_FRAME ("gfx/limbo/limbo_frame05" , 5 , LF_X2 , LF_Y2 , LF_W3 , LF_H3)
LEFT_FRAME ("gfx/limbo/limbo_frame06" , 6 , LF_X1 , LF_Y2 , LF_W2 , LF_H3)
LEFT_FRAME ("gfx/limbo/limbo_frame07" , 7 , 0 , LF_Y2 , LF_W1 , LF_H3)
LEFT_FRAME ("gfx/limbo/limbo_frame08" , 8 , 0 , LF_Y1 , LF_W1 , LF_H2)
MEDAL_PIC (0)
MEDAL_PIC (1)
MEDAL_PIC (2)
MEDAL_PIC (3)
MEDAL_PIC (4)
MEDAL_PIC (5)
MEDAL_PIC (6)
TEAM_COUNTER (0)
TEAM_COUNTER (1)
TEAM_COUNTER (2)
Variable Documentation
panel_button_t briefingButton static
Initial value:
=
{
    NULL,
    NULL,
    { 252,                            388,   24, 24 },
    { 0,                              0,     0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_BriefingButton_KeyDown,
    NULL,
    CG_LimboPanel_BriefingButton_Draw,
    NULL,
    0
}
Definition at line 908 of file cg_limbopanel.c.
panel_button_t cancelButton static
Initial value:
=
{
    NULL,
    NULL,
    { 543 + 2,                454 + 2,       82 - 4, 18 - 4 },
    { 0,                      0,             0,      0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_CancelButton_KeyDown,
    NULL,
    CG_LimboPanel_Border_Draw,
    NULL,
    0
}
Definition at line 980 of file cg_limbopanel.c.
panel_button_t cancelButtonText static
Initial value:
=
{
    NULL,
    "CANCEL",
    { 556,                     469,100, 40 },
    { 0,                       0,  0,   0, 0, 0, 0, 0},
    &titleLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 966 of file cg_limbopanel.c.
panel_button_t classBar static
Initial value:
=
{
    "gfx/limbo/lightup_bar",
    NULL,
    { 470,                    320,140, 20 },
    { 0,                      0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 277 of file cg_limbopanel.c.
panel_button_text_t classBarFont static
Initial value:
=
{
    0.22f,                 0.24f,
    { 0.f,                 0.f,  0.f,0.8f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 60 of file cg_limbopanel.c.
panel_button_t classBarText static
Initial value:
=
{
    NULL,
    NULL,
    { 460,                      334,   160, 16 },
    { 0,                        0,     0,   0, 0, 0, 0, 0},
    &classBarFont,
    NULL,
    NULL,
    CG_LimboPanel_ClassBar_Draw,
    NULL,
    0
}
Definition at line 291 of file cg_limbopanel.c.
vec4_t clrBackBorder = { 0.1f, 0.1f, 0.1f, 1.f } static
Definition at line 2458 of file cg_limbopanel.c.
Referenced by CG_DrawBorder().
vec4_t clrBackBorder2 = { 0.2f, 0.2f, 0.2f, 1.f } static
Definition at line 2459 of file cg_limbopanel.c.
Referenced by CG_DrawBorder().
vec4_t clrDrawWeapon = { 1.f, 1.f, 1.f, 0.6f } static
Definition at line 2400 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_WeaponPanel_DrawWeapon().
vec4_t clrRenderClassButton = { 1.f, 1.f, 1.f, 0.4f } static
Definition at line 1656 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderClassButton().
vec4_t clrRenderClassButton2 = { 1.f, 1.f, 1.f, 0.75f } static
Definition at line 1657 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderClassButton().
vec4_t clrRenderClassButton3 = { 1.f, 1.f, 1.f, 0.6f } static
Definition at line 1658 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderClassButton().
vec4_t clrRenderClassButton4 = { 1.f, 0.f, 0.f, 0.5f } static
Definition at line 1659 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderClassButton().
vec4_t clrRenderTeamButton2 = { 1.f, 1.f, 1.f, 0.4f } static
Definition at line 1468 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderTeamButton().
vec4_t clrRenderTeamButton4 = { 1.f, 0.f, 0.f, 0.75f } static
Definition at line 1469 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderTeamButton().
vec4_t clrWeaponPanel = { 0.f, 0.f, 0.f, 0.4f } static
Definition at line 2522 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_WeaponPanel().
vec4_t clrWeaponPanel2 = { 1.f, 1.f, 1.f, 0.4f } static
Definition at line 2523 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_WeaponPanel().
panel_button_t commandmapPanel static
Initial value:
=
{
    NULL,
    NULL,
    { CC_2D_X,                     CC_2D_Y,       CC_2D_W, CC_2D_H },
    { 0,                           0,             0,       0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCommandMap,
    NULL,
    0
}
Definition at line 836 of file cg_limbopanel.c.
panel_button_t filterTitleText static
Initial value:
=
{
    NULL,
    "FILTERS",
    { 8,                       36, 0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &weaponPanelFilterFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 335 of file cg_limbopanel.c.
panel_button_t* limboPanelButtons[] static
Definition at line 1066 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup().
panel_button_t limboTitleText static
Initial value:
=
{
    NULL,
    "COMMAND MAP",
    { 8,                       16, 0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &titleLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 621 of file cg_limbopanel.c.
panel_button_t mapTimeCounter static
Initial value:
=
{
    NULL,
    NULL,
    { 276,                      5,   20, 14 },
    { 5,                        0,   0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 547 of file cg_limbopanel.c.
panel_button_t mapTimeCounter2 static
Initial value:
=
{
    NULL,
    NULL,
    { 252,                      5,   20, 14 },
    { 5,                        1,   0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 561 of file cg_limbopanel.c.
panel_button_t mapTimeCounterText static
Initial value:
=
{
    NULL,
    "MISSION TIME",
    { 176,                     16, 0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &spawnLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 575 of file cg_limbopanel.c.
panel_button_t minusButton static
Initial value:
=
{
    NULL,
    NULL,
    { 18,                     348,  18, 12 },
    { 12,                     0,    0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_MinusButton_KeyDown,
    NULL,
    CG_LimboPanel_Border_Draw,
    NULL,
    0
}
Definition at line 1038 of file cg_limbopanel.c.
panel_button_t minusButtonText static
Initial value:
=
{
    NULL,
    "-",
    { 18,                      346,  18, 12 },
    { 12,                      0,    0,  0, 0, 0, 0, 0},
    &titleLimboFontBigCenter,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 1052 of file cg_limbopanel.c.
panel_button_t nameEdit static
Initial value:
=
{
    NULL,
    "limboname",
    { SCREEN_HEIGHT,             150,      120, 20 },
    { 0,                         0,        0,   0, 0, 0, 0, 0},
    &nameEditFont,
    BG_PanelButton_EditClick,
    NULL,
    BG_PanelButton_RenderEdit,
    CG_LimboPanel_NameEditFinish,
    0
}
Definition at line 996 of file cg_limbopanel.c.
panel_button_text_t nameEditFont static
Initial value:
=
{
    0.22f,                   0.24f,
    { 1.f,                   1.f,  1.f,0.8f },
    ITEM_TEXTSTYLE_SHADOWED, 0,
    &cgs.media.limboFont2,
}
Definition at line 52 of file cg_limbopanel.c.
panel_button_t objectivePanel static
Initial value:
=
{
    NULL,
    NULL,
    { 8,                              398, 240, 74 },
    { 0,                              0,   0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderObjectiveBack,
    NULL,
    0
}
Definition at line 852 of file cg_limbopanel.c.
panel_button_t objectivePanelButtonDown static
Initial value:
=
{
    "gfx/limbo/but_objective_dn",
    NULL,
    { 252,                       444,24, 24 },
    { 0,                         0,  0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_ObjectiveText_KeyDown,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 922 of file cg_limbopanel.c.
panel_button_t objectivePanelButtonUp static
Initial value:
=
{
    "gfx/limbo/but_objective_up",
    NULL,
    { 252,                       416,24, 24 },
    { 0,                         0,  0,  0, 0, 0, 0, 1},
    NULL,
    CG_LimboPanel_ObjectiveText_KeyDown,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 894 of file cg_limbopanel.c.
panel_button_t objectivePanelText static
Initial value:
=
{
    NULL,
    NULL,
    { 8,                              398, 240, 74 },
    { 0,                              0,   0,   0, 0, 0, 0, 0},
    &objectivePanelTxt,
    NULL,
    NULL,
    CG_LimboPanel_RenderObjectiveText,
    NULL,
    0
}
Definition at line 866 of file cg_limbopanel.c.
panel_button_t objectivePanelTitle static
Initial value:
=
{
    NULL,
    "OBJECTIVES",
    { 8,                       392,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &titleLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 880 of file cg_limbopanel.c.
panel_button_text_t objectivePanelTxt static
Initial value:
=
{
    0.2f,                  0.2f,
    { 0.0f,                0.0f,0.0f,    0.5f },
    0,                     0,
    &cgs.media.limboFont2,
}
Definition at line 141 of file cg_limbopanel.c.
panel_button_t okButton static
Initial value:
=
{
    NULL,
    NULL,
    { 454 + 2,                454 + 2,       82 - 4, 18 - 4 },
    { 0,                      0,             0,      0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_OkButton_KeyDown,
    NULL,
    CG_LimboPanel_Border_Draw,
    NULL,
    0
}
Definition at line 952 of file cg_limbopanel.c.
panel_button_t okButtonText static
Initial value:
=
{
    NULL,
    "OK",
    { 484,                     469,   100, 40 },
    { 0,                       0,     0,   0, 0, 0, 0, 0},
    &titleLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 938 of file cg_limbopanel.c.
panel_button_t playerLimboHead static
Initial value:
=
{
    NULL,
    NULL,
    { 456,                   30,   68, 84 },
    { 0,                     0,    0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderHead,
    NULL,
    0
}
Definition at line 391 of file cg_limbopanel.c.
panel_button_t playerSetupText static
Initial value:
=
{
    NULL,
    "PLAYER SETUP",
    { 448,                     16, 0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &titleLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 635 of file cg_limbopanel.c.
panel_button_t playerSkillCounter0 static
Initial value:
=
{
    NULL,
    NULL,
    { 552,                      36,   60, 16 },
    { 4,                        0,    0,  0, 0, 0, 4, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 433 of file cg_limbopanel.c.
panel_button_t playerSkillCounter1 static
Initial value:
=
{
    NULL,
    NULL,
    { 552,                      56,   60, 16 },
    { 4,                        1,    0,  0, 0, 0, 4, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 447 of file cg_limbopanel.c.
panel_button_t playerSkillCounter2 static
Initial value:
=
{
    NULL,
    NULL,
    { 552,                      76,   60, 16 },
    { 4,                        2,    0,  0, 0, 0, 4, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 461 of file cg_limbopanel.c.
panel_button_t playerSkillIcon0 static
Initial value:
=
{
    NULL,
    NULL,
    { 532,                        36,   16, 16 },
    { 0,                          0,    0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderSkillIcon,
    NULL,
    0
}
Definition at line 475 of file cg_limbopanel.c.
panel_button_t playerSkillIcon1 static
Initial value:
=
{
    NULL,
    NULL,
    { 532,                        56,   16, 16 },
    { 1,                          0,    0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderSkillIcon,
    NULL,
    0
}
Definition at line 489 of file cg_limbopanel.c.
panel_button_t playerSkillIcon2 static
Initial value:
=
{
    NULL,
    NULL,
    { 532,                        76,   16, 16 },
    { 2,                          0,    0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderSkillIcon,
    NULL,
    0
}
Definition at line 503 of file cg_limbopanel.c.
panel_button_t playerXPCounter static
Initial value:
=
{
    NULL,
    NULL,
    { 584,                      96,   40, 16 },
    { 2,                        0,    0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 419 of file cg_limbopanel.c.
panel_button_t playerXPCounterText static
Initial value:
=
{
    NULL,
    "XP",
    { 566,                        108,   60, 16 },
    { 2,                          0,     0,  0, 0, 0, 0, 0},
    &spawnLimboFont,
    NULL,
    NULL,
    CG_LimboPanelRenderText_NoLMS,
    NULL,
    0
}
Definition at line 405 of file cg_limbopanel.c.
panel_button_t plusButton static
Initial value:
=
{
    NULL,
    NULL,
    { 18,                     325,  18, 12 },
    { 12,                     0,    0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_PlusButton_KeyDown,
    NULL,
    CG_LimboPanel_Border_Draw,
    NULL,
    0
}
Definition at line 1010 of file cg_limbopanel.c.
panel_button_t plusButtonText static
Initial value:
=
{
    NULL,
    "+",
    { 18,                      323,  18, 12 },
    { 12,                      0,    0,  0, 0, 0, 0, 0},
    &titleLimboFontBigCenter,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 1024 of file cg_limbopanel.c.
panel_button_t respawnCounter static
Initial value:
=
{
    NULL,
    NULL,
    { 400,                      5,   20, 14 },
    { 3,                        0,   0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 591 of file cg_limbopanel.c.
panel_button_t respawnCounterText static
Initial value:
=
{
    NULL,
    "REINFORCEMENTS",
    { 300,                     16, 0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &spawnLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 605 of file cg_limbopanel.c.
panel_button_t rightLimboPannel static
Initial value:
=
{
    "gfx/limbo/limbo_back",
    NULL,
    { 440,                    0,  200, SCREEN_HEIGHT },
    { 0,                      0,  0,   0, 0, 0, 0, 0 },
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0
}
Definition at line 150 of file cg_limbopanel.c.
panel_button_t skillsText static
Initial value:
=
{
    NULL,
    "SKILLS",
    { 532,                             32, 0, 0 },
    { 0,                               0,  0, 0, 0, 0, 0, 0},
    &weaponPanelStatsFont,
    NULL,
    NULL,
    CG_LimboPanelRenderText_SkillsText,
    NULL,
    0
}
Definition at line 649 of file cg_limbopanel.c.
panel_button_text_t spawnLimboFont static
Initial value:
=
{
    0.18f,                 0.22f,
    { 1.f,                 1.f,  1.f,0.6f },
    0,                     0,
    &cgs.media.limboFont1,
}
Definition at line 93 of file cg_limbopanel.c.
panel_button_t spawnPointButton static
Initial value:
=
{
    NULL,
    NULL,
    { 132,                              381,   15, 15 },
    { 0,                                0,     0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_SpawnPointButton_KeyDown,
    NULL,
    CG_LimboPanel_SpawnPointButton_Draw,
    NULL,
    0
}
Definition at line 533 of file cg_limbopanel.c.
panel_button_t spawnPointText static
Initial value:
=
{
    NULL,
    "AUTOSPAWN",
    { 150,                     392,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &spawnLimboFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 519 of file cg_limbopanel.c.
team_t teamOrder[3] static
Initial value:
=
{
    TEAM_AXIS,
    TEAM_ALLIES,
    TEAM_SPECTATOR,
}
Definition at line 45 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_GetTeam(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderLight_GetValue(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_Setup(), and CG_LimboPanel_TeamButton_KeyDown().
panel_button_text_t titleLimboFont static
Initial value:
=
{
    0.24f,                 0.28f,
    { 1.f,                 1.f,  1.f,0.6f },
    0,                     0,
    &cgs.media.limboFont1,
}
Definition at line 68 of file cg_limbopanel.c.
panel_button_text_t titleLimboFontBigCenter static
Initial value:
=
{
    0.3f,                  0.3f,
    { 1.f,                 1.f,              1.f,  0.6f },
    0,                     ITEM_ALIGN_CENTER,
    &cgs.media.limboFont1,
}
Definition at line 85 of file cg_limbopanel.c.
panel_button_text_t weaponButtonFont static
Initial value:
=
{
    0.33f,                 0.33f,
    { 0.f,                 0.f,  0.f,0.6f },
    0,                     0,
    &cgs.media.limboFont1,
}
Definition at line 101 of file cg_limbopanel.c.
panel_button_t weaponLight1 static
Initial value:
=
{
    NULL,
    NULL,
    { 605,                     362,   20, 20 },
    { SECONDARY_SLOT,          0,     0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_WeaponLights_KeyDown,
    NULL,
    CG_LimboPanel_WeaponLights,
    NULL,
    0
}
Definition at line 679 of file cg_limbopanel.c.
panel_button_t weaponLight1Text static
Initial value:
=
{
    NULL,
    "1",
    { 609,                     378,   0, 0 },
    { 0,                       0,     0, 0, 0, 0, 0, 0},
    &weaponButtonFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 693 of file cg_limbopanel.c.
panel_button_t weaponLight2 static
Initial value:
=
{
    NULL,
    NULL,
    { 605,                     386,   20, 20 },
    { PRIMARY_SLOT,            0,     0,  0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_WeaponLights_KeyDown,
    NULL,
    CG_LimboPanel_WeaponLights,
    NULL,
    0
}
Definition at line 707 of file cg_limbopanel.c.
panel_button_t weaponLight2Text static
Initial value:
=
{
    NULL,
    "2",
    { 609,                     402,   0, 0 },
    { 0,                       0,     0, 0, 0, 0, 0, 0},
    &weaponButtonFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 721 of file cg_limbopanel.c.
panel_button_t weaponPanel static
Initial value:
=
{
    NULL,
    NULL,
    { 455,                    353,   140, 56 },
    { 0,                      0,     0,   0, 0, 0, 0, 0},
    NULL,
    CG_LimboPanel_WeaponPanel_KeyDown,
    CG_LimboPanel_WeaponPanel_KeyUp,
    CG_LimboPanel_WeaponPanel,
    NULL,
    0
}
Definition at line 665 of file cg_limbopanel.c.
panel_button_text_t weaponPanelFilterFont static
Initial value:
=
{
    0.17f,                    0.17f,
    { 1.0f,                   1.0f, 1.0f,  0.6f },
    0,                        0,
    &cgs.media.limboFont1_lo,
}
Definition at line 117 of file cg_limbopanel.c.
panel_button_text_t weaponPanelNameFont static
Initial value:
=
{
    0.20f,                 0.24f,
    { 1.0f,                1.0f, 1.0f,  0.4f },
    0,                     0,
    &cgs.media.limboFont1,
}
Definition at line 109 of file cg_limbopanel.c.
panel_button_text_t weaponPanelStatsFont static
Initial value:
=
{
    0.15f,                    0.17f,
    { 1.0f,                   1.0f, 1.0f,  0.6f },
    0,                        0,
    &cgs.media.limboFont1_lo,
}
Definition at line 125 of file cg_limbopanel.c.
panel_button_text_t weaponPanelStatsPercFont static
Initial value:
=
{
    0.2f,                  0.2f,
    { 1.0f,                1.0f,1.0f,    0.6f },
    0,                     0,
    &cgs.media.limboFont1,
}
Definition at line 133 of file cg_limbopanel.c.
panel_button_t weaponStatsAccCounter static
Initial value:
=
{
    NULL,
    NULL,
    { 570,                      426,   30, 14 },
    { 6,                        2,     0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 806 of file cg_limbopanel.c.
panel_button_t weaponStatsAccPercentage static
Initial value:
=
{
    NULL,
    "%",
    { 600,                     436,   0, 0 },
    { 0,                       0,     0, 0, 0, 0, 0, 0},
    &weaponPanelStatsPercFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 820 of file cg_limbopanel.c.
panel_button_t weaponStatsAccText static
Initial value:
=
{
    NULL,
    "ACC",
    { 570,                     422,  0, 0 },
    { 0,                       0,    0, 0, 0, 0, 0, 0},
    &weaponPanelStatsFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 792 of file cg_limbopanel.c.
panel_button_t weaponStatsHitsCounter static
Initial value:
=
{
    NULL,
    NULL,
    { 516,                      426,   40, 14 },
    { 6,                        1,     0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 777 of file cg_limbopanel.c.
panel_button_t weaponStatsHitsText static
Initial value:
=
{
    NULL,
    "HITS",
    { 516,                     422, 0, 0 },
    { 0,                       0,   0, 0, 0, 0, 0, 0},
    &weaponPanelStatsFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 763 of file cg_limbopanel.c.
panel_button_t weaponStatsShotsCounter static
Initial value:
=
{
    NULL,
    NULL,
    { 460,                      426,   40, 14 },
    { 6,                        0,     0,  0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_LimboPanel_RenderCounter,
    NULL,
    0
}
Definition at line 749 of file cg_limbopanel.c.
panel_button_t weaponStatsShotsText static
Initial value:
=
{
    NULL,
    "SHOTS",
    { 460,                     422,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &weaponPanelStatsFont,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0
}
Definition at line 735 of file cg_limbopanel.c.