ET: Legacy: src/cgame/cg_polybus.c File Reference
cg_polybus.c File Reference
#include "cg_local.h"
Macros
#define MAX_PB_BUFFERS 128
Functions
polyBuffer_t * CG_PB_FindFreePolyBuffer (qhandle_t shader, int numVerts, int numIndicies)
CG_PB_FindFreePolyBuffer.
void CG_PB_ClearPolyBuffers (void)
CG_PB_ClearPolyBuffers.
void CG_PB_RenderPolyBuffers (void)
CG_PB_RenderPolyBuffers.
Variables
polyBuffer_t cg_polyBuffers [MAX_PB_BUFFERS]
qboolean cg_polyBuffersInuse [MAX_PB_BUFFERS]
Macro Definition Documentation
#define MAX_PB_BUFFERS 128
Definition at line 37 of file cg_polybus.c.
Referenced by CG_PB_FindFreePolyBuffer(), and CG_PB_RenderPolyBuffers().
Function Documentation
void CG_PB_ClearPolyBuffers (void)
CG_PB_ClearPolyBuffers.
Definition at line 104 of file cg_polybus.c.
Referenced by CG_DrawActiveFrame().
polyBuffer_t* CG_PB_FindFreePolyBuffer (qhandle_t shader, int numVerts, int numIndicies)
CG_PB_FindFreePolyBuffer.
Parameters
[in] shader
[in] numVerts
[in] numIndicies
Returns
Definition at line 49 of file cg_polybus.c.
Referenced by CG_AddFlameSpriteToScene(), CG_AddPolyToPool(), and CG_AddTrailToScene().
void CG_PB_RenderPolyBuffers (void)
CG_PB_RenderPolyBuffers.
Definition at line 113 of file cg_polybus.c.
Referenced by CG_DrawActive().
Variable Documentation
polyBuffer_t cg_polyBuffers[MAX_PB_BUFFERS]
Definition at line 39 of file cg_polybus.c.
qboolean cg_polyBuffersInuse[MAX_PB_BUFFERS]
Definition at line 40 of file cg_polybus.c.
Referenced by CG_PB_ClearPolyBuffers(), CG_PB_FindFreePolyBuffer(), and CG_PB_RenderPolyBuffers().