ET: Legacy: src/cgame/cg_draw.c File Reference
cg_draw.c File Reference
Draw all of the graphical elements during active (after loading) gameplay.
#include "cg_local.h"
Macros
#define CHATLOC_Y 478
#define CP_LINEWIDTH (int)(Ccg_WideX(56))
#define INFOTEXT_STARTX 8
#define INFOTEXT_STARTY 146
#define OID_TOP 360
Functions
char * Binding_FromName (const char *cvar)
Binding_FromName.
void Controls_GetConfig (void)
Controls_GetConfig.
void CG_DrawOverlays (void)
CG_DrawOverlays.
void CG_Text_SetActiveFont (int font)
CG_Text_SetActiveFont.
int CG_Text_Width_Ext (const char *text, float scale, int limit, fontHelper_t *font)
CG_Text_Width_Ext.
int CG_Text_Width (const char *text, float scale, int limit)
CG_Text_Width.
int CG_Text_Height_Ext (const char *text, float scale, int limit, fontHelper_t *font)
CG_Text_Height_Ext.
int CG_Text_Height (const char *text, float scale, int limit)
CG_Text_Height.
void CG_Text_PaintChar_Ext (float x, float y, float w, float h, float scalex, float scaley, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar_Ext.
void CG_Text_PaintChar (float x, float y, float width, float height, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar.
void CG_Text_Paint_Centred_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
CG_Text_Paint_Centred_Ext.
void CG_Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
CG_Text_Paint_Ext.
void CG_Text_Paint (float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
CG_Text_Paint.
void CG_Text_PaintWithCursor_Ext (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style, fontHelper_t *font)
CG_Text_PaintWithCursor_Ext.
void CG_Text_PaintWithCursor (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style)
CG_Text_PaintWithCursor.
void CG_DrawTeamBackground (int x, int y, int w, int h, float alpha, int team)
CG_DrawTeamBackground.
static void CG_DrawTeamInfo (void)
CG_DrawTeamInfo.
const char * CG_PickupItemText (int itemNum)
CG_PickupItemText.
static int CG_FormatCenterPrint (char *s)
Format the message by turning spaces into newlines, if we've run over the linewidth.
void CG_CenterPrint (const char *str, int y, float fontScale)
Called for important messages that should stay in the center of the screen for a few moments.
void CG_PriorityCenterPrint (const char *str, int y, float fontScale, int priority)
Called for important messages that should stay in the center of the screen for a few moments.
static void CG_DrawCenterString (void)
CG_DrawCenterString.
static void CG_DrawScopedReticle (void)
CG_DrawWeapReticle.
static void CG_DrawMortarReticle (void)
CG_DrawMortarReticle.
static void CG_DrawBinocReticle (void)
CG_DrawBinocReticle.
static void CG_DrawCrosshair (void)
CG_DrawCrosshair.
static void CG_DrawNoShootIcon (void)
CG_DrawNoShootIcon.
void CG_ScanForCrosshairMine (centity_t *cent)
CG_ScanForCrosshairMine.
void CG_ScanForCrosshairDyna (centity_t *cent)
CG_ScanForCrosshairDyna.
static float CG_ScanForCrosshairEntity (float *zChange, qboolean *hitClient)
Returns the distance to the entity.
void CG_CheckForCursorHints (void)
CG_CheckForCursorHints.
static void CG_DrawCrosshairNames (void)
CG_DrawCrosshairNames.
static void CG_DrawSpectator (void)
CG_DrawSpectator.
static void CG_DrawVote (void)
CG_DrawVote.
static void CG_DrawIntermission (void)
CG_DrawIntermission.
static void CG_DrawSpectatorMessage (void)
CG_DrawSpectatorMessage.
float CG_CalculateReinfTime_Float (qboolean menu)
CG_CalculateReinfTime_Float.
int CG_CalculateReinfTime (qboolean menu)
CG_CalculateReinfTime.
int CG_CalculateShoutcasterReinfTime (team_t team)
CG_CalculateShoutcasterReinfTime.
static void CG_DrawLimboMessage (void)
CG_DrawLimboMessage.
static qboolean CG_DrawFollow (void)
CG_DrawFollow.
static void CG_DrawWarmup (void)
CG_DrawWarmup.
static void CG_DrawFlashFade (void)
CG_DrawFlashFade.
static void CG_DrawFlashZoomTransition (void)
Hide the snap transition from regular view to/from zoomed.
static void CG_DrawFlashDamage (void)
CG_DrawFlashDamage.
static void CG_DrawFlashFire (void)
CG_DrawFlashFire.
static void CG_DrawFlashBlendBehindHUD (void)
Screen flash stuff drawn first (on top of world, behind HUD)
static void CG_DrawFlashBlend (void)
Screen flash stuff drawn last (on top of everything)
void CG_ObjectivePrint (const char *str, float fontScale)
CG_ObjectivePrint.
static void CG_DrawObjectiveInfo (void)
CG_DrawObjectiveInfo.
static void CG_DrawTimedMenus (void)
CG_DrawTimedMenus.
void CG_Fade (int r, int g, int b, int a, int time, int duration)
CG_Fade.
static void CG_ScreenFade (void)
CG_ScreenFade.
void CG_DrawDemoRecording (void)
CG_DrawDemoRecording.
void CG_DrawOnScreenLabels (void)
CG_DrawOnScreenLabels.
static void CG_Draw2D (void)
CG_Draw2D.
void CG_StartShakeCamera (float p)
CG_StartShakeCamera.
void CG_ShakeCamera (void)
CG_ShakeCamera.
void CG_DrawMiscGamemodels (void)
CG_DrawMiscGamemodels.
void CG_Coronas (void)
CG_Coronas.
void CG_DrawActive ()
Perform all drawing needed to completely fill the screen.
Variables
int activeFont
vec4_t HUD_Border
static int lastDemoScoreTime = 0
Detailed Description
Draw all of the graphical elements during active (after loading) gameplay.
Definition in file cg_draw.c.
Macro Definition Documentation
#define CHATLOC_Y 478
Definition at line 504 of file cg_draw.c.
Referenced by CG_DrawTeamInfo().
#define CP_LINEWIDTH (int)(Ccg_WideX(56))
Definition at line 633 of file cg_draw.c.
Referenced by CG_FormatCenterPrint().
#define INFOTEXT_STARTX 8
Definition at line 1986 of file cg_draw.c.
Referenced by CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawSpectatorMessage(), and CG_DrawVote().
#define INFOTEXT_STARTY 146
Definition at line 1987 of file cg_draw.c.
Referenced by CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawSpectatorMessage(), and CG_DrawVote().
#define OID_TOP 360
Definition at line 3184 of file cg_draw.c.
Referenced by CG_ObjectivePrint().
Function Documentation
char* Binding_FromName (const char * cvar)
Binding_FromName.
Parameters
[in] cvar
Returns
Definition at line 1018 of file ui_shared.c.
Referenced by CG_DrawLimboMessage(), CG_DrawSpectatorMessage(), CG_DrawVote(), CG_DrawWarmup(), and Item_Bind_Paint().
int CG_CalculateReinfTime (qboolean menu)
CG_CalculateReinfTime.
Parameters
menu
Returns
Definition at line 2511 of file cg_draw.c.
Referenced by CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), and WM_DrawObjectives().
float CG_CalculateReinfTime_Float (qboolean menu)
CG_CalculateReinfTime_Float.
Parameters
[in] menu
Returns
Definition at line 2481 of file cg_draw.c.
Referenced by CG_CalculateReinfTime(), and CG_LimboPanel_RenderCounter_ValueForButton().
int CG_CalculateShoutcasterReinfTime (team_t team)
CG_CalculateShoutcasterReinfTime.
Parameters
[in] team
Returns
Definition at line 2521 of file cg_draw.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
void CG_CenterPrint (const char * str, int y, float fontScale)
Called for important messages that should stay in the center of the screen for a few moments.
Parameters
[in] str
[in] y
[in] fontScale
Definition at line 703 of file cg_draw.c.
void CG_CheckForCursorHints (void)
CG_CheckForCursorHints.
Note
Concept in progress...
Definition at line 1537 of file cg_draw.c.
Referenced by CG_DrawCursorhint().
void CG_Coronas (void)
CG_Coronas.
Definition at line 3837 of file cg_draw.c.
Referenced by CG_DrawActive().
static void CG_Draw2D (void) static
CG_Draw2D.
Definition at line 3582 of file cg_draw.c.
Referenced by CG_DrawActive().
void CG_DrawActive (void)
Perform all drawing needed to completely fill the screen.
Definition at line 3898 of file cg_draw.c.
Referenced by CG_DrawActiveFrame().
static void CG_DrawBinocReticle (void) static
CG_DrawBinocReticle.
Definition at line 1200 of file cg_draw.c.
Referenced by CG_DrawCrosshair().
static void CG_DrawCenterString (void) static
CG_DrawCenterString.
Definition at line 739 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawCrosshair (void) static
CG_DrawCrosshair.
Todo:
: spectators/chasing?
Definition at line 1221 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawCrosshairNames (void) static
CG_DrawCrosshairNames.
Todo:
: name already clean
Definition at line 1632 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_DrawDemoRecording (void)
CG_DrawDemoRecording.
Definition at line 3459 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawFlashBlend (void) static
Screen flash stuff drawn last (on top of everything)
Definition at line 3171 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawFlashBlendBehindHUD (void) static
Screen flash stuff drawn first (on top of world, behind HUD)
Definition at line 3162 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawFlashDamage (void) static
CG_DrawFlashDamage.
Definition at line 3071 of file cg_draw.c.
Referenced by CG_DrawFlashBlend().
static void CG_DrawFlashFade (void) static
CG_DrawFlashFade.
Todo:
: translate team names? team name
Definition at line 2938 of file cg_draw.c.
Referenced by CG_Draw2D(), and CG_DrawFlashBlendBehindHUD().
static void CG_DrawFlashFire (void) static
CG_DrawFlashFire.
Definition at line 3100 of file cg_draw.c.
Referenced by CG_DrawFlashBlend().
static void CG_DrawFlashZoomTransition (void) static
Hide the snap transition from regular view to/from zoomed.
Todo:
FIXME: TODO: use cg_fade?
Definition at line 3033 of file cg_draw.c.
Referenced by CG_DrawFlashBlendBehindHUD().
static qboolean CG_DrawFollow (void) static
CG_DrawFollow.
Returns
Definition at line 2606 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawIntermission (void) static
CG_DrawIntermission.
Definition at line 2362 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawLimboMessage (void) static
CG_DrawLimboMessage.
Definition at line 2532 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_DrawMiscGamemodels (void)
CG_DrawMiscGamemodels.
Definition at line 3792 of file cg_draw.c.
Referenced by CG_DrawActive().
static void CG_DrawMortarReticle (void) static
CG_DrawMortarReticle.
Definition at line 890 of file cg_draw.c.
Referenced by CG_DrawCrosshair().
static void CG_DrawNoShootIcon (void) static
CG_DrawNoShootIcon.
Definition at line 1351 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawObjectiveInfo (void) static
CG_DrawObjectiveInfo.
Definition at line 3214 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_DrawOnScreenLabels (void)
CG_DrawOnScreenLabels.
Definition at line 3509 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_DrawOverlays (void)
CG_DrawOverlays.
Definition at line 2132 of file cg_info.c.
Referenced by CG_Draw2D().
static void CG_DrawScopedReticle (void) static
CG_DrawWeapReticle.
Definition at line 826 of file cg_draw.c.
Referenced by CG_DrawCrosshair().
static void CG_DrawSpectator (void) static
CG_DrawSpectator.
Definition at line 1992 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawSpectatorMessage (void) static
CG_DrawSpectatorMessage.
Definition at line 2411 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_DrawTeamBackground (int x, int y, int w, int h, float alpha, int team)
CG_DrawTeamBackground.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] alpha
[in] team
Note
Unused
Definition at line 471 of file cg_draw.c.
static void CG_DrawTeamInfo (void) static
CG_DrawTeamInfo.
Definition at line 509 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawTimedMenus (void) static
CG_DrawTimedMenus.
Definition at line 3350 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawVote (void) static
CG_DrawVote.
Definition at line 2019 of file cg_draw.c.
Referenced by CG_Draw2D().
static void CG_DrawWarmup (void) static
CG_DrawWarmup.
Definition at line 2742 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_Fade (int r, int g, int b, int a, int time, int duration)
CG_Fade.
Parameters
r - unused
g - unused
b - unused
[in] a
[in] time
[in] duration
Todo:
cleanup ?
Todo:
: early return?
Definition at line 3373 of file cg_draw.c.
Referenced by CG_Fade_f().
static int CG_FormatCenterPrint (char * s) static
Format the message by turning spaces into newlines, if we've run over the linewidth.
Parameters
[in,out] s The message to format
Returns
The number of line needed to display the messages
Definition at line 640 of file cg_draw.c.
Referenced by CG_ObjectivePrint(), and CG_PriorityCenterPrint().
void CG_ObjectivePrint (const char * str, float fontScale)
CG_ObjectivePrint.
Parameters
[in] str
[in] fontScale
Definition at line 3191 of file cg_draw.c.
Referenced by CG_TouchTriggerPrediction().
const char* CG_PickupItemText (int itemNum)
CG_PickupItemText.
Parameters
[in] item
Returns
Todo:
: this is just related to english
Definition at line 602 of file cg_draw.c.
Referenced by CG_ItemPickup().
void CG_PriorityCenterPrint (const char * str, int y, float fontScale, int priority)
Called for important messages that should stay in the center of the screen for a few moments.
Parameters
[in] str
[in] y
[in] fontScale
[in] priority
Definition at line 717 of file cg_draw.c.
Referenced by CG_CenterPrint(), CG_Class_f(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_SendSetupMsg(), CG_NewClientInfo(), CG_Obituary(), CG_ServerCommand(), and CG_SpawnpointsCheckExecKey().
void CG_ScanForCrosshairDyna (centity_t * cent)
CG_ScanForCrosshairDyna.
Mainly just a copy paste of CG_ScanForCrosshairMine
Parameters
cent
Definition at line 1421 of file cg_draw.c.
Referenced by CG_DrawMineMarkerFlag(), and CG_Missile().
static float CG_ScanForCrosshairEntity (float * zChange, qboolean * hitClient) static
Returns the distance to the entity.
Parameters
[out] zChange
[out] hitClient
Returns
Distance to the entity
Definition at line 1456 of file cg_draw.c.
Referenced by CG_DrawCrosshairNames().
void CG_ScanForCrosshairMine (centity_t * cent)
CG_ScanForCrosshairMine.
Parameters
[in] cent
Definition at line 1390 of file cg_draw.c.
Referenced by CG_DrawMineMarkerFlag(), and CG_Missile().
static void CG_ScreenFade (void) static
CG_ScreenFade.
Definition at line 3409 of file cg_draw.c.
Referenced by CG_Draw2D().
void CG_ShakeCamera (void)
CG_ShakeCamera.
Definition at line 3760 of file cg_draw.c.
Referenced by CG_DrawActive().
void CG_StartShakeCamera (float p)
CG_StartShakeCamera.
Parameters
[in] p
Definition at line 3748 of file cg_draw.c.
Referenced by CG_EntityEvent().
int CG_Text_Height (const char * text, float scale, int limit)
CG_Text_Height.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 170 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
int CG_Text_Height_Ext (const char * text, float scale, int limit, fontHelper_t * font)
CG_Text_Height_Ext.
Parameters
[in] text
[in] scale
[in] limit
[in] font
Returns
Definition at line 125 of file cg_draw.c.
Referenced by CG_AddOnScreenText(), CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawFollow(), CG_DrawGrid(), CG_DrawLimboMessage(), CG_DrawMortarReticle(), CG_DrawSpectatorMessage(), CG_DrawVote(), CG_LoadHudMenu(), CG_ObjectivePrint(), CG_PriorityCenterPrint(), CG_removeStrings(), CG_Text_Height(), and CG_windowNormalizeOnText().
void CG_Text_Paint (float x, float y, float scale, vec4_t color, const char * text, float adjust, int limit, int style)
CG_Text_Paint.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] adjust
[in] limit
[in] style
Definition at line 328 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
void CG_Text_Paint_Centred_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char * text, float adjust, int limit, int style, fontHelper_t * font)
CG_Text_Paint_Centred_Ext.
Parameters
[in] x
[in] y
[in] scalex
[in] scaley
[in] color
[in] text
[in] adjust
[in] limit
[in] style
[in] font
Definition at line 234 of file cg_draw.c.
Referenced by CG_DrawConnectScreen().
void CG_Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char * text, float adjust, int limit, int style, fontHelper_t * font)
CG_Text_Paint_Ext.
Parameters
[in] x
[in] y
[in] scalex
[in] scaley
[in] color
[in] text
[in] adjust
[in] limit
[in] style
[in] font
Definition at line 254 of file cg_draw.c.
Referenced by CG_CommandMap_DrawHighlightText(), CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_DebriefingPlayerList_Draw(), CG_DebriefingPlayerWeaponStats_Draw(), CG_DebriefingTitle_Draw(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawAmmoCount(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDemoControls(), CG_DrawDemoRecording(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawLimboMessage(), CG_DrawLocalTime(), CG_DrawMapEntity(), CG_DrawMortarReticle(), CG_DrawObjectiveInfo(), CG_DrawOnScreenLabels(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScoreboard(), CG_DrawSkills(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawStatsDebug(), CG_DrawTeamInfo(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawXP(), CG_Fireteams_MenuText_Draw(), CG_Fireteams_MenuTitleText_Draw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_LoadPanel_LoadingBarText(), CG_LoadPanel_RenderCampaignNameText(), CG_LoadPanel_RenderCampaignTypeText(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_VoteButton_Draw(), CG_MapVoteList_Draw(), CG_ObjectivesDraw(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_Spawnpoints_MenuText_Draw(), CG_Spawnpoints_MenuTitleText_Draw(), CG_SpeakerEditor_LocInfo(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerEditorDraw(), CG_SpeakerInfo_Text(), CG_TeamDebriefingTeamSkillXP_Draw(), CG_Text_Paint(), CG_Text_Paint_Centred_Ext(), CG_TopShotsDraw(), CG_windowDraw(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void CG_Text_PaintChar (float x, float y, float width, float height, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] scale
[in] s
[in] t
[in] s2
[in] t2
[in] hShader
Definition at line 212 of file cg_draw.c.
Referenced by CG_Text_PaintWithCursor_Ext().
void CG_Text_PaintChar_Ext (float x, float y, float w, float h, float scalex, float scaley, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar_Ext.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] scalex
[in] scaley
[in] s
[in] t
[in] s2
[in] t2
[in] hShader
Definition at line 191 of file cg_draw.c.
Referenced by CG_Text_Paint_Ext().
void CG_Text_PaintWithCursor (float x, float y, float scale, vec4_t color, const char * text, int cursorPos, const char * cursor, int limit, int style)
CG_Text_PaintWithCursor.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] cursorPos
[in] cursor
[in] limit
[in] style
Definition at line 453 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
void CG_Text_PaintWithCursor_Ext (float x, float y, float scale, vec4_t color, const char * text, int cursorPos, const char * cursor, int limit, int style, fontHelper_t * font)
CG_Text_PaintWithCursor_Ext.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] cursorPos
[in] cursor
[in] limit
[in] style
Definition at line 347 of file cg_draw.c.
Referenced by CG_Debriefing_ChatEdit_Draw(), CG_LoadHudMenu(), and CG_Text_PaintWithCursor().
void CG_Text_SetActiveFont (int font)
CG_Text_SetActiveFont.
Parameters
[in] font
Definition at line 54 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
int CG_Text_Width (const char * text, float scale, int limit)
CG_Text_Width.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 110 of file cg_draw.c.
Referenced by CG_FitTextToWidth2(), CG_FitTextToWidth_SingleLine(), CG_LoadHudMenu(), and CG_TrimLeftPixels().
int CG_Text_Width_Ext (const char * text, float scale, int limit, fontHelper_t * font)
CG_Text_Width_Ext.
Parameters
[in] text
[in] scale
[in] limit
[in] font
Returns
Definition at line 67 of file cg_draw.c.
Referenced by CG_AddOnScreenText(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_DebriefingTitle_Draw(), CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawAmmoCount(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawMapEntity(), CG_DrawMortarReticle(), CG_DrawObjectiveInfo(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawRank(), CG_DrawScoreboard(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpeed(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawWarmup(), CG_DrawXP(), CG_FitTextToWidth_Ext(), CG_getBindKeyName(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_LoadPanel_RenderCampaignNameText(), CG_ObjectivePrint(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_PriorityCenterPrint(), CG_removeStrings(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerInfo_Text(), CG_StatsDebugAddText(), CG_Text_Paint_Centred_Ext(), CG_Text_Width(), CG_windowNormalizeOnText(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void Controls_GetConfig (void)
Controls_GetConfig.
Definition at line 815 of file ui_shared.c.
Referenced by CG_DrawSpectatorMessage(), and UI_RunMenuScript().
Variable Documentation
int activeFont
Definition at line 42 of file cg_draw.c.
Referenced by CG_Text_Height(), CG_Text_Paint(), CG_Text_PaintWithCursor(), CG_Text_SetActiveFont(), and CG_Text_Width().
vec4_t HUD_Border
Definition at line 633 of file cg_draw_hud.c.
Referenced by CG_DemoClick(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSnapshot(), CG_DrawSpeed(), and CG_DrawTimerNormal().
int lastDemoScoreTime = 0 static
Definition at line 3454 of file cg_draw.c.
Referenced by CG_DrawDemoRecording().