ET: Legacy: src/cgame/cg_atmospheric.c File Reference
cg_atmospheric.c File Reference
Add atmospheric effects (e.g. rain, snow etc.) to view.
#include "cg_local.h"
Data Structures
struct cg_atmosphericParticle_s
struct cg_atmosphericEffect_s
Macros
#define MAX_ATMOSPHERIC_HEIGHT MAX_MAP_SIZE
#define MAX_ATMOSPHERIC_PARTICLES 4000
#define MAX_ATMOSPHERIC_DISTANCE 1000
#define MAX_ATMOSPHERIC_EFFECTSHADERS 4
#define ATMOSPHERIC_RAIN_SPEED (1.1f * DEFAULT_GRAVITY)
#define ATMOSPHERIC_RAIN_HEIGHT 150
#define ATMOSPHERIC_SNOW_SPEED (0.1f * DEFAULT_GRAVITY)
#define ATMOSPHERIC_SNOW_HEIGHT 3
#define ATMOSPHERIC_PARTICLE_OFFSET 10
Typedefs
typedef struct cg_atmosphericParticle_s cg_atmosphericParticle_t
typedef struct cg_atmosphericEffect_s cg_atmosphericEffect_t
Enumerations
enum atmFXType_t { ATM_NONE = 0, ATM_RAIN, ATM_SNOW }
enum active_t { ACT_NOT = 0, ACT_FALLING }
Functions
static void CG_AddPolyToPool (qhandle_t shader, const polyVert_t *verts)
Add polygon to pool.
qboolean CG_AtmosphericKludge (void)
Activate atmospheric effects for kludge maps.
static qboolean CG_SetParticleActive (cg_atmosphericParticle_t *particle, active_t active)
Activate particule.
static qboolean CG_ParticleGenerate (cg_atmosphericParticle_t *particle, vec3_t currvec, float currweight, atmFXType_t atmFX)
Generate a particle.
static qboolean CG_ParticleCheckVisible (cg_atmosphericParticle_t *particle)
Check visibility of particle.
static void CG_ParticleRender (cg_atmosphericParticle_t *particle)
Draw a particle.
static void CG_EffectGust (void)
Gust effect.
static qboolean CG_EffectGustCurrent (vec3_t curr, float *weight, int *num)
Gust current effect.
static void CG_EP_ParseFloats (char *floatstr, float *f1, float *f2)
Parse floats.
static void CG_EP_ParseInts (char *intstr, int *i1, int *i2)
Parse ints.
void CG_EffectParse (const char *effectstr)
Parse effect.
void CG_AddAtmosphericEffects ()
Add atmospheric effects.
Variables
static qboolean kludgeChecked
static qboolean kludgeResult
static cg_atmosphericEffect_t cg_atmFx
Detailed Description
Add atmospheric effects (e.g. rain, snow etc.) to view.
Current supported effects are rain and snow.
Definition in file cg_atmospheric.c.
Macro Definition Documentation
#define ATMOSPHERIC_PARTICLE_OFFSET 10
Definition at line 53 of file cg_atmospheric.c.
Referenced by CG_ParticleGenerate(), and CG_ParticleRender().
#define ATMOSPHERIC_RAIN_HEIGHT 150
Definition at line 48 of file cg_atmospheric.c.
Referenced by CG_ParticleGenerate().
#define ATMOSPHERIC_RAIN_SPEED (1.1f * DEFAULT_GRAVITY)
Definition at line 47 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
#define ATMOSPHERIC_SNOW_HEIGHT 3
Definition at line 51 of file cg_atmospheric.c.
Referenced by CG_ParticleGenerate().
#define ATMOSPHERIC_SNOW_SPEED (0.1f * DEFAULT_GRAVITY)
Definition at line 50 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
#define MAX_ATMOSPHERIC_DISTANCE 1000
Definition at line 44 of file cg_atmospheric.c.
Referenced by CG_ParticleCheckVisible(), and CG_ParticleGenerate().
#define MAX_ATMOSPHERIC_EFFECTSHADERS 4
Definition at line 45 of file cg_atmospheric.c.
#define MAX_ATMOSPHERIC_HEIGHT MAX_MAP_SIZE
Definition at line 40 of file cg_atmospheric.c.
Referenced by CG_ParticleGenerate().
#define MAX_ATMOSPHERIC_PARTICLES 4000
Definition at line 43 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
Typedef Documentation
typedef struct cg_atmosphericEffect_s cg_atmosphericEffect_t
typedef struct cg_atmosphericParticle_s cg_atmosphericParticle_t
Enumeration Type Documentation
enum active_t
Enumerator
ACT_NOT
ACT_FALLING
Definition at line 175 of file cg_atmospheric.c.
enum atmFXType_t
Enumerator
ATM_NONE
ATM_RAIN
ATM_SNOW
Definition at line 55 of file cg_atmospheric.c.
Function Documentation
void CG_AddAtmosphericEffects (void)
Add atmospheric effects.
Add atmospheric effects (e.g. rain, snow etc.) to view]
Definition at line 846 of file cg_atmospheric.c.
Referenced by CG_DrawActiveFrame().
static void CG_AddPolyToPool (qhandle_t shader, const polyVert_t * verts) static
Add polygon to pool.
Helper function to add polygon to pool
Parameters
[in] shader
[in] verts
Definition at line 70 of file cg_atmospheric.c.
Referenced by CG_ParticleRender().
qboolean CG_AtmosphericKludge (void)
Activate atmospheric effects for kludge maps.
Activate rain for specified kludge maps that don't have it specified for them
Definition at line 110 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
static void CG_EffectGust (void) static
Gust effect.
Generate random values for the next gust.
Definition at line 541 of file cg_atmospheric.c.
Referenced by CG_AddAtmosphericEffects(), and CG_EffectParse().
static qboolean CG_EffectGustCurrent (vec3_t curr, float * weight, int * num) static
Gust current effect.
Calculate direction for new drops.
Parameters
[out] curr
[out] weight
[out] num
Returns
Definition at line 562 of file cg_atmospheric.c.
Referenced by CG_AddAtmosphericEffects().
void CG_EffectParse (const char * effectstr)
Parse effect.
Split the string into it's component parts.
Parameters
[in] effectstr
Definition at line 667 of file cg_atmospheric.c.
Referenced by SP_worldspawn().
static void CG_EP_ParseFloats (char * floatstr, float * f1, float * f2) static
Parse floats.
Parse the float or floats.
Parameters
[in] floatstr
[out] f1
[out] f2
Definition at line 614 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
static void CG_EP_ParseInts (char * intstr, int * i1, int * i2) static
Parse ints.
Parse the int or ints.
Parameters
[in] intstr
[out] i1
[out] i2
Definition at line 642 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
static qboolean CG_ParticleCheckVisible (cg_atmosphericParticle_t * particle) static
Check visibility of particle.
Check the drop is visible and still going, wrapping if necessary.
Parameters
[in] particle
Returns
Definition at line 333 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
static qboolean CG_ParticleGenerate (cg_atmosphericParticle_t * particle, vec3_t currvec, float currweight, atmFXType_t atmFX) static
Generate a particle.
Attempt to 'spot' a drop somewhere below a sky texture.
Parameters
[out] particle
[in] currvec
[in] currweight
[in] atmFX
Returns
Definition at line 242 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
static void CG_ParticleRender (cg_atmosphericParticle_t * particle) static
Draw a particle.
Renders a particle.
Parameters
[in] particle
Definition at line 373 of file cg_atmospheric.c.
Referenced by CG_EffectParse().
static qboolean CG_SetParticleActive (cg_atmosphericParticle_t * particle, active_t active) static
Activate particule.
Activate atmospheric particle
Parameters
[out] particle
[in] active
Returns
Definition at line 227 of file cg_atmospheric.c.
Referenced by CG_ParticleCheckVisible(), and CG_ParticleGenerate().
Variable Documentation
cg_atmosphericEffect_t cg_atmFx static
Definition at line 218 of file cg_atmospheric.c.
qboolean kludgeChecked static
Definition at line 105 of file cg_atmospheric.c.
Referenced by CG_AtmosphericKludge().
qboolean kludgeResult static
Definition at line 105 of file cg_atmospheric.c.
Referenced by CG_AtmosphericKludge().