ET: Legacy: src/cgame/cg_drawtools.c File Reference
cg_drawtools.c File Reference
Helper functions called by cg_draw, cg_scoreboard, cg_info, etc.
#include "cg_local.h"
Macros
#define BAR_BORDERSIZE 2
Functions
void CG_AdjustFrom640 (float *x, float *y, float *w, float *h)
Adjusted for resolution and screen aspect ratio.
qboolean Ccg_Is43Screen (void)
Ccg_Is43Screen.
float Ccg_WideX (float x)
Ccg_WideX.
float Ccg_WideXoffset (void)
Ccg_WideXoffset.
void CG_FillRect (float x, float y, float width, float height, const float *color)
CG_FillRect.
void CG_FilledBar (float x, float y, float w, float h, float *startColor, float *endColor, const float *bgColor, float frac, int flags)
CG_FilledBar.
void CG_HorizontalPercentBar (float x, float y, float width, float height, float percent)
Generic routine for pretty much all status indicators that show a fractional value to the player by virtue of how full a drawn box is.
void CG_DrawSides (float x, float y, float w, float h, float size)
CG_DrawSides.
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
CG_DrawTopBottom.
void CG_DrawSides_NoScale (float x, float y, float w, float h, float size)
CG_DrawSides_NoScale.
void CG_DrawTopBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawTopBottom_NoScale.
void CG_DrawBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawBottom_NoScale.
void CG_DrawRect (float x, float y, float width, float height, float size, const float *color)
CG_DrawRect.
void CG_DrawRect_FixedBorder (float x, float y, float width, float height, int border, const float *color)
CG_DrawRect_FixedBorder.
void CG_DrawPicST (float x, float y, float width, float height, float s0, float t0, float s1, float t1, qhandle_t hShader)
Allows passing of st co-ords.
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
CG_DrawPic.
void CG_DrawRotatedPic (float x, float y, float width, float height, qhandle_t hShader, float angle)
CG_DrawRotatedPic.
static void CG_TileClearBox (int x, int y, int w, int h, qhandle_t hShader)
This repeats a 64*64 tile graphic to fill the screen around a sized down refresh window.
void CG_TileClear (void)
CG_TileClear.
float * CG_FadeColor (int startMsec, int totalMsec)
CG_FadeColor.
float * CG_TeamColor (int team)
CG_TeamColor.
void CG_GetColorForHealth (int health, vec4_t hcolor)
CG_GetColorForHealth.
void CG_ColorForHealth (vec4_t hcolor)
CG_ColorForHealth.
const char * CG_TranslateString (const char *string)
CG_TranslateString.
qboolean CG_WorldCoordToScreenCoordFloat (vec3_t point, float *x, float *y)
Float a sprite over the player's head added height parameter.
void CG_AddOnScreenText (const char *text, vec3_t origin)
CG_AddOnScreenText.
Variables
static vec4_t red = { 1.0f, 0.2f, 0.2f, 1.0f }
static vec4_t blue = { 0.2f, 0.2f, 1.0f, 1.0f }
static vec4_t other = { 1.0f, 1.0f, 1.0f, 1.0f }
static vec4_t spectator = { 0.7f, 0.7f, 0.7f, 1.0f }
Detailed Description
Helper functions called by cg_draw, cg_scoreboard, cg_info, etc.
Definition in file cg_drawtools.c.
Macro Definition Documentation
#define BAR_BORDERSIZE 2
Definition at line 132 of file cg_drawtools.c.
Referenced by CG_FilledBar().
Function Documentation
qboolean Ccg_Is43Screen (void)
Ccg_Is43Screen.
Returns
Definition at line 64 of file cg_drawtools.c.
Referenced by Ccg_WideX(), Ccg_WideXoffset(), CG_AdjustFrom640(), CG_CalcVrect(), and vmMain().
float Ccg_WideX (float x)
Ccg_WideX.
Parameters
[in] x
Returns
Definition at line 78 of file cg_drawtools.c.
Referenced by CG_CompasMoveLocation(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawBinocReticle(), CG_DrawCenterString(), CG_DrawDisconnect(), CG_DrawExpandedAutoMap(), CG_DrawFireTeamOverlay(), CG_DrawFlashDamage(), CG_DrawFlashFade(), CG_DrawFlashFire(), CG_DrawFlashZoomTransition(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawPMItemsBig(), CG_DrawScoreboard(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawSpeed(), CG_DrawTeamInfo(), CG_DrawTimerNormal(), CG_DrawWarmup(), CG_GameStatsDraw(), CG_Hud_Setup(), CG_ObjectivesDraw(), CG_RectParse(), CG_removeStrings(), CG_ScreenFade(), CG_setDefaultHudValues(), CG_TopShotsDraw(), CG_windowNormalizeOnText(), CG_WorldCoordToScreenCoordFloat(), and WM_DrawInfoLine().
float Ccg_WideXoffset (void)
Ccg_WideXoffset.
Returns
Definition at line 87 of file cg_drawtools.c.
Referenced by CG_DrawInformation().
void CG_AddOnScreenText (const char * text, vec3_t origin)
CG_AddOnScreenText.
Parameters
[in] text
[in] origin
Definition at line 750 of file cg_drawtools.c.
Referenced by CG_EntityFloatText(), and CG_PlayerFloatText().
void CG_AdjustFrom640 (float * x, float * y, float * w, float * h)
Adjusted for resolution and screen aspect ratio.
Parameters
[out] x
[out] y
[out] w
[out] h
Definition at line 45 of file cg_drawtools.c.
Referenced by CG_CalcVrect(), CG_DrawBottom_NoScale(), CG_DrawCrosshair(), CG_DrawExpandedAutoMap(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawMap(), CG_DrawNoShootIcon(), CG_DrawPic(), CG_DrawPicST(), CG_DrawPlayerHead(), CG_DrawRotatedPic(), CG_DrawSides(), CG_DrawSides_NoScale(), CG_DrawSkillBar(), CG_DrawTopBottom(), CG_DrawTopBottom_NoScale(), CG_FillRect(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounterNumber(), CG_SpeakerEditorDraw(), CG_Text_PaintChar(), and CG_Text_PaintChar_Ext().
void CG_ColorForHealth (vec4_t hcolor)
CG_ColorForHealth.
Parameters
[in] hcolor
Definition at line 639 of file cg_drawtools.c.
Referenced by CG_DrawCrosshair(), CG_DrawFireTeamOverlay(), and CG_DrawPlayerHealthBar().
void CG_DrawBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawBottom_NoScale.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 346 of file cg_drawtools.c.
Referenced by WM_TeamScoreboard().
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
CG_DrawPic.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] hShader
Note
Coordinates are 640*480 virtual values
Definition at line 419 of file cg_drawtools.c.
Referenced by CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_DemoClick(), CG_Draw2D(), CG_DrawBinocReticle(), CG_DrawBorder(), CG_DrawBreathBar(), CG_DrawCompassIcon(), CG_DrawConnectScreen(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawDisconnect(), CG_DrawField(), CG_DrawFireTeamOverlay(), CG_DrawFlashFire(), CG_DrawFollow(), CG_DrawLivesLeft(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNewCompass(), CG_DrawObjectiveInfo(), CG_DrawPicShadowed(), CG_DrawPlayerHealthBar(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawScopedReticle(), CG_DrawSkills(), CG_DrawSpawnPointInfo(), CG_DrawStaminaBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawWeapRecharge(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_Draw(), CG_LimboPanel_Filter_Draw(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderLight(), CG_LimboPanel_RenderMedal(), CG_LimboPanel_RenderObjectiveBack(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_SpawnPointButton_Draw(), CG_LimboPanel_WeaponLights(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_MapVoteList_Draw(), CG_ObjectivesDraw(), CG_SpeakerEditorDraw(), CG_windowDraw(), WM_DrawClientScore(), WM_DrawClientScore_Small(), and WM_DrawObjectives().
void CG_DrawPicST (float x, float y, float width, float height, float s0, float t0, float s1, float t1, qhandle_t hShader)
Allows passing of st co-ords.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] s0
[in] t0
[in] s1
[in] t1
[in] hShader
Note
Coordinates are 640*480 virtual values
Definition at line 404 of file cg_drawtools.c.
Referenced by CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_DrawBorder(), CG_DrawFlag(), CG_LimboPanel_RenderHead(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadPanel_RenderLoadingBar(), and WM_TeamScoreboard().
void CG_DrawRect (float x, float y, float width, float height, float size, const float * color)
CG_DrawRect.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] size
[in,out] color
Note
Coordinates are 640*480 virtual values
Definition at line 362 of file cg_drawtools.c.
Referenced by CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawDemoControls(), CG_DrawFireTeamOverlay(), CG_DrawObjectiveInfo(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_LoadHudMenu(), CG_ObjectivesDraw(), CG_SpeakerEditor_Back(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerInfo_Text(), CG_TopShotsDraw(), and CG_windowDraw().
void CG_DrawRect_FixedBorder (float x, float y, float width, float height, int border, const float * color)
CG_DrawRect_FixedBorder.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] border
[in,out] color
Definition at line 381 of file cg_drawtools.c.
Referenced by CG_Debriefing_Scrollbar_Draw(), CG_DemoClick(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSkillBar(), CG_DrawSnapshot(), CG_DrawSpeed(), CG_DrawTimerNormal(), CG_FilledBar(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void CG_DrawRotatedPic (float x, float y, float width, float height, qhandle_t hShader, float angle)
CG_DrawRotatedPic.
Clear around a sized down screen
Parameters
[in] x
[in] y
[in] width
[in] height
[in] hShader
[in] angle
Definition at line 464 of file cg_drawtools.c.
Referenced by CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMortarMarker(), and CG_DrawNewCompass().
void CG_DrawSides (float x, float y, float w, float h, float size)
CG_DrawSides.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 280 of file cg_drawtools.c.
Referenced by CG_DrawRect(), and CG_LoadHudMenu().
void CG_DrawSides_NoScale (float x, float y, float w, float h, float size)
CG_DrawSides_NoScale.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 314 of file cg_drawtools.c.
Referenced by CG_DrawRect_FixedBorder().
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
CG_DrawTopBottom.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 297 of file cg_drawtools.c.
Referenced by CG_DrawRect(), and CG_LoadHudMenu().
void CG_DrawTopBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawTopBottom_NoScale.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 330 of file cg_drawtools.c.
Referenced by CG_DrawRect_FixedBorder().
float* CG_FadeColor (int startMsec, int totalMsec)
CG_FadeColor.
Parameters
[in] startMsec
[in] totalMsec
Returns
Definition at line 529 of file cg_drawtools.c.
Referenced by CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), and CG_DrawScoreboard().
void CG_FilledBar (float x, float y, float w, float h, float * startColor, float * endColor, const float * bgColor, float frac, int flags)
CG_FilledBar.
Parameters
[in] x
[in] y
[in] w
[in] h
[in,out] startColor
[in,out] endColor
[in,out] bgColor
[in] frac
[in] flags
Todo:
: remember to swap colors on the ends here
Todo:
: remember to swap colors on the ends here
Definition at line 146 of file cg_drawtools.c.
Referenced by CG_DemoControlButtonRender(), CG_DrawBreathBar(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawPlayerHealthBar(), CG_DrawStaminaBar(), CG_DrawWeapHeat(), CG_DrawWeapRecharge(), CG_DrawWeapStability(), and CG_HorizontalPercentBar().
void CG_FillRect (float x, float y, float width, float height, const float * color)
CG_FillRect.
Parameters
[in] x
[in] y
[in] width
[in] height
[in,out] color
Note
Coordinates are 640*480 virtual values
Definition at line 101 of file cg_drawtools.c.
Referenced by CG_Debriefing_Maps_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_Scrollbar_Draw(), CG_DebriefingPlayerList_Draw(), CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawBinocReticle(), CG_DrawBorder(), CG_DrawDemoControls(), CG_DrawFireTeamOverlay(), CG_DrawFlashDamage(), CG_DrawFlashFade(), CG_DrawFlashZoomTransition(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawMortarReticle(), CG_DrawPing(), CG_DrawScopedReticle(), CG_DrawSkillBar(), CG_DrawSnapshot(), CG_DrawSpeed(), CG_DrawStatsDebug(), CG_DrawTimerNormal(), CG_FilledBar(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_LimboPanel_RenderHead(), CG_LoadHudMenu(), CG_MapVoteList_Draw(), CG_ObjectivesDraw(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_ScreenFade(), CG_SpeakerEditor_Back(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerEditor_RenderEdit(), CG_SpeakerInfo_Text(), CG_TopShotsDraw(), CG_windowDraw(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void CG_GetColorForHealth (int health, vec4_t hcolor)
CG_GetColorForHealth.
Parameters
[in] health
[in] hcolor
Note
Unused
Definition at line 594 of file cg_drawtools.c.
void CG_HorizontalPercentBar (float x, float y, float width, float height, float percent)
Generic routine for pretty much all status indicators that show a fractional value to the player by virtue of how full a drawn box is.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] percent
Note
Unused
Definition at line 264 of file cg_drawtools.c.
float* CG_TeamColor (int team)
CG_TeamColor.
Parameters
[in] team
Returns
Note
Unused
Definition at line 572 of file cg_drawtools.c.
void CG_TileClear (void)
CG_TileClear.
Clear around a sized down screen
Definition at line 493 of file cg_drawtools.c.
Referenced by CG_DrawActive().
static void CG_TileClearBox (int x, int y, int w, int h, qhandle_t hShader) static
This repeats a 64*64 tile graphic to fill the screen around a sized down refresh window.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] hShader
Definition at line 479 of file cg_drawtools.c.
Referenced by CG_TileClear().
const char* CG_TranslateString (const char * string)
CG_TranslateString.
Parameters
[in] string
Returns
Definition at line 688 of file cg_drawtools.c.
Referenced by CG_BuddyVoiceChat_f(), CG_Class_f(), CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatButton_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_WinStringForTeam(), CG_DebriefingTitle_Draw(), CG_DemoClick(), CG_DemoHelpDraw(), CG_DrawCrosshairNames(), CG_DrawDemoControls(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawScoreboard(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawVote(), CG_DrawWarmup(), CG_dumpStats(), CG_findClientNum(), CG_Fireteams_MenuText_Draw(), CG_Fireteams_MenuTitleText_Draw(), CG_FTSayPlayerClass_f(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_GetPMItemText(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_ItemPickup(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_WeaponPanel(), CG_LoadHudMenu(), CG_LoadPanel_GameTypeName(), CG_LocalizeServerCommand(), CG_MapVoteList_Draw(), CG_NewClientInfo(), CG_Obituary(), CG_ObjectivePrint(), CG_ObjectivesDraw(), CG_ParseSpawns(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_ParseWolfinfo(), CG_PickupItemText(), CG_SayPlayerClass_f(), CG_ServerCommand(), CG_Spawnpoints_MenuTitleText_Draw(), CG_SpawnpointsCheckExecKey(), CG_TeamVoiceChat_f(), CG_TopShotsDraw(), CG_TouchTriggerPrediction(), CG_VoiceChatLocal(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
qboolean CG_WorldCoordToScreenCoordFloat (vec3_t point, float * x, float * y)
Float a sprite over the player's head added height parameter.
Parameters
point
[out] x
[out] y
Returns
Definition at line 711 of file cg_drawtools.c.
Referenced by CG_AddOnScreenText().
Variable Documentation
vec4_t blue = { 0.2f, 0.2f, 1.0f, 1.0f } static
Definition at line 561 of file cg_drawtools.c.
Referenced by CG_TeamColor(), GL_ClearColor(), GL_ColorMask(), LoadRGBEToFloats(), R_LoadBMP(), and R_LoadTGA().
vec4_t other = { 1.0f, 1.0f, 1.0f, 1.0f } static
Definition at line 562 of file cg_drawtools.c.
Referenced by CG_TeamColor(), checkpoint_spawntouch(), checkpoint_touch(), checkpoint_use(), CheckVote(), ClientImpacts(), Cmd_God_f(), Cmd_Vote_f(), G_FreeSatchel(), G_MissileImpact(), G_Say(), G_SendSystemMessage(), GibEntity(), Pickup_Team(), SP_Props_Locker_Tall(), Team_TouchEnemyFlag(), Think_SpawnNewDoorTrigger(), Touch_flagonly(), Touch_flagonly_multiple(), and Z_Free().
vec4_t red = { 1.0f, 0.2f, 0.2f, 1.0f } static
Definition at line 560 of file cg_drawtools.c.
Referenced by CG_TeamColor(), GL_ClearColor(), GL_ColorMask(), LoadRGBEToFloats(), R_LoadBMP(), R_LoadTGA(), and R_MakeIntensity().
vec4_t spectator = { 0.7f, 0.7f, 0.7f, 1.0f } static
Definition at line 563 of file cg_drawtools.c.
Referenced by CG_TeamColor(), and CG_TouchTriggerPrediction().