ET: Legacy: src/cgame/cg_sound.c File Reference
cg_sound.c File Reference
Parsing and use of sound script files.
#include "cg_local.h"
Data Structures
struct editHandle_s
Macros
#define FILE_HASH_SIZE 1024
#define generateHashValue(fname) Q_GenerateHashValue(fname, FILE_HASH_SIZE, qfalse, qtrue)
#define MAX_SOUND_SCRIPTS 1024
#define MAX_SOUND_SCRIPT_SOUNDS 4096
#define MAX_SOUND_FILES 16
Typedefs
typedef struct editHandle_s editHandle_t
Functions
int CG_SoundScriptPrecache (const char *name)
CG_SoundScriptPrecache.
int CG_SoundPickOldestRandomSound (soundScript_t *sound, vec3_t org, int entnum)
CG_SoundPickOldestRandomSound.
void CG_AddBufferedSoundScript (soundScript_t *sound)
CG_AddBufferedSoundScript.
void CG_UpdateBufferedSoundScripts (void)
CG_UpdateBufferedSoundScripts.
int CG_SoundPlaySoundScript (const char *name, vec3_t org, int entnum, qboolean buffer)
CG_SoundPlaySoundScript.
void CG_SoundPlayIndexedScript (int index, vec3_t org, int entnum)
CG_SoundPlayIndexedScript.
static void CG_SoundParseSounds (const char *filename, char *buffer)
CG_SoundParseSounds.
static void CG_SoundLoadSoundFiles (void)
CG_SoundLoadSoundFiles.
void CG_SoundInit (void)
CG_SoundInit.
qboolean CG_SaveSpeakersToScript (void)
CG_SaveSpeakersToScript.
void CG_AddLineToScene (vec3_t start, vec3_t end, vec4_t colour)
CG_AddLineToScene.
void CG_SetViewanglesForSpeakerEditor (void)
CG_SetViewanglesForSpeakerEditor.
static void CG_RenderScriptSpeakers (void)
CG_RenderScriptSpeakers.
void CG_SpeakerInfo_Text (panel_button_t *button)
CG_SpeakerInfo_Text.
void CG_SpeakerEditor_RenderEdit (panel_button_t *button)
CG_SpeakerEditor_RenderEdit.
void CG_SpeakerEditor_RenderButton (panel_button_t *button)
CG_SpeakerEditor_RenderButton.
char * CG_GetStrFromStrArray (const char *in, const int index)
CG_GetStrFromStrArray.
void CG_SpeakerEditor_RenderDropdown (panel_button_t *button)
CG_SpeakerEditor_RenderDropdown.
void CG_SpeakerEditor_Back (panel_button_t *button)
CG_SpeakerEditor_Back.
void CG_SpeakerEditor_LocInfo (panel_button_t *button)
CG_SpeakerEditor_LocInfo.
qboolean CG_SpeakerEditor_NoiseEdit_KeyDown (panel_button_t *button, int key)
CG_SpeakerEditor_NoiseEdit_KeyDown.
void CG_SpeakerEditor_NoiseEditFinish (panel_button_t *button)
CG_SpeakerEditor_NoiseEditFinish.
void CG_SpeakerEditor_TargetnameEditFinish (panel_button_t *button)
CG_SpeakerEditor_TargetnameEditFinish.
qboolean CG_SpeakerEditor_Dropdown_KeyDown (panel_button_t *button, int key)
CG_SpeakerEditor_Dropdown_KeyDown.
qboolean CG_SpeakerEditor_Looped_KeyUp (panel_button_t *button, int key)
CG_SpeakerEditor_Looped_KeyUp.
qboolean CG_SpeakerEditor_Broadcast_KeyUp (panel_button_t *button, int key)
CG_SpeakerEditor_Broadcast_KeyUp.
void CG_SpeakerEditor_WaitEditFinish (panel_button_t *button)
CG_SpeakerEditor_WaitEditFinish.
void CG_SpeakerEditor_RandomEditFinish (panel_button_t *button)
CG_SpeakerEditor_RandomEditFinish.
void CG_SpeakerEditor_VolumeEditFinish (panel_button_t *button)
CG_SpeakerEditor_VolumeEditFinish.
void CG_SpeakerEditor_RangeEditFinish (panel_button_t *button)
CG_SpeakerEditor_RangeEditFinish.
qboolean CG_SpeakerEditor_Ok_KeyDown (panel_button_t *button, int key)
CG_SpeakerEditor_Ok_KeyDown.
qboolean CG_SpeakerEditor_Ok_KeyUp (panel_button_t *button, int key)
CG_SpeakerEditor_Ok_KeyUp.
qboolean CG_SpeakerEditor_Cancel_KeyDown (panel_button_t *button, int key)
CG_SpeakerEditor_Cancel_KeyDown.
qboolean CG_SpeakerEditor_Cancel_KeyUp (panel_button_t *button, int key)
CG_SpeakerEditor_Cancel_KeyUp.
qboolean CG_SpeakerEditor_Delete_KeyDown (panel_button_t *button, int key)
CG_SpeakerEditor_Delete_KeyDown.
qboolean CG_SpeakerEditor_Delete_KeyUp (panel_button_t *button, int key)
CG_SpeakerEditor_Delete_KeyUp.
void CG_SpeakerEditorDraw (void)
CG_SpeakerEditorDraw.
void CG_SpeakerEditor_KeyHandling (int key, qboolean down)
CG_SpeakerEditor_KeyHandling.
void CG_SpeakerEditorMouseMove_Handling (int x, int y)
CG_SpeakerEditorMouseMove_Handling.
void CG_ActivateEditSoundMode (void)
CG_ActivateEditSoundMode.
void CG_DeActivateEditSoundMode (void)
CG_DeActivateEditSoundMode.
void CG_ModifyEditSpeaker (void)
CG_ModifyEditSpeaker.
void CG_UndoEditSpeaker (void)
CG_UndoEditSpeaker.
void CG_ToggleActiveOnScriptSpeaker (int index)
CG_ToggleActiveOnScriptSpeaker.
void CG_UnsetActiveOnScriptSpeaker (int index)
CG_UnsetActiveOnScriptSpeaker.
void CG_SetActiveOnScriptSpeaker (int index)
CG_SetActiveOnScriptSpeaker.
static void CG_PlayScriptSpeaker (bg_speaker_t *speaker, qboolean global)
CG_PlayScriptSpeaker.
void CG_AddScriptSpeakers (void)
CG_AddScriptSpeakers.
Variables
static soundScript_t * hashTable [FILE_HASH_SIZE]
static soundScript_t soundScripts [MAX_SOUND_SCRIPTS]
int numSoundScripts = 0
static soundScriptSound_t soundScriptSounds [MAX_SOUND_SCRIPT_SOUNDS]
int numSoundScriptSounds = 0
char bigTextBuffer [100000]
static qhandle_t speakerShader = 0
static qhandle_t speakerShaderGrayScale = 0
static bg_speaker_t * editSpeaker = NULL
static bg_speaker_t undoSpeaker
static int undoSpeakerIndex
static qboolean editSpeakerActive = qfalse
static editHandle_t editSpeakerHandle
static int numSpeakersInPvs
static const char * s_lt_string []
static const char * s_bt_string []
panel_button_text_t speakerEditorTxt
panel_button_t speakerInfo
static panel_button_t * speakerInfoButtons []
static char noiseMatchString [MAX_QPATH]
static int noiseMatchCount
static int noiseMatchIndex
panel_button_t speakerEditorBack
panel_button_t speakerEditorLocInfo
panel_button_t speakerEditorNoiseLabel
char noiseEditBuffer [MAX_QPATH]
panel_button_t speakerEditorNoiseEdit
panel_button_t speakerEditorTargetnameLabel
char targetnameEditBuffer [32]
panel_button_t speakerEditorTargetnameEdit
panel_button_t speakerEditorLoopedLabel
panel_button_t speakerEditorLoopedDropdown
panel_button_t speakerEditorBroadcastLabel
panel_button_t speakerEditorBroadcastDropdown
panel_button_t speakerEditorWaitLabel
char waitEditBuffer [12]
panel_button_t speakerEditorWaitEdit
panel_button_t speakerEditorRandomLabel
char randomEditBuffer [12]
panel_button_t speakerEditorRandomEdit
panel_button_t speakerEditorVolumeLabel
char volumeEditBuffer [12]
panel_button_t speakerEditorVolumeEdit
panel_button_t speakerEditorRangeLabel
char rangeEditBuffer [12]
panel_button_t speakerEditorRangeEdit
panel_button_t speakerEditorOkButton
panel_button_t speakerEditorCancelButton
panel_button_t speakerEditorDeleteButton
static panel_button_t * speakerEditorButtons []
Detailed Description
Parsing and use of sound script files.
Definition in file cg_sound.c.
Macro Definition Documentation
#define FILE_HASH_SIZE 1024
Definition at line 40 of file cg_sound.c.
#define generateHashValue (fname) Q_GenerateHashValue(fname, FILE_HASH_SIZE, qfalse, qtrue)
Definition at line 42 of file cg_sound.c.
Referenced by CG_SoundParseSounds(), CG_SoundPlaySoundScript(), CG_SoundScriptPrecache(), FindShaderInShaderTextR1(), and ScanAndLoadShaderFilesR1().
#define MAX_SOUND_FILES 16
Decreased from 128 - ET uses 3! (2 x team voice & map)
Definition at line 452 of file cg_sound.c.
Referenced by CG_SoundLoadSoundFiles().
#define MAX_SOUND_SCRIPT_SOUNDS 4096
Definition at line 48 of file cg_sound.c.
Referenced by CG_SoundParseSounds().
#define MAX_SOUND_SCRIPTS 1024
Definition at line 44 of file cg_sound.c.
Referenced by CG_SoundParseSounds().
Typedef Documentation
typedef struct editHandle_s editHandle_t
Function Documentation
void CG_ActivateEditSoundMode (void)
CG_ActivateEditSoundMode.
Definition at line 2377 of file cg_sound.c.
Referenced by CG_EditSpeakers_f().
void CG_AddBufferedSoundScript (soundScript_t * sound)
CG_AddBufferedSoundScript.
Parameters
[in] sound
Definition at line 154 of file cg_sound.c.
Referenced by CG_SoundPlaySoundScript().
void CG_AddLineToScene (vec3_t start, vec3_t end, vec4_t colour)
CG_AddLineToScene.
Parameters
[in] start
[in] end
[in] colour
Definition at line 693 of file cg_sound.c.
Referenced by CG_RenderScriptSpeakers().
void CG_AddScriptSpeakers (void)
CG_AddScriptSpeakers.
Definition at line 2555 of file cg_sound.c.
Referenced by CG_DrawActiveFrame().
void CG_DeActivateEditSoundMode (void)
CG_DeActivateEditSoundMode.
Definition at line 2400 of file cg_sound.c.
Referenced by CG_EditSpeakers_f().
char* CG_GetStrFromStrArray (const char * in, const int index)
CG_GetStrFromStrArray.
Parameters
[in] in
[in] index
Returns
Definition at line 1131 of file cg_sound.c.
Referenced by CG_SpeakerEditor_RenderDropdown().
void CG_ModifyEditSpeaker (void)
CG_ModifyEditSpeaker.
Definition at line 2419 of file cg_sound.c.
Referenced by CG_ModifySpeaker_f(), and CG_SpeakerEditor_KeyHandling().
static void CG_PlayScriptSpeaker (bg_speaker_t * speaker, qboolean global) static
CG_PlayScriptSpeaker.
Parameters
[in,out] speaker
[in] global
Definition at line 2527 of file cg_sound.c.
Referenced by CG_AddScriptSpeakers().
static void CG_RenderScriptSpeakers (void) static
CG_RenderScriptSpeakers.
Definition at line 729 of file cg_sound.c.
Referenced by CG_AddScriptSpeakers().
qboolean CG_SaveSpeakersToScript (void)
CG_SaveSpeakersToScript.
Returns
Definition at line 597 of file cg_sound.c.
Referenced by CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditor_Ok_KeyUp(), and CG_UndoEditSpeaker().
void CG_SetActiveOnScriptSpeaker (int index)
CG_SetActiveOnScriptSpeaker.
Parameters
[in] index
Definition at line 2512 of file cg_sound.c.
Referenced by CG_EntityEvent().
void CG_SetViewanglesForSpeakerEditor (void)
CG_SetViewanglesForSpeakerEditor.
Definition at line 713 of file cg_sound.c.
Referenced by CG_CalcViewValues().
void CG_SoundInit (void)
CG_SoundInit.
Definition at line 535 of file cg_sound.c.
Referenced by CG_MapRestart(), and CG_RegisterSounds().
static void CG_SoundLoadSoundFiles (void) static
CG_SoundLoadSoundFiles.
Definition at line 457 of file cg_sound.c.
Referenced by CG_SoundInit().
static void CG_SoundParseSounds (const char * filename, char * buffer) static
CG_SoundParseSounds.
Parameters
[in] filename
[in,out] buffer
Definition at line 275 of file cg_sound.c.
Referenced by CG_SoundLoadSoundFiles().
int CG_SoundPickOldestRandomSound (soundScript_t * sound, vec3_t org, int entnum)
CG_SoundPickOldestRandomSound.
Parameters
[in] sound
[in] org
[in] entnum
Returns
Todo:
: make compressed settable through the soundscript
Definition at line 106 of file cg_sound.c.
Referenced by CG_AddBufferedSoundScript(), CG_SoundPlayIndexedScript(), CG_SoundPlaySoundScript(), and CG_UpdateBufferedSoundScripts().
void CG_SoundPlayIndexedScript (int index, vec3_t org, int entnum)
CG_SoundPlayIndexedScript.
Parameters
[in] index
[in] org
[in] entnum
Definition at line 251 of file cg_sound.c.
Referenced by CG_Init().
int CG_SoundPlaySoundScript (const char * name, vec3_t org, int entnum, qboolean buffer)
CG_SoundPlaySoundScript.
Parameters
name
org
entnum
buffer
Returns
qtrue if a script is found
Definition at line 207 of file cg_sound.c.
Referenced by CG_CheckLocalSounds(), CG_EntityEvent(), CG_LimboPanel_BriefingButton_KeyDown(), CG_NewClientInfo(), CG_PlayGlobalSound(), CG_PlayPMItemSound(), and CG_ServerCommand().
int CG_SoundScriptPrecache (const char * name)
CG_SoundScriptPrecache.
Parameters
name
Returns
The index+1 of the script in the global list, for fast calling
Definition at line 57 of file cg_sound.c.
Referenced by CG_ConfigStringModified(), CG_Init(), CG_RegisterSounds(), and CG_SoundParseSounds().
void CG_SpeakerEditor_Back (panel_button_t * button)
CG_SpeakerEditor_Back.
Parameters
[in] button
Definition at line 1286 of file cg_sound.c.
qboolean CG_SpeakerEditor_Broadcast_KeyUp (panel_button_t * button, int key)
CG_SpeakerEditor_Broadcast_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 1535 of file cg_sound.c.
qboolean CG_SpeakerEditor_Cancel_KeyDown (panel_button_t * button, int key)
CG_SpeakerEditor_Cancel_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1715 of file cg_sound.c.
qboolean CG_SpeakerEditor_Cancel_KeyUp (panel_button_t * button, int key)
CG_SpeakerEditor_Cancel_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 1732 of file cg_sound.c.
qboolean CG_SpeakerEditor_Delete_KeyDown (panel_button_t * button, int key)
CG_SpeakerEditor_Delete_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1761 of file cg_sound.c.
qboolean CG_SpeakerEditor_Delete_KeyUp (panel_button_t * button, int key)
CG_SpeakerEditor_Delete_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 1778 of file cg_sound.c.
qboolean CG_SpeakerEditor_Dropdown_KeyDown (panel_button_t * button, int key)
CG_SpeakerEditor_Dropdown_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1467 of file cg_sound.c.
void CG_SpeakerEditor_KeyHandling (int key, qboolean down)
CG_SpeakerEditor_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 2247 of file cg_sound.c.
Referenced by CG_KeyEvent().
void CG_SpeakerEditor_LocInfo (panel_button_t * button)
CG_SpeakerEditor_LocInfo.
Parameters
[in] button
Definition at line 1301 of file cg_sound.c.
qboolean CG_SpeakerEditor_Looped_KeyUp (panel_button_t * button, int key)
CG_SpeakerEditor_Looped_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 1484 of file cg_sound.c.
qboolean CG_SpeakerEditor_NoiseEdit_KeyDown (panel_button_t * button, int key)
CG_SpeakerEditor_NoiseEdit_KeyDown.
Parameters
[in] button
[in] key
Returns
Todo:
: autocomplete directories?
Definition at line 1318 of file cg_sound.c.
void CG_SpeakerEditor_NoiseEditFinish (panel_button_t * button)
CG_SpeakerEditor_NoiseEditFinish.
Parameters
[in] button
Definition at line 1438 of file cg_sound.c.
qboolean CG_SpeakerEditor_Ok_KeyDown (panel_button_t * button, int key)
CG_SpeakerEditor_Ok_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1670 of file cg_sound.c.
qboolean CG_SpeakerEditor_Ok_KeyUp (panel_button_t * button, int key)
CG_SpeakerEditor_Ok_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 1687 of file cg_sound.c.
void CG_SpeakerEditor_RandomEditFinish (panel_button_t * button)
CG_SpeakerEditor_RandomEditFinish.
Parameters
[in] button
Definition at line 1597 of file cg_sound.c.
void CG_SpeakerEditor_RangeEditFinish (panel_button_t * button)
CG_SpeakerEditor_RangeEditFinish.
Parameters
[in] button
Definition at line 1646 of file cg_sound.c.
void CG_SpeakerEditor_RenderButton (panel_button_t * button)
CG_SpeakerEditor_RenderButton.
Parameters
[in] button
Definition at line 1092 of file cg_sound.c.
void CG_SpeakerEditor_RenderDropdown (panel_button_t * button)
CG_SpeakerEditor_RenderDropdown.
Parameters
[in] button
Definition at line 1162 of file cg_sound.c.
void CG_SpeakerEditor_RenderEdit (panel_button_t * button)
CG_SpeakerEditor_RenderEdit.
Parameters
[in] button
Definition at line 1065 of file cg_sound.c.
void CG_SpeakerEditor_TargetnameEditFinish (panel_button_t * button)
CG_SpeakerEditor_TargetnameEditFinish.
Parameters
[in] button
Definition at line 1456 of file cg_sound.c.
void CG_SpeakerEditor_VolumeEditFinish (panel_button_t * button)
CG_SpeakerEditor_VolumeEditFinish.
Parameters
[in] button
Definition at line 1619 of file cg_sound.c.
void CG_SpeakerEditor_WaitEditFinish (panel_button_t * button)
CG_SpeakerEditor_WaitEditFinish.
Parameters
[in] button
Definition at line 1575 of file cg_sound.c.
void CG_SpeakerEditorDraw (void)
CG_SpeakerEditorDraw.
Definition at line 2139 of file cg_sound.c.
Referenced by CG_Draw2D().
void CG_SpeakerEditorMouseMove_Handling (int x, int y)
CG_SpeakerEditorMouseMove_Handling.
Parameters
[in] x
[in] y
Definition at line 2325 of file cg_sound.c.
Referenced by CG_MouseEvent().
void CG_SpeakerInfo_Text (panel_button_t * button)
CG_SpeakerInfo_Text.
Parameters
[in] button
Definition at line 896 of file cg_sound.c.
void CG_ToggleActiveOnScriptSpeaker (int index)
CG_ToggleActiveOnScriptSpeaker.
Parameters
[in] index
Definition at line 2484 of file cg_sound.c.
Referenced by CG_EntityEvent().
void CG_UndoEditSpeaker (void)
CG_UndoEditSpeaker.
Definition at line 2448 of file cg_sound.c.
Referenced by CG_UndoSpeaker_f().
void CG_UnsetActiveOnScriptSpeaker (int index)
CG_UnsetActiveOnScriptSpeaker.
Parameters
[in] index
Definition at line 2498 of file cg_sound.c.
Referenced by CG_EntityEvent().
void CG_UpdateBufferedSoundScripts (void)
CG_UpdateBufferedSoundScripts.
Definition at line 172 of file cg_sound.c.
Referenced by CG_DrawActiveFrame().
Variable Documentation
char bigTextBuffer[100000]
Definition at line 38 of file cg_character.c.
Referenced by CG_SoundLoadSoundFiles(), CG_SoundParseSounds(), and CG_SpeakerEditor_NoiseEdit_KeyDown().
bg_speaker_t* editSpeaker = NULL static
Definition at line 572 of file cg_sound.c.
qboolean editSpeakerActive = qfalse static
Definition at line 575 of file cg_sound.c.
Referenced by CG_ActivateEditSoundMode(), CG_DeActivateEditSoundMode(), CG_ModifyEditSpeaker(), CG_RenderScriptSpeakers(), CG_SetViewanglesForSpeakerEditor(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditor_Ok_KeyUp(), CG_SpeakerEditorDraw(), and CG_SpeakerEditorMouseMove_Handling().
editHandle_t editSpeakerHandle static
Definition at line 576 of file cg_sound.c.
soundScript_t* hashTable[FILE_HASH_SIZE] static
Definition at line 41 of file cg_sound.c.
Referenced by NewVertexHashTable().
char noiseEditBuffer[MAX_QPATH]
Definition at line 1844 of file cg_sound.c.
Referenced by CG_ModifyEditSpeaker().
int noiseMatchCount static
Definition at line 1309 of file cg_sound.c.
Referenced by CG_SpeakerEditor_NoiseEdit_KeyDown().
int noiseMatchIndex static
Definition at line 1310 of file cg_sound.c.
Referenced by CG_SpeakerEditor_NoiseEdit_KeyDown().
char noiseMatchString[MAX_QPATH] static
Definition at line 1308 of file cg_sound.c.
Referenced by CG_SpeakerEditor_NoiseEdit_KeyDown().
int numSoundScripts = 0
Definition at line 46 of file cg_sound.c.
Referenced by CG_SoundInit(), CG_SoundLoadSoundFiles(), CG_SoundParseSounds(), and CG_SoundPlayIndexedScript().
int numSoundScriptSounds = 0
Definition at line 50 of file cg_sound.c.
Referenced by CG_SoundInit(), and CG_SoundParseSounds().
int numSpeakersInPvs static
Definition at line 577 of file cg_sound.c.
Referenced by CG_RenderScriptSpeakers(), and CG_SpeakerEditorDraw().
char randomEditBuffer[12]
Definition at line 1990 of file cg_sound.c.
Referenced by CG_ModifyEditSpeaker().
char rangeEditBuffer[12]
Definition at line 2050 of file cg_sound.c.
Referenced by CG_ModifyEditSpeaker().
const char* s_bt_string[] static
Initial value:
=
{
    "no",
    "global",
    "nopvs"
}
Definition at line 586 of file cg_sound.c.
Referenced by CG_SaveSpeakersToScript(), and CG_SpeakerInfo_Text().
const char* s_lt_string[] static
Initial value:
=
{
    "no",
    "on",
    "off"
}
Definition at line 579 of file cg_sound.c.
Referenced by CG_SaveSpeakersToScript(), and CG_SpeakerInfo_Text().
soundScript_t soundScripts[MAX_SOUND_SCRIPTS] static
Definition at line 45 of file cg_sound.c.
soundScriptSound_t soundScriptSounds[MAX_SOUND_SCRIPT_SOUNDS] static
Definition at line 49 of file cg_sound.c.
panel_button_t speakerEditorBack
Initial value:
=
{
    NULL,
    NULL,
    { 360,                330,   272, 142 },
    { 0,                  0,     0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    CG_SpeakerEditor_Back,
    NULL,
    0,
}
Definition at line 1802 of file cg_sound.c.
panel_button_t speakerEditorBroadcastDropdown
Initial value:
=
{
    NULL,
    "no\0global\0nopvs",
    { 430,                          386,60, 12 },
    { 3,                            0,  0,  0, 0, 0, 0, 0},
    &speakerEditorTxt,
    CG_SpeakerEditor_Dropdown_KeyDown,
    CG_SpeakerEditor_Broadcast_KeyUp,
    CG_SpeakerEditor_RenderDropdown,
    NULL,
    0,
}
Definition at line 1932 of file cg_sound.c.
panel_button_t speakerEditorBroadcastLabel
Initial value:
=
{
    NULL,
    "Broadcast:",
    { 361,                     386 + 9,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 1918 of file cg_sound.c.
panel_button_t* speakerEditorButtons[] static
Initial value:
=
{
    &speakerEditorBack,
    &speakerEditorLocInfo,
    &speakerEditorNoiseLabel,
    &speakerEditorNoiseEdit,
    &speakerEditorTargetnameLabel,
    &speakerEditorTargetnameEdit,
    &speakerEditorLoopedLabel,
    &speakerEditorBroadcastLabel,
    &speakerEditorWaitLabel,
    &speakerEditorWaitEdit,
    &speakerEditorRandomLabel,
    &speakerEditorRandomEdit,
    &speakerEditorVolumeLabel,
    &speakerEditorVolumeEdit,
    &speakerEditorRangeLabel,
    &speakerEditorRangeEdit,
    &speakerEditorOkButton,
    &speakerEditorCancelButton,
    &speakerEditorDeleteButton,
    &speakerEditorBroadcastDropdown,
    &speakerEditorLoopedDropdown,
    NULL
}
Definition at line 2108 of file cg_sound.c.
panel_button_t speakerEditorCancelButton
Initial value:
=
{
    NULL,
    "Cancel",
    { 461,                        458,70, 12 },
    { 0,                          0,  0,  0, 0, 0, 0, 0},
    &speakerEditorTxt,
    CG_SpeakerEditor_Cancel_KeyDown,
    CG_SpeakerEditor_Cancel_KeyUp,
    CG_SpeakerEditor_RenderButton,
    NULL,
    0,
}
Definition at line 2080 of file cg_sound.c.
panel_button_t speakerEditorDeleteButton
Initial value:
=
{
    NULL,
    "Delete",
    { 546,                        458,70, 12 },
    { 0,                          0,  0,  0, 0, 0, 0, 0},
    &speakerEditorTxt,
    CG_SpeakerEditor_Delete_KeyDown,
    CG_SpeakerEditor_Delete_KeyUp,
    CG_SpeakerEditor_RenderButton,
    NULL,
    0,
}
Definition at line 2094 of file cg_sound.c.
panel_button_t speakerEditorLocInfo
Initial value:
=
{
    NULL,
    NULL,
    { 361,                   330 + 9,   272, 10 },
    { 0,                     0,         0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    CG_SpeakerEditor_LocInfo,
    NULL,
    0,
}
Definition at line 1816 of file cg_sound.c.
panel_button_t speakerEditorLoopedDropdown
Initial value:
=
{
    NULL,
    "no\0on\0off",
    { 430,                          372,60, 12 },
    { 3,                            0,  0,  0, 0, 0, 0, 0},
    &speakerEditorTxt,
    CG_SpeakerEditor_Dropdown_KeyDown,
    CG_SpeakerEditor_Looped_KeyUp,
    CG_SpeakerEditor_RenderDropdown,
    NULL,
    0,
}
Definition at line 1904 of file cg_sound.c.
panel_button_t speakerEditorLoopedLabel
Initial value:
=
{
    NULL,
    "Looped:",
    { 361,                     372 + 9,0, 0 },
    { 0,                       0,    0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 1890 of file cg_sound.c.
panel_button_t speakerEditorNoiseEdit
Initial value:
=
{
    NULL,
    noiseEditBuffer,
    { 430,                           344,200, 12 },
    { MAX_QPATH,                     0,  0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    CG_SpeakerEditor_NoiseEdit_KeyDown,
    NULL,
    CG_SpeakerEditor_RenderEdit,
    CG_SpeakerEditor_NoiseEditFinish,
    0,
}
Definition at line 1846 of file cg_sound.c.
panel_button_t speakerEditorNoiseLabel
Initial value:
=
{
    NULL,
    "Noise:",
    { 361,                     344 + 9,0, 0 },
    { 0,                       0,     0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 1830 of file cg_sound.c.
panel_button_t speakerEditorOkButton
Initial value:
=
{
    NULL,
    "Ok",
    { 376,                        458,   70, 12 },
    { 0,                          0,     0,  0, 0, 0, 0, 0},
    &speakerEditorTxt,
    CG_SpeakerEditor_Ok_KeyDown,
    CG_SpeakerEditor_Ok_KeyUp,
    CG_SpeakerEditor_RenderButton,
    NULL,
    0,
}
Definition at line 2066 of file cg_sound.c.
panel_button_t speakerEditorRandomEdit
Initial value:
=
{
    NULL,
    randomEditBuffer,
    { 430,                            414,200, 12 },
    { 12,                             2,  0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    BG_PanelButton_EditClick,
    NULL,
    CG_SpeakerEditor_RenderEdit,
    CG_SpeakerEditor_RandomEditFinish,
    0,
}
Definition at line 1992 of file cg_sound.c.
panel_button_t speakerEditorRandomLabel
Initial value:
=
{
    NULL,
    "Random:",
    { 361,                     414 + 9,0, 0 },
    { 0,                       0,    0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 1976 of file cg_sound.c.
panel_button_t speakerEditorRangeEdit
Initial value:
=
{
    NULL,
    rangeEditBuffer,
    { 430,                           442,200, 12 },
    { 12,                            2,  0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    BG_PanelButton_EditClick,
    NULL,
    CG_SpeakerEditor_RenderEdit,
    CG_SpeakerEditor_RangeEditFinish,
    0,
}
Definition at line 2052 of file cg_sound.c.
panel_button_t speakerEditorRangeLabel
Initial value:
=
{
    NULL,
    "Range:",
    { 361,                     442 + 9,0, 0 },
    { 0,                       0,     0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 2036 of file cg_sound.c.
panel_button_t speakerEditorTargetnameEdit
Initial value:
=
{
    NULL,
    targetnameEditBuffer,
    { 430,                                358,200, 12 },
    { 32,                                 0,  0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    BG_PanelButton_EditClick,
    NULL,
    CG_SpeakerEditor_RenderEdit,
    CG_SpeakerEditor_TargetnameEditFinish,
    0,
}
Definition at line 1876 of file cg_sound.c.
panel_button_t speakerEditorTargetnameLabel
Initial value:
=
{
    NULL,
    "Targetname:",
    { 361,                     358 + 9,0, 0 },
    { 0,                       0,  0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 1860 of file cg_sound.c.
panel_button_text_t speakerEditorTxt
Initial value:
=
{
    0.2f,                    0.2f,
    { 1.0f,                  1.0f,1.0f,    0.5f },
    ITEM_TEXTSTYLE_SHADOWED, 0,
    &cgs.media.limboFont2,
}
Definition at line 1033 of file cg_sound.c.
panel_button_t speakerEditorVolumeEdit
Initial value:
=
{
    NULL,
    volumeEditBuffer,
    { 430,                            428,200, 12 },
    { 12,                             2,  0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    BG_PanelButton_EditClick,
    NULL,
    CG_SpeakerEditor_RenderEdit,
    CG_SpeakerEditor_VolumeEditFinish,
    0,
}
Definition at line 2022 of file cg_sound.c.
panel_button_t speakerEditorVolumeLabel
Initial value:
=
{
    NULL,
    "Volume:",
    { 361,                     428 + 9,0, 0 },
    { 0,                       0,    0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 2006 of file cg_sound.c.
panel_button_t speakerEditorWaitEdit
Initial value:
=
{
    NULL,
    waitEditBuffer,
    { 430,                          400,200, 12 },
    { 12,                           2,  0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    BG_PanelButton_EditClick,
    NULL,
    CG_SpeakerEditor_RenderEdit,
    CG_SpeakerEditor_WaitEditFinish,
    0,
}
Definition at line 1962 of file cg_sound.c.
panel_button_t speakerEditorWaitLabel
Initial value:
=
{
    NULL,
    "Wait:",
    { 361,                     400 + 9,0, 0 },
    { 0,                       0,      0, 0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    BG_PanelButtonsRender_Text,
    NULL,
    0,
}
Definition at line 1946 of file cg_sound.c.
panel_button_t speakerInfo
Initial value:
=
{
    NULL,
    NULL,
    { 344,              184,   272, 72 },
    { 0,                0,     0,   0, 0, 0, 0, 0},
    &speakerEditorTxt,
    NULL,
    NULL,
    CG_SpeakerInfo_Text,
    NULL,
    0,
}
Definition at line 1041 of file cg_sound.c.
panel_button_t* speakerInfoButtons[] static
Initial value:
=
{
    &speakerInfo,
    NULL
}
Definition at line 1055 of file cg_sound.c.
qhandle_t speakerShader = 0 static
Definition at line 570 of file cg_sound.c.
Referenced by CG_ActivateEditSoundMode(), and CG_RenderScriptSpeakers().
qhandle_t speakerShaderGrayScale = 0 static
Definition at line 571 of file cg_sound.c.
Referenced by CG_ActivateEditSoundMode(), and CG_RenderScriptSpeakers().
char targetnameEditBuffer[32]
Definition at line 1874 of file cg_sound.c.
Referenced by CG_ModifyEditSpeaker().
bg_speaker_t undoSpeaker static
Definition at line 573 of file cg_sound.c.
int undoSpeakerIndex static
Definition at line 574 of file cg_sound.c.
Referenced by CG_ActivateEditSoundMode(), CG_DeActivateEditSoundMode(), CG_ModifyEditSpeaker(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditorDraw(), and CG_UndoEditSpeaker().
char volumeEditBuffer[12]
Definition at line 2020 of file cg_sound.c.
Referenced by CG_ModifyEditSpeaker().
char waitEditBuffer[12]
Definition at line 1960 of file cg_sound.c.
Referenced by CG_ModifyEditSpeaker().