ET: Legacy: src/cgame/cg_local.h File Reference
cg_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/q_unicode.h"
#include "../renderercommon/tr_types.h"
#include "../game/bg_public.h"
#include "cg_public.h"
#include "../ui/ui_shared.h"
Data Structures
struct specLabel_s
struct cg_window_t
struct cg_string_t
struct cg_windowHandler_t
struct lerpFrame_t
struct playerEntity_t
struct tag_s
struct centity_s
struct markPoly_s
struct localEntity_s
struct score_t
struct clientInfo_s
struct soundSurfaceTable_s
struct partModel_s
struct weaponModel_s
struct weaponSounds_s
struct weaponInfo_s
struct viewDamage_t
struct soundScriptHandle_s
struct soundScriptSound_s
struct soundScript_s
struct mapEntityData_t
struct cg_t
struct cgMedia_t
all of the model, shader, and sound references that are loaded at gamestate time are stored in cgMedia_t Other media that can be tied to clients, weapons, or items are stored in the clientInfo_t, itemInfo_t, and weaponInfo_t
struct arenaInfo_t
struct cg_campaignInfo_t
struct cg_gamemodel_s
struct cg_corona_s
struct cg_weaponstats_s
struct gameStats_t
struct topshotStats_t
struct oidInfo_s
struct objectives_t
struct location_s
struct clientLocation_t
struct lagometer_t
struct sample_s
struct sampledStat_s
struct cgs_s
struct consoleCommand_t
struct rankicon_t
struct mapScissor_s
struct hudComponent_s
struct hudStructure_s
Macros
#define STATS_FADE_TIME 200
#define FADE_TIME 200
#define DAMAGE_DEFLECT_TIME 100
#define DAMAGE_RETURN_TIME 400
#define DAMAGE_TIME 500
#define LAND_DEFLECT_TIME 150
#define LAND_RETURN_TIME 300
#define STEP_TIME 200
#define DUCK_TIME 100
#define PAIN_TWITCH_TIME 200
#define ZOOM_TIME 150.0f
#define MUZZLE_FLASH_TIME 30
#define SINK_TIME 3000
time for fragments to sink into ground before going away
#define PRONE_TIME 500
#define MAX_STEP_CHANGE 32
#define MAX_VERTS_ON_POLY 10
#define MAX_MARK_POLYS 256
was 1024
#define STAT_MINUS 10
num frame for '-' stats digit
#define NOTIFY_WIDTH 80
#define NOTIFY_HEIGHT 5
#define TEAMCHAT_WIDTH 70
#define TEAMCHAT_HEIGHT 8
#define NUM_CROSSHAIRS 16
#define STYPE_STRETCH 0
#define STYPE_REPEAT 1
#define TJFL_FADEIN (1 << 0)
#define TJFL_CROSSOVER (1 << 1)
#define TJFL_NOCULL (1 << 2)
#define TJFL_FIXDISTORT (1 << 3)
#define TJFL_SPARKHEADFLARE (1 << 4)
#define TJFL_NOPOLYMERGE (1 << 5)
#define AA_DEMORECORD 0x01
#define AA_SCREENSHOT 0x02
#define AA_STATSDUMP 0x04
#define CURSOR_OFFSETX 13
#define CURSOR_OFFSETY 12
#define DEMO_THIRDPERSONUPDATE 0
#define DEMO_RANGEDELTA 6
#define DEMO_ANGLEDELTA 4
#define MAX_WINDOW_COUNT 10
#define MAX_WINDOW_LINES 64
#define MAX_STRINGS 80
#define MAX_STRING_POOL_LENGTH 128
#define WINDOW_FONTWIDTH 8
For non-true-type: width to scale from.
#define WINDOW_FONTHEIGHT 8
For non-true-type: height to scale from.
#define WID_NONE 0x00
General window.
#define WID_STATS 0x01
Stats (reusable due to scroll effect)
#define WID_TOPSHOTS 0x02
Top/Bottom-shots.
#define WID_MOTD 0x04
MOTD.
#define WFX_TEXTSIZING 0x01
Size the window based on text/font setting.
#define WFX_FLASH 0x02
Alternate between bg and b2 every half second.
#define WFX_TRUETYPE 0x04
Use truetype fonts for text.
#define WFX_MULTIVIEW 0x08
Multiview window.
#define WFX_FADEIN 0x10
Fade the window in (and back out when closing)
#define WFX_SCROLLUP 0x20
Scroll window up from the bottom (and back down when closing)
#define WFX_SCROLLDOWN 0x40
Scroll window down from the top (and back up when closing)
#define WFX_SCROLLLEFT 0x80
Scroll window in from the left (and back right when closing)
#define WFX_SCROLLRIGHT 0x100
Scroll window in from the right (and back left when closing)
#define WSTATE_COMPLETE 0x00
Window is up with startup effects complete.
#define WSTATE_START 0x01
Window is "initializing" w/effects.
#define WSTATE_SHUTDOWN 0x02
Window is shutting down with effects.
#define WSTATE_OFF 0x04
Window is completely shutdown.
#define ISVALIDCLIENTNUM(clientNum) ((clientNum) >= 0 && (clientNum) < MAX_CLIENTS)
#define MAX_WEAPON_SOUNDS 5
#define MAX_VIEWDAMAGE 8
#define MAX_PREDICTED_EVENTS 16
#define MAX_SPAWN_VARS 64
#define MAX_SPAWN_VARS_CHARS 2048
#define MAX_SPAWNPOINTS 32
#define MAX_SPAWNDESC 128
#define MAX_BUFFERED_SOUNDSCRIPTS 16
#define MAX_SOUNDSCRIPT_SOUNDS 16
#define MAX_FLOATING_STRINGS 128
#define MAX_WEAP_BANKS_MP 10
#define MAX_WEAPS_IN_BANK_MP 18
#define MAX_WEAP_BANK_SWITCH_ORDER 4
#define MAX_BACKUP_STATES (CMD_BACKUP + 2)
#define MAX_LOCKER_DEBRIS 5
#define MAX_COMMAND_INFO MAX_CLIENTS
#define MAX_STATIC_GAMEMODELS 1024
some maps have > 512 game models (f.e. 'raiders' with 555)
#define MAX_GAMECORONAS 1024
#define MAX_C_LOCATIONS 1024
Locations.
#define NUM_ENDGAME_AWARDS 20
total number of endgame awards
#define NUMSHOW_ENDGAME_AWARDS 14
number of awards to display that will fit on screen
#define SECONDARY_SLOT 0
#define PRIMARY_SLOT 1
#define PERIOD_SAMPLES 5000
#define LAG_SAMPLES 128
#define MAX_LAGOMETER_PING 900
#define MAX_LAGOMETER_RANGE 300
#define LOCALTIME_ON 0x01
#define LOCALTIME_SECOND 0x02
#define LOCALTIME_12HOUR 0x04
#define CROSSHAIR_CLASS 0x01
#define CROSSHAIR_RANK 0x02
#define PS_FX_NONE 0
#define PS_FX_COMMON 1
#define PS_FX_WATER 2
#define PS_FX_FLESH 3
#define CC_FILTER_AXIS (1 << 0)
#define CC_FILTER_ALLIES (1 << 1)
#define CC_FILTER_SPAWNS (1 << 2)
#define CC_FILTER_CMDPOST (1 << 3)
#define CC_FILTER_HACABINETS (1 << 4)
#define CC_FILTER_CONSTRUCTIONS (1 << 5)
#define CC_FILTER_DESTRUCTIONS (1 << 6)
#define CC_FILTER_LANDMINES (1 << 7)
#define CC_FILTER_OBJECTIVES (1 << 8)
#define UI_CAMPAIGN_BRIEFING 0
#define UI_COMMAND_MAP 1
#define UI_SQUAD_SELECT 2
#define Pri(x) CG_Printf("[cgnotify]%s", CG_LocalizeServerCommand(x))
#define CPri(x) CG_CenterPrint(CG_LocalizeServerCommand(x), 400, cg_fontScaleCP.value)
#define LIMBO_3D_X 287
#define LIMBO_3D_Y 382
#define LIMBO_3D_W 128
#define LIMBO_3D_H 96
#define CC_2D_X 64
#define CC_2D_Y 23
#define CC_2D_W 352
#define CC_2D_H 352
#define SCREEN_WIDTH_SAFE Ccg_WideX(SCREEN_WIDTH)
#define SCREEN_HEIGHT_SAFE SCREEN_HEIGHT
#define IS_MOUNTED_TANK_BROWNING(entNum) (cg_entities[cg_entities[cg_entities[entNum].tagParent].tankparent].currentState.density & 8)
Typedefs
typedef struct specLabel_s specLabel_t
typedef struct tag_s tag_t
typedef struct centity_s centity_t
centity_t have a direct corespondence with gentity_t in the game, but only the entityState_t is directly communicated to the cgame
typedef struct markPoly_s markPoly_t
typedef struct localEntity_s localEntity_t
Local entities are created as a result of events or predicted actions, and live independantly from all server transmitted entities.
typedef struct clientInfo_s clientInfo_t
Each client has an associated clientInfo_t that contains media references necessary to present the client model and other color coded effects this is regenerated each time a client's configstring changes, usually as a result of a userinfo (name, model, etc) change.
typedef enum soundSurface_s soundSurface_t
typedef struct soundSurfaceTable_s soundSurfaceTable_t
Sound Surface Table.
typedef struct partModel_s partModel_t
typedef struct weaponModel_s weaponModel_t
typedef struct weaponSounds_s weaponSounds_t
typedef struct weaponInfo_s weaponInfo_t
each WP_* weapon enum has an associated weaponInfo_t that contains media references necessary to present the weapon and its effects
typedef struct soundScriptHandle_s soundScriptHandle_t
typedef struct soundScriptSound_s soundScriptSound_t
typedef struct soundScript_s soundScript_t
typedef struct cg_gamemodel_s cg_gamemodel_t
typedef struct cg_corona_s cg_corona_t
typedef struct cg_weaponstats_s cg_weaponstats_t
typedef struct oidInfo_s oidInfo_t
typedef struct location_s location_t
typedef struct sample_s sample_t
typedef struct sampledStat_s sampledStat_t
typedef struct cgs_s cgs_t
The client game static (cgs) structure should hold everything loaded or calculated from the gamestate. It will NOT be cleared when a tournement restart is done, allowing all clients to begin playing instantly.
typedef struct mapScissor_s mapScissor_t
A scissored map always has the player in the center.
typedef struct hudComponent_s hudComponent_t
typedef struct hudStructure_s hudStucture_t
Enumerations
enum leType_t {
LE_MARK = 0, LE_EXPLOSION, LE_SPRITE_EXPLOSION, LE_FRAGMENT,
LE_MOVE_SCALE_FADE, LE_FALL_SCALE_FADE, LE_FADE_RGB, LE_CONST_RGB,
LE_SCALE_FADE, LE_SPARK, LE_DEBRIS, LE_BLOOD,
LE_FUSE_SPARK, LE_MOVING_TRACER, LE_EMITTER
}
enum leFlag_t {
LEF_PUFF_DONT_SCALE = 0x0001, LEF_TUMBLE = 0x0002, LEF_NOFADEALPHA = 0x0004, LEF_SMOKING = 0x0008,
LEF_TUMBLE_SLOW = 0x0010
}
enum leMarkType_t { LEMT_NONE = 0, LEMT_BLOOD }
Fragment local entities can leave marks on walls.
enum leBounceSoundType_t {
LEBS_NONE = 0, LEBS_BLOOD, LEBS_ROCK, LEBS_WOOD,
LEBS_BRASS, LEBS_METAL, LEBS_BONE, LEBS_SG_BRASS
}
Fragment local entities can make sounds on impacts.
enum barrelType_t {
W_PART_1 = 0, W_PART_2, W_PART_3, W_PART_4,
W_PART_5, W_PART_6, W_PART_7, W_MAX_PARTS
}
enum modelViewType_t { W_TP_MODEL = 0, W_FP_MODEL, W_PU_MODEL, W_NUM_TYPES }
enum soundSurface_s {
W_SND_SURF_DEFAULT = 0, W_SND_SURF_FAR, W_SND_SURF_METAL, W_SND_SURF_WOOD,
W_SND_SURF_GRASS, W_SND_SURF_GRAVEL, W_SND_SURF_GLASS, W_SND_SURF_SNOW,
W_SND_SURF_ROOF, W_SND_SURF_CARPET, W_SND_SURF_WATER, W_SND_SURF_FLESH,
W_MAX_SND_SURF
}
enum showView_t { SHOW_OFF = 0, SHOW_SHUTDOWN, SHOW_ON }
enum {
POPUP_FILTER_CONNECT = BIT(0), POPUP_FILTER_TEAMJOIN = BIT(1), POPUP_FILTER_MISSION = BIT(2), POPUP_FILTER_PICKUP = BIT(3),
POPUP_FILTER_DEATH = BIT(4)
}
enum { POPUP_BIG_FILTER_SKILL = BIT(0), POPUP_BIG_FILTER_RANK = BIT(1) }
enum {
LOC_FTEAM = BIT(0), LOC_VCHAT = BIT(1), LOC_TCHAT = BIT(1), LOC_LANDMINES = BIT(2),
LOC_KEEPUNKNOWN = BIT(3), LOC_SHOWCOORDS = BIT(4), LOC_SHOWDISTANCE = BIT(5), LOC_DEBUG = BIT(9)
}
enum {
BAR_LEFT = BIT(0), BAR_CENTER = BIT(1), BAR_VERT = BIT(2), BAR_NOHUDALPHA = BIT(3),
BAR_BG = BIT(4), BAR_BGSPACING_X0Y5 = BIT(5), BAR_BGSPACING_X0Y0 = BIT(6), BAR_LERP_COLOR = BIT(7),
BAR_BORDER = BIT(8), BAR_BORDER_SMALL = BIT(9)
}
enum hitsooundFlags { HITSOUNDS_ON = BIT(0), HITSOUNDS_NOBODYSHOT = BIT(1), HITSOUNDS_NOHEADSHOT = BIT(2), HITSOUNDS_NOTEAMSHOT = BIT(3) }
Functions
void CG_ParseMapEntityInfo (int axis_number, int allied_number)
CG_ParseMapEntityInfo.
void CG_EffectParse (const char *effectstr)
Parse effect.
void CG_AddAtmosphericEffects (void)
Add atmospheric effects.
qboolean CG_RegisterCharacter (const char *characterFile, bg_character_t *character)
Register character.
bg_character_t * CG_CharacterForClientinfo (clientInfo_t *ci, centity_t *cent)
Character for clientinfo.
bg_character_t * CG_CharacterForPlayerstate (playerState_t *ps)
Character for playerstate.
void CG_RegisterPlayerClasses (void)
Register player classes.
const char * CG_ConfigString (int index)
CG_ConfigString.
int CG_ConfigStringCopy (int index, char *buff, size_t buffsize)
CG_ConfigStringCopy.
const char * CG_Argv (int arg)
CG_Argv.
float CG_Cvar_Get (const char *cvar)
CG_Cvar_Get.
char * CG_generateFilename (void)
Generate standard naming for screenshots/demos.
int CG_findClientNum (const char *s)
CG_findClientNum.
void CG_printConsoleString (const char *str)
CG_printConsoleString.
void CG_LoadObjectiveData (void)
CG_LoadObjectiveData.
void QDECL CG_Printf (const char *msg,...) __attribute__((format(printf
void QDECL void QDECL CG_DPrintf (const char *msg,...) __attribute__((format(printf
void QDECL void QDECL void QDECL CG_Error (const char *msg,...) __attribute__((noreturn
void QDECL void QDECL void QDECL format (printf, 1, 2)))
void CG_StartMusic (void)
CG_StartMusic.
void CG_QueueMusic (void)
CG_QueueMusic.
void CG_UpdateCvars (void)
CG_UpdateCvars.
qboolean CG_execFile (const char *filename)
Try to exec a cfg file if it is found.
int CG_CrosshairPlayer (void)
CG_CrosshairPlayer.
int CG_LastAttacker (void)
CG_LastAttacker.
void CG_KeyEvent (int key, qboolean down)
void CG_MouseEvent (int x, int y)
CG_MouseEvent.
void CG_EventHandling (int type, qboolean fForced)
CG_EventHandling.
qboolean CG_GetTag (int clientNum, const char *tagname, orientation_t *orientation)
CG_GetTag.
qboolean CG_GetWeaponTag (int clientNum, const char *tagname, orientation_t *orientation)
CG_GetWeaponTag.
sfxHandle_t CG_GetGameSound (int index)
CG_GetGameSound.
void QDECL CG_WriteToLog (const char *fmt,...) _attribute((format(printf
void QDECL int CG_cleanName (const char *pszIn, char *pszOut, int dwMaxLength, qboolean fCRLF)
Strip colors and control codes, copying up to dwMaxLength-1 "good" chars and nul-terminating.
void CG_TestModel_f (void)
Creates an entity in front of the current position, which can then be moved around.
void CG_TestGun_f (void)
Replaces the current view weapon with the given model.
void CG_TestModelNextFrame_f (void)
CG_TestModelNextFrame_f.
void CG_TestModelPrevFrame_f (void)
CG_TestModelPrevFrame_f.
void CG_TestModelNextSkin_f (void)
CG_TestModelNextSkin_f.
void CG_TestModelPrevSkin_f (void)
CG_TestModelPrevSkin_f.
void CG_ZoomIn_f (void)
CG_ZoomIn_f.
void CG_ZoomOut_f (void)
CG_ZoomOut_f.
void CG_SetupFrustum (void)
qboolean CG_CullPoint (vec3_t pt)
CG_CullPoint.
qboolean CG_CullPointAndRadius (const vec3_t pt, vec_t radius)
CG_CullPointAndRadius.
void CG_DrawActiveFrame (int serverTime, qboolean demoPlayback)
Generates and draws a game scene and status information at the given time.
void CG_DrawSkyBoxPortal (qboolean fLocalView)
CG_DrawSkyBoxPortal.
void CG_Letterbox (float xsize, float ysize, qboolean center)
Sets the coordinates of the rendered window.
qboolean Ccg_Is43Screen (void)
Ccg_Is43Screen.
float Ccg_WideX (float x)
Ccg_WideX.
float Ccg_WideXoffset (void)
Ccg_WideXoffset.
void CG_AdjustFrom640 (float *x, float *y, float *w, float *h)
Adjusted for resolution and screen aspect ratio.
void CG_FillRect (float x, float y, float width, float height, const float *color)
CG_FillRect.
void CG_HorizontalPercentBar (float x, float y, float width, float height, float percent)
Generic routine for pretty much all status indicators that show a fractional value to the player by virtue of how full a drawn box is.
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
CG_DrawPic.
void CG_DrawPicST (float x, float y, float width, float height, float s0, float t0, float s1, float t1, qhandle_t hShader)
Allows passing of st co-ords.
void CG_DrawRotatedPic (float x, float y, float width, float height, qhandle_t hShader, float angle)
CG_DrawRotatedPic.
void CG_FilledBar (float x, float y, float w, float h, float *startColor, float *endColor, const float *bgColor, float frac, int flags)
CG_FilledBar.
void CG_DrawStretchPic (float x, float y, float width, float height, qhandle_t hShader)
float * CG_FadeColor (int startMsec, int totalMsec)
CG_FadeColor.
float * CG_TeamColor (int team)
CG_TeamColor.
void CG_TileClear (void)
CG_TileClear.
void CG_ColorForHealth (vec4_t hcolor)
CG_ColorForHealth.
void CG_GetColorForHealth (int health, vec4_t hcolor)
CG_GetColorForHealth.
qboolean CG_WorldCoordToScreenCoordFloat (vec3_t point, float *x, float *y)
Float a sprite over the player's head added height parameter.
void CG_AddOnScreenText (const char *text, vec3_t origin)
CG_AddOnScreenText.
void CG_DrawRect (float x, float y, float width, float height, float size, const float *color)
CG_DrawRect.
void CG_DrawRect_FixedBorder (float x, float y, float width, float height, int border, const float *color)
CG_DrawRect_FixedBorder.
void CG_DrawSides (float x, float y, float w, float h, float size)
CG_DrawSides.
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
CG_DrawTopBottom.
void CG_DrawTopBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawTopBottom_NoScale.
void CG_DrawBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawBottom_NoScale.
const char * CG_TranslateString (const char *string)
CG_TranslateString.
void CG_InitStatsDebug (void)
CG_InitStatsDebug.
void CG_StatsDebugAddText (const char *text)
CG_StatsDebugAddText.
void CG_AddLagometerFrameInfo (void)
Adds the current interpolate / extrapolate bar for this frame.
void CG_AddLagometerSnapshotInfo (snapshot_t *snap)
Log the ping time, server framerate and number of dropped snapshots before it each time a snapshot is received.
void CG_CenterPrint (const char *str, int y, float fontScale)
Called for important messages that should stay in the center of the screen for a few moments.
void CG_PriorityCenterPrint (const char *str, int y, float fontScale, int priority)
Called for important messages that should stay in the center of the screen for a few moments.
void CG_ObjectivePrint (const char *str, float fontScale)
CG_ObjectivePrint.
void CG_DrawActive (void)
Perform all drawing needed to completely fill the screen.
void CG_CheckForCursorHints (void)
CG_CheckForCursorHints.
void CG_DrawTeamBackground (int x, int y, int w, int h, float alpha, int team)
CG_DrawTeamBackground.
void CG_Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
CG_Text_Paint_Ext.
void CG_Text_Paint_Centred_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
CG_Text_Paint_Centred_Ext.
void CG_Text_Paint (float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
CG_Text_Paint.
void CG_Text_PaintWithCursor_Ext (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style, fontHelper_t *font)
CG_Text_PaintWithCursor_Ext.
void CG_Text_PaintWithCursor (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style)
CG_Text_PaintWithCursor.
void CG_Text_SetActiveFont (int font)
CG_Text_SetActiveFont.
int CG_Text_Width_Ext (const char *text, float scale, int limit, fontHelper_t *font)
CG_Text_Width_Ext.
int CG_Text_Width (const char *text, float scale, int limit)
CG_Text_Width.
int CG_Text_Height_Ext (const char *text, float scale, int limit, fontHelper_t *font)
CG_Text_Height_Ext.
int CG_Text_Height (const char *text, float scale, int limit)
CG_Text_Height.
float CG_GetValue (int ownerDraw, int type)
CG_GetValue.
qboolean CG_OwnerDrawVisible (int flags)
CG_OwnerDrawVisible.
void CG_RunMenuScript (char **args)
CG_RunMenuScript.
void CG_GetTeamColor (vec4_t *color)
CG_GetTeamColor.
void CG_ReadHudScripts (void)
CG_ReadHudScripts.
void CG_Hud_Setup (void)
CG_Hud_Setup.
void CG_DrawUpperRight (void)
CG_DrawUpperRight.
void CG_SetHud (void)
CG_SetHud.
void CG_DrawActiveHud (void)
CG_DrawActiveHud.
void CG_DrawGlobalHud (void)
CG_DrawGlobalHud.
void CG_Text_PaintChar_Ext (float x, float y, float w, float h, float scalex, float scaley, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar_Ext.
void CG_Text_PaintChar (float x, float y, float width, float height, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar.
void CG_DrawCursorhint (rectDef_t *rect)
CG_DrawCursorhint.
void CG_DrawWeapStability (rectDef_t *rect)
Draw a bar showing current stability level (0-255), max at current weapon/ability, and 'perfect' reference mark probably only drawn for scoped weapons.
void CG_DrawWeapHeat (rectDef_t *rect, int align)
CG_DrawWeapHeat.
void CG_DrawPlayerWeaponIcon (rectDef_t *rect, qboolean drawHighlighted, int align, vec4_t *refcolor)
CG_DrawPlayerWeaponIcon.
int CG_CalculateReinfTime (qboolean menu)
CG_CalculateReinfTime.
float CG_CalculateReinfTime_Float (qboolean menu)
CG_CalculateReinfTime_Float.
int CG_CalculateShoutcasterReinfTime (team_t team)
CG_CalculateShoutcasterReinfTime.
void CG_Fade (int r, int g, int b, int a, int time, int duration)
CG_Fade.
qboolean CG_EntOnFire (centity_t *cent)
CG_EntOnFire.
void CG_Player (centity_t *cent)
CG_Player.
void CG_ResetPlayerEntity (centity_t *cent)
A player just came into view or teleported, so reset all animation info.
void CG_AddRefEntityWithPowerups (refEntity_t *ent, int powerups, int team, entityState_t *es, const vec3_t fireRiseDir)
Adds a piece with modifications or duplications for powerups Also called by CG_Missile for quad rockets, but nobody can tell...
void CG_NewClientInfo (int clientNum)
CG_NewClientInfo.
sfxHandle_t CG_CustomSound (int clientNum, const char *soundName)
CG_CustomSound.
void CG_ParseTeamXPs (int n)
CG_ParseTeamXPs.
int CG_NewParticleArea (int num)
CG_NewParticleArea.
void CG_BuildSolidList (void)
When a new cg.snap has been set, this function builds a sublist of the entities that are actually solid, to make for more efficient collision detection.
int CG_PointContents (const vec3_t point, int passEntityNum)
CG_PointContents.
void CG_Trace (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_Trace.
void CG_PredictPlayerState (void)
Generates cg.predictedPlayerState for the current cg.time cg.predictedPlayerState is guaranteed to be valid after exiting.
void CG_RunBindingBuf (int key, qboolean down, char *buf)
void CG_RunBinding (int key, qboolean down)
void CG_EDV_WeaponCam (centity_t *cent, refEntity_t *ent)
void CG_EDV_RunInput (void)
void CG_CheckEvents (centity_t *cent)
CG_CheckEvents.
void CG_EntityEvent (centity_t *cent, vec3_t position)
An entity has an event value also called by CG_CheckPlayerstateEvents.
void CG_PainEvent (centity_t *cent, int health, qboolean crouching)
Also called by playerstate transition.
void CG_PrecacheFXSounds (void)
CG_PrecacheFXSounds.
void CG_SetEntitySoundPosition (centity_t *cent)
Also called by event processing code.
void CG_AddPacketEntities (void)
CG_AddPacketEntities.
void CG_Beam (centity_t *cent)
Also called as an event.
void CG_AdjustPositionForMover (const vec3_t in, int moverNum, int fromTime, int toTime, vec3_t out, vec3_t outDeltaAngles)
Also called by client movement prediction code.
void CG_AddCEntity (centity_t *cent)
CG_AddCEntity.
qboolean CG_AddCEntity_Filter (centity_t *cent)
CG_AddCEntity_Filter.
qboolean CG_AddLinkedEntity (centity_t *cent, qboolean ignoreframe, int atTime)
CG_AddLinkedEntity.
void CG_PositionEntityOnTag (refEntity_t *entity, const refEntity_t *parent, const char *tagName, int startIndex, vec3_t *offset)
Modifies the entities position and axis by the given tag location.
void CG_PositionRotatedEntityOnTag (refEntity_t *entity, const refEntity_t *parent, const char *tagName)
Modifies the entities position and axis by the given tag location.
void CG_LastWeaponUsed_f (void)
CG_LastWeaponUsed_f.
void CG_NextWeaponInBank_f (void)
CG_NextWeaponInBank_f.
void CG_PrevWeaponInBank_f (void)
CG_PrevWeaponInBank_f.
void CG_AltWeapon_f (void)
For example, switching between WP_MAUSER and WP_SNIPERRIFLE.
void CG_NextWeapon_f (void)
CG_NextWeapon_f.
void CG_PrevWeapon_f (void)
CG_PrevWeapon_f.
void CG_Weapon_f (void)
CG_Weapon_f.
void CG_WeaponBank_f (void)
Weapon keys are not generally bound directly('bind 1 weapon 1'), rather the key is bound to a given bank ('bind 1 weaponbank 1')
qboolean CG_WeaponSelectable (int weapon)
Check weapon is selectable.
void CG_FinishWeaponChange (int lastweap, int newweap)
CG_FinishWeaponChange.
void CG_SetSniperZoom (int weapon)
void CG_RegisterWeapon (int weaponNum, qboolean force)
CG_RegisterWeapon.
void CG_RegisterItemVisuals (int itemNum)
Registers models and icons for items of bg_itemlist (except weapons which are registered from *.weap file data)
void CG_FireWeapon (centity_t *cent)
Caused by an EV_FIRE_WEAPON event.
void CG_MissileHitWall (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, int entHit)
Caused by an EV_MISSILE_MISS event, or directly by local bullet tracing.
void CG_MissileHitWallSmall (vec3_t origin, vec3_t dir)
CG_MissileHitWallSmall.
void CG_DrawTracer (const vec3_t start, const vec3_t finish)
CG_DrawTracer.
void CG_MG42EFX (centity_t *cent)
CG_MG42EFX.
void CG_MortarEFX (centity_t *cent)
Right now mostly copied directly from Raf's MG42 FX, but with the optional addtion of smoke.
void CG_MissileHitPlayer (int entityNum, int weapon, vec3_t origin, vec3_t dir, int fleshEntityNum)
CG_MissileHitPlayer.
qboolean CG_CalcMuzzlePoint (int entityNum, vec3_t muzzle)
CG_CalcMuzzlePoint.
void CG_Bullet (int weapon, vec3_t end, int sourceEntityNum, qboolean flesh, int fleshEntityNum, int otherEntNum2, float waterfraction, int seed)
Renders bullet effects.
void CG_RailTrail (vec3_t color, vec3_t start, vec3_t end, int type, int index)
CG_RailTrail.
void CG_RailTrail2 (vec3_t color, vec3_t start, vec3_t end, int index, int sideNum)
Re-inserted this as a debug mechanism for bullets.
void CG_AddViewWeapon (playerState_t *ps)
Add the weapon, and flash for the player's view.
void CG_AddPlayerWeapon (refEntity_t *parent, playerState_t *ps, centity_t *cent)
Used for both the view weapon (ps is valid) and the world modelother character models (ps is NULL) The main player will have this called for BOTH cases, so effects like light and sound should only be done on the world model case.
void CG_OutOfAmmoChange (qboolean allowforceswitch)
The current weapon has just run out of ammo, switch to another one.
soundSurface_t CG_GetSoundSurfaceIndex (int surfFlags)
CG_GetSoundSurfaceIndex.
sfxHandle_t CG_GetRandomSoundSurface (weaponSounds_t *weaponSounds, soundSurface_t surf, qboolean forceDefault)
CG_GetRandomSoundSurface.
void CG_AddDebris (vec3_t origin, vec3_t dir, int speed, int duration, int count, trace_t *trace)
CG_AddDebris.
void CG_InitMarkPolys (void)
This is called at startup and for tournement restarts.
void CG_AddMarks (void)
CG_AddMarks.
void CG_ImpactMark (qhandle_t markShader, vec3_t origin, vec4_t projection, float radius, float orientation, float r, float g, float b, float a, int lifeTime)
CG_ImpactMark.
void CG_ClearParticles (void)
CG_ClearParticles.
void CG_AddParticles (void)
CG_AddParticles.
void CG_ParticleSnow (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
CG_ParticleSnow.
void CG_ParticleSmoke (qhandle_t pshader, centity_t *cent)
CG_ParticleSmoke.
void CG_ParticleSnowFlurry (qhandle_t pshader, centity_t *cent)
CG_ParticleSnowFlurry.
void CG_ParticleBulletDebris (vec3_t org, vec3_t vel, int duration)
CG_ParticleBulletDebris.
void CG_ParticleDirtBulletDebris_Core (vec3_t org, vec3_t vel, int duration, float width, float height, float alpha, qhandle_t shader)
The core of the dirt explosion.
void CG_ParticleSparks (vec3_t org, vec3_t vel, int duration, float x, float y, float speed)
CG_ParticleSparks.
void CG_ParticleDust (centity_t *cent, vec3_t origin, vec3_t dir)
CG_ParticleDust.
void CG_ParticleExplosion (const char *animStr, vec3_t origin, vec3_t vel, int duration, int sizeStart, int sizeEnd, qboolean dlight)
CG_ParticleExplosion.
void CG_ParticleImpactSmokePuff (qhandle_t pshader, vec3_t origin)
CG_ParticleImpactSmokePuff.
void CG_ParticleImpactSmokePuffExtended (qhandle_t pshader, vec3_t origin, int lifetime, int vel, int acc, int maxroll, float alpha, float size)
CG_ParticleImpactSmokePuffExtended.
void CG_GetBleedOrigin (vec3_t head_origin, vec3_t body_origin, int fleshEntityNum)
CG_GetBleedOrigin.
void CG_Particle_OilParticle (qhandle_t pshader, vec3_t origin, vec3_t dir, int ptime, int snum)
CG_Particle_OilParticle.
void CG_Particle_OilSlick (qhandle_t pshader, centity_t *cent)
CG_Particle_OilSlick.
void CG_OilSlickRemove (centity_t *cent)
CG_OilSlickRemove.
void CG_ParticleBloodCloud (centity_t *cent, vec3_t origin, vec3_t dir)
CG_ParticleBloodCloud.
int CG_AddTrailJunc (int headJuncIndex, void *usedby, qhandle_t shader, int spawnTime, int sType, vec3_t pos, int trailLife, float alphaStart, float alphaEnd, float startWidth, float endWidth, int flags, vec3_t colorStart, vec3_t colorEnd, float sRatio, float animSpeed)
Used for generic trails.
int CG_AddSparkJunc (int headJuncIndex, void *usedby, qhandle_t shader, vec3_t pos, int trailLife, float alphaStart, float alphaEnd, float startWidth, float endWidth)
CG_AddSparkJunc.
int CG_AddSmokeJunc (int headJuncIndex, void *usedby, qhandle_t shader, vec3_t pos, int trailLife, float alpha, float startWidth, float endWidth)
CG_AddSmokeJunc.
void CG_AddTrails (void)
CG_AddTrails.
void CG_ClearTrails (void)
CG_ClearTrails.
int CG_SoundScriptPrecache (const char *name)
CG_SoundScriptPrecache.
int CG_SoundPlaySoundScript (const char *name, vec3_t org, int entnum, qboolean buffer)
CG_SoundPlaySoundScript.
void CG_UpdateBufferedSoundScripts (void)
CG_UpdateBufferedSoundScripts.
void CG_SoundPlayIndexedScript (int index, vec3_t org, int entnum)
CG_SoundPlayIndexedScript.
void CG_SoundInit (void)
CG_SoundInit.
void CG_SetViewanglesForSpeakerEditor (void)
CG_SetViewanglesForSpeakerEditor.
void CG_SpeakerEditorDraw (void)
CG_SpeakerEditorDraw.
void CG_SpeakerEditor_KeyHandling (int key, qboolean down)
CG_SpeakerEditor_KeyHandling.
void CG_Debriefing_KeyEvent (int key, qboolean down)
CG_Debriefing_KeyEvent.
void CG_SpeakerEditorMouseMove_Handling (int x, int y)
CG_SpeakerEditorMouseMove_Handling.
void CG_ActivateEditSoundMode (void)
CG_ActivateEditSoundMode.
void CG_DeActivateEditSoundMode (void)
CG_DeActivateEditSoundMode.
void CG_ModifyEditSpeaker (void)
CG_ModifyEditSpeaker.
void CG_UndoEditSpeaker (void)
CG_UndoEditSpeaker.
void CG_ToggleActiveOnScriptSpeaker (int index)
CG_ToggleActiveOnScriptSpeaker.
void CG_UnsetActiveOnScriptSpeaker (int index)
CG_UnsetActiveOnScriptSpeaker.
void CG_SetActiveOnScriptSpeaker (int index)
CG_SetActiveOnScriptSpeaker.
void CG_AddScriptSpeakers (void)
CG_AddScriptSpeakers.
void CG_FireFlameChunks (centity_t *cent, vec3_t origin, vec3_t angles, float speedScale, qboolean firing)
The given entity is firing a flamethrower.
void CG_InitFlameChunks (void)
CG_InitFlameChunks.
void CG_AddFlameChunks (void)
CG_AddFlameChunks.
void CG_UpdateFlamethrowerSounds (void)
CG_UpdateFlamethrowerSounds.
void CG_InitLocalEntities (void)
This is called at startup and for tournement restarts.
localEntity_t * CG_AllocLocalEntity (void)
CG_AllocLocalEntity.
localEntity_t * CG_FindLocalEntity (int index, int sideNum)
CG_FindLocalEntity.
void CG_AddLocalEntities (void)
CG_AddLocalEntities.
char * CG_GetLocationMsg (int clientNum, vec3_t origin)
CG_GetLocationMsg.
char * CG_BuildLocationString (int clientNum, vec3_t origin, int flag)
CG_BuildLocationString.
void CG_LoadLocations (void)
Report a location for the player. Uses placed nearby target_location entities.
int CG_GetOriginForTag (centity_t *cent, refEntity_t *parent, const char *tagName, int startIndex, vec3_t org, vec3_t axis[3])
Places the position of the tag into "org".
localEntity_t * CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
Adds a smoke puff or blood trail localEntity.
void CG_BubbleTrail (vec3_t start, vec3_t end, float size, float spacing)
Bullets shot underwater.
void CG_GibPlayer (centity_t *cent, vec3_t playerOrigin, vec3_t gdir)
Generated a bunch of gibs launching out from the bodies location.
void CG_LoseHat (centity_t *cent, vec3_t dir)
CG_LoseHat.
void CG_Bleed (vec3_t origin, int entityNum)
This is the spurt of blood when a character gets hit.
localEntity_t * CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
CG_MakeExplosion.
void CG_SparklerSparks (vec3_t origin, int count)
CG_SparklerSparks.
void CG_ClearFlameChunks (void)
CG_ClearFlameChunks.
void CG_RumbleEfx (float pitch, float yaw)
CG_RumbleEfx.
void InitSmokeSprites (void)
InitSmokeSprites.
void CG_RenderSmokeGrenadeSmoke (centity_t *cent, const weaponInfo_t *weapon)
CG_RenderSmokeGrenadeSmoke.
void CG_AddSmokeSprites (void)
CG_AddSmokeSprites.
void CG_ProcessSnapshots (void)
CG_ProcessSnapshots.
qboolean CG_SpawnString (const char *key, const char *defaultString, char **out)
CG_SpawnString.
qboolean CG_SpawnFloat (const char *key, const char *defaultString, float *out)
CG_SpawnFloat.
qboolean CG_SpawnInt (const char *key, const char *defaultString, int *out)
CG_SpawnInt.
qboolean CG_SpawnVector (const char *key, const char *defaultString, float *out)
CG_SpawnVector.
void CG_ParseEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
void CG_LoadingString (const char *s)
CG_LoadingString.
void CG_DrawInformation (qboolean forcerefresh)
Draw all the status / pacifier stuff during level loading.
void CG_DemoClick (int key, qboolean down)
Demo playback key catcher support.
void CG_ShowHelp_Off (int *status)
CG_ShowHelp_Off.
void CG_ShowHelp_On (int *status)
CG_ShowHelp_On.
qboolean CG_DrawScoreboard (void)
Draw the normal in-game scoreboard.
int SkillNumForClass (int classNum)
SkillNumForClass.
void CG_TransformToCommandMapCoord (float *coord_x, float *coord_y)
CG_TransformToCommandMapCoord.
void CG_DrawExpandedAutoMap (void)
CG_DrawExpandedAutoMap.
void CG_DrawAutoMap (float x, float y, float w, float h)
CG_DrawAutoMap.
qboolean CG_DrawMissionBriefing (void)
void CG_MissionBriefingClick (int key)
qboolean CG_FindArenaInfo (const char *filename, const char *mapname, arenaInfo_t *info)
CG_FindArenaInfo.
void CG_LoadRankIcons (void)
CG_LoadRankIcons.
qboolean CG_DrawStatsRanksMedals (void)
void CG_StatsRanksMedalsClick (int key)
void CG_ParseFireteams (void)
Parses fireteam servercommand.
void CG_ParseOIDInfos (void)
CG_ParseOIDInfos.
qboolean CG_ConsoleCommand (void)
The string has been tokenized and can be retrieved with Cmd_Argc() / Cmd_Argv()
void CG_InitConsoleCommands (void)
Let the client system know about all of our commands so it can perform tab completion.
void CG_ScoresDown_f (void)
CG_ScoresDown_f.
void CG_ScoresUp_f (void)
CG_ScoresUp_f.
void CG_autoRecord_f (void)
Dynamically names a demo and sets up the recording.
void CG_autoScreenShot_f (void)
Dynamically names a screenshot.
void CG_keyOn_f (void)
CG_keyOn_f.
void CG_keyOff_f (void)
CG_keyOff_f.
void CG_dumpStats_f (void)
CG_dumpStats_f.
void CG_ForceTapOut_f (void)
CG_ForceTapOut_f.
void CG_parseMapVoteListInfo (void)
CG_parseMapVoteListInfo.
void CG_parseMapVoteTally (void)
CG_parseMapVoteTally.
void CG_ExecuteNewServerCommands (int latestSequence)
Execute all of the server commands that were received along with this this snapshot.
void CG_ParseServerinfo (void)
This is called explicitly when the gamestate is first received, and whenever the server updates any serverinfo flagged cvars.
void CG_ParseSysteminfo (void)
void CG_ParseLegacyinfo (void)
CG_ParseLegacyinfo.
void CG_ParseWolfinfo (void)
CG_ParseWolfinfo.
void CG_ParseSpawns (void)
CG_ParseSpawns.
void CG_ParseServerVersionInfo (const char *pszVersionInfo)
Parse server version info (for demo playback compatibility)
void CG_ParseReinforcementTimes (const char *pszReinfSeedString)
Parse reinforcement offsets.
void CG_SetConfigValues (void)
Called on load to set the initial values from configure strings.
void CG_ShaderStateChanged (void)
CG_ShaderStateChanged.
void CG_ChargeTimesChanged (void)
CG_ChargeTimesChanged.
void CG_TeamRestrictionsChanged (void)
CG_TeamRestrictionsChanged.
void CG_SkillLevelsChanged (void)
CG_SkillLevelsChanged.
void CG_LoadVoiceChats (void)
CG_LoadVoiceChats.
void CG_PlayBufferedVoiceChats (void)
CG_PlayBufferedVoiceChats.
void CG_AddToNotify (const char *str)
const char * CG_LocalizeServerCommand (const char *buf)
Localize string sent from server.
void CG_wstatsParse_cmd (void)
CG_wstatsParse_cmd.
void CG_parseWeaponStats_cmd (void(txt_dump)(const char *))
Client-side stat presentation.
void CG_UpdateSvCvars (void)
CG_UpdateSvCvars.
void CG_Respawn (qboolean revived)
A respawn happened this snapshot.
void CG_TransitionPlayerState (playerState_t *ps, playerState_t *ops)
CG_TransitionPlayerState.
void trap_Print (const char *fmt)
trap_Print
void trap_Error (const char *fmt) __attribute__((noreturn))
trap_Error
int trap_Milliseconds (void)
trap_Milliseconds
int trap_RealTime (qtime_t *qtime)
trap_RealTime
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
trap_Cvar_Register
void trap_Cvar_Update (vmCvar_t *vmCvar)
trap_Cvar_Update
void trap_Cvar_Set (const char *varName, const char *value)
trap_Cvar_Set
void trap_Cvar_VariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_VariableStringBuffer
void trap_Cvar_LatchedVariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
int trap_Argc (void)
trap_Argc
void trap_Argv (int n, char *buffer, int bufferLength)
trap_Argv
void trap_Args (char *buffer, int bufferLength)
trap_Args
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
trap_FS_FOpenFile
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
trap_FS_Read
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
trap_FS_Write
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
trap_FS_GetFileList
int trap_FS_Delete (const char *filename)
trap_FS_Delete
void trap_SendConsoleCommand (const char *text)
trap_SendConsoleCommand
void trap_AddCommand (const char *cmdName)
trap_AddCommand
void trap_RemoveCommand (const char *cmdName)
void trap_SendClientCommand (const char *s)
trap_SendClientCommand
void trap_UpdateScreen (void)
trap_UpdateScreen
void trap_CM_LoadMap (const char *mapname)
trap_CM_LoadMap
int trap_CM_NumInlineModels (void)
trap_CM_NumInlineModels
clipHandle_t trap_CM_InlineModel (int index)
trap_CM_InlineModel
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempBoxModel
clipHandle_t trap_CM_TempCapsuleModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempCapsuleModel
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
trap_CM_PointContents
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedPointContents
void trap_CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_BoxTrace
void trap_CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedBoxTrace
void trap_CM_CapsuleTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_CapsuleTrace
void trap_CM_TransformedCapsuleTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedCapsuleTrace
int trap_CM_MarkFragments (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
trap_CM_MarkFragments
void trap_R_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t *points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
trap_R_ProjectDecal
void trap_R_ClearDecals (void)
trap_R_ClearDecals
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
Starts a sound.
void trap_S_StartSoundVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int volume)
trap_S_StartSoundVControl
void trap_S_StartSoundEx (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags)
trap_S_StartSoundEx
void trap_S_StartSoundExVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags, int volume)
trap_S_StartSoundExVControl
void trap_S_StopStreamingSound (int entityNum)
trap_S_StopStreamingSound
int trap_S_GetSoundLength (sfxHandle_t sfx)
trap_S_GetSoundLength
int trap_S_GetCurrentSoundTime (void)
For timing looped sounds.
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
void trap_S_ClearLoopingSounds (void)
trap_S_ClearLoopingSounds
void trap_S_ClearSounds (qboolean killmusic)
trap_S_ClearSounds
void trap_S_AddLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int volume, int soundTime)
trap_S_AddLoopingSound
void trap_S_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int range, int volume, int soundTime)
trap_S_AddRealLoopingSound
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
trap_S_UpdateEntityPosition
int trap_S_GetVoiceAmplitude (int entityNum)
Talking animations.
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
trap_S_Respatialize
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
trap_S_RegisterSound
void trap_S_StartBackgroundTrack (const char *intro, const char *loop, int fadeupTime)
trap_S_StartBackgroundTrack
void trap_S_FadeBackgroundTrack (float targetvol, int time, int num)
trap_S_FadeBackgroundTrack
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
int trap_S_StartStreamingSound (const char *intro, const char *loop, int entnum, int channel, int attenuation)
trap_S_StartStreamingSound
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
void trap_R_LoadWorldMap (const char *mapname)
trap_R_LoadWorldMap
qhandle_t trap_R_RegisterModel (const char *name)
trap_R_RegisterModel
qhandle_t trap_R_RegisterSkin (const char *name)
trap_R_RegisterSkin
qhandle_t trap_R_RegisterShader (const char *name)
trap_R_RegisterShader
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
trap_R_RegisterShaderNoMip
qboolean trap_R_GetSkinModel (qhandle_t skinid, const char *type, char *name)
trap_R_GetSkinModel
qhandle_t trap_R_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
trap_R_GetShaderFromModel
void trap_R_ClearScene (void)
trap_R_ClearScene
void trap_R_AddRefEntityToScene (const refEntity_t *re)
trap_R_AddRefEntityToScene
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
trap_R_AddPolyToScene
void trap_R_AddPolyBufferToScene (polyBuffer_t *pPolyBuffer)
trap_R_AddPolyBufferToScene
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
trap_R_AddPolysToScene
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
void trap_R_RenderScene (const refdef_t *fd)
trap_R_RenderScene
void trap_R_SetColor (const float *rgba)
trap_R_SetColor
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
void trap_R_DrawStretchPicGradient (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float *gradientColor, int gradientType)
trap_R_DrawStretchPicGradient
void trap_R_Add2dPolys (polyVert_t *verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
int trap_R_LerpTag (orientation_t *tag, const refEntity_t *refent, const char *tagName, int startIndex)
trap_R_LerpTag
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
trap_R_RemapShader
void trap_R_SaveViewParms (void)
trap_R_SaveViewParms
void trap_R_RestoreViewParms (void)
trap_R_RestoreViewParms
void trap_R_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
trap_R_SetFog
void trap_R_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
trap_R_SetGlobalFog
void trap_GetGlconfig (glconfig_t *glconfig)
trap_GetGlconfig
void trap_GetGameState (gameState_t *gamestate)
trap_GetGameState
void trap_GetCurrentSnapshotNumber (int *snapshotNumber, int *serverTime)
trap_GetCurrentSnapshotNumber
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t *snapshot)
trap_GetSnapshot
qboolean trap_GetServerCommand (int serverCommandNumber)
trap_GetServerCommand
int trap_GetCurrentCmdNumber (void)
trap_GetCurrentCmdNumber
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t *ucmd)
trap_GetUserCmd
void trap_SetUserCmdValue (int stateValue, int flags, float sensitivityScale, int mpIdentClient)
trap_SetUserCmdValue
void trap_SetClientLerpOrigin (float x, float y, float z)
trap_SetClientLerpOrigin
void testPrintInt (char *string, int i)
testPrintInt
void testPrintFloat (char *string, float f)
testPrintFloat
int trap_MemoryRemaining (void)
trap_MemoryRemaining
void trap_R_RegisterFont (const char *fontName, int pointSize, void *font)
trap_R_RegisterFont
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
void trap_Key_KeysForBinding (const char *binding, int *key1, int *key2)
trap_Key_KeysForBinding
int trap_Key_GetKey (const char *binding)
trap_Key_GetKey
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
void trap_UI_Popup (int arg0)
trap_UI_Popup
void trap_UI_ClosePopup (const char *arg0)
trap_UI_ClosePopup
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
trap_Key_GetBindingBuf
void trap_Key_SetBinding (int keynum, const char *binding)
trap_Key_SetBinding
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
trap_Key_KeynumToStringBuf
void trap_TranslateString (const char *string, char *buf)
trap_TranslateString
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle.
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
void trap_SnapVector (float *v)
trap_SnapVector
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
trap_GetEntityToken
qboolean trap_R_inPVS (const vec3_t p1, const vec3_t p2)
trap_R_inPVS
void trap_GetHunkData (int *hunkused, int *hunkexpected)
trap_GetHunkData
qboolean trap_SendMessage (char *buf, int buflen)
Binary message channel.
messageStatus_t trap_MessageStatus (void)
trap_MessageStatus
qboolean trap_R_LoadDynamicShader (const char *shadername, const char *shadertext)
Dynamic shaders.
void trap_R_RenderToTexture (int textureid, int x, int y, int w, int h)
Render to texture.
int trap_R_GetTextureId (const char *name)
trap_R_GetTextureId
void trap_R_Finish (void)
Sync rendering.
bg_playerclass_t * CG_PlayerClassForClientinfo (clientInfo_t *ci, centity_t *cent)
CG_PlayerClassForClientinfo.
void CG_FitTextToWidth2 (char *instr, float scale, float w, int size)
CG_FitTextToWidth2.
void CG_FitTextToWidth_Ext (char *instr, float scale, float w, int size, fontHelper_t *font)
CG_FitTextToWidth_Ext.
int CG_TrimLeftPixels (char *instr, float scale, float w, int size)
CG_TrimLeftPixels.
void CG_FitTextToWidth_SingleLine (char *instr, float scale, float w, int size)
CG_FitTextToWidth_SingleLine.
void CG_LocateCampaign (void)
CG_LocateCampaign.
void CG_LocateArena (void)
CG_LocateArena.
const char * CG_DescriptionForCampaign (void)
CG_DescriptionForCampaign.
const char * CG_NameForCampaign (void)
CG_NameForCampaign.
void CG_CloseMenus (void)
void CG_LimboMenu_f (void)
CG_LimboMenu_f.
qboolean CG_UICommonClick (void)
void CG_DrawUISelectedSoldier (void)
void CG_UICurrentSquadSetup (void)
void CG_CampaignBriefingSetup (void)
fireteamData_t * CG_IsOnFireteam (int clientNum)
Fireteam that the specified client is a part of.
fireteamData_t * CG_IsOnSameFireteam (int clientNum, int clientNum2)
Fireteam that both specified clients are on, if they both are on the same team.
fireteamData_t * CG_IsFireTeamLeader (int clientNum)
Fireteam that specified client is leader of, or NULL if none.
clientInfo_t * CG_ClientInfoForPosition (int pos, int max)
Client, not on a fireteam, not sorted, but on your team.
fireteamData_t * CG_FireTeamForPosition (int pos, int max)
Fireteam, that's on your same team.
clientInfo_t * CG_FireTeamPlayerForPosition (int pos, int max)
Client, not sorted by rank, on CLIENT'S fireteam.
void CG_SortClientFireteam (void)
Sorts client's fireteam by leader then rank.
void CG_DrawFireTeamOverlay (rectDef_t *rect)
Draw FireTeam overlay.
clientInfo_t * CG_SortedFireTeamPlayerForPosition (int pos)
Client, sorted by rank, on CLIENT'S fireteam.
qboolean CG_FireteamHasClass (int classnum, qboolean selectedonly)
CG_FireteamHasClass.
const char * CG_BuildSelectedFirteamString (void)
CG_BuildSelectedFirteamString.
qboolean CG_addString (cg_window_t *w, const char *buf)
CG_addString.
void CG_createStatsWindow (void)
CG_createStatsWindow.
void CG_createTopShotsWindow (void)
CG_createTopShotsWindow.
void CG_createWstatsMsgWindow (void)
void CG_createWtopshotsMsgWindow (void)
void CG_createMOTDWindow (void)
CG_createMOTDWindow.
void CG_initStrings (void)
String buffer handling.
void CG_printWindow (const char *str)
CG_printWindow.
void CG_removeStrings (cg_window_t *w)
CG_removeStrings.
cg_window_t * CG_windowAlloc (int fx, int startupLength)
Reserve a window.
void CG_windowDraw (void)
Main window-drawing handler.
void CG_windowFree (cg_window_t *w)
Free up a window reservation.
void CG_windowInit (void)
Windowing system setup.
void CG_windowNormalizeOnText (cg_window_t *w)
Set the window width and height based on the windows text/font parameters.
void CG_SetupCabinets (void)
CG_SetupCabinets.
void CG_ParseSkyBox (void)
CG_ParseSkyBox.
void CG_ParseTagConnect (int tagNum)
CG_ParseTagConnect.
void CG_ParseTagConnects (void)
CG_ParseTagConnects.
void CG_AttachBitsToTank (centity_t *tank, refEntity_t *mg42base, refEntity_t *mg42upper, refEntity_t *mg42gun, refEntity_t *player, refEntity_t *flash, vec_t *playerangles, const char *tagName, qboolean browning)
CG_AttachBitsToTank.
polyBuffer_t * CG_PB_FindFreePolyBuffer (qhandle_t shader, int numVerts, int numIndicies)
CG_PB_FindFreePolyBuffer.
void CG_PB_ClearPolyBuffers (void)
CG_PB_ClearPolyBuffers.
void CG_PB_RenderPolyBuffers (void)
CG_PB_RenderPolyBuffers.
void CG_LimboPanel_KeyHandling (int key, qboolean down)
CG_LimboPanel_KeyHandling.
int CG_LimboPanel_GetMaxObjectives (void)
CG_LimboPanel_GetMaxObjectives.
qboolean CG_LimboPanel_WeaponLights_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_WeaponLights_KeyDown.
qboolean CG_LimboPanel_WeaponPanel_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_WeaponPanel_KeyDown.
qboolean CG_LimboPanel_WeaponPanel_KeyUp (panel_button_t *button, int key)
CG_LimboPanel_WeaponPanel_KeyUp.
qboolean CG_LimboPanel_ObjectiveText_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_ObjectiveText_KeyDown.
qboolean CG_LimboPanel_TeamButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_TeamButton_KeyDown.
qboolean CG_LimboPanel_ClassButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_ClassButton_KeyDown.
qboolean CG_LimboPanel_OkButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_OkButton_KeyDown.
qboolean CG_LimboPanel_PlusButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_PlusButton_KeyDown.
qboolean CG_LimboPanel_MinusButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_MinusButton_KeyDown.
qboolean CG_LimboPanel_CancelButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_CancelButton_KeyDown.
qboolean CG_LimboPanel_Filter_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_Filter_KeyDown.
qboolean CG_LimboPanel_BriefingButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_BriefingButton_KeyDown.
qboolean CG_LimboPanel_SpawnPointButton_KeyDown (panel_button_t *button, int key)
CG_LimboPanel_SpawnPointButton_KeyDown.
void CG_LimboPanel_SpawnPointButton_Draw (panel_button_t *button)
CG_LimboPanel_SpawnPointButton_Draw.
void CG_LimboPanel_BriefingButton_Draw (panel_button_t *button)
CG_LimboPanel_BriefingButton_Draw.
void CG_LimboPanel_ClassBar_Draw (panel_button_t *button)
CG_LimboPanel_ClassBar_Draw.
void CG_LimboPanel_Filter_Draw (panel_button_t *button)
CG_LimboPanel_Filter_Draw.
void CG_LimboPanel_RenderSkillIcon (panel_button_t *button)
CG_LimboPanel_RenderSkillIcon.
void CG_LimboPanel_RenderTeamButton (panel_button_t *button)
CG_LimboPanel_RenderTeamButton.
void CG_LimboPanel_RenderClassButton (panel_button_t *button)
CG_LimboPanel_RenderClassButton.
void CG_LimboPanel_RenderObjectiveText (panel_button_t *button)
void CG_LimboPanel_RenderCommandMap (panel_button_t *button)
CG_LimboPanel_RenderCommandMap.
void CG_LimboPanel_RenderObjectiveBack (panel_button_t *button)
CG_LimboPanel_RenderObjectiveBack.
void CG_LimboPanel_RenderLight (panel_button_t *button)
CG_LimboPanel_RenderLight.
void CG_LimboPanel_WeaponLights (panel_button_t *button)
CG_LimboPanel_WeaponLights.
void CG_LimboPanel_RenderHead (panel_button_t *button)
CG_LimboPanel_RenderHead.
void CG_LimboPanel_WeaponPanel (panel_button_t *button)
CG_LimboPanel_WeaponPanel.
void CG_LimboPanel_Border_Draw (panel_button_t *button)
CG_LimboPanel_Border_Draw.
void CG_LimboPanel_RenderMedal (panel_button_t *button)
CG_LimboPanel_RenderMedal.
void CG_LimboPanel_RenderCounter (panel_button_t *button)
CG_LimboPanel_RenderCounter.
void CG_LimboPanelRenderText_NoLMS (panel_button_t *button)
CG_LimboPanelRenderText_NoLMS.
void CG_LimboPanelRenderText_SkillsText (panel_button_t *button)
CG_LimboPanelRenderText_SkillsText.
void CG_LimboPanel_NameEditFinish (panel_button_t *button)
CG_LimboPanel_NameEditFinish.
void CG_LimboPanel_Setup (void)
CG_LimboPanel_Setup.
void CG_LimboPanel_Init (void)
CG_LimboPanel_Init.
void CG_LimboPanel_RequestObjective (void)
CG_LimboPanel_RequestObjective.
void CG_LimboPanel_RequestWeaponStats (void)
CG_LimboPanel_RequestWeaponStats.
qboolean CG_LimboPanel_Draw (void)
CG_LimboPanel_Draw.
int CG_LimboPanel_GetSpawnPoint (void)
CG_LimboPanel_GetSpawnPoint.
team_t CG_LimboPanel_GetTeam (void)
CG_LimboPanel_GetTeam.
team_t CG_LimboPanel_GetRealTeam (void)
CG_LimboPanel_GetRealTeam.
bg_character_t * CG_LimboPanel_GetCharacter (void)
CG_LimboPanel_GetCharacter.
int CG_LimboPanel_GetClass (void)
CG_LimboPanel_GetClass.
int CG_LimboPanel_ClassCount (team_t checkTeam, int classIndex)
CG_LimboPanel_ClassCount.
int CG_LimboPanel_MaxCount (int playerCount, const char *variableString)
CG_LimboPanel_MaxCount.
int CG_LimboPanel_TeamCount (int weap)
CG_LimboPanel_TeamCount.
int CG_LimboPanel_WeaponCount (int number)
CG_LimboPanel_WeaponCount.
weapon_t CG_LimboPanel_GetSelectedWeapon (int slot)
CG_LimboPanel_GetSelectedWeapon.
void CG_LimboPanel_SetSelectedWeaponNum (int slot, weapon_t weapon)
CG_LimboPanel_SetSelectedWeaponNum.
bg_playerclass_t * CG_LimboPanel_GetPlayerClass (void)
CG_LimboPanel_GetPlayerClass.
weapon_t CG_LimboPanel_GetWeaponForNumber (int number, int slot, qboolean ignoreDisabled)
qboolean CG_LimboPanel_IsValidSelectedWeapon (int slot)
CG_LimboPanel_IsValidSelectedWeapon.
void CG_LimboPanel_SetDefaultWeapon (int slot)
CG_LimboPanel_SetSelectedDefaultWeapon.
qboolean CG_LimboPanel_RealWeaponIsDisabled (weapon_t weapon)
Checks for heavy and rifle weapons.
qboolean CG_LimboPanel_ClassIsDisabled (team_t selectedTeam, int classIndex)
CG_LimboPanel_ClassIsDisabled.
qboolean CG_LimboPanel_TeamIsDisabled (team_t checkTeam)
CG_LimboPanel_TeamIsDisabled.
int CG_LimboPanel_FindFreeClass (team_t checkTeam)
CG_LimboPanel_FindFreeClass.
int CG_LimboPanel_GetWeaponNumberForPos (int pos)
int CG_CurLayerForZ (int z)
CG_CurLayerForZ.
void CG_DrawMap (float x, float y, float w, float h, int mEntFilter, mapScissor_t *scissor, qboolean interactive, float alpha, qboolean borderblend)
CG_DrawMap.
int CG_DrawSpawnPointInfo (float px, float py, float pw, float ph, qboolean draw, mapScissor_t *scissor, int expand)
CG_DrawSpawnPointInfo.
void CG_DrawMortarMarker (float px, float py, float pw, float ph, qboolean draw, mapScissor_t *scissor, int expand)
CG_DrawMortarMarker.
void CG_CommandMap_SetHighlightText (const char *text, float x, float y)
CG_CommandMap_SetHighlightText.
void CG_CommandMap_DrawHighlightText (void)
CG_CommandMap_DrawHighlightText.
qboolean CG_CommandCentreSpawnPointClick (void)
CG_CommandCentreSpawnPointClick.
void CG_DrawPlayerHead (rectDef_t *rect, bg_character_t *character, bg_character_t *headcharacter, float yaw, float pitch, qboolean drawHat, hudHeadAnimNumber_t animation, qhandle_t painSkin, int rank, qboolean spectator, int team)
CG_DrawPlayerHead.
void CG_InitPM (void)
CG_InitPM.
void CG_InitPMGraphics (void)
CG_InitPMGraphics.
void CG_UpdatePMLists (void)
CG_UpdatePMLists.
void CG_AddPMItem (popupMessageType_t type, const char *message, const char *message2, qhandle_t shader, qhandle_t weaponShader, int scaleShader, vec3_t color)
CG_AddPMItem.
void CG_AddPMItemBig (popupMessageBigType_t type, const char *message, qhandle_t shader)
CG_AddPMItemBig.
void CG_DrawPMItems (rectDef_t rect, int style)
CG_DrawPMItems.
void CG_DrawPMItemsBig (void)
CG_DrawPMItemsBig.
const char * CG_GetPMItemText (centity_t *cent)
CG_GetPMItemText.
void CG_PlayPMItemSound (centity_t *cent)
CG_PlayPMItemSound.
qhandle_t CG_GetPMItemIcon (centity_t *cent)
CG_GetPMItemIcon.
clientInfo_t * CG_Debriefing_GetSelectedClientInfo (void)
CG_Debriefing_GetSelectedClientInfo.
void CG_Debrieing_SetSelectedClient (int clientNum)
CG_Debrieing_SetSelectedClient.
qboolean CG_Debriefing_Draw (void)
CG_Debriefing_Draw.
void CG_ChatPanel_Setup (void)
CG_ChatPanel_Setup.
void CG_Debriefing_ChatEditFinish (panel_button_t *button)
CG_Debriefing_ChatEditFinish.
void CG_Debriefing_VoteButton_Draw (panel_button_t *button)
CG_Debriefing_VoteButton_Draw.
void CG_Debriefing_NextButton_Draw (panel_button_t *button)
CG_Debriefing_NextButton_Draw.
void CG_Debriefing_ChatButton_Draw (panel_button_t *button)
CG_Debriefing_ChatButton_Draw.
void CG_Debriefing_ReadyButton_Draw (panel_button_t *button)
CG_Debriefing_ReadyButton_Draw.
qboolean CG_Debriefing_ChatButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_ChatButton_KeyDown.
qboolean CG_Debriefing_ReadyButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_ReadyButton_KeyDown.
qboolean CG_Debriefing_QCButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_QCButton_KeyDown.
qboolean CG_Debriefing_VoteButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_VoteButton_KeyDown.
qboolean CG_Debriefing_NextButton_KeyDown (panel_button_t *button, int key)
CG_Debriefing_NextButton_KeyDown.
void CG_PanelButtonsRender_Button_Ext (rectDef_t *r, const char *text)
CG_PanelButtonsRender_Button_Ext.
void CG_Debriefing_PlayerName_Draw (panel_button_t *button)
CG_Debriefing_PlayerName_Draw.
void CG_Debriefing_PlayerRank_Draw (panel_button_t *button)
CG_Debriefing_PlayerRank_Draw.
void CG_Debriefing_PlayerMedals_Draw (panel_button_t *button)
CG_Debriefing_PlayerMedals_Draw.
void CG_Debriefing_PlayerTime_Draw (panel_button_t *button)
CG_Debriefing_PlayerTime_Draw.
void CG_Debriefing_PlayerXP_Draw (panel_button_t *button)
CG_Debriefing_PlayerXP_Draw.
void CG_Debriefing_PlayerACC_Draw (panel_button_t *button)
CG_Debriefing_PlayerACC_Draw.
void CG_Debriefing_PlayerHS_Draw (panel_button_t *button)
CG_Debriefing_PlayerHS_Draw.
void CG_Debriefing_PlayerSkills_Draw (panel_button_t *button)
CG_Debriefing_PlayerSkills_Draw.
void CG_Debriefing_PlayerHitRegions_Draw (panel_button_t *button)
void CG_DebriefingPlayerWeaponStats_Draw (panel_button_t *button)
CG_DebriefingPlayerWeaponStats_Draw.
void CG_DebriefingXPHeader_Draw (panel_button_t *button)
CG_DebriefingXPHeader_Draw.
void CG_DebriefingTitle_Draw (panel_button_t *button)
CG_DebriefingTitle_Draw.
void CG_DebriefingPlayerList_Draw (panel_button_t *button)
CG_DebriefingPlayerList_Draw.
qboolean CG_DebriefingPlayerList_KeyDown (panel_button_t *button, int key)
CG_DebriefingPlayerList_KeyDown.
void CG_Debriefing_ChatEdit_Draw (panel_button_t *button)
CG_Debriefing_ChatEdit_Draw.
void CG_Debriefing_ChatBox_Draw (panel_button_t *button)
CG_Debriefing_ChatBox_Draw.
void CG_Debriefing_Scrollbar_Draw (panel_button_t *button)
CG_Debriefing_Scrollbar_Draw.
qboolean CG_Debriefing_Scrollbar_KeyDown (panel_button_t *button, int key)
CG_Debriefing_Scrollbar_KeyDown.
qboolean CG_Debriefing_Scrollbar_KeyUp (panel_button_t *button, int key)
CG_Debriefing_Scrollbar_KeyUp.
float CG_Debriefing_CalcCampaignProgress (void)
CG_Debriefing_CalcCampaignProgress.
const char * CG_Debriefing_RankNameForClientInfo (clientInfo_t *ci)
CG_Debriefing_RankNameForClientInfo.
const char * CG_Debriefing_FullRankNameForClientInfo (clientInfo_t *ci)
CG_Debriefing_FullRankNameForClientInfo.
void CG_Debriefing_Startup (void)
CG_Debriefing_Startup.
void CG_Debriefing_Shutdown (void)
CG_Debriefing_Shutdown.
void CG_Debriefing_MouseEvent (int x, int y)
CG_Debriefing_MouseEvent.
void CG_Debriefing_ParseWeaponAccuracies (void)
CG_Debriefing_ParseWeaponAccuracies.
void CG_Debriefing_ParseWeaponStats (void)
CG_Debriefing_ParseWeaponStats.
void CG_Debriefing_ParsePlayerKillsDeaths (void)
CG_Debriefing_ParsePlayerKillsDeaths.
void CG_Debriefing_ParsePlayerTime (void)
CG_Debriefing_ParsePlayerTime.
void CG_Debriefing_ParseSkillRating (void)
void CG_TeamDebriefingTeamSkillXP_Draw (panel_button_t *button)
CG_TeamDebriefingTeamSkillXP_Draw.
const char * CG_PickupItemText (int itemNum)
CG_PickupItemText.
void CG_LoadPanel_DrawPin (const char *text, float px, float py, float sx, float sy, qhandle_t shader, float pinsize, float backheight)
CG_LoadPanel_DrawPin.
void CG_LoadPanel_RenderCampaignPins (panel_button_t *button)
CG_LoadPanel_RenderCampaignPins.
void CG_LoadPanel_RenderMissionDescriptionText (panel_button_t *button)
CG_LoadPanel_RenderMissionDescriptionText.
void CG_LoadPanel_RenderCampaignTypeText (panel_button_t *button)
CG_LoadPanel_RenderCampaignTypeText.
void CG_LoadPanel_RenderCampaignNameText (panel_button_t *button)
CG_LoadPanel_RenderCampaignNameText.
void CG_LoadPanel_RenderLoadingBar (panel_button_t *button)
CG_LoadPanel_RenderLoadingBar.
void CG_LoadPanel_LoadingBarText (panel_button_t *button)
Draws infoScreenText in loading bar.
void CG_LoadPanel_KeyHandling (int key, qboolean down)
CG_LoadPanel_KeyHandling.
void CG_DrawConnectScreen (qboolean interactive, qboolean forcerefresh)
CG_DrawConnectScreen.
qboolean CG_Debriefing_Maps_KeyDown (panel_button_t *button, int key)
CG_Debriefing_Maps_KeyDown.
void CG_Debriefing_TeamSkillHeaders_Draw (panel_button_t *button)
CG_Debriefing_TeamSkillHeaders_Draw.
void CG_Debriefing_TeamSkillXP_Draw (panel_button_t *button)
CG_Debriefing_TeamSkillXP_Draw.
void CG_Debriefing_MissionTitle_Draw (panel_button_t *button)
CG_Debriefing_MissionTitle_Draw.
void CG_Debriefing_Mission_Draw (panel_button_t *button)
CG_Debriefing_Mission_Draw.
void CG_Debriefing_Maps_Draw (panel_button_t *button)
CG_Debriefing_Maps_Draw.
void CG_Debriefing_Awards_Draw (panel_button_t *button)
CG_Debriefing_Awards_Draw.
void CG_PanelButtonsRender_Window (panel_button_t *button)
CG_PanelButtonsRender_Window.
void CG_PanelButtonsRender_Button (panel_button_t *button)
CG_PanelButtonsRender_Button.
team_t CG_Debriefing_FindWinningTeamForMap (void)
CG_Debriefing_FindWinningTeamForMap.
int CG_CalcViewValues (void)
Sets cg.refdef view values.
void CG_HudHeadAnimation (bg_character_t *ch, lerpFrame_t *lf, int *oldframe, int *frame, float *backlerp, hudHeadAnimNumber_t animation)
CG_HudHeadAnimation.
void CG_Fireteams_KeyHandling (int key, qboolean down)
CG_Fireteams_KeyHandling.
qboolean CG_FireteamCheckExecKey (int key, qboolean doaction)
CG_FireteamCheckExecKey.
void CG_Fireteams_Draw (void)
CG_Fireteams_Draw.
void CG_Fireteams_Setup (void)
CG_Fireteams_Setup.
void CG_Fireteams_MenuText_Draw (panel_button_t *button)
CG_Fireteams_MenuText_Draw.
void CG_Fireteams_MenuTitleText_Draw (panel_button_t *button)
void CG_Spawnpoints_KeyHandling (int key, qboolean down)
CG_Spawnpoints_KeyHandling.
qboolean CG_SpawnpointsCheckExecKey (int key, qboolean doaction)
CG_SpawnpointsCheckExecKey.
void CG_Spawnpoints_Draw (void)
CG_Spawnpoints_Draw.
void CG_Spawnpoints_Setup (void)
CG_Spawnpoints_Setup.
void CG_Spawnpoints_MenuText_Draw (panel_button_t *button)
CG_Spawnpoints_MenuText_Draw.
void CG_Spawnpoints_MenuTitleText_Draw (panel_button_t *button)
hudStucture_t * CG_GetActiveHUD ()
CG_getActiveHUD Returns reference to an active hud structure.
Variables
lagometer_t lagometer
cgs_t cgs
cg_t cg
centity_t cg_entities [MAX_GENTITIES]
weaponInfo_t cg_weapons [MAX_WEAPONS]
markPoly_t cg_markPolys [MAX_MARK_POLYS]
vmCvar_t cg_centertime
vmCvar_t cg_bobup
vmCvar_t cg_bobpitch
vmCvar_t cg_bobroll
vmCvar_t cg_swingSpeed
vmCvar_t cg_shadows
vmCvar_t cg_gibs
vmCvar_t cg_draw2D
vmCvar_t cg_drawFPS
vmCvar_t cg_drawPing
vmCvar_t cg_lagometer
vmCvar_t cg_drawSnapshot
vmCvar_t cg_drawCrosshair
vmCvar_t cg_drawCrosshairInfo
vmCvar_t cg_drawCrosshairNames
vmCvar_t cg_drawCrosshairPickups
vmCvar_t cg_useWeapsForZoom
vmCvar_t cg_weaponCycleDelay
vmCvar_t cg_cycleAllWeaps
vmCvar_t cg_crosshairX
vmCvar_t cg_crosshairY
vmCvar_t cg_crosshairSize
vmCvar_t cg_crosshairHealth
vmCvar_t cg_drawStatus
vmCvar_t cg_animSpeed
vmCvar_t cg_debugAnim
vmCvar_t cg_debugPosition
vmCvar_t cg_debugEvents
vmCvar_t cg_drawSpreadScale
vmCvar_t cg_railTrailTime
vmCvar_t cg_errorDecay
vmCvar_t cg_nopredict
vmCvar_t cg_noPlayerAnims
vmCvar_t cg_showmiss
vmCvar_t cg_markTime
vmCvar_t cg_brassTime
vmCvar_t cg_gun_frame
vmCvar_t cg_gun_x
vmCvar_t cg_gun_y
vmCvar_t cg_gun_z
vmCvar_t cg_drawGun
vmCvar_t cg_cursorHints
vmCvar_t cg_letterbox
vmCvar_t cg_tracerChance
vmCvar_t cg_tracerWidth
vmCvar_t cg_tracerLength
vmCvar_t cg_tracerSpeed
vmCvar_t cg_autoswitch
vmCvar_t cg_fov
vmCvar_t cg_muzzleFlash
vmCvar_t cg_zoomDefaultSniper
vmCvar_t cg_zoomStepSniper
vmCvar_t cg_thirdPersonRange
vmCvar_t cg_thirdPersonAngle
vmCvar_t cg_thirdPerson
vmCvar_t cg_teamChatTime
vmCvar_t cg_teamChatHeight
vmCvar_t cg_stats
vmCvar_t cg_coronafardist
vmCvar_t cg_coronas
vmCvar_t cg_buildScript
vmCvar_t cg_paused
vmCvar_t cg_blood
vmCvar_t cg_predictItems
vmCvar_t cg_teamChatsOnly
vmCvar_t cg_voiceChats
vmCvar_t cg_voiceText
vmCvar_t cg_autoactivate
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t cg_timescale
vmCvar_t cg_voiceSpriteTime
vmCvar_t cg_wolfparticles
vmCvar_t cg_gameType
vmCvar_t cg_bloodTime
vmCvar_t cg_skybox
vmCvar_t cg_redlimbotime
vmCvar_t cg_bluelimbotime
vmCvar_t cg_movespeed
vmCvar_t cg_drawCompass
vmCvar_t cg_drawNotifyText
vmCvar_t cg_quickMessageAlt
vmCvar_t cg_descriptiveText
vmCvar_t cg_antilag
vmCvar_t developer
vmCvar_t authLevel
vmCvar_t cf_wstats
vmCvar_t cf_wtopshots
vmCvar_t cg_autoAction
vmCvar_t cg_autoReload
vmCvar_t cg_bloodDamageBlend
vmCvar_t cg_bloodFlash
vmCvar_t cg_complaintPopUp
vmCvar_t cg_crosshairAlpha
vmCvar_t cg_crosshairAlphaAlt
vmCvar_t cg_crosshairColor
vmCvar_t cg_crosshairColorAlt
vmCvar_t cg_crosshairPulse
vmCvar_t cg_drawReinforcementTime
vmCvar_t cg_drawWeaponIconFlash
vmCvar_t cg_noAmmoAutoSwitch
vmCvar_t cg_printObjectiveInfo
vmCvar_t cg_uinfo
vmCvar_t demo_avifpsF1
vmCvar_t demo_avifpsF2
vmCvar_t demo_avifpsF3
vmCvar_t demo_avifpsF4
vmCvar_t demo_avifpsF5
vmCvar_t demo_drawTimeScale
vmCvar_t demo_infoWindow
vmCvar_t int_cl_maxpackets
vmCvar_t int_cl_timenudge
vmCvar_t int_m_pitch
vmCvar_t int_sensitivity
vmCvar_t int_ui_blackout
vmCvar_t cg_rconPassword
vmCvar_t cg_refereePassword
vmCvar_t cg_atmosphericEffects
vmCvar_t cg_drawRoundTimer
vmCvar_t cg_debugSkills
vmCvar_t cg_drawFireteamOverlay
vmCvar_t cg_drawSmallPopupIcons
vmCvar_t cg_instanttapout
vmCvar_t cl_demorecording
vmCvar_t cl_demofilename
vmCvar_t cl_demooffset
vmCvar_t cl_waverecording
vmCvar_t cl_wavefilename
vmCvar_t cl_waveoffset
vmCvar_t cg_recording_statusline
vmCvar_t cg_announcer
vmCvar_t cg_hitSounds
vmCvar_t cg_locations
vmCvar_t cg_spawnTimer_period
vmCvar_t cg_spawnTimer_set
vmCvar_t cg_countryflags
GeoIP.
vmCvar_t cg_altHud
vmCvar_t cg_altHudFlags
vmCvar_t cg_tracers
vmCvar_t cg_fireteamLatchedClass
vmCvar_t cg_simpleItems
vmCvar_t cg_weapaltReloads
vmCvar_t cg_automapZoom
vmCvar_t cg_drawTime
vmCvar_t cg_popupFadeTime
vmCvar_t cg_popupStayTime
vmCvar_t cg_popupFilter
vmCvar_t cg_popupBigFilter
vmCvar_t cg_graphicObituaries
vmCvar_t cg_fontScaleTP
vmCvar_t cg_fontScaleSP
vmCvar_t cg_fontScaleCP
vmCvar_t cg_fontScaleCN
vmCvar_t cg_optimizePrediction
vmCvar_t cg_debugPlayerHitboxes
vmCvar_t cg_quickchat
vmCvar_t cg_drawspeed
vmCvar_t cg_visualEffects
turn invisible (0) / visible (1) visual effect (i.e airstrike plane, debris ...)
qboolean initparticles
const char * aMonths [12]
qboolean ccInitial
rankicon_t rankicons [NUM_EXPERIENCE_LEVELS][2][2]
displayContextDef_t cgDC
qboolean resetmaxspeed
Detailed Description
The entire cgame module is unloaded and reloaded on each level change, so there is NO persistant data between levels on the client side. If you absolutely need something stored, it can either be kept by the server in the server stored userinfos, or stashed in a cvar.
Definition in file cg_local.h.
Macro Definition Documentation
#define AA_DEMORECORD 0x01
Definition at line 94 of file cg_local.h.
Referenced by CG_DrawActiveFrame(), CG_DrawIntermission(), and CG_DrawWarmup().
#define AA_SCREENSHOT 0x02
Definition at line 95 of file cg_local.h.
Referenced by CG_DrawIntermission().
#define AA_STATSDUMP 0x04
Definition at line 96 of file cg_local.h.
Referenced by CG_DrawIntermission(), and CG_setClientFlags().
#define CC_2D_H 352
Definition at line 3564 of file cg_local.h.
Referenced by CG_DrawExpandedAutoMap(), CG_ParseMapEntity(), and CG_TransformToCommandMapCoord().
#define CC_2D_W 352
Definition at line 3563 of file cg_local.h.
Referenced by CG_DrawExpandedAutoMap(), CG_ParseMapEntity(), and CG_TransformToCommandMapCoord().
#define CC_2D_X 64
Definition at line 3561 of file cg_local.h.
Referenced by CG_TransformToCommandMapCoord().
#define CC_2D_Y 23
Definition at line 3562 of file cg_local.h.
Referenced by CG_TransformToCommandMapCoord().
#define CC_FILTER_ALLIES (1 << 1)
Definition at line 3349 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_AXIS (1 << 0)
Definition at line 3348 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_CMDPOST (1 << 3)
Definition at line 3351 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_CONSTRUCTIONS (1 << 5)
Definition at line 3353 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_DESTRUCTIONS (1 << 6)
Definition at line 3354 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_HACABINETS (1 << 4)
Definition at line 3352 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_LANDMINES (1 << 7)
Definition at line 3355 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_OBJECTIVES (1 << 8)
Definition at line 3356 of file cg_local.h.
Referenced by CG_DrawMapEntity().
#define CC_FILTER_SPAWNS (1 << 2)
Definition at line 3350 of file cg_local.h.
Referenced by CG_CommandCentreSpawnPointClick(), and CG_DrawSpawnPointInfo().
#define CPri (x) CG_CenterPrint(CG_LocalizeServerCommand(x), 400, cg_fontScaleCP.value)
Definition at line 3401 of file cg_local.h.
Referenced by CG_DrawWarmup(), CG_ParseWarmup(), CG_ParseWolfinfo(), and CG_ServerCommand().
#define CROSSHAIR_CLASS 0x01
Definition at line 2625 of file cg_local.h.
Referenced by CG_DrawCrosshairNames().
#define CROSSHAIR_RANK 0x02
Definition at line 2626 of file cg_local.h.
Referenced by CG_DrawCrosshairNames().
#define CURSOR_OFFSETX 13
Definition at line 99 of file cg_local.h.
#define CURSOR_OFFSETY 12
Definition at line 100 of file cg_local.h.
#define DAMAGE_DEFLECT_TIME 100
Definition at line 53 of file cg_local.h.
Referenced by CG_OffsetFirstPersonView().
#define DAMAGE_RETURN_TIME 400
Definition at line 54 of file cg_local.h.
Referenced by CG_OffsetFirstPersonView().
#define DAMAGE_TIME 500
Definition at line 55 of file cg_local.h.
Referenced by CG_DamageFeedback(), and CG_DrawFlashDamage().
#define DEMO_ANGLEDELTA 4
Definition at line 105 of file cg_local.h.
Referenced by CG_DemoClick().
#define DEMO_RANGEDELTA 6
Definition at line 104 of file cg_local.h.
Referenced by CG_DemoClick().
#define DEMO_THIRDPERSONUPDATE 0
Definition at line 103 of file cg_local.h.
Referenced by CG_DemoClick().
#define DUCK_TIME 100
Definition at line 59 of file cg_local.h.
Referenced by CG_OffsetFirstPersonView().
#define FADE_TIME 200
Definition at line 52 of file cg_local.h.
Referenced by CG_DrawScoreboard(), and CG_FadeColor().
#define IS_MOUNTED_TANK_BROWNING (entNum) (cg_entities[cg_entities[cg_entities[entNum].tagParent].tankparent].currentState.density & 8)
Definition at line 3704 of file cg_local.h.
Referenced by CG_AddViewWeapon(), CG_Bullet(), CG_DrawFireTeamOverlay(), CG_DrawPlayerWeaponIcon(), CG_EntityEvent(), and CG_FireWeapon().
#define ISVALIDCLIENTNUM (clientNum) ((clientNum) >= 0 && (clientNum) < MAX_CLIENTS)
Definition at line 150 of file cg_local.h.
Referenced by CG_GetLocation().
#define LAG_SAMPLES 128
Definition at line 2082 of file cg_local.h.
Referenced by CG_AddLagometerFrameInfo(), CG_AddLagometerSnapshotInfo(), and CG_DrawLagometer().
#define LAND_DEFLECT_TIME 150
Definition at line 56 of file cg_local.h.
Referenced by CG_CalculateWeaponPosition(), and CG_OffsetFirstPersonView().
#define LAND_RETURN_TIME 300
Definition at line 57 of file cg_local.h.
Referenced by CG_CalculateWeaponPosition(), and CG_OffsetFirstPersonView().
#define LIMBO_3D_H 96
Definition at line 3559 of file cg_local.h.
Referenced by CG_CalcVrect().
#define LIMBO_3D_W 128
Definition at line 3558 of file cg_local.h.
Referenced by CG_CalcVrect(), and CG_LimboPanel_Draw().
#define LIMBO_3D_X 287
Definition at line 3556 of file cg_local.h.
Referenced by CG_CalcVrect(), and CG_LimboPanel_Draw().
#define LIMBO_3D_Y 382
Definition at line 3557 of file cg_local.h.
Referenced by CG_CalcVrect(), and CG_LimboPanel_Draw().
#define LOCALTIME_12HOUR 0x04
Definition at line 2622 of file cg_local.h.
Referenced by CG_DrawLocalTime(), and CG_DrawTimersAlt().
#define LOCALTIME_ON 0x01
Definition at line 2620 of file cg_local.h.
Referenced by CG_DrawTimersAlt(), and CG_DrawUpperRight().
#define LOCALTIME_SECOND 0x02
Definition at line 2621 of file cg_local.h.
Referenced by CG_DrawLocalTime(), and CG_DrawTimersAlt().
#define MAX_BACKUP_STATES (CMD_BACKUP + 2)
Definition at line 954 of file cg_local.h.
Referenced by CG_PredictPlayerState().
#define MAX_BUFFERED_SOUNDSCRIPTS 16
Definition at line 869 of file cg_local.h.
Referenced by CG_AddBufferedSoundScript(), and CG_UpdateBufferedSoundScripts().
#define MAX_C_LOCATIONS 1024
Locations.
Definition at line 1934 of file cg_local.h.
Referenced by CG_LoadLocations().
#define MAX_COMMAND_INFO MAX_CLIENTS
Definition at line 1825 of file cg_local.h.
#define MAX_FLOATING_STRINGS 128
Definition at line 872 of file cg_local.h.
Referenced by CG_AddOnScreenText().
#define MAX_GAMECORONAS 1024
Definition at line 1828 of file cg_local.h.
Referenced by CG_corona().
#define MAX_LAGOMETER_PING 900
Definition at line 2083 of file cg_local.h.
Referenced by CG_DrawLagometer().
#define MAX_LAGOMETER_RANGE 300
Definition at line 2084 of file cg_local.h.
Referenced by CG_DrawLagometer().
#define MAX_LOCKER_DEBRIS 5
Definition at line 1385 of file cg_local.h.
Referenced by CG_RegisterGraphics(), and CG_ShardJunk().
#define MAX_MARK_POLYS 256
was 1024
Definition at line 70 of file cg_local.h.
Referenced by CG_InitMarkPolys().
#define MAX_PREDICTED_EVENTS 16
Definition at line 861 of file cg_local.h.
Referenced by CG_CheckPlayerstateEvents().
#define MAX_SOUNDSCRIPT_SOUNDS 16
Definition at line 870 of file cg_local.h.
Referenced by CG_SoundParseSounds().
#define MAX_SPAWN_VARS 64
Definition at line 863 of file cg_local.h.
Referenced by CG_ParseSpawnVars(), etpro_ScriptAction_SetValues(), G_Lua_CreateEntity(), G_ParseSpawnVars(), and G_ScriptAction_Create().
#define MAX_SPAWN_VARS_CHARS 2048
Definition at line 864 of file cg_local.h.
Referenced by CG_AddSpawnVarToken(), and G_AddSpawnVarToken().
#define MAX_SPAWNDESC 128
Definition at line 867 of file cg_local.h.
Referenced by CG_ParseSpawns().
#define MAX_SPAWNPOINTS 32
Definition at line 866 of file cg_local.h.
#define MAX_STATIC_GAMEMODELS 1024
some maps have > 512 game models (f.e. 'raiders' with 555)
Definition at line 1827 of file cg_local.h.
Referenced by SP_misc_gamemodel().
#define MAX_STEP_CHANGE 32
Definition at line 67 of file cg_local.h.
Referenced by CG_EntityEvent().
#define MAX_STRING_POOL_LENGTH 128
Definition at line 117 of file cg_local.h.
#define MAX_STRINGS 80
Definition at line 116 of file cg_local.h.
Referenced by CG_addString(), CG_initStrings(), and CG_removeStrings().
#define MAX_VERTS_ON_POLY 10
Definition at line 69 of file cg_local.h.
#define MAX_VIEWDAMAGE 8
Definition at line 844 of file cg_local.h.
Referenced by CG_DamageBlendBlob(), and CG_DamageFeedback().
#define MAX_WEAP_BANK_SWITCH_ORDER 4
Definition at line 952 of file cg_local.h.
Referenced by CG_OutOfAmmoChange().
#define MAX_WEAP_BANKS_MP 10
Definition at line 950 of file cg_local.h.
Referenced by CG_MapRestart(), CG_NextWeap(), CG_PrevWeap(), CG_Weapon_f(), CG_WeaponBank_f(), CG_WeaponIndex(), getNextBankWeap(), and getPrevBankWeap().
#define MAX_WEAPON_SOUNDS 5
Definition at line 757 of file cg_local.h.
Referenced by CG_RW_ParseWeaponSound().
#define MAX_WEAPS_IN_BANK_MP 18
Definition at line 951 of file cg_local.h.
Referenced by CG_NextWeap(), CG_OutOfAmmoChange(), CG_PrevWeap(), CG_WeaponBank_f(), CG_WeaponIndex(), getNextWeapInBank(), getPrevBankWeap(), and getPrevWeapInBank().
#define MAX_WINDOW_COUNT 10
Definition at line 113 of file cg_local.h.
Referenced by CG_windowAlloc(), and CG_windowInit().
#define MAX_WINDOW_LINES 64
Definition at line 114 of file cg_local.h.
Referenced by CG_printWindow().
#define MUZZLE_FLASH_TIME 30
Definition at line 62 of file cg_local.h.
Referenced by CG_AddPlayerWeapon(), and CG_AddViewWeapon().
#define NOTIFY_HEIGHT 5
Definition at line 75 of file cg_local.h.
Referenced by CG_AddToNotify().
#define NOTIFY_WIDTH 80
Definition at line 74 of file cg_local.h.
Referenced by CG_AddToNotify().
#define NUM_CROSSHAIRS 16
Definition at line 80 of file cg_local.h.
Referenced by AssetCache(), CG_DrawCrosshair(), CG_RegisterGraphics(), CG_SpeakerEditorDraw(), UI_Crosshair_HandleKey(), and UI_DrawCrosshair().
#define NUM_ENDGAME_AWARDS 20
total number of endgame awards
Definition at line 2013 of file cg_local.h.
Referenced by CG_Debriefing_Awards_Draw(), CG_Debriefing_ParseAwards(), and CG_Debriefing_ScrollGetCount().
#define NUMSHOW_ENDGAME_AWARDS 14
number of awards to display that will fit on screen
Definition at line 2015 of file cg_local.h.
Referenced by CG_Debriefing_Awards_Draw(), and CG_Debriefing_ScrollGetMax().
#define PAIN_TWITCH_TIME 200
Definition at line 60 of file cg_local.h.
Referenced by CG_AddPainTwitch().
#define PERIOD_SAMPLES 5000
Definition at line 2081 of file cg_local.h.
Referenced by CG_AddLagometerSnapshotInfo().
#define Pri (x) CG_Printf("[cgnotify]%s", CG_LocalizeServerCommand(x))
Definition at line 3400 of file cg_local.h.
Referenced by CG_ParseWarmup(), CG_ParseWolfinfo(), and CG_StatsDown_f().
#define PRIMARY_SLOT 1
Definition at line 2073 of file cg_local.h.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_SetSelectedWeaponNum(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponCount(), and CG_LimboPanel_WeaponPanel().
#define PRONE_TIME 500
Definition at line 65 of file cg_local.h.
Referenced by CG_OffsetFirstPersonView().
#define PS_FX_COMMON 1
Definition at line 2630 of file cg_local.h.
Referenced by CG_Bullet(), CG_BulletImpact(), CG_MeleeImpact(), and CG_MissileHitWall().
#define PS_FX_FLESH 3
Definition at line 2632 of file cg_local.h.
Referenced by CG_Bullet(), CG_MissileHitPlayer(), and CG_MissileHitWall().
#define PS_FX_NONE 0
Definition at line 2629 of file cg_local.h.
Referenced by CG_BulletImpact(), CG_Effect(), CG_EntityEvent(), and CG_MissileHitPlayer().
#define PS_FX_WATER 2
Definition at line 2631 of file cg_local.h.
Referenced by CG_BigExplosionImpact(), CG_Bullet(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_Effect(), CG_EntityEvent(), CG_MapMortarImpact(), CG_MissileHitPlayer(), CG_MissileHitWall(), and CG_SmallExplosionImpact().
#define SCREEN_HEIGHT_SAFE SCREEN_HEIGHT
Definition at line 3702 of file cg_local.h.
Referenced by CG_MouseEvent().
#define SCREEN_WIDTH_SAFE Ccg_WideX(SCREEN_WIDTH)
Definition at line 3701 of file cg_local.h.
Referenced by CG_MouseEvent().
#define SECONDARY_SLOT 0
Definition at line 2072 of file cg_local.h.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponPanel_KeyUp(), and CG_NewClientInfo().
#define SINK_TIME 3000
time for fragments to sink into ground before going away
Definition at line 63 of file cg_local.h.
Referenced by CG_AddDebrisElementsExtended().
#define STAT_MINUS 10
num frame for '-' stats digit
Definition at line 72 of file cg_local.h.
Referenced by CG_DrawField().
#define STATS_FADE_TIME 200
Definition at line 51 of file cg_local.h.
Referenced by CG_DemoHelpDraw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_objectivesDown_f(), CG_ObjectivesDraw(), CG_objectivesUp_f(), CG_ShowHelp_Off(), CG_ShowHelp_On(), CG_StatsDown_f(), CG_StatsUp_f(), CG_topshotsDown_f(), CG_TopShotsDraw(), and CG_topshotsUp_f().
#define STEP_TIME 200
Definition at line 58 of file cg_local.h.
Referenced by CG_EntityEvent(), and CG_StepOffset().
#define STYPE_REPEAT 1
Definition at line 84 of file cg_local.h.
Referenced by CG_AddFlameToScene(), CG_AddSmokeJunc(), CG_AddTrailJunc(), and CG_AddTrailToScene().
#define STYPE_STRETCH 0
Definition at line 83 of file cg_local.h.
Referenced by CG_AddFlameToScene(), CG_AddFuseSparkElements(), CG_AddSparkJunc(), CG_AddTrailToScene(), and CG_BloodTrail().
#define TEAMCHAT_HEIGHT 8
Definition at line 78 of file cg_local.h.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
#define TEAMCHAT_WIDTH 70
Definition at line 77 of file cg_local.h.
Referenced by CG_AddToTeamChat().
#define TJFL_CROSSOVER (1 << 1)
Definition at line 87 of file cg_local.h.
Referenced by CG_AddFlameToScene(), and CG_AddTrailToScene().
#define TJFL_FADEIN (1 << 0)
Definition at line 86 of file cg_local.h.
Referenced by CG_AddSmokeJunc(), and CG_AddTrailToScene().
#define TJFL_FIXDISTORT (1 << 3)
Definition at line 89 of file cg_local.h.
Referenced by CG_AddFlameToScene(), and CG_AddTrailToScene().
#define TJFL_NOCULL (1 << 2)
Definition at line 88 of file cg_local.h.
Referenced by CG_AddFlameToScene(), CG_AddSparkJunc(), CG_AddTrailToScene(), and CG_BloodTrail().
#define TJFL_NOPOLYMERGE (1 << 5)
Definition at line 91 of file cg_local.h.
Referenced by CG_AddTrailToScene().
#define TJFL_SPARKHEADFLARE (1 << 4)
Definition at line 90 of file cg_local.h.
Referenced by CG_AddFuseSparkElements(), and CG_AddTrailToScene().
#define UI_CAMPAIGN_BRIEFING 0
Definition at line 3375 of file cg_local.h.
#define UI_COMMAND_MAP 1
Definition at line 3376 of file cg_local.h.
#define UI_SQUAD_SELECT 2
Definition at line 3377 of file cg_local.h.
#define WFX_FADEIN 0x10
Fade the window in (and back out when closing)
Definition at line 134 of file cg_local.h.
Referenced by CG_createMOTDWindow(), CG_createStatsWindow(), CG_createTopShotsWindow(), CG_windowDraw(), CG_windowFree(), and CG_windowReset().
#define WFX_FLASH 0x02
Alternate between bg and b2 every half second.
Definition at line 130 of file cg_local.h.
Referenced by CG_createTopShotsWindow(), and CG_windowDraw().
#define WFX_MULTIVIEW 0x08
Multiview window.
Definition at line 132 of file cg_local.h.
Referenced by CG_removeStrings(), and CG_windowDraw().
#define WFX_SCROLLDOWN 0x40
Scroll window down from the top (and back up when closing)
Definition at line 136 of file cg_local.h.
#define WFX_SCROLLLEFT 0x80
Scroll window in from the left (and back right when closing)
Definition at line 137 of file cg_local.h.
#define WFX_SCROLLRIGHT 0x100
Scroll window in from the right (and back left when closing)
Definition at line 138 of file cg_local.h.
#define WFX_SCROLLUP 0x20
Scroll window up from the bottom (and back down when closing)
Definition at line 135 of file cg_local.h.
Referenced by CG_createTopShotsWindow(), and CG_windowDraw().
#define WFX_TEXTSIZING 0x01
Size the window based on text/font setting.
Definition at line 129 of file cg_local.h.
Referenced by CG_createMOTDWindow(), CG_createStatsWindow(), CG_createTopShotsWindow(), CG_windowDraw(), and CG_wstatsParse_cmd().
#define WFX_TRUETYPE 0x04
Use truetype fonts for text.
Definition at line 131 of file cg_local.h.
Referenced by CG_createStatsWindow(), CG_createTopShotsWindow(), CG_windowDraw(), and CG_windowNormalizeOnText().
#define WID_MOTD 0x04
MOTD.
Definition at line 125 of file cg_local.h.
Referenced by CG_createMOTDWindow().
#define WID_NONE 0x00
General window.
Definition at line 122 of file cg_local.h.
Referenced by CG_windowFree(), and CG_windowReset().
#define WID_STATS 0x01
Stats (reusable due to scroll effect)
Definition at line 123 of file cg_local.h.
Referenced by CG_createStatsWindow(), and CG_wstatsParse_cmd().
#define WID_TOPSHOTS 0x02
Top/Bottom-shots.
Definition at line 124 of file cg_local.h.
Referenced by CG_createTopShotsWindow().
#define WINDOW_FONTHEIGHT 8
For non-true-type: height to scale from.
Definition at line 120 of file cg_local.h.
Referenced by CG_windowNormalizeOnText().
#define WINDOW_FONTWIDTH 8
For non-true-type: width to scale from.
Definition at line 119 of file cg_local.h.
Referenced by CG_windowNormalizeOnText().
#define WSTATE_COMPLETE 0x00
Window is up with startup effects complete.
Definition at line 140 of file cg_local.h.
Referenced by CG_windowDraw(), and CG_windowReset().
#define WSTATE_OFF 0x04
Window is completely shutdown.
Definition at line 143 of file cg_local.h.
Referenced by CG_windowCleanup(), CG_windowDraw(), and CG_windowFree().
#define WSTATE_SHUTDOWN 0x02
Window is shutting down with effects.
Definition at line 142 of file cg_local.h.
Referenced by CG_windowDraw(), CG_windowFree(), and CG_wstatsParse_cmd().
#define WSTATE_START 0x01
Window is "initializing" w/effects.
Definition at line 141 of file cg_local.h.
Referenced by CG_windowDraw(), CG_windowReset(), and CG_wstatsParse_cmd().
#define ZOOM_TIME 150.0f
Definition at line 61 of file cg_local.h.
Referenced by CG_CalcFov(), and CG_DrawSkyBoxPortal().
Typedef Documentation
centity_t
centity_t have a direct corespondence with gentity_t in the game, but only the entityState_t is directly communicated to the cgame
cg_corona_t
cg_gamemodel_t
cg_weaponstats_t
cgs_t
The client game static (cgs) structure should hold everything loaded or calculated from the gamestate. It will NOT be cleared when a tournement restart is done, allowing all clients to begin playing instantly.
clientInfo_t
Each client has an associated clientInfo_t that contains media references necessary to present the client model and other color coded effects this is regenerated each time a client's configstring changes, usually as a result of a userinfo (name, model, etc) change.
typedef struct hudComponent_s hudComponent_t
typedef struct hudStructure_s hudStucture_t
localEntity_t
Local entities are created as a result of events or predicted actions, and live independantly from all server transmitted entities.
location_t
mapScissor_t
A scissored map always has the player in the center.
See also
cg_commandmap.c
markPoly_t
oidInfo_t
partModel_t
sample_t
typedef struct sampledStat_s sampledStat_t
soundScript_t
soundScriptHandle_t
soundScriptSound_t
typedef enum soundSurface_s soundSurface_t
soundSurfaceTable_t
Sound Surface Table.
specLabel_t
tag_t
weaponInfo_t
each WP_* weapon enum has an associated weaponInfo_t that contains media references necessary to present the weapon and its effects
weaponModel_t
typedef struct weaponSounds_s weaponSounds_t
Enumeration Type Documentation
anonymous enum
Enumerator
POPUP_FILTER_CONNECT
POPUP_FILTER_TEAMJOIN
POPUP_FILTER_MISSION
POPUP_FILTER_PICKUP
POPUP_FILTER_DEATH
Definition at line 1917 of file cg_local.h.
anonymous enum
Enumerator
POPUP_BIG_FILTER_SKILL
POPUP_BIG_FILTER_RANK
Definition at line 1927 of file cg_local.h.
anonymous enum
Enumerator
LOC_FTEAM
LOC_VCHAT
LOC_TCHAT
LOC_LANDMINES
LOC_KEEPUNKNOWN
LOC_SHOWCOORDS
LOC_SHOWDISTANCE
LOC_DEBUG
Definition at line 1948 of file cg_local.h.
anonymous enum
Enumerator
BAR_LEFT
BAR_CENTER
BAR_VERT
BAR_NOHUDALPHA
BAR_BG
BAR_BGSPACING_X0Y5
BAR_BGSPACING_X0Y0
BAR_LERP_COLOR
BAR_BORDER
BAR_BORDER_SMALL
Definition at line 1960 of file cg_local.h.
enum barrelType_t
Enumerator
W_PART_1
W_PART_2
W_PART_3
W_PART_4
W_PART_5
W_PART_6
W_PART_7
W_MAX_PARTS
Definition at line 674 of file cg_local.h.
enum hitsooundFlags
Enumerator
HITSOUNDS_ON
HITSOUNDS_NOBODYSHOT
HITSOUNDS_NOHEADSHOT
HITSOUNDS_NOTEAMSHOT
Definition at line 3692 of file cg_local.h.
enum leBounceSoundType_t
Fragment local entities can make sounds on impacts.
Enumerator
LEBS_NONE
LEBS_BLOOD
LEBS_ROCK
LEBS_WOOD
LEBS_BRASS
LEBS_METAL
LEBS_BONE
LEBS_SG_BRASS
Definition at line 496 of file cg_local.h.
enum leFlag_t
Enumerator
LEF_PUFF_DONT_SCALE
do not scale size over time
LEF_TUMBLE
tumble over time, used for ejecting shells
LEF_NOFADEALPHA
sparks
LEF_SMOKING
smoking
LEF_TUMBLE_SLOW
slow down tumble on hitting ground
Definition at line 473 of file cg_local.h.
enum leMarkType_t
Fragment local entities can leave marks on walls.
Enumerator
LEMT_NONE
LEMT_BLOOD
Definition at line 486 of file cg_local.h.
enum leType_t
Enumerator
LE_MARK
LE_EXPLOSION
LE_SPRITE_EXPLOSION
LE_FRAGMENT
LE_MOVE_SCALE_FADE
LE_FALL_SCALE_FADE
LE_FADE_RGB
LE_CONST_RGB
LE_SCALE_FADE
LE_SPARK
LE_DEBRIS
LE_BLOOD
LE_FUSE_SPARK
LE_MOVING_TRACER
LE_EMITTER
Definition at line 450 of file cg_local.h.
enum modelViewType_t
Enumerator
W_TP_MODEL
Third person model.
W_FP_MODEL
First person model.
W_PU_MODEL
Pickup model.
W_NUM_TYPES
Definition at line 690 of file cg_local.h.
enum showView_t
Enumerator
SHOW_OFF
SHOW_SHUTDOWN
SHOW_ON
Definition at line 941 of file cg_local.h.
enum soundSurface_s
Enumerator
W_SND_SURF_DEFAULT
default sound in case of no sound found for given surface
W_SND_SURF_FAR
used sound when player is far from the origin
W_SND_SURF_METAL
W_SND_SURF_WOOD
W_SND_SURF_GRASS
W_SND_SURF_GRAVEL
W_SND_SURF_GLASS
W_SND_SURF_SNOW
W_SND_SURF_ROOF
W_SND_SURF_CARPET
W_SND_SURF_WATER
W_SND_SURF_FLESH
W_MAX_SND_SURF
Definition at line 704 of file cg_local.h.
Function Documentation
qboolean Ccg_Is43Screen (void)
Ccg_Is43Screen.
Returns
Definition at line 64 of file cg_drawtools.c.
Referenced by Ccg_WideX(), Ccg_WideXoffset(), CG_AdjustFrom640(), CG_CalcVrect(), and vmMain().
float Ccg_WideX (float x)
Ccg_WideX.
Parameters
[in] x
Returns
Definition at line 78 of file cg_drawtools.c.
Referenced by CG_CompasMoveLocation(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawBinocReticle(), CG_DrawCenterString(), CG_DrawDisconnect(), CG_DrawExpandedAutoMap(), CG_DrawFireTeamOverlay(), CG_DrawFlashDamage(), CG_DrawFlashFade(), CG_DrawFlashFire(), CG_DrawFlashZoomTransition(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawPMItemsBig(), CG_DrawScoreboard(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawSpeed(), CG_DrawTeamInfo(), CG_DrawTimerNormal(), CG_DrawWarmup(), CG_GameStatsDraw(), CG_Hud_Setup(), CG_ObjectivesDraw(), CG_RectParse(), CG_removeStrings(), CG_ScreenFade(), CG_setDefaultHudValues(), CG_TopShotsDraw(), CG_windowNormalizeOnText(), CG_WorldCoordToScreenCoordFloat(), and WM_DrawInfoLine().
float Ccg_WideXoffset (void)
Ccg_WideXoffset.
Returns
Definition at line 87 of file cg_drawtools.c.
Referenced by CG_DrawInformation().
void CG_ActivateEditSoundMode (void)
CG_ActivateEditSoundMode.
Definition at line 2377 of file cg_sound.c.
Referenced by CG_EditSpeakers_f().
void CG_AddAtmosphericEffects (void)
Add atmospheric effects.
Add atmospheric effects (e.g. rain, snow etc.) to view]
Definition at line 846 of file cg_atmospheric.c.
Referenced by CG_DrawActiveFrame().
void CG_AddCEntity (centity_t * cent)
CG_AddCEntity.
Parameters
[in,out] cent
Definition at line 2589 of file cg_ents.c.
Referenced by CG_AddCEntity_Filter(), and CG_AddPacketEntities().
qboolean CG_AddCEntity_Filter (centity_t * cent)
CG_AddCEntity_Filter.
Parameters
[in] cent
Returns
Definition at line 2895 of file cg_ents.c.
Referenced by CG_AddEntityToTag(), CG_AddPacketEntities(), and CG_AttachBitsToTank().
void CG_AddDebris (vec3_t origin, vec3_t dir, int speed, int duration, int count, trace_t * trace)
CG_AddDebris.
Parameters
[in] origin
[in] dir
[in] speed
[in] duration
[in] count
[in] trace
Todo:
: this is such a waste - change to (or even drop the multiplicator *2)
Todo:
: find better models and/or extend ...
Todo:
: make dependant from surface (snow etc and use related models/sounds) and or weapon
Todo:
: find a client cvar so purists can disable (see CG_AddLocalEntities)
Todo:
: find some other models
Todo:
: replace with surface related models
Definition at line 5124 of file cg_weapons.c.
Referenced by CG_BigExplosionImpact(), CG_DynamiteExplosionImpact(), CG_Effect(), CG_MissileHitWallSmall(), and CG_SmallExplosionImpact().
void CG_AddFlameChunks (void)
CG_AddFlameChunks.
Definition at line 1267 of file cg_flamethrower.c.
Referenced by CG_DrawActiveFrame().
void CG_AddLagometerFrameInfo (void)
Adds the current interpolate / extrapolate bar for this frame.
Definition at line 2485 of file cg_draw_hud.c.
Referenced by CG_DrawActiveFrame().
void CG_AddLagometerSnapshotInfo (snapshot_t * snap)
Log the ping time, server framerate and number of dropped snapshots before it each time a snapshot is received.
Parameters
[in] snap
Todo:
: check this for demoPlayback
Definition at line 2496 of file cg_draw_hud.c.
Referenced by CG_ReadNextSnapshot().
qboolean CG_AddLinkedEntity (centity_t * cent, qboolean ignoreframe, int atTime)
CG_AddLinkedEntity.
Parameters
[in,out] cent
[in] ignoreframe
[in] atTime
Returns
Definition at line 2616 of file cg_ents.c.
Referenced by CG_AddCEntity_Filter(), CG_AddLinkedEntity(), and CG_AdjustPositionForMover().
void CG_AddLocalEntities (void)
CG_AddLocalEntities.
Todo:
merge with CG_AddDebrisElements
Definition at line 1640 of file cg_localents.c.
Referenced by CG_DrawActiveFrame().
void CG_AddMarks (void)
CG_AddMarks.
Definition at line 170 of file cg_marks.c.
Referenced by CG_DrawActiveFrame().
void CG_AddOnScreenText (const char * text, vec3_t origin)
CG_AddOnScreenText.
Parameters
[in] text
[in] origin
Definition at line 750 of file cg_drawtools.c.
Referenced by CG_EntityFloatText(), and CG_PlayerFloatText().
void CG_AddPacketEntities (void)
CG_AddPacketEntities.
Definition at line 2923 of file cg_ents.c.
Referenced by CG_DrawActiveFrame().
void CG_AddParticles (void)
CG_AddParticles.
Definition at line 916 of file cg_particles.c.
Referenced by CG_DrawActiveFrame().
void CG_AddPlayerWeapon (refEntity_t * parent, playerState_t * ps, centity_t * cent)
Used for both the view weapon (ps is valid) and the world modelother character models (ps is NULL) The main player will have this called for BOTH cases, so effects like light and sound should only be done on the world model case.
Parameters
[in] parent
[in] ps
[in,out] cent
Todo:
: this might be useful for other weapons too (move up?)
Definition at line 2450 of file cg_weapons.c.
Referenced by CG_AddViewWeapon(), and CG_Player().
void CG_AddPMItem (popupMessageType_t type, const char * message, const char * message2, qhandle_t shader, qhandle_t weaponShader, int scaleShader, vec3_t color)
CG_AddPMItem.
Parameters
[in] type
[in] message
[in] message2
[in] shader
[in] weaponShader
[in] scaleShader
[in] color
Todo:
: translate this (does it makes sense?)
Definition at line 400 of file cg_popupmessages.c.
Referenced by CG_CPM_f(), CG_EntityEvent(), CG_ItemPickup(), CG_Obituary(), and CG_ServerCommand().
void CG_AddPMItemBig (popupMessageBigType_t type, const char * message, qhandle_t shader)
CG_AddPMItemBig.
Parameters
[in] type
[in] message
[in] shader
Definition at line 555 of file cg_popupmessages.c.
Referenced by CG_NewClientInfo().
void CG_AddRefEntityWithPowerups (refEntity_t * ent, int powerups, int team, entityState_t * es, const vec3_t fireRiseDir)
Adds a piece with modifications or duplications for powerups Also called by CG_Missile for quad rockets, but nobody can tell...
Parameters
[in,out] ent
[in] powerups - unused
[in] team - unused
[in] es
[in] fireRiseDir
Todo:
: onFire is always true !
Definition at line 2329 of file cg_players.c.
Referenced by CG_Missile(), and CG_Player().
void CG_AddScriptSpeakers (void)
CG_AddScriptSpeakers.
Definition at line 2555 of file cg_sound.c.
Referenced by CG_DrawActiveFrame().
int CG_AddSmokeJunc (int headJuncIndex, void * usedby, qhandle_t shader, vec3_t pos, int trailLife, float alpha, float startWidth, float endWidth)
CG_AddSmokeJunc.
Parameters
[in] headJuncIndex
[in] usedby
[in] shader
[in] pos
[in] trailLife
[in] alpha
[in] startWidth
[in] endWidth
Returns
The index of the trail junction created
Definition at line 445 of file cg_trails.c.
Referenced by CG_AddDebrisElements(), and CG_GrenadeTrail().
void CG_AddSmokeSprites (void)
CG_AddSmokeSprites.
Definition at line 1210 of file cg_effects.c.
Referenced by CG_DrawActiveFrame().
int CG_AddSparkJunc (int headJuncIndex, void * usedby, qhandle_t shader, vec3_t pos, int trailLife, float alphaStart, float alphaEnd, float startWidth, float endWidth)
CG_AddSparkJunc.
Parameters
[in] headJuncIndex
[in] usedby
[in] shader
[in] pos
[in] trailLife
[in] alphaStart
[in] alphaEnd
[in] startWidth
[in] endWidth
Returns
The index of the trail junction created
Definition at line 372 of file cg_trails.c.
Referenced by CG_AddBloodElements(), CG_AddDebrisElements(), and CG_AddSparkElements().
qboolean CG_addString (cg_window_t * w, const char * buf)
CG_addString.
Parameters
[in,out] w
[in] buf
Returns
Definition at line 642 of file cg_window.c.
Referenced by CG_printWindow().
void CG_AddToNotify (const char * str)
Definition at line 1183 of file cg_servercmds.c.
Referenced by CG_Printf().
int CG_AddTrailJunc (int headJuncIndex, void * usedby, qhandle_t shader, int spawnTime, int sType, vec3_t pos, int trailLife, float alphaStart, float alphaEnd, float startWidth, float endWidth, int flags, vec3_t colorStart, vec3_t colorEnd, float sRatio, float animSpeed)
Used for generic trails.
Parameters
headJuncIndex
[in,out] usedby
[in] shader
[in] spawnTime
[in] sType
[in] pos
[in] trailLife
[in] alphaStart
[in] alphaEnd
[in] startWidth
[in] endWidth
[in] flags
[in] colorStart
[in] colorEnd
[in] sRatio
[in] animSpeed
Returns
The index of the trail junction created
Todo:
: need a way to specify offset timing
Definition at line 265 of file cg_trails.c.
Referenced by CG_AddFlameToScene(), CG_AddFuseSparkElements(), and CG_BloodTrail().
void CG_AddTrails (void)
CG_AddTrails.
Definition at line 898 of file cg_trails.c.
Referenced by CG_DrawActiveFrame().
void CG_AddViewWeapon (playerState_t * ps)
Add the weapon, and flash for the player's view.
Parameters
[in] ps
Todo:
: ?
Todo:
: HACK dummy model to just draw something
Definition at line 3122 of file cg_weapons.c.
Referenced by CG_DrawActiveFrame().
void CG_AdjustFrom640 (float * x, float * y, float * w, float * h)
Adjusted for resolution and screen aspect ratio.
Parameters
[out] x
[out] y
[out] w
[out] h
Definition at line 45 of file cg_drawtools.c.
Referenced by CG_CalcVrect(), CG_DrawBottom_NoScale(), CG_DrawCrosshair(), CG_DrawExpandedAutoMap(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawMap(), CG_DrawNoShootIcon(), CG_DrawPic(), CG_DrawPicST(), CG_DrawPlayerHead(), CG_DrawRotatedPic(), CG_DrawSides(), CG_DrawSides_NoScale(), CG_DrawSkillBar(), CG_DrawTopBottom(), CG_DrawTopBottom_NoScale(), CG_FillRect(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounterNumber(), CG_SpeakerEditorDraw(), CG_Text_PaintChar(), and CG_Text_PaintChar_Ext().
void CG_AdjustPositionForMover (const vec3_t in, int moverNum, int fromTime, int toTime, vec3_t out, vec3_t outDeltaAngles)
Also called by client movement prediction code.
Parameters
[in] in
[in] moverNum
[in] fromTime
[in] toTime
[in] out
[in] outDeltaAngles
Definition at line 2334 of file cg_ents.c.
Referenced by CG_CalcEntityLerpPositions(), and CG_PredictPlayerState().
localEntity_t* CG_AllocLocalEntity (void)
CG_AllocLocalEntity.
Will allways succeed, even if it requires freeing an old active entity
Returns
Definition at line 427 of file cg_localents.c.
Referenced by CG_AddBloodTrails(), CG_AddDebris(), CG_AddFragment(), CG_AddSparks(), CG_BubbleTrail(), CG_Debris(), CG_Effect(), CG_EntityEvent(), CG_Explodef(), CG_LaunchGib(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_MakeExplosion(), CG_PanzerFaustEjectBrass(), CG_RailTrail2(), CG_RubbleFx(), CG_Shard(), CG_ShardJunk(), CG_SmokePuff(), CG_SparklerSparks(), CG_SpawnTracer(), and CG_WaterRipple().
void CG_AltWeapon_f (void)
For example, switching between WP_MAUSER and WP_SNIPERRIFLE.
Todo:
: This is a horrible way of doing it but theres not other way atm.
Todo:
: This is a horrible way of doing it but theres not other way atm.
Definition at line 3746 of file cg_weapons.c.
const char* CG_Argv (int arg)
CG_Argv.
Parameters
[in] arg
Returns
Definition at line 955 of file cg_main.c.
Referenced by CG_ConfigStringModified(), CG_ConsoleCommand(), CG_CPM_f(), CG_Debriefing_ParsePlayerKillsDeaths(), CG_Debriefing_ParsePlayerTime(), CG_Debriefing_ParseWeaponAccuracies(), CG_Debriefing_ParseWeaponStats(), CG_Fade_f(), CG_parseBestShotsStats_cmd(), CG_parseMapVoteListInfo(), CG_parseMapVoteTally(), CG_ParsePortalPos(), CG_ParseScore(), CG_ParseTeamInfo(), CG_parseTopShotsStats_cmd(), CG_ParseWeaponStats(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_scores_cmd(), CG_SelectBuddy_f(), CG_ServerCommand(), CG_TestModel_f(), CG_topshotsParse_cmd(), CG_VoiceChat(), CG_vstrDown_f(), CG_vstrUp_f(), CG_Weapon_f(), and CG_WeaponBank_f().
void CG_AttachBitsToTank (centity_t * tank, refEntity_t * mg42base, refEntity_t * mg42upper, refEntity_t * mg42gun, refEntity_t * player, refEntity_t * flash, vec_t * playerangles, const char * tagName, qboolean browning)
CG_AttachBitsToTank.
Parameters
[in,out] tank
[out] mg42base
[out] mg42upper
[out] mg42gun
[out] player
[out] flash
[in] playerangles
[in] tagName
[in] browning
Definition at line 3036 of file cg_ents.c.
Referenced by CG_Mover_PostProcess().
void CG_autoRecord_f (void)
Dynamically names a demo and sets up the recording.
Definition at line 833 of file cg_consolecmds.c.
Referenced by CG_DrawActiveFrame(), and CG_DrawWarmup().
void CG_autoScreenShot_f (void)
Dynamically names a screenshot.
Definition at line 841 of file cg_consolecmds.c.
Referenced by CG_DemoClick(), and CG_DrawIntermission().
void CG_Beam (centity_t * cent)
Also called as an event.
Parameters
[in] cent
Definition at line 2004 of file cg_ents.c.
Referenced by CG_ProcessEntity().
void CG_Bleed (vec3_t origin, int entityNum)
This is the spurt of blood when a character gets hit.
Parameters
[in] origin
[in] entityNum
Definition at line 304 of file cg_effects.c.
Referenced by CG_Bullet(), and CG_MissileHitPlayer().
void CG_BubbleTrail (vec3_t start, vec3_t end, float size, float spacing)
Bullets shot underwater.
Parameters
[in] start
[in] end
[in] size
[in] spacing
Definition at line 46 of file cg_effects.c.
Referenced by CG_Bullet(), CG_GrenadeTrail(), and CG_RocketTrail().
char* CG_BuildLocationString (int clientNum, vec3_t origin, int flag)
CG_BuildLocationString.
Parameters
[in] clientNum
[in] origin
[in] flag
Returns
Definition at line 135 of file cg_localents.c.
Referenced by CG_DrawFireTeamOverlay(), CG_GetPMItemText(), CG_ServerCommand(), and CG_VoiceChatLocal().
const char* CG_BuildSelectedFirteamString (void)
CG_BuildSelectedFirteamString.
Returns
Definition at line 829 of file cg_fireteamoverlay.c.
Referenced by CG_AltWeapon_f(), CG_BuddyVoiceChat_f(), CG_FireteamCheckExecKey(), and CG_FTSayPlayerClass_f().
void CG_BuildSolidList (void)
When a new cg.snap has been set, this function builds a sublist of the entities that are actually solid, to make for more efficient collision detection.
Definition at line 55 of file cg_predict.c.
Referenced by CG_SetInitialSnapshot(), and CG_SetNextSnap().
void CG_Bullet (int weapon, vec3_t end, int sourceEntityNum, qboolean flesh, int fleshEntityNum, int otherEntNum2, float waterfraction, int seed)
Renders bullet effects.
Parameters
[in] end
[in] sourceEntityNum
[in] flesh
[in] fleshEntityNum
[in] otherEntNum2
[in] waterfraction
[in] seed
Todo:
Todo:
: AAGUN
Definition at line 6273 of file cg_weapons.c.
Referenced by CG_EntityEvent().
qboolean CG_CalcMuzzlePoint (int entityNum, vec3_t muzzle)
CG_CalcMuzzlePoint.
Parameters
[in] entityNum
[in] muzzle
Returns
Definition at line 6072 of file cg_weapons.c.
Referenced by CG_Bullet(), CG_DrawActiveFrame(), and CG_EntityEffects().
int CG_CalculateReinfTime (qboolean menu)
CG_CalculateReinfTime.
Parameters
menu
Returns
Definition at line 2511 of file cg_draw.c.
Referenced by CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), and WM_DrawObjectives().
float CG_CalculateReinfTime_Float (qboolean menu)
CG_CalculateReinfTime_Float.
Parameters
[in] menu
Returns
Definition at line 2481 of file cg_draw.c.
Referenced by CG_CalculateReinfTime(), and CG_LimboPanel_RenderCounter_ValueForButton().
int CG_CalculateShoutcasterReinfTime (team_t team)
CG_CalculateShoutcasterReinfTime.
Parameters
[in] team
Returns
Definition at line 2521 of file cg_draw.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
int CG_CalcViewValues (void)
Sets cg.refdef view values.
Returns
Definition at line 1220 of file cg_view.c.
Referenced by CG_DrawActiveFrame(), and CG_Mover_PostProcess().
void CG_CampaignBriefingSetup (void)
void CG_CenterPrint (const char * str, int y, float fontScale)
Called for important messages that should stay in the center of the screen for a few moments.
Parameters
[in] str
[in] y
[in] fontScale
Definition at line 703 of file cg_draw.c.
bg_character_t* CG_CharacterForClientinfo (clientInfo_t * ci, centity_t * cent)
Character for clientinfo.
Define character for clientinfo.
Parameters
[in] ci
[in] cent
Returns
Definition at line 583 of file cg_character.c.
Referenced by CG_AddFragment(), CG_EntityEvent(), CG_GetBleedOrigin(), CG_GibPlayer(), CG_LoseHat(), CG_Player(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PredictPlayerState(), CG_SetLerpFrameAnimation(), and CG_SetLerpFrameAnimationRate().
bg_character_t* CG_CharacterForPlayerstate (playerState_t * ps)
Character for playerstate.
Define character for playerstate.
Parameters
[in] ps
Returns
Definition at line 626 of file cg_character.c.
Referenced by CG_DrawPlayerStatusHead().
void CG_ChargeTimesChanged (void)
CG_ChargeTimesChanged.
Definition at line 816 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
void CG_ChatPanel_Setup (void)
CG_ChatPanel_Setup.
Todo:
: only active for gametype 6 ?
Definition at line 1497 of file cg_debriefing.c.
Referenced by CG_RegisterGraphics().
void CG_CheckEvents (centity_t * cent)
CG_CheckEvents.
Parameters
[in] cent
Definition at line 2874 of file cg_event.c.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionEntity().
void CG_CheckForCursorHints (void)
CG_CheckForCursorHints.
Note
Concept in progress...
Definition at line 1537 of file cg_draw.c.
Referenced by CG_DrawCursorhint().
void QDECL int CG_cleanName (const char * pszIn, char * pszOut, int dwMaxLength, qboolean fCRLF)
Strip colors and control codes, copying up to dwMaxLength-1 "good" chars and nul-terminating.
Parameters
[in] pszIn
[out] pszOut
[in] dwMaxLength
[in] fCRLF
Returns
The length of the cleaned string
Definition at line 997 of file cg_main.c.
Referenced by CG_findClientNum(), CG_parseBestShotsStats_cmd(), CG_parseTopShotsStats_cmd(), CG_parseWeaponStats_cmd(), CG_printFile(), CG_scores_cmd(), and CG_topshotsParse_cmd().
void CG_ClearFlameChunks (void)
CG_ClearFlameChunks.
Definition at line 387 of file cg_flamethrower.c.
Referenced by CG_InitFlameChunks(), and CG_MapRestart().
void CG_ClearParticles (void)
CG_ClearParticles.
Definition at line 152 of file cg_particles.c.
Referenced by CG_AddParticles(), CG_MapRestart(), and CG_RegisterGraphics().
void CG_ClearTrails (void)
CG_ClearTrails.
Definition at line 972 of file cg_trails.c.
Referenced by CG_AddTrails(), and CG_Init().
clientInfo_t* CG_ClientInfoForPosition (int pos, int max)
Client, not on a fireteam, not sorted, but on your team.
Parameters
[in] pos
[in] max
Returns
Client information
Note
Unused
Definition at line 252 of file cg_fireteamoverlay.c.
void CG_CloseMenus (void)
void CG_ColorForHealth (vec4_t hcolor)
CG_ColorForHealth.
Parameters
[in] hcolor
Definition at line 639 of file cg_drawtools.c.
Referenced by CG_DrawCrosshair(), CG_DrawFireTeamOverlay(), and CG_DrawPlayerHealthBar().
qboolean CG_CommandCentreSpawnPointClick (void)
CG_CommandCentreSpawnPointClick.
Returns
Definition at line 1907 of file cg_commandmap.c.
Referenced by CG_LimboPanel_KeyHandling().
void CG_CommandMap_DrawHighlightText (void)
CG_CommandMap_DrawHighlightText.
Definition at line 1972 of file cg_commandmap.c.
Referenced by CG_LimboPanel_RenderCommandMap().
void CG_CommandMap_SetHighlightText (const char * text, float x, float y)
CG_CommandMap_SetHighlightText.
Parameters
[in] text
[in] x
[in] y
Definition at line 1961 of file cg_commandmap.c.
Referenced by CG_DrawMapEntity(), and CG_DrawSpawnPointInfo().
const char* CG_ConfigString (int index)
CG_ConfigString.
Parameters
[in] index
Returns
Definition at line 2143 of file cg_main.c.
Referenced by CG_ChargeTimesChanged(), CG_ConfigStringCopy(), CG_ConfigStringModified(), CG_createMOTDWindow(), CG_Debriefing_FindWinningTeamForMap(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_ParseAwards(), CG_Debriefing_Startup(), CG_DebriefingTitle_Draw(), CG_DrawConnectScreen(), CG_DrawCrosshairNames(), CG_DrawFlag(), CG_DrawMapEntity(), CG_DrawScoreboard(), CG_DrawWarmup(), CG_dumpStats(), CG_Effect(), CG_EntityEvent(), CG_generateFilename(), CG_GetPMItemText(), CG_Init(), CG_LimboPanel_GetMaxObjectives(), CG_LimboPanel_RenderObjectiveText(), CG_LoadPanel_RenderCampaignPins(), CG_MapRestart(), CG_NewClientInfo(), CG_NewParticleArea(), CG_ObjectivesDraw(), CG_ParseFireteams(), CG_ParseFog(), CG_ParseGlobalFog(), CG_ParseLegacyinfo(), CG_ParseOIDInfo(), CG_ParseScreenFade(), CG_ParseServerinfo(), CG_ParseSkyBox(), CG_ParseSpawns(), CG_ParseSysteminfo(), CG_ParseTagConnect(), CG_ParseTeamXPs(), CG_ParseWarmup(), CG_ParseWolfinfo(), CG_PlayGlobalSound(), CG_QueueMusic(), CG_RegisterClients(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_SetConfigValues(), CG_SetupDlightstyles(), CG_ShaderStateChanged(), CG_SkillLevelsChanged(), CG_StartMusic(), CG_TeamRestrictionsChanged(), CG_TouchTriggerPrediction(), CG_UpdateSvCvars(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
int CG_ConfigStringCopy (int index, char * buff, size_t buffsize)
CG_ConfigStringCopy.
Parameters
[in] index
[out] buff
[in] buffsize
Returns
Definition at line 2159 of file cg_main.c.
Referenced by CG_LoadHudMenu().
qboolean CG_ConsoleCommand (void)
The string has been tokenized and can be retrieved with Cmd_Argc() / Cmd_Argv()
Returns
Definition at line 2022 of file cg_consolecmds.c.
Referenced by vmMain().
void CG_createMOTDWindow (void)
CG_createMOTDWindow.
Todo:
TODO: dynamic game server MOTD window, see CG_DrawInformation()
Definition at line 94 of file cg_window.c.
void CG_createStatsWindow (void)
CG_createStatsWindow.
Definition at line 47 of file cg_window.c.
Referenced by CG_wstatsParse_cmd().
void CG_createTopShotsWindow (void)
CG_createTopShotsWindow.
Note
Unused
Definition at line 69 of file cg_window.c.
void CG_createWstatsMsgWindow (void)
void CG_createWtopshotsMsgWindow (void)
int CG_CrosshairPlayer (void)
CG_CrosshairPlayer.
Returns
Definition at line 802 of file cg_main.c.
Referenced by vmMain().
qboolean CG_CullPoint (vec3_t pt)
CG_CullPoint.
Parameters
pt
Returns
true if culled otherwise false
Definition at line 1730 of file cg_view.c.
Referenced by CG_ParticleRender().
qboolean CG_CullPointAndRadius (const vec3_t pt, vec_t radius)
CG_CullPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
Definition at line 1755 of file cg_view.c.
Referenced by CG_AddFlameSpriteToScene(), and CG_DrawMiscGamemodels().
int CG_CurLayerForZ (int z)
CG_CurLayerForZ.
Parameters
[in] z
Returns
Definition at line 61 of file cg_commandmap.c.
Referenced by CG_CommandCentreSpawnPointClick(), CG_DrawAutoMap(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), and CG_LimboPanel_Setup().
sfxHandle_t CG_CustomSound (int clientNum, const char * soundName)
CG_CustomSound.
Parameters
clientNum - unused
[in] soundName
Returns
Definition at line 99 of file cg_players.c.
Referenced by CG_EntityEvent(), and CG_PlayGlobalSound().
float CG_Cvar_Get (const char * cvar)
CG_Cvar_Get.
Parameters
[in] cvar
Returns
Definition at line 2379 of file cg_main.c.
Referenced by CG_LoadHudMenu().
void CG_DeActivateEditSoundMode (void)
CG_DeActivateEditSoundMode.
Definition at line 2400 of file cg_sound.c.
Referenced by CG_EditSpeakers_f().
void CG_Debriefing_Awards_Draw (panel_button_t * button)
CG_Debriefing_Awards_Draw.
Parameters
[in] button
Definition at line 3467 of file cg_debriefing.c.
float CG_Debriefing_CalcCampaignProgress (void)
CG_Debriefing_CalcCampaignProgress.
Returns
Note
Unused
Definition at line 3141 of file cg_debriefing.c.
void CG_Debriefing_ChatBox_Draw (panel_button_t * button)
CG_Debriefing_ChatBox_Draw.
Parameters
[in] button
Definition at line 1420 of file cg_debriefing.c.
void CG_Debriefing_ChatButton_Draw (panel_button_t * button)
CG_Debriefing_ChatButton_Draw.
Parameters
[in] button
Definition at line 2972 of file cg_debriefing.c.
qboolean CG_Debriefing_ChatButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_ChatButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 2914 of file cg_debriefing.c.
void CG_Debriefing_ChatEdit_Draw (panel_button_t * button)
CG_Debriefing_ChatEdit_Draw.
Parameters
[in] button
Definition at line 1379 of file cg_debriefing.c.
void CG_Debriefing_ChatEditFinish (panel_button_t * button)
CG_Debriefing_ChatEditFinish.
Parameters
[in] button
Definition at line 3112 of file cg_debriefing.c.
qboolean CG_Debriefing_Draw (void)
CG_Debriefing_Draw.
Returns
Definition at line 1642 of file cg_debriefing.c.
Referenced by CG_DrawIntermission().
team_t CG_Debriefing_FindWinningTeamForMap (void)
CG_Debriefing_FindWinningTeamForMap.
Returns
Definition at line 3769 of file cg_debriefing.c.
Referenced by CG_Debriefing_MissionTitle_Draw().
const char* CG_Debriefing_FullRankNameForClientInfo (clientInfo_t * ci)
CG_Debriefing_FullRankNameForClientInfo.
Parameters
[in] ci
Returns
Definition at line 2010 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerRank_Draw().
clientInfo_t* CG_Debriefing_GetSelectedClientInfo (void)
CG_Debriefing_GetSelectedClientInfo.
Returns
Definition at line 2871 of file cg_debriefing.c.
Referenced by CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Debriefing_PlayerTime_Draw(), and CG_Debriefing_PlayerXP_Draw().
void CG_Debriefing_KeyEvent (int key, qboolean down)
CG_Debriefing_KeyEvent.
Parameters
[in] key
[in] down
Definition at line 2503 of file cg_debriefing.c.
Referenced by CG_KeyEvent().
void CG_Debriefing_Maps_Draw (panel_button_t * button)
CG_Debriefing_Maps_Draw.
Parameters
[in] button
Definition at line 3516 of file cg_debriefing.c.
qboolean CG_Debriefing_Maps_KeyDown (panel_button_t * button, int key)
CG_Debriefing_Maps_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 3936 of file cg_debriefing.c.
void CG_Debriefing_Mission_Draw (panel_button_t * button)
CG_Debriefing_Mission_Draw.
Parameters
[in] button
Definition at line 3564 of file cg_debriefing.c.
void CG_Debriefing_MissionTitle_Draw (panel_button_t * button)
CG_Debriefing_MissionTitle_Draw.
Parameters
[in] button
Definition at line 3342 of file cg_debriefing.c.
void CG_Debriefing_MouseEvent (int x, int y)
CG_Debriefing_MouseEvent.
Parameters
[in] x
[in] y
Definition at line 2370 of file cg_debriefing.c.
Referenced by CG_MouseEvent().
void CG_Debriefing_NextButton_Draw (panel_button_t * button)
CG_Debriefing_NextButton_Draw.
Parameters
[in] button
Definition at line 3103 of file cg_debriefing.c.
qboolean CG_Debriefing_NextButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_NextButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3068 of file cg_debriefing.c.
void CG_Debriefing_ParsePlayerKillsDeaths (void)
CG_Debriefing_ParsePlayerKillsDeaths.
Definition at line 2086 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_ParsePlayerTime (void)
CG_Debriefing_ParsePlayerTime.
Definition at line 2053 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_ParseSkillRating (void)
Referenced by CG_Debriefing_ParsePlayerTime(), and CG_ServerCommand().
void CG_Debriefing_ParseWeaponAccuracies (void)
CG_Debriefing_ParseWeaponAccuracies.
Definition at line 2038 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_ParseWeaponStats (void)
CG_Debriefing_ParseWeaponStats.
Definition at line 2105 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_Debriefing_PlayerACC_Draw (panel_button_t * button)
CG_Debriefing_PlayerACC_Draw.
Parameters
[in] button
Definition at line 2684 of file cg_debriefing.c.
void CG_Debriefing_PlayerHitRegions_Draw (panel_button_t * button)
Definition at line 2589 of file cg_debriefing.c.
void CG_Debriefing_PlayerHS_Draw (panel_button_t * button)
CG_Debriefing_PlayerHS_Draw.
Parameters
[in] button
Definition at line 2700 of file cg_debriefing.c.
void CG_Debriefing_PlayerMedals_Draw (panel_button_t * button)
CG_Debriefing_PlayerMedals_Draw.
Parameters
[in] button
Definition at line 2787 of file cg_debriefing.c.
void CG_Debriefing_PlayerName_Draw (panel_button_t * button)
CG_Debriefing_PlayerName_Draw.
Parameters
[in] button
Definition at line 2839 of file cg_debriefing.c.
void CG_Debriefing_PlayerRank_Draw (panel_button_t * button)
CG_Debriefing_PlayerRank_Draw.
Parameters
[in] button
Definition at line 2814 of file cg_debriefing.c.
void CG_Debriefing_PlayerSkills_Draw (panel_button_t * button)
CG_Debriefing_PlayerSkills_Draw.
Parameters
[in] button
Definition at line 2546 of file cg_debriefing.c.
void CG_Debriefing_PlayerTime_Draw (panel_button_t * button)
CG_Debriefing_PlayerTime_Draw.
Parameters
[in] button
Definition at line 2755 of file cg_debriefing.c.
void CG_Debriefing_PlayerXP_Draw (panel_button_t * button)
CG_Debriefing_PlayerXP_Draw.
Parameters
[in] button
Definition at line 2716 of file cg_debriefing.c.
qboolean CG_Debriefing_QCButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_QCButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3028 of file cg_debriefing.c.
const char* CG_Debriefing_RankNameForClientInfo (clientInfo_t * ci)
CG_Debriefing_RankNameForClientInfo.
Parameters
[in] ci
Returns
Definition at line 2025 of file cg_debriefing.c.
Referenced by CG_DebriefingPlayerList_Draw().
void CG_Debriefing_ReadyButton_Draw (panel_button_t * button)
CG_Debriefing_ReadyButton_Draw.
Parameters
[in] button
Definition at line 2946 of file cg_debriefing.c.
qboolean CG_Debriefing_ReadyButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_ReadyButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3000 of file cg_debriefing.c.
void CG_Debriefing_Scrollbar_Draw (panel_button_t * button)
CG_Debriefing_Scrollbar_Draw.
Parameters
[in] button
Definition at line 2440 of file cg_debriefing.c.
Referenced by CG_Debriefing_MouseEvent().
qboolean CG_Debriefing_Scrollbar_KeyDown (panel_button_t * button, int key)
CG_Debriefing_Scrollbar_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2463 of file cg_debriefing.c.
qboolean CG_Debriefing_Scrollbar_KeyUp (panel_button_t * button, int key)
CG_Debriefing_Scrollbar_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 2486 of file cg_debriefing.c.
void CG_Debriefing_Shutdown (void)
CG_Debriefing_Shutdown.
Definition at line 1568 of file cg_debriefing.c.
Referenced by CG_Draw2D().
void CG_Debriefing_Startup (void)
CG_Debriefing_Startup.
Definition at line 1518 of file cg_debriefing.c.
Referenced by CG_Debriefing_Draw().
void CG_Debriefing_TeamSkillHeaders_Draw (panel_button_t * button)
CG_Debriefing_TeamSkillHeaders_Draw.
Parameters
[in] button
Definition at line 3974 of file cg_debriefing.c.
void CG_Debriefing_TeamSkillXP_Draw (panel_button_t * button)
CG_Debriefing_TeamSkillXP_Draw.
Parameters
[in] button
Definition at line 4005 of file cg_debriefing.c.
void CG_Debriefing_VoteButton_Draw (panel_button_t * button)
CG_Debriefing_VoteButton_Draw.
Parameters
[in] button
Definition at line 3089 of file cg_debriefing.c.
qboolean CG_Debriefing_VoteButton_KeyDown (panel_button_t * button, int key)
CG_Debriefing_VoteButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 3044 of file cg_debriefing.c.
void CG_DebriefingPlayerList_Draw (panel_button_t * button)
CG_DebriefingPlayerList_Draw.
Parameters
[in] button
Definition at line 1908 of file cg_debriefing.c.
qboolean CG_DebriefingPlayerList_KeyDown (panel_button_t * button, int key)
CG_DebriefingPlayerList_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1703 of file cg_debriefing.c.
void CG_DebriefingPlayerWeaponStats_Draw (panel_button_t * button)
CG_DebriefingPlayerWeaponStats_Draw.
Parameters
[in] button
Definition at line 1753 of file cg_debriefing.c.
void CG_DebriefingTitle_Draw (panel_button_t * button)
CG_DebriefingTitle_Draw.
Parameters
[in] button
Note
Unused
Definition at line 1805 of file cg_debriefing.c.
void CG_DebriefingXPHeader_Draw (panel_button_t * button)
CG_DebriefingXPHeader_Draw.
Parameters
[in] button
Definition at line 1890 of file cg_debriefing.c.
void CG_Debrieing_SetSelectedClient (int clientNum)
CG_Debrieing_SetSelectedClient.
Parameters
[in] clientNum
Definition at line 2894 of file cg_debriefing.c.
Referenced by CG_Debriefing_GetSelectedClientInfo(), and CG_DebriefingPlayerList_KeyDown().
void CG_DemoClick (int key, qboolean down)
Demo playback key catcher support.
Parameters
[in] key
[in] down
Definition at line 324 of file cg_info.c.
Referenced by CG_KeyEvent().
const char* CG_DescriptionForCampaign (void)
CG_DescriptionForCampaign.
Returns
Definition at line 41 of file cg_missionbriefing.c.
Referenced by CG_LoadHudMenu().
void QDECL void QDECL CG_DPrintf (const char * msg, ...)
Referenced by CG_EntityEvent(), CG_RegisterItemVisuals(), and trap_TranslateString().
void CG_DrawActive (void)
Perform all drawing needed to completely fill the screen.
Definition at line 3898 of file cg_draw.c.
Referenced by CG_DrawActiveFrame().
void CG_DrawActiveFrame (int serverTime, qboolean demoPlayback)
Generates and draws a game scene and status information at the given time.
Parameters
[in] serverTime
[in] demoPlayback
Todo:
: this is a hack for the time being since a scripted "selectweapon" does
Definition at line 1978 of file cg_view.c.
Referenced by vmMain().
void CG_DrawActiveHud (void)
CG_DrawActiveHud.
Definition at line 3074 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
void CG_DrawAutoMap (float x, float y, float w, float h)
CG_DrawAutoMap.
Parameters
[in] x
[in] y
[in] w
[in] h
Definition at line 1493 of file cg_commandmap.c.
Referenced by CG_DrawNewCompass().
void CG_DrawBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawBottom_NoScale.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 346 of file cg_drawtools.c.
Referenced by WM_TeamScoreboard().
void CG_DrawConnectScreen (qboolean interactive, qboolean forcerefresh)
CG_DrawConnectScreen.
Parameters
[in] interactive
[in] forcerefresh
Definition at line 283 of file cg_loadpanel.c.
Referenced by CG_DrawInformation().
void CG_DrawCursorhint (rectDef_t * rect)
CG_DrawCursorhint.
Parameters
[in] rect
Note
cg_cursorHints.integer == 0: no hints 1: sin size pulse 2: one way size pulse 3: alpha pulse 4+: static image
Definition at line 355 of file cg_newDraw.c.
Referenced by CG_DrawActiveHud().
void CG_DrawExpandedAutoMap (void)
CG_DrawExpandedAutoMap.
Definition at line 1359 of file cg_commandmap.c.
Referenced by CG_DrawAutoMap(), and CG_DrawNewCompass().
void CG_DrawFireTeamOverlay (rectDef_t * rect)
Draw FireTeam overlay.
Parameters
[in] rect
Definition at line 380 of file cg_fireteamoverlay.c.
Referenced by CG_DrawUpperRight().
void CG_DrawGlobalHud (void)
CG_DrawGlobalHud.
Definition at line 3107 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
void CG_DrawInformation (qboolean forcerefresh)
Draw all the status / pacifier stuff during level loading.
Parameters
[in] forcerefresh
Todo:
: dynamic game server MOTD window
Definition at line 83 of file cg_info.c.
Referenced by CG_DrawActive(), CG_DrawActiveFrame(), trap_CM_LoadMap(), trap_R_LoadWorldMap(), trap_R_RegisterFont(), trap_R_RegisterModel(), trap_R_RegisterShader(), trap_R_RegisterShaderNoMip(), trap_R_RegisterSkin(), trap_S_RegisterSound(), and trap_TranslateString().
void CG_DrawMap (float x, float y, float w, float h, int mEntFilter, mapScissor_t * scissor, qboolean interactive, float alpha, qboolean borderblend)
CG_DrawMap.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] mEntFilter
[in] scissor
[in] interactive
[in] alpha
[in] borderblend
Todo:
: the code above seems to do weird things to the next trap_R_DrawStretchPic issued.
Definition at line 1156 of file cg_commandmap.c.
Referenced by CG_DrawAutoMap(), CG_DrawExpandedAutoMap(), and CG_LimboPanel_RenderCommandMap().
qboolean CG_DrawMissionBriefing (void)
void CG_DrawMortarMarker (float px, float py, float pw, float ph, qboolean draw, mapScissor_t * scissor, int expand)
CG_DrawMortarMarker.
Parameters
[in] px
[in] py
[in] pw
[in] ph
[in] draw - unused
[in] scissor - unused
[in] expand
Definition at line 1789 of file cg_commandmap.c.
Referenced by CG_DrawMap().
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
CG_DrawPic.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] hShader
Note
Coordinates are 640*480 virtual values
Definition at line 419 of file cg_drawtools.c.
Referenced by CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_DemoClick(), CG_Draw2D(), CG_DrawBinocReticle(), CG_DrawBorder(), CG_DrawBreathBar(), CG_DrawCompassIcon(), CG_DrawConnectScreen(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawDisconnect(), CG_DrawField(), CG_DrawFireTeamOverlay(), CG_DrawFlashFire(), CG_DrawFollow(), CG_DrawLivesLeft(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNewCompass(), CG_DrawObjectiveInfo(), CG_DrawPicShadowed(), CG_DrawPlayerHealthBar(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawScopedReticle(), CG_DrawSkills(), CG_DrawSpawnPointInfo(), CG_DrawStaminaBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawWeapRecharge(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_Draw(), CG_LimboPanel_Filter_Draw(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderLight(), CG_LimboPanel_RenderMedal(), CG_LimboPanel_RenderObjectiveBack(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_SpawnPointButton_Draw(), CG_LimboPanel_WeaponLights(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_MapVoteList_Draw(), CG_ObjectivesDraw(), CG_SpeakerEditorDraw(), CG_windowDraw(), WM_DrawClientScore(), WM_DrawClientScore_Small(), and WM_DrawObjectives().
void CG_DrawPicST (float x, float y, float width, float height, float s0, float t0, float s1, float t1, qhandle_t hShader)
Allows passing of st co-ords.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] s0
[in] t0
[in] s1
[in] t1
[in] hShader
Note
Coordinates are 640*480 virtual values
Definition at line 404 of file cg_drawtools.c.
Referenced by CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_DrawBorder(), CG_DrawFlag(), CG_LimboPanel_RenderHead(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadPanel_RenderLoadingBar(), and WM_TeamScoreboard().
void CG_DrawPlayerHead (rectDef_t * rect, bg_character_t * character, bg_character_t * headcharacter, float yaw, float pitch, qboolean drawHat, hudHeadAnimNumber_t animation, qhandle_t painSkin, int rank, qboolean spectator, int team)
CG_DrawPlayerHead.
Parameters
[in] rect
[in] character
[in] headcharacter
[in] yaw
[in] pitch
[in] drawHat
[in] animation
[in] painSkin
[in] rank
[in] spectator - unused
[in] team
Definition at line 2016 of file cg_limbopanel.c.
Referenced by CG_DrawPlayerStatusHead(), and CG_LimboPanel_RenderHead().
void CG_DrawPlayerWeaponIcon (rectDef_t * rect, qboolean drawHighlighted, int align, vec4_t * refcolor)
CG_DrawPlayerWeaponIcon.
Parameters
[in] rect
drawHighlighted - unused
[in] align
[in] refcolor
Definition at line 232 of file cg_newDraw.c.
Referenced by CG_DrawGunIcon().
void CG_DrawPMItems (rectDef_t rect, int style)
CG_DrawPMItems.
Parameters
[in] rect
[in] style
Definition at line 609 of file cg_popupmessages.c.
Referenced by CG_DrawGlobalHud().
void CG_DrawPMItemsBig (void)
CG_DrawPMItemsBig.
Definition at line 775 of file cg_popupmessages.c.
Referenced by CG_DrawGlobalHud().
void CG_DrawRect (float x, float y, float width, float height, float size, const float * color)
CG_DrawRect.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] size
[in,out] color
Note
Coordinates are 640*480 virtual values
Definition at line 362 of file cg_drawtools.c.
Referenced by CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawDemoControls(), CG_DrawFireTeamOverlay(), CG_DrawObjectiveInfo(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_LoadHudMenu(), CG_ObjectivesDraw(), CG_SpeakerEditor_Back(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerInfo_Text(), CG_TopShotsDraw(), and CG_windowDraw().
void CG_DrawRect_FixedBorder (float x, float y, float width, float height, int border, const float * color)
CG_DrawRect_FixedBorder.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] border
[in,out] color
Definition at line 381 of file cg_drawtools.c.
Referenced by CG_Debriefing_Scrollbar_Draw(), CG_DemoClick(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSkillBar(), CG_DrawSnapshot(), CG_DrawSpeed(), CG_DrawTimerNormal(), CG_FilledBar(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void CG_DrawRotatedPic (float x, float y, float width, float height, qhandle_t hShader, float angle)
CG_DrawRotatedPic.
Clear around a sized down screen
Parameters
[in] x
[in] y
[in] width
[in] height
[in] hShader
[in] angle
Definition at line 464 of file cg_drawtools.c.
Referenced by CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMortarMarker(), and CG_DrawNewCompass().
qboolean CG_DrawScoreboard (void)
Draw the normal in-game scoreboard.
Returns
Definition at line 1296 of file cg_scoreboard.c.
Referenced by CG_Debriefing_Draw(), and CG_Draw2D().
void CG_DrawSides (float x, float y, float w, float h, float size)
CG_DrawSides.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 280 of file cg_drawtools.c.
Referenced by CG_DrawRect(), and CG_LoadHudMenu().
void CG_DrawSkyBoxPortal (qboolean fLocalView)
CG_DrawSkyBoxPortal.
Parameters
[in] fLocalView
Definition at line 1579 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
int CG_DrawSpawnPointInfo (float px, float py, float pw, float ph, qboolean draw, mapScissor_t * scissor, int expand)
CG_DrawSpawnPointInfo.
Parameters
[in] px
[in] py
[in] pw
[in] ph
[in] draw
[in] scissor
[in] expand
Returns
Definition at line 1612 of file cg_commandmap.c.
Referenced by CG_DrawMap().
qboolean CG_DrawStatsRanksMedals (void)
void CG_DrawStretchPic (float x, float y, float width, float height, qhandle_t hShader)
void CG_DrawTeamBackground (int x, int y, int w, int h, float alpha, int team)
CG_DrawTeamBackground.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] alpha
[in] team
Note
Unused
Definition at line 471 of file cg_draw.c.
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
CG_DrawTopBottom.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 297 of file cg_drawtools.c.
Referenced by CG_DrawRect(), and CG_LoadHudMenu().
void CG_DrawTopBottom_NoScale (float x, float y, float w, float h, float size)
CG_DrawTopBottom_NoScale.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Note
Coordinates are 640*480 virtual values
Definition at line 330 of file cg_drawtools.c.
Referenced by CG_DrawRect_FixedBorder().
void CG_DrawTracer (const vec3_t start, const vec3_t finish)
CG_DrawTracer.
Parameters
[in] start
[in] finish
Definition at line 5980 of file cg_weapons.c.
Referenced by CG_AddMovingTracer(), and CG_Tracer().
void CG_DrawUISelectedSoldier (void)
void CG_DrawUpperRight (void)
CG_DrawUpperRight.
Definition at line 3137 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
void CG_DrawWeapHeat (rectDef_t * rect, int align)
CG_DrawWeapHeat.
Parameters
[in] rect
[in] align
Definition at line 580 of file cg_newDraw.c.
Referenced by CG_DrawGunIcon().
void CG_DrawWeapStability (rectDef_t * rect)
Draw a bar showing current stability level (0-255), max at current weapon/ability, and 'perfect' reference mark probably only drawn for scoped weapons.
Parameters
[in] rect
Definition at line 542 of file cg_newDraw.c.
Referenced by CG_DrawActiveHud().
void CG_dumpStats_f (void)
CG_dumpStats_f.
Definition at line 912 of file cg_consolecmds.c.
Referenced by CG_DrawIntermission().
void CG_EDV_RunInput (void)
Referenced by CG_DrawActiveFrame().
void CG_EDV_WeaponCam (centity_t * cent, refEntity_t * ent)
Referenced by CG_Missile().
void CG_EffectParse (const char * effectstr)
Parse effect.
Split the string into it's component parts.
Parameters
[in] effectstr
Definition at line 667 of file cg_atmospheric.c.
Referenced by SP_worldspawn().
void CG_EntityEvent (centity_t * cent, vec3_t position)
An entity has an event value also called by CG_CheckPlayerstateEvents.
Parameters
[in] cent
[in] position
Todo:
: CHAN_LOCAL_SOUND ?
Todo:
: handle theses
Definition at line 1878 of file cg_event.c.
Referenced by CG_CheckEvents(), and CG_CheckPlayerstateEvents().
qboolean CG_EntOnFire (centity_t * cent)
CG_EntOnFire.
Parameters
[in] cent
Returns
Definition at line 48 of file cg_players.c.
Referenced by CG_AddRefEntityWithPowerups(), CG_EntityEffects(), CG_LaunchGib(), CG_LoseHat(), and CG_TransitionEntity().
void QDECL void QDECL void QDECL CG_Error (const char * msg, ...)
Referenced by CG_AddFragment(), CG_AddLocalEntities(), CG_AddSpawnVarToken(), CG_CalcMoveSpeeds(), CG_CheckForExistingAnimModelInfo(), CG_ConfigStringModified(), CG_corona(), CG_EntityEvent(), CG_FireWeapon(), CG_FreeLocalEntity(), CG_FreeMarkPoly(), CG_GibPlayer(), CG_Item(), CG_LoadLocations(), CG_LoseHat(), CG_MakeExplosion(), CG_MergeFlameChunks(), CG_MustParse(), CG_Obituary(), CG_ParseEntitiesFromString(), CG_ParseSpawnVars(), CG_ParseTagConnect(), CG_ParticleExplosion(), CG_Player(), CG_ProcessEntity(), CG_ProcessSnapshots(), CG_RegisterPlayerClasses(), CG_RW_ParseClient(), CG_SetHudHeadLerpFrameAnimation(), CG_SetLerpFrameAnimation(), CG_SetLerpFrameAnimationRate(), CG_SetLerpFrameAnimationRateCorpse(), CG_SetWeapLerpFrameAnimation(), CG_SoundLoadSoundFiles(), CG_SoundParseSounds(), CG_SoundPickOldestRandomSound(), CG_SpawnString(), CG_TransitionSnapshot(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_path_corner_2(), and SP_worldspawn().
void CG_EventHandling (int type, qboolean fForced)
CG_EventHandling.
Parameters
[in] type
[in] fForced
Definition at line 746 of file cg_newDraw.c.
Referenced by CG_ClassMenu_f(), CG_DeActivateEditSoundMode(), CG_FireteamCheckExecKey(), CG_KeyEvent(), CG_keyOff_f(), CG_keyOn_f(), CG_LimboMenu_f(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_KeyHandling(), CG_LimboPanel_SendSetupMsg(), CG_ModifyEditSpeaker(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickFireteams_f(), CG_QuickMessage_f(), CG_QuickSpawnpoint_f(), CG_Shutdown(), CG_SpawnpointsCheckExecKey(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditor_Ok_KeyUp(), CG_TeamMenu_f(), and vmMain().
qboolean CG_execFile (const char * filename)
Try to exec a cfg file if it is found.
Parameters
[in] filename
Returns
Definition at line 753 of file cg_main.c.
Referenced by CG_Init(), and CG_Respawn().
void CG_ExecuteNewServerCommands (int latestSequence)
Execute all of the server commands that were received along with this this snapshot.
Parameters
[in] latestSequence
Definition at line 3302 of file cg_servercmds.c.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionSnapshot().
void CG_Fade (int r, int g, int b, int a, int time, int duration)
CG_Fade.
Parameters
r - unused
g - unused
b - unused
[in] a
[in] time
[in] duration
Todo:
cleanup ?
Todo:
: early return?
Definition at line 3373 of file cg_draw.c.
Referenced by CG_Fade_f().
float* CG_FadeColor (int startMsec, int totalMsec)
CG_FadeColor.
Parameters
[in] startMsec
[in] totalMsec
Returns
Definition at line 529 of file cg_drawtools.c.
Referenced by CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), and CG_DrawScoreboard().
void CG_FilledBar (float x, float y, float w, float h, float * startColor, float * endColor, const float * bgColor, float frac, int flags)
CG_FilledBar.
Parameters
[in] x
[in] y
[in] w
[in] h
[in,out] startColor
[in,out] endColor
[in,out] bgColor
[in] frac
[in] flags
Todo:
: remember to swap colors on the ends here
Todo:
: remember to swap colors on the ends here
Definition at line 146 of file cg_drawtools.c.
Referenced by CG_DemoControlButtonRender(), CG_DrawBreathBar(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawPlayerHealthBar(), CG_DrawStaminaBar(), CG_DrawWeapHeat(), CG_DrawWeapRecharge(), CG_DrawWeapStability(), and CG_HorizontalPercentBar().
void CG_FillRect (float x, float y, float width, float height, const float * color)
CG_FillRect.
Parameters
[in] x
[in] y
[in] width
[in] height
[in,out] color
Note
Coordinates are 640*480 virtual values
Definition at line 101 of file cg_drawtools.c.
Referenced by CG_Debriefing_Maps_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_Scrollbar_Draw(), CG_DebriefingPlayerList_Draw(), CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawBinocReticle(), CG_DrawBorder(), CG_DrawDemoControls(), CG_DrawFireTeamOverlay(), CG_DrawFlashDamage(), CG_DrawFlashFade(), CG_DrawFlashZoomTransition(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawMortarReticle(), CG_DrawPing(), CG_DrawScopedReticle(), CG_DrawSkillBar(), CG_DrawSnapshot(), CG_DrawSpeed(), CG_DrawStatsDebug(), CG_DrawTimerNormal(), CG_FilledBar(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_LimboPanel_RenderHead(), CG_LoadHudMenu(), CG_MapVoteList_Draw(), CG_ObjectivesDraw(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_ScreenFade(), CG_SpeakerEditor_Back(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerEditor_RenderEdit(), CG_SpeakerInfo_Text(), CG_TopShotsDraw(), CG_windowDraw(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
qboolean CG_FindArenaInfo (const char * filename, const char * mapname, arenaInfo_t * info)
CG_FindArenaInfo.
Parameters
[in] filename
[in] mapname
[in] info
Returns
Definition at line 233 of file cg_missionbriefing.c.
Referenced by CG_LocateArena(), CG_LocateCampaign(), and CG_parseMapVoteListInfo().
int CG_findClientNum (const char * s)
CG_findClientNum.
Parameters
[in] s
Returns
Definition at line 1027 of file cg_main.c.
localEntity_t* CG_FindLocalEntity (int index, int sideNum)
CG_FindLocalEntity.
Will allways succeed, even if it requires freeing an old active entity
Parameters
[in] index
[in] sideNum
Returns
Definition at line 405 of file cg_localents.c.
Referenced by CG_RailTrail2().
void CG_FinishWeaponChange (int lastWeapon, int newWeapon)
CG_FinishWeaponChange.
Parameters
[in] lastweap
[in] newweap
Definition at line 3646 of file cg_weapons.c.
Referenced by CG_AltWeapon_f(), CG_EntityEvent(), CG_LastWeaponUsed_f(), CG_NextWeap(), CG_OutOfAmmoChange(), CG_PrevWeap(), CG_Respawn(), CG_TransitionPlayerState(), and CG_WeaponBank_f().
void CG_FireFlameChunks (centity_t * cent, vec3_t origin, vec3_t angles, float speedScale, qboolean firing)
The given entity is firing a flamethrower.
Parameters
[in] cent
[in] origin
[in] angles
[in] speedScale
[in] firing
Definition at line 166 of file cg_flamethrower.c.
Referenced by CG_AddPlayerWeapon(), CG_EntityEvent(), and CG_FlamethrowerFlame().
qboolean CG_FireteamCheckExecKey (int key, qboolean doaction)
CG_FireteamCheckExecKey.
Parameters
[in] key
[in] doaction
Returns
Definition at line 1086 of file cg_fireteams.c.
Referenced by CG_CheckExecKey(), and CG_Fireteams_KeyHandling().
fireteamData_t* CG_FireTeamForPosition (int pos, int max)
Fireteam, that's on your same team.
Parameters
[in] pos
[in] max
Returns
Note
Unused
Definition at line 279 of file cg_fireteamoverlay.c.
qboolean CG_FireteamHasClass (int classnum, qboolean selectedonly)
CG_FireteamHasClass.
Parameters
[in] classnum
[in] selectedonly
Returns
Definition at line 783 of file cg_fireteamoverlay.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
clientInfo_t* CG_FireTeamPlayerForPosition (int pos, int max)
Client, not sorted by rank, on CLIENT'S fireteam.
Parameters
[in] pos
[in] max
Returns
Note
Unused
Definition at line 306 of file cg_fireteamoverlay.c.
void CG_Fireteams_Draw (void)
CG_Fireteams_Draw.
Definition at line 1070 of file cg_fireteams.c.
Referenced by CG_Draw2D().
void CG_Fireteams_KeyHandling (int key, qboolean down)
CG_Fireteams_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 1059 of file cg_fireteams.c.
Referenced by CG_KeyEvent().
void CG_Fireteams_MenuText_Draw (panel_button_t * button)
CG_Fireteams_MenuText_Draw.
Parameters
[in] button
Definition at line 838 of file cg_fireteams.c.
void CG_Fireteams_MenuTitleText_Draw (panel_button_t * button)
Definition at line 341 of file cg_fireteams.c.
void CG_Fireteams_Setup (void)
CG_Fireteams_Setup.
Definition at line 1049 of file cg_fireteams.c.
Referenced by CG_RegisterGraphics().
void CG_FireWeapon (centity_t * cent)
Caused by an EV_FIRE_WEAPON event.
Parameters
[in,out] cent
Todo:
: use numbers that are weapon specific
Definition at line 4817 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_FitTextToWidth2 (char * instr, float scale, float w, int size)
CG_FitTextToWidth2.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
Note
Unused
Definition at line 144 of file cg_newDraw.c.
void CG_FitTextToWidth_Ext (char * instr, float scale, float w, int size, fontHelper_t * font)
CG_FitTextToWidth_Ext.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
[in] font
Definition at line 83 of file cg_newDraw.c.
Referenced by CG_LimboPanel_RenderObjectiveText(), and CG_ObjectivesDraw().
void CG_FitTextToWidth_SingleLine (char * instr, float scale, float w, int size)
CG_FitTextToWidth_SingleLine.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
Note
Unused
Definition at line 205 of file cg_newDraw.c.
void CG_ForceTapOut_f (void)
CG_ForceTapOut_f.
Definition at line 1147 of file cg_consolecmds.c.
Referenced by CG_ServerCommand().
char* CG_generateFilename (void)
Generate standard naming for screenshots/demos.
Returns
Definition at line 968 of file cg_main.c.
Referenced by CG_autoRecord_f(), and CG_autoScreenShot_f().
hudStucture_t* CG_GetActiveHUD ()
CG_getActiveHUD Returns reference to an active hud structure.
Returns
Definition at line 99 of file cg_draw_hud.c.
Referenced by CG_TransformAutomapEntity().
void CG_GetBleedOrigin (vec3_t head_origin, vec3_t body_origin, int fleshEntityNum)
CG_GetBleedOrigin.
Parameters
[in] head_origin
[in] body_origin
[in] fleshEntityNum
Definition at line 3076 of file cg_players.c.
Referenced by CG_Bleed().
void CG_GetColorForHealth (int health, vec4_t hcolor)
CG_GetColorForHealth.
Parameters
[in] health
[in] hcolor
Note
Unused
Definition at line 594 of file cg_drawtools.c.
sfxHandle_t CG_GetGameSound (int index)
CG_GetGameSound.
Parameters
[in] index
Returns
Definition at line 1470 of file cg_main.c.
Referenced by CG_AddLightstyle(), CG_EntityEffects(), CG_EntityEvent(), CG_GetSoundFx(), CG_PlayGlobalSound(), and CG_Speaker().
char* CG_GetLocationMsg (int clientNum, vec3_t origin)
CG_GetLocationMsg.
Parameters
[in] clientNum
[in] origin
Returns
Definition at line 110 of file cg_localents.c.
Referenced by CG_BuildLocationString().
int CG_GetOriginForTag (centity_t * cent, refEntity_t * parent, const char * tagName, int startIndex, vec3_t org, vec3_t axis[3])
Places the position of the tag into "org".
Parameters
cent - unused
[in] parent
[in] tagName
[in] startIndex
[in,out] org
[in] axis
Returns
The index of the tag it used, so we can cycle through tag's with the same name
Definition at line 541 of file cg_effects.c.
Referenced by CG_BreathPuffs(), CG_Bullet(), CG_GibPlayer(), CG_LoseHat(), and CG_PlayerShadow().
qhandle_t CG_GetPMItemIcon (centity_t * cent)
CG_GetPMItemIcon.
Parameters
[in] cent
Returns
Definition at line 997 of file cg_popupmessages.c.
Referenced by CG_EntityEvent().
const char* CG_GetPMItemText (centity_t * cent)
CG_GetPMItemText.
Parameters
[in] cent
Returns
Definition at line 806 of file cg_popupmessages.c.
Referenced by CG_EntityEvent().
sfxHandle_t CG_GetRandomSoundSurface (weaponSounds_t * weaponSounds, soundSurface_t surf, qboolean forceDefault)
CG_GetRandomSoundSurface.
Parameters
[in] weapon
[in] surf
Returns
Definition at line 5335 of file cg_weapons.c.
Referenced by CG_EntityEvent(), and CG_MissileHitWall().
soundSurface_t CG_GetSoundSurfaceIndex (int surfFlags)
CG_GetSoundSurfaceIndex.
Parameters
[in] surfFlags
Returns
Definition at line 5314 of file cg_weapons.c.
Referenced by CG_EntityEvent(), and CG_MissileHitWall().
qboolean CG_GetTag (int clientNum, const char * tagname, orientation_t * orientation)
CG_GetTag.
Parameters
[in] clientNum
[in] tagname
[in,out] orientation
Returns
Definition at line 3132 of file cg_players.c.
Referenced by vmMain().
void CG_GetTeamColor (vec4_t * color)
CG_GetTeamColor.
Parameters
[out] color
Definition at line 962 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
float CG_GetValue (int ownerDraw, int type)
CG_GetValue.
Parameters
ownerDraw - unused
type - unused
Todo:
FIXME: what's this ??
Returns
Definition at line 521 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
qboolean CG_GetWeaponTag (int clientNum, const char * tagname, orientation_t * orientation)
CG_GetWeaponTag.
Parameters
[in] clientNum
[in] tagname
[in,out] orientation
Returns
Definition at line 3184 of file cg_players.c.
Referenced by CG_SpawnTracer().
void CG_GibPlayer (centity_t * cent, vec3_t playerOrigin, vec3_t gdir)
Generated a bunch of gibs launching out from the bodies location.
Parameters
[in,out] cent
[in] playerOrigin
[in] gdir
Definition at line 579 of file cg_effects.c.
Referenced by CG_EntityEvent().
void CG_HorizontalPercentBar (float x, float y, float width, float height, float percent)
Generic routine for pretty much all status indicators that show a fractional value to the player by virtue of how full a drawn box is.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] percent
Note
Unused
Definition at line 264 of file cg_drawtools.c.
void CG_Hud_Setup (void)
CG_Hud_Setup.
Definition at line 2939 of file cg_draw_hud.c.
Referenced by CG_RegisterGraphics().
void CG_HudHeadAnimation (bg_character_t * ch, lerpFrame_t * lf, int * oldframe, int * frame, float * backlerp, hudHeadAnimNumber_t animation)
CG_HudHeadAnimation.
Parameters
[in] ch
[in] lf
[out] oldframe
[out] frame
[out] backlerp
[in] animation
Definition at line 3372 of file cg_players.c.
Referenced by CG_DrawPlayerHead(), and CG_Player().
void CG_ImpactMark (qhandle_t markShader, vec3_t origin, vec4_t projection, float radius, float orientation, float r, float g, float b, float a, int lifeTime)
CG_ImpactMark.
Parameters
[in] markShader
[in] origin
[in] projection
[in] radius
[in] orientation
[in] r
[in] g
[in] b
[in] a
[in] lifeTime
Note
TODO: projection is a normal and distance (not a plane, but rather how far to project) it MUST be normalized! if lifeTime < 0, then generate a temporary mark
Definition at line 104 of file cg_marks.c.
Referenced by CG_Bullet(), CG_FragmentBounceMark(), CG_GibPlayer(), CG_MissileHitWall(), and CG_PlayerShadow().
void CG_InitConsoleCommands (void)
Let the client system know about all of our commands so it can perform tab completion.
Definition at line 2051 of file cg_consolecmds.c.
Referenced by CG_Init().
void CG_InitFlameChunks (void)
CG_InitFlameChunks.
Definition at line 1160 of file cg_flamethrower.c.
Referenced by CG_Init().
void CG_InitLocalEntities (void)
This is called at startup and for tournement restarts.
Definition at line 357 of file cg_localents.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_InitMarkPolys (void)
This is called at startup and for tournement restarts.
Definition at line 51 of file cg_marks.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_InitPM (void)
CG_InitPM.
Definition at line 127 of file cg_popupmessages.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_InitPMGraphics (void)
CG_InitPMGraphics.
Definition at line 93 of file cg_popupmessages.c.
Referenced by CG_RegisterGraphics().
void CG_InitStatsDebug (void)
CG_InitStatsDebug.
Definition at line 1555 of file cg_draw_hud.c.
Referenced by CG_Init().
void CG_initStrings (void)
String buffer handling.
Definition at line 625 of file cg_window.c.
Referenced by CG_Init().
fireteamData_t* CG_IsFireTeamLeader (int clientNum)
Fireteam that specified client is leader of, or NULL if none.
Parameters
[in] clientNum
Returns
Definition at line 227 of file cg_fireteamoverlay.c.
Referenced by CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), and CG_SortFireTeam().
fireteamData_t* CG_IsOnFireteam (int clientNum)
Fireteam that the specified client is a part of.
Parameters
[in] clientNum
Returns
Definition at line 197 of file cg_fireteamoverlay.c.
Referenced by CG_ClientInfoForPosition(), CG_CountPlayersNF(), CG_CountPlayersSF(), CG_Debriefing_ChatButton_KeyDown(), CG_DrawFireTeamOverlay(), CG_DrawUpperRight(), CG_FireteamCheckExecKey(), CG_FireteamHasClass(), CG_FireTeamPlayerForPosition(), CG_Fireteams_MenuText_Draw(), CG_IsFireTeamLeader(), CG_IsOnSameFireteam(), CG_MessageMode_f(), CG_PlayerNFFromPos(), CG_PlayerSFFromPos(), CG_PlayerSprites(), CG_QuickFireteams_f(), CG_SelectBuddy_f(), and CG_SortedFireTeamPlayerForPosition().
fireteamData_t* CG_IsOnSameFireteam (int clientNum, int clientNum2)
Fireteam that both specified clients are on, if they both are on the same team.
Parameters
[in] clientNum
[in] clientNum2
Returns
Definition at line 212 of file cg_fireteamoverlay.c.
Referenced by CG_DrawMapEntity(), CG_DrawNewCompass(), and CG_SortFireTeam().
void CG_KeyEvent (int key, qboolean down)
Definition at line 883 of file cg_newDraw.c.
Referenced by vmMain().
void CG_keyOff_f (void)
CG_keyOff_f.
Definition at line 900 of file cg_consolecmds.c.
Referenced by CG_DemoClick().
void CG_keyOn_f (void)
CG_keyOn_f.
Definition at line 881 of file cg_consolecmds.c.
Referenced by CG_SetInitialSnapshot().
int CG_LastAttacker (void)
CG_LastAttacker.
Returns
Definition at line 815 of file cg_main.c.
Referenced by vmMain().
void CG_LastWeaponUsed_f (void)
CG_LastWeaponUsed_f.
Definition at line 4389 of file cg_weapons.c.
void CG_Letterbox (float xsize, float ysize, qboolean center)
Sets the coordinates of the rendered window.
Parameters
[in] xsize
[in] ysize
[in] center
Definition at line 209 of file cg_view.c.
Referenced by CG_CalcVrect().
void CG_LimboMenu_f (void)
CG_LimboMenu_f.
Definition at line 52 of file cg_consolecmds.c.
Referenced by CG_SetInitialSnapshot().
void CG_LimboPanel_Border_Draw (panel_button_t * button)
CG_LimboPanel_Border_Draw.
Parameters
[in] button
Definition at line 2517 of file cg_limbopanel.c.
void CG_LimboPanel_BriefingButton_Draw (panel_button_t * button)
CG_LimboPanel_BriefingButton_Draw.
Parameters
[in] button
Definition at line 1202 of file cg_limbopanel.c.
qboolean CG_LimboPanel_BriefingButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_BriefingButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1155 of file cg_limbopanel.c.
qboolean CG_LimboPanel_CancelButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_CancelButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1239 of file cg_limbopanel.c.
void CG_LimboPanel_ClassBar_Draw (panel_button_t * button)
CG_LimboPanel_ClassBar_Draw.
Parameters
[in] button
Definition at line 1585 of file cg_limbopanel.c.
qboolean CG_LimboPanel_ClassButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_ClassButton_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1546 of file cg_limbopanel.c.
int CG_LimboPanel_ClassCount (team_t checkTeam, int classIndex)
CG_LimboPanel_ClassCount.
Parameters
[in] checkTeam
[in] classIndex
Returns
Definition at line 3856 of file cg_limbopanel.c.
Referenced by CG_IsClassFull(), and CG_LimboPanel_ClassIsDisabled().
qboolean CG_LimboPanel_ClassIsDisabled (team_t selectedTeam, int classIndex)
CG_LimboPanel_ClassIsDisabled.
Parameters
[in] selectedTeam
[in] classIndex
Returns
Definition at line 3894 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_FindFreeClass(), CG_LimboPanel_RenderClassButton(), and CG_LimboPanel_TeamButton_KeyDown().
qboolean CG_LimboPanel_Draw (void)
CG_LimboPanel_Draw.
Returns
Definition at line 3263 of file cg_limbopanel.c.
Referenced by CG_DrawActive().
void CG_LimboPanel_Filter_Draw (panel_button_t * button)
CG_LimboPanel_Filter_Draw.
Parameters
[in] button
Definition at line 2237 of file cg_limbopanel.c.
qboolean CG_LimboPanel_Filter_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_Filter_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2220 of file cg_limbopanel.c.
int CG_LimboPanel_FindFreeClass (team_t checkTeam)
CG_LimboPanel_FindFreeClass.
Parameters
[in] checkTeam
Returns
Definition at line 4006 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_TeamButton_KeyDown(), and CG_LimboPanel_TeamIsDisabled().
bg_character_t* CG_LimboPanel_GetCharacter (void)
CG_LimboPanel_GetCharacter.
Returns
Definition at line 3386 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderHead().
int CG_LimboPanel_GetClass (void)
CG_LimboPanel_GetClass.
Returns
Definition at line 3377 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_GetCharacter(), CG_LimboPanel_GetPlayerClass(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderLight_GetValue(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanel_SendSetupMsg(), and CG_LimboPanel_TeamButton_KeyDown().
int CG_LimboPanel_GetMaxObjectives (void)
CG_LimboPanel_GetMaxObjectives.
Returns
Definition at line 1770 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Draw(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_Setup(), and CG_LimboPanel_TeamButton_KeyDown().
bg_playerclass_t* CG_LimboPanel_GetPlayerClass (void)
CG_LimboPanel_GetPlayerClass.
Returns
Definition at line 3395 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassIsDisabled(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_WeaponCount(), and CG_LimboPanel_WeaponPanel().
team_t CG_LimboPanel_GetRealTeam (void)
CG_LimboPanel_GetRealTeam.
Returns
Definition at line 3368 of file cg_limbopanel.c.
Referenced by CG_CommandCentreSpawnPointClick(), CG_DrawMap(), CG_DrawSpawnPointInfo(), CG_LimboPanel_ClassIsDisabled(), and CG_LimboPanel_RenderCounter_ValueForButton().
weapon_t CG_LimboPanel_GetSelectedWeapon (int slot)
CG_LimboPanel_GetSelectedWeapon.
Returns
Definition at line 3577 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_RequestWeaponStats(), and CG_LimboPanel_WeaponPanel().
int CG_LimboPanel_GetSpawnPoint (void)
CG_LimboPanel_GetSpawnPoint.
Returns
Definition at line 3350 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_SpawnPointButton_Draw().
team_t CG_LimboPanel_GetTeam (void)
CG_LimboPanel_GetTeam.
Returns
Definition at line 3359 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_Draw(), CG_LimboPanel_GetCharacter(), CG_LimboPanel_GetMaxObjectives(), CG_LimboPanel_GetPlayerClass(), CG_LimboPanel_GetRealTeam(), CG_LimboPanel_RealWeaponIsDisabled(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderLight_GetValue(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_TeamCount(), CG_LimboPanel_WeaponLights(), CG_LimboPanel_WeaponLights_KeyDown(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_KeyDown(), and CG_LimboPanel_WeaponPanel_KeyUp().
weapon_t CG_LimboPanel_GetWeaponForNumber (int number, int slot, qboolean ignoreDisabled)
int CG_LimboPanel_GetWeaponNumberForPos (int pos)
void CG_LimboPanel_Init (void)
CG_LimboPanel_Init.
Definition at line 3253 of file cg_limbopanel.c.
Referenced by CG_RegisterGraphics().
qboolean CG_LimboPanel_IsValidSelectedWeapon (int slot)
CG_LimboPanel_IsValidSelectedWeapon.
Parameters
[in] slot
Returns
Definition at line 3461 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_KeyHandling (int key, qboolean down)
CG_LimboPanel_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 3316 of file cg_limbopanel.c.
Referenced by CG_KeyEvent().
int CG_LimboPanel_MaxCount (int playerCount, const char * variableString)
CG_LimboPanel_MaxCount.
Parameters
[in] playerCount
[in] variableString
Returns
Definition at line 3753 of file cg_limbopanel.c.
Referenced by CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_ClassIsDisabled(), and CG_LimboPanel_RealWeaponIsDisabled().
qboolean CG_LimboPanel_MinusButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_MinusButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1291 of file cg_limbopanel.c.
void CG_LimboPanel_NameEditFinish (panel_button_t * button)
CG_LimboPanel_NameEditFinish.
Parameters
button
Definition at line 1223 of file cg_limbopanel.c.
qboolean CG_LimboPanel_ObjectiveText_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_ObjectiveText_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1786 of file cg_limbopanel.c.
qboolean CG_LimboPanel_OkButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_OkButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1412 of file cg_limbopanel.c.
qboolean CG_LimboPanel_PlusButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_PlusButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1266 of file cg_limbopanel.c.
qboolean CG_LimboPanel_RealWeaponIsDisabled (weapon_t weapon)
Checks for heavy and rifle weapons.
Parameters
[in] weapon
Returns
Note
FIXME: this function needs some rework: count picked up opposite team weapons too see G_IsWeaponDisabled check: CG_LimboPanel_RealWeaponIsDisabled probably doesn't have to check for alt weapons they can't be selected
Definition at line 3783 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_SetSelectedWeaponNum(), CG_LimboPanel_Setup(), and CG_LimboPanel_WeaponPanel().
void CG_LimboPanel_RenderClassButton (panel_button_t * button)
CG_LimboPanel_RenderClassButton.
Parameters
[in] button
Definition at line 1665 of file cg_limbopanel.c.
void CG_LimboPanel_RenderCommandMap (panel_button_t * button)
CG_LimboPanel_RenderCommandMap.
Parameters
[in] button
Definition at line 1950 of file cg_limbopanel.c.
void CG_LimboPanel_RenderCounter (panel_button_t * button)
CG_LimboPanel_RenderCounter.
Parameters
[in] button
Note
This function is mental, i love it :)
Definition at line 3036 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup().
void CG_LimboPanel_RenderHead (panel_button_t * button)
CG_LimboPanel_RenderHead.
Parameters
[in] button
Todo:
:
Definition at line 2171 of file cg_limbopanel.c.
void CG_LimboPanel_RenderLight (panel_button_t * button)
CG_LimboPanel_RenderLight.
Parameters
[in] button
Todo:
Need cleanup
Definition at line 1981 of file cg_limbopanel.c.
void CG_LimboPanel_RenderMedal (panel_button_t * button)
CG_LimboPanel_RenderMedal.
Parameters
[in] button
Definition at line 2950 of file cg_limbopanel.c.
void CG_LimboPanel_RenderObjectiveBack (panel_button_t * button)
CG_LimboPanel_RenderObjectiveBack.
Parameters
[in] button
Definition at line 1941 of file cg_limbopanel.c.
void CG_LimboPanel_RenderObjectiveText (panel_button_t * button)
Definition at line 1817 of file cg_limbopanel.c.
void CG_LimboPanel_RenderSkillIcon (panel_button_t * button)
CG_LimboPanel_RenderSkillIcon.
Parameters
[in] button
Definition at line 2255 of file cg_limbopanel.c.
void CG_LimboPanel_RenderTeamButton (panel_button_t * button)
CG_LimboPanel_RenderTeamButton.
Parameters
[in] button
Todo:
: There is no lock status transfer yet.
Definition at line 1475 of file cg_limbopanel.c.
void CG_LimboPanel_RequestObjective (void)
CG_LimboPanel_RequestObjective.
Definition at line 3615 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Draw(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_Setup(), and CG_MapRestart().
void CG_LimboPanel_RequestWeaponStats (void)
CG_LimboPanel_RequestWeaponStats.
Todo:
: Bleh?
Definition at line 3595 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponLights_KeyDown(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_SetDefaultWeapon (int slot)
CG_LimboPanel_SetSelectedDefaultWeapon.
Parameters
[in] slot
Definition at line 3524 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_WeaponPanel_KeyUp(), and CG_NewClientInfo().
void CG_LimboPanel_SetSelectedWeaponNum (int slot, weapon_t weapon)
CG_LimboPanel_SetSelectedWeaponNum.
Parameters
[in] number
Definition at line 3637 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_Setup(), and CG_LimboPanel_WeaponPanel_KeyUp().
void CG_LimboPanel_Setup (void)
CG_LimboPanel_Setup.
Definition at line 3179 of file cg_limbopanel.c.
Referenced by CG_EventHandling(), and CG_NewClientInfo().
void CG_LimboPanel_SpawnPointButton_Draw (panel_button_t * button)
CG_LimboPanel_SpawnPointButton_Draw.
Parameters
[in] button
Definition at line 1186 of file cg_limbopanel.c.
qboolean CG_LimboPanel_SpawnPointButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_SpawnPointButton_KeyDown.
Parameters
button - unused
[in] key
Returns
Definition at line 1134 of file cg_limbopanel.c.
qboolean CG_LimboPanel_TeamButton_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_TeamButton_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 1432 of file cg_limbopanel.c.
int CG_LimboPanel_TeamCount (int weap)
CG_LimboPanel_TeamCount.
Parameters
[in] weap weapon_t or -1
Returns
Definition at line 3657 of file cg_limbopanel.c.
Referenced by CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_ClassIsDisabled(), and CG_LimboPanel_RealWeaponIsDisabled().
qboolean CG_LimboPanel_TeamIsDisabled (team_t checkTeam)
CG_LimboPanel_TeamIsDisabled.
Parameters
[in] checkTeam
Returns
Definition at line 3976 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_RenderTeamButton(), and CG_LimboPanel_TeamButton_KeyDown().
int CG_LimboPanel_WeaponCount (int slotNumber)
CG_LimboPanel_WeaponCount.
Parameters
[in] slotNumber primary or secondary slot weapon
Returns
Definition at line 3405 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_WeaponPanel().
void CG_LimboPanel_WeaponLights (panel_button_t * button)
CG_LimboPanel_WeaponLights.
Parameters
[in] button
Definition at line 2311 of file cg_limbopanel.c.
qboolean CG_LimboPanel_WeaponLights_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_WeaponLights_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2288 of file cg_limbopanel.c.
void CG_LimboPanel_WeaponPanel (panel_button_t * button)
CG_LimboPanel_WeaponPanel.
Parameters
[in] button
Definition at line 2529 of file cg_limbopanel.c.
qboolean CG_LimboPanel_WeaponPanel_KeyDown (panel_button_t * button, int key)
CG_LimboPanel_WeaponPanel_KeyDown.
Parameters
[in] button
[in] key
Returns
Definition at line 2329 of file cg_limbopanel.c.
qboolean CG_LimboPanel_WeaponPanel_KeyUp (panel_button_t * button, int key)
CG_LimboPanel_WeaponPanel_KeyUp.
Parameters
[in] button
[in] key
Returns
Definition at line 2355 of file cg_limbopanel.c.
void CG_LimboPanelRenderText_NoLMS (panel_button_t * button)
CG_LimboPanelRenderText_NoLMS.
Parameters
[in] button
Definition at line 3005 of file cg_limbopanel.c.
void CG_LimboPanelRenderText_SkillsText (panel_button_t * button)
CG_LimboPanelRenderText_SkillsText.
Parameters
[in] button
Definition at line 3019 of file cg_limbopanel.c.
void CG_LoadingString (const char * s)
CG_LoadingString.
Parameters
[in] s
Definition at line 68 of file cg_info.c.
Referenced by CG_Init(), and CG_RegisterGraphics().
void CG_LoadLocations (void)
Report a location for the player. Uses placed nearby target_location entities.
Definition at line 186 of file cg_localents.c.
Referenced by CG_Init().
void CG_LoadObjectiveData (void)
CG_LoadObjectiveData.
Definition at line 1085 of file cg_main.c.
Referenced by CG_MapRestart(), and CG_RegisterGraphics().
void CG_LoadPanel_DrawPin (const char * text, float px, float py, float sx, float sy, qhandle_t shader, float pinsize, float backheight)
CG_LoadPanel_DrawPin.
Parameters
[in] text
[in] px
[in] py
[in] sx
[in] sy
[in] shader
[in] pinsize
[in] backheight
Definition at line 672 of file cg_loadpanel.c.
Referenced by CG_LoadPanel_RenderCampaignPins().
void CG_LoadPanel_KeyHandling (int key, qboolean down)
CG_LoadPanel_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 653 of file cg_loadpanel.c.
Referenced by CG_KeyEvent().
void CG_LoadPanel_LoadingBarText (panel_button_t * button)
Draws infoScreenText in loading bar.
Parameters
[in] button
Definition at line 772 of file cg_loadpanel.c.
void CG_LoadPanel_RenderCampaignNameText (panel_button_t * button)
CG_LoadPanel_RenderCampaignNameText.
Parameters
[in] button
Todo:
: up to 128 chars !
Definition at line 546 of file cg_loadpanel.c.
void CG_LoadPanel_RenderCampaignPins (panel_button_t * button)
CG_LoadPanel_RenderCampaignPins.
Parameters
button - unused
Definition at line 715 of file cg_loadpanel.c.
void CG_LoadPanel_RenderCampaignTypeText (panel_button_t * button)
CG_LoadPanel_RenderCampaignTypeText.
Parameters
[in] button
Definition at line 501 of file cg_loadpanel.c.
void CG_LoadPanel_RenderLoadingBar (panel_button_t * button)
CG_LoadPanel_RenderLoadingBar.
Parameters
[in] button
Definition at line 472 of file cg_loadpanel.c.
void CG_LoadPanel_RenderMissionDescriptionText (panel_button_t * button)
CG_LoadPanel_RenderMissionDescriptionText.
Parameters
[in] button
Definition at line 586 of file cg_loadpanel.c.
void CG_LoadRankIcons (void)
CG_LoadRankIcons.
Definition at line 154 of file cg_statsranksmedals.c.
Referenced by CG_RegisterGraphics().
void CG_LoadVoiceChats (void)
CG_LoadVoiceChats.
Definition at line 1587 of file cg_servercmds.c.
Referenced by CG_RegisterSounds().
const char* CG_LocalizeServerCommand (const char * buf)
Localize string sent from server.
localization is ON by default.
use [lof] in string to turn OFF
use [lon] in string to turn back ON
Parameters
buf
Returns
Definition at line 1877 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_LocateArena (void)
CG_LocateArena.
Definition at line 469 of file cg_missionbriefing.c.
Referenced by CG_Init(), and CG_parseMapVoteListInfo().
void CG_LocateCampaign (void)
CG_LocateCampaign.
Definition at line 423 of file cg_missionbriefing.c.
Referenced by CG_Init().
void CG_LoseHat (centity_t * cent, vec3_t dir)
CG_LoseHat.
Parameters
[in] cent
[in] dir
Todo:
: origin of hat md3 is offset from center. need to center the origin when you toss it
Definition at line 457 of file cg_effects.c.
Referenced by CG_EntityEvent(), and CG_GibPlayer().
localEntity_t* CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
CG_MakeExplosion.
Parameters
[in] origin
[in] dir
[in] hModel
[in] shader
[in] msec
[in] isSprite
Returns
Definition at line 187 of file cg_effects.c.
Referenced by CG_BigExplosionImpact(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_MapMortarImpact(), and CG_SmallExplosionImpact().
void CG_MG42EFX (centity_t * cent)
CG_MG42EFX.
Parameters
[in] cent
Definition at line 4706 of file cg_weapons.c.
Referenced by CG_AddPlayerWeapon().
void CG_MissileHitPlayer (int entityNum, int weapon, vec3_t origin, vec3_t dir, int fleshEntityNum)
CG_MissileHitPlayer.
Parameters
[in] entityNum
[in] weapon
[in] origin
[in] dir
[in] fleshEntityNum
Definition at line 5881 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_MissileHitWall (int weapon, int missileEffect, vec3_t origin, vec3_t dir, int surfFlags, int sourceEnt)
Caused by an EV_MISSILE_MISS event, or directly by local bullet tracing.
Parameters
[in] weapon
[in] missileEffect used to define what sort of effect to spawn
[in] origin
[in] dir
[in] surfFlags
[in] sourceEnt
Note
modified to send missilehitwall surface parameters
Definition at line 5744 of file cg_weapons.c.
Referenced by CG_Bullet(), CG_Effect(), CG_EntityEvent(), and CG_MissileHitPlayer().
void CG_MissileHitWallSmall (vec3_t origin, vec3_t dir)
CG_MissileHitWallSmall.
Parameters
[in] origin
[in] dir
Definition at line 5847 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_MissionBriefingClick (int key)
void CG_ModifyEditSpeaker (void)
CG_ModifyEditSpeaker.
Definition at line 2419 of file cg_sound.c.
Referenced by CG_ModifySpeaker_f(), and CG_SpeakerEditor_KeyHandling().
void CG_MortarEFX (centity_t * cent)
Right now mostly copied directly from Raf's MG42 FX, but with the optional addtion of smoke.
Parameters
[in] cent
Definition at line 4748 of file cg_weapons.c.
Referenced by CG_EntityEvent().
void CG_MouseEvent (int x, int y)
CG_MouseEvent.
Parameters
[in] x
[in] y
Definition at line 613 of file cg_newDraw.c.
Referenced by vmMain().
const char* CG_NameForCampaign (void)
CG_NameForCampaign.
Returns
Definition at line 50 of file cg_missionbriefing.c.
Referenced by CG_LoadHudMenu().
void CG_NewClientInfo (int clientNum)
CG_NewClientInfo.
Parameters
[in] clientNum
Todo:
: make these more secure)
Definition at line 174 of file cg_players.c.
Referenced by CG_ConfigStringModified(), and CG_RegisterClients().
int CG_NewParticleArea (int num)
CG_NewParticleArea.
Parameters
[in] num
Returns
Note
Unused
Definition at line 1559 of file cg_particles.c.
void CG_NextWeapon_f (void)
CG_NextWeapon_f.
Definition at line 4451 of file cg_weapons.c.
void CG_NextWeaponInBank_f (void)
CG_NextWeaponInBank_f.
Definition at line 4415 of file cg_weapons.c.
void CG_ObjectivePrint (const char * str, float fontScale)
CG_ObjectivePrint.
Parameters
[in] str
[in] fontScale
Definition at line 3191 of file cg_draw.c.
Referenced by CG_TouchTriggerPrediction().
void CG_OilSlickRemove (centity_t * cent)
CG_OilSlickRemove.
Parameters
[in] cent
Definition at line 1938 of file cg_particles.c.
Referenced by CG_EntityEvent().
void CG_OutOfAmmoChange (qboolean allowForceSwitch)
The current weapon has just run out of ammo, switch to another one.
Parameters
[in] allowForceSwitch - enable on EV_NOAMMO and disable on EV_WEAPONSWITCHED
Definition at line 4600 of file cg_weapons.c.
Referenced by CG_EntityEvent().
qboolean CG_OwnerDrawVisible (int flags)
CG_OwnerDrawVisible.
Parameters
flags - unused
Returns
Note
THINKABOUTME: should these be exclusive or inclusive..
Definition at line 532 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
void CG_PainEvent (centity_t * cent, int health, qboolean crouching)
Also called by playerstate transition.
Parameters
[in] cent
[in] health - unused
[in] crouching - unused
Definition at line 448 of file cg_event.c.
Referenced by CG_CheckLocalSounds(), and CG_EntityEvent().
void CG_PanelButtonsRender_Button (panel_button_t * button)
CG_PanelButtonsRender_Button.
Parameters
[in] button
Definition at line 3263 of file cg_debriefing.c.
Referenced by CG_Debriefing_NextButton_Draw(), CG_Debriefing_ReadyButton_Draw(), and CG_Debriefing_VoteButton_Draw().
void CG_PanelButtonsRender_Button_Ext (rectDef_t * r, const char * text)
CG_PanelButtonsRender_Button_Ext.
Parameters
[in] r
[in] text
Definition at line 3236 of file cg_debriefing.c.
Referenced by CG_Debriefing_ChatButton_Draw(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_VoteButton_Draw(), and CG_PanelButtonsRender_Button().
void CG_PanelButtonsRender_Window (panel_button_t * button)
CG_PanelButtonsRender_Window.
Parameters
[in] button
Definition at line 3315 of file cg_debriefing.c.
void CG_ParseEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
Definition at line 696 of file cg_spawn.c.
Referenced by CG_MapRestart(), and CG_RegisterGraphics().
void CG_ParseFireteams (void)
Parses fireteam servercommand.
Definition at line 132 of file cg_fireteamoverlay.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
void CG_ParseLegacyinfo (void)
CG_ParseLegacyinfo.
Definition at line 302 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseMapEntityInfo (int axis_number, int allied_number)
CG_ParseMapEntityInfo.
Parameters
[in] axis_number
[in] allied_number
Definition at line 280 of file cg_commandmap.c.
Referenced by CG_ServerCommand().
void CG_parseMapVoteListInfo (void)
CG_parseMapVoteListInfo.
Definition at line 4070 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_parseMapVoteTally (void)
CG_parseMapVoteTally.
Definition at line 4114 of file cg_debriefing.c.
Referenced by CG_ServerCommand().
void CG_ParseOIDInfos (void)
CG_ParseOIDInfos.
Definition at line 454 of file cg_servercmds.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_ParseReinforcementTimes (const char * pszReinfSeedString)
Parse reinforcement offsets.
Parameters
[in] pszReinfSeedString
Definition at line 702 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_SetConfigValues().
void CG_ParseServerinfo (void)
This is called explicitly when the gamestate is first received, and whenever the server updates any serverinfo flagged cvars.
Definition at line 167 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseServerVersionInfo (const char * pszVersionInfo)
Parse server version info (for demo playback compatibility)
Parameters
[in] pszVersionInfo
Definition at line 691 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_SetConfigValues().
void CG_ParseSkyBox (void)
CG_ParseSkyBox.
Definition at line 1467 of file cg_view.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseSpawns (void)
CG_ParseSpawns.
Definition at line 506 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), CG_MapRestart(), and SP_worldspawn().
void CG_ParseSysteminfo (void)
Definition at line 270 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseTagConnect (int tagNum)
CG_ParseTagConnect.
Parameters
tagNum
Definition at line 1545 of file cg_view.c.
Referenced by CG_ConfigStringModified(), and CG_ParseTagConnects().
void CG_ParseTagConnects (void)
CG_ParseTagConnects.
Definition at line 1531 of file cg_view.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_ParseTeamXPs (int n)
CG_ParseTeamXPs.
Parameters
[in] n
Definition at line 139 of file cg_players.c.
Referenced by CG_ConfigStringModified().
void CG_parseWeaponStats_cmd (void(txt_dump)(const char *))
Client-side stat presentation.
Definition at line 2218 of file cg_servercmds.c.
Referenced by CG_dumpStats(), CG_ServerCommand(), and CG_wstatsParse_cmd().
void CG_ParseWolfinfo (void)
CG_ParseWolfinfo.
Definition at line 467 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
void CG_Particle_OilParticle (qhandle_t pshader, vec3_t origin, vec3_t dir, int ptime, int snum)
CG_Particle_OilParticle.
Parameters
[in] pshader
[in] origin
[in] dir
[in] ptime
[in] snum
Definition at line 1795 of file cg_particles.c.
Referenced by CG_AddEmitter(), and CG_EntityEvent().
void CG_Particle_OilSlick (qhandle_t pshader, centity_t * cent)
CG_Particle_OilSlick.
Parameters
[in] pshader
[in] cent
Definition at line 1860 of file cg_particles.c.
Referenced by CG_EntityEvent().
void CG_ParticleBloodCloud (centity_t * cent, vec3_t origin, vec3_t dir)
CG_ParticleBloodCloud.
Parameters
[in] cent
[in] origin
[in] dir
Definition at line 1974 of file cg_particles.c.
Referenced by CG_GibPlayer().
void CG_ParticleBulletDebris (vec3_t org, vec3_t vel, int duration)
CG_ParticleBulletDebris.
Parameters
[in] org
[in] vel
[in] duration
Definition at line 1387 of file cg_particles.c.
Referenced by CG_AddBulletParticles().
void CG_ParticleDirtBulletDebris_Core (vec3_t org, vec3_t vel, int duration, float width, float height, float alpha, qhandle_t shader)
The core of the dirt explosion.
Parameters
[in] org
[in] vel
[in] duration
[in] width
[in] height
[in] alpha
[in] shader
Definition at line 1439 of file cg_particles.c.
Referenced by CG_AddDirtBulletParticles().
void CG_ParticleDust (centity_t * cent, vec3_t origin, vec3_t dir)
CG_ParticleDust.
Parameters
[in] cent
[in] origin
[in] dir
Definition at line 2135 of file cg_particles.c.
Referenced by CG_EntityEvent().
void CG_ParticleExplosion (const char * animStr, vec3_t origin, vec3_t vel, int duration, int sizeStart, int sizeEnd, qboolean dlight)
CG_ParticleExplosion.
Parameters
[in] animStr
[in] origin
[in] vel
[in] duration
[in] sizeStart
[in] sizeEnd
[in] dlight
Definition at line 1487 of file cg_particles.c.
Referenced by CG_BigExplosionImpact(), CG_DynamiteExplosionImpact(), CG_Effect(), CG_MapMortarImpact(), CG_MissileHitWallSmall(), CG_RocketTrail(), and CG_SmallExplosionImpact().
void CG_ParticleImpactSmokePuff (qhandle_t pshader, vec3_t origin)
CG_ParticleImpactSmokePuff.
Parameters
[in] pshader
[in] origin
Definition at line 1707 of file cg_particles.c.
Referenced by CG_BulletImpact(), and CG_MortarEFX().
void CG_ParticleImpactSmokePuffExtended (qhandle_t pshader, vec3_t origin, int lifetime, int vel, int acc, int maxroll, float alpha, float size)
CG_ParticleImpactSmokePuffExtended.
Parameters
[in] pshader
[in] origin
[in] lifetime
[in] vel
[in] acc
[in] maxroll
[in] alpha
[in] size
Definition at line 1655 of file cg_particles.c.
Referenced by CG_AddFragment(), CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_DrawActiveFrame(), CG_EntityEffects(), and CG_ParticleImpactSmokePuff().
void CG_ParticleSmoke (qhandle_t pshader, centity_t * cent)
CG_ParticleSmoke.
Parameters
[in] pshader
[in] cent
Definition at line 1245 of file cg_particles.c.
Referenced by CG_EntityEvent(), and CG_Smoker().
void CG_ParticleSnow (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
CG_ParticleSnow.
Parameters
[in] pshader
[in] origin
[in] origin2
[in] turb
[in] range
[in] snum
Definition at line 1105 of file cg_particles.c.
Referenced by CG_NewParticleArea().
void CG_ParticleSnowFlurry (qhandle_t pshader, centity_t * cent)
CG_ParticleSnowFlurry.
Parameters
[in] pshader
[in] cent
Definition at line 1035 of file cg_particles.c.
Referenced by CG_EntityEvent().
void CG_ParticleSparks (vec3_t org, vec3_t vel, int duration, float x, float y, float speed)
CG_ParticleSparks.
Parameters
[in] org
[in] vel
[in] duration
[in] x
[in] y
[in] speed
Definition at line 2077 of file cg_particles.c.
Referenced by CG_EntityEvent().
void CG_PB_ClearPolyBuffers (void)
CG_PB_ClearPolyBuffers.
Definition at line 104 of file cg_polybus.c.
Referenced by CG_DrawActiveFrame().
polyBuffer_t* CG_PB_FindFreePolyBuffer (qhandle_t shader, int numVerts, int numIndicies)
CG_PB_FindFreePolyBuffer.
Parameters
[in] shader
[in] numVerts
[in] numIndicies
Returns
Definition at line 49 of file cg_polybus.c.
Referenced by CG_AddFlameSpriteToScene(), CG_AddPolyToPool(), and CG_AddTrailToScene().
void CG_PB_RenderPolyBuffers (void)
CG_PB_RenderPolyBuffers.
Definition at line 113 of file cg_polybus.c.
Referenced by CG_DrawActive().
const char* CG_PickupItemText (int itemNum)
CG_PickupItemText.
Parameters
[in] item
Returns
Todo:
: this is just related to english
Definition at line 602 of file cg_draw.c.
Referenced by CG_ItemPickup().
void CG_PlayBufferedVoiceChats (void)
CG_PlayBufferedVoiceChats.
Definition at line 1709 of file cg_servercmds.c.
Referenced by CG_DrawActiveFrame().
void CG_Player (centity_t * cent)
CG_Player.
Parameters
[in,out] cent
Todo:
: buggy
Definition at line 2483 of file cg_players.c.
Referenced by CG_ProcessEntity().
bg_playerclass_t* CG_PlayerClassForClientinfo (clientInfo_t * ci, centity_t * cent)
CG_PlayerClassForClientinfo.
Parameters
[in] ci
[in] cent
Returns
Definition at line 418 of file cg_players.c.
Referenced by CG_DrawMap(), and CG_DrawMapEntity().
void CG_PlayPMItemSound (centity_t * cent)
CG_PlayPMItemSound.
Parameters
[in] cent
Definition at line 908 of file cg_popupmessages.c.
Referenced by CG_EntityEvent().
int CG_PointContents (const vec3_t point, int passEntityNum)
CG_PointContents.
Parameters
[in] point
[in] passEntityNum
Returns
Definition at line 469 of file cg_predict.c.
Referenced by CG_AddDebrisElementsExtended(), CG_AddFragment(), CG_AddPlayerWeapon(), CG_AltWeapon_f(), CG_BreathPuffs(), CG_Bullet(), CG_CalcFov(), CG_CheckForCursorHints(), CG_DrawPlayerStatus(), CG_Effect(), CG_EntityEvent(), CG_GrenadeTrail(), CG_MachineGunEjectBrass(), CG_MissileHitPlayer(), CG_PanzerFaustEjectBrass(), CG_PlayerSplash(), CG_PredictPlayerState(), CG_PyroSmokeTrail(), and CG_RocketTrail().
void CG_PositionEntityOnTag (refEntity_t * entity, const refEntity_t * parent, const char * tagName, int startIndex, vec3_t * offset)
Modifies the entities position and axis by the given tag location.
Parameters
[in] entity
[in] parent
[in] tagName
[in] startIndex
[in] offset
Definition at line 47 of file cg_ents.c.
Referenced by CG_AddEntityToTag(), CG_AddFragment(), CG_AddPlayerWeapon(), CG_AttachBitsToTank(), CG_Cabinet(), CG_DrawPlayerHead(), CG_Item(), and CG_Player().
void CG_PositionRotatedEntityOnTag (refEntity_t * entity, const refEntity_t * parent, const char * tagName)
Modifies the entities position and axis by the given tag location.
Parameters
[in] entity
[in] parent
[in] tagName
Todo:
: allow origin offsets along tag?
Definition at line 77 of file cg_ents.c.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_AttachBitsToTank(), CG_GetBleedOrigin(), CG_MachineGunEjectBrass(), and CG_Player().
void CG_PrecacheFXSounds (void)
CG_PrecacheFXSounds.
Definition at line 491 of file cg_event.c.
Referenced by CG_RegisterSounds().
void CG_PredictPlayerState (void)
Generates cg.predictedPlayerState for the current cg.time cg.predictedPlayerState is guaranteed to be valid after exiting.
For demo playback, this will be an interpolation between two valid playerState_t.
For normal gameplay, it will be the result of predicted usercmd_t on top of the most recent playerState_t received from the server.
Each new snapshot will usually have one or more new usercmd over the last, but we simulate all unacknowledged commands each time, not just the new ones. This means that on an internet connection, quite a few pmoves may be issued each frame.
OPTIMIZE: don't re-simulate unless the newly arrived snapshot playerState_t differs from the predicted one. Would require saving all intermediate playerState_t during prediction. (this is "dead reckoning" and would definately be nice to have in there
We detect prediction errors and allow them to be decayed off over several frames to ease the jerk.
Todo:
: clarify MG & Browning are locked in place too?
Definition at line 965 of file cg_predict.c.
Referenced by CG_DrawActiveFrame().
void CG_PrevWeapon_f (void)
CG_PrevWeapon_f.
Definition at line 4483 of file cg_weapons.c.
void CG_PrevWeaponInBank_f (void)
CG_PrevWeaponInBank_f.
Definition at line 4433 of file cg_weapons.c.
void CG_printConsoleString (const char * str)
CG_printConsoleString.
Parameters
[in] str
Definition at line 1077 of file cg_main.c.
Referenced by CG_ServerCommand().
void QDECL CG_Printf (const char * msg, ...)
Referenced by CG_ActivateEditSoundMode(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddPMItem(), CG_AddTestModel(), CG_BuddyVoiceChat_f(), CG_Class_f(), CG_ConfigStringModified(), CG_CurLayerForZ(), CG_currentTime_f(), CG_DeActivateEditSoundMode(), CG_DrawActiveFrame(), CG_DumpSpeaker_f(), CG_dumpStats(), CG_EditSpeakers_f(), CG_EffectParse(), CG_EntityEvent(), CG_Fireteams_MenuTitleText_Draw(), CG_FTSayPlayerClass_f(), CG_GetBleedOrigin(), CG_ImpactMark(), CG_keyOn_f(), CG_ListSpawnPoints_f(), CG_LoadingString(), CG_LoadLocations(), CG_MapRestart(), CG_MapVote_MultiVoteButton_KeyDown(), CG_NewClientInfo(), CG_OilSlickRemove(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseTeamInfo(), CG_ParseWeaponConfig(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBubble(), CG_ParticleImpactSmokePuff(), CG_ParticleImpactSmokePuffExtended(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), CG_PlayerAnimation(), CG_PlayGlobalSound(), CG_PlayVoiceChat(), CG_PredictionOk(), CG_PredictPlayerState(), CG_printFile(), CG_PrintObjectiveInfo_f(), CG_QuickFireteams_f(), CG_ReadHuds_f(), CG_ReadNextSnapshot(), CG_RegisterCharacter(), CG_RegisterPlayerClasses(), CG_RegisterWeapon(), CG_ResetPlayerEntity(), CG_RunHudHeadLerpFrame(), CG_RunLerpFrame(), CG_RunLerpFrameRate(), CG_RunLerpFrameRateCorpse(), CG_RunWeapLerpFrame(), CG_RW_ParseWeaponSound(), CG_SaveSpeakersToScript(), CG_SayPlayerClass_f(), CG_scores_cmd(), CG_ServerCommand(), CG_SetLerpFrameAnimation(), CG_SetLerpFrameAnimationRate(), CG_SetLerpFrameAnimationRateCorpse(), CG_SetWeapLerpFrameAnimation(), CG_Shard(), CG_SoundInit(), CG_SoundLoadSoundFiles(), CG_SoundParseSounds(), CG_SoundPlaySoundScript(), CG_SoundScriptPrecache(), CG_StatsDebugAddText(), CG_TeamVoiceChat_f(), CG_TestModel_f(), CG_TestModelNextFrame_f(), CG_TestModelNextSkin_f(), CG_TestModelPrevFrame_f(), CG_TestModelPrevSkin_f(), CG_TimerReset_f(), CG_TimerSet_f(), CG_UndoEditSpeaker(), CG_Viewpos_f(), CG_vstrDown_f(), CG_vstrUp_f(), CG_WeaponAnimation(), and SP_worldspawn().
void CG_printWindow (const char * str)
CG_printWindow.
Parameters
[in] str
Definition at line 578 of file cg_window.c.
Referenced by CG_createMOTDWindow(), CG_parseBestShotsStats_cmd(), CG_parseWeaponStats_cmd(), and CG_wstatsParse_cmd().
void CG_PriorityCenterPrint (const char * str, int y, float fontScale, int priority)
Called for important messages that should stay in the center of the screen for a few moments.
Parameters
[in] str
[in] y
[in] fontScale
[in] priority
Definition at line 717 of file cg_draw.c.
Referenced by CG_CenterPrint(), CG_Class_f(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_SendSetupMsg(), CG_NewClientInfo(), CG_Obituary(), CG_ServerCommand(), and CG_SpawnpointsCheckExecKey().
void CG_ProcessSnapshots (void)
CG_ProcessSnapshots.
We are trying to set up a renderable view, so determine what the simulated time is, and try to get snapshots both before and after that time if available.
If we don't have a valid cg.snap after exiting this function, then a 3D game view cannot be rendered. This should only happen right after the initial connection. After cg.snap has been valid once, it will never turn invalid.
Even if cg.snap is valid, cg.nextSnap may not be, if the snapshot hasn't arrived yet (it becomes an extrapolating situation instead of an interpolating one)
Definition at line 524 of file cg_snapshot.c.
Referenced by CG_DrawActiveFrame().
void CG_QueueMusic (void)
CG_QueueMusic.
Todo:
: \/ the values stored in here will be made accessable so
Definition at line 2189 of file cg_main.c.
Referenced by CG_ConfigStringModified().
void CG_RailTrail (vec3_t color, vec3_t start, vec3_t end, int type, int index)
CG_RailTrail.
Parameters
[in] color
[in] start
[in] end
[in] type
[in] index
Definition at line 679 of file cg_weapons.c.
Referenced by CG_EntityEvent(), CG_Player(), and CG_TouchTriggerPrediction().
void CG_RailTrail2 (vec3_t color, vec3_t start, vec3_t end, int index, int sideNum)
Re-inserted this as a debug mechanism for bullets.
Parameters
[in] color
[in] start
[in] end
[in] index
[in] sideNum
Definition at line 627 of file cg_weapons.c.
Referenced by CG_Player(), and CG_RailTrail().
void CG_ReadHudScripts (void)
CG_ReadHudScripts.
Definition at line 620 of file cg_draw_hud.c.
Referenced by CG_Hud_Setup(), and CG_ReadHuds_f().
qboolean CG_RegisterCharacter (const char * characterFile, bg_character_t * character)
Register character.
Register character.
Parameters
[in] characterFile
[in] character
Returns
Definition at line 457 of file cg_character.c.
Referenced by CG_ConfigStringModified(), CG_RegisterGraphics(), and CG_RegisterPlayerClasses().
void CG_RegisterItemVisuals (int itemNum)
Registers models and icons for items of bg_itemlist (except weapons which are registered from *.weap file data)
Parameters
[in] itemNum
Note
Actually IT_AMMO & IT_TEAM have no visuals
Definition at line 1992 of file cg_weapons.c.
Referenced by CG_RegisterGraphics().
void CG_RegisterPlayerClasses (void)
Register player classes.
Register player classes.
Definition at line 656 of file cg_character.c.
Referenced by CG_RegisterGraphics().
void CG_RegisterWeapon (int weaponNum, qboolean force)
CG_RegisterWeapon.
Parameters
[in] weaponNum
[in] force
Definition at line 1933 of file cg_weapons.c.
Referenced by CG_RegisterGraphics().
void CG_removeStrings (cg_window_t * w)
CG_removeStrings.
Parameters
[in,out] w
Definition at line 686 of file cg_window.c.
Referenced by CG_windowFree().
void CG_RenderSmokeGrenadeSmoke (centity_t * cent, const weaponInfo_t * weapon)
CG_RenderSmokeGrenadeSmoke.
Parameters
[in,out] cent
[in] weapon
Definition at line 1081 of file cg_effects.c.
Referenced by CG_Missile().
void CG_ResetPlayerEntity (centity_t * cent)
A player just came into view or teleported, so reset all animation info.
Parameters
[in,out] cent
Definition at line 3034 of file cg_players.c.
Referenced by CG_LoadClientInfo(), and CG_ResetEntity().
void CG_Respawn (qboolean revived)
A respawn happened this snapshot.
Parameters
[in] revived
Definition at line 180 of file cg_playerstate.c.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionPlayerState().
void CG_RumbleEfx (float pitch, float yaw)
CG_RumbleEfx.
Parameters
[in] pitch
[in] yaw
Definition at line 807 of file cg_effects.c.
Referenced by CG_EntityEvent().
void CG_RunBinding (int key, qboolean down)
Referenced by CG_DemoClick(), and CG_KeyEvent().
void CG_RunBindingBuf (int key, qboolean down, char * buf)
void CG_RunMenuScript (char ** args)
CG_RunMenuScript.
Parameters
args - unused
Todo:
Unused function ?
Definition at line 989 of file cg_newDraw.c.
Referenced by CG_LoadHudMenu().
void CG_ScoresDown_f (void)
CG_ScoresDown_f.
Definition at line 211 of file cg_consolecmds.c.
Referenced by CG_DemoClick().
void CG_ScoresUp_f (void)
CG_ScoresUp_f.
Definition at line 280 of file cg_consolecmds.c.
Referenced by CG_DemoClick(), and CG_EventHandling().
void CG_SetActiveOnScriptSpeaker (int index)
CG_SetActiveOnScriptSpeaker.
Parameters
[in] index
Definition at line 2512 of file cg_sound.c.
Referenced by CG_EntityEvent().
void CG_SetConfigValues (void)
Called on load to set the initial values from configure strings.
Definition at line 736 of file cg_servercmds.c.
Referenced by CG_Init().
void CG_SetEntitySoundPosition (centity_t * cent)
Also called by event processing code.
Parameters
[in] cent
Definition at line 107 of file cg_ents.c.
Referenced by CG_CheckEvents(), and CG_EntityEffects().
void CG_SetHud (void)
CG_SetHud.
Definition at line 3046 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
void CG_SetSniperZoom (int weapon)
void CG_SetupCabinets (void)
CG_SetupCabinets.
Definition at line 2311 of file cg_ents.c.
Referenced by CG_Init().
void CG_SetupFrustum (void)
Definition at line 1696 of file cg_view.c.
Referenced by CG_DrawActiveFrame().
void CG_SetViewanglesForSpeakerEditor (void)
CG_SetViewanglesForSpeakerEditor.
Definition at line 713 of file cg_sound.c.
Referenced by CG_CalcViewValues().
void CG_ShaderStateChanged (void)
CG_ShaderStateChanged.
Definition at line 766 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ShowHelp_Off (int * status)
CG_ShowHelp_Off.
Parameters
[in,out] status
Definition at line 156 of file cg_info.c.
Referenced by CG_DemoClick(), CG_dumpStats_f(), and CG_EventHandling().
void CG_ShowHelp_On (int * status)
CG_ShowHelp_On.
Parameters
[in,out] status
Definition at line 136 of file cg_info.c.
Referenced by CG_DemoClick(), CG_dumpStats_f(), CG_keyOn_f(), CG_SetInitialSnapshot(), and CG_UpdateCvars().
void CG_SkillLevelsChanged (void)
CG_SkillLevelsChanged.
Definition at line 862 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
localEntity_t* CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
Adds a smoke puff or blood trail localEntity.
Parameters
[in] p
[in] vel
[in] radius
[in] r
[in] g
[in] b
[in] a
[in] duration
[in] startTime
[in] fadeInTime
[in] leFlags
[in] hShader
Returns
Todo:
It would be nice to have an acceleration vector for this as well. Big velocity vector with a negative acceleration for deceleration, etc. (breath could then come out of a guys mouth at the rate he's walking/running and it would slow down once it's created)
Definition at line 118 of file cg_effects.c.
Referenced by CG_BreathPuffs(), CG_Bullet(), CG_EntityEffects(), and CG_PyroSmokeTrail().
void CG_SortClientFireteam (void)
Sorts client's fireteam by leader then rank.
Definition at line 111 of file cg_fireteamoverlay.c.
Referenced by CG_NewClientInfo(), and CG_ParseFireteams().
clientInfo_t* CG_SortedFireTeamPlayerForPosition (int pos)
Client, sorted by rank, on CLIENT'S fireteam.
Parameters
[in] pos
Returns
Definition at line 341 of file cg_fireteamoverlay.c.
Referenced by CG_BuildSelectedFirteamString(), CG_DrawFireTeamOverlay(), and CG_SelectBuddy_f().
void CG_SoundInit (void)
CG_SoundInit.
Definition at line 535 of file cg_sound.c.
Referenced by CG_MapRestart(), and CG_RegisterSounds().
void CG_SoundPlayIndexedScript (int index, vec3_t org, int entnum)
CG_SoundPlayIndexedScript.
Parameters
[in] index
[in] org
[in] entnum
Definition at line 251 of file cg_sound.c.
Referenced by CG_Init().
int CG_SoundPlaySoundScript (const char * name, vec3_t org, int entnum, qboolean buffer)
CG_SoundPlaySoundScript.
Parameters
name
org
entnum
buffer
Returns
qtrue if a script is found
Definition at line 207 of file cg_sound.c.
Referenced by CG_CheckLocalSounds(), CG_EntityEvent(), CG_LimboPanel_BriefingButton_KeyDown(), CG_NewClientInfo(), CG_PlayGlobalSound(), CG_PlayPMItemSound(), and CG_ServerCommand().
int CG_SoundScriptPrecache (const char * name)
CG_SoundScriptPrecache.
Parameters
name
Returns
The index+1 of the script in the global list, for fast calling
Definition at line 57 of file cg_sound.c.
Referenced by CG_ConfigStringModified(), CG_Init(), CG_RegisterSounds(), and CG_SoundParseSounds().
void CG_SparklerSparks (vec3_t origin, int count)
CG_SparklerSparks.
Parameters
[in] origin
[in] count
Note
Unused
Definition at line 769 of file cg_effects.c.
qboolean CG_SpawnFloat (const char * key, const char * defaultString, float * out)
CG_SpawnFloat.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 75 of file cg_spawn.c.
Referenced by CG_corona(), and SP_misc_gamemodel().
qboolean CG_SpawnInt (const char * key, const char * defaultString, int * out)
CG_SpawnInt.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 92 of file cg_spawn.c.
Referenced by CG_ParseEntityFromSpawnVars().
void CG_Spawnpoints_Draw (void)
CG_Spawnpoints_Draw.
Definition at line 202 of file cg_spawnpoints.c.
Referenced by CG_Draw2D().
void CG_Spawnpoints_KeyHandling (int key, qboolean down)
CG_Spawnpoints_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 191 of file cg_spawnpoints.c.
Referenced by CG_KeyEvent().
void CG_Spawnpoints_MenuText_Draw (panel_button_t * button)
CG_Spawnpoints_MenuText_Draw.
Parameters
[in] button
Definition at line 141 of file cg_spawnpoints.c.
void CG_Spawnpoints_MenuTitleText_Draw (panel_button_t * button)
Definition at line 132 of file cg_spawnpoints.c.
void CG_Spawnpoints_Setup (void)
CG_Spawnpoints_Setup.
Definition at line 181 of file cg_spawnpoints.c.
Referenced by CG_RegisterGraphics().
qboolean CG_SpawnpointsCheckExecKey (int key, qboolean doaction)
CG_SpawnpointsCheckExecKey.
Parameters
[in] key
[in] doaction
Returns
Definition at line 213 of file cg_spawnpoints.c.
Referenced by CG_CheckExecKey(), and CG_Spawnpoints_KeyHandling().
qboolean CG_SpawnString (const char * key, const char * defaultString, char ** out)
CG_SpawnString.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 45 of file cg_spawn.c.
Referenced by CG_corona(), CG_ParseEntityFromSpawnVars(), CG_SpawnFloat(), CG_SpawnInt(), CG_SpawnVector(), CG_SpawnVector2D(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_path_corner_2(), SP_trigger_objective_info(), and SP_worldspawn().
qboolean CG_SpawnVector (const char * key, const char * defaultString, float * out)
CG_SpawnVector.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 109 of file cg_spawn.c.
Referenced by CG_corona(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_path_corner_2(), and SP_worldspawn().
void CG_SpeakerEditor_KeyHandling (int key, qboolean down)
CG_SpeakerEditor_KeyHandling.
Parameters
[in] key
[in] down
Definition at line 2247 of file cg_sound.c.
Referenced by CG_KeyEvent().
void CG_SpeakerEditorDraw (void)
CG_SpeakerEditorDraw.
Definition at line 2139 of file cg_sound.c.
Referenced by CG_Draw2D().
void CG_SpeakerEditorMouseMove_Handling (int x, int y)
CG_SpeakerEditorMouseMove_Handling.
Parameters
[in] x
[in] y
Definition at line 2325 of file cg_sound.c.
Referenced by CG_MouseEvent().
void CG_StartMusic (void)
CG_StartMusic.
Definition at line 2170 of file cg_main.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
void CG_StatsDebugAddText (const char * text)
CG_StatsDebugAddText.
Parameters
[in] text
Definition at line 1566 of file cg_draw_hud.c.
Referenced by CG_ServerCommand().
void CG_StatsRanksMedalsClick (int key)
float* CG_TeamColor (int team)
CG_TeamColor.
Parameters
[in] team
Returns
Note
Unused
Definition at line 572 of file cg_drawtools.c.
void CG_TeamDebriefingTeamSkillXP_Draw (panel_button_t * button)
CG_TeamDebriefingTeamSkillXP_Draw.
Parameters
[in] button
Definition at line 3214 of file cg_debriefing.c.
void CG_TeamRestrictionsChanged (void)
CG_TeamRestrictionsChanged.
Definition at line 837 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_TestGun_f (void)
Replaces the current view weapon with the given model.
Definition at line 115 of file cg_view.c.
void CG_TestModel_f (void)
Creates an entity in front of the current position, which can then be moved around.
Definition at line 77 of file cg_view.c.
Referenced by CG_TestGun_f().
void CG_TestModelNextFrame_f (void)
CG_TestModelNextFrame_f.
Definition at line 125 of file cg_view.c.
void CG_TestModelNextSkin_f (void)
CG_TestModelNextSkin_f.
Definition at line 147 of file cg_view.c.
void CG_TestModelPrevFrame_f (void)
CG_TestModelPrevFrame_f.
Definition at line 134 of file cg_view.c.
void CG_TestModelPrevSkin_f (void)
CG_TestModelPrevSkin_f.
Definition at line 156 of file cg_view.c.
int CG_Text_Height (const char * text, float scale, int limit)
CG_Text_Height.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 170 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
int CG_Text_Height_Ext (const char * text, float scale, int limit, fontHelper_t * font)
CG_Text_Height_Ext.
Parameters
[in] text
[in] scale
[in] limit
[in] font
Returns
Definition at line 125 of file cg_draw.c.
Referenced by CG_AddOnScreenText(), CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawFollow(), CG_DrawGrid(), CG_DrawLimboMessage(), CG_DrawMortarReticle(), CG_DrawSpectatorMessage(), CG_DrawVote(), CG_LoadHudMenu(), CG_ObjectivePrint(), CG_PriorityCenterPrint(), CG_removeStrings(), CG_Text_Height(), and CG_windowNormalizeOnText().
void CG_Text_Paint (float x, float y, float scale, vec4_t color, const char * text, float adjust, int limit, int style)
CG_Text_Paint.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] adjust
[in] limit
[in] style
Definition at line 328 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
void CG_Text_Paint_Centred_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char * text, float adjust, int limit, int style, fontHelper_t * font)
CG_Text_Paint_Centred_Ext.
Parameters
[in] x
[in] y
[in] scalex
[in] scaley
[in] color
[in] text
[in] adjust
[in] limit
[in] style
[in] font
Definition at line 234 of file cg_draw.c.
Referenced by CG_DrawConnectScreen().
void CG_Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char * text, float adjust, int limit, int style, fontHelper_t * font)
CG_Text_Paint_Ext.
Parameters
[in] x
[in] y
[in] scalex
[in] scaley
[in] color
[in] text
[in] adjust
[in] limit
[in] style
[in] font
Definition at line 254 of file cg_draw.c.
Referenced by CG_CommandMap_DrawHighlightText(), CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_DebriefingPlayerList_Draw(), CG_DebriefingPlayerWeaponStats_Draw(), CG_DebriefingTitle_Draw(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawAmmoCount(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDemoControls(), CG_DrawDemoRecording(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawLimboMessage(), CG_DrawLocalTime(), CG_DrawMapEntity(), CG_DrawMortarReticle(), CG_DrawObjectiveInfo(), CG_DrawOnScreenLabels(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScoreboard(), CG_DrawSkills(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawStatsDebug(), CG_DrawTeamInfo(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawXP(), CG_Fireteams_MenuText_Draw(), CG_Fireteams_MenuTitleText_Draw(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_LoadPanel_LoadingBarText(), CG_LoadPanel_RenderCampaignNameText(), CG_LoadPanel_RenderCampaignTypeText(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_VoteButton_Draw(), CG_MapVoteList_Draw(), CG_ObjectivesDraw(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_Spawnpoints_MenuText_Draw(), CG_Spawnpoints_MenuTitleText_Draw(), CG_SpeakerEditor_LocInfo(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerEditorDraw(), CG_SpeakerInfo_Text(), CG_TeamDebriefingTeamSkillXP_Draw(), CG_Text_Paint(), CG_Text_Paint_Centred_Ext(), CG_TopShotsDraw(), CG_windowDraw(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void CG_Text_PaintChar (float x, float y, float width, float height, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] scale
[in] s
[in] t
[in] s2
[in] t2
[in] hShader
Definition at line 212 of file cg_draw.c.
Referenced by CG_Text_PaintWithCursor_Ext().
void CG_Text_PaintChar_Ext (float x, float y, float w, float h, float scalex, float scaley, float s, float t, float s2, float t2, qhandle_t hShader)
CG_Text_PaintChar_Ext.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] scalex
[in] scaley
[in] s
[in] t
[in] s2
[in] t2
[in] hShader
Definition at line 191 of file cg_draw.c.
Referenced by CG_Text_Paint_Ext().
void CG_Text_PaintWithCursor (float x, float y, float scale, vec4_t color, const char * text, int cursorPos, const char * cursor, int limit, int style)
CG_Text_PaintWithCursor.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] cursorPos
[in] cursor
[in] limit
[in] style
Definition at line 453 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
void CG_Text_PaintWithCursor_Ext (float x, float y, float scale, vec4_t color, const char * text, int cursorPos, const char * cursor, int limit, int style, fontHelper_t * font)
CG_Text_PaintWithCursor_Ext.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] cursorPos
[in] cursor
[in] limit
[in] style
Definition at line 347 of file cg_draw.c.
Referenced by CG_Debriefing_ChatEdit_Draw(), CG_LoadHudMenu(), and CG_Text_PaintWithCursor().
void CG_Text_SetActiveFont (int font)
CG_Text_SetActiveFont.
Parameters
[in] font
Definition at line 54 of file cg_draw.c.
Referenced by CG_LoadHudMenu().
int CG_Text_Width (const char * text, float scale, int limit)
CG_Text_Width.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 110 of file cg_draw.c.
Referenced by CG_FitTextToWidth2(), CG_FitTextToWidth_SingleLine(), CG_LoadHudMenu(), and CG_TrimLeftPixels().
int CG_Text_Width_Ext (const char * text, float scale, int limit, fontHelper_t * font)
CG_Text_Width_Ext.
Parameters
[in] text
[in] scale
[in] limit
[in] font
Returns
Definition at line 67 of file cg_draw.c.
Referenced by CG_AddOnScreenText(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_DebriefingTitle_Draw(), CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawAmmoCount(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawMapEntity(), CG_DrawMortarReticle(), CG_DrawObjectiveInfo(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawRank(), CG_DrawScoreboard(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpeed(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawWarmup(), CG_DrawXP(), CG_FitTextToWidth_Ext(), CG_getBindKeyName(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_LoadPanel_RenderCampaignNameText(), CG_ObjectivePrint(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_PriorityCenterPrint(), CG_removeStrings(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerInfo_Text(), CG_StatsDebugAddText(), CG_Text_Paint_Centred_Ext(), CG_Text_Width(), CG_windowNormalizeOnText(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
void CG_TileClear (void)
CG_TileClear.
Clear around a sized down screen
Definition at line 493 of file cg_drawtools.c.
Referenced by CG_DrawActive().
void CG_ToggleActiveOnScriptSpeaker (int index)
CG_ToggleActiveOnScriptSpeaker.
Parameters
[in] index
Definition at line 2484 of file cg_sound.c.
Referenced by CG_EntityEvent().
void CG_Trace (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
CG_Trace.
Parameters
[in] result
[in] start
[in] mins
[in] maxs
[in] end
[in] skipNumber
[in] mask
Definition at line 362 of file cg_predict.c.
Referenced by CG_AddBloodElements(), CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), CG_AddFragment(), CG_AddSparkElements(), CG_Bullet(), CG_CheckForCursorHints(), CG_Corona(), CG_Coronas(), CG_DrawOnScreenLabels(), CG_DumpSpeaker_f(), CG_FireFlameChunks(), CG_GibPlayer(), CG_InterpolatePlayerState(), CG_MoveFlameChunk(), CG_OffsetThirdPersonView(), CG_PredictLean(), CG_RenderSmokeGrenadeSmoke(), CG_ScanForCrosshairDyna(), CG_ScanForCrosshairEntity(), CG_ScanForCrosshairMine(), CG_ShakeCamera(), and CG_SmokeSpritePhysics().
void CG_TransformToCommandMapCoord (float * coord_x, float * coord_y)
CG_TransformToCommandMapCoord.
Parameters
[in] coord_x
[in] coord_y
Definition at line 48 of file cg_commandmap.c.
Referenced by CG_ParseSpawns().
void CG_TransitionPlayerState (playerState_t * ps, playerState_t * ops)
CG_TransitionPlayerState.
Parameters
[in] ps
[in] ops
Definition at line 491 of file cg_playerstate.c.
Referenced by CG_PredictPlayerState(), and CG_TransitionSnapshot().
const char* CG_TranslateString (const char * string)
CG_TranslateString.
Parameters
[in] string
Returns
Definition at line 688 of file cg_drawtools.c.
Referenced by CG_BuddyVoiceChat_f(), CG_Class_f(), CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatButton_Draw(), CG_Debriefing_Maps_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerRank_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_WinStringForTeam(), CG_DebriefingTitle_Draw(), CG_DemoClick(), CG_DemoHelpDraw(), CG_DrawCrosshairNames(), CG_DrawDemoControls(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawScoreboard(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawVote(), CG_DrawWarmup(), CG_dumpStats(), CG_findClientNum(), CG_Fireteams_MenuText_Draw(), CG_Fireteams_MenuTitleText_Draw(), CG_FTSayPlayerClass_f(), CG_GameStatsDraw(), CG_getBindKeyName(), CG_GetPMItemText(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_ItemPickup(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_WeaponPanel(), CG_LoadHudMenu(), CG_LoadPanel_GameTypeName(), CG_LocalizeServerCommand(), CG_MapVoteList_Draw(), CG_NewClientInfo(), CG_Obituary(), CG_ObjectivePrint(), CG_ObjectivesDraw(), CG_ParseSpawns(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_ParseWolfinfo(), CG_PickupItemText(), CG_SayPlayerClass_f(), CG_ServerCommand(), CG_Spawnpoints_MenuTitleText_Draw(), CG_SpawnpointsCheckExecKey(), CG_TeamVoiceChat_f(), CG_TopShotsDraw(), CG_TouchTriggerPrediction(), CG_VoiceChatLocal(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
int CG_TrimLeftPixels (char * instr, float scale, float w, int size)
CG_TrimLeftPixels.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
Returns
Note
Unused
Definition at line 47 of file cg_newDraw.c.
qboolean CG_UICommonClick (void)
void CG_UICurrentSquadSetup (void)
void CG_UndoEditSpeaker (void)
CG_UndoEditSpeaker.
Definition at line 2448 of file cg_sound.c.
Referenced by CG_UndoSpeaker_f().
void CG_UnsetActiveOnScriptSpeaker (int index)
CG_UnsetActiveOnScriptSpeaker.
Parameters
[in] index
Definition at line 2498 of file cg_sound.c.
Referenced by CG_EntityEvent().
void CG_UpdateBufferedSoundScripts (void)
CG_UpdateBufferedSoundScripts.
Definition at line 172 of file cg_sound.c.
Referenced by CG_DrawActiveFrame().
void CG_UpdateCvars (void)
CG_UpdateCvars.
Definition at line 651 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
void CG_UpdateFlamethrowerSounds (void)
CG_UpdateFlamethrowerSounds.
Definition at line 1330 of file cg_flamethrower.c.
Referenced by CG_AddPacketEntities().
void CG_UpdatePMLists (void)
CG_UpdatePMLists.
Definition at line 163 of file cg_popupmessages.c.
Referenced by CG_DrawActiveFrame().
void CG_UpdateSvCvars (void)
CG_UpdateSvCvars.
Definition at line 228 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_Weapon_f (void)
CG_Weapon_f.
Definition at line 4581 of file cg_weapons.c.
void CG_WeaponBank_f (void)
Weapon keys are not generally bound directly('bind 1 weapon 1'), rather the key is bound to a given bank ('bind 1 weaponbank 1')
Definition at line 4516 of file cg_weapons.c.
Referenced by CG_Weapon_f().
qboolean CG_WeaponSelectable (int weapon)
Check weapon is selectable.
Parameters
weapon - the weapon to check if selectable
Returns
qtrue if the weapon is selectable, else qfalse if not
Definition at line 3408 of file cg_weapons.c.
Referenced by CG_AltWeapon_f(), CG_EntityEvent(), CG_FinishWeaponChange(), CG_LastWeaponUsed_f(), CG_NextWeap(), CG_OutOfAmmoChange(), CG_PrevWeap(), and CG_WeaponBank_f().
cg_window_t* CG_windowAlloc (int fx, int startupLength)
Reserve a window.
Parameters
[in] fx
[in] startupLength
Returns
Definition at line 198 of file cg_window.c.
Referenced by CG_createMOTDWindow(), CG_createStatsWindow(), and CG_createTopShotsWindow().
void CG_windowDraw (void)
Main window-drawing handler.
Todo:
: Add in support for ALL scrolling effects
Definition at line 327 of file cg_window.c.
Referenced by CG_Draw2D().
void CG_windowFree (cg_window_t * w)
Free up a window reservation.
Parameters
[in,out] w
Definition at line 228 of file cg_window.c.
Referenced by CG_SetInitialSnapshot(), and CG_windowCleanup().
void CG_windowInit (void)
Windowing system setup.
Definition at line 147 of file cg_window.c.
Referenced by CG_Init().
void CG_windowNormalizeOnText (cg_window_t * w)
Set the window width and height based on the windows text/font parameters.
Parameters
[in,out] w
Definition at line 510 of file cg_window.c.
Referenced by CG_windowDraw().
qboolean CG_WorldCoordToScreenCoordFloat (vec3_t point, float * x, float * y)
Float a sprite over the player's head added height parameter.
Parameters
point
[out] x
[out] y
Returns
Definition at line 711 of file cg_drawtools.c.
Referenced by CG_AddOnScreenText().
void QDECL CG_WriteToLog (const char * fmt, ...)
Referenced by CG_PlayVoiceChat(), and CG_ServerCommand().
void CG_wstatsParse_cmd (void)
CG_wstatsParse_cmd.
Definition at line 1937 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_ZoomIn_f (void)
CG_ZoomIn_f.
Definition at line 842 of file cg_view.c.
Referenced by CG_DemoClick(), and CG_ZoomRequired().
void CG_ZoomOut_f (void)
CG_ZoomOut_f.
Definition at line 864 of file cg_view.c.
Referenced by CG_DemoClick(), and CG_ZoomRequired().
void QDECL void QDECL void QDECL format (printf , 1 , 2)
Referenced by CG_getBindKeyName(), Com_Error(), Com_Printf(), G_DPrintf(), G_Error(), G_LogPrintf(), G_Printf(), Q_isforfilename(), R_CreateFBOColorBuffer(), R_CreateFBODepthBuffer(), R_CreateFBOPackedDepthStencilBuffer(), R_CreateFBOStencilBuffer(), R_LoadDDSImageData(), R_ScreenShot_f(), R_TakeScreenshot(), and R_UploadImage().
void InitSmokeSprites (void)
InitSmokeSprites.
Definition at line 907 of file cg_effects.c.
Referenced by CG_MapRestart(), and CG_RegisterGraphics().
int SkillNumForClass (int classNum)
SkillNumForClass.
Parameters
[in] classNum
Returns
Definition at line 363 of file cg_scoreboard.c.
Referenced by CG_DemoClick(), CG_DrawCrosshairNames(), CG_DrawFireTeamOverlay(), CG_DrawFollow(), WM_DrawClientScore(), and WM_DrawClientScore_Small().
void testPrintFloat (char * string, float f)
testPrintFloat
Parameters
[out] string
[in] f
Definition at line 1211 of file cg_syscalls.c.
void testPrintInt (char * string, int i)
testPrintInt
Parameters
[out] string
[in] i
Definition at line 1201 of file cg_syscalls.c.
void trap_AddCommand (const char * cmdName)
trap_AddCommand
Todo:
: replace this with a normal console command "defineCommand"?
Parameters
[in] cmdName
Definition at line 258 of file cg_syscalls.c.
Referenced by CG_InitConsoleCommands(), and UI_Init().
int trap_Argc (void)
trap_Argc
Returns
Definition at line 153 of file cg_syscalls.c.
Referenced by _et_trap_Argc(), Bot_Interface_ConsoleCommand(), CC_loadconfig(), CC_svcvar(), CG_BuddyVoiceChat_f(), CG_Class_f(), CG_Fade_f(), CG_parseMapVoteListInfo(), CG_parseMapVoteTally(), CG_ReadHuds_f(), CG_scores_cmd(), CG_ServerCommand(), CG_TeamVoiceChat_f(), CG_TestModel_f(), CG_TimerSet_f(), CG_VoiceChat_f(), CG_vstrDown_f(), CG_vstrUp_f(), Cmd_CallVote_f(), Cmd_FireTeam_MP_f(), Cmd_Follow_f(), Cmd_Say_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_Voice_f(), Cmd_WeaponStat_f(), ConcatArgs(), G_Config_v(), G_GetPlayerByName(), G_GetPlayerByNum(), G_IntermissionMapVote(), G_makesc_cmd(), G_MapRestart_v(), G_MatchReset_v(), G_Nextmap_v(), G_ParseCampaigns(), G_PlaySound_Cmd(), G_ref_cmd(), G_Referee_v(), G_refMakeShoutcaster_cmd(), G_refRemoveShoutcaster_cmd(), G_removesc_cmd(), G_sclogin_cmd(), G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), G_StartMatch_v(), G_statsPrint(), G_SwapTeams_v(), G_Unreferee_v(), G_voteDescription(), G_weaponRankings_cmd(), Svcmd_AddIP_f(), Svcmd_Burn(), Svcmd_CSInfo_f(), Svcmd_Die(), Svcmd_EntityList_f(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Svcmd_Pip(), Svcmd_RemoveIP_f(), and Svcmd_Unfreeze().
void trap_Args (char * buffer, int bufferLength)
trap_Args
Parameters
[out] buffer
[in] bufferLength
Definition at line 174 of file cg_syscalls.c.
Referenced by CG_ReadHuds_f().
void trap_Argv (int n, char * buffer, int bufferLength)
trap_Argv
Parameters
[in] n
[out] buffer
[in] bufferLength
[in] n
[in] buffer
[in] bufferLength
Definition at line 164 of file cg_syscalls.c.
Referenced by _et_trap_Argv(), Bot_Interface_ConsoleCommand(), CC_loadconfig(), CC_svcvar(), CG_Argv(), CG_BuddyVoiceChat_f(), CG_Class_f(), CG_MessageMode_f(), CG_ParseMapEntity(), CG_ReadHuds_f(), CG_ServerCommand(), CG_SetWeaponCrosshair_f(), CG_TeamVoiceChat_f(), CG_TimerSet_f(), CG_VoiceChat_f(), ClientCommand(), Cmd_AuthRcon_f(), Cmd_CallVote_f(), Cmd_FireTeam_MP_f(), Cmd_Follow_f(), Cmd_Ignore_f(), Cmd_IntermissionWeaponStats_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_UnIgnore_f(), Cmd_Voice_f(), Cmd_Vote_f(), Cmd_WeaponStat_f(), ConcatArgs(), ConsoleCommand(), G_commandHelp(), G_IntermissionMapVote(), G_MakeReferee(), G_makesc_cmd(), G_MuteClient(), G_ParseCampaigns(), G_PlayerBan(), G_PlaySound_Cmd(), G_ref_cmd(), G_refMakeShoutcaster_cmd(), G_refMute_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_refRemoveShoutcaster_cmd(), G_refWarmup_cmd(), G_refWarning_cmd(), G_RemoveReferee(), G_removesc_cmd(), G_sclogin_cmd(), G_sclogout_cmd(), G_specinvite_cmd(), G_statsPrint(), G_UnMuteClient(), G_Voice(), G_voteDescription(), G_weaponRankings_cmd(), Svcmd_AddIP_f(), Svcmd_Burn(), Svcmd_Campaign_f(), Svcmd_CSInfo_f(), Svcmd_Die(), Svcmd_Fling(), Svcmd_ForceTeam_f(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Svcmd_Pip(), Svcmd_Ref_f(), Svcmd_RemoveIP_f(), Svcmd_RevivePlayer(), Svcmd_Unfreeze(), UI_Argv(), and UI_Campaign_f().
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
Parameters
handle
[in] handle
Definition at line 1479 of file cg_syscalls.c.
Referenced by CG_DrawCinematic(), UI_DrawCampaignCinematic(), UI_DrawCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), and UI_DrawPreviewCinematic().
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle.
arg0 is the name in the format "idlogo.roq", set arg1 to NULL, alteredstates to qfalse (do not alter gamestate)
Parameters
[in] arg0
[in] xpos
[in] ypos
[in] width
[in] height
[in] bits
Returns
This returns a handle.
Parameters
[in] arg0
[in] xpos
[in] ypos
[in] width
[in] height
[in] bits
Returns
Definition at line 1447 of file cg_syscalls.c.
Referenced by CG_PlayCinematic(), UI_DrawCampaignCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawPreviewCinematic(), UI_FeederSelection(), and UI_PlayCinematic().
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
Parameters
[in] handle
Returns
Definition at line 1470 of file cg_syscalls.c.
Referenced by CG_RunCinematicFrame(), UI_DrawCampaignCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawPreviewCinematic(), and UI_RunCinematicFrame().
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 1492 of file cg_syscalls.c.
Referenced by CG_DrawCinematic(), UI_DrawCampaignCinematic(), UI_DrawCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), and UI_DrawPreviewCinematic().
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
Parameters
[in] handle
Returns
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
Parameters
[in] handle
Returns
Definition at line 1459 of file cg_syscalls.c.
Referenced by CG_StopCinematic(), UI_ClanName_HandleKey(), UI_FeederSelection(), UI_RunMenuScript(), and UI_StopCinematic().
void trap_CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_BoxTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
Definition at line 369 of file cg_syscalls.c.
Referenced by CG_BigExplosionImpact(), CG_Bullet(), CG_DynamiteExplosionImpact(), CG_MapMortarImpact(), CG_PlayerShadow(), CG_PlayerSplash(), CG_SmallExplosionImpact(), and CG_Trace().
void trap_CM_CapsuleTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_CapsuleTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
Definition at line 406 of file cg_syscalls.c.
Referenced by CG_TraceCapsule(), and CG_TraceCapsule_World().
clipHandle_t trap_CM_InlineModel (int index)
trap_CM_InlineModel
Parameters
[in] index
Returns
Definition at line 308 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities(), and CG_PointContents().
void trap_CM_LoadMap (const char * mapname)
trap_CM_LoadMap
Parameters
[in] mapname
Definition at line 1829 of file cg_syscalls.c.
Referenced by CG_Init(), and trap_TranslateString().
int trap_CM_MarkFragments (int numPoints, const vec3_t * points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t * fragmentBuffer)
trap_CM_MarkFragments
Parameters
[in] numPoints
[in] points
[in] projection
[in] maxPoints
[in] pointBuffer
[in] maxFragments
[in] fragmentBuffer
Returns
Definition at line 444 of file cg_syscalls.c.
int trap_CM_NumInlineModels (void)
trap_CM_NumInlineModels
Returns
Definition at line 298 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics().
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
trap_CM_PointContents
Parameters
[in] p
[in] model
Returns
Definition at line 341 of file cg_syscalls.c.
Referenced by CG_PointContents().
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempBoxModel
Parameters
[in] mins
[in] maxs
Returns
Definition at line 319 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities().
clipHandle_t trap_CM_TempCapsuleModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempCapsuleModel
Parameters
[in] mins
[in] maxs
Returns
Definition at line 330 of file cg_syscalls.c.
void trap_CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedBoxTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] origin
[in] angles
Definition at line 388 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities().
void trap_CM_TransformedCapsuleTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedCapsuleTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] origin
[in] angles
Definition at line 425 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities().
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedPointContents
Parameters
[in] p
[in] model
[in] origin
[in] angles
Returns
Definition at line 354 of file cg_syscalls.c.
Referenced by CG_PointContents().
void trap_Cvar_LatchedVariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
[in] varName
[in] buffer
[in] bufsize
Definition at line 144 of file cg_syscalls.c.
Referenced by G_UpdateCvars().
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
trap_Cvar_Register
Parameters
[in] vmCvar
[in] varName
[in] defaultValue
[in] flags
Definition at line 103 of file cg_syscalls.c.
Referenced by CG_RegisterCvars(), G_DebugOpenSkillLog(), G_RegisterCvars(), G_Script_ScriptLoad(), and UI_RegisterCvars().
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 122 of file cg_syscalls.c.
Referenced by _et_trap_Cvar_Set(), BeginIntermission(), BG_PanelButton_EditClick(), Bot_Interface_Init(), Bot_Interface_Update(), CG_AdjustAutomapZoom(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_Startup(), CG_DemoClick(), CG_DrawActiveFrame(), CG_DrawConnectScreen(), CG_DrawFlashFade(), CG_DrawTimedMenus(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_EventHandling(), CG_FinishWeaponChange(), CG_Init(), CG_KickAngles(), CG_LimboPanel_NameEditFinish(), CG_LimboPanel_Setup(), CG_LoadHudMenu(), CG_MapRestart(), CG_MessageMode_f(), CG_MessageSend_f(), CG_NewClientInfo(), CG_ParseServerinfo(), CG_ParseWolfinfo(), CG_PredictPlayerState(), CG_ProcessCvars(), CG_RegisterCvars(), CG_RestoreProfile(), CG_ScoresDown_f(), CG_setClientFlags(), CG_SetHud(), CG_Shutdown(), CG_TimerReset_f(), CG_TimerSet_f(), CG_UpdateCvars(), CheckCvars(), CheckExitRules(), CheckWolfMP(), ClientThink_real(), etpro_PlayerInfo(), ExitLevel(), G_BalancedTeams_v(), G_checkReady(), G_ClearMapXP(), G_configSet(), G_deleteStats(), G_InitGame(), G_LogExit(), G_ParseCampaigns(), G_ParseSettings(), G_ReadSessionData(), G_refWarmup_cmd(), G_RegisterCvars(), G_resetModeState(), G_resetRoundState(), G_Script_ScriptLoad(), G_ScriptAction_AlliedRespawntime(), G_ScriptAction_AxisRespawntime(), G_ScriptAction_Cvar(), G_ScriptAction_EntityScriptName(), G_ScriptAction_SetDebugLevel(), G_ScriptAction_SetRoundTimelimit(), G_ShutdownGame(), G_StoreMapXP(), G_UpdateCvars(), G_verifyMatchState(), G_voteFlags(), G_voteSetOnOff(), G_voteSetValue(), G_wipeCvars(), G_WriteClientSessionData(), G_WriteSessionData(), ETInterface::InterfaceSendMessage(), Script_ConditionalScript(), SP_worldspawn(), Svcmd_Campaign_f(), Svcmd_SwapTeams_f(), UI_BuildPlayerList(), UI_Campaign_f(), UI_CheckExecKey(), UI_ClanName_HandleKey(), UI_Crosshair_HandleKey(), UI_DrawCampaignCinematic(), UI_DrawCampaignMapDescription(), UI_DrawCampaignMapPreview(), UI_DrawCampaignName(), UI_DrawCampaignPreview(), UI_DrawLoadPanel(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_GetServerStatusInfo(), UI_GLCustom(), UI_Init(), UI_KeyEvent(), UI_LoadProfiles(), UI_NextOpponent(), UI_Pause(), UI_PriorOpponent(), UI_Refresh(), UI_RegisterCvars(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_ShowPostGame(), UI_StartServerRefresh(), UI_TeamMember_HandleKey(), UI_TeamName_HandleKey(), UI_Update(), and UpdateIPBans().
void trap_Cvar_Update (vmCvar_t * vmCvar)
trap_Cvar_Update
Parameters
[in] vmCvar
Definition at line 112 of file cg_syscalls.c.
Referenced by BeginIntermission(), Bot_Interface_Init(), CG_ParseServerinfo(), CG_UpdateCvars(), CheckExitRules(), CheckWolfMP(), G_InitGame(), G_LogExit(), G_RegisterCvars(), G_ShutdownGame(), G_UpdateCvars(), UI_BuildServerDisplayList(), UI_LoadProfiles(), UI_RunMenuScript(), and UI_UpdateCvars().
void trap_Cvar_VariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_VariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
[in] varName
[in] buffer
[in] bufsize
Definition at line 133 of file cg_syscalls.c.
Referenced by _et_trap_Cvar_Get(), BG_AddPredictableEventToPlayerstate(), BG_PanelButton_RenderEdit(), CG_AddToNotify(), CG_Cvar_Get(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_ChatEditFinish(), CG_KickAngles(), CG_LimboPanel_NameEditFinish(), CG_LimboPanel_Setup(), CG_LoadHudMenu(), CG_MessageSend_f(), CG_MouseEvent(), CG_ProcessCvars(), CG_RegisterCvars(), CG_SetInitialSnapshot(), CG_UpdateSvCvars(), Cmd_AuthRcon_f(), ExitLevel(), G_Campaign_v(), G_ConfigCheckLocked(), G_Gametype_v(), G_GetMapXP(), G_InitWorldSession(), G_Is_SV_Running(), G_LuaStartVM(), G_Map_v(), G_NextCampaign_v(), G_Nextmap_v(), G_ParseMapSettings(), G_ReadSessionData(), G_refWarmup_cmd(), G_RestartCampaign_v(), G_Script_ScriptLoad(), ETInterface::GetLogPath(), Item_SettingShow(), Script_ConditionalScript(), UI_BuildServerDisplayList(), UI_Cvar_VariableString(), UI_DrawMissionBriefingMap(), UI_DrawMissionBriefingObjectives(), UI_DrawMissionBriefingTitle(), UI_Init(), UI_LoadPanel_RenderHeaderText(), UI_LoadPanel_RenderLoadingText(), UI_RunMenuScript(), and UI_SetActiveMenu().
void trap_Error (const char * fmt)
trap_Error
Parameters
[in] fmt
Definition at line 80 of file cg_syscalls.c.
Referenced by CG_Error(), Com_Error(), G_Error(), UI_LoadMenus(), and UI_RunMenuScript().
int trap_FS_Delete (const char * filename)
trap_FS_Delete
Parameters
[in] filename
Returns
Definition at line 240 of file cg_syscalls.c.
Referenced by Script_WriteProfile(), and UI_RunMenuScript().
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
Parameters
[in] f
Definition at line 217 of file cg_syscalls.c.
Referenced by _et_trap_FS_FCloseFile(), BG_LoadTraceMap(), CG_AddFlameToScene(), CG_dumpStats(), CG_LoadLocations(), CG_MapVoteList_Draw(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_SaveSpeakersToScript(), CG_scores_cmd(), CG_ServerCommand(), CG_Shutdown(), CG_SoundLoadSoundFiles(), FileExists(), G_configSet(), G_DebugCloseSkillLog(), G_InitGame(), G_isValidConfig(), G_LuaRunIsolated(), G_MapVoteInfoRead(), G_MapVoteInfoWrite(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_Script_ScriptLoad(), G_ShutdownGame(), GeoIP_open(), GetMenuBuffer(), Script_CheckProfile(), Script_ConditionalScript(), Script_WriteProfile(), UI_FeederSelection(), UI_FileText(), and UI_RunMenuScript().
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
trap_FS_FOpenFile
Parameters
[in] qpath
[in,out] f
[in] mode
Returns
Parameters
[in] qpath
[in] f
[in] mode
Returns
Definition at line 186 of file cg_syscalls.c.
Referenced by _et_trap_FS_FOpenFile(), BG_LoadTraceMap(), CG_AddFlameToScene(), CG_dumpStats(), CG_Init(), CG_LoadLocations(), CG_MapVoteList_Draw(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_SaveSpeakersToScript(), CG_ServerCommand(), CG_SoundLoadSoundFiles(), FileExists(), G_configSet(), G_DebugOpenSkillLog(), G_InitGame(), G_isValidConfig(), G_LuaRunIsolated(), G_MapVoteInfoRead(), G_MapVoteInfoWrite(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_Script_ScriptLoad(), GeoIP_open(), GetMenuBuffer(), Script_CheckProfile(), Script_ConditionalScript(), Script_WriteProfile(), UI_FeederSelection(), UI_FileText(), and UI_RunMenuScript().
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
trap_FS_GetFileList
Parameters
[in] path
[in] extension
[out] listbuf
[in] bufsize
Returns
Parameters
[in] path
[in] extension
[in] listbuf
[in] bufsize
Returns
Definition at line 230 of file cg_syscalls.c.
Referenced by _et_trap_FS_GetFileList(), BeginIntermission(), CG_LocateCampaign(), CG_SpeakerEditor_NoiseEdit_KeyDown(), G_ParseCampaigns(), G_PrintConfigs(), UI_LoadArenas(), UI_LoadCampaigns(), UI_LoadDemos(), UI_LoadMods(), UI_LoadMovies(), and UI_LoadProfiles().
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
trap_FS_Read
Parameters
[out] buffer
[in] len
[in] f
[in] buffer
[in] len
[in] f
Definition at line 197 of file cg_syscalls.c.
Referenced by _et_trap_FS_Read(), BG_LoadTraceMap(), CG_LoadLocations(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_SoundLoadSoundFiles(), G_LuaRunIsolated(), G_MapVoteInfoRead(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_Script_ScriptLoad(), GeoIP_open(), GetMenuBuffer(), Script_CheckProfile(), UI_FileText(), and UI_RunMenuScript().
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
trap_FS_Write
Parameters
[in] buffer
[in] len
[in] f
[in] buffer
[in] len
[in] f
Returns
Definition at line 208 of file cg_syscalls.c.
Referenced by _et_G_LogPrint(), _et_trap_FS_Write(), CG_AddFlameToScene(), CG_printFile(), CG_SaveSpeakersToScript(), CG_scores_cmd(), CG_WriteToLog(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DebugCloseSkillLog(), G_DebugOpenSkillLog(), G_InitGame(), G_LogPrintf(), G_MapVoteInfoWrite(), G_WriteConfigFileString(), Script_WriteProfile(), and UI_RunMenuScript().
int trap_GetCurrentCmdNumber (void)
trap_GetCurrentCmdNumber
Returns
Definition at line 1157 of file cg_syscalls.c.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
void trap_GetCurrentSnapshotNumber (int * snapshotNumber, int * serverTime)
trap_GetCurrentSnapshotNumber
Parameters
[out] snapshotNumber
[out] serverTime
Definition at line 1039 of file cg_syscalls.c.
Referenced by CG_ProcessSnapshots().
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
trap_GetEntityToken
Parameters
[out] buffer
[in] bufferSize
Returns
Definition at line 1503 of file cg_syscalls.c.
Referenced by CG_ParseSpawnVars(), and G_ParseSpawnVars().
void trap_GetGameState (gameState_t * gamestate)
trap_GetGameState
Parameters
[out] gamestate
Definition at line 1016 of file cg_syscalls.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void trap_GetGlconfig (glconfig_t * glconfig)
trap_GetGlconfig
Parameters
[out] glconfig
[in] glconfig
Definition at line 1007 of file cg_syscalls.c.
Referenced by CG_Init(), and UI_Init().
void trap_GetHunkData (int * hunkused, int * hunkexpected)
trap_GetHunkData
Parameters
[out] hunkused
[out] hunkexpected
[in] hunkused
[in] hunkexpected
Definition at line 1862 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), CG_LoadPanel_RenderLoadingBar(), and UI_Init().
qboolean trap_GetServerCommand (int serverCommandNumber)
trap_GetServerCommand
Parameters
[in] serverCommandNumber
Returns
Definition at line 1148 of file cg_syscalls.c.
Referenced by CG_ExecuteNewServerCommands().
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t * snapshot)
trap_GetSnapshot
Parameters
[in] snapshotNumber
[out] snapshot
Returns
Definition at line 1078 of file cg_syscalls.c.
Referenced by CG_ReadNextSnapshot().
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t * ucmd)
trap_GetUserCmd
Parameters
[in] cmdNumber
[out] ucmd
Returns
Definition at line 1168 of file cg_syscalls.c.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
trap_Key_GetBindingBuf
Parameters
[in] keynum
[in] buf
[in] buflen
Definition at line 1533 of file cg_syscalls.c.
Referenced by CG_getBindKeyName(), CG_LoadHudMenu(), and UI_Init().
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
Returns
Definition at line 1289 of file cg_syscalls.c.
Referenced by CG_Debriefing_Draw(), CG_EventHandling(), CG_MouseEvent(), UI_CheckExecKey(), UI_KeyEvent(), UI_Pause(), UI_RunMenuScript(), and UI_SetActiveMenu().
int trap_Key_GetKey (const char * binding)
trap_Key_GetKey
Parameters
[in] binding
Returns
Definition at line 1339 of file cg_syscalls.c.
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
Returns
Definition at line 1298 of file cg_syscalls.c.
Referenced by BG_PanelButton_EditClick(), BG_PanelButton_RenderEdit(), CG_Debriefing_ChatEdit_Draw(), CG_LoadHudMenu(), and UI_Init().
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
Parameters
[in] keynum
Returns
Definition at line 1280 of file cg_syscalls.c.
Referenced by UI_Init().
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
trap_Key_KeynumToStringBuf
Parameters
[in] keynum
[out] buf
[in] buflen
[in] keynum
[in] buf
[in] buflen
Definition at line 1554 of file cg_syscalls.c.
Referenced by CG_getBindKeyName(), CG_LoadHudMenu(), CG_SpeakerEditorDraw(), and UI_Init().
void trap_Key_KeysForBinding (const char * binding, int * key1, int * key2)
trap_Key_KeysForBinding
Parameters
[in] binding
[in,out] key1
[in,out] key2
Note
binding MUST be lower case
Parameters
[in] binding
[in] key1
[in] key2
Note
binding MUST be lower case
Definition at line 1320 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), CG_SpeakerEditorDraw(), and UI_Init().
void trap_Key_SetBinding (int keynum, const char * binding)
trap_Key_SetBinding
Parameters
[in] keynum
[in] binding
Definition at line 1543 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
Parameters
[in] catcher
Definition at line 1329 of file cg_syscalls.c.
Referenced by CG_Debriefing_Draw(), CG_EventHandling(), CG_MouseEvent(), UI_KeyEvent(), UI_Pause(), UI_RunMenuScript(), and UI_SetActiveMenu().
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
Parameters
[in] state
Definition at line 1307 of file cg_syscalls.c.
Referenced by BG_PanelButton_EditClick(), CG_LoadHudMenu(), and UI_Init().
int trap_MemoryRemaining (void)
trap_MemoryRemaining
Returns
Definition at line 1220 of file cg_syscalls.c.
messageStatus_t trap_MessageStatus (void)
trap_MessageStatus
Returns
Definition at line 1882 of file cg_syscalls.c.
int trap_Milliseconds (void)
trap_Milliseconds
Returns
Definition at line 91 of file cg_syscalls.c.
Referenced by _et_trap_Milliseconds(), CG_DemoClick(), CG_DemoHelpDraw(), CG_DrawActiveFrame(), CG_DrawFlashFade(), CG_DrawFPS(), CG_DrawInformation(), CG_DrawSpeed(), CG_getBindKeyName(), CG_ShowHelp_Off(), CG_ShowHelp_On(), CG_windowDraw(), CG_windowFree(), CG_windowReset(), CG_wstatsParse_cmd(), DoClientThinks(), G_RunFrame(), UI_LoadMenus(), and vmMain().
void trap_Print (const char * fmt)
trap_Print
Parameters
[in] fmt
Definition at line 71 of file cg_syscalls.c.
Referenced by CG_AddPMItem(), CG_DPrintf(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_Obituary(), CG_ParseVoiceChats(), CG_Printf(), Com_Printf(), GetMenuBuffer(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadCampaigns(), and UI_LoadCampaignsFromFile().
void trap_R_Add2dPolys (polyVert_t * verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
Parameters
[in] verts
[in] numverts
[in] hShader
Definition at line 963 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
Parameters
[in] org
[in] r
[in] g
[in] b
[in] scale
[in] id
[in] visible
Definition at line 831 of file cg_syscalls.c.
Referenced by CG_Corona(), and CG_Coronas().
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
Parameters
[in] org
[in] radius
[in] intensity
[in] r
[in] g
[in] b
[in] hShader
[in] flags
Definition at line 815 of file cg_syscalls.c.
Referenced by CG_AddExplosion(), CG_AddFlameToScene(), CG_AddLightstyle(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddSpriteExplosion(), CG_DynamiteTrail(), CG_EntityEffects(), CG_MG42EFX(), CG_Missile(), and CG_MortarEFX().
void trap_R_AddPolyBufferToScene (polyBuffer_t * pPolyBuffer)
trap_R_AddPolyBufferToScene
Parameters
[in] pPolyBuffer
Definition at line 787 of file cg_syscalls.c.
Referenced by CG_PB_RenderPolyBuffers().
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int numPolys)
trap_R_AddPolysToScene
Parameters
[in] hShader
[in] numVerts
[in] verts
[in] numPolys
Definition at line 799 of file cg_syscalls.c.
Referenced by CG_AddTrailToScene().
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
trap_R_AddPolyToScene
Parameters
[in] hShader
[in] numVerts
[in] verts
Definition at line 778 of file cg_syscalls.c.
Referenced by CG_AddMarks(), CG_AddParticleToScene(), CG_AddSmokeSprites(), CG_AddTrailToScene(), CG_DrawTracer(), CG_Item(), and CG_PlayerSplash().
void trap_R_AddRefEntityToScene (const refEntity_t * re)
trap_R_AddRefEntityToScene
Parameters
re
[in] re
Definition at line 767 of file cg_syscalls.c.
Referenced by CG_AddConstRGB(), CG_AddDebrisElementsExtended(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddLineToScene(), CG_AddMoveScaleFade(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddSpriteExplosion(), CG_AddTestModel(), CG_AddViewWeapon(), CG_AddWeaponWithPowerups(), CG_Beam(), CG_Beam_2(), CG_Cabinet(), CG_Constructible(), CG_DamageBlendBlob(), CG_DrawMiscGamemodels(), CG_DrawPlayerHead(), CG_Explosive(), CG_General(), CG_Item(), CG_LoadHudMenu(), CG_MG42EFX(), CG_MortarEFX(), CG_MovePlane(), CG_Mover(), CG_Mover_PostProcess(), CG_PlayerFloatSprite(), CG_Portal(), CG_Prop(), CG_RenderScriptSpeakers(), CG_Trap(), and UI_Init().
void trap_R_ClearDecals (void)
trap_R_ClearDecals
Definition at line 470 of file cg_syscalls.c.
Referenced by CG_MapRestart().
void trap_R_ClearScene (void)
trap_R_ClearScene
Definition at line 758 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame(), CG_DrawPlayerHead(), CG_LoadHudMenu(), and UI_Init().
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] angle
Definition at line 930 of file cg_syscalls.c.
Referenced by CG_DrawRotatedPic().
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
Definition at line 911 of file cg_syscalls.c.
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), CG_DrawBottom_NoScale(), CG_DrawCrosshair(), CG_DrawExpandedAutoMap(), CG_DrawGrid(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawMap(), CG_DrawNoShootIcon(), CG_DrawPic(), CG_DrawPicST(), CG_DrawSides(), CG_DrawSides_NoScale(), CG_DrawSkillBar(), CG_DrawTopBottom(), CG_DrawTopBottom_NoScale(), CG_FillRect(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounterNumber(), CG_LoadHudMenu(), CG_SpeakerEditorDraw(), CG_Text_PaintChar(), CG_Text_PaintChar_Ext(), CG_TileClearBox(), Text_PaintChar(), Text_PaintCharExt(), UI_DrawHandlePic(), UI_DrawLoadPanel(), UI_DrawMapPreview(), UI_DrawTopBottom(), UI_FillRect(), and UI_Init().
void trap_R_DrawStretchPicGradient (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float * gradientColor, int gradientType)
trap_R_DrawStretchPicGradient
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] gradientColor
[in] gradientType
Definition at line 950 of file cg_syscalls.c.
void trap_R_Finish (void)
Sync rendering.
Definition at line 1924 of file cg_syscalls.c.
qhandle_t trap_R_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
trap_R_GetShaderFromModel
Parameters
[in] modelid
[in] surfnum
[in] withlightmap
Returns
Definition at line 750 of file cg_syscalls.c.
Referenced by CG_AddFragment(), CG_Explode(), and CG_Rubble().
qboolean trap_R_GetSkinModel (qhandle_t skinid, const char * type, char * name)
trap_R_GetSkinModel
Parameters
[in] skinid
[in] type
[out] name
Returns
Definition at line 738 of file cg_syscalls.c.
Referenced by CG_RegisterCharacter().
int trap_R_GetTextureId (const char * name)
trap_R_GetTextureId
Parameters
[in] name
Returns
Definition at line 1916 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
qboolean trap_R_inPVS (const vec3_t p1, const vec3_t p2)
trap_R_inPVS
Parameters
[in] p1
[in] p2
Returns
Definition at line 1852 of file cg_syscalls.c.
Referenced by CG_AddScriptSpeakers(), CG_Coronas(), CG_DrawMiscGamemodels(), CG_GetLocation(), CG_RenderLocations(), and CG_RenderScriptSpeakers().
int trap_R_LerpTag (orientation_t * tag, const refEntity_t * refent, const char * tagName, int startIndex)
trap_R_LerpTag
Parameters
[in] tag
[in] refent
[in] tagName
[in] startIndex
Returns
Definition at line 987 of file cg_syscalls.c.
Referenced by CG_CalcMoveSpeeds(), CG_GetOriginForTag(), CG_GetTag(), CG_GetWeaponTag(), CG_Player(), CG_PositionEntityOnTag(), and CG_PositionRotatedEntityOnTag().
qboolean trap_R_LoadDynamicShader (const char * shadername, const char * shadertext)
Dynamic shaders.
Parameters
[in] shadername
[in] shadertext
Returns
Definition at line 1893 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics().
void trap_R_LoadWorldMap (const char * mapname)
trap_R_LoadWorldMap
Parameters
[in] mapname
Definition at line 1839 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics(), and trap_TranslateString().
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
Parameters
[in] model
[in] mins
[in] maxs
Definition at line 974 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead(), CG_Item(), CG_LoadHudMenu(), CG_RegisterGraphics(), CG_TouchTriggerPrediction(), SP_misc_gamemodel(), and UI_Init().
void trap_R_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t * points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
trap_R_ProjectDecal
Parameters
[in] hShader
[in] numPoints
[in] points
[in] projection
[in] color
[in] lifeTime
[in] fadeTime
Definition at line 462 of file cg_syscalls.c.
Referenced by CG_Bullet(), CG_Effect(), CG_FragmentBounceMark(), CG_GibPlayer(), CG_ImpactMark(), CG_MissileHitWall(), and CG_MissileHitWallSmall().
void trap_R_RegisterFont (const char * fontName, int pointSize, void * font)
trap_R_RegisterFont
Parameters
[in] fontName
[in] pointSize
[in] font
Definition at line 1819 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
qhandle_t trap_R_RegisterModel (const char * name)
trap_R_RegisterModel
Parameters
[in] name
Returns
Definition at line 1774 of file cg_syscalls.c.
Referenced by BG_RAG_ParseAnimation(), BG_RAG_ParseAnimFile(), CG_AddTestModel(), CG_ConfigStringModified(), CG_LoadHudMenu(), CG_ParseGibModels(), CG_RegisterAcc(), CG_RegisterCharacter(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RegisterSounds(), CG_RW_ParseClient(), CG_RW_ParseModModel(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLinkPart(), CG_SetupCabinets(), CG_TestModel_f(), G_RegisterCharacter(), SP_misc_gamemodel(), SP_worldspawn(), and UI_Init().
qhandle_t trap_R_RegisterShader (const char * name)
trap_R_RegisterShader
Parameters
[in] name
Returns
Definition at line 1796 of file cg_syscalls.c.
Referenced by CG_ActivateEditSoundMode(), CG_ClearParticles(), CG_ConfigStringModified(), CG_Effect(), CG_EffectParse(), CG_Init(), CG_InitFlameChunks(), CG_ParseVoiceChats(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RW_ParseModModel(), and trap_TranslateString().
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
trap_R_RegisterShaderNoMip
Parameters
[in] name
Returns
Definition at line 1807 of file cg_syscalls.c.
Referenced by Asset_Parse(), AssetCache(), BG_PanelButtonsSetup(), CG_AssetCache(), CG_ConfigStringModified(), CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_DrawInformation(), CG_Init(), CG_InitPMGraphics(), CG_LoadHudMenu(), CG_LoadRankIcons(), CG_MapVoteList_Draw(), CG_RegisterGraphics(), CG_RegisterPlayerClasses(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), UI_BuildServerDisplayList(), UI_DrawCampaignMapPreview(), UI_DrawCampaignPreview(), UI_DrawClanLogo(), UI_DrawMapPreview(), UI_DrawMissionBriefingMap(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_FeederItemImage(), UI_FeederSelection(), UI_Init(), and WM_DrawObjectives().
qhandle_t trap_R_RegisterSkin (const char * name)
trap_R_RegisterSkin
Parameters
[in] name
Returns
Definition at line 1785 of file cg_syscalls.c.
Referenced by CG_ConfigStringModified(), CG_RegisterAcc(), CG_RegisterCharacter(), CG_RegisterGraphics(), CG_RW_ParseClient(), CG_RW_ParseViewType(), and CG_RW_ParseWeaponLinkPart().
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
trap_R_RemapShader
Parameters
[in] oldShader
[in] newShader
[in] timeOffset
Definition at line 998 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics(), CG_ServerCommand(), and CG_ShaderStateChanged().
void trap_R_RenderScene (const refdef_t * fd)
trap_R_RenderScene
Parameters
[in] fd
Definition at line 869 of file cg_syscalls.c.
Referenced by CG_DrawActive(), CG_DrawPlayerHead(), CG_DrawSkyBoxPortal(), CG_LoadHudMenu(), and UI_Init().
void trap_R_RenderToTexture (int textureid, int x, int y, int w, int h)
Render to texture.
Parameters
[in] textureid
[in] x
[in] y
[in] w
[in] h
Definition at line 1906 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
void trap_R_RestoreViewParms (void)
trap_R_RestoreViewParms
Definition at line 885 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
void trap_R_SaveViewParms (void)
trap_R_SaveViewParms
Definition at line 877 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
void trap_R_SetColor (const float * rgba)
trap_R_SetColor
Parameters
[in] rgba
Definition at line 894 of file cg_syscalls.c.
Referenced by _UI_DrawRect(), BG_PanelButtonsRender_Img(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Draw2D(), CG_DrawBreathBar(), CG_DrawCenterString(), CG_DrawConnectScreen(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawFireTeamOverlay(), CG_DrawFlag(), CG_DrawFlashFire(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawLimboMessage(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), CG_DrawPicShadowed(), CG_DrawPlayerHealthBar(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRect(), CG_DrawRect_FixedBorder(), CG_DrawStaminaBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawWeapRecharge(), CG_FillRect(), CG_Init(), CG_LimboPanel_Draw(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_MapVoteList_Draw(), CG_SpeakerEditorDraw(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), Text_Paint_Ext(), Text_Paint_Limit(), Text_PaintWithCursor_Ext(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawCrosshair(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_FillRect(), UI_Init(), UI_Refresh(), and WM_TeamScoreboard().
void trap_R_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
trap_R_SetFog
Parameters
[in] fogvar
[in] var1
[in] var2
[in] r
[in] g
[in] b
[in] density
Definition at line 846 of file cg_syscalls.c.
Referenced by CG_MapRestart(), CG_ParseFog(), CG_ParseSkyBox(), and CG_Respawn().
void trap_R_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
trap_R_SetGlobalFog
Parameters
[in] restore
[in] duration
[in] r
[in] g
[in] b
[in] depthForOpaque
Definition at line 860 of file cg_syscalls.c.
Referenced by CG_ParseGlobalFog().
int trap_RealTime (qtime_t * qtime)
trap_RealTime
Parameters
[out] qtime
Returns
Parameters
[in] qtime
Returns
Definition at line 1420 of file cg_syscalls.c.
Referenced by CG_currentTime_f(), CG_DrawLocalTime(), CG_DrawTimersAlt(), CG_dumpStats(), CG_generateFilename(), CG_GetRealTime(), CG_scores_cmd(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DebugCloseSkillLog(), G_DebugOpenSkillLog(), and UI_StartServerRefresh().
void trap_RemoveCommand (const char * cmdName)
Although this trap is not actually used anywhere in baseq3 game source, a reasonable assumption, based on function name and parameters, is that this trap removes a command name from the list of command completions. That is, the inverse of trap_AddCommand().
Unknown: case sensitivity (i.e. if capitalization matters for string matching)
Parameters
[in] cmdName command name
Definition at line 272 of file cg_syscalls.c.
Referenced by CG_InitConsoleCommands().
void trap_S_AddLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int volume, int soundTime)
trap_S_AddLoopingSound
Parameters
[in] origin
[in] velocity
[in] sfx
[in] volume
[in] soundTime
Note
Volume was previously removed from CG_S_ADDLOOPINGSOUND. I added 'range'
Definition at line 602 of file cg_syscalls.c.
Referenced by CG_AddFragment(), CG_AddPlayerWeapon(), CG_DrawFlashFire(), CG_EntityEffects(), CG_Missile(), CG_RenderSmokeGrenadeSmoke(), CG_UnderwaterSounds(), and CG_UpdateFlamethrowerSounds().
void trap_S_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int range, int volume, int soundTime)
trap_S_AddRealLoopingSound
Parameters
[in] origin
[in] velocity
[in] sfx
[in] range
[in] volume
[in] soundTime
Definition at line 616 of file cg_syscalls.c.
Referenced by CG_EntityEffects(), and CG_PlayScriptSpeaker().
void trap_S_ClearLoopingSounds (void)
trap_S_ClearLoopingSounds
Definition at line 578 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame(), CG_Init(), and CG_MapRestart().
void trap_S_ClearSounds (qboolean killmusic)
trap_S_ClearSounds
Parameters
[in] killmusic
Definition at line 587 of file cg_syscalls.c.
Referenced by CG_Init(), and CG_MapRestart().
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
Parameters
[in] targetvol
[in] time
[in] stopsounds
Definition at line 712 of file cg_syscalls.c.
Referenced by CG_Init(), CG_ServerCommand(), and UI_SetActiveMenu().
void trap_S_FadeBackgroundTrack (float targetvol, int time, int num)
trap_S_FadeBackgroundTrack
Parameters
[in] targetvol
[in] time
[in] num
Note
yes, i know. fadebackground coming in, fadestreaming going out. will have to see where functionality leads...
'num' is '0' if it's music, '1' if it's "all streaming sounds"
Parameters
[in] targetvol
[in] time
[in] num
Definition at line 701 of file cg_syscalls.c.
Referenced by CG_EventHandling(), and CG_ServerCommand().
int trap_S_GetCurrentSoundTime (void)
For timing looped sounds.
Returns
Definition at line 676 of file cg_syscalls.c.
Referenced by CG_EntityEffects(), and CG_PlayScriptSpeaker().
int trap_S_GetSoundLength (sfxHandle_t sfx)
trap_S_GetSoundLength
Parameters
[in] sfx
Returns
Definition at line 667 of file cg_syscalls.c.
Referenced by CG_SoundPickOldestRandomSound().
int trap_S_GetVoiceAmplitude (int entityNum)
Talking animations.
Parameters
[in] entityNum
Returns
Definition at line 645 of file cg_syscalls.c.
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
trap_S_RegisterSound
Todo:
: unique debug macros
Parameters
[in] sample
[in] compressed
Returns
Parameters
[in] sample
[in] compressed
Returns
Definition at line 1763 of file cg_syscalls.c.
Referenced by Asset_Parse(), CG_ConfigStringModified(), CG_CustomSound(), CG_Debriefing_Startup(), CG_EntityEvent(), CG_GetSoundFx(), CG_LoadHudMenu(), CG_ParseVoiceChats(), CG_PrecacheFXSounds(), CG_RegisterGameSounds(), CG_RegisterGraphics(), CG_RegisterItemSounds(), CG_RegisterSounds(), CG_RW_ParseClient(), CG_RW_ParseWeaponSound(), CG_SoundPickOldestRandomSound(), CG_SoundScriptPrecache(), CG_SpeakerEditor_NoiseEditFinish(), SP_worldspawn(), and UI_Init().
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
trap_S_Respatialize
Parameters
[in] entityNum
[in] origin
[in] axis
[in] inwater
Definition at line 657 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame().
void trap_S_StartBackgroundTrack (const char * intro, const char * loop, int fadeupTime)
trap_S_StartBackgroundTrack
Parameters
[in] intro
[in] loop
[in] fadeupTime
Definition at line 687 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), CG_QueueMusic(), CG_ServerCommand(), CG_StartMusic(), and UI_Init().
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
Parameters
[in] sfx
[in] channelNum
Note
127 Default volume always for the moment
Parameters
[in] sfx
[in] channelNum
Definition at line 570 of file cg_syscalls.c.
Referenced by CG_CheckLocalSounds(), CG_Debriefing_Startup(), CG_DrawPlayerWeaponIcon(), CG_DrawWarmup(), CG_LoadHudMenu(), CG_ParseWolfinfo(), CG_PlayGlobalSound(), CG_PlayScriptSpeaker(), CG_PlayVoiceChat(), and UI_Init().
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
Starts a sound.
Parameters
[in] origin position or NULL for position of player entity (see entityNum)
[in] entityNum
[in] entchannel
[in] sfx
Definition at line 482 of file cg_syscalls.c.
Referenced by CG_AddLightstyle(), CG_CheckLocalSounds(), CG_Effect(), CG_EntityEvent(), CG_Explodef(), CG_FireWeapon(), CG_FragmentBounceSound(), CG_MissileHitWallSmall(), CG_Obituary(), CG_PlayGlobalSound(), CG_PMItemBigSound(), CG_PyroSmokeTrail(), CG_RubbleFx(), CG_SoundPickOldestRandomSound(), and CG_Speaker().
void trap_S_StartSoundEx (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags)
trap_S_StartSoundEx
Parameters
[in] origin
[in] entityNum
[in] entchannel
[in] sfx
[in] flags
Definition at line 532 of file cg_syscalls.c.
Referenced by CG_EntityEvent(), CG_FireWeapon(), and CG_MissileHitWall().
void trap_S_StartSoundExVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags, int volume)
trap_S_StartSoundExVControl
Parameters
[in] origin
[in] entityNum
[in] entchannel
[in] sfx
[in] flags
[in] volume
Definition at line 558 of file cg_syscalls.c.
Referenced by CG_EntityEvent().
void trap_S_StartSoundVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int volume)
trap_S_StartSoundVControl
Parameters
[in] origin
[in] entityNum
[in] entchannel
[in] sfx
[in] volume
Definition at line 507 of file cg_syscalls.c.
Referenced by CG_EntityEvent(), CG_FragmentBounceSound(), CG_MissileHitWall(), and CG_PlayScriptSpeaker().
int trap_S_StartStreamingSound (const char * intro, const char * loop, int entnum, int channel, int attenuation)
trap_S_StartStreamingSound
Parameters
[in] intro
[in] loop
[in] entnum
[in] channel
[in] attenuation
Returns
Definition at line 726 of file cg_syscalls.c.
Referenced by CG_SoundPickOldestRandomSound().
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
Definition at line 1410 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
void trap_S_StopStreamingSound (int entityNum)
trap_S_StopStreamingSound
Parameters
[in] entityNum
Definition at line 625 of file cg_syscalls.c.
Referenced by CG_EventHandling(), and CG_LimboPanel_BriefingButton_KeyDown().
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
trap_S_UpdateEntityPosition
Parameters
[in] entityNum
[in] origin
Definition at line 635 of file cg_syscalls.c.
Referenced by CG_SetEntitySoundPosition().
void trap_SendClientCommand (const char * s)
trap_SendClientCommand
Parameters
[in] s
Definition at line 281 of file cg_syscalls.c.
Referenced by CG_Class_f(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_InfoRequests(), CG_Debriefing_ReadyButton_KeyDown(), CG_DrawDemoRecording(), CG_dumpStats(), CG_dumpStats_f(), CG_EventHandling(), CG_FireteamCheckExecKey(), CG_ForceTapOut_f(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_RequestWeaponStats(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SpawnPointButton_KeyDown(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_KeyDown(), CG_ReadHuds_f(), CG_ScoresDown_f(), CG_ServerCommand(), CG_SpawnpointsCheckExecKey(), CG_StatsDown_f(), and CG_topshotsDown_f().
void trap_SendConsoleCommand (const char * text)
trap_SendConsoleCommand
Parameters
[in] text
Definition at line 249 of file cg_syscalls.c.
Referenced by _et_trap_SendConsoleCommand(), CG_AddViewWeapon(), CG_AltWeapon_f(), CG_autoRecord_f(), CG_autoScreenShot_f(), CG_BuddyVoiceChat_f(), CG_CommandCentreSpawnPointClick(), CG_DemoClick(), CG_DemoControlButtonDown(), CG_DrawIntermission(), CG_execFile(), CG_FinishWeaponChange(), CG_FireteamCheckExecKey(), CG_FTSayPlayerClass_f(), CG_MessageSend_f(), CG_Respawn(), CG_SayPlayerClass_f(), CG_TeamVoiceChat_f(), CG_TransitionPlayerState(), CG_UpdateCvars(), CG_VoiceChat_f(), CG_vstrDown_f(), CG_vstrUp_f(), CheckExitRules(), CheckWolfMP(), ExitLevel(), G_Campaign_v(), G_configSet(), G_Gametype_v(), G_InitGame(), G_Kick_v(), G_LogExit(), G_Map_v(), G_NextCampaign_v(), G_Nextmap_v(), G_ParseCampaigns(), G_ParseSettings(), G_readyMatchState(), G_RestartCampaign_v(), G_UpdateCvars(), G_verifyMatchState(), G_voteSetVoteString(), G_Warmupfire_v(), ETInterface::InterfaceSendMessage(), Svcmd_Campaign_f(), Svcmd_ListIp_f(), Svcmd_ResetMatch_f(), and vmMain().
qboolean trap_SendMessage (char * buf, int buflen)
Binary message channel.
Parameters
[out] buf
[in] buflen
Returns
result
Definition at line 1873 of file cg_syscalls.c.
void trap_SetClientLerpOrigin (float x, float y, float z)
trap_SetClientLerpOrigin
Parameters
[in] x
[in] y
[in] z
Definition at line 1191 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame().
void trap_SetUserCmdValue (int stateValue, int flags, float sensitivityScale, int mpIdentClient)
trap_SetUserCmdValue
Parameters
[in] stateValue
[in] flags
[in] sensitivityScale
[in] mpIdentClient
Definition at line 1180 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame().
void trap_SnapVector (float * v)
trap_SnapVector
Parameters
[out] v
[in] v
Definition at line 1429 of file cg_syscalls.c.
Referenced by G_LinkDebris().
void trap_TranslateString (const char * string, char * buf)
trap_TranslateString
Parameters
[in] string
[out] buf
Definition at line 1564 of file cg_syscalls.c.
Referenced by CG_TranslateString(), Item_Multi_Setting(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), UI_BuildServerDisplayList(), UI_Campaign_f(), UI_DrawKeyBindStatus(), UI_DrawServerRefreshDate(), UI_Init(), UI_ListCampaigns_f(), UI_ListFavourites_f(), UI_LoadPanel_RenderHeaderText(), UI_LoadPanel_RenderLoadingText(), UI_OwnerDrawWidth(), UI_RemoveAllFavourites_f(), UI_RunMenuScript(), UI_SetActiveMenu(), and UI_StopServerRefresh().
void trap_UI_ClosePopup (const char * arg0)
trap_UI_ClosePopup
Parameters
arg0 - unused
Note
TODO: this function is empty and is NEVER used
Definition at line 1523 of file cg_syscalls.c.
void trap_UI_Popup (int arg0)
trap_UI_Popup
Parameters
[in] arg0
Definition at line 1512 of file cg_syscalls.c.
Referenced by CG_ClassMenu_f(), CG_EventHandling(), CG_MessageMode_f(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickMessage_f(), CG_ServerCommand(), CG_SetInitialSnapshot(), and CG_TeamMenu_f().
void trap_UpdateScreen (void)
trap_UpdateScreen
Definition at line 289 of file cg_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
Variable Documentation
const char* aMonths[12]
Definition at line 813 of file cg_consolecmds.c.
Referenced by CG_currentTime_f(), and CG_scores_cmd().
vmCvar_t authLevel
Definition at line 226 of file cg_main.c.
Referenced by CG_ParseServerinfo().
qboolean ccInitial
Definition at line 41 of file cg_commandmap.c.
Referenced by CG_EventHandling(), and CG_SetInitialSnapshot().
vmCvar_t cf_wstats
Definition at line 228 of file cg_main.c.
Referenced by CG_createStatsWindow().
vmCvar_t cf_wtopshots
Definition at line 229 of file cg_main.c.
Referenced by CG_createTopShotsWindow().
cg_t cg
Definition at line 119 of file cg_main.c.
Referenced by CG_ActivateEditSoundMode(), CG_AddAtmosphericEffects(), CG_AddBloodElements(), CG_AddBloodTrails(), CG_AddBufferedSoundScript(), CG_AddBufferedVoiceChat(), CG_AddCEntity(), CG_AddCEntity_Filter(), CG_AddDebris(), CG_AddDebrisElements(), CG_AddDebrisElementsExtended(), CG_AddEmitter(), CG_AddEntityToTag(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFlameChunks(), CG_AddFlameSpriteToScene(), CG_AddFlameToScene(), CG_AddFragment(), CG_AddFuseSparkElements(), CG_AddLagometerFrameInfo(), CG_AddLagometerSnapshotInfo(), CG_AddLightstyle(), CG_AddLinkedEntity(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddMoveScaleFade(), CG_AddMovingTracer(), CG_AddOnScreenText(), CG_AddPacketEntities(), CG_AddPainTwitch(), CG_AddParticles(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddPMItem(), CG_AddPMItemBig(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddScriptSpeakers(), CG_AddSmokeJunc(), CG_AddSmokeSprites(), CG_AddSparkElements(), CG_AddSparkJunc(), CG_AddSparks(), CG_AddSpawnVarToken(), CG_AddSpriteExplosion(), CG_addString(), CG_AddTestModel(), CG_AddToTeamChat(), CG_AddTrailJunc(), CG_AddTrails(), CG_AddTrailToScene(), CG_AddViewWeapon(), CG_AdjustPositionForMover(), CG_AdjustZoomVal(), CG_AltWeapon_f(), CG_AnimPlayerConditions(), CG_AttachBitsToTank(), CG_AutomapExpandDown_f(), CG_AutomapExpandUp_f(), CG_Beam_2(), CG_Bleed(), CG_BloodTrail(), CG_BreathPuffs(), CG_BubbleTrail(), CG_BuddyVoiceChat_f(), CG_BuildLocationString(), CG_BuildSelectedFirteamString(), CG_BuildSolidList(), CG_Bullet(), CG_BulletImpact(), CG_CalcEntityLerpPositions(), CG_CalcFov(), CG_CalcMuzzlePoint(), CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_CalculateWeaponPosition(), CG_CalcViewValues(), CG_CalcVrect(), CG_CenterPrint(), CG_ChargeTimesChanged(), CG_CheckCanSwitch(), CG_CheckEvents(), CG_CheckForCursorHints(), CG_CheckLocalSounds(), CG_CheckPlayerstateEvents(), CG_Class_f(), CG_ClassMenu_f(), CG_ClassSkillForPosition(), CG_ClearHudHeadLerpFrame(), CG_ClearLerpFrame(), CG_ClearLerpFrameRate(), CG_ClearParticles(), CG_ClearWeapLerpFrame(), CG_ClientHitboxMaxZ(), CG_ClientInfoForPosition(), CG_ClipMoveToEntities(), CG_ColorForHealth(), CG_CommandCentreSpawnPointClick(), CG_CompasMoveLocationCalc(), CG_ConfigStringModified(), CG_ConsoleCommand(), CG_ContinueWeaponAnim(), CG_corona(), CG_Corona(), CG_Coronas(), CG_CountFireteamsByTeam(), CG_CountPlayersNF(), CG_CountPlayersSF(), CG_createMOTDWindow(), CG_createStatsWindow(), CG_createTopShotsWindow(), CG_DamageBlendBlob(), CG_DamageFeedback(), CG_DeActivateEditSoundMode(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatButton_KeyDown(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_GetSelectedClientInfo(), CG_Debriefing_InfoRequests(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_ReadyButton_Draw(), CG_Debriefing_ReadyButton_KeyDown(), CG_Debriefing_Startup(), CG_DebriefingPlayerList_Draw(), CG_DebriefingTitle_Draw(), CG_Debris(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoControlButtonDown(), CG_DemoControlButtonRender(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DisguiseMapCheck(), CG_Draw2D(), CG_DrawActive(), CG_DrawActiveFrame(), CG_DrawActiveHud(), CG_DrawAutoMap(), CG_DrawBreathBar(), CG_DrawBulletTracer(), CG_DrawCenterString(), CG_DrawCompassIcon(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawDemoRecording(), CG_DrawDisconnect(), CG_DrawExpandedAutoMap(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlashBlend(), CG_DrawFlashDamage(), CG_DrawFlashFade(), CG_DrawFlashFire(), CG_DrawFlashZoomTransition(), CG_DrawFollow(), CG_DrawGrid(), CG_DrawGunIcon(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawLagometer(), CG_DrawLandmine(), CG_DrawLimboMessage(), CG_DrawLivesLeft(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMineMarkerFlag(), CG_DrawMiscGamemodels(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNewCompass(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), CG_DrawOnScreenLabels(), CG_DrawOverlays(), CG_DrawPing(), CG_DrawPlayerHead(), CG_DrawPlayerHealth(), CG_DrawPlayerHealthBar(), CG_DrawPlayerStatus(), CG_DrawPlayerStatusHead(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScopedReticle(), CG_DrawScoreboard(), CG_DrawSkills(), CG_DrawSkyBoxPortal(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawStaminaBar(), CG_DrawStatsDebug(), CG_DrawTeamInfo(), CG_DrawTimedMenus(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawTracer(), CG_DrawUpperRight(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeapHeat(), CG_DrawWeapRecharge(), CG_DrawWeapStability(), CG_DrawXP(), CG_DumpSpeaker_f(), CG_dumpStats_f(), CG_DynamiteTrail(), CG_EditSpeakers_f(), CG_Effect(), CG_EffectGust(), CG_EffectGustCurrent(), CG_EffectParse(), CG_EntityEffects(), CG_EntityEvent(), CG_EntOnFire(), CG_EventHandling(), CG_Explodef(), CG_Fade(), CG_Fade_f(), CG_FadeColor(), CG_FinishWeaponChange(), CG_FireFlameChunks(), CG_FireteamCheckExecKey(), CG_FireTeamForPosition(), CG_FireteamHasClass(), CG_FireTeamPlayerForPosition(), CG_Fireteams_MenuText_Draw(), CG_FireWeapon(), CG_FragmentBounceMark(), CG_FTSayPlayerClass_f(), CG_GameStatsDraw(), CG_General(), CG_getBindKeyName(), CG_GetPMItemText(), CG_GetSecondaryWeapon(), CG_GetTag(), CG_GetTeamColor(), CG_GetWeaponTag(), CG_GetWindVector(), CG_GrenadeTrail(), CG_initStrings(), CG_inSVCVARBackupList(), CG_InterpolateEntityPosition(), CG_InterpolatePlayerState(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_Item(), CG_ItemPickup(), CG_KeyEvent(), CG_keyOff_f(), CG_keyOn_f(), CG_KickAngles(), CG_LastWeaponUsed_f(), CG_LaunchGib(), CG_Letterbox(), CG_LimboMenu_f(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_ClassCount(), CG_LimboPanel_ClassIsDisabled(), CG_LimboPanel_Draw(), CG_LimboPanel_GetRealTeam(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_RealWeaponIsDisabled(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderMedal(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_Setup(), CG_LimboPanel_TeamCount(), CG_LimboPanel_TeamIsDisabled(), CG_LimboPanel_TeamIsFull(), CG_LimboPanel_WeaponCount(), CG_LimboPanel_WeaponPanel(), CG_ListSpawnPoints_f(), CG_LoadingString(), CG_LoadPanel_LoadingBarText(), CG_LoadPanel_RenderCampaignPins(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_MakeExplosion(), CG_MapRestart(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_Draw(), CG_MapVote_VoteButton_KeyDown(), CG_MapVoteList_Draw(), CG_MapVoteList_KeyDown(), CG_MessageMode_f(), CG_MG42EFX(), CG_Missile(), CG_MissileHitWall(), CG_ModifySpeaker_f(), CG_MortarEFX(), CG_MortarImpact(), CG_MortarMiss(), CG_MouseEvent(), CG_MoveFlameChunk(), CG_MovePlane(), CG_Mover(), CG_Mover_PostProcess(), CG_NewClientInfo(), CG_NextWeap(), CG_NextWeapon_f(), CG_Obituary(), CG_ObjectivePrint(), CG_objectivesDown_f(), CG_ObjectivesDraw(), CG_objectivesUp_f(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_OilSlickRemove(), CG_OutOfAmmoChange(), CG_PainEvent(), CG_PanzerFaustEjectBrass(), CG_ParseEntitiesFromString(), CG_ParseFireteams(), CG_ParseMapEntity(), CG_ParseScore(), CG_ParseScreenFade(), CG_ParseSkyBox(), CG_ParseSpawns(), CG_ParseSpawnVars(), CG_ParseWarmup(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBloodCloud(), CG_ParticleBubble(), CG_ParticleBulletDebris(), CG_ParticleCheckVisible(), CG_ParticleDirtBulletDebris_Core(), CG_ParticleDust(), CG_ParticleExplosion(), CG_ParticleGenerate(), CG_ParticleImpactSmokePuff(), CG_ParticleImpactSmokePuffExtended(), CG_ParticleRender(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), CG_ParticleSparks(), CG_PlayBufferedVoiceChats(), CG_Player(), CG_PlayerAmmoValue(), CG_PlayerAngles(), CG_PlayerFloatSprite(), CG_PlayerNFFromPos(), CG_PlayerSFFromPos(), CG_PlayerShadow(), CG_PlayerSprites(), CG_PlayGlobalSound(), CG_PlayPMItemSound(), CG_PlayVoiceChat(), CG_PMItemBigSound(), CG_PredictLean(), CG_PredictPlayerState(), CG_PrevWeap(), CG_PrevWeapon_f(), CG_printWindow(), CG_PriorityCenterPrint(), CG_ProcessCvars(), CG_ProcessEntity(), CG_ProcessSnapshots(), CG_Prop(), CG_PyroSmokeTrail(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickFireteams_f(), CG_QuickSpawnpoint_f(), CG_RailTrail2(), CG_ReadHuds_f(), CG_ReadNextSnapshot(), CG_ReflectVelocity(), CG_removeStrings(), CG_RenderLocations(), CG_RenderScriptSpeakers(), CG_RenderSmokeGrenadeSmoke(), CG_ResetEntity(), CG_ResetPlayerEntity(), CG_Respawn(), CG_RocketTrail(), CG_RubbleFx(), CG_RumbleEfx(), CG_RunHudHeadLerpFrame(), CG_RunLerpFrame(), CG_RunLerpFrameRate(), CG_RunLerpFrameRateCorpse(), CG_RunWeapLerpFrame(), CG_SayPlayerClass_f(), CG_ScanForCrosshairDyna(), CG_ScanForCrosshairEntity(), CG_ScanForCrosshairMine(), CG_ScoresDown_f(), CG_ScoresUp_f(), CG_ScreenFade(), CG_SelectBuddy_f(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetInitialSnapshot(), CG_SetLerpFrameAnimationRate(), CG_SetLerpFrameAnimationRateCorpse(), CG_SetNextSnap(), CG_SetupFrustum(), CG_SetViewanglesForSpeakerEditor(), CG_SetWeaponCrosshair_f(), CG_ShakeCamera(), CG_Shard(), CG_ShardJunk(), CG_ShowHelp_Off(), CG_ShowHelp_On(), CG_Smoker(), CG_SortedFireTeamPlayerForPosition(), CG_SortFireTeam(), CG_SoundPickOldestRandomSound(), CG_SparklerSparks(), CG_Spawnpoints_MenuText_Draw(), CG_SpawnpointsCheckExecKey(), CG_SpawnString(), CG_SpawnTracer(), CG_Speaker(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditorDraw(), CG_SpeakerEditorMouseMove_Handling(), CG_StartShakeCamera(), CG_StartWeaponAnim(), CG_StatsDebugAddText(), CG_StatsDown_f(), CG_StatsUp_f(), CG_StepOffset(), CG_SwingAngles(), CG_TeamRestrictionsChanged(), CG_TeamVoiceChat_f(), CG_TestGun_f(), CG_TestModel_f(), CG_TestModelNextFrame_f(), CG_TestModelNextSkin_f(), CG_TestModelPrevFrame_f(), CG_TestModelPrevSkin_f(), CG_TileClear(), CG_TimerReset_f(), CG_TimerSet_f(), CG_topshotsDown_f(), CG_TopShotsDraw(), CG_topshotsUp_f(), CG_TouchTriggerPrediction(), CG_TransformAutomapEntity(), CG_TransformToCommandMapCoord(), CG_TransitionEntity(), CG_TransitionPlayerState(), CG_TransitionSnapshot(), CG_Trap(), CG_UnderwaterSounds(), CG_UndoSpeaker_f(), CG_UpdateBufferedSoundScripts(), CG_UpdateFlamethrowerSounds(), CG_UpdatePMLists(), CG_UpdateSvCvars(), CG_Viewpos_f(), CG_VoiceChatLocal(), CG_WaterRipple(), CG_WeaponAnimation(), CG_WeaponBank_f(), CG_WeaponFireRecoil(), CG_WeaponHasAmmo(), CG_WeaponSelectable(), CG_windowAlloc(), CG_windowCleanup(), CG_windowDraw(), CG_windowFree(), CG_windowInit(), CG_WorldCoordToScreenCoordFloat(), CG_wstatsParse_cmd(), CG_Zoom(), CG_ZoomIn_f(), CG_ZoomOut_f(), CG_ZoomRequired(), CG_ZoomSway(), PmoveSingle(), SP_misc_gamemodel(), SP_trigger_objective_info(), SP_worldspawn(), trap_GetCurrentSnapshotNumber(), trap_S_StartSound(), trap_S_StartSoundEx(), trap_S_StartSoundVControl(), vmMain(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
vmCvar_t cg_altHud
Definition at line 315 of file cg_main.c.
Referenced by CG_DrawAutoMap(), CG_DrawNewCompass(), CG_DrawUpperRight(), and CG_SetHud().
vmCvar_t cg_altHudFlags
Definition at line 316 of file cg_main.c.
Referenced by CG_DrawGlobalHud(), CG_DrawPlayerStats(), and CG_DrawUpperRight().
vmCvar_t cg_animSpeed
Definition at line 151 of file cg_main.c.
Referenced by CG_RunLerpFrame(), CG_RunLerpFrameRate(), and CG_RunWeapLerpFrame().
vmCvar_t cg_announcer
Definition at line 304 of file cg_main.c.
Referenced by CG_DrawWarmup(), and CG_ParseWolfinfo().
vmCvar_t cg_antilag
Definition at line 222 of file cg_main.c.
Referenced by CG_ParseServerinfo().
vmCvar_t cg_atmosphericEffects
Definition at line 284 of file cg_main.c.
Referenced by CG_AddAtmosphericEffects().
vmCvar_t cg_autoAction
Definition at line 231 of file cg_main.c.
Referenced by CG_DrawActiveFrame(), CG_DrawIntermission(), and CG_DrawWarmup().
vmCvar_t cg_autoactivate
Definition at line 195 of file cg_main.c.
vmCvar_t cg_automapZoom
Definition at line 324 of file cg_main.c.
Referenced by CG_AdjustAutomapZoom(), CG_DrawAutoMap(), and CG_TransformAutomapEntity().
vmCvar_t cg_autoReload
Definition at line 232 of file cg_main.c.
Referenced by CG_MapRestart(), and CG_Respawn().
vmCvar_t cg_autoswitch
Definition at line 174 of file cg_main.c.
Referenced by CG_ItemPickup().
vmCvar_t cg_blood
Definition at line 192 of file cg_main.c.
Referenced by CG_Bleed(), CG_BloodTrail(), CG_Bullet(), CG_GibPlayer(), and CG_LaunchGib().
vmCvar_t cg_bloodDamageBlend
Definition at line 233 of file cg_main.c.
Referenced by CG_DamageBlendBlob().
vmCvar_t cg_bloodFlash
Definition at line 234 of file cg_main.c.
Referenced by CG_DrawFlashDamage().
vmCvar_t cg_bloodTime
Definition at line 204 of file cg_main.c.
Referenced by CG_Bullet(), CG_FragmentBounceMark(), and CG_GibPlayer().
vmCvar_t cg_bluelimbotime
Definition at line 220 of file cg_main.c.
Referenced by CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_DrawFollow(), CG_DrawMapEntity(), and CG_ParseServerinfo().
vmCvar_t cg_bobpitch
Definition at line 126 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_bobroll
Definition at line 127 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_bobup
Definition at line 125 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_brassTime
Definition at line 162 of file cg_main.c.
Referenced by CG_FireWeapon(), CG_MachineGunEjectBrass(), and CG_PanzerFaustEjectBrass().
vmCvar_t cg_buildScript
Definition at line 188 of file cg_main.c.
Referenced by CG_ParseVoiceChats(), and CG_ServerCommand().
vmCvar_t cg_centertime
Definition at line 124 of file cg_main.c.
Referenced by CG_DrawCenterString().
vmCvar_t cg_complaintPopUp
Definition at line 235 of file cg_main.c.
Referenced by CG_DrawVote(), and CG_ServerCommand().
vmCvar_t cg_coronafardist
Definition at line 189 of file cg_main.c.
Referenced by CG_Corona(), and CG_Coronas().
vmCvar_t cg_coronas
Definition at line 190 of file cg_main.c.
Referenced by CG_Corona(), and CG_Coronas().
vmCvar_t cg_countryflags
GeoIP.
Definition at line 313 of file cg_main.c.
Referenced by WM_DrawClientScore(), and WM_DrawClientScore_Small().
vmCvar_t cg_crosshairAlpha
Definition at line 236 of file cg_main.c.
vmCvar_t cg_crosshairAlphaAlt
Definition at line 237 of file cg_main.c.
vmCvar_t cg_crosshairColor
Definition at line 238 of file cg_main.c.
vmCvar_t cg_crosshairColorAlt
Definition at line 239 of file cg_main.c.
vmCvar_t cg_crosshairHealth
Definition at line 146 of file cg_main.c.
Referenced by CG_DrawCrosshair().
vmCvar_t cg_crosshairPulse
Definition at line 240 of file cg_main.c.
Referenced by CG_DrawCrosshair().
vmCvar_t cg_crosshairSize
Definition at line 143 of file cg_main.c.
Referenced by CG_DrawCrosshair(), and CG_SpeakerEditorDraw().
vmCvar_t cg_crosshairX
Definition at line 144 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawNoShootIcon(), and CG_SpeakerEditorDraw().
vmCvar_t cg_crosshairY
Definition at line 145 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawNoShootIcon(), and CG_SpeakerEditorDraw().
vmCvar_t cg_cursorHints
Definition at line 165 of file cg_main.c.
Referenced by CG_DrawCursorhint().
vmCvar_t cg_cycleAllWeaps
Definition at line 141 of file cg_main.c.
Referenced by CG_NextWeap(), and CG_PrevWeap().
vmCvar_t cg_debugAnim
Definition at line 154 of file cg_main.c.
Referenced by CG_RunLerpFrame(), CG_RunLerpFrameRate(), CG_RunLerpFrameRateCorpse(), CG_RunWeapLerpFrame(), CG_SetLerpFrameAnimation(), CG_SetLerpFrameAnimationRate(), CG_SetLerpFrameAnimationRateCorpse(), CG_SetWeapLerpFrameAnimation(), and CG_WeaponAnimation().
vmCvar_t cg_debugEvents
Definition at line 156 of file cg_main.c.
Referenced by CG_EntityEvent().
vmCvar_t cg_debugPlayerHitboxes
Definition at line 341 of file cg_main.c.
Referenced by CG_Player().
vmCvar_t cg_debugPosition
Definition at line 155 of file cg_main.c.
Referenced by CG_ResetPlayerEntity().
vmCvar_t cg_debugSkills
Definition at line 290 of file cg_main.c.
Referenced by CG_DrawStatsDebug(), and CG_StatsDebugAddText().
vmCvar_t cg_descriptiveText
Definition at line 217 of file cg_main.c.
Referenced by CG_DrawLimboMessage(), CG_DrawScoreboard(), and CG_DrawSpectatorMessage().
vmCvar_t cg_draw2D
Definition at line 131 of file cg_main.c.
Referenced by CG_Draw2D(), and CG_DrawFlashFade().
vmCvar_t cg_drawCompass
Definition at line 214 of file cg_main.c.
Referenced by CG_DrawAutoMap(), and CG_DrawNewCompass().
vmCvar_t cg_drawCrosshair
Definition at line 136 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawCrosshairNames(), and CG_SpeakerEditorDraw().
vmCvar_t cg_drawCrosshairInfo
Definition at line 137 of file cg_main.c.
Referenced by CG_DrawCrosshairNames().
vmCvar_t cg_drawCrosshairNames
Definition at line 138 of file cg_main.c.
Referenced by CG_DrawCrosshairNames(), and CG_PlayerSprites().
vmCvar_t cg_drawCrosshairPickups
Definition at line 139 of file cg_main.c.
Referenced by CG_Item().
vmCvar_t cg_drawFireteamOverlay
Definition at line 291 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawFPS
Definition at line 132 of file cg_main.c.
Referenced by CG_DrawFPS(), and CG_DrawUpperRight().
vmCvar_t cg_drawGun
Definition at line 164 of file cg_main.c.
Referenced by CG_AddViewWeapon(), and CG_CalcMuzzlePoint().
vmCvar_t cg_drawNotifyText
Definition at line 215 of file cg_main.c.
vmCvar_t cg_drawPing
Definition at line 133 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawReinforcementTime
Definition at line 241 of file cg_main.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
vmCvar_t cg_drawRoundTimer
Definition at line 286 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawSmallPopupIcons
Definition at line 292 of file cg_main.c.
Referenced by CG_DrawPMItems(), and CG_GetObituaryIcon().
vmCvar_t cg_drawSnapshot
Definition at line 135 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawspeed
Definition at line 350 of file cg_main.c.
Referenced by CG_DrawSpeed(), and CG_DrawUpperRight().
vmCvar_t cg_drawSpreadScale
Definition at line 152 of file cg_main.c.
Referenced by CG_DrawWeapStability().
vmCvar_t cg_drawStatus
Definition at line 150 of file cg_main.c.
Referenced by CG_Draw2D().
vmCvar_t cg_drawTime
Definition at line 326 of file cg_main.c.
Referenced by CG_DrawLocalTime(), CG_DrawTimersAlt(), and CG_DrawUpperRight().
vmCvar_t cg_drawWeaponIconFlash
Definition at line 242 of file cg_main.c.
Referenced by CG_DrawGunIcon().
centity_t cg_entities[MAX_GENTITIES]
Definition at line 121 of file cg_main.c.
Referenced by CG_AddEntityToTag(), CG_AddFlameToScene(), CG_AddLinkedEntity(), CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AdjustPositionForMover(), CG_AttachBitsToTank(), CG_BuildSolidList(), CG_Bullet(), CG_CalcMuzzlePoint(), CG_CalcViewValues(), CG_CalcVrect(), CG_CheckForCursorHints(), CG_CheckPlayerstateEvents(), CG_DisguiseMapCheck(), CG_DrawCrosshairNames(), CG_DrawFireTeamOverlay(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawNewCompass(), CG_DrawPowerUps(), CG_EntityEffects(), CG_EntityEvent(), CG_GetBleedOrigin(), CG_GetTag(), CG_GetWeaponTag(), CG_LoadClientInfo(), CG_MachineGunEjectBrass(), CG_MG42EFX(), CG_Mover_PostProcess(), CG_ParseTagConnect(), CG_Player(), CG_PlayerAmmoValue(), CG_PlayerAngles(), CG_PlayVoiceChat(), CG_PredictPlayerState(), CG_ScanForCrosshairEntity(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_SpawnTracer(), CG_TransitionPlayerState(), CG_TransitionSnapshot(), CG_ZoomIn_f(), and CG_ZoomOut_f().
vmCvar_t cg_errorDecay
Definition at line 157 of file cg_main.c.
Referenced by CG_CalcViewValues(), and CG_PredictPlayerState().
vmCvar_t cg_fireteamLatchedClass
Definition at line 318 of file cg_main.c.
Referenced by CG_DrawFireTeamOverlay().
vmCvar_t cg_fontScaleCN
Definition at line 337 of file cg_main.c.
Referenced by CG_DrawCrosshairNames().
vmCvar_t cg_fontScaleCP
Definition at line 336 of file cg_main.c.
Referenced by CG_Class_f(), CG_demoAviFPSDraw(), CG_DrawWarmup(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_LimboPanel_SendSetupMsg(), CG_NewClientInfo(), CG_Obituary(), CG_ServerCommand(), CG_SpawnpointsCheckExecKey(), and CG_TouchTriggerPrediction().
vmCvar_t cg_fontScaleSP
Definition at line 335 of file cg_main.c.
Referenced by CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawLimboMessage(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawScoreboard(), CG_DrawSpectatorMessage(), CG_DrawVote(), CG_removeStrings(), CG_windowDraw(), and CG_windowNormalizeOnText().
vmCvar_t cg_fontScaleTP
Definition at line 334 of file cg_main.c.
Referenced by CG_DrawDisconnect(), CG_DrawLagometer(), CG_DrawSpectator(), CG_DrawWarmup(), and CG_ServerCommand().
vmCvar_t cg_fov
Definition at line 175 of file cg_main.c.
Referenced by CG_AddViewWeapon(), CG_CalcFov(), and CG_DrawSkyBoxPortal().
vmCvar_t cg_gameType
Definition at line 203 of file cg_main.c.
Referenced by CG_Debriefing_FindWinningTeam(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Maps_KeyDown(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_DebriefingTitle_Draw(), CG_DrawLivesLeft(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_RenderCounter_NumRollers(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanelRenderText_NoLMS(), CG_LimboPanelRenderText_SkillsText(), CG_ParseServerinfo(), CG_TeamDebriefing_CalcXP(), WM_DrawClientScore(), WM_DrawClientScore_Small(), and WM_TeamScoreboard().
vmCvar_t cg_gibs
Definition at line 130 of file cg_main.c.
Referenced by CG_LaunchGib().
vmCvar_t cg_graphicObituaries
Definition at line 332 of file cg_main.c.
Referenced by CG_Obituary().
vmCvar_t cg_gun_frame
Definition at line 166 of file cg_main.c.
Referenced by CG_AddViewWeapon().
vmCvar_t cg_gun_x
Definition at line 167 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_gun_y
Definition at line 168 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_gun_z
Definition at line 169 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_hitSounds
Definition at line 305 of file cg_main.c.
Referenced by CG_CheckLocalSounds().
vmCvar_t cg_instanttapout
Definition at line 288 of file cg_main.c.
Referenced by CG_ServerCommand().
vmCvar_t cg_lagometer
Definition at line 134 of file cg_main.c.
Referenced by CG_DrawUpperRight().
vmCvar_t cg_letterbox
Definition at line 163 of file cg_main.c.
Referenced by CG_Letterbox().
vmCvar_t cg_locations
Definition at line 306 of file cg_main.c.
Referenced by CG_BuildLocationString(), CG_DrawActiveFrame(), CG_DrawFireTeamOverlay(), and CG_GetPMItemText().
markPoly_t cg_markPolys[MAX_MARK_POLYS]
Definition at line 46 of file cg_marks.c.
Referenced by CG_InitMarkPolys().
vmCvar_t cg_markTime
Definition at line 161 of file cg_main.c.
Referenced by CG_AddMarks(), CG_BigExplosionImpact(), CG_BulletImpact(), CG_DynamiteExplosionImpact(), CG_Effect(), CG_MapMortarImpact(), CG_MeleeImpact(), CG_MissileHitWallSmall(), and CG_SmallExplosionImpact().
vmCvar_t cg_movespeed
vmCvar_t cg_muzzleFlash
Definition at line 176 of file cg_main.c.
Referenced by CG_FireWeapon().
vmCvar_t cg_noAmmoAutoSwitch
Definition at line 243 of file cg_main.c.
Referenced by CG_EntityEvent().
vmCvar_t cg_noPlayerAnims
Definition at line 159 of file cg_main.c.
Referenced by CG_PlayerAnimation(), and CG_WeaponAnimation().
vmCvar_t cg_nopredict
Definition at line 158 of file cg_main.c.
Referenced by CG_DrawLagometer(), CG_EntityEvent(), CG_PredictPlayerState(), and CG_TransitionSnapshot().
vmCvar_t cg_optimizePrediction
Definition at line 340 of file cg_main.c.
Referenced by CG_PredictPlayerState().
vmCvar_t cg_paused
Definition at line 191 of file cg_main.c.
Referenced by CG_Draw2D(), CG_DrawScoreboard(), and CG_SpawnTrailJunc().
vmCvar_t cg_popupBigFilter
Definition at line 331 of file cg_main.c.
Referenced by CG_NewClientInfo().
vmCvar_t cg_popupFadeTime
Definition at line 328 of file cg_main.c.
Referenced by CG_DrawPMItems(), CG_DrawPMItemsBig(), and CG_UpdatePMLists().
vmCvar_t cg_popupFilter
Definition at line 330 of file cg_main.c.
Referenced by CG_CheckPMItemFilter().
vmCvar_t cg_popupStayTime
Definition at line 329 of file cg_main.c.
Referenced by CG_DrawPMItems(), CG_DrawPMItemsBig(), and CG_UpdatePMLists().
vmCvar_t cg_predictItems
Definition at line 193 of file cg_main.c.
vmCvar_t cg_printObjectiveInfo
Definition at line 244 of file cg_main.c.
Referenced by CG_ServerCommand().
vmCvar_t cg_quickchat
Definition at line 348 of file cg_main.c.
Referenced by CG_AltWeapon_f().
vmCvar_t cg_quickMessageAlt
Definition at line 216 of file cg_main.c.
Referenced by CG_ClassMenu_f(), CG_DrawFireteamsByTeam(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), CG_QuickFireteamMessage_f(), CG_QuickMessage_f(), and CG_TeamMenu_f().
vmCvar_t cg_railTrailTime
Definition at line 153 of file cg_main.c.
Referenced by CG_RailTrail2().
vmCvar_t cg_rconPassword
Definition at line 282 of file cg_main.c.
vmCvar_t cg_recording_statusline
Definition at line 302 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t cg_redlimbotime
Definition at line 219 of file cg_main.c.
Referenced by CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_DrawFollow(), CG_DrawMapEntity(), and CG_ParseServerinfo().
vmCvar_t cg_refereePassword
Definition at line 283 of file cg_main.c.
vmCvar_t cg_shadows
Definition at line 129 of file cg_main.c.
Referenced by CG_Player(), CG_PlayerShadow(), CG_PlayerSplash(), and Script_ConditionalScript().
vmCvar_t cg_showmiss
Definition at line 160 of file cg_main.c.
Referenced by CG_MapRestart(), CG_PredictionOk(), and CG_PredictPlayerState().
vmCvar_t cg_simpleItems
Definition at line 322 of file cg_main.c.
Referenced by CG_Item().
vmCvar_t cg_skybox
Definition at line 205 of file cg_main.c.
Referenced by CG_DrawSkyBoxPortal().
vmCvar_t cg_spawnTimer_period
Definition at line 309 of file cg_main.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
vmCvar_t cg_spawnTimer_set
Definition at line 308 of file cg_main.c.
Referenced by CG_DrawTimerNormal(), and CG_DrawTimersAlt().
vmCvar_t cg_stats
Definition at line 187 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_swingSpeed
Definition at line 128 of file cg_main.c.
Referenced by CG_PlayerAngles().
vmCvar_t cg_teamChatHeight
Definition at line 186 of file cg_main.c.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
vmCvar_t cg_teamChatsOnly
Definition at line 147 of file cg_main.c.
Referenced by CG_ServerCommand(), and CG_VoiceChatLocal().
vmCvar_t cg_teamChatTime
Definition at line 185 of file cg_main.c.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
vmCvar_t cg_thirdPerson
Definition at line 179 of file cg_main.c.
Referenced by CG_DemoClick(), CG_DrawActiveFrame(), CG_FireFlameChunks(), and CG_OffsetThirdPersonView().
vmCvar_t cg_thirdPersonAngle
Definition at line 181 of file cg_main.c.
Referenced by CG_DemoClick(), and CG_OffsetThirdPersonView().
vmCvar_t cg_thirdPersonRange
Definition at line 180 of file cg_main.c.
Referenced by CG_DemoClick(), and CG_OffsetThirdPersonView().
vmCvar_t cg_timescale
Definition at line 210 of file cg_main.c.
Referenced by CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawActiveFrame(), and CG_DrawDisconnect().
vmCvar_t cg_tracerChance
Definition at line 170 of file cg_main.c.
Referenced by CG_Bullet().
vmCvar_t cg_tracerLength
Definition at line 172 of file cg_main.c.
Referenced by CG_AddMovingTracer(), CG_SpawnTracer(), and CG_Tracer().
vmCvar_t cg_tracers
Definition at line 317 of file cg_main.c.
Referenced by CG_Bullet(), and CG_DrawBulletTracer().
vmCvar_t cg_tracerSpeed
Definition at line 173 of file cg_main.c.
Referenced by CG_SpawnTracer().
vmCvar_t cg_tracerWidth
Definition at line 171 of file cg_main.c.
Referenced by CG_DrawTracer().
vmCvar_t cg_uinfo
Definition at line 248 of file cg_main.c.
vmCvar_t cg_useWeapsForZoom
Definition at line 142 of file cg_main.c.
Referenced by CG_ZoomRequired().
vmCvar_t cg_visualEffects
turn invisible (0) / visible (1) visual effect (i.e airstrike plane, debris ...)
Definition at line 352 of file cg_main.c.
Referenced by CG_AddDebris(), CG_AddLocalEntities(), and CG_MovePlane().
vmCvar_t cg_voiceChats
Definition at line 148 of file cg_main.c.
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_voiceSpriteTime
Definition at line 212 of file cg_main.c.
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_voiceText
Definition at line 149 of file cg_main.c.
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_weapaltReloads
Definition at line 320 of file cg_main.c.
Referenced by CG_AltWeapon_f().
vmCvar_t cg_weaponCycleDelay
Definition at line 140 of file cg_main.c.
Referenced by CG_AltWeapon_f(), and CG_CheckCanSwitch().
weaponInfo_t cg_weapons[MAX_WEAPONS]
Definition at line 122 of file cg_main.c.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_CalculateWeaponPosition(), CG_DrawFireTeamOverlay(), CG_DrawPlayerWeaponIcon(), CG_EntityEvent(), CG_FireWeapon(), CG_GetObituaryIcon(), CG_Item(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_MachineGunEjectBrass(), CG_Missile(), CG_MissileHitWall(), CG_PanzerFaustEjectBrass(), CG_Player(), CG_RegisterWeapon(), and CG_WeaponFireRecoil().
vmCvar_t cg_wolfparticles
Definition at line 201 of file cg_main.c.
Referenced by CG_AddParticleToScene().
vmCvar_t cg_zoomDefaultSniper
Definition at line 178 of file cg_main.c.
Referenced by CG_Zoom().
vmCvar_t cg_zoomStepSniper
Definition at line 177 of file cg_main.c.
Referenced by CG_ZoomIn_f(), and CG_ZoomOut_f().
displayContextDef_t cgDC
Definition at line 38 of file cg_main.c.
Referenced by CG_CommandCentreSpawnPointClick(), CG_Debriefing_Draw(), CG_DemoControlButtonDown(), CG_Draw2D(), CG_DrawActiveFrame(), CG_DrawDemoControls(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), CG_LimboPanel_Draw(), CG_LimboPanel_KeyHandling(), CG_ProcessSnapshots(), CG_SpeakerEditorDraw(), CG_Text_Height(), CG_Text_Paint(), CG_Text_PaintWithCursor(), CG_Text_PaintWithCursor_Ext(), CG_Text_Width(), and CG_windowDraw().
cgs_t cgs
Definition at line 120 of file cg_main.c.
Referenced by Ccg_Is43Screen(), Ccg_WideX(), Ccg_WideXoffset(), CG_AddBloodElements(), CG_AddDebris(), CG_AddDebrisElements(), CG_AddEmitter(), CG_AddFlameToScene(), CG_AddFragment(), CG_AddFuseSparkElements(), CG_AddLagometerSnapshotInfo(), CG_AddLineToScene(), CG_AddOnScreenText(), CG_AddPlayerWeapon(), CG_AddPMItemBig(), CG_AddRefEntityWithPowerups(), CG_AddSmokeSprites(), CG_AddSparks(), CG_AddToNotify(), CG_AddToTeamChat(), CG_AddTrailToScene(), CG_AddViewWeapon(), CG_AdjustFrom640(), CG_AttachBitsToTank(), CG_AutomapExpandDown_f(), CG_AutomapExpandUp_f(), CG_AutomapZoomIn_f(), CG_AutomapZoomOut_f(), CG_Beam(), CG_Beam_2(), CG_BigExplosionImpact(), CG_BloodTrail(), CG_BreathPuffs(), CG_BubbleTrail(), CG_BuddyVoiceChat_f(), CG_BuildLocationString(), CG_BuildSelectedFirteamString(), CG_Bullet(), CG_BulletImpact(), CG_CalcFov(), CG_CalculateReinfTime_Float(), CG_CalculateShoutcasterReinfTime(), CG_CalcViewValues(), CG_CalcVrect(), CG_CharacterForClientinfo(), CG_CharacterForPlayerstate(), CG_ChatPanel_Setup(), CG_CheckForExistingAnimModelInfo(), CG_CheckLocalSounds(), CG_Class_f(), CG_ClassMenu_f(), CG_ClientInfoForPosition(), CG_CommandCentreSpawnPointClick(), CG_CommandMap_DrawHighlightText(), CG_CompasMoveLocationCalc(), CG_ConfigStringModified(), CG_Constructible(), CG_corona(), CG_Coronas(), CG_CountFireteamsByTeam(), CG_CountPlayersNF(), CG_CountPlayersSF(), CG_CPM_f(), CG_CurLayerForZ(), CG_DamageBlendBlob(), CG_Debriefing_Awards_Draw(), CG_Debriefing_CalcCampaignProgress(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatButton_Draw(), CG_Debriefing_ChatButton_KeyDown(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_Draw(), CG_Debriefing_FindWinningTeam(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_GetNextWeaponStat(), CG_Debriefing_GetSelectedClientInfo(), CG_Debriefing_InfoRequests(), CG_Debriefing_KeyEvent(), CG_Debriefing_Maps_Draw(), CG_Debriefing_Maps_KeyDown(), CG_Debriefing_Mission_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_MouseEvent(), CG_Debriefing_NextButton_KeyDown(), CG_Debriefing_ParseAwards(), CG_Debriefing_ParsePlayerKillsDeaths(), CG_Debriefing_ParsePlayerTime(), CG_Debriefing_ParseWeaponAccuracies(), CG_Debriefing_ParseWeaponStats(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerMedals_Draw(), CG_Debriefing_PlayerName_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_ReadyButton_Draw(), CG_Debriefing_Scrollbar_KeyDown(), CG_Debriefing_ScrollGetCount(), CG_Debriefing_ScrollGetOffset(), CG_Debriefing_ScrollSetOffset(), CG_Debriefing_Shutdown(), CG_Debriefing_Startup(), CG_Debriefing_TeamSkillHeaders_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_Debriefing_VoteButton_Draw(), CG_Debriefing_VoteButton_KeyDown(), CG_DebriefingPlayerList_Draw(), CG_DebriefingPlayerList_KeyDown(), CG_DebriefingPlayerWeaponStats_Draw(), CG_DebriefingTitle_Draw(), CG_DebriefingXPHeader_Draw(), CG_Debrieing_SetSelectedClient(), CG_Debris(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DescriptionForCampaign(), CG_DisguiseMapCheck(), CG_Draw2D(), CG_DrawActiveFrame(), CG_DrawAmmoCount(), CG_DrawAutoMap(), CG_DrawBinocReticle(), CG_DrawBorder(), CG_DrawBottom_NoScale(), CG_DrawBreathBar(), CG_DrawCenterString(), CG_DrawConnectScreen(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawDemoRecording(), CG_DrawDisconnect(), CG_DrawExpandedAutoMap(), CG_DrawField(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlag(), CG_DrawFlashBlend(), CG_DrawFlashFade(), CG_DrawFlashFire(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawGlobalHud(), CG_DrawGrid(), CG_DrawGunIcon(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawLagometer(), CG_DrawLandmine(), CG_DrawLimboMessage(), CG_DrawLivesLeft(), CG_DrawLocalTime(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMiscGamemodels(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNewCompass(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), CG_DrawOnScreenLabels(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPlayerHealthBar(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawPlayerStats(), CG_DrawPlayerStatusHead(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScopedReticle(), CG_DrawScoreboard(), CG_DrawSides(), CG_DrawSides_NoScale(), CG_DrawSkillBar(), CG_DrawSkills(), CG_DrawSkyBoxPortal(), CG_DrawSnapshot(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawStaminaBar(), CG_DrawStatsDebug(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawTopBottom(), CG_DrawTopBottom_NoScale(), CG_DrawTracer(), CG_DrawUpperRight(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeapRecharge(), CG_DrawXP(), CG_dumpStats(), CG_dumpStats_f(), CG_DynamiteExplosionImpact(), CG_EditSpeakers_f(), CG_Effect(), CG_EffectParse(), CG_EntityEffects(), CG_EntityEvent(), CG_EventHandling(), CG_ExecuteNewServerCommands(), CG_Explode(), CG_Explodef(), CG_Explosive(), CG_Fade(), CG_FillRect(), CG_FireteamCheckExecKey(), CG_FireTeamForPosition(), CG_FireteamHasClass(), CG_FireTeamPlayerForPosition(), CG_Fireteams_MenuText_Draw(), CG_Fireteams_MenuTitleText_Draw(), CG_FireWeapon(), CG_FragmentBounceMark(), CG_FragmentBounceSound(), CG_FTSayPlayerClass_f(), CG_GameStatsDraw(), CG_General(), CG_GetBleedOrigin(), CG_GetLocation(), CG_GetLocationMsg(), CG_GetObituaryIcon(), CG_GetPMItemIcon(), CG_GetPMItemText(), CG_GetSecondaryWeapon(), CG_GetTag(), CG_GetWeaponTag(), CG_GibPlayer(), CG_GrenadeTrail(), CG_InitConsoleCommands(), CG_InitPMGraphics(), CG_IsOnFireteam(), CG_IsWeaponDisabled(), CG_Item(), CG_ItemPickup(), CG_KeyEvent(), CG_Letterbox(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_ClassCount(), CG_LimboPanel_ClassIsDisabled(), CG_LimboPanel_Draw(), CG_LimboPanel_Filter_Draw(), CG_LimboPanel_Filter_KeyDown(), CG_LimboPanel_GetClass(), CG_LimboPanel_GetRealTeam(), CG_LimboPanel_GetSelectedWeapon(), CG_LimboPanel_GetSpawnPoint(), CG_LimboPanel_GetTeam(), CG_LimboPanel_Init(), CG_LimboPanel_IsValidSelectedWeapon(), CG_LimboPanel_MinusButton_KeyDown(), CG_LimboPanel_ObjectiveText_KeyDown(), CG_LimboPanel_PlusButton_KeyDown(), CG_LimboPanel_RealWeaponIsDisabled(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCommandMap(), CG_LimboPanel_RenderCounter(), CG_LimboPanel_RenderCounter_GetShaders(), CG_LimboPanel_RenderCounter_ValueForButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderLight(), CG_LimboPanel_RenderMedal(), CG_LimboPanel_RenderObjectiveBack(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderSkillIcon(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_RequestWeaponStats(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SetDefaultWeapon(), CG_LimboPanel_SetSelectedWeaponNum(), CG_LimboPanel_Setup(), CG_LimboPanel_SpawnPointButton_Draw(), CG_LimboPanel_SpawnPointButton_KeyDown(), CG_LimboPanel_TeamButton_KeyDown(), CG_LimboPanel_TeamCount(), CG_LimboPanel_TeamIsDisabled(), CG_LimboPanel_TeamIsFull(), CG_LimboPanel_WeaponCount(), CG_LimboPanel_WeaponLights(), CG_LimboPanel_WeaponLights_KeyDown(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LimboPanel_WeaponPanel_KeyUp(), CG_LoadLocations(), CG_LoadPanel_DrawPin(), CG_LoadPanel_RenderCampaignNameText(), CG_LoadPanel_RenderCampaignPins(), CG_LoadPanel_RenderCampaignTypeText(), CG_LoadPanel_RenderMissionDescriptionText(), CG_LocateArena(), CG_LocateCampaign(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_MapMortarImpact(), CG_MapRestart(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_Draw(), CG_MapVote_VoteButton_KeyDown(), CG_MapVoteList_Draw(), CG_MapVoteList_KeyDown(), CG_MessageMode_f(), CG_MG42EFX(), CG_Missile(), CG_MissileHitWall(), CG_MissileHitWallSmall(), CG_MortarEFX(), CG_MouseEvent(), CG_MovePlane(), CG_Mover(), CG_NameForCampaign(), CG_NewClientInfo(), CG_NewParticleArea(), CG_Obituary(), CG_ObjectivePrint(), CG_objectivesDown_f(), CG_ObjectivesDraw(), CG_objectivesUp_f(), CG_PanelButtonsRender_Button_Ext(), CG_PanelButtonsRender_Window_Ext(), CG_PanzerFaustEjectBrass(), CG_ParseAnimationFiles(), CG_parseBestShotsStats_cmd(), CG_ParseFireteams(), CG_ParseLegacyinfo(), CG_ParseMapEntity(), CG_parseMapVoteListInfo(), CG_parseMapVoteTally(), CG_ParseOIDInfo(), CG_ParsePortalPos(), CG_ParseReinforcementTimes(), CG_ParseScore(), CG_ParseScreenFade(), CG_ParseServerinfo(), CG_ParseServerVersionInfo(), CG_ParseSpawns(), CG_ParseSysteminfo(), CG_ParseTeamInfo(), CG_ParseTeamXPs(), CG_parseTopShotsStats_cmd(), CG_ParseWarmup(), CG_ParseWeaponStats(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_ParseWolfinfo(), CG_ParticleBloodCloud(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleSmoke(), CG_ParticleSparks(), CG_Player(), CG_PlayerAmmoValue(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PlayerCanPickupWeapon(), CG_PlayerNFFromPos(), CG_PlayerSFFromPos(), CG_PlayerShadow(), CG_PlayerSplash(), CG_PlayerSprites(), CG_PlayGlobalSound(), CG_PlayPMItemSound(), CG_PlayVoiceChat(), CG_PMItemBigSound(), CG_PredictPlayerState(), CG_printFile(), CG_PrintObjectiveInfo_f(), CG_PriorityCenterPrint(), CG_ProcessEntity(), CG_ProcessSnapshots(), CG_Prop(), CG_PyroSmokeTrail(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickFireteams_f(), CG_QuickSpawnpoint_f(), CG_RailTrail2(), CG_RandomDebris(), CG_ReadHuds_f(), CG_ReadNextSnapshot(), CG_removeStrings(), CG_RenderLocations(), CG_RenderScriptSpeakers(), CG_ResetPlayerEntity(), CG_Respawn(), CG_Rubble(), CG_RubbleFx(), CG_SaveSpeakersToScript(), CG_SayPlayerClass_f(), CG_ScanForCrosshairEntity(), CG_scores_cmd(), CG_ScoresDown_f(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetEntitySoundPosition(), CG_SetInitialSnapshot(), CG_SetLerpFrameAnimationRateCorpse(), CG_ShaderStateChanged(), CG_Shard(), CG_ShardJunk(), CG_SmallExplosionImpact(), CG_Smoker(), CG_SortedFireTeamPlayerForPosition(), CG_SortFireTeam(), CG_SortPlayersByXP(), CG_SoundLoadSoundFiles(), CG_Spawnpoints_MenuText_Draw(), CG_SpawnTracer(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditorDraw(), CG_SpeakerEditorMouseMove_Handling(), CG_StatsDebugAddText(), CG_StatsDown_f(), CG_StatsUp_f(), CG_TeamDebriefing_CalcXP(), CG_TeamDebriefingTeamSkillXP_Draw(), CG_TeamVoiceChat_f(), CG_TileClear(), CG_TimerReset_f(), CG_TimerSet_f(), CG_ToggleAutomap_f(), CG_topshotsDown_f(), CG_TopShotsDraw(), CG_topshotsParse_cmd(), CG_topshotsUp_f(), CG_TouchTriggerPrediction(), CG_Trap(), CG_UnderwaterSounds(), CG_UpdateFlamethrowerSounds(), CG_VoiceChatListForClient(), CG_VoiceChatLocal(), CG_WeaponAnimation(), CG_windowDraw(), CG_windowNormalizeOnText(), CG_Zoom(), SP_misc_gamemodel(), SP_worldspawn(), trap_S_StartSound(), trap_S_StartSoundEx(), trap_S_StartSoundVControl(), vmMain(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
vmCvar_t cl_demofilename
Definition at line 296 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t cl_demooffset
Definition at line 297 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t cl_demorecording
Definition at line 295 of file cg_main.c.
Referenced by CG_DrawActiveFrame(), and CG_DrawDemoRecording().
vmCvar_t cl_wavefilename
Definition at line 300 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t cl_waveoffset
Definition at line 301 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t cl_waverecording
Definition at line 299 of file cg_main.c.
Referenced by CG_DrawDemoRecording().
vmCvar_t demo_avifpsF1
Definition at line 250 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF2
Definition at line 251 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF3
Definition at line 252 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF4
Definition at line 253 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_avifpsF5
Definition at line 254 of file cg_main.c.
Referenced by CG_DemoClick().
vmCvar_t demo_drawTimeScale
Definition at line 255 of file cg_main.c.
Referenced by CG_demoTimescaleDraw().
vmCvar_t demo_infoWindow
Definition at line 256 of file cg_main.c.
Referenced by CG_keyOn_f(), and CG_SetInitialSnapshot().
vmCvar_t developer
Definition at line 224 of file cg_main.c.
Referenced by CG_CalcFov(), and Com_DPrintf().
qboolean initparticles
Definition at line 143 of file cg_particles.c.
Referenced by CG_AddParticles(), and CG_ClearParticles().
vmCvar_t int_cl_maxpackets
Definition at line 276 of file cg_main.c.
vmCvar_t int_cl_timenudge
Definition at line 277 of file cg_main.c.
vmCvar_t int_m_pitch
Definition at line 278 of file cg_main.c.
vmCvar_t int_sensitivity
Definition at line 279 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
vmCvar_t int_ui_blackout
Definition at line 280 of file cg_main.c.
Referenced by CG_DrawFlashFade().
lagometer_t lagometer
Definition at line 2096 of file cg_local.h.
Referenced by CG_AddLagometerFrameInfo(), CG_AddLagometerSnapshotInfo(), and CG_DrawLagometer().
vmCvar_t pmove_fixed
Definition at line 197 of file cg_main.c.
Referenced by CG_PredictPlayerState(), and ClientThink_real().
vmCvar_t pmove_msec
Definition at line 198 of file cg_main.c.
Referenced by CG_PredictPlayerState(), ClientThink_real(), ClientUserinfoChanged(), and DoClientThinks().
rankicon_t rankicons[NUM_EXPERIENCE_LEVELS][2][2]
Definition at line 37 of file cg_statsranksmedals.c.
Referenced by CG_Debriefing_PlayerRank_Draw(), CG_DemoClick(), CG_DrawCrosshairNames(), CG_DrawFollow(), CG_DrawPlayerHead(), CG_NewClientInfo(), CG_Player(), WM_DrawClientScore(), and WM_DrawClientScore_Small().
qboolean resetmaxspeed
Definition at line 1182 of file cg_consolecmds.c.
Referenced by CG_DrawSpeed(), and CG_ResetMaxSpeed_f().