ET: Legacy: src/cgame/cg_fireteamoverlay.c File Reference
cg_fireteamoverlay.c File Reference
#include "cg_local.h"
Macros
#define FONT_HEADER &cgs.media.limboFont1
#define FONT_TEXT &cgs.media.limboFont2
#define FT_BAR_YSPACING 2.f
#define FT_BAR_HEIGHT 10.f
#define MIN_BORDER_DISTANCE 10
Functions
int QDECL CG_SortFireTeam (const void *a, const void *b)
CG_SortFireTeam.
void CG_SortClientFireteam ()
Sorts client's fireteam by leader then rank.
void CG_ParseFireteams ()
Parses fireteam servercommand.
fireteamData_t * CG_IsOnFireteam (int clientNum)
Fireteam that the specified client is a part of.
fireteamData_t * CG_IsOnSameFireteam (int clientNum, int clientNum2)
Fireteam that both specified clients are on, if they both are on the same team.
fireteamData_t * CG_IsFireTeamLeader (int clientNum)
Fireteam that specified client is leader of, or NULL if none.
clientInfo_t * CG_ClientInfoForPosition (int pos, int max)
Client, not on a fireteam, not sorted, but on your team.
fireteamData_t * CG_FireTeamForPosition (int pos, int max)
Fireteam, that's on your same team.
clientInfo_t * CG_FireTeamPlayerForPosition (int pos, int max)
Client, not sorted by rank, on CLIENT'S fireteam.
clientInfo_t * CG_SortedFireTeamPlayerForPosition (int pos)
Client, sorted by rank, on CLIENT'S fireteam.
void CG_DrawFireTeamOverlay (rectDef_t *rect)
Draw FireTeam overlay.
qboolean CG_FireteamHasClass (int classnum, qboolean selectedonly)
CG_FireteamHasClass.
const char * CG_BuildSelectedFirteamString (void)
CG_BuildSelectedFirteamString.
Variables
static int sortedFireTeamClients [MAX_CLIENTS]
static vec4_t FT_bg = { 0.16f, 0.2f, 0.17f, 0.8f }
static vec4_t FT_bg2 = { 0.0f, 0.0f, 0.0f, 0.3f }
static vec4_t FT_border = { 0.5f, 0.5f, 0.5f, 0.5f }
static vec4_t FT_noselect = { 0.0f, 0.0f, 0.0f, 0.1f }
static vec4_t FT_select = { 0.5f, 0.5f, 0.2f, 0.3f }
static vec4_t FT_text = { 0.6f, 0.6f, 0.6f, 1.0f }
Macro Definition Documentation
#define FONT_HEADER &cgs.media.limboFont1
Definition at line 47 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
#define FONT_TEXT &cgs.media.limboFont2
Definition at line 48 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
#define FT_BAR_HEIGHT 10.f
Definition at line 372 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
#define FT_BAR_YSPACING 2.f
Definition at line 371 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
#define MIN_BORDER_DISTANCE 10
Definition at line 374 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
Function Documentation
const char* CG_BuildSelectedFirteamString (void)
CG_BuildSelectedFirteamString.
Returns
Definition at line 829 of file cg_fireteamoverlay.c.
Referenced by CG_AltWeapon_f(), CG_BuddyVoiceChat_f(), CG_FireteamCheckExecKey(), and CG_FTSayPlayerClass_f().
clientInfo_t* CG_ClientInfoForPosition (int pos, int max)
Client, not on a fireteam, not sorted, but on your team.
Parameters
[in] pos
[in] max
Returns
Client information
Note
Unused
Definition at line 252 of file cg_fireteamoverlay.c.
void CG_DrawFireTeamOverlay (rectDef_t * rect)
Draw FireTeam overlay.
Parameters
[in] rect
Definition at line 380 of file cg_fireteamoverlay.c.
Referenced by CG_DrawUpperRight().
fireteamData_t* CG_FireTeamForPosition (int pos, int max)
Fireteam, that's on your same team.
Parameters
[in] pos
[in] max
Returns
Note
Unused
Definition at line 279 of file cg_fireteamoverlay.c.
qboolean CG_FireteamHasClass (int classnum, qboolean selectedonly)
CG_FireteamHasClass.
Parameters
[in] classnum
[in] selectedonly
Returns
Definition at line 783 of file cg_fireteamoverlay.c.
Referenced by CG_FireteamCheckExecKey(), and CG_Fireteams_MenuText_Draw().
clientInfo_t* CG_FireTeamPlayerForPosition (int pos, int max)
Client, not sorted by rank, on CLIENT'S fireteam.
Parameters
[in] pos
[in] max
Returns
Note
Unused
Definition at line 306 of file cg_fireteamoverlay.c.
fireteamData_t* CG_IsFireTeamLeader (int clientNum)
Fireteam that specified client is leader of, or NULL if none.
Parameters
[in] clientNum
Returns
Definition at line 227 of file cg_fireteamoverlay.c.
Referenced by CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), and CG_SortFireTeam().
fireteamData_t* CG_IsOnFireteam (int clientNum)
Fireteam that the specified client is a part of.
Parameters
[in] clientNum
Returns
Definition at line 197 of file cg_fireteamoverlay.c.
Referenced by CG_ClientInfoForPosition(), CG_CountPlayersNF(), CG_CountPlayersSF(), CG_Debriefing_ChatButton_KeyDown(), CG_DrawFireTeamOverlay(), CG_DrawUpperRight(), CG_FireteamCheckExecKey(), CG_FireteamHasClass(), CG_FireTeamPlayerForPosition(), CG_Fireteams_MenuText_Draw(), CG_IsFireTeamLeader(), CG_IsOnSameFireteam(), CG_MessageMode_f(), CG_PlayerNFFromPos(), CG_PlayerSFFromPos(), CG_PlayerSprites(), CG_QuickFireteams_f(), CG_SelectBuddy_f(), and CG_SortedFireTeamPlayerForPosition().
fireteamData_t* CG_IsOnSameFireteam (int clientNum, int clientNum2)
Fireteam that both specified clients are on, if they both are on the same team.
Parameters
[in] clientNum
[in] clientNum2
Returns
Definition at line 212 of file cg_fireteamoverlay.c.
Referenced by CG_DrawMapEntity(), CG_DrawNewCompass(), and CG_SortFireTeam().
void CG_ParseFireteams (void)
Parses fireteam servercommand.
Definition at line 132 of file cg_fireteamoverlay.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
void CG_SortClientFireteam (void)
Sorts client's fireteam by leader then rank.
Definition at line 111 of file cg_fireteamoverlay.c.
Referenced by CG_NewClientInfo(), and CG_ParseFireteams().
clientInfo_t* CG_SortedFireTeamPlayerForPosition (int pos)
Client, sorted by rank, on CLIENT'S fireteam.
Parameters
[in] pos
Returns
Definition at line 341 of file cg_fireteamoverlay.c.
Referenced by CG_BuildSelectedFirteamString(), CG_DrawFireTeamOverlay(), and CG_SelectBuddy_f().
int QDECL CG_SortFireTeam (const void * a, const void * b)
CG_SortFireTeam.
Parameters
[in] a
[in] b
Returns
Definition at line 56 of file cg_fireteamoverlay.c.
Referenced by CG_SortClientFireteam().
Variable Documentation
vec4_t FT_bg = { 0.16f, 0.2f, 0.17f, 0.8f } static
Definition at line 40 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
vec4_t FT_bg2 = { 0.0f, 0.0f, 0.0f, 0.3f } static
Definition at line 41 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
vec4_t FT_border = { 0.5f, 0.5f, 0.5f, 0.5f } static
Definition at line 42 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
vec4_t FT_noselect = { 0.0f, 0.0f, 0.0f, 0.1f } static
Definition at line 43 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
vec4_t FT_select = { 0.5f, 0.5f, 0.2f, 0.3f } static
Definition at line 44 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
vec4_t FT_text = { 0.6f, 0.6f, 0.6f, 1.0f } static
Definition at line 45 of file cg_fireteamoverlay.c.
Referenced by CG_DrawFireTeamOverlay().
int sortedFireTeamClients[MAX_CLIENTS] static
Definition at line 37 of file cg_fireteamoverlay.c.
Referenced by CG_SortClientFireteam(), and CG_SortedFireTeamPlayerForPosition().