ET: Legacy: src/cgame/cg_servercmds.c File Reference
cg_servercmds.c File Reference
Reliably sequenced text commands sent by the server.
#include "cg_local.h"
Data Structures
struct voiceChat_s
struct voiceChatList_s
struct bufferedVoiceChat_s
Macros
#define TEAMINFOARGS 6
#define GETVAL(x, y) if ((tmp = strchr(tmp, ' ')) == NULL) { return; } x = atoi(++tmp) / y;
#define SETSKILL(skill, string) sscanf(string, "%i,%i,%i,%i", &GetSkillTableData(skill)->skillLevels[1], &GetSkillTableData(skill)->skillLevels[2], &GetSkillTableData(skill)->skillLevels[3], &GetSkillTableData(skill)->skillLevels[4])
#define MAX_VOICEFILES 8
#define MAX_VOICEFILESIZE 32768
#define MAX_VOICECHATS 272
#define MAX_VOICESOUNDS 32
#define MAX_CHATSIZE 64
#define MAX_VOICECHATBUFFER 32
#define ENTNFO_HASH 78985
#define CS_HASH 25581
#define TINFO_HASH 65811
#define SC0_HASH 31373
#define SC1_HASH 31494
#define WEAPONSTATS_HASH 149968
#define SC_HASH 25565
#define CPM_HASH 38410
#define CP_HASH 25221
#define PRINT_HASH 67401
#define CHAT_HASH 50150
#define VCHAT_HASH 64608
#define TCHAT_HASH 64370
#define VTCHAT_HASH 78944
#define VBCHAT_HASH 76784
#define GAMECHAT_HASH 101222
#define VSCHAT_HASH 78824
#define WS_HASH 27961
#define WWS_HASH 42356
#define GSTATS_HASH 80455
#define ASTATS_HASH 79741
#define ASTATSB_HASH 91991
#define BSTATS_HASH 79860
#define BSTATSB_HASH 92110
#define WBSTATS_HASH 94678
#define RWS_HASH 41761
#define MAP_RESTART_HASH 147165
#define PORTALCAMPOS_HASH 161962
#define REMAPSHADER_HASH 144301
#define ADDTOBUILD_HASH 129971
#define SPAWNSERVER_HASH 150779
#define APPLICATION_HASH 145376
#define INVITATION_HASH 134986
#define PROPOSITION_HASH 151490
#define AFT_HASH 37819
#define AFTC_HASH 49897
#define AFTJ_HASH 50751
#define COMPLAINT_HASH 118983
#define REQFORCESPAWN_HASH 176027
#define SDBG_HASH 50109
#define IMMAPLIST_HASH 120113
#define IMVOTETALLY_HASH 150058
#define SETSPAWNPT_HASH 137482
#define IMWA_HASH 51808
#define IMWS_HASH 54004
#define IMPKD_HASH 64481
#define IMPT_HASH 53279
#define IMSR_HASH 53398
#define SR_HASH 27365
#define SRA_HASH 39102
#define MU_START_HASH 107698
#define MU_PLAY_HASH 92607
#define MU_STOP_HASH 94568
#define MU_FADE_HASH 87906
#define SND_FADE_HASH 100375
#define ROCKANDROLL_HASH 146207
Typedefs
typedef struct voiceChat_s voiceChat_t
typedef struct voiceChatList_s voiceChatList_t
typedef struct bufferedVoiceChat_s bufferedVoiceChat_t
Functions
static void CG_ParseScore (team_t team)
CG_ParseScore.
static void CG_ParseTeamInfo (void)
CG_ParseTeamInfo.
void CG_ParseServerinfo (void)
This is called explicitly when the gamestate is first received, and whenever the server updates any serverinfo flagged cvars.
static qboolean CG_inSVCVARBackupList (const char *cvar1)
CG_inSVCVARBackupList.
void CG_UpdateSvCvars (void)
CG_UpdateSvCvars.
void CG_ParseSysteminfo (void)
void CG_ParseLegacyinfo (void)
CG_ParseLegacyinfo.
static void CG_ParseWarmup (void)
CG_ParseWarmup.
void CG_ParseOIDInfo (int num)
CG_OIDInfoForEntityNum.
void CG_ParseOIDInfos (void)
CG_ParseOIDInfos.
void CG_ParseWolfinfo (void)
CG_ParseWolfinfo.
void CG_ParseSpawns (void)
CG_ParseSpawns.
static void CG_ParseScreenFade (void)
CG_ParseScreenFade.
static void CG_ParseFog (void)
CG_ParseFog.
static void CG_ParseGlobalFog (void)
CG_ParseGlobalFog.
void CG_ParseServerVersionInfo (const char *pszVersionInfo)
Parse server version info (for demo playback compatibility)
void CG_ParseReinforcementTimes (const char *pszReinfSeedString)
Parse reinforcement offsets.
void CG_SetConfigValues (void)
Called on load to set the initial values from configure strings.
void CG_ShaderStateChanged (void)
CG_ShaderStateChanged.
void CG_ChargeTimesChanged (void)
CG_ChargeTimesChanged.
void CG_TeamRestrictionsChanged (void)
CG_TeamRestrictionsChanged.
void CG_SkillLevelsChanged (void)
CG_SkillLevelsChanged.
static void CG_ConfigStringModified (void)
CG_ConfigStringModified.
static void CG_AddToTeamChat (const char *str, int clientnum)
CG_AddToTeamChat.
void CG_AddToNotify (const char *str)
static void CG_MapRestart (void)
The server has issued a map_restart, so the next snapshot is completely new and should not be interpolated to.
int CG_ParseVoiceChats (const char *filename, voiceChatList_t *voiceChatList, int maxVoiceChats)
CG_ParseVoiceChats.
void CG_LoadVoiceChats (void)
CG_LoadVoiceChats.
int CG_GetVoiceChat (voiceChatList_t *voiceChatList, const char *id, sfxHandle_t *snd, qhandle_t *sprite, char **chat)
CG_GetVoiceChat.
voiceChatList_t * CG_VoiceChatListForClient (int clientNum)
CG_VoiceChatListForClient.
void CG_PlayVoiceChat (bufferedVoiceChat_t *vchat)
CG_PlayVoiceChat.
void CG_PlayBufferedVoiceChats (void)
CG_PlayBufferedVoiceChats.
void CG_AddBufferedVoiceChat (bufferedVoiceChat_t *vchat)
CG_AddBufferedVoiceChat.
void CG_VoiceChatLocal (int mode, qboolean voiceOnly, int clientNum, int color, const char *cmd, vec3_t origin)
CG_VoiceChatLocal.
void CG_VoiceChat (int mode)
CG_VoiceChat.
static void CG_RemoveChatEscapeChar (char *text)
CG_RemoveChatEscapeChar.
const char * CG_LocalizeServerCommand (const char *buf)
Localize string sent from server.
void CG_wstatsParse_cmd (void)
CG_wstatsParse_cmd.
void CG_topshotsParse_cmd (qboolean doBest)
CG_topshotsParse_cmd.
void CG_ParseWeaponStats (void)
CG_ParseWeaponStats.
void CG_ParsePortalPos (void)
CG_ParsePortalPos.
void CG_parseWeaponStatsGS_cmd (void)
Cached stats.
void CG_parseWeaponStats_cmd (void(txt_dump)(const char *))
Client-side stat presentation.
static void CG_parseBestShotsStats_cmd (qboolean doTop, void(txt_dump)(const char *))
CG_parseBestShotsStats_cmd.
static void CG_parseTopShotsStats_cmd (qboolean doTop, void(txt_dump)(const char *))
CG_parseTopShotsStats_cmd.
static void CG_scores_cmd (void)
CG_scores_cmd.
static void CG_printFile (const char *str)
CG_printFile.
void CG_dumpStats (void)
CG_dumpStats.
static void CG_ServerCommand (void)
The string has been tokenized and can be retrieved with Cmd_Argc() / Cmd_Argv()
void CG_ExecuteNewServerCommands (int latestSequence)
Execute all of the server commands that were received along with this this snapshot.
Variables
voiceChatList_t voiceChatLists [MAX_VOICEFILES]
bufferedVoiceChat_t voiceChatBuffer [MAX_VOICECHATBUFFER]
Detailed Description
Reliably sequenced text commands sent by the server.
These are processed at snapshot transition time, so there will definately be a valid snapshot this frame.
Definition in file cg_servercmds.c.
Macro Definition Documentation
#define ADDTOBUILD_HASH 129971
Definition at line 2723 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define AFT_HASH 37819
Definition at line 2728 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define AFTC_HASH 49897
Definition at line 2729 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define AFTJ_HASH 50751
Definition at line 2730 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define APPLICATION_HASH 145376
Definition at line 2725 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define ASTATS_HASH 79741
Definition at line 2714 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define ASTATSB_HASH 91991
Definition at line 2715 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define BSTATS_HASH 79860
Definition at line 2716 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define BSTATSB_HASH 92110
Definition at line 2717 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define CHAT_HASH 50150
Definition at line 2704 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define COMPLAINT_HASH 118983
Definition at line 2731 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define CP_HASH 25221
Definition at line 2702 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define CPM_HASH 38410
Definition at line 2701 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define CS_HASH 25581
Definition at line 2695 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define ENTNFO_HASH 78985
Definition at line 2694 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define GAMECHAT_HASH 101222
Definition at line 2709 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define GETVAL (x, y) if ((tmp = strchr(tmp, ' ')) == NULL) { return; } x = atoi(++tmp) / y;
Referenced by CG_ParseReinforcementTimes().
#define GSTATS_HASH 80455
Definition at line 2713 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMMAPLIST_HASH 120113
Definition at line 2734 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMPKD_HASH 64481
Definition at line 2739 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMPT_HASH 53279
Definition at line 2740 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMSR_HASH 53398
Definition at line 2741 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMVOTETALLY_HASH 150058
Definition at line 2735 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMWA_HASH 51808
Definition at line 2737 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define IMWS_HASH 54004
Definition at line 2738 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define INVITATION_HASH 134986
Definition at line 2726 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define MAP_RESTART_HASH 147165
Definition at line 2720 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define MAX_CHATSIZE 64
Definition at line 1416 of file cg_servercmds.c.
Referenced by CG_ParseVoiceChats().
#define MAX_VOICECHATBUFFER 32
Definition at line 1640 of file cg_servercmds.c.
Referenced by CG_PlayBufferedVoiceChats().
#define MAX_VOICECHATS 272
Definition at line 1411 of file cg_servercmds.c.
Referenced by CG_LoadVoiceChats().
#define MAX_VOICEFILES 8
Definition at line 1407 of file cg_servercmds.c.
#define MAX_VOICEFILESIZE 32768
Definition at line 1410 of file cg_servercmds.c.
Referenced by CG_ParseVoiceChats().
#define MAX_VOICESOUNDS 32
Definition at line 1414 of file cg_servercmds.c.
Referenced by CG_ParseVoiceChats().
#define MU_FADE_HASH 87906
Definition at line 2747 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define MU_PLAY_HASH 92607
Definition at line 2745 of file cg_servercmds.c.
Referenced by CG_ServerCommand(), and G_Script_ScriptParse().
#define MU_START_HASH 107698
Definition at line 2744 of file cg_servercmds.c.
Referenced by CG_ServerCommand(), and G_Script_ScriptParse().
#define MU_STOP_HASH 94568
Definition at line 2746 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define PORTALCAMPOS_HASH 161962
Definition at line 2721 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define PRINT_HASH 67401
Definition at line 2703 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define PROPOSITION_HASH 151490
Definition at line 2727 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define REMAPSHADER_HASH 144301
Definition at line 2722 of file cg_servercmds.c.
Referenced by CG_ServerCommand(), and G_Script_ScriptParse().
#define REQFORCESPAWN_HASH 176027
Definition at line 2732 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define ROCKANDROLL_HASH 146207
Definition at line 2749 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define RWS_HASH 41761
Definition at line 2719 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SC0_HASH 31373
Definition at line 2697 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SC1_HASH 31494
Definition at line 2698 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SC_HASH 25565
Definition at line 2700 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SDBG_HASH 50109
Definition at line 2733 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SETSKILL (skill, string) sscanf(string, "%i,%i,%i,%i", &GetSkillTableData(skill)->skillLevels[1], &GetSkillTableData(skill)->skillLevels[2], &GetSkillTableData(skill)->skillLevels[3], &GetSkillTableData(skill)->skillLevels[4])
Definition at line 857 of file cg_servercmds.c.
Referenced by CG_SkillLevelsChanged().
#define SETSPAWNPT_HASH 137482
Definition at line 2736 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SND_FADE_HASH 100375
Definition at line 2748 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SPAWNSERVER_HASH 150779
Definition at line 2724 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SR_HASH 27365
Definition at line 2742 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define SRA_HASH 39102
Definition at line 2743 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define TCHAT_HASH 64370
Definition at line 2706 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define TEAMINFOARGS 6
Definition at line 122 of file cg_servercmds.c.
Referenced by CG_ParseTeamInfo().
#define TINFO_HASH 65811
Definition at line 2696 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define VBCHAT_HASH 76784
Definition at line 2708 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define VCHAT_HASH 64608
Definition at line 2705 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define VSCHAT_HASH 78824
Definition at line 2710 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define VTCHAT_HASH 78944
Definition at line 2707 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define WBSTATS_HASH 94678
Definition at line 2718 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define WEAPONSTATS_HASH 149968
Definition at line 2699 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define WS_HASH 27961
Definition at line 2711 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
#define WWS_HASH 42356
Definition at line 2712 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
Typedef Documentation
typedef struct bufferedVoiceChat_s bufferedVoiceChat_t
typedef struct voiceChat_s voiceChat_t
typedef struct voiceChatList_s voiceChatList_t
Function Documentation
void CG_AddBufferedVoiceChat (bufferedVoiceChat_t * vchat)
CG_AddBufferedVoiceChat.
Parameters
[in,out] vchat
Note
FIXME: Put this on a cvar to choose which to uses
Todo:
put this on a cvar to choose which to use
Definition at line 1728 of file cg_servercmds.c.
Referenced by CG_VoiceChatLocal().
void CG_AddToNotify (const char * str)
Definition at line 1183 of file cg_servercmds.c.
Referenced by CG_Printf().
static void CG_AddToTeamChat (const char * str, int clientnum) static
CG_AddToTeamChat.
Parameters
[in] str
[in] clientnum
Todo:
: never return for console chat?
Todo:
: never return for console chat?
Definition at line 1074 of file cg_servercmds.c.
Referenced by CG_PlayVoiceChat(), and CG_ServerCommand().
void CG_ChargeTimesChanged (void)
CG_ChargeTimesChanged.
Definition at line 816 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
static void CG_ConfigStringModified (void) static
CG_ConfigStringModified.
Todo:
: add a compress flag?
Todo:
dlight changes ignored!
Definition at line 880 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_dumpStats (void)
CG_dumpStats.
Definition at line 2649 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_ExecuteNewServerCommands (int latestSequence)
Execute all of the server commands that were received along with this this snapshot.
Parameters
[in] latestSequence
Definition at line 3302 of file cg_servercmds.c.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionSnapshot().
int CG_GetVoiceChat (voiceChatList_t * voiceChatList, const char * id, sfxHandle_t * snd, qhandle_t * sprite, char ** chat)
CG_GetVoiceChat.
Parameters
[in] voiceChatList
[in] id
[out] snd
[out] sprite
[out] chat
Returns
Definition at line 1605 of file cg_servercmds.c.
Referenced by CG_VoiceChatLocal().
static qboolean CG_inSVCVARBackupList (const char * cvar1) static
CG_inSVCVARBackupList.
Parameters
[in] cvar1
Returns
Definition at line 211 of file cg_servercmds.c.
Referenced by CG_UpdateSvCvars().
void CG_LoadVoiceChats (void)
CG_LoadVoiceChats.
Definition at line 1587 of file cg_servercmds.c.
Referenced by CG_RegisterSounds().
const char* CG_LocalizeServerCommand (const char * buf)
Localize string sent from server.
localization is ON by default.
use [lof] in string to turn OFF
use [lon] in string to turn back ON
Parameters
buf
Returns
Definition at line 1877 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_MapRestart (void) static
The server has issued a map_restart, so the next snapshot is completely new and should not be interpolated to.
A tournement restart will clear everything, but doesn't require a reload of all the media
Definition at line 1275 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_parseBestShotsStats_cmd (qboolean doTop, void(txt_dump)(const char *)) static
CG_parseBestShotsStats_cmd.
Parameters
[in] doTop
Definition at line 2460 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_ParseFog (void) static
CG_ParseFog.
Note
: float near dist float far dist float density float[3] r,g,b int time
Definition at line 614 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified().
static void CG_ParseGlobalFog (void) static
CG_ParseGlobalFog.
Definition at line 652 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified().
void CG_ParseLegacyinfo (void)
CG_ParseLegacyinfo.
Definition at line 302 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseOIDInfo (int num)
CG_OIDInfoForEntityNum.
Parameters
[in] num
Returns
Note
Unused oidInfo_t *CG_OIDInfoForEntityNum(int num) { int i;
for (i = 0; i < MAX_OID_TRIGGERS; i++) { if (cgs.oidInfo[i].entityNum == num) { return &cgs.oidInfo[i]; } }
return NULL; } CG_ParseOIDInfo
Parameters
[in] num
Definition at line 381 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_ParseOIDInfos().
void CG_ParseOIDInfos (void)
CG_ParseOIDInfos.
Definition at line 454 of file cg_servercmds.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_ParsePortalPos (void)
CG_ParsePortalPos.
Definition at line 2021 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_ParseReinforcementTimes (const char * pszReinfSeedString)
Parse reinforcement offsets.
Parameters
[in] pszReinfSeedString
Definition at line 702 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_SetConfigValues().
static void CG_ParseScore (team_t team) static
CG_ParseScore.
Parameters
[in] team
Note
NOTE: team doesnt actually signify team
Definition at line 66 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_ParseScreenFade (void) static
CG_ParseScreenFade.
Definition at line 584 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified().
void CG_ParseServerinfo (void)
This is called explicitly when the gamestate is first received, and whenever the server updates any serverinfo flagged cvars.
Definition at line 167 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParseServerVersionInfo (const char * pszVersionInfo)
Parse server version info (for demo playback compatibility)
Parameters
[in] pszVersionInfo
Definition at line 691 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_SetConfigValues().
void CG_ParseSpawns (void)
CG_ParseSpawns.
Definition at line 506 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), CG_MapRestart(), and SP_worldspawn().
void CG_ParseSysteminfo (void)
Definition at line 270 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
static void CG_ParseTeamInfo (void) static
CG_ParseTeamInfo.
Todo:
: get origin/location from somewhere else and shorten tinfo
Definition at line 127 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_parseTopShotsStats_cmd (qboolean doTop, void(txt_dump)(const char *)) static
CG_parseTopShotsStats_cmd.
Parameters
[in] doTop
Definition at line 2538 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
int CG_ParseVoiceChats (const char * filename, voiceChatList_t * voiceChatList, int maxVoiceChats)
CG_ParseVoiceChats.
Parameters
[in] filename
[in,out] voiceChatList
[in] maxVoiceChats
Returns
Definition at line 1444 of file cg_servercmds.c.
Referenced by CG_LoadVoiceChats().
static void CG_ParseWarmup (void) static
CG_ParseWarmup.
Definition at line 326 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_ParseWolfinfo().
void CG_ParseWeaponStats (void)
CG_ParseWeaponStats.
Definition at line 2012 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_parseWeaponStats_cmd (void(txt_dump)(const char *))
Client-side stat presentation.
Definition at line 2218 of file cg_servercmds.c.
Referenced by CG_dumpStats(), CG_ServerCommand(), and CG_wstatsParse_cmd().
void CG_parseWeaponStatsGS_cmd (void)
Cached stats.
Definition at line 2042 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_ParseWolfinfo (void)
CG_ParseWolfinfo.
Definition at line 467 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
void CG_PlayBufferedVoiceChats (void)
CG_PlayBufferedVoiceChats.
Definition at line 1709 of file cg_servercmds.c.
Referenced by CG_DrawActiveFrame().
void CG_PlayVoiceChat (bufferedVoiceChat_t * vchat)
CG_PlayVoiceChat.
Parameters
[in,out] vchat
Definition at line 1659 of file cg_servercmds.c.
Referenced by CG_AddBufferedVoiceChat(), and CG_PlayBufferedVoiceChats().
static void CG_printFile (const char * str) static
CG_printFile.
Parameters
[in] str
Definition at line 2634 of file cg_servercmds.c.
Referenced by CG_dumpStats().
static void CG_RemoveChatEscapeChar (char * text) static
CG_RemoveChatEscapeChar.
Parameters
[in,out] text
Definition at line 1853 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_scores_cmd (void) static
CG_scores_cmd.
Definition at line 2594 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
static void CG_ServerCommand (void) static
The string has been tokenized and can be retrieved with Cmd_Argc() / Cmd_Argv()
Todo:
: skip for console?
Definition at line 2756 of file cg_servercmds.c.
Referenced by CG_ExecuteNewServerCommands().
void CG_SetConfigValues (void)
Called on load to set the initial values from configure strings.
Definition at line 736 of file cg_servercmds.c.
Referenced by CG_Init().
void CG_ShaderStateChanged (void)
CG_ShaderStateChanged.
Definition at line 766 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_SkillLevelsChanged (void)
CG_SkillLevelsChanged.
Definition at line 862 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_TeamRestrictionsChanged (void)
CG_TeamRestrictionsChanged.
Definition at line 837 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_topshotsParse_cmd (qboolean doBest)
CG_topshotsParse_cmd.
Parameters
doBest - unused
Definition at line 1972 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
void CG_UpdateSvCvars (void)
CG_UpdateSvCvars.
Definition at line 228 of file cg_servercmds.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_VoiceChat (int mode)
CG_VoiceChat.
Parameters
[in] mode
Definition at line 1826 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
voiceChatList_t* CG_VoiceChatListForClient (int clientNum)
CG_VoiceChatListForClient.
Parameters
[in] clientNum
Returns
Definition at line 1628 of file cg_servercmds.c.
Referenced by CG_VoiceChatLocal().
void CG_VoiceChatLocal (int mode, qboolean voiceOnly, int clientNum, int color, const char * cmd, vec3_t origin)
CG_VoiceChatLocal.
Parameters
[in] mode
[in] voiceOnly
[in] clientNum
[in] color
[in] cmd
[in] origin
Todo:
: CG_TranslateString doesn't make sense here
Todo:
: CG_TranslateString doesn't make sense here
Todo:
: CG_TranslateString doesn't make sense here
Definition at line 1745 of file cg_servercmds.c.
Referenced by CG_VoiceChat().
void CG_wstatsParse_cmd (void)
CG_wstatsParse_cmd.
Definition at line 1937 of file cg_servercmds.c.
Referenced by CG_ServerCommand().
Variable Documentation
bufferedVoiceChat_t voiceChatBuffer[MAX_VOICECHATBUFFER]
Definition at line 1653 of file cg_servercmds.c.
voiceChatList_t voiceChatLists[MAX_VOICEFILES]
Definition at line 1435 of file cg_servercmds.c.