ET: Legacy: src/cgame/cg_window.c File Reference
cg_window.c File Reference
cgame window handling
#include "cg_local.h"
Functions
void CG_createStatsWindow (void)
CG_createStatsWindow.
void CG_createTopShotsWindow (void)
CG_createTopShotsWindow.
void CG_createMOTDWindow (void)
CG_createMOTDWindow.
void CG_windowInit (void)
Windowing system setup.
void CG_windowReset (cg_window_t *w, int fx, int startupLength)
Window stuct "constructor" with some common defaults.
cg_window_t * CG_windowAlloc (int fx, int startupLength)
Reserve a window.
void CG_windowFree (cg_window_t *w)
Free up a window reservation.
void CG_windowCleanup (void)
CG_windowCleanup.
void CG_demoAviFPSDraw (void)
CG_demoAviFPSDraw.
void CG_demoTimescaleDraw (void)
CG_demoTimescaleDraw.
void CG_windowDraw (void)
Main window-drawing handler.
void CG_windowNormalizeOnText (cg_window_t *w)
Set the window width and height based on the windows text/font parameters.
void CG_printWindow (const char *str)
CG_printWindow.
void CG_initStrings (void)
String buffer handling.
qboolean CG_addString (cg_window_t *w, const char *buf)
CG_addString.
void CG_removeStrings (cg_window_t *w)
CG_removeStrings.
Variables
vec4_t colorGreen2 = { 0.305f, 0.475f, 0.305f, 0.48f }
Detailed Description
cgame window handling
Definition in file cg_window.c.
Function Documentation
qboolean CG_addString (cg_window_t * w, const char * buf)
CG_addString.
Parameters
[in,out] w
[in] buf
Returns
Definition at line 642 of file cg_window.c.
Referenced by CG_printWindow().
void CG_createMOTDWindow (void)
CG_createMOTDWindow.
Todo:
TODO: dynamic game server MOTD window, see CG_DrawInformation()
Definition at line 94 of file cg_window.c.
void CG_createStatsWindow (void)
CG_createStatsWindow.
Definition at line 47 of file cg_window.c.
Referenced by CG_wstatsParse_cmd().
void CG_createTopShotsWindow (void)
CG_createTopShotsWindow.
Note
Unused
Definition at line 69 of file cg_window.c.
void CG_demoAviFPSDraw (void)
CG_demoAviFPSDraw.
Definition at line 293 of file cg_window.c.
Referenced by CG_windowDraw().
void CG_demoTimescaleDraw (void)
CG_demoTimescaleDraw.
Definition at line 306 of file cg_window.c.
Referenced by CG_windowDraw().
void CG_initStrings (void)
String buffer handling.
Definition at line 625 of file cg_window.c.
Referenced by CG_Init().
void CG_printWindow (const char * str)
CG_printWindow.
Parameters
[in] str
Definition at line 578 of file cg_window.c.
Referenced by CG_createMOTDWindow(), CG_parseBestShotsStats_cmd(), CG_parseWeaponStats_cmd(), and CG_wstatsParse_cmd().
void CG_removeStrings (cg_window_t * w)
CG_removeStrings.
Parameters
[in,out] w
Definition at line 686 of file cg_window.c.
Referenced by CG_windowFree().
cg_window_t* CG_windowAlloc (int fx, int startupLength)
Reserve a window.
Parameters
[in] fx
[in] startupLength
Returns
Definition at line 198 of file cg_window.c.
Referenced by CG_createMOTDWindow(), CG_createStatsWindow(), and CG_createTopShotsWindow().
void CG_windowCleanup (void)
CG_windowCleanup.
Definition at line 273 of file cg_window.c.
Referenced by CG_windowDraw().
void CG_windowDraw (void)
Main window-drawing handler.
Todo:
: Add in support for ALL scrolling effects
Definition at line 327 of file cg_window.c.
Referenced by CG_Draw2D().
void CG_windowFree (cg_window_t * w)
Free up a window reservation.
Parameters
[in,out] w
Definition at line 228 of file cg_window.c.
Referenced by CG_SetInitialSnapshot(), and CG_windowCleanup().
void CG_windowInit (void)
Windowing system setup.
Definition at line 147 of file cg_window.c.
Referenced by CG_Init().
void CG_windowNormalizeOnText (cg_window_t * w)
Set the window width and height based on the windows text/font parameters.
Parameters
[in,out] w
Definition at line 510 of file cg_window.c.
Referenced by CG_windowDraw().
void CG_windowReset (cg_window_t * w, int fx, int startupLength)
Window stuct "constructor" with some common defaults.
Parameters
[in] w
[out] fx
[out] startupLength
Definition at line 169 of file cg_window.c.
Referenced by CG_windowAlloc().
Variable Documentation
vec4_t colorGreen2 = { 0.305f, 0.475f, 0.305f, 0.48f }
Definition at line 42 of file cg_window.c.
Referenced by CG_createMOTDWindow(), and CG_createTopShotsWindow().