ET: Legacy: src/cgame/cg_syscalls.c File Reference
cg_syscalls.c File Reference
#include "cg_local.h"
Functions
static intptr_t (QDECL *syscall)(intptr_t arg
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
dllEntry
int PASSFLOAT (float x)
PASSFLOAT.
void trap_PumpEventLoop (void)
trap_PumpEventLoop
void trap_Print (const char *fmt)
trap_Print
void trap_Error (const char *fmt)
trap_Error
int trap_Milliseconds (void)
trap_Milliseconds
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
trap_Cvar_Register
void trap_Cvar_Update (vmCvar_t *vmCvar)
trap_Cvar_Update
void trap_Cvar_Set (const char *varName, const char *value)
trap_Cvar_Set
void trap_Cvar_VariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_VariableStringBuffer
void trap_Cvar_LatchedVariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
int trap_Argc (void)
trap_Argc
void trap_Argv (int n, char *buffer, int bufferLength)
trap_Argv
void trap_Args (char *buffer, int bufferLength)
trap_Args
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
trap_FS_FOpenFile
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
trap_FS_Read
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
trap_FS_Write
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
trap_FS_GetFileList
int trap_FS_Delete (const char *filename)
trap_FS_Delete
void trap_SendConsoleCommand (const char *text)
trap_SendConsoleCommand
void trap_AddCommand (const char *cmdName)
trap_AddCommand
void trap_RemoveCommand (const char *cmdName)
void trap_SendClientCommand (const char *s)
trap_SendClientCommand
void trap_UpdateScreen (void)
trap_UpdateScreen
int trap_CM_NumInlineModels (void)
trap_CM_NumInlineModels
clipHandle_t trap_CM_InlineModel (int index)
trap_CM_InlineModel
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempBoxModel
clipHandle_t trap_CM_TempCapsuleModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempCapsuleModel
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
trap_CM_PointContents
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedPointContents
void trap_CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_BoxTrace
void trap_CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedBoxTrace
void trap_CM_CapsuleTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_CapsuleTrace
void trap_CM_TransformedCapsuleTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedCapsuleTrace
int trap_CM_MarkFragments (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
trap_CM_MarkFragments
void trap_R_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t *points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
trap_R_ProjectDecal
void trap_R_ClearDecals (void)
trap_R_ClearDecals
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
Starts a sound.
void trap_S_StartSoundVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int volume)
trap_S_StartSoundVControl
void trap_S_StartSoundEx (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags)
trap_S_StartSoundEx
void trap_S_StartSoundExVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags, int volume)
trap_S_StartSoundExVControl
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
void trap_S_ClearLoopingSounds (void)
trap_S_ClearLoopingSounds
void trap_S_ClearSounds (qboolean killmusic)
trap_S_ClearSounds
void trap_S_AddLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int volume, int soundTime)
trap_S_AddLoopingSound
void trap_S_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int range, int volume, int soundTime)
trap_S_AddRealLoopingSound
void trap_S_StopStreamingSound (int entityNum)
trap_S_StopStreamingSound
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
trap_S_UpdateEntityPosition
int trap_S_GetVoiceAmplitude (int entityNum)
Talking animations.
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
trap_S_Respatialize
int trap_S_GetSoundLength (sfxHandle_t sfx)
trap_S_GetSoundLength
int trap_S_GetCurrentSoundTime (void)
For timing looped sounds.
void trap_S_StartBackgroundTrack (const char *intro, const char *loop, int fadeupTime)
trap_S_StartBackgroundTrack
void trap_S_FadeBackgroundTrack (float targetvol, int time, int num)
trap_S_FadeBackgroundTrack
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
int trap_S_StartStreamingSound (const char *intro, const char *loop, int entnum, int channel, int attenuation)
trap_S_StartStreamingSound
qboolean trap_R_GetSkinModel (qhandle_t skinid, const char *type, char *name)
trap_R_GetSkinModel
qhandle_t trap_R_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
trap_R_GetShaderFromModel
void trap_R_ClearScene (void)
trap_R_ClearScene
void trap_R_AddRefEntityToScene (const refEntity_t *re)
trap_R_AddRefEntityToScene
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
trap_R_AddPolyToScene
void trap_R_AddPolyBufferToScene (polyBuffer_t *pPolyBuffer)
trap_R_AddPolyBufferToScene
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
trap_R_AddPolysToScene
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
void trap_R_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
trap_R_SetFog
void trap_R_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
trap_R_SetGlobalFog
void trap_R_RenderScene (const refdef_t *fd)
trap_R_RenderScene
void trap_R_SaveViewParms ()
trap_R_SaveViewParms
void trap_R_RestoreViewParms ()
trap_R_RestoreViewParms
void trap_R_SetColor (const float *rgba)
trap_R_SetColor
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
void trap_R_DrawStretchPicGradient (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float *gradientColor, int gradientType)
trap_R_DrawStretchPicGradient
void trap_R_Add2dPolys (polyVert_t *verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
int trap_R_LerpTag (orientation_t *tag, const refEntity_t *refent, const char *tagName, int startIndex)
trap_R_LerpTag
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
trap_R_RemapShader
void trap_GetGlconfig (glconfig_t *glconfig)
trap_GetGlconfig
void trap_GetGameState (gameState_t *gamestate)
trap_GetGameState
void trap_GetCurrentSnapshotNumber (int *snapshotNumber, int *serverTime)
trap_GetCurrentSnapshotNumber
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t *snapshot)
trap_GetSnapshot
qboolean trap_GetServerCommand (int serverCommandNumber)
trap_GetServerCommand
int trap_GetCurrentCmdNumber (void)
trap_GetCurrentCmdNumber
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t *ucmd)
trap_GetUserCmd
void trap_SetUserCmdValue (int stateValue, int flags, float sensitivityScale, int mpIdentClient)
trap_SetUserCmdValue
void trap_SetClientLerpOrigin (float x, float y, float z)
trap_SetClientLerpOrigin
void testPrintInt (char *string, int i)
testPrintInt
void testPrintFloat (char *string, float f)
testPrintFloat
int trap_MemoryRemaining (void)
trap_MemoryRemaining
qboolean trap_loadCamera (int camNum, const char *name)
trap_loadCamera
void trap_startCamera (int camNum, int time)
trap_startCamera
void trap_stopCamera (int camNum)
trap_stopCamera
qboolean trap_getCameraInfo (int camNum, int time, vec3_t *origin, vec3_t *angles, float *fov)
trap_getCameraInfo
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
void trap_Key_KeysForBinding (const char *binding, int *key1, int *key2)
trap_Key_KeysForBinding
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
int trap_Key_GetKey (const char *binding)
trap_Key_GetKey
int trap_PC_AddGlobalDefine (char *define)
trap_PC_AddGlobalDefine
int trap_PC_LoadSource (const char *filename)
trap_PC_LoadSource
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
trap_PC_ReadToken
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
trap_PC_SourceFileAndLine
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
int trap_RealTime (qtime_t *qtime)
trap_RealTime
void trap_SnapVector (float *v)
trap_SnapVector
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle.
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
trap_GetEntityToken
void trap_UI_Popup (int arg0)
trap_UI_Popup
void trap_UI_ClosePopup (const char *arg0)
trap_UI_ClosePopup
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
trap_Key_GetBindingBuf
void trap_Key_SetBinding (int keynum, const char *binding)
trap_Key_SetBinding
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
trap_Key_KeynumToStringBuf
void trap_TranslateString (const char *string, char *buf)
trap_TranslateString
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
trap_S_RegisterSound
qhandle_t trap_R_RegisterModel (const char *name)
trap_R_RegisterModel
qhandle_t trap_R_RegisterSkin (const char *name)
trap_R_RegisterSkin
qhandle_t trap_R_RegisterShader (const char *name)
trap_R_RegisterShader
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
trap_R_RegisterShaderNoMip
void trap_R_RegisterFont (const char *fontName, int pointSize, void *font)
trap_R_RegisterFont
void trap_CM_LoadMap (const char *mapname)
trap_CM_LoadMap
void trap_R_LoadWorldMap (const char *mapname)
trap_R_LoadWorldMap
qboolean trap_R_inPVS (const vec3_t p1, const vec3_t p2)
trap_R_inPVS
void trap_GetHunkData (int *hunkused, int *hunkexpected)
trap_GetHunkData
qboolean trap_SendMessage (char *buf, int buflen)
Binary message channel.
messageStatus_t trap_MessageStatus (void)
trap_MessageStatus
qboolean trap_R_LoadDynamicShader (const char *shadername, const char *shadertext)
Dynamic shaders.
void trap_R_RenderToTexture (int textureid, int x, int y, int w, int h)
Render to texture.
int trap_R_GetTextureId (const char *name)
trap_R_GetTextureId
void trap_R_Finish (void)
Sync rendering.
Function Documentation
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
dllEntry
Definition at line 42 of file cg_syscalls.c.
Referenced by Sys_LoadGameDll().
static intptr_t (QDECL * syscall) static
Referenced by BG_GetConditionValue(), CL_CgameSystemCalls(), CL_UISystemCalls(), Com_InitHunkMemory(), CopyWinding(), Hunk_AllocateTempMemory(), R_Init(), RB_ReadPixels(), RB_ReadZBuffer(), SV_DirectConnect(), SV_GameSystemCalls(), Sys_ListFiles(), Sys_ListFilteredFiles(), Sys_LoadGameDll(), VM_CallFunc(), VM_CallInterpreted(), VM_DllSyscall(), VM_Restart(), vmMain(), and Z_TagMalloc().
int PASSFLOAT (float x)
PASSFLOAT.
Parameters
[in] x
Returns
Definition at line 52 of file cg_syscalls.c.
Referenced by testPrintFloat(), trap_R_AddCoronaToScene(), trap_R_AddLightToScene(), trap_R_DrawRotatedPic(), trap_R_DrawStretchPic(), trap_R_DrawStretchPicGradient(), trap_R_SetFog(), trap_R_SetGlobalFog(), trap_S_FadeAllSound(), trap_S_FadeBackgroundTrack(), trap_SetClientLerpOrigin(), and trap_SetUserCmdValue().
void testPrintFloat (char * string, float f)
testPrintFloat
Parameters
[out] string
[in] f
Definition at line 1211 of file cg_syscalls.c.
void testPrintInt (char * string, int i)
testPrintInt
Parameters
[out] string
[in] i
Definition at line 1201 of file cg_syscalls.c.
void trap_AddCommand (const char * cmdName)
trap_AddCommand
Parameters
[in] cmdName
Definition at line 258 of file cg_syscalls.c.
int trap_Argc (void)
trap_Argc
Returns
Definition at line 153 of file cg_syscalls.c.
void trap_Args (char * buffer, int bufferLength)
trap_Args
Parameters
[out] buffer
[in] bufferLength
Definition at line 174 of file cg_syscalls.c.
Referenced by CG_ReadHuds_f().
void trap_Argv (int n, char * buffer, int bufferLength)
trap_Argv
Parameters
[in] n
[out] buffer
[in] bufferLength
Definition at line 164 of file cg_syscalls.c.
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
Parameters
handle
Definition at line 1479 of file cg_syscalls.c.
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle.
arg0 is the name in the format "idlogo.roq", set arg1 to NULL, alteredstates to qfalse (do not alter gamestate)
Parameters
[in] arg0
[in] xpos
[in] ypos
[in] width
[in] height
[in] bits
Returns
Definition at line 1447 of file cg_syscalls.c.
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
Parameters
[in] handle
Returns
Definition at line 1470 of file cg_syscalls.c.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 1492 of file cg_syscalls.c.
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
Parameters
[in] handle
Returns
Definition at line 1459 of file cg_syscalls.c.
void trap_CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_BoxTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
Definition at line 369 of file cg_syscalls.c.
Referenced by CG_BigExplosionImpact(), CG_Bullet(), CG_DynamiteExplosionImpact(), CG_MapMortarImpact(), CG_PlayerShadow(), CG_PlayerSplash(), CG_SmallExplosionImpact(), and CG_Trace().
void trap_CM_CapsuleTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
trap_CM_CapsuleTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
Definition at line 406 of file cg_syscalls.c.
Referenced by CG_TraceCapsule(), and CG_TraceCapsule_World().
clipHandle_t trap_CM_InlineModel (int index)
trap_CM_InlineModel
Parameters
[in] index
Returns
Definition at line 308 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities(), and CG_PointContents().
void trap_CM_LoadMap (const char * mapname)
trap_CM_LoadMap
Parameters
[in] mapname
Definition at line 1829 of file cg_syscalls.c.
Referenced by CG_Init(), and trap_TranslateString().
int trap_CM_MarkFragments (int numPoints, const vec3_t * points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t * fragmentBuffer)
trap_CM_MarkFragments
Parameters
[in] numPoints
[in] points
[in] projection
[in] maxPoints
[in] pointBuffer
[in] maxFragments
[in] fragmentBuffer
Returns
Definition at line 444 of file cg_syscalls.c.
int trap_CM_NumInlineModels (void)
trap_CM_NumInlineModels
Returns
Definition at line 298 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics().
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
trap_CM_PointContents
Parameters
[in] p
[in] model
Returns
Definition at line 341 of file cg_syscalls.c.
Referenced by CG_PointContents().
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempBoxModel
Parameters
[in] mins
[in] maxs
Returns
Definition at line 319 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities().
clipHandle_t trap_CM_TempCapsuleModel (const vec3_t mins, const vec3_t maxs)
trap_CM_TempCapsuleModel
Parameters
[in] mins
[in] maxs
Returns
Definition at line 330 of file cg_syscalls.c.
void trap_CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedBoxTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] origin
[in] angles
Definition at line 388 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities().
void trap_CM_TransformedCapsuleTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedCapsuleTrace
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] origin
[in] angles
Definition at line 425 of file cg_syscalls.c.
Referenced by CG_ClipMoveToEntities().
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
trap_CM_TransformedPointContents
Parameters
[in] p
[in] model
[in] origin
[in] angles
Returns
Definition at line 354 of file cg_syscalls.c.
Referenced by CG_PointContents().
void trap_Cvar_LatchedVariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
Definition at line 144 of file cg_syscalls.c.
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
trap_Cvar_Register
Parameters
[in] vmCvar
[in] varName
[in] defaultValue
[in] flags
Definition at line 103 of file cg_syscalls.c.
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 122 of file cg_syscalls.c.
void trap_Cvar_Update (vmCvar_t * vmCvar)
trap_Cvar_Update
Parameters
[in] vmCvar
Definition at line 112 of file cg_syscalls.c.
void trap_Cvar_VariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_VariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
Definition at line 133 of file cg_syscalls.c.
Referenced by trap_GetCurrentSnapshotNumber(), and trap_GetSnapshot().
void trap_Error (const char * fmt)
trap_Error
Parameters
[in] fmt
Definition at line 80 of file cg_syscalls.c.
int trap_FS_Delete (const char * filename)
trap_FS_Delete
Parameters
[in] filename
Returns
Definition at line 240 of file cg_syscalls.c.
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
Parameters
[in] f
Definition at line 217 of file cg_syscalls.c.
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
trap_FS_FOpenFile
Parameters
[in] qpath
[in,out] f
[in] mode
Returns
Definition at line 186 of file cg_syscalls.c.
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
trap_FS_GetFileList
Parameters
[in] path
[in] extension
[out] listbuf
[in] bufsize
Returns
Definition at line 230 of file cg_syscalls.c.
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
trap_FS_Read
Parameters
[out] buffer
[in] len
[in] f
Definition at line 197 of file cg_syscalls.c.
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
trap_FS_Write
Parameters
[in] buffer
[in] len
[in] f
Definition at line 208 of file cg_syscalls.c.
qboolean trap_getCameraInfo (int camNum, int time, vec3_t * origin, vec3_t * angles, float * fov)
trap_getCameraInfo
Parameters
camNum - unused
time - unused
origin - unused
angles - unused
fov - unused
Returns
Note
Unused
Definition at line 1270 of file cg_syscalls.c.
int trap_GetCurrentCmdNumber (void)
trap_GetCurrentCmdNumber
Returns
Definition at line 1157 of file cg_syscalls.c.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
void trap_GetCurrentSnapshotNumber (int * snapshotNumber, int * serverTime)
trap_GetCurrentSnapshotNumber
Parameters
[out] snapshotNumber
[out] serverTime
Definition at line 1039 of file cg_syscalls.c.
Referenced by CG_ProcessSnapshots().
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
trap_GetEntityToken
Parameters
[out] buffer
[in] bufferSize
Returns
Definition at line 1503 of file cg_syscalls.c.
void trap_GetGameState (gameState_t * gamestate)
trap_GetGameState
Parameters
[out] gamestate
Definition at line 1016 of file cg_syscalls.c.
Referenced by CG_ConfigStringModified(), and CG_Init().
void trap_GetGlconfig (glconfig_t * glconfig)
trap_GetGlconfig
Parameters
[out] glconfig
Definition at line 1007 of file cg_syscalls.c.
void trap_GetHunkData (int * hunkused, int * hunkexpected)
trap_GetHunkData
Parameters
[out] hunkused
[out] hunkexpected
Definition at line 1862 of file cg_syscalls.c.
qboolean trap_GetServerCommand (int serverCommandNumber)
trap_GetServerCommand
Parameters
[in] serverCommandNumber
Returns
Definition at line 1148 of file cg_syscalls.c.
Referenced by CG_ExecuteNewServerCommands().
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t * snapshot)
trap_GetSnapshot
Parameters
[in] snapshotNumber
[out] snapshot
Returns
Definition at line 1078 of file cg_syscalls.c.
Referenced by CG_ReadNextSnapshot().
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t * ucmd)
trap_GetUserCmd
Parameters
[in] cmdNumber
[out] ucmd
Returns
Definition at line 1168 of file cg_syscalls.c.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
trap_Key_GetBindingBuf
Parameters
[in] keynum
[in] buf
[in] buflen
Definition at line 1533 of file cg_syscalls.c.
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
Returns
Definition at line 1289 of file cg_syscalls.c.
int trap_Key_GetKey (const char * binding)
trap_Key_GetKey
Parameters
[in] binding
Returns
Definition at line 1339 of file cg_syscalls.c.
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
Returns
Definition at line 1298 of file cg_syscalls.c.
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
Parameters
[in] keynum
Returns
Definition at line 1280 of file cg_syscalls.c.
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
trap_Key_KeynumToStringBuf
Parameters
[in] keynum
[out] buf
[in] buflen
Definition at line 1554 of file cg_syscalls.c.
void trap_Key_KeysForBinding (const char * binding, int * key1, int * key2)
trap_Key_KeysForBinding
Parameters
[in] binding
[in,out] key1
[in,out] key2
Note
binding MUST be lower case
Definition at line 1320 of file cg_syscalls.c.
void trap_Key_SetBinding (int keynum, const char * binding)
trap_Key_SetBinding
Parameters
[in] keynum
[in] binding
Definition at line 1543 of file cg_syscalls.c.
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
Parameters
[in] catcher
Definition at line 1329 of file cg_syscalls.c.
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
Parameters
[in] state
Definition at line 1307 of file cg_syscalls.c.
qboolean trap_loadCamera (int camNum, const char * name)
trap_loadCamera
Parameters
camNum - unused
name - unused
Returns
Note
Unused
Definition at line 1233 of file cg_syscalls.c.
int trap_MemoryRemaining (void)
trap_MemoryRemaining
Returns
Definition at line 1220 of file cg_syscalls.c.
messageStatus_t trap_MessageStatus (void)
trap_MessageStatus
Returns
Definition at line 1882 of file cg_syscalls.c.
int trap_Milliseconds (void)
trap_Milliseconds
Returns
Definition at line 91 of file cg_syscalls.c.
int trap_PC_AddGlobalDefine (char * define)
trap_PC_AddGlobalDefine
Parameters
[in] define
Returns
Definition at line 1349 of file cg_syscalls.c.
Referenced by UI_LoadMenus().
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
Parameters
[in] handle
Returns
Definition at line 1369 of file cg_syscalls.c.
Referenced by BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_PCF_ParseError(), BG_R_RegisterAnimationGroup(), BG_RAG_ParseError(), BG_SS_ParseError(), CG_execFile(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_HUD_ParseError(), CG_LoadObjectiveData(), CG_ReadHudFile(), CG_RegisterWeaponFromWeaponFile(), CG_RW_ParseError(), G_ConfigError(), G_configLoadAndSet(), G_LoadCampaignsFromFile(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadProfiles(), and UI_ParseMenu().
int trap_PC_LoadSource (const char * filename)
trap_PC_LoadSource
Parameters
[in] filename
Returns
Definition at line 1359 of file cg_syscalls.c.
Referenced by BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_R_RegisterAnimationGroup(), CG_execFile(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_LoadObjectiveData(), CG_ReadHudFile(), CG_RegisterWeaponFromWeaponFile(), G_configLoadAndSet(), G_LoadCampaignsFromFile(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadProfiles(), and UI_ParseMenu().
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
trap_PC_ReadToken
Parameters
[in] handle
[out] pc_token
Returns
Definition at line 1380 of file cg_syscalls.c.
Referenced by Asset_Parse(), BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_R_RegisterAnimationGroup(), BG_RAG_ParseAnimFile(), BG_SS_ParseSpeaker(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_LoadObjectiveData(), CG_ParseHUD(), CG_ReadHudFile(), CG_RegisterWeaponFromWeaponFile(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), CG_RW_ParseSoundSurface(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLink(), CG_RW_ParseWeaponLinkPart(), CG_RW_ParseWeaponSound(), G_configLoadAndSet(), G_LoadCampaignsFromFile(), G_ParseMapSettings(), G_ParseSettings(), Item_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarListUndefined(), ItemParse_cvarStrList(), ItemParse_textfile(), Load_Menu(), Menu_Parse(), PC_Char_Parse(), PC_Float_Parse(), PC_Int_Parse(), PC_Script_Parse(), PC_String_Parse(), PC_String_ParseNoAlloc(), PC_String_ParseTranslate(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadProfiles(), and UI_ParseMenu().
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
trap_PC_SourceFileAndLine
Parameters
[in] handle
[out] filename
[out] line
Returns
Definition at line 1392 of file cg_syscalls.c.
Referenced by BG_PCF_ParseError(), BG_RAG_ParseError(), BG_SS_ParseError(), CG_HUD_ParseError(), CG_RW_ParseError(), G_ConfigError(), and PC_SourceError().
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
Parameters
[in] handle
Returns
Definition at line 1402 of file cg_syscalls.c.
void trap_Print (const char * fmt)
trap_Print
Parameters
[in] fmt
Definition at line 71 of file cg_syscalls.c.
void trap_PumpEventLoop (void)
trap_PumpEventLoop
Definition at line 63 of file cg_syscalls.c.
void trap_R_Add2dPolys (polyVert_t * verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
Parameters
[in] verts
[in] numverts
[in] hShader
Definition at line 963 of file cg_syscalls.c.
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
Parameters
[in] org
[in] r
[in] g
[in] b
[in] scale
[in] id
[in] visible
Definition at line 831 of file cg_syscalls.c.
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
Parameters
[in] org
[in] radius
[in] intensity
[in] r
[in] g
[in] b
[in] hShader
[in] flags
Definition at line 815 of file cg_syscalls.c.
void trap_R_AddPolyBufferToScene (polyBuffer_t * pPolyBuffer)
trap_R_AddPolyBufferToScene
Parameters
[in] pPolyBuffer
Definition at line 787 of file cg_syscalls.c.
Referenced by CG_PB_RenderPolyBuffers().
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int numPolys)
trap_R_AddPolysToScene
Parameters
[in] hShader
[in] numVerts
[in] verts
[in] numPolys
Definition at line 799 of file cg_syscalls.c.
Referenced by CG_AddTrailToScene().
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
trap_R_AddPolyToScene
Parameters
[in] hShader
[in] numVerts
[in] verts
Definition at line 778 of file cg_syscalls.c.
void trap_R_AddRefEntityToScene (const refEntity_t * re)
trap_R_AddRefEntityToScene
Parameters
re
Definition at line 767 of file cg_syscalls.c.
void trap_R_ClearDecals (void)
trap_R_ClearDecals
Definition at line 470 of file cg_syscalls.c.
Referenced by CG_MapRestart().
void trap_R_ClearScene (void)
trap_R_ClearScene
Definition at line 758 of file cg_syscalls.c.
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] angle
Definition at line 930 of file cg_syscalls.c.
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
Definition at line 911 of file cg_syscalls.c.
void trap_R_DrawStretchPicGradient (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float * gradientColor, int gradientType)
trap_R_DrawStretchPicGradient
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] gradientColor
[in] gradientType
Definition at line 950 of file cg_syscalls.c.
void trap_R_Finish (void)
Sync rendering.
Definition at line 1924 of file cg_syscalls.c.
qhandle_t trap_R_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
trap_R_GetShaderFromModel
Parameters
[in] modelid
[in] surfnum
[in] withlightmap
Returns
Definition at line 750 of file cg_syscalls.c.
Referenced by CG_AddFragment(), CG_Explode(), and CG_Rubble().
qboolean trap_R_GetSkinModel (qhandle_t skinid, const char * type, char * name)
trap_R_GetSkinModel
Parameters
[in] skinid
[in] type
[out] name
Returns
Definition at line 738 of file cg_syscalls.c.
Referenced by CG_RegisterCharacter().
int trap_R_GetTextureId (const char * name)
trap_R_GetTextureId
Parameters
[in] name
Returns
Definition at line 1916 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
qboolean trap_R_inPVS (const vec3_t p1, const vec3_t p2)
trap_R_inPVS
Parameters
[in] p1
[in] p2
Returns
Definition at line 1852 of file cg_syscalls.c.
Referenced by CG_AddScriptSpeakers(), CG_Coronas(), CG_DrawMiscGamemodels(), CG_GetLocation(), CG_RenderLocations(), and CG_RenderScriptSpeakers().
int trap_R_LerpTag (orientation_t * tag, const refEntity_t * refent, const char * tagName, int startIndex)
trap_R_LerpTag
Parameters
[in] tag
[in] refent
[in] tagName
[in] startIndex
Returns
Definition at line 987 of file cg_syscalls.c.
Referenced by CG_CalcMoveSpeeds(), CG_GetOriginForTag(), CG_GetTag(), CG_GetWeaponTag(), CG_Player(), CG_PositionEntityOnTag(), and CG_PositionRotatedEntityOnTag().
qboolean trap_R_LoadDynamicShader (const char * shadername, const char * shadertext)
Dynamic shaders.
Parameters
[in] shadername
[in] shadertext
Returns
Definition at line 1893 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics().
void trap_R_LoadWorldMap (const char * mapname)
trap_R_LoadWorldMap
Parameters
[in] mapname
Definition at line 1839 of file cg_syscalls.c.
Referenced by CG_RegisterGraphics(), and trap_TranslateString().
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
Parameters
[in] model
[in] mins
[in] maxs
Definition at line 974 of file cg_syscalls.c.
void trap_R_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t * points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
trap_R_ProjectDecal
Parameters
[in] hShader
[in] numPoints
[in] points
[in] projection
[in] color
[in] lifeTime
[in] fadeTime
Definition at line 462 of file cg_syscalls.c.
Referenced by CG_Bullet(), CG_Effect(), CG_FragmentBounceMark(), CG_GibPlayer(), CG_ImpactMark(), CG_MissileHitWall(), and CG_MissileHitWallSmall().
void trap_R_RegisterFont (const char * fontName, int pointSize, void * font)
trap_R_RegisterFont
Parameters
[in] fontName
[in] pointSize
[in] font
Definition at line 1819 of file cg_syscalls.c.
Referenced by trap_TranslateString().
qhandle_t trap_R_RegisterModel (const char * name)
trap_R_RegisterModel
Parameters
[in] name
Returns
Definition at line 1774 of file cg_syscalls.c.
Referenced by trap_TranslateString().
qhandle_t trap_R_RegisterShader (const char * name)
trap_R_RegisterShader
Parameters
[in] name
Returns
Definition at line 1796 of file cg_syscalls.c.
Referenced by CG_ActivateEditSoundMode(), CG_ClearParticles(), CG_ConfigStringModified(), CG_Effect(), CG_EffectParse(), CG_Init(), CG_InitFlameChunks(), CG_ParseVoiceChats(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RW_ParseModModel(), and trap_TranslateString().
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
trap_R_RegisterShaderNoMip
Parameters
[in] name
Returns
Definition at line 1807 of file cg_syscalls.c.
Referenced by trap_TranslateString().
qhandle_t trap_R_RegisterSkin (const char * name)
trap_R_RegisterSkin
Parameters
[in] name
Returns
Definition at line 1785 of file cg_syscalls.c.
Referenced by trap_TranslateString().
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
trap_R_RemapShader
Parameters
[in] oldShader
[in] newShader
[in] timeOffset
Definition at line 998 of file cg_syscalls.c.
void trap_R_RenderScene (const refdef_t * fd)
trap_R_RenderScene
Parameters
[in] fd
Definition at line 869 of file cg_syscalls.c.
void trap_R_RenderToTexture (int textureid, int x, int y, int w, int h)
Render to texture.
Parameters
[in] textureid
[in] x
[in] y
[in] w
[in] h
Definition at line 1906 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
void trap_R_RestoreViewParms (void)
trap_R_RestoreViewParms
Definition at line 885 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
void trap_R_SaveViewParms (void)
trap_R_SaveViewParms
Definition at line 877 of file cg_syscalls.c.
Referenced by CG_DrawPlayerHead().
void trap_R_SetColor (const float * rgba)
trap_R_SetColor
Parameters
[in] rgba
Definition at line 894 of file cg_syscalls.c.
void trap_R_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
trap_R_SetFog
Parameters
[in] fogvar
[in] var1
[in] var2
[in] r
[in] g
[in] b
[in] density
Definition at line 846 of file cg_syscalls.c.
Referenced by CG_MapRestart(), CG_ParseFog(), CG_ParseSkyBox(), and CG_Respawn().
void trap_R_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
trap_R_SetGlobalFog
Parameters
[in] restore
[in] duration
[in] r
[in] g
[in] b
[in] depthForOpaque
Definition at line 860 of file cg_syscalls.c.
Referenced by CG_ParseGlobalFog().
int trap_RealTime (qtime_t * qtime)
trap_RealTime
Parameters
[out] qtime
Returns
Definition at line 1420 of file cg_syscalls.c.
void trap_RemoveCommand (const char * cmdName)
Although this trap is not actually used anywhere in baseq3 game source, a reasonable assumption, based on function name and parameters, is that this trap removes a command name from the list of command completions. That is, the inverse of trap_AddCommand().
Unknown: case sensitivity (i.e. if capitalization matters for string matching)
Parameters
[in] cmdName command name
Definition at line 272 of file cg_syscalls.c.
Referenced by CG_InitConsoleCommands().
void trap_S_AddLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int volume, int soundTime)
trap_S_AddLoopingSound
Parameters
[in] origin
[in] velocity
[in] sfx
[in] volume
[in] soundTime
Note
Volume was previously removed from CG_S_ADDLOOPINGSOUND. I added 'range'
Definition at line 602 of file cg_syscalls.c.
Referenced by CG_AddFragment(), CG_AddPlayerWeapon(), CG_DrawFlashFire(), CG_EntityEffects(), CG_Missile(), CG_RenderSmokeGrenadeSmoke(), CG_UnderwaterSounds(), and CG_UpdateFlamethrowerSounds().
void trap_S_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx, int range, int volume, int soundTime)
trap_S_AddRealLoopingSound
Parameters
[in] origin
[in] velocity
[in] sfx
[in] range
[in] volume
[in] soundTime
Definition at line 616 of file cg_syscalls.c.
Referenced by CG_EntityEffects(), and CG_PlayScriptSpeaker().
void trap_S_ClearLoopingSounds (void)
trap_S_ClearLoopingSounds
Definition at line 578 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame(), CG_Init(), and CG_MapRestart().
void trap_S_ClearSounds (qboolean killmusic)
trap_S_ClearSounds
Parameters
[in] killmusic
Definition at line 587 of file cg_syscalls.c.
Referenced by CG_Init(), and CG_MapRestart().
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
Parameters
[in] targetvol
[in] time
[in] stopsounds
Definition at line 712 of file cg_syscalls.c.
void trap_S_FadeBackgroundTrack (float targetvol, int time, int num)
trap_S_FadeBackgroundTrack
Parameters
[in] targetvol
[in] time
[in] num
Note
yes, i know. fadebackground coming in, fadestreaming going out. will have to see where functionality leads...
'num' is '0' if it's music, '1' if it's "all streaming sounds"
Definition at line 701 of file cg_syscalls.c.
int trap_S_GetCurrentSoundTime (void)
For timing looped sounds.
Returns
Definition at line 676 of file cg_syscalls.c.
Referenced by CG_EntityEffects(), and CG_PlayScriptSpeaker().
int trap_S_GetSoundLength (sfxHandle_t sfx)
trap_S_GetSoundLength
Parameters
[in] sfx
Returns
Definition at line 667 of file cg_syscalls.c.
Referenced by CG_SoundPickOldestRandomSound().
int trap_S_GetVoiceAmplitude (int entityNum)
Talking animations.
Parameters
[in] entityNum
Returns
Definition at line 645 of file cg_syscalls.c.
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
trap_S_RegisterSound
Todo:
: unique debug macros
Parameters
[in] sample
[in] compressed
Returns
Definition at line 1763 of file cg_syscalls.c.
Referenced by trap_TranslateString().
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
trap_S_Respatialize
Parameters
[in] entityNum
[in] origin
[in] axis
[in] inwater
Definition at line 657 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame().
void trap_S_StartBackgroundTrack (const char * intro, const char * loop, int fadeupTime)
trap_S_StartBackgroundTrack
Parameters
[in] intro
[in] loop
[in] fadeupTime
Definition at line 687 of file cg_syscalls.c.
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
Parameters
[in] sfx
[in] channelNum
Note
127 Default volume always for the moment
Definition at line 570 of file cg_syscalls.c.
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
Starts a sound.
Parameters
[in] origin position or NULL for position of player entity (see entityNum)
[in] entityNum
[in] entchannel
[in] sfx
Definition at line 482 of file cg_syscalls.c.
Referenced by CG_AddLightstyle(), CG_CheckLocalSounds(), CG_Effect(), CG_EntityEvent(), CG_Explodef(), CG_FireWeapon(), CG_FragmentBounceSound(), CG_MissileHitWallSmall(), CG_Obituary(), CG_PlayGlobalSound(), CG_PMItemBigSound(), CG_PyroSmokeTrail(), CG_RubbleFx(), CG_SoundPickOldestRandomSound(), and CG_Speaker().
void trap_S_StartSoundEx (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags)
trap_S_StartSoundEx
Parameters
[in] origin
[in] entityNum
[in] entchannel
[in] sfx
[in] flags
Definition at line 532 of file cg_syscalls.c.
Referenced by CG_EntityEvent(), CG_FireWeapon(), and CG_MissileHitWall().
void trap_S_StartSoundExVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int flags, int volume)
trap_S_StartSoundExVControl
Parameters
[in] origin
[in] entityNum
[in] entchannel
[in] sfx
[in] flags
[in] volume
Definition at line 558 of file cg_syscalls.c.
Referenced by CG_EntityEvent().
void trap_S_StartSoundVControl (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx, int volume)
trap_S_StartSoundVControl
Parameters
[in] origin
[in] entityNum
[in] entchannel
[in] sfx
[in] volume
Definition at line 507 of file cg_syscalls.c.
Referenced by CG_EntityEvent(), CG_FragmentBounceSound(), CG_MissileHitWall(), and CG_PlayScriptSpeaker().
int trap_S_StartStreamingSound (const char * intro, const char * loop, int entnum, int channel, int attenuation)
trap_S_StartStreamingSound
Parameters
[in] intro
[in] loop
[in] entnum
[in] channel
[in] attenuation
Returns
Definition at line 726 of file cg_syscalls.c.
Referenced by CG_SoundPickOldestRandomSound().
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
Definition at line 1410 of file cg_syscalls.c.
void trap_S_StopStreamingSound (int entityNum)
trap_S_StopStreamingSound
Parameters
[in] entityNum
Definition at line 625 of file cg_syscalls.c.
Referenced by CG_EventHandling(), and CG_LimboPanel_BriefingButton_KeyDown().
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
trap_S_UpdateEntityPosition
Parameters
[in] entityNum
[in] origin
Definition at line 635 of file cg_syscalls.c.
Referenced by CG_SetEntitySoundPosition().
void trap_SendClientCommand (const char * s)
trap_SendClientCommand
Parameters
[in] s
Definition at line 281 of file cg_syscalls.c.
Referenced by CG_Class_f(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_InfoRequests(), CG_Debriefing_ReadyButton_KeyDown(), CG_DrawDemoRecording(), CG_dumpStats(), CG_dumpStats_f(), CG_EventHandling(), CG_FireteamCheckExecKey(), CG_ForceTapOut_f(), CG_LimboPanel_CancelButton_KeyDown(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_RequestWeaponStats(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_SpawnPointButton_KeyDown(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_KeyDown(), CG_ReadHuds_f(), CG_ScoresDown_f(), CG_ServerCommand(), CG_SpawnpointsCheckExecKey(), CG_StatsDown_f(), and CG_topshotsDown_f().
void trap_SendConsoleCommand (const char * text)
trap_SendConsoleCommand
Parameters
[in] text
Definition at line 249 of file cg_syscalls.c.
Referenced by _et_trap_SendConsoleCommand(), CG_AddViewWeapon(), CG_AltWeapon_f(), CG_autoRecord_f(), CG_autoScreenShot_f(), CG_BuddyVoiceChat_f(), CG_CommandCentreSpawnPointClick(), CG_DemoClick(), CG_DemoControlButtonDown(), CG_DrawIntermission(), CG_execFile(), CG_FinishWeaponChange(), CG_FireteamCheckExecKey(), CG_FTSayPlayerClass_f(), CG_MessageSend_f(), CG_Respawn(), CG_SayPlayerClass_f(), CG_TeamVoiceChat_f(), CG_TransitionPlayerState(), CG_UpdateCvars(), CG_VoiceChat_f(), CG_vstrDown_f(), CG_vstrUp_f(), CheckExitRules(), CheckWolfMP(), ExitLevel(), G_Campaign_v(), G_configSet(), G_Gametype_v(), G_InitGame(), G_Kick_v(), G_LogExit(), G_Map_v(), G_NextCampaign_v(), G_Nextmap_v(), G_ParseCampaigns(), G_ParseSettings(), G_readyMatchState(), G_RestartCampaign_v(), G_UpdateCvars(), G_verifyMatchState(), G_voteSetVoteString(), G_Warmupfire_v(), ETInterface::InterfaceSendMessage(), Svcmd_Campaign_f(), Svcmd_ListIp_f(), Svcmd_ResetMatch_f(), and vmMain().
qboolean trap_SendMessage (char * buf, int buflen)
Binary message channel.
Parameters
[out] buf
[in] buflen
Returns
result
Definition at line 1873 of file cg_syscalls.c.
void trap_SetClientLerpOrigin (float x, float y, float z)
trap_SetClientLerpOrigin
Parameters
[in] x
[in] y
[in] z
Definition at line 1191 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame().
void trap_SetUserCmdValue (int stateValue, int flags, float sensitivityScale, int mpIdentClient)
trap_SetUserCmdValue
Parameters
[in] stateValue
[in] flags
[in] sensitivityScale
[in] mpIdentClient
Definition at line 1180 of file cg_syscalls.c.
Referenced by CG_DrawActiveFrame().
void trap_SnapVector (float * v)
trap_SnapVector
Parameters
[out] v
Definition at line 1429 of file cg_syscalls.c.
void trap_startCamera (int camNum, int time)
trap_startCamera
Parameters
camNum - unused
time - unused
Note
Unused
Definition at line 1245 of file cg_syscalls.c.
void trap_stopCamera (int camNum)
trap_stopCamera
Parameters
camNum - unused
Note
Unused
Definition at line 1255 of file cg_syscalls.c.
void trap_TranslateString (const char * string, char * buf)
trap_TranslateString
Parameters
[in] string
[out] buf
Definition at line 1564 of file cg_syscalls.c.
Referenced by CG_TranslateString(), Item_Multi_Setting(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), UI_BuildServerDisplayList(), UI_Campaign_f(), UI_DrawKeyBindStatus(), UI_DrawServerRefreshDate(), UI_Init(), UI_ListCampaigns_f(), UI_ListFavourites_f(), UI_LoadPanel_RenderHeaderText(), UI_LoadPanel_RenderLoadingText(), UI_OwnerDrawWidth(), UI_RemoveAllFavourites_f(), UI_RunMenuScript(), UI_SetActiveMenu(), and UI_StopServerRefresh().
void trap_UI_ClosePopup (const char * arg0)
trap_UI_ClosePopup
Parameters
arg0 - unused
Note
TODO: this function is empty and is NEVER used
Definition at line 1523 of file cg_syscalls.c.
void trap_UI_Popup (int arg0)
trap_UI_Popup
Parameters
[in] arg0
Definition at line 1512 of file cg_syscalls.c.
Referenced by CG_ClassMenu_f(), CG_EventHandling(), CG_MessageMode_f(), CG_QuickFireteamAdmin_f(), CG_QuickFireteamMessage_f(), CG_QuickMessage_f(), CG_ServerCommand(), CG_SetInitialSnapshot(), and CG_TeamMenu_f().
void trap_UpdateScreen (void)
trap_UpdateScreen
Definition at line 289 of file cg_syscalls.c.