ET: Legacy: src/cgame/cg_character.c File Reference
cg_character.c File Reference
Character loading.
#include "cg_local.h"
Data Structures
struct acc_t
Functions
static qboolean CG_ParseGibModels (const char *modelPath, bg_character_t *character)
Parse gib models.
static qboolean CG_ParseHudHeadConfig (const char *filename, animation_t *hha)
Parse HUD head config.
static void CG_CalcMoveSpeeds (bg_character_t *character)
Calculate move speeds.
static qboolean CG_ParseAnimationFiles (bg_character_t *character, const char *animationGroup, const char *animationScript)
Parse animation files.
static qboolean CG_CheckForExistingAnimModelInfo (const char *animationGroup, const char *animationScript, animModelInfo_t **animModelInfo)
Check for existing animation model information.
static qboolean CG_RegisterAcc (const char *modelName, int *model, const char *skinname, qhandle_t *skin)
Register accessories.
qboolean CG_RegisterCharacter (const char *characterFile, bg_character_t *character)
Register character.
bg_character_t * CG_CharacterForClientinfo (clientInfo_t *ci, centity_t *cent)
Character for clientinfo.
bg_character_t * CG_CharacterForPlayerstate (playerState_t *ps)
Character for playerstate.
void CG_RegisterPlayerClasses (void)
Register player classes.
Variables
char bigTextBuffer [100000]
static acc_t cg_accessories []
static int cg_numAccessories = sizeof(cg_accessories) / sizeof(cg_accessories[0])
static acc_t cg_headAccessories []
static int cg_numHeadAccessories = sizeof(cg_headAccessories) / sizeof(cg_headAccessories[0])
Detailed Description
Character loading.
Definition in file cg_character.c.
Function Documentation
static void CG_CalcMoveSpeeds (bg_character_t * character) static
Calculate move speeds.
Calculate movement speeds.
Parameters
[in] character
Definition at line 217 of file cg_character.c.
Referenced by CG_ParseAnimationFiles().
bg_character_t* CG_CharacterForClientinfo (clientInfo_t * ci, centity_t * cent)
Character for clientinfo.
Define character for clientinfo.
Parameters
[in] ci
[in] cent
Returns
Definition at line 583 of file cg_character.c.
Referenced by CG_AddFragment(), CG_EntityEvent(), CG_GetBleedOrigin(), CG_GibPlayer(), CG_LoseHat(), CG_Player(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PredictPlayerState(), CG_SetLerpFrameAnimation(), and CG_SetLerpFrameAnimationRate().
bg_character_t* CG_CharacterForPlayerstate (playerState_t * ps)
Character for playerstate.
Define character for playerstate.
Parameters
[in] ps
Returns
Definition at line 626 of file cg_character.c.
Referenced by CG_DrawPlayerStatusHead().
static qboolean CG_CheckForExistingAnimModelInfo (const char * animationGroup, const char * animationScript, animModelInfo_t ** animModelInfo) static
Check for existing animation model information.
If this player model has already been parsed, then use the existing information. Otherwise, set the modelInfo pointer to the first free slot.
Parameters
[in] animationGroup
[in] animationScript
[in] animModelInfo
Returns
Definition at line 358 of file cg_character.c.
Referenced by CG_RegisterCharacter().
static qboolean CG_ParseAnimationFiles (bg_character_t * character, const char * animationGroup, const char * animationScript) static
Parse animation files.
Read in all the configuration and script files for this model.
Parameters
[in] character
[in] animationGroup
[in] animationScript
Returns
Definition at line 309 of file cg_character.c.
Referenced by CG_RegisterCharacter().
static qboolean CG_ParseGibModels (const char * modelPath, bg_character_t * character) static
Parse gib models.
Read a configuration file containing gib models for use with this character.
Parameters
[in] modelPath
[out] character
Returns
Definition at line 47 of file cg_character.c.
Referenced by CG_RegisterCharacter().
static qboolean CG_ParseHudHeadConfig (const char * filename, animation_t * hha) static
Parse HUD head config.
Parse HUD head config
Parameters
[in] filename
[out] hha
Returns
Definition at line 115 of file cg_character.c.
Referenced by CG_RegisterCharacter().
static qboolean CG_RegisterAcc (const char * modelName, int * model, const char * skinname, qhandle_t * skin) static
Register accessories.
Register model accessories.
Parameters
[in] modelName
[in,out] model
[in] skinname
[out] skin
Returns
Definition at line 404 of file cg_character.c.
Referenced by CG_RegisterCharacter().
qboolean CG_RegisterCharacter (const char * characterFile, bg_character_t * character)
Register character.
Register character.
Parameters
[in] characterFile
[in] character
Returns
Definition at line 457 of file cg_character.c.
Referenced by CG_ConfigStringModified(), CG_RegisterGraphics(), and CG_RegisterPlayerClasses().
void CG_RegisterPlayerClasses (void)
Register player classes.
Register player classes.
Definition at line 656 of file cg_character.c.
Referenced by CG_RegisterGraphics().
Variable Documentation
acc_t cg_accessories[] static
Initial value:
=
{
    { "md3_beltr",   ACC_BELT_LEFT  },
    { "md3_beltl",   ACC_BELT_RIGHT },
    { "md3_belt",    ACC_BELT       },
    { "md3_back",    ACC_BACK       },
    { "md3_weapon",  ACC_WEAPON     },
    { "md3_weapon2", ACC_WEAPON2    },
}
Definition at line 428 of file cg_character.c.
acc_t cg_headAccessories[] static
Initial value:
=
{
    { "md3_hat",  ACC_HAT    },
    { "md3_rank", ACC_RANK   },
    { "md3_hat2", ACC_MOUTH2 },
    { "md3_hat3", ACC_MOUTH3 },
}
Definition at line 440 of file cg_character.c.
int cg_numAccessories = sizeof(cg_accessories) / sizeof(cg_accessories[0]) static
Definition at line 438 of file cg_character.c.
Referenced by CG_RegisterCharacter().
int cg_numHeadAccessories = sizeof(cg_headAccessories) / sizeof(cg_headAccessories[0]) static
Definition at line 448 of file cg_character.c.
Referenced by CG_RegisterCharacter().