ET: Legacy: src/cgame/cg_popupmessages.c File Reference
cg_popupmessages.c File Reference
#include "cg_local.h"
Data Structures
struct pmStackItem_s
struct pmStackItemBig_s
Macros
#define NUM_PM_STACK_ITEMS 32
#define NUM_PM_STACK_ITEMS_BIG 8
#define PM_FADETIME_BIG 1000
#define PM_WAITTIME_BIG 3500
#define PM_BIGPOPUP_TIME 2500
#define PM_ICON_SIZE_NORMAL 20
#define PM_ICON_SIZE_SMALL 12
#define ICON_Y_OFFSET(y) y + 3
Typedefs
typedef struct pmStackItem_s pmListItem_t
typedef struct pmStackItemBig_s pmListItemBig_t
Functions
void CG_PMItemBigSound (pmListItemBig_t *item)
CG_PMItemBigSound.
void CG_InitPMGraphics (void)
CG_InitPMGraphics.
void CG_InitPM (void)
CG_InitPM.
void CG_AddToListFront (pmListItem_t **list, pmListItem_t *item)
CG_AddToListFront.
void CG_UpdatePMLists (void)
CG_UpdatePMLists.
pmListItemBig_t * CG_FindFreePMItem2 (void)
CG_FindFreePMItem2.
pmListItem_t * CG_FindFreePMItem (void)
CG_FindFreePMItem.
static qboolean CG_CheckPMItemFilter (popupMessageType_t type)
CG_CheckPMItemFilter.
void CG_AddPMItem (popupMessageType_t type, const char *message, const char *message2, qhandle_t shader, qhandle_t weaponShader, int scaleShader, vec3_t color)
CG_AddPMItem.
void CG_AddPMItemBig (popupMessageBigType_t type, const char *message, qhandle_t shader)
CG_AddPMItemBig.
void CG_DrawPMItems (rectDef_t rect, int style)
CG_DrawPMItems.
void CG_DrawPMItemsBig (void)
CG_DrawPMItemsBig.
const char * CG_GetPMItemText (centity_t *cent)
CG_GetPMItemText.
void CG_PlayPMItemSound (centity_t *cent)
CG_PlayPMItemSound.
qhandle_t CG_GetPMItemIcon (centity_t *cent)
CG_GetPMItemIcon.
Variables
pmListItem_t cg_pmStack [NUM_PM_STACK_ITEMS]
pmListItem_t * cg_pmOldList
pmListItem_t * cg_pmWaitingList
pmListItemBig_t * cg_pmWaitingListBig
pmListItemBig_t cg_pmStackBig [NUM_PM_STACK_ITEMS_BIG]
const char * cg_skillRewards [SK_NUM_SKILLS][NUM_SKILL_LEVELS-1]
static int lastSoundTime = 0
Macro Definition Documentation
#define ICON_Y_OFFSET (y) y + 3
Definition at line 602 of file cg_popupmessages.c.
Referenced by CG_DrawPMItems().
#define NUM_PM_STACK_ITEMS 32
Definition at line 37 of file cg_popupmessages.c.
Referenced by CG_FindFreePMItem().
#define NUM_PM_STACK_ITEMS_BIG 8
Definition at line 38 of file cg_popupmessages.c.
Referenced by CG_FindFreePMItem2().
#define PM_BIGPOPUP_TIME 2500
Definition at line 147 of file cg_popupmessages.c.
Referenced by CG_DrawPMItemsBig(), and CG_UpdatePMLists().
#define PM_FADETIME_BIG 1000
Definition at line 145 of file cg_popupmessages.c.
#define PM_ICON_SIZE_NORMAL 20
Definition at line 600 of file cg_popupmessages.c.
Referenced by CG_DrawPMItems().
#define PM_ICON_SIZE_SMALL 12
Definition at line 601 of file cg_popupmessages.c.
Referenced by CG_DrawPMItems().
#define PM_WAITTIME_BIG 3500
Definition at line 146 of file cg_popupmessages.c.
Typedef Documentation
typedef struct pmStackItem_s pmListItem_t
Definition at line 40 of file cg_popupmessages.c.
typedef struct pmStackItemBig_s pmListItemBig_t
Definition at line 41 of file cg_popupmessages.c.
Function Documentation
void CG_AddPMItem (popupMessageType_t type, const char * message, const char * message2, qhandle_t shader, qhandle_t weaponShader, int scaleShader, vec3_t color)
CG_AddPMItem.
Parameters
[in] type
[in] message
[in] message2
[in] shader
[in] weaponShader
[in] scaleShader
[in] color
Todo:
: translate this (does it makes sense?)
Definition at line 400 of file cg_popupmessages.c.
Referenced by CG_CPM_f(), CG_EntityEvent(), CG_ItemPickup(), CG_Obituary(), and CG_ServerCommand().
void CG_AddPMItemBig (popupMessageBigType_t type, const char * message, qhandle_t shader)
CG_AddPMItemBig.
Parameters
[in] type
[in] message
[in] shader
Definition at line 555 of file cg_popupmessages.c.
Referenced by CG_NewClientInfo().
void CG_AddToListFront (pmListItem_t ** list, pmListItem_t * item)
CG_AddToListFront.
Parameters
[in,out] list
[in,out] item
Definition at line 154 of file cg_popupmessages.c.
Referenced by CG_UpdatePMLists().
static qboolean CG_CheckPMItemFilter (popupMessageType_t type) static
CG_CheckPMItemFilter.
Parameters
[in] type
Returns
Definition at line 343 of file cg_popupmessages.c.
Referenced by CG_AddPMItem().
void CG_DrawPMItems (rectDef_t rect, int style)
CG_DrawPMItems.
Parameters
[in] rect
[in] style
Definition at line 609 of file cg_popupmessages.c.
Referenced by CG_DrawGlobalHud().
void CG_DrawPMItemsBig (void)
CG_DrawPMItemsBig.
Definition at line 775 of file cg_popupmessages.c.
Referenced by CG_DrawGlobalHud().
pmListItem_t* CG_FindFreePMItem (void)
CG_FindFreePMItem.
Returns
Definition at line 295 of file cg_popupmessages.c.
Referenced by CG_AddPMItem().
pmListItemBig_t* CG_FindFreePMItem2 (void)
CG_FindFreePMItem2.
Returns
Definition at line 276 of file cg_popupmessages.c.
Referenced by CG_AddPMItemBig().
qhandle_t CG_GetPMItemIcon (centity_t * cent)
CG_GetPMItemIcon.
Parameters
[in] cent
Returns
Definition at line 997 of file cg_popupmessages.c.
Referenced by CG_EntityEvent().
const char* CG_GetPMItemText (centity_t * cent)
CG_GetPMItemText.
Parameters
[in] cent
Returns
Definition at line 806 of file cg_popupmessages.c.
Referenced by CG_EntityEvent().
void CG_InitPM (void)
CG_InitPM.
Definition at line 127 of file cg_popupmessages.c.
Referenced by CG_Init(), and CG_MapRestart().
void CG_InitPMGraphics (void)
CG_InitPMGraphics.
Definition at line 93 of file cg_popupmessages.c.
Referenced by CG_RegisterGraphics().
void CG_PlayPMItemSound (centity_t * cent)
CG_PlayPMItemSound.
Parameters
[in] cent
Definition at line 908 of file cg_popupmessages.c.
Referenced by CG_EntityEvent().
void CG_PMItemBigSound (pmListItemBig_t * item)
CG_PMItemBigSound.
Parameters
item
Todo:
: handle case missing ?
Definition at line 528 of file cg_popupmessages.c.
Referenced by CG_AddPMItemBig(), and CG_UpdatePMLists().
void CG_UpdatePMLists (void)
CG_UpdatePMLists.
Definition at line 163 of file cg_popupmessages.c.
Referenced by CG_DrawActiveFrame().
Variable Documentation
pmListItem_t* cg_pmOldList
Definition at line 71 of file cg_popupmessages.c.
Referenced by CG_DrawPMItems(), and CG_UpdatePMLists().
pmListItem_t cg_pmStack[NUM_PM_STACK_ITEMS]
Definition at line 70 of file cg_popupmessages.c.
pmListItemBig_t cg_pmStackBig[NUM_PM_STACK_ITEMS_BIG]
Definition at line 75 of file cg_popupmessages.c.
pmListItem_t* cg_pmWaitingList
Definition at line 72 of file cg_popupmessages.c.
Referenced by CG_AddPMItem().
pmListItemBig_t* cg_pmWaitingListBig
Definition at line 73 of file cg_popupmessages.c.
Referenced by CG_AddPMItemBig().
const char* cg_skillRewards[SK_NUM_SKILLS][NUM_SKILL_LEVELS-1]
Initial value:
=
{
    { "Binoculars for any Class",                 "Improved Physical Fitness",                 "Improved Health",                       "Trap Awareness"           },
    { "Improved use of Explosive Ammunition",     "Improved Dexterity",                        "Improved Construction and Destruction", "a Flak Jacket"            },
    { "Medic Ammo",                               "Improved First Aid Resources",              "Full Revive",                           "Adrenalin Self"           },
    { "Improved Ammo Resources",                  "Improved Signals",                          "Improved Air and Ground Support",       "Enemy Recognition"        },
    { "Improved use of Light Weapon Ammunition",  "Faster Reload",                             "Improved Light Weapon Handling",        "Dual-Wield Pistols"       },
    { "Improved Projectile Resources",            "Heavy Weapon Proficiency",                  "Improved Dexterity",                    "Improved Weapon Handling" },
    { "Improved use of Scoped Weapon Ammunition", "Improved use of Sabotage and Misdirection", "Breath Control",                        "Assassin"                 }
}
Definition at line 77 of file cg_popupmessages.c.
Referenced by CG_NewClientInfo().
int lastSoundTime = 0 static
Definition at line 902 of file cg_popupmessages.c.
Referenced by CG_PlayPMItemSound().