ET: Legacy: src/cgame/cg_players.c File Reference
cg_players.c File Reference
Handle the media and animation for player entities.
#include "cg_local.h"
Data Structures
struct shadowPart_t
Macros
#define SWING_RIGHT 1.f
#define SWING_LEFT 2.f
#define ANIM_SCALEMAX_LOW 1.1f
#define ANIM_SCALEMAX_HIGH 1.6f
#define ANIM_SPEEDMAX_LOW 100
#define ANIM_SPEEDMAX_HIGH 20
#define LEAN_MAX 28.0f
#define LEAN_TIME_TO 200.0f
#define LEAN_TIME_FR 300.0f
#define SHADOW_DISTANCE 64
#define ZOFS 6.0f
#define SHADOW_MIN_DIST 250.0f
#define SHADOW_MAX_DIST 512.0f
Functions
qboolean CG_EntOnFire (centity_t *cent)
CG_EntOnFire.
qboolean CG_IsCrouchingAnim (animModelInfo_t *animModelInfo, int animNum)
CG_IsCrouchingAnim.
sfxHandle_t CG_CustomSound (int clientNum, const char *soundName)
CG_CustomSound.
static void CG_LoadClientInfo (int clientNum)
Load it now, taking the disk hits. This will usually be deferred to a safe time.
void CG_ParseTeamXPs (int n)
CG_ParseTeamXPs.
void CG_LimboPanel_SendSetupMsg (qboolean forceteam)
CG_LimboPanel_SendSetupMsg.
void CG_NewClientInfo (int clientNum)
CG_NewClientInfo.
bg_playerclass_t * CG_PlayerClassForClientinfo (clientInfo_t *ci, centity_t *cent)
CG_PlayerClassForClientinfo.
static void CG_SetLerpFrameAnimation (centity_t *cent, clientInfo_t *ci, lerpFrame_t *lf, int newAnimation)
CG_SetLerpFrameAnimation.
void CG_RunLerpFrame (centity_t *cent, clientInfo_t *ci, lerpFrame_t *lf, int newAnimation, float speedScale)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
static void CG_ClearLerpFrame (centity_t *cent, clientInfo_t *ci, lerpFrame_t *lf, int animationNumber)
CG_ClearLerpFrame.
void CG_SetLerpFrameAnimationRate (centity_t *cent, clientInfo_t *ci, lerpFrame_t *lf, int newAnimation)
CG_SetLerpFrameAnimationRate.
void CG_RunLerpFrameRate (clientInfo_t *ci, lerpFrame_t *lf, int newAnimation, centity_t *cent, int recursion)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
void CG_ClearLerpFrameRate (centity_t *cent, clientInfo_t *ci, lerpFrame_t *lf, int animationNumber)
CG_ClearLerpFrameRate.
void CG_SetLerpFrameAnimationRateCorpse (centity_t *cent, lerpFrame_t *lf, int newAnimation)
Similar to CG_RunLerpFrameRate, simplifed, and sets remaining animation, so animation won't be replayed.
void CG_RunLerpFrameRateCorpse (clientInfo_t *ci, lerpFrame_t *lf, int newAnimation, centity_t *cent, int recursion)
Simplifed code for corpses.
static void CG_PlayerAnimation (centity_t *cent, refEntity_t *body)
CG_PlayerAnimation.
static void CG_SwingAngles (float destination, float swingTolerance, float clampTolerance, float speed, float *angle, qboolean *swinging)
CG_SwingAngles.
static void CG_AddPainTwitch (centity_t *cent, vec3_t torsoAngles)
CG_AddPainTwitch.
void CG_PredictLean (centity_t *cent, vec3_t torsoAngles, vec3_t headAngles, int viewHeight)
CG_PredictLean.
static void CG_PlayerAngles (centity_t *cent, vec3_t legs[3], vec3_t torso[3], vec3_t head[3])
Handles seperate torso motion.
static void CG_BreathPuffs (centity_t *cent, refEntity_t *head)
CG_BreathPuffs.
static void CG_PlayerFloatSprite (centity_t *cent, qhandle_t shader, int height, int off)
Float a sprite over the player's head added height parameter.
static void CG_PlayerFloatText (centity_t *cent, const char *text, int height)
CG_PlayerFloatText.
static void CG_PlayerSprites (centity_t *cent)
Float sprites over the player's head.
static qboolean CG_PlayerShadow (centity_t *cent, float *shadowPlane)
Returns the Z component of the surface being shadowed.
static void CG_PlayerSplash (centity_t *cent)
Draw a mark at the water surface.
void CG_AddRefEntityWithPowerups (refEntity_t *ent, int powerups, int team, entityState_t *es, const vec3_t fireRiseDir)
Adds a piece with modifications or duplications for powerups Also called by CG_Missile for quad rockets, but nobody can tell...
void CG_AnimPlayerConditions (bg_character_t *character, centity_t *cent)
Predict, or calculate condition for this entity, if it is not the local client.
void CG_Player (centity_t *cent)
CG_Player.
void CG_ResetPlayerEntity (centity_t *cent)
A player just came into view or teleported, so reset all animation info.
void CG_GetBleedOrigin (vec3_t head_origin, vec3_t body_origin, int fleshEntityNum)
CG_GetBleedOrigin.
qboolean CG_GetTag (int clientNum, const char *tagname, orientation_t *orientation)
CG_GetTag.
qboolean CG_GetWeaponTag (int clientNum, const char *tagname, orientation_t *orientation)
CG_GetWeaponTag.
void CG_SetHudHeadLerpFrameAnimation (bg_character_t *ch, lerpFrame_t *lf, int newAnimation)
CG_SetHudHeadLerpFrameAnimation.
void CG_ClearHudHeadLerpFrame (bg_character_t *ch, lerpFrame_t *lf, int animationNumber)
CG_ClearHudHeadLerpFrame.
void CG_RunHudHeadLerpFrame (bg_character_t *ch, lerpFrame_t *lf, int newAnimation, float speedScale)
CG_RunHudHeadLerpFrame.
void CG_HudHeadAnimation (bg_character_t *ch, lerpFrame_t *lf, int *oldframe, int *frame, float *backlerp, hudHeadAnimNumber_t animation)
CG_HudHeadAnimation.
Variables
const char * cg_skillRewards [SK_NUM_SKILLS][NUM_SKILL_LEVELS-1]
Detailed Description
Handle the media and animation for player entities.
Definition in file cg_players.c.
Macro Definition Documentation
#define ANIM_SCALEMAX_HIGH 1.6f
Definition at line 705 of file cg_players.c.
Referenced by CG_RunLerpFrameRate().
#define ANIM_SCALEMAX_LOW 1.1f
Definition at line 704 of file cg_players.c.
Referenced by CG_RunLerpFrameRate().
#define ANIM_SPEEDMAX_HIGH 20
Definition at line 708 of file cg_players.c.
Referenced by CG_RunLerpFrameRate().
#define ANIM_SPEEDMAX_LOW 100
Definition at line 707 of file cg_players.c.
Referenced by CG_RunLerpFrameRate().
#define LEAN_MAX 28.0f
Definition at line 1446 of file cg_players.c.
Referenced by CG_PredictLean().
#define LEAN_TIME_FR 300.0f
Definition at line 1448 of file cg_players.c.
Referenced by CG_PredictLean().
#define LEAN_TIME_TO 200.0f
Definition at line 1447 of file cg_players.c.
Referenced by CG_PredictLean().
#define SHADOW_DISTANCE 64
Definition at line 2051 of file cg_players.c.
Referenced by CG_PlayerShadow().
#define SHADOW_MAX_DIST 512.0f
Definition at line 2054 of file cg_players.c.
Referenced by CG_PlayerShadow().
#define SHADOW_MIN_DIST 250.0f
Definition at line 2053 of file cg_players.c.
Referenced by CG_PlayerShadow().
#define SWING_LEFT 2.f
Definition at line 39 of file cg_players.c.
Referenced by CG_SwingAngles().
#define SWING_RIGHT 1.f
Definition at line 38 of file cg_players.c.
Referenced by CG_PlayerAnimation(), and CG_SwingAngles().
#define ZOFS 6.0f
Definition at line 2052 of file cg_players.c.
Referenced by CG_PlayerShadow().
Function Documentation
static void CG_AddPainTwitch (centity_t * cent, vec3_t torsoAngles) static
CG_AddPainTwitch.
Parameters
[in,out] cent
[in] torsoAngles
Note
direction unused ?
Definition at line 1384 of file cg_players.c.
Referenced by CG_PlayerAngles().
void CG_AddRefEntityWithPowerups (refEntity_t * ent, int powerups, int team, entityState_t * es, const vec3_t fireRiseDir)
Adds a piece with modifications or duplications for powerups Also called by CG_Missile for quad rockets, but nobody can tell...
Parameters
[in,out] ent
[in] powerups - unused
[in] team - unused
[in] es
[in] fireRiseDir
Todo:
: onFire is always true !
Definition at line 2329 of file cg_players.c.
Referenced by CG_Missile(), and CG_Player().
void CG_AnimPlayerConditions (bg_character_t * character, centity_t * cent)
Predict, or calculate condition for this entity, if it is not the local client.
Parameters
[in] character
[in] cent
Definition at line 2406 of file cg_players.c.
Referenced by CG_Player().
static void CG_BreathPuffs (centity_t * cent, refEntity_t * head) static
CG_BreathPuffs.
Parameters
[in] cent
[in] head
Definition at line 1785 of file cg_players.c.
Referenced by CG_Player().
void CG_ClearHudHeadLerpFrame (bg_character_t * ch, lerpFrame_t * lf, int animationNumber)
CG_ClearHudHeadLerpFrame.
Parameters
[in] ch
[in,out] lf
animationNumber
Definition at line 3264 of file cg_players.c.
Referenced by CG_RunHudHeadLerpFrame().
static void CG_ClearLerpFrame (centity_t * cent, clientInfo_t * ci, lerpFrame_t * lf, int animationNumber) static
CG_ClearLerpFrame.
Parameters
[in] cent
[in] ci
[in,out] lf
animationNumber
Definition at line 589 of file cg_players.c.
Referenced by CG_ResetPlayerEntity().
void CG_ClearLerpFrameRate (centity_t * cent, clientInfo_t * ci, lerpFrame_t * lf, int animationNumber)
CG_ClearLerpFrameRate.
Parameters
[in] cent
[in] ci
[in,out] lf
[in] animationNumber
Definition at line 1023 of file cg_players.c.
Referenced by CG_ResetPlayerEntity().
sfxHandle_t CG_CustomSound (int clientNum, const char * soundName)
CG_CustomSound.
Parameters
clientNum - unused
[in] soundName
Returns
Definition at line 99 of file cg_players.c.
Referenced by CG_EntityEvent(), and CG_PlayGlobalSound().
qboolean CG_EntOnFire (centity_t * cent)
CG_EntOnFire.
Parameters
[in] cent
Returns
Definition at line 48 of file cg_players.c.
Referenced by CG_AddRefEntityWithPowerups(), CG_EntityEffects(), CG_LaunchGib(), CG_LoseHat(), and CG_TransitionEntity().
void CG_GetBleedOrigin (vec3_t head_origin, vec3_t body_origin, int fleshEntityNum)
CG_GetBleedOrigin.
Parameters
[in] head_origin
[in] body_origin
[in] fleshEntityNum
Definition at line 3076 of file cg_players.c.
Referenced by CG_Bleed().
qboolean CG_GetTag (int clientNum, const char * tagname, orientation_t * orientation)
CG_GetTag.
Parameters
[in] clientNum
[in] tagname
[in,out] orientation
Returns
Definition at line 3132 of file cg_players.c.
Referenced by vmMain().
qboolean CG_GetWeaponTag (int clientNum, const char * tagname, orientation_t * orientation)
CG_GetWeaponTag.
Parameters
[in] clientNum
[in] tagname
[in,out] orientation
Returns
Definition at line 3184 of file cg_players.c.
Referenced by CG_SpawnTracer().
void CG_HudHeadAnimation (bg_character_t * ch, lerpFrame_t * lf, int * oldframe, int * frame, float * backlerp, hudHeadAnimNumber_t animation)
CG_HudHeadAnimation.
Parameters
[in] ch
[in] lf
[out] oldframe
[out] frame
[out] backlerp
[in] animation
Definition at line 3372 of file cg_players.c.
Referenced by CG_DrawPlayerHead(), and CG_Player().
qboolean CG_IsCrouchingAnim (animModelInfo_t * animModelInfo, int animNum)
CG_IsCrouchingAnim.
Parameters
[in] animModelInfo
[in] animNum
Returns
Todo:
: make compatible with new scripting
Definition at line 77 of file cg_players.c.
Referenced by CG_SetLerpFrameAnimationRate().
void CG_LimboPanel_SendSetupMsg (qboolean forceteam)
CG_LimboPanel_SendSetupMsg.
Parameters
[in] forceteam
Todo:
: handle all case ?
Definition at line 1314 of file cg_limbopanel.c.
Referenced by CG_LimboPanel_ClassButton_KeyDown(), CG_LimboPanel_OkButton_KeyDown(), CG_NewClientInfo(), and CG_ParseTeamXPs().
static void CG_LoadClientInfo (int clientNum) static
Load it now, taking the disk hits. This will usually be deferred to a safe time.
Parameters
clientNum
Definition at line 120 of file cg_players.c.
Referenced by CG_NewClientInfo().
void CG_NewClientInfo (int clientNum)
CG_NewClientInfo.
Parameters
[in] clientNum
Todo:
: make these more secure)
Definition at line 174 of file cg_players.c.
Referenced by CG_ConfigStringModified(), and CG_RegisterClients().
void CG_ParseTeamXPs (int n)
CG_ParseTeamXPs.
Parameters
[in] n
Definition at line 139 of file cg_players.c.
Referenced by CG_ConfigStringModified().
void CG_Player (centity_t * cent)
CG_Player.
Parameters
[in,out] cent
Todo:
: buggy
Definition at line 2483 of file cg_players.c.
Referenced by CG_ProcessEntity().
static void CG_PlayerAngles (centity_t * cent, vec3_t legs[3], vec3_t torso[3], vec3_t head[3]) static
Handles seperate torso motion.
legs pivot based on direction of movement
head always looks exactly at cent->lerpAngles
if motion < 20 degrees, show in head only if < 45 degrees, also show in torso
Parameters
[in,out] cent
[in] legs
[in] torso
[in] head
Todo:
: what is this strstr hack??
Definition at line 1607 of file cg_players.c.
Referenced by CG_GetBleedOrigin(), and CG_Player().
static void CG_PlayerAnimation (centity_t * cent, refEntity_t * body) static
CG_PlayerAnimation.
Parameters
[in] cent
[out] body
Definition at line 1219 of file cg_players.c.
Referenced by CG_GetBleedOrigin(), and CG_Player().
bg_playerclass_t* CG_PlayerClassForClientinfo (clientInfo_t * ci, centity_t * cent)
CG_PlayerClassForClientinfo.
Parameters
[in] ci
[in] cent
Returns
Definition at line 418 of file cg_players.c.
Referenced by CG_DrawMap(), and CG_DrawMapEntity().
static void CG_PlayerFloatSprite (centity_t * cent, qhandle_t shader, int height, int off) static
Float a sprite over the player's head added height parameter.
Parameters
[in] cent
[in] shader
[in] height
[in] off
Todo:
: adjust origin for others
Definition at line 1841 of file cg_players.c.
Referenced by CG_PlayerSprites().
static void CG_PlayerFloatText (centity_t * cent, const char * text, int height) static
CG_PlayerFloatText.
Parameters
[in] cent
[in] text
[in] height
Definition at line 1915 of file cg_players.c.
Referenced by CG_PlayerSprites().
static qboolean CG_PlayerShadow (centity_t * cent, float * shadowPlane) static
Returns the Z component of the surface being shadowed.
Parameters
[in] cent
[in,out] shadowPlane
Returns
Note
TODO: Should it return a full plane instead of a Z?
Definition at line 2072 of file cg_players.c.
Referenced by CG_Player().
static void CG_PlayerSplash (centity_t * cent) static
Draw a mark at the water surface.
Parameters
[in] cent
Definition at line 2233 of file cg_players.c.
Referenced by CG_Player().
static void CG_PlayerSprites (centity_t * cent) static
Float sprites over the player's head.
Parameters
[in] cent
Definition at line 1937 of file cg_players.c.
Referenced by CG_Player().
void CG_PredictLean (centity_t * cent, vec3_t torsoAngles, vec3_t headAngles, int viewHeight)
CG_PredictLean.
Parameters
[in,out] cent
[in] torsoAngles
[in] headAngles
[in] viewHeight
Definition at line 1457 of file cg_players.c.
Referenced by CG_PlayerAngles().
void CG_ResetPlayerEntity (centity_t * cent)
A player just came into view or teleported, so reset all animation info.
Parameters
[in,out] cent
Definition at line 3034 of file cg_players.c.
Referenced by CG_LoadClientInfo(), and CG_ResetEntity().
void CG_RunHudHeadLerpFrame (bg_character_t * ch, lerpFrame_t * lf, int newAnimation, float speedScale)
CG_RunHudHeadLerpFrame.
Parameters
[in] ch
[in,out] lf
[in] newAnimation
[in] speedScale
Definition at line 3279 of file cg_players.c.
Referenced by CG_HudHeadAnimation().
void CG_RunLerpFrame (centity_t * cent, clientInfo_t * ci, lerpFrame_t * lf, int newAnimation, float speedScale)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
Parameters
[in] cent
[in] ci
[in,out] lf
[in] newAnimation
[in] speedScale
Definition at line 489 of file cg_players.c.
Referenced by CG_Trap().
void CG_RunLerpFrameRate (clientInfo_t * ci, lerpFrame_t * lf, int newAnimation, centity_t * cent, int recursion)
Sets cg.snap, cg.oldFrame, and cg.backlerp cg.time should be between oldFrameTime and frameTime after exit.
Parameters
[in] ci
[in,out] lf
[in] newAnimation
[in] cent
[in] recursion
anim->moveSpeed ||
Definition at line 719 of file cg_players.c.
Referenced by CG_PlayerAnimation().
void CG_RunLerpFrameRateCorpse (clientInfo_t * ci, lerpFrame_t * lf, int newAnimation, centity_t * cent, int recursion)
Simplifed code for corpses.
Parameters
[in] ci - unused
[in,out] lf
[in] newAnimation
[in] cent
[in] recursion - unused
Definition at line 1110 of file cg_players.c.
Referenced by CG_PlayerAnimation().
void CG_SetHudHeadLerpFrameAnimation (bg_character_t * ch, lerpFrame_t * lf, int newAnimation)
CG_SetHudHeadLerpFrameAnimation.
Parameters
[in] ch
[in,out] lf
[in] newAnimation
Definition at line 3240 of file cg_players.c.
Referenced by CG_ClearHudHeadLerpFrame(), and CG_RunHudHeadLerpFrame().
static void CG_SetLerpFrameAnimation (centity_t * cent, clientInfo_t * ci, lerpFrame_t * lf, int newAnimation) static
CG_SetLerpFrameAnimation.
Parameters
cent
ci
lf
newAnimation
Note
May include ANIM_TOGGLEBIT
Definition at line 448 of file cg_players.c.
Referenced by CG_ClearLerpFrame(), and CG_RunLerpFrame().
void CG_SetLerpFrameAnimationRate (centity_t * cent, clientInfo_t * ci, lerpFrame_t * lf, int newAnimation)
CG_SetLerpFrameAnimationRate.
Parameters
[in] cent
[in] ci
[in,out] lf
[in] newAnimation
Note
May include ANIM_TOGGLEBIT
Definition at line 608 of file cg_players.c.
Referenced by CG_ClearLerpFrameRate(), and CG_RunLerpFrameRate().
void CG_SetLerpFrameAnimationRateCorpse (centity_t * cent, lerpFrame_t * lf, int newAnimation)
Similar to CG_RunLerpFrameRate, simplifed, and sets remaining animation, so animation won't be replayed.
Parameters
[in] cent
[in,out] lf
[in] newAnimation
Definition at line 1040 of file cg_players.c.
Referenced by CG_RunLerpFrameRateCorpse().
static void CG_SwingAngles (float destination, float swingTolerance, float clampTolerance, float speed, float * angle, qboolean * swinging) static
CG_SwingAngles.
Parameters
[in] destination
[in] swingTolerance
[in] clampTolerance
[in] speed
[in,out] angle
[in,out] swinging
Definition at line 1304 of file cg_players.c.
Referenced by CG_PlayerAngles().
Variable Documentation
const char* cg_skillRewards[SK_NUM_SKILLS][NUM_SKILL_LEVELS-1]
Definition at line 77 of file cg_popupmessages.c.
Referenced by CG_NewClientInfo().