ET: Legacy: src/cgame/cg_spawn.c File Reference
cg_spawn.c File Reference
Client sided only map entities.
#include "cg_local.h"
Data Structures
struct spawn_t
Macros
#define NUMSPAWNS (int)(sizeof(spawns) / sizeof(spawn_t))
Functions
qboolean CG_SpawnString (const char *key, const char *defaultString, char **out)
CG_SpawnString.
qboolean CG_SpawnFloat (const char *key, const char *defaultString, float *out)
CG_SpawnFloat.
qboolean CG_SpawnInt (const char *key, const char *defaultString, int *out)
CG_SpawnInt.
qboolean CG_SpawnVector (const char *key, const char *defaultString, float *out)
CG_SpawnVector.
qboolean CG_SpawnVector2D (const char *key, const char *defaultString, float *out)
CG_SpawnVector2D.
char * vtos (const vec3_t v)
This is just a convenience function for printing vectors.
void SP_path_corner_2 (void)
SP_path_corner_2.
void SP_info_train_spline_main (void)
SP_info_train_spline_main.
void CG_corona (void)
CG_corona.
void SP_misc_gamemodel (void)
SP_misc_gamemodel.
void SP_trigger_objective_info (void)
SP_trigger_objective_info.
void CG_ParseEntityFromSpawnVars (void)
Spawn an entity and fill in all of the level fields from cg.spawnVars[], then call the class specfic spawn function.
char * CG_AddSpawnVarToken (const char *string)
CG_AddSpawnVarToken.
qboolean CG_ParseSpawnVars (void)
Parses a brace bounded set of key / value pairs out of the level's entity strings into cg.spawnVars[].
void SP_worldspawn (void)
SP_worldspawn.
void CG_ParseEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
Variables
spawn_t spawns []
Detailed Description
Client sided only map entities.
Definition in file cg_spawn.c.
Macro Definition Documentation
#define NUMSPAWNS (int)(sizeof(spawns) / sizeof(spawn_t))
Definition at line 384 of file cg_spawn.c.
Referenced by CG_ParseEntityFromSpawnVars().
Function Documentation
char* CG_AddSpawnVarToken (const char * string)
CG_AddSpawnVarToken.
Parameters
[in] string
Returns
Definition at line 420 of file cg_spawn.c.
Referenced by CG_ParseSpawnVars().
void CG_corona (void)
CG_corona.
Definition at line 230 of file cg_spawn.c.
void CG_ParseEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
Definition at line 696 of file cg_spawn.c.
Referenced by CG_MapRestart(), and CG_RegisterGraphics().
void CG_ParseEntityFromSpawnVars (void)
Spawn an entity and fill in all of the level fields from cg.spawnVars[], then call the class specfic spawn function.
Definition at line 390 of file cg_spawn.c.
Referenced by CG_ParseEntitiesFromString().
qboolean CG_ParseSpawnVars (void)
Parses a brace bounded set of key / value pairs out of the level's entity strings into cg.spawnVars[].
This does not actually spawn an entity.
Returns
Definition at line 446 of file cg_spawn.c.
Referenced by CG_ParseEntitiesFromString().
qboolean CG_SpawnFloat (const char * key, const char * defaultString, float * out)
CG_SpawnFloat.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 75 of file cg_spawn.c.
Referenced by CG_corona(), and SP_misc_gamemodel().
qboolean CG_SpawnInt (const char * key, const char * defaultString, int * out)
CG_SpawnInt.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 92 of file cg_spawn.c.
Referenced by CG_ParseEntityFromSpawnVars().
qboolean CG_SpawnString (const char * key, const char * defaultString, char ** out)
CG_SpawnString.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 45 of file cg_spawn.c.
Referenced by CG_corona(), CG_ParseEntityFromSpawnVars(), CG_SpawnFloat(), CG_SpawnInt(), CG_SpawnVector(), CG_SpawnVector2D(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_path_corner_2(), SP_trigger_objective_info(), and SP_worldspawn().
qboolean CG_SpawnVector (const char * key, const char * defaultString, float * out)
CG_SpawnVector.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 109 of file cg_spawn.c.
Referenced by CG_corona(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_path_corner_2(), and SP_worldspawn().
qboolean CG_SpawnVector2D (const char * key, const char * defaultString, float * out)
CG_SpawnVector2D.
Parameters
[in] key
[in] defaultString
[out] out
Returns
Definition at line 126 of file cg_spawn.c.
Referenced by SP_worldspawn().
void SP_info_train_spline_main (void)
SP_info_train_spline_main.
Definition at line 183 of file cg_spawn.c.
void SP_misc_gamemodel (void)
SP_misc_gamemodel.
Definition at line 273 of file cg_spawn.c.
void SP_path_corner_2 (void)
SP_path_corner_2.
Definition at line 159 of file cg_spawn.c.
void SP_trigger_objective_info (void)
SP_trigger_objective_info.
Definition at line 353 of file cg_spawn.c.
void SP_worldspawn (void)
SP_worldspawn.
Definition at line 504 of file cg_spawn.c.
Referenced by CG_ParseEntitiesFromString().
char* vtos (const vec3_t v)
This is just a convenience function for printing vectors.
Parameters
[in] v
Returns
Definition at line 141 of file cg_spawn.c.
Referenced by Cmd_Where_f(), FinishSpawningItem(), locateMaster(), misc_beam_start(), misc_spawner_think(), props_locker_spawn_item(), SP_func_timer(), SP_func_train(), SP_func_train_rotating(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_misc_spawner(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_path_corner(), SP_path_corner_2(), SP_props_snowGenerator(), SP_target_speaker(), SP_target_teleporter(), target_laser_start(), target_speaker_multiple(), Think_SetupTrainTargets(), and Think_SetupTrainTargets_rotating().
Variable Documentation
spawn_t spawns[]
Initial value:
=
{
    { 0,                           0                         },
    { "path_corner_2",             SP_path_corner_2          },
    { "info_train_spline_main",    SP_info_train_spline_main },
    { "info_train_spline_control", SP_path_corner_2          },
    { "trigger_objective_info",    SP_trigger_objective_info },
    { "misc_gamemodel",            SP_misc_gamemodel         },
    { "corona",                    CG_corona                 },
}
Definition at line 372 of file cg_spawn.c.