ET: Legacy: src/cgame/cg_draw_hud.c File Reference
cg_draw_hud.c File Reference
Draws the player's hud.
#include "cg_local.h"
Macros
#define SKILL_ICON_SIZE 14
#define SKILLS_X 112
#define SKILLS_Y 20
#define SKILL_BAR_OFFSET (2 * SKILL_BAR_X_INDENT)
#define SKILL_BAR_X_INDENT 0
#define SKILL_BAR_Y_INDENT 6
#define SKILL_BAR_WIDTH (SKILL_ICON_SIZE - SKILL_BAR_OFFSET)
#define SKILL_BAR_X (SKILL_BAR_OFFSET + SKILL_BAR_X_INDENT + SKILLS_X)
#define SKILL_BAR_X_SCALE (SKILL_ICON_SIZE + 2)
#define SKILL_ICON_X (SKILL_BAR_OFFSET + SKILLS_X)
#define SKILL_ICON_X_SCALE (SKILL_ICON_SIZE + 2)
#define SKILL_BAR_Y (SKILL_BAR_Y_INDENT - SKILL_BAR_OFFSET - SKILLS_Y)
#define SKILL_BAR_Y_SCALE (SKILL_ICON_SIZE + 2)
#define SKILL_ICON_Y (-(SKILL_ICON_SIZE + 2) - SKILL_BAR_OFFSET - SKILLS_Y)
#define MAXHUDS 128
#define UPPERRIGHT_X 634
#define UPPERRIGHT_W 52
#define SPEED_US_TO_KPH 15.58f
#define SPEED_US_TO_MPH 23.44f
#define MAX_FPS_FRAMES 500
Enumerations
enum althud_flags { FLAGS_MOVE_TIMERS = BIT(0), FLAGS_REMOVE_RANKS = BIT(1), FLAGS_MOVE_POPUPS = BIT(2), FLAGS_POPUPS_SHADOW = BIT(3) }
enum componentStyle { STYLE_NORMAL, STYLE_SIMPLE }
Functions
hudStucture_t * CG_GetActiveHUD ()
CG_getActiveHUD Returns reference to an active hud structure.
hudComponent_t CG_getComponent (float x, float y, float w, float h, qboolean visible, componentStyle style)
CG_getComponent.
void CG_setDefaultHudValues (hudStucture_t *hud)
CG_setDefaultHudValues.
static hudStucture_t * CG_getHudByNumber (int number)
CG_getHudByNumber.
static qboolean CG_isHudNumberAvailable (int number)
CG_isHudNumberAvailable.
static void CG_addHudToList (hudStucture_t *hud)
CG_addHudToList.
static qboolean CG_HUD_ParseError (int handle, const char *format,...)
CG_HUD_ParseError.
static qboolean CG_RectParse (int handle, rectDef_t *r)
CG_RectParse.
static qboolean CG_ParseHudComponent (int handle, hudComponent_t *comp)
CG_ParseHudComponent.
static qboolean CG_ParseHUD (int handle)
CG_ParseHUD.
static qboolean CG_ReadHudFile (const char *filename)
void CG_ReadHudScripts (void)
CG_ReadHudScripts.
static void CG_DrawPicShadowed (float x, float y, float w, float h, qhandle_t icon)
CG_DrawPicShadowed.
static void CG_DrawPlayerStatusHead (hudComponent_t comp)
CG_DrawPlayerStatusHead.
static void CG_PlayerAmmoValue (int *ammo, int *clips, int *akimboammo)
Get the current ammo and/or clip count of the holded weapon (if using ammo).
static void CG_DrawPlayerHealthBar (rectDef_t *rect)
CG_DrawPlayerHealthBar.
static void CG_DrawStaminaBar (rectDef_t *rect)
CG_DrawStaminaBar.
static void CG_DrawBreathBar (rectDef_t *rect)
Draw the breath bar.
static void CG_DrawWeapRecharge (rectDef_t *rect)
Draw weapon recharge bar.
static void CG_DrawGunIcon (rectDef_t location)
CG_DrawGunIcon.
static void CG_DrawAmmoCount (float x, float y)
CG_DrawAmmoCount.
static void CG_DrawSkillBar (float x, float y, float w, float h, int skill)
CG_DrawSkillBar.
skillType_t CG_ClassSkillForPosition (clientInfo_t *ci, int pos)
CG_ClassSkillForPosition.
static void CG_DrawPlayerHealth (float x, float y)
CG_DrawPlayerHealth.
static void CG_DrawSkills (hudComponent_t comp)
CG_DrawSkills.
static void CG_DrawXP (float x, float y)
CG_DrawXP.
static void CG_DrawRank (float x, float y)
CG_DrawRank.
static void CG_DrawPowerUps (rectDef_t rect)
CG_DrawPowerUps.
int CG_DrawField (int x, int y, int width, int value, int charWidth, int charHeight, qboolean dodrawpic, qboolean leftAlign)
CG_DrawField.
void CG_DrawLivesLeft (hudComponent_t comp)
CG_DrawLivesLeft.
void CG_InitStatsDebug (void)
CG_InitStatsDebug.
void CG_StatsDebugAddText (const char *text)
CG_StatsDebugAddText.
void CG_DrawCompassIcon (float x, float y, float w, float h, vec3_t origin, vec3_t dest, qhandle_t shader)
CG_DrawCompassIcon.
static void CG_CompasMoveLocationCalc (float *locationvalue, qboolean directionplus, qboolean animationout)
CG_CompasMoveLocationCalc.
static void CG_CompasMoveLocation (float *basex, float *basey, qboolean animationout)
CG_CompasMoveLocation.
static void CG_DrawNewCompass (rectDef_t location)
CG_DrawNewCompass.
static void CG_DrawStatsDebug (void)
CG_DrawStatsDebug.
static float CG_DrawSnapshot (float y)
CG_DrawSnapshot.
static float CG_DrawSpeed (float y)
CG_DrawSpeed.
static float CG_DrawFPS (float y)
CG_DrawFPS.
static void CG_DrawTimersAlt (rectDef_t *respawn, rectDef_t *spawntimer, rectDef_t *localtime, rectDef_t *roundtimer)
CG_DrawTimersAlt.
static float CG_DrawTimerNormal (float y)
CG_DrawTimerNormal.
static float CG_DrawLocalTime (float y)
CG_DrawLocalTime.
void CG_AddLagometerFrameInfo (void)
Adds the current interpolate / extrapolate bar for this frame.
void CG_AddLagometerSnapshotInfo (snapshot_t *snap)
Log the ping time, server framerate and number of dropped snapshots before it each time a snapshot is received.
static float CG_DrawDisconnect (float y)
Draw disconnect icon for long lag.
static float CG_DrawPing (float y)
CG_DrawPing.
static float CG_DrawLagometer (float y)
CG_DrawLagometer.
static void CG_DrawPlayerStatus (void)
Draw the player status.
static void CG_DrawPlayerStats (void)
Draw the player stats.
void CG_Hud_Setup (void)
CG_Hud_Setup.
void CG_SetHud (void)
CG_SetHud.
void CG_DrawActiveHud (void)
CG_DrawActiveHud.
void CG_DrawGlobalHud (void)
CG_DrawGlobalHud.
void CG_DrawUpperRight (void)
CG_DrawUpperRight.
Variables
int hudCount = 0
hudStucture_t hudlist [MAXHUDS]
hudStucture_t * activehud
hudStucture_t hud0
vec4_t HUD_Background = { 0.16f, 0.2f, 0.17f, 0.8f }
vec4_t HUD_Border = { 0.5f, 0.5f, 0.5f, 0.5f }
vec4_t HUD_Text = { 0.6f, 0.6f, 0.6f, 1.0f }
vec4_t bgcolor = { 1.f, 1.f, 1.f, .3f }
static char statsDebugStrings [6][512]
static int statsDebugTime [6]
static int statsDebugTextWidth [6]
static int statsDebugPos
static vec_t highestSpeed
static vec_t speed
static int lasttime
vec4_t tclr = { 0.625f, 0.625f, 0.6f, 1.0f }
vec4_t colorAW = { 0, 0.5, 0, 0.5f }
Detailed Description
Draws the player's hud.
Definition in file cg_draw_hud.c.
Macro Definition Documentation
#define MAX_FPS_FRAMES 500
Definition at line 2137 of file cg_draw_hud.c.
Referenced by CG_DrawFPS().
#define MAXHUDS 128
Definition at line 71 of file cg_draw_hud.c.
Referenced by CG_getHudByNumber().
#define SKILL_BAR_OFFSET (2 * SKILL_BAR_X_INDENT)
Definition at line 58 of file cg_draw_hud.c.
#define SKILL_BAR_WIDTH (SKILL_ICON_SIZE - SKILL_BAR_OFFSET)
Definition at line 62 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_BAR_X (SKILL_BAR_OFFSET + SKILL_BAR_X_INDENT + SKILLS_X)
Definition at line 63 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_BAR_X_INDENT 0
Definition at line 59 of file cg_draw_hud.c.
#define SKILL_BAR_X_SCALE (SKILL_ICON_SIZE + 2)
Definition at line 64 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_BAR_Y (SKILL_BAR_Y_INDENT - SKILL_BAR_OFFSET - SKILLS_Y)
Definition at line 67 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_BAR_Y_INDENT 6
Definition at line 60 of file cg_draw_hud.c.
#define SKILL_BAR_Y_SCALE (SKILL_ICON_SIZE + 2)
Definition at line 68 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_ICON_SIZE 14
Definition at line 53 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_ICON_X (SKILL_BAR_OFFSET + SKILLS_X)
Definition at line 65 of file cg_draw_hud.c.
Referenced by CG_DrawSkills(), and CG_setDefaultHudValues().
#define SKILL_ICON_X_SCALE (SKILL_ICON_SIZE + 2)
Definition at line 66 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILL_ICON_Y (-(SKILL_ICON_SIZE + 2) - SKILL_BAR_OFFSET - SKILLS_Y)
Definition at line 69 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
#define SKILLS_X 112
Definition at line 55 of file cg_draw_hud.c.
Referenced by CG_setDefaultHudValues().
#define SKILLS_Y 20
Definition at line 56 of file cg_draw_hud.c.
#define SPEED_US_TO_KPH 15.58f
Definition at line 2041 of file cg_draw_hud.c.
Referenced by CG_DrawSpeed().
#define SPEED_US_TO_MPH 23.44f
Definition at line 2042 of file cg_draw_hud.c.
Referenced by CG_DrawSpeed().
#define UPPERRIGHT_W 52
Definition at line 2016 of file cg_draw_hud.c.
Referenced by CG_DrawDisconnect(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSnapshot(), CG_DrawSpeed(), and CG_DrawTimerNormal().
#define UPPERRIGHT_X 634
Definition at line 2015 of file cg_draw_hud.c.
Referenced by CG_DrawDisconnect(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSnapshot(), CG_DrawSpeed(), and CG_DrawTimerNormal().
Enumeration Type Documentation
enum althud_flags
Enumerator
FLAGS_MOVE_TIMERS
FLAGS_REMOVE_RANKS
FLAGS_MOVE_POPUPS
FLAGS_POPUPS_SHADOW
Definition at line 39 of file cg_draw_hud.c.
enum componentStyle
Enumerator
STYLE_NORMAL
STYLE_SIMPLE
Definition at line 47 of file cg_draw_hud.c.
Function Documentation
static void CG_addHudToList (hudStucture_t * hud) static
CG_addHudToList.
Parameters
[in] hud
Definition at line 227 of file cg_draw_hud.c.
Referenced by CG_Hud_Setup(), and CG_ParseHUD().
void CG_AddLagometerFrameInfo (void)
Adds the current interpolate / extrapolate bar for this frame.
Definition at line 2485 of file cg_draw_hud.c.
Referenced by CG_DrawActiveFrame().
void CG_AddLagometerSnapshotInfo (snapshot_t * snap)
Log the ping time, server framerate and number of dropped snapshots before it each time a snapshot is received.
Parameters
[in] snap
Todo:
: check this for demoPlayback
Definition at line 2496 of file cg_draw_hud.c.
Referenced by CG_ReadNextSnapshot().
skillType_t CG_ClassSkillForPosition (clientInfo_t * ci, int pos)
CG_ClassSkillForPosition.
Parameters
[in] ci
[in] pos
Returns
Definition at line 1127 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
static void CG_CompasMoveLocation (float * basex, float * basey, qboolean animationout) static
CG_CompasMoveLocation.
Parameters
[in] basex
[in] basey
[in] animationout
Definition at line 1672 of file cg_draw_hud.c.
Referenced by CG_DrawNewCompass().
static void CG_CompasMoveLocationCalc (float * locationvalue, qboolean directionplus, qboolean animationout) static
CG_CompasMoveLocationCalc.
Parameters
[out] locationvalue
[in] directionplus
[in] animationout
Definition at line 1640 of file cg_draw_hud.c.
Referenced by CG_CompasMoveLocation().
void CG_DrawActiveHud (void)
CG_DrawActiveHud.
Definition at line 3074 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
static void CG_DrawAmmoCount (float x, float y) static
CG_DrawAmmoCount.
Parameters
[in] x
[in] y
Definition at line 1052 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStatus().
static void CG_DrawBreathBar (rectDef_t * rect) static
Draw the breath bar.
Parameters
[in] rect
Definition at line 890 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStatus().
void CG_DrawCompassIcon (float x, float y, float w, float h, vec3_t origin, vec3_t dest, qhandle_t shader)
CG_DrawCompassIcon.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] origin
[in] dest
[in] shader
Definition at line 1595 of file cg_draw_hud.c.
Referenced by CG_DrawNewCompass().
static float CG_DrawDisconnect (float y) static
Draw disconnect icon for long lag.
Parameters
[in] y
Returns
Definition at line 2579 of file cg_draw_hud.c.
Referenced by CG_DrawLagometer(), and CG_DrawUpperRight().
int CG_DrawField (int x, int y, int width, int value, int charWidth, int charHeight, qboolean dodrawpic, qboolean leftAlign)
CG_DrawField.
Parameters
[in] x
[in] y
[in] width
[in] value
[in] charWidth
[in] charHeight
[in] dodrawpic
[in] leftAlign
Returns
Definition at line 1450 of file cg_draw_hud.c.
Referenced by CG_DrawLivesLeft().
static float CG_DrawFPS (float y) static
CG_DrawFPS.
Parameters
[in] y
Returns
Definition at line 2144 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
void CG_DrawGlobalHud (void)
CG_DrawGlobalHud.
Definition at line 3107 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
static void CG_DrawGunIcon (rectDef_t location) static
CG_DrawGunIcon.
Parameters
[in] location
Definition at line 1013 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStatus().
static float CG_DrawLagometer (float y) static
CG_DrawLagometer.
Parameters
[in] y
Returns
Todo:
: see warmup blinky blinky
Todo:
: we might do different views x/Y or in %
Definition at line 2663 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
void CG_DrawLivesLeft (hudComponent_t comp)
CG_DrawLivesLeft.
Parameters
[in] comp - unused
Definition at line 1530 of file cg_draw_hud.c.
Referenced by CG_DrawActiveHud().
static float CG_DrawLocalTime (float y) static
CG_DrawLocalTime.
Parameters
[in] y
Returns
Definition at line 2430 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
static void CG_DrawNewCompass (rectDef_t location) static
CG_DrawNewCompass.
Parameters
location
Definition at line 1744 of file cg_draw_hud.c.
Referenced by CG_DrawGlobalHud().
static void CG_DrawPicShadowed (float x, float y, float w, float h, qhandle_t icon) static
CG_DrawPicShadowed.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] icon
Definition at line 644 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
static float CG_DrawPing (float y) static
CG_DrawPing.
Parameters
[in] y
Returns
Definition at line 2637 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
static void CG_DrawPlayerHealth (float x, float y) static
CG_DrawPlayerHealth.
Parameters
[in] x
[in] y
Definition at line 1154 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStats().
static void CG_DrawPlayerHealthBar (rectDef_t * rect) static
CG_DrawPlayerHealthBar.
Parameters
[in] rect
Definition at line 821 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStatus().
static void CG_DrawPlayerStats (void) static
Draw the player stats.
Definition at line 2908 of file cg_draw_hud.c.
Referenced by CG_DrawActiveHud().
static void CG_DrawPlayerStatus (void) static
Draw the player status.
Definition at line 2848 of file cg_draw_hud.c.
Referenced by CG_DrawActiveHud().
static void CG_DrawPlayerStatusHead (hudComponent_t comp) static
CG_DrawPlayerStatusHead.
Parameters
[in] comp
Definition at line 656 of file cg_draw_hud.c.
Referenced by CG_DrawActiveHud().
static void CG_DrawPowerUps (rectDef_t rect) static
CG_DrawPowerUps.
Parameters
[in] rect
Definition at line 1239 of file cg_draw_hud.c.
Referenced by CG_DrawGlobalHud().
static void CG_DrawRank (float x, float y) static
CG_DrawRank.
Parameters
[in] x
[in] y
Definition at line 1224 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStats().
static void CG_DrawSkillBar (float x, float y, float w, float h, int skill) static
CG_DrawSkillBar.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] skill
Definition at line 1084 of file cg_draw_hud.c.
Referenced by CG_DrawSkills().
static void CG_DrawSkills (hudComponent_t comp) static
CG_DrawSkills.
Parameters
[in] comp
Definition at line 1167 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStats().
static float CG_DrawSnapshot (float y) static
CG_DrawSnapshot.
Parameters
y
Returns
Definition at line 2023 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
static float CG_DrawSpeed (float y) static
CG_DrawSpeed.
Parameters
y
Returns
Definition at line 2053 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
static void CG_DrawStaminaBar (rectDef_t * rect) static
CG_DrawStaminaBar.
Parameters
[in] rect
Definition at line 850 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStatus().
static void CG_DrawStatsDebug (void) static
CG_DrawStatsDebug.
Definition at line 1939 of file cg_draw_hud.c.
Referenced by CG_DrawActiveHud().
static float CG_DrawTimerNormal (float y) static
CG_DrawTimerNormal.
Parameters
[in] y
Returns
Definition at line 2340 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
static void CG_DrawTimersAlt (rectDef_t * respawn, rectDef_t * spawntimer, rectDef_t * localtime, rectDef_t * roundtimer) static
CG_DrawTimersAlt.
Parameters
[in] respawn
[in] spawntimer
[in] localtime
[in] roundtimer
Definition at line 2218 of file cg_draw_hud.c.
Referenced by CG_DrawUpperRight().
void CG_DrawUpperRight (void)
CG_DrawUpperRight.
Definition at line 3137 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
static void CG_DrawWeapRecharge (rectDef_t * rect) static
Draw weapon recharge bar.
Parameters
rect
Todo:
: potential DIV 0 when charge times are set to 0!
Definition at line 911 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStatus().
static void CG_DrawXP (float x, float y) static
CG_DrawXP.
Parameters
[in] x
[in] y
Definition at line 1198 of file cg_draw_hud.c.
Referenced by CG_DrawPlayerStats().
hudStucture_t* CG_GetActiveHUD ()
CG_getActiveHUD Returns reference to an active hud structure.
Returns
Definition at line 99 of file cg_draw_hud.c.
Referenced by CG_TransformAutomapEntity().
hudComponent_t CG_getComponent (float x, float y, float w, float h, qboolean visible, componentStyle style)
CG_getComponent.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] visible
[in] style
Returns
Definition at line 114 of file cg_draw_hud.c.
Referenced by CG_Hud_Setup(), and CG_setDefaultHudValues().
static hudStucture_t* CG_getHudByNumber (int number) static
CG_getHudByNumber.
Parameters
[in] number
Returns
Definition at line 180 of file cg_draw_hud.c.
Referenced by CG_isHudNumberAvailable(), and CG_SetHud().
static qboolean CG_HUD_ParseError (int handle, const char * format, ...) static
CG_HUD_ParseError.
Parameters
[in] handle
[in] format
Returns
Definition at line 241 of file cg_draw_hud.c.
Referenced by CG_ParseHUD(), and CG_ReadHudFile().
void CG_Hud_Setup (void)
CG_Hud_Setup.
Definition at line 2939 of file cg_draw_hud.c.
Referenced by CG_RegisterGraphics().
void CG_InitStatsDebug (void)
CG_InitStatsDebug.
Definition at line 1555 of file cg_draw_hud.c.
Referenced by CG_Init().
static qboolean CG_isHudNumberAvailable (int number) static
CG_isHudNumberAvailable.
Parameters
[in] number
Returns
Definition at line 209 of file cg_draw_hud.c.
Referenced by CG_ParseHUD().
static qboolean CG_ParseHUD (int handle) static
CG_ParseHUD.
Parameters
[in] handle
Returns
Definition at line 318 of file cg_draw_hud.c.
Referenced by CG_ReadHudFile().
static qboolean CG_ParseHudComponent (int handle, hudComponent_t * comp) static
CG_ParseHudComponent.
Parameters
[in] handle
[in] comp
Returns
Definition at line 296 of file cg_draw_hud.c.
Referenced by CG_ParseHUD().
static void CG_PlayerAmmoValue (int * ammo, int * clips, int * akimboammo) static
Get the current ammo and/or clip count of the holded weapon (if using ammo).
Parameters
[out] ammo - the number of ammo left (in the current clip if using clip)
[out] clips - the total ammount of ammo in all clips (if using clip)
[out] akimboammo - the number of ammo left in the second pistol of akimbo (if using akimbo)
Definition at line 734 of file cg_draw_hud.c.
Referenced by CG_DrawAmmoCount().
static qboolean CG_ReadHudFile (const char * filename) static
Definition at line 565 of file cg_draw_hud.c.
Referenced by CG_ReadHudScripts().
void CG_ReadHudScripts (void)
CG_ReadHudScripts.
Definition at line 620 of file cg_draw_hud.c.
Referenced by CG_Hud_Setup(), and CG_ReadHuds_f().
static qboolean CG_RectParse (int handle, rectDef_t * r) static
CG_RectParse.
Parameters
[in] handle
[in,out] r
Returns
Definition at line 269 of file cg_draw_hud.c.
Referenced by CG_ParseHudComponent().
void CG_setDefaultHudValues (hudStucture_t * hud)
CG_setDefaultHudValues.
Parameters
[out] hud
Todo:
: widescreen ?
Definition at line 125 of file cg_draw_hud.c.
Referenced by CG_Hud_Setup(), and CG_ParseHUD().
void CG_SetHud (void)
CG_SetHud.
Definition at line 3046 of file cg_draw_hud.c.
Referenced by CG_Draw2D().
void CG_StatsDebugAddText (const char * text)
CG_StatsDebugAddText.
Parameters
[in] text
Definition at line 1566 of file cg_draw_hud.c.
Referenced by CG_ServerCommand().
Variable Documentation
hudStucture_t* activehud
Definition at line 76 of file cg_draw_hud.c.
Referenced by CG_GetActiveHUD().
vec4_t bgcolor = { 1.f, 1.f, 1.f, .3f }
Definition at line 815 of file cg_draw_hud.c.
Referenced by CG_DrawBreathBar(), CG_DrawCrosshairNames(), CG_DrawPlayerHealthBar(), CG_DrawStaminaBar(), CG_DrawWeapRecharge(), and CG_HorizontalPercentBar().
vec4_t colorAW = { 0, 0.5, 0, 0.5f }
Definition at line 2656 of file cg_draw_hud.c.
Referenced by CG_DrawLagometer().
vec_t highestSpeed static
Definition at line 2044 of file cg_draw_hud.c.
Referenced by CG_DrawSpeed().
hudStucture_t hud0
Definition at line 77 of file cg_draw_hud.c.
Referenced by CG_Hud_Setup(), and CG_SetHud().
vec4_t HUD_Background = { 0.16f, 0.2f, 0.17f, 0.8f }
Definition at line 632 of file cg_draw_hud.c.
Referenced by CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSnapshot(), CG_DrawSpeed(), and CG_DrawTimerNormal().
vec4_t HUD_Border = { 0.5f, 0.5f, 0.5f, 0.5f }
Definition at line 633 of file cg_draw_hud.c.
Referenced by CG_DemoClick(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), CG_DrawSnapshot(), CG_DrawSpeed(), and CG_DrawTimerNormal().
vec4_t HUD_Text = { 0.6f, 0.6f, 0.6f, 1.0f }
Definition at line 634 of file cg_draw_hud.c.
Referenced by CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLocalTime(), CG_DrawPing(), and CG_DrawSnapshot().
int hudCount = 0
Definition at line 73 of file cg_draw_hud.c.
Referenced by CG_addHudToList(), CG_getHudByNumber(), and CG_ReadHudScripts().
hudStucture_t hudlist[MAXHUDS]
Definition at line 74 of file cg_draw_hud.c.
int lasttime static
Definition at line 2045 of file cg_draw_hud.c.
Referenced by CG_AddLagometerSnapshotInfo(), and CG_DrawSpeed().
vec_t speed static
Definition at line 2044 of file cg_draw_hud.c.
Referenced by CG_DrawSpeed(), CG_OffsetFirstPersonView(), CG_ParticleSparks(), CG_PlayerAngles(), CG_PlayGlobalSound(), CG_SwingAngles(), CL_AdjustAngles(), DoClientThinks(), G_LinkDebris(), G_RunFlamechunk(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GotoMarker(), G_ScriptAction_SetSpeed(), PM_Friction(), PM_NoclipMove(), PM_SetMovementDir(), Reached_Train(), Reached_Train_rotating(), and SP_func_pendulum().
int statsDebugPos static
Definition at line 1550 of file cg_draw_hud.c.
Referenced by CG_DrawStatsDebug(), CG_InitStatsDebug(), and CG_StatsDebugAddText().
char statsDebugStrings[6][512] static
Definition at line 1547 of file cg_draw_hud.c.
Referenced by CG_DrawStatsDebug(), CG_InitStatsDebug(), and CG_StatsDebugAddText().
int statsDebugTextWidth[6] static
Definition at line 1549 of file cg_draw_hud.c.
Referenced by CG_DrawStatsDebug(), and CG_StatsDebugAddText().
int statsDebugTime[6] static
Definition at line 1548 of file cg_draw_hud.c.
Referenced by CG_DrawStatsDebug(), CG_InitStatsDebug(), and CG_StatsDebugAddText().
vec4_t tclr = { 0.625f, 0.625f, 0.6f, 1.0f }
Definition at line 2046 of file cg_draw_hud.c.
Referenced by CG_DrawSpeed().