ET: Legacy: src/client/cl_cinematic.c File Reference
cl_cinematic.c File Reference
Video and cinematic playback.
#include "client.h"
Data Structures
struct videoDecode_s
Typedefs
typedef struct videoDecode_s videoDecode_t
Enumerations
enum cinType_t { VIDEO_NONE = 0, VIDEO_ROQ, VIDEO_NUM_CODECS }
Functions
static cinematic_t * CIN_HandleForCinematic (cinHandle_t *handle)
Finds a free cinHandle_t.
static qboolean CIN_HandleValid (cinHandle_t handle)
CIN_HandleValid.
cinematic_t * CIN_GetCinematicByHandle (cinHandle_t handle)
CIN_GetCinematicByHandle.
static void CIN_FreeCinematic (cinematic_t *cin, qboolean runtime)
CIN_FreeCinematic.
static void CIN_PlayCinematic_f (void)
CIN_PlayCinematic_f.
static void CIN_ListCinematics_f (void)
CIN_ListCinematics_f.
static void CIN_Completion_VideoName (char *args, int argNum)
CIN_Completion_VideoName.
cinHandle_t CIN_PlayCinematic (const char *name, int x, int y, int w, int h, int flags)
CIN_PlayCinematic.
void CIN_ResetCinematic (cinHandle_t handle)
CIN_ResetCinematic.
e_status CIN_StopCinematic (cinHandle_t handle)
CIN_StopCinematic.
void CIN_Init (void)
CIN_Init.
void CIN_Shutdown (void)
CIN_Shutdown.
void CIN_CloseAllVideos (void)
Stop all the cinematics.
e_status CIN_RunCinematic (int handle)
CIN_RunCinematic.
void CIN_SetExtents (int handle, int x, int y, int w, int h)
CIN_SetExtents.
void SCR_StopCinematic (void)
SCR_StopCinematic.
void SCR_RunCinematic (void)
SCR_RunCinematic.
void SCR_DrawCinematic (void)
SCR_DrawCinematic.
void CIN_DrawCinematic (int handle)
CIN_DrawCinematic.
void CIN_UploadCinematic (int handle)
CIN_UploadCinematic.
Variables
static videoDecode_t videoDecoders []
static cinematic_t cin_cinematics [MAX_CINEMATICS]
Detailed Description
Video and cinematic playback.
Definition in file cl_cinematic.c.
Typedef Documentation
typedef struct videoDecode_s videoDecode_t
Enumeration Type Documentation
enum cinType_t
Enumerator
VIDEO_NONE
VIDEO_ROQ
VIDEO_NUM_CODECS
Definition at line 53 of file cl_cinematic.c.
Function Documentation
void CIN_CloseAllVideos (void)
Stop all the cinematics.
Definition at line 563 of file cl_cinematic.c.
Referenced by CIN_Shutdown(), and Hunk_Clear().
static void CIN_Completion_VideoName (char * args, int argNum) static
CIN_Completion_VideoName.
Parameters
args - unused
[in] argNum
Definition at line 291 of file cl_cinematic.c.
Referenced by CIN_Init().
void CIN_DrawCinematic (int handle)
CIN_DrawCinematic.
Parameters
[in] handle
Definition at line 675 of file cl_cinematic.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SCR_DrawCinematic().
static void CIN_FreeCinematic (cinematic_t * cin, qboolean runtime) static
CIN_FreeCinematic.
Parameters
[in,out] cin
[in] runtime
Definition at line 151 of file cl_cinematic.c.
Referenced by CIN_CloseAllVideos(), CIN_PlayCinematic(), and CIN_StopCinematic().
cinematic_t* CIN_GetCinematicByHandle (cinHandle_t handle)
CIN_GetCinematicByHandle.
Parameters
[in] handle
Returns
A cinematic_t for the given cinHandle_t
Definition at line 127 of file cl_cinematic.c.
Referenced by CIN_DrawCinematic(), CIN_ResetCinematic(), CIN_RunCinematic(), CIN_SetExtents(), CIN_StopCinematic(), and CIN_UploadCinematic().
static cinematic_t* CIN_HandleForCinematic (cinHandle_t * handle) static
Finds a free cinHandle_t.
Parameters
[out] handle
Returns
Definition at line 84 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic().
static qboolean CIN_HandleValid (cinHandle_t handle) static
CIN_HandleValid.
Parameters
[in] handle
Returns
Definition at line 112 of file cl_cinematic.c.
Referenced by CIN_DrawCinematic(), CIN_GetCinematicByHandle(), CIN_ResetCinematic(), CIN_RunCinematic(), CIN_SetExtents(), CIN_StopCinematic(), CIN_UploadCinematic(), SCR_DrawCinematic(), SCR_RunCinematic(), and SCR_StopCinematic().
void CIN_Init (void)
CIN_Init.
Definition at line 519 of file cl_cinematic.c.
Referenced by CL_Init().
static void CIN_ListCinematics_f (void) static
CIN_ListCinematics_f.
Definition at line 250 of file cl_cinematic.c.
Referenced by CIN_Init().
cinHandle_t CIN_PlayCinematic (const char * name, int x, int y, int w, int h, int flags)
CIN_PlayCinematic.
Parameters
[in] name
[in] x
[in] y
[in] w
[in] h
[in] flags
Returns
Definition at line 314 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic_f(), CL_CgameSystemCalls(), CL_InitRef(), and CL_UISystemCalls().
static void CIN_PlayCinematic_f (void) static
CIN_PlayCinematic_f.
Definition at line 197 of file cl_cinematic.c.
Referenced by CIN_Init().
void CIN_ResetCinematic (cinHandle_t handle)
CIN_ResetCinematic.
Parameters
[in] handle
Note
Unused
Definition at line 452 of file cl_cinematic.c.
e_status CIN_RunCinematic (int handle)
CIN_RunCinematic.
Parameters
[in] handle
Returns
Definition at line 584 of file cl_cinematic.c.
Referenced by CL_CgameSystemCalls(), CL_InitRef(), CL_UISystemCalls(), and SCR_RunCinematic().
void CIN_SetExtents (int handle, int x, int y, int w, int h)
CIN_SetExtents.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 623 of file cl_cinematic.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void CIN_Shutdown (void)
CIN_Shutdown.
Definition at line 541 of file cl_cinematic.c.
Referenced by CL_Shutdown().
e_status CIN_StopCinematic (cinHandle_t handle)
CIN_StopCinematic.
Parameters
[in] handle
Returns
Definition at line 482 of file cl_cinematic.c.
Referenced by CIN_RunCinematic(), CL_CgameSystemCalls(), CL_UISystemCalls(), and SCR_StopCinematic().
void CIN_UploadCinematic (int handle)
CIN_UploadCinematic.
Parameters
handle
Definition at line 706 of file cl_cinematic.c.
Referenced by CL_InitRef().
void SCR_DrawCinematic (void)
SCR_DrawCinematic.
Definition at line 663 of file cl_cinematic.c.
Referenced by SCR_DrawScreenField().
void SCR_RunCinematic (void)
SCR_RunCinematic.
Definition at line 652 of file cl_cinematic.c.
Referenced by CL_Frame().
void SCR_StopCinematic (void)
SCR_StopCinematic.
Definition at line 640 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic_f(), CL_Disconnect(), and CL_Disconnect_f().
Variable Documentation
cinematic_t cin_cinematics[MAX_CINEMATICS] static
Definition at line 77 of file cl_cinematic.c.
videoDecode_t videoDecoders[] static
Initial value:
=
{
    { "\0",  "\0",  NULL,     NULL, NULL,          NULL,                NULL,      NULL          },
    { "roq", "\0",  ROQ_Init, NULL, ROQ_StartRead,  ROQ_UpdateCinematic,  ROQ_Reset, ROQ_StopVideo },
}
Definition at line 65 of file cl_cinematic.c.