ET: Legacy: src/client/cl_net_chan.c File Reference
cl_net_chan.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "client.h"
Functions
static void CL_Netchan_Encode (msg_t *msg)
CL_Netchan_Encode.
static void CL_Netchan_Decode (msg_t *msg)
CL_Netchan_Decode.
void CL_Netchan_TransmitNextFragment (netchan_t *chan)
CL_Netchan_TransmitNextFragment.
static void CL_WriteBinaryMessage (msg_t *msg)
CL_WriteBinaryMessage.
void CL_Netchan_Transmit (netchan_t *chan, msg_t *msg)
CL_Netchan_Transmit.
qboolean CL_Netchan_Process (netchan_t *chan, msg_t *msg)
CL_Netchan_Process.
Variables
int newsize = 0
Function Documentation
static void CL_Netchan_Decode (msg_t * msg) static
CL_Netchan_Decode.
First four bytes of the data are always: long reliableAcknowledge;
Parameters
[in,out] msg
Definition at line 105 of file cl_net_chan.c.
Referenced by CL_Netchan_Process().
static void CL_Netchan_Encode (msg_t * msg) static
CL_Netchan_Encode.
First 12 bytes of the data are always: long serverId; long messageAcknowledge; long reliableAcknowledge;
Parameters
[in,out] msg
Definition at line 47 of file cl_net_chan.c.
Referenced by CL_Netchan_Transmit().
qboolean CL_Netchan_Process (netchan_t * chan, msg_t * msg)
CL_Netchan_Process.
Parameters
[in] chan
[in] msg
Returns
Definition at line 204 of file cl_net_chan.c.
Referenced by CL_PacketEvent().
void CL_Netchan_Transmit (netchan_t * chan, msg_t * msg)
CL_Netchan_Transmit.
Parameters
[in] chan
[in] msg
Definition at line 186 of file cl_net_chan.c.
Referenced by CL_WritePacket().
void CL_Netchan_TransmitNextFragment (netchan_t * chan)
CL_Netchan_TransmitNextFragment.
Parameters
[in] chan
Definition at line 152 of file cl_net_chan.c.
Referenced by CL_WritePacket().
static void CL_WriteBinaryMessage (msg_t * msg) static
CL_WriteBinaryMessage.
Parameters
[in] msg
Definition at line 161 of file cl_net_chan.c.
Referenced by CL_Netchan_Transmit().
Variable Documentation
int newsize = 0
Definition at line 196 of file cl_net_chan.c.
Referenced by CL_Netchan_Process().