ET: Legacy: src/client/cl_demo.c File Reference
cl_demo.c File Reference
#include "client.h"
Data Structures
struct demoInfo_t
struct rewindBackups_t
Macros
#define DEMODEBUG(msg, ...)
#define Com_FuncDPrinf(msg, ...)
#define Com_FuncPrinf Com_Printf
#define Com_FuncError(...) Com_Error(ERR_FATAL, __VA_ARGS__)
#define Com_FuncDrop(...) Com_Error(ERR_DROP, __VA_ARGS__)
#define MEGABYTES(x) x / 1024.0 / 1024.0
#define MAX_REWIND_BACKUPS 20
#define NEW_DEMOFUNC 1
Functions
static int CL_WalkDemoExt (const char *arg, char *name, int *demofile)
CL_WalkDemoExt.
qboolean CL_PeekSnapshot (int snapshotNumber, snapshot_t *snapshot)
CL_PeekSnapshot.
static void CL_DemoFastForward (double wantedTime)
CL_DemoFastForward.
static void CL_RewindDemo (double wantedTime)
CL_RewindDemo.
static void CL_DemoSeekMs (double ms, int exactServerTime)
CL_DemoSeekMs.
static void CL_ParseDemoSnapShotSimple (msg_t *msg)
CL_ParseDemoSnapShotSimple.
static void CL_ParseDemo (void)
Do very shallow parse of the demo (could be extended) just to get times and snapshot count.
void CL_FreeDemoPoints (void)
CL_FreeDemoPoints.
void CL_AllocateDemoPoints (void)
CL_AllocateDemoPoints.
void CL_WriteDemoMessage (msg_t *msg, int headerBytes)
Dumps the current net message, prefixed by the length.
void CL_StopRecord_f (void)
Stop recording a demo.
void CL_DemoFilename (int number, char *fileName)
CL_DemoFilename.
void CL_Record_f (void)
Begins recording a demo from the current position.
void CL_Record (const char *name)
CL_Record.
void CL_DemoCleanUp (void)
CL_DemoCleanUp.
void CL_DemoCompleted (void)
CL_DemoCompleted.
void CL_DemoRun (void)
CL_DemoRun.
void CL_ReadDemoMessage (void)
CL_ReadDemoMessage.
static void CL_CompleteDemoName (char *args, int argNum)
CL_CompleteDemoName.
void CL_PlayDemo_f (void)
Usage: demo <demoname>
void CL_NextDemo (void)
Called when a demo or cinematic finishes If the "nextdemo" cvar is set, that command will be issued.
void CL_Rewind_f (void)
CL_Rewind_f.
void CL_FastForward_f (void)
CL_FastForward_f.
void CL_SeekServerTime_f (void)
CL_SeekServerTime_f.
void CL_Seek_f (void)
CL_Seek_f.
void CL_SeekEnd_f (void)
CL_SeekEnd_f.
void CL_SeekNext_f (void)
CL_SeekNext_f.
void CL_SeekPrev_f (void)
CL_SeekPrev_f.
void CL_PauseDemo_f (void)
CL_PauseDemo_f.
void CL_DemoInit (void)
CL_DemoInit.
Variables
cvar_t * cl_maxRewindBackups
demoInfo_t di
rewindBackups_t * rewindBackups = NULL
int maxRewindBackups = 0
demoPlayInfo_t dpi = { 0, 0 }
static char demoName [MAX_OSPATH]
Macro Definition Documentation
#define Com_FuncDPrinf (msg, ...)
Definition at line 45 of file cl_demo.c.
Referenced by CL_DemoFastForward(), CL_NextDemo(), and CL_SeekNext_f().
#define Com_FuncDrop (...) Com_Error(ERR_DROP, __VA_ARGS__)
Definition at line 48 of file cl_demo.c.
Referenced by CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_PeekSnapshot(), CL_PlayDemo_f(), CL_ReadDemoMessage(), and CL_Rewind_f().
#define Com_FuncError (...) Com_Error(ERR_FATAL, __VA_ARGS__)
Definition at line 47 of file cl_demo.c.
Referenced by CL_AllocateDemoPoints().
#define Com_FuncPrinf Com_Printf
Definition at line 46 of file cl_demo.c.
Referenced by CL_AllocateDemoPoints(), CL_DemoCompleted(), CL_DemoFastForward(), CL_DemoSeekMs(), CL_FastForward_f(), CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_PauseDemo_f(), CL_PeekSnapshot(), CL_PlayDemo_f(), CL_ReadDemoMessage(), CL_Record(), CL_Record_f(), CL_Rewind_f(), CL_RewindDemo(), CL_Seek_f(), CL_SeekEnd_f(), CL_SeekNext_f(), CL_SeekPrev_f(), CL_SeekServerTime_f(), CL_StopRecord_f(), and CL_WalkDemoExt().
#define DEMODEBUG (msg, ...)
Definition at line 44 of file cl_demo.c.
Referenced by CL_DemoFastForward(), CL_DemoRun(), CL_DemoSeekMs(), CL_Rewind_f(), CL_RewindDemo(), and CL_SeekServerTime_f().
#define MAX_REWIND_BACKUPS 20
Definition at line 52 of file cl_demo.c.
Referenced by CL_AllocateDemoPoints(), and CL_DemoInit().
#define MEGABYTES (x) x / 1024.0 / 1024.0
Definition at line 51 of file cl_demo.c.
Referenced by CL_AllocateDemoPoints().
#define NEW_DEMOFUNC 1
Definition at line 54 of file cl_demo.c.
Function Documentation
void CL_AllocateDemoPoints (void)
CL_AllocateDemoPoints.
Definition at line 894 of file cl_demo.c.
Referenced by CL_PlayDemo_f().
static void CL_CompleteDemoName (char * args, int argNum) static
CL_CompleteDemoName.
Parameters
args - unused
[in] argNum
Definition at line 1371 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_DemoCleanUp (void)
CL_DemoCleanUp.
Definition at line 1140 of file cl_demo.c.
Referenced by CL_Disconnect().
void CL_DemoCompleted (void)
CL_DemoCompleted.
Definition at line 1157 of file cl_demo.c.
Referenced by CL_ParseDemo(), and CL_ReadDemoMessage().
static void CL_DemoFastForward (double wantedTime) static
CL_DemoFastForward.
Parameters
[in] wantedTime
Todo:
: fix this
Definition at line 378 of file cl_demo.c.
Referenced by CL_DemoSeekMs(), CL_FastForward_f(), and CL_RewindDemo().
void CL_DemoFilename (int number, char * fileName)
CL_DemoFilename.
Parameters
[in] number
[in] fileName
Definition at line 974 of file cl_demo.c.
Referenced by CL_Record_f().
void CL_DemoInit (void)
CL_DemoInit.
Definition at line 1777 of file cl_demo.c.
Referenced by CL_Init().
void CL_DemoRun (void)
CL_DemoRun.
Definition at line 1193 of file cl_demo.c.
Referenced by CL_SetCGameTime().
static void CL_DemoSeekMs (double ms, int exactServerTime) static
CL_DemoSeekMs.
Parameters
[in] ms
[in] exactServerTime
Definition at line 526 of file cl_demo.c.
Referenced by CL_PauseDemo_f(), CL_Seek_f(), CL_SeekEnd_f(), CL_SeekNext_f(), CL_SeekPrev_f(), and CL_SeekServerTime_f().
void CL_FastForward_f (void)
CL_FastForward_f.
Definition at line 1543 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_FreeDemoPoints (void)
CL_FreeDemoPoints.
Definition at line 882 of file cl_demo.c.
Referenced by CL_AllocateDemoPoints(), CL_DemoCleanUp(), and CL_DemoCompleted().
void CL_NextDemo (void)
Called when a demo or cinematic finishes If the "nextdemo" cvar is set, that command will be issued.
Definition at line 1483 of file cl_demo.c.
Referenced by CL_DemoCompleted().
static void CL_ParseDemo (void) static
Do very shallow parse of the demo (could be extended) just to get times and snapshot count.
Definition at line 677 of file cl_demo.c.
Referenced by CL_PlayDemo_f().
static void CL_ParseDemoSnapShotSimple (msg_t * msg) static
CL_ParseDemoSnapShotSimple.
Parameters
[in] msg
Definition at line 559 of file cl_demo.c.
Referenced by CL_ParseDemo().
void CL_PauseDemo_f (void)
CL_PauseDemo_f.
Todo:
: this is just a hack, actually fix the cl_freezeDemo instead of this
Definition at line 1742 of file cl_demo.c.
Referenced by CL_DemoInit().
qboolean CL_PeekSnapshot (int snapshotNumber, snapshot_t * snapshot)
CL_PeekSnapshot.
Parameters
[in] snapshotNumber
[out] snapshot
Returns
Todo:
:
Todo:
: changed this check if it works
Todo:
other ents not supported yet
Todo:
if you fix other ents
Todo:
: configstring changes and server commands!!!
Definition at line 158 of file cl_demo.c.
Referenced by CL_SeekNext_f().
void CL_PlayDemo_f (void)
Usage: demo <demoname>
Definition at line 1385 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_ReadDemoMessage (void)
CL_ReadDemoMessage.
Definition at line 1271 of file cl_demo.c.
Referenced by CL_DemoFastForward(), CL_DemoRun(), CL_PlayDemo_f(), and CL_SetCGameTime().
void CL_Record (const char * name)
CL_Record.
Parameters
[in] name
Definition at line 1044 of file cl_demo.c.
Referenced by CL_ParseSnapshot(), and CL_Record_f().
void CL_Record_f (void)
Begins recording a demo from the current position.
Definition at line 990 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_Rewind_f (void)
CL_Rewind_f.
Definition at line 1505 of file cl_demo.c.
Referenced by CL_DemoInit().
static void CL_RewindDemo (double wantedTime) static
CL_RewindDemo.
Parameters
[in] wantedTime
Todo:
: take a look at these hacks
Todo:
: this is a hack to set the state to something valid
Definition at line 460 of file cl_demo.c.
Referenced by CL_DemoSeekMs(), and CL_Rewind_f().
void CL_Seek_f (void)
CL_Seek_f.
Definition at line 1609 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_SeekEnd_f (void)
CL_SeekEnd_f.
Definition at line 1640 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_SeekNext_f (void)
CL_SeekNext_f.
Definition at line 1671 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_SeekPrev_f (void)
CL_SeekPrev_f.
Definition at line 1713 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_SeekServerTime_f (void)
CL_SeekServerTime_f.
Definition at line 1584 of file cl_demo.c.
Referenced by CL_DemoInit().
void CL_StopRecord_f (void)
Stop recording a demo.
Definition at line 945 of file cl_demo.c.
Referenced by CL_DemoInit(), CL_Disconnect(), and CL_ShutdownAll().
static int CL_WalkDemoExt (const char * arg, char * name, int * demofile) static
CL_WalkDemoExt.
Parameters
[in] arg
[in,out] name
[in,out] demofile
Returns
Definition at line 109 of file cl_demo.c.
Referenced by CL_PlayDemo_f().
void CL_WriteDemoMessage (msg_t * msg, int headerBytes)
Dumps the current net message, prefixed by the length.
Parameters
[in] msg
[in] headerBytes
Definition at line 926 of file cl_demo.c.
Referenced by CL_PacketEvent().
Variable Documentation
cvar_t* cl_maxRewindBackups
Definition at line 93 of file cl_demo.c.
char demoName[MAX_OSPATH] static
Definition at line 985 of file cl_demo.c.
Referenced by CL_Record(), and CL_Record_f().
demoInfo_t di
Definition at line 95 of file cl_demo.c.
Referenced by RB_MDM_SurfaceAnim(), RB_SurfaceAnim(), and Tess_MDM_SurfaceAnim().
demoPlayInfo_t dpi = { 0, 0 }
Definition at line 100 of file cl_demo.c.
Referenced by CL_InitCGame(), and R_LoadScalableFont().
int maxRewindBackups = 0
Definition at line 97 of file cl_demo.c.
Referenced by CL_AllocateDemoPoints(), and CL_ReadDemoMessage().
rewindBackups_t* rewindBackups = NULL
Definition at line 96 of file cl_demo.c.