ET: Legacy: src/client/cl_cgame.c File Reference
cl_cgame.c File Reference
Client system interaction with client game.
#include "client.h"
#include "../botlib/botlib.h"
Macros
#define RESET_TIME 500
Functions
void Key_GetBindingBuf (int keynum, char *buf, int buflen)
void Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
void CL_GetGameState (gameState_t *gs)
CL_GetGameState.
void CL_GetGlconfig (glconfig_t *glconfig)
CL_GetGlconfig.
qboolean CL_GetUserCmd (int cmdNumber, usercmd_t *ucmd)
CL_GetUserCmd.
int CL_GetCurrentCmdNumber (void)
CL_GetCurrentCmdNumber.
void CL_GetCurrentSnapshotNumber (int *snapshotNumber, int *serverTime)
CL_GetCurrentSnapshotNumber.
qboolean CL_GetSnapshot (int snapshotNumber, snapshot_t *snapshot)
CL_GetSnapshot.
void CL_SetUserCmdValue (int userCmdValue, int flags, float sensitivityScale, int mpIdentClient)
CL_SetUserCmdValue.
void CL_SetClientLerpOrigin (float x, float y, float z)
CL_SetClientLerpOrigin.
qboolean CL_CGameCheckKeyExec (int key)
CL_CGameCheckKeyExec.
void CL_ConfigstringModified (void)
CL_ConfigstringModified.
qboolean CL_GetServerCommand (int serverCommandNumber)
Set up argc/argv for the given command.
void CL_SetExpectedHunkUsage (const char *mapname)
Sets com_expectedhunkusage, so the client knows how to draw the percentage bar.
static int CL_SendBinaryMessage (const char *buf, int buflen)
CL_SendBinaryMessage.
static int CL_BinaryMessageStatus (void)
CL_BinaryMessageStatus.
void CL_CGameBinaryMessageReceived (const byte *buf, int buflen, int serverTime)
CL_CGameBinaryMessageReceived.
void CL_CM_LoadMap (const char *mapname)
Just adds default parameters that cgame doesn't need to know about.
void CL_ShutdownCGame (void)
CL_ShutdownCGame.
static int FloatAsInt (float f)
intptr_t CL_CgameSystemCalls (intptr_t *args)
The cgame module is making a system call.
void CL_UpdateLevelHunkUsage (void)
This updates the "hunkusage.dat" file with the current map and it's hunk usage count.
void CL_InitCGame (void)
Should only be called by CL_StartHunkUsers.
qboolean CL_GameCommand (void)
See if the current console command is claimed by the cgame.
void CL_CGameRendering ()
CL_CGameRendering.
void CL_AdjustTimeDelta (void)
Adjust the clients view of server time.
void CL_FirstSnapshot (void)
CL_FirstSnapshot.
void CL_SetCGameTime (void)
CL_SetCGameTime.
Variables
botlib_export_t * botlib_export
Detailed Description
Client system interaction with client game.
Definition in file cl_cgame.c.
Macro Definition Documentation
#define RESET_TIME 500
Definition at line 1235 of file cl_cgame.c.
Referenced by CL_AdjustTimeDelta().
Function Documentation
void CL_AdjustTimeDelta (void)
Adjust the clients view of server time.
We attempt to have cl.serverTime exactly equal the server's view of time plus the timeNudge, but with variable latencies over the internet it will often need to drift a bit to match conditions.
Our ideal time would be to have the adjusted time approach, but not pass, the very latest snapshot.
Adjustments are only made when a new snapshot arrives with a rational latency, which keeps the adjustment process framerate independent and prevents massive overadjustment during times of significant packet loss or bursted delayed packets.
Todo:
: is this a problem for cgame?
Definition at line 1253 of file cl_cgame.c.
Referenced by CL_ParseDemo(), and CL_SetCGameTime().
static int CL_BinaryMessageStatus (void) static
CL_BinaryMessageStatus.
Returns
Definition at line 525 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_CGameBinaryMessageReceived (const byte * buf, int buflen, int serverTime)
CL_CGameBinaryMessageReceived.
Parameters
[in] buf
[in] buflen
[in] serverTime
Definition at line 546 of file cl_cgame.c.
Referenced by CL_ParseBinaryMessage().
qboolean CL_CGameCheckKeyExec (int key)
CL_CGameCheckKeyExec.
Parameters
[in] key
Returns
Definition at line 231 of file cl_cgame.c.
Referenced by CL_KeyEvent().
void CL_CGameRendering (void)
CL_CGameRendering.
Definition at line 1229 of file cl_cgame.c.
Referenced by SCR_DrawScreenField().
intptr_t CL_CgameSystemCalls (intptr_t * args)
The cgame module is making a system call.
Parameters
[in] args
Returns
Todo:
handling of looping sounds changed
Definition at line 612 of file cl_cgame.c.
Referenced by CL_InitCGame().
void CL_CM_LoadMap (const char * mapname)
Just adds default parameters that cgame doesn't need to know about.
Parameters
[in] mapname
Definition at line 565 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_ConfigstringModified (void)
CL_ConfigstringModified.
Definition at line 246 of file cl_cgame.c.
Referenced by CL_GetServerCommand().
void CL_FirstSnapshot (void)
CL_FirstSnapshot.
Definition at line 1319 of file cl_cgame.c.
Referenced by CL_SetCGameTime().
qboolean CL_GameCommand (void)
See if the current console command is claimed by the cgame.
Returns
Definition at line 1216 of file cl_cgame.c.
Referenced by Cmd_ExecuteString().
int CL_GetCurrentCmdNumber (void)
CL_GetCurrentCmdNumber.
Returns
Definition at line 94 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_GetCurrentSnapshotNumber (int * snapshotNumber, int * serverTime)
CL_GetCurrentSnapshotNumber.
Parameters
[out] snapshotNumber
[out] serverTime
Definition at line 131 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_GetGameState (gameState_t * gs)
CL_GetGameState.
Parameters
[out] gs
Definition at line 48 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_GetGlconfig (glconfig_t * glconfig)
CL_GetGlconfig.
Parameters
[out] glconfig
Definition at line 57 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
qboolean CL_GetServerCommand (int serverCommandNumber)
Set up argc/argv for the given command.
Parameters
[in] serverCommandNumber
Returns
Definition at line 316 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls(), and CL_DemoFastForward().
qboolean CL_GetSnapshot (int snapshotNumber, snapshot_t * snapshot)
CL_GetSnapshot.
Parameters
[in] snapshotNumber
[out] snapshot
Returns
Todo:
: configstring changes and server commands!!!
Definition at line 143 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls(), and CL_PeekSnapshot().
qboolean CL_GetUserCmd (int cmdNumber, usercmd_t * ucmd)
CL_GetUserCmd.
Parameters
[in] cmdNumber
[out] ucmd
Returns
Definition at line 68 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_InitCGame (void)
Should only be called by CL_StartHunkUsers.
Definition at line 1151 of file cl_cgame.c.
Referenced by CL_DownloadsComplete(), and CL_Vid_Restart_f().
static int CL_SendBinaryMessage (const char * buf, int buflen) static
CL_SendBinaryMessage.
Parameters
[in] buf
[in] buflen
Returns
Definition at line 507 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_SetCGameTime (void)
CL_SetCGameTime.
Definition at line 1356 of file cl_cgame.c.
Referenced by CL_Frame().
void CL_SetClientLerpOrigin (float x, float y, float z)
CL_SetClientLerpOrigin.
Parameters
[in] x
[in] y
[in] z
Definition at line 219 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_SetExpectedHunkUsage (const char * mapname)
Sets com_expectedhunkusage, so the client knows how to draw the percentage bar.
Parameters
[in] mapname
See also
SV_SetExpectedHunkUsage (Copied from server to here)
Definition at line 457 of file cl_cgame.c.
Referenced by CL_CM_LoadMap().
void CL_SetUserCmdValue (int userCmdValue, int flags, float sensitivityScale, int mpIdentClient)
CL_SetUserCmdValue.
Parameters
[in] userCmdValue
[in] flags
[in] sensitivityScale
[in] mpIdentClient
Definition at line 205 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void CL_ShutdownCGame (void)
CL_ShutdownCGame.
Definition at line 586 of file cl_cgame.c.
Referenced by CL_ShutdownAll(), CL_Vid_Restart_f(), Com_Quit_f(), and Hunk_Clear().
void CL_UpdateLevelHunkUsage (void)
This updates the "hunkusage.dat" file with the current map and it's hunk usage count.
This is used for level loading, so we can show a percentage bar dependant on the amount of hunk memory allocated so far
This will be slightly inaccurate if some settings like sound quality are changed, but these things should only account for a small variation (hopefully)
Definition at line 1047 of file cl_cgame.c.
Referenced by CL_Init(), and CL_InitCGame().
static int FloatAsInt (float f) static
Definition at line 599 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls().
void Key_GetBindingBuf (int keynum, char * buf, int buflen)
Referenced by CL_CgameSystemCalls().
void Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
Referenced by CL_CgameSystemCalls().
Variable Documentation
botlib_export_t* botlib_export
Definition at line 39 of file sv_game.c.