ET: Legacy: src/client/cl_input.c File Reference
cl_input.c File Reference
Builds an intended movement command to send to the server.
#include "client.h"
Functions
void IN_MLookDown (void)
IN_MLookDown.
void IN_MLookUp (void)
IN_MLookUp.
void IN_KeyDown (kbutton_t *b)
IN_KeyDown.
void IN_KeyUp (kbutton_t *b)
IN_KeyUp.
float CL_KeyState (kbutton_t *key)
CL_KeyState.
void IN_UpDown (void)
IN_UpDown.
void IN_UpUp (void)
IN_UpUp.
void IN_DownDown (void)
IN_DownDown.
void IN_DownUp (void)
IN_DownUp.
void IN_LeftDown (void)
IN_LeftDown.
void IN_LeftUp (void)
IN_LeftUp.
void IN_RightDown (void)
IN_RightDown.
void IN_RightUp (void)
IN_RightUp.
void IN_ForwardDown (void)
IN_ForwardDown.
void IN_ForwardUp (void)
IN_ForwardUp.
void IN_BackDown (void)
IN_BackDown.
void IN_BackUp (void)
IN_BackUp.
void IN_LookupDown (void)
IN_LookupDown.
void IN_LookupUp (void)
IN_LookupUp.
void IN_LookdownDown (void)
IN_LookdownDown.
void IN_LookdownUp (void)
IN_LookdownUp.
void IN_MoveleftDown (void)
IN_MoveleftDown.
void IN_MoveleftUp (void)
IN_MoveleftUp.
void IN_MoverightDown (void)
IN_MoverightDown.
void IN_MoverightUp (void)
IN_MoverightUp.
void IN_SpeedDown (void)
IN_SpeedDown.
void IN_SpeedUp (void)
IN_SpeedUp.
void IN_StrafeDown (void)
IN_StrafeDown.
void IN_StrafeUp (void)
IN_StrafeUp.
void IN_Button0Down (void)
IN_Button0Down.
void IN_Button0Up (void)
IN_Button0Up.
void IN_Button1Down (void)
IN_Button1Down.
void IN_Button1Up (void)
IN_Button1Up.
void IN_UseItemDown (void)
IN_UseItemDown.
void IN_UseItemUp (void)
IN_UseItemUp.
void IN_Button3Down (void)
IN_Button3Down.
void IN_Button3Up (void)
IN_Button3Up.
void IN_ActivateDown (void)
IN_ActivateDown.
void IN_ActivateUp (void)
IN_ActivateUp.
void IN_SprintDown (void)
IN_SprintDown.
void IN_SprintUp (void)
IN_SprintUp.
void IN_Wbutton0Down (void)
wbuttons (wolf buttons)
void IN_Wbutton0Up (void)
IN_Wbutton0Up.
void IN_ZoomDown (void)
IN_ZoomDown.
void IN_ZoomUp (void)
IN_ZoomUp.
void IN_ReloadDown (void)
IN_ReloadDown.
void IN_ReloadUp (void)
IN_ReloadUp.
void IN_LeanLeftDown (void)
IN_LeanLeftDown.
void IN_LeanLeftUp (void)
IN_LeanLeftUp.
void IN_LeanRightDown (void)
IN_LeanRightDown.
void IN_LeanRightUp (void)
IN_LeanRightUp.
void IN_ProneDown (void)
IN_ProneDown Kick now wbutton prone.
void IN_ProneUp (void)
IN_ProneUp.
void IN_Help (void)
IN_Help.
void CL_AdjustAngles (void)
Moves the local angle positions.
void CL_KeyMove (usercmd_t *cmd)
Sets the usercmd_t based on key states.
void CL_MouseEvent (int dx, int dy, int time)
CL_MouseEvent.
void CL_JoystickEvent (int axis, int value, int time)
Joystick values stay set until changed.
void CL_JoystickMove (usercmd_t *cmd)
CL_JoystickMove.
void CL_MouseMove (usercmd_t *cmd)
CL_MouseMove.
void CL_CmdButtons (usercmd_t *cmd)
CL_CmdButtons.
void CL_FinishMove (usercmd_t *cmd)
CL_FinishMove.
usercmd_t CL_CreateCmd (void)
CL_CreateCmd.
void CL_CreateNewCommands (void)
Create a new usercmd_t structure for this frame.
qboolean CL_ReadyToSendPacket (void)
CL_ReadyToSendPacket.
void CL_WritePacket (void)
Create and send the command packet to the server Including both the reliable commands and the usercmds.
void CL_SendCmd (void)
Called every frame to builds and sends a command packet to the server.
void CL_InitInput (void)
CL_InitInput.
void CL_ClearKeys (void)
CL_ClearKeys.
Variables
unsigned frame_msec
int old_com_frameTime
static kbutton_t kb [NUM_BUTTONS]
static kbuttons_t dtmapping []
cvar_t * cl_yawspeed
cvar_t * cl_pitchspeed
cvar_t * cl_run
cvar_t * cl_anglespeedkey
cvar_t * cl_recoilPitch
cvar_t * cl_bypassMouseInput
cvar_t * cl_doubletapdelay
Detailed Description
Builds an intended movement command to send to the server.
Definition in file cl_input.c.
Function Documentation
void CL_AdjustAngles (void)
Moves the local angle positions.
Definition at line 695 of file cl_input.c.
Referenced by CL_CreateCmd().
void CL_ClearKeys (void)
CL_ClearKeys.
Note
Unused
Definition at line 1488 of file cl_input.c.
void CL_CmdButtons (usercmd_t * cmd)
CL_CmdButtons.
Parameters
[in,out] cmd
Definition at line 989 of file cl_input.c.
Referenced by CL_CreateCmd().
usercmd_t CL_CreateCmd (void)
CL_CreateCmd.
Returns
Definition at line 1063 of file cl_input.c.
Referenced by CL_CreateNewCommands().
void CL_CreateNewCommands (void)
Create a new usercmd_t structure for this frame.
Definition at line 1128 of file cl_input.c.
Referenced by CL_SendCmd().
void CL_FinishMove (usercmd_t * cmd)
CL_FinishMove.
Parameters
[out] cmd
Definition at line 1038 of file cl_input.c.
Referenced by CL_CreateCmd().
void CL_InitInput (void)
CL_InitInput.
Definition at line 1413 of file cl_input.c.
Referenced by CL_Init().
void CL_JoystickEvent (int axis, int value, int time)
Joystick values stay set until changed.
Parameters
[in] axis
[in] value
time - unused
Definition at line 860 of file cl_input.c.
Referenced by Com_EventLoop().
void CL_JoystickMove (usercmd_t * cmd)
CL_JoystickMove.
Parameters
[in,out] cmd
Definition at line 873 of file cl_input.c.
Referenced by CL_CreateCmd().
void CL_KeyMove (usercmd_t * cmd)
Sets the usercmd_t based on key states.
Parameters
cmd
Definition at line 722 of file cl_input.c.
Referenced by CL_CreateCmd().
float CL_KeyState (kbutton_t * key)
CL_KeyState.
Parameters
key
Returns
The fraction of the frame that the key was down
Definition at line 205 of file cl_input.c.
Referenced by CL_AdjustAngles(), and CL_KeyMove().
void CL_MouseEvent (int dx, int dy, int time)
CL_MouseEvent.
Parameters
[in] dx
[in] dy
time - unused
Definition at line 820 of file cl_input.c.
Referenced by Com_EventLoop().
void CL_MouseMove (usercmd_t * cmd)
CL_MouseMove.
Parameters
[in,out] cmd
Definition at line 916 of file cl_input.c.
Referenced by CL_CreateCmd().
qboolean CL_ReadyToSendPacket (void)
CL_ReadyToSendPacket.
Returns qfalse if we are over the maxpackets limit and should choke back the bandwidth a bit by not sending a packet this frame. All the commands will still get delivered in the next packet, but saving a header and getting more delta compression will reduce total bandwidth.
Returns
Definition at line 1172 of file cl_input.c.
Referenced by CL_SendCmd().
void CL_SendCmd (void)
Called every frame to builds and sends a command packet to the server.
Definition at line 1380 of file cl_input.c.
Referenced by CL_Frame().
void CL_WritePacket (void)
Create and send the command packet to the server Including both the reliable commands and the usercmds.
During normal gameplay, a client packet will contain something like:
4 sequence number 2 qport 4 serverid 4 acknowledged sequence number 4 clc.serverCommandSequence <optional reliable commands> 1 clc_move or clc_moveNoDelta 1 command count <count * usercmds>
Definition at line 1248 of file cl_input.c.
Referenced by CL_Disconnect(), CL_DownloadsComplete(), CL_ParseDownload(), and CL_SendCmd().
void IN_ActivateDown (void)
IN_ActivateDown.
Definition at line 525 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ActivateUp (void)
IN_ActivateUp.
Definition at line 533 of file cl_input.c.
Referenced by CL_InitInput().
void IN_BackDown (void)
IN_BackDown.
Definition at line 329 of file cl_input.c.
Referenced by CL_InitInput().
void IN_BackUp (void)
IN_BackUp.
Definition at line 337 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Button0Down (void)
IN_Button0Down.
Definition at line 441 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Button0Up (void)
IN_Button0Up.
Definition at line 449 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Button1Down (void)
IN_Button1Down.
Definition at line 457 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Button1Up (void)
IN_Button1Up.
Definition at line 465 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Button3Down (void)
IN_Button3Down.
Definition at line 489 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Button3Up (void)
IN_Button3Up.
Definition at line 497 of file cl_input.c.
Referenced by CL_InitInput().
void IN_DownDown (void)
IN_DownDown.
Definition at line 265 of file cl_input.c.
Referenced by CL_InitInput().
void IN_DownUp (void)
IN_DownUp.
Definition at line 273 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ForwardDown (void)
IN_ForwardDown.
Definition at line 313 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ForwardUp (void)
IN_ForwardUp.
Definition at line 321 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Help (void)
IN_Help.
Definition at line 675 of file cl_input.c.
Referenced by CL_InitInput().
void IN_KeyDown (kbutton_t * b)
IN_KeyDown.
Parameters
[in,out] b
Definition at line 96 of file cl_input.c.
Referenced by IN_ActivateDown(), IN_BackDown(), IN_Button0Down(), IN_Button1Down(), IN_Button3Down(), IN_DownDown(), IN_ForwardDown(), IN_LeanLeftDown(), IN_LeanRightDown(), IN_LeftDown(), IN_LookdownDown(), IN_LookupDown(), IN_MoveleftDown(), IN_MoverightDown(), IN_ProneDown(), IN_ReloadDown(), IN_RightDown(), IN_SpeedDown(), IN_SprintDown(), IN_StrafeDown(), IN_UpDown(), IN_UseItemDown(), IN_Wbutton0Down(), and IN_ZoomDown().
void IN_KeyUp (kbutton_t * b)
IN_KeyUp.
Parameters
[in,out] b
Definition at line 147 of file cl_input.c.
Referenced by IN_ActivateUp(), IN_BackUp(), IN_Button0Up(), IN_Button1Up(), IN_Button3Up(), IN_DownUp(), IN_ForwardUp(), IN_LeanLeftUp(), IN_LeanRightUp(), IN_LeftUp(), IN_LookdownUp(), IN_LookupUp(), IN_MoveleftUp(), IN_MoverightUp(), IN_ProneUp(), IN_ReloadUp(), IN_RightUp(), IN_SpeedUp(), IN_SprintUp(), IN_StrafeUp(), IN_UpUp(), IN_UseItemUp(), IN_Wbutton0Up(), and IN_ZoomUp().
void IN_LeanLeftDown (void)
IN_LeanLeftDown.
Definition at line 605 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LeanLeftUp (void)
IN_LeanLeftUp.
Definition at line 613 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LeanRightDown (void)
IN_LeanRightDown.
Definition at line 621 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LeanRightUp (void)
IN_LeanRightUp.
Definition at line 629 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LeftDown (void)
IN_LeftDown.
Definition at line 281 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LeftUp (void)
IN_LeftUp.
Definition at line 289 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LookdownDown (void)
IN_LookdownDown.
Definition at line 361 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LookdownUp (void)
IN_LookdownUp.
Definition at line 369 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LookupDown (void)
IN_LookupDown.
Definition at line 345 of file cl_input.c.
Referenced by CL_InitInput().
void IN_LookupUp (void)
IN_LookupUp.
Definition at line 353 of file cl_input.c.
Referenced by CL_InitInput().
void IN_MLookDown (void)
IN_MLookDown.
Definition at line 79 of file cl_input.c.
Referenced by CL_InitInput().
void IN_MLookUp (void)
IN_MLookUp.
Definition at line 87 of file cl_input.c.
Referenced by CL_InitInput().
void IN_MoveleftDown (void)
IN_MoveleftDown.
Definition at line 377 of file cl_input.c.
Referenced by CL_InitInput().
void IN_MoveleftUp (void)
IN_MoveleftUp.
Definition at line 385 of file cl_input.c.
Referenced by CL_InitInput().
void IN_MoverightDown (void)
IN_MoverightDown.
Definition at line 393 of file cl_input.c.
Referenced by CL_InitInput().
void IN_MoverightUp (void)
IN_MoverightUp.
Definition at line 401 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ProneDown (void)
IN_ProneDown Kick now wbutton prone.
Definition at line 639 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ProneUp (void)
IN_ProneUp.
Definition at line 647 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ReloadDown (void)
IN_ReloadDown.
Definition at line 589 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ReloadUp (void)
IN_ReloadUp.
Definition at line 597 of file cl_input.c.
Referenced by CL_InitInput().
void IN_RightDown (void)
IN_RightDown.
Definition at line 297 of file cl_input.c.
Referenced by CL_InitInput().
void IN_RightUp (void)
IN_RightUp.
Definition at line 305 of file cl_input.c.
Referenced by CL_InitInput().
void IN_SpeedDown (void)
IN_SpeedDown.
Definition at line 409 of file cl_input.c.
Referenced by CL_InitInput().
void IN_SpeedUp (void)
IN_SpeedUp.
Definition at line 417 of file cl_input.c.
Referenced by CL_InitInput().
void IN_SprintDown (void)
IN_SprintDown.
Definition at line 541 of file cl_input.c.
Referenced by CL_InitInput().
void IN_SprintUp (void)
IN_SprintUp.
Definition at line 549 of file cl_input.c.
Referenced by CL_InitInput().
void IN_StrafeDown (void)
IN_StrafeDown.
Definition at line 425 of file cl_input.c.
Referenced by CL_InitInput().
void IN_StrafeUp (void)
IN_StrafeUp.
Definition at line 433 of file cl_input.c.
Referenced by CL_InitInput().
void IN_UpDown (void)
IN_UpDown.
Definition at line 249 of file cl_input.c.
Referenced by CL_InitInput().
void IN_UpUp (void)
IN_UpUp.
Definition at line 257 of file cl_input.c.
Referenced by CL_InitInput().
void IN_UseItemDown (void)
IN_UseItemDown.
Definition at line 473 of file cl_input.c.
Referenced by CL_InitInput().
void IN_UseItemUp (void)
IN_UseItemUp.
Definition at line 481 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Wbutton0Down (void)
wbuttons (wolf buttons)
Definition at line 557 of file cl_input.c.
Referenced by CL_InitInput().
void IN_Wbutton0Up (void)
IN_Wbutton0Up.
Definition at line 565 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ZoomDown (void)
IN_ZoomDown.
Definition at line 573 of file cl_input.c.
Referenced by CL_InitInput().
void IN_ZoomUp (void)
IN_ZoomUp.
Definition at line 581 of file cl_input.c.
Referenced by CL_InitInput().
Variable Documentation
cvar_t* cl_anglespeedkey
Definition at line 687 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_bypassMouseInput
Definition at line 689 of file cl_input.c.
Referenced by CL_Init(), and CL_KeyEvent().
cvar_t* cl_doubletapdelay
Definition at line 690 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_pitchspeed
Definition at line 685 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_recoilPitch
Definition at line 688 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_run
Definition at line 686 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_yawspeed
Definition at line 684 of file cl_input.c.
Referenced by CL_Init().
kbuttons_t dtmapping[] static
Initial value:
=
{
    KB_NONE,
    KB_MOVELEFT,
    KB_MOVERIGHT,
    KB_FORWARD,
    KB_BACK,
    KB_WBUTTONS4,
    KB_WBUTTONS5,
    KB_UP
}
Definition at line 64 of file cl_input.c.
Referenced by CL_CmdButtons(), and CL_KeyMove().
unsigned frame_msec
Definition at line 38 of file cl_input.c.
Referenced by CL_CreateNewCommands(), CL_KeyState(), CL_MouseMove(), and IN_KeyUp().
kbutton_t kb[NUM_BUTTONS] static
Definition at line 61 of file cl_input.c.
Referenced by CL_KeyEvent().
int old_com_frameTime
Definition at line 39 of file cl_input.c.
Referenced by CL_CreateNewCommands().