ET: Legacy: src/client/cl_ui.c File Reference
cl_ui.c File Reference
#include "client.h"
#include "../botlib/botlib.h"
Functions
static void GetClientState (uiClientState_t *state)
GetClientState.
void LAN_LoadCachedServers (void)
LAN_LoadCachedServers.
void LAN_SaveServersToFile (void)
Saves favorite servers into .dat file format.
static void LAN_ResetPings (int source)
LAN_ResetPings.
int LAN_AddServer (int source, const char *name, const char *address)
Adds servers to the internal data structure.
static void LAN_RemoveServer (int source, const char *addr)
Removes server(s) from the 'cache'.
static int LAN_GetServerCount (int source)
LAN_GetServerCount.
static void LAN_GetServerAddressString (int source, int n, char *buf, size_t buflen)
LAN_GetServerAddressString.
static void LAN_GetServerInfo (int source, int n, char *buf, size_t buflen)
LAN_GetServerInfo.
static int LAN_GetServerPing (int source, int n)
LAN_GetServerPing.
static serverInfo_t * LAN_GetServerPtr (int source, int n)
LAN_GetServerPtr.
static int LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
LAN_CompareServers.
static int LAN_GetPingQueueCount (void)
LAN_GetPingQueueCount.
static void LAN_ClearPing (int n)
LAN_ClearPing.
static void LAN_GetPing (int n, char *buf, size_t buflen, int *pingtime)
LAN_GetPing.
static void LAN_GetPingInfo (int n, char *buf, size_t buflen)
LAN_GetPingInfo.
static void LAN_MarkServerVisible (int source, int n, qboolean visible)
LAN_MarkServerVisible.
static int LAN_ServerIsVisible (int source, int n)
LAN_ServerIsVisible.
qboolean LAN_UpdateVisiblePings (int source)
LAN_UpdateVisiblePings.
int LAN_GetServerStatus (const char *serverAddress, char *serverStatus, size_t maxLen)
LAN_GetServerStatus.
qboolean LAN_ServerIsInFavoriteList (int source, int n)
LAN_ServerIsInFavoriteList.
static void CL_GetGlconfig (glconfig_t *config)
CL_GetGlconfig.
static void GetClipboardData (char *buf, unsigned int buflen)
GetClipboardData.
void Key_KeynumToStringBuf (int keynum, char *buf, size_t buflen)
Key_KeynumToStringBuf.
void Key_GetBindingBuf (int keynum, char *buf, size_t buflen)
Key_GetBindingBuf.
int Key_GetCatcher (void)
Key_GetCatcher.
void Key_SetCatcher (int catcher)
Key_SetCatcher.
static int GetConfigString (int index, char *buf, size_t size)
GetConfigString.
static int FloatAsInt (float f)
FloatAsInt.
intptr_t CL_UISystemCalls (intptr_t *args)
The ui module is making a system call.
void CL_ShutdownUI (void)
CL_ShutdownUI.
void CL_InitUI (void)
CL_InitUI.
qboolean UI_checkKeyExec (int key)
qboolean UI_GameCommand (void)
See if the current console command is claimed by the ui.
Variables
botlib_export_t * botlib_export
vm_t * uivm
interface to ui dll or vm
Function Documentation
static void CL_GetGlconfig (glconfig_t * config) static
CL_GetGlconfig.
Parameters
[out] config
Definition at line 911 of file cl_ui.c.
Referenced by CL_UISystemCalls().
void CL_InitUI (void)
CL_InitUI.
Todo:
: Never executed !
Definition at line 1379 of file cl_ui.c.
Referenced by CL_Disconnect(), CL_StartHunkUsers(), and CL_UI_Restart_f().
void CL_ShutdownUI (void)
CL_ShutdownUI.
Definition at line 1363 of file cl_ui.c.
Referenced by CL_Disconnect(), CL_Shutdown(), CL_ShutdownAll(), CL_UI_Restart_f(), CL_Vid_Restart_f(), Hunk_CheckMark(), and Hunk_Clear().
intptr_t CL_UISystemCalls (intptr_t * args)
The ui module is making a system call.
Parameters
[in] args
Returns
Definition at line 1049 of file cl_ui.c.
Referenced by CL_InitUI().
static int FloatAsInt (float f) static
FloatAsInt.
Parameters
[in] f
Returns
Definition at line 1036 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void GetClientState (uiClientState_t * state) static
GetClientState.
Parameters
[out] state
Definition at line 51 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void GetClipboardData (char * buf, unsigned int buflen) static
GetClipboardData.
Parameters
[out] buf
[in] buflen
Definition at line 921 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static int GetConfigString (int index, char * buf, size_t size) static
GetConfigString.
Parameters
[in] index
[out] buf
[in] size
Returns
Definition at line 1003 of file cl_ui.c.
Referenced by CL_UISystemCalls().
void Key_GetBindingBuf (int keynum, char * buf, size_t buflen)
Key_GetBindingBuf.
Parameters
[in] keynum
[out] buf
[in] buflen
Definition at line 955 of file cl_ui.c.
Referenced by CL_UISystemCalls().
int Key_GetCatcher (void)
Key_GetCatcher.
Returns
Definition at line 974 of file cl_ui.c.
Referenced by CL_CgameSystemCalls(), CL_ShutdownCGame(), CL_UISystemCalls(), IN_DeactivateMouse(), IN_Frame(), and IN_ProcessEvents().
void Key_KeynumToStringBuf (int keynum, char * buf, size_t buflen)
Key_KeynumToStringBuf.
Parameters
[in] keynum
[out] buf
[in] buflen
Definition at line 944 of file cl_ui.c.
Referenced by CL_UISystemCalls().
void Key_SetCatcher (int catcher)
Key_SetCatcher.
Parameters
[in] catcher
Definition at line 983 of file cl_ui.c.
Referenced by CL_CgameSystemCalls(), CL_ShutdownCGame(), and CL_UISystemCalls().
int LAN_AddServer (int source, const char * name, const char * address)
Adds servers to the internal data structure.
Note
Never ever add a localhost!
Parameters
[in] source
[in] name
[in] address
Returns
1 on success
Definition at line 197 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_ClearPing (int n) static
LAN_ClearPing.
Parameters
[in] n
Definition at line 712 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static int LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2) static
LAN_CompareServers.
Parameters
[in] source
[in] sortKey
[in] sortDir
[in] s1
[in] s2
Returns
Definition at line 604 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_GetPing (int n, char * buf, size_t buflen, int * pingtime) static
LAN_GetPing.
Parameters
[in] n
[out] buf
[in] buflen
[out] pingtime
Definition at line 724 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_GetPingInfo (int n, char * buf, size_t buflen) static
LAN_GetPingInfo.
Parameters
[in] n
[out] buf
[in] buflen
Definition at line 735 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static int LAN_GetPingQueueCount (void) static
LAN_GetPingQueueCount.
Returns
Definition at line 703 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_GetServerAddressString (int source, int n, char * buf, size_t buflen) static
LAN_GetServerAddressString.
Parameters
[in] source
[in] n
[out] buf
[in] buflen
Definition at line 414 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static int LAN_GetServerCount (int source) static
LAN_GetServerCount.
Parameters
[in] source
Returns
Definition at line 390 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_GetServerInfo (int source, int n, char * buf, size_t buflen) static
LAN_GetServerInfo.
Parameters
[in] source
[in] n
[in] buf
[in] buflen
Definition at line 453 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static int LAN_GetServerPing (int source, int n) static
LAN_GetServerPing.
Parameters
[in] source
[in] n
Returns
Definition at line 525 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static serverInfo_t* LAN_GetServerPtr (int source, int n) static
LAN_GetServerPtr.
Parameters
[in] source
[in] n
Returns
Definition at line 566 of file cl_ui.c.
Referenced by LAN_CompareServers().
int LAN_GetServerStatus (const char * serverAddress, char * serverStatus, size_t maxLen)
LAN_GetServerStatus.
Parameters
[in] serverAddress
[out] serverStatus
[in] maxLen
Returns
Definition at line 853 of file cl_ui.c.
Referenced by CL_UISystemCalls().
void LAN_LoadCachedServers (void)
LAN_LoadCachedServers.
Definition at line 64 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_MarkServerVisible (int source, int n, qboolean visible) static
LAN_MarkServerVisible.
Parameters
[in] source
[in] n
[in] visible
Definition at line 746 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_RemoveServer (int source, const char * addr) static
Removes server(s) from the 'cache'.
Parameters
[in] source Positive values AS_LOCAL, AS_GLOBAL, AS_FAVORITES or negative values AS_LOCAL_ALL, AS_GLOBAL_ALL, AS_FAVORITES_ALL to remove all
[in] addr Server address - in case of negative source param addr is not required
Definition at line 279 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static void LAN_ResetPings (int source) static
LAN_ResetPings.
Parameters
[in] source
Definition at line 158 of file cl_ui.c.
Referenced by CL_UISystemCalls().
void LAN_SaveServersToFile (void)
Saves favorite servers into .dat file format.
Definition at line 121 of file cl_ui.c.
Referenced by CL_SaveFavServersToFile_f(), LAN_AddServer(), and LAN_RemoveServer().
qboolean LAN_ServerIsInFavoriteList (int source, int n)
LAN_ServerIsInFavoriteList.
Parameters
[in] source
[in] n
Returns
Definition at line 864 of file cl_ui.c.
Referenced by CL_UISystemCalls().
static int LAN_ServerIsVisible (int source, int n) static
LAN_ServerIsVisible.
Parameters
[in] source
[in] n
Returns
Definition at line 810 of file cl_ui.c.
Referenced by CL_UISystemCalls().
qboolean LAN_UpdateVisiblePings (int source)
LAN_UpdateVisiblePings.
Parameters
[in] source
Returns
Definition at line 841 of file cl_ui.c.
Referenced by CL_UISystemCalls().
qboolean UI_checkKeyExec (int key)
Definition at line 1401 of file cl_ui.c.
Referenced by CL_KeyEvent().
qboolean UI_GameCommand (void)
See if the current console command is claimed by the ui.
Returns
Definition at line 1417 of file cl_ui.c.
Referenced by Cmd_ExecuteString().
Variable Documentation
botlib_export_t* botlib_export
Definition at line 39 of file sv_game.c.
vm_t* uivm
interface to ui dll or vm
Definition at line 45 of file cl_ui.c.
Referenced by CIN_PlayCinematic(), CL_CgameSystemCalls(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_KeyEvent(), CL_MouseEvent(), Com_UpdateInfoPacket(), IN_Help(), and SCR_DrawScreenField().