ET: Legacy: IEngineInterface71 Class Reference
IEngineInterface71 Class Reference abstract
#include <IEngineInterface.h>
Public Member Functions
virtual int AddBot (const MessageHelper &_data)=0
virtual void RemoveBot (const MessageHelper &_data)=0
virtual obResult ChangeTeam (int _client, int _newteam, const MessageHelper *_data)=0
virtual obResult ChangeClass (int _client, int _newclass, const MessageHelper *_data)=0
virtual void UpdateBotInput (int _client, const ClientInput &_input)=0
virtual void BotCommand (int _client, const char *_cmd)=0
virtual obBool IsInPVS (const float _pos[3], const float _target[3])=0
virtual obResult TraceLine (obTraceResult &_result, const float _start[3], const float _end[3], const AABB *_pBBox, int _mask, int _user, obBool _bUsePVS)=0
virtual int GetPointContents (const float _pos[3])=0
virtual GameEntity GetLocalGameEntity ()=0
virtual GameEntity FindEntityInSphere (const float _pos[3], float _radius, GameEntity _pStart, int classId)=0
virtual int GetEntityClass (const GameEntity _ent)=0
virtual obResult GetEntityCategory (const GameEntity _ent, BitFlag32 &_category)=0
virtual obResult GetEntityFlags (const GameEntity _ent, BitFlag64 &_flags)=0
virtual obResult GetEntityPowerups (const GameEntity _ent, BitFlag64 &_flags)=0
virtual obResult GetEntityEyePosition (const GameEntity _ent, float _pos[3])=0
virtual obResult GetEntityBonePosition (const GameEntity _ent, int _boneid, float _pos[3])=0
virtual obResult GetEntityOrientation (const GameEntity _ent, float _fwd[3], float _right[3], float _up[3])=0
virtual obResult GetEntityVelocity (const GameEntity _ent, float _velocity[3])=0
virtual obResult GetEntityPosition (const GameEntity _ent, float _pos[3])=0
virtual obResult GetEntityWorldAABB (const GameEntity _ent, AABB &_aabb)=0
virtual obResult GetEntityGroundEntity (const GameEntity _ent, GameEntity &moveent)=0
virtual GameEntity GetEntityOwner (const GameEntity _ent)=0
virtual int GetEntityTeam (const GameEntity _ent)=0
virtual const char * GetEntityName (const GameEntity _ent)=0
virtual obResult GetCurrentWeaponClip (const GameEntity _ent, FireMode _mode, int &_curclip, int &_maxclip)=0
virtual obResult GetCurrentAmmo (const GameEntity _ent, int _weaponId, int &_cur, int &_max)=0
virtual int GetGameTime ()=0
virtual void GetGoals ()=0
virtual void GetPlayerInfo (obPlayerInfo &info)=0
virtual obResult InterfaceSendMessage (const MessageHelper &_data, const GameEntity _ent)=0
virtual bool DebugLine (const float _start[3], const float _end[3], const obColor &_color, float _time)=0
virtual bool DebugRadius (const float _pos[3], const float _radius, const obColor &_color, float _time)=0
virtual bool DebugPolygon (const obVec3 *_verts, const int _numverts, const obColor &_color, float _time, int _flags)=0
virtual void PrintError (const char *_error)=0
virtual void PrintMessage (const char *_msg)=0
virtual bool PrintScreenText (const float _pos[3], float _duration, const obColor &_color, const char *_msg)=0
virtual const char * GetMapName ()=0
virtual void GetMapExtents (AABB &_aabb)=0
virtual GameEntity EntityFromID (const int _gameId)=0
virtual GameEntity EntityByName (const char *_name)=0
virtual int IDFromEntity (const GameEntity _ent)=0
virtual bool DoesEntityStillExist (const GameEntity &_hndl)=0
virtual int GetAutoNavFeatures (AutoNavFeature *_feature, int _max)=0
virtual const char * GetGameName ()=0
virtual const char * GetModName ()=0
virtual const char * GetModVers ()=0
virtual const char * GetBotPath ()=0
virtual const char * GetLogPath ()=0
Detailed Description
Definition at line 415 of file IEngineInterface.h.
Member Function Documentation
virtual int IEngineInterface71::AddBot (const MessageHelper & _data) pure virtual
Referenced by IEngineInterface71wrapper::AddBot().
virtual void IEngineInterface71::BotCommand (int _client, const char * _cmd) pure virtual
Referenced by IEngineInterface71wrapper::BotCommand().
virtual obResult IEngineInterface71::ChangeClass (int _client, int _newclass, const MessageHelper * _data) pure virtual
Referenced by IEngineInterface71wrapper::ChangeClass().
virtual obResult IEngineInterface71::ChangeTeam (int _client, int _newteam, const MessageHelper * _data) pure virtual
Referenced by IEngineInterface71wrapper::ChangeTeam().
virtual bool IEngineInterface71::DebugLine (const float _start[3], const float _end[3], const obColor & _color, float _time) pure virtual
virtual bool IEngineInterface71::DebugPolygon (const obVec3 * _verts, const int _numverts, const obColor & _color, float _time, int _flags) pure virtual
virtual bool IEngineInterface71::DebugRadius (const float _pos[3], const float _radius, const obColor & _color, float _time) pure virtual
virtual bool IEngineInterface71::DoesEntityStillExist (const GameEntity & _hndl) pure virtual
Referenced by IEngineInterface71wrapper::DoesEntityStillExist().
virtual GameEntity IEngineInterface71::EntityByName (const char * _name) pure virtual
Referenced by IEngineInterface71wrapper::EntityByName().
virtual GameEntity IEngineInterface71::EntityFromID (const int _gameId) pure virtual
Referenced by IEngineInterface71wrapper::EntityFromID().
virtual GameEntity IEngineInterface71::FindEntityInSphere (const float _pos[3], float _radius, GameEntity _pStart, int classId) pure virtual
Referenced by IEngineInterface71wrapper::FindEntityInSphere().
virtual int IEngineInterface71::GetAutoNavFeatures (AutoNavFeature * _feature, int _max) pure virtual
Referenced by IEngineInterface71wrapper::GetAutoNavFeatures().
virtual const char* IEngineInterface71::GetBotPath () pure virtual
Referenced by IEngineInterface71wrapper::GetBotPath().
virtual obResult IEngineInterface71::GetCurrentAmmo (const GameEntity _ent, int _weaponId, int & _cur, int & _max) pure virtual
Referenced by IEngineInterface71wrapper::GetCurrentAmmo().
virtual obResult IEngineInterface71::GetCurrentWeaponClip (const GameEntity _ent, FireMode _mode, int & _curclip, int & _maxclip) pure virtual
Referenced by IEngineInterface71wrapper::GetCurrentWeaponClip().
virtual obResult IEngineInterface71::GetEntityBonePosition (const GameEntity _ent, int _boneid, float _pos[3]) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityBonePosition().
virtual obResult IEngineInterface71::GetEntityCategory (const GameEntity _ent, BitFlag32 & _category) pure virtual
virtual int IEngineInterface71::GetEntityClass (const GameEntity _ent) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityClass().
virtual obResult IEngineInterface71::GetEntityEyePosition (const GameEntity _ent, float _pos[3]) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityEyePosition().
virtual obResult IEngineInterface71::GetEntityFlags (const GameEntity _ent, BitFlag64 & _flags) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityFlags().
virtual obResult IEngineInterface71::GetEntityGroundEntity (const GameEntity _ent, GameEntity & moveent) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityGroundEntity().
virtual const char* IEngineInterface71::GetEntityName (const GameEntity _ent) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityName().
virtual obResult IEngineInterface71::GetEntityOrientation (const GameEntity _ent, float _fwd[3], float _right[3], float _up[3]) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityOrientation().
virtual GameEntity IEngineInterface71::GetEntityOwner (const GameEntity _ent) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityOwner().
virtual obResult IEngineInterface71::GetEntityPosition (const GameEntity _ent, float _pos[3]) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityPosition().
virtual obResult IEngineInterface71::GetEntityPowerups (const GameEntity _ent, BitFlag64 & _flags) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityPowerups().
virtual int IEngineInterface71::GetEntityTeam (const GameEntity _ent) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityTeam().
virtual obResult IEngineInterface71::GetEntityVelocity (const GameEntity _ent, float _velocity[3]) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityVelocity().
virtual obResult IEngineInterface71::GetEntityWorldAABB (const GameEntity _ent, AABB & _aabb) pure virtual
Referenced by IEngineInterface71wrapper::GetEntityWorldAABB().
virtual const char* IEngineInterface71::GetGameName () pure virtual
Referenced by IEngineInterface71wrapper::GetGameName().
virtual int IEngineInterface71::GetGameTime () pure virtual
Referenced by IEngineInterface71wrapper::GetGameTime().
virtual void IEngineInterface71::GetGoals () pure virtual
Referenced by IEngineInterface71wrapper::GetGoals().
virtual GameEntity IEngineInterface71::GetLocalGameEntity () pure virtual
Referenced by IEngineInterface71wrapper::GetLocalGameEntity().
virtual const char* IEngineInterface71::GetLogPath () pure virtual
Referenced by IEngineInterface71wrapper::GetLogPath().
virtual void IEngineInterface71::GetMapExtents (AABB & _aabb) pure virtual
Referenced by IEngineInterface71wrapper::GetMapExtents().
virtual const char* IEngineInterface71::GetMapName () pure virtual
Referenced by IEngineInterface71wrapper::GetMapName().
virtual const char* IEngineInterface71::GetModName () pure virtual
Referenced by IEngineInterface71wrapper::GetModName().
virtual const char* IEngineInterface71::GetModVers () pure virtual
Referenced by IEngineInterface71wrapper::GetModVers().
virtual void IEngineInterface71::GetPlayerInfo (obPlayerInfo & info) pure virtual
Referenced by IEngineInterface71wrapper::GetPlayerInfo().
virtual int IEngineInterface71::GetPointContents (const float _pos[3]) pure virtual
Referenced by IEngineInterface71wrapper::GetPointContents().
virtual int IEngineInterface71::IDFromEntity (const GameEntity _ent) pure virtual
Referenced by IEngineInterface71wrapper::IDFromEntity().
virtual obResult IEngineInterface71::InterfaceSendMessage (const MessageHelper & _data, const GameEntity _ent) pure virtual
virtual obBool IEngineInterface71::IsInPVS (const float _pos[3], const float _target[3]) pure virtual
Referenced by IEngineInterface71wrapper::IsInPVS().
virtual void IEngineInterface71::PrintError (const char * _error) pure virtual
Referenced by IEngineInterface71wrapper::PrintError().
virtual void IEngineInterface71::PrintMessage (const char * _msg) pure virtual
Referenced by IEngineInterface71wrapper::PrintMessage().
virtual bool IEngineInterface71::PrintScreenText (const float _pos[3], float _duration, const obColor & _color, const char * _msg) pure virtual
Referenced by IEngineInterface71wrapper::PrintScreenText().
virtual void IEngineInterface71::RemoveBot (const MessageHelper & _data) pure virtual
Referenced by IEngineInterface71wrapper::RemoveBot().
virtual obResult IEngineInterface71::TraceLine (obTraceResult & _result, const float _start[3], const float _end[3], const AABB * _pBBox, int _mask, int _user, obBool _bUsePVS) pure virtual
virtual void IEngineInterface71::UpdateBotInput (int _client, const ClientInput & _input) pure virtual
Referenced by IEngineInterface71wrapper::UpdateBotInput().
The documentation for this class was generated from the following file:
src/Omnibot/Common/IEngineInterface.h