ET: Legacy: GameEntity Class Reference
GameEntity Class Reference
#include <Omni-Bot_Types.h>
Data Structures
union udatatype
Public Member Functions
obint16 GetIndex () const
obint16 GetSerial () const
obint32 AsInt () const
void FromInt (obint32 _n)
void Reset ()
bool IsValid () const
bool operator!= (const GameEntity &_other) const
bool operator== (const GameEntity &_other) const
GameEntity (obint16 _index, obint16 _serial)
GameEntity ()
Private Attributes
union GameEntity::udatatype udata
Detailed Description
Definition at line 47 of file Omni-Bot_Types.h.
Constructor & Destructor Documentation
GameEntity::GameEntity (obint16 _index, obint16 _serial) inline explicit
Definition at line 87 of file Omni-Bot_Types.h.
GameEntity::GameEntity () inline
Definition at line 92 of file Omni-Bot_Types.h.
Referenced by Reset().
Member Function Documentation
obint32 GameEntity::AsInt () const inline
Definition at line 59 of file Omni-Bot_Types.h.
void GameEntity::FromInt (obint32 _n) inline
Definition at line 63 of file Omni-Bot_Types.h.
obint16 GameEntity::GetIndex () const inline
Definition at line 50 of file Omni-Bot_Types.h.
Referenced by EntityFromHandle(), ETInterface::GetEntityPosition(), and ETInterface::GetEntityWorldAABB().
obint16 GameEntity::GetSerial () const inline
Definition at line 54 of file Omni-Bot_Types.h.
Referenced by EntityFromHandle().
bool GameEntity::IsValid () const inline
Definition at line 73 of file Omni-Bot_Types.h.
Referenced by ETInterface::DoesEntityStillExist(), ETInterface::FindEntityInSphere(), and ETInterface::InterfaceSendMessage().
bool GameEntity::operator!= (const GameEntity & _other) const inline
Definition at line 78 of file Omni-Bot_Types.h.
bool GameEntity::operator== (const GameEntity & _other) const inline
Definition at line 82 of file Omni-Bot_Types.h.
void GameEntity::Reset () inline
Definition at line 68 of file Omni-Bot_Types.h.
Referenced by ETInterface::TraceLine().
Field Documentation
union GameEntity::udatatype GameEntity::udata private
Referenced by AsInt(), FromInt(), GameEntity(), GetIndex(), GetSerial(), IsValid(), operator!=(), and operator==().
The documentation for this class was generated from the following file:
src/Omnibot/Common/Omni-Bot_Types.h