ET: Legacy: KeyVals Class Reference
KeyVals Class Reference
#include <Omni-Bot_Types.h>
Public Types
enum { MaxArgs = 32, MaxArgLength = 32, MaxStringLength = 64 }
Public Member Functions
bool SetInt (const char *_key, int _val)
KeyVals::SetInt.
bool SetFloat (const char *_key, float _val)
KeyVals::SetFloat.
bool SetEntity (const char *_key, GameEntity _val)
KeyVals::SetEntity.
bool SetVector (const char *_key, float _x, float _y, float _z)
KeyVals::SetVector.
bool SetVector (const char *_key, const float *_v)
KeyVals::SetVector.
bool SetString (const char *_key, const char *_value)
KeyVals::SetString.
bool Set (const char *_key, const obUserData &_value)
KeyVals::Set.
bool GetInt (const char *_key, int &_val) const
KeyVals::GetInt.
bool GetFloat (const char *_key, float &_val) const
KeyVals::GetFloat.
bool GetEntity (const char *_key, GameEntity &_val) const
KeyVals::GetEntity.
bool GetVector (const char *_key, float &_x, float &_y, float &_z) const
KeyVals::GetVector.
bool GetVector (const char *_key, float *_v) const
KeyVals::GetVector.
bool GetString (const char *_key, const char *&_value) const
KeyVals::GetString.
void Reset ()
KeyVals::Reset.
void GetKV (int _index, const char *&_key, obUserData &ud) const
KeyVals::GetKV.
KeyVals ()
KeyVals::KeyVals.
Private Member Functions
bool SetKeyVal (const char *_key, const obUserData &_ud)
KeyVals::SetKeyVal.
bool GetKeyVal (const char *_key, obUserData &_ud) const
KeyVals::GetKeyVal.
Private Attributes
char m_Key [MaxArgs][MaxArgLength]
char m_String [MaxArgs][MaxStringLength]
obUserData m_Value [MaxArgs]
Detailed Description
Definition at line 1111 of file Omni-Bot_Types.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MaxArgs
MaxArgLength
MaxStringLength
Definition at line 1114 of file Omni-Bot_Types.h.
Constructor & Destructor Documentation
KeyVals::KeyVals ()
KeyVals::KeyVals.
Definition at line 402 of file BotLoadLibrary.cpp.
Member Function Documentation
bool KeyVals::GetEntity (const char * _key, GameEntity & _val) const
KeyVals::GetEntity.
Parameters
[in] _key
[out] _val
Returns
Definition at line 583 of file BotLoadLibrary.cpp.
bool KeyVals::GetFloat (const char * _key, float & _val) const
KeyVals::GetFloat.
Parameters
[in] _key
[out] _val
Returns
Definition at line 566 of file BotLoadLibrary.cpp.
bool KeyVals::GetInt (const char * _key, int & _val) const
KeyVals::GetInt.
Parameters
[in] _key
[out] _val
Returns
Definition at line 549 of file BotLoadLibrary.cpp.
bool KeyVals::GetKeyVal (const char * _key, obUserData & _ud) const private
KeyVals::GetKeyVal.
Parameters
[in] _key
[out] _ud
Returns
Definition at line 657 of file BotLoadLibrary.cpp.
void KeyVals::GetKV (int _index, const char *& _key, obUserData & ud) const
KeyVals::GetKV.
Parameters
[in] _index
[out] _key
[out] ud
Definition at line 676 of file BotLoadLibrary.cpp.
bool KeyVals::GetString (const char * _key, const char *& _val) const
KeyVals::GetString.
Parameters
[in] _key
[out] _val
Returns
Definition at line 640 of file BotLoadLibrary.cpp.
bool KeyVals::GetVector (const char * _key, float & _x, float & _y, float & _z) const
KeyVals::GetVector.
Parameters
[in] _key
[out] _x
[out] _y
[out] _z
Returns
Definition at line 602 of file BotLoadLibrary.cpp.
bool KeyVals::GetVector (const char * _key, float * _v) const
KeyVals::GetVector.
Parameters
[in] _key
[out] _v
Returns
Definition at line 621 of file BotLoadLibrary.cpp.
void KeyVals::Reset ()
KeyVals::Reset.
Definition at line 410 of file BotLoadLibrary.cpp.
bool KeyVals::Set (const char * _key, const obUserData & _value)
KeyVals::Set.
Parameters
[in] _key
[in] _value
Returns
Definition at line 503 of file BotLoadLibrary.cpp.
Referenced by Bot_Util_AddGoal().
bool KeyVals::SetEntity (const char * _key, GameEntity _val)
KeyVals::SetEntity.
Parameters
[in] _key
[in] _val
Returns
Definition at line 445 of file BotLoadLibrary.cpp.
Referenced by Bot_Util_AddGoal().
bool KeyVals::SetFloat (const char * _key, float _val)
KeyVals::SetFloat.
Parameters
[in] _key
[in] _val
Returns
Definition at line 434 of file BotLoadLibrary.cpp.
bool KeyVals::SetInt (const char * _key, int _val)
KeyVals::SetInt.
Parameters
[in] _key
[in] _val
Returns
Definition at line 423 of file BotLoadLibrary.cpp.
Referenced by Bot_Util_AddGoal().
bool KeyVals::SetKeyVal (const char * _key, const obUserData & _ud) private
KeyVals::SetKeyVal.
Parameters
[in] _key
[in] _ud
Returns
Definition at line 514 of file BotLoadLibrary.cpp.
bool KeyVals::SetString (const char * _key, const char * _value)
KeyVals::SetString.
Parameters
[in] _key
[in] _value
Returns
Definition at line 480 of file BotLoadLibrary.cpp.
Referenced by Bot_Util_AddGoal().
bool KeyVals::SetVector (const char * _key, float _x, float _y, float _z)
KeyVals::SetVector.
Parameters
[in] _key
[in] _x
[in] _y
[in] _z
Returns
Definition at line 458 of file BotLoadLibrary.cpp.
bool KeyVals::SetVector (const char * _key, const float * _v)
KeyVals::SetVector.
Parameters
[in] _key
[in] _v
Returns
Definition at line 469 of file BotLoadLibrary.cpp.
Field Documentation
char KeyVals::m_Key[MaxArgs][MaxArgLength] private
Definition at line 1137 of file Omni-Bot_Types.h.
char KeyVals::m_String[MaxArgs][MaxStringLength] private
Definition at line 1138 of file Omni-Bot_Types.h.
obUserData KeyVals::m_Value[MaxArgs] private
Definition at line 1139 of file Omni-Bot_Types.h.
The documentation for this class was generated from the following files:
src/Omnibot/Common/Omni-Bot_Types.h
src/Omnibot/Common/BotLoadLibrary.cpp