ET: Legacy: IEngineInterface Class Reference
IEngineInterface Class Reference abstract
#include <IEngineInterface.h>
Public Types
enum DebugRenderFlags { DR_NODEPTHTEST = (1 << 0) }
Public Member Functions
virtual int AddBot (const MessageHelper &_data)=0
virtual void RemoveBot (const MessageHelper &_data)=0
virtual obResult ChangeTeam (int _client, int _newteam, const MessageHelper *_data)=0
virtual obResult ChangeClass (int _client, int _newclass, const MessageHelper *_data)=0
virtual void UpdateBotInput (int _client, const ClientInput &_input)=0
virtual void BotCommand (int _client, const char *_cmd)=0
virtual obBool IsInPVS (const float _pos[3], const float _target[3])=0
virtual obResult TraceLine (obTraceResult &_result, const float _start[3], const float _end[3], const AABB *_pBBox, int _mask, int _user, obBool _bUsePVS)=0
virtual int GetPointContents (const float _pos[3])=0
virtual GameEntity GetLocalGameEntity ()=0
virtual GameEntity FindEntityInSphere (const float _pos[3], float _radius, GameEntity _pStart, int classId)=0
virtual int GetEntityClass (const GameEntity _ent)=0
virtual obResult GetEntityCategory (const GameEntity _ent, BitFlag32 &_category)=0
virtual obResult GetEntityFlags (const GameEntity _ent, BitFlag64 &_flags)=0
virtual obResult GetEntityPowerups (const GameEntity _ent, BitFlag64 &_flags)=0
virtual obResult GetEntityEyePosition (const GameEntity _ent, float _pos[3])=0
virtual obResult GetEntityBonePosition (const GameEntity _ent, int _boneid, float _pos[3])=0
virtual obResult GetEntityOrientation (const GameEntity _ent, float _fwd[3], float _right[3], float _up[3])=0
virtual obResult GetEntityVelocity (const GameEntity _ent, float _velocity[3])=0
virtual obResult GetEntityPosition (const GameEntity _ent, float _pos[3])=0
virtual obResult GetEntityLocalAABB (const GameEntity _ent, AABB &_aabb)=0
virtual obResult GetEntityWorldAABB (const GameEntity _ent, AABB &_aabb)=0
virtual obResult GetEntityWorldOBB (const GameEntity _ent, float *_center, float *_axis0, float *_axis1, float *_axis2, float *_extents)=0
virtual obResult GetEntityGroundEntity (const GameEntity _ent, GameEntity &moveent)=0
virtual GameEntity GetEntityOwner (const GameEntity _ent)=0
virtual int GetEntityTeam (const GameEntity _ent)=0
virtual const char * GetEntityName (const GameEntity _ent)=0
virtual obResult GetCurrentWeaponClip (const GameEntity _ent, FireMode _mode, int &_curclip, int &_maxclip)=0
virtual obResult GetCurrentAmmo (const GameEntity _ent, int _weaponId, FireMode _mode, int &_cur, int &_max)=0
virtual int GetGameTime ()=0
virtual void GetGoals ()=0
virtual void GetPlayerInfo (obPlayerInfo &info)=0
virtual obResult InterfaceSendMessage (const MessageHelper &_data, const GameEntity _ent)=0
virtual bool DebugLine (const float _start[3], const float _end[3], const obColor &_color, float _time)
virtual bool DebugBox (const float _mins[3], const float _maxs[3], const obColor &_color, float _time)
virtual bool DebugArrow (const float _start[3], const float _end[3], const obColor &_color, float _time)
virtual bool DebugRadius (const float _pos[3], const float _radius, const obColor &_color, float _time)
virtual bool DebugPolygon (const obVec3 *_verts, const int _numverts, const obColor &_color, float _time, int _flags)
virtual bool PrintScreenText (const float _pos[3], float _duration, const obColor &_color, const char *_msg)
virtual void PrintError (const char *_error)=0
virtual void PrintMessage (const char *_msg)=0
virtual const char * GetMapName ()=0
virtual void GetMapExtents (AABB &_aabb)=0
virtual GameEntity EntityFromID (const int _gameId)=0
virtual GameEntity EntityByName (const char *_name)=0
virtual int IDFromEntity (const GameEntity _ent)=0
virtual bool DoesEntityStillExist (const GameEntity &_hndl)=0
virtual int GetAutoNavFeatures (AutoNavFeature *_feature, int _max)=0
virtual const char * GetGameName ()=0
virtual const char * GetModName ()=0
virtual const char * GetModVers ()=0
virtual const char * GetBotPath ()=0
virtual const char * GetLogPath ()=0
IEngineInterface ()
virtual ~IEngineInterface ()
Detailed Description
Definition at line 163 of file IEngineInterface.h.
Member Enumeration Documentation
enum IEngineInterface::DebugRenderFlags
Enumerator
DR_NODEPTHTEST
Definition at line 166 of file IEngineInterface.h.
Constructor & Destructor Documentation
IEngineInterface::IEngineInterface () inline
Definition at line 407 of file IEngineInterface.h.
virtual IEngineInterface::~IEngineInterface () inline virtual
Definition at line 410 of file IEngineInterface.h.
Member Function Documentation
virtual int IEngineInterface::AddBot (const MessageHelper & _data) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::BotCommand (int _client, const char * _cmd) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::ChangeClass (int _client, int _newclass, const MessageHelper * _data) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::ChangeTeam (int _client, int _newteam, const MessageHelper * _data) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual bool IEngineInterface::DebugArrow (const float _start[3], const float _end[3], const obColor & _color, float _time) inline virtual
Definition at line 323 of file IEngineInterface.h.
virtual bool IEngineInterface::DebugBox (const float _mins[3], const float _maxs[3], const obColor & _color, float _time) inline virtual
Definition at line 316 of file IEngineInterface.h.
virtual bool IEngineInterface::DebugLine (const float _start[3], const float _end[3], const obColor & _color, float _time) inline virtual
Reimplemented in ETInterface.
Definition at line 309 of file IEngineInterface.h.
virtual bool IEngineInterface::DebugPolygon (const obVec3 * _verts, const int _numverts, const obColor & _color, float _time, int _flags) inline virtual
Definition at line 337 of file IEngineInterface.h.
virtual bool IEngineInterface::DebugRadius (const float _pos[3], const float _radius, const obColor & _color, float _time) inline virtual
Reimplemented in ETInterface.
Definition at line 330 of file IEngineInterface.h.
virtual bool IEngineInterface::DoesEntityStillExist (const GameEntity & _hndl) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual GameEntity IEngineInterface::EntityByName (const char * _name) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual GameEntity IEngineInterface::EntityFromID (const int _gameId) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual GameEntity IEngineInterface::FindEntityInSphere (const float _pos[3], float _radius, GameEntity _pStart, int classId) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual int IEngineInterface::GetAutoNavFeatures (AutoNavFeature * _feature, int _max) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetBotPath () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetCurrentAmmo (const GameEntity _ent, int _weaponId, FireMode _mode, int & _cur, int & _max) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetCurrentWeaponClip (const GameEntity _ent, FireMode _mode, int & _curclip, int & _maxclip) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityBonePosition (const GameEntity _ent, int _boneid, float _pos[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityCategory (const GameEntity _ent, BitFlag32 & _category) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
Referenced by Bot_Event_EntityCreated().
virtual int IEngineInterface::GetEntityClass (const GameEntity _ent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
Referenced by Bot_Event_EntityCreated().
virtual obResult IEngineInterface::GetEntityEyePosition (const GameEntity _ent, float _pos[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityFlags (const GameEntity _ent, BitFlag64 & _flags) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityGroundEntity (const GameEntity _ent, GameEntity & moveent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityLocalAABB (const GameEntity _ent, AABB & _aabb) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetEntityName (const GameEntity _ent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityOrientation (const GameEntity _ent, float _fwd[3], float _right[3], float _up[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual GameEntity IEngineInterface::GetEntityOwner (const GameEntity _ent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityPosition (const GameEntity _ent, float _pos[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
Referenced by Bot_Event_Sound().
virtual obResult IEngineInterface::GetEntityPowerups (const GameEntity _ent, BitFlag64 & _flags) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual int IEngineInterface::GetEntityTeam (const GameEntity _ent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityVelocity (const GameEntity _ent, float _velocity[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityWorldAABB (const GameEntity _ent, AABB & _aabb) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::GetEntityWorldOBB (const GameEntity _ent, float * _center, float * _axis0, float * _axis1, float * _axis2, float * _extents) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetGameName () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual int IEngineInterface::GetGameTime () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::GetGoals () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual GameEntity IEngineInterface::GetLocalGameEntity () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetLogPath () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::GetMapExtents (AABB & _aabb) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetMapName () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetModName () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual const char* IEngineInterface::GetModVers () pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::GetPlayerInfo (obPlayerInfo & info) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual int IEngineInterface::GetPointContents (const float _pos[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual int IEngineInterface::IDFromEntity (const GameEntity _ent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::InterfaceSendMessage (const MessageHelper & _data, const GameEntity _ent) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obBool IEngineInterface::IsInPVS (const float _pos[3], const float _target[3]) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::PrintError (const char * _error) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::PrintMessage (const char * _msg) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual bool IEngineInterface::PrintScreenText (const float _pos[3], float _duration, const obColor & _color, const char * _msg) inline virtual
Reimplemented in IEngineInterface71wrapper.
Definition at line 344 of file IEngineInterface.h.
virtual void IEngineInterface::RemoveBot (const MessageHelper & _data) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual obResult IEngineInterface::TraceLine (obTraceResult & _result, const float _start[3], const float _end[3], const AABB * _pBBox, int _mask, int _user, obBool _bUsePVS) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
virtual void IEngineInterface::UpdateBotInput (int _client, const ClientInput & _input) pure virtual
Implemented in ETInterface, and IEngineInterface71wrapper.
The documentation for this class was generated from the following file:
src/Omnibot/Common/IEngineInterface.h