ET: Legacy: MessageHelper Class Reference
MessageHelper Class Reference
#include <MessageHelper.h>
Public Member Functions
template<class Type >
Type * Get () const
template<class Type >
void Get2 (Type *&_p) const
int GetMessageId () const
operator bool () const
MessageHelper (int _msgId, void *_void=0, obuint32 _size=0)
~MessageHelper ()
Data Fields
int m_MessageId
Private Member Functions
MessageHelper ()
Private Attributes
void * m_pVoid
obuint32 m_BlockSize
Friends
class MessageRouter
Detailed Description
Definition at line 31 of file MessageHelper.h.
Constructor & Destructor Documentation
MessageHelper::MessageHelper (int _msgId, void * _void = 0, obuint32 _size = 0) inline
Definition at line 60 of file MessageHelper.h.
MessageHelper::~MessageHelper () inline
Definition at line 66 of file MessageHelper.h.
MessageHelper::MessageHelper () private
Member Function Documentation
template<class Type > Type* MessageHelper::Get () const inline
Definition at line 37 of file MessageHelper.h.
Referenced by ETInterface::InterfaceSendMessage().
template<class Type > void MessageHelper::Get2 (Type *& _p) const inline
Definition at line 44 of file MessageHelper.h.
Referenced by ETInterface::ChangeClass(), and ETInterface::ChangeTeam().
int MessageHelper::GetMessageId () const inline
Definition at line 50 of file MessageHelper.h.
Referenced by ETInterface::InterfaceSendMessage().
MessageHelper::operator bool () const inline
Definition at line 55 of file MessageHelper.h.
Friends And Related Function Documentation
friend class MessageRouter friend
Definition at line 34 of file MessageHelper.h.
Field Documentation
obuint32 MessageHelper::m_BlockSize private
Definition at line 73 of file MessageHelper.h.
int MessageHelper::m_MessageId mutable
Definition at line 68 of file MessageHelper.h.
void* MessageHelper::m_pVoid private
Definition at line 72 of file MessageHelper.h.
The documentation for this class was generated from the following file:
src/Omnibot/Common/MessageHelper.h