ET: Legacy: src/client/client.h File Reference
client.h File Reference
Primary header for client.
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "../renderercommon/tr_public.h"
#include "../ui/ui_public.h"
#include "keys.h"
#include "snd_public.h"
#include "../cgame/cg_public.h"
#include "../game/bg_public.h"
#include "../irc/irc_client.h"
Data Structures
struct clSnapshot_t
Snapshots are a view of the server at a given time.
struct doubleTap_t
struct outPacket_t
struct clientActive_t
The clientActive_t structure is wiped completely at every new gamestate_t, potentially several times during an established connection.
struct clientConnection_t
The clientConnection_t structure is wiped when disconnecting from a server, either to go to a full screen console, play a demo, or connect to a different server.
struct ping_t
struct serverInfo_t
struct clientStatic_t
the clientStatic_t structure is never wiped, and is used even when no client connection is active at all
struct kbutton_t
struct console_t
struct cinData_t
struct cinematic_t
Macros
#define RETRANSMIT_TIMEOUT 3000
time between connection packet retransmits
#define LIMBOCHAT_WIDTH 140
NOTE: buffer size indicator, not related to screen bbox.
#define LIMBOCHAT_HEIGHT 7
#define ETKEY_FILE "etkey"
#define ETKEY_SIZE 28
#define MAX_PARSE_ENTITIES 2048
#define NUM_CON_TIMES 10
console
#define CON_TEXTSIZE 131072
#define SCR_DrawSmallChar(x, y, ch) SCR_DrawChar(x, y, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT, ch, qtrue)
#define SCR_DrawBigString(x, y, s, color, noColorEscape) SCR_DrawStringExt(x, y, BIGCHAR_WIDTH, BIGCHAR_HEIGHT, s, color, qtrue, noColorEscape, qtrue, qfalse)
#define SCR_DrawSmallString(x, y, string, setColor, forceColor, noColorEscape) SCR_DrawStringExt(x, y, SMALLCHAR_WIDTH, BIGCHAR_HEIGHT, string, setColor, forceColor, noColorEscape, qfalse, qtrue)
#define MAX_CINEMATICS 16
Typedefs
typedef int cinHandle_t
Enumerations
enum kbuttons_t {
KB_NONE = -1, KB_LEFT, KB_RIGHT, KB_FORWARD,
KB_BACK, KB_LOOKUP, KB_LOOKDOWN, KB_MOVELEFT,
KB_MOVERIGHT, KB_STRAFE, KB_SPEED, KB_UP,
KB_DOWN, KB_BUTTONS0, KB_BUTTONS1, KB_BUTTONS2,
KB_BUTTONS3, KB_BUTTONS4, KB_BUTTONS5, KB_BUTTONS6,
KB_BUTTONS7, KB_WBUTTONS0, KB_WBUTTONS1, KB_WBUTTONS2,
KB_WBUTTONS3, KB_WBUTTONS4, KB_WBUTTONS5, KB_WBUTTONS6,
KB_WBUTTONS7, KB_MLOOK, NUM_BUTTONS
}
Functions
void CL_WriteWaveOpen (void)
CL_WriteWaveOpen.
void CL_WriteWaveClose (void)
CL_WriteWaveClose.
void CL_Init (void)
CL_Init.
void CL_FlushMemory (void)
Called by CL_MapLoading, CL_Connect_f, CL_PlayDemo_f, and CL_ParseGamestate the only ways a client gets into a game Also called by Com_Error.
void CL_ShutdownAll (void)
CL_ShutdownAll.
void CL_AddReliableCommand (const char *cmd)
The given command will be transmitted to the server, and is guaranteed to not have future usercmd_t executed before it is executed.
void CL_StartHunkUsers (void)
After the server has cleared the hunk, these will need to be restarted This is the only place that any of these functions are called from.
void CL_RequestMasterData (qboolean force)
CL_RequestMasterData.
void CL_Disconnect_f (void)
CL_Disconnect_f.
void CL_GetChallengePacket (void)
void CL_Vid_Restart_f (void)
Restart the video subsystem.
void CL_Snd_Restart_f (void)
Restart the sound subsystem.
void CL_NextDemo (void)
Called when a demo or cinematic finishes If the "nextdemo" cvar is set, that command will be issued.
void CL_ReadDemoMessage (void)
CL_ReadDemoMessage.
void CL_DownloadsComplete (void)
CL_AddFavServer_f DO NOT ACTIVATE UNTIL WE HAVE CLARIFIED SECURITY! (command execution vie ascripts) void CL_AddFavServer_f(void) { if (cls.state != CA_ACTIVE) { Com_Printf("Not connected to a server\n"); return; }.
void CL_GetPing (int n, char *buf, size_t buflen, int *pingtime)
CL_GetPing.
void CL_GetPingInfo (int n, char *buf, size_t buflen)
CL_GetPingInfo.
void CL_ClearPing (int n)
CL_ClearPing.
int CL_GetPingQueueCount (void)
CL_GetPingQueueCount.
void CL_ShutdownRef (void)
CL_ShutdownRef.
void CL_InitRef (void)
CL_InitRef.
int CL_ServerStatus (const char *serverAddress, char *serverStatusString, size_t maxLen)
CL_ServerStatus.
void CL_AddToLimboChat (const char *str)
CL_AddToLimboChat.
qboolean CL_GetLimboString (int index, char *buf)
CL_GetLimboString.
void CL_TranslateString (const char *string, char *dest_buffer)
Called by engine to handle translation.
const char * CL_TranslateStringBuf (const char *string)
Stores in a static buf, converts \n to chr(13)
void CL_TranslateStringMod (const char *string, char *dest_buffer)
Called by mod libs to handle translation.
void CL_OpenURL (const char *url)
CL_OpenURL.
void CL_Record (const char *name)
CL_Record.
qboolean CL_OpenAVIForWriting (const char *fileName)
Creates an AVI file and gets it into a state where writing the actual data can begin.
void CL_TakeVideoFrame (void)
CL_TakeVideoFrame.
void CL_WriteAVIVideoFrame (const byte *imageBuffer, int size)
CL_WriteAVIVideoFrame.
void CL_WriteAVIAudioFrame (const byte *pcmBuffer, int size)
CL_WriteAVIAudioFrame.
qboolean CL_CloseAVI (void)
Closes the AVI file and writes an index chunk.
qboolean CL_VideoRecording (void)
CL_VideoRecording.
void CL_DemoCleanUp (void)
CL_DemoCleanUp.
void CL_DemoCompleted (void)
CL_DemoCompleted.
void CL_WriteDemoMessage (msg_t *msg, int headerBytes)
Dumps the current net message, prefixed by the length.
void CL_StopRecord_f (void)
Stop recording a demo.
void CL_DemoRun (void)
CL_DemoRun.
void CL_DemoInit (void)
CL_DemoInit.
void CL_ClearKeys (void)
CL_ClearKeys.
void CL_InitInput (void)
CL_InitInput.
void CL_SendCmd (void)
Called every frame to builds and sends a command packet to the server.
void CL_ClearState (void)
Called before parsing a gamestate.
void CL_ReadPackets (void)
void CL_WritePacket (void)
Create and send the command packet to the server Including both the reliable commands and the usercmds.
void IN_Help (void)
IN_Help.
float CL_KeyState (kbutton_t *key)
CL_KeyState.
int Key_StringToKeynum (const char *str)
Returns a key number to be used to index keys[] by looking at the given string. Single ascii characters return themselves, while the K_* names are matched up.
char * Key_KeynumToString (int keynum)
Returns a string (either a single ascii char, a K_* name, or a 0x11 hex string) for the given keynum.
void CL_ParseSnapshot (msg_t *msg)
If the snapshot is parsed properly, it will be copied to cl.snap and saved in cl.snapshots[]. If the snapshot is invalid for any reason, no changes to the state will be made at all.
void CL_ParsePacketEntities (msg_t *msg, clSnapshot_t *oldframe, clSnapshot_t *newframe)
CL_ParsePacketEntities.
void CL_SystemInfoChanged (void)
The systeminfo configstring has been changed, so parse new information out of it. This will happen at every gamestate, and possibly during gameplay.
void CL_ParseServerMessage (msg_t *msg)
CL_ParseServerMessage.
void CL_ServerInfoPacket (netadr_t from, msg_t *msg)
CL_ServerInfoPacket.
void CL_LocalServers_f (void)
CL_LocalServers_f.
void CL_GlobalServers_f (void)
Sends a request for server list to the chosen master server. 0 fetch all master servers and 1-5 request a single master server.
void CL_Ping_f (void)
CL_Ping_f.
qboolean CL_UpdateVisiblePings_f (int source)
CL_UpdateVisiblePings_f.
void Con_DrawCharacter (int cx, int line, int num)
void Con_ToggleConsole_f (void)
Toggle console.
void Con_DrawNotify (void)
Draws the last few lines of output transparently over the game top.
void Con_ClearNotify (void)
Con_ClearNotify.
void Con_Clear_f (void)
Clear console.
void Con_Dump_f (void)
Save content to a file.
void Con_CheckResize (void)
Reformat the buffer if the line width has changed.
void Cmd_CompleteTxtName (char *args, int argNum)
Complete file text name.
void Con_Init (void)
Initialize console.
void Con_Shutdown (void)
Free client console commands before shutdown.
void Con_Linefeed (qboolean skipnotify)
Line feed.
void CL_ConsolePrint (char *txt)
Handles cursor positioning, line wrapping, etc.
void Con_DrawClock (void)
Draw system clock.
void Con_DrawVersion (void)
Draw version text.
void Con_DrawInput (void)
Draw the editline after a ] prompt.
void Con_DrawScrollbar (int length, float x, float y)
Draw scrollbar.
void Con_DrawSolidConsole (float frac)
Draws the console with the solid background.
void Con_DrawConsole (void)
Draw console.
void Con_RunConsole (void)
Scroll console up or down.
void Con_PageUp (void)
Page up.
void Con_PageDown (void)
Page down.
void Con_ScrollUp (int lines)
Scroll up.
void Con_ScrollDown (int lines)
Scroll down.
void Con_ScrollTop (void)
Scroll to top.
void Con_ScrollBottom (void)
Scroll to bottom.
void Con_Close (void)
Close console.
void SCR_Init (void)
SCR_Init.
void SCR_UpdateScreen (void)
This is called every frame, and can also be called explicitly to flush text to the screen.
void SCR_DebugGraph (float value)
SCR_DebugGraph.
void SCR_AdjustFrom640 (float *x, float *y, float *w, float *h)
Adjusted for resolution and screen aspect ratio.
void SCR_FillRect (float x, float y, float width, float height, const float *color)
Coordinates are 640*480 virtual values.
void SCR_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
Coordinates are 640*480 virtual values.
void SCR_DrawChar (int x, int y, float w, float h, int ch, qboolean nativeResolution)
Chars are drawn at 640*480 virtual or native screen size.
void SCR_DrawStringExt (int x, int y, float w, float h, const char *string, float *setColor, qboolean forceColor, qboolean noColorEscape, qboolean dropShadow, qboolean nativeResolution)
Draws a multi-colored string with a drop shadow, optionally forcing to a fixed color.
void SCR_DrawCinematic (void)
SCR_DrawCinematic.
void SCR_RunCinematic (void)
SCR_RunCinematic.
void SCR_StopCinematic (void)
SCR_StopCinematic.
int CIN_PlayCinematic (const char *name, int x, int y, int w, int h, int flags)
CIN_PlayCinematic.
e_status CIN_StopCinematic (int handle)
CIN_StopCinematic.
e_status CIN_RunCinematic (int handle)
CIN_RunCinematic.
void CIN_DrawCinematic (int handle)
CIN_DrawCinematic.
void CIN_SetExtents (int handle, int x, int y, int w, int h)
CIN_SetExtents.
void CIN_UploadCinematic (int handle)
CIN_UploadCinematic.
void CIN_CloseAllVideos (void)
Stop all the cinematics.
void CIN_Init (void)
CIN_Init.
void CIN_Shutdown (void)
CIN_Shutdown.
cinematic_t * CIN_GetCinematicByHandle (cinHandle_t handle)
CIN_GetCinematicByHandle.
void ROQ_UpdateCinematic (cinematic_t *cin, int time)
ROQ_UpdateCinematic.
qboolean ROQ_StartRead (cinematic_t *cin)
ROQ_StartRead.
void ROQ_StopVideo (cinematic_t *cin)
ROQ_StopVideo.
void ROQ_Reset (cinematic_t *cin)
ROQ_Reset.
void ROQ_Init (void)
ROQ_Init.
void CL_InitCGame (void)
Should only be called by CL_StartHunkUsers.
void CL_ShutdownCGame (void)
CL_ShutdownCGame.
qboolean CL_GameCommand (void)
See if the current console command is claimed by the cgame.
void CL_CGameRendering (void)
CL_CGameRendering.
void CL_SetCGameTime (void)
CL_SetCGameTime.
void CL_FirstSnapshot (void)
CL_FirstSnapshot.
void CL_ShaderStateChanged (void)
void CL_UpdateLevelHunkUsage (void)
This updates the "hunkusage.dat" file with the current map and it's hunk usage count.
void CL_CGameBinaryMessageReceived (const byte *buf, int buflen, int serverTime)
CL_CGameBinaryMessageReceived.
qboolean CL_GetSnapshot (int snapshotNumber, snapshot_t *snapshot)
CL_GetSnapshot.
qboolean CL_GetServerCommand (int serverCommandNumber)
Set up argc/argv for the given command.
void CL_AdjustTimeDelta (void)
Adjust the clients view of server time.
void CL_InitUI (void)
CL_InitUI.
void CL_ShutdownUI (void)
CL_ShutdownUI.
int Key_GetCatcher (void)
Key_GetCatcher.
void Key_SetCatcher (int catcher)
Key_SetCatcher.
void LAN_LoadCachedServers (void)
LAN_LoadCachedServers.
void LAN_SaveServersToFile (void)
Saves favorite servers into .dat file format.
void CL_Netchan_Transmit (netchan_t *chan, msg_t *msg)
CL_Netchan_Transmit.
void CL_Netchan_TransmitNextFragment (netchan_t *chan)
CL_Netchan_TransmitNextFragment.
qboolean CL_Netchan_Process (netchan_t *chan, msg_t *msg)
CL_Netchan_Process.
Variables
int g_console_field_width
clientActive_t cl
clientConnection_t clc
clientStatic_t cls
vm_t * cgvm
interface to cgame dll or vm
vm_t * uivm
interface to ui dll or vm
refexport_t re
interface to refresh .dll
cvar_t * cl_nodelta
cvar_t * cl_debugMove
cvar_t * cl_noprint
cvar_t * cl_timegraph
cvar_t * cl_maxpackets
cvar_t * cl_packetdup
cvar_t * cl_shownet
cvar_t * cl_shownuments
cvar_t * cl_showSend
cvar_t * cl_showServerCommands
cvar_t * cl_timeNudge
cvar_t * cl_showTimeDelta
cvar_t * cl_freezeDemo
cvar_t * cl_yawspeed
cvar_t * cl_pitchspeed
cvar_t * cl_run
cvar_t * cl_anglespeedkey
cvar_t * cl_recoilPitch
cvar_t * cl_bypassMouseInput
cvar_t * cl_doubletapdelay
cvar_t * cl_sensitivity
cvar_t * cl_freelook
cvar_t * cl_mouseAccel
cvar_t * cl_showMouseRate
cvar_t * cl_avidemo
cvar_t * cl_aviMotionJpeg
cvar_t * m_pitch
cvar_t * m_yaw
cvar_t * m_forward
cvar_t * m_side
cvar_t * m_filter
cvar_t * cl_timedemo
cvar_t * cl_activeAction
cvar_t * cl_autorecord
cvar_t * cl_activatelean
cvar_t * cl_allowDownload
cvar_t * cl_conXOffset
cvar_t * cl_missionStats
cvar_t * cl_profile
cvar_t * cl_defaultProfile
cvar_t * cl_consoleKeys
demoPlayInfo_t dpi
int cl_connectedToPureServer
int cl_connectedToCheatServer
console_t con
Detailed Description
Primary header for client.
Definition in file client.h.
Macro Definition Documentation
#define CON_TEXTSIZE 131072
Definition at line 589 of file client.h.
Referenced by Con_CheckResize(), and Con_Clear_f().
#define ETKEY_FILE "etkey"
Definition at line 56 of file client.h.
Referenced by CL_GenerateETKey(), and CL_UpdateGUID().
#define ETKEY_SIZE 28
Definition at line 57 of file client.h.
Referenced by CL_GenerateETKey(), and CL_UpdateGUID().
#define LIMBOCHAT_HEIGHT 7
Definition at line 54 of file client.h.
Referenced by CL_AddToLimboChat(), and CL_GetLimboString().
#define LIMBOCHAT_WIDTH 140
NOTE: buffer size indicator, not related to screen bbox.
Definition at line 53 of file client.h.
Referenced by CL_AddToLimboChat().
#define MAX_CINEMATICS 16
Definition at line 679 of file client.h.
Referenced by CIN_CloseAllVideos(), CIN_HandleForCinematic(), CIN_HandleValid(), CIN_ListCinematics_f(), and CIN_PlayCinematic().
#define MAX_PARSE_ENTITIES 2048
the parseEntities array must be large enough to hold PACKET_BACKUP frames of entities, so that when a delta compressed message arives from the server it can be un-deltad from the original
Definition at line 111 of file client.h.
Referenced by CL_DeltaEntity(), CL_GetSnapshot(), CL_ParseDemoSnapShotSimple(), CL_ParsePacketEntities(), CL_ParseSnapshot(), and CL_PeekSnapshot().
#define NUM_CON_TIMES 10
console
Definition at line 587 of file client.h.
Referenced by CL_ConsolePrint(), Con_ClearNotify(), Con_DrawNotify(), and Con_Linefeed().
#define RETRANSMIT_TIMEOUT 3000
time between connection packet retransmits
Definition at line 51 of file client.h.
Referenced by CL_CheckForResend(), and CL_MapLoading().
#define SCR_DrawBigString (x, y, s, color, noColorEscape) SCR_DrawStringExt(x, y, BIGCHAR_WIDTH, BIGCHAR_HEIGHT, s, color, qtrue, noColorEscape, qtrue, qfalse)
Definition at line 674 of file client.h.
Referenced by Field_VariableSizeDraw().
#define SCR_DrawSmallChar (x, y, ch) SCR_DrawChar(x, y, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT, ch, qtrue)
Definition at line 672 of file client.h.
Referenced by Con_DrawClock(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_DrawVersion(), and Field_VariableSizeDraw().
#define SCR_DrawSmallString (x, y, string, setColor, forceColor, noColorEscape) SCR_DrawStringExt(x, y, SMALLCHAR_WIDTH, BIGCHAR_HEIGHT, string, setColor, forceColor, noColorEscape, qfalse, qtrue)
Definition at line 675 of file client.h.
Referenced by Field_VariableSizeDraw().
Typedef Documentation
typedef int cinHandle_t
Definition at line 681 of file client.h.
Enumeration Type Documentation
enum kbuttons_t
Enumerator
KB_NONE
KB_LEFT
KB_RIGHT
KB_FORWARD
KB_BACK
KB_LOOKUP
KB_LOOKDOWN
KB_MOVELEFT
KB_MOVERIGHT
KB_STRAFE
KB_SPEED
KB_UP
KB_DOWN
KB_BUTTONS0
KB_BUTTONS1
KB_BUTTONS2
KB_BUTTONS3
KB_BUTTONS4
KB_BUTTONS5
KB_BUTTONS6
KB_BUTTONS7
unused
KB_WBUTTONS0
KB_WBUTTONS1
KB_WBUTTONS2
KB_WBUTTONS3
KB_WBUTTONS4
KB_WBUTTONS5
KB_WBUTTONS6
KB_WBUTTONS7
KB_MLOOK
NUM_BUTTONS
Definition at line 519 of file client.h.
Function Documentation
void CIN_CloseAllVideos (void)
Stop all the cinematics.
Definition at line 563 of file cl_cinematic.c.
void CIN_DrawCinematic (int handle)
CIN_DrawCinematic.
Parameters
[in] handle
Definition at line 675 of file cl_cinematic.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SCR_DrawCinematic().
cinematic_t* CIN_GetCinematicByHandle (cinHandle_t handle)
CIN_GetCinematicByHandle.
Parameters
[in] handle
Returns
A cinematic_t for the given cinHandle_t
Definition at line 127 of file cl_cinematic.c.
Referenced by CIN_DrawCinematic(), CIN_ResetCinematic(), CIN_RunCinematic(), CIN_SetExtents(), CIN_StopCinematic(), and CIN_UploadCinematic().
void CIN_Init (void)
CIN_Init.
Definition at line 519 of file cl_cinematic.c.
Referenced by CL_Init().
int CIN_PlayCinematic (const char * name, int x, int y, int w, int h, int flags)
CIN_PlayCinematic.
Parameters
[in] name
[in] x
[in] y
[in] w
[in] h
[in] flags
Returns
Definition at line 314 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic_f(), CL_CgameSystemCalls(), CL_InitRef(), and CL_UISystemCalls().
e_status CIN_RunCinematic (int handle)
CIN_RunCinematic.
Parameters
[in] handle
Returns
Definition at line 584 of file cl_cinematic.c.
Referenced by CL_CgameSystemCalls(), CL_InitRef(), CL_UISystemCalls(), and SCR_RunCinematic().
void CIN_SetExtents (int handle, int x, int y, int w, int h)
CIN_SetExtents.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 623 of file cl_cinematic.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void CIN_Shutdown (void)
CIN_Shutdown.
Definition at line 541 of file cl_cinematic.c.
Referenced by CL_Shutdown().
e_status CIN_StopCinematic (cinHandle_t handle)
CIN_StopCinematic.
Parameters
[in] handle
Returns
Definition at line 482 of file cl_cinematic.c.
Referenced by CIN_RunCinematic(), CL_CgameSystemCalls(), CL_UISystemCalls(), and SCR_StopCinematic().
void CIN_UploadCinematic (int handle)
CIN_UploadCinematic.
Parameters
handle
Definition at line 706 of file cl_cinematic.c.
Referenced by CL_InitRef().
void CL_AddReliableCommand (const char * cmd)
The given command will be transmitted to the server, and is guaranteed to not have future usercmd_t executed before it is executed.
Parameters
cmd
Definition at line 200 of file cl_main.c.
Referenced by CL_CgameSystemCalls(), CL_CheckUserinfo(), CL_Disconnect(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_ParseDownload(), CL_ResetPureClientAtServer(), and CL_SendPureChecksums().
void CL_AddToLimboChat (const char * str)
CL_AddToLimboChat.
Parameters
[in] str
Note
Unused
Definition at line 4038 of file cl_main.c.
void CL_AdjustTimeDelta (void)
Adjust the clients view of server time.
We attempt to have cl.serverTime exactly equal the server's view of time plus the timeNudge, but with variable latencies over the internet it will often need to drift a bit to match conditions.
Our ideal time would be to have the adjusted time approach, but not pass, the very latest snapshot.
Adjustments are only made when a new snapshot arrives with a rational latency, which keeps the adjustment process framerate independent and prevents massive overadjustment during times of significant packet loss or bursted delayed packets.
Todo:
: is this a problem for cgame?
Definition at line 1253 of file cl_cgame.c.
Referenced by CL_ParseDemo(), and CL_SetCGameTime().
void CL_CGameBinaryMessageReceived (const byte * buf, int buflen, int serverTime)
CL_CGameBinaryMessageReceived.
Parameters
[in] buf
[in] buflen
[in] serverTime
Definition at line 546 of file cl_cgame.c.
Referenced by CL_ParseBinaryMessage().
void CL_CGameRendering (void)
CL_CGameRendering.
Definition at line 1229 of file cl_cgame.c.
Referenced by SCR_DrawScreenField().
void CL_ClearKeys (void)
CL_ClearKeys.
Note
Unused
Definition at line 1488 of file cl_input.c.
void CL_ClearPing (int n)
CL_ClearPing.
Parameters
[in] n
Definition at line 3685 of file cl_main.c.
Referenced by CL_UpdateVisiblePings_f(), and LAN_ClearPing().
void CL_ClearState (void)
Called before parsing a gamestate.
Definition at line 590 of file cl_main.c.
Referenced by CL_Disconnect(), CL_Init(), CL_ParseDemo(), and CL_ParseGamestate().
qboolean CL_CloseAVI (void)
Closes the AVI file and writes an index chunk.
Returns
Definition at line 638 of file cl_avi.c.
Referenced by CL_CheckFileSize(), and CL_StopVideo_f().
void CL_ConsolePrint (char * txt)
Handles cursor positioning, line wrapping, etc.
Parameters
[in] txt Handles cursor positioning, line wrapping, etc.
txt - unused
Definition at line 399 of file cl_console.c.
void CL_DemoCleanUp (void)
CL_DemoCleanUp.
Definition at line 1140 of file cl_demo.c.
Referenced by CL_Disconnect().
void CL_DemoCompleted (void)
CL_DemoCompleted.
Definition at line 1157 of file cl_demo.c.
Referenced by CL_ParseDemo(), and CL_ReadDemoMessage().
void CL_DemoInit (void)
CL_DemoInit.
Definition at line 1777 of file cl_demo.c.
Referenced by CL_Init().
void CL_DemoRun (void)
CL_DemoRun.
Definition at line 1193 of file cl_demo.c.
Referenced by CL_SetCGameTime().
void CL_Disconnect_f (void)
CL_Disconnect_f.
Definition at line 821 of file cl_main.c.
Referenced by CL_Init(), and CL_KeyEvent().
void CL_DownloadsComplete (void)
CL_AddFavServer_f DO NOT ACTIVATE UNTIL WE HAVE CLARIFIED SECURITY! (command execution vie ascripts) void CL_AddFavServer_f(void) { if (cls.state != CA_ACTIVE) { Com_Printf("Not connected to a server\n"); return; }.
if (clc.demoplaying) { return; }
(void) LAN_AddServer(AS_FAVORITES, "", NET_AdrToString(clc.netchan.remoteAddress)); } CL_DownloadsComplete
Definition at line 1333 of file cl_main.c.
Referenced by Com_DownloadsComplete().
void CL_FirstSnapshot (void)
CL_FirstSnapshot.
Definition at line 1319 of file cl_cgame.c.
Referenced by CL_SetCGameTime().
void CL_FlushMemory (void)
Called by CL_MapLoading, CL_Connect_f, CL_PlayDemo_f, and CL_ParseGamestate the only ways a client gets into a game Also called by Com_Error.
Called by CL_MapLoading, CL_Connect_f, CL_PlayDemo_f, and CL_ParseGamestate the only ways a client gets into a game Also called by Com_Error.
Definition at line 446 of file cl_main.c.
qboolean CL_GameCommand (void)
See if the current console command is claimed by the cgame.
Returns
See if the current console command is claimed by the cgame.
Returns
Definition at line 1216 of file cl_cgame.c.
void CL_GetChallengePacket (void)
qboolean CL_GetLimboString (int index, char * buf)
CL_GetLimboString.
Parameters
[in] index
[out] buf
Returns
Definition at line 4081 of file cl_main.c.
Referenced by CL_UISystemCalls().
void CL_GetPing (int n, char * buf, size_t buflen, int * pingtime)
CL_GetPing.
Parameters
[in] n
[out] buf
[in] buflen
[out] pingtime
Definition at line 3620 of file cl_main.c.
Referenced by CL_UpdateVisiblePings_f(), and LAN_GetPing().
void CL_GetPingInfo (int n, char * buf, size_t buflen)
CL_GetPingInfo.
Parameters
[in] n
[out] buf
[in] buflen
Definition at line 3666 of file cl_main.c.
Referenced by LAN_GetPingInfo().
int CL_GetPingQueueCount (void)
CL_GetPingQueueCount.
Returns
Definition at line 3699 of file cl_main.c.
Referenced by CL_UpdateVisiblePings_f(), and LAN_GetPingQueueCount().
qboolean CL_GetServerCommand (int serverCommandNumber)
Set up argc/argv for the given command.
Parameters
[in] serverCommandNumber
Returns
Definition at line 316 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls(), and CL_DemoFastForward().
qboolean CL_GetSnapshot (int snapshotNumber, snapshot_t * snapshot)
CL_GetSnapshot.
Parameters
[in] snapshotNumber
[out] snapshot
Returns
Todo:
: configstring changes and server commands!!!
Definition at line 143 of file cl_cgame.c.
Referenced by CL_CgameSystemCalls(), and CL_PeekSnapshot().
void CL_GlobalServers_f (void)
Sends a request for server list to the chosen master server. 0 fetch all master servers and 1-5 request a single master server.
Definition at line 3514 of file cl_main.c.
Referenced by CL_Init().
void CL_Init (void)
CL_Init.
Todo:
: remove caching system? inspect!
Definition at line 2722 of file cl_main.c.
void CL_InitCGame (void)
Should only be called by CL_StartHunkUsers.
Definition at line 1151 of file cl_cgame.c.
Referenced by CL_DownloadsComplete(), and CL_Vid_Restart_f().
void CL_InitInput (void)
CL_InitInput.
Definition at line 1413 of file cl_input.c.
Referenced by CL_Init().
void CL_InitRef (void)
CL_InitRef.
Definition at line 2583 of file cl_main.c.
Referenced by CL_Init(), and CL_Vid_Restart_f().
void CL_InitUI (void)
CL_InitUI.
Todo:
: Never executed !
Definition at line 1379 of file cl_ui.c.
Referenced by CL_Disconnect(), CL_StartHunkUsers(), and CL_UI_Restart_f().
float CL_KeyState (kbutton_t * key)
CL_KeyState.
Parameters
key
Returns
The fraction of the frame that the key was down
Definition at line 205 of file cl_input.c.
Referenced by CL_AdjustAngles(), and CL_KeyMove().
void CL_LocalServers_f (void)
CL_LocalServers_f.
Definition at line 3460 of file cl_main.c.
Referenced by CL_Init().
qboolean CL_Netchan_Process (netchan_t * chan, msg_t * msg)
CL_Netchan_Process.
Parameters
[in] chan
[in] msg
Returns
Definition at line 204 of file cl_net_chan.c.
Referenced by CL_PacketEvent().
void CL_Netchan_Transmit (netchan_t * chan, msg_t * msg)
CL_Netchan_Transmit.
Parameters
[in] chan
[in] msg
Definition at line 186 of file cl_net_chan.c.
Referenced by CL_WritePacket().
void CL_Netchan_TransmitNextFragment (netchan_t * chan)
CL_Netchan_TransmitNextFragment.
Parameters
[in] chan
Definition at line 152 of file cl_net_chan.c.
Referenced by CL_WritePacket().
void CL_NextDemo (void)
Called when a demo or cinematic finishes If the "nextdemo" cvar is set, that command will be issued.
Definition at line 1483 of file cl_demo.c.
Referenced by CL_DemoCompleted().
qboolean CL_OpenAVIForWriting (const char * fileName)
Creates an AVI file and gets it into a state where writing the actual data can begin.
Parameters
[in] fileName
Returns
Definition at line 365 of file cl_avi.c.
Referenced by CL_CheckFileSize(), and CL_StartVideoRecording().
void CL_OpenURL (const char * url)
CL_OpenURL.
Parameters
[in] url
Definition at line 4146 of file cl_main.c.
Referenced by CL_UISystemCalls().
void CL_ParsePacketEntities (msg_t * msg, clSnapshot_t * oldframe, clSnapshot_t * newframe)
CL_ParsePacketEntities.
Parameters
[in] msg
[in] oldframe
[out] newframe
Note
oldnum is set to MAX_GENTITIES to ensure newnum will never be greater than oldnum in case of invalid oldframe or oldindex
Definition at line 260 of file cl_parse.c.
Referenced by CL_ParseDemoSnapShotSimple(), and CL_ParseSnapshot().
void CL_ParseServerMessage (msg_t * msg)
CL_ParseServerMessage.
Parameters
[in] msg
Definition at line 1057 of file cl_parse.c.
Referenced by CL_PacketEvent(), and CL_ReadDemoMessage().
void CL_ParseSnapshot (msg_t * msg)
If the snapshot is parsed properly, it will be copied to cl.snap and saved in cl.snapshots[]. If the snapshot is invalid for any reason, no changes to the state will be made at all.
Parameters
[in] msg
Definition at line 398 of file cl_parse.c.
Referenced by CL_ParseServerMessage(), and CL_PeekSnapshot().
void CL_Ping_f (void)
CL_Ping_f.
Definition at line 3774 of file cl_main.c.
Referenced by CL_Init().
void CL_ReadDemoMessage (void)
CL_ReadDemoMessage.
Definition at line 1271 of file cl_demo.c.
Referenced by CL_DemoFastForward(), CL_DemoRun(), CL_PlayDemo_f(), and CL_SetCGameTime().
void CL_ReadPackets (void)
void CL_Record (const char * name)
CL_Record.
Parameters
[in] name
Definition at line 1044 of file cl_demo.c.
Referenced by CL_ParseSnapshot(), and CL_Record_f().
void CL_RequestMasterData (qboolean force)
CL_RequestMasterData.
Parameters
[in] force
Definition at line 771 of file cl_main.c.
Referenced by CL_Connect_f(), CL_Frame(), and CL_UISystemCalls().
void CL_SendCmd (void)
Called every frame to builds and sends a command packet to the server.
Definition at line 1380 of file cl_input.c.
Referenced by CL_Frame().
void CL_ServerInfoPacket (netadr_t from, msg_t * msg)
CL_ServerInfoPacket.
Parameters
[in] from
[in] msg
Definition at line 3120 of file cl_main.c.
Referenced by CL_ConnectionlessPacket().
int CL_ServerStatus (const char * serverAddress, char * serverStatusString, size_t maxLen)
CL_ServerStatus.
Parameters
[in] serverAddress
[out] serverStatusString
[in] maxLen
Returns
Definition at line 3270 of file cl_main.c.
Referenced by LAN_GetServerStatus().
void CL_SetCGameTime (void)
CL_SetCGameTime.
Definition at line 1356 of file cl_cgame.c.
Referenced by CL_Frame().
void CL_ShaderStateChanged (void)
void CL_ShutdownAll (void)
CL_ShutdownAll.
Definition at line 391 of file cl_main.c.
void CL_ShutdownCGame (void)
CL_ShutdownCGame.
Definition at line 586 of file cl_cgame.c.
void CL_ShutdownRef (void)
CL_ShutdownRef.
Definition at line 2456 of file cl_main.c.
Referenced by CL_Shutdown(), and CL_Vid_Restart_f().
void CL_ShutdownUI (void)
CL_ShutdownUI.
Definition at line 1363 of file cl_ui.c.
void CL_Snd_Restart_f (void)
Restart the sound subsystem.
The cgame and game must also be forced to restart because handles will be invalid
Definition at line 1195 of file cl_main.c.
Referenced by CL_Init().
void CL_StartHunkUsers (void)
After the server has cleared the hunk, these will need to be restarted This is the only place that any of these functions are called from.
After the server has cleared the hunk, these will need to be restarted This is the only place that any of these functions are called from.
Definition at line 2497 of file cl_main.c.
void CL_StopRecord_f (void)
Stop recording a demo.
Definition at line 945 of file cl_demo.c.
Referenced by CL_DemoInit(), CL_Disconnect(), and CL_ShutdownAll().
void CL_SystemInfoChanged (void)
The systeminfo configstring has been changed, so parse new information out of it. This will happen at every gamestate, and possibly during gameplay.
Definition at line 596 of file cl_parse.c.
Referenced by CL_ConfigstringModified(), and CL_ParseGamestate().
void CL_TakeVideoFrame (void)
CL_TakeVideoFrame.
Definition at line 623 of file cl_avi.c.
Referenced by CL_CaptureFrameVideo().
void CL_TranslateString (const char * string, char * dest_buffer)
Called by engine to handle translation.
Parameters
[in] string to be translated
[out] dest_buffer translated text
Note
for mod translations use __(x) macro instead.
Definition at line 4099 of file cl_main.c.
Referenced by CL_TranslateStringBuf().
const char* CL_TranslateStringBuf (const char * string)
Stores in a static buf, converts \n to chr(13)
Todo:
Replace / remove.
Definition at line 4120 of file cl_main.c.
void CL_TranslateStringMod (const char * string, char * dest_buffer)
Called by mod libs to handle translation.
Parameters
[in] string to be translated
[out] dest_buffer translated text
Note
for client translations use _(x) macro instead.
Definition at line 4111 of file cl_main.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void CL_UpdateLevelHunkUsage (void)
This updates the "hunkusage.dat" file with the current map and it's hunk usage count.
This is used for level loading, so we can show a percentage bar dependant on the amount of hunk memory allocated so far
This will be slightly inaccurate if some settings like sound quality are changed, but these things should only account for a small variation (hopefully)
Definition at line 1047 of file cl_cgame.c.
Referenced by CL_Init(), and CL_InitCGame().
qboolean CL_UpdateVisiblePings_f (int source)
CL_UpdateVisiblePings_f.
Parameters
[in] source
Returns
Todo:
: Dead code, this part is NEVER REACHED !
Definition at line 3835 of file cl_main.c.
Referenced by LAN_UpdateVisiblePings().
void CL_Vid_Restart_f (void)
Restart the video subsystem.
We also have to reload the UI and CGame because the renderer doesn't know what graphics to reload
Definition at line 1092 of file cl_main.c.
Referenced by CL_Init(), and CL_Snd_Restart_f().
qboolean CL_VideoRecording (void)
CL_VideoRecording.
Returns
Definition at line 711 of file cl_avi.c.
Referenced by CL_CaptureFrameVideo(), CL_DemoCompleted(), CL_Frame(), CL_InitRef(), CL_StopVideo_f(), CL_Vid_Restart_f(), S_GetSoundtime(), and S_TransferStereo16().
void CL_WriteAVIAudioFrame (const byte * pcmBuffer, int size)
CL_WriteAVIAudioFrame.
Parameters
[in] pcmBuffer
[in] size
Definition at line 555 of file cl_avi.c.
Referenced by S_TransferStereo16().
void CL_WriteAVIVideoFrame (const byte * imageBuffer, int size)
CL_WriteAVIVideoFrame.
Parameters
[in] imageBuffer
[in] size
Definition at line 502 of file cl_avi.c.
Referenced by CL_InitRef().
void CL_WriteDemoMessage (msg_t * msg, int headerBytes)
Dumps the current net message, prefixed by the length.
Parameters
[in] msg
[in] headerBytes
Definition at line 926 of file cl_demo.c.
Referenced by CL_PacketEvent().
void CL_WritePacket (void)
Create and send the command packet to the server Including both the reliable commands and the usercmds.
During normal gameplay, a client packet will contain something like:
4 sequence number 2 qport 4 serverid 4 acknowledged sequence number 4 clc.serverCommandSequence <optional reliable commands> 1 clc_move or clc_moveNoDelta 1 command count <count * usercmds>
Definition at line 1248 of file cl_input.c.
Referenced by CL_Disconnect(), CL_DownloadsComplete(), CL_ParseDownload(), and CL_SendCmd().
void CL_WriteWaveClose (void)
CL_WriteWaveClose.
Definition at line 368 of file cl_main.c.
Referenced by CL_DemoCompleted(), and CL_WavStopRecord_f().
void CL_WriteWaveOpen (void)
CL_WriteWaveOpen.
Definition at line 301 of file cl_main.c.
Referenced by CL_PlayDemo_f(), and CL_WavRecord_f().
void Cmd_CompleteTxtName (char * args, int argNum)
Complete file text name.
Parameters
args - unused
[in] argNum
Definition at line 306 of file cl_console.c.
Referenced by Con_Init().
void Con_CheckResize (void)
Reformat the buffer if the line width has changed.
Definition at line 223 of file cl_console.c.
Referenced by CL_ConsolePrint(), and Con_DrawConsole().
void Con_Clear_f (void)
Clear console.
Definition at line 101 of file cl_console.c.
Referenced by Con_Init().
void Con_ClearNotify (void)
Con_ClearNotify.
Definition at line 208 of file cl_console.c.
Referenced by CL_GetServerCommand(), CL_InitCGame(), Con_CheckResize(), Con_Close(), and Con_ToggleConsole_f().
void Con_Close (void)
Close console.
Definition at line 1042 of file cl_console.c.
Referenced by CIN_PlayCinematic(), CL_Connect_f(), CL_GetServerCommand(), CL_InitCGame(), CL_MapLoading(), CL_PlayDemo_f(), and Com_GetAutoUpdate().
void Con_DrawCharacter (int cx, int line, int num)
void Con_DrawClock (void)
Draw system clock.
Definition at line 545 of file cl_console.c.
Referenced by Con_DrawSolidConsole().
void Con_DrawConsole (void)
Draw console.
Definition at line 873 of file cl_console.c.
Referenced by SCR_DrawScreenField().
void Con_DrawInput (void)
Draw the editline after a ] prompt.
Definition at line 571 of file cl_console.c.
Referenced by Con_DrawSolidConsole().
void Con_DrawNotify (void)
Draws the last few lines of output transparently over the game top.
Definition at line 609 of file cl_console.c.
Referenced by Con_DrawConsole().
void Con_DrawScrollbar (int length, float x, float y)
Draw scrollbar.
Parameters
[in] length
[in] x
[in] y
Definition at line 686 of file cl_console.c.
Referenced by Con_DrawSolidConsole().
void Con_DrawSolidConsole (float frac)
Draws the console with the solid background.
Parameters
[in] frac
Definition at line 718 of file cl_console.c.
Referenced by Con_DrawConsole().
void Con_DrawVersion (void)
Draw version text.
Definition at line 517 of file cl_console.c.
Referenced by Con_DrawSolidConsole().
void Con_Dump_f (void)
Save content to a file.
Definition at line 119 of file cl_console.c.
Referenced by Con_Init().
void Con_Init (void)
Initialize console.
Definition at line 317 of file cl_console.c.
Referenced by CL_Init().
void Con_Linefeed (qboolean skipnotify)
Line feed.
Definition at line 351 of file cl_console.c.
Referenced by CL_ConsolePrint().
void Con_PageDown (void)
Page down.
Definition at line 998 of file cl_console.c.
Referenced by Console_Key().
void Con_PageUp (void)
Page up.
Definition at line 990 of file cl_console.c.
Referenced by Console_Key().
void Con_RunConsole (void)
Scroll console up or down.
Definition at line 899 of file cl_console.c.
Referenced by CL_Frame().
void Con_ScrollBottom (void)
Scroll to bottom.
Definition at line 1033 of file cl_console.c.
Referenced by Con_Clear_f(), and Console_Key().
void Con_ScrollDown (int lines)
Scroll down.
Definition at line 1015 of file cl_console.c.
Referenced by Con_PageDown(), and Console_Key().
void Con_ScrollTop (void)
Scroll to top.
Definition at line 1024 of file cl_console.c.
Referenced by Console_Key().
void Con_ScrollUp (int lines)
Scroll up.
Definition at line 1006 of file cl_console.c.
Referenced by Con_PageUp(), and Console_Key().
void Con_Shutdown (void)
Free client console commands before shutdown.
Definition at line 341 of file cl_console.c.
Referenced by CL_Shutdown().
void Con_ToggleConsole_f (void)
Toggle console.
Definition at line 56 of file cl_console.c.
Referenced by CL_KeyEvent(), and Con_Init().
void IN_Help (void)
IN_Help.
Definition at line 675 of file cl_input.c.
Referenced by CL_InitInput().
int Key_GetCatcher (void)
Key_GetCatcher.
Returns
Definition at line 974 of file cl_ui.c.
Referenced by CL_CgameSystemCalls(), CL_ShutdownCGame(), CL_UISystemCalls(), IN_DeactivateMouse(), IN_Frame(), and IN_ProcessEvents().
char* Key_KeynumToString (int keynum)
Returns a string (either a single ascii char, a K_* name, or a 0x11 hex string) for the given keynum.
Parameters
[in] keynum
Returns
Definition at line 857 of file cl_keys.c.
Referenced by CL_KeyEvent(), IN_PrintKey(), Key_Bind_f(), Key_Bindlist_f(), Key_KeynumToStringBuf(), and Key_WriteBindings().
void Key_SetCatcher (int catcher)
Key_SetCatcher.
Parameters
[in] catcher
Definition at line 983 of file cl_ui.c.
Referenced by CL_CgameSystemCalls(), CL_ShutdownCGame(), and CL_UISystemCalls().
int Key_StringToKeynum (const char * str)
Returns a key number to be used to index keys[] by looking at the given string. Single ascii characters return themselves, while the K_* names are matched up.
0x11 will be interpreted as raw hex, which will allow new controlers to be configured even if they don't have defined names.
Parameters
[in] str
Returns
Definition at line 814 of file cl_keys.c.
Referenced by IN_IsConsoleKey(), Key_Bind_f(), and Key_Unbind_f().
void LAN_LoadCachedServers (void)
LAN_LoadCachedServers.
Definition at line 64 of file cl_ui.c.
Referenced by CL_UISystemCalls().
void LAN_SaveServersToFile (void)
Saves favorite servers into .dat file format.
Definition at line 121 of file cl_ui.c.
Referenced by CL_SaveFavServersToFile_f(), LAN_AddServer(), and LAN_RemoveServer().
void ROQ_Init (void)
ROQ_Init.
Definition at line 1079 of file cl_roq.c.
void ROQ_Reset (cinematic_t * cin)
ROQ_Reset.
Parameters
[in,out] cin
Definition at line 1022 of file cl_roq.c.
qboolean ROQ_StartRead (cinematic_t * cin)
ROQ_StartRead.
Parameters
[in,out] cin
Returns
Definition at line 1033 of file cl_roq.c.
void ROQ_StopVideo (cinematic_t * cin)
ROQ_StopVideo.
Parameters
[in,out] cin
Definition at line 1067 of file cl_roq.c.
void ROQ_UpdateCinematic (cinematic_t * cin, int time)
ROQ_UpdateCinematic.
Parameters
[in,out] cin
[in] time
Definition at line 931 of file cl_roq.c.
void SCR_AdjustFrom640 (float * x, float * y, float * w, float * h)
Adjusted for resolution and screen aspect ratio.
Parameters
[in,out] x
[in,out] y
[in,out] w
[in,out] h
Definition at line 53 of file cl_scrn.c.
Referenced by CIN_DrawCinematic(), Con_DrawSolidConsole(), SCR_DrawChar(), SCR_DrawPic(), and SCR_FillRect().
void SCR_DebugGraph (float value)
SCR_DebugGraph.
Parameters
value
Definition at line 281 of file cl_scrn.c.
void SCR_DrawChar (int x, int y, float w, float h, int ch, qboolean nativeResolution)
Chars are drawn at 640*480 virtual or native screen size.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] ch
[in] nativeResolution
Definition at line 155 of file cl_scrn.c.
Referenced by SCR_DrawStringExt().
void SCR_DrawCinematic (void)
SCR_DrawCinematic.
Definition at line 663 of file cl_cinematic.c.
Referenced by SCR_DrawScreenField().
void SCR_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
Coordinates are 640*480 virtual values.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] hShader
Definition at line 113 of file cl_scrn.c.
Referenced by Con_DrawSolidConsole().
void SCR_DrawStringExt (int x, int y, float w, float h, const char * string, float * setColor, qboolean forceColor, qboolean noColorEscape, qboolean dropShadow, qboolean nativeResolution)
Draws a multi-colored string with a drop shadow, optionally forcing to a fixed color.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] string
[in] setColor
[in] forceColor
[in] noColorEscape
[in] dropShadow
[in] nativeResolution
Definition at line 199 of file cl_scrn.c.
void SCR_FillRect (float x, float y, float width, float height, const float * color)
Coordinates are 640*480 virtual values.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] color
Definition at line 95 of file cl_scrn.c.
Referenced by Con_DrawScrollbar(), and Con_DrawSolidConsole().
void SCR_Init (void)
SCR_Init.
Definition at line 322 of file cl_scrn.c.
Referenced by CL_Init().
void SCR_RunCinematic (void)
SCR_RunCinematic.
Definition at line 652 of file cl_cinematic.c.
Referenced by CL_Frame().
void SCR_StopCinematic (void)
SCR_StopCinematic.
Definition at line 640 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic_f(), CL_Disconnect(), and CL_Disconnect_f().
void SCR_UpdateScreen (void)
This is called every frame, and can also be called explicitly to flush text to the screen.
Definition at line 423 of file cl_scrn.c.
Referenced by CL_CgameSystemCalls(), CL_Frame(), CL_Init(), CL_MapLoading(), CL_UISystemCalls(), and Console_Key().
Variable Documentation
vm_t* cgvm
interface to cgame dll or vm
Definition at line 119 of file cl_main.c.
Referenced by CL_CGameBinaryMessageReceived(), CL_CGameCheckKeyExec(), CL_CGameRendering(), CL_CharEvent(), CL_GameCommand(), CL_InitCGame(), CL_KeyEvent(), CL_MouseEvent(), and CL_ShutdownCGame().
clientActive_t cl
Definition at line 116 of file cl_main.c.
Referenced by __declspec(), CalculateRanks(), CG_AddLightstyle(), CG_EntityEffects(), CheckIntermissionExit(), CL_AdjustAngles(), CL_AdjustTimeDelta(), CL_CGameRendering(), CL_ConfigstringModified(), CL_CreateCmd(), CL_CreateNewCommands(), CL_DeltaEntity(), CL_DemoFastForward(), CL_DemoRun(), CL_DemoSeekMs(), CL_FastForward_f(), CL_FinishMove(), CL_FirstSnapshot(), CL_GetCurrentCmdNumber(), CL_GetCurrentSnapshotNumber(), CL_GetGameState(), CL_GetServerCommand(), CL_GetSnapshot(), CL_GetUserCmd(), CL_InitCGame(), CL_JoystickEvent(), CL_JoystickMove(), CL_KeyMove(), CL_MouseEvent(), CL_MouseMove(), CL_ParseBinaryMessage(), CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_ParseGamestate(), CL_ParsePacketEntities(), CL_ParseSnapshot(), CL_PauseDemo_f(), CL_PeekSnapshot(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_Record(), CL_Rewind_f(), CL_RewindDemo(), CL_SeekNext_f(), CL_SeekPrev_f(), CL_SetCGameTime(), CL_SetClientLerpOrigin(), CL_SetUserCmdValue(), CL_SystemInfoChanged(), CL_UpdateLevelHunkUsage(), CL_WritePacket(), ClientForString(), ClientNumberFromString(), Cmd_IntermissionPlayerTime_f(), Cmd_UnIgnore_f(), Cmd_Vote_f(), Com_Frame(), Con_DrawNotify(), Do_Activate_f(), ExitLevel(), G_BuildEndgameStats(), G_checkReady(), G_deleteStats(), G_GetPlayerByName(), G_GetPlayerByNum(), G_LandmineSnapshotCallback(), G_LogExit(), G_matchInfoDump(), G_MatchOnePlayer(), G_parseStats(), G_players_cmd(), G_PlaySound_Cmd(), G_printMatchInfo(), G_refAllReady_cmd(), G_Referee_v(), G_RemoveAllShoutcasters(), G_removeSpecInvite(), G_SendScore_Add(), G_shuffleTeamsXP(), G_swapTeams(), G_teamready_cmd(), G_Unreferee_v(), G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), GetClientState(), GetConfigString(), isEntVisible(), limbo(), Pickup_Team(), SpectatorClientEndFrame(), SV_BotAllocateClient(), SV_BotFreeClient(), SV_BotGetConsoleMessage(), SV_CalcPings(), SV_CheckClientUserinfoTimer(), SV_CheckPaused(), SV_CheckTimeouts(), SV_DirectConnect(), SV_DumpUser_f(), SV_FinalCommand(), SV_GetPlayerByName(), SV_PacketEvent(), SV_SendDownloadMessages(), SV_SendQueuedMessages(), SV_Status_f(), SVC_Status(), Svcmd_ForceTeam_f(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), and WolfFindMedic().
cvar_t* cl_activatelean
Definition at line 89 of file cl_main.c.
Referenced by CL_KeyMove().
cvar_t* cl_activeAction
Definition at line 87 of file cl_main.c.
Referenced by CL_FirstSnapshot().
cvar_t* cl_allowDownload
Definition at line 93 of file cl_main.c.
Referenced by CL_ParseDownload(), and Com_InitDownloads().
cvar_t* cl_anglespeedkey
Definition at line 687 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_autorecord
Definition at line 91 of file cl_main.c.
Referenced by CL_ParseSnapshot().
cvar_t* cl_avidemo
Definition at line 70 of file cl_main.c.
Referenced by CL_OpenAVIForWriting(), and S_GetSoundtime().
cvar_t* cl_aviMotionJpeg
Definition at line 73 of file cl_main.c.
Referenced by CL_OpenAVIForWriting().
cvar_t* cl_bypassMouseInput
Definition at line 689 of file cl_input.c.
int cl_connectedToCheatServer
Definition at line 588 of file cl_parse.c.
Referenced by CL_InitCGame(), and CL_SystemInfoChanged().
int cl_connectedToPureServer
Definition at line 587 of file cl_parse.c.
cvar_t* cl_consoleKeys
Definition at line 114 of file cl_main.c.
Referenced by IN_IsConsoleKey().
cvar_t* cl_conXOffset
Definition at line 95 of file cl_main.c.
Referenced by Con_DrawNotify().
cvar_t* cl_debugMove
Definition at line 51 of file cl_main.c.
Referenced by CL_CreateCmd(), CL_InitInput(), and SCR_DrawScreenField().
cvar_t* cl_defaultProfile
Definition at line 101 of file cl_main.c.
cvar_t* cl_doubletapdelay
Definition at line 690 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_freelook
Definition at line 75 of file cl_main.c.
Referenced by CL_MouseMove().
cvar_t* cl_freezeDemo
Definition at line 63 of file cl_main.c.
cvar_t* cl_maxpackets
Definition at line 59 of file cl_main.c.
Referenced by CL_ReadyToSendPacket().
cvar_t* cl_missionStats
Definition at line 98 of file cl_main.c.
cvar_t* cl_mouseAccel
Definition at line 78 of file cl_main.c.
Referenced by CL_MouseMove().
cvar_t* cl_nodelta
Definition at line 50 of file cl_main.c.
Referenced by CL_InitInput(), and CL_WritePacket().
cvar_t* cl_noprint
Definition at line 53 of file cl_main.c.
Referenced by CL_ConsolePrint().
cvar_t* cl_packetdup
Definition at line 60 of file cl_main.c.
Referenced by CL_WritePacket().
cvar_t* cl_pitchspeed
Definition at line 685 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_profile
Definition at line 100 of file cl_main.c.
cvar_t* cl_recoilPitch
Definition at line 688 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_run
Definition at line 686 of file cl_input.c.
Referenced by CL_Init().
cvar_t* cl_sensitivity
Definition at line 76 of file cl_main.c.
Referenced by CL_MouseMove().
cvar_t* cl_showMouseRate
Definition at line 79 of file cl_main.c.
Referenced by CL_MouseMove().
cvar_t* cl_shownet
Definition at line 65 of file cl_main.c.
cvar_t* cl_shownuments
Definition at line 66 of file cl_main.c.
Referenced by CL_ParsePacketEntities().
cvar_t* cl_showSend
Definition at line 67 of file cl_main.c.
Referenced by CL_SendCmd(), and CL_WritePacket().
cvar_t* cl_showServerCommands
Definition at line 68 of file cl_main.c.
Referenced by CL_GetServerCommand().
cvar_t* cl_showTimeDelta
Definition at line 62 of file cl_main.c.
Referenced by CL_AdjustTimeDelta().
cvar_t* cl_timedemo
Definition at line 69 of file cl_main.c.
Referenced by CL_DemoCompleted(), and CL_DemoRun().
cvar_t* cl_timegraph
Definition at line 41 of file cl_scrn.c.
Referenced by CL_Frame().
cvar_t* cl_timeNudge
Definition at line 61 of file cl_main.c.
Referenced by CL_SetCGameTime().
cvar_t* cl_yawspeed
Definition at line 684 of file cl_input.c.
Referenced by CL_Init().
clientConnection_t clc
Definition at line 117 of file cl_main.c.
Referenced by CL_AdjustTimeDelta(), CL_BinaryMessageStatus(), CL_CGameRendering(), CL_CgameSystemCalls(), CL_DeltaEntity(), CL_DemoCleanUp(), CL_DemoCompleted(), CL_DemoFastForward(), CL_DemoRun(), CL_DemoSeekMs(), CL_FastForward_f(), CL_FirstSnapshot(), CL_GetServerCommand(), CL_InitCGame(), CL_KeyEvent(), CL_Netchan_Decode(), CL_Netchan_Encode(), CL_ParseCommandString(), CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PauseDemo_f(), CL_PeekSnapshot(), CL_PlayDemo_f(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_Record(), CL_Record_f(), CL_Rewind_f(), CL_RewindDemo(), CL_Seek_f(), CL_SeekEnd_f(), CL_SeekServerTime_f(), CL_SendBinaryMessage(), CL_SetCGameTime(), CL_StopRecord_f(), CL_SystemInfoChanged(), CL_WriteBinaryMessage(), CL_WriteDemoMessage(), CL_WritePacket(), Com_CheckUpdateStarted(), Com_DownloadsComplete(), Com_GetAutoUpdate(), Com_InitUpdateDownloads(), Com_RunUpdateBinary(), CON_Input(), GetClientState(), IN_Help(), and SCR_DrawDemoRecording().
clientStatic_t cls
Definition at line 118 of file cl_main.c.
Referenced by BG_GetCharacter(), CG_CharacterForClientinfo(), CG_CharacterForPlayerstate(), CG_Class_f(), CG_PlayerClassForClientinfo(), CG_RegisterPlayerClasses(), CIN_CloseAllVideos(), CIN_PlayCinematic(), CIN_PlayCinematic_f(), CIN_RunCinematic(), CIN_StopCinematic(), CL_AdjustAngles(), CL_AdjustTimeDelta(), CL_CgameSystemCalls(), CL_CharEvent(), CL_CmdButtons(), CL_ConsolePrint(), CL_CreateNewCommands(), CL_DemoFastForward(), CL_DemoRun(), CL_FirstSnapshot(), CL_GetGlconfig(), CL_InitCGame(), CL_InitUI(), CL_JoystickMove(), CL_KeyEvent(), CL_KeyMove(), CL_MouseEvent(), CL_OpenAVIForWriting(), CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_ParseDownload(), CL_ParseSnapshot(), CL_PeekSnapshot(), CL_PlayDemo_f(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_Record_f(), CL_RewindDemo(), CL_SendCmd(), CL_SetCGameTime(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_SystemInfoChanged(), CL_WritePacket(), Cmd_Echo_f(), Com_BeginDownload(), Com_Download_f(), Com_GetAutoUpdate(), Com_InitDownloads(), Con_CheckResize(), Con_Close(), Con_DrawClock(), Con_DrawConsole(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_DrawVersion(), Con_Linefeed(), Con_RunConsole(), Con_ToggleConsole_f(), Console_Key(), Field_VariableSizeDraw(), G_RegisterPlayerClasses(), G_Voice(), GetClientState(), GLimp_SetGamma(), IN_ActivateMouse(), IN_DeactivateMouse(), IN_Frame(), IN_Help(), IN_WindowResize(), Key_GetCatcher(), Key_SetCatcher(), LAN_AddServer(), LAN_GetServerAddressString(), LAN_GetServerCount(), LAN_GetServerInfo(), LAN_GetServerPing(), LAN_GetServerPtr(), LAN_LoadCachedServers(), LAN_MarkServerVisible(), LAN_RemoveServer(), LAN_ResetPings(), LAN_SaveServersToFile(), LAN_ServerIsInFavoriteList(), LAN_ServerIsVisible(), S_Base_AddLoopingSound(), SCR_AdjustFrom640(), SCR_DrawCinematic(), SCR_DrawDebugGraph(), SCR_DrawScreenField(), SCR_FillRect(), SCR_RunCinematic(), SCR_StopCinematic(), SRC_DrawSingleChar(), and UI_GameCommand().
console_t con
Definition at line 45 of file cl_console.c.
Referenced by CL_KeyEvent(), CM_FloodArea_r(), and Console_Key().
demoPlayInfo_t dpi
Definition at line 100 of file cl_demo.c.
Referenced by CL_InitCGame(), and R_LoadScalableFont().
int g_console_field_width
Definition at line 43 of file cl_console.c.
Referenced by CL_InitRenderer(), Con_Init(), Con_ToggleConsole_f(), and Console_Key().
cvar_t* m_filter
Definition at line 85 of file cl_main.c.
Referenced by CG_MouseEvent(), and CL_MouseMove().
cvar_t* m_forward
Definition at line 83 of file cl_main.c.
Referenced by CL_MouseMove().
cvar_t* m_pitch
Definition at line 81 of file cl_main.c.
Referenced by CG_MouseEvent(), and CL_MouseMove().
cvar_t* m_side
Definition at line 84 of file cl_main.c.
Referenced by CL_MouseMove().
cvar_t* m_yaw
Definition at line 82 of file cl_main.c.
Referenced by CG_MouseEvent(), and CL_MouseMove().
refexport_t re
interface to refresh .dll
Definition at line 124 of file cl_main.c.
Referenced by CG_AddBloodTrails(), CG_AddConstRGB(), CG_AddDebris(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddLineToScene(), CG_AddMoveScaleFade(), CG_AddScaleFade(), CG_AddSparks(), CG_AddSpriteExplosion(), CG_BubbleTrail(), CG_Debris(), CG_Effect(), CG_Explodef(), CG_GibPlayer(), CG_LaunchGib(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_PanzerFaustEjectBrass(), CG_RailTrail2(), CG_RenderLocations(), CG_RenderScriptSpeakers(), CG_RubbleFx(), CG_Shard(), CG_ShardJunk(), CG_SmokePuff(), CG_SparklerSparks(), CG_WaterRipple(), CIN_DrawCinematic(), CIN_UploadCinematic(), CL_CgameSystemCalls(), CL_InitCGame(), CL_TakeVideoFrame(), CL_UISystemCalls(), Con_DrawClock(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_DrawVersion(), GetRefAPI(), GLimp_Init(), GLimp_SetMode(), SCR_DrawDebugGraph(), SCR_DrawPic(), SCR_DrawScreenField(), SCR_DrawStringExt(), SCR_FillRect(), SCR_UpdateScreen(), and SRC_DrawSingleChar().
vm_t* uivm
interface to ui dll or vm
Definition at line 45 of file cl_ui.c.
Referenced by CIN_PlayCinematic(), CL_CgameSystemCalls(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_KeyEvent(), CL_MouseEvent(), Com_UpdateInfoPacket(), IN_Help(), and SCR_DrawScreenField().