ET: Legacy: src/qcommon/cm_polylib.c File Reference
cm_polylib.c File Reference
Used only for visualization tools in cm_ debug functions.
#include "cm_local.h"
Macros
#define MAX_HULL_POINTS 128
Functions
void pw (winding_t *w)
pw
winding_t * AllocWinding (int points)
AllocWinding.
void FreeWinding (winding_t *w)
FreeWinding.
void RemoveColinearPoints (winding_t *w)
RemoveColinearPoints.
void WindingPlane (winding_t *w, vec3_t normal, vec_t *dist)
WindingPlane.
vec_t WindingArea (winding_t *w)
WindingArea.
void WindingBounds (winding_t *w, vec3_t mins, vec3_t maxs)
WindingBounds.
void WindingCenter (winding_t *w, vec3_t center)
WindingCenter.
winding_t * BaseWindingForPlane (vec3_t normal, vec_t dist)
BaseWindingForPlane.
winding_t * CopyWinding (winding_t *w)
CopyWinding.
winding_t * ReverseWinding (winding_t *w)
ReverseWinding.
void ClipWindingEpsilon (winding_t *in, vec3_t normal, vec_t dist, vec_t epsilon, winding_t **front, winding_t **back)
ClipWindingEpsilon.
void ChopWindingInPlace (winding_t **w, vec3_t normal, vec_t dist, vec_t epsilon)
ChopWindingInPlace.
winding_t * ChopWinding (winding_t *in, vec3_t normal, vec_t dist)
ChopWinding.
void CheckWinding (winding_t *w)
CheckWinding.
int WindingOnPlaneSide (winding_t *w, vec3_t normal, vec_t dist)
WindingOnPlaneSide.
void AddWindingToConvexHull (winding_t *w, winding_t **hull, vec3_t normal)
Both w and *hull are on the same plane.
Variables
int c_active_windings
int c_peak_windings
int c_winding_allocs
int c_winding_points
int c_removed
Detailed Description
Used only for visualization tools in cm_ debug functions.
Definition in file cm_polylib.c.
Macro Definition Documentation
#define MAX_HULL_POINTS 128
Definition at line 749 of file cm_polylib.c.
Referenced by AddWindingToConvexHull().
Function Documentation
void AddWindingToConvexHull (winding_t * w, winding_t ** hull, vec3_t normal)
Both w and *hull are on the same plane.
Parameters
[in,out] w
[in,out] hull
[in] normal
Note
Unused
Definition at line 759 of file cm_polylib.c.
winding_t* AllocWinding (int points)
AllocWinding.
Parameters
[in] points
Returns
Definition at line 64 of file cm_polylib.c.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), ChopWindingInPlace(), ClipWindingEpsilon(), CopyWinding(), and ReverseWinding().
winding_t* BaseWindingForPlane (vec3_t normal, vec_t dist)
BaseWindingForPlane.
Parameters
[in] normal
[in] dist
Returns
Definition at line 238 of file cm_polylib.c.
Referenced by CM_AddFacetBevels(), CM_DrawDebugSurface(), and CM_ValidateFacet().
void CheckWinding (winding_t * w)
CheckWinding.
Parameters
[in] w
Note
Unused
Definition at line 626 of file cm_polylib.c.
winding_t* ChopWinding (winding_t * in, vec3_t normal, vec_t dist)
ChopWinding.
Parameters
[in] in
[in] normal
[in] dist
Returns
The fragment of in that is on the front side of the cliping plane. The original is freed.
Note
Unused
Definition at line 606 of file cm_polylib.c.
void ChopWindingInPlace (winding_t ** w, vec3_t normal, vec_t dist, vec_t epsilon)
ChopWindingInPlace.
Parameters
[in,out] w
[in] normal
[in] dist
[in] epsilon
Definition at line 481 of file cm_polylib.c.
Referenced by CM_AddFacetBevels(), CM_DrawDebugSurface(), and CM_ValidateFacet().
void ClipWindingEpsilon (winding_t * in, vec3_t normal, vec_t dist, vec_t epsilon, winding_t ** front, winding_t ** back)
ClipWindingEpsilon.
Parameters
[in] in
[in] normal
[in] dist
[in] epsilon
[out] front
[out] back
Note
Unused (called by ChopWinding() which is unused)
Definition at line 353 of file cm_polylib.c.
Referenced by ChopWinding().
winding_t* CopyWinding (winding_t * w)
CopyWinding.
Parameters
[in] w
Returns
Definition at line 309 of file cm_polylib.c.
Referenced by AddWindingToConvexHull(), ClipWindingEpsilon(), and CM_AddFacetBevels().
void FreeWinding (winding_t * w)
FreeWinding.
Parameters
[in,out] w
Definition at line 87 of file cm_polylib.c.
Referenced by AddWindingToConvexHull(), ChopWinding(), ChopWindingInPlace(), CM_AddFacetBevels(), CM_DrawDebugSurface(), and CM_ValidateFacet().
void pw (winding_t * w)
pw
Parameters
[in] w
Definition at line 49 of file cm_polylib.c.
Referenced by CG_DrawMortarMarker(), and CG_DrawSpawnPointInfo().
void RemoveColinearPoints (winding_t * w)
RemoveColinearPoints.
Parameters
[in,out] w
Note
Unused
Definition at line 108 of file cm_polylib.c.
winding_t* ReverseWinding (winding_t * w)
ReverseWinding.
Parameters
[in] w
Returns
Note
Unused
Definition at line 327 of file cm_polylib.c.
vec_t WindingArea (winding_t * w)
WindingArea.
Parameters
[in] w
Returns
Definition at line 162 of file cm_polylib.c.
Referenced by CheckWinding().
void WindingBounds (winding_t * w, vec3_t mins, vec3_t maxs)
WindingBounds.
Parameters
[in] w
[in,out] mins
[in,out] maxs
Definition at line 185 of file cm_polylib.c.
Referenced by CM_AddFacetBevels(), and CM_ValidateFacet().
void WindingCenter (winding_t * w, vec3_t center)
WindingCenter.
Parameters
[in] w
[in,out] center
Note
Unused
Definition at line 217 of file cm_polylib.c.
int WindingOnPlaneSide (winding_t * w, vec3_t normal, vec_t dist)
WindingOnPlaneSide.
Parameters
[in] w
[in] normal
[in] dist
Returns
Note
Unused
Definition at line 706 of file cm_polylib.c.
void WindingPlane (winding_t * w, vec3_t normal, vec_t * dist)
WindingPlane.
Parameters
w
normal
dist
Definition at line 146 of file cm_polylib.c.
Referenced by CheckWinding().
Variable Documentation
int c_active_windings
Definition at line 40 of file cm_polylib.c.
Referenced by AllocWinding(), and FreeWinding().
int c_peak_windings
Definition at line 41 of file cm_polylib.c.
Referenced by AllocWinding().
int c_removed
Definition at line 100 of file cm_polylib.c.
Referenced by RemoveColinearPoints().
int c_winding_allocs
Definition at line 42 of file cm_polylib.c.
Referenced by AllocWinding().
int c_winding_points
Definition at line 43 of file cm_polylib.c.
Referenced by AllocWinding().