ET: Legacy: src/qcommon/cm_public.h File Reference
cm_public.h File Reference
#include "qfiles.h"
#include "../renderercommon/tr_types.h"
Functions
void CM_LoadMap (const char *name, qboolean clientload, unsigned int *checksum)
Loads in the map and all submodels.
void CM_ClearMap (void)
CM_ClearMap.
clipHandle_t CM_InlineModel (int index)
CM_InlineModel.
clipHandle_t CM_TempBoxModel (const vec3_t mins, const vec3_t maxs, qboolean capsule)
To keep everything totally uniform, bounding boxes are turned into small BSP trees instead of being compared directly. Capsules are handled differently though.
void CM_SetTempBoxModelContents (int contents)
CM_SetTempBoxModelContents.
void CM_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
CM_ModelBounds.
int CM_NumClusters (void)
CM_NumClusters.
int CM_NumInlineModels (void)
CM_NumInlineModels.
char * CM_EntityString (void)
CM_EntityString.
int CM_PointContents (const vec3_t p, clipHandle_t model)
CM_PointContents.
int CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
Handles offseting and rotation of the end points for moving and rotating entities.
void CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, qboolean capsule)
CM_BoxTrace.
void CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles, qboolean capsule)
Handles offseting and rotation of the end points for moving and rotating entities.
byte * CM_ClusterPVS (int cluster)
CM_ClusterPVS.
int CM_PointLeafnum (const vec3_t p)
CM_PointLeafnum.
int CM_BoxLeafnums (const vec3_t mins, const vec3_t maxs, int *list, int listsize, int *lastLeaf)
CM_BoxLeafnums.
int CM_LeafCluster (int leafnum)
CM_LeafCluster.
int CM_LeafArea (int leafnum)
CM_LeafArea.
void CM_AdjustAreaPortalState (int area1, int area2, qboolean open)
CM_AdjustAreaPortalState.
qboolean CM_AreasConnected (int area1, int area2)
CM_AreasConnected.
int CM_WriteAreaBits (byte *buffer, int area)
Writes a bit vector of all the areas that are in the same flood as the area parameter.
void CM_DrawDebugSurface (void(*drawPoly)(int color, int numPoints, float *points))
Called from the renderer.
Function Documentation
void CM_AdjustAreaPortalState (int area1, int area2, qboolean open)
CM_AdjustAreaPortalState.
Parameters
[in] area1
[in] area2
[in] open
Definition at line 461 of file cm_test.c.
Referenced by SV_AdjustAreaPortalState().
qboolean CM_AreasConnected (int area1, int area2)
CM_AreasConnected.
Parameters
[in] area1
[in] area2
Returns
Definition at line 497 of file cm_test.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_GameSystemCalls(), and SV_inPVS().
int CM_BoxLeafnums (const vec3_t mins, const vec3_t maxs, int * list, int listsize, int * lastLeaf)
CM_BoxLeafnums.
Parameters
[in] mins
[in] maxs
[in] list
[in] listsize
[out] lastLeaf
Returns
Definition at line 225 of file cm_test.c.
Referenced by SV_LinkEntity().
void CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, qboolean capsule)
CM_BoxTrace.
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] capsule
Definition at line 1671 of file cm_trace.c.
Referenced by CL_CgameSystemCalls(), isEntVisible(), and SV_Trace().
void CM_ClearMap (void)
CM_ClearMap.
Definition at line 712 of file cm_load.c.
Referenced by CL_FlushMemory(), and SV_SpawnServer().
byte* CM_ClusterPVS (int cluster)
CM_ClusterPVS.
===============================================================================
PVS
Parameters
[in] cluster
Returns
Definition at line 382 of file cm_test.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_inPVSIgnorePortals().
void CM_DrawDebugSurface (void(*)(int color, int numPoints, float *points) drawPoly)
Called from the renderer.
Todo:
: remove in sv_bot.c
Todo:
: remove in sv_bot.c
Definition at line 2055 of file cm_patch.c.
Referenced by CL_InitRef().
char* CM_EntityString (void)
CM_EntityString.
Returns
Definition at line 785 of file cm_load.c.
Referenced by BotImport_BSPEntityData(), and SV_InitGameVM().
clipHandle_t CM_InlineModel (int index)
CM_InlineModel.
Parameters
[in] index
Returns
Definition at line 753 of file cm_load.c.
Referenced by BotImport_BSPModelMinsMaxsOrigin(), CL_CgameSystemCalls(), SV_ClearWorld(), SV_ClipHandleForEntity(), and SV_SetBrushModel().
int CM_LeafArea (int leafnum)
CM_LeafArea.
Parameters
[in] leafnum
Returns
Definition at line 810 of file cm_load.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_LinkEntity().
int CM_LeafCluster (int leafnum)
CM_LeafCluster.
Parameters
[in] leafnum
Returns
Definition at line 795 of file cm_load.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), SV_inPVSIgnorePortals(), and SV_LinkEntity().
void CM_LoadMap (const char * name, qboolean clientload, unsigned int * checksum)
Loads in the map and all submodels.
Parameters
[in] name
[in] clientload
[out] checksum
Definition at line 612 of file cm_load.c.
Referenced by CL_CM_LoadMap(), and SV_SpawnServer().
void CM_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
CM_ModelBounds.
Parameters
[in] model
[out] mins
[out] maxs
Definition at line 925 of file cm_load.c.
Referenced by BotImport_BSPModelMinsMaxsOrigin(), CM_TestInLeaf(), CM_TraceThroughLeaf(), SV_ClearWorld(), and SV_SetBrushModel().
int CM_NumClusters (void)
CM_NumClusters.
Returns
Definition at line 767 of file cm_load.c.
int CM_NumInlineModels (void)
CM_NumInlineModels.
Returns
Definition at line 776 of file cm_load.c.
Referenced by CL_CgameSystemCalls().
int CM_PointContents (const vec3_t p, clipHandle_t model)
CM_PointContents.
Parameters
[in] p
[in] model
Returns
Todo:
test for Cash
Definition at line 284 of file cm_test.c.
Referenced by CL_CgameSystemCalls(), CL_InitRef(), CM_TransformedPointContents(), and SV_PointContents().
int CM_PointLeafnum (const vec3_t p)
CM_PointLeafnum.
Parameters
[in] p
Returns
Definition at line 82 of file cm_test.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), SV_inPVSIgnorePortals(), and SV_LinkEntity().
void CM_SetTempBoxModelContents (int contents)
CM_SetTempBoxModelContents.
Parameters
[in] contents
Definition at line 914 of file cm_load.c.
Referenced by SV_ClipMoveToEntities().
clipHandle_t CM_TempBoxModel (const vec3_t mins, const vec3_t maxs, qboolean capsule)
To keep everything totally uniform, bounding boxes are turned into small BSP trees instead of being compared directly. Capsules are handled differently though.
Parameters
[in] mins
[in] maxs
[in] capsule
Returns
Definition at line 881 of file cm_load.c.
Referenced by CL_CgameSystemCalls(), CM_TestInLeaf(), CM_TraceThroughLeaf(), and SV_ClipHandleForEntity().
void CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles, qboolean capsule)
Handles offseting and rotation of the end points for moving and rotating entities.
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] origin
[in] angles
[in] capsule
Definition at line 1692 of file cm_trace.c.
Referenced by CL_CgameSystemCalls(), SV_ClipMoveToEntities(), SV_ClipToEntity(), and SV_EntityContact().
int CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
Handles offseting and rotation of the end points for moving and rotating entities.
Parameters
[in] p
[in] model
[in] origin
[in] angles
Returns
Definition at line 347 of file cm_test.c.
Referenced by CL_CgameSystemCalls(), and SV_PointContents().
int CM_WriteAreaBits (byte * buffer, int area)
Writes a bit vector of all the areas that are in the same flood as the area parameter.
The bits are OR'd in, so you can CM_WriteAreaBits from multiple viewpoints and get the union of all visible areas.
This is used to cull non-visible entities from snapshots
Parameters
[out] buffer
[in] area
Returns
The number of bytes needed to hold all the bits.
Definition at line 535 of file cm_test.c.
Referenced by SV_AddEntitiesVisibleFromPoint().