ET: Legacy: src/qcommon/cm_trace.c File Reference
cm_trace.c File Reference
#include "cm_local.h"
#include "cm_patch.h"
Macros
#define ALWAYS_BBOX_VS_BBOX
Always use bbox vs. bbox collision and never capsule vs. bbox or vice versa.
#define MAX_POSITION_LEAFS 1024
Functions
void CM_ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vDir, vec3_t vProj)
Always use capsule vs. capsule collision and never capsule vs. bbox or vice versa.
void CM_TestBoxInBrush (traceWork_t *tw, cbrush_t *brush)
CM_TestBoxInBrush.
void CM_TestInLeaf (traceWork_t *tw, cLeaf_t *leaf)
CM_TestInLeaf.
void CM_PositionTest (traceWork_t *tw)
CM_PositionTest.
static void CM_TraceThroughPatch (traceWork_t *tw, cPatch_t *patch)
CM_TraceThroughPatch.
static void CM_CalcTraceBounds (traceWork_t *tw, qboolean expand)
CM_CalcTraceBounds.
static float CM_BoxDistanceFromPlane (vec3_t center, vec3_t extents, cplane_t *plane)
CM_BoxDistanceFromPlane.
static int CM_TraceThroughBounds (traceWork_t *tw, vec3_t mins, vec3_t maxs)
CM_TraceThroughBounds.
static void CM_TraceThroughBrush (traceWork_t *tw, cbrush_t *brush)
CM_TraceThroughBrush.
static void CM_TraceThroughLeaf (traceWork_t *tw, cLeaf_t *leaf)
CM_TraceThroughLeaf.
static void CM_TraceThroughTree (traceWork_t *tw, int num, float p1f, float p2f, vec3_t p1, vec3_t p2)
Traverse all the contacted leafs from the start to the end position.
static void CM_Trace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, const vec3_t origin, int brushmask, qboolean capsule, sphere_t *sphere)
CM_Trace.
void CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, qboolean capsule)
CM_BoxTrace.
void CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles, qboolean capsule)
Handles offseting and rotation of the end points for moving and rotating entities.
Macro Definition Documentation
#define ALWAYS_BBOX_VS_BBOX
Always use bbox vs. bbox collision and never capsule vs. bbox or vice versa.
Definition at line 39 of file cm_trace.c.
#define MAX_POSITION_LEAFS 1024
Definition at line 408 of file cm_trace.c.
Referenced by CM_PositionTest().
Function Documentation
static float CM_BoxDistanceFromPlane (vec3_t center, vec3_t extents, cplane_t * plane) static
CM_BoxDistanceFromPlane.
Parameters
[in] center
[in] extents
[in] plane
Returns
Definition at line 540 of file cm_trace.c.
Referenced by CM_TraceThroughBounds().
void CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, qboolean capsule)
CM_BoxTrace.
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] capsule
Definition at line 1671 of file cm_trace.c.
Referenced by CL_CgameSystemCalls(), isEntVisible(), and SV_Trace().
static void CM_CalcTraceBounds (traceWork_t * tw, qboolean expand) static
CM_CalcTraceBounds.
Parameters
[in,out] tw
[in] expand
Definition at line 485 of file cm_trace.c.
Referenced by CM_Trace(), and CM_TraceThroughLeaf().
void CM_PositionTest (traceWork_t * tw)
CM_PositionTest.
Parameters
[in,out] tw
Definition at line 414 of file cm_trace.c.
Referenced by CM_Trace().
void CM_ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vDir, vec3_t vProj)
Always use capsule vs. capsule collision and never capsule vs. bbox or vice versa.
===============================================================================
BASIC MATH
CM_ProjectPointOntoVector
Parameters
point
vStart
vDir
vProj
Definition at line 58 of file cm_trace.c.
void CM_TestBoxInBrush (traceWork_t * tw, cbrush_t * brush)
CM_TestBoxInBrush.
===============================================================================
POSITION TESTING
Parameters
[in] tw
[in] brush
Definition at line 139 of file cm_trace.c.
Referenced by CM_TestInLeaf().
void CM_TestInLeaf (traceWork_t * tw, cLeaf_t * leaf)
CM_TestInLeaf.
Parameters
[in,out] tw
[in] leaf
Definition at line 230 of file cm_trace.c.
Referenced by CM_PositionTest(), and CM_Trace().
static void CM_Trace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, const vec3_t origin, int brushmask, qboolean capsule, sphere_t * sphere) static
CM_Trace.
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] origin
[in] brushmask
[in] capsule
[in] sphere
Definition at line 1400 of file cm_trace.c.
Referenced by CM_BoxTrace(), and CM_TransformedBoxTrace().
static int CM_TraceThroughBounds (traceWork_t * tw, vec3_t mins, vec3_t maxs) static
CM_TraceThroughBounds.
Parameters
[in] tw
[in] mins
[in] maxs
Returns
Definition at line 567 of file cm_trace.c.
Referenced by CM_TraceThroughLeaf().
static void CM_TraceThroughBrush (traceWork_t * tw, cbrush_t * brush) static
CM_TraceThroughBrush.
Parameters
[in,out] tw
[in] brush
Definition at line 604 of file cm_trace.c.
Referenced by CM_TraceThroughLeaf().
static void CM_TraceThroughLeaf (traceWork_t * tw, cLeaf_t * leaf) static
CM_TraceThroughLeaf.
Parameters
[in] tw
[in] leaf
Definition at line 811 of file cm_trace.c.
Referenced by CM_Trace(), and CM_TraceThroughTree().
static void CM_TraceThroughPatch (traceWork_t * tw, cPatch_t * patch) static
CM_TraceThroughPatch.
===============================================================================
TRACING
Parameters
[in,out] tw
[in] patch
Definition at line 465 of file cm_trace.c.
Referenced by CM_TraceThroughLeaf().
static void CM_TraceThroughTree (traceWork_t * tw, int num, float p1f, float p2f, vec3_t p1, vec3_t p2) static
Traverse all the contacted leafs from the start to the end position.
If the trace is a point, they will be exactly in order, but for larger trace volumes it is possible to hit something in a later leaf with a smaller intercept fraction.
Parameters
[in] tw
[in] num
[in] p1f
[in] p2f
[in] p1
[in] p2
Definition at line 1252 of file cm_trace.c.
Referenced by CM_Trace().
void CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles, qboolean capsule)
Handles offseting and rotation of the end points for moving and rotating entities.
Parameters
[out] results
[in] start
[in] end
[in] mins
[in] maxs
[in] model
[in] brushmask
[in] origin
[in] angles
[in] capsule
Definition at line 1692 of file cm_trace.c.
Referenced by CL_CgameSystemCalls(), SV_ClipMoveToEntities(), SV_ClipToEntity(), and SV_EntityContact().