ET: Legacy: src/qcommon/cm_patch.c File Reference
cm_patch.c File Reference
#include "cm_local.h"
#include "cm_patch.h"
Macros
#define ADDBEVELS
#define POINT_EPSILON 0.1f
#define NORMAL_EPSILON 0.00015f
#define DIST_EPSILON 0.0235f
Typedefs
typedef void(* BotPolyFunc) (int color, int numPoints, float *points)
Enumerations
enum edgeName_t { EN_TOP, EN_RIGHT, EN_BOTTOM, EN_LEFT }
Functions
void CM_ClearLevelPatches (void)
CM_ClearLevelPatches.
static int CM_SignbitsForNormal (vec3_t normal)
CM_SignbitsForNormal.
static qboolean CM_PlaneFromPoints (vec4_t plane, vec3_t a, vec3_t b, vec3_t c)
CM_PlaneFromPoints.
static qboolean CM_NeedsSubdivision (vec3_t a, vec3_t b, vec3_t c)
CM_NeedsSubdivision.
static void CM_Subdivide (vec3_t a, vec3_t b, vec3_t c, vec3_t out1, vec3_t out2, vec3_t out3)
CM_Subdivide.
static void CM_TransposeGrid (cGrid_t *grid)
Swaps the rows and columns in place.
static void CM_SetGridWrapWidth (cGrid_t *grid)
If the left and right columns are exactly equal, set grid->wrapWidth qtrue.
static void CM_SubdivideGridColumns (cGrid_t *grid)
Adds columns as necessary to the grid until all the aproximating points are within SUBDIVIDE_DISTANCE from the true curve.
static qboolean CM_ComparePoints (float *a, float *b)
CM_ComparePoints.
static void CM_RemoveDegenerateColumns (cGrid_t *grid)
If there are any identical columns, remove them.
int CM_PlaneEqual (patchPlane_t *p, float plane[4], int *flipped)
CM_PlaneEqual.
void CM_SnapVector (vec3_t normal)
CM_SnapVector.
int CM_FindPlane2 (float plane[4], int *flipped)
CM_FindPlane2.
static int CM_FindPlane (float *p1, float *p2, float *p3)
CM_FindPlane.
static int CM_PointOnPlaneSide (float *p, int planeNum)
CM_PointOnPlaneSide.
static int CM_GridPlane (int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int tri)
CM_GridPlane.
static int CM_EdgePlaneNum (cGrid_t *grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int k)
CM_EdgePlaneNum.
static void CM_SetBorderInward (facet_t *facet, cGrid_t *grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int which)
CM_SetBorderInward.
static qboolean CM_ValidateFacet (facet_t *facet)
If the facet isn't bounded by its borders, we screwed up.
void CM_AddFacetBevels (facet_t *facet)
CM_AddFacetBevels.
static void CM_PatchCollideFromGrid (cGrid_t *grid, patchCollide_t *pf, qboolean addBevels)
CM_PatchCollideFromGrid.
struct patchCollide_s * CM_GeneratePatchCollide (int width, int height, vec3_t *points, qboolean addBevels)
Creates an internal structure that will be used to perform collision detection with a patch mesh. Points is packed as concatenated rows.
void CM_TracePointThroughPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
Special case for point traces because the patch collide "brushes" have no volume.
int CM_CheckFacetPlane (float *plane, vec3_t start, vec3_t end, float *enterFrac, float *leaveFrac, int *hit)
CM_CheckFacetPlane.
void CM_TraceThroughPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
CM_TraceThroughPatchCollide.
qboolean CM_PositionTestInPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
CM_PositionTestInPatchCollide.
void CM_DrawDebugSurface (void(*drawPoly)(int color, int numPoints, float *points))
Called from the renderer.
Variables
static const patchCollide_t * debugPatchCollide
static const facet_t * debugFacet
static qboolean debugBlock
static vec3_t debugBlockPoints [4]
static unsigned int numPlanes
static patchPlane_t planes [MAX_PATCH_PLANES]
static unsigned int numFacets
static facet_t facets [MAX_FACETS]
Macro Definition Documentation
#define ADDBEVELS
Definition at line 115 of file cm_patch.c.
#define DIST_EPSILON 0.0235f
Definition at line 492 of file cm_patch.c.
Referenced by CM_PlaneEqual().
#define NORMAL_EPSILON 0.00015f
Definition at line 491 of file cm_patch.c.
Referenced by CM_PlaneEqual(), and CM_SnapVector().
#define POINT_EPSILON 0.1f
Definition at line 412 of file cm_patch.c.
Referenced by CM_ComparePoints().
Typedef Documentation
typedef void(* BotPolyFunc) (int color, int numPoints, float *points)
Definition at line 2047 of file cm_patch.c.
Enumeration Type Documentation
enum edgeName_t
Enumerator
EN_TOP
EN_RIGHT
EN_BOTTOM
EN_LEFT
Definition at line 1188 of file cm_patch.c.
Function Documentation
void CM_AddFacetBevels (facet_t * facet)
CM_AddFacetBevels.
Parameters
[in,out] facet
Definition at line 962 of file cm_patch.c.
Referenced by CM_PatchCollideFromGrid().
int CM_CheckFacetPlane (float * plane, vec3_t start, vec3_t end, float * enterFrac, float * leaveFrac, int * hit)
CM_CheckFacetPlane.
Parameters
[in] plane
[in] start
[in] end
[in,out] enterFrac
[in,out] leaveFrac
[out] hit
Returns
Definition at line 1719 of file cm_patch.c.
Referenced by CM_TraceThroughPatchCollide().
void CM_ClearLevelPatches (void)
CM_ClearLevelPatches.
Definition at line 129 of file cm_patch.c.
Referenced by CM_ClearMap(), and CM_LoadMap().
static qboolean CM_ComparePoints (float * a, float * b) static
CM_ComparePoints.
Parameters
[in] a
[in] b
Returns
Definition at line 420 of file cm_patch.c.
Referenced by CM_RemoveDegenerateColumns().
void CM_DrawDebugSurface (void(*)(int color, int numPoints, float *points) drawPoly)
Called from the renderer.
Todo:
: remove in sv_bot.c
Todo:
: remove in sv_bot.c
Definition at line 2055 of file cm_patch.c.
Referenced by CL_InitRef().
static int CM_EdgePlaneNum (cGrid_t * grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int k) static
CM_EdgePlaneNum.
Parameters
[in] grid
[in] gridPlanes
[in] i
[in] j
[in] k
Returns
Definition at line 721 of file cm_patch.c.
Referenced by CM_PatchCollideFromGrid().
static int CM_FindPlane (float * p1, float * p2, float * p3) static
CM_FindPlane.
Parameters
[in] p1
[in] p2
[in] p3
Returns
Definition at line 598 of file cm_patch.c.
Referenced by CM_EdgePlaneNum(), and CM_PatchCollideFromGrid().
int CM_FindPlane2 (float plane[4], int * flipped)
CM_FindPlane2.
Parameters
[in] plane
[out] flipped
Returns
Definition at line 562 of file cm_patch.c.
Referenced by CM_AddFacetBevels().
struct patchCollide_s* CM_GeneratePatchCollide (int width, int height, vec3_t * points, qboolean addBevels)
Creates an internal structure that will be used to perform collision detection with a patch mesh. Points is packed as concatenated rows.
Parameters
[in] width
[in] height
[in,out] points
[in] addBevels
Returns
Definition at line 1412 of file cm_patch.c.
Referenced by CMod_LoadPatches().
static int CM_GridPlane (int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int tri) static
CM_GridPlane.
Parameters
[in] gridPlanes
[in] i
[in] j
[in] tri
Returns
Definition at line 693 of file cm_patch.c.
Referenced by CM_EdgePlaneNum().
static qboolean CM_NeedsSubdivision (vec3_t a, vec3_t b, vec3_t c) static
CM_NeedsSubdivision.
================================================================================
GRID SUBDIVISION
Parameters
a
b
c
Returns
true if the given quadratic curve is not flat enough for our collision detection purposes
Definition at line 193 of file cm_patch.c.
Referenced by CM_SubdivideGridColumns().
static void CM_PatchCollideFromGrid (cGrid_t * grid, patchCollide_t * pf, qboolean addBevels) static
CM_PatchCollideFromGrid.
Parameters
[in] grid
[out] pf
[in] addBevels
Definition at line 1202 of file cm_patch.c.
Referenced by CM_GeneratePatchCollide().
int CM_PlaneEqual (patchPlane_t * p, float plane[4], int * flipped)
CM_PlaneEqual.
Parameters
[in] p
[in] plane
[out] flipped
Returns
Definition at line 501 of file cm_patch.c.
Referenced by CM_AddFacetBevels(), and CM_FindPlane2().
static qboolean CM_PlaneFromPoints (vec4_t plane, vec3_t a, vec3_t b, vec3_t c) static
CM_PlaneFromPoints.
The normal will point out of the clock for clockwise ordered points
Parameters
[in,out] plane
[in] a
[in] b
[in] c
Returns
false if the triangle is degenrate.
Definition at line 163 of file cm_patch.c.
Referenced by CM_FindPlane().
static int CM_PointOnPlaneSide (float * p, int planeNum) static
CM_PointOnPlaneSide.
Parameters
[in] p
[in] planeNum
Returns
Definition at line 659 of file cm_patch.c.
Referenced by CM_SetBorderInward().
qboolean CM_PositionTestInPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
CM_PositionTestInPatchCollide.
Parameters
[in] tw
[in] pc
Returns
Definition at line 1940 of file cm_patch.c.
Referenced by CM_TestInLeaf().
static void CM_RemoveDegenerateColumns (cGrid_t * grid) static
If there are any identical columns, remove them.
Parameters
[in,out] grid
Definition at line 445 of file cm_patch.c.
Referenced by CM_GeneratePatchCollide().
static void CM_SetBorderInward (facet_t * facet, cGrid_t * grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int which) static
CM_SetBorderInward.
Parameters
[in,out] facet
[in] grid
gridPlanes - unused
[in] i
[in] j
[in] which
Definition at line 811 of file cm_patch.c.
Referenced by CM_PatchCollideFromGrid().
static void CM_SetGridWrapWidth (cGrid_t * grid) static
If the left and right columns are exactly equal, set grid->wrapWidth qtrue.
Parameters
[in,out] grid
Definition at line 308 of file cm_patch.c.
Referenced by CM_GeneratePatchCollide().
static int CM_SignbitsForNormal (vec3_t normal) static
CM_SignbitsForNormal.
Parameters
[in] normal
Returns
Definition at line 140 of file cm_patch.c.
Referenced by CM_FindPlane(), and CM_FindPlane2().
void CM_SnapVector (vec3_t normal)
CM_SnapVector.
Parameters
[in,out] normal
Definition at line 535 of file cm_patch.c.
Referenced by CM_AddFacetBevels().
static void CM_Subdivide (vec3_t a, vec3_t b, vec3_t c, vec3_t out1, vec3_t out2, vec3_t out3) static
CM_Subdivide.
The subdivided sequence will be: a, out1, out2, out3, c
Parameters
[in] a control point
[in] b control point
[in] c control point
[in,out] out1
[out] out2
[in,out] out3
Definition at line 230 of file cm_patch.c.
Referenced by CM_SubdivideGridColumns().
static void CM_SubdivideGridColumns (cGrid_t * grid) static
Adds columns as necessary to the grid until all the aproximating points are within SUBDIVIDE_DISTANCE from the true curve.
Parameters
[in,out] grid
Definition at line 345 of file cm_patch.c.
Referenced by CM_GeneratePatchCollide().
void CM_TracePointThroughPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
Special case for point traces because the patch collide "brushes" have no volume.
Parameters
[in,out] tw
[in] pc
Todo:
: until I get player sized clipping working right
Definition at line 1596 of file cm_patch.c.
Referenced by CM_TraceThroughPatchCollide().
void CM_TraceThroughPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
CM_TraceThroughPatchCollide.
Parameters
[in,out] tw
[in] pc
Definition at line 1777 of file cm_patch.c.
Referenced by CM_TraceThroughPatch().
static void CM_TransposeGrid (cGrid_t * grid) static
Swaps the rows and columns in place.
Parameters
[in,out] grid
Definition at line 246 of file cm_patch.c.
Referenced by CM_GeneratePatchCollide().
static qboolean CM_ValidateFacet (facet_t * facet) static
If the facet isn't bounded by its borders, we screwed up.
Parameters
facet
Returns
Definition at line 901 of file cm_patch.c.
Referenced by CM_PatchCollideFromGrid().
Variable Documentation
qboolean debugBlock static
Definition at line 123 of file cm_patch.c.
Referenced by CM_SetBorderInward().
vec3_t debugBlockPoints[4] static
Definition at line 124 of file cm_patch.c.
Referenced by CM_DrawDebugSurface(), and CM_SetBorderInward().
const facet_t* debugFacet static
Definition at line 122 of file cm_patch.c.
const patchCollide_t* debugPatchCollide static
Definition at line 121 of file cm_patch.c.
Referenced by CM_DrawDebugSurface().
facet_t facets[MAX_FACETS] static
Definition at line 489 of file cm_patch.c.
unsigned int numFacets static
Definition at line 488 of file cm_patch.c.
Referenced by CM_DrawDebugSurface(), and CM_PatchCollideFromGrid().
unsigned int numPlanes static
Definition at line 485 of file cm_patch.c.
Referenced by CM_FindPlane(), CM_FindPlane2(), CM_PatchCollideFromGrid(), R_AddMarkFragments(), and R_MarkFragments().
patchPlane_t planes[MAX_PATCH_PLANES] static
Definition at line 486 of file cm_patch.c.
Referenced by CM_PositionTestInPatchCollide(), CM_TracePointThroughPatchCollide(), CM_TraceThroughPatchCollide(), PM_SlideMove(), and R_CalcTangentsForTriangle().