ET: Legacy: src/sys/con_passive.c File Reference
con_passive.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "sys_local.h"
#include <stdio.h>
Functions
void CON_Shutdown (void)
void CON_Init (void)
char * CON_Input (void)
void CON_Print (const char *msg)
Detailed Description
Wolfenstein: Enemy Territory GPL Source Code Copyright (C) 1999-2010 id Software LLC, a ZeniMax Media company.
ET: Legacy Copyright (C) 2012-2018 ET:Legacy team mail@.nosp@m.etle.nosp@m.gacy..nosp@m.com
This file is part of ET: Legacy - http://www.etlegacy.com
ET: Legacy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
ET: Legacy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with ET: Legacy. If not, see http://www.gnu.org/licenses/.
In addition, Wolfenstein: Enemy Territory GPL Source Code is also subject to certain additional terms. You should have received a copy of these additional terms immediately following the terms and conditions of the GNU General Public License which accompanied the source code. If not, please request a copy in writing from id Software at the address below.
id Software LLC, c/o ZeniMax Media Inc., Suite 120, Rockville, Maryland 20850 USA.
Definition in file con_passive.c.
Function Documentation
void CON_Init (void)
Definition at line 54 of file con_passive.c.
Referenced by Sys_SetUpConsoleAndSignals().
char* CON_Input (void)
Definition at line 63 of file con_passive.c.
Referenced by Sys_ConsoleInput().
void CON_Print (const char * msg)
Definition at line 73 of file con_passive.c.
Referenced by Sys_Print().
void CON_Shutdown (void)
Definition at line 45 of file con_passive.c.
Referenced by __attribute__().