ET: Legacy: src/db/db_sqlite3.c File Reference
db_sqlite3.c File Reference
ET: Legacy SQL interface.
#include "db_sql.h"
Functions
qboolean DB_Init (void)
DB_Init.
static qboolean DB_CreateOrUpdateSchema (int startSchemaVersion)
creates tables and populates our scheme.
int DB_CallbackVersion (void *NotUsed, int argc, char **argv, char **azColName)
DB_CallbackVersion.
qboolean DB_CheckUpdates (void)
DB_CheckUpdates.
qboolean DB_Create (void)
DB_Create.
qboolean DB_SaveMemDB (void)
saves memory db to disk
qboolean DB_Close (void)
Closes the database properly.
int DB_BackupDB (const char *zFilename, void(*xProgress)(int, int))
Perform an online backup of our database db to the database file named by zFilename. Used to store our memory table in between map changes to disk.
int DB_LoadOrSaveDb (sqlite3 *pInMemory, const char *zFilename, int isSave)
This function is used to load the contents of a database file on disk into the "main" database of open database connection pInMemory, or to save the current contents of the database opened by pInMemory into a database file on disk. pInMemory is probably an in-memory database, but this function will also work fine if it is not.
int DB_Callback (void *NotUsed, int argc, char **argv, char **azColName)
Simple callback function which can be used to show results printed on console.
qboolean DB_BeginTransaction (void)
Disables autocommit.
qboolean DB_EndTransaction (void)
Enables autocommit.
Variables
cvar_t * db_mode
cvar_t * db_uri
sqlite3 * db
qboolean isDBActive
const char * sql_Version_Statements [SQL_DBMS_SCHEMA_VERSION]
Detailed Description
ET: Legacy SQL interface.
Tutorial: http://zetcode.com/db/sqlitec/
Definition in file db_sqlite3.c.
Function Documentation
int DB_BackupDB (const char * zFilename, void(*)(int, int) xProgress)
Perform an online backup of our database db to the database file named by zFilename. Used to store our memory table in between map changes to disk.
This function copies 5 database pages from pDb to zFilename, then unlocks pDb and sleeps for 250 ms, then repeats the process until the entire database is backed up.
The third argument passed to this function must be a pointer to a progress function. After each set of 5 pages is backed up, the progress function is invoked with two integer parameters: the number of pages left to copy, and the total number of pages in the source file. This information may be used, for example, to update a GUI progress bar.
While this function is running, another thread may use the database pDb, or another process may access the underlying database file via a separate connection.
If the backup process is successfully completed, SQLITE_OK is returned. Otherwise, if an error occurs, an SQLite error code is returned.
Parameters
[in] zFilename
xProgress Progress function to invoke
Returns
sqlite result code
Todo:
Definition at line 613 of file db_sqlite3.c.
qboolean DB_BeginTransaction (void)
Disables autocommit.
Definition at line 761 of file db_sqlite3.c.
Referenced by FS_Unzip().
int DB_Callback (void * NotUsed, int argc, char ** argv, char ** azColName)
Simple callback function which can be used to show results printed on console.
Parameters
NotUsed
[in] argc
[in] argv
azColName
Returns
0
Definition at line 737 of file db_sqlite3.c.
Referenced by DB_ExecSQLCommand_f().
int DB_CallbackVersion (void * NotUsed, int argc, char ** argv, char ** azColName)
DB_CallbackVersion.
Definition at line 311 of file db_sqlite3.c.
qboolean DB_CheckUpdates (void)
DB_CheckUpdates.
Returns
qtrue on success
Definition at line 329 of file db_sqlite3.c.
Referenced by DB_Init().
qboolean DB_Close (void)
Closes the database properly.
Returns
qtrue on success
Definition at line 553 of file db_sqlite3.c.
Referenced by Com_Shutdown().
qboolean DB_Create (void)
DB_Create.
Returns
qtrue on sucess
Definition at line 415 of file db_sqlite3.c.
Referenced by DB_Init().
static qboolean DB_CreateOrUpdateSchema (int startSchemaVersion) static
creates tables and populates our scheme.
Parameters
[in]
Definition at line 267 of file db_sqlite3.c.
Referenced by DB_CheckUpdates(), and DB_Create().
qboolean DB_EndTransaction (void)
Enables autocommit.
Definition at line 790 of file db_sqlite3.c.
Referenced by FS_Unzip().
qboolean DB_Init (void)
DB_Init.
Returns
qtrue on success
Definition at line 115 of file db_sqlite3.c.
Referenced by Com_Init().
int DB_LoadOrSaveDb (sqlite3 * pInMemory, const char * zFilename, int isSave)
This function is used to load the contents of a database file on disk into the "main" database of open database connection pInMemory, or to save the current contents of the database opened by pInMemory into a database file on disk. pInMemory is probably an in-memory database, but this function will also work fine if it is not.
Parameter zFilename points to a nul-terminated string containing the name of the database file on disk to load from or save to. If parameter isSave is non-zero, then the contents of the file zFilename are overwritten with the contents of the database opened by pInMemory. If parameter isSave is zero, then the contents of the database opened by pInMemory are replaced by data loaded from the file zFilename.
If the operation is successful, SQLITE_OK is returned. Otherwise, if an error occurs, an SQLite error code is returned.
Parameters
[in] pInMemory
[in] zFilename
[in] isSave
Returns
result code
Todo:
Definition at line 679 of file db_sqlite3.c.
Referenced by DB_CheckUpdates(), DB_Init(), and DB_SaveMemDB().
qboolean DB_SaveMemDB (void)
saves memory db to disk
Returns
qtrue on success
Definition at line 500 of file db_sqlite3.c.
Referenced by DB_Close(), DB_Init(), and DB_SaveMemDB_f().
Variable Documentation
sqlite3* db
Definition at line 45 of file db_sqlite3.c.
Referenced by DB_BackupDB(), DB_BeginTransaction(), DB_CheckUpdates(), DB_Close(), DB_Create(), DB_CreateOrUpdateSchema(), DB_EndTransaction(), DB_ExecSQLCommand_f(), DB_Init(), DB_SaveMemDB(), and DB_SaveMemDB_f().
cvar_t* db_mode
Todo:
: - move cvars to qcommon?
Definition at line 42 of file db_sqlite3.c.
Referenced by DB_ExecSQLCommand_f(), DB_SaveMemDB_f(), LAN_AddServer(), LAN_LoadCachedServers(), and LAN_RemoveServer().
cvar_t* db_uri
Definition at line 43 of file db_sqlite3.c.
qboolean isDBActive
Definition at line 46 of file db_sqlite3.c.
Referenced by DB_BeginTransaction(), DB_Close(), DB_EndTransaction(), DB_ExecSQLCommand_f(), and DB_Init().
const char* sql_Version_Statements[SQL_DBMS_SCHEMA_VERSION]
Initial value:
=
{
        "CREATE TABLE IF NOT EXISTS etl_version (Id INT PRIMARY KEY NOT NULL, name TEXT, sql TEXT, created TEXT);"
        "CREATE TABLE IF NOT EXISTS rating_users (guid TEXT PRIMARY KEY NOT NULL, mu REAL, sigma REAL, created TEXT, updated TEXT, UNIQUE (guid));"
        "CREATE TABLE IF NOT EXISTS rating_match (guid TEXT PRIMARY KEY NOT NULL, mu REAL, sigma REAL, time_axis INT, time_allies INT, UNIQUE (guid));"
        "CREATE TABLE IF NOT EXISTS rating_maps (mapname TEXT PRIMARY KEY NOT NULL, win_axis INT, win_allies INT, UNIQUE (mapname));",
        "CREATE TABLE IF NOT EXISTS client_servers (profile TEXT NOT NULL, source INT NOT NULL, address TEXT NOT NULL, name TEXT NOT NULL, mod TEXT NOT NULL, updated DATETIME, created DATETIME);"
        "CREATE INDEX IF NOT EXISTS client_servers_profile_idx ON client_servers(profile);"
        "CREATE INDEX IF NOT EXISTS client_servers_address_idx ON client_servers(address);"
        "CREATE TABLE IF NOT EXISTS etl_whitelist (key TEXT PRIMARY KEY NOT NULL, filename TEXT NOT NULL, updated DATETIME , created DATETIME NOT NULL);"
        "CREATE INDEX IF NOT EXISTS etl_whitelist_idx ON etl_whitelist(filename);"
}
Definition at line 80 of file db_sqlite3.c.
Referenced by DB_CreateOrUpdateSchema().