ET: Legacy: src/qcommon/dl_local.h File Reference
dl_local.h File Reference
Macros
#define _attribute(x)
#define Q_stricmp strcasecmp
Functions
int Com_DPrintf (const char *fmt,...) _attribute((format(printf
A Com_Printf that only shows up if the "developer" cvar is set.
int int Com_Printf (const char *fmt,...) _attribute((format(printf
int int void Com_Error (int code, const char *fmt,...) _attribute((format(printf
int int void void Cvar_SetValue (const char *var_name, float value)
Cvar_SetValue.
void Cvar_Set (const char *varName, const char *value)
Cvar_Set.
char * va (char *format,...) _attribute((format(printf
Variables
int com_errorEntered
Macro Definition Documentation
#define _attribute (x)
Definition at line 41 of file dl_local.h.
#define Q_stricmp strcasecmp
Definition at line 57 of file dl_local.h.
Referenced by _et_gentity_getfield(), _GetEntityClass(), _I18N_Translate(), AddRemap(), alarmbox_updateparts(), Asset_Parse(), BeginIntermission(), BG_AnimationIndexForString(), BG_AnimParseAnimScript(), BG_Find_PathCorner(), BG_Find_Spline(), BG_FindCharacter(), BG_FindFreeCharacter(), BG_FindItem(), BG_FindItemForClassName(), BG_IndexForString(), BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_ParseCommands(), BG_ParseConditionBits(), BG_ParseConditions(), BG_R_RegisterAnimationGroup(), BG_RAG_FindFreeAnimation(), BG_RAG_ParseAnimFile(), BG_setCrosshair(), BG_SS_ParseSpeaker(), Binding_IDFromName(), Bot_Interface_ConsoleCommand(), Bot_Util_CheckForGoalEntity(), CC_svcvar(), CG_BuildLocationString(), CG_CheckForExistingAnimModelInfo(), CG_Class_f(), CG_ConsoleCommand(), CG_Debriefing_CalcCampaignProgress(), CG_DrawScoreboard(), CG_DrawSpectatorMessage(), CG_DrawVote(), CG_DrawWarmup(), CG_EffectParse(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_findClientNum(), CG_getBindKeyName(), CG_GetVoiceChat(), CG_GibPlayer(), CG_inSVCVARBackupList(), CG_LimboPanel_SendSetupMsg(), CG_LoadLocations(), CG_LoadObjectiveData(), CG_MessageMode_f(), CG_ParseEntityFromSpawnVars(), CG_ParseHUD(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_ParticleExplosion(), CG_ProcessCvars(), CG_ReadHudFile(), CG_ReadHuds_f(), CG_RegisterWeaponFromWeaponFile(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), CG_RW_ParseSoundSurface(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLink(), CG_RW_ParseWeaponLinkPart(), CG_SetInitialSnapshot(), CG_SoundParseSounds(), CG_SoundPlaySoundScript(), CG_SoundScriptPrecache(), CG_SpeakerEditor_NoiseEdit_KeyDown(), CheckCvars(), CIN_PlayCinematic(), CIN_PlayCinematic_f(), CL_ConnectionlessPacket(), CL_MapLoading(), CL_OpenAVIForWriting(), CL_ServerInfoPacket(), CL_SetCGameTime(), CL_SetExpectedHunkUsage(), CL_SystemInfoChanged(), CL_UpdateLevelHunkUsage(), ClientCommand(), ClientConnect(), ClientForString(), ClientUserinfoChanged(), Cmd_CompleteArgument(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_FindCommand(), Cmd_FireTeam_MP_f(), Cmd_Follow_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_SetCommandCompletionFunc(), Cmd_SetCommandDescription(), Com_InitUpdateDownloads(), Com_SafeMode(), ConsoleCommand(), CreateShaderByGuide(), Cvar_FindVar(), Cvar_List_f(), Cvar_Print(), Do_Activate_f(), EmitterCheck(), etpro_ScriptAction_SetValues(), FindClientByName(), FindGuideInGuideText(), findNonAIBrushTargeter(), FindShaderInShaderText(), FindShaderInShaderTextR1(), FS_AddBothGameDirectories(), FS_AddFileToList(), FS_AddGameDirectory(), FS_DeleteDir(), FS_FOpenFileReadDir(), FS_GetFileList(), FS_GetModList(), FS_IsExt(), FS_IsSamePath(), FS_ListFilteredFiles(), FS_LoadZipFile(), FS_Restart(), FS_Startup(), FS_SV_FOpenFileRead(), FS_VerifyOfficialPaks(), FS_VerifyPak(), func_constructiblespawn(), func_explosive_explode(), func_explosive_use(), G_CallSpawn(), G_CheckForCursorHints(), G_CheckForExistingAnimModelInfo(), G_commandCheck(), G_commandHelp(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_Damage(), G_DrawEntBBox(), G_EmplacedGunIsMountable(), G_EmplacedGunIsRepairable(), G_FilterMaxLivesPacket(), G_Find(), G_FindByTargetname(), G_FindByTargetnameFast(), G_FindTeams(), G_FireteamNumberForString(), G_GetPlayerByName(), G_GetSysMessageNumber(), G_GetTeamFromEntity(), G_InitWorldSession(), G_IsShoutcastPasswordSet(), G_KillEnts(), G_LoadCampaignsFromFile(), G_LuaRunIsolated(), G_LuaStartVM(), G_MapIsValidCampaignStartMap(), G_MapVoteInfoRead(), G_MissileImpact(), G_ParseCampaigns(), G_ParseField(), G_ParseMapSettings(), G_ParseSettings(), G_PlaySound_Cmd(), G_PrintConfigs(), G_ref_cmd(), G_refClientnumForName(), G_refCommandCheck(), G_RunMover(), G_SayTo(), G_sclogin_cmd(), G_Script_EventMatch_StringEqual(), G_Script_ScriptEvent(), G_Script_ScriptParse(), G_ScriptAction_Accum(), G_ScriptAction_AllowTankEnter(), G_ScriptAction_AllowTankExit(), G_ScriptAction_Cvar(), G_ScriptAction_Delete(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), G_ScriptAction_FaceAngles(), G_ScriptAction_FadeAllSounds(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GlobalAccum(), G_ScriptAction_GotoMarker(), G_ScriptAction_PlayAnim(), G_ScriptAction_PlaySound(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetModelFromBrushmodel(), G_ScriptAction_SetSpeed(), G_ScriptAction_SetState(), G_ScriptAction_SpawnRubble(), G_ScriptAction_StartAnimation(), G_ScriptAction_ToggleSpeaker(), G_ScriptAction_Trigger(), G_ScriptAction_Wait(), G_SetEntState(), G_StartMatch_v(), G_TeamDataForString(), G_UpdateCvars(), G_UseTargets(), G_voteCmdCheck(), G_voteDescription(), G_weaponRankings_cmd(), GameType_Parse(), ETInterface::GetAutoNavFeatures(), ETInterface::GetEntityCategory(), ETInterface::GetEntityFlags(), ETInterface::GetEntityLocalAABB(), ETInterface::GetEntityOwner(), ETInterface::GetEntityWorldAABB(), GetFieldIndex(), ETInterface::GetGoals(), GetOpType(), GL_CheckForExtension(), GL_TextureMode(), GLimp_EndFrame(), GLSL_FindDefinitionInText(), GLSL_FindShader(), GLSL_GetAttribByName(), GLSL_GetMacroByName(), GLSL_ParseDefinition(), GLSL_PreprocessShaderText(), HT_Create(), Hunk_SmallLog(), I18N_SetLanguage(), InitMover(), InitProp(), ETInterface::InterfaceSendMessage(), IsBinaryMoverBlocked(), Item_Combo_Paint(), Item_EnableShowViaCvar(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_RunScript(), Key_GetBindingByString(), Key_GetKey(), Key_StringToKeynum(), KeywordHash_Find(), LAN_CompareServers(), LoadMap(), LoadRGBEToFloats(), Menu_FindItemByName(), Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), Menu_UpdatePosition(), MenuParse_name(), Menus_ActivateByName(), Menus_FindByName(), NameToAFunc(), NameToDstBlendMode(), NameToGenFunc(), NameToSrcBlendMode(), NameToStencilOp(), NET_IsLocalAddressString(), ParseDeform(), ParseShader(), ParseShaderR1(), ParseSort(), ParseStage(), ParseStencil(), ParseSurfaceParm(), ParseTexMod(), PC_PushScript(), PC_Script_Parse(), Props_Activated(), Props_Chair_Animate(), Props_Chair_Touch(), props_statue_blocked(), Props_TurnLightsOff(), R_FindCachedImage(), R_FindCachedShader(), R_FindCubeImage(), R_FindImageFile(), R_FindShader(), R_FindShaderByName(), R_LoadEntities(), R_LoadImage(), R_LoadLights(), R_LoadMD5(), R_LoadMD5Anim(), R_LoadPreRenderedFont(), R_LoadScalableFont(), R_RemapShader(), RE_BeginFrame(), RE_BoneIndex(), RE_CheckSkeleton(), RE_GetSkinModel(), RE_LoadDynamicShader(), RE_RegisterAnimation(), RE_RegisterModel(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), ETInterface::RemoveBot(), S_FindCodecForFile(), S_FindName(), S_LoadSound(), S_StartStreamingSoundEx(), ScanAndLoadShaderFilesR1(), Script_ConditionalScript(), Script_GetClipboard(), Script_SetColor(), Script_SetItemColor(), Script_SetMenuItemColor(), SetMoverState(), setProjTargetOrigin(), Simple_EmplacedGunIsRepairable(), SP_func_explosive(), SP_func_invisible_user(), SP_props_decoration(), SP_props_footlocker(), SP_props_statue(), SP_script_mover(), SP_target_effect(), SP_target_explosion(), SP_worldspawn(), sparks_angles_think(), Spawn_Shard(), SurfaceParm(), SV_CheckLastCmd(), SV_ClientCommand(), SV_ConnectionlessPacket(), SV_DemoClientCommandCapture(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DemoStartPlayback(), SV_GetPlayerByName(), SV_GetTag(), SV_LoadTag(), SV_Map_f(), SV_SetExpectedHunkUsage(), SV_WWWDownload_f(), Svcmd_Burn(), Svcmd_Campaign_f(), Svcmd_CSInfo_f(), Svcmd_Die(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_Pip(), Svcmd_Unfreeze(), Sys_Dialog(), Sys_ListFiles(), Sys_ListFilteredFiles(), TeamplayInfoMessage(), Think_SetupTrainTargets(), trap_TranslateString(), UI_BuildServerDisplayList(), UI_Campaign_f(), UI_ConsoleCommand(), UI_DescriptionForCampaign(), UI_FeederItemText(), UI_FindCampaignInCampaignList(), UI_FindMapInfoByMapname(), UI_GetServerStatusInfo(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadDemos(), UI_LoadMenus(), UI_LoadMovies(), UI_LoadProfiles(), UI_NameForCampaign(), UI_ParseGameInfo(), UI_ParseMenu(), UI_RunMenuScript(), UI_SetActiveMenu(), UI_SortServerStatusInfo(), UI_TeamIndexFromName(), UI_Update(), validOilSlickSpawnPoint(), VM_Create(), and Weapon_Engineer().
Function Documentation
int Com_DPrintf (const char * fmt, ...)
A Com_Printf that only shows up if the "developer" cvar is set.
Parameters
[in] fmt
Definition at line 312 of file common.c.
int int void Com_Error (int code, const char * fmt, ...)
int int Com_Printf (const char * fmt, ...)
void Cvar_Set (const char * varName, const char * value)
Cvar_Set.
Parameters
[in] varName
[in] value
Definition at line 782 of file cvar.c.
int int void void Cvar_SetValue (const char * var_name, float value)
Cvar_SetValue.
Parameters
[in] var_name
[in] value
Definition at line 827 of file cvar.c.
char* va (char * format, ...)
Referenced by __attribute__(), _et_MutePlayer(), _et_UnmutePlayer(), ETInterface::AddBot(), AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), AssetCache(), AutoBuildConstruction(), BeginIntermission(), BG_LoadTraceMap(), BG_PanelButton_RenderEdit(), Bot_Interface_Update(), CalculateRanks(), CG_AddPMItem(), CG_AdjustAutomapZoom(), CG_AltWeapon_f(), CG_autoRecord_f(), CG_autoScreenShot_f(), CG_BuddyVoiceChat_f(), CG_BuildLocationString(), CG_BuildSelectedFirteamString(), CG_Class_f(), CG_ClearParticles(), CG_CommandCentreSpawnPointClick(), CG_Debriefing_Awards_Draw(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_InfoRequests(), CG_Debriefing_Maps_Draw(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_ParseAwards(), CG_Debriefing_PlayerACC_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerHS_Draw(), CG_Debriefing_PlayerTime_Draw(), CG_Debriefing_PlayerXP_Draw(), CG_Debriefing_TeamSkillXP_Draw(), CG_Debriefing_TimeToString(), CG_DebriefingPlayerList_Draw(), CG_DebriefingPlayerWeaponStats_Draw(), CG_DebriefingTitle_Draw(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_DemoControlButtonDown(), CG_DemoHelpDraw(), CG_demoTimescaleDraw(), CG_DrawActiveFrame(), CG_DrawConnectScreen(), CG_DrawCrosshairNames(), CG_DrawFireTeamOverlay(), CG_DrawFireteamsByTeam(), CG_DrawFlashFade(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawLimboMessage(), CG_DrawLocalTime(), CG_DrawMapEntity(), CG_DrawMortarReticle(), CG_DrawObjectiveInfo(), CG_DrawPing(), CG_DrawPlayerHealth(), CG_DrawPlayerNF(), CG_DrawPlayerSF(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScoreboard(), CG_DrawSkills(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawSpeed(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawXP(), CG_dumpStats(), CG_Effect(), CG_execFile(), CG_FeederItemText(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_FinishWeaponChange(), CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), CG_FTSayPlayerClass_f(), CG_generateFilename(), CG_getBindKeyName(), CG_GetLocationMsg(), CG_GetPMItemText(), CG_GetRealTime(), CG_Init(), CG_IsClassFull(), CG_IsWeaponDisabled(), CG_Item(), CG_ItemPickup(), CG_KickAngles(), CG_LimboPanel_BriefingButton_KeyDown(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RequestObjective(), CG_LimboPanel_RequestWeaponStats(), CG_LimboPanel_SendSetupMsg(), CG_LimboPanel_WeaponPanel(), CG_LoadLocations(), CG_LoadObjectiveData(), CG_LoadPanel_RenderCampaignNameText(), CG_LoadPanel_RenderCampaignTypeText(), CG_MapVote_MultiVoteButton_Draw(), CG_MapVote_MultiVoteButton_KeyDown(), CG_MapVote_VoteButton_KeyDown(), CG_MapVoteList_Draw(), CG_MessageSend_f(), CG_Missile(), CG_NewClientInfo(), CG_Obituary(), CG_ObjectivesDraw(), CG_parseBestShotsStats_cmd(), CG_ParseGibModels(), CG_parseMapVoteListInfo(), CG_ParseServerinfo(), CG_parseTopShotsStats_cmd(), CG_ParseVoiceChats(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_ParseWolfinfo(), CG_PickupItemText(), CG_ProcessCvars(), CG_ReadHuds_f(), CG_RegisterAcc(), CG_RegisterCharacter(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_RegisterWeapon(), CG_Respawn(), CG_RW_ParseWeaponSound(), CG_SaveSpeakersToScript(), CG_SayPlayerClass_f(), CG_scores_cmd(), CG_ScoresDown_f(), CG_ServerCommand(), CG_setClientFlags(), CG_Spawnpoints_MenuText_Draw(), CG_SpawnpointsCheckExecKey(), CG_SpeakerEditor_LocInfo(), CG_SpeakerEditorDraw(), CG_SpeakerInfo_Text(), CG_StatsDown_f(), CG_TeamDebriefingTeamSkillXP_Draw(), CG_TeamRestrictionsChanged(), CG_TeamVoiceChat_f(), CG_TimerReset_f(), CG_TimerSet_f(), CG_topshotsParse_cmd(), CG_TouchTriggerPrediction(), CG_UpdateCvars(), CG_UpdateSvCvars(), CG_VoiceChat_f(), CG_vstrDown_f(), CG_vstrUp_f(), ETInterface::ChangeTeam(), CheatsOk(), CheckExitRules(), checkpoint_spawntouch(), checkpoint_use(), CheckVote(), CheckWolfMP(), CIN_StopCinematic(), CL_CheckFileSize(), CL_CheckForResend(), CL_CheckUserinfo(), CL_CloseAVI(), CL_DemoInit(), CL_GetServerCommand(), CL_OpenAVIForWriting(), CL_ParseDownload(), CL_Reconnect_f(), CL_RequestMotd(), CL_ResetPureClientAtServer(), CL_ServerInfoPacket(), CL_SystemInfoChanged(), ClientBegin(), ClientCommand(), ClientConnect(), ClientInactivityTimer(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallVote_f(), Cmd_Echo_f(), Cmd_Follow_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_Ignore_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_Notarget_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_UnIgnore_f(), Cmd_Vote_f(), Cmd_Vstr_f(), Cmd_WeaponStat_f(), Cmd_Where_f(), Com_BeginDownload(), Com_CheckAutoUpdate(), Com_Error(), Com_GetCommandLine(), Com_Init(), Com_InitDownloads(), Com_InitUpdateDownloads(), Com_MD5File(), Com_ModifyMsec(), Com_Printf(), Com_SetupDownload(), Com_UpdateInfoPacket(), Com_WriteConfiguration(), Com_WWWBadChecksum(), Com_WWWDownload(), Cvar_Cycle_f(), Cvar_Toggle_f(), DB_CheckUpdates(), DB_CreateOrUpdateSchema(), DL_BeginDownload(), DL_GetString(), dlight_finish_spawning(), Do_Activate2_f(), DoClientThinks(), DoorSetSounds(), ExitLevel(), FS_ComparePaks(), FS_DeleteDir(), FS_idPak(), FS_LoadedPakChecksums(), FS_LoadedPakPureChecksums(), FS_ReferencedPakChecksums(), FS_ReferencedPakPureChecksums(), FS_Restart(), FS_Unzip(), func_constructible_explode(), func_constructible_use(), func_constructiblespawn(), G_AddKillSkillPoints(), G_ApplyToFireTeam(), G_BuildEndgameStats(), G_Campaign_v(), G_checkReady(), G_ClearMapXP(), G_cmdDebounce(), G_commandHelp(), G_commands_cmd(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_configSet(), G_createStats(), G_Damage(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DebugCloseSkillLog(), G_DebugOpenSkillLog(), G_delayPrint(), G_deleteStats(), G_DropItems(), G_EntitySound(), G_EntitySoundNoCut(), G_Gametype_v(), G_GetMapXP(), G_HQSay(), G_InitGame(), G_InitWorldSession(), G_IntermissionMapList(), G_IntermissionMapVote(), G_IntermissionVoteTally(), G_InviteToFireTeam(), G_isValidConfig(), G_IsWeaponDisabled(), G_Kick_v(), G_LeaveTank(), G_loadMatchGame(), G_lock_cmd(), G_LogExit(), G_LuaStartVM(), G_MakeReferee(), G_MakeShoutcaster(), G_Map_v(), G_MapVoteInfoWrite(), G_matchInfoDump(), G_ModifyTOI(), G_Mute_v(), G_MuteClient(), G_ParseCampaigns(), G_ParseMapSettings(), G_ParseSettings(), G_pause_cmd(), G_players_cmd(), G_PlaySound_Cmd(), G_PrintAccuracyLog(), G_PrintClientSpammyCenterPrint(), G_printFull(), G_printMatchInfo(), G_ProcessTagConnect(), G_ProposeFireTeamPlayer(), G_PushMapEntityToBuffer(), G_ReadSessionData(), G_ready_cmd(), G_readyMatchState(), G_ref_cmd(), G_Referee_v(), G_refLockTeams_cmd(), G_refPause_cmd(), G_refPrintf(), G_refRemove_cmd(), G_refSpeclockTeams_cmd(), G_refWarmup_cmd(), G_refWarning_cmd(), G_RegisterCvars(), G_RemoveClientFromFireteams(), G_RestartCampaign_v(), G_RunFrame(), G_SayTo(), G_sclogin_cmd(), G_Script_ScriptEvent(), G_Script_ScriptParse(), G_ScriptAction_AlliedRespawntime(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_AxisRespawntime(), G_ScriptAction_Cvar(), G_ScriptAction_FaceAngles(), G_ScriptAction_FadeAllSounds(), G_ScriptAction_GotoMarker(), G_ScriptAction_MusicFade(), G_ScriptAction_MusicPlay(), G_ScriptAction_MusicStart(), G_ScriptAction_MusicStop(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDebugLevel(), G_ScriptAction_SetGlobalFog(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetModelFromBrushmodel(), G_ScriptAction_SetRoundTimelimit(), G_SendScore(), G_SendSystemMessage(), G_SHA1(), G_ShutdownGame(), G_specinvite_cmd(), G_speclock_cmd(), G_statsall_cmd(), G_statsPrint(), G_StoreMapXP(), G_Surrender_v(), G_TeamCommand(), G_teamJoinCheck(), G_teamready_cmd(), G_UnMute_v(), G_UnMuteClient(), G_Unreferee_v(), G_UpdateCvars(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), G_UpdateSvCvars(), G_verifyMatchState(), G_VoiceTo(), G_voteFlags(), G_voteSetOnOff(), G_voteSetValue(), G_voteSetVoteString(), G_Warmupfire_v(), G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), G_WriteClientSessionData(), G_WriteSessionData(), GeneratePermanentShader(), GetMDMSurfaceShader(), GetMenuBuffer(), GL_TextureMode(), GLimp_DetectAvailableModes(), GLimp_EndFrame(), GLimp_Init(), GLSL_CompileGPUShader(), GLSL_FinnishShaderTextAndCompile(), GLSL_GenerateMacroString(), GLSL_GetShaderText(), GLSL_LoadShaderBinary(), GLSL_SaveShaderBinary(), HandleEntsThatBlockConstructible(), Hunk_Alloc(), Hunk_Clear(), I18N_Init(), ETInterface::InterfaceSendMessage(), Item_CheckBox_HandleKey(), Item_Combo_HandleKey(), Item_Multi_HandleKey(), Item_Scroll_Slider_ThumbFunc(), Item_Slider_HandleKey(), Item_Text_Paint(), Item_YesNo_HandleKey(), LAN_GetServerInfo(), LoadMap(), Menu_PaintAll(), NET_GetCvars(), Netchan_Init(), PC_Script_Parse(), player_die(), PrintMsg(), R_AddAnimSurfaces(), R_AddMD3Surfaces(), R_AddMDCSurfaces(), R_BuildCubeMaps(), R_CreateBloomRenderFBOImage(), R_CreateShadowCubeFBOImage(), R_CreateShadowMapFBOImage(), R_CreateSubModelVBOs(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_CreateWorldVBO(), R_FindImageFile(), R_FindShader(), R_InitFBOs(), R_inPVS(), R_LoadCubeProbe(), R_LoadImage(), R_LoadLightmaps(), R_LoadLightmapsExternal(), R_LoadLightmapsInternal(), R_LoadMD5Anim(), R_LoadNodesAndLeafs(), R_LoadScalableFont(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_MDM_AddAnimSurfaces(), R_PurgeLightmapShaders(), R_Register(), RE_InitOpenGl(), RE_RegisterModel(), ReviveEntity(), SCR_DrawDemoRecording(), Script_ConditionalScript(), Script_Exec(), Script_ExecNOW(), Script_ExecWolfConfig(), Script_GetClipboard(), Script_ToggleCvarBit(), SetMoverState(), SetPlayerSpawn(), SP_func_constructible(), SP_func_explosive(), SP_info_train_spline_main(), SP_misc_constructiblemarker(), SP_script_mover(), SP_skyportal(), SP_trigger_objective_info(), SP_worldspawn(), SV_BoundMaxClients(), SV_CheckDRDoS(), SV_CheckLastCmd(), SV_CheckTimeouts(), SV_ConnectionlessPacket(), SV_Demo_Play_f(), SV_DemoAutoDemoRecord(), SV_DemoCvarsRestore(), SV_DemoReadClientUserinfo(), SV_DemoReadFrame(), SV_DemoRestartPlayback(), SV_DemoStartPlayback(), SV_DemoStopPlayback(), SV_DirectConnect(), SV_Frame(), SV_GenerateDateTime(), SV_GetChallenge(), SV_Init(), SV_Map_f(), SV_MapRestart_f(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SV_SetupDownloadFile(), SV_Shutdown(), SV_SpawnServer(), SV_TransitionGameState(), SV_WWWDownload_f(), SVC_BucketForAddress(), SVC_Info(), SVC_RateLimit(), SVC_RemoteCommand(), SVC_Status(), Svcmd_Burn(), Svcmd_Campaign_f(), Svcmd_Chat_f(), Svcmd_CP_f(), Svcmd_Die(), Svcmd_EntityList_f(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Pip(), Svcmd_ResetMatch_f(), Svcmd_Say_f(), Svcmd_Unfreeze(), Sys_ErrorDialog(), Sys_KdialogCommand(), Sys_ListFiles(), Sys_SetEnv(), Sys_SigHandler(), Sys_ZenityCommand(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), TeamplayInfoMessage(), Touch_flagonly(), Touch_flagonly_multiple(), TranslationMissing(), TryConstructing(), UI_BuildPlayerList(), UI_BuildServerDisplayList(), UI_Campaign_f(), UI_Crosshair_HandleKey(), UI_DownloadInfo(), UI_DrawCampaignCinematic(), UI_DrawCampaignName(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_DrawMissionBriefingMap(), UI_DrawMissionBriefingTitle(), UI_DrawNetFilter(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawPreviewCinematic(), UI_DrawServerRefreshDate(), UI_DrawTeamName(), UI_FeederItemText(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_ListFavourites_f(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadPanel_RenderLoadingText(), UI_LoadProfiles(), UI_OwnerDrawWidth(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_StartServerRefresh(), UI_TeamMember_HandleKey(), UpdateIPBans(), Use_BinaryMover(), Use_target_fog(), Use_Target_Print(), vmMain(), Weapon_Engineer(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawInfoLine(), WM_DrawObjectives(), WM_TeamScoreboard(), and WM_TimeToString().
Variable Documentation
int com_errorEntered
Definition at line 167 of file common.c.