ET: Legacy: src/qcommon/dl_main_curl.c File Reference
dl_main_curl.c File Reference
#include <curl/curl.h>
#include "q_shared.h"
#include "qcommon.h"
#include "dl_public.h"
Data Structures
struct write_result_s
Macros
#define APP_NAME "ID_DOWNLOAD"
#define APP_VERSION "2.0"
#define GET_BUFFER_SIZE 1024 * 256
Typedefs
typedef struct write_result_s write_result_t
Functions
static size_t DL_cb_FWriteFile (void *ptr, size_t size, size_t nmemb, void *stream)
DL_cb_FWriteFile.
static int DL_cb_Progress (void *clientp, double dltotal, double dlnow, double ultotal, double ulnow)
DL_cb_Progress.
size_t DL_write_function (void *ptr, size_t size, size_t nmemb, void *stream)
DL_write_function.
void DL_InitDownload (void)
DL_InitDownload.
void DL_Shutdown (void)
DL_Shutdown.
int DL_BeginDownload (char *localName, const char *remoteName)
Inspired from http://www.w3.org/Library/Examples/LoadToFile.c setup the download, return once we have a connection.
char * DL_GetString (const char *url)
DL_GetString.
dlStatus_t DL_DownloadLoop (void)
DL_DownloadLoop.
Variables
static int dl_initialized = 0
Initialize once.
static CURLM * dl_multi = NULL
static CURL * dl_request = NULL
static FILE * dl_file = NULL
Detailed Description
Todo:
Additional features that would be nice for this code: Only display <gamepath>/<file>, e.g., etpro/etpro-3_0_1.pk3 in the UI. Add server as referring URL
Definition in file dl_main_curl.c.
Macro Definition Documentation
#define APP_NAME "ID_DOWNLOAD"
Definition at line 45 of file dl_main_curl.c.
Referenced by DL_BeginDownload(), and DL_GetString().
#define APP_VERSION "2.0"
Definition at line 46 of file dl_main_curl.c.
Referenced by DL_BeginDownload(), and DL_GetString().
#define GET_BUFFER_SIZE 1024 * 256
Definition at line 48 of file dl_main_curl.c.
Referenced by DL_GetString(), and DL_write_function().
Typedef Documentation
typedef struct write_result_s write_result_t
Function Documentation
int DL_BeginDownload (char * localName, const char * remoteName)
Inspired from http://www.w3.org/Library/Examples/LoadToFile.c setup the download, return once we have a connection.
Parameters
localName
remoteName
Returns
Definition at line 170 of file dl_main_curl.c.
Referenced by CL_ParseDownload(), Com_InitUpdateDownloads(), and Com_SetupDownload().
static size_t DL_cb_FWriteFile (void * ptr, size_t size, size_t nmemb, void * stream) static
DL_cb_FWriteFile.
Parameters
[in] ptr
[in] size
[in] nmemb
[in] stream
Returns
Definition at line 77 of file dl_main_curl.c.
Referenced by DL_BeginDownload().
static int DL_cb_Progress (void * clientp, double dltotal, double dlnow, double ultotal, double ulnow) static
DL_cb_Progress.
Parameters
clientp - unused
dltotal - unused
[in] dlnow
ultotal - unused
ulnow - unused
Returns
Note
cl_downloadSize and cl_downloadTime are set by the Q3 protocol... and it would probably be expensive to verify them here.
Definition at line 95 of file dl_main_curl.c.
Referenced by DL_BeginDownload().
dlStatus_t DL_DownloadLoop (void)
DL_DownloadLoop.
Returns
Note
maybe this should be CL_DL_DownloadLoop
Definition at line 328 of file dl_main_curl.c.
Referenced by Com_WWWDownload().
char* DL_GetString (const char * url)
DL_GetString.
Parameters
[in] url
Returns
Note
Unused
Definition at line 243 of file dl_main_curl.c.
void DL_InitDownload (void)
DL_InitDownload.
Definition at line 128 of file dl_main_curl.c.
Referenced by DL_BeginDownload(), and DL_GetString().
void DL_Shutdown (void)
DL_Shutdown.
Definition at line 147 of file dl_main_curl.c.
Referenced by CL_Shutdown(), and CL_ShutdownAll().
size_t DL_write_function (void * ptr, size_t size, size_t nmemb, void * stream)
DL_write_function.
Parameters
[in] ptr
[in] size
[in] nmemb
[out] stream
Returns
Definition at line 109 of file dl_main_curl.c.
Referenced by DL_GetString().
Variable Documentation
FILE* dl_file = NULL static
Definition at line 58 of file dl_main_curl.c.
Referenced by DL_BeginDownload(), and DL_DownloadLoop().
dl_initialized = 0 static
Initialize once.
Definition at line 54 of file dl_main_curl.c.
Referenced by DL_InitDownload(), and DL_Shutdown().
CURLM* dl_multi = NULL static
Definition at line 56 of file dl_main_curl.c.
Referenced by DL_BeginDownload(), DL_DownloadLoop(), DL_InitDownload(), and DL_Shutdown().
CURL* dl_request = NULL static
Definition at line 57 of file dl_main_curl.c.
Referenced by DL_BeginDownload(), DL_DownloadLoop(), and DL_GetString().