ET: Legacy: src/qcommon/dl_public.h File Reference
dl_public.h File Reference
Enumerations
enum dlStatus_t { DL_CONTINUE, DL_DONE, DL_FAILED }
enum dlFlags_t { DL_FLAG_DISCON = 0, DL_FLAG_URL }
bitmask
Functions
int DL_BeginDownload (char *localName, const char *remoteName)
Inspired from http://www.w3.org/Library/Examples/LoadToFile.c setup the download, return once we have a connection.
char * DL_GetString (const char *url)
DL_GetString.
dlStatus_t DL_DownloadLoop (void)
DL_DownloadLoop.
void DL_Shutdown (void)
DL_Shutdown.
Enumeration Type Documentation
enum dlFlags_t
bitmask
Enumerator
DL_FLAG_DISCON
DL_FLAG_URL
Definition at line 55 of file dl_public.h.
enum dlStatus_t
Enumerator
DL_CONTINUE
DL_DONE
DL_FAILED
Definition at line 38 of file dl_public.h.
Function Documentation
int DL_BeginDownload (char * localName, const char * remoteName)
Inspired from http://www.w3.org/Library/Examples/LoadToFile.c setup the download, return once we have a connection.
Parameters
localName
remoteName
Returns
Inspired from http://www.w3.org/Library/Examples/LoadToFile.c setup the download, return once we have a connection.
Parameters
localName - unused
remoteName - unused
Returns
Definition at line 170 of file dl_main_curl.c.
Referenced by CL_ParseDownload(), Com_InitUpdateDownloads(), and Com_SetupDownload().
dlStatus_t DL_DownloadLoop (void)
DL_DownloadLoop.
Returns
Note
maybe this should be CL_DL_DownloadLoop
Returns
Note
Maybe this should be CL_DL_DownloadLoop
Definition at line 328 of file dl_main_curl.c.
Referenced by Com_WWWDownload().
char* DL_GetString (const char * url)
DL_GetString.
Parameters
[in] url
Returns
Note
Unused
Parameters
url - unused
Returns
Definition at line 243 of file dl_main_curl.c.
void DL_Shutdown (void)
DL_Shutdown.
Definition at line 147 of file dl_main_curl.c.
Referenced by CL_Shutdown(), and CL_ShutdownAll().