ET: Legacy: src/qcommon/download.c File Reference
download.c File Reference
#include "../client/client.h"
Macros
#define dld cls.download
#define Com_AddReliableCommand(x) CL_AddReliableCommand(x)
Functions
void Com_ClearDownload (void)
Com_ClearDownload.
void Com_ClearStaticDownload (void)
Clear download information that we keep in cls (disconnected download support)
static void Com_DownloadsComplete (void)
Called when all downloading has been completed Initiates update process after an update has been downloaded.
void Com_BeginDownload (const char *localName, const char *remoteName)
Requests a file to download from the server. Stores it in the current game directory.
static void checkDownloadName (char *filename)
void Com_NextDownload (void)
A download completed or failed.
void Com_InitDownloads (void)
After receiving a valid game state, we validate the cgame and local zip files here and determine if we need to download them.
void Com_WWWDownload (void)
Com_WWWDownload.
qboolean Com_WWWBadChecksum (const char *pakname)
FS code calls this when doing FS_ComparePaks we can detect files that we got from a www dl redirect with a wrong checksum this indicates that the redirect setup is broken, and next dl attempt should NOT redirect.
static void Com_SetupDownload (const char *remote, const char *filename)
Com_SetupDownload.
void Com_Download_f (void)
Com_Download_f.
Macro Definition Documentation
#define Com_AddReliableCommand (x) CL_AddReliableCommand(x)
Definition at line 42 of file download.c.
Referenced by Com_BeginDownload(), Com_DownloadsComplete(), and Com_WWWDownload().
#define dld cls.download
Definition at line 41 of file download.c.
Referenced by Com_BeginDownload(), Com_ClearDownload(), Com_ClearStaticDownload(), Com_Download_f(), Com_DownloadsComplete(), Com_InitDownloads(), Com_NextDownload(), Com_SetupDownload(), Com_WWWBadChecksum(), and Com_WWWDownload().
Function Documentation
static void checkDownloadName (char * filename) static
Definition at line 160 of file download.c.
Referenced by Com_NextDownload().
void Com_BeginDownload (const char * localName, const char * remoteName)
Requests a file to download from the server. Stores it in the current game directory.
Parameters
[in] localName
[in] remoteName
Definition at line 134 of file download.c.
Referenced by Com_NextDownload().
void Com_ClearDownload (void)
Com_ClearDownload.
Definition at line 48 of file download.c.
Referenced by CL_Disconnect(), and CL_ParseDemo().
void Com_ClearStaticDownload (void)
Clear download information that we keep in cls (disconnected download support)
Definition at line 66 of file download.c.
Referenced by CL_Disconnect(), Com_CheckUpdateDownloads(), Com_DownloadsComplete(), Com_InitDownloads(), Com_RunUpdateBinary(), and Com_WWWDownload().
void Com_Download_f (void)
Com_Download_f.
Definition at line 485 of file download.c.
Referenced by Com_Init().
static void Com_DownloadsComplete (void) static
Called when all downloading has been completed Initiates update process after an update has been downloaded.
Definition at line 80 of file download.c.
Referenced by Com_InitDownloads(), and Com_NextDownload().
void Com_InitDownloads (void)
After receiving a valid game state, we validate the cgame and local zip files here and determine if we need to download them.
Definition at line 233 of file download.c.
Referenced by CL_ParseGamestate(), Com_CheckUpdateDownloads(), and Com_CheckUpdateStarted().
void Com_NextDownload (void)
A download completed or failed.
Definition at line 177 of file download.c.
Referenced by CL_ParseDownload(), Com_InitDownloads(), and Com_WWWDownload().
static void Com_SetupDownload (const char * remote, const char * filename) static
Com_SetupDownload.
Parameters
[in] remote
[in] filename
Definition at line 464 of file download.c.
Referenced by Com_Download_f().
qboolean Com_WWWBadChecksum (const char * pakname)
FS code calls this when doing FS_ComparePaks we can detect files that we got from a www dl redirect with a wrong checksum this indicates that the redirect setup is broken, and next dl attempt should NOT redirect.
Parameters
[in] pakname
Returns
Definition at line 440 of file download.c.
Referenced by FS_ComparePaks().
void Com_WWWDownload (void)
Com_WWWDownload.
Definition at line 329 of file download.c.
Referenced by CL_Frame(), and SV_Frame().