ET: Legacy: src/game/et-antiwarp.c File Reference
et-antiwarp.c File Reference
Antiwarp code from etpro thanks to zinx.
#include "g_local.h"
Functions
qboolean G_DoAntiwarp (gentity_t *ent)
G_DoAntiwarp.
void etpro_AddUsercmd (int clientNum, usercmd_t *cmd)
etpro_AddUsercmd
static float G_CmdScale (gentity_t *ent, usercmd_t *cmd)
G_CmdScale.
void DoClientThinks (gentity_t *ent)
DoClientThinks.
Detailed Description
Antiwarp code from etpro thanks to zinx.
Copyright
ETPro
Definition in file et-antiwarp.c.
Function Documentation
void DoClientThinks (gentity_t * ent)
DoClientThinks.
Parameters
[in,out] ent
Definition at line 144 of file et-antiwarp.c.
Referenced by ClientThink(), and G_RunClient().
void etpro_AddUsercmd (int clientNum, usercmd_t * cmd)
etpro_AddUsercmd
Parameters
[in] clientNum
[in] cmd
Definition at line 49 of file et-antiwarp.c.
Referenced by ClientThink().
static float G_CmdScale (gentity_t * ent, usercmd_t * cmd) static
G_CmdScale.
Parameters
[in] ent
[in] cmd
Returns
Note
G_CmdScale is a hack :x
Definition at line 74 of file et-antiwarp.c.
Referenced by DoClientThinks().
qboolean G_DoAntiwarp (gentity_t * ent)
G_DoAntiwarp.
Parameters
[in] ent
Returns
Note
Fixes spectator bugs
Definition at line 16 of file et-antiwarp.c.
Referenced by ClientEndFrame(), ClientThink(), ClientThink_real(), and G_RunClient().