ET: Legacy: src/game/g_antilag.c File Reference
g_antilag.c File Reference
#include "g_local.h"
Macros
#define POSITION_READJUST
Functions
static void TimeShiftLerp (vec3_t start, vec3_t end, float frac, vec3_t result)
Used below to interpolate between two previous vectors.
static qboolean G_AntilagSafe (gentity_t *ent)
G_AntilagSafe.
void G_StoreClientPosition (gentity_t *ent)
G_StoreClientPosition.
static void G_AdjustSingleClientPosition (gentity_t *ent, int time)
G_AdjustSingleClientPosition.
void G_ReAdjustSingleClientPosition (gentity_t *ent)
G_ReAdjustSingleClientPosition.
static void G_AdjustClientPositions (gentity_t *ent, int time, qboolean forward)
G_AdjustClientPositions.
void G_ResetMarkers (gentity_t *ent)
G_ResetMarkers.
static void G_AttachBodyParts (gentity_t *ent)
G_AttachBodyParts.
static void G_DettachBodyParts (void)
G_DettachBodyParts.
static int G_SwitchBodyPartEntity (gentity_t *ent)
G_SwitchBodyPartEntity.
void G_HistoricalTrace (gentity_t *ent, trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Run a trace with players in historical positions.
void G_HistoricalTraceBegin (gentity_t *ent)
G_HistoricalTraceBegin.
void G_HistoricalTraceEnd (gentity_t *ent)
G_HistoricalTraceEnd.
void G_Trace (gentity_t *ent, trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, qboolean ignoreCorpses)
Run a trace without fixups (historical fixups will be done externally)
qboolean G_SkipCorrectionSafe (gentity_t *ent)
G_SkipCorrectionSafe.
void G_PredictPmove (gentity_t *ent, float frametime)
Make use of the 'Pmove' functions to figure out where a player would have moved in the short amount of time indicated by frametime.
Variables
static grefEntity_t refent
Macro Definition Documentation
#define POSITION_READJUST
Value:
if (res != results->entityNum) {               \
        VectorSubtract(end, start, dir);          \
        VectorNormalizeFast(dir);             \
                                    \
        VectorMA(results->endpos, -1, dir, results->endpos);  \
        results->entityNum = res;               \
    }
Definition at line 681 of file g_antilag.c.
Referenced by G_HistoricalTrace(), and G_Trace().
Function Documentation
static void G_AdjustClientPositions (gentity_t * ent, int time, qboolean forward) static
G_AdjustClientPositions.
Parameters
[in] ent
[in] time
[in] forward
Definition at line 509 of file g_antilag.c.
Referenced by G_HistoricalTrace(), G_HistoricalTraceBegin(), and G_HistoricalTraceEnd().
static void G_AdjustSingleClientPosition (gentity_t * ent, int time) static
G_AdjustSingleClientPosition.
Parameters
[in,out] ent
[in] time
Definition at line 194 of file g_antilag.c.
Referenced by G_AdjustClientPositions().
static qboolean G_AntilagSafe (gentity_t * ent) static
G_AntilagSafe.
Parameters
[in] ent
Returns
Definition at line 71 of file g_antilag.c.
Referenced by G_AdjustSingleClientPosition(), G_ReAdjustSingleClientPosition(), and G_StoreClientPosition().
static void G_AttachBodyParts (gentity_t * ent) static
G_AttachBodyParts.
Parameters
[in] ent
Definition at line 613 of file g_antilag.c.
Referenced by G_HistoricalTrace(), and G_Trace().
static void G_DettachBodyParts (void) static
G_DettachBodyParts.
Definition at line 644 of file g_antilag.c.
Referenced by G_HistoricalTrace(), and G_Trace().
void G_HistoricalTrace (gentity_t * ent, trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Run a trace with players in historical positions.
Parameters
[in] ent
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 701 of file g_antilag.c.
Referenced by _et_G_HistoricalTrace(), Fire_Lead_Ext(), Weapon_Knife(), and Weapon_Syringe().
void G_HistoricalTraceBegin (gentity_t * ent)
G_HistoricalTraceBegin.
Parameters
[in] ent
Definition at line 767 of file g_antilag.c.
Referenced by Bullet_Fire().
void G_HistoricalTraceEnd (gentity_t * ent)
G_HistoricalTraceEnd.
Parameters
[in] ent
Definition at line 781 of file g_antilag.c.
Referenced by Bullet_Fire().
void G_PredictPmove (gentity_t * ent, float frametime)
Make use of the 'Pmove' functions to figure out where a player would have moved in the short amount of time indicated by frametime.
After the Pmove is complete, copy the values to the player's entity state, but then copy the original player state values back to the player state so that the player's movements aren't effected in any way.
The only Pmove functions used are PM_StepSlideMove() and PM_GroundTrace() since these are all that is needed for this short period of time. This means that a lot of movement types cannot be predicted and no prediction should be done for them See G_SkipCorrectionSafe()
Parameters
[in,out] ent
[in] frametime
Definition at line 960 of file g_antilag.c.
Referenced by ClientEndFrame().
void G_ReAdjustSingleClientPosition (gentity_t * ent)
G_ReAdjustSingleClientPosition.
Parameters
[in,out] ent
Definition at line 450 of file g_antilag.c.
Referenced by G_AdjustClientPositions(), IsHeadShot(), IsLegShot(), and player_die().
void G_ResetMarkers (gentity_t * ent)
G_ResetMarkers.
Parameters
[in,out] ent
Definition at line 544 of file g_antilag.c.
Referenced by ClientSpawn(), and TeleportPlayer().
qboolean G_SkipCorrectionSafe (gentity_t * ent)
G_SkipCorrectionSafe.
Parameters
[in] ent
Returns
Definition at line 872 of file g_antilag.c.
Referenced by G_PredictPmove().
void G_StoreClientPosition (gentity_t * ent)
G_StoreClientPosition.
Parameters
[in,out] ent
Definition at line 134 of file g_antilag.c.
Referenced by ClientEndFrame().
static int G_SwitchBodyPartEntity (gentity_t * ent) static
G_SwitchBodyPartEntity.
Parameters
[in] ent
Returns
Definition at line 668 of file g_antilag.c.
Referenced by G_HistoricalTrace(), and G_Trace().
void G_Trace (gentity_t * ent, trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, qboolean ignoreCorpses)
Run a trace without fixups (historical fixups will be done externally)
Parameters
[in] ent
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
[in] ignoreCorpses Skip corpses for bullet tracing (=non gibbing weapons)
Definition at line 803 of file g_antilag.c.
Referenced by Bullet_Fire_Extended().
static void TimeShiftLerp (vec3_t start, vec3_t end, float frac, vec3_t result) static
Used below to interpolate between two previous vectors.
Parameters
[in] start
[in] end
[in] frac
[out] result A vector "frac" times the distance between "start" and "end"
Definition at line 44 of file g_antilag.c.
Referenced by G_AdjustSingleClientPosition().
Variable Documentation
grefEntity_t refent static
Definition at line 607 of file g_antilag.c.
Referenced by CG_CalcMoveSpeeds(), CG_GetTag(), CG_GetWeaponTag(), ClientEndFrame(), ClientThink_real(), CopyToBodyQue(), R_CalcBones(), RB_MDM_SurfaceAnim(), RB_SurfaceAnim(), Tess_MDM_SurfaceAnim(), and Tess_SurfaceVBOMDMMesh().