ET: Legacy: src/game/g_alarm.c File Reference
g_alarm.c File Reference
#include "g_local.h"
Functions
void propExplosion (gentity_t *ent)
propExplosion
void alarmbox_updateparts (gentity_t *ent, qboolean matestoo)
alarmbox_updateparts
void alarmbox_use (gentity_t *ent, gentity_t *other, gentity_t *foo)
alarmbox_use
void alarmbox_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
alarmbox_die
void alarmbox_finishspawning (gentity_t *ent)
alarmbox_finishspawning
void SP_alarm_box (gentity_t *ent)
SP_alarm_box.
Function Documentation
void alarmbox_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
alarmbox_die
Parameters
[in,out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 156 of file g_alarm.c.
Referenced by SP_alarm_box().
void alarmbox_finishspawning (gentity_t * ent)
alarmbox_finishspawning
Parameters
[in] ent
Definition at line 169 of file g_alarm.c.
Referenced by SP_alarm_box().
void alarmbox_updateparts (gentity_t * ent, qboolean matestoo)
alarmbox_updateparts
Parameters
[in] ent
[in] matestoo
Definition at line 44 of file g_alarm.c.
Referenced by alarmbox_die(), alarmbox_finishspawning(), and alarmbox_use().
void alarmbox_use (gentity_t * ent, gentity_t * other, gentity_t * foo)
alarmbox_use
Parameters
[in,out] ent
[in] other
foo - unused
Definition at line 131 of file g_alarm.c.
Referenced by SP_alarm_box().
void propExplosion (gentity_t * ent)
propExplosion
Parameters
[in] ent
Definition at line 681 of file g_props.c.
Referenced by alarmbox_die(), Props_Barrel_Die(), props_radio_die(), and props_radio_dieSEVEN().
void SP_alarm_box (gentity_t * ent)
SP_alarm_box.
QUAKED alarm_box (1 0 1) START_ON You need to have an origin brush as part of this entity current alarm box model is (8 x 16 x 28) "health" defaults to 10
"noise" the sound to play over the system (this would be the siren sound)
START_ON means the button is pushed in, any dlights are cycling, and alarms are sounding
"team" key/value is valid for teamed alarm boxes teamed alarm_boxes work in tandem (switches/lights syncronize) target a box to dlights to have them activate/deactivate with the system (use a stylestring that matches the cycletime for the alarmbox sound) alarm sound locations are also placed in the dlights, so wherever you place an attached dlight, you will hear the alarm model: the model used is "models/mapobjects/electronics/alarmbox.md3" place the origin at the center of your trigger box
Parameters
[in,out] ent
Todo:
: temp
Definition at line 205 of file g_alarm.c.