ET: Legacy: src/game/g_active.c File Reference
g_active.c File Reference
#include "g_local.h"
#include "g_etbot_interface.h"
Macros
#define MIN_BURN_INTERVAL 399
#define UNDERWATER_DAMAGE 2
#define WR_PUSHAMOUNT 25
Functions
void P_DamageFeedback (gentity_t *player)
Called just before a snapshot is sent to the given player.
void P_WorldEffects (gentity_t *ent)
Check for lava/slime contents and drowning.
void G_SetClientSound (gentity_t *ent)
Disables sound looping in entity.
void PushBot (gentity_t *ent, gentity_t *other)
PushBot.
qboolean ReadyToCallArtillery (gentity_t *ent)
Does ent have enough "energy" to call artillery?
qboolean ReadyToConstruct (gentity_t *ent, gentity_t *constructible, qboolean updateState)
Are we ready to construct?
void ClientImpacts (gentity_t *ent, pmove_t *pm)
ClientImpacts.
void G_TouchTriggers (gentity_t *ent)
Find all trigger entities that ent's current position touches.
qboolean G_SpectatorAttackFollow (gentity_t *ent)
G_SpectatorAttackFollow.
void SpectatorThink (gentity_t *ent, usercmd_t *ucmd)
SpectatorThink.
qboolean ClientInactivityTimer (gclient_t *client)
g_inactivity and g_spectatorinactivity : Values have to be higher then 10 seconds, that is the time after the warn message is sent. (if it's lower than that value, it will not work at all)
void ClientTimerActions (gentity_t *ent, int msec)
Actions that happen once a second.
void ClientIntermissionThink (gclient_t *client)
ClientIntermissionThink.
void G_FallDamage (gentity_t *ent, int event)
G_FallDamage.
void ClientEvents (gentity_t *ent, int oldEventSequence)
Events will be passed on to the clients for presentation, but any server game effects are handled here.
void WolfFindMedic (gentity_t *self)
WolfFindMedic.
void ClientThink_real (gentity_t *ent, qboolean skipServerTime)
This will be called once for each client frame, which will usually be a couple times for each server frame on fast clients.
void ClientThink_cmd (gentity_t *ent, usercmd_t *cmd, qboolean skipServerTime)
etpro antiwarp
void ClientThink (int clientNum)
A new command has arrived from the client.
void G_RunClient (gentity_t *ent)
G_RunClient.
void SpectatorClientEndFrame (gentity_t *ent)
SpectatorClientEndFrame.
qboolean StuckInClient (gentity_t *self)
StuckInClient.
void WolfRevivePushEnt (gentity_t *self, gentity_t *other)
WolfRevivePushEnt.
void WolfReviveBbox (gentity_t *self)
WolfReviveBbox.
void ClientEndFrame (gentity_t *ent)
Called at the end of each server frame for each connected client A fast client will have multiple ClientThink for each ClientEndFrame, while a slow client may have multiple ClientEndFrame between ClientThink.
Variables
vec3_t playerMins
vec3_t playerMaxs
Macro Definition Documentation
#define MIN_BURN_INTERVAL 399
Definition at line 113 of file g_active.c.
Referenced by P_WorldEffects().
#define UNDERWATER_DAMAGE 2
Definition at line 114 of file g_active.c.
Referenced by P_WorldEffects().
#define WR_PUSHAMOUNT 25
Definition at line 1975 of file g_active.c.
Referenced by WolfRevivePushEnt().
Function Documentation
void ClientEndFrame (gentity_t * ent)
Called at the end of each server frame for each connected client A fast client will have multiple ClientThink for each ClientEndFrame, while a slow client may have multiple ClientEndFrame between ClientThink.
Parameters
[in,out] ent Entity
Definition at line 2087 of file g_active.c.
Referenced by ClientSpawn(), and G_RunFrame().
void ClientEvents (gentity_t * ent, int oldEventSequence)
Events will be passed on to the clients for presentation, but any server game effects are handled here.
Parameters
[in] ent Pointer to Entity
oldEventSequence Old event sequence number
Definition at line 975 of file g_active.c.
Referenced by ClientThink_real().
void ClientImpacts (gentity_t * ent, pmove_t * pm)
ClientImpacts.
Parameters
[in] ent Entity
[in] pm Player Move
Definition at line 364 of file g_active.c.
Referenced by ClientThink_real().
qboolean ClientInactivityTimer (gclient_t * client)
g_inactivity and g_spectatorinactivity : Values have to be higher then 10 seconds, that is the time after the warn message is sent. (if it's lower than that value, it will not work at all)
Parameters
[in,out] client Client
Returns
Returns qfalse if the client is dropped
Definition at line 714 of file g_active.c.
Referenced by ClientThink_real().
void ClientIntermissionThink (gclient_t * client)
ClientIntermissionThink.
Parameters
[in,out] client Client
Definition at line 895 of file g_active.c.
Referenced by ClientThink_real().
void ClientThink (int clientNum)
A new command has arrived from the client.
Parameters
[in] clientNum Client Number from 0 to MAX_CLIENTS
Definition at line 1644 of file g_active.c.
Referenced by ClientSpawn(), and vmMain().
void ClientThink_cmd (gentity_t * ent, usercmd_t * cmd, qboolean skipServerTime)
etpro antiwarp
Author
zinx
Parameters
[in,out] ent Entity
[in] cmd User Command
Definition at line 1633 of file g_active.c.
Referenced by ClientThink(), and DoClientThinks().
void ClientThink_real (gentity_t * ent, qboolean skipServerTime)
This will be called once for each client frame, which will usually be a couple times for each server frame on fast clients.
If "g_synchronousClients 1" is set, this will be called exactly once for each server frame, which makes for smooth demo recording.
Parameters
[in,out] ent Entity
Todo:
:? MP method (causes problems for us. activate 'sticks')
Todo:
:? MP method
Definition at line 1149 of file g_active.c.
Referenced by ClientThink_cmd().
void ClientTimerActions (gentity_t * ent, int msec)
Actions that happen once a second.
Parameters
[in,out] ent Entity
msec Scheduler time
Definition at line 850 of file g_active.c.
Referenced by ClientThink_real().
void G_FallDamage (gentity_t * ent, int event)
G_FallDamage.
Parameters
[in,out] ent
[in] event
Definition at line 915 of file g_active.c.
Referenced by ClientEvents().
void G_RunClient (gentity_t * ent)
G_RunClient.
Parameters
[in,out] ent Entity
Definition at line 1672 of file g_active.c.
Referenced by G_RunEntity().
void G_SetClientSound (gentity_t * ent)
Disables sound looping in entity.
Parameters
[in,out] ent Entity
Definition at line 224 of file g_active.c.
Referenced by ClientEndFrame().
qboolean G_SpectatorAttackFollow (gentity_t * ent)
G_SpectatorAttackFollow.
Parameters
ent
Returns
true if a player was found to follow, otherwise false
Definition at line 511 of file g_active.c.
Referenced by SpectatorThink().
void G_TouchTriggers (gentity_t * ent)
Find all trigger entities that ent's current position touches.
Parameters
[in,out] ent Entity
Spectators will only interact with teleporters.
Definition at line 417 of file g_active.c.
Referenced by ClientEndFrame(), ClientThink_real(), and SpectatorThink().
void P_DamageFeedback (gentity_t * player)
Called just before a snapshot is sent to the given player.
Totals up all damage and generates both the player_state_t damage values to that client for pain blends and kicks, and global pain sound events for all clients.
Parameters
[in,out] player Player Entity
Definition at line 54 of file g_active.c.
Referenced by ClientEndFrame().
void P_WorldEffects (gentity_t * ent)
Check for lava/slime contents and drowning.
Parameters
[in,out] ent Entity
Definition at line 120 of file g_active.c.
Referenced by ClientEndFrame().
void PushBot (gentity_t * ent, gentity_t * other)
PushBot.
Parameters
[in] ent
[in] other
Definition at line 235 of file g_active.c.
Referenced by ClientImpacts().
qboolean ReadyToCallArtillery (gentity_t * ent)
Does ent have enough "energy" to call artillery?
Parameters
[in] ent Entity
Definition at line 281 of file g_active.c.
Referenced by Weapon_Artillery().
qboolean ReadyToConstruct (gentity_t * ent, gentity_t * constructible, qboolean updateState)
Are we ready to construct?
Parameters
[in,out] ent Entity
[in] constructible Constructible Entity
[in] updateState Do we want to update Entity weapon time?
Optionally, will also update the time while we are constructing
Definition at line 306 of file g_active.c.
Referenced by TryConstructing().
void SpectatorClientEndFrame (gentity_t * ent)
SpectatorClientEndFrame.
Parameters
[in,out] ent Spectator Entity
Definition at line 1707 of file g_active.c.
Referenced by ClientEndFrame().
void SpectatorThink (gentity_t * ent, usercmd_t * ucmd)
SpectatorThink.
Parameters
[in,out] ent
[in] ucmd
Todo:
: WBUTTON_ATTACK2
Definition at line 553 of file g_active.c.
Referenced by ClientThink_real().
qboolean StuckInClient (gentity_t * self)
StuckInClient.
Parameters
[in,out] self Current Player Entity
Returns
Definition at line 1921 of file g_active.c.
Referenced by ClientEndFrame().
void WolfFindMedic (gentity_t * self)
WolfFindMedic.
Parameters
[in,out] self Current Player Entity
Definition at line 1064 of file g_active.c.
Referenced by ClientThink_real().
void WolfReviveBbox (gentity_t * self)
WolfReviveBbox.
Parameters
[in,out] self Current Player Entity
Note
Completely revived for capsules
Definition at line 2016 of file g_active.c.
Referenced by ClientEndFrame().
void WolfRevivePushEnt (gentity_t * self, gentity_t * other)
WolfRevivePushEnt.
Parameters
[in,out] self
[in,out] other
Definition at line 1982 of file g_active.c.
Referenced by WolfReviveBbox().
Variable Documentation
vec3_t playerMaxs
Definition at line 54 of file g_client.c.
Referenced by StuckInClient(), and WolfReviveBbox().
vec3_t playerMins
Definition at line 53 of file g_client.c.
Referenced by StuckInClient(), and WolfReviveBbox().