ET: Legacy: src/game/g_config.c File Reference
g_config.c File Reference
Config/Mode settings.
#include "g_local.h"
Functions
static qboolean G_ConfigError (int handle, const char *format,...)
G_ConfigError.
void G_PrintConfigs (gentity_t *ent)
G_PrintConfigs.
qboolean G_isValidConfig (gentity_t *ent, const char *configname)
Checks if config file is in paths (used before initiating a vote for configs)
qboolean G_ParseSettings (int handle, qboolean setvars, config_t *config)
G_ParseSettings.
qboolean G_ParseMapSettings (int handle, config_t *config)
G_ParseMapSettings.
void G_configLoadAndSet (const char *name)
G_configLoadAndSet.
qboolean G_configSet (const char *configname)
Force settings to predefined state.
void G_ConfigCheckLocked (void)
G_ConfigCheckLocked.
void G_ReloadConfig (void)
G_ReloadConfig.
Detailed Description
Config/Mode settings.
Definition in file g_config.c.
Function Documentation
void G_ConfigCheckLocked (void)
G_ConfigCheckLocked.
Todo:
: check for anything else?
Definition at line 516 of file g_config.c.
Referenced by G_RunFrame().
static qboolean G_ConfigError (int handle, const char * format, ...) static
G_ConfigError.
Parameters
[in] handle
[in] format
Returns
Definition at line 44 of file g_config.c.
Referenced by G_ParseMapSettings(), and G_ParseSettings().
void G_configLoadAndSet (const char * name)
G_configLoadAndSet.
Parameters
[in] name
Definition at line 347 of file g_config.c.
Referenced by G_configSet().
qboolean G_configSet (const char * configname)
Force settings to predefined state.
Parameters
[in] configname
Returns
Todo:
: handle the mapscript hash and run the map script
Definition at line 463 of file g_config.c.
Referenced by CC_loadconfig(), G_Config_v(), G_InitGame(), and G_ReloadConfig().
qboolean G_isValidConfig (gentity_t * ent, const char * configname)
Checks if config file is in paths (used before initiating a vote for configs)
Parameters
[in] ent
[in] configname
Definition at line 102 of file g_config.c.
Referenced by G_Config_v().
qboolean G_ParseMapSettings (int handle, config_t * config)
G_ParseMapSettings.
Parameters
[in] handle
[in] config
Returns
Todo:
: handle this properly..
Definition at line 273 of file g_config.c.
Referenced by G_configLoadAndSet().
qboolean G_ParseSettings (int handle, qboolean setvars, config_t * config)
G_ParseSettings.
Parameters
[in] handle
[in] setvars
[in] config
Returns
FIXME: - this parser requires quotes set for values (negative values are causing issues)
map names with numbers in name (at start?!) have issues see legacy1.config map 1v1dm rewrite parser by using bg tools ...
Definition at line 139 of file g_config.c.
Referenced by G_configLoadAndSet(), and G_ParseMapSettings().
void G_PrintConfigs (gentity_t * ent)
G_PrintConfigs.
Parameters
[in] ent
Definition at line 70 of file g_config.c.
Referenced by G_Config_v().
void G_ReloadConfig (void)
G_ReloadConfig.
Definition at line 552 of file g_config.c.