ET: Legacy: src/game/g_cmds_ext.c File Reference
g_cmds_ext.c File Reference
Extended command set handling.
#include "g_local.h"
#include "../../etmain/ui/menudef.h"
Data Structures
struct cmd_reference_t
Functions
qboolean G_commandCheck (gentity_t *ent, const char *cmd, qboolean fDoAnytime)
G_commandCheck.
qboolean G_commandHelp (gentity_t *ent, const char *pszCommand, unsigned int dwCommand)
Prints specific command help info.
qboolean G_cmdDebounce (gentity_t *ent, const char *pszCommand)
Debounces cmd request as necessary.
void G_noTeamControls (gentity_t *ent)
G_noTeamControls.
void G_commands_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Lists server commands.
void G_lock_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team.
void G_pause_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fPause)
Pause/unpause a match.
void G_players_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Show client info.
void G_ready_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Sets a player's "ready" status.
void G_say_teamnl_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Team chat w/no location info.
void G_sclogin_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Request for shoutcaster status.
void G_sclogout_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Removes shoutcaster status.
void G_makesc_cmd (void)
Set shoutcaster command.
void G_removesc_cmd (void)
Remove shoutcaster command.
void G_scores_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Shows match stats to the requesting client.
void G_specinvite_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fLock)
Sends an invitation to a player to spectate a team.
void G_speclock_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team from spectators.
void G_weaponStats_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Shows a player's stats to the requesting client.
void G_statsall_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Shows all players' stats to the requesting client.
void G_teamready_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Sets a player's team "ready" status.
int QDECL SortStats (const void *a, const void *b)
Gives back overall or specific weapon rankings.
void G_weaponStatsLeaders_cmd (gentity_t *ent, qboolean doTop, qboolean doWindow)
Shows the most accurate players for each weapon to the requesting client.
void G_weaponRankings_cmd (gentity_t *ent, unsigned int dwCommand, qboolean state)
Shows best/worst accuracy for all weapons, or sorted accuracies for a single weapon.
Variables
int iWeap = WS_MAX
const char * lock_status [2] = { "unlock", "lock" }
static const cmd_reference_t aCommandInfo []
const unsigned int cQualifyingShots [WS_MAX]
Detailed Description
Extended command set handling.
Definition in file g_cmds_ext.c.
Function Documentation
qboolean G_cmdDebounce (gentity_t * ent, const char * pszCommand)
Debounces cmd request as necessary.
Parameters
[in,out] ent
[in] pszCommand
Returns
Definition at line 174 of file g_cmds_ext.c.
Referenced by G_lock_cmd(), G_pause_cmd(), G_ready_cmd(), G_refPause_cmd(), G_specinvite_cmd(), G_speclock_cmd(), and G_teamready_cmd().
qboolean G_commandCheck (gentity_t * ent, const char * cmd, qboolean fDoAnytime)
G_commandCheck.
Parameters
[in] ent
[in] cmd
[in] fDoAnytime
Returns
Definition at line 118 of file g_cmds_ext.c.
Referenced by ClientCommand().
qboolean G_commandHelp (gentity_t * ent, const char * pszCommand, unsigned int dwCommand)
Prints specific command help info.
Parameters
[in] ent
[in] pszCommand
[in] dwCommand
Returns
Definition at line 150 of file g_cmds_ext.c.
Referenced by G_commandCheck(), and G_weaponRankings_cmd().
void G_commands_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Lists server commands.
Parameters
ent - unused
dwCommand - unused
fValue - unused
Definition at line 208 of file g_cmds_ext.c.
void G_lock_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team.
Parameters
[in] ent
[in] dwCommand
[in] fLock
Definition at line 257 of file g_cmds_ext.c.
void G_makesc_cmd (void)
Set shoutcaster command.
Definition at line 715 of file g_cmds_ext.c.
void G_noTeamControls (gentity_t * ent)
G_noTeamControls.
Parameters
ent - unused
Definition at line 191 of file g_cmds_ext.c.
Referenced by G_lock_cmd(), G_pause_cmd(), G_specinvite_cmd(), and G_speclock_cmd().
void G_pause_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fPause)
Pause/unpause a match.
Parameters
[in] ent
[in] dwCommand
[in] fPause
Definition at line 298 of file g_cmds_ext.c.
void G_players_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Show client info.
Parameters
[in] ent
dwCommand - unused
fDump - unused
Definition at line 376 of file g_cmds_ext.c.
void G_ready_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Sets a player's "ready" status.
Parameters
[in,out] ent
[in] dwCommand
[in] fDump
Definition at line 561 of file g_cmds_ext.c.
void G_removesc_cmd (void)
Remove shoutcaster command.
Definition at line 777 of file g_cmds_ext.c.
void G_say_teamnl_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Team chat w/no location info.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 628 of file g_cmds_ext.c.
void G_sclogin_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Request for shoutcaster status.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 639 of file g_cmds_ext.c.
void G_sclogout_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Removes shoutcaster status.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 686 of file g_cmds_ext.c.
void G_scores_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Shows match stats to the requesting client.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 833 of file g_cmds_ext.c.
void G_specinvite_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fLock)
Sends an invitation to a player to spectate a team.
Parameters
[in] ent
[in] dwCommand
fLock - unused
Definition at line 844 of file g_cmds_ext.c.
void G_speclock_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team from spectators.
Parameters
[in] ent
[in] dwCommand
[in] fLock
Definition at line 911 of file g_cmds_ext.c.
void G_statsall_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Shows all players' stats to the requesting client.
Parameters
ent
dwCommand - unused
fDump - unused
Definition at line 963 of file g_cmds_ext.c.
Referenced by G_matchInfoDump().
void G_teamready_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Sets a player's team "ready" status.
Parameters
[in] ent
[in] dwCommand
fDump - unused
Definition at line 985 of file g_cmds_ext.c.
void G_weaponRankings_cmd (gentity_t * ent, unsigned int dwCommand, qboolean state)
Shows best/worst accuracy for all weapons, or sorted accuracies for a single weapon.
Parameters
[in] ent
[in] dwCommand
[in] state
Definition at line 1192 of file g_cmds_ext.c.
void G_weaponStats_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Shows a player's stats to the requesting client.
Parameters
[in] ent
dwCommand - unused
fDump - unused
Definition at line 952 of file g_cmds_ext.c.
void G_weaponStatsLeaders_cmd (gentity_t * ent, qboolean doTop, qboolean doWindow)
Shows the most accurate players for each weapon to the requesting client.
Parameters
ent - unused
[in] doTop
[in] doWindow
Definition at line 1123 of file g_cmds_ext.c.
Referenced by ClientCommand(), and G_weaponRankings_cmd().
int QDECL SortStats (const void * a, const void * b)
Gives back overall or specific weapon rankings.
Parameters
[in] a
[in] b
Returns
Definition at line 1070 of file g_cmds_ext.c.
Referenced by G_weaponRankings_cmd().
Variable Documentation
const cmd_reference_t aCommandInfo[] static
Definition at line 57 of file g_cmds_ext.c.
Referenced by G_commandCheck(), and G_commands_cmd().
const unsigned int cQualifyingShots[WS_MAX]
Initial value:
=
{
    10,
    10,
    15,
    15,
    30,
    30,
    30,
    30,
    3,
    3,
    100,
    5,
    5,
    5,
    5,
    3,
    3,
    3,
    5,
    10,
    100,
    100,
    30,
    30,
    30,
    30,
    30,
}
Definition at line 1033 of file g_cmds_ext.c.
Referenced by G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), and SortStats().
int iWeap = WS_MAX
Definition at line 39 of file g_cmds_ext.c.
Referenced by CG_parseBestShotsStats_cmd(), CG_parseTopShotsStats_cmd(), CG_topshotsParse_cmd(), G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), and SortStats().
const char* lock_status[2] = { "unlock", "lock" }
Definition at line 41 of file g_cmds_ext.c.
Referenced by G_lock_cmd(), and G_speclock_cmd().