ET: Legacy: src/game/g_client.c File Reference
g_client.c File Reference
Client functions that don't happen every frame.
#include "g_local.h"
#include "../../etmain/ui/menudef.h"
#include "g_strparse.h"
#include "g_etbot_interface.h"
#include "g_lua.h"
Macros
#define MAX_SPAWN_POINTS 128
Functions
void SP_info_player_deathmatch (gentity_t *ent)
QUAKED info_player_deathmatch (1 0 1) (-18 -18 -24) (18 18 48) potential spawning position for deathmatch games. Targets will be fired when someone spawns in on them. "nobots" will prevent bots from using this spot. "nohumans" will prevent non-bots from using this spot.
void SP_info_player_checkpoint (gentity_t *ent)
QUAKED info_player_checkpoint (1 0 0) (-16 -16 -24) (16 16 32) a b c d these are start points /after/ the level start the letter (a b c d) designates the checkpoint that needs to be complete in order to use this start position.
void SP_info_player_start (gentity_t *ent)
QUAKED info_player_start (1 0 0) (-18 -18 -24) (18 18 48) equivelant to info_player_deathmatch.
void SP_info_player_intermission (gentity_t *ent)
QUAKED info_player_intermission (1 0 1) (-16 -16 -24) (16 16 32) AXIS ALLIED The intermission will be viewed from this point. Target an info_notnull for the view direction.
qboolean SpotWouldTelefrag (gentity_t *spot)
SpotWouldTelefrag.
gentity_t * SelectNearestDeathmatchSpawnPoint (vec3_t from)
Find the spot that we DON'T want to use.
gentity_t * SelectRandomDeathmatchSpawnPoint (void)
Go to a random point that doesn't telefrag.
gentity_t * SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles)
Chooses a player start, deathmatch start, etc.
gentity_t * SelectSpectatorSpawnPoint (vec3_t origin, vec3_t angles)
SelectSpectatorSpawnPoint.
void InitBodyQue (void)
InitBodyQue.
void BodyUnlink (gentity_t *ent)
Called by BodySink.
void G_BodyDP (gentity_t *ent)
G_BodyDP.
void BodySink2 (gentity_t *ent)
After sitting around for five seconds, fall into the ground and dissapear.
void BodySink (gentity_t *ent)
After sitting around for five seconds, fall into the ground and dissapear.
void CopyToBodyQue (gentity_t *ent)
A player is respawning, so make an entity that looks just like the existing corpse to leave behind.
void SetClientViewAngle (gentity_t *ent, vec3_t angle)
SetClientViewAngle.
void G_DropLimboHealth (gentity_t *ent)
G_DropLimboHealth.
void G_DropLimboAmmo (gentity_t *ent)
G_DropLimboAmmo.
void limbo (gentity_t *ent, qboolean makeCorpse)
limbo
void reinforce (gentity_t *ent)
Called when time expires for a team deployment cycle and there is at least one guy ready to go.
void respawn (gentity_t *ent)
respawn
int TeamCount (int ignoreClientNum, team_t team)
Count the number of players on a team.
team_t PickTeam (int ignoreClientNum)
PickTeam.
static void AddExtraSpawnAmmo (gclient_t *client, weapon_t weaponNum)
AddExtraSpawnAmmo.
void AddWeaponToPlayer (gclient_t *client, weapon_t weapon, int ammo, int ammoclip, qboolean setcurrent)
AddWeaponToPlayer.
void SetWolfSpawnWeapons (gclient_t *client)
SetWolfSpawnWeapons.
int G_CountTeamMedics (team_t team, qboolean alivecheck)
G_CountTeamMedics.
void AddMedicTeamBonus (gclient_t *client)
AddMedicTeamBonus.
int G_CountTeamFieldops (team_t team)
G_CountTeamFieldops.
static void ClientCleanName (const char *in, char *out, size_t outSize)
ClientCleanName.
const char * GetParsedIP (const char *ipadd)
GetParsedIP.
char * CheckUserinfo (int clientNum, char *userinfo)
Based on userinfocheck.lua and combinedfixes.lua.
void ClientUserinfoChanged (int clientNum)
Called from ClientConnect when the player first connects and directly by the server system when the player updates a userinfo variable.
char * ClientConnect (int clientNum, qboolean firstTime, qboolean isBot)
Called when a player begins connecting to the server. Called again for every map change or tournement restart.
int G_ComputeMaxLives (gclient_t *cl, int maxRespawns)
Scaling for late-joiners of maxlives based on current game time.
void ClientBegin (int clientNum)
Called when a client has finished connecting, and is ready to be placed into the level. This will happen every level load, and on transition between teams, but doesn't happen on respawns.
static qboolean isMortalSelfDamage (gentity_t *ent)
void ClientSpawn (gentity_t *ent, qboolean revived, qboolean teamChange, qboolean restoreHealth)
Called every time a client is placed fresh in the world: after the first ClientBegin, and after each respawn Initializes all non-persistant parts of playerState.
void ClientDisconnect (int clientNum)
Called when a player drops from the server. Will not be called between levels.
void ClientStoreSurfaceFlags (int clientNum, int surfaceFlags)
In just the GAME DLL, we want to store the groundtrace surface stuff, so we don't have to keep tracing.
float ClientHitboxMaxZ (gentity_t *hitEnt)
ClientHitboxMaxZ.
Variables
vec3_t playerMins = { -18, -18, -24 }
vec3_t playerMaxs = { 18, 18, 48 }
const char * country_name [MAX_COUNTRY_NUM]
Detailed Description
Client functions that don't happen every frame.
Definition in file g_client.c.
Macro Definition Documentation
#define MAX_SPAWN_POINTS 128
Definition at line 184 of file g_client.c.
Referenced by SelectRandomDeathmatchSpawnPoint().
Function Documentation
static void AddExtraSpawnAmmo (gclient_t * client, weapon_t weaponNum) static
AddExtraSpawnAmmo.
Parameters
[in,out] client
[in] weaponNum
Definition at line 1020 of file g_client.c.
Referenced by AddWeaponToPlayer().
void AddMedicTeamBonus (gclient_t * client)
AddMedicTeamBonus.
Parameters
[in,out] client
Definition at line 1329 of file g_client.c.
Referenced by ClientSpawn().
void AddWeaponToPlayer (gclient_t * client, weapon_t weapon, int ammo, int ammoclip, qboolean setcurrent)
AddWeaponToPlayer.
Parameters
[in,out] client
[in] weapon
[in] ammo
[in] ammoclip
[in] setcurrent
Definition at line 1090 of file g_client.c.
Referenced by G_SetPlayerSkill(), G_UpgradeSkill(), and SetWolfSpawnWeapons().
void BodySink (gentity_t * ent)
After sitting around for five seconds, fall into the ground and dissapear.
Parameters
[in,out] ent
Definition at line 365 of file g_client.c.
Referenced by CopyToBodyQue().
void BodySink2 (gentity_t * ent)
After sitting around for five seconds, fall into the ground and dissapear.
Parameters
[in,out] ent
Definition at line 339 of file g_client.c.
Referenced by BodySink().
void BodyUnlink (gentity_t * ent)
Called by BodySink.
Parameters
[in,out] ent
Definition at line 306 of file g_client.c.
Referenced by BodySink2().
char* CheckUserinfo (int clientNum, char * userinfo)
Based on userinfocheck.lua and combinedfixes.lua.
Parameters
clientNum - unused
[in] userinfo
Returns
Note
FIXME: IP6
Todo:
: replace ?
Definition at line 1512 of file g_client.c.
Referenced by ClientUserinfoChanged().
void ClientBegin (int clientNum)
Called when a client has finished connecting, and is ready to be placed into the level. This will happen every level load, and on transition between teams, but doesn't happen on respawns.
Parameters
[in] clientNum
Definition at line 2357 of file g_client.c.
Referenced by G_shuffleTeamsXP(), G_swapTeams(), SetTeam(), SpectatorClientEndFrame(), and vmMain().
static void ClientCleanName (const char * in, char * out, size_t outSize) static
ClientCleanName.
Parameters
[in] in
[out] out
[in] outSize
Definition at line 1384 of file g_client.c.
Referenced by ClientUserinfoChanged().
char* ClientConnect (int clientNum, qboolean firstTime, qboolean isBot)
Called when a player begins connecting to the server. Called again for every map change or tournement restart.
The session information will be valid after exit.
Return NULL if the client should be allowed, otherwise return a string with the reason for denial.
Otherwise, the client will be sent the current gamestate and will eventually get to ClientBegin.
Parameters
[in] clientNum
[in] firstTime will be qtrue the very first time a client connects to the server machine, but qfalse on map changes and tournement restarts.
[in] isBot
Returns
NULL if the client should be allowed, otherwise return a string with the reason for denial.
Definition at line 2007 of file g_client.c.
Referenced by ETInterface::AddBot(), and vmMain().
void ClientDisconnect (int clientNum)
Called when a player drops from the server. Will not be called between levels.
This should NOT be called directly by any game logic, call trap_DropClient(), which will call this and do server system housekeeping.
Parameters
[in] clientNum
Todo:
: find a new sound?
Definition at line 3127 of file g_client.c.
Referenced by ClientConnect(), and vmMain().
float ClientHitboxMaxZ (gentity_t * hitEnt)
ClientHitboxMaxZ.
Parameters
[in] hitEnt
Returns
the proper value to use for the entity's r.maxs[2] when running a trace.
Definition at line 3333 of file g_client.c.
Referenced by Bullet_Fire_Extended(), ClientEndFrame(), ClientThink_real(), G_DrawEntBBox(), G_HistoricalTrace(), and G_Trace().
void ClientSpawn (gentity_t * ent, qboolean revived, qboolean teamChange, qboolean restoreHealth)
Called every time a client is placed fresh in the world: after the first ClientBegin, and after each respawn Initializes all non-persistant parts of playerState.
Parameters
[in,out] ent
[in] revived
[in] teamChange
[in] restoreHealth
Definition at line 2708 of file g_client.c.
Referenced by ClientBegin(), Cmd_UnIgnore_f(), respawn(), and ReviveEntity().
void ClientStoreSurfaceFlags (int clientNum, int surfaceFlags)
In just the GAME DLL, we want to store the groundtrace surface stuff, so we don't have to keep tracing.
Parameters
[in] clientNum
[in] surfaceFlags
Definition at line 3322 of file g_client.c.
Referenced by PM_FootstepForSurface().
void ClientUserinfoChanged (int clientNum)
Called from ClientConnect when the player first connects and directly by the server system when the player updates a userinfo variable.
The game can override any of the settings and call trap_SetUserinfo if desired.
Parameters
[in] clientNum
Todo:
: move other userinfo flag settings in here
Todo:
: Gordon: wont this break if medals > 9 arnout?
Definition at line 1669 of file g_client.c.
Referenced by _et_ClientUserinfoChanged(), ClientConnect(), ClientDisconnect(), ClientSpawn(), Cmd_Give_f(), Cmd_ResetSetup_f(), Cmd_Team_f(), Do_Activate2_f(), G_LogExit(), G_MakeReferee(), G_MakeShoutcaster(), G_Mute_v(), G_MuteClient(), G_ref_cmd(), G_Referee_v(), G_refLogout_cmd(), G_refMute_cmd(), G_RemoveAllShoutcasters(), G_RemoveReferee(), G_RemoveShoutcaster(), G_ResetXP(), G_SetClientWeapons(), G_shuffleTeamsXP(), G_swapTeams(), G_UnMute_v(), G_UnMuteClient(), G_Unreferee_v(), G_UpgradeSkill(), ETInterface::InterfaceSendMessage(), SetTeam(), and vmMain().
void CopyToBodyQue (gentity_t * ent)
A player is respawning, so make an entity that looks just like the existing corpse to leave behind.
Parameters
[in] ent
Definition at line 514 of file g_client.c.
Referenced by limbo().
void G_BodyDP (gentity_t * ent)
G_BodyDP.
Parameters
[in,out] ent
Definition at line 323 of file g_client.c.
Referenced by BodySink2().
int G_ComputeMaxLives (gclient_t * cl, int maxRespawns)
Scaling for late-joiners of maxlives based on current game time.
Parameters
cl - unused
[in] maxRespawns
Returns
Definition at line 2326 of file g_client.c.
Referenced by ClientBegin().
int G_CountTeamFieldops (team_t team)
G_CountTeamFieldops.
Parameters
[in] team
[in] alivecheck
Returns
Definition at line 1353 of file g_client.c.
Referenced by G_MaxAvailableAirstrikes(), and G_MaxAvailableArtillery().
int G_CountTeamMedics (team_t team, qboolean alivecheck)
G_CountTeamMedics.
Parameters
[in] team
[in] alivecheck
Returns
Definition at line 1287 of file g_client.c.
Referenced by AddMedicTeamBonus(), and player_die().
void G_DropLimboAmmo (gentity_t * ent)
G_DropLimboAmmo.
Parameters
[in,out] ent
Definition at line 739 of file g_client.c.
Referenced by limbo().
void G_DropLimboHealth (gentity_t * ent)
G_DropLimboHealth.
Parameters
[in,out] ent
Definition at line 698 of file g_client.c.
Referenced by limbo().
const char* GetParsedIP (const char * ipadd)
GetParsedIP.
Parameters
[in] ipadd
Returns
Todo:
FIXME: IP6
Note
Courtesy of Dens
Definition at line 1473 of file g_client.c.
Referenced by CheckUserinfo().
void InitBodyQue (void)
InitBodyQue.
Definition at line 281 of file g_client.c.
Referenced by G_InitGame().
static qboolean isMortalSelfDamage (gentity_t * ent) static
Definition at line 2689 of file g_client.c.
Referenced by ClientSpawn().
void limbo (gentity_t * ent, qboolean makeCorpse)
limbo
Parameters
[in,out] ent
[in] makeCorpse
Definition at line 787 of file g_client.c.
Referenced by ClientBegin(), ClientCommand(), ClientThink_real(), Cmd_Kill_f(), Cmd_UnIgnore_f(), G_Damage(), ETInterface::InterfaceSendMessage(), player_die(), and SetTeam().
team_t PickTeam (int ignoreClientNum)
PickTeam.
Parameters
[in] ignoreClientNum
Returns
Definition at line 995 of file g_client.c.
Referenced by G_TeamDataForString().
void reinforce (gentity_t * ent)
Called when time expires for a team deployment cycle and there is at least one guy ready to go.
Parameters
[in,out] ent
Definition at line 901 of file g_client.c.
Referenced by SpectatorClientEndFrame().
void respawn (gentity_t * ent)
respawn
Parameters
[in,out] ent
Definition at line 931 of file g_client.c.
Referenced by reinforce(), and Touch_Item().
gentity_t* SelectNearestDeathmatchSpawnPoint (vec3_t from)
Find the spot that we DON'T want to use.
Parameters
[in] from
Returns
Definition at line 165 of file g_client.c.
Referenced by SelectSpawnPoint().
gentity_t* SelectRandomDeathmatchSpawnPoint (void)
Go to a random point that doesn't telefrag.
Returns
Definition at line 190 of file g_client.c.
Referenced by SelectSpawnPoint().
gentity_t* SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles)
Chooses a player start, deathmatch start, etc.
Parameters
[in] avoidPoint
[in] origin
[in] angles
Returns
Definition at line 224 of file g_client.c.
Referenced by FindIntermissionPoint(), and SelectCTFSpawnPoint().
gentity_t* SelectSpectatorSpawnPoint (vec3_t origin, vec3_t angles)
SelectSpectatorSpawnPoint.
Parameters
[out] origin
[out] angles
Returns
Definition at line 262 of file g_client.c.
Referenced by ClientSpawn().
void SetClientViewAngle (gentity_t * ent, vec3_t angle)
SetClientViewAngle.
Parameters
[in,out] ent
[in] angle
Definition at line 679 of file g_client.c.
Referenced by ClientSpawn(), Cmd_UnIgnore_f(), StopFollowing(), TeleportPlayer(), and ETInterface::UpdateBotInput().
void SetWolfSpawnWeapons (gclient_t * client)
SetWolfSpawnWeapons.
Parameters
[in,out] client
Definition at line 1156 of file g_client.c.
Referenced by ClientSpawn(), and G_ResetXP().
void SP_info_player_checkpoint (gentity_t * ent)
QUAKED info_player_checkpoint (1 0 0) (-16 -16 -24) (16 16 32) a b c d these are start points /after/ the level start the letter (a b c d) designates the checkpoint that needs to be complete in order to use this start position.
Parameters
[in] ent
Definition at line 99 of file g_client.c.
void SP_info_player_deathmatch (gentity_t * ent)
QUAKED info_player_deathmatch (1 0 1) (-18 -18 -24) (18 18 48) potential spawning position for deathmatch games. Targets will be fired when someone spawns in on them. "nobots" will prevent bots from using this spot. "nohumans" will prevent non-bots from using this spot.
If the start position is targeting an entity, the players camera will start out facing that ent (like an info_notnull)
Parameters
[in,out] ent
Definition at line 67 of file g_client.c.
Referenced by SP_info_player_checkpoint(), and SP_info_player_start().
void SP_info_player_intermission (gentity_t * ent)
QUAKED info_player_intermission (1 0 1) (-16 -16 -24) (16 16 32) AXIS ALLIED The intermission will be viewed from this point. Target an info_notnull for the view direction.
Parameters
ent - unused
Definition at line 122 of file g_client.c.
void SP_info_player_start (gentity_t * ent)
QUAKED info_player_start (1 0 0) (-18 -18 -24) (18 18 48) equivelant to info_player_deathmatch.
Parameters
ent
Definition at line 110 of file g_client.c.
qboolean SpotWouldTelefrag (gentity_t * spot)
SpotWouldTelefrag.
Parameters
[in] spot
Returns
Definition at line 137 of file g_client.c.
Referenced by ClientBegin(), SelectRandomDeathmatchSpawnPoint(), and SelectRandomTeamSpawnPoint().
int TeamCount (int ignoreClientNum, team_t team)
Count the number of players on a team.
Parameters
[in] ignoreClientNum
[in] team
Returns
Number of players on a team
Definition at line 971 of file g_client.c.
Referenced by ETInterface::ChangeClass(), ETInterface::ChangeTeam(), Cmd_Follow_f(), G_allowFollow(), G_printMatchInfo(), G_refLockTeams_cmd(), G_refPlayerPut_cmd(), G_refSpeclockTeams_cmd(), G_TeamDataForString(), G_teamJoinCheck(), G_verifyMatchState(), PickTeam(), and SetTeam().
Variable Documentation
const char* country_name[MAX_COUNTRY_NUM]
Definition at line 43 of file geoip.c.
Referenced by ClientConnect(), and ClientUserinfoChanged().
vec3_t playerMaxs = { 18, 18, 48 }
Definition at line 54 of file g_client.c.
Referenced by ClientSpawn(), Cmd_SetViewpos_f(), G_LeaveTank(), SpotWouldTelefrag(), StuckInClient(), and WolfReviveBbox().
vec3_t playerMins = { -18, -18, -24 }
Definition at line 53 of file g_client.c.
Referenced by ClientSpawn(), Cmd_SetViewpos_f(), G_LeaveTank(), SpotWouldTelefrag(), StuckInClient(), and WolfReviveBbox().