ET: Legacy: src/game/g_combat.c File Reference
g_combat.c File Reference
#include "g_local.h"
#include "../qcommon/q_shared.h"
#include "g_mdx.h"
#include "g_etbot_interface.h"
#include "g_lua.h"
Macros
#define REALHEAD_HEAD 1
#define MASK_CAN_DAMAGE (CONTENTS_SOLID | CONTENTS_BODY)
Functions
void AddKillScore (gentity_t *ent, int score)
Adds score to both the client and his team, only used for LMS.
void TossWeapons (gentity_t *self)
Toss the weapon and powerups for the killed player.
void LookAtKiller (gentity_t *self, gentity_t *inflictor, gentity_t *attacker)
LookAtKiller.
void GibEntity (gentity_t *self, int killer)
GibEntity.
void body_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t meansOfDeath)
body_die
void player_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t meansOfDeath)
player_die
gentity_t * G_BuildHead (gentity_t *ent, grefEntity_t *refent, qboolean newRefent)
G_BuildHead.
gentity_t * G_BuildLeg (gentity_t *ent, grefEntity_t *refent, qboolean newRefent)
G_BuildLeg.
qboolean IsHeadShot (gentity_t *targ, vec3_t dir, vec3_t point, meansOfDeath_t mod, grefEntity_t *refent, qboolean newRefent)
IsHeadShot.
qboolean IsLegShot (gentity_t *targ, vec3_t dir, vec3_t point, meansOfDeath_t mod, grefEntity_t *refent, qboolean newRefent)
IsLegShot.
qboolean IsArmShot (gentity_t *targ, gentity_t *ent, vec3_t point, meansOfDeath_t mod)
IsArmShot.
void G_Damage (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker, vec3_t dir, vec3_t point, int damage, int dflags, meansOfDeath_t mod)
G_Damage.
void G_RailTrail (vec_t *start, vec_t *end, vec_t *color)
void G_RailBox (vec_t *origin, vec_t *mins, vec_t *maxs, vec_t *color, int index)
G_RailBox.
qboolean CanDamage (gentity_t *targ, vec3_t origin)
Used for explosions and melee attacks.
void G_AdjustedDamageVec (gentity_t *ent, vec3_t origin, vec3_t vec)
G_AdjustedDamageVec.
qboolean G_RadiusDamage (vec3_t origin, gentity_t *inflictor, gentity_t *attacker, float damage, float radius, gentity_t *ignore, meansOfDeath_t mod)
G_RadiusDamage.
qboolean etpro_RadiusDamage (vec3_t origin, gentity_t *inflictor, gentity_t *attacker, float damage, float radius, gentity_t *ignore, meansOfDeath_t mod, qboolean clientsonly)
Mutation of G_RadiusDamage which lets us selectively damage only clients or only non clients.
Variables
vec3_t muzzleTrace
static grefEntity_t refent
This variable needs to be here in order for isHeadShot() to access it..
Macro Definition Documentation
#define MASK_CAN_DAMAGE (CONTENTS_SOLID | CONTENTS_BODY)
Definition at line 1810 of file g_combat.c.
Referenced by CanDamage().
#define REALHEAD_HEAD 1
Definition at line 698 of file g_combat.c.
Referenced by G_BuildHead(), and G_BuildLeg().
Function Documentation
void AddKillScore (gentity_t * ent, int score)
Adds score to both the client and his team, only used for LMS.
Parameters
[in,out] ent
[in] score
Definition at line 54 of file g_combat.c.
Referenced by player_die().
void body_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t meansOfDeath)
body_die
Parameters
[in,out] self
inflictor - unused
attacker - unused
damage - unused
meansOfDeath - unused
Definition at line 239 of file g_combat.c.
Referenced by CopyToBodyQue(), and player_die().
qboolean CanDamage (gentity_t * targ, vec3_t origin)
Used for explosions and melee attacks.
Parameters
[in] targ
[in] origin
Returns
qtrue if the inflictor can directly damage the target.
Definition at line 1818 of file g_combat.c.
Referenced by EntsThatRadiusCanDamage(), etpro_RadiusDamage(), and G_RadiusDamage().
qboolean etpro_RadiusDamage (vec3_t origin, gentity_t * inflictor, gentity_t * attacker, float damage, float radius, gentity_t * ignore, meansOfDeath_t mod, qboolean clientsonly)
Mutation of G_RadiusDamage which lets us selectively damage only clients or only non clients.
Parameters
[in] origin
[in] inflictor
[in] attacker
[in] damage
[in] radius
[in] ignore
[in] mod
[in] clientsonly
Returns
Definition at line 2127 of file g_combat.c.
Referenced by G_RealExplodedMissile().
void G_AdjustedDamageVec (gentity_t * ent, vec3_t origin, vec3_t vec)
G_AdjustedDamageVec.
Parameters
[in] ent
[in] origin
[out] vec
Definition at line 1951 of file g_combat.c.
Referenced by etpro_RadiusDamage(), and G_RadiusDamage().
gentity_t* G_BuildHead (gentity_t * ent, grefEntity_t * refent, qboolean newRefent)
G_BuildHead.
Parameters
[in] ent
[in] refent
[in] newRefent
Returns
Definition at line 707 of file g_combat.c.
Referenced by ClientEndFrame(), ClientThink_real(), G_AttachBodyParts(), and IsHeadShot().
gentity_t* G_BuildLeg (gentity_t * ent, grefEntity_t * refent, qboolean newRefent)
G_BuildLeg.
Parameters
[in] ent
[in] refent
[in] newRefent
Returns
Definition at line 828 of file g_combat.c.
Referenced by ClientEndFrame(), ClientThink_real(), G_AttachBodyParts(), and IsLegShot().
void G_Damage (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker, vec3_t dir, vec3_t point, int damage, int dflags, meansOfDeath_t mod)
G_Damage.
Parameters
[in,out] targ entity that is being damaged
[in,out] inflictor entity that is causing the damage
[in,out] attacker entity that caused the inflictor to damage targ example: targ=monster, inflictor=rocket, attacker=player
[in] dir direction of the attack for knockback
[in] point point at which the damage is being inflicted, used for headshots
[in] damage amount of damage being inflicted
[in] dflags these flags are used to control how T_Damage works DAMAGE_RADIUS damage was indirect (from a nearby explosion) DAMAGE_NO_ARMOR armor does not protect from this damage DAMAGE_NO_KNOCKBACK do not affect velocity, just view angles DAMAGE_NO_PROTECTION kills godmode, armor, everything
[in] mod
Note
inflictor, attacker, dir, and point can be NULL for environmental effects
This parameter was previously present : knockback force to be applied against targ as a result of the damage
Todo:
: also when damage is 0 ?
Definition at line 1130 of file g_combat.c.
Referenced by _et_G_Damage(), Blocked_Door(), Blocked_DoorRotate(), Bullet_Fire_Extended(), etpro_RadiusDamage(), Fire_Lead_Ext(), func_constructible_explode(), G_BurnMeGood(), G_BurnTarget(), G_FallDamage(), G_KillEnts(), G_MissileImpact(), G_MoverPush(), G_RadiusDamage(), G_SetEntState(), HandleEntsThatBlockConstructible(), hurt_touch(), ETInterface::InterfaceSendMessage(), Just_Got_Thrown(), P_WorldEffects(), props_castlebed_touch(), props_statue_blocked(), script_mover_blocked(), Svcmd_Die(), Svcmd_Gib(), target_kill_use(), target_laser_think(), Use_DamageInflictor(), and Weapon_Knife().
qboolean G_RadiusDamage (vec3_t origin, gentity_t * inflictor, gentity_t * attacker, float damage, float radius, gentity_t * ignore, meansOfDeath_t mod)
G_RadiusDamage.
Parameters
[in] origin
[in] inflictor
[in] attacker
[in] damage
[in] radius
[in] ignore
[in] mod
Returns
Definition at line 1990 of file g_combat.c.
Referenced by func_explosive_explode(), G_RealExplodedMissile(), target_effect(), and target_explosion_use().
void G_RailBox (vec_t * origin, vec_t * mins, vec_t * maxs, vec_t * color, int index)
G_RailBox.
Parameters
[in] origin
[in] mins
[in] maxs
[in] color
[in] index
Definition at line 1786 of file g_combat.c.
Referenced by ClientEndFrame(), ClientThink_real(), G_DrawEntBBox(), IsHeadShot(), and IsLegShot().
void G_RailTrail (vec_t * start, vec_t * end, vec_t * color)
Definition at line 1764 of file g_combat.c.
Referenced by IsHeadShot(), and IsLegShot().
void GibEntity (gentity_t * self, int killer)
GibEntity.
Parameters
[in,out] self
[in] killer
Definition at line 206 of file g_combat.c.
Referenced by body_die(), G_Damage(), G_MoverPush(), G_TryPushingEntity(), and player_die().
qboolean IsArmShot (gentity_t * targ, gentity_t * ent, vec3_t point, meansOfDeath_t mod)
IsArmShot.
Parameters
[in] targ
ent - unused
[in] point
[in] mod
Returns
Definition at line 1061 of file g_combat.c.
Referenced by G_Damage().
qboolean IsHeadShot (gentity_t * targ, vec3_t dir, vec3_t point, meansOfDeath_t mod, grefEntity_t * refent, qboolean newRefent)
IsHeadShot.
Parameters
[in] targ
[in] dir
[in] point
[in] mod
[in] refent
[in] newRefent
Returns
Definition at line 902 of file g_combat.c.
Referenced by G_Damage().
qboolean IsLegShot (gentity_t * targ, vec3_t dir, vec3_t point, meansOfDeath_t mod, grefEntity_t * refent, qboolean newRefent)
IsLegShot.
Parameters
[in] targ
[in] dir
[in] point
[in] mod
[in] refent
[in] newRefent
Returns
Definition at line 972 of file g_combat.c.
Referenced by G_Damage().
void LookAtKiller (gentity_t * self, gentity_t * inflictor, gentity_t * attacker)
LookAtKiller.
Parameters
[in,out] self
[in] inflictor
[in] attacker
Definition at line 180 of file g_combat.c.
Referenced by player_die().
void player_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t meansOfDeath)
player_die
Parameters
[in,out] self
[in] inflictor
[in,out] attacker
[in] damage
[in] meansOfDeath
Todo:
: contents is always 0 here
Todo:
: add POSITION_RIGHT, POSITION_LEFT
Definition at line 255 of file g_combat.c.
Referenced by ClientSpawn(), Cmd_Kill_f(), Cmd_UnIgnore_f(), and SetTeam().
void TossWeapons (gentity_t * self)
Toss the weapon and powerups for the killed player.
Parameters
[in] self
Todo:
; drop secondary too?!
Definition at line 81 of file g_combat.c.
Referenced by ClientDisconnect(), and limbo().
Variable Documentation
vec3_t muzzleTrace
Definition at line 45 of file g_weapon.c.
Referenced by Bullet_Endpos(), Bullet_Fire(), Bullet_Fire_Extended(), CalcMuzzlePoints(), G_Damage(), Weapon_Engineer(), Weapon_Knife(), and Weapon_Syringe().
refent static
This variable needs to be here in order for isHeadShot() to access it..
Definition at line 1103 of file g_combat.c.