ET: Legacy: src/game/g_cmds.c File Reference
g_cmds.c File Reference
#include "g_local.h"
#include "g_etbot_interface.h"
#include "g_lua.h"
Functions
qboolean G_IsOnFireteam (int entityNum, fireteamData_t **teamNum)
G_IsOnFireteam.
qboolean G_MatchOnePlayer (int *plist, char *err, size_t len)
G_MatchOnePlayer.
int ClientNumbersFromString (char *s, int *plist)
Sets plist to an array of integers that represent client numbers that have names that are a partial match for s. List is terminated by a -1.
void G_PlaySound_Cmd (void)
G_PlaySound_Cmd.
qboolean G_SendScore_Add (gentity_t *ent, int i, char *buf, int bufsize)
Add score with clientNum at index i of level.sortedClients[] to the string buf.
void G_SendScore (gentity_t *ent)
Sends current scoreboard information.
void Cmd_Score_f (gentity_t *ent)
Request current scoreboard information.
qboolean CheatsOk (gentity_t *ent)
CheatsOk.
char * ConcatArgs (int start)
Concatenates console arguments.
void SanitizeString (char *in, char *out, qboolean fToLower)
Remove case and control characters.
int ClientNumberFromString (gentity_t *to, char *s)
ClientNumberFromString.
float GetSkillPointUntilLevelUp (gentity_t *ent, skillType_t skill)
GetSkillPointUntilLevelUp.
void Cmd_Give_f (gentity_t *ent)
Give items to a client.
void Cmd_God_f (gentity_t *ent)
Sets client to godmode.
void Cmd_Nofatigue_f (gentity_t *ent)
Sets client to nofatigue.
void Cmd_Notarget_f (gentity_t *ent)
Sets client to notarget.
void Cmd_Noclip_f (gentity_t *ent)
Cmd_Noclip_f.
void Cmd_Nostamina_f (gentity_t *ent)
Sets client to nostamina.
void Cmd_Kill_f (gentity_t *ent)
Cmd_Kill_f.
void Cmd_DropObjective_f (gentity_t *ent)
Cmd_DropObjective_f.
void G_TeamDataForString (const char *teamstr, int clientNum, team_t *team, spectatorState_t *sState, int *specClient)
G_TeamDataForString.
void G_DropItems (gentity_t *self)
Drops items. Currently only red-/blueflag.
qboolean SetTeam (gentity_t *ent, const char *s, qboolean force, weapon_t w1, weapon_t w2, qboolean setweapons)
SetTeam.
void StopFollowing (gentity_t *ent)
If the client being followed leaves the game, or you just want to drop to free floating spectator mode.
int G_NumPlayersOnTeam (team_t team)
G_NumPlayersOnTeam.
int G_TeamCount (gentity_t *ent, int weap)
G_TeamCount.
qboolean G_IsWeaponDisabled (gentity_t *ent, weapon_t weapon)
Checks for heavy and rifle weapons restriction.
void G_SetClientWeapons (gentity_t *ent, weapon_t w1, weapon_t w2, qboolean updateclient)
G_SetClientWeapons.
int G_ClassCount (gentity_t *ent, int playerType, team_t team)
G_ClassCount.
qboolean G_IsClassFull (gentity_t *ent, int playerType, team_t team)
G_IsClassFull.
void Cmd_Team_f (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Cmd_Team_f.
void Cmd_ResetSetup_f (gentity_t *ent)
Cmd_ResetSetup_f.
void Cmd_Follow_f (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Cmd_Follow_f.
void Cmd_FollowCycle_f (gentity_t *ent, int dir, qboolean skipBots)
Cmd_FollowCycle_f.
qboolean G_FollowSame (gentity_t *ent)
Try to follow the same client as last time (before getting killed)
void G_EntitySound (gentity_t *ent, const char *soundId, int volume)
Plays a sound (wav file or sound script) on this entity.
void G_EntitySoundNoCut (gentity_t *ent, const char *soundId, int volume)
Similar to G_EntitySound, but do not cut this sound off.
void G_HQSay (gentity_t *other, int color, const char *name, const char *message)
G_HQSay.
void G_SayTo (gentity_t *ent, gentity_t *other, int mode, int color, const char *name, const char *message, qboolean localize)
G_SayTo.
void G_Say (gentity_t *ent, gentity_t *target, int mode, const char *chatText)
G_Say.
void Cmd_Say_f (gentity_t *ent, int mode, qboolean arg0)
Cmd_Say_f.
void G_VoiceTo (gentity_t *ent, gentity_t *other, int mode, const char *id, qboolean voiceonly, float randomNum)
G_VoiceTo.
void G_Voice (gentity_t *ent, gentity_t *target, int mode, const char *id, const char *customChat, qboolean voiceonly)
G_Voice.
static void Cmd_Voice_f (gentity_t *ent, int mode, qboolean arg0, qboolean voiceonly)
Cmd_Voice_f.
void Cmd_Where_f (gentity_t *ent)
Cmd_Where_f.
qboolean Cmd_CallVote_f (gentity_t *ent, unsigned int dwCommand, qboolean fRefCommand)
Cmd_CallVote_f.
qboolean StringToFilter (const char *s, ipFilter_t *f)
StringToFilter.
qboolean G_FindFreeComplainIP (gclient_t *cl, ipFilter_t *ip)
G_FindFreeComplainIP.
void Cmd_Vote_f (gentity_t *ent)
Cmd_Vote_f.
void Cmd_SetViewpos_f (gentity_t *ent)
Cmd_SetViewpos_f.
qboolean G_TankIsOccupied (gentity_t *ent)
G_TankIsOccupied.
qboolean G_TankIsMountable (gentity_t *ent, gentity_t *other)
G_TankIsMountable.
qboolean Do_Activate2_f (gentity_t *ent, gentity_t *traceEnt)
Do_Activate2_f.
qboolean Do_Activate_f (gentity_t *ent, gentity_t *traceEnt)
Extracted out the functionality of Cmd_Activate_f from finding the object to use so we can force bots to use items, without worrying that they are looking EXACTLY at the target.
void G_LeaveTank (gentity_t *ent, qboolean position)
G_LeaveTank.
void Cmd_Activate_f (gentity_t *ent)
Cmd_Activate_f.
qboolean G_PushPlayer (gentity_t *ent, gentity_t *victim)
G_PushPlayer.
void Cmd_Activate2_f (gentity_t *ent)
Cmd_Activate2_f.
void SetPlayerSpawn (gentity_t *ent, int spawn, qboolean update)
SetPlayerSpawn.
void Cmd_SetSpawnPoint_f (gentity_t *ent)
Cmd_SetSpawnPoint_f.
void G_PrintAccuracyLog (gentity_t *ent)
G_PrintAccuracyLog.
void Cmd_WeaponStat_f (gentity_t *ent)
Cmd_WeaponStat_f.
void Cmd_IntermissionWeaponStats_f (gentity_t *ent)
Cmd_IntermissionWeaponStats_f.
void G_MakeReady (gentity_t *ent)
G_MakeReady.
void G_MakeUnready (gentity_t *ent)
G_MakeUnready.
void Cmd_IntermissionReady_f (gentity_t *ent)
Cmd_IntermissionReady_f.
void Cmd_IntermissionPlayerKillsDeaths_f (gentity_t *ent)
Cmd_IntermissionPlayerKillsDeaths_f.
void Cmd_IntermissionPlayerTime_f (gentity_t *ent)
Cmd_IntermissionPlayerTime_f.
void G_CalcClientAccuracies (void)
G_CalcClientAccuracies.
void Cmd_IntermissionWeaponAccuracies_f (gentity_t *ent)
Cmd_IntermissionWeaponAccuracies_f.
void Cmd_SelectedObjective_f (gentity_t *ent)
Cmd_SelectedObjective_f.
void Cmd_Ignore_f (gentity_t *ent)
Cmd_Ignore_f.
void Cmd_UnIgnore_f (gentity_t *ent)
Cmd_UnIgnore_f.
void ClientCommand (int clientNum)
ClientCommand.
char * Q_AddCR (char *s)
Replaces all occurances of "\\\\n" with '\n'.
Variables
vec3_t playerMins
vec3_t playerMaxs
Function Documentation
qboolean CheatsOk (gentity_t * ent)
CheatsOk.
Parameters
[in] ent
Returns
Definition at line 469 of file g_cmds.c.
Referenced by Cmd_Give_f(), Cmd_God_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), and Cmd_Notarget_f().
void ClientCommand (int clientNum)
ClientCommand.
Parameters
[in] clientNum
Definition at line 4783 of file g_cmds.c.
Referenced by vmMain().
int ClientNumberFromString (gentity_t * to, char * s)
ClientNumberFromString.
Parameters
[in] to
[in] s
Returns
A player number for either a number or name string, -1 if invalid
Definition at line 556 of file g_cmds.c.
Referenced by G_Kick_v(), G_Mute_v(), G_Referee_v(), G_refMakeShoutcaster_cmd(), G_refMute_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_refRemoveShoutcaster_cmd(), G_specinvite_cmd(), G_statsPrint(), G_UnMute_v(), and G_Unreferee_v().
int ClientNumbersFromString (char * s, int * plist)
Sets plist to an array of integers that represent client numbers that have names that are a partial match for s. List is terminated by a -1.
Parameters
[in] s
[out] plist
Returns
Number of matching clientids.
Definition at line 98 of file g_cmds.c.
Referenced by _et_ClientNumberFromString(), Cmd_Follow_f(), G_makesc_cmd(), G_PlaySound_Cmd(), G_removesc_cmd(), Svcmd_Burn(), Svcmd_Die(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Pip(), and Svcmd_Unfreeze().
void Cmd_Activate2_f (gentity_t * ent)
Cmd_Activate2_f.
Parameters
[in] ent
Definition at line 4161 of file g_cmds.c.
Referenced by G_RunClient().
void Cmd_Activate_f (gentity_t * ent)
Cmd_Activate_f.
Parameters
[in,out] ent
Definition at line 3968 of file g_cmds.c.
Referenced by ClientThink_real(), and SpectatorThink().
qboolean Cmd_CallVote_f (gentity_t * ent, unsigned int dwCommand, qboolean fRefCommand)
Cmd_CallVote_f.
Parameters
[in,out] ent
dwCommand - unused
[in] fRefCommand
Returns
Definition at line 3049 of file g_cmds.c.
Referenced by G_ref_cmd().
void Cmd_DropObjective_f (gentity_t * ent)
Cmd_DropObjective_f.
Parameters
[in,out] ent
Definition at line 1163 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Follow_f (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Cmd_Follow_f.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 2241 of file g_cmds.c.
void Cmd_FollowCycle_f (gentity_t * ent, int dir, qboolean skipBots)
Cmd_FollowCycle_f.
Parameters
[in,out] ent
[in] dir
[in] skipBots
Definition at line 2367 of file g_cmds.c.
Referenced by ClientCommand(), ClientDisconnect(), Cmd_Follow_f(), limbo(), and SpectatorThink().
void Cmd_Give_f (gentity_t * ent)
Give items to a client.
Parameters
[in,out] ent
Definition at line 641 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_God_f (gentity_t * ent)
Sets client to godmode.
Parameters
[in,out] ent
Note
argv(0) god
Definition at line 880 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Ignore_f (gentity_t * ent)
Cmd_Ignore_f.
Parameters
[in] ent
Definition at line 4657 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_IntermissionPlayerKillsDeaths_f (gentity_t * ent)
Cmd_IntermissionPlayerKillsDeaths_f.
Parameters
[in,out] ent
Definition at line 4432 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_IntermissionPlayerTime_f (gentity_t * ent)
Cmd_IntermissionPlayerTime_f.
Parameters
[in] ent
Definition at line 4462 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_IntermissionReady_f (gentity_t * ent)
Cmd_IntermissionReady_f.
Parameters
[in,out] ent
Definition at line 4412 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_IntermissionWeaponAccuracies_f (gentity_t * ent)
Cmd_IntermissionWeaponAccuracies_f.
Parameters
[in] ent
Definition at line 4568 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_IntermissionWeaponStats_f (gentity_t * ent)
Cmd_IntermissionWeaponStats_f.
Parameters
[in] ent
Definition at line 4351 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Kill_f (gentity_t * ent)
Cmd_Kill_f.
Parameters
[in,out] ent
Definition at line 1123 of file g_cmds.c.
Referenced by Bot_Util_CheckForSuicide(), ETInterface::ChangeClass(), and ClientCommand().
void Cmd_Noclip_f (gentity_t * ent)
Cmd_Noclip_f.
Parameters
[in,out] ent
Note
argv(0) noclip
Definition at line 1041 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Nofatigue_f (gentity_t * ent)
Sets client to nofatigue.
Parameters
[in,out] ent
Note
argv(0) nofatigue
Definition at line 972 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Nostamina_f (gentity_t * ent)
Sets client to nostamina.
Parameters
[in,out] ent
Note
argv(0) nostamina
Definition at line 1084 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Notarget_f (gentity_t * ent)
Sets client to notarget.
Parameters
[in,out] ent
Note
argv(0) notarget
Definition at line 1013 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_ResetSetup_f (gentity_t * ent)
Cmd_ResetSetup_f.
Parameters
[in,out] ent
Definition at line 2206 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Say_f (gentity_t * ent, int mode, qboolean arg0)
Cmd_Say_f.
Parameters
[in] ent
[in] mode
[in] arg0
Definition at line 2729 of file g_cmds.c.
Referenced by ClientCommand(), and G_say_teamnl_cmd().
void Cmd_Score_f (gentity_t * ent)
Request current scoreboard information.
Parameters
[out] ent
Definition at line 458 of file g_cmds.c.
Referenced by ClientCommand(), and player_die().
void Cmd_SelectedObjective_f (gentity_t * ent)
Cmd_SelectedObjective_f.
Parameters
[in,out] ent
Definition at line 4600 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_SetSpawnPoint_f (gentity_t * ent)
Cmd_SetSpawnPoint_f.
Parameters
[in,out] ent
Definition at line 4274 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_SetViewpos_f (gentity_t * ent)
Cmd_SetViewpos_f.
Parameters
[in] ent
Definition at line 3571 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Team_f (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Cmd_Team_f.
Parameters
[in,out] ent
dwCommand - unused
fValue - unused
Definition at line 2106 of file g_cmds.c.
void Cmd_UnIgnore_f (gentity_t * ent)
Cmd_UnIgnore_f.
Parameters
[in] ent
Definition at line 4683 of file g_cmds.c.
Referenced by ClientCommand().
static void Cmd_Voice_f (gentity_t * ent, int mode, qboolean arg0, qboolean voiceonly) static
Cmd_Voice_f.
Parameters
[in] ent
[in] mode
[in] arg0
[in] voiceonly
Definition at line 2995 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Vote_f (gentity_t * ent)
Cmd_Vote_f.
Parameters
[in,out] ent
Definition at line 3242 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_WeaponStat_f (gentity_t * ent)
Cmd_WeaponStat_f.
Parameters
[in] ent
Definition at line 4322 of file g_cmds.c.
Referenced by ClientCommand().
void Cmd_Where_f (gentity_t * ent)
Cmd_Where_f.
Parameters
[in] ent
Definition at line 3037 of file g_cmds.c.
Referenced by ClientCommand().
char* ConcatArgs (int start)
Concatenates console arguments.
Parameters
[in] start concatenate from this argument
Definition at line 488 of file g_cmds.c.
Referenced by _et_ConcatArgs(), CC_svcvar(), Cmd_Give_f(), Cmd_God_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_Say_f(), Cmd_Voice_f(), G_Poll_v(), Svcmd_Chat_f(), Svcmd_CP_f(), and Svcmd_Say_f().
qboolean Do_Activate2_f (gentity_t * ent, gentity_t * traceEnt)
Do_Activate2_f.
Parameters
[in,out] ent
[in,out] traceEnt
Returns
Definition at line 3664 of file g_cmds.c.
Referenced by Cmd_Activate2_f().
qboolean Do_Activate_f (gentity_t * ent, gentity_t * traceEnt)
Extracted out the functionality of Cmd_Activate_f from finding the object to use so we can force bots to use items, without worrying that they are looking EXACTLY at the target.
Parameters
[in,out] ent
[in,out] traceEnt
Returns
Definition at line 3726 of file g_cmds.c.
Referenced by Cmd_Activate_f().
void G_CalcClientAccuracies (void)
G_CalcClientAccuracies.
Definition at line 4527 of file g_cmds.c.
Referenced by Cmd_IntermissionWeaponAccuracies_f(), and G_BuildEndgameStats().
int G_ClassCount (gentity_t * ent, int playerType, team_t team)
G_ClassCount.
Parameters
[in] ent
[in] playerType
[in] team
Returns
Definition at line 1935 of file g_cmds.c.
Referenced by G_IsClassFull().
void G_DropItems (gentity_t * self)
Drops items. Currently only red-/blueflag.
Parameters
[in,out] self
Todo:
set player->otherentitynum2 with old modelindex2 from flag and restore here
Definition at line 1270 of file g_cmds.c.
Referenced by ClientDisconnect(), Cmd_DropObjective_f(), and player_die().
void G_EntitySound (gentity_t * ent, const char * soundId, int volume)
Plays a sound (wav file or sound script) on this entity.
Parameters
[in] ent entity to play the sound on
[in] soundId sound file name or sound script ID
[in] volume sound volume, only applies to sound file name call
Note
Unused. Keep this.
Calling G_AddEvent(..., EV_GENERAL_SOUND, ...) has the danger of the event never getting through to the client because the entity might not be visible (unless it has the SVF_BROADCAST flag), so if you want to make sure the sound is heard, call this function instead.
Definition at line 2526 of file g_cmds.c.
void G_EntitySoundNoCut (gentity_t * ent, const char * soundId, int volume)
Similar to G_EntitySound, but do not cut this sound off.
Parameters
[in] ent entity to play the sound on
[in] soundId sound file name or sound script ID
[in] volume sound volume, only applies to sound file name call
Note
Unused. See G_EntitySound()
Definition at line 2541 of file g_cmds.c.
qboolean G_FindFreeComplainIP (gclient_t * cl, ipFilter_t * ip)
G_FindFreeComplainIP.
Parameters
[in,out] cl
[in] ip
Returns
Definition at line 3213 of file g_cmds.c.
Referenced by Cmd_Vote_f().
qboolean G_FollowSame (gentity_t * ent)
Try to follow the same client as last time (before getting killed)
Parameters
[in] ent
Definition at line 2466 of file g_cmds.c.
Referenced by limbo().
void G_HQSay (gentity_t * other, int color, const char * name, const char * message)
G_HQSay.
Parameters
[in] other
[in] color
[in] name
[in] message
Definition at line 2555 of file g_cmds.c.
Referenced by Weapon_Artillery(), weapon_callAirStrike(), and weapon_checkAirStrike().
qboolean G_IsClassFull (gentity_t * ent, int playerType, team_t team)
G_IsClassFull.
Parameters
[in] ent
[in] playerType
[in] team
Returns
Definition at line 1975 of file g_cmds.c.
Referenced by Cmd_Team_f().
qboolean G_IsOnFireteam (int entityNum, fireteamData_t ** teamNum)
G_IsOnFireteam.
Parameters
[in] entityNum
[out] teamNum
Returns
Definition at line 211 of file g_fireteams.c.
Referenced by G_SayTo(), and G_VoiceTo().
qboolean G_IsWeaponDisabled (gentity_t * ent, weapon_t weapon)
Checks for heavy and rifle weapons restriction.
Parameters
[in] ent
[in] weapon
Returns
Todo:
This function needs some rework: count picked up opposite team weapons too see CG_LimboPanel_RealWeaponIsDisabled
Definition at line 1802 of file g_cmds.c.
Referenced by _choosePriWeap(), _chooseSecWeap(), ETInterface::ChangeClass(), ETInterface::ChangeTeam(), ClientSpawn(), and G_SetClientWeapons().
void G_LeaveTank (gentity_t * ent, qboolean position)
G_LeaveTank.
Parameters
[in,out] ent
[in] position
Definition at line 3894 of file g_cmds.c.
Referenced by ClientDisconnect(), Cmd_Activate_f(), G_shuffleTeamsXP(), MoveClientToIntermission(), player_die(), script_mover_die(), and SetTeam().
void G_MakeReady (gentity_t * ent)
G_MakeReady.
Parameters
[in,out] ent
Definition at line 4390 of file g_cmds.c.
Referenced by Cmd_IntermissionReady_f(), G_ready_cmd(), and G_teamready_cmd().
void G_MakeUnready (gentity_t * ent)
G_MakeUnready.
Parameters
[in,out] ent
Definition at line 4401 of file g_cmds.c.
Referenced by G_LogExit(), and G_ready_cmd().
qboolean G_MatchOnePlayer (int * plist, char * err, size_t len)
G_MatchOnePlayer.
Parameters
[in] plist
[out] err
[in] len
Returns
Definition at line 54 of file g_cmds.c.
Referenced by G_PlaySound_Cmd(), Svcmd_Burn(), Svcmd_Die(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Pip(), and Svcmd_Unfreeze().
int G_NumPlayersOnTeam (team_t team)
G_NumPlayersOnTeam.
Parameters
[in] team
Returns
Definition at line 1726 of file g_cmds.c.
Referenced by G_IsClassFull().
void G_PlaySound_Cmd (void)
G_PlaySound_Cmd.
Definition at line 185 of file g_cmds.c.
void G_PrintAccuracyLog (gentity_t * ent)
G_PrintAccuracyLog.
Parameters
[in] ent
Definition at line 104 of file g_stats.c.
Referenced by ClientCommand(), and Cmd_SetSpawnPoint_f().
qboolean G_PushPlayer (gentity_t * ent, gentity_t * victim)
G_PushPlayer.
Parameters
[in,out] ent
[in,out] victim
Returns
Definition at line 4074 of file g_cmds.c.
Referenced by Cmd_Activate2_f().
void G_Say (gentity_t * ent, gentity_t * target, int mode, const char * chatText)
G_Say.
Parameters
[in] ent
[in] target
[in] mode
[in] chatText
Definition at line 2661 of file g_cmds.c.
Referenced by _et_G_Say(), Cmd_Say_f(), and G_Voice().
void G_SayTo (gentity_t * ent, gentity_t * other, int mode, int color, const char * name, const char * message, qboolean localize)
G_SayTo.
Parameters
[in] ent
[in] other
[in] mode
[in] color
[in] name
[in] message
[in] localize
Definition at line 2575 of file g_cmds.c.
Referenced by G_Say().
void G_SendScore (gentity_t * ent)
Sends current scoreboard information.
Parameters
[in] ent
Definition at line 381 of file g_cmds.c.
Referenced by ClientThink_real().
qboolean G_SendScore_Add (gentity_t * ent, int i, char * buf, int bufsize)
Add score with clientNum at index i of level.sortedClients[] to the string buf.
Parameters
ent - unused
[in] i
[out] buf
[in] bufsize
Returns
qtrue if the score was appended to buf, qfalse otherwise.
Todo:
FIXME: FEATURE_MULTIVIEW might be buggy -> powerups var is used to store player class/type (differs from GPL Code) playerClass is no longer sent!
Definition at line 289 of file g_cmds.c.
Referenced by G_SendScore().
void G_SetClientWeapons (gentity_t * ent, weapon_t w1, weapon_t w2, qboolean updateclient)
G_SetClientWeapons.
Parameters
[in,out] ent
[in] w1
[in] w2
[in] updateclient
Definition at line 1895 of file g_cmds.c.
Referenced by Cmd_Team_f(), and SetTeam().
qboolean G_TankIsMountable (gentity_t * ent, gentity_t * other)
G_TankIsMountable.
Parameters
[in] ent
[in] other
Returns
Definition at line 3624 of file g_cmds.c.
Referenced by Do_Activate_f(), and G_CheckForCursorHints().
qboolean G_TankIsOccupied (gentity_t * ent)
G_TankIsOccupied.
Parameters
[in] ent
Returns
Definition at line 3609 of file g_cmds.c.
Referenced by G_TankIsMountable(), and ETInterface::GetEntityFlags().
int G_TeamCount (gentity_t * ent, int weap)
G_TeamCount.
Parameters
[in] ent
[in] weap weapon or -1
Returns
Definition at line 1751 of file g_cmds.c.
Referenced by G_IsWeaponDisabled(), G_MaxAvailableAirstrikes(), and G_MaxAvailableArtillery().
void G_TeamDataForString (const char * teamstr, int clientNum, team_t * team, spectatorState_t * sState, int * specClient)
G_TeamDataForString.
Parameters
[in] teamstr
[in] clientNum
[out] team
[out] sState
[in,out] specClient
Definition at line 1197 of file g_cmds.c.
Referenced by Cmd_Team_f(), and SetTeam().
void G_Voice (gentity_t * ent, gentity_t * target, int mode, const char * id, const char * customChat, qboolean voiceonly)
G_Voice.
Parameters
[in,out] ent
[in] target
[in] mode
[in] id
[in] voiceonly
Definition at line 2843 of file g_cmds.c.
Referenced by Cmd_Voice_f().
void G_VoiceTo (gentity_t * ent, gentity_t * other, int mode, const char * id, qboolean voiceonly, float randomNum)
G_VoiceTo.
Parameters
[in] ent
[in] other
[in] mode
[in] id
[in] voiceonly
[in] randomNum
Definition at line 2747 of file g_cmds.c.
Referenced by G_Voice().
float GetSkillPointUntilLevelUp (gentity_t * ent, skillType_t skill)
GetSkillPointUntilLevelUp.
Parameters
[in] ent
[in] skill
Returns
Definition at line 619 of file g_cmds.c.
Referenced by Cmd_Give_f().
char* Q_AddCR (char * s)
Replaces all occurances of "\\\\n" with '\n'.
Parameters
[in] s
Definition at line 5111 of file g_cmds.c.
Referenced by Svcmd_Chat_f(), Svcmd_CP_f(), and Svcmd_Say_f().
void SanitizeString (char * in, char * out, qboolean fToLower)
Remove case and control characters.
Parameters
[in] in
[out] out
[in] fToLower
Definition at line 524 of file g_cmds.c.
Referenced by ClientNumberFromString(), ClientNumbersFromString(), G_players_cmd(), and G_printMatchInfo().
void SetPlayerSpawn (gentity_t * ent, int spawn, qboolean update)
SetPlayerSpawn.
Parameters
[in,out] ent
[in] spawn
[in] update
Definition at line 4232 of file g_cmds.c.
Referenced by Cmd_SetSpawnPoint_f(), and ETInterface::InterfaceSendMessage().
qboolean SetTeam (gentity_t * ent, const char * s, qboolean force, weapon_t w1, weapon_t w2, qboolean setweapons)
SetTeam.
Parameters
[in,out] ent
[in] s
[in] force
[in] w1
[in] w2
[in] setweapons
Returns
Todo:
: doesn't ClientBegin take care of this already?
Definition at line 1370 of file g_cmds.c.
Referenced by ETInterface::ChangeTeam(), ClientInactivityTimer(), Cmd_FollowCycle_f(), Cmd_Team_f(), G_MakeShoutcaster(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_updateSpecLock(), StopFollowing(), and Svcmd_ForceTeam_f().
void StopFollowing (gentity_t * ent)
If the client being followed leaves the game, or you just want to drop to free floating spectator mode.
Parameters
[in,out] ent
Todo:
: to avoid having a spectator with a gun..
Todo:
: useless?
Definition at line 1651 of file g_cmds.c.
Referenced by ClientDisconnect(), Cmd_Follow_f(), G_updateSpecLock(), MoveClientToIntermission(), and SpectatorThink().
qboolean StringToFilter (const char * s, ipFilter_t * f)
StringToFilter.
Parameters
[in,out] s
[out] f
Returns
Definition at line 106 of file g_svcmds.c.
Referenced by AddIP(), Cmd_CallVote_f(), Cmd_Vote_f(), and Svcmd_RemoveIP_f().
Variable Documentation
vec3_t playerMaxs
Definition at line 54 of file g_client.c.
Referenced by ClientSpawn(), Cmd_SetViewpos_f(), G_LeaveTank(), and SpotWouldTelefrag().
vec3_t playerMins
Definition at line 53 of file g_client.c.
Referenced by ClientSpawn(), Cmd_SetViewpos_f(), G_LeaveTank(), and SpotWouldTelefrag().