ET: Legacy: src/game/g_etbot_interface.h File Reference
g_etbot_interface.h File Reference
ET <-> Omni-Bot interface header file.
#include "g_local.h"
Macros
#define OMNIBOT_NAME "Legacy"
#define OMNIBOT_MODNAME GAMEVERSION
#define OMNIBOT_MODVERSION ETLEGACY_VERSION_SHORT
Enumerations
enum BotFlagOptions {
OBF_DONT_XPSAVE = (1 << 0), OBF_DONT_MOUNT_TANKS = (1 << 1), OBF_DONT_MOUNT_GUNS = (1 << 2), OBF_DONT_SHOW_BOTCOUNT = (1 << 3),
OBF_GIBBING = (1 << 4), OBF_TRIGGER_MINES = (1 << 5), OBF_SHOVING = (1 << 6), OBF_NEXT_FLAG = (1 << 16)
}
g_OmniBotFlags bits
Functions
int Bot_Interface_Init ()
void Bot_Interface_InitHandles ()
int Bot_Interface_Shutdown ()
void Bot_Interface_Update ()
void Bot_Interface_ConsoleCommand (void)
qboolean Bot_Util_AllowPush (int weaponId)
qboolean Bot_Util_CheckForSuicide (gentity_t *ent)
const char * _GetEntityName (gentity_t *_ent)
void Bot_Util_SendTrigger (gentity_t *_ent, gentity_t *_activator, const char *_tagname, const char *_action)
int Bot_WeaponGameToBot (int weapon)
int Bot_TeamGameToBot (int team)
int Bot_PlayerClassGameToBot (int playerClass)
void Bot_Queue_EntityCreated (gentity_t *pEnt)
void Bot_Event_EntityDeleted (gentity_t *pEnt)
void Bot_Event_ClientConnected (int _client, qboolean _isbot)
void Bot_Event_ClientDisConnected (int _client)
void Bot_Event_ResetWeapons (int _client)
void Bot_Event_AddWeapon (int _client, int _weaponId)
void Bot_Event_RemoveWeapon (int _client, int _weaponId)
void Bot_Event_TakeDamage (int _client, gentity_t *_ent)
void Bot_Event_Death (int _client, gentity_t *_killer, const char *_meansofdeath)
void Bot_Event_KilledSomeone (int _client, gentity_t *_victim, const char *_meansofdeath)
void Bot_Event_Revived (int _client, gentity_t *_whodoneit)
void Bot_Event_Healed (int _client, gentity_t *_whodoneit)
void Bot_Event_RecievedAmmo (int _client, gentity_t *_whodoneit)
void Bot_Event_FireWeapon (int _client, int _weaponId, gentity_t *_projectile)
void Bot_Event_PreTriggerMine (int _client, gentity_t *_mine)
void Bot_Event_PostTriggerMine (int _client, gentity_t *_mine)
void Bot_Event_MortarImpact (int _client, vec3_t _pos)
void Bot_Event_Spectated (int _client, int _who)
void Bot_Event_ChatMessage (int _client, gentity_t *_source, int _type, const char *_message)
void Bot_Event_VoiceMacro (int _client, gentity_t *_source, int _type, const char *_message)
void Bot_Event_Sound (gentity_t *_source, int _sndtype, const char *_name)
void Bot_Event_FireTeamCreated (int _client, int _fireteamnum)
void Bot_Event_FireTeamDestroyed (int _client)
void Bot_Event_JoinedFireTeam (int _client, gentity_t *leader)
void Bot_Event_LeftFireTeam (int _client)
void Bot_Event_InviteFireTeam (int _inviter, int _invitee)
void Bot_Event_FireTeam_Proposal (int _client, int _proposed)
void Bot_Event_FireTeam_Warn (int _client, int _warned)
void Bot_AddDynamiteGoal (gentity_t *_ent, int _team, const char *_tag)
void Bot_AddFallenTeammateGoals (gentity_t *_teammate, int _team)
void AddDeferredGoal (gentity_t *ent)
void UpdateGoalEntity (gentity_t *oldent, gentity_t *newent)
void GetEntityCenter (gentity_t *ent, vec3_t pos)
Detailed Description
ET <-> Omni-Bot interface header file.
Definition in file g_etbot_interface.h.
Macro Definition Documentation
#define OMNIBOT_MODNAME GAMEVERSION
Definition at line 48 of file g_etbot_interface.h.
Referenced by ETInterface::GetModName().
#define OMNIBOT_MODVERSION ETLEGACY_VERSION_SHORT
Definition at line 49 of file g_etbot_interface.h.
Referenced by ETInterface::GetModVers().
#define OMNIBOT_NAME "Legacy"
Warning
IMPORTANT: when changed this has to be copied manually to GAMEVERSION (g_local.h)
Definition at line 46 of file g_etbot_interface.h.
Enumeration Type Documentation
enum BotFlagOptions
g_OmniBotFlags bits
Enumerator
OBF_DONT_XPSAVE
Disables XPSave for bots.
OBF_DONT_MOUNT_TANKS
Bots cannot mount tanks.
OBF_DONT_MOUNT_GUNS
Bots cannot mount emplaced guns.
OBF_DONT_SHOW_BOTCOUNT
Don't count bots.
OBF_GIBBING
Bots will target ungibbed enemies.
OBF_TRIGGER_MINES
Bots will trigger team and spotted mines.
OBF_SHOVING
Bots can use g_shove.
OBF_NEXT_FLAG
mod specific flags start from here
Definition at line 56 of file g_etbot_interface.h.
Function Documentation
const char* _GetEntityName (gentity_t * _ent)
Definition at line 6533 of file g_etbot_interface.cpp.
Referenced by Bot_AddFallenTeammateGoals(), Bot_Util_CheckForGoalEntity(), checkpoint_spawntouch(), G_Script_ScriptEvent(), G_ScriptAction_FaceAngles(), G_ScriptAction_GotoMarker(), G_ScriptAction_ObjectiveStatus(), ETInterface::GetEntityName(), ETInterface::GetGoals(), GetMG42s(), SetMoverState(), Team_ResetFlag(), Team_TouchOurFlag(), and Weapon_Engineer().
void AddDeferredGoal (gentity_t * ent)
void Bot_AddDynamiteGoal (gentity_t * _ent, int _team, const char * _tag)
Definition at line 7171 of file g_etbot_interface.cpp.
Referenced by Weapon_Engineer().
void Bot_AddFallenTeammateGoals (gentity_t * _teammate, int _team)
Definition at line 7183 of file g_etbot_interface.cpp.
Referenced by player_die().
void Bot_Event_AddWeapon (int _client, int _weaponId)
Definition at line 6701 of file g_etbot_interface.cpp.
Referenced by _et_AddWeaponToPlayer(), AddWeaponToPlayer(), Pickup_Weapon(), and ReTransmitWeapons().
void Bot_Event_ChatMessage (int _client, gentity_t * _source, int _type, const char * _message)
Definition at line 6933 of file g_etbot_interface.cpp.
Referenced by G_SayTo().
void Bot_Event_ClientConnected (int _client, qboolean _isbot)
Definition at line 6670 of file g_etbot_interface.cpp.
Referenced by ClientConnect().
void Bot_Event_ClientDisConnected (int _client)
Definition at line 6681 of file g_etbot_interface.cpp.
Referenced by ClientDisconnect().
void Bot_Event_Death (int _client, gentity_t * _killer, const char * _meansofdeath)
Definition at line 6806 of file g_etbot_interface.cpp.
Referenced by player_die().
void Bot_Event_EntityDeleted (gentity_t * pEnt)
Definition at line 7132 of file g_etbot_interface.cpp.
Referenced by G_FreeEntity().
void Bot_Event_FireTeam_Proposal (int _client, int _proposed)
Definition at line 7061 of file g_etbot_interface.cpp.
Referenced by G_ProposeFireTeamPlayer().
void Bot_Event_FireTeam_Warn (int _client, int _warned)
Definition at line 7073 of file g_etbot_interface.cpp.
Referenced by G_WarnFireTeamPlayer().
void Bot_Event_FireTeamCreated (int _client, int _fireteamnum)
Definition at line 7001 of file g_etbot_interface.cpp.
Referenced by G_RegisterFireteam().
void Bot_Event_FireTeamDestroyed (int _client)
Definition at line 7013 of file g_etbot_interface.cpp.
Referenced by G_DestroyFireteam().
void Bot_Event_FireWeapon (int _client, int _weaponId, gentity_t * _projectile)
Definition at line 6873 of file g_etbot_interface.cpp.
Referenced by FireWeapon(), Weapon_Artillery(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void Bot_Event_Healed (int _client, gentity_t * _whodoneit)
Definition at line 6821 of file g_etbot_interface.cpp.
Referenced by Pickup_Health().
void Bot_Event_InviteFireTeam (int _inviter, int _invitee)
Definition at line 7049 of file g_etbot_interface.cpp.
Referenced by G_InviteToFireTeam().
void Bot_Event_JoinedFireTeam (int _client, gentity_t * leader)
Definition at line 7025 of file g_etbot_interface.cpp.
Referenced by G_AddClientToFireteam(), and G_RegisterFireteam().
void Bot_Event_KilledSomeone (int _client, gentity_t * _victim, const char * _meansofdeath)
Definition at line 6857 of file g_etbot_interface.cpp.
Referenced by player_die().
void Bot_Event_LeftFireTeam (int _client)
Definition at line 7037 of file g_etbot_interface.cpp.
Referenced by G_KickFireTeamPlayer(), and G_RemoveClientFromFireteams().
void Bot_Event_MortarImpact (int _client, vec3_t _pos)
Definition at line 6909 of file g_etbot_interface.cpp.
void Bot_Event_PostTriggerMine (int _client, gentity_t * _mine)
Definition at line 6897 of file g_etbot_interface.cpp.
Referenced by LandminePostThink().
void Bot_Event_PreTriggerMine (int _client, gentity_t * _mine)
Definition at line 6885 of file g_etbot_interface.cpp.
Referenced by G_LandmineThink().
void Bot_Event_RecievedAmmo (int _client, gentity_t * _whodoneit)
Definition at line 6833 of file g_etbot_interface.cpp.
Referenced by Pickup_Weapon().
void Bot_Event_RemoveWeapon (int _client, int _weaponId)
Definition at line 6780 of file g_etbot_interface.cpp.
Referenced by _et_RemoveWeaponFromPlayer(), and G_DropWeapon().
void Bot_Event_ResetWeapons (int _client)
Definition at line 6690 of file g_etbot_interface.cpp.
Referenced by ReTransmitWeapons(), and SetWolfSpawnWeapons().
void Bot_Event_Revived (int _client, gentity_t * _whodoneit)
Definition at line 6845 of file g_etbot_interface.cpp.
Referenced by ReviveEntity().
void Bot_Event_Sound (gentity_t * _source, int _sndtype, const char * _name)
Definition at line 6988 of file g_etbot_interface.cpp.
void Bot_Event_Spectated (int _client, int _who)
Definition at line 6921 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_Update().
void Bot_Event_TakeDamage (int _client, gentity_t * _ent)
Definition at line 6794 of file g_etbot_interface.cpp.
Referenced by G_Damage().
void Bot_Event_VoiceMacro (int _client, gentity_t * _source, int _type, const char * _message)
Definition at line 6963 of file g_etbot_interface.cpp.
Referenced by G_VoiceTo().
void Bot_Interface_ConsoleCommand (void)
Definition at line 6339 of file g_etbot_interface.cpp.
int Bot_Interface_Init ()
Definition at line 6301 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_ConsoleCommand(), and vmMain().
void Bot_Interface_InitHandles ()
Definition at line 6291 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_ConsoleCommand(), and vmMain().
int Bot_Interface_Shutdown ()
Definition at line 6327 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_ConsoleCommand(), and G_ShutdownGame().
void Bot_Interface_Update ()
Definition at line 6384 of file g_etbot_interface.cpp.
Referenced by vmMain().
int Bot_PlayerClassGameToBot (int playerClass)
Definition at line 589 of file g_etbot_interface.cpp.
Referenced by _GetEntityClass(), ETInterface::ChangeClass(), and ETInterface::ChangeTeam().
void Bot_Queue_EntityCreated (gentity_t * pEnt)
Definition at line 7125 of file g_etbot_interface.cpp.
Referenced by G_InitGentity().
int Bot_TeamGameToBot (int team)
Definition at line 555 of file g_etbot_interface.cpp.
Referenced by _GetEntityTeam(), ETInterface::ChangeClass(), ETInterface::ChangeTeam(), and ETInterface::InterfaceSendMessage().
qboolean Bot_Util_AllowPush (int weaponId)
Definition at line 6514 of file g_etbot_interface.cpp.
Referenced by PushBot().
qboolean Bot_Util_CheckForSuicide (gentity_t * ent)
Definition at line 6638 of file g_etbot_interface.cpp.
Referenced by ClientThink_real().
void Bot_Util_SendTrigger (gentity_t * _ent, gentity_t * _activator, const char * _tagname, const char * _action)
Definition at line 7159 of file g_etbot_interface.cpp.
int Bot_WeaponGameToBot (int weapon)
Definition at line 763 of file g_etbot_interface.cpp.
Referenced by _et_AddWeaponToPlayer(), _et_RemoveWeaponFromPlayer(), _GetEntityClass(), AddWeaponToPlayer(), FireWeapon(), G_DropWeapon(), ETInterface::InterfaceSendMessage(), Pickup_Weapon(), ReTransmitWeapons(), Weapon_Artillery(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void GetEntityCenter (gentity_t * ent, vec3_t pos)
Definition at line 300 of file g_etbot_interface.cpp.
Referenced by CheckForMG42(), GetMG42s(), and UpdateMG42().
void UpdateGoalEntity (gentity_t * oldent, gentity_t * newent)
Definition at line 201 of file g_etbot_interface.cpp.