ET: Legacy: src/game/g_etbot_interface.cpp File Reference
g_etbot_interface.cpp File Reference
ET <-> Omni-Bot interface source file.
#include <sstream>
#include <iomanip>
#include "g_etbot_interface.h"
#include "../Omnibot/Common/BotExports.h"
#include "../Omnibot/ET/ET_Config.h"
#include "../Omnibot/ET/ET_Messages.h"
Data Structures
struct BotEntity
struct mg42s_t
class ETInterface
Macros
#define OMNIBOT_MIN_ENG 2
#define OMNIBOT_MIN_MED 2
#define OMNIBOT_MIN_FOP 2
#define OMNIBOT_MIN_SOL 2
#define OMNIBOT_MIN_COP 1
#define WC_WEAPON_TIME_LEFT level.time - ps->classWeaponTime
#define WC_SOLDIER_TIME level.soldierChargeTime[team - TEAM_AXIS]
#define WC_ENGINEER_TIME level.engineerChargeTime[team - TEAM_AXIS]
#define WC_FIELDOPS_TIME level.fieldopsChargeTime[team - TEAM_AXIS]
#define WC_MEDIC_TIME level.medicChargeTime[team - TEAM_AXIS]
#define WC_COVERTOPS_TIME level.covertopsChargeTime[team - TEAM_AXIS]
#define MAX_SMOKE_RADIUS 320.0f
#define MAX_SMOKE_RADIUS_TIME 10000.0f
#define UNAFFECTED_BY_SMOKE_DIST Square(100)
Functions
qboolean G_IsOnFireteam (int entityNum, fireteamData_t **teamNum)
G_IsOnFireteam.
void Bot_Event_EntityCreated (gentity_t *pEnt)
bool IsBot (gentity_t *e)
gentity_t * INDEXENT (const int _gameId)
int ENTINDEX (gentity_t *_ent)
gentity_t * EntityFromHandle (GameEntity _ent)
GameEntity HandleFromEntity (gentity_t *_ent)
void UpdateGoalEntity (gentity_t *oldent, gentity_t *newent)
void DeleteMapGoal (char *name)
void GetMG42s ()
void UpdateMG42 (gentity_t *ent)
void CheckForMG42 (gentity_t *ent, const char *newname)
void GetEntityCenter (gentity_t *ent, vec3_t pos)
static qboolean weaponCharged (playerState_t *ps, team_t team, int weapon, int *skill)
static int CountPlayerClass (team_t team, int playerClass, int ignore)
int Bot_TeamGameToBot (int team)
static int playerClassBotToGame (int playerClass)
int Bot_PlayerClassGameToBot (int playerClass)
static weapon_t _weaponBotToGame (int weapon)
int Bot_WeaponGameToBot (int weapon)
static int Bot_HintGameToBot (gentity_t *_ent)
qboolean Simple_EmplacedGunIsRepairable (gentity_t *ent)
static int _choosePriWeap (gentity_t *bot, int playerClass, int team)
static int _chooseSecWeap (gentity_t *bot, int playerClass, int team)
static void ReTransmitWeapons (const gentity_t *bot)
gentity_t * Bot_EntInvisibleBySmokeBomb (vec3_t start, vec3_t end)
void Bot_Util_AddGoal (const char *_type, gentity_t *_ent, int _team, const char *_tag, const char *_extrakey=0, obUserData *_extraval=0)
static int _GetEntityTeam (gentity_t *_ent)
static int _GetEntityClass (gentity_t *_ent)
qboolean _TankIsMountable (gentity_t *_ent)
qboolean _EmplacedGunIsMountable (gentity_t *_ent)
void Omnibot_Load_PrintMsg (const char *_msg)
void Omnibot_Load_PrintErr (const char *_msg)
int obUtilBotContentsFromGameContents (int _contents)
int obUtilBotSurfaceFromGameSurface (int _surfaceflags)
void Bot_Util_CheckForGoalEntity (GameEntity _ent)
qboolean InFieldOfVision (vec3_t viewangles, float fov, vec3_t angles)
void Bot_Interface_InitHandles ()
int Bot_Interface_Init ()
int Bot_Interface_Shutdown ()
void Bot_Interface_ConsoleCommand (void)
void script_mover_spawn (gentity_t *ent)
script_mover_spawn
void Bot_Interface_Update ()
qboolean Bot_Util_AllowPush (int weaponId)
const char * _GetEntityName (gentity_t *_ent)
qboolean Bot_Util_CheckForSuicide (gentity_t *ent)
void Bot_Event_ClientConnected (int _client, qboolean _isbot)
void Bot_Event_ClientDisConnected (int _client)
void Bot_Event_ResetWeapons (int _client)
void Bot_Event_AddWeapon (int _client, int _weaponId)
void Bot_Event_RemoveWeapon (int _client, int _weaponId)
void Bot_Event_TakeDamage (int _client, gentity_t *_ent)
void Bot_Event_Death (int _client, gentity_t *_killer, const char *_meansofdeath)
void Bot_Event_Healed (int _client, gentity_t *_whodoneit)
void Bot_Event_RecievedAmmo (int _client, gentity_t *_whodoneit)
void Bot_Event_Revived (int _client, gentity_t *_whodoneit)
void Bot_Event_KilledSomeone (int _client, gentity_t *_victim, const char *_meansofdeath)
void Bot_Event_FireWeapon (int _client, int _weaponId, gentity_t *_projectile)
void Bot_Event_PreTriggerMine (int _client, gentity_t *_mine)
void Bot_Event_PostTriggerMine (int _client, gentity_t *_mine)
void Bot_Event_MortarImpact (int _client, vec3_t _pos)
void Bot_Event_Spectated (int _client, int _who)
void Bot_Event_ChatMessage (int _client, gentity_t *_source, int _type, const char *_message)
void Bot_Event_VoiceMacro (int _client, gentity_t *_source, int _type, const char *_message)
void Bot_Event_Sound (gentity_t *_source, int _sndtype, const char *_name)
void Bot_Event_FireTeamCreated (int _client, int _fireteamnum)
void Bot_Event_FireTeamDestroyed (int _client)
void Bot_Event_JoinedFireTeam (int _client, gentity_t *leader)
void Bot_Event_LeftFireTeam (int _client)
void Bot_Event_InviteFireTeam (int _inviter, int _invitee)
void Bot_Event_FireTeam_Proposal (int _client, int _proposed)
void Bot_Event_FireTeam_Warn (int _client, int _warned)
void Bot_Queue_EntityCreated (gentity_t *pEnt)
void Bot_Event_EntityDeleted (gentity_t *pEnt)
void Bot_Util_SendTrigger (gentity_t *_ent, gentity_t *_activator, const char *_tagname, const char *_action)
void Bot_AddDynamiteGoal (gentity_t *_ent, int _team, const char *_tag)
void Bot_AddFallenTeammateGoals (gentity_t *_teammate, int _team)
Variables
const int MAX_SMOKEGREN_CACHE = 32
gentity_t * g_SmokeGrenadeCache [MAX_SMOKEGREN_CACHE] = { 0 }
BotEntity m_EntityHandles [MAX_GENTITIES]
bool g_GoalSubmitReady = false
mg42s_t mg42s [64]
int numofmg42s
int g_LastScreenMessageTime = 0
Detailed Description
ET <-> Omni-Bot interface source file.
Definition in file g_etbot_interface.cpp.
Macro Definition Documentation
#define MAX_SMOKE_RADIUS 320.0f
Definition at line 1579 of file g_etbot_interface.cpp.
Referenced by Bot_EntInvisibleBySmokeBomb().
#define MAX_SMOKE_RADIUS_TIME 10000.0f
Definition at line 1580 of file g_etbot_interface.cpp.
Referenced by Bot_EntInvisibleBySmokeBomb().
#define OMNIBOT_MIN_COP 1
Definition at line 50 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
#define OMNIBOT_MIN_ENG 2
Definition at line 46 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
#define OMNIBOT_MIN_FOP 2
Definition at line 48 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
#define OMNIBOT_MIN_MED 2
Definition at line 47 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
#define OMNIBOT_MIN_SOL 2
Definition at line 49 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
#define UNAFFECTED_BY_SMOKE_DIST Square(100)
Definition at line 1581 of file g_etbot_interface.cpp.
Referenced by Bot_EntInvisibleBySmokeBomb().
#define WC_COVERTOPS_TIME level.covertopsChargeTime[team - TEAM_AXIS]
Definition at line 86 of file g_etbot_interface.cpp.
Referenced by weaponCharged().
#define WC_ENGINEER_TIME level.engineerChargeTime[team - TEAM_AXIS]
Definition at line 79 of file g_etbot_interface.cpp.
Referenced by weaponCharged().
#define WC_FIELDOPS_TIME level.fieldopsChargeTime[team - TEAM_AXIS]
Definition at line 81 of file g_etbot_interface.cpp.
Referenced by weaponCharged().
#define WC_MEDIC_TIME level.medicChargeTime[team - TEAM_AXIS]
Definition at line 85 of file g_etbot_interface.cpp.
Referenced by weaponCharged().
#define WC_SOLDIER_TIME level.soldierChargeTime[team - TEAM_AXIS]
Definition at line 78 of file g_etbot_interface.cpp.
Referenced by weaponCharged().
#define WC_WEAPON_TIME_LEFT level.time - ps->classWeaponTime
Definition at line 77 of file g_etbot_interface.cpp.
Referenced by weaponCharged().
Function Documentation
static int _choosePriWeap (gentity_t * bot, int playerClass, int team) static
Definition at line 1053 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass(), and ETInterface::ChangeTeam().
static int _chooseSecWeap (gentity_t * bot, int playerClass, int team) static
Definition at line 1313 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass(), and ETInterface::ChangeTeam().
qboolean _EmplacedGunIsMountable (gentity_t * _ent)
Definition at line 1983 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetEntityFlags().
static int _GetEntityClass (gentity_t * _ent) static
Definition at line 1703 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetEntityClass().
const char* _GetEntityName (gentity_t * _ent)
Definition at line 6533 of file g_etbot_interface.cpp.
Referenced by Bot_AddFallenTeammateGoals(), Bot_Util_CheckForGoalEntity(), checkpoint_spawntouch(), G_Script_ScriptEvent(), G_ScriptAction_FaceAngles(), G_ScriptAction_GotoMarker(), G_ScriptAction_ObjectiveStatus(), ETInterface::GetEntityName(), ETInterface::GetGoals(), GetMG42s(), SetMoverState(), Team_ResetFlag(), Team_TouchOurFlag(), and Weapon_Engineer().
static int _GetEntityTeam (gentity_t * _ent) static
Todo:
: hack, when the game joins clients again after warmup, they are temporarily ET_GENERAL entities(LAME)
Definition at line 1667 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetEntityTeam(), and ETInterface::InterfaceSendMessage().
qboolean _TankIsMountable (gentity_t * _ent)
Definition at line 1956 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetEntityFlags().
static weapon_t _weaponBotToGame (int weapon) static
Definition at line 608 of file g_etbot_interface.cpp.
Referenced by _choosePriWeap(), _chooseSecWeap(), ETInterface::ChangeClass(), ETInterface::ChangeTeam(), ETInterface::GetCurrentAmmo(), ETInterface::InterfaceSendMessage(), and ETInterface::UpdateBotInput().
void Bot_AddDynamiteGoal (gentity_t * _ent, int _team, const char * _tag)
Definition at line 7171 of file g_etbot_interface.cpp.
Referenced by Weapon_Engineer().
void Bot_AddFallenTeammateGoals (gentity_t * _teammate, int _team)
Definition at line 7183 of file g_etbot_interface.cpp.
Referenced by player_die().
gentity_t* Bot_EntInvisibleBySmokeBomb (vec3_t start, vec3_t end)
Definition at line 1583 of file g_etbot_interface.cpp.
Referenced by ETInterface::TraceLine().
void Bot_Event_AddWeapon (int _client, int _weaponId)
Definition at line 6701 of file g_etbot_interface.cpp.
Referenced by _et_AddWeaponToPlayer(), AddWeaponToPlayer(), Pickup_Weapon(), and ReTransmitWeapons().
void Bot_Event_ChatMessage (int _client, gentity_t * _source, int _type, const char * _message)
Definition at line 6933 of file g_etbot_interface.cpp.
Referenced by G_SayTo().
void Bot_Event_ClientConnected (int _client, qboolean _isbot)
Definition at line 6670 of file g_etbot_interface.cpp.
Referenced by ClientConnect().
void Bot_Event_ClientDisConnected (int _client)
Definition at line 6681 of file g_etbot_interface.cpp.
Referenced by ClientDisconnect().
void Bot_Event_Death (int _client, gentity_t * _killer, const char * _meansofdeath)
Definition at line 6806 of file g_etbot_interface.cpp.
Referenced by player_die().
void Bot_Event_EntityCreated (gentity_t * pEnt)
Definition at line 7085 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_Update().
void Bot_Event_EntityDeleted (gentity_t * pEnt)
Definition at line 7132 of file g_etbot_interface.cpp.
Referenced by G_FreeEntity().
void Bot_Event_FireTeam_Proposal (int _client, int _proposed)
Definition at line 7061 of file g_etbot_interface.cpp.
Referenced by G_ProposeFireTeamPlayer().
void Bot_Event_FireTeam_Warn (int _client, int _warned)
Definition at line 7073 of file g_etbot_interface.cpp.
Referenced by G_WarnFireTeamPlayer().
void Bot_Event_FireTeamCreated (int _client, int _fireteamnum)
Definition at line 7001 of file g_etbot_interface.cpp.
Referenced by G_RegisterFireteam().
void Bot_Event_FireTeamDestroyed (int _client)
Definition at line 7013 of file g_etbot_interface.cpp.
Referenced by G_DestroyFireteam().
void Bot_Event_FireWeapon (int _client, int _weaponId, gentity_t * _projectile)
Definition at line 6873 of file g_etbot_interface.cpp.
Referenced by FireWeapon(), Weapon_Artillery(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void Bot_Event_Healed (int _client, gentity_t * _whodoneit)
Definition at line 6821 of file g_etbot_interface.cpp.
Referenced by Pickup_Health().
void Bot_Event_InviteFireTeam (int _inviter, int _invitee)
Definition at line 7049 of file g_etbot_interface.cpp.
Referenced by G_InviteToFireTeam().
void Bot_Event_JoinedFireTeam (int _client, gentity_t * leader)
Definition at line 7025 of file g_etbot_interface.cpp.
Referenced by G_AddClientToFireteam(), and G_RegisterFireteam().
void Bot_Event_KilledSomeone (int _client, gentity_t * _victim, const char * _meansofdeath)
Definition at line 6857 of file g_etbot_interface.cpp.
Referenced by player_die().
void Bot_Event_LeftFireTeam (int _client)
Definition at line 7037 of file g_etbot_interface.cpp.
Referenced by G_KickFireTeamPlayer(), and G_RemoveClientFromFireteams().
void Bot_Event_MortarImpact (int _client, vec3_t _pos)
Definition at line 6909 of file g_etbot_interface.cpp.
void Bot_Event_PostTriggerMine (int _client, gentity_t * _mine)
Definition at line 6897 of file g_etbot_interface.cpp.
Referenced by LandminePostThink().
void Bot_Event_PreTriggerMine (int _client, gentity_t * _mine)
Definition at line 6885 of file g_etbot_interface.cpp.
Referenced by G_LandmineThink().
void Bot_Event_RecievedAmmo (int _client, gentity_t * _whodoneit)
Definition at line 6833 of file g_etbot_interface.cpp.
Referenced by Pickup_Weapon().
void Bot_Event_RemoveWeapon (int _client, int _weaponId)
Definition at line 6780 of file g_etbot_interface.cpp.
Referenced by _et_RemoveWeaponFromPlayer(), and G_DropWeapon().
void Bot_Event_ResetWeapons (int _client)
Definition at line 6690 of file g_etbot_interface.cpp.
Referenced by ReTransmitWeapons(), and SetWolfSpawnWeapons().
void Bot_Event_Revived (int _client, gentity_t * _whodoneit)
Definition at line 6845 of file g_etbot_interface.cpp.
Referenced by ReviveEntity().
void Bot_Event_Sound (gentity_t * _source, int _sndtype, const char * _name)
Definition at line 6988 of file g_etbot_interface.cpp.
void Bot_Event_Spectated (int _client, int _who)
Definition at line 6921 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_Update().
void Bot_Event_TakeDamage (int _client, gentity_t * _ent)
Definition at line 6794 of file g_etbot_interface.cpp.
Referenced by G_Damage().
void Bot_Event_VoiceMacro (int _client, gentity_t * _source, int _type, const char * _message)
Definition at line 6963 of file g_etbot_interface.cpp.
Referenced by G_VoiceTo().
static int Bot_HintGameToBot (gentity_t * _ent) static
Definition at line 918 of file g_etbot_interface.cpp.
Referenced by ETInterface::InterfaceSendMessage().
void Bot_Interface_ConsoleCommand (void)
Definition at line 6339 of file g_etbot_interface.cpp.
int Bot_Interface_Init ()
Definition at line 6301 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_ConsoleCommand(), and vmMain().
void Bot_Interface_InitHandles ()
Definition at line 6291 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_ConsoleCommand(), and vmMain().
int Bot_Interface_Shutdown ()
Definition at line 6327 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_ConsoleCommand(), and G_ShutdownGame().
void Bot_Interface_Update ()
Definition at line 6384 of file g_etbot_interface.cpp.
Referenced by vmMain().
int Bot_PlayerClassGameToBot (int playerClass)
Definition at line 589 of file g_etbot_interface.cpp.
Referenced by _GetEntityClass(), ETInterface::ChangeClass(), and ETInterface::ChangeTeam().
void Bot_Queue_EntityCreated (gentity_t * pEnt)
Definition at line 7125 of file g_etbot_interface.cpp.
Referenced by G_InitGentity().
int Bot_TeamGameToBot (int team)
Definition at line 555 of file g_etbot_interface.cpp.
Referenced by _GetEntityTeam(), ETInterface::ChangeClass(), ETInterface::ChangeTeam(), and ETInterface::InterfaceSendMessage().
void Bot_Util_AddGoal (const char * _type, gentity_t * _ent, int _team, const char * _tag, const char * _extrakey = 0, obUserData * _extraval = 0)
Definition at line 1648 of file g_etbot_interface.cpp.
Referenced by Bot_AddDynamiteGoal(), Bot_AddFallenTeammateGoals(), Bot_Util_CheckForGoalEntity(), and ETInterface::GetGoals().
qboolean Bot_Util_AllowPush (int weaponId)
Definition at line 6514 of file g_etbot_interface.cpp.
Referenced by PushBot().
void Bot_Util_CheckForGoalEntity (GameEntity _ent)
Definition at line 2060 of file g_etbot_interface.cpp.
Referenced by Bot_Event_EntityCreated().
qboolean Bot_Util_CheckForSuicide (gentity_t * ent)
Definition at line 6638 of file g_etbot_interface.cpp.
Referenced by ClientThink_real().
void Bot_Util_SendTrigger (gentity_t * _ent, gentity_t * _activator, const char * _tagname, const char * _action)
Definition at line 7159 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_Update(), checkpoint_spawntouch(), G_DropItems(), G_LogExit(), G_Script_ScriptEvent(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_FaceAngles(), G_ScriptAction_GotoMarker(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_RepairMG42(), G_ScriptAction_TeamVoiceAnnounce(), SetMoverState(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), Touch_flagonly(), Touch_flagonly_multiple(), and Use_BinaryMover().
int Bot_WeaponGameToBot (int weapon)
Definition at line 763 of file g_etbot_interface.cpp.
Referenced by _et_AddWeaponToPlayer(), _et_RemoveWeaponFromPlayer(), _GetEntityClass(), AddWeaponToPlayer(), FireWeapon(), G_DropWeapon(), ETInterface::InterfaceSendMessage(), Pickup_Weapon(), ReTransmitWeapons(), Weapon_Artillery(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void CheckForMG42 (gentity_t * ent, const char * newname)
Definition at line 276 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetGoals().
static int CountPlayerClass (team_t team, int playerClass, int ignore) static
Definition at line 527 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
void DeleteMapGoal (char * name)
Definition at line 209 of file g_etbot_interface.cpp.
int ENTINDEX (gentity_t * _ent)
Definition at line 105 of file g_etbot_interface.cpp.
Referenced by ETInterface::InterfaceSendMessage().
gentity_t* EntityFromHandle (GameEntity _ent)
Definition at line 110 of file g_etbot_interface.cpp.
Referenced by Bot_Util_CheckForGoalEntity(), ETInterface::DoesEntityStillExist(), ETInterface::FindEntityInSphere(), ETInterface::GetCurrentAmmo(), ETInterface::GetCurrentWeaponClip(), ETInterface::GetEntityCategory(), ETInterface::GetEntityClass(), ETInterface::GetEntityEyePosition(), ETInterface::GetEntityFlags(), ETInterface::GetEntityGroundEntity(), ETInterface::GetEntityLocalAABB(), ETInterface::GetEntityName(), ETInterface::GetEntityOrientation(), ETInterface::GetEntityOwner(), ETInterface::GetEntityPosition(), ETInterface::GetEntityTeam(), ETInterface::GetEntityVelocity(), ETInterface::GetEntityWorldAABB(), ETInterface::GetEntityWorldOBB(), ETInterface::IDFromEntity(), and ETInterface::InterfaceSendMessage().
qboolean G_IsOnFireteam (int entityNum, fireteamData_t ** teamNum)
G_IsOnFireteam.
Parameters
[in] entityNum
[out] teamNum
Returns
Definition at line 211 of file g_fireteams.c.
Referenced by G_AddClientToFireteam(), G_ApplyToFireTeam(), G_GiveAdminOfFireTeam(), G_InviteToFireTeam(), G_KickFireTeamPlayer(), G_ProposeFireTeamPlayer(), G_RegisterFireteam(), G_RemoveClientFromFireteams(), G_WarnFireTeamPlayer(), and ETInterface::InterfaceSendMessage().
void GetEntityCenter (gentity_t * ent, vec3_t pos)
Definition at line 300 of file g_etbot_interface.cpp.
Referenced by CheckForMG42(), GetMG42s(), and UpdateMG42().
void GetMG42s ()
Definition at line 226 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetGoals().
GameEntity HandleFromEntity (gentity_t * _ent)
Definition at line 131 of file g_etbot_interface.cpp.
Referenced by Bot_Event_ChatMessage(), Bot_Event_Death(), Bot_Event_EntityCreated(), Bot_Event_FireTeam_Proposal(), Bot_Event_FireTeam_Warn(), Bot_Event_FireWeapon(), Bot_Event_Healed(), Bot_Event_InviteFireTeam(), Bot_Event_JoinedFireTeam(), Bot_Event_KilledSomeone(), Bot_Event_PostTriggerMine(), Bot_Event_PreTriggerMine(), Bot_Event_RecievedAmmo(), Bot_Event_Revived(), Bot_Event_Sound(), Bot_Event_TakeDamage(), Bot_Event_VoiceMacro(), Bot_Util_AddGoal(), Bot_Util_SendTrigger(), ETInterface::EntityByName(), ETInterface::EntityFromID(), ETInterface::FindEntityInSphere(), ETInterface::GetEntityGroundEntity(), ETInterface::GetEntityOwner(), ETInterface::GetPlayerInfo(), ETInterface::InterfaceSendMessage(), ETInterface::TraceLine(), and UpdateGoalEntity().
gentity_t* INDEXENT (const int _gameId)
Definition at line 90 of file g_etbot_interface.cpp.
Referenced by ETInterface::EntityFromID().
qboolean InFieldOfVision (vec3_t viewangles, float fov, vec3_t angles)
Definition at line 2107 of file g_etbot_interface.cpp.
bool IsBot (gentity_t * e)
Definition at line 55 of file g_etbot_interface.cpp.
Referenced by Bot_Event_AddWeapon(), Bot_Event_ChatMessage(), Bot_Event_Death(), Bot_Event_FireTeam_Proposal(), Bot_Event_FireTeam_Warn(), Bot_Event_FireTeamCreated(), Bot_Event_FireTeamDestroyed(), Bot_Event_FireWeapon(), Bot_Event_Healed(), Bot_Event_InviteFireTeam(), Bot_Event_JoinedFireTeam(), Bot_Event_KilledSomeone(), Bot_Event_LeftFireTeam(), Bot_Event_MortarImpact(), Bot_Event_PostTriggerMine(), Bot_Event_PreTriggerMine(), Bot_Event_RecievedAmmo(), Bot_Event_RemoveWeapon(), Bot_Event_ResetWeapons(), Bot_Event_Revived(), Bot_Event_Spectated(), Bot_Event_TakeDamage(), Bot_Event_VoiceMacro(), Bot_Interface_Update(), ETInterface::GetEntityFlags(), ETInterface::GetPlayerInfo(), and ETInterface::RemoveBot().
int obUtilBotContentsFromGameContents (int _contents)
Definition at line 2004 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetPointContents(), and ETInterface::TraceLine().
int obUtilBotSurfaceFromGameSurface (int _surfaceflags)
Definition at line 2046 of file g_etbot_interface.cpp.
Referenced by ETInterface::TraceLine().
void Omnibot_Load_PrintErr (const char * _msg)
Definition at line 1997 of file g_etbot_interface.cpp.
Referenced by Omnibot_strncpy().
void Omnibot_Load_PrintMsg (const char * _msg)
Definition at line 1992 of file g_etbot_interface.cpp.
Referenced by Omnibot_strncpy().
static int playerClassBotToGame (int playerClass) static
Definition at line 570 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
static void ReTransmitWeapons (const gentity_t * bot) static
Definition at line 1561 of file g_etbot_interface.cpp.
Referenced by ETInterface::ChangeClass().
void script_mover_spawn (gentity_t * ent)
script_mover_spawn
Parameters
[in,out] ent
Definition at line 1007 of file g_script.c.
Referenced by Bot_Interface_ConsoleCommand(), Bot_Interface_Update(), script_mover_use(), and SP_script_mover().
qboolean Simple_EmplacedGunIsRepairable (gentity_t * ent)
Definition at line 1040 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetEntityFlags(), and ETInterface::InterfaceSendMessage().
void UpdateGoalEntity (gentity_t * oldent, gentity_t * newent)
Definition at line 201 of file g_etbot_interface.cpp.
Referenced by mg42_spawn(), and mg42_use().
void UpdateMG42 (gentity_t * ent)
Definition at line 252 of file g_etbot_interface.cpp.
Referenced by ETInterface::GetGoals().
static qboolean weaponCharged (playerState_t * ps, team_t team, int weapon, int * skill) static
Definition at line 319 of file g_etbot_interface.cpp.
Referenced by ETInterface::InterfaceSendMessage().
Variable Documentation
bool g_GoalSubmitReady = false
Definition at line 144 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_Init(), ETInterface::GetGoals(), and UpdateGoalEntity().
int g_LastScreenMessageTime = 0
Definition at line 2002 of file g_etbot_interface.cpp.
gentity_t* g_SmokeGrenadeCache[MAX_SMOKEGREN_CACHE] = { 0 }
Definition at line 63 of file g_etbot_interface.cpp.
BotEntity m_EntityHandles[MAX_GENTITIES]
Definition at line 72 of file g_etbot_interface.cpp.
const int MAX_SMOKEGREN_CACHE = 32
Definition at line 62 of file g_etbot_interface.cpp.
Referenced by Bot_EntInvisibleBySmokeBomb(), Bot_Event_EntityCreated(), and Bot_Event_EntityDeleted().
mg42s_t mg42s[64]
Definition at line 223 of file g_etbot_interface.cpp.
int numofmg42s
Definition at line 224 of file g_etbot_interface.cpp.
Referenced by CheckForMG42(), ETInterface::GetGoals(), GetMG42s(), and UpdateMG42().