ET: Legacy: src/game/g_fireteams.c File Reference
g_fireteams.c File Reference
#include "g_local.h"
#include "g_etbot_interface.h"
Macros
#define G_ClientPrint(entityNum, text) trap_SendServerCommand(entityNum, "cpm \"" text "\"\n");
Functions
fireteamData_t * G_FindFreeFireteam (void)
G_FindFreeFireteam.
team_t G_GetFireteamTeam (fireteamData_t *ft)
G_GetFireteamTeam.
int G_CountTeamFireteams (team_t team)
G_CountTeamFireteams.
int G_CountFireteamMembers (fireteamData_t *ft)
G_CountFireteamMembers.
void G_UpdateFireteamConfigString (fireteamData_t *ft)
G_UpdateFireteamConfigString.
qboolean G_IsOnFireteam (int entityNum, fireteamData_t **teamNum)
G_IsOnFireteam.
qboolean G_IsFireteamLeader (int entityNum, fireteamData_t **teamNum)
G_IsFireteamLeader.
int G_FindFreeFireteamIdent (team_t team)
G_FindFreeFireteamIdent.
void G_RegisterFireteam (int entityNum)
Should be the only function that ever creates a fireteam.
void G_AddClientToFireteam (int entityNum, int leaderNum)
Only way a client should ever join a fireteam, other than creating one.
qboolean G_OnlyBotsInFireteam (fireteamData_t *ft, int excludeEntityNum, int *firstHuman)
Check if the fireteam contains only bots.
void G_RemoveClientFromFireteams (int entityNum, qboolean update, qboolean print)
The only way a client should be removed from a fireteam.
void G_InviteToFireTeam (int entityNum, int otherEntityNum)
The only way a client should ever be invited to join a team.
void G_DestroyFireteam (int entityNum)
G_DestroyFireteam.
void G_WarnFireTeamPlayer (int entityNum, int otherEntityNum)
G_WarnFireTeamPlayer.
void G_KickFireTeamPlayer (int entityNum, int otherEntityNum)
G_KickFireTeamPlayer.
void G_ApplyToFireTeam (int entityNum, int fireteamNum)
The only way a client should ever apply to join a team.
void G_ProposeFireTeamPlayer (int entityNum, int otherEntityNum)
G_ProposeFireTeamPlayer.
int G_FireteamNumberForString (const char *name, team_t team)
G_FireteamNumberForString.
fireteamData_t * G_FindFreePublicFireteam (team_t team)
G_FindFreePublicFireteam.
void G_GiveAdminOfFireTeam (int entityNum, int otherEntityNum)
G_GiveAdminOfFireTeam.
void Cmd_FireTeam_MP_f (gentity_t *ent)
Cmd_FireTeam_MP_f.
Macro Definition Documentation
#define G_ClientPrint (entityNum, text) trap_SendServerCommand(entityNum, "cpm \"" text "\"\n");
Definition at line 85 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), G_AddClientToFireteam(), G_ApplyToFireTeam(), G_DestroyFireteam(), G_GiveAdminOfFireTeam(), G_InviteToFireTeam(), G_KickFireTeamPlayer(), G_ProposeFireTeamPlayer(), G_RegisterFireteam(), and G_WarnFireTeamPlayer().
Function Documentation
void Cmd_FireTeam_MP_f (gentity_t * ent)
Cmd_FireTeam_MP_f.
Parameters
[in] ent
Definition at line 1086 of file g_fireteams.c.
Referenced by ClientCommand().
void G_AddClientToFireteam (int entityNum, int leaderNum)
Only way a client should ever join a fireteam, other than creating one.
Parameters
[in] entityNum
[in] leaderNum
Definition at line 411 of file g_fireteams.c.
Referenced by Cmd_Vote_f(), and G_InviteToFireTeam().
void G_ApplyToFireTeam (int entityNum, int fireteamNum)
The only way a client should ever apply to join a team.
Parameters
[in] entityNum
[in] fireteamNum
Definition at line 814 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().
int G_CountFireteamMembers (fireteamData_t * ft)
G_CountFireteamMembers.
Parameters
[in] ft
Returns
Definition at line 151 of file g_fireteams.c.
Referenced by G_AddClientToFireteam(), G_ApplyToFireTeam(), G_InviteToFireTeam(), and G_ProposeFireTeamPlayer().
int G_CountTeamFireteams (team_t team)
G_CountTeamFireteams.
Parameters
[in] team
Returns
Definition at line 131 of file g_fireteams.c.
Referenced by G_RegisterFireteam().
void G_DestroyFireteam (int entityNum)
G_DestroyFireteam.
Parameters
[in] entityNum
Definition at line 690 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().
fireteamData_t* G_FindFreeFireteam (void)
G_FindFreeFireteam.
Returns
Definition at line 91 of file g_fireteams.c.
Referenced by G_RegisterFireteam().
int G_FindFreeFireteamIdent (team_t team)
G_FindFreeFireteamIdent.
Parameters
[in] team
Returns
Definition at line 296 of file g_fireteams.c.
Referenced by G_RegisterFireteam().
fireteamData_t* G_FindFreePublicFireteam (team_t team)
G_FindFreePublicFireteam.
Parameters
[in] team
Returns
Definition at line 975 of file g_fireteams.c.
Referenced by Cmd_Vote_f(), and SetTeam().
int G_FireteamNumberForString (const char * name, team_t team)
G_FireteamNumberForString.
Parameters
[in] name
[in] team
Returns
Definition at line 936 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().
team_t G_GetFireteamTeam (fireteamData_t * ft)
G_GetFireteamTeam.
Parameters
[in] ft
Returns
Definition at line 111 of file g_fireteams.c.
Referenced by G_CountTeamFireteams().
void G_GiveAdminOfFireTeam (int entityNum, int otherEntityNum)
G_GiveAdminOfFireTeam.
Parameters
[in] entityNum
[in] otherEntityNum
Definition at line 1019 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().
void G_InviteToFireTeam (int entityNum, int otherEntityNum)
The only way a client should ever be invited to join a team.
Parameters
[in] entityNum
[in] otherEntityNum
Definition at line 630 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), Cmd_Vote_f(), and G_ProposeFireTeamPlayer().
qboolean G_IsFireteamLeader (int entityNum, fireteamData_t ** teamNum)
G_IsFireteamLeader.
Parameters
[in] entityNum
[out] teamNum
Returns
Definition at line 258 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), Cmd_Vote_f(), G_AddClientToFireteam(), G_DestroyFireteam(), G_GiveAdminOfFireTeam(), G_InviteToFireTeam(), G_KickFireTeamPlayer(), and G_WarnFireTeamPlayer().
qboolean G_IsOnFireteam (int entityNum, fireteamData_t ** teamNum)
G_IsOnFireteam.
Parameters
[in] entityNum
[out] teamNum
Returns
Definition at line 211 of file g_fireteams.c.
Referenced by G_AddClientToFireteam(), G_ApplyToFireTeam(), G_GiveAdminOfFireTeam(), G_InviteToFireTeam(), G_KickFireTeamPlayer(), G_ProposeFireTeamPlayer(), G_RegisterFireteam(), G_RemoveClientFromFireteams(), G_SayTo(), G_VoiceTo(), G_WarnFireTeamPlayer(), and ETInterface::InterfaceSendMessage().
void G_KickFireTeamPlayer (int entityNum, int otherEntityNum)
G_KickFireTeamPlayer.
Parameters
[in] entityNum
[in] otherEntityNum
Definition at line 769 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().
qboolean G_OnlyBotsInFireteam (fireteamData_t * ft, int excludeEntityNum, int * firstHuman)
Check if the fireteam contains only bots.
Parameters
[in] ft
[in] excludeEntityNum Will be excluded from the test (if -1, it has no effect)
[out] firstHuman returns the joinOrder of the first human found in the fireteam (-1 if none is found)
Returns
Definition at line 475 of file g_fireteams.c.
Referenced by G_RemoveClientFromFireteams().
void G_ProposeFireTeamPlayer (int entityNum, int otherEntityNum)
G_ProposeFireTeamPlayer.
Parameters
[in] entityNum
[in] otherEntityNum
Definition at line 868 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().
void G_RegisterFireteam (int entityNum)
Should be the only function that ever creates a fireteam.
Parameters
[in] entityNum
Definition at line 332 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), and Cmd_Vote_f().
void G_RemoveClientFromFireteams (int entityNum, qboolean update, qboolean print)
The only way a client should be removed from a fireteam.
Parameters
[in] entityNum
[in] update
[in] print
Definition at line 518 of file g_fireteams.c.
Referenced by ClientDisconnect(), Cmd_FireTeam_MP_f(), G_DestroyFireteam(), G_KickFireTeamPlayer(), G_shuffleTeamsXP(), and SetTeam().
void G_UpdateFireteamConfigString (fireteamData_t * ft)
G_UpdateFireteamConfigString.
Parameters
ft
Definition at line 177 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), Cmd_Vote_f(), G_AddClientToFireteam(), G_DestroyFireteam(), G_GiveAdminOfFireTeam(), G_InitWorldSession(), G_RegisterFireteam(), and G_RemoveClientFromFireteams().
void G_WarnFireTeamPlayer (int entityNum, int otherEntityNum)
G_WarnFireTeamPlayer.
Parameters
[in] entityNum
[in] otherEntityNum
Definition at line 726 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f().