ET: Legacy: src/game/g_items.c File Reference
g_items.c File Reference
Items are any object that a player can touch to gain some effect.
#include "g_local.h"
#include "g_etbot_interface.h"
Macros
#define RESPAWN_NEVER -1
#define RESPAWN_KEY 4
#define RESPAWN_ARMOR 25
#define RESPAWN_TEAM_WEAPON 30
#define RESPAWN_HEALTH 35
#define RESPAWN_AMMO 40
#define RESPAWN_HOLDABLE 60
#define RESPAWN_MEGAHEALTH 120
#define RESPAWN_POWERUP 120
#define RESPAWN_PARTIAL 998
#define RESPAWN_PARTIAL_DONE 999
Functions
int AddToClip (playerState_t *ps, weapon_t weapon, int ammomove, int outOfReserve)
Add the specified ammount of ammo into the clip.
void Fill_Clip (playerState_t *ps, weapon_t weapon)
Push reserve ammo into available space in the clip.
int Add_Ammo (gentity_t *ent, weapon_t weapon, int count, qboolean fillClip)
Add ammo.
qboolean AddMagicAmmo (gentity_t *receiver, int numOfClips)
Add the specified number of clips of magic ammo.
weapon_t G_GetPrimaryWeaponForClient (gclient_t *client)
Get the primary weapon of the client.
weapon_t G_GetPrimaryWeaponForClientSoldier (weapon_t weapon, gclient_t *client)
Get the primary weapon of the client.
void G_DropWeapon (gentity_t *ent, weapon_t weapon)
Drop Weapon.
qboolean G_CanPickupWeapon (weapon_t weapon, gentity_t *ent)
Check if a weapon can be picked up.
int Pickup_Weapon (gentity_t *ent, gentity_t *other)
Pick a weapon up.
int Pickup_Health (gentity_t *ent, gentity_t *other)
Pick health.
void RespawnItem (gentity_t *ent)
Respawn item.
void Touch_Item_Auto (gentity_t *ent, gentity_t *other, trace_t *trace)
Auto action when touching an item.
void Touch_Item (gentity_t *ent, gentity_t *other, trace_t *trace)
Action when touching an item.
gentity_t * LaunchItem (gitem_t *item, vec3_t origin, vec3_t velocity, int ownerNum)
Spawns an item and tosses it forward.
gentity_t * Drop_Item (gentity_t *ent, gitem_t *item, float angle, qboolean novelocity)
Spawns an item and tosses it forward.
void Use_Item (gentity_t *ent, gentity_t *other, gentity_t *activator)
Respawn the item.
void FinishSpawningItem (gentity_t *ent)
Traces down to find where an item should rest, instead of letting them free fall from their spawn points.
void G_SpawnItem (gentity_t *ent, gitem_t *item)
Sets the clipping size and plants the object on the floor.
void G_BounceItem (gentity_t *ent, trace_t *trace)
Bounce an item.
void G_RunItemProp (gentity_t *ent, vec3_t origin)
Run item prop.
void G_RunItem (gentity_t *ent)
Run item.
Detailed Description
Items are any object that a player can touch to gain some effect.
Pickup will return the number of seconds until they should respawn. all items should pop when dropped in lava or slime. Respawnable items don't actually go away when picked up, they are just made invisible and untouchable. This allows them to ride movers and respawn apropriately.
Definition in file g_items.c.
Macro Definition Documentation
#define RESPAWN_AMMO 40
Definition at line 53 of file g_items.c.
#define RESPAWN_ARMOR 25
Definition at line 50 of file g_items.c.
#define RESPAWN_HEALTH 35
Definition at line 52 of file g_items.c.
#define RESPAWN_HOLDABLE 60
Definition at line 54 of file g_items.c.
#define RESPAWN_KEY 4
Definition at line 49 of file g_items.c.
#define RESPAWN_MEGAHEALTH 120
Definition at line 55 of file g_items.c.
#define RESPAWN_NEVER -1
Definition at line 48 of file g_items.c.
Referenced by Pickup_Weapon().
#define RESPAWN_PARTIAL 998
Definition at line 57 of file g_items.c.
#define RESPAWN_PARTIAL_DONE 999
Definition at line 58 of file g_items.c.
#define RESPAWN_POWERUP 120
Definition at line 56 of file g_items.c.
#define RESPAWN_TEAM_WEAPON 30
Definition at line 51 of file g_items.c.
Function Documentation
int Add_Ammo (gentity_t * ent, weapon_t weapon, int count, qboolean fillClip)
Add ammo.
Parameters
[in,out] ent
[in] weapon
[in] count
[in] fillClip
Returns
whether any ammo was added
Definition at line 130 of file g_items.c.
Referenced by Cmd_Give_f(), Pickup_Weapon(), and Weapon_Engineer().
qboolean AddMagicAmmo (gentity_t * receiver, int numOfClips)
Add the specified number of clips of magic ammo.
Parameters
[in] receiver
[in] numOfClips
Returns
whether any ammo was actually added
Definition at line 173 of file g_items.c.
Referenced by ammo_touch(), G_IsAllowedAmmo(), and Pickup_Weapon().
int AddToClip (playerState_t * ps, weapon_t weapon, int ammomove, int outOfReserve)
Add the specified ammount of ammo into the clip.
Parameters
[in,out] ps which player
[in] weapon to add ammo for
[in] ammomove amount to add. 0 means fill the clip if possible
[in] outOfReserve amount to be added out of reserve
Returns
qboolean whether ammo was added to the clip.
Definition at line 68 of file g_items.c.
Referenced by Fill_Clip().
gentity_t* Drop_Item (gentity_t * ent, gitem_t * item, float angle, qboolean novelocity)
Spawns an item and tosses it forward.
Parameters
[in] ent
[in] item
[in] angle
[in] novelocity
Returns
Definition at line 941 of file g_items.c.
Referenced by misc_spawner_think().
void Fill_Clip (playerState_t * ps, weapon_t weapon)
Push reserve ammo into available space in the clip.
Parameters
[in] ps
[in] weapon
Definition at line 117 of file g_items.c.
Referenced by Add_Ammo().
void FinishSpawningItem (gentity_t * ent)
Traces down to find where an item should rest, instead of letting them free fall from their spawn points.
Parameters
[in,out] ent
Definition at line 981 of file g_items.c.
Referenced by G_SpawnItem().
void G_BounceItem (gentity_t * ent, trace_t * trace)
Bounce an item.
Parameters
[in,out] ent
[in,out] trace
Definition at line 1132 of file g_items.c.
Referenced by G_RunItem().
qboolean G_CanPickupWeapon (weapon_t weapon, gentity_t * ent)
Check if a weapon can be picked up.
Parameters
[in] weapon
[in] ent
Returns
Definition at line 423 of file g_items.c.
Referenced by G_CheckForCursorHints(), and Pickup_Weapon().
void G_DropWeapon (gentity_t * ent, weapon_t weapon)
Drop Weapon.
Parameters
[in] ent
[in] weapon
Definition at line 324 of file g_items.c.
Referenced by Pickup_Weapon(), and TossWeapons().
weapon_t G_GetPrimaryWeaponForClient (gclient_t * client)
Get the primary weapon of the client.
Parameters
[in] client
Returns
the primary weapon of the client
Definition at line 183 of file g_items.c.
Referenced by Pickup_Weapon(), and TossWeapons().
weapon_t G_GetPrimaryWeaponForClientSoldier (weapon_t weapon, gclient_t * client)
Get the primary weapon of the client.
Parameters
[in] weapon
[in] client
Returns
the primary weapon of the soldier client
Definition at line 272 of file g_items.c.
Referenced by Pickup_Weapon().
void G_RunItem (gentity_t * ent)
Run item.
Parameters
[in,out] ent
Todo:
: avoid this for stationary?
Definition at line 1224 of file g_items.c.
Referenced by G_RunEntity().
void G_RunItemProp (gentity_t * ent, vec3_t origin)
Run item prop.
Parameters
[in,out] ent
[in] origin
Definition at line 1178 of file g_items.c.
Referenced by G_RunItem().
void G_SpawnItem (gentity_t * ent, gitem_t * item)
Sets the clipping size and plants the object on the floor.
Parameters
[in,out] ent
[in] item
Definition at line 1091 of file g_items.c.
Referenced by G_CallSpawn().
gentity_t* LaunchItem (gitem_t * item, vec3_t origin, vec3_t velocity, int ownerNum)
Spawns an item and tosses it forward.
Parameters
[in] item
[in] origin
[in] velocity
[in] ownerNum
Returns
Definition at line 849 of file g_items.c.
Referenced by Drop_Item(), G_DropItems(), G_DropWeapon(), props_locker_spawn_item(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
int Pickup_Health (gentity_t * ent, gentity_t * other)
Pick health.
Parameters
[in,out] ent
[in,out] other
Returns
Definition at line 591 of file g_items.c.
Referenced by Touch_Item().
int Pickup_Weapon (gentity_t * ent, gentity_t * other)
Pick a weapon up.
Parameters
[in,out] ent
[in,out] other
Returns
Definition at line 451 of file g_items.c.
Referenced by Touch_Item().
void RespawnItem (gentity_t * ent)
Respawn item.
Parameters
[in,out] ent
Definition at line 635 of file g_items.c.
Referenced by Team_ResetFlag(), Touch_Item(), and Use_Item().
void Touch_Item (gentity_t * ent, gentity_t * other, trace_t * trace)
Action when touching an item.
Parameters
[in,out] ent
[in] other
trace - unused
Definition at line 713 of file g_items.c.
Referenced by Touch_Item_Auto(), and Use_Target_Give().
void Touch_Item_Auto (gentity_t * ent, gentity_t * other, trace_t * trace)
Auto action when touching an item.
PICKUP_ACTIVATE (0), he will pick up items only when using +activate PICKUP_TOUCH (1), he will pickup items when touched PICKUP_FORCE (2), he will pickup the next item when touched (and reset to PICKUP_ACTIVATE when done)
Parameters
[in,out] ent
[in,out] other
[in] trace
Definition at line 680 of file g_items.c.
Referenced by FinishSpawningItem(), and LaunchItem().
void Use_Item (gentity_t * ent, gentity_t * other, gentity_t * activator)
Respawn the item.
Parameters
[in] ent
other - unused
activator - unused
Definition at line 970 of file g_items.c.
Referenced by FinishSpawningItem().