ET: Legacy: src/game/g_lua.h File Reference
g_lua.h File Reference
ET <-> Lua interface header file.
#include "../qcommon/q_shared.h"
#include "g_local.h"
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
Data Structures
struct lua_vm_t
struct gentity_field_t
struct luaPrintFunctions_s
Macros
#define LUA_NUM_VM 18
#define LUA_MAX_FSIZE 1024 * 1024
1MB
#define FIELD_INT 0
#define FIELD_STRING 1
#define FIELD_FLOAT 2
#define FIELD_ENTITY 3
#define FIELD_VEC3 4
#define FIELD_INT_ARRAY 5
#define FIELD_TRAJECTORY 6
#define FIELD_FLOAT_ARRAY 7
#define FIELD_WEAPONSTAT 8
#define FIELD_FLAG_GENTITY 1
marks a gentity_s field
#define FIELD_FLAG_GCLIENT 2
marks a gclient_s field
#define FIELD_FLAG_NOPTR 4
#define FIELD_FLAG_READONLY 8
read-only access
#define HOSTARCH "UNIX"
#define EXTENSION "so"
#define lua_registerglobal(L, n, v) (lua_pushstring(L, v), lua_setglobal(L, n))
#define lua_regconstinteger(L, n) (lua_pushstring(L, #n), lua_pushinteger(L, n), lua_settable(L, -3))
#define lua_regconststring(L, n) (lua_pushstring(L, #n), lua_pushstring(L, n), lua_settable(L, -3))
#define _et_gentity_addfield(n, t, f) { #n, t, offsetof(struct gentity_s, n), FIELD_FLAG_GENTITY + f }
#define _et_gentity_addfieldalias(n, a, t, f) { #n, t, offsetof(struct gentity_s, a), FIELD_FLAG_GENTITY + f }
#define _et_gclient_addfield(n, t, f) { #n, t, offsetof(struct gclient_s, n), FIELD_FLAG_GCLIENT + f }
#define _et_gclient_addfieldalias(n, a, t, f) { #n, t, offsetof(struct gclient_s, a), FIELD_FLAG_GCLIENT + f }
Typedefs
typedef enum printMessageType_e printMessageType_t
typedef struct luaPrintFunctions_s luaPrintFunctions_t
Enumerations
enum printMessageType_e { GPRINT_TEXT = 0, GPRINT_DEVELOPER, GPRINT_ERROR }
Functions
qboolean G_LuaInit (void)
qboolean G_LuaCall (lua_vm_t *vm, const char *func, int nargs, int nresults)
qboolean G_LuaGetNamedFunction (lua_vm_t *vm, const char *name)
qboolean G_LuaStartVM (lua_vm_t *vm)
qboolean G_LuaRunIsolated (const char *modName)
void G_LuaStopVM (lua_vm_t *vm)
void G_LuaShutdown (void)
void G_LuaRestart (void)
void G_LuaStatus (gentity_t *ent)
void G_LuaStackDump ()
Dump the lua stack to console Executed by the ingame "lua_api" command.
lua_vm_t * G_LuaGetVM (lua_State *L)
void G_LuaHook_InitGame (int levelTime, int randomSeed, int restart)
void G_LuaHook_ShutdownGame (int restart)
void G_LuaHook_RunFrame (int levelTime)
qboolean G_LuaHook_ClientConnect (int clientNum, qboolean firstTime, qboolean isBot, char *reason)
void G_LuaHook_ClientDisconnect (int clientNum)
void G_LuaHook_ClientBegin (int clientNum)
void G_LuaHook_ClientUserinfoChanged (int clientNum)
void G_LuaHook_ClientSpawn (int clientNum, qboolean revived, qboolean teamChange, qboolean restoreHealth)
qboolean G_LuaHook_ClientCommand (int clientNum, char *command)
qboolean G_LuaHook_ConsoleCommand (char *command)
qboolean G_LuaHook_UpgradeSkill (int cno, skillType_t skill)
qboolean G_LuaHook_SetPlayerSkill (int cno, skillType_t skill)
void G_LuaHook_Print (printMessageType_t category, char *text)
qboolean G_LuaHook_Obituary (int victim, int killer, int meansOfDeath)
qboolean G_LuaHook_Damage (int target, int attacker, int damage, int dflags, meansOfDeath_t mod)
void G_LuaHook_SpawnEntitiesFromString ()
qboolean G_ScriptAction_Delete (gentity_t *ent, char *params)
Delete entities that match all the criteria provided in "params".
qboolean G_LuaHook_WeaponFire (int clientNum, weapon_t weapon, gentity_t **pFiredShot)
qboolean G_LuaHook_FixedMGFire (int clientNum)
qboolean G_LuaHook_MountedMGFire (int clientNum)
qboolean G_LuaHook_AAGunFire (int clientNum)
Variables
lua_vm_t * lVM [LUA_NUM_VM]
Detailed Description
ET <-> Lua interface header file.
Copyright
This code is taken from ETPub. All credits go to their team especially to quad and pheno! http://etpub.org http://shitstorm.org
Definition in file g_lua.h.
Macro Definition Documentation
#define _et_gclient_addfield (n, t, f) { #n, t, offsetof(struct gclient_s, n), FIELD_FLAG_GCLIENT + f }
Definition at line 78 of file g_lua.h.
#define _et_gclient_addfieldalias (n, a, t, f) { #n, t, offsetof(struct gclient_s, a), FIELD_FLAG_GCLIENT + f }
Definition at line 79 of file g_lua.h.
#define _et_gentity_addfield (n, t, f) { #n, t, offsetof(struct gentity_s, n), FIELD_FLAG_GENTITY + f }
Definition at line 76 of file g_lua.h.
#define _et_gentity_addfieldalias (n, a, t, f) { #n, t, offsetof(struct gentity_s, a), FIELD_FLAG_GENTITY + f }
Definition at line 77 of file g_lua.h.
#define EXTENSION "so"
Definition at line 65 of file g_lua.h.
Referenced by G_LuaStartVM().
#define FIELD_ENTITY 3
Definition at line 43 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_FLAG_GCLIENT 2
marks a gclient_s field
Definition at line 52 of file g_lua.h.
#define FIELD_FLAG_GENTITY 1
marks a gentity_s field
Definition at line 51 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_FLAG_NOPTR 4
Definition at line 53 of file g_lua.h.
Referenced by _et_G_GetSpawnVar(), _et_G_SetSpawnVar(), _et_gentity_get(), and _et_gentity_set().
#define FIELD_FLAG_READONLY 8
read-only access
Definition at line 54 of file g_lua.h.
Referenced by _et_gentity_set().
#define FIELD_FLOAT 2
Definition at line 42 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_FLOAT_ARRAY 7
Definition at line 47 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_INT 0
Definition at line 40 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_INT_ARRAY 5
Definition at line 45 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_STRING 1
Definition at line 41 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_TRAJECTORY 6
Definition at line 46 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_VEC3 4
Definition at line 44 of file g_lua.h.
Referenced by _et_gentity_get(), and _et_gentity_set().
#define FIELD_WEAPONSTAT 8
Definition at line 48 of file g_lua.h.
Referenced by _et_gentity_get().
#define HOSTARCH "UNIX"
Definition at line 64 of file g_lua.h.
Referenced by registerConstants().
#define LUA_MAX_FSIZE 1024 * 1024
1MB
Definition at line 38 of file g_lua.h.
Referenced by G_LuaRunIsolated().
#define LUA_NUM_VM 18
Definition at line 37 of file g_lua.h.
Referenced by G_LuaGetVM(), G_LuaHook_AAGunFire(), G_LuaHook_ClientBegin(), G_LuaHook_ClientCommand(), G_LuaHook_ClientConnect(), G_LuaHook_ClientDisconnect(), G_LuaHook_ClientSpawn(), G_LuaHook_ClientUserinfoChanged(), G_LuaHook_ConsoleCommand(), G_LuaHook_Damage(), G_LuaHook_FixedMGFire(), G_LuaHook_InitGame(), G_LuaHook_MountedMGFire(), G_LuaHook_Obituary(), G_LuaHook_Print(), G_LuaHook_RunFrame(), G_LuaHook_SetPlayerSkill(), G_LuaHook_ShutdownGame(), G_LuaHook_SpawnEntitiesFromString(), G_LuaHook_UpgradeSkill(), G_LuaHook_WeaponFire(), G_LuaInit(), G_LuaRunIsolated(), G_LuaShutdown(), and G_LuaStatus().
#define lua_regconstinteger (L, n) (lua_pushstring(L, #n), lua_pushinteger(L, n), lua_settable(L, -3))
Definition at line 70 of file g_lua.h.
Referenced by registerConfigstringConstants(), registerConstants(), registerModConstants(), registerPowerupConstants(), registerSurfaceConstants(), and registerWeaponConstants().
#define lua_regconststring (L, n) (lua_pushstring(L, #n), lua_pushstring(L, n), lua_settable(L, -3))
Definition at line 72 of file g_lua.h.
Referenced by registerConstants().
#define lua_registerglobal (L, n, v) (lua_pushstring(L, v), lua_setglobal(L, n))
Definition at line 69 of file g_lua.h.
Referenced by G_LuaStartVM().
Typedef Documentation
luaPrintFunctions_t
printMessageType_t
Enumeration Type Documentation
enum printMessageType_e
Enumerator
GPRINT_TEXT
GPRINT_DEVELOPER
GPRINT_ERROR
Definition at line 116 of file g_lua.h.
Function Documentation
qboolean G_LuaCall (lua_vm_t * vm, const char * func, int nargs, int nresults)
Definition at line 2259 of file g_lua.c.
Referenced by _et_IPCSend(), G_LuaHook_AAGunFire(), G_LuaHook_ClientBegin(), G_LuaHook_ClientCommand(), G_LuaHook_ClientConnect(), G_LuaHook_ClientDisconnect(), G_LuaHook_ClientSpawn(), G_LuaHook_ClientUserinfoChanged(), G_LuaHook_ConsoleCommand(), G_LuaHook_Damage(), G_LuaHook_FixedMGFire(), G_LuaHook_InitGame(), G_LuaHook_MountedMGFire(), G_LuaHook_Obituary(), G_LuaHook_Print(), G_LuaHook_RunFrame(), G_LuaHook_SetPlayerSkill(), G_LuaHook_ShutdownGame(), G_LuaHook_SpawnEntitiesFromString(), G_LuaHook_UpgradeSkill(), G_LuaHook_WeaponFire(), G_LuaStartVM(), and G_LuaStopVM().
qboolean G_LuaGetNamedFunction (lua_vm_t * vm, const char * name)
Definition at line 2288 of file g_lua.c.
Referenced by _et_IPCSend(), G_LuaHook_AAGunFire(), G_LuaHook_ClientBegin(), G_LuaHook_ClientCommand(), G_LuaHook_ClientConnect(), G_LuaHook_ClientDisconnect(), G_LuaHook_ClientSpawn(), G_LuaHook_ClientUserinfoChanged(), G_LuaHook_ConsoleCommand(), G_LuaHook_Damage(), G_LuaHook_FixedMGFire(), G_LuaHook_InitGame(), G_LuaHook_MountedMGFire(), G_LuaHook_Obituary(), G_LuaHook_Print(), G_LuaHook_RunFrame(), G_LuaHook_SetPlayerSkill(), G_LuaHook_ShutdownGame(), G_LuaHook_SpawnEntitiesFromString(), G_LuaHook_UpgradeSkill(), G_LuaHook_WeaponFire(), and G_LuaStopVM().
lua_vm_t* G_LuaGetVM (lua_State * L)
Definition at line 3029 of file g_lua.c.
Referenced by _et_FindSelf(), _et_IPCSend(), and _et_RegisterModname().
qboolean G_LuaInit (void)
Definition at line 2202 of file g_lua.c.
Referenced by G_InitGame(), and G_LuaRestart().
void G_LuaRestart (void)
Definition at line 2978 of file g_lua.c.
Referenced by ConsoleCommand().
qboolean G_LuaRunIsolated (const char * modName)
Definition at line 2106 of file g_lua.c.
Referenced by G_LuaInit().
void G_LuaShutdown (void)
Definition at line 2959 of file g_lua.c.
Referenced by G_LuaRestart(), G_ShutdownGame(), and G_UpdateCvars().
void G_LuaStackDump ()
Dump the lua stack to console Executed by the ingame "lua_api" command.
Definition at line 2310 of file g_lua.c.
Referenced by ConsoleCommand().
qboolean G_LuaStartVM (lua_vm_t * vm)
Definition at line 2803 of file g_lua.c.
Referenced by G_LuaRunIsolated(), and G_LuaStackDump().
void G_LuaStatus (gentity_t * ent)
Definition at line 2988 of file g_lua.c.
Referenced by ClientCommand(), and ConsoleCommand().
void G_LuaStopVM (lua_vm_t * vm)
Definition at line 2921 of file g_lua.c.
Referenced by G_LuaRunIsolated(), and G_LuaShutdown().
qboolean G_ScriptAction_Delete (gentity_t * ent, char * params)
Delete entities that match all the criteria provided in "params".
Parameters
ent - unused
[in] params
Returns
Definition at line 4942 of file g_script_actions.c.
Variable Documentation
lua_vm_t* lVM[LUA_NUM_VM]
Definition at line 29 of file g_lua.c.