ET: Legacy: src/game/g_lua.c File Reference
g_lua.c File Reference
ET <-> Lua interface source file.
#include "g_lua.h"
#include "g_etbot_interface.h"
Functions
static int C_gentity_ptr_to_entNum (unsigned long addr)
static int _et_RegisterModname (lua_State *L)
Registers a name for this Lua module.
static int _et_FindSelf (lua_State *L)
Gets slot number assigned to this lua VM.
static int _et_FindMod (lua_State *L)
Gets name of lua module at slot vmnumber and its signature hash.
static int _et_IPCSend (lua_State *L)
static int _et_G_Print (lua_State *L)
static int _et_G_LogPrint (lua_State *L)
static int _et_ConcatArgs (lua_State *L)
static int _et_trap_Argc (lua_State *L)
static int _et_trap_Argv (lua_State *L)
static int _et_trap_Cvar_Get (lua_State *L)
static int _et_trap_Cvar_Set (lua_State *L)
static int _et_trap_GetConfigstring (lua_State *L)
static int _et_trap_SetConfigstring (lua_State *L)
static int _et_trap_SendConsoleCommand (lua_State *L)
static int _et_trap_SendServerCommand (lua_State *L)
static int _et_trap_DropClient (lua_State *L)
static int _et_ClientNumberFromString (lua_State *L)
Searches for one partial match with string, if one is found the clientnum is returned, if there is none or more than one match nil is returned.
static int _et_G_Say (lua_State *L)
static int _et_MutePlayer (lua_State *L)
static int _et_UnmutePlayer (lua_State *L)
static int _et_trap_GetUserinfo (lua_State *L)
static int _et_trap_SetUserinfo (lua_State *L)
static int _et_ClientUserinfoChanged (lua_State *L)
static int _et_Info_RemoveKey (lua_State *L)
static int _et_Info_SetValueForKey (lua_State *L)
static int _et_Info_ValueForKey (lua_State *L)
static int _et_Q_CleanStr (lua_State *L)
static int _et_trap_FS_FOpenFile (lua_State *L)
static int _et_trap_FS_Read (lua_State *L)
static int _et_trap_FS_Write (lua_State *L)
static int _et_trap_FS_FCloseFile (lua_State *L)
static int _et_trap_FS_Rename (lua_State *L)
static int _et_trap_FS_GetFileList (lua_State *L)
static int _et_G_SoundIndex (lua_State *L)
static int _et_G_ModelIndex (lua_State *L)
static int _et_G_globalSound (lua_State *L)
static int _et_G_Sound (lua_State *L)
static int _et_G_ClientSound (lua_State *L)
static int _et_trap_Milliseconds (lua_State *L)
static int _et_isBitSet (lua_State *L)
static int _et_G_Damage (lua_State *L)
static int _et_G_AddSkillPoints (lua_State *L)
static int _et_G_LoseSkillPoints (lua_State *L)
static int _et_G_XP_Set (lua_State *L)
static int _et_G_ResetXP (lua_State *L)
Reset XP of the player in slot number clientNum.
static int _et_AddWeaponToPlayer (lua_State *L)
static int _et_RemoveWeaponFromPlayer (lua_State *L)
static int _et_GetCurrentWeapon (lua_State *L)
static gentity_field_t * _et_gentity_getfield (gentity_t *ent, char *fieldname)
static void _et_gentity_getvec3 (lua_State *L, vec3_t vec3)
static void _et_gentity_setvec3 (lua_State *L, vec3_t *vec3)
static void _et_gentity_gettrajectory (lua_State *L, trajectory_t *traj)
static void _et_gentity_settrajectory (lua_State *L, trajectory_t *traj)
static void _et_gentity_getweaponstat (lua_State *L, weapon_stat_t *ws)
gentity_t * G_Lua_CreateEntity (char *params)
static int _et_G_Lua_CreateEntity (lua_State *L)
static int _et_G_Lua_DeleteEntity (lua_State *L)
static int _et_G_TempEntity (lua_State *L)
static int _et_G_FreeEntity (lua_State *L)
static int _et_G_EntitiesFree (lua_State *L)
static int _et_G_SetEntState (lua_State *L)
static int _et_trap_LinkEntity (lua_State *L)
static int _et_trap_UnlinkEntity (lua_State *L)
static int _et_G_GetSpawnVar (lua_State *L)
static int _et_G_SetSpawnVar (lua_State *L)
static int _et_gentity_get (lua_State *L)
static int _et_gentity_set (lua_State *L)
static int _et_G_AddEvent (lua_State *L)
static int _et_G_ShaderRemap (lua_State *L)
static int _et_G_ResetRemappedShaders (lua_State *L)
static int _et_G_ShaderRemapFlush (lua_State *L)
static int _et_G_SetGlobalFog (lua_State *L)
static void _et_getclipplane (lua_State *L, cplane_t *plane)
static void _et_gettrace (lua_State *L, trace_t *tr)
static vec3_t * _etH_toVec3 (lua_State *L, int inx)
static int _et_trap_Trace (lua_State *L)
static int _et_G_HistoricalTrace (lua_State *L)
qboolean G_LuaRunIsolated (const char *modName)
qboolean G_LuaInit (void)
qboolean G_LuaCall (lua_vm_t *vm, const char *func, int nargs, int nresults)
qboolean G_LuaGetNamedFunction (lua_vm_t *vm, const char *name)
void G_LuaStackDump ()
Dump the lua stack to console Executed by the ingame "lua_api" command.
static void registerConfigstringConstants (lua_vm_t *vm)
static void registerPowerupConstants (lua_vm_t *vm)
static void registerWeaponConstants (lua_vm_t *vm)
static void registerModConstants (lua_vm_t *vm)
static void registerSurfaceConstants (lua_vm_t *vm)
static void registerConstants (lua_vm_t *vm)
qboolean G_LuaStartVM (lua_vm_t *vm)
void G_LuaStopVM (lua_vm_t *vm)
void G_LuaShutdown (void)
void G_LuaRestart (void)
void G_LuaStatus (gentity_t *ent)
lua_vm_t * G_LuaGetVM (lua_State *L)
void G_LuaHook_InitGame (int levelTime, int randomSeed, int restart)
void G_LuaHook_ShutdownGame (int restart)
void G_LuaHook_RunFrame (int levelTime)
qboolean G_LuaHook_ClientConnect (int clientNum, qboolean firstTime, qboolean isBot, char *reason)
void G_LuaHook_ClientDisconnect (int clientNum)
void G_LuaHook_ClientBegin (int clientNum)
void G_LuaHook_ClientUserinfoChanged (int clientNum)
void G_LuaHook_ClientSpawn (int clientNum, qboolean revived, qboolean teamChange, qboolean restoreHealth)
qboolean G_LuaHook_ClientCommand (int clientNum, char *command)
qboolean G_LuaHook_ConsoleCommand (char *command)
qboolean G_LuaHook_UpgradeSkill (int cno, skillType_t skill)
qboolean G_LuaHook_SetPlayerSkill (int cno, skillType_t skill)
void G_LuaHook_Print (printMessageType_t category, char *text)
qboolean G_LuaHook_Obituary (int victim, int killer, int meansOfDeath)
qboolean G_LuaHook_Damage (int target, int attacker, int damage, int dflags, meansOfDeath_t mod)
qboolean G_LuaHook_WeaponFire (int clientNum, weapon_t weapon, gentity_t **pFiredShot)
qboolean G_LuaHook_FixedMGFire (int clientNum)
qboolean G_LuaHook_MountedMGFire (int clientNum)
qboolean G_LuaHook_AAGunFire (int clientNum)
void G_LuaHook_SpawnEntitiesFromString ()
Variables
field_t fields []
lua_vm_t * lVM [LUA_NUM_VM]
char bigTextBuffer [100000]
static const gentity_field_t gclient_fields []
static const gentity_field_t gentity_fields []
static const luaL_Reg etlib []
static luaPrintFunctions_t g_luaPrintFunctions []
Detailed Description
ET <-> Lua interface source file.
Copyright
This code is taken from ETPub and NQ. All credits go to their teams especially to quad and pheno! http://etpub.org http://shitstorm.org
Definition in file g_lua.c.
Function Documentation
static int C_gentity_ptr_to_entNum (unsigned long addr) static
Parameters
addr pointer to a gentity (gentity*)
Returns
the entity number. if (input==0) return = -1 if (input address is out of g_entities[] memory range) return -1;
Definition at line 37 of file g_lua.c.
Referenced by _et_G_GetSpawnVar(), and _et_gentity_get().
qboolean G_LuaCall (lua_vm_t * vm, const char * func, int nargs, int nresults)
Definition at line 2259 of file g_lua.c.
Referenced by _et_IPCSend(), G_LuaHook_AAGunFire(), G_LuaHook_ClientBegin(), G_LuaHook_ClientCommand(), G_LuaHook_ClientConnect(), G_LuaHook_ClientDisconnect(), G_LuaHook_ClientSpawn(), G_LuaHook_ClientUserinfoChanged(), G_LuaHook_ConsoleCommand(), G_LuaHook_Damage(), G_LuaHook_FixedMGFire(), G_LuaHook_InitGame(), G_LuaHook_MountedMGFire(), G_LuaHook_Obituary(), G_LuaHook_Print(), G_LuaHook_RunFrame(), G_LuaHook_SetPlayerSkill(), G_LuaHook_ShutdownGame(), G_LuaHook_SpawnEntitiesFromString(), G_LuaHook_UpgradeSkill(), G_LuaHook_WeaponFire(), G_LuaStartVM(), and G_LuaStopVM().
qboolean G_LuaGetNamedFunction (lua_vm_t * vm, const char * name)
Definition at line 2288 of file g_lua.c.
Referenced by _et_IPCSend(), G_LuaHook_AAGunFire(), G_LuaHook_ClientBegin(), G_LuaHook_ClientCommand(), G_LuaHook_ClientConnect(), G_LuaHook_ClientDisconnect(), G_LuaHook_ClientSpawn(), G_LuaHook_ClientUserinfoChanged(), G_LuaHook_ConsoleCommand(), G_LuaHook_Damage(), G_LuaHook_FixedMGFire(), G_LuaHook_InitGame(), G_LuaHook_MountedMGFire(), G_LuaHook_Obituary(), G_LuaHook_Print(), G_LuaHook_RunFrame(), G_LuaHook_SetPlayerSkill(), G_LuaHook_ShutdownGame(), G_LuaHook_SpawnEntitiesFromString(), G_LuaHook_UpgradeSkill(), G_LuaHook_WeaponFire(), and G_LuaStopVM().
lua_vm_t* G_LuaGetVM (lua_State * L)
Definition at line 3029 of file g_lua.c.
Referenced by _et_FindSelf(), _et_IPCSend(), and _et_RegisterModname().
qboolean G_LuaInit (void)
Definition at line 2202 of file g_lua.c.
Referenced by G_InitGame(), and G_LuaRestart().
void G_LuaRestart (void)
Definition at line 2978 of file g_lua.c.
Referenced by ConsoleCommand().
qboolean G_LuaRunIsolated (const char * modName)
Definition at line 2106 of file g_lua.c.
Referenced by G_LuaInit().
void G_LuaShutdown (void)
Definition at line 2959 of file g_lua.c.
Referenced by G_LuaRestart(), G_ShutdownGame(), and G_UpdateCvars().
void G_LuaStackDump ()
Dump the lua stack to console Executed by the ingame "lua_api" command.
Definition at line 2310 of file g_lua.c.
Referenced by ConsoleCommand().
qboolean G_LuaStartVM (lua_vm_t * vm)
Definition at line 2803 of file g_lua.c.
Referenced by G_LuaRunIsolated(), and G_LuaStackDump().
void G_LuaStatus (gentity_t * ent)
Definition at line 2988 of file g_lua.c.
Referenced by ClientCommand(), and ConsoleCommand().
void G_LuaStopVM (lua_vm_t * vm)
Definition at line 2921 of file g_lua.c.
Referenced by G_LuaRunIsolated(), and G_LuaShutdown().
static void registerConfigstringConstants (lua_vm_t * vm) static
Definition at line 2375 of file g_lua.c.
Referenced by registerConstants().
static void registerConstants (lua_vm_t * vm) static
Definition at line 2704 of file g_lua.c.
Referenced by G_LuaStartVM().
static void registerModConstants (lua_vm_t * vm) static
Definition at line 2540 of file g_lua.c.
Referenced by registerConstants().
static void registerPowerupConstants (lua_vm_t * vm) static
Definition at line 2451 of file g_lua.c.
Referenced by registerConstants().
static void registerSurfaceConstants (lua_vm_t * vm) static
Definition at line 2632 of file g_lua.c.
Referenced by registerConstants().
static void registerWeaponConstants (lua_vm_t * vm) static
Definition at line 2472 of file g_lua.c.
Referenced by registerConstants().
Variable Documentation
const luaL_Reg etlib[] static
Definition at line 2009 of file g_lua.c.
Referenced by G_LuaStartVM().
field_t fields[]
Definition at line 153 of file g_spawn.c.
lua_vm_t* lVM[LUA_NUM_VM]
Definition at line 29 of file g_lua.c.