ET: Legacy: src/game/g_local.h File Reference
g_local.h File Reference
Local definitions for game module.
#include "../qcommon/q_shared.h"
#include "bg_public.h"
#include "g_public.h"
Data Structures
struct g_script_stack_action_t
Scripting (parsed at each start)
struct g_script_stack_item_t
struct g_script_stack_t
struct g_script_event_t
struct g_script_event_define_t
struct g_script_status_t
Scripting Status.
struct g_constructible_stats_s
struct commanderTeamChat_s
struct mapVoteInfo_t
MAPVOTE.
struct glerpFrame_t
realistic hitboxes based on lerpFrame_t
struct gentity_s
struct playerTeamState_t
struct weapon_stat_t
struct clientSession_t
struct ipFilter_s
struct clientPersistant_t
Client data that stays across multiple respawns, but is cleared on each level change or team change at ClientBegin()
struct clientMarker_t
struct debrisChunk_s
struct gclient_s
struct brushmodelInfo_t
struct limbo_cam_s
struct voteInfo_s
struct cfgCvar_s
struct config_s
struct spawnPointState_s
struct level_locals_s
struct g_campaignInfo_t
struct grefEntity_t
cut down refEntity_t w/ only stuff needed for player bone calculation Used only by game code - not engine core: This struct was moved here from etpro_mdx.h
struct GeoIPTag
struct mapEntityData_s
struct mapEntityData_Team_s
struct team_info
Team extras.
struct field_t
struct weapFireTable_t
struct consoleCommandTable_s
Macros
#define GAMEVERSION "legacy"
The "gameversion" client command will print this plus compile date.
#define BODY_QUEUE_SIZE 8
#define EVENT_VALID_MSEC 300
#define MG42_MULTIPLAYER_HEALTH 350
#define MISSILE_PRESTEP_TIME 50
#define BODY_TIME 10000
How long do bodies last? (in ms)
#define FL_GODMODE 0x00000010
#define FL_NOTARGET 0x00000020
#define FL_TEAMSLAVE 0x00000400
not the first on the team
#define FL_NO_KNOCKBACK 0x00000800
#define FL_DROPPED_ITEM 0x00001000
#define FL_NO_BOTS 0x00002000
spawn point not for bot use
#define FL_NO_HUMANS 0x00004000
spawn point just for bots
#define FL_NOSTAMINA 0x00008000
cheat flag no stamina
#define FL_NOFATIGUE 0x00010000
cheat flag no fatigue
#define FL_TOGGLE 0x00020000
ent is toggling (doors use this for ex.)
#define FL_KICKACTIVATE 0x00040000
ent has been activated by a kick (doors use this too for ex.)
#define FL_SOFTACTIVATE 0x00000040
ent has been activated while 'walking' (doors use this too for ex.)
#define FL_NODRAW 0x01000000
#define TKFL_MINES 0x00000001
#define TKFL_AIRSTRIKE 0x00000002
#define TKFL_MORTAR 0x00000004
#define NO_GT_WOLF 1
#define NO_STOPWATCH 2
#define NO_CHECKPOINT 4
unused
#define NO_LMS 8
#define MAX_CONSTRUCT_STAGES 3
#define ALLOW_AXIS_TEAM 1
#define ALLOW_ALLIED_TEAM 2
#define ALLOW_DISGUISED_CVOPS 4
#define G_MAX_SCRIPT_STACK_ITEMS 196
value set high for the tank
#define SCFL_GOING_TO_MARKER 0x1
#define SCFL_ANIMATING 0x2
#define SCFL_FIRST_CALL 0x4
#define G_MAX_SCRIPT_ACCUM_BUFFERS 10
#define NUM_CONSTRUCTIBLE_CLASSES 3
#define MAX_NETNAME 36
#define MAX_COMMANDER_TEAM_SOUNDS 16
#define PICKUP_ACTIVATE 0
pickup items only when using "+activate"
#define PICKUP_TOUCH 1
pickup items when touched
#define PICKUP_FORCE 2
pickup the next item when touched (and reset to PICKUP_ACTIVATE when done)
#define LAG_MAX_COMMANDS 512
#define LAG_MAX_DELTA 75
#define LAG_MAX_DROP_THRESHOLD 800
#define LAG_MIN_DROP_THRESHOLD (LAG_MAX_DROP_THRESHOLD - 200)
#define LAG_DECAY 1.02f
#define MAX_COMPLAINTIPS 5
#define MAX_CLIENT_MARKERS 17
#define FIELDOPS_SPECIAL_PICKUP_MOD 3
Number of times (minus one for modulo) field ops must drop ammo before scoring a point.
#define MEDIC_SPECIAL_PICKUP_MOD 4
Same thing for medic.
#define MAX_DEBRISCHUNKS 256
#define MAX_LIMBO_CAMS 32
#define MAX_SPAWN_VARS 64
#define MAX_SPAWN_VARS_CHARS 2048
#define VOTE_MAXSTRING 256
Same value as MAX_STRING_TOKENS.
#define MAX_SCRIPT_ACCUM_BUFFERS 10
increased from 8 to 10 for compatability with maps that relied on it before Project: Bug Fix #055
#define G_SpawnString(key, def, out) G_SpawnStringExt(key, def, out, __FILE__, __LINE__)
#define G_SpawnFloat(key, def, out) G_SpawnFloatExt(key, def, out, __FILE__, __LINE__)
#define G_SpawnInt(key, def, out) G_SpawnIntExt(key, def, out, __FILE__, __LINE__)
#define G_SpawnVector(key, def, out) G_SpawnVectorExt(key, def, out, __FILE__, __LINE__)
#define G_SpawnVector2D(key, def, out) G_SpawnVector2DExt(key, def, out, __FILE__, __LINE__)
#define DAMAGE_RADIUS 0x00000001
damage was indirect
#define DAMAGE_HALF_KNOCKBACK 0x00000002
do less knockback
#define DAMAGE_NO_KNOCKBACK 0x00000008
do not affect velocity, just view angles
#define DAMAGE_NO_PROTECTION 0x00000020
armor, shields, invulnerability, and godmode have no effect
#define DAMAGE_NO_TEAM_PROTECTION 0x00000010
unused. Armor, shields, invulnerability, and godmode have no effect
#define DAMAGE_DISTANCEFALLOFF 0x00000040
distance falloff
#define CF_ENABLE 1
enables common countryflags functionallity
#define CF_CONNECT 2
draws country name in connect announcer
#define FOFS(x) ((size_t)&(((gentity_t *)0)->x))
#define STICKYCHARGE_NONE 0
#define STICKYCHARGE_SELFKILL 1
#define STICKYCHARGE_ANYDEATH 2
#define BODY_VALUE(ENT) ENT->watertype
#define BODY_TEAM(ENT) ENT->s.modelindex
#define BODY_CLASS(ENT) ENT->s.modelindex2
#define BODY_CHARACTER(ENT) ENT->s.onFireStart
#define PAUSE_NONE 0x00
Match is NOT paused.
#define PAUSE_UNPAUSING 0x01
Pause is about to expire.
#define G_OK 0
#define G_INVALID -1
#define G_NOTFOUND -2
#define AP(x) trap_SendServerCommand(-1, x)
Print to all.
#define CP(x) trap_SendServerCommand(ent - g_entities, x)
Print to an ent.
#define CPx(x, y) trap_SendServerCommand(x, y)
Print to id = x.
#define HELP_COLUMNS 4
#define CMD_DEBOUNCE 5000
5s between cmds
#define EOM_WEAPONSTATS 0x01
Dump of player weapon stats at end of match.
#define EOM_MATCHINFO 0x02
Dump of match stats at end of match.
#define AA_STATSALL 0x01
Client AutoAction: Dump ALL player stats.
#define AA_STATSTEAM 0x02
Client AutoAction: Dump TEAM player stats.
#define OBJECTIVE_INFO_AXIS_OBJECTIVE 1
#define OBJECTIVE_INFO_ALLIED_OBJECTIVE 2
#define OBJECTIVE_INFO_MESSAGE_OVERRIDE 4
#define OBJECTIVE_INFO_TANK 8
#define OBJECTIVE_INFO_IS_OBJECTIVE 16
#define OBJECTIVE_INFO_IS_HEALTHAMMOCABINET 32
(see cg_commandmap)
#define OBJECTIVE_INFO_IS_COMMANDPOST 64
128 is disabled
#define MOVER_TRIGGERSPAWN 1
#define MOVER_SOLID 2
#define MOVER_EXPLOSIVEDAMAGEONLY 4
#define MOVER_RESURECTABLE 8
#define MOVER_COMPASS 16
#define MOVER_ALLIED 32
#define MOVER_AXIS 64
#define MOVER_MOUNTEDGUN 128
#define MULTI_TRIGGER_AXIS_ONLY 1
#define MULTI_TRIGGER_ALLIED_ONLY 2
#define MULTI_TRIGGER_NOBOT 4
#define MULTI_TRIGGER_BOTONLY 8
#define MULTI_TRIGGER_SOLDIERONLY 16
#define MULTI_TRIGGER_FIELDOPSONLY 32
#define MULTI_TRIGGER_MEDICONLY 64
#define MULTI_TRIGGER_ENGINEERONLY 128
#define MULTI_TRIGGER_COVERTOPSONLY 256
#define MULTI_TRIGGER_DISGUISEDSONLY 512
legacy only
#define MULTI_TRIGGER_OBJECTIVEONLY 1024
legacy only
#define TARGET_PUSH_BOUNCEPAD 1
#define DOOR_ROTATING_TOGGLE 2
#define DOOR_ROTATING_X_AXIS 4
#define DOOR_ROTATING_Y_AXIS 8
#define DOOR_ROTATING_REVERSE 16
#define DOOR_ROTATING_FORCE 32
#define DOOR_ROTATING_STAYOPEN 64
#define DOOR_START_OPEN 1
#define DOOR_TOGGLE 2
#define DOOR_CRUSHER 4
#define DOOR_TOUCH 8
#define AXIS_OBJECTIVE 1
#define ALLIED_OBJECTIVE 2
#define OBJECTIVE_DESTROYED 4
#define CONSTRUCTIBLE_START_BUILT 1
#define CONSTRUCTIBLE_INVULNERABLE 2
#define AXIS_CONSTRUCTIBLE 4
#define ALLIED_CONSTRUCTIBLE 8
#define CONSTRUCTIBLE_BLOCK_PATHS_WHEN_BUILD 16
#define CONSTRUCTIBLE_NO_AAS_BLOCKING 32
#define EXPLOSIVE_START_INVIS 1
#define EXPLOSIVE_TOUCHABLE 2
#define EXPLOSIVE_USESHADER 4
#define EXPLOSIVE_LOWGRAV 8
#define EXPLOSIVE_TANK 32
#define MAPVOTE_TIE_LEASTPLAYED 1
#define MAPVOTE_ALT_INTERMISSION 2
unused
#define MAPVOTE_MULTI_VOTE 4
#define MAPVOTE_NO_RANDOMIZE 8
unused
#define MAPVOTE_NEXTMAP_VOTEMAP 16
#define G_PROTECT_LOCALHOST_REF 1
#define G_PROTECT_MAX_LIVES_BAN_GUID 2
#define G_MISC_SHOVE_Z BIT(0)
#define G_MISC_CROSSHAIR_DYNAMITE BIT(3)
#define G_MISC_CROSSHAIR_LANDMINE BIT(4)
#define VOTEF_USE_TOTAL_VOTERS 1
use total voters instead of total players to decide if a vote passes
#define VOTEF_NO_POPULIST_PENALTY 2
successful votes do not count against vote_limit
#define VOTEF_DISP_CALLER 4
append "(called by name)" in vote string
#define SERVER_FRAMETIME (1000 / trap_Cvar_VariableIntegerValue("sv_fps"))
(1000/20) default
#define SERVER_FRAMETIME_F (1000.f / trap_Cvar_VariableIntegerValue("sv_fps"))
#define SERVER_FRAMETIME_DELTA (2 * SERVER_FRAMETIME)
msec
#define SERVER_FRAMETIME_DELTA_F (2.f * SERVER_FRAMETIME_F)
msec
#define GetWeaponFireTableData(weapIndex) ((weapFireTable_t *)(&weapFireTable[weapIndex]))
Typedefs
typedef struct gentity_s gentity_t
typedef struct gclient_s gclient_t
This structure is cleared on each ClientSpawn(), except for 'client->pers' and 'client->sess'.
typedef struct g_constructible_stats_s g_constructible_stats_t
typedef struct commanderTeamChat_s commanderTeamChat_t
typedef struct ipFilter_s ipFilter_t
typedef struct debrisChunk_s debrisChunk_t
Debris test.
typedef struct limbo_cam_s limbo_cam_t
typedef struct voteInfo_s voteInfo_t
typedef struct cfgCvar_s cfgCvar_t
typedef struct config_s config_t
typedef struct spawnPointState_s spawnPointState_t
typedef struct level_locals_s level_locals_t
typedef struct GeoIPTag GeoIP
typedef struct mapEntityData_s mapEntityData_t
typedef struct mapEntityData_Team_s mapEntityData_Team_t
typedef struct weapFireTable_t weapFireTable_t
typedef struct consoleCommandTable_s consoleCommandTable_t
Enumerations
enum moverState_t {
MOVER_POS1 = 0, MOVER_POS2, MOVER_POS3, MOVER_1TO2,
MOVER_2TO1, MOVER_2TO3, MOVER_3TO2, MOVER_POS1ROTATE,
MOVER_POS2ROTATE, MOVER_1TO2ROTATE, MOVER_2TO1ROTATE
}
Movers are things like doors, plats, buttons, etc.
enum clientConnected_t { CON_DISCONNECTED = 0, CON_CONNECTING, CON_CONNECTED }
enum spectatorState_t { SPECTATOR_NOT = 0, SPECTATOR_FREE, SPECTATOR_FOLLOW }
enum combatstate_t { COMBATSTATE_COLD = 0, COMBATSTATE_DAMAGEDEALT, COMBATSTATE_DAMAGERECEIVED, COMBATSTATE_KILLEDPLAYER }
enum playerTeamStateState_t { TEAM_BEGIN = 0, TEAM_ACTIVE }
enum enum_t_dp { DP_PAUSEINFO = 0, DP_UNPAUSING, DP_CONNECTINFO, DP_MVSPAWN }
"Delayed Print" ent enumerations
enum fieldtype_t {
F_INT = 0, F_FLOAT, F_LSTRING, F_GSTRING,
F_VECTOR, F_ANGLEHACK, F_ENTITY, F_ITEM,
F_CLIENT, F_IGNORE
}
Functions
void G_Script_ScriptEvent (gentity_t *ent, const char *eventStr, const char *params)
An event has occured, for which a script may exist.
qboolean G_SpawnStringExt (const char *key, const char *defaultString, char **out, const char *file, int line)
G_SpawnStringExt.
qboolean G_SpawnFloatExt (const char *key, const char *defaultString, float *out, const char *file, int line)
G_SpawnFloatExt.
qboolean G_SpawnIntExt (const char *key, const char *defaultString, int *out, const char *file, int line)
G_SpawnIntExt.
qboolean G_SpawnVectorExt (const char *key, const char *defaultString, float *out, const char *file, int line)
G_SpawnVectorExt.
qboolean G_SpawnVector2DExt (const char *key, const char *defaultString, float *out, const char *file, int line)
G_SpawnVector2DExt.
void G_SpawnEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
char * G_NewString (const char *string)
Builds a copy of the string, translating \n to real linefeeds so message texts can be multi-line.
gentity_t * G_SpawnGEntityFromSpawnVars (void)
Spawn an entity and fill in all of the level fields from level.spawnVars[], then call the class specfic spawn function.
qboolean G_CallSpawn (gentity_t *ent)
Finds the spawn function for the entity and calls it.
char * G_AddSpawnVarToken (const char *string)
G_AddSpawnVarToken.
void G_ParseField (const char *key, const char *value, gentity_t *ent)
Takes a key/value pair and sets the binary values in a gentity.
void Cmd_Score_f (gentity_t *ent)
Request current scoreboard information.
void StopFollowing (gentity_t *ent)
If the client being followed leaves the game, or you just want to drop to free floating spectator mode.
void G_TeamDataForString (const char *teamstr, int clientNum, team_t *team, spectatorState_t *sState, int *specClient)
G_TeamDataForString.
qboolean SetTeam (gentity_t *ent, const char *s, qboolean force, weapon_t w1, weapon_t w2, qboolean setweapons)
SetTeam.
void G_SetClientWeapons (gentity_t *ent, weapon_t w1, weapon_t w2, qboolean updateclient)
G_SetClientWeapons.
void Cmd_FollowCycle_f (gentity_t *ent, int dir, qboolean skipBots)
Cmd_FollowCycle_f.
qboolean G_FollowSame (gentity_t *ent)
Try to follow the same client as last time (before getting killed)
void Cmd_Kill_f (gentity_t *ent)
Cmd_Kill_f.
void G_IntermissionMapVote (gentity_t *ent)
G_IntermissionMapVote.
void G_IntermissionMapList (gentity_t *ent)
G_IntermissionMapList.
void G_IntermissionVoteTally (gentity_t *ent)
G_IntermissionVoteTally.
void G_EntitySound (gentity_t *ent, const char *soundId, int volume)
Plays a sound (wav file or sound script) on this entity.
void G_EntitySoundNoCut (gentity_t *ent, const char *soundId, int volume)
Similar to G_EntitySound, but do not cut this sound off.
qboolean G_MatchOnePlayer (int *plist, char *err, size_t len)
G_MatchOnePlayer.
int ClientNumberFromString (gentity_t *to, char *s)
ClientNumberFromString.
void SanitizeString (char *in, char *out, qboolean fToLower)
Remove case and control characters.
void G_RunItem (gentity_t *ent)
Run item.
void RespawnItem (gentity_t *ent)
Respawn item.
gentity_t * Drop_Item (gentity_t *ent, gitem_t *item, float angle, qboolean novelocity)
Spawns an item and tosses it forward.
gentity_t * LaunchItem (gitem_t *item, vec3_t origin, vec3_t velocity, int ownerNum)
Spawns an item and tosses it forward.
void G_SpawnItem (gentity_t *ent, gitem_t *item)
Sets the clipping size and plants the object on the floor.
void FinishSpawningItem (gentity_t *ent)
Traces down to find where an item should rest, instead of letting them free fall from their spawn points.
void Fill_Clip (playerState_t *ps, weapon_t weapon)
Push reserve ammo into available space in the clip.
int Add_Ammo (gentity_t *ent, weapon_t weapon, int count, qboolean fillClip)
Add ammo.
void Touch_Item (gentity_t *ent, gentity_t *other, trace_t *trace)
Action when touching an item.
qboolean AddMagicAmmo (gentity_t *receiver, int numOfClips)
Add the specified number of clips of magic ammo.
weapon_t G_GetPrimaryWeaponForClient (gclient_t *client)
Get the primary weapon of the client.
weapon_t G_GetPrimaryWeaponForClientSoldier (weapon_t weapon, gclient_t *client)
Get the primary weapon of the client.
void G_DropWeapon (gentity_t *ent, weapon_t weapon)
Drop Weapon.
void Touch_Item_Auto (gentity_t *ent, gentity_t *other, trace_t *trace)
Auto action when touching an item.
void Prop_Break_Sound (gentity_t *ent)
This should work for all fx types now.
void Spawn_Shard (gentity_t *ent, gentity_t *inflictor, float quantity, int type)
Spawn_Shard.
int G_FindConfigstringIndex (const char *name, int start, int max, qboolean create)
G_FindConfigstringIndex.
void G_RemoveConfigstringIndex (const char *name, int start, int max)
Prevent player always mounting the last gun used, on multiple tank maps. Ported from the Bugfix project (#087)
int G_ModelIndex (const char *name)
G_ModelIndex.
int G_SoundIndex (const char *name)
G_SoundIndex.
int G_SkinIndex (const char *name)
G_SkinIndex.
int G_ShaderIndex (const char *name)
G_ShaderIndex.
int G_CharacterIndex (const char *name)
G_CharacterIndex.
int G_StringIndex (const char *string)
G_StringIndex.
qboolean G_AllowTeamsAllowed (gentity_t *ent, gentity_t *activator)
G_AllowTeamsAllowed.
void G_UseEntity (gentity_t *ent, gentity_t *other, gentity_t *activator)
Added to allow more checking on what uses what.
qboolean G_IsWeaponDisabled (gentity_t *ent, weapon_t weapon)
Checks for heavy and rifle weapons restriction.
void G_TeamCommand (team_t team, const char *cmd)
Broadcasts a command to only a specific team.
gentity_t * G_Find (gentity_t *from, int fieldofs, const char *match)
Searches all active entities for the next one that holds the matching string at fieldofs (use the FOFS() macro) in the structure. Searches beginning at the entity after from, or the beginning if NULL NULL will be returned if the end of the list is reached.
gentity_t * G_FindInt (gentity_t *from, int fieldofs, int match)
Like G_Find, but searches for integer values.
gentity_t * G_FindFloat (gentity_t *from, int fieldofs, float match)
Like G_Find, but searches for float values..
gentity_t * G_FindVector (gentity_t *from, int fieldofs, const vec3_t match)
Like G_Find, but searches for vector values..
gentity_t * G_FindByTargetname (gentity_t *from, const char *match)
G_FindByTargetname.
gentity_t * G_FindByTargetnameFast (gentity_t *from, const char *match, int hash)
This version should be used for loops, saves the constant hash building.
gentity_t * G_PickTarget (const char *targetname)
Selects a random entity from among the targets.
void G_UseTargets (gentity_t *ent, gentity_t *activator)
Search for (string)targetname in all entities that match (string)self.target and call their .use function.
void G_SetMovedir (vec3_t angles, vec3_t movedir)
The editor only specifies a single value for angles (yaw), but we have special constants to generate an up or down direction. Angles will be cleared, because it is being used to represent a direction instead of an orientation.
void G_InitGentity (gentity_t *e)
G_InitGentity.
gentity_t * G_Spawn (void)
Either finds a free entity, or allocates a new one.
gentity_t * G_TempEntity (vec3_t origin, entity_event_t event)
Spawns an event entity that will be auto-removed.
gentity_t * G_TempEntityNotLinked (entity_event_t event)
Spawns an event entity that will be auto-removed Use this for non visible and not origin based events like global sounds etc.
gentity_t * G_PopupMessage (popupMessageType_t type)
G_PopupMessage.
void G_Sound (gentity_t *ent, int soundIndex)
Removed channel parm, since it wasn't used, and could cause confusion.
void G_AnimScriptSound (int soundIndex, vec3_t org, int client)
G_AnimScriptSound.
void G_FreeEntity (gentity_t *ent)
Marks the entity as free.
int G_EntitiesFree (void)
G_EntitiesFree.
void G_ClientSound (gentity_t *ent, int soundIndex)
G_ClientSound.
void G_TouchTriggers (gentity_t *ent)
Find all trigger entities that ent's current position touches.
char * vtos (const vec3_t v)
This is just a convenience function for printing vectors.
void G_AddPredictableEvent (gentity_t *ent, int event, int eventParm)
Use for non-pmove events that would also be predicted on the client side: jumppads and item pickups Adds an event+parm and twiddles the event counter.
void G_AddEvent (gentity_t *ent, int event, int eventParm)
Adds an event+parm and twiddles the event counter.
void G_SetOrigin (gentity_t *ent, vec3_t origin)
Sets the pos trajectory for a fixed position.
void AddRemap (const char *oldShader, const char *newShader, float timeOffset)
AddRemap.
void G_ResetRemappedShaders (void)
G_ResetRemappedShaders.
const char * BuildShaderStateConfig (void)
BuildShaderStateConfig.
void G_SetAngle (gentity_t *ent, vec3_t angle)
G_SetAngle.
qboolean infront (gentity_t *self, gentity_t *other)
infront
void G_ProcessTagConnect (gentity_t *ent, qboolean clearAngles)
G_ProcessTagConnect.
void G_SetEntState (gentity_t *ent, entState_t state)
Sets the entstate of an entity.
void G_ParseCampaigns (void)
G_ParseCampaigns.
qboolean G_MapIsValidCampaignStartMap (void)
G_MapIsValidCampaignStartMap.
team_t G_GetTeamFromEntity (gentity_t *ent)
G_GetTeamFromEntity.
const char * G_StringContains (const char *str1, const char *str2, int casesensitive)
G_StringContains.
qboolean G_MatchString (const char *filter, const char *name, int casesensitive)
G_MatchString.
void G_AdjustedDamageVec (gentity_t *ent, vec3_t origin, vec3_t vec)
G_AdjustedDamageVec.
qboolean CanDamage (gentity_t *targ, vec3_t origin)
Used for explosions and melee attacks.
void G_Damage (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker, vec3_t dir, vec3_t point, int damage, int dflags, meansOfDeath_t mod)
G_Damage.
qboolean G_RadiusDamage (vec3_t origin, gentity_t *inflictor, gentity_t *attacker, float damage, float radius, gentity_t *ignore, meansOfDeath_t mod)
G_RadiusDamage.
qboolean etpro_RadiusDamage (vec3_t origin, gentity_t *inflictor, gentity_t *attacker, float damage, float radius, gentity_t *ignore, meansOfDeath_t mod, qboolean clientsonly)
Mutation of G_RadiusDamage which lets us selectively damage only clients or only non clients.
void body_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t meansOfDeath)
body_die
void TossWeapons (gentity_t *self)
Toss the weapon and powerups for the killed player.
gentity_t * G_BuildHead (gentity_t *ent, grefEntity_t *refent, qboolean newRefent)
G_BuildHead.
gentity_t * G_BuildLeg (gentity_t *ent, grefEntity_t *refent, qboolean newRefent)
G_BuildLeg.
void G_RunMissile (gentity_t *ent)
G_RunMissile.
int G_PredictMissile (gentity_t *ent, int duration, vec3_t endPos, qboolean allowBounce)
G_PredictMissile.
void G_RunFlamechunk (gentity_t *ent)
G_RunFlamechunk.
gentity_t * fire_flamechunk (gentity_t *self, vec3_t start, vec3_t dir)
fire_flamechunk
gentity_t * fire_missile (gentity_t *self, vec3_t start, vec3_t dir, int weapon)
fire_missile
void Fire_Lead_Ext (gentity_t *ent, gentity_t *activator, float spread, int damage, vec3_t muzzle, vec3_t forward, vec3_t right, vec3_t up, meansOfDeath_t mod)
Fire_Lead_Ext - machine/flag gun fire.
gentity_t * fire_flamebarrel (gentity_t *self, vec3_t start, vec3_t dir)
fire_flamebarrel
gentity_t * G_TestEntityPosition (gentity_t *ent)
G_TestEntityPosition.
void G_RunMover (gentity_t *ent)
G_RunMover.
qboolean G_MoverPush (gentity_t *pusher, vec3_t move, vec3_t amove, gentity_t **obstacle)
Objects need to be moved back on a failed push, otherwise riders would continue to slide.
void Use_BinaryMover (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_BinaryMover.
void G_TryDoor (gentity_t *ent, gentity_t *other, gentity_t *activator)
Seemed better to have this isolated. this way i can get func_invisible_user's using the regular rules of doors.
void InitMoverRotate (gentity_t *ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
void InitMover (gentity_t *ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
void SetMoverState (gentity_t *ent, moverState_t moverState, int time)
SetMoverState.
void func_constructible_underconstructionthink (gentity_t *ent)
func_constructible_underconstructionthink
void Think_SetupObjectiveInfo (gentity_t *ent)
Links the trigger to it's objective, determining if it's a func_explosive of func_constructible and spawning the right indicator.
void TeleportPlayer (gentity_t *player, vec3_t origin, vec3_t angles)
Teleport player to a given origin and angles.
void mg42_fire (gentity_t *other)
mg42_fire
void mg42_stopusing (gentity_t *self)
This is to be called for the gun ent, not the tripod.
void aagun_fire (gentity_t *other)
aagun_fire
void aagun_stopusing (gentity_t *self)
aagun_stopusing
float AngleDifference (float ang1, float ang2)
AngleDifference.
qboolean G_FlingClient (gentity_t *vic, int flingType)
G_FlingClient.
void G_PreFilledMissileEntity (gentity_t *ent, int weaponNum, int realWeapon, int ownerNum, team_t teamNum, int clientNum, gentity_t *parent, const vec3_t start, const vec3_t dir)
G_PreFilledMissileEntity.
int G_GetEnemyPosition (gentity_t *ent, gentity_t *targ)
G_GetEnemyPosition.
void G_MagicSink (gentity_t *self)
Magically sink given entity before freeing.
qboolean AccuracyHit (gentity_t *target, gentity_t *attacker)
AccuracyHit.
void CalcMuzzlePoint (gentity_t *ent, int weapon, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
Set muzzle location relative to pivoting eye.
void SnapVectorTowards (vec3_t v, vec3_t to)
SnapVectorTowards.
void G_FadeItems (gentity_t *ent, int modType)
Remove any items that the player should no longer have, on disconnect/class change etc changed to just set the parent to NULL.
gentity_t * G_FindSatchel (gentity_t *ent)
G_FindSatchel.
void G_ExplodeMines (gentity_t *ent)
G_ExplodeMines.
qboolean G_ExplodeSatchels (gentity_t *ent)
G_ExplodeSatchels.
void G_FreeSatchel (gentity_t *ent)
G_FreeSatchel.
void CalcMuzzlePoints (gentity_t *ent, int weapon)
CalcMuzzlePoints.
void CalcMuzzlePointForActivate (gentity_t *ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
For activate.
void Weapon_MagicAmmo_Ext (gentity_t *ent, vec3_t viewpos, vec3_t tosspos, vec3_t velocity)
Weapon_MagicAmmo_Ext.
void Weapon_Medic_Ext (gentity_t *ent, vec3_t viewpos, vec3_t tosspos, vec3_t velocity)
Weapon_Medic_Ext.
int TeamCount (int ignoreClientNum, team_t team)
Count the number of players on a team.
team_t PickTeam (int ignoreClientNum)
PickTeam.
void SetClientViewAngle (gentity_t *ent, vec3_t angle)
SetClientViewAngle.
gentity_t * SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles)
Chooses a player start, deathmatch start, etc.
void respawn (gentity_t *ent)
respawn
void BeginIntermission (void)
BeginIntermission.
void InitBodyQue (void)
InitBodyQue.
void ClientSpawn (gentity_t *ent, qboolean revived, qboolean teamChange, qboolean restoreHealth)
Called every time a client is placed fresh in the world: after the first ClientBegin, and after each respawn Initializes all non-persistant parts of playerState.
void player_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t meansOfDeath)
player_die
void AddKillScore (gentity_t *ent, int score)
Adds score to both the client and his team, only used for LMS.
void CalculateRanks (void)
Recalculates the score ranks of all players. This will be called on every client connect, begin, disconnect, death, and team change.
qboolean SpotWouldTelefrag (gentity_t *spot)
SpotWouldTelefrag.
void SetWolfSpawnWeapons (gclient_t *client)
SetWolfSpawnWeapons.
void limbo (gentity_t *ent, qboolean makeCorpse)
limbo
void reinforce (gentity_t *ent)
Called when time expires for a team deployment cycle and there is at least one guy ready to go.
char * G_SHA1 (const char *string)
G_SHA1.
qboolean G_RegisterCharacter (const char *characterFile, bg_character_t *character)
G_RegisterCharacter.
void G_RegisterPlayerClasses (void)
G_RegisterPlayerClasses.
void G_UpdateCharacter (gclient_t *client)
G_UpdateCharacter.
qboolean ConsoleCommand (void)
ConsoleCommand.
void G_ProcessIPBans (void)
G_ProcessIPBans.
qboolean G_FilterIPBanPacket (char *from)
G_FilterIPBanPacket.
qboolean G_FilterMaxLivesPacket (char *from)
Check to see if the user is trying to sneak back in with g_enforcemaxlives enabled.
qboolean G_FilterMaxLivesIPPacket (char *from)
G_FilterMaxLivesIPPacket.
void AddMaxLivesGUID (const char *str)
>ith g_enforcemaxlives enabled, this adds a client GUID to a list that prevents them from quitting and reconnecting
void AddMaxLivesBan (const char *str)
AddMaxLivesBan.
void ClearMaxLivesBans (void)
Clears out the entire list maxlives enforcement banlist.
void AddIPBan (const char *str)
AddIPBan.
void Svcmd_ShuffleTeamsXP_f (qboolean restart)
randomly places players on teams
void Svcmd_ShuffleTeamsSR_f (qboolean restart)
void FireWeapon (gentity_t *ent)
FireWeapon.
void G_BurnMeGood (gentity_t *self, gentity_t *body, gentity_t *chunk)
BurnMeGood now takes the flamechunk separately, because the old 'set-self-in-flames' method doesn't have a flamechunk to pass, and deaths were getting blamed on the world/player 0.
void MoveClientToIntermission (gentity_t *ent)
When the intermission starts, this will be called for all players. If a new client connects, this will be called after the spawn function.
void G_SendScore (gentity_t *ent)
Sends current scoreboard information.
void G_Say (gentity_t *ent, gentity_t *target, int mode, const char *chatText)
G_Say.
void G_SayTo (gentity_t *ent, gentity_t *other, int mode, int color, const char *name, const char *message, qboolean localize)
G_SayTo.
void G_HQSay (gentity_t *other, int color, const char *name, const char *message)
G_HQSay.
qboolean Cmd_CallVote_f (gentity_t *ent, unsigned int dwCommand, qboolean fRefCommand)
Cmd_CallVote_f.
void Cmd_Follow_f (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Cmd_Follow_f.
void Cmd_Say_f (gentity_t *ent, int mode, qboolean arg0)
Cmd_Say_f.
void Cmd_Team_f (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Cmd_Team_f.
void G_PlaySound_Cmd (void)
G_PlaySound_Cmd.
int ClientNumbersFromString (char *s, int *plist)
Sets plist to an array of integers that represent client numbers that have names that are a partial match for s. List is terminated by a -1.
char * ConcatArgs (int start)
Concatenates console arguments.
void G_DropItems (gentity_t *self)
Drops items. Currently only red-/blueflag.
void FindIntermissionPoint (void)
This is also used for spectator spawns.
void G_RunThink (gentity_t *ent)
Runs thinking code for this frame if necessary.
void QDECL G_LogPrintf (const char *fmt,...) _attribute((format(printf
void QDECL void G_LogExit (const char *string)
Append information about this game to the log file.
void SendScoreboardMessageToAllClients (void)
Do this at BeginIntermission time and whenever ranks are recalculated due to enters/exits/forced team changes.
void QDECL G_Printf (const char *fmt,...) _attribute((format(printf
void QDECL void QDECL G_DPrintf (const char *fmt,...) _attribute((format(printf
void QDECL void QDECL void QDECL G_Error (const char *fmt,...) __attribute__((noreturn
void QDECL void QDECL void QDECL format (printf, 1, 2)))
char * ClientConnect (int clientNum, qboolean firstTime, qboolean isBot)
Called when a player begins connecting to the server. Called again for every map change or tournement restart.
void ClientUserinfoChanged (int clientNum)
Called from ClientConnect when the player first connects and directly by the server system when the player updates a userinfo variable.
void ClientDisconnect (int clientNum)
Called when a player drops from the server. Will not be called between levels.
void ClientBegin (int clientNum)
Called when a client has finished connecting, and is ready to be placed into the level. This will happen every level load, and on transition between teams, but doesn't happen on respawns.
void ClientCommand (int clientNum)
ClientCommand.
float ClientHitboxMaxZ (gentity_t *hitEnt)
ClientHitboxMaxZ.
void ClientThink (int clientNum)
A new command has arrived from the client.
void ClientEndFrame (gentity_t *ent)
Called at the end of each server frame for each connected client A fast client will have multiple ClientThink for each ClientEndFrame, while a slow client may have multiple ClientEndFrame between ClientThink.
void G_RunClient (gentity_t *ent)
G_RunClient.
void ClientThink_cmd (gentity_t *ent, usercmd_t *cmd, qboolean skipServerTime)
etpro antiwarp
void etpro_AddUsercmd (int clientNum, usercmd_t *cmd)
etpro_AddUsercmd
void DoClientThinks (gentity_t *ent)
DoClientThinks.
qboolean G_DoAntiwarp (gentity_t *ent)
G_DoAntiwarp.
qboolean ReadyToCallArtillery (gentity_t *ent)
Does ent have enough "energy" to call artillery?
qboolean ReadyToCallAirstrike (gentity_t *ent)
qboolean ReadyToConstruct (gentity_t *ent, gentity_t *constructible, qboolean updateState)
Are we ready to construct?
qboolean OnSameTeam (gentity_t *ent1, gentity_t *ent2)
OnSameTeam.
void * G_Alloc (unsigned int size)
G_Alloc.
void G_InitMemory (void)
G_InitMemory.
void Svcmd_GameMem_f (void)
Svcmd_GameMem_f.
void G_ReadSessionData (gclient_t *client)
Called on a reconnect.
void G_InitSessionData (gclient_t *client, const char *userinfo)
Called on a first-time connect.
void G_InitWorldSession (void)
G_InitWorldSession.
void G_WriteSessionData (qboolean restart)
G_WriteSessionData.
void G_CalcRank (gclient_t *client)
G_CalcRank.
void Cmd_Activate_f (gentity_t *ent)
Cmd_Activate_f.
void Cmd_Activate2_f (gentity_t *ent)
Cmd_Activate2_f.
qboolean Do_Activate_f (gentity_t *ent, gentity_t *traceEnt)
Extracted out the functionality of Cmd_Activate_f from finding the object to use so we can force bots to use items, without worrying that they are looking EXACTLY at the target.
void G_LeaveTank (gentity_t *ent, qboolean position)
G_LeaveTank.
char * Q_AddCR (char *s)
Replaces all occurances of "\\\\n" with '\n'.
void G_Script_ScriptParse (gentity_t *ent)
Parses the script for the given entity.
qboolean G_Script_ScriptRun (gentity_t *ent)
G_Script_ScriptRun.
void G_Script_ScriptLoad (void)
Loads the script for the current level into the buffer.
void mountedmg42_fire (gentity_t *other)
mountedmg42_fire
void script_mover_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
script_mover_use
void script_mover_blocked (gentity_t *ent, gentity_t *other)
script_mover_blocked
qboolean G_ScriptAction_GotoMarker (gentity_t *ent, char *params)
G_ScriptAction_GotoMarker.
qboolean G_ScriptAction_Wait (gentity_t *ent, char *params)
G_ScriptAction_Wait.
qboolean G_ScriptAction_Trigger (gentity_t *ent, char *params)
Calls the specified trigger for the given ai character or script entity.
qboolean G_ScriptAction_PlaySound (gentity_t *ent, char *params)
Currently only allows playing on the VOICE channel, unless you use a sound script. Use the optional LOOPING paramater to attach the sound to the entities looping channel. syntax: playsound <soundname OR scriptname> [LOOPING].
qboolean G_ScriptAction_PlayAnim (gentity_t *ent, char *params)
G_ScriptAction_PlayAnim.
qboolean G_ScriptAction_AlertEntity (gentity_t *ent, char *params)
Modified to target multiple entities with the same targetname.
qboolean G_ScriptAction_ToggleSpeaker (gentity_t *ent, char *params)
G_ScriptAction_ToggleSpeaker.
qboolean G_ScriptAction_DisableSpeaker (gentity_t *ent, char *params)
G_ScriptAction_DisableSpeaker.
qboolean G_ScriptAction_EnableSpeaker (gentity_t *ent, char *params)
G_ScriptAction_EnableSpeaker.
qboolean G_ScriptAction_Accum (gentity_t *ent, char *params)
G_ScriptAction_Accum.
qboolean G_ScriptAction_GlobalAccum (gentity_t *ent, char *params)
G_ScriptAction_GlobalAccum.
qboolean G_ScriptAction_Print (gentity_t *ent, char *params)
Mostly for debugging purposes.
qboolean G_ScriptAction_FaceAngles (gentity_t *ent, char *params)
The entity will face the given angles, taking <duration> to get their. If the GOTOTIME is given instead of a timed duration, the duration calculated from the last gotomarker command will be used instead.
qboolean G_ScriptAction_ResetScript (gentity_t *ent, char *params)
Causes any currently running scripts to abort, in favour of the current script.
qboolean G_ScriptAction_TagConnect (gentity_t *ent, char *params)
Connect this entity onto the tag of another entity.
qboolean G_ScriptAction_Halt (gentity_t *ent, char *params)
Stop moving.
qboolean G_ScriptAction_StopSound (gentity_t *ent, char *params)
Stops any looping sounds for this entity.
qboolean G_ScriptAction_EntityScriptName (gentity_t *ent, char *params)
G_ScriptAction_EntityScriptName.
qboolean G_ScriptAction_AxisRespawntime (gentity_t *ent, char *params)
G_ScriptAction_AxisRespawntime.
qboolean G_ScriptAction_AlliedRespawntime (gentity_t *ent, char *params)
G_ScriptAction_AlliedRespawntime.
qboolean G_ScriptAction_NumberofObjectives (gentity_t *ent, char *params)
G_ScriptAction_NumberofObjectives.
qboolean G_ScriptAction_SetWinner (gentity_t *ent, char *params)
G_ScriptAction_SetWinner.
qboolean G_ScriptAction_SetDefendingTeam (gentity_t *ent, char *params)
Sets defending team for stopwatch mode.
qboolean G_ScriptAction_Announce (gentity_t *ent, char *params)
G_ScriptAction_Announce.
qboolean G_ScriptAction_Announce_Icon (gentity_t *ent, char *params)
G_ScriptAction_Announce_Icon.
qboolean G_ScriptAction_AddTeamVoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_AddTeamVoiceAnnounce.
qboolean G_ScriptAction_RemoveTeamVoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_RemoveTeamVoiceAnnounce.
qboolean G_ScriptAction_TeamVoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_TeamVoiceAnnounce.
qboolean G_ScriptAction_EndRound (gentity_t *ent, char *params)
G_ScriptAction_EndRound.
qboolean G_ScriptAction_SetRoundTimelimit (gentity_t *ent, char *params)
G_ScriptAction_SetRoundTimelimit.
qboolean G_ScriptAction_RemoveEntity (gentity_t *ent, char *params)
G_ScriptAction_RemoveEntity.
qboolean G_ScriptAction_SetState (gentity_t *ent, char *params)
G_ScriptAction_SetState.
qboolean G_ScriptAction_VoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_VoiceAnnounce.
qboolean G_ScriptAction_FollowSpline (gentity_t *ent, char *params)
G_ScriptAction_FollowSpline.
qboolean G_ScriptAction_FollowPath (gentity_t *ent, char *params)
G_ScriptAction_FollowPath.
qboolean G_ScriptAction_AbortMove (gentity_t *ent, char *params)
G_ScriptAction_AbortMove.
qboolean G_ScriptAction_SetSpeed (gentity_t *ent, char *params)
G_ScriptAction_SetSpeed.
qboolean G_ScriptAction_SetRotation (gentity_t *ent, char *params)
G_ScriptAction_SetRotation.
qboolean G_ScriptAction_StopRotation (gentity_t *ent, char *params)
G_ScriptAction_StopRotation.
qboolean G_ScriptAction_StartAnimation (gentity_t *ent, char *params)
G_ScriptAction_StartAnimation.
qboolean G_ScriptAction_AttatchToTrain (gentity_t *ent, char *params)
G_ScriptAction_AttatchToTrain.
qboolean G_ScriptAction_FreezeAnimation (gentity_t *ent, char *params)
G_ScriptAction_FreezeAnimation.
qboolean G_ScriptAction_UnFreezeAnimation (gentity_t *ent, char *params)
G_ScriptAction_UnFreezeAnimation.
qboolean G_ScriptAction_ShaderRemap (gentity_t *ent, char *params)
G_ScriptAction_ShaderRemap.
qboolean G_ScriptAction_ShaderRemapFlush (gentity_t *ent, char *params)
G_ScriptAction_ShaderRemapFlush.
qboolean G_ScriptAction_ChangeModel (gentity_t *ent, char *params)
G_ScriptAction_ChangeModel.
qboolean G_ScriptAction_SetChargeTimeFactor (gentity_t *ent, char *params)
syntax: setchargetimefactor <team> <class> <factor> team: 0 = axis, 1 = allies
qboolean G_ScriptAction_SetDamagable (gentity_t *ent, char *params)
G_ScriptAction_SetDamagable.
qboolean G_ScriptAction_RepairMG42 (gentity_t *ent, char *params)
G_ScriptAction_RepairMG42.
qboolean G_ScriptAction_SetHQStatus (gentity_t *ent, char *params)
G_ScriptAction_SetHQStatus.
qboolean G_ScriptAction_PrintAccum (gentity_t *ent, char *params)
Prints out the value of accum 'accumNumber'.
qboolean G_ScriptAction_PrintGlobalAccum (gentity_t *ent, char *params)
prints out the value of global accum 'globalaccumnumber'
qboolean G_ScriptAction_ObjectiveStatus (gentity_t *ent, char *params)
G_ScriptAction_ObjectiveStatus.
qboolean G_ScriptAction_SetModelFromBrushmodel (gentity_t *ent, char *params)
G_ScriptAction_SetModelFromBrushmodel.
qboolean G_ScriptAction_SetPosition (gentity_t *ent, char *params)
G_ScriptAction_SetPosition.
qboolean G_ScriptAction_SetAutoSpawn (gentity_t *ent, char *params)
G_ScriptAction_SetAutoSpawn.
qboolean G_ScriptAction_SetMainObjective (gentity_t *ent, char *params)
syntax: wm_set_main_objective <objective_targetname> <team>
qboolean G_ScriptAction_SpawnRubble (gentity_t *ent, char *params)
G_ScriptAction_SpawnRubble.
qboolean G_ScriptAction_AllowTankExit (gentity_t *ent, char *params)
G_ScriptAction_AllowTankExit.
qboolean G_ScriptAction_AllowTankEnter (gentity_t *ent, char *params)
G_ScriptAction_AllowTankEnter.
qboolean G_ScriptAction_SetTankAmmo (gentity_t *ent, char *params)
G_ScriptAction_SetTankAmmo.
qboolean G_ScriptAction_AddTankAmmo (gentity_t *ent, char *params)
G_ScriptAction_AddTankAmmo.
qboolean G_ScriptAction_Kill (gentity_t *ent, char *params)
G_ScriptAction_Kill.
qboolean G_ScriptAction_DisableMessage (gentity_t *ent, char *params)
G_ScriptAction_DisableMessage - obsolete function used for old bot ai.
qboolean G_ScriptAction_SetGlobalFog (gentity_t *ent, char *params)
G_ScriptAction_SetGlobalFog.
qboolean G_ScriptAction_Cvar (gentity_t *ent, char *params)
G_ScriptAction_Cvar.
qboolean G_ScriptAction_AbortIfWarmup (gentity_t *ent, char *params)
G_ScriptAction_AbortIfWarmup.
qboolean G_ScriptAction_AbortIfNotSinglePlayer (gentity_t *ent, char *params)
G_ScriptAction_AbortIfNotSinglePlayer.
qboolean G_ScriptAction_MusicStart (gentity_t *ent, char *params)
G_ScriptAction_MusicStart.
qboolean G_ScriptAction_MusicPlay (gentity_t *ent, char *params)
G_ScriptAction_MusicPlay.
qboolean G_ScriptAction_MusicStop (gentity_t *ent, char *params)
G_ScriptAction_MusicStop.
qboolean G_ScriptAction_MusicQueue (gentity_t *ent, char *params)
G_ScriptAction_MusicQueue.
qboolean G_ScriptAction_MusicFade (gentity_t *ent, char *params)
G_ScriptAction_MusicFade.
qboolean G_ScriptAction_SetDebugLevel (gentity_t *ent, char *params)
G_ScriptAction_SetDebugLevel.
qboolean G_ScriptAction_FadeAllSounds (gentity_t *ent, char *params)
Fades all sounds up or down, going from the current level to max or zero in 'time' milliseconds.
qboolean G_ScriptAction_Construct (gentity_t *ent, char *params)
G_ScriptAction_Construct.
qboolean G_ScriptAction_ConstructibleClass (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleClass.
qboolean G_ScriptAction_ConstructibleChargeBarReq (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleChargeBarReq.
qboolean G_ScriptAction_ConstructibleConstructXPBonus (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleConstructXPBonus.
qboolean G_ScriptAction_ConstructibleDestructXPBonus (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleDestructXPBonus.
qboolean G_ScriptAction_ConstructibleHealth (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleHealth.
qboolean G_ScriptAction_ConstructibleWeaponclass (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleWeaponclass.
qboolean G_ScriptAction_ConstructibleDuration (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleDuration.
qboolean etpro_ScriptAction_SetValues (gentity_t *ent, char *params)
etpro_ScriptAction_SetValues
qboolean G_ScriptAction_Create (gentity_t *ent, char *params)
Added for compatability with etpro map scripts.
qboolean G_ScriptAction_Delete (gentity_t *ent, char *params)
Delete entities that match all the criteria provided in "params".
void Props_Chair_Skyboxtouch (gentity_t *ent)
Props_Chair_Skyboxtouch.
unsigned long GeoIP_addr_to_num (const char *addr)
GeoIP_addr_to_num.
unsigned int GeoIP_seek_record (GeoIP *gi, unsigned long ipnum)
GeoIP_seek_record.
void GeoIP_open (void)
GeoIP_open.
void GeoIP_close (void)
GeoIP_close.
void trap_Printf (const char *fmt)
trap_Printf
void trap_Error (const char *fmt) __attribute__((noreturn))
trap_Error
int trap_Milliseconds (void)
trap_Milliseconds
int trap_Argc (void)
trap_Argc
void trap_Argv (int n, char *buffer, int bufferLength)
trap_Argv
void trap_Args (char *buffer, int bufferLength)
trap_Args
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
trap_FS_FOpenFile
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
trap_FS_Read
int trap_FS_Write (const void *buffer, int len, fileHandle_t f)
trap_FS_Write
int trap_FS_Rename (const char *from, const char *to)
trap_FS_Rename
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
trap_FS_GetFileList
void trap_SendConsoleCommand (int exec_when, const char *text)
trap_SendConsoleCommand
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
trap_Cvar_Register
void trap_Cvar_Update (vmCvar_t *vmCvar)
trap_Cvar_Update
void trap_Cvar_Set (const char *varName, const char *value)
trap_Cvar_Set
int trap_Cvar_VariableIntegerValue (const char *varName)
trap_Cvar_VariableIntegerValue
float trap_Cvar_VariableValue (const char *varName)
trap_Cvar_VariableValue
void trap_Cvar_VariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_VariableStringBuffer
void trap_Cvar_LatchedVariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
void trap_LocateGameData (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *gameClients, int sizeofGClient)
trap_LocateGameData
void trap_DropClient (int clientNum, const char *reason, int length)
trap_DropClient
void trap_SendServerCommand (int clientNum, const char *text)
trap_SendServerCommand
void trap_SetConfigstring (int num, const char *string)
trap_SetConfigstring
void trap_GetConfigstring (int num, char *buffer, int bufferSize)
trap_GetConfigstring
void trap_GetUserinfo (int num, char *buffer, int bufferSize)
trap_GetUserinfo
void trap_SetUserinfo (int num, const char *buffer)
trap_SetUserinfo
void trap_GetServerinfo (char *buffer, int bufferSize)
trap_GetServerinfo
void trap_SetBrushModel (gentity_t *ent, const char *name)
trap_SetBrushModel
void trap_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_Trace
void trap_TraceCapsule (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsule
void trap_TraceCapsuleNoEnts (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsuleNoEnts
void trap_TraceNoEnts (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceNoEnts
int trap_PointContents (const vec3_t point, int passEntityNum)
trap_PointContents
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
trap_InPVS
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
trap_InPVSIgnorePortals
void trap_AdjustAreaPortalState (gentity_t *ent, qboolean open)
trap_AdjustAreaPortalState
qboolean trap_AreasConnected (int area1, int area2)
trap_AreasConnected
void trap_LinkEntity (gentity_t *ent)
trap_LinkEntity
void trap_UnlinkEntity (gentity_t *ent)
trap_UnlinkEntity
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int *list, int maxCount)
trap_EntitiesInBox
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
trap_EntityContact
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
int trap_BotAllocateClient (int clientNum)
trap_BotAllocateClient
int trap_BotGetServerCommand (int clientNum, char *message, int size)
trap_BotGetServerCommand
void trap_BotUserCommand (int clientNum, usercmd_t *ucmd)
trap_BotUserCommand
void trap_EA_Command (int clientNum, char *command)
trap_EA_Command
void trap_GetUsercmd (int clientNum, usercmd_t *cmd)
trap_GetUsercmd
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
trap_GetEntityToken
qboolean trap_GetTag (int clientNum, int tagFileNumber, char *tagName, orientation_t *orientation)
trap_GetTag
qboolean trap_LoadTag (const char *filename)
trap_LoadTag
int trap_RealTime (qtime_t *qtime)
trap_RealTime
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
trap_DebugPolygonCreate
void trap_DebugPolygonDelete (int id)
trap_DebugPolygonDelete
void trap_SnapVector (float *v)
trap_SnapVector
qboolean trap_SendMessage (int clientNum, char *buf, int buflen)
Sends binary messages. Since ETL 2.76 this is no longer void. See new return values.
messageStatus_t trap_MessageStatus (int clientNum)
trap_MessageStatus
void G_ExplodeMissile (gentity_t *ent)
Explode a missile without an impact.
void Svcmd_StartMatch_f (void)
starts match if in tournament mode
void Svcmd_ResetMatch_f (qboolean fDoReset, qboolean fDoRestart)
Multi-use now for both map restarts and total match resets.
void Svcmd_SwapTeams_f (void)
swaps all clients to opposite team
void G_StoreClientPosition (gentity_t *ent)
G_StoreClientPosition.
void G_ReAdjustSingleClientPosition (gentity_t *ent)
G_ReAdjustSingleClientPosition.
void G_ResetMarkers (gentity_t *ent)
G_ResetMarkers.
void G_HistoricalTrace (gentity_t *ent, trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Run a trace with players in historical positions.
void G_HistoricalTraceBegin (gentity_t *ent)
G_HistoricalTraceBegin.
void G_HistoricalTraceEnd (gentity_t *ent)
G_HistoricalTraceEnd.
void G_Trace (gentity_t *ent, trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, qboolean ignoreCorpses)
Run a trace without fixups (historical fixups will be done externally)
void G_PredictPmove (gentity_t *ent, float frametime)
Make use of the 'Pmove' functions to figure out where a player would have moved in the short amount of time indicated by frametime.
void Cmd_FireTeam_MP_f (gentity_t *ent)
Cmd_FireTeam_MP_f.
void G_RemoveFromAllIgnoreLists (int clientNum)
G_RemoveFromAllIgnoreLists.
void G_InitMapEntityData (mapEntityData_Team_t *teamList)
G_InitMapEntityData.
mapEntityData_t * G_FreeMapEntityData (mapEntityData_Team_t *teamList, mapEntityData_t *mEnt)
G_FreeMapEntityData.
mapEntityData_t * G_AllocMapEntityData (mapEntityData_Team_t *teamList)
G_AllocMapEntityData.
mapEntityData_t * G_FindMapEntityData (mapEntityData_Team_t *teamList, int entNum)
G_FindMapEntityData.
mapEntityData_t * G_FindMapEntityDataSingleClient (mapEntityData_Team_t *teamList, mapEntityData_t *start, int entNum, int clientNum)
G_FindMapEntityDataSingleClient.
void G_ResetTeamMapData (void)
G_ResetTeamMapData.
void G_UpdateTeamMapData (void)
G_UpdateTeamMapData.
void G_SetupFrustum (gentity_t *ent)
G_SetupFrustum.
void G_SetupFrustum_ForBinoculars (gentity_t *ent)
G_SetupFrustum_ForBinoculars.
qboolean G_VisibleFromBinoculars (gentity_t *viewer, gentity_t *ent, vec3_t origin)
G_VisibleFromBinoculars.
qboolean G_VisibleFromBinoculars_Box (gentity_t *viewer, gentity_t *ent, vec3_t origin, vec3_t mins, vec3_t maxs)
G_VisibleFromBinoculars_Box.
void G_LogTeamKill (gentity_t *ent, weapon_t weap)
G_LogTeamKill.
void G_LogDeath (gentity_t *ent, weapon_t weap)
G_LogDeath.
void G_LogKill (gentity_t *ent, weapon_t weap)
G_LogKill.
void G_LogRegionHit (gentity_t *ent, hitRegion_t hr)
G_LogRegionHit.
void G_ResetXP (gentity_t *ent)
G_ResetXP.
void G_SetPlayerScore (gclient_t *client)
G_SetPlayerScore.
void G_SetPlayerSkill (gclient_t *client, skillType_t skill)
G_SetPlayerSkill.
void G_AddSkillPoints (gentity_t *ent, skillType_t skill, float points)
G_AddSkillPoints.
void G_LoseSkillPoints (gentity_t *ent, skillType_t skill, float points)
G_LoseSkillPoints.
void G_AddKillSkillPoints (gentity_t *attacker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
G_AddKillSkillPoints.
void G_AddKillSkillPointsForDestruction (gentity_t *attacker, meansOfDeath_t mod, g_constructible_stats_t *constructibleStats)
G_AddKillSkillPointsForDestruction.
void G_LoseKillSkillPoints (gentity_t *tker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
Loose skill for evil tkers :E.
void G_DebugOpenSkillLog (void)
G_DebugOpenSkillLog.
void G_DebugCloseSkillLog (void)
G_DebugCloseSkillLog.
void G_DebugAddSkillLevel (gentity_t *ent, skillType_t skill)
G_DebugAddSkillLevel.
void G_DebugAddSkillPoints (gentity_t *ent, skillType_t skill, float points, const char *reason)
G_DebugAddSkillPoints.
void G_SendMapEntityInfo (gentity_t *e)
G_SendMapEntityInfo.
void G_SendSystemMessage (sysMsg_t message, int team)
G_SendSystemMessage.
int G_GetSysMessageNumber (const char *sysMsg)
G_GetSysMessageNumber.
int G_CountTeamLandmines (team_t team)
G_CountTeamLandmines.
qboolean G_SweepForLandmines (vec3_t origin, float radius, int team)
G_SweepForLandmines.
void G_AddClientToFireteam (int entityNum, int leaderNum)
Only way a client should ever join a fireteam, other than creating one.
void G_InviteToFireTeam (int entityNum, int otherEntityNum)
The only way a client should ever be invited to join a team.
void G_UpdateFireteamConfigString (fireteamData_t *ft)
G_UpdateFireteamConfigString.
void G_RemoveClientFromFireteams (int entityNum, qboolean update, qboolean print)
The only way a client should be removed from a fireteam.
void G_PrintClientSpammyCenterPrint (int entityNum, const char *text)
G_PrintClientSpammyCenterPrint.
void G_UpdateCvars (void)
G_UpdateCvars.
void G_wipeCvars (void)
Reset particular server variables back to defaults if a config is voted in.
qboolean G_commandCheck (gentity_t *ent, const char *cmd, qboolean fDoAnytime)
G_commandCheck.
qboolean G_commandHelp (gentity_t *ent, const char *pszCommand, unsigned int dwCommand)
Prints specific command help info.
qboolean G_cmdDebounce (gentity_t *ent, const char *pszCommand)
Debounces cmd request as necessary.
void G_commands_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Lists server commands.
void G_lock_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team.
void G_pause_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fPause)
Pause/unpause a match.
void G_players_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Show client info.
void G_ready_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Sets a player's "ready" status.
void G_say_teamnl_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Team chat w/no location info.
void G_sclogin_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Request for shoutcaster status.
void G_sclogout_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Removes shoutcaster status.
void G_makesc_cmd (void)
Set shoutcaster command.
void G_removesc_cmd (void)
Remove shoutcaster command.
void G_scores_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Shows match stats to the requesting client.
void G_specinvite_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fLock)
Sends an invitation to a player to spectate a team.
void G_speclock_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team from spectators.
void G_statsall_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Shows all players' stats to the requesting client.
void G_teamready_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Sets a player's team "ready" status.
void G_weaponRankings_cmd (gentity_t *ent, unsigned int dwCommand, qboolean state)
Shows best/worst accuracy for all weapons, or sorted accuracies for a single weapon.
void G_weaponStats_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fDump)
Shows a player's stats to the requesting client.
void G_weaponStatsLeaders_cmd (gentity_t *ent, qboolean doTop, qboolean doWindow)
Shows the most accurate players for each weapon to the requesting client.
void G_VoiceTo (gentity_t *ent, gentity_t *other, int mode, const char *id, qboolean voiceonly, float randomNum)
G_VoiceTo.
qboolean G_configSet (const char *configname)
Force settings to predefined state.
void G_ConfigCheckLocked (void)
G_ConfigCheckLocked.
void G_PrintConfigs (gentity_t *ent)
G_PrintConfigs.
qboolean G_isValidConfig (gentity_t *ent, const char *configname)
Checks if config file is in paths (used before initiating a vote for configs)
void G_ReloadConfig (void)
G_ReloadConfig.
void G_addStats (gentity_t *targ, gentity_t *attacker, int damage, meansOfDeath_t mod)
G_addStats.
void G_addStatsHeadShot (gentity_t *attacker, meansOfDeath_t mod)
Records weapon headshots.
int G_checkServerToggle (vmCvar_t *cv)
Update configstring for vote info.
char * G_createStats (gentity_t *refEnt)
Generates weapon stat info for given ent.
void G_deleteStats (int nClient)
Resets player's current stats (session related only)
qboolean G_desiredFollow (gentity_t *ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
void G_globalSound (const char *sound)
Plays specified sound globally.
void G_globalSoundEnum (int sound)
G_globalSoundEnum.
void G_initMatch (void)
G_initMatch.
void G_loadMatchGame (void)
Setting initialization.
void G_matchInfoDump (unsigned int dwDumpType)
Dumps end-of-match info.
void G_printMatchInfo (gentity_t *ent)
Prints current player match info.
void G_parseStats (const char *pszStatsInfo)
Parses weapon stat info for given ent The given string must be space delimited and contain only integers.
void G_printFull (const char *str, gentity_t *ent)
Simple alias for sure-fire print :)
void G_resetModeState (void)
G_resetModeState.
void G_resetRoundState (void)
G_resetRoundState.
void G_spawnPrintf (int print_type, int print_time, gentity_t *owner)
G_spawnPrintf.
void G_statsPrint (gentity_t *ent, int nType)
Sends a player's stats to the requesting client.
void G_UpgradeSkill (gentity_t *ent, skillType_t skill)
Local func to actual do skill upgrade, used by both MP skill system, and SP scripted skill system.
void Cmd_AuthRcon_f (gentity_t *ent)
Client authentication.
void G_refAllReady_cmd (gentity_t *ent)
Readies all players in the game.
void G_ref_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Request for ref status or lists ref commands.
qboolean G_refCommandCheck (gentity_t *ent, const char *cmd)
Parses for a referee command. ref arg allows for the server console to utilize all referee commands (ent == NULL)
void G_refHelp_cmd (gentity_t *ent)
Lists ref commands.
void G_refLockTeams_cmd (gentity_t *ent, qboolean fLock)
Changes team lock status.
void G_refPause_cmd (gentity_t *ent, qboolean fPause)
Pause/unpause a match.
void G_refPlayerPut_cmd (gentity_t *ent, team_t team_id)
Puts a player on a team.
void G_refRemove_cmd (gentity_t *ent)
Removes a player from a team.
void G_refSpeclockTeams_cmd (gentity_t *ent, qboolean fLock)
Changes team spectator lock status.
void G_refWarmup_cmd (gentity_t *ent)
G_refWarmup_cmd.
void G_refWarning_cmd (gentity_t *ent)
G_refWarning_cmd.
void G_refMute_cmd (gentity_t *ent, qboolean mute)
(Un)Mutes a player
void G_refMakeShoutcaster_cmd (gentity_t *ent)
G_refMakeShoutcaster_cmd.
void G_refRemoveShoutcaster_cmd (gentity_t *ent)
G_refRemoveShoutcaster_cmd.
void G_refLogout_cmd (gentity_t *ent)
G_refLogout_cmd.
int G_refClientnumForName (gentity_t *ent, const char *name)
G_refClientnumForName.
void G_refPrintf (gentity_t *ent, const char *fmt,...) _attribute((format(printf
void void G_PlayerBan (void)
G_PlayerBan.
void G_MakeReferee (void)
G_MakeReferee.
void G_RemoveReferee (void)
G_RemoveReferee.
void G_MuteClient (void)
G_MuteClient.
void G_UnMuteClient (void)
G_UnMuteClient.
qboolean G_IsShoutcastPasswordSet (void)
G_IsShoutcastPasswordSet.
qboolean G_IsShoutcastStatusAvailable (gentity_t *ent)
G_IsShoutcastStatusAvailable.
void G_MakeShoutcaster (gentity_t *ent)
G_MakeShoutcaster.
void G_RemoveShoutcaster (gentity_t *ent)
G_RemoveShoutcaster.
void G_RemoveAllShoutcasters (void)
G_RemoveAllShoutcasters.
qboolean G_allowFollow (gentity_t *ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
int G_blockoutTeam (gentity_t *ent, int nTeam)
Return blockout status for a player.
qboolean G_checkReady (void)
Determine if the "ready" player threshold has been reached.
qboolean G_readyMatchState (void)
Checks ready states to start/stop the sequence to get the match rolling.
void G_removeSpecInvite (int team)
Removes everyone's specinvite for a particular team.
void G_shuffleTeamsXP (void)
Shuffle active players onto teams.
void G_shuffleTeamsSR (void)
void G_swapTeamLocks (void)
Swap team speclocks.
void G_swapTeams (void)
Swaps active players on teams.
qboolean G_teamJoinCheck (team_t nTeam, gentity_t *ent)
Checks to see if a specified team is allowing players to join.
void G_teamReset (int team_num, qboolean fClearSpecLock)
Resets a team's settings.
void G_verifyMatchState (team_t nTeam)
Check if we need to reset the game state due to an empty team.
void G_updateSpecLock (int nTeam, qboolean fLock)
Update specs for blackout, as needed.
int OtherTeam (int team)
OtherTeam.
const char * TeamName (int team)
TeamName.
const char * TeamColorString (int team)
TeamColorString.
void Team_DroppedFlagThink (gentity_t *ent)
Automatically set in Launch_Item if the item is one of the flags.
void Team_ReturnFlag (gentity_t *ent)
Team_ReturnFlag.
gentity_t * SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, int spawnObjective)
SelectCTFSpawnPoint.
void TeamplayInfoMessage (team_t team)
TeamplayInfoMessage.
void CheckTeamStatus (void)
CheckTeamStatus.
int Pickup_Team (gentity_t *ent, gentity_t *other)
Pickup_Team.
void G_globalFlagIndicator (void)
G_globalFlagIndicator.
void G_clientFlagIndicator (gentity_t *ent)
G_clientFlagIndicator.
int G_voteCmdCheck (gentity_t *ent, char *arg, char *arg2, qboolean fRefereeCmd)
Checks for valid custom callvote requests from the client.
void G_voteFlags (void)
Set disabled votes for client UI.
void G_voteHelp (gentity_t *ent, qboolean fShowVote)
Voting help summary.
void G_playersMessage (gentity_t *ent)
Player ID message stub.
int G_Gametype_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
GameType.
int G_Kick_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Player Kick.
int G_Mute_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Player Mute.
int G_UnMute_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Player Un-Mute.
int G_Map_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Map - simpleton: we dont verify map is allowed/exists.
int G_Campaign_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Campaign - simpleton: we dont verify map is allowed/exists.
int G_MapRestart_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Map Restart.
int G_MatchReset_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Match Restart.
int G_Mutespecs_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Mute Spectators.
int G_Nextmap_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Nextmap.
int G_Referee_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Referee voting.
int G_ShuffleTeamsXP_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Shuffle teams by XP.
int G_ShuffleTeamsXP_NoRestart_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Shuffle teams by XP without restart.
int G_StartMatch_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Start Match.
int G_SwapTeams_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Swap teams.
int G_FriendlyFire_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Team Damage.
int G_Timelimit_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Timelimit.
int G_Warmupfire_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Warmup Weapon Fire.
int G_Unreferee_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Un-Referee voting.
int G_AntiLag_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Anti-Lag.
int G_BalancedTeams_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Balanced Teams.
int G_Surrender_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_Surrender_v.
int G_RestartCampaign_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_RestartCampaign_v.
int G_NextCampaign_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_NextCampaign_v.
int G_Poll_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_Poll_v.
int G_Config_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_Config_v.
void G_LinkDebris (void)
G_LinkDebris.
void G_LinkDamageParents (void)
G_LinkDamageParents.
int EntsThatRadiusCanDamage (vec3_t origin, float radius, int *damagedList)
Crude version of G_RadiusDamage to see if the dynamite can damage a func_constructible.
qboolean G_LandmineTriggered (gentity_t *ent)
G_LandmineTriggered.
qboolean G_LandmineArmed (gentity_t *ent)
G_LandmineArmed.
qboolean G_LandmineUnarmed (gentity_t *ent)
G_LandmineUnarmed.
qboolean G_LandmineSpotted (gentity_t *ent)
G_LandmineSpotted.
qboolean G_AvailableAirstrike (gentity_t *ent)
G_AvailableAirstrikes.
qboolean G_AvailableArtillery (gentity_t *ent)
Arty/airstrike rate limiting.
void G_AddAirstrikeToCounters (gentity_t *ent)
G_AddAirstrikeToCounters.
void G_AddArtilleryToCounters (gentity_t *ent)
G_AddArtilleryToCounters.
int G_MaxAvailableAirstrikes (gentity_t *ent)
G_MaxAvailableAirstrikes.
int G_MaxAvailableArtillery (gentity_t *ent)
G_MaxAvailableArtillery.
void G_SetTargetName (gentity_t *ent, char *targetname)
G_SetTargetName.
void G_KillEnts (const char *target, gentity_t *ignore, gentity_t *killer, meansOfDeath_t mod)
Kills the activator. (default)
void trap_EngineerTrace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_EngineerTrace
int G_CountTeamMedics (team_t team, qboolean alivecheck)
G_CountTeamMedics.
int G_CountTeamFieldops (team_t team)
G_CountTeamFieldops.
qboolean G_TankIsOccupied (gentity_t *ent)
G_TankIsOccupied.
qboolean G_TankIsMountable (gentity_t *ent, gentity_t *other)
G_TankIsMountable.
qboolean G_ConstructionBegun (gentity_t *ent)
G_ConstructionBegun.
qboolean G_ConstructionIsFullyBuilt (gentity_t *ent)
G_ConstructionIsFullyBuilt.
qboolean G_ConstructionIsPartlyBuilt (gentity_t *ent)
G_ConstructionIsPartlyBuilt.
gentity_t * G_ConstructionForTeam (gentity_t *toi, team_t team)
G_ConstructionForTeam.
gentity_t * G_IsConstructible (team_t team, gentity_t *toi)
G_IsConstructible.
qboolean G_EmplacedGunIsRepairable (gentity_t *ent, gentity_t *other)
G_EmplacedGunIsRepairable.
qboolean G_EmplacedGunIsMountable (gentity_t *ent, gentity_t *other)
G_EmplacedGunIsMountable.
void G_CheckForCursorHints (gentity_t *ent)
non-AI's check for cursor hint contacts
void G_CalcClientAccuracies (void)
G_CalcClientAccuracies.
void G_BuildEndgameStats (void)
send name, team and value when there is a winner - else empty string and TEAM_FREE = 0 (client structure is only used for awards!)
int G_TeamCount (gentity_t *ent, int weap)
G_TeamCount.
qboolean G_IsFireteamLeader (int entityNum, fireteamData_t **teamNum)
G_IsFireteamLeader.
fireteamData_t * G_FindFreePublicFireteam (team_t team)
G_FindFreePublicFireteam.
void G_RegisterFireteam (int entityNum)
Should be the only function that ever creates a fireteam.
void weapon_callAirStrike (gentity_t *ent)
Launch airstrike as line of bombs mostly-perpendicular to line of grenade travel (close air support should always drop parallel to friendly lines, tho accidents do happen)
void weapon_checkAirStrikeThink (gentity_t *ent)
weapon_checkAirStrikeThink
void weapon_callSecondPlane (gentity_t *ent)
qboolean weapon_checkAirStrike (gentity_t *ent)
weapon_checkAirStrike
void weapon_smokeBombExplode (gentity_t *ent)
Increases postsmoke time from 2000->32000, this way, the entity is still around while the smoke is around, so we can check if it blocks bot's vision.
void DynaSink (gentity_t *self)
DynaSink.
void DynaFree (gentity_t *self)
DynaFree.
void G_MakeReady (gentity_t *ent)
G_MakeReady.
void G_MakeUnready (gentity_t *ent)
G_MakeUnready.
void SetPlayerSpawn (gentity_t *ent, int spawn, qboolean update)
SetPlayerSpawn.
void G_UpdateSpawnPointState (gentity_t *ent)
Udates spawn point state.
void G_UpdateSpawnPointStatePlayerCounts ()
Udates player counts in all spawn point states.
void G_SetConfigStringValue (int num, const char *key, const char *value)
G_SetConfigStringValue.
void G_GlobalClientEvent (entity_event_t event, int param, int client)
G_GlobalClientEvent.
void G_InitTempTraceIgnoreEnts (void)
System to temporarily ignore certain ents during traces.
void G_ResetTempTraceIgnoreEnts (void)
G_ResetTempTraceIgnoreEnts.
void G_TempTraceIgnoreEntity (gentity_t *ent)
G_TempTraceIgnoreEntity.
void G_TempTraceIgnorePlayersAndBodies (void)
G_TempTraceIgnorePlayersAndBodies.
qboolean G_CanPickupWeapon (weapon_t weapon, gentity_t *ent)
Check if a weapon can be picked up.
qboolean G_LandmineSnapshotCallback (int entityNum, int clientNum)
G_LandmineSnapshotCallback.
int GetFieldIndex (const char *fieldname)
GetFieldIndex.
fieldtype_t GetFieldType (const char *fieldname)
GetFieldType.
void G_MapVoteInfoWrite (void)
G_MapVoteInfoWrite.
void G_MapVoteInfoRead (void)
G_MapVoteInfoRead.
void G_RailTrail (vec_t *start, vec_t *end, vec_t *color)
void G_RailBox (vec_t *origin, vec_t *mins, vec_t *maxs, vec_t *color, int index)
G_RailBox.
Variables
g_constructible_stats_t g_constructible_classes [NUM_CONSTRUCTIBLE_CLASSES]
level_locals_t level
gentity_t g_entities []
was explicitly set to MAX_ENTITIES
g_campaignInfo_t g_campaigns []
vmCvar_t g_OmniBotPath
vmCvar_t g_OmniBotEnable
vmCvar_t g_OmniBotFlags
vmCvar_t g_OmniBotPlaying
vmCvar_t g_gametype
vmCvar_t g_log
vmCvar_t g_dedicated
vmCvar_t g_cheats
vmCvar_t g_maxclients
allow this many total, including spectators
vmCvar_t g_maxGameClients
allow this many active
vmCvar_t g_minGameClients
we need at least this many before match actually starts
vmCvar_t g_restarted
vmCvar_t g_timelimit
vmCvar_t g_friendlyFire
vmCvar_t g_password
vmCvar_t sv_privatepassword
vmCvar_t g_gravity
vmCvar_t g_speed
vmCvar_t g_knockback
vmCvar_t g_forcerespawn
vmCvar_t g_inactivity
vmCvar_t g_debugMove
vmCvar_t g_debugAlloc
vmCvar_t g_debugDamage
vmCvar_t g_debugBullets
vmCvar_t g_motd
vmCvar_t g_warmup
vmCvar_t voteFlags
vmCvar_t g_complaintlimit
number of complaints allowed before kick/ban
vmCvar_t g_ipcomplaintlimit
vmCvar_t g_filtercams
vmCvar_t g_maxlives
number of respawns allowed (0==infinite)
vmCvar_t g_maxlivesRespawnPenalty
vmCvar_t g_voiceChatsAllowed
number before spam control
vmCvar_t g_alliedmaxlives
vmCvar_t g_axismaxlives
vmCvar_t g_fastres
Fast medic res'ing.
vmCvar_t g_enforcemaxlives
Temp ban with maxlives between rounds.
vmCvar_t g_needpass
vmCvar_t g_balancedteams
vmCvar_t g_doWarmup
vmCvar_t g_teamForceBalance
vmCvar_t g_banIPs
vmCvar_t g_filterBan
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t g_scriptName
name of script file to run (instead of default for that map)
vmCvar_t g_scriptDebug
what level of detail do we want script printing to go to.
vmCvar_t g_scriptDebugLevel
filter out script debug messages from other entities
vmCvar_t g_scriptDebugTarget
vmCvar_t g_userAim
vmCvar_t g_developer
vmCvar_t g_redlimbotime
vmCvar_t g_bluelimbotime
vmCvar_t g_medicChargeTime
vmCvar_t g_engineerChargeTime
vmCvar_t g_fieldopsChargeTime
vmCvar_t g_soldierChargeTime
vmCvar_t g_covertopsChargeTime
vmCvar_t g_debugConstruct
vmCvar_t g_landminetimeout
vmCvar_t g_movespeed
How fast do SP player and allied bots move?
vmCvar_t g_axismapxp
vmCvar_t g_alliedmapxp
vmCvar_t g_currentCampaign
vmCvar_t g_currentCampaignMap
vmCvar_t g_axiswins
vmCvar_t g_alliedwins
vmCvar_t g_lms_teamForceBalance
vmCvar_t g_lms_roundlimit
vmCvar_t g_lms_matchlimit
vmCvar_t g_lms_currentMatch
vmCvar_t g_lms_lockTeams
vmCvar_t g_lms_followTeamOnly
vmCvar_t g_nextTimeLimit
vmCvar_t g_userTimeLimit
vmCvar_t g_userAlliedRespawnTime
vmCvar_t g_userAxisRespawnTime
vmCvar_t g_currentRound
vmCvar_t g_noTeamSwitching
vmCvar_t g_altStopwatchMode
vmCvar_t g_gamestate
vmCvar_t g_swapteams
vmCvar_t g_antilag
vmCvar_t refereePassword
vmCvar_t shoutcastPassword
vmCvar_t g_spectatorInactivity
vmCvar_t match_latejoin
vmCvar_t match_minplayers
vmCvar_t match_mutespecs
vmCvar_t match_readypercent
vmCvar_t match_timeoutcount
vmCvar_t match_timeoutlength
vmCvar_t match_warmupDamage
vmCvar_t server_motd0
vmCvar_t server_motd1
vmCvar_t server_motd2
vmCvar_t server_motd3
vmCvar_t server_motd4
vmCvar_t server_motd5
vmCvar_t team_maxplayers
vmCvar_t team_nocontrols
vmCvar_t vote_allow_config
vmCvar_t vote_allow_gametype
vmCvar_t vote_allow_kick
vmCvar_t vote_allow_map
vmCvar_t vote_allow_matchreset
vmCvar_t vote_allow_mutespecs
vmCvar_t vote_allow_nextmap
vmCvar_t vote_allow_referee
vmCvar_t vote_allow_shuffleteamsxp
vmCvar_t vote_allow_shuffleteamsxp_norestart
vmCvar_t vote_allow_swapteams
vmCvar_t vote_allow_friendlyfire
vmCvar_t vote_allow_timelimit
vmCvar_t vote_allow_warmupdamage
vmCvar_t vote_allow_antilag
vmCvar_t vote_allow_balancedteams
vmCvar_t vote_allow_muting
vmCvar_t vote_limit
vmCvar_t vote_percent
vmCvar_t vote_allow_surrender
vmCvar_t vote_allow_restartcampaign
vmCvar_t vote_allow_nextcampaign
vmCvar_t vote_allow_poll
vmCvar_t vote_allow_maprestart
vmCvar_t g_debugSkills
vmCvar_t g_heavyWeaponRestriction
vmCvar_t g_autoFireteams
vmCvar_t g_nextmap
vmCvar_t g_nextcampaign
vmCvar_t g_disableComplaints
vmCvar_t g_antiwarp
vmCvar_t g_maxWarp
vmCvar_t lua_modules
vmCvar_t lua_allowedModules
vmCvar_t g_protect
vmCvar_t g_dropHealth
vmCvar_t g_dropAmmo
vmCvar_t g_shove
vmCvar_t g_mapVoteFlags
vmCvar_t g_maxMapsVotedFor
vmCvar_t g_minMapAge
vmCvar_t g_excludedMaps
vmCvar_t g_resetXPMapCount
vmCvar_t g_campaignFile
vmCvar_t g_countryflags
vmCvar_t team_maxAirstrikes
vmCvar_t team_maxArtillery
vmCvar_t team_maxSoldiers
vmCvar_t team_maxMedics
vmCvar_t team_maxEngineers
vmCvar_t team_maxFieldops
vmCvar_t team_maxCovertops
vmCvar_t team_maxMortars
vmCvar_t team_maxFlamers
vmCvar_t team_maxMachineguns
vmCvar_t team_maxRockets
vmCvar_t team_maxRiflegrenades
vmCvar_t team_maxLandmines
vmCvar_t team_riflegrenades
vmCvar_t skill_soldier
vmCvar_t skill_medic
vmCvar_t skill_engineer
vmCvar_t skill_fieldops
vmCvar_t skill_covertops
vmCvar_t skill_battlesense
vmCvar_t skill_lightweapons
vmCvar_t g_misc
vmCvar_t g_intermissionTime
vmCvar_t g_intermissionReadyPercent
vmCvar_t g_mapScriptDirectory
vmCvar_t g_mapConfigs
vmCvar_t g_customConfig
vmCvar_t g_moverScale
vmCvar_t g_debugHitboxes
vmCvar_t g_debugPlayerHitboxes
vmCvar_t g_voting
see VOTEF_* defines
vmCvar_t g_corpses
vmCvar_t g_realHead
vmCvar_t sv_fps
vmCvar_t g_skipCorrection
vmCvar_t g_extendedNames
vmCvar_t g_stickyCharge
GeoIP * gidb
mapEntityData_Team_t mapEntityData [2]
const char * aTeams [TEAM_NUM_TEAMS]
team_info teamInfo [TEAM_NUM_TEAMS]
weapFireTable_t weapFireTable [WP_NUM_WEAPONS]
const char * gameNames []
Detailed Description
Local definitions for game module.
Definition in file g_local.h.
Macro Definition Documentation
#define AA_STATSALL 0x01
Client AutoAction: Dump ALL player stats.
Definition at line 2310 of file g_local.h.
Referenced by G_matchInfoDump().
#define AA_STATSTEAM 0x02
Client AutoAction: Dump TEAM player stats.
Definition at line 2311 of file g_local.h.
Referenced by G_matchInfoDump().
#define ALLIED_CONSTRUCTIBLE 8
Definition at line 2675 of file g_local.h.
Referenced by AutoBuildConstruction(), func_constructiblespawn(), SP_func_constructible(), and TryConstructing().
#define ALLIED_OBJECTIVE 2
Definition at line 2669 of file g_local.h.
Referenced by G_CheckForCursorHints(), G_RealExplodedMissile(), G_UpdateTeamMapData_CommandmapMarker(), ETInterface::GetGoals(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
#define ALLOW_ALLIED_TEAM 2
Definition at line 119 of file g_local.h.
Referenced by G_SpawnGEntityFromSpawnVars().
#define ALLOW_AXIS_TEAM 1
Definition at line 118 of file g_local.h.
Referenced by G_SpawnGEntityFromSpawnVars().
#define ALLOW_DISGUISED_CVOPS 4
Definition at line 120 of file g_local.h.
Referenced by G_AllowTeamsAllowed(), and G_SpawnGEntityFromSpawnVars().
#define AP (x) trap_SendServerCommand(-1, x)
Print to all.
Definition at line 2299 of file g_local.h.
Referenced by _et_MutePlayer(), _et_UnmutePlayer(), CheckVote(), Cmd_CallVote_f(), G_Config_v(), G_delayPrint(), G_Kick_v(), G_lock_cmd(), G_MakeReferee(), G_MakeShoutcaster(), G_MapRestart_v(), G_MatchReset_v(), G_Mute_v(), G_Nextmap_v(), G_pause_cmd(), G_printFull(), G_ready_cmd(), G_readyMatchState(), G_ref_cmd(), G_Referee_v(), G_refPause_cmd(), G_refRemove_cmd(), G_shuffleTeamsXP(), G_Surrender_v(), G_swapTeams(), G_UnMute_v(), G_Unreferee_v(), G_UpdateCvars(), G_voteSetOnOff(), G_voteSetValue(), G_voteSetVoteString(), and G_Warmupfire_v().
#define AXIS_CONSTRUCTIBLE 4
Definition at line 2674 of file g_local.h.
Referenced by AutoBuildConstruction(), func_constructiblespawn(), SP_func_constructible(), Think_SetupObjectiveInfo(), and TryConstructing().
#define AXIS_OBJECTIVE 1
Definition at line 2668 of file g_local.h.
Referenced by G_CheckForCursorHints(), G_RealExplodedMissile(), G_UpdateTeamMapData_CommandmapMarker(), ETInterface::GetGoals(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
#define BODY_CHARACTER (ENT) ENT->s.onFireStart
Definition at line 2201 of file g_local.h.
Referenced by CopyToBodyQue().
#define BODY_CLASS (ENT) ENT->s.modelindex2
Definition at line 2200 of file g_local.h.
Referenced by CopyToBodyQue(), and Do_Activate2_f().
#define BODY_QUEUE_SIZE 8
Definition at line 51 of file g_local.h.
Referenced by CopyToBodyQue(), G_TempTraceIgnorePlayersAndBodies(), G_Trace(), and InitBodyQue().
#define BODY_TEAM (ENT) ENT->s.modelindex
Definition at line 2199 of file g_local.h.
Referenced by _GetEntityTeam(), CopyToBodyQue(), Do_Activate2_f(), G_CheckForCursorHints(), and ETInterface::GetEntityFlags().
#define BODY_TIME 10000
How long do bodies last? (in ms)
Todo:
cvar it ?
Definition at line 65 of file g_local.h.
Referenced by CopyToBodyQue(), Do_Activate2_f(), and G_CheckForCursorHints().
#define BODY_VALUE (ENT) ENT->watertype
Definition at line 2198 of file g_local.h.
Referenced by CopyToBodyQue(), Do_Activate2_f(), G_CheckForCursorHints(), and ETInterface::GetEntityFlags().
#define CF_CONNECT 2
draws country name in connect announcer
Definition at line 1618 of file g_local.h.
Referenced by ClientConnect().
#define CF_ENABLE 1
enables common countryflags functionallity
Definition at line 1617 of file g_local.h.
#define CMD_DEBOUNCE 5000
5s between cmds
Definition at line 2305 of file g_local.h.
Referenced by G_cmdDebounce().
#define CONSTRUCTIBLE_BLOCK_PATHS_WHEN_BUILD 16
Definition at line 2676 of file g_local.h.
Referenced by func_constructible_explode(), and func_constructible_use().
#define CONSTRUCTIBLE_INVULNERABLE 2
Definition at line 2673 of file g_local.h.
Referenced by AutoBuildConstruction(), func_constructiblespawn(), G_CheckForCursorHints(), ETInterface::InterfaceSendMessage(), TryConstructing(), and Weapon_Engineer().
#define CONSTRUCTIBLE_NO_AAS_BLOCKING 32
Definition at line 2677 of file g_local.h.
Referenced by func_constructible_explode().
#define CONSTRUCTIBLE_START_BUILT 1
Definition at line 2672 of file g_local.h.
Referenced by func_constructiblespawn().
#define CP (x) trap_SendServerCommand(ent - g_entities, x)
Print to an ent.
Definition at line 2300 of file g_local.h.
Referenced by ClientUserinfoChanged(), Cmd_CallVote_f(), Cmd_DropObjective_f(), Cmd_Follow_f(), Cmd_Team_f(), Cmd_Vote_f(), G_cmdDebounce(), G_commandHelp(), G_commands_cmd(), G_IntermissionMapVote(), G_IsClassFull(), G_IsWeaponDisabled(), G_lock_cmd(), G_matchInfoDump(), G_noTeamControls(), G_pause_cmd(), G_players_cmd(), G_printFull(), G_printMatchInfo(), G_ready_cmd(), G_ref_cmd(), G_refHelp_cmd(), G_refLogout_cmd(), G_refPrintf(), G_sclogin_cmd(), G_sclogout_cmd(), G_specinvite_cmd(), G_speclock_cmd(), G_statsall_cmd(), G_statsPrint(), G_teamready_cmd(), G_voteHelp(), G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), and SetTeam().
#define CPx (x, y) trap_SendServerCommand(x, y)
Print to id = x.
Definition at line 2301 of file g_local.h.
Referenced by _et_MutePlayer(), _et_UnmutePlayer(), ClientCommand(), ClientDisconnect(), ClientInactivityTimer(), ClientNumberFromString(), Do_Activate2_f(), G_refMute_cmd(), G_refRemove_cmd(), G_VoiceTo(), Svcmd_Burn(), Svcmd_Die(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Pip(), and Svcmd_Unfreeze().
#define DAMAGE_DISTANCEFALLOFF 0x00000040
distance falloff
Definition at line 1529 of file g_local.h.
Referenced by Bullet_Fire_Extended(), and G_Damage().
#define DAMAGE_HALF_KNOCKBACK 0x00000002
do less knockback
Definition at line 1525 of file g_local.h.
Referenced by etpro_RadiusDamage(), G_Damage(), and G_RadiusDamage().
#define DAMAGE_NO_KNOCKBACK 0x00000008
do not affect velocity, just view angles
Definition at line 1526 of file g_local.h.
Referenced by G_Damage(), P_WorldEffects(), and target_laser_think().
#define DAMAGE_NO_PROTECTION 0x00000020
armor, shields, invulnerability, and godmode have no effect
Definition at line 1527 of file g_local.h.
Referenced by G_Damage(), G_KillEnts(), G_SetEntState(), HandleEntsThatBlockConstructible(), hurt_touch(), ETInterface::InterfaceSendMessage(), and target_kill_use().
#define DAMAGE_NO_TEAM_PROTECTION 0x00000010
unused. Armor, shields, invulnerability, and godmode have no effect
Definition at line 1528 of file g_local.h.
#define DAMAGE_RADIUS 0x00000001
damage was indirect
Definition at line 1524 of file g_local.h.
Referenced by etpro_RadiusDamage(), G_Damage(), and G_RadiusDamage().
#define DOOR_CRUSHER 4
Definition at line 2664 of file g_local.h.
Referenced by Blocked_Door().
#define DOOR_ROTATING_FORCE 32
Definition at line 2658 of file g_local.h.
Referenced by IsBinaryMoverBlocked().
#define DOOR_ROTATING_REVERSE 16
Definition at line 2657 of file g_local.h.
Referenced by SP_func_door_rotating().
#define DOOR_ROTATING_STAYOPEN 64
Definition at line 2659 of file g_local.h.
Referenced by InitMoverRotate().
#define DOOR_ROTATING_TOGGLE 2
Definition at line 2654 of file g_local.h.
Referenced by SP_func_door_rotating().
#define DOOR_ROTATING_X_AXIS 4
Definition at line 2655 of file g_local.h.
Referenced by SP_func_door_rotating().
#define DOOR_ROTATING_Y_AXIS 8
Definition at line 2656 of file g_local.h.
Referenced by SP_func_door_rotating().
#define DOOR_START_OPEN 1
Definition at line 2662 of file g_local.h.
Referenced by SP_func_door().
#define DOOR_TOGGLE 2
Definition at line 2663 of file g_local.h.
Referenced by SP_func_door().
#define DOOR_TOUCH 8
Definition at line 2665 of file g_local.h.
Referenced by SP_func_button().
#define EOM_MATCHINFO 0x02
Dump of match stats at end of match.
Definition at line 2308 of file g_local.h.
Referenced by CheckIntermissionExit(), and G_matchInfoDump().
#define EOM_WEAPONSTATS 0x01
Dump of player weapon stats at end of match.
Definition at line 2307 of file g_local.h.
Referenced by CheckIntermissionExit(), and G_matchInfoDump().
#define EVENT_VALID_MSEC 300
Definition at line 53 of file g_local.h.
Referenced by G_RunEntity().
#define EXPLOSIVE_LOWGRAV 8
Definition at line 2683 of file g_local.h.
Referenced by SP_func_explosive().
#define EXPLOSIVE_START_INVIS 1
Definition at line 2680 of file g_local.h.
Referenced by SP_func_explosive().
#define EXPLOSIVE_TANK 32
Definition at line 2685 of file g_local.h.
Referenced by _GetEntityClass(), G_CheckForCursorHints(), and ETInterface::GetEntityCategory().
#define EXPLOSIVE_TOUCHABLE 2
Definition at line 2681 of file g_local.h.
Referenced by SP_func_explosive().
#define EXPLOSIVE_USESHADER 4
Definition at line 2682 of file g_local.h.
Referenced by SP_func_explosive().
#define FIELDOPS_SPECIAL_PICKUP_MOD 3
Number of times (minus one for modulo) field ops must drop ammo before scoring a point.
Definition at line 881 of file g_local.h.
#define FL_DROPPED_ITEM 0x00001000
Definition at line 72 of file g_local.h.
Referenced by ETInterface::InterfaceSendMessage(), LaunchItem(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), and Touch_Item().
#define FL_GODMODE 0x00000010
Definition at line 68 of file g_local.h.
Referenced by Cmd_God_f(), Cmd_Kill_f(), Cmd_UnIgnore_f(), G_Damage(), P_DamageFeedback(), and SetTeam().
#define FL_KICKACTIVATE 0x00040000
ent has been activated by a kick (doors use this too for ex.)
Definition at line 79 of file g_local.h.
Referenced by G_UseTargets(), MatchTeam(), MatchTeamReverseAngleOnSlaves(), Reached_BinaryMover(), SetMoverState(), and Use_BinaryMover().
#define FL_NO_BOTS 0x00002000
spawn point not for bot use
Definition at line 73 of file g_local.h.
Referenced by SP_info_player_deathmatch().
#define FL_NO_HUMANS 0x00004000
spawn point just for bots
Definition at line 74 of file g_local.h.
Referenced by SP_info_player_deathmatch().
#define FL_NO_KNOCKBACK 0x00000800
Definition at line 71 of file g_local.h.
Referenced by G_Damage().
#define FL_NODRAW 0x01000000
Definition at line 83 of file g_local.h.
Referenced by FinishSpawningItem(), G_RunEntity(), RespawnItem(), and Touch_Item().
#define FL_NOFATIGUE 0x00010000
cheat flag no fatigue
Definition at line 76 of file g_local.h.
Referenced by ClientThink_real(), Cmd_Nofatigue_f(), and SpectatorThink().
#define FL_NOSTAMINA 0x00008000
cheat flag no stamina
Definition at line 75 of file g_local.h.
Referenced by ClientThink_real(), Cmd_Nostamina_f(), and SpectatorThink().
#define FL_NOTARGET 0x00000020
Definition at line 69 of file g_local.h.
Referenced by Cmd_Notarget_f().
#define FL_SOFTACTIVATE 0x00000040
ent has been activated while 'walking' (doors use this too for ex.)
Definition at line 80 of file g_local.h.
Referenced by Do_Activate_f(), G_TryDoor(), G_UseTargets(), MatchTeam(), MatchTeamReverseAngleOnSlaves(), Reached_BinaryMover(), ReturnToPos1Rotate(), SetMoverState(), Use_BinaryMover(), and Use_TrinaryMover().
#define FL_TEAMSLAVE 0x00000400
not the first on the team
Definition at line 70 of file g_local.h.
Referenced by FinishSpawningItem(), finishSpawningKeyedMover(), flippy_table_use(), G_FindTeams(), G_RunMover(), SP_func_door(), SP_func_door_rotating(), SP_func_rotating(), SP_func_secret(), SP_func_static(), Use_BinaryMover(), Use_Func_Rotate(), and Use_TrinaryMover().
#define FL_TOGGLE 0x00020000
ent is toggling (doors use this for ex.)
Definition at line 78 of file g_local.h.
Referenced by Reached_BinaryMover(), SP_func_door(), SP_func_door_rotating(), and Use_BinaryMover().
#define FOFS (x) ((size_t)&(((gentity_t *)0)->x))
Definition at line 1828 of file g_local.h.
Referenced by AutoBuildConstruction(), ETInterface::FindEntityInSphere(), FindIntermissionPoint(), findNonAIBrushTargeter(), func_constructiblespawn(), G_ScriptAction_Accum(), G_ScriptAction_Cvar(), G_ScriptAction_GlobalAccum(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetMainObjective(), G_ScriptAction_TagConnect(), G_ScriptAction_Trigger(), GetMG42s(), HandleEntsThatBlockConstructible(), SelectNearestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomTeamSpawnPoint(), smoke_init(), SP_props_snowGenerator(), target_script_trigger_use(), TryConstructing(), Use_Props_Shard_Generator(), and Use_Target_Lock().
#define G_INVALID -1
Definition at line 2296 of file g_local.h.
Referenced by G_Campaign_v(), G_Config_v(), G_Gametype_v(), G_Kick_v(), G_Map_v(), G_MapRestart_v(), G_MatchReset_v(), G_Mute_v(), G_NextCampaign_v(), G_Nextmap_v(), G_Poll_v(), G_Referee_v(), G_RestartCampaign_v(), G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), G_StartMatch_v(), G_Surrender_v(), G_SwapTeams_v(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_voteProcessOnOff(), and G_Warmupfire_v().
#define G_MAX_SCRIPT_ACCUM_BUFFERS 10
Definition at line 207 of file g_local.h.
Referenced by G_ScriptAction_Accum(), G_ScriptAction_FollowSpline(), and G_ScriptAction_PrintAccum().
#define G_MAX_SCRIPT_STACK_ITEMS 196
value set high for the tank
Definition at line 152 of file g_local.h.
Referenced by G_Script_ScriptParse().
#define G_MISC_CROSSHAIR_DYNAMITE BIT(3)
Definition at line 2744 of file g_local.h.
Referenced by Weapon_Engineer().
#define G_MISC_CROSSHAIR_LANDMINE BIT(4)
Definition at line 2745 of file g_local.h.
Referenced by Weapon_Engineer().
#define G_MISC_SHOVE_Z BIT(0)
Definition at line 2741 of file g_local.h.
Referenced by G_PushPlayer().
#define G_NOTFOUND -2
Definition at line 2297 of file g_local.h.
Referenced by Cmd_CallVote_f(), G_Mute_v(), G_UnMute_v(), and G_voteCmdCheck().
#define G_OK 0
Definition at line 2295 of file g_local.h.
Referenced by Cmd_CallVote_f(), G_AntiLag_v(), G_BalancedTeams_v(), G_Campaign_v(), G_Config_v(), G_FriendlyFire_v(), G_Gametype_v(), G_Kick_v(), G_Map_v(), G_MapRestart_v(), G_MatchReset_v(), G_Mute_v(), G_Mutespecs_v(), G_NextCampaign_v(), G_Nextmap_v(), G_Poll_v(), G_Referee_v(), G_RestartCampaign_v(), G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), G_StartMatch_v(), G_Surrender_v(), G_SwapTeams_v(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_voteCmdCheck(), G_voteProcessOnOff(), and G_Warmupfire_v().
#define G_PROTECT_LOCALHOST_REF 1
Definition at line 2733 of file g_local.h.
Referenced by ClientUserinfoChanged().
#define G_PROTECT_MAX_LIVES_BAN_GUID 2
Definition at line 2734 of file g_local.h.
Referenced by ClientConnect().
#define G_SpawnFloat (key, def, out) G_SpawnFloatExt(key, def, out, __FILE__, __LINE__)
Definition at line 1348 of file g_local.h.
Referenced by G_SpawnItem(), InitMoverRotate(), InitProp(), SP_corona(), SP_func_bobbing(), SP_func_button(), SP_func_constructible(), SP_func_debris(), SP_func_door(), SP_func_explosive(), SP_func_pendulum(), SP_func_plat(), SP_func_secret(), SP_func_timer(), SP_misc_gamemodel(), SP_misc_portal_camera(), SP_props_decor_Scale(), SP_props_decoration(), SP_props_statue(), SP_script_mover(), SP_target_delay(), SP_target_explosion(), SP_target_fog(), SP_target_speaker(), and SP_trigger_multiple().
#define G_SpawnInt (key, def, out) G_SpawnIntExt(key, def, out, __FILE__, __LINE__)
Definition at line 1349 of file g_local.h.
Referenced by G_ModifyTOI(), G_SpawnGEntityFromSpawnVars(), G_SpawnItem(), SP_dlight(), SP_func_bobbing(), SP_func_constructible(), SP_func_door(), SP_func_door_rotating(), SP_func_explosive(), SP_func_pendulum(), SP_func_plat(), SP_func_secret(), SP_func_static(), SP_info_limbo_camera(), SP_info_player_deathmatch(), SP_misc_beam(), SP_misc_gamemodel(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_footlocker(), SP_script_mover(), SP_skyportal(), SP_target_effect(), SP_target_explosion(), SP_target_fog(), SP_target_speaker(), SP_trigger_multiple(), and SP_trigger_objective_info().
#define G_SpawnString (key, def, out) G_SpawnStringExt(key, def, out, __FILE__, __LINE__)
Definition at line 1347 of file g_local.h.
Referenced by G_ModifyTOI(), G_SpawnGEntityFromSpawnVars(), G_SpawnItem(), InitExplosive(), InitProp(), SP_alarm_box(), SP_dlight(), SP_func_explosive(), SP_func_invisible_user(), SP_info_train_spline_main(), SP_mg42(), SP_misc_beam(), SP_misc_constructiblemarker(), SP_props_decoration(), SP_props_flamethrower(), SP_props_footlocker(), SP_props_statue(), SP_script_mover(), SP_skyportal(), SP_target_effect(), SP_target_explosion(), SP_target_relay(), SP_target_rumble(), SP_target_smoke(), SP_target_speaker(), SP_team_WOLF_checkpoint(), SP_team_WOLF_objective(), SP_trigger_ammo(), SP_trigger_flagonly(), SP_trigger_flagonly_multiple(), SP_trigger_heal(), SP_trigger_hurt(), SP_trigger_objective_info(), and SP_worldspawn().
#define G_SpawnVector (key, def, out) G_SpawnVectorExt(key, def, out, __FILE__, __LINE__)
Definition at line 1350 of file g_local.h.
Referenced by InitMoverRotate(), InitProp(), SP_misc_beam(), SP_misc_gamemodel(), SP_props_decor_Scale(), SP_props_decoration(), SP_props_statue(), SP_script_mover(), and SP_skyportal().
#define G_SpawnVector2D (key, def, out) G_SpawnVector2DExt(key, def, out, __FILE__, __LINE__)
Definition at line 1351 of file g_local.h.
Referenced by SP_worldspawn().
#define GAMEVERSION "legacy"
The "gameversion" client command will print this plus compile date.
Definition at line 49 of file g_local.h.
Referenced by etpro_ScriptAction_SetValues(), G_ClearMapXP(), G_GetMapXP(), G_InitGame(), G_Lua_CreateEntity(), G_ScriptAction_Create(), G_StoreMapXP(), and trap_SendServerCommand().
#define GetWeaponFireTableData (weapIndex) ((weapFireTable_t *)(&weapFireTable[weapIndex]))
Definition at line 2792 of file g_local.h.
Referenced by G_PreFilledMissileEntity(), G_RunMissile(), landmine_setup(), Weapon_FlamethrowerFire(), weapon_gpg40_fire(), weapon_grenadelauncher_fire(), and weapon_mortar_fire().
#define HELP_COLUMNS 4
Definition at line 2303 of file g_local.h.
Referenced by G_commands_cmd(), and G_voteHelp().
#define LAG_DECAY 1.02f
Definition at line 704 of file g_local.h.
Referenced by DoClientThinks().
#define LAG_MAX_COMMANDS 512
Definition at line 700 of file g_local.h.
Referenced by DoClientThinks(), and etpro_AddUsercmd().
#define LAG_MAX_DELTA 75
Definition at line 701 of file g_local.h.
Referenced by DoClientThinks().
#define LAG_MAX_DROP_THRESHOLD 800
Definition at line 702 of file g_local.h.
Referenced by DoClientThinks().
#define LAG_MIN_DROP_THRESHOLD (LAG_MAX_DROP_THRESHOLD - 200)
Definition at line 703 of file g_local.h.
Referenced by DoClientThinks().
#define MAPVOTE_ALT_INTERMISSION 2
unused
Definition at line 2689 of file g_local.h.
#define MAPVOTE_MULTI_VOTE 4
Definition at line 2690 of file g_local.h.
Referenced by ClientDisconnect(), and G_IntermissionMapList().
#define MAPVOTE_NEXTMAP_VOTEMAP 16
Definition at line 2692 of file g_local.h.
Referenced by G_Nextmap_v().
#define MAPVOTE_NO_RANDOMIZE 8
unused
Definition at line 2691 of file g_local.h.
#define MAPVOTE_TIE_LEASTPLAYED 1
Definition at line 2688 of file g_local.h.
Referenced by ExitLevel().
#define MAX_CLIENT_MARKERS 17
Definition at line 879 of file g_local.h.
Referenced by G_AdjustSingleClientPosition(), G_ResetMarkers(), and G_StoreClientPosition().
#define MAX_COMMANDER_TEAM_SOUNDS 16
Definition at line 235 of file g_local.h.
Referenced by G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_RemoveTeamVoiceAnnounce(), and SetTeam().
#define MAX_COMPLAINTIPS 5
Definition at line 733 of file g_local.h.
Referenced by G_FindFreeComplainIP().
#define MAX_CONSTRUCT_STAGES 3
Definition at line 116 of file g_local.h.
Referenced by func_constructiblespawn().
#define MAX_DEBRISCHUNKS 256
Definition at line 898 of file g_local.h.
Referenced by G_AllocDebrisChunk(), and G_ScriptAction_SpawnRubble().
#define MAX_LIMBO_CAMS 32
Definition at line 1054 of file g_local.h.
Referenced by info_limbo_camera_setup().
#define MAX_NETNAME 36
Definition at line 233 of file g_local.h.
Referenced by ClientConnect(), ClientUserinfoChanged(), G_players_cmd(), and ETInterface::RemoveBot().
#define MAX_SCRIPT_ACCUM_BUFFERS 10
increased from 8 to 10 for compatability with maps that relied on it before Project: Bug Fix #055
Definition at line 1060 of file g_local.h.
Referenced by G_ScriptAction_FollowSpline(), G_ScriptAction_GlobalAccum(), and G_ScriptAction_PrintGlobalAccum().
#define MAX_SPAWN_VARS 64
Definition at line 1057 of file g_local.h.
#define MAX_SPAWN_VARS_CHARS 2048
Definition at line 1058 of file g_local.h.
#define MEDIC_SPECIAL_PICKUP_MOD 4
Same thing for medic.
Definition at line 882 of file g_local.h.
#define MG42_MULTIPLAYER_HEALTH 350
Definition at line 55 of file g_local.h.
Referenced by G_ScriptAction_RepairMG42(), ETInterface::InterfaceSendMessage(), SP_mg42(), and Weapon_Engineer().
#define MISSILE_PRESTEP_TIME 50
Definition at line 57 of file g_local.h.
Referenced by fire_flamebarrel().
#define MOVER_ALLIED 32
Definition at line 2634 of file g_local.h.
#define MOVER_AXIS 64
Definition at line 2635 of file g_local.h.
#define MOVER_COMPASS 16
Definition at line 2633 of file g_local.h.
#define MOVER_EXPLOSIVEDAMAGEONLY 4
Definition at line 2631 of file g_local.h.
#define MOVER_MOUNTEDGUN 128
Definition at line 2636 of file g_local.h.
#define MOVER_RESURECTABLE 8
Definition at line 2632 of file g_local.h.
#define MOVER_SOLID 2
Definition at line 2630 of file g_local.h.
#define MOVER_TRIGGERSPAWN 1
Definition at line 2629 of file g_local.h.
#define MULTI_TRIGGER_ALLIED_ONLY 2
Definition at line 2640 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_AXIS_ONLY 1
Definition at line 2639 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_BOTONLY 8
Definition at line 2642 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_COVERTOPSONLY 256
Definition at line 2647 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_DISGUISEDSONLY 512
legacy only
Definition at line 2648 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_ENGINEERONLY 128
Definition at line 2646 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_FIELDOPSONLY 32
Definition at line 2644 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_MEDICONLY 64
Definition at line 2645 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_NOBOT 4
Definition at line 2641 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_OBJECTIVEONLY 1024
legacy only
Definition at line 2649 of file g_local.h.
Referenced by Touch_Multi().
#define MULTI_TRIGGER_SOLDIERONLY 16
Definition at line 2643 of file g_local.h.
Referenced by Touch_Multi().
#define NO_CHECKPOINT 4
unused
Definition at line 113 of file g_local.h.
#define NO_GT_WOLF 1
Definition at line 111 of file g_local.h.
Referenced by G_ShutdownGame(), and G_UpdateCvars().
#define NO_LMS 8
Definition at line 114 of file g_local.h.
Referenced by G_ShutdownGame(), and G_UpdateCvars().
#define NO_STOPWATCH 2
Definition at line 112 of file g_local.h.
Referenced by G_ShutdownGame(), and G_UpdateCvars().
#define NUM_CONSTRUCTIBLE_CLASSES 3
Definition at line 227 of file g_local.h.
Referenced by G_ScriptAction_ConstructibleClass(), SP_func_constructible(), and SP_func_explosive().
#define OBJECTIVE_DESTROYED 4
Definition at line 2670 of file g_local.h.
Referenced by Weapon_Engineer().
#define OBJECTIVE_INFO_ALLIED_OBJECTIVE 2
Definition at line 2620 of file g_local.h.
#define OBJECTIVE_INFO_AXIS_OBJECTIVE 1
Definition at line 2619 of file g_local.h.
#define OBJECTIVE_INFO_IS_COMMANDPOST 64
128 is disabled
(see cg_commandmap)
Definition at line 2625 of file g_local.h.
#define OBJECTIVE_INFO_IS_HEALTHAMMOCABINET 32
(see cg_commandmap)
Definition at line 2624 of file g_local.h.
#define OBJECTIVE_INFO_IS_OBJECTIVE 16
Definition at line 2623 of file g_local.h.
#define OBJECTIVE_INFO_MESSAGE_OVERRIDE 4
Definition at line 2621 of file g_local.h.
#define OBJECTIVE_INFO_TANK 8
Definition at line 2622 of file g_local.h.
Referenced by func_constructible_underconstructionthink().
#define PAUSE_NONE 0x00
Match is NOT paused.
Definition at line 2291 of file g_local.h.
Referenced by ClientEndFrame(), ClientThink_real(), Cmd_Kill_f(), G_delayPrint(), G_pause_cmd(), G_refPause_cmd(), G_RunEntity(), G_RunFrame(), G_RunMover(), G_RunThink(), and SpectatorThink().
#define PAUSE_UNPAUSING 0x01
Pause is about to expire.
Definition at line 2292 of file g_local.h.
Referenced by G_delayPrint(), G_pause_cmd(), and G_refPause_cmd().
#define PICKUP_ACTIVATE 0
pickup items only when using "+activate"
Definition at line 695 of file g_local.h.
Referenced by ammo_touch(), ClientUserinfoChanged(), Do_Activate_f(), heal_touch(), and Touch_Item_Auto().
#define PICKUP_FORCE 2
pickup the next item when touched (and reset to PICKUP_ACTIVATE when done)
Definition at line 697 of file g_local.h.
Referenced by ammo_touch(), Do_Activate_f(), heal_touch(), and Touch_Item_Auto().
#define PICKUP_TOUCH 1
pickup items when touched
Definition at line 696 of file g_local.h.
Referenced by ClientUserinfoChanged().
#define SCFL_ANIMATING 0x2
Definition at line 188 of file g_local.h.
Referenced by G_Script_ScriptRun(), and G_ScriptAction_PlayAnim().
#define SCFL_FIRST_CALL 0x4
Definition at line 189 of file g_local.h.
Referenced by G_Script_ScriptChange(), and G_Script_ScriptRun().
#define SCFL_GOING_TO_MARKER 0x1
Definition at line 187 of file g_local.h.
Referenced by G_Script_ScriptRun(), G_ScriptAction_AbortMove(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GotoMarker(), and G_ScriptAction_Halt().
#define SERVER_FRAMETIME (1000 / trap_Cvar_VariableIntegerValue("sv_fps"))
(1000/20) default
Definition at line 2753 of file g_local.h.
#define SERVER_FRAMETIME_DELTA (2 * SERVER_FRAMETIME)
msec
Definition at line 2757 of file g_local.h.
#define SERVER_FRAMETIME_DELTA_F (2.f * SERVER_FRAMETIME_F)
msec
Definition at line 2758 of file g_local.h.
#define SERVER_FRAMETIME_F (1000.f / trap_Cvar_VariableIntegerValue("sv_fps"))
Definition at line 2754 of file g_local.h.
#define STICKYCHARGE_ANYDEATH 2
Definition at line 2094 of file g_local.h.
Referenced by ClientSpawn().
#define STICKYCHARGE_NONE 0
Definition at line 2092 of file g_local.h.
#define STICKYCHARGE_SELFKILL 1
Definition at line 2093 of file g_local.h.
Referenced by ClientSpawn().
#define TARGET_PUSH_BOUNCEPAD 1
Definition at line 2651 of file g_local.h.
Referenced by SP_target_push().
#define TKFL_AIRSTRIKE 0x00000002
Definition at line 86 of file g_local.h.
Referenced by player_die().
#define TKFL_MINES 0x00000001
Definition at line 85 of file g_local.h.
Referenced by player_die().
#define TKFL_MORTAR 0x00000004
Definition at line 87 of file g_local.h.
Referenced by player_die().
#define VOTE_MAXSTRING 256
Same value as MAX_STRING_TOKENS.
Definition at line 1059 of file g_local.h.
Referenced by Cmd_CallVote_f(), G_Campaign_v(), G_Config_v(), G_Gametype_v(), G_Kick_v(), G_Map_v(), G_Mute_v(), G_Poll_v(), G_Referee_v(), G_Surrender_v(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_voteCmdCheck(), G_voteProcessOnOff(), and G_Warmupfire_v().
#define VOTEF_DISP_CALLER 4
append "(called by name)" in vote string
Definition at line 2750 of file g_local.h.
Referenced by Cmd_CallVote_f().
#define VOTEF_NO_POPULIST_PENALTY 2
successful votes do not count against vote_limit
Definition at line 2749 of file g_local.h.
Referenced by CheckVote().
#define VOTEF_USE_TOTAL_VOTERS 1
use total voters instead of total players to decide if a vote passes
Definition at line 2748 of file g_local.h.
Referenced by CheckVote().
Typedef Documentation
cfgCvar_t
commanderTeamChat_t
config_t
consoleCommandTable_t
debrisChunk_t
Debris test.
g_constructible_stats_t
gclient_t
This structure is cleared on each ClientSpawn(), except for 'client->pers' and 'client->sess'.
Definition at line 125 of file g_local.h.
gentity_t
Definition at line 124 of file g_local.h.
GeoIP
ipFilter_t
level_locals_t
limbo_cam_t
mapEntityData_t
mapEntityData_Team_t
typedef struct spawnPointState_s spawnPointState_t
voteInfo_t
typedef struct weapFireTable_t weapFireTable_t
Enumeration Type Documentation
enum clientConnected_t
Enumerator
CON_DISCONNECTED
CON_CONNECTING
CON_CONNECTED
Definition at line 558 of file g_local.h.
enum combatstate_t
Enumerator
COMBATSTATE_COLD
COMBATSTATE_DAMAGEDEALT
COMBATSTATE_DAMAGERECEIVED
COMBATSTATE_KILLEDPLAYER
Definition at line 580 of file g_local.h.
enum enum_t_dp
"Delayed Print" ent enumerations
Enumerator
DP_PAUSEINFO
Print current pause info.
DP_UNPAUSING
Print unpause countdown + unpause.
DP_CONNECTINFO
Display info on connect.
DP_MVSPAWN
Set up MV views for clients who need them.
Definition at line 2317 of file g_local.h.
enum fieldtype_t
Enumerator
F_INT
F_FLOAT
F_LSTRING
string on disk, pointer in memory, TAG_LEVEL
F_GSTRING
string on disk, pointer in memory, TAG_GAME
F_VECTOR
F_ANGLEHACK
F_ENTITY
index on disk, pointer in memory
F_ITEM
index on disk, pointer in memory
F_CLIENT
index on disk, pointer in memory
F_IGNORE
Definition at line 2701 of file g_local.h.
enum moverState_t
Movers are things like doors, plats, buttons, etc.
Enumerator
MOVER_POS1
MOVER_POS2
MOVER_POS3
MOVER_1TO2
MOVER_2TO1
MOVER_2TO3
MOVER_3TO2
MOVER_POS1ROTATE
MOVER_POS2ROTATE
MOVER_1TO2ROTATE
MOVER_2TO1ROTATE
Definition at line 93 of file g_local.h.
enum playerTeamStateState_t
Enumerator
TEAM_BEGIN
Beginning a team game, spawn at base.
TEAM_ACTIVE
Now actively playing.
Definition at line 592 of file g_local.h.
enum spectatorState_t
Enumerator
SPECTATOR_NOT
SPECTATOR_FREE
SPECTATOR_FOLLOW
Definition at line 569 of file g_local.h.
Function Documentation
void aagun_fire (gentity_t * other)
aagun_fire
Parameters
[in,out] other
Definition at line 1325 of file g_misc.c.
Referenced by ClientEvents().
void aagun_stopusing (gentity_t * self)
aagun_stopusing
Parameters
[in,out] self
Definition at line 1305 of file g_misc.c.
Referenced by G_SetEntState().
qboolean AccuracyHit (gentity_t * target, gentity_t * attacker)
AccuracyHit.
Parameters
[in] target
[in] attacker
Returns
Definition at line 3840 of file g_weapon.c.
Referenced by Bullet_Fire_Extended(), etpro_RadiusDamage(), and G_RadiusDamage().
int Add_Ammo (gentity_t * ent, weapon_t weapon, int count, qboolean fillClip)
Add ammo.
Parameters
[in,out] ent
[in] weapon
[in] count
[in] fillClip
Returns
whether any ammo was added
Definition at line 130 of file g_items.c.
Referenced by Cmd_Give_f(), Pickup_Weapon(), and Weapon_Engineer().
void AddIPBan (const char * str)
AddIPBan.
Parameters
[in] str
Definition at line 342 of file g_svcmds.c.
Referenced by G_PlayerBan(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
void AddKillScore (gentity_t * ent, int score)
Adds score to both the client and his team, only used for LMS.
Parameters
[in,out] ent
[in] score
Definition at line 54 of file g_combat.c.
Referenced by player_die().
qboolean AddMagicAmmo (gentity_t * receiver, int numOfClips)
Add the specified number of clips of magic ammo.
Parameters
[in] receiver
[in] numOfClips
Returns
whether any ammo was actually added
Definition at line 173 of file g_items.c.
Referenced by ammo_touch(), G_IsAllowedAmmo(), and Pickup_Weapon().
void AddMaxLivesBan (const char * str)
AddMaxLivesBan.
Parameters
[in] str
Definition at line 351 of file g_svcmds.c.
Referenced by ClientBegin().
void AddMaxLivesGUID (const char * str)
>ith g_enforcemaxlives enabled, this adds a client GUID to a list that prevents them from quitting and reconnecting
Parameters
[in] str
Definition at line 362 of file g_svcmds.c.
Referenced by ClientBegin().
void AddRemap (const char * oldShader, const char * newShader, float timeOffset)
AddRemap.
Parameters
[in] oldShader
[in] newShader
[in] timeOffset
Definition at line 60 of file g_utils.c.
Referenced by _et_G_ShaderRemap(), and G_ScriptAction_ShaderRemap().
float AngleDifference (float ang1, float ang2)
AngleDifference.
Parameters
[in] ang1
[in] ang2
Returns
Definition at line 2671 of file g_misc.c.
Referenced by clamp_hweapontofirearc(), G_ScriptAction_FaceAngles(), and G_ScriptAction_GotoMarker().
void BeginIntermission (void)
BeginIntermission.
Definition at line 3311 of file g_main.c.
Referenced by CheckExitRules().
void body_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t meansOfDeath)
body_die
Parameters
[in,out] self
inflictor - unused
attacker - unused
damage - unused
meansOfDeath - unused
Definition at line 239 of file g_combat.c.
Referenced by CopyToBodyQue(), and player_die().
const char* BuildShaderStateConfig (void)
BuildShaderStateConfig.
Returns
Definition at line 111 of file g_utils.c.
Referenced by _et_G_ShaderRemapFlush(), and G_ScriptAction_ShaderRemapFlush().
void CalcMuzzlePoint (gentity_t * ent, int weapon, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
Set muzzle location relative to pivoting eye.
Parameters
[in] ent
[in] weapon
forward - unused
[in] right
[in] up
[out] muzzlePoint
Definition at line 3889 of file g_weapon.c.
Referenced by CalcMuzzlePoints(), and Weapon_Knife().
void CalcMuzzlePointForActivate (gentity_t * ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
For activate.
Parameters
[in] ent
forward - unused
right - unused
up - unused
[out] muzzlePoint
Definition at line 3920 of file g_weapon.c.
Referenced by CalcMuzzlePoints(), Cmd_Activate2_f(), and Weapon_Syringe().
void CalcMuzzlePoints (gentity_t * ent, int weapon)
CalcMuzzlePoints.
Parameters
[in] ent
[in] weapon
Definition at line 3936 of file g_weapon.c.
Referenced by FireWeapon().
void CalculateRanks (void)
Recalculates the score ranks of all players. This will be called on every client connect, begin, disconnect, death, and team change.
Definition at line 2975 of file g_main.c.
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), G_AddKillSkillPoints(), G_AddKillSkillPointsForDestruction(), G_AddSkillPoints(), G_LoseKillSkillPoints(), G_LoseSkillPoints(), player_die(), and Weapon_Syringe().
qboolean CanDamage (gentity_t * targ, vec3_t origin)
Used for explosions and melee attacks.
Parameters
[in] targ
[in] origin
Returns
qtrue if the inflictor can directly damage the target.
Definition at line 1818 of file g_combat.c.
Referenced by EntsThatRadiusCanDamage(), etpro_RadiusDamage(), and G_RadiusDamage().
void CheckTeamStatus (void)
CheckTeamStatus.
Definition at line 776 of file g_team.c.
Referenced by G_RunFrame().
void ClearMaxLivesBans (void)
Clears out the entire list maxlives enforcement banlist.
Definition at line 470 of file g_svcmds.c.
Referenced by G_InitGame().
void ClientBegin (int clientNum)
Called when a client has finished connecting, and is ready to be placed into the level. This will happen every level load, and on transition between teams, but doesn't happen on respawns.
Parameters
[in] clientNum
Definition at line 2357 of file g_client.c.
Referenced by G_shuffleTeamsXP(), G_swapTeams(), SetTeam(), SpectatorClientEndFrame(), and vmMain().
void ClientCommand (int clientNum)
ClientCommand.
Parameters
[in] clientNum
Definition at line 4783 of file g_cmds.c.
Referenced by vmMain().
char* ClientConnect (int clientNum, qboolean firstTime, qboolean isBot)
Called when a player begins connecting to the server. Called again for every map change or tournement restart.
The session information will be valid after exit.
Return NULL if the client should be allowed, otherwise return a string with the reason for denial.
Otherwise, the client will be sent the current gamestate and will eventually get to ClientBegin.
Parameters
[in] clientNum
[in] firstTime will be qtrue the very first time a client connects to the server machine, but qfalse on map changes and tournement restarts.
[in] isBot
Returns
NULL if the client should be allowed, otherwise return a string with the reason for denial.
Definition at line 2007 of file g_client.c.
Referenced by ETInterface::AddBot(), and vmMain().
void ClientDisconnect (int clientNum)
Called when a player drops from the server. Will not be called between levels.
This should NOT be called directly by any game logic, call trap_DropClient(), which will call this and do server system housekeeping.
Parameters
[in] clientNum
Todo:
: find a new sound?
Definition at line 3127 of file g_client.c.
Referenced by ClientConnect(), and vmMain().
void ClientEndFrame (gentity_t * ent)
Called at the end of each server frame for each connected client A fast client will have multiple ClientThink for each ClientEndFrame, while a slow client may have multiple ClientEndFrame between ClientThink.
Parameters
[in,out] ent Entity
Definition at line 2087 of file g_active.c.
Referenced by ClientSpawn(), and G_RunFrame().
float ClientHitboxMaxZ (gentity_t * hitEnt)
ClientHitboxMaxZ.
Parameters
[in] hitEnt
Returns
the proper value to use for the entity's r.maxs[2] when running a trace.
Definition at line 3333 of file g_client.c.
Referenced by Bullet_Fire_Extended(), ClientEndFrame(), ClientThink_real(), G_DrawEntBBox(), G_HistoricalTrace(), and G_Trace().
int ClientNumberFromString (gentity_t * to, char * s)
ClientNumberFromString.
Parameters
[in] to
[in] s
Returns
A player number for either a number or name string, -1 if invalid
Definition at line 556 of file g_cmds.c.
Referenced by G_Kick_v(), G_Mute_v(), G_Referee_v(), G_refMakeShoutcaster_cmd(), G_refMute_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_refRemoveShoutcaster_cmd(), G_specinvite_cmd(), G_statsPrint(), G_UnMute_v(), and G_Unreferee_v().
int ClientNumbersFromString (char * s, int * plist)
Sets plist to an array of integers that represent client numbers that have names that are a partial match for s. List is terminated by a -1.
Parameters
[in] s
[out] plist
Returns
Number of matching clientids.
Definition at line 98 of file g_cmds.c.
Referenced by _et_ClientNumberFromString(), Cmd_Follow_f(), G_makesc_cmd(), G_PlaySound_Cmd(), G_removesc_cmd(), Svcmd_Burn(), Svcmd_Die(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Pip(), and Svcmd_Unfreeze().
void ClientSpawn (gentity_t * ent, qboolean revived, qboolean teamChange, qboolean restoreHealth)
Called every time a client is placed fresh in the world: after the first ClientBegin, and after each respawn Initializes all non-persistant parts of playerState.
Parameters
[in,out] ent
[in] revived
[in] teamChange
[in] restoreHealth
Definition at line 2708 of file g_client.c.
Referenced by ClientBegin(), Cmd_UnIgnore_f(), respawn(), and ReviveEntity().
void ClientThink (int clientNum)
A new command has arrived from the client.
Parameters
[in] clientNum Client Number from 0 to MAX_CLIENTS
Definition at line 1644 of file g_active.c.
Referenced by ClientSpawn(), and vmMain().
void ClientThink_cmd (gentity_t * ent, usercmd_t * cmd, qboolean skipServerTime)
etpro antiwarp
Author
zinx
Parameters
[in,out] ent Entity
[in] cmd User Command
Definition at line 1633 of file g_active.c.
Referenced by ClientThink(), and DoClientThinks().
void ClientUserinfoChanged (int clientNum)
Called from ClientConnect when the player first connects and directly by the server system when the player updates a userinfo variable.
The game can override any of the settings and call trap_SetUserinfo if desired.
Parameters
[in] clientNum
Todo:
: move other userinfo flag settings in here
Todo:
: Gordon: wont this break if medals > 9 arnout?
Definition at line 1669 of file g_client.c.
Referenced by _et_ClientUserinfoChanged(), ClientConnect(), ClientDisconnect(), ClientSpawn(), Cmd_Give_f(), Cmd_ResetSetup_f(), Cmd_Team_f(), Do_Activate2_f(), G_LogExit(), G_MakeReferee(), G_MakeShoutcaster(), G_Mute_v(), G_MuteClient(), G_ref_cmd(), G_Referee_v(), G_refLogout_cmd(), G_refMute_cmd(), G_RemoveAllShoutcasters(), G_RemoveReferee(), G_RemoveShoutcaster(), G_ResetXP(), G_SetClientWeapons(), G_shuffleTeamsXP(), G_swapTeams(), G_UnMute_v(), G_UnMuteClient(), G_Unreferee_v(), G_UpgradeSkill(), ETInterface::InterfaceSendMessage(), SetTeam(), and vmMain().
void Cmd_Activate2_f (gentity_t * ent)
Cmd_Activate2_f.
Parameters
[in] ent
Definition at line 4161 of file g_cmds.c.
Referenced by G_RunClient().
void Cmd_Activate_f (gentity_t * ent)
Cmd_Activate_f.
Parameters
[in,out] ent
Definition at line 3968 of file g_cmds.c.
Referenced by ClientThink_real(), and SpectatorThink().
void Cmd_AuthRcon_f (gentity_t * ent)
Client authentication.
Parameters
[in,out] ent
Definition at line 594 of file g_referee.c.
Referenced by ClientCommand().
qboolean Cmd_CallVote_f (gentity_t * ent, unsigned int dwCommand, qboolean fRefCommand)
Cmd_CallVote_f.
Parameters
[in,out] ent
dwCommand - unused
[in] fRefCommand
Returns
Definition at line 3049 of file g_cmds.c.
Referenced by G_ref_cmd().
void Cmd_FireTeam_MP_f (gentity_t * ent)
Cmd_FireTeam_MP_f.
Parameters
[in] ent
Definition at line 1086 of file g_fireteams.c.
Referenced by ClientCommand().
void Cmd_Follow_f (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Cmd_Follow_f.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 2241 of file g_cmds.c.
void Cmd_FollowCycle_f (gentity_t * ent, int dir, qboolean skipBots)
Cmd_FollowCycle_f.
Parameters
[in,out] ent
[in] dir
[in] skipBots
Definition at line 2367 of file g_cmds.c.
Referenced by ClientCommand(), ClientDisconnect(), Cmd_Follow_f(), limbo(), and SpectatorThink().
void Cmd_Kill_f (gentity_t * ent)
Cmd_Kill_f.
Parameters
[in,out] ent
Definition at line 1123 of file g_cmds.c.
Referenced by Bot_Util_CheckForSuicide(), ETInterface::ChangeClass(), and ClientCommand().
void Cmd_Say_f (gentity_t * ent, int mode, qboolean arg0)
Cmd_Say_f.
Parameters
[in] ent
[in] mode
[in] arg0
Definition at line 2729 of file g_cmds.c.
Referenced by ClientCommand(), and G_say_teamnl_cmd().
void Cmd_Score_f (gentity_t * ent)
Request current scoreboard information.
Parameters
[out] ent
Definition at line 458 of file g_cmds.c.
Referenced by ClientCommand(), and player_die().
void Cmd_Team_f (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Cmd_Team_f.
Parameters
[in,out] ent
dwCommand - unused
fValue - unused
Definition at line 2106 of file g_cmds.c.
char* ConcatArgs (int start)
Concatenates console arguments.
Parameters
[in] start concatenate from this argument
Definition at line 488 of file g_cmds.c.
qboolean ConsoleCommand (void)
ConsoleCommand.
Returns
Definition at line 2572 of file g_svcmds.c.
Referenced by vmMain().
qboolean Do_Activate_f (gentity_t * ent, gentity_t * traceEnt)
Extracted out the functionality of Cmd_Activate_f from finding the object to use so we can force bots to use items, without worrying that they are looking EXACTLY at the target.
Parameters
[in,out] ent
[in,out] traceEnt
Returns
Definition at line 3726 of file g_cmds.c.
Referenced by Cmd_Activate_f().
void DoClientThinks (gentity_t * ent)
DoClientThinks.
Parameters
[in,out] ent
Definition at line 144 of file et-antiwarp.c.
Referenced by ClientThink(), and G_RunClient().
gentity_t* Drop_Item (gentity_t * ent, gitem_t * item, float angle, qboolean novelocity)
Spawns an item and tosses it forward.
Parameters
[in] ent
[in] item
[in] angle
[in] novelocity
Returns
Definition at line 941 of file g_items.c.
Referenced by misc_spawner_think().
void DynaFree (gentity_t * self)
DynaFree.
Parameters
[in,out] self
Definition at line 1095 of file g_missile.c.
void DynaSink (gentity_t * self)
DynaSink.
Parameters
[in,out] self
Definition at line 1075 of file g_missile.c.
int EntsThatRadiusCanDamage (vec3_t origin, float radius, int * damagedList)
Crude version of G_RadiusDamage to see if the dynamite can damage a func_constructible.
Parameters
[in] origin
[in] radius
[out] damagedList
Returns
Definition at line 513 of file g_weapon.c.
Referenced by DynaFree(), and Weapon_Engineer().
void etpro_AddUsercmd (int clientNum, usercmd_t * cmd)
etpro_AddUsercmd
Parameters
[in] clientNum
[in] cmd
Definition at line 49 of file et-antiwarp.c.
Referenced by ClientThink().
qboolean etpro_RadiusDamage (vec3_t origin, gentity_t * inflictor, gentity_t * attacker, float damage, float radius, gentity_t * ignore, meansOfDeath_t mod, qboolean clientsonly)
Mutation of G_RadiusDamage which lets us selectively damage only clients or only non clients.
Parameters
[in] origin
[in] inflictor
[in] attacker
[in] damage
[in] radius
[in] ignore
[in] mod
[in] clientsonly
Returns
Definition at line 2127 of file g_combat.c.
Referenced by G_RealExplodedMissile().
qboolean etpro_ScriptAction_SetValues (gentity_t * ent, char * params)
etpro_ScriptAction_SetValues
Ikkyo - change key/value pairs of any entity
syntax (example): set { origin "3510 -960 1280" classname "ookblat" etc etc } available fields can be found in field_t of g_spawn.c, it is quite simple to add new ones
Parameters
[in,out] ent
[in] params
Returns
Definition at line 4842 of file g_script_actions.c.
void Fill_Clip (playerState_t * ps, weapon_t weapon)
Push reserve ammo into available space in the clip.
Parameters
[in] ps
[in] weapon
Definition at line 117 of file g_items.c.
Referenced by Add_Ammo().
void FindIntermissionPoint (void)
This is also used for spectator spawns.
Definition at line 3189 of file g_main.c.
Referenced by BeginIntermission(), and SelectSpectatorSpawnPoint().
void FinishSpawningItem (gentity_t * ent)
Traces down to find where an item should rest, instead of letting them free fall from their spawn points.
Parameters
[in,out] ent
Definition at line 981 of file g_items.c.
Referenced by G_SpawnItem().
gentity_t* fire_flamebarrel (gentity_t * self, vec3_t start, vec3_t dir)
fire_flamebarrel
Parameters
[in] self
[in] start
[in] dir
Returns
Definition at line 1708 of file g_missile.c.
Referenced by Props_Barrel_Die().
gentity_t* fire_flamechunk (gentity_t * self, vec3_t start, vec3_t dir)
fire_flamechunk
Parameters
[in,out] self
[in] start
[in] dir
Returns
Definition at line 1044 of file g_missile.c.
Referenced by props_flamethrower_think(), and Weapon_FlamethrowerFire().
void Fire_Lead_Ext (gentity_t * ent, gentity_t * activator, float spread, int damage, vec3_t muzzle, vec3_t forward, vec3_t right, vec3_t up, meansOfDeath_t mod)
Fire_Lead_Ext - machine/flag gun fire.
Parameters
[in,out] ent
[in] activator
[in] spread
[in] damage
[in] muzzle
[in] forward
[in] right
[in] up
[in] mod
Note
Before calling this ensure ent->s.eFlags and activator->s.eFlags are set (EF_MG42_ACTIVE or EF_AAGUN_ACTIVE)
Definition at line 983 of file g_misc.c.
Referenced by aagun_fire(), mg42_fire(), and mountedmg42_fire().
gentity_t* fire_missile (gentity_t * self, vec3_t start, vec3_t dir, int weapon)
fire_missile
Parameters
[in] self
[in] start
[in] dir
[in] weapon
Returns
Note
IMPORTANT!!! : This accepts a /non-normalized/ direction vector to allow specification of how hard it's thrown. Please scale the vector before calling.
Definition at line 1670 of file g_missile.c.
Referenced by artillerySpotterThink(), G_AirStrikeThink(), G_ArtilleryExplode(), player_die(), Use_Shooter(), weapon_antitank_fire(), weapon_gpg40_fire(), weapon_grenadelauncher_fire(), and weapon_mortar_fire().
void FireWeapon (gentity_t * ent)
FireWeapon.
Parameters
[in,out] ent
Definition at line 4102 of file g_weapon.c.
Referenced by ClientEvents().
void QDECL void QDECL void QDECL format (printf , 1 , 2)
void func_constructible_underconstructionthink (gentity_t * ent)
func_constructible_underconstructionthink
Parameters
[in,out] ent
Todo:
: truck?
Definition at line 5296 of file g_mover.c.
Referenced by TryConstructing().
void G_AddAirstrikeToCounters (gentity_t * ent)
G_AddAirstrikeToCounters.
Parameters
[in] ent
Definition at line 2486 of file g_weapon.c.
Referenced by weapon_callAirStrike().
void G_AddArtilleryToCounters (gentity_t * ent)
G_AddArtilleryToCounters.
Parameters
[in] ent
Definition at line 2516 of file g_weapon.c.
Referenced by Weapon_Artillery().
void G_AddClientToFireteam (int entityNum, int leaderNum)
Only way a client should ever join a fireteam, other than creating one.
Parameters
[in] entityNum
[in] leaderNum
Definition at line 411 of file g_fireteams.c.
Referenced by Cmd_Vote_f(), and G_InviteToFireTeam().
void G_AddEvent (gentity_t * ent, int event, int eventParm)
Adds an event+parm and twiddles the event counter.
Parameters
[in,out] ent
[in] event
[in] eventParm
Definition at line 1057 of file g_utils.c.
Referenced by _et_G_AddEvent(), _et_RemoveWeaponFromPlayer(), alarmbox_use(), checkpoint_spawntouch(), checkpoint_touch(), ClientDisconnect(), Do_Activate2_f(), func_explosive_explode(), G_AnimScriptSound(), G_Damage(), G_DropWeapon(), G_FreeSatchel(), G_MissileImpact(), G_PlaySound_Cmd(), G_PushPlayer(), G_RunMissile(), G_ScriptAction_PlaySound(), G_TryDoor(), GibEntity(), GotoPos3(), P_DamageFeedback(), player_die(), Prop_Break_Sound(), Props_Chair_Touch(), props_flamethrower_think(), props_statue_death(), Reached_BinaryMover(), Reached_TrinaryMover(), ReturnToPos1(), ReturnToPos1Rotate(), ReturnToPos2(), Spawn_Junk(), Spawn_Shard(), target_rumble_think(), Touch_Item(), TryConstructing(), Use_BinaryMover(), Use_Shooter(), Use_Target_Speaker(), Use_TrinaryMover(), weapon_callPlane(), Weapon_Engineer(), and weapon_satcheldet_fire().
void G_AddKillSkillPoints (gentity_t * attacker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
G_AddKillSkillPoints.
Parameters
[in] attacker
[in] mod
[in] hr
[in] splash
Definition at line 489 of file g_stats.c.
Referenced by G_Damage().
void G_AddKillSkillPointsForDestruction (gentity_t * attacker, meansOfDeath_t mod, g_constructible_stats_t * constructibleStats)
G_AddKillSkillPointsForDestruction.
Parameters
[in] attacker
[in] mod
[in] constructibleStats
Definition at line 548 of file g_stats.c.
Referenced by func_constructible_explode(), func_explosive_explode(), G_KillEnts(), and G_RealExplodedMissile().
void G_AddPredictableEvent (gentity_t * ent, int event, int eventParm)
Use for non-pmove events that would also be predicted on the client side: jumppads and item pickups Adds an event+parm and twiddles the event counter.
Parameters
[in] ent
[in] event
[in] eventParm
Definition at line 1042 of file g_utils.c.
Referenced by ammo_touch(), and heal_touch().
void G_AddSkillPoints (gentity_t * ent, skillType_t skill, float points)
G_AddSkillPoints.
Parameters
[in,out] ent
[in] skill
[in] points
Definition at line 413 of file g_stats.c.
Referenced by _et_G_AddSkillPoints(), ClientThink_real(), Cmd_Give_f(), Do_Activate2_f(), G_AddKillSkillPoints(), G_AddKillSkillPointsForDestruction(), G_CheckSpottedLandMines(), Pickup_Health(), Pickup_Weapon(), TryConstructing(), Weapon_Engineer(), and Weapon_Syringe().
char* G_AddSpawnVarToken (const char * string)
G_AddSpawnVarToken.
Parameters
[in] string
Returns
Definition at line 857 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues(), G_Lua_CreateEntity(), G_ParseSpawnVars(), and G_ScriptAction_Create().
void G_addStats (gentity_t * targ, gentity_t * attacker, int damage, meansOfDeath_t mod)
G_addStats.
Parameters
[in,out] targ
[in,out] attacker
[in] damage
[in] mod
Todo:
: inspect world kills count as selfkill?
Definition at line 272 of file g_match.c.
Referenced by G_BurnTarget(), G_Damage(), and player_die().
void G_addStatsHeadShot (gentity_t * attacker, meansOfDeath_t mod)
Records weapon headshots.
Parameters
[in,out] attacker
[in] mod
Definition at line 379 of file g_match.c.
Referenced by G_Damage().
void G_AdjustedDamageVec (gentity_t * ent, vec3_t origin, vec3_t vec)
G_AdjustedDamageVec.
Parameters
[in] ent
[in] origin
[out] vec
Definition at line 1951 of file g_combat.c.
Referenced by etpro_RadiusDamage(), and G_RadiusDamage().
void* G_Alloc (unsigned int size)
G_Alloc.
Parameters
[in] size
Returns
Definition at line 47 of file g_mem.c.
Referenced by G_NewString(), G_Script_ScriptLoad(), G_Script_ScriptParse(), and SP_team_WOLF_objective().
mapEntityData_t* G_AllocMapEntityData (mapEntityData_Team_t * teamList)
G_AllocMapEntityData.
Parameters
[in,out] teamList
Returns
Definition at line 126 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_DisguisedPlayer(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), and G_UpdateTeamMapData_Tank().
qboolean G_allowFollow (gentity_t * ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
Parameters
[in] ent
[in] nTeam
Returns
Definition at line 2076 of file g_team.c.
Referenced by Cmd_Follow_f(), G_blockoutTeam(), G_desiredFollow(), and SpectatorThink().
qboolean G_AllowTeamsAllowed (gentity_t * ent, gentity_t * activator)
G_AllowTeamsAllowed.
Parameters
[in] ent
[in] activator
Returns
Definition at line 607 of file g_utils.c.
Referenced by G_CheckForCursorHints(), G_TryDoor(), and G_UseEntity().
void G_AnimScriptSound (int soundIndex, vec3_t org, int client)
G_AnimScriptSound.
Parameters
[in] soundIndex
org - unused
[in] client
Definition at line 1125 of file g_utils.c.
Referenced by G_InitGame().
int G_AntiLag_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Anti-Lag.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1253 of file g_vote.c.
qboolean G_AvailableAirstrike (gentity_t * ent)
G_AvailableAirstrikes.
Parameters
[in] ent
Returns
Definition at line 2439 of file g_weapon.c.
Referenced by ClientThink_real(), and weapon_checkAirStrike().
qboolean G_AvailableArtillery (gentity_t * ent)
Arty/airstrike rate limiting.
Parameters
[in] ent
Returns
Definition at line 2463 of file g_weapon.c.
Referenced by ClientThink_real(), and Weapon_Artillery().
int G_BalancedTeams_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Balanced Teams.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1282 of file g_vote.c.
int G_blockoutTeam (gentity_t * ent, int nTeam)
Return blockout status for a player.
Parameters
[in] ent
[in] nTeam
Returns
Definition at line 2065 of file g_team.c.
Referenced by SpectatorClientEndFrame().
void G_BuildEndgameStats (void)
send name, team and value when there is a winner - else empty string and TEAM_FREE = 0 (client structure is only used for awards!)
connectedClients have a team but keep the check for TEAM_FREE ... we'll never know for sure, connectedClients are determined in CalculateRanks
Definition at line 681 of file g_stats.c.
Referenced by G_LogExit().
gentity_t* G_BuildHead (gentity_t * ent, grefEntity_t * refent, qboolean newRefent)
G_BuildHead.
Parameters
[in] ent
[in] refent
[in] newRefent
Returns
Definition at line 707 of file g_combat.c.
Referenced by ClientEndFrame(), ClientThink_real(), G_AttachBodyParts(), and IsHeadShot().
gentity_t* G_BuildLeg (gentity_t * ent, grefEntity_t * refent, qboolean newRefent)
G_BuildLeg.
Parameters
[in] ent
[in] refent
[in] newRefent
Returns
Definition at line 828 of file g_combat.c.
Referenced by ClientEndFrame(), ClientThink_real(), G_AttachBodyParts(), and IsLegShot().
void G_BurnMeGood (gentity_t * self, gentity_t * body, gentity_t * chunk)
BurnMeGood now takes the flamechunk separately, because the old 'set-self-in-flames' method doesn't have a flamechunk to pass, and deaths were getting blamed on the world/player 0.
======================================================================
FLAMETHROWER
Parameters
[in] self
[in,out] body
[in] chunk
Definition at line 3722 of file g_weapon.c.
Referenced by G_BurnTarget(), Svcmd_Burn(), and Weapon_FlamethrowerFire().
void G_CalcClientAccuracies (void)
G_CalcClientAccuracies.
Definition at line 4527 of file g_cmds.c.
Referenced by Cmd_IntermissionWeaponAccuracies_f(), and G_BuildEndgameStats().
void G_CalcRank (gclient_t * client)
G_CalcRank.
Parameters
[in,out] client
Definition at line 200 of file g_session.c.
Referenced by _et_G_XP_Set(), ClientConnect(), G_LogExit(), G_ReadSessionData(), and G_ResetXP().
qboolean G_CallSpawn (gentity_t * ent)
Finds the spawn function for the entity and calls it.
Parameters
ent
Returns
qfalse if spawn not found
Definition at line 631 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues(), and G_SpawnGEntityFromSpawnVars().
int G_Campaign_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Campaign - simpleton: we dont verify map is allowed/exists.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 736 of file g_vote.c.
qboolean G_CanPickupWeapon (weapon_t weapon, gentity_t * ent)
Check if a weapon can be picked up.
Parameters
[in] weapon
[in] ent
Returns
Definition at line 423 of file g_items.c.
Referenced by G_CheckForCursorHints(), and Pickup_Weapon().
int G_CharacterIndex (const char * name)
G_CharacterIndex.
Parameters
[in] name
Returns
Note
Unused
Definition at line 271 of file g_utils.c.
void G_CheckForCursorHints (gentity_t * ent)
non-AI's check for cursor hint contacts
server-side because there's info we want to show that the client just doesn't know about. (health or other info of an explosive,invisible_users,items,etc.)
traceEnt is the ent hit by the trace, checkEnt is the ent that is being checked against (in case the traceent was an invisible_user or something)
Parameters
[in,out] ent
Definition at line 990 of file g_main.c.
Referenced by ClientThink_real().
qboolean G_checkReady (void)
Determine if the "ready" player threshold has been reached.
Returns
Definition at line 1778 of file g_team.c.
Referenced by G_readyMatchState(), and G_verifyMatchState().
int G_checkServerToggle (vmCvar_t * cv)
Update configstring for vote info.
Parameters
[in] cv
Returns
Definition at line 855 of file g_match.c.
Referenced by G_RegisterCvars(), and G_UpdateCvars().
void G_clientFlagIndicator (gentity_t * ent)
G_clientFlagIndicator.
Parameters
[in] flagIndicator
Definition at line 522 of file g_team.c.
Referenced by ClientBegin().
void G_ClientSound (gentity_t * ent, int soundIndex)
G_ClientSound.
Parameters
[in] ent
[in] soundIndex
Definition at line 1103 of file g_utils.c.
Referenced by _et_G_ClientSound(), and G_PlaySound_Cmd().
qboolean G_cmdDebounce (gentity_t * ent, const char * pszCommand)
Debounces cmd request as necessary.
Parameters
[in,out] ent
[in] pszCommand
Returns
Definition at line 174 of file g_cmds_ext.c.
Referenced by G_lock_cmd(), G_pause_cmd(), G_ready_cmd(), G_refPause_cmd(), G_specinvite_cmd(), G_speclock_cmd(), and G_teamready_cmd().
qboolean G_commandCheck (gentity_t * ent, const char * cmd, qboolean fDoAnytime)
G_commandCheck.
Parameters
[in] ent
[in] cmd
[in] fDoAnytime
Returns
Definition at line 118 of file g_cmds_ext.c.
Referenced by ClientCommand().
qboolean G_commandHelp (gentity_t * ent, const char * pszCommand, unsigned int dwCommand)
Prints specific command help info.
Parameters
[in] ent
[in] pszCommand
[in] dwCommand
Returns
Definition at line 150 of file g_cmds_ext.c.
Referenced by G_commandCheck(), and G_weaponRankings_cmd().
void G_commands_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Lists server commands.
Parameters
ent - unused
dwCommand - unused
fValue - unused
Definition at line 208 of file g_cmds_ext.c.
int G_Config_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_Config_v.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1313 of file g_vote.c.
void G_ConfigCheckLocked (void)
G_ConfigCheckLocked.
Todo:
: check for anything else?
Definition at line 516 of file g_config.c.
Referenced by G_RunFrame().
qboolean G_configSet (const char * configname)
Force settings to predefined state.
Parameters
[in] configname
Returns
Todo:
: handle the mapscript hash and run the map script
Definition at line 463 of file g_config.c.
Referenced by CC_loadconfig(), G_Config_v(), G_InitGame(), and G_ReloadConfig().
qboolean G_ConstructionBegun (gentity_t * ent)
G_ConstructionBegun.
Parameters
[in] ent
Returns
qtrue if a construction is under way on this ent, even before it hits any stages
Definition at line 2543 of file g_misc.c.
Referenced by G_IsConstructible().
gentity_t* G_ConstructionForTeam (gentity_t * toi, team_t team)
G_ConstructionForTeam.
Parameters
[in] toi
[in] team
Returns
Tshe constructible for this team that is attached to this toi
Definition at line 2605 of file g_misc.c.
Referenced by G_IsConstructible(), ETInterface::GetEntityLocalAABB(), ETInterface::GetEntityWorldAABB(), ETInterface::GetGoals(), and ETInterface::InterfaceSendMessage().
qboolean G_ConstructionIsFullyBuilt (gentity_t * ent)
G_ConstructionIsFullyBuilt.
Parameters
[in] ent
Returns
qtrue if all stage are built
Definition at line 2563 of file g_misc.c.
Referenced by G_ConstructionIsPartlyBuilt(), G_IsConstructible(), ETInterface::GetEntityFlags(), and ETInterface::InterfaceSendMessage().
qboolean G_ConstructionIsPartlyBuilt (gentity_t * ent)
G_ConstructionIsPartlyBuilt.
Parameters
[in] ent
Returns
qtrue if 1 stage or more is built
Definition at line 2577 of file g_misc.c.
Referenced by G_CheckForCursorHints(), G_ConstructionBegun(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
int G_CountTeamFieldops (team_t team)
G_CountTeamFieldops.
Parameters
[in] team
[in] alivecheck
Returns
Definition at line 1353 of file g_client.c.
Referenced by G_MaxAvailableAirstrikes(), and G_MaxAvailableArtillery().
int G_CountTeamLandmines (team_t team)
G_CountTeamLandmines.
Parameters
[in] team
Returns
Definition at line 1196 of file g_missile.c.
Referenced by G_RunFrame(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
int G_CountTeamMedics (team_t team, qboolean alivecheck)
G_CountTeamMedics.
Parameters
[in] team
[in] alivecheck
Returns
Definition at line 1287 of file g_client.c.
Referenced by AddMedicTeamBonus(), and player_die().
char* G_createStats (gentity_t * refEnt)
Generates weapon stat info for given ent.
Parameters
[in] refEnt
Returns
Definition at line 400 of file g_match.c.
Referenced by ClientDisconnect(), G_matchInfoDump(), G_statsall_cmd(), and G_statsPrint().
void G_Damage (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker, vec3_t dir, vec3_t point, int damage, int dflags, meansOfDeath_t mod)
G_Damage.
Parameters
[in,out] targ entity that is being damaged
[in,out] inflictor entity that is causing the damage
[in,out] attacker entity that caused the inflictor to damage targ example: targ=monster, inflictor=rocket, attacker=player
[in] dir direction of the attack for knockback
[in] point point at which the damage is being inflicted, used for headshots
[in] damage amount of damage being inflicted
[in] dflags these flags are used to control how T_Damage works DAMAGE_RADIUS damage was indirect (from a nearby explosion) DAMAGE_NO_ARMOR armor does not protect from this damage DAMAGE_NO_KNOCKBACK do not affect velocity, just view angles DAMAGE_NO_PROTECTION kills godmode, armor, everything
[in] mod
Note
inflictor, attacker, dir, and point can be NULL for environmental effects
This parameter was previously present : knockback force to be applied against targ as a result of the damage
Todo:
: also when damage is 0 ?
Definition at line 1130 of file g_combat.c.
Referenced by _et_G_Damage(), Blocked_Door(), Blocked_DoorRotate(), Bullet_Fire_Extended(), etpro_RadiusDamage(), Fire_Lead_Ext(), func_constructible_explode(), G_BurnMeGood(), G_BurnTarget(), G_FallDamage(), G_KillEnts(), G_MissileImpact(), G_MoverPush(), G_RadiusDamage(), G_SetEntState(), HandleEntsThatBlockConstructible(), hurt_touch(), ETInterface::InterfaceSendMessage(), Just_Got_Thrown(), P_WorldEffects(), props_castlebed_touch(), props_statue_blocked(), script_mover_blocked(), Svcmd_Die(), Svcmd_Gib(), target_kill_use(), target_laser_think(), Use_DamageInflictor(), and Weapon_Knife().
void G_DebugAddSkillLevel (gentity_t * ent, skillType_t skill)
G_DebugAddSkillLevel.
Parameters
[in] ent
[in] skill
Definition at line 622 of file g_stats.c.
Referenced by G_UpgradeSkill().
void G_DebugAddSkillPoints (gentity_t * ent, skillType_t skill, float points, const char * reason)
G_DebugAddSkillPoints.
Parameters
[in] ent
[in] skill
[in] points
[in] reason
Definition at line 652 of file g_stats.c.
Referenced by ClientThink_real(), Cmd_Give_f(), Do_Activate2_f(), G_AddKillSkillPoints(), G_AddKillSkillPointsForDestruction(), G_CheckSpottedLandMines(), Pickup_Health(), Pickup_Weapon(), TryConstructing(), Weapon_Engineer(), and Weapon_Syringe().
void G_DebugCloseSkillLog (void)
G_DebugCloseSkillLog.
Definition at line 598 of file g_stats.c.
Referenced by G_ShutdownGame().
void G_DebugOpenSkillLog (void)
G_DebugOpenSkillLog.
Definition at line 567 of file g_stats.c.
Referenced by G_InitGame().
void G_deleteStats (int nClient)
Resets player's current stats (session related only)
Parameters
[in] nClient
Definition at line 500 of file g_match.c.
Referenced by G_InitSessionData(), G_WriteClientSessionData(), and G_WriteSessionData().
qboolean G_desiredFollow (gentity_t * ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
Parameters
[in] ent
[in] nTeam
Returns
Definition at line 2112 of file g_team.c.
Referenced by Cmd_FollowCycle_f(), and G_FollowSame().
qboolean G_DoAntiwarp (gentity_t * ent)
G_DoAntiwarp.
Parameters
[in] ent
Returns
Note
Fixes spectator bugs
Definition at line 16 of file et-antiwarp.c.
Referenced by ClientEndFrame(), ClientThink(), ClientThink_real(), and G_RunClient().
void QDECL G_DPrintf (const char * fmt, ...)
Referenced by ClientEndFrame(), ClientUserinfoChanged(), Cmd_UnIgnore_f(), G_ParseMapSettings(), G_ScriptAction_SetChargeTimeFactor(), G_SetEntState(), InitTrigger(), respawn(), SP_func_explosive(), SP_misc_gamemodel(), Use_Team_Spawnpoint(), and WolfReviveBbox().
void G_DropItems (gentity_t * self)
Drops items. Currently only red-/blueflag.
Parameters
[in,out] self
Todo:
set player->otherentitynum2 with old modelindex2 from flag and restore here
Definition at line 1270 of file g_cmds.c.
Referenced by ClientDisconnect(), Cmd_DropObjective_f(), and player_die().
void G_DropWeapon (gentity_t * ent, weapon_t weapon)
Drop Weapon.
Parameters
[in] ent
[in] weapon
Definition at line 324 of file g_items.c.
Referenced by Pickup_Weapon(), and TossWeapons().
qboolean G_EmplacedGunIsMountable (gentity_t * ent, gentity_t * other)
G_EmplacedGunIsMountable.
Parameters
[in] ent
[in] other
Returns
Definition at line 878 of file g_main.c.
Referenced by Do_Activate_f(), and G_CheckForCursorHints().
qboolean G_EmplacedGunIsRepairable (gentity_t * ent, gentity_t * other)
G_EmplacedGunIsRepairable.
Parameters
[in] ent
[in] other
Returns
Definition at line 949 of file g_main.c.
Referenced by G_CheckForCursorHints(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
int G_EntitiesFree (void)
G_EntitiesFree.
Returns
Definition at line 872 of file g_utils.c.
Referenced by _et_G_EntitiesFree(), and G_DrawEntBBox().
void G_EntitySound (gentity_t * ent, const char * soundId, int volume)
Plays a sound (wav file or sound script) on this entity.
Parameters
[in] ent entity to play the sound on
[in] soundId sound file name or sound script ID
[in] volume sound volume, only applies to sound file name call
Note
Unused. Keep this.
Calling G_AddEvent(..., EV_GENERAL_SOUND, ...) has the danger of the event never getting through to the client because the entity might not be visible (unless it has the SVF_BROADCAST flag), so if you want to make sure the sound is heard, call this function instead.
Definition at line 2526 of file g_cmds.c.
void G_EntitySoundNoCut (gentity_t * ent, const char * soundId, int volume)
Similar to G_EntitySound, but do not cut this sound off.
Parameters
[in] ent entity to play the sound on
[in] soundId sound file name or sound script ID
[in] volume sound volume, only applies to sound file name call
Note
Unused. See G_EntitySound()
Definition at line 2541 of file g_cmds.c.
void QDECL G_Error (const char * fmt, ...)
Referenced by Cmd_FollowCycle_f(), constructiblemarker_setup(), etpro_ScriptAction_SetValues(), func_constructiblespawn(), G_AddClientToFireteam(), G_AddSpawnVarToken(), G_Alloc(), G_AllocDebrisChunk(), G_AllocMapEntityData(), G_ApplyToFireTeam(), G_CheckForExistingAnimModelInfo(), G_DestroyFireteam(), G_FindConfigstringIndex(), G_FreeMapEntityData(), G_GetFireteamTeam(), G_GiveAdminOfFireTeam(), G_InviteToFireTeam(), G_IsFireteamLeader(), G_IsOnFireteam(), G_KickFireTeamPlayer(), G_LinkDamageParents(), G_LinkDebris(), G_LuaRunIsolated(), G_ParseCampaigns(), G_ParseSpawnVars(), G_ProcessTagConnect(), G_ProposeFireTeamPlayer(), G_RegisterFireteam(), G_RegisterPlayerClasses(), G_RemoveClientFromFireteams(), G_Script_ScriptParse(), G_ScriptAction_Accum(), G_ScriptAction_AddTankAmmo(), G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_AlertEntity(), G_ScriptAction_AlliedRespawntime(), G_ScriptAction_AllowTankEnter(), G_ScriptAction_AllowTankExit(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_AttatchToTrain(), G_ScriptAction_AxisRespawntime(), G_ScriptAction_ChangeModel(), G_ScriptAction_Construct(), G_ScriptAction_ConstructibleChargeBarReq(), G_ScriptAction_ConstructibleClass(), G_ScriptAction_ConstructibleConstructXPBonus(), G_ScriptAction_ConstructibleDestructXPBonus(), G_ScriptAction_ConstructibleDuration(), G_ScriptAction_ConstructibleHealth(), G_ScriptAction_ConstructibleWeaponclass(), G_ScriptAction_Create(), G_ScriptAction_Cvar(), G_ScriptAction_Delete(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), G_ScriptAction_FaceAngles(), G_ScriptAction_FadeAllSounds(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GlobalAccum(), G_ScriptAction_GotoMarker(), G_ScriptAction_Kill(), G_ScriptAction_MusicFade(), G_ScriptAction_MusicPlay(), G_ScriptAction_MusicQueue(), G_ScriptAction_MusicStart(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_PlayAnim(), G_ScriptAction_PlaySound(), G_ScriptAction_Print(), G_ScriptAction_PrintAccum(), G_ScriptAction_PrintGlobalAccum(), G_ScriptAction_RemoveTeamVoiceAnnounce(), G_ScriptAction_RepairMG42(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDamagable(), G_ScriptAction_SetDebugLevel(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetGlobalFog(), G_ScriptAction_SetHQStatus(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetModelFromBrushmodel(), G_ScriptAction_SetPosition(), G_ScriptAction_SetRotation(), G_ScriptAction_SetRoundTimelimit(), G_ScriptAction_SetSpeed(), G_ScriptAction_SetState(), G_ScriptAction_SetTankAmmo(), G_ScriptAction_SetWinner(), G_ScriptAction_ShaderRemap(), G_ScriptAction_StartAnimation(), G_ScriptAction_TagConnect(), G_ScriptAction_TeamVoiceAnnounce(), G_ScriptAction_ToggleSpeaker(), G_ScriptAction_Trigger(), G_ScriptAction_VoiceAnnounce(), G_ScriptAction_Wait(), G_SHA1(), G_Spawn(), G_SpawnEntitiesFromString(), G_SpawnStringExt(), G_TryPushingEntity(), G_WarnFireTeamPlayer(), info_limbo_camera_setup(), misc_firetrails_think(), objective_Register(), player_die(), PrintMsg(), Reached_BinaryMover(), Reached_TrinaryMover(), RespawnItem(), SelectRandomTeamSpawnPoint(), SelectSpawnPoint(), SP_func_brushmodel(), SP_func_constructible(), SP_func_debris(), SP_func_door(), SP_func_door_rotating(), SP_func_secret(), SP_misc_gamemodel(), SP_misc_landmine(), SP_script_camera(), SP_script_model_med(), SP_script_mover(), SP_script_multiplayer(), SP_target_speaker(), SP_team_WOLF_checkpoint(), SP_trigger_objective_info(), SP_worldspawn(), target_speaker_multiple(), Think_SetupObjectiveInfo(), trigger_ammo_setup(), trigger_heal_setup(), and Use_Target_Print().
void G_ExplodeMines (gentity_t * ent)
G_ExplodeMines.
Removes any weapon objects lying around in the map when they disconnect/switch team
Parameters
[in] ent
Definition at line 1321 of file g_missile.c.
Referenced by ClientDisconnect(), G_shuffleTeamsXP(), and SetTeam().
void G_ExplodeMissile (gentity_t * ent)
Explode a missile without an impact.
Parameters
[in,out] ent
Definition at line 400 of file g_missile.c.
Referenced by G_Damage(), weapon_callAirStrike(), weapon_checkAirStrike(), weapon_checkAirStrikeThink(), and Weapon_Engineer().
qboolean G_ExplodeSatchels (gentity_t * ent)
G_ExplodeSatchels.
Parameters
[in] ent
Returns
Definition at line 1331 of file g_missile.c.
Referenced by weapon_satcheldet_fire().
void G_FadeItems (gentity_t * ent, int modType)
Remove any items that the player should no longer have, on disconnect/class change etc changed to just set the parent to NULL.
Parameters
[in] ent
[in] modType
Definition at line 1149 of file g_missile.c.
Referenced by ClientDisconnect(), G_ExplodeMines(), G_shuffleTeamsXP(), player_die(), and SetTeam().
qboolean G_FilterIPBanPacket (char * from)
G_FilterIPBanPacket.
Parameters
[in] from
Returns
Definition at line 269 of file g_svcmds.c.
Referenced by ClientConnect().
qboolean G_FilterMaxLivesIPPacket (char * from)
G_FilterMaxLivesIPPacket.
Parameters
[in] from
Returns
Definition at line 279 of file g_svcmds.c.
Referenced by ClientConnect().
qboolean G_FilterMaxLivesPacket (char * from)
Check to see if the user is trying to sneak back in with g_enforcemaxlives enabled.
Parameters
[in] from
Definition at line 289 of file g_svcmds.c.
Referenced by ClientConnect().
gentity_t* G_Find (gentity_t * from, int fieldofs, const char * match)
Searches all active entities for the next one that holds the matching string at fieldofs (use the FOFS() macro) in the structure. Searches beginning at the entity after from, or the beginning if NULL NULL will be returned if the end of the list is reached.
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 320 of file g_utils.c.
Referenced by AutoBuildConstruction(), ETInterface::FindEntityInSphere(), FindIntermissionPoint(), findNonAIBrushTargeter(), func_constructiblespawn(), G_ScriptAction_Accum(), G_ScriptAction_Cvar(), G_ScriptAction_Delete(), G_ScriptAction_GlobalAccum(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetMainObjective(), G_ScriptAction_TagConnect(), G_ScriptAction_Trigger(), GetMG42s(), HandleEntsThatBlockConstructible(), SelectNearestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomTeamSpawnPoint(), smoke_init(), SP_props_snowGenerator(), target_script_trigger_use(), TryConstructing(), Use_Props_Shard_Generator(), and Use_Target_Lock().
gentity_t* G_FindByTargetname (gentity_t * from, const char * match)
G_FindByTargetname.
Parameters
[in,out] from
[in] match
Returns
Definition at line 475 of file g_utils.c.
Referenced by alarmbox_updateparts(), ClientBegin(), constructiblemarker_setup(), dust_angles_think(), ETInterface::EntityByName(), func_constructiblespawn(), G_CheckForCursorHints(), G_KillEnts(), G_LinkDamageParents(), G_LinkDebris(), G_PickTarget(), G_ScriptAction_Accum(), G_ScriptAction_AddTankAmmo(), G_ScriptAction_AttatchToTrain(), G_ScriptAction_Construct(), G_ScriptAction_GotoMarker(), G_ScriptAction_RepairMG42(), G_ScriptAction_SetDamagable(), G_ScriptAction_SetPosition(), G_ScriptAction_SetTankAmmo(), G_ScriptAction_TagConnect(), ETInterface::GetGoals(), info_limbo_camera_setup(), locateMaster(), misc_beam_start(), misc_firetrails_think(), props_flamethrower_init(), props_flamethrower_think(), script_mover_spawn(), sparks_angles_think(), target_laser_start(), target_speaker_multiple(), Think_SetupObjectiveInfo(), Think_SetupTrainTargets(), Think_SetupTrainTargets_rotating(), trigger_ammo_setup(), trigger_heal_setup(), Use_DamageInflictor(), and Use_Target_Give().
gentity_t* G_FindByTargetnameFast (gentity_t * from, const char * match, int hash)
This version should be used for loops, saves the constant hash building.
Parameters
[in,out] from
[in] match
[in] hash
Returns
Definition at line 525 of file g_utils.c.
Referenced by checkpoint_spawntouch(), func_explosive_explode(), G_ScriptAction_AlertEntity(), G_ScriptAction_SetState(), and G_UseTargets().
int G_FindConfigstringIndex (const char * name, int start, int max, qboolean create)
G_FindConfigstringIndex.
=========================================================================
model / sound configstring indexes
Parameters
[in] name
[in] start
[in] max
[in] create
Returns
Definition at line 144 of file g_utils.c.
Referenced by dlight_finish_spawning(), G_CharacterIndex(), G_ModelIndex(), G_ProcessTagConnect(), G_ShaderIndex(), G_SkinIndex(), G_SoundIndex(), and G_StringIndex().
gentity_t* G_FindFloat (gentity_t * from, int fieldofs, float match)
Like G_Find, but searches for float values..
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 398 of file g_utils.c.
Referenced by G_ScriptAction_Delete().
fireteamData_t* G_FindFreePublicFireteam (team_t team)
G_FindFreePublicFireteam.
Parameters
[in] team
Returns
Definition at line 975 of file g_fireteams.c.
Referenced by Cmd_Vote_f(), and SetTeam().
gentity_t* G_FindInt (gentity_t * from, int fieldofs, int match)
Like G_Find, but searches for integer values.
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 361 of file g_utils.c.
Referenced by G_ScriptAction_Delete().
mapEntityData_t* G_FindMapEntityData (mapEntityData_Team_t * teamList, int entNum)
G_FindMapEntityData.
Parameters
[in] teamList
[in] entNum
Returns
Definition at line 157 of file g_teammapdata.c.
Referenced by ClientDisconnect(), constructible_indicator_think(), explosive_indicator_think(), func_constructible_explode(), G_Damage(), G_RealExplodedMissile(), G_SetEntState(), G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), G_UpdateTeamMapData_Tank(), HandleEntsThatBlockConstructible(), player_die(), SetTeam(), TryConstructing(), and Weapon_Engineer().
mapEntityData_t* G_FindMapEntityDataSingleClient (mapEntityData_Team_t * teamList, mapEntityData_t * start, int entNum, int clientNum)
G_FindMapEntityDataSingleClient.
Parameters
[in] teamList
[in] start
[in] entNum
[in] clientNum
Returns
Definition at line 185 of file g_teammapdata.c.
Referenced by ClientDisconnect(), G_UpdateTeamMapData(), G_UpdateTeamMapData_DisguisedPlayer(), player_die(), and SetTeam().
gentity_t* G_FindSatchel (gentity_t * ent)
G_FindSatchel.
Parameters
[in] ent
Returns
Definition at line 1280 of file g_missile.c.
gentity_t* G_FindVector (gentity_t * from, int fieldofs, const vec3_t match)
Like G_Find, but searches for vector values..
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 435 of file g_utils.c.
Referenced by G_ScriptAction_Delete().
qboolean G_FlingClient (gentity_t * vic, int flingType)
G_FlingClient.
Parameters
[in,out] vic
[in] flingType
Returns
Definition at line 2754 of file g_misc.c.
Referenced by Svcmd_Fling().
qboolean G_FollowSame (gentity_t * ent)
Try to follow the same client as last time (before getting killed)
Parameters
[in] ent
Definition at line 2466 of file g_cmds.c.
Referenced by limbo().
void G_FreeEntity (gentity_t * ent)
Marks the entity as free.
Parameters
[in,out] ent
Todo:
: remove tmp var l_free if we are sure there are no issues caused by this change (especially on network games)
Definition at line 894 of file g_utils.c.
Referenced by _et_G_FreeEntity(), AimAtTarget(), BecomeExplosion(), Blocked_Door(), Blocked_DoorRotate(), ClientEndFrame(), ClientThink_real(), constructible_indicator_think(), crate_animate(), DynaSink(), explosive_indicator_think(), FinishSpawningItem(), firetrail_die(), func_brushmodel_delete(), func_constructible_explode(), G_AirStrikeThink(), G_BodyDP(), G_delayPrint(), G_DettachBodyParts(), G_FadeItems(), G_KillEnts(), G_MagicSink(), G_MoverPush(), G_RealExplodedMissile(), G_RunEntity(), G_RunFlamechunk(), G_RunItem(), G_RunMissile(), G_ScriptAction_Delete(), G_ScriptAction_RemoveEntity(), G_SetEntState(), G_SpawnGEntityFromSpawnVars(), ETInterface::GetGoals(), HandleEntsThatBlockConstructible(), hurt_think(), info_limbo_camera_setup(), IsHeadShot(), IsLegShot(), landmine_setup(), locateCamera(), locateMaster(), mg42_spawn(), misc_beam_start(), multi_trigger(), OilParticles_think(), Props_Activated(), Props_Barrel_Animate(), Props_Chair_Animate(), Props_Chair_Skyboxtouch(), props_decoration_death(), props_flippy_blocked(), props_radio_die(), props_radio_dieSEVEN(), props_statue_death(), Psmoke_think(), script_mover_blocked(), script_mover_die(), smoke_think(), smoker_think(), SP_corona(), SP_func_debris(), SP_func_train(), SP_func_train_rotating(), SP_info_limbo_camera(), SP_info_null(), SP_info_train_spline_main(), SP_light(), SP_lightJunior(), SP_misc_gamemodel(), SP_misc_light_surface(), SP_misc_model(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_path_corner(), SP_path_corner_2(), SP_props_sparks(), SP_target_location(), SP_trigger_concussive_dust(), Spawn_Junk(), Spawn_Shard(), Team_ResetFlag(), Touch_flagonly(), trigger_always_think(), Use_DamageInflictor(), Use_Props_Shard_Generator(), Weapon_Engineer(), and weapon_smokeBombExplode().
mapEntityData_t* G_FreeMapEntityData (mapEntityData_Team_t * teamList, mapEntityData_t * mEnt)
G_FreeMapEntityData.
Parameters
[in,out] teamList
[in,out] mEnt
Returns
Next entity in the array
Definition at line 101 of file g_teammapdata.c.
Referenced by ClientDisconnect(), constructible_indicator_think(), explosive_indicator_think(), func_constructible_explode(), G_Damage(), G_RealExplodedMissile(), G_SendMapEntityInfo(), G_SendSpectatorMapEntityInfo(), G_SetEntState(), HandleEntsThatBlockConstructible(), player_die(), SetTeam(), TryConstructing(), and Weapon_Engineer().
void G_FreeSatchel (gentity_t * ent)
G_FreeSatchel.
Parameters
[in,out] ent
Definition at line 1377 of file g_missile.c.
int G_FriendlyFire_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Team Damage.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1224 of file g_vote.c.
int G_Gametype_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
GameType.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 395 of file g_vote.c.
int G_GetEnemyPosition (gentity_t * ent, gentity_t * targ)
G_GetEnemyPosition.
Parameters
[in] ent
[in] targ
Returns
Definition at line 2882 of file g_misc.c.
Referenced by Weapon_Knife().
weapon_t G_GetPrimaryWeaponForClient (gclient_t * client)
Get the primary weapon of the client.
Parameters
[in] client
Returns
the primary weapon of the client
Definition at line 183 of file g_items.c.
Referenced by Pickup_Weapon(), and TossWeapons().
weapon_t G_GetPrimaryWeaponForClientSoldier (weapon_t weapon, gclient_t * client)
Get the primary weapon of the client.
Parameters
[in] weapon
[in] client
Returns
the primary weapon of the soldier client
Definition at line 272 of file g_items.c.
Referenced by Pickup_Weapon().
int G_GetSysMessageNumber (const char * sysMsg)
G_GetSysMessageNumber.
Parameters
[in] sysMsg
Returns
Definition at line 88 of file g_systemmsg.c.
Referenced by G_ScriptAction_VoiceAnnounce().
team_t G_GetTeamFromEntity (gentity_t * ent)
G_GetTeamFromEntity.
Parameters
[in] ent
Returns
Definition at line 1835 of file g_utils.c.
Referenced by G_Damage(), and player_die().
void G_GlobalClientEvent (entity_event_t event, int param, int client)
G_GlobalClientEvent.
Parameters
[in] event
[in] param
[in] client
Definition at line 2938 of file g_weapon.c.
Referenced by Weapon_Artillery(), weapon_callAirStrike(), and weapon_checkAirStrike().
void G_globalFlagIndicator (void)
G_globalFlagIndicator.
Parameters
[in] flagIndicator
Definition at line 506 of file g_team.c.
Referenced by G_DropItems(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), Touch_flagonly(), and Touch_flagonly_multiple().
void G_globalSound (const char * sound)
Plays specified sound globally.
Parameters
[in] sound
Definition at line 114 of file g_match.c.
Referenced by _et_G_globalSound(), G_delayPrint(), G_pause_cmd(), G_PlaySound_Cmd(), and G_refPause_cmd().
void G_globalSoundEnum (int sound)
G_globalSoundEnum.
Parameters
[in] sound
Definition at line 128 of file g_match.c.
Referenced by Cmd_CallVote_f(), G_pause_cmd(), and G_refPause_cmd().
void G_HistoricalTrace (gentity_t * ent, trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Run a trace with players in historical positions.
Parameters
[in] ent
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 701 of file g_antilag.c.
Referenced by _et_G_HistoricalTrace(), Fire_Lead_Ext(), Weapon_Knife(), and Weapon_Syringe().
void G_HistoricalTraceBegin (gentity_t * ent)
G_HistoricalTraceBegin.
Parameters
[in] ent
Definition at line 767 of file g_antilag.c.
Referenced by Bullet_Fire().
void G_HistoricalTraceEnd (gentity_t * ent)
G_HistoricalTraceEnd.
Parameters
[in] ent
Definition at line 781 of file g_antilag.c.
Referenced by Bullet_Fire().
void G_HQSay (gentity_t * other, int color, const char * name, const char * message)
G_HQSay.
Parameters
[in] other
[in] color
[in] name
[in] message
Definition at line 2555 of file g_cmds.c.
Referenced by Weapon_Artillery(), weapon_callAirStrike(), and weapon_checkAirStrike().
void G_InitGentity (gentity_t * e)
G_InitGentity.
Parameters
[in,out] e
Definition at line 779 of file g_utils.c.
Referenced by ClientBegin(), and G_Spawn().
void G_InitMapEntityData (mapEntityData_Team_t * teamList)
G_InitMapEntityData.
Parameters
[out] teamList
Definition at line 77 of file g_teammapdata.c.
Referenced by G_ResetTeamMapData().
void G_initMatch (void)
G_initMatch.
Definition at line 42 of file g_match.c.
Referenced by SP_worldspawn().
void G_InitMemory (void)
G_InitMemory.
Definition at line 72 of file g_mem.c.
Referenced by G_InitGame().
void G_InitSessionData (gclient_t * client, const char * userinfo)
Called on a first-time connect.
Parameters
[in] client
userinfo
Definition at line 404 of file g_session.c.
Referenced by ClientConnect().
void G_InitTempTraceIgnoreEnts (void)
System to temporarily ignore certain ents during traces.
Note
Unused
Definition at line 2468 of file g_misc.c.
void G_InitWorldSession (void)
G_InitWorldSession.
Todo:
: deal with the multi-map missions
Definition at line 445 of file g_session.c.
Referenced by G_InitGame().
void G_IntermissionMapList (gentity_t * ent)
G_IntermissionMapList.
Parameters
[in] ent
Definition at line 1648 of file g_vote.c.
Referenced by ClientCommand().
void G_IntermissionMapVote (gentity_t * ent)
G_IntermissionMapVote.
Parameters
[in,out] ent
Definition at line 1568 of file g_vote.c.
Referenced by ClientCommand().
void G_IntermissionVoteTally (gentity_t * ent)
G_IntermissionVoteTally.
Parameters
[in] ent
Definition at line 1685 of file g_vote.c.
Referenced by ClientCommand(), ClientDisconnect(), ClientSpawn(), and G_IntermissionMapVote().
void G_InviteToFireTeam (int entityNum, int otherEntityNum)
The only way a client should ever be invited to join a team.
Parameters
[in] entityNum
[in] otherEntityNum
Definition at line 630 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), Cmd_Vote_f(), and G_ProposeFireTeamPlayer().
gentity_t* G_IsConstructible (team_t team, gentity_t * toi)
G_IsConstructible.
Parameters
[in] team
[in] toi
Returns
Definition at line 2638 of file g_misc.c.
Referenced by G_CheckForCursorHints(), and ETInterface::InterfaceSendMessage().
qboolean G_IsFireteamLeader (int entityNum, fireteamData_t ** teamNum)
G_IsFireteamLeader.
Parameters
[in] entityNum
[out] teamNum
Returns
Definition at line 258 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), Cmd_Vote_f(), G_AddClientToFireteam(), G_DestroyFireteam(), G_GiveAdminOfFireTeam(), G_InviteToFireTeam(), G_KickFireTeamPlayer(), and G_WarnFireTeamPlayer().
qboolean G_IsShoutcastPasswordSet (void)
G_IsShoutcastPasswordSet.
Returns
Definition at line 864 of file g_referee.c.
Referenced by G_IsShoutcastStatusAvailable(), G_makesc_cmd(), G_refMakeShoutcaster_cmd(), G_refRemoveShoutcaster_cmd(), and G_removesc_cmd().
qboolean G_IsShoutcastStatusAvailable (gentity_t * ent)
G_IsShoutcastStatusAvailable.
Parameters
[in] ent
Returns
Definition at line 879 of file g_referee.c.
Referenced by G_sclogin_cmd(), and G_sclogout_cmd().
qboolean G_isValidConfig (gentity_t * ent, const char * configname)
Checks if config file is in paths (used before initiating a vote for configs)
Parameters
[in] ent
[in] configname
Definition at line 102 of file g_config.c.
Referenced by G_Config_v().
qboolean G_IsWeaponDisabled (gentity_t * ent, weapon_t weapon)
Checks for heavy and rifle weapons restriction.
Parameters
[in] ent
[in] weapon
Returns
Todo:
This function needs some rework: count picked up opposite team weapons too see CG_LimboPanel_RealWeaponIsDisabled
Definition at line 1802 of file g_cmds.c.
Referenced by _choosePriWeap(), _chooseSecWeap(), ETInterface::ChangeClass(), ETInterface::ChangeTeam(), ClientSpawn(), and G_SetClientWeapons().
int G_Kick_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Player Kick.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 457 of file g_vote.c.
Referenced by CheckVote(), Cmd_CallVote_f(), and Cmd_Vote_f().
void G_KillEnts (const char * target, gentity_t * ignore, gentity_t * killer, meansOfDeath_t mod)
Kills the activator. (default)
QUAKED target_kill (.5 .5 .5) (-8 -8 -8) (8 8 8) kill_user_too If targets, they will be killed when this is fired "kill_user_too" will still kill the activator when this ent has targets (default is only kill targets, not activator)
Parameters
[in] target
[in] ignore
[in] killer
[in] mod
Definition at line 833 of file g_target.c.
Referenced by G_ScriptAction_Kill(), and target_kill_use().
qboolean G_LandmineArmed (gentity_t * ent)
G_LandmineArmed.
Parameters
[in] ent
Returns
Definition at line 1473 of file g_weapon.c.
Referenced by G_LandmineSnapshotCallback().
qboolean G_LandmineSnapshotCallback (int entityNum, int clientNum)
G_LandmineSnapshotCallback.
Parameters
[in] entityNum
[in] clientNum
Returns
Definition at line 1598 of file g_missile.c.
Referenced by G_SnapshotCallback().
qboolean G_LandmineSpotted (gentity_t * ent)
G_LandmineSpotted.
Parameters
[in] ent
Returns
Definition at line 1493 of file g_weapon.c.
Referenced by G_LandmineSnapshotCallback(), and G_LandmineThink().
qboolean G_LandmineTriggered (gentity_t * ent)
G_LandmineTriggered.
Parameters
[in] ent
Returns
Definition at line 1463 of file g_weapon.c.
Referenced by G_CheckSpottedLandMines().
qboolean G_LandmineUnarmed (gentity_t * ent)
G_LandmineUnarmed.
Parameters
[in] ent
Returns
Definition at line 1483 of file g_weapon.c.
Referenced by Weapon_Engineer().
void G_LeaveTank (gentity_t * ent, qboolean position)
G_LeaveTank.
Parameters
[in,out] ent
[in] position
Definition at line 3894 of file g_cmds.c.
Referenced by ClientDisconnect(), Cmd_Activate_f(), G_shuffleTeamsXP(), MoveClientToIntermission(), player_die(), script_mover_die(), and SetTeam().
void G_LinkDamageParents (void)
G_LinkDamageParents.
Definition at line 5817 of file g_mover.c.
Referenced by G_InitGame().
void G_LinkDebris (void)
G_LinkDebris.
Definition at line 5838 of file g_mover.c.
Referenced by G_InitGame().
void G_loadMatchGame (void)
Setting initialization.
Definition at line 55 of file g_match.c.
Referenced by G_InitGame().
void G_lock_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team.
Parameters
[in] ent
[in] dwCommand
[in] fLock
Definition at line 257 of file g_cmds_ext.c.
void G_LogDeath (gentity_t * ent, weapon_t weap)
G_LogDeath.
Parameters
[in,out] ent
[in] weap
Definition at line 46 of file g_stats.c.
Referenced by player_die().
void QDECL void G_LogExit (const char * string)
Append information about this game to the log file.
Parameters
[in] string
Definition at line 3680 of file g_main.c.
Referenced by CheckExitRules(), G_Nextmap_v(), G_ScriptAction_EndRound(), and G_Surrender_v().
void G_LogKill (gentity_t * ent, weapon_t weap)
G_LogKill.
Parameters
[in,out] ent
[in] weap
Definition at line 61 of file g_stats.c.
Referenced by player_die().
void QDECL G_LogPrintf (const char * fmt, ...)
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallVote_f(), G_matchInfoDump(), G_ParseCampaigns(), G_Say(), G_Script_ScriptEvent(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), player_die(), PrintMaxLivesGUID(), Touch_Item(), trap_SendServerCommand(), Weapon_Engineer(), and Weapon_Syringe().
void G_LogRegionHit (gentity_t * ent, hitRegion_t hr)
G_LogRegionHit.
Parameters
[in,out] ent
[in] hr
Definition at line 91 of file g_stats.c.
Referenced by G_Damage().
void G_LogTeamKill (gentity_t * ent, weapon_t weap)
G_LogTeamKill.
Parameters
[in,out] ent
[in] weap
Definition at line 76 of file g_stats.c.
Referenced by player_die().
void G_LoseKillSkillPoints (gentity_t * tker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
Loose skill for evil tkers :E.
Parameters
[in] tker
[in] mod
hr - unused
splash - unused
Definition at line 466 of file g_stats.c.
Referenced by Cmd_Vote_f().
void G_LoseSkillPoints (gentity_t * ent, skillType_t skill, float points)
G_LoseSkillPoints.
Parameters
[in,out] ent
[in] skill
[in] points
Definition at line 285 of file g_stats.c.
Referenced by _et_G_LoseSkillPoints(), and G_LoseKillSkillPoints().
void G_MagicSink (gentity_t * self)
Magically sink given entity before freeing.
Parameters
[in,out] self The entity to sink
Note
Make it TR_LINEAR so it doesnt chew bandwidth...
Definition at line 2909 of file g_misc.c.
Referenced by G_FadeItems(), LaunchItem(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void G_MakeReady (gentity_t * ent)
G_MakeReady.
Parameters
[in,out] ent
Definition at line 4390 of file g_cmds.c.
Referenced by Cmd_IntermissionReady_f(), G_ready_cmd(), and G_teamready_cmd().
void G_MakeReferee (void)
G_MakeReferee.
Definition at line 653 of file g_referee.c.
void G_makesc_cmd (void)
Set shoutcaster command.
Definition at line 715 of file g_cmds_ext.c.
void G_MakeShoutcaster (gentity_t * ent)
G_MakeShoutcaster.
Parameters
[in] ent
Definition at line 726 of file g_referee.c.
Referenced by G_makesc_cmd(), G_refMakeShoutcaster_cmd(), and G_sclogin_cmd().
void G_MakeUnready (gentity_t * ent)
G_MakeUnready.
Parameters
[in,out] ent
Definition at line 4401 of file g_cmds.c.
Referenced by G_LogExit(), and G_ready_cmd().
int G_Map_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Map - simpleton: we dont verify map is allowed/exists.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 677 of file g_vote.c.
qboolean G_MapIsValidCampaignStartMap (void)
G_MapIsValidCampaignStartMap.
Returns
Definition at line 1693 of file g_utils.c.
Referenced by G_UpdateCvars().
int G_MapRestart_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Map Restart.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 792 of file g_vote.c.
void G_MapVoteInfoRead (void)
G_MapVoteInfoRead.
Definition at line 5326 of file g_main.c.
Referenced by BeginIntermission().
void G_MapVoteInfoWrite (void)
G_MapVoteInfoWrite.
Definition at line 5224 of file g_main.c.
Referenced by ExitLevel().
void G_matchInfoDump (unsigned int dwDumpType)
Dumps end-of-match info.
Parameters
dwDumpType
Definition at line 749 of file g_match.c.
Referenced by CheckIntermissionExit().
qboolean G_MatchOnePlayer (int * plist, char * err, size_t len)
G_MatchOnePlayer.
Parameters
[in] plist
[out] err
[in] len
Returns
Definition at line 54 of file g_cmds.c.
Referenced by G_PlaySound_Cmd(), Svcmd_Burn(), Svcmd_Die(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Pip(), and Svcmd_Unfreeze().
int G_MatchReset_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Match Restart.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 827 of file g_vote.c.
qboolean G_MatchString (const char * filter, const char * name, int casesensitive)
G_MatchString.
Parameters
[in] filter
[in] name
[in] casesensitive
Returns
Definition at line 1936 of file g_utils.c.
Referenced by G_Script_GetEventIndex(), and G_Script_ScriptRun().
int G_MaxAvailableAirstrikes (gentity_t * ent)
G_MaxAvailableAirstrikes.
Parameters
[in] ent
Returns
Definition at line 2387 of file g_weapon.c.
Referenced by G_AddAirstrikeToCounters().
int G_MaxAvailableArtillery (gentity_t * ent)
G_MaxAvailableArtillery.
Parameters
[in] ent
Returns
Definition at line 2413 of file g_weapon.c.
Referenced by G_AddArtilleryToCounters().
int G_ModelIndex (const char * name)
G_ModelIndex.
Parameters
[in] name
Returns
Definition at line 229 of file g_utils.c.
Referenced by _et_G_ModelIndex(), aagun_spawn(), FinishSpawningItem(), flak_spawn(), G_Script_ScriptParse(), G_ScriptAction_ChangeModel(), G_SpawnItem(), InitExplosive(), InitMover(), InitMoverRotate(), InitProp(), mg42_spawn(), misc_firetrails_think(), script_model_med_spawn(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_func_leaky(), SP_func_static(), SP_misc_constructiblemarker(), SP_misc_gamemodel(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_Props_Chair(), SP_Props_ChairChat(), SP_Props_ChairChatArm(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_props_decoration(), SP_props_decorBRUSH(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_footlocker(), SP_props_statue(), SP_props_statueBRUSH(), and SP_team_WOLF_checkpoint().
qboolean G_MoverPush (gentity_t * pusher, vec3_t move, vec3_t amove, gentity_t ** obstacle)
Objects need to be moved back on a failed push, otherwise riders would continue to slide.
Parameters
[in,out] pusher
[in] move
[in] amove
[in] obstacle
Returns
If qfalse, *obstacle will be the blocking entity
Definition at line 498 of file g_mover.c.
Referenced by G_MoverTeam(), and G_TagLinkEntity().
int G_Mute_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Player Mute.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 529 of file g_vote.c.
Referenced by Cmd_CallVote_f().
void G_MuteClient (void)
G_MuteClient.
Definition at line 795 of file g_referee.c.
int G_Mutespecs_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Mute Spectators.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 862 of file g_vote.c.
char* G_NewString (const char * string)
Builds a copy of the string, translating \n to real linefeeds so message texts can be multi-line.
Parameters
string
Returns
Definition at line 695 of file g_spawn.c.
Referenced by G_ParseField(), and SP_misc_beam().
int G_NextCampaign_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_NextCampaign_v.
Parameters
ent - unused
dwVoteIndex - unused
[in] arg
arg2 - unused
fRefereeCmd - unused
Returns
Definition at line 1854 of file g_vote.c.
int G_Nextmap_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Nextmap.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 891 of file g_vote.c.
void G_ParseCampaigns (void)
G_ParseCampaigns.
Definition at line 1713 of file g_utils.c.
Referenced by G_InitGame().
void G_ParseField (const char * key, const char * value, gentity_t * ent)
Takes a key/value pair and sets the binary values in a gentity.
Parameters
[in] key
[in] value
[in] ent
Definition at line 737 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues(), and G_SpawnGEntityFromSpawnVars().
void G_parseStats (const char * pszStatsInfo)
Parses weapon stat info for given ent The given string must be space delimited and contain only integers.
Parameters
pszStatsInfo
Definition at line 545 of file g_match.c.
Referenced by G_ReadSessionData().
void G_pause_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fPause)
Pause/unpause a match.
Parameters
[in] ent
[in] dwCommand
[in] fPause
Definition at line 298 of file g_cmds_ext.c.
gentity_t* G_PickTarget (const char * targetname)
Selects a random entity from among the targets.
Parameters
[in] targetname
Returns
Definition at line 566 of file g_utils.c.
Referenced by AimAtTarget(), FindIntermissionPoint(), ETInterface::GetAutoNavFeatures(), InitShooter_Finish(), locateCamera(), SP_info_player_deathmatch(), SP_team_CTF_bluespawn(), SP_team_CTF_redspawn(), target_relay_use(), target_teleporter_use(), and trigger_teleporter_touch().
void void G_PlayerBan (void)
G_PlayerBan.
Console admin commands
Definition at line 614 of file g_referee.c.
void G_players_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Show client info.
Parameters
[in] ent
dwCommand - unused
fDump - unused
Definition at line 376 of file g_cmds_ext.c.
void G_playersMessage (gentity_t * ent)
Player ID message stub.
Parameters
[in] ent
Definition at line 268 of file g_vote.c.
Referenced by G_Referee_v(), and G_Unreferee_v().
void G_PlaySound_Cmd (void)
G_PlaySound_Cmd.
Definition at line 185 of file g_cmds.c.
int G_Poll_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_Poll_v.
Parameters
ent - unused
dwVoteIndex - unused
[in] arg
[out] arg2
fRefereeCmd - unused
Returns
Definition at line 1935 of file g_vote.c.
Referenced by Cmd_CallVote_f().
gentity_t* G_PopupMessage (popupMessageType_t type)
G_PopupMessage.
Parameters
[in] type
Returns
Definition at line 1011 of file g_utils.c.
Referenced by G_PopupMessageForMines(), SetTeam(), Team_ReturnFlagSound(), Team_TouchEnemyFlag(), and Weapon_Engineer().
int G_PredictMissile (gentity_t * ent, int duration, vec3_t endPos, qboolean allowBounce)
G_PredictMissile.
Parameters
[in,out] ent is the character that is checking to see what the missile is going to do
[in] duration
[out] endPos
[in] allowBounce
Returns
qfalse if the missile won't explode, otherwise it'll return the time is it expected to explode
Definition at line 681 of file g_missile.c.
void G_PredictPmove (gentity_t * ent, float frametime)
Make use of the 'Pmove' functions to figure out where a player would have moved in the short amount of time indicated by frametime.
After the Pmove is complete, copy the values to the player's entity state, but then copy the original player state values back to the player state so that the player's movements aren't effected in any way.
The only Pmove functions used are PM_StepSlideMove() and PM_GroundTrace() since these are all that is needed for this short period of time. This means that a lot of movement types cannot be predicted and no prediction should be done for them See G_SkipCorrectionSafe()
Parameters
[in,out] ent
[in] frametime
Definition at line 960 of file g_antilag.c.
Referenced by ClientEndFrame().
void G_PreFilledMissileEntity (gentity_t * ent, int weaponNum, int realWeapon, int ownerNum, team_t teamNum, int clientNum, gentity_t * parent, const vec3_t start, const vec3_t dir)
G_PreFilledMissileEntity.
Parameters
[in] ent
[in] weaponNum
[in] realWeapon
[in] ownerNum
[in] teamNum
[in] clientNum
[in] parent
Definition at line 2806 of file g_misc.c.
Referenced by fire_flamechunk(), fire_missile(), and landmine_setup().
void G_PrintClientSpammyCenterPrint (int entityNum, const char * text)
G_PrintClientSpammyCenterPrint.
Parameters
[in] entityNum
[in] text
Definition at line 1814 of file g_utils.c.
Referenced by TryConstructing(), and Weapon_Engineer().
void G_PrintConfigs (gentity_t * ent)
G_PrintConfigs.
Parameters
[in] ent
Definition at line 70 of file g_config.c.
Referenced by G_Config_v().
void QDECL G_Printf (const char * fmt, ...)
Referenced by _et_G_LogPrint(), _et_gentity_set(), _et_trap_FS_Read(), AddIP(), AddMaxLivesGUID(), AddRemap(), alarmbox_updateparts(), Bot_Interface_ConsoleCommand(), Bot_Interface_Init(), CC_loadconfig(), CC_svcvar(), ClientForString(), ClientInactivityTimer(), ClientName(), ClientUserinfoChanged(), etpro_ScriptAction_SetValues(), FinishSpawningItem(), G_AddEvent(), G_Alloc(), G_CallSpawn(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_configSet(), G_Damage(), G_FindByTargetname(), G_GetPlayerByName(), G_GetPlayerByNum(), G_InitWorldSession(), G_LoadCampaignsFromFile(), G_loadMatchGame(), G_LoseSkillPoints(), G_Lua_CreateEntity(), G_LuaCall(), G_LuaInit(), G_LuaRunIsolated(), G_LuaStackDump(), G_LuaStartVM(), G_LuaStopVM(), G_MakeReferee(), G_makesc_cmd(), G_Mute_v(), G_MuteClient(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_ParseSettings(), G_PickTarget(), G_PlayerBan(), G_players_cmd(), G_PlaySound_Cmd(), G_PrintConfigs(), G_refHelp_cmd(), G_refMute_cmd(), G_RegisterCharacter(), G_RemoveReferee(), G_removesc_cmd(), G_Say(), G_Script_ActionForString(), G_Script_GetEventIndex(), G_Script_ScriptRun(), G_ScriptAction_Accum(), G_ScriptAction_Create(), G_ScriptAction_Cvar(), G_ScriptAction_Delete(), G_ScriptAction_GlobalAccum(), G_ScriptAction_PlayAnim(), G_ScriptAction_Print(), G_ScriptAction_PrintAccum(), G_ScriptAction_PrintGlobalAccum(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetState(), G_ScriptAction_StartAnimation(), G_ScriptAction_Trigger(), G_SendScore(), G_Spawn(), G_SpawnEntitiesFromString(), G_SpawnGEntityFromSpawnVars(), G_UnMute_v(), G_UnMuteClient(), G_UpdateCharacter(), G_UseTargets(), G_Voice(), GeoIP_open(), GeoIP_seek_record(), InitShooter(), landmine_setup(), locateCamera(), locateMaster(), misc_beam_start(), misc_spawner_think(), Omnibot_Load_PrintErr(), Omnibot_Load_PrintMsg(), player_die(), ETInterface::PrintError(), ETInterface::PrintMessage(), props_castlebed_touch(), props_locker_spawn_item(), reinforce(), SP_alarm_box(), SP_func_debris(), SP_func_timer(), SP_func_train(), SP_func_train_rotating(), SP_info_train_spline_main(), SP_misc_spawner(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_path_corner(), SP_path_corner_2(), SP_Props_Flipping_Table(), SP_Props_Locker_Tall(), SP_Props_Radio(), SP_Props_RadioSEVEN(), SP_props_snowGenerator(), SP_target_effect(), SP_target_location(), SP_target_teleporter(), SP_trigger_concussive_dust(), SP_trigger_multiple(), SP_trigger_push(), StringToFilter(), Svcmd_AddIP_f(), Svcmd_Burn(), Svcmd_Campaign_f(), Svcmd_CSInfo_f(), Svcmd_Die(), Svcmd_EntityList_f(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_GameMem_f(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Svcmd_ListCampaigns_f(), Svcmd_Pip(), Svcmd_RemoveIP_f(), Svcmd_RevivePlayer(), Svcmd_Unfreeze(), target_laser_start(), target_teleporter_use(), Team_ResetFlag(), Team_ReturnFlagSound(), TeamplayInfoMessage(), Think_SetupTrainTargets(), Think_SetupTrainTargets_rotating(), trigger_teleporter_touch(), Use_DamageInflictor(), Use_Target_Lock(), and Weapon_Artillery().
void G_printFull (const char * str, gentity_t * ent)
Simple alias for sure-fire print :)
Parameters
[in] str
[in] ent
Definition at line 96 of file g_match.c.
Referenced by G_delayPrint(), G_refLockTeams_cmd(), G_refSpeclockTeams_cmd(), G_specinvite_cmd(), G_speclock_cmd(), G_teamJoinCheck(), and G_teamready_cmd().
void G_printMatchInfo (gentity_t * ent)
Prints current player match info.
Parameters
[in] ent
Todo:
FIXME: put the pretty print on the client
Definition at line 591 of file g_match.c.
Referenced by G_matchInfoDump(), and G_scores_cmd().
void G_ProcessIPBans (void)
G_ProcessIPBans.
Definition at line 376 of file g_svcmds.c.
Referenced by G_InitGame().
void G_ProcessTagConnect (gentity_t * ent, qboolean clearAngles)
G_ProcessTagConnect.
Tag connections
Parameters
[in,out] ent
[in] clearAngles
Definition at line 1205 of file g_utils.c.
Referenced by Do_Activate_f(), G_ScriptAction_TagConnect(), and misc_firetrails_think().
qboolean G_RadiusDamage (vec3_t origin, gentity_t * inflictor, gentity_t * attacker, float damage, float radius, gentity_t * ignore, meansOfDeath_t mod)
G_RadiusDamage.
Parameters
[in] origin
[in] inflictor
[in] attacker
[in] damage
[in] radius
[in] ignore
[in] mod
Returns
Definition at line 1990 of file g_combat.c.
Referenced by func_explosive_explode(), G_RealExplodedMissile(), target_effect(), and target_explosion_use().
void G_RailBox (vec_t * origin, vec_t * mins, vec_t * maxs, vec_t * color, int index)
G_RailBox.
Parameters
[in] origin
[in] mins
[in] maxs
[in] color
[in] index
Definition at line 1786 of file g_combat.c.
Referenced by ClientEndFrame(), ClientThink_real(), G_DrawEntBBox(), IsHeadShot(), and IsLegShot().
void G_RailTrail (vec_t * start, vec_t * end, vec_t * color)
Definition at line 1764 of file g_combat.c.
Referenced by IsHeadShot(), and IsLegShot().
void G_ReAdjustSingleClientPosition (gentity_t * ent)
G_ReAdjustSingleClientPosition.
Parameters
[in,out] ent
Definition at line 450 of file g_antilag.c.
Referenced by G_AdjustClientPositions(), IsHeadShot(), IsLegShot(), and player_die().
void G_ReadSessionData (gclient_t * client)
Called on a reconnect.
Parameters
[in] client
Definition at line 260 of file g_session.c.
Referenced by ClientConnect().
void G_ready_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Sets a player's "ready" status.
Parameters
[in,out] ent
[in] dwCommand
[in] fDump
Definition at line 561 of file g_cmds_ext.c.
qboolean G_readyMatchState (void)
Checks ready states to start/stop the sequence to get the match rolling.
Returns
Definition at line 1828 of file g_team.c.
Referenced by CheckWolfMP(), G_ready_cmd(), G_refAllReady_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), and G_teamready_cmd().
void G_ref_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Request for ref status or lists ref commands.
Parameters
[in,out] ent
dwCommand - unused
fValue - unused
Definition at line 170 of file g_referee.c.
void G_refAllReady_cmd (gentity_t * ent)
Readies all players in the game.
Parameters
[in] ent
Definition at line 237 of file g_referee.c.
Referenced by G_refCommandCheck(), G_StartMatch_v(), and Svcmd_StartMatch_f().
int G_refClientnumForName (gentity_t * ent, const char * name)
G_refClientnumForName.
Utility
Parameters
[in] ent
[in] name
Returns
Definition at line 1002 of file g_referee.c.
Referenced by Cmd_Ignore_f(), Cmd_UnIgnore_f(), G_MakeReferee(), G_MuteClient(), G_PlayerBan(), G_refWarning_cmd(), G_RemoveReferee(), and G_UnMuteClient().
qboolean G_refCommandCheck (gentity_t * ent, const char * cmd)
Parses for a referee command. ref arg allows for the server console to utilize all referee commands (ent == NULL)
Parameters
[in] ent
[in] cmd
Returns
Definition at line 46 of file g_referee.c.
Referenced by G_ref_cmd(), and Svcmd_Ref_f().
int G_Referee_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Referee voting.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Todo:
: Differentiate voted refs from passworded refs
Definition at line 987 of file g_vote.c.
void G_refHelp_cmd (gentity_t * ent)
Lists ref commands.
Parameters
[in] ent
Definition at line 132 of file g_referee.c.
Referenced by G_ref_cmd(), G_refCommandCheck(), and Svcmd_Ref_f().
void G_refLockTeams_cmd (gentity_t * ent, qboolean fLock)
Changes team lock status.
Parameters
[in] ent
[in] fLock
Definition at line 269 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refLogout_cmd (gentity_t * ent)
G_refLogout_cmd.
Parameters
[in] ent
Definition at line 580 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refMakeShoutcaster_cmd (gentity_t * ent)
G_refMakeShoutcaster_cmd.
Parameters
[in] ent
Definition at line 899 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refMute_cmd (gentity_t * ent, qboolean mute)
(Un)Mutes a player
Parameters
[in] ent
[in] mute
Definition at line 532 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refPause_cmd (gentity_t * ent, qboolean fPause)
Pause/unpause a match.
Parameters
[in] ent
[in] fPause
Definition at line 297 of file g_referee.c.
Referenced by G_pause_cmd(), and G_refCommandCheck().
void G_refPlayerPut_cmd (gentity_t * ent, team_t team_id)
Puts a player on a team.
Parameters
[in] ent
[in] team_id
Definition at line 346 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refPrintf (gentity_t * ent, const char * fmt, ...)
Referenced by Cmd_CallVote_f(), G_Config_v(), G_Gametype_v(), G_GametypeList(), G_isValidConfig(), G_Kick_v(), G_LuaStatus(), G_Mute_v(), G_Nextmap_v(), G_playersMessage(), G_PrintConfigs(), G_Referee_v(), G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), G_StartMatch_v(), G_SwapTeams_v(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_voteCurrentSetting(), G_voteDescription(), G_voteDisableMessage(), G_voteHelp(), G_voteProcessOnOff(), G_WarmupDamageTypeList(), and G_Warmupfire_v().
void G_refRemove_cmd (gentity_t * ent)
Removes a player from a team.
Parameters
[in] ent
Definition at line 403 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refRemoveShoutcaster_cmd (gentity_t * ent)
G_refRemoveShoutcaster_cmd.
Parameters
[in] ent
Definition at line 951 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refSpeclockTeams_cmd (gentity_t * ent, qboolean fLock)
Changes team spectator lock status.
Parameters
ent - unused
[in] fLock
Definition at line 449 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refWarmup_cmd (gentity_t * ent)
G_refWarmup_cmd.
Parameters
[in] ent
Definition at line 476 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refWarning_cmd (gentity_t * ent)
G_refWarning_cmd.
Parameters
[in] ent
Definition at line 496 of file g_referee.c.
Referenced by G_refCommandCheck().
qboolean G_RegisterCharacter (const char * characterFile, bg_character_t * character)
G_RegisterCharacter.
Parameters
[in] characterFile
[in] character
Returns
Definition at line 234 of file g_character.c.
Referenced by G_RegisterPlayerClasses(), and G_UpdateCharacter().
void G_RegisterFireteam (int entityNum)
Should be the only function that ever creates a fireteam.
Parameters
[in] entityNum
Definition at line 332 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), and Cmd_Vote_f().
void G_RegisterPlayerClasses (void)
G_RegisterPlayerClasses.
Definition at line 271 of file g_character.c.
Referenced by G_InitGame().
void G_ReloadConfig (void)
G_ReloadConfig.
Definition at line 552 of file g_config.c.
void G_RemoveAllShoutcasters (void)
G_RemoveAllShoutcasters.
Definition at line 769 of file g_referee.c.
Referenced by G_UpdateCvars().
void G_RemoveClientFromFireteams (int entityNum, qboolean update, qboolean print)
The only way a client should be removed from a fireteam.
Parameters
[in] entityNum
[in] update
[in] print
Definition at line 518 of file g_fireteams.c.
Referenced by ClientDisconnect(), Cmd_FireTeam_MP_f(), G_DestroyFireteam(), G_KickFireTeamPlayer(), G_shuffleTeamsXP(), and SetTeam().
void G_RemoveConfigstringIndex (const char * name, int start, int max)
Prevent player always mounting the last gun used, on multiple tank maps. Ported from the Bugfix project (#087)
Parameters
[in] name
[in] start
[in] max
Definition at line 190 of file g_utils.c.
Referenced by G_LeaveTank().
void G_RemoveFromAllIgnoreLists (int clientNum)
G_RemoveFromAllIgnoreLists.
Parameters
[in] clientNum
Definition at line 41 of file g_buddy_list.c.
Referenced by ClientDisconnect().
void G_RemoveReferee (void)
G_RemoveReferee.
Definition at line 692 of file g_referee.c.
void G_removesc_cmd (void)
Remove shoutcaster command.
Definition at line 777 of file g_cmds_ext.c.
void G_RemoveShoutcaster (gentity_t * ent)
G_RemoveShoutcaster.
Parameters
[in] ent
Definition at line 749 of file g_referee.c.
Referenced by G_refRemoveShoutcaster_cmd(), G_removesc_cmd(), and G_sclogout_cmd().
void G_removeSpecInvite (int team)
Removes everyone's specinvite for a particular team.
Parameters
[in] team
Note
Unused
Definition at line 2042 of file g_team.c.
void G_ResetMarkers (gentity_t * ent)
G_ResetMarkers.
Parameters
[in,out] ent
Definition at line 544 of file g_antilag.c.
Referenced by ClientSpawn(), and TeleportPlayer().
void G_resetModeState (void)
G_resetModeState.
Definition at line 999 of file g_match.c.
Referenced by Svcmd_ResetMatch_f(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), and Svcmd_SwapTeams_f().
void G_ResetRemappedShaders (void)
G_ResetRemappedShaders.
Definition at line 92 of file g_utils.c.
Referenced by _et_G_ResetRemappedShaders(), and G_InitGame().
void G_resetRoundState (void)
G_resetRoundState.
Definition at line 983 of file g_match.c.
Referenced by Svcmd_ResetMatch_f(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), and Svcmd_SwapTeams_f().
void G_ResetTeamMapData (void)
G_ResetTeamMapData.
Definition at line 452 of file g_teammapdata.c.
Referenced by ClientSpawn(), and G_InitGame().
void G_ResetTempTraceIgnoreEnts (void)
G_ResetTempTraceIgnoreEnts.
Definition at line 2476 of file g_misc.c.
Referenced by DynaFree(), G_RealExplodedMissile(), G_Trace(), trap_EngineerTrace(), and Weapon_Engineer().
void G_ResetXP (gentity_t * ent)
G_ResetXP.
Parameters
[in,out] ent
Definition at line 336 of file g_stats.c.
Referenced by _et_G_ResetXP().
int G_RestartCampaign_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_RestartCampaign_v.
Parameters
ent - unused
dwVoteIndex - unused
[in] arg
arg2 - unused
fRefereeCmd - unused
Returns
Definition at line 1897 of file g_vote.c.
void G_RunClient (gentity_t * ent)
G_RunClient.
Parameters
[in,out] ent Entity
Definition at line 1672 of file g_active.c.
Referenced by G_RunEntity().
void G_RunFlamechunk (gentity_t * ent)
G_RunFlamechunk.
Parameters
[in,out] ent
Definition at line 924 of file g_missile.c.
Referenced by G_RunEntity().
void G_RunItem (gentity_t * ent)
Run item.
Parameters
[in,out] ent
Todo:
: avoid this for stationary?
Definition at line 1224 of file g_items.c.
Referenced by G_RunEntity().
void G_RunMissile (gentity_t * ent)
G_RunMissile.
Parameters
[in,out] ent
Definition at line 438 of file g_missile.c.
Referenced by G_RunEntity().
void G_RunMover (gentity_t * ent)
G_RunMover.
Parameters
[in,out] ent
Definition at line 833 of file g_mover.c.
Referenced by G_RunEntity().
void G_RunThink (gentity_t * ent)
Runs thinking code for this frame if necessary.
Parameters
[in,out] ent
Definition at line 4472 of file g_main.c.
Referenced by G_RunEntity(), G_RunFlamechunk(), G_RunItem(), G_RunMissile(), and G_RunMover().
void G_Say (gentity_t * ent, gentity_t * target, int mode, const char * chatText)
G_Say.
Parameters
[in] ent
[in] target
[in] mode
[in] chatText
Definition at line 2661 of file g_cmds.c.
Referenced by _et_G_Say(), Cmd_Say_f(), and G_Voice().
void G_say_teamnl_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Team chat w/no location info.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 628 of file g_cmds_ext.c.
void G_SayTo (gentity_t * ent, gentity_t * other, int mode, int color, const char * name, const char * message, qboolean localize)
G_SayTo.
Parameters
[in] ent
[in] other
[in] mode
[in] color
[in] name
[in] message
[in] localize
Definition at line 2575 of file g_cmds.c.
Referenced by G_Say().
void G_sclogin_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Request for shoutcaster status.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 639 of file g_cmds_ext.c.
void G_sclogout_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Removes shoutcaster status.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 686 of file g_cmds_ext.c.
void G_scores_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Shows match stats to the requesting client.
Parameters
[in] ent
dwCommand - unused
fValue - unused
Definition at line 833 of file g_cmds_ext.c.
void G_Script_ScriptEvent (gentity_t * ent, const char * eventStr, const char * params)
An event has occured, for which a script may exist.
Parameters
[in] ent
[in] eventStr
[in] params
Definition at line 725 of file g_script.c.
Referenced by AutoBuildConstruction(), CheckExitRules(), checkpoint_spawntouch(), checkpoint_touch(), ClientSpawn(), Do_Activate_f(), DynaFree(), func_constructible_explode(), func_constructible_underconstructionthink(), func_explosive_explode(), func_explosive_use(), G_CallSpawn(), G_Damage(), G_LeaveTank(), G_RealExplodedMissile(), G_ScriptAction_Accum(), G_ScriptAction_Cvar(), G_ScriptAction_GlobalAccum(), G_ScriptAction_Trigger(), LaunchItem(), multi_trigger(), script_mover_die(), script_mover_use(), target_script_trigger_use(), Team_DroppedFlagThink(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), Touch_flagonly(), Touch_flagonly_multiple(), TryConstructing(), use_invisible_user(), and Weapon_Engineer().
void G_Script_ScriptLoad (void)
Loads the script for the current level into the buffer.
Definition at line 269 of file g_script.c.
Referenced by G_InitGame().
void G_Script_ScriptParse (gentity_t * ent)
Parses the script for the given entity.
Parameters
[in,out] ent
Definition at line 344 of file g_script.c.
Referenced by G_CallSpawn().
qboolean G_Script_ScriptRun (gentity_t * ent)
G_Script_ScriptRun.
Parameters
[in,out] ent
Returns
qtrue if the script completed
Definition at line 795 of file g_script.c.
Referenced by ClientEndFrame(), G_RunEntity(), G_RunThink(), and G_Script_ScriptChange().
qboolean G_ScriptAction_AbortIfNotSinglePlayer (gentity_t * ent, char * params)
G_ScriptAction_AbortIfNotSinglePlayer.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 4720 of file g_script_actions.c.
qboolean G_ScriptAction_AbortIfWarmup (gentity_t * ent, char * params)
G_ScriptAction_AbortIfWarmup.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 4703 of file g_script_actions.c.
qboolean G_ScriptAction_AbortMove (gentity_t * ent, char * params)
G_ScriptAction_AbortMove.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 959 of file g_script_actions.c.
qboolean G_ScriptAction_Accum (gentity_t * ent, char * params)
G_ScriptAction_Accum.
syntax: accum <buffer_index> <command> <paramater...>
Commands:
accum <n> inc <m> accum <n> abort_if_less_than <m> accum <n> abort_if_greater_than <m> accum <n> abort_if_not_equal <m> accum <n> abort_if_equal <m> accum <n> set <m> accum <n> random <m> accum <n> bitset <m> accum <n> bitreset <m> accum <n> abort_if_bitset <m> accum <n> abort_if_not_bitset <m> accum <n> trigger_if_equal <m> <s> <t> accum <n> wait_while_equal <m>
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2418 of file g_script_actions.c.
qboolean G_ScriptAction_AddTankAmmo (gentity_t * ent, char * params)
G_ScriptAction_AddTankAmmo.
Parameters
ent - unused
[in] params
Returns
Definition at line 1221 of file g_script_actions.c.
qboolean G_ScriptAction_AddTeamVoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_AddTeamVoiceAnnounce.
syntax: wm_addteamvoiceannounce
Parameters
ent - unused
[in] params
Returns
Definition at line 3624 of file g_script_actions.c.
qboolean G_ScriptAction_AlertEntity (gentity_t * ent, char * params)
Modified to target multiple entities with the same targetname.
syntax: alertentity <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2222 of file g_script_actions.c.
qboolean G_ScriptAction_AlliedRespawntime (gentity_t * ent, char * params)
G_ScriptAction_AlliedRespawntime.
syntax: wm_allied_respawntime <seconds>
Parameters
ent - unused
[in] params
Returns
Definition at line 3275 of file g_script_actions.c.
qboolean G_ScriptAction_AllowTankEnter (gentity_t * ent, char * params)
G_ScriptAction_AllowTankEnter.
Parameters
ent - unused
[in] params
Returns
Definition at line 1154 of file g_script_actions.c.
qboolean G_ScriptAction_AllowTankExit (gentity_t * ent, char * params)
G_ScriptAction_AllowTankExit.
syntax: allowtankexit <yes|on|no|off>
Parameters
ent - unused
[in] params
Returns
Definition at line 1126 of file g_script_actions.c.
qboolean G_ScriptAction_Announce (gentity_t * ent, char * params)
G_ScriptAction_Announce.
syntax: wm_announce <"text to send to all clients">
Parameters
[in] ent
[in] params
Returns
Definition at line 3827 of file g_script_actions.c.
qboolean G_ScriptAction_Announce_Icon (gentity_t * ent, char * params)
G_ScriptAction_Announce_Icon.
syntax: wm_announce_icon <icon number> <"text to send to all clients">
Parameters
[in] ent
[in] params
Returns
Definition at line 3781 of file g_script_actions.c.
qboolean G_ScriptAction_AttatchToTrain (gentity_t * ent, char * params)
G_ScriptAction_AttatchToTrain.
Parameters
[out] ent
[in] params
Returns
Todo:
: optimize ... is this used for players?
Definition at line 447 of file g_script_actions.c.
qboolean G_ScriptAction_AxisRespawntime (gentity_t * ent, char * params)
G_ScriptAction_AxisRespawntime.
syntax: wm_axis_respawntime <seconds>
Parameters
ent - unused
[in] params
Returns
Definition at line 3246 of file g_script_actions.c.
qboolean G_ScriptAction_ChangeModel (gentity_t * ent, char * params)
G_ScriptAction_ChangeModel.
Parameters
[out] ent
[in] params
Returns
Definition at line 226 of file g_script_actions.c.
qboolean G_ScriptAction_Construct (gentity_t * ent, char * params)
G_ScriptAction_Construct.
Parameters
ent - unused
[in] params
Returns
Definition at line 4243 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleChargeBarReq (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleChargeBarReq.
syntax: constructible_chargebarreq <float:fraction>
Parameters
[in] ent
[in] params
Returns
Definition at line 4304 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleClass (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleClass.
syntax: constructible_class <int:class>
Parameters
[out] ent
params
Returns
Definition at line 4271 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleConstructXPBonus (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleConstructXPBonus.
syntax: constructible_constructxpbonus <int:xppoints>
Parameters
[out] ent
[in] params
Returns
Definition at line 4333 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleDestructXPBonus (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleDestructXPBonus.
syntax: constructible_destructxpbonus <int:xppoints>
Parameters
[out] ent
[in] params
Returns
Definition at line 4362 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleDuration (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleDuration.
syntax: constructible_duration <int:duration>
Parameters
[out] ent
[in] params
Returns
Definition at line 4451 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleHealth (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleHealth.
syntax: constructible_health <int:health>
Parameters
[out] ent
[in] params
Returns
Definition at line 4391 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleWeaponclass (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleWeaponclass.
syntax: constructible_weaponclass <int:class>
Parameters
[out] ent
[in] params
Returns
Definition at line 4421 of file g_script_actions.c.
qboolean G_ScriptAction_Create (gentity_t * ent, char * params)
Added for compatability with etpro map scripts.
Parameters
[in] ent
[in] params
Returns
Definition at line 5094 of file g_script_actions.c.
qboolean G_ScriptAction_Cvar (gentity_t * ent, char * params)
G_ScriptAction_Cvar.
syntax: cvar <cvarName> <operation> <value>
Parameters
[in,out] ent
[in] params
Returns
Todo:
: cvarValue is never read
Todo:
: cvarValue is never read
Todo:
: cvarValue is never read
Todo:
: cvarValue is never read
Definition at line 4480 of file g_script_actions.c.
qboolean G_ScriptAction_Delete (gentity_t * ent, char * params)
Delete entities that match all the criteria provided in "params".
Parameters
ent - unused
[in] params
Returns
Definition at line 4942 of file g_script_actions.c.
Referenced by _et_G_Lua_DeleteEntity().
qboolean G_ScriptAction_DisableMessage (gentity_t * ent, char * params)
G_ScriptAction_DisableMessage - obsolete function used for old bot ai.
Parameters
ent
[in] params
Returns
Definition at line 1269 of file g_script_actions.c.
qboolean G_ScriptAction_DisableSpeaker (gentity_t * ent, char * params)
G_ScriptAction_DisableSpeaker.
syntax: disablespeaker <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2321 of file g_script_actions.c.
qboolean G_ScriptAction_EnableSpeaker (gentity_t * ent, char * params)
G_ScriptAction_EnableSpeaker.
syntax: enablespeaker <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2361 of file g_script_actions.c.
qboolean G_ScriptAction_EndRound (gentity_t * ent, char * params)
G_ScriptAction_EndRound.
syntax: wm_endround <>
Parameters
ent - unused
params - unused
Returns
Definition at line 3861 of file g_script_actions.c.
qboolean G_ScriptAction_EntityScriptName (gentity_t * ent, char * params)
G_ScriptAction_EntityScriptName.
Parameters
ent - unused
[in] params
Returns
Definition at line 3231 of file g_script_actions.c.
qboolean G_ScriptAction_FaceAngles (gentity_t * ent, char * params)
The entity will face the given angles, taking <duration> to get their. If the GOTOTIME is given instead of a timed duration, the duration calculated from the last gotomarker command will be used instead.
syntax: faceangles <pitch> <yaw> <roll> <duration\/GOTOTIME> [ACCEL\/DECCEL]
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2976 of file g_script_actions.c.
qboolean G_ScriptAction_FadeAllSounds (gentity_t * ent, char * params)
Fades all sounds up or down, going from the current level to max or zero in 'time' milliseconds.
syntax: fadeallsounds [UP\/DOWN] time
Parameters
ent - unused
[in] params
Returns
Definition at line 1903 of file g_script_actions.c.
qboolean G_ScriptAction_FollowPath (gentity_t * ent, char * params)
G_ScriptAction_FollowPath.
Parameters
[in,out] ent
[in] params
Returns
Definition at line 296 of file g_script_actions.c.
qboolean G_ScriptAction_FollowSpline (gentity_t * ent, char * params)
G_ScriptAction_FollowSpline.
syntax: followspline <targetname> <speed> [wait]
Parameters
[in,out] ent
[in] params
Returns
Note
Speed may be modified to round the duration to the next 50ms for smooth transitions
Definition at line 731 of file g_script_actions.c.
qboolean G_ScriptAction_FreezeAnimation (gentity_t * ent, char * params)
G_ScriptAction_FreezeAnimation.
Parameters
[out] ent
params - unused
Returns
Definition at line 487 of file g_script_actions.c.
qboolean G_ScriptAction_GlobalAccum (gentity_t * ent, char * params)
G_ScriptAction_GlobalAccum.
syntax: globalAccum <buffer_index> <command> <paramater...>
Commands:
globalAccum <n> inc <m> globalAccum <n> abort_if_less_than <m> globalAccum <n> abort_if_greater_than <m> globalAccum <n> abort_if_not_equal <m> globalAccum <n> abort_if_equal <m> globalAccum <n> set <m> globalAccum <n> random <m> globalAccum <n> bitset <m> globalAccum <n> bitreset <m> globalAccum <n> abort_if_bitset <m> globalAccum <n> abort_if_not_bitset <m> globalAccum <n> trigger_if_equal <m> <s> <t> globalAccum <n> wait_while_equal <m>
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2702 of file g_script_actions.c.
qboolean G_ScriptAction_GotoMarker (gentity_t * ent, char * params)
G_ScriptAction_GotoMarker.
syntax: gotomarker <targetname> <speed> [accel\/deccel] [turntotarget] [wait] [relative <position>]
Parameters
[in,out] ent
[in] params
Returns
Note
Speed may be modified to round the duration to the next 50ms for smooth transitions
Todo:
: optimize ... is this used for players?
Todo:
: optimize ... is this used for players?
Definition at line 1376 of file g_script_actions.c.
Referenced by G_Script_ScriptRun().
qboolean G_ScriptAction_Halt (gentity_t * ent, char * params)
Stop moving.
syntax: halt
Parameters
[in,out] ent
params - unused
Returns
Definition at line 3178 of file g_script_actions.c.
qboolean G_ScriptAction_Kill (gentity_t * ent, char * params)
G_ScriptAction_Kill.
Parameters
[in] ent
[in] params
Returns
Definition at line 1297 of file g_script_actions.c.
qboolean G_ScriptAction_MusicFade (gentity_t * ent, char * params)
G_ScriptAction_MusicFade.
Parameters
ent - unused
[in] params
Returns
Definition at line 2050 of file g_script_actions.c.
qboolean G_ScriptAction_MusicPlay (gentity_t * ent, char * params)
G_ScriptAction_MusicPlay.
Parameters
ent - unused
[in] params
Returns
Definition at line 1981 of file g_script_actions.c.
qboolean G_ScriptAction_MusicQueue (gentity_t * ent, char * params)
G_ScriptAction_MusicQueue.
Parameters
ent - unused
[in] params
Returns
Definition at line 2027 of file g_script_actions.c.
qboolean G_ScriptAction_MusicStart (gentity_t * ent, char * params)
G_ScriptAction_MusicStart.
Parameters
ent - unused
[in] params
Returns
See also
GS Copied in code from old source for mu_start, mu_play & mu_stop
Definition at line 1951 of file g_script_actions.c.
qboolean G_ScriptAction_MusicStop (gentity_t * ent, char * params)
G_ScriptAction_MusicStop.
Parameters
ent - unused
[in] params
Returns
Definition at line 2005 of file g_script_actions.c.
qboolean G_ScriptAction_NumberofObjectives (gentity_t * ent, char * params)
G_ScriptAction_NumberofObjectives.
syntax: wm_number_of_objectives <number>
Parameters
ent - unused
[in] params
Returns
Definition at line 3304 of file g_script_actions.c.
qboolean G_ScriptAction_ObjectiveStatus (gentity_t * ent, char * params)
G_ScriptAction_ObjectiveStatus.
syntax: wm_objective_status <objective_number> <team> <status>
Parameters
[in] ent
[in] params
Returns
Definition at line 3394 of file g_script_actions.c.
qboolean G_ScriptAction_PlayAnim (gentity_t * ent, char * params)
G_ScriptAction_PlayAnim.
syntax: playanim <startframe> <endframe> [looping <FOREVER\/duration>] [rate <FPS>]
Parameters
[in,out] ent
[in] params
Returns
Note
All source animations must be at 20fps
Definition at line 2088 of file g_script_actions.c.
Referenced by G_Script_ScriptRun().
qboolean G_ScriptAction_PlaySound (gentity_t * ent, char * params)
Currently only allows playing on the VOICE channel, unless you use a sound script. Use the optional LOOPING paramater to attach the sound to the entities looping channel. syntax: playsound <soundname OR scriptname> [LOOPING].
Parameters
[in,out] ent
[in] params
Returns
Definition at line 1839 of file g_script_actions.c.
qboolean G_ScriptAction_Print (gentity_t * ent, char * params)
Mostly for debugging purposes.
syntax: print <text>
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2930 of file g_script_actions.c.
qboolean G_ScriptAction_PrintAccum (gentity_t * ent, char * params)
Prints out the value of accum 'accumNumber'.
syntax: printaccum <accumNumber>
Parameters
[in] ent
[in] params
Returns
Definition at line 4173 of file g_script_actions.c.
qboolean G_ScriptAction_PrintGlobalAccum (gentity_t * ent, char * params)
prints out the value of global accum 'globalaccumnumber'
syntax: printGlobalAccum <globalaccumnumber>
Parameters
ent - unused
[in] params
Returns
Definition at line 4208 of file g_script_actions.c.
qboolean G_ScriptAction_RemoveEntity (gentity_t * ent, char * params)
G_ScriptAction_RemoveEntity.
syntax: remove
Parameters
[out] ent
params - unused
Returns
Definition at line 3932 of file g_script_actions.c.
qboolean G_ScriptAction_RemoveTeamVoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_RemoveTeamVoiceAnnounce.
Parameters
ent - unused
[in] params
Returns
Definition at line 3683 of file g_script_actions.c.
qboolean G_ScriptAction_RepairMG42 (gentity_t * ent, char * params)
G_ScriptAction_RepairMG42.
syntax: repairmg42 <target>
Parameters
[in] ent
[in] params
Returns
Definition at line 4064 of file g_script_actions.c.
qboolean G_ScriptAction_ResetScript (gentity_t * ent, char * params)
Causes any currently running scripts to abort, in favour of the current script.
Parameters
[in] ent
params - unused
Returns
Definition at line 3110 of file g_script_actions.c.
qboolean G_ScriptAction_SetAutoSpawn (gentity_t * ent, char * params)
G_ScriptAction_SetAutoSpawn.
Parameters
ent - unused
[in] params
Returns
Definition at line 177 of file g_script_actions.c.
qboolean G_ScriptAction_SetChargeTimeFactor (gentity_t * ent, char * params)
syntax: setchargetimefactor <team> <class> <factor> team: 0 = axis, 1 = allies
Parameters
ent - unused
[in] params
Returns
Definition at line 993 of file g_script_actions.c.
qboolean G_ScriptAction_SetDamagable (gentity_t * ent, char * params)
G_ScriptAction_SetDamagable.
Parameters
ent - unused
[in] params
Returns
Definition at line 3946 of file g_script_actions.c.
qboolean G_ScriptAction_SetDebugLevel (gentity_t * ent, char * params)
G_ScriptAction_SetDebugLevel.
Parameters
ent - unused
[in] params
Returns
Definition at line 3461 of file g_script_actions.c.
qboolean G_ScriptAction_SetDefendingTeam (gentity_t * ent, char * params)
Sets defending team for stopwatch mode.
syntax: wm_set_objective_status <status> status: 0==axis, 1==allies
Parameters
ent - unused
[in] params
Returns
Definition at line 3585 of file g_script_actions.c.
qboolean G_ScriptAction_SetGlobalFog (gentity_t * ent, char * params)
G_ScriptAction_SetGlobalFog.
syntax: setglobalfog <bool:restore> <int:duration> [float:r] [float:g] [float:b] [float:depthForOpaque]
Parameters
ent - unused
[in] params
Returns
Definition at line 1319 of file g_script_actions.c.
Referenced by _et_G_SetGlobalFog().
qboolean G_ScriptAction_SetHQStatus (gentity_t * ent, char * params)
G_ScriptAction_SetHQStatus.
syntax: sethqstatus <team> <status>
Parameters
ent - unused
[in] params
Returns
Definition at line 4122 of file g_script_actions.c.
qboolean G_ScriptAction_SetMainObjective (gentity_t * ent, char * params)
syntax: wm_set_main_objective <objective_targetname> <team>
Parameters
ent - unused
params
Returns
true or aborts
Todo:
check for param is number to distinguish between old and new wm_set_main_objective cmd - throw next commented G_Error
Todo:
throw this if we can't find the target by name
Definition at line 3338 of file g_script_actions.c.
qboolean G_ScriptAction_SetModelFromBrushmodel (gentity_t * ent, char * params)
G_ScriptAction_SetModelFromBrushmodel.
Parameters
[out] ent
[in] params
Returns
Definition at line 56 of file g_script_actions.c.
qboolean G_ScriptAction_SetPosition (gentity_t * ent, char * params)
G_ScriptAction_SetPosition.
Parameters
[in] ent
[in] params
Returns
Todo:
: optimize ... is this used for players?
Definition at line 135 of file g_script_actions.c.
qboolean G_ScriptAction_SetRotation (gentity_t * ent, char * params)
G_ScriptAction_SetRotation.
Parameters
[in,out] ent
[in] params
Returns
Definition at line 675 of file g_script_actions.c.
qboolean G_ScriptAction_SetRoundTimelimit (gentity_t * ent, char * params)
G_ScriptAction_SetRoundTimelimit.
syntax: wm_set_round_timelimit <number>
Parameters
ent - unused
[in] params
Returns
Definition at line 3880 of file g_script_actions.c.
qboolean G_ScriptAction_SetSpeed (gentity_t * ent, char * params)
G_ScriptAction_SetSpeed.
Parameters
[in,out] ent
[in] params
Returns
Definition at line 614 of file g_script_actions.c.
qboolean G_ScriptAction_SetState (gentity_t * ent, char * params)
G_ScriptAction_SetState.
syntax: remove
Parameters
ent - unused
[in] params
Returns
Definition at line 3985 of file g_script_actions.c.
qboolean G_ScriptAction_SetTankAmmo (gentity_t * ent, char * params)
G_ScriptAction_SetTankAmmo.
Parameters
ent - unused
[in] params
Returns
Definition at line 1182 of file g_script_actions.c.
qboolean G_ScriptAction_SetWinner (gentity_t * ent, char * params)
G_ScriptAction_SetWinner.
syntax: wm_setwinner <team> team: 0==AXIS, 1==ALLIED
Parameters
ent - unused
[in] params
Returns
Todo:
: never read
Definition at line 3540 of file g_script_actions.c.
qboolean G_ScriptAction_ShaderRemap (gentity_t * ent, char * params)
G_ScriptAction_ShaderRemap.
Parameters
ent - unused
[in] params
Returns
Definition at line 252 of file g_script_actions.c.
qboolean G_ScriptAction_ShaderRemapFlush (gentity_t * ent, char * params)
G_ScriptAction_ShaderRemapFlush.
Parameters
ent - unused
params - unused
Returns
Definition at line 284 of file g_script_actions.c.
qboolean G_ScriptAction_SpawnRubble (gentity_t * ent, char * params)
G_ScriptAction_SpawnRubble.
Debris test
syntax: spawnrubble <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 1100 of file g_script_actions.c.
qboolean G_ScriptAction_StartAnimation (gentity_t * ent, char * params)
G_ScriptAction_StartAnimation.
Parameters
[out] ent
[in] params
Returns
Definition at line 513 of file g_script_actions.c.
qboolean G_ScriptAction_StopRotation (gentity_t * ent, char * params)
G_ScriptAction_StopRotation.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 710 of file g_script_actions.c.
qboolean G_ScriptAction_StopSound (gentity_t * ent, char * params)
Stops any looping sounds for this entity.
syntax: stopsound
Parameters
ent
params
Returns
Definition at line 3219 of file g_script_actions.c.
qboolean G_ScriptAction_TagConnect (gentity_t * ent, char * params)
Connect this entity onto the tag of another entity.
syntax: attachtotag <targetname\/scriptname> <tagname>
Parameters
[out] ent
[in] params
Returns
Todo:
: optimize ... is this used for players?
Definition at line 3127 of file g_script_actions.c.
qboolean G_ScriptAction_TeamVoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_TeamVoiceAnnounce.
syntax: wm_teamvoiceannounce <team> <soundname>
Parameters
[in] ent
[in] params
Returns
Definition at line 3730 of file g_script_actions.c.
qboolean G_ScriptAction_ToggleSpeaker (gentity_t * ent, char * params)
G_ScriptAction_ToggleSpeaker.
syntax: togglespeaker <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2281 of file g_script_actions.c.
qboolean G_ScriptAction_Trigger (gentity_t * ent, char * params)
Calls the specified trigger for the given ai character or script entity.
syntax: trigger <aiName\/scriptName> <trigger>
Parameters
[in] ent
[in] params
Returns
Definition at line 1707 of file g_script_actions.c.
qboolean G_ScriptAction_UnFreezeAnimation (gentity_t * ent, char * params)
G_ScriptAction_UnFreezeAnimation.
Parameters
[out] ent
params - unused
Returns
Definition at line 500 of file g_script_actions.c.
qboolean G_ScriptAction_VoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_VoiceAnnounce.
Parameters
ent - unused
[in] params
Returns
Definition at line 3493 of file g_script_actions.c.
qboolean G_ScriptAction_Wait (gentity_t * ent, char * params)
G_ScriptAction_Wait.
syntax: wait <duration> wait random <min> <max>
Parameters
[in] ent
[in] params
Returns
Definition at line 1652 of file g_script_actions.c.
void G_SendMapEntityInfo (gentity_t * e)
G_SendMapEntityInfo.
Parameters
[in] e
Definition at line 1094 of file g_teammapdata.c.
Referenced by ClientThink_real().
void G_SendScore (gentity_t * ent)
Sends current scoreboard information.
Parameters
[in] ent
Definition at line 381 of file g_cmds.c.
Referenced by ClientThink_real().
void G_SendSystemMessage (sysMsg_t message, int team)
G_SendSystemMessage.
Parameters
[in] message
[in] team
Definition at line 108 of file g_systemmsg.c.
Referenced by G_ScriptAction_VoiceAnnounce().
void G_SetAngle (gentity_t * ent, vec3_t angle)
G_SetAngle.
Parameters
[out] ent
[in] angle
Definition at line 1161 of file g_utils.c.
Referenced by aagun_spawn(), FinishSpawningItem(), G_BounceItem(), init_locker(), InitProp(), LaunchItem(), Props_Activated(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_misc_cabinet_health(), SP_misc_cabinet_supply(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_statue(), SP_script_mover(), SP_team_WOLF_checkpoint(), Spawn_Junk(), and Spawn_Shard().
void G_SetClientWeapons (gentity_t * ent, weapon_t w1, weapon_t w2, qboolean updateclient)
G_SetClientWeapons.
Parameters
[in,out] ent
[in] w1
[in] w2
[in] updateclient
Definition at line 1895 of file g_cmds.c.
Referenced by Cmd_Team_f(), and SetTeam().
void G_SetConfigStringValue (int num, const char * key, const char * value)
G_SetConfigStringValue.
Parameters
[in] num
[in] key
[in] value
Definition at line 1571 of file g_trigger.c.
Referenced by G_ModifyTOI(), and SP_trigger_objective_info().
void G_SetEntState (gentity_t * ent, entState_t state)
Sets the entstate of an entity.
Parameters
[in,out] ent
[in] state
Definition at line 1291 of file g_utils.c.
Referenced by _et_G_SetEntState(), AutoBuildConstruction(), func_constructible_underconstructionthink(), G_ScriptAction_SetState(), mg42_spawn(), and TryConstructing().
void G_SetMovedir (vec3_t angles, vec3_t movedir)
The editor only specifies a single value for angles (yaw), but we have special constants to generate an up or down direction. Angles will be cleared, because it is being used to represent a direction instead of an orientation.
Parameters
[in,out] angles
[out] movedir
Definition at line 753 of file g_utils.c.
Referenced by InitShooter(), InitTrigger(), locateCamera(), SP_func_button(), SP_func_door(), SP_func_secret(), SP_target_push(), and target_laser_start().
void G_SetOrigin (gentity_t * ent, vec3_t origin)
Sets the pos trajectory for a fixed position.
Parameters
[out] ent
[in] origin
Definition at line 1139 of file g_utils.c.
Referenced by aagun_spawn(), ClientSpawn(), DropToFloor(), DropToFloorG(), FinishSpawningItem(), flak_spawn(), G_BounceItem(), G_BounceMissile(), G_BuildHead(), G_BuildLeg(), G_PositionEntityOnTag(), G_ScriptAction_SetPosition(), G_TempEntity(), init_locker(), InitProp(), landmine_setup(), LaunchItem(), mg42_spawn(), Props_Activated(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_Dust(), SP_func_fakebrush(), SP_info_camp(), SP_info_notnull(), SP_misc_cabinet_health(), SP_misc_cabinet_supply(), SP_misc_commandmap_marker(), SP_misc_gamemodel(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_DamageInflictor(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_flamethrower(), SP_props_gunsparks(), SP_props_shard_generator(), SP_props_statue(), SP_SmokeDust(), SP_target_position(), SP_target_script_trigger(), SP_target_smoke(), SP_team_WOLF_checkpoint(), Spawn_Junk(), Spawn_Shard(), and Think_SetupObjectiveInfo().
void G_SetPlayerScore (gclient_t * client)
G_SetPlayerScore.
Parameters
[in,out] client
Definition at line 146 of file g_stats.c.
Referenced by G_SetPlayerSkill().
void G_SetPlayerSkill (gclient_t * client, skillType_t skill)
G_SetPlayerSkill.
Parameters
[in,out] client
[in] skill
Definition at line 161 of file g_stats.c.
Referenced by G_AddSkillPoints(), G_CalcRank(), G_LoseSkillPoints(), and G_UpdateCvars().
void G_SetTargetName (gentity_t * ent, char * targetname)
G_SetTargetName.
Parameters
[out] ent
[in] targetname
Definition at line 1548 of file g_main.c.
Referenced by flak_spawn(), G_FindTeams(), mg42_spawn(), and misc_firetrails_think().
void G_SetupFrustum (gentity_t * ent)
G_SetupFrustum.
Parameters
[in] ent
Definition at line 239 of file g_teammapdata.c.
Referenced by G_PlayerCanBeSeenByOthers(), and G_UpdateTeamMapData().
void G_SetupFrustum_ForBinoculars (gentity_t * ent)
G_SetupFrustum_ForBinoculars.
Parameters
[in] ent
Definition at line 281 of file g_teammapdata.c.
Referenced by G_CheckSpottedLandMines(), G_PlayerCanBeSeenByOthers(), and G_UpdateTeamMapData().
char* G_SHA1 (const char * string)
G_SHA1.
Parameters
[in] string
Returns
Definition at line 16 of file g_sha1.c.
Referenced by G_LuaRunIsolated(), and G_ParseMapSettings().
int G_ShaderIndex (const char * name)
G_ShaderIndex.
Parameters
[in] name
Returns
Definition at line 259 of file g_utils.c.
Referenced by BuildShaderStateConfig(), G_ModifyTOI(), G_Script_ScriptParse(), SP_misc_beam(), SP_target_smoke(), and SP_trigger_objective_info().
void G_shuffleTeamsSR (void)
Referenced by G_shuffleTeamsXP(), and Svcmd_ShuffleTeamsXPNoRestart().
void G_shuffleTeamsXP (void)
Shuffle active players onto teams.
Definition at line 1648 of file g_team.c.
Referenced by Svcmd_ShuffleTeamsXP_f().
int G_ShuffleTeamsXP_NoRestart_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Shuffle teams by XP without restart.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 1734 of file g_vote.c.
int G_ShuffleTeamsXP_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Shuffle teams by XP.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 1064 of file g_vote.c.
int G_SkinIndex (const char * name)
G_SkinIndex.
Parameters
[in] name
Returns
Definition at line 249 of file g_utils.c.
Referenced by SP_misc_constructiblemarker(), and SP_misc_gamemodel().
void G_Sound (gentity_t * ent, int soundIndex)
Removed channel parm, since it wasn't used, and could cause confusion.
Parameters
[in] ent
[in] soundIndex
Definition at line 1089 of file g_utils.c.
Referenced by _et_G_Sound(), hurt_touch(), P_WorldEffects(), ReviveEntity(), target_relay_use(), use_invisible_user(), and Use_target_push().
int G_SoundIndex (const char * name)
G_SoundIndex.
Parameters
[in] name
Returns
Definition at line 239 of file g_utils.c.
Referenced by _et_G_SoundIndex(), DoorSetSounds(), G_globalSound(), G_InitGame(), G_PlaySound_Cmd(), G_Script_ScriptParse(), G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_PlaySound(), G_ScriptAction_RemoveTeamVoiceAnnounce(), G_ScriptAction_TeamVoiceAnnounce(), G_SpawnItem(), InitProp(), SP_alarm_box(), SP_dlight(), SP_func_button(), SP_func_explosive(), SP_func_invisible_user(), SP_func_plat(), SP_func_secret(), SP_props_decoration(), SP_props_footlocker(), SP_props_statue(), SP_target_explosion(), SP_target_push(), SP_target_relay(), SP_target_rumble(), SP_target_speaker(), SP_team_WOLF_checkpoint(), SP_trigger_hurt(), and SP_trigger_teleport().
gentity_t* G_Spawn (void)
Either finds a free entity, or allocates a new one.
The slots from 0 to MAX_CLIENTS-1 are always reserved for clients, and will never be used by anything else.
Try to avoid reusing an entity that was recently freed, because it can cause the client to think the entity morphed into something else instead of being removed and recreated, which can cause interpolated angles and bad trails.
Returns
Todo:
: inspect -> add '&& level.startTime != 0' for warmup?
Definition at line 813 of file g_utils.c.
Referenced by AutoBuildConstruction(), CopyToBodyQue(), fire_flamebarrel(), fire_flamechunk(), fire_missile(), flak_spawn(), func_constructiblespawn(), G_BuildHead(), G_BuildLeg(), G_PopupMessage(), G_SpawnGEntityFromSpawnVars(), G_spawnPrintf(), G_TempEntity(), G_TempEntityNotLinked(), InitBodyQue(), LaunchItem(), mg42_spawn(), misc_firetrails_think(), OilSlick_remove(), prop_smoke(), propExplosion(), Props_Activated(), Spawn_Junk(), Spawn_Shard(), SpawnPlatTrigger(), Think_SetupObjectiveInfo(), Think_SpawnNewDoorTrigger(), TryConstructing(), Weapon_Artillery(), and weapon_callAirStrike().
void G_SpawnEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
Definition at line 1030 of file g_spawn.c.
Referenced by G_InitGame().
qboolean G_SpawnFloatExt (const char * key, const char * defaultString, float * out, const char * file, int line)
G_SpawnFloatExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 86 of file g_spawn.c.
gentity_t* G_SpawnGEntityFromSpawnVars (void)
Spawn an entity and fill in all of the level fields from level.spawnVars[], then call the class specfic spawn function.
Returns
Definition at line 788 of file g_spawn.c.
Referenced by G_Lua_CreateEntity(), G_ScriptAction_Create(), and G_SpawnEntitiesFromString().
qboolean G_SpawnIntExt (const char * key, const char * defaultString, int * out, const char * file, int line)
G_SpawnIntExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 105 of file g_spawn.c.
void G_SpawnItem (gentity_t * ent, gitem_t * item)
Sets the clipping size and plants the object on the floor.
Parameters
[in,out] ent
[in] item
Definition at line 1091 of file g_items.c.
Referenced by G_CallSpawn().
void G_spawnPrintf (int print_type, int print_time, gentity_t * owner)
G_spawnPrintf.
Parameters
[in] print_type
[in] print_time
[in] owner
Definition at line 245 of file g_match.c.
Referenced by G_delayPrint(), G_InitGame(), G_pause_cmd(), and G_refPause_cmd().
qboolean G_SpawnStringExt (const char * key, const char * defaultString, char ** out, const char * file, int line)
G_SpawnStringExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 53 of file g_spawn.c.
Referenced by G_SpawnFloatExt(), G_SpawnIntExt(), G_SpawnVector2DExt(), and G_SpawnVectorExt().
qboolean G_SpawnVector2DExt (const char * key, const char * defaultString, float * out, const char * file, int line)
G_SpawnVector2DExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 143 of file g_spawn.c.
qboolean G_SpawnVectorExt (const char * key, const char * defaultString, float * out, const char * file, int line)
G_SpawnVectorExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 124 of file g_spawn.c.
void G_specinvite_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fLock)
Sends an invitation to a player to spectate a team.
Parameters
[in] ent
[in] dwCommand
fLock - unused
Definition at line 844 of file g_cmds_ext.c.
void G_speclock_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fLock)
Locks/unlocks a player's team from spectators.
Parameters
[in] ent
[in] dwCommand
[in] fLock
Definition at line 911 of file g_cmds_ext.c.
int G_StartMatch_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Start Match.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1136 of file g_vote.c.
void G_statsall_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Shows all players' stats to the requesting client.
Parameters
ent
dwCommand - unused
fDump - unused
Definition at line 963 of file g_cmds_ext.c.
Referenced by G_matchInfoDump().
void G_statsPrint (gentity_t * ent, int nType)
Sends a player's stats to the requesting client.
Parameters
[in] ent
[in] nType
Definition at line 935 of file g_match.c.
Referenced by ClientCommand(), and G_weaponStats_cmd().
void G_StoreClientPosition (gentity_t * ent)
G_StoreClientPosition.
Parameters
[in,out] ent
Definition at line 134 of file g_antilag.c.
Referenced by ClientEndFrame().
const char* G_StringContains (const char * str1, const char * str2, int casesensitive)
G_StringContains.
Parameters
[in] str1
[in] str2
[in] casesensitive
Returns
Definition at line 1897 of file g_utils.c.
Referenced by G_MatchString().
int G_StringIndex (const char * string)
G_StringIndex.
Parameters
[in] string
Returns
Definition at line 281 of file g_utils.c.
Referenced by Team_ReturnFlagSound(), and Team_TouchEnemyFlag().
int G_Surrender_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_Surrender_v.
Parameters
[in] ent
dwVoteIndex - unused
[in] arg
[in] arg2
fRefereeCmd - unused
Returns
Definition at line 1808 of file g_vote.c.
Referenced by CheckVote(), and Cmd_Vote_f().
void G_swapTeamLocks (void)
Swap team speclocks.
Definition at line 2025 of file g_team.c.
Referenced by G_InitWorldSession().
void G_swapTeams (void)
Swaps active players on teams.
Definition at line 1562 of file g_team.c.
Referenced by Svcmd_SwapTeams_f().
int G_SwapTeams_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Swap teams.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 1188 of file g_vote.c.
qboolean G_SweepForLandmines (vec3_t origin, float radius, int team)
G_SweepForLandmines.
Parameters
[in] origin
[in] radius
[in] team
Returns
Definition at line 1235 of file g_missile.c.
Referenced by ClientThink_real().
qboolean G_TankIsMountable (gentity_t * ent, gentity_t * other)
G_TankIsMountable.
Parameters
[in] ent
[in] other
Returns
Definition at line 3624 of file g_cmds.c.
Referenced by Do_Activate_f(), and G_CheckForCursorHints().
qboolean G_TankIsOccupied (gentity_t * ent)
G_TankIsOccupied.
Parameters
[in] ent
Returns
Definition at line 3609 of file g_cmds.c.
Referenced by G_TankIsMountable(), and ETInterface::GetEntityFlags().
void G_TeamCommand (team_t team, const char * cmd)
Broadcasts a command to only a specific team.
Parameters
[in] team
[in] cmd
Definition at line 293 of file g_utils.c.
Referenced by Use_Target_Print().
int G_TeamCount (gentity_t * ent, int weap)
G_TeamCount.
Parameters
[in] ent
[in] weap weapon or -1
Returns
Definition at line 1751 of file g_cmds.c.
Referenced by G_IsWeaponDisabled(), G_MaxAvailableAirstrikes(), and G_MaxAvailableArtillery().
void G_TeamDataForString (const char * teamstr, int clientNum, team_t * team, spectatorState_t * sState, int * specClient)
G_TeamDataForString.
Parameters
[in] teamstr
[in] clientNum
[out] team
[out] sState
[in,out] specClient
Definition at line 1197 of file g_cmds.c.
Referenced by Cmd_Team_f(), and SetTeam().
qboolean G_teamJoinCheck (team_t nTeam, gentity_t * ent)
Checks to see if a specified team is allowing players to join.
Parameters
[in] nTeam
[in] ent
Returns
Definition at line 1900 of file g_team.c.
Referenced by G_TeamDataForString(), and SetTeam().
void G_teamready_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Sets a player's team "ready" status.
Parameters
[in] ent
[in] dwCommand
fDump - unused
Definition at line 985 of file g_cmds_ext.c.
void G_teamReset (int team_num, qboolean fClearSpecLock)
Resets a team's settings.
Parameters
[in] team_num
[in] fClearSpecLock
Definition at line 1546 of file g_team.c.
Referenced by G_initMatch(), G_shuffleTeamsXP(), G_swapTeams(), G_teamJoinCheck(), and G_verifyMatchState().
gentity_t* G_TempEntity (vec3_t origin, entity_event_t event)
Spawns an event entity that will be auto-removed.
The origin will be snapped to save net bandwidth, so care must be taken if the origin is right on a surface (snap towards start vector first)
Parameters
[in] origin
[in] event
Returns
Definition at line 956 of file g_utils.c.
Referenced by _et_G_TempEntity(), barrel_smoke(), BodyUnlink(), Bullet_Fire_Extended(), dust_use(), EmitterCheck(), Fire_Lead_Ext(), flakPuff(), func_constructible_underconstructionthink(), G_BodyDP(), G_GlobalClientEvent(), G_Pip(), G_RailBox(), G_RailTrail(), G_RealExplodedMissile(), G_RunFlamechunk(), G_RunMissile(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), G_ScriptAction_SpawnRubble(), G_ScriptAction_ToggleSpeaker(), G_Sound(), OilParticles_think(), OilSlick_remove_think(), PGUNsparks_use(), props_locker_mass(), props_snowGenerator_think(), Psmoke_think(), smokedust_use(), SP_OilSlick(), target_effect(), target_explosion_use(), target_rumble_think(), Touch_Item(), Use_Shooter(), and Weapon_Knife().
gentity_t* G_TempEntityNotLinked (entity_event_t event)
Spawns an event entity that will be auto-removed Use this for non visible and not origin based events like global sounds etc.
Parameters
[in] event
Returns
Note
Don't forget to call e->r.svFlags = SVF_BROADCAST; after
Definition at line 990 of file g_utils.c.
Referenced by G_clientFlagIndicator(), G_ClientSound(), G_globalFlagIndicator(), G_globalSound(), G_globalSoundEnum(), G_ScriptAction_TeamVoiceAnnounce(), player_die(), and SetTeam().
void G_TempTraceIgnoreEntity (gentity_t * ent)
G_TempTraceIgnoreEntity.
Parameters
[in,out] ent
Definition at line 2495 of file g_misc.c.
Referenced by G_TempTraceIgnorePlayersAndBodies(), and G_Trace().
void G_TempTraceIgnorePlayersAndBodies (void)
G_TempTraceIgnorePlayersAndBodies.
Definition at line 2509 of file g_misc.c.
Referenced by DynaFree(), G_RealExplodedMissile(), trap_EngineerTrace(), and Weapon_Engineer().
gentity_t* G_TestEntityPosition (gentity_t * ent)
G_TestEntityPosition.
Parameters
[in] ent
Returns
Definition at line 128 of file g_mover.c.
Referenced by func_constructible_explode(), G_MoverPush(), G_SetEntState(), G_TryPushingEntity(), HandleEntsThatBlockConstructible(), and WolfReviveBbox().
int G_Timelimit_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Timelimit.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1368 of file g_vote.c.
void G_TouchTriggers (gentity_t * ent)
Find all trigger entities that ent's current position touches.
Parameters
[in,out] ent Entity
Spectators will only interact with teleporters.
Definition at line 417 of file g_active.c.
Referenced by ClientEndFrame(), ClientThink_real(), and SpectatorThink().
void G_Trace (gentity_t * ent, trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, qboolean ignoreCorpses)
Run a trace without fixups (historical fixups will be done externally)
Parameters
[in] ent
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
[in] ignoreCorpses Skip corpses for bullet tracing (=non gibbing weapons)
Definition at line 803 of file g_antilag.c.
Referenced by Bullet_Fire_Extended().
void G_TryDoor (gentity_t * ent, gentity_t * other, gentity_t * activator)
Seemed better to have this isolated. this way i can get func_invisible_user's using the regular rules of doors.
Parameters
[in,out] ent
other - unused
[in] activator
Definition at line 2354 of file g_mover.c.
Referenced by Do_Activate_f(), and G_UseTargets().
int G_UnMute_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Player Un-Mute.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 609 of file g_vote.c.
void G_UnMuteClient (void)
G_UnMuteClient.
Definition at line 829 of file g_referee.c.
int G_Unreferee_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Un-Referee voting.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 1490 of file g_vote.c.
void G_UpdateCharacter (gclient_t * client)
G_UpdateCharacter.
Parameters
[in,out] client
Definition at line 298 of file g_character.c.
Referenced by ClientConnect(), ClientSpawn(), G_shuffleTeamsXP(), G_swapTeams(), and SetTeam().
void G_UpdateCvars (void)
G_UpdateCvars.
Todo:
: mapvote & xp
Definition at line 1814 of file g_main.c.
Referenced by G_configLoadAndSet(), G_RunFrame(), and G_wipeCvars().
void G_UpdateFireteamConfigString (fireteamData_t * ft)
G_UpdateFireteamConfigString.
Parameters
ft
Definition at line 177 of file g_fireteams.c.
Referenced by Cmd_FireTeam_MP_f(), Cmd_Vote_f(), G_AddClientToFireteam(), G_DestroyFireteam(), G_GiveAdminOfFireTeam(), G_InitWorldSession(), G_RegisterFireteam(), and G_RemoveClientFromFireteams().
void G_UpdateSpawnPointState (gentity_t * ent)
Udates spawn point state.
Parameters
[in] ent wolf_objective entity.
Returns
Definition at line 2261 of file g_team.c.
Referenced by G_SetEntState(), objective_Register(), and team_wolf_objective_use().
void G_UpdateSpawnPointStatePlayerCounts ()
Udates player counts in all spawn point states.
Returns
Definition at line 2200 of file g_team.c.
Referenced by ClientSpawn(), G_ScriptAction_SetAutoSpawn(), G_UpdateSpawnPointState(), and SetPlayerSpawn().
void G_updateSpecLock (int nTeam, qboolean fLock)
Update specs for blackout, as needed.
Parameters
[in] nTeam
[in] fLock
Definition at line 1964 of file g_team.c.
Referenced by G_refSpeclockTeams_cmd(), and G_speclock_cmd().
void G_UpdateTeamMapData (void)
G_UpdateTeamMapData.
Definition at line 1315 of file g_teammapdata.c.
Referenced by G_RunFrame().
void G_UpgradeSkill (gentity_t * ent, skillType_t skill)
Local func to actual do skill upgrade, used by both MP skill system, and SP scripted skill system.
Parameters
[in,out] ent
[in] skill
Definition at line 192 of file g_stats.c.
Referenced by G_AddSkillPoints(), and G_UpdateCvars().
void G_UseEntity (gentity_t * ent, gentity_t * other, gentity_t * activator)
Added to allow more checking on what uses what.
Parameters
[in,out] ent
[in] other
[in] activator
Definition at line 646 of file g_utils.c.
Referenced by alarmbox_updateparts(), Do_Activate_f(), func_constructible_explode(), func_constructible_underconstructionthink(), G_Damage(), G_ScriptAction_AlertEntity(), G_UseTargets(), target_relay_use(), and TryConstructing().
void G_UseTargets (gentity_t * ent, gentity_t * activator)
Search for (string)targetname in all entities that match (string)self.target and call their .use function.
Parameters
[in] ent
[in] activator Should be set to the entity that initiated the firing.
Definition at line 665 of file g_utils.c.
Referenced by ClientSpawn(), crate_animate(), Do_Activate_f(), func_explosive_explode(), func_timer_think(), G_RealExplodedMissile(), G_TryDoor(), locker_tall_think(), multi_trigger(), props_58x112tablew_think(), Props_Barrel_Die(), props_bench_think(), props_castlebed_animate(), Props_Chair_Animate(), Props_Chair_Touch(), props_crate32x64_think(), props_decoration_death(), props_flippy_table_die(), props_locker_tall_die(), props_radio_die(), props_radio_dieSEVEN(), props_statue_death(), Props_TurnLightsOff(), Reached_BinaryMover(), Reached_Train(), Reached_Train_rotating(), Reached_TrinaryMover(), Static_Pain(), target_effect(), target_explosion_use(), target_relay_use(), target_script_trigger_use(), Think_Target_Delay(), Touch_Item(), trigger_always_think(), use_invisible_user(), Use_Target_Alarm(), and Use_Target_Counter().
void G_verifyMatchState (team_t nTeam)
Check if we need to reset the game state due to an empty team.
Parameters
[in] nTeam
Definition at line 1862 of file g_team.c.
Referenced by ClientDisconnect(), and SetTeam().
qboolean G_VisibleFromBinoculars (gentity_t * viewer, gentity_t * ent, vec3_t origin)
G_VisibleFromBinoculars.
Parameters
[in] viewer
[in] ent
[in,out] origin
Returns
Definition at line 358 of file g_teammapdata.c.
Referenced by G_CheckSpottedLandMines().
qboolean G_VisibleFromBinoculars_Box (gentity_t * viewer, gentity_t * ent, vec3_t origin, vec3_t mins, vec3_t maxs)
G_VisibleFromBinoculars_Box.
Parameters
[in] viewer
[in] ent
[in,out] origin
[in] mins
[in] maxs
Returns
Definition at line 408 of file g_teammapdata.c.
Referenced by G_PlayerCanBeSeenByOthers(), and G_UpdateTeamMapData().
void G_VoiceTo (gentity_t * ent, gentity_t * other, int mode, const char * id, qboolean voiceonly, float randomNum)
G_VoiceTo.
Parameters
[in] ent
[in] other
[in] mode
[in] id
[in] voiceonly
[in] randomNum
Definition at line 2747 of file g_cmds.c.
Referenced by G_Voice().
int G_voteCmdCheck (gentity_t * ent, char * arg, char * arg2, qboolean fRefereeCmd)
Checks for valid custom callvote requests from the client.
Parameters
[in] ent
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 113 of file g_vote.c.
Referenced by Cmd_CallVote_f().
void G_voteFlags (void)
Set disabled votes for client UI.
Definition at line 208 of file g_vote.c.
Referenced by G_loadMatchGame(), and G_UpdateCvars().
void G_voteHelp (gentity_t * ent, qboolean fShowVote)
Voting help summary.
Parameters
[in] ent
[in] fShowVote
Definition at line 145 of file g_vote.c.
Referenced by Cmd_CallVote_f(), and G_refHelp_cmd().
int G_Warmupfire_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Warmup Weapon Fire.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 1430 of file g_vote.c.
void G_weaponRankings_cmd (gentity_t * ent, unsigned int dwCommand, qboolean state)
Shows best/worst accuracy for all weapons, or sorted accuracies for a single weapon.
Parameters
[in] ent
[in] dwCommand
[in] state
Definition at line 1192 of file g_cmds_ext.c.
void G_weaponStats_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fDump)
Shows a player's stats to the requesting client.
Parameters
[in] ent
dwCommand - unused
fDump - unused
Definition at line 952 of file g_cmds_ext.c.
void G_weaponStatsLeaders_cmd (gentity_t * ent, qboolean doTop, qboolean doWindow)
Shows the most accurate players for each weapon to the requesting client.
Parameters
ent - unused
[in] doTop
[in] doWindow
Definition at line 1123 of file g_cmds_ext.c.
Referenced by ClientCommand(), and G_weaponRankings_cmd().
void G_wipeCvars (void)
Reset particular server variables back to defaults if a config is voted in.
Definition at line 2111 of file g_main.c.
Referenced by G_configLoadAndSet().
void G_WriteSessionData (qboolean restart)
G_WriteSessionData.
Parameters
[in] restart
Definition at line 556 of file g_session.c.
Referenced by ExitLevel(), and G_ShutdownGame().
unsigned long GeoIP_addr_to_num (const char * addr)
GeoIP_addr_to_num.
Parameters
[in] addr
Returns
Definition at line 75 of file geoip.c.
Referenced by ClientConnect().
void GeoIP_close (void)
GeoIP_close.
Definition at line 226 of file geoip.c.
Referenced by G_ShutdownGame(), and GeoIP_open().
void GeoIP_open (void)
GeoIP_open.
Definition at line 167 of file geoip.c.
Referenced by G_InitGame().
unsigned int GeoIP_seek_record (GeoIP * gi, unsigned long ipnum)
GeoIP_seek_record.
Parameters
[in] gi
[in] ipnum
Returns
Definition at line 126 of file geoip.c.
Referenced by ClientConnect().
int GetFieldIndex (const char * fieldname)
GetFieldIndex.
Parameters
[in] fieldname
Returns
The index in the fiels[] array of the given fieldname, -1 if not found..
Definition at line 1070 of file g_spawn.c.
Referenced by _et_G_GetSpawnVar(), _et_G_SetSpawnVar(), and GetFieldType().
fieldtype_t GetFieldType (const char * fieldname)
GetFieldType.
Parameters
[in] fieldname
Returns
The fieldType of the given fieldname, otherwise F_IGNORE if the field is not found.
Definition at line 1087 of file g_spawn.c.
Referenced by _et_G_GetSpawnVar(), and _et_G_SetSpawnVar().
qboolean infront (gentity_t * self, gentity_t * other)
infront
Parameters
[in] self
[in] other
Returns
Definition at line 1178 of file g_utils.c.
Referenced by flippy_table_use(), G_EmplacedGunIsMountable(), and player_die().
void InitBodyQue (void)
InitBodyQue.
Definition at line 281 of file g_client.c.
Referenced by G_InitGame().
void InitMover (gentity_t * ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
Parameters
[in,out] ent
Definition at line 1823 of file g_mover.c.
Referenced by G_ScriptAction_GotoMarker(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_secret(), SP_func_static(), SP_func_train(), SP_func_train_rotating(), and SP_script_mover().
void InitMoverRotate (gentity_t * ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
Parameters
[in,out] ent
Definition at line 1895 of file g_mover.c.
Referenced by SP_func_door_rotating(), and SP_Props_Flipping_Table().
gentity_t* LaunchItem (gitem_t * item, vec3_t origin, vec3_t velocity, int ownerNum)
Spawns an item and tosses it forward.
Parameters
[in] item
[in] origin
[in] velocity
[in] ownerNum
Returns
Definition at line 849 of file g_items.c.
Referenced by Drop_Item(), G_DropItems(), G_DropWeapon(), props_locker_spawn_item(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void limbo (gentity_t * ent, qboolean makeCorpse)
limbo
Parameters
[in,out] ent
[in] makeCorpse
Definition at line 787 of file g_client.c.
Referenced by ClientBegin(), ClientCommand(), ClientThink_real(), Cmd_Kill_f(), Cmd_UnIgnore_f(), G_Damage(), ETInterface::InterfaceSendMessage(), player_die(), and SetTeam().
void mg42_fire (gentity_t * other)
mg42_fire
Parameters
[in,out] other
Definition at line 1472 of file g_misc.c.
Referenced by ClientEvents().
void mg42_stopusing (gentity_t * self)
This is to be called for the gun ent, not the tripod.
Parameters
[in,out] self
Definition at line 1670 of file g_misc.c.
Referenced by G_SetEntState().
void mountedmg42_fire (gentity_t * other)
mountedmg42_fire
Parameters
[in,out] other
Definition at line 883 of file g_script.c.
Referenced by ClientEvents().
void MoveClientToIntermission (gentity_t * ent)
When the intermission starts, this will be called for all players. If a new client connects, this will be called after the spawn function.
Parameters
[in,out] ent Client
Definition at line 3144 of file g_main.c.
Referenced by BeginIntermission(), and ClientSpawn().
qboolean OnSameTeam (gentity_t * ent1, gentity_t * ent2)
OnSameTeam.
Parameters
[in] ent1
[in] ent2
Returns
Definition at line 145 of file g_team.c.
Referenced by AccuracyHit(), Cmd_God_f(), G_BurnTarget(), G_Damage(), G_SayTo(), G_VoiceTo(), isMortalSelfDamage(), and player_die().
int OtherTeam (int team)
OtherTeam.
Parameters
[in] team
Returns
Note
Unused
Definition at line 50 of file g_team.c.
team_t PickTeam (int ignoreClientNum)
PickTeam.
Parameters
[in] ignoreClientNum
Returns
Definition at line 995 of file g_client.c.
Referenced by G_TeamDataForString().
int Pickup_Team (gentity_t * ent, gentity_t * other)
Pickup_Team.
Parameters
[in] ent
[in,out] other
Returns
Definition at line 464 of file g_team.c.
Referenced by Touch_Item().
void player_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t meansOfDeath)
player_die
Parameters
[in,out] self
[in] inflictor
[in,out] attacker
[in] damage
[in] meansOfDeath
Todo:
: contents is always 0 here
Todo:
: add POSITION_RIGHT, POSITION_LEFT
Definition at line 255 of file g_combat.c.
Referenced by ClientSpawn(), Cmd_Kill_f(), Cmd_UnIgnore_f(), and SetTeam().
void Prop_Break_Sound (gentity_t * ent)
This should work for all fx types now.
Parameters
ent
Definition at line 1709 of file g_props.c.
Referenced by G_RunItemProp(), Props_Barrel_Die(), props_castlebed_die(), Props_Chair_Die(), and props_radio_dieSEVEN().
void Props_Chair_Skyboxtouch (gentity_t * ent)
Props_Chair_Skyboxtouch.
Parameters
[out] ent
Definition at line 1757 of file g_props.c.
Referenced by G_RunItemProp().
char* Q_AddCR (char * s)
Replaces all occurances of "\\\\n" with '\n'.
Parameters
[in] s
Definition at line 5111 of file g_cmds.c.
Referenced by Svcmd_Chat_f(), Svcmd_CP_f(), and Svcmd_Say_f().
qboolean ReadyToCallAirstrike (gentity_t * ent)
qboolean ReadyToCallArtillery (gentity_t * ent)
Does ent have enough "energy" to call artillery?
Parameters
[in] ent Entity
Definition at line 281 of file g_active.c.
Referenced by Weapon_Artillery().
qboolean ReadyToConstruct (gentity_t * ent, gentity_t * constructible, qboolean updateState)
Are we ready to construct?
Parameters
[in,out] ent Entity
[in] constructible Constructible Entity
[in] updateState Do we want to update Entity weapon time?
Optionally, will also update the time while we are constructing
Definition at line 306 of file g_active.c.
Referenced by TryConstructing().
void reinforce (gentity_t * ent)
Called when time expires for a team deployment cycle and there is at least one guy ready to go.
Parameters
[in,out] ent
Definition at line 901 of file g_client.c.
Referenced by SpectatorClientEndFrame().
void respawn (gentity_t * ent)
respawn
Parameters
[in,out] ent
Definition at line 931 of file g_client.c.
Referenced by reinforce(), and Touch_Item().
void RespawnItem (gentity_t * ent)
Respawn item.
Parameters
[in,out] ent
Definition at line 635 of file g_items.c.
Referenced by Team_ResetFlag(), Touch_Item(), and Use_Item().
void SanitizeString (char * in, char * out, qboolean fToLower)
Remove case and control characters.
Parameters
[in] in
[out] out
[in] fToLower
Definition at line 524 of file g_cmds.c.
Referenced by ClientNumberFromString(), ClientNumbersFromString(), G_players_cmd(), and G_printMatchInfo().
void script_mover_blocked (gentity_t * ent, gentity_t * other)
script_mover_blocked
Parameters
[in] ent
[in] other
Todo:
: we could have certain entities stop us, thereby "pausing" movement
Definition at line 1085 of file g_script.c.
Referenced by G_TagLinkEntity(), and SP_script_mover().
void script_mover_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
script_mover_use
Parameters
[in] ent
other - unused
activator - unused
Definition at line 1057 of file g_script.c.
Referenced by G_ScriptAction_GotoMarker(), and SP_script_mover().
gentity_t* SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, int spawnObjective)
SelectCTFSpawnPoint.
Parameters
[in] team
[in] teamstate
[in,out] origin
[in,out] angles
[in] spawnObjective
Returns
Definition at line 678 of file g_team.c.
Referenced by ClientSpawn().
gentity_t* SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles)
Chooses a player start, deathmatch start, etc.
Parameters
[in] avoidPoint
[in] origin
[in] angles
Returns
Definition at line 224 of file g_client.c.
Referenced by FindIntermissionPoint(), and SelectCTFSpawnPoint().
void SendScoreboardMessageToAllClients (void)
Do this at BeginIntermission time and whenever ranks are recalculated due to enters/exits/forced team changes.
Definition at line 3125 of file g_main.c.
Referenced by BeginIntermission(), and CalculateRanks().
void SetClientViewAngle (gentity_t * ent, vec3_t angle)
SetClientViewAngle.
Parameters
[in,out] ent
[in] angle
Definition at line 679 of file g_client.c.
Referenced by ClientSpawn(), Cmd_UnIgnore_f(), StopFollowing(), TeleportPlayer(), and ETInterface::UpdateBotInput().
void SetMoverState (gentity_t * ent, moverState_t moverState, int time)
SetMoverState.
Parameters
[in,out] ent
[in] moverState
[in] time
Definition at line 880 of file g_mover.c.
Referenced by Blocked_Door(), Blocked_DoorRotate(), G_ScriptAction_GotoMarker(), MatchTeam(), MatchTeamReverseAngleOnSlaves(), Reached_BinaryMover(), Reached_Train(), Reached_Train_rotating(), and Reached_TrinaryMover().
void SetPlayerSpawn (gentity_t * ent, int spawn, qboolean update)
SetPlayerSpawn.
Parameters
[in,out] ent
[in] spawn
[in] update
Definition at line 4232 of file g_cmds.c.
Referenced by Cmd_SetSpawnPoint_f(), and ETInterface::InterfaceSendMessage().
qboolean SetTeam (gentity_t * ent, const char * s, qboolean force, weapon_t w1, weapon_t w2, qboolean setweapons)
SetTeam.
Parameters
[in,out] ent
[in] s
[in] force
[in] w1
[in] w2
[in] setweapons
Returns
Todo:
: doesn't ClientBegin take care of this already?
Definition at line 1370 of file g_cmds.c.
Referenced by ETInterface::ChangeTeam(), ClientInactivityTimer(), Cmd_FollowCycle_f(), Cmd_Team_f(), G_MakeShoutcaster(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_updateSpecLock(), StopFollowing(), and Svcmd_ForceTeam_f().
void SetWolfSpawnWeapons (gclient_t * client)
SetWolfSpawnWeapons.
Parameters
[in,out] client
Definition at line 1156 of file g_client.c.
Referenced by ClientSpawn(), and G_ResetXP().
void SnapVectorTowards (vec3_t v, vec3_t to)
SnapVectorTowards.
Parameters
v
to SnapVectorTowards.
[in,out] v
[out] to
Note
Modified so it doesn't have trouble with negative locations (quadrant problems) (this was causing some problems with bullet marks appearing since snapping too far off the target surface causes the the distance between the transmitted impact point and the actual hit surface larger than the mark radius. (so nothing shows))
Definition at line 6221 of file cg_weapons.c.
Referenced by Bullet_Fire_Extended(), CG_Bullet(), EmitterCheck(), Fire_Lead_Ext(), G_DropItems(), weapon_gpg40_fire(), weapon_grenadelauncher_fire(), Weapon_MagicAmmo_Ext(), Weapon_Medic_Ext(), and weapon_mortar_fire().
void Spawn_Shard (gentity_t * ent, gentity_t * inflictor, float quantity, int type)
Spawn_Shard.
Parameters
[in] ent
[in] inflictor
[in] quantity
[in] type
Definition at line 1657 of file g_props.c.
Referenced by crate_die(), Props_Barrel_Die(), Props_Chair_Die(), props_decoration_death(), props_radio_dieSEVEN(), props_statue_death(), Static_Pain(), and Use_Props_Shard_Generator().
qboolean SpotWouldTelefrag (gentity_t * spot)
SpotWouldTelefrag.
Parameters
[in] spot
Returns
Definition at line 137 of file g_client.c.
Referenced by ClientBegin(), SelectRandomDeathmatchSpawnPoint(), and SelectRandomTeamSpawnPoint().
void StopFollowing (gentity_t * ent)
If the client being followed leaves the game, or you just want to drop to free floating spectator mode.
Parameters
[in,out] ent
Todo:
: to avoid having a spectator with a gun..
Todo:
: useless?
Definition at line 1651 of file g_cmds.c.
Referenced by ClientDisconnect(), Cmd_Follow_f(), G_updateSpecLock(), MoveClientToIntermission(), and SpectatorThink().
void Svcmd_GameMem_f (void)
Svcmd_GameMem_f.
Definition at line 80 of file g_mem.c.
void Svcmd_ResetMatch_f (qboolean fDoReset, qboolean fDoRestart)
Multi-use now for both map restarts and total match resets.
Parameters
[in] fDoReset
[in] fDoRestart
Definition at line 839 of file g_svcmds.c.
Referenced by G_Map_v(), G_MapRestart_v(), G_MatchReset_v(), Svcmd_ResetMatch(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), and Svcmd_SwapTeams_f().
void Svcmd_ShuffleTeamsSR_f (qboolean restart)
Referenced by G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), and Svcmd_ShuffleTeamsXPNoRestart().
void Svcmd_ShuffleTeamsXP_f (qboolean restart)
randomly places players on teams
Parameters
[in] restart
Definition at line 893 of file g_svcmds.c.
Referenced by G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), Svcmd_ShuffleTeamsXP(), and Svcmd_ShuffleTeamsXPNoRestart().
void Svcmd_StartMatch_f (void)
starts match if in tournament mode
Definition at line 807 of file g_svcmds.c.
void Svcmd_SwapTeams_f (void)
swaps all clients to opposite team
Definition at line 871 of file g_svcmds.c.
Referenced by G_SwapTeams_v().
void Team_DroppedFlagThink (gentity_t * ent)
Automatically set in Launch_Item if the item is one of the flags.
Flags are unique in that if they are dropped, the base flag must be respawned when they time out
Parameters
[in] ent
Definition at line 265 of file g_team.c.
Referenced by Blocked_Door(), Blocked_DoorRotate(), func_constructible_explode(), G_SetEntState(), HandleEntsThatBlockConstructible(), LaunchItem(), and script_mover_blocked().
void Team_ReturnFlag (gentity_t * ent)
Team_ReturnFlag.
Parameters
[in] ent
Todo:
: returns RED/BLUE flag ... change to Axis/Allies?
Definition at line 249 of file g_team.c.
Referenced by G_RunItem(), and Use_target_remove_powerups().
const char* TeamColorString (int team)
TeamColorString.
Parameters
[in] team
Returns
Note
Unused
Definition at line 92 of file g_team.c.
int TeamCount (int ignoreClientNum, team_t team)
Count the number of players on a team.
Parameters
[in] ignoreClientNum
[in] team
Returns
Number of players on a team
Definition at line 971 of file g_client.c.
Referenced by ETInterface::ChangeClass(), ETInterface::ChangeTeam(), Cmd_Follow_f(), G_allowFollow(), G_printMatchInfo(), G_refLockTeams_cmd(), G_refPlayerPut_cmd(), G_refSpeclockTeams_cmd(), G_TeamDataForString(), G_teamJoinCheck(), G_verifyMatchState(), PickTeam(), and SetTeam().
const char* TeamName (int team)
TeamName.
Parameters
[in] team
Returns
Definition at line 68 of file g_team.c.
Referenced by Team_ReturnFlag().
void TeamplayInfoMessage (team_t team)
TeamplayInfoMessage.
Format: clientNum location health armor weapon powerups
Parameters
[in] team
Definition at line 703 of file g_team.c.
Referenced by CheckTeamStatus().
void TeleportPlayer (gentity_t * player, vec3_t origin, vec3_t angles)
Teleport player to a given origin and angles.
=================================================================================
TELEPORTERS
Parameters
[in,out] player
[in] origin
[in] angles
Definition at line 132 of file g_misc.c.
Referenced by Cmd_SetViewpos_f(), G_LeaveTank(), target_teleporter_use(), Touch_DoorTriggerSpectator(), and trigger_teleporter_touch().
void Think_SetupObjectiveInfo (gentity_t * ent)
Links the trigger to it's objective, determining if it's a func_explosive of func_constructible and spawning the right indicator.
Parameters
[in,out] ent
Definition at line 1601 of file g_trigger.c.
Referenced by func_constructible_explode(), func_constructible_use(), G_ModifyTOI(), and SP_trigger_objective_info().
void TossWeapons (gentity_t * self)
Toss the weapon and powerups for the killed player.
Parameters
[in] self
Todo:
; drop secondary too?!
Definition at line 81 of file g_combat.c.
Referenced by ClientDisconnect(), and limbo().
void Touch_Item (gentity_t * ent, gentity_t * other, trace_t * trace)
Action when touching an item.
Parameters
[in,out] ent
[in] other
trace - unused
Definition at line 713 of file g_items.c.
Referenced by Touch_Item_Auto(), and Use_Target_Give().
void Touch_Item_Auto (gentity_t * ent, gentity_t * other, trace_t * trace)
Auto action when touching an item.
PICKUP_ACTIVATE (0), he will pick up items only when using +activate PICKUP_TOUCH (1), he will pickup items when touched PICKUP_FORCE (2), he will pickup the next item when touched (and reset to PICKUP_ACTIVATE when done)
Parameters
[in,out] ent
[in,out] other
[in] trace
Definition at line 680 of file g_items.c.
Referenced by FinishSpawningItem(), and LaunchItem().
void trap_AdjustAreaPortalState (gentity_t * ent, qboolean open)
trap_AdjustAreaPortalState
Parameters
[in] ent
[in] open
Definition at line 453 of file g_syscalls.c.
Referenced by Reached_BinaryMover(), Reached_TrinaryMover(), Use_BinaryMover(), and Use_TrinaryMover().
qboolean trap_AreasConnected (int area1, int area2)
trap_AreasConnected
Parameters
[in] area1
[in] area2
Returns
Definition at line 464 of file g_syscalls.c.
int trap_Argc (void)
trap_Argc
Returns
Definition at line 153 of file cg_syscalls.c.
void trap_Args (char * buffer, int bufferLength)
trap_Args
Parameters
[out] buffer
[in] bufferLength
Definition at line 174 of file cg_syscalls.c.
void trap_Argv (int n, char * buffer, int bufferLength)
trap_Argv
Parameters
[in] n
[out] buffer
[in] bufferLength
[in] n
[in] buffer
[in] bufferLength
Definition at line 164 of file cg_syscalls.c.
int trap_BotAllocateClient (int clientNum)
trap_BotAllocateClient
Todo:
: precompiler macros for engine ?
Parameters
[in] clientNum
Returns
Definition at line 524 of file g_syscalls.c.
Referenced by ETInterface::AddBot().
int trap_BotGetServerCommand (int clientNum, char * message, int size)
trap_BotGetServerCommand
Parameters
[in] clientNum
[out] message
[in] size
Returns
Definition at line 536 of file g_syscalls.c.
Referenced by Bot_Interface_Update().
void trap_BotUserCommand (int clientNum, usercmd_t * ucmd)
trap_BotUserCommand
Parameters
[in] clientNum
[in] ucmd
Definition at line 546 of file g_syscalls.c.
Referenced by ETInterface::UpdateBotInput().
void trap_Cvar_LatchedVariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
[in] varName
[in] buffer
[in] bufsize
Definition at line 144 of file cg_syscalls.c.
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
trap_Cvar_Register
Parameters
[in] vmCvar
[in] varName
[in] defaultValue
[in] flags
Definition at line 103 of file cg_syscalls.c.
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 122 of file cg_syscalls.c.
void trap_Cvar_Update (vmCvar_t * vmCvar)
trap_Cvar_Update
Parameters
[in] vmCvar
Definition at line 112 of file cg_syscalls.c.
int trap_Cvar_VariableIntegerValue (const char * varName)
trap_Cvar_VariableIntegerValue
Parameters
[in] varName
Returns
Definition at line 223 of file g_syscalls.c.
Referenced by G_FreeEntity(), G_players_cmd(), G_Script_ScriptParse(), G_ScriptAction_Cvar(), G_voteFlags(), and ETInterface::InterfaceSendMessage().
void trap_Cvar_VariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_VariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
[in] varName
[in] buffer
[in] bufsize
Definition at line 133 of file cg_syscalls.c.
float trap_Cvar_VariableValue (const char * varName)
trap_Cvar_VariableValue
Parameters
[in] varName
Returns
Definition at line 125 of file ui_syscalls.c.
Referenced by Com_DPrintf(), UI_BuildPlayerList(), UI_DownloadInfo(), UI_DrawLoadPanel(), UI_Init(), UI_KeyEvent(), UI_LoadDemos(), UI_LoadPanel_RenderLoadingText(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_Refresh(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_StartServerRefresh(), UI_TeamMember_HandleKey(), and UI_Update().
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
trap_DebugPolygonCreate
Parameters
[in] color
[in] numPoints
[in] points
Returns
Definition at line 669 of file g_syscalls.c.
Referenced by DebugLine().
void trap_DebugPolygonDelete (int id)
trap_DebugPolygonDelete
Parameters
[in] id
Definition at line 678 of file g_syscalls.c.
void trap_DropClient (int clientNum, const char * reason, int length)
trap_DropClient
Parameters
[in] clientNum
[in] reason
[in] length
Definition at line 270 of file g_syscalls.c.
Referenced by _et_trap_DropClient(), ClientInactivityTimer(), ClientUserinfoChanged(), Cmd_Vote_f(), ETInterface::RemoveBot(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
void trap_EA_Command (int clientNum, char * command)
trap_EA_Command
Parameters
[in] clientNum
[in] command
Definition at line 556 of file g_syscalls.c.
Referenced by ETInterface::BotCommand(), and ETInterface::InterfaceSendMessage().
void trap_EngineerTrace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_EngineerTrace
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 1508 of file g_weapon.c.
Referenced by G_DropItems(), Weapon_Engineer(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int * list, int maxCount)
trap_EntitiesInBox
Parameters
[in] mins
[in] maxs
[out] list
[in] maxCount
Returns
Definition at line 495 of file g_syscalls.c.
Referenced by EntsThatRadiusCanDamage(), etpro_RadiusDamage(), func_constructible_explode(), G_FlameDamage(), G_LandmineThink(), G_MoverPush(), G_RadiusDamage(), G_RealExplodedMissile(), G_SetEntState(), G_TouchTriggers(), HandleEntsThatBlockConstructible(), LandminePostThink(), multi_trigger(), SpotWouldTelefrag(), Weapon_Engineer(), and WolfReviveBbox().
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
trap_EntityContact
Parameters
[in] mins
[in] maxs
[in] ent
Returns
Definition at line 507 of file g_syscalls.c.
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 512 of file g_syscalls.c.
Referenced by ammo_touch(), G_TouchTriggers(), heal_touch(), and WolfReviveBbox().
void trap_Error (const char * fmt)
trap_Error
Parameters
[in] fmt
Definition at line 80 of file cg_syscalls.c.
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
Parameters
[in] f
Definition at line 217 of file cg_syscalls.c.
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
trap_FS_FOpenFile
Parameters
[in] qpath
[in,out] f
[in] mode
Returns
Parameters
[in] qpath
[in] f
[in] mode
Returns
Definition at line 186 of file cg_syscalls.c.
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
trap_FS_GetFileList
Parameters
[in] path
[in] extension
[out] listbuf
[in] bufsize
Returns
Parameters
[in] path
[in] extension
[in] listbuf
[in] bufsize
Returns
Definition at line 230 of file cg_syscalls.c.
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
trap_FS_Read
Parameters
[out] buffer
[in] len
[in] f
[in] buffer
[in] len
[in] f
Definition at line 197 of file cg_syscalls.c.
int trap_FS_Rename (const char * from, const char * to)
trap_FS_Rename
Parameters
[in] from
[in] to
Returns
Definition at line 150 of file g_syscalls.c.
Referenced by _et_trap_FS_Rename().
int trap_FS_Write (const void * buffer, int len, fileHandle_t f)
trap_FS_Write
Parameters
[in] buffer
[in] len
[in] f
[in] buffer
[in] len
[in] f
Returns
Definition at line 208 of file cg_syscalls.c.
void trap_GetConfigstring (int num, char * buffer, int bufferSize)
trap_GetConfigstring
Parameters
[in] num
[out] buffer
[in] bufferSize
Definition at line 309 of file g_syscalls.c.
Referenced by _et_trap_GetConfigstring(), CheckExitRules(), ClientName(), ClientUserinfoChanged(), FindIntermissionPoint(), G_FindConfigstringIndex(), G_InitGame(), G_LogExit(), G_RemoveConfigstringIndex(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetWinner(), G_SetConfigStringValue(), G_StoreMapXP(), G_Surrender_v(), G_UpdateCharacter(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), objective_Register(), ScoreIsTied(), SP_misc_constructiblemarker(), SP_script_mover(), and Svcmd_CSInfo_f().
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
trap_GetEntityToken
Parameters
[out] buffer
[in] bufferSize
Returns
Definition at line 1503 of file cg_syscalls.c.
void trap_GetServerinfo (char * buffer, int bufferSize)
trap_GetServerinfo
Parameters
[out] buffer
[in] bufferSize
Definition at line 340 of file g_syscalls.c.
Referenced by G_Campaign_v(), G_InitGame(), G_InitWorldSession(), G_Map_v(), G_ParseMapSettings(), and G_WriteSessionData().
qboolean trap_GetTag (int clientNum, int tagFileNumber, char * tagName, orientation_t * orientation)
trap_GetTag
Parameters
[in] clientNum
[in] tagFileNumber
[out] tagName
[out] orientation
Definition at line 711 of file g_syscalls.c.
Referenced by G_BuildHead(), and G_PositionEntityOnTag().
void trap_GetUsercmd (int clientNum, usercmd_t * cmd)
trap_GetUsercmd
Parameters
[in] clientNum
[in] cmd
Definition at line 599 of file g_syscalls.c.
Referenced by ClientSpawn(), and ClientThink().
void trap_GetUserinfo (int num, char * buffer, int bufferSize)
trap_GetUserinfo
Parameters
[in] num
[out] buffer
[in] bufferSize
Definition at line 320 of file g_syscalls.c.
Referenced by _et_trap_GetUserinfo(), _GetEntityName(), ClientBegin(), ClientConnect(), ClientUserinfoChanged(), G_PlayerBan(), G_players_cmd(), G_UpdateCharacter(), ETInterface::InterfaceSendMessage(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
trap_InPVS
Parameters
[in] p1
[in] p2
Returns
Definition at line 432 of file g_syscalls.c.
Referenced by G_LandmineSnapshotCallback(), G_VisibleFromBinoculars(), G_VisibleFromBinoculars_Box(), ETInterface::IsInPVS(), and ETInterface::TraceLine().
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
trap_InPVSIgnorePortals
Parameters
[in] p1
[in] p2
Returns
Definition at line 443 of file g_syscalls.c.
void trap_LinkEntity (gentity_t * ent)
trap_LinkEntity
Parameters
[in] ent
Definition at line 473 of file g_syscalls.c.
Referenced by _et_trap_LinkEntity(), aagun_spawn(), aagun_use(), artilleryGoAway(), artillerySpotterThink(), AutoBuildConstruction(), Blocked_Door(), Blocked_DoorRotate(), clamp_playerbehindgun(), ClientSpawn(), ClientThink_real(), constructiblemarker_setup(), CopyToBodyQue(), crate_die(), dust_angles_think(), etpro_ScriptAction_SetValues(), FinishSpawningItem(), firetrail_use(), flak_spawn(), flippy_table_use(), func_constructible_explode(), func_constructible_spawn(), func_constructible_use(), func_constructiblespawn(), func_explosive_spawn(), G_AdjustSingleClientPosition(), G_BuildHead(), G_BuildLeg(), G_CheckSpottedLandMines(), G_Lua_CreateEntity(), G_ModifyTOI(), G_MoverPush(), G_MoverTeam(), G_PositionEntityOnTag(), G_PredictPmove(), G_ReAdjustSingleClientPosition(), G_RealExplodedMissile(), G_RunEntity(), G_RunItem(), G_RunMissile(), G_ScriptAction_Create(), G_ScriptAction_SetModelFromBrushmodel(), G_SetEntState(), G_TempEntity(), HandleEntsThatBlockConstructible(), init_locker(), InitConstructible(), InitExplosive(), InitMover(), InitMoverRotate(), InitShooter(), landmine_setup(), LandMineTrigger(), LaunchItem(), MakeTemporarySolid(), mg42_die(), mg42_spawn(), mg42_use(), misc_beam_think(), misc_firetrails_think(), misc_spawner_use(), moveit(), OilSlick_remove(), player_die(), Props_Activated(), Props_Barrel_Die(), Props_Chair_Die(), Props_Chair_Think(), props_decoration_death(), props_flamethrower_init(), props_locker_death(), props_radio_dieSEVEN(), props_statue_death(), RespawnItem(), ReviveEntity(), script_linkentity(), script_model_med_spawn(), smoke_init(), smoke_toggle(), SP_alarm_box(), SP_corona(), SP_crate_32(), SP_crate_64(), SP_dlight(), SP_Dust(), SP_func_door_rotating(), SP_func_invisible_user(), SP_func_leaky(), SP_func_rotating(), SP_misc_cabinet_health(), SP_misc_cabinet_supply(), SP_misc_gamemodel(), SP_misc_portal_camera(), SP_misc_portal_surface(), SP_misc_spawner(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_Props_58x112tablew(), SP_Props_Bench(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_props_castlebed(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_Crate32x64(), SP_Props_DamageInflictor(), SP_props_decor_Scale(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_Props_Flipping_Table(), SP_props_gunsparks(), SP_Props_Locker_Tall(), SP_Props_Radio(), SP_Props_RadioSEVEN(), SP_props_shard_generator(), SP_props_snowGenerator(), SP_props_statue(), SP_script_multiplayer(), SP_SmokeDust(), SP_target_rumble(), SP_target_smoke(), SP_target_speaker(), SP_team_WOLF_checkpoint(), SP_trigger_flagonly(), SP_trigger_flagonly_multiple(), SP_trigger_multiple(), SP_trigger_objective_info(), SP_trigger_once(), SP_trigger_teleport(), sparks_angles_think(), Spawn_Junk(), Spawn_Shard(), SpawnPlatTrigger(), target_laser_think(), TeleportPlayer(), Think_SetupObjectiveInfo(), Think_SetupTrainTargets(), Think_SpawnNewDoorTrigger(), Touch_Item(), TryConstructing(), UndoTemporarySolid(), use_corona(), use_dlight(), Use_Func_Rotate(), Use_props_decoration(), Use_Static(), Weapon_Engineer(), and WolfReviveBbox().
qboolean trap_LoadTag (const char * filename)
trap_LoadTag
Parameters
[in] filename
Returns
Definition at line 721 of file g_syscalls.c.
Referenced by G_ScriptAction_ChangeModel(), SP_misc_gamemodel(), and SP_script_mover().
void trap_LocateGameData (gentity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * gameClients, int sizeofGClient)
trap_LocateGameData
Parameters
[in] gEnts
[in] numGEntities
[in] sizeofGEntity_t
[in] gameClients
[in] sizeofGClient
Definition at line 258 of file g_syscalls.c.
Referenced by G_InitGame(), and G_Spawn().
messageStatus_t trap_MessageStatus (int clientNum)
trap_MessageStatus
Parameters
[in] clientNum
Returns
Definition at line 808 of file g_syscalls.c.
int trap_Milliseconds (void)
trap_Milliseconds
Returns
Definition at line 91 of file cg_syscalls.c.
int trap_PointContents (const vec3_t point, int passEntityNum)
trap_PointContents
Parameters
[in] point
[in] passEntityNum
Returns
Definition at line 421 of file g_syscalls.c.
Referenced by ClientThink_real(), CopyToBodyQue(), G_PredictPmove(), G_RunItem(), ETInterface::GetPointContents(), limbo(), and SpectatorThink().
void trap_Printf (const char * fmt)
trap_Printf
Parameters
[in] fmt
Definition at line 64 of file g_syscalls.c.
Referenced by _et_G_Print(), G_DPrintf(), G_Printf(), and G_refPrintf().
int trap_RealTime (qtime_t * qtime)
trap_RealTime
Parameters
[out] qtime
Returns
Parameters
[in] qtime
Returns
Definition at line 1420 of file cg_syscalls.c.
void trap_SendConsoleCommand (int exec_when, const char * text)
trap_SendConsoleCommand
Parameters
[in] exec_when
[in] text
Definition at line 182 of file g_syscalls.c.
qboolean trap_SendMessage (int clientNum, char * buf, int buflen)
Sends binary messages. Since ETL 2.76 this is no longer void. See new return values.
Returns
1 if message is in queue (will be sent) - 0 not sent
Definition at line 798 of file g_syscalls.c.
void trap_SendServerCommand (int clientNum, const char * text)
trap_SendServerCommand
Parameters
[in] clientNum
[in] text
Definition at line 280 of file g_syscalls.c.
Referenced by _et_trap_SendServerCommand(), CheatsOk(), CheckExitRules(), checkpoint_use(), ClientBegin(), ClientCommand(), ClientConnect(), ClientThink_real(), ClientUserinfoChanged(), Cmd_Give_f(), Cmd_God_f(), Cmd_Ignore_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionReady_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), Cmd_Kill_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_Notarget_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_UnIgnore_f(), Cmd_Vote_f(), Cmd_WeaponStat_f(), Cmd_Where_f(), DoClientThinks(), fire_missile(), G_ApplyToFireTeam(), G_CheckSpottedLandMines(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_Damage(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DestroyFireteam(), G_EntitySound(), G_EntitySoundNoCut(), G_HQSay(), G_IntermissionMapList(), G_IntermissionVoteTally(), G_InviteToFireTeam(), G_MakeReferee(), G_Mute_v(), G_MuteClient(), G_PlaySound_Cmd(), G_PrintAccuracyLog(), G_PrintClientSpammyCenterPrint(), G_printMatchInfo(), G_ProposeFireTeamPlayer(), G_refWarning_cmd(), G_RegisterFireteam(), G_RemoveClientFromFireteams(), G_SayTo(), G_Script_ScriptParse(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_FadeAllSounds(), G_ScriptAction_MusicFade(), G_ScriptAction_MusicPlay(), G_ScriptAction_MusicStart(), G_ScriptAction_MusicStop(), G_SendMapEntityInfo(), G_SendScore(), G_SendSpectatorMapEntityInfo(), G_SendSystemMessage(), G_TeamCommand(), G_UnMute_v(), G_UnMuteClient(), G_UpdateCvars(), G_Voice(), G_WarnFireTeamPlayer(), HandleEntsThatBlockConstructible(), player_die(), PrintMsg(), ReviveEntity(), SetPlayerSpawn(), SetTeam(), Svcmd_Chat_f(), Svcmd_CP_f(), Svcmd_Say_f(), TeamplayInfoMessage(), Use_Target_Print(), and Weapon_Engineer().
void trap_SetBrushModel (gentity_t * ent, const char * name)
trap_SetBrushModel
Parameters
[in] ent
[in] name
Definition at line 350 of file g_syscalls.c.
Referenced by AutoBuildConstruction(), func_constructible_explode(), func_constructible_use(), func_constructiblespawn(), G_ScriptAction_SetModelFromBrushmodel(), HandleEntsThatBlockConstructible(), InitTrigger(), SP_alarm_box(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_door_rotating(), SP_func_explosive(), SP_func_invisible_user(), SP_func_leaky(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_secret(), SP_func_static(), SP_func_train(), SP_func_train_rotating(), SP_misc_constructiblemarker(), SP_Props_58x112tablew(), SP_Props_Bench(), SP_props_castlebed(), SP_Props_Crate32x64(), SP_props_decorBRUSH(), SP_Props_Flipping_Table(), SP_Props_Locker_Tall(), SP_Props_Radio(), SP_Props_RadioSEVEN(), SP_props_snowGenerator(), SP_props_statueBRUSH(), SP_script_mover(), and TryConstructing().
void trap_SetConfigstring (int num, const char * string)
trap_SetConfigstring
Parameters
[in] num
[in] string
Definition at line 298 of file g_syscalls.c.
Referenced by _et_G_ShaderRemapFlush(), _et_trap_SetConfigstring(), BeginIntermission(), CalculateRanks(), CC_loadconfig(), CheckExitRules(), CheckVote(), CheckWolfMP(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallVote_f(), Cmd_Vote_f(), G_BuildEndgameStats(), G_ClearMapXP(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_delayPrint(), G_FindConfigstringIndex(), G_GetMapXP(), G_InitGame(), G_loadMatchGame(), G_LogExit(), G_ModifyTOI(), G_pause_cmd(), G_refLockTeams_cmd(), G_refPause_cmd(), G_refSpeclockTeams_cmd(), G_RegisterCvars(), G_ReloadConfig(), G_RemoveConfigstringIndex(), G_RunFrame(), G_ScriptAction_MusicQueue(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetGlobalFog(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetWinner(), G_ScriptAction_ShaderRemapFlush(), G_SetConfigStringValue(), G_StoreMapXP(), G_Surrender_v(), G_UpdateCvars(), G_UpdateFireteamConfigString(), G_UpdateSkillsToClients(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), G_UpdateSvCvars(), objective_Register(), props_locker_mass(), SP_misc_constructiblemarker(), SP_script_mover(), SP_skyportal(), SP_trigger_objective_info(), SP_worldspawn(), target_effect(), and Use_target_fog().
void trap_SetUserinfo (int num, const char * buffer)
trap_SetUserinfo
Parameters
[in] num
[in] buffer
Definition at line 330 of file g_syscalls.c.
Referenced by _et_trap_SetUserinfo(), ETInterface::AddBot(), ClientUserinfoChanged(), and ETInterface::InterfaceSendMessage().
void trap_SnapVector (float * v)
trap_SnapVector
Parameters
[out] v
[in] v
Definition at line 1429 of file cg_syscalls.c.
void trap_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_Trace
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 365 of file g_syscalls.c.
Referenced by _et_trap_Trace(), BodySink(), CanDamage(), Cmd_Activate2_f(), Cmd_Activate_f(), DropToFloor(), DropToFloorG(), EntsThatRadiusCanDamage(), etpro_RadiusDamage(), FinishSpawningItem(), G_BurnTarget(), G_CheckForCursorHints(), G_DropWeapon(), G_HistoricalTrace(), G_LeaveTank(), G_PredictMissile(), G_RadiusDamage(), G_RunFlamechunk(), G_RunItem(), G_RunItemProp(), G_RunMissile(), G_SpectatorAttackFollow(), G_TestEntityPosition(), G_Trace(), G_VisibleFromBinoculars(), G_VisibleFromBinoculars_Box(), ETInterface::InterfaceSendMessage(), IsHeadShot(), IsLegShot(), Just_Got_Thrown(), Landmine_Check_Ground(), landmine_setup(), LaunchItem(), mg42_die(), moveit(), Prop_Check_Ground(), Prop_Touch(), Props_Chair_Think(), props_statue_blocked(), ReviveEntity(), target_laser_think(), ETInterface::TraceLine(), trap_EngineerTrace(), validOilSlickSpawnPoint(), Weapon_Artillery(), weapon_callAirStrike(), Weapon_FlamethrowerFire(), weapon_gpg40_fire(), weapon_grenadelauncher_fire(), weapon_mortar_fire(), Weapon_Syringe(), and WolfFindMedic().
void trap_TraceCapsule (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsule
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 395 of file g_syscalls.c.
Referenced by BodySink(), ClientThink_real(), G_TestEntityPosition(), and weapon_callAirStrike().
void trap_TraceCapsuleNoEnts (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsuleNoEnts
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
passEntityNum - unused
[in] contentmask
Definition at line 410 of file g_syscalls.c.
Referenced by ClientThink_real(), G_PredictPmove(), and SpectatorThink().
void trap_TraceNoEnts (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceNoEnts
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
passEntityNum - unused
[in] contentmask
Definition at line 380 of file g_syscalls.c.
Referenced by ETInterface::TraceLine().
void trap_UnlinkEntity (gentity_t * ent)
trap_UnlinkEntity
Parameters
[in] ent
Definition at line 482 of file g_syscalls.c.
Referenced by _et_trap_UnlinkEntity(), BodyUnlink(), clamp_playerbehindgun(), ClientBegin(), ClientConnect(), ClientDisconnect(), CopyToBodyQue(), crate_die(), ExitLevel(), flippy_table_use(), func_constructible_explode(), func_constructible_use(), func_constructiblespawn(), G_FreeEntity(), G_KillEnts(), G_MoverPush(), G_RunClient(), G_RunEntity(), G_RunMissile(), G_RunMover(), G_SetEntState(), limbo(), Props_Activated(), Props_Barrel_Die(), Props_Chair_Die(), props_locker_death(), shutoff_dlight(), smoke_toggle(), SP_func_explosive(), SP_func_rotating(), SP_func_static(), SP_script_model_med(), SP_script_mover(), SpectatorThink(), target_laser_off(), use_corona(), use_dlight(), Use_props_decoration(), Use_Static(), and Use_Target_Give().
void Use_BinaryMover (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_BinaryMover.
Parameters
[in,out] ent
[in] other
[in] activator
Todo:
: THIS IS STILL A HACK)
Todo:
: check out this line (see blocked mover in Use_TrinaryMover)
Definition at line 1594 of file g_mover.c.
Referenced by Do_Activate_f(), flippy_table_use(), G_TryDoor(), InitMover(), InitMoverRotate(), Touch_Button(), Touch_DoorTrigger(), and Touch_PlatCenterTrigger().
char* vtos (const vec3_t v)
This is just a convenience function for printing vectors.
Parameters
[in] v
Returns
Definition at line 141 of file cg_spawn.c.
Referenced by Cmd_Where_f(), FinishSpawningItem(), locateMaster(), misc_beam_start(), misc_spawner_think(), props_locker_spawn_item(), SP_func_timer(), SP_func_train(), SP_func_train_rotating(), SP_info_train_spline_main(), SP_misc_gamemodel(), SP_misc_spawner(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_path_corner(), SP_path_corner_2(), SP_props_snowGenerator(), SP_target_speaker(), SP_target_teleporter(), target_laser_start(), target_speaker_multiple(), Think_SetupTrainTargets(), and Think_SetupTrainTargets_rotating().
void weapon_callAirStrike (gentity_t * ent)
Launch airstrike as line of bombs mostly-perpendicular to line of grenade travel (close air support should always drop parallel to friendly lines, tho accidents do happen)
Parameters
[in,out] ent
Todo:
: HARD-CODED!
Definition at line 2689 of file g_weapon.c.
Referenced by weapon_checkAirStrikeThink().
void weapon_callSecondPlane (gentity_t * ent)
qboolean weapon_checkAirStrike (gentity_t * ent)
weapon_checkAirStrike
Parameters
[in,out] ent
Returns
Todo:
: this is a stupid workaround. Just store the parent team in the enitity itself and use that - no need to look up the parent
Definition at line 2575 of file g_weapon.c.
Referenced by weapon_checkAirStrikeThink().
void weapon_checkAirStrikeThink (gentity_t * ent)
weapon_checkAirStrikeThink
Parameters
[in,out] ent
Definition at line 2549 of file g_weapon.c.
void Weapon_MagicAmmo_Ext (gentity_t * ent, vec3_t viewpos, vec3_t tosspos, vec3_t velocity)
Weapon_MagicAmmo_Ext.
Parameters
[in,out] ent
[in,out] viewpos
[in,out] tosspos
[in] velocity
Definition at line 268 of file g_weapon.c.
Referenced by G_DropLimboAmmo(), and Weapon_MagicAmmo().
void Weapon_Medic_Ext (gentity_t * ent, vec3_t viewpos, vec3_t tosspos, vec3_t velocity)
Weapon_Medic_Ext.
Parameters
[in,out] ent
[in,out] viewpos
[in,out] tosspos
[in] velocity
Definition at line 190 of file g_weapon.c.
Referenced by G_DropLimboHealth(), and Weapon_Medic().
void weapon_smokeBombExplode (gentity_t * ent)
Increases postsmoke time from 2000->32000, this way, the entity is still around while the smoke is around, so we can check if it blocks bot's vision.
eeeeeh this is wrong. 32 seconds is way too long. Also - we shouldn't be rendering the grenade anymore after the smoke stops and definately not send it to the client
back to the old value 2000, now that it looks like smoke disappears more quickly
Parameters
[in,out] ent
Definition at line 3093 of file g_weapon.c.
Variable Documentation
const char* aTeams[TEAM_NUM_TEAMS]
Definition at line 1538 of file g_team.c.
Referenced by Cmd_Follow_f(), G_lock_cmd(), G_pause_cmd(), G_players_cmd(), G_printMatchInfo(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_specinvite_cmd(), G_speclock_cmd(), G_teamJoinCheck(), and G_teamready_cmd().
vmCvar_t g_alliedmapxp
Definition at line 231 of file g_main.c.
vmCvar_t g_alliedmaxlives
Definition at line 139 of file g_main.c.
Referenced by ClientBegin(), ClientConnect(), respawn(), SetTeam(), and SpectatorClientEndFrame().
vmCvar_t g_alliedwins
Definition at line 238 of file g_main.c.
vmCvar_t g_altStopwatchMode
Definition at line 124 of file g_main.c.
Referenced by G_InitWorldSession(), and G_ReadSessionData().
vmCvar_t g_antilag
Definition at line 171 of file g_main.c.
Referenced by G_AntiLag_v(), G_checkServerToggle(), G_HistoricalTrace(), G_HistoricalTraceBegin(), G_HistoricalTraceEnd(), IsHeadShot(), and IsLegShot().
vmCvar_t g_antiwarp
Definition at line 260 of file g_main.c.
Referenced by DoClientThinks(), and G_DoAntiwarp().
vmCvar_t g_autoFireteams
Definition at line 252 of file g_main.c.
Referenced by G_RegisterFireteam(), and SetTeam().
vmCvar_t g_axismapxp
Definition at line 230 of file g_main.c.
vmCvar_t g_axismaxlives
Definition at line 140 of file g_main.c.
Referenced by ClientBegin(), ClientConnect(), respawn(), SetTeam(), and SpectatorClientEndFrame().
vmCvar_t g_axiswins
Definition at line 237 of file g_main.c.
vmCvar_t g_balancedteams
Definition at line 145 of file g_main.c.
Referenced by G_BalancedTeams_v(), and G_checkServerToggle().
vmCvar_t g_banIPs
Definition at line 149 of file g_main.c.
Referenced by G_ProcessIPBans().
vmCvar_t g_bluelimbotime
Definition at line 163 of file g_main.c.
Referenced by Bot_Util_CheckForSuicide(), ETInterface::InterfaceSendMessage(), and SpectatorClientEndFrame().
vmCvar_t g_campaignFile
Definition at line 284 of file g_main.c.
Referenced by G_ParseCampaigns().
g_campaignInfo_t g_campaigns[]
Definition at line 65 of file g_main.c.
Referenced by ClientConnect(), ClientEndFrame(), G_Campaign_v(), G_createStats(), G_LoadCampaignsFromFile(), G_MapIsValidCampaignStartMap(), G_ParseCampaigns(), G_ReadSessionData(), G_RestartCampaign_v(), G_SendScore_Add(), SpectatorClientEndFrame(), Svcmd_Campaign_f(), and Svcmd_ListCampaigns_f().
vmCvar_t g_cheats
Definition at line 102 of file g_main.c.
Referenced by Bot_Interface_Init(), Bot_Interface_Update(), CheatsOk(), Cmd_SetViewpos_f(), ETInterface::InterfaceSendMessage(), and Svcmd_RevivePlayer().
vmCvar_t g_complaintlimit
number of complaints allowed before kick/ban
Definition at line 133 of file g_main.c.
Referenced by Cmd_Vote_f(), and player_die().
g_constructible_stats_t g_constructible_classes[NUM_CONSTRUCTIBLE_CLASSES]
Definition at line 5642 of file g_mover.c.
Referenced by G_ScriptAction_ConstructibleClass(), and SP_func_explosive().
vmCvar_t g_corpses
Definition at line 338 of file g_main.c.
Referenced by BodySink2(), CopyToBodyQue(), G_TempTraceIgnorePlayersAndBodies(), G_Trace(), and InitBodyQue().
vmCvar_t g_countryflags
Definition at line 286 of file g_main.c.
Referenced by ClientConnect(), and GeoIP_open().
vmCvar_t g_covertopsChargeTime
Definition at line 169 of file g_main.c.
Referenced by G_ScriptAction_SetChargeTimeFactor().
vmCvar_t g_currentCampaign
Definition at line 233 of file g_main.c.
Referenced by G_LoadCampaignsFromFile().
vmCvar_t g_currentCampaignMap
Definition at line 234 of file g_main.c.
Referenced by G_LoadCampaignsFromFile().
vmCvar_t g_currentRound
Definition at line 122 of file g_main.c.
Referenced by ClientEndFrame(), G_createStats(), G_InitWorldSession(), G_matchInfoDump(), G_ReadSessionData(), G_SendScore_Add(), and SpectatorClientEndFrame().
vmCvar_t g_customConfig
Definition at line 324 of file g_main.c.
Referenced by G_configSet(), G_PrintConfigs(), and G_ReloadConfig().
vmCvar_t g_debugAlloc
Definition at line 109 of file g_main.c.
Referenced by G_Alloc().
vmCvar_t g_debugBullets
Definition at line 110 of file g_main.c.
Referenced by Bullet_Fire_Extended(), Fire_Lead_Ext(), G_Damage(), G_RunFlamechunk(), IsHeadShot(), and IsLegShot().
vmCvar_t g_debugConstruct
Definition at line 220 of file g_main.c.
Referenced by ReadyToConstruct().
vmCvar_t g_debugDamage
Definition at line 108 of file g_main.c.
Referenced by G_Damage().
vmCvar_t g_debugHitboxes
Definition at line 333 of file g_main.c.
vmCvar_t g_debugMove
Definition at line 107 of file g_main.c.
Referenced by ClientThink_real().
vmCvar_t g_debugPlayerHitboxes
Definition at line 334 of file g_main.c.
Referenced by ClientEndFrame(), and ClientThink_real().
vmCvar_t g_debugSkills
Definition at line 250 of file g_main.c.
Referenced by G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), and G_DebugOpenSkillLog().
vmCvar_t g_dedicated
Definition at line 99 of file g_main.c.
Referenced by ClientUserinfoChanged(), ETInterface::DebugLine(), ETInterface::DebugRadius(), G_Say(), G_Voice(), ETInterface::GetEntityPosition(), ETInterface::GetEntityWorldAABB(), Svcmd_Chat_f(), and Svcmd_Say_f().
vmCvar_t g_developer
Definition at line 157 of file g_main.c.
Referenced by ClientUserinfoChanged(), and G_ScriptAction_SetState().
vmCvar_t g_disableComplaints
Definition at line 257 of file g_main.c.
Referenced by player_die().
vmCvar_t g_doWarmup
Definition at line 146 of file g_main.c.
Referenced by G_checkReady(), G_readyMatchState(), and G_verifyMatchState().
vmCvar_t g_dropAmmo
Definition at line 273 of file g_main.c.
Referenced by G_DropLimboAmmo().
vmCvar_t g_dropHealth
Definition at line 272 of file g_main.c.
Referenced by G_DropLimboHealth().
vmCvar_t g_enforcemaxlives
Temp ban with maxlives between rounds.
Definition at line 142 of file g_main.c.
Referenced by ClientBegin(), and ClientConnect().
vmCvar_t g_engineerChargeTime
Definition at line 166 of file g_main.c.
Referenced by G_ScriptAction_SetChargeTimeFactor().
gentity_t g_entities[]
was explicitly set to MAX_ENTITIES
Definition at line 62 of file g_main.c.
Referenced by _et_AddWeaponToPlayer(), _et_G_AddEvent(), _et_G_AddSkillPoints(), _et_G_ClientSound(), _et_G_Damage(), _et_G_FreeEntity(), _et_G_GetSpawnVar(), _et_G_HistoricalTrace(), _et_G_LoseSkillPoints(), _et_G_Lua_CreateEntity(), _et_G_ResetXP(), _et_G_Say(), _et_G_SetEntState(), _et_G_SetSpawnVar(), _et_G_Sound(), _et_G_TempEntity(), _et_G_XP_Set(), _et_gentity_get(), _et_gentity_set(), _et_GetCurrentWeapon(), _et_MutePlayer(), _et_RemoveWeaponFromPlayer(), _et_trap_LinkEntity(), _et_trap_UnlinkEntity(), _et_UnmutePlayer(), _GetEntityClass(), _GetEntityName(), _GetEntityTeam(), aagun_fire(), aagun_spawn(), aagun_stopusing(), aagun_think(), aagun_use(), ETInterface::AddBot(), ammo_touch(), AutoBuildConstruction(), Bot_Event_AddWeapon(), Bot_Event_ChatMessage(), Bot_Event_Death(), Bot_Event_EntityCreated(), Bot_Event_EntityDeleted(), Bot_Event_FireTeam_Proposal(), Bot_Event_FireTeam_Warn(), Bot_Event_FireTeamCreated(), Bot_Event_FireTeamDestroyed(), Bot_Event_FireWeapon(), Bot_Event_Healed(), Bot_Event_InviteFireTeam(), Bot_Event_JoinedFireTeam(), Bot_Event_KilledSomeone(), Bot_Event_LeftFireTeam(), Bot_Event_MortarImpact(), Bot_Event_PostTriggerMine(), Bot_Event_PreTriggerMine(), Bot_Event_RecievedAmmo(), Bot_Event_RemoveWeapon(), Bot_Event_ResetWeapons(), Bot_Event_Revived(), Bot_Event_Spectated(), Bot_Event_TakeDamage(), Bot_Event_VoiceMacro(), Bot_Interface_Update(), Bot_Queue_EntityCreated(), Bot_Util_CheckForGoalEntity(), Bullet_Fire_Extended(), C_gentity_ptr_to_entNum(), CanDamage(), ETInterface::ChangeClass(), ETInterface::ChangeTeam(), CheatsOk(), checkpoint_use(), CheckTeamStatus(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientImpacts(), ClientInactivityTimer(), ClientNumberFromString(), ClientSpawn(), ClientStoreSurfaceFlags(), ClientThink(), ClientThink_real(), ClientUserinfoChanged(), Cmd_Activate2_f(), Cmd_Activate_f(), Cmd_CallVote_f(), Cmd_FireTeam_MP_f(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_Ignore_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionReady_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), Cmd_Kill_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_Notarget_f(), Cmd_ResetSetup_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_UnIgnore_f(), Cmd_Vote_f(), Cmd_WeaponStat_f(), Cmd_Where_f(), constructible_indicator_think(), constructiblemarker_setup(), CopyToBodyQue(), Do_Activate2_f(), DoClientThinks(), DynaFree(), ENTINDEX(), EntityFromHandle(), EntsThatRadiusCanDamage(), etpro_AddUsercmd(), etpro_RadiusDamage(), explosive_indicator_think(), Fire_Lead_Ext(), fire_missile(), FireWeapon(), flak_spawn(), func_constructible_explode(), func_constructible_underconstructionthink(), func_constructible_use(), func_constructiblespawn(), func_explosive_explode(), G_AddClientToFireteam(), G_AdjustClientPositions(), G_AnimScriptSound(), G_ApplyToFireTeam(), G_AttachBodyParts(), G_BounceMissile(), G_CalcClientAccuracies(), G_checkReady(), G_CheckSpottedLandMines(), G_ClassCount(), G_CountTeamLandmines(), G_CountTeamMedics(), G_createStats(), G_Damage(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_delayPrint(), G_DestroyFireteam(), G_DettachBodyParts(), G_EntitiesFree(), G_ExplodeSatchels(), G_FadeItems(), G_Find(), G_FindByTargetname(), G_FindByTargetnameFast(), G_FindFloat(), G_FindFreeFireteamIdent(), G_FindFreePublicFireteam(), G_FindInt(), G_FindSatchel(), G_FindVector(), G_FireteamNumberForString(), G_FlameDamage(), G_FreeSatchel(), G_GetFireteamTeam(), G_GetTeamFromEntity(), G_GiveAdminOfFireTeam(), G_HistoricalTrace(), G_HQSay(), G_InitGame(), G_InitGentity(), G_IntermissionMapList(), G_IntermissionVoteTally(), G_InviteToFireTeam(), G_IsFireteamLeader(), G_IsOnFireteam(), G_Kick_v(), G_KickFireTeamPlayer(), G_LandmineSnapshotCallback(), G_LandmineThink(), G_LinkDamageParents(), G_LinkDebris(), G_LuaHook_WeaponFire(), G_makesc_cmd(), G_MakeShoutcaster(), G_matchInfoDump(), G_MissileImpact(), G_ModifyTOI(), G_MoverPush(), G_Mute_v(), G_NeedEngineers(), G_OnlyBotsInFireteam(), G_PlayerBan(), G_PlayerCanBeSeenByOthers(), G_players_cmd(), G_PlaySound_Cmd(), G_PopupMessageForMines(), G_PreFilledMissileEntity(), G_PrintAccuracyLog(), G_PrintClientSpammyCenterPrint(), G_printMatchInfo(), G_ProposeFireTeamPlayer(), G_PushPlayer(), G_RadiusDamage(), G_RealExplodedMissile(), G_ref_cmd(), G_Referee_v(), G_refMakeShoutcaster_cmd(), G_refMute_cmd(), G_refPause_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_refRemoveShoutcaster_cmd(), G_RegisterFireteam(), G_RemoveClientFromFireteams(), G_removesc_cmd(), G_RemoveShoutcaster(), G_removeSpecInvite(), G_ResetTempTraceIgnoreEnts(), G_ResetXP(), G_RunFlamechunk(), G_RunItemProp(), G_Say(), G_SayTo(), G_ScriptAction_Accum(), G_ScriptAction_AddTankAmmo(), G_ScriptAction_Construct(), G_ScriptAction_Delete(), G_ScriptAction_RepairMG42(), G_ScriptAction_SetDamagable(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetState(), G_ScriptAction_SetTankAmmo(), G_ScriptAction_Trigger(), G_SendMapEntityInfo(), G_SendScore(), G_SendScore_Add(), G_SendSpectatorMapEntityInfo(), G_SendSystemMessage(), G_SetClientWeapons(), G_SetEntState(), G_shuffleTeamsXP(), G_Spawn(), G_specinvite_cmd(), G_SpectatorAttackFollow(), G_statsall_cmd(), G_statsPrint(), G_SweepForLandmines(), G_SwitchBodyPartEntity(), G_TeamCount(), G_TeamDataForString(), G_TempTraceIgnoreEntity(), G_TempTraceIgnorePlayersAndBodies(), G_TestEntityPosition(), G_TouchTriggers(), G_Trace(), G_Unreferee_v(), G_updateSpecLock(), G_UpdateTeamMapData(), G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_DisguisedPlayer(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), G_UpdateTeamMapData_Tank(), G_UpgradeSkill(), G_Voice(), G_VoiceTo(), G_WarnFireTeamPlayer(), G_WriteClientSessionData(), ETInterface::GetAutoNavFeatures(), ETInterface::GetEntityCategory(), ETInterface::GetEntityFlags(), ETInterface::GetEntityGroundEntity(), ETInterface::GetEntityOwner(), ETInterface::GetEntityVelocity(), ETInterface::GetGoals(), ETInterface::GetPlayerInfo(), GibEntity(), HandleEntsThatBlockConstructible(), HandleFromEntity(), heal_touch(), ETInterface::IDFromEntity(), INDEXENT(), info_limbo_camera_setup(), ETInterface::InterfaceSendMessage(), IsHeadShot(), IsLegShot(), landmine_setup(), LandminePostThink(), LaunchItem(), limbo(), locateMaster(), mg42_die(), mg42_fire(), mg42_spawn(), mg42_stopusing(), mg42_think(), mg42_use(), misc_firetrails_think(), multi_trigger(), OilParticles_think(), P_WorldEffects(), Pickup_Health(), Pickup_Weapon(), player_die(), PrintMsg(), Props_Activated(), props_statue_blocked(), ETInterface::RemoveBot(), ReTransmitWeapons(), ReviveEntity(), script_mover_spawn(), SetPlayerSpawn(), SetTeam(), SP_misc_constructiblemarker(), SP_script_mover(), SP_trigger_objective_info(), SP_worldspawn(), SpectatorThink(), SpotWouldTelefrag(), StopFollowing(), StuckInClient(), Svcmd_Burn(), Svcmd_Die(), Svcmd_EntityList_f(), Svcmd_Fling(), Svcmd_ForceTeam_f(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Svcmd_Pip(), Svcmd_ResetMatch_f(), Svcmd_RevivePlayer(), Svcmd_Unfreeze(), target_laser_think(), Team_DroppedFlagThink(), Team_ResetFlag(), Team_TouchOurFlag(), TeamplayInfoMessage(), Think_SetupObjectiveInfo(), Think_SetupTrainTargets(), Think_SetupTrainTargets_rotating(), Touch_flagonly(), Touch_flagonly_multiple(), ETInterface::TraceLine(), TryConstructing(), ETInterface::UpdateBotInput(), Use_Target_Print(), Use_target_remove_powerups(), validOilSlickSpawnPoint(), Weapon_Artillery(), weapon_callAirStrike(), weapon_checkAirStrike(), Weapon_Engineer(), Weapon_Knife(), Weapon_MagicAmmo_Ext(), Weapon_Medic_Ext(), Weapon_Syringe(), WolfFindMedic(), and WolfReviveBbox().
vmCvar_t g_excludedMaps
Definition at line 281 of file g_main.c.
vmCvar_t g_extendedNames
Definition at line 356 of file g_main.c.
Referenced by ClientConnect(), and ClientUserinfoChanged().
vmCvar_t g_fastres
Fast medic res'ing.
Definition at line 141 of file g_main.c.
Referenced by ClientSpawn(), and ReviveEntity().
vmCvar_t g_fieldopsChargeTime
Definition at line 167 of file g_main.c.
Referenced by G_ScriptAction_SetChargeTimeFactor().
vmCvar_t g_filterBan
Definition at line 150 of file g_main.c.
Referenced by G_FilterPacket().
vmCvar_t g_filtercams
Definition at line 135 of file g_main.c.
vmCvar_t g_forcerespawn
Definition at line 105 of file g_main.c.
Referenced by ClientThink_real().
vmCvar_t g_friendlyFire
Definition at line 93 of file g_main.c.
Referenced by G_BurnTarget(), G_checkServerToggle(), G_Damage(), G_FriendlyFire_v(), and weapon_checkAirStrike().
vmCvar_t g_gamestate
Definition at line 125 of file g_main.c.
Referenced by aagun_think(), ClientBegin(), ClientDisconnect(), ClientEndFrame(), ClientEvents(), ClientInactivityTimer(), ClientSpawn(), Cmd_Give_f(), Cmd_IntermissionReady_f(), Cmd_Kill_f(), Cmd_Vote_f(), FireWeapon(), func_constructible_underconstructionthink(), G_AddSkillPoints(), G_addStats(), G_addStatsHeadShot(), G_ComputeMaxLives(), G_configSet(), G_Damage(), G_DoAntiwarp(), G_DropLimboHealth(), G_InitWorldSession(), G_IntermissionMapVote(), G_LoseSkillPoints(), G_Nextmap_v(), G_pause_cmd(), G_players_cmd(), G_ReadSessionData(), G_ready_cmd(), G_readyMatchState(), G_refAllReady_cmd(), G_refPause_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_EndRound(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetWinner(), G_ScriptAction_TeamVoiceAnnounce(), G_ScriptAction_VoiceAnnounce(), G_StartMatch_v(), G_Surrender_v(), G_teamJoinCheck(), G_teamready_cmd(), G_teamReset(), G_verifyMatchState(), G_WriteSessionData(), ETInterface::InterfaceSendMessage(), mg42_think(), player_die(), respawn(), SetTeam(), SP_worldspawn(), SpectatorClientEndFrame(), Svcmd_ResetMatch_f(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), Svcmd_SwapTeams_f(), TossWeapons(), Touch_Item(), and Weapon_Artillery().
vmCvar_t g_gametype
Definition at line 90 of file g_main.c.
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), ClientEndFrame(), ClientSpawn(), ClientThink_real(), Cmd_God_f(), Cmd_IntermissionReady_f(), G_AddSkillPoints(), G_allowFollow(), G_BuildEndgameStats(), G_CallSpawn(), G_Campaign_v(), G_checkServerToggle(), G_createStats(), G_Gametype_v(), G_InitWorldSession(), G_IntermissionMapList(), G_IntermissionMapVote(), G_IntermissionVoteTally(), G_LoadCampaignsFromFile(), G_LoseSkillPoints(), G_Map_v(), G_matchInfoDump(), G_NextCampaign_v(), G_Nextmap_v(), G_ParseCampaigns(), G_players_cmd(), G_printMatchInfo(), G_ReadSessionData(), G_readyMatchState(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_resetModeState(), G_resetRoundState(), G_RestartCampaign_v(), G_Script_ScriptLoad(), G_ScriptAction_SetRoundTimelimit(), G_ScriptAction_SetWinner(), G_SendScore_Add(), G_teamJoinCheck(), G_verifyMatchState(), G_voteHelp(), G_WriteSessionData(), ETInterface::InterfaceSendMessage(), player_die(), respawn(), SetTeam(), SP_info_limbo_camera(), SpectatorClientEndFrame(), and Weapon_Syringe().
vmCvar_t g_gravity
Definition at line 101 of file g_main.c.
Referenced by AimAtTarget(), Bot_Interface_Update(), ClientThink_real(), and SP_func_pendulum().
vmCvar_t g_heavyWeaponRestriction
Definition at line 251 of file g_main.c.
Referenced by G_IsWeaponDisabled(), G_MaxAvailableAirstrikes(), and G_MaxAvailableArtillery().
vmCvar_t g_inactivity
Definition at line 106 of file g_main.c.
Referenced by ClientBegin(), ClientInactivityTimer(), ClientSpawn(), and SetTeam().
vmCvar_t g_intermissionReadyPercent
Definition at line 320 of file g_main.c.
vmCvar_t g_intermissionTime
Definition at line 319 of file g_main.c.
vmCvar_t g_ipcomplaintlimit
Definition at line 134 of file g_main.c.
Referenced by G_FindFreeComplainIP().
vmCvar_t g_knockback
Definition at line 103 of file g_main.c.
Referenced by G_Damage().
vmCvar_t g_landminetimeout
Definition at line 221 of file g_main.c.
Referenced by ClientDisconnect(), ClientSpawn(), G_shuffleTeamsXP(), and SetTeam().
vmCvar_t g_lms_currentMatch
Definition at line 242 of file g_main.c.
vmCvar_t g_lms_followTeamOnly
Definition at line 244 of file g_main.c.
Referenced by G_allowFollow().
vmCvar_t g_lms_lockTeams
Definition at line 243 of file g_main.c.
Referenced by G_readyMatchState(), and G_teamJoinCheck().
vmCvar_t g_lms_matchlimit
Definition at line 241 of file g_main.c.
vmCvar_t g_lms_roundlimit
Definition at line 240 of file g_main.c.
vmCvar_t g_lms_teamForceBalance
Definition at line 239 of file g_main.c.
Referenced by SetTeam().
vmCvar_t g_log
Definition at line 129 of file g_main.c.
Referenced by ClientUserinfoChanged().
vmCvar_t g_mapConfigs
Definition at line 323 of file g_main.c.
vmCvar_t g_mapScriptDirectory
Definition at line 322 of file g_main.c.
Referenced by G_Script_ScriptLoad().
vmCvar_t g_mapVoteFlags
Definition at line 278 of file g_main.c.
Referenced by ClientDisconnect(), G_IntermissionMapList(), and G_Nextmap_v().
vmCvar_t g_maxclients
allow this many total, including spectators
Definition at line 96 of file g_main.c.
Referenced by Bot_Interface_Update(), ClientInactivityTimer(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), G_CalcClientAccuracies(), G_OnlyBotsInFireteam(), G_PlaySound_Cmd(), G_RemoveClientFromFireteams(), ETInterface::GetEntityOwner(), ETInterface::GetPlayerInfo(), ETInterface::InterfaceSendMessage(), and ETInterface::RemoveBot().
vmCvar_t g_maxGameClients
allow this many active
Definition at line 97 of file g_main.c.
Referenced by SetTeam().
vmCvar_t g_maxlives
number of respawns allowed (0==infinite)
Definition at line 136 of file g_main.c.
Referenced by ClientBegin(), ClientConnect(), respawn(), SetTeam(), and SpectatorClientEndFrame().
vmCvar_t g_maxlivesRespawnPenalty
Definition at line 137 of file g_main.c.
Referenced by limbo(), and SpectatorClientEndFrame().
vmCvar_t g_maxMapsVotedFor
Definition at line 279 of file g_main.c.
Referenced by G_IntermissionMapList(), and G_IntermissionVoteTally().
vmCvar_t g_maxWarp
Definition at line 261 of file g_main.c.
Referenced by ClientEndFrame(), and ClientThink_real().
vmCvar_t g_medicChargeTime
Definition at line 165 of file g_main.c.
Referenced by G_ScriptAction_SetChargeTimeFactor().
vmCvar_t g_minGameClients
we need at least this many before match actually starts
Definition at line 98 of file g_main.c.
Referenced by G_checkReady().
vmCvar_t g_minMapAge
Definition at line 280 of file g_main.c.
vmCvar_t g_misc
Definition at line 317 of file g_main.c.
Referenced by G_PushPlayer(), and Weapon_Engineer().
vmCvar_t g_motd
Definition at line 111 of file g_main.c.
Referenced by SP_worldspawn().
vmCvar_t g_moverScale
Definition at line 326 of file g_main.c.
Referenced by G_ScriptAction_FollowSpline(), G_ScriptAction_GotoMarker(), Reached_Train(), and Reached_Train_rotating().
vmCvar_t g_movespeed
How fast do SP player and allied bots move?
Definition at line 228 of file g_main.c.
Referenced by ETInterface::InterfaceSendMessage().
vmCvar_t g_needpass
Definition at line 144 of file g_main.c.
vmCvar_t g_nextcampaign
Definition at line 255 of file g_main.c.
Referenced by G_checkServerToggle().
vmCvar_t g_nextmap
Definition at line 254 of file g_main.c.
Referenced by G_checkServerToggle().
vmCvar_t g_nextTimeLimit
Definition at line 117 of file g_main.c.
Referenced by G_matchInfoDump(), and G_ScriptAction_SetRoundTimelimit().
vmCvar_t g_noTeamSwitching
Definition at line 123 of file g_main.c.
Referenced by SetTeam().
vmCvar_t g_OmniBotEnable
Definition at line 83 of file g_main.c.
Referenced by Bot_Interface_Init().
vmCvar_t g_OmniBotFlags
Definition at line 84 of file g_main.c.
Referenced by _EmplacedGunIsMountable(), _TankIsMountable(), Bot_Interface_Update(), Cmd_Activate2_f(), G_LandmineThink(), and ETInterface::GetEntityFlags().
vmCvar_t g_OmniBotPath
Definition at line 82 of file g_main.c.
Referenced by Bot_Interface_Init().
vmCvar_t g_OmniBotPlaying
Definition at line 85 of file g_main.c.
Referenced by Bot_Interface_Update(), and ClientInactivityTimer().
vmCvar_t g_password
Definition at line 94 of file g_main.c.
Referenced by ClientConnect().
vmCvar_t g_protect
Definition at line 268 of file g_main.c.
Referenced by ClientConnect(), and ClientUserinfoChanged().
vmCvar_t g_realHead
Definition at line 351 of file g_main.c.
Referenced by G_AntilagSafe(), G_BuildHead(), and G_BuildLeg().
vmCvar_t g_redlimbotime
Definition at line 162 of file g_main.c.
Referenced by Bot_Util_CheckForSuicide(), ETInterface::InterfaceSendMessage(), and SpectatorClientEndFrame().
vmCvar_t g_resetXPMapCount
Definition at line 282 of file g_main.c.
vmCvar_t g_restarted
Definition at line 128 of file g_main.c.
Referenced by SP_worldspawn().
vmCvar_t g_scriptDebug
what level of detail do we want script printing to go to.
Definition at line 225 of file g_main.c.
Referenced by etpro_ScriptAction_SetValues(), G_Lua_CreateEntity(), G_Script_GetEventIndex(), G_Script_ScriptRun(), G_ScriptAction_Create(), G_ScriptAction_SetState(), and G_ScriptAction_StartAnimation().
vmCvar_t g_scriptDebugLevel
filter out script debug messages from other entities
Definition at line 226 of file g_main.c.
Referenced by G_ScriptAction_Print().
vmCvar_t g_scriptDebugTarget
Definition at line 227 of file g_main.c.
Referenced by G_Script_GetEventIndex(), and G_Script_ScriptRun().
vmCvar_t g_scriptName
name of script file to run (instead of default for that map)
Definition at line 155 of file g_main.c.
vmCvar_t g_shove
Definition at line 275 of file g_main.c.
Referenced by G_PushPlayer().
vmCvar_t g_skipCorrection
Definition at line 354 of file g_main.c.
Referenced by ClientEndFrame().
vmCvar_t g_soldierChargeTime
Definition at line 168 of file g_main.c.
Referenced by G_ScriptAction_SetChargeTimeFactor().
vmCvar_t g_spectatorInactivity
Definition at line 173 of file g_main.c.
Referenced by ClientBegin(), ClientInactivityTimer(), and SetTeam().
vmCvar_t g_speed
Definition at line 100 of file g_main.c.
Referenced by ClientThink_real().
vmCvar_t g_stickyCharge
Definition at line 366 of file g_main.c.
Referenced by ClientSpawn(), and limbo().
vmCvar_t g_swapteams
Definition at line 126 of file g_main.c.
Referenced by G_InitWorldSession(), and G_ReadSessionData().
vmCvar_t g_teamForceBalance
Definition at line 148 of file g_main.c.
Referenced by SetTeam().
vmCvar_t g_timelimit
Definition at line 92 of file g_main.c.
Referenced by Bot_Interface_Update(), G_ComputeMaxLives(), G_matchInfoDump(), G_Timelimit_v(), and ETInterface::InterfaceSendMessage().
vmCvar_t g_userAim
Definition at line 159 of file g_main.c.
Referenced by Bullet_Fire().
vmCvar_t g_userAlliedRespawnTime
Definition at line 120 of file g_main.c.
Referenced by G_ScriptAction_AlliedRespawntime().
vmCvar_t g_userAxisRespawnTime
Definition at line 121 of file g_main.c.
Referenced by G_ScriptAction_AxisRespawntime().
vmCvar_t g_userTimeLimit
Definition at line 119 of file g_main.c.
Referenced by G_ScriptAction_SetRoundTimelimit().
vmCvar_t g_voiceChatsAllowed
number before spam control
Definition at line 138 of file g_main.c.
Referenced by G_Voice().
vmCvar_t g_voting
see VOTEF_* defines
Definition at line 336 of file g_main.c.
Referenced by Cmd_CallVote_f().
vmCvar_t g_warmup
Definition at line 115 of file g_main.c.
const char* gameNames[]
Definition at line 69 of file g_main.c.
Referenced by G_Gametype_v(), G_GametypeList(), G_InitGame(), and G_RegisterCvars().
GeoIP* gidb
Definition at line 41 of file geoip.c.
Referenced by ClientConnect().
level_locals_t level
Definition at line 49 of file g_main.c.
Referenced by _et_G_LogPrint(), _et_G_ShaderRemap(), _et_G_XP_Set(), _TankIsMountable(), aagun_spawn(), aagun_think(), aagun_track(), AddKillScore(), ammo_touch(), AutoBuildConstruction(), BecomeExplosion(), Blocked_Door(), Blocked_DoorRotate(), BodySink(), BodySink2(), Bot_EntInvisibleBySmokeBomb(), Bot_Interface_Update(), Bot_Util_CheckForSuicide(), CalcMuzzlePoints(), CC_cvarempty(), CC_loadconfig(), CC_svcvar(), checkpoint_hold_think(), checkpoint_spawntouch(), checkpoint_touch(), checkpoint_use(), CheckTeamStatus(), clamp_playerbehindgun(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientEndFrame(), ClientForString(), ClientInactivityTimer(), ClientNumberFromString(), ClientNumbersFromString(), ClientSpawn(), ClientThink_real(), ClientUserinfoChanged(), Cmd_Activate_f(), Cmd_CallVote_f(), Cmd_DropObjective_f(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_God_f(), Cmd_Ignore_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), Cmd_Kill_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_UnIgnore_f(), Cmd_Vote_f(), constructible_indicator_think(), CopyToBodyQue(), CountPlayerClass(), crate_animate(), crate_die(), Do_Activate_f(), DropToFloor(), DropToFloorG(), DynaSink(), etpro_RadiusDamage(), etpro_ScriptAction_SetValues(), explosive_indicator_think(), FindClientByName(), finishSpawningKeyedMover(), fire_flamebarrel(), fire_flamechunk(), fire_missile(), flak_spawn(), func_constructible_underconstructionthink(), func_constructiblespawn(), func_explosive_explode(), func_timer_think(), G_AddAirstrikeToCounters(), G_AddArtilleryToCounters(), G_AddEvent(), G_AddSkillPoints(), G_AddSpawnVarToken(), G_AdjustClientPositions(), G_AdjustSingleClientPosition(), G_AirStrikeThink(), G_AllocDebrisChunk(), G_allowFollow(), G_AntilagSafe(), G_ApplyToFireTeam(), G_AttachBodyParts(), G_AvailableAirstrike(), G_AvailableArtillery(), G_BalancedTeams_v(), G_BlockThink(), G_BounceItem(), G_BounceMissile(), G_BuildEndgameStats(), G_BuildHead(), G_BuildLeg(), G_BurnMeGood(), G_BurnTarget(), G_CalcClientAccuracies(), G_Campaign_v(), G_CheckForExistingAnimModelInfo(), G_checkReady(), G_checkServerToggle(), G_CheckSpottedLandMines(), G_ClassCount(), G_clientFlagIndicator(), G_ClientSound(), G_cmdDebounce(), G_ComputeMaxLives(), G_Config_v(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_configSet(), G_ConvertToSpawnPointIndex(), G_CountTeamFieldops(), G_CountTeamFireteams(), G_CountTeamLandmines(), G_CountTeamMedics(), G_createStats(), G_Damage(), G_delayPrint(), G_deleteStats(), G_DettachBodyParts(), G_DoAntiwarp(), G_DropItems(), G_DropLimboAmmo(), G_DropLimboHealth(), G_EntitiesFree(), G_ExplodeSatchels(), G_FadeItems(), G_FallDamage(), G_Find(), G_FindByTargetname(), G_FindByTargetnameFast(), G_FindFloat(), G_FindFreeFireteam(), G_FindFreeFireteamIdent(), G_FindFreePublicFireteam(), G_FindInt(), G_FindSatchel(), G_FindVector(), G_FireteamNumberForString(), G_FollowSame(), G_FreeEntity(), G_Gametype_v(), G_GetPlayerByName(), G_GetPlayerByNum(), G_globalFlagIndicator(), G_HistoricalTrace(), G_InitGentity(), G_InitSessionData(), G_InitTempTraceIgnoreEnts(), G_InitWorldSession(), G_IntermissionMapList(), G_IntermissionMapVote(), G_IntermissionVoteTally(), G_InviteToFireTeam(), G_IsFireteamLeader(), G_IsOnFireteam(), G_Kick_v(), G_KillEnts(), G_LandminePrime(), G_LandmineSnapshotCallback(), G_LandmineThink(), G_LinkDamageParents(), G_LinkDebris(), G_LoadCampaignsFromFile(), G_loadMatchGame(), G_LoseSkillPoints(), G_Lua_CreateEntity(), G_MagicSink(), G_MakeReferee(), G_Map_v(), G_MapIsValidCampaignStartMap(), G_matchInfoDump(), G_MatchOnePlayer(), G_MissileImpact(), G_ModifyTOI(), G_MoverTeam(), G_Mute_v(), G_MuteClient(), G_NeedEngineers(), G_NumPlayersOnTeam(), G_ParseAnimationFiles(), G_ParseCampaigns(), G_ParseSpawnVars(), G_parseStats(), G_pause_cmd(), G_PlayerCanBeSeenByOthers(), G_players_cmd(), G_PlaySound_Cmd(), G_PopupMessage(), G_PredictMissile(), G_PreFilledMissileEntity(), G_PrintAccuracyLog(), G_PrintClientSpammyCenterPrint(), G_printMatchInfo(), G_ProcessTagConnect(), G_ProposeFireTeamPlayer(), G_PushMapEntityToBuffer(), G_PushPlayer(), G_RadiusDamage(), G_ReAdjustSingleClientPosition(), G_ReadSessionData(), G_ready_cmd(), G_readyMatchState(), G_RealExplodedMissile(), G_ref_cmd(), G_refAllReady_cmd(), G_refClientnumForName(), G_Referee_v(), G_refLockTeams_cmd(), G_refPause_cmd(), G_refSpeclockTeams_cmd(), G_refWarning_cmd(), G_RegisterFireteam(), G_ReloadConfig(), G_RemoveAllShoutcasters(), G_RemoveClientFromFireteams(), G_RemoveFromAllIgnoreLists(), G_RemoveReferee(), G_removeSpecInvite(), G_ResetMarkers(), G_ResetTempTraceIgnoreEnts(), G_ResolveSpawnPointIndex(), G_RestartCampaign_v(), G_RunFlamechunk(), G_RunItem(), G_RunMissile(), G_RunMover(), G_Say(), G_Script_GetEventIndex(), G_Script_ScriptChange(), G_Script_ScriptLoad(), G_Script_ScriptParse(), G_Script_ScriptRun(), G_ScriptAction_AbortIfWarmup(), G_ScriptAction_AbortMove(), G_ScriptAction_Accum(), G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_AllowTankEnter(), G_ScriptAction_AllowTankExit(), G_ScriptAction_Create(), G_ScriptAction_FaceAngles(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GlobalAccum(), G_ScriptAction_GotoMarker(), G_ScriptAction_Halt(), G_ScriptAction_PlayAnim(), G_ScriptAction_PrintGlobalAccum(), G_ScriptAction_RemoveEntity(), G_ScriptAction_RemoveTeamVoiceAnnounce(), G_ScriptAction_ResetScript(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetHQStatus(), G_ScriptAction_SetModelFromBrushmodel(), G_ScriptAction_SetRotation(), G_ScriptAction_SetSpeed(), G_ScriptAction_ShaderRemap(), G_ScriptAction_SpawnRubble(), G_ScriptAction_StopRotation(), G_ScriptAction_TagConnect(), G_ScriptAction_Trigger(), G_ScriptAction_Wait(), G_SendMapEntityInfo(), G_SendScore(), G_SendScore_Add(), G_SendSpectatorMapEntityInfo(), G_SendSystemMessage(), G_SetPlayerSkill(), G_shuffleTeamsXP(), G_SortPlayersByXP(), G_Spawn(), G_SpawnEntitiesFromString(), G_SpawnGEntityFromSpawnVars(), G_SpawnItem(), G_spawnPrintf(), G_SpawnStringExt(), G_StartMatch_v(), G_statsall_cmd(), G_StoreClientPosition(), G_Surrender_v(), G_swapTeams(), G_SweepForLandmines(), G_TankIsMountable(), G_TeamCommand(), G_TeamCount(), G_teamready_cmd(), G_TempEntity(), G_TempEntityNotLinked(), G_TempTraceIgnoreEntity(), G_TempTraceIgnorePlayersAndBodies(), G_Timelimit_v(), G_TouchTriggers(), G_Trace(), G_UnMute_v(), G_UnMuteClient(), G_Unreferee_v(), G_UpdateFireteamConfigString(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), G_updateSpecLock(), G_UpdateSvCvars(), G_UpdateTeamMapData(), G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_DisguisedPlayer(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), G_UpdateTeamMapData_Tank(), G_verifyMatchState(), G_Voice(), G_voteCmdCheck(), G_voteProcessOnOff(), G_voteSetOnOff(), G_voteSetValue(), G_voteSetVoteString(), G_Warmupfire_v(), G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), G_WriteClientSessionData(), G_WriteSessionData(), ETInterface::GetAutoNavFeatures(), ETInterface::GetGameTime(), ETInterface::GetGoals(), ETInterface::GetMapExtents(), ETInterface::GetMapName(), ETInterface::GetPlayerInfo(), GotoPos3(), HandleEntsThatBlockConstructible(), heal_touch(), hurt_think(), hurt_touch(), hurt_use(), info_limbo_camera_setup(), InitBodyQue(), InitExplosive(), InitShooter(), ETInterface::InterfaceSendMessage(), Just_Got_Thrown(), landmine_setup(), LandminePostThink(), LandMinePostTrigger(), LandMineTrigger(), LaunchItem(), limbo(), locker_tall_think(), mg42_spawn(), mg42_think(), mg42_track(), misc_beam_start(), misc_beam_think(), misc_spawner_use(), multi_trigger(), objective_Register(), OilParticles_think(), OilSlick_remove(), P_DamageFeedback(), P_WorldEffects(), PickTeam(), Pickup_Team(), Pickup_Weapon(), player_die(), prop_smoke(), Prop_Touch(), propExplosion(), props_58x112tablew_die(), props_58x112tablew_think(), Props_Activated(), Props_Barrel_Animate(), Props_Barrel_Die(), props_bench_die(), props_bench_think(), props_castlebed_animate(), props_castlebed_die(), Props_Chair_Animate(), Props_Chair_Die(), Props_Chair_Think(), Props_Chair_Touch(), props_crate32x64_die(), props_crate32x64_think(), props_decoration_animate(), props_decoration_death(), props_flamethrower_think(), props_flamethrower_use(), props_flippy_blocked(), props_flippy_table_die(), props_locker_tall_die(), props_locker_use(), props_snowGenerator_think(), props_snowGenerator_use(), props_statue_animate(), props_statue_death(), Psmoke_think(), PushBot(), Reached_BinaryMover(), Reached_Train(), Reached_Train_rotating(), Reached_TrinaryMover(), ReadyToCallArtillery(), ReadyToConstruct(), ReturnToPos1(), ReturnToPos1Rotate(), ReturnToPos2(), script_mover_spawn(), script_mover_think(), script_mover_use(), SelectRandomTeamSpawnPoint(), SelectSpectatorSpawnPoint(), SetMoverState(), SetPlayerSpawn(), SetTeam(), smoke_init(), smoke_think(), smoker_think(), SortStats(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_dlight(), SP_Dust(), SP_func_brushmodel(), SP_func_constructible(), SP_func_door(), SP_func_door_rotating(), SP_func_secret(), SP_func_timer(), SP_func_train(), SP_func_train_rotating(), SP_info_limbo_camera(), SP_info_null(), SP_mg42(), SP_misc_beam(), SP_misc_constructiblemarker(), SP_misc_firetrails(), SP_misc_flak(), SP_misc_landmine(), SP_misc_portal_surface(), SP_misc_vis_dummy(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_flamethrower(), SP_props_footlocker(), SP_props_gunsparks(), SP_props_snowGenerator(), SP_script_mover(), SP_script_multiplayer(), SP_target_laser(), SP_target_push(), SP_target_smoke(), SP_target_speaker(), SP_team_WOLF_objective(), SP_trigger_always(), SP_trigger_ammo(), SP_trigger_heal(), SP_trigger_objective_info(), SP_worldspawn(), sparks_angles_think(), Spawn_Junk(), Spawn_Shard(), SpectatorClientEndFrame(), SpectatorThink(), Static_Pain(), StuckInClient(), Svcmd_Burn(), Svcmd_Campaign_f(), Svcmd_Die(), Svcmd_EntityList_f(), Svcmd_Fling(), Svcmd_ForceTeam_f(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_ListCampaigns_f(), Svcmd_Pip(), Svcmd_Ref_f(), Svcmd_ResetMatch_f(), Svcmd_Unfreeze(), target_laser_think(), target_rumble_think(), target_rumble_use(), Team_DroppedFlagThink(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), TeamCount(), TeamplayInfoMessage(), TeleportPlayer(), Think_BeginMoving(), Think_BeginMoving_rotating(), Think_MatchTeam(), Think_SetupObjectiveInfo(), Think_SpawnNewDoorTrigger(), Touch_flagonly(), Touch_flagonly_multiple(), Touch_Item(), Touch_Plat(), trigger_ammo_setup(), trigger_ammo_think(), trigger_heal_setup(), trigger_heal_think(), TryConstructing(), ETInterface::UpdateBotInput(), Use_BinaryMover(), use_dlight(), use_invisible_user(), Use_props_decoration(), Use_Target_Delay(), Use_target_push(), Use_TrinaryMover(), VM_Debug(), Weapon_AdrenalineSyringe(), Weapon_Artillery(), weapon_callAirStrike(), weapon_checkAirStrike(), weapon_checkAirStrikeThink(), Weapon_Engineer(), Weapon_FlamethrowerFire(), Weapon_MagicAmmo_Ext(), Weapon_Medic_Ext(), weapon_smokeBombExplode(), and WolfFindMedic().
vmCvar_t lua_allowedModules
Definition at line 265 of file g_main.c.
Referenced by G_LuaRunIsolated().
vmCvar_t lua_modules
Definition at line 264 of file g_main.c.
Referenced by G_LuaInit().
mapEntityData_Team_t mapEntityData[2]
Definition at line 67 of file g_main.c.
Referenced by ClientDisconnect(), constructible_indicator_think(), explosive_indicator_think(), func_constructible_explode(), G_Damage(), G_RealExplodedMissile(), G_ResetTeamMapData(), G_SendMapEntityInfo(), G_SendSpectatorMapEntityInfo(), G_SetEntState(), G_UpdateTeamMapData(), G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_DisguisedPlayer(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), G_UpdateTeamMapData_Tank(), HandleEntsThatBlockConstructible(), player_die(), SetTeam(), TryConstructing(), and Weapon_Engineer().
vmCvar_t match_latejoin
Definition at line 174 of file g_main.c.
Referenced by G_teamReset().
vmCvar_t match_minplayers
Definition at line 175 of file g_main.c.
Referenced by G_checkReady(), G_ready_cmd(), G_StartMatch_v(), and G_teamready_cmd().
vmCvar_t match_mutespecs
Definition at line 176 of file g_main.c.
Referenced by G_checkServerToggle(), G_Mutespecs_v(), G_SayTo(), and G_VoiceTo().
vmCvar_t match_readypercent
Definition at line 177 of file g_main.c.
Referenced by G_checkReady().
vmCvar_t match_timeoutcount
Definition at line 178 of file g_main.c.
Referenced by G_teamReset().
vmCvar_t match_timeoutlength
Definition at line 179 of file g_main.c.
Referenced by G_delayPrint().
vmCvar_t match_warmupDamage
Definition at line 180 of file g_main.c.
Referenced by G_checkServerToggle(), G_Damage(), and G_Warmupfire_v().
vmCvar_t pmove_fixed
Definition at line 197 of file cg_main.c.
vmCvar_t pmove_msec
Definition at line 198 of file cg_main.c.
vmCvar_t refereePassword
Definition at line 218 of file g_main.c.
Referenced by G_ref_cmd().
vmCvar_t server_motd0
Definition at line 183 of file g_main.c.
Referenced by G_loadMatchGame().
vmCvar_t server_motd1
Definition at line 184 of file g_main.c.
Referenced by G_loadMatchGame().
vmCvar_t server_motd2
Definition at line 185 of file g_main.c.
Referenced by G_loadMatchGame().
vmCvar_t server_motd3
Definition at line 186 of file g_main.c.
Referenced by G_loadMatchGame().
vmCvar_t server_motd4
Definition at line 187 of file g_main.c.
Referenced by G_loadMatchGame().
vmCvar_t server_motd5
Definition at line 188 of file g_main.c.
Referenced by G_loadMatchGame().
vmCvar_t shoutcastPassword
Definition at line 219 of file g_main.c.
Referenced by G_IsShoutcastPasswordSet(), and G_sclogin_cmd().
vmCvar_t skill_battlesense
Definition at line 314 of file g_main.c.
vmCvar_t skill_covertops
Definition at line 313 of file g_main.c.
vmCvar_t skill_engineer
Definition at line 311 of file g_main.c.
vmCvar_t skill_fieldops
Definition at line 312 of file g_main.c.
vmCvar_t skill_lightweapons
Definition at line 315 of file g_main.c.
vmCvar_t skill_medic
Definition at line 310 of file g_main.c.
vmCvar_t skill_soldier
Definition at line 309 of file g_main.c.
vmCvar_t sv_fps
Definition at line 353 of file g_main.c.
Referenced by Bot_Interface_Update(), ClientEndFrame(), G_ResetMarkers(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_Init(), and SV_UserinfoChanged().
vmCvar_t sv_privatepassword
Definition at line 95 of file g_main.c.
Referenced by ClientConnect().
vmCvar_t team_maxAirstrikes
Definition at line 289 of file g_main.c.
Referenced by G_AddAirstrikeToCounters().
vmCvar_t team_maxArtillery
Definition at line 290 of file g_main.c.
Referenced by G_AddArtilleryToCounters().
vmCvar_t team_maxCovertops
Definition at line 298 of file g_main.c.
Referenced by G_IsClassFull().
vmCvar_t team_maxEngineers
Definition at line 296 of file g_main.c.
Referenced by G_IsClassFull().
vmCvar_t team_maxFieldops
Definition at line 297 of file g_main.c.
Referenced by G_IsClassFull().
vmCvar_t team_maxFlamers
Definition at line 301 of file g_main.c.
Referenced by G_IsWeaponDisabled().
vmCvar_t team_maxLandmines
Definition at line 305 of file g_main.c.
Referenced by ETInterface::InterfaceSendMessage(), SP_script_multiplayer(), and Weapon_Engineer().
vmCvar_t team_maxMachineguns
Definition at line 302 of file g_main.c.
Referenced by G_IsWeaponDisabled().
vmCvar_t team_maxMedics
Definition at line 295 of file g_main.c.
Referenced by G_IsClassFull().
vmCvar_t team_maxMortars
Definition at line 300 of file g_main.c.
Referenced by G_IsWeaponDisabled().
vmCvar_t team_maxplayers
Definition at line 181 of file g_main.c.
Referenced by G_refPlayerPut_cmd(), and G_teamJoinCheck().
vmCvar_t team_maxRiflegrenades
Definition at line 304 of file g_main.c.
Referenced by G_IsWeaponDisabled().
vmCvar_t team_maxRockets
Definition at line 303 of file g_main.c.
Referenced by G_IsWeaponDisabled().
vmCvar_t team_maxSoldiers
Definition at line 294 of file g_main.c.
Referenced by G_IsClassFull().
vmCvar_t team_nocontrols
Definition at line 182 of file g_main.c.
Referenced by G_lock_cmd(), G_pause_cmd(), G_specinvite_cmd(), and G_speclock_cmd().
vmCvar_t team_riflegrenades
Definition at line 307 of file g_main.c.
Referenced by AddWeaponToPlayer().
team_info teamInfo[TEAM_NUM_TEAMS]
Definition at line 1539 of file g_team.c.
vmCvar_t vote_allow_antilag
Definition at line 207 of file g_main.c.
Referenced by G_AntiLag_v().
vmCvar_t vote_allow_balancedteams
Definition at line 208 of file g_main.c.
Referenced by G_BalancedTeams_v().
vmCvar_t vote_allow_config
Definition at line 189 of file g_main.c.
Referenced by G_Config_v().
vmCvar_t vote_allow_friendlyfire
Definition at line 204 of file g_main.c.
Referenced by G_FriendlyFire_v().
vmCvar_t vote_allow_gametype
Definition at line 190 of file g_main.c.
Referenced by G_Gametype_v().
vmCvar_t vote_allow_kick
Definition at line 191 of file g_main.c.
Referenced by G_Kick_v().
vmCvar_t vote_allow_map
Definition at line 192 of file g_main.c.
Referenced by G_Campaign_v(), and G_Map_v().
vmCvar_t vote_allow_maprestart
Definition at line 216 of file g_main.c.
Referenced by G_MapRestart_v().
vmCvar_t vote_allow_matchreset
Definition at line 193 of file g_main.c.
Referenced by G_MatchReset_v().
vmCvar_t vote_allow_mutespecs
Definition at line 194 of file g_main.c.
Referenced by G_Mutespecs_v().
vmCvar_t vote_allow_muting
Definition at line 209 of file g_main.c.
Referenced by G_Mute_v(), and G_UnMute_v().
vmCvar_t vote_allow_nextcampaign
Definition at line 214 of file g_main.c.
Referenced by G_NextCampaign_v().
vmCvar_t vote_allow_nextmap
Definition at line 195 of file g_main.c.
Referenced by G_Nextmap_v().
vmCvar_t vote_allow_poll
Definition at line 215 of file g_main.c.
Referenced by G_Poll_v().
vmCvar_t vote_allow_referee
Definition at line 196 of file g_main.c.
Referenced by G_Referee_v(), and G_Unreferee_v().
vmCvar_t vote_allow_restartcampaign
Definition at line 213 of file g_main.c.
Referenced by G_RestartCampaign_v().
vmCvar_t vote_allow_shuffleteamsxp
Definition at line 197 of file g_main.c.
Referenced by G_ShuffleTeamsXP_v().
vmCvar_t vote_allow_shuffleteamsxp_norestart
Definition at line 198 of file g_main.c.
Referenced by G_ShuffleTeamsXP_NoRestart_v().
vmCvar_t vote_allow_surrender
Definition at line 212 of file g_main.c.
Referenced by G_Surrender_v().
vmCvar_t vote_allow_swapteams
Definition at line 203 of file g_main.c.
Referenced by G_SwapTeams_v().
vmCvar_t vote_allow_timelimit
Definition at line 205 of file g_main.c.
Referenced by G_Timelimit_v().
vmCvar_t vote_allow_warmupdamage
Definition at line 206 of file g_main.c.
Referenced by G_Warmupfire_v().
vmCvar_t vote_limit
Definition at line 210 of file g_main.c.
Referenced by Cmd_CallVote_f().
vmCvar_t vote_percent
Definition at line 211 of file g_main.c.
vmCvar_t voteFlags
Definition at line 132 of file g_main.c.
Referenced by Cmd_CallVote_f(), and G_voteFlags().
weapFireTable_t weapFireTable[WP_NUM_WEAPONS]
Definition at line 4030 of file g_weapon.c.