ET: Legacy: src/game/g_misc.c File Reference
g_misc.c File Reference
#include "g_local.h"
#include "g_lua.h"
Macros
#define SF_SHOOTER_TEAM_WP 4
#define USEDIST 128.f
#define FLAK_SPREAD 100
#define FLAK_DAMAGE 36
#define GUN1_IDLE 0
#define GUN2_IDLE 4
#define GUN3_IDLE 8
#define GUN4_IDLE 12
#define GUN1_LASTFIRE 3
#define GUN2_LASTFIRE 7
#define GUN3_LASTFIRE 11
#define GUN4_LASTFIRE 15
Functions
void AimAtTarget (gentity_t *self)
Calculate origin2 so the target apogee will be hit.
float AngleDifference (float ang1, float ang2)
AngleDifference.
void SP_info_camp (gentity_t *self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_camp (0 0.5 0) (-4 -4 -4) (4 4 4)
void SP_info_null (gentity_t *self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_null (0 0.5 0) (-4 -4 -4) (4 4 4)
void SP_info_notnull (gentity_t *self)
Used as a positional target for in-game calculation, like jumppad targets. target_position does the same thing QUAKED info_notnull (0 0.5 0) (-4 -4 -4) (4 4 4)
void SP_light (gentity_t *self)
QUAKED light (0 1 0) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point q3map_non-dynamic Non-displayed light. "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf) "q3map_non-dynamic" specifies that this light should not contribute to the world's 'light grid' and therefore will not light dynamic models in the game.(wolf)
void SP_lightJunior (gentity_t *self)
QUAKED lightJunior (0 0.7 0.3) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point Non-displayed light that only affects dynamic game models, but does not contribute to lightmaps "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf)
void TeleportPlayer (gentity_t *player, vec3_t origin, vec3_t angles)
Teleport player to a given origin and angles.
void SP_misc_teleporter_dest (gentity_t *ent)
QUAKED misc_teleporter_dest (1 0 0) (-32 -32 -24) (32 32 -16) Point teleporters at these. Now that we don't have teleport destination pads, this is just an info_notnull.
void SP_misc_model (gentity_t *ent)
QUAKED misc_model (1 0 0) (-16 -16 -16) (16 16 16) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested)
void SP_misc_gamemodel (gentity_t *ent)
QUAKED misc_gamemodel (1 0 0) (-16 -16 -16) (16 16 16) ORIENT_LOD START_ANIMATE md3 placed in the game at runtime (rather than in the bsp) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x, and scales uniformly) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested) "skin" .skin file used to define shaders for model "trunk" diameter of solid core (used for trace visibility and collision (not ai pathing)) "trunkheight" height of trunk.
void locateMaster (gentity_t *ent)
locateMaster
void SP_misc_vis_dummy (gentity_t *ent)
QUAKED misc_vis_dummy (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. For safety, you should have each dummy only point at one entity (however, it's okay to have many dummies pointing at one entity)
void SP_misc_vis_dummy_multiple (gentity_t *ent)
QUAKED misc_vis_dummy_multiple (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. This entity was created to have multiple speakers targeting it.
void SP_misc_light_surface (gentity_t *ent)
QUAKED misc_light_surface (1 .5 0) (-8 -8 -8) (8 8 8) The surfaces nearest these entities will be the only surfaces lit by the targeting light This must be within 64 world units of the surface to be lit!
void locateCamera (gentity_t *ent)
locateCamera
void SP_misc_portal_surface (gentity_t *ent)
QUAKED misc_portal_surface (0 0 1) (-8 -8 -8) (8 8 8) The portal surface nearest this entity will show a view from the targeted misc_portal_camera, or a mirror view if untargeted. This must be within 64 world units of the surface!
void SP_misc_portal_camera (gentity_t *ent)
QUAKED misc_portal_camera (0 0 1) (-8 -8 -8) (8 8 8) slowrotate fastrotate The target for a misc_portal_director. You can set either angles or target another entity to determine the direction of view. "roll" an angle modifier to orient the camera around the target vector;.
void Use_Shooter (gentity_t *ent, gentity_t *other, gentity_t *activator)
SHOOTERS weapons WP_MAPMORTAR, WP_GRENADE_LAUNCHER/WP_GRENADE_PINEAPPLE and WP_PANZERFAUST/WP_BAZOOKA.
static void InitShooter_Finish (gentity_t *ent)
InitShooter_Finish.
void InitShooter (gentity_t *ent, int weapon)
InitShooter.
void SP_shooter_mortar (gentity_t *ent)
QUAKED shooter_mortar (1 0 0) (-16 -16 -16) (16 16 16) SMOKE_FX FLASH_FX Lobs a mortar so that it will pass through the info_notnull targeted by this entity "random" the number of degrees of deviance from the taget. (1.0 default) if LAUNCH_FX is checked a smoke effect will play at the origin of this entity. if FLASH_FX is checked a muzzle flash effect will play at the origin of this entity.
void SP_shooter_rocket (gentity_t *ent)
QUAKED shooter_rocket (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" the number of degrees of deviance from the taget. (1.0 default)
void SP_shooter_grenade (gentity_t *ent)
QUAKED shooter_grenade (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" is the number of degrees of deviance from the taget. (1.0 default)
void use_corona (gentity_t *ent, gentity_t *other, gentity_t *activator)
So level designers can toggle them on/off.
void SP_corona (gentity_t *ent)
QUAKED corona (0 1 0) (-4 -4 -4) (4 4 4) START_OFF Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). "scale" will designate a multiplier to the default size. (so 2.0 is 2xdefault size, 0.5 is half)
void dlight_finish_spawning (gentity_t *ent)
All the dlights should call this on the same frame, thereby being synched, starting their sequences all at the same time.
void shutoff_dlight (gentity_t *ent)
The dlight knew when it was triggered to unlink after going through it's cycle once.
void use_dlight (gentity_t *ent, gentity_t *other, gentity_t *activator)
use_dlight
void SP_dlight (gentity_t *ent)
QUAKED dlight (0 1 0) (-12 -12 -12) (12 12 12) FORCEACTIVE STARTOFF ONETIME "style": value is an int from 1-19 that contains a pre-defined 'flicker' string. "stylestring": set your own 'flicker' string. (ex. "klmnmlk"). NOTE: this should be all lowercase Stylestring characters run at 10 cps in the game. (meaning the alphabet, at 24 characters, would take 2.4 seconds to cycle) "offset": change the initial index in a style string. So val of 3 in the above example would start this light at 'N'. (used to get dlights using the same style out of sync). "atten": offset from the alpha values of the stylestring. stylestring of "ddeeffzz" with an atten of -1 would result in "ccddeeyy" Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). FORCEACTIVE - toggle makes sure this light stays alive in a map even if the user has r_dynamiclight set to 0. STARTOFF - means the dlight doesn't spawn in until ent is triggered ONETIME - when the dlight is triggered, it will play through it's cycle once, then shut down until triggered again "shader" name of shader to apply "sound" sound to loop every cycle (this actually just plays the sound at the beginning of each cycle)
void flakPuff (vec3_t origin)
flakPuff
void Fire_Lead_Ext (gentity_t *ent, gentity_t *activator, float spread, int damage, vec3_t muzzle, vec3_t forward, vec3_t right, vec3_t up, meansOfDeath_t mod)
Fire_Lead_Ext - machine/flag gun fire.
void clamp_playerbehindgun (gentity_t *self, gentity_t *other, vec3_t dang)
clamp_playerbehindgun
void clamp_hweapontofirearc (gentity_t *self, vec3_t dang)
clamp_hweapontofirearc
void aagun_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
quad 20mm specs from marauder. Fire each barrel every 1s, so 250ms per shot total.
void aagun_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
aagun_die
void aagun_track (gentity_t *self, gentity_t *other)
aagun_track
void aagun_think (gentity_t *self)
aagun_think
void aagun_stopusing (gentity_t *self)
aagun_stopusing
void aagun_fire (gentity_t *other)
aagun_fire
void aagun_touch (gentity_t *self, gentity_t *other, trace_t *trace)
aagun_touch
void aagun_spawn (gentity_t *gun)
aagun_spawn
void SP_aagun (gentity_t *self)
QUAKED misc_aagun (1 0 0) (-32 -32 0) (64 32 56) harc = fixed full 360? varc = fixed 0-45 up?
void mg42_touch (gentity_t *self, gentity_t *other, trace_t *trace)
mg42_touch
void mg42_fire (gentity_t *other)
mg42_fire
void mg42_track (gentity_t *self, gentity_t *other)
mg42_track
void mg42_think (gentity_t *self)
mg42_think
void mg42_stopusing (gentity_t *self)
This is to be called for the gun ent, not the tripod.
void mg42_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
mg42_die
void mg42_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
mg42_use
void UpdateGoalEntity (gentity_t *oldent, gentity_t *newent)
void mg42_spawn (gentity_t *ent)
mg42_spawn
void SP_mg42 (gentity_t *self)
QUAKED misc_mg42 (1 0 0) (-16 -16 -24) (16 16 24) HIGH NOTRIPOD harc = horizonal fire arc Default is 57.5 (left and right) varc = vertical fire arc Default is 45 (upwards and 22.5 down) health = how much damage can it take default is 50 damage = determines how much the weapon will inflict if a non player uses it "accuracy" all guns are 100% accurate an entry of 0.5 would make it 50%.
void flak_spawn (gentity_t *ent)
flak_spawn
void SP_misc_flak (gentity_t *self)
QUAKED misc_flak (1 0 0) (-32 -32 0) (32 32 100)
void misc_spawner_think (gentity_t *ent)
misc_spawner_think
void misc_spawner_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
misc_spawner_use
void SP_misc_spawner (gentity_t *ent)
QUAKED misc_spawner (.3 .7 .8) (-8 -8 -8) (8 8 8) use the pickup name when this entity gets used it will spawn an item that matches its spawnitem field e.i. spawnitem 9mm.
void firetrail_die (gentity_t *ent)
firetrail_die
void firetrail_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
firetrail_use
void misc_firetrails_think (gentity_t *ent)
QUAKED misc_firetrails (.4 .9 .7) (-16 -16 -16) (16 16 16) This entity must target the plane its going to be attached to.
void SP_misc_firetrails (gentity_t *ent)
SP_misc_firetrails.
void constructiblemarker_setup (gentity_t *ent)
QUAKED misc_constructiblemarker (1 0.85 0) ? Used to indicate where constructibles are, is a special entity due to bot needs. The entity has to be solid and target the trigger_objective_info belonging to the constructible.
void SP_misc_constructiblemarker (gentity_t *ent)
SP_misc_constructiblemarker.
void G_LandmineThink (gentity_t *self)
Landmine waits for 2 seconds then primes, which sets think to checking for "enemies".
void landmine_setup (gentity_t *ent)
QUAKED misc_landmine (.35 0.85 .35) (-16 -16 0) (16 16 16) AXIS ALLIED Landmine entity. Make sure it is placed less than 64 units above an appropiate, landmine placement compatible surface. It will drop down on spawn and then settle itself.
void SP_misc_landmine (gentity_t *ent)
SP_misc_landmine.
void SP_misc_commandmap_marker (gentity_t *ent)
Command map marker entity. When set to state default it shows, any other state and it isn't visible. QUAKED misc_commandmap_marker (0 0.85 .85) (-16 -16 0) (16 16 16) ONLY_AXIS ONLY_ALLIED ISOBJECTIVE ISHEALTHAMMOCABINET ISCOMMANDPOST -----— KEYS -----— (none) -----— SPAWNFLAGS -----— (none)
void G_InitTempTraceIgnoreEnts (void)
System to temporarily ignore certain ents during traces.
void G_ResetTempTraceIgnoreEnts (void)
G_ResetTempTraceIgnoreEnts.
void G_TempTraceIgnoreEntity (gentity_t *ent)
G_TempTraceIgnoreEntity.
void G_TempTraceIgnorePlayersAndBodies (void)
G_TempTraceIgnorePlayersAndBodies.
qboolean G_ConstructionBegun (gentity_t *ent)
G_ConstructionBegun.
qboolean G_ConstructionIsFullyBuilt (gentity_t *ent)
G_ConstructionIsFullyBuilt.
qboolean G_ConstructionIsPartlyBuilt (gentity_t *ent)
G_ConstructionIsPartlyBuilt.
gentity_t * G_ConstructionForTeam (gentity_t *toi, team_t team)
G_ConstructionForTeam.
gentity_t * G_IsConstructible (team_t team, gentity_t *toi)
G_IsConstructible.
char * ClientName (int client, char *name, size_t size)
ClientName.
int FindClientByName (const char *name)
FindClientByName.
qboolean G_FlingClient (gentity_t *vic, int flingType)
G_FlingClient.
void G_PreFilledMissileEntity (gentity_t *ent, int weaponNum, int realWeapon, int ownerNum, team_t teamNum, int clientNum, gentity_t *parent, const vec3_t start, const vec3_t dir)
G_PreFilledMissileEntity.
int G_GetEnemyPosition (gentity_t *ent, gentity_t *targ)
G_GetEnemyPosition.
void G_MagicSink (gentity_t *self)
Magically sink given entity before freeing.
Variables
char * predef_lightstyles []
static int dlightstarttime = 0
Macro Definition Documentation
#define FLAK_DAMAGE 36
Definition at line 1992 of file g_misc.c.
#define FLAK_SPREAD 100
Definition at line 1991 of file g_misc.c.
#define GUN1_IDLE 0
Definition at line 1994 of file g_misc.c.
#define GUN1_LASTFIRE 3
Definition at line 1999 of file g_misc.c.
#define GUN2_IDLE 4
Definition at line 1995 of file g_misc.c.
#define GUN2_LASTFIRE 7
Definition at line 2000 of file g_misc.c.
#define GUN3_IDLE 8
Definition at line 1996 of file g_misc.c.
#define GUN3_LASTFIRE 11
Definition at line 2001 of file g_misc.c.
#define GUN4_IDLE 12
Definition at line 1997 of file g_misc.c.
#define GUN4_LASTFIRE 15
Definition at line 2002 of file g_misc.c.
#define SF_SHOOTER_TEAM_WP 4
Todo:
: make these available for bg (mortar effects are client side only)
Definition at line 516 of file g_misc.c.
Referenced by SP_shooter_grenade(), and SP_shooter_rocket().
#define USEDIST 128.f
Definition at line 1536 of file g_misc.c.
Referenced by mg42_think().
Function Documentation
void aagun_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
aagun_die
Parameters
self
inflictor
attacker
damage
mod
Note
not implented yet ?
Definition at line 1181 of file g_misc.c.
Referenced by aagun_spawn().
void aagun_fire (gentity_t * other)
aagun_fire
Parameters
[in,out] other
Definition at line 1325 of file g_misc.c.
Referenced by ClientEvents().
void aagun_spawn (gentity_t * gun)
aagun_spawn
Parameters
[out] gun
Definition at line 1386 of file g_misc.c.
Referenced by SP_aagun().
void aagun_stopusing (gentity_t * self)
aagun_stopusing
Parameters
[in,out] self
Definition at line 1305 of file g_misc.c.
Referenced by G_SetEntState().
void aagun_think (gentity_t * self)
aagun_think
Parameters
[in,out] self
Definition at line 1219 of file g_misc.c.
Referenced by aagun_spawn().
void aagun_touch (gentity_t * self, gentity_t * other, trace_t * trace)
aagun_touch
Parameters
[in] self
[in,out] other
trace - unused
Definition at line 1357 of file g_misc.c.
Referenced by aagun_spawn().
void aagun_track (gentity_t * self, gentity_t * other)
aagun_track
Parameters
[in,out] self
[in] other
Definition at line 1190 of file g_misc.c.
Referenced by aagun_think().
void aagun_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
quad 20mm specs from marauder. Fire each barrel every 1s, so 250ms per shot total.
Parameters
[in] ent
[out] other
activator - unused
Todo:
TODO: Hitscan Use some part of entitystate to store firing barrel? or just encode it with event more likely Shouldn't really have smoke puff in air, but may add anyway for effect
Definition at line 1151 of file g_misc.c.
Referenced by aagun_spawn().
void AimAtTarget (gentity_t * self)
Calculate origin2 so the target apogee will be hit.
Parameters
[in,out] self
Definition at line 335 of file g_trigger.c.
Referenced by SP_target_push(), and Use_Shooter().
float AngleDifference (float ang1, float ang2)
AngleDifference.
Parameters
[in] ang1
[in] ang2
Returns
Definition at line 2671 of file g_misc.c.
Referenced by clamp_hweapontofirearc(), G_ScriptAction_FaceAngles(), and G_ScriptAction_GotoMarker().
void clamp_hweapontofirearc (gentity_t * self, vec3_t dang)
clamp_hweapontofirearc
Parameters
[in] self
[in,out] dang
Definition at line 1107 of file g_misc.c.
Referenced by aagun_think(), and mg42_think().
void clamp_playerbehindgun (gentity_t * self, gentity_t * other, vec3_t dang)
clamp_playerbehindgun
Parameters
[in] self
[in,out] other
dang - unused
Note
This only effects the external view of the user, when using the mg42, the view position is set on the client-side to keep it firm behind the gun with interpolation
Definition at line 1069 of file g_misc.c.
Referenced by aagun_think(), aagun_touch(), mg42_think(), and mg42_touch().
char* ClientName (int client, char * name, size_t size)
ClientName.
Parameters
[in] client
[out] name
[in] size
Returns
client name
Definition at line 2699 of file g_misc.c.
Referenced by FindClientByName().
void constructiblemarker_setup (gentity_t * ent)
QUAKED misc_constructiblemarker (1 0.85 0) ? Used to indicate where constructibles are, is a special entity due to bot needs. The entity has to be solid and target the trigger_objective_info belonging to the constructible.
"model2" optional model "angles" angles for the model "skin" optional .skin file to use for the model "description" name of the construction
Parameters
[in,out] ent
Definition at line 2315 of file g_misc.c.
Referenced by SP_misc_constructiblemarker().
void dlight_finish_spawning (gentity_t * ent)
All the dlights should call this on the same frame, thereby being synched, starting their sequences all at the same time.
Parameters
ent
Definition at line 785 of file g_misc.c.
Referenced by SP_dlight().
int FindClientByName (const char * name)
FindClientByName.
Parameters
[in] name
Returns
Definition at line 2720 of file g_misc.c.
Referenced by Svcmd_ListCampaigns_f(), and Svcmd_RevivePlayer().
void Fire_Lead_Ext (gentity_t * ent, gentity_t * activator, float spread, int damage, vec3_t muzzle, vec3_t forward, vec3_t right, vec3_t up, meansOfDeath_t mod)
Fire_Lead_Ext - machine/flag gun fire.
Parameters
[in,out] ent
[in] activator
[in] spread
[in] damage
[in] muzzle
[in] forward
[in] right
[in] up
[in] mod
Note
Before calling this ensure ent->s.eFlags and activator->s.eFlags are set (EF_MG42_ACTIVE or EF_AAGUN_ACTIVE)
Definition at line 983 of file g_misc.c.
Referenced by aagun_fire(), mg42_fire(), and mountedmg42_fire().
void firetrail_die (gentity_t * ent)
firetrail_die
Mounted Gun, attached to a moving vehicle of some-sort
Parameters
[in] ent
Definition at line 2218 of file g_misc.c.
Referenced by misc_firetrails_think().
void firetrail_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
firetrail_use
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 2229 of file g_misc.c.
Referenced by misc_firetrails_think().
void flak_spawn (gentity_t * ent)
flak_spawn
Parameters
[in,out] ent
Definition at line 2072 of file g_misc.c.
Referenced by SP_misc_flak().
void flakPuff (vec3_t origin)
flakPuff
Parameters
[in] origin
Note
Unused
Definition at line 951 of file g_misc.c.
qboolean G_ConstructionBegun (gentity_t * ent)
G_ConstructionBegun.
Parameters
[in] ent
Returns
qtrue if a construction is under way on this ent, even before it hits any stages
Definition at line 2543 of file g_misc.c.
Referenced by G_IsConstructible().
gentity_t* G_ConstructionForTeam (gentity_t * toi, team_t team)
G_ConstructionForTeam.
Parameters
[in] toi
[in] team
Returns
Tshe constructible for this team that is attached to this toi
Definition at line 2605 of file g_misc.c.
Referenced by G_IsConstructible(), ETInterface::GetEntityLocalAABB(), ETInterface::GetEntityWorldAABB(), ETInterface::GetGoals(), and ETInterface::InterfaceSendMessage().
qboolean G_ConstructionIsFullyBuilt (gentity_t * ent)
G_ConstructionIsFullyBuilt.
Parameters
[in] ent
Returns
qtrue if all stage are built
Definition at line 2563 of file g_misc.c.
Referenced by G_ConstructionIsPartlyBuilt(), G_IsConstructible(), ETInterface::GetEntityFlags(), and ETInterface::InterfaceSendMessage().
qboolean G_ConstructionIsPartlyBuilt (gentity_t * ent)
G_ConstructionIsPartlyBuilt.
Parameters
[in] ent
Returns
qtrue if 1 stage or more is built
Definition at line 2577 of file g_misc.c.
Referenced by G_CheckForCursorHints(), G_ConstructionBegun(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
qboolean G_FlingClient (gentity_t * vic, int flingType)
G_FlingClient.
Parameters
[in,out] vic
[in] flingType
Returns
Definition at line 2754 of file g_misc.c.
Referenced by Svcmd_Fling().
int G_GetEnemyPosition (gentity_t * ent, gentity_t * targ)
G_GetEnemyPosition.
Parameters
[in] ent
[in] targ
Returns
Definition at line 2882 of file g_misc.c.
Referenced by Weapon_Knife().
void G_InitTempTraceIgnoreEnts (void)
System to temporarily ignore certain ents during traces.
Note
Unused
Definition at line 2468 of file g_misc.c.
gentity_t* G_IsConstructible (team_t team, gentity_t * toi)
G_IsConstructible.
Parameters
[in] team
[in] toi
Returns
Definition at line 2638 of file g_misc.c.
Referenced by G_CheckForCursorHints(), and ETInterface::InterfaceSendMessage().
void G_LandmineThink (gentity_t * self)
Landmine waits for 2 seconds then primes, which sets think to checking for "enemies".
Parameters
[in,out] self
Note
107 11 20 0 0 0 0 fire gren
Definition at line 1469 of file g_missile.c.
Referenced by G_LandminePrime(), landmine_setup(), and SP_misc_constructiblemarker().
void G_MagicSink (gentity_t * self)
Magically sink given entity before freeing.
Parameters
[in,out] self The entity to sink
Note
Make it TR_LINEAR so it doesnt chew bandwidth...
Definition at line 2909 of file g_misc.c.
Referenced by G_FadeItems(), LaunchItem(), Weapon_MagicAmmo_Ext(), and Weapon_Medic_Ext().
void G_PreFilledMissileEntity (gentity_t * ent, int weaponNum, int realWeapon, int ownerNum, team_t teamNum, int clientNum, gentity_t * parent, const vec3_t start, const vec3_t dir)
G_PreFilledMissileEntity.
Parameters
[in] ent
[in] weaponNum
[in] realWeapon
[in] ownerNum
[in] teamNum
[in] clientNum
[in] parent
Definition at line 2806 of file g_misc.c.
Referenced by fire_flamechunk(), fire_missile(), and landmine_setup().
void G_ResetTempTraceIgnoreEnts (void)
G_ResetTempTraceIgnoreEnts.
Definition at line 2476 of file g_misc.c.
Referenced by DynaFree(), G_RealExplodedMissile(), G_Trace(), trap_EngineerTrace(), and Weapon_Engineer().
void G_TempTraceIgnoreEntity (gentity_t * ent)
G_TempTraceIgnoreEntity.
Parameters
[in,out] ent
Definition at line 2495 of file g_misc.c.
Referenced by G_TempTraceIgnorePlayersAndBodies(), and G_Trace().
void G_TempTraceIgnorePlayersAndBodies (void)
G_TempTraceIgnorePlayersAndBodies.
Definition at line 2509 of file g_misc.c.
Referenced by DynaFree(), G_RealExplodedMissile(), trap_EngineerTrace(), and Weapon_Engineer().
void InitShooter (gentity_t * ent, int weapon)
InitShooter.
Parameters
[in,out] ent
[in] weapon
Definition at line 608 of file g_misc.c.
Referenced by SP_shooter_grenade(), SP_shooter_mortar(), and SP_shooter_rocket().
static void InitShooter_Finish (gentity_t * ent) static
InitShooter_Finish.
Parameters
[in] ent
Definition at line 596 of file g_misc.c.
Referenced by InitShooter().
void landmine_setup (gentity_t * ent)
QUAKED misc_landmine (.35 0.85 .35) (-16 -16 0) (16 16 16) AXIS ALLIED Landmine entity. Make sure it is placed less than 64 units above an appropiate, landmine placement compatible surface. It will drop down on spawn and then settle itself.
NOTE: there is a team limit of 10 landmines. With this entity you can place more landmines for that team in the map on start, but none of the engineers will be able to place landmines until there are less than 10 left.
"angle" landmine orientation
Parameters
[in,out] ent
Definition at line 2381 of file g_misc.c.
Referenced by SP_misc_landmine().
void locateCamera (gentity_t * ent)
locateCamera
Parameters
[in,out] ent
Definition at line 416 of file g_misc.c.
Referenced by SP_misc_portal_surface().
void locateMaster (gentity_t * ent)
locateMaster
Parameters
[in,out] ent
Definition at line 335 of file g_misc.c.
Referenced by SP_misc_vis_dummy().
void mg42_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
mg42_die
Parameters
[in,out] self
inflictor - unused
[in] attacker
damage - unused
mod - unused
Definition at line 1702 of file g_misc.c.
Referenced by mg42_spawn().
void mg42_fire (gentity_t * other)
mg42_fire
Parameters
[in,out] other
Definition at line 1472 of file g_misc.c.
Referenced by ClientEvents().
void mg42_spawn (gentity_t * ent)
mg42_spawn
Parameters
[in] ent
Definition at line 1803 of file g_misc.c.
Referenced by SP_mg42().
void mg42_stopusing (gentity_t * self)
This is to be called for the gun ent, not the tripod.
Parameters
[in,out] self
Definition at line 1670 of file g_misc.c.
Referenced by G_SetEntState().
void mg42_think (gentity_t * self)
mg42_think
Parameters
[in,out] self
Definition at line 1542 of file g_misc.c.
Referenced by flak_spawn(), and mg42_spawn().
void mg42_touch (gentity_t * self, gentity_t * other, trace_t * trace)
mg42_touch
Parameters
[in] self
[in,out] other
trace - unused
Definition at line 1443 of file g_misc.c.
Referenced by flak_spawn(), and mg42_spawn().
void mg42_track (gentity_t * self, gentity_t * other)
mg42_track
Parameters
[in,out] self
[in] other
Definition at line 1511 of file g_misc.c.
Referenced by mg42_think().
void mg42_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
mg42_use
Parameters
[in,out] ent
[out] other
activator - unused
Definition at line 1773 of file g_misc.c.
Referenced by mg42_spawn().
void misc_firetrails_think (gentity_t * ent)
QUAKED misc_firetrails (.4 .9 .7) (-16 -16 -16) (16 16 16) This entity must target the plane its going to be attached to.
its use function will turn the fire stream effect on and off
an alert entity call will kill it
Parameters
[in] ent
Definition at line 2253 of file g_misc.c.
Referenced by SP_misc_firetrails().
void misc_spawner_think (gentity_t * ent)
misc_spawner_think
Parameters
[in] ent
Definition at line 2144 of file g_misc.c.
Referenced by misc_spawner_use().
void misc_spawner_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
misc_spawner_use
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 2171 of file g_misc.c.
Referenced by SP_misc_spawner().
void shutoff_dlight (gentity_t * ent)
The dlight knew when it was triggered to unlink after going through it's cycle once.
Parameters
[in,out] ent
Definition at line 796 of file g_misc.c.
Referenced by use_dlight().
void SP_aagun (gentity_t * self)
QUAKED misc_aagun (1 0 0) (-32 -32 0) (64 32 56) harc = fixed full 360? varc = fixed 0-45 up?
Parameters
self
Definition at line 1429 of file g_misc.c.
void SP_corona (gentity_t * ent)
QUAKED corona (0 1 0) (-4 -4 -4) (4 4 4) START_OFF Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). "scale" will designate a multiplier to the default size. (so 2.0 is 2xdefault size, 0.5 is half)
Parameters
[in,out] ent
Definition at line 717 of file g_misc.c.
void SP_dlight (gentity_t * ent)
QUAKED dlight (0 1 0) (-12 -12 -12) (12 12 12) FORCEACTIVE STARTOFF ONETIME "style": value is an int from 1-19 that contains a pre-defined 'flicker' string. "stylestring": set your own 'flicker' string. (ex. "klmnmlk"). NOTE: this should be all lowercase Stylestring characters run at 10 cps in the game. (meaning the alphabet, at 24 characters, would take 2.4 seconds to cycle) "offset": change the initial index in a style string. So val of 3 in the above example would start this light at 'N'. (used to get dlights using the same style out of sync). "atten": offset from the alpha values of the stylestring. stylestring of "ddeeffzz" with an atten of -1 would result in "ccddeeyy" Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). FORCEACTIVE - toggle makes sure this light stays alive in a map even if the user has r_dynamiclight set to 0. STARTOFF - means the dlight doesn't spawn in until ent is triggered ONETIME - when the dlight is triggered, it will play through it's cycle once, then shut down until triggered again "shader" name of shader to apply "sound" sound to loop every cycle (this actually just plays the sound at the beginning of each cycle)
styles: 1 - "mmnmmommommnonmmonqnmmo" 2 - "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba" 3 - "mmmmmaaaaammmmmaaaaaabcdefgabcdefg" 4 - "ma" 5 - "jklmnopqrstuvwxyzyxwvutsrqponmlkj" 6 - "nmonqnmomnmomomono" 7 - "mmmaaaabcdefgmmmmaaaammmaamm" 8 - "aaaaaaaazzzzzzzz" 9 - "mmamammmmammamamaaamammma" 10 - "abcdefghijklmnopqrrqponmlkjihgfedcba" 11 - "mmnommomhkmmomnonmmonqnmmo" 12 - "kmamaamakmmmaakmamakmakmmmma" 13 - "kmmmakakmmaaamammamkmamakmmmma" 14 - "mmnnoonnmmmmmmmmmnmmmmnonmmmmmmm" 15 - "mmmmnonmmmmnmmmmmnonmmmmmnmmmmmmm" 16 - "zzzzzzzzaaaaaaaa" 17 - "zzzzzzzzaaaaaaaaaaaaaaaa" 18 - "aaaaaaaazzzzzzzzaaaaaaaa" 19 - "aaaaaaaaaaaaaaaazzzzzzzz"
ent->dl_stylestring contains the lightstyle string ent->health tracks current index into style string ent->count tracks length of style string
Parameters
[in,out] ent
Definition at line 874 of file g_misc.c.
void SP_info_camp (gentity_t * self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_camp (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
[in] self
Definition at line 52 of file g_misc.c.
void SP_info_notnull (gentity_t * self)
Used as a positional target for in-game calculation, like jumppad targets. target_position does the same thing QUAKED info_notnull (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
self
Definition at line 80 of file g_misc.c.
void SP_info_null (gentity_t * self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_null (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
[in,out] self
Definition at line 63 of file g_misc.c.
void SP_light (gentity_t * self)
QUAKED light (0 1 0) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point q3map_non-dynamic Non-displayed light. "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf) "q3map_non-dynamic" specifies that this light should not contribute to the world's 'light grid' and therefore will not light dynamic models in the game.(wolf)
Parameters
[in] self
Definition at line 98 of file g_misc.c.
void SP_lightJunior (gentity_t * self)
QUAKED lightJunior (0 0.7 0.3) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point Non-displayed light that only affects dynamic game models, but does not contribute to lightmaps "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf)
Parameters
[in] self
Definition at line 115 of file g_misc.c.
void SP_mg42 (gentity_t * self)
QUAKED misc_mg42 (1 0 0) (-16 -16 -24) (16 16 24) HIGH NOTRIPOD harc = horizonal fire arc Default is 57.5 (left and right) varc = vertical fire arc Default is 45 (upwards and 22.5 down) health = how much damage can it take default is 50 damage = determines how much the weapon will inflict if a non player uses it "accuracy" all guns are 100% accurate an entry of 0.5 would make it 50%.
Parameters
[in,out] self
Definition at line 1941 of file g_misc.c.
void SP_misc_commandmap_marker (gentity_t * ent)
Command map marker entity. When set to state default it shows, any other state and it isn't visible. QUAKED misc_commandmap_marker (0 0.85 .85) (-16 -16 0) (16 16 16) ONLY_AXIS ONLY_ALLIED ISOBJECTIVE ISHEALTHAMMOCABINET ISCOMMANDPOST -----— KEYS -----— (none) -----— SPAWNFLAGS -----— (none)
Parameters
[in,out] ent
Definition at line 2455 of file g_misc.c.
void SP_misc_constructiblemarker (gentity_t * ent)
SP_misc_constructiblemarker.
Parameters
[in,out] ent
Definition at line 2331 of file g_misc.c.
void SP_misc_firetrails (gentity_t * ent)
SP_misc_firetrails.
Parameters
[out] ent
Definition at line 2296 of file g_misc.c.
void SP_misc_flak (gentity_t * self)
QUAKED misc_flak (1 0 0) (-32 -32 0) (32 32 100)
Parameters
[in,out] self
Definition at line 2111 of file g_misc.c.
void SP_misc_gamemodel (gentity_t * ent)
QUAKED misc_gamemodel (1 0 0) (-16 -16 -16) (16 16 16) ORIENT_LOD START_ANIMATE md3 placed in the game at runtime (rather than in the bsp) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x, and scales uniformly) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested) "skin" .skin file used to define shaders for model "trunk" diameter of solid core (used for trace visibility and collision (not ai pathing)) "trunkheight" height of trunk.
"frames" number of animation frames "start" frame to start on "fps" fps to animate with
ORIENT_LOD - if flagged, the entity will yaw towards the player when the LOD switches START_ANIMATE - if flagged, the entity will spawn animating
"modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both, the "modelscale" is ignored
Parameters
[in,out] ent
Definition at line 217 of file g_misc.c.
void SP_misc_landmine (gentity_t * ent)
SP_misc_landmine.
Parameters
[in,out] ent
Definition at line 2426 of file g_misc.c.
void SP_misc_light_surface (gentity_t * ent)
QUAKED misc_light_surface (1 .5 0) (-8 -8 -8) (8 8 8) The surfaces nearest these entities will be the only surfaces lit by the targeting light This must be within 64 world units of the surface to be lit!
Parameters
[in] ent
Definition at line 405 of file g_misc.c.
void SP_misc_model (gentity_t * ent)
QUAKED misc_model (1 0 0) (-16 -16 -16) (16 16 16) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested)
"modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both, the "modelscale" is ignored
Parameters
[in] ent
Definition at line 191 of file g_misc.c.
void SP_misc_portal_camera (gentity_t * ent)
QUAKED misc_portal_camera (0 0 1) (-8 -8 -8) (8 8 8) slowrotate fastrotate The target for a misc_portal_director. You can set either angles or target another entity to determine the direction of view. "roll" an angle modifier to orient the camera around the target vector;.
Parameters
ent
Definition at line 494 of file g_misc.c.
void SP_misc_portal_surface (gentity_t * ent)
QUAKED misc_portal_surface (0 0 1) (-8 -8 -8) (8 8 8) The portal surface nearest this entity will show a view from the targeted misc_portal_camera, or a mirror view if untargeted. This must be within 64 world units of the surface!
Parameters
[in,out] ent
Definition at line 468 of file g_misc.c.
void SP_misc_spawner (gentity_t * ent)
QUAKED misc_spawner (.3 .7 .8) (-8 -8 -8) (8 8 8) use the pickup name when this entity gets used it will spawn an item that matches its spawnitem field e.i. spawnitem 9mm.
Parameters
[in,out] ent
Definition at line 2195 of file g_misc.c.
void SP_misc_teleporter_dest (gentity_t * ent)
QUAKED misc_teleporter_dest (1 0 0) (-32 -32 -24) (32 32 -16) Point teleporters at these. Now that we don't have teleport destination pads, this is just an info_notnull.
Parameters
ent - unused
Warning
Do not remove this function - this is just to create a destination spot entity for the teleporter
Definition at line 174 of file g_misc.c.
void SP_misc_vis_dummy (gentity_t * ent)
QUAKED misc_vis_dummy (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. For safety, you should have each dummy only point at one entity (however, it's okay to have many dummies pointing at one entity)
Parameters
[in] ent
Definition at line 357 of file g_misc.c.
void SP_misc_vis_dummy_multiple (gentity_t * ent)
QUAKED misc_vis_dummy_multiple (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. This entity was created to have multiple speakers targeting it.
Parameters
[in] ent
Definition at line 382 of file g_misc.c.
void SP_shooter_grenade (gentity_t * ent)
QUAKED shooter_grenade (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" is the number of degrees of deviance from the taget. (1.0 default)
Parameters
[in] ent
Definition at line 677 of file g_misc.c.
void SP_shooter_mortar (gentity_t * ent)
QUAKED shooter_mortar (1 0 0) (-16 -16 -16) (16 16 16) SMOKE_FX FLASH_FX Lobs a mortar so that it will pass through the info_notnull targeted by this entity "random" the number of degrees of deviance from the taget. (1.0 default) if LAUNCH_FX is checked a smoke effect will play at the origin of this entity. if FLASH_FX is checked a muzzle flash effect will play at the origin of this entity.
Parameters
[in] ent
Definition at line 644 of file g_misc.c.
void SP_shooter_rocket (gentity_t * ent)
QUAKED shooter_rocket (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" the number of degrees of deviance from the taget. (1.0 default)
Parameters
[in] ent
Definition at line 658 of file g_misc.c.
void TeleportPlayer (gentity_t * player, vec3_t origin, vec3_t angles)
Teleport player to a given origin and angles.
=================================================================================
TELEPORTERS
Parameters
[in,out] player
[in] origin
[in] angles
Definition at line 132 of file g_misc.c.
Referenced by Cmd_SetViewpos_f(), G_LeaveTank(), target_teleporter_use(), Touch_DoorTriggerSpectator(), and trigger_teleporter_touch().
void UpdateGoalEntity (gentity_t * oldent, gentity_t * newent)
Definition at line 201 of file g_etbot_interface.cpp.
Referenced by mg42_spawn(), and mg42_use().
void use_corona (gentity_t * ent, gentity_t * other, gentity_t * activator)
So level designers can toggle them on/off.
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 697 of file g_misc.c.
Referenced by SP_corona().
void use_dlight (gentity_t * ent, gentity_t * other, gentity_t * activator)
use_dlight
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 814 of file g_misc.c.
Referenced by SP_dlight().
void Use_Shooter (gentity_t * ent, gentity_t * other, gentity_t * activator)
SHOOTERS weapons WP_MAPMORTAR, WP_GRENADE_LAUNCHER/WP_GRENADE_PINEAPPLE and WP_PANZERFAUST/WP_BAZOOKA.
Parameters
[in] ent
other - unused
activator - unused
FIXME: enhance this one day so shooter can deal with more weapons (bullets -> map sniper fire)
Todo:
: why we do normalize the vector before this switch? See comment of fire_grenade
Definition at line 526 of file g_misc.c.
Referenced by InitShooter().
Variable Documentation
int dlightstarttime = 0 static
Definition at line 790 of file g_misc.c.
Referenced by SP_dlight().
char* predef_lightstyles[]
Initial value:
=
{
    "mmnmmommommnonmmonqnmmo",
    "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba",
    "mmmmmaaaaammmmmaaaaaabcdefgabcdefg",
    "ma",
    "jklmnopqrstuvwxyzyxwvutsrqponmlkj",
    "nmonqnmomnmomomono",
    "mmmaaaabcdefgmmmmaaaammmaamm",
    "aaaaaaaazzzzzzzz",
    "mmamammmmammamamaaamammma",
    "abcdefghijklmnopqrrqponmlkjihgfedcba",
    "mmnommomhkmmomnonmmonqnmmo",
    "kmamaamakmmmaakmamakmakmmmma",
    "kmmmakakmmaaamammamkmamakmmmma",
    "mmnnoonnmmmmmmmmmnmmmmnonmmmmmmm",
    "mmmmnonmmmmnmmmmmnonmmmmmnmmmmmmm",
    "zzzzzzzzaaaaaaaa",
    "zzzzzzzzaaaaaaaaaaaaaaaa",
    "aaaaaaaazzzzzzzzaaaaaaaa",
    "aaaaaaaaaaaaaaaazzzzzzzz"
}
Definition at line 757 of file g_misc.c.
Referenced by SP_dlight().