ET: Legacy: src/game/g_match.c File Reference
g_match.c File Reference
Match handling.
#include "g_local.h"
#include "../../etmain/ui/menudef.h"
Macros
#define GETVAL(x) if ((tmp = strchr(tmp, ' ')) == NULL) { return; } x = atoi(++tmp);
Functions
void G_initMatch (void)
G_initMatch.
void G_loadMatchGame (void)
Setting initialization.
void G_printFull (const char *str, gentity_t *ent)
Simple alias for sure-fire print :)
void G_globalSound (const char *sound)
Plays specified sound globally.
void G_globalSoundEnum (int sound)
G_globalSoundEnum.
void G_delayPrint (gentity_t *dpent)
G_delayPrint.
void G_spawnPrintf (int print_type, int print_time, gentity_t *owner)
G_spawnPrintf.
void G_addStats (gentity_t *targ, gentity_t *attacker, int damage, meansOfDeath_t mod)
G_addStats.
void G_addStatsHeadShot (gentity_t *attacker, meansOfDeath_t mod)
Records weapon headshots.
char * G_createStats (gentity_t *refEnt)
Generates weapon stat info for given ent.
void G_deleteStats (int nClient)
Resets player's current stats (session related only)
void G_parseStats (const char *pszStatsInfo)
Parses weapon stat info for given ent The given string must be space delimited and contain only integers.
void G_printMatchInfo (gentity_t *ent)
Prints current player match info.
void G_matchInfoDump (unsigned int dwDumpType)
Dumps end-of-match info.
int G_checkServerToggle (vmCvar_t *cv)
Update configstring for vote info.
void G_statsPrint (gentity_t *ent, int nType)
Sends a player's stats to the requesting client.
void G_resetRoundState (void)
G_resetRoundState.
void G_resetModeState (void)
G_resetModeState.
Variables
static char * pszDPInfo []
Detailed Description
Match handling.
Definition in file g_match.c.
Macro Definition Documentation
#define GETVAL (x) if ((tmp = strchr(tmp, ' ')) == NULL) { return; } x = atoi(++tmp);
Referenced by G_parseStats().
Function Documentation
void G_addStats (gentity_t * targ, gentity_t * attacker, int damage, meansOfDeath_t mod)
G_addStats.
Parameters
[in,out] targ
[in,out] attacker
[in] damage
[in] mod
Todo:
: inspect world kills count as selfkill?
Definition at line 272 of file g_match.c.
Referenced by G_BurnTarget(), G_Damage(), and player_die().
void G_addStatsHeadShot (gentity_t * attacker, meansOfDeath_t mod)
Records weapon headshots.
Parameters
[in,out] attacker
[in] mod
Definition at line 379 of file g_match.c.
Referenced by G_Damage().
int G_checkServerToggle (vmCvar_t * cv)
Update configstring for vote info.
Parameters
[in] cv
Returns
Definition at line 855 of file g_match.c.
Referenced by G_RegisterCvars(), and G_UpdateCvars().
char* G_createStats (gentity_t * refEnt)
Generates weapon stat info for given ent.
Parameters
[in] refEnt
Returns
Definition at line 400 of file g_match.c.
Referenced by ClientDisconnect(), G_matchInfoDump(), G_statsall_cmd(), and G_statsPrint().
void G_delayPrint (gentity_t * dpent)
G_delayPrint.
Parameters
[in,out] dpent
Definition at line 142 of file g_match.c.
Referenced by G_spawnPrintf().
void G_deleteStats (int nClient)
Resets player's current stats (session related only)
Parameters
[in] nClient
Definition at line 500 of file g_match.c.
Referenced by G_InitSessionData(), G_WriteClientSessionData(), and G_WriteSessionData().
void G_globalSound (const char * sound)
Plays specified sound globally.
Parameters
[in] sound
Definition at line 114 of file g_match.c.
Referenced by _et_G_globalSound(), G_delayPrint(), G_pause_cmd(), G_PlaySound_Cmd(), and G_refPause_cmd().
void G_globalSoundEnum (int sound)
G_globalSoundEnum.
Parameters
[in] sound
Definition at line 128 of file g_match.c.
Referenced by Cmd_CallVote_f(), G_pause_cmd(), and G_refPause_cmd().
void G_initMatch (void)
G_initMatch.
Definition at line 42 of file g_match.c.
Referenced by SP_worldspawn().
void G_loadMatchGame (void)
Setting initialization.
Definition at line 55 of file g_match.c.
Referenced by G_InitGame().
void G_matchInfoDump (unsigned int dwDumpType)
Dumps end-of-match info.
Parameters
dwDumpType
Definition at line 749 of file g_match.c.
Referenced by CheckIntermissionExit().
void G_parseStats (const char * pszStatsInfo)
Parses weapon stat info for given ent The given string must be space delimited and contain only integers.
Parameters
pszStatsInfo
Definition at line 545 of file g_match.c.
Referenced by G_ReadSessionData().
void G_printFull (const char * str, gentity_t * ent)
Simple alias for sure-fire print :)
Parameters
[in] str
[in] ent
Definition at line 96 of file g_match.c.
Referenced by G_delayPrint(), G_refLockTeams_cmd(), G_refSpeclockTeams_cmd(), G_specinvite_cmd(), G_speclock_cmd(), G_teamJoinCheck(), and G_teamready_cmd().
void G_printMatchInfo (gentity_t * ent)
Prints current player match info.
Parameters
[in] ent
Todo:
FIXME: put the pretty print on the client
Definition at line 591 of file g_match.c.
Referenced by G_matchInfoDump(), and G_scores_cmd().
void G_resetModeState (void)
G_resetModeState.
Definition at line 999 of file g_match.c.
Referenced by Svcmd_ResetMatch_f(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), and Svcmd_SwapTeams_f().
void G_resetRoundState (void)
G_resetRoundState.
Definition at line 983 of file g_match.c.
Referenced by Svcmd_ResetMatch_f(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), and Svcmd_SwapTeams_f().
void G_spawnPrintf (int print_type, int print_time, gentity_t * owner)
G_spawnPrintf.
Parameters
[in] print_type
[in] print_time
[in] owner
Definition at line 245 of file g_match.c.
Referenced by G_delayPrint(), G_InitGame(), G_pause_cmd(), and G_refPause_cmd().
void G_statsPrint (gentity_t * ent, int nType)
Sends a player's stats to the requesting client.
Parameters
[in] ent
[in] nType
Definition at line 935 of file g_match.c.
Referenced by ClientCommand(), and G_weaponStats_cmd().
Variable Documentation
char* pszDPInfo[] static
Initial value:
=
{
    "DPRINTF_PAUSEINFO",
    "DPRINTF_UNPAUSING",
    "DPRINTF_CONNECTINFO",
    "DPRINTF_MVSPAWN",
    "DPRINTF_UNK1",
    "DPRINTF_UNK2",
    "DPRINTF_UNK3",
    "DPRINTF_UNK4",
    "DPRINTF_UNK5"
}
Definition at line 226 of file g_match.c.
Referenced by G_spawnPrintf().