ET: Legacy: src/game/g_match_tokens.c File Reference
g_match_tokens.c File Reference
ANSI-C code produced by gperf version 3.0.3 (dirty)
#include <string.h>
#include "g_strparse.h"
Data Structures
struct g_strtoken_t
Macros
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 20
#define MAX_HASH_VALUE 95
Functions
static unsigned int hash (register const char *str, register unsigned int len)
const struct g_strtoken_t * in_word_set (register const char *str, register unsigned int len)
in_word_set
Detailed Description
ANSI-C code produced by gperf version 3.0.3 (dirty)
Command-line: gperf -t7C –language=ANSI-C input_tokens.gperf
Computed positions: -k'1-2'
Definition in file g_match_tokens.c.
Macro Definition Documentation
#define MAX_HASH_VALUE 95
Definition at line 47 of file g_match_tokens.c.
#define MAX_WORD_LENGTH 20
Definition at line 46 of file g_match_tokens.c.
#define MIN_WORD_LENGTH 1
Definition at line 45 of file g_match_tokens.c.
Referenced by in_word_set().
Function Documentation
static unsigned int hash (register const char * str, register unsigned int len) static
Definition at line 59 of file g_match_tokens.c.
Referenced by _HT_CreateEntry(), _HT_GetCIKey(), _HT_GetKey(), AddVertexToHashTable(), BG_AnimationIndexForString(), BG_IndexForString(), BG_StringHashValue(), BG_StringHashValue_Lwr(), CalculateGUID(), CalculateMD5ForSeed(), CG_SoundParseSounds(), CG_SoundPlaySoundScript(), CG_SoundScriptPrecache(), checkpoint_spawntouch(), Com_HashKey(), Com_InitDownloads(), Cvar_FindVar(), Cvar_Get(), FindGuideInGuideText(), FindShaderInShaderText(), FindShaderInShaderTextR1(), FindVertexInHashTable(), FS_FileIsInPAK(), FS_FOpenFileReadDir(), FS_HashFileName(), FS_LoadZipFile(), FS_Unzip(), func_explosive_explode(), G_FindByTargetname(), G_Script_ActionForString(), G_Script_EventForString(), G_Script_GetEventIndex(), G_ScriptAction_AlertEntity(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), G_ScriptAction_SetState(), G_ScriptAction_ToggleSpeaker(), G_UseTargets(), GeneratePermanentShader(), GeneratePermanentShaderTable(), GetMDMSurfaceShader(), GetOpType(), GL_BindNearestCubeMap(), GLSL_FindShader(), hashForString(), HT_DeleteItem(), HT_GetItem(), HT_PutItem(), in_word_set(), Key_GetBindingByString(), KeywordHash_Add(), KeywordHash_Find(), KeywordHash_Key(), MSG_HashKey(), PC_AddDefineToHash(), PC_Directive_undef(), PC_FindHashedDefine(), PC_NameHash(), Q_GenerateHashValue(), R_AddAnimSurfaces(), R_AddMD3Surfaces(), R_AddMDCSurfaces(), R_AllocImage(), R_CreateImage(), R_FindCachedImage(), R_FindCachedShader(), R_FindCubeImage(), R_FindImageFile(), R_FindShader(), R_FindShaderByName(), R_FindTwoNearestCubeMaps(), R_MDM_AddAnimSurfaces(), R_RemapShader(), R_TouchImage(), RE_GetShaderFromModel(), RE_GetSkinModel(), RE_RegisterShaderFromImage(), S_FindName(), S_HashSFXName(), ScanAndLoadShaderFilesR1(), String_Alloc(), SVC_BucketForAddress(), SVC_HashForAddress(), UI_LoadCampaigns(), and VertexCoordGenerateHash().
const struct g_strtoken_t* in_word_set (register const char * str, register unsigned int len)
in_word_set
Parameters
[in] str
[in] len
Returns
Definition at line 103 of file g_match_tokens.c.