ET: Legacy: src/game/g_mdx.h File Reference
g_mdx.h File Reference
Data Structures
struct mdm_hdr
The mdm_hdr struct.
struct mdm_tag
struct mdx_hdr
struct mdx_frame_bone
struct mdx_frame
struct mdx_bone
struct mdx
struct bone
struct frame_bone
struct frame
struct hit_area
struct tag
struct interntag_s
struct mdm_s
struct mdx_s
struct hit_s
Macros
#define REALHEAD_BONEHITS 128
#define REALHEAD_DEBUG_HEAD 256
#define REALHEAD_DEBUG_LEGS 512
#define REALHEAD_DEBUG_BODY 1024
#define RHTAG_CHEST 1
#define RHTAG_WEAPON 2
#define RHTAG_WEAPON2 3
Typedefs
typedef struct interntag_s interntag_t
typedef struct mdm_s mdm_t
typedef struct mdx_s mdx_t
typedef struct hit_s hit_t
Enumerations
enum mdx_advanced_position_t {
MRP_NECK, MRP_ELBOW_LEFT, MRP_ELBOW_RIGHT, MRP_HAND_LEFT,
MRP_HAND_RIGHT, MRP_BACK, MRP_CHEST, MRP_PELVIS,
MRP_KNEE_LEFT, MRP_KNEE_RIGHT, MRP_ANKLE_LEFT, MRP_ANKLE_RIGHT,
MRP_MAX
}
Functions
void mdx_cleanup (void)
qhandle_t trap_R_RegisterModel (const char *filename)
trap_R_RegisterModel
int trap_R_LerpTagNumber (orientation_t *tag, grefEntity_t *refent, int tagNum)
int trap_R_LookupTag (grefEntity_t *refent, const char *tagName)
int trap_R_LerpTag (orientation_t *tag, grefEntity_t *refent, const char *tagName, int startIndex)
void mdx_head_position (gentity_t *ent, grefEntity_t *refent, vec3_t org)
void mdx_legs_position (gentity_t *ent, grefEntity_t *refent, vec3_t org)
void mdx_tag_position (gentity_t *ent, grefEntity_t *refent, vec3_t org, const char *tagName, float up_offset, float forward_offset)
void mdx_PlayerAngles (gentity_t *ent, vec3_t legsAngles, vec3_t torsoAngles, vec3_t headAngles, qboolean doswing)
void mdx_PlayerAnimation (gentity_t *ent)
void mdx_gentity_to_grefEntity (gentity_t *ent, grefEntity_t *refent, int lerpTime)
void mdx_LoadHitsFile (char *animationGroup, animModelInfo_t *animModelInfo)
Macro Definition Documentation
#define REALHEAD_BONEHITS 128
Todo:
: enable this later on when fixed (&& figured out how the fuck it works)
Definition at line 39 of file g_mdx.h.
#define REALHEAD_DEBUG_BODY 1024
Definition at line 43 of file g_mdx.h.
#define REALHEAD_DEBUG_HEAD 256
Definition at line 41 of file g_mdx.h.
#define REALHEAD_DEBUG_LEGS 512
Definition at line 42 of file g_mdx.h.
#define RHTAG_CHEST 1
Definition at line 330 of file g_mdx.h.
#define RHTAG_WEAPON 2
Definition at line 331 of file g_mdx.h.
#define RHTAG_WEAPON2 3
Definition at line 332 of file g_mdx.h.
Typedef Documentation
hit_t
typedef struct interntag_s interntag_t
mdm_t
mdx_t
Enumeration Type Documentation
enum mdx_advanced_position_t
Enumerator
MRP_NECK
MRP_ELBOW_LEFT
MRP_ELBOW_RIGHT
MRP_HAND_LEFT
MRP_HAND_RIGHT
MRP_BACK
MRP_CHEST
MRP_PELVIS
MRP_KNEE_LEFT
MRP_KNEE_RIGHT
MRP_ANKLE_LEFT
MRP_ANKLE_RIGHT
MRP_MAX
Definition at line 342 of file g_mdx.h.
Function Documentation
void mdx_cleanup (void)
Referenced by G_ShutdownGame().
void mdx_gentity_to_grefEntity (gentity_t * ent, grefEntity_t * refent, int lerpTime)
Referenced by CopyToBodyQue(), G_BuildHead(), and G_BuildLeg().
void mdx_head_position (gentity_t * ent, grefEntity_t * refent, vec3_t org)
Referenced by G_BuildHead().
void mdx_legs_position (gentity_t * ent, grefEntity_t * refent, vec3_t org)
Referenced by G_BuildLeg().
void mdx_LoadHitsFile (char * animationGroup, animModelInfo_t * animModelInfo)
Referenced by G_RegisterCharacter().
void mdx_PlayerAngles (gentity_t * ent, vec3_t legsAngles, vec3_t torsoAngles, vec3_t headAngles, qboolean doswing)
void mdx_PlayerAnimation (gentity_t * ent)
Referenced by ClientEndFrame(), and CopyToBodyQue().
void mdx_tag_position (gentity_t * ent, grefEntity_t * refent, vec3_t org, const char * tagName, float up_offset, float forward_offset)
Referenced by CopyToBodyQue().
int trap_R_LerpTag (orientation_t * tag, grefEntity_t * refent, const char * tagName, int startIndex)
int trap_R_LerpTagNumber (orientation_t * tag, grefEntity_t * refent, int tagNum)
int trap_R_LookupTag (grefEntity_t * refent, const char * tagName)
qhandle_t trap_R_RegisterModel (const char * name)
trap_R_RegisterModel
Parameters
[in] name
Returns
Definition at line 1774 of file cg_syscalls.c.