ET: Legacy: src/game/g_mover.c File Reference
g_mover.c File Reference
#include "g_local.h"
#include "g_etbot_interface.h"
Data Structures
struct pushed_t
Macros
#define PUSH_STACK_DEPTH 3
#define JITTER_INC 4
#define JITTER_MAX (check->r.maxs[0] / 2.0f)
#define TRAIN_BLOCK_STOPS 4
#define CONSTRUCT_PREDECAY_TIME 30000
Functions
void MatchTeam (gentity_t *teamLeader, moverState_t moverState, int time)
All entities in a mover team will move from pos1 to pos2 in the same amount of time.
void Reached_Train (gentity_t *ent)
Reached_Train.
void Think_BeginMoving (gentity_t *ent)
The wait time at a corner has completed, so start moving again.
void Use_Func_Rotate (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Func_Rotate.
void Blocked_Door (gentity_t *ent, gentity_t *other)
Blocked_Door.
void Blocked_DoorRotate (gentity_t *ent, gentity_t *other)
Blocked_DoorRotate.
gentity_t * G_TestEntityPosition (gentity_t *ent)
G_TestEntityPosition.
qboolean G_TryPushingEntity (gentity_t *check, gentity_t *pusher, vec3_t move, vec3_t amove)
G_TryPushingEntity.
void LandMineTrigger (gentity_t *self)
LandMineTrigger.
void GibEntity (gentity_t *self, int killer)
GibEntity.
qboolean G_MoverPush (gentity_t *pusher, vec3_t move, vec3_t amove, gentity_t **obstacle)
Objects need to be moved back on a failed push, otherwise riders would continue to slide.
void G_MoverTeam (gentity_t *ent)
G_MoverTeam.
void G_RunMover (gentity_t *ent)
G_RunMover.
void SetMoverState (gentity_t *ent, moverState_t moverState, int time)
SetMoverState.
void MatchTeamReverseAngleOnSlaves (gentity_t *teamLeader, moverState_t moverState, int time)
The activator was blocking the door so reverse its direction.
void ReturnToPos1 (gentity_t *ent)
ReturnToPos1.
void ReturnToPos2 (gentity_t *ent)
ReturnToPos2.
void GotoPos3 (gentity_t *ent)
GotoPos3.
void ReturnToPos1Rotate (gentity_t *ent)
Closing.
void Reached_BinaryMover (gentity_t *ent)
Reached_BinaryMover.
qboolean IsBinaryMoverBlocked (gentity_t *ent, gentity_t *other, gentity_t *activator)
IsBinaryMoverBlocked.
void Reached_TrinaryMover (gentity_t *ent)
Reached_TrinaryMover.
void Use_TrinaryMover (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_TrinaryMover.
void Use_BinaryMover (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_BinaryMover.
void InitMover (gentity_t *ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
void InitMoverRotate (gentity_t *ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
static void Touch_DoorTriggerSpectator (gentity_t *ent, gentity_t *other, trace_t *trace)
Touch_DoorTriggerSpectator.
void Touch_DoorTrigger (gentity_t *ent, gentity_t *other, trace_t *trace)
Touch_DoorTrigger.
void Think_SpawnNewDoorTrigger (gentity_t *ent)
All of the parts of a door have been spawned, so create a trigger that encloses all of them.
void Think_MatchTeam (gentity_t *ent)
Think_MatchTeam.
qboolean findNonAIBrushTargeter (gentity_t *ent)
determine if there is an entity pointing at ent that is not a "trigger_aidoor" (used now for checking which key to set for a door)
void finishSpawningKeyedMover (gentity_t *ent)
finishSpawningKeyedMover
void Door_reverse_sounds (gentity_t *ent)
The door has been marked as "START_OPEN" which means the open/closed positions have been swapped. This swaps the sounds around as well.
void DoorSetSounds (gentity_t *ent, int doortype, qboolean isRotating)
Get sound indexes for the various door sounds (used by SP_func_door() and SP_func_door_rotating())
void G_TryDoor (gentity_t *ent, gentity_t *other, gentity_t *activator)
Seemed better to have this isolated. this way i can get func_invisible_user's using the regular rules of doors.
void SP_func_door (gentity_t *ent)
SP_func_door.
void SP_func_secret (gentity_t *ent)
SP_func_secret.
void Touch_Plat (gentity_t *ent, gentity_t *other, trace_t *trace)
Don't allow decent if a living player is on it.
void Touch_PlatCenterTrigger (gentity_t *ent, gentity_t *other, trace_t *trace)
If the plat is at the bottom position, start it going up.
void SpawnPlatTrigger (gentity_t *ent)
Spawn a trigger in the middle of the plat's low position Elevator cars require that the trigger extend through the entire low position, not just sit on top of it.
void SP_func_plat (gentity_t *ent)
SP_func_plat.
void Touch_Button (gentity_t *ent, gentity_t *other, trace_t *trace)
Touch_Button.
void SP_func_button (gentity_t *ent)
SP_func_button.
void Think_SetupTrainTargets (gentity_t *ent)
Link all the corners together.
void SP_path_corner (gentity_t *self)
SP_path_corner.
void SP_path_corner_2 (gentity_t *self)
QUAKED path_corner_2 (.5 .3 0) (-8 -8 -8) (8 8 8) STOP END REVERSE Train path corners. THIS VERSION WILL NOT CONTRIBUTE TOWARDS INGAME ENTITY COUNT "targetname" The script uses this name to identify the corner.
void SP_info_train_spline_main (gentity_t *self)
SP_info_train_spline_main.
void info_limbo_camera_setup (gentity_t *self)
info_limbo_camera_setup
void SP_info_limbo_camera (gentity_t *self)
SP_info_limbo_camera.
void SP_func_train (gentity_t *self)
SP_func_train.
void Think_BeginMoving_rotating (gentity_t *ent)
The wait time at a corner has completed, so start moving again.
void Reached_Train_rotating (gentity_t *ent)
Reached_Train_rotating.
void Think_SetupTrainTargets_rotating (gentity_t *ent)
Link all the corners together.
void SP_func_train_rotating (gentity_t *self)
SP_func_train_rotating.
void Use_Static (gentity_t *ent, gentity_t *other, gentity_t *activator)
Toggle hide or show (including collisions) this entity.
void Static_Pain (gentity_t *ent, gentity_t *attacker, int damage, vec3_t point)
Static_Pain.
void G_BlockThink (gentity_t *ent)
G_BlockThink.
void SP_func_leaky (gentity_t *ent)
SP_func_leaky.
void SP_func_static (gentity_t *ent)
SP_func_static.
void SP_func_rotating (gentity_t *ent)
SP_func_rotating.
void SP_func_bobbing (gentity_t *ent)
SP_func_bobbing.
void SP_func_pendulum (gentity_t *ent)
SP_func_pendulum.
void SP_func_door_rotating (gentity_t *ent)
SP_func_door_rotating.
void target_effect (gentity_t *self, gentity_t *other, gentity_t *activator)
target_effect
void SP_target_effect (gentity_t *ent)
SP_target_effect.
void BecomeExplosion (gentity_t *self)
Nuke the original entity and create all the debris entities that need to be synced to clients.
void func_explosive_explode (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
func_explosive_explode
void func_explosive_touch (gentity_t *self, gentity_t *other, trace_t *trace)
func_explosive_touch
void func_explosive_use (gentity_t *self, gentity_t *other, gentity_t *activator)
func_explosive_use
void func_explosive_alert (gentity_t *self)
func_explosive_alert
void func_explosive_spawn (gentity_t *self, gentity_t *other, gentity_t *activator)
func_explosive_spawn
void InitExplosive (gentity_t *ent)
InitExplosive.
void target_explosion_use (gentity_t *self, gentity_t *other, gentity_t *attacker)
void SP_target_explosion (gentity_t *ent)
SP_target_explosion.
void SP_func_explosive (gentity_t *ent)
SP_func_explosive.
void use_invisible_user (gentity_t *ent, gentity_t *other, gentity_t *activator)
use_invisible_user
void SP_func_invisible_user (gentity_t *ent)
SP_func_invisible_user.
void InitConstructible (gentity_t *ent)
InitConstructible.
void func_constructible_spawn (gentity_t *self, gentity_t *other, gentity_t *activator)
func_constructible_spawn
void func_constructible_use (gentity_t *self, gentity_t *other, gentity_t *activator)
func_constructible_use
void func_constructible_explode (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
func_constructible_explode
void func_constructible_underconstructionthink (gentity_t *ent)
func_constructible_underconstructionthink
void explosive_indicator_think (gentity_t *ent)
Spawn an explosive indicator.
void func_constructiblespawn (gentity_t *ent)
func_constructiblespawn
void SP_func_constructible (gentity_t *ent)
SP_func_constructible.
void func_brushmodel_delete (gentity_t *ent)
func_brushmodel_delete
void SP_func_brushmodel (gentity_t *ent)
SP_func_brushmodel.
debrisChunk_t * G_AllocDebrisChunk (void)
G_AllocDebrisChunk.
void SP_func_debris (gentity_t *ent)
SP_func_debris.
void G_LinkDamageParents (void)
G_LinkDamageParents.
void G_LinkDebris (void)
G_LinkDebris.
Variables
const char * hintStrings [HINT_NUM_HINTS]
int pushedStackDepth = 0
pushed_t pushed [MAX_GENTITIES *PUSH_STACK_DEPTH]
pushed_t * pushed_p
g_constructible_stats_t g_constructible_classes [NUM_CONSTRUCTIBLE_CLASSES]
Macro Definition Documentation
#define CONSTRUCT_PREDECAY_TIME 30000
If not under construction for this duration, start decaying
Definition at line 5290 of file g_mover.c.
Referenced by func_constructible_underconstructionthink().
#define JITTER_INC 4
Referenced by G_TryPushingEntity().
#define JITTER_MAX (check->r.maxs[0] / 2.0f)
Referenced by G_TryPushingEntity().
#define PUSH_STACK_DEPTH 3
Definition at line 110 of file g_mover.c.
Referenced by G_TryPushingEntity().
#define TRAIN_BLOCK_STOPS 4
Definition at line 2946 of file g_mover.c.
Referenced by SP_func_train(), and SP_func_train_rotating().
Function Documentation
void BecomeExplosion (gentity_t * self)
Nuke the original entity and create all the debris entities that need to be synced to clients.
=============================================================================== EXPLOSIVE
Note
I'm keeping all this stuff in here just to avoid collisions with Raf right now in g_misc or g_props
Will move.
Parameters
self
Definition at line 4303 of file g_mover.c.
Referenced by func_explosive_explode().
void Blocked_Door (gentity_t * ent, gentity_t * other)
Blocked_Door.
=============================================================================== DOOR
A use can be triggered either by a touch function, by being shot, or by being
targeted by another entity.
Parameters
[in] ent
[in] other
Definition at line 1989 of file g_mover.c.
Referenced by SP_func_door(), SP_func_plat(), SP_func_secret(), SP_func_train(), and Use_BinaryMover().
void Blocked_DoorRotate (gentity_t * ent, gentity_t * other)
Blocked_DoorRotate.
Parameters
[in] ent
[in] other
Definition at line 2079 of file g_mover.c.
Referenced by SP_func_door_rotating(), and Use_BinaryMover().
void Door_reverse_sounds (gentity_t * ent)
The door has been marked as "START_OPEN" which means the open/closed positions have been swapped. This swaps the sounds around as well.
Parameters
ent
Definition at line 2299 of file g_mover.c.
Referenced by SP_func_door().
void DoorSetSounds (gentity_t * ent, int doortype, qboolean isRotating)
Get sound indexes for the various door sounds (used by SP_func_door() and SP_func_door_rotating())
Parameters
[out] ent
[in] doortype
isRotating - unused
Definition at line 2331 of file g_mover.c.
Referenced by SP_func_door(), and SP_func_door_rotating().
void explosive_indicator_think (gentity_t * ent)
Spawn an explosive indicator.
Parameters
[in,out] ent
Definition at line 1467 of file g_trigger.c.
Referenced by func_constructible_underconstructionthink(), and func_constructiblespawn().
qboolean findNonAIBrushTargeter (gentity_t * ent)
determine if there is an entity pointing at ent that is not a "trigger_aidoor" (used now for checking which key to set for a door)
Parameters
[in] ent
Returns
Definition at line 2215 of file g_mover.c.
Referenced by finishSpawningKeyedMover().
void finishSpawningKeyedMover (gentity_t * ent)
finishSpawningKeyedMover
Parameters
[in,out] ent
Todo:
: is this safe? is ent->spawnflags & 8 consistant among all keyed ents?
Definition at line 2240 of file g_mover.c.
Referenced by SP_func_door(), SP_func_door_rotating(), and SP_func_secret().
void func_brushmodel_delete (gentity_t * ent)
func_brushmodel_delete
QUAKED func_brushmodel (.9 .50 .50) ? A brushmodel that gets deleted on the fourth frame. We use this to hijack it's brushmodel in func_constructible entities that are based around staged construction.
Parameters
[in] ent
Definition at line 5729 of file g_mover.c.
Referenced by SP_func_brushmodel().
void func_constructible_explode (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
func_constructible_explode
Parameters
[in,out] self
[in] inflictor
[in] attacker
damage - unused
[in] mod
Definition at line 5067 of file g_mover.c.
Referenced by func_constructiblespawn().
void func_constructible_spawn (gentity_t * self, gentity_t * other, gentity_t * activator)
func_constructible_spawn
Parameters
[in,out] self
other - unused
activator - unused
Definition at line 5052 of file g_mover.c.
Referenced by func_constructible_use(), func_constructiblespawn(), and InitConstructible().
void func_constructible_underconstructionthink (gentity_t * ent)
func_constructible_underconstructionthink
Parameters
[in,out] ent
Todo:
: truck?
Definition at line 5296 of file g_mover.c.
Referenced by TryConstructing().
void func_constructible_use (gentity_t * self, gentity_t * other, gentity_t * activator)
func_constructible_use
Parameters
[in,out] self
other - unused
activator - unused
Todo:
make this explode or so?
Definition at line 4965 of file g_mover.c.
Referenced by func_constructible_spawn(), and func_constructiblespawn().
void func_constructiblespawn (gentity_t * ent)
func_constructiblespawn
Parameters
[in,out] ent
Todo:
: allow other contents?
Todo:
: allow other contents?
Definition at line 5407 of file g_mover.c.
Referenced by SP_func_constructible().
void func_explosive_alert (gentity_t * self)
func_explosive_alert
Parameters
[in] self
Definition at line 4457 of file g_mover.c.
Referenced by SP_func_explosive().
void func_explosive_explode (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
func_explosive_explode
Parameters
[in,out] self
inflictor - unuses
[in] attacker
damage - unused
[in] mod
Note
The 'damage' passed in is ignored completely
Todo:
: use self->targetnamehash one day ...
Definition at line 4325 of file g_mover.c.
Referenced by func_explosive_alert(), func_explosive_touch(), func_explosive_use(), and SP_func_explosive().
void func_explosive_spawn (gentity_t * self, gentity_t * other, gentity_t * activator)
func_explosive_spawn
Parameters
[in] self
other - unused
activator - unused
Definition at line 4468 of file g_mover.c.
Referenced by SP_func_explosive().
void func_explosive_touch (gentity_t * self, gentity_t * other, trace_t * trace)
func_explosive_touch
Parameters
[in] self
[in] other
trace - unused
Definition at line 4430 of file g_mover.c.
Referenced by SP_func_explosive().
void func_explosive_use (gentity_t * self, gentity_t * other, gentity_t * activator)
func_explosive_use
Parameters
[in] self
[in] other
activator - unused
Definition at line 4441 of file g_mover.c.
Referenced by func_explosive_spawn(), and SP_func_explosive().
debrisChunk_t* G_AllocDebrisChunk (void)
G_AllocDebrisChunk.
Debris test
Returns
Definition at line 5764 of file g_mover.c.
Referenced by SP_func_debris().
void G_BlockThink (gentity_t * ent)
G_BlockThink.
Parameters
[out] ent
Definition at line 3690 of file g_mover.c.
Referenced by InitExplosive().
void G_LinkDamageParents (void)
G_LinkDamageParents.
Definition at line 5817 of file g_mover.c.
Referenced by G_InitGame().
void G_LinkDebris (void)
G_LinkDebris.
Definition at line 5838 of file g_mover.c.
Referenced by G_InitGame().
qboolean G_MoverPush (gentity_t * pusher, vec3_t move, vec3_t amove, gentity_t ** obstacle)
Objects need to be moved back on a failed push, otherwise riders would continue to slide.
Parameters
[in,out] pusher
[in] move
[in] amove
[in] obstacle
Returns
If qfalse, *obstacle will be the blocking entity
Definition at line 498 of file g_mover.c.
Referenced by G_MoverTeam(), and G_TagLinkEntity().
void G_MoverTeam (gentity_t * ent)
G_MoverTeam.
Parameters
[in] ent
Definition at line 748 of file g_mover.c.
Referenced by G_RunMover().
void G_RunMover (gentity_t * ent)
G_RunMover.
Parameters
[in,out] ent
Definition at line 833 of file g_mover.c.
Referenced by G_RunEntity().
gentity_t* G_TestEntityPosition (gentity_t * ent)
G_TestEntityPosition.
Parameters
[in] ent
Returns
Definition at line 128 of file g_mover.c.
Referenced by func_constructible_explode(), G_MoverPush(), G_SetEntState(), G_TryPushingEntity(), HandleEntsThatBlockConstructible(), and WolfReviveBbox().
void G_TryDoor (gentity_t * ent, gentity_t * other, gentity_t * activator)
Seemed better to have this isolated. this way i can get func_invisible_user's using the regular rules of doors.
Parameters
[in,out] ent
other - unused
[in] activator
Definition at line 2354 of file g_mover.c.
Referenced by Do_Activate_f(), and G_UseTargets().
qboolean G_TryPushingEntity (gentity_t * check, gentity_t * pusher, vec3_t move, vec3_t amove)
G_TryPushingEntity.
Parameters
[in,out] check
[in] pusher
[in] move
[in] amove
Returns
qfalse if the move is blocked
Definition at line 296 of file g_mover.c.
Referenced by G_MoverPush().
void GibEntity (gentity_t * self, int killer)
GibEntity.
Parameters
[in,out] self
[in] killer
Definition at line 206 of file g_combat.c.
Referenced by body_die(), G_Damage(), G_MoverPush(), G_TryPushingEntity(), and player_die().
void GotoPos3 (gentity_t * ent)
GotoPos3.
Parameters
[in,out] ent
Definition at line 1131 of file g_mover.c.
Referenced by Reached_TrinaryMover().
void info_limbo_camera_setup (gentity_t * self)
info_limbo_camera_setup
QUAKED info_limbo_camera (.5 .0 .0) ? (-8 -8 -8) (8 8 8) Camera for limbo menu, target at an appropriate entity (spawn flag, script mover, position marker...)
Parameters
[in] self
Definition at line 3209 of file g_mover.c.
Referenced by SP_info_limbo_camera().
void InitConstructible (gentity_t * ent)
InitConstructible.
Parameters
[in,out] ent
Definition at line 4949 of file g_mover.c.
Referenced by func_constructiblespawn().
void InitExplosive (gentity_t * ent)
InitExplosive.
Parameters
[in,out] ent
Definition at line 4479 of file g_mover.c.
Referenced by SP_func_explosive().
void InitMover (gentity_t * ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
Parameters
[in,out] ent
Definition at line 1823 of file g_mover.c.
Referenced by G_ScriptAction_GotoMarker(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_secret(), SP_func_static(), SP_func_train(), SP_func_train_rotating(), and SP_script_mover().
void InitMoverRotate (gentity_t * ent)
"pos1", "pos2", and "speed" should be set before calling, so the movement delta can be calculated
Parameters
[in,out] ent
Definition at line 1895 of file g_mover.c.
Referenced by SP_func_door_rotating(), and SP_Props_Flipping_Table().
qboolean IsBinaryMoverBlocked (gentity_t * ent, gentity_t * other, gentity_t * activator)
IsBinaryMoverBlocked.
Parameters
[in] ent
[in] other
[in] activator
Returns
Definition at line 1300 of file g_mover.c.
Referenced by Use_BinaryMover(), and Use_TrinaryMover().
void LandMineTrigger (gentity_t * self)
LandMineTrigger.
Parameters
[in,out] self
Definition at line 1414 of file g_missile.c.
Referenced by G_LandmineThink(), G_MoverPush(), and G_TryPushingEntity().
void MatchTeam (gentity_t * teamLeader, moverState_t moverState, int time)
All entities in a mover team will move from pos1 to pos2 in the same amount of time.
Parameters
[in] teamLeader
[in] moverState
[in] time
Definition at line 1046 of file g_mover.c.
Referenced by GotoPos3(), ReturnToPos1(), ReturnToPos1Rotate(), ReturnToPos2(), Think_MatchTeam(), Think_SpawnNewDoorTrigger(), Use_BinaryMover(), and Use_TrinaryMover().
void MatchTeamReverseAngleOnSlaves (gentity_t * teamLeader, moverState_t moverState, int time)
The activator was blocking the door so reverse its direction.
Parameters
[in] teamLeader
[in] moverState
[in] time
Definition at line 1072 of file g_mover.c.
Referenced by Use_BinaryMover(), and Use_TrinaryMover().
void Reached_BinaryMover (gentity_t * ent)
Reached_BinaryMover.
Parameters
[in,out] ent
Definition at line 1167 of file g_mover.c.
Referenced by InitMover(), and InitMoverRotate().
void Reached_Train (gentity_t * ent)
Reached_Train.
Parameters
[in,out] ent
Definition at line 2962 of file g_mover.c.
Referenced by SP_func_train(), and Think_SetupTrainTargets().
void Reached_Train_rotating (gentity_t * ent)
Reached_Train_rotating.
Parameters
[in,out] ent
Todo:
: trDuration is not float, does floor(int) make sense? - inspect!
Definition at line 3373 of file g_mover.c.
Referenced by SP_func_train_rotating(), and Think_SetupTrainTargets_rotating().
void Reached_TrinaryMover (gentity_t * ent)
Reached_TrinaryMover.
Parameters
[in,out] ent
Definition at line 1381 of file g_mover.c.
Referenced by InitMover().
void ReturnToPos1 (gentity_t * ent)
ReturnToPos1.
Parameters
[in,out] ent
Definition at line 1099 of file g_mover.c.
Referenced by Reached_BinaryMover(), and Reached_TrinaryMover().
void ReturnToPos1Rotate (gentity_t * ent)
Closing.
Parameters
[in,out] ent
Definition at line 1147 of file g_mover.c.
Referenced by Reached_BinaryMover().
void ReturnToPos2 (gentity_t * ent)
ReturnToPos2.
Parameters
[in,out] ent
Definition at line 1115 of file g_mover.c.
Referenced by Reached_TrinaryMover().
void SetMoverState (gentity_t * ent, moverState_t moverState, int time)
SetMoverState.
Parameters
[in,out] ent
[in] moverState
[in] time
Definition at line 880 of file g_mover.c.
Referenced by Blocked_Door(), Blocked_DoorRotate(), G_ScriptAction_GotoMarker(), MatchTeam(), MatchTeamReverseAngleOnSlaves(), Reached_BinaryMover(), Reached_Train(), Reached_Train_rotating(), and Reached_TrinaryMover().
void SP_func_bobbing (gentity_t * ent)
SP_func_bobbing.
QUAKED func_bobbing (0 .5 .8) ? X_AXIS Y_AXIS Normally bobs on the Z axis "model2" .md3 model to also draw "height" amplitude of bob (32 default) "speed" seconds to complete a bob cycle (4 default) "phase" the 0.0 to 1.0 offset in the cycle to start at "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius
Parameters
[in,out] ent
Definition at line 3930 of file g_mover.c.
void SP_func_brushmodel (gentity_t * ent)
SP_func_brushmodel.
Parameters
[in,out] ent
Definition at line 5738 of file g_mover.c.
void SP_func_button (gentity_t * ent)
SP_func_button.
QUAKED func_button (0 .5 .8) ? x x x TOUCH x x STAYOPEN When a button is touched, it moves some distance in the direction of it's angle, triggers all of it's targets, waits some time, then returns to it's original position where it can be triggered again.
"model2" .md3 model to also draw "angle" determines the opening direction "target" all entities with a matching targetname will be used "speed" override the default 40 speed "wait" override the default 1 second wait (-1 = never return) "lip" override the default 4 pixel lip remaining at end of move "health" if set, the button must be killed instead of touched "color" constantLight color "light" constantLight radius
Parameters
ent
Definition at line 2886 of file g_mover.c.
void SP_func_constructible (gentity_t * ent)
SP_func_constructible.
QUAKED func_constructible (.9 .75 .15) ? START_BUILT INVULNERABLE AXIS_CONSTRUCTIBLE ALLIED_CONSTRUCTIBLE BLOCK_PATHS_WHEN_BUILT NO_AAS_BLOCKING AAS_SCRIPTED A constructible object that functions as target for engineers. "track" functions as a group name. All entities with the same 'track' as the func_constructible will be constructed at the same time. "constages" list of target func_brushmodel entities (up to 3) that make up the construction stages (example: "stage1;stage2;") "desstages" list of target func_brushmodel entities (up to 3) that make up the destruction stages (example: "desstage1;desstage2;")
START_BUILT : building starts built INVULNERABLE : building can't be destroyed AXIS_CONSTRUCTIBLE : building is constructible by axis ALLIED_CONSTRUCTIBLE : building is constructible by allies BLOCK_PATHS_WHEN_BUILT : when built, areas touching structures are blocked NO_AAS_BLOCKING : dont interact with AAS at all
Parameters
[in,out] ent
Definition at line 5671 of file g_mover.c.
void SP_func_debris (gentity_t * ent)
SP_func_debris.
Parameters
[in] ent
Definition at line 5779 of file g_mover.c.
void SP_func_door (gentity_t * ent)
SP_func_door.
QUAKED func_door (0 .5 .8) ? START_OPEN TOGGLE CRUSHER TOUCH SHOOT-THRU TOGGLE wait in both the start and end states for a trigger event. START_OPEN the door to moves to its destination when spawned, and operate in reverse. It is used to temporarily or permanently close off an area when triggered (not useful for touch or takedamage doors). NOMONSTER monsters will not trigger this door
"key" -1 for locked, key number for which key opens, 0 for open. default '0' unless door is targeted. (trigger_aidoor entities targeting this door do /not/ affect the key status) "model2" .md3 model to also draw "angle" determines the opening direction "targetname" if set, no touch field will be spawned and a remote button or trigger field activates the door. "speed" movement speed (100 default) "closespeed" optional different movement speed for door closing "wait" wait before returning (3 default, -1 = never return) "lip" lip remaining at end of move (8 default) "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius "health" if set, the door must be shot open "team" team name. other doors with same team name will open/close in syncronicity "lockpickTime" time to unpick the lock on a locked door - use with key set to 99 "type" use sounds based on construction of door: 0 - nosound (default) 1 - metal 2 - stone 3 - lab 4 - wood 5 - iron/jail 6 - portcullis 7 - wood (quiet)
SOUND NAMING INFO - inside "sound/movers/doors/door<number>... _open.wav // opening _endo.wav // open _close.wav // closing _endc.wav // closed _loopo.wav // opening loop _loopc.wav // closing loop _locked.wav // locked
_openq.wav // opening quietly _endoq.wav // open quietly _closeq.wav // closing quietly _endcq.wav // closed quietly
and for rotating doors: _kicked.wav _kickedend.wav
Parameters
[in,out] ent
Todo:
: never executed !
Definition at line 2447 of file g_mover.c.
void SP_func_door_rotating (gentity_t * ent)
SP_func_door_rotating.
QUAKED func_door_rotating (0 .5 .8) ? - TOGGLE X_AXIS Y_AXIS REVERSE FORCE STAYOPEN TAKE_KEY You need to have an origin brush as part of this entity. The center of that brush will be the point around which it is rotated. It will rotate around the Z axis by default. You can check either the X_AXIS or Y_AXIS box to change that (only one axis allowed. If both X and Y are checked, the default of Z will be used). FORCE door opens even if blocked TAKE_KEY removes the key from the players inventory AXIS_ONLY Only axis team can open the doors ALLIES_ONLY Only allied team can open the doors ACCEPT_CVOPS Accept a disguised covert ops as a valid team member for team only doors
"key" -1 for locked, key number for which key opens, 0 for open. default '0' unless door is targeted. (trigger_aidoor entities targeting this door do /not/ affect the key status) "model2" .md3 model to also draw "degrees" determines how many degrees it will turn (90 default) "speed" movement speed (100 default) "closespeed" optional different movement speed for door closing "time" how many milliseconds it will take to open 1 sec = 1000 "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius "lockpickTime" time to unpick the lock on a locked door - use with key set to 99 "type" use sounds based on construction of door: 0 - nosound (default) 1 - metal 2 - stone 3 - lab 4 - wood 5 - iron/jail 6 - portcullis 7 - wood (quiet) "team" team name. other doors with same team name will open/close in syncronicity
Parameters
[in,out] ent
Todo:
: never execute
Definition at line 4061 of file g_mover.c.
void SP_func_explosive (gentity_t * ent)
SP_func_explosive.
QUAKED func_explosive (0 .5 .8) ? START_INVIS TOUCHABLE USESHADER LOWGRAV NOBLOCKAAS TANK Any brush that you want to explode or break apart. If you want an explosion, set dmg and it will do a radius explosion of that amount at the center of the bursh. TOUCHABLE means automatic use on player contact. USESHADER will apply the shader used on the brush model to the debris. LOWGRAV specifies that the debris will /always/ fall slowly "item" - when it explodes, pop this item out with the debirs (use QUAKED name. ex: "item_health_small") "dmg" - how much radius damage should be done, defaults to 0 "health" - defaults to 100. If health is set to '0' the brush will not be shootable. "targetname" - if set, no touch field will be spawned and a remote button or trigger field triggers the explosion. "type" - type of debris ("glass", "wood", "metal", "gibs", "brick", "rock", "fabric") default is "wood" "mass" - defaults to 75. This determines how much debris is emitted when it explodes. You get one large chunk per 100 of mass (up to 8) and one small chunk per 25 of mass (up to 16). So 800 gives the most. "noise" - sound to play when triggered. The explosive will default to a sound that matches it's 'type'. Use the sound name "nosound" (case in-sensitive) if you want it silent. the default sounds are: "wood" - "sound/world/boardbreak.wav" "glass" - "sound/world/glassbreak_01.wav" "metal" - "sound/world/metalbreak.wav" "gibs" - "sound/player/gibsplit1.wav" "brick" - "sound/world/debris1.wav" "stone" - "sound/world/stonefall.wav" "fabric" - "sound/world/metalbreak.wav" "fxdensity" size of explosion 1 - 100 (default is 10)
Parameters
[in,out] ent
Todo:
: test this
Definition at line 4671 of file g_mover.c.
void SP_func_invisible_user (gentity_t * ent)
SP_func_invisible_user.
Parameters
[in,out] ent
Definition at line 4896 of file g_mover.c.
void SP_func_leaky (gentity_t * ent)
SP_func_leaky.
QUAKED func_leaky (0 .5 .8) ? "type" - leaks particles of this type
1:oil 2:water 3:steam
Parameters
[in,out] ent
Definition at line 3707 of file g_mover.c.
void SP_func_pendulum (gentity_t * ent)
SP_func_pendulum.
QUAKED func_pendulum (0 .5 .8) ? You need to have an origin brush as part of this entity. Pendulums always swing north / south on unrotated models. Add an angles field to the model to allow rotation in other directions. Pendulum frequency is a physical constant based on the length of the beam and gravity. "model2" .md3 model to also draw "speed" the number of degrees each way the pendulum swings, (30 default) "phase" the 0.0 to 1.0 offset in the cycle to start at "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius
Parameters
ent
Definition at line 3987 of file g_mover.c.
void SP_func_plat (gentity_t * ent)
SP_func_plat.
QUAKED func_plat (0 .5 .8) ? Plats are always drawn in the extended position so they will light correctly.
"lip" default 8, protrusion above rest position "height" total height of movement, defaults to model height "speed" overrides default 200. "dmg" overrides default 2 "model2" .md3 model to also draw "color" constantLight color "light" constantLight radius
Parameters
ent
Definition at line 2797 of file g_mover.c.
void SP_func_rotating (gentity_t * ent)
SP_func_rotating.
Parameters
[in,out] ent
Definition at line 3860 of file g_mover.c.
void SP_func_secret (gentity_t * ent)
SP_func_secret.
QUAKED func_secret (0 .5 .8) ? REVERSE x CRUSHER TOUCH TOGGLE wait in both the start and end states for a trigger event. START_OPEN the door to moves to its destination when spawned, and operate in reverse. It is used to temporarily or permanently close off an area when triggered (not useful for touch or takedamage doors). NOMONSTER monsters will not trigger this door
"key" -1 for locked, key number for which key opens, 0 for open. default '0' unless door is targeted. (trigger_aidoor entities targeting this door do /not/ affect the key status) "model2" .md3 model to also draw "angle" determines the opening direction "targetname" if set, no touch field will be spawned and a remote button or trigger field activates the door. "speed" movement speed (100 default) "wait" wait before returning (2 default, -1 = never return) "lip" lip remaining at end of move (8 default) "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius "health" if set, the door must be shot open "lockpickTime" time to unpick the lock on a locked door - use with key set to 99
Parameters
[in,out] ent
Todo:
: never executed !
Definition at line 2585 of file g_mover.c.
void SP_func_static (gentity_t * ent)
SP_func_static.
QUAKED func_static (0 .5 .8) ? start_invis pain painEFX A bmodel that just sits there, doing nothing. Can be used for conditional walls and models. "model2" .md3 model to also draw "color" constantLight color "light" constantLight radius "start_invis" will start the entity as non-existant If targeted, it will toggle existance when triggered
pain will use its target
When using pain you will need to specify the delay time value of 1 = 1 sec 2 = 2 sec so on... default is 1 sec you can use decimals example : delay 1.27
painEFX will spawn a shards example: shard 4 will spawn rubble
shard default is 4
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] ent
Definition at line 3755 of file g_mover.c.
void SP_func_train (gentity_t * self)
SP_func_train.
QUAKED func_train (0 .5 .8) ? START_ON TOGGLE BLOCK_STOPS A train is a mover that moves between path_corner target points. Trains MUST HAVE AN ORIGIN BRUSH. The train spawns at the first target it is pointing at. "model2" .md3 model to also draw "speed" default 100 "dmg" default 2 "noise" looping sound to play when the train is in motion "target" next path corner "color" constantLight color "light" constantLight radius
Parameters
[in,out] self
Definition at line 3317 of file g_mover.c.
void SP_func_train_rotating (gentity_t * self)
SP_func_train_rotating.
QUAKED func_train_rotating (0 .5 .8) ? START_ON TOGGLE BLOCK_STOPS A train is a mover that moves between path_corner target points. This train can also rotate along the X Y Z Trains MUST HAVE AN ORIGIN BRUSH. The train spawns at the first target it is pointing at.
"model2" .md3 model to also draw "dmg" default 2 "speed" default 100 "noise" looping sound to play when the train is in motion "target" next path corner "color" constantLight color "light" constantLight radius
On the path corner: speed departure speed from that corner rotate angle change for X Y Z to next corner duration duration for angle change (overrides speed)
Parameters
[in,out] self
Definition at line 3580 of file g_mover.c.
void SP_info_limbo_camera (gentity_t * self)
SP_info_limbo_camera.
Parameters
[in,out] self
Definition at line 3272 of file g_mover.c.
void SP_info_train_spline_main (gentity_t * self)
SP_info_train_spline_main.
QUAKED info_train_spline_main (0 1 0) (-8 -8 -8) (8 8 8) Train spline.
Parameters
[in] self
Definition at line 3158 of file g_mover.c.
void SP_path_corner (gentity_t * self)
SP_path_corner.
QUAKED path_corner (.5 .3 0) (-8 -8 -8) (8 8 8) STOP END REVERSE Train path corners. Target: next path corner and other targets to fire "speed" speed to move to the next corner "wait" seconds to wait before behining move to next corner
"count2" used only in conjunction with the truck_cam to control playing of gear changes
Parameters
[in,out] self
Definition at line 3106 of file g_mover.c.
void SP_path_corner_2 (gentity_t * self)
QUAKED path_corner_2 (.5 .3 0) (-8 -8 -8) (8 8 8) STOP END REVERSE Train path corners. THIS VERSION WILL NOT CONTRIBUTE TOWARDS INGAME ENTITY COUNT "targetname" The script uses this name to identify the corner.
Parameters
[in,out] self
Definition at line 3129 of file g_mover.c.
void SP_target_effect (gentity_t * ent)
SP_target_effect.
QUAKED target_effect (0 .5 .8) (-6 -6 -6) (6 6 6) fire explode smoke rubble gore lowgrav debris "mass" defaults to 15. This determines how much debris is emitted when it explodes. (number of pieces) "dmg" defaults to 0. damage radius blast when triggered "type" - if 'rubble' is specified, this is the model type ("glass", "wood", "metal", "gibs", "brick", "rock", "fabric") default is "wood"
Parameters
[in,out] ent
Todo:
: test this
Definition at line 4232 of file g_mover.c.
void SP_target_explosion (gentity_t * ent)
SP_target_explosion.
Parameters
[in,out] ent
Todo:
: test this
Definition at line 4539 of file g_mover.c.
void SpawnPlatTrigger (gentity_t * ent)
Spawn a trigger in the middle of the plat's low position Elevator cars require that the trigger extend through the entire low position, not just sit on top of it.
Parameters
[in] ent
Definition at line 2744 of file g_mover.c.
Referenced by SP_func_plat().
void Static_Pain (gentity_t * ent, gentity_t * attacker, int damage, vec3_t point)
Static_Pain.
Parameters
[in] ent
[in] attacker
damage - unused
point - unused
Definition at line 3650 of file g_mover.c.
Referenced by SP_func_static().
void target_effect (gentity_t * self, gentity_t * other, gentity_t * activator)
target_effect
=============================================================================== EFFECTS
Note
I'm keeping all this stuff in here just to avoid collisions with Raf right now in g_misc or g_props
Will move.
Parameters
[in] self
[in] other
activator - unused
Definition at line 4190 of file g_mover.c.
Referenced by SP_target_effect().
void target_explosion_use (gentity_t * self, gentity_t * other, gentity_t * attacker)
QUAKED target_explosion (0 .5 .8) (-32 -32 -32) (32 32 32) LOWGRAV "type" - type of debris ("glass", "wood", "metal", "gibs", "brick", "rock", "fabric") default is "wood"
Parameters
[in] self
other - unused
[in] attacker
Definition at line 4514 of file g_mover.c.
Referenced by SP_target_explosion().
void Think_BeginMoving (gentity_t * ent)
The wait time at a corner has completed, so start moving again.
Parameters
[out] ent
Definition at line 2952 of file g_mover.c.
Referenced by Reached_Train().
void Think_BeginMoving_rotating (gentity_t * ent)
The wait time at a corner has completed, so start moving again.
Parameters
[out] ent
Definition at line 3363 of file g_mover.c.
Referenced by Reached_Train_rotating().
void Think_MatchTeam (gentity_t * ent)
Think_MatchTeam.
Parameters
[in] ent
Definition at line 2204 of file g_mover.c.
Referenced by finishSpawningKeyedMover().
void Think_SetupTrainTargets (gentity_t * ent)
Link all the corners together.
Parameters
[in,out] ent
Definition at line 3033 of file g_mover.c.
Referenced by SP_func_train().
void Think_SetupTrainTargets_rotating (gentity_t * ent)
Link all the corners together.
Parameters
[in,out] ent
Definition at line 3502 of file g_mover.c.
Referenced by SP_func_train_rotating().
void Think_SpawnNewDoorTrigger (gentity_t * ent)
All of the parts of a door have been spawned, so create a trigger that encloses all of them.
Parameters
ent
Definition at line 2155 of file g_mover.c.
Referenced by finishSpawningKeyedMover().
void Touch_Button (gentity_t * ent, gentity_t * other, trace_t * trace)
Touch_Button.
Parameters
[in] ent
[in] other
trace - unused
Definition at line 2855 of file g_mover.c.
Referenced by SP_func_button().
void Touch_DoorTrigger (gentity_t * ent, gentity_t * other, trace_t * trace)
Touch_DoorTrigger.
Parameters
[in] ent
[in] other
[in] trace
Definition at line 2133 of file g_mover.c.
Referenced by Think_SpawnNewDoorTrigger().
static void Touch_DoorTriggerSpectator (gentity_t * ent, gentity_t * other, trace_t * trace) static
Touch_DoorTriggerSpectator.
Parameters
[in] ent
[in] other
trace - unused
Definition at line 2045 of file g_mover.c.
Referenced by Touch_DoorTrigger().
void Touch_Plat (gentity_t * ent, gentity_t * other, trace_t * trace)
Don't allow decent if a living player is on it.
Parameters
[in,out] ent
[in] other
trace - unused
Definition at line 2705 of file g_mover.c.
Referenced by SP_func_plat().
void Touch_PlatCenterTrigger (gentity_t * ent, gentity_t * other, trace_t * trace)
If the plat is at the bottom position, start it going up.
Parameters
[in,out] ent
[in] other
trace - unused
Definition at line 2725 of file g_mover.c.
Referenced by SpawnPlatTrigger().
void Use_BinaryMover (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_BinaryMover.
Parameters
[in,out] ent
[in] other
[in] activator
Todo:
: THIS IS STILL A HACK)
Todo:
: check out this line (see blocked mover in Use_TrinaryMover)
Definition at line 1594 of file g_mover.c.
Referenced by Do_Activate_f(), flippy_table_use(), G_TryDoor(), InitMover(), InitMoverRotate(), Touch_Button(), Touch_DoorTrigger(), and Touch_PlatCenterTrigger().
void Use_Func_Rotate (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Func_Rotate.
QUAKED func_rotating (0 .5 .8) ? START_ON STARTINVIS X_AXIS Y_AXIS You need to have an origin brush as part of this entity. The center of that brush will be the point around which it is rotated. It will rotate around the Z axis by default. You can check either the X_AXIS or Y_AXIS box to change that.
"model2" .md3 model to also draw "speed" determines how fast it moves; default value is 100. "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 3833 of file g_mover.c.
Referenced by InitMover().
void use_invisible_user (gentity_t * ent, gentity_t * other, gentity_t * activator)
use_invisible_user
Parameters
[in,out] ent
[in] other
activator
Definition at line 4843 of file g_mover.c.
Referenced by SP_func_invisible_user().
void Use_Static (gentity_t * ent, gentity_t * other, gentity_t * activator)
Toggle hide or show (including collisions) this entity.
Parameters
[in] ent
other - unused
activator - unused
Definition at line 3631 of file g_mover.c.
Referenced by SP_func_static().
void Use_TrinaryMover (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_TrinaryMover.
Parameters
[in,out] ent
[in] other
[in] activator
Definition at line 1455 of file g_mover.c.
Referenced by InitMover().
Variable Documentation
g_constructible_stats_t g_constructible_classes[NUM_CONSTRUCTIBLE_CLASSES]
Initial value:
=
{
    { .5f,  5,    5,    350, 1, 2500 },
    { 1.f,  7.5f, 7.5f, 100, 2, 5000 },
    { 1.5f, 10,   10,   100, 3, 7500 }
}
Definition at line 5642 of file g_mover.c.
Referenced by G_ScriptAction_ConstructibleClass(), and SP_func_explosive().
const char* hintStrings[HINT_NUM_HINTS]
Definition at line 41 of file g_mover.c.
Referenced by SP_func_explosive(), and SP_func_invisible_user().
pushed_t pushed[MAX_GENTITIES *PUSH_STACK_DEPTH]
Definition at line 121 of file g_mover.c.
Referenced by G_MoverPush(), and G_MoverTeam().
pushed_t * pushed_p
Definition at line 121 of file g_mover.c.
int pushedStackDepth = 0
Definition at line 111 of file g_mover.c.
Referenced by G_MoverPush(), and G_TryPushingEntity().