ET: Legacy: src/game/g_missile.c File Reference
g_missile.c File Reference
#include "g_local.h"
#include "g_etbot_interface.h"
Macros
#define LANDMINE_TRIGGER_DIST 64.0f
Functions
void G_RealExplodedMissile (gentity_t *ent, vec3_t dir, gentity_t *other)
G_RealExplodedMissile.
void G_BounceMissile (gentity_t *ent, trace_t *trace)
G_BounceMissile.
qboolean G_MissileImpact (gentity_t *ent, trace_t *trace, int impactDamage)
G_MissileImpact.
void G_ExplodeMissile (gentity_t *ent)
Explode a missile without an impact.
void Landmine_Check_Ground (gentity_t *self)
Landmine_Check_Ground.
void G_RunMissile (gentity_t *ent)
G_RunMissile.
void G_PredictBounceMissile (gentity_t *ent, trajectory_t *pos, trace_t *trace, int time)
G_PredictBounceMissile.
int G_PredictMissile (gentity_t *ent, int duration, vec3_t endPos, qboolean allowBounce)
G_PredictMissile.
void G_BurnTarget (gentity_t *self, gentity_t *body, qboolean directhit)
G_BurnTarget.
void G_FlameDamage (gentity_t *self, gentity_t *ignoreent)
G_FlameDamage.
void G_RunFlamechunk (gentity_t *ent)
G_RunFlamechunk.
gentity_t * fire_flamechunk (gentity_t *self, vec3_t start, vec3_t dir)
fire_flamechunk
void DynaSink (gentity_t *self)
DynaSink.
void DynaFree (gentity_t *self)
DynaFree.
void G_FadeItems (gentity_t *ent, int modType)
Remove any items that the player should no longer have, on disconnect/class change etc changed to just set the parent to NULL.
int G_CountTeamLandmines (team_t team)
G_CountTeamLandmines.
qboolean G_SweepForLandmines (vec3_t origin, float radius, int team)
G_SweepForLandmines.
gentity_t * G_FindSatchel (gentity_t *ent)
G_FindSatchel.
void G_ExplodeMines (gentity_t *ent)
G_ExplodeMines.
qboolean G_ExplodeSatchels (gentity_t *ent)
G_ExplodeSatchels.
void G_FreeSatchel (gentity_t *ent)
G_FreeSatchel.
void LandminePostThink (gentity_t *self)
LandminePostThink.
void LandMineTrigger (gentity_t *self)
LandMineTrigger.
void LandMinePostTrigger (gentity_t *self)
LandMinePostTrigger.
qboolean sEntWillTriggerMine (gentity_t *ent, gentity_t *mine)
Check if an entity will set off a landmine.
void G_LandmineThink (gentity_t *self)
Landmine waits for 2 seconds then primes, which sets think to checking for "enemies".
void G_LandminePrime (gentity_t *self)
G_LandminePrime.
qboolean G_LandmineSnapshotCallback (int entityNum, int clientNum)
G_LandmineSnapshotCallback.
gentity_t * fire_missile (gentity_t *self, vec3_t start, vec3_t dir, int weapon)
fire_missile
gentity_t * fire_flamebarrel (gentity_t *self, vec3_t start, vec3_t dir)
fire_flamebarrel
Macro Definition Documentation
#define LANDMINE_TRIGGER_DIST 64.0f
Definition at line 1436 of file g_missile.c.
Referenced by G_LandmineThink(), LandminePostThink(), and sEntWillTriggerMine().
Function Documentation
void DynaFree (gentity_t * self)
DynaFree.
Parameters
[in,out] self
Definition at line 1095 of file g_missile.c.
void DynaSink (gentity_t * self)
DynaSink.
Parameters
[in,out] self
Definition at line 1075 of file g_missile.c.
gentity_t* fire_flamebarrel (gentity_t * self, vec3_t start, vec3_t dir)
fire_flamebarrel
Parameters
[in] self
[in] start
[in] dir
Returns
Definition at line 1708 of file g_missile.c.
Referenced by Props_Barrel_Die().
gentity_t* fire_flamechunk (gentity_t * self, vec3_t start, vec3_t dir)
fire_flamechunk
Parameters
[in,out] self
[in] start
[in] dir
Returns
Definition at line 1044 of file g_missile.c.
Referenced by props_flamethrower_think(), and Weapon_FlamethrowerFire().
gentity_t* fire_missile (gentity_t * self, vec3_t start, vec3_t dir, int weapon)
fire_missile
Parameters
[in] self
[in] start
[in] dir
[in] weapon
Returns
Note
IMPORTANT!!! : This accepts a /non-normalized/ direction vector to allow specification of how hard it's thrown. Please scale the vector before calling.
Definition at line 1670 of file g_missile.c.
Referenced by artillerySpotterThink(), G_AirStrikeThink(), G_ArtilleryExplode(), player_die(), Use_Shooter(), weapon_antitank_fire(), weapon_gpg40_fire(), weapon_grenadelauncher_fire(), and weapon_mortar_fire().
void G_BounceMissile (gentity_t * ent, trace_t * trace)
G_BounceMissile.
Parameters
[in,out] ent
[in] trace
Todo:
: this condition is always true due to || 1 ... why ?
Definition at line 205 of file g_missile.c.
Referenced by G_MissileImpact().
void G_BurnTarget (gentity_t * self, gentity_t * body, qboolean directhit)
G_BurnTarget.
Parameters
self
[in,out] body
[in] directhit
Definition at line 766 of file g_missile.c.
Referenced by G_FlameDamage(), and G_RunFlamechunk().
int G_CountTeamLandmines (team_t team)
G_CountTeamLandmines.
Parameters
[in] team
Returns
Definition at line 1196 of file g_missile.c.
Referenced by G_RunFrame(), ETInterface::InterfaceSendMessage(), and Weapon_Engineer().
void G_ExplodeMines (gentity_t * ent)
G_ExplodeMines.
Removes any weapon objects lying around in the map when they disconnect/switch team
Parameters
[in] ent
Definition at line 1321 of file g_missile.c.
Referenced by ClientDisconnect(), G_shuffleTeamsXP(), and SetTeam().
void G_ExplodeMissile (gentity_t * ent)
Explode a missile without an impact.
Parameters
[in,out] ent
Definition at line 400 of file g_missile.c.
Referenced by DynaFree(), fire_flamebarrel(), G_BounceMissile(), G_Damage(), G_ExplodeSatchels(), G_RunMissile(), LandMinePostTrigger(), propExplosion(), SP_Dust(), weapon_callAirStrike(), weapon_checkAirStrike(), weapon_checkAirStrikeThink(), and Weapon_Engineer().
qboolean G_ExplodeSatchels (gentity_t * ent)
G_ExplodeSatchels.
Parameters
[in] ent
Returns
Definition at line 1331 of file g_missile.c.
Referenced by weapon_satcheldet_fire().
void G_FadeItems (gentity_t * ent, int modType)
Remove any items that the player should no longer have, on disconnect/class change etc changed to just set the parent to NULL.
Parameters
[in] ent
[in] modType
Definition at line 1149 of file g_missile.c.
Referenced by ClientDisconnect(), G_ExplodeMines(), G_shuffleTeamsXP(), player_die(), and SetTeam().
gentity_t* G_FindSatchel (gentity_t * ent)
G_FindSatchel.
Parameters
[in] ent
Returns
Definition at line 1280 of file g_missile.c.
void G_FlameDamage (gentity_t * self, gentity_t * ignoreent)
G_FlameDamage.
Parameters
[in] self
[in] ignoreent
Definition at line 890 of file g_missile.c.
Referenced by G_RunFlamechunk().
void G_FreeSatchel (gentity_t * ent)
G_FreeSatchel.
Parameters
[in,out] ent
Definition at line 1377 of file g_missile.c.
void G_LandminePrime (gentity_t * self)
G_LandminePrime.
Parameters
[out] self
Definition at line 1586 of file g_missile.c.
Referenced by EntsThatRadiusCanDamage(), and Weapon_Engineer().
qboolean G_LandmineSnapshotCallback (int entityNum, int clientNum)
G_LandmineSnapshotCallback.
Parameters
[in] entityNum
[in] clientNum
Returns
Definition at line 1598 of file g_missile.c.
Referenced by G_SnapshotCallback().
void G_LandmineThink (gentity_t * self)
Landmine waits for 2 seconds then primes, which sets think to checking for "enemies".
Parameters
[in,out] self
Note
107 11 20 0 0 0 0 fire gren
Definition at line 1469 of file g_missile.c.
Referenced by G_LandminePrime(), landmine_setup(), and SP_misc_constructiblemarker().
qboolean G_MissileImpact (gentity_t * ent, trace_t * trace, int impactDamage)
G_MissileImpact.
Parameters
[in] ent
[in] trace
[in] impactDamage is how much damage the impact will do to func_explosives
Returns
true if missile exploded otherwise false
Definition at line 319 of file g_missile.c.
Referenced by G_RunMissile().
void G_PredictBounceMissile (gentity_t * ent, trajectory_t * pos, trace_t * trace, int time)
G_PredictBounceMissile.
Parameters
[in] ent
[in,out] pos
[in] trace
[in] time
Definition at line 635 of file g_missile.c.
Referenced by G_PredictMissile().
int G_PredictMissile (gentity_t * ent, int duration, vec3_t endPos, qboolean allowBounce)
G_PredictMissile.
Parameters
[in,out] ent is the character that is checking to see what the missile is going to do
[in] duration
[out] endPos
[in] allowBounce
Returns
qfalse if the missile won't explode, otherwise it'll return the time is it expected to explode
Definition at line 681 of file g_missile.c.
void G_RealExplodedMissile (gentity_t * ent, vec3_t dir, gentity_t * other)
G_RealExplodedMissile.
Parameters
[in,out] ent
[in] dir
[in] hit
Todo:
: is it cheaper in bandwidth to just remove this ent and create a new
Definition at line 47 of file g_missile.c.
Referenced by G_ExplodeMissile(), and G_MissileImpact().
void G_RunFlamechunk (gentity_t * ent)
G_RunFlamechunk.
Parameters
[in,out] ent
Definition at line 924 of file g_missile.c.
Referenced by G_RunEntity().
void G_RunMissile (gentity_t * ent)
G_RunMissile.
Parameters
[in,out] ent
Definition at line 438 of file g_missile.c.
Referenced by G_RunEntity().
qboolean G_SweepForLandmines (vec3_t origin, float radius, int team)
G_SweepForLandmines.
Parameters
[in] origin
[in] radius
[in] team
Returns
Definition at line 1235 of file g_missile.c.
Referenced by ClientThink_real().
void Landmine_Check_Ground (gentity_t * self)
Landmine_Check_Ground.
Parameters
[in,out] self
Definition at line 412 of file g_missile.c.
Referenced by G_RunMissile().
void LandminePostThink (gentity_t * self)
LandminePostThink.
Parameters
[in,out] self
Definition at line 1540 of file g_missile.c.
Referenced by G_FreeSatchel(), and LandMineTrigger().
void LandMinePostTrigger (gentity_t * self)
LandMinePostTrigger.
Parameters
[out] self
Definition at line 1430 of file g_missile.c.
Referenced by LandminePostThink().
void LandMineTrigger (gentity_t * self)
LandMineTrigger.
Parameters
[in,out] self
Definition at line 1414 of file g_missile.c.
Referenced by G_LandmineThink(), G_MoverPush(), and G_TryPushingEntity().
qboolean sEntWillTriggerMine (gentity_t * ent, gentity_t * mine)
Check if an entity will set off a landmine.
Parameters
[in] ent
[in] mine
Returns
Definition at line 1444 of file g_missile.c.
Referenced by G_LandmineThink(), and LandminePostThink().