ET: Legacy: src/game/g_props.c File Reference
g_props.c File Reference
#include "g_local.h"
Macros
#define LOCKER_ANIM_USEEND 5
#define LOCKER_ANIM_DEATHSTART 6
#define LOCKER_ANIM_DEATHEND 11
#define MAX_LOCKER_DEBRIS 5
Functions
void DropToFloorG (gentity_t *ent)
DropToFloorG.
void DropToFloor (gentity_t *ent)
DropToFloor.
void moveit (gentity_t *ent, float yaw, float dist)
moveit
void touch_props_box_32 (gentity_t *self, gentity_t *other, trace_t *trace)
touch_props_box_32
void SP_props_box_32 (gentity_t *self)
SP_props_box_32 QUAKED props_box_32 (1 0 0) (-16 -16 -16) (16 16 16)
void touch_props_box_48 (gentity_t *self, gentity_t *other, trace_t *trace)
touch_props_box_48
void SP_props_box_48 (gentity_t *self)
SP_props_box_48 QUAKED props_box_48 (1 0 0) (-24 -24 -24) (24 24 24)
void touch_props_box_64 (gentity_t *self, gentity_t *other, trace_t *trace)
touch_props_box_64
void SP_props_box_64 (gentity_t *self)
SP_props_box_64 QUAKED props_box_64 (1 0 0) (-32 -32 -32) (32 32 32)
void Psmoke_think (gentity_t *ent)
Psmoke_think.
void prop_smoke (gentity_t *ent)
prop_smoke
void PGUNsparks_use (gentity_t *ent, gentity_t *self, gentity_t *activator)
PGUNsparks_use.
void Psparks_think (gentity_t *ent)
Psparks_think.
void sparks_angles_think (gentity_t *ent)
sparks_angles_think
void SP_props_sparks (gentity_t *ent)
SP_props_sparks.
void SP_props_gunsparks (gentity_t *ent)
SP_props_gunsparks.
void smokedust_use (gentity_t *ent, gentity_t *self, gentity_t *activator)
QUAKED props_smokedust (.8 .46 .16) (-8 -8 -8) (8 8 8) health = how many pieces 16 is default.
void SP_SmokeDust (gentity_t *ent)
SP_SmokeDust.
void dust_use (gentity_t *ent, gentity_t *self, gentity_t *activator)
dust_use
void dust_angles_think (gentity_t *ent)
dust_angles_think
void SP_Dust (gentity_t *ent)
SP_Dust.
void G_ExplodeMissile (gentity_t *ent)
Explode a missile without an impact.
void propExplosion (gentity_t *ent)
propExplosion
void InitProp (gentity_t *ent)
InitProp.
void props_bench_think (gentity_t *ent)
props_bench_think
void props_bench_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_bench_die
void SP_Props_Bench (gentity_t *ent)
SP_Props_Bench.
void props_radio_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_radio_die
void SP_Props_Radio (gentity_t *ent)
SP_Props_Radio.
void props_radio_dieSEVEN (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_radio_dieSEVEN
void SP_Props_RadioSEVEN (gentity_t *ent)
SP_Props_RadioSEVEN.
void locker_tall_think (gentity_t *ent)
locker_tall_think
void props_locker_tall_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_locker_tall_die
void SP_Props_Locker_Tall (gentity_t *ent)
SP_Props_Locker_Tall.
void Props_Chair_Think (gentity_t *self)
Props_Chair_Think.
void Props_Chair_Touch (gentity_t *self, gentity_t *other, trace_t *trace)
Props_Chair_Touch.
void Props_Chair_Die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
Props_Chair_Die.
void Just_Got_Thrown (gentity_t *self)
Just_Got_Thrown.
void Props_TurnLightsOff (gentity_t *self)
Props_TurnLightsOff.
void Props_Activated (gentity_t *self)
Props_Activated.
void Prop_Check_Ground (gentity_t *self)
Prop_Check_Ground.
qboolean Prop_Touch (gentity_t *self, gentity_t *other, vec3_t v)
Prop_Touch.
void Props_Chair_Animate (gentity_t *ent)
Props_Chair_Animate.
void Spawn_Shard (gentity_t *ent, gentity_t *inflictor, float quantity, int type)
Spawn_Shard.
void Prop_Break_Sound (gentity_t *ent)
This should work for all fx types now.
void Props_Chair_Skyboxtouch (gentity_t *ent)
Props_Chair_Skyboxtouch.
void SP_Props_Chair (gentity_t *ent)
SP_Props_Chair.
void SP_Props_ChairHiback (gentity_t *ent)
SP_Props_ChairHiback.
void SP_Props_ChairSide (gentity_t *ent)
SP_Props_ChairSide.
void SP_Props_ChateauChair (gentity_t *ent)
SP_Props_ChateauChair.
void SP_Props_ChairChat (gentity_t *ent)
SP_Props_ChairChat.
void SP_Props_ChairChatArm (gentity_t *ent)
SP_Props_ChairChatArm.
void Use_DamageInflictor (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_DamageInflictor.
void SP_Props_DamageInflictor (gentity_t *ent)
SP_Props_DamageInflictor.
void Use_Props_Shard_Generator (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Props_Shard_Generator.
void SP_props_shard_generator (gentity_t *ent)
SP_props_shard_generator.
void SP_Props_Desklamp (gentity_t *ent)
SP_Props_Desklamp.
void Props_Barrel_Touch (gentity_t *self, gentity_t *other, trace_t *trace)
Props_Barrel_Touch.
void Props_Barrel_Animate (gentity_t *ent)
Props_Barrel_Animate.
void barrel_smoke (gentity_t *ent)
barrel_smoke
void smoker_think (gentity_t *ent)
smoker_think
void SP_OilSlick (gentity_t *ent)
SP_OilSlick.
void OilParticles_think (gentity_t *ent)
OilParticles_think.
qboolean validOilSlickSpawnPoint (vec3_t point, gentity_t *ent)
validOilSlickSpawnPoint
void SP_OilParticles (gentity_t *ent)
SP_OilParticles.
void Props_Barrel_Pain (gentity_t *ent, gentity_t *attacker, int damage, vec3_t point)
Props_Barrel_Pain.
void OilSlick_remove_think (gentity_t *ent)
OilSlick_remove_think.
void OilSlick_remove (gentity_t *ent)
OilSlick_remove.
void Props_Barrel_Die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
Props_Barrel_Die.
void Props_Barrel_Think (gentity_t *self)
Props_Barrel_Think.
void SP_Props_Flamebarrel (gentity_t *ent)
SP_Props_Flamebarrel.
void touch_crate_64 (gentity_t *self, gentity_t *other, trace_t *trace)
touch_crate_64
void crate_animate (gentity_t *ent)
crate_animate
void crate_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
crate_die
void SP_crate_64 (gentity_t *self)
SP_crate_64.
void SP_crate_32 (gentity_t *self)
SP_crate_32.
void props_crate32x64_think (gentity_t *ent)
props_crate32x64_think
void props_crate32x64_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_crate32x64_die
void SP_Props_Crate32x64 (gentity_t *ent)
SP_Props_Crate32x64.
void flippy_table_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
flippy_table_use
void flippy_table_animate (gentity_t *ent)
flippy_table_animate
void props_flippy_table_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_flippy_table_die
void props_flippy_blocked (gentity_t *ent, gentity_t *other)
props_flippy_blocked
void SP_Props_Flipping_Table (gentity_t *ent)
SP_Props_Flipping_Table.
void props_58x112tablew_think (gentity_t *ent)
props_58x112tablew_think
void props_58x112tablew_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_58x112tablew_die
void SP_Props_58x112tablew (gentity_t *ent)
SP_Props_58x112tablew.
void props_castlebed_touch (gentity_t *ent, gentity_t *other, trace_t *trace)
props_castlebed_touch
void props_castlebed_animate (gentity_t *ent)
props_castlebed_animate
void props_castlebed_die (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_castlebed_die
void SP_props_castlebed (gentity_t *ent)
SP_props_castlebed.
void props_snowGenerator_think (gentity_t *ent)
props_snowGenerator_think
void props_snowGenerator_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
props_snowGenerator_use
void SP_props_snowGenerator (gentity_t *ent)
SP_props_snowGenerator.
void props_decoration_animate (gentity_t *ent)
props_decoration_animate
void props_decoration_death (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_decoration_death
void Use_props_decoration (gentity_t *ent, gentity_t *self, gentity_t *activator)
Use_props_decoration.
void props_touch (gentity_t *self, gentity_t *other, trace_t *trace)
props_touch
void SP_props_decoration (gentity_t *ent)
SP_props_decoration.
void SP_props_decorBRUSH (gentity_t *self)
SP_props_decorBRUSH.
void SP_props_decor_Scale (gentity_t *ent)
SP_props_decor_Scale.
void SP_skyportal (gentity_t *ent)
SP_skyportal.
void props_statue_blocked (gentity_t *ent)
props_statue_blocked
void props_statue_animate (gentity_t *ent)
props_statue_animate
void props_statue_death (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_statue_death
void props_statue_touch (gentity_t *self, gentity_t *other, trace_t *trace)
props_statue_touch
void SP_props_statue (gentity_t *ent)
SP_props_statue.
void SP_props_statueBRUSH (gentity_t *self)
SP_props_statueBRUSH.
void init_locker (gentity_t *ent)
init_locker
void props_locker_death (gentity_t *ent, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
props_locker_death
void Spawn_Junk (gentity_t *ent)
Spawn_Junk.
void props_locker_endrattle (gentity_t *ent)
props_locker_endrattle
void props_locker_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
props_locker_use
void props_locker_pain (gentity_t *ent, gentity_t *attacker, int damage, vec3_t point)
props_locker_pain
void props_locker_spawn_item (gentity_t *ent)
props_locker_spawn_item
void props_locker_mass (gentity_t *ent)
props_locker_mass
void SP_props_footlocker (gentity_t *self)
SP_props_footlocker.
void props_flamethrower_think (gentity_t *ent)
props_flamethrower_think
void props_flamethrower_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
props_flamethrower_use
void props_flamethrower_init (gentity_t *ent)
props_flamethrower_init
void SP_props_flamethrower (gentity_t *ent)
SP_props_flamethrower.
Variables
int locker_debris_model [MAX_LOCKER_DEBRIS]
Macro Definition Documentation
#define LOCKER_ANIM_DEATHEND 11
Definition at line 4245 of file g_props.c.
Referenced by init_locker().
#define LOCKER_ANIM_DEATHSTART 6
Definition at line 4244 of file g_props.c.
#define LOCKER_ANIM_USEEND 5
Definition at line 4243 of file g_props.c.
#define MAX_LOCKER_DEBRIS 5
Definition at line 4251 of file g_props.c.
Function Documentation
void barrel_smoke (gentity_t * ent)
barrel_smoke
Parameters
[in] ent
Definition at line 2241 of file g_props.c.
Referenced by smoker_think().
void crate_animate (gentity_t * ent)
crate_animate
Parameters
[in,out] ent
Definition at line 2650 of file g_props.c.
Referenced by crate_die().
void crate_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
crate_die
Parameters
[in,out] ent
[in] inflictor
attacker - unused
damage - unused
mod - unused
Definition at line 2674 of file g_props.c.
Referenced by SP_crate_32(), and SP_crate_64().
void DropToFloor (gentity_t * ent)
DropToFloor.
Parameters
[in,out] ent
Definition at line 63 of file g_props.c.
Referenced by SP_crate_32(), SP_crate_64(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_team_CTF_bluespawn(), SP_team_CTF_redspawn(), and Use_Team_Spawnpoint().
void DropToFloorG (gentity_t * ent)
DropToFloorG.
Parameters
[in,out] ent
Definition at line 41 of file g_props.c.
Referenced by DropToFloor().
void dust_angles_think (gentity_t * ent)
dust_angles_think
Parameters
[in] ent
Definition at line 598 of file g_props.c.
Referenced by SP_Dust().
void dust_use (gentity_t * ent, gentity_t * self, gentity_t * activator)
dust_use
QUAKED props_dust (.7 .3 .16) (-8 -8 -8) (8 8 8) WHITE you should give this ent a target use a not null or you could set its angles in the editor
Parameters
[in] ent
self - unused
activator - unused
Definition at line 564 of file g_props.c.
Referenced by SP_Dust().
void flippy_table_animate (gentity_t * ent)
flippy_table_animate
Parameters
ent
Todo:
FIXME: remove ?
Definition at line 2969 of file g_props.c.
Referenced by props_flippy_table_die().
void flippy_table_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
flippy_table_use
QUAKED props_flippy_table (.8 .6 .2) ? - - X_AXIS Y_AXIS LEADER this entity will need a leader and an origin brush !!!!!!!!!!!!!! just a reminder to put the origin brush in the proper location for the leader and the slave so that the table will flip over correctly.
Parameters
[in] ent
[in] other
activator - unused
Definition at line 2905 of file g_props.c.
Referenced by SP_Props_Flipping_Table().
void G_ExplodeMissile (gentity_t * ent)
Explode a missile without an impact.
Parameters
[in,out] ent
Definition at line 400 of file g_missile.c.
Referenced by DynaFree(), fire_flamebarrel(), G_BounceMissile(), G_ExplodeSatchels(), G_RunMissile(), LandMinePostTrigger(), propExplosion(), and SP_Dust().
void init_locker (gentity_t * ent)
init_locker
Parameters
[out] ent
Todo:
: change from 'trap' to something else. 'trap' is a misnomer. it's actually used for other stuff too
Definition at line 4335 of file g_props.c.
Referenced by SP_props_footlocker().
void InitProp (gentity_t * ent)
InitProp.
Parameters
[in,out] ent
Todo:
: the following models are missing in genuine ET pk3s - relics ?
Definition at line 716 of file g_props.c.
Referenced by SP_Props_58x112tablew(), SP_Props_Bench(), SP_props_castlebed(), SP_Props_Crate32x64(), SP_Props_Locker_Tall(), SP_Props_Radio(), and SP_Props_RadioSEVEN().
void Just_Got_Thrown (gentity_t * self)
Just_Got_Thrown.
Parameters
[in,out] self
Definition at line 1137 of file g_props.c.
Referenced by Props_Activated(), and Props_Chair_Think().
void locker_tall_think (gentity_t * ent)
locker_tall_think
Parameters
[in,out] ent
Definition at line 1000 of file g_props.c.
Referenced by props_locker_tall_die().
void moveit (gentity_t * ent, float yaw, float dist)
moveit
Parameters
[in,out] ent
[in] yaw
[in] dist
Definition at line 95 of file g_props.c.
Referenced by Props_Barrel_Animate(), Props_Chair_Animate(), touch_crate_64(), touch_props_box_32(), touch_props_box_48(), and touch_props_box_64().
void OilParticles_think (gentity_t * ent)
OilParticles_think.
Parameters
[in,out] ent
Note
Unused ? See SP_OilParticles
Definition at line 2301 of file g_props.c.
void OilSlick_remove (gentity_t * ent)
OilSlick_remove.
Parameters
[in] ent
Definition at line 2470 of file g_props.c.
Referenced by Props_Barrel_Die().
void OilSlick_remove_think (gentity_t * ent)
OilSlick_remove_think.
Parameters
[in] ent
Definition at line 2457 of file g_props.c.
Referenced by OilSlick_remove().
void PGUNsparks_use (gentity_t * ent, gentity_t * self, gentity_t * activator)
PGUNsparks_use.
QUAKED props_sparks (.8 .46 .16) (-8 -8 -8) (8 8 8) ELECTRIC the default direction is strait up use info_no_null for alt direction
delay = how long till next spark effect wait = life of the spark with some random variance default 1.0 sec health = random number of sparks upto specified amount default 8
start_size default 8 along the x end_size default 8 along the y by changing the size will change the spawn origin of the individual spark ei 16 x 8 or 24 x 32 would cause the sparks to spawn that many units from the origin
speed controls how quickly the sparks will travel default is 2
Parameters
[in] ent
self - unused
activator - unused
Definition at line 338 of file g_props.c.
Referenced by sparks_angles_think().
void Prop_Break_Sound (gentity_t * ent)
This should work for all fx types now.
Parameters
ent
Definition at line 1709 of file g_props.c.
Referenced by G_RunItemProp(), Props_Barrel_Die(), props_castlebed_die(), Props_Chair_Die(), and props_radio_dieSEVEN().
void Prop_Check_Ground (gentity_t * self)
Prop_Check_Ground.
Parameters
[in,out] self
Definition at line 1498 of file g_props.c.
Referenced by Props_Activated(), Props_Chair_Think(), and Props_Chair_Touch().
void prop_smoke (gentity_t * ent)
prop_smoke
Parameters
[in] ent
Note
Unused
Definition at line 305 of file g_props.c.
qboolean Prop_Touch (gentity_t * self, gentity_t * other, vec3_t v)
Prop_Touch.
Parameters
[in,out] self
[in] other
[in] v
Returns
Definition at line 1445 of file g_props.c.
Referenced by Props_Chair_Touch().
void propExplosion (gentity_t * ent)
propExplosion
Parameters
[in] ent
Definition at line 681 of file g_props.c.
Referenced by alarmbox_die(), Props_Barrel_Die(), props_radio_die(), and props_radio_dieSEVEN().
void props_58x112tablew_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_58x112tablew_die
Parameters
[out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 3170 of file g_props.c.
Referenced by SP_Props_58x112tablew().
void props_58x112tablew_think (gentity_t * ent)
props_58x112tablew_think
QUAKED props_58x112tablew (.8 .6 .2) ? dimensions are 58 x 112 x 32 (x,y,z)
requires an origin brush
breakable NOT pushable
brushmodel only
health = default = 10 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] ent
Definition at line 3145 of file g_props.c.
Referenced by props_58x112tablew_die().
void Props_Activated (gentity_t * self)
Props_Activated.
Parameters
[in,out] self
Definition at line 1215 of file g_props.c.
Referenced by Props_Chair_Think().
void Props_Barrel_Animate (gentity_t * ent)
Props_Barrel_Animate.
Parameters
[in,out] ent
Todo:
: Duplicate branch if/else
Definition at line 2197 of file g_props.c.
Referenced by Props_Barrel_Die().
void Props_Barrel_Die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
Props_Barrel_Die.
Parameters
[in,out] ent
[in] inflictor
attacker
[in] damage
mod
Definition at line 2491 of file g_props.c.
Referenced by SP_Props_Flamebarrel().
void Props_Barrel_Pain (gentity_t * ent, gentity_t * attacker, int damage, vec3_t point)
Props_Barrel_Pain.
Parameters
[in,out] ent
attacker - unused
damage - unused
point - unused
Definition at line 2432 of file g_props.c.
Referenced by SP_Props_Flamebarrel().
void Props_Barrel_Think (gentity_t * self)
Props_Barrel_Think.
Parameters
[in,out] self
Definition at line 2550 of file g_props.c.
Referenced by SP_Props_Flamebarrel().
void Props_Barrel_Touch (gentity_t * self, gentity_t * other, trace_t * trace)
Props_Barrel_Touch.
QUAKED props_flamebarrel (.8 .6 .2) (-13 -13 0) (13 13 40) SMOKING NOLID OIL - angle will determine which way the lid will fly off when it explodes
when selecting the OIL spawnflag you have the option of giving it a target this will ensure that the oil sprite will show up where you want it (be sure to put it on the floor) the default is in the middle of the barrel on the floor
Parameters
self - unused
other - unused
trace - unused
Note
Barrels cant move
Definition at line 2188 of file g_props.c.
Referenced by SP_Props_Flamebarrel().
void props_bench_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_bench_die
Parameters
[out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 834 of file g_props.c.
Referenced by SP_Props_Bench().
void props_bench_think (gentity_t * ent)
props_bench_think
Parameters
[in,out] ent
Definition at line 808 of file g_props.c.
Referenced by props_bench_die().
void props_castlebed_animate (gentity_t * ent)
props_castlebed_animate
Parameters
[in,out] ent
Note
Unused
Definition at line 3256 of file g_props.c.
Referenced by props_castlebed_die().
void props_castlebed_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_castlebed_die
Parameters
[out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Note
Unused
Definition at line 3283 of file g_props.c.
Referenced by SP_props_castlebed().
void props_castlebed_touch (gentity_t * ent, gentity_t * other, trace_t * trace)
props_castlebed_touch
QUAKED props_castlebed (.8 .6 .2) ? dimensions are 112 x 128 x 80 (x,y,z)
requires an origin brush
breakable NOT pushable
brushmodel only
health = default = 20 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in] ent
[in,out] other
trace - unused
Note
Unused
Definition at line 3227 of file g_props.c.
Referenced by SP_props_castlebed().
void Props_Chair_Animate (gentity_t * ent)
Props_Chair_Animate.
Parameters
[in,out] ent
Definition at line 1573 of file g_props.c.
Referenced by Props_Chair_Die().
void Props_Chair_Die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
Props_Chair_Die.
Parameters
[in,out] ent
[in] inflictor
attacker - unused
[in] damage
mod - unused
Definition at line 1730 of file g_props.c.
Referenced by Just_Got_Thrown(), Props_Activated(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_Desklamp(), and SP_Props_Locker_Tall().
void Props_Chair_Skyboxtouch (gentity_t * ent)
Props_Chair_Skyboxtouch.
Parameters
[out] ent
Definition at line 1757 of file g_props.c.
Referenced by G_RunItemProp().
void Props_Chair_Think (gentity_t * self)
Props_Chair_Think.
Parameters
[in,out] self
Definition at line 1359 of file g_props.c.
Referenced by Just_Got_Thrown(), Props_Barrel_Think(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_Desklamp(), and SP_Props_Locker_Tall().
void Props_Chair_Touch (gentity_t * self, gentity_t * other, trace_t * trace)
Props_Chair_Touch.
Parameters
[in,out] self
[in] other
trace - unused
Definition at line 1526 of file g_props.c.
Referenced by Just_Got_Thrown(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_Desklamp(), and SP_Props_Locker_Tall().
void props_crate32x64_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_crate32x64_die
Parameters
[out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 2862 of file g_props.c.
Referenced by SP_Props_Crate32x64().
void props_crate32x64_think (gentity_t * ent)
props_crate32x64_think
QUAKED props_crate_32x64 (.8 .6 .2) ? requires an origin brush
breakable NOT pushable
brushmodel only
health = default = 20 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] ent
Definition at line 2836 of file g_props.c.
Referenced by props_crate32x64_die().
void props_decoration_animate (gentity_t * ent)
props_decoration_animate
QUAKED props_decoration (.6 .7 .7) (-8 -8 0) (8 8 16) STARTINVIS DEBRIS ANIMATE KEEPBLOCK TOUCHACTIVATE LOOPING STARTON "model2" will specify the model to load
"noise" the looping sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
you will need to specify the bounding box for the entity "high" default is 4 "wide" default is 4
"frames" how many frames of animation to play "loop" when the animation is done start again on this frame "startonframe" on what frame do you want to start the animation
Parameters
[in,out] ent
Definition at line 3501 of file g_props.c.
Referenced by props_decoration_death(), SP_props_decoration(), and Use_props_decoration().
void props_decoration_death (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_decoration_death
Parameters
[in,out] ent
[in] inflictor
attacker - unused
damage - unused
mod - unused
Definition at line 3537 of file g_props.c.
Referenced by props_touch(), and SP_props_decoration().
void props_flamethrower_init (gentity_t * ent)
props_flamethrower_init
Parameters
[in,out] ent
Definition at line 4721 of file g_props.c.
Referenced by SP_props_flamethrower().
void props_flamethrower_think (gentity_t * ent)
props_flamethrower_think
QUAKED props_flamethrower (.6 .7 .3) (-8 -8 -8) (8 8 8) TRACKING NOSOUND the effect occurs when this entity is used needs to aim at a info_notnull "duration" how long the effect is going to last for example 1.2 sec 2.7 sec "random" how long of a random variance so the effect isnt exactly the same each time for example 1.1 sec or 0.2 sec "size" valid ranges are 1.0 to 0.1
NOSOUND - silent (duh)
Parameters
[in,out] ent
Definition at line 4592 of file g_props.c.
Referenced by props_flamethrower_use().
void props_flamethrower_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
props_flamethrower_use
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 4684 of file g_props.c.
Referenced by SP_props_flamethrower().
void props_flippy_blocked (gentity_t * ent, gentity_t * other)
props_flippy_blocked
Parameters
[in] ent
[in,out] other
Definition at line 3012 of file g_props.c.
Referenced by SP_Props_Flipping_Table().
void props_flippy_table_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_flippy_table_die
Parameters
[out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Note
Unused (see SP_Props_Flipping_Table)
Definition at line 2998 of file g_props.c.
void props_locker_death (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_locker_death
QUAKED props_footlocker (.6 .7 .3) (-12 -21 -12) (12 21 12) ? NO_JUNK "noise" the sound entity is to make upon death the default sounds are: "wood" - "sound/world/boardbreak.wav" "glass" - "sound/world/glassbreak.wav" "metal" - "sound/world/metalbreak.wav" "gibs" - "sound/player/gibsplit1.wav" "brick" - "sound/world/debris1.wav" "stone" - "sound/world/stonefall.wav" "fabric" - "sound/world/fabricbreak.wav"
"locknoise" the locked sound to play "wait" denotes how long the wait is going to be before the locked sound is played again default is 1 sec "health" default is 1
"spawnitem" - will spawn this item unpon death use the pickup_name ei 9mm
"type" - type of debris ("glass", "wood", "metal", "gibs", "brick", "rock", "fabric") default is "wood" "mass" - defaults to 75. This determines how much debris is emitted. You get one large chunk per 100 of mass (up to 8) and one small chunk per 25 of mass (up to 16). So 800 gives the most.
"dl_shader" needs to be set the same way as a target_effect
Todo:
FIXME/TBD: the spawning of junk still pending and animation when used
-----— MODEL FOR RADIANT ONLY - DO NOT SET THIS AS A KEY -----— model="models/mapobjects/furniture/footlocker.md3"
Parameters
[in,out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 4467 of file g_props.c.
Referenced by init_locker().
void props_locker_endrattle (gentity_t * ent)
props_locker_endrattle
Parameters
[out] ent
Definition at line 4294 of file g_props.c.
Referenced by props_locker_use().
void props_locker_mass (gentity_t * ent)
props_locker_mass
Parameters
[in] ent
Note
Unused
Definition at line 4402 of file g_props.c.
void props_locker_pain (gentity_t * ent, gentity_t * attacker, int damage, vec3_t point)
props_locker_pain
Parameters
[in] ent
[in] attacker
damage - unused
point - unused
Definition at line 4326 of file g_props.c.
Referenced by init_locker().
void props_locker_spawn_item (gentity_t * ent)
props_locker_spawn_item
Parameters
[in] ent
Definition at line 4373 of file g_props.c.
Referenced by props_locker_death().
void props_locker_tall_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_locker_tall_die
Parameters
[out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 1022 of file g_props.c.
Referenced by SP_Props_Locker_Tall().
void props_locker_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
props_locker_use
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 4308 of file g_props.c.
Referenced by init_locker(), and props_locker_pain().
void props_radio_die (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_radio_die
Parameters
[in,out] ent
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 877 of file g_props.c.
Referenced by SP_Props_Radio().
void props_radio_dieSEVEN (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_radio_dieSEVEN
Parameters
[in,out] ent
[in] inflictor
attacker - unused
damage - unused
mod - unused
Definition at line 929 of file g_props.c.
Referenced by SP_Props_RadioSEVEN().
void props_snowGenerator_think (gentity_t * ent)
props_snowGenerator_think
QUAKED props_snowGenerator (3 2 7) ? TOGGLE_ON ALWAYS_ON entity brush need to be targeted to an info notnull this will determine the direction the snow particles will travel.
speed gravity turb
count is the number of snowflurries 3 to 5 would be a good number
duration is how long the effect will last 1 is 1 second
Parameters
[in,out] ent
Definition at line 3338 of file g_props.c.
Referenced by props_snowGenerator_use(), and SP_props_snowGenerator().
void props_snowGenerator_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
props_snowGenerator_use
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 3386 of file g_props.c.
Referenced by SP_props_snowGenerator().
void props_statue_animate (gentity_t * ent)
props_statue_animate
Parameters
[in,out] ent
Definition at line 3984 of file g_props.c.
Referenced by props_statue_death().
void props_statue_blocked (gentity_t * ent)
props_statue_blocked
QUAKED props_statue (.6 .3 .2) (-8 -8 0) (8 8 128) HURT DEBRIS ANIMATE KEEPBLOCK "model2" will specify the model to load
"noise" the sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
you will need to specify the bounding box for the entity "high" default is 4 "wide" default is 4
"frames" how many frames of animation to play "delay" how long of a delay before damage is inflicted ei. 0.5 sec or 2.7 sec
"damage" amount of damage to be inflicted
Parameters
[in] ent
Definition at line 3910 of file g_props.c.
Referenced by props_statue_animate().
void props_statue_death (gentity_t * ent, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
props_statue_death
Parameters
[in] ent
[in] inflictor
attacker - unused
damage - unused
mod - unused
Definition at line 4030 of file g_props.c.
Referenced by props_statue_touch(), and SP_props_statue().
void props_statue_touch (gentity_t * self, gentity_t * other, trace_t * trace)
props_statue_touch
Parameters
[in] self
[in] other
trace - unused
Definition at line 4069 of file g_props.c.
Referenced by SP_props_statue().
void props_touch (gentity_t * self, gentity_t * other, trace_t * trace)
props_touch
Parameters
[in] self
[in] other
trace - unused
Definition at line 3597 of file g_props.c.
Referenced by SP_props_decoration().
void Props_TurnLightsOff (gentity_t * self)
Props_TurnLightsOff.
Parameters
[in,out] self
Definition at line 1199 of file g_props.c.
Referenced by Props_Activated().
void Psmoke_think (gentity_t * ent)
Psmoke_think.
Parameters
[out] ent
Definition at line 276 of file g_props.c.
Referenced by prop_smoke().
void Psparks_think (gentity_t * ent)
Psparks_think.
Parameters
[in] ent
Todo:
FIXME: MOVE TO CLIENT!
Todo:
MOVE TO CLIENT!
Definition at line 355 of file g_props.c.
Referenced by sparks_angles_think().
void smokedust_use (gentity_t * ent, gentity_t * self, gentity_t * activator)
QUAKED props_smokedust (.8 .46 .16) (-8 -8 -8) (8 8 8) health = how many pieces 16 is default.
Parameters
[in] ent
self - unused
activator - unused
Definition at line 515 of file g_props.c.
Referenced by SP_SmokeDust().
void smoker_think (gentity_t * ent)
smoker_think
Parameters
[in,out] ent
Note
Unused
Definition at line 2264 of file g_props.c.
void SP_crate_32 (gentity_t * self)
SP_crate_32.
QUAKED props_crate_32 (.8 .6 .2) (-16 -16 0) (16 16 32) breakable pushable
health = default = 20 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] self
Definition at line 2769 of file g_props.c.
void SP_crate_64 (gentity_t * self)
SP_crate_64.
QUAKED props_crate_64 (.8 .6 .2) (-32 -32 0) (32 32 64) breakable pushable
health = default = 20 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] self
Definition at line 2708 of file g_props.c.
void SP_Dust (gentity_t * ent)
SP_Dust.
Parameters
[in,out] ent
Definition at line 619 of file g_props.c.
void SP_OilParticles (gentity_t * ent)
SP_OilParticles.
Parameters
ent
Todo:
FIXME: move this to client !
Definition at line 2385 of file g_props.c.
Referenced by Props_Barrel_Pain().
void SP_OilSlick (gentity_t * ent)
SP_OilSlick.
Parameters
[in] ent
Definition at line 2283 of file g_props.c.
Referenced by Props_Barrel_Pain().
void SP_Props_58x112tablew (gentity_t * ent)
SP_Props_58x112tablew.
Parameters
[in,out] ent
Definition at line 3181 of file g_props.c.
void SP_Props_Bench (gentity_t * ent)
SP_Props_Bench.
QUAKED props_bench (.8 .6 .2) ? requires an origin brush health = 10 by default
Parameters
ent
Definition at line 849 of file g_props.c.
void SP_props_box_32 (gentity_t * self)
SP_props_box_32 QUAKED props_box_32 (1 0 0) (-16 -16 -16) (16 16 16)
Parameters
[out] self
Definition at line 163 of file g_props.c.
void SP_props_box_48 (gentity_t * self)
SP_props_box_48 QUAKED props_box_48 (1 0 0) (-24 -24 -24) (24 24 24)
Parameters
[out] self
Definition at line 208 of file g_props.c.
void SP_props_box_64 (gentity_t * self)
SP_props_box_64 QUAKED props_box_64 (1 0 0) (-32 -32 -32) (32 32 32)
Parameters
[out] self
Definition at line 253 of file g_props.c.
void SP_props_castlebed (gentity_t * ent)
SP_props_castlebed.
Parameters
[in,out] ent
Note
Unused
Definition at line 3300 of file g_props.c.
void SP_Props_Chair (gentity_t * ent)
SP_Props_Chair.
Parameters
[in,out] ent
Definition at line 1766 of file g_props.c.
void SP_Props_ChairChat (gentity_t * ent)
SP_Props_ChairChat.
Parameters
[in,out] ent
Definition at line 1990 of file g_props.c.
void SP_Props_ChairChatArm (gentity_t * ent)
SP_Props_ChairChatArm.
Parameters
[in,out] ent
Definition at line 2000 of file g_props.c.
void SP_Props_ChairHiback (gentity_t * ent)
SP_Props_ChairHiback.
Parameters
[in,out] ent
Definition at line 1822 of file g_props.c.
void SP_Props_ChairSide (gentity_t * ent)
SP_Props_ChairSide.
Parameters
[in,out] ent
Definition at line 1878 of file g_props.c.
void SP_Props_ChateauChair (gentity_t * ent)
SP_Props_ChateauChair.
Parameters
[in,out] ent
Note
Can be one of two types, but they have the same animations/etc, so re-use what you can
Definition at line 1936 of file g_props.c.
Referenced by SP_Props_ChairChat(), and SP_Props_ChairChatArm().
void SP_Props_Crate32x64 (gentity_t * ent)
SP_Props_Crate32x64.
Parameters
[in,out] ent
Definition at line 2872 of file g_props.c.
void SP_Props_DamageInflictor (gentity_t * ent)
SP_Props_DamageInflictor.
QUAKED props_damageinflictor (.8 .6 .6) (-8 -8 -8) (8 8 8) this entity when used will cause 9999 damage to all entities it is targeting then it will be removed
Parameters
[in,out] ent
Definition at line 2040 of file g_props.c.
void SP_props_decor_Scale (gentity_t * ent)
SP_props_decor_Scale.
QUAKED props_decoration_scale (.6 .7 .7) (-8 -8 0) (8 8 16) STARTINVIS DEBRIS ANIMATE KEEPBLOCK TOUCHACTIVATE LOOPING STARTON
"modelscale" - Scale multiplier (defaults to 1.0 and scales uniformly) "modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both the "modelscale" is ignored
"model2" will specify the model to load
"noise" the looping sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
you will need to specify the bounding box for the entity "high" default is 4 "wide" default is 4
"frames" how many frames of animation to play "loop" when the animation is done start again on this frame "startonframe" on what frame do you want to start the animation
Parameters
[in,out] ent
Definition at line 3830 of file g_props.c.
void SP_props_decoration (gentity_t * ent)
SP_props_decoration.
Parameters
[in,out] ent
Definition at line 3609 of file g_props.c.
Referenced by SP_props_decor_Scale(), and SP_props_decorBRUSH().
void SP_props_decorBRUSH (gentity_t * self)
SP_props_decorBRUSH.
QUAKED props_decorBRUSH (.6 .7 .7) ? STARTINVIS DEBRIS ANIMATE KEEPBLOCK - LOOPING STARTON ANIMATE animate on death STARTON playanimation on death must have an origin brush
"model2" will specify the model to load
"noise" the looping sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
"frames" how many frames of animation to play "loop" when the animation is done start again on this frame "startonframe" on what frame do you want to start the animation
Parameters
[in,out] self
Definition at line 3793 of file g_props.c.
void SP_Props_Desklamp (gentity_t * ent)
SP_Props_Desklamp.
QUAKED props_desklamp (.8 .6 .2) (-16 -16 0) (16 16 32) point entity health = default = 10 wait = defaults to 5 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] ent
Definition at line 2121 of file g_props.c.
void SP_Props_Flamebarrel (gentity_t * ent)
SP_Props_Flamebarrel.
Parameters
[in,out] ent
Definition at line 2560 of file g_props.c.
void SP_props_flamethrower (gentity_t * ent)
SP_props_flamethrower.
Parameters
[in,out] ent
Definition at line 4755 of file g_props.c.
void SP_Props_Flipping_Table (gentity_t * ent)
SP_Props_Flipping_Table.
Parameters
[in,out] ent
Definition at line 3063 of file g_props.c.
void SP_props_footlocker (gentity_t * self)
SP_props_footlocker.
Parameters
[in,out] self
Todo:
: test this
Definition at line 4484 of file g_props.c.
void SP_props_gunsparks (gentity_t * ent)
SP_props_gunsparks.
QUAKED props_gunsparks (.8 .46 .16) (-8 -8 -8) (8 8 8) the default direction is strait up use info_no_null for alt direction
this entity must be used to see the effect
"speed" default is 20 "health" number to spawn default is 4
Parameters
ent
Definition at line 486 of file g_props.c.
void SP_Props_Locker_Tall (gentity_t * ent)
SP_Props_Locker_Tall.
QUAKED props_locker_tall (.8 .6 .2) ? requires an origin brush
Parameters
ent
Definition at line 1040 of file g_props.c.
void SP_Props_Radio (gentity_t * ent)
SP_Props_Radio.
QUAKED props_radio (.8 .6 .2) ? requires an origin brush health = defaults to 100
Parameters
[in,out] ent
Definition at line 897 of file g_props.c.
void SP_Props_RadioSEVEN (gentity_t * ent)
SP_Props_RadioSEVEN.
QUAKED props_radioSEVEN (.8 .6 .2) ? requires an origin brush health = defaults to 100
the models dims are x 32 y 136 z 32
if you want more explosions you'll need func explosive
it will fire all its targets upon death
Parameters
[in,out] ent
Definition at line 970 of file g_props.c.
void SP_props_shard_generator (gentity_t * ent)
SP_props_shard_generator.
Parameters
[in,out] ent
Note
Unused
Definition at line 2086 of file g_props.c.
void SP_props_snowGenerator (gentity_t * ent)
SP_props_snowGenerator.
Parameters
[in,out] ent
Definition at line 3405 of file g_props.c.
void SP_props_sparks (gentity_t * ent)
SP_props_sparks.
Parameters
[out] ent
Definition at line 426 of file g_props.c.
void SP_props_statue (gentity_t * ent)
SP_props_statue.
Parameters
[in,out] ent
Definition at line 4078 of file g_props.c.
Referenced by SP_props_statueBRUSH().
void SP_props_statueBRUSH (gentity_t * self)
SP_props_statueBRUSH.
QUAKED props_statueBRUSH (.6 .3 .2) ? HURT DEBRIS ANIMATE KEEPBLOCK needs an origin brush
"model2" will specify the model to load
"noise" the sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
"frames" how many frames of animation to play "delay" how long of a delay before damage is inflicted ei. 0.5 sec or 2.7 sec
THE damage has been disabled at the moment "damage" amount of damage to be inflicted
Parameters
[in,out] self
Definition at line 4222 of file g_props.c.
void SP_skyportal (gentity_t * ent)
SP_skyportal.
QUAKED props_skyportal (.6 .7 .7) (-8 -8 0) (8 8 16) "fov" for the skybox default is 90 To have the portal sky fogged, enter any of the following values: "fogcolor" (r g b) (values 0.0-1.0) "fognear" distance from entity to start fogging "fogfar" distance from entity that fog is opaque
Parameters
ent
Definition at line 3869 of file g_props.c.
void SP_SmokeDust (gentity_t * ent)
SP_SmokeDust.
Parameters
[in,out] ent
Definition at line 538 of file g_props.c.
void sparks_angles_think (gentity_t * ent)
sparks_angles_think
Parameters
[in,out] ent
Definition at line 387 of file g_props.c.
Referenced by SP_props_gunsparks().
void Spawn_Junk (gentity_t * ent)
Spawn_Junk.
Parameters
[in] ent
Note
Unused
Definition at line 4262 of file g_props.c.
void Spawn_Shard (gentity_t * ent, gentity_t * inflictor, float quantity, int type)
Spawn_Shard.
Parameters
[in] ent
[in] inflictor
[in] quantity
[in] type
Definition at line 1657 of file g_props.c.
Referenced by crate_die(), Props_Barrel_Die(), Props_Chair_Die(), props_decoration_death(), props_radio_dieSEVEN(), props_statue_death(), Static_Pain(), and Use_Props_Shard_Generator().
void touch_crate_64 (gentity_t * self, gentity_t * other, trace_t * trace)
touch_crate_64
Parameters
[in] self
[in] other
trace - unused
Definition at line 2632 of file g_props.c.
Referenced by SP_crate_32(), and SP_crate_64().
void touch_props_box_32 (gentity_t * self, gentity_t * other, trace_t * trace)
touch_props_box_32
Parameters
[in] self
[in] other
trace - unused
Definition at line 143 of file g_props.c.
Referenced by SP_props_box_32().
void touch_props_box_48 (gentity_t * self, gentity_t * other, trace_t * trace)
touch_props_box_48
Parameters
[in] self
[in] other
trace - unused
Definition at line 188 of file g_props.c.
Referenced by SP_props_box_48().
void touch_props_box_64 (gentity_t * self, gentity_t * other, trace_t * trace)
touch_props_box_64
Parameters
[in] self
[in] other
trace - unused
Definition at line 233 of file g_props.c.
Referenced by SP_props_box_64().
void Use_DamageInflictor (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_DamageInflictor.
Parameters
[in] ent
other - unused
activator - unused
Definition at line 2012 of file g_props.c.
Referenced by SP_Props_DamageInflictor().
void Use_props_decoration (gentity_t * ent, gentity_t * self, gentity_t * activator)
Use_props_decoration.
Parameters
[in,out] ent
self - unused
activator - unused
Definition at line 3572 of file g_props.c.
Referenced by SP_props_decoration().
void Use_Props_Shard_Generator (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Props_Shard_Generator.
QUAKED props_shard_generator (.8 .5 .1) (-4 -4 -4) (4 4 4)
wait = defaults to 5 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_WOOD = 0, FXTYPE_GLASS = 1, FXTYPE_METAL = 2
Parameters
[in] ent
other - unused
activator - unused
Definition at line 2066 of file g_props.c.
Referenced by SP_props_shard_generator().
qboolean validOilSlickSpawnPoint (vec3_t point, gentity_t * ent)
validOilSlickSpawnPoint
Parameters
[in] point
[in] ent
Returns
Note
Unused
Definition at line 2352 of file g_props.c.
Variable Documentation
int locker_debris_model[MAX_LOCKER_DEBRIS]
Definition at line 4253 of file g_props.c.