ET: Legacy: src/game/g_referee.c File Reference
g_referee.c File Reference
Referee handling.
#include "g_local.h"
#include "../../etmain/ui/menudef.h"
Functions
qboolean G_refCommandCheck (gentity_t *ent, const char *cmd)
Parses for a referee command. ref arg allows for the server console to utilize all referee commands (ent == NULL)
void G_refHelp_cmd (gentity_t *ent)
Lists ref commands.
void G_ref_cmd (gentity_t *ent, unsigned int dwCommand, qboolean fValue)
Request for ref status or lists ref commands.
void G_refAllReady_cmd (gentity_t *ent)
Readies all players in the game.
void G_refLockTeams_cmd (gentity_t *ent, qboolean fLock)
Changes team lock status.
void G_refPause_cmd (gentity_t *ent, qboolean fPause)
Pause/unpause a match.
void G_refPlayerPut_cmd (gentity_t *ent, team_t team_id)
Puts a player on a team.
void G_refRemove_cmd (gentity_t *ent)
Removes a player from a team.
void G_refSpeclockTeams_cmd (gentity_t *ent, qboolean fLock)
Changes team spectator lock status.
void G_refWarmup_cmd (gentity_t *ent)
G_refWarmup_cmd.
void G_refWarning_cmd (gentity_t *ent)
G_refWarning_cmd.
void G_refMute_cmd (gentity_t *ent, qboolean mute)
(Un)Mutes a player
void G_refLogout_cmd (gentity_t *ent)
G_refLogout_cmd.
void Cmd_AuthRcon_f (gentity_t *ent)
Client authentication.
void G_PlayerBan ()
G_PlayerBan.
void G_MakeReferee ()
G_MakeReferee.
void G_RemoveReferee ()
G_RemoveReferee.
void G_MakeShoutcaster (gentity_t *ent)
G_MakeShoutcaster.
void G_RemoveShoutcaster (gentity_t *ent)
G_RemoveShoutcaster.
void G_RemoveAllShoutcasters (void)
G_RemoveAllShoutcasters.
void G_MuteClient ()
G_MuteClient.
void G_UnMuteClient ()
G_UnMuteClient.
qboolean G_IsShoutcastPasswordSet (void)
G_IsShoutcastPasswordSet.
qboolean G_IsShoutcastStatusAvailable (gentity_t *ent)
G_IsShoutcastStatusAvailable.
void G_refMakeShoutcaster_cmd (gentity_t *ent)
G_refMakeShoutcaster_cmd.
void G_refRemoveShoutcaster_cmd (gentity_t *ent)
G_refRemoveShoutcaster_cmd.
int G_refClientnumForName (gentity_t *ent, const char *name)
G_refClientnumForName.
void G_refPrintf (gentity_t *ent, const char *fmt,...)
G_refPrintf.
Detailed Description
Referee handling.
Definition in file g_referee.c.
Function Documentation
void Cmd_AuthRcon_f (gentity_t * ent)
Client authentication.
Parameters
[in,out] ent
Definition at line 594 of file g_referee.c.
Referenced by ClientCommand().
qboolean G_IsShoutcastPasswordSet (void)
G_IsShoutcastPasswordSet.
Returns
Definition at line 864 of file g_referee.c.
Referenced by G_IsShoutcastStatusAvailable(), G_makesc_cmd(), G_refMakeShoutcaster_cmd(), G_refRemoveShoutcaster_cmd(), and G_removesc_cmd().
qboolean G_IsShoutcastStatusAvailable (gentity_t * ent)
G_IsShoutcastStatusAvailable.
Parameters
[in] ent
Returns
Definition at line 879 of file g_referee.c.
Referenced by G_sclogin_cmd(), and G_sclogout_cmd().
void G_MakeReferee (void)
G_MakeReferee.
Definition at line 653 of file g_referee.c.
void G_MakeShoutcaster (gentity_t * ent)
G_MakeShoutcaster.
Parameters
[in] ent
Definition at line 726 of file g_referee.c.
Referenced by G_makesc_cmd(), G_refMakeShoutcaster_cmd(), and G_sclogin_cmd().
void G_MuteClient (void)
G_MuteClient.
Definition at line 795 of file g_referee.c.
void G_PlayerBan (void)
G_PlayerBan.
Console admin commands
Definition at line 614 of file g_referee.c.
void G_ref_cmd (gentity_t * ent, unsigned int dwCommand, qboolean fValue)
Request for ref status or lists ref commands.
Parameters
[in,out] ent
dwCommand - unused
fValue - unused
Definition at line 170 of file g_referee.c.
void G_refAllReady_cmd (gentity_t * ent)
Readies all players in the game.
Parameters
[in] ent
Definition at line 237 of file g_referee.c.
Referenced by G_refCommandCheck(), G_StartMatch_v(), and Svcmd_StartMatch_f().
int G_refClientnumForName (gentity_t * ent, const char * name)
G_refClientnumForName.
Utility
Parameters
[in] ent
[in] name
Returns
Definition at line 1002 of file g_referee.c.
Referenced by Cmd_Ignore_f(), Cmd_UnIgnore_f(), G_MakeReferee(), G_MuteClient(), G_PlayerBan(), G_refWarning_cmd(), G_RemoveReferee(), and G_UnMuteClient().
qboolean G_refCommandCheck (gentity_t * ent, const char * cmd)
Parses for a referee command. ref arg allows for the server console to utilize all referee commands (ent == NULL)
Parameters
[in] ent
[in] cmd
Returns
Definition at line 46 of file g_referee.c.
Referenced by G_ref_cmd(), and Svcmd_Ref_f().
void G_refHelp_cmd (gentity_t * ent)
Lists ref commands.
Parameters
[in] ent
Definition at line 132 of file g_referee.c.
Referenced by G_ref_cmd(), G_refCommandCheck(), and Svcmd_Ref_f().
void G_refLockTeams_cmd (gentity_t * ent, qboolean fLock)
Changes team lock status.
Parameters
[in] ent
[in] fLock
Definition at line 269 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refLogout_cmd (gentity_t * ent)
G_refLogout_cmd.
Parameters
[in] ent
Definition at line 580 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refMakeShoutcaster_cmd (gentity_t * ent)
G_refMakeShoutcaster_cmd.
Parameters
[in] ent
Definition at line 899 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refMute_cmd (gentity_t * ent, qboolean mute)
(Un)Mutes a player
Parameters
[in] ent
[in] mute
Definition at line 532 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refPause_cmd (gentity_t * ent, qboolean fPause)
Pause/unpause a match.
Parameters
[in] ent
[in] fPause
Definition at line 297 of file g_referee.c.
Referenced by G_pause_cmd(), and G_refCommandCheck().
void G_refPlayerPut_cmd (gentity_t * ent, team_t team_id)
Puts a player on a team.
Parameters
[in] ent
[in] team_id
Definition at line 346 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refPrintf (gentity_t * ent, const char * fmt, ...)
G_refPrintf.
Parameters
[in] ent
[in] fmt
Definition at line 1032 of file g_referee.c.
Referenced by G_refAllReady_cmd(), G_refClientnumForName(), G_refLockTeams_cmd(), G_refMakeShoutcaster_cmd(), G_refMute_cmd(), G_refPause_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_refRemoveShoutcaster_cmd(), G_refWarmup_cmd(), and G_refWarning_cmd().
void G_refRemove_cmd (gentity_t * ent)
Removes a player from a team.
Parameters
[in] ent
Definition at line 403 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refRemoveShoutcaster_cmd (gentity_t * ent)
G_refRemoveShoutcaster_cmd.
Parameters
[in] ent
Definition at line 951 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refSpeclockTeams_cmd (gentity_t * ent, qboolean fLock)
Changes team spectator lock status.
Parameters
ent - unused
[in] fLock
Definition at line 449 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refWarmup_cmd (gentity_t * ent)
G_refWarmup_cmd.
Parameters
[in] ent
Definition at line 476 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_refWarning_cmd (gentity_t * ent)
G_refWarning_cmd.
Parameters
[in] ent
Definition at line 496 of file g_referee.c.
Referenced by G_refCommandCheck().
void G_RemoveAllShoutcasters (void)
G_RemoveAllShoutcasters.
Definition at line 769 of file g_referee.c.
Referenced by G_UpdateCvars().
void G_RemoveReferee (void)
G_RemoveReferee.
Definition at line 692 of file g_referee.c.
void G_RemoveShoutcaster (gentity_t * ent)
G_RemoveShoutcaster.
Parameters
[in] ent
Definition at line 749 of file g_referee.c.
Referenced by G_refRemoveShoutcaster_cmd(), G_removesc_cmd(), and G_sclogout_cmd().
void G_UnMuteClient (void)
G_UnMuteClient.
Definition at line 829 of file g_referee.c.