ET: Legacy: src/game/g_strparse.c File Reference
g_strparse.c File Reference
#include "g_strparse.h"
#include "g_local.h"
Data Structures
struct g_strtoken_t
Functions
const g_strtoken_t * in_word_set (const char *str, unsigned int len)
g_StringToken_t G_GetTokenForString (char const *str)
G_GetTokenForString.
Function Documentation
g_StringToken_t G_GetTokenForString (char const * str)
G_GetTokenForString.
Parameters
[in] str
Returns
Definition at line 54 of file g_strparse.c.
Referenced by ClientConnect(), and ClientUserinfoChanged().
const g_strtoken_t* in_word_set (const char * str, unsigned int len)
Referenced by G_GetTokenForString().