ET: Legacy: src/game/g_svcmds.c File Reference
g_svcmds.c File Reference
Holds commands that can be executed by the server console, but not remote clients.
#include "g_local.h"
#include "g_etbot_interface.h"
#include "g_lua.h"
Data Structures
struct ipGUID_s
struct ipFilterList_s
Macros
#define MAX_IPFILTERS 1024
#define USE_ENGINE_BANLIST qtrue
Typedefs
typedef struct ipGUID_s ipGUID_t
typedef struct ipFilterList_s ipFilterList_t
Functions
qboolean StringToFilter (const char *s, ipFilter_t *f)
StringToFilter.
static void UpdateIPBans (ipFilterList_t *ipFilterList)
UpdateIPBans.
void PrintMaxLivesGUID (void)
PrintMaxLivesGUID.
qboolean G_FilterPacket (ipFilterList_t *ipFilterList, char *from)
G_FilterPacket.
qboolean G_FilterIPBanPacket (char *from)
G_FilterIPBanPacket.
qboolean G_FilterMaxLivesIPPacket (char *from)
G_FilterMaxLivesIPPacket.
qboolean G_FilterMaxLivesPacket (char *from)
Check to see if the user is trying to sneak back in with g_enforcemaxlives enabled.
void AddIP (ipFilterList_t *ipFilterList, const char *str)
AddIP.
void AddIPBan (const char *str)
AddIPBan.
void AddMaxLivesBan (const char *str)
AddMaxLivesBan.
void AddMaxLivesGUID (const char *str)
>ith g_enforcemaxlives enabled, this adds a client GUID to a list that prevents them from quitting and reconnecting
void G_ProcessIPBans (void)
G_ProcessIPBans.
void Svcmd_AddIP_f (void)
Svcmd_AddIP_f.
void Svcmd_RemoveIP_f (void)
Svcmd_RemoveIP_f.
void Svcmd_ListIp_f (void)
Svcmd_ListIp_f.
void ClearMaxLivesBans ()
Clears out the entire list maxlives enforcement banlist.
void Svcmd_EntityList_f (void)
prints a list of used - or when any param is added for all entities with following info
gclient_t * ClientForString (const char *s)
ClientForString.
static qboolean G_Is_SV_Running (void)
G_Is_SV_Running.
gclient_t * G_GetPlayerByNum (int clientNum)
G_GetPlayerByNum.
gclient_t * G_GetPlayerByName (const char *name)
G_GetPlayerByName.
void Svcmd_ForceTeam_f (void)
Svcmd_ForceTeam_f.
void Svcmd_StartMatch_f (void)
starts match if in tournament mode
void Svcmd_ResetMatch_f (qboolean fDoReset, qboolean fDoRestart)
Multi-use now for both map restarts and total match resets.
void Svcmd_ResetMatch (void)
Svcmd_ResetMatch.
void Svcmd_SwapTeams_f (void)
swaps all clients to opposite team
void Svcmd_ShuffleTeamsXP_f (qboolean restart)
randomly places players on teams
void Svcmd_ShuffleTeamsXP (void)
Svcmd_ShuffleTeamsXP.
void Svcmd_ShuffleTeamsXPNoRestart (void)
Svcmd_ShuffleTeamsXPNoRestart.
void Svcmd_Campaign_f (void)
Svcmd_Campaign_f.
void Svcmd_ListCampaigns_f (void)
Svcmd_ListCampaigns_f.
void ReviveEntity (gentity_t *ent, gentity_t *traceEnt)
Took this out of Weapon_Syringe so we can use it from other places.
int FindClientByName (const char *name)
FindClientByName.
void Svcmd_RevivePlayer (void)
Svcmd_RevivePlayer.
static void Svcmd_Gib (void)
Gib command - based on shrubbot.
static void Svcmd_Die (void)
kill command - kills players
static void Svcmd_Freeze (void)
freeze command - freezes players
static void Svcmd_Unfreeze (void)
unfreeze command - unfreezes players
static void Svcmd_Burn (void)
burn command - burns players
static void G_Pip (gentity_t *vic)
G_Pip.
static void Svcmd_Pip (void)
pip command - pips players
static void Svcmd_Fling (void)
Svcmd_Fling.
static void Svcmd_Kick_f (void)
kick a user off of the server
static void Svcmd_KickNum_f (void)
kick a user off of the server
void Svcmd_CP_f (void)
Svcmd_CP_f.
void G_UpdateSvCvars (void)
G_UpdateSvCvars.
void CC_cvarempty (void)
CC_cvarempty.
void CC_svcvar (void)
Forces client cvar to a specific value.
char * ConcatArgs (int start)
Concatenates console arguments.
void CC_loadconfig (void)
CC_loadconfig.
void Svcmd_CSInfo_f (void)
Svcmd_CSInfo_f.
void Svcmd_Ref_f (void)
Svcmd_Ref_f.
qboolean Svcmd_Say_f (void)
Svcmd_Say_f.
qboolean Svcmd_Chat_f (void)
Svcmd_Chat_f.
qboolean ConsoleCommand (void)
ConsoleCommand.
Variables
static ipFilterList_t ipFilters
static ipFilterList_t ipMaxLivesFilters
static ipGUID_t guidMaxLivesFilters [MAX_IPFILTERS]
static int numMaxLivesFilters = 0
const char * enttypenames []
static consoleCommandTable_t consoleCommandTable []
Store common console command.
Detailed Description
Holds commands that can be executed by the server console, but not remote clients.
Definition in file g_svcmds.c.
Macro Definition Documentation
#define MAX_IPFILTERS 1024
Definition at line 85 of file g_svcmds.c.
Referenced by AddIP(), and AddMaxLivesGUID().
#define USE_ENGINE_BANLIST qtrue
change into qfalse if you want to use the qagame banning system which makes it possible to unban IP addresses
Definition at line 1779 of file g_svcmds.c.
Referenced by Svcmd_Kick_f(), and Svcmd_KickNum_f().
Typedef Documentation
typedef struct ipFilterList_s ipFilterList_t
typedef struct ipGUID_s ipGUID_t
Function Documentation
void AddIP (ipFilterList_t * ipFilterList, const char * str)
AddIP.
Parameters
[in] ipFilterList
[in] str
Definition at line 308 of file g_svcmds.c.
Referenced by AddIPBan(), AddMaxLivesBan(), G_ProcessIPBans(), and Svcmd_AddIP_f().
void AddIPBan (const char * str)
AddIPBan.
Parameters
[in] str
Definition at line 342 of file g_svcmds.c.
Referenced by G_PlayerBan(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
void AddMaxLivesBan (const char * str)
AddMaxLivesBan.
Parameters
[in] str
Definition at line 351 of file g_svcmds.c.
Referenced by ClientBegin().
void AddMaxLivesGUID (const char * str)
>ith g_enforcemaxlives enabled, this adds a client GUID to a list that prevents them from quitting and reconnecting
Parameters
[in] str
Definition at line 362 of file g_svcmds.c.
Referenced by ClientBegin().
void CC_cvarempty (void)
CC_cvarempty.
Definition at line 2029 of file g_svcmds.c.
void CC_loadconfig (void)
CC_loadconfig.
Definition at line 2151 of file g_svcmds.c.
void CC_svcvar (void)
Forces client cvar to a specific value.
Definition at line 2039 of file g_svcmds.c.
void ClearMaxLivesBans (void)
Clears out the entire list maxlives enforcement banlist.
Definition at line 470 of file g_svcmds.c.
Referenced by G_InitGame().
gclient_t* ClientForString (const char * s)
ClientForString.
Parameters
[in] s
Returns
Note
If a player is called '3' and there are only 2 players on the server (clientnum 0 and 1) this function will say 'client 3 is not connected' solution: first check for usernames, if none is found, check for slotnumbers
Definition at line 643 of file g_svcmds.c.
Referenced by Svcmd_ForceTeam_f().
char* ConcatArgs (int start)
Concatenates console arguments.
Parameters
[in] start concatenate from this argument
Definition at line 488 of file g_cmds.c.
Referenced by _et_ConcatArgs(), CC_svcvar(), Cmd_Give_f(), Cmd_God_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_Say_f(), Cmd_Voice_f(), G_Poll_v(), Svcmd_Chat_f(), Svcmd_CP_f(), and Svcmd_Say_f().
qboolean ConsoleCommand (void)
ConsoleCommand.
Returns
Definition at line 2572 of file g_svcmds.c.
Referenced by vmMain().
int FindClientByName (const char * name)
FindClientByName.
Parameters
[in] name
Returns
Definition at line 2720 of file g_misc.c.
Referenced by Svcmd_ListCampaigns_f(), and Svcmd_RevivePlayer().
qboolean G_FilterIPBanPacket (char * from)
G_FilterIPBanPacket.
Parameters
[in] from
Returns
Definition at line 269 of file g_svcmds.c.
Referenced by ClientConnect().
qboolean G_FilterMaxLivesIPPacket (char * from)
G_FilterMaxLivesIPPacket.
Parameters
[in] from
Returns
Definition at line 279 of file g_svcmds.c.
Referenced by ClientConnect().
qboolean G_FilterMaxLivesPacket (char * from)
Check to see if the user is trying to sneak back in with g_enforcemaxlives enabled.
Parameters
[in] from
Definition at line 289 of file g_svcmds.c.
Referenced by ClientConnect().
qboolean G_FilterPacket (ipFilterList_t * ipFilterList, char * from)
G_FilterPacket.
Parameters
[in] ipFilterList
[in] from
Returns
Definition at line 228 of file g_svcmds.c.
Referenced by G_FilterIPBanPacket(), and G_FilterMaxLivesIPPacket().
gclient_t* G_GetPlayerByName (const char * name)
G_GetPlayerByName.
Parameters
[in] name
Returns
Definition at line 742 of file g_svcmds.c.
Referenced by Svcmd_Kick_f().
gclient_t* G_GetPlayerByNum (int clientNum)
G_GetPlayerByNum.
Parameters
[in] clientNum
Returns
Definition at line 704 of file g_svcmds.c.
Referenced by Svcmd_KickNum_f().
static qboolean G_Is_SV_Running (void) static
G_Is_SV_Running.
Returns
Definition at line 691 of file g_svcmds.c.
Referenced by G_GetPlayerByName(), G_GetPlayerByNum(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
static void G_Pip (gentity_t * vic) static
G_Pip.
Parameters
[in] vic
Todo:
FIXME: beside the pip command EV_SPARKS and EV_SPARKS_ELECTRIC aren't used for real ... we may delete these events EV_SPARKS_ELECTRIC doesn't seem to work anyway
Definition at line 1572 of file g_svcmds.c.
Referenced by Svcmd_Pip().
void G_ProcessIPBans (void)
G_ProcessIPBans.
Definition at line 376 of file g_svcmds.c.
Referenced by G_InitGame().
void G_UpdateSvCvars (void)
G_UpdateSvCvars.
Todo:
: print a warning when this configstring has nearly reached MAX_INFO_STRING size and don't set it if greater
Definition at line 1999 of file g_svcmds.c.
Referenced by CC_cvarempty(), and CC_svcvar().
void PrintMaxLivesGUID (void)
PrintMaxLivesGUID.
Definition at line 211 of file g_svcmds.c.
void ReviveEntity (gentity_t * ent, gentity_t * traceEnt)
Took this out of Weapon_Syringe so we can use it from other places.
Parameters
[in] ent
[in,out] traceEnt
Returns
Definition at line 323 of file g_weapon.c.
Referenced by Svcmd_ListCampaigns_f(), Svcmd_RevivePlayer(), and Weapon_Syringe().
qboolean StringToFilter (const char * s, ipFilter_t * f)
StringToFilter.
Parameters
[in,out] s
[out] f
Returns
Definition at line 106 of file g_svcmds.c.
Referenced by AddIP(), Cmd_CallVote_f(), Cmd_Vote_f(), and Svcmd_RemoveIP_f().
void Svcmd_AddIP_f (void)
Svcmd_AddIP_f.
Definition at line 406 of file g_svcmds.c.
static void Svcmd_Burn (void) static
burn command - burns players
Todo:
: usage
Todo:
: add mod param? mod_unknown instead of flamer
Todo:
: add mod param? mod_unknown instead of flamer
Definition at line 1487 of file g_svcmds.c.
void Svcmd_Campaign_f (void)
Svcmd_Campaign_f.
Definition at line 978 of file g_svcmds.c.
qboolean Svcmd_Chat_f (void)
Svcmd_Chat_f.
Definition at line 2500 of file g_svcmds.c.
Referenced by ConsoleCommand().
void Svcmd_CP_f (void)
Svcmd_CP_f.
Definition at line 1991 of file g_svcmds.c.
void Svcmd_CSInfo_f (void)
Svcmd_CSInfo_f.
Definition at line 2171 of file g_svcmds.c.
static void Svcmd_Die (void) static
kill command - kills players
Todo:
: usage
Definition at line 1163 of file g_svcmds.c.
names of enum entityType_t for Svcmd_EntityList_f (void)
prints a list of used - or when any param is added for all entities with following info
entnum (color red -> neverFree)
entity type OR event OR freed
classname
neverFree
Definition at line 578 of file g_svcmds.c.
static void Svcmd_Fling (void) static
Svcmd_Fling.
Definition at line 1668 of file g_svcmds.c.
void Svcmd_ForceTeam_f (void)
Svcmd_ForceTeam_f.
forceteam <player> <team>
Definition at line 786 of file g_svcmds.c.
static void Svcmd_Freeze (void) static
freeze command - freezes players
Todo:
: usage
Definition at line 1321 of file g_svcmds.c.
static void Svcmd_Gib (void) static
Gib command - based on shrubbot.
Definition at line 1090 of file g_svcmds.c.
static void Svcmd_Kick_f (void) static
kick a user off of the server
Definition at line 1784 of file g_svcmds.c.
static void Svcmd_KickNum_f (void) static
kick a user off of the server
Definition at line 1917 of file g_svcmds.c.
void Svcmd_ListCampaigns_f (void)
Svcmd_ListCampaigns_f.
Definition at line 1017 of file g_svcmds.c.
void Svcmd_ListIp_f (void)
Svcmd_ListIp_f.
Definition at line 462 of file g_svcmds.c.
static void Svcmd_Pip (void) static
pip command - pips players
Todo:
: usage
Definition at line 1591 of file g_svcmds.c.
void Svcmd_Ref_f (void)
Svcmd_Ref_f.
Definition at line 2467 of file g_svcmds.c.
void Svcmd_RemoveIP_f (void)
Svcmd_RemoveIP_f.
Definition at line 424 of file g_svcmds.c.
void Svcmd_ResetMatch (void)
Svcmd_ResetMatch.
Definition at line 863 of file g_svcmds.c.
void Svcmd_ResetMatch_f (qboolean fDoReset, qboolean fDoRestart)
Multi-use now for both map restarts and total match resets.
Parameters
[in] fDoReset
[in] fDoRestart
Definition at line 839 of file g_svcmds.c.
Referenced by G_Map_v(), G_MapRestart_v(), G_MatchReset_v(), Svcmd_ResetMatch(), Svcmd_ShuffleTeamsXP_f(), Svcmd_ShuffleTeamsXPNoRestart(), and Svcmd_SwapTeams_f().
void Svcmd_RevivePlayer (void)
Svcmd_RevivePlayer.
Parameters
[in] name
Definition at line 1056 of file g_svcmds.c.
qboolean Svcmd_Say_f (void)
Svcmd_Say_f.
Definition at line 2487 of file g_svcmds.c.
Referenced by ConsoleCommand().
void Svcmd_ShuffleTeamsXP (void)
Svcmd_ShuffleTeamsXP.
Definition at line 918 of file g_svcmds.c.
void Svcmd_ShuffleTeamsXP_f (qboolean restart)
randomly places players on teams
Parameters
[in] restart
Definition at line 893 of file g_svcmds.c.
Referenced by G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), Svcmd_ShuffleTeamsXP(), and Svcmd_ShuffleTeamsXPNoRestart().
void Svcmd_ShuffleTeamsXPNoRestart (void)
Svcmd_ShuffleTeamsXPNoRestart.
Definition at line 926 of file g_svcmds.c.
void Svcmd_StartMatch_f (void)
starts match if in tournament mode
Definition at line 807 of file g_svcmds.c.
void Svcmd_SwapTeams_f (void)
swaps all clients to opposite team
Definition at line 871 of file g_svcmds.c.
Referenced by G_SwapTeams_v().
static void Svcmd_Unfreeze (void) static
unfreeze command - unfreezes players
Todo:
: usage
Definition at line 1407 of file g_svcmds.c.
static void UpdateIPBans (ipFilterList_t * ipFilterList) static
UpdateIPBans.
Parameters
[in] ipFilterList
Definition at line 163 of file g_svcmds.c.
Referenced by AddIP(), and Svcmd_RemoveIP_f().
Variable Documentation
consoleCommandTable static
Store common console command.
Definition at line 2514 of file g_svcmds.c.
Referenced by ConsoleCommand().
const char* enttypenames[]
Definition at line 487 of file g_svcmds.c.
Referenced by Svcmd_EntityList_f().
ipGUID_t guidMaxLivesFilters[MAX_IPFILTERS] static
Definition at line 97 of file g_svcmds.c.
ipFilterList_t ipFilters static
Definition at line 94 of file g_svcmds.c.
ipFilterList_t ipMaxLivesFilters static
Definition at line 95 of file g_svcmds.c.
int numMaxLivesFilters = 0 static
Definition at line 98 of file g_svcmds.c.
Referenced by AddMaxLivesGUID(), ClearMaxLivesBans(), G_FilterMaxLivesPacket(), and PrintMaxLivesGUID().