ET: Legacy: src/game/g_script_actions.c File Reference
g_script_actions.c File Reference
Wolfenstein Entity Scripting.
#include "../game/g_local.h"
#include "../qcommon/q_shared.h"
#include "g_etbot_interface.h"
Functions
void script_linkentity (gentity_t *ent)
script_linkentity
qboolean G_ScriptAction_SetModelFromBrushmodel (gentity_t *ent, char *params)
G_ScriptAction_SetModelFromBrushmodel.
qboolean G_ScriptAction_SetPosition (gentity_t *ent, char *params)
G_ScriptAction_SetPosition.
qboolean G_ScriptAction_SetAutoSpawn (gentity_t *ent, char *params)
G_ScriptAction_SetAutoSpawn.
qboolean G_ScriptAction_ChangeModel (gentity_t *ent, char *params)
G_ScriptAction_ChangeModel.
qboolean G_ScriptAction_ShaderRemap (gentity_t *ent, char *params)
G_ScriptAction_ShaderRemap.
qboolean G_ScriptAction_ShaderRemapFlush (gentity_t *ent, char *params)
G_ScriptAction_ShaderRemapFlush.
qboolean G_ScriptAction_FollowPath (gentity_t *ent, char *params)
G_ScriptAction_FollowPath.
qboolean G_ScriptAction_AttatchToTrain (gentity_t *ent, char *params)
G_ScriptAction_AttatchToTrain.
qboolean G_ScriptAction_FreezeAnimation (gentity_t *ent, char *params)
G_ScriptAction_FreezeAnimation.
qboolean G_ScriptAction_UnFreezeAnimation (gentity_t *ent, char *params)
G_ScriptAction_UnFreezeAnimation.
qboolean G_ScriptAction_StartAnimation (gentity_t *ent, char *params)
G_ScriptAction_StartAnimation.
qboolean G_ScriptAction_SetSpeed (gentity_t *ent, char *params)
G_ScriptAction_SetSpeed.
qboolean G_ScriptAction_SetRotation (gentity_t *ent, char *params)
G_ScriptAction_SetRotation.
qboolean G_ScriptAction_StopRotation (gentity_t *ent, char *params)
G_ScriptAction_StopRotation.
qboolean G_ScriptAction_FollowSpline (gentity_t *ent, char *params)
G_ScriptAction_FollowSpline.
qboolean G_ScriptAction_AbortMove (gentity_t *ent, char *params)
G_ScriptAction_AbortMove.
qboolean G_ScriptAction_SetChargeTimeFactor (gentity_t *ent, char *params)
syntax: setchargetimefactor <team> <class> <factor> team: 0 = axis, 1 = allies
qboolean G_ScriptAction_SpawnRubble (gentity_t *ent, char *params)
G_ScriptAction_SpawnRubble.
qboolean G_ScriptAction_AllowTankExit (gentity_t *ent, char *params)
G_ScriptAction_AllowTankExit.
qboolean G_ScriptAction_AllowTankEnter (gentity_t *ent, char *params)
G_ScriptAction_AllowTankEnter.
qboolean G_ScriptAction_SetTankAmmo (gentity_t *ent, char *params)
G_ScriptAction_SetTankAmmo.
qboolean G_ScriptAction_AddTankAmmo (gentity_t *ent, char *params)
G_ScriptAction_AddTankAmmo.
qboolean G_ScriptAction_DisableMessage (gentity_t *ent, char *params)
G_ScriptAction_DisableMessage - obsolete function used for old bot ai.
qboolean G_ScriptAction_Kill (gentity_t *ent, char *params)
G_ScriptAction_Kill.
qboolean G_ScriptAction_SetGlobalFog (gentity_t *ent, char *params)
G_ScriptAction_SetGlobalFog.
qboolean G_ScriptAction_GotoMarker (gentity_t *ent, char *params)
G_ScriptAction_GotoMarker.
qboolean G_ScriptAction_Wait (gentity_t *ent, char *params)
G_ScriptAction_Wait.
qboolean G_ScriptAction_Trigger (gentity_t *ent, char *params)
Calls the specified trigger for the given ai character or script entity.
qboolean G_ScriptAction_PlaySound (gentity_t *ent, char *params)
Currently only allows playing on the VOICE channel, unless you use a sound script. Use the optional LOOPING paramater to attach the sound to the entities looping channel. syntax: playsound <soundname OR scriptname> [LOOPING].
qboolean G_ScriptAction_FadeAllSounds (gentity_t *ent, char *params)
Fades all sounds up or down, going from the current level to max or zero in 'time' milliseconds.
qboolean G_ScriptAction_MusicStart (gentity_t *ent, char *params)
G_ScriptAction_MusicStart.
qboolean G_ScriptAction_MusicPlay (gentity_t *ent, char *params)
G_ScriptAction_MusicPlay.
qboolean G_ScriptAction_MusicStop (gentity_t *ent, char *params)
G_ScriptAction_MusicStop.
qboolean G_ScriptAction_MusicQueue (gentity_t *ent, char *params)
G_ScriptAction_MusicQueue.
qboolean G_ScriptAction_MusicFade (gentity_t *ent, char *params)
G_ScriptAction_MusicFade.
qboolean G_ScriptAction_PlayAnim (gentity_t *ent, char *params)
G_ScriptAction_PlayAnim.
qboolean G_ScriptAction_AlertEntity (gentity_t *ent, char *params)
Modified to target multiple entities with the same targetname.
qboolean G_ScriptAction_ToggleSpeaker (gentity_t *ent, char *params)
G_ScriptAction_ToggleSpeaker.
qboolean G_ScriptAction_DisableSpeaker (gentity_t *ent, char *params)
G_ScriptAction_DisableSpeaker.
qboolean G_ScriptAction_EnableSpeaker (gentity_t *ent, char *params)
G_ScriptAction_EnableSpeaker.
qboolean G_ScriptAction_Accum (gentity_t *ent, char *params)
G_ScriptAction_Accum.
qboolean G_ScriptAction_GlobalAccum (gentity_t *ent, char *params)
G_ScriptAction_GlobalAccum.
qboolean G_ScriptAction_Print (gentity_t *ent, char *params)
Mostly for debugging purposes.
qboolean G_ScriptAction_FaceAngles (gentity_t *ent, char *params)
The entity will face the given angles, taking <duration> to get their. If the GOTOTIME is given instead of a timed duration, the duration calculated from the last gotomarker command will be used instead.
qboolean G_ScriptAction_ResetScript (gentity_t *ent, char *params)
Causes any currently running scripts to abort, in favour of the current script.
qboolean G_ScriptAction_TagConnect (gentity_t *ent, char *params)
Connect this entity onto the tag of another entity.
qboolean G_ScriptAction_Halt (gentity_t *ent, char *params)
Stop moving.
qboolean G_ScriptAction_StopSound (gentity_t *ent, char *params)
Stops any looping sounds for this entity.
qboolean G_ScriptAction_EntityScriptName (gentity_t *ent, char *params)
G_ScriptAction_EntityScriptName.
qboolean G_ScriptAction_AxisRespawntime (gentity_t *ent, char *params)
G_ScriptAction_AxisRespawntime.
qboolean G_ScriptAction_AlliedRespawntime (gentity_t *ent, char *params)
G_ScriptAction_AlliedRespawntime.
qboolean G_ScriptAction_NumberofObjectives (gentity_t *ent, char *params)
G_ScriptAction_NumberofObjectives.
qboolean G_ScriptAction_SetMainObjective (gentity_t *ent, char *params)
syntax: wm_set_main_objective <objective_targetname> <team>
qboolean G_ScriptAction_ObjectiveStatus (gentity_t *ent, char *params)
G_ScriptAction_ObjectiveStatus.
qboolean G_ScriptAction_SetDebugLevel (gentity_t *ent, char *params)
G_ScriptAction_SetDebugLevel.
qboolean G_ScriptAction_VoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_VoiceAnnounce.
qboolean G_ScriptAction_SetWinner (gentity_t *ent, char *params)
G_ScriptAction_SetWinner.
qboolean G_ScriptAction_SetDefendingTeam (gentity_t *ent, char *params)
Sets defending team for stopwatch mode.
qboolean G_ScriptAction_AddTeamVoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_AddTeamVoiceAnnounce.
qboolean G_ScriptAction_RemoveTeamVoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_RemoveTeamVoiceAnnounce.
qboolean G_ScriptAction_TeamVoiceAnnounce (gentity_t *ent, char *params)
G_ScriptAction_TeamVoiceAnnounce.
qboolean G_ScriptAction_Announce_Icon (gentity_t *ent, char *params)
G_ScriptAction_Announce_Icon.
qboolean G_ScriptAction_Announce (gentity_t *ent, char *params)
G_ScriptAction_Announce.
qboolean G_ScriptAction_EndRound (gentity_t *ent, char *params)
G_ScriptAction_EndRound.
qboolean G_ScriptAction_SetRoundTimelimit (gentity_t *ent, char *params)
G_ScriptAction_SetRoundTimelimit.
qboolean G_ScriptAction_RemoveEntity (gentity_t *ent, char *params)
G_ScriptAction_RemoveEntity.
qboolean G_ScriptAction_SetDamagable (gentity_t *ent, char *params)
G_ScriptAction_SetDamagable.
qboolean G_ScriptAction_SetState (gentity_t *ent, char *params)
G_ScriptAction_SetState.
qboolean G_ScriptAction_RepairMG42 (gentity_t *ent, char *params)
G_ScriptAction_RepairMG42.
qboolean G_ScriptAction_SetHQStatus (gentity_t *ent, char *params)
G_ScriptAction_SetHQStatus.
qboolean G_ScriptAction_PrintAccum (gentity_t *ent, char *params)
Prints out the value of accum 'accumNumber'.
qboolean G_ScriptAction_PrintGlobalAccum (gentity_t *ent, char *params)
prints out the value of global accum 'globalaccumnumber'
void AutoBuildConstruction (gentity_t *constructible)
AutoBuildConstruction.
qboolean G_ScriptAction_Construct (gentity_t *ent, char *params)
G_ScriptAction_Construct.
qboolean G_ScriptAction_ConstructibleClass (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleClass.
qboolean G_ScriptAction_ConstructibleChargeBarReq (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleChargeBarReq.
qboolean G_ScriptAction_ConstructibleConstructXPBonus (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleConstructXPBonus.
qboolean G_ScriptAction_ConstructibleDestructXPBonus (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleDestructXPBonus.
qboolean G_ScriptAction_ConstructibleHealth (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleHealth.
qboolean G_ScriptAction_ConstructibleWeaponclass (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleWeaponclass.
qboolean G_ScriptAction_ConstructibleDuration (gentity_t *ent, char *params)
G_ScriptAction_ConstructibleDuration.
qboolean G_ScriptAction_Cvar (gentity_t *ent, char *params)
G_ScriptAction_Cvar.
qboolean G_ScriptAction_AbortIfWarmup (gentity_t *ent, char *params)
G_ScriptAction_AbortIfWarmup.
qboolean G_ScriptAction_AbortIfNotSinglePlayer (gentity_t *ent, char *params)
G_ScriptAction_AbortIfNotSinglePlayer.
void G_ModifyTOI (gentity_t *ent)
G_ModifyTOI.
qboolean etpro_ScriptAction_SetValues (gentity_t *ent, char *params)
etpro_ScriptAction_SetValues
qboolean G_ScriptAction_Delete (gentity_t *ent, char *params)
Delete entities that match all the criteria provided in "params".
qboolean G_ScriptAction_Create (gentity_t *ent, char *params)
Added for compatability with etpro map scripts.
Variables
field_t fields []
Detailed Description
Wolfenstein Entity Scripting.
Author
Ridah
Contains the code to handle the various commands available with an event script. These functions will return true if the action has been performed, and the script should proceed to the next item on the list.
Definition in file g_script_actions.c.
Function Documentation
void AutoBuildConstruction (gentity_t * constructible)
AutoBuildConstruction.
Parameters
[in,out] constructible
Definition at line 1253 of file g_weapon.c.
Referenced by G_ScriptAction_Construct(), and G_ScriptAction_PrintGlobalAccum().
qboolean etpro_ScriptAction_SetValues (gentity_t * ent, char * params)
etpro_ScriptAction_SetValues
Ikkyo - change key/value pairs of any entity
syntax (example): set { origin "3510 -960 1280" classname "ookblat" etc etc } available fields can be found in field_t of g_spawn.c, it is quite simple to add new ones
Parameters
[in,out] ent
[in] params
Returns
Definition at line 4842 of file g_script_actions.c.
void G_ModifyTOI (gentity_t * ent)
G_ModifyTOI.
Parameters
[in,out] ent
Todo:
FIXME should we just do set stuff BEFORE actual spawning code? or add update code to entities ? (there are certainly more entities requiring update after set{})
Definition at line 4733 of file g_script_actions.c.
Referenced by etpro_ScriptAction_SetValues().
qboolean G_ScriptAction_AbortIfNotSinglePlayer (gentity_t * ent, char * params)
G_ScriptAction_AbortIfNotSinglePlayer.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 4720 of file g_script_actions.c.
qboolean G_ScriptAction_AbortIfWarmup (gentity_t * ent, char * params)
G_ScriptAction_AbortIfWarmup.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 4703 of file g_script_actions.c.
qboolean G_ScriptAction_AbortMove (gentity_t * ent, char * params)
G_ScriptAction_AbortMove.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 959 of file g_script_actions.c.
qboolean G_ScriptAction_Accum (gentity_t * ent, char * params)
G_ScriptAction_Accum.
syntax: accum <buffer_index> <command> <paramater...>
Commands:
accum <n> inc <m> accum <n> abort_if_less_than <m> accum <n> abort_if_greater_than <m> accum <n> abort_if_not_equal <m> accum <n> abort_if_equal <m> accum <n> set <m> accum <n> random <m> accum <n> bitset <m> accum <n> bitreset <m> accum <n> abort_if_bitset <m> accum <n> abort_if_not_bitset <m> accum <n> trigger_if_equal <m> <s> <t> accum <n> wait_while_equal <m>
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2418 of file g_script_actions.c.
qboolean G_ScriptAction_AddTankAmmo (gentity_t * ent, char * params)
G_ScriptAction_AddTankAmmo.
Parameters
ent - unused
[in] params
Returns
Definition at line 1221 of file g_script_actions.c.
qboolean G_ScriptAction_AddTeamVoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_AddTeamVoiceAnnounce.
syntax: wm_addteamvoiceannounce
Parameters
ent - unused
[in] params
Returns
Definition at line 3624 of file g_script_actions.c.
qboolean G_ScriptAction_AlertEntity (gentity_t * ent, char * params)
Modified to target multiple entities with the same targetname.
syntax: alertentity <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2222 of file g_script_actions.c.
qboolean G_ScriptAction_AlliedRespawntime (gentity_t * ent, char * params)
G_ScriptAction_AlliedRespawntime.
syntax: wm_allied_respawntime <seconds>
Parameters
ent - unused
[in] params
Returns
Definition at line 3275 of file g_script_actions.c.
qboolean G_ScriptAction_AllowTankEnter (gentity_t * ent, char * params)
G_ScriptAction_AllowTankEnter.
Parameters
ent - unused
[in] params
Returns
Definition at line 1154 of file g_script_actions.c.
qboolean G_ScriptAction_AllowTankExit (gentity_t * ent, char * params)
G_ScriptAction_AllowTankExit.
syntax: allowtankexit <yes|on|no|off>
Parameters
ent - unused
[in] params
Returns
Definition at line 1126 of file g_script_actions.c.
qboolean G_ScriptAction_Announce (gentity_t * ent, char * params)
G_ScriptAction_Announce.
syntax: wm_announce <"text to send to all clients">
Parameters
[in] ent
[in] params
Returns
Definition at line 3827 of file g_script_actions.c.
qboolean G_ScriptAction_Announce_Icon (gentity_t * ent, char * params)
G_ScriptAction_Announce_Icon.
syntax: wm_announce_icon <icon number> <"text to send to all clients">
Parameters
[in] ent
[in] params
Returns
Definition at line 3781 of file g_script_actions.c.
qboolean G_ScriptAction_AttatchToTrain (gentity_t * ent, char * params)
G_ScriptAction_AttatchToTrain.
Parameters
[out] ent
[in] params
Returns
Todo:
: optimize ... is this used for players?
Definition at line 447 of file g_script_actions.c.
qboolean G_ScriptAction_AxisRespawntime (gentity_t * ent, char * params)
G_ScriptAction_AxisRespawntime.
syntax: wm_axis_respawntime <seconds>
Parameters
ent - unused
[in] params
Returns
Definition at line 3246 of file g_script_actions.c.
qboolean G_ScriptAction_ChangeModel (gentity_t * ent, char * params)
G_ScriptAction_ChangeModel.
Parameters
[out] ent
[in] params
Returns
Definition at line 226 of file g_script_actions.c.
qboolean G_ScriptAction_Construct (gentity_t * ent, char * params)
G_ScriptAction_Construct.
Parameters
ent - unused
[in] params
Returns
Definition at line 4243 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleChargeBarReq (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleChargeBarReq.
syntax: constructible_chargebarreq <float:fraction>
Parameters
[in] ent
[in] params
Returns
Definition at line 4304 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleClass (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleClass.
syntax: constructible_class <int:class>
Parameters
[out] ent
params
Returns
Definition at line 4271 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleConstructXPBonus (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleConstructXPBonus.
syntax: constructible_constructxpbonus <int:xppoints>
Parameters
[out] ent
[in] params
Returns
Definition at line 4333 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleDestructXPBonus (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleDestructXPBonus.
syntax: constructible_destructxpbonus <int:xppoints>
Parameters
[out] ent
[in] params
Returns
Definition at line 4362 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleDuration (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleDuration.
syntax: constructible_duration <int:duration>
Parameters
[out] ent
[in] params
Returns
Definition at line 4451 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleHealth (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleHealth.
syntax: constructible_health <int:health>
Parameters
[out] ent
[in] params
Returns
Definition at line 4391 of file g_script_actions.c.
qboolean G_ScriptAction_ConstructibleWeaponclass (gentity_t * ent, char * params)
G_ScriptAction_ConstructibleWeaponclass.
syntax: constructible_weaponclass <int:class>
Parameters
[out] ent
[in] params
Returns
Definition at line 4421 of file g_script_actions.c.
qboolean G_ScriptAction_Create (gentity_t * ent, char * params)
Added for compatability with etpro map scripts.
Parameters
[in] ent
[in] params
Returns
Definition at line 5094 of file g_script_actions.c.
qboolean G_ScriptAction_Cvar (gentity_t * ent, char * params)
G_ScriptAction_Cvar.
syntax: cvar <cvarName> <operation> <value>
Parameters
[in,out] ent
[in] params
Returns
Todo:
: cvarValue is never read
Todo:
: cvarValue is never read
Todo:
: cvarValue is never read
Todo:
: cvarValue is never read
Definition at line 4480 of file g_script_actions.c.
qboolean G_ScriptAction_Delete (gentity_t * ent, char * params)
Delete entities that match all the criteria provided in "params".
Parameters
ent - unused
[in] params
Returns
Definition at line 4942 of file g_script_actions.c.
Referenced by _et_G_Lua_DeleteEntity().
qboolean G_ScriptAction_DisableMessage (gentity_t * ent, char * params)
G_ScriptAction_DisableMessage - obsolete function used for old bot ai.
Parameters
ent
[in] params
Returns
Definition at line 1269 of file g_script_actions.c.
qboolean G_ScriptAction_DisableSpeaker (gentity_t * ent, char * params)
G_ScriptAction_DisableSpeaker.
syntax: disablespeaker <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2321 of file g_script_actions.c.
qboolean G_ScriptAction_EnableSpeaker (gentity_t * ent, char * params)
G_ScriptAction_EnableSpeaker.
syntax: enablespeaker <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2361 of file g_script_actions.c.
qboolean G_ScriptAction_EndRound (gentity_t * ent, char * params)
G_ScriptAction_EndRound.
syntax: wm_endround <>
Parameters
ent - unused
params - unused
Returns
Definition at line 3861 of file g_script_actions.c.
qboolean G_ScriptAction_EntityScriptName (gentity_t * ent, char * params)
G_ScriptAction_EntityScriptName.
Parameters
ent - unused
[in] params
Returns
Definition at line 3231 of file g_script_actions.c.
qboolean G_ScriptAction_FaceAngles (gentity_t * ent, char * params)
The entity will face the given angles, taking <duration> to get their. If the GOTOTIME is given instead of a timed duration, the duration calculated from the last gotomarker command will be used instead.
syntax: faceangles <pitch> <yaw> <roll> <duration\/GOTOTIME> [ACCEL\/DECCEL]
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2976 of file g_script_actions.c.
qboolean G_ScriptAction_FadeAllSounds (gentity_t * ent, char * params)
Fades all sounds up or down, going from the current level to max or zero in 'time' milliseconds.
syntax: fadeallsounds [UP\/DOWN] time
Parameters
ent - unused
[in] params
Returns
Definition at line 1903 of file g_script_actions.c.
qboolean G_ScriptAction_FollowPath (gentity_t * ent, char * params)
G_ScriptAction_FollowPath.
Parameters
[in,out] ent
[in] params
Returns
Definition at line 296 of file g_script_actions.c.
qboolean G_ScriptAction_FollowSpline (gentity_t * ent, char * params)
G_ScriptAction_FollowSpline.
syntax: followspline <targetname> <speed> [wait]
Parameters
[in,out] ent
[in] params
Returns
Note
Speed may be modified to round the duration to the next 50ms for smooth transitions
Definition at line 731 of file g_script_actions.c.
qboolean G_ScriptAction_FreezeAnimation (gentity_t * ent, char * params)
G_ScriptAction_FreezeAnimation.
Parameters
[out] ent
params - unused
Returns
Definition at line 487 of file g_script_actions.c.
qboolean G_ScriptAction_GlobalAccum (gentity_t * ent, char * params)
G_ScriptAction_GlobalAccum.
syntax: globalAccum <buffer_index> <command> <paramater...>
Commands:
globalAccum <n> inc <m> globalAccum <n> abort_if_less_than <m> globalAccum <n> abort_if_greater_than <m> globalAccum <n> abort_if_not_equal <m> globalAccum <n> abort_if_equal <m> globalAccum <n> set <m> globalAccum <n> random <m> globalAccum <n> bitset <m> globalAccum <n> bitreset <m> globalAccum <n> abort_if_bitset <m> globalAccum <n> abort_if_not_bitset <m> globalAccum <n> trigger_if_equal <m> <s> <t> globalAccum <n> wait_while_equal <m>
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2702 of file g_script_actions.c.
qboolean G_ScriptAction_GotoMarker (gentity_t * ent, char * params)
G_ScriptAction_GotoMarker.
syntax: gotomarker <targetname> <speed> [accel\/deccel] [turntotarget] [wait] [relative <position>]
Parameters
[in,out] ent
[in] params
Returns
Note
Speed may be modified to round the duration to the next 50ms for smooth transitions
Todo:
: optimize ... is this used for players?
Todo:
: optimize ... is this used for players?
Definition at line 1376 of file g_script_actions.c.
Referenced by G_Script_ScriptRun().
qboolean G_ScriptAction_Halt (gentity_t * ent, char * params)
Stop moving.
syntax: halt
Parameters
[in,out] ent
params - unused
Returns
Definition at line 3178 of file g_script_actions.c.
qboolean G_ScriptAction_Kill (gentity_t * ent, char * params)
G_ScriptAction_Kill.
Parameters
[in] ent
[in] params
Returns
Definition at line 1297 of file g_script_actions.c.
qboolean G_ScriptAction_MusicFade (gentity_t * ent, char * params)
G_ScriptAction_MusicFade.
Parameters
ent - unused
[in] params
Returns
Definition at line 2050 of file g_script_actions.c.
qboolean G_ScriptAction_MusicPlay (gentity_t * ent, char * params)
G_ScriptAction_MusicPlay.
Parameters
ent - unused
[in] params
Returns
Definition at line 1981 of file g_script_actions.c.
qboolean G_ScriptAction_MusicQueue (gentity_t * ent, char * params)
G_ScriptAction_MusicQueue.
Parameters
ent - unused
[in] params
Returns
Definition at line 2027 of file g_script_actions.c.
qboolean G_ScriptAction_MusicStart (gentity_t * ent, char * params)
G_ScriptAction_MusicStart.
Parameters
ent - unused
[in] params
Returns
See also
GS Copied in code from old source for mu_start, mu_play & mu_stop
Definition at line 1951 of file g_script_actions.c.
qboolean G_ScriptAction_MusicStop (gentity_t * ent, char * params)
G_ScriptAction_MusicStop.
Parameters
ent - unused
[in] params
Returns
Definition at line 2005 of file g_script_actions.c.
qboolean G_ScriptAction_NumberofObjectives (gentity_t * ent, char * params)
G_ScriptAction_NumberofObjectives.
syntax: wm_number_of_objectives <number>
Parameters
ent - unused
[in] params
Returns
Definition at line 3304 of file g_script_actions.c.
qboolean G_ScriptAction_ObjectiveStatus (gentity_t * ent, char * params)
G_ScriptAction_ObjectiveStatus.
syntax: wm_objective_status <objective_number> <team> <status>
Parameters
[in] ent
[in] params
Returns
Definition at line 3394 of file g_script_actions.c.
qboolean G_ScriptAction_PlayAnim (gentity_t * ent, char * params)
G_ScriptAction_PlayAnim.
syntax: playanim <startframe> <endframe> [looping <FOREVER\/duration>] [rate <FPS>]
Parameters
[in,out] ent
[in] params
Returns
Note
All source animations must be at 20fps
Definition at line 2088 of file g_script_actions.c.
Referenced by G_Script_ScriptRun().
qboolean G_ScriptAction_PlaySound (gentity_t * ent, char * params)
Currently only allows playing on the VOICE channel, unless you use a sound script. Use the optional LOOPING paramater to attach the sound to the entities looping channel. syntax: playsound <soundname OR scriptname> [LOOPING].
Parameters
[in,out] ent
[in] params
Returns
Definition at line 1839 of file g_script_actions.c.
qboolean G_ScriptAction_Print (gentity_t * ent, char * params)
Mostly for debugging purposes.
syntax: print <text>
Parameters
[in,out] ent
[in] params
Returns
Definition at line 2930 of file g_script_actions.c.
qboolean G_ScriptAction_PrintAccum (gentity_t * ent, char * params)
Prints out the value of accum 'accumNumber'.
syntax: printaccum <accumNumber>
Parameters
[in] ent
[in] params
Returns
Definition at line 4173 of file g_script_actions.c.
qboolean G_ScriptAction_PrintGlobalAccum (gentity_t * ent, char * params)
prints out the value of global accum 'globalaccumnumber'
syntax: printGlobalAccum <globalaccumnumber>
Parameters
ent - unused
[in] params
Returns
Definition at line 4208 of file g_script_actions.c.
qboolean G_ScriptAction_RemoveEntity (gentity_t * ent, char * params)
G_ScriptAction_RemoveEntity.
syntax: remove
Parameters
[out] ent
params - unused
Returns
Definition at line 3932 of file g_script_actions.c.
qboolean G_ScriptAction_RemoveTeamVoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_RemoveTeamVoiceAnnounce.
Parameters
ent - unused
[in] params
Returns
Definition at line 3683 of file g_script_actions.c.
qboolean G_ScriptAction_RepairMG42 (gentity_t * ent, char * params)
G_ScriptAction_RepairMG42.
syntax: repairmg42 <target>
Parameters
[in] ent
[in] params
Returns
Definition at line 4064 of file g_script_actions.c.
qboolean G_ScriptAction_ResetScript (gentity_t * ent, char * params)
Causes any currently running scripts to abort, in favour of the current script.
Parameters
[in] ent
params - unused
Returns
Definition at line 3110 of file g_script_actions.c.
qboolean G_ScriptAction_SetAutoSpawn (gentity_t * ent, char * params)
G_ScriptAction_SetAutoSpawn.
Parameters
ent - unused
[in] params
Returns
Definition at line 177 of file g_script_actions.c.
qboolean G_ScriptAction_SetChargeTimeFactor (gentity_t * ent, char * params)
syntax: setchargetimefactor <team> <class> <factor> team: 0 = axis, 1 = allies
Parameters
ent - unused
[in] params
Returns
Definition at line 993 of file g_script_actions.c.
qboolean G_ScriptAction_SetDamagable (gentity_t * ent, char * params)
G_ScriptAction_SetDamagable.
Parameters
ent - unused
[in] params
Returns
Definition at line 3946 of file g_script_actions.c.
qboolean G_ScriptAction_SetDebugLevel (gentity_t * ent, char * params)
G_ScriptAction_SetDebugLevel.
Parameters
ent - unused
[in] params
Returns
Definition at line 3461 of file g_script_actions.c.
qboolean G_ScriptAction_SetDefendingTeam (gentity_t * ent, char * params)
Sets defending team for stopwatch mode.
syntax: wm_set_objective_status <status> status: 0==axis, 1==allies
Parameters
ent - unused
[in] params
Returns
Definition at line 3585 of file g_script_actions.c.
qboolean G_ScriptAction_SetGlobalFog (gentity_t * ent, char * params)
G_ScriptAction_SetGlobalFog.
syntax: setglobalfog <bool:restore> <int:duration> [float:r] [float:g] [float:b] [float:depthForOpaque]
Parameters
ent - unused
[in] params
Returns
Definition at line 1319 of file g_script_actions.c.
Referenced by _et_G_SetGlobalFog().
qboolean G_ScriptAction_SetHQStatus (gentity_t * ent, char * params)
G_ScriptAction_SetHQStatus.
syntax: sethqstatus <team> <status>
Parameters
ent - unused
[in] params
Returns
Definition at line 4122 of file g_script_actions.c.
qboolean G_ScriptAction_SetMainObjective (gentity_t * ent, char * params)
syntax: wm_set_main_objective <objective_targetname> <team>
Parameters
ent - unused
params
Returns
true or aborts
Todo:
check for param is number to distinguish between old and new wm_set_main_objective cmd - throw next commented G_Error
Todo:
throw this if we can't find the target by name
Definition at line 3338 of file g_script_actions.c.
qboolean G_ScriptAction_SetModelFromBrushmodel (gentity_t * ent, char * params)
G_ScriptAction_SetModelFromBrushmodel.
Parameters
[out] ent
[in] params
Returns
Definition at line 56 of file g_script_actions.c.
qboolean G_ScriptAction_SetPosition (gentity_t * ent, char * params)
G_ScriptAction_SetPosition.
Parameters
[in] ent
[in] params
Returns
Todo:
: optimize ... is this used for players?
Definition at line 135 of file g_script_actions.c.
qboolean G_ScriptAction_SetRotation (gentity_t * ent, char * params)
G_ScriptAction_SetRotation.
Parameters
[in,out] ent
[in] params
Returns
Definition at line 675 of file g_script_actions.c.
qboolean G_ScriptAction_SetRoundTimelimit (gentity_t * ent, char * params)
G_ScriptAction_SetRoundTimelimit.
syntax: wm_set_round_timelimit <number>
Parameters
ent - unused
[in] params
Returns
Definition at line 3880 of file g_script_actions.c.
qboolean G_ScriptAction_SetSpeed (gentity_t * ent, char * params)
G_ScriptAction_SetSpeed.
Parameters
[in,out] ent
[in] params
Returns
Definition at line 614 of file g_script_actions.c.
qboolean G_ScriptAction_SetState (gentity_t * ent, char * params)
G_ScriptAction_SetState.
syntax: remove
Parameters
ent - unused
[in] params
Returns
Definition at line 3985 of file g_script_actions.c.
qboolean G_ScriptAction_SetTankAmmo (gentity_t * ent, char * params)
G_ScriptAction_SetTankAmmo.
Parameters
ent - unused
[in] params
Returns
Definition at line 1182 of file g_script_actions.c.
qboolean G_ScriptAction_SetWinner (gentity_t * ent, char * params)
G_ScriptAction_SetWinner.
syntax: wm_setwinner <team> team: 0==AXIS, 1==ALLIED
Parameters
ent - unused
[in] params
Returns
Todo:
: never read
Definition at line 3540 of file g_script_actions.c.
qboolean G_ScriptAction_ShaderRemap (gentity_t * ent, char * params)
G_ScriptAction_ShaderRemap.
Parameters
ent - unused
[in] params
Returns
Definition at line 252 of file g_script_actions.c.
qboolean G_ScriptAction_ShaderRemapFlush (gentity_t * ent, char * params)
G_ScriptAction_ShaderRemapFlush.
Parameters
ent - unused
params - unused
Returns
Definition at line 284 of file g_script_actions.c.
qboolean G_ScriptAction_SpawnRubble (gentity_t * ent, char * params)
G_ScriptAction_SpawnRubble.
Debris test
syntax: spawnrubble <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 1100 of file g_script_actions.c.
qboolean G_ScriptAction_StartAnimation (gentity_t * ent, char * params)
G_ScriptAction_StartAnimation.
Parameters
[out] ent
[in] params
Returns
Definition at line 513 of file g_script_actions.c.
qboolean G_ScriptAction_StopRotation (gentity_t * ent, char * params)
G_ScriptAction_StopRotation.
Parameters
[in,out] ent
params - unused
Returns
Definition at line 710 of file g_script_actions.c.
qboolean G_ScriptAction_StopSound (gentity_t * ent, char * params)
Stops any looping sounds for this entity.
syntax: stopsound
Parameters
ent
params
Returns
Definition at line 3219 of file g_script_actions.c.
qboolean G_ScriptAction_TagConnect (gentity_t * ent, char * params)
Connect this entity onto the tag of another entity.
syntax: attachtotag <targetname\/scriptname> <tagname>
Parameters
[out] ent
[in] params
Returns
Todo:
: optimize ... is this used for players?
Definition at line 3127 of file g_script_actions.c.
qboolean G_ScriptAction_TeamVoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_TeamVoiceAnnounce.
syntax: wm_teamvoiceannounce <team> <soundname>
Parameters
[in] ent
[in] params
Returns
Definition at line 3730 of file g_script_actions.c.
qboolean G_ScriptAction_ToggleSpeaker (gentity_t * ent, char * params)
G_ScriptAction_ToggleSpeaker.
syntax: togglespeaker <targetname>
Parameters
ent - unused
[in] params
Returns
Definition at line 2281 of file g_script_actions.c.
qboolean G_ScriptAction_Trigger (gentity_t * ent, char * params)
Calls the specified trigger for the given ai character or script entity.
syntax: trigger <aiName\/scriptName> <trigger>
Parameters
[in] ent
[in] params
Returns
Definition at line 1707 of file g_script_actions.c.
qboolean G_ScriptAction_UnFreezeAnimation (gentity_t * ent, char * params)
G_ScriptAction_UnFreezeAnimation.
Parameters
[out] ent
params - unused
Returns
Definition at line 500 of file g_script_actions.c.
qboolean G_ScriptAction_VoiceAnnounce (gentity_t * ent, char * params)
G_ScriptAction_VoiceAnnounce.
Parameters
ent - unused
[in] params
Returns
Definition at line 3493 of file g_script_actions.c.
qboolean G_ScriptAction_Wait (gentity_t * ent, char * params)
G_ScriptAction_Wait.
syntax: wait <duration> wait random <min> <max>
Parameters
[in] ent
[in] params
Returns
Definition at line 1652 of file g_script_actions.c.
void script_linkentity (gentity_t * ent)
script_linkentity
Parameters
[in] ent
Definition at line 925 of file g_script.c.
Referenced by G_ScriptAction_AbortMove(), G_ScriptAction_FaceAngles(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GotoMarker(), G_ScriptAction_Halt(), G_ScriptAction_SetRotation(), G_ScriptAction_SetSpeed(), and script_mover_spawn().
Variable Documentation
field_t fields[]
Definition at line 153 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues().