ET: Legacy: src/game/g_stats.c File Reference
g_stats.c File Reference
#include "g_local.h"
#include "g_lua.h"
Functions
void G_LogDeath (gentity_t *ent, weapon_t weap)
G_LogDeath.
void G_LogKill (gentity_t *ent, weapon_t weap)
G_LogKill.
void G_LogTeamKill (gentity_t *ent, weapon_t weap)
G_LogTeamKill.
void G_LogRegionHit (gentity_t *ent, hitRegion_t hr)
G_LogRegionHit.
void G_PrintAccuracyLog (gentity_t *ent)
G_PrintAccuracyLog.
void G_SetPlayerScore (gclient_t *client)
G_SetPlayerScore.
void G_SetPlayerSkill (gclient_t *client, skillType_t skill)
G_SetPlayerSkill.
void AddWeaponToPlayer (gclient_t *client, weapon_t weapon, int ammo, int ammoclip, qboolean setcurrent)
AddWeaponToPlayer.
void G_UpgradeSkill (gentity_t *ent, skillType_t skill)
Local func to actual do skill upgrade, used by both MP skill system, and SP scripted skill system.
void G_LoseSkillPoints (gentity_t *ent, skillType_t skill, float points)
G_LoseSkillPoints.
void G_ResetXP (gentity_t *ent)
G_ResetXP.
void G_AddSkillPoints (gentity_t *ent, skillType_t skill, float points)
G_AddSkillPoints.
void G_LoseKillSkillPoints (gentity_t *tker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
Loose skill for evil tkers :E.
void G_AddKillSkillPoints (gentity_t *attacker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
G_AddKillSkillPoints.
void G_AddKillSkillPointsForDestruction (gentity_t *attacker, meansOfDeath_t mod, g_constructible_stats_t *constructibleStats)
G_AddKillSkillPointsForDestruction.
void G_DebugOpenSkillLog (void)
G_DebugOpenSkillLog.
void G_DebugCloseSkillLog (void)
G_DebugCloseSkillLog.
void G_DebugAddSkillLevel (gentity_t *ent, skillType_t skill)
G_DebugAddSkillLevel.
void G_DebugAddSkillPoints (gentity_t *ent, skillType_t skill, float points, const char *reason)
G_DebugAddSkillPoints.
void G_BuildEndgameStats (void)
send name, team and value when there is a winner - else empty string and TEAM_FREE = 0 (client structure is only used for awards!)
Variables
static fileHandle_t skillDebugLog = -1
Function Documentation
void AddWeaponToPlayer (gclient_t * client, weapon_t weapon, int ammo, int ammoclip, qboolean setcurrent)
AddWeaponToPlayer.
Parameters
[in,out] client
[in] weapon
[in] ammo
[in] ammoclip
[in] setcurrent
Definition at line 1090 of file g_client.c.
Referenced by G_SetPlayerSkill(), G_UpgradeSkill(), and SetWolfSpawnWeapons().
void G_AddKillSkillPoints (gentity_t * attacker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
G_AddKillSkillPoints.
Parameters
[in] attacker
[in] mod
[in] hr
[in] splash
Definition at line 489 of file g_stats.c.
Referenced by G_Damage().
void G_AddKillSkillPointsForDestruction (gentity_t * attacker, meansOfDeath_t mod, g_constructible_stats_t * constructibleStats)
G_AddKillSkillPointsForDestruction.
Parameters
[in] attacker
[in] mod
[in] constructibleStats
Definition at line 548 of file g_stats.c.
Referenced by func_constructible_explode(), func_explosive_explode(), G_KillEnts(), and G_RealExplodedMissile().
void G_AddSkillPoints (gentity_t * ent, skillType_t skill, float points)
G_AddSkillPoints.
Parameters
[in,out] ent
[in] skill
[in] points
Definition at line 413 of file g_stats.c.
Referenced by _et_G_AddSkillPoints(), ClientThink_real(), Cmd_Give_f(), Do_Activate2_f(), G_AddKillSkillPoints(), G_AddKillSkillPointsForDestruction(), G_CheckSpottedLandMines(), Pickup_Health(), Pickup_Weapon(), TryConstructing(), Weapon_Engineer(), and Weapon_Syringe().
void G_BuildEndgameStats (void)
send name, team and value when there is a winner - else empty string and TEAM_FREE = 0 (client structure is only used for awards!)
connectedClients have a team but keep the check for TEAM_FREE ... we'll never know for sure, connectedClients are determined in CalculateRanks
Definition at line 681 of file g_stats.c.
Referenced by G_LogExit().
void G_DebugAddSkillLevel (gentity_t * ent, skillType_t skill)
G_DebugAddSkillLevel.
Parameters
[in] ent
[in] skill
Definition at line 622 of file g_stats.c.
Referenced by G_UpgradeSkill().
void G_DebugAddSkillPoints (gentity_t * ent, skillType_t skill, float points, const char * reason)
G_DebugAddSkillPoints.
Parameters
[in] ent
[in] skill
[in] points
[in] reason
Definition at line 652 of file g_stats.c.
Referenced by ClientThink_real(), Cmd_Give_f(), Do_Activate2_f(), G_AddKillSkillPoints(), G_AddKillSkillPointsForDestruction(), G_CheckSpottedLandMines(), Pickup_Health(), Pickup_Weapon(), TryConstructing(), Weapon_Engineer(), and Weapon_Syringe().
void G_DebugCloseSkillLog (void)
G_DebugCloseSkillLog.
Definition at line 598 of file g_stats.c.
Referenced by G_ShutdownGame().
void G_DebugOpenSkillLog (void)
G_DebugOpenSkillLog.
Definition at line 567 of file g_stats.c.
Referenced by G_InitGame().
void G_LogDeath (gentity_t * ent, weapon_t weap)
G_LogDeath.
Parameters
[in,out] ent
[in] weap
Definition at line 46 of file g_stats.c.
Referenced by player_die().
void G_LogKill (gentity_t * ent, weapon_t weap)
G_LogKill.
Parameters
[in,out] ent
[in] weap
Definition at line 61 of file g_stats.c.
Referenced by player_die().
void G_LogRegionHit (gentity_t * ent, hitRegion_t hr)
G_LogRegionHit.
Parameters
[in,out] ent
[in] hr
Definition at line 91 of file g_stats.c.
Referenced by G_Damage().
void G_LogTeamKill (gentity_t * ent, weapon_t weap)
G_LogTeamKill.
Parameters
[in,out] ent
[in] weap
Definition at line 76 of file g_stats.c.
Referenced by player_die().
void G_LoseKillSkillPoints (gentity_t * tker, meansOfDeath_t mod, hitRegion_t hr, qboolean splash)
Loose skill for evil tkers :E.
Parameters
[in] tker
[in] mod
hr - unused
splash - unused
Definition at line 466 of file g_stats.c.
Referenced by Cmd_Vote_f().
void G_LoseSkillPoints (gentity_t * ent, skillType_t skill, float points)
G_LoseSkillPoints.
Parameters
[in,out] ent
[in] skill
[in] points
Definition at line 285 of file g_stats.c.
Referenced by _et_G_LoseSkillPoints(), and G_LoseKillSkillPoints().
void G_PrintAccuracyLog (gentity_t * ent)
G_PrintAccuracyLog.
Parameters
[in] ent
Definition at line 104 of file g_stats.c.
Referenced by ClientCommand(), and Cmd_SetSpawnPoint_f().
void G_ResetXP (gentity_t * ent)
G_ResetXP.
Parameters
[in,out] ent
Definition at line 336 of file g_stats.c.
Referenced by _et_G_ResetXP().
void G_SetPlayerScore (gclient_t * client)
G_SetPlayerScore.
Parameters
[in,out] client
Definition at line 146 of file g_stats.c.
Referenced by G_SetPlayerSkill().
void G_SetPlayerSkill (gclient_t * client, skillType_t skill)
G_SetPlayerSkill.
Parameters
[in,out] client
[in] skill
Definition at line 161 of file g_stats.c.
Referenced by G_AddSkillPoints(), G_CalcRank(), G_LoseSkillPoints(), and G_UpdateCvars().
void G_UpgradeSkill (gentity_t * ent, skillType_t skill)
Local func to actual do skill upgrade, used by both MP skill system, and SP scripted skill system.
Parameters
[in,out] ent
[in] skill
Definition at line 192 of file g_stats.c.
Referenced by G_AddSkillPoints(), and G_UpdateCvars().
Variable Documentation
fileHandle_t skillDebugLog = -1 static
Definition at line 562 of file g_stats.c.
Referenced by G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DebugCloseSkillLog(), and G_DebugOpenSkillLog().