ET: Legacy: src/game/g_syscalls.c File Reference
g_syscalls.c File Reference
#include "g_local.h"
Functions
static intptr_t (QDECL *syscall)(intptr_t arg
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
dllEntry
int PASSFLOAT (float x)
PASSFLOAT.
void trap_Printf (const char *fmt)
trap_Printf
void trap_Error (const char *fmt)
trap_Error
int trap_Milliseconds (void)
trap_Milliseconds
int trap_Argc (void)
trap_Argc
void trap_Argv (int n, char *buffer, int bufferLength)
trap_Argv
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
trap_FS_FOpenFile
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
trap_FS_Read
int trap_FS_Write (const void *buffer, int len, fileHandle_t f)
trap_FS_Write
int trap_FS_Rename (const char *from, const char *to)
trap_FS_Rename
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
trap_FS_GetFileList
void trap_SendConsoleCommand (int exec_when, const char *text)
trap_SendConsoleCommand
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
trap_Cvar_Register
void trap_Cvar_Update (vmCvar_t *vmCvar)
trap_Cvar_Update
void trap_Cvar_Set (const char *varName, const char *value)
trap_Cvar_Set
int trap_Cvar_VariableIntegerValue (const char *varName)
trap_Cvar_VariableIntegerValue
void trap_Cvar_VariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_VariableStringBuffer
void trap_Cvar_LatchedVariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
void trap_LocateGameData (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *gameClients, int sizeofGClient)
trap_LocateGameData
void trap_DropClient (int clientNum, const char *reason, int length)
trap_DropClient
void trap_SendServerCommand (int clientNum, const char *text)
trap_SendServerCommand
void trap_SetConfigstring (int num, const char *string)
trap_SetConfigstring
void trap_GetConfigstring (int num, char *buffer, int bufferSize)
trap_GetConfigstring
void trap_GetUserinfo (int num, char *buffer, int bufferSize)
trap_GetUserinfo
void trap_SetUserinfo (int num, const char *buffer)
trap_SetUserinfo
void trap_GetServerinfo (char *buffer, int bufferSize)
trap_GetServerinfo
void trap_SetBrushModel (gentity_t *ent, const char *name)
trap_SetBrushModel
void trap_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_Trace
void trap_TraceNoEnts (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceNoEnts
void trap_TraceCapsule (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsule
void trap_TraceCapsuleNoEnts (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsuleNoEnts
int trap_PointContents (const vec3_t point, int passEntityNum)
trap_PointContents
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
trap_InPVS
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
trap_InPVSIgnorePortals
void trap_AdjustAreaPortalState (gentity_t *ent, qboolean open)
trap_AdjustAreaPortalState
qboolean trap_AreasConnected (int area1, int area2)
trap_AreasConnected
void trap_LinkEntity (gentity_t *ent)
trap_LinkEntity
void trap_UnlinkEntity (gentity_t *ent)
trap_UnlinkEntity
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int *list, int maxCount)
trap_EntitiesInBox
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
trap_EntityContact
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
int trap_BotAllocateClient (int clientNum)
trap_BotAllocateClient
int trap_BotGetServerCommand (int clientNum, char *message, int size)
trap_BotGetServerCommand
void trap_BotUserCommand (int clientNum, usercmd_t *ucmd)
trap_BotUserCommand
void trap_EA_Command (int clientNum, char *command)
trap_EA_Command
int trap_GetSoundLength (sfxHandle_t sfxHandle)
trap_GetSoundLength
sfxHandle_t trap_RegisterSound (const char *sample, qboolean compressed)
trap_RegisterSound
void trap_GetUsercmd (int clientNum, usercmd_t *cmd)
trap_GetUsercmd
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
trap_GetEntityToken
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
trap_DebugPolygonCreate
void trap_DebugPolygonDelete (int id)
trap_DebugPolygonDelete
int trap_RealTime (qtime_t *qtime)
trap_RealTime
void trap_SnapVector (float *v)
trap_SnapVector
qboolean trap_GetTag (int clientNum, int tagFileNumber, char *tagName, orientation_t *orientation)
trap_GetTag
qboolean trap_LoadTag (const char *filename)
trap_LoadTag
int trap_PC_AddGlobalDefine (char *define)
trap_PC_AddGlobalDefine
int trap_PC_LoadSource (const char *filename)
trap_PC_LoadSource
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
trap_PC_ReadToken
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
trap_PC_SourceFileAndLine
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
qboolean trap_SendMessage (int clientNum, char *buf, int buflen)
Sends binary messages. Since ETL 2.76 this is no longer void. See new return values.
messageStatus_t trap_MessageStatus (int clientNum)
trap_MessageStatus
Function Documentation
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
dllEntry
Definition at line 42 of file g_syscalls.c.
static intptr_t (QDECL * syscall) static
int PASSFLOAT (float x)
PASSFLOAT.
Parameters
[in] x
Returns
Definition at line 52 of file g_syscalls.c.
void trap_AdjustAreaPortalState (gentity_t * ent, qboolean open)
trap_AdjustAreaPortalState
Parameters
[in] ent
[in] open
Definition at line 453 of file g_syscalls.c.
Referenced by Reached_BinaryMover(), Reached_TrinaryMover(), Use_BinaryMover(), and Use_TrinaryMover().
qboolean trap_AreasConnected (int area1, int area2)
trap_AreasConnected
Parameters
[in] area1
[in] area2
Returns
Definition at line 464 of file g_syscalls.c.
int trap_Argc (void)
trap_Argc
Returns
Definition at line 93 of file g_syscalls.c.
void trap_Argv (int n, char * buffer, int bufferLength)
trap_Argv
Parameters
[in] n
[out] buffer
[in] bufferLength
Definition at line 104 of file g_syscalls.c.
int trap_BotAllocateClient (int clientNum)
trap_BotAllocateClient
Todo:
: precompiler macros for engine ?
Parameters
[in] clientNum
Returns
Definition at line 524 of file g_syscalls.c.
Referenced by ETInterface::AddBot().
int trap_BotGetServerCommand (int clientNum, char * message, int size)
trap_BotGetServerCommand
Parameters
[in] clientNum
[out] message
[in] size
Returns
Definition at line 536 of file g_syscalls.c.
Referenced by Bot_Interface_Update().
void trap_BotUserCommand (int clientNum, usercmd_t * ucmd)
trap_BotUserCommand
Parameters
[in] clientNum
[in] ucmd
Definition at line 546 of file g_syscalls.c.
Referenced by ETInterface::UpdateBotInput().
void trap_Cvar_LatchedVariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
Definition at line 245 of file g_syscalls.c.
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
trap_Cvar_Register
Parameters
[in] vmCvar
[in] varName
[in] defaultValue
[in] flags
Definition at line 194 of file g_syscalls.c.
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 213 of file g_syscalls.c.
void trap_Cvar_Update (vmCvar_t * vmCvar)
trap_Cvar_Update
Parameters
[in] vmCvar
Definition at line 203 of file g_syscalls.c.
int trap_Cvar_VariableIntegerValue (const char * varName)
trap_Cvar_VariableIntegerValue
Parameters
[in] varName
Returns
Definition at line 223 of file g_syscalls.c.
Referenced by G_FreeEntity(), G_players_cmd(), G_Script_ScriptParse(), G_ScriptAction_Cvar(), G_voteFlags(), and ETInterface::InterfaceSendMessage().
void trap_Cvar_VariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_VariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
Definition at line 234 of file g_syscalls.c.
Referenced by trap_GetUsercmd().
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
trap_DebugPolygonCreate
Parameters
[in] color
[in] numPoints
[in] points
Returns
Definition at line 669 of file g_syscalls.c.
Referenced by DebugLine().
void trap_DebugPolygonDelete (int id)
trap_DebugPolygonDelete
Parameters
[in] id
Definition at line 678 of file g_syscalls.c.
void trap_DropClient (int clientNum, const char * reason, int length)
trap_DropClient
Parameters
[in] clientNum
[in] reason
[in] length
Definition at line 270 of file g_syscalls.c.
Referenced by _et_trap_DropClient(), ClientInactivityTimer(), ClientUserinfoChanged(), Cmd_Vote_f(), ETInterface::RemoveBot(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
void trap_EA_Command (int clientNum, char * command)
trap_EA_Command
Parameters
[in] clientNum
[in] command
Definition at line 556 of file g_syscalls.c.
Referenced by ETInterface::BotCommand(), and ETInterface::InterfaceSendMessage().
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int * list, int maxCount)
trap_EntitiesInBox
Parameters
[in] mins
[in] maxs
[out] list
[in] maxCount
Returns
Definition at line 495 of file g_syscalls.c.
Referenced by EntsThatRadiusCanDamage(), etpro_RadiusDamage(), func_constructible_explode(), G_FlameDamage(), G_LandmineThink(), G_MoverPush(), G_RadiusDamage(), G_RealExplodedMissile(), G_SetEntState(), G_TouchTriggers(), HandleEntsThatBlockConstructible(), LandminePostThink(), multi_trigger(), SpotWouldTelefrag(), Weapon_Engineer(), and WolfReviveBbox().
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
trap_EntityContact
Parameters
[in] mins
[in] maxs
[in] ent
Returns
Definition at line 507 of file g_syscalls.c.
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 512 of file g_syscalls.c.
Referenced by ammo_touch(), G_TouchTriggers(), heal_touch(), and WolfReviveBbox().
void trap_Error (const char * fmt)
trap_Error
Parameters
[in] fmt
Definition at line 73 of file g_syscalls.c.
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
Parameters
[in] f
Definition at line 159 of file g_syscalls.c.
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
trap_FS_FOpenFile
Parameters
[in] qpath
[in] f
[in] mode
Returns
Definition at line 116 of file g_syscalls.c.
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
trap_FS_GetFileList
Parameters
[in] path
[in] extension
[out] listbuf
[in] bufsize
Returns
Definition at line 172 of file g_syscalls.c.
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
trap_FS_Read
Parameters
[out] buffer
[in] len
[in] f
Definition at line 127 of file g_syscalls.c.
int trap_FS_Rename (const char * from, const char * to)
trap_FS_Rename
Parameters
[in] from
[in] to
Returns
Definition at line 150 of file g_syscalls.c.
Referenced by _et_trap_FS_Rename().
int trap_FS_Write (const void * buffer, int len, fileHandle_t f)
trap_FS_Write
Parameters
[in] buffer
[in] len
[in] f
Returns
Definition at line 139 of file g_syscalls.c.
void trap_GetConfigstring (int num, char * buffer, int bufferSize)
trap_GetConfigstring
Parameters
[in] num
[out] buffer
[in] bufferSize
Definition at line 309 of file g_syscalls.c.
Referenced by _et_trap_GetConfigstring(), CheckExitRules(), ClientName(), ClientUserinfoChanged(), FindIntermissionPoint(), G_FindConfigstringIndex(), G_InitGame(), G_LogExit(), G_RemoveConfigstringIndex(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetWinner(), G_SetConfigStringValue(), G_StoreMapXP(), G_Surrender_v(), G_UpdateCharacter(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), objective_Register(), ScoreIsTied(), SP_misc_constructiblemarker(), SP_script_mover(), and Svcmd_CSInfo_f().
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
trap_GetEntityToken
Parameters
[out] buffer
[in] bufferSize
Returns
Definition at line 657 of file g_syscalls.c.
Referenced by CG_ParseSpawnVars(), and G_ParseSpawnVars().
void trap_GetServerinfo (char * buffer, int bufferSize)
trap_GetServerinfo
Parameters
[out] buffer
[in] bufferSize
Definition at line 340 of file g_syscalls.c.
Referenced by G_Campaign_v(), G_InitGame(), G_InitWorldSession(), G_Map_v(), G_ParseMapSettings(), and G_WriteSessionData().
int trap_GetSoundLength (sfxHandle_t sfxHandle)
trap_GetSoundLength
Parameters
[in] sfxHandle
Returns
Definition at line 567 of file g_syscalls.c.
qboolean trap_GetTag (int clientNum, int tagFileNumber, char * tagName, orientation_t * orientation)
trap_GetTag
Parameters
[in] clientNum
[in] tagFileNumber
[out] tagName
[out] orientation
Definition at line 711 of file g_syscalls.c.
Referenced by G_BuildHead(), and G_PositionEntityOnTag().
void trap_GetUsercmd (int clientNum, usercmd_t * cmd)
trap_GetUsercmd
Parameters
[in] clientNum
[in] cmd
Definition at line 599 of file g_syscalls.c.
Referenced by ClientSpawn(), and ClientThink().
void trap_GetUserinfo (int num, char * buffer, int bufferSize)
trap_GetUserinfo
Parameters
[in] num
[out] buffer
[in] bufferSize
Definition at line 320 of file g_syscalls.c.
Referenced by _et_trap_GetUserinfo(), _GetEntityName(), ClientBegin(), ClientConnect(), ClientUserinfoChanged(), G_PlayerBan(), G_players_cmd(), G_UpdateCharacter(), ETInterface::InterfaceSendMessage(), Svcmd_Kick_f(), and Svcmd_KickNum_f().
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
trap_InPVS
Parameters
[in] p1
[in] p2
Returns
Definition at line 432 of file g_syscalls.c.
Referenced by G_LandmineSnapshotCallback(), G_VisibleFromBinoculars(), G_VisibleFromBinoculars_Box(), ETInterface::IsInPVS(), and ETInterface::TraceLine().
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
trap_InPVSIgnorePortals
Parameters
[in] p1
[in] p2
Returns
Definition at line 443 of file g_syscalls.c.
void trap_LinkEntity (gentity_t * ent)
trap_LinkEntity
Parameters
[in] ent
Definition at line 473 of file g_syscalls.c.
Referenced by _et_trap_LinkEntity(), aagun_spawn(), aagun_use(), artilleryGoAway(), artillerySpotterThink(), AutoBuildConstruction(), Blocked_Door(), Blocked_DoorRotate(), clamp_playerbehindgun(), ClientSpawn(), ClientThink_real(), constructiblemarker_setup(), CopyToBodyQue(), crate_die(), dust_angles_think(), etpro_ScriptAction_SetValues(), FinishSpawningItem(), firetrail_use(), flak_spawn(), flippy_table_use(), func_constructible_explode(), func_constructible_spawn(), func_constructible_use(), func_constructiblespawn(), func_explosive_spawn(), G_AdjustSingleClientPosition(), G_BuildHead(), G_BuildLeg(), G_CheckSpottedLandMines(), G_Lua_CreateEntity(), G_ModifyTOI(), G_MoverPush(), G_MoverTeam(), G_PositionEntityOnTag(), G_PredictPmove(), G_ReAdjustSingleClientPosition(), G_RealExplodedMissile(), G_RunEntity(), G_RunItem(), G_RunMissile(), G_ScriptAction_Create(), G_ScriptAction_SetModelFromBrushmodel(), G_SetEntState(), G_TempEntity(), HandleEntsThatBlockConstructible(), init_locker(), InitConstructible(), InitExplosive(), InitMover(), InitMoverRotate(), InitShooter(), landmine_setup(), LandMineTrigger(), LaunchItem(), MakeTemporarySolid(), mg42_die(), mg42_spawn(), mg42_use(), misc_beam_think(), misc_firetrails_think(), misc_spawner_use(), moveit(), OilSlick_remove(), player_die(), Props_Activated(), Props_Barrel_Die(), Props_Chair_Die(), Props_Chair_Think(), props_decoration_death(), props_flamethrower_init(), props_locker_death(), props_radio_dieSEVEN(), props_statue_death(), RespawnItem(), ReviveEntity(), script_linkentity(), script_model_med_spawn(), smoke_init(), smoke_toggle(), SP_alarm_box(), SP_corona(), SP_crate_32(), SP_crate_64(), SP_dlight(), SP_Dust(), SP_func_door_rotating(), SP_func_invisible_user(), SP_func_leaky(), SP_func_rotating(), SP_misc_cabinet_health(), SP_misc_cabinet_supply(), SP_misc_gamemodel(), SP_misc_portal_camera(), SP_misc_portal_surface(), SP_misc_spawner(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_Props_58x112tablew(), SP_Props_Bench(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_props_castlebed(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_Crate32x64(), SP_Props_DamageInflictor(), SP_props_decor_Scale(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_Props_Flipping_Table(), SP_props_gunsparks(), SP_Props_Locker_Tall(), SP_Props_Radio(), SP_Props_RadioSEVEN(), SP_props_shard_generator(), SP_props_snowGenerator(), SP_props_statue(), SP_script_multiplayer(), SP_SmokeDust(), SP_target_rumble(), SP_target_smoke(), SP_target_speaker(), SP_team_WOLF_checkpoint(), SP_trigger_flagonly(), SP_trigger_flagonly_multiple(), SP_trigger_multiple(), SP_trigger_objective_info(), SP_trigger_once(), SP_trigger_teleport(), sparks_angles_think(), Spawn_Junk(), Spawn_Shard(), SpawnPlatTrigger(), target_laser_think(), TeleportPlayer(), Think_SetupObjectiveInfo(), Think_SetupTrainTargets(), Think_SpawnNewDoorTrigger(), Touch_Item(), TryConstructing(), UndoTemporarySolid(), use_corona(), use_dlight(), Use_Func_Rotate(), Use_props_decoration(), Use_Static(), Weapon_Engineer(), and WolfReviveBbox().
qboolean trap_LoadTag (const char * filename)
trap_LoadTag
Parameters
[in] filename
Returns
Definition at line 721 of file g_syscalls.c.
Referenced by G_ScriptAction_ChangeModel(), SP_misc_gamemodel(), and SP_script_mover().
void trap_LocateGameData (gentity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * gameClients, int sizeofGClient)
trap_LocateGameData
Parameters
[in] gEnts
[in] numGEntities
[in] sizeofGEntity_t
[in] gameClients
[in] sizeofGClient
Definition at line 258 of file g_syscalls.c.
Referenced by G_InitGame(), and G_Spawn().
messageStatus_t trap_MessageStatus (int clientNum)
trap_MessageStatus
Parameters
[in] clientNum
Returns
Definition at line 808 of file g_syscalls.c.
int trap_Milliseconds (void)
trap_Milliseconds
Returns
Definition at line 84 of file g_syscalls.c.
int trap_PC_AddGlobalDefine (char * define)
trap_PC_AddGlobalDefine
Parameters
define - unused
Returns
Note
Empty function return 0
Definition at line 733 of file g_syscalls.c.
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
Parameters
[in] handle
Returns
Definition at line 753 of file g_syscalls.c.
int trap_PC_LoadSource (const char * filename)
trap_PC_LoadSource
Parameters
[in] filename
Returns
Definition at line 743 of file g_syscalls.c.
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
trap_PC_ReadToken
Parameters
[in] handle
[out] pc_token
Returns
Definition at line 764 of file g_syscalls.c.
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
trap_PC_SourceFileAndLine
Parameters
[in] handle
[in] filename
[in] line
Returns
Definition at line 776 of file g_syscalls.c.
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
Parameters
[in] handle
Returns
Definition at line 786 of file g_syscalls.c.
int trap_PointContents (const vec3_t point, int passEntityNum)
trap_PointContents
Parameters
[in] point
[in] passEntityNum
Returns
Definition at line 421 of file g_syscalls.c.
Referenced by ClientThink_real(), CopyToBodyQue(), G_PredictPmove(), G_RunItem(), ETInterface::GetPointContents(), limbo(), and SpectatorThink().
void trap_Printf (const char * fmt)
trap_Printf
Parameters
[in] fmt
Definition at line 64 of file g_syscalls.c.
Referenced by _et_G_Print(), G_DPrintf(), G_Printf(), and G_refPrintf().
int trap_RealTime (qtime_t * qtime)
trap_RealTime
Parameters
[in] qtime
Returns
Definition at line 688 of file g_syscalls.c.
sfxHandle_t trap_RegisterSound (const char * sample, qboolean compressed)
trap_RegisterSound
Parameters
[in] sample
[in] compressed
Returns
Definition at line 578 of file g_syscalls.c.
void trap_SendConsoleCommand (int exec_when, const char * text)
trap_SendConsoleCommand
Parameters
[in] exec_when
[in] text
Definition at line 182 of file g_syscalls.c.
qboolean trap_SendMessage (int clientNum, char * buf, int buflen)
Sends binary messages. Since ETL 2.76 this is no longer void. See new return values.
Returns
1 if message is in queue (will be sent) - 0 not sent
Definition at line 798 of file g_syscalls.c.
void trap_SendServerCommand (int clientNum, const char * text)
trap_SendServerCommand
Parameters
[in] clientNum
[in] text
Definition at line 280 of file g_syscalls.c.
Referenced by _et_trap_SendServerCommand(), CheatsOk(), CheckExitRules(), checkpoint_use(), ClientBegin(), ClientCommand(), ClientConnect(), ClientThink_real(), ClientUserinfoChanged(), Cmd_Give_f(), Cmd_God_f(), Cmd_Ignore_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionReady_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), Cmd_Kill_f(), Cmd_Noclip_f(), Cmd_Nofatigue_f(), Cmd_Nostamina_f(), Cmd_Notarget_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_UnIgnore_f(), Cmd_Vote_f(), Cmd_WeaponStat_f(), Cmd_Where_f(), DoClientThinks(), fire_missile(), G_ApplyToFireTeam(), G_CheckSpottedLandMines(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_Damage(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DestroyFireteam(), G_EntitySound(), G_EntitySoundNoCut(), G_HQSay(), G_IntermissionMapList(), G_IntermissionVoteTally(), G_InviteToFireTeam(), G_MakeReferee(), G_Mute_v(), G_MuteClient(), G_PlaySound_Cmd(), G_PrintAccuracyLog(), G_PrintClientSpammyCenterPrint(), G_printMatchInfo(), G_ProposeFireTeamPlayer(), G_refWarning_cmd(), G_RegisterFireteam(), G_RemoveClientFromFireteams(), G_SayTo(), G_Script_ScriptParse(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_FadeAllSounds(), G_ScriptAction_MusicFade(), G_ScriptAction_MusicPlay(), G_ScriptAction_MusicStart(), G_ScriptAction_MusicStop(), G_SendMapEntityInfo(), G_SendScore(), G_SendSpectatorMapEntityInfo(), G_SendSystemMessage(), G_TeamCommand(), G_UnMute_v(), G_UnMuteClient(), G_UpdateCvars(), G_Voice(), G_WarnFireTeamPlayer(), HandleEntsThatBlockConstructible(), player_die(), PrintMsg(), ReviveEntity(), SetPlayerSpawn(), SetTeam(), Svcmd_Chat_f(), Svcmd_CP_f(), Svcmd_Say_f(), TeamplayInfoMessage(), Use_Target_Print(), and Weapon_Engineer().
void trap_SetBrushModel (gentity_t * ent, const char * name)
trap_SetBrushModel
Parameters
[in] ent
[in] name
Definition at line 350 of file g_syscalls.c.
Referenced by AutoBuildConstruction(), func_constructible_explode(), func_constructible_use(), func_constructiblespawn(), G_ScriptAction_SetModelFromBrushmodel(), HandleEntsThatBlockConstructible(), InitTrigger(), SP_alarm_box(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_door_rotating(), SP_func_explosive(), SP_func_invisible_user(), SP_func_leaky(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_secret(), SP_func_static(), SP_func_train(), SP_func_train_rotating(), SP_misc_constructiblemarker(), SP_Props_58x112tablew(), SP_Props_Bench(), SP_props_castlebed(), SP_Props_Crate32x64(), SP_props_decorBRUSH(), SP_Props_Flipping_Table(), SP_Props_Locker_Tall(), SP_Props_Radio(), SP_Props_RadioSEVEN(), SP_props_snowGenerator(), SP_props_statueBRUSH(), SP_script_mover(), and TryConstructing().
void trap_SetConfigstring (int num, const char * string)
trap_SetConfigstring
Parameters
[in] num
[in] string
Definition at line 298 of file g_syscalls.c.
Referenced by _et_G_ShaderRemapFlush(), _et_trap_SetConfigstring(), BeginIntermission(), CalculateRanks(), CC_loadconfig(), CheckExitRules(), CheckVote(), CheckWolfMP(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallVote_f(), Cmd_Vote_f(), G_BuildEndgameStats(), G_ClearMapXP(), G_ConfigCheckLocked(), G_configLoadAndSet(), G_delayPrint(), G_FindConfigstringIndex(), G_GetMapXP(), G_InitGame(), G_loadMatchGame(), G_LogExit(), G_ModifyTOI(), G_pause_cmd(), G_refLockTeams_cmd(), G_refPause_cmd(), G_refSpeclockTeams_cmd(), G_RegisterCvars(), G_ReloadConfig(), G_RemoveConfigstringIndex(), G_RunFrame(), G_ScriptAction_MusicQueue(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetGlobalFog(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetWinner(), G_ScriptAction_ShaderRemapFlush(), G_SetConfigStringValue(), G_StoreMapXP(), G_Surrender_v(), G_UpdateCvars(), G_UpdateFireteamConfigString(), G_UpdateSkillsToClients(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), G_UpdateSvCvars(), objective_Register(), props_locker_mass(), SP_misc_constructiblemarker(), SP_script_mover(), SP_skyportal(), SP_trigger_objective_info(), SP_worldspawn(), target_effect(), and Use_target_fog().
void trap_SetUserinfo (int num, const char * buffer)
trap_SetUserinfo
Parameters
[in] num
[in] buffer
Definition at line 330 of file g_syscalls.c.
Referenced by _et_trap_SetUserinfo(), ETInterface::AddBot(), ClientUserinfoChanged(), and ETInterface::InterfaceSendMessage().
void trap_SnapVector (float * v)
trap_SnapVector
Parameters
[in] v
Definition at line 697 of file g_syscalls.c.
Referenced by G_LinkDebris(), PM_Sprint(), and PmoveSingle().
void trap_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_Trace
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 365 of file g_syscalls.c.
Referenced by _et_trap_Trace(), BodySink(), CanDamage(), Cmd_Activate2_f(), Cmd_Activate_f(), DropToFloor(), DropToFloorG(), EntsThatRadiusCanDamage(), etpro_RadiusDamage(), FinishSpawningItem(), G_BurnTarget(), G_CheckForCursorHints(), G_DropWeapon(), G_HistoricalTrace(), G_LeaveTank(), G_PredictMissile(), G_RadiusDamage(), G_RunFlamechunk(), G_RunItem(), G_RunItemProp(), G_RunMissile(), G_SpectatorAttackFollow(), G_TestEntityPosition(), G_Trace(), G_VisibleFromBinoculars(), G_VisibleFromBinoculars_Box(), ETInterface::InterfaceSendMessage(), IsHeadShot(), IsLegShot(), Just_Got_Thrown(), Landmine_Check_Ground(), landmine_setup(), LaunchItem(), mg42_die(), moveit(), Prop_Check_Ground(), Prop_Touch(), Props_Chair_Think(), props_statue_blocked(), ReviveEntity(), target_laser_think(), ETInterface::TraceLine(), trap_EngineerTrace(), validOilSlickSpawnPoint(), Weapon_Artillery(), weapon_callAirStrike(), Weapon_FlamethrowerFire(), weapon_gpg40_fire(), weapon_grenadelauncher_fire(), weapon_mortar_fire(), Weapon_Syringe(), and WolfFindMedic().
void trap_TraceCapsule (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsule
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
Definition at line 395 of file g_syscalls.c.
Referenced by BodySink(), ClientThink_real(), G_TestEntityPosition(), and weapon_callAirStrike().
void trap_TraceCapsuleNoEnts (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceCapsuleNoEnts
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
passEntityNum - unused
[in] contentmask
Definition at line 410 of file g_syscalls.c.
Referenced by ClientThink_real(), G_PredictPmove(), and SpectatorThink().
void trap_TraceNoEnts (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
trap_TraceNoEnts
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
passEntityNum - unused
[in] contentmask
Definition at line 380 of file g_syscalls.c.
Referenced by ETInterface::TraceLine().
void trap_UnlinkEntity (gentity_t * ent)
trap_UnlinkEntity
Parameters
[in] ent
Definition at line 482 of file g_syscalls.c.
Referenced by _et_trap_UnlinkEntity(), BodyUnlink(), clamp_playerbehindgun(), ClientBegin(), ClientConnect(), ClientDisconnect(), CopyToBodyQue(), crate_die(), ExitLevel(), flippy_table_use(), func_constructible_explode(), func_constructible_use(), func_constructiblespawn(), G_FreeEntity(), G_KillEnts(), G_MoverPush(), G_RunClient(), G_RunEntity(), G_RunMissile(), G_RunMover(), G_SetEntState(), limbo(), Props_Activated(), Props_Barrel_Die(), Props_Chair_Die(), props_locker_death(), shutoff_dlight(), smoke_toggle(), SP_func_explosive(), SP_func_rotating(), SP_func_static(), SP_script_model_med(), SP_script_mover(), SpectatorThink(), target_laser_off(), use_corona(), use_dlight(), Use_props_decoration(), Use_Static(), and Use_Target_Give().