ET: Legacy: src/game/g_script.c File Reference
g_script.c File Reference
Wolfenstein Entity Scripting.
#include "g_local.h"
#include "g_lua.h"
#include "../qcommon/q_shared.h"
#include "g_etbot_interface.h"
Macros
#define SMF_TRIGGERSPAWN 1
#define SMF_SOLID 2
#define SMF_EXPLOSIVEDAMAGEONLY 4
#define SMF_RESURRECTABLE 8
#define SMF_COMPASS 16
#define SMF_ALLIES 32
#define SMF_AXIS 64
#define SMF_MOUNTED_GUN 128
#define SMF_DENSITY 256
#define SMMSF_TRIGGERSPAWN 1
#define SMMSF_SOLID 2
Functions
qboolean G_Script_EventMatch_StringEqual (g_script_event_t *event, const char *eventParm)
G_Script_EventMatch_StringEqual.
qboolean G_Script_EventMatch_IntInRange (g_script_event_t *event, const char *eventParm)
G_Script_EventMatch_IntInRange.
int G_Script_EventForString (const char *string)
G_Script_EventForString.
g_script_stack_action_t * G_Script_ActionForString (const char *string)
G_Script_ActionForString.
void G_Script_ScriptLoad (void)
Loads the script for the current level into the buffer.
void G_Script_ScriptParse (gentity_t *ent)
Parses the script for the given entity.
void G_Script_ScriptChange (gentity_t *ent, int newScriptNum)
G_Script_ScriptChange.
int G_Script_GetEventIndex (gentity_t *ent, const char *eventStr, const char *params)
G_Script_GetEventIndex.
void G_Script_ScriptEvent (gentity_t *ent, const char *eventStr, const char *params)
An event has occured, for which a script may exist.
qboolean G_Script_ScriptRun (gentity_t *ent)
G_Script_ScriptRun.
void mountedmg42_fire (gentity_t *other)
mountedmg42_fire
void script_linkentity (gentity_t *ent)
script_linkentity
void script_mover_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, meansOfDeath_t mod)
script_mover_die
void script_mover_think (gentity_t *ent)
script_mover_think
void script_mover_spawn (gentity_t *ent)
script_mover_spawn
void script_mover_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
script_mover_use
void script_mover_blocked (gentity_t *ent, gentity_t *other)
script_mover_blocked
void SP_script_mover (gentity_t *ent)
Scripted brush entity. A simplified means of moving brushes around based on events.
void script_model_med_spawn (gentity_t *ent)
script_model_med_spawn
void script_model_med_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
script_model_med_use
void SP_script_model_med (gentity_t *ent)
SP_script_model_med.
void SP_script_camera (gentity_t *ent)
This is a camera entity.
void SP_script_multiplayer (gentity_t *ent)
This is used to script multiplayer maps. Entity not displayed in game.
Variables
static g_script_stack_action_t gScriptActions []
These are the actions that each event can call.
static g_script_event_define_t gScriptEvents []
Detailed Description
Wolfenstein Entity Scripting.
Author
Ridah
Scripting that allows the designers to control the behaviour of entities according to each different scenario.
Definition in file g_script.c.
Macro Definition Documentation
#define SMF_ALLIES 32
Definition at line 940 of file g_script.c.
Referenced by SP_script_mover().
#define SMF_AXIS 64
Definition at line 941 of file g_script.c.
Referenced by SP_script_mover().
#define SMF_COMPASS 16
Definition at line 939 of file g_script.c.
Referenced by SP_script_mover().
#define SMF_DENSITY 256
Definition at line 943 of file g_script.c.
Referenced by SP_script_mover().
#define SMF_EXPLOSIVEDAMAGEONLY 4
Definition at line 937 of file g_script.c.
#define SMF_MOUNTED_GUN 128
Definition at line 942 of file g_script.c.
Referenced by script_mover_spawn(), script_mover_think(), and SP_script_mover().
#define SMF_RESURRECTABLE 8
Definition at line 938 of file g_script.c.
Referenced by script_mover_die(), script_mover_use(), and SP_script_mover().
#define SMF_SOLID 2
Definition at line 936 of file g_script.c.
Referenced by script_mover_spawn().
#define SMF_TRIGGERSPAWN 1
Script mover flags
Definition at line 935 of file g_script.c.
Referenced by SP_script_mover().
#define SMMSF_SOLID 2
Definition at line 1284 of file g_script.c.
Referenced by script_model_med_spawn().
#define SMMSF_TRIGGERSPAWN 1
Script model med spawn flags
Definition at line 1283 of file g_script.c.
Referenced by SP_script_model_med().
Function Documentation
g_script_stack_action_t* G_Script_ActionForString (const char * string)
G_Script_ActionForString.
Parameters
[in] string
Returns
Definition at line 247 of file g_script.c.
Referenced by G_Script_ScriptParse().
int G_Script_EventForString (const char * string)
G_Script_EventForString.
Parameters
[in] string
Returns
Definition at line 224 of file g_script.c.
Referenced by G_Script_ScriptParse().
qboolean G_Script_EventMatch_IntInRange (g_script_event_t * event, const char * eventParm)
G_Script_EventMatch_IntInRange.
Parameters
[in] event
[in] eventParm
Returns
Definition at line 202 of file g_script.c.
qboolean G_Script_EventMatch_StringEqual (g_script_event_t * event, const char * eventParm)
G_Script_EventMatch_StringEqual.
Parameters
[in] event
[in] eventParm
Returns
Definition at line 191 of file g_script.c.
int G_Script_GetEventIndex (gentity_t * ent, const char * eventStr, const char * params)
G_Script_GetEventIndex.
Parameters
[in] ent
[in] eventStr
[in] params
Returns
The event index within the entity for the specified event string extracted from G_Script_ScriptEvent.
Definition at line 664 of file g_script.c.
Referenced by G_Script_ScriptEvent().
void G_Script_ScriptChange (gentity_t * ent, int newScriptNum)
G_Script_ScriptChange.
Parameters
[in,out] ent
[in] newScriptNum
Definition at line 634 of file g_script.c.
Referenced by G_Script_ScriptEvent().
void G_Script_ScriptEvent (gentity_t * ent, const char * eventStr, const char * params)
An event has occured, for which a script may exist.
Parameters
[in] ent
[in] eventStr
[in] params
Definition at line 725 of file g_script.c.
Referenced by AutoBuildConstruction(), CheckExitRules(), checkpoint_spawntouch(), checkpoint_touch(), ClientSpawn(), Do_Activate_f(), DynaFree(), func_constructible_explode(), func_constructible_underconstructionthink(), func_explosive_explode(), func_explosive_use(), G_CallSpawn(), G_Damage(), G_LeaveTank(), G_RealExplodedMissile(), G_ScriptAction_Accum(), G_ScriptAction_Cvar(), G_ScriptAction_GlobalAccum(), G_ScriptAction_Trigger(), LaunchItem(), multi_trigger(), script_mover_die(), script_mover_use(), target_script_trigger_use(), Team_DroppedFlagThink(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), Touch_flagonly(), Touch_flagonly_multiple(), TryConstructing(), use_invisible_user(), and Weapon_Engineer().
void G_Script_ScriptLoad (void)
Loads the script for the current level into the buffer.
Definition at line 269 of file g_script.c.
Referenced by G_InitGame().
void G_Script_ScriptParse (gentity_t * ent)
Parses the script for the given entity.
Parameters
[in,out] ent
Definition at line 344 of file g_script.c.
Referenced by G_CallSpawn().
qboolean G_Script_ScriptRun (gentity_t * ent)
G_Script_ScriptRun.
Parameters
[in,out] ent
Returns
qtrue if the script completed
Definition at line 795 of file g_script.c.
Referenced by ClientEndFrame(), G_RunEntity(), G_RunThink(), and G_Script_ScriptChange().
void mountedmg42_fire (gentity_t * other)
mountedmg42_fire
Parameters
[in,out] other
Definition at line 883 of file g_script.c.
Referenced by ClientEvents().
void script_linkentity (gentity_t * ent)
script_linkentity
Parameters
[in] ent
Definition at line 925 of file g_script.c.
Referenced by G_ScriptAction_AbortMove(), G_ScriptAction_FaceAngles(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GotoMarker(), G_ScriptAction_Halt(), G_ScriptAction_SetRotation(), G_ScriptAction_SetSpeed(), and script_mover_spawn().
void script_model_med_spawn (gentity_t * ent)
script_model_med_spawn
Parameters
[in,out] ent
Definition at line 1290 of file g_script.c.
Referenced by script_model_med_use(), and SP_script_model_med().
void script_model_med_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
script_model_med_use
Parameters
[in] ent
other - unused
activator - unused
Definition at line 1314 of file g_script.c.
Referenced by SP_script_model_med().
void script_mover_blocked (gentity_t * ent, gentity_t * other)
script_mover_blocked
Parameters
[in] ent
[in] other
Todo:
: we could have certain entities stop us, thereby "pausing" movement
Definition at line 1085 of file g_script.c.
Referenced by G_TagLinkEntity(), and SP_script_mover().
void script_mover_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, meansOfDeath_t mod)
script_mover_die
Parameters
[in,out] self
inflictor - unused
attacker - unused
damage - unused
mod - unused
Definition at line 953 of file g_script.c.
Referenced by script_mover_use(), and SP_script_mover().
void script_mover_spawn (gentity_t * ent)
script_mover_spawn
Parameters
[in,out] ent
Definition at line 1007 of file g_script.c.
Referenced by Bot_Interface_ConsoleCommand(), Bot_Interface_Update(), script_mover_use(), and SP_script_mover().
void script_mover_think (gentity_t * ent)
script_mover_think
Parameters
[in,out] ent
Definition at line 974 of file g_script.c.
Referenced by script_mover_spawn(), and script_mover_use().
void script_mover_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
script_mover_use
Parameters
[in] ent
other - unused
activator - unused
Definition at line 1057 of file g_script.c.
Referenced by G_ScriptAction_GotoMarker(), and SP_script_mover().
void SP_script_camera (gentity_t * ent)
This is a camera entity.
QUAKED script_camera (1.0 0.25 1.0) (-8 -8 -8) (8 8 8) TriggerSpawn
Used by the scripting to show cinematics, via special camera commands. See scripting documentation.
"scriptname" name used for scripting purposes (like aiName in AI scripting)
Parameters
[in,out] ent
Note
Unused
Definition at line 1375 of file g_script.c.
void SP_script_model_med (gentity_t * ent)
SP_script_model_med.
QUAKED script_model_med (0.5 0.25 1.0) (-16 -16 -24) (16 16 64) TriggerSpawn Solid MEDIUM SIZED scripted entity, used for animating a model, moving it around, etc SOLID spawnflag means this entity will clip the player and AI, otherwise they can walk straight through it "model" the full path of the model to use "scriptname" name used for scripting purposes (like aiName in AI scripting)
Parameters
[in,out] ent
Definition at line 1331 of file g_script.c.
void SP_script_mover (gentity_t * ent)
Scripted brush entity. A simplified means of moving brushes around based on events.
QUAKED script_mover (0.5 0.25 1.0) ? TRIGGERSPAWN SOLID EXPLOSIVEDAMAGEONLY RESURECTABLE COMPASS ALLIED AXIS MOUNTED_GUN
"modelscale" - Scale multiplier (defaults to 1, and scales uniformly) "modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both the "modelscale" is ignored "model2" optional md3 to draw over the solid clip brush "scriptname" name used for scripting purposes (like aiName in AI scripting) "health" optionally make this entity damagable "description" used with health, if the entity is damagable, it draws a healthbar with this description above it.
Parameters
[in,out] ent
Definition at line 1124 of file g_script.c.
void SP_script_multiplayer (gentity_t * ent)
This is used to script multiplayer maps. Entity not displayed in game.
QUAKED script_multiplayer (1.0 0.25 1.0) (-8 -8 -8) (8 8 8)
"scriptname" name used for scripting purposes (REQUIRED)
Parameters
[in,out] ent
Note
Also storing some stuff that will change often but needs to be broadcast, so we dont want to use a configstring
Definition at line 1405 of file g_script.c.
Variable Documentation
gScriptActions static
These are the actions that each event can call.
Definition at line 53 of file g_script.c.
gScriptEvents static
Initial value:
=
{
    { "spawn",       NULL,                            SPAWN_HASH       },
    { "trigger",     G_Script_EventMatch_StringEqual, TRIGGER_HASH     },
    { "pain",        G_Script_EventMatch_IntInRange,  PAIN_HASH        },
    { "death",       NULL,                            DEATH_HASH       },
    { "activate",    G_Script_EventMatch_StringEqual, ACTIVATE_HASH    },
    { "stopcam",     NULL,                            STOPCAM_HASH     },
    { "playerstart", NULL,                            PLAYERSTART_HASH },
    { "built",       G_Script_EventMatch_StringEqual, BUILT_HASH       },
    { "buildstart",  G_Script_EventMatch_StringEqual, BUILDSTART_HASH  },
    { "decayed",     G_Script_EventMatch_StringEqual, DECAYED_HASH     },
    { "destroyed",   G_Script_EventMatch_StringEqual, DESTROYED_HASH   },
    { "rebirth",     NULL,                            REBIRTH_HASH     },
    { "failed",      NULL,                            FAILED_HASH      },
    { "dynamited",   NULL,                            DYNAMITED_HASH   },
    { "defused",     NULL,                            DEFUSED_HASH     },
    { "mg42",        G_Script_EventMatch_StringEqual, MG42_HASH        },
    { "message",     G_Script_EventMatch_StringEqual, MESSAGE_HASH     },
    { "exploded",    NULL,                            EXPLODED_HASH    },
    { NULL,          NULL,                            00               }
}
The list of events that can start an action sequence
Definition at line 161 of file g_script.c.