ET: Legacy: src/game/g_spawn.c File Reference
g_spawn.c File Reference
#include "g_local.h"
#include "g_lua.h"
Data Structures
struct spawn_t
Functions
qboolean G_SpawnStringExt (const char *key, const char *defaultString, char **out, const char *file, int line)
G_SpawnStringExt.
qboolean G_SpawnFloatExt (const char *key, const char *defaultString, float *out, const char *file, int line)
G_SpawnFloatExt.
qboolean G_SpawnIntExt (const char *key, const char *defaultString, int *out, const char *file, int line)
G_SpawnIntExt.
qboolean G_SpawnVectorExt (const char *key, const char *defaultString, float *out, const char *file, int line)
G_SpawnVectorExt.
qboolean G_SpawnVector2DExt (const char *key, const char *defaultString, float *out, const char *file, int line)
G_SpawnVector2DExt.
void SP_info_player_start (gentity_t *ent)
QUAKED info_player_start (1 0 0) (-18 -18 -24) (18 18 48) equivelant to info_player_deathmatch.
void SP_info_player_checkpoint (gentity_t *ent)
QUAKED info_player_checkpoint (1 0 0) (-16 -16 -24) (16 16 32) a b c d these are start points /after/ the level start the letter (a b c d) designates the checkpoint that needs to be complete in order to use this start position.
void SP_info_player_deathmatch (gentity_t *ent)
QUAKED info_player_deathmatch (1 0 1) (-18 -18 -24) (18 18 48) potential spawning position for deathmatch games. Targets will be fired when someone spawns in on them. "nobots" will prevent bots from using this spot. "nohumans" will prevent non-bots from using this spot.
void SP_info_player_intermission (gentity_t *ent)
QUAKED info_player_intermission (1 0 1) (-16 -16 -24) (16 16 32) AXIS ALLIED The intermission will be viewed from this point. Target an info_notnull for the view direction.
void SP_func_plat (gentity_t *ent)
SP_func_plat.
void SP_func_static (gentity_t *ent)
SP_func_static.
void SP_func_leaky (gentity_t *ent)
SP_func_leaky.
void SP_func_rotating (gentity_t *ent)
SP_func_rotating.
void SP_func_bobbing (gentity_t *ent)
SP_func_bobbing.
void SP_func_pendulum (gentity_t *ent)
SP_func_pendulum.
void SP_func_button (gentity_t *ent)
SP_func_button.
void SP_func_explosive (gentity_t *ent)
SP_func_explosive.
void SP_func_door (gentity_t *ent)
SP_func_door.
void SP_func_train (gentity_t *ent)
SP_func_train.
void SP_func_timer (gentity_t *self)
SP_func_timer.
void SP_func_train_rotating (gentity_t *ent)
SP_func_train_rotating.
void SP_func_secret (gentity_t *ent)
SP_func_secret.
void SP_func_door_rotating (gentity_t *ent)
SP_func_door_rotating.
void SP_func_constructible (gentity_t *ent)
SP_func_constructible.
void SP_func_brushmodel (gentity_t *ent)
SP_func_brushmodel.
void SP_misc_constructiblemarker (gentity_t *ent)
SP_misc_constructiblemarker.
void SP_target_explosion (gentity_t *ent)
SP_target_explosion.
void SP_misc_landmine (gentity_t *ent)
SP_misc_landmine.
void SP_trigger_always (gentity_t *ent)
This trigger will always fire. It is activated by the world.
void SP_trigger_multiple (gentity_t *ent)
SP_trigger_multiple.
void SP_trigger_push (gentity_t *ent)
SP_trigger_push.
void SP_trigger_teleport (gentity_t *ent)
QUAKED trigger_teleport (.5 .5 .5) ? Allows client side prediction of teleportation events. Must point at a target_position, which will be the teleport destination.
void SP_trigger_hurt (gentity_t *ent)
SP_trigger_hurt.
void SP_trigger_heal (gentity_t *ent)
SP_trigger_heal.
void SP_trigger_ammo (gentity_t *ent)
SP_trigger_ammo.
void SP_misc_cabinet_health (gentity_t *self)
SP_misc_cabinet_health.
void SP_misc_cabinet_supply (gentity_t *self)
SP_misc_cabinet_supply.
void SP_trigger_concussive_dust (gentity_t *ent)
SP_trigger_concussive_dust.
void SP_trigger_once (gentity_t *ent)
SP_trigger_once.
void SP_target_remove_powerups (gentity_t *ent)
SP_target_remove_powerups.
void SP_target_give (gentity_t *ent)
SP_target_give.
void SP_target_delay (gentity_t *ent)
SP_target_delay.
void SP_target_speaker (gentity_t *ent)
SP_target_speaker.
void SP_target_print (gentity_t *ent)
SP_target_print.
void SP_target_laser (gentity_t *self)
SP_target_laser.
void SP_target_teleporter (gentity_t *ent)
The activator will be teleported away. QUAKED target_teleporter (1 0 0) (-8 -8 -8) (8 8 8)
void SP_target_relay (gentity_t *ent)
SP_target_relay.
void SP_target_kill (gentity_t *ent)
SP_target_kill.
void SP_target_position (gentity_t *ent)
Used as a positional target for in-game calculation, like jumppad targets.
void SP_target_location (gentity_t *ent)
SP_target_location.
void SP_target_push (gentity_t *ent)
SP_target_push.
void SP_target_script_trigger (gentity_t *ent)
SP_target_script_trigger.
void SP_misc_beam (gentity_t *self)
SP_misc_beam.
void SP_target_alarm (gentity_t *ent)
QUAKED target_alarm (1 1 0) (-4 -4 -4) (4 4 4) does nothing yet (effectively a relay right now)
void SP_target_counter (gentity_t *ent)
QUAKED target_counter (1 1 0) (-8 -8 -8) (8 8 8) Increments the counter pointed to. "count" is the key for the count value.
void SP_target_lock (gentity_t *ent)
SP_target_lock.
void SP_target_effect (gentity_t *ent)
SP_target_effect.
void SP_target_fog (gentity_t *ent)
SP_target_fog.
void SP_misc_vis_dummy (gentity_t *ent)
QUAKED misc_vis_dummy (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. For safety, you should have each dummy only point at one entity (however, it's okay to have many dummies pointing at one entity)
void SP_misc_vis_dummy_multiple (gentity_t *ent)
QUAKED misc_vis_dummy_multiple (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. This entity was created to have multiple speakers targeting it.
void SP_light (gentity_t *self)
QUAKED light (0 1 0) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point q3map_non-dynamic Non-displayed light. "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf) "q3map_non-dynamic" specifies that this light should not contribute to the world's 'light grid' and therefore will not light dynamic models in the game.(wolf)
void SP_info_null (gentity_t *self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_null (0 0.5 0) (-4 -4 -4) (4 4 4)
void SP_info_notnull (gentity_t *self)
Used as a positional target for in-game calculation, like jumppad targets. target_position does the same thing QUAKED info_notnull (0 0.5 0) (-4 -4 -4) (4 4 4)
void SP_info_camp (gentity_t *self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_camp (0 0.5 0) (-4 -4 -4) (4 4 4)
void SP_path_corner (gentity_t *self)
SP_path_corner.
void SP_path_corner_2 (gentity_t *self)
QUAKED path_corner_2 (.5 .3 0) (-8 -8 -8) (8 8 8) STOP END REVERSE Train path corners. THIS VERSION WILL NOT CONTRIBUTE TOWARDS INGAME ENTITY COUNT "targetname" The script uses this name to identify the corner.
void SP_info_limbo_camera (gentity_t *self)
SP_info_limbo_camera.
void SP_info_train_spline_main (gentity_t *self)
SP_info_train_spline_main.
void SP_misc_teleporter_dest (gentity_t *self)
QUAKED misc_teleporter_dest (1 0 0) (-32 -32 -24) (32 32 -16) Point teleporters at these. Now that we don't have teleport destination pads, this is just an info_notnull.
void SP_misc_model (gentity_t *ent)
QUAKED misc_model (1 0 0) (-16 -16 -16) (16 16 16) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested)
void SP_misc_gamemodel (gentity_t *ent)
QUAKED misc_gamemodel (1 0 0) (-16 -16 -16) (16 16 16) ORIENT_LOD START_ANIMATE md3 placed in the game at runtime (rather than in the bsp) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x, and scales uniformly) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested) "skin" .skin file used to define shaders for model "trunk" diameter of solid core (used for trace visibility and collision (not ai pathing)) "trunkheight" height of trunk.
void SP_misc_portal_camera (gentity_t *ent)
QUAKED misc_portal_camera (0 0 1) (-8 -8 -8) (8 8 8) slowrotate fastrotate The target for a misc_portal_director. You can set either angles or target another entity to determine the direction of view. "roll" an angle modifier to orient the camera around the target vector;.
void SP_misc_portal_surface (gentity_t *ent)
QUAKED misc_portal_surface (0 0 1) (-8 -8 -8) (8 8 8) The portal surface nearest this entity will show a view from the targeted misc_portal_camera, or a mirror view if untargeted. This must be within 64 world units of the surface!
void SP_misc_light_surface (gentity_t *ent)
QUAKED misc_light_surface (1 .5 0) (-8 -8 -8) (8 8 8) The surfaces nearest these entities will be the only surfaces lit by the targeting light This must be within 64 world units of the surface to be lit!
void SP_misc_commandmap_marker (gentity_t *ent)
Command map marker entity. When set to state default it shows, any other state and it isn't visible. QUAKED misc_commandmap_marker (0 0.85 .85) (-16 -16 0) (16 16 16) ONLY_AXIS ONLY_ALLIED ISOBJECTIVE ISHEALTHAMMOCABINET ISCOMMANDPOST -----— KEYS -----— (none) -----— SPAWNFLAGS -----— (none)
void SP_shooter_rocket (gentity_t *ent)
QUAKED shooter_rocket (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" the number of degrees of deviance from the taget. (1.0 default)
void SP_shooter_grenade (gentity_t *ent)
QUAKED shooter_grenade (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" is the number of degrees of deviance from the taget. (1.0 default)
void SP_team_CTF_redspawn (gentity_t *ent)
SP_team_CTF_redspawn.
void SP_team_CTF_bluespawn (gentity_t *ent)
SP_team_CTF_bluespawn.
void SP_team_WOLF_objective (gentity_t *ent)
SP_team_WOLF_objective.
void SP_team_WOLF_checkpoint (gentity_t *ent)
SP_team_WOLF_checkpoint.
void SP_props_box_32 (gentity_t *self)
SP_props_box_32 QUAKED props_box_32 (1 0 0) (-16 -16 -16) (16 16 16)
void SP_props_box_48 (gentity_t *self)
SP_props_box_48 QUAKED props_box_48 (1 0 0) (-24 -24 -24) (24 24 24)
void SP_props_box_64 (gentity_t *self)
SP_props_box_64 QUAKED props_box_64 (1 0 0) (-32 -32 -32) (32 32 32)
void SP_target_smoke (gentity_t *ent)
SP_target_smoke.
void SP_dlight (gentity_t *ent)
QUAKED dlight (0 1 0) (-12 -12 -12) (12 12 12) FORCEACTIVE STARTOFF ONETIME "style": value is an int from 1-19 that contains a pre-defined 'flicker' string. "stylestring": set your own 'flicker' string. (ex. "klmnmlk"). NOTE: this should be all lowercase Stylestring characters run at 10 cps in the game. (meaning the alphabet, at 24 characters, would take 2.4 seconds to cycle) "offset": change the initial index in a style string. So val of 3 in the above example would start this light at 'N'. (used to get dlights using the same style out of sync). "atten": offset from the alpha values of the stylestring. stylestring of "ddeeffzz" with an atten of -1 would result in "ccddeeyy" Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). FORCEACTIVE - toggle makes sure this light stays alive in a map even if the user has r_dynamiclight set to 0. STARTOFF - means the dlight doesn't spawn in until ent is triggered ONETIME - when the dlight is triggered, it will play through it's cycle once, then shut down until triggered again "shader" name of shader to apply "sound" sound to loop every cycle (this actually just plays the sound at the beginning of each cycle)
void SP_corona (gentity_t *ent)
QUAKED corona (0 1 0) (-4 -4 -4) (4 4 4) START_OFF Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). "scale" will designate a multiplier to the default size. (so 2.0 is 2xdefault size, 0.5 is half)
void SP_mg42 (gentity_t *ent)
QUAKED misc_mg42 (1 0 0) (-16 -16 -24) (16 16 24) HIGH NOTRIPOD harc = horizonal fire arc Default is 57.5 (left and right) varc = vertical fire arc Default is 45 (upwards and 22.5 down) health = how much damage can it take default is 50 damage = determines how much the weapon will inflict if a non player uses it "accuracy" all guns are 100% accurate an entry of 0.5 would make it 50%.
void SP_aagun (gentity_t *ent)
QUAKED misc_aagun (1 0 0) (-32 -32 0) (64 32 56) harc = fixed full 360? varc = fixed 0-45 up?
void SP_shooter_mortar (gentity_t *ent)
QUAKED shooter_mortar (1 0 0) (-16 -16 -16) (16 16 16) SMOKE_FX FLASH_FX Lobs a mortar so that it will pass through the info_notnull targeted by this entity "random" the number of degrees of deviance from the taget. (1.0 default) if LAUNCH_FX is checked a smoke effect will play at the origin of this entity. if FLASH_FX is checked a muzzle flash effect will play at the origin of this entity.
void SP_alarm_box (gentity_t *ent)
SP_alarm_box.
void SP_trigger_flagonly (gentity_t *ent)
SP_trigger_flagonly.
void SP_trigger_flagonly_multiple (gentity_t *ent)
SP_trigger_flagonly_multiple.
void SP_trigger_objective_info (gentity_t *ent)
QUAKED trigger_objective_info (.5 .5 .5) ? AXIS_OBJECTIVE ALLIED_OBJECTIVE MESSAGE_OVERRIDE TANK IS_OBJECTIVE IS_HEALTHAMMOCABINET IS_COMMANDPOST Players in this field will see a message saying that they are near an objective.
void SP_target_rumble (gentity_t *ent)
SP_target_rumble.
void SP_SmokeDust (gentity_t *ent)
SP_SmokeDust.
void SP_Dust (gentity_t *ent)
SP_Dust.
void SP_props_sparks (gentity_t *ent)
SP_props_sparks.
void SP_props_gunsparks (gentity_t *ent)
SP_props_gunsparks.
void SP_Props_Bench (gentity_t *ent)
SP_Props_Bench.
void SP_Props_Radio (gentity_t *ent)
SP_Props_Radio.
void SP_Props_Chair (gentity_t *ent)
SP_Props_Chair.
void SP_Props_ChairHiback (gentity_t *ent)
SP_Props_ChairHiback.
void SP_Props_ChairSide (gentity_t *ent)
SP_Props_ChairSide.
void SP_Props_ChairChat (gentity_t *ent)
SP_Props_ChairChat.
void SP_Props_ChairChatArm (gentity_t *ent)
SP_Props_ChairChatArm.
void SP_Props_DamageInflictor (gentity_t *ent)
SP_Props_DamageInflictor.
void SP_Props_Locker_Tall (gentity_t *ent)
SP_Props_Locker_Tall.
void SP_Props_Desklamp (gentity_t *ent)
SP_Props_Desklamp.
void SP_Props_Flamebarrel (gentity_t *ent)
SP_Props_Flamebarrel.
void SP_crate_64 (gentity_t *ent)
SP_crate_64.
void SP_Props_Flipping_Table (gentity_t *ent)
SP_Props_Flipping_Table.
void SP_crate_32 (gentity_t *self)
SP_crate_32.
void SP_Props_Crate32x64 (gentity_t *ent)
SP_Props_Crate32x64.
void SP_Props_58x112tablew (gentity_t *ent)
SP_Props_58x112tablew.
void SP_Props_RadioSEVEN (gentity_t *ent)
SP_Props_RadioSEVEN.
void SP_props_flamethrower (gentity_t *ent)
SP_props_flamethrower.
void SP_func_invisible_user (gentity_t *ent)
SP_func_invisible_user.
void SP_lightJunior (gentity_t *self)
QUAKED lightJunior (0 0.7 0.3) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point Non-displayed light that only affects dynamic game models, but does not contribute to lightmaps "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf)
void SP_misc_flak (gentity_t *ent)
QUAKED misc_flak (1 0 0) (-32 -32 0) (32 32 100)
void SP_props_snowGenerator (gentity_t *ent)
SP_props_snowGenerator.
void SP_props_decoration (gentity_t *ent)
SP_props_decoration.
void SP_props_decorBRUSH (gentity_t *ent)
SP_props_decorBRUSH.
void SP_props_statue (gentity_t *ent)
SP_props_statue.
void SP_props_statueBRUSH (gentity_t *ent)
SP_props_statueBRUSH.
void SP_skyportal (gentity_t *ent)
SP_skyportal.
void SP_script_model_med (gentity_t *ent)
SP_script_model_med.
void SP_script_mover (gentity_t *ent)
Scripted brush entity. A simplified means of moving brushes around based on events.
void SP_script_multiplayer (gentity_t *ent)
This is used to script multiplayer maps. Entity not displayed in game.
void SP_props_footlocker (gentity_t *self)
SP_props_footlocker.
void SP_misc_firetrails (gentity_t *ent)
SP_misc_firetrails.
void SP_misc_spawner (gentity_t *ent)
QUAKED misc_spawner (.3 .7 .8) (-8 -8 -8) (8 8 8) use the pickup name when this entity gets used it will spawn an item that matches its spawnitem field e.i. spawnitem 9mm.
void SP_props_decor_Scale (gentity_t *ent)
SP_props_decor_Scale.
void SP_func_debris (gentity_t *ent)
SP_func_debris.
void SP_func_fakebrush (gentity_t *ent)
forty - etpro mapscripting - spawn function for fake brushes
qboolean G_CallSpawn (gentity_t *ent)
Finds the spawn function for the entity and calls it.
char * G_NewString (const char *string)
Builds a copy of the string, translating \n to real linefeeds so message texts can be multi-line.
void G_ParseField (const char *key, const char *value, gentity_t *ent)
Takes a key/value pair and sets the binary values in a gentity.
gentity_t * G_SpawnGEntityFromSpawnVars (void)
Spawn an entity and fill in all of the level fields from level.spawnVars[], then call the class specfic spawn function.
char * G_AddSpawnVarToken (const char *string)
G_AddSpawnVarToken.
qboolean G_ParseSpawnVars (void)
Parses a brace bounded set of key / value pairs out of the level's entity strings into level.spawnVars[] This does not actually spawn an entity.
void SP_worldspawn (void)
Every map should have exactly one worldspawn.
void G_SpawnEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
int GetFieldIndex (const char *fieldname)
GetFieldIndex.
fieldtype_t GetFieldType (const char *fieldname)
GetFieldType.
Variables
field_t fields []
spawn_t spawns []
Function Documentation
char* G_AddSpawnVarToken (const char * string)
G_AddSpawnVarToken.
Parameters
[in] string
Returns
Definition at line 857 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues(), G_Lua_CreateEntity(), G_ParseSpawnVars(), and G_ScriptAction_Create().
qboolean G_CallSpawn (gentity_t * ent)
Finds the spawn function for the entity and calls it.
Parameters
ent
Returns
qfalse if spawn not found
Definition at line 631 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues(), and G_SpawnGEntityFromSpawnVars().
char* G_NewString (const char * string)
Builds a copy of the string, translating \n to real linefeeds so message texts can be multi-line.
Parameters
string
Returns
Definition at line 695 of file g_spawn.c.
Referenced by G_ParseField(), and SP_misc_beam().
void G_ParseField (const char * key, const char * value, gentity_t * ent)
Takes a key/value pair and sets the binary values in a gentity.
Parameters
[in] key
[in] value
[in] ent
Definition at line 737 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues(), and G_SpawnGEntityFromSpawnVars().
qboolean G_ParseSpawnVars (void)
Parses a brace bounded set of key / value pairs out of the level's entity strings into level.spawnVars[] This does not actually spawn an entity.
Returns
Definition at line 882 of file g_spawn.c.
Referenced by G_SpawnEntitiesFromString().
void G_SpawnEntitiesFromString (void)
Parses textual entity definitions out of an entstring and spawns gentities.
Definition at line 1030 of file g_spawn.c.
Referenced by G_InitGame().
qboolean G_SpawnFloatExt (const char * key, const char * defaultString, float * out, const char * file, int line)
G_SpawnFloatExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 86 of file g_spawn.c.
gentity_t* G_SpawnGEntityFromSpawnVars (void)
Spawn an entity and fill in all of the level fields from level.spawnVars[], then call the class specfic spawn function.
Returns
Definition at line 788 of file g_spawn.c.
Referenced by G_Lua_CreateEntity(), G_ScriptAction_Create(), and G_SpawnEntitiesFromString().
qboolean G_SpawnIntExt (const char * key, const char * defaultString, int * out, const char * file, int line)
G_SpawnIntExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 105 of file g_spawn.c.
qboolean G_SpawnStringExt (const char * key, const char * defaultString, char ** out, const char * file, int line)
G_SpawnStringExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 53 of file g_spawn.c.
Referenced by G_SpawnFloatExt(), G_SpawnIntExt(), G_SpawnVector2DExt(), and G_SpawnVectorExt().
qboolean G_SpawnVector2DExt (const char * key, const char * defaultString, float * out, const char * file, int line)
G_SpawnVector2DExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 143 of file g_spawn.c.
qboolean G_SpawnVectorExt (const char * key, const char * defaultString, float * out, const char * file, int line)
G_SpawnVectorExt.
Parameters
[in] key
[in] defaultString
[out] out
[in] file
[in] line
Returns
Definition at line 124 of file g_spawn.c.
int GetFieldIndex (const char * fieldname)
GetFieldIndex.
Parameters
[in] fieldname
Returns
The index in the fiels[] array of the given fieldname, -1 if not found..
Definition at line 1070 of file g_spawn.c.
Referenced by _et_G_GetSpawnVar(), _et_G_SetSpawnVar(), and GetFieldType().
fieldtype_t GetFieldType (const char * fieldname)
GetFieldType.
Parameters
[in] fieldname
Returns
The fieldType of the given fieldname, otherwise F_IGNORE if the field is not found.
Definition at line 1087 of file g_spawn.c.
Referenced by _et_G_GetSpawnVar(), and _et_G_SetSpawnVar().
void SP_aagun (gentity_t * self)
QUAKED misc_aagun (1 0 0) (-32 -32 0) (64 32 56) harc = fixed full 360? varc = fixed 0-45 up?
Parameters
self
Definition at line 1429 of file g_misc.c.
void SP_alarm_box (gentity_t * ent)
SP_alarm_box.
QUAKED alarm_box (1 0 1) START_ON You need to have an origin brush as part of this entity current alarm box model is (8 x 16 x 28) "health" defaults to 10
"noise" the sound to play over the system (this would be the siren sound)
START_ON means the button is pushed in, any dlights are cycling, and alarms are sounding
"team" key/value is valid for teamed alarm boxes teamed alarm_boxes work in tandem (switches/lights syncronize) target a box to dlights to have them activate/deactivate with the system (use a stylestring that matches the cycletime for the alarmbox sound) alarm sound locations are also placed in the dlights, so wherever you place an attached dlight, you will hear the alarm model: the model used is "models/mapobjects/electronics/alarmbox.md3" place the origin at the center of your trigger box
Parameters
[in,out] ent
Todo:
: temp
Definition at line 205 of file g_alarm.c.
void SP_corona (gentity_t * ent)
QUAKED corona (0 1 0) (-4 -4 -4) (4 4 4) START_OFF Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). "scale" will designate a multiplier to the default size. (so 2.0 is 2xdefault size, 0.5 is half)
Parameters
[in,out] ent
Definition at line 717 of file g_misc.c.
void SP_crate_32 (gentity_t * self)
SP_crate_32.
QUAKED props_crate_32 (.8 .6 .2) (-16 -16 0) (16 16 32) breakable pushable
health = default = 20 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] self
Definition at line 2769 of file g_props.c.
void SP_crate_64 (gentity_t * self)
SP_crate_64.
QUAKED props_crate_64 (.8 .6 .2) (-32 -32 0) (32 32 64) breakable pushable
health = default = 20 wait = defaults to 10 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] self
Definition at line 2708 of file g_props.c.
void SP_dlight (gentity_t * ent)
QUAKED dlight (0 1 0) (-12 -12 -12) (12 12 12) FORCEACTIVE STARTOFF ONETIME "style": value is an int from 1-19 that contains a pre-defined 'flicker' string. "stylestring": set your own 'flicker' string. (ex. "klmnmlk"). NOTE: this should be all lowercase Stylestring characters run at 10 cps in the game. (meaning the alphabet, at 24 characters, would take 2.4 seconds to cycle) "offset": change the initial index in a style string. So val of 3 in the above example would start this light at 'N'. (used to get dlights using the same style out of sync). "atten": offset from the alpha values of the stylestring. stylestring of "ddeeffzz" with an atten of -1 would result in "ccddeeyy" Use color picker to set color or key "color". values are 0.0-1.0 for each color (rgb). FORCEACTIVE - toggle makes sure this light stays alive in a map even if the user has r_dynamiclight set to 0. STARTOFF - means the dlight doesn't spawn in until ent is triggered ONETIME - when the dlight is triggered, it will play through it's cycle once, then shut down until triggered again "shader" name of shader to apply "sound" sound to loop every cycle (this actually just plays the sound at the beginning of each cycle)
styles: 1 - "mmnmmommommnonmmonqnmmo" 2 - "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba" 3 - "mmmmmaaaaammmmmaaaaaabcdefgabcdefg" 4 - "ma" 5 - "jklmnopqrstuvwxyzyxwvutsrqponmlkj" 6 - "nmonqnmomnmomomono" 7 - "mmmaaaabcdefgmmmmaaaammmaamm" 8 - "aaaaaaaazzzzzzzz" 9 - "mmamammmmammamamaaamammma" 10 - "abcdefghijklmnopqrrqponmlkjihgfedcba" 11 - "mmnommomhkmmomnonmmonqnmmo" 12 - "kmamaamakmmmaakmamakmakmmmma" 13 - "kmmmakakmmaaamammamkmamakmmmma" 14 - "mmnnoonnmmmmmmmmmnmmmmnonmmmmmmm" 15 - "mmmmnonmmmmnmmmmmnonmmmmmnmmmmmmm" 16 - "zzzzzzzzaaaaaaaa" 17 - "zzzzzzzzaaaaaaaaaaaaaaaa" 18 - "aaaaaaaazzzzzzzzaaaaaaaa" 19 - "aaaaaaaaaaaaaaaazzzzzzzz"
ent->dl_stylestring contains the lightstyle string ent->health tracks current index into style string ent->count tracks length of style string
Parameters
[in,out] ent
Definition at line 874 of file g_misc.c.
void SP_Dust (gentity_t * ent)
SP_Dust.
Parameters
[in,out] ent
Definition at line 619 of file g_props.c.
void SP_func_bobbing (gentity_t * ent)
SP_func_bobbing.
QUAKED func_bobbing (0 .5 .8) ? X_AXIS Y_AXIS Normally bobs on the Z axis "model2" .md3 model to also draw "height" amplitude of bob (32 default) "speed" seconds to complete a bob cycle (4 default) "phase" the 0.0 to 1.0 offset in the cycle to start at "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius
Parameters
[in,out] ent
Definition at line 3930 of file g_mover.c.
void SP_func_brushmodel (gentity_t * ent)
SP_func_brushmodel.
Parameters
[in,out] ent
Definition at line 5738 of file g_mover.c.
void SP_func_button (gentity_t * ent)
SP_func_button.
QUAKED func_button (0 .5 .8) ? x x x TOUCH x x STAYOPEN When a button is touched, it moves some distance in the direction of it's angle, triggers all of it's targets, waits some time, then returns to it's original position where it can be triggered again.
"model2" .md3 model to also draw "angle" determines the opening direction "target" all entities with a matching targetname will be used "speed" override the default 40 speed "wait" override the default 1 second wait (-1 = never return) "lip" override the default 4 pixel lip remaining at end of move "health" if set, the button must be killed instead of touched "color" constantLight color "light" constantLight radius
Parameters
ent
Definition at line 2886 of file g_mover.c.
void SP_func_constructible (gentity_t * ent)
SP_func_constructible.
QUAKED func_constructible (.9 .75 .15) ? START_BUILT INVULNERABLE AXIS_CONSTRUCTIBLE ALLIED_CONSTRUCTIBLE BLOCK_PATHS_WHEN_BUILT NO_AAS_BLOCKING AAS_SCRIPTED A constructible object that functions as target for engineers. "track" functions as a group name. All entities with the same 'track' as the func_constructible will be constructed at the same time. "constages" list of target func_brushmodel entities (up to 3) that make up the construction stages (example: "stage1;stage2;") "desstages" list of target func_brushmodel entities (up to 3) that make up the destruction stages (example: "desstage1;desstage2;")
START_BUILT : building starts built INVULNERABLE : building can't be destroyed AXIS_CONSTRUCTIBLE : building is constructible by axis ALLIED_CONSTRUCTIBLE : building is constructible by allies BLOCK_PATHS_WHEN_BUILT : when built, areas touching structures are blocked NO_AAS_BLOCKING : dont interact with AAS at all
Parameters
[in,out] ent
Definition at line 5671 of file g_mover.c.
void SP_func_debris (gentity_t * ent)
SP_func_debris.
Parameters
[in] ent
Definition at line 5779 of file g_mover.c.
void SP_func_door (gentity_t * ent)
SP_func_door.
QUAKED func_door (0 .5 .8) ? START_OPEN TOGGLE CRUSHER TOUCH SHOOT-THRU TOGGLE wait in both the start and end states for a trigger event. START_OPEN the door to moves to its destination when spawned, and operate in reverse. It is used to temporarily or permanently close off an area when triggered (not useful for touch or takedamage doors). NOMONSTER monsters will not trigger this door
"key" -1 for locked, key number for which key opens, 0 for open. default '0' unless door is targeted. (trigger_aidoor entities targeting this door do /not/ affect the key status) "model2" .md3 model to also draw "angle" determines the opening direction "targetname" if set, no touch field will be spawned and a remote button or trigger field activates the door. "speed" movement speed (100 default) "closespeed" optional different movement speed for door closing "wait" wait before returning (3 default, -1 = never return) "lip" lip remaining at end of move (8 default) "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius "health" if set, the door must be shot open "team" team name. other doors with same team name will open/close in syncronicity "lockpickTime" time to unpick the lock on a locked door - use with key set to 99 "type" use sounds based on construction of door: 0 - nosound (default) 1 - metal 2 - stone 3 - lab 4 - wood 5 - iron/jail 6 - portcullis 7 - wood (quiet)
SOUND NAMING INFO - inside "sound/movers/doors/door<number>... _open.wav // opening _endo.wav // open _close.wav // closing _endc.wav // closed _loopo.wav // opening loop _loopc.wav // closing loop _locked.wav // locked
_openq.wav // opening quietly _endoq.wav // open quietly _closeq.wav // closing quietly _endcq.wav // closed quietly
and for rotating doors: _kicked.wav _kickedend.wav
Parameters
[in,out] ent
Todo:
: never executed !
Definition at line 2447 of file g_mover.c.
void SP_func_door_rotating (gentity_t * ent)
SP_func_door_rotating.
QUAKED func_door_rotating (0 .5 .8) ? - TOGGLE X_AXIS Y_AXIS REVERSE FORCE STAYOPEN TAKE_KEY You need to have an origin brush as part of this entity. The center of that brush will be the point around which it is rotated. It will rotate around the Z axis by default. You can check either the X_AXIS or Y_AXIS box to change that (only one axis allowed. If both X and Y are checked, the default of Z will be used). FORCE door opens even if blocked TAKE_KEY removes the key from the players inventory AXIS_ONLY Only axis team can open the doors ALLIES_ONLY Only allied team can open the doors ACCEPT_CVOPS Accept a disguised covert ops as a valid team member for team only doors
"key" -1 for locked, key number for which key opens, 0 for open. default '0' unless door is targeted. (trigger_aidoor entities targeting this door do /not/ affect the key status) "model2" .md3 model to also draw "degrees" determines how many degrees it will turn (90 default) "speed" movement speed (100 default) "closespeed" optional different movement speed for door closing "time" how many milliseconds it will take to open 1 sec = 1000 "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius "lockpickTime" time to unpick the lock on a locked door - use with key set to 99 "type" use sounds based on construction of door: 0 - nosound (default) 1 - metal 2 - stone 3 - lab 4 - wood 5 - iron/jail 6 - portcullis 7 - wood (quiet) "team" team name. other doors with same team name will open/close in syncronicity
Parameters
[in,out] ent
Todo:
: never execute
Definition at line 4061 of file g_mover.c.
void SP_func_explosive (gentity_t * ent)
SP_func_explosive.
QUAKED func_explosive (0 .5 .8) ? START_INVIS TOUCHABLE USESHADER LOWGRAV NOBLOCKAAS TANK Any brush that you want to explode or break apart. If you want an explosion, set dmg and it will do a radius explosion of that amount at the center of the bursh. TOUCHABLE means automatic use on player contact. USESHADER will apply the shader used on the brush model to the debris. LOWGRAV specifies that the debris will /always/ fall slowly "item" - when it explodes, pop this item out with the debirs (use QUAKED name. ex: "item_health_small") "dmg" - how much radius damage should be done, defaults to 0 "health" - defaults to 100. If health is set to '0' the brush will not be shootable. "targetname" - if set, no touch field will be spawned and a remote button or trigger field triggers the explosion. "type" - type of debris ("glass", "wood", "metal", "gibs", "brick", "rock", "fabric") default is "wood" "mass" - defaults to 75. This determines how much debris is emitted when it explodes. You get one large chunk per 100 of mass (up to 8) and one small chunk per 25 of mass (up to 16). So 800 gives the most. "noise" - sound to play when triggered. The explosive will default to a sound that matches it's 'type'. Use the sound name "nosound" (case in-sensitive) if you want it silent. the default sounds are: "wood" - "sound/world/boardbreak.wav" "glass" - "sound/world/glassbreak_01.wav" "metal" - "sound/world/metalbreak.wav" "gibs" - "sound/player/gibsplit1.wav" "brick" - "sound/world/debris1.wav" "stone" - "sound/world/stonefall.wav" "fabric" - "sound/world/metalbreak.wav" "fxdensity" size of explosion 1 - 100 (default is 10)
Parameters
[in,out] ent
Todo:
: test this
Definition at line 4671 of file g_mover.c.
void SP_func_fakebrush (gentity_t * ent)
forty - etpro mapscripting - spawn function for fake brushes
Parameters
ent
Definition at line 1019 of file g_spawn.c.
void SP_func_invisible_user (gentity_t * ent)
SP_func_invisible_user.
Parameters
[in,out] ent
Definition at line 4896 of file g_mover.c.
void SP_func_leaky (gentity_t * ent)
SP_func_leaky.
QUAKED func_leaky (0 .5 .8) ? "type" - leaks particles of this type
1:oil 2:water 3:steam
Parameters
[in,out] ent
Definition at line 3707 of file g_mover.c.
void SP_func_pendulum (gentity_t * ent)
SP_func_pendulum.
QUAKED func_pendulum (0 .5 .8) ? You need to have an origin brush as part of this entity. Pendulums always swing north / south on unrotated models. Add an angles field to the model to allow rotation in other directions. Pendulum frequency is a physical constant based on the length of the beam and gravity. "model2" .md3 model to also draw "speed" the number of degrees each way the pendulum swings, (30 default) "phase" the 0.0 to 1.0 offset in the cycle to start at "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius
Parameters
ent
Definition at line 3987 of file g_mover.c.
void SP_func_plat (gentity_t * ent)
SP_func_plat.
QUAKED func_plat (0 .5 .8) ? Plats are always drawn in the extended position so they will light correctly.
"lip" default 8, protrusion above rest position "height" total height of movement, defaults to model height "speed" overrides default 200. "dmg" overrides default 2 "model2" .md3 model to also draw "color" constantLight color "light" constantLight radius
Parameters
ent
Definition at line 2797 of file g_mover.c.
void SP_func_rotating (gentity_t * ent)
SP_func_rotating.
Parameters
[in,out] ent
Definition at line 3860 of file g_mover.c.
void SP_func_secret (gentity_t * ent)
SP_func_secret.
QUAKED func_secret (0 .5 .8) ? REVERSE x CRUSHER TOUCH TOGGLE wait in both the start and end states for a trigger event. START_OPEN the door to moves to its destination when spawned, and operate in reverse. It is used to temporarily or permanently close off an area when triggered (not useful for touch or takedamage doors). NOMONSTER monsters will not trigger this door
"key" -1 for locked, key number for which key opens, 0 for open. default '0' unless door is targeted. (trigger_aidoor entities targeting this door do /not/ affect the key status) "model2" .md3 model to also draw "angle" determines the opening direction "targetname" if set, no touch field will be spawned and a remote button or trigger field activates the door. "speed" movement speed (100 default) "wait" wait before returning (2 default, -1 = never return) "lip" lip remaining at end of move (8 default) "dmg" damage to inflict when blocked (2 default) "color" constantLight color "light" constantLight radius "health" if set, the door must be shot open "lockpickTime" time to unpick the lock on a locked door - use with key set to 99
Parameters
[in,out] ent
Todo:
: never executed !
Definition at line 2585 of file g_mover.c.
void SP_func_static (gentity_t * ent)
SP_func_static.
QUAKED func_static (0 .5 .8) ? start_invis pain painEFX A bmodel that just sits there, doing nothing. Can be used for conditional walls and models. "model2" .md3 model to also draw "color" constantLight color "light" constantLight radius "start_invis" will start the entity as non-existant If targeted, it will toggle existance when triggered
pain will use its target
When using pain you will need to specify the delay time value of 1 = 1 sec 2 = 2 sec so on... default is 1 sec you can use decimals example : delay 1.27
painEFX will spawn a shards example: shard 4 will spawn rubble
shard default is 4
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] ent
Definition at line 3755 of file g_mover.c.
void SP_func_timer (gentity_t * self)
SP_func_timer.
Parameters
[in,out] self
Definition at line 1178 of file g_trigger.c.
void SP_func_train (gentity_t * self)
SP_func_train.
QUAKED func_train (0 .5 .8) ? START_ON TOGGLE BLOCK_STOPS A train is a mover that moves between path_corner target points. Trains MUST HAVE AN ORIGIN BRUSH. The train spawns at the first target it is pointing at. "model2" .md3 model to also draw "speed" default 100 "dmg" default 2 "noise" looping sound to play when the train is in motion "target" next path corner "color" constantLight color "light" constantLight radius
Parameters
[in,out] self
Definition at line 3317 of file g_mover.c.
void SP_func_train_rotating (gentity_t * self)
SP_func_train_rotating.
QUAKED func_train_rotating (0 .5 .8) ? START_ON TOGGLE BLOCK_STOPS A train is a mover that moves between path_corner target points. This train can also rotate along the X Y Z Trains MUST HAVE AN ORIGIN BRUSH. The train spawns at the first target it is pointing at.
"model2" .md3 model to also draw "dmg" default 2 "speed" default 100 "noise" looping sound to play when the train is in motion "target" next path corner "color" constantLight color "light" constantLight radius
On the path corner: speed departure speed from that corner rotate angle change for X Y Z to next corner duration duration for angle change (overrides speed)
Parameters
[in,out] self
Definition at line 3580 of file g_mover.c.
void SP_info_camp (gentity_t * self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_camp (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
[in] self
Definition at line 52 of file g_misc.c.
void SP_info_limbo_camera (gentity_t * self)
SP_info_limbo_camera.
Parameters
[in,out] self
Definition at line 3272 of file g_mover.c.
void SP_info_notnull (gentity_t * self)
Used as a positional target for in-game calculation, like jumppad targets. target_position does the same thing QUAKED info_notnull (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
self
Definition at line 80 of file g_misc.c.
void SP_info_null (gentity_t * self)
Used as a positional target for calculations in the utilities (spotlights, etc), but removed during gameplay. QUAKED info_null (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
[in,out] self
Definition at line 63 of file g_misc.c.
void SP_info_player_checkpoint (gentity_t * ent)
QUAKED info_player_checkpoint (1 0 0) (-16 -16 -24) (16 16 32) a b c d these are start points /after/ the level start the letter (a b c d) designates the checkpoint that needs to be complete in order to use this start position.
Parameters
[in] ent
Definition at line 99 of file g_client.c.
void SP_info_player_deathmatch (gentity_t * ent)
QUAKED info_player_deathmatch (1 0 1) (-18 -18 -24) (18 18 48) potential spawning position for deathmatch games. Targets will be fired when someone spawns in on them. "nobots" will prevent bots from using this spot. "nohumans" will prevent non-bots from using this spot.
If the start position is targeting an entity, the players camera will start out facing that ent (like an info_notnull)
Parameters
[in,out] ent
Definition at line 67 of file g_client.c.
Referenced by SP_info_player_checkpoint(), and SP_info_player_start().
void SP_info_player_intermission (gentity_t * ent)
QUAKED info_player_intermission (1 0 1) (-16 -16 -24) (16 16 32) AXIS ALLIED The intermission will be viewed from this point. Target an info_notnull for the view direction.
Parameters
ent - unused
Definition at line 122 of file g_client.c.
void SP_info_player_start (gentity_t * ent)
QUAKED info_player_start (1 0 0) (-18 -18 -24) (18 18 48) equivelant to info_player_deathmatch.
Parameters
ent
Definition at line 110 of file g_client.c.
void SP_info_train_spline_main (gentity_t * self)
SP_info_train_spline_main.
QUAKED info_train_spline_main (0 1 0) (-8 -8 -8) (8 8 8) Train spline.
Parameters
[in] self
Definition at line 3158 of file g_mover.c.
void SP_light (gentity_t * self)
QUAKED light (0 1 0) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point q3map_non-dynamic Non-displayed light. "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf) "q3map_non-dynamic" specifies that this light should not contribute to the world's 'light grid' and therefore will not light dynamic models in the game.(wolf)
Parameters
[in] self
Definition at line 98 of file g_misc.c.
void SP_lightJunior (gentity_t * self)
QUAKED lightJunior (0 0.7 0.3) (-8 -8 -8) (8 8 8) nonlinear angle negative_spot negative_point Non-displayed light that only affects dynamic game models, but does not contribute to lightmaps "light" overrides the default 300 intensity. Nonlinear checkbox gives inverse square falloff instead of linear Angle adds light:surface angle calculations (only valid for "Linear" lights) (wolf) Lights pointed at a target will be spotlights. "radius" overrides the default 64 unit radius of a spotlight at the target point. "fade" falloff/radius adjustment value. multiply the run of the slope by "fade" (1.0f default) (only valid for "Linear" lights) (wolf)
Parameters
[in] self
Definition at line 115 of file g_misc.c.
void SP_mg42 (gentity_t * self)
QUAKED misc_mg42 (1 0 0) (-16 -16 -24) (16 16 24) HIGH NOTRIPOD harc = horizonal fire arc Default is 57.5 (left and right) varc = vertical fire arc Default is 45 (upwards and 22.5 down) health = how much damage can it take default is 50 damage = determines how much the weapon will inflict if a non player uses it "accuracy" all guns are 100% accurate an entry of 0.5 would make it 50%.
Parameters
[in,out] self
Definition at line 1941 of file g_misc.c.
void SP_misc_beam (gentity_t * self)
SP_misc_beam.
Parameters
[in,out] self
Definition at line 511 of file g_target.c.
void SP_misc_cabinet_health (gentity_t * self)
SP_misc_cabinet_health.
QUAKED misc_cabinet_health (.5 .5 .5) (-20 -20 0) (20 20 60)
Parameters
[out] self
Definition at line 838 of file g_trigger.c.
void SP_misc_cabinet_supply (gentity_t * self)
SP_misc_cabinet_supply.
QUAKED misc_cabinet_supply (.5 .5 .5) (-20 -20 0) (20 20 60)
Parameters
[in,out] self
Definition at line 1065 of file g_trigger.c.
void SP_misc_commandmap_marker (gentity_t * ent)
Command map marker entity. When set to state default it shows, any other state and it isn't visible. QUAKED misc_commandmap_marker (0 0.85 .85) (-16 -16 0) (16 16 16) ONLY_AXIS ONLY_ALLIED ISOBJECTIVE ISHEALTHAMMOCABINET ISCOMMANDPOST -----— KEYS -----— (none) -----— SPAWNFLAGS -----— (none)
Parameters
[in,out] ent
Definition at line 2455 of file g_misc.c.
void SP_misc_constructiblemarker (gentity_t * ent)
SP_misc_constructiblemarker.
Parameters
[in,out] ent
Definition at line 2331 of file g_misc.c.
void SP_misc_firetrails (gentity_t * ent)
SP_misc_firetrails.
Parameters
[out] ent
Definition at line 2296 of file g_misc.c.
void SP_misc_flak (gentity_t * self)
QUAKED misc_flak (1 0 0) (-32 -32 0) (32 32 100)
Parameters
[in,out] self
Definition at line 2111 of file g_misc.c.
void SP_misc_gamemodel (gentity_t * ent)
QUAKED misc_gamemodel (1 0 0) (-16 -16 -16) (16 16 16) ORIENT_LOD START_ANIMATE md3 placed in the game at runtime (rather than in the bsp) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x, and scales uniformly) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested) "skin" .skin file used to define shaders for model "trunk" diameter of solid core (used for trace visibility and collision (not ai pathing)) "trunkheight" height of trunk.
"frames" number of animation frames "start" frame to start on "fps" fps to animate with
ORIENT_LOD - if flagged, the entity will yaw towards the player when the LOD switches START_ANIMATE - if flagged, the entity will spawn animating
"modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both, the "modelscale" is ignored
Parameters
[in,out] ent
Definition at line 217 of file g_misc.c.
void SP_misc_landmine (gentity_t * ent)
SP_misc_landmine.
Parameters
[in,out] ent
Definition at line 2426 of file g_misc.c.
void SP_misc_light_surface (gentity_t * ent)
QUAKED misc_light_surface (1 .5 0) (-8 -8 -8) (8 8 8) The surfaces nearest these entities will be the only surfaces lit by the targeting light This must be within 64 world units of the surface to be lit!
Parameters
[in] ent
Definition at line 405 of file g_misc.c.
void SP_misc_model (gentity_t * ent)
QUAKED misc_model (1 0 0) (-16 -16 -16) (16 16 16) "model" arbitrary .md3 file to display "modelscale" scale multiplier (defaults to 1x) "modelscale_vec" scale multiplier (defaults to 1 1 1, scales each axis as requested)
"modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both, the "modelscale" is ignored
Parameters
[in] ent
Definition at line 191 of file g_misc.c.
void SP_misc_portal_camera (gentity_t * ent)
QUAKED misc_portal_camera (0 0 1) (-8 -8 -8) (8 8 8) slowrotate fastrotate The target for a misc_portal_director. You can set either angles or target another entity to determine the direction of view. "roll" an angle modifier to orient the camera around the target vector;.
Parameters
ent
Definition at line 494 of file g_misc.c.
void SP_misc_portal_surface (gentity_t * ent)
QUAKED misc_portal_surface (0 0 1) (-8 -8 -8) (8 8 8) The portal surface nearest this entity will show a view from the targeted misc_portal_camera, or a mirror view if untargeted. This must be within 64 world units of the surface!
Parameters
[in,out] ent
Definition at line 468 of file g_misc.c.
void SP_misc_spawner (gentity_t * ent)
QUAKED misc_spawner (.3 .7 .8) (-8 -8 -8) (8 8 8) use the pickup name when this entity gets used it will spawn an item that matches its spawnitem field e.i. spawnitem 9mm.
Parameters
[in,out] ent
Definition at line 2195 of file g_misc.c.
void SP_misc_teleporter_dest (gentity_t * ent)
QUAKED misc_teleporter_dest (1 0 0) (-32 -32 -24) (32 32 -16) Point teleporters at these. Now that we don't have teleport destination pads, this is just an info_notnull.
Parameters
ent - unused
Warning
Do not remove this function - this is just to create a destination spot entity for the teleporter
Definition at line 174 of file g_misc.c.
void SP_misc_vis_dummy (gentity_t * ent)
QUAKED misc_vis_dummy (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. For safety, you should have each dummy only point at one entity (however, it's okay to have many dummies pointing at one entity)
Parameters
[in] ent
Definition at line 357 of file g_misc.c.
void SP_misc_vis_dummy_multiple (gentity_t * ent)
QUAKED misc_vis_dummy_multiple (1 .5 0) (-8 -8 -8) (8 8 8) If this entity is "visible" (in player's PVS) then it's target is forced to be active whether it is in the player's PVS or not. This entity itself is never visible or transmitted to clients. This entity was created to have multiple speakers targeting it.
Parameters
[in] ent
Definition at line 382 of file g_misc.c.
void SP_path_corner (gentity_t * self)
SP_path_corner.
QUAKED path_corner (.5 .3 0) (-8 -8 -8) (8 8 8) STOP END REVERSE Train path corners. Target: next path corner and other targets to fire "speed" speed to move to the next corner "wait" seconds to wait before behining move to next corner
"count2" used only in conjunction with the truck_cam to control playing of gear changes
Parameters
[in,out] self
Definition at line 3106 of file g_mover.c.
void SP_path_corner_2 (gentity_t * self)
QUAKED path_corner_2 (.5 .3 0) (-8 -8 -8) (8 8 8) STOP END REVERSE Train path corners. THIS VERSION WILL NOT CONTRIBUTE TOWARDS INGAME ENTITY COUNT "targetname" The script uses this name to identify the corner.
Parameters
[in,out] self
Definition at line 3129 of file g_mover.c.
void SP_Props_58x112tablew (gentity_t * ent)
SP_Props_58x112tablew.
Parameters
[in,out] ent
Definition at line 3181 of file g_props.c.
void SP_Props_Bench (gentity_t * ent)
SP_Props_Bench.
QUAKED props_bench (.8 .6 .2) ? requires an origin brush health = 10 by default
Parameters
ent
Definition at line 849 of file g_props.c.
void SP_props_box_32 (gentity_t * self)
SP_props_box_32 QUAKED props_box_32 (1 0 0) (-16 -16 -16) (16 16 16)
Parameters
[out] self
Definition at line 163 of file g_props.c.
void SP_props_box_48 (gentity_t * self)
SP_props_box_48 QUAKED props_box_48 (1 0 0) (-24 -24 -24) (24 24 24)
Parameters
[out] self
Definition at line 208 of file g_props.c.
void SP_props_box_64 (gentity_t * self)
SP_props_box_64 QUAKED props_box_64 (1 0 0) (-32 -32 -32) (32 32 32)
Parameters
[out] self
Definition at line 253 of file g_props.c.
void SP_Props_Chair (gentity_t * ent)
SP_Props_Chair.
Parameters
[in,out] ent
Definition at line 1766 of file g_props.c.
void SP_Props_ChairChat (gentity_t * ent)
SP_Props_ChairChat.
Parameters
[in,out] ent
Definition at line 1990 of file g_props.c.
void SP_Props_ChairChatArm (gentity_t * ent)
SP_Props_ChairChatArm.
Parameters
[in,out] ent
Definition at line 2000 of file g_props.c.
void SP_Props_ChairHiback (gentity_t * ent)
SP_Props_ChairHiback.
Parameters
[in,out] ent
Definition at line 1822 of file g_props.c.
void SP_Props_ChairSide (gentity_t * ent)
SP_Props_ChairSide.
Parameters
[in,out] ent
Definition at line 1878 of file g_props.c.
void SP_Props_Crate32x64 (gentity_t * ent)
SP_Props_Crate32x64.
Parameters
[in,out] ent
Definition at line 2872 of file g_props.c.
void SP_Props_DamageInflictor (gentity_t * ent)
SP_Props_DamageInflictor.
QUAKED props_damageinflictor (.8 .6 .6) (-8 -8 -8) (8 8 8) this entity when used will cause 9999 damage to all entities it is targeting then it will be removed
Parameters
[in,out] ent
Definition at line 2040 of file g_props.c.
void SP_props_decor_Scale (gentity_t * ent)
SP_props_decor_Scale.
QUAKED props_decoration_scale (.6 .7 .7) (-8 -8 0) (8 8 16) STARTINVIS DEBRIS ANIMATE KEEPBLOCK TOUCHACTIVATE LOOPING STARTON
"modelscale" - Scale multiplier (defaults to 1.0 and scales uniformly) "modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both the "modelscale" is ignored
"model2" will specify the model to load
"noise" the looping sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
you will need to specify the bounding box for the entity "high" default is 4 "wide" default is 4
"frames" how many frames of animation to play "loop" when the animation is done start again on this frame "startonframe" on what frame do you want to start the animation
Parameters
[in,out] ent
Definition at line 3830 of file g_props.c.
void SP_props_decoration (gentity_t * ent)
SP_props_decoration.
Parameters
[in,out] ent
Definition at line 3609 of file g_props.c.
Referenced by SP_props_decor_Scale(), and SP_props_decorBRUSH().
void SP_props_decorBRUSH (gentity_t * self)
SP_props_decorBRUSH.
QUAKED props_decorBRUSH (.6 .7 .7) ? STARTINVIS DEBRIS ANIMATE KEEPBLOCK - LOOPING STARTON ANIMATE animate on death STARTON playanimation on death must have an origin brush
"model2" will specify the model to load
"noise" the looping sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
"frames" how many frames of animation to play "loop" when the animation is done start again on this frame "startonframe" on what frame do you want to start the animation
Parameters
[in,out] self
Definition at line 3793 of file g_props.c.
void SP_Props_Desklamp (gentity_t * ent)
SP_Props_Desklamp.
QUAKED props_desklamp (.8 .6 .2) (-16 -16 0) (16 16 32) point entity health = default = 10 wait = defaults to 5 how many shards to spawn (try not to exceed 20)
shard = FXTYPE_GLASS = 0, FXTYPE_WOOD = 1, FXTYPE_METAL = 2
Parameters
[in,out] ent
Definition at line 2121 of file g_props.c.
void SP_Props_Flamebarrel (gentity_t * ent)
SP_Props_Flamebarrel.
Parameters
[in,out] ent
Definition at line 2560 of file g_props.c.
void SP_props_flamethrower (gentity_t * ent)
SP_props_flamethrower.
Parameters
[in,out] ent
Definition at line 4755 of file g_props.c.
void SP_Props_Flipping_Table (gentity_t * ent)
SP_Props_Flipping_Table.
Parameters
[in,out] ent
Definition at line 3063 of file g_props.c.
void SP_props_footlocker (gentity_t * self)
SP_props_footlocker.
Parameters
[in,out] self
Todo:
: test this
Definition at line 4484 of file g_props.c.
void SP_props_gunsparks (gentity_t * ent)
SP_props_gunsparks.
QUAKED props_gunsparks (.8 .46 .16) (-8 -8 -8) (8 8 8) the default direction is strait up use info_no_null for alt direction
this entity must be used to see the effect
"speed" default is 20 "health" number to spawn default is 4
Parameters
ent
Definition at line 486 of file g_props.c.
void SP_Props_Locker_Tall (gentity_t * ent)
SP_Props_Locker_Tall.
QUAKED props_locker_tall (.8 .6 .2) ? requires an origin brush
Parameters
ent
Definition at line 1040 of file g_props.c.
void SP_Props_Radio (gentity_t * ent)
SP_Props_Radio.
QUAKED props_radio (.8 .6 .2) ? requires an origin brush health = defaults to 100
Parameters
[in,out] ent
Definition at line 897 of file g_props.c.
void SP_Props_RadioSEVEN (gentity_t * ent)
SP_Props_RadioSEVEN.
QUAKED props_radioSEVEN (.8 .6 .2) ? requires an origin brush health = defaults to 100
the models dims are x 32 y 136 z 32
if you want more explosions you'll need func explosive
it will fire all its targets upon death
Parameters
[in,out] ent
Definition at line 970 of file g_props.c.
void SP_props_snowGenerator (gentity_t * ent)
SP_props_snowGenerator.
Parameters
[in,out] ent
Definition at line 3405 of file g_props.c.
void SP_props_sparks (gentity_t * ent)
SP_props_sparks.
Parameters
[out] ent
Definition at line 426 of file g_props.c.
void SP_props_statue (gentity_t * ent)
SP_props_statue.
Parameters
[in,out] ent
Definition at line 4078 of file g_props.c.
Referenced by SP_props_statueBRUSH().
void SP_props_statueBRUSH (gentity_t * self)
SP_props_statueBRUSH.
QUAKED props_statueBRUSH (.6 .3 .2) ? HURT DEBRIS ANIMATE KEEPBLOCK needs an origin brush
"model2" will specify the model to load
"noise" the sound entity is to make
"type" type of debris ("glass", "wood", "metal", "rubble") default is "wood" "count" how much debris ei. default 4 pieces
"frames" how many frames of animation to play "delay" how long of a delay before damage is inflicted ei. 0.5 sec or 2.7 sec
THE damage has been disabled at the moment "damage" amount of damage to be inflicted
Parameters
[in,out] self
Definition at line 4222 of file g_props.c.
void SP_script_model_med (gentity_t * ent)
SP_script_model_med.
QUAKED script_model_med (0.5 0.25 1.0) (-16 -16 -24) (16 16 64) TriggerSpawn Solid MEDIUM SIZED scripted entity, used for animating a model, moving it around, etc SOLID spawnflag means this entity will clip the player and AI, otherwise they can walk straight through it "model" the full path of the model to use "scriptname" name used for scripting purposes (like aiName in AI scripting)
Parameters
[in,out] ent
Definition at line 1331 of file g_script.c.
void SP_script_mover (gentity_t * ent)
Scripted brush entity. A simplified means of moving brushes around based on events.
QUAKED script_mover (0.5 0.25 1.0) ? TRIGGERSPAWN SOLID EXPLOSIVEDAMAGEONLY RESURECTABLE COMPASS ALLIED AXIS MOUNTED_GUN
"modelscale" - Scale multiplier (defaults to 1, and scales uniformly) "modelscale_vec" - Set scale per-axis. Overrides "modelscale", so if you have both the "modelscale" is ignored "model2" optional md3 to draw over the solid clip brush "scriptname" name used for scripting purposes (like aiName in AI scripting) "health" optionally make this entity damagable "description" used with health, if the entity is damagable, it draws a healthbar with this description above it.
Parameters
[in,out] ent
Definition at line 1124 of file g_script.c.
void SP_script_multiplayer (gentity_t * ent)
This is used to script multiplayer maps. Entity not displayed in game.
QUAKED script_multiplayer (1.0 0.25 1.0) (-8 -8 -8) (8 8 8)
"scriptname" name used for scripting purposes (REQUIRED)
Parameters
[in,out] ent
Note
Also storing some stuff that will change often but needs to be broadcast, so we dont want to use a configstring
Definition at line 1405 of file g_script.c.
void SP_shooter_grenade (gentity_t * ent)
QUAKED shooter_grenade (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" is the number of degrees of deviance from the taget. (1.0 default)
Parameters
[in] ent
Definition at line 677 of file g_misc.c.
void SP_shooter_mortar (gentity_t * ent)
QUAKED shooter_mortar (1 0 0) (-16 -16 -16) (16 16 16) SMOKE_FX FLASH_FX Lobs a mortar so that it will pass through the info_notnull targeted by this entity "random" the number of degrees of deviance from the taget. (1.0 default) if LAUNCH_FX is checked a smoke effect will play at the origin of this entity. if FLASH_FX is checked a muzzle flash effect will play at the origin of this entity.
Parameters
[in] ent
Definition at line 644 of file g_misc.c.
void SP_shooter_rocket (gentity_t * ent)
QUAKED shooter_rocket (1 0 0) (-16 -16 -16) (16 16 16) Fires at either the target or the current direction. "random" the number of degrees of deviance from the taget. (1.0 default)
Parameters
[in] ent
Definition at line 658 of file g_misc.c.
void SP_skyportal (gentity_t * ent)
SP_skyportal.
QUAKED props_skyportal (.6 .7 .7) (-8 -8 0) (8 8 16) "fov" for the skybox default is 90 To have the portal sky fogged, enter any of the following values: "fogcolor" (r g b) (values 0.0-1.0) "fognear" distance from entity to start fogging "fogfar" distance from entity that fog is opaque
Parameters
ent
Definition at line 3869 of file g_props.c.
void SP_SmokeDust (gentity_t * ent)
SP_SmokeDust.
Parameters
[in,out] ent
Definition at line 538 of file g_props.c.
void SP_target_alarm (gentity_t * ent)
QUAKED target_alarm (1 1 0) (-4 -4 -4) (4 4 4) does nothing yet (effectively a relay right now)
Parameters
[out] ent
Definition at line 1070 of file g_target.c.
void SP_target_counter (gentity_t * ent)
QUAKED target_counter (1 1 0) (-8 -8 -8) (8 8 8) Increments the counter pointed to. "count" is the key for the count value.
Parameters
[out] ent
Definition at line 1029 of file g_target.c.
void SP_target_delay (gentity_t * ent)
SP_target_delay.
Parameters
[in,out] ent
Definition at line 149 of file g_target.c.
void SP_target_effect (gentity_t * ent)
SP_target_effect.
QUAKED target_effect (0 .5 .8) (-6 -6 -6) (6 6 6) fire explode smoke rubble gore lowgrav debris "mass" defaults to 15. This determines how much debris is emitted when it explodes. (number of pieces) "dmg" defaults to 0. damage radius blast when triggered "type" - if 'rubble' is specified, this is the model type ("glass", "wood", "metal", "gibs", "brick", "rock", "fabric") default is "wood"
Parameters
[in,out] ent
Todo:
: test this
Definition at line 4232 of file g_mover.c.
void SP_target_explosion (gentity_t * ent)
SP_target_explosion.
Parameters
[in,out] ent
Todo:
: test this
Definition at line 4539 of file g_mover.c.
void SP_target_fog (gentity_t * ent)
SP_target_fog.
QUAKED target_fog (1 1 0) (-8 -8 -8) (8 8 8) color picker chooses color of fog "distance" sets fog distance. Use value '0' to give control back to the game (and use the fog values specified in the sky shader if present) "time" time it takes to change fog to new value. default time is 1 sec
Parameters
[out] ent
Definition at line 995 of file g_target.c.
void SP_target_give (gentity_t * ent)
SP_target_give.
Parameters
[out] ent
Definition at line 80 of file g_target.c.
void SP_target_kill (gentity_t * self)
SP_target_kill.
Parameters
[out] self
Definition at line 893 of file g_target.c.
void SP_target_laser (gentity_t * self)
SP_target_laser.
Parameters
[out] self
Definition at line 664 of file g_target.c.
void SP_target_location (gentity_t * self)
SP_target_location.
QUAKED target_location (0 0.5 0) (-8 -8 -8) (8 8 8) Set "message" to the name of this location. Set "count" to 0-7 for color. 0:white 1:red 2:green 3:yellow 4:blue 5:cyan 6:magenta 7:white
Closest target_location in sight used for the location, if none in site, closest in distance
Parameters
self
Definition at line 919 of file g_target.c.
void SP_target_lock (gentity_t * ent)
SP_target_lock.
QUAKED target_lock (1 1 0) (-8 -8 -8) (8 8 8) Sets the door to a state requiring key n "key" is the required key so: key:0 unlocks the door key:-1 locks the door until a target_lock with key:0 key:n means the door now requires key n
Parameters
[out] ent
Definition at line 1049 of file g_target.c.
void SP_target_position (gentity_t * self)
Used as a positional target for in-game calculation, like jumppad targets.
DEFUNCT target_position (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
self
Definition at line 903 of file g_target.c.
void SP_target_print (gentity_t * ent)
SP_target_print.
Parameters
[out] ent
Definition at line 209 of file g_target.c.
void SP_target_push (gentity_t * self)
SP_target_push.
QUAKED target_push (.5 .5 .5) (-8 -8 -8) (8 8 8) bouncepad Pushes the activator in the direction.of angle, or towards a target apex. "speed" defaults to 1000 if "bouncepad", play bounce noise instead of windfly
Parameters
[in,out] self
Definition at line 424 of file g_trigger.c.
void SP_target_relay (gentity_t * self)
SP_target_relay.
Parameters
[in,out] self
Definition at line 795 of file g_target.c.
void SP_target_remove_powerups (gentity_t * ent)
SP_target_remove_powerups.
Parameters
[out] ent
Definition at line 114 of file g_target.c.
void SP_target_rumble (gentity_t * self)
SP_target_rumble.
Parameters
[in,out] self
Definition at line 1438 of file g_target.c.
void SP_target_script_trigger (gentity_t * ent)
SP_target_script_trigger.
Parameters
[out] ent
Definition at line 1309 of file g_target.c.
void SP_target_smoke (gentity_t * ent)
SP_target_smoke.
Parameters
[in,out] ent
Definition at line 1169 of file g_target.c.
void SP_target_speaker (gentity_t * ent)
SP_target_speaker.
Parameters
[in,out] ent
Definition at line 290 of file g_target.c.
void SP_target_teleporter (gentity_t * self)
The activator will be teleported away. QUAKED target_teleporter (1 0 0) (-8 -8 -8) (8 8 8)
Parameters
[in,out] self
Definition at line 709 of file g_target.c.
void SP_team_CTF_bluespawn (gentity_t * ent)
SP_team_CTF_bluespawn.
QUAKED team_CTF_bluespawn (0 0 1) (-16 -16 -24) (16 16 32) ? INVULNERABLE STARTACTIVE potential spawning position for allied team in wolfdm games.
TODO: SelectRandomTeamSpawnPoint() will choose team_CTF_bluespawn point that:
1) has been activated (active) 2) isn't occupied and 3) is closest to selected team_WOLF_objective
This allows spawnpoints to advance across the battlefield as new ones are placed and/or activated.
If target is set, point spawnpoint toward target activation
Parameters
[in,out] ent
Note
edited quaked def
Definition at line 886 of file g_team.c.
void SP_team_CTF_redspawn (gentity_t * ent)
SP_team_CTF_redspawn.
QUAKED team_CTF_redspawn (1 0 0) (-16 -16 -24) (16 16 32) ? INVULNERABLE STARTACTIVE potential spawning position for axis team in wolfdm games.
TODO: SelectRandomTeamSpawnPoint() will choose team_CTF_redspawn point that:
1) has been activated (FL_SPAWNPOINT_ACTIVE) 2) isn't occupied and 3) is closest to team_WOLF_objective
This allows spawnpoints to advance across the battlefield as new ones are placed and/or activated.
If target is set, point spawnpoint toward target activation
Parameters
[in,out] ent
Note
edited quaked def
Definition at line 846 of file g_team.c.
void SP_team_WOLF_checkpoint (gentity_t * ent)
SP_team_WOLF_checkpoint.
QUAKED team_WOLF_checkpoint (.9 .3 .9) (-16 -16 0) (16 16 128) SPAWNPOINT CP_HOLD AXIS_ONLY ALLIED_ONLY This is the flagpole players touch in Capture and Hold game scenarios.
It will call specific trigger funtions in the map script for this object. When allies capture, it will call "allied_capture". When axis capture, it will call "axis_capture".
if spawnpoint flag is set, think will turn on spawnpoints (specified as targets) for capture team and turn off targeted spawnpoints for opposing team
Parameters
[in,out] ent
Definition at line 1437 of file g_team.c.
void SP_team_WOLF_objective (gentity_t * ent)
SP_team_WOLF_objective.
Parameters
[in,out] ent
Todo:
: wtf is this g_alloced? just use a static buffer fgs...
Definition at line 976 of file g_team.c.
void SP_trigger_always (gentity_t * ent)
This trigger will always fire. It is activated by the world.
QUAKED trigger_always (.5 .5 .5) (-8 -8 -8) (8 8 8)
Parameters
ent
Definition at line 306 of file g_trigger.c.
void SP_trigger_ammo (gentity_t * self)
SP_trigger_ammo.
Parameters
[in,out] self
Definition at line 1085 of file g_trigger.c.
void SP_trigger_concussive_dust (gentity_t * self)
SP_trigger_concussive_dust.
QUAKED trigger_concussive_dust (.5 .5 .5) ? Allows client side prediction of teleportation events. Must point at a target_position, which will be the teleport destination.
Parameters
[in] self
Definition at line 1926 of file g_trigger.c.
void SP_trigger_flagonly (gentity_t * ent)
SP_trigger_flagonly.
QUAKED trigger_flagonly (.5 .5 .5) ? RED_FLAG BLUE_FLAG KILL_FLAG Player must be carrying the proper flag for it to trigger. It will call the "death" function in the object's script.
"scriptName" The object name in the script file
RED_FLAG – only trigger if player is carrying red flag BLUE_FLAG – only trigger if player is carrying blue flag
Parameters
[in,out] ent
Definition at line 1408 of file g_trigger.c.
void SP_trigger_flagonly_multiple (gentity_t * ent)
SP_trigger_flagonly_multiple.
QUAKED trigger_flagonly_multiple (.5 .5 .5) ? RED_FLAG BLUE_FLAG Player must be carrying the proper flag for it to trigger. It will call the "death" function in the object's script.
"scriptName" The object name in the script file
RED_FLAG – only trigger if player is carrying red flag BLUE_FLAG – only trigger if player is carrying blue flag
Parameters
ent
Definition at line 1443 of file g_trigger.c.
void SP_trigger_heal (gentity_t * self)
SP_trigger_heal.
Parameters
[in,out] self
Definition at line 858 of file g_trigger.c.
void SP_trigger_hurt (gentity_t * self)
SP_trigger_hurt.
Parameters
[in,out] self
Definition at line 626 of file g_trigger.c.
void SP_trigger_multiple (gentity_t * ent)
SP_trigger_multiple.
QUAKED trigger_multiple (.5 .5 .5) ? AXIS_ONLY ALLIED_ONLY NOBOT BOTONLY SOLDIERONLY LTONLY MEDICONLY ENGINEERONLY COVERTOPSONLY "wait" : Seconds between triggerings, 0.5 default, -1 = one time only. "random" wait variance, default is 0 Variable sized repeatable trigger. Must be targeted at one or more entities. so, the basic time between firing is a random time between (wait - random) and (wait + random)
Parameters
[in,out] ent
Definition at line 260 of file g_trigger.c.
void SP_trigger_objective_info (gentity_t * ent)
QUAKED trigger_objective_info (.5 .5 .5) ? AXIS_OBJECTIVE ALLIED_OBJECTIVE MESSAGE_OVERRIDE TANK IS_OBJECTIVE IS_HEALTHAMMOCABINET IS_COMMANDPOST Players in this field will see a message saying that they are near an objective.
"track" Mandatory, this is the text that is appended to "You are near " "shortname" Short name to show on command centre
Parameters
[in,out] ent
Definition at line 1801 of file g_trigger.c.
void SP_trigger_once (gentity_t * ent)
SP_trigger_once.
QUAKED trigger_once (.5 .5 .5) ? AI_Touch Must be targeted at one or more entities. Once triggered, this entity is destroyed (you can actually do the same thing with trigger_multiple with a wait of -1)
Parameters
[out] ent
Definition at line 1217 of file g_trigger.c.
void SP_trigger_push (gentity_t * self)
SP_trigger_push.
QUAKED trigger_push (.5 .5 .5) ? TOGGLE REMOVEAFTERTOUCH PUSHPLAYERONLY Must point at a target_position, which will be the apex of the leap. This will be client side predicted, unlike target_push
Parameters
self - unused
Definition at line 381 of file g_trigger.c.
void SP_trigger_teleport (gentity_t * self)
QUAKED trigger_teleport (.5 .5 .5) ? Allows client side prediction of teleportation events. Must point at a target_position, which will be the teleport destination.
Parameters
[out] self
Definition at line 493 of file g_trigger.c.
void SP_worldspawn (void)
Every map should have exactly one worldspawn.
QUAKED worldspawn (0 0 0) ? NO_GT_WOLF NO_GT_STOPWATCH NO_GT_CHECKPOINT NO_LMS
"music" Music wav file "gravity" 800 is default gravity "message" Text to print during connection process "ambient" Ambient light value (must use '_color') "_color" Ambient light color (must be used with 'ambient') "sun" Shader to use for 'sun' image
Definition at line 948 of file g_spawn.c.
Referenced by G_SpawnEntitiesFromString().
Variable Documentation
field_t fields[]
Definition at line 153 of file g_spawn.c.
Referenced by etpro_ScriptAction_SetValues().
spawn_t spawns[]
Definition at line 432 of file g_spawn.c.