ET: Legacy: src/game/g_team.c File Reference
g_team.c File Reference
#include <limits.h>
#include "g_local.h"
#include "g_etbot_interface.h"
Macros
#define WCP_ANIM_NOFLAG 0
#define WCP_ANIM_RAISE_AXIS 1
#define WCP_ANIM_RAISE_AMERICAN 2
#define WCP_ANIM_AXIS_RAISED 3
#define WCP_ANIM_AMERICAN_RAISED 4
#define WCP_ANIM_AXIS_TO_AMERICAN 5
#define WCP_ANIM_AMERICAN_TO_AXIS 6
#define WCP_ANIM_AXIS_FALLING 7
#define WCP_ANIM_AMERICAN_FALLING 8
#define MAX_TEAM_SPAWN_POINTS 256
#define SPAWNPOINT 1
#define CP_HOLD 2
#define AXIS_ONLY 4
#define ALLIED_ONLY 8
Functions
int OtherTeam (int team)
OtherTeam.
const char * TeamName (int team)
TeamName.
const char * TeamColorString (int team)
TeamColorString.
void QDECL PrintMsg (gentity_t *ent, const char *fmt,...)
PrintMsg.
qboolean OnSameTeam (gentity_t *ent1, gentity_t *ent2)
OnSameTeam.
void Team_ResetFlag (gentity_t *ent)
Team_ResetFlag.
void Team_ReturnFlagSound (gentity_t *ent, int team)
Team_ReturnFlagSound.
void Team_ReturnFlag (gentity_t *ent)
Team_ReturnFlag.
void Team_DroppedFlagThink (gentity_t *ent)
Automatically set in Launch_Item if the item is one of the flags.
int Team_TouchOurFlag (gentity_t *ent, gentity_t *other, int team)
Team_TouchOurFlag.
int Team_TouchEnemyFlag (gentity_t *ent, gentity_t *other, int team)
Team_TouchEnemyFlag.
int Pickup_Team (gentity_t *ent, gentity_t *other)
Pickup_Team.
void G_globalFlagIndicator ()
G_globalFlagIndicator.
void G_clientFlagIndicator (gentity_t *ent)
G_clientFlagIndicator.
gentity_t * SelectRandomTeamSpawnPoint (int teamstate, team_t team, int spawnObjective)
Go to a random point that doesn't telefrag.
gentity_t * SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, int spawnObjective)
SelectCTFSpawnPoint.
void TeamplayInfoMessage (team_t team)
TeamplayInfoMessage.
void CheckTeamStatus (void)
CheckTeamStatus.
void Use_Team_Spawnpoint (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Team_Spawnpoint.
void DropToFloor (gentity_t *ent)
DropToFloor.
void SP_team_CTF_redspawn (gentity_t *ent)
SP_team_CTF_redspawn.
void SP_team_CTF_bluespawn (gentity_t *ent)
SP_team_CTF_bluespawn.
void team_wolf_objective_use (gentity_t *self, gentity_t *other, gentity_t *activator)
Swaps the team.
void objective_Register (gentity_t *self)
objective_Register
void SP_team_WOLF_objective (gentity_t *ent)
SP_team_WOLF_objective.
void checkpoint_touch (gentity_t *self, gentity_t *other, trace_t *trace)
checkpoint_touch
void checkpoint_use_think (gentity_t *self)
checkpoint_use_think
void checkpoint_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
checkpoint_use
void checkpoint_spawntouch (gentity_t *self, gentity_t *other, trace_t *trace)
If spawn flag is set, use this touch fn instead to turn on/off targeted spawnpoints.
void checkpoint_hold_think (gentity_t *self)
checkpoint_hold_think
void checkpoint_think (gentity_t *self)
checkpoint_think
void SP_team_WOLF_checkpoint (gentity_t *ent)
SP_team_WOLF_checkpoint.
void G_teamReset (int team_num, qboolean fClearSpecLock)
Resets a team's settings.
void G_swapTeams (void)
Swaps active players on teams.
int QDECL G_SortPlayersByXP (const void *a, const void *b)
G_SortPlayersByXP.
void G_shuffleTeamsXP (void)
Shuffle active players onto teams.
qboolean G_checkReady (void)
Determine if the "ready" player threshold has been reached.
qboolean G_readyMatchState (void)
Checks ready states to start/stop the sequence to get the match rolling.
void G_verifyMatchState (team_t nTeam)
Check if we need to reset the game state due to an empty team.
qboolean G_teamJoinCheck (team_t nTeam, gentity_t *ent)
Checks to see if a specified team is allowing players to join.
void G_updateSpecLock (int nTeam, qboolean fLock)
Update specs for blackout, as needed.
void G_swapTeamLocks (void)
Swap team speclocks.
void G_removeSpecInvite (int team)
Removes everyone's specinvite for a particular team.
int G_blockoutTeam (gentity_t *ent, int nTeam)
Return blockout status for a player.
qboolean G_allowFollow (gentity_t *ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
qboolean G_desiredFollow (gentity_t *ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
static int G_ResolveSpawnPointIndex (team_t team, int targetSpawnPt)
Finds suitable spawn point index for the given team. If player selected spawn point is invalid, tries to resolve it.
static int G_ConvertToSpawnPointIndex (int spawnPointValue, int defaultSpawnPointIndex)
Converts spawn point value into spawn point index.
void G_UpdateSpawnPointStatePlayerCounts ()
Udates player counts in all spawn point states.
void G_UpdateSpawnPointState (gentity_t *ent)
Udates spawn point state.
Variables
const char * aTeams [TEAM_NUM_TEAMS] = { "FFA", "^1Axis^7", "^$Allies^7", "^2Spectators^7" }
team_info teamInfo [TEAM_NUM_TEAMS]
Macro Definition Documentation
#define ALLIED_ONLY 8
Definition at line 1004 of file g_team.c.
Referenced by checkpoint_spawntouch().
#define AXIS_ONLY 4
Definition at line 1003 of file g_team.c.
Referenced by checkpoint_spawntouch().
#define CP_HOLD 2
Definition at line 1002 of file g_team.c.
Referenced by checkpoint_think(), and SP_team_WOLF_checkpoint().
#define MAX_TEAM_SPAWN_POINTS 256
Definition at line 537 of file g_team.c.
Referenced by SelectRandomTeamSpawnPoint().
#define SPAWNPOINT 1
Definition at line 1001 of file g_team.c.
Referenced by checkpoint_think(), and SP_team_WOLF_checkpoint().
#define WCP_ANIM_AMERICAN_FALLING 8
Definition at line 168 of file g_team.c.
Referenced by checkpoint_spawntouch(), and checkpoint_think().
#define WCP_ANIM_AMERICAN_RAISED 4
Definition at line 164 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), and checkpoint_touch().
#define WCP_ANIM_AMERICAN_TO_AXIS 6
Definition at line 166 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), and checkpoint_touch().
#define WCP_ANIM_AXIS_FALLING 7
Definition at line 167 of file g_team.c.
Referenced by checkpoint_spawntouch(), and checkpoint_think().
#define WCP_ANIM_AXIS_RAISED 3
Definition at line 163 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), and checkpoint_touch().
#define WCP_ANIM_AXIS_TO_AMERICAN 5
Definition at line 165 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), and checkpoint_touch().
#define WCP_ANIM_NOFLAG 0
Definition at line 160 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), checkpoint_touch(), and SP_team_WOLF_checkpoint().
#define WCP_ANIM_RAISE_AMERICAN 2
Definition at line 162 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), and checkpoint_touch().
#define WCP_ANIM_RAISE_AXIS 1
Definition at line 161 of file g_team.c.
Referenced by checkpoint_spawntouch(), checkpoint_think(), and checkpoint_touch().
Function Documentation
void checkpoint_hold_think (gentity_t * self)
checkpoint_hold_think
Parameters
[out] self
Note
Unused
Definition at line 1115 of file g_team.c.
void checkpoint_spawntouch (gentity_t * self, gentity_t * other, trace_t * trace)
If spawn flag is set, use this touch fn instead to turn on/off targeted spawnpoints.
Parameters
[in,out] self
[in,out] other
trace - unused
Definition at line 1249 of file g_team.c.
Referenced by checkpoint_think(), checkpoint_use(), and SP_team_WOLF_checkpoint().
void checkpoint_think (gentity_t * self)
checkpoint_think
Parameters
[in,out] self
Definition at line 1124 of file g_team.c.
Referenced by checkpoint_spawntouch(), and checkpoint_touch().
void checkpoint_touch (gentity_t * self, gentity_t * other, trace_t * trace)
checkpoint_touch
Parameters
[in,out] self
[in,out] other
trace - unused
Definition at line 1173 of file g_team.c.
Referenced by checkpoint_think(), checkpoint_use(), and SP_team_WOLF_checkpoint().
void checkpoint_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
checkpoint_use
Parameters
[in,out] ent
[out] other
[in] activator
Definition at line 1032 of file g_team.c.
Referenced by SP_team_WOLF_checkpoint().
void checkpoint_use_think (gentity_t * self)
checkpoint_use_think
Parameters
[in,out] self
Definition at line 1012 of file g_team.c.
Referenced by checkpoint_use().
void CheckTeamStatus (void)
CheckTeamStatus.
Definition at line 776 of file g_team.c.
Referenced by G_RunFrame().
void DropToFloor (gentity_t * ent)
DropToFloor.
Parameters
[in,out] ent
Definition at line 63 of file g_props.c.
Referenced by SP_crate_32(), SP_crate_64(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_team_CTF_bluespawn(), SP_team_CTF_redspawn(), and Use_Team_Spawnpoint().
qboolean G_allowFollow (gentity_t * ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
Parameters
[in] ent
[in] nTeam
Returns
Definition at line 2076 of file g_team.c.
Referenced by Cmd_Follow_f(), G_blockoutTeam(), G_desiredFollow(), and SpectatorThink().
int G_blockoutTeam (gentity_t * ent, int nTeam)
Return blockout status for a player.
Parameters
[in] ent
[in] nTeam
Returns
Definition at line 2065 of file g_team.c.
Referenced by SpectatorClientEndFrame().
qboolean G_checkReady (void)
Determine if the "ready" player threshold has been reached.
Returns
Definition at line 1778 of file g_team.c.
Referenced by G_readyMatchState(), and G_verifyMatchState().
void G_clientFlagIndicator (gentity_t * ent)
G_clientFlagIndicator.
Parameters
[in] flagIndicator
Definition at line 522 of file g_team.c.
Referenced by ClientBegin().
static int G_ConvertToSpawnPointIndex (int spawnPointValue, int defaultSpawnPointIndex) static
Converts spawn point value into spawn point index.
Parameters
[in] spawnPointValue
[in] defaultSpawnPointIndex
Returns
Definition at line 2187 of file g_team.c.
Referenced by G_UpdateSpawnPointStatePlayerCounts().
qboolean G_desiredFollow (gentity_t * ent, int nTeam)
Figure out if we are allowed/want to follow a given player.
Parameters
[in] ent
[in] nTeam
Returns
Definition at line 2112 of file g_team.c.
Referenced by Cmd_FollowCycle_f(), and G_FollowSame().
void G_globalFlagIndicator (void)
G_globalFlagIndicator.
Parameters
[in] flagIndicator
Definition at line 506 of file g_team.c.
Referenced by G_DropItems(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), Touch_flagonly(), and Touch_flagonly_multiple().
qboolean G_readyMatchState (void)
Checks ready states to start/stop the sequence to get the match rolling.
Returns
Definition at line 1828 of file g_team.c.
Referenced by CheckWolfMP(), G_ready_cmd(), G_refAllReady_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), and G_teamready_cmd().
void G_removeSpecInvite (int team)
Removes everyone's specinvite for a particular team.
Parameters
[in] team
Note
Unused
Definition at line 2042 of file g_team.c.
static int G_ResolveSpawnPointIndex (team_t team, int targetSpawnPt) static
Finds suitable spawn point index for the given team. If player selected spawn point is invalid, tries to resolve it.
Parameters
[in] team
[in] targetSpawnPt Player selected spawn point.
Returns
Spawn point index or -1.
Definition at line 2130 of file g_team.c.
Referenced by G_UpdateSpawnPointStatePlayerCounts().
void G_shuffleTeamsXP (void)
Shuffle active players onto teams.
Definition at line 1648 of file g_team.c.
Referenced by Svcmd_ShuffleTeamsXP_f().
int QDECL G_SortPlayersByXP (const void * a, const void * b)
G_SortPlayersByXP.
Parameters
[in] a
[in] b
Returns
Definition at line 1603 of file g_team.c.
Referenced by G_shuffleTeamsXP().
void G_swapTeamLocks (void)
Swap team speclocks.
Definition at line 2025 of file g_team.c.
Referenced by G_InitWorldSession().
void G_swapTeams (void)
Swaps active players on teams.
Definition at line 1562 of file g_team.c.
Referenced by Svcmd_SwapTeams_f().
qboolean G_teamJoinCheck (team_t nTeam, gentity_t * ent)
Checks to see if a specified team is allowing players to join.
Parameters
[in] nTeam
[in] ent
Returns
Definition at line 1900 of file g_team.c.
Referenced by G_TeamDataForString(), and SetTeam().
void G_teamReset (int team_num, qboolean fClearSpecLock)
Resets a team's settings.
Parameters
[in] team_num
[in] fClearSpecLock
Definition at line 1546 of file g_team.c.
Referenced by G_initMatch(), G_shuffleTeamsXP(), G_swapTeams(), G_teamJoinCheck(), and G_verifyMatchState().
void G_UpdateSpawnPointState (gentity_t * ent)
Udates spawn point state.
Parameters
[in] ent wolf_objective entity.
Returns
Definition at line 2261 of file g_team.c.
Referenced by G_SetEntState(), objective_Register(), and team_wolf_objective_use().
void G_UpdateSpawnPointStatePlayerCounts ()
Udates player counts in all spawn point states.
Returns
Definition at line 2200 of file g_team.c.
Referenced by ClientSpawn(), G_ScriptAction_SetAutoSpawn(), G_UpdateSpawnPointState(), and SetPlayerSpawn().
void G_updateSpecLock (int nTeam, qboolean fLock)
Update specs for blackout, as needed.
Parameters
[in] nTeam
[in] fLock
Definition at line 1964 of file g_team.c.
Referenced by G_refSpeclockTeams_cmd(), and G_speclock_cmd().
void G_verifyMatchState (team_t nTeam)
Check if we need to reset the game state due to an empty team.
Parameters
[in] nTeam
Definition at line 1862 of file g_team.c.
Referenced by ClientDisconnect(), and SetTeam().
void objective_Register (gentity_t * self)
objective_Register
Parameters
[in,out] self
Definition at line 945 of file g_team.c.
Referenced by SP_team_WOLF_objective().
qboolean OnSameTeam (gentity_t * ent1, gentity_t * ent2)
OnSameTeam.
Parameters
[in] ent1
[in] ent2
Returns
Definition at line 145 of file g_team.c.
Referenced by AccuracyHit(), Cmd_God_f(), G_BurnTarget(), G_Damage(), G_SayTo(), G_VoiceTo(), isMortalSelfDamage(), and player_die().
int OtherTeam (int team)
OtherTeam.
Parameters
[in] team
Returns
Note
Unused
Definition at line 50 of file g_team.c.
int Pickup_Team (gentity_t * ent, gentity_t * other)
Pickup_Team.
Parameters
[in] ent
[in,out] other
Returns
Definition at line 464 of file g_team.c.
Referenced by Touch_Item().
void QDECL PrintMsg (gentity_t * ent, const char * fmt, ...)
PrintMsg.
Parameters
ent
fmt
Note
NULL for everyone
Definition at line 116 of file g_team.c.
Referenced by Pickup_Team(), and Team_ReturnFlag().
gentity_t* SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, int spawnObjective)
SelectCTFSpawnPoint.
Parameters
[in] team
[in] teamstate
[in,out] origin
[in,out] angles
[in] spawnObjective
Returns
Definition at line 678 of file g_team.c.
Referenced by ClientSpawn().
gentity_t* SelectRandomTeamSpawnPoint (int teamstate, team_t team, int spawnObjective)
Go to a random point that doesn't telefrag.
Parameters
teamstate - unused
[in] team
[in] spawnObjective
Returns
Definition at line 546 of file g_team.c.
Referenced by SelectCTFSpawnPoint().
void SP_team_CTF_bluespawn (gentity_t * ent)
SP_team_CTF_bluespawn.
QUAKED team_CTF_bluespawn (0 0 1) (-16 -16 -24) (16 16 32) ? INVULNERABLE STARTACTIVE potential spawning position for allied team in wolfdm games.
TODO: SelectRandomTeamSpawnPoint() will choose team_CTF_bluespawn point that:
1) has been activated (active) 2) isn't occupied and 3) is closest to selected team_WOLF_objective
This allows spawnpoints to advance across the battlefield as new ones are placed and/or activated.
If target is set, point spawnpoint toward target activation
Parameters
[in,out] ent
Note
edited quaked def
Definition at line 886 of file g_team.c.
void SP_team_CTF_redspawn (gentity_t * ent)
SP_team_CTF_redspawn.
QUAKED team_CTF_redspawn (1 0 0) (-16 -16 -24) (16 16 32) ? INVULNERABLE STARTACTIVE potential spawning position for axis team in wolfdm games.
TODO: SelectRandomTeamSpawnPoint() will choose team_CTF_redspawn point that:
1) has been activated (FL_SPAWNPOINT_ACTIVE) 2) isn't occupied and 3) is closest to team_WOLF_objective
This allows spawnpoints to advance across the battlefield as new ones are placed and/or activated.
If target is set, point spawnpoint toward target activation
Parameters
[in,out] ent
Note
edited quaked def
Definition at line 846 of file g_team.c.
void SP_team_WOLF_checkpoint (gentity_t * ent)
SP_team_WOLF_checkpoint.
QUAKED team_WOLF_checkpoint (.9 .3 .9) (-16 -16 0) (16 16 128) SPAWNPOINT CP_HOLD AXIS_ONLY ALLIED_ONLY This is the flagpole players touch in Capture and Hold game scenarios.
It will call specific trigger funtions in the map script for this object. When allies capture, it will call "allied_capture". When axis capture, it will call "axis_capture".
if spawnpoint flag is set, think will turn on spawnpoints (specified as targets) for capture team and turn off targeted spawnpoints for opposing team
Parameters
[in,out] ent
Definition at line 1437 of file g_team.c.
void SP_team_WOLF_objective (gentity_t * ent)
SP_team_WOLF_objective.
Parameters
[in,out] ent
Todo:
: wtf is this g_alloced? just use a static buffer fgs...
Definition at line 976 of file g_team.c.
void Team_DroppedFlagThink (gentity_t * ent)
Automatically set in Launch_Item if the item is one of the flags.
Flags are unique in that if they are dropped, the base flag must be respawned when they time out
Parameters
[in] ent
Definition at line 265 of file g_team.c.
Referenced by Blocked_Door(), Blocked_DoorRotate(), func_constructible_explode(), G_SetEntState(), HandleEntsThatBlockConstructible(), LaunchItem(), and script_mover_blocked().
void Team_ResetFlag (gentity_t * ent)
Team_ResetFlag.
Parameters
[in] ent
Definition at line 174 of file g_team.c.
Referenced by Team_DroppedFlagThink(), Team_ReturnFlag(), and Team_TouchOurFlag().
void Team_ReturnFlag (gentity_t * ent)
Team_ReturnFlag.
Parameters
[in] ent
Todo:
: returns RED/BLUE flag ... change to Axis/Allies?
Definition at line 249 of file g_team.c.
Referenced by G_RunItem(), and Use_target_remove_powerups().
void Team_ReturnFlagSound (gentity_t * ent, int team)
Team_ReturnFlagSound.
Parameters
[in] ent
[in] team
Definition at line 228 of file g_team.c.
Referenced by Team_DroppedFlagThink(), Team_ReturnFlag(), and Team_TouchOurFlag().
int Team_TouchEnemyFlag (gentity_t * ent, gentity_t * other, int team)
Team_TouchEnemyFlag.
Parameters
[in,out] ent
[out] other
[in] team
Returns
Definition at line 366 of file g_team.c.
Referenced by Pickup_Team().
int Team_TouchOurFlag (gentity_t * ent, gentity_t * other, int team)
Team_TouchOurFlag.
Parameters
[in] ent
[in] other
[in] team
Returns
Definition at line 301 of file g_team.c.
Referenced by Pickup_Team().
void team_wolf_objective_use (gentity_t * self, gentity_t * other, gentity_t * activator)
Swaps the team.
QUAKED team_WOLF_objective (1 1 0.3) (-16 -16 -24) (16 16 32) DEFAULT_AXIS DEFAULT_ALLIES marker for objective
This marker will be used for computing effective radius for dynamite damage, as well as generating a list of objectives that players can elect to spawn near to in the limbo spawn screen.
"description"   short text key for objective name that will appear in objective selection in limbo UI.
DEFAULT_AXIS - This spawn region belongs to the Axis at the start of the map DEFAULT_ALLIES - This spawn region belongs to the Alles at the start of the map
Parameters
[in,out] self
other - unused
activator - unused
Definition at line 926 of file g_team.c.
Referenced by objective_Register().
const char* TeamColorString (int team)
TeamColorString.
Parameters
[in] team
Returns
Note
Unused
Definition at line 92 of file g_team.c.
const char* TeamName (int team)
TeamName.
Parameters
[in] team
Returns
Definition at line 68 of file g_team.c.
Referenced by Team_ReturnFlag().
void TeamplayInfoMessage (team_t team)
TeamplayInfoMessage.
Format: clientNum location health armor weapon powerups
Parameters
[in] team
Definition at line 703 of file g_team.c.
Referenced by CheckTeamStatus().
void Use_Team_Spawnpoint (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Team_Spawnpoint.
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 808 of file g_team.c.
Referenced by SP_team_CTF_bluespawn(), and SP_team_CTF_redspawn().
Variable Documentation
const char* aTeams[TEAM_NUM_TEAMS] = { "FFA", "^1Axis^7", "^$Allies^7", "^2Spectators^7" }
Definition at line 1538 of file g_team.c.
Referenced by Cmd_Follow_f(), G_lock_cmd(), G_pause_cmd(), G_players_cmd(), G_printMatchInfo(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_specinvite_cmd(), G_speclock_cmd(), G_teamJoinCheck(), and G_teamready_cmd().
team_info teamInfo[TEAM_NUM_TEAMS]
Definition at line 1539 of file g_team.c.