ET: Legacy: src/game/g_trigger.c File Reference
g_trigger.c File Reference
#include "g_local.h"
Macros
#define HEALTH_REGENTIME 10000
#define TRIGGER_HEAL_CANTHINK(self) self->count != -9999
#define AMMO_REGENTIME 60000
#define TRIGGER_AMMO_CANTHINK(self) self->count != -9999
#define RED_FLAG 1
#define BLUE_FLAG 2
#define AXIS_OBJECTIVE 1
#define ALLIED_OBJECTIVE 2
#define MESSAGE_OVERRIDE 4
#define TANK 8
Functions
void InitTrigger (gentity_t *self)
InitTrigger.
void multi_wait (gentity_t *ent)
The wait time has passed, so set back up for another activation.
void multi_trigger (gentity_t *ent, gentity_t *activator)
The trigger was just activated.
void Use_Multi (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Multi.
void Touch_Multi (gentity_t *self, gentity_t *other, trace_t *trace)
Touch_Multi.
void SP_trigger_multiple (gentity_t *ent)
SP_trigger_multiple.
void trigger_always_think (gentity_t *ent)
trigger_always_think
void SP_trigger_always (gentity_t *ent)
This trigger will always fire. It is activated by the world.
void AimAtTarget (gentity_t *self)
Calculate origin2 so the target apogee will be hit.
void SP_trigger_push (gentity_t *self)
SP_trigger_push.
void Use_target_push (gentity_t *self, gentity_t *other, gentity_t *activator)
Use_target_push.
void SP_target_push (gentity_t *self)
SP_target_push.
void trigger_teleporter_touch (gentity_t *self, gentity_t *other, trace_t *trace)
trigger_teleporter_touch
void SP_trigger_teleport (gentity_t *self)
QUAKED trigger_teleport (.5 .5 .5) ? Allows client side prediction of teleportation events. Must point at a target_position, which will be the teleport destination.
void hurt_touch (gentity_t *self, gentity_t *other, trace_t *trace)
hurt_touch
void hurt_think (gentity_t *ent)
hurt_think
void hurt_use (gentity_t *self, gentity_t *other, gentity_t *activator)
hurt_use
void SP_trigger_hurt (gentity_t *self)
SP_trigger_hurt.
qboolean G_IsAllowedHeal (gentity_t *ent)
G_IsAllowedHeal.
void heal_touch (gentity_t *self, gentity_t *other, trace_t *trace)
heal_touch
void trigger_heal_think (gentity_t *self)
trigger_heal_think
void trigger_heal_setup (gentity_t *self)
trigger_heal_setup
void SP_misc_cabinet_health (gentity_t *self)
SP_misc_cabinet_health.
void SP_trigger_heal (gentity_t *self)
SP_trigger_heal.
qboolean G_IsAllowedAmmo (gentity_t *ent)
G_IsAllowedAmmo.
void ammo_touch (gentity_t *self, gentity_t *other, trace_t *trace)
ammo_touch
void trigger_ammo_think (gentity_t *self)
trigger_ammo_think
void trigger_ammo_setup (gentity_t *self)
trigger_ammo_setup
void SP_misc_cabinet_supply (gentity_t *self)
SP_misc_cabinet_supply.
void SP_trigger_ammo (gentity_t *self)
SP_trigger_ammo.
void func_timer_think (gentity_t *self)
func_timer_think
void func_timer_use (gentity_t *self, gentity_t *other, gentity_t *activator)
func_timer_use
void SP_func_timer (gentity_t *self)
SP_func_timer.
void SP_trigger_once (gentity_t *ent)
SP_trigger_once.
void Bot_Util_SendTrigger (gentity_t *_ent, gentity_t *_activator, const char *_tagname, const char *_action)
void Touch_flagonly (gentity_t *ent, gentity_t *other, trace_t *trace)
Touch_flagonly.
void Touch_flagonly_multiple (gentity_t *ent, gentity_t *other, trace_t *trace)
Touch_flagonly_multiple.
void SP_trigger_flagonly (gentity_t *ent)
SP_trigger_flagonly.
void SP_trigger_flagonly_multiple (gentity_t *ent)
SP_trigger_flagonly_multiple.
void explosive_indicator_think (gentity_t *ent)
Spawn an explosive indicator.
void constructible_indicator_think (gentity_t *ent)
Spawn a constructible indicator.
void G_SetConfigStringValue (int num, const char *key, const char *value)
G_SetConfigStringValue.
void Touch_ObjectiveInfo (gentity_t *ent, gentity_t *other, trace_t *trace)
Touch_ObjectiveInfo.
void Think_SetupObjectiveInfo (gentity_t *ent)
Links the trigger to it's objective, determining if it's a func_explosive of func_constructible and spawning the right indicator.
void SP_trigger_objective_info (gentity_t *ent)
QUAKED trigger_objective_info (.5 .5 .5) ? AXIS_OBJECTIVE ALLIED_OBJECTIVE MESSAGE_OVERRIDE TANK IS_OBJECTIVE IS_HEALTHAMMOCABINET IS_COMMANDPOST Players in this field will see a message saying that they are near an objective.
void SP_trigger_concussive_dust (gentity_t *self)
SP_trigger_concussive_dust.
Macro Definition Documentation
#define ALLIED_OBJECTIVE 2
Definition at line 1788 of file g_trigger.c.
Referenced by Think_SetupObjectiveInfo().
#define AMMO_REGENTIME 60000
Definition at line 1020 of file g_trigger.c.
Referenced by SP_trigger_ammo(), and trigger_ammo_think().
#define AXIS_OBJECTIVE 1
Definition at line 1787 of file g_trigger.c.
Referenced by Think_SetupObjectiveInfo().
#define BLUE_FLAG 2
Definition at line 1230 of file g_trigger.c.
Referenced by Touch_flagonly(), and Touch_flagonly_multiple().
#define HEALTH_REGENTIME 10000
Definition at line 793 of file g_trigger.c.
Referenced by SP_trigger_heal(), and trigger_heal_think().
#define MESSAGE_OVERRIDE 4
Definition at line 1789 of file g_trigger.c.
Referenced by SP_trigger_objective_info().
#define RED_FLAG 1
Definition at line 1229 of file g_trigger.c.
Referenced by Touch_flagonly(), and Touch_flagonly_multiple().
#define TANK 8
Definition at line 1790 of file g_trigger.c.
#define TRIGGER_AMMO_CANTHINK (self) self->count != -9999
Definition at line 1037 of file g_trigger.c.
Referenced by SP_trigger_ammo(), and trigger_ammo_setup().
#define TRIGGER_HEAL_CANTHINK (self) self->count != -9999
Definition at line 810 of file g_trigger.c.
Referenced by SP_trigger_heal(), and trigger_heal_setup().
Function Documentation
void AimAtTarget (gentity_t * self)
Calculate origin2 so the target apogee will be hit.
Parameters
[in,out] self
Definition at line 335 of file g_trigger.c.
Referenced by SP_target_push(), and Use_Shooter().
void ammo_touch (gentity_t * self, gentity_t * other, trace_t * trace)
ammo_touch
Parameters
[in,out] self
[in] other
trace - unused
Definition at line 945 of file g_trigger.c.
Referenced by SP_trigger_ammo().
void Bot_Util_SendTrigger (gentity_t * _ent, gentity_t * _activator, const char * _tagname, const char * _action)
Definition at line 7159 of file g_etbot_interface.cpp.
Referenced by Bot_Interface_Update(), checkpoint_spawntouch(), G_DropItems(), G_LogExit(), G_Script_ScriptEvent(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_FaceAngles(), G_ScriptAction_GotoMarker(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_RepairMG42(), G_ScriptAction_TeamVoiceAnnounce(), SetMoverState(), Team_ResetFlag(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), Touch_flagonly(), Touch_flagonly_multiple(), and Use_BinaryMover().
void constructible_indicator_think (gentity_t * ent)
Spawn a constructible indicator.
Parameters
[in,out] ent
Definition at line 1510 of file g_trigger.c.
Referenced by Think_SetupObjectiveInfo().
void explosive_indicator_think (gentity_t * ent)
Spawn an explosive indicator.
Parameters
[in,out] ent
Definition at line 1467 of file g_trigger.c.
Referenced by AutoBuildConstruction(), EntsThatRadiusCanDamage(), func_constructible_underconstructionthink(), func_constructiblespawn(), Think_SetupObjectiveInfo(), and TryConstructing().
void func_timer_think (gentity_t * self)
func_timer_think
QUAKED func_timer (0.3 0.1 0.6) (-8 -8 -8) (8 8 8) START_ON This should be renamed trigger_timer... Repeatedly fires its targets. Can be turned on or off by using.
"wait" base time between triggering all targets, default is 1 "random" wait variance, default is 0 so, the basic time between firing is a random time between (wait - random) and (wait + random)
Parameters
[in,out] self
Definition at line 1146 of file g_trigger.c.
Referenced by func_timer_use(), and SP_func_timer().
void func_timer_use (gentity_t * self, gentity_t * other, gentity_t * activator)
func_timer_use
Parameters
[in,out] self
other - unused
[in] activator
Definition at line 1159 of file g_trigger.c.
Referenced by SP_func_timer().
qboolean G_IsAllowedAmmo (gentity_t * ent)
G_IsAllowedAmmo.
QUAKED trigger_ammo (.5 .5 .5) ? Any entity that touches this will get additional ammo a specified rate up to a specified maximum.
"ammorate" rate of ammo clips per second. default 1. (whole number only) "ammototal" the maximum clips of ammo this trigger can add. if <= 0, it's unlimited. default 0 (whole numbers only) "target" cabinet that this entity is linked to
Parameters
[in] ent
Returns
Definition at line 919 of file g_trigger.c.
Referenced by ammo_touch().
qboolean G_IsAllowedHeal (gentity_t * ent)
G_IsAllowedHeal.
QUAKED trigger_heal (.5 .5 .5) ? Any entity that touches this will be healed at a specified rate up to a specified maximum.
"healrate" rate of healing per second, default 5 (whole numbers only) "healtotal" the maximum of healing this trigger can do. if <= 0, it's unlimited. default 0 (whole numbers only) "target" cabinet that this entity is linked to
Parameters
ent
Returns
Definition at line 676 of file g_trigger.c.
Referenced by heal_touch().
void G_SetConfigStringValue (int num, const char * key, const char * value)
G_SetConfigStringValue.
Parameters
[in] num
[in] key
[in] value
Definition at line 1571 of file g_trigger.c.
Referenced by G_ModifyTOI(), and SP_trigger_objective_info().
void heal_touch (gentity_t * self, gentity_t * other, trace_t * trace)
heal_touch
Parameters
[in,out] self
[in] other
trace - unused
Definition at line 713 of file g_trigger.c.
Referenced by SP_trigger_heal().
void hurt_think (gentity_t * ent)
hurt_think
Parameters
[in,out] ent
Definition at line 587 of file g_trigger.c.
Referenced by hurt_use().
void hurt_touch (gentity_t * self, gentity_t * other, trace_t * trace)
hurt_touch
QUAKED trigger_hurt (.5 .5 .5) ? START_OFF - SILENT NO_PROTECTION SLOW ONCE Any entity that touches this will be hurt. It does dmg points of damage each server frame Targeting the trigger will toggle its on / off state.
SILENT supresses playing the sound SLOW changes the damage rate to once per second NO_PROTECTION nothing stops the damage
"dmg" default 5 (whole numbers only)
"life" time this brush will exist if value is zero will live for ever ei 0.5 sec 2.sec default is zero
the entity must be used first before it will count down its life
Parameters
[in,out] self
[in] other
trace - unused
Definition at line 538 of file g_trigger.c.
Referenced by hurt_use(), and SP_trigger_hurt().
void hurt_use (gentity_t * self, gentity_t * other, gentity_t * activator)
hurt_use
Parameters
[in,out] self
other - unused
activator - unused
Definition at line 603 of file g_trigger.c.
Referenced by SP_trigger_hurt().
void InitTrigger (gentity_t * self)
InitTrigger.
Parameters
[in,out] self
Definition at line 41 of file g_trigger.c.
Referenced by SP_trigger_ammo(), SP_trigger_flagonly(), SP_trigger_flagonly_multiple(), SP_trigger_heal(), SP_trigger_hurt(), SP_trigger_multiple(), SP_trigger_objective_info(), SP_trigger_once(), and SP_trigger_teleport().
void multi_trigger (gentity_t * ent, gentity_t * activator)
The trigger was just activated.
ent->activator should be set to the activator so it can be held through a delay so wait for the delay time before firing
Parameters
[in,out] ent
[in] activator
Definition at line 80 of file g_trigger.c.
Referenced by Touch_Multi(), and Use_Multi().
void multi_wait (gentity_t * ent)
The wait time has passed, so set back up for another activation.
Parameters
[out] ent
Definition at line 66 of file g_trigger.c.
Referenced by multi_trigger().
void SP_func_timer (gentity_t * self)
SP_func_timer.
Parameters
[in,out] self
Definition at line 1178 of file g_trigger.c.
void SP_misc_cabinet_health (gentity_t * self)
SP_misc_cabinet_health.
QUAKED misc_cabinet_health (.5 .5 .5) (-20 -20 0) (20 20 60)
Parameters
[out] self
Definition at line 838 of file g_trigger.c.
void SP_misc_cabinet_supply (gentity_t * self)
SP_misc_cabinet_supply.
QUAKED misc_cabinet_supply (.5 .5 .5) (-20 -20 0) (20 20 60)
Parameters
[in,out] self
Definition at line 1065 of file g_trigger.c.
void SP_target_push (gentity_t * self)
SP_target_push.
QUAKED target_push (.5 .5 .5) (-8 -8 -8) (8 8 8) bouncepad Pushes the activator in the direction.of angle, or towards a target apex. "speed" defaults to 1000 if "bouncepad", play bounce noise instead of windfly
Parameters
[in,out] self
Definition at line 424 of file g_trigger.c.
void SP_trigger_always (gentity_t * ent)
This trigger will always fire. It is activated by the world.
QUAKED trigger_always (.5 .5 .5) (-8 -8 -8) (8 8 8)
Parameters
ent
Definition at line 306 of file g_trigger.c.
void SP_trigger_ammo (gentity_t * self)
SP_trigger_ammo.
Parameters
[in,out] self
Definition at line 1085 of file g_trigger.c.
void SP_trigger_concussive_dust (gentity_t * self)
SP_trigger_concussive_dust.
QUAKED trigger_concussive_dust (.5 .5 .5) ? Allows client side prediction of teleportation events. Must point at a target_position, which will be the teleport destination.
Parameters
[in] self
Definition at line 1926 of file g_trigger.c.
void SP_trigger_flagonly (gentity_t * ent)
SP_trigger_flagonly.
QUAKED trigger_flagonly (.5 .5 .5) ? RED_FLAG BLUE_FLAG KILL_FLAG Player must be carrying the proper flag for it to trigger. It will call the "death" function in the object's script.
"scriptName" The object name in the script file
RED_FLAG – only trigger if player is carrying red flag BLUE_FLAG – only trigger if player is carrying blue flag
Parameters
[in,out] ent
Definition at line 1408 of file g_trigger.c.
void SP_trigger_flagonly_multiple (gentity_t * ent)
SP_trigger_flagonly_multiple.
QUAKED trigger_flagonly_multiple (.5 .5 .5) ? RED_FLAG BLUE_FLAG Player must be carrying the proper flag for it to trigger. It will call the "death" function in the object's script.
"scriptName" The object name in the script file
RED_FLAG – only trigger if player is carrying red flag BLUE_FLAG – only trigger if player is carrying blue flag
Parameters
ent
Definition at line 1443 of file g_trigger.c.
void SP_trigger_heal (gentity_t * self)
SP_trigger_heal.
Parameters
[in,out] self
Definition at line 858 of file g_trigger.c.
void SP_trigger_hurt (gentity_t * self)
SP_trigger_hurt.
Parameters
[in,out] self
Definition at line 626 of file g_trigger.c.
void SP_trigger_multiple (gentity_t * ent)
SP_trigger_multiple.
QUAKED trigger_multiple (.5 .5 .5) ? AXIS_ONLY ALLIED_ONLY NOBOT BOTONLY SOLDIERONLY LTONLY MEDICONLY ENGINEERONLY COVERTOPSONLY "wait" : Seconds between triggerings, 0.5 default, -1 = one time only. "random" wait variance, default is 0 Variable sized repeatable trigger. Must be targeted at one or more entities. so, the basic time between firing is a random time between (wait - random) and (wait + random)
Parameters
[in,out] ent
Definition at line 260 of file g_trigger.c.
void SP_trigger_objective_info (gentity_t * ent)
QUAKED trigger_objective_info (.5 .5 .5) ? AXIS_OBJECTIVE ALLIED_OBJECTIVE MESSAGE_OVERRIDE TANK IS_OBJECTIVE IS_HEALTHAMMOCABINET IS_COMMANDPOST Players in this field will see a message saying that they are near an objective.
"track" Mandatory, this is the text that is appended to "You are near " "shortname" Short name to show on command centre
Parameters
[in,out] ent
Definition at line 1801 of file g_trigger.c.
void SP_trigger_once (gentity_t * ent)
SP_trigger_once.
QUAKED trigger_once (.5 .5 .5) ? AI_Touch Must be targeted at one or more entities. Once triggered, this entity is destroyed (you can actually do the same thing with trigger_multiple with a wait of -1)
Parameters
[out] ent
Definition at line 1217 of file g_trigger.c.
void SP_trigger_push (gentity_t * self)
SP_trigger_push.
QUAKED trigger_push (.5 .5 .5) ? TOGGLE REMOVEAFTERTOUCH PUSHPLAYERONLY Must point at a target_position, which will be the apex of the leap. This will be client side predicted, unlike target_push
Parameters
self - unused
Definition at line 381 of file g_trigger.c.
void SP_trigger_teleport (gentity_t * self)
QUAKED trigger_teleport (.5 .5 .5) ? Allows client side prediction of teleportation events. Must point at a target_position, which will be the teleport destination.
Parameters
[out] self
Definition at line 493 of file g_trigger.c.
void Think_SetupObjectiveInfo (gentity_t * ent)
Links the trigger to it's objective, determining if it's a func_explosive of func_constructible and spawning the right indicator.
Parameters
[in,out] ent
Definition at line 1601 of file g_trigger.c.
Referenced by func_constructible_explode(), func_constructible_use(), G_ModifyTOI(), and SP_trigger_objective_info().
void Touch_flagonly (gentity_t * ent, gentity_t * other, trace_t * trace)
Touch_flagonly.
Parameters
[in,out] ent
[in,out] other
trace - unused
Definition at line 1242 of file g_trigger.c.
Referenced by SP_trigger_flagonly().
void Touch_flagonly_multiple (gentity_t * ent, gentity_t * other, trace_t * trace)
Touch_flagonly_multiple.
Parameters
[in,out] ent
[in,out] other
trace - unused
Definition at line 1329 of file g_trigger.c.
Referenced by SP_trigger_flagonly_multiple().
void Touch_Multi (gentity_t * self, gentity_t * other, trace_t * trace)
Touch_Multi.
Parameters
[in] self
[in] other
trace - unused
Definition at line 150 of file g_trigger.c.
Referenced by SP_trigger_multiple(), and SP_trigger_once().
void Touch_ObjectiveInfo (gentity_t * ent, gentity_t * other, trace_t * trace)
Touch_ObjectiveInfo.
Parameters
[in] ent
[in,out] other
trace - unused
Definition at line 1586 of file g_trigger.c.
Referenced by Think_SetupObjectiveInfo().
void trigger_always_think (gentity_t * ent)
trigger_always_think
Parameters
[in] ent
Definition at line 295 of file g_trigger.c.
Referenced by SP_trigger_always().
void trigger_ammo_setup (gentity_t * self)
trigger_ammo_setup
Parameters
[in,out] self
Definition at line 1043 of file g_trigger.c.
Referenced by SP_trigger_ammo().
void trigger_ammo_think (gentity_t * self)
trigger_ammo_think
Parameters
[in,out] self
Definition at line 1026 of file g_trigger.c.
Referenced by SP_trigger_ammo(), and trigger_ammo_setup().
void trigger_heal_setup (gentity_t * self)
trigger_heal_setup
Parameters
[in,out] self
Definition at line 816 of file g_trigger.c.
Referenced by SP_trigger_heal().
void trigger_heal_think (gentity_t * self)
trigger_heal_think
Parameters
[in,out] self
Definition at line 799 of file g_trigger.c.
Referenced by SP_trigger_heal(), and trigger_heal_setup().
void trigger_teleporter_touch (gentity_t * self, gentity_t * other, trace_t * trace)
trigger_teleporter_touch
Parameters
[in] self
[in] other
trace - unused
Definition at line 463 of file g_trigger.c.
Referenced by SP_trigger_teleport().
void Use_Multi (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Multi.
Parameters
[in] ent
other - unused
[in] activator
Definition at line 139 of file g_trigger.c.
Referenced by SP_trigger_multiple(), and SP_trigger_once().
void Use_target_push (gentity_t * self, gentity_t * other, gentity_t * activator)
Use_target_push.
Parameters
[in] self
other - unused
[in,out] activator
Definition at line 392 of file g_trigger.c.
Referenced by SP_target_push().