ET: Legacy: src/game/g_target.c File Reference
g_target.c File Reference
#include "g_local.h"
Functions
void Use_Target_Give (gentity_t *ent, gentity_t *other, gentity_t *activator)
Gives the activator all the items pointed to. QUAKED target_give (1 0 0) (-8 -8 -8) (8 8 8)
void SP_target_give (gentity_t *ent)
SP_target_give.
void Use_target_remove_powerups (gentity_t *ent, gentity_t *other, gentity_t *activator)
Takes away all the activators powerups. Used to drop flight powerups into death puts. QUAKED target_remove_powerups (1 0 0) (-8 -8 -8) (8 8 8)
void SP_target_remove_powerups (gentity_t *ent)
SP_target_remove_powerups.
void Think_Target_Delay (gentity_t *ent)
QUAKED target_delay (1 1 0) (-8 -8 -8) (8 8 8) "wait" seconds to pause before firing targets. "random" delay variance, total delay = delay +/- random seconds.
void Use_Target_Delay (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Target_Delay.
void SP_target_delay (gentity_t *ent)
SP_target_delay.
void Use_Target_Print (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Target_Print QUAKED target_print (1 0 0) (-8 -8 -8) (8 8 8) redteam blueteam private "message" text to print If "private", only the activator gets the message. If no checks, all clients get the message.
void SP_target_print (gentity_t *ent)
SP_target_print.
void Use_Target_Speaker (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Target_Speaker.
void target_speaker_multiple (gentity_t *ent)
target_speaker_multiple
void SP_target_speaker (gentity_t *ent)
SP_target_speaker.
void misc_beam_think (gentity_t *self)
When on, displays a electric beam from target to target2.
void misc_beam_start (gentity_t *self)
misc_beam_start
void SP_misc_beam (gentity_t *self)
SP_misc_beam.
void target_laser_think (gentity_t *self)
When triggered, fires a laser. You can either set a target or a direction.
void target_laser_on (gentity_t *self)
target_laser_on
void target_laser_off (gentity_t *self)
target_laser_off
void target_laser_use (gentity_t *self, gentity_t *other, gentity_t *activator)
target_laser_use
void target_laser_start (gentity_t *self)
target_laser_start
void SP_target_laser (gentity_t *self)
SP_target_laser.
void target_teleporter_use (gentity_t *self, gentity_t *other, gentity_t *activator)
target_teleporter_use
void SP_target_teleporter (gentity_t *self)
The activator will be teleported away. QUAKED target_teleporter (1 0 0) (-8 -8 -8) (8 8 8)
void target_relay_use (gentity_t *self, gentity_t *other, gentity_t *activator)
target_relay_use
void SP_target_relay (gentity_t *self)
SP_target_relay.
void G_KillEnts (const char *target, gentity_t *ignore, gentity_t *killer, meansOfDeath_t mod)
Kills the activator. (default)
void target_kill_use (gentity_t *self, gentity_t *other, gentity_t *activator)
target_kill_use
void SP_target_kill (gentity_t *self)
SP_target_kill.
void SP_target_position (gentity_t *self)
Used as a positional target for in-game calculation, like jumppad targets.
void SP_target_location (gentity_t *self)
SP_target_location.
void Use_Target_Counter (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Target_Counter.
void Use_Target_Lock (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Target_Lock.
void Use_target_fog (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_target_fog.
void SP_target_fog (gentity_t *ent)
SP_target_fog.
void SP_target_counter (gentity_t *ent)
QUAKED target_counter (1 1 0) (-8 -8 -8) (8 8 8) Increments the counter pointed to. "count" is the key for the count value.
void SP_target_lock (gentity_t *ent)
SP_target_lock.
void Use_Target_Alarm (gentity_t *ent, gentity_t *other, gentity_t *activator)
Use_Target_Alarm.
void SP_target_alarm (gentity_t *ent)
QUAKED target_alarm (1 1 0) (-4 -4 -4) (4 4 4) does nothing yet (effectively a relay right now)
void smoke_think (gentity_t *ent)
smoke_think
void smoke_toggle (gentity_t *ent, gentity_t *self, gentity_t *activator)
smoke_toggle
void smoke_init (gentity_t *ent)
smoke_init
void SP_target_smoke (gentity_t *ent)
SP_target_smoke.
void target_script_trigger_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
When used it will fire its targets.
void SP_target_script_trigger (gentity_t *ent)
SP_target_script_trigger.
void target_rumble_think (gentity_t *ent)
target_rumble_think
void target_rumble_use (gentity_t *ent, gentity_t *other, gentity_t *activator)
target_rumble_use
void SP_target_rumble (gentity_t *self)
SP_target_rumble.
Function Documentation
void G_KillEnts (const char * target, gentity_t * ignore, gentity_t * killer, meansOfDeath_t mod)
Kills the activator. (default)
QUAKED target_kill (.5 .5 .5) (-8 -8 -8) (8 8 8) kill_user_too If targets, they will be killed when this is fired "kill_user_too" will still kill the activator when this ent has targets (default is only kill targets, not activator)
Parameters
[in] target
[in] ignore
[in] killer
[in] mod
Definition at line 833 of file g_target.c.
Referenced by G_ScriptAction_Kill(), and target_kill_use().
void misc_beam_start (gentity_t * self)
misc_beam_start
Parameters
[in,out] self
Definition at line 462 of file g_target.c.
Referenced by SP_misc_beam().
void misc_beam_think (gentity_t * self)
When on, displays a electric beam from target to target2.
QUAKED misc_beam (0 .5 .8) (-8 -8 -8) (8 8 8)
"target" start of beam "target2" end of beam "shader" the shader "color" colour of beam NOT WORKIN YET "scale" width of beam NOT WORKIN YET
Parameters
[in,out] self
Definition at line 391 of file g_target.c.
Referenced by misc_beam_start().
void smoke_init (gentity_t * ent)
smoke_init
Parameters
[in,out] ent
Definition at line 1133 of file g_target.c.
Referenced by SP_target_smoke().
void smoke_think (gentity_t * ent)
smoke_think
QUAKED target_smoke (1 0 0) (-32 -32 -16) (32 32 16) Black White SmokeON Gravity 1 second = 1000 1 FRAME = 100 delay = 100 = one millisecond default this is the maximum smoke that will show up time = 5000 default before the smoke disipates duration = 2000 before the smoke starts to alpha start_size = 24 default end_size = 96 default wait = default is 50 the rate at which it will travel up shader = custom shader to use for particles
Parameters
ent
Definition at line 1089 of file g_target.c.
Referenced by smoke_init().
void smoke_toggle (gentity_t * ent, gentity_t * self, gentity_t * activator)
smoke_toggle
Parameters
[in,out] ent
self - unused
activator - unused
Definition at line 1115 of file g_target.c.
Referenced by SP_target_smoke().
void SP_misc_beam (gentity_t * self)
SP_misc_beam.
Parameters
[in,out] self
Definition at line 511 of file g_target.c.
void SP_target_alarm (gentity_t * ent)
QUAKED target_alarm (1 1 0) (-4 -4 -4) (4 4 4) does nothing yet (effectively a relay right now)
Parameters
[out] ent
Definition at line 1070 of file g_target.c.
void SP_target_counter (gentity_t * ent)
QUAKED target_counter (1 1 0) (-8 -8 -8) (8 8 8) Increments the counter pointed to. "count" is the key for the count value.
Parameters
[out] ent
Definition at line 1029 of file g_target.c.
void SP_target_delay (gentity_t * ent)
SP_target_delay.
Parameters
[in,out] ent
Definition at line 149 of file g_target.c.
void SP_target_fog (gentity_t * ent)
SP_target_fog.
QUAKED target_fog (1 1 0) (-8 -8 -8) (8 8 8) color picker chooses color of fog "distance" sets fog distance. Use value '0' to give control back to the game (and use the fog values specified in the sky shader if present) "time" time it takes to change fog to new value. default time is 1 sec
Parameters
[out] ent
Definition at line 995 of file g_target.c.
void SP_target_give (gentity_t * ent)
SP_target_give.
Parameters
[out] ent
Definition at line 80 of file g_target.c.
void SP_target_kill (gentity_t * self)
SP_target_kill.
Parameters
[out] self
Definition at line 893 of file g_target.c.
void SP_target_laser (gentity_t * self)
SP_target_laser.
Parameters
[out] self
Definition at line 664 of file g_target.c.
void SP_target_location (gentity_t * self)
SP_target_location.
QUAKED target_location (0 0.5 0) (-8 -8 -8) (8 8 8) Set "message" to the name of this location. Set "count" to 0-7 for color. 0:white 1:red 2:green 3:yellow 4:blue 5:cyan 6:magenta 7:white
Closest target_location in sight used for the location, if none in site, closest in distance
Parameters
self
Definition at line 919 of file g_target.c.
void SP_target_lock (gentity_t * ent)
SP_target_lock.
QUAKED target_lock (1 1 0) (-8 -8 -8) (8 8 8) Sets the door to a state requiring key n "key" is the required key so: key:0 unlocks the door key:-1 locks the door until a target_lock with key:0 key:n means the door now requires key n
Parameters
[out] ent
Definition at line 1049 of file g_target.c.
void SP_target_position (gentity_t * self)
Used as a positional target for in-game calculation, like jumppad targets.
DEFUNCT target_position (0 0.5 0) (-4 -4 -4) (4 4 4)
Parameters
self
Definition at line 903 of file g_target.c.
void SP_target_print (gentity_t * ent)
SP_target_print.
Parameters
[out] ent
Definition at line 209 of file g_target.c.
void SP_target_relay (gentity_t * self)
SP_target_relay.
Parameters
[in,out] self
Definition at line 795 of file g_target.c.
void SP_target_remove_powerups (gentity_t * ent)
SP_target_remove_powerups.
Parameters
[out] ent
Definition at line 114 of file g_target.c.
void SP_target_rumble (gentity_t * self)
SP_target_rumble.
Parameters
[in,out] self
Definition at line 1438 of file g_target.c.
void SP_target_script_trigger (gentity_t * ent)
SP_target_script_trigger.
Parameters
[out] ent
Definition at line 1309 of file g_target.c.
void SP_target_smoke (gentity_t * ent)
SP_target_smoke.
Parameters
[in,out] ent
Definition at line 1169 of file g_target.c.
void SP_target_speaker (gentity_t * ent)
SP_target_speaker.
Parameters
[in,out] ent
Definition at line 290 of file g_target.c.
void SP_target_teleporter (gentity_t * self)
The activator will be teleported away. QUAKED target_teleporter (1 0 0) (-8 -8 -8) (8 8 8)
Parameters
[in,out] self
Definition at line 709 of file g_target.c.
void target_kill_use (gentity_t * self, gentity_t * other, gentity_t * activator)
target_kill_use
Parameters
[in] self
other - unused
[in] activator
Definition at line 879 of file g_target.c.
Referenced by SP_target_kill().
void target_laser_off (gentity_t * self)
target_laser_off
Parameters
[out] self
Definition at line 593 of file g_target.c.
Referenced by target_laser_start(), and target_laser_use().
void target_laser_on (gentity_t * self)
target_laser_on
Parameters
[in,out] self
Definition at line 580 of file g_target.c.
Referenced by target_laser_start(), and target_laser_use().
void target_laser_start (gentity_t * self)
target_laser_start
Parameters
[in,out] self
Definition at line 622 of file g_target.c.
Referenced by SP_target_laser().
void target_laser_think (gentity_t * self)
When triggered, fires a laser. You can either set a target or a direction.
QUAKED target_laser (0 .5 .8) (-8 -8 -8) (8 8 8) START_ON
Parameters
[in,out] self
Definition at line 543 of file g_target.c.
Referenced by target_laser_on(), and target_laser_start().
void target_laser_use (gentity_t * self, gentity_t * other, gentity_t * activator)
target_laser_use
Parameters
[in,out] self
other - unused
[in] activator
Definition at line 605 of file g_target.c.
Referenced by target_laser_start().
void target_relay_use (gentity_t * self, gentity_t * other, gentity_t * activator)
target_relay_use
QUAKED target_relay (1 1 0) (-8 -8 -8) (8 8 8) RED_ONLY BLUE_ONLY RANDOM NOKEY_ONLY TAKE_KEY NO_LOCKED_NOISE This doesn't perform any actions except fire its targets. The activator can be forced to be from a certain team. if RANDOM is checked, only one of the targets will be fired, not all of them "key" specifies an item you can be carrying that affects the operation of this relay this key is currently an int (1-16) which matches the id of a key entity (key_key1 = 1, etc) NOKEY_ONLY means "fire only if I do /not/ have the specified key" TAKE_KEY removes the key from the players inventory "lockednoise" specifies a .wav file to play if the relay is used and the player doesn't have the necessary key. By default this sound is "sound/movers/doors/default_door_locked.wav" NO_LOCKED_NOISE specifies that it will be silent if activated without proper key
Parameters
[in] self
other - unused
[in] activator
Definition at line 739 of file g_target.c.
Referenced by SP_target_relay().
void target_rumble_think (gentity_t * ent)
target_rumble_think
QUAKED target_rumble (0 0.75 0.8) (-8 -8 -8) (8 8 8) STARTOFF wait = default is 2 seconds = time the entity will enable rumble effect "pitch" value from 1 to 10 default is 5 "yaw" value from 1 to 10 default is 5
"rampup" how much time it will take to reach maximum pitch and yaw in seconds "rampdown" how long till effect ends after rampup is reached in seconds
"startnoise" startingsound "noise" the looping sound entity is to make "endnoise" endsound
"duration" the amount of time the effect is to last ei 1.0 sec 3.6 sec
Parameters
[in,out] ent
Todo:
: div / 0
Definition at line 1338 of file g_target.c.
Referenced by target_rumble_use().
void target_rumble_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
target_rumble_use
Parameters
[out] ent
other - unused
activator - unused
Definition at line 1417 of file g_target.c.
Referenced by SP_target_rumble().
void target_script_trigger_use (gentity_t * ent, gentity_t * other, gentity_t * activator)
When used it will fire its targets.
QUAKED target_script_trigger (1 .7 .2) (-8 -8 -8) (8 8 8) must have an aiName must have a target
Parameters
[in] ent
[in] other
activator - unused
Definition at line 1268 of file g_target.c.
Referenced by SP_target_script_trigger().
void target_speaker_multiple (gentity_t * ent)
target_speaker_multiple
Parameters
[in] ent
Definition at line 265 of file g_target.c.
Referenced by SP_target_speaker().
void target_teleporter_use (gentity_t * self, gentity_t * other, gentity_t * activator)
target_teleporter_use
Parameters
[in] self
other - unused
[in] activator
Definition at line 685 of file g_target.c.
Referenced by SP_target_teleporter().
void Think_Target_Delay (gentity_t * ent)
QUAKED target_delay (1 1 0) (-8 -8 -8) (8 8 8) "wait" seconds to pause before firing targets. "random" delay variance, total delay = delay +/- random seconds.
Parameters
ent
Definition at line 127 of file g_target.c.
Referenced by Use_Target_Delay().
void Use_Target_Alarm (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Target_Alarm.
Parameters
[in] ent
[in] other
activator - unused
Definition at line 1060 of file g_target.c.
Referenced by SP_target_alarm().
void Use_Target_Counter (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Target_Counter.
Parameters
[in,out] ent
[in] other
activator - unused
Definition at line 934 of file g_target.c.
Referenced by SP_target_counter().
void Use_Target_Delay (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Target_Delay.
Parameters
[in,out] ent
other - unused
[in] activator
Definition at line 138 of file g_target.c.
Referenced by SP_target_delay().
void Use_target_fog (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_target_fog.
Parameters
[in,out] ent
other - unused
activator - unused
Definition at line 976 of file g_target.c.
Referenced by SP_target_fog().
void Use_Target_Give (gentity_t * ent, gentity_t * other, gentity_t * activator)
Gives the activator all the items pointed to. QUAKED target_give (1 0 0) (-8 -8 -8) (8 8 8)
Parameters
[in] ent
other - unused
[in] activator
Definition at line 46 of file g_target.c.
Referenced by SP_target_give().
void Use_Target_Lock (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Target_Lock.
Parameters
[in] ent
other - unused
activator - unused
Definition at line 957 of file g_target.c.
Referenced by SP_target_lock().
void Use_Target_Print (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Target_Print QUAKED target_print (1 0 0) (-8 -8 -8) (8 8 8) redteam blueteam private "message" text to print If "private", only the activator gets the message. If no checks, all clients get the message.
Parameters
[in] ent
other - unused
[in] activator
Definition at line 173 of file g_target.c.
Referenced by SP_target_print().
void Use_target_remove_powerups (gentity_t * ent, gentity_t * other, gentity_t * activator)
Takes away all the activators powerups. Used to drop flight powerups into death puts. QUAKED target_remove_powerups (1 0 0) (-8 -8 -8) (8 8 8)
Parameters
ent - unused
other - unused
[in,out] activator
Definition at line 95 of file g_target.c.
Referenced by SP_target_remove_powerups().
void Use_Target_Speaker (gentity_t * ent, gentity_t * other, gentity_t * activator)
Use_Target_Speaker.
QUAKED target_speaker (1 0 0) (-8 -8 -8) (8 8 8) LOOPED_ON LOOPED_OFF GLOBAL ACTIVATOR VIS_MULTIPLE NO_PVS "noise" wav file to play A global sound will play full volume throughout the level. Activator sounds will play on the player that activated the target. Global and activator sounds can't be combined with looping. Normal sounds play each time the target is used. Looped sounds will be toggled by use functions. Multiple identical looping sounds will just increase volume without any speed cost. NO_PVS - this sound will not turn off when not in the player's PVS "wait" : Seconds between auto triggerings, 0 = don't auto trigger "random" : wait variance, default is 0 "volume" volume control 255 is default
Parameters
[in,out] ent
other
[in] activator - unused
Definition at line 235 of file g_target.c.
Referenced by SP_target_speaker().