ET: Legacy: src/game/g_teammapdata.c File Reference
g_teammapdata.c File Reference
#include "g_local.h"
Data Structures
struct plane_s
Some culling bits.
Macros
#define BINOCULAR_ANGLE 10.0f
#define BOT_BINOCULAR_ANGLE 60.0f
Typedefs
typedef struct plane_s plane_t
Functions
void G_PushMapEntityToBuffer (char *buffer, size_t size, mapEntityData_t *mEnt)
G_PushMapEntityToBuffer.
void G_InitMapEntityData (mapEntityData_Team_t *teamList)
G_InitMapEntityData.
mapEntityData_t * G_FreeMapEntityData (mapEntityData_Team_t *teamList, mapEntityData_t *mEnt)
G_FreeMapEntityData.
mapEntityData_t * G_AllocMapEntityData (mapEntityData_Team_t *teamList)
G_AllocMapEntityData.
mapEntityData_t * G_FindMapEntityData (mapEntityData_Team_t *teamList, int entNum)
G_FindMapEntityData.
mapEntityData_t * G_FindMapEntityDataSingleClient (mapEntityData_Team_t *teamList, mapEntityData_t *start, int entNum, int clientNum)
G_FindMapEntityDataSingleClient.
void G_SetupFrustum (gentity_t *ent)
G_SetupFrustum.
void G_SetupFrustum_ForBinoculars (gentity_t *ent)
G_SetupFrustum_ForBinoculars.
static qboolean G_CullPointAndRadius (vec3_t pt, float radius)
G_CullPointAndRadius.
qboolean G_VisibleFromBinoculars (gentity_t *viewer, gentity_t *ent, vec3_t origin)
G_VisibleFromBinoculars.
qboolean G_VisibleFromBinoculars_Box (gentity_t *viewer, gentity_t *ent, vec3_t origin, vec3_t mins, vec3_t maxs)
G_VisibleFromBinoculars_Box.
void G_ResetTeamMapData ()
G_ResetTeamMapData.
void G_UpdateTeamMapData_Construct (gentity_t *ent)
G_UpdateTeamMapData_Construct.
void G_UpdateTeamMapData_Tank (gentity_t *ent)
G_UpdateTeamMapData_Tank.
void G_UpdateTeamMapData_Destruct (gentity_t *ent)
G_UpdateTeamMapData_Destruct.
void G_UpdateTeamMapData_Player (gentity_t *ent, qboolean forceAllied, qboolean forceAxis)
G_UpdateTeamMapData_Player.
static void G_UpdateTeamMapData_DisguisedPlayer (gentity_t *spotter, gentity_t *ent, qboolean forceAllied, qboolean forceAxis)
G_UpdateTeamMapData_DisguisedPlayer.
void G_UpdateTeamMapData_LandMine (gentity_t *ent)
G_UpdateTeamMapData_LandMine.
void G_UpdateTeamMapData_CommandmapMarker (gentity_t *ent)
G_UpdateTeamMapData_CommandmapMarker.
void G_SendSpectatorMapEntityInfo (gentity_t *e)
G_SendSpectatorMapEntityInfo.
void G_SendMapEntityInfo (gentity_t *e)
G_SendMapEntityInfo.
void G_PopupMessageForMines (gentity_t *player)
G_PopupMessageForMines.
void G_CheckSpottedLandMines (void)
G_CheckSpottedLandMines.
void G_UpdateTeamMapData (void)
G_UpdateTeamMapData.
Variables
static plane_t frustum [4]
Macro Definition Documentation
#define BINOCULAR_ANGLE 10.0f
Definition at line 274 of file g_teammapdata.c.
Referenced by G_SetupFrustum_ForBinoculars().
#define BOT_BINOCULAR_ANGLE 60.0f
Definition at line 275 of file g_teammapdata.c.
Referenced by G_SetupFrustum_ForBinoculars().
Typedef Documentation
typedef struct plane_s plane_t
Function Documentation
mapEntityData_t* G_AllocMapEntityData (mapEntityData_Team_t * teamList)
G_AllocMapEntityData.
Parameters
[in,out] teamList
Returns
Definition at line 126 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_DisguisedPlayer(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), and G_UpdateTeamMapData_Tank().
void G_CheckSpottedLandMines (void)
G_CheckSpottedLandMines.
Definition at line 1193 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
static qboolean G_CullPointAndRadius (vec3_t pt, float radius) static
G_CullPointAndRadius.
Parameters
[in] pt
[in] radius
Returns
true if not culled
Definition at line 321 of file g_teammapdata.c.
Referenced by G_VisibleFromBinoculars(), and G_VisibleFromBinoculars_Box().
mapEntityData_t* G_FindMapEntityData (mapEntityData_Team_t * teamList, int entNum)
G_FindMapEntityData.
Parameters
[in] teamList
[in] entNum
Returns
Definition at line 157 of file g_teammapdata.c.
Referenced by ClientDisconnect(), constructible_indicator_think(), explosive_indicator_think(), func_constructible_explode(), G_Damage(), G_RealExplodedMissile(), G_SetEntState(), G_UpdateTeamMapData_CommandmapMarker(), G_UpdateTeamMapData_Construct(), G_UpdateTeamMapData_Destruct(), G_UpdateTeamMapData_LandMine(), G_UpdateTeamMapData_Player(), G_UpdateTeamMapData_Tank(), HandleEntsThatBlockConstructible(), player_die(), SetTeam(), TryConstructing(), and Weapon_Engineer().
mapEntityData_t* G_FindMapEntityDataSingleClient (mapEntityData_Team_t * teamList, mapEntityData_t * start, int entNum, int clientNum)
G_FindMapEntityDataSingleClient.
Parameters
[in] teamList
[in] start
[in] entNum
[in] clientNum
Returns
Definition at line 185 of file g_teammapdata.c.
Referenced by ClientDisconnect(), G_UpdateTeamMapData(), G_UpdateTeamMapData_DisguisedPlayer(), player_die(), and SetTeam().
mapEntityData_t* G_FreeMapEntityData (mapEntityData_Team_t * teamList, mapEntityData_t * mEnt)
G_FreeMapEntityData.
Parameters
[in,out] teamList
[in,out] mEnt
Returns
Next entity in the array
Definition at line 101 of file g_teammapdata.c.
Referenced by ClientDisconnect(), constructible_indicator_think(), explosive_indicator_think(), func_constructible_explode(), G_Damage(), G_RealExplodedMissile(), G_SendMapEntityInfo(), G_SendSpectatorMapEntityInfo(), G_SetEntState(), HandleEntsThatBlockConstructible(), player_die(), SetTeam(), TryConstructing(), and Weapon_Engineer().
void G_InitMapEntityData (mapEntityData_Team_t * teamList)
G_InitMapEntityData.
Parameters
[out] teamList
Definition at line 77 of file g_teammapdata.c.
Referenced by G_ResetTeamMapData().
void G_PopupMessageForMines (gentity_t * player)
G_PopupMessageForMines.
Parameters
[in] player
Definition at line 1178 of file g_teammapdata.c.
Referenced by G_CheckSpottedLandMines().
void G_PushMapEntityToBuffer (char * buffer, size_t size, mapEntityData_t * mEnt)
G_PushMapEntityToBuffer.
Parameters
[out] buffer
[in] size
[in] mEnt
Definition at line 43 of file g_teammapdata.c.
Referenced by G_SendMapEntityInfo(), and G_SendSpectatorMapEntityInfo().
void G_ResetTeamMapData (void)
G_ResetTeamMapData.
Definition at line 452 of file g_teammapdata.c.
Referenced by ClientSpawn(), and G_InitGame().
void G_SendMapEntityInfo (gentity_t * e)
G_SendMapEntityInfo.
Parameters
[in] e
Definition at line 1094 of file g_teammapdata.c.
Referenced by ClientThink_real().
void G_SendSpectatorMapEntityInfo (gentity_t * e)
G_SendSpectatorMapEntityInfo.
Parameters
[in] e
Todo:
: Find out why objective counts are reset to zero when a new player connects
Definition at line 947 of file g_teammapdata.c.
Referenced by G_SendMapEntityInfo().
void G_SetupFrustum (gentity_t * ent)
G_SetupFrustum.
Parameters
[in] ent
Definition at line 239 of file g_teammapdata.c.
Referenced by G_PlayerCanBeSeenByOthers(), and G_UpdateTeamMapData().
void G_SetupFrustum_ForBinoculars (gentity_t * ent)
G_SetupFrustum_ForBinoculars.
Parameters
[in] ent
Definition at line 281 of file g_teammapdata.c.
Referenced by G_CheckSpottedLandMines(), G_PlayerCanBeSeenByOthers(), and G_UpdateTeamMapData().
void G_UpdateTeamMapData (void)
G_UpdateTeamMapData.
Definition at line 1315 of file g_teammapdata.c.
Referenced by G_RunFrame().
void G_UpdateTeamMapData_CommandmapMarker (gentity_t * ent)
G_UpdateTeamMapData_CommandmapMarker.
Parameters
[in] ent
Definition at line 894 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
void G_UpdateTeamMapData_Construct (gentity_t * ent)
G_UpdateTeamMapData_Construct.
Parameters
[in] ent
Definition at line 462 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
void G_UpdateTeamMapData_Destruct (gentity_t * ent)
G_UpdateTeamMapData_Destruct.
Parameters
[in] ent
Definition at line 571 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
static void G_UpdateTeamMapData_DisguisedPlayer (gentity_t * spotter, gentity_t * ent, qboolean forceAllied, qboolean forceAxis) static
G_UpdateTeamMapData_DisguisedPlayer.
Parameters
[in] spotter
[in] ent
[in] forceAllied
[in] forceAxis
Definition at line 779 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
void G_UpdateTeamMapData_LandMine (gentity_t * ent)
G_UpdateTeamMapData_LandMine.
Parameters
[in] ent
Definition at line 848 of file g_teammapdata.c.
Referenced by G_CheckSpottedLandMines(), and G_UpdateTeamMapData().
void G_UpdateTeamMapData_Player (gentity_t * ent, qboolean forceAllied, qboolean forceAxis)
G_UpdateTeamMapData_Player.
Parameters
[in] ent
[in] forceAllied
[in] forceAxis
Definition at line 690 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
void G_UpdateTeamMapData_Tank (gentity_t * ent)
G_UpdateTeamMapData_Tank.
Parameters
[in] ent
Definition at line 520 of file g_teammapdata.c.
Referenced by G_UpdateTeamMapData().
qboolean G_VisibleFromBinoculars (gentity_t * viewer, gentity_t * ent, vec3_t origin)
G_VisibleFromBinoculars.
Parameters
[in] viewer
[in] ent
[in,out] origin
Returns
Definition at line 358 of file g_teammapdata.c.
Referenced by G_CheckSpottedLandMines().
qboolean G_VisibleFromBinoculars_Box (gentity_t * viewer, gentity_t * ent, vec3_t origin, vec3_t mins, vec3_t maxs)
G_VisibleFromBinoculars_Box.
Parameters
[in] viewer
[in] ent
[in,out] origin
[in] mins
[in] maxs
Returns
Definition at line 408 of file g_teammapdata.c.
Referenced by G_PlayerCanBeSeenByOthers(), and G_UpdateTeamMapData().
Variable Documentation
plane_t frustum[4] static
Definition at line 233 of file g_teammapdata.c.