ET: Legacy: src/game/g_utils.c File Reference
g_utils.c File Reference
Misc utility functions for game module.
#include "g_local.h"
#include "g_etbot_interface.h"
Data Structures
struct shaderRemap_t
Macros
#define MAX_SHADER_REMAPS 128
#define MAXCHOICES 32
Functions
void AddRemap (const char *oldShader, const char *newShader, float timeOffset)
AddRemap.
void G_ResetRemappedShaders (void)
G_ResetRemappedShaders.
const char * BuildShaderStateConfig ()
BuildShaderStateConfig.
int G_FindConfigstringIndex (const char *name, int start, int max, qboolean create)
G_FindConfigstringIndex.
void G_RemoveConfigstringIndex (const char *name, int start, int max)
Prevent player always mounting the last gun used, on multiple tank maps. Ported from the Bugfix project (#087)
int G_ModelIndex (const char *name)
G_ModelIndex.
int G_SoundIndex (const char *name)
G_SoundIndex.
int G_SkinIndex (const char *name)
G_SkinIndex.
int G_ShaderIndex (const char *name)
G_ShaderIndex.
int G_CharacterIndex (const char *name)
G_CharacterIndex.
int G_StringIndex (const char *string)
G_StringIndex.
void G_TeamCommand (team_t team, const char *cmd)
Broadcasts a command to only a specific team.
gentity_t * G_Find (gentity_t *from, int fieldofs, const char *match)
Searches all active entities for the next one that holds the matching string at fieldofs (use the FOFS() macro) in the structure. Searches beginning at the entity after from, or the beginning if NULL NULL will be returned if the end of the list is reached.
gentity_t * G_FindInt (gentity_t *from, int fieldofs, int match)
Like G_Find, but searches for integer values.
gentity_t * G_FindFloat (gentity_t *from, int fieldofs, float match)
Like G_Find, but searches for float values..
gentity_t * G_FindVector (gentity_t *from, int fieldofs, const vec3_t match)
Like G_Find, but searches for vector values..
gentity_t * G_FindByTargetname (gentity_t *from, const char *match)
G_FindByTargetname.
gentity_t * G_FindByTargetnameFast (gentity_t *from, const char *match, int hash)
This version should be used for loops, saves the constant hash building.
gentity_t * G_PickTarget (const char *targetname)
Selects a random entity from among the targets.
qboolean G_AllowTeamsAllowed (gentity_t *ent, gentity_t *activator)
G_AllowTeamsAllowed.
void G_UseEntity (gentity_t *ent, gentity_t *other, gentity_t *activator)
Added to allow more checking on what uses what.
void G_UseTargets (gentity_t *ent, gentity_t *activator)
Search for (string)targetname in all entities that match (string)self.target and call their .use function.
char * vtos (const vec3_t v)
This is just a convenience function for printing vectors.
void G_SetMovedir (vec3_t angles, vec3_t movedir)
The editor only specifies a single value for angles (yaw), but we have special constants to generate an up or down direction. Angles will be cleared, because it is being used to represent a direction instead of an orientation.
void G_InitGentity (gentity_t *e)
G_InitGentity.
gentity_t * G_Spawn (void)
Either finds a free entity, or allocates a new one.
int G_EntitiesFree (void)
G_EntitiesFree.
void G_FreeEntity (gentity_t *ent)
Marks the entity as free.
gentity_t * G_TempEntity (vec3_t origin, entity_event_t event)
Spawns an event entity that will be auto-removed.
gentity_t * G_TempEntityNotLinked (entity_event_t event)
Spawns an event entity that will be auto-removed Use this for non visible and not origin based events like global sounds etc.
gentity_t * G_PopupMessage (popupMessageType_t type)
G_PopupMessage.
void G_AddPredictableEvent (gentity_t *ent, int event, int eventParm)
Use for non-pmove events that would also be predicted on the client side: jumppads and item pickups Adds an event+parm and twiddles the event counter.
void G_AddEvent (gentity_t *ent, int event, int eventParm)
Adds an event+parm and twiddles the event counter.
void G_Sound (gentity_t *ent, int soundIndex)
Removed channel parm, since it wasn't used, and could cause confusion.
void G_ClientSound (gentity_t *ent, int soundIndex)
G_ClientSound.
void G_AnimScriptSound (int soundIndex, vec3_t org, int client)
G_AnimScriptSound.
void G_SetOrigin (gentity_t *ent, vec3_t origin)
Sets the pos trajectory for a fixed position.
void G_SetAngle (gentity_t *ent, vec3_t angle)
G_SetAngle.
qboolean infront (gentity_t *self, gentity_t *other)
infront
void G_ProcessTagConnect (gentity_t *ent, qboolean clearAngles)
G_ProcessTagConnect.
int DebugLine (vec3_t start, vec3_t end, int color)
Debug polygons only work when running a local game with r_debugSurface set to 2.
void G_SetEntState (gentity_t *ent, entState_t state)
Sets the entstate of an entity.
static qboolean G_LoadCampaignsFromFile (const char *filename)
G_LoadCampaignsFromFile.
qboolean G_MapIsValidCampaignStartMap (void)
G_MapIsValidCampaignStartMap.
void G_ParseCampaigns (void)
G_ParseCampaigns.
void G_PrintClientSpammyCenterPrint (int entityNum, const char *text)
G_PrintClientSpammyCenterPrint.
team_t G_GetTeamFromEntity (gentity_t *ent)
G_GetTeamFromEntity.
const char * G_StringContains (const char *str1, const char *str2, int casesensitive)
G_StringContains.
qboolean G_MatchString (const char *filter, const char *name, int casesensitive)
G_MatchString.
Variables
int remapCount = 0
shaderRemap_t remappedShaders [MAX_SHADER_REMAPS]
char bigTextBuffer [100000]
Detailed Description
Misc utility functions for game module.
Definition in file g_utils.c.
Macro Definition Documentation
#define MAX_SHADER_REMAPS 128
Definition at line 49 of file g_utils.c.
Referenced by AddRemap(), and G_ResetRemappedShaders().
#define MAXCHOICES 32
Definition at line 559 of file g_utils.c.
Referenced by G_PickTarget().
Function Documentation
void AddRemap (const char * oldShader, const char * newShader, float timeOffset)
AddRemap.
Parameters
[in] oldShader
[in] newShader
[in] timeOffset
Definition at line 60 of file g_utils.c.
Referenced by _et_G_ShaderRemap(), and G_ScriptAction_ShaderRemap().
const char* BuildShaderStateConfig (void)
BuildShaderStateConfig.
Returns
Definition at line 111 of file g_utils.c.
Referenced by _et_G_ShaderRemapFlush(), and G_ScriptAction_ShaderRemapFlush().
int DebugLine (vec3_t start, vec3_t end, int color)
Debug polygons only work when running a local game with r_debugSurface set to 2.
Parameters
[in] start
[in] end
[in] color
Returns
Definition at line 1253 of file g_utils.c.
Referenced by IEngineInterface::DebugArrow().
void G_AddEvent (gentity_t * ent, int event, int eventParm)
Adds an event+parm and twiddles the event counter.
Parameters
[in,out] ent
[in] event
[in] eventParm
Definition at line 1057 of file g_utils.c.
Referenced by _et_G_AddEvent(), _et_RemoveWeaponFromPlayer(), alarmbox_use(), checkpoint_spawntouch(), checkpoint_touch(), ClientDisconnect(), Do_Activate2_f(), func_explosive_explode(), G_AnimScriptSound(), G_Damage(), G_DropWeapon(), G_FreeSatchel(), G_MissileImpact(), G_PlaySound_Cmd(), G_PushPlayer(), G_RunMissile(), G_ScriptAction_PlaySound(), G_TryDoor(), GibEntity(), GotoPos3(), P_DamageFeedback(), player_die(), Prop_Break_Sound(), Props_Chair_Touch(), props_flamethrower_think(), props_statue_death(), Reached_BinaryMover(), Reached_TrinaryMover(), ReturnToPos1(), ReturnToPos1Rotate(), ReturnToPos2(), Spawn_Junk(), Spawn_Shard(), target_rumble_think(), Touch_Item(), TryConstructing(), Use_BinaryMover(), Use_Shooter(), Use_Target_Speaker(), Use_TrinaryMover(), weapon_callPlane(), Weapon_Engineer(), and weapon_satcheldet_fire().
void G_AddPredictableEvent (gentity_t * ent, int event, int eventParm)
Use for non-pmove events that would also be predicted on the client side: jumppads and item pickups Adds an event+parm and twiddles the event counter.
Parameters
[in] ent
[in] event
[in] eventParm
Definition at line 1042 of file g_utils.c.
Referenced by ammo_touch(), and heal_touch().
qboolean G_AllowTeamsAllowed (gentity_t * ent, gentity_t * activator)
G_AllowTeamsAllowed.
Parameters
[in] ent
[in] activator
Returns
Definition at line 607 of file g_utils.c.
Referenced by G_CheckForCursorHints(), G_TryDoor(), and G_UseEntity().
void G_AnimScriptSound (int soundIndex, vec3_t org, int client)
G_AnimScriptSound.
Parameters
[in] soundIndex
org - unused
[in] client
Definition at line 1125 of file g_utils.c.
Referenced by G_InitGame().
int G_CharacterIndex (const char * name)
G_CharacterIndex.
Parameters
[in] name
Returns
Note
Unused
Definition at line 271 of file g_utils.c.
void G_ClientSound (gentity_t * ent, int soundIndex)
G_ClientSound.
Parameters
[in] ent
[in] soundIndex
Definition at line 1103 of file g_utils.c.
Referenced by _et_G_ClientSound(), and G_PlaySound_Cmd().
int G_EntitiesFree (void)
G_EntitiesFree.
Returns
Definition at line 872 of file g_utils.c.
Referenced by _et_G_EntitiesFree(), and G_DrawEntBBox().
gentity_t* G_Find (gentity_t * from, int fieldofs, const char * match)
Searches all active entities for the next one that holds the matching string at fieldofs (use the FOFS() macro) in the structure. Searches beginning at the entity after from, or the beginning if NULL NULL will be returned if the end of the list is reached.
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 320 of file g_utils.c.
Referenced by AutoBuildConstruction(), ETInterface::FindEntityInSphere(), FindIntermissionPoint(), findNonAIBrushTargeter(), func_constructiblespawn(), G_ScriptAction_Accum(), G_ScriptAction_Cvar(), G_ScriptAction_Delete(), G_ScriptAction_GlobalAccum(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetMainObjective(), G_ScriptAction_TagConnect(), G_ScriptAction_Trigger(), GetMG42s(), HandleEntsThatBlockConstructible(), SelectNearestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomTeamSpawnPoint(), smoke_init(), SP_props_snowGenerator(), target_script_trigger_use(), TryConstructing(), Use_Props_Shard_Generator(), and Use_Target_Lock().
gentity_t* G_FindByTargetname (gentity_t * from, const char * match)
G_FindByTargetname.
Parameters
[in,out] from
[in] match
Returns
Definition at line 475 of file g_utils.c.
Referenced by alarmbox_updateparts(), ClientBegin(), constructiblemarker_setup(), dust_angles_think(), ETInterface::EntityByName(), func_constructiblespawn(), G_CheckForCursorHints(), G_KillEnts(), G_LinkDamageParents(), G_LinkDebris(), G_PickTarget(), G_ScriptAction_Accum(), G_ScriptAction_AddTankAmmo(), G_ScriptAction_AttatchToTrain(), G_ScriptAction_Construct(), G_ScriptAction_GotoMarker(), G_ScriptAction_RepairMG42(), G_ScriptAction_SetDamagable(), G_ScriptAction_SetPosition(), G_ScriptAction_SetTankAmmo(), G_ScriptAction_TagConnect(), ETInterface::GetGoals(), info_limbo_camera_setup(), locateMaster(), misc_beam_start(), misc_firetrails_think(), props_flamethrower_init(), props_flamethrower_think(), script_mover_spawn(), sparks_angles_think(), target_laser_start(), target_speaker_multiple(), Think_SetupObjectiveInfo(), Think_SetupTrainTargets(), Think_SetupTrainTargets_rotating(), trigger_ammo_setup(), trigger_heal_setup(), Use_DamageInflictor(), and Use_Target_Give().
gentity_t* G_FindByTargetnameFast (gentity_t * from, const char * match, int hash)
This version should be used for loops, saves the constant hash building.
Parameters
[in,out] from
[in] match
[in] hash
Returns
Definition at line 525 of file g_utils.c.
Referenced by checkpoint_spawntouch(), func_explosive_explode(), G_ScriptAction_AlertEntity(), G_ScriptAction_SetState(), and G_UseTargets().
int G_FindConfigstringIndex (const char * name, int start, int max, qboolean create)
G_FindConfigstringIndex.
=========================================================================
model / sound configstring indexes
Parameters
[in] name
[in] start
[in] max
[in] create
Returns
Definition at line 144 of file g_utils.c.
Referenced by dlight_finish_spawning(), G_CharacterIndex(), G_ModelIndex(), G_ProcessTagConnect(), G_ShaderIndex(), G_SkinIndex(), G_SoundIndex(), and G_StringIndex().
gentity_t* G_FindFloat (gentity_t * from, int fieldofs, float match)
Like G_Find, but searches for float values..
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 398 of file g_utils.c.
Referenced by G_ScriptAction_Delete().
gentity_t* G_FindInt (gentity_t * from, int fieldofs, int match)
Like G_Find, but searches for integer values.
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 361 of file g_utils.c.
Referenced by G_ScriptAction_Delete().
gentity_t* G_FindVector (gentity_t * from, int fieldofs, const vec3_t match)
Like G_Find, but searches for vector values..
Parameters
[in,out] from
[in] fieldofs
[in] match
Returns
Definition at line 435 of file g_utils.c.
Referenced by G_ScriptAction_Delete().
void G_FreeEntity (gentity_t * ent)
Marks the entity as free.
Parameters
[in,out] ent
Todo:
: remove tmp var l_free if we are sure there are no issues caused by this change (especially on network games)
Definition at line 894 of file g_utils.c.
Referenced by _et_G_FreeEntity(), AimAtTarget(), BecomeExplosion(), Blocked_Door(), Blocked_DoorRotate(), ClientEndFrame(), ClientThink_real(), constructible_indicator_think(), crate_animate(), DynaSink(), explosive_indicator_think(), FinishSpawningItem(), firetrail_die(), func_brushmodel_delete(), func_constructible_explode(), G_AirStrikeThink(), G_BodyDP(), G_delayPrint(), G_DettachBodyParts(), G_FadeItems(), G_KillEnts(), G_MagicSink(), G_MoverPush(), G_RealExplodedMissile(), G_RunEntity(), G_RunFlamechunk(), G_RunItem(), G_RunMissile(), G_ScriptAction_Delete(), G_ScriptAction_RemoveEntity(), G_SetEntState(), G_SpawnGEntityFromSpawnVars(), ETInterface::GetGoals(), HandleEntsThatBlockConstructible(), hurt_think(), info_limbo_camera_setup(), IsHeadShot(), IsLegShot(), landmine_setup(), locateCamera(), locateMaster(), mg42_spawn(), misc_beam_start(), multi_trigger(), OilParticles_think(), Props_Activated(), Props_Barrel_Animate(), Props_Chair_Animate(), Props_Chair_Skyboxtouch(), props_decoration_death(), props_flippy_blocked(), props_radio_die(), props_radio_dieSEVEN(), props_statue_death(), Psmoke_think(), script_mover_blocked(), script_mover_die(), smoke_think(), smoker_think(), SP_corona(), SP_func_debris(), SP_func_train(), SP_func_train_rotating(), SP_info_limbo_camera(), SP_info_null(), SP_info_train_spline_main(), SP_light(), SP_lightJunior(), SP_misc_gamemodel(), SP_misc_light_surface(), SP_misc_model(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_path_corner(), SP_path_corner_2(), SP_props_sparks(), SP_target_location(), SP_trigger_concussive_dust(), Spawn_Junk(), Spawn_Shard(), Team_ResetFlag(), Touch_flagonly(), trigger_always_think(), Use_DamageInflictor(), Use_Props_Shard_Generator(), Weapon_Engineer(), and weapon_smokeBombExplode().
team_t G_GetTeamFromEntity (gentity_t * ent)
G_GetTeamFromEntity.
Parameters
[in] ent
Returns
Definition at line 1835 of file g_utils.c.
Referenced by G_Damage(), and player_die().
void G_InitGentity (gentity_t * e)
G_InitGentity.
Parameters
[in,out] e
Definition at line 779 of file g_utils.c.
Referenced by ClientBegin(), and G_Spawn().
static qboolean G_LoadCampaignsFromFile (const char * filename) static
G_LoadCampaignsFromFile.
Parameters
[in] filename
Returns
Definition at line 1490 of file g_utils.c.
Referenced by G_ParseCampaigns().
qboolean G_MapIsValidCampaignStartMap (void)
G_MapIsValidCampaignStartMap.
Returns
Definition at line 1693 of file g_utils.c.
Referenced by G_UpdateCvars().
qboolean G_MatchString (const char * filter, const char * name, int casesensitive)
G_MatchString.
Parameters
[in] filter
[in] name
[in] casesensitive
Returns
Definition at line 1936 of file g_utils.c.
Referenced by G_Script_GetEventIndex(), and G_Script_ScriptRun().
int G_ModelIndex (const char * name)
G_ModelIndex.
Parameters
[in] name
Returns
Definition at line 229 of file g_utils.c.
Referenced by _et_G_ModelIndex(), aagun_spawn(), FinishSpawningItem(), flak_spawn(), G_Script_ScriptParse(), G_ScriptAction_ChangeModel(), G_SpawnItem(), InitExplosive(), InitMover(), InitMoverRotate(), InitProp(), mg42_spawn(), misc_firetrails_think(), script_model_med_spawn(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_func_leaky(), SP_func_static(), SP_misc_constructiblemarker(), SP_misc_gamemodel(), SP_props_box_32(), SP_props_box_48(), SP_props_box_64(), SP_Props_Chair(), SP_Props_ChairChat(), SP_Props_ChairChatArm(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_props_decoration(), SP_props_decorBRUSH(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_footlocker(), SP_props_statue(), SP_props_statueBRUSH(), and SP_team_WOLF_checkpoint().
void G_ParseCampaigns (void)
G_ParseCampaigns.
Definition at line 1713 of file g_utils.c.
Referenced by G_InitGame().
gentity_t* G_PickTarget (const char * targetname)
Selects a random entity from among the targets.
Parameters
[in] targetname
Returns
Definition at line 566 of file g_utils.c.
Referenced by AimAtTarget(), FindIntermissionPoint(), ETInterface::GetAutoNavFeatures(), InitShooter_Finish(), locateCamera(), SP_info_player_deathmatch(), SP_team_CTF_bluespawn(), SP_team_CTF_redspawn(), target_relay_use(), target_teleporter_use(), and trigger_teleporter_touch().
gentity_t* G_PopupMessage (popupMessageType_t type)
G_PopupMessage.
Parameters
[in] type
Returns
Definition at line 1011 of file g_utils.c.
Referenced by G_PopupMessageForMines(), SetTeam(), Team_ReturnFlagSound(), Team_TouchEnemyFlag(), and Weapon_Engineer().
void G_PrintClientSpammyCenterPrint (int entityNum, const char * text)
G_PrintClientSpammyCenterPrint.
Parameters
[in] entityNum
[in] text
Definition at line 1814 of file g_utils.c.
Referenced by TryConstructing(), and Weapon_Engineer().
void G_ProcessTagConnect (gentity_t * ent, qboolean clearAngles)
G_ProcessTagConnect.
Tag connections
Parameters
[in,out] ent
[in] clearAngles
Definition at line 1205 of file g_utils.c.
Referenced by Do_Activate_f(), G_ScriptAction_TagConnect(), and misc_firetrails_think().
void G_RemoveConfigstringIndex (const char * name, int start, int max)
Prevent player always mounting the last gun used, on multiple tank maps. Ported from the Bugfix project (#087)
Parameters
[in] name
[in] start
[in] max
Definition at line 190 of file g_utils.c.
Referenced by G_LeaveTank().
void G_ResetRemappedShaders (void)
G_ResetRemappedShaders.
Definition at line 92 of file g_utils.c.
Referenced by _et_G_ResetRemappedShaders(), and G_InitGame().
void G_SetAngle (gentity_t * ent, vec3_t angle)
G_SetAngle.
Parameters
[out] ent
[in] angle
Definition at line 1161 of file g_utils.c.
Referenced by aagun_spawn(), FinishSpawningItem(), G_BounceItem(), init_locker(), InitProp(), LaunchItem(), Props_Activated(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_misc_cabinet_health(), SP_misc_cabinet_supply(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_statue(), SP_script_mover(), SP_team_WOLF_checkpoint(), Spawn_Junk(), and Spawn_Shard().
void G_SetEntState (gentity_t * ent, entState_t state)
Sets the entstate of an entity.
Parameters
[in,out] ent
[in] state
Definition at line 1291 of file g_utils.c.
Referenced by _et_G_SetEntState(), AutoBuildConstruction(), func_constructible_underconstructionthink(), G_ScriptAction_SetState(), mg42_spawn(), and TryConstructing().
void G_SetMovedir (vec3_t angles, vec3_t movedir)
The editor only specifies a single value for angles (yaw), but we have special constants to generate an up or down direction. Angles will be cleared, because it is being used to represent a direction instead of an orientation.
Parameters
[in,out] angles
[out] movedir
Definition at line 753 of file g_utils.c.
Referenced by InitShooter(), InitTrigger(), locateCamera(), SP_func_button(), SP_func_door(), SP_func_secret(), SP_target_push(), and target_laser_start().
void G_SetOrigin (gentity_t * ent, vec3_t origin)
Sets the pos trajectory for a fixed position.
Parameters
[out] ent
[in] origin
Definition at line 1139 of file g_utils.c.
Referenced by aagun_spawn(), ClientSpawn(), DropToFloor(), DropToFloorG(), FinishSpawningItem(), flak_spawn(), G_BounceItem(), G_BounceMissile(), G_BuildHead(), G_BuildLeg(), G_PositionEntityOnTag(), G_ScriptAction_SetPosition(), G_TempEntity(), init_locker(), InitProp(), landmine_setup(), LaunchItem(), mg42_spawn(), Props_Activated(), SP_alarm_box(), SP_crate_32(), SP_crate_64(), SP_Dust(), SP_func_fakebrush(), SP_info_camp(), SP_info_notnull(), SP_misc_cabinet_health(), SP_misc_cabinet_supply(), SP_misc_commandmap_marker(), SP_misc_gamemodel(), SP_misc_vis_dummy(), SP_misc_vis_dummy_multiple(), SP_Props_Chair(), SP_Props_ChairHiback(), SP_Props_ChairSide(), SP_Props_ChateauChair(), SP_Props_DamageInflictor(), SP_props_decoration(), SP_Props_Desklamp(), SP_Props_Flamebarrel(), SP_props_flamethrower(), SP_props_gunsparks(), SP_props_shard_generator(), SP_props_statue(), SP_SmokeDust(), SP_target_position(), SP_target_script_trigger(), SP_target_smoke(), SP_team_WOLF_checkpoint(), Spawn_Junk(), Spawn_Shard(), and Think_SetupObjectiveInfo().
int G_ShaderIndex (const char * name)
G_ShaderIndex.
Parameters
[in] name
Returns
Definition at line 259 of file g_utils.c.
Referenced by BuildShaderStateConfig(), G_ModifyTOI(), G_Script_ScriptParse(), SP_misc_beam(), SP_target_smoke(), and SP_trigger_objective_info().
int G_SkinIndex (const char * name)
G_SkinIndex.
Parameters
[in] name
Returns
Definition at line 249 of file g_utils.c.
Referenced by SP_misc_constructiblemarker(), and SP_misc_gamemodel().
void G_Sound (gentity_t * ent, int soundIndex)
Removed channel parm, since it wasn't used, and could cause confusion.
Parameters
[in] ent
[in] soundIndex
Definition at line 1089 of file g_utils.c.
Referenced by _et_G_Sound(), hurt_touch(), P_WorldEffects(), ReviveEntity(), target_relay_use(), use_invisible_user(), and Use_target_push().
int G_SoundIndex (const char * name)
G_SoundIndex.
Parameters
[in] name
Returns
Definition at line 239 of file g_utils.c.
Referenced by _et_G_SoundIndex(), DoorSetSounds(), G_globalSound(), G_InitGame(), G_PlaySound_Cmd(), G_Script_ScriptParse(), G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_PlaySound(), G_ScriptAction_RemoveTeamVoiceAnnounce(), G_ScriptAction_TeamVoiceAnnounce(), G_SpawnItem(), InitProp(), SP_alarm_box(), SP_dlight(), SP_func_button(), SP_func_explosive(), SP_func_invisible_user(), SP_func_plat(), SP_func_secret(), SP_props_decoration(), SP_props_footlocker(), SP_props_statue(), SP_target_explosion(), SP_target_push(), SP_target_relay(), SP_target_rumble(), SP_target_speaker(), SP_team_WOLF_checkpoint(), SP_trigger_hurt(), and SP_trigger_teleport().
gentity_t* G_Spawn (void)
Either finds a free entity, or allocates a new one.
The slots from 0 to MAX_CLIENTS-1 are always reserved for clients, and will never be used by anything else.
Try to avoid reusing an entity that was recently freed, because it can cause the client to think the entity morphed into something else instead of being removed and recreated, which can cause interpolated angles and bad trails.
Returns
Todo:
: inspect -> add '&& level.startTime != 0' for warmup?
Definition at line 813 of file g_utils.c.
Referenced by AutoBuildConstruction(), CopyToBodyQue(), fire_flamebarrel(), fire_flamechunk(), fire_missile(), flak_spawn(), func_constructiblespawn(), G_BuildHead(), G_BuildLeg(), G_PopupMessage(), G_SpawnGEntityFromSpawnVars(), G_spawnPrintf(), G_TempEntity(), G_TempEntityNotLinked(), InitBodyQue(), LaunchItem(), mg42_spawn(), misc_firetrails_think(), OilSlick_remove(), prop_smoke(), propExplosion(), Props_Activated(), Spawn_Junk(), Spawn_Shard(), SpawnPlatTrigger(), Think_SetupObjectiveInfo(), Think_SpawnNewDoorTrigger(), TryConstructing(), Weapon_Artillery(), and weapon_callAirStrike().
const char* G_StringContains (const char * str1, const char * str2, int casesensitive)
G_StringContains.
Parameters
[in] str1
[in] str2
[in] casesensitive
Returns
Definition at line 1897 of file g_utils.c.
Referenced by G_MatchString().
int G_StringIndex (const char * string)
G_StringIndex.
Parameters
[in] string
Returns
Definition at line 281 of file g_utils.c.
Referenced by Team_ReturnFlagSound(), and Team_TouchEnemyFlag().
void G_TeamCommand (team_t team, const char * cmd)
Broadcasts a command to only a specific team.
Parameters
[in] team
[in] cmd
Definition at line 293 of file g_utils.c.
Referenced by Use_Target_Print().
gentity_t* G_TempEntity (vec3_t origin, entity_event_t event)
Spawns an event entity that will be auto-removed.
The origin will be snapped to save net bandwidth, so care must be taken if the origin is right on a surface (snap towards start vector first)
Parameters
[in] origin
[in] event
Returns
Definition at line 956 of file g_utils.c.
Referenced by _et_G_TempEntity(), barrel_smoke(), BodyUnlink(), Bullet_Fire_Extended(), dust_use(), EmitterCheck(), Fire_Lead_Ext(), flakPuff(), func_constructible_underconstructionthink(), G_BodyDP(), G_GlobalClientEvent(), G_Pip(), G_RailBox(), G_RailTrail(), G_RealExplodedMissile(), G_RunFlamechunk(), G_RunMissile(), G_ScriptAction_DisableSpeaker(), G_ScriptAction_EnableSpeaker(), G_ScriptAction_SpawnRubble(), G_ScriptAction_ToggleSpeaker(), G_Sound(), OilParticles_think(), OilSlick_remove_think(), PGUNsparks_use(), props_locker_mass(), props_snowGenerator_think(), Psmoke_think(), smokedust_use(), SP_OilSlick(), target_effect(), target_explosion_use(), target_rumble_think(), Touch_Item(), Use_Shooter(), and Weapon_Knife().
gentity_t* G_TempEntityNotLinked (entity_event_t event)
Spawns an event entity that will be auto-removed Use this for non visible and not origin based events like global sounds etc.
Parameters
[in] event
Returns
Note
Don't forget to call e->r.svFlags = SVF_BROADCAST; after
Definition at line 990 of file g_utils.c.
Referenced by G_clientFlagIndicator(), G_ClientSound(), G_globalFlagIndicator(), G_globalSound(), G_globalSoundEnum(), G_ScriptAction_TeamVoiceAnnounce(), player_die(), and SetTeam().
void G_UseEntity (gentity_t * ent, gentity_t * other, gentity_t * activator)
Added to allow more checking on what uses what.
Parameters
[in,out] ent
[in] other
[in] activator
Definition at line 646 of file g_utils.c.
Referenced by alarmbox_updateparts(), Do_Activate_f(), func_constructible_explode(), func_constructible_underconstructionthink(), G_Damage(), G_ScriptAction_AlertEntity(), G_UseTargets(), target_relay_use(), and TryConstructing().
void G_UseTargets (gentity_t * ent, gentity_t * activator)
Search for (string)targetname in all entities that match (string)self.target and call their .use function.
Parameters
[in] ent
[in] activator Should be set to the entity that initiated the firing.
Definition at line 665 of file g_utils.c.
Referenced by ClientSpawn(), crate_animate(), Do_Activate_f(), func_explosive_explode(), func_timer_think(), G_RealExplodedMissile(), G_TryDoor(), locker_tall_think(), multi_trigger(), props_58x112tablew_think(), Props_Barrel_Die(), props_bench_think(), props_castlebed_animate(), Props_Chair_Animate(), Props_Chair_Touch(), props_crate32x64_think(), props_decoration_death(), props_flippy_table_die(), props_locker_tall_die(), props_radio_die(), props_radio_dieSEVEN(), props_statue_death(), Props_TurnLightsOff(), Reached_BinaryMover(), Reached_Train(), Reached_Train_rotating(), Reached_TrinaryMover(), Static_Pain(), target_effect(), target_explosion_use(), target_relay_use(), target_script_trigger_use(), Think_Target_Delay(), Touch_Item(), trigger_always_think(), use_invisible_user(), Use_Target_Alarm(), and Use_Target_Counter().
qboolean infront (gentity_t * self, gentity_t * other)
infront
Parameters
[in] self
[in] other
Returns
Definition at line 1178 of file g_utils.c.
Referenced by flippy_table_use(), G_EmplacedGunIsMountable(), and player_die().
char* vtos (const vec3_t v)
This is just a convenience function for printing vectors.
Parameters
[in] v
Returns
Definition at line 729 of file g_utils.c.
Variable Documentation
int remapCount = 0
Definition at line 51 of file g_utils.c.
Referenced by AddRemap(), BuildShaderStateConfig(), and G_ResetRemappedShaders().
shaderRemap_t remappedShaders[MAX_SHADER_REMAPS]
Definition at line 52 of file g_utils.c.