ET: Legacy: src/game/g_vote.c File Reference
g_vote.c File Reference
All callvote handling.
#include "g_local.h"
#include "../../etmain/ui/menudef.h"
Data Structures
struct vote_reference_t
Macros
#define T_FFA 0x01
#define T_1V1 0x02
#define T_SP 0x04
#define T_TDM 0x08
#define T_CTF 0x10
#define T_WLF 0x20
#define T_WSW 0x40
#define T_WCP 0x80
#define T_WCH 0x100
Functions
int G_voteCmdCheck (gentity_t *ent, char *arg, char *arg2, qboolean fRefereeCmd)
Checks for valid custom callvote requests from the client.
void G_voteHelp (gentity_t *ent, qboolean fShowVote)
Voting help summary.
void G_voteFlags (void)
Set disabled votes for client UI.
qboolean G_voteDescription (gentity_t *ent, qboolean fRefereeCmd, unsigned int cmd)
Prints specific callvote command help description.
void G_voteDisableMessage (gentity_t *ent, const char *cmd)
Localize disable message info.
void G_playersMessage (gentity_t *ent)
Player ID message stub.
void G_voteCurrentSetting (gentity_t *ent, const char *cmd, const char *setting)
Localize current parameter setting.
int G_voteProcessOnOff (gentity_t *ent, char *arg, char *arg2, qboolean fRefereeCmd, int curr_setting, int vote_allow, unsigned int vote_type)
Vote toggling.
void G_voteSetOnOff (const char *desc, const char *cvar)
G_voteSetOnOff.
void G_voteSetValue (const char *desc, const char *cvar)
G_voteSetValue.
void G_voteSetVoteString (const char *desc)
G_voteSetVoteString.
void G_GametypeList (gentity_t *ent)
G_GametypeList.
int G_Gametype_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
GameType.
int G_Kick_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Player Kick.
int G_Mute_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Player Mute.
int G_UnMute_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Player Un-Mute.
int G_Map_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Map - simpleton: we dont verify map is allowed/exists.
int G_Campaign_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Campaign - simpleton: we dont verify map is allowed/exists.
int G_MapRestart_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Map Restart.
int G_MatchReset_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Match Restart.
int G_Mutespecs_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Mute Spectators.
int G_Nextmap_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Nextmap.
int G_Referee_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Referee voting.
int G_ShuffleTeamsXP_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Shuffle teams by XP.
int G_StartMatch_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Start Match.
int G_SwapTeams_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Swap teams.
int G_FriendlyFire_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Team Damage.
int G_AntiLag_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Anti-Lag.
int G_BalancedTeams_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Balanced Teams.
int G_Config_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_Config_v.
int G_Timelimit_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Timelimit.
void G_WarmupDamageTypeList (gentity_t *ent)
G_WarmupDamageTypeList.
int G_Warmupfire_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Warmup Weapon Fire.
int G_Unreferee_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Un-Referee voting.
void G_IntermissionMapVote (gentity_t *ent)
G_IntermissionMapVote.
void G_IntermissionMapList (gentity_t *ent)
G_IntermissionMapList.
void G_IntermissionVoteTally (gentity_t *ent)
G_IntermissionVoteTally.
int G_ShuffleTeamsXP_NoRestart_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
Shuffle teams by XP without restart.
int G_Surrender_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_Surrender_v.
int G_NextCampaign_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_NextCampaign_v.
int G_RestartCampaign_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_RestartCampaign_v.
int G_Poll_v (gentity_t *ent, unsigned int dwVoteIndex, char *arg, char *arg2, qboolean fRefereeCmd)
G_Poll_v.
Variables
static const char * ACTIVATED = "ACTIVATED"
static const char * DEACTIVATED = "DEACTIVATED"
static const char * ENABLED = "ENABLED"
static const char * DISABLED = "DISABLED"
static const vote_reference_t aVoteInfo []
VC optimizes for dup strings :)
const char * warmupType [] = { "None", "Enemies Only", "Everyone" }
Detailed Description
All callvote handling.
Definition in file g_vote.c.
Macro Definition Documentation
#define T_1V1 0x02
Definition at line 40 of file g_vote.c.
#define T_CTF 0x10
Definition at line 43 of file g_vote.c.
#define T_FFA 0x01
Definition at line 39 of file g_vote.c.
#define T_SP 0x04
Definition at line 41 of file g_vote.c.
#define T_TDM 0x08
Definition at line 42 of file g_vote.c.
#define T_WCH 0x100
Definition at line 47 of file g_vote.c.
#define T_WCP 0x80
Definition at line 46 of file g_vote.c.
#define T_WLF 0x20
Definition at line 44 of file g_vote.c.
#define T_WSW 0x40
Definition at line 45 of file g_vote.c.
Function Documentation
int G_AntiLag_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Anti-Lag.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1253 of file g_vote.c.
int G_BalancedTeams_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Balanced Teams.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1282 of file g_vote.c.
int G_Campaign_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Campaign - simpleton: we dont verify map is allowed/exists.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 736 of file g_vote.c.
int G_Config_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_Config_v.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1313 of file g_vote.c.
int G_FriendlyFire_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Team Damage.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1224 of file g_vote.c.
int G_Gametype_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
GameType.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 395 of file g_vote.c.
void G_GametypeList (gentity_t * ent)
G_GametypeList.
Parameters
[in] ent
Definition at line 369 of file g_vote.c.
Referenced by G_Gametype_v().
void G_IntermissionMapList (gentity_t * ent)
G_IntermissionMapList.
Parameters
[in] ent
Definition at line 1648 of file g_vote.c.
Referenced by ClientCommand().
void G_IntermissionMapVote (gentity_t * ent)
G_IntermissionMapVote.
Parameters
[in,out] ent
Definition at line 1568 of file g_vote.c.
Referenced by ClientCommand().
void G_IntermissionVoteTally (gentity_t * ent)
G_IntermissionVoteTally.
Parameters
[in] ent
Definition at line 1685 of file g_vote.c.
Referenced by ClientCommand(), ClientDisconnect(), ClientSpawn(), and G_IntermissionMapVote().
int G_Kick_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Player Kick.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 457 of file g_vote.c.
Referenced by CheckVote(), Cmd_CallVote_f(), and Cmd_Vote_f().
int G_Map_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Map - simpleton: we dont verify map is allowed/exists.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 677 of file g_vote.c.
int G_MapRestart_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Map Restart.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 792 of file g_vote.c.
int G_MatchReset_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Match Restart.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 827 of file g_vote.c.
int G_Mute_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Player Mute.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 529 of file g_vote.c.
Referenced by Cmd_CallVote_f().
int G_Mutespecs_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Mute Spectators.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 862 of file g_vote.c.
int G_NextCampaign_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_NextCampaign_v.
Parameters
ent - unused
dwVoteIndex - unused
[in] arg
arg2 - unused
fRefereeCmd - unused
Returns
Definition at line 1854 of file g_vote.c.
int G_Nextmap_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Nextmap.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 891 of file g_vote.c.
void G_playersMessage (gentity_t * ent)
Player ID message stub.
Parameters
[in] ent
Definition at line 268 of file g_vote.c.
Referenced by G_Referee_v(), and G_Unreferee_v().
int G_Poll_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_Poll_v.
Parameters
ent - unused
dwVoteIndex - unused
[in] arg
[out] arg2
fRefereeCmd - unused
Returns
Definition at line 1935 of file g_vote.c.
Referenced by Cmd_CallVote_f().
int G_Referee_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Referee voting.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Todo:
: Differentiate voted refs from passworded refs
Definition at line 987 of file g_vote.c.
int G_RestartCampaign_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_RestartCampaign_v.
Parameters
ent - unused
dwVoteIndex - unused
[in] arg
arg2 - unused
fRefereeCmd - unused
Returns
Definition at line 1897 of file g_vote.c.
int G_ShuffleTeamsXP_NoRestart_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Shuffle teams by XP without restart.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 1734 of file g_vote.c.
int G_ShuffleTeamsXP_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Shuffle teams by XP.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 1064 of file g_vote.c.
int G_StartMatch_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Start Match.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1136 of file g_vote.c.
int G_Surrender_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
G_Surrender_v.
Parameters
[in] ent
dwVoteIndex - unused
[in] arg
[in] arg2
fRefereeCmd - unused
Returns
Definition at line 1808 of file g_vote.c.
Referenced by CheckVote(), and Cmd_Vote_f().
int G_SwapTeams_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Swap teams.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
arg2 - unused
[in] fRefereeCmd
Returns
Definition at line 1188 of file g_vote.c.
int G_Timelimit_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Timelimit.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 1368 of file g_vote.c.
int G_UnMute_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Player Un-Mute.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 609 of file g_vote.c.
int G_Unreferee_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Un-Referee voting.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 1490 of file g_vote.c.
int G_voteCmdCheck (gentity_t * ent, char * arg, char * arg2, qboolean fRefereeCmd)
Checks for valid custom callvote requests from the client.
Parameters
[in] ent
[in] arg
[in] arg2
[in] fRefereeCmd
Returns
Definition at line 113 of file g_vote.c.
Referenced by Cmd_CallVote_f().
void G_voteCurrentSetting (gentity_t * ent, const char * cmd, const char * setting)
Localize current parameter setting.
Parameters
[in] ent
[in] cmd
[in] setting
Definition at line 279 of file g_vote.c.
Referenced by G_Campaign_v(), G_Gametype_v(), G_Map_v(), G_Timelimit_v(), G_voteProcessOnOff(), and G_Warmupfire_v().
qboolean G_voteDescription (gentity_t * ent, qboolean fRefereeCmd, unsigned int cmd)
Prints specific callvote command help description.
Parameters
[in] ent
[in] fRefereeCmd
[in] cmd
Returns
Definition at line 233 of file g_vote.c.
Referenced by G_Campaign_v(), G_Config_v(), G_Gametype_v(), G_Kick_v(), G_Map_v(), G_MapRestart_v(), G_MatchReset_v(), G_Mute_v(), G_Referee_v(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_voteProcessOnOff(), and G_Warmupfire_v().
void G_voteDisableMessage (gentity_t * ent, const char * cmd)
Localize disable message info.
Parameters
[in] ent
[in] cmd
Definition at line 259 of file g_vote.c.
Referenced by G_Campaign_v(), G_Config_v(), G_Gametype_v(), G_Kick_v(), G_Map_v(), G_MapRestart_v(), G_MatchReset_v(), G_Mute_v(), G_Nextmap_v(), G_Referee_v(), G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), G_SwapTeams_v(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_voteProcessOnOff(), and G_Warmupfire_v().
void G_voteFlags (void)
Set disabled votes for client UI.
Definition at line 208 of file g_vote.c.
Referenced by G_loadMatchGame(), and G_UpdateCvars().
void G_voteHelp (gentity_t * ent, qboolean fShowVote)
Voting help summary.
Parameters
[in] ent
[in] fShowVote
Definition at line 145 of file g_vote.c.
Referenced by Cmd_CallVote_f(), and G_refHelp_cmd().
int G_voteProcessOnOff (gentity_t * ent, char * arg, char * arg2, qboolean fRefereeCmd, int curr_setting, int vote_allow, unsigned int vote_type)
Vote toggling.
Parameters
[in] ent
arg - unused
[in] arg2
[in] fRefereeCmd
[in] curr_setting
[in] vote_allow
[in] vote_type
Returns
Definition at line 295 of file g_vote.c.
Referenced by G_AntiLag_v(), G_BalancedTeams_v(), G_FriendlyFire_v(), and G_Mutespecs_v().
void G_voteSetOnOff (const char * desc, const char * cvar)
G_voteSetOnOff.
Several commands to help with cvar setting
Parameters
[in] desc
[in] cvar
Definition at line 330 of file g_vote.c.
Referenced by G_AntiLag_v(), G_BalancedTeams_v(), G_FriendlyFire_v(), and G_Mutespecs_v().
void G_voteSetValue (const char * desc, const char * cvar)
G_voteSetValue.
Parameters
[in] desc
[in] cvar
Definition at line 342 of file g_vote.c.
Referenced by G_Gametype_v().
void G_voteSetVoteString (const char * desc)
G_voteSetVoteString.
Parameters
[in] desc
Definition at line 353 of file g_vote.c.
Referenced by G_Timelimit_v().
void G_WarmupDamageTypeList (gentity_t * ent)
G_WarmupDamageTypeList.
Parameters
[in] ent
Definition at line 1409 of file g_vote.c.
Referenced by G_Warmupfire_v().
int G_Warmupfire_v (gentity_t * ent, unsigned int dwVoteIndex, char * arg, char * arg2, qboolean fRefereeCmd)
Warmup Weapon Fire.
Parameters
[in] ent
[in] dwVoteIndex
[in] arg
[in,out] arg2
[in] fRefereeCmd
Returns
Definition at line 1430 of file g_vote.c.
Variable Documentation
const char* ACTIVATED = "ACTIVATED" static
Definition at line 49 of file g_vote.c.
Referenced by G_voteProcessOnOff().
aVoteInfo static
VC optimizes for dup strings :)
Definition at line 70 of file g_vote.c.
Referenced by G_voteCmdCheck(), and G_voteHelp().
const char* DEACTIVATED = "DEACTIVATED" static
Definition at line 50 of file g_vote.c.
Referenced by G_voteProcessOnOff().
const char* DISABLED = "DISABLED" static
Definition at line 52 of file g_vote.c.
Referenced by G_voteProcessOnOff(), and G_voteSetOnOff().
const char* ENABLED = "ENABLED" static
Definition at line 51 of file g_vote.c.
Referenced by G_voteProcessOnOff(), and G_voteSetOnOff().
const char* warmupType[] = { "None", "Enemies Only", "Everyone" }
Definition at line 1403 of file g_vote.c.
Referenced by G_WarmupDamageTypeList(), and G_Warmupfire_v().