ET: Legacy: Lua functions
Lua functions
Lua API for the Legacy mod
Functions
static int _et_RegisterModname (lua_State *L)
Registers a name for this Lua module.
static int _et_FindSelf (lua_State *L)
Gets slot number assigned to this lua VM.
static int _et_FindMod (lua_State *L)
Gets name of lua module at slot vmnumber and its signature hash.
static int _et_IPCSend (lua_State *L)
static int _et_G_Print (lua_State *L)
static int _et_G_LogPrint (lua_State *L)
static int _et_ConcatArgs (lua_State *L)
static int _et_trap_Argc (lua_State *L)
static int _et_trap_Argv (lua_State *L)
static int _et_trap_Cvar_Get (lua_State *L)
static int _et_trap_Cvar_Set (lua_State *L)
static int _et_trap_GetConfigstring (lua_State *L)
static int _et_trap_SetConfigstring (lua_State *L)
static int _et_trap_SendConsoleCommand (lua_State *L)
static int _et_trap_SendServerCommand (lua_State *L)
static int _et_trap_DropClient (lua_State *L)
static int _et_ClientNumberFromString (lua_State *L)
Searches for one partial match with string, if one is found the clientnum is returned, if there is none or more than one match nil is returned.
static int _et_G_Say (lua_State *L)
static int _et_MutePlayer (lua_State *L)
static int _et_UnmutePlayer (lua_State *L)
static int _et_trap_GetUserinfo (lua_State *L)
static int _et_trap_SetUserinfo (lua_State *L)
static int _et_ClientUserinfoChanged (lua_State *L)
static int _et_Info_RemoveKey (lua_State *L)
static int _et_Info_SetValueForKey (lua_State *L)
static int _et_Info_ValueForKey (lua_State *L)
static int _et_Q_CleanStr (lua_State *L)
static int _et_trap_FS_FOpenFile (lua_State *L)
static int _et_trap_FS_Read (lua_State *L)
static int _et_trap_FS_Write (lua_State *L)
static int _et_trap_FS_FCloseFile (lua_State *L)
static int _et_trap_FS_Rename (lua_State *L)
static int _et_trap_FS_GetFileList (lua_State *L)
static int _et_G_SoundIndex (lua_State *L)
static int _et_G_ModelIndex (lua_State *L)
static int _et_G_globalSound (lua_State *L)
static int _et_G_Sound (lua_State *L)
static int _et_G_ClientSound (lua_State *L)
static int _et_trap_Milliseconds (lua_State *L)
static int _et_isBitSet (lua_State *L)
static int _et_G_Damage (lua_State *L)
static int _et_G_AddSkillPoints (lua_State *L)
static int _et_G_LoseSkillPoints (lua_State *L)
static int _et_G_XP_Set (lua_State *L)
static int _et_G_ResetXP (lua_State *L)
Reset XP of the player in slot number clientNum.
static int _et_AddWeaponToPlayer (lua_State *L)
static int _et_RemoveWeaponFromPlayer (lua_State *L)
static int _et_GetCurrentWeapon (lua_State *L)
static gentity_field_t * _et_gentity_getfield (gentity_t *ent, char *fieldname)
static void _et_gentity_getvec3 (lua_State *L, vec3_t vec3)
static void _et_gentity_setvec3 (lua_State *L, vec3_t *vec3)
static void _et_gentity_gettrajectory (lua_State *L, trajectory_t *traj)
static void _et_gentity_settrajectory (lua_State *L, trajectory_t *traj)
static void _et_gentity_getweaponstat (lua_State *L, weapon_stat_t *ws)
gentity_t * G_Lua_CreateEntity (char *params)
static int _et_G_Lua_CreateEntity (lua_State *L)
static int _et_G_Lua_DeleteEntity (lua_State *L)
static int _et_G_TempEntity (lua_State *L)
static int _et_G_FreeEntity (lua_State *L)
static int _et_G_EntitiesFree (lua_State *L)
static int _et_G_SetEntState (lua_State *L)
static int _et_trap_LinkEntity (lua_State *L)
static int _et_trap_UnlinkEntity (lua_State *L)
static int _et_G_GetSpawnVar (lua_State *L)
static int _et_G_SetSpawnVar (lua_State *L)
static int _et_gentity_get (lua_State *L)
static int _et_gentity_set (lua_State *L)
static int _et_G_AddEvent (lua_State *L)
static int _et_G_ShaderRemap (lua_State *L)
static int _et_G_ResetRemappedShaders (lua_State *L)
static int _et_G_ShaderRemapFlush (lua_State *L)
static int _et_G_SetGlobalFog (lua_State *L)
static void _et_getclipplane (lua_State *L, cplane_t *plane)
static void _et_gettrace (lua_State *L, trace_t *tr)
static vec3_t * _etH_toVec3 (lua_State *L, int inx)
static int _et_trap_Trace (lua_State *L)
static int _et_G_HistoricalTrace (lua_State *L)
Variables
char bigTextBuffer [100000]
static const gentity_field_t gclient_fields []
static const gentity_field_t gentity_fields []
Detailed Description
ET Legacy mod function calls from lua
Function Documentation
static int _et_AddWeaponToPlayer (lua_State * L) static
Definition at line 814 of file g_lua.c.
static int _et_ClientNumberFromString (lua_State * L) static
Searches for one partial match with string, if one is found the clientnum is returned, if there is none or more than one match nil is returned.
Call from lua:
clientnum = et.ClientNumberFromString(string)
See also
ClientNumbersFromString()
Definition at line 326 of file g_lua.c.
static int _et_ClientUserinfoChanged (lua_State * L) static
Definition at line 446 of file g_lua.c.
static int _et_ConcatArgs (lua_State * L) static
Definition at line 216 of file g_lua.c.
static int _et_FindMod (lua_State * L) static
Gets name of lua module at slot vmnumber and its signature hash.
Call from lua:
modname, signature = et.FindMod(vmnumber)
Returns
VM name registered by _et_RegisterModname() and SHA-1 signature of the VM
Definition at line 103 of file g_lua.c.
static int _et_FindSelf (lua_State * L) static
Gets slot number assigned to this lua VM.
Call from lua:
vmnumber = et.FindSelf()
Returns
Slot number between 0 and LUA_NUM_VM
Definition at line 83 of file g_lua.c.
static int _et_G_AddEvent (lua_State * L) static
Definition at line 1813 of file g_lua.c.
static int _et_G_AddSkillPoints (lua_State * L) static
Definition at line 693 of file g_lua.c.
static int _et_G_ClientSound (lua_State * L) static
Definition at line 634 of file g_lua.c.
static int _et_G_Damage (lua_State * L) static
Definition at line 671 of file g_lua.c.
static int _et_G_EntitiesFree (lua_State * L) static
Definition at line 1429 of file g_lua.c.
static int _et_G_FreeEntity (lua_State * L) static
Definition at line 1419 of file g_lua.c.
static int _et_G_GetSpawnVar (lua_State * L) static
Definition at line 1484 of file g_lua.c.
static int _et_G_globalSound (lua_State * L) static
Definition at line 615 of file g_lua.c.
static int _et_G_HistoricalTrace (lua_State * L) static
Definition at line 1954 of file g_lua.c.
static int _et_G_LogPrint (lua_State * L) static
Definition at line 179 of file g_lua.c.
static int _et_G_LoseSkillPoints (lua_State * L) static
Definition at line 704 of file g_lua.c.
static int _et_G_Lua_CreateEntity (lua_State * L) static
Definition at line 1379 of file g_lua.c.
static int _et_G_Lua_DeleteEntity (lua_State * L) static
Definition at line 1398 of file g_lua.c.
static int _et_G_ModelIndex (lua_State * L) static
Definition at line 605 of file g_lua.c.
static int _et_G_Print (lua_State * L) static
Definition at line 169 of file g_lua.c.
static int _et_G_ResetRemappedShaders (lua_State * L) static
Definition at line 1835 of file g_lua.c.
static int _et_G_ResetXP (lua_State * L) static
Reset XP of the player in slot number clientNum.
Call from lua:
et.G_ResetXP (clientNum)
Definition at line 789 of file g_lua.c.
static int _et_G_Say (lua_State * L) static
Definition at line 344 of file g_lua.c.
static int _et_G_SetEntState (lua_State * L) static
Definition at line 1436 of file g_lua.c.
static int _et_G_SetGlobalFog (lua_State * L) static
Definition at line 1853 of file g_lua.c.
static int _et_G_SetSpawnVar (lua_State * L) static
Definition at line 1567 of file g_lua.c.
static int _et_G_ShaderRemap (lua_State * L) static
Definition at line 1824 of file g_lua.c.
static int _et_G_ShaderRemapFlush (lua_State * L) static
Definition at line 1842 of file g_lua.c.
static int _et_G_Sound (lua_State * L) static
Definition at line 624 of file g_lua.c.
static int _et_G_SoundIndex (lua_State * L) static
Definition at line 596 of file g_lua.c.
static int _et_G_TempEntity (lua_State * L) static
Definition at line 1407 of file g_lua.c.
static int _et_G_XP_Set (lua_State * L) static
Definition at line 717 of file g_lua.c.
static int _et_gentity_get (lua_State * L) static
Definition at line 1643 of file g_lua.c.
static gentity_field_t* _et_gentity_getfield (gentity_t * ent, char * fieldname) static
Definition at line 1192 of file g_lua.c.
Referenced by _et_gentity_get(), and _et_gentity_set().
static void _et_gentity_gettrajectory (lua_State * L, trajectory_t * traj) static
Definition at line 1246 of file g_lua.c.
Referenced by _et_gentity_get().
static void _et_gentity_getvec3 (lua_State * L, vec3_t vec3) static
Definition at line 1219 of file g_lua.c.
Referenced by _et_G_GetSpawnVar(), _et_gentity_get(), _et_gentity_gettrajectory(), _et_getclipplane(), and _et_gettrace().
static void _et_gentity_getweaponstat (lua_State * L, weapon_stat_t * ws) static
Definition at line 1295 of file g_lua.c.
Referenced by _et_gentity_get().
static int _et_gentity_set (lua_State * L) static
Definition at line 1729 of file g_lua.c.
static void _et_gentity_settrajectory (lua_State * L, trajectory_t * traj) static
Definition at line 1271 of file g_lua.c.
Referenced by _et_gentity_set().
static void _et_gentity_setvec3 (lua_State * L, vec3_t * vec3) static
Definition at line 1230 of file g_lua.c.
Referenced by _et_G_SetSpawnVar(), _et_G_TempEntity(), _et_gentity_set(), _et_gentity_settrajectory(), and _etH_toVec3().
static void _et_getclipplane (lua_State * L, cplane_t * plane) static
Definition at line 1861 of file g_lua.c.
Referenced by _et_gettrace().
static int _et_GetCurrentWeapon (lua_State * L) static
Definition at line 893 of file g_lua.c.
static void _et_gettrace (lua_State * L, trace_t * tr) static
Definition at line 1880 of file g_lua.c.
Referenced by _et_G_HistoricalTrace(), and _et_trap_Trace().
static int _et_Info_RemoveKey (lua_State * L) static
Definition at line 456 of file g_lua.c.
static int _et_Info_SetValueForKey (lua_State * L) static
Definition at line 468 of file g_lua.c.
static int _et_Info_ValueForKey (lua_State * L) static
Definition at line 481 of file g_lua.c.
static int _et_IPCSend (lua_State * L) static
Definition at line 122 of file g_lua.c.
static int _et_isBitSet (lua_State * L) static
Definition at line 654 of file g_lua.c.
static int _et_MutePlayer (lua_State * L) static
Definition at line 356 of file g_lua.c.
static int _et_Q_CleanStr (lua_State * L) static
Definition at line 491 of file g_lua.c.
static int _et_RegisterModname (lua_State * L) static
Registers a name for this Lua module.
Call from lua:
et.RegisterModname(modname)
Definition at line 63 of file g_lua.c.
static int _et_RemoveWeaponFromPlayer (lua_State * L) static
Definition at line 852 of file g_lua.c.
static int _et_trap_Argc (lua_State * L) static
Definition at line 225 of file g_lua.c.
static int _et_trap_Argv (lua_State * L) static
Definition at line 232 of file g_lua.c.
static int _et_trap_Cvar_Get (lua_State * L) static
Definition at line 244 of file g_lua.c.
static int _et_trap_Cvar_Set (lua_State * L) static
Definition at line 255 of file g_lua.c.
static int _et_trap_DropClient (lua_State * L) static
Definition at line 309 of file g_lua.c.
static int _et_trap_FS_FCloseFile (lua_State * L) static
Definition at line 550 of file g_lua.c.
static int _et_trap_FS_FOpenFile (lua_State * L) static
Definition at line 503 of file g_lua.c.
static int _et_trap_FS_GetFileList (lua_State * L) static
Definition at line 569 of file g_lua.c.
static int _et_trap_FS_Read (lua_State * L) static
Definition at line 517 of file g_lua.c.
static int _et_trap_FS_Rename (lua_State * L) static
Definition at line 558 of file g_lua.c.
static int _et_trap_FS_Write (lua_State * L) static
Definition at line 539 of file g_lua.c.
static int _et_trap_GetConfigstring (lua_State * L) static
Definition at line 266 of file g_lua.c.
static int _et_trap_GetUserinfo (lua_State * L) static
Definition at line 425 of file g_lua.c.
static int _et_trap_LinkEntity (lua_State * L) static
Definition at line 1455 of file g_lua.c.
static int _et_trap_Milliseconds (lua_State * L) static
Definition at line 645 of file g_lua.c.
static int _et_trap_SendConsoleCommand (lua_State * L) static
Definition at line 288 of file g_lua.c.
static int _et_trap_SendServerCommand (lua_State * L) static
Definition at line 299 of file g_lua.c.
static int _et_trap_SetConfigstring (lua_State * L) static
Definition at line 277 of file g_lua.c.
static int _et_trap_SetUserinfo (lua_State * L) static
Definition at line 436 of file g_lua.c.
static int _et_trap_Trace (lua_State * L) static
Definition at line 1913 of file g_lua.c.
static int _et_trap_UnlinkEntity (lua_State * L) static
Definition at line 1464 of file g_lua.c.
static int _et_UnmutePlayer (lua_State * L) static
Definition at line 404 of file g_lua.c.
static vec3_t* _etH_toVec3 (lua_State * L, int inx) static
Definition at line 1901 of file g_lua.c.
Referenced by _et_G_HistoricalTrace(), and _et_trap_Trace().
gentity_t* G_Lua_CreateEntity (char * params)
Definition at line 1315 of file g_lua.c.
Referenced by _et_G_Lua_CreateEntity().
Variable Documentation
char bigTextBuffer[100000]
Definition at line 38 of file cg_character.c.
Referenced by _et_trap_FS_GetFileList(), _et_trap_FS_Rename(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), and G_ParseCampaigns().
const gentity_field_t gclient_fields[] static
Definition at line 924 of file g_lua.c.
const gentity_field_t gentity_fields[] static
Definition at line 1070 of file g_lua.c.