ET: Legacy: Lua callbacks
Lua callbacks
Lua API for the Legacy mod
Functions
void G_LuaHook_InitGame (int levelTime, int randomSeed, int restart)
void G_LuaHook_ShutdownGame (int restart)
void G_LuaHook_RunFrame (int levelTime)
qboolean G_LuaHook_ClientConnect (int clientNum, qboolean firstTime, qboolean isBot, char *reason)
void G_LuaHook_ClientDisconnect (int clientNum)
void G_LuaHook_ClientBegin (int clientNum)
void G_LuaHook_ClientUserinfoChanged (int clientNum)
void G_LuaHook_ClientSpawn (int clientNum, qboolean revived, qboolean teamChange, qboolean restoreHealth)
qboolean G_LuaHook_ClientCommand (int clientNum, char *command)
qboolean G_LuaHook_ConsoleCommand (char *command)
qboolean G_LuaHook_UpgradeSkill (int cno, skillType_t skill)
qboolean G_LuaHook_SetPlayerSkill (int cno, skillType_t skill)
void G_LuaHook_Print (printMessageType_t category, char *text)
qboolean G_LuaHook_Obituary (int victim, int killer, int meansOfDeath)
qboolean G_LuaHook_Damage (int target, int attacker, int damage, int dflags, meansOfDeath_t mod)
qboolean G_LuaHook_WeaponFire (int clientNum, weapon_t weapon, gentity_t **pFiredShot)
qboolean G_LuaHook_FixedMGFire (int clientNum)
qboolean G_LuaHook_MountedMGFire (int clientNum)
qboolean G_LuaHook_AAGunFire (int clientNum)
void G_LuaHook_SpawnEntitiesFromString ()
Variables
static luaPrintFunctions_t g_luaPrintFunctions []
Detailed Description
Lua API hooks / callbacks
Function Documentation
qboolean G_LuaHook_AAGunFire (int clientNum)
Definition at line 3784 of file g_lua.c.
Referenced by aagun_fire().
void G_LuaHook_ClientBegin (int clientNum)
Definition at line 3237 of file g_lua.c.
Referenced by ClientBegin().
qboolean G_LuaHook_ClientCommand (int clientNum, char * command)
Definition at line 3342 of file g_lua.c.
Referenced by ClientCommand().
qboolean G_LuaHook_ClientConnect (int clientNum, qboolean firstTime, qboolean isBot, char * reason)
Definition at line 3158 of file g_lua.c.
Referenced by ClientConnect().
void G_LuaHook_ClientDisconnect (int clientNum)
Definition at line 3203 of file g_lua.c.
Referenced by ClientDisconnect().
void G_LuaHook_ClientSpawn (int clientNum, qboolean revived, qboolean teamChange, qboolean restoreHealth)
Definition at line 3305 of file g_lua.c.
Referenced by ClientSpawn().
void G_LuaHook_ClientUserinfoChanged (int clientNum)
Definition at line 3271 of file g_lua.c.
Referenced by ClientUserinfoChanged().
qboolean G_LuaHook_ConsoleCommand (char * command)
Definition at line 3388 of file g_lua.c.
Referenced by ConsoleCommand().
qboolean G_LuaHook_Damage (int target, int attacker, int damage, int dflags, meansOfDeath_t mod)
Definition at line 3614 of file g_lua.c.
Referenced by G_Damage().
qboolean G_LuaHook_FixedMGFire (int clientNum)
Definition at line 3706 of file g_lua.c.
Referenced by mg42_fire().
void G_LuaHook_InitGame (int levelTime, int randomSeed, int restart)
Definition at line 3054 of file g_lua.c.
Referenced by G_InitGame().
qboolean G_LuaHook_MountedMGFire (int clientNum)
Definition at line 3745 of file g_lua.c.
Referenced by mountedmg42_fire().
qboolean G_LuaHook_Obituary (int victim, int killer, int meansOfDeath)
Definition at line 3571 of file g_lua.c.
Referenced by player_die().
void G_LuaHook_Print (printMessageType_t category, char * text)
Definition at line 3532 of file g_lua.c.
Referenced by G_DPrintf(), G_Error(), and G_Printf().
void G_LuaHook_RunFrame (int levelTime)
Definition at line 3124 of file g_lua.c.
Referenced by G_RunFrame().
qboolean G_LuaHook_SetPlayerSkill (int cno, skillType_t skill)
Definition at line 3479 of file g_lua.c.
Referenced by G_SetPlayerSkill().
void G_LuaHook_ShutdownGame (int restart)
Definition at line 3090 of file g_lua.c.
Referenced by G_ShutdownGame().
void G_LuaHook_SpawnEntitiesFromString ()
Definition at line 3825 of file g_lua.c.
Referenced by G_SpawnEntitiesFromString().
qboolean G_LuaHook_UpgradeSkill (int cno, skillType_t skill)
Definition at line 3433 of file g_lua.c.
Referenced by G_UpgradeSkill().
qboolean G_LuaHook_WeaponFire (int clientNum, weapon_t weapon, gentity_t ** pFiredShot)
Definition at line 3658 of file g_lua.c.
Referenced by FireWeapon().
Variable Documentation
luaPrintFunctions_t g_luaPrintFunctions[] static
Initial value:
=
{
    { GPRINT_TEXT,      "et_Print"  },
    { GPRINT_DEVELOPER, "et_DPrint" },
    { GPRINT_ERROR,     "et_Error"  }
}
Definition at line 3521 of file g_lua.c.