ET: Legacy: src/irc/htable.c File Reference
htable.c File Reference
#include "htable.h"
Data Structures
struct listhead_t
"List heads" - used to store various lists
struct tentry_t
Table entry - used to store actual items.
struct hashtable_s
Main hash table structure.
Macros
#define RESET_LIST(LPTR) ((LPTR)->previous = (LPTR)->next = (LPTR))
Resets a list head.
#define TABLE_START(TABLE) ((struct listhead_t *)(((char *)(TABLE)) + sizeof(struct hashtable_s)))
Macro that finds the first list head after a table's main structure.
Typedefs
typedef unsigned int(* getkey_t) (const char *key)
typedef char *(* keyfromentry_t) (struct tentry_t *entry, size_t key_offset)
typedef int(* comparekey_t) (const char *k1, const char *k2)
Functions
static qboolean _HT_IsPrime (size_t n)
Checks if a size is a prime number.
static size_t _HT_NextPrime (size_t n)
Finds the next higher prime number.
static unsigned int _HT_GetCIKey (const char *key)
Computes a string's hash key (case insensitive)
static unsigned int _HT_GetKey (const char *key)
Computes a string's hash key (case sensitive)
static char * _HT_KeyFromEntryII (struct tentry_t *entry, size_t key_offset)
Returns a table entry's key (in-table items, fixed size key)
static char * _HT_KeyFromEntryIP (struct tentry_t *entry, size_t key_offset)
Returns a table entry's key (in-table items, pointer key)
static char * _HT_KeyFromEntryPI (struct tentry_t *entry, size_t key_offset)
Returns a table entry's key (external items, fixed size key)
static char * _HT_KeyFromEntryPP (struct tentry_t *entry, size_t key_offset)
Returns a table entry's key (external items, pointer key)
static struct tentry_t * _HT_CreateEntry (hashtable_t table, unsigned int hash, struct listhead_t *list_entry, const char *key)
Allocate and initialise a table entry.
static void _HT_InsertInGlobalList (hashtable_t table, struct tentry_t *t_entry, const char *key)
Insert a table entry into a table's global list.
hashtable_t HT_Create (size_t size, unsigned int flags, size_t item_size, size_t key_offset, size_t key_length)
Hash table creation.
void HT_Destroy (hashtable_t table)
Hash table destruction.
void * HT_GetItem (hashtable_t table, const char *key, qboolean *created)
Gets an item from the table.
void * HT_PutItem (hashtable_t table, void *item, qboolean allow_replacement)
Stores an item into the table.
qboolean HT_DeleteItem (hashtable_t table, const char *key, void **found)
Deletes an item from the table.
void HT_Apply (hashtable_t table, ht_apply_funct function, void *data)
Applies a function to all items in the table.
Detailed Description
Note
This is FEATURE_IRC_CLIENT and FEATURE_IRC_SERVER only
Definition in file htable.c.
Macro Definition Documentation
#define RESET_LIST (LPTR) ((LPTR)->previous = (LPTR)->next = (LPTR))
Resets a list head.
Definition at line 58 of file htable.c.
Referenced by HT_Create().
#define TABLE_START (TABLE) ((struct listhead_t *)(((char *)(TABLE)) + sizeof(struct hashtable_s)))
Macro that finds the first list head after a table's main structure.
Definition at line 119 of file htable.c.
Referenced by HT_Create(), HT_DeleteItem(), HT_GetItem(), and HT_PutItem().
Typedef Documentation
typedef int(* comparekey_t) (const char *k1, const char *k2)
Definition at line 83 of file htable.c.
typedef unsigned int(* getkey_t) (const char *key)
Definition at line 81 of file htable.c.
typedef char*(* keyfromentry_t) (struct tentry_t *entry, size_t key_offset)
Definition at line 82 of file htable.c.
Function Documentation
static struct tentry_t * _HT_CreateEntry (hashtable_t table, unsigned int hash, struct listhead_t * list_entry, const char * key) static
Allocate and initialise a table entry.
_HT_CreateEntry
Parameters
[in] table
[in] hash
[in,out] list_entry
[in] key
Returns
Definition at line 773 of file htable.c.
Referenced by HT_GetItem(), and HT_PutItem().
static unsigned int _HT_GetCIKey (const char * key) static
Computes a string's hash key (case insensitive)
_HT_GetCIKey
Parameters
[in] key
Returns
Definition at line 656 of file htable.c.
Referenced by HT_Create().
static unsigned int _HT_GetKey (const char * key) static
Computes a string's hash key (case sensitive)
_HT_GetKey
Parameters
[in] key
Returns
Definition at line 681 of file htable.c.
Referenced by HT_Create().
static void _HT_InsertInGlobalList (hashtable_t table, struct tentry_t * t_entry, const char * key) static
Insert a table entry into a table's global list.
_HT_InsertInGlobalList
Parameters
[in] table
[in,out] t_entry
[in] key
Definition at line 803 of file htable.c.
Referenced by _HT_CreateEntry().
static qboolean _HT_IsPrime (size_t n) static
Checks if a size is a prime number.
_HT_IsPrime
Parameters
[in] n
Returns
Definition at line 608 of file htable.c.
Referenced by _HT_NextPrime().
static char * _HT_KeyFromEntryII (struct tentry_t * entry, size_t key_offset) static
Returns a table entry's key (in-table items, fixed size key)
_HT_KeyFromEntryII
Parameters
[in] entry
[in] key_offset
Returns
Definition at line 711 of file htable.c.
Referenced by HT_Create().
static char * _HT_KeyFromEntryIP (struct tentry_t * entry, size_t key_offset) static
Returns a table entry's key (in-table items, pointer key)
_HT_KeyFromEntryIP
Parameters
[in] entry
[in] key_offset
Returns
Definition at line 725 of file htable.c.
Referenced by HT_Create().
static char * _HT_KeyFromEntryPI (struct tentry_t * entry, size_t key_offset) static
Returns a table entry's key (external items, fixed size key)
_HT_KeyFromEntryPI
Parameters
[in] entry
[in] key_offset
Returns
Definition at line 739 of file htable.c.
Referenced by HT_Create().
static char * _HT_KeyFromEntryPP (struct tentry_t * entry, size_t key_offset) static
Returns a table entry's key (external items, pointer key)
_HT_KeyFromEntryPP
Parameters
[in] entry
[in] key_offset
Returns
Definition at line 753 of file htable.c.
Referenced by HT_Create().
static size_t _HT_NextPrime (size_t n) static
Finds the next higher prime number.
_HT_NextPrime
Parameters
[in] n
Returns
Definition at line 639 of file htable.c.
Referenced by HT_Create().
void HT_Apply (hashtable_t table, ht_apply_funct function, void * data)
Applies a function to all items in the table.
Parameters
[in] table The hash table onto which the function is to be applied
[in] function Pointer to the function to apply
[in] data Extra data to pass as the function's second parameter
Note
The order in which the function is applied is either the insertion order or, if the table has HT_FLAG_SORTED set, the increasing key order.
The function should return false if processing is to stop.
Definition at line 571 of file htable.c.
hashtable_t HT_Create (size_t size, unsigned int flags, size_t item_size, size_t key_offset, size_t key_length)
Hash table creation.
Parameters
[in] size Size of the table (will be rounded up to the next prime number)
[in] flags Combination of HT_FLAG_* for the table
[in] item_size Size of the table's items
[in] key_offset Offset of the key in the table's items
[in] key_length Maximal length of the key in the table; if 0, the key will be accessed as a pointer instead of an array
Definition at line 171 of file htable.c.
Referenced by IRC_InitHandlers().
qboolean HT_DeleteItem (hashtable_t table, const char * key, void ** found)
Deletes an item from the table.
Parameters
[in] table The hash table from which an item is to be deleted
[in] key The key to delete
[out] found A pointer to a pointer which will be set to the deleted item's value; may be NULL
Returns
true if an item was deleted, false otherwise
Note
If the items are stored in-table or are freed automatically, then the "found" parameter will always be ignored.
Definition at line 475 of file htable.c.
void HT_Destroy (hashtable_t table)
Hash table destruction.
Parameters
[in] table
Definition at line 224 of file htable.c.
Referenced by IRC_FreeHandlers().
void* HT_GetItem (hashtable_t table, const char * key, qboolean * created)
Gets an item from the table.
Parameters
[in] table The hash table to access
[in] key The key to look up
[out] created Pointer to a boolean which will be set to true if the item was created; if NULL, no creation will take place
Definition at line 262 of file htable.c.
Referenced by IRC_AddCTCPHandler(), IRC_AddHandler(), IRC_ExecuteCTCPHandler(), and IRC_ExecuteHandler().
void* HT_PutItem (hashtable_t table, void * item, qboolean allow_replacement)
Stores an item into the table.
Parameters
[in] table The hash table to add an item to
[in] item The item to add to the table
[in] allow_replacement whether replacement of a previous item is allowed
Returns
The item that matched the specified key, or NULL if no item using the same key existed
Note
Replacement behaviour varies greatly depending on the flags. If the items are stored in-table, or if the table must free the memory they use, a replacement will still return NULL, as the memory will have been freed or reused.
Todo:
: never used
Definition at line 357 of file htable.c.