ET: Legacy: src/qcommon/i18n_main.cpp File Reference
i18n_main.cpp File Reference
Glue for findlocale and tinygettext.
#include "q_shared.h"
#include "qcommon.h"
#include "i18n_findlocale.h"
#include <iostream>
#include <string.h>
#include <stdlib.h>
#include <map>
#include "../tinygettext/tinygettext/po_parser.hpp"
#include "../tinygettext/tinygettext/tinygettext.hpp"
#include "../tinygettext/tinygettext/log.hpp"
#include "../tinygettext/tinygettext/file_system.hpp"
Data Structures
class QInputbuf
std::streambuf based class that uses the engine's File I/O functions for input
class QIstream
Simple istream based class that takes ownership of the streambuf.
class QFileSystem
Class used by tinygettext to read files and directories. Uses the engine's File I/O functions for this purpose.
Functions
static void TranslationMissing (const char *msgid)
A dumb function which saves missing strings for the current language and mod passed to it.
static void Tinygettext_Error (const std::string &str)
Tinygettext_Error.
static void Tinygettext_Warning (const std::string &str)
Tinygettext_Warning.
static void Tinygettext_Info (const std::string &str)
Tinygettext_Info.
void I18N_Init (void)
Attempts to detect the system language unless cl_lang was already set. Then loads the PO file containing translated strings.
void I18N_SetLanguage (const char *language)
Loads a localization file.
static const char * _I18N_Translate (const char *msgid, tinygettext::DictionaryManager &dict)
Translates a string using the specified dictionary.
const char * I18N_Translate (const char *msgid)
I18N_Translate.
const char * I18N_TranslateMod (const char *msgid)
I18N_TranslateMod.
Variables
tinygettext::DictionaryManager dictionary
tinygettext::DictionaryManager dictionary_mod
cvar_t * cl_lang
cvar_t * cl_langDebug
static char cl_lang_last [3]
qboolean doTranslate = qfalse
qboolean doTranslateMod = qtrue
std::map< std::string, std::string > strings
Detailed Description
Glue for findlocale and tinygettext.
Definition in file i18n_main.cpp.
Function Documentation
static const char* _I18N_Translate (const char * msgid, tinygettext::DictionaryManager & dict) static
Translates a string using the specified dictionary.
Localized strings are stored in a map container as tinygettext would attempt to read them from the po file at each call and would endlessly spam the console with warnings if the requested translation did not exist.
Parameters
[in] msgid original string in English
[in] dict dictionary to use (client / mod)
Returns
translated string or English text if dictionary was not found
Definition at line 301 of file i18n_main.cpp.
Referenced by I18N_Translate(), and I18N_TranslateMod().
void I18N_Init (void)
Attempts to detect the system language unless cl_lang was already set. Then loads the PO file containing translated strings.
Definition at line 204 of file i18n_main.cpp.
Referenced by CL_Init(), and CL_Vid_Restart_f().
void I18N_SetLanguage (const char * language)
Loads a localization file.
Parameters
[in] language
Todo:
: check if there is a localization file available for the selected language
Definition at line 268 of file i18n_main.cpp.
Referenced by _I18N_Translate(), and I18N_Init().
const char* I18N_Translate (const char * msgid)
I18N_Translate.
Parameters
[in] msgid
Returns
Definition at line 335 of file i18n_main.cpp.
const char* I18N_TranslateMod (const char * msgid)
I18N_TranslateMod.
Parameters
[in] msgid
Returns
Definition at line 345 of file i18n_main.cpp.
static void Tinygettext_Error (const std::string & str) static
Tinygettext_Error.
Logging functions which override the default ones from Tinygettext
Parameters
[in] str
Definition at line 383 of file i18n_main.cpp.
Referenced by I18N_Init().
static void Tinygettext_Info (const std::string & str) static
Tinygettext_Info.
Parameters
[in] str
Definition at line 404 of file i18n_main.cpp.
Referenced by I18N_Init().
static void Tinygettext_Warning (const std::string & str) static
Tinygettext_Warning.
Parameters
[in] str
Definition at line 392 of file i18n_main.cpp.
Referenced by I18N_Init().
static void TranslationMissing (const char * msgid) static
A dumb function which saves missing strings for the current language and mod passed to it.
Parameters
[in] msgid original text
Definition at line 365 of file i18n_main.cpp.
Referenced by _I18N_Translate().
Variable Documentation
cvar_t* cl_lang
Definition at line 63 of file i18n_main.cpp.
Referenced by Script_ConditionalScript(), and UI_RunMenuScript().
char cl_lang_last[3] static
Definition at line 65 of file i18n_main.cpp.
Referenced by _I18N_Translate(), and I18N_SetLanguage().
cvar_t* cl_langDebug
Definition at line 64 of file i18n_main.cpp.
tinygettext::DictionaryManager dictionary
Definition at line 60 of file i18n_main.cpp.
Referenced by I18N_Init(), I18N_SetLanguage(), and I18N_Translate().
tinygettext::DictionaryManager dictionary_mod
Definition at line 61 of file i18n_main.cpp.
Referenced by I18N_Init(), I18N_SetLanguage(), and I18N_TranslateMod().
qboolean doTranslate = qfalse
Definition at line 67 of file i18n_main.cpp.
Referenced by _I18N_Translate(), and I18N_SetLanguage().
qboolean doTranslateMod = qtrue
Definition at line 68 of file i18n_main.cpp.
Referenced by FS_Startup(), and I18N_TranslateMod().
std::map<std::string, std::string> strings
Definition at line 70 of file i18n_main.cpp.
Referenced by _I18N_Translate(), CG_FireteamCheckExecKey(), CG_Fireteams_MenuText_Draw(), and I18N_SetLanguage().