ET: Legacy: src/qcommon/i18n_findlocale.c File Reference
i18n_findlocale.c File Reference
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "i18n_findlocale.h"
Functions
static int is_lcchar (const int c)
is_lcchar
static void lang_country_variant_from_envstring (const char *str, char **lang, char **country, char **variant)
lang_country_variant_from_envstring
static int accumulate_locstring (const char *str, FL_Locale *l)
accumulate_locstring
static int accumulate_env (const char *name, FL_Locale *l)
accumulate_env
static void canonise_fl (FL_Locale *l)
canonise_fl
FL_Success FL_FindLocale (FL_Locale **locale)
FL_FindLocale.
void FL_FreeLocale (FL_Locale **locale)
FL_FreeLocale.
Function Documentation
static int accumulate_env (const char * name, FL_Locale * l) static
accumulate_env
Parameters
[in] name
[out] l
Returns
Definition at line 153 of file i18n_findlocale.c.
Referenced by FL_FindLocale().
static int accumulate_locstring (const char * str, FL_Locale * l) static
accumulate_locstring
Parameters
[in] str
[out] l
Returns
Definition at line 123 of file i18n_findlocale.c.
Referenced by accumulate_env(), canonise_fl(), and FL_FindLocale().
static void canonise_fl (FL_Locale * l) static
canonise_fl
Parameters
[in,out] l
Definition at line 176 of file i18n_findlocale.c.
Referenced by FL_FindLocale().
FL_Success FL_FindLocale (FL_Locale ** locale)
FL_FindLocale.
Parameters
[out] locale
Returns
Definition at line 496 of file i18n_findlocale.c.
Referenced by I18N_Init().
void FL_FreeLocale (FL_Locale ** locale)
FL_FreeLocale.
This should be used to free the struct written by FL_FindLocale.
Parameters
[in,out] locale
Definition at line 564 of file i18n_findlocale.c.
Referenced by I18N_Init().
static int is_lcchar (const int c) static
is_lcchar
Parameters
[in] c
Returns
Definition at line 17 of file i18n_findlocale.c.
Referenced by lang_country_variant_from_envstring().
static void lang_country_variant_from_envstring (const char * str, char ** lang, char ** country, char ** variant) static
lang_country_variant_from_envstring
Parameters
[in] str
[out] lang
[out] country
[out] variant
Definition at line 29 of file i18n_findlocale.c.
Referenced by accumulate_locstring().