ET: Legacy: src/irc/irc_client.h File Reference
irc_client.h File Reference
Macros
#define IRCM_AUTO_CONNECT 1
#define IRCM_AUTO_OVERRIDE_NICKNAME 2
#define IRCM_MUTE_CHANNEL 4
#define IRCM_CHANNEL_TO_CHAT 8
dedicated only
Functions
void IRC_Init (void)
IRC_Init.
void IRC_Connect (void)
IRC_Connect.
void IRC_InitiateShutdown (void)
IRC_InitiateShutdown.
void IRC_WaitShutdown (void)
IRC_WaitShutdown.
void IRC_Say (void)
Sends an IRC message (console command).
qboolean IRC_IsConnected (void)
IRC_IsConnected.
qboolean IRC_IsRunning (void)
IRC_IsRunning.
Variables
cvar_t * irc_mode
cvar_t * irc_server
cvar_t * irc_channel
cvar_t * irc_port
cvar_t * irc_nickname
cvar_t * irc_kick_rejoin
cvar_t * irc_reconnect_delay
Detailed Description
Note
This is FEATURE_IRC_CLIENT and FEATURE_IRC_SERVER only
Definition in file irc_client.h.
Macro Definition Documentation
#define IRCM_AUTO_CONNECT 1
Definition at line 51 of file irc_client.h.
Referenced by CL_Connect_f().
#define IRCM_AUTO_OVERRIDE_NICKNAME 2
Definition at line 52 of file irc_client.h.
Referenced by IRC_InitialiseUser().
#define IRCM_CHANNEL_TO_CHAT 8
dedicated only
Definition at line 54 of file irc_client.h.
Referenced by IRC_Display().
#define IRCM_MUTE_CHANNEL 4
Definition at line 53 of file irc_client.h.
Referenced by IRC_Display().
Function Documentation
void IRC_Connect (void)
IRC_Connect.
Definition at line 2490 of file irc_client.c.
Referenced by CL_Connect_f(), CL_Init(), and SV_AddOperatorCommands().
void IRC_Init (void)
IRC_Init.
Definition at line 2505 of file irc_client.c.
Referenced by CL_Init(), and SV_Init().
void IRC_InitiateShutdown (void)
IRC_InitiateShutdown.
Definition at line 2519 of file irc_client.c.
Referenced by CL_Init(), CL_Shutdown(), SV_AddOperatorCommands(), and SV_Shutdown().
qboolean IRC_IsConnected (void)
IRC_IsConnected.
Returns
Definition at line 2536 of file irc_client.c.
qboolean IRC_IsRunning (void)
IRC_IsRunning.
Returns
Definition at line 2546 of file irc_client.c.
void IRC_Say (void)
Sends an IRC message (console command).
Definition at line 1879 of file irc_client.c.
Referenced by CL_Init(), and SV_AddOperatorCommands().
void IRC_WaitShutdown (void)
IRC_WaitShutdown.
Definition at line 2527 of file irc_client.c.
Referenced by CL_Shutdown(), and SV_Shutdown().
Variable Documentation
cvar_t* irc_channel
Definition at line 45 of file irc_client.h.
Referenced by IRC_Init(), IRC_JoinChannel(), IRC_ProcessSendQueue(), and IRCH_PrivMsg().
cvar_t* irc_kick_rejoin
Definition at line 48 of file irc_client.h.
Referenced by IRC_Init(), and IRCH_Kick().
cvar_t* irc_mode
Definition at line 43 of file irc_client.h.
Referenced by CL_Connect_f(), IRC_Display(), IRC_Init(), and IRC_InitialiseUser().
cvar_t* irc_nickname
Definition at line 47 of file irc_client.h.
Referenced by IRC_Init(), and IRC_InitialiseUser().
cvar_t* irc_port
Definition at line 46 of file irc_client.h.
Referenced by IRC_AttemptConnection(), and IRC_Init().
cvar_t* irc_reconnect_delay
Definition at line 49 of file irc_client.h.
Referenced by IRC_Init(), IRC_InitialConnect(), and IRC_Reconnect().
cvar_t* irc_server
Definition at line 44 of file irc_client.h.
Referenced by IRC_AttemptConnection(), and IRC_Init().