ET: Legacy: src/client/keys.h File Reference
keys.h File Reference
#include "../ui/keycodes.h"
Data Structures
struct qkey_t
Macros
#define COMMAND_HISTORY 32
Functions
void Field_KeyDownEvent (field_t *edit, int key)
Performs the basic line editing functions for the console, in-game talk, and menu fields.
void Field_CharEvent (field_t *edit, int ch)
Field_CharEvent.
void Field_Draw (field_t *edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
Field_Draw.
void Field_BigDraw (field_t *edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
Field_BigDraw.
void Key_WriteBindings (fileHandle_t f)
Writes lines containing "bind key value".
void Key_SetBinding (int keynum, const char *binding)
Key_SetBinding.
void Key_GetBindingByString (const char *binding, int *key1, int *key2)
Key_GetBindingByString.
char * Key_GetBinding (int keynum)
Key_GetBinding.
qboolean Key_IsDown (int keynum)
Key_IsDown.
qboolean Key_GetOverstrikeMode (void)
Key_GetOverstrikeMode.
void Key_SetOverstrikeMode (qboolean state)
Key_SetOverstrikeMode.
void Key_ClearStates (void)
Key_ClearStates.
int Key_GetKey (const char *binding)
Key_GetKey.
Variables
qboolean key_overstrikeMode
qkey_t keys [MAX_KEYS]
field_t historyEditLines [COMMAND_HISTORY]
field_t g_consoleField
int anykeydown
Macro Definition Documentation
#define COMMAND_HISTORY 32
Definition at line 62 of file keys.h.
Referenced by Con_Init(), and Console_Key().
Function Documentation
void Field_BigDraw (field_t * edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
Field_BigDraw.
Parameters
[in] edit
[in] x
[in] y
[in] width
[in] showCursor
[in] noColorEscape
Note
Unused
Definition at line 370 of file cl_keys.c.
void Field_CharEvent (field_t * edit, int ch)
Field_CharEvent.
Parameters
[in,out] edit
[in] ch
Definition at line 492 of file cl_keys.c.
Referenced by CL_CharEvent(), and Field_Paste().
void Field_Draw (field_t * edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
Field_Draw.
Parameters
[in] edit
[in] x
[in] y
[in] width
[in] showCursor
[in] noColorEscape
Definition at line 354 of file cl_keys.c.
Referenced by Con_DrawInput().
void Field_KeyDownEvent (field_t * edit, int key)
Performs the basic line editing functions for the console, in-game talk, and menu fields.
Key events are used for non-printable characters, others are gotten from char events.
Parameters
[in,out] edit
[in] key
Definition at line 410 of file cl_keys.c.
Referenced by Console_Key().
void Key_ClearStates (void)
Key_ClearStates.
Note
for win32 dedicated
Definition at line 1583 of file cl_keys.c.
Referenced by CL_KeyEvent(), CL_UISystemCalls(), and IN_ProcessEvents().
char* Key_GetBinding (int keynum)
Key_GetBinding.
Parameters
[in] keynum
Returns
Definition at line 945 of file cl_keys.c.
Referenced by Key_GetBindingBuf().
void Key_GetBindingByString (const char * binding, int * key1, int * key2)
Key_GetBindingByString.
Parameters
[in] binding
[out] key1
[out] key2
Note
Binding MUST be lower case
Definition at line 963 of file cl_keys.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
int Key_GetKey (const char * binding)
Key_GetKey.
Parameters
[in] binding
Returns
Definition at line 993 of file cl_keys.c.
Referenced by CL_CgameSystemCalls().
qboolean Key_GetOverstrikeMode (void)
Key_GetOverstrikeMode.
Returns
Definition at line 774 of file cl_keys.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
qboolean Key_IsDown (int keynum)
Key_IsDown.
Parameters
[in] keynum
Returns
Definition at line 793 of file cl_keys.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void Key_SetBinding (int keynum, const char * binding)
Key_SetBinding.
Parameters
[in] keynum
[in] binding
Definition at line 911 of file cl_keys.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Key_Bind_f(), Key_Unbind_f(), and Key_Unbindall_f().
void Key_SetOverstrikeMode (qboolean state)
Key_SetOverstrikeMode.
Parameters
[in] state
Definition at line 783 of file cl_keys.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void Key_WriteBindings (fileHandle_t f)
Writes lines containing "bind key value".
Parameters
[in] f Writes lines containing "bind key value".
f - unused
Definition at line 1103 of file cl_keys.c.
Variable Documentation
int anykeydown
Definition at line 53 of file cl_keys.c.
Referenced by CL_CmdButtons(), CL_KeyEvent(), and Key_ClearStates().
field_t g_consoleField
Definition at line 49 of file cl_keys.c.
Referenced by CL_InitRenderer(), Con_Close(), Con_DrawInput(), Con_Init(), Con_ToggleConsole_f(), and Console_Key().
field_t historyEditLines[COMMAND_HISTORY]
Definition at line 43 of file cl_keys.c.
Referenced by Con_Init().
qboolean key_overstrikeMode
Definition at line 51 of file cl_keys.c.
Referenced by Field_CharEvent(), Field_KeyDownEvent(), Field_VariableSizeDraw(), Key_GetOverstrikeMode(), and Key_SetOverstrikeMode().
qkey_t keys[MAX_KEYS]
Definition at line 54 of file cl_keys.c.
Referenced by Con_ToggleConsole_f(), IN_InitKeyLockStates(), and IN_ProcessEvents().