ET: Legacy: src/botlib/l_precomp.h File Reference
l_precomp.h File Reference
Pre-compiler.
Data Structures
struct define_s
struct indent_s
struct source_s
Macros
#define MAX_PATH MAX_QPATH
#define DEFINE_FIXED 0x0001
#define BUILTIN_LINE 1
#define BUILTIN_FILE 2
#define BUILTIN_DATE 3
#define BUILTIN_TIME 4
#define BUILTIN_STDC 5
#define INDENT_IF 0x0001
#define INDENT_ELSE 0x0002
#define INDENT_ELIF 0x0004
#define INDENT_IFDEF 0x0008
#define INDENT_IFNDEF 0x0010
Typedefs
typedef struct define_s define_t
Macro definitions.
typedef struct indent_s indent_t
indents used for conditional compilation directives: #if, #else, #elif, #ifdef, #ifndef
typedef struct source_s source_t
Source File.
Functions
int PC_ReadToken (source_t *source, token_t *token)
Read a token from the source.
int PC_CheckTokenString (source_t *source, const char *string)
Ckeck if token is available.
void PC_UnreadToken (source_t *source, token_t *token)
Unread the given token.
int PC_ReadLine (source_t *source, token_t *token)
Reads a token from the current line, continues reading on the next Line only if a backslash '\' is encountered.
int PC_WhiteSpaceBeforeToken (token_t *token)
PC_WhiteSpaceBeforeToken.
int PC_AddGlobalDefine (const char *string)
Add a globals define that will be added to all opened sources.
void PC_RemoveAllGlobalDefines (void)
Remove all globals defines.
source_t * LoadSourceFile (const char *filename)
Load a source file.
void FreeSource (source_t *source)
Free the given source.
void QDECL SourceError (source_t *source, const char *str,...) __attribute__((format(printf
void QDECL void QDECL SourceWarning (source_t *source, const char *str,...) __attribute__((format(printf
void QDECL void QDECL int PC_LoadSourceHandle (const char *filename)
PC_LoadSourceHandle.
int PC_FreeSourceHandle (int handle)
PC_FreeSourceHandle.
int PC_ReadTokenHandle (int handle, struct pc_token_s *pc_token)
PC_ReadTokenHandle.
int PC_SourceFileAndLine (int handle, char *filename, int *line)
PC_SourceFileAndLine.
void PC_CheckOpenSourceHandles (void)
PC_CheckOpenSourceHandles.
void PC_UnreadLastTokenHandle (int handle)
PC_UnreadLastTokenHandle.
Detailed Description
Pre-compiler.
Definition in file l_precomp.h.
Macro Definition Documentation
#define BUILTIN_DATE 3
Definition at line 47 of file l_precomp.h.
Referenced by PC_ExpandBuiltinDefine().
#define BUILTIN_FILE 2
Definition at line 46 of file l_precomp.h.
Referenced by PC_ExpandBuiltinDefine().
#define BUILTIN_LINE 1
Definition at line 45 of file l_precomp.h.
Referenced by PC_ExpandBuiltinDefine().
#define BUILTIN_STDC 5
Definition at line 49 of file l_precomp.h.
Referenced by PC_ExpandBuiltinDefine().
#define BUILTIN_TIME 4
Definition at line 48 of file l_precomp.h.
Referenced by PC_ExpandBuiltinDefine().
#define DEFINE_FIXED 0x0001
Definition at line 43 of file l_precomp.h.
Referenced by PC_Directive_define(), and PC_Directive_undef().
#define INDENT_ELIF 0x0004
Definition at line 53 of file l_precomp.h.
Referenced by PC_Directive_elif().
#define INDENT_ELSE 0x0002
Definition at line 52 of file l_precomp.h.
Referenced by PC_Directive_elif(), and PC_Directive_else().
#define INDENT_IF 0x0001
Definition at line 51 of file l_precomp.h.
Referenced by PC_Directive_if().
#define INDENT_IFDEF 0x0008
Definition at line 54 of file l_precomp.h.
Referenced by PC_Directive_if_def(), and PC_Directive_ifdef().
#define INDENT_IFNDEF 0x0010
Definition at line 55 of file l_precomp.h.
Referenced by PC_Directive_ifndef().
#define MAX_PATH MAX_QPATH
Definition at line 40 of file l_precomp.h.
Referenced by Sys_DefaultHomePath().
Typedef Documentation
define_t
Macro definitions.
indent_t
indents used for conditional compilation directives: #if, #else, #elif, #ifdef, #ifndef
source_t
Source File.
Function Documentation
void FreeSource (source_t * source)
Free the given source.
Parameters
[in,out] source
Definition at line 3434 of file l_precomp.c.
Referenced by PC_FreeSourceHandle().
source_t* LoadSourceFile (const char * filename)
Load a source file.
Parameters
[in] filename
Returns
Definition at line 3359 of file l_precomp.c.
Referenced by PC_LoadSourceHandle().
int PC_AddGlobalDefine (const char * string)
Add a globals define that will be added to all opened sources.
Parameters
[in] string
Returns
Definition at line 1430 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_CheckOpenSourceHandles (void)
PC_CheckOpenSourceHandles.
Definition at line 3647 of file l_precomp.c.
Referenced by Export_BotLibShutdown().
int PC_CheckTokenString (source_t * source, const char * string)
Ckeck if token is available.
Parameters
[in] source
[in] string
Returns
true when the token is available
Definition at line 3226 of file l_precomp.c.
Referenced by PC_Directive_define().
int PC_FreeSourceHandle (int handle)
PC_FreeSourceHandle.
Parameters
[in] handle
Returns
Definition at line 3534 of file l_precomp.c.
Referenced by GetBotLibAPI().
void QDECL void QDECL int PC_LoadSourceHandle (const char * filename)
PC_LoadSourceHandle.
Parameters
[in] filename
Returns
Definition at line 3503 of file l_precomp.c.
Referenced by GetBotLibAPI().
int PC_ReadLine (source_t * source, token_t * token)
Reads a token from the current line, continues reading on the next Line only if a backslash '\' is encountered.
Parameters
[in] source
[in] token
Returns
Definition at line 1045 of file l_precomp.c.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_Directive_pragma(), PC_Directive_undef(), and PC_Evaluate().
int PC_ReadToken (source_t * source, token_t * token)
Read a token from the source.
Parameters
[in,out] source
[in] token
Returns
Definition at line 2990 of file l_precomp.c.
Referenced by PC_CheckTokenString(), PC_ReadToken(), and PC_ReadTokenHandle().
int PC_ReadTokenHandle (int handle, pc_token_t * pc_token)
PC_ReadTokenHandle.
Parameters
[in] handle
[in] pc_token
Returns
Definition at line 3556 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_RemoveAllGlobalDefines (void)
Remove all globals defines.
Definition at line 1467 of file l_precomp.c.
Referenced by Export_BotLibShutdown(), and GetBotLibAPI().
int PC_SourceFileAndLine (int handle, char * filename, int * line)
PC_SourceFileAndLine.
Parameters
[in] handle
[in] filename
[in] line
Returns
Definition at line 3610 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_UnreadLastTokenHandle (int handle)
PC_UnreadLastTokenHandle.
Parameters
[in] handle
Definition at line 3589 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_UnreadToken (source_t * source, token_t * token)
Unread the given token.
Parameters
[in] source
[in] token
Definition at line 3312 of file l_precomp.c.
Referenced by PC_ReadToken().
int PC_WhiteSpaceBeforeToken (token_t * token)
PC_WhiteSpaceBeforeToken.
Parameters
[in] token
Returns
True if there was a white space in front of the token
Definition at line 1073 of file l_precomp.c.
Referenced by PC_Directive_define().
void QDECL SourceError (source_t * source, const char * str, ...)
void QDECL void QDECL SourceWarning (source_t * source, const char * str, ...)