ET: Legacy: src/botlib/l_precomp.c File Reference
l_precomp.c File Reference
Pre-compiler.
#include "../qcommon/q_shared.h"
#include "botlib.h"
#include "be_interface.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
Data Structures
struct directive_s
struct operator_s
struct value_s
Macros
#define MAX_DEFINEPARMS 128
#define DEFINEHASHING 1
#define DEFINEHASHSIZE 1024
#define MAX_VALUES 64
#define MAX_OPERATORS 64
#define AllocValue(val)
#define FreeValue(val)
#define AllocOperator(op)
#define FreeOperator(op)
#define MAX_SOURCEFILES 64
Typedefs
typedef struct directive_s directive_t
typedef struct operator_s operator_t
typedef struct value_s value_t
Functions
void QDECL SourceError (source_t *source, const char *str,...)
Print a source error.
void QDECL SourceWarning (source_t *source, const char *str,...)
Print a source warning.
void PC_PushIndent (source_t *source, int type, int skip)
PC_PushIndent.
void PC_PopIndent (source_t *source, int *type, int *skip)
PC_PopIndent.
void PC_PushScript (source_t *source, script_t *script)
PC_PushScript.
token_t * PC_CopyToken (token_t *token)
PC_CopyToken.
void PC_FreeToken (token_t *token)
PC_FreeToken.
int PC_ReadSourceToken (source_t *source, token_t *token)
PC_ReadSourceToken.
int PC_UnreadSourceToken (source_t *source, token_t *token)
PC_UnreadSourceToken.
define_t * PC_FindHashedDefine (define_t **definehash, const char *name)
PC_FindHashedDefine.
int PC_ExpandDefineIntoSource (source_t *source, token_t *deftoken, define_t *define)
PC_ExpandDefineIntoSource.
int PC_ReadDefineParms (source_t *source, define_t *define, token_t **parms, int maxparms)
PC_ReadDefineParms.
int PC_StringizeTokens (token_t *tokens, token_t *token)
PC_StringizeTokens.
int PC_MergeTokens (token_t *t1, token_t *t2)
PC_MergeTokens.
int PC_NameHash (const char *name)
PC_NameHash.
void PC_AddDefineToHash (define_t *define, define_t **definehash)
PC_AddDefineToHash.
define_t * PC_FindDefine (define_t *defines, const char *name)
PC_FindDefine.
int PC_FindDefineParm (define_t *define, char *name)
PC_FindDefineParm.
void PC_FreeDefine (define_t *define)
PC_FreeDefine.
int PC_ExpandBuiltinDefine (source_t *source, token_t *deftoken, define_t *define, token_t **firsttoken, token_t **lasttoken)
PC_ExpandBuiltinDefine.
int PC_ExpandDefine (source_t *source, token_t *deftoken, define_t *define, token_t **firsttoken, token_t **lasttoken)
PC_ExpandDefine.
void PC_ConvertPath (char *path)
PC_ConvertPath.
int PC_Directive_include (source_t *source)
PC_Directive_include.
int PC_ReadLine (source_t *source, token_t *token)
Reads a token from the current line, continues reading on the next Line only if a backslash '\' is encountered.
int PC_WhiteSpaceBeforeToken (token_t *token)
PC_WhiteSpaceBeforeToken.
void PC_ClearTokenWhiteSpace (token_t *token)
PC_ClearTokenWhiteSpace.
int PC_Directive_undef (source_t *source)
PC_Directive_undef.
int PC_Directive_define (source_t *source)
PC_Directive_define.
define_t * PC_DefineFromString (const char *string)
PC_DefineFromString.
int PC_AddGlobalDefine (const char *string)
Add a globals define that will be added to all opened sources.
void PC_RemoveAllGlobalDefines (void)
Remove all globals defines.
define_t * PC_CopyDefine (source_t *source, define_t *define)
PC_CopyDefine.
void PC_AddGlobalDefinesToSource (source_t *source)
PC_AddGlobalDefinesToSource.
int PC_Directive_if_def (source_t *source, int type)
PC_Directive_if_def.
int PC_Directive_ifdef (source_t *source)
PC_Directive_ifdef.
int PC_Directive_ifndef (source_t *source)
PC_Directive_ifndef.
int PC_Directive_else (source_t *source)
PC_Directive_else.
int PC_Directive_endif (source_t *source)
PC_Directive_endif.
int PC_OperatorPriority (int op)
PC_OperatorPriority.
int PC_EvaluateTokens (source_t *source, token_t *tokens, signed long int *intvalue, double *floatvalue, int integer)
PC_EvaluateTokens.
int PC_Evaluate (source_t *source, signed long int *intvalue, double *floatvalue, int integer)
PC_Evaluate.
int PC_DollarEvaluate (source_t *source, signed long int *intvalue, double *floatvalue, int integer)
PC_DollarEvaluate.
int PC_Directive_elif (source_t *source)
PC_Directive_elif.
int PC_Directive_if (source_t *source)
PC_Directive_if.
int PC_Directive_line (source_t *source)
PC_Directive_line.
int PC_Directive_error (source_t *source)
PC_Directive_error.
int PC_Directive_pragma (source_t *source)
PC_Directive_pragma.
void UnreadSignToken (source_t *source)
UnreadSignToken.
int PC_Directive_eval (source_t *source)
PC_Directive_eval.
int PC_Directive_evalfloat (source_t *source)
PC_Directive_evalfloat.
int PC_ReadDirective (source_t *source)
PC_ReadDirective.
int PC_DollarDirective_evalint (source_t *source)
PC_DollarDirective_evalint.
int PC_DollarDirective_evalfloat (source_t *source)
PC_DollarDirective_evalfloat.
int PC_ReadDollarDirective (source_t *source)
PC_ReadDollarDirective.
int PC_ReadToken (source_t *source, token_t *token)
Read a token from the source.
int PC_CheckTokenString (source_t *source, const char *string)
Ckeck if token is available.
void PC_UnreadToken (source_t *source, token_t *token)
Unread the given token.
source_t * LoadSourceFile (const char *filename)
Load a source file.
void FreeSource (source_t *source)
Free the given source.
int PC_LoadSourceHandle (const char *filename)
PC_LoadSourceHandle.
int PC_FreeSourceHandle (int handle)
PC_FreeSourceHandle.
int PC_ReadTokenHandle (int handle, pc_token_t *pc_token)
PC_ReadTokenHandle.
void PC_UnreadLastTokenHandle (int handle)
PC_UnreadLastTokenHandle.
int PC_SourceFileAndLine (int handle, char *filename, int *line)
PC_SourceFileAndLine.
void PC_CheckOpenSourceHandles (void)
PC_CheckOpenSourceHandles.
Variables
int numtokens
define_t * globaldefines
directive_t directives [15]
directive_t dollardirectives [20]
source_t * sourceFiles [MAX_SOURCEFILES]
Detailed Description
Pre-compiler.
Definition in file l_precomp.c.
Macro Definition Documentation
#define AllocOperator (op)
Value:
if (numoperators >= MAX_OPERATORS) {                \
        SourceError(source, "out of operator space\n");   \
        error = 1;                                      \
        break;                                          \
    }                                                   \
    else { \
        op = &operator_heap[numoperators++]; }
Definition at line 1749 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
#define AllocValue (val)
Value:
if (numvalues >= MAX_VALUES) {                      \
        SourceError(source, "out of value space\n");      \
        error = 1;                                      \
        break;                                          \
    }                                                   \
    else { \
        val = &value_heap[numvalues++]; }
Definition at line 1739 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
#define DEFINEHASHING 1
Definition at line 49 of file l_precomp.c.
#define DEFINEHASHSIZE 1024
Definition at line 58 of file l_precomp.c.
Referenced by FreeSource(), LoadSourceFile(), PC_DefineFromString(), and PC_NameHash().
#define FreeOperator (op)
Definition at line 1757 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
#define FreeValue (val)
Definition at line 1747 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
#define MAX_DEFINEPARMS 128
Todo:
: PC_StringizeTokens ?!
Definition at line 47 of file l_precomp.c.
Referenced by PC_ExpandDefine().
#define MAX_OPERATORS 64
Definition at line 1738 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
#define MAX_SOURCEFILES 64
Definition at line 3494 of file l_precomp.c.
Referenced by PC_CheckOpenSourceHandles(), PC_FreeSourceHandle(), PC_LoadSourceHandle(), PC_ReadTokenHandle(), PC_SourceFileAndLine(), and PC_UnreadLastTokenHandle().
#define MAX_VALUES 64
Definition at line 1737 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
Typedef Documentation
typedef struct directive_s directive_t
typedef struct operator_s operator_t
typedef struct value_s value_t
Function Documentation
void FreeSource (source_t * source)
Free the given source.
Parameters
[in,out] source
Definition at line 3434 of file l_precomp.c.
Referenced by PC_FreeSourceHandle().
source_t* LoadSourceFile (const char * filename)
Load a source file.
Parameters
[in] filename
Returns
Definition at line 3359 of file l_precomp.c.
Referenced by PC_LoadSourceHandle().
void PC_AddDefineToHash (define_t * define, define_t ** definehash)
PC_AddDefineToHash.
Parameters
[in,out] define
[in,out] definehash
Definition at line 512 of file l_precomp.c.
Referenced by PC_AddGlobalDefinesToSource(), and PC_Directive_define().
int PC_AddGlobalDefine (const char * string)
Add a globals define that will be added to all opened sources.
Parameters
[in] string
Returns
Definition at line 1430 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_AddGlobalDefinesToSource (source_t * source)
PC_AddGlobalDefinesToSource.
Parameters
[in] source
Definition at line 1540 of file l_precomp.c.
Referenced by LoadSourceFile().
void PC_CheckOpenSourceHandles (void)
PC_CheckOpenSourceHandles.
Definition at line 3647 of file l_precomp.c.
Referenced by Export_BotLibShutdown().
int PC_CheckTokenString (source_t * source, const char * string)
Ckeck if token is available.
Parameters
[in] source
[in] string
Returns
true when the token is available
Definition at line 3226 of file l_precomp.c.
Referenced by PC_Directive_define().
void PC_ClearTokenWhiteSpace (token_t * token)
PC_ClearTokenWhiteSpace.
Parameters
[out] token
Definition at line 1082 of file l_precomp.c.
Referenced by PC_Directive_define().
void PC_ConvertPath (char * path)
PC_ConvertPath.
Parameters
[in] path
Definition at line 929 of file l_precomp.c.
Referenced by PC_Directive_include().
define_t* PC_CopyDefine (source_t * source, define_t * define)
PC_CopyDefine.
Parameters
source - unused
[in] define
Returns
Definition at line 1486 of file l_precomp.c.
Referenced by PC_AddGlobalDefinesToSource().
token_t* PC_CopyToken (token_t * token)
PC_CopyToken.
Parameters
[in] token
Returns
Definition at line 175 of file l_precomp.c.
Referenced by PC_CopyDefine(), PC_Directive_define(), PC_DollarEvaluate(), PC_Evaluate(), PC_ExpandBuiltinDefine(), PC_ExpandDefine(), PC_ReadDefineParms(), and PC_UnreadSourceToken().
define_t* PC_DefineFromString (const char * string)
PC_DefineFromString.
Parameters
[in] string
Returns
Definition at line 1342 of file l_precomp.c.
Referenced by PC_AddGlobalDefine().
int PC_Directive_define (source_t * source)
PC_Directive_define.
Parameters
[in] source
Returns
Definition at line 1177 of file l_precomp.c.
Referenced by PC_DefineFromString().
int PC_Directive_elif (source_t * source)
PC_Directive_elif.
Parameters
[in] source
Returns
Definition at line 2654 of file l_precomp.c.
int PC_Directive_else (source_t * source)
PC_Directive_else.
Parameters
[in] source
Returns
Definition at line 1614 of file l_precomp.c.
int PC_Directive_endif (source_t * source)
PC_Directive_endif.
Parameters
[in] source
Returns
Definition at line 1638 of file l_precomp.c.
int PC_Directive_error (source_t * source)
PC_Directive_error.
Parameters
[in] source
Returns
Definition at line 2709 of file l_precomp.c.
int PC_Directive_eval (source_t * source)
PC_Directive_eval.
Parameters
[in] source
Returns
Definition at line 2757 of file l_precomp.c.
int PC_Directive_evalfloat (source_t * source)
PC_Directive_evalfloat.
Parameters
[in] source
Returns
Definition at line 2787 of file l_precomp.c.
int PC_Directive_if (source_t * source)
PC_Directive_if.
Parameters
[in] source
Returns
Definition at line 2679 of file l_precomp.c.
int PC_Directive_if_def (source_t * source, int type)
PC_Directive_if_def.
Parameters
[in] source
[in] type
Returns
Definition at line 1562 of file l_precomp.c.
Referenced by PC_Directive_ifdef(), and PC_Directive_ifndef().
int PC_Directive_ifdef (source_t * source)
PC_Directive_ifdef.
Parameters
[in] source
Returns
Definition at line 1594 of file l_precomp.c.
int PC_Directive_ifndef (source_t * source)
PC_Directive_ifndef.
Parameters
[in] source
Returns
Definition at line 1604 of file l_precomp.c.
int PC_Directive_include (source_t * source)
PC_Directive_include.
Parameters
[in] source
Returns
Definition at line 962 of file l_precomp.c.
int PC_Directive_line (source_t * source)
PC_Directive_line.
Parameters
[in] source
Returns
Definition at line 2698 of file l_precomp.c.
int PC_Directive_pragma (source_t * source)
PC_Directive_pragma.
Parameters
[in] source
Returns
Definition at line 2724 of file l_precomp.c.
int PC_Directive_undef (source_t * source)
PC_Directive_undef.
Parameters
[in] source
Returns
Definition at line 1094 of file l_precomp.c.
Referenced by PC_Directive_define().
int PC_DollarDirective_evalfloat (source_t * source)
PC_DollarDirective_evalfloat.
Parameters
[in] source
Returns
Definition at line 2909 of file l_precomp.c.
int PC_DollarDirective_evalint (source_t * source)
PC_DollarDirective_evalint.
Parameters
[in] source
Returns
Definition at line 2875 of file l_precomp.c.
int PC_DollarEvaluate (source_t * source, signed long int * intvalue, double * floatvalue, int integer)
PC_DollarEvaluate.
Parameters
[in] source
[out] intvalue
[out] floatvalue
[in] integer
Returns
Definition at line 2500 of file l_precomp.c.
Referenced by PC_DollarDirective_evalfloat(), and PC_DollarDirective_evalint().
int PC_Evaluate (source_t * source, signed long int * intvalue, double * floatvalue, int integer)
PC_Evaluate.
Parameters
[in] source
[out] intvalue
[out] floatvalue
[in] integer
Returns
Definition at line 2361 of file l_precomp.c.
Referenced by PC_Directive_elif(), PC_Directive_eval(), PC_Directive_evalfloat(), and PC_Directive_if().
int PC_EvaluateTokens (source_t * source, token_t * tokens, signed long int * intvalue, double * floatvalue, int integer)
PC_EvaluateTokens.
Parameters
[in] source
[in] tokens
[out] intvalue
[out] floatvalue
[in] integer
Returns
Definition at line 1768 of file l_precomp.c.
Referenced by PC_DollarEvaluate(), and PC_Evaluate().
int PC_ExpandBuiltinDefine (source_t * source, token_t * deftoken, define_t * define, token_t ** firsttoken, token_t ** lasttoken)
PC_ExpandBuiltinDefine.
Parameters
[in] source
[in] deftoken
[in] define
[out] firsttoken
[out] lasttoken
Returns
Definition at line 662 of file l_precomp.c.
Referenced by PC_ExpandDefine().
int PC_ExpandDefine (source_t * source, token_t * deftoken, define_t * define, token_t ** firsttoken, token_t ** lasttoken)
PC_ExpandDefine.
Parameters
[in] source
[in] deftoken
[in] define
[out] firsttoken
[out] lasttoken
Returns
Definition at line 743 of file l_precomp.c.
Referenced by PC_ExpandDefineIntoSource().
int PC_ExpandDefineIntoSource (source_t * source, token_t * deftoken, define_t * define)
PC_ExpandDefineIntoSource.
Parameters
[in,out] source
[in] deftoken
[in] define
Returns
Definition at line 907 of file l_precomp.c.
Referenced by PC_DollarEvaluate(), PC_Evaluate(), PC_ReadDefineParms(), PC_ReadToken(), and PC_UnreadSourceToken().
define_t* PC_FindDefine (define_t * defines, const char * name)
PC_FindDefine.
Parameters
[in] defines
[in] name
Returns
Definition at line 550 of file l_precomp.c.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), and PC_ReadToken().
int PC_FindDefineParm (define_t * define, char * name)
PC_FindDefineParm.
Parameters
define
name
Returns
The number of the parm otherwise if no parm found with the given name -1 is returned
Definition at line 570 of file l_precomp.c.
Referenced by PC_Directive_define(), and PC_ExpandDefine().
define_t * PC_FindHashedDefine (define_t ** definehash, const char * name)
PC_FindHashedDefine.
Parameters
[in] definehash
[in] name
Returns
Definition at line 527 of file l_precomp.c.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ReadDefineParms(), PC_ReadToken(), and PC_UnreadSourceToken().
void PC_FreeDefine (define_t * define)
PC_FreeDefine.
Parameters
[in,out] define
Definition at line 591 of file l_precomp.c.
Referenced by FreeSource(), PC_DefineFromString(), PC_Directive_undef(), and PC_RemoveAllGlobalDefines().
int PC_FreeSourceHandle (int handle)
PC_FreeSourceHandle.
Parameters
[in] handle
Returns
Definition at line 3534 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_FreeToken (token_t * token)
PC_FreeToken.
Parameters
[in] token
Definition at line 196 of file l_precomp.c.
Referenced by FreeSource(), PC_DefineFromString(), PC_DollarEvaluate(), PC_Evaluate(), PC_ExpandDefine(), PC_FreeDefine(), and PC_ReadSourceToken().
int PC_LoadSourceHandle (const char * filename)
PC_LoadSourceHandle.
Parameters
[in] filename
Returns
Definition at line 3503 of file l_precomp.c.
Referenced by GetBotLibAPI().
int PC_MergeTokens (token_t * t1, token_t * t2)
PC_MergeTokens.
Parameters
[in,out] t1
[in] t2
Returns
Todo:
: merging of two number of the same sub type
Definition at line 424 of file l_precomp.c.
Referenced by PC_ExpandDefine().
int PC_NameHash (const char * name)
PC_NameHash.
Parameters
[in] name
Returns
Definition at line 492 of file l_precomp.c.
Referenced by PC_AddDefineToHash(), PC_Directive_undef(), and PC_FindHashedDefine().
int PC_OperatorPriority (int op)
PC_OperatorPriority.
Parameters
[in] op
Returns
Definition at line 1672 of file l_precomp.c.
Referenced by PC_EvaluateTokens().
void PC_PopIndent (source_t * source, int * type, int * skip)
PC_PopIndent.
Parameters
[in] source
[in] type
[in] skip
Definition at line 122 of file l_precomp.c.
Referenced by PC_Directive_elif(), PC_Directive_else(), PC_Directive_endif(), and PC_ReadSourceToken().
void PC_PushIndent (source_t * source, int type, int skip)
PC_PushIndent.
Parameters
[in] source
[in] type
[in] skip
Definition at line 103 of file l_precomp.c.
Referenced by PC_Directive_elif(), PC_Directive_else(), PC_Directive_if(), and PC_Directive_if_def().
void PC_PushScript (source_t * source, script_t * script)
PC_PushScript.
Parameters
[in,out] source
[in,out] script
Definition at line 153 of file l_precomp.c.
Referenced by PC_Directive_include().
int PC_ReadDefineParms (source_t * source, define_t * define, token_t ** parms, int maxparms)
PC_ReadDefineParms.
Parameters
[in] source
[in] define
[in,out] parms
[in] maxparms
Returns
Todo:
: lastcomma is never read !
Definition at line 279 of file l_precomp.c.
Referenced by PC_ExpandDefine().
int PC_ReadDirective (source_t * source)
PC_ReadDirective.
Parameters
[in] source
Returns
Definition at line 2835 of file l_precomp.c.
Referenced by PC_ReadToken().
int PC_ReadDollarDirective (source_t * source)
PC_ReadDollarDirective.
Parameters
[in] source
Returns
Definition at line 2949 of file l_precomp.c.
Referenced by PC_ReadToken().
int PC_ReadLine (source_t * source, token_t * token)
Reads a token from the current line, continues reading on the next Line only if a backslash '\' is encountered.
Parameters
[in] source
[in] token
Returns
Definition at line 1045 of file l_precomp.c.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_Directive_pragma(), PC_Directive_undef(), and PC_Evaluate().
int PC_ReadSourceToken (source_t * source, token_t * token)
PC_ReadSourceToken.
Parameters
[in,out] source
[in] token
Returns
Definition at line 208 of file l_precomp.c.
Referenced by PC_Directive_error(), PC_Directive_include(), PC_DollarEvaluate(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadLine(), and PC_ReadToken().
int PC_ReadToken (source_t * source, token_t * token)
Read a token from the source.
Parameters
[in,out] source
[in] token
Returns
Definition at line 2990 of file l_precomp.c.
Referenced by PC_CheckTokenString(), PC_ReadToken(), and PC_ReadTokenHandle().
int PC_ReadTokenHandle (int handle, pc_token_t * pc_token)
PC_ReadTokenHandle.
Parameters
[in] handle
[in] pc_token
Returns
Definition at line 3556 of file l_precomp.c.
Referenced by GetBotLibAPI().
void PC_RemoveAllGlobalDefines (void)
Remove all globals defines.
Definition at line 1467 of file l_precomp.c.
Referenced by Export_BotLibShutdown(), and GetBotLibAPI().
int PC_SourceFileAndLine (int handle, char * filename, int * line)
PC_SourceFileAndLine.
Parameters
[in] handle
[in] filename
[in] line
Returns
Definition at line 3610 of file l_precomp.c.
Referenced by GetBotLibAPI().
int PC_StringizeTokens (token_t * tokens, token_t * token)
PC_StringizeTokens.
Parameters
[in] tokens
[in,out] token
Returns
Definition at line 401 of file l_precomp.c.
Referenced by PC_ExpandDefine().
void PC_UnreadLastTokenHandle (int handle)
PC_UnreadLastTokenHandle.
Parameters
[in] handle
Definition at line 3589 of file l_precomp.c.
Referenced by GetBotLibAPI().
int PC_UnreadSourceToken (source_t * source, token_t * token)
PC_UnreadSourceToken.
Parameters
[in,out] source
[in] token
Returns
Definition at line 258 of file l_precomp.c.
Referenced by PC_CheckTokenString(), PC_Directive_define(), PC_Directive_eval(), PC_Directive_evalfloat(), PC_Directive_if_def(), PC_Directive_include(), PC_Directive_undef(), PC_DollarDirective_evalfloat(), PC_DollarDirective_evalint(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadLine(), PC_UnreadLastTokenHandle(), PC_UnreadToken(), and UnreadSignToken().
void PC_UnreadToken (source_t * source, token_t * token)
Unread the given token.
Parameters
[in] source
[in] token
Definition at line 3312 of file l_precomp.c.
Referenced by PC_ReadToken().
int PC_WhiteSpaceBeforeToken (token_t * token)
PC_WhiteSpaceBeforeToken.
Parameters
[in] token
Returns
True if there was a white space in front of the token
Definition at line 1073 of file l_precomp.c.
Referenced by PC_Directive_define().
void QDECL SourceError (source_t * source, const char * str, ...)
Print a source error.
Parameters
[in] source
[in] str
Definition at line 70 of file l_precomp.c.
Referenced by PC_Directive_define(), PC_Directive_elif(), PC_Directive_else(), PC_Directive_endif(), PC_Directive_error(), PC_Directive_if_def(), PC_Directive_include(), PC_Directive_line(), PC_Directive_undef(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ExpandDefine(), PC_PushScript(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), and PC_ReadToken().
void QDECL SourceWarning (source_t * source, const char * str, ...)
Print a source warning.
Parameters
[in] source
[in] str
Definition at line 86 of file l_precomp.c.
Referenced by PC_Directive_define(), PC_Directive_include(), PC_Directive_pragma(), PC_Directive_undef(), PC_ExpandDefine(), PC_ReadDefineParms(), and PC_ReadSourceToken().
void UnreadSignToken (source_t * source)
UnreadSignToken.
Parameters
[in] source
Definition at line 2738 of file l_precomp.c.
Referenced by PC_Directive_eval(), PC_Directive_evalfloat(), PC_DollarDirective_evalfloat(), and PC_DollarDirective_evalint().
Variable Documentation
directive_t directives[15]
Initial value:
=
{
    { "if",        PC_Directive_if        },
    { "ifdef",     PC_Directive_ifdef     },
    { "ifndef",    PC_Directive_ifndef    },
    { "elif",      PC_Directive_elif      },
    { "else",      PC_Directive_else      },
    { "endif",     PC_Directive_endif     },
    { "include",   PC_Directive_include   },
    { "define",    PC_Directive_define    },
    { "undef",     PC_Directive_undef     },
    { "line",      PC_Directive_line      },
    { "error",     PC_Directive_error     },
    { "pragma",    PC_Directive_pragma    },
    { "eval",      PC_Directive_eval      },
    { "evalfloat", PC_Directive_evalfloat },
    { NULL,        NULL                   }
}
Definition at line 2811 of file l_precomp.c.
directive_t dollardirectives[20]
Initial value:
=
{
    { "evalint",   PC_DollarDirective_evalint   },
    { "evalfloat", PC_DollarDirective_evalfloat },
    { NULL,        NULL                         }
}
Definition at line 2937 of file l_precomp.c.
define_t* globaldefines
Definition at line 63 of file l_precomp.c.
Referenced by BotLibSetup(), PC_AddGlobalDefine(), and PC_RemoveAllGlobalDefines().
int numtokens
Definition at line 60 of file l_precomp.c.
Referenced by PC_CopyToken(), and PC_FreeToken().
source_t* sourceFiles[MAX_SOURCEFILES]
Definition at line 3496 of file l_precomp.c.