ET: Legacy: src/botlib/l_script.c File Reference
l_script.c File Reference
Lexicographical parser.
#include "../qcommon/q_shared.h"
#include "botlib.h"
#include "be_interface.h"
#include "l_script.h"
#include "l_memory.h"
Macros
#define PUNCTABLE
Functions
void PS_CreatePunctuationTable (script_t *script, punctuation_t *punctuations)
PS_CreatePunctuationTable.
char * PunctuationFromNum (script_t *script, int num)
PunctuationFromNum.
void QDECL ScriptError (script_t *script, const char *str,...)
Print a script error with filename and line number.
void QDECL ScriptWarning (script_t *script, const char *str,...)
Print a script warning with filename and line number.
void SetScriptPunctuations (script_t *script, punctuation_t *p)
Set an array with punctuations, NULL restores default C/C++ set.
int PS_ReadWhiteSpace (script_t *script)
Reads spaces, tabs, C-like comments etc. When a newline character is found the scripts line counter is increased.
int PS_ReadEscapeCharacter (script_t *script, char *ch)
Reads an escape character.
int PS_ReadString (script_t *script, token_t *token, int quote)
Reads C-like string.
int PS_ReadName (script_t *script, token_t *token)
PS_ReadName.
void NumberValue (char *string, int subtype, unsigned long int *intvalue, long double *floatvalue)
NumberValue.
int PS_ReadNumber (script_t *script, token_t *token)
PS_ReadNumber.
int PS_ReadPunctuation (script_t *script, token_t *token)
PS_ReadPunctuation.
int PS_ReadPrimitive (script_t *script, token_t *token)
PS_ReadPrimitive.
int PS_ReadToken (script_t *script, token_t *token)
Read a token from the script.
void StripDoubleQuotes (char *string)
Remove any leading and trailing double quotes from the token.
int EndOfScript (script_t *script)
EndOfScript.
script_t * LoadScriptFile (const char *filename)
Load a script from the given file at the given offset with the given length.
script_t * LoadScriptMemory (const char *ptr, int length, const char *name)
Load a script from the given memory with the given length.
void FreeScript (script_t *script)
Free a script.
void PS_SetBaseFolder (const char *path)
Set the base folder to load files from.
Variables
punctuation_t default_punctuations []
char basefolder [MAX_QPATH]
Detailed Description
Lexicographical parser.
Definition in file l_script.c.
Macro Definition Documentation
#define PUNCTABLE
Definition at line 43 of file l_script.c.
Function Documentation
int EndOfScript (script_t * script)
EndOfScript.
Parameters
[in,out] script
Returns
Definition at line 1438 of file l_script.c.
Referenced by PC_ReadSourceToken().
void FreeScript (script_t * script)
Free a script.
Parameters
[in,out] script
Definition at line 1587 of file l_script.c.
Referenced by FreeSource(), PC_DefineFromString(), and PC_ReadSourceToken().
script_t* LoadScriptFile (const char * filename)
Load a script from the given file at the given offset with the given length.
Parameters
[in] filename
Returns
Definition at line 1495 of file l_script.c.
Referenced by LoadSourceFile(), and PC_Directive_include().
script_t* LoadScriptMemory (const char * ptr, int length, const char * name)
Load a script from the given memory with the given length.
Parameters
[in] ptr
[in] length
[in] name
Returns
Definition at line 1552 of file l_script.c.
Referenced by PC_DefineFromString().
void NumberValue (char * string, int subtype, unsigned long int * intvalue, long double * floatvalue)
NumberValue.
Parameters
[in,out] string
[in] subtype
[out] intvalue
[out] floatvalue
Definition at line 596 of file l_script.c.
Referenced by PS_ReadNumber().
void PS_CreatePunctuationTable (script_t * script, punctuation_t * punctuations)
PS_CreatePunctuationTable.
Parameters
[in,out] script
[in,out] punctuations
Definition at line 130 of file l_script.c.
Referenced by SetScriptPunctuations().
int PS_ReadEscapeCharacter (script_t * script, char * ch)
Reads an escape character.
Parameters
[in,out] script Script to read from
[out] ch Place to store the read escape character
Returns
Definition at line 359 of file l_script.c.
Referenced by PS_ReadString().
int PS_ReadName (script_t * script, token_t * token)
PS_ReadName.
Parameters
[in] script
[out] token
Returns
Definition at line 563 of file l_script.c.
Referenced by PS_ReadToken().
int PS_ReadNumber (script_t * script, token_t * token)
PS_ReadNumber.
Parameters
[in,out] script
[out] token
Returns
Definition at line 684 of file l_script.c.
Referenced by PS_ReadToken().
int PS_ReadPrimitive (script_t * script, token_t * token)
PS_ReadPrimitive.
Parameters
[out] script
[in,out] token
Returns
Definition at line 915 of file l_script.c.
Referenced by PS_ReadToken().
int PS_ReadPunctuation (script_t * script, token_t * token)
PS_ReadPunctuation.
Parameters
[in,out] script
[in,out] token
Returns
Definition at line 873 of file l_script.c.
Referenced by PS_ReadToken().
int PS_ReadString (script_t * script, token_t * token, int quote)
Reads C-like string.
Escape characters are interpretted. Quotes are included with the string. Reads two strings with a white space between them as one string.
Parameters
[in,out] script Script to read from
[in,out] token Buffer to store the string
[in] quote
Returns
qtrue when a string was read succesfully
Definition at line 464 of file l_script.c.
Referenced by PS_ReadToken().
int PS_ReadToken (script_t * script, token_t * token)
Read a token from the script.
Parameters
[in,out] script
[in,out] token
Returns
Definition at line 942 of file l_script.c.
Referenced by PC_ReadSourceToken().
int PS_ReadWhiteSpace (script_t * script)
Reads spaces, tabs, C-like comments etc. When a newline character is found the scripts line counter is increased.
Parameters
[in,out] script
Returns
Definition at line 277 of file l_script.c.
Referenced by PS_ReadString(), and PS_ReadToken().
void PS_SetBaseFolder (const char * path)
Set the base folder to load files from.
Parameters
[in] path
Definition at line 1602 of file l_script.c.
Referenced by PC_LoadSourceHandle().
char* PunctuationFromNum (script_t * script, int num)
PunctuationFromNum.
Parameters
[in] script
[in] num
Returns
A pointer to the punctuation with the given number
Definition at line 186 of file l_script.c.
Referenced by PC_EvaluateTokens().
void QDECL ScriptError (script_t * script, const char * str, ...)
Print a script error with filename and line number.
Parameters
[in] script
[in] str
Definition at line 205 of file l_script.c.
Referenced by PS_ReadEscapeCharacter(), PS_ReadName(), PS_ReadNumber(), PS_ReadPrimitive(), PS_ReadString(), and PS_ReadToken().
void QDECL ScriptWarning (script_t * script, const char * str, ...)
Print a script warning with filename and line number.
Parameters
[in] script
[in] str
Definition at line 226 of file l_script.c.
Referenced by PS_ReadEscapeCharacter().
void SetScriptPunctuations (script_t * script, punctuation_t * p)
Set an array with punctuations, NULL restores default C/C++ set.
Parameters
[in,out] script
[in] p
Definition at line 247 of file l_script.c.
Referenced by LoadScriptFile(), and LoadScriptMemory().
void StripDoubleQuotes (char * string)
Remove any leading and trailing double quotes from the token.
Parameters
[in,out] string
Definition at line 1304 of file l_script.c.
Referenced by PC_Directive_include(), and PC_ReadTokenHandle().
Variable Documentation
char basefolder[MAX_QPATH]
Definition at line 123 of file l_script.c.
Referenced by LoadScriptFile(), and PS_SetBaseFolder().
punctuation_t default_punctuations[]
Definition at line 46 of file l_script.c.
Referenced by SetScriptPunctuations().