ET: Legacy: src/rendererGLES/tr_surface.c File Reference
tr_surface.c File Reference
#include "tr_local.h"
Macros
#define NUM_BEAM_SEGS 6
Functions
void RB_CheckOverflow (int verts, int indexes)
RB_CheckOverflow.
void RB_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, byte *color, float s1, float t1, float s2, float t2)
RB_AddQuadStampExt.
void RB_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, byte *color)
RB_AddQuadStamp.
static void RB_SurfaceSplash (void)
RB_SurfaceSplash.
static void RB_SurfaceSprite (void)
RB_SurfaceSprite.
void RB_SurfacePolychain (srfPoly_t *p)
RB_SurfacePolychain.
void RB_SurfaceTriangles (srfTriangles_t *srf)
RB_SurfaceTriangles.
void RB_SurfaceFoliage (srfFoliage_t *srf)
RB_SurfaceFoliage.
void RB_SurfaceBeam (void)
RB_SurfaceBeam.
static void DoRailCore (const vec3_t start, const vec3_t end, const vec3_t up, float len, float spanWidth)
DoRailCore.
static void DoRailDiscs (int numSegs, const vec3_t start, const vec3_t dir, const vec3_t right, const vec3_t up)
DoRailDiscs.
void RB_SurfaceRailRings (void)
RB_SurfaceRailRings.
void RB_SurfaceRailCore (void)
RB_SurfaceRailCore.
void RB_SurfaceLightningBolt (void)
RB_SurfaceLightningBolt.
static void LerpMeshVertexes (md3Surface_t *surf, float backlerp)
LerpMeshVertexes.
void RB_SurfaceMesh (md3Surface_t *surface)
RB_SurfaceMesh.
void R_LatLongToNormal (vec3_t outNormal, short latLong)
R_LatLongToNormal.
static void LerpCMeshVertexes (mdcSurface_t *surf, float backlerp)
LerpCMeshVertexes.
void RB_SurfaceCMesh (mdcSurface_t *surface)
RB_SurfaceCMesh.
void RB_SurfaceFace (srfSurfaceFace_t *surf)
RB_SurfaceFace.
static float LodErrorForVolume (vec3_t local, float radius)
LodErrorForVolume.
void RB_SurfaceGrid (srfGridMesh_t *cv)
Just copy the grid of points and triangulate.
void RB_SurfaceAxis (void)
Draws x/y/z lines from the origin for orientation debugging.
void RB_SurfaceEntity (surfaceType_t *surfType)
Entities that have a single procedurally generated surface.
void RB_SurfaceBad (surfaceType_t *surfType)
RB_SurfaceBad.
void RB_SurfaceFlare (srfFlare_t *surf)
RB_SurfaceFlare.
void RB_SurfaceDisplayList (srfDisplayList_t *surf)
RB_SurfaceDisplayList.
void RB_SurfacePolyBuffer (srfPolyBuffer_t *surf)
RB_SurfacePolyBuffer.
void RB_SurfaceDecal (srfDecal_t *srf)
RB_SurfaceDecal.
void RB_SurfaceSkip (void *surf)
RB_SurfaceSkip.
Variables
void(* rb_surfaceTable [SF_NUM_SURFACE_TYPES])(void *)
Detailed Description
THIS ENTIRE FILE IS BACK END b ackEnd.currentEntity *will be valid. Tess_Begin has already been called for the surface's shader.
The modelview matrix will be set.
It is safe to actually issue drawing commands here if you don't want to use the shader system.
Definition in file tr_surface.c.
Macro Definition Documentation
#define NUM_BEAM_SEGS 6
Referenced by RB_SurfaceBeam().
Function Documentation
static void DoRailCore (const vec3_t start, const vec3_t end, const vec3_t up, float len, float spanWidth) static
DoRailCore.
Parameters
[in] start
[in] end
[in] up
[in] len
[in] spanWidth
Todo:
: use quad stamp?
Definition at line 665 of file tr_surface.c.
Referenced by RB_SurfaceLightningBolt(), and RB_SurfaceRailCore().
static void DoRailDiscs (int numSegs, const vec3_t start, const vec3_t dir, const vec3_t right, const vec3_t up) static
DoRailDiscs.
Parameters
[in] numSegs
[in] start
[in] dir
[in] right
[in] up
Definition at line 738 of file tr_surface.c.
Referenced by RB_SurfaceRailRings().
static void LerpCMeshVertexes (mdcSurface_t * surf, float backlerp) static
LerpCMeshVertexes.
Parameters
[in] surf
[in] backlerp
Definition at line 1101 of file tr_surface.c.
Referenced by RB_SurfaceCMesh().
static void LerpMeshVertexes (md3Surface_t * surf, float backlerp) static
LerpMeshVertexes.
Parameters
[in] surf
[in] backlerp
Definition at line 902 of file tr_surface.c.
Referenced by RB_SurfaceMesh().
static float LodErrorForVolume (vec3_t local, float radius) static
LodErrorForVolume.
Parameters
[in] local
[in] radius
Returns
Definition at line 1376 of file tr_surface.c.
Referenced by RB_SurfaceGrid().
void R_LatLongToNormal (vec3_t outNormal, short latLong)
R_LatLongToNormal.
Parameters
[in] outNormal
[in] latLong
Definition at line 1079 of file tr_surface.c.
void RB_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, byte * color)
RB_AddQuadStamp.
Parameters
[in] origin
[in] left
[in] up
[in] color
Definition at line 259 of file tr_surface.c.
Referenced by AutospriteDeform(), and RB_DrawSun().
void RB_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, byte * color, float s1, float t1, float s2, float t2)
RB_AddQuadStampExt.
Parameters
[in] origin
[in] left
[in] up
[in] color
[in] s1
[in] t1
[in] s2
[in] t2
Definition at line 185 of file tr_surface.c.
Referenced by DeformText().
void RB_CheckOverflow (int verts, int indexes)
RB_CheckOverflow.
Parameters
[in] verts
[in] indexes
Definition at line 51 of file tr_surface.c.
Referenced by RB_MDM_SurfaceAnim(), and RB_SurfaceAnim().
void RB_SurfaceAxis (void)
Draws x/y/z lines from the origin for orientation debugging.
Definition at line 1582 of file tr_surface.c.
void RB_SurfaceBad (surfaceType_t * surfType)
RB_SurfaceBad.
Parameters
surfType - unused
Todo:
better impl ?
Definition at line 1670 of file tr_surface.c.
void RB_SurfaceBeam (void)
RB_SurfaceBeam.
Definition at line 583 of file tr_surface.c.
void RB_SurfaceCMesh (mdcSurface_t * surface)
RB_SurfaceCMesh.
Parameters
[in] surface
Todo:
: fill in lightmapST for completeness?
Definition at line 1260 of file tr_surface.c.
void RB_SurfaceDecal (srfDecal_t * srf)
RB_SurfaceDecal.
Parameters
[in] srf
Definition at line 1793 of file tr_surface.c.
void RB_SurfaceDisplayList (srfDisplayList_t * surf)
RB_SurfaceDisplayList.
Parameters
[in] surf
Definition at line 1752 of file tr_surface.c.
void RB_SurfaceEntity (surfaceType_t * surfType)
Entities that have a single procedurally generated surface.
Parameters
surfType - unused
Definition at line 1636 of file tr_surface.c.
void RB_SurfaceFace (srfSurfaceFace_t * surf)
RB_SurfaceFace.
Parameters
[in] surf
Definition at line 1319 of file tr_surface.c.
void RB_SurfaceFlare (srfFlare_t * surf)
RB_SurfaceFlare.
Parameters
[in] surf
Definition at line 1725 of file tr_surface.c.
void RB_SurfaceFoliage (srfFoliage_t * srf)
RB_SurfaceFoliage.
Parameters
[in] srf
Definition at line 434 of file tr_surface.c.
void RB_SurfaceGrid (srfGridMesh_t * cv)
Just copy the grid of points and triangulate.
Parameters
[in] cv
Definition at line 1414 of file tr_surface.c.
void RB_SurfaceLightningBolt (void)
RB_SurfaceLightningBolt.
Definition at line 862 of file tr_surface.c.
void RB_SurfaceMesh (md3Surface_t * surface)
RB_SurfaceMesh.
Parameters
[in] surface
Todo:
: fill in lightmapST for completeness?
Definition at line 1019 of file tr_surface.c.
void RB_SurfacePolyBuffer (srfPolyBuffer_t * surf)
RB_SurfacePolyBuffer.
Parameters
[in] surf
Definition at line 1763 of file tr_surface.c.
void RB_SurfacePolychain (srfPoly_t * p)
RB_SurfacePolychain.
Parameters
[in] p
Definition at line 323 of file tr_surface.c.
void RB_SurfaceRailCore (void)
RB_SurfaceRailCore.
Definition at line 833 of file tr_surface.c.
void RB_SurfaceRailRings (void)
RB_SurfaceRailRings.
Definition at line 803 of file tr_surface.c.
void RB_SurfaceSkip (void * surf)
RB_SurfaceSkip.
Parameters
surf - dummy function for SF_SKIP
Definition at line 1827 of file tr_surface.c.
static void RB_SurfaceSplash (void) static
RB_SurfaceSplash.
Definition at line 267 of file tr_surface.c.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceSprite (void) static
RB_SurfaceSprite.
Definition at line 287 of file tr_surface.c.
Referenced by RB_SurfaceEntity().
void RB_SurfaceTriangles (srfTriangles_t * srf)
RB_SurfaceTriangles.
Parameters
[in] srf
Definition at line 358 of file tr_surface.c.
Variable Documentation
void(* rb_surfaceTable[SF_NUM_SURFACE_TYPES])(void *)
Initial value:
=
{
    (void (*)(void *))RB_SurfaceBad,
    (void (*)(void *))RB_SurfaceSkip,
    (void (*)(void *))RB_SurfaceFace,
    (void (*)(void *))RB_SurfaceGrid,
    (void (*)(void *))RB_SurfaceTriangles,
    (void (*)(void *))RB_SurfaceFoliage,
    (void (*)(void *))RB_SurfacePolychain,
    (void (*)(void *))RB_SurfaceMesh,
    (void (*)(void *))RB_SurfaceCMesh,
    (void (*)(void *))RB_SurfaceAnim,
    (void (*)(void *))RB_MDM_SurfaceAnim,
    (void (*)(void *))RB_SurfaceFlare,
    (void (*)(void *))RB_SurfaceEntity,
    (void (*)(void *))RB_SurfaceDisplayList,
    (void (*)(void *))RB_SurfacePolyBuffer,
    (void (*)(void *))RB_SurfaceDecal,
}
Definition at line 1832 of file tr_surface.c.
Referenced by RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderDrawSurfList(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), and SurfIsOffscreen().