ET: Legacy: src/rendererGLES/tr_curve.c File Reference
tr_curve.c File Reference
This file does all of the processing necessary to turn a raw grid of points read from the map file into a srfGridMesh_t ready for rendering.
#include "tr_local.h"
Functions
static void LerpDrawVert (drawVert_t *a, drawVert_t *b, drawVert_t *out)
LerpDrawVert.
static void Transpose (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE])
Transpose.
static void MakeMeshNormals (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE])
Handles all the complicated wrapping and degenerate cases.
static void InvertCtrl (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE])
InvertCtrl.
static void InvertErrorTable (float errorTable[2][MAX_GRID_SIZE], int width, int height)
InvertErrorTable.
static void PutPointsOnCurve (drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], int width, int height)
PutPointsOnCurve.
srfGridMesh_t * R_CreateSurfaceGridMesh (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], float errorTable[2][MAX_GRID_SIZE])
R_CreateSurfaceGridMesh.
void R_FreeSurfaceGridMesh (srfGridMesh_t *grid)
R_FreeSurfaceGridMesh.
srfGridMesh_t * R_SubdividePatchToGrid (int width, int height, drawVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
R_SubdividePatchToGrid.
srfGridMesh_t * R_GridInsertColumn (srfGridMesh_t *grid, int column, int row, vec3_t point, float loderror)
R_GridInsertColumn.
srfGridMesh_t * R_GridInsertRow (srfGridMesh_t *grid, int row, int column, vec3_t point, float loderror)
R_GridInsertRow.
Detailed Description
This file does all of the processing necessary to turn a raw grid of points read from the map file into a srfGridMesh_t ready for rendering.
The level of detail solution is direction independent, based only on subdivided distance from the true curve.
Only a single entry point: R_SubdividePatchToGrid(int width, int height, srfVert_t points[MAX_PATCH_SIZE*MAX_PATCH_SIZE])
Definition in file tr_curve.c.
Function Documentation
static void InvertCtrl (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE]) static
InvertCtrl.
Parameters
[in] width
[in] height
[in,out] ctrl
Definition at line 258 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().
static void InvertErrorTable (float errorTable[2][MAX_GRID_SIZE], int width, int height) static
InvertErrorTable.
Parameters
[out] errorTable
[in] width
[in] height
Definition at line 280 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().
static void LerpDrawVert (drawVert_t * a, drawVert_t * b, drawVert_t * out) static
LerpDrawVert.
Parameters
[in] a
[in] b
[out] out
Definition at line 52 of file tr_curve.c.
Referenced by PutPointsOnCurve(), R_GridInsertColumn(), R_GridInsertRow(), and R_SubdividePatchToGrid().
static void MakeMeshNormals (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE]) static
Handles all the complicated wrapping and degenerate cases.
Parameters
[in] width
[in] height
[in,out] ctrl
Definition at line 135 of file tr_curve.c.
Referenced by R_GridInsertColumn(), R_GridInsertRow(), and R_SubdividePatchToGrid().
static void PutPointsOnCurve (drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], int width, int height) static
PutPointsOnCurve.
Parameters
[in] ctrl
[in] width
[in] height
Definition at line 304 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().
srfGridMesh_t* R_CreateSurfaceGridMesh (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE], float errorTable[2][MAX_GRID_SIZE])
R_CreateSurfaceGridMesh.
Parameters
[in] width
[in] height
[in] ctrl
[in] errorTable
Returns
Definition at line 339 of file tr_curve.c.
void R_FreeSurfaceGridMesh (srfGridMesh_t * grid)
R_FreeSurfaceGridMesh.
Parameters
[in] grid
Definition at line 400 of file tr_curve.c.
srfGridMesh_t* R_GridInsertColumn (srfGridMesh_t * grid, int column, int row, vec3_t point, float loderror)
R_GridInsertColumn.
Parameters
[in,out] grid
[in] column
[in] row
[in] point
[in] loderror
Returns
Definition at line 601 of file tr_curve.c.
srfGridMesh_t* R_GridInsertRow (srfGridMesh_t * grid, int row, int column, vec3_t point, float loderror)
R_GridInsertRow.
Parameters
[in,out] grid
[in] row
[in] column
[in] point
[in] loderror
Returns
Definition at line 667 of file tr_curve.c.
srfGridMesh_t* R_SubdividePatchToGrid (int width, int height, drawVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
R_SubdividePatchToGrid.
Parameters
[in] width
[in] height
[in] points
Returns
Todo:
: also check midpoints of adjacent patches against the control points
Definition at line 414 of file tr_curve.c.
static void Transpose (int width, int height, drawVert_t ctrl[MAX_GRID_SIZE][MAX_GRID_SIZE]) static
Transpose.
Parameters
[in] width
[in] height
[in,out] ctrl
Definition at line 80 of file tr_curve.c.
Referenced by R_SubdividePatchToGrid().