ET: Legacy: src/rendererGLES/tr_scene.c File Reference
tr_scene.c File Reference
#include "tr_local.h"
Functions
void R_InitNextFrame (void)
R_InitNextFrame.
void RE_ClearScene (void)
RE_ClearScene.
void R_AddPolygonSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
void RE_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
RE_AddPolyToScene.
void RE_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
RE_AddPolysToScene.
void R_AddPolygonBufferSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
void RE_AddPolyBufferToScene (polyBuffer_t *pPolyBuffer)
RE_AddPolyBufferToScene.
void RE_AddRefEntityToScene (const refEntity_t *ent)
RE_AddRefEntityToScene.
void RE_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
Modified dlight system to support seperate radius and intensity.
void RE_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
RE_AddCoronaToScene.
void RE_RenderScene (const refdef_t *fd)
Draw a 3D view into a part of the window, then return to 2D drawing.
Variables
int r_firstSceneDrawSurf
int r_numdlights
int r_firstSceneDlight
int r_numcoronas
int r_firstSceneCorona
int r_numentities
int r_firstSceneEntity
int r_numpolys
int r_firstScenePoly
int r_numpolyverts
int r_firstScenePolybuffer
int r_numpolybuffers
int r_firstSceneDecalProjector
int r_numDecalProjectors
int r_firstSceneDecal
int skyboxportal
Function Documentation
void R_AddPolygonBufferSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
Definition at line 308 of file tr_scene.c.
Referenced by R_GenerateDrawSurfs(), and R_RenderView().
void R_AddPolygonSurfaces (void)
Adds all the scene's polys into this view's drawsurf list.
Definition at line 118 of file tr_scene.c.
Referenced by R_GenerateDrawSurfs(), and R_RenderView().
void R_InitNextFrame (void)
R_InitNextFrame.
Definition at line 67 of file tr_scene.c.
Referenced by R_Init(), and RE_EndFrame().
void RE_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
RE_AddCoronaToScene.
Parameters
[in] org
[in] r
[in] g
[in] b
[in] scale
[in] id
[in] visible
Definition at line 488 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
Modified dlight system to support seperate radius and intensity.
Parameters
[in] org
[in] radius
[in] intensity
[in] r
[in] g
[in] b
[in] hShader
[in] flags
Definition at line 434 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_AddPolyBufferToScene (polyBuffer_t * pPolyBuffer)
RE_AddPolyBufferToScene.
Parameters
[in] pPolyBuffer
Definition at line 329 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int numPolys)
RE_AddPolysToScene.
Parameters
[in] hShader
[in] numVerts
[in] verts
[in] numPolys
Definition at line 220 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
RE_AddPolyToScene.
Parameters
[in] hShader
[in] numVerts
[in] verts
Definition at line 141 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_AddRefEntityToScene (const refEntity_t * ent)
RE_AddRefEntityToScene.
Parameters
[in] ent
Definition at line 382 of file tr_scene.c.
Referenced by GetRefAPI().
void RE_ClearScene (void)
RE_ClearScene.
Definition at line 100 of file tr_scene.c.
Referenced by GetRefAPI(), and RE_BeginRegistration().
void RE_RenderScene (const refdef_t * fd)
Draw a 3D view into a part of the window, then return to 2D drawing.
Rendering a scene may require multiple views to be rendered to handle mirrors.
Parameters
[in] fd
Definition at line 527 of file tr_scene.c.
Referenced by GetRefAPI(), and R_BuildCubeMaps().
Variable Documentation
int r_firstSceneCorona
Definition at line 43 of file tr_scene.c.
int r_firstSceneDecal
Definition at line 60 of file tr_scene.c.
Referenced by R_AddDecalSurface().
int r_firstSceneDecalProjector
Definition at line 58 of file tr_scene.c.
int r_firstSceneDlight
Definition at line 40 of file tr_scene.c.
int r_firstSceneDrawSurf
Definition at line 37 of file tr_scene.c.
int r_firstSceneEntity
Definition at line 46 of file tr_scene.c.
int r_firstScenePoly
Definition at line 49 of file tr_scene.c.
int r_firstScenePolybuffer
Definition at line 54 of file tr_scene.c.
int r_numcoronas
Definition at line 42 of file tr_scene.c.
int r_numDecalProjectors
Definition at line 59 of file tr_scene.c.
Referenced by RE_ProjectDecal().
int r_numdlights
Definition at line 39 of file tr_scene.c.
int r_numentities
Definition at line 45 of file tr_scene.c.
int r_numpolybuffers
Definition at line 55 of file tr_scene.c.
int r_numpolys
Definition at line 48 of file tr_scene.c.
int r_numpolyverts
Definition at line 51 of file tr_scene.c.
Referenced by RE_2DPolyies(), and RE_StretchPic().
int skyboxportal
Definition at line 62 of file tr_scene.c.
Referenced by RB_BeginDrawingView(), RB_StageIteratorSky(), RE_LoadWorldMap(), and SetIteratorFog().