ET: Legacy: src/rendererGLES/tr_shade_calc.c File Reference
tr_shade_calc.c File Reference
#include "tr_local.h"
Macros
#define WAVEVALUE(table, base, amplitude, phase, freq) ((base) + table[(int64_t)((((phase) + tess.shaderTime * (freq)) *FUNCTABLE_SIZE)) & FUNCTABLE_MASK] * (amplitude))
Functions
static float * TableForFunc (genFunc_t func)
TableForFunc.
static float EvalWaveForm (const waveForm_t *wf)
Evaluates a given waveForm_t, referencing backEnd.refdef.time directly.
static float EvalWaveFormClamped (const waveForm_t *wf)
EvalWaveFormClamped.
void RB_CalcStretchTexCoords (const waveForm_t *wf, float *texCoords)
RB_CalcStretchTexCoords.
void RB_CalcDeformVertexes (deformStage_t *ds)
RB_CalcDeformVertexes.
void RB_CalcDeformNormals (deformStage_t *ds)
Wiggle the normals for wavy environment mapping.
void RB_CalcBulgeVertexes (deformStage_t *ds)
RB_CalcBulgeVertexes.
void RB_CalcMoveVertexes (deformStage_t *ds)
A deformation that can move an entire surface along a wave path.
void DeformText (const char *text)
Change a polygon into a bunch of text polygons.
void GlobalVectorToLocal (const vec3_t in, vec3_t out)
GlobalVectorToLocal.
static void AutospriteDeform (void)
Assuming all the triangles for this shader are independant quads, rebuild them as forward facing sprites.
static void Autosprite2Deform (void)
Autosprite2 will pivot a rectangular quad along the center of its long axis.
void RB_DeformTessGeometry (void)
RB_DeformTessGeometry.
void RB_CalcColorFromEntity (unsigned char *colors)
RB_CalcColorFromEntity.
void RB_CalcColorFromOneMinusEntity (unsigned char *colors)
RB_CalcColorFromOneMinusEntity.
void RB_CalcAlphaFromEntity (unsigned char *colors)
RB_CalcAlphaFromEntity.
void RB_CalcAlphaFromOneMinusEntity (unsigned char *colors)
RB_CalcAlphaFromOneMinusEntity.
void RB_CalcWaveColor (const waveForm_t *wf, unsigned char *colors)
RB_CalcWaveColor.
void RB_CalcWaveAlpha (const waveForm_t *wf, unsigned char *colors)
RB_CalcWaveAlpha.
void RB_CalcModulateAlphasByFog (unsigned char *colors)
RB_CalcModulateAlphasByFog.
void RB_CalcModulateColorsByFog (unsigned char *colors)
RB_CalcModulateColorsByFog.
void RB_CalcModulateRGBAsByFog (unsigned char *colors)
RB_CalcModulateRGBAsByFog.
void RB_CalcFogTexCoords (float *texCoords)
To do the clipped fog plane really correctly, we should use projected textures, but I don't trust the drivers and it doesn't fit our shader data.
void RB_CalcEnvironmentTexCoords (float *texCoords)
RB_CalcEnvironmentTexCoords.
void RB_CalcFireRiseEnvTexCoords (float *st)
RB_CalcFireRiseEnvTexCoords.
void RB_CalcSwapTexCoords (float *texCoords)
RB_CalcSwapTexCoords.
void RB_CalcTurbulentTexCoords (const waveForm_t *wf, float *texCoords)
RB_CalcTurbulentTexCoords.
void RB_CalcScaleTexCoords (const float scale[2], float *texCoords)
RB_CalcScaleTexCoords.
void RB_CalcScrollTexCoords (const float scrollSpeed[2], float *texCoords)
RB_CalcScrollTexCoords.
void RB_CalcTransformTexCoords (const texModInfo_t *tmi, float *texCoords)
RB_CalcTransformTexCoords.
void RB_CalcRotateTexCoords (float degsPerSecond, float *texCoords)
RB_CalcRotateTexCoords.
void RB_CalcSpecularAlpha (unsigned char *alphas)
Calculates specular coefficient and places it in the alpha channel.
void RB_CalcDiffuseColor (unsigned char *colors)
The basic vertex lighting calc.
Variables
int edgeVerts [6][2]
vec3_t lightOrigin = { -960, 1980, 96 }
Macro Definition Documentation
#define WAVEVALUE (table, base, amplitude, phase, freq) ((base) + table[(int64_t)((((phase) + tess.shaderTime * (freq)) *FUNCTABLE_SIZE)) & FUNCTABLE_MASK] * (amplitude))
Definition at line 37 of file tr_shade_calc.c.
Referenced by EvalWaveForm(), RB_CalcDeformVertexes(), and RB_CalcMoveVertexes().
Function Documentation
static void Autosprite2Deform (void) static
Autosprite2 will pivot a rectangular quad along the center of its long axis.
Definition at line 506 of file tr_shade_calc.c.
Referenced by RB_DeformTessGeometry().
static void AutospriteDeform (void) static
Assuming all the triangles for this shader are independant quads, rebuild them as forward facing sprites.
Definition at line 417 of file tr_shade_calc.c.
Referenced by RB_DeformTessGeometry().
void DeformText (const char * text)
Change a polygon into a bunch of text polygons.
Parameters
[in] text
Definition at line 331 of file tr_shade_calc.c.
static float EvalWaveForm (const waveForm_t * wf) static
Evaluates a given waveForm_t, referencing backEnd.refdef.time directly.
Parameters
[in] wf
Returns
Definition at line 72 of file tr_shade_calc.c.
Referenced by EvalWaveFormClamped(), RB_CalcDeformVertexes(), RB_CalcStretchTexCoords(), and RB_CalcWaveColor().
static float EvalWaveFormClamped (const waveForm_t * wf) static
EvalWaveFormClamped.
Parameters
[in] wf
Returns
Definition at line 86 of file tr_shade_calc.c.
Referenced by RB_CalcWaveAlpha().
void GlobalVectorToLocal (const vec3_t in, vec3_t out)
GlobalVectorToLocal.
Parameters
[in] in
[out] out
Definition at line 406 of file tr_shade_calc.c.
void RB_CalcAlphaFromEntity (unsigned char * colors)
RB_CalcAlphaFromEntity.
Parameters
[in,out] colors
Definition at line 735 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcAlphaFromOneMinusEntity (unsigned char * colors)
RB_CalcAlphaFromOneMinusEntity.
Parameters
[in,out] colors
Definition at line 756 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcBulgeVertexes (deformStage_t * ds)
RB_CalcBulgeVertexes.
Parameters
[in] ds
Definition at line 278 of file tr_shade_calc.c.
void RB_CalcColorFromEntity (unsigned char * colors)
RB_CalcColorFromEntity.
Parameters
[in,out] colors
Definition at line 683 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcColorFromOneMinusEntity (unsigned char * colors)
RB_CalcColorFromOneMinusEntity.
Parameters
[in,out] colors
Definition at line 706 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcDeformNormals (deformStage_t * ds)
Wiggle the normals for wavy environment mapping.
Parameters
[in] ds
Definition at line 246 of file tr_shade_calc.c.
void RB_CalcDeformVertexes (deformStage_t * ds)
RB_CalcDeformVertexes.
Parameters
[in,out] ds
Definition at line 136 of file tr_shade_calc.c.
void RB_CalcDiffuseColor (unsigned char * colors)
The basic vertex lighting calc.
Faster, table-based version of this function saves about 1-2ms per frame on my machine with 64 x 1000 triangle models in scene
Parameters
[in,out] colors
Definition at line 1360 of file tr_shade_calc.c.
Referenced by ComputeColors(), and RB_StageIteratorVertexLitTexture().
void RB_CalcEnvironmentTexCoords (float * texCoords)
RB_CalcEnvironmentTexCoords.
Parameters
[in,out] texCoords
Definition at line 1091 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcFireRiseEnvTexCoords (float * st)
RB_CalcFireRiseEnvTexCoords.
Parameters
[in,out] st
Definition at line 1144 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcFogTexCoords (float * texCoords)
To do the clipped fog plane really correctly, we should use projected textures, but I don't trust the drivers and it doesn't fit our shader data.
Parameters
[in,out] texCoords
Definition at line 990 of file tr_shade_calc.c.
Referenced by ComputeTexCoords(), and RB_FogPass().
void RB_CalcModulateAlphasByFog (unsigned char * colors)
RB_CalcModulateAlphasByFog.
Parameters
[in,out] colors
Definition at line 848 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcModulateColorsByFog (unsigned char * colors)
RB_CalcModulateColorsByFog.
Parameters
[in,out] colors
Definition at line 889 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcModulateRGBAsByFog (unsigned char * colors)
RB_CalcModulateRGBAsByFog.
Parameters
[in,out] colors
Definition at line 934 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcMoveVertexes (deformStage_t * ds)
A deformation that can move an entire surface along a wave path.
Parameters
[in] ds
Definition at line 303 of file tr_shade_calc.c.
void RB_CalcRotateTexCoords (float degsPerSecond, float * texCoords)
RB_CalcRotateTexCoords.
Parameters
[in] degsPerSecond
[in,out] texCoords
Definition at line 1274 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcScaleTexCoords (const float scale[2], float * texCoords)
RB_CalcScaleTexCoords.
Parameters
[in] scale
[in,out] texCoords
Definition at line 1214 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcScrollTexCoords (const float scrollSpeed[2], float * texCoords)
RB_CalcScrollTexCoords.
Parameters
[in] scrollSpeed
[in,out] texCoords
Definition at line 1230 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcSpecularAlpha (unsigned char * alphas)
Calculates specular coefficient and places it in the alpha channel.
Todo:
: track dynamically
Parameters
[in,out] alphas
Definition at line 1300 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcStretchTexCoords (const waveForm_t * wf, float * texCoords)
RB_CalcStretchTexCoords.
Parameters
[in] wf
[out] texCoords
Definition at line 108 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcSwapTexCoords (float * texCoords)
RB_CalcSwapTexCoords.
Parameters
[in,out] texCoords
Definition at line 1173 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcTransformTexCoords (const texModInfo_t * tmi, float * texCoords)
RB_CalcTransformTexCoords.
Parameters
[in] tmi
[in,out] texCoords
Definition at line 1254 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcTurbulentTexCoords (const waveForm_t * wf, float * texCoords)
RB_CalcTurbulentTexCoords.
Parameters
[in] wf
[in,out] texCoords
Definition at line 1193 of file tr_shade_calc.c.
Referenced by ComputeTexCoords().
void RB_CalcWaveAlpha (const waveForm_t * wf, unsigned char * colors)
RB_CalcWaveAlpha.
Parameters
[in] wf
[in,out] colors
Definition at line 820 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_CalcWaveColor (const waveForm_t * wf, unsigned char * colors)
RB_CalcWaveColor.
Parameters
[in] wf
[in,out] colors
Definition at line 778 of file tr_shade_calc.c.
Referenced by ComputeColors().
void RB_DeformTessGeometry (void)
RB_DeformTessGeometry.
Definition at line 625 of file tr_shade_calc.c.
Referenced by RB_StageIteratorGeneric().
static float* TableForFunc (genFunc_t func) static
TableForFunc.
Parameters
[in] func
Returns
Definition at line 44 of file tr_shade_calc.c.
Referenced by EvalWaveForm(), RB_CalcDeformVertexes(), and RB_CalcMoveVertexes().
Variable Documentation
int edgeVerts[6][2]
Initial value:
=
{
    { 0, 1 },
    { 0, 2 },
    { 0, 3 },
    { 1, 2 },
    { 1, 3 },
    { 2, 3 }
}
Definition at line 493 of file tr_shade_calc.c.
vec3_t lightOrigin = { -960, 1980, 96 }
Definition at line 1294 of file tr_shade_calc.c.