ET: Legacy: src/rendererGLES/tr_shader.c File Reference
tr_shader.c File Reference
Parsing and definition of shaders.
#include "tr_local.h"
Data Structures
struct shaderStringPointer_s
struct infoParm_t
struct collapse_t
struct dynamicshader
Dynamic shader list.
Macros
#define FILE_HASH_SIZE 4096
#define generateHashValue(fname) Q_GenerateHashValue(fname, FILE_HASH_SIZE, qfalse, qtrue)
#define EXTERNAL_LIGHTMAP "lm_%04d.tga"
#define MAX_SHADER_STRING_POINTERS 100000
#define MAX_SHADER_FILES 4096
Typedefs
typedef struct shaderStringPointer_s shaderStringPointer_t
typedef struct dynamicshader dynamicshader_t
Functions
void R_RemapShader (const char *shaderName, const char *newShaderName, const char *timeOffset)
R_RemapShader.
static qboolean ParseVector (char **text, int count, float *v)
ParseVector.
static unsigned NameToAFunc (const char *funcname)
NameToAFunc.
static int NameToSrcBlendMode (const char *name)
NameToSrcBlendMode.
static int NameToDstBlendMode (const char *name)
NameToDstBlendMode.
static genFunc_t NameToGenFunc (const char *funcname)
NameToGenFunc.
static void ParseWaveForm (char **text, waveForm_t *wave)
ParseWaveForm.
static void ParseTexMod (char *_text, shaderStage_t *stage)
ParseTexMod.
static qboolean ParseStage (shaderStage_t *stage, char **text)
ParseStage.
static void ParseDeform (char **text)
ParseDeform.
static void ParseSkyParms (char **text)
ParseSkyParms.
void ParseSort (char **text)
ParseSort.
static void ParseSurfaceParm (char **text)
ParseSurfaceParm.
static qboolean ParseShader (char **text)
The current text pointer is at the explicit text definition of the shader. Parse it into the global shader variable. Later functions will optimize it.
static void ComputeStageIteratorFunc (void)
See if we can use on of the simple fastpath stage functions, otherwise set to the generic stage function.
static qboolean CollapseMultitexture (void)
Attempt to combine two stages into a single multitexture stage.
static void FixRenderCommandList (int newShader)
FixRenderCommandList.
static void SortNewShader (void)
Positions the most recently created shader in the tr.sortedShaders[] array so that the shader->sort key is sorted reletive to the other shaders.
static shader_t * GeneratePermanentShader (void)
GeneratePermanentShader.
static void SetImplicitShaderStages (image_t *image)
Sets a shader's stages to one of several defaults.
static shader_t * FinishShader (void)
Returns a freshly allocated shader with all the needed info from the current global working shader.
qboolean RE_LoadDynamicShader (const char *shadername, const char *shadertext)
load a new dynamic shader if shadertext is NULL, looks for matching shadername and removes it
static char * FindShaderInShaderText (const char *shadername)
Scans the combined text description of all the shader files for the given shader name.
shader_t * R_FindShaderByName (const char *name)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
void R_FindLightmap (int *lightmapIndex)
Given a (potentially erroneous) lightmap index, attempts to load an external lightmap image and/or sets the index to a valid number.
shader_t * R_FindShader (const char *name, int lightmapIndex, qboolean mipRawImage)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
qhandle_t RE_RegisterShaderFromImage (const char *name, int lightmapIndex, image_t *image, qboolean mipRawImage)
RE_RegisterShaderFromImage.
qhandle_t RE_RegisterShaderLightMap (const char *name, int lightmapIndex)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
qhandle_t RE_RegisterShader (const char *name)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
qhandle_t RE_RegisterShaderNoMip (const char *name)
RE_RegisterShaderNoMip.
shader_t * R_GetShaderByHandle (qhandle_t hShader)
When a handle is passed in by another module, this range checks it and returns a valid (possibly default) shader_t to be used internally.
void R_ShaderList_f (void)
Dump information on all valid shaders to the console A second parameter will cause it to print in sorted order.
static void BuildShaderChecksumLookup (void)
BuildShaderChecksumLookup.
static void ScanAndLoadShaderFiles (void)
Finds and loads all .shader files, combining them into a single large text block that can be scanned for shader names.
static void CreateInternalShaders (void)
CreateInternalShaders.
static void CreateExternalShaders (void)
void * R_CacheShaderAllocExt (const char *name, int size, const char *file, int line)
R_CacheShaderAllocExt.
void R_CacheShaderFreeExt (const char *name, void *ptr, const char *file, int line)
R_CacheShaderFreeExt.
void R_PurgeShaders (int count)
R_PurgeShaders.
qboolean R_ShaderCanBeCached (shader_t *sh)
R_ShaderCanBeCached.
void R_PurgeLightmapShaders (void)
R_PurgeLightmapShaders.
void R_BackupShaders (void)
R_BackupShaders.
static qboolean R_RegisterShaderImages (shader_t *sh)
Make sure all images that belong to this shader remain valid.
shader_t * R_FindCachedShader (const char *name, int lightmapIndex, int hash)
Look for the given shader in the list of backupShaders.
void R_LoadCacheShaders (void)
R_LoadCacheShaders.
void R_InitShaders (void)
R_InitShaders.
Variables
static char * s_shaderText
static shaderStage_t stages [MAX_SHADER_STAGES]
static shader_t shader
static texModInfo_t texMods [MAX_SHADER_STAGES][TR_MAX_TEXMODS]
static char implicitMap [MAX_QPATH]
static unsigned implicitStateBits
static cullType_t implicitCullType
static shader_t * hashTable [FILE_HASH_SIZE]
shaderStringPointer_t shaderChecksumLookup [FILE_HASH_SIZE]
infoParm_t infoParms []
static collapse_t collapse []
static dynamicshader_t * dshader = NULL
shaderStringPointer_t shaderStringPointerList [MAX_SHADER_STRING_POINTERS]
static int numBackupShaders = 0
static shader_t * backupShaders [MAX_SHADERS]
static shader_t * backupHashTable [FILE_HASH_SIZE]
qboolean purgeallshaders = qfalse
Detailed Description
Parsing and definition of shaders.
Definition in file tr_shader.c.
Macro Definition Documentation
#define EXTERNAL_LIGHTMAP "lm_%04d.tga"
Definition at line 3237 of file tr_shader.c.
Referenced by R_FindLightmap().
#define FILE_HASH_SIZE 4096
Definition at line 50 of file tr_shader.c.
#define generateHashValue (fname) Q_GenerateHashValue(fname, FILE_HASH_SIZE, qfalse, qtrue)
Definition at line 52 of file tr_shader.c.
Referenced by BuildShaderChecksumLookup(), FindShaderInShaderText(), GeneratePermanentShader(), R_FindShader(), R_FindShaderByName(), R_RemapShader(), and RE_RegisterShaderFromImage().
#define MAX_SHADER_FILES 4096
Definition at line 3813 of file tr_shader.c.
Referenced by ScanAndLoadShaderFiles().
#define MAX_SHADER_STRING_POINTERS 100000
Definition at line 3750 of file tr_shader.c.
Referenced by BuildShaderChecksumLookup().
Typedef Documentation
typedef struct dynamicshader dynamicshader_t
Definition at line 2954 of file tr_shader.c.
typedef struct shaderStringPointer_s shaderStringPointer_t
Function Documentation
static void BuildShaderChecksumLookup (void) static
BuildShaderChecksumLookup.
Definition at line 3756 of file tr_shader.c.
Referenced by ScanAndLoadShaderFiles().
static qboolean CollapseMultitexture (void) static
Attempt to combine two stages into a single multitexture stage.
Returns
Todo:
FIXME: I think modulated add + modulated add collapses incorrectly
Definition at line 2292 of file tr_shader.c.
Referenced by FinishShader().
static void ComputeStageIteratorFunc (void) static
See if we can use on of the simple fastpath stage functions, otherwise set to the generic stage function.
Definition at line 2173 of file tr_shader.c.
Referenced by FinishShader().
static void CreateExternalShaders (void) static
Definition at line 3913 of file tr_shader.c.
Referenced by R_InitShaders().
static void CreateInternalShaders (void) static
CreateInternalShaders.
Definition at line 3891 of file tr_shader.c.
Referenced by R_InitShaders().
static char* FindShaderInShaderText (const char * shadername) static
Scans the combined text description of all the shader files for the given shader name.
Parameters
[in] shadername
Returns
If found, it will return a valid shader. Otherwise return NULL if not found
Definition at line 3084 of file tr_shader.c.
Referenced by R_FindShader().
static shader_t* FinishShader (void) static
Returns a freshly allocated shader with all the needed info from the current global working shader.
Returns
Definition at line 2781 of file tr_shader.c.
Referenced by CreateInternalShaders(), R_FindShader(), and RE_RegisterShaderFromImage().
static void FixRenderCommandList (int newShader) static
FixRenderCommandList.
Todo:
This is a nasty issue. Shaders can be registered after drawsurfaces are generated but before the frame is rendered. This will, for the duration of one frame, cause drawsurfaces to be rendered with bad shaders. To fix this, need to go through all render commands and fix sortedIndex.
Parameters
newShader
Definition at line 2411 of file tr_shader.c.
Referenced by SortNewShader().
static shader_t* GeneratePermanentShader (void) static
GeneratePermanentShader.
Returns
Definition at line 2525 of file tr_shader.c.
Referenced by FinishShader().
static unsigned NameToAFunc (const char * funcname) static
NameToAFunc.
Parameters
[in] funcname
Definition at line 176 of file tr_shader.c.
Referenced by ParseStage().
static int NameToDstBlendMode (const char * name) static
NameToDstBlendMode.
Parameters
[in] name
Returns
Definition at line 249 of file tr_shader.c.
Referenced by ParseStage().
static genFunc_t NameToGenFunc (const char * funcname) static
NameToGenFunc.
Parameters
[in] funcname
Returns
Definition at line 293 of file tr_shader.c.
Referenced by ParseTexMod(), and ParseWaveForm().
static int NameToSrcBlendMode (const char * name) static
NameToSrcBlendMode.
Parameters
[in] name
Returns
Definition at line 200 of file tr_shader.c.
Referenced by ParseStage().
static void ParseDeform (char ** text) static
ParseDeform.
Parameters
[in,out] text
Note
deformVertexes wave <spread> <waveform> <base> <amplitude> <phase> <frequency> deformVertexes normal <frequency> <amplitude> deformVertexes move <vector> <waveform> <base> <amplitude> <phase> <frequency> deformVertexes bulge <bulgeWidth> <bulgeHeight> <bulgeSpeed> deformVertexes projectionShadow deformVertexes autoSprite deformVertexes autoSprite2 deformVertexes text[0-7]
Definition at line 1272 of file tr_shader.c.
static qboolean ParseShader (char ** text) static
The current text pointer is at the explicit text definition of the shader. Parse it into the global shader variable. Later functions will optimize it.
Parameters
[in,out] text
Returns
Todo:
Definition at line 1696 of file tr_shader.c.
Referenced by R_FindShader().
static void ParseSkyParms (char ** text) static
ParseSkyParms.
Parameters
[in,out] text
Note
skyParms <outerbox> <cloudheight> <innerbox>
Definition at line 1429 of file tr_shader.c.
void ParseSort (char ** text)
ParseSort.
Parameters
[in,out] text
Definition at line 1501 of file tr_shader.c.
static qboolean ParseStage (shaderStage_t * stage, char ** text) static
ParseStage.
Parameters
[in,out] stage
[in,out] text
Returns
Definition at line 602 of file tr_shader.c.
static void ParseSurfaceParm (char ** text) static
ParseSurfaceParm.
Parameters
[in,out] text
Note
surfaceparm <name>
Definition at line 1653 of file tr_shader.c.
static void ParseTexMod (char * _text, shaderStage_t * stage) static
ParseTexMod.
Parameters
[in,out] _text
[in,out] stage
Definition at line 380 of file tr_shader.c.
static qboolean ParseVector (char ** text, int count, float * v) static
ParseVector.
Parameters
[in,out] text
[in] count
[out] v
Returns
Todo:
: spaces are currently required after parens, should change parseext...
Definition at line 138 of file tr_shader.c.
Referenced by ParseShader(), and ParseStage().
static void ParseWaveForm (char ** text, waveForm_t * wave) static
ParseWaveForm.
Parameters
[in,out] text
[out] wave
Definition at line 329 of file tr_shader.c.
void R_BackupShaders (void)
R_BackupShaders.
Definition at line 4087 of file tr_shader.c.
Referenced by RE_Shutdown().
void* R_CacheShaderAllocExt (const char * name, int size, const char * file, int line)
R_CacheShaderAllocExt.
Parameters
name - unused
[in] size
file - unused
line - unused
Returns
Definition at line 3935 of file tr_shader.c.
void R_CacheShaderFreeExt (const char * name, void * ptr, const char * file, int line)
R_CacheShaderFreeExt.
Parameters
name - unused
[in] ptr
file - unused
line - unused
Definition at line 3955 of file tr_shader.c.
shader_t* R_FindCachedShader (const char * name, int lightmapIndex, int hash)
Look for the given shader in the list of backupShaders.
Parameters
[in] name
[in] lightmapIndex
[in] hash
Returns
Definition at line 4161 of file tr_shader.c.
void R_FindLightmap (int * lightmapIndex)
Given a (potentially erroneous) lightmap index, attempts to load an external lightmap image and/or sets the index to a valid number.
Parameters
[in,out] lightmapIndex
Definition at line 3244 of file tr_shader.c.
shader_t* R_FindShader (const char * name, int lightmapIndex, qboolean mipRawImage)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
In the interest of not requiring an explicit shader text entry to be defined for every single image used in the game, three default shader behaviors can be auto-created for any image:
If lightmapIndex == LIGHTMAP_NONE, then the image will have dynamic diffuse lighting applied to it, as apropriate for most entity skin surfaces.
If lightmapIndex == LIGHTMAP_2D, then the image will be used for 2D rendering unless an explicit shader is found
If lightmapIndex == LIGHTMAP_BY_VERTEX, then the image will use the vertex rgba modulate values, as apropriate for misc_model pre-lit surfaces.
Other lightmapIndex values will have a lightmap stage created and src*dest blending applied with the texture, as apropriate for most world construction surfaces.
Parameters
[in] name
[in] lightmapIndex
[in] mipRawImage
Returns
Todo:
: set these "need" values apropriately
Definition at line 3316 of file tr_shader.c.
Referenced by AddSurfaceToVBOSurfacesList2(), R_LoadFogs(), R_LoadMD3(), R_LoadMD5(), R_LoadMDC(), R_LoadMDM(), R_LoadMDS(), R_LoadModelShadow(), R_RegisterMD3Shaders(), R_RegisterMDCShaders(), RE_GetShaderFromModel(), RE_LoadWorldMap(), RE_RegisterSkin(), and ShaderForShaderNum().
shader_t* R_FindShaderByName (const char * name)
Will always return a valid shader, but it might be the default shader if the real one can't be found.
Parameters
[in] name
Returns
Definition at line 3203 of file tr_shader.c.
shader_t* R_GetShaderByHandle (qhandle_t hShader)
When a handle is passed in by another module, this range checks it and returns a valid (possibly default) shader_t to be used internally.
Parameters
[in] hShader
Returns
Todo:
name
Definition at line 3638 of file tr_shader.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), GetMDMSurfaceShader(), GetMDVSurfaceShader(), R_AddAnimSurfaces(), R_AddBrushModelSurfaces(), R_AddBSPModelSurfaces(), R_AddEntitySurfaces(), R_AddMD3Surfaces(), R_AddMD5Interactions(), R_AddMD5Surfaces(), R_AddMDCSurfaces(), R_AddPolygonBufferSurfaces(), R_AddPolygonInteractions(), R_AddPolygonSurfaces(), R_MDM_AddAnimSurfaces(), R_SetupLightShader(), RE_2DPolyies(), RE_AddDynamicLightToScene(), RE_AddLightToScene(), RE_ProjectDecal(), RE_RotatedPic(), RE_StretchPic(), and RE_StretchPicGradient().
void R_InitShaders (void)
R_InitShaders.
Definition at line 4287 of file tr_shader.c.
Referenced by R_Init().
void R_LoadCacheShaders (void)
R_LoadCacheShaders.
Definition at line 4244 of file tr_shader.c.
void R_PurgeLightmapShaders (void)
R_PurgeLightmapShaders.
Definition at line 4025 of file tr_shader.c.
void R_PurgeShaders (int count)
R_PurgeShaders.
Parameters
count - unused
Definition at line 3969 of file tr_shader.c.
Referenced by R_PurgeCache(), and R_RenderView().
static qboolean R_RegisterShaderImages (shader_t * sh) static
Make sure all images that belong to this shader remain valid.
Parameters
[in] sh
Returns
Definition at line 4126 of file tr_shader.c.
Referenced by R_FindCachedShader().
void R_RemapShader (const char * shaderName, const char * newShaderName, const char * timeOffset)
R_RemapShader.
Parameters
[in] shaderName
[in] newShaderName
[in] timeOffset
Definition at line 75 of file tr_shader.c.
Referenced by GetRefAPI(), and R_LoadEntities().
qboolean R_ShaderCanBeCached (shader_t * sh)
R_ShaderCanBeCached.
Parameters
[in] sh
Returns
Definition at line 3986 of file tr_shader.c.
void R_ShaderList_f (void)
Dump information on all valid shaders to the console A second parameter will cause it to print in sorted order.
Definition at line 3657 of file tr_shader.c.
Referenced by R_Register().
qboolean RE_LoadDynamicShader (const char * shadername, const char * shadertext)
load a new dynamic shader if shadertext is NULL, looks for matching shadername and removes it
Parameters
[in] shadername
[in] shadertext
Returns
qtrue if request was successful, qfalse if the gods were angered
Definition at line 2976 of file tr_shader.c.
Referenced by GetRefAPI().
qhandle_t RE_RegisterShader (const char * name)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
This should really only be used for explicit shaders, because there is no way to ask for different implicit lighting modes (vertex, lightmap, etc)
Parameters
[in] name
Returns
Definition at line 3573 of file tr_shader.c.
Referenced by GetRefAPI().
qhandle_t RE_RegisterShaderFromImage (const char * name, int lightmapIndex, image_t * image, qboolean mipRawImage)
RE_RegisterShaderFromImage.
Parameters
[in] name
[in] lightmapIndex
[in] image
mipRawImage - unused
Returns
Todo:
: set these "need" values apropriately
Definition at line 3480 of file tr_shader.c.
Referenced by R_LoadScalableFont().
qhandle_t RE_RegisterShaderLightMap (const char * name, int lightmapIndex)
This is the exported shader entry point for the rest of the system It will always return an index that will be valid.
This should really only be used for explicit shaders, because there is no way to ask for different implicit lighting modes (vertex, lightmap, etc)
Parameters
[in] name
[in] lightmapIndex
Returns
Definition at line 3537 of file tr_shader.c.
qhandle_t RE_RegisterShaderNoMip (const char * name)
RE_RegisterShaderNoMip.
Parameters
name
Returns
Note
For menu graphics that should never be picmiped
Definition at line 3606 of file tr_shader.c.
Referenced by GetRefAPI(), and R_LoadPreRenderedFont().
static void ScanAndLoadShaderFiles (void) static
Finds and loads all .shader files, combining them into a single large text block that can be scanned for shader names.
Definition at line 3818 of file tr_shader.c.
Referenced by R_InitShaders().
static void SetImplicitShaderStages (image_t * image) static
Sets a shader's stages to one of several defaults.
Parameters
image
Definition at line 2706 of file tr_shader.c.
Referenced by R_FindShader(), and RE_RegisterShaderFromImage().
static void SortNewShader (void) static
Positions the most recently created shader in the tr.sortedShaders[] array so that the shader->sort key is sorted reletive to the other shaders.
Note
Sets shader->sortedIndex
Definition at line 2498 of file tr_shader.c.
Referenced by GeneratePermanentShader(), and R_FindCachedShader().
Variable Documentation
shader_t* backupHashTable[FILE_HASH_SIZE] static
Definition at line 3925 of file tr_shader.c.
Referenced by R_PurgeLightmapShaders().
shader_t* backupShaders[MAX_SHADERS] static
Definition at line 3924 of file tr_shader.c.
collapse_t collapse[] static
Definition at line 2254 of file tr_shader.c.
dynamicshader_t* dshader = NULL static
Definition at line 2965 of file tr_shader.c.
Referenced by FindShaderInShaderText(), and RE_LoadDynamicShader().
shader_t* hashTable[FILE_HASH_SIZE] static
Definition at line 51 of file tr_shader.c.
cullType_t implicitCullType static
Definition at line 48 of file tr_shader.c.
Referenced by ParseShader(), R_FindShader(), and SetImplicitShaderStages().
char implicitMap[MAX_QPATH] static
Definition at line 46 of file tr_shader.c.
Referenced by ParseShader(), and R_FindShader().
unsigned implicitStateBits static
Definition at line 47 of file tr_shader.c.
Referenced by ParseShader(), R_FindShader(), and SetImplicitShaderStages().
infoParm_t infoParms[]
Definition at line 1568 of file tr_shader.c.
int numBackupShaders = 0 static
Definition at line 3923 of file tr_shader.c.
Referenced by R_BackupShaders(), R_FindCachedShader(), R_LoadCacheShaders(), R_PurgeLightmapShaders(), and R_PurgeShaders().
qboolean purgeallshaders = qfalse
Definition at line 3963 of file tr_shader.c.
char* s_shaderText static
Definition at line 37 of file tr_shader.c.
Referenced by BuildShaderChecksumLookup(), FindShaderInShaderText(), and ScanAndLoadShaderFiles().
shader_t shader static
Definition at line 42 of file tr_shader.c.
Referenced by FixRenderCommandList(), GeneratePermanentShader(), and R_ShaderList_f().
shaderStringPointer_t shaderChecksumLookup[FILE_HASH_SIZE]
Definition at line 67 of file tr_shader.c.
shaderStringPointer_t shaderStringPointerList[MAX_SHADER_STRING_POINTERS]
Definition at line 3751 of file tr_shader.c.
shaderStage_t stages[MAX_SHADER_STAGES] static
Definition at line 41 of file tr_shader.c.
texModInfo_t texMods[MAX_SHADER_STAGES][TR_MAX_TEXMODS] static
Definition at line 43 of file tr_shader.c.