ET: Legacy: src/rendererGLES/tr_init.c File Reference
tr_init.c File Reference
Functions that are not called every frame.
#include "tr_local.h"
Functions
static void GfxInfo_f (void)
GfxInfo_f.
static void InitOpenGL (void)
This function is responsible for initializing a valid OpenGL subsystem.
void GL_CheckErrors (void)
GL_CheckErrors.
byte * RB_ReadPixels (int x, int y, int width, int height, size_t *offset, int *padlen)
Reads an image but takes care of alignment issues for reading RGB images.
byte * RB_ReadZBuffer (int x, int y, int width, int height, int *padlen)
RB_ReadZBuffer.
void RB_TakeScreenshotTGA (int x, int y, int width, int height, const char *fileName)
RB_TakeScreenshotTGA.
void RB_TakeScreenshotJPEG (int x, int y, int width, int height, char *fileName)
RB_TakeScreenshotJPEG.
const void * RB_TakeScreenshotCmd (const void *data)
RB_TakeScreenshotCmd.
void R_TakeScreenshot (int x, int y, int width, int height, const char *name, ssFormat_t format)
R_TakeScreenshot.
void R_ScreenshotFilename (int lastNumber, char *fileName, char *ext)
R_ScreenshotFilename.
const void * RB_TakeVideoFrameCmd (const void *data)
RB_TakeVideoFrameCmd.
void R_LevelShot (void)
Levelshots are specialized 128*128 thumbnails for the menu system, sampled down from full screen distorted images.
void R_ScreenShot_f (void)
R_ScreenShot_f.
void GL_SetDefaultState (void)
GL_SetDefaultState.
void R_Register (void)
R_Register.
void R_Init (void)
R_Init.
void R_PurgeCache (void)
void RE_Shutdown (qboolean destroyWindow)
RE_Shutdown.
void RE_EndRegistration (void)
Touch all images to make sure they are resident.
void R_DebugPolygon (int color, int numPoints, float *points)
R_DebugPolygon.
refexport_t * GetRefAPI (int apiVersion, refimport_t *rimp)
GetRefAPI.
Variables
glconfig_t glConfig
outside of TR since it shouldn't be cleared during ref re-init
qboolean textureFilterAnisotropic = qfalse
int maxAnisotropy = 0
glstate_t glState
outside of TR since it shouldn't be cleared during ref re-init
cvar_t * r_flareSize
cvar_t * r_flareFade
cvar_t * r_railWidth
cvar_t * r_railSegmentLength
cvar_t * r_ignoreFastPath
allows us to ignore our Tess fast paths
cvar_t * r_ignore
used for debugging anything
cvar_t * r_detailTextures
enables/disables detail texturing stages
cvar_t * r_zNear
near Z clip plane
cvar_t * r_zFar
far Z clip plane
cvar_t * r_skipBackEnd
cvar_t * r_greyScale
cvar_t * r_measureOverdraw
enables stencil buffer overdraw measurement
cvar_t * r_fastSky
controls whether sky should be cleared or drawn
cvar_t * r_drawSun
cvar_t * r_dynamicLight
dynamic lights enabled/disabled
cvar_t * r_lodBias
push/pull LOD transitions
cvar_t * r_lodScale
cvar_t * r_noreFresh
bypasses the ref rendering
cvar_t * r_drawEntities
disable/enable entity rendering
cvar_t * r_drawWorld
disable/enable world rendering
cvar_t * r_drawFoliage
disable/enable foliage rendering
cvar_t * r_speeds
various levels of information display
cvar_t * r_noVis
disable/enable usage of PVS
cvar_t * r_noCull
cvar_t * r_facePlaneCull
enables culling of planar surfaces with back side test
cvar_t * r_showCluster
cvar_t * r_noCurves
cvar_t * r_allowExtensions
global enable/disable of OpenGL extensions
cvar_t * r_extCompressedTextures
cvar_t * r_extMultitexture
cvar_t * r_extTextureEnvAdd
cvar_t * r_extTextureFilterAnisotropic
cvar_t * r_extMaxAnisotropy
cvar_t * r_ignoreGLErrors
cvar_t * r_logFile
number of frames to emit GL logs
cvar_t * r_primitives
cvar_t * r_textureBits
cvar_t * r_drawBuffer
cvar_t * r_lightMap
render lightmaps only
cvar_t * r_uiFullScreen
ui is running fullscreen
cvar_t * r_shadows
controls shadows: 0 = none, 1 = blur, 2 = stencil, 3 = black planar projection
cvar_t * r_portalSky
cvar_t * r_flares
light flares
cvar_t * r_noBind
turns off binding to appropriate textures
cvar_t * r_singleShader
make most world faces use default shader
cvar_t * r_roundImagesDown
cvar_t * r_colorMipLevels
development aid to see texture mip usage
cvar_t * r_picMip
controls picmip values
cvar_t * r_showTris
enables wireframe rendering of the world
cvar_t * r_trisColor
enables modifying of the wireframe colour (in 0xRRGGBB[AA] format, alpha defaults to FF)
cvar_t * r_showSky
forces sky in front of all surfaces
cvar_t * r_showNormals
draws wireframe normals
cvar_t * r_normalLength
length of the normals
cvar_t * r_finish
cvar_t * r_clear
force screen clear every frame
cvar_t * r_textureMode
cvar_t * r_offsetFactor
cvar_t * r_offsetUnits
cvar_t * r_gamma
cvar_t * r_intensity
cvar_t * r_lockPvs
cvar_t * r_noportals
cvar_t * r_portalOnly
cvar_t * r_subDivisions
cvar_t * r_lodCurveError
cvar_t * r_overBrightBits
cvar_t * r_mapOverBrightBits
cvar_t * r_debugSurface
cvar_t * r_simpleMipMaps
cvar_t * r_showImages
cvar_t * r_ambientScale
cvar_t * r_directedScale
cvar_t * r_debugLight
cvar_t * r_debugSort
cvar_t * r_printShaders
cvar_t * r_cache
cvar_t * r_cacheShaders
cvar_t * r_cacheModels
cvar_t * r_cacheGathering
cvar_t * r_bonesDebug
cvar_t * r_wolfFog
cvar_t * r_screenshotJpegQuality
cvar_t * r_maxPolys
cvar_t * r_maxPolyVerts
cvar_t * r_gfxInfo
Detailed Description
Functions that are not called every frame.
Definition in file tr_init.c.
Function Documentation
refexport_t* GetRefAPI (int apiVersion, refimport_t * rimp)
GetRefAPI.
Parameters
[in] apiVersion
[in] rimp
Returns
Definition at line 1316 of file tr_init.c.
Referenced by CL_InitRef(), and CL_ScaledMilliseconds().
void GfxInfo_f (void) static
GfxInfo_f.
Todo:
: implicit declaration
Definition at line 887 of file tr_init.c.
Referenced by InitOpenGL(), and R_Register().
void GL_CheckErrors (void)
GL_CheckErrors.
Definition at line 220 of file tr_init.c.
void GL_SetDefaultState (void)
GL_SetDefaultState.
Definition at line 843 of file tr_init.c.
static void InitOpenGL (void) static
This function is responsible for initializing a valid OpenGL subsystem.
This is done by calling GLimp_Init (which gives us a working OGL subsystem) then setting variables, checking GL constants, and reporting the gfx system config to the user.
Definition at line 177 of file tr_init.c.
Referenced by R_Init().
void R_DebugPolygon (int color, int numPoints, float * points)
R_DebugPolygon.
Parameters
[in] color
[in] numPoints
[in] points
Definition at line 1776 of file tr_main.c.
Referenced by R_DebugGraphics().
void R_Init (void)
R_Init.
Definition at line 1141 of file tr_init.c.
void R_LevelShot (void)
Levelshots are specialized 128*128 thumbnails for the menu system, sampled down from full screen distorted images.
Definition at line 679 of file tr_init.c.
void R_PurgeCache (void)
Definition at line 1221 of file tr_init.c.
void R_Register (void)
R_Register.
Definition at line 985 of file tr_init.c.
void R_ScreenShot_f (void)
R_ScreenShot_f.
Note
Doesn't print the pacifier message if there is a second arg
screenshot screenshot [silent] screenshot [levelshot] screenshot [filename]
Todo:
: allow multiple format
Definition at line 754 of file tr_init.c.
void R_ScreenshotFilename (int lastNumber, char * fileName, char * ext)
R_ScreenshotFilename.
Parameters
[in] lastNumber
[out] fileName
Definition at line 568 of file tr_init.c.
void R_TakeScreenshot (int x, int y, int width, int height, const char * name, ssFormat_t format)
R_TakeScreenshot.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] name
[in] jpeg
Definition at line 542 of file tr_init.c.
byte* RB_ReadPixels (int x, int y, int width, int height, size_t * offset, int * padlen)
Reads an image but takes care of alignment issues for reading RGB images.
Reads a minimum offset for where the RGB data starts in the image from integer stored at pointer offset. When the function has returned the actual offset was written back to address offset. This address will always have an alignment of packAlign to ensure efficient copying.
Stores the length of padding after a line of pixels to address padlen
Return value must be freed with ri.Hunk_FreeTempMemory()
Parameters
[in] x
[in] y
[in] width
[in] height
[in,out] offset
[in,out] padlen
Returns
Definition at line 300 of file tr_init.c.
byte* RB_ReadZBuffer (int x, int y, int width, int height, int * padlen)
RB_ReadZBuffer.
Parameters
[in] x
[in] y
[in] width
[in,out] height
[in,out] padlen
Returns
Note
Unused
Definition at line 334 of file tr_init.c.
const void* RB_TakeScreenshotCmd (const void * data)
RB_TakeScreenshotCmd.
Parameters
[in] data
Returns
Definition at line 513 of file tr_init.c.
void RB_TakeScreenshotJPEG (int x, int y, int width, int height, char * fileName)
RB_TakeScreenshotJPEG.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] fileName
Definition at line 489 of file tr_init.c.
void RB_TakeScreenshotTGA (int x, int y, int width, int height, const char * fileName)
RB_TakeScreenshotTGA.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] fileName
Definition at line 424 of file tr_init.c.
const void* RB_TakeVideoFrameCmd (const void * data)
RB_TakeVideoFrameCmd.
Parameters
[in] data
Returns
Definition at line 595 of file tr_init.c.
void RE_EndRegistration (void)
Touch all images to make sure they are resident.
Definition at line 1293 of file tr_init.c.
void RE_Shutdown (qboolean destroyWindow)
RE_Shutdown.
Parameters
[in] destroyWindow
Definition at line 1232 of file tr_init.c.
Variable Documentation
glconfig_t glConfig
outside of TR since it shouldn't be cleared during ref re-init
Definition at line 38 of file tr_init.c.
glstate_t glState
outside of TR since it shouldn't be cleared during ref re-init
Definition at line 42 of file tr_init.c.
int maxAnisotropy = 0
Definition at line 40 of file tr_init.c.
cvar_t* r_allowExtensions
global enable/disable of OpenGL extensions
Definition at line 92 of file tr_init.c.
cvar_t* r_ambientScale
Definition at line 146 of file tr_init.c.
Referenced by R_DlightBmodel(), and R_SetupEntityLighting().
cvar_t* r_bonesDebug
Definition at line 159 of file tr_init.c.
cvar_t* r_cache
Definition at line 153 of file tr_init.c.
cvar_t* r_cacheGathering
Definition at line 157 of file tr_init.c.
cvar_t* r_cacheModels
Definition at line 155 of file tr_init.c.
cvar_t* r_cacheShaders
Definition at line 154 of file tr_init.c.
cvar_t* r_clear
force screen clear every frame
Definition at line 125 of file tr_init.c.
cvar_t* r_colorMipLevels
development aid to see texture mip usage
Definition at line 116 of file tr_init.c.
cvar_t* r_debugLight
Definition at line 148 of file tr_init.c.
Referenced by R_DlightBmodel(), and R_SetupEntityLighting().
cvar_t* r_debugSort
Definition at line 149 of file tr_init.c.
cvar_t* r_debugSurface
Definition at line 141 of file tr_init.c.
cvar_t* r_detailTextures
enables/disables detail texturing stages
Definition at line 62 of file tr_init.c.
cvar_t* r_directedScale
Definition at line 147 of file tr_init.c.
Referenced by R_DlightBmodel().
cvar_t* r_drawBuffer
Definition at line 107 of file tr_init.c.
cvar_t* r_drawEntities
disable/enable entity rendering
Definition at line 81 of file tr_init.c.
cvar_t* r_drawFoliage
disable/enable foliage rendering
Definition at line 83 of file tr_init.c.
cvar_t* r_drawSun
controls drawing of sun quad "0" no sun "1" draw sun "2" also draw lens flare effect centered on sun
Definition at line 74 of file tr_init.c.
cvar_t* r_drawWorld
disable/enable world rendering
Definition at line 82 of file tr_init.c.
cvar_t* r_dynamicLight
dynamic lights enabled/disabled
Definition at line 75 of file tr_init.c.
cvar_t* r_extCompressedTextures
Definition at line 94 of file tr_init.c.
cvar_t* r_extMaxAnisotropy
Definition at line 99 of file tr_init.c.
cvar_t* r_extMultitexture
Todo:
: not used in GLES ! move it ?
Definition at line 95 of file tr_init.c.
cvar_t* r_extTextureEnvAdd
Todo:
: not used in GLES ! move it ?
Definition at line 96 of file tr_init.c.
cvar_t* r_extTextureFilterAnisotropic
Todo:
: not used in GLES ! move it ?
Definition at line 98 of file tr_init.c.
cvar_t* r_facePlaneCull
enables culling of planar surfaces with back side test
Definition at line 88 of file tr_init.c.
cvar_t* r_fastSky
controls whether sky should be cleared or drawn
Definition at line 73 of file tr_init.c.
cvar_t* r_finish
Definition at line 124 of file tr_init.c.
cvar_t* r_flareFade
Definition at line 53 of file tr_init.c.
cvar_t* r_flares
light flares
Definition at line 112 of file tr_init.c.
cvar_t* r_flareSize
Definition at line 52 of file tr_init.c.
cvar_t* r_gamma
Todo:
: use in sdl only !
Definition at line 129 of file tr_init.c.
cvar_t* r_gfxInfo
Definition at line 168 of file tr_init.c.
cvar_t* r_greyScale
Definition at line 69 of file tr_init.c.
cvar_t* r_ignore
used for debugging anything
Definition at line 60 of file tr_init.c.
cvar_t* r_ignoreFastPath
allows us to ignore our Tess fast paths
Definition at line 58 of file tr_init.c.
cvar_t* r_ignoreGLErrors
Definition at line 101 of file tr_init.c.
cvar_t* r_intensity
Definition at line 130 of file tr_init.c.
cvar_t* r_lightMap
render lightmaps only
Todo:
: not used in GLES ! move it ?
: "extern int maxAnisotropy" founded
Definition at line 108 of file tr_init.c.
cvar_t* r_lockPvs
Definition at line 131 of file tr_init.c.
cvar_t* r_lodBias
push/pull LOD transitions
Definition at line 77 of file tr_init.c.
cvar_t* r_lodCurveError
Definition at line 136 of file tr_init.c.
cvar_t* r_lodScale
Definition at line 78 of file tr_init.c.
cvar_t* r_logFile
number of frames to emit GL logs
Definition at line 102 of file tr_init.c.
cvar_t* r_mapOverBrightBits
Definition at line 139 of file tr_init.c.
cvar_t* r_maxPolys
Todo:
: both!
Definition at line 165 of file tr_init.c.
cvar_t* r_maxPolyVerts
Definition at line 166 of file tr_init.c.
cvar_t* r_measureOverdraw
enables stencil buffer overdraw measurement
Definition at line 71 of file tr_init.c.
cvar_t* r_noBind
turns off binding to appropriate textures
Todo:
: not used in GLES ! move it ?
Definition at line 113 of file tr_init.c.
cvar_t* r_noCull
Definition at line 87 of file tr_init.c.
cvar_t* r_noCurves
Definition at line 90 of file tr_init.c.
cvar_t* r_noportals
Definition at line 132 of file tr_init.c.
cvar_t* r_noreFresh
bypasses the ref rendering
Definition at line 80 of file tr_init.c.
cvar_t* r_normalLength
length of the normals
Definition at line 122 of file tr_init.c.
cvar_t* r_noVis
disable/enable usage of PVS
Definition at line 86 of file tr_init.c.
cvar_t* r_offsetFactor
Definition at line 127 of file tr_init.c.
cvar_t* r_offsetUnits
Definition at line 128 of file tr_init.c.
cvar_t* r_overBrightBits
Definition at line 138 of file tr_init.c.
cvar_t* r_picMip
controls picmip values
Definition at line 117 of file tr_init.c.
cvar_t* r_portalOnly
Definition at line 133 of file tr_init.c.
cvar_t* r_portalSky
Definition at line 111 of file tr_init.c.
cvar_t* r_primitives
"0" = based on compiled vertex array existance "1" = glDrawElemet tristrips "2" = glDrawElements triangles "-1" = no drawing
Definition at line 104 of file tr_init.c.
cvar_t* r_printShaders
Definition at line 150 of file tr_init.c.
cvar_t* r_railSegmentLength
Definition at line 56 of file tr_init.c.
cvar_t* r_railWidth
Definition at line 55 of file tr_init.c.
cvar_t* r_roundImagesDown
Definition at line 115 of file tr_init.c.
cvar_t* r_screenshotJpegQuality
Definition at line 163 of file tr_init.c.
cvar_t* r_shadows
controls shadows: 0 = none, 1 = blur, 2 = stencil, 3 = black planar projection
Definition at line 110 of file tr_init.c.
cvar_t* r_showCluster
Definition at line 89 of file tr_init.c.
cvar_t* r_showImages
Definition at line 144 of file tr_init.c.
cvar_t* r_showNormals
draws wireframe normals
Definition at line 121 of file tr_init.c.
cvar_t* r_showSky
forces sky in front of all surfaces
Definition at line 120 of file tr_init.c.
cvar_t* r_showTris
enables wireframe rendering of the world
Definition at line 118 of file tr_init.c.
cvar_t* r_simpleMipMaps
Definition at line 142 of file tr_init.c.
cvar_t* r_singleShader
make most world faces use default shader
Definition at line 114 of file tr_init.c.
cvar_t* r_skipBackEnd
Definition at line 67 of file tr_init.c.
cvar_t* r_speeds
various levels of information display
Definition at line 84 of file tr_init.c.
cvar_t* r_subDivisions
Definition at line 135 of file tr_init.c.
cvar_t* r_textureBits
number of desired texture bits 0 = use framebuffer depth 16 = use 16-bit textures 32 = use 32-bit textures all else = error
Definition at line 105 of file tr_init.c.
cvar_t* r_textureMode
Definition at line 126 of file tr_init.c.
cvar_t* r_trisColor
enables modifying of the wireframe colour (in 0xRRGGBB[AA] format, alpha defaults to FF)
Definition at line 119 of file tr_init.c.
cvar_t* r_uiFullScreen
ui is running fullscreen
Definition at line 109 of file tr_init.c.
cvar_t* r_wolfFog
Definition at line 161 of file tr_init.c.
cvar_t* r_zFar
far Z clip plane
Definition at line 65 of file tr_init.c.
cvar_t* r_zNear
near Z clip plane
Definition at line 64 of file tr_init.c.
qboolean textureFilterAnisotropic = qfalse
Definition at line 39 of file tr_init.c.