ET: Legacy: src/luasql/ls_sqlite3.c File Reference
ls_sqlite3.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "sqlite3.h"
#include "lua.h"
#include "lauxlib.h"
#include "luasql.h"
Data Structures
struct env_data
struct conn_data
struct cur_data
Macros
#define LUASQL_ENVIRONMENT_SQLITE "SQLite3 environment"
#define LUASQL_CONNECTION_SQLITE "SQLite3 connection"
#define LUASQL_CURSOR_SQLITE "SQLite3 cursor"
Functions
LUASQL_API int luaopen_luasql_sqlite3 (lua_State *L)
static env_data * getenvironment (lua_State *L)
static conn_data * getconnection (lua_State *L)
static cur_data * getcursor (lua_State *L)
static void cur_nullify (lua_State *L, cur_data *cur)
static int finalize (lua_State *L, cur_data *cur)
static void push_column (lua_State *L, sqlite3_stmt *vm, int column)
static int cur_fetch (lua_State *L)
static int cur_gc (lua_State *L)
static int cur_close (lua_State *L)
static int cur_getcolnames (lua_State *L)
static int cur_getcoltypes (lua_State *L)
static int create_cursor (lua_State *L, int o, conn_data *conn, sqlite3_stmt *sql_vm, int numcols)
static int conn_gc (lua_State *L)
static int conn_close (lua_State *L)
static int conn_escape (lua_State *L)
static int conn_execute (lua_State *L)
static int conn_commit (lua_State *L)
static int conn_rollback (lua_State *L)
static int conn_getlastautoid (lua_State *L)
static int conn_setautocommit (lua_State *L)
static int create_connection (lua_State *L, int env, sqlite3 *sql_conn)
static int env_connect (lua_State *L)
static int env_gc (lua_State *L)
static int env_close (lua_State *L)
static void create_metatables (lua_State *L)
static int create_environment (lua_State *L)
Macro Definition Documentation
#define LUASQL_CONNECTION_SQLITE "SQLite3 connection"
Definition at line 23 of file ls_sqlite3.c.
Referenced by conn_close(), conn_gc(), create_connection(), create_metatables(), and getconnection().
#define LUASQL_CURSOR_SQLITE "SQLite3 cursor"
Definition at line 24 of file ls_sqlite3.c.
Referenced by create_cursor(), create_metatables(), cur_close(), cur_gc(), and getcursor().
#define LUASQL_ENVIRONMENT_SQLITE "SQLite3 environment"
Definition at line 22 of file ls_sqlite3.c.
Referenced by create_environment(), create_metatables(), env_close(), env_gc(), and getenvironment().
Function Documentation
static int conn_close (lua_State * L) static
Definition at line 345 of file ls_sqlite3.c.
Referenced by create_metatables().
static int conn_commit (lua_State * L) static
Definition at line 430 of file ls_sqlite3.c.
Referenced by create_metatables().
static int conn_escape (lua_State * L) static
Definition at line 359 of file ls_sqlite3.c.
Referenced by create_metatables().
static int conn_execute (lua_State * L) static
Definition at line 380 of file ls_sqlite3.c.
Referenced by create_metatables().
static int conn_gc (lua_State * L) static
Definition at line 325 of file ls_sqlite3.c.
Referenced by conn_close(), and create_metatables().
static int conn_getlastautoid (lua_State * L) static
Definition at line 481 of file ls_sqlite3.c.
Referenced by create_metatables().
static int conn_rollback (lua_State * L) static
Definition at line 458 of file ls_sqlite3.c.
Referenced by create_metatables().
static int conn_setautocommit (lua_State * L) static
Definition at line 494 of file ls_sqlite3.c.
Referenced by create_metatables().
static int create_connection (lua_State * L, int env, sqlite3 * sql_conn) static
Definition at line 526 of file ls_sqlite3.c.
Referenced by env_connect().
static int create_cursor (lua_State * L, int o, conn_data * conn, sqlite3_stmt * sql_vm, int numcols) static
Definition at line 278 of file ls_sqlite3.c.
Referenced by conn_execute().
static int create_environment (lua_State * L) static
Definition at line 663 of file ls_sqlite3.c.
Referenced by luaopen_luasql_sqlite3().
static void create_metatables (lua_State * L) static
Definition at line 627 of file ls_sqlite3.c.
Referenced by luaopen_luasql_sqlite3().
static int cur_close (lua_State * L) static
Definition at line 236 of file ls_sqlite3.c.
Referenced by create_metatables().
static int cur_fetch (lua_State * L) static
Definition at line 160 of file ls_sqlite3.c.
Referenced by create_metatables().
static int cur_gc (lua_State * L) static
Definition at line 220 of file ls_sqlite3.c.
Referenced by create_metatables().
static int cur_getcolnames (lua_State * L) static
Definition at line 254 of file ls_sqlite3.c.
Referenced by create_metatables().
static int cur_getcoltypes (lua_State * L) static
Definition at line 265 of file ls_sqlite3.c.
Referenced by create_metatables().
static void cur_nullify (lua_State * L, cur_data * cur) static
Definition at line 90 of file ls_sqlite3.c.
Referenced by cur_close(), cur_gc(), and finalize().
static int env_close (lua_State * L) static
Definition at line 599 of file ls_sqlite3.c.
Referenced by create_metatables().
static int env_connect (lua_State * L) static
Definition at line 546 of file ls_sqlite3.c.
Referenced by create_metatables().
static int env_gc (lua_State * L) static
Definition at line 587 of file ls_sqlite3.c.
Referenced by create_metatables(), and env_close().
static int finalize (lua_State * L, cur_data * cur) static
Definition at line 112 of file ls_sqlite3.c.
Referenced by cur_fetch().
static conn_data* getconnection (lua_State * L) static
Definition at line 69 of file ls_sqlite3.c.
Referenced by conn_commit(), conn_execute(), conn_getlastautoid(), conn_rollback(), and conn_setautocommit().
static cur_data* getcursor (lua_State * L) static
Definition at line 80 of file ls_sqlite3.c.
Referenced by cur_fetch(), cur_getcolnames(), and cur_getcoltypes().
static env_data* getenvironment (lua_State * L) static
Definition at line 58 of file ls_sqlite3.c.
Referenced by env_connect().
LUASQL_API int luaopen_luasql_sqlite3 (lua_State * L)
Definition at line 678 of file ls_sqlite3.c.
Referenced by G_LuaStartVM().
static void push_column (lua_State * L, sqlite3_stmt * vm, int column) static
Definition at line 126 of file ls_sqlite3.c.
Referenced by cur_fetch().