ET: Legacy: src/luasql/luasql.c File Reference
luasql.c File Reference
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "luasql.h"
Data Structures
struct pseudo_data
Macros
#define lua_pushliteral(L, s) lua_pushstring(L, "" s, (sizeof(s)/sizeof(char))-1)
Functions
LUASQL_API int luasql_faildirect (lua_State *L, const char *err)
LUASQL_API int luasql_failmsg (lua_State *L, const char *err, const char *m)
static int luasql_tostring (lua_State *L)
void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUASQL_API int luasql_createmeta (lua_State *L, const char *name, const luaL_Reg *methods)
LUASQL_API void luasql_setmeta (lua_State *L, const char *name)
LUASQL_API void luasql_set_info (lua_State *L)
Macro Definition Documentation
#define lua_pushliteral (L, s) lua_pushstring(L, "" s, (sizeof(s)/sizeof(char))-1)
Definition at line 15 of file luasql.c.
Referenced by conn_commit(), conn_rollback(), conn_setautocommit(), luaopen_luasql_sqlite3(), luasql_createmeta(), luasql_faildirect(), luasql_failmsg(), and luasql_set_info().
Function Documentation
void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 69 of file luasql.c.
Referenced by luaopen_luasql_sqlite3(), and luasql_createmeta().
LUASQL_API int luasql_createmeta (lua_State * L, const char * name, const luaL_Reg * methods)
Definition at line 86 of file luasql.c.
Referenced by create_metatables().
LUASQL_API int luasql_faildirect (lua_State * L, const char * err)
Definition at line 23 of file luasql.c.
Referenced by conn_execute(), env_connect(), and finalize().
LUASQL_API int luasql_failmsg (lua_State * L, const char * err, const char * m)
Definition at line 37 of file luasql.c.
LUASQL_API void luasql_set_info (lua_State * L)
Definition at line 123 of file luasql.c.
Referenced by luaopen_luasql_sqlite3().
LUASQL_API void luasql_setmeta (lua_State * L, const char * name)
Definition at line 114 of file luasql.c.
Referenced by create_connection(), create_cursor(), and create_environment().
static int luasql_tostring (lua_State * L) static
Definition at line 53 of file luasql.c.
Referenced by luasql_createmeta().