ET: Legacy: src/qcommon/md4.c File Reference
md4.c File Reference
#include "q_shared.h"
Data Structures
struct MD4_CTX
Macros
#define S11 3
#define S12 7
#define S13 11
#define S14 19
#define S21 3
#define S22 5
#define S23 9
#define S24 13
#define S31 3
#define S32 9
#define S33 11
#define S34 15
#define F(x, y, z) (((x) & (y)) | ((~x) & (z)))
#define G(x, y, z) (((x) & (y)) | ((x) & (z)) | ((y) & (z)))
#define H(x, y, z) ((x) ^ (y) ^ (z))
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32 - (n))))
#define FF(a, b, c, d, x, s) { (a) += F((b), (c), (d)) + (x); (a) = ROTATE_LEFT((a), (s)); }
#define GG(a, b, c, d, x, s) { (a) += G((b), (c), (d)) + (x) + (UINT4)0x5a827999; (a) = ROTATE_LEFT((a), (s)); }
#define HH(a, b, c, d, x, s) { (a) += H((b), (c), (d)) + (x) + (UINT4)0x6ed9eba1; (a) = ROTATE_LEFT((a), (s)); }
Typedefs
typedef unsigned char * POINTER
typedef unsigned short int UINT2
typedef unsigned int UINT4
Functions
void MD4Init (MD4_CTX *)
void MD4Update (MD4_CTX *, const unsigned char *, unsigned int)
void MD4Final (unsigned char[16], MD4_CTX *)
static void MD4Transform (UINT4[4], const unsigned char[64])
static void Encode (unsigned char *, UINT4 *, unsigned int)
static void Decode (UINT4 *, const unsigned char *, unsigned int)
unsigned int Com_BlockChecksum (void *buffer, size_t length)
unsigned int Com_BlockChecksumKey (void *buffer, int length, int key)
Variables
static unsigned char PADDING [64]
Macro Definition Documentation
#define F (x, y, z) (((x) & (y)) | ((~x) & (z)))
Definition at line 117 of file md4.c.
#define FF (a, b, c, d, x, s) { (a) += F((b), (c), (d)) + (x); (a) = ROTATE_LEFT((a), (s)); }
Definition at line 126 of file md4.c.
Referenced by MD4Transform().
#define G (x, y, z) (((x) & (y)) | ((x) & (z)) | ((y) & (z)))
Definition at line 118 of file md4.c.
#define GG (a, b, c, d, x, s) { (a) += G((b), (c), (d)) + (x) + (UINT4)0x5a827999; (a) = ROTATE_LEFT((a), (s)); }
Definition at line 128 of file md4.c.
Referenced by MD4Transform().
#define H (x, y, z) ((x) ^ (y) ^ (z))
Definition at line 119 of file md4.c.
#define HH (a, b, c, d, x, s) { (a) += H((b), (c), (d)) + (x) + (UINT4)0x6ed9eba1; (a) = ROTATE_LEFT((a), (s)); }
Definition at line 130 of file md4.c.
Referenced by MD4Transform().
#define ROTATE_LEFT (x, n) (((x) << (n)) | ((x) >> (32 - (n))))
Definition at line 122 of file md4.c.
#define S11 3
Definition at line 94 of file md4.c.
Referenced by MD4Transform().
#define S12 7
Definition at line 95 of file md4.c.
Referenced by MD4Transform().
#define S13 11
Definition at line 96 of file md4.c.
Referenced by MD4Transform().
#define S14 19
Definition at line 97 of file md4.c.
Referenced by MD4Transform().
#define S21 3
Definition at line 98 of file md4.c.
Referenced by MD4Transform().
#define S22 5
Definition at line 99 of file md4.c.
Referenced by MD4Transform().
#define S23 9
Definition at line 100 of file md4.c.
Referenced by MD4Transform().
#define S24 13
Definition at line 101 of file md4.c.
Referenced by MD4Transform().
#define S31 3
Definition at line 102 of file md4.c.
Referenced by MD4Transform().
#define S32 9
Definition at line 103 of file md4.c.
Referenced by MD4Transform().
#define S33 11
Definition at line 104 of file md4.c.
Referenced by MD4Transform().
#define S34 15
Definition at line 105 of file md4.c.
Referenced by MD4Transform().
Typedef Documentation
typedef unsigned char* POINTER
Definition at line 46 of file md4.c.
typedef unsigned short int UINT2
Definition at line 49 of file md4.c.
typedef unsigned int UINT4
Definition at line 52 of file md4.c.
Function Documentation
unsigned int Com_BlockChecksum (void * buffer, size_t length)
Definition at line 306 of file md4.c.
Referenced by CM_Checksum(), CM_LoadMap(), CM_LumpChecksum(), FS_CalcModHashes(), FS_LoadZipFile(), and GLSL_GenerateCheckSum().
unsigned int Com_BlockChecksumKey (void * buffer, int length, int key)
Definition at line 321 of file md4.c.
static void Decode (UINT4 * output, const unsigned char * input, unsigned int len) static
Definition at line 296 of file md4.c.
Referenced by MD4Transform().
static void Encode (unsigned char * output, UINT4 * input, unsigned int len) static
Definition at line 281 of file md4.c.
Referenced by MD4Final().
void MD4Final (unsigned char digest[16], MD4_CTX * context)
Definition at line 185 of file md4.c.
Referenced by Com_BlockChecksum(), and Com_BlockChecksumKey().
void MD4Init (MD4_CTX * context)
Definition at line 134 of file md4.c.
Referenced by Com_BlockChecksum(), and Com_BlockChecksumKey().
static void MD4Transform (UINT4 state[4], const unsigned char block[64]) static
Definition at line 210 of file md4.c.
Referenced by MD4Update().
void MD4Update (MD4_CTX * context, const unsigned char * input, unsigned int inputLen)
Definition at line 146 of file md4.c.
Referenced by Com_BlockChecksum(), Com_BlockChecksumKey(), and MD4Final().
Variable Documentation
unsigned char PADDING[64] static
Initial value:
=
{
    0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
}
Definition at line 111 of file md4.c.
Referenced by MD4Final().