ET: Legacy: src/qcommon/net_ip.c File Reference
net_ip.c File Reference
#include "q_shared.h"
#include "qcommon.h"
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/time.h>
#include <unistd.h>
#include <ifaddrs.h>
Data Structures
struct nip_localaddr_t
Macros
#define INVALID_SOCKET -1
#define SOCKET_ERROR -1
#define closesocket close
#define ioctlsocket ioctl
#define socketError errno
#define NET_MULTICAST_IP6 "ff04::696f:7175:616b:6533"
#define IF_NAMESIZE 16
#define MAX_IPS 32
Typedefs
typedef int SOCKET
Functions
char * NET_ErrorString (void)
NET_ErrorString.
static void NetadrToSockadr (netadr_t *a, struct sockaddr *s)
NetadrToSockadr.
static void SockadrToNetadr (struct sockaddr *s, netadr_t *a)
SockadrToNetadr.
static struct addrinfo * SearchAddrInfo (struct addrinfo *hints, sa_family_t family)
static qboolean Sys_StringToSockaddr (const char *s, struct sockaddr *sadr, int sadr_len, sa_family_t family)
Sys_StringToSockaddr.
static void Sys_SockaddrToString (char *dest, size_t destlen, struct sockaddr *input)
Copies ANSI host name into dest of address familiy IPv4 or IPv6.
qboolean Sys_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
Sys_StringToAdr.
qboolean NET_CompareBaseAdrMask (netadr_t a, netadr_t b, int netmask)
Compare without port, and up to the bit number given in netmask.
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
Compares ip addresses without the port.
const char * NET_AdrToStringNoPort (netadr_t a)
NET_AdrToStringNoPort.
const char * NET_AdrToString (netadr_t a)
Returns address & port.
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
NET_CompareAdr.
qboolean NET_IsLocalAddress (netadr_t adr)
NET_IsLocalAddress.
qboolean NET_IsLocalAddressString (const char *address)
NET_IsLocalAddressString.
qboolean NET_GetPacket (netadr_t *net_from, msg_t *net_message, fd_set *fdr)
Receive one packet.
void Sys_SendPacket (int length, const void *data, netadr_t to)
Sys_SendPacket.
qboolean Sys_IsLANAddress (netadr_t adr)
LAN clients will have their rate var ignored.
void Sys_ShowIP (void)
Sys_ShowIP.
int NET_IPSocket (const char *net_interface, int port, int *err)
NET_IPSocket.
int NET_IP6Socket (const char *net_interface, int port, struct sockaddr_in6 *bindto, int *err)
NET_IP6Socket.
void NET_SetMulticast6 (void)
Set the current multicast group.
void NET_JoinMulticast6 (void)
Join an ipv6 multicast group.
void NET_LeaveMulticast6 (void)
NET_LeaveMulticast6.
void NET_OpenSocks (int port)
NET_OpenSocks.
static void NET_AddLocalAddress (const char *ifname, struct sockaddr *addr, struct sockaddr *netmask)
NET_AddLocalAddress.
static void NET_GetLocalAddress (void)
NET_GetLocalAddress.
void NET_OpenIP (void)
NET_OpenIP.
static qboolean NET_GetCvars (void)
NET_GetCvars.
static void NET_Config (qboolean enableNetworking)
NET_Config.
void NET_Init (void)
NET_Init.
void NET_Shutdown (void)
NET_Shutdown.
void NET_Event (fd_set *fdr)
Called from NET_Sleep which uses select() to determine which sockets have seen action.
void NET_Sleep (int msec)
Sleeps msec or until something happens on the network.
void NET_Restart_f (void)
NET_Restart_f.
Variables
static qboolean usingSocks = qfalse
static qboolean networkingEnabled = qfalse
static cvar_t * net_enabled
static cvar_t * net_socksEnabled
static cvar_t * net_socksServer
static cvar_t * net_socksPort
static cvar_t * net_socksUsername
static cvar_t * net_socksPassword
static cvar_t * net_ip
static cvar_t * net_port
static cvar_t * net_ip6
static cvar_t * net_port6
static cvar_t * net_mcast6addr
static cvar_t * net_mcast6iface
static cvar_t * net_dropsim
static struct sockaddr socksRelayAddr
static SOCKET ip_socket = INVALID_SOCKET
static SOCKET socks_socket = INVALID_SOCKET
static SOCKET ip6_socket = INVALID_SOCKET
static SOCKET multicast6_socket = INVALID_SOCKET
static struct ipv6_mreq curgroup
static struct sockaddr_in6 boundto
static nip_localaddr_t localIP [MAX_IPS]
static int numIP
static char socksBuf [4096]
Macro Definition Documentation
#define closesocket close
Definition at line 108 of file net_ip.c.
Referenced by NET_Config(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), and NET_LeaveMulticast6().
#define IF_NAMESIZE 16
Definition at line 156 of file net_ip.c.
#define INVALID_SOCKET -1
Definition at line 106 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), NET_LeaveMulticast6(), NET_OpenIP(), NET_OpenSocks(), NET_Sleep(), and Sys_SendPacket().
#define ioctlsocket ioctl
Definition at line 109 of file net_ip.c.
Referenced by NET_IP6Socket(), and NET_IPSocket().
#define MAX_IPS 32
Definition at line 159 of file net_ip.c.
Referenced by NET_AddLocalAddress().
#define NET_MULTICAST_IP6 "ff04::696f:7175:616b:6533"
Definition at line 152 of file net_ip.c.
Referenced by NET_GetCvars().
#define SOCKET_ERROR -1
Definition at line 107 of file net_ip.c.
Referenced by NET_GetLocalAddress(), NET_GetPacket(), NET_IP6Socket(), NET_IPSocket(), NET_OpenSocks(), NET_Sleep(), and Sys_SendPacket().
#define socketError errno
Definition at line 110 of file net_ip.c.
Referenced by NET_ErrorString(), NET_GetPacket(), NET_IP6Socket(), NET_IPSocket(), and Sys_SendPacket().
Typedef Documentation
typedef int SOCKET
Definition at line 105 of file net_ip.c.
Function Documentation
static void NET_AddLocalAddress (const char * ifname, struct sockaddr * addr, struct sockaddr * netmask) static
NET_AddLocalAddress.
Parameters
[in] ifname
[in] addr
[in] netmask
Definition at line 1612 of file net_ip.c.
Referenced by NET_GetLocalAddress().
const char* NET_AdrToString (netadr_t a)
Returns address & port.
Parameters
[in] a
Returns
Definition at line 647 of file net_ip.c.
Referenced by CL_Connect_f(), CL_ConnectionlessPacket(), CL_GetPing(), CL_GlobalServers_f(), CL_PacketEvent(), CL_RequestMotd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), Com_CheckAutoUpdate(), Com_GetAutoUpdate(), Com_UpdateInfoPacket(), LAN_GetServerAddressString(), LAN_GetServerInfo(), NET_GetPacket(), Netchan_Process(), SV_CheckDRDoS(), SV_ConnectionlessPacket(), SV_DirectConnect(), SV_GetChallenge(), SV_isClientIPValidToConnect(), SV_isValidClient(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SV_Status_f(), SV_UserinfoChanged(), SVC_BucketForAddress(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
const char* NET_AdrToStringNoPort (netadr_t a)
NET_AdrToStringNoPort.
Parameters
[in] a
Returns
Definition at line 602 of file net_ip.c.
Referenced by NET_AdrToString().
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
NET_CompareAdr.
Parameters
[in] a
[in] b
Returns
Definition at line 686 of file net_ip.c.
Referenced by CL_ConnectionlessPacket(), CL_DisconnectPacket(), CL_GetServerStatus(), CL_MotdPacket(), CL_PacketEvent(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus(), CL_ServerStatusResponse(), CL_SetServerInfoByAddress(), CL_UpdateVisiblePings_f(), Com_CheckUpdateStarted(), Com_InitUpdateDownloads(), Com_UpdateInfoPacket(), Com_UpdatePacketEvent(), LAN_AddServer(), LAN_RemoveServer(), LAN_ServerIsInFavoriteList(), SV_DirectConnect(), SV_DropClient(), SV_GetChallenge(), and SV_TempBanIsBanned().
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
Compares ip addresses without the port.
Parameters
[in] a
[in] b
Returns
Definition at line 592 of file net_ip.c.
Referenced by NET_CompareAdr(), SV_CheckDRDoS(), SV_DirectConnect(), and SV_PacketEvent().
qboolean NET_CompareBaseAdrMask (netadr_t a, netadr_t b, int netmask)
Compare without port, and up to the bit number given in netmask.
Parameters
[in] a
[in] b
[in] netmask
Returns
Definition at line 504 of file net_ip.c.
Referenced by NET_CompareBaseAdr().
static void NET_Config (qboolean enableNetworking) static
NET_Config.
Parameters
[in] enableNetworking
Definition at line 1922 of file net_ip.c.
Referenced by NET_Init(), NET_Restart_f(), and NET_Shutdown().
char* NET_ErrorString (void)
NET_ErrorString.
Returns
Definition at line 180 of file net_ip.c.
Referenced by NET_AddLocalAddress(), NET_GetPacket(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), NET_OpenSocks(), NET_Sleep(), and Sys_SendPacket().
void NET_Event (fd_set * fdr)
Called from NET_Sleep which uses select() to determine which sockets have seen action.
Parameters
fdr
Definition at line 2065 of file net_ip.c.
Referenced by NET_Sleep().
static qboolean NET_GetCvars (void) static
NET_GetCvars.
Returns
Definition at line 1840 of file net_ip.c.
Referenced by NET_Config().
static void NET_GetLocalAddress (void) static
NET_GetLocalAddress.
Definition at line 1694 of file net_ip.c.
Referenced by NET_AddLocalAddress(), and NET_OpenIP().
qboolean NET_GetPacket (netadr_t * net_from, msg_t * net_message, fd_set * fdr)
Receive one packet.
Parameters
[in,out] net_from
[in,out] net_message
[in] fdr
Returns
Definition at line 742 of file net_ip.c.
Referenced by NET_Event().
void NET_Init (void)
NET_Init.
Definition at line 2022 of file net_ip.c.
Referenced by main().
int NET_IP6Socket (const char * net_interface, int port, struct sockaddr_in6 * bindto, int * err)
NET_IP6Socket.
Parameters
[in] net_interface
[in] port
[in] bindto
[out] err
Returns
Definition at line 1198 of file net_ip.c.
Referenced by NET_JoinMulticast6(), and NET_OpenIP().
int NET_IPSocket (const char * net_interface, int port, int * err)
NET_IPSocket.
Parameters
[in] net_interface
[in] port
[out] err
Returns
Definition at line 1102 of file net_ip.c.
Referenced by NET_OpenIP().
qboolean NET_IsLocalAddress (netadr_t adr)
NET_IsLocalAddress.
Parameters
[in] adr
Returns
Definition at line 717 of file net_ip.c.
Referenced by CL_Connect_f(), SV_DirectConnect(), SV_isClientIPValidToConnect(), and SV_UserinfoChanged().
qboolean NET_IsLocalAddressString (const char * address)
NET_IsLocalAddressString.
Parameters
[in] address
Returns
Definition at line 727 of file net_ip.c.
Referenced by LAN_AddServer().
void NET_JoinMulticast6 (void)
Join an ipv6 multicast group.
Definition at line 1327 of file net_ip.c.
void NET_LeaveMulticast6 (void)
NET_LeaveMulticast6.
Definition at line 1382 of file net_ip.c.
void NET_OpenIP (void)
NET_OpenIP.
Definition at line 1761 of file net_ip.c.
Referenced by NET_Config().
void NET_OpenSocks (int port)
NET_OpenSocks.
Parameters
[in] port
Definition at line 1404 of file net_ip.c.
Referenced by NET_OpenIP().
void NET_Restart_f (void)
NET_Restart_f.
Definition at line 2162 of file net_ip.c.
Referenced by NET_Init().
void NET_SetMulticast6 (void)
Set the current multicast group.
Definition at line 1294 of file net_ip.c.
Referenced by NET_Config().
void NET_Shutdown (void)
NET_Shutdown.
Definition at line 2046 of file net_ip.c.
Referenced by __attribute__().
void NET_Sleep (int msec)
Sleeps msec or until something happens on the network.
Parameters
[in] msec
Definition at line 2106 of file net_ip.c.
Referenced by Com_Frame().
static void NetadrToSockadr (netadr_t * a, struct sockaddr * s) static
NetadrToSockadr.
Parameters
[in] a
[out] s
Definition at line 242 of file net_ip.c.
Referenced by NET_AdrToStringNoPort(), and Sys_SendPacket().
static struct addrinfo* SearchAddrInfo (struct addrinfo * hints, sa_family_t family) static
Definition at line 300 of file net_ip.c.
Referenced by Sys_StringToSockaddr().
static void SockadrToNetadr (struct sockaddr * s, netadr_t * a) static
SockadrToNetadr.
Parameters
[in] s
[out] a
Definition at line 280 of file net_ip.c.
Referenced by NET_GetPacket(), and Sys_StringToAdr().
qboolean Sys_IsLANAddress (netadr_t adr)
LAN clients will have their rate var ignored.
IPv4: A LAN client is loopback adapter (localhost/127.0.0.1), a computer of the network this computer is member of or private network from RFC1918: 10.0.0.0 - 10.255.255.255 (10/8 prefix) 172.16.0.0 - 172.31.255.255 (172.16/12 prefix) 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
IPv6: FIXME: docu
This function expects adresses of type NA_IP_4 & 6 ONLY! other types (also NA_BOT) will return qfalse
Parameters
[in] adr
Todo:
docu IPv6
Todo:
? should we check the scope_id here?
Definition at line 974 of file net_ip.c.
Referenced by CL_ReadyToSendPacket(), SV_CheckDRDoS(), SV_DirectConnect(), SV_SendClientMessages(), and SV_UserinfoChanged().
void Sys_SendPacket (int length, const void * data, netadr_t to)
Sys_SendPacket.
Parameters
[in] length
[in] data
[in] to
Definition at line 873 of file net_ip.c.
Referenced by NET_SendPacket().
void Sys_ShowIP (void)
Sys_ShowIP.
Definition at line 1071 of file net_ip.c.
Referenced by CL_ShowIP_f(), NET_AddLocalAddress(), and NET_GetLocalAddress().
static void Sys_SockaddrToString (char * dest, size_t destlen, struct sockaddr * input) static
Copies ANSI host name into dest of address familiy IPv4 or IPv6.
Parameters
[out] dest
[in] destlen
[in] input
Definition at line 439 of file net_ip.c.
Referenced by NET_AdrToStringNoPort(), and Sys_ShowIP().
qboolean Sys_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
Sys_StringToAdr.
Parameters
[in] s
[in] a
[in] family
Returns
Definition at line 469 of file net_ip.c.
Referenced by NET_StringToAdr().
static qboolean Sys_StringToSockaddr (const char * s, struct sockaddr * sadr, int sadr_len, sa_family_t family) static
Sys_StringToSockaddr.
Parameters
[in] s
[out] sadr
[in] sadr_len
[in] family
Returns
Definition at line 324 of file net_ip.c.
Referenced by NET_IP6Socket(), NET_IPSocket(), NET_SetMulticast6(), and Sys_StringToAdr().
Variable Documentation
struct sockaddr_in6 boundto static
Definition at line 149 of file net_ip.c.
Referenced by NET_JoinMulticast6(), and NET_OpenIP().
struct ipv6_mreq curgroup static
Definition at line 147 of file net_ip.c.
Referenced by NET_JoinMulticast6(), NET_LeaveMulticast6(), NET_SetMulticast6(), and NetadrToSockadr().
SOCKET ip6_socket = INVALID_SOCKET static
Definition at line 143 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_JoinMulticast6(), NET_LeaveMulticast6(), NET_OpenIP(), NET_Sleep(), and Sys_SendPacket().
SOCKET ip_socket = INVALID_SOCKET static
Definition at line 139 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_OpenIP(), NET_Sleep(), and Sys_SendPacket().
nip_localaddr_t localIP[MAX_IPS] static
Definition at line 171 of file net_ip.c.
SOCKET multicast6_socket = INVALID_SOCKET static
Definition at line 144 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_JoinMulticast6(), and NET_LeaveMulticast6().
cvar_t* net_dropsim static
Definition at line 135 of file net_ip.c.
cvar_t* net_enabled static
Definition at line 117 of file net_ip.c.
cvar_t* net_ip static
Definition at line 125 of file net_ip.c.
cvar_t* net_ip6 static
Definition at line 129 of file net_ip.c.
cvar_t* net_mcast6addr static
Definition at line 131 of file net_ip.c.
cvar_t* net_mcast6iface static
Definition at line 132 of file net_ip.c.
cvar_t* net_port static
Definition at line 126 of file net_ip.c.
cvar_t* net_port6 static
Definition at line 130 of file net_ip.c.
cvar_t* net_socksEnabled static
Definition at line 119 of file net_ip.c.
cvar_t* net_socksPassword static
Definition at line 123 of file net_ip.c.
cvar_t* net_socksPort static
Definition at line 121 of file net_ip.c.
cvar_t* net_socksServer static
Definition at line 120 of file net_ip.c.
cvar_t* net_socksUsername static
Definition at line 122 of file net_ip.c.
qboolean networkingEnabled = qfalse static
Definition at line 115 of file net_ip.c.
Referenced by NET_Config(), NET_Restart_f(), and NET_Shutdown().
int numIP static
Definition at line 172 of file net_ip.c.
Referenced by NET_AddLocalAddress(), Sys_IsLANAddress(), and Sys_ShowIP().
SOCKET socks_socket = INVALID_SOCKET static
Definition at line 140 of file net_ip.c.
Referenced by NET_Config(), and NET_OpenSocks().
char socksBuf[4096] static
Definition at line 865 of file net_ip.c.
Referenced by Sys_SendPacket().
struct sockaddr socksRelayAddr static
Definition at line 137 of file net_ip.c.
Referenced by NET_GetPacket(), NET_OpenSocks(), and Sys_SendPacket().
qboolean usingSocks = qfalse static
Definition at line 114 of file net_ip.c.
Referenced by NET_GetPacket(), NET_OpenSocks(), and Sys_SendPacket().