ET: Legacy: src/qcommon/net_chan.c File Reference
net_chan.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Data Structures
struct loopmsg_t
struct loopback_t
struct delaybuf
Macros
#define MAX_PACKETLEN 1400
max size of a network packet
#define FRAGMENT_SIZE (MAX_PACKETLEN - 100)
#define PACKET_HEADER 10
two ints and a short
#define FRAGMENT_BIT (1U << 31)
#define MAX_LOOPBACK 16
Typedefs
typedef struct delaybuf delaybuf_t
Functions
void Netchan_Init (int port)
Netchan_Init.
void Netchan_Setup (netsrc_t sock, netchan_t *chan, netadr_t adr, int qport)
Called to open a channel to a remote system.
void Netchan_TransmitNextFragment (netchan_t *chan)
Send one fragment of the current message.
void Netchan_Transmit (netchan_t *chan, int length, const byte *data)
Sends a message to a connection, fragmenting if necessary A 0 length will still generate a packet.
qboolean Netchan_Process (netchan_t *chan, msg_t *msg)
Msg must be large enough to hold MAX_MSGLEN, because if this is the final fragment of a multi-part message, the entire thing will be copied out.
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t *net_from, msg_t *net_message)
NET_GetLoopPacket.
void NET_SendLoopPacket (netsrc_t sock, int length, const void *data, netadr_t to)
NET_SendLoopPacket.
void NET_SendPacket (netsrc_t sock, int length, const void *data, netadr_t to)
NET_SendPacket.
void QDECL NET_OutOfBandPrint (netsrc_t sock, netadr_t adr, const char *format,...)
Sends a text message in an out-of-band datagram.
void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, const char *format, int len)
Sends a data message in an out-of-band datagram (only used for "connect")
int NET_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
Traps "localhost" for loopback, passes everything else to system.
Variables
cvar_t * showpackets
cvar_t * showdrop
cvar_t * qport
static const char * netsrcString [2]
loopback_t loopbacks [2]
cvar_t * sv_packetloss
cvar_t * sv_packetdelay
cvar_t * cl_packetloss
cvar_t * cl_packetdelay
static delaybuf_t * sv_delaybuf_head = NULL
static delaybuf_t * sv_delaybuf_tail = NULL
static delaybuf_t * cl_delaybuf_head = NULL
static delaybuf_t * cl_delaybuf_tail = NULL
Macro Definition Documentation
#define FRAGMENT_BIT (1U << 31)
Definition at line 64 of file net_chan.c.
Referenced by Netchan_Process(), and Netchan_TransmitNextFragment().
#define FRAGMENT_SIZE (MAX_PACKETLEN - 100)
Definition at line 61 of file net_chan.c.
Referenced by Netchan_Process(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
#define MAX_LOOPBACK 16
=============================================================================
LOOPBACK BUFFERS FOR LOCAL PLAYER
There needs to be enough loopback messages to hold a complete gamestate of maximum size
Definition at line 415 of file net_chan.c.
Referenced by NET_GetLoopPacket(), and NET_SendLoopPacket().
#define MAX_PACKETLEN 1400
max size of a network packet
Definition at line 59 of file net_chan.c.
Referenced by Netchan_Transmit(), and Netchan_TransmitNextFragment().
#define PACKET_HEADER 10
two ints and a short
Definition at line 62 of file net_chan.c.
Typedef Documentation
typedef struct delaybuf delaybuf_t
Definition at line 502 of file net_chan.c.
Function Documentation
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t * net_from, msg_t * net_message)
NET_GetLoopPacket.
Parameters
[in] sock
[out] net_from
[out] net_message
Returns
Definition at line 444 of file net_chan.c.
Referenced by Com_EventLoop().
void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, const char * format, int len)
Sends a data message in an out-of-band datagram (only used for "connect")
Parameters
[in] sock
[in] adr
[in] format
[in] len
Definition at line 702 of file net_chan.c.
Referenced by CL_CheckForResend().
void QDECL NET_OutOfBandPrint (netsrc_t sock, netadr_t adr, const char * format, ...)
Sends a text message in an out-of-band datagram.
Parameters
[in] sock
[in] adr
[in] format
Definition at line 675 of file net_chan.c.
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_GlobalServers_f(), CL_Ping_f(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), CL_UpdateVisiblePings_f(), Com_CheckAutoUpdate(), SV_DirectConnect(), SV_FlushRedirect(), SV_GetChallenge(), SV_isValidClient(), SV_IsValidUserinfo(), SV_MasterHeartbeat(), SVC_Info(), and SVC_Status().
void NET_SendLoopPacket (netsrc_t sock, int length, const void * data, netadr_t to)
NET_SendLoopPacket.
Parameters
[in] sock
[in] length
[in] data
to - unused
Definition at line 479 of file net_chan.c.
Referenced by NET_SendPacket().
void NET_SendPacket (netsrc_t sock, int length, const void * data, netadr_t to)
NET_SendPacket.
Parameters
[in] sock
[in] length
[in] data
[in] to
Definition at line 526 of file net_chan.c.
Referenced by CL_LocalServers_f(), CL_Rcon_f(), NET_OutOfBandData(), NET_OutOfBandPrint(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
int NET_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
Traps "localhost" for loopback, passes everything else to system.
Parameters
[in] s
[in,out] a
[in] family
Returns
0 on address not found, 1 on address found with port, 2 on address found without port.
Definition at line 733 of file net_chan.c.
Referenced by CL_Connect_f(), CL_GlobalServers_f(), CL_MapLoading(), CL_Ping_f(), CL_Rcon_f(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), Com_CheckAutoUpdate(), LAN_AddServer(), LAN_RemoveServer(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_MasterGameCompleteStatus(), and SV_MasterHeartbeat().
void Netchan_Init (int port)
Netchan_Init.
Parameters
[in] port
Definition at line 80 of file net_chan.c.
Referenced by Com_Init().
qboolean Netchan_Process (netchan_t * chan, msg_t * msg)
Msg must be large enough to hold MAX_MSGLEN, because if this is the final fragment of a multi-part message, the entire thing will be copied out.
Parameters
[in,out] chan
[in,out] msg
Returns
qfalse if the message should not be processed due to being out of order or a fragment.
Definition at line 239 of file net_chan.c.
Referenced by CL_Netchan_Process(), and SV_Netchan_Process().
void Netchan_Setup (netsrc_t sock, netchan_t * chan, netadr_t adr, int qport)
Called to open a channel to a remote system.
Parameters
[in] sock
[out] chan
[in] adr
[in] qport
Definition at line 95 of file net_chan.c.
Referenced by CL_ConnectionlessPacket(), and SV_DirectConnect().
void Netchan_Transmit (netchan_t * chan, int length, const byte * data)
Sends a message to a connection, fragmenting if necessary A 0 length will still generate a packet.
Parameters
[in,out] chan
[in] length
[in] data
Definition at line 174 of file net_chan.c.
Referenced by CL_Netchan_Transmit(), SV_Netchan_Transmit(), and SV_Netchan_TransmitNextInQueue().
void Netchan_TransmitNextFragment (netchan_t * chan)
Send one fragment of the current message.
Parameters
[in,out] chan
Definition at line 110 of file net_chan.c.
Referenced by CL_Netchan_TransmitNextFragment(), Netchan_Transmit(), and SV_Netchan_TransmitNextFragment().
Variable Documentation
delaybuf_t* cl_delaybuf_head = NULL static
Definition at line 515 of file net_chan.c.
Referenced by NET_SendPacket().
delaybuf_t* cl_delaybuf_tail = NULL static
Definition at line 516 of file net_chan.c.
Referenced by NET_SendPacket().
cvar_t* cl_packetdelay
Definition at line 112 of file cl_main.c.
Referenced by NET_SendLoopPacket().
cvar_t* cl_packetloss
Definition at line 111 of file cl_main.c.
Referenced by NET_SendLoopPacket().
loopback_t loopbacks[2]
Definition at line 435 of file net_chan.c.
const char* netsrcString[2] static
Initial value:
=
{
    "client",
    "server"
}
Definition at line 70 of file net_chan.c.
Referenced by Netchan_Process(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
cvar_t* qport
Definition at line 68 of file net_chan.c.
Referenced by Com_Init(), Netchan_Setup(), SV_DirectConnect(), and SV_PacketEvent().
cvar_t* showdrop
Definition at line 67 of file net_chan.c.
cvar_t* showpackets
Definition at line 66 of file net_chan.c.
delaybuf_t* sv_delaybuf_head = NULL static
Definition at line 512 of file net_chan.c.
Referenced by NET_SendPacket().
delaybuf_t* sv_delaybuf_tail = NULL static
Definition at line 513 of file net_chan.c.
Referenced by NET_SendPacket().
cvar_t* sv_packetdelay
Definition at line 126 of file common.c.
Referenced by NET_SendLoopPacket().
cvar_t* sv_packetloss
Definition at line 85 of file sv_main.c.
Referenced by NET_SendLoopPacket(), and SV_Init().