ET: Legacy: src/null/null_input.c File Reference
null_input.c File Reference
#include "../client/client.h"
Functions
void IN_Init (void)
IN_Init.
void IN_Frame (void)
IN_Frame.
void IN_Shutdown (void)
IN_Shutdown.
void IN_MouseEvent (int mstate)
IN_MouseEvent.
void IN_Activate (qboolean active)
IN_Activate.
void IN_Restart (void)
IN_Restart.
Function Documentation
void IN_Activate (qboolean active)
IN_Activate.
Parameters
active
Note
Unused
Definition at line 74 of file null_input.c.
void IN_Frame (void)
IN_Frame.
Definition at line 47 of file null_input.c.
Referenced by Com_Frame().
void IN_Init (void)
IN_Init.
Definition at line 40 of file null_input.c.
Referenced by CL_InitRef(), and GLimp_Init().
void IN_MouseEvent (int mstate)
IN_MouseEvent.
Parameters
mstate
Note
Unused
Definition at line 64 of file null_input.c.
void IN_Restart (void)
IN_Restart.
Definition at line 81 of file null_input.c.
Referenced by CL_InitRef(), GLimp_EndFrame(), and Sys_In_Restart_f().
void IN_Shutdown (void)
IN_Shutdown.
Definition at line 54 of file null_input.c.
Referenced by CL_InitRef(), GLimp_Shutdown(), and Sys_Error().