ET: Legacy: src/null/null_snddma.c File Reference
null_snddma.c File Reference
All other sound mixing is portable.
#include "../client/client.h"
Functions
qboolean SNDDMA_Init (void)
SNDDMA_Init.
int SNDDMA_GetDMAPos (void)
SNDDMA_GetDMAPos.
void SNDDMA_Shutdown (void)
SNDDMA_Shutdown.
void SNDDMA_BeginPainting (void)
SNDDMA_BeginPainting.
void SNDDMA_Submit (void)
SNDDMA_Submit.
sfxHandle_t S_RegisterSound (const char *name, qboolean compressed)
S_RegisterSound.
void S_StartLocalSound (sfxHandle_t sfxHandle, int channelNum, int volume)
S_StartLocalSound.
void S_ClearSoundBuffer (qboolean killStreaming)
S_ClearSoundBuffer.
int S_GetSoundLength (sfxHandle_t sfxHandle)
S_GetSoundLength.
void S_UpdateThread (void)
S_UpdateThread.
void S_AddLoopSounds (void)
S_AddLoopSounds.
Detailed Description
All other sound mixing is portable.
Definition in file null_snddma.c.
Function Documentation
void S_AddLoopSounds (void)
S_AddLoopSounds.
Todo:
TODO: empty
Definition at line 134 of file null_snddma.c.
void S_ClearSoundBuffer (qboolean killStreaming)
S_ClearSoundBuffer.
Parameters
killStreaming
Definition at line 104 of file null_snddma.c.
int S_GetSoundLength (sfxHandle_t sfxHandle)
S_GetSoundLength.
Returns how long the sound lasts in milliseconds.
Parameters
sfxHandle
Returns
Definition at line 113 of file null_snddma.c.
Referenced by FloatAsInt(), and SV_GameSystemCalls().
sfxHandle_t S_RegisterSound (const char * name, qboolean compressed)
S_RegisterSound.
Parameters
name
compressed
Returns
Note
bk001119 - added boolean flag, match client/snd_public.h
Definition at line 85 of file null_snddma.c.
Referenced by FloatAsInt(), and SV_GameSystemCalls().
void S_StartLocalSound (sfxHandle_t sfxHandle, int channelNum, int volume)
S_StartLocalSound.
Parameters
sfxHandle
channelNum
volume
Definition at line 96 of file null_snddma.c.
void S_UpdateThread (void)
S_UpdateThread.
Note
Unused
Definition at line 125 of file null_snddma.c.
void SNDDMA_BeginPainting (void)
SNDDMA_BeginPainting.
Definition at line 66 of file null_snddma.c.
int SNDDMA_GetDMAPos (void)
SNDDMA_GetDMAPos.
Returns
Definition at line 51 of file null_snddma.c.
qboolean SNDDMA_Init (void)
SNDDMA_Init.
Returns
Definition at line 42 of file null_snddma.c.
void SNDDMA_Shutdown (void)
SNDDMA_Shutdown.
Definition at line 59 of file null_snddma.c.
void SNDDMA_Submit (void)
SNDDMA_Submit.
Definition at line 73 of file null_snddma.c.