ET: Legacy: src/qcommon/q_math.c File Reference
q_math.c File Reference
Stateless support routines that are included in each code module.
#include "q_shared.h"
Functions
int Q_rand (int *seed)
Q_rand.
float Q_random (int *seed)
Q_random.
float Q_crandom (int *seed)
Q_crandom.
signed char ClampChar (int i)
ClampChar.
byte ClampByte (int i)
ClampByte.
void ClampColor (vec4_t color)
ClampColor.
int DirToByte (vec3_t dir)
DirToByte.
void ByteToDir (int b, vec3_t dir)
ByteToDir.
unsigned ColorBytes4 (float r, float g, float b, float a)
ColorBytes4.
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
PlaneFromPoints.
void RotatePoint (vec3_t point, vec3_t matrix[3])
RotatePoint.
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
RotatePointAroundVector.
void RotateAroundDirection (vec3_t axis[3], float yaw)
RotateAroundDirection.
void CreateRotationMatrix (const vec3_t angles, vec3_t matrix[3])
CreateRotationMatrix.
void vec3_to_angles (const vec3_t value1, vec3_t angles)
vec3_to_angles
void angles_to_axis (const vec3_t angles, vec3_t axis[3])
angles_to_axis
void axis_clear (axis_t axis)
axis_clear
void axis_copy (axis_t in, axis_t out)
axis_copy
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
ProjectPointOnPlane.
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
Given a normalized forward vector, create two other perpendicular vectors.
void vec3_rotate (const vec3_t in, vec3_t matrix[3], vec3_t out)
vec3_rotate
float Q_rsqrt (float f)
Q_rsqrt.
float Q_fabs (float f)
Q_fabs.
float angle_lerp (float from, float to, float frac)
angle_lerp
void vec3_lerp (vec3_t start, vec3_t end, float frac, vec3_t out)
vec3_lerp
float angle_sub (float a1, float a2)
angle_sub
void angles_sub (vec3_t v1, vec3_t v2, vec3_t v3)
angles_sub
float angle_mod (float a)
angle_mod
float angle_norm_360 (float angle)
angle_norm_360
float angle_norm_180 (float angle)
angle_norm_180
float angle_delta (float angle1, float angle2)
angle_delta
void SetPlaneSignbits (struct cplane_s *out)
SetPlaneSignbits.
__inline __declspec (naked)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s *p)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
RadiusFromBounds.
void ClearBounds (vec3_t mins, vec3_t maxs)
ClearBounds.
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
AddPointToBounds.
void BoundsAdd (vec3_t mins, vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
BoundsAdd.
qboolean vec3_compare (const vec3_t v1, const vec3_t v2)
vec3_compare
vec_t vec3_norm (vec3_t v)
vec3_norm
void vec3_norm_fast (vec3_t v)
fast vector normalize routine that does not check to make sure that length != 0, nor does it return length
vec_t vec3_norm2 (const vec3_t v, vec3_t out)
vec3_norm2
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
_VectorMA
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
_DotProduct
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
_VectorSubtract
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
_VectorAdd
void _VectorCopy (const vec3_t in, vec3_t out)
_VectorCopy
void _VectorScale (const vec3_t in, vec_t scale, vec3_t out)
_VectorScale
void vec3_cross (const vec3_t v1, const vec3_t v2, vec3_t cross)
vec3_cross
vec_t vec3_length (const vec3_t v)
vec3_length
vec_t vec3_length_squared (const vec3_t v)
vec3_length_squared
vec_t vec3_distance (const vec3_t p1, const vec3_t p2)
vec3_distance
vec_t vec3_distance_squared (const vec3_t p1, const vec3_t p2)
vec3_distance_squared
void vec3_inv (vec3_t v)
vec3_inv
void _MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
_MatrixMultiply
void mat3_transpose (vec3_t matrix[3], vec3_t transpose[3])
mat3_transpose
void angles_vectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
angles_vectors
void vec3_per (const vec3_t src, vec3_t dst)
vec3_per
void GetPerpendicularViewVector (const vec3_t point, const vec3_t p1, const vec3_t p2, vec3_t up)
Used to find an "up" vector for drawing a sprite so that it always faces the view as best as possible.
void ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
ProjectPointOntoVector.
void ProjectPointOntoVectorBounded (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
ProjectPointOntoVectorBounded.
float DistanceFromLineSquared (vec3_t p, vec3_t lp1, vec3_t lp2)
DistanceFromLineSquared.
float DistanceFromVectorSquared (vec3_t p, vec3_t lp1, vec3_t lp2)
DistanceFromVectorSquared.
float vec3_to_yawn (const vec3_t vec)
vec3_to_yawn
void axis_to_angles (axis_t axis, vec3_t angles)
Used to convert the MD3 tag axis to MDC tag angles, which are much smaller.
float vec3_dist (vec3_t v1, vec3_t v2)
vec3_dist
float vec3_dist_squared (vec3_t v1, vec3_t v2)
vec3_dist_squared
int Q_isnan (float x)
Don't pass doubles to this.
float Q_acos (float c)
The msvc acos doesn't always return a value between -PI and PI:
void quat_from_mat4 (quat_t q, const mat4_t m)
quat_from_mat4
void quat_from_angles (quat_t q, vec_t pitch, vec_t yaw, vec_t roll)
quat_from_angles
void quat_to_vec3_FLU (const quat_t q, vec3_t forward, vec3_t left, vec3_t up)
quat_to_vec3_FLU
void quat_to_vec3_FRU (const quat_t q, vec3_t forward, vec3_t right, vec3_t up)
quat_to_vec3_FRU
void quat_to_axis (const quat_t q, vec3_t axis[3])
quat_to_axis
vec_t quat_norm (quat_t q)
quat_norm
void quat_slerp (const quat_t from, const quat_t to, float frac, quat_t out)
quat_slerp
qboolean mat4_compare (const mat4_t a, const mat4_t b)
mat4_compare
void mat4_copy (const mat4_t in, mat4_t out)
mat4_copy
void MatrixOrthogonalProjection (mat4_t m, vec_t left, vec_t right, vec_t bottom, vec_t top, vec_t nearvec, vec_t farvec)
replacement for glOrtho see glspec30.pdf chapter 2.12 Coordinate Transformations
void mat4_transform_vec4 (const mat4_t m, const vec4_t in, vec4_t out)
mat4_transform_vec4
void mat4_reset_translate (mat4_t m, vec_t x, vec_t y, vec_t z)
mat4_reset_translate
void mat4_reset_translate_vec3 (mat4_t m, vec3_t position)
mat4_reset_translate_vec3
void mat4_reset_scale (mat4_t m, vec_t x, vec_t y, vec_t z)
mat4_reset_scale
void mat4_mult (const mat4_t a, const mat4_t b, mat4_t out)
mat4_mult
void mat4_mult_self (mat4_t m, const mat4_t m2)
mat4_mult_self
void mat4_ident (mat4_t m)
mat4_ident
void mat4_transform_vec3 (const mat4_t m, const vec3_t in, vec3_t out)
mat4_transform_vec3
void mat4_transform_vec3_self (const mat4_t m, vec3_t inout)
mat4_transform_vec3_self
void mat4_transpose (const mat4_t in, mat4_t out)
mat4_transpose
void mat4_from_quat (mat4_t m, const quat_t q)
mat4_from_quat
void MatrixFromVectorsFLU (mat4_t m, const vec3_t forward, const vec3_t left, const vec3_t up)
MatrixFromVectorsFLU.
void MatrixSetupTransformFromVectorsFLU (mat4_t m, const vec3_t forward, const vec3_t left, const vec3_t up, const vec3_t origin)
MatrixSetupTransformFromVectorsFLU.
void MatrixToVectorsFLU (const mat4_t m, vec3_t forward, vec3_t left, vec3_t up)
MatrixToVectorsFLU.
void MatrixSetupTransformFromVectorsFRU (mat4_t m, const vec3_t forward, const vec3_t right, const vec3_t up, const vec3_t origin)
MatrixSetupTransformFromVectorsFRU.
void MatrixToVectorsFRU (const mat4_t m, vec3_t forward, vec3_t right, vec3_t up)
MatrixToVectorsFRU.
qboolean mat4_inverse (const mat4_t in, mat4_t out)
Based on gluInvertMatrix.
qboolean mat4_inverse_self (mat4_t matrix)
mat4_inverse_self
void mat4_from_angles (mat4_t m, vec_t pitch, vec_t yaw, vec_t roll)
mat4_from_angles
Variables
vec3_t vec3_origin = { 0, 0, 0 }
vec3_t axisDefault [3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } }
vec4_t colorBlack = { 0, 0, 0, 1 }
vec4_t colorRed = { 1, 0, 0, 1 }
vec4_t colorGreen = { 0, 1, 0, 1 }
vec4_t colorBlue = { 0, 0, 1, 1 }
vec4_t colorYellow = { 1, 1, 0, 1 }
vec4_t colorOrange = { 1, 0.5, 0, 1 }
vec4_t colorMagenta = { 1, 0, 1, 1 }
vec4_t colorCyan = { 0, 1, 1, 1 }
vec4_t colorWhite = { 1, 1, 1, 1 }
vec4_t colorLtGrey = { 0.75, 0.75, 0.75, 1 }
vec4_t colorMdGrey = { 0.5, 0.5, 0.5, 1 }
vec4_t colorDkGrey = { 0.25, 0.25, 0.25, 1 }
vec4_t colorMdRed = { 0.5, 0, 0, 1 }
vec4_t colorMdGreen = { 0, 0.5, 0, 1 }
vec4_t colorDkGreen = { 0, 0.20f, 0, 1 }
vec4_t colorMdCyan = { 0, 0.5, 0.5, 1 }
vec4_t colorMdYellow = { 0.5, 0.5, 0, 1 }
vec4_t colorMdOrange = { 0.5, 0.25, 0, 1 }
vec4_t colorMdBlue = { 0, 0, 0.5, 1 }
vec4_t clrBrown = { 0.68f, 0.68f, 0.56f, 1.f }
vec4_t clrBrownDk = { 0.58f * 0.75f, 0.58f * 0.75f, 0.46f * 0.75f, 1.f }
vec4_t clrBrownLine = { 0.0525f, 0.05f, 0.025f, 0.2f }
vec4_t clrBrownLineFull = { 0.0525f, 0.05f, 0.025f, 1.f }
vec4_t clrBrownTextLt2 = { 108 * 1.8f / 255.f, 88 * 1.8f / 255.f, 62 * 1.8f / 255.f, 1.f }
vec4_t clrBrownTextLt = { 108 * 1.3f / 255.f, 88 * 1.3f / 255.f, 62 * 1.3f / 255.f, 1.f }
vec4_t clrBrownText = { 108 / 255.f, 88 / 255.f, 62 / 255.f, 1.f }
vec4_t clrBrownTextDk = { 20 / 255.f, 2 / 255.f, 0 / 255.f, 1.f }
vec4_t clrBrownTextDk2 = { 108 * 0.75f / 255.f, 88 * 0.75f / 255.f, 62 * 0.75f / 255.f, 1.f }
vec4_t g_color_table [32]
vec3_t bytedirs [NUMVERTEXNORMALS]
Detailed Description
Stateless support routines that are included in each code module.
Definition in file q_math.c.
Function Documentation
__inline __declspec (naked)
Definition at line 1086 of file q_math.c.
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
_DotProduct
Parameters
[in] v1
[in] v2
Returns
Definition at line 1594 of file q_math.c.
void _MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
_MatrixMultiply
Parameters
[in] in1
[in] in2
[out] out
Definition at line 1762 of file q_math.c.
Referenced by SV_GameSystemCalls().
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
_VectorAdd
Parameters
[in] veca
[in] vecb
[out] out
Definition at line 1618 of file q_math.c.
void _VectorCopy (const vec3_t in, vec3_t out)
_VectorCopy
Parameters
[in] in
[out] out
Definition at line 1630 of file q_math.c.
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
_VectorMA
Parameters
[in] veca
[in] scale
[in] vecb
[out] vecc
Definition at line 1581 of file q_math.c.
void _VectorScale (const vec3_t in, vec_t scale, vec3_t out)
_VectorScale
Parameters
[in] in
[in] scale
[out] out
Definition at line 1643 of file q_math.c.
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
_VectorSubtract
Parameters
[in] veca
[in] vecb
[out] out
Definition at line 1605 of file q_math.c.
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
AddPointToBounds.
Parameters
[in] v
[in,out] mins
[in,out] maxs
Definition at line 1379 of file q_math.c.
Referenced by CM_GeneratePatchCollide(), HandleEntsThatBlockConstructible(), MergeInteractionBounds(), ParseFace(), ParseFoliage(), ParseTriSurf(), R_AddBSPModelSurfaces(), R_AddPolygonInteractions(), R_AddPolysToScene(), R_CreateSubModelVBOs(), R_CreateSurfaceGridMesh(), R_CullLightTriangle(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MarkFragments(), R_SetParent(), R_SetupLightLocalBounds(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RE_AddPolyBufferToScene(), RE_AddPolysToScene(), RE_AddPolyToScene(), RE_BuildSkeleton(), RE_ProjectDecal(), and Think_SpawnNewDoorTrigger().
float angle_delta (float angle1, float angle2)
angle_delta
Parameters
[in] angle1
[in] angle2
Returns
the normalized delta from angle1 to angle2
Definition at line 934 of file q_math.c.
float angle_lerp (float from, float to, float frac)
angle_lerp
Parameters
[in] from
[in] to
[in] frac
Returns
Definition at line 820 of file q_math.c.
float angle_mod (float a)
angle_mod
Parameters
[in] a
Returns
Definition at line 888 of file q_math.c.
float angle_norm_180 (float angle)
angle_norm_180
Parameters
[in] angle
Returns
angle normalized to the range [-180 < angle <= 180]
Definition at line 918 of file q_math.c.
Referenced by angle_delta(), and axis_to_angles().
float angle_norm_360 (float angle)
angle_norm_360
Parameters
[in] angle
Returns
angle normalized to the range [0 <= angle < 360]
Definition at line 908 of file q_math.c.
Referenced by angle_norm_180().
float angle_sub (float a1, float a2)
angle_sub
Parameters
[in] a1
[in] a2
Returns
Always returns a value from -180 to 180
Definition at line 855 of file q_math.c.
Referenced by angles_sub().
void angles_sub (vec3_t v1, vec3_t v2, vec3_t v3)
angles_sub
Parameters
[in] v1
[in] v2
[out] v3
Definition at line 876 of file q_math.c.
void angles_to_axis (const vec3_t angles, vec3_t axis[3])
angles_to_axis
Parameters
[in] angles
[in,out] axis
Definition at line 668 of file q_math.c.
void angles_vectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
angles_vectors
Parameters
[in] angles
[out] forward
[out] right
[out] up
Definition at line 1812 of file q_math.c.
Referenced by angles_to_axis(), CM_TransformedPointContents(), CreateRotationMatrix(), isEntVisible(), SV_BuildClientSnapshot(), and SV_GameSystemCalls().
void axis_clear (axis_t axis)
axis_clear
Parameters
[out] axis
Definition at line 681 of file q_math.c.
void axis_copy (axis_t in, axis_t out)
axis_copy
Parameters
[in] in
[out] out
Definition at line 699 of file q_math.c.
void axis_to_angles (axis_t axis, vec3_t angles)
Used to convert the MD3 tag axis to MDC tag angles, which are much smaller.
This doesn't have to be fast, since it's only used for conversion in utils, try to avoid using this during gameplay
Parameters
[in] axis
[out] angles
Definition at line 2058 of file q_math.c.
void BoundsAdd (vec3_t mins, vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
BoundsAdd.
Parameters
[in,out] mins
[in,out] maxs
[in] mins2
[in] maxs2
Definition at line 1457 of file q_math.c.
Referenced by R_CreateClusters(), R_CreateVBOLightMeshes(), R_CreateVBOShadowMeshes(), R_inPVS(), R_SetParent(), and RB_RenderInteractionsShadowMapped().
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s * p)
Definition at line 1316 of file q_math.c.
Referenced by CM_BoxLeafnums_r(), InsideViewFrustum(), MergeInteractionBounds(), R_AddWorldSurfaces(), R_BoxSurfaces_r(), R_CalcLightCubeSideBits(), R_CoherentHierachicalCulling(), R_CullBox(), R_CullLightWorldBounds(), R_RecursiveAddInteractionNode(), R_RecursiveInteractionNode(), R_RecursivePrecacheInteractionNode(), R_RecursiveWorldNode(), R_SetupLightScissor(), R_ShadowFrustumCullWorldBounds(), RB_RenderEntityOcclusionQueries(), and SetPlaneSignbits().
void ByteToDir (int b, vec3_t dir)
ByteToDir.
Parameters
[in] b
[out] dir
Definition at line 345 of file q_math.c.
Referenced by CG_EntityEvent(), and CG_Portal().
byte ClampByte (int i)
ClampByte.
Parameters
[in] i
Returns
Definition at line 271 of file q_math.c.
Referenced by CIN_DecodeQuadCodebook(), and R_CreateBuiltinImages().
signed char ClampChar (int i)
ClampChar.
Parameters
[in] i
Returns
Definition at line 234 of file q_math.c.
Referenced by CL_JoystickMove(), CL_KeyMove(), and CL_MouseMove().
void ClampColor (vec4_t color)
ClampColor.
Parameters
[in,out] color
Definition at line 290 of file q_math.c.
void ClearBounds (vec3_t mins, vec3_t maxs)
ClearBounds.
Parameters
[in,out] mins
[in,out] maxs
Definition at line 1367 of file q_math.c.
Referenced by CM_GeneratePatchCollide(), MergeInteractionBounds(), ParseFace(), ParseFoliage(), ParseTriSurf(), R_AddBSPModelSurfaces(), R_AddPolygonInteractions(), R_AddWorldSurfaces(), R_CreateClusters(), R_CreateSubModelVBOs(), R_CreateSurfaceGridMesh(), R_CreateVBOLightMeshes(), R_CreateVBOShadowMeshes(), R_CullLightTriangle(), R_inPVS(), R_LoadMD5(), R_LoadMDM(), R_LoadNodesAndLeafs(), R_LoadPSK(), R_MarkFragments(), R_SetParent(), R_SetupLightLocalBounds(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RE_BuildSkeleton(), and RE_ProjectDecal().
unsigned ColorBytes4 (float r, float g, float b, float a)
ColorBytes4.
Parameters
[in] r
[in] g
[in] b
[in] a
Definition at line 381 of file q_math.c.
Referenced by ParseShader(), R_SetFrameFog(), and RE_SetGlobalFog().
void CreateRotationMatrix (const vec3_t angles, vec3_t matrix[3])
CreateRotationMatrix.
Parameters
[in] angles
[in,out] matrix
Definition at line 602 of file q_math.c.
Referenced by CG_AddEntityToTag(), CG_AdjustPositionForMover(), CM_TransformedBoxTrace(), and G_TryPushingEntity().
int DirToByte (vec3_t dir)
DirToByte.
Parameters
[in] dir
Returns
Note
This isn't a real cheap function to call!
Definition at line 315 of file q_math.c.
Referenced by Bullet_Fire_Extended(), Fire_Lead_Ext(), func_explosive_explode(), G_Damage(), G_RealExplodedMissile(), GibEntity(), locateCamera(), Spawn_Junk(), Spawn_Shard(), target_explosion_use(), and Weapon_Knife().
float DistanceFromLineSquared (vec3_t p, vec3_t lp1, vec3_t lp2)
DistanceFromLineSquared.
Parameters
[in] p
[in] lp1
[in] lp2
Returns
Definition at line 1967 of file q_math.c.
Referenced by Bot_EntInvisibleBySmokeBomb().
float DistanceFromVectorSquared (vec3_t p, vec3_t lp1, vec3_t lp2)
DistanceFromVectorSquared.
Parameters
[in] p
[in] lp1
[in] lp2
Returns
Note
Unused
Definition at line 2004 of file q_math.c.
void GetPerpendicularViewVector (const vec3_t point, const vec3_t p1, const vec3_t p2, vec3_t up)
Used to find an "up" vector for drawing a sprite so that it always faces the view as best as possible.
Parameters
[in] point
[in] p1
[in] p2
[out] up
Definition at line 1888 of file q_math.c.
Referenced by CG_AddTrailToScene().
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
Given a normalized forward vector, create two other perpendicular vectors.
Parameters
[in] forward
[in,out] right
[out] up
Definition at line 738 of file q_math.c.
Referenced by CM_Trace(), RB_SurfaceRailRings(), and Tess_SurfaceRailRings().
void mat3_transpose (vec3_t matrix[3], vec3_t transpose[3])
mat3_transpose
Parameters
[in] matrix
[out] transpose
Definition at line 1780 of file q_math.c.
Referenced by CM_TransformedBoxTrace(), and S_Base_Respatialize().
qboolean mat4_compare (const mat4_t a, const mat4_t b)
mat4_compare
Parameters
[in] a
[in] b
Returns
Definition at line 2514 of file q_math.c.
Referenced by GL_LoadModelViewMatrix(), GL_LoadProjectionMatrix(), and GLSL_SetUniformMatrix16().
void mat4_copy (const mat4_t in, mat4_t out)
mat4_copy
Parameters
[in] in
[out] out
Definition at line 2527 of file q_math.c.
Referenced by GL_LoadModelViewMatrix(), GL_LoadProjectionMatrix(), GLSL_SetUniformMatrix16(), mat4_mult_self(), MatrixMultiplyShear(), MatrixMultiplyTranslation(), MatrixMultiplyZRotation(), R_RotateEntityForLight(), R_RotateForViewer(), R_SetupUnprojection(), and RB_RenderInteractionsShadowMapped().
void mat4_from_angles (mat4_t m, vec_t pitch, vec_t yaw, vec_t roll)
mat4_from_angles
Parameters
[out] m
[in] pitch
[in] yaw
[in] roll
Definition at line 3201 of file q_math.c.
Referenced by quat_from_angles(), R_CalcLightCubeSideBits(), R_LoadPSK(), and RB_RenderInteractionsShadowMapped().
void mat4_from_quat (mat4_t m, const quat_t q)
mat4_from_quat
Parameters
[out] m
[in] q
Definition at line 2833 of file q_math.c.
Referenced by MatrixSetupTransformFromQuat(), quat_to_axis(), quat_to_vec3_FLU(), quat_to_vec3_FRU(), QuatTransformVector(), and R_LoadMD5().
void mat4_ident (mat4_t m)
mat4_ident
Parameters
[in] m
Definition at line 2760 of file q_math.c.
Referenced by GL_SetDefaultState(), ParseTexMod(), R_RotateEntityForLight(), R_RotateForViewer(), RB_CalcTexMatrix(), RB_CameraPostFX(), RB_RenderInteractionsShadowMapped(), and Tess_SurfaceMD5().
qboolean mat4_inverse (const mat4_t in, mat4_t out)
Based on gluInvertMatrix.
Parameters
[in] in
[out] out
Returns
Definition at line 3050 of file q_math.c.
Referenced by mat4_inverse_self().
qboolean mat4_inverse_self (mat4_t matrix)
mat4_inverse_self
Parameters
[in,out] matrix
Returns
Definition at line 3189 of file q_math.c.
Referenced by R_LoadMD5(), R_LoadPSK(), and R_SetupUnprojection().
void mat4_mult (const mat4_t a, const mat4_t b, mat4_t out)
mat4_mult
Parameters
[in] a
[in] b
[out] out
Definition at line 2687 of file q_math.c.
Referenced by GL_LoadModelViewMatrix(), GL_LoadProjectionMatrix(), mat4_mult_self(), MatrixMultiplyShear(), MatrixMultiplyTranslation(), MatrixMultiplyZRotation(), R_CalcLightCubeSideBits(), R_ComputeFinalAttenuation(), R_RenderView(), R_RotateEntityForLight(), R_RotateEntityForViewParms(), R_RotateForViewer(), R_RotateLightForViewParms(), RB_DrawSun(), RB_RenderDebugUtils(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), Tess_SurfaceMD5(), and Tess_SurfaceVBOMD5Mesh().
void mat4_mult_self (mat4_t m, const mat4_t m2)
mat4_mult_self
Parameters
[in,out] m
[in,out] m2
Definition at line 2748 of file q_math.c.
Referenced by R_SetupUnprojection(), RB_CalcTexMatrix(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), Render_lightVolume(), Tess_SurfaceMD5(), and Tess_SurfaceVBOMD5Mesh().
void mat4_reset_scale (mat4_t m, vec_t x, vec_t y, vec_t z)
mat4_reset_scale
Parameters
[out] m
[in] x
[in] y
[in] z
Definition at line 2673 of file q_math.c.
Referenced by R_SetupLightProjection(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), Tess_SurfaceMD5(), and Tess_SurfaceVBOMD5Mesh().
void mat4_reset_translate (mat4_t m, vec_t x, vec_t y, vec_t z)
mat4_reset_translate
Parameters
[out] m
[in] x
[in] y
[in] z
Definition at line 2648 of file q_math.c.
Referenced by mat4_reset_translate_vec3(), MatrixMultiplyTranslation(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), and Render_lightVolume().
void mat4_reset_translate_vec3 (mat4_t m, vec3_t position)
mat4_reset_translate_vec3
Parameters
[out] m
[in] position
Definition at line 2661 of file q_math.c.
Referenced by RB_DrawSun().
void mat4_transform_vec3 (const mat4_t m, const vec3_t in, vec3_t out)
mat4_transform_vec3
Parameters
[in] m
[in] in
[out] out
Definition at line 2774 of file q_math.c.
Referenced by R_LocalPointToWorld(), R_SetupLightFrustum(), R_SetupLightOrigin(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), and Tess_SurfaceMD5().
void mat4_transform_vec3_self (const mat4_t m, vec3_t inout)
mat4_transform_vec3_self
Parameters
[in] m
[in,out] inout
Note
Unused
Definition at line 2788 of file q_math.c.
void mat4_transform_vec4 (const mat4_t m, const vec4_t in, vec4_t out)
mat4_transform_vec4
Parameters
[in] m
[in] in
[out] out
Definition at line 2604 of file q_math.c.
Referenced by MergeInteractionBounds(), R_TransformModelToClip(), R_TransformWorldToClip(), RB_RenderDebugUtils(), and RB_RenderInteractionsShadowMapped().
void mat4_transpose (const mat4_t in, mat4_t out)
mat4_transpose
Parameters
[in] in
[out] out
Definition at line 2804 of file q_math.c.
Referenced by Tess_SurfaceVBOMDMMesh().
void MatrixFromVectorsFLU (mat4_t m, const vec3_t forward, const vec3_t left, const vec3_t up)
MatrixFromVectorsFLU.
Parameters
[out] m
[in] forward
[in] left
[in] up
Definition at line 2940 of file q_math.c.
Referenced by RenderEntityOcclusionVolume(), and Tess_SurfaceVBOMDMMesh().
void MatrixOrthogonalProjection (mat4_t m, vec_t left, vec_t right, vec_t bottom, vec_t top, vec_t nearvec, vec_t farvec)
replacement for glOrtho see glspec30.pdf chapter 2.12 Coordinate Transformations
Parameters
[out] m
[in] left
[in] right
[in] bottom
[in] top
[in] nearvec
[in] farvec
Definition at line 2590 of file q_math.c.
Referenced by RB_RenderBloom(), RB_SetGL2D(), and RB_SetViewMVPM().
void MatrixSetupTransformFromVectorsFLU (mat4_t m, const vec3_t forward, const vec3_t left, const vec3_t up, const vec3_t origin)
MatrixSetupTransformFromVectorsFLU.
Parameters
[in] m
[out] forward
[out] left
[out] up
[out] origin
Definition at line 2956 of file q_math.c.
Referenced by R_RotateEntityForLight(), R_RotateEntityForViewParms(), R_RotateForViewer(), R_RotateLightForViewParms(), and RenderEntityOcclusionVolume().
void MatrixSetupTransformFromVectorsFRU (mat4_t m, const vec3_t forward, const vec3_t right, const vec3_t up, const vec3_t origin)
MatrixSetupTransformFromVectorsFRU.
Parameters
[out] m
[in] forward
[in] right
[in] up
[in] origin
Note
Unused
Definition at line 3005 of file q_math.c.
void MatrixToVectorsFLU (const mat4_t m, vec3_t forward, vec3_t left, vec3_t up)
MatrixToVectorsFLU.
Parameters
[in] m
[out] forward
[out] left
[out] up
Definition at line 2971 of file q_math.c.
Referenced by quat_to_axis(), R_DebugAxis(), R_RotateForViewer(), and RB_RenderDebugUtils().
void MatrixToVectorsFRU (const mat4_t m, vec3_t forward, vec3_t right, vec3_t up)
MatrixToVectorsFRU.
Parameters
[in] m
[out] forward
[out] right
[out] up
Definition at line 3020 of file q_math.c.
Referenced by quat_to_vec3_FLU(), quat_to_vec3_FRU(), and Tess_SurfaceAxis().
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
PlaneFromPoints.
Parameters
[in,out] plane
[in] a
[in] b
[in] c
Returns
false if the triangle is degenrate. The normal will point out of the clock for clockwise ordered points
Definition at line 437 of file q_math.c.
Referenced by ProjectDecalOntoWinding(), R_PlaneForSurface(), RE_ProjectDecal(), Tess_AddQuadStampExt2(), and UpdateLightTriangles().
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
ProjectPointOnPlane.
Parameters
[out] dst
[in] p
[in] normal
Definition at line 712 of file q_math.c.
Referenced by vec3_per().
void ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
ProjectPointOntoVector.
Parameters
[in] point
[in] vStart
[in] vEnd
[out] vProj
Definition at line 1909 of file q_math.c.
Referenced by CG_AddFlameSpriteToScene(), CG_AddTrailToScene(), CG_Bleed(), DistanceFromLineSquared(), and DistanceFromVectorSquared().
void ProjectPointOntoVectorBounded (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
ProjectPointOntoVectorBounded.
Parameters
[in] point
[in] vStart
[in] vEnd
[out] vProj
Note
Unused
Definition at line 1930 of file q_math.c.
float Q_acos (float c)
The msvc acos doesn't always return a value between -PI and PI:
int i; i = 1065353246; acos(*(float*) &i) == -1.#IND0
Parameters
[in] c
Returns
Definition at line 2146 of file q_math.c.
Referenced by CL_CgameSystemCalls(), and R_InitSkyTexCoords().
float Q_crandom (int * seed)
Q_crandom.
Parameters
[in] seed
Returns
Definition at line 221 of file q_math.c.
Referenced by CG_Bullet(), and Fire_Lead_Ext().
float Q_fabs (float f)
Q_fabs.
Parameters
[in] f
Returns
Definition at line 802 of file q_math.c.
Referenced by AddLean(), AddSkyPolygon(), AimAtTarget(), BaseWindingForPlane(), CG_AddDebris(), CG_AddFlameToScene(), CG_CalcMoveSpeeds(), CG_DamageBlendBlob(), CG_DrawFlashDamage(), CG_DrawNewCompass(), CG_EntityEffects(), CG_KickAngles(), CG_LimboPanel_RenderCounter_RollTimeForButton(), CG_SwingAngles(), CL_CreateCmd(), clamp_hweapontofirearc(), CM_BoxDistanceFromPlane(), CM_CalcTraceBounds(), CM_DrawDebugSurface(), CM_PlaneEqual(), CM_PositionTestInPatchCollide(), CM_ProjectPointOntoVector(), CM_SnapVector(), CM_Trace(), CM_TraceThroughBounds(), CM_TraceThroughPatchCollide(), DistanceFromLineSquared(), DrawNormals(), DropToFloor(), DynamicLightPass(), DynamicLightPass_scalar(), DynamicLightSinglePass(), FindVertexInHashTable(), G_PushPlayer(), GLimp_CompareModes(), MakeTextureMatrix(), PC_Directive_evalfloat(), PC_DollarDirective_evalfloat(), PM_AdjustAimSpreadScale(), PmoveSingle(), ProjectDecalOntoWinding(), ProjectPointOntoVectorBounded(), ProjectRadius(), Q_ftol(), quat_slerp(), QuatCalcW(), R_CalcBone(), R_CalcBoneLerp(), R_CalcTangentSpace(), R_CalcTangentSpaceFast(), R_CalcTangentVectors(), R_CreateBuiltinImages(), R_FixSharedVertexLodError_r(), R_LoadMD5(), R_LoadMDM(), R_LoadPSK(), R_MarkFragments(), R_MergedHeightPoints(), R_MergedWidthPoints(), R_ProjectDecalOntoSurface(), R_ProjectRadius(), R_StitchPatches(), RadiusFromBounds(), RB_CalcDeformVertexes(), RB_ProjectRadius(), RenderEntityOcclusionVolume(), sEntWillTriggerMine(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_secret(), Touch_DoorTriggerSpectator(), and vec3_per().
int Q_isnan (float x)
Don't pass doubles to this.
Parameters
[in] x
Returns
Definition at line 2122 of file q_math.c.
Referenced by RB_CalculateAdaptation(), and RE_AddRefEntityToScene().
int Q_rand (int * seed)
Q_rand.
Parameters
[in,out] seed
Returns
Definition at line 200 of file q_math.c.
Referenced by Q_random().
float Q_random (int * seed)
Q_random.
Parameters
[in] seed
Returns
Definition at line 211 of file q_math.c.
Referenced by CG_SmokePuff(), and Q_crandom().
float Q_rsqrt (float f)
Q_rsqrt.
Parameters
[in] f
Returns
Definition at line 781 of file q_math.c.
Referenced by Q_ftol(), RB_CalcSpecularAlpha(), and vec3_norm_fast().
void quat_from_angles (quat_t q, vec_t pitch, vec_t yaw, vec_t roll)
quat_from_angles
Parameters
[out] q
[in] pitch
[in] yaw
[in] roll
Note
Unused
Definition at line 2309 of file q_math.c.
void quat_from_mat4 (quat_t q, const mat4_t m)
quat_from_mat4
Parameters
[out] q
[in] m
Definition at line 2174 of file q_math.c.
Referenced by quat_from_angles(), and R_LoadLights().
vec_t quat_norm (quat_t q)
quat_norm
Parameters
[in,out] q
Returns
Definition at line 2386 of file q_math.c.
Referenced by quat_from_mat4(), and RE_BuildSkeleton().
void quat_slerp (const quat_t from, const quat_t to, float frac, quat_t out)
quat_slerp
Parameters
[in] from
[in] to
[in] frac
[out] out
Definition at line 2412 of file q_math.c.
Referenced by RE_BlendSkeleton(), and RE_BuildSkeleton().
void quat_to_axis (const quat_t q, vec3_t axis[3])
quat_to_axis
Parameters
[in] q
[out] axis
Definition at line 2373 of file q_math.c.
Referenced by R_RotateLightForViewParms(), R_SetupLightFrustum(), and RE_LerpTagET().
void quat_to_vec3_FLU (const quat_t q, vec3_t forward, vec3_t left, vec3_t up)
quat_to_vec3_FLU
Parameters
[in] q
[out] forward
[out] left
[out] up
Note
Unused
Definition at line 2345 of file q_math.c.
void quat_to_vec3_FRU (const quat_t q, vec3_t forward, vec3_t right, vec3_t up)
quat_to_vec3_FRU
Parameters
[in] q
[out] forward
[out] right
[out] up
Definition at line 2360 of file q_math.c.
Referenced by RB_RenderDebugUtils().
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
RadiusFromBounds.
Parameters
[in] mins
[in] maxs
Returns
Definition at line 1346 of file q_math.c.
Referenced by BotImport_BSPModelMinsMaxsOrigin(), G_MoverPush(), MergeInteractionBounds(), R_AddBSPModelSurfaces(), R_ComputeLOD(), R_SetupLightLocalBounds(), SP_misc_gamemodel(), and SV_LinkEntity().
void RotateAroundDirection (vec3_t axis[3], float yaw)
RotateAroundDirection.
Parameters
[in,out] axis
[in] yaw
Definition at line 579 of file q_math.c.
Referenced by CG_MakeExplosion(), and CG_Missile().
void RotatePoint (vec3_t point, vec3_t matrix[3])
RotatePoint.
Parameters
[out] point
[in] matrix
Definition at line 458 of file q_math.c.
Referenced by CG_AdjustPositionForMover(), CM_TransformedBoxTrace(), and G_TryPushingEntity().
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
RotatePointAroundVector.
Parameters
[out] dst
[in] dir
[in] point
[in] degrees
Note
This is not implemented very well...
Definition at line 477 of file q_math.c.
Referenced by axis_to_angles(), CG_AddSmokeSprites(), CG_ImpactMark(), func_explosive_explode(), R_GetPortalOrientations(), R_MarkFragments(), RB_RenderDebugUtils(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), RotateAroundDirection(), Tess_SurfaceBeam(), Tess_SurfaceLightningBolt(), and weapon_callAirStrike().
void SetPlaneSignbits (struct cplane_s * out)
SetPlaneSignbits.
Parameters
[in,out] out
Definition at line 945 of file q_math.c.
Referenced by CM_InitBoxHull(), FinishGenericSurface(), R_SetupFrustum(), R_SetupFrustum2(), R_SetupLightFrustum(), and R_SetupSplitFrustums().
qboolean vec3_compare (const vec3_t v1, const vec3_t v2)
vec3_compare
Parameters
[in] v1
[in] v2
Returns
Definition at line 1496 of file q_math.c.
Referenced by SV_LinkEntity().
void vec3_cross (const vec3_t v1, const vec3_t v2, vec3_t cross)
vec3_cross
Parameters
[in] v1
[in] v2
[out] cross
Definition at line 1656 of file q_math.c.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), BotImport_DebugLineShow(), CheckWinding(), CM_AddFacetBevels(), CM_PlaneFromPoints(), GetPerpendicularViewVector(), isEntVisible(), MakeNormalVectors(), PlaneFromPoints(), RotateAroundDirection(), RotatePointAroundVector(), WindingArea(), and WindingPlane().
float vec3_dist (vec3_t v1, vec3_t v2)
vec3_dist
Parameters
[in] v1
[in] v2
Returns
Definition at line 2095 of file q_math.c.
float vec3_dist_squared (vec3_t v1, vec3_t v2)
vec3_dist_squared
Parameters
[in] v1
[in] v2
Returns
Definition at line 2109 of file q_math.c.
vec_t vec3_distance (const vec3_t p1, const vec3_t p2)
vec3_distance
Parameters
[in] p1
[in] p2
Returns
Definition at line 1689 of file q_math.c.
vec_t vec3_distance_squared (const vec3_t p1, const vec3_t p2)
vec3_distance_squared
Parameters
[in] p1
[in] p2
Returns
Definition at line 1703 of file q_math.c.
Referenced by S_Base_AddLoopingSound().
void vec3_inv (vec3_t v)
vec3_inv
Parameters
[in,out] v
Definition at line 1715 of file q_math.c.
Referenced by CreateRotationMatrix().
vec_t vec3_length (const vec3_t v)
vec3_length
Parameters
[in] v
Returns
Definition at line 1668 of file q_math.c.
Referenced by CheckWinding(), CM_NeedsSubdivision(), CM_TraceThroughLeaf(), RadiusFromBounds(), vec3_dist(), vec3_distance(), and WindingArea().
vec_t vec3_length_squared (const vec3_t v)
vec3_length_squared
Parameters
[in] v
Returns
Definition at line 1678 of file q_math.c.
Referenced by CM_ProjectPointOntoVector(), CM_TestInLeaf(), CM_TraceThroughLeaf(), DistanceFromLineSquared(), DistanceFromVectorSquared(), S_Base_AddLoopingSound(), and vec3_dist_squared().
void vec3_lerp (vec3_t start, vec3_t end, float frac, vec3_t out)
vec3_lerp
Parameters
[in] start
[in] end
[in] frac
[out] out
Definition at line 841 of file q_math.c.
vec_t vec3_norm (vec3_t v)
vec3_norm
Parameters
[in] v
Returns
Definition at line 1511 of file q_math.c.
Referenced by CM_AddFacetBevels(), CM_PlaneFromPoints(), CM_Trace(), CM_TraceThroughLeaf(), GetPerpendicularViewVector(), MakeNormalVectors(), PlaneFromPoints(), ProjectPointOntoVector(), ProjectPointOntoVectorBounded(), S_SpatializeOrigin(), and vec3_per().
vec_t vec3_norm2 (const vec3_t v, vec3_t out)
vec3_norm2
Parameters
[in] v
[out] out
Returns
Definition at line 1551 of file q_math.c.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), CheckWinding(), RemoveColinearPoints(), and WindingPlane().
void vec3_norm_fast (vec3_t v)
fast vector normalize routine that does not check to make sure that length != 0, nor does it return length
Parameters
[in,out] v
Definition at line 1534 of file q_math.c.
Referenced by isEntVisible().
void vec3_per (const vec3_t src, vec3_t dst)
vec3_per
Parameters
[in] src assumes is normalized
[out] dst
Definition at line 1855 of file q_math.c.
void vec3_rotate (const vec3_t in, vec3_t matrix[3], vec3_t out)
vec3_rotate
Parameters
[in] in
[in] matrix
[out] out
Definition at line 760 of file q_math.c.
Referenced by CG_Item(), and S_SpatializeOrigin().
void vec3_to_angles (const vec3_t value1, vec3_t angles)
vec3_to_angles
Parameters
[in] value1
[out] angles
Definition at line 613 of file q_math.c.
Referenced by axis_to_angles().
float vec3_to_yawn (const vec3_t vec)
vec3_to_yawn
Parameters
[in] vec
Returns
Definition at line 2018 of file q_math.c.
Variable Documentation
vec3_t axisDefault[3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } }
Definition at line 39 of file q_math.c.
Referenced by axis_to_angles(), CG_AddBloodTrails(), CG_AddDebris(), CG_AddSparks(), CG_Debris(), CG_Effect(), CG_Explodef(), CG_LoseHat(), CG_MachineGunEjectBrass(), CG_PanzerFaustEjectBrass(), CG_RubbleFx(), CG_Shard(), and CG_ShardJunk().
vec3_t bytedirs[NUMVERTEXNORMALS]
Definition at line 108 of file q_math.c.
Referenced by ByteToDir(), CG_AddFragment(), CG_SpawnSmokeSprite(), and DirToByte().
vec4_t clrBrown = { 0.68f, 0.68f, 0.56f, 1.f }
Definition at line 61 of file q_math.c.
vec4_t clrBrownDk = { 0.58f * 0.75f, 0.58f * 0.75f, 0.46f * 0.75f, 1.f }
Definition at line 62 of file q_math.c.
vec4_t clrBrownLine = { 0.0525f, 0.05f, 0.025f, 0.2f }
Definition at line 63 of file q_math.c.
Referenced by CG_DrawGrid().
vec4_t clrBrownLineFull = { 0.0525f, 0.05f, 0.025f, 1.f }
Definition at line 64 of file q_math.c.
vec4_t clrBrownText = { 108 / 255.f, 88 / 255.f, 62 / 255.f, 1.f }
Definition at line 68 of file q_math.c.
vec4_t clrBrownTextDk = { 20 / 255.f, 2 / 255.f, 0 / 255.f, 1.f }
Definition at line 69 of file q_math.c.
vec4_t clrBrownTextDk2 = { 108 * 0.75f / 255.f, 88 * 0.75f / 255.f, 62 * 0.75f / 255.f, 1.f }
Definition at line 70 of file q_math.c.
vec4_t clrBrownTextLt = { 108 * 1.3f / 255.f, 88 * 1.3f / 255.f, 62 * 1.3f / 255.f, 1.f }
Definition at line 67 of file q_math.c.
vec4_t clrBrownTextLt2 = { 108 * 1.8f / 255.f, 88 * 1.8f / 255.f, 62 * 1.8f / 255.f, 1.f }
Definition at line 66 of file q_math.c.
vec4_t colorBlack = { 0, 0, 0, 1 }
Definition at line 41 of file q_math.c.
Referenced by CG_Debriefing_Mission_Draw(), CG_DrawBinocReticle(), CG_DrawConnectScreen(), CG_DrawGrid(), CG_DrawPicShadowed(), CG_DrawScopedReticle(), CG_DrawSkillBar(), CG_LimboPanel_RenderObjectiveText(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadPanel_DrawPin(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RE_StretchRaw(), RE_UploadCinematic(), SCR_DrawStringExt(), Text_Paint_Ext(), Text_PaintWithCursor_Ext(), UI_DrawMapPreview(), UI_Refresh(), and WM_TeamScoreboard().
vec4_t colorBlue = { 0, 0, 1, 1 }
Definition at line 44 of file q_math.c.
Referenced by CG_DrawLagometer(), CG_SpeakerEditor_Back(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerInfo_Text(), DrawTris(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), and Tess_SurfaceAxis().
vec4_t colorCyan = { 0, 1, 1, 1 }
Definition at line 48 of file q_math.c.
Referenced by CG_Debriefing_ChatEdit_Draw(), R_SetupLightFrustum(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), and RenderLightOcclusionVolume().
vec4_t colorDkGreen = { 0, 0.20f, 0, 1 }
Definition at line 55 of file q_math.c.
vec4_t colorDkGrey = { 0.25, 0.25, 0.25, 1 }
Definition at line 52 of file q_math.c.
vec4_t colorGreen = { 0, 1, 0, 1 }
Definition at line 43 of file q_math.c.
Referenced by CG_DemoControlButtonRender(), CG_DrawCursorhint(), CG_DrawFireTeamOverlay(), CG_DrawLagometer(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), R_SetupLightFrustum(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderLightOcclusionVolume(), Tess_SurfaceAxis(), and TraverseNode().
vec4_t colorLtGrey = { 0.75, 0.75, 0.75, 1 }
Definition at line 50 of file q_math.c.
vec4_t colorMagenta = { 1, 0, 1, 1 }
Definition at line 47 of file q_math.c.
Referenced by RB_RenderDebugUtils().
vec4_t colorMdBlue = { 0, 0, 0.5, 1 }
Definition at line 59 of file q_math.c.
Referenced by CG_SpeakerEditor_Back(), CG_SpeakerEditor_RenderButton(), and CG_SpeakerInfo_Text().
vec4_t colorMdCyan = { 0, 0.5, 0.5, 1 }
Definition at line 56 of file q_math.c.
vec4_t colorMdGreen = { 0, 0.5, 0, 1 }
Definition at line 54 of file q_math.c.
vec4_t colorMdGrey = { 0.5, 0.5, 0.5, 1 }
Definition at line 51 of file q_math.c.
Referenced by CG_Debriefing_Scrollbar_Draw(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderDebugUtils(), RE_LoadWorldMap(), and TraverseNode().
vec4_t colorMdOrange = { 0.5, 0.25, 0, 1 }
Definition at line 58 of file q_math.c.
vec4_t colorMdRed = { 0.5, 0, 0, 1 }
Definition at line 53 of file q_math.c.
Referenced by CG_DrawStaminaBar().
vec4_t colorMdYellow = { 0.5, 0.5, 0, 1 }
Definition at line 57 of file q_math.c.
vec4_t colorOrange = { 1, 0.5, 0, 1 }
Definition at line 46 of file q_math.c.
Referenced by CG_DrawWeapRecharge().
vec4_t colorRed = { 1, 0, 0, 1 }
Definition at line 42 of file q_math.c.
Referenced by CG_DrawCursorhint(), CG_DrawDemoRecording(), CG_DrawFireTeamOverlay(), CG_DrawGunIcon(), CG_DrawLagometer(), CG_DrawMapEntity(), CG_DrawNoShootIcon(), CG_DrawWeapRecharge(), DrawTris(), R_SetupLightFrustum(), RB_RenderDebugUtils(), RenderLightOcclusionVolume(), Tess_SurfaceAxis(), WM_DrawClientScore(), and WM_DrawClientScore_Small().
vec4_t colorWhite = { 1, 1, 1, 1 }
Definition at line 49 of file q_math.c.
Referenced by CG_Bullet(), CG_CommandMap_DrawHighlightText(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerName_Draw(), CG_DebriefingPlayerList_Draw(), CG_demoAviFPSDraw(), CG_DemoClick(), CG_demoTimescaleDraw(), CG_DrawAmmoCount(), CG_DrawCenterString(), CG_DrawConnectScreen(), CG_DrawDisconnect(), CG_DrawFireTeamOverlay(), CG_DrawFollow(), CG_DrawGunIcon(), CG_DrawLagometer(), CG_DrawLimboMessage(), CG_DrawMapEntity(), CG_DrawPlayerHealth(), CG_DrawPowerUps(), CG_DrawRank(), CG_DrawScoreboard(), CG_DrawSkills(), CG_DrawSpawnPointInfo(), CG_DrawSpectator(), CG_DrawSpectatorMessage(), CG_DrawStaminaBar(), CG_DrawWarmup(), CG_DrawXP(), CG_LoadPanel_DrawPin(), CG_MissileHitWall(), CG_MissileHitWallSmall(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerEditor_RenderEdit(), CG_SpeakerEditorDraw(), CG_windowDraw(), DeformText(), DrawTris(), Field_VariableSizeDraw(), R_AddModelShadow(), R_CoherentHierachicalCulling(), R_InitUnitCubeVBO(), R_LoadNodesAndLeafs(), R_SetupLightFrustum(), RB_DrawSun(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlare(), RB_RenderHDRResultToFrameBuffer(), RB_RenderScreenSpaceAmbientOcclusion(), RE_SetColor(), RE_StretchPicGradient(), RenderLightOcclusionVolume(), UI_DrawMapPreview(), WM_DrawClientScore(), WM_DrawClientScore_Small(), and WM_TeamScoreboard().
vec4_t colorYellow = { 1, 1, 0, 1 }
Definition at line 45 of file q_math.c.
Referenced by CG_Debriefing_ChatEdit_Draw(), CG_DrawGunIcon(), CG_DrawLagometer(), CG_DrawMapEntity(), CG_DrawVote(), CG_DrawWeapRecharge(), CG_DrawXP(), CG_SpeakerEditor_RenderDropdown(), CG_SpeakerEditor_RenderEdit(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), WM_DrawClientScore(), and WM_DrawClientScore_Small().
vec4_t g_color_table[32]
Definition at line 72 of file q_math.c.
Referenced by CG_Text_Paint_Ext(), CON_ColorCharToAttrib(), Con_DrawClock(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_DrawVersion(), DrawTris(), RB_RenderDebugUtils(), SCR_DrawDebugGraph(), SCR_DrawStringExt(), Text_Paint_Ext(), and Text_Paint_Limit().
vec3_t vec3_origin = { 0, 0, 0 }
Definition at line 38 of file q_math.c.
Referenced by AddSkyPolygon(), angles_to_axis(), AutospriteDeform(), BaseWindingForPlane(), ByteToDir(), CanDamage(), CG_AddEntityToTag(), CG_AddFragment(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_BloodTrail(), CG_Bullet(), CG_CheckForCursorHints(), CG_ClipMoveToEntities(), CG_DamageFeedback(), CG_DrawFlashFire(), CG_EntityEffects(), CG_FragmentBounceMark(), CG_GibPlayer(), CG_Missile(), CG_MissileHitWall(), CG_Mover_PostProcess(), CG_PlayScriptSpeaker(), CG_Portal(), CG_RenderSmokeGrenadeSmoke(), CG_RocketTrail(), CG_UnderwaterSounds(), CG_UpdateFlamethrowerSounds(), CM_AddFacetBevels(), CM_BoxTrace(), CM_DrawDebugSurface(), CM_Trace(), CM_TransformedBoxTrace(), CM_ValidateFacet(), ComputeColors(), Do_Activate_f(), EntsThatRadiusCanDamage(), etpro_RadiusDamage(), FindIntermissionPoint(), G_BurnMeGood(), G_BurnTarget(), G_GlobalClientEvent(), G_RadiusDamage(), G_TagLinkEntity(), GibEntity(), InitTrigger(), mg42_think(), PM_NoclipMove(), R_AddModelShadow(), R_GetPortalOrientations(), R_InitUnitCubeVBO(), R_LoadFogs(), R_LoadNodesAndLeafs(), R_MirrorViewBySurface(), R_SetupLightFrustum(), R_SetupLightLocalBounds(), R_SetupLightOrigin(), R_SetupLightProjection(), R_SetupLightScissor(), RB_AddQuadStampExt(), RB_CalcDeformVertexes(), RB_RenderDebugUtils(), RB_SurfaceBad(), RB_SurfaceSplash(), RB_SurfaceSprite(), RE_ProjectDecal(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), SelectCTFSpawnPoint(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), SV_LinkEntity(), SV_Trace(), Tess_AddQuadStampExt(), Tess_SurfaceSplash(), Tess_SurfaceSprite(), Weapon_Knife(), and WindingCenter().