ET: Legacy: src/qcommon/q_shared.c File Reference
q_shared.c File Reference
Stateless support routines that are included in each code dll.
#include "q_shared.h"
Functions
qboolean Com_PowerOf2 (int x)
Com_PowerOf2.
void COM_FixPath (char *pathname)
COM_FixPath.
char * COM_SkipPath (char *pathname)
COM_SkipPath.
const char * COM_GetExtension (const char *name)
COM_GetExtension.
void COM_StripExtension (const char *in, char *out, int destsize)
COM_StripExtension.
qboolean COM_CompareExtension (const char *in, const char *ext)
String compare the end of the strings and return qtrue if strings match.
void COM_StripFilename (const char *in, char *out)
COM_StripFilename.
void COM_DefaultExtension (char *path, size_t maxSize, const char *extension)
if path doesn't have an extension, then append the specified one (which should include the .)
int Com_HashKey (char *string, int maxlen)
Com_HashKey.
qboolean COM_BitCheck (const int array[], unsigned int bitNum)
Allows bit-wise checks on arrays with more than one item (> 32 bits)
void COM_BitSet (int array[], unsigned int bitNum)
Allows bit-wise SETS on arrays with more than one item (> 32 bits)
void COM_BitClear (int array[], unsigned int bitNum)
Allows bit-wise CLEAR on arrays with more than one item (> 32 bits)
short ShortSwap (short l)
ShortSwap.
short ShortNoSwap (short l)
ShortNoSwap.
int LongSwap (int l)
LongSwap.
int LongNoSwap (int l)
LongNoSwap.
float FloatSwap (const float *f)
FloatSwap.
float FloatNoSwap (float f)
FloatNoSwap.
void COM_BeginParseSession (const char *name)
COM_BeginParseSession.
void COM_BackupParseSession (char **data_p)
COM_BackupParseSession.
void COM_RestoreParseSession (char **data_p)
COM_RestoreParseSession.
void COM_SetCurrentParseLine (int line)
COM_SetCurrentParseLine.
int COM_GetCurrentParseLine (void)
COM_GetCurrentParseLine.
char * COM_Parse (char **data_p)
COM_Parse.
void COM_ParseError (const char *format,...)
COM_ParseError.
static char * SkipWhitespace (char *data, qboolean *hasNewLines)
Parse a token out of a string Will never return NULL, just empty strings.
int COM_Compress (char *data_p)
COM_Compress.
char * COM_ParseExt (char **data_p, qboolean allowLineBreaks)
COM_ParseExt.
char * COM_Parse2 (char **data_p)
COM_Parse2.
char * COM_ParseExt2 (char **data_p, qboolean allowLineBreaks)
COM_ParseExt2.
void COM_MatchToken (char **buf_p, char *match)
COM_MatchToken.
void SkipBracedSection_Depth (char **program, int depth)
SkipBracedSection_Depth.
void SkipBracedSection (char **program)
The next token should be an open brace. Skips until a matching close brace is found. Internal brace depths are properly skipped.
void SkipRestOfLine (char **data)
SkipRestOfLine.
void Parse1DMatrix (char **buf_p, int x, float *m)
Parse1DMatrix.
void Parse2DMatrix (char **buf_p, int y, int x, float *m)
Parse2DMatrix.
void Parse3DMatrix (char **buf_p, int z, int y, int x, float *m)
Parse3DMatrix.
int Com_ParseInfos (char *buf, int max, char infos[][MAX_INFO_STRING])
Com_ParseInfos.
int Com_HexStrToInt (const char *str)
Com_HexStrToInt.
int Q_isprint (int c)
Q_isprint.
int Q_islower (int c)
Q_islower.
int Q_isupper (int c)
Q_isupper.
int Q_isalpha (int c)
Q_isalpha.
int Q_isnumeric (int c)
Q_isnumeric.
int Q_isalphanumeric (int c)
Q_isalphanumeric.
qboolean Q_isanumber (const char *s)
Q_isanumber.
qboolean Q_isintegral (float f)
Q_isintegral.
int Q_isforfilename (int c)
Q_isforfilename.
void Q_strncpyz (char *dest, const char *src, size_t destsize)
Safe strncpy that ensures a trailing zero.
int Q_stricmpn (const char *s1, const char *s2, size_t n)
Compare strings without case sensitivity up to n characters.
int Q_strncmp (const char *s1, const char *s2, size_t n)
Compare strings up to n characters.
int Q_stricmp (const char *s1, const char *s2)
Compare whole strings without case sensitivity.
char * Q_strlwr (char *s1)
Q_strlwr.
char * Q_strupr (char *s1)
Q_strupr.
void Q_strcat (char *dest, size_t size, const char *src)
Q_strcat.
const char * Q_stristr (const char *s, const char *find)
Find the first occurrence of find in s.
int Q_PrintStrlen (const char *string)
Q_PrintStrlen.
char * Q_CleanStr (char *string)
Remove special characters and color sequences from string.
void Q_ColorizeString (char colorCode, const char *inStr, char *outStr, size_t outBufferLen)
Takes a plain "un-colored" string, and then colorizes it so the string is displayed in the given color. If given a string such as "Bob" and asked to colorize to '1' (red)', the output would be "^1Bob". If given "John^^7Candy" the output is "^1John^^1^^17Candy" – Note that when drawn, this would literally show the text "John^^7Candy" in red.
qboolean Q_isBadDirChar (char c)
Strips whitespaces and bad characters.
char * Q_CleanDirName (char *dirname)
Q_CleanDirName.
int Q_CountChar (const char *string, char tocount)
Q_CountChar.
long Q_GenerateHashValue (const char *fname, int size, qboolean fullPath, qboolean ignoreCase)
Q_GenerateHashValue.
int QDECL Com_sprintf (char *dest, unsigned int size, const char *fmt,...)
Com_sprintf.
char *QDECL va (const char *format,...)
Does a varargs printf into a temp buffer, so I don't need to have varargs versions of all text functions.
void Com_TruncateLongString (char *buffer, const char *s)
Assumes buffer is atleast TRUNCATE_LENGTH big.
float * tv (float x, float y, float z)
This is just a convenience function for making temporary vectors for function calls.
char * Info_ValueForKey (const char *s, const char *key)
Searches the string for the given key and returns the associated value, or an empty string.
qboolean Info_NextPair (const char **head, char *key, char *value)
Used to itterate through all the key/value pairs in an info string.
void Info_RemoveKey (char *s, const char *key)
Info_RemoveKey.
void Info_RemoveKey_Big (char *s, const char *key)
Info_RemoveKey_Big.
qboolean Info_Validate (const char *s)
Some characters are illegal in info strings because they can mess up the server's parsing.
void Info_SetValueForKey (char *s, const char *key, const char *value)
Changes or adds a key/value pair.
void Info_SetValueForKey_Big (char *s, const char *key, const char *value)
Changes or adds a key/value pair.
char * Q_StrReplace (char *haystack, const char *needle, const char *newVal)
Q_StrReplace.
static qboolean Com_CharIsOneOfCharset (char c, const char *set)
Com_CharIsOneOfCharset.
char * Com_SkipCharset (char *s, char *sep)
Com_SkipCharset.
char * Com_SkipTokens (char *s, int numTokens, const char *sep)
Com_SkipTokens.
void * Q_LinearSearch (const void *key, const void *ptr, size_t count, size_t size, cmpFunc_t cmp)
Q_LinearSearch.
int GetIPLength (char const *ip)
Q_GetIPLength.
qboolean CompareIPNoPort (char const *ip1, char const *ip2)
CompareIPNoPort.
void * Com_AnyOf (void **ptr, int n)
Com_AnyOf returns first valid pointer from the set.
Variables
const char * punctuation []
Multiple character punctuation tokens.
static char com_token [MAX_TOKEN_CHARS]
static char com_parsename [MAX_TOKEN_CHARS]
static int com_lines
static int backup_lines
static char * backup_text
Detailed Description
Stateless support routines that are included in each code dll.
Definition in file q_shared.c.
Function Documentation
void* Com_AnyOf (void ** ptr, int n)
Com_AnyOf returns first valid pointer from the set.
Parameters
[in] ptr list of pointers
[in] n pointer count
Returns
first non-null pointer
Definition at line 2679 of file q_shared.c.
Referenced by RE_RegisterModel().
void COM_BackupParseSession (char ** data_p)
COM_BackupParseSession.
Parameters
[in] data_p
Definition at line 376 of file q_shared.c.
Referenced by COM_ParseExt(), and COM_ParseExt2().
void COM_BeginParseSession (const char * name)
COM_BeginParseSession.
Parameters
[in] name
Definition at line 366 of file q_shared.c.
Referenced by BG_AnimParseAnimScript(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseWeaponConfig(), CL_SetExpectedHunkUsage(), CL_UpdateLevelHunkUsage(), G_MapVoteInfoRead(), G_Script_ScriptParse(), and ScanAndLoadShaderFilesR1().
qboolean COM_BitCheck (const int array[], unsigned int bitNum)
Allows bit-wise checks on arrays with more than one item (> 32 bits)
Parameters
[in] array
[in] bitNum
Returns
Definition at line 216 of file q_shared.c.
Referenced by BG_AddMagicAmmo(), BG_GetConditionBitFlag(), BG_GetConditionValue(), Bot_Event_AddWeapon(), CG_AltWeapon_f(), CG_DrawMortarMarker(), CG_ItemPickup(), CG_ParseFireteams(), CG_WeaponSelectable(), Cmd_Give_f(), G_CheckForCursorHints(), G_GetPrimaryWeaponForClient(), G_GetPrimaryWeaponForClientSoldier(), G_players_cmd(), G_ResetXP(), G_Say(), G_SayTo(), G_Voice(), Pickup_Weapon(), PM_BeginWeaponChange(), PM_CoolWeapons(), PM_FinishWeaponChange(), ReTransmitWeapons(), SetWolfSpawnWeapons(), and Touch_Item_Auto().
void COM_BitClear (int array[], unsigned int bitNum)
Allows bit-wise CLEAR on arrays with more than one item (> 32 bits)
Parameters
[out] array
[in] bitNum
Definition at line 245 of file q_shared.c.
Referenced by _et_RemoveWeaponFromPlayer(), BG_ClearConditionBitFlag(), Cmd_UnIgnore_f(), G_DropWeapon(), G_RemoveFromAllIgnoreLists(), and PM_SwitchIfEmpty().
void COM_BitSet (int array[], unsigned int bitNum)
Allows bit-wise SETS on arrays with more than one item (> 32 bits)
Parameters
[in] array
[out] bitNum
Definition at line 230 of file q_shared.c.
Referenced by _et_AddWeaponToPlayer(), Add_Ammo(), AddWeaponToPlayer(), BG_AddMagicAmmo(), BG_ParseConditionBits(), BG_SetConditionBitFlag(), BG_UpdateConditionValue(), Cmd_Give_f(), Cmd_Ignore_f(), G_UpdateFireteamConfigString(), and Pickup_Weapon().
static qboolean Com_CharIsOneOfCharset (char c, const char * set) static
Com_CharIsOneOfCharset.
Parameters
[in] c
[in] set
Returns
Definition at line 2512 of file q_shared.c.
Referenced by Com_SkipCharset(), and Com_SkipTokens().
qboolean COM_CompareExtension (const char * in, const char * ext)
String compare the end of the strings and return qtrue if strings match.
Parameters
[in] in
[in] ext
Returns
Definition at line 139 of file q_shared.c.
Referenced by CIN_PlayCinematic(), Com_Download_f(), Com_WriteConfig_f(), Con_Dump_f(), DB_Create(), DB_Init(), DB_SaveMemDB(), FS_CheckFilenameIsMutable(), FS_CheckFilenameIsNotExecutable(), S_AL_Init(), and Sys_DllExtension().
int COM_Compress (char * data_p)
COM_Compress.
Parameters
[in,out] data_p
Returns
Definition at line 491 of file q_shared.c.
Referenced by ScanAndLoadShaderFilesR1().
void COM_DefaultExtension (char * path, size_t maxSize, const char * extension)
if path doesn't have an extension, then append the specified one (which should include the .)
Parameters
[in,out] path
[in] maxSize
[in] extension
Definition at line 176 of file q_shared.c.
Referenced by CIN_PlayCinematic_f(), Cmd_Exec_f(), Com_WriteConfig_f(), Con_Dump_f(), R_FindShader(), R_LoadModelShadow(), S_CodecLoad(), S_CodecOpenStream(), S_FindCodecForFile(), and S_Play_f().
void COM_FixPath (char * pathname)
COM_FixPath.
Parameters
[in,out] pathname
Definition at line 57 of file q_shared.c.
Referenced by GLSL_FindShader(), LoadMap(), R_FindShader(), R_FindShaderByName(), RE_RegisterShaderFromImage(), and ScanAndLoadShaderFiles().
int COM_GetCurrentParseLine (void)
COM_GetCurrentParseLine.
Returns
Definition at line 405 of file q_shared.c.
Referenced by __attribute__(), G_MapVoteInfoRead(), G_ReadConfigFileInt(), G_ReadConfigFileString(), G_Script_ScriptParse(), and ScanAndLoadShaderFilesR1().
const char* COM_GetExtension (const char * name)
COM_GetExtension.
Parameters
[in] name
Returns
Definition at line 94 of file q_shared.c.
Referenced by CIN_PlayCinematic(), and FS_CheckFilenameIsMutable().
int Com_HashKey (char * string, int maxlen)
Com_HashKey.
Parameters
[in,out] string
[in] maxlen
Returns
Definition at line 196 of file q_shared.c.
Referenced by GetMDMSurfaceShader(), R_AddAnimSurfaces(), R_AddMD3Surfaces(), R_AddMDCSurfaces(), R_MDM_AddAnimSurfaces(), RE_GetSkinModel(), and RE_RegisterSkin().
int Com_HexStrToInt (const char * str)
Com_HexStrToInt.
Parameters
[in] str
Returns
Definition at line 1236 of file q_shared.c.
Referenced by IN_IsConsoleKey(), and Key_StringToKeynum().
void COM_MatchToken (char ** buf_p, char * match)
COM_MatchToken.
Parameters
[in] buf_p
[in] match
Definition at line 1009 of file q_shared.c.
Referenced by Parse1DMatrix(), Parse2DMatrix(), and Parse3DMatrix().
char* COM_Parse (char ** data_p)
COM_Parse.
Parameters
[in] data_p
Returns
Definition at line 415 of file q_shared.c.
Referenced by BG_AnimParseAnimScript(), CG_Debriefing_ParseAwards(), CG_MustParse(), CG_NewParticleArea(), CG_ParseFog(), CG_ParseGibModels(), CG_ParseGlobalFog(), CG_ParseHudHeadConfig(), CG_ParseScreenFade(), CG_ParseWeaponConfig(), CG_QueueMusic(), CG_SetupDlightstyles(), CG_StartMusic(), CL_SetExpectedHunkUsage(), CL_UpdateLevelHunkUsage(), ClientBegin(), Com_Init(), COM_MatchToken(), Com_ParseInfos(), DrawTris(), G_MapVoteInfoRead(), G_Script_ScriptParse(), G_ScriptAction_AddTeamVoiceAnnounce(), G_ScriptAction_AlliedRespawntime(), G_ScriptAction_Announce(), G_ScriptAction_Announce_Icon(), G_ScriptAction_AxisRespawntime(), G_ScriptAction_FaceAngles(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_RemoveTeamVoiceAnnounce(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetMainObjective(), G_ScriptAction_SetRotation(), G_ScriptAction_SetRoundTimelimit(), G_ScriptAction_SetSpeed(), G_ScriptAction_SetWinner(), G_ScriptAction_TagConnect(), G_ScriptAction_TeamVoiceAnnounce(), G_ScriptAction_VoiceAnnounce(), IN_IsConsoleKey(), Parse1DMatrix(), R_GetEntityToken(), SV_GameSystemCalls(), SV_SetExpectedHunkUsage(), and VM_LoadSymbols().
char* COM_Parse2 (char ** data_p)
COM_Parse2.
added COM_Parse2 for having a Doom 3 style tokenizer.
Parameters
[in] data_p
Returns
Definition at line 743 of file q_shared.c.
Referenced by R_GetEntityToken().
void COM_ParseError (const char * format, ...)
COM_ParseError.
Parameters
[in] format
Definition at line 424 of file q_shared.c.
Referenced by G_Script_ScriptParse().
char* COM_ParseExt (char ** data_p, qboolean allowLineBreaks)
COM_ParseExt.
Parameters
[in,out] data_p
[in] allowLineBreaks
Returns
Definition at line 593 of file q_shared.c.
Referenced by BG_AnimParseAnimScript(), BG_ParseCommands(), BG_ParseConditionBits(), BG_ParseConditions(), BuildShaderChecksumLookup(), CG_ParseSkyBox(), CG_ParseTeamXPs(), CG_ParseVoiceChats(), CG_SoundLoadSoundFiles(), CG_SoundParseSounds(), COM_Parse(), Com_ParseInfos(), etpro_ScriptAction_SetValues(), FindShaderInShaderText(), FindShaderInShaderTextR1(), Float_Parse(), G_Lua_CreateEntity(), G_ReadConfigFileInt(), G_ReadConfigFileString(), G_Script_EventMatch_IntInRange(), G_Script_ScriptParse(), G_ScriptAction_Accum(), G_ScriptAction_AddTankAmmo(), G_ScriptAction_AllowTankEnter(), G_ScriptAction_AllowTankExit(), G_ScriptAction_AttatchToTrain(), G_ScriptAction_ChangeModel(), G_ScriptAction_Construct(), G_ScriptAction_ConstructibleChargeBarReq(), G_ScriptAction_ConstructibleClass(), G_ScriptAction_ConstructibleConstructXPBonus(), G_ScriptAction_ConstructibleDestructXPBonus(), G_ScriptAction_ConstructibleDuration(), G_ScriptAction_ConstructibleHealth(), G_ScriptAction_ConstructibleWeaponclass(), G_ScriptAction_Create(), G_ScriptAction_Cvar(), G_ScriptAction_Delete(), G_ScriptAction_FadeAllSounds(), G_ScriptAction_FollowPath(), G_ScriptAction_FollowSpline(), G_ScriptAction_GlobalAccum(), G_ScriptAction_GotoMarker(), G_ScriptAction_Kill(), G_ScriptAction_MusicFade(), G_ScriptAction_MusicPlay(), G_ScriptAction_MusicQueue(), G_ScriptAction_MusicStart(), G_ScriptAction_MusicStop(), G_ScriptAction_PlayAnim(), G_ScriptAction_PlaySound(), G_ScriptAction_Print(), G_ScriptAction_PrintAccum(), G_ScriptAction_PrintGlobalAccum(), G_ScriptAction_RepairMG42(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDamagable(), G_ScriptAction_SetDebugLevel(), G_ScriptAction_SetGlobalFog(), G_ScriptAction_SetHQStatus(), G_ScriptAction_SetModelFromBrushmodel(), G_ScriptAction_SetPosition(), G_ScriptAction_SetState(), G_ScriptAction_SetTankAmmo(), G_ScriptAction_ShaderRemap(), G_ScriptAction_StartAnimation(), G_ScriptAction_Trigger(), G_ScriptAction_Wait(), G_SetSkillLevels(), GameType_Parse(), GLSL_CopyNextToken(), GLSL_FindDefinitionInText(), GLSL_ParseDefinition(), Int_Parse(), ParseDeform(), ParseShader(), ParseShaderR1(), ParseSkyParms(), ParseSort(), ParseStage(), ParseStencil(), ParseSurfaceParm(), ParseTexMod(), ParseVector(), ParseWaveForm(), R_LoadCacheImages(), R_LoadCacheModels(), R_LoadCacheShaders(), R_LoadEntities(), R_LoadImage(), RE_LoadDynamicShader(), ScanAndLoadShaderFilesR1(), SkipBracedSection(), SkipBracedSection_Depth(), String_Parse(), and UI_ParseGameInfo().
char* COM_ParseExt2 (char ** data_p, qboolean allowLineBreaks)
COM_ParseExt2.
Parameters
[in,out] data_p
[in] allowLineBreaks
Returns
Definition at line 755 of file q_shared.c.
Referenced by COM_Parse2(), CreateShaderByGuide(), FindGuideInGuideText(), FindShaderInShaderText(), GLSL_FinnishShaderTextAndCompile(), GLSL_PreprocessShaderText(), LoadMap(), LoadRGBEToFloats(), ParseAddNormals(), ParseDeform(), ParseDisplaceMap(), ParseHeightMap(), ParseInvertAlpha(), ParseInvertColor(), ParseMakeAlpha(), ParseMakeIntensity(), ParseMap(), ParseShader(), ParseShaderR1(), ParseSkyParms(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), ParseWaveForm(), R_LoadEntities(), R_LoadLights(), R_LoadMD5(), R_LoadMD5Anim(), ScanAndLoadShaderFilesR1(), and setProjTargetOrigin().
int Com_ParseInfos (char * buf, int max, char infos[][MAX_INFO_STRING])
Com_ParseInfos.
Parameters
[in] buf
[in] max
[out] infos
Returns
Note
Unused
Definition at line 1178 of file q_shared.c.
qboolean Com_PowerOf2 (int x)
Com_PowerOf2.
Parameters
[in] x
Returns
Note
Unused
Definition at line 45 of file q_shared.c.
void COM_RestoreParseSession (char ** data_p)
COM_RestoreParseSession.
Parameters
[out] data_p
Definition at line 386 of file q_shared.c.
Referenced by BG_ParseCommands(), BG_ParseConditionBits(), and CG_ParseVoiceChats().
void COM_SetCurrentParseLine (int line)
COM_SetCurrentParseLine.
Parameters
[in] line
Definition at line 396 of file q_shared.c.
char* Com_SkipCharset (char * s, char * sep)
Com_SkipCharset.
Parameters
[in] s
[in] sep
Returns
Definition at line 2533 of file q_shared.c.
Referenced by Field_CompleteCommand().
char* COM_SkipPath (char * pathname)
COM_SkipPath.
Parameters
[in,out] pathname
Returns
Definition at line 74 of file q_shared.c.
Referenced by CG_SpeakerEditor_NoiseEdit_KeyDown(), COM_StripFilename(), and RE_LoadWorldMap().
char* Com_SkipTokens (char * s, int numTokens, const char * sep)
Com_SkipTokens.
Parameters
[in] s
[in] numTokens
[in] sep
Returns
Definition at line 2559 of file q_shared.c.
Referenced by CL_CompleteRcon(), Cvar_CompleteCvarName(), Key_CompleteBind(), and Key_CompleteUnbind().
int QDECL Com_sprintf (char * dest, unsigned int size, const char * fmt, ...)
Com_sprintf.
Parameters
dest
size
fmt
Returns
Definition at line 1932 of file q_shared.c.
Referenced by _et_G_LogPrint(), BG_GetLocationString(), BuildShaderStateConfig(), CG_AddFlameToScene(), CG_DrawAmmoCount(), CG_DrawDemoRecording(), CG_DrawField(), CG_DrawFireTeamOverlay(), CG_DrawGrid(), CG_DrawSpawnPointInfo(), CG_InitFlameChunks(), CG_LocateArena(), CG_LocateCampaign(), CG_ModifyEditSpeaker(), CG_ParseServerinfo(), CG_ParseVoiceChats(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_SaveSpeakersToScript(), CG_ServerCommand(), CG_SoundLoadSoundFiles(), CG_SpeakerEditor_NoiseEdit_KeyDown(), CG_SpeakerEditor_RandomEditFinish(), CG_SpeakerEditor_RangeEditFinish(), CG_SpeakerEditor_VolumeEditFinish(), CG_SpeakerEditor_WaitEditFinish(), CG_SpeakerInfo_Text(), CG_VoiceChatLocal(), CG_WriteToLog(), CIN_PlayCinematic_f(), CL_CheckForResend(), CL_CompleteDemoName(), CL_DemoFilename(), CL_GenerateETKey(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitCGame(), CL_InitRef(), CL_KeyEvent(), CL_ParseSnapshot(), CL_PlayDemo_f(), CL_Record_f(), CL_RequestMotd(), CL_SendPureChecksums(), CL_ServerStatusResponse(), CL_StartVideoRecording(), CL_TranslateString(), CL_TranslateStringMod(), CL_UpdateLevelHunkUsage(), CL_Video_f(), CL_WalkDemoExt(), CL_WavFilename(), CL_WriteWaveOpen(), Cmd_CallVote_f(), Com_BeginDownload(), COM_BeginParseSession(), Com_Printf(), Com_RunUpdateBinary(), Con_DrawClock(), Con_DrawVersion(), CON_Input(), Console_AutoComplete(), Console_Key(), Cvar_SetValue(), Cvar_SetValueSafe(), Cvar_Validate(), Cvar_WriteVariables(), FS_AddBothGameDirectories(), FS_BuildOSPath(), FS_ComparePaks(), FS_DeleteDir(), FS_GetModList(), FS_Unzip(), FS_UnzipTo(), FS_VerifyOfficialPaks(), G_Campaign_v(), G_Config_v(), G_Gametype_v(), G_Kick_v(), G_LogPrintf(), G_Map_v(), G_MatchOnePlayer(), G_Mute_v(), G_Poll_v(), G_PushMapEntityToBuffer(), G_Referee_v(), G_Say(), G_SendMapEntityInfo(), G_SendScore_Add(), G_SendSpectatorMapEntityInfo(), G_Timelimit_v(), G_UnMute_v(), G_Unreferee_v(), G_UpdateFireteamConfigString(), G_voteCmdCheck(), G_voteProcessOnOff(), G_Warmupfire_v(), G_WriteSessionData(), GetParsedIP(), GL_CheckErrors(), GL_CheckErrors_(), GLSL_GetShaderText(), Hunk_Log(), Hunk_SmallLog(), I18N_SetLanguage(), IN_WindowResize(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Item_Text_Paint(), LAN_LoadCachedServers(), LAN_SaveServersToFile(), LoadScriptFile(), NET_AdrToString(), NET_AdrToStringNoPort(), objective_Register(), ParseSkyParms(), PS_SetBaseFolder(), R_FindCubeImage(), R_GetFont(), R_LevelShot(), R_LoadScalableFont(), R_LoadSubmodels(), R_ScreenShot_f(), R_ScreenshotFilename(), R_TakeScreenshot(), RE_BeginFrame(), ScanAndLoadShaderFiles(), ScanAndLoadShaderFilesR1(), SV_CheckClientUserinfoTimer(), SV_CheckDownloadAllowed(), SV_ClientCommand(), SV_CompleteDemoName(), SV_Demo_Play_f(), SV_Demo_Record_f(), SV_DemoWriteConfigString(), SV_Map_f(), SV_WriteAttackLog(), SVC_Status(), Svcmd_EntityList_f(), Sys_AnsiColorPrint(), Sys_ListFiles(), Sys_ListFilteredFiles(), Sys_LoadDll(), Sys_LoadGameDll(), Sys_OpenURL(), Sys_TryLibraryLoad(), TeamplayInfoMessage(), UI_FeederItemText(), UI_GetServerStatusInfo(), UI_LoadDemos(), UI_LoadPanel_RenderLoadingText(), UI_PrintTime(), UI_ReadableSize(), UI_RunMenuScript(), UI_StartServerRefresh(), VM_Create(), VM_LoadSymbols(), VM_Restart(), VM_ValueToSymbol(), vtos(), and Z_LogZoneHeap().
void COM_StripExtension (const char * in, char * out, int destsize)
COM_StripExtension.
Parameters
[in] in
[out] out
[in] destsize
Definition at line 114 of file q_shared.c.
Referenced by CG_RegisterAcc(), CG_RegisterCharacter(), FS_FilenameCompletion(), G_ScriptAction_ChangeModel(), GLSL_FindShader(), Item_Text_Paint(), LoadMap(), R_FindCubeImage(), R_FindImageFile(), R_FindShader(), R_FindShaderByName(), R_LoadImage(), R_LoadLightmapsExternal(), R_LoadModelShadow(), R_RemapShader(), RE_LoadWorldMap(), RE_RegisterShaderFromImage(), SP_misc_gamemodel(), SP_script_mover(), and VM_LoadSymbols().
void COM_StripFilename (const char * in, char * out)
COM_StripFilename.
Parameters
[in] in
[out] out
Definition at line 161 of file q_shared.c.
Referenced by CG_SpeakerEditor_NoiseEdit_KeyDown().
void Com_TruncateLongString (char * buffer, const char * s)
Assumes buffer is atleast TRUNCATE_LENGTH big.
Parameters
[out] buffer
[in] s
Definition at line 2023 of file q_shared.c.
Referenced by PrintCvarMatches().
qboolean CompareIPNoPort (char const * ip1, char const * ip2)
CompareIPNoPort.
Parameters
[in] ip1
[in] ip2
Returns
Definition at line 2654 of file q_shared.c.
Referenced by ClientUserinfoChanged(), and SV_isClientIPValidToConnect().
float FloatNoSwap (float f)
FloatNoSwap.
Parameters
[in] f
Returns
Note
Unused
Definition at line 333 of file q_shared.c.
float FloatSwap (const float * f)
FloatSwap.
Parameters
[in] f
Returns
Definition at line 316 of file q_shared.c.
int GetIPLength (char const * ip)
Q_GetIPLength.
Parameters
ip
Returns
The length of the IP address if it has a port, or INT_MAX otherwise
Todo:
FIXME: IPv6
Definition at line 2641 of file q_shared.c.
Referenced by CompareIPNoPort().
qboolean Info_NextPair (const char ** head, char * key, char * value)
Used to itterate through all the key/value pairs in an info string.
Parameters
[in] head
[out] key
[out] value
Returns
qfalse if we discover the infostring is invalid
Definition at line 2151 of file q_shared.c.
Referenced by CL_SystemInfoChanged(), ClientConnect(), and ClientUserinfoChanged().
void Info_RemoveKey (char * s, const char * key)
Info_RemoveKey.
Parameters
[in,out] s
[in] key
Definition at line 2201 of file q_shared.c.
Referenced by _et_Info_RemoveKey(), Info_SetValueForKey(), and SV_DemoFilterClientUserinfo().
void Info_RemoveKey_Big (char * s, const char * key)
Info_RemoveKey_Big.
Parameters
[in,out] s
[in] key
Definition at line 2268 of file q_shared.c.
Referenced by Info_SetValueForKey_Big().
void Info_SetValueForKey (char * s, const char * key, const char * value)
Changes or adds a key/value pair.
Parameters
[in,out] s
[in] key
[in] value
Definition at line 2353 of file q_shared.c.
Referenced by _et_Info_SetValueForKey(), ETInterface::AddBot(), CheckExitRules(), CL_CheckForResend(), CL_RequestMotd(), CL_ServerInfoPacket(), ClientUserinfoChanged(), Com_CheckAutoUpdate(), Com_ParseInfos(), Cvar_InfoString(), G_InitGame(), G_ScriptAction_NumberofObjectives(), G_ScriptAction_ObjectiveStatus(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDefendingTeam(), G_ScriptAction_SetWinner(), G_SetConfigStringValue(), G_Surrender_v(), G_UpdateCvars(), G_UpdateSkillsToClients(), G_UpdateSpawnPointState(), G_UpdateSpawnPointStatePlayerCounts(), G_UpdateSvCvars(), ETInterface::InterfaceSendMessage(), LAN_GetServerInfo(), objective_Register(), SP_misc_constructiblemarker(), SP_script_mover(), SV_DirectConnect(), SV_UserinfoChanged(), SVC_Info(), and SVC_Status().
void Info_SetValueForKey_Big (char * s, const char * key, const char * value)
Changes or adds a key/value pair.
Parameters
[in,out] s
[in] key
[in] value
Definition at line 2404 of file q_shared.c.
Referenced by Cvar_InfoString_Big().
qboolean Info_Validate (const char * s)
Some characters are illegal in info strings because they can mess up the server's parsing.
Parameters
[in] s
Returns
Definition at line 2334 of file q_shared.c.
Referenced by ClientUserinfoChanged().
char* Info_ValueForKey (const char * s, const char * key)
Searches the string for the given key and returns the associated value, or an empty string.
Parameters
[in] s
[in] key
Returns
Definition at line 2079 of file q_shared.c.
Referenced by _et_Info_ValueForKey(), _GetEntityName(), CG_ChargeTimesChanged(), CG_Debriefing_FindWinningTeamForMap(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_MissionTitle_Draw(), CG_Debriefing_Startup(), CG_DebriefingTitle_Draw(), CG_DrawConnectScreen(), CG_DrawCrosshairNames(), CG_DrawFlag(), CG_DrawWarmup(), CG_dumpStats(), CG_generateFilename(), CG_LimboPanel_GetMaxObjectives(), CG_LimboPanel_RenderObjectiveText(), CG_NewClientInfo(), CG_ObjectivesDraw(), CG_ParseFireteams(), CG_ParseLegacyinfo(), CG_ParseOIDInfo(), CG_ParseServerinfo(), CG_ParseSpawns(), CG_ParseSysteminfo(), CG_ParseWolfinfo(), CG_SkillLevelsChanged(), CG_TeamRestrictionsChanged(), CG_UpdateSvCvars(), CheckUserinfo(), CL_InitCGame(), CL_MotdPacket(), CL_ServerInfoPacket(), CL_SetServerInfo(), CL_SystemInfoChanged(), ClientBegin(), ClientName(), FindIntermissionPoint(), G_InitGame(), G_InitWorldSession(), G_LogExit(), G_Map_v(), G_ParseMapSettings(), G_PlayerBan(), G_players_cmd(), G_UpdateCharacter(), G_WriteSessionData(), ScoreIsTied(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DirectConnect(), SV_IsValidUserinfo(), SV_SetUserinfo(), SV_UserinfoChanged(), Svcmd_Kick_f(), Svcmd_KickNum_f(), UI_BuildPlayerList(), UI_BuildServerDisplayList(), UI_DescriptionForCampaign(), UI_FeederItemText(), UI_FeederSelection(), UI_FeederSelectionClick(), UI_ListFavourites_f(), UI_LoadPanel_RenderLoadingText(), UI_NameForCampaign(), UI_RunMenuScript(), WM_DrawInfoLine(), WM_DrawObjectives(), and WM_TeamScoreboard().
int LongNoSwap (int l)
LongNoSwap.
Parameters
[in] l
Returns
Note
Unused
Definition at line 306 of file q_shared.c.
int LongSwap (int l)
LongSwap.
Parameters
[in] l
Returns
Definition at line 287 of file q_shared.c.
Referenced by FloatSwap().
void Parse1DMatrix (char ** buf_p, int x, float * m)
Parse1DMatrix.
Parameters
[in] buf_p
[in] x
[out] m
Definition at line 1108 of file q_shared.c.
Referenced by G_ScriptAction_SetGlobalFog(), and Parse2DMatrix().
void Parse2DMatrix (char ** buf_p, int y, int x, float * m)
Parse2DMatrix.
Parameters
[in] buf_p
[in] y
[in] x
[out] m
Definition at line 1131 of file q_shared.c.
Referenced by Parse3DMatrix().
void Parse3DMatrix (char ** buf_p, int z, int y, int x, float * m)
Parse3DMatrix.
Parameters
[in] buf_p
[in] z
[in] y
[in] x
[out] m
Note
Unused
Definition at line 1155 of file q_shared.c.
char* Q_CleanDirName (char * dirname)
Q_CleanDirName.
removes whitespaces and other bad directory characters
Parameters
[in,out] dirname
Returns
Definition at line 1826 of file q_shared.c.
Referenced by Script_ConditionalScript(), UI_FeederItemText(), UI_LoadProfiles(), and UI_RunMenuScript().
char* Q_CleanStr (char * string)
Remove special characters and color sequences from string.
removes color sequences from string
Parameters
[in,out] string
Returns
Definition at line 1711 of file q_shared.c.
Referenced by _et_Q_CleanStr(), _GetEntityName(), CG_DrawVote(), CG_NewClientInfo(), ClientName(), Field_VariableSizeDraw(), G_GetPlayerByName(), G_refClientnumForName(), LAN_CompareServers(), ETInterface::RemoveBot(), Script_ConditionalScript(), SV_GetPlayerByName(), UI_FeederItemText(), UI_LoadProfiles(), UI_RunMenuScript(), UI_SortArenas(), and UI_SortCampaigns().
void Q_ColorizeString (char colorCode, const char * inStr, char * outStr, size_t outBufferLen)
Takes a plain "un-colored" string, and then colorizes it so the string is displayed in the given color. If given a string such as "Bob" and asked to colorize to '1' (red)', the output would be "^1Bob". If given "John^^7Candy" the output is "^1John^^1^^17Candy" – Note that when drawn, this would literally show the text "John^^7Candy" in red.
Encodes a plain un-colored string so that it'll be drawn with the given color code.
If the desired result is to see "John^Candy" in red, then create a clean un-colored string before calling this.
REQUIREMENTS:
Callers must pass in a buffer that is at least 3 bytes long.
inStr and outStr cannot overlap
Parameters
[in] colorCode
[in] inStr
[out] outStr
[in] outBufferLen
Definition at line 1751 of file q_shared.c.
Referenced by CG_DrawCrosshairNames().
int Q_CountChar (const char * string, char tocount)
Q_CountChar.
Count the number of char tocount encountered in string.
Parameters
[in] string
[in] tocount
Returns
Definition at line 1856 of file q_shared.c.
Referenced by NET_IP6Socket(), and NET_StringToAdr().
long Q_GenerateHashValue (const char * fname, int size, qboolean fullPath, qboolean ignoreCase)
Q_GenerateHashValue.
generate hashvalue from filename for set hashmap size
Parameters
[in] fname
[in] size
[in] fullPath
[in] ignoreCase
Returns
Todo:
: never executed
Definition at line 1879 of file q_shared.c.
Referenced by GLSL_FindShader().
int Q_isalpha (int c)
Q_isalpha.
Parameters
[in] c
Returns
Definition at line 1332 of file q_shared.c.
Referenced by G_DrawEntBBox(), and Q_isalphanumeric().
int Q_isalphanumeric (int c)
Q_isalphanumeric.
Parameters
[in] c
Returns
Definition at line 1360 of file q_shared.c.
Referenced by Q_isforfilename().
qboolean Q_isanumber (const char * s)
Q_isanumber.
Parameters
[in] s
Returns
Todo:
: Why d was marked unused but was used ?
Definition at line 1375 of file q_shared.c.
Referenced by Cvar_Validate().
qboolean Q_isBadDirChar (char c)
Strips whitespaces and bad characters.
Parameters
[in] c
Returns
Definition at line 1805 of file q_shared.c.
Referenced by Q_CleanDirName().
int Q_isforfilename (int c)
Q_isforfilename.
Parameters
[in] c
Returns
Definition at line 1406 of file q_shared.c.
qboolean Q_isintegral (float f)
Q_isintegral.
Parameters
[in] f
Returns
Definition at line 1396 of file q_shared.c.
Referenced by Cvar_SetValueSafe(), and Cvar_Validate().
int Q_islower (int c)
Q_islower.
Parameters
[in] c
Returns
Definition at line 1304 of file q_shared.c.
int Q_isnumeric (int c)
Q_isnumeric.
Parameters
[in] c
Returns
Definition at line 1346 of file q_shared.c.
Referenced by CL_FastForward_f(), CL_Rewind_f(), CL_Seek_f(), CL_SeekEnd_f(), ExtractInt(), and Q_isalphanumeric().
int Q_isprint (int c)
Q_isprint.
Parameters
[in] c
Returns
Definition at line 1290 of file q_shared.c.
int Q_isupper (int c)
Q_isupper.
Parameters
[in] c
Returns
Definition at line 1318 of file q_shared.c.
Referenced by BG_StringHashValue().
void* Q_LinearSearch (const void * key, const void * ptr, size_t count, size_t size, cmpFunc_t cmp)
Q_LinearSearch.
Parameters
[in] key
[in] ptr
[in] count
[in] size
[in] cmp
Returns
Note
Unused
Definition at line 2618 of file q_shared.c.
int Q_PrintStrlen (const char * string)
Q_PrintStrlen.
strlen that discounts Quake color sequences
Parameters
[in] string
Returns
Definition at line 1680 of file q_shared.c.
Referenced by CG_LoadPanel_RenderCampaignNameText(), SV_Status_f(), and UI_FeederItemText().
void Q_strcat (char * dest, size_t size, const char * src)
Q_strcat.
buffer size safe library replacements
Parameters
[out] dest
[in] size
[in] src
Note
Never goes past bounds or leaves without a terminating 0
Definition at line 1622 of file q_shared.c.
Referenced by BG_ParseConditionBits(), Binding_FromName(), BuildShaderStateConfig(), CalculateRanks(), CG_BuildLocationString(), CG_BuildSelectedFirteamString(), CG_Debriefing_ParseAwards(), CG_DPrintf(), CG_DrawCenterString(), CG_DrawObjectiveInfo(), CG_LocalizeServerCommand(), CG_LocateCampaign(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_Printf(), CG_RegisterAcc(), CL_Cache_EndGather_f(), CL_Cache_UsedFile_f(), CL_GlobalServers_f(), CL_Rcon_f(), CL_ServerInfoPacket(), CL_UpdateLevelHunkUsage(), ClientUserinfoChanged(), Cmd_Args(), Cmd_ArgsFrom(), Cmd_ArgsFromTo(), Cmd_CallVote_f(), Cmd_Echo_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), COM_DefaultExtension(), Com_InitUpdateDownloads(), Com_MD5File(), Com_Printf(), Com_TruncateLongString(), Con_Dump_f(), CreateShaderByGuide(), Field_Complete(), FS_ComparePaks(), FS_LoadedPakChecksums(), FS_LoadedPakNames(), FS_LoadedPakPureChecksums(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), FS_ReferencedPakPureChecksums(), FS_VerifyPak(), G_BuildEndgameStats(), G_createStats(), G_InitGame(), G_IntermissionMapList(), G_IntermissionVoteTally(), G_loadMatchGame(), G_MatchOnePlayer(), G_PlaySound_Cmd(), G_PrintAccuracyLog(), G_PushMapEntityToBuffer(), G_ReadConfigFileString(), G_Script_ScriptLoad(), G_Script_ScriptParse(), G_ScriptAction_ChangeModel(), G_SendScore_Add(), G_StoreMapXP(), G_weaponRankings_cmd(), G_weaponStatsLeaders_cmd(), G_WriteSessionData(), GLimp_DetectAvailableModes(), GLSL_FinnishShaderTextAndCompile(), GLSL_GenerateCheckSum(), GLSL_GenerateMacroString(), GLSL_GetShaderHeader(), GLSL_GetShaderText(), Item_EnableShowViaCvar(), Item_RunScript(), Key_Bind_f(), ParseMap(), ParseStage(), PC_Directive_include(), PC_MergeTokens(), PC_Script_Parse(), Q_StrReplace(), R_FindCubeImage(), R_FindImageFile(), R_ShaderExp_f(), RE_InitOpenGl(), S_AL_Init(), SP_misc_gamemodel(), SP_script_mover(), SVC_RemoteCommand(), Svcmd_EntityList_f(), Sys_BuildCommandLine(), Sys_DefaultHomePath(), UI_LoadPanel_RenderLoadingText(), UpdateIPBans(), WM_DrawClientScore(), and WM_DrawClientScore_Small().
int Q_stricmp (const char * s1, const char * s2)
Compare whole strings without case sensitivity.
Parameters
[in] s1
[in] s2
Returns
Definition at line 1569 of file q_shared.c.
Referenced by COM_CompareExtension(), Info_RemoveKey(), Info_RemoveKey_Big(), and Info_ValueForKey().
int Q_stricmpn (const char * s1, const char * s2, size_t n)
Compare strings without case sensitivity up to n characters.
Parameters
[in] s1
[in] s2
[in] n
Returns
Definition at line 1481 of file q_shared.c.
Referenced by _GetEntityName(), CG_DrawVote(), CG_SpeakerEditor_NoiseEdit_KeyDown(), CL_Connect_f(), CL_PlayDemo_f(), CL_PrintPacket(), Cmd_Give_f(), Com_AddStartupCommands(), Com_Error(), FindIndexMatch(), FindMatches(), FS_GetModList(), FS_IsDemoExt(), FS_ListFilteredFiles(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), IRC_AttemptConnection(), IRC_Say(), ParseDeform(), ParseShader(), ParseShaderR1(), PrintCvarMatches(), PrintMatches(), Q_stricmp(), Q_stristr(), Q_StrReplace(), R_FindCubeImage(), R_FindImageFile(), R_LoadPSA(), R_LoadPSK(), R_ShaderList_f(), RE_RegisterAnimation(), RE_RegisterModel(), RE_RegisterSkin(), Script_ConditionalScript(), Sys_Dialog(), and UI_SetActiveMenu().
const char* Q_stristr (const char * s, const char * find)
Find the first occurrence of find in s.
Parameters
[in] s
[in] find
Returns
Definition at line 1640 of file q_shared.c.
Referenced by CL_KeyEvent(), CreateShaderByGuide(), FindClientByName(), GL_CheckForExtension(), UI_BuildServerDisplayList(), and UI_FeederItemText().
char* Q_strlwr (char * s1)
Q_strlwr.
Parameters
[in,out] s1
Returns
Definition at line 1579 of file q_shared.c.
Referenced by BG_LoadTraceMap(), BG_RAG_ParseAnimFile(), CG_LoadObjectiveData(), CL_Cache_UsedFile_f(), FS_LoadZipFile(), G_Script_ScriptParse(), G_SpawnGEntityFromSpawnVars(), InitOpenGL(), ItemParse_cvar(), Key_SetBinding(), R_LoadMD3(), R_LoadMDC(), and RE_RegisterSkin().
int Q_strncmp (const char * s1, const char * s2, size_t n)
Compare strings up to n characters.
Parameters
[in] s1
[in] s2
[in] n
Returns
Definition at line 1539 of file q_shared.c.
Referenced by _GetEntityClass(), BG_AnimParseAnimScript(), BG_RAG_ParseAnimation(), CG_DPrintf(), CG_LocalizeServerCommand(), CG_Printf(), CL_Cache_UsedFile_f(), CL_ConnectionlessPacket(), CL_ConsolePrint(), CompareIPNoPort(), FS_AllowDeletion(), ETInterface::GetEntityCategory(), GetParsedIP(), main(), Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), R_FindCachedModel(), R_LoadEntities(), S_FindRIFFChunk(), SV_CheckClientCommand(), SV_CheckGameCommand(), SV_CheckServerCommand(), SV_ClientCommand(), SV_ConnectionlessPacket(), SV_ExecuteClientCommand(), SV_ExpandNewlines(), and Sys_BuildCommandLine().
void Q_strncpyz (char * dest, const char * src, size_t destsize)
Safe strncpy that ensures a trailing zero.
buffer size safe library replacements
Parameters
[out] dest
[in] src
[in] destsize
Definition at line 1455 of file q_shared.c.
Referenced by _et_G_LogPrint(), _et_G_Print(), _et_G_SetSpawnVar(), _et_gentity_set(), _et_Info_RemoveKey(), _et_Info_SetValueForKey(), _et_Q_CleanStr(), _et_RegisterModname(), _GetEntityName(), AddMaxLivesGUID(), AddRemap(), AutoBuildConstruction(), BeginIntermission(), BG_AddPathCorner(), BG_AddSplineControl(), BG_AddSplinePath(), BG_FindFreeCharacter(), BG_FitTextToWidth_Ext(), BG_RAG_FindFreeAnimation(), BG_RAG_ParseAnimFile(), Binding_FromName(), Bot_Event_ChatMessage(), Bot_Event_Death(), Bot_Event_KilledSomeone(), Bot_Event_Sound(), Bot_Event_VoiceMacro(), Bot_Util_SendTrigger(), CalculateRanks(), CC_svcvar(), CG_AddPMItem(), CG_AddPMItemBig(), CG_addString(), CG_CommandMap_SetHighlightText(), CG_ConfigStringCopy(), CG_ConfigStringModified(), CG_Debriefing_ParseAwards(), CG_DPrintf(), CG_DrawCenterString(), CG_DrawDemoRecording(), CG_DrawObjectiveInfo(), CG_DrawVote(), CG_DrawWarmup(), CG_EffectParse(), CG_EP_ParseFloats(), CG_EP_ParseInts(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_FitTextToWidth2(), CG_FitTextToWidth_Ext(), CG_FitTextToWidth_SingleLine(), CG_getBindKeyName(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderObjectiveText(), CG_LoadingString(), CG_LoadObjectiveData(), CG_LoadPanel_RenderMissionDescriptionText(), CG_LocateCampaign(), CG_ModifyEditSpeaker(), CG_NewClientInfo(), CG_Obituary(), CG_ObjectivePrint(), CG_ObjectivesDraw(), CG_ParseAnimationFiles(), CG_ParseFireteams(), CG_parseMapVoteListInfo(), CG_ParseOIDInfo(), CG_ParseServerinfo(), CG_ParseSpawns(), CG_ParseTagConnect(), CG_parseWeaponStats_cmd(), CG_parseWeaponStatsGS_cmd(), CG_Printf(), CG_printWindow(), CG_PriorityCenterPrint(), CG_QueueMusic(), CG_RegisterGraphics(), CG_RegisterPlayerClasses(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetupDlightstyles(), CG_SoundParseSounds(), CG_SpeakerEditor_NoiseEdit_KeyDown(), CG_SpeakerEditor_NoiseEditFinish(), CG_SpeakerEditor_TargetnameEditFinish(), CG_StartMusic(), CG_StatsDebugAddText(), CG_TeamRestrictionsChanged(), CG_TestModel_f(), CG_topshotsParse_cmd(), CG_TrimLeftPixels(), CG_UpdateSvCvars(), CG_VoiceChatLocal(), CheckForMG42(), CIN_PlayCinematic(), CL_AddReliableCommand(), CL_Cache_EndGather_f(), CL_Cache_UsedFile_f(), CL_CheckForResend(), CL_Connect_f(), CL_GetPing(), CL_GetPingInfo(), CL_MapLoading(), CL_MotdPacket(), CL_NextDemo(), CL_OpenAVIForWriting(), CL_ParseCommandString(), CL_ParseDownload(), CL_ParseSnapshot(), CL_PlayDemo_f(), CL_PrintPacket(), CL_Record(), CL_Record_f(), CL_ServerInfoPacket(), CL_ServerStatus(), CL_SetServerInfo(), CL_WriteWaveOpen(), ClearMaxLivesBans(), ClientCleanName(), ClientConnect(), ClientName(), ClientUserinfoChanged(), CM_LoadMap(), Cmd_ArgsBuffer(), Cmd_ArgvBuffer(), Cmd_CallVote_f(), Cmd_Exec_f(), Cmd_IntermissionPlayerKillsDeaths_f(), Cmd_IntermissionPlayerTime_f(), Cmd_IntermissionWeaponAccuracies_f(), Cmd_IntermissionWeaponStats_f(), Cmd_TokenizeString2(), Com_BeginDownload(), Com_GetAutoUpdate(), Com_GetCommandLine(), Com_InitUpdateDownloads(), Com_MD5File(), Com_ParseInfos(), Com_RunUpdateBinary(), Com_SetupDownload(), COM_StripExtension(), COM_StripFilename(), Com_TrackProfile(), Com_TruncateLongString(), Com_WriteConfig_f(), Con_Dump_f(), CON_HistAdd(), CON_HistNext(), CON_HistPrev(), CON_Input(), Console_Key(), CreateInternalShaders(), CreateShaderByGuide(), Cvar_InfoStringBuffer(), Cvar_LatchedVariableStringBuffer(), Cvar_Update(), Cvar_VariableStringBuffer(), DL_BeginDownload(), Do_Activate_f(), etpro_ScriptAction_SetValues(), Field_Complete(), Field_CompleteCommand(), FindIndexMatch(), FindMatches(), FS_AddBothGameDirectories(), FS_AddGameDirectory(), FS_CL_ExtractFromPakFile(), FS_CreatePath(), FS_FilenameCompletion(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_InitFilesystem(), FS_LoadZipFile(), FS_Restart(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_Unzip(), FS_VerifyOfficialPaks(), FS_VerifyPak(), func_constructiblespawn(), G_configSet(), G_GetPlayerByName(), G_InitGame(), G_InitWorldSession(), G_IntermissionMapList(), G_IntermissionVoteTally(), G_isValidConfig(), G_LoadCampaignsFromFile(), G_loadMatchGame(), G_LuaHook_ClientConnect(), G_LuaInit(), G_LuaRunIsolated(), G_LuaStackDump(), G_ParseAnimationFiles(), G_ParseSettings(), G_players_cmd(), G_PlaySound_Cmd(), G_PrintAccuracyLog(), G_PrintConfigs(), G_ProcessIPBans(), G_refClientnumForName(), G_RegisterPlayerClasses(), G_Say(), G_SayTo(), G_Script_ScriptLoad(), G_Script_ScriptParse(), G_ScriptAction_Accum(), G_ScriptAction_Cvar(), G_ScriptAction_GlobalAccum(), G_ScriptAction_MusicPlay(), G_ScriptAction_MusicQueue(), G_ScriptAction_MusicStart(), G_ScriptAction_PlayAnim(), G_ScriptAction_PlaySound(), G_ScriptAction_RepairMG42(), G_ScriptAction_SetAutoSpawn(), G_ScriptAction_SetChargeTimeFactor(), G_ScriptAction_SetDamagable(), G_ScriptAction_SetModelFromBrushmodel(), G_ScriptAction_SetState(), G_ScriptAction_ShaderRemap(), G_ScriptAction_TagConnect(), G_ScriptAction_Trigger(), G_SendScore(), G_Surrender_v(), G_UpdateCharacter(), G_weaponRankings_cmd(), G_WriteConfigFileString(), GetClientState(), GetClipboardData(), GetConfigString(), ETInterface::GetGoals(), GetMG42s(), GetOpType(), GLimp_EndFrame(), GLimp_InitExtensionsR2(), GLimp_InitOpenGLContext(), GLSL_CopyStringAlloc(), GLSL_InitGPUShader2(), GLSL_LoadDefinitions(), GLSL_PrintInfoLog(), IN_GetClipboardData(), InitShader(), IRC_AddSendItem(), IRC_AttemptConnection(), IRC_InitialiseUser(), Item_Text_Paint(), Key_GetBindingBuf(), Key_KeynumToStringBuf(), LAN_AddServer(), LAN_CompareServers(), LAN_GetServerAddressString(), LAN_GetServerInfo(), LAN_LoadCachedServers(), LAN_SaveServersToFile(), LoadScriptFile(), LoadScriptMemory(), LoadSourceFile(), misc_firetrails_think(), MSG_WriteBigString(), MSG_WriteString(), NET_AddLocalAddress(), NET_StringToAdr(), OSX_ApplicationSupportPath(), ParseShader(), ParseShaderR1(), ParseSkyParms(), PC_Directive_include(), PC_Int_Parse(), PC_String_ParseNoAlloc(), PS_ReadPunctuation(), Q_strcat(), Q_strreplace(), Q_StrReplace(), R_AllocImage(), R_CreateFBO(), R_CreateIBO(), R_CreateIBO2(), R_CreateVBO(), R_CreateVBO2(), R_FindCubeImage(), R_FindImageFile(), R_FindShader(), R_GetEntityToken(), R_InitSkins(), R_inPVS(), R_LerpTag(), R_LoadCacheImages(), R_LoadCacheModels(), R_LoadCacheShaders(), R_LoadEntities(), R_LoadImage(), R_LoadLightmapsExternal(), R_LoadLights(), R_LoadMD3(), R_LoadMD5(), R_LoadMD5Anim(), R_LoadMDC(), R_LoadMDM(), R_LoadPreRenderedFont(), R_LoadPSA(), R_LoadPSK(), R_LoadScalableFont(), R_PrintLongString(), R_TakeScreenshot(), RB_RenderDebugUtils(), RE_BuildSkeleton(), RE_GetSkinModel(), RE_InitOpenGl(), RE_LerpTagET(), RE_LerpTagQ3A(), RE_LoadDynamicShader(), RE_LoadWorldMap(), RE_RegisterAnimation(), RE_RegisterModel(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), ETInterface::RemoveBot(), S_CodecLoad(), S_CodecOpenStream(), S_FindCodecForFile(), S_Play_f(), S_StartStreamingSoundEx(), S_UpdateStreamingSounds(), ScanAndLoadShaderFilesR1(), Script_ConditionalScript(), setProjTargetOrigin(), SP_func_brushmodel(), SP_func_debris(), SP_func_explosive(), SP_script_mover(), SP_target_explosion(), SP_target_speaker(), SP_team_WOLF_objective(), SP_trigger_objective_info(), SP_worldspawn(), SV_AddServerCommand(), SV_BeginDownload_f(), SV_CheckClientCommand(), SV_CheckLastCmd(), SV_DemoAutoDemoRecord(), SV_DemoCvarsRestore(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DemoStartPlayback(), SV_DemoWriteClientUserinfo(), SV_DirectConnect(), SV_Frame(), SV_GameSystemCalls(), SV_GetConfigstring(), SV_GetPlayerByName(), SV_GetServerinfo(), SV_GetUserinfo(), SV_LoadTag(), SV_Map_f(), SV_MapRestart_f(), SV_Netchan_Transmit(), SV_SetupDownloadFile(), SV_SetUserinfo(), SV_UpdateConfigStrings(), SV_UpdateUserinfo_f(), SV_UserinfoChanged(), Svcmd_CSInfo_f(), Svcmd_Fling(), Sys_AppendToExecBuffer(), Sys_Basename(), Sys_DefaultHomePath(), Sys_Dirname(), Sys_SetBinaryPath(), Sys_SetDefaultInstallPath(), TeamplayInfoMessage(), Think_SetupObjectiveInfo(), TryConstructing(), UI_BuildPlayerList(), UI_BuildServerDisplayList(), UI_DrawServerRefreshDate(), UI_FeederItemText(), UI_FeederSelectionClick(), UI_GetServerStatusInfo(), UI_Init(), UI_Load(), UI_RunMenuScript(), UI_SetActiveMenu(), UI_SortArenas(), UI_SortCampaigns(), VM_Create(), VM_LoadSymbols(), and VM_Restart().
char* Q_StrReplace (char * haystack, const char * needle, const char * newVal)
Q_StrReplace.
replace all occuraces in haystack if needle with new
Parameters
[in,out] haystack
[in] needle
[in] newVal
Returns
Definition at line 2456 of file q_shared.c.
Referenced by BeginIntermission(), and G_PrintConfigs().
char* Q_strupr (char * s1)
Q_strupr.
Parameters
[in,out] s1
Returns
Definition at line 1599 of file q_shared.c.
Referenced by Binding_FromName(), CG_DrawFireTeamOverlay(), CG_getBindKeyName(), CG_LimboPanel_ClassBar_Draw(), CG_SpeakerEditorDraw(), G_LuaRunIsolated(), and UI_LoadMovies().
short ShortNoSwap (short l)
ShortNoSwap.
Parameters
[in] l
Returns
Note
Unused
Definition at line 277 of file q_shared.c.
short ShortSwap (short l)
ShortSwap.
Parameters
[in] l
Returns
Definition at line 261 of file q_shared.c.
void SkipBracedSection (char ** program)
The next token should be an open brace. Skips until a matching close brace is found. Internal brace depths are properly skipped.
Parameters
[in] program
Definition at line 1056 of file q_shared.c.
Referenced by BuildShaderChecksumLookup(), FindGuideInGuideText(), FindShaderInShaderText(), GLSL_FindDefinitionInText(), and ScanAndLoadShaderFilesR1().
void SkipBracedSection_Depth (char ** program, int depth)
SkipBracedSection_Depth.
start at given depth if already
Parameters
program
depth
Note
Unused
Definition at line 1027 of file q_shared.c.
void SkipRestOfLine (char ** data)
SkipRestOfLine.
Parameters
[in,out] data
Definition at line 1083 of file q_shared.c.
Referenced by ParseExpression(), ParseShader(), ParseShaderR1(), and ParseStage().
static char* SkipWhitespace (char * data, qboolean * hasNewLines) static
Parse a token out of a string Will never return NULL, just empty strings.
If "allowLineBreaks" is qtrue then an empty string will be returned if the next token is a newline.
Parameters
[in,out] data
[out] hasNewLines
Returns
Definition at line 465 of file q_shared.c.
Referenced by COM_ParseExt(), and COM_ParseExt2().
float* tv (float x, float y, float z)
This is just a convenience function for making temporary vectors for function calls.
Parameters
[in] x
[in] y
[in] z
Returns
See also
This is straight out of g_utils.c around line 210
Definition at line 2049 of file q_shared.c.
Referenced by artillerySpotterThink(), CG_BulletImpact(), CG_GibPlayer(), CG_LoseHat(), CG_Player(), CG_ShakeCamera(), CG_TouchTriggerPrediction(), ClientEndFrame(), ClientThink_real(), func_explosive_explode(), G_AirStrikeThink(), G_DrawEntBBox(), IsHeadShot(), IsLegShot(), and props_locker_spawn_item().
char* QDECL va (const char * format, ...)
Does a varargs printf into a temp buffer, so I don't need to have varargs versions of all text functions.
Parameters
[in] format
Returns
Todo:
FIXME: make this buffer size safe someday
Todo:
modified this into a circular list, to further prevent stepping on previous strings
Definition at line 1987 of file q_shared.c.
Variable Documentation
int backup_lines static
Definition at line 359 of file q_shared.c.
Referenced by COM_BackupParseSession(), and COM_RestoreParseSession().
char* backup_text static
Definition at line 360 of file q_shared.c.
Referenced by COM_BackupParseSession(), and COM_RestoreParseSession().
int com_lines static
Definition at line 357 of file q_shared.c.
Referenced by COM_BackupParseSession(), COM_BeginParseSession(), COM_GetCurrentParseLine(), COM_ParseError(), COM_ParseExt(), COM_ParseExt2(), COM_RestoreParseSession(), COM_SetCurrentParseLine(), SkipRestOfLine(), and SkipWhitespace().
char com_parsename[MAX_TOKEN_CHARS] static
Definition at line 356 of file q_shared.c.
Referenced by COM_BeginParseSession(), and COM_ParseError().
char com_token[MAX_TOKEN_CHARS] static
Definition at line 355 of file q_shared.c.
Referenced by CG_ParseSpawnVars(), COM_ParseExt(), COM_ParseExt2(), CommaParse(), and G_ParseSpawnVars().
punctuation
Initial value:
=
{
    "+=", "-=", "*=", "/=", "&=", "|=", "++", "--",
    "&&", "||", "<=", ">=", "==", "!=",
    NULL
}
Multiple character punctuation tokens.
Definition at line 348 of file q_shared.c.
Referenced by COM_ParseExt2(), and ParseExpressionElement().