ET: Legacy: src/qcommon/q_unicode.h File Reference
q_unicode.h File Reference
Unicode & UTF-8 handling.
Macros
#define UNICODE_SUPPORT_VERSION 273
#define INVALID_CHAR_OFFSET 215
Functions
int Q_UTF8_Width (const char *str)
Never returns more than 4.
int Q_UTF8_WidthCP (int ch)
Q_UTF8_WidthCP.
int Q_UTF8_Strlen (const char *str)
Q_UTF8_Strlen.
int Q_UTF8_PrintStrlen (const char *str)
Q_UTF8_PrintStrlen.
int Q_UTF8_ByteOffset (const char *str, int offset)
Q_UTF8_ByteOffset.
void Q_UTF8_Insert (char *dest, int size, int offset, int key, qboolean overstrike)
Q_UTF8_Insert.
void Q_UTF8_Move (char *data, size_t offset1, size_t offset2, size_t size)
Q_UTF8_Move.
qboolean Q_UTF8_ContByte (char c)
Q_UTF8_ContByte.
unsigned long Q_UTF8_CodePoint (const char *str)
Calculates codepoint for a single char.
void Q_UTF8_RegisterFont (const char *fontName, int pointSize, fontHelper_t *font, qboolean extended, void(*font_register)(const char *, int, void *))
Q_UTF8_RegisterFont.
void Q_UTF8_FreeFont (fontHelper_t *font)
Q_UTF8_FreeFont.
char * Q_UTF8_Encode (unsigned long codepoint)
Q_UTF8_Encode.
int Q_UTF8_Store (const char *s)
Stores a single UTF8 char inside an int.
char * Q_UTF8_Unstore (int e)
Converts a single UTF8 char stored as an int into a byte array.
void Q_UTF8_ToUTF32 (char *string, int *charArray, int *outlen)
Q_UTF8_ToUTF32.
Detailed Description
Unicode & UTF-8 handling.
The whole unicode handling system was published at cprogramming.com by Jeff Bezanson and adapted for the id Tech 3 engine by Unvanquished developers.
Definition in file q_unicode.h.
Macro Definition Documentation
#define INVALID_CHAR_OFFSET 215
Definition at line 53 of file q_unicode.h.
Referenced by Q_UTF8_GetGlyphExtended(), and Q_UTF8_GetGlyphVanilla().
#define UNICODE_SUPPORT_VERSION 273
Todo:
: change this to 273 before release...!!!
Definition at line 50 of file q_unicode.h.
Referenced by trap_R_RegisterFont(), and trap_TranslateString().
Function Documentation
int Q_UTF8_ByteOffset (const char * str, int offset)
Q_UTF8_ByteOffset.
Parameters
[in] str
[in] offset
Returns
Definition at line 164 of file q_unicode.c.
Referenced by Field_CharEvent(), Q_UTF8_Insert(), and Q_UTF8_Move().
unsigned long Q_UTF8_CodePoint (const char * str)
Calculates codepoint for a single char.
Parameters
str character to convert
Returns
codepoint of a character
Definition at line 356 of file q_unicode.c.
Referenced by CL_ConsolePrint(), SCR_DrawStringExt(), and Text_Paint_Ext().
qboolean Q_UTF8_ContByte (char c)
Q_UTF8_ContByte.
Parameters
[in] c
Returns
Definition at line 272 of file q_unicode.c.
char* Q_UTF8_Encode (unsigned long codepoint)
Q_UTF8_Encode.
Parameters
[in] codepoint
Returns
Definition at line 414 of file q_unicode.c.
Referenced by Q_UTF8_Insert().
void Q_UTF8_FreeFont (fontHelper_t * font)
Q_UTF8_FreeFont.
Parameters
[in,out] font
Definition at line 595 of file q_unicode.c.
Referenced by CG_Shutdown(), Q_UTF8_RegisterFont(), and UI_Shutdown().
void Q_UTF8_Insert (char * dest, int size, int offset, int key, qboolean overstrike)
Q_UTF8_Insert.
Parameters
[in,out] dest
[in] size
[in] offset
[in] key
[in] overstrike
Definition at line 198 of file q_unicode.c.
Referenced by Field_CharEvent(), and Item_TextField_InsertToCursor().
void Q_UTF8_Move (char * data, size_t offset1, size_t offset2, size_t size)
Q_UTF8_Move.
Parameters
[in,out] data
[in] offset1
[in] offset2
[in] size
Definition at line 240 of file q_unicode.c.
Referenced by Item_TextField_HandleKey().
int Q_UTF8_PrintStrlen (const char * str)
Q_UTF8_PrintStrlen.
Parameters
[in] str
Returns
Definition at line 134 of file q_unicode.c.
Referenced by CG_FormatCenterPrint().
void Q_UTF8_RegisterFont (const char * fontName, int pointSize, fontHelper_t * font, qboolean extended, void(*)(const char *, int, void *) font_register)
Q_UTF8_RegisterFont.
Parameters
[in] fontName
[in] pointSize
[in,out] font
[in] extended
font_register
Definition at line 568 of file q_unicode.c.
int Q_UTF8_Store (const char * s)
Stores a single UTF8 char inside an int.
Parameters
[in] s
Returns
Definition at line 459 of file q_unicode.c.
int Q_UTF8_Strlen (const char * str)
Q_UTF8_Strlen.
Parameters
[in] str
Returns
Definition at line 115 of file q_unicode.c.
Referenced by CG_Text_Height_Ext(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), CG_Text_Width_Ext(), Field_CharEvent(), Item_CalcTextFieldCursor(), Item_TextField_HandleKey(), Multiline_Text_Height(), Multiline_Text_Width(), Q_UTF8_Move(), Text_Height_Ext(), Text_Paint_Ext(), Text_Paint_Limit(), Text_PaintWithCursor_Ext(), Text_Width_Ext(), and UI_BuildServerDisplayList().
void Q_UTF8_ToUTF32 (char * string, int * charArray, int * outlen)
Q_UTF8_ToUTF32.
Parameters
[in,out] string
[in] charArray
[out] outlen
Definition at line 614 of file q_unicode.c.
Referenced by Item_TextField_HandleKey().
char* Q_UTF8_Unstore (int e)
Converts a single UTF8 char stored as an int into a byte array.
Parameters
[in] e
Returns
Definition at line 503 of file q_unicode.c.
int Q_UTF8_Width (const char * str)
Never returns more than 4.
Parameters
[in] str
Returns
Definition at line 47 of file q_unicode.c.
Referenced by CG_DrawCenterString(), CG_DrawObjectiveInfo(), CG_FormatCenterPrint(), CG_Text_Height_Ext(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), CG_Text_Width_Ext(), CL_ConsolePrint(), Item_Text_AutoWrapped_Paint(), Multiline_Text_Height(), Multiline_Text_Width(), Q_UTF8_ByteOffset(), Q_UTF8_CodePoint(), Q_UTF8_Insert(), Q_UTF8_PrintStrlen(), Q_UTF8_Strlen(), SCR_DrawStringExt(), Text_Height_Ext(), Text_Paint_Ext(), Text_Paint_Limit(), Text_PaintWithCursor_Ext(), and Text_Width_Ext().
int Q_UTF8_WidthCP (int ch)
Q_UTF8_WidthCP.
Parameters
[in] ch
Returns
Definition at line 89 of file q_unicode.c.
Referenced by Q_UTF8_Insert().