ET: Legacy: src/qcommon/qcommon.h File Reference
qcommon.h File Reference
Definitions common between client and server, but not game or ref modules.
#include "../qcommon/cm_public.h"
#include <unistd.h>
#include "dl_public.h"
#include "json_public.h"
Data Structures
struct msg_t
struct netadr_t
struct netchan_t
Netchan handles packet fragmentation and out of order / duplicate suppression.
struct download_t
download_t
struct autoupdate_t
struct modHash
struct field_t
struct sysEvent_t
struct nodetype
struct huff_t
struct huffman_t
Macros
#define __attribute__(x)
#define NET_ENABLEV4 0x01
#define NET_ENABLEV6 0x02
#define NET_PRIOV6 0x04
if this flag is set, always attempt ipv6 connections instead of ipv4 if a v6 address is found.
#define NET_DISABLEMCAST 0x08
#define PACKET_BACKUP 32
number of old messages that must be kept on client and server for delta comrpession and ping estimation
#define PACKET_MASK (PACKET_BACKUP - 1)
#define MAX_PACKET_USERCMDS 32
max number of usercmd_t in a packet
#define PORT_ANY -1
#define MAX_RELIABLE_COMMANDS 256
max string commands buffered for restransmit
#define NET_ADDRSTRMAXLEN 48
maximum length of an IPv6 address string including trailing '\0'
#define NET_ADDRSTRMAXLEN_EXT 56
#define MAX_MSGLEN 32768
max length of a message, which may be fragmented into multiple packets
#define MAX_DOWNLOAD_WINDOW 48
ACK window of 48 download chunks.Cannot set this higher, or clients will overflow the reliable commands buffer.
#define MAX_DOWNLOAD_BLKSIZE 1024
896 byte block chunks
#define DLTYPE_WWW -1
block -1 means www/ftp download
#define AUTOUPDATE_DIR "update"
#define PROTOCOL_MISMATCH_ERROR "ERROR: Protocol Mismatch Between Client and Server.\The server you are attempting to join is running an incompatible version of the game."
sent by the server, printed on connection screen, works for all clients (restrictions: does not handle
, no more than 256 chars)
#define PROTOCOL_MISMATCH_ERROR_LONG "ERROR: Protocol Mismatch Between Client and Server.\n\n\The server you attempted to join is running an incompatible version of the game.\n\You or the server may be running older versions of the game. Press the auto-update\ button if it appears on the Main Menu screen."
long version used by the client in diagnostic window
#define GAMENAME_STRING "et"
#define PROTOCOL_VERSION 84
#define MOTD_SERVER_NAME "motd.etlegacy.com"
location of the message of the day server
#define UPDATE_SERVER_NAME "update.etlegacy.com"
location of the update server
#define PORT_MASTER 27950
#define PORT_MOTD 27951
#define PORT_UPDATE 27951
#define PORT_SERVER 27960
#define NUM_SERVER_PORTS 4
#define VM_CALL_END -1337
This should be something like INT_MAX but that would need limits.h everywhere so meh and negative values should be somewhat safe.
#define VM_Call(vm, ...) VM_CallFunc(vm, __VA_ARGS__, VM_CALL_END)
#define VMA(x) VM_ArgPtr(args[x])
#define VMF(x) _vmf(args[x])
#define EXPAND(x) x
#define GET_MACRO(_1, _2, _3, _4, NAME, ...) NAME
#define Cmd_AddCommand1(x) Cmd_AddSystemCommand(x, NULL, NULL, NULL)
#define Cmd_AddCommand2(x, y) Cmd_AddSystemCommand(x, y, NULL, NULL)
#define Cmd_AddCommand3(x, y, z) Cmd_AddSystemCommand(x, y, z, NULL)
#define Cmd_AddCommand4(x, y, z, i) Cmd_AddSystemCommand(x, y, z, i)
#define Cmd_AddCommand(...) EXPAND(GET_MACRO(__VA_ARGS__, Cmd_AddCommand4, Cmd_AddCommand3, Cmd_AddCommand2, Cmd_AddCommand1) (__VA_ARGS__))
#define BASEGAME "etmain"
#define DEFAULT_MODGAME "legacy"
#define IS_LEGACY_MOD (modHashes.defaultMod == modHashes.currentMod)
#define FS_GENERAL_REF 0x01
#define FS_UI_REF 0x02
#define FS_CGAME_REF 0x04
#define FS_QAGAME_REF 0x08
#define NUM_ID_PAKS 9
number of id paks that will never be autodownloaded from etmain
#define MAX_FILE_HANDLES 64
#define MAX_FOUND_FILES 0x1000
Max return of listing files.
#define Q_rmdir rmdir
#define FS_EXCLUDE_DIR 0x1
#define FS_EXCLUDE_PK3 0x2
#define MAX_EDIT_LINE 512
#define AVI_LINE_PADDING 4
#define Sys_GetDLLName(x) x ".mp." ARCH_STRING DLL_EXT
#define NYT HMAX
NYT = Not Yet Transmitted.
#define INTERNAL_NODE (HMAX + 1)
#define HMAX 256
Maximum symbol.
#define SV_ENCODE_START 4
#define SV_DECODE_START 12
#define CL_ENCODE_START 12
#define CL_DECODE_START 4
#define _(x) I18N_Translate(x)
#define __(x) I18N_TranslateMod(x)
Typedefs
typedef struct vm_s vm_t
typedef enum vmSlots_e vmSlots_t
typedef void(* xcommand_t) (void)
typedef void(* completionFunc_t) (char *args, int argNum)
typedef struct nodetype node_t
Enumerations
enum netadrtype_t {
NA_BAD = 0, NA_BOT, NA_LOOPBACK, NA_BROADCAST,
NA_IP, NA_IP6, NA_MULTICAST6, NA_UNSPEC
}
enum netsrc_t { NS_CLIENT, NS_SERVER }
enum svc_ops_e {
svc_bad, svc_nop, svc_gamestate, svc_configstring,
svc_baseline, svc_serverCommand, svc_download, svc_snapshot,
svc_EOF
}
Server to client.
enum clc_ops_e {
clc_bad, clc_nop, clc_move, clc_moveNoDelta,
clc_clientCommand, clc_EOF
}
Client to server.
enum vmInterpret_t { VMI_NATIVE, VMI_BYTECODE, VMI_COMPILED }
enum vmSlots_e { VM_GAME = 0, VM_CGAME, VM_UI, MAX_VM }
enum sharedTraps_t {
TRAP_MEMSET = 100, TRAP_MEMCPY, TRAP_STRNCPY, TRAP_SIN,
TRAP_COS, TRAP_ATAN2, TRAP_SQRT, TRAP_MATRIXMULTIPLY,
TRAP_ANGLEVECTORS, TRAP_PERPENDICULARVECTOR, TRAP_FLOOR, TRAP_CEIL,
TRAP_TESTPRINTINT, TRAP_TESTPRINTFLOAT
}
enum memtag_t {
TAG_FREE, TAG_GENERAL, TAG_BOTLIB, TAG_RENDERER,
TAG_SMALL, TAG_STATIC
}
enum UPDATE_FLAGS { CLEAR_STATUS = 0, CLEAR_FLAGS, CLEAR_ALL }
enum joystickAxis_t {
AXIS_SIDE, AXIS_FORWARD, AXIS_UP, AXIS_ROLL,
AXIS_YAW, AXIS_PITCH, MAX_JOYSTICK_AXIS
}
enum sysEventType_t {
SE_NONE = 0, SE_KEY, SE_CHAR, SE_MOUSE,
SE_JOYSTICK_AXIS, SE_CONSOLE
}
enum dialogResult_t { DR_YES = 0, DR_NO = 1, DR_OK = 0, DR_CANCEL = 1 }
enum dialogType_t {
DT_INFO, DT_WARNING, DT_ERROR, DT_YES_NO,
DT_OK_CANCEL
}
Functions
void MSG_Init (msg_t *buf, byte *data, int length)
MSG_Init.
void MSG_InitOOB (msg_t *buf, byte *data, int length)
MSG_InitOOB.
void MSG_Clear (msg_t *buf)
MSG_Clear.
void * MSG_GetSpace (msg_t *buf, int length)
void MSG_WriteData (msg_t *buf, const void *data, int length)
MSG_WriteData.
void MSG_Bitstream (msg_t *buf)
MSG_Bitstream.
void MSG_Uncompressed (msg_t *buf)
MSG_Uncompressed.
void MSG_Copy (msg_t *buf, byte *data, int length, msg_t *src)
MSG_Copy.
void MSG_WriteBits (msg_t *msg, int value, int bits)
MSG_WriteBits.
void MSG_WriteChar (msg_t *msg, int c)
MSG_WriteChar.
void MSG_WriteByte (msg_t *msg, int c)
MSG_WriteByte.
void MSG_WriteShort (msg_t *msg, int c)
MSG_WriteShort.
void MSG_WriteLong (msg_t *msg, int c)
MSG_WriteLong.
void MSG_WriteFloat (msg_t *msg, float f)
MSG_WriteFloat.
void MSG_WriteString (msg_t *msg, const char *s)
MSG_WriteString.
void MSG_WriteBigString (msg_t *msg, const char *s)
MSG_WriteBigString.
void MSG_WriteAngle16 (msg_t *msg, float f)
MSG_WriteAngle16.
int MSG_HashKey (const char *string, int maxlen)
void MSG_BeginReading (msg_t *msg)
MSG_BeginReading.
void MSG_BeginReadingOOB (msg_t *msg)
void MSG_BeginReadingUncompressed (msg_t *msg)
MSG_BeginReadingUncompressed.
int MSG_ReadBits (msg_t *msg, int bits)
MSG_ReadBits.
int MSG_ReadChar (msg_t *msg)
MSG_ReadChar.
int MSG_ReadByte (msg_t *msg)
MSG_ReadByte.
int MSG_ReadShort (msg_t *msg)
MSG_ReadShort.
int MSG_ReadLong (msg_t *msg)
MSG_ReadLong.
float MSG_ReadFloat (msg_t *msg)
MSG_ReadFloat.
char * MSG_ReadString (msg_t *msg)
MSG_ReadString.
char * MSG_ReadBigString (msg_t *msg)
MSG_ReadBigString.
char * MSG_ReadStringLine (msg_t *msg)
MSG_ReadStringLine.
float MSG_ReadAngle16 (msg_t *msg)
MSG_ReadAngle16.
void MSG_ReadData (msg_t *msg, void *data, int size)
MSG_ReadData.
void MSG_WriteDeltaUsercmdKey (msg_t *msg, int key, usercmd_t *from, usercmd_t *to)
MSG_WriteDeltaUsercmdKey.
void MSG_ReadDeltaUsercmdKey (msg_t *msg, int key, usercmd_t *from, usercmd_t *to)
MSG_ReadDeltaUsercmdKey.
void MSG_WriteDeltaEntity (msg_t *msg, entityState_t *from, entityState_t *to, qboolean force)
Writes part of a packetentities message, including the entity number. Can delta from either a baseline or a previous packet_entity If to is NULL, a remove entity update will be sent If force is not set, then nothing at all will be generated if the entity is identical, under the assumption that the in-order delta code will catch it.
void MSG_ReadDeltaEntity (msg_t *msg, entityState_t *from, entityState_t *to, int number)
The entity number has already been read from the message, which is how the from state is identified.
void MSG_WriteDeltaSharedEntity (msg_t *msg, void *from, void *to, qboolean force, int number)
MSG_WriteDeltaSharedEntity.
void MSG_ReadDeltaSharedEntity (msg_t *msg, void *from, void *to, int number)
MSG_ReadDeltaSharedEntity.
void MSG_WriteDeltaPlayerstate (msg_t *msg, struct playerState_s *from, struct playerState_s *to)
MSG_WriteDeltaPlayerstate.
void MSG_ReadDeltaPlayerstate (msg_t *msg, struct playerState_s *from, struct playerState_s *to)
MSG_ReadDeltaPlayerstate.
void MSG_ReportChangeVectors_f (void)
Prints out a table from the current statistics for copying to code.
void NET_Init (void)
NET_Init.
void NET_Shutdown (void)
NET_Shutdown.
void NET_Restart_f (void)
NET_Restart_f.
void NET_SendPacket (netsrc_t sock, int length, const void *data, netadr_t to)
NET_SendPacket.
void QDECL NET_OutOfBandPrint (netsrc_t sock, netadr_t adr, const char *format,...)
Sends a text message in an out-of-band datagram.
void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, const char *format, int len)
Sends a data message in an out-of-band datagram (only used for "connect")
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
NET_CompareAdr.
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
Compares ip addresses without the port.
qboolean NET_IsLocalAddress (netadr_t adr)
NET_IsLocalAddress.
qboolean NET_IsLocalAddressString (const char *address)
NET_IsLocalAddressString.
qboolean NET_IsIPXAddress (const char *buf)
const char * NET_AdrToString (netadr_t a)
Returns address & port.
const char * NET_AdrToStringNoPort (netadr_t a)
NET_AdrToStringNoPort.
int NET_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
Traps "localhost" for loopback, passes everything else to system.
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t *net_from, msg_t *net_message)
NET_GetLoopPacket.
void NET_Sleep (int msec)
Sleeps msec or until something happens on the network.
void Netchan_Init (int port)
Netchan_Init.
void Netchan_Setup (netsrc_t sock, netchan_t *chan, netadr_t adr, int qport)
Called to open a channel to a remote system.
void Netchan_Transmit (netchan_t *chan, int length, const byte *data)
Sends a message to a connection, fragmenting if necessary A 0 length will still generate a packet.
void Netchan_TransmitNextFragment (netchan_t *chan)
Send one fragment of the current message.
qboolean Netchan_Process (netchan_t *chan, msg_t *msg)
Msg must be large enough to hold MAX_MSGLEN, because if this is the final fragment of a multi-part message, the entire thing will be copied out.
void VM_Init (void)
VM_Init.
vm_t * VM_Create (const char *module, qboolean extract, intptr_t(*systemCalls)(intptr_t *), vmInterpret_t interpret)
If image ends in .qvm it will be interpreted, otherwise it will attempt to load as a system dll.
void VM_Free (vm_t *vm)
VM_Free.
void VM_Clear (void)
VM_Clear.
vm_t * VM_Restart (vm_t *vm)
Reload the data, but leave everything else in place This allows a server to do a map_restart without changing memory allocation.
intptr_t QDECL VM_CallFunc (vm_t *vm, int callNum,...)
VM_CallFunc.
void VM_Debug (int level)
VM_Debug.
void * VM_ArgPtr (intptr_t intValue)
VM_ArgPtr.
void * VM_ExplicitArgPtr (vm_t *vm, intptr_t intValue)
VM_ExplicitArgPtr.
static ID_INLINE float _vmf (intptr_t x)
_vmf
void Cbuf_Init (void)
allocates an initial text buffer that will grow as needed
void Cbuf_AddText (const char *text)
Adds command text at the end of the buffer, does NOT add a final
.
void Cbuf_ExecuteText (int exec_when, const char *text)
this can be used in place of either Cbuf_AddText or Cbuf_InsertText
void Cbuf_Execute (void)
Cbuf_Execute.
void Cmd_Init (void)
Cmd_Init.
void Cmd_AddSystemCommand (const char *cmd_name, xcommand_t function, const char *description, completionFunc_t complete)
Cmd_AddSystemCommand.
void Cmd_RemoveCommand (const char *cmd_name)
Cmd_RemoveCommand.
void Cmd_RemoveCommandSafe (const char *cmd_name)
Only remove commands with no associated function Already removed in ETL: +button4, -button4 Allowed to remove: +lookup, +lookdown, -lookup, +lookup, configstrings.
void Cmd_CommandCompletion (void(*callback)(const char *s))
callback with each valid string
void Cmd_SetCommandCompletionFunc (const char *command, completionFunc_t complete)
Cmd_SetCommandCompletionFunc.
void Cmd_SetCommandDescription (const char *command, const char *description)
Cmd_SetCommandDescription.
void Cmd_CompleteArgument (const char *command, char *args, int argNum)
Cmd_CompleteArgument.
void Cmd_SaveCmdContext (void)
void Cmd_RestoreCmdContext (void)
int Cmd_Argc (void)
Cmd_Argc.
char * Cmd_Argv (int arg)
Cmd_Argv.
void Cmd_ArgvBuffer (int arg, char *buffer, size_t bufferLength)
The interpreted versions use this because they can't have pointers returned to them.
char * Cmd_Args (void)
Cmd_Args.
char * Cmd_ArgsFrom (int arg)
Cmd_ArgsFrom.
char * Cmd_ArgsFromTo (int arg, int max)
Cmd_ArgsFromTo.
void Cmd_ArgsBuffer (char *buffer, size_t bufferLength)
The interpreted versions use this because they can't have pointers returned to them.
char * Cmd_Cmd (void)
Retrieve the unmodified command string. For rcon use when you want to transmit without altering quoting.
void Cmd_Args_Sanitize (void)
Replaces command separators with space to prevent interpretation.
void Cmd_TokenizeString (const char *text)
Cmd_TokenizeString.
void Cmd_TokenizeStringIgnoreQuotes (const char *text_in)
Cmd_TokenizeStringIgnoreQuotes.
void Cmd_ExecuteString (const char *text)
A complete command line has been parsed, so try to execute it.
cvar_t * Cvar_Get (const char *varName, const char *value, int flags)
If the variable already exists, the value will not be set unless CVAR_ROM The flags will be or'ed in if the variable exists.
void Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
Basically a slightly modified Cvar_Get for the interpreted modules.
void Cvar_Update (vmCvar_t *vmCvar)
Updates an interpreted modules' version of a cvar.
void Cvar_Set (const char *varName, const char *value)
Cvar_Set.
cvar_t * Cvar_Set2 (const char *var_name, const char *value, qboolean force)
Cvar_Set2.
void Cvar_SetSafe (const char *var_name, const char *value)
Cvar_SetSafe.
void Cvar_SetLatched (const char *var_name, const char *value)
Cvar_SetLatched.
void Cvar_SetValue (const char *var_name, float value)
Cvar_SetValue.
void Cvar_SetValueSafe (const char *var_name, float value)
Cvar_SetValueSafe.
float Cvar_VariableValue (const char *var_name)
Cvar_VariableValue.
int Cvar_VariableIntegerValue (const char *var_name)
Cvar_VariableIntegerValue.
char * Cvar_VariableString (const char *var_name)
Cvar_VariableString.
void Cvar_VariableStringBuffer (const char *var_name, char *buffer, size_t bufsize)
Cvar_VariableStringBuffer.
void Cvar_LatchedVariableStringBuffer (const char *var_name, char *buffer, size_t bufsize)
Cvar_LatchedVariableStringBuffer.
int Cvar_Flags (const char *var_name)
Cvar_Flags.
void Cvar_CommandCompletion (void(*callback)(const char *s))
Cvar_CommandCompletion.
void Cvar_Reset (const char *var_name)
Cvar_Reset.
void Cvar_ForceReset (const char *var_name)
Cvar_ForceReset.
void Cvar_SetCheatState (void)
Any testing variables will be reset to the safe values.
qboolean Cvar_Command (void)
Handles variable inspection and changing from the console.
void Cvar_WriteVariables (fileHandle_t f)
Appends lines containing "set variable value" for all variables with the archive flag set to qtrue.
void Cvar_Init (void)
Reads in all archived cvars.
char * Cvar_InfoString (int bit)
Cvar_InfoString.
char * Cvar_InfoString_Big (int bit)
Handles large info strings (CS_SYSTEMINFO)
void Cvar_InfoStringBuffer (int bit, char *buff, size_t buffsize)
Cvar_InfoStringBuffer.
void Cvar_CheckRange (cvar_t *cv, float minVal, float maxVal, qboolean shouldBeIntegral)
cvar range check
void Cvar_SetDescription (cvar_t *cv, const char *varDescription)
Cvar_SetDescription.
void Cvar_Restart (qboolean unsetVM)
Resets all cvars to their hardcoded values and removes userdefined variables and variables added via the VMs if requested.
void Cvar_Restart_f (void)
Resets all cvars to their hardcoded values.
void Cvar_CompleteCvarName (char *args, int argNum)
Cvar_CompleteCvarName.
qboolean FS_Initialized (void)
FS_Initialized.
void FS_InitFilesystem (void)
Called only at initial startup, not when the filesystem is resetting due to a game change.
void FS_Shutdown (qboolean closemfp)
Frees all resources and closes all files.
qboolean FS_ConditionalRestart (int checksumFeed)
Restart if necessary.
void FS_Restart (int checksumFeed)
FS_Restart.
char ** FS_ListFiles (const char *path, const char *extension, int *numfiles)
FS_ListFiles.
void FS_FreeFileList (char **list)
FS_FreeFileList.
qboolean FS_FileExists (const char *file)
Tests if the file exists in the current gamedir of fs_homepath.
qboolean FS_SV_FileExists (const char *file)
Tests if the file in fs_homepath exists.
qboolean FS_IsSamePath (const char *s1, const char *s2)
Similar to FS_PathCmp() but real path name comparison. It deals with trailing slashes and relative paths.
qboolean FS_CreatePath (const char *OSPath)
Creates any directories needed to store the given fileName.
void FS_CheckFilenameIsNotExecutable (const char *fileName, const char *function)
ERR_FATAL if trying to manipulate a file with the platform library extension.
void FS_Remove (const char *osPath)
FS_Remove.
char * FS_BuildOSPath (const char *base, const char *game, const char *qpath)
Qpath may have either forward or backwards slashes.
int FS_LoadStack (void)
return load stack
int FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
FS_GetFileList.
int FS_GetModList (char *listbuf, int bufsize)
A mod directory is a peer to etmain with a pk3 in it The directories are searched in base path and home path.
fileHandle_t FS_FOpenFileWrite (const char *fileName)
FS_FOpenFileWrite.
long FS_filelength (fileHandle_t f)
If this is called on a non-unique FILE (from a pak file), it will return the size of the pak file, not the expected size of the file.
fileHandle_t FS_SV_FOpenFileWrite (const char *fileName)
FS_SV_FOpenFileWrite.
long FS_SV_FOpenFileRead (const char *fileName, fileHandle_t *fp)
search for a file somewhere below the home path, base path or cd path we search in that order, matching FS_SV_FOpenFileRead order
void FS_SV_Rename (const char *from, const char *to)
FS_SV_Rename - used to rename downloaded files from .tmp to .pk3.
long FS_FOpenFileRead (const char *fileName, fileHandle_t *file, qboolean uniqueFILE)
Finds the file in the search path. Used for streaming data out of either a separate file or a ZIP file.
long FS_FOpenFileRead_Filtered (const char *qpath, fileHandle_t *file, qboolean uniqueFILE, int filter_flag)
int FS_FileIsInPAK (const char *fileName, int *pChecksum)
FS_FileIsInPAK.
int FS_Delete (const char *fileName)
Removes file in the current fs_gamedir in homepath.
int FS_Write (const void *buffer, int len, fileHandle_t h)
Properly handles partial writes.
int FS_OSStatFile (const char *ospath)
int FS_Read (void *buffer, int len, fileHandle_t f)
FS_Read.
void FS_FCloseFile (fileHandle_t f)
If the FILE pointer is an open pak file, leave it open.
int FS_ReadFile (const char *qpath, void **buffer)
Open a file relative to the ET:L search path. A null buffer will just return the file length without loading.
void FS_ForceFlush (fileHandle_t f)
FS_ForceFlush.
void FS_FreeFile (void *buffer)
FS_FreeFile.
void FS_WriteFile (const char *qpath, const void *buffer, int size)
Filename are reletive to the quake search path.
int FS_FTell (fileHandle_t f)
FS_FTell.
void FS_Flush (fileHandle_t f)
FS_Flush.
void QDECL FS_Printf (fileHandle_t h, const char *fmt,...)
FS_Printf.
int FS_FOpenFileByMode (const char *qpath, fileHandle_t *f, fsMode_t mode)
Handle based file calls for virtual machines.
int FS_Seek (fileHandle_t f, long offset, int origin)
FS_Seek.
qboolean FS_FilenameCompare (const char *s1, const char *s2)
Compare filenames Ignores case and separator char distinctions.
const char * FS_LoadedPakNames (void)
FS_LoadedPakNames.
const char * FS_LoadedPakChecksums (void)
FS_LoadedPakChecksums.
const char * FS_LoadedPakPureChecksums (void)
FS_LoadedPakPureChecksums.
const char * FS_ReferencedPakNames (void)
FS_ReferencedPakNames.
const char * FS_ReferencedPakChecksums (void)
FS_ReferencedPakChecksums.
const char * FS_ReferencedPakPureChecksums (void)
This function is only used by the client to build the string sent back to server, it's useless in dedicated.
void FS_ClearPakReferences (int flags)
FS_ClearPakReferences.
void FS_ClearPureServerPacks (void)
FS_ClearPureServerPacks.
void FS_PureServerSetReferencedPaks (const char *pakSums, const char *pakNames)
The checksums and names of the pk3 files referenced at the server are sent to the client and stored here. The client will use these checksums to see if any pk3 files need to be auto-downloaded.
void FS_PureServerSetLoadedPaks (const char *pakSums, const char *pakNames)
If the string is empty, all data sources will be allowed. If not empty, only pk3 files that match one of the space separated checksums will be checked for files, with the exception of .cfg and .dat files.
qboolean FS_CheckDirTraversal (const char *checkdir)
Check whether the string contains stuff like "../" to prevent directory traversal bugs.
qboolean FS_VerifyOfficialPaks (void)
FS_VerifyOfficialPaks.
qboolean FS_idPak (const char *pak, const char *base)
FS_idPak.
qboolean FS_ComparePaks (char *neededpaks, size_t len, qboolean dlstring)
FS_ComparePaks.
qboolean FS_InvalidGameDir (const char *gamedir)
FS_InvalidGameDir.
void FS_Rename (const char *from, const char *to)
FS_Rename.
void FS_FilenameCompletion (const char *dir, int numext, const char **ext, qboolean stripExt, void(*callback)(const char *s), qboolean allowNonPureFilesOnDisk)
FS_FilenameCompletion.
qboolean FS_CL_ExtractFromPakFile (const char *base, const char *gamedir, const char *fileName)
Extracts the latest file from a pak file.
void FS_CopyFile (const char *fromOSPath, const char *toOSPath)
Copy a fully specified file from one place to another.
qboolean FS_VerifyPak (const char *pak)
Compared requested pak against the names as we built them in FS_ReferencedPakNames.
qboolean FS_UnzipTo (const char *fileName, const char *outpath, qboolean quiet)
Extracts zipped file into the selected path.
qboolean FS_Unzip (const char *fileName, qboolean quiet)
Extracts zipped file into the current gamedir.
void FS_HomeRemove (const char *homePath)
FS_HomeRemove.
qboolean FS_FileInPathExists (const char *testpath)
Tests if path and file exists.
void Console_RemoveHighlighted (field_t *field, int *completionOffset)
Console_RemoveHighlighted.
void Console_AutoComplete (field_t *field, int *completionOffset)
Console_AutoComplete.
void Field_Clear (field_t *field)
Field_Clear.
void Field_AutoComplete (field_t *field)
Perform Tab expansion.
void Field_CompleteKeyname (void)
Field_CompleteKeyname.
void Field_CompleteFilenameMultiple (const char *dir, int numext, const char **ext, qboolean allowNonPureFilesOnDisk)
Field_CompleteFilenameMultiple.
void Field_CompleteFilename (const char *dir, const char *ext, qboolean stripExt, qboolean allowNonPureFilesOnDisk)
Field_CompleteFilename.
void Field_CompleteCommand (char *cmd, qboolean doCommands, qboolean doCvars)
Field_CompleteCommand.
char * CopyString (const char *in)
CopyString.
void Info_Print (const char *s)
Info_Print - prints key and values of a given String to console.
void Com_BeginRedirect (char *buffer, size_t buffersize, void(*flush)(char *))
Com_BeginRedirect.
void Com_EndRedirect (void)
Com_EndRedirect.
void QDECL Com_Printf (const char *fmt,...) __attribute__((format(printf
void QDECL void QDECL Com_DPrintf (const char *fmt,...) __attribute__((format(printf
A Com_Printf that only shows up if the "developer" cvar is set.
void QDECL void QDECL void QDECL Com_Error (int code, const char *fmt,...) __attribute__((noreturn
void QDECL void QDECL void QDECL format (printf, 2, 3)))
void Com_Quit_f (void) __attribute__((noreturn))
Both client and server can use this, and it will do the appropriate thing.
int Com_Milliseconds (void)
Can be used for profiling, but will be journaled accurately - see com_journal Com_Milliseconds also processes system events.
unsigned int Com_BlockChecksum (const void *buffer, size_t length)
unsigned int Com_BlockChecksumKey (void *buffer, int length, int key)
char * Com_MD5FileETCompat (const char *fileName)
int Com_HashKey (char *string, int maxlen)
Com_HashKey.
int Com_Filter (char *filter, char *name, int casesensitive)
Com_Filter.
int Com_FilterPath (const char *filter, const char *name, int casesensitive)
Com_FilterPath.
int Com_RealTime (qtime_t *qtime)
Com_RealTime.
qboolean Com_SafeMode (void)
Check for "safe" on the command line, which will skip loading of wolfconfig.cfg.
void Com_RandomBytes (byte *string, int len)
fills string array with len radom bytes, peferably from the OS randomizer
char * Com_MD5File (const char *fileName, int length, const char *prefix, int prefix_len)
Generates md5 checksum of a given file.
void Com_StartupVariable (const char *match)
Searches for command line parameters that are set commands.
void Com_SetRecommended (void)
sets recommended values
void Com_TrackProfile (const char *profile_path)
Track profile changes, delete old pid file if we change fs_game(dir) Hackish, we fiddle with fs_gamedir to make FS_* calls work "right".
qboolean Com_CheckProfile (void)
Checks if profile.pid is valid.
void * Z_TagMalloc (int size, int tag)
void * Z_Malloc (int size)
void * S_Malloc (int size)
void Z_Free (void *ptr)
Z_Free.
void Z_FreeTags (int tag)
Z_FreeTags.
void Z_LogHeap (void)
Z_LogHeap.
void Hunk_Clear (void)
The server calls this before shutting down or loading a new map.
void Hunk_ClearToMark (void)
The client calls this before starting a vid_restart or snd_restart.
void Hunk_SetMark (void)
The server calls this after the level and game VM have been loaded.
qboolean Hunk_CheckMark (void)
Hunk_CheckMark.
void Hunk_ClearTempMemory (void)
The temp space is no longer needed.
void * Hunk_AllocateTempMemory (unsigned int size)
This is used by the file loading system. Multiple files can be loaded in temporary memory. When the files-in-use count reaches zero, all temp memory will be deleted.
void Hunk_FreeTempMemory (void *buf)
Hunk_FreeTempMemory.
int Hunk_MemoryRemaining (void)
Hunk_MemoryRemaining.
void Hunk_SmallLog (void)
Hunk_SmallLog.
void Hunk_Log (void)
Hunk_Log.
void Com_TouchMemory (void)
Touch all known used data to make sure it is paged in.
void Com_Init (char *commandLine)
Com_Init.
char * Com_GetCommandLine (void)
Com_GetCommandLine.
void Com_Frame (void)
Com_Frame.
void Com_Shutdown (qboolean badProfile)
Com_Shutdown.
void CL_InitKeyCommands (void)
CL_InitKeyCommands.
void CL_Init (void)
CL_Init.
void CL_Disconnect (qboolean showMainMenu)
Called when a connection, demo, or cinematic is being terminated.
void CL_Shutdown (void)
CL_Shutdown.
void CL_Frame (int msec)
CL_Frame.
qboolean CL_GameCommand (void)
See if the current console command is claimed by the cgame.
void CL_KeyEvent (int key, qboolean down, unsigned time)
Called by the system for both key up and key down events.
void CL_CharEvent (int key)
Normal keyboard characters, already shifted / capslocked / etc.
void CL_MouseEvent (int dx, int dy, int time)
CL_MouseEvent.
void CL_JoystickEvent (int axis, int value, int time)
Joystick values stay set until changed.
void CL_PacketEvent (netadr_t from, msg_t *msg)
A packet has arrived from the main event loop.
void CL_ConsolePrint (char *txt)
Handles cursor positioning, line wrapping, etc.
void CL_MapLoading (void)
A local server is starting to load a map, so update the screen to let the user know about it, then dump all client memory on the hunk from cgame, ui, and renderer.
void CL_ForwardCommandToServer (const char *string)
Adds the current command line as a clientCommand things like godmode, noclip, etc, are commands directed to the server, so when they are typed in at the console, they will need to be forwarded.
void CL_ShutdownAll (void)
CL_ShutdownAll.
void CL_FlushMemory (void)
Called by CL_MapLoading, CL_Connect_f, CL_PlayDemo_f, and CL_ParseGamestate the only ways a client gets into a game Also called by Com_Error.
qboolean CL_ConnectedToServer (void)
CL_ConnectedToServer.
void CL_StartHunkUsers (void)
After the server has cleared the hunk, these will need to be restarted This is the only place that any of these functions are called from.
void CL_Snd_Shutdown (void)
Restart the sound subsystem.
void Com_CheckAutoUpdate (void)
Com_CheckAutoUpdate.
void Com_GetAutoUpdate (void)
Com_GetAutoUpdate.
qboolean Com_CheckUpdateDownloads (void)
Com_CheckUpdateDownloads.
qboolean Com_InitUpdateDownloads (void)
Com_InitUpdateDownloads.
qboolean Com_UpdatePacketEvent (netadr_t from)
Com_UpdatePacketEvent.
void Com_UpdateInfoPacket (netadr_t from)
Com_UpdateInfoPacket.
void Com_CheckUpdateStarted (void)
Com_CheckUpdateStarted.
void Com_UpdateVarsClean (int flags)
Com_UpdateVarsClean.
void Com_Update_f (void)
Com_Update_f.
void Com_ClearDownload (void)
Com_ClearDownload.
void Com_ClearStaticDownload (void)
Clear download information that we keep in cls (disconnected download support)
void Com_NextDownload (void)
A download completed or failed.
void Com_InitDownloads (void)
After receiving a valid game state, we validate the cgame and local zip files here and determine if we need to download them.
void Com_WWWDownload (void)
Com_WWWDownload.
qboolean Com_WWWBadChecksum (const char *pakname)
FS code calls this when doing FS_ComparePaks we can detect files that we got from a www dl redirect with a wrong checksum this indicates that the redirect setup is broken, and next dl attempt should NOT redirect.
void Com_Download_f (void)
Com_Download_f.
void Key_KeynameCompletion (void(*callback)(const char *s))
Key_KeynameCompletion.
void Key_WriteBindings (fileHandle_t f)
Writes lines containing "bind key value".
void S_ClearSoundBuffer (qboolean killStreaming)
S_ClearSoundBuffer.
void SCR_DebugGraph (float value)
SCR_DebugGraph.
void SV_Init (void)
SV_Init.
void SV_Shutdown (const char *finalmsg)
Called when each game quits, before Sys_Quit or Sys_Error.
void SV_Frame (int msec)
Player movement occurs as a result of packet events, which happen before SV_Frame is called.
void SV_PacketEvent (netadr_t from, msg_t *msg)
SV_PacketEvent.
qboolean SV_GameCommand (void)
See if the current console command is claimed by the game.
int SV_FrameMsec ()
Return time in millseconds until processing of the next server frame.
int SV_SendQueuedPackets ()
Send download messages and queued packets in the time that we're idle, i.e. not computing a server frame or sending client snapshots.
qboolean UI_GameCommand (void)
See if the current console command is claimed by the ui.
void Com_QueueEvent (int time, sysEventType_t type, int value, int value2, int ptrLength, void *ptr)
A time of 0 will get the current time Ptr should either be null, or point to a block of data that can be freed by the game later.
int Com_EventLoop (void)
Com_EventLoop.
sysEvent_t Com_GetSystemEvent (void)
Com_GetSystemEvent.
void Com_RunAndTimeServerPacket (netadr_t *evFrom, msg_t *buf)
Com_RunAndTimeServerPacket.
void Sys_Init (void)
Sys_Init.
qboolean IN_IsNumLockDown (void)
Check if Num key is lock down.
qboolean Sys_DllExtension (const char *name)
Check if filename should be allowed to be loaded as a DLL.
char * Sys_GetCurrentUser (void)
Get current user username.
void QDECL Sys_Error (const char *error,...) __attribute__((noreturn
void QDECL format (printf, 1, 2)))
void Sys_Quit (void) __attribute__((noreturn))
Sys_Quit.
char * IN_GetClipboardData (void)
IN_GetClipboardData.
void Sys_Print (const char *msg)
Sys_Print.
int Sys_Milliseconds (void)
Sys_Milliseconds.
int Sys_PID (void)
Sys_PID.
qboolean Sys_WritePIDFile (void)
Writes pid to profile or to the homepath root if running a server.
qboolean Sys_PIDIsRunning (unsigned int pid)
Check if specified PID is running.
void Sys_SnapVector (float *v)
Sys_SnapVector.
void Sys_DisplaySystemConsole (qboolean show)
void Sys_SendPacket (int length, const void *data, netadr_t to)
Sys_SendPacket.
qboolean Sys_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
Sys_StringToAdr.
qboolean Sys_IsLANAddress (netadr_t adr)
LAN clients will have their rate var ignored.
void Sys_ShowIP (void)
Sys_ShowIP.
qboolean Sys_CheckCD (void)
FILE * Sys_FOpen (const char *ospath, const char *mode)
Safe function to open a file and preventing TOCTOU attacks.
qboolean Sys_Mkdir (const char *path)
Create directory.
char * Sys_Cwd (void)
Get current working directory.
char * Sys_DefaultBasePath (void)
char * Sys_DefaultInstallPath (void)
Sys_DefaultInstallPath.
char * Sys_DefaultHomePath (void)
Get current home path.
const char * Sys_Dirname (char *path)
Sys_Dirname.
const char * Sys_Basename (char *path)
Sys_Basename.
char * Sys_ConsoleInput (void)
Handle new console input.
qboolean Sys_RandomBytes (byte *string, int len)
Sys_RandomBytes.
char ** Sys_ListFiles (const char *directory, const char *extension, const char *filter, int *numfiles, qboolean wantsubs)
List files in directory by filter.
void Sys_FreeFileList (char **list)
Sys_FreeFileList.
qboolean Sys_LowPhysicalMemory (void)
Sys_LowPhysicalMemory.
void Sys_SetEnv (const char *name, const char *value)
Set/Unset environment variables.
dialogResult_t Sys_Dialog (dialogType_t type, const char *message, const char *title)
Display an OS X dialog box.
void Sys_StartProcess (char *cmdline, qboolean doexit)
Starts process.
void Sys_OpenURL (const char *url, qboolean doexit)
Open URL in system browser.
void Sys_Chmod (const char *file, int mode)
Safe function to Chmod a file and preventing TOCTOU attacks.
void Hist_Add (field_t *field)
field_t * Hist_Prev (void)
field_t * Hist_Next (void)
void Huff_Compress (msg_t *mbuf, int offset)
Huff_Compress.
void Huff_Decompress (msg_t *mbuf, int offset)
Huff_Decompress.
void Huff_Init (huffman_t *huff)
Huff_Init.
void Huff_addRef (huff_t *huff, byte ch)
Huff_addRef.
int Huff_Receive (node_t *node, int *ch, byte *fin)
Get a symbol.
void Huff_transmit (huff_t *huff, int ch, byte *fout, int maxoffset)
Huff_transmit.
void Huff_offsetReceive (node_t *node, int *ch, byte *fin, int *offset, int maxoffset)
Get a symbol.
void Huff_offsetTransmit (huff_t *huff, int ch, byte *fout, int *offset, int maxoffset)
Huff_offsetTransmit.
void Huff_putBit (int bit, byte *fout, int *offset)
Clears data along the way so we dont have to memset() it ahead of time.
int Huff_getBit (byte *fin, int *offset)
Huff_getBit.
void Com_GetHunkInfo (int *hunkused, int *hunkexpected)
Com_GetHunkInfo.
void I18N_Init (void)
Attempts to detect the system language unless cl_lang was already set. Then loads the PO file containing translated strings.
void I18N_SetLanguage (const char *language)
Loads a localization file.
const char * I18N_Translate (const char *msgid)
I18N_Translate.
const char * I18N_TranslateMod (const char *msgid)
I18N_TranslateMod.
Variables
autoupdate_t autoupdate
int demo_protocols []
Maintain a list of compatible protocols for demo playing.
const char * vmStrs [MAX_VM]
int cvar_modifiedFlags
modHash modHashes
int cl_connectedToPureServer
cvar_t * com_crashed
cvar_t * com_ignorecrash
cvar_t * com_pid
cvar_t * com_pidfile
cvar_t * com_developer
cvar_t * com_dedicated
cvar_t * com_speeds
cvar_t * com_timescale
cvar_t * com_sv_running
cvar_t * com_cl_running
cvar_t * com_viewlog
cvar_t * com_version
cvar_t * com_buildScript
cvar_t * com_journal
cvar_t * com_ansiColor
cvar_t * com_unfocused
cvar_t * com_minimized
cvar_t * com_updateavailable
cvar_t * com_updatemessage
cvar_t * com_updatefiles
cvar_t * com_motd
cvar_t * com_motdString
cvar_t * com_watchdog
cvar_t * com_watchdog_cmd
cvar_t * cl_paused
cvar_t * sv_paused
cvar_t * cl_packetdelay
cvar_t * sv_packetdelay
int time_game
int time_frontend
int time_backend
int com_frameTime
int com_expectedhunkusage
int com_hunkusedvalue
qboolean com_errorEntered
cvar_t * com_downloadURL
fileHandle_t com_journalFile
fileHandle_t com_journalDataFile
huffman_t clientHuffTables
qboolean doTranslateMod
Detailed Description
Definitions common between client and server, but not game or ref modules.
Definition in file qcommon.h.
Macro Definition Documentation
#define _ (x) I18N_Translate(x)
Definition at line 1544 of file qcommon.h.
Referenced by CL_TranslateString(), Con_DrawClock(), and Con_DrawVersion().
#define __ (x) I18N_TranslateMod(x)
Definition at line 1545 of file qcommon.h.
Referenced by CL_TranslateStringMod(), and PC_String_ParseTranslate().
#define __attribute__ (x)
Definition at line 45 of file qcommon.h.
#define AUTOUPDATE_DIR "update"
Definition at line 340 of file qcommon.h.
Referenced by Com_CLeanUpdateFolder(), Com_InitUpdateDownloads(), Com_RunUpdateBinary(), and Com_UnpackUpdatePackage().
#define AVI_LINE_PADDING 4
Todo:
: move logging to common?
Definition at line 1278 of file qcommon.h.
Referenced by RB_TakeVideoFrameCmd().
#define BASEGAME "etmain"
Definition at line 743 of file qcommon.h.
Referenced by CL_GenerateETKey(), CL_UpdateGUID(), FS_CheckRequiredFiles(), FS_ComparePaks(), FS_GetModList(), FS_InitFilesystem(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), FS_Restart(), FS_Startup(), FS_VerifyOfficialPaks(), SV_CheckDownloadAllowed(), SV_DemoAutoDemoRecord(), and SV_DemoStartPlayback().
#define CL_DECODE_START 4
Definition at line 1533 of file qcommon.h.
Referenced by CL_Netchan_Decode().
#define CL_ENCODE_START 12
Definition at line 1532 of file qcommon.h.
Referenced by CL_Netchan_Encode().
#define Cmd_AddCommand (...) EXPAND(GET_MACRO(__VA_ARGS__, Cmd_AddCommand4, Cmd_AddCommand3, Cmd_AddCommand2, Cmd_AddCommand1) (__VA_ARGS__))
Definition at line 582 of file qcommon.h.
Referenced by CIN_Init(), CL_CgameSystemCalls(), CL_DemoInit(), CL_Init(), CL_InitInput(), CL_InitKeyCommands(), CL_UISystemCalls(), Cmd_Init(), Com_Init(), Com_InitHunkMemory(), Con_Init(), Cvar_Init(), FS_InitFilesystem(), FS_Startup(), GLimp_InitCvars(), IN_InitJoystick(), NET_Init(), S_Init(), SNDDMA_Init(), SV_AddOperatorCommands(), SV_DemoInit(), Sys_Init(), and VM_Init().
#define Cmd_AddCommand1 (x) Cmd_AddSystemCommand(x, NULL, NULL, NULL)
Definition at line 578 of file qcommon.h.
#define Cmd_AddCommand2 (x, y) Cmd_AddSystemCommand(x, y, NULL, NULL)
Definition at line 579 of file qcommon.h.
#define Cmd_AddCommand3 (x, y, z) Cmd_AddSystemCommand(x, y, z, NULL)
Definition at line 580 of file qcommon.h.
#define Cmd_AddCommand4 (x, y, z, i) Cmd_AddSystemCommand(x, y, z, i)
Definition at line 581 of file qcommon.h.
#define DEFAULT_MODGAME "legacy"
Definition at line 744 of file qcommon.h.
Referenced by FS_CalcModHashes(), FS_InitFilesystem(), FS_Startup(), and Sys_LoadGameDll().
#define DLTYPE_WWW -1
block -1 means www/ftp download
Definition at line 263 of file qcommon.h.
Referenced by CL_ParseDownload(), SV_CheckFallbackURL(), and SV_SetupDownloadFile().
#define EXPAND (x) x
Definition at line 576 of file qcommon.h.
#define FS_CGAME_REF 0x04
Definition at line 764 of file qcommon.h.
Referenced by CL_Vid_Restart_f(), FS_FOpenFileReadDir(), and FS_ReferencedPakPureChecksums().
#define FS_EXCLUDE_DIR 0x1
Definition at line 845 of file qcommon.h.
Referenced by FS_CL_ExtractFromPakFile(), FS_FOpenFileRead(), and SV_TouchCGameDLL().
#define FS_EXCLUDE_PK3 0x2
Definition at line 846 of file qcommon.h.
Referenced by FS_FOpenFileRead().
#define FS_GENERAL_REF 0x01
Definition at line 762 of file qcommon.h.
Referenced by FS_FOpenFileReadDir(), and FS_ReferencedPakPureChecksums().
#define FS_QAGAME_REF 0x08
Definition at line 765 of file qcommon.h.
Referenced by FS_FOpenFileReadDir().
#define FS_UI_REF 0x02
Definition at line 763 of file qcommon.h.
Referenced by CL_Vid_Restart_f(), FS_FOpenFileReadDir(), and FS_ReferencedPakPureChecksums().
#define GAMENAME_STRING "et"
Definition at line 387 of file qcommon.h.
Referenced by CL_GlobalServers_f(), CL_ServerInfoPacket(), and SVC_Info().
#define GET_MACRO (_1, _2, _3, _4, NAME, ...) NAME
Definition at line 577 of file qcommon.h.
#define HMAX 256
Maximum symbol.
Definition at line 1486 of file qcommon.h.
#define INTERNAL_NODE (HMAX + 1)
Definition at line 1465 of file qcommon.h.
Referenced by Huff_addRef(), Huff_offsetReceive(), and Huff_Receive().
#define IS_LEGACY_MOD (modHashes.defaultMod == modHashes.currentMod)
Definition at line 758 of file qcommon.h.
Referenced by CL_Netchan_Decode(), CL_Netchan_Encode(), CL_PauseDemo_f(), CL_RewindDemo(), CL_SetServerInfo(), MSG_HashKey(), MSG_ReadBigString(), MSG_ReadString(), MSG_ReadStringLine(), MSG_WriteBigString(), MSG_WriteString(), SV_Netchan_Decode(), and SV_Netchan_Encode().
#define MAX_DOWNLOAD_BLKSIZE 1024
896 byte block chunks
Definition at line 257 of file qcommon.h.
Referenced by SV_SendQueuedPackets(), and SV_WriteDownloadToClient().
#define MAX_DOWNLOAD_WINDOW 48
ACK window of 48 download chunks.Cannot set this higher, or clients will overflow the reliable commands buffer.
Definition at line 251 of file qcommon.h.
Referenced by SV_CloseDownload(), SV_NextDownload_f(), and SV_WriteDownloadToClient().
#define MAX_EDIT_LINE 512
Definition at line 981 of file qcommon.h.
Referenced by CL_KeyEvent(), CON_Input(), CON_Show(), Field_CharEvent(), and Field_Clear().
#define MAX_FILE_HANDLES 64
Definition at line 777 of file qcommon.h.
Referenced by FS_FileForHandle(), FS_HandleForFile(), FS_Path_f(), and FS_Shutdown().
#define MAX_FOUND_FILES 0x1000
Max return of listing files.
Definition at line 783 of file qcommon.h.
Referenced by FS_ListFilteredFiles(), Sys_ListFiles(), and Sys_ListFilteredFiles().
#define MAX_MSGLEN 32768
max length of a message, which may be fragmented into multiple packets
Definition at line 245 of file qcommon.h.
Referenced by CL_ParseDemo(), CL_ParseDownload(), CL_PeekSnapshot(), CL_ReadDemoMessage(), CL_Record(), CL_WritePacket(), Com_EventLoop(), NET_Event(), NET_OutOfBandData(), NET_OutOfBandPrint(), Netchan_Transmit(), SV_SendClientGameState(), SV_SendClientIdle(), SV_SendClientSnapshot(), SV_SendDownloadMessages(), SV_SendServerCommand(), and SVC_Status().
#define MAX_PACKET_USERCMDS 32
max number of usercmd_t in a packet
Definition at line 163 of file qcommon.h.
Referenced by CL_WritePacket(), and SV_UserMove().
#define MAX_RELIABLE_COMMANDS 256
max string commands buffered for restransmit
increased - seems to keep causing problems when set to 64
Definition at line 173 of file qcommon.h.
Referenced by CL_AddReliableCommand(), CL_DemoFastForward(), CL_GetServerCommand(), CL_Netchan_Decode(), CL_Netchan_Encode(), CL_ParseCommandString(), CL_ParseDemo(), CL_ParseServerMessage(), CL_WritePacket(), SV_AddServerCommand(), SV_BotGetConsoleMessage(), SV_ExecuteClientMessage(), SV_Netchan_Decode(), SV_UpdateServerCommandsToClient(), and SV_UserMove().
#define MOTD_SERVER_NAME "motd.etlegacy.com"
location of the message of the day server
Definition at line 397 of file qcommon.h.
Referenced by CL_RequestMotd().
#define NET_ADDRSTRMAXLEN 48
maximum length of an IPv6 address string including trailing '\0'
Definition at line 205 of file qcommon.h.
Referenced by NET_AdrToStringNoPort(), and Sys_ShowIP().
#define NET_ADDRSTRMAXLEN_EXT 56
Definition at line 206 of file qcommon.h.
Referenced by NET_AdrToString().
#define NET_DISABLEMCAST 0x08
Definition at line 149 of file qcommon.h.
Referenced by NET_JoinMulticast6(), NET_SetMulticast6(), and Sys_SendPacket().
#define NET_ENABLEV4 0x01
==============================================================
NET
Definition at line 137 of file qcommon.h.
Referenced by CL_GlobalServers_f(), NET_OpenIP(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), and Sys_StringToSockaddr().
#define NET_ENABLEV6 0x02
Definition at line 138 of file qcommon.h.
Referenced by CL_LocalServers_f(), NET_OpenIP(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), and Sys_StringToSockaddr().
#define NET_PRIOV6 0x04
if this flag is set, always attempt ipv6 connections instead of ipv4 if a v6 address is found.
disables ipv6 multicast support if set.
Referenced by Sys_StringToSockaddr().
#define NUM_ID_PAKS 9
number of id paks that will never be autodownloaded from etmain
Definition at line 771 of file qcommon.h.
Referenced by FS_idPak().
#define NUM_SERVER_PORTS 4
Broadcast scan this many ports after PORT_SERVER so a single machine can run multiple servers
Definition at line 411 of file qcommon.h.
Referenced by CL_LocalServers_f().
#define NYT HMAX
NYT = Not Yet Transmitted.
Definition at line 1464 of file qcommon.h.
Referenced by Huff_Compress(), Huff_Decompress(), Huff_Init(), and Huff_transmit().
#define PACKET_BACKUP 32
number of old messages that must be kept on client and server for delta comrpession and ping estimation
Definition at line 156 of file qcommon.h.
Referenced by CL_GetSnapshot(), CL_ParseDemoSnapShotSimple(), CL_ParseSnapshot(), SV_CalcPings(), SV_SetNumSnapshotEntities(), and SV_WriteSnapshotToClient().
#define PACKET_MASK (PACKET_BACKUP - 1)
Definition at line 157 of file qcommon.h.
Referenced by CL_GetSnapshot(), CL_ParseDemoSnapShotSimple(), CL_ParseSnapshot(), CL_ReadyToSendPacket(), CL_SeekPrev_f(), CL_WritePacket(), SV_BuildClientSnapshot(), SV_SendMessageToClient(), SV_UserMove(), and SV_WriteSnapshotToClient().
#define PORT_ANY -1
Definition at line 165 of file qcommon.h.
Referenced by NET_IP6Socket(), and NET_IPSocket().
#define PORT_MASTER 27950
Definition at line 400 of file qcommon.h.
Referenced by CL_GlobalServers_f(), SV_MasterGameCompleteStatus(), and SV_MasterHeartbeat().
#define PORT_MOTD 27951
Definition at line 401 of file qcommon.h.
Referenced by CL_RequestMotd().
#define PORT_SERVER 27960
Definition at line 403 of file qcommon.h.
Referenced by CL_Connect_f(), CL_LocalServers_f(), CL_Rcon_f(), NET_GetCvars(), and NET_StringToAdr().
#define PORT_UPDATE 27951
Definition at line 402 of file qcommon.h.
Referenced by Com_CheckAutoUpdate().
#define PROTOCOL_MISMATCH_ERROR "ERROR: Protocol Mismatch Between Client and Server.\The server you are attempting to join is running an incompatible version of the game."
sent by the server, printed on connection screen, works for all clients (restrictions: does not handle
, no more than 256 chars)
Definition at line 375 of file qcommon.h.
#define PROTOCOL_MISMATCH_ERROR_LONG "ERROR: Protocol Mismatch Between Client and Server.\n\n\The server you attempted to join is running an incompatible version of the game.\n\You or the server may be running older versions of the game. Press the auto-update\ button if it appears on the Main Menu screen."
long version used by the client in diagnostic window
Definition at line 382 of file qcommon.h.
Referenced by CL_PrintPacket(), and SV_IsValidUserinfo().
#define PROTOCOL_VERSION 84
Definition at line 388 of file qcommon.h.
Referenced by CL_CheckForResend(), CL_CompleteDemoName(), CL_ParseSnapshot(), CL_PlayDemo_f(), CL_Record_f(), CL_ServerInfoPacket(), CL_WalkDemoExt(), FS_IsDemoExt(), SV_CompleteDemoName(), SV_Demo_Play_f(), SV_Demo_Record_f(), SV_DemoAutoDemoRecord(), SV_Init(), SV_IsValidUserinfo(), and SVC_Info().
#define Q_rmdir rmdir
Definition at line 790 of file qcommon.h.
Referenced by FS_DeleteDir().
#define SV_DECODE_START 12
Definition at line 1531 of file qcommon.h.
Referenced by SV_Netchan_Decode().
#define SV_ENCODE_START 4
Definition at line 1530 of file qcommon.h.
Referenced by SV_Netchan_Encode().
#define Sys_GetDLLName (x) x ".mp." ARCH_STRING DLL_EXT
Todo:
: detect the *BSD variant
Todo:
: detect the *BSD variant
Todo:
: detect the *BSD variant
Definition at line 1363 of file qcommon.h.
Referenced by FS_FOpenFileReadDir(), SV_TouchCGameDLL(), SV_VerifyPaks_f(), and Sys_LoadGameDll().
#define UPDATE_SERVER_NAME "update.etlegacy.com"
location of the update server
Definition at line 398 of file qcommon.h.
Referenced by Com_CheckAutoUpdate(), and Com_InitUpdateDownloads().
#define VM_Call (vm, ...) VM_CallFunc(vm, __VA_ARGS__, VM_CALL_END)
Definition at line 519 of file qcommon.h.
Referenced by CIN_PlayCinematic(), CL_CGameBinaryMessageReceived(), CL_CGameCheckKeyExec(), CL_CGameRendering(), CL_CgameSystemCalls(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_GameCommand(), CL_InitCGame(), CL_InitUI(), CL_KeyEvent(), CL_MouseEvent(), CL_ShutdownCGame(), CL_ShutdownUI(), Com_UpdateInfoPacket(), IN_Help(), SCR_DrawScreenField(), SV_AddEntToSnapshot(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DemoReadClientConfigString(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_Frame(), SV_GameBinaryMessageReceived(), SV_GameCommand(), SV_InitGameVM(), SV_MapRestart_f(), SV_RestartGameProgs(), SV_ShutdownGameProgs(), SV_SpawnServer(), SV_UpdateUserinfo_f(), UI_checkKeyExec(), and UI_GameCommand().
#define VM_CALL_END -1337
This should be something like INT_MAX but that would need limits.h everywhere so meh and negative values should be somewhat safe.
Definition at line 516 of file qcommon.h.
Referenced by VM_CallFunc().
#define VMA (x) VM_ArgPtr(args[x])
Definition at line 526 of file qcommon.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
#define VMF (x) _vmf(args[x])
Definition at line 537 of file qcommon.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
Typedef Documentation
typedef void(* completionFunc_t) (char *args, int argNum)
Definition at line 570 of file qcommon.h.
node_t
typedef struct vm_s vm_t
Definition at line 452 of file qcommon.h.
vmSlots_t
typedef void(* xcommand_t) (void)
Definition at line 569 of file qcommon.h.
Enumeration Type Documentation
enum clc_ops_e
Client to server.
Enumerator
clc_bad
clc_nop
clc_move
[[usercmd_t]
clc_moveNoDelta
[[usercmd_t]
clc_clientCommand
[string] message
clc_EOF
Definition at line 436 of file qcommon.h.
enum dialogResult_t
Enumerator
DR_YES
DR_NO
DR_OK
DR_CANCEL
Definition at line 1422 of file qcommon.h.
enum dialogType_t
Enumerator
DT_INFO
DT_WARNING
DT_ERROR
DT_YES_NO
DT_OK_CANCEL
Definition at line 1434 of file qcommon.h.
enum joystickAxis_t
Enumerator
AXIS_SIDE
AXIS_FORWARD
AXIS_UP
AXIS_ROLL
AXIS_YAW
AXIS_PITCH
MAX_JOYSTICK_AXIS
Definition at line 1304 of file qcommon.h.
enum memtag_t
Enumerator
TAG_FREE
TAG_GENERAL
TAG_BOTLIB
TAG_RENDERER
TAG_SMALL
TAG_STATIC
Definition at line 1109 of file qcommon.h.
enum netadrtype_t
Enumerator
NA_BAD
an address lookup failed
NA_BOT
NA_LOOPBACK
NA_BROADCAST
NA_IP
NA_IP6
NA_MULTICAST6
NA_UNSPEC
Definition at line 179 of file qcommon.h.
enum netsrc_t
Enumerator
NS_CLIENT
NS_SERVER
Definition at line 195 of file qcommon.h.
enum sharedTraps_t
Enumerator
TRAP_MEMSET
TRAP_MEMCPY
TRAP_STRNCPY
TRAP_SIN
TRAP_COS
TRAP_ATAN2
TRAP_SQRT
TRAP_MATRIXMULTIPLY
TRAP_ANGLEVECTORS
TRAP_PERPENDICULARVECTOR
TRAP_FLOOR
TRAP_CEIL
TRAP_TESTPRINTINT
TRAP_TESTPRINTFLOAT
Definition at line 484 of file qcommon.h.
enum svc_ops_e
Server to client.
Enumerator
svc_bad
svc_nop
svc_gamestate
svc_configstring
[short] [string] only in gamestate messages
svc_baseline
only in gamestate messages
svc_serverCommand
[string] to be executed by client game module
svc_download
[short] size [size bytes]
svc_snapshot
svc_EOF
Definition at line 419 of file qcommon.h.
enum sysEventType_t
Note
Make sure SE_NONE is zero
Enumerator
SE_NONE
evTime is still valid
SE_KEY
evValue is a key code, evValue2 is the down flag
SE_CHAR
evValue is an ascii char
SE_MOUSE
evValue and evValue2 are reletive signed x / y moves
SE_JOYSTICK_AXIS
evValue is an axis number and evValue2 is the current state (-127 to 127)
SE_CONSOLE
evPtr is a char*
Definition at line 1320 of file qcommon.h.
enum UPDATE_FLAGS
Enumerator
CLEAR_STATUS
CLEAR_FLAGS
CLEAR_ALL
Definition at line 1239 of file qcommon.h.
enum vmInterpret_t
Enumerator
VMI_NATIVE
VMI_BYTECODE
VMI_COMPILED
Definition at line 458 of file qcommon.h.
enum vmSlots_e
Enumerator
VM_GAME
VM_CGAME
VM_UI
MAX_VM
Definition at line 470 of file qcommon.h.
Function Documentation
static ID_INLINE float _vmf (intptr_t x) static
_vmf
Parameters
[in] x
Definition at line 531 of file qcommon.h.
void Cbuf_AddText (const char * text)
Adds command text at the end of the buffer, does NOT add a final
.
Adds command text at the end of the buffer, does NOT add a final
.
Parameters
text
Definition at line 102 of file cmd.c.
Referenced by Cbuf_ExecuteText(), CL_CgameSystemCalls(), CL_FirstSnapshot(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_KeyEvent(), CL_NextDemo(), CL_Reconnect_f(), Cmd_Echo_f(), Com_AddStartupCommands(), Com_EventLoop(), Com_Init(), Com_ModifyMsec(), Com_SetRecommended(), Console_Key(), FS_Restart(), getApplicationName(), IN_Frame(), SV_DemoAutoDemoRecord(), SV_DemoCvarsRestore(), SV_DemoRestartPlayback(), SV_DemoStartPlayback(), SV_DemoStopPlayback(), and SV_Frame().
void Cbuf_Execute (void)
Cbuf_Execute.
Pulls off
terminated lines of text from the command buffer and sends them through Cmd_ExecuteString. Stops when the buffer is empty. Normally called once per frame, but may be explicitly invoked. Do not call inside a command function, or current args will be destroyed.
Todo:
: ignore quoted text
Definition at line 185 of file cmd.c.
Referenced by Cbuf_ExecuteText(), CL_Init(), CL_NextDemo(), Com_Frame(), and Com_Init().
void Cbuf_ExecuteText (int exec_when, const char * text)
this can be used in place of either Cbuf_AddText or Cbuf_InsertText
this can be used in place of either Cbuf_AddText or Cbuf_InsertText
Parameters
[in] exec_when
[in] text
Definition at line 155 of file cmd.c.
Referenced by CIN_StopCinematic(), CL_CaptureFrameVideo(), CL_InitRef(), CL_KeyEvent(), CL_ParseDownload(), CL_UISystemCalls(), Com_Init(), Com_WWWDownload(), GLimp_EndFrame(), IN_ProcessEvents(), SV_DemoStartPlayback(), SV_GameSystemCalls(), Sys_OpenURL(), and Sys_StartProcess().
void Cbuf_Init (void)
allocates an initial text buffer that will grow as needed
allocates an initial text buffer that will grow as needed
=============================================================================
COMMAND BUFFER
Definition at line 91 of file cmd.c.
Referenced by Com_Init().
void CL_CharEvent (int key)
Normal keyboard characters, already shifted / capslocked / etc.
Parameters
[in] key Normal keyboard characters, already shifted / capslocked / etc.
key - unused
Definition at line 1548 of file cl_keys.c.
Referenced by Com_EventLoop().
qboolean CL_ConnectedToServer (void)
CL_ConnectedToServer.
Returns
Note
Unused
Returns
Definition at line 436 of file cl_main.c.
void CL_ConsolePrint (char * txt)
Handles cursor positioning, line wrapping, etc.
Parameters
[in] txt Handles cursor positioning, line wrapping, etc.
txt - unused
Definition at line 399 of file cl_console.c.
Referenced by Com_Printf().
void CL_Disconnect (qboolean showMainMenu)
Called when a connection, demo, or cinematic is being terminated.
Goes from a connected state to either a menu state or a console state Sends a disconnect message to the server
This is also called on Com_Error and Com_Quit, so it shouldn't cause any errors
Parameters
[in] showMainMenu Called when a connection, demo, or cinematic is being terminated.
showMainMenu - unused
Definition at line 605 of file cl_main.c.
Referenced by CIN_PlayCinematic_f(), CL_CheckTimeout(), CL_Connect_f(), CL_DemoCompleted(), CL_DisconnectPacket(), CL_MapLoading(), CL_PlayDemo_f(), CL_Shutdown(), Com_CheckUpdateDownloads(), Com_Error(), Com_GetAutoUpdate(), and SV_Shutdown().
void CL_FlushMemory (void)
Called by CL_MapLoading, CL_Connect_f, CL_PlayDemo_f, and CL_ParseGamestate the only ways a client gets into a game Also called by Com_Error.
Called by CL_MapLoading, CL_Connect_f, CL_PlayDemo_f, and CL_ParseGamestate the only ways a client gets into a game Also called by Com_Error.
Definition at line 446 of file cl_main.c.
Referenced by CL_DownloadsComplete(), and Com_Error().
void CL_ForwardCommandToServer (const char * string)
Adds the current command line as a clientCommand things like godmode, noclip, etc, are commands directed to the server, so when they are typed in at the console, they will need to be forwarded.
Parameters
[in] string Adds the current command line as a clientCommand things like godmode, noclip, etc, are commands directed to the server, so when they are typed in at the console, they will need to be forwarded.
string - unused
Definition at line 699 of file cl_main.c.
Referenced by Cmd_ExecuteString().
void CL_Frame (int msec)
CL_Frame.
Parameters
[in] msec
msec
Definition at line 2153 of file cl_main.c.
Referenced by Com_Frame().
qboolean CL_GameCommand (void)
See if the current console command is claimed by the cgame.
Returns
See if the current console command is claimed by the cgame.
Returns
Definition at line 1216 of file cl_cgame.c.
Referenced by Cmd_ExecuteString().
void CL_Init (void)
CL_Init.
Todo:
: remove caching system? inspect!
Todo:
: remove caching system? inspect!
Definition at line 2722 of file cl_main.c.
Referenced by Com_Frame(), and Com_Init().
void CL_InitKeyCommands (void)
CL_InitKeyCommands.
Definition at line 1221 of file cl_keys.c.
Referenced by Com_Init().
void CL_JoystickEvent (int axis, int value, int time)
Joystick values stay set until changed.
Parameters
[in] axis
[in] value
time - unused
Joystick values stay set until changed.
Parameters
axis - unused
value - unused
time - unused
Definition at line 860 of file cl_input.c.
Referenced by Com_EventLoop().
void CL_KeyEvent (int key, qboolean down, unsigned time)
Called by the system for both key up and key down events.
Parameters
[in] key
[in] down
[in] time Called by the system for both key up and key down events.
key - unused
down - unused
time - unused
Definition at line 1260 of file cl_keys.c.
Referenced by Com_EventLoop(), and Key_ClearStates().
void CL_MapLoading (void)
A local server is starting to load a map, so update the screen to let the user know about it, then dump all client memory on the hunk from cgame, ui, and renderer.
A local server is starting to load a map, so update the screen to let the user know about it, then dump all client memory on the hunk from cgame, ui, and renderer.
Definition at line 473 of file cl_main.c.
Referenced by SV_SpawnServer().
void CL_MouseEvent (int dx, int dy, int time)
CL_MouseEvent.
Parameters
[in] dx
[in] dy
time - unused
dx - unused
dy - unused
time - unused
Definition at line 820 of file cl_input.c.
Referenced by Com_EventLoop().
void CL_PacketEvent (netadr_t from, msg_t * msg)
A packet has arrived from the main event loop.
Parameters
[in] from
[in] msg A packet has arrived from the main event loop.
from - unused
msg - unused
Definition at line 1909 of file cl_main.c.
Referenced by Com_EventLoop(), and NET_Event().
void CL_Shutdown (void)
CL_Shutdown.
Definition at line 2941 of file cl_main.c.
Referenced by Com_Error(), Com_Frame(), Com_Quit_f(), and Sys_SigHandler().
void CL_ShutdownAll (void)
CL_ShutdownAll.
Definition at line 391 of file cl_main.c.
Referenced by CL_FlushMemory(), and SV_SpawnServer().
void CL_Snd_Shutdown (void)
Restart the sound subsystem.
Restart the sound subsystem.
Definition at line 1183 of file cl_main.c.
Referenced by CL_Shutdown(), and CL_Snd_Restart_f().
void CL_StartHunkUsers (void)
After the server has cleared the hunk, these will need to be restarted This is the only place that any of these functions are called from.
After the server has cleared the hunk, these will need to be restarted This is the only place that any of these functions are called from.
Definition at line 2497 of file cl_main.c.
Referenced by CL_FlushMemory(), CL_Vid_Restart_f(), and Com_Init().
void Cmd_AddSystemCommand (const char * cmd_name, xcommand_t function, const char * description, completionFunc_t complete)
Cmd_AddSystemCommand.
Called by the init functions of other parts of the program to register commands and functions to call for them. The cmd_name is referenced later, so it should not be in temp memory if function is NULL, the command will be forwarded to the server as a clc_clientCommand instead of executed locally
Parameters
[in] cmd_name
[in] function
[in] description
[in] complete
Definition at line 757 of file cmd.c.
Referenced by CL_InitRef().
int Cmd_Argc (void)
Cmd_Argc.
Returns
Definition at line 414 of file cmd.c.
Referenced by __attribute__(), CIN_PlayCinematic_f(), CL_Cache_SetIndex_f(), CL_Cache_UsedFile_f(), CL_CgameSystemCalls(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_FastForward_f(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitRef(), CL_Ping_f(), CL_PlayDemo_f(), CL_Record_f(), CL_Rewind_f(), CL_Seek_f(), CL_SeekEnd_f(), CL_SeekServerTime_f(), CL_ServerStatus_f(), CL_UISystemCalls(), CL_Video_f(), CL_WriteWaveOpen(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_List_f(), Cmd_Vstr_f(), Cmd_Wait_f(), Com_Download_f(), Com_Freeze_f(), Com_Meminfo_f(), Com_WriteConfig_f(), Con_Dump_f(), Console_AutoComplete(), Cvar_Command(), Cvar_Cycle_f(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Field_CompleteCommand(), FS_Dir_f(), FS_NewDir_f(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_TouchFile_f(), IRC_Say(), Key_Bind_f(), Key_Bindlist_f(), Key_Unbind_f(), S_Music_f(), S_Play_f(), S_Stream_f(), SV_ConSay_f(), SV_Demo_Play_f(), SV_Demo_Record_f(), SV_DumpUser_f(), SV_GameSystemCalls(), SV_GetPlayerByName(), SV_MapRestart_f(), SV_Uptime_f(), and SV_VerifyPaks_f().
char* Cmd_Args (void)
Cmd_Args.
Returns
A single string containing argv(1) to argv(argc()-1)
Definition at line 448 of file cmd.c.
Referenced by CL_ForwardToServer_f(), Cmd_ArgsBuffer(), Cmd_Echo_f(), Cvar_Command(), DB_ExecSQLCommand_f(), IRC_Say(), and SV_ConSay_f().
void Cmd_Args_Sanitize (void)
Replaces command separators with space to prevent interpretation.
The functions that execute commands get their parameters with these functions. Cmd_Argv () will return an empty string, not a NULL if arg > argc, so string operations are allways safe.
This prevents the infamous callvote hack.
Definition at line 557 of file cmd.c.
Referenced by SV_ExecuteClientCommand().
void Cmd_ArgsBuffer (char * buffer, size_t bufferLength)
The interpreted versions use this because they can't have pointers returned to them.
Parameters
[out] buffer
[in] bufferLength
Definition at line 537 of file cmd.c.
Referenced by CL_CgameSystemCalls().
char* Cmd_ArgsFrom (int arg)
Cmd_ArgsFrom.
Parameters
arg
Returns
A single string containing argv(arg) to argv(argc()-1)
Definition at line 471 of file cmd.c.
Referenced by CL_ConfigstringModified(), CL_GlobalServers_f(), and Com_StartupVariable().
char* Cmd_ArgsFromTo (int arg, int max)
Cmd_ArgsFromTo.
Parameters
arg
max
Returns
A single string containing argv(arg) to argv(max-1)
Todo:
what should these be
Definition at line 499 of file cmd.c.
Referenced by Cvar_Set_f().
char* Cmd_Argv (int arg)
Cmd_Argv.
Parameters
arg
Returns
Definition at line 424 of file cmd.c.
Referenced by CIN_PlayCinematic_f(), CL_Cache_SetIndex_f(), CL_Cache_UsedFile_f(), CL_ConfigstringModified(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_FastForward_f(), CL_ForwardCommandToServer(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitRef(), CL_MotdPacket(), CL_Ping_f(), CL_PlayDemo_f(), CL_Record_f(), CL_Rewind_f(), CL_Seek_f(), CL_SeekEnd_f(), CL_SeekServerTime_f(), CL_ServerStatus_f(), CL_Video_f(), CL_WriteWaveOpen(), Cmd_ArgvBuffer(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_List_f(), Cmd_Vstr_f(), Cmd_Wait_f(), Com_Download_f(), Com_Freeze_f(), Com_SafeMode(), Com_StartupVariable(), Com_UpdateInfoPacket(), Com_WriteConfig_f(), Con_Dump_f(), Cvar_Command(), Cvar_Cycle_f(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Field_CompleteCommand(), FS_Dir_f(), FS_NewDir_f(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_TouchFile_f(), FS_Which_f(), IN_KeyDown(), IN_KeyUp(), Key_Bind_f(), Key_Unbind_f(), S_Music_f(), S_Play_f(), S_Stream_f(), SV_BeginDownload_f(), SV_CheckGameCommand(), SV_ConnectionlessPacket(), SV_Demo_Play_f(), SV_Demo_Record_f(), SV_DemoClientCommandCapture(), SV_DirectConnect(), SV_ExecuteClientCommand(), SV_GetPlayerByName(), SV_Map_f(), SV_MapRestart_f(), SV_NextDownload_f(), SV_UpdateUserinfo_f(), SV_VerifyPaks_f(), SV_WWWDownload_f(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
void Cmd_ArgvBuffer (int arg, char * buffer, size_t bufferLength)
The interpreted versions use this because they can't have pointers returned to them.
Parameters
arg
buffer
bufferLength
Definition at line 439 of file cmd.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
char* Cmd_Cmd (void)
Retrieve the unmodified command string. For rcon use when you want to transmit without altering quoting.
Returns
Definition at line 547 of file cmd.c.
Referenced by CL_Rcon_f(), SV_DemoStartPlayback(), and SVC_RemoteCommand().
void Cmd_CommandCompletion (void(*)(const char *s) callback)
callback with each valid string
callback with each valid string
Definition at line 931 of file cmd.c.
Referenced by Console_AutoComplete(), and Field_CompleteCommand().
void Cmd_CompleteArgument (const char * command, char * args, int argNum)
Cmd_CompleteArgument.
Parameters
[in] command
[in] args
[in] argNum
Definition at line 947 of file cmd.c.
Referenced by Field_CompleteCommand().
void Cmd_ExecuteString (const char * text)
A complete command line has been parsed, so try to execute it.
Parses a single line of text into arguments and tries to execute it as if it was typed at the console
Parameters
text
Definition at line 968 of file cmd.c.
Referenced by Cbuf_Execute(), Cbuf_ExecuteText(), CL_DemoCompleted(), CL_StopVideo_f(), CL_Vid_Restart_f(), and SVC_RemoteCommand().
void Cmd_Init (void)
Cmd_Init.
Definition at line 1087 of file cmd.c.
Referenced by Com_Init().
void Cmd_RemoveCommand (const char * cmd_name)
Cmd_RemoveCommand.
Parameters
[in] cmd_name
Definition at line 839 of file cmd.c.
Referenced by CIN_Shutdown(), CL_InitRef(), CL_Shutdown(), Cmd_RemoveCommandSafe(), Com_Shutdown(), Con_Shutdown(), FS_Shutdown(), IN_ShutdownJoystick(), S_Base_Shutdown(), S_Shutdown(), SNDDMA_Shutdown(), SV_DemoShutdown(), SV_RemoveOperatorCommands(), and SV_Shutdown().
void Cmd_RemoveCommandSafe (const char * cmd_name)
Only remove commands with no associated function Already removed in ETL: +button4, -button4 Allowed to remove: +lookup, +lookdown, -lookup, +lookup, configstrings.
Parameters
[in] cmd_name
Definition at line 880 of file cmd.c.
Referenced by CL_CgameSystemCalls().
void Cmd_RestoreCmdContext (void)
void Cmd_SaveCmdContext (void)
void Cmd_SetCommandCompletionFunc (const char * command, completionFunc_t complete)
Cmd_SetCommandCompletionFunc.
Parameters
[in] command
[in] complete
Definition at line 801 of file cmd.c.
Referenced by CL_DemoInit(), and CL_InitKeyCommands().
void Cmd_SetCommandDescription (const char * command, const char * description)
Cmd_SetCommandDescription.
Parameters
[in] command
[in] description
Note
Unused
Definition at line 822 of file cmd.c.
void Cmd_TokenizeString (const char * text)
Cmd_TokenizeString.
Parameters
[in] text
Definition at line 717 of file cmd.c.
Referenced by CL_ConnectionlessPacket(), CL_GetServerCommand(), Cmd_ExecuteString(), Com_SafeMode(), Com_StartupVariable(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), SV_CheckClientUserinfoTimer(), SV_CheckGameCommand(), SV_ConnectionlessPacket(), SV_DemoReadClientUserinfo(), SV_ExecuteClientCommand(), and SV_VerifyPaks_f().
void Cmd_TokenizeStringIgnoreQuotes (const char * text_in)
Cmd_TokenizeStringIgnoreQuotes.
Takes a null terminated string. Does not need to be /n terminated. breaks the string up into arg tokens.
Parameters
[in] text_in
Definition at line 726 of file cmd.c.
Referenced by Console_AutoComplete(), and Field_CompleteCommand().
void Com_BeginRedirect (char * buffer, size_t buffersize, void(*)(char *) flush)
Com_BeginRedirect.
Parameters
[in] buffer
[in] buffersize
[in] flush Function pointer
Definition at line 187 of file common.c.
Referenced by SVC_RemoteCommand().
unsigned int Com_BlockChecksum (const void * buffer, size_t length)
unsigned int Com_BlockChecksumKey (void * buffer, int length, int key)
Definition at line 321 of file md4.c.
void Com_CheckAutoUpdate (void)
Com_CheckAutoUpdate.
Definition at line 63 of file update.c.
Referenced by CL_RequestMasterData(), and Com_Update_f().
qboolean Com_CheckProfile (void)
Checks if profile.pid is valid.
Returns
qtrue if valid, otherwise qfalse if invalid(!)
Definition at line 2667 of file common.c.
Referenced by Com_Init(), and FS_Restart().
qboolean Com_CheckUpdateDownloads (void)
Com_CheckUpdateDownloads.
Returns
Definition at line 316 of file update.c.
Referenced by Com_DownloadsComplete().
void Com_CheckUpdateStarted (void)
Com_CheckUpdateStarted.
Definition at line 526 of file update.c.
Referenced by CL_ConnectionlessPacket(), and Com_GetAutoUpdate().
void Com_ClearDownload (void)
Com_ClearDownload.
Definition at line 48 of file download.c.
Referenced by CL_Disconnect(), and CL_ParseDemo().
void Com_ClearStaticDownload (void)
Clear download information that we keep in cls (disconnected download support)
Definition at line 66 of file download.c.
Referenced by CL_Disconnect(), Com_CheckUpdateDownloads(), Com_DownloadsComplete(), Com_InitDownloads(), Com_RunUpdateBinary(), and Com_WWWDownload().
void Com_Download_f (void)
Com_Download_f.
Definition at line 485 of file download.c.
Referenced by Com_Init().
void QDECL void QDECL Com_DPrintf (const char * fmt, ...)
A Com_Printf that only shows up if the "developer" cvar is set.
Parameters
[in] fmt
Definition at line 312 of file common.c.
void Com_EndRedirect (void)
Com_EndRedirect.
Definition at line 203 of file common.c.
Referenced by SVC_RemoteCommand().
void QDECL void QDECL void QDECL Com_Error (int code, const char * fmt, ...)
int Com_EventLoop (void)
Com_EventLoop.
Returns
Last event time
Definition at line 2484 of file common.c.
Referenced by CL_DownloadsComplete(), and Com_Frame().
int Com_Filter (char * filter, char * name, int casesensitive)
Com_Filter.
Parameters
[in] filter
[in] name
[in] casesensitive
Returns
Definition at line 721 of file common.c.
Referenced by Cmd_List_f(), Com_FilterPath(), and Cvar_List_f().
int Com_FilterPath (const char * filter, const char * name, int casesensitive)
Com_FilterPath.
Parameters
[in] filter
[in] name
[in] casesensitive
Returns
Definition at line 854 of file common.c.
Referenced by FS_ListFilteredFiles(), FS_Unzip(), and Sys_ListFilteredFiles().
void Com_Frame (void)
Com_Frame.
Definition at line 3285 of file common.c.
Referenced by Sys_GameLoop().
void Com_GetAutoUpdate (void)
Com_GetAutoUpdate.
Todo:
: this should be saved & restored after update
Definition at line 113 of file update.c.
Referenced by CL_UISystemCalls(), Com_Error(), Com_Update_f(), and Com_UpdateInfoPacket().
char* Com_GetCommandLine (void)
Com_GetCommandLine.
Returns
Definition at line 511 of file common.c.
Referenced by Com_RunUpdateBinary().
void Com_GetHunkInfo (int * hunkused, int * hunkexpected)
Com_GetHunkInfo.
Parameters
[out] hunkused
[out] hunkexpected
Definition at line 3920 of file common.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
sysEvent_t Com_GetSystemEvent (void)
Com_GetSystemEvent.
Returns
Definition at line 2290 of file common.c.
Referenced by Com_GetRealEvent().
int Com_HashKey (char * string, int maxlen)
Com_HashKey.
Parameters
[in,out] string
[in] maxlen
Returns
Definition at line 196 of file q_shared.c.
Referenced by GetMDMSurfaceShader(), R_AddAnimSurfaces(), R_AddMD3Surfaces(), R_AddMDCSurfaces(), R_MDM_AddAnimSurfaces(), RE_GetSkinModel(), and RE_RegisterSkin().
void Com_Init (char * commandLine)
Com_Init.
Parameters
[in] commandLine
Definition at line 2775 of file common.c.
Referenced by main().
void Com_InitDownloads (void)
After receiving a valid game state, we validate the cgame and local zip files here and determine if we need to download them.
Definition at line 233 of file download.c.
Referenced by CL_ParseGamestate(), Com_CheckUpdateDownloads(), and Com_CheckUpdateStarted().
qboolean Com_InitUpdateDownloads (void)
Com_InitUpdateDownloads.
Returns
Todo:
: add file size, so UI can show progress bar
Todo:
: never executed
Definition at line 358 of file update.c.
Referenced by Com_InitDownloads().
char* Com_MD5File (const char * fn, int length, const char * prefix, int prefix_len)
Generates md5 checksum of a given file.
Parameters
fn file name
length file length. Ignored if 0
prefix ignored if NULL
prefix_len ignored if 0
Returns
md5 checksum
Definition at line 280 of file md5.c.
Referenced by Com_CheckAutoUpdate().
char* Com_MD5FileETCompat (const char * fileName)
Definition at line 395 of file md5.c.
Referenced by CL_UpdateGUID().
int Com_Milliseconds (void)
Can be used for profiling, but will be journaled accurately - see com_journal Com_Milliseconds also processes system events.
Returns
Sys_Milliseconds (finally)
Definition at line 2567 of file common.c.
Referenced by CL_Init(), Com_Freeze_f(), Com_Init(), and SV_InitGameVM().
void Com_NextDownload (void)
A download completed or failed.
Definition at line 177 of file download.c.
Referenced by CL_ParseDownload(), Com_InitDownloads(), and Com_WWWDownload().
void QDECL Com_Printf (const char * fmt, ...)
void Com_QueueEvent (int time, sysEventType_t type, int value, int value2, int ptrLength, void * ptr)
A time of 0 will get the current time Ptr should either be null, or point to a block of data that can be freed by the game later.
Parameters
[in] time
[in] type
[in] value
[in] value2
[in] ptrLength
[in] ptr
Definition at line 2256 of file common.c.
Referenced by Com_GetSystemEvent(), IN_JoyMove(), and IN_ProcessEvents().
void Com_Quit_f (void)
Both client and server can use this, and it will do the appropriate thing.
Definition at line 437 of file common.c.
Referenced by Com_Init(), and Sys_Error().
void Com_RandomBytes (byte * string, int len)
fills string array with len radom bytes, peferably from the OS randomizer
Author
ioquake3
Parameters
[in,out] string
[in] len
Definition at line 4087 of file common.c.
Referenced by Com_Init().
int Com_RealTime (qtime_t * qtime)
Com_RealTime.
Parameters
[out] qtime
Returns
Definition at line 893 of file common.c.
Referenced by CL_CgameSystemCalls(), CL_InitRef(), CL_ParseSnapshot(), CL_UISystemCalls(), SV_DemoAutoDemoRecord(), SV_GameSystemCalls(), SV_GenerateDateTime(), and SV_WriteAttackLog().
void Com_RunAndTimeServerPacket (netadr_t * evFrom, msg_t * buf)
Com_RunAndTimeServerPacket.
Parameters
[in] evFrom
[in] buf
Definition at line 2454 of file common.c.
Referenced by Com_EventLoop(), and NET_Event().
qboolean Com_SafeMode (void)
Check for "safe" on the command line, which will skip loading of wolfconfig.cfg.
Definition at line 541 of file common.c.
Referenced by Com_Init(), and FS_Restart().
void Com_SetRecommended (void)
sets recommended values
Definition at line 2641 of file common.c.
Referenced by CL_SetRecommended_f(), and Com_Init().
void Com_Shutdown (qboolean badProfile)
Com_Shutdown.
Parameters
[in] badProfile
Todo:
: common defines more cmds - remove all see Cmd_AddCommand()
Definition at line 3525 of file common.c.
Referenced by Com_Error(), and Com_Quit_f().
void Com_StartupVariable (const char * match)
Searches for command line parameters that are set commands.
If match is not NULL, only that cvar will be looked for. That is necessary because cddir and basedir need to be set before the filesystem is started, but all other sets shouls be after execing the config and default.
Parameters
[in] match
Definition at line 568 of file common.c.
Referenced by Com_Init(), Com_InitJournaling(), and FS_InitFilesystem().
void Com_TouchMemory (void)
Touch all known used data to make sure it is paged in.
Definition at line 1620 of file common.c.
Referenced by CL_InitCGame().
void Com_TrackProfile (const char * profile_path)
Track profile changes, delete old pid file if we change fs_game(dir) Hackish, we fiddle with fs_gamedir to make FS_* calls work "right".
Parameters
profile_path
Definition at line 2717 of file common.c.
Referenced by Sys_WritePIDFile().
void Com_Update_f (void)
Com_Update_f.
Definition at line 569 of file update.c.
Referenced by Com_Init().
void Com_UpdateInfoPacket (netadr_t from)
Com_UpdateInfoPacket.
Parameters
[in] from
Definition at line 463 of file update.c.
Referenced by CL_ConnectionlessPacket(), and SV_ConnectionlessPacket().
qboolean Com_UpdatePacketEvent (netadr_t from)
Com_UpdatePacketEvent.
Parameters
[in] from
Returns
Definition at line 440 of file update.c.
Referenced by CL_PacketEvent().
void Com_UpdateVarsClean (int flags)
Com_UpdateVarsClean.
Parameters
[in] flags
Definition at line 548 of file update.c.
Referenced by CL_Disconnect(), CL_UI_Restart_f(), CL_Vid_Restart_f(), and Com_Init().
qboolean Com_WWWBadChecksum (const char * pakname)
FS code calls this when doing FS_ComparePaks we can detect files that we got from a www dl redirect with a wrong checksum this indicates that the redirect setup is broken, and next dl attempt should NOT redirect.
Parameters
[in] pakname
Returns
Definition at line 440 of file download.c.
Referenced by FS_ComparePaks().
void Com_WWWDownload (void)
Com_WWWDownload.
Definition at line 329 of file download.c.
Referenced by CL_Frame(), and SV_Frame().
void Console_AutoComplete (field_t * field, int * completionOffset)
Console_AutoComplete.
Parameters
[in,out] field
[in,out] completionOffset
Definition at line 3986 of file common.c.
Referenced by Console_Key().
void Console_RemoveHighlighted (field_t * field, int * completionOffset)
Console_RemoveHighlighted.
Parameters
[in,out] field
[in] completionOffset
Definition at line 3965 of file common.c.
Referenced by Console_Key().
char* CopyString (const char * in)
CopyString.
Parameters
[in] in
Returns
Note
Never write over the memory CopyString returns because memory from a memstatic_t might be returned
Definition at line 1413 of file common.c.
Referenced by Cmd_AddSystemCommand(), Cmd_SetCommandDescription(), Cvar_Get(), Cvar_Set2(), Cvar_SetDescription(), FS_AddFileToList(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), Key_SetBinding(), SV_SetConfigstring(), SV_SetConfigstringNoUpdate(), SV_SpawnServer(), Sys_ListFiles(), and Sys_ListFilteredFiles().
void Cvar_CheckRange (cvar_t * cv, float minVal, float maxVal, qboolean shouldBeIntegral)
cvar range check
Parameters
[in] cv
[in] minVal
[in] maxVal
[in] shouldBeIntegral
Note
This isn't static so visible to all!
Definition at line 1588 of file cvar.c.
Referenced by CL_InitRef(), Com_Frame(), and GLimp_InitCvars().
qboolean Cvar_Command (void)
Handles variable inspection and changing from the console.
Returns
Definition at line 946 of file cvar.c.
Referenced by Cmd_ExecuteString().
void Cvar_CommandCompletion (void(*)(const char *s) callback)
Cvar_CommandCompletion.
Definition at line 229 of file cvar.c.
Referenced by Console_AutoComplete(), and Field_CompleteCommand().
void Cvar_CompleteCvarName (char * args, int argNum)
Cvar_CompleteCvarName.
Parameters
[in] args
[in] argNum
Definition at line 1799 of file cvar.c.
Referenced by Cmd_Init(), and Cvar_Init().
int Cvar_Flags (const char * var_name)
Cvar_Flags.
Parameters
[in] var_name
Returns
Definition at line 205 of file cvar.c.
Referenced by CL_SystemInfoChanged(), Com_StartupVariable(), and Cvar_SetSafe().
void Cvar_ForceReset (const char * var_name)
Cvar_ForceReset.
Parameters
[in] var_name
Definition at line 875 of file cvar.c.
Referenced by CL_InitRef().
cvar_t* Cvar_Get (const char * varName, const char * value, int flags)
If the variable already exists, the value will not be set unless CVAR_ROM The flags will be or'ed in if the variable exists.
Parameters
[in] varName
[in] value
[in] flags
Returns
Todo:
: values with backslash happen
Definition at line 409 of file cvar.c.
Referenced by CL_DemoInit(), CL_Init(), CL_InitInput(), CL_InitRef(), CL_SystemInfoChanged(), CM_DrawDebugSurface(), CM_LoadMap(), CM_TracePointThroughPatchCollide(), CM_TraceThroughPatchCollide(), Com_Frame(), Com_Init(), Com_InitHunkMemory(), Com_InitJournaling(), Com_InitZoneMemory(), Com_SetRecommended(), Com_StartupVariable(), Con_Init(), Cvar_Init(), Cvar_Register(), Cvar_Set2(), DB_Init(), FS_InitFilesystem(), FS_Startup(), GLimp_Init(), GLimp_InitCvars(), I18N_Init(), IN_Init(), IN_InitJoystick(), IRC_Init(), NET_GetCvars(), Netchan_Init(), S_AL_Init(), S_Base_Init(), S_Init(), SCR_Init(), SND_setup(), SNDDMA_Init(), SV_BoundMaxClients(), SV_DemoChangeMaxClients(), SV_DemoStartPlayback(), SV_DemoStopPlayback(), and SV_Init().
char* Cvar_InfoString (int bit)
Cvar_InfoString.
Parameters
[in] bit
Returns
Definition at line 1528 of file cvar.c.
Referenced by CL_CheckForResend(), CL_CheckUserinfo(), CL_Clientinfo_f(), Cvar_InfoStringBuffer(), SV_Frame(), SV_GetServerinfo(), SV_Serverinfo_f(), SV_SpawnServer(), and SVC_Status().
char* Cvar_InfoString_Big (int bit)
Handles large info strings (CS_SYSTEMINFO)
Parameters
bit
Returns
Definition at line 1550 of file cvar.c.
Referenced by SV_Frame(), SV_SpawnServer(), and SV_Systeminfo_f().
void Cvar_InfoStringBuffer (int bit, char * buff, size_t buffsize)
Cvar_InfoStringBuffer.
Parameters
[in] bit
[out] buff
[in] buffsize
Definition at line 1573 of file cvar.c.
Referenced by CL_UISystemCalls().
void Cvar_Init (void)
Reads in all archived cvars.
Definition at line 1816 of file cvar.c.
Referenced by Com_Init().
void Cvar_LatchedVariableStringBuffer (const char * var_name, char * buffer, size_t bufsize)
Cvar_LatchedVariableStringBuffer.
Parameters
[in] var_name
[out] buffer
[in] bufsize
Definition at line 178 of file cvar.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
void Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
Basically a slightly modified Cvar_Get for the interpreted modules.
Parameters
[in,out] vmCvar
[in] varName
[in] defaultValue
[in] flags
Todo:
/inspect: this causes an endless loop while loading some maps (f.e. fueldump)
Definition at line 1662 of file cvar.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
void Cvar_Reset (const char * var_name)
Cvar_Reset.
Parameters
[in] var_name
Definition at line 866 of file cvar.c.
Referenced by CL_UISystemCalls(), and Cvar_Reset_f().
void Cvar_Restart (qboolean unsetVM)
Resets all cvars to their hardcoded values and removes userdefined variables and variables added via the VMs if requested.
Parameters
unsetVM
Definition at line 1490 of file cvar.c.
Referenced by Cvar_Restart_f().
void Cvar_Restart_f (void)
Resets all cvars to their hardcoded values.
Definition at line 1517 of file cvar.c.
Referenced by Cvar_Init().
void Cvar_Set (const char * varName, const char * value)
Cvar_Set.
Parameters
[in] varName
[in] value
Definition at line 782 of file cvar.c.
Referenced by checkDownloadName(), CIN_StopCinematic(), CL_Cache_EndGather_f(), CL_Cache_StartGather_f(), CL_CheckTimeout(), CL_CM_LoadMap(), CL_Connect_f(), CL_DemoRun(), CL_Disconnect(), CL_DisconnectPacket(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_Init(), CL_InitRef(), CL_KeyEvent(), CL_MapLoading(), CL_MotdPacket(), CL_NextDemo(), CL_ParseDownload(), CL_ParseGamestate(), CL_PlayDemo_f(), CL_PrintPacket(), CL_ReadyToSendPacket(), CL_Record(), CL_Shutdown(), CL_StopRecord_f(), CL_StopVideo_f(), CL_SystemInfoChanged(), CL_UpdateGUID(), CL_Vid_Restart_f(), CL_Video_f(), CL_WavStopRecord_f(), CL_WritePacket(), CL_WriteWaveOpen(), Com_BeginDownload(), Com_CheckUpdateDownloads(), Com_Error(), Com_GetAutoUpdate(), Com_Init(), Com_InitDownloads(), Com_InitJournaling(), Com_InitUpdateDownloads(), Com_InitZoneMemory(), Com_SetRecommended(), Com_TrackProfile(), Com_UpdateInfoPacket(), Com_UpdateVarsClean(), Com_WWWDownload(), Cvar_CheckRange(), Cvar_Set2(), Cvar_SetCheatState(), Cvar_SetSafe(), Cvar_SetValue(), DL_BeginDownload(), DL_DownloadLoop(), FS_CheckRequiredFiles(), FS_InitFilesystem(), FS_PureServerSetLoadedPaks(), GLimp_DetectAvailableModes(), GLimp_EndFrame(), GLimp_Init(), GLimp_StartDriverAndSetMode(), Hunk_Alloc(), Hunk_Clear(), I18N_Init(), IN_InitJoystick(), IN_WindowResize(), S_Init(), S_StartStreamingSoundEx(), SCR_DrawDemoRecording(), SNDDMA_Init(), SV_BoundMaxClients(), SV_CheckPaused(), SV_Frame(), SV_Init(), SV_Map_f(), SV_MapRestart_f(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SV_RateMsec(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), SV_TransitionGameState(), Sys_Init(), and Sys_ListFiles().
cvar_t* Cvar_Set2 (const char * var_name, const char * value, qboolean force)
Cvar_Set2.
Parameters
[in] var_name
[in] value
[in] force
Returns
Definition at line 617 of file cvar.c.
Referenced by Com_StartupVariable(), Cvar_Command(), Cvar_Cycle_f(), Cvar_ForceReset(), Cvar_Get(), Cvar_Reset(), Cvar_Restart(), Cvar_Set(), Cvar_Set2(), Cvar_Set_f(), Cvar_SetLatched(), and Cvar_Toggle_f().
void Cvar_SetCheatState (void)
Any testing variables will be reset to the safe values.
Definition at line 883 of file cvar.c.
Referenced by CL_InitCGame(), and CL_SystemInfoChanged().
void Cvar_SetDescription (cvar_t * cv, const char * varDescription)
Cvar_SetDescription.
Parameters
[in,out] cv
[in] varDescription
Definition at line 1642 of file cvar.c.
Referenced by CL_InitRef(), and Com_InitHunkMemory().
void Cvar_SetLatched (const char * var_name, const char * value)
Cvar_SetLatched.
Parameters
[in] var_name
[in] value
Definition at line 817 of file cvar.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
void Cvar_SetSafe (const char * var_name, const char * value)
Cvar_SetSafe.
Parameters
[in] var_name
[in] value
Definition at line 792 of file cvar.c.
Referenced by CL_CgameSystemCalls(), CL_SystemInfoChanged(), CL_UISystemCalls(), Cvar_SetValueSafe(), and SV_GameSystemCalls().
void Cvar_SetValue (const char * var_name, float value)
Cvar_SetValue.
Parameters
[in] var_name
[in] value
Definition at line 827 of file cvar.c.
Referenced by CL_ParseDownload(), CL_PauseDemo_f(), Com_BeginDownload(), Com_InitHunkMemory(), Com_Printf(), DL_cb_Progress(), IN_Init(), IN_ProcessEvents(), NET_OpenIP(), NET_SetMulticast6(), SV_DemoChangeMaxClients(), SV_DemoCvarsRestore(), SV_DemoRestartPlayback(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopPlayback(), and SV_DemoStopRecord().
void Cvar_SetValueSafe (const char * var_name, float value)
Cvar_SetValueSafe.
Parameters
[in] var_name
[in] value
Definition at line 847 of file cvar.c.
Referenced by CL_UISystemCalls().
void Cvar_Update (vmCvar_t * vmCvar)
Updates an interpreted modules' version of a cvar.
Parameters
[in,out] vmCvar
Definition at line 1761 of file cvar.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Cvar_Register(), and SV_GameSystemCalls().
int Cvar_VariableIntegerValue (const char * var_name)
Cvar_VariableIntegerValue.
Parameters
[in] var_name
Returns
Definition at line 122 of file cvar.c.
Referenced by CL_GetPing(), CL_GlobalServers_f(), CL_InitRef(), CL_KeyEvent(), CL_LocalServers_f(), CL_OpenAVIForWriting(), CL_UpdateLevelHunkUsage(), Com_Frame(), Con_DrawVersion(), FS_FOpenFileReadDir(), GLimp_EndFrame(), GLimp_Init(), GLimp_StartDriverAndSetMode(), S_Update(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_GameSystemCalls(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), and Sys_GLimpInit().
char* Cvar_VariableString (const char * var_name)
Cvar_VariableString.
Parameters
[in] var_name
Returns
Definition at line 139 of file cvar.c.
Referenced by __attribute__(), CIN_StopCinematic(), CL_GlobalServers_f(), CL_NextDemo(), CL_OpenAVIForWriting(), CL_ParseDownload(), CL_SystemInfoChanged(), Cmd_Echo_f(), Cmd_Vstr_f(), Com_CheckAutoUpdate(), Com_CLeanUpdateFolder(), Com_Frame(), Com_Init(), Com_InitDownloads(), Com_InitUpdateDownloads(), Com_RunUpdateBinary(), Com_SetupDownload(), Com_Shutdown(), Com_UnpackUpdatePackage(), Com_WriteConfiguration(), Com_WWWDownload(), Cvar_Toggle_f(), DB_CheckUpdates(), DB_Create(), DB_Init(), DB_SaveMemDB(), DL_BeginDownload(), FS_CalcModHashes(), FS_CheckRequiredFiles(), FS_Restart(), GLimp_EndFrame(), IRC_AttemptConnection(), PrintCvarMatches(), S_LoadSound(), SV_DemoAutoDemoRecord(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopPlayback(), SV_MapRestart_f(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SVC_Info(), Sys_ErrorDialog(), Sys_LoadDll(), Sys_LoadGameDll(), Sys_TryLibraryLoad(), and TranslationMissing().
void Cvar_VariableStringBuffer (const char * var_name, char * buffer, size_t bufsize)
Cvar_VariableStringBuffer.
Parameters
[in] var_name
[out] buffer
[in] bufsize
Definition at line 157 of file cvar.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
float Cvar_VariableValue (const char * var_name)
Cvar_VariableValue.
Parameters
[in] var_name
Returns
Definition at line 105 of file cvar.c.
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_FastForward_f(), CL_PlayDemo_f(), CL_Rewind_f(), CL_Seek_f(), CL_SeekEnd_f(), CL_SystemInfoChanged(), CL_UISystemCalls(), Cvar_Cycle_f(), Cvar_Toggle_f(), and SV_SpawnServer().
void Cvar_WriteVariables (fileHandle_t f)
Appends lines containing "set variable value" for all variables with the archive flag set to qtrue.
Parameters
[in] f
Definition at line 1178 of file cvar.c.
Referenced by Com_WriteConfigToFile().
void Field_AutoComplete (field_t * field)
Perform Tab expansion.
Parameters
[in] field
Definition at line 4074 of file common.c.
Referenced by CON_Input(), and Console_AutoComplete().
void Field_Clear (field_t * field)
Field_Clear.
===========================================
command line completion
Parameters
[out] field
Definition at line 3580 of file common.c.
Referenced by Con_Close(), CON_Init(), Con_Init(), CON_Input(), Con_ToggleConsole_f(), Console_Key(), and Field_CharEvent().
void Field_CompleteCommand (char * cmd, qboolean doCommands, qboolean doCvars)
Field_CompleteCommand.
Parameters
[in,out] cmd
[in] doCommands
[in] doCvars
Definition at line 3794 of file common.c.
Referenced by CL_CompleteRcon(), Cvar_CompleteCvarName(), Field_AutoComplete(), Field_CompleteCommand(), and Key_CompleteBind().
void Field_CompleteFilename (const char * dir, const char * ext, qboolean stripExt, qboolean allowNonPureFilesOnDisk)
Field_CompleteFilename.
Parameters
[in] dir
[in] ext
[in] stripExt
[in] allowNonPureFilesOnDisk
Definition at line 3774 of file common.c.
Referenced by CIN_Completion_VideoName(), CL_CompleteDemoName(), Cmd_CompleteCfgName(), Cmd_CompleteTxtName(), SV_CompleteDemoName(), and SV_CompleteMapName().
void Field_CompleteFilenameMultiple (const char * dir, int numext, const char ** ext, qboolean allowNonPureFilesOnDisk)
Field_CompleteFilenameMultiple.
Parameters
[in] dir
[in] numext
[in] ext
[in] allowNonPureFilesOnDisk
Definition at line 3754 of file common.c.
Referenced by CIN_Completion_VideoName().
void Field_CompleteKeyname (void)
Field_CompleteKeyname.
Definition at line 3733 of file common.c.
Referenced by Key_CompleteBind(), and Key_CompleteUnbind().
void QDECL void QDECL void QDECL format (printf , 2 , 3)
void QDECL format (printf , 1 , 2)
char* FS_BuildOSPath (const char * base, const char * game, const char * qpath)
Qpath may have either forward or backwards slashes.
Parameters
[in] base
[in] game
[in] qpath
Returns
Definition at line 590 of file files.c.
Referenced by CL_ParseDownload(), Com_CLeanUpdateFolder(), Com_InitDownloads(), Com_InitUpdateDownloads(), Com_RunUpdateBinary(), Com_SetupDownload(), Com_UnpackUpdatePackage(), Com_WWWDownload(), DB_CheckUpdates(), DB_Create(), DB_Init(), DB_SaveMemDB(), FS_AddGameDirectory(), FS_CL_ExtractFromPakFile(), FS_ComparePaks(), FS_Delete(), FS_DeleteDir(), FS_FileExists(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_GetModList(), FS_HomeRemove(), FS_ListFilteredFiles(), FS_Rename(), FS_SV_FileExists(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), Sys_ErrorDialog(), and Sys_TryLibraryLoad().
qboolean FS_CheckDirTraversal (const char * checkdir)
Check whether the string contains stuff like "../" to prevent directory traversal bugs.
Parameters
[in] checkdir
Returns
qtrue if it does.
Definition at line 3841 of file files.c.
Referenced by FS_ComparePaks().
void FS_CheckFilenameIsNotExecutable (const char * fileName, const char * function)
ERR_FATAL if trying to manipulate a file with the platform library extension.
Parameters
[in] fileName
[in] function
Definition at line 739 of file files.c.
Referenced by FS_Delete(), FS_HomeRemove(), and FS_SV_Rename().
qboolean FS_CL_ExtractFromPakFile (const char * base, const char * gamedir, const char * fileName)
Extracts the latest file from a pak file.
Compares packed file against extracted file. If no differences, does not copy. This is necessary for exe\/dlls which may or may not be locked.
Parameters
[in] base
[in] gamedir
[in] fileName
Returns
the return value doesn't tell whether file was extracted or not, it just says whether it's ok to continue (i.e. either the right file was extracted successfully, or it was already present)
Note
fullpath gives the full OS path to the dll that will potentially be loaded on win32 it's always in fs_basepath\/<fs_game>\/ on linux it can be in fs_homepath\/<fs_game>\/ or fs_basepath\/<fs_game>\/ The dll is extracted to fs_homepath (== fs_basepath on win32) if needed
cvar_lastVersion is the optional name of a CVAR_ARCHIVE used to store the wolf version for the last extracted .so
Definition at line 1731 of file files.c.
Referenced by Sys_LoadGameDll().
void FS_ClearPakReferences (int flags)
FS_ClearPakReferences.
Parameters
[in] flags
Definition at line 4503 of file files.c.
Referenced by CL_Vid_Restart_f(), FS_Restart(), and SV_SpawnServer().
void FS_ClearPureServerPacks (void)
FS_ClearPureServerPacks.
Definition at line 4524 of file files.c.
Referenced by CL_Connect_f(), and CL_Disconnect().
qboolean FS_ComparePaks (char * neededpaks, size_t len, qboolean dlstring)
FS_ComparePaks.
dlstring == qtrue Returns a list of pak files that we should download from the server. They all get stored in the current gamedir and an FS_Restart will be fired up after we download them all.
The string is the format:
@remotename@localname [repeat]
static int fs_numServerReferencedPaks; static int fs_serverReferencedPaks[MAX_SEARCH_PATHS]; static char *fs_serverReferencedPakNames[MAX_SEARCH_PATHS];
dlstring == qfalse
we are not interested in a download string format, we want something human-readable
(this is used for diagnostics while connecting to a pure server)
Parameters
[out] neededpaks
[in] len
[in] dlstring
Returns
Definition at line 3895 of file files.c.
Referenced by Com_InitDownloads().
qboolean FS_ConditionalRestart (int checksumFeed)
Restart if necessary.
Parameters
[in] checksumFeed
Returns
Todo:
This doesn't catch all cases where an FS_Restart is necessary
Definition at line 4849 of file files.c.
Referenced by CL_ParseGamestate(), CL_Vid_Restart_f(), and Com_RunUpdateBinary().
void FS_CopyFile (const char * fromOSPath, const char * toOSPath)
Copy a fully specified file from one place to another.
Parameters
fromOSPath
toOSPath
Definition at line 668 of file files.c.
Referenced by Com_WWWDownload(), FS_Rename(), and FS_SV_Rename().
qboolean FS_CreatePath (const char * OSPath)
Creates any directories needed to store the given fileName.
Parameters
[in] OSPath
Returns
Definition at line 623 of file files.c.
Referenced by DB_CheckUpdates(), DB_Create(), DB_SaveMemDB(), DL_BeginDownload(), FS_CopyFile(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileWrite(), FS_SV_FOpenFileWrite(), and FS_UnzipTo().
int FS_Delete (const char * fileName)
Removes file in the current fs_gamedir in homepath.
Parameters
[in] fileName
Returns
Definition at line 1961 of file files.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Com_CheckProfile(), Com_Shutdown(), Com_TrackProfile(), and Sys_WritePIDFile().
void FS_FCloseFile (fileHandle_t f)
If the FILE pointer is an open pak file, leave it open.
Parameters
[in] f
Note
For some reason, other dll's can't just cal fclose() on files returned by FS_FOpenFile...
Definition at line 1053 of file files.c.
Referenced by CIN_FreeCinematic(), CL_Cache_EndGather_f(), CL_CgameSystemCalls(), CL_CloseAVI(), CL_DemoCleanUp(), CL_Disconnect(), CL_GenerateETKey(), CL_OpenAVIForWriting(), CL_ParseDownload(), CL_SetExpectedHunkUsage(), CL_StopRecord_f(), CL_UISystemCalls(), CL_UpdateGUID(), CL_UpdateLevelHunkUsage(), CL_WriteWaveClose(), Com_CheckProfile(), Com_MD5File(), Com_Shutdown(), Com_WriteConfigToFile(), Con_Dump_f(), FS_CL_ExtractFromPakFile(), FS_GetModList(), FS_ReadFile(), FS_Shutdown(), FS_TouchFile_f(), FS_WriteFile(), LAN_LoadCachedServers(), LAN_SaveServersToFile(), S_CodecUtilClose(), S_CodecUtilOpen(), S_WAV_CodecLoad(), SV_BotInitBotLib(), SV_CloseAttackLog(), SV_CloseDownload(), SV_DemoStopPlayback(), SV_DemoStopRecord(), SV_GameSystemCalls(), SV_SetExpectedHunkUsage(), SV_SetupDownloadFile(), SV_TouchCGameDLL(), Sys_WritePIDFile(), TranslationMissing(), and QInputbuf::~QInputbuf().
qboolean FS_FileExists (const char * file)
Tests if the file exists in the current gamedir of fs_homepath.
DOES NOT search the paths. This is to determine if opening a file to write (which always goes into the current gamedir) will cause any overwrites.
Parameters
[in] file
Note
This goes with FS_FOpenFileWrite for opening the file afterwards
Definition at line 831 of file files.c.
Referenced by __attribute__(), CL_InitRef(), CL_StartVideoRecording(), CL_WriteWaveOpen(), Com_Shutdown(), Com_TrackProfile(), and SV_Demo_Record_f().
qboolean FS_FileInPathExists (const char * testpath)
Tests if path and file exists.
Parameters
[in] testpath
Returns
Definition at line 806 of file files.c.
Referenced by Com_CLeanUpdateFolder(), Com_UnpackUpdatePackage(), FS_FileExists(), FS_SV_FileExists(), and Sys_WritePIDFile().
int FS_FileIsInPAK (const char * fileName, int * pChecksum)
FS_FileIsInPAK.
======================================================================================
CONVENIENCE FUNCTIONS FOR ENTIRE FILES
Parameters
[in] fileName
[out] pChecksum
Returns
Definition at line 2276 of file files.c.
Referenced by CL_InitRef(), and SV_VerifyPaks_f().
long FS_filelength (fileHandle_t f)
If this is called on a non-unique FILE (from a pak file), it will return the size of the pak file, not the expected size of the file.
Parameters
[in] f
Returns
Definition at line 537 of file files.c.
Referenced by FS_SV_FOpenFileRead().
qboolean FS_FilenameCompare (const char * s1, const char * s2)
Compare filenames Ignores case and separator char distinctions.
Parameters
[in] s1
[in] s2
Returns
Definition at line 1216 of file files.c.
Referenced by FS_FileIsInPAK(), FS_FOpenFileReadDir(), FS_idPak(), and Sys_LoadDll().
void FS_FilenameCompletion (const char * dir, int numext, const char ** ext, qboolean stripExt, void(*)(const char *s) callback, qboolean allowNonPureFilesOnDisk)
FS_FilenameCompletion.
Parameters
[in] dir
[in] numext
[in] ext
[in] stripExt
callback
[in] allowNonPureFilesOnDisk
Definition at line 4965 of file files.c.
Referenced by Field_CompleteFilename(), and Field_CompleteFilenameMultiple().
void FS_Flush (fileHandle_t f)
FS_Flush.
Parameters
[in] f
Definition at line 4951 of file files.c.
Referenced by FS_ReadFile().
int FS_FOpenFileByMode (const char * qpath, fileHandle_t * f, fsMode_t mode)
Handle based file calls for virtual machines.
Parameters
[in] qpath
[in,out] f
[in] mode
Returns
Definition at line 4868 of file files.c.
Referenced by CL_CgameSystemCalls(), CL_SetExpectedHunkUsage(), CL_UISystemCalls(), CL_UpdateLevelHunkUsage(), SV_BotInitBotLib(), SV_GameSystemCalls(), SV_InitAttackLog(), SV_SetExpectedHunkUsage(), and TranslationMissing().
long FS_FOpenFileRead (const char * fileName, fileHandle_t * file, qboolean uniqueFILE)
Finds the file in the search path. Used for streaming data out of either a separate file or a ZIP file.
Parameters
[in] fileName
[in,out] file
[in] uniqueFILE
Returns
filesize and an open FILE pointer - 0 or -1 for invalid files
Definition at line 1636 of file files.c.
Referenced by CIN_PlayCinematic(), CL_CloseAVI(), CL_InitRef(), CL_PlayDemo_f(), CL_WalkDemoExt(), Com_CheckProfile(), Com_InitJournaling(), FS_CheckRequiredFiles(), FS_FOpenFileByMode(), FS_FOpenFileRead_Filtered(), FS_ReadFile(), FS_TouchFile_f(), LAN_LoadCachedServers(), QInputbuf::QInputbuf(), S_CodecUtilOpen(), S_LoadSound(), S_WAV_CodecLoad(), SV_Demo_Play_f(), and SV_DemoStartPlayback().
long FS_FOpenFileRead_Filtered (const char * qpath, fileHandle_t * file, qboolean uniqueFILE, int filter_flag)
Definition at line 1697 of file files.c.
Referenced by SV_TouchCGameDLL().
fileHandle_t FS_FOpenFileWrite (const char * fileName)
FS_FOpenFileWrite.
Parameters
[in] fileName
Returns
Definition at line 1084 of file files.c.
Referenced by CL_Cache_EndGather_f(), CL_OpenAVIForWriting(), CL_Record(), CL_UpdateLevelHunkUsage(), CL_WriteWaveOpen(), Com_InitJournaling(), Com_Printf(), Com_WriteConfigToFile(), Con_Dump_f(), FS_FOpenFileByMode(), FS_WriteFile(), LAN_SaveServersToFile(), SV_Demo_Record_f(), and Sys_WritePIDFile().
void FS_ForceFlush (fileHandle_t f)
FS_ForceFlush.
Parameters
[in] f
Definition at line 500 of file files.c.
Referenced by Com_Printf().
void FS_FreeFile (void * buffer)
FS_FreeFile.
Parameters
[out] buffer
Definition at line 2487 of file files.c.
Referenced by CL_InitRef(), CM_LoadMap(), Cmd_Exec_f(), Com_Init(), Com_MD5FileETCompat(), FS_CL_ExtractFromPakFile(), SV_LoadTag(), VM_Create(), VM_LoadSymbols(), and VM_Restart().
void FS_FreeFileList (char ** list)
FS_FreeFileList.
Parameters
[in,out] list
Definition at line 2939 of file files.c.
Referenced by CL_InitRef(), FS_Dir_f(), FS_FilenameCompletion(), FS_GetFileList(), FS_NewDir_f(), and QFileSystem::open_directory().
int FS_FTell (fileHandle_t f)
FS_FTell.
Parameters
[in] f
Returns
Definition at line 4921 of file files.c.
Referenced by CL_ParseDemo(), CL_PeekSnapshot(), CL_ReadDemoMessage(), FS_Seek(), and SCR_DrawDemoRecording().
int FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
FS_GetFileList.
Parameters
[in] path
[in] extension
[out] listbuf
[in] bufsize
Returns
Definition at line 2969 of file files.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
int FS_GetModList (char * listbuf, int bufsize)
A mod directory is a peer to etmain with a pk3 in it The directories are searched in base path and home path.
Parameters
listbuf
bufsize
Returns
A list of mod directory names
Definition at line 3100 of file files.c.
Referenced by FS_GetFileList().
void FS_HomeRemove (const char * homePath)
FS_HomeRemove.
Parameters
[in] homePath
Definition at line 787 of file files.c.
Referenced by CL_CloseAVI().
qboolean FS_idPak (const char * pak, const char * base)
FS_idPak.
Parameters
[in] pak
[in] base
Returns
Definition at line 3730 of file files.c.
Referenced by FS_ComparePaks(), FS_VerifyOfficialPaks(), and SV_CheckDownloadAllowed().
void FS_InitFilesystem (void)
Called only at initial startup, not when the filesystem is resetting due to a game change.
Definition at line 4741 of file files.c.
Referenced by Com_Init().
qboolean FS_Initialized (void)
FS_Initialized.
Returns
Definition at line 377 of file files.c.
Referenced by Com_Printf(), Hunk_Log(), Hunk_SmallLog(), and Z_LogZoneHeap().
qboolean FS_InvalidGameDir (const char * gamedir)
FS_InvalidGameDir.
Parameters
Definition at line 3856 of file files.c.
Referenced by CL_SystemInfoChanged(), and FS_Startup().
qboolean FS_IsSamePath (const char * s1, const char * s2)
Similar to FS_PathCmp() but real path name comparison. It deals with trailing slashes and relative paths.
Warning
Do not use this with quake game paths - only real filesystem paths!
Parameters
[in] s1 path A
[in] s2 path B
Definition at line 3345 of file files.c.
Referenced by FS_Startup().
char** FS_ListFiles (const char * path, const char * extension, int * numfiles)
FS_ListFiles.
Parameters
[in] path
[in] extension
[out] numfiles
Returns
Definition at line 2930 of file files.c.
Referenced by CL_InitRef(), FS_Dir_f(), FS_GetFileList(), and QFileSystem::open_directory().
const char* FS_LoadedPakChecksums (void)
FS_LoadedPakChecksums.
Returns
A space separated string containing the checksums of all loaded pk3 files. Servers with sv_pure set will get this string and pass it to clients.
Definition at line 4264 of file files.c.
Referenced by SV_SpawnServer().
const char* FS_LoadedPakNames (void)
FS_LoadedPakNames.
Returns
A space separated string containing the names of all loaded pk3 files. Servers with sv_pure set will get this string and pass it to clients.
Definition at line 4298 of file files.c.
Referenced by CL_OpenedPK3List_f(), and SV_SpawnServer().
const char* FS_LoadedPakPureChecksums (void)
FS_LoadedPakPureChecksums.
Returns
A space separated string containing the pure checksums of all loaded pk3 files. Servers with sv_pure use these checksums to compare with the checksums the clients send back to the server.
Definition at line 4333 of file files.c.
Referenced by SV_VerifyPaks_f().
int FS_LoadStack (void)
return load stack
Definition at line 411 of file files.c.
Referenced by Com_InitHunkMemory().
int FS_OSStatFile (const char * ospath)
Definition at line 1940 of file files.c.
Referenced by FS_Delete(), and FS_DeleteDir().
void QDECL FS_Printf (fileHandle_t h, const char * fmt, ...)
FS_Printf.
Parameters
[in] h
[in] fmt
Definition at line 2138 of file files.c.
Referenced by Com_WriteConfigToFile(), Key_WriteBindings(), and Sys_WritePIDFile().
void FS_PureServerSetLoadedPaks (const char * pakSums, const char * pakNames)
If the string is empty, all data sources will be allowed. If not empty, only pk3 files that match one of the space separated checksums will be checked for files, with the exception of .cfg and .dat files.
Parameters
[in] pakSums
[in] pakNames
Definition at line 4552 of file files.c.
Referenced by CL_SystemInfoChanged(), Com_Error(), and FS_CheckRequiredFiles().
void FS_PureServerSetReferencedPaks (const char * pakSums, const char * pakNames)
The checksums and names of the pk3 files referenced at the server are sent to the client and stored here. The client will use these checksums to see if any pk3 files need to be auto-downloaded.
Parameters
[in] pakSums
[in] pakNames
Definition at line 4624 of file files.c.
Referenced by CL_SystemInfoChanged().
int FS_Read (void * buffer, int len, fileHandle_t f)
FS_Read.
Parameters
[out] buffer
[in] len
[in] f
Returns
Definition at line 2013 of file files.c.
Referenced by CIN_DecodeChunk(), CL_CgameSystemCalls(), CL_CloseAVI(), CL_InitRef(), CL_ParseDemo(), CL_PeekSnapshot(), CL_ReadDemoMessage(), CL_SetExpectedHunkUsage(), CL_UISystemCalls(), CL_UpdateLevelHunkUsage(), Com_CheckProfile(), Com_GetRealEvent(), Com_MD5File(), FGetLittleLong(), FGetLittleShort(), FS_ReadFile(), FS_Seek(), LAN_LoadCachedServers(), ROQ_StartRead(), S_ReadChunkInfo(), S_ReadRIFFHeader(), S_WAV_CodecLoad(), S_WAV_CodecReadStream(), SV_BotInitBotLib(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_GameSystemCalls(), SV_SetExpectedHunkUsage(), SV_WriteDownloadToClient(), and QInputbuf::underflow().
int FS_ReadFile (const char * qpath, void ** buffer)
Open a file relative to the ET:L search path. A null buffer will just return the file length without loading.
Parameters
[in] qpath
[out] buffer
Returns
Definition at line 2353 of file files.c.
Referenced by CL_InitRef(), CL_Record_f(), CM_LoadMap(), Cmd_Exec_f(), Com_Init(), Com_MD5FileETCompat(), FS_CL_ExtractFromPakFile(), S_FindCodecForFile(), SV_LoadTag(), SV_Map_f(), VM_Create(), VM_LoadSymbols(), and VM_Restart().
const char* FS_ReferencedPakChecksums (void)
FS_ReferencedPakChecksums.
Returns
A space separated string containing the checksums of all referenced pk3 files. The server will send this to the clients so they can check which files should be auto-downloaded.
Definition at line 4370 of file files.c.
Referenced by SV_SpawnServer().
const char* FS_ReferencedPakNames (void)
FS_ReferencedPakNames.
Returns
A space separated string containing the names of all referenced pk3 files. The server will send this to the clients so they can check which files should be auto-downloaded.
Definition at line 4405 of file files.c.
Referenced by CL_ReferencedPK3List_f(), and SV_SpawnServer().
const char* FS_ReferencedPakPureChecksums (void)
This function is only used by the client to build the string sent back to server, it's useless in dedicated.
Returns
A space separated string containing the pure checksums of all referenced pk3 files. Servers with sv_pure set will get this string back from clients for pure validation
Note
The string has a specific order, "cgame ui @ ref1 ref2 ref3 ..."
Definition at line 4450 of file files.c.
Referenced by CL_SendPureChecksums().
void FS_Remove (const char * osPath)
FS_Remove.
Parameters
[in] osPath
Note
Ensure file removals are save when initiated by user inputs - call FS_CheckFilenameIsMutable or FS_CheckFilenameIsNotExecutable before to avoid unwanted binary or pk3 removals
Definition at line 771 of file files.c.
Referenced by Com_CLeanUpdateFolder(), FS_ComparePaks(), FS_Rename(), and FS_SV_Rename().
void FS_Rename (const char * from, const char * to)
FS_Rename.
Parameters
[in] from
[in] to
Definition at line 1018 of file files.c.
Referenced by SV_GameSystemCalls().
void FS_Restart (int checksumFeed)
FS_Restart.
Parameters
[in] checksumFeed
Definition at line 4789 of file files.c.
Referenced by Com_DownloadsComplete(), FS_CheckRequiredFiles(), FS_ClearPureServerPacks(), FS_ConditionalRestart(), FS_PureServerSetLoadedPaks(), and SV_SpawnServer().
int FS_Seek (fileHandle_t f, long offset, int origin)
FS_Seek.
Parameters
[in] f
[in] offset
[in] origin
Returns
Todo:
: this is really, really
Definition at line 2159 of file files.c.
Referenced by CL_CloseAVI(), CL_ParseDemo(), CL_PeekSnapshot(), CL_RewindDemo(), CL_WriteWaveClose(), ROQ_Reset(), ROQ_UpdateCinematic(), S_FindRIFFChunk(), S_ReadRIFFHeader(), and SV_BotInitBotLib().
void FS_Shutdown (qboolean closemfp)
Frees all resources and closes all files.
Parameters
closemfp - unused
Definition at line 4019 of file files.c.
Referenced by Com_Quit_f(), and FS_Restart().
qboolean FS_SV_FileExists (const char * file)
Tests if the file in fs_homepath exists.
Parameters
[in] file
Returns
Definition at line 853 of file files.c.
Referenced by DB_Init(), and FS_ComparePaks().
long FS_SV_FOpenFileRead (const char * fileName, fileHandle_t * fp)
search for a file somewhere below the home path, base path or cd path we search in that order, matching FS_SV_FOpenFileRead order
Parameters
[in] fileName
[out] fp
Todo:
: use FS_PathCmp() (slashes, low/big letters ... trailing slash)
Definition at line 917 of file files.c.
Referenced by CL_GenerateETKey(), CL_UpdateGUID(), Com_MD5File(), FS_GetModList(), and SV_SetupDownloadFile().
fileHandle_t FS_SV_FOpenFileWrite (const char * fileName)
FS_SV_FOpenFileWrite.
Parameters
[in] fileName
Returns
Definition at line 868 of file files.c.
Referenced by CL_GenerateETKey(), and CL_ParseDownload().
void FS_SV_Rename (const char * from, const char * to)
FS_SV_Rename - used to rename downloaded files from .tmp to .pk3.
Parameters
[in] from
[in] to
Definition at line 984 of file files.c.
Referenced by CL_ParseDownload().
qboolean FS_Unzip (const char * fileName, qboolean quiet)
Extracts zipped file into the current gamedir.
Parameters
[in] fileName to extract
[in] quiet whether to inform if unzipping fails
Returns
qtrue if successfully extracted
qfalse if extraction failed
Definition at line 5237 of file files.c.
Referenced by Sys_TryLibraryLoad().
qboolean FS_UnzipTo (const char * fileName, const char * outpath, qboolean quiet)
Extracts zipped file into the selected path.
Parameters
[in] fileName to extract
[in] outpath the path where to write the extracted files
[in] quiet whether to inform if unzipping fails
Returns
qtrue if successfully extracted
qfalse if extraction failed
Definition at line 5033 of file files.c.
Referenced by Com_UnpackUpdatePackage(), and FS_Unzip().
qboolean FS_VerifyOfficialPaks (void)
FS_VerifyOfficialPaks.
Returns
Definition at line 3761 of file files.c.
Referenced by CL_ParseGamestate().
qboolean FS_VerifyPak (const char * pak)
Compared requested pak against the names as we built them in FS_ReferencedPakNames.
Parameters
pak
Returns
Note
CVE-2006-2082
Definition at line 5002 of file files.c.
Referenced by SV_WriteDownloadToClient().
int FS_Write (const void * buffer, int len, fileHandle_t h)
Properly handles partial writes.
Parameters
[in] buffer
[in] len
[in] h
Returns
Definition at line 2077 of file files.c.
Referenced by CL_Cache_EndGather_f(), CL_CgameSystemCalls(), CL_GenerateETKey(), CL_ParseDownload(), CL_Record(), CL_StopRecord_f(), CL_UISystemCalls(), CL_UpdateLevelHunkUsage(), CL_WriteDemoMessage(), CL_WriteWaveClose(), CL_WriteWaveHeader(), Com_GetRealEvent(), Com_Printf(), Con_Dump_f(), Cvar_WriteVariables(), FS_CL_ExtractFromPakFile(), FS_Printf(), FS_ReadFile(), FS_WriteFile(), Hunk_Log(), Hunk_SmallLog(), LAN_SaveServersToFile(), SafeFS_Write(), SV_BotInitBotLib(), SV_DemoWriteMessage(), SV_GameSystemCalls(), SV_WriteAttackLog(), TranslationMissing(), and Z_LogZoneHeap().
void FS_WriteFile (const char * qpath, const void * buffer, int size)
Filename are reletive to the quake search path.
Parameters
[in] qpath
[out] buffer
[in] size
Definition at line 2514 of file files.c.
Referenced by CL_InitRef().
void Hist_Add (field_t * field)
Definition at line 200 of file con_tty.c.
Referenced by CON_Input().
field_t* Hist_Next (void)
Definition at line 256 of file con_tty.c.
Referenced by CON_Input().
field_t* Hist_Prev (void)
Definition at line 233 of file con_tty.c.
Referenced by CON_Input().
void Huff_addRef (huff_t * huff, byte ch)
Huff_addRef.
Parameters
[in,out] huff
[in] ch
Definition at line 295 of file huffman.c.
Referenced by Huff_Compress(), Huff_Decompress(), and MSG_initHuffman().
void Huff_Compress (msg_t * mbuf, int offset)
Huff_Compress.
Parameters
[in,out] mbuf
[in] offset
Definition at line 594 of file huffman.c.
Referenced by NET_OutOfBandData().
void Huff_Decompress (msg_t * mbuf, int offset)
Huff_Decompress.
Parameters
[in,out] mbuf
[in] offset
Todo:
: would it be better to have a overflow check in get_bit ?
Definition at line 528 of file huffman.c.
Referenced by SV_ConnectionlessPacket().
int Huff_getBit (byte * fin, int * offset)
Huff_getBit.
Parameters
[in] fin
[in,out] offset
Returns
Definition at line 71 of file huffman.c.
Referenced by MSG_ReadBits().
void Huff_Init (huffman_t * huff)
Huff_Init.
Parameters
[in,out] huff
Definition at line 640 of file huffman.c.
Referenced by MSG_initHuffman().
void Huff_offsetReceive (node_t * node, int * ch, byte * fin, int * offset, int maxoffset)
Get a symbol.
Parameters
[in] node
[out] ch
[in] fin
[out] offset
[in] maxoffset
Definition at line 421 of file huffman.c.
Referenced by MSG_ReadBits().
void Huff_offsetTransmit (huff_t * huff, int ch, byte * fout, int * offset, int maxoffset)
Huff_offsetTransmit.
Parameters
[in] huff
[in] ch
[out] fout
[in,out] offset
[in] maxoffset
Definition at line 516 of file huffman.c.
Referenced by MSG_WriteBits().
void Huff_putBit (int bit, byte * fout, int * offset)
Clears data along the way so we dont have to memset() it ahead of time.
Parameters
[in] bit
[out] fout
[out] offset
Definition at line 49 of file huffman.c.
Referenced by MSG_WriteBits().
int Huff_Receive (node_t * node, int * ch, byte * fin)
Get a symbol.
Parameters
[in] node
[out] ch
[in] fin
Returns
Definition at line 392 of file huffman.c.
Referenced by Huff_Decompress().
void Huff_transmit (huff_t * huff, int ch, byte * fout, int maxoffset)
Huff_transmit.
Parameters
[in] huff
[in] ch
[out] fout
[in] maxoffset
Definition at line 489 of file huffman.c.
Referenced by Huff_Compress(), and Huff_transmit().
void* Hunk_AllocateTempMemory (unsigned int size)
This is used by the file loading system. Multiple files can be loaded in temporary memory. When the files-in-use count reaches zero, all temp memory will be deleted.
Parameters
size
Returns
Definition at line 2068 of file common.c.
Referenced by CL_InitRef(), Con_Dump_f(), FS_ReadFile(), S_LoadSound(), S_WAV_CodecLoad(), SV_ChangeMaxClients(), and SV_DemoChangeMaxClients().
qboolean Hunk_CheckMark (void)
Hunk_CheckMark.
Returns
Definition at line 1906 of file common.c.
Referenced by BotImport_HunkAlloc().
void Hunk_Clear (void)
The server calls this before shutting down or loading a new map.
Definition at line 1921 of file common.c.
Referenced by CL_FlushMemory(), CL_Vid_Restart_f(), Com_InitHunkMemory(), and SV_SpawnServer().
void Hunk_ClearTempMemory (void)
The temp space is no longer needed.
If we have left more touched but unused memory on this side, have future permanent allocs use this side.
Definition at line 2175 of file common.c.
Referenced by FS_FreeFile().
void Hunk_ClearToMark (void)
The client calls this before starting a vid_restart or snd_restart.
Definition at line 1896 of file common.c.
Referenced by CL_FlushMemory(), CL_InitRef(), and CL_Vid_Restart_f().
void Hunk_FreeTempMemory (void * buf)
Hunk_FreeTempMemory.
Parameters
[out] buf
Definition at line 2121 of file common.c.
Referenced by CL_InitRef(), Con_Dump_f(), FS_FreeFile(), S_LoadSound(), SV_ChangeMaxClients(), and SV_DemoChangeMaxClients().
void Hunk_Log (void)
Hunk_Log.
Definition at line 1717 of file common.c.
Referenced by Com_InitHunkMemory(), and Hunk_Alloc().
int Hunk_MemoryRemaining (void)
Hunk_MemoryRemaining.
Returns
Definition at line 1876 of file common.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and VM_Create().
void Hunk_SetMark (void)
The server calls this after the level and game VM have been loaded.
Definition at line 1887 of file common.c.
Referenced by SV_SpawnServer().
void Hunk_SmallLog (void)
Hunk_SmallLog.
Definition at line 1749 of file common.c.
Referenced by Com_InitHunkMemory(), and Hunk_Alloc().
void I18N_Init (void)
Attempts to detect the system language unless cl_lang was already set. Then loads the PO file containing translated strings.
Definition at line 204 of file i18n_main.cpp.
Referenced by CL_Init(), and CL_Vid_Restart_f().
void I18N_SetLanguage (const char * language)
Loads a localization file.
Parameters
[in] language
Todo:
: check if there is a localization file available for the selected language
Definition at line 268 of file i18n_main.cpp.
Referenced by _I18N_Translate(), and I18N_Init().
const char* I18N_Translate (const char * msgid)
I18N_Translate.
Parameters
[in] msgid
Returns
Definition at line 335 of file i18n_main.cpp.
const char* I18N_TranslateMod (const char * msgid)
I18N_TranslateMod.
Parameters
[in] msgid
Returns
Definition at line 345 of file i18n_main.cpp.
char* IN_GetClipboardData (void)
IN_GetClipboardData.
Returns
Definition at line 75 of file sdl_input.c.
Referenced by Field_Paste(), and GetClipboardData().
qboolean IN_IsNumLockDown (void)
Check if Num key is lock down.
Returns
qtrue if Num key is lock down, qfalse if not
Definition at line 112 of file sdl_input.c.
Referenced by CL_KeyEvent().
void Info_Print (const char * s)
Info_Print - prints key and values of a given String to console.
Parameters
[in] s
Definition at line 633 of file common.c.
Referenced by CL_Clientinfo_f(), SV_DumpUser_f(), SV_Serverinfo_f(), and SV_Systeminfo_f().
void Key_KeynameCompletion (void(*)(const char *s) callback)
Key_KeynameCompletion.
Definition at line 1158 of file cl_keys.c.
Referenced by Field_CompleteKeyname().
void Key_WriteBindings (fileHandle_t f)
Writes lines containing "bind key value".
Parameters
[in] f Writes lines containing "bind key value".
f - unused
Definition at line 1103 of file cl_keys.c.
Referenced by Com_WriteConfigToFile().
void MSG_BeginReading (msg_t * msg)
MSG_BeginReading.
Parameters
[out] msg
Definition at line 137 of file msg.c.
void MSG_BeginReadingOOB (msg_t * msg)
Definition at line 144 of file msg.c.
Referenced by CL_ConnectionlessPacket(), Netchan_Process(), SV_ConnectionlessPacket(), and SV_PacketEvent().
void MSG_BeginReadingUncompressed (msg_t * msg)
MSG_BeginReadingUncompressed.
Parameters
[out] msg
Definition at line 155 of file msg.c.
Referenced by CL_ParseBinaryMessage(), and SV_ParseBinaryMessage().
void MSG_Bitstream (msg_t * buf)
MSG_Bitstream.
Parameters
[out] buf
Definition at line 117 of file msg.c.
Referenced by CL_ParseDemo(), CL_ParseServerMessage(), CL_PeekSnapshot(), CL_Record(), CL_WritePacket(), and SV_ExecuteClientMessage().
void MSG_Clear (msg_t * buf)
MSG_Clear.
Parameters
[out] buf
Definition at line 106 of file msg.c.
Referenced by SV_DemoReadFrame(), SV_DemoWriteMessage(), SV_SendClientIdle(), and SV_SendClientSnapshot().
void MSG_Copy (msg_t * buf, byte * data, int length, msg_t * src)
MSG_Copy.
copy a msg_t in case we need to store it as is for a bit (as I needed this to keep an msg_t from a static var for later use) sets data buffer as MSG_Init does prior to do the copy
Parameters
[out] buf
[in] data
[in] length
[in] src
Definition at line 169 of file msg.c.
Referenced by SV_Netchan_Transmit().
void* MSG_GetSpace (msg_t * buf, int length)
int MSG_HashKey (const char * string, int maxlen)
Definition at line 602 of file msg.c.
Referenced by CL_WritePacket(), and SV_UserMove().
void MSG_Init (msg_t * buf, byte * data, int length)
MSG_Init.
Parameters
[out] buf
[in] data
[in] length
Definition at line 69 of file msg.c.
Referenced by CL_ParseDemo(), CL_PeekSnapshot(), CL_ReadDemoMessage(), CL_Record(), CL_WritePacket(), Com_EventLoop(), NET_Event(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopRecord(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DemoWriteAllPlayerState(), SV_DemoWriteClientCommand(), SV_DemoWriteClientConfigString(), SV_DemoWriteClientUserinfo(), SV_DemoWriteConfigString(), SV_DemoWriteFrame(), SV_DemoWriteGameCommand(), SV_DemoWriteServerCommand(), SV_SendClientGameState(), SV_SendClientIdle(), SV_SendClientSnapshot(), and SV_SendDownloadMessages().
void MSG_InitOOB (msg_t * buf, byte * data, int length)
MSG_InitOOB.
Parameters
[out] buf
[in] data
[in] length
Definition at line 88 of file msg.c.
Referenced by Netchan_Transmit(), and Netchan_TransmitNextFragment().
float MSG_ReadAngle16 (msg_t * msg)
MSG_ReadAngle16.
Parameters
[in] msg
Returns
Definition at line 842 of file msg.c.
char* MSG_ReadBigString (msg_t * msg)
MSG_ReadBigString.
Parameters
[in] msg
Returns
Definition at line 764 of file msg.c.
Referenced by CL_ParseDemo(), CL_ParseGamestate(), and CL_PrintPacket().
int MSG_ReadBits (msg_t * msg, int bits)
MSG_ReadBits.
Parameters
[in,out] msg
[in] bits
Returns
Definition at line 299 of file msg.c.
Referenced by CL_ParseDemo(), CL_ParseGamestate(), CL_ParsePacketEntities(), MSG_ReadByte(), MSG_ReadChar(), MSG_ReadDeltaEntity(), MSG_ReadDeltaKey(), MSG_ReadDeltaKeyFloat(), MSG_ReadDeltaPlayerstate(), MSG_ReadDeltaSharedEntity(), MSG_ReadDeltaUsercmdKey(), MSG_ReadFloat(), MSG_ReadLong(), MSG_ReadShort(), SV_DemoReadAllEntityShared(), and SV_DemoReadAllEntityState().
int MSG_ReadByte (msg_t * msg)
MSG_ReadByte.
Parameters
[in] msg
Returns
-1 if no more characters are available
Definition at line 648 of file msg.c.
Referenced by CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PeekSnapshot(), MSG_ReadBigString(), MSG_ReadData(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReadDeltaSharedEntity(), MSG_ReadString(), MSG_ReadStringLine(), SV_DemoReadAllPlayerState(), SV_DemoReadClientCommand(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DemoReadFrame(), SV_DemoReadGameCommand(), SV_DemoStartPlayback(), SV_ExecuteClientMessage(), and SV_UserMove().
int MSG_ReadChar (msg_t * msg)
MSG_ReadChar.
Parameters
[in] msg
Returns
-1 if no more characters are available
Definition at line 630 of file msg.c.
void MSG_ReadData (msg_t * msg, void * data, int size)
MSG_ReadData.
Parameters
[in] msg
[in] data
[in] size
Definition at line 853 of file msg.c.
Referenced by CL_ParseDemoSnapShotSimple(), CL_ParseDownload(), and CL_ParseSnapshot().
void MSG_ReadDeltaEntity (msg_t * msg, entityState_t * from, entityState_t * to, int number)
The entity number has already been read from the message, which is how the from state is identified.
If the delta removes the entity, entityState_t->number will be set to MAX_GENTITIES-1
Can go from either a baseline or a previous packet_entity
Parameters
[in] msg
[in] from
[out] to
[in] number
Definition at line 1430 of file msg.c.
Referenced by CL_DeltaEntity(), CL_ParseDemo(), CL_ParseGamestate(), and SV_DemoReadAllEntityState().
void MSG_ReadDeltaPlayerstate (msg_t * msg, playerState_t * from, playerState_t * to)
MSG_ReadDeltaPlayerstate.
Parameters
[in] msg
[in] from
[out] to
Definition at line 2324 of file msg.c.
Referenced by CL_ParseDemoSnapShotSimple(), CL_ParseSnapshot(), and SV_DemoReadAllPlayerState().
void MSG_ReadDeltaSharedEntity (msg_t * msg, void * from, void * to, int number)
MSG_ReadDeltaSharedEntity.
Parameters
[in] msg
[in] from
[in] to
number - unused
Definition at line 1766 of file msg.c.
Referenced by SV_DemoReadAllEntityShared().
void MSG_ReadDeltaUsercmdKey (msg_t * msg, int key, usercmd_t * from, usercmd_t * to)
MSG_ReadDeltaUsercmdKey.
Parameters
[in] msg
[in] key
[in] from
[out] to
Definition at line 1026 of file msg.c.
Referenced by SV_UserMove().
float MSG_ReadFloat (msg_t * msg)
MSG_ReadFloat.
Parameters
[in] msg
Returns
-1 if no more characters are available
Definition at line 701 of file msg.c.
int MSG_ReadLong (msg_t * msg)
MSG_ReadLong.
Parameters
[in] msg
Returns
-1 if no more characters are available
Definition at line 683 of file msg.c.
Referenced by CL_ConnectionlessPacket(), CL_Netchan_Decode(), CL_Netchan_Encode(), CL_ParseCommandString(), CL_ParseDemo(), CL_ParseDemoSnapShotSimple(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PeekSnapshot(), MSG_ReadDeltaPlayerstate(), Netchan_Process(), SV_ClientCommand(), SV_ConnectionlessPacket(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_ExecuteClientMessage(), SV_Netchan_Decode(), SV_Netchan_Encode(), and SV_PacketEvent().
int MSG_ReadShort (msg_t * msg)
MSG_ReadShort.
Parameters
[in] msg
Returns
-1 if no more characters are available
Definition at line 665 of file msg.c.
Referenced by CL_ParseDemo(), CL_ParseDownload(), CL_ParseGamestate(), MSG_ReadAngle16(), MSG_ReadDeltaPlayerstate(), Netchan_Process(), and SV_PacketEvent().
char* MSG_ReadString (msg_t * msg)
MSG_ReadString.
Parameters
[in] msg
Returns
Definition at line 724 of file msg.c.
Referenced by CL_ParseCommandString(), CL_ParseDemo(), CL_ParseDownload(), CL_PeekSnapshot(), CL_ServerInfoPacket(), SV_ClientCommand(), SV_DemoReadClientCommand(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DemoReadConfigString(), SV_DemoReadGameCommand(), SV_DemoReadServerCommand(), and SV_DemoStartPlayback().
char* MSG_ReadStringLine (msg_t * msg)
MSG_ReadStringLine.
Parameters
[in] msg
Returns
Definition at line 803 of file msg.c.
Referenced by CL_ConnectionlessPacket(), CL_ServerStatusResponse(), and SV_ConnectionlessPacket().
void MSG_ReportChangeVectors_f (void)
Prints out a table from the current statistics for copying to code.
Definition at line 1093 of file msg.c.
Referenced by Com_Init().
void MSG_Uncompressed (msg_t * buf)
MSG_Uncompressed.
Parameters
[out] buf
Definition at line 126 of file msg.c.
Referenced by CL_WriteBinaryMessage(), and SV_WriteBinaryMessage().
void MSG_WriteAngle16 (msg_t * msg, float f)
MSG_WriteAngle16.
Parameters
[in,out] msg
[in] f
Definition at line 595 of file msg.c.
void MSG_WriteBigString (msg_t * msg, const char * s)
MSG_WriteBigString.
Parameters
[in,out] msg
[in] s
Definition at line 547 of file msg.c.
Referenced by CL_Record(), and SV_SendClientGameState().
void MSG_WriteBits (msg_t * msg, int value, int bits)
MSG_WriteBits.
Parameters
[in,out] msg
[in] value
[in] bits
Definition at line 194 of file msg.c.
Referenced by MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDeltaEntity(), MSG_WriteDeltaKey(), MSG_WriteDeltaKeyFloat(), MSG_WriteDeltaPlayerstate(), MSG_WriteDeltaSharedEntity(), MSG_WriteDeltaUsercmdKey(), MSG_WriteFloat(), MSG_WriteLong(), MSG_WriteShort(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), and SV_EmitPacketEntities().
void MSG_WriteByte (msg_t * msg, int c)
MSG_WriteByte.
Parameters
[in,out] msg
[in] c
Definition at line 432 of file msg.c.
Referenced by CL_Netchan_Transmit(), CL_Record(), CL_WritePacket(), MSG_WriteAngle(), MSG_WriteData(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), MSG_WriteDeltaSharedEntity(), SV_BadDownload(), SV_CheckFallbackURL(), SV_DemoStartRecord(), SV_DemoStopRecord(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DemoWriteAllPlayerState(), SV_DemoWriteClientCommand(), SV_DemoWriteClientConfigString(), SV_DemoWriteClientUserinfo(), SV_DemoWriteConfigString(), SV_DemoWriteFrame(), SV_DemoWriteGameCommand(), SV_DemoWriteMessage(), SV_DemoWriteServerCommand(), SV_Netchan_Transmit(), SV_SendClientGameState(), SV_SetupDownloadFile(), SV_UpdateServerCommandsToClient(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
void MSG_WriteChar (msg_t * msg, int c)
MSG_WriteChar.
Parameters
[in,out] msg
[in] c
Definition at line 415 of file msg.c.
void MSG_WriteData (msg_t * buf, const void * data, int length)
MSG_WriteData.
Parameters
[in,out] buf
[in] data
[in] length
Definition at line 450 of file msg.c.
Referenced by CL_WriteBinaryMessage(), MSG_WriteBigString(), MSG_WriteString(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_WriteBinaryMessage(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
void MSG_WriteDeltaEntity (msg_t * msg, entityState_t * from, entityState_t * to, qboolean force)
Writes part of a packetentities message, including the entity number. Can delta from either a baseline or a previous packet_entity If to is NULL, a remove entity update will be sent If force is not set, then nothing at all will be generated if the entity is identical, under the assumption that the in-order delta code will catch it.
Parameters
[out] msg
[in] from
[in] to
[in] force
Definition at line 1257 of file msg.c.
Referenced by CL_Record(), SV_DemoWriteAllEntityState(), SV_EmitPacketEntities(), and SV_SendClientGameState().
void MSG_WriteDeltaPlayerstate (msg_t * msg, struct playerState_s * from, struct playerState_s * to)
MSG_WriteDeltaPlayerstate.
Parameters
[out] msg
[in] from
[in] to
Definition at line 1992 of file msg.c.
Referenced by SV_DemoWriteAllPlayerState(), and SV_WriteSnapshotToClient().
void MSG_WriteDeltaSharedEntity (msg_t * msg, void * from, void * to, qboolean force, int number)
MSG_WriteDeltaSharedEntity.
Parameters
[out] msg
[in] from
[in] to
[in] force
[in] number
Definition at line 1652 of file msg.c.
Referenced by SV_DemoWriteAllEntityShared().
void MSG_WriteDeltaUsercmdKey (msg_t * msg, int key, usercmd_t * from, usercmd_t * to)
MSG_WriteDeltaUsercmdKey.
Parameters
[out] msg
[in] key
[in] from
[in] to
Definition at line 974 of file msg.c.
Referenced by CL_WritePacket().
void MSG_WriteFloat (msg_t * msg, float f)
MSG_WriteFloat.
Parameters
[in,out] msg
[in] f
Definition at line 492 of file msg.c.
void MSG_WriteLong (msg_t * msg, int c)
MSG_WriteLong.
Parameters
[in,out] msg
[in] c
Definition at line 482 of file msg.c.
Referenced by CL_Record(), CL_WritePacket(), MSG_WriteDeltaPlayerstate(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_BadDownload(), SV_CheckFallbackURL(), SV_DemoStartRecord(), SV_DemoWriteFrame(), SV_SendClientGameState(), SV_SendClientIdle(), SV_SendClientSnapshot(), SV_SendDownloadMessages(), SV_SetupDownloadFile(), SV_UpdateServerCommandsToClient(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
void MSG_WriteShort (msg_t * msg, int c)
MSG_WriteShort.
Parameters
[in,out] msg
[in] c
Definition at line 465 of file msg.c.
Referenced by CL_Record(), MSG_WriteAngle16(), MSG_WriteDeltaPlayerstate(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_BadDownload(), SV_CheckFallbackURL(), SV_SendClientGameState(), SV_SetupDownloadFile(), and SV_WriteDownloadToClient().
void MSG_WriteString (msg_t * msg, const char * s)
MSG_WriteString.
Parameters
[in,out] msg
[in] s
Definition at line 509 of file msg.c.
Referenced by CL_WritePacket(), SV_CheckDownloadAllowed(), SV_CheckFallbackURL(), SV_DemoStartRecord(), SV_DemoWriteClientCommand(), SV_DemoWriteClientConfigString(), SV_DemoWriteClientUserinfo(), SV_DemoWriteConfigString(), SV_DemoWriteGameCommand(), SV_DemoWriteServerCommand(), SV_SetupDownloadFile(), and SV_UpdateServerCommandsToClient().
const char* NET_AdrToString (netadr_t a)
Returns address & port.
Parameters
[in] a
Returns
Definition at line 647 of file net_ip.c.
Referenced by CL_Connect_f(), CL_ConnectionlessPacket(), CL_GetPing(), CL_GlobalServers_f(), CL_PacketEvent(), CL_RequestMotd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), Com_CheckAutoUpdate(), Com_GetAutoUpdate(), Com_UpdateInfoPacket(), LAN_GetServerAddressString(), LAN_GetServerInfo(), NET_GetPacket(), Netchan_Process(), SV_CheckDRDoS(), SV_ConnectionlessPacket(), SV_DirectConnect(), SV_GetChallenge(), SV_isClientIPValidToConnect(), SV_isValidClient(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SV_Status_f(), SV_UserinfoChanged(), SVC_BucketForAddress(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
const char* NET_AdrToStringNoPort (netadr_t a)
NET_AdrToStringNoPort.
Parameters
[in] a
Returns
Definition at line 602 of file net_ip.c.
Referenced by NET_AdrToString().
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
NET_CompareAdr.
Parameters
[in] a
[in] b
Returns
Definition at line 686 of file net_ip.c.
Referenced by CL_ConnectionlessPacket(), CL_DisconnectPacket(), CL_GetServerStatus(), CL_MotdPacket(), CL_PacketEvent(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus(), CL_ServerStatusResponse(), CL_SetServerInfoByAddress(), CL_UpdateVisiblePings_f(), Com_CheckUpdateStarted(), Com_InitUpdateDownloads(), Com_UpdateInfoPacket(), Com_UpdatePacketEvent(), LAN_AddServer(), LAN_RemoveServer(), LAN_ServerIsInFavoriteList(), SV_DirectConnect(), SV_DropClient(), SV_GetChallenge(), and SV_TempBanIsBanned().
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
Compares ip addresses without the port.
Parameters
[in] a
[in] b
Returns
Definition at line 592 of file net_ip.c.
Referenced by NET_CompareAdr(), SV_CheckDRDoS(), SV_DirectConnect(), and SV_PacketEvent().
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t * net_from, msg_t * net_message)
NET_GetLoopPacket.
Parameters
[in] sock
[out] net_from
[out] net_message
Returns
Definition at line 444 of file net_chan.c.
Referenced by Com_EventLoop().
void NET_Init (void)
NET_Init.
Definition at line 2022 of file net_ip.c.
Referenced by main().
qboolean NET_IsIPXAddress (const char * buf)
qboolean NET_IsLocalAddress (netadr_t adr)
NET_IsLocalAddress.
Parameters
[in] adr
Returns
Definition at line 717 of file net_ip.c.
Referenced by CL_Connect_f(), SV_DirectConnect(), SV_isClientIPValidToConnect(), and SV_UserinfoChanged().
qboolean NET_IsLocalAddressString (const char * address)
NET_IsLocalAddressString.
Parameters
[in] address
Returns
Definition at line 727 of file net_ip.c.
Referenced by LAN_AddServer().
void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, const char * format, int len)
Sends a data message in an out-of-band datagram (only used for "connect")
Parameters
[in] sock
[in] adr
[in] format
[in] len
Definition at line 702 of file net_chan.c.
Referenced by CL_CheckForResend().
void QDECL NET_OutOfBandPrint (netsrc_t sock, netadr_t adr, const char * format, ...)
Sends a text message in an out-of-band datagram.
Parameters
[in] sock
[in] adr
[in] format
Definition at line 675 of file net_chan.c.
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_GlobalServers_f(), CL_Ping_f(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), CL_UpdateVisiblePings_f(), Com_CheckAutoUpdate(), SV_DirectConnect(), SV_FlushRedirect(), SV_GetChallenge(), SV_isValidClient(), SV_IsValidUserinfo(), SV_MasterHeartbeat(), SVC_Info(), and SVC_Status().
void NET_Restart_f (void)
NET_Restart_f.
Definition at line 2162 of file net_ip.c.
Referenced by NET_Init().
void NET_SendPacket (netsrc_t sock, int length, const void * data, netadr_t to)
NET_SendPacket.
Parameters
[in] sock
[in] length
[in] data
[in] to
Definition at line 526 of file net_chan.c.
Referenced by CL_LocalServers_f(), CL_Rcon_f(), NET_OutOfBandData(), NET_OutOfBandPrint(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
void NET_Shutdown (void)
NET_Shutdown.
Definition at line 2046 of file net_ip.c.
Referenced by __attribute__().
void NET_Sleep (int msec)
Sleeps msec or until something happens on the network.
Parameters
[in] msec
Definition at line 2106 of file net_ip.c.
Referenced by Com_Frame().
int NET_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
Traps "localhost" for loopback, passes everything else to system.
Parameters
[in] s
[in,out] a
[in] family
Returns
0 on address not found, 1 on address found with port, 2 on address found without port.
Definition at line 733 of file net_chan.c.
Referenced by CL_Connect_f(), CL_GlobalServers_f(), CL_MapLoading(), CL_Ping_f(), CL_Rcon_f(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), Com_CheckAutoUpdate(), LAN_AddServer(), LAN_RemoveServer(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_MasterGameCompleteStatus(), and SV_MasterHeartbeat().
void Netchan_Init (int port)
Netchan_Init.
Parameters
[in] port
Definition at line 80 of file net_chan.c.
Referenced by Com_Init().
qboolean Netchan_Process (netchan_t * chan, msg_t * msg)
Msg must be large enough to hold MAX_MSGLEN, because if this is the final fragment of a multi-part message, the entire thing will be copied out.
Parameters
[in,out] chan
[in,out] msg
Returns
qfalse if the message should not be processed due to being out of order or a fragment.
Definition at line 239 of file net_chan.c.
Referenced by CL_Netchan_Process(), and SV_Netchan_Process().
void Netchan_Setup (netsrc_t sock, netchan_t * chan, netadr_t adr, int qport)
Called to open a channel to a remote system.
Parameters
[in] sock
[out] chan
[in] adr
[in] qport
Definition at line 95 of file net_chan.c.
Referenced by CL_ConnectionlessPacket(), and SV_DirectConnect().
void Netchan_Transmit (netchan_t * chan, int length, const byte * data)
Sends a message to a connection, fragmenting if necessary A 0 length will still generate a packet.
Parameters
[in,out] chan
[in] length
[in] data
Definition at line 174 of file net_chan.c.
Referenced by CL_Netchan_Transmit(), SV_Netchan_Transmit(), and SV_Netchan_TransmitNextInQueue().
void Netchan_TransmitNextFragment (netchan_t * chan)
Send one fragment of the current message.
Parameters
[in,out] chan
Definition at line 110 of file net_chan.c.
Referenced by CL_Netchan_TransmitNextFragment(), Netchan_Transmit(), and SV_Netchan_TransmitNextFragment().
void S_ClearSoundBuffer (qboolean killStreaming)
S_ClearSoundBuffer.
Parameters
[in] killStreaming
killStreaming
Definition at line 531 of file snd_main.c.
Referenced by CL_Disconnect().
void* S_Malloc (int size)
Definition at line 1276 of file common.c.
Referenced by Cmd_AddSystemCommand(), and CopyString().
void SCR_DebugGraph (float value)
SCR_DebugGraph.
Parameters
value
Definition at line 281 of file cl_scrn.c.
Referenced by CL_CreateCmd(), and CL_Frame().
void SV_Frame (int msec)
Player movement occurs as a result of packet events, which happen before SV_Frame is called.
Parameters
[in] msec
Todo:
: add mail, IRC, player info etc for both warnings
Todo:
: inspect/adjust these values and/or add cvars
Definition at line 1553 of file sv_main.c.
Referenced by CL_Connect_f(), Com_Frame(), and Com_GetAutoUpdate().
int SV_FrameMsec ()
Return time in millseconds until processing of the next server frame.
Definition at line 1519 of file sv_main.c.
Referenced by Com_Frame().
qboolean SV_GameCommand (void)
See if the current console command is claimed by the game.
Returns
Definition at line 785 of file sv_game.c.
Referenced by Cmd_ExecuteString().
void SV_Init (void)
SV_Init.
Definition at line 981 of file sv_init.c.
Referenced by Com_Init().
void SV_PacketEvent (netadr_t from, msg_t * msg)
SV_PacketEvent.
Parameters
[in] from
[in] msg
Definition at line 1256 of file sv_main.c.
Referenced by Com_RunAndTimeServerPacket().
int SV_SendQueuedPackets ()
Send download messages and queued packets in the time that we're idle, i.e. not computing a server frame or sending client snapshots.
Returns
The time in msec until we expect to be called next
Definition at line 1895 of file sv_main.c.
Referenced by Com_Frame().
void SV_Shutdown (const char * finalmsg)
Called when each game quits, before Sys_Quit or Sys_Error.
Parameters
[in] finalmsg
Definition at line 1192 of file sv_init.c.
Referenced by CIN_PlayCinematic_f(), CL_Connect_f(), Com_Error(), Com_GetAutoUpdate(), Com_Quit_f(), SV_Frame(), SV_KillServer_f(), and Sys_SigHandler().
const char* Sys_Basename (char * path)
Sys_Basename.
Parameters
path
Returns
Definition at line 245 of file sys_unix.c.
qboolean Sys_CheckCD (void)
void Sys_Chmod (const char * file, int mode)
Safe function to Chmod a file and preventing TOCTOU attacks.
Parameters
[in] file Filename
[in] mode Access Mode
Definition at line 96 of file sys_unix.c.
Referenced by Com_RunUpdateBinary().
char* Sys_ConsoleInput (void)
Handle new console input.
Definition at line 119 of file sys_main.c.
Referenced by Com_GetSystemEvent().
char* Sys_Cwd (void)
Get current working directory.
Returns
Path to current working directory
Get current working directory.
Returns
Definition at line 365 of file sys_unix.c.
Referenced by Sys_DefaultInstallPath().
char* Sys_DefaultBasePath (void)
char* Sys_DefaultHomePath (void)
Get current home path.
Returns
path to ET: Legacy directory
homepath pointing to "My Documents\\ETLegacy"
Todo:
: forcing SHGFP_TYPE_CURRENT because file creation fails
Definition at line 70 of file sys_unix.c.
Referenced by FS_Startup().
char* Sys_DefaultInstallPath (void)
Sys_DefaultInstallPath.
Returns
Definition at line 95 of file sys_main.c.
Referenced by FS_Startup().
dialogResult_t Sys_Dialog (dialogType_t type, const char * message, const char * title)
Display an OS X dialog box.
Display an OS X dialog box.
Parameters
type Dialog Type
[in] message Message to show
[in] title Message box title
Display an OS X dialog box.
Parameters
[in] type
[in] message
[in] title
Returns
Definition at line 54 of file sys_osx.m.
Referenced by Com_Init(), main(), needsOSXQuarantineFix(), and Sys_ErrorDialog().
const char* Sys_Dirname (char * path)
Sys_Dirname.
Parameters
path
Returns
Definition at line 250 of file sys_unix.c.
Referenced by main().
void Sys_DisplaySystemConsole (qboolean show)
qboolean Sys_DllExtension (const char * name)
Check if filename should be allowed to be loaded as a DLL.
Parameters
name
Definition at line 1135 of file sys_unix.c.
Referenced by FS_CheckFilenameIsMutable(), and Sys_LoadDll().
void QDECL Sys_Error (const char * error, ...)
Referenced by Com_Error(), Com_Init(), and Sys_ListFiles().
FILE* Sys_FOpen (const char * ospath, const char * mode)
Safe function to open a file and preventing TOCTOU attacks.
Parameters
[in] ospath The file path to open
[in] mode The mode used to open the file ('rb','wb','ab')
Returns
Safe function to open a file and preventing TOCTOU attacks.
Parameters
[in] ospath
[in] mode
Returns
Definition at line 261 of file sys_unix.c.
Referenced by FS_CL_ExtractFromPakFile(), FS_CopyFile(), FS_FileInPathExists(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_Unzip(), and FS_UnzipTo().
void Sys_FreeFileList (char ** list)
Sys_FreeFileList.
Parameters
[in,out] list
Definition at line 601 of file sys_unix.c.
Referenced by FS_AddGameDirectory(), FS_DeleteDir(), FS_GetModList(), and FS_ListFilteredFiles().
char* Sys_GetCurrentUser (void)
Get current user username.
Returns
username
Get current user username.
Returns
Definition at line 225 of file sys_unix.c.
Referenced by Sys_Init().
void Sys_Init (void)
Sys_Init.
Definition at line 252 of file sys_main.c.
Referenced by Com_Init().
qboolean Sys_IsLANAddress (netadr_t adr)
LAN clients will have their rate var ignored.
IPv4: A LAN client is loopback adapter (localhost/127.0.0.1), a computer of the network this computer is member of or private network from RFC1918: 10.0.0.0 - 10.255.255.255 (10/8 prefix) 172.16.0.0 - 172.31.255.255 (172.16/12 prefix) 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
IPv6: FIXME: docu
This function expects adresses of type NA_IP_4 & 6 ONLY! other types (also NA_BOT) will return qfalse
Parameters
[in] adr
Todo:
docu IPv6
Todo:
? should we check the scope_id here?
Definition at line 974 of file net_ip.c.
Referenced by CL_ReadyToSendPacket(), SV_CheckDRDoS(), SV_DirectConnect(), SV_SendClientMessages(), and SV_UserinfoChanged().
char** Sys_ListFiles (const char * directory, const char * extension, const char * filter, int * numfiles, qboolean wantsubs)
List files in directory by filter.
Parameters
[in] directory What we want to list?
[in] extension Limit files to specified extension
[in] filter Filter results
[out] numfiles Number of listed files
wantsubs Do we want to list subdirectories too?
Returns
Array of strings with files
List files in directory by filter.
Parameters
[in] directory
[in] extension
[in] filter
[out] numfiles
[in] wantsubs
Returns
Definition at line 464 of file sys_unix.c.
Referenced by FS_AddGameDirectory(), FS_DeleteDir(), FS_GetModList(), and FS_ListFilteredFiles().
qboolean Sys_LowPhysicalMemory (void)
Sys_LowPhysicalMemory.
Todo:
Returns
Definition at line 240 of file sys_unix.c.
Referenced by CL_InitCGame().
int Sys_Milliseconds (void)
Sys_Milliseconds.
Returns
Definition at line 166 of file sys_unix.c.
Referenced by CL_CgameSystemCalls(), CL_DemoCompleted(), CL_DemoRun(), CL_GenerateETKey(), CL_InitCGame(), CL_ParseDemo(), CL_ScaledMilliseconds(), CL_ServerStatus(), CL_ServerStatusResponse(), CL_UISystemCalls(), Com_Error(), Com_Frame(), Com_GetSystemEvent(), Com_ModifyMsec(), Com_QueueEvent(), Com_RunAndTimeServerPacket(), Com_TimeVal(), Com_TouchMemory(), DB_Create(), DB_Init(), DB_SaveMemDB(), FindShaderInShaderText(), FS_Unzip(), IN_Frame(), IN_WindowResize(), main(), NET_SendPacket(), Netchan_Transmit(), Netchan_TransmitNextFragment(), S_AddLoopSounds(), S_Base_StartSoundEx(), S_ChannelMalloc(), S_FreeOldestSound(), S_LoadSound(), S_Update_(), SV_Frame(), SV_GameSystemCalls(), SV_RateMsec(), SV_SendQueuedPackets(), SV_SpawnServer(), SV_Status_f(), SV_Uptime_f(), SVC_BucketForAddress(), SVC_RateLimit(), and Sys_GameLoop().
qboolean Sys_Mkdir (const char * path)
Create directory.
Parameters
[in] path Path
Return values
qfalse on failure
qtrue on success
Create directory.
Parameters
[in] path
Returns
Definition at line 349 of file sys_unix.c.
Referenced by FS_CreatePath(), and Sys_ErrorDialog().
void Sys_OpenURL (const char * url, qboolean doexit)
Open URL in system browser.
Parameters
[in] url URL to open
doexit Quit from game after opening URL
Open URL in system browser.
Parameters
[in] url
[in] doexit
Definition at line 1031 of file sys_unix.c.
Referenced by CL_OpenURL(), CL_ParseDownload(), and Com_GetAutoUpdate().
int Sys_PID (void)
Sys_PID.
Returns
PID of current process
Definition at line 1115 of file sys_unix.c.
Referenced by Com_Init().
qboolean Sys_PIDIsRunning (unsigned int pid)
Check if specified PID is running.
Parameters
pid PID to check
Return values
qfalse on failure
qtrue on success
Check if specified PID is running.
Parameters
[in] pid
Returns
Definition at line 1126 of file sys_unix.c.
void Sys_Print (const char * msg)
Sys_Print.
Parameters
msg
Definition at line 409 of file sys_main.c.
Referenced by Com_Printf(), and Sys_ErrorDialog().
void Sys_Quit (void)
Sys_Quit.
Definition at line 237 of file sys_main.c.
Referenced by Com_Quit_f().
qboolean Sys_RandomBytes (byte * string, int len)
Sys_RandomBytes.
Parameters
[out] string Place to put random string
len How much random data we need?
Return values
qfalse on failure
qtrue on success
Parameters
[in] string
[in] len
Returns
Definition at line 199 of file sys_unix.c.
Referenced by Com_RandomBytes().
void Sys_SendPacket (int length, const void * data, netadr_t to)
Sys_SendPacket.
Parameters
[in] length
[in] data
[in] to
Definition at line 873 of file net_ip.c.
Referenced by NET_SendPacket().
void Sys_SetEnv (const char * name, const char * value)
Set/Unset environment variables.
Parameters
[in] name Environment Variable
[in] value New value to set
Note
Empty value removes variable
Set/Unset environment variables.
Parameters
name
value
Definition at line 1100 of file sys_unix.c.
Referenced by CL_InitRef(), Sys_GLimpInit(), and Sys_GLimpSafeInit().
void Sys_ShowIP (void)
Sys_ShowIP.
Definition at line 1071 of file net_ip.c.
Referenced by CL_ShowIP_f(), NET_AddLocalAddress(), and NET_GetLocalAddress().
void Sys_SnapVector (float * v)
Sys_SnapVector.
Parameters
[in,out] v Vector
[in,out] v
Definition at line 186 of file sys_unix.c.
Referenced by CL_CgameSystemCalls(), and SV_GameSystemCalls().
void Sys_StartProcess (char * cmdline, qboolean doexit)
Starts process.
Parameters
[in] cmdline Execution string
doexit Quit from game after executing command
Note
might even want to add a small delay?
If !doexit then start the process ASAP, otherwise push it for execution at exit (i.e. let complete shutdown of the game and freeing of resources happen)
Starts process.
Parameters
[in] cmdline
[in] doexit
Definition at line 1012 of file sys_unix.c.
Referenced by Com_RunUpdateBinary(), and Sys_OpenURL().
qboolean Sys_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
Sys_StringToAdr.
Parameters
[in] s
[in] a
[in] family
Returns
Definition at line 469 of file net_ip.c.
Referenced by NET_StringToAdr().
qboolean Sys_WritePIDFile (void)
Writes pid to profile or to the homepath root if running a server.
Returns
qtrue if pid file successfully created otherwise qfalse if it wasn't possible to create a new pid file
Todo:
: check if we are hijacking live pid file
Definition at line 130 of file sys_main.c.
Referenced by Com_Init(), and FS_Restart().
qboolean UI_GameCommand (void)
See if the current console command is claimed by the ui.
Returns
See if the current console command is claimed by the ui.
Returns
Definition at line 1417 of file cl_ui.c.
Referenced by Cmd_ExecuteString().
void* VM_ArgPtr (intptr_t intValue)
VM_ArgPtr.
Parameters
[in] intValue
Returns
Definition at line 644 of file vm.c.
intptr_t QDECL VM_CallFunc (vm_t * vm, int callNum, ...)
VM_CallFunc.
Upon a system call, the stack will look like:
sp+32 parm1 sp+28 parm0 sp+24 return value sp+20 return address sp+16 local1 sp+14 local0 sp+12 arg1 sp+8 arg0 sp+4 return stack sp return address
An interpreted function will immediately execute an OP_ENTER instruction, which will subtract space for locals from sp
Parameters
[in] vm
[in] callNum
Returns
Definition at line 717 of file vm.c.
void VM_Clear (void)
VM_Clear.
Definition at line 623 of file vm.c.
Referenced by Hunk_Clear().
vm_t* VM_Create (const char * module, qboolean extract, intptr_t(*)(intptr_t *) systemCalls, vmInterpret_t interpret)
If image ends in .qvm it will be interpreted, otherwise it will attempt to load as a system dll.
Parameters
[in] module
[in] extract
systemCalls
[in] interpret
Returns
Definition at line 453 of file vm.c.
Referenced by CL_InitCGame(), CL_InitUI(), SV_InitGameProgs(), and VM_Restart().
void VM_Debug (int level)
VM_Debug.
Parameters
[in] level
Definition at line 77 of file vm.c.
Referenced by CL_CGameRendering(), and VM_CallInterpreted().
void* VM_ExplicitArgPtr (vm_t * vm, intptr_t intValue)
VM_ExplicitArgPtr.
Parameters
[in] vm
[in] intValue
Returns
Definition at line 672 of file vm.c.
Referenced by SV_DirectConnect(), SV_MapRestart_f(), and SV_SpawnServer().
void VM_Free (vm_t * vm)
VM_Free.
Parameters
[in,out] vm
Definition at line 593 of file vm.c.
Referenced by CL_ShutdownCGame(), CL_ShutdownUI(), SV_ShutdownGameProgs(), VM_Create(), and VM_Restart().
void VM_Init (void)
VM_Init.
Todo:
: doesn't print anything with +set developer 1
Definition at line 85 of file vm.c.
Referenced by Com_Init().
vm_t* VM_Restart (vm_t * vm)
Reload the data, but leave everything else in place This allows a server to do a map_restart without changing memory allocation.
Parameters
[in,out] vm
Returns
Todo:
: Division of result of sizeof() on pointer type. This seems suspect.
Definition at line 368 of file vm.c.
Referenced by SV_RestartGameProgs().
void Z_Free (void * ptr)
Z_Free.
Parameters
[out] ptr
Definition at line 1010 of file common.c.
Referenced by BotImport_FreeMemory(), CL_CloseAVI(), CL_InitRef(), CL_SetExpectedHunkUsage(), CL_UpdateLevelHunkUsage(), Cmd_RemoveCommand(), Com_EventLoop(), Com_PushEvent(), Com_QueueEvent(), Cvar_Get(), Cvar_Set2(), Cvar_SetCheatState(), Cvar_SetDescription(), Cvar_Unset(), Field_Paste(), FreeWinding(), FS_CL_ExtractFromPakFile(), FS_FreeFileList(), FS_FreePak(), FS_LoadZipFile(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_Shutdown(), FS_SortFileList(), GetClipboardData(), HT_DeleteItem(), HT_Destroy(), HT_PutItem(), Hunk_FreeTempMemory(), Key_SetBinding(), NET_SendPacket(), S_CodecUtilClose(), SV_ClearServer(), SV_CloseDownload(), SV_DemoChangeMaxClients(), SV_Netchan_ClearQueue(), SV_Netchan_TransmitNextInQueue(), SV_SetConfigstring(), SV_SetConfigstringNoUpdate(), SV_SetExpectedHunkUsage(), Sys_ConcatenateFileLists(), Sys_FreeFileList(), VM_Free(), VM_VmProfile_f(), and Z_FreeTags().
void Z_FreeTags (int tag)
Z_FreeTags.
Parameters
[in] tag
Definition at line 1091 of file common.c.
Referenced by BotImport_FreeZoneMemory(), and CL_RefTagFree().
void Z_LogHeap (void)
Z_LogHeap.
Definition at line 1374 of file common.c.
Referenced by Com_InitHunkMemory(), SV_SpawnServer(), and Z_TagMalloc().
void* Z_Malloc (int size)
Definition at line 1245 of file common.c.
Referenced by _HT_CreateEntry(), AllocWinding(), CL_OpenAVIForWriting(), CL_SetExpectedHunkUsage(), CL_UpdateLevelHunkUsage(), Com_GetRealEvent(), Com_GetSystemEvent(), FS_AddGameDirectory(), FS_CL_ExtractFromPakFile(), FS_ListFilteredFiles(), FS_LoadZipFile(), FS_SortFileList(), HT_Create(), HT_GetItem(), Hunk_AllocateTempMemory(), IN_GetClipboardData(), NET_SendPacket(), S_CodecUtilOpen(), SV_DemoChangeMaxClients(), SV_Netchan_Transmit(), SV_SetExpectedHunkUsage(), SV_WriteDownloadToClient(), Sys_ConcatenateFileLists(), Sys_ListFiles(), and VM_VmProfile_f().
void* Z_TagMalloc (int size, int tag)
Definition at line 1136 of file common.c.
Referenced by BotImport_GetMemory(), CL_RefMalloc(), S_Malloc(), and Z_Malloc().
Variable Documentation
autoupdate_t autoupdate
Definition at line 58 of file update.c.
Referenced by CL_ConnectionlessPacket(), CL_MotdPacket(), CL_RequestMasterData(), CL_RequestMotd(), and Com_WWWDownload().
int cl_connectedToPureServer
Definition at line 587 of file cl_parse.c.
Referenced by CL_Disconnect(), CL_ParseDemo(), CL_ParseGamestate(), and CL_SystemInfoChanged().
cvar_t* cl_packetdelay
Definition at line 112 of file cl_main.c.
cvar_t* cl_paused
Definition at line 123 of file common.c.
Referenced by CL_CheckTimeout(), CL_CheckUserinfo(), CL_SendCmd(), CL_SetCGameTime(), and SV_CheckPaused().
huffman_t clientHuffTables
cvar_t* com_ansiColor
Definition at line 90 of file common.c.
Referenced by CON_Print().
cvar_t* com_buildScript
Definition at line 114 of file common.c.
cvar_t* com_cl_running
Definition at line 110 of file common.c.
Referenced by CL_Disconnect(), CL_DoPurgeCache(), CL_Frame(), CL_MapLoading(), CL_StartHunkUsers(), Cmd_ExecuteString(), Con_Close(), and SV_ClientCommand().
cvar_t* com_crashed
Definition at line 92 of file common.c.
Referenced by Cvar_Set2(), and Cvar_Set_f().
cvar_t* com_dedicated
Definition at line 102 of file common.c.
Referenced by main(), SV_AddOperatorCommands(), SV_Frame(), SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), SV_SendServerCommand(), SV_SetNumSnapshotEntities(), and SV_UserinfoChanged().
cvar_t* com_developer
Definition at line 101 of file common.c.
Referenced by CL_ConnectionlessPacket(), CL_PacketEvent(), CL_ServerInfoPacket(), Con_Close(), S_WAV_CodecLoad(), SV_ConnectionlessPacket(), SV_DirectConnect(), SV_isValidClient(), and VM_LoadSymbols().
cvar_t* com_downloadURL
Definition at line 151 of file common.c.
Referenced by Com_Download_f().
qboolean com_errorEntered
Definition at line 167 of file common.c.
Referenced by Com_Error(), Com_Quit_f(), Cvar_Get(), SV_Shutdown(), and SV_SpawnServer().
int com_expectedhunkusage
Definition at line 164 of file common.c.
Referenced by CL_SetExpectedHunkUsage(), Com_GetHunkInfo(), and SV_SetExpectedHunkUsage().
int com_frameTime
Definition at line 162 of file common.c.
Referenced by CL_CreateNewCommands(), CL_KeyMove(), CL_KeyState(), Com_Frame(), Com_Init(), Com_TimeVal(), SV_MapRestart_f(), and SV_SpawnServer().
int com_hunkusedvalue
Definition at line 165 of file common.c.
Referenced by Com_GetHunkInfo(), Com_Init(), Hunk_Alloc(), and Hunk_Clear().
cvar_t* com_ignorecrash
Definition at line 95 of file common.c.
cvar_t* com_journal
Definition at line 106 of file common.c.
Referenced by FS_ReadFile().
fileHandle_t com_journalDataFile
Definition at line 88 of file common.c.
Referenced by Com_InitJournaling(), and FS_ReadFile().
fileHandle_t com_journalFile
Definition at line 87 of file common.c.
Referenced by Com_GetRealEvent(), Com_InitJournaling(), and Com_Shutdown().
cvar_t* com_minimized
Definition at line 119 of file common.c.
Referenced by IN_Frame(), and IN_ProcessEvents().
cvar_t* com_motd
Definition at line 128 of file common.c.
Referenced by CL_RequestMotd().
cvar_t* com_motdString
Definition at line 129 of file common.c.
cvar_t* com_pid
Definition at line 96 of file common.c.
Referenced by Script_CheckProfile(), Script_WriteProfile(), and Sys_WritePIDFile().
cvar_t* com_pidfile
Definition at line 97 of file common.c.
Referenced by FS_Restart(), and Sys_WritePIDFile().
cvar_t* com_speeds
Definition at line 100 of file common.c.
Referenced by SCR_UpdateScreen(), SV_Frame(), and Sys_GameLoop().
cvar_t* com_sv_running
Definition at line 109 of file common.c.
Referenced by CL_CM_LoadMap(), CL_Connect_f(), CL_FlushMemory(), CL_Frame(), CL_GetServerCommand(), CL_SendCmd(), CL_SetCGameTime(), CL_Vid_Restart_f(), Cmd_ExecuteString(), Com_GetAutoUpdate(), NET_Event(), SV_ConSay_f(), SV_Demo_Record_f(), SV_DemoStartPlayback(), SV_DumpUser_f(), SV_Frame(), SV_GetPlayerByName(), SV_MapRestart_f(), SV_Serverinfo_f(), SV_Shutdown(), and SV_Status_f().
cvar_t* com_timescale
Definition at line 103 of file common.c.
Referenced by CL_AdjustTimeDelta(), CL_DemoRun(), CL_Frame(), CL_ScaledMilliseconds(), SV_DemoReadFrame(), SV_RateMsec(), and SV_SendClientMessages().
cvar_t* com_unfocused
Definition at line 118 of file common.c.
Referenced by IN_Frame().
cvar_t* com_updateavailable
Definition at line 130 of file common.c.
Referenced by CL_Init(), Com_CheckUpdateStarted(), Com_GetAutoUpdate(), and Com_UpdateInfoPacket().
cvar_t* com_updatefiles
Definition at line 132 of file common.c.
Referenced by CL_Init(), Com_CheckUpdateDownloads(), Com_GetAutoUpdate(), and Com_InitUpdateDownloads().
cvar_t* com_updatemessage
Definition at line 131 of file common.c.
Referenced by Com_UpdateInfoPacket().
cvar_t* com_version
Definition at line 113 of file common.c.
cvar_t* com_viewlog
Definition at line 99 of file common.c.
Referenced by main().
cvar_t* com_watchdog
cvar_t* com_watchdog_cmd
int cvar_modifiedFlags
Definition at line 41 of file cvar.c.
Referenced by CL_CheckForResend(), CL_CheckUserinfo(), Com_Init(), Com_WriteConfiguration(), Cvar_Get(), Cvar_Set2(), Cvar_Set_f(), Cvar_Unset(), Key_SetBinding(), SV_Frame(), and SV_SpawnServer().
int demo_protocols[]
Maintain a list of compatible protocols for demo playing.
Note
That stuff only works with two digits protocols
Definition at line 62 of file common.c.
Referenced by CL_PlayDemo_f(), CL_WalkDemoExt(), and FS_IsDemoExt().
qboolean doTranslateMod
Definition at line 68 of file i18n_main.cpp.
Referenced by FS_Startup(), and I18N_TranslateMod().
modHash modHashes
Definition at line 4693 of file files.c.
cvar_t* sv_packetdelay
Definition at line 126 of file common.c.
cvar_t* sv_paused
Definition at line 124 of file common.c.
Referenced by CL_CheckTimeout(), CL_SendCmd(), CL_SetCGameTime(), and SV_CheckPaused().
int time_backend
Definition at line 160 of file common.c.
Referenced by Com_Frame(), and SCR_UpdateScreen().
int time_frontend
Definition at line 159 of file common.c.
Referenced by Com_Frame(), and SCR_UpdateScreen().
int time_game
Definition at line 158 of file common.c.
Referenced by Com_Frame(), and SV_Frame().
const char* vmStrs[MAX_VM]
Definition at line 49 of file vm.c.