ET: Legacy: src/sdl/sdl_glimp.c File Reference
sdl_glimp.c File Reference
#include "sdl_defs.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "../sys/sys_local.h"
#include "../client/client.h"
#include "sdl_icon.h"
#include "sdl_splash.h"
Data Structures
struct vidmode_s
Macros
#define R_MODE_FALLBACK 3
Typedefs
typedef struct vidmode_s vidmode_t
Enumerations
enum rserr_t {
RSERR_OK, RSERR_INVALID_FULLSCREEN, RSERR_INVALID_MODE, RSERR_OLD_GL,
RSERR_UNKNOWN
}
Functions
void * GLimp_MainWindow (void)
GLimp_MainWindow.
void GLimp_Minimize (void)
Minimize the game so that user is back at the desktop.
qboolean GLimp_GetModeInfo (int *width, int *height, float *windowAspect, int mode)
GLimp_GetModeInfo.
void GLimp_ModeList_f (void)
Prints hardcoded screen resolutions.
static void GLimp_InitCvars (void)
GLimp_InitCvars.
void GLimp_Shutdown (void)
GLimp_Shutdown.
static int GLimp_CompareModes (const void *a, const void *b)
GLimp_CompareModes.
static void GLimp_DetectAvailableModes (void)
GLimp_DetectAvailableModes.
static int GLimp_SetMode (glconfig_t *glConfig, int mode, qboolean fullscreen, qboolean noborder, windowContext_t *context)
GLimp_SetMode.
static qboolean GLimp_StartDriverAndSetMode (glconfig_t *glConfig, int mode, qboolean fullscreen, qboolean noborder, windowContext_t *context)
GLimp_StartDriverAndSetMode.
void GLimp_Splash (glconfig_t *glConfig)
GLimp_Splash.
void GLimp_Init (glconfig_t *glConfig, windowContext_t *context)
This routine is responsible for initializing the OS specific portions of OpenGL.
void GLimp_EndFrame (void)
Responsible for doing a swapbuffers.
void GLimp_SetGamma (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
GLimp_SetGamma.
Variables
SDL_Window * main_window = NULL
static SDL_Renderer * main_renderer = NULL
static SDL_GLContext SDL_glContext = NULL
static float displayAspect = 0.f
cvar_t * r_allowSoftwareGL
cvar_t * r_allowResize
cvar_t * r_fullscreen = 0
cvar_t * r_noBorder
cvar_t * r_centerWindow
cvar_t * r_customwidth
cvar_t * r_customheight
cvar_t * r_swapInterval
cvar_t * r_mode
cvar_t * r_customaspect
cvar_t * r_displayRefresh
cvar_t * r_stencilbits
cvar_t * r_depthbits
cvar_t * r_colorbits
cvar_t * r_ignorehwgamma
cvar_t * r_ext_multisample
vidmode_t glimp_vidModes []
static int s_numVidModes = ARRAY_LEN(glimp_vidModes)
Macro Definition Documentation
#define R_MODE_FALLBACK 3
Definition at line 827 of file sdl_glimp.c.
Referenced by GLimp_Init().
Typedef Documentation
typedef struct vidmode_s vidmode_t
Enumeration Type Documentation
enum rserr_t
Enumerator
RSERR_OK
RSERR_INVALID_FULLSCREEN
RSERR_INVALID_MODE
RSERR_OLD_GL
RSERR_UNKNOWN
Definition at line 82 of file sdl_glimp.c.
Function Documentation
static int GLimp_CompareModes (const void * a, const void * b) static
GLimp_CompareModes.
Parameters
[in] a
[in] b
Returns
Definition at line 272 of file sdl_glimp.c.
Referenced by GLimp_DetectAvailableModes().
static void GLimp_DetectAvailableModes (void) static
GLimp_DetectAvailableModes.
Definition at line 302 of file sdl_glimp.c.
Referenced by GLimp_SetMode().
void GLimp_EndFrame (void)
Responsible for doing a swapbuffers.
Todo:
: remove this nonesense
Definition at line 948 of file sdl_glimp.c.
Referenced by CL_InitRef().
qboolean GLimp_GetModeInfo (int * width, int * height, float * windowAspect, int mode)
GLimp_GetModeInfo.
Parameters
[in,out] width
[in,out] height
[out] windowAspect
[in] mode
Returns
Definition at line 152 of file sdl_glimp.c.
Referenced by GLimp_SetMode().
void GLimp_Init (glconfig_t * glConfig, windowContext_t * context)
This routine is responsible for initializing the OS specific portions of OpenGL.
Parameters
[in,out] glConfig
[in] context
Definition at line 877 of file sdl_glimp.c.
Referenced by CL_InitRef().
static void GLimp_InitCvars (void) static
GLimp_InitCvars.
Definition at line 210 of file sdl_glimp.c.
Referenced by GLimp_Init().
void* GLimp_MainWindow (void)
GLimp_MainWindow.
Returns
Definition at line 131 of file sdl_glimp.c.
Referenced by IN_Init().
void GLimp_Minimize (void)
Minimize the game so that user is back at the desktop.
Definition at line 139 of file sdl_glimp.c.
Referenced by GLimp_InitCvars().
void GLimp_ModeList_f (void)
Prints hardcoded screen resolutions.
See also
r_availableModes for supported resolutions
Definition at line 190 of file sdl_glimp.c.
Referenced by GLimp_InitCvars().
void GLimp_SetGamma (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
GLimp_SetGamma.
Parameters
[in] red
[in] green
[in] blue
Definition at line 1020 of file sdl_glimp.c.
Referenced by CL_InitRef().
static int GLimp_SetMode (glconfig_t * glConfig, int mode, qboolean fullscreen, qboolean noborder, windowContext_t * context) static
GLimp_SetMode.
Parameters
[in,out] glConfig
[in] mode
[in] fullscreen
[in] noborder
[in] context
Returns
Definition at line 410 of file sdl_glimp.c.
Referenced by GLimp_StartDriverAndSetMode().
void GLimp_Shutdown (void)
GLimp_Shutdown.
Definition at line 247 of file sdl_glimp.c.
Referenced by CL_InitRef().
void GLimp_Splash (glconfig_t * glConfig)
GLimp_Splash.
Parameters
[in] glConfig
Returns
Definition at line 834 of file sdl_glimp.c.
Referenced by GLimp_Init().
static qboolean GLimp_StartDriverAndSetMode (glconfig_t * glConfig, int mode, qboolean fullscreen, qboolean noborder, windowContext_t * context) static
GLimp_StartDriverAndSetMode.
Parameters
[in] glConfig
[in] mode
[in] fullscreen
[in] noborder
[in] context
Returns
Definition at line 782 of file sdl_glimp.c.
Referenced by GLimp_Init().
Variable Documentation
float displayAspect = 0.f static
Definition at line 59 of file sdl_glimp.c.
Referenced by GLimp_CompareModes(), and GLimp_SetMode().
vidmode_t glimp_vidModes[]
Initial value:
=
{
    { "Mode  0: 320x240",           320,  240,  1 },
    { "Mode  1: 400x300",           400,  300,  1 },
    { "Mode  2: 512x384",           512,  384,  1 },
    { "Mode  3: 640x480",           640,  480,  1 },
    { "Mode  4: 800x600",           800,  600,  1 },
    { "Mode  5: 960x720",           960,  720,  1 },
    { "Mode  6: 1024x768",          1024, 768,  1 },
    { "Mode  7: 1152x864",          1152, 864,  1 },
    { "Mode  8: 1280x1024",         1280, 1024, 1 },
    { "Mode  9: 1600x1200",         1600, 1200, 1 },
    { "Mode 10: 2048x1536",         2048, 1536, 1 },
    { "Mode 11: 856x480 (16:9)",    856,  480,  1 },
    { "Mode 12: 1366x768 (16:9)",   1366, 768,  1 },
    { "Mode 13: 1440x900 (16:10)",  1440, 900,  1 },
    { "Mode 14: 1680x1050 (16:10)", 1680, 1050, 1 },
    { "Mode 15: 1600x1200",         1600, 1200, 1 },
    { "Mode 16: 1920x1080 (16:9)",  1920, 1080, 1 },
    { "Mode 17: 1920x1200 (16:10)", 1920, 1200, 1 },
    { "Mode 18: 2560x1440 (16:9)",  2560, 1440, 1 },
    { "Mode 19: 2560x1600 (16:10)", 2560, 1600, 1 },
    { "Mode 20: 3840x2160 (16:9)",  3840, 2160, 1 },
}
Definition at line 101 of file sdl_glimp.c.
SDL_Renderer* main_renderer = NULL static
Definition at line 57 of file sdl_glimp.c.
Referenced by GLimp_Shutdown().
SDL_Window* main_window = NULL
Definition at line 56 of file sdl_glimp.c.
Referenced by GLimp_DetectAvailableModes(), GLimp_EndFrame(), GLimp_Init(), GLimp_MainWindow(), GLimp_Minimize(), GLimp_SetGamma(), GLimp_SetMode(), GLimp_Shutdown(), and GLimp_Splash().
cvar_t* r_allowResize
Definition at line 62 of file sdl_glimp.c.
cvar_t* r_allowSoftwareGL
Definition at line 61 of file sdl_glimp.c.
cvar_t* r_centerWindow
Definition at line 67 of file sdl_glimp.c.
cvar_t* r_colorbits
Definition at line 78 of file sdl_glimp.c.
Referenced by Script_ConditionalScript().
cvar_t* r_customaspect
Definition at line 72 of file sdl_glimp.c.
cvar_t* r_customheight
Definition at line 69 of file sdl_glimp.c.
cvar_t* r_customwidth
Definition at line 68 of file sdl_glimp.c.
cvar_t* r_depthbits
Definition at line 77 of file sdl_glimp.c.
Referenced by Script_ConditionalScript().
cvar_t* r_displayRefresh
Definition at line 73 of file sdl_glimp.c.
cvar_t* r_ext_multisample
Definition at line 80 of file sdl_glimp.c.
Referenced by Script_ConditionalScript().
cvar_t* r_fullscreen = 0
Definition at line 65 of file sdl_glimp.c.
Referenced by Script_ConditionalScript(), and UI_RunMenuScript().
cvar_t* r_ignorehwgamma
Definition at line 79 of file sdl_glimp.c.
cvar_t* r_mode
Definition at line 71 of file sdl_glimp.c.
Referenced by Script_ConditionalScript(), and UI_RunMenuScript().
cvar_t* r_noBorder
Definition at line 66 of file sdl_glimp.c.
cvar_t* r_stencilbits
Definition at line 76 of file sdl_glimp.c.
cvar_t* r_swapInterval
Definition at line 70 of file sdl_glimp.c.
int s_numVidModes = ARRAY_LEN(glimp_vidModes) static
Definition at line 125 of file sdl_glimp.c.
Referenced by GLimp_GetModeInfo(), and GLimp_ModeList_f().
SDL_GLContext SDL_glContext = NULL static
Definition at line 58 of file sdl_glimp.c.
Referenced by GLimp_SetMode().