ET: Legacy: src/server/server.h File Reference
server.h File Reference
Primary header for server.
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "../game/g_public.h"
#include "../game/bg_public.h"
Data Structures
struct svEntity_s
struct server_t
struct clientSnapshot_t
struct netchan_buffer_s
struct client_s
struct svstats_t
struct challenge_t
struct receipt_t
struct tempBan_s
struct serverStatic_t
This structure will be cleared only when the game dll changes.
struct leakyBucket_s
Macros
#define PERS_SCORE 0
!!! MUST NOT CHANGE, SERVER AND GAME BOTH REFERENCE !!!
#define SVA_MASTER 0x0001
1 - master server
#define SVA_TRACKER 0x0002
2 - tracker
#define SVP_IOQ3 0x0001
1 - ioQuake3 way
#define SVP_OWOLF 0x0002
2 - OpenWolf way
#define SVP_CONSOLE 0x0004
4 - console print
#define MAX_ENT_CLUSTERS 16
#define MAX_BPS_WINDOW 20
net debugging
#define STATFRAMES 100
5 seconds - assumed we run 20 fps
#define MAX_CHALLENGES 2048
Made large to prevent a DoS attack that could cycle all of them out before legitimate users connected.
#define MAX_INFO_RECEIPTS 48
the maximum number of getstatus+getinfo responses that we send in a two second time period.
#define MAX_TEMPBAN_ADDRESSES MAX_CLIENTS
#define SERVER_PERFORMANCECOUNTER_FRAMES 600
#define SERVER_PERFORMANCECOUNTER_SAMPLES 6
#define MAX_BUCKETS 16384
This is deliberately quite large to make it more of an effort to DoS.
#define MAX_HASHES 1024
#define SV_WriteAttackLogD(x)
#define DLNOTIFY_REDIRECT 0x00000001
"Redirecting client ..."
#define DLNOTIFY_BEGIN 0x00000002
"clientDownload: 4 : beginning ..."
#define DLNOTIFY_ALL (DLNOTIFY_REDIRECT | DLNOTIFY_BEGIN)
Typedefs
typedef struct svEntity_s svEntity_t
typedef struct netchan_buffer_s netchan_buffer_t
typedef struct client_s client_t
typedef struct tempBan_s tempBan_t
typedef struct leakyBucket_s leakyBucket_t
Enumerations
enum serverState_t { SS_DEAD, SS_LOADING, SS_GAME }
enum clientState_t {
CS_FREE = 0, CS_ZOMBIE, CS_CONNECTED, CS_PRIMED,
CS_ACTIVE
}
Functions
void SV_DemoAutoDemoRecord (void)
Generates a meaningful demo filename and automatically starts the demo recording.
void SV_DemoRestartPlayback (void)
Just issue again the demo_play command along with the demo filename (used when the system will automatically restart the server for special cvars values to be set up, eg: sv_maxclients, fs_game, g_gametype, etc..)
void SV_DemoReadFrame (void)
Play a frame from the demo file.
void SV_DemoWriteFrame (void)
Record all the entities (gentities fields) and players (player_t fields) at the end of every frame (this is the only write function to be called in every frame for sure)
qboolean SV_DemoClientCommandCapture (client_t *client, const char *msg)
SV_DemoClientCommandCapture.
void SV_DemoWriteServerCommand (const char *cmd)
Write a server command to the demo file.
void SV_DemoWriteGameCommand (int clientNum, const char *cmd)
Write a game command to the demo file.
void SV_DemoWriteConfigString (int cs_index, const char *cs_string)
Write a configstring to the demo file.
void SV_DemoWriteClientUserinfo (client_t *client, const char *userinfo)
Write a client userinfo to the demo file (client_t fields can almost all be filled from the userinfo string)
qboolean SV_CheckLastCmd (const char *cmd, qboolean onlyStore)
Check and store the last command and compare it with the current one, to avoid duplicates. If onlyStore is true, it will only store the new cmd, without checking.
void SV_DemoStopAll (void)
SV_DemoStopAll.
void SV_DemoInit (void)
SV_DemoInit.
void SV_DemoShutdown (void)
SV_DemoShutdown.
void SV_GentityUpdateHealthField (sharedEntity_t *gent, playerState_t *player)
Update the value of the gentity_t->health field with playerState_t->stats[STAT_HEALTH] for a given player.
void SV_FinalCommand (const char *cmd, qboolean disconnect)
added disconnect flag so map changes can use this function as well
void QDECL SV_SendServerCommand (client_t *cl, const char *fmt,...) __attribute__((format(printf
void QDECL void SV_AddOperatorCommands (void)
SV_AddOperatorCommands.
void SV_RemoveOperatorCommands (void)
SV_RemoveOperatorCommands.
void SV_MasterHeartbeat (const char *msg)
Send a message to the masters every few minutes to let it know we are alive, and log information.
void SV_MasterShutdown (void)
Informs all masters that this server is going down.
void SV_MasterGameCompleteStatus (void)
Sends gameCompleteStatus messages to all master servers.
int SV_RateMsec (client_t *client)
Return the number of msec until another message can be sent to a client based on its rate settings.
qboolean SVC_RateLimit (leakyBucket_t *bucket, int burst, int period)
SVC_RateLimit.
qboolean SVC_RateLimitAddress (netadr_t from, int burst, int period)
Rate limit for a particular address.
void SV_SetConfigstringNoUpdate (int index, const char *val)
SV_SetConfigstringNoUpdate.
void SV_SetConfigstring (int index, const char *val)
SV_SetConfigstring.
void SV_UpdateConfigStrings (void)
Updates the configstring.
void SV_GetConfigstring (int index, char *buffer, unsigned int bufferSize)
SV_GetConfigstring.
void SV_SetUserinfo (int index, const char *val)
SV_SetUserinfo.
void SV_GetUserinfo (int index, char *buffer, unsigned int bufferSize)
SV_GetUserinfo.
void SV_ChangeMaxClients (void)
SV_ChangeMaxClients.
void SV_SpawnServer (const char *server)
Change the server to a new map, taking all connected clients along with it. This is NOT called for map_restart.
void SV_WriteAttackLog (const char *log)
SV_WriteAttackLog.
void SV_GetChallenge (netadr_t from)
A "getchallenge" OOB command has been received.
void SV_DirectConnect (netadr_t from)
A "connect" OOB command has been received.
void SV_ExecuteClientMessage (client_t *cl, msg_t *msg)
SV_ExecuteClientMessage.
void SV_UserinfoChanged (client_t *cl)
Pull specific info from a newly changed userinfo string into a more C friendly form.
void SV_UpdateUserinfo_f (client_t *cl)
SV_UpdateUserinfo_f.
void SV_ClientEnterWorld (client_t *client, usercmd_t *cmd)
SV_ClientEnterWorld.
void SV_DropClient (client_t *drop, const char *reason)
Called when the player is totally leaving the server, either willingly or unwillingly. This is NOT called if the entire server is quiting or crashing – SV_FinalCommand() will handle that.
void SV_ExecuteClientCommand (client_t *cl, const char *s, qboolean clientOK, qboolean premaprestart)
Also called by bot code.
void SV_ClientThink (client_t *cl, usercmd_t *cmd)
Also called by bot code.
int SV_SendDownloadMessages (void)
Send one round of download messages to all clients.
int SV_SendQueuedMessages (void)
Send one round of fragments, or queued messages to all clients that have data pending.
void SV_Heartbeat_f (void)
Also called by SV_DropClient, SV_DirectConnect, and SV_SpawnServer.
qboolean SV_TempBanIsBanned (netadr_t address)
SV_TempBanIsBanned.
void SV_TempBanNetAddress (netadr_t address, int length)
SV_TempBanNetAddress.
void SV_UptimeReset (void)
SV_UptimeReset.
void SV_AddServerCommand (client_t *client, const char *cmd)
The given command will be transmitted to the client, and is guaranteed to not have future snapshot_t executed before it is executed.
void SV_UpdateServerCommandsToClient (client_t *client, msg_t *msg)
(re)send all server commands the client hasn't acknowledged yet
void SV_SendMessageToClient (msg_t *msg, client_t *client)
Called by SV_SendClientSnapshot and SV_SendClientGameState.
void SV_SendClientMessages (void)
SV_SendClientMessages.
void SV_SendClientSnapshot (client_t *client)
SV_SendClientSnapshot.
void SV_CheckClientUserinfoTimer (void)
SV_CheckClientUserinfoTimer.
void SV_SendClientIdle (client_t *client)
There is no need to send full snapshots to clients who are loading a map. So we send them "idle" packets with the bare minimum required to keep them on the server.
int SV_NumForGentity (sharedEntity_t *ent)
SV_NumForGentity.
sharedEntity_t * SV_GentityNum (int num)
SV_GentityNum.
playerState_t * SV_GameClientNum (int num)
SV_GameClientNum.
svEntity_t * SV_SvEntityForGentity (sharedEntity_t *gEnt)
SV_SvEntityForGentity.
sharedEntity_t * SV_GEntityForSvEntity (svEntity_t *svEnt)
SV_GEntityForSvEntity.
void SV_InitGameProgs (void)
Called on a normal map change, not on a map_restart.
void SV_ShutdownGameProgs (void)
Called every time a map changes.
void SV_RestartGameProgs (void)
Called on a map_restart, but not on a normal map change.
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
Also checks portalareas so that doors block sight.
qboolean SV_GetTag (int clientNum, int tagFileNumber, char *tagname, orientation_t *orientation)
SV_GetTag.
int SV_LoadTag (const char *mod_name)
SV_LoadTag.
void SV_GameSendServerCommand (int clientNum, const char *text)
Sends a command string to a client.
void SV_GameBinaryMessageReceived (int cno, const char *buf, int buflen, int commandTime)
SV_GameBinaryMessageReceived.
int SV_BotAllocateClient (int clientNum)
Attempts to add a bot to the game First player slot is reserved and cannot be used by a bot.
void SV_BotFreeClient (int clientNum)
SV_BotFreeClient.
int SV_BotGetConsoleMessage (int client, char *buf, size_t size)
SV_BotGetConsoleMessage.
int BotImport_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
BotImport_DebugPolygonCreate.
void BotImport_DebugPolygonDelete (int id)
BotImport_DebugPolygonDelete.
void SV_ClearWorld (void)
SV_ClearWorld.
void SV_UnlinkEntity (sharedEntity_t *gEnt)
SV_UnlinkEntity.
void SV_LinkEntity (sharedEntity_t *gEnt)
SV_LinkEntity.
clipHandle_t SV_ClipHandleForEntity (const sharedEntity_t *ent)
Return a headnode that can be used for testing or clipping to a given entity.
void SV_SectorList_f (void)
SV_SectorList_f.
int SV_AreaEntities (const vec3_t mins, const vec3_t maxs, int *entityList, int maxcount)
SV_AreaEntities.
int SV_PointContents (const vec3_t p, int passEntityNum)
SV_PointContents.
void SV_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, qboolean capsule)
Moves the given mins/maxs volume through the world from start to end. passEntityNum and entities owned by passEntityNum are explicitly not checked.
void SV_ClipToEntity (trace_t *trace, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int entityNum, int contentmask, qboolean capsule)
SV_ClipToEntity.
void SV_Netchan_Transmit (client_t *client, msg_t *msg)
SV_Netchan_Transmit.
void SV_Netchan_ClearQueue (client_t *client)
SV_Netchan_ClearQueue.
int SV_Netchan_TransmitNextFragment (client_t *client)
SV_Netchan_TransmitNextFragment.
qboolean SV_Netchan_Process (client_t *client, msg_t *msg)
SV_Netchan_Process.
Variables
serverStatic_t svs
persistant server info across maps
server_t sv
cleared each map
vm_t * gvm
game virtual machine
cvar_t * sv_fps
cvar_t * sv_timeout
cvar_t * sv_zombietime
cvar_t * sv_rconPassword
cvar_t * sv_privatePassword
cvar_t * sv_allowDownload
cvar_t * sv_friendlyFire
cvar_t * sv_maxlives
cvar_t * sv_maxclients
cvar_t * sv_needpass
cvar_t * sv_democlients
cvar_t * sv_privateClients
cvar_t * sv_hostname
cvar_t * sv_master [MAX_MASTER_SERVERS]
cvar_t * sv_reconnectlimit
cvar_t * sv_tempbanmessage
cvar_t * sv_padPackets
cvar_t * sv_killserver
cvar_t * sv_mapname
cvar_t * sv_mapChecksum
cvar_t * sv_serverid
cvar_t * sv_minRate
cvar_t * sv_maxRate
cvar_t * sv_minPing
cvar_t * sv_maxPing
cvar_t * sv_gametype
cvar_t * sv_pure
cvar_t * sv_floodProtect
cvar_t * sv_lanForceRate
cvar_t * sv_onlyVisibleClients
cvar_t * sv_showAverageBPS
net debugging
cvar_t * sv_dl_timeout
autodl
cvar_t * sv_wwwDownload
general flag to enable/disable www download redirects
cvar_t * sv_wwwBaseURL
cvar_t * sv_wwwDlDisconnected
cvar_t * sv_wwwFallbackURL
cvar_t * sv_cheats
cvar_t * sv_packetloss
cvar_t * sv_packetdelay
cvar_t * sv_dlRate
cvar_t * sv_fullmsg
cvar_t * sv_advert
cvar_t * sv_protect
cvar_t * sv_protectLog
cvar_t * sv_demopath
cvar_t * sv_demoState
cvar_t * sv_autoDemo
cvar_t * cl_freezeDemo
cvar_t * sv_demoTolerant
cvar_t * sv_ipMaxClients
limit client connection
leakyBucket_t outboundLeakyBucket
Detailed Description
Primary header for server.
Definition in file server.h.
Macro Definition Documentation
#define DLNOTIFY_ALL (DLNOTIFY_REDIRECT | DLNOTIFY_BEGIN)
Definition at line 671 of file server.h.
Referenced by SV_BeginDownload_f().
#define DLNOTIFY_BEGIN 0x00000002
"clientDownload: 4 : beginning ..."
Definition at line 670 of file server.h.
Referenced by SV_SetupDownloadFile().
#define DLNOTIFY_REDIRECT 0x00000001
"Redirecting client ..."
Definition at line 669 of file server.h.
Referenced by SV_SetupDownloadFile().
#define MAX_BPS_WINDOW 20
net debugging
Definition at line 61 of file server.h.
Referenced by SV_SendClientMessages().
#define MAX_BUCKETS 16384
This is deliberately quite large to make it more of an effort to DoS.
Definition at line 532 of file server.h.
Referenced by SVC_BucketForAddress().
#define MAX_CHALLENGES 2048
Made large to prevent a DoS attack that could cycle all of them out before legitimate users connected.
Definition at line 306 of file server.h.
Referenced by SV_DirectConnect(), SV_DropClient(), and SV_GetChallenge().
#define MAX_ENT_CLUSTERS 16
Definition at line 59 of file server.h.
Referenced by SV_LinkEntity().
#define MAX_HASHES 1024
Definition at line 533 of file server.h.
Referenced by SVC_HashForAddress().
#define MAX_INFO_RECEIPTS 48
the maximum number of getstatus+getinfo responses that we send in a two second time period.
Definition at line 340 of file server.h.
Referenced by SV_CheckDRDoS().
#define MAX_TEMPBAN_ADDRESSES MAX_CLIENTS
Definition at line 353 of file server.h.
Referenced by SV_TempBanIsBanned(), and SV_TempBanNetAddress().
#define PERS_SCORE 0
!!! MUST NOT CHANGE, SERVER AND GAME BOTH REFERENCE !!!
Definition at line 48 of file server.h.
#define SERVER_PERFORMANCECOUNTER_FRAMES 600
Definition at line 355 of file server.h.
Referenced by SV_Frame().
#define SERVER_PERFORMANCECOUNTER_SAMPLES 6
Definition at line 356 of file server.h.
Referenced by SV_Frame().
#define STATFRAMES 100
5 seconds - assumed we run 20 fps
Definition at line 282 of file server.h.
Referenced by SV_Frame().
#define SV_WriteAttackLogD (x)
Definition at line 553 of file server.h.
Referenced by SVC_BucketForAddress(), and SVC_RateLimit().
#define SVA_MASTER 0x0001
1 - master server
Definition at line 51 of file server.h.
Referenced by SV_MasterGameCompleteStatus(), SV_MasterHeartbeat(), and SV_SpawnServer().
#define SVA_TRACKER 0x0002
2 - tracker
Definition at line 52 of file server.h.
#define SVP_CONSOLE 0x0004
4 - console print
Definition at line 57 of file server.h.
Referenced by SV_WriteAttackLog().
#define SVP_IOQ3 0x0001
1 - ioQuake3 way
Definition at line 55 of file server.h.
Referenced by SV_DirectConnect(), SV_GetChallenge(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
#define SVP_OWOLF 0x0002
2 - OpenWolf way
Definition at line 56 of file server.h.
Referenced by SV_ConnectionlessPacket().
Typedef Documentation
client_t
leakyBucket_t
Definition at line 506 of file server.h.
netchan_buffer_t
svEntity_t
tempBan_t
Enumeration Type Documentation
enum clientState_t
Enumerator
CS_FREE
can be reused for a new connection
CS_ZOMBIE
client has been disconnected, but don't reuse connection for a couple seconds
CS_CONNECTED
has been assigned to a client_t, but no gamestate yet
CS_PRIMED
gamestate has been sent, but client hasn't sent a usercmd
CS_ACTIVE
client is fully in game
Definition at line 176 of file server.h.
enum serverState_t
Enumerator
SS_DEAD
no map loaded
SS_LOADING
spawning level entities
SS_GAME
actively running
Definition at line 85 of file server.h.
Function Documentation
int BotImport_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
BotImport_DebugPolygonCreate.
Parameters
[in] color
[in] numPoints
[in] points
Returns
Definition at line 342 of file sv_bot.c.
Referenced by BotImport_DebugLineCreate(), SV_BotInitBotLib(), and SV_GameSystemCalls().
void BotImport_DebugPolygonDelete (int id)
BotImport_DebugPolygonDelete.
Parameters
[in] id
Definition at line 408 of file sv_bot.c.
Referenced by BotImport_DebugLineDelete(), SV_BotInitBotLib(), and SV_GameSystemCalls().
void QDECL void SV_AddOperatorCommands (void)
SV_AddOperatorCommands.
Definition at line 692 of file sv_ccmds.c.
Referenced by SV_Init().
void SV_AddServerCommand (client_t * client, const char * cmd)
The given command will be transmitted to the client, and is guaranteed to not have future snapshot_t executed before it is executed.
Parameters
[in,out] client
[in] cmd
Definition at line 171 of file sv_main.c.
Referenced by SV_MapRestart_f(), and SV_SendServerCommand().
int SV_AreaEntities (const vec3_t mins, const vec3_t maxs, int * entityList, int maxcount)
SV_AreaEntities.
Parameters
[in] mins
[in] maxs
[in] entityList
[in] maxcount
Returns
Definition at line 509 of file sv_world.c.
Referenced by SV_ClipMoveToEntities(), SV_GameSystemCalls(), and SV_PointContents().
int SV_BotAllocateClient (int clientNum)
Attempts to add a bot to the game First player slot is reserved and cannot be used by a bot.
If the specified slot is taken or private, the first free slot starting from the public slots will be returned.
Parameters
[in] clientNum has to be bigger than 0
Returns
assigned client slot or -1 if it fails to allocate one
Definition at line 53 of file sv_bot.c.
Referenced by SV_GameSystemCalls().
void SV_BotFreeClient (int clientNum)
SV_BotFreeClient.
Parameters
[in] clientNum
Definition at line 115 of file sv_bot.c.
Referenced by SV_DropClient().
int SV_BotGetConsoleMessage (int client, char * buf, size_t size)
SV_BotGetConsoleMessage.
Parameters
[in] client
buf - unused
size - unused
Returns
Definition at line 561 of file sv_bot.c.
Referenced by SV_GameSystemCalls().
void SV_ChangeMaxClients (void)
SV_ChangeMaxClients.
Definition at line 368 of file sv_init.c.
Referenced by SV_SpawnServer().
void SV_CheckClientUserinfoTimer (void)
SV_CheckClientUserinfoTimer.
Definition at line 1093 of file sv_snapshot.c.
Referenced by SV_Frame().
qboolean SV_CheckLastCmd (const char * cmd, qboolean onlyStore)
Check and store the last command and compare it with the current one, to avoid duplicates. If onlyStore is true, it will only store the new cmd, without checking.
Parameters
[in] cmd
[in] onlyStore
Returns
Definition at line 258 of file sv_demo.c.
Referenced by SV_CheckGameCommand(), SV_DemoReadGameCommand(), and SV_GameSendServerCommand().
void SV_ClearWorld (void)
SV_ClearWorld.
Definition at line 161 of file sv_world.c.
Referenced by SV_SpawnServer().
void SV_ClientEnterWorld (client_t * client, usercmd_t * cmd)
SV_ClientEnterWorld.
Parameters
[in,out] client
[in] cmd
Definition at line 771 of file sv_client.c.
Referenced by SV_MapRestart_f(), and SV_UserMove().
void SV_ClientThink (client_t * cl, usercmd_t * cmd)
Also called by bot code.
Parameters
[in,out] cl
[in] cmd
Definition at line 1929 of file sv_client.c.
Referenced by SV_GameSystemCalls(), and SV_UserMove().
clipHandle_t SV_ClipHandleForEntity (const sharedEntity_t * ent)
Return a headnode that can be used for testing or clipping to a given entity.
Parameters
[in] ent
Returns
If the entity is a bsp model, the headnode will be returned, otherwise a custom box tree will be constructed.
Definition at line 47 of file sv_world.c.
Referenced by SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), and SV_PointContents().
void SV_ClipToEntity (trace_t * trace, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int entityNum, int contentmask, qboolean capsule)
SV_ClipToEntity.
Parameters
[in,out] trace
[in] start
[in] mins
[in] maxs
[in] end
[in] entityNum
[in] contentmask
[in] capsule
Definition at line 550 of file sv_world.c.
Referenced by BotImport_EntityTrace().
void SV_DemoAutoDemoRecord (void)
Generates a meaningful demo filename and automatically starts the demo recording.
This function is used in conjunction with the variable sv_autoDemo 1
Note
Be careful, if the hostname contains bad characters, the demo may not be able to be saved at all! There's a small filtering in place but a bad filename may pass through!
this function is called at MapRestart and SpawnServer (called in Map func), but in no way it's called right at the time it's set.
Definition at line 823 of file sv_demo.c.
Referenced by SV_InitGameVM(), and SV_SpawnServer().
qboolean SV_DemoClientCommandCapture (client_t * client, const char * msg)
SV_DemoClientCommandCapture.
Parameters
[in] client
[in] msg
Returns
Definition at line 462 of file sv_demo.c.
Referenced by SV_ExecuteClientCommand().
void SV_DemoInit (void)
SV_DemoInit.
Definition at line 2090 of file sv_demo.c.
Referenced by SV_AddOperatorCommands().
void SV_DemoReadFrame (void)
Play a frame from the demo file.
This function will read one frame per call, and will process every events contained (switch to the next event when meeting the demo_EOF marker) until it meets the end of the frame (demo_endDemo marker).
Called in the main server's loop SV_Frame() in sv_main.c (it's called after any other event processing, so that it overwrites anything the game may have loaded into memory, but before the entities are broadcasted to the clients)
Todo:
: inspect!
Definition at line 1799 of file sv_demo.c.
Referenced by SV_DemoStartPlayback(), and SV_Frame().
void SV_DemoRestartPlayback (void)
Just issue again the demo_play command along with the demo filename (used when the system will automatically restart the server for special cvars values to be set up, eg: sv_maxclients, fs_game, g_gametype, etc..)
Definition at line 930 of file sv_demo.c.
Referenced by SV_Frame().
void SV_DemoShutdown (void)
SV_DemoShutdown.
Todo:
: don't remove these on server shutdown/demo end so listen servers can start another demo and server owners too
Definition at line 2100 of file sv_demo.c.
Referenced by SV_Shutdown().
void SV_DemoStopAll (void)
SV_DemoStopAll.
Definition at line 1945 of file sv_demo.c.
Referenced by SV_Demo_Stop_f(), and SV_ShutdownGameProgs().
void SV_DemoWriteClientUserinfo (client_t * client, const char * userinfo)
Write a client userinfo to the demo file (client_t fields can almost all be filled from the userinfo string)
Parameters
[in] client
[in] userinfo
Note
In practice, clients userinfo should be loaded before their configstrings (because configstrings derive from userinfo in a real game)
Definition at line 592 of file sv_demo.c.
Referenced by SV_CheckClientCommand(), SV_DemoStartRecord(), SV_SetUserinfo(), and SV_UpdateUserinfo_f().
void SV_DemoWriteConfigString (int cs_index, const char * cs_string)
Write a configstring to the demo file.
cs_index = index of the configstring (see bg_public.h) cs_string = content of the configstring to set
Parameters
[in] cs_index
[in] cs_string
Todo:
: try to replace by a WriteLong instead of WriteString? Or WriteData (with length! and it uses WriteByte)
Definition at line 544 of file sv_demo.c.
Referenced by SV_CheckGameCommand(), SV_DemoStartRecord(), and SV_SetConfigstring().
void SV_DemoWriteFrame (void)
Record all the entities (gentities fields) and players (player_t fields) at the end of every frame (this is the only write function to be called in every frame for sure)
Will be called once per server's frame Called in the main server's loop SV_Frame() in sv_main.c Note that this function could be called DemoWriteEndFrame, because it writes once at the end of every frame (the other events are written whenever they happen using hooks)
Definition at line 776 of file sv_demo.c.
Referenced by SV_DemoStartRecord(), and SV_Frame().
void SV_DemoWriteGameCommand (int clientNum, const char * cmd)
Write a game command to the demo file.
Parameters
[in] clientNum
[in] cmd
Note
Game commands are sent to server commands, but we record them separately because game commands are safe to be replayed to everyone (even if at recording time it was only intended to one player), while server commands may be unsafe if it was dedicated only to one player (such as "disconnect")
Definition at line 517 of file sv_demo.c.
Referenced by SV_GameSendServerCommand().
void SV_DemoWriteServerCommand (const char * cmd)
Write a server command to the demo file.
Parameters
[in] cmd
Note
We record only server commands that are meant to be sent to everyone in the first place, that's why we don't even bother to store the clientnum. For commands that were only intended to specifically one player, we only record them if they were game commands (see below the specialized function), else we do not because it may be unsafe (such as "disconnect" command)
Definition at line 491 of file sv_demo.c.
Referenced by SV_SendServerCommand().
void SV_DirectConnect (netadr_t from)
A "connect" OOB command has been received.
Parameters
[in] from
Definition at line 301 of file sv_client.c.
Referenced by SV_ConnectionlessPacket().
void SV_DropClient (client_t * drop, const char * reason)
Called when the player is totally leaving the server, either willingly or unwillingly. This is NOT called if the entire server is quiting or crashing – SV_FinalCommand() will handle that.
Parameters
[in,out] drop
[in] reason
Definition at line 598 of file sv_client.c.
Referenced by SV_AddServerCommand(), SV_CheckTimeouts(), SV_ClientCommand(), SV_DemoReadClientConfigString(), SV_DirectConnect(), SV_Disconnect_f(), SV_ExecuteClientMessage(), SV_GameDropClient(), SV_MapRestart_f(), SV_NextDownload_f(), SV_SendClientIdle(), SV_SendClientMessages(), SV_SendClientSnapshot(), SV_SetupDownloadFile(), SV_SpawnServer(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), and SV_WWWDownload_f().
void SV_ExecuteClientCommand (client_t * cl, const char * s, qboolean clientOK, qboolean premaprestart)
Also called by bot code.
Parameters
[in] cl
[in] s
[in] clientOK
[in] premaprestart
Definition at line 1789 of file sv_client.c.
Referenced by BotClientCommand(), SV_ClientCommand(), SV_ClientEnterWorld(), SV_DemoReadClientCommand(), SV_DemoReadClientUserinfo(), SV_DemoStartPlayback(), and SV_GameSystemCalls().
void SV_ExecuteClientMessage (client_t * cl, msg_t * msg)
SV_ExecuteClientMessage.
Parameters
[in,out] cl
[in] msg
Definition at line 2106 of file sv_client.c.
Referenced by SV_PacketEvent().
void SV_FinalCommand (const char * cmd, qboolean disconnect)
added disconnect flag so map changes can use this function as well
added disconnect flag so map changes can use this function as well
Parameters
[in] cmd
[in] disconnect
Definition at line 1155 of file sv_init.c.
Referenced by SV_Shutdown(), and SV_SpawnServer().
void SV_GameBinaryMessageReceived (int cno, const char * buf, int buflen, int commandTime)
SV_GameBinaryMessageReceived.
Parameters
[in] cno
[in] buf
[in] buflen
[in] commandTime
Definition at line 401 of file sv_game.c.
Referenced by SV_ParseBinaryMessage().
playerState_t* SV_GameClientNum (int num)
SV_GameClientNum.
Parameters
[in] num
Returns
Definition at line 77 of file sv_game.c.
Referenced by SV_BuildClientSnapshot(), SV_CalcPings(), SV_DemoReadAllPlayerState(), SV_DemoReadRefreshEntities(), SV_DemoReadRefreshPlayersHealth(), SV_DemoWriteAllPlayerState(), SV_Status_f(), and SVC_Status().
void SV_GameSendServerCommand (int clientNum, const char * text)
Sends a command string to a client.
Parameters
[in] clientNum
[in] text
Definition at line 115 of file sv_game.c.
Referenced by SV_DemoReadGameCommand(), and SV_GameSystemCalls().
sharedEntity_t* SV_GEntityForSvEntity (svEntity_t * svEnt)
SV_GEntityForSvEntity.
Parameters
[in] svEnt
Returns
Definition at line 103 of file sv_game.c.
Referenced by SV_AreaEntities_r().
sharedEntity_t* SV_GentityNum (int num)
SV_GentityNum.
Parameters
[in] num
Returns
Definition at line 65 of file sv_game.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_BotAllocateClient(), SV_BuildClientSnapshot(), SV_ClientEnterWorld(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_CreateBaseline(), SV_DemoReadAllEntityShared(), SV_DemoReadAllEntityState(), SV_DemoReadRefreshEntities(), SV_DemoReadRefreshPlayersHealth(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DirectConnect(), SV_GEntityForSvEntity(), SV_PointContents(), and SV_SpawnServer().
void SV_GentityUpdateHealthField (sharedEntity_t * gent, playerState_t * player)
Update the value of the gentity_t->health field with playerState_t->stats[STAT_HEALTH] for a given player.
You need to supply the player's sharedEntity and playerState (because since we have special includes here, we don't have access to the functions that can return a player from their int id).
The concrete effect is that when replaying a demo, the players' health will be updated on the HUD (if it weren't for this function to update the health, the health wouldn't change and stay kinda static).
Parameters
[out] gent
[in] player
Note
1. We need to do that because the demo can only records this stats[stat_health], which is concretely the same as gentity_t->health. The latter should have been removed altogether considering the comments in g_active.c : (ent->client->ps.stats[STAT_HEALTH] = ent->health; ///
Todo:
: get rid of ent->health...), but it seems to have survived because it allows non-player entities to have health, such as obelisks. And weirdly, gentity_t->health has ascendence over stat_health (meaning stat_health is updated following gentity_t->health, but never the other way around), when for example stat_armor has ascendence over anything else of the same kind, so here we have to update it by ourselves.
Note
2. This works pretty simply: sharedEntity_t = gentity_t but with only the first 2 fields declared (entityShared_t and entityState_t), but all the other fields are still in memory! We only need to get a valid declaration for gentity_t (which we do by doing the right includes at the top of this file, in g_local.h), and then we can convert the limited sharedEntity_t into a gentity_t with all the fields!
Definition at line 101 of file sv_demo_ext.c.
Referenced by SV_DemoReadRefreshPlayersHealth().
void SV_GetChallenge (netadr_t from)
A "getchallenge" OOB command has been received.
Parameters
[in] from
Returns
challenge number that can be used in a subsequent connectResponse command.
We do this to prevent denial of service attacks that flood the server with invalid connection IPs. With a challenge, they must give a valid IP address.
Todo:
: deal with restricted filesystem - done with sv_pure check ?
Definition at line 52 of file sv_client.c.
Referenced by SV_ConnectionlessPacket().
void SV_GetConfigstring (int index, char * buffer, unsigned int bufferSize)
SV_GetConfigstring.
Parameters
[in] index
[out] buffer
[in] bufferSize
Definition at line 209 of file sv_init.c.
Referenced by SV_GameSystemCalls().
qboolean SV_GetTag (int clientNum, int tagFileNumber, char * tagname, orientation_t * orientation)
SV_GetTag.
Parameters
[in] clientNum - unused
[in] tagFileNumber
[out] tagname
[out] orientation
Returns
qfalse if unable to retrieve tag information for this client
Definition at line 803 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_GetUserinfo (int index, char * buffer, unsigned int bufferSize)
SV_GetUserinfo.
Parameters
[in] index
[out] buffer
[in] bufferSize
Definition at line 261 of file sv_init.c.
Referenced by SV_GameSystemCalls().
void SV_Heartbeat_f (void)
Also called by SV_DropClient, SV_DirectConnect, and SV_SpawnServer.
Definition at line 562 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands(), SV_DirectConnect(), SV_DropClient(), and SV_SpawnServer().
void SV_InitGameProgs (void)
Called on a normal map change, not on a map_restart.
Definition at line 766 of file sv_game.c.
Referenced by SV_SpawnServer().
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
Also checks portalareas so that doors block sight.
Parameters
[in] p1
[in] p2
Returns
Definition at line 200 of file sv_game.c.
Referenced by BotImport_inPVS(), and SV_GameSystemCalls().
void SV_LinkEntity (sharedEntity_t * gEnt)
SV_LinkEntity.
Parameters
[in,out] gEnt
Todo:
: - Clarify if this warning is false positive for some ents
Definition at line 220 of file sv_world.c.
Referenced by SV_DemoReadAllEntityShared(), SV_GameSystemCalls(), and SV_SetBrushModel().
int SV_LoadTag (const char * mod_name)
SV_LoadTag.
Parameters
[in] mod_name
Returns
Definition at line 1813 of file sv_main.c.
Referenced by SV_GameSystemCalls().
void SV_MasterGameCompleteStatus (void)
Sends gameCompleteStatus messages to all master servers.
Definition at line 417 of file sv_main.c.
Referenced by SV_GameCompleteStatus_f().
void SV_MasterHeartbeat (const char * msg)
Send a message to the masters every few minutes to let it know we are alive, and log information.
We will also have a heartbeat sent when a server changes from empty to non-empty, and full to non-full, but not on every player enter or exit.
Parameters
[in] msg
Definition at line 292 of file sv_main.c.
Referenced by SV_Frame(), and SV_MasterShutdown().
void SV_MasterShutdown (void)
Informs all masters that this server is going down.
Definition at line 535 of file sv_main.c.
Referenced by SV_Shutdown().
void SV_Netchan_ClearQueue (client_t * client)
SV_Netchan_ClearQueue.
Parameters
[in,out] client
Definition at line 155 of file sv_net_chan.c.
Referenced by SV_DirectConnect(), SV_DropClient(), and SV_Shutdown().
qboolean SV_Netchan_Process (client_t * client, msg_t * msg)
SV_Netchan_Process.
Parameters
[in] client
[in] msg
Returns
Definition at line 286 of file sv_net_chan.c.
Referenced by SV_PacketEvent().
void SV_Netchan_Transmit (client_t * client, msg_t * msg)
SV_Netchan_Transmit.
If there are some unsent fragments (which may happen if the snapshots and the gamestate are fragmenting, and collide on send for instance) then buffer them and make sure they get sent in correct order
Parameters
[in,out] client
[in] msg
Definition at line 255 of file sv_net_chan.c.
Referenced by SV_SendDownloadMessages(), and SV_SendMessageToClient().
int SV_Netchan_TransmitNextFragment (client_t * client)
SV_Netchan_TransmitNextFragment.
Parameters
[in] client
Returns
Definition at line 204 of file sv_net_chan.c.
Referenced by SV_SendQueuedMessages().
int SV_NumForGentity (sharedEntity_t * ent)
SV_NumForGentity.
Todo:
TODO: These functions must be used instead of pointer arithmetic, because the game allocates gentities with private information after the server shared part
Parameters
[in] ent
Returns
Note
Unused
Definition at line 53 of file sv_game.c.
int SV_PointContents (const vec3_t p, int passEntityNum)
SV_PointContents.
Parameters
[in] p
[in] passEntityNum
Returns
Definition at line 793 of file sv_world.c.
Referenced by BotImport_PointContents(), and SV_GameSystemCalls().
int SV_RateMsec (client_t * client)
Return the number of msec until another message can be sent to a client based on its rate settings.
Parameters
[in] client
Returns
The number of msec
Definition at line 774 of file sv_snapshot.c.
Referenced by SV_Netchan_TransmitNextFragment(), SV_SendClientMessages(), and SV_SendQueuedMessages().
void SV_RemoveOperatorCommands (void)
SV_RemoveOperatorCommands.
Definition at line 733 of file sv_ccmds.c.
Referenced by SV_Shutdown().
void SV_RestartGameProgs (void)
Called on a map_restart, but not on a normal map change.
Definition at line 745 of file sv_game.c.
Referenced by SV_MapRestart_f().
void SV_SectorList_f (void)
SV_SectorList_f.
Definition at line 92 of file sv_world.c.
Referenced by SV_AddOperatorCommands().
void SV_SendClientIdle (client_t * client)
There is no need to send full snapshots to clients who are loading a map. So we send them "idle" packets with the bare minimum required to keep them on the server.
Parameters
[in] client
Definition at line 857 of file sv_snapshot.c.
Referenced by SV_SendClientSnapshot().
void SV_SendClientMessages (void)
SV_SendClientMessages.
Definition at line 961 of file sv_snapshot.c.
Referenced by SV_Frame().
void SV_SendClientSnapshot (client_t * client)
SV_SendClientSnapshot.
Parameters
[in] client
Note
Also called by SV_FinalCommand
Definition at line 902 of file sv_snapshot.c.
Referenced by SV_FinalCommand(), SV_SendClientMessages(), and SV_VerifyPaks_f().
int SV_SendDownloadMessages (void)
Send one round of download messages to all clients.
Returns
Definition at line 1370 of file sv_client.c.
Referenced by SV_SendQueuedPackets().
void SV_SendMessageToClient (msg_t * msg, client_t * client)
Called by SV_SendClientSnapshot and SV_SendClientGameState.
Parameters
[in] msg
[in,out] client
Definition at line 840 of file sv_snapshot.c.
Referenced by SV_SendClientGameState(), SV_SendClientIdle(), and SV_SendClientSnapshot().
int SV_SendQueuedMessages (void)
Send one round of fragments, or queued messages to all clients that have data pending.
Returns
The shortest time interval for sending next packet to client
Definition at line 1338 of file sv_client.c.
Referenced by SV_SendQueuedPackets().
void QDECL SV_SendServerCommand (client_t * cl, const char * fmt, ...)
Referenced by IRC_Display(), SV_ConSay_f(), SV_DemoClientCommandCapture(), SV_DemoReadServerCommand(), SV_DemoStartPlayback(), SV_DropClient(), SV_FinalCommand(), SV_GameSendServerCommand(), SV_UpdateConfigStrings(), and SV_UpdateUserinfo_f().
void SV_SetConfigstring (int index, const char * val)
SV_SetConfigstring.
Parameters
[in] index
[in] val
Definition at line 74 of file sv_init.c.
Referenced by SV_DemoReadClientConfigString(), SV_DemoReadConfigString(), SV_DemoStopPlayback(), SV_Frame(), SV_GameSystemCalls(), SV_MapRestart_f(), and SV_SpawnServer().
void SV_SetConfigstringNoUpdate (int index, const char * val)
SV_SetConfigstringNoUpdate.
Parameters
[in] index
[in] val
Definition at line 46 of file sv_init.c.
Referenced by SV_Frame().
void SV_SetUserinfo (int index, const char * val)
SV_SetUserinfo.
Parameters
[in] index
[in] val
Definition at line 233 of file sv_init.c.
Referenced by SV_DropClient(), and SV_GameSystemCalls().
void SV_ShutdownGameProgs (void)
Called every time a map changes.
Definition at line 697 of file sv_game.c.
void SV_SpawnServer (const char * server)
Change the server to a new map, taking all connected clients along with it. This is NOT called for map_restart.
Parameters
[in] server
Definition at line 648 of file sv_init.c.
Referenced by SV_Map_f(), and SV_MapRestart_f().
svEntity_t* SV_SvEntityForGentity (sharedEntity_t * gEnt)
SV_SvEntityForGentity.
Parameters
[in] gEnt
Returns
Definition at line 89 of file sv_game.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_AdjustAreaPortalState(), SV_LinkEntity(), and SV_UnlinkEntity().
qboolean SV_TempBanIsBanned (netadr_t address)
SV_TempBanIsBanned.
Parameters
[in] address
Returns
Definition at line 435 of file sv_ccmds.c.
Referenced by SV_GetChallenge(), and SV_isValidClient().
void SV_TempBanNetAddress (netadr_t address, int length)
SV_TempBanNetAddress.
Parameters
[in] address
[in] length
Definition at line 400 of file sv_ccmds.c.
Referenced by SV_GameDropClient().
void SV_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, qboolean capsule)
Moves the given mins/maxs volume through the world from start to end. passEntityNum and entities owned by passEntityNum are explicitly not checked.
Parameters
[out] results
[in] start
[in] mins
[in] maxs
[in] end
[in] passEntityNum
[in] contentmask
[in] capsule
Definition at line 729 of file sv_world.c.
Referenced by BotImport_Trace(), and SV_GameSystemCalls().
void SV_UnlinkEntity (sharedEntity_t * gEnt)
SV_UnlinkEntity.
Parameters
[in,out] gEnt
Definition at line 179 of file sv_world.c.
Referenced by SV_DemoReadAllEntityShared(), SV_GameSystemCalls(), and SV_LinkEntity().
void SV_UpdateConfigStrings (void)
Updates the configstring.
Note
It's nice to know this function sends several server commands when a configstring is greater than 1000 usually BIG_INFO_STRINGs
Definition at line 108 of file sv_init.c.
Referenced by SV_SendClientMessages(), and SV_SpawnServer().
void SV_UpdateServerCommandsToClient (client_t * client, msg_t * msg)
(re)send all server commands the client hasn't acknowledged yet
Parameters
[in] client
[in] msg
Definition at line 249 of file sv_snapshot.c.
Referenced by SV_SendClientGameState(), SV_SendClientIdle(), and SV_SendClientSnapshot().
void SV_UpdateUserinfo_f (client_t * cl)
SV_UpdateUserinfo_f.
Parameters
[in] cl
Definition at line 1730 of file sv_client.c.
Referenced by SV_CheckClientUserinfoTimer(), and SV_DemoReadClientUserinfo().
void SV_UptimeReset (void)
SV_UptimeReset.
Definition at line 658 of file sv_ccmds.c.
Referenced by SV_Init().
void SV_UserinfoChanged (client_t * cl)
Pull specific info from a newly changed userinfo string into a more C friendly form.
Parameters
[in,out] cl
Definition at line 1619 of file sv_client.c.
Referenced by SV_DirectConnect(), and SV_UpdateUserinfo_f().
void SV_WriteAttackLog (const char * log)
SV_WriteAttackLog.
Parameters
[in] log
Definition at line 909 of file sv_init.c.
Referenced by Com_UpdateInfoPacket(), SV_CheckDRDoS(), SV_CloseAttackLog(), SV_ConnectionlessPacket(), SV_DirectConnect(), SV_GetChallenge(), SV_InitAttackLog(), SV_SendServerCommand(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
qboolean SVC_RateLimit (leakyBucket_t * bucket, int burst, int period)
SVC_RateLimit.
Parameters
[in,out] bucket
[in] burst
[in] period
Returns
Note
Don't call if sv_protect 1 (SVP_IOQ3) flag is not set!
Definition at line 705 of file sv_main.c.
Referenced by SV_GetChallenge(), SVC_Info(), SVC_RateLimitAddress(), SVC_RemoteCommand(), and SVC_Status().
qboolean SVC_RateLimitAddress (netadr_t from, int burst, int period)
Rate limit for a particular address.
Parameters
from
burst
period
Returns
Note
Don't call if sv_protect 1 (SVP_IOQ3) flag is not set!
Definition at line 748 of file sv_main.c.
Referenced by SV_DirectConnect(), SV_GetChallenge(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
Variable Documentation
cvar_t* cl_freezeDemo
Definition at line 63 of file cl_main.c.
Referenced by CL_DemoRun(), CL_PauseDemo_f(), CL_SetCGameTime(), and SV_Init().
vm_t* gvm
game virtual machine
Definition at line 39 of file sv_main.c.
Referenced by SV_AddEntToSnapshot(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DemoReadClientConfigString(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_GameBinaryMessageReceived(), SV_GameCommand(), SV_InitGameProgs(), SV_InitGameVM(), SV_MapRestart_f(), SV_RestartGameProgs(), SV_ShutdownGameProgs(), SV_SpawnServer(), and SV_UpdateUserinfo_f().
leakyBucket_t outboundLeakyBucket
Definition at line 552 of file sv_main.c.
Referenced by SV_GetChallenge().
server_t sv
cleared each map
Definition at line 38 of file sv_main.c.
Referenced by Com_DownloadsComplete(), Com_Frame(), Com_RunUpdateBinary(), R_BuildCubeMaps(), SV_AddEntitiesVisibleFromPoint(), SV_AddEntToSnapshot(), SV_AreaEntities_r(), SV_BuildClientSnapshot(), SV_ClearServer(), SV_ClientEnterWorld(), SV_CreateBaseline(), SV_Demo_Play_f(), SV_Demo_Record_f(), SV_Demo_Stop_f(), SV_DemoAutoDemoRecord(), SV_DemoChangeMaxClients(), SV_DemoClientCommandCapture(), SV_DemoReadAllEntityShared(), SV_DemoReadAllEntityState(), SV_DemoReadAllPlayerState(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DemoReadFrame(), SV_DemoReadRefreshEntities(), SV_DemoRestartPlayback(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopAll(), SV_DemoStopPlayback(), SV_DemoStopRecord(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DemoWriteAllPlayerState(), SV_DemoWriteMessage(), SV_EmitPacketEntities(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_GameClientNum(), SV_GameCommand(), SV_GameSendServerCommand(), SV_GameSystemCalls(), SV_GEntityForSvEntity(), SV_GentityNum(), SV_GetConfigstring(), SV_GetTag(), SV_InitGameProgs(), SV_InitGameVM(), SV_LinkEntity(), SV_LocateGameData(), SV_MapRestart_f(), SV_NumForGentity(), SV_SendClientGameState(), SV_SendClientIdle(), SV_SendClientMessages(), SV_SendClientSnapshot(), SV_SetConfigstring(), SV_SetConfigstringNoUpdate(), SV_SetUserinfo(), SV_SpawnServer(), SV_SvEntityForGentity(), SV_UpdateConfigStrings(), SV_UpdateUserinfo_f(), SV_UserMove(), and SV_VerifyPaks_f().
cvar_t* sv_advert
Definition at line 93 of file sv_main.c.
Referenced by SV_Init(), and SV_SpawnServer().
cvar_t* sv_allowDownload
Definition at line 46 of file sv_main.c.
Referenced by SV_CheckDownloadAllowed(), and SV_Init().
cvar_t* sv_autoDemo
Definition at line 113 of file sv_main.c.
Referenced by SV_Init(), SV_InitGameVM(), and SV_SpawnServer().
cvar_t* sv_cheats
Definition at line 84 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_democlients
number of democlients: this should always be set to 0, and will be automatically adjusted when needed by the demo facility. ATTENTION: if sv_maxclients = sv_democlients then server will be full! sv_democlients consume clients slots even if there are no democlients recorded nor replaying for this slot!
Definition at line 48 of file sv_main.c.
Referenced by SV_ClientEnterWorld(), SV_DemoChangeMaxClients(), SV_DemoClientCommandCapture(), SV_DemoReadRefreshEntities(), SV_DemoReadRefreshPlayersHealth(), SV_DemoStartPlayback(), SV_DemoStopPlayback(), SV_DirectConnect(), SV_GameSystemCalls(), and SV_Init().
cvar_t* sv_demopath
Definition at line 111 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_demoState
Definition at line 112 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_demoTolerant
Definition at line 115 of file sv_main.c.
Referenced by SV_DemoReadFrame(), SV_DemoStartPlayback(), and SV_Init().
cvar_t* sv_dl_timeout
autodl
Definition at line 73 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_dlRate
Definition at line 90 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_floodProtect
Definition at line 66 of file sv_main.c.
Referenced by SV_CheckClientUserinfoTimer(), SV_ClientCommand(), SV_Init(), and SV_UpdateUserinfo_f().
cvar_t* sv_fps
Definition at line 353 of file g_main.c.
cvar_t* sv_friendlyFire
Definition at line 69 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_fullmsg
Definition at line 88 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_gametype
Definition at line 64 of file sv_main.c.
Referenced by SV_DemoStartPlayback(), SV_DemoStartRecord(), and SV_Init().
cvar_t* sv_hostname
Definition at line 51 of file sv_main.c.
Referenced by SV_DemoAutoDemoRecord(), SV_DemoStartRecord(), and SV_Init().
cvar_t* sv_ipMaxClients
limit client connection
Definition at line 117 of file sv_main.c.
Referenced by SV_Init(), SV_isClientIPValidToConnect(), and SV_isValidClient().
cvar_t* sv_killserver
Definition at line 56 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_lanForceRate
Definition at line 67 of file sv_main.c.
Referenced by SV_Init(), SV_SendClientMessages(), and SV_UserinfoChanged().
cvar_t* sv_mapChecksum
Definition at line 58 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_mapname
Definition at line 57 of file sv_main.c.
Referenced by SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_Init(), and SV_Status_f().
cvar_t* sv_master[MAX_MASTER_SERVERS]
cvar_t* sv_maxclients
Definition at line 47 of file sv_main.c.
Referenced by SV_BinaryMessageStatus(), SV_BotAllocateClient(), SV_BotFreeClient(), SV_BoundMaxClients(), SV_BuildClientSnapshot(), SV_ChangeMaxClients(), SV_ClientEnterWorld(), SV_Demo_Record_f(), SV_DemoChangeMaxClients(), SV_DemoClientCommandCapture(), SV_DemoReadConfigString(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopPlayback(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DemoWriteAllPlayerState(), SV_DirectConnect(), SV_DropClient(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GameSystemCalls(), SV_GetUsercmd(), SV_GetUserinfo(), SV_Init(), SV_InitGameVM(), SV_isClientIPValidToConnect(), SV_MapRestart_f(), SV_SendBinaryMessage(), SV_SendClientMessages(), SV_SendDownloadMessages(), SV_SendQueuedMessages(), SV_SetNumSnapshotEntities(), SV_SetUserinfo(), SV_Shutdown(), SV_SpawnServer(), and SV_Startup().
cvar_t* sv_maxlives
Definition at line 70 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_maxPing
Definition at line 63 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_maxRate
Definition at line 61 of file sv_main.c.
Referenced by SV_Init(), and SV_RateMsec().
cvar_t* sv_minPing
Definition at line 62 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_minRate
Definition at line 60 of file sv_main.c.
Referenced by SV_Init(), and SV_RateMsec().
cvar_t* sv_needpass
Definition at line 71 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_onlyVisibleClients
Definition at line 68 of file sv_main.c.
Referenced by SV_GetChallenge(), and SV_Init().
cvar_t* sv_packetdelay
Definition at line 126 of file common.c.
Referenced by SV_Init().
cvar_t* sv_packetloss
Definition at line 85 of file sv_main.c.
cvar_t* sv_padPackets
Definition at line 55 of file sv_main.c.
Referenced by SV_Init(), and SV_WriteSnapshotToClient().
cvar_t* sv_privateClients
Definition at line 50 of file sv_main.c.
Referenced by SV_BotAllocateClient(), SV_DemoChangeMaxClients(), SV_DirectConnect(), and SV_Init().
cvar_t* sv_privatePassword
Definition at line 45 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_protect
Definition at line 98 of file sv_main.c.
Referenced by SV_DirectConnect(), SV_GetChallenge(), SV_Init(), and SV_WriteAttackLog().
cvar_t* sv_protectLog
Definition at line 102 of file sv_main.c.
Referenced by SV_Init(), and SV_InitAttackLog().
cvar_t* sv_pure
Definition at line 65 of file sv_main.c.
Referenced by SV_CheckDownloadAllowed(), SV_Init(), SV_SpawnServer(), SV_TouchCGameDLL(), SV_UserMove(), and SV_VerifyPaks_f().
cvar_t* sv_rconPassword
Definition at line 44 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_reconnectlimit
Definition at line 52 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_serverid
Definition at line 59 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_showAverageBPS
net debugging
Definition at line 75 of file sv_main.c.
Referenced by SV_Init(), and SV_SendClientMessages().
cvar_t* sv_tempbanmessage
Definition at line 53 of file sv_main.c.
Referenced by SV_GetChallenge(), SV_Init(), SV_isValidClient(), and SV_IsValidUserinfo().
cvar_t* sv_timeout
Definition at line 42 of file sv_main.c.
Referenced by SV_Init().
cvar_t* sv_wwwBaseURL
the base URL of all the files
Definition at line 78 of file sv_main.c.
Referenced by SV_Init(), and SV_SetupDownloadFile().
cvar_t* sv_wwwDlDisconnected
tell clients to perform their downloads while disconnected from the server this gets you a better throughput, but you loose the ability to control the download usage
Definition at line 81 of file sv_main.c.
Referenced by SV_Init(), and SV_SetupDownloadFile().
cvar_t* sv_wwwDownload
general flag to enable/disable www download redirects
Definition at line 77 of file sv_main.c.
Referenced by SV_Init(), and SV_SetupDownloadFile().
cvar_t* sv_wwwFallbackURL
Definition at line 82 of file sv_main.c.
Referenced by SV_CheckFallbackURL(), and SV_Init().
cvar_t* sv_zombietime
Definition at line 43 of file sv_main.c.
Referenced by SV_Init().
serverStatic_t svs
persistant server info across maps
Definition at line 37 of file sv_main.c.
Referenced by BotClientCommand(), Com_Printf(), SV_BinaryMessageStatus(), SV_BotAllocateClient(), SV_BotFreeClient(), SV_BotGetConsoleMessage(), SV_BuildClientSnapshot(), SV_ChangeMaxClients(), SV_CheckClientUserinfoTimer(), SV_CheckDownloadAllowed(), SV_ClientCommand(), SV_ClientEnterWorld(), SV_ClientThink(), SV_CloseDownload(), SV_DemoChangeMaxClients(), SV_DemoClientCommandCapture(), SV_DemoReadClientCommand(), SV_DemoReadClientConfigString(), SV_DemoReadClientUserinfo(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoWriteAllPlayerState(), SV_DemoWriteClientCommand(), SV_DemoWriteClientUserinfo(), SV_DemoWriteFrame(), SV_DirectConnect(), SV_DoneDownload_f(), SV_DropClient(), SV_EmitPacketEntities(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_FinalCommand(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GameSystemCalls(), SV_GetChallenge(), SV_GetPlayerByName(), SV_GetUsercmd(), SV_GetUserinfo(), SV_Heartbeat_f(), SV_Init(), SV_InitGameVM(), SV_isClientIPValidToConnect(), SV_MapRestart_f(), SV_NextDownload_f(), SV_ParseBinaryMessage(), SV_SendBinaryMessage(), SV_SendClientGameState(), SV_SendClientMessages(), SV_SendDownloadMessages(), SV_SendMessageToClient(), SV_SendQueuedMessages(), SV_SetNumSnapshotEntities(), SV_SetupDownloadFile(), SV_SetUserinfo(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), SV_Status_f(), SV_StopDownload_f(), SV_TempBanIsBanned(), SV_TempBanNetAddress(), SV_UpdateConfigStrings(), SV_UpdateUserinfo_f(), SV_Uptime_f(), SV_UserMove(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().