ET: Legacy: src/qcommon/crypto/sha-1/sha1.h File Reference
sha1.h File Reference
This class implements the Secure Hashing Standard as defined in FIPS PUB 180-1 published April 17, 1995.
Data Structures
struct SHA1Context
Typedefs
typedef struct SHA1Context SHA1Context
Functions
void SHA1Reset (SHA1Context *)
int SHA1Result (SHA1Context *)
void SHA1Input (SHA1Context *, const unsigned char *, unsigned)
Detailed Description
This class implements the Secure Hashing Standard as defined in FIPS PUB 180-1 published April 17, 1995.
Many of the variable names in the SHA1Context, especially the single character names, were used because those were the names used in the publication.
Please read the file sha1.c for more information.
Definition in file sha1.h.
Typedef Documentation
typedef struct SHA1Context SHA1Context
Function Documentation
void SHA1Input (SHA1Context * , const unsigned char * , unsigned)
Definition at line 141 of file sha1.c.
Referenced by FS_Unzip(), G_SHA1(), and main().
void SHA1Reset (SHA1Context *)
Definition at line 69 of file sha1.c.
Referenced by FS_Unzip(), G_SHA1(), and main().
int SHA1Result (SHA1Context *)
Definition at line 102 of file sha1.c.
Referenced by FS_Unzip(), G_SHA1(), and main().