ET: Legacy: src/tools/shdr/shaders2h.cpp File Reference
shaders2h.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <string>
#include <cstdarg>
#include <vector>
#include "tinydir.h"
Data Structures
struct shader_out
Macros
#define LINE_SIZE 16
Functions
static void add_string_part (string &out, const string &enc, const string &plain)
static void make_c_string (string &in)
static bool read_file_to_c_string (const string &path, string &output)
static shader_out read_file (tinydir_file *file, const string &path)
static void process_folder (vector< shader_out > &shaders, const string &folder, const string &path)
static void write_const_char (FILE *outputFile, const string &name, const string &text, const string &comment="")
static int write_output (string &out_file, string &array_name, vector< shader_out > &shaders, const string &shader_def)
int main (int argc, char **args)
Variables
static bool plain_text = false
const char * headerValue
const char hexChars [16] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' }
Macro Definition Documentation
#define LINE_SIZE 16
Definition at line 330 of file shaders2h.cpp.
Referenced by write_const_char().
Function Documentation
static void add_string_part (string & out, const string & enc, const string & plain) static
Definition at line 79 of file shaders2h.cpp.
Referenced by make_c_string().
int main (int argc, char ** args)
Definition at line 431 of file shaders2h.cpp.
static void make_c_string (string & in) static
Definition at line 91 of file shaders2h.cpp.
Referenced by read_file_to_c_string().
static void process_folder (vector< shader_out > & shaders, const string & folder, const string & path) static
Definition at line 292 of file shaders2h.cpp.
Referenced by main().
static shader_out read_file (tinydir_file * file, const string & path) static
Definition at line 262 of file shaders2h.cpp.
Referenced by process_folder().
static bool read_file_to_c_string (const string & path, string & output) static
Definition at line 241 of file shaders2h.cpp.
Referenced by main(), and read_file().
static void write_const_char (FILE * outputFile, const string & name, const string & text, const string & comment = "") static
Definition at line 332 of file shaders2h.cpp.
Referenced by write_output().
static int write_output (string & out_file, string & array_name, vector< shader_out > & shaders, const string & shader_def) static
Definition at line 385 of file shaders2h.cpp.
Referenced by main().
Variable Documentation
const char* headerValue
Initial value:
=
"/*\n"
"===========================================================================\n"
"Copyright (C) 2006-2008 Robert Beckebans <trebor_7@users.sourceforge.net>\n"
"\n"
"This file is part of XreaL source code.\n"
"\n"
"XreaL source code is free software; you can redistribute it\n"
"and/or modify it under the terms of the GNU General Public License as\n"
"published by the Free Software Foundation; either version 2 of the License,\n"
"or (at your option) any later version.\n"
"\n"
"XreaL source code is distributed in the hope that it will be\n"
"useful, but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"GNU General Public License for more details.\n"
"\n"
"You should have received a copy of the GNU General Public License\n"
"along with XreaL source code; if not, write to the Free Software\n"
"Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA\n"
"===========================================================================\n"
"*/\n"
"/* This file was generated by shdr2h, do not modify as it will get overwritten */"
Definition at line 55 of file shaders2h.cpp.
Referenced by write_output().
const char hexChars[16] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' }
Definition at line 329 of file shaders2h.cpp.
Referenced by write_const_char().
bool plain_text = false static
Definition at line 45 of file shaders2h.cpp.
Referenced by add_string_part(), main(), make_c_string(), and write_const_char().