ET: Legacy: src/client/snd_codec_wav.c File Reference
snd_codec_wav.c File Reference
#include "client.h"
#include "snd_codec.h"
Functions
static int FGetLittleLong (fileHandle_t f)
FGetLittleLong.
static short FGetLittleShort (fileHandle_t f)
FGetLittleShort.
static int S_ReadChunkInfo (fileHandle_t f, char *name)
S_ReadChunkInfo.
static int S_FindRIFFChunk (fileHandle_t f, const char *chunk)
S_FindRIFFChunk.
static void S_ByteSwapRawSamples (int samples, int width, int s_channels, byte *data)
S_ByteSwapRawSamples.
static qboolean S_ReadRIFFHeader (fileHandle_t file, snd_info_t *info)
S_ReadRIFFHeader.
void * S_WAV_CodecLoad (const char *filename, snd_info_t *info)
S_WAV_CodecLoad.
snd_stream_t * S_WAV_CodecOpenStream (const char *filename)
S_WAV_CodecOpenStream.
void S_WAV_CodecCloseStream (snd_stream_t *stream)
S_WAV_CodecCloseStream.
int S_WAV_CodecReadStream (snd_stream_t *stream, int bytes, void *buffer)
S_WAV_CodecReadStream.
Variables
snd_codec_t wav_codec
Function Documentation
static int FGetLittleLong (fileHandle_t f) static
FGetLittleLong.
Parameters
[in] f
Returns
Definition at line 43 of file snd_codec_wav.c.
Referenced by S_ReadChunkInfo(), and S_ReadRIFFHeader().
static short FGetLittleShort (fileHandle_t f) static
FGetLittleShort.
Parameters
[in] f
Returns
Definition at line 57 of file snd_codec_wav.c.
Referenced by S_ReadRIFFHeader().
static void S_ByteSwapRawSamples (int samples, int width, int s_channels, byte * data) static
S_ByteSwapRawSamples.
Parameters
[in] samples
[in] width
[in] s_channels
[in,out] data
Definition at line 129 of file snd_codec_wav.c.
Referenced by S_WAV_CodecLoad(), and S_WAV_CodecReadStream().
static int S_FindRIFFChunk (fileHandle_t f, const char * chunk) static
S_FindRIFFChunk.
Parameters
[in] f
[in] chunk
Returns
The length of the data in the chunk, or -1 if not found
Definition at line 100 of file snd_codec_wav.c.
Referenced by S_ReadRIFFHeader().
static int S_ReadChunkInfo (fileHandle_t f, char * name) static
S_ReadChunkInfo.
Parameters
[in] f
[in,out] name
Returns
Definition at line 72 of file snd_codec_wav.c.
Referenced by S_FindRIFFChunk().
static qboolean S_ReadRIFFHeader (fileHandle_t file, snd_info_t * info) static
S_ReadRIFFHeader.
Parameters
[in] file
[out] info
Returns
Definition at line 158 of file snd_codec_wav.c.
Referenced by S_WAV_CodecLoad(), and S_WAV_CodecOpenStream().
void S_WAV_CodecCloseStream (snd_stream_t * stream)
S_WAV_CodecCloseStream.
Parameters
[in,out] stream
Definition at line 303 of file snd_codec_wav.c.
void* S_WAV_CodecLoad (const char * filename, snd_info_t * info)
S_WAV_CodecLoad.
Parameters
[in] filename
[in] info
Returns
Definition at line 228 of file snd_codec_wav.c.
snd_stream_t* S_WAV_CodecOpenStream (const char * filename)
S_WAV_CodecOpenStream.
Parameters
[in] filename
Returns
Definition at line 278 of file snd_codec_wav.c.
int S_WAV_CodecReadStream (snd_stream_t * stream, int bytes, void * buffer)
S_WAV_CodecReadStream.
Parameters
[in,out] stream
[in] bytes
[out] buffer
Returns
Definition at line 315 of file snd_codec_wav.c.
Variable Documentation
snd_codec_t wav_codec
Initial value:
=
{
    ".wav",
    S_WAV_CodecLoad,
    S_WAV_CodecOpenStream,
    S_WAV_CodecReadStream,
    S_WAV_CodecCloseStream,
    NULL
}
Definition at line 212 of file snd_codec_wav.c.
Referenced by S_CodecInit().