ET: Legacy: src/client/snd_dma.c File Reference
snd_dma.c File Reference
Main control for any streaming sound output device.
#include "snd_local.h"
#include "snd_codec.h"
#include "client.h"
Macros
#define SOUND_FULLVOLUME 80
#define SOUND_RANGE_DEFAULT 1250
#define MAX_SFX 4096
#define LOOP_HASH 128
#define UNDERWATER_BIT 16
Functions
void S_Update_ (void)
S_Update_.
void S_Base_StopAllSounds (void)
S_Base_StopAllSounds.
void S_StopStreamingSound (int stream)
Stops a streaming sound completely in its tracks.
void S_FreeStreamingSound (int stream)
Frees a streaming sound so that it can be used again, but does not terminate the sound.
void S_UpdateStreamingSounds (void)
S_UpdateStreamingSounds.
void S_Base_SoundInfo (void)
S_Base_SoundInfo.
void S_Base_SoundList (void)
S_Base_SoundList.
void S_ChannelFree (channel_t *v)
S_ChannelFree.
channel_t * S_ChannelMalloc (void)
S_ChannelMalloc.
void S_ChannelSetup (void)
S_ChannelSetup.
static long S_HashSFXName (const char *name)
S_HashSFXName.
static sfx_t * S_FindName (const char *name)
Will allocate a new sfx if it isn't found.
void S_Base_Reload (void)
S_Base_Reload.
void S_Base_DisableSounds (void)
Disables sounds until the next S_BeginRegistration. This is called when the hunk is cleared and the sounds are no longer valid.
sfxHandle_t S_Base_RegisterSound (const char *name, qboolean compressed)
Creates a default buzz sound if the file can't be loaded.
void S_Base_BeginRegistration (void)
S_Base_BeginRegistration.
void S_memoryLoad (sfx_t *sfx)
S_memoryLoad.
void S_SpatializeOrigin (vec3_t origin, int master_vol, int *left_vol, int *right_vol, float range, int no_attenuation)
Used for spatializing s_channels.
void S_Base_StartSoundEx (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfxHandle, int flags, int volume)
Validates the parms and ques the sound up if pos is NULL, the sound will be dynamically sourced from the entity Entchannel 0 will never override a playing sound.
void S_Base_StartSound (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfxHandle, int volume)
S_Base_StartSound.
void S_Base_StartLocalSound (sfxHandle_t sfxHandle, int channelNum, int volume)
S_Base_StartLocalSound.
void S_Base_ClearSounds (qboolean clearStreaming, qboolean clearMusic)
S_Base_ClearSounds.
void S_Base_ClearSoundBuffer (qboolean killStreaming)
If we are about to perform file access, clear the buffer so sound doesn't stutter.
void S_Base_ClearLoopingSounds (void)
S_Base_ClearLoopingSounds.
void S_Base_AddLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
Called during entity generation for a frame Include velocity in case I get around to doing doppler...
void S_Base_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
Called during entity generation for a frame Include velocity in case I get around to doing doppler...
void S_AddLoopSounds (void)
Spatialize all of the looping sounds. All sounds are on the same cycle, so any duplicates can just sum up the channel multipliers.
void S_ByteSwapRawSamples (int samples, int width, int s_channels, const byte *data)
If raw data has been loaded in little endien binary form, this must be done. If raw data was calculated, as with ADPCM, this should not be called.
void S_Base_RawSamples (int stream, int samples, int rate, int width, int s_channels, const byte *data, float lvol, float rvol)
Music streaming.
void S_Base_UpdateEntityPosition (int entnum, const vec3_t origin)
Let the sound system know where an entity currently is.
void S_Base_Respatialize (int entnum, const vec3_t head, vec3_t axis[3], int inwater)
Change the volumes of all the playing sounds for changes in their positions.
static qboolean S_ScanChannelStarts (void)
S_ScanChannelStarts.
void S_Base_Update (void)
Called once each time through the main loop.
void S_GetSoundtime (void)
S_GetSoundtime.
float S_StartStreamingSoundEx (const char *intro, const char *loop, int entnum, int channel, qboolean music, int param)
S_StartStreamingSoundEx.
float S_Base_StartStreamingSound (const char *intro, const char *loop, int entnum, int channel, int attenuation)
S_Base_StartStreamingSound.
void S_Base_StopEntStreamingSound (int entnum)
S_Base_StopEntStreamingSound.
void S_Base_FadeAllSounds (float targetVol, int time, qboolean stopsounds)
S_Base_FadeAllSounds.
void S_Base_FadeStreamingSound (float targetVol, int time, int stream)
S_Base_FadeStreamingSound.
float S_GetStreamingFade (streamingSound_t *ss)
S_GetStreamingFade.
void S_Base_StopBackgroundTrack (void)
S_Base_StopBackgroundTrack.
void S_Base_StartBackgroundTrack (const char *intro, const char *loop, int fadeupTime)
S_Base_StartBackgroundTrack.
int S_Base_GetVoiceAmplitude (int entnum)
S_Base_GetVoiceAmplitude.
int S_Base_GetSoundLength (sfxHandle_t sfxHandle)
Returns how long the sound lasts in milliseconds.
int S_Base_GetCurrentSoundTime (void)
For looped sound synchronisation.
void S_FreeOldestSound (void)
S_FreeOldestSound.
void S_Base_Shutdown (void)
S_Base_Shutdown.
qboolean S_Base_Init (soundInterface_t *si)
S_Base_Init.
Variables
streamingSound_t streamingSounds [MAX_STREAMING_SOUNDS]
channel_t s_channels [MAX_CHANNELS]
channel_t loop_channels [MAX_CHANNELS]
int numLoopChannels
static int s_soundStarted
static qboolean s_soundMuted
static float s_volStart
static float s_volTarget
static int s_volTime1
static int s_volTime2
static float s_volFadeFrac
static qboolean s_stopSounds
float s_volCurrent
dma_t dma
static int listener_number
static vec3_t listener_origin
static vec3_t listener_axis [3]
int s_soundtime
int s_paintedtime
static sfx_t knownSfx [MAX_SFX]
static int numSfx = 0
static sfx_t * sfxHash [LOOP_HASH]
cvar_t * s_testsound
cvar_t * s_show
cvar_t * s_mixahead
cvar_t * s_mixPreStep
cvar_t * s_debugStreams
static loopSound_t loopSounds [MAX_LOOP_SOUNDS]
static vec3_t entityPositions [MAX_GENTITIES]
static channel_t * freelist = NULL
static int numLoopSounds
int s_rawend [MAX_RAW_STREAMS]
portable_samplepair_t s_rawsamples [MAX_RAW_STREAMS][MAX_RAW_SAMPLES]
Detailed Description
Main control for any streaming sound output device.
Definition in file snd_dma.c.
Macro Definition Documentation
#define LOOP_HASH 128
Definition at line 85 of file snd_dma.c.
Referenced by S_Base_BeginRegistration(), S_Base_Init(), and S_HashSFXName().
#define MAX_SFX 4096
Definition at line 81 of file snd_dma.c.
Referenced by S_FindName().
#define SOUND_FULLVOLUME 80
Definition at line 53 of file snd_dma.c.
#define SOUND_RANGE_DEFAULT 1250
Definition at line 54 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_Respatialize(), and S_UpdateStreamingSounds().
#define UNDERWATER_BIT 16
Definition at line 922 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), and S_Base_AddRealLoopingSound().
Function Documentation
void S_AddLoopSounds (void)
Spatialize all of the looping sounds. All sounds are on the same cycle, so any duplicates can just sum up the channel multipliers.
Definition at line 1110 of file snd_dma.c.
Referenced by S_Base_Respatialize().
void S_Base_AddLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
Called during entity generation for a frame Include velocity in case I get around to doing doppler...
Parameters
origin
velocity
range
sfxHandle
volume
soundTime
Definition at line 934 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
Called during entity generation for a frame Include velocity in case I get around to doing doppler...
Parameters
[in] origin
[in] velocity
[in] range
[in] sfxHandle
[in] volume
soundTime - unused
Definition at line 1051 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_BeginRegistration (void)
S_Base_BeginRegistration.
Definition at line 501 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_ClearLoopingSounds (void)
S_Base_ClearLoopingSounds.
Definition at line 909 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_ClearSoundBuffer (qboolean killStreaming)
If we are about to perform file access, clear the buffer so sound doesn't stutter.
Parameters
killStreaming
Definition at line 883 of file snd_dma.c.
Referenced by S_Base_Init(), and S_Base_StopAllSounds().
void S_Base_ClearSounds (qboolean clearStreaming, qboolean clearMusic)
S_Base_ClearSounds.
Parameters
[in] clearStreaming
[in] clearMusic
Definition at line 807 of file snd_dma.c.
Referenced by S_Base_ClearSoundBuffer(), and S_Base_Init().
void S_Base_DisableSounds (void)
Disables sounds until the next S_BeginRegistration. This is called when the hunk is cleared and the sounds are no longer valid.
Definition at line 429 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_FadeAllSounds (float targetVol, int time, qboolean stopsounds)
S_Base_FadeAllSounds.
Parameters
[in] targetVol
[in] time
[in] stopsounds
Definition at line 1934 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_FadeStreamingSound (float targetVol, int time, int stream)
S_Base_FadeStreamingSound.
Parameters
[in] targetVol
[in] time
[in] stream
Definition at line 1965 of file snd_dma.c.
Referenced by S_Base_Init().
int S_Base_GetCurrentSoundTime (void)
For looped sound synchronisation.
Definition at line 2234 of file snd_dma.c.
Referenced by S_Base_Init().
int S_Base_GetSoundLength (sfxHandle_t sfxHandle)
Returns how long the sound lasts in milliseconds.
Parameters
sfxHandle
Returns
Definition at line 2221 of file snd_dma.c.
Referenced by S_Base_Init().
int S_Base_GetVoiceAmplitude (int entnum)
S_Base_GetVoiceAmplitude.
Parameters
entnum - unused
Returns
Note
TODO: not implemented
Definition at line 2211 of file snd_dma.c.
Referenced by S_Base_Init().
qboolean S_Base_Init (soundInterface_t * si)
S_Base_Init.
Parameters
[out] si
Returns
Definition at line 2303 of file snd_dma.c.
Referenced by S_Init().
void S_Base_RawSamples (int stream, int samples, int rate, int width, int s_channels, const byte * data, float lvol, float rvol)
Music streaming.
Parameters
[in] stream
[in] samples
[in] rate
[in] width
[in] s_channels
[in,out] data
[in] lvol
[in] rvol
Definition at line 1257 of file snd_dma.c.
Referenced by S_Base_Init(), and S_UpdateStreamingSounds().
sfxHandle_t S_Base_RegisterSound (const char * name, qboolean compressed)
Creates a default buzz sound if the file can't be loaded.
Parameters
[in] name
[in] compressed
Returns
Todo:
: non WAV
Definition at line 441 of file snd_dma.c.
Referenced by S_Base_BeginRegistration(), and S_Base_Init().
void S_Base_Reload (void)
S_Base_Reload.
Definition at line 404 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_Respatialize (int entnum, const vec3_t head, vec3_t axis[3], int inwater)
Change the volumes of all the playing sounds for changes in their positions.
Parameters
[in] entnum
[in] head
[in] axis
inwater - unused
Definition at line 1408 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_Shutdown (void)
S_Base_Shutdown.
Definition at line 2282 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_SoundInfo (void)
S_Base_SoundInfo.
Definition at line 109 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_SoundList (void)
S_Base_SoundList.
Definition at line 201 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_StartBackgroundTrack (const char * intro, const char * loop, int fadeupTime)
S_Base_StartBackgroundTrack.
Parameters
[in] intro
[in] loop
[in] fadeupTime
Definition at line 2043 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_StartLocalSound (sfxHandle_t sfxHandle, int channelNum, int volume)
S_Base_StartLocalSound.
Parameters
[in] sfxHandle
[in] channelNum
[in] volume
Definition at line 786 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_StartSound (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfxHandle, int volume)
S_Base_StartSound.
Parameters
[in] origin
[in] entnum
[in] entchannel
[in] sfxHandle
[in] volume
Definition at line 775 of file snd_dma.c.
Referenced by S_Base_Init(), and S_Base_StartLocalSound().
void S_Base_StartSoundEx (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfxHandle, int flags, int volume)
Validates the parms and ques the sound up if pos is NULL, the sound will be dynamically sourced from the entity Entchannel 0 will never override a playing sound.
Parameters
[in] origin
[in] entnum
[in] entchannel
[in] sfxHandle
[in] flags
[in] volume
Definition at line 623 of file snd_dma.c.
Referenced by S_Base_Init(), and S_Base_StartSound().
float S_Base_StartStreamingSound (const char * intro, const char * loop, int entnum, int channel, int attenuation)
S_Base_StartStreamingSound.
Parameters
[in] intro
[in] loop
[in] entnum
[in] channel
[in] attenuation
Returns
Definition at line 1862 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_StopAllSounds (void)
S_Base_StopAllSounds.
Definition at line 896 of file snd_dma.c.
Referenced by S_Base_DisableSounds(), S_Base_Init(), S_Base_Reload(), and S_GetSoundtime().
void S_Base_StopBackgroundTrack (void)
S_Base_StopBackgroundTrack.
Definition at line 2032 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_StopEntStreamingSound (int entnum)
S_Base_StopEntStreamingSound.
Parameters
[in] entnum
Definition at line 1908 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_Update (void)
Called once each time through the main loop.
Definition at line 1498 of file snd_dma.c.
Referenced by S_Base_Init().
void S_Base_UpdateEntityPosition (int entnum, const vec3_t origin)
Let the sound system know where an entity currently is.
Parameters
[in] entnum
[in] origin
Definition at line 1392 of file snd_dma.c.
Referenced by S_Base_Init().
void S_ByteSwapRawSamples (int samples, int width, int s_channels, const byte * data)
If raw data has been loaded in little endien binary form, this must be done. If raw data was calculated, as with ADPCM, this should not be called.
Parameters
[in] samples
[in] width
[in] s_channels
[in,out] data
Definition at line 1222 of file snd_dma.c.
void S_ChannelFree (channel_t * v)
S_ChannelFree.
Parameters
[in,out] v
Definition at line 232 of file snd_dma.c.
Referenced by S_Base_ClearSounds(), S_Base_StartSoundEx(), and S_ScanChannelStarts().
channel_t* S_ChannelMalloc (void)
S_ChannelMalloc.
Returns
Definition at line 243 of file snd_dma.c.
Referenced by S_Base_StartSoundEx().
void S_ChannelSetup (void)
S_ChannelSetup.
Definition at line 260 of file snd_dma.c.
Referenced by S_Base_ClearSounds().
static sfx_t* S_FindName (const char * name) static
Will allocate a new sfx if it isn't found.
Parameters
[in] name
Returns
Definition at line 317 of file snd_dma.c.
Referenced by S_Base_RegisterSound().
void S_FreeOldestSound (void)
S_FreeOldestSound.
Definition at line 2242 of file snd_dma.c.
Referenced by SND_malloc().
void S_FreeStreamingSound (int stream)
Frees a streaming sound so that it can be used again, but does not terminate the sound.
Parameters
stream
Definition at line 1871 of file snd_dma.c.
Referenced by S_StopStreamingSound(), and S_UpdateStreamingSounds().
void S_GetSoundtime (void)
S_GetSoundtime.
Definition at line 1534 of file snd_dma.c.
Referenced by S_Update_().
float S_GetStreamingFade (streamingSound_t * ss)
S_GetStreamingFade.
Parameters
[in] ss
Returns
Definition at line 2008 of file snd_dma.c.
Referenced by S_UpdateStreamingSounds().
static long S_HashSFXName (const char * name) static
S_HashSFXName.
Parameters
[in] name
Returns
a hash value for the sfx name
Definition at line 288 of file snd_dma.c.
Referenced by S_FindName().
void S_memoryLoad (sfx_t * sfx)
S_memoryLoad.
Parameters
[in,out] sfx
Definition at line 520 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_RegisterSound(), S_Base_Reload(), and S_Base_StartSoundEx().
static qboolean S_ScanChannelStarts (void) static
S_ScanChannelStarts.
Returns
qtrue if any new sounds were started since the last mix
Definition at line 1463 of file snd_dma.c.
Referenced by S_Update_().
void S_SpatializeOrigin (vec3_t origin, int master_vol, int * left_vol, int * right_vol, float range, int no_attenuation)
Used for spatializing s_channels.
Parameters
[in] origin
[in] master_vol
[out] left_vol
[out] right_vol
[in] range
[in] no_attenuation
Definition at line 541 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_Respatialize(), and S_UpdateStreamingSounds().
float S_StartStreamingSoundEx (const char * intro, const char * loop, int entnum, int channel, qboolean music, int param)
S_StartStreamingSoundEx.
Parameters
[in] intro
[in] loop
[in] entnum
[in] channel
[in] music
[in] param
Returns
Definition at line 1701 of file snd_dma.c.
Referenced by S_Base_StartBackgroundTrack(), S_Base_StartStreamingSound(), and S_UpdateStreamingSounds().
void S_StopStreamingSound (int stream)
Stops a streaming sound completely in its tracks.
Parameters
stream
Definition at line 1898 of file snd_dma.c.
Referenced by S_Base_ClearSounds(), S_Base_StopBackgroundTrack(), S_Base_StopEntStreamingSound(), S_StartStreamingSoundEx(), and S_UpdateStreamingSounds().
void S_Update_ (void)
S_Update_.
Definition at line 1593 of file snd_dma.c.
Referenced by S_Base_Update().
void S_UpdateStreamingSounds (void)
S_UpdateStreamingSounds.
Todo:
: Implement a rewind?
Definition at line 2051 of file snd_dma.c.
Referenced by S_Base_ClearSounds(), and S_Base_Update().
Variable Documentation
dma_t dma
Definition at line 70 of file snd_dma.c.
Referenced by CL_OpenAVIForWriting(), CL_WriteWaveHeader(), ResampleSfx(), ResampleSfxRaw(), S_TransferPaintBuffer(), S_TransferStereo16(), SNDDMA_AudioCallback(), SNDDMA_Init(), and SNDDMA_Shutdown().
vec3_t entityPositions[MAX_GENTITIES] static
Definition at line 95 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), S_Base_Respatialize(), S_Base_UpdateEntityPosition(), and S_UpdateStreamingSounds().
channel_t* freelist = NULL static
Definition at line 96 of file snd_dma.c.
Referenced by S_ChannelMalloc().
sfx_t knownSfx[MAX_SFX] static
Definition at line 82 of file snd_dma.c.
Referenced by S_Base_RegisterSound().
vec3_t listener_axis[3] static
Definition at line 74 of file snd_dma.c.
Referenced by S_Base_Respatialize(), and S_SpatializeOrigin().
int listener_number static
Definition at line 72 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), S_Base_Respatialize(), S_Base_StartLocalSound(), and S_Base_StartSoundEx().
vec3_t listener_origin static
Definition at line 73 of file snd_dma.c.
Referenced by S_Base_Respatialize(), and S_SpatializeOrigin().
channel_t loop_channels[MAX_CHANNELS]
Definition at line 57 of file snd_dma.c.
Referenced by S_PaintChannels().
loopSound_t loopSounds[MAX_LOOP_SOUNDS] static
Definition at line 94 of file snd_dma.c.
int numLoopChannels
Definition at line 58 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_ClearLoopingSounds(), S_Base_ClearSounds(), and S_PaintChannels().
int numLoopSounds static
Definition at line 97 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_ClearLoopingSounds(), and S_Base_ClearSounds().
int numSfx = 0 static
Definition at line 83 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_BeginRegistration(), S_Base_GetSoundLength(), S_Base_Reload(), S_Base_Shutdown(), S_Base_SoundList(), S_Base_StartLocalSound(), S_Base_StartSoundEx(), S_FindName(), and S_FreeOldestSound().
channel_t s_channels[MAX_CHANNELS]
Definition at line 56 of file snd_dma.c.
Referenced by S_Base_ClearSounds(), S_Base_Respatialize(), S_Base_StartSoundEx(), S_Base_Update(), S_ChannelSetup(), S_PaintChannels(), and S_ScanChannelStarts().
cvar_t* s_debugStreams
Definition at line 92 of file snd_dma.c.
cvar_t* s_mixahead
Definition at line 90 of file snd_dma.c.
cvar_t* s_mixPreStep
Definition at line 91 of file snd_dma.c.
int s_paintedtime
Definition at line 77 of file snd_dma.c.
Referenced by S_Base_Init(), S_Base_StartSoundEx(), S_Base_Update(), S_GetSoundtime(), S_PaintChannels(), S_ScanChannelStarts(), S_TransferPaintBuffer(), and S_TransferStereo16().
int s_rawend[MAX_RAW_STREAMS]
Definition at line 99 of file snd_dma.c.
Referenced by S_Base_RawSamples(), S_PaintChannels(), S_StopStreamingSound(), and S_UpdateStreamingSounds().
portable_samplepair_t s_rawsamples[MAX_RAW_STREAMS][MAX_RAW_SAMPLES]
Definition at line 100 of file snd_dma.c.
Referenced by S_PaintChannels().
cvar_t* s_show
Definition at line 89 of file snd_dma.c.
qboolean s_soundMuted static
Definition at line 61 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_BeginRegistration(), S_Base_DisableSounds(), S_Base_Init(), S_Base_RawSamples(), S_Base_Respatialize(), S_Base_SoundInfo(), S_Base_StartLocalSound(), S_Base_StartSoundEx(), S_Base_Update(), and S_Update_().
int s_soundStarted static
Definition at line 60 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_ClearSoundBuffer(), S_Base_ClearSounds(), S_Base_Init(), S_Base_RawSamples(), S_Base_RegisterSound(), S_Base_Reload(), S_Base_Respatialize(), S_Base_Shutdown(), S_Base_SoundInfo(), S_Base_StartLocalSound(), S_Base_StartSoundEx(), S_Base_StopAllSounds(), S_Base_Update(), and S_Update_().
int s_soundtime
Definition at line 76 of file snd_dma.c.
Referenced by S_Base_FadeAllSounds(), S_Base_FadeStreamingSound(), S_Base_GetCurrentSoundTime(), S_Base_Init(), S_Base_RawSamples(), S_GetSoundtime(), S_GetStreamingFade(), S_StartStreamingSoundEx(), S_Update_(), and S_UpdateStreamingSounds().
qboolean s_stopSounds static
Definition at line 67 of file snd_dma.c.
Referenced by S_Base_FadeAllSounds(), and S_Update_().
cvar_t* s_testsound
Definition at line 88 of file snd_dma.c.
Referenced by S_TransferPaintBuffer().
float s_volCurrent
Definition at line 68 of file snd_dma.c.
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_FadeAllSounds(), S_PaintChannels(), S_Update_(), and S_UpdateStreamingSounds().
float s_volFadeFrac static
Definition at line 66 of file snd_dma.c.
Referenced by S_Update_().
float s_volStart static
Definition at line 64 of file snd_dma.c.
Referenced by S_Base_FadeAllSounds(), and S_Update_().
float s_volTarget static
Definition at line 64 of file snd_dma.c.
Referenced by S_Base_FadeAllSounds(), and S_Update_().
int s_volTime1 static
Definition at line 65 of file snd_dma.c.
Referenced by S_Base_FadeAllSounds(), and S_Update_().
int s_volTime2 static
Definition at line 65 of file snd_dma.c.
Referenced by S_Base_FadeAllSounds(), and S_Update_().
sfx_t* sfxHash[LOOP_HASH] static
Definition at line 86 of file snd_dma.c.
streamingSound_t streamingSounds[MAX_STREAMING_SOUNDS]
Definition at line 46 of file snd_dma.c.