ET: Legacy: src/client/snd_mem.c File Reference
snd_mem.c File Reference
Sound caching.
#include "snd_local.h"
#include "snd_codec.h"
Macros
#define DEF_COMSOUNDMEGS "160"
Functions
void SND_Com_Dealloc (sndBuffer *v)
sndBuffer * SND_malloc (void)
SND_malloc.
void SND_setup (void)
SND_setup.
void SND_shutdown (void)
SND_shutdown.
static int ResampleSfx (sfx_t *sfx, int channels, int inrate, int inwidth, int samples, byte *data, qboolean compressed)
Resample / decimate to the current source rate.
static int ResampleSfxRaw (short *sfx, int channels, int inrate, int inwidth, int samples, byte *data)
Resample / decimate to the current source rate.
qboolean S_LoadSound (sfx_t *sfx)
The filename may be different than sfx->name in the case of a forced fallback of a player specific sound.
void S_DisplayFreeMemory (void)
S_DisplayFreeMemory.
Variables
static sndBuffer * buffer = NULL
static sndBuffer * freelist = NULL
static int inUse = 0
static int totalInUse = 0
short * sfxScratchBuffer = NULL
sfx_t * sfxScratchPointer = NULL
int sfxScratchIndex = 0
Detailed Description
Sound caching.
Definition in file snd_mem.c.
Macro Definition Documentation
#define DEF_COMSOUNDMEGS "160"
Definition at line 39 of file snd_mem.c.
Referenced by SND_setup().
Function Documentation
static int ResampleSfx (sfx_t * sfx, int channels, int inrate, int inwidth, int samples, byte * data, qboolean compressed) static
Resample / decimate to the current source rate.
Parameters
[in] sfx
[in] channels
[in] inrate
[in] inwidth
[in] samples
[in] data
compressed - unused
Returns
Definition at line 146 of file snd_mem.c.
Referenced by S_LoadSound().
static int ResampleSfxRaw (short * sfx, int channels, int inrate, int inwidth, int samples, byte * data) static
Resample / decimate to the current source rate.
Parameters
[in] sfx
[in] channels
[in] inrate
[in] inwidth
[in] samples
[in] data
Returns
Definition at line 204 of file snd_mem.c.
Referenced by S_LoadSound().
void S_DisplayFreeMemory (void)
S_DisplayFreeMemory.
Definition at line 335 of file snd_mem.c.
Referenced by S_Base_SoundList().
qboolean S_LoadSound (sfx_t * sfx)
The filename may be different than sfx->name in the case of a forced fallback of a player specific sound.
Parameters
[in,out] sfx
Returns
Definition at line 240 of file snd_mem.c.
Referenced by S_memoryLoad().
void SND_Com_Dealloc (sndBuffer * v)
Definition at line 56 of file snd_mem.c.
Referenced by S_FreeOldestSound().
sndBuffer* SND_malloc (void)
SND_malloc.
Returns
Definition at line 67 of file snd_mem.c.
Referenced by encodeMuLaw(), encodeWavelet(), ResampleSfx(), and S_AdpcmEncodeSound().
void SND_setup (void)
SND_setup.
Definition at line 89 of file snd_mem.c.
Referenced by S_Base_BeginRegistration().
void SND_shutdown (void)
SND_shutdown.
Definition at line 129 of file snd_mem.c.
Referenced by S_Base_Shutdown().
Variable Documentation
sndBuffer* buffer = NULL static
Definition at line 47 of file snd_mem.c.
Referenced by SND_setup().
sndBuffer* freelist = NULL static
Definition at line 48 of file snd_mem.c.
Referenced by SND_malloc().
int inUse = 0 static
Definition at line 49 of file snd_mem.c.
Referenced by S_DisplayFreeMemory(), SND_Com_Dealloc(), SND_malloc(), and SND_setup().
short* sfxScratchBuffer = NULL
Definition at line 52 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), S_PaintChannelFromWavelet(), SND_setup(), and SND_shutdown().
int sfxScratchIndex = 0
Definition at line 54 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), and S_PaintChannelFromWavelet().
sfx_t* sfxScratchPointer = NULL
Definition at line 53 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), and S_PaintChannelFromWavelet().
int totalInUse = 0 static
Definition at line 50 of file snd_mem.c.
Referenced by S_DisplayFreeMemory(), and SND_malloc().