ET: Legacy: src/client/snd_public.h File Reference
snd_public.h File Reference
Macros
#define QUEUED_PLAY_ONCE -1
#define QUEUED_PLAY_LOOPED -2
#define QUEUED_PLAY_ONCE_SILENT -3
when done it goes quiet
Functions
void S_Init (void)
Initiates the sound system.
void S_Shutdown (void)
Destroys the sound system.
void S_Reload (void)
S_Reload.
void S_StartSound (vec3_t origin, int entNum, int entchannel, sfxHandle_t sfxHandle, int volume)
S_StartSound.
void S_StartSoundEx (vec3_t origin, int entNum, int entchannel, sfxHandle_t sfxHandle, int flags, int volume)
S_StartSoundEx.
void S_StartLocalSound (sfxHandle_t sfxHandle, int channelNum, int volume)
S_StartLocalSound.
void S_StartBackgroundTrack (const char *intro, const char *loop, int fadeUpTime)
S_StartBackgroundTrack.
void S_StopBackgroundTrack (void)
S_StopBackgroundTrack.
float S_StartStreamingSound (const char *intro, const char *loop, int entNum, int channel, int attenuation)
S_StartStreamingSound.
void S_StopEntStreamingSound (int entNum)
S_StopEntStreamingSound.
void S_FadeStreamingSound (float targetvol, int time, int stream)
S_FadeStreamingSound.
void S_RawSamples (int stream, int samples, int rate, int width, int channels, const byte *data, float lvol, float rvol)
S_RawSamples.
void S_ClearSounds (qboolean clearStreaming, qboolean clearMusic)
S_ClearSounds.
void S_StopAllSounds (void)
S_StopAllSounds.
void S_FadeAllSounds (float targetVol, int time, qboolean stopSounds)
S_FadeAllSounds.
void S_ClearLoopingSounds (void)
S_ClearLoopingSounds.
void S_AddLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
S_AddLoopingSound.
void S_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
S_AddRealLoopingSound.
void S_Respatialize (int entNum, const vec3_t origin, vec3_t axis[3], int inwater)
S_Respatialize.
void S_UpdateEntityPosition (int entNum, const vec3_t origin)
S_UpdateEntityPosition.
void S_Update (void)
S_Update.
void S_DisableSounds (void)
S_DisableSounds.
void S_BeginRegistration (void)
S_BeginRegistration.
sfxHandle_t S_RegisterSound (const char *name, qboolean compressed)
S_RegisterSound.
void S_DisplayFreeMemory (void)
S_DisplayFreeMemory.
void S_ClearSoundBuffer (qboolean killStreaming)
S_ClearSoundBuffer.
int S_GetVoiceAmplitude (int entNum)
S_GetVoiceAmplitude.
int S_GetSoundLength (sfxHandle_t sfxHandle)
Returns how long the sound lasts in milliseconds.
int S_GetCurrentSoundTime (void)
For looped sound synchronisation.
Macro Definition Documentation
#define QUEUED_PLAY_LOOPED -2
Definition at line 40 of file snd_public.h.
Referenced by S_UpdateStreamingSounds().
#define QUEUED_PLAY_ONCE -1
Definition at line 39 of file snd_public.h.
Referenced by S_UpdateStreamingSounds().
#define QUEUED_PLAY_ONCE_SILENT -3
when done it goes quiet
Definition at line 41 of file snd_public.h.
Referenced by S_UpdateStreamingSounds().
Function Documentation
void S_AddLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
S_AddLoopingSound.
Parameters
[in] origin
[in] velocity
[in] range
[in] sfxHandle
[in] volume
[in] soundTime
Definition at line 399 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_AddRealLoopingSound (const vec3_t origin, const vec3_t velocity, int range, sfxHandle_t sfxHandle, int volume, int soundTime)
S_AddRealLoopingSound.
Parameters
[in] origin
[in] velocity
[in] range
[in] sfxHandle
[in] volume
[in] soundTime
Definition at line 418 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_BeginRegistration (void)
S_BeginRegistration.
Definition at line 501 of file snd_main.c.
Referenced by CL_StartHunkUsers(), and CL_Vid_Restart_f().
void S_ClearLoopingSounds (void)
S_ClearLoopingSounds.
Definition at line 382 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_ClearSoundBuffer (qboolean killStreaming)
S_ClearSoundBuffer.
Parameters
[in] killStreaming
killStreaming
Definition at line 531 of file snd_main.c.
void S_ClearSounds (qboolean clearStreaming, qboolean clearMusic)
S_ClearSounds.
Parameters
[in] clearStreaming
[in] clearMusic
Definition at line 346 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_DisableSounds (void)
S_DisableSounds.
Definition at line 490 of file snd_main.c.
Referenced by CL_ShutdownAll().
void S_DisplayFreeMemory (void)
S_DisplayFreeMemory.
Definition at line 335 of file snd_mem.c.
Referenced by S_Base_SoundList().
void S_FadeAllSounds (float targetVol, int time, qboolean stopSounds)
S_FadeAllSounds.
Parameters
[in] targetVol
[in] time
[in] stopSounds
Definition at line 371 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void S_FadeStreamingSound (float targetvol, int time, int stream)
S_FadeStreamingSound.
Parameters
[in] targetvol
[in] time
[in] stream
Definition at line 313 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
int S_GetCurrentSoundTime (void)
For looped sound synchronisation.
Definition at line 598 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
int S_GetSoundLength (sfxHandle_t sfxHandle)
Returns how long the sound lasts in milliseconds.
Parameters
sfxHandle
Returns
Returns how long the sound lasts in milliseconds.
Parameters
sfxHandle
Returns
Definition at line 583 of file snd_main.c.
int S_GetVoiceAmplitude (int entNum)
S_GetVoiceAmplitude.
Parameters
[in] entNum
Returns
Definition at line 566 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_Init (void)
Initiates the sound system.
Definition at line 810 of file snd_main.c.
Referenced by CL_StartHunkUsers().
void S_RawSamples (int stream, int samples, int rate, int width, int channels, const byte * data, float lvol, float rvol)
S_RawSamples.
Parameters
[in] stream
[in] samples
[in] rate
[in] width
[in] channels
[in] data
[in] lvol
[in] rvol
Definition at line 332 of file snd_main.c.
Referenced by CIN_DecodeSoundMono22(), CIN_DecodeSoundMono48(), CIN_DecodeSoundStereo22(), and CIN_DecodeSoundStereo48().
sfxHandle_t S_RegisterSound (const char * name, qboolean compressed)
S_RegisterSound.
Parameters
[in] name
[in] compressed
Returns
Parameters
name
compressed
Returns
Note
bk001119 - added boolean flag, match client/snd_public.h
Definition at line 515 of file snd_main.c.
void S_Reload (void)
S_Reload.
Note
Unused
Definition at line 890 of file snd_main.c.
void S_Respatialize (int entNum, const vec3_t origin, vec3_t axis[3], int inwater)
S_Respatialize.
Parameters
[in] entNum
[in] origin
[in] axis
[in] inwater
Definition at line 435 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_Shutdown (void)
Destroys the sound system.
Definition at line 901 of file snd_main.c.
Referenced by CL_Snd_Shutdown().
void S_StartBackgroundTrack (const char * intro, const char * loop, int fadeUpTime)
S_StartBackgroundTrack.
Parameters
[in] intro
[in] loop
[in] fadeUpTime
Definition at line 253 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and S_UpdateStreamingSounds().
void S_StartLocalSound (sfxHandle_t sfxHandle, int channelNum, int volume)
S_StartLocalSound.
Parameters
[in] sfxHandle
[in] channelNum
[in] volume
sfxHandle
channelNum
volume
Definition at line 239 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void S_StartSound (vec3_t origin, int entNum, int entchannel, sfxHandle_t sfxHandle, int volume)
S_StartSound.
Parameters
[in] origin
[in] entNum
[in] entchannel
[in] sfxHandle
[in] volume
Definition at line 206 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_StartSoundEx (vec3_t origin, int entNum, int entchannel, sfxHandle_t sfxHandle, int flags, int volume)
S_StartSoundEx.
Parameters
[in] origin
[in] entNum
[in] entchannel
[in] sfxHandle
[in] flags
[in] volume
Definition at line 224 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
float S_StartStreamingSound (const char * intro, const char * loop, int entNum, int channel, int attenuation)
S_StartStreamingSound.
Parameters
[in] intro
[in] loop
[in] entNum
[in] channel
[in] attenuation
Returns
Definition at line 282 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_StopAllSounds (void)
S_StopAllSounds.
Definition at line 357 of file snd_main.c.
Referenced by CIN_FreeCinematic(), CIN_PlayCinematic(), CL_Connect_f(), CL_Frame(), CL_KeyEvent(), CL_ParseDownload(), CL_StopVideo_f(), CL_Vid_Restart_f(), Com_GetAutoUpdate(), S_Base_FadeAllSounds(), S_Init(), S_Update_(), and SCR_DrawScreenField().
void S_StopBackgroundTrack (void)
S_StopBackgroundTrack.
Definition at line 265 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
void S_StopEntStreamingSound (int entNum)
S_StopEntStreamingSound.
Parameters
[in] entNum
Definition at line 299 of file snd_main.c.
Referenced by CL_CgameSystemCalls().
void S_Update (void)
S_Update.
Definition at line 460 of file snd_main.c.
Referenced by CL_Frame().
void S_UpdateEntityPosition (int entNum, const vec3_t origin)
S_UpdateEntityPosition.
Parameters
[in] entNum
[in] origin
Definition at line 449 of file snd_main.c.
Referenced by CL_CgameSystemCalls().