ET: Legacy: displayContextDef_t Struct Reference
displayContextDef_t Struct Reference
#include <ui_shared.h>
Data Fields
qhandle_t(* registerShaderNoMip)(const char *p)
void(* setColor)(const vec4_t v)
void(* drawHandlePic)(float x, float y, float w, float h, qhandle_t asset)
void(* drawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void(* drawText)(float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
void(* drawTextExt)(float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
int(* textWidth)(const char *text, float scale, int limit)
int(* textWidthExt)(const char *text, float scale, int limit, fontHelper_t *font)
int(* multiLineTextWidth)(const char *text, float scale, int limit)
int(* textHeight)(const char *text, float scale, int limit)
int(* textHeightExt)(const char *text, float scale, int limit, fontHelper_t *font)
int(* multiLineTextHeight)(const char *text, float scale, int limit)
void(* textFont)(int font)
qhandle_t(* registerModel)(const char *p)
void(* modelBounds)(qhandle_t model, vec3_t min, vec3_t max)
void(* fillRect)(float x, float y, float w, float h, const vec4_t color)
void(* drawRect)(float x, float y, float w, float h, float size, const vec4_t color)
void(* drawSides)(float x, float y, float w, float h, float size)
void(* drawTopBottom)(float x, float y, float w, float h, float size)
void(* clearScene)(void)
void(* addRefEntityToScene)(const refEntity_t *re)
void(* renderScene)(const refdef_t *fd)
void(* registerFont)(const char *pFontname, int pointSize, void *font)
void(* ownerDrawItem)(float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, int special, float scale, vec4_t color, qhandle_t shader, int textStyle)
float(* getValue)(int ownerDraw, int type)
qboolean(* ownerDrawVisible)(int flags)
void(* runScript)(char **p)
void(* getTeamColor)(vec4_t *color)
void(* getCVarString)(const char *cvar, char *buffer, int bufsize)
float(* getCVarValue)(const char *cvar)
void(* setCVar)(const char *cvar, const char *value)
void(* drawTextWithCursor)(float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style)
void(* drawTextWithCursorExt)(float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style, fontHelper_t *font)
void(* setOverstrikeMode)(qboolean b)
qboolean(* getOverstrikeMode)(void)
void(* startLocalSound)(sfxHandle_t sfx, int channelNum)
qboolean(* ownerDrawHandleKey)(int ownerDraw, int flags, int *special, int key)
int(* feederCount)(int feederID)
const char *(* feederItemText)(int feederID, int index, int column, qhandle_t *handles, int *numhandles)
const char *(* fileText)(const char *fileName)
qhandle_t(* feederItemImage)(int feederID, int index)
void(* feederSelection)(int feederID, int index)
qboolean(* feederSelectionClick)(itemDef_t *item)
void(* feederAddItem)(int feederID, const char *name, int index)
const char *(* translateString)(const char *string)
void(* checkAutoUpdate)(void)
void(* getAutoUpdate)(void)
void(* keynumToStringBuf)(int keynum, char *buf, int buflen)
void(* getBindingBuf)(int keynum, char *buf, int buflen)
void(* getKeysForBinding)(const char *binding, int *key1, int *key2)
qboolean(* keyIsDown)(int keynum)
void(* getClipboardData)(char *buf, size_t bufsize)
void(* setBinding)(int keynum, const char *binding)
void(* executeText)(int exec_when, const char *text)
void(* Error)(int level, const char *error,...) __attribute__((noreturn
void(* format)(printf, 2, 3)))
void(* Print)(const char *msg,...) __attribute__((format(printf
void(*) void(* Pause)(qboolean b)
int(* ownerDrawWidth)(int ownerDraw, float scale)
sfxHandle_t(* registerSound)(const char *name, qboolean compressed)
void(* startBackgroundTrack)(const char *intro, const char *loop, int fadeupTime)
void(* stopBackgroundTrack)(void)
int(* playCinematic)(const char *name, float x, float y, float w, float h)
void(* stopCinematic)(int handle)
void(* drawCinematic)(int handle, float x, float y, float w, float h)
void(* runCinematicFrame)(int handle)
const char *(* descriptionForCampaign)(void)
const char *(* nameForCampaign)(void)
void(* add2dPolys)(polyVert_t *verts, int numverts, qhandle_t hShader)
void(* updateScreen)(void)
void(* getHunkData)(int *hunkused, int *hunkexpected)
int(* getConfigString)(int index, char *buff, size_t buffsize)
float yscale
float xscale
float bias
int realTime
int frameTime
int cursorx
int cursory
qboolean debug
cachedAssets_t Assets
glconfig_t glconfig
qhandle_t whiteShader
qhandle_t gradientImage
qhandle_t cursor
float FPS
Detailed Description
Definition at line 459 of file ui_shared.h.
Field Documentation
void(* displayContextDef_t::add2dPolys) (polyVert_t *verts, int numverts, qhandle_t hShader)
Definition at line 534 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), and UI_Init().
void(* displayContextDef_t::addRefEntityToScene) (const refEntity_t *re)
Definition at line 481 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Model_Paint(), and UI_Init().
cachedAssets_t displayContextDef_t::Assets
Definition at line 548 of file ui_shared.h.
Referenced by Asset_Parse(), AssetCache(), CG_AssetCache(), CG_DrawConnectScreen(), CG_Text_Height(), CG_Text_Paint(), CG_Text_PaintWithCursor(), CG_Text_Width(), GradientBar_Paint(), Item_CheckBox_Paint(), Item_ListBox_Paint(), Item_SetFocus(), Item_Slider_Paint(), Menu_Init(), Multiline_Text_Height(), Multiline_Text_Width(), Script_SetEditFocus(), Script_SetFocus(), Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), Text_Width(), UI_DrawCrosshair(), UI_DrawEffects(), UI_DrawLoadPanel(), UI_FeederItemText(), UI_Refresh(), and UI_Shutdown().
float displayContextDef_t::bias
Definition at line 541 of file ui_shared.h.
Referenced by UI_Init().
void(* displayContextDef_t::checkAutoUpdate) (void)
Definition at line 506 of file ui_shared.h.
Referenced by Script_CheckAutoUpdate(), and UI_Init().
void(* displayContextDef_t::clearScene) (void)
Definition at line 480 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Model_Paint(), and UI_Init().
qhandle_t displayContextDef_t::cursor
Definition at line 553 of file ui_shared.h.
int displayContextDef_t::cursorx
Definition at line 544 of file ui_shared.h.
Referenced by BG_CursorInRect(), CG_CommandCentreSpawnPointClick(), CG_Debriefing_Draw(), CG_DemoControlButtonDown(), CG_Draw2D(), CG_DrawConnectScreen(), CG_DrawDemoControls(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), CG_LimboPanel_Draw(), CG_SpeakerEditorDraw(), CG_windowDraw(), Item_Bind_HandleKey(), Item_CheckBox_HandleKey(), Item_Combo_Paint(), Item_ListBox_HandleKey(), Item_ListBox_ThumbDrawPosition(), Item_MouseActivate(), Item_Multi_HandleKey(), Item_Scroll_ListBox_ThumbFunc(), Item_Scroll_Slider_ThumbFunc(), Item_Slider_HandleKey(), Item_StartCapture(), Item_YesNo_HandleKey(), Menu_HandleKey(), Menu_PaintAll(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), Menus_HandleOOBClick(), UI_FeederSelectionClick(), UI_MouseEvent(), UI_Refresh(), UI_SetActiveMenu(), and vmMain().
int displayContextDef_t::cursory
Definition at line 545 of file ui_shared.h.
Referenced by BG_CursorInRect(), CG_CommandCentreSpawnPointClick(), CG_Debriefing_Draw(), CG_Draw2D(), CG_DrawConnectScreen(), CG_DrawDemoControls(), CG_DrawMapEntity(), CG_DrawSpawnPointInfo(), CG_LimboPanel_Draw(), CG_SpeakerEditorDraw(), CG_windowDraw(), Item_Bind_HandleKey(), Item_CheckBox_HandleKey(), Item_Combo_Paint(), Item_ListBox_HandleKey(), Item_ListBox_ThumbDrawPosition(), Item_MouseActivate(), Item_Multi_HandleKey(), Item_Scroll_ListBox_ThumbFunc(), Item_Slider_HandleKey(), Item_StartCapture(), Item_YesNo_HandleKey(), Menu_HandleKey(), Menu_PaintAll(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), Menus_HandleOOBClick(), UI_FeederSelectionClick(), UI_MouseEvent(), UI_Refresh(), UI_SetActiveMenu(), and vmMain().
qboolean displayContextDef_t::debug
Definition at line 546 of file ui_shared.h.
const char*(* displayContextDef_t::descriptionForCampaign) (void)
Definition at line 532 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), CG_LoadPanel_RenderMissionDescriptionText(), and UI_Init().
void(* displayContextDef_t::drawCinematic) (int handle, float x, float y, float w, float h)
Definition at line 528 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::drawHandlePic) (float x, float y, float w, float h, qhandle_t asset)
Definition at line 463 of file ui_shared.h.
Referenced by BG_PanelButtonsRender_Img(), CG_DrawConnectScreen(), CG_LoadHudMenu(), CG_LoadPanel_DrawPin(), GradientBar_Paint(), Item_CheckBox_Paint(), Item_ListBox_Paint(), Item_Slider_Paint(), Menu_Paint(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::drawRect) (float x, float y, float w, float h, float size, const vec4_t color)
Definition at line 477 of file ui_shared.h.
Referenced by BG_PanelButtonsRender_Img(), BG_PanelButtonsRender_TextExt(), CG_LoadHudMenu(), Item_Combo_Paint(), Item_ListBox_Paint(), Item_Paint(), Menu_Paint(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::drawSides) (float x, float y, float w, float h, float size)
Definition at line 478 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::drawStretchPic) (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 464 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), and UI_Init().
void(* displayContextDef_t::drawText) (float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
Definition at line 465 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Bind_Paint(), Item_CheckBox_Paint(), Item_Combo_Paint(), Item_ListBox_Paint(), Item_Multi_Paint(), Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), Item_Text_Wrapped_Paint(), Item_TextField_Paint(), Item_YesNo_Paint(), Menu_PaintAll(), UI_DrawCampaignDescription(), UI_DrawGametypeDescription(), and UI_Init().
void(* displayContextDef_t::drawTextExt) (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
Definition at line 466 of file ui_shared.h.
Referenced by BG_PanelButton_RenderEdit(), BG_PanelButtonsRender_TextExt(), CG_LoadHudMenu(), CG_LoadPanel_DrawPin(), CG_LoadPanel_RenderMissionDescriptionText(), and UI_Init().
void(* displayContextDef_t::drawTextWithCursor) (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style)
Definition at line 492 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_TextField_Paint(), and UI_Init().
void(* displayContextDef_t::drawTextWithCursorExt) (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style, fontHelper_t *font)
Definition at line 493 of file ui_shared.h.
Referenced by BG_PanelButton_RenderEdit(), CG_LoadHudMenu(), and UI_Init().
void(* displayContextDef_t::drawTopBottom) (float x, float y, float w, float h, float size)
Definition at line 479 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::Error) (int level, const char *error,...) __attribute__((noreturn
Definition at line 519 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), and UI_Init().
void(* displayContextDef_t::executeText) (int exec_when, const char *text)
Definition at line 518 of file ui_shared.h.
Referenced by Controls_SetConfig(), Menu_HandleKey(), Script_Exec(), Script_ExecNOW(), Script_ExecWolfConfig(), Script_GetClipboard(), and UI_Init().
void(* displayContextDef_t::feederAddItem) (int feederID, const char *name, int index)
Definition at line 504 of file ui_shared.h.
Referenced by Script_AddListItem(), and UI_Init().
int(* displayContextDef_t::feederCount) (int feederID)
Definition at line 498 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_ListBox_HandleKey(), Item_ListBox_MaxScroll(), Item_ListBox_Paint(), and UI_Init().
qhandle_t(* displayContextDef_t::feederItemImage) (int feederID, int index)
Definition at line 501 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_ListBox_Paint(), and UI_Init().
const char*(* displayContextDef_t::feederItemText) (int feederID, int index, int column, qhandle_t *handles, int *numhandles)
Definition at line 499 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_ListBox_Paint(), and UI_Init().
void(* displayContextDef_t::feederSelection) (int feederID, int index)
Definition at line 502 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_ListBox_HandleKey(), Menu_SetFeederSelection(), and UI_Init().
qboolean(* displayContextDef_t::feederSelectionClick) (itemDef_t *item)
Definition at line 503 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), and UI_Init().
const char*(* displayContextDef_t::fileText) (const char *fileName)
Definition at line 500 of file ui_shared.h.
Referenced by ItemParse_textfile(), and UI_Init().
void(* displayContextDef_t::fillRect) (float x, float y, float w, float h, const vec4_t color)
Definition at line 476 of file ui_shared.h.
Referenced by BG_PanelButtonsRender_TextExt(), CG_LoadHudMenu(), CG_LoadPanel_DrawPin(), Item_Combo_Paint(), Item_ListBox_Paint(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::format) (printf, 2, 3)))
Definition at line 519 of file ui_shared.h.
float displayContextDef_t::FPS
Definition at line 554 of file ui_shared.h.
Referenced by Menu_PaintAll(), and UI_Refresh().
int displayContextDef_t::frameTime
Definition at line 543 of file ui_shared.h.
Referenced by UI_ConsoleCommand(), and UI_Refresh().
void(* displayContextDef_t::getAutoUpdate) (void)
Definition at line 507 of file ui_shared.h.
Referenced by Script_GetAutoUpdate(), and UI_Init().
void(* displayContextDef_t::getBindingBuf) (int keynum, char *buf, int buflen)
Definition at line 510 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), String_Init(), and UI_Init().
void(* displayContextDef_t::getClipboardData) (char *buf, size_t bufsize)
Definition at line 515 of file ui_shared.h.
Referenced by Item_TextField_HandleKey(), Script_GetClipboard(), and UI_Init().
int(* displayContextDef_t::getConfigString) (int index, char *buff, size_t buffsize)
Definition at line 537 of file ui_shared.h.
Referenced by CG_DrawConnectScreen(), CG_LoadHudMenu(), Item_SettingShow(), and UI_Init().
void(* displayContextDef_t::getCVarString) (const char *cvar, char *buffer, int bufsize)
Definition at line 489 of file ui_shared.h.
Referenced by BG_PanelButton_EditClick(), CG_LoadHudMenu(), Item_CalcTextFieldCursor(), Item_Combo_Paint(), Item_EnableShowViaCvar(), Item_HandleTextFieldDeSelect(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_SetTextExtents(), Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), Item_Text_Wrapped_Paint(), Item_TextField_HandleKey(), Item_TextField_Paint(), Script_CheckProfile(), Script_ConditionalOpen(), Script_ConditionalScript(), Script_CopyCvar(), Script_ExecWolfConfig(), Script_ToggleCvarBit(), Script_WriteProfile(), and UI_Init().
float(* displayContextDef_t::getCVarValue) (const char *cvar)
Definition at line 490 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Cui_WideRect(), Item_CheckBox_HandleKey(), Item_CheckBox_Paint(), Item_Combo_Paint(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_Slider_ThumbPosition(), Item_YesNo_HandleKey(), Item_YesNo_Paint(), Menu_HandleKey(), Menu_Paint(), Script_ConditionalOpen(), Script_ConditionalScript(), UI_ConsoleCommand(), UI_GLCustom(), and UI_Init().
void(* displayContextDef_t::getHunkData) (int *hunkused, int *hunkexpected)
Definition at line 536 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), and UI_Init().
void(* displayContextDef_t::getKeysForBinding) (const char *binding, int *key1, int *key2)
Definition at line 511 of file ui_shared.h.
Referenced by Binding_FromName(), Binding_Set(), Binding_Unset(), CG_LimboPanel_KeyHandling(), CG_LoadHudMenu(), Controls_GetConfig(), and UI_Init().
qboolean(* displayContextDef_t::getOverstrikeMode) (void)
Definition at line 495 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_TextField_HandleKey(), Item_TextField_InsertToCursor(), Item_TextField_Paint(), and UI_Init().
void(* displayContextDef_t::getTeamColor) (vec4_t *color)
Definition at line 488 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Script_SetTeamColor(), UI_Init(), and Window_Paint().
float(* displayContextDef_t::getValue) (int ownerDraw, int type)
Definition at line 485 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_OwnerDraw_Paint(), and UI_Init().
glconfig_t displayContextDef_t::glconfig
Definition at line 550 of file ui_shared.h.
Referenced by AdjustFrom640(), Cui_WideRect(), Cui_WideX(), Cui_WideXoffset(), UI_AdjustFrom640(), UI_DrawLoadPanel(), UI_FeederItemText(), UI_Init(), UI_LoadMenus(), and UI_ParseGLConfig().
qhandle_t displayContextDef_t::gradientImage
Definition at line 552 of file ui_shared.h.
qboolean(* displayContextDef_t::keyIsDown) (int keynum)
Definition at line 513 of file ui_shared.h.
Referenced by Menu_HandleKey(), and UI_Init().
void(* displayContextDef_t::keynumToStringBuf) (int keynum, char *buf, int buflen)
Definition at line 509 of file ui_shared.h.
Referenced by Binding_FromName(), CG_LoadHudMenu(), and UI_Init().
void(* displayContextDef_t::modelBounds) (qhandle_t model, vec3_t min, vec3_t max)
Definition at line 475 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Model_Paint(), and UI_Init().
int(* displayContextDef_t::multiLineTextHeight) (const char *text, float scale, int limit)
Definition at line 472 of file ui_shared.h.
Referenced by Tooltip_ComputePosition(), and UI_Init().
int(* displayContextDef_t::multiLineTextWidth) (const char *text, float scale, int limit)
Definition at line 469 of file ui_shared.h.
Referenced by Tooltip_ComputePosition(), and UI_Init().
const char*(* displayContextDef_t::nameForCampaign) (void)
Definition at line 533 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), CG_LoadPanel_RenderCampaignNameText(), and UI_Init().
qboolean(* displayContextDef_t::ownerDrawHandleKey) (int ownerDraw, int flags, int *special, int key)
Definition at line 497 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_OwnerDraw_HandleKey(), and UI_Init().
void(* displayContextDef_t::ownerDrawItem) (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, int special, float scale, vec4_t color, qhandle_t shader, int textStyle)
Definition at line 484 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_OwnerDraw_Paint(), and UI_Init().
qboolean(* displayContextDef_t::ownerDrawVisible) (int flags)
Definition at line 486 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Paint(), Menu_Paint(), and UI_Init().
int(* displayContextDef_t::ownerDrawWidth) (int ownerDraw, float scale)
Definition at line 522 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_SetTextExtents(), and UI_Init().
void(*) void(* displayContextDef_t::Pause) (qboolean b)
Definition at line 521 of file ui_shared.h.
Referenced by Menus_HandleOOBClick(), and UI_Init().
int(* displayContextDef_t::playCinematic) (const char *name, float x, float y, float w, float h)
Definition at line 526 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), UI_Init(), Window_CacheContents(), and Window_Paint().
void(* displayContextDef_t::Print) (const char *msg,...) __attribute__((format(printf
Definition at line 520 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), UI_Alloc(), and UI_Init().
int displayContextDef_t::realTime
Definition at line 542 of file ui_shared.h.
Referenced by CG_DrawActiveFrame(), CG_ProcessSnapshots(), CG_Text_PaintWithCursor_Ext(), Fade(), Item_Bind_Paint(), Item_CheckBox_Paint(), Item_DoTransition(), Item_ListBox_HandleKey(), Item_Model_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Paint(), Item_Scroll_ListBox_AutoFunc(), Item_Scroll_ListBox_ThumbFunc(), Item_Slider_Paint(), Item_StartCapture(), Item_Text_Paint(), Item_TextColor(), Item_TextField_Paint(), Item_YesNo_Paint(), ItemParse_model_animplay(), Menu_Paint(), Menus_Activate(), Text_PaintWithCursor_Ext(), UI_BuildServerDisplayList(), UI_BuildServerStatus(), UI_ConsoleCommand(), UI_DoServerRefresh(), UI_DownloadInfo(), UI_DrawSelectedPlayer(), UI_DrawServerMOTD(), UI_DrawServerRefreshDate(), UI_FeederCount(), UI_FeederItemText(), UI_Refresh(), UI_StartServerRefresh(), and UI_UpdatePendingPings().
void(* displayContextDef_t::registerFont) (const char *pFontname, int pointSize, void *font)
Definition at line 483 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), and UI_Init().
qhandle_t(* displayContextDef_t::registerModel) (const char *p)
Definition at line 474 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), ItemParse_asset_model(), and UI_Init().
qhandle_t(* displayContextDef_t::registerShaderNoMip) (const char *p)
Definition at line 461 of file ui_shared.h.
Referenced by CG_DrawConnectScreen(), CG_LoadHudMenu(), ItemParse_asset_shader(), ItemParse_background(), MenuParse_background(), Script_SetBackground(), UI_DrawLoadPanel(), and UI_Init().
sfxHandle_t(* displayContextDef_t::registerSound) (const char *name, qboolean compressed)
Definition at line 523 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), ItemParse_focusSound(), Menu_CacheContents(), Script_Play(), and UI_Init().
void(* displayContextDef_t::renderScene) (const refdef_t *fd)
Definition at line 482 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Model_Paint(), and UI_Init().
void(* displayContextDef_t::runCinematicFrame) (int handle)
Definition at line 529 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::runScript) (char **p)
Definition at line 487 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_RunScript(), and UI_Init().
void(* displayContextDef_t::setBinding) (int keynum, const char *binding)
Definition at line 517 of file ui_shared.h.
Referenced by Binding_Unset(), CG_LoadHudMenu(), Controls_SetConfig(), Item_Bind_HandleKey(), and UI_Init().
void(* displayContextDef_t::setColor) (const vec4_t v)
Definition at line 462 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), GradientBar_Paint(), Item_ListBox_Paint(), Item_Slider_Paint(), UI_Init(), and Window_Paint().
void(* displayContextDef_t::setCVar) (const char *cvar, const char *value)
Definition at line 491 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_CalcTextFieldCursor(), Item_CheckBox_HandleKey(), Item_Combo_HandleKey(), Item_HandleTextFieldDeSelect(), Item_Multi_HandleKey(), Item_Scroll_Slider_ThumbFunc(), Item_Slider_HandleKey(), Item_TextField_HandleKey(), Item_YesNo_HandleKey(), Script_ClearCvar(), Script_CopyCvar(), Script_GetClipboard(), Script_SetCvar(), Script_SetEditFocus(), Script_SetPlayerHead(), Script_SetPlayerModel(), Script_ToggleCvarBit(), UI_BuildServerDisplayList(), UI_GLCustom(), and UI_Init().
void(* displayContextDef_t::setOverstrikeMode) (qboolean b)
Definition at line 494 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_TextField_HandleKey(), and UI_Init().
void(* displayContextDef_t::startBackgroundTrack) (const char *intro, const char *loop, int fadeupTime)
Definition at line 524 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Menus_Activate(), Script_playLooped(), and UI_Init().
void(* displayContextDef_t::startLocalSound) (sfxHandle_t sfx, int channelNum)
Definition at line 496 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_SetFocus(), Script_Play(), Script_SetEditFocus(), Script_SetFocus(), and UI_Init().
void(* displayContextDef_t::stopBackgroundTrack) (void)
Definition at line 525 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Script_playLooped(), and UI_Init().
void(* displayContextDef_t::stopCinematic) (int handle)
Definition at line 527 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Menu_CloseCinematics(), Menu_ShowItemByName(), UI_Init(), Window_CacheContents(), and Window_CloseCinematic().
void(* displayContextDef_t::textFont) (int font)
Definition at line 473 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Paint(), Menu_PaintAll(), Tooltip_ComputePosition(), and UI_Init().
int(* displayContextDef_t::textHeight) (const char *text, float scale, int limit)
Definition at line 470 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_SetTextExtents(), and UI_Init().
int(* displayContextDef_t::textHeightExt) (const char *text, float scale, int limit, fontHelper_t *font)
Definition at line 471 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), and UI_Init().
int(* displayContextDef_t::textWidth) (const char *text, float scale, int limit)
Definition at line 467 of file ui_shared.h.
Referenced by CG_LoadHudMenu(), Item_Combo_Paint(), Item_SetTextExtents(), Item_Text_AutoWrapped_Paint(), Item_TextField_Paint(), UI_DrawCampaignDescription(), UI_DrawGametypeDescription(), and UI_Init().
int(* displayContextDef_t::textWidthExt) (const char *text, float scale, int limit, fontHelper_t *font)
Definition at line 468 of file ui_shared.h.
Referenced by BG_FitTextToWidth_Ext(), BG_PanelButton_RenderEdit(), BG_PanelButtonsRender_TextExt(), CG_LoadHudMenu(), CG_LoadPanel_DrawPin(), and UI_Init().
const char*(* displayContextDef_t::translateString) (const char *string)
Definition at line 505 of file ui_shared.h.
Referenced by Binding_FromName(), CG_LoadHudMenu(), Item_YesNo_Paint(), and UI_Init().
void(* displayContextDef_t::updateScreen) (void)
Definition at line 535 of file ui_shared.h.
Referenced by CG_DrawConnectScreen(), CG_LoadHudMenu(), and UI_Init().
qhandle_t displayContextDef_t::whiteShader
Definition at line 551 of file ui_shared.h.
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), UI_DrawTopBottom(), UI_FillRect(), and UI_Init().
float displayContextDef_t::xscale
Definition at line 540 of file ui_shared.h.
Referenced by _UI_DrawSides(), AdjustFrom640(), CG_LoadHudMenu(), Cui_WideRect(), UI_AdjustFrom640(), UI_DrawLoadPanel(), and UI_Init().
float displayContextDef_t::yscale
Definition at line 539 of file ui_shared.h.
Referenced by _UI_DrawTopBottom(), AdjustFrom640(), CG_LoadHudMenu(), Cui_WideRect(), UI_AdjustFrom640(), and UI_Init().
The documentation for this struct was generated from the following file:
src/ui/ui_shared.h