ET: Legacy: botlib_export_s Struct Reference
botlib_export_s Struct Reference
#include <botlib.h>
Data Fields
int(* BotLibSetup)(qboolean singleplayer)
int(* BotLibShutdown)(void)
int(* PC_AddGlobalDefine)(const char *string)
void(* PC_RemoveAllGlobalDefines)(void)
int(* PC_LoadSourceHandle)(const char *filename)
int(* PC_FreeSourceHandle)(int handle)
int(* PC_ReadTokenHandle)(int handle, pc_token_t *pc_token)
int(* PC_SourceFileAndLine)(int handle, char *filename, int *line)
void(* PC_UnreadLastTokenHandle)(int handle)
Detailed Description
Definition at line 110 of file botlib.h.
Field Documentation
int(* botlib_export_s::BotLibSetup) (qboolean singleplayer)
Definition at line 113 of file botlib.h.
Referenced by GetBotLibAPI().
int(* botlib_export_s::BotLibShutdown) (void)
Definition at line 115 of file botlib.h.
Referenced by GetBotLibAPI().
int(* botlib_export_s::PC_AddGlobalDefine) (const char *string)
Definition at line 119 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetBotLibAPI().
int(* botlib_export_s::PC_FreeSourceHandle) (int handle)
Definition at line 122 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_LoadSourceHandle) (const char *filename)
Definition at line 121 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_ReadTokenHandle) (int handle, pc_token_t *pc_token)
Definition at line 123 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
void(* botlib_export_s::PC_RemoveAllGlobalDefines) (void)
Definition at line 120 of file botlib.h.
Referenced by CL_UISystemCalls(), and GetBotLibAPI().
int(* botlib_export_s::PC_SourceFileAndLine) (int handle, char *filename, int *line)
Definition at line 124 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
void(* botlib_export_s::PC_UnreadLastTokenHandle) (int handle)
Definition at line 125 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
The documentation for this struct was generated from the following file:
src/botlib/botlib.h