ET: Legacy: Bot_EngineFuncs_t Struct Reference
Bot_EngineFuncs_t Struct Reference
#include <Functions_Bot.h>
Data Fields
omnibot_error(* pfnInitialize)(IEngineInterface *_pEngineFuncs, int _version)
void(* pfnUpdate)()
void(* pfnShutdown)()
void(* pfnConsoleCommand)(const Arguments &_args)
void(* pfnSendTrigger)(const TriggerInfo &_triggerInfo)
void(* pfnAddBlackboardRecord)(BlackBoard_Key _type, int _posterID, int _targetID, obUserData *_data)
void(* pfnSendEvent)(int _dest, const MessageHelper &_message)
void(* pfnSendGlobalEvent)(const MessageHelper &_message)
void(* pfnAddGoal)(const MapGoalDef &goaldef)
void(* pfnDeleteGoal)(const char *goalname)
void(* pfnUpdateEntity)(GameEntity oldent, GameEntity newent)
Detailed Description
Definition at line 24 of file Functions_Bot.h.
Field Documentation
void(* Bot_EngineFuncs_t::pfnAddBlackboardRecord) (BlackBoard_Key _type, int _posterID, int _targetID, obUserData *_data)
Definition at line 32 of file Functions_Bot.h.
void(* Bot_EngineFuncs_t::pfnAddGoal) (const MapGoalDef &goaldef)
Definition at line 39 of file Functions_Bot.h.
Referenced by Bot_Util_AddGoal().
void(* Bot_EngineFuncs_t::pfnConsoleCommand) (const Arguments &_args)
Definition at line 29 of file Functions_Bot.h.
Referenced by Bot_Interface_ConsoleCommand().
void(* Bot_EngineFuncs_t::pfnDeleteGoal) (const char *goalname)
Definition at line 40 of file Functions_Bot.h.
Referenced by DeleteMapGoal().
omnibot_error(* Bot_EngineFuncs_t::pfnInitialize) (IEngineInterface *_pEngineFuncs, int _version)
Definition at line 26 of file Functions_Bot.h.
Referenced by Omnibot_strncpy().
void(* Bot_EngineFuncs_t::pfnSendEvent) (int _dest, const MessageHelper &_message)
Definition at line 35 of file Functions_Bot.h.
Referenced by Bot_Event_AddWeapon(), Bot_Event_ChatMessage(), Bot_Event_Death(), Bot_Event_FireTeam_Proposal(), Bot_Event_FireTeam_Warn(), Bot_Event_FireTeamCreated(), Bot_Event_FireTeamDestroyed(), Bot_Event_FireWeapon(), Bot_Event_Healed(), Bot_Event_InviteFireTeam(), Bot_Event_JoinedFireTeam(), Bot_Event_KilledSomeone(), Bot_Event_LeftFireTeam(), Bot_Event_MortarImpact(), Bot_Event_PostTriggerMine(), Bot_Event_PreTriggerMine(), Bot_Event_RecievedAmmo(), Bot_Event_RemoveWeapon(), Bot_Event_ResetWeapons(), Bot_Event_Revived(), Bot_Event_Spectated(), Bot_Event_TakeDamage(), and Bot_Event_VoiceMacro().
void(* Bot_EngineFuncs_t::pfnSendGlobalEvent) (const MessageHelper &_message)
Definition at line 36 of file Functions_Bot.h.
Referenced by Bot_Event_ClientConnected(), Bot_Event_ClientDisConnected(), Bot_Event_EntityCreated(), Bot_Event_EntityDeleted(), Bot_Event_Sound(), and Bot_Interface_Update().
void(* Bot_EngineFuncs_t::pfnSendTrigger) (const TriggerInfo &_triggerInfo)
Definition at line 31 of file Functions_Bot.h.
Referenced by Bot_Util_SendTrigger().
void(* Bot_EngineFuncs_t::pfnShutdown) ()
Definition at line 28 of file Functions_Bot.h.
Referenced by Bot_Interface_Shutdown().
void(* Bot_EngineFuncs_t::pfnUpdate) ()
Definition at line 27 of file Functions_Bot.h.
Referenced by Bot_Interface_Update().
void(* Bot_EngineFuncs_t::pfnUpdateEntity) (GameEntity oldent, GameEntity newent)
Definition at line 41 of file Functions_Bot.h.
Referenced by UpdateGoalEntity().
The documentation for this struct was generated from the following file:
src/Omnibot/Common/Functions_Bot.h