ET: Legacy: refexport_t Struct Reference
refexport_t Struct Reference
#include <tr_public.h>
Data Fields
void(* Shutdown)(qboolean destroyWindow)
void(* BeginRegistration)(glconfig_t *config)
qhandle_t(* RegisterModel)(const char *name)
qhandle_t(* RegisterModelAllLODs)(const char *name)
qhandle_t(* RegisterSkin)(const char *name)
qhandle_t(* RegisterShader)(const char *name)
qhandle_t(* RegisterShaderNoMip)(const char *name)
void(* RegisterFont)(const char *fontName, int pointSize, void *font, qboolean extended)
void(* LoadWorld)(const char *name)
qboolean(* GetSkinModel)(qhandle_t skinid, const char *type, char *name)
qhandle_t(* GetShaderFromModel)(qhandle_t modelid, int surfnum, int withlightmap)
void(* SetWorldVisData)(const byte *vis)
void(* EndRegistration)(void)
void(* ClearScene)(void)
void(* AddRefEntityToScene)(const refEntity_t *re)
int(* LightForPoint)(vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void(* AddPolyToScene)(qhandle_t hShader, int numVerts, const polyVert_t *verts)
void(* AddPolysToScene)(qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
void(* AddLightToScene)(const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
void(* AddCoronaToScene)(const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
void(* SetFog)(int fogvar, int var1, int var2, float r, float g, float b, float density)
void(* RenderScene)(const refdef_t *fd)
void(* SetColor)(const float *rgba)
void(* DrawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
NULL = 1,1,1,1.
void(* DrawRotatedPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
0 = white
void(* DrawStretchPicGradient)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float *gradientColor, int gradientType)
NERVE - SMF.
void(* Add2dPolys)(polyVert_t *polys, int numverts, qhandle_t hShader)
void(* DrawStretchRaw)(int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Draw images for cinematic rendering, pass as 32 bit rgba.
void(* UploadCinematic)(int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
void(* BeginFrame)(void)
void(* EndFrame)(int *frontEndMsec, int *backEndMsec)
if the pointers are not NULL, timing info will be returned
int(* MarkFragments)(int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
void(* ProjectDecal)(qhandle_t hShader, int numPoints, vec3_t *points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
void(* ClearDecals)(void)
int(* LerpTag)(orientation_t *tag, const refEntity_t *refent, const char *tagName, int startIndex)
void(* ModelBounds)(qhandle_t model, vec3_t mins, vec3_t maxs)
void(* RemapShader)(const char *oldShader, const char *newShader, const char *offsetTime)
void(* DrawDebugPolygon)(int color, int numpoints, float *points)
void(* DrawDebugText)(const vec3_t org, float r, float g, float b, const char *text, qboolean neverOcclude)
qboolean(* GetEntityToken)(char *buffer, size_t size)
void(* AddPolyBufferToScene)(polyBuffer_t *pPolyBuffer)
void(* SetGlobalFog)(qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
qboolean(* inPVS)(const vec3_t p1, const vec3_t p2)
void(* purgeCache)(void)
qboolean(* LoadDynamicShader)(const char *shadername, const char *shadertext)
void(* RenderToTexture)(int textureid, int x, int y, int w, int h)
int(* GetTextureId)(const char *imagename)
void(* Finish)(void)
void(* TakeVideoFrame)(int h, int w, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
avi output stuff
void(* InitOpenGL)(void)
int(* InitOpenGLSubSystem)(void)
qhandle_t(* RegisterAnimation)(const char *name)
alternative skeletal animation system
int(* CheckSkeleton)(refSkeleton_t *skel, qhandle_t model, qhandle_t anim)
int(* BuildSkeleton)(refSkeleton_t *skel, qhandle_t anim, int startFrame, int endFrame, float frac, qboolean clearOrigin)
int(* BlendSkeleton)(refSkeleton_t *skel, const refSkeleton_t *blend, float frac)
int(* BoneIndex)(qhandle_t hModel, const char *boneName)
int(* AnimNumFrames)(qhandle_t hAnim)
int(* AnimFrameRate)(qhandle_t hAnim)
Detailed Description
Definition at line 46 of file tr_public.h.
Field Documentation
void(* refexport_t::Add2dPolys) (polyVert_t *polys, int numverts, qhandle_t hShader)
Definition at line 98 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddCoronaToScene) (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
Definition at line 90 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddLightToScene) (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
Definition at line 89 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddPolyBufferToScene) (polyBuffer_t *pPolyBuffer)
Definition at line 127 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::AddPolysToScene) (qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
Definition at line 88 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddPolyToScene) (qhandle_t hShader, int numVerts, const polyVert_t *verts)
Definition at line 87 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddRefEntityToScene) (const refEntity_t *re)
Definition at line 85 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
int(* refexport_t::AnimFrameRate) (qhandle_t hAnim)
Definition at line 162 of file tr_public.h.
Referenced by GetRefAPI().
int(* refexport_t::AnimNumFrames) (qhandle_t hAnim)
Definition at line 161 of file tr_public.h.
Referenced by GetRefAPI().
void(* refexport_t::BeginFrame) (void)
Definition at line 104 of file tr_public.h.
Referenced by GetRefAPI(), and SCR_DrawScreenField().
void(* refexport_t::BeginRegistration) (glconfig_t *config)
BeginRegistration makes any existing media pointers invalid and returns the current gl configuration, including screen width and height, which can be used by the client to intelligently size display elements
Definition at line 62 of file tr_public.h.
Referenced by CL_InitRenderer(), and GetRefAPI().
int(* refexport_t::BlendSkeleton) (refSkeleton_t *skel, const refSkeleton_t *blend, float frac)
Definition at line 159 of file tr_public.h.
Referenced by GetRefAPI().
int(* refexport_t::BoneIndex) (qhandle_t hModel, const char *boneName)
Definition at line 160 of file tr_public.h.
Referenced by GetRefAPI().
int(* refexport_t::BuildSkeleton) (refSkeleton_t *skel, qhandle_t anim, int startFrame, int endFrame, float frac, qboolean clearOrigin)
Definition at line 157 of file tr_public.h.
Referenced by GetRefAPI().
int(* refexport_t::CheckSkeleton) (refSkeleton_t *skel, qhandle_t model, qhandle_t anim)
Definition at line 156 of file tr_public.h.
Referenced by GetRefAPI().
void(* refexport_t::ClearDecals) (void)
Definition at line 114 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::ClearScene) (void)
a scene is built up by calls to R_ClearScene and the various R_Add functions. Nothing is drawn until R_RenderScene is called.
Definition at line 84 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::DrawDebugPolygon) (int color, int numpoints, float *points)
Definition at line 121 of file tr_public.h.
Referenced by BotImport_DrawPolygon(), and GetRefAPI().
void(* refexport_t::DrawDebugText) (const vec3_t org, float r, float g, float b, const char *text, qboolean neverOcclude)
Definition at line 123 of file tr_public.h.
Referenced by GetRefAPI().
void(* refexport_t::DrawRotatedPic) (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
0 = white
Definition at line 96 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::DrawStretchPic) (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
NULL = 1,1,1,1.
Definition at line 95 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Con_DrawInput(), GetRefAPI(), SCR_DrawDebugGraph(), SCR_DrawPic(), SCR_FillRect(), and SRC_DrawSingleChar().
void(* refexport_t::DrawStretchPicGradient) (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, const float *gradientColor, int gradientType)
NERVE - SMF.
Definition at line 97 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::DrawStretchRaw) (int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Draw images for cinematic rendering, pass as 32 bit rgba.
Definition at line 101 of file tr_public.h.
Referenced by CIN_DrawCinematic(), and GetRefAPI().
void(* refexport_t::EndFrame) (int *frontEndMsec, int *backEndMsec)
if the pointers are not NULL, timing info will be returned
Definition at line 107 of file tr_public.h.
Referenced by GetRefAPI(), and SCR_UpdateScreen().
void(* refexport_t::EndRegistration) (void)
EndRegistration will draw a tiny polygon with each texture, forcing them to be loaded into card memory
Definition at line 80 of file tr_public.h.
Referenced by CL_InitCGame(), and GetRefAPI().
void(* refexport_t::Finish) (void)
Definition at line 140 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
qboolean(* refexport_t::GetEntityToken) (char *buffer, size_t size)
Definition at line 125 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::GetShaderFromModel) (qhandle_t modelid, int surfnum, int withlightmap)
Definition at line 72 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
qboolean(* refexport_t::GetSkinModel) (qhandle_t skinid, const char *type, char *name)
Definition at line 71 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
int(* refexport_t::GetTextureId) (const char *imagename)
Definition at line 139 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::InitOpenGL) (void)
Definition at line 145 of file tr_public.h.
Referenced by GetRefAPI(), and GLimp_Init().
int(* refexport_t::InitOpenGLSubSystem) (void)
Definition at line 146 of file tr_public.h.
Referenced by GetRefAPI(), and GLimp_SetMode().
qboolean(* refexport_t::inPVS) (const vec3_t p1, const vec3_t p2)
Definition at line 131 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
int(* refexport_t::LerpTag) (orientation_t *tag, const refEntity_t *refent, const char *tagName, int startIndex)
Definition at line 116 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
int(* refexport_t::LightForPoint) (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
Definition at line 86 of file tr_public.h.
qboolean(* refexport_t::LoadDynamicShader) (const char *shadername, const char *shadertext)
Definition at line 135 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::LoadWorld) (const char *name)
Definition at line 70 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
int(* refexport_t::MarkFragments) (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
Definition at line 110 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::ModelBounds) (qhandle_t model, vec3_t mins, vec3_t maxs)
Definition at line 117 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::ProjectDecal) (qhandle_t hShader, int numPoints, vec3_t *points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
Definition at line 113 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::purgeCache) (void)
Definition at line 133 of file tr_public.h.
Referenced by CL_DoPurgeCache(), CL_ShutdownAll(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterAnimation) (const char *name)
alternative skeletal animation system
Definition at line 155 of file tr_public.h.
Referenced by GetRefAPI().
void(* refexport_t::RegisterFont) (const char *fontName, int pointSize, void *font, qboolean extended)
Definition at line 68 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterModel) (const char *name)
Definition at line 63 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterModelAllLODs) (const char *name)
Definition at line 64 of file tr_public.h.
qhandle_t(* refexport_t::RegisterShader) (const char *name)
Definition at line 66 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_InitRenderer(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterShaderNoMip) (const char *name)
Definition at line 67 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterSkin) (const char *name)
Definition at line 65 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::RemapShader) (const char *oldShader, const char *newShader, const char *offsetTime)
Definition at line 119 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::RenderScene) (const refdef_t *fd)
Definition at line 92 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::RenderToTexture) (int textureid, int x, int y, int w, int h)
Definition at line 137 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::SetColor) (const float *rgba)
Definition at line 94 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Con_DrawClock(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_DrawVersion(), GetRefAPI(), SCR_DrawDebugGraph(), SCR_DrawStringExt(), and SCR_FillRect().
void(* refexport_t::SetFog) (int fogvar, int var1, int var2, float r, float g, float b, float density)
Definition at line 91 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::SetGlobalFog) (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
Definition at line 129 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::SetWorldVisData) (const byte *vis)
the vis data is a large enough block of data that we go to the trouble of sharing it with the clipmodel subsystem
Definition at line 76 of file tr_public.h.
Referenced by GetRefAPI().
void(* refexport_t::Shutdown) (qboolean destroyWindow)
called before the library is unloaded if the system is just reconfiguring, pass destroyWindow = qfalse, which will keep the screen from flashing to the desktop.
Definition at line 51 of file tr_public.h.
Referenced by CL_ShutdownAll(), CL_ShutdownRef(), and GetRefAPI().
void(* refexport_t::TakeVideoFrame) (int h, int w, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
avi output stuff
Definition at line 143 of file tr_public.h.
Referenced by CL_TakeVideoFrame(), and GetRefAPI().
void(* refexport_t::UploadCinematic) (int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Definition at line 102 of file tr_public.h.
Referenced by CIN_UploadCinematic(), and GetRefAPI().
The documentation for this struct was generated from the following file:
src/renderercommon/tr_public.h