ET: Legacy: soundInterface_t Struct Reference
soundInterface_t Struct Reference
#include <snd_local.h>
Data Fields
void(* Shutdown)(void)
void(* Reload)(void)
void(* StartSound)(vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx, int volume)
void(* StartSoundEx)(vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx, int flags, int volume)
void(* StartLocalSound)(sfxHandle_t sfx, int channelNum, int volume)
void(* StartBackgroundTrack)(const char *intro, const char *loop, int fadeupTime)
void(* StopBackgroundTrack)(void)
float(* StartStreamingSound)(const char *intro, const char *loop, int entnum, int channel, int attenuation)
void(* StopEntStreamingSound)(int entNum)
void(* FadeStreamingSound)(float targetvol, int time, int ssNum)
void(* RawSamples)(int stream, int samples, int rate, int width, int channels, const byte *data, float lvol, float rvol)
void(* ClearSounds)(qboolean clearStreaming, qboolean clearMusic)
void(* StopAllSounds)(void)
void(* FadeAllSounds)(float targetvol, int time, qboolean stopsounds)
void(* ClearLoopingSounds)(void)
void(* AddLoopingSound)(const vec3_t origin, const vec3_t velocity, const int range, sfxHandle_t sfx, int volume, int soundTime)
void(* AddRealLoopingSound)(const vec3_t origin, const vec3_t velocity, const int range, sfxHandle_t sfx, int volume, int soundTime)
void(* Respatialize)(int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
void(* UpdateEntityPosition)(int entityNum, const vec3_t origin)
void(* Update)(void)
void(* DisableSounds)(void)
void(* BeginRegistration)(void)
sfxHandle_t(* RegisterSound)(const char *sample, qboolean compressed)
void(* ClearSoundBuffer)(qboolean killStreaming)
void(* SoundInfo)(void)
void(* SoundList)(void)
int(* GetVoiceAmplitude)(int entityNum)
int(* GetSoundLength)(sfxHandle_t sfxHandle)
int(* GetCurrentSoundTime)(void)
Detailed Description
Definition at line 187 of file snd_local.h.
Field Documentation
void(* soundInterface_t::AddLoopingSound) (const vec3_t origin, const vec3_t velocity, const int range, sfxHandle_t sfx, int volume, int soundTime)
Definition at line 204 of file snd_local.h.
Referenced by S_AddLoopingSound(), S_AL_Init(), S_Base_Init(), and S_ValidSoundInterface().
void(* soundInterface_t::AddRealLoopingSound) (const vec3_t origin, const vec3_t velocity, const int range, sfxHandle_t sfx, int volume, int soundTime)
Definition at line 205 of file snd_local.h.
Referenced by S_AddRealLoopingSound(), S_AL_Init(), S_Base_Init(), and S_ValidSoundInterface().
void(* soundInterface_t::BeginRegistration) (void)
Definition at line 210 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_BeginRegistration(), and S_ValidSoundInterface().
void(* soundInterface_t::ClearLoopingSounds) (void)
Definition at line 203 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_ClearLoopingSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::ClearSoundBuffer) (qboolean killStreaming)
Definition at line 212 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_ClearSoundBuffer(), and S_ValidSoundInterface().
void(* soundInterface_t::ClearSounds) (qboolean clearStreaming, qboolean clearMusic)
Definition at line 200 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_ClearSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::DisableSounds) (void)
Definition at line 209 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_DisableSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::FadeAllSounds) (float targetvol, int time, qboolean stopsounds)
Definition at line 202 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_FadeAllSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::FadeStreamingSound) (float targetvol, int time, int ssNum)
Definition at line 198 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_FadeStreamingSound(), and S_ValidSoundInterface().
int(* soundInterface_t::GetCurrentSoundTime) (void)
Definition at line 217 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_GetCurrentSoundTime(), and S_ValidSoundInterface().
int(* soundInterface_t::GetSoundLength) (sfxHandle_t sfxHandle)
Definition at line 216 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_GetSoundLength(), and S_ValidSoundInterface().
int(* soundInterface_t::GetVoiceAmplitude) (int entityNum)
Definition at line 215 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_GetVoiceAmplitude(), and S_ValidSoundInterface().
void(* soundInterface_t::RawSamples) (int stream, int samples, int rate, int width, int channels, const byte *data, float lvol, float rvol)
Definition at line 199 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_RawSamples(), and S_ValidSoundInterface().
sfxHandle_t(* soundInterface_t::RegisterSound) (const char *sample, qboolean compressed)
Definition at line 211 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Play_f(), S_RegisterSound(), and S_ValidSoundInterface().
void(* soundInterface_t::Reload) (void)
Definition at line 190 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Reload(), and S_ValidSoundInterface().
void(* soundInterface_t::Respatialize) (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
Definition at line 206 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Respatialize(), and S_ValidSoundInterface().
void(* soundInterface_t::Shutdown) (void)
Definition at line 189 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Shutdown(), and S_ValidSoundInterface().
void(* soundInterface_t::SoundInfo) (void)
Definition at line 213 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_SoundInfo(), and S_ValidSoundInterface().
void(* soundInterface_t::SoundList) (void)
Definition at line 214 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_SoundList(), and S_ValidSoundInterface().
void(* soundInterface_t::StartBackgroundTrack) (const char *intro, const char *loop, int fadeupTime)
Definition at line 194 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Music_f(), S_StartBackgroundTrack(), and S_ValidSoundInterface().
void(* soundInterface_t::StartLocalSound) (sfxHandle_t sfx, int channelNum, int volume)
Definition at line 193 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Play_f(), S_StartLocalSound(), and S_ValidSoundInterface().
void(* soundInterface_t::StartSound) (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx, int volume)
Definition at line 191 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_StartSound(), and S_ValidSoundInterface().
void(* soundInterface_t::StartSoundEx) (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx, int flags, int volume)
Definition at line 192 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_StartSoundEx(), and S_ValidSoundInterface().
float(* soundInterface_t::StartStreamingSound) (const char *intro, const char *loop, int entnum, int channel, int attenuation)
Definition at line 196 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_StartStreamingSound(), S_Stream_f(), and S_ValidSoundInterface().
void(* soundInterface_t::StopAllSounds) (void)
Definition at line 201 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_StopAllSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::StopBackgroundTrack) (void)
Definition at line 195 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_StopBackgroundTrack(), S_StopMusic_f(), and S_ValidSoundInterface().
void(* soundInterface_t::StopEntStreamingSound) (int entNum)
Definition at line 197 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_StopEntStreamingSound(), and S_ValidSoundInterface().
void(* soundInterface_t::Update) (void)
Definition at line 208 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_Update(), and S_ValidSoundInterface().
void(* soundInterface_t::UpdateEntityPosition) (int entityNum, const vec3_t origin)
Definition at line 207 of file snd_local.h.
Referenced by S_AL_Init(), S_Base_Init(), S_UpdateEntityPosition(), and S_ValidSoundInterface().
The documentation for this struct was generated from the following file:
src/client/snd_local.h