ET: Legacy: videoDecode_s Struct Reference
videoDecode_s Struct Reference
Data Fields
char fileExt [10]
char fileExt2 [10]
void(* Init)(void)
void(* Shutdown)(void)
qboolean(* Start)(cinematic_t *cin)
void(* Update)(cinematic_t *cin, int time)
void(* Reset)(cinematic_t *cin)
void(* Stop)(cinematic_t *cin)
Detailed Description
Definition at line 38 of file cl_cinematic.c.
Field Documentation
char videoDecode_s::fileExt[10]
Definition at line 40 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic(), CIN_ResetCinematic(), and CIN_RunCinematic().
char videoDecode_s::fileExt2[10]
Definition at line 41 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic().
void(* videoDecode_s::Init) (void)
Definition at line 44 of file cl_cinematic.c.
Referenced by CIN_Init().
void(* videoDecode_s::Reset) (cinematic_t *cin)
Definition at line 49 of file cl_cinematic.c.
Referenced by CIN_ResetCinematic().
void(* videoDecode_s::Shutdown) (void)
Definition at line 45 of file cl_cinematic.c.
Referenced by CIN_Shutdown().
qboolean(* videoDecode_s::Start) (cinematic_t *cin)
Definition at line 47 of file cl_cinematic.c.
Referenced by CIN_PlayCinematic().
void(* videoDecode_s::Stop) (cinematic_t *cin)
Definition at line 50 of file cl_cinematic.c.
Referenced by CIN_FreeCinematic().
void(* videoDecode_s::Update) (cinematic_t *cin, int time)
Definition at line 48 of file cl_cinematic.c.
Referenced by CIN_RunCinematic().
The documentation for this struct was generated from the following file:
src/client/cl_cinematic.c