ET: Legacy: animScriptData_t Struct Reference
animScriptData_t Struct Reference
This is the main structure that is duplicated on the client and server.
#include <bg_public.h>
Data Fields
animModelInfo_t modelInfo [MAX_ANIMSCRIPT_MODELS]
int clientConditions [MAX_CLIENTS][NUM_ANIM_CONDITIONS][2]
int(* soundIndex)(const char *name)
void(* playSound)(int soundIndex, vec3_t org, int clientNum)
Detailed Description
This is the main structure that is duplicated on the client and server.
Definition at line 2289 of file bg_public.h.
Field Documentation
int animScriptData_t::clientConditions[MAX_CLIENTS][NUM_ANIM_CONDITIONS][2]
Definition at line 2292 of file bg_public.h.
Referenced by BG_AnimUpdatePlayerStateConditions(), BG_ClearConditionBitFlag(), BG_EvaluateConditions(), BG_GetConditionBitFlag(), BG_GetConditionValue(), BG_SetConditionBitFlag(), and BG_UpdateConditionValue().
animModelInfo_t animScriptData_t::modelInfo[MAX_ANIMSCRIPT_MODELS]
Definition at line 2291 of file bg_public.h.
Referenced by CG_CheckForExistingAnimModelInfo(), and G_CheckForExistingAnimModelInfo().
void(* animScriptData_t::playSound) (int soundIndex, vec3_t org, int clientNum)
Definition at line 2297 of file bg_public.h.
Referenced by BG_ExecuteCommand(), CG_Init(), and G_InitGame().
int(* animScriptData_t::soundIndex) (const char *name)
Definition at line 2296 of file bg_public.h.
Referenced by BG_ParseCommands(), CG_Init(), and G_InitGame().
The documentation for this struct was generated from the following file:
src/game/bg_public.h