ET: Legacy: refimport_t Struct Reference
refimport_t Struct Reference
#include <tr_public.h>
Public Member Functions
void (QDECL *Printf)(int printLevel
print message on the local console
const char __attribute__ ((format(printf, 2, 3)))
void (QDECL *Error)(int errorLevel
abort the game
const char __attribute__ ((noreturn, format(printf, 2, 3)))
Data Fields
const char * fmt
int(* Milliseconds)(void)
int(* RealTime)(qtime_t *qtime)
void(* Hunk_Clear)(void)
void *(* Hunk_Alloc)(unsigned int size, ha_pref pref)
void *(* Hunk_AllocateTempMemory)(unsigned int size)
void(* Hunk_FreeTempMemory)(void *block)
void *(* Z_Malloc)(int bytes)
dynamic memory allocator for things that need to be freed
void(* Free)(void *buf)
void(* Tag_Free)(void)
cvar_t *(* Cvar_Get)(const char *name, const char *value, int flags)
void(* Cvar_Set)(const char *name, const char *value)
void(* Cvar_CheckRange)(cvar_t *cv, float minVal, float maxVal, qboolean shouldBeIntegral)
void(* Cvar_SetDescription)(cvar_t *cv, const char *description)
int(* Cvar_VariableIntegerValue)(const char *var_name)
void(* Cmd_AddSystemCommand)(const char *name, void(*cmd)(void), const char *description, void(*complete)(char *args, int argNum))
void(* Cmd_RemoveSystemCommand)(const char *name)
int(* Cmd_Argc)(void)
char *(* Cmd_Argv)(int i)
void(* Cmd_ExecuteText)(int exec_when, const char *text)
int(* CM_PointContents)(const vec3_t p, clipHandle_t model)
visualization for debugging collision detection
void(* CM_DrawDebugSurface)(void(*drawPoly)(int color, int numPoints, float *points))
int(* FS_FileIsInPAK)(const char *name, int *pChecksum)
int(* FS_ReadFile)(const char *name, void **buf)
void(* FS_FreeFile)(void *buf)
char **(* FS_ListFiles)(const char *name, const char *extension, int *numfilesfound)
void(* FS_FreeFileList)(char **filelist)
void(* FS_WriteFile)(const char *qpath, const void *buffer, int size)
qboolean(* FS_FileExists)(const char *file)
long(* FS_FOpenFileRead)(const char *filename, fileHandle_t *file, qboolean uniqueFILE)
int(* FS_Read)(void *buffer, int len, fileHandle_t f)
void(* CIN_UploadCinematic)(int handle)
cinematic stuff
int(* CIN_PlayCinematic)(const char *arg0, int xpos, int ypos, int width, int height, int bits)
e_status(* CIN_RunCinematic)(int handle)
qboolean(* CL_VideoRecording)(void)
avi output stuff
void(* CL_WriteAVIVideoFrame)(const byte *buffer, int size)
void(* Sys_GLimpSafeInit)(void)
void(* Sys_GLimpInit)(void)
void(* Sys_SetEnv)(const char *name, const char *value)
void(* IN_Init)(void)
input event handling
void(* IN_Shutdown)(void)
void(* IN_Restart)(void)
void(* GLimp_Init)(glconfig_t *glConfig, windowContext_t *context)
void(* GLimp_Shutdown)(void)
void(* GLimp_SwapFrame)(void)
void(* GLimp_SetGamma)(unsigned char red[256], unsigned char green[256], unsigned char blue[256])
Detailed Description
Definition at line 171 of file tr_public.h.
Member Function Documentation
const char refimport_t::__attribute__ ((format(printf, 2, 3)))
const char refimport_t::__attribute__ ((noreturn, format(printf, 2, 3)))
refimport_t::void (QDECL * Printf)
print message on the local console
refimport_t::void (QDECL * Error)
abort the game
Field Documentation
int(* refimport_t::CIN_PlayCinematic) (const char *arg0, int xpos, int ypos, int width, int height, int bits)
Definition at line 237 of file tr_public.h.
Referenced by CL_InitRef(), and ParseStage().
e_status(* refimport_t::CIN_RunCinematic) (int handle)
Definition at line 238 of file tr_public.h.
Referenced by BindAnimatedImage(), CL_InitRef(), and R_BindAnimatedImage().
void(* refimport_t::CIN_UploadCinematic) (int handle)
cinematic stuff
Definition at line 236 of file tr_public.h.
Referenced by BindAnimatedImage(), CL_InitRef(), and R_BindAnimatedImage().
qboolean(* refimport_t::CL_VideoRecording) (void)
avi output stuff
Definition at line 241 of file tr_public.h.
Referenced by CL_InitRef(), and RB_TakeVideoFrameCmd().
void(* refimport_t::CL_WriteAVIVideoFrame) (const byte *buffer, int size)
Definition at line 242 of file tr_public.h.
Referenced by CL_InitRef(), and RB_TakeVideoFrameCmd().
void(* refimport_t::CM_DrawDebugSurface) (void(*drawPoly)(int color, int numPoints, float *points))
Definition at line 220 of file tr_public.h.
Referenced by CL_InitRef(), and R_DebugGraphics().
int(* refimport_t::CM_PointContents) (const vec3_t p, clipHandle_t model)
visualization for debugging collision detection
Definition at line 219 of file tr_public.h.
Referenced by CL_InitRef(), and R_BuildCubeMaps().
void(* refimport_t::Cmd_AddSystemCommand) (const char *name, void(*cmd)(void), const char *description, void(*complete)(char *args, int argNum))
Definition at line 210 of file tr_public.h.
Referenced by CL_InitRef(), and R_Register().
int(* refimport_t::Cmd_Argc) (void)
Definition at line 213 of file tr_public.h.
Referenced by CL_InitRef(), R_ScreenShot_f(), R_ShaderExp_f(), R_ShaderList_f(), and R_TakeScreenshot().
char*(* refimport_t::Cmd_Argv) (int i)
Definition at line 214 of file tr_public.h.
Referenced by CL_InitRef(), R_Modellist_f(), R_ScreenShot_f(), R_ShaderExp_f(), R_ShaderList_f(), and R_TakeScreenshot().
void(* refimport_t::Cmd_ExecuteText) (int exec_when, const char *text)
Definition at line 216 of file tr_public.h.
Referenced by CL_InitRef(), R_FindImageFile(), and RE_RegisterModel().
void(* refimport_t::Cmd_RemoveSystemCommand) (const char *name)
Definition at line 211 of file tr_public.h.
Referenced by CL_InitRef(), and RE_Shutdown().
void(* refimport_t::Cvar_CheckRange) (cvar_t *cv, float minVal, float maxVal, qboolean shouldBeIntegral)
Definition at line 206 of file tr_public.h.
Referenced by CL_InitRef(), R_Init(), and R_Register().
cvar_t*(* refimport_t::Cvar_Get) (const char *name, const char *value, int flags)
Definition at line 204 of file tr_public.h.
Referenced by CL_InitRef(), and R_Register().
void(* refimport_t::Cvar_Set) (const char *name, const char *value)
Definition at line 205 of file tr_public.h.
Referenced by CL_InitRef(), GL_TextureMode(), GLSL_CompileGPUShaders(), R_BuildCubeMaps(), R_Register(), R_SetColorMappings(), and RE_BeginFrame().
void(* refimport_t::Cvar_SetDescription) (cvar_t *cv, const char *description)
Definition at line 207 of file tr_public.h.
Referenced by CL_InitRef().
int(* refimport_t::Cvar_VariableIntegerValue) (const char *var_name)
Definition at line 208 of file tr_public.h.
Referenced by CL_InitRef(), GfxInfo_f(), GLimp_InitExtensionsR2(), R_InitGamma(), and RB_ColorCorrection().
const char * refimport_t::fmt
Definition at line 174 of file tr_public.h.
void(* refimport_t::Free) (void *buf)
Definition at line 201 of file tr_public.h.
Referenced by CL_InitRef(), CloseBufferedFile(), DecompressIDATs(), R_BuildCubeMaps(), R_CacheShaderFreeExt(), R_FreeSurfaceGridMesh(), R_LoadLightmapsExternal(), R_LoadLights(), R_LoadPCX(), R_LoadPNG(), R_LoadScalableFont(), R_LoadTGA(), R_SaveCubeProbes(), RE_ConstructGlyphInfo(), RE_LoadDynamicShader(), RE_SaveTGA(), ReadBufferedFile(), setProjTargetOrigin(), and Upload32().
qboolean(* refimport_t::FS_FileExists) (const char *file)
Definition at line 230 of file tr_public.h.
Referenced by CL_InitRef(), R_BuildCubeMaps(), R_ScreenShot_f(), and R_TakeScreenshot().
int(* refimport_t::FS_FileIsInPAK) (const char *name, int *pChecksum)
a -1 return means the file does not exist NULL can be passed for buf to just determine existance
Definition at line 224 of file tr_public.h.
Referenced by CL_InitRef().
long(* refimport_t::FS_FOpenFileRead) (const char *filename, fileHandle_t *file, qboolean uniqueFILE)
Definition at line 232 of file tr_public.h.
Referenced by CL_InitRef(), GLSL_GetShaderText(), R_LoadImage(), R_LoadModelShadow(), R_LoadScalableFont(), RE_RegisterModel(), and RE_RegisterSkin().
void(* refimport_t::FS_FreeFile) (void *buf)
Definition at line 226 of file tr_public.h.
Referenced by CL_InitRef(), CloseBufferedFile(), GLSL_GetShaderText(), GLSL_LoadShaderBinary(), LoadRGBEToFloats(), R_LoadBMP(), R_LoadCubeProbe(), R_LoadDDSImage(), R_LoadJPG(), R_LoadModelShadow(), R_LoadPCX(), R_LoadPreRenderedFont(), R_LoadScalableFont(), R_LoadTGA(), RE_LoadWorldMap(), RE_RegisterAnimation(), RE_RegisterModel(), RE_RegisterSkin(), ScanAndLoadShaderFiles(), and ScanAndLoadShaderFilesR1().
void(* refimport_t::FS_FreeFileList) (char **filelist)
Definition at line 228 of file tr_public.h.
Referenced by CL_InitRef(), ScanAndLoadShaderFiles(), and ScanAndLoadShaderFilesR1().
char**(* refimport_t::FS_ListFiles) (const char *name, const char *extension, int *numfilesfound)
Definition at line 227 of file tr_public.h.
Referenced by CL_InitRef(), R_LoadLightmapsExternal(), ScanAndLoadShaderFiles(), and ScanAndLoadShaderFilesR1().
int(* refimport_t::FS_Read) (void *buffer, int len, fileHandle_t f)
Definition at line 233 of file tr_public.h.
Referenced by CL_InitRef().
int(* refimport_t::FS_ReadFile) (const char *name, void **buf)
Definition at line 225 of file tr_public.h.
Referenced by CL_InitRef(), GLSL_GetShaderText(), GLSL_LoadShaderBinary(), LoadRGBEToFloats(), R_LoadBMP(), R_LoadCacheImages(), R_LoadCacheModels(), R_LoadCacheShaders(), R_LoadCubeProbe(), R_LoadDDSImage(), R_LoadJPG(), R_LoadModelShadow(), R_LoadPCX(), R_LoadPreRenderedFont(), R_LoadScalableFont(), R_LoadTGA(), RE_LoadWorldMap(), RE_RegisterAnimation(), RE_RegisterModel(), RE_RegisterSkin(), ReadBufferedFile(), ScanAndLoadShaderFiles(), and ScanAndLoadShaderFilesR1().
void(* refimport_t::FS_WriteFile) (const char *qpath, const void *buffer, int size)
Definition at line 229 of file tr_public.h.
Referenced by CL_InitRef(), GLSL_CompileGPUShader(), GLSL_SaveShaderBinary(), R_LevelShot(), R_SaveCubeProbes(), RB_TakeScreenshot(), RB_TakeScreenshotTGA(), RE_SaveJPG(), and RE_SaveTGA().
void(* refimport_t::GLimp_Init) (glconfig_t *glConfig, windowContext_t *context)
Definition at line 253 of file tr_public.h.
Referenced by CL_InitRef(), and InitOpenGL().
void(* refimport_t::GLimp_SetGamma) (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
Definition at line 256 of file tr_public.h.
Referenced by CL_InitRef(), and R_SetColorMappings().
void(* refimport_t::GLimp_Shutdown) (void)
Definition at line 254 of file tr_public.h.
Referenced by CL_InitRef(), and R_DoGLimpShutdown().
void(* refimport_t::GLimp_SwapFrame) (void)
Definition at line 255 of file tr_public.h.
Referenced by CL_InitRef(), Glimp_ClearScreen(), and RB_SwapBuffers().
void*(* refimport_t::Hunk_Alloc) (unsigned int size, ha_pref pref)
Definition at line 190 of file tr_public.h.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), AddVertexToHashTable(), CL_InitRef(), GeneratePermanentShader(), GeneratePermanentShaderTable(), NewVertexHashTable(), ParseFace(), ParseFlare(), ParseFoliage(), ParseShader(), ParseShaderR1(), ParseTriSurf(), R_AllocAnimation(), R_AllocImage(), R_AllocModel(), R_BuildCubeMaps(), R_CacheImageAlloc(), R_CacheModelAlloc(), R_CacheShaderAllocExt(), R_CreateClusters(), R_CreateFBO(), R_CreateIBO(), R_CreateIBO2(), R_CreateInteractionVBO(), R_CreateSubModelVBOs(), R_CreateSurfaceGridMesh(), R_CreateVBO(), R_CreateVBO2(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_CreateWorldVBO(), R_FindCachedModel(), R_Init(), R_InitSkins(), R_InitSurfMemory(), R_inPVS(), R_LoadEntities(), R_LoadFogs(), R_LoadLightGrid(), R_LoadLights(), R_LoadMarksurfaces(), R_LoadMD3(), R_LoadMD5(), R_LoadMD5Anim(), R_LoadMDC(), R_LoadMDM(), R_LoadMDS(), R_LoadMDX(), R_LoadNodesAndLeafs(), R_LoadPlanes(), R_LoadPSA(), R_LoadPSK(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_LoadVisibility(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_MovePatchSurfacesToHunk(), R_PrecacheInteraction(), R_PrecacheInteractions(), R_RecursiveAddInteractionNode(), RE_LoadWorldMap(), RE_RegisterSkin(), ScanAndLoadShaderFiles(), and ScanAndLoadShaderFilesR1().
void*(* refimport_t::Hunk_AllocateTempMemory) (unsigned int size)
Definition at line 192 of file tr_public.h.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), CL_InitRef(), GLSL_GenerateCheckSum(), GLSL_PrintInfoLog(), GLSL_SaveShaderBinary(), LoadRGBEToFloats(), R_CreateCubeRenderImage(), R_CreateFogImage(), R_CreateIBO2(), R_CreateRenderImageSize(), R_CreateSubModelVBOs(), R_CreateVBO2(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_InitGamma(), R_InitUnitCubeVBO(), R_inPVS(), R_LevelShot(), R_LoadCacheImages(), R_LoadCacheModels(), R_LoadCacheShaders(), R_LoadNodesAndLeafs(), R_LoadTGA(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_MipMap2(), R_SetupLightFrustum(), R_UploadImage(), RB_CountOverDraw(), RB_ReadPixels(), RB_ReadZBuffer(), RB_SwapBuffers(), RE_SaveJPG(), and Upload32().
void(* refimport_t::Hunk_Clear) (void)
stack based memory allocation for per-level things that won't be freed
Definition at line 186 of file tr_public.h.
Referenced by CL_InitRef(), and RE_BeginRegistration().
void(* refimport_t::Hunk_FreeTempMemory) (void *block)
Definition at line 193 of file tr_public.h.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), CL_InitRef(), GLSL_GenerateCheckSum(), GLSL_PrintInfoLog(), GLSL_SaveShaderBinary(), LoadRGBEToBytes(), R_CreateCubeRenderImage(), R_CreateFogImage(), R_CreateIBO2(), R_CreateRenderImageSize(), R_CreateSubModelVBOs(), R_CreateVBO2(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_InitGamma(), R_InitUnitCubeVBO(), R_inPVS(), R_LevelShot(), R_LoadCacheImages(), R_LoadCacheModels(), R_LoadCacheShaders(), R_LoadNodesAndLeafs(), R_LoadTGA(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_MipMap2(), R_SetupLightFrustum(), R_UploadImage(), RB_CountOverDraw(), RB_SwapBuffers(), RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), RB_TakeScreenshotTGA(), RE_SaveJPG(), and Upload32().
void(* refimport_t::IN_Init) (void)
input event handling
Definition at line 249 of file tr_public.h.
Referenced by CL_InitRef().
void(* refimport_t::IN_Restart) (void)
Definition at line 251 of file tr_public.h.
Referenced by CL_InitRef().
void(* refimport_t::IN_Shutdown) (void)
Definition at line 250 of file tr_public.h.
Referenced by CL_InitRef().
int(* refimport_t::Milliseconds) (void)
milliseconds should only be used for profiling, never for anything game related. Get time from the refdef
Definition at line 181 of file tr_public.h.
Referenced by CL_InitRef(), FindShaderInShaderText(), GLSL_CompileGPUShaders(), GLSL_CompileShaderProgram(), GLSL_InitGPUShaders(), R_BuildCubeMaps(), R_CoherentHierachicalCulling(), R_CreateWorldVBO(), R_PrecacheInteractions(), RB_CalculateAdaptation(), RB_ExecuteRenderCommands(), RB_MDM_SurfaceAnim(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderViewFront(), RB_SetGL2D(), RB_ShowImages(), RB_SurfaceAnim(), RE_RenderScene(), RE_StretchRaw(), and Tess_MDM_SurfaceAnim().
int(* refimport_t::RealTime) (qtime_t *qtime)
Definition at line 182 of file tr_public.h.
Referenced by CL_InitRef(), and R_TakeScreenshot().
void(* refimport_t::Sys_GLimpInit) (void)
Definition at line 245 of file tr_public.h.
Referenced by CL_InitRef().
void(* refimport_t::Sys_GLimpSafeInit) (void)
Definition at line 244 of file tr_public.h.
Referenced by CL_InitRef().
void(* refimport_t::Sys_SetEnv) (const char *name, const char *value)
Definition at line 246 of file tr_public.h.
Referenced by CL_InitRef().
void(* refimport_t::Tag_Free) (void)
Definition at line 202 of file tr_public.h.
Referenced by CL_InitRef(), and RE_Shutdown().
void*(* refimport_t::Z_Malloc) (int bytes)
dynamic memory allocator for things that need to be freed
Definition at line 199 of file tr_public.h.
Referenced by CL_InitRef(), DecompressIDATs(), gles_convertLuminance(), gles_convertLuminanceAlpha(), gles_convertRGB(), gles_convertRGB5(), gles_convertRGBA4(), LoadRGBEToBytes(), R_BuildCubeMaps(), R_CacheShaderAllocExt(), R_CreateSurfaceGridMesh(), R_LoadLights(), R_LoadPCX(), R_LoadScalableFont(), R_RenderGlyph(), R_SaveCubeProbes(), RE_LoadDynamicShader(), RE_SaveTGA(), ReadBufferedFile(), and setProjTargetOrigin().
The documentation for this struct was generated from the following file:
src/renderercommon/tr_public.h