ET: Legacy: src/server/sv_bot.c File Reference
sv_bot.c File Reference
Server interface for bots.
#include "server.h"
#include "../botlib/botlib.h"
Functions
int SV_BotAllocateClient (int clientNum)
Attempts to add a bot to the game First player slot is reserved and cannot be used by a bot.
void SV_BotFreeClient (int clientNum)
SV_BotFreeClient.
static __attribute__ ((format(printf, 2, 3)))
BotImport_Print.
void BotImport_Trace (bsp_trace_t *bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
BotImport_Trace.
void BotImport_EntityTrace (bsp_trace_t *bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int entnum, int contentmask)
BotImport_EntityTrace.
int BotImport_PointContents (vec3_t point)
BotImport_PointContents.
int BotImport_inPVS (vec3_t p1, vec3_t p2)
BotImport_inPVS.
char * BotImport_BSPEntityData (void)
BotImport_BSPEntityData.
void BotImport_BSPModelMinsMaxsOrigin (int modelnum, vec3_t angles, vec3_t outmins, vec3_t outmaxs, vec3_t origin)
BotImport_BSPModelMinsMaxsOrigin.
void * BotImport_GetMemory (int size)
BotImport_GetMemory.
void BotImport_FreeMemory (void *ptr)
BotImport_FreeMemory.
void BotImport_FreeZoneMemory (void)
BotImport_FreeZoneMemory.
void * BotImport_HunkAlloc (int size)
BotImport_HunkAlloc.
int BotImport_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
BotImport_DebugPolygonCreate.
bot_debugpoly_t * BotImport_GetFreeDebugPolygon (void)
BotImport_GetFreeDebugPolygon.
void BotImport_DebugPolygonShow (int id, int color, int numPoints, vec3_t *points)
BotImport_DebugPolygonShow.
void BotImport_DebugPolygonDelete (int id)
BotImport_DebugPolygonDelete.
void BotImport_DebugPolygonDeletePointer (bot_debugpoly_t *pPoly)
BotImport_DebugPolygonDeletePointer.
int BotImport_DebugLineCreate (void)
BotImport_DebugLineCreate.
void BotImport_DebugLineDelete (int line)
BotImport_DebugLineDelete.
void BotImport_DebugLineShow (int line, vec3_t start, vec3_t end, int color)
BotImport_DebugLineShow.
void BotClientCommand (int client, char *command)
BotClientCommand.
void BotImport_DrawPolygon (int color, int numpoints, float *points)
BotImport_DrawPolygon.
void SV_BotInitBotLib (void)
SV_BotInitBotLib.
int SV_BotGetConsoleMessage (int client, char *buf, size_t size)
SV_BotGetConsoleMessage.
Variables
static bot_debugpoly_t debugpolygons [MAX_DEBUGPOLYS]
botlib_export_t * botlib_export
Detailed Description
Server interface for bots.
Definition in file sv_bot.c.
Function Documentation
static __attribute__ ((format(printf, 2, 3))) static
BotImport_Print.
Parameters
[in] type
[in] fmt
Definition at line 149 of file sv_bot.c.
void BotClientCommand (int client, char * command)
BotClientCommand.
Parameters
[in] client
[in] command
Definition at line 487 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
char* BotImport_BSPEntityData (void)
BotImport_BSPEntityData.
Returns
Definition at line 244 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_BSPModelMinsMaxsOrigin (int modelnum, vec3_t angles, vec3_t outmins, vec3_t outmaxs, vec3_t origin)
BotImport_BSPModelMinsMaxsOrigin.
Parameters
[in] modelnum
[in] angles
[in] outmins
[in] outmaxs
[in] origin
Definition at line 257 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
int BotImport_DebugLineCreate (void)
BotImport_DebugLineCreate.
Returns
Definition at line 426 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_DebugLineDelete (int line)
BotImport_DebugLineDelete.
Parameters
[in] line
Definition at line 436 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_DebugLineShow (int line, vec3_t start, vec3_t end, int color)
BotImport_DebugLineShow.
Parameters
[in] line
[in] start
[in] end
[in] color
Definition at line 448 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
int BotImport_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
BotImport_DebugPolygonCreate.
Parameters
[in] color
[in] numPoints
[in] points
Returns
Definition at line 342 of file sv_bot.c.
Referenced by BotImport_DebugLineCreate(), SV_BotInitBotLib(), and SV_GameSystemCalls().
void BotImport_DebugPolygonDelete (int id)
BotImport_DebugPolygonDelete.
Parameters
[in] id
Definition at line 408 of file sv_bot.c.
Referenced by BotImport_DebugLineDelete(), SV_BotInitBotLib(), and SV_GameSystemCalls().
void BotImport_DebugPolygonDeletePointer (bot_debugpoly_t * pPoly)
BotImport_DebugPolygonDeletePointer.
Parameters
[out] pPoly
Definition at line 417 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_DebugPolygonShow (int id, int color, int numPoints, vec3_t * points)
BotImport_DebugPolygonShow.
Parameters
id
color
numPoints
points
Definition at line 394 of file sv_bot.c.
Referenced by BotImport_DebugLineShow().
void BotImport_DrawPolygon (int color, int numpoints, float * points)
BotImport_DrawPolygon.
Parameters
[in] color
[in] numpoints
[in] points
Definition at line 4162 of file cl_main.c.
Referenced by BotClientCommand(), and SV_BotInitBotLib().
void BotImport_EntityTrace (bsp_trace_t * bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int entnum, int contentmask)
BotImport_EntityTrace.
Parameters
[in] bsptrace
[in] start
[in] mins
[in] maxs
[in] end
[in] entnum
[in] contentmask
Todo:
: always use bounding box for bot stuff ?
Definition at line 213 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_FreeMemory (void * ptr)
BotImport_FreeMemory.
Parameters
[in,out] ptr
Definition at line 307 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_FreeZoneMemory (void)
BotImport_FreeZoneMemory.
Definition at line 315 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
bot_debugpoly_t* BotImport_GetFreeDebugPolygon (void)
BotImport_GetFreeDebugPolygon.
Returns
Definition at line 372 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void* BotImport_GetMemory (int size)
BotImport_GetMemory.
Parameters
size
Returns
Definition at line 295 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void* BotImport_HunkAlloc (int size)
BotImport_HunkAlloc.
Parameters
[in] size
Returns
Definition at line 325 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
int BotImport_inPVS (vec3_t p1, vec3_t p2)
BotImport_inPVS.
Parameters
[in] p1
[in] p2
Returns
Definition at line 235 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
int BotImport_PointContents (vec3_t point)
BotImport_PointContents.
Parameters
[in] point
Returns
Definition at line 224 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
void BotImport_Trace (bsp_trace_t * bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
BotImport_Trace.
Parameters
[in] bsptrace
[in] start
[in] mins
[in] maxs
[in] end
[in] passent
[in] contentmask
Definition at line 197 of file sv_bot.c.
Referenced by SV_BotInitBotLib().
int SV_BotAllocateClient (int clientNum)
Attempts to add a bot to the game First player slot is reserved and cannot be used by a bot.
If the specified slot is taken or private, the first free slot starting from the public slots will be returned.
Parameters
[in] clientNum has to be bigger than 0
Returns
assigned client slot or -1 if it fails to allocate one
Definition at line 53 of file sv_bot.c.
Referenced by SV_GameSystemCalls().
void SV_BotFreeClient (int clientNum)
SV_BotFreeClient.
Parameters
[in] clientNum
Definition at line 115 of file sv_bot.c.
Referenced by SV_DropClient().
int SV_BotGetConsoleMessage (int client, char * buf, size_t size)
SV_BotGetConsoleMessage.
Parameters
[in] client
buf - unused
size - unused
Returns
Definition at line 561 of file sv_bot.c.
Referenced by SV_GameSystemCalls().
void SV_BotInitBotLib (void)
SV_BotInitBotLib.
Only called at main exe startup, not for each game.
Definition at line 510 of file sv_bot.c.
Referenced by SV_CloseAttackLog(), and SV_Init().
Variable Documentation
botlib_export_t* botlib_export
Definition at line 39 of file sv_game.c.
bot_debugpoly_t debugpolygons[MAX_DEBUGPOLYS] static
Definition at line 39 of file sv_bot.c.