ET: Legacy: src/server/sv_game.c File Reference
sv_game.c File Reference
Interface to the game dll.
#include "server.h"
#include "../botlib/botlib.h"
Functions
int SV_NumForGentity (sharedEntity_t *ent)
SV_NumForGentity.
sharedEntity_t * SV_GentityNum (int num)
SV_GentityNum.
playerState_t * SV_GameClientNum (int num)
SV_GameClientNum.
svEntity_t * SV_SvEntityForGentity (sharedEntity_t *gEnt)
SV_SvEntityForGentity.
sharedEntity_t * SV_GEntityForSvEntity (svEntity_t *svEnt)
SV_GEntityForSvEntity.
void SV_GameSendServerCommand (int clientNum, const char *text)
Sends a command string to a client.
void SV_GameDropClient (int clientNum, const char *reason, int length)
Disconnects the client with a message.
void SV_SetBrushModel (sharedEntity_t *ent, const char *name)
Sets mins and maxs for inline bmodels.
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
Also checks portalareas so that doors block sight.
qboolean SV_inPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Does NOT check portalareas.
void SV_AdjustAreaPortalState (sharedEntity_t *ent, qboolean open)
SV_AdjustAreaPortalState.
qboolean SV_EntityContact (const vec3_t mins, const vec3_t maxs, const sharedEntity_t *gEnt, const qboolean capsule)
SV_EntityContact.
void SV_GetServerinfo (char *buffer, unsigned int bufferSize)
SV_GetServerinfo.
void SV_LocateGameData (sharedEntity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *clients, int sizeofGameClient)
SV_LocateGameData.
void SV_GetUsercmd (int clientNum, usercmd_t *cmd)
SV_GetUsercmd.
static int SV_SendBinaryMessage (int cno, char *buf, int buflen)
SV_SendBinaryMessage.
static int SV_BinaryMessageStatus (int cno)
SV_BinaryMessageStatus.
void SV_GameBinaryMessageReceived (int cno, const char *buf, int buflen, int commandTime)
SV_GameBinaryMessageReceived.
static int FloatAsInt (float f)
FloatAsInt.
int S_RegisterSound (const char *name, qboolean compressed)
S_RegisterSound.
int S_GetSoundLength (sfxHandle_t sfxHandle)
Returns how long the sound lasts in milliseconds.
intptr_t SV_GameSystemCalls (intptr_t *args)
The module is making a system call.
void SV_ShutdownGameProgs (void)
Called every time a map changes.
static void SV_InitGameVM (qboolean restart)
Called for both a full init and a restart.
void SV_RestartGameProgs (void)
Called on a map_restart, but not on a normal map change.
void SV_InitGameProgs (void)
Called on a normal map change, not on a map_restart.
qboolean SV_GameCommand (void)
See if the current console command is claimed by the game.
qboolean SV_GetTag (int clientNum, int tagFileNumber, char *tagname, orientation_t *orientation)
SV_GetTag.
Variables
botlib_export_t * botlib_export
Detailed Description
Interface to the game dll.
Definition in file sv_game.c.
Function Documentation
static int FloatAsInt (float f) static
FloatAsInt.
Parameters
[in] f
Returns
Definition at line 413 of file sv_game.c.
Referenced by SV_GameSystemCalls().
int S_GetSoundLength (sfxHandle_t sfxHandle)
Returns how long the sound lasts in milliseconds.
Parameters
sfxHandle
Returns
Returns how long the sound lasts in milliseconds.
Parameters
sfxHandle
Returns
Definition at line 583 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), FloatAsInt(), and SV_GameSystemCalls().
int S_RegisterSound (const char * name, qboolean compressed)
S_RegisterSound.
Parameters
[in] name
[in] compressed
Returns
Parameters
name
compressed
Returns
Note
bk001119 - added boolean flag, match client/snd_public.h
Definition at line 515 of file snd_main.c.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), FloatAsInt(), and SV_GameSystemCalls().
void SV_AdjustAreaPortalState (sharedEntity_t * ent, qboolean open)
SV_AdjustAreaPortalState.
Parameters
[in] ent
[in] open
Definition at line 259 of file sv_game.c.
Referenced by SV_GameSystemCalls().
static int SV_BinaryMessageStatus (int cno) static
SV_BinaryMessageStatus.
Parameters
[in] cno
Returns
Definition at line 374 of file sv_game.c.
Referenced by SV_GameSystemCalls().
qboolean SV_EntityContact (const vec3_t mins, const vec3_t maxs, const sharedEntity_t * gEnt, const qboolean capsule)
SV_EntityContact.
Parameters
[in] mins
[in] maxs
[in] gEnt
[in] capsule
Returns
Definition at line 279 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_GameBinaryMessageReceived (int cno, const char * buf, int buflen, int commandTime)
SV_GameBinaryMessageReceived.
Parameters
[in] cno
[in] buf
[in] buflen
[in] commandTime
Definition at line 401 of file sv_game.c.
Referenced by SV_ParseBinaryMessage().
playerState_t* SV_GameClientNum (int num)
SV_GameClientNum.
Parameters
[in] num
Returns
Definition at line 77 of file sv_game.c.
Referenced by SV_BuildClientSnapshot(), SV_CalcPings(), SV_DemoReadAllPlayerState(), SV_DemoReadRefreshEntities(), SV_DemoReadRefreshPlayersHealth(), SV_DemoWriteAllPlayerState(), SV_Status_f(), and SVC_Status().
qboolean SV_GameCommand (void)
See if the current console command is claimed by the game.
Returns
Definition at line 785 of file sv_game.c.
Referenced by Cmd_ExecuteString().
void SV_GameDropClient (int clientNum, const char * reason, int length)
Disconnects the client with a message.
Parameters
[in] clientNum
[in] reason
[in] length
Definition at line 148 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_GameSendServerCommand (int clientNum, const char * text)
Sends a command string to a client.
Parameters
[in] clientNum
[in] text
Definition at line 115 of file sv_game.c.
Referenced by SV_DemoReadGameCommand(), and SV_GameSystemCalls().
intptr_t SV_GameSystemCalls (intptr_t * args)
The module is making a system call.
Parameters
[in] args
Returns
Definition at line 429 of file sv_game.c.
Referenced by SV_InitGameProgs().
sharedEntity_t* SV_GEntityForSvEntity (svEntity_t * svEnt)
SV_GEntityForSvEntity.
Parameters
[in] svEnt
Returns
Definition at line 103 of file sv_game.c.
Referenced by SV_AreaEntities_r().
sharedEntity_t* SV_GentityNum (int num)
SV_GentityNum.
Parameters
[in] num
Returns
Definition at line 65 of file sv_game.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_BotAllocateClient(), SV_BuildClientSnapshot(), SV_ClientEnterWorld(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_CreateBaseline(), SV_DemoReadAllEntityShared(), SV_DemoReadAllEntityState(), SV_DemoReadRefreshEntities(), SV_DemoReadRefreshPlayersHealth(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DirectConnect(), SV_GEntityForSvEntity(), SV_PointContents(), and SV_SpawnServer().
void SV_GetServerinfo (char * buffer, unsigned int bufferSize)
SV_GetServerinfo.
Parameters
[out] buffer
[in] bufferSize
Definition at line 299 of file sv_game.c.
Referenced by SV_GameSystemCalls().
qboolean SV_GetTag (int clientNum, int tagFileNumber, char * tagname, orientation_t * orientation)
SV_GetTag.
Parameters
[in] clientNum - unused
[in] tagFileNumber
[out] tagname
[out] orientation
Returns
qfalse if unable to retrieve tag information for this client
Definition at line 803 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_GetUsercmd (int clientNum, usercmd_t * cmd)
SV_GetUsercmd.
Parameters
[in] clientNum
[out] cmd
Definition at line 332 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_InitGameProgs (void)
Called on a normal map change, not on a map_restart.
Definition at line 766 of file sv_game.c.
Referenced by SV_SpawnServer().
static void SV_InitGameVM (qboolean restart) static
Called for both a full init and a restart.
Parameters
[in] restart
Definition at line 717 of file sv_game.c.
Referenced by SV_InitGameProgs(), and SV_RestartGameProgs().
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
Also checks portalareas so that doors block sight.
Parameters
[in] p1
[in] p2
Returns
Definition at line 200 of file sv_game.c.
Referenced by BotImport_inPVS(), and SV_GameSystemCalls().
qboolean SV_inPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Does NOT check portalareas.
Parameters
[in] p1
[in] p2
Returns
Definition at line 233 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_LocateGameData (sharedEntity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * clients, int sizeofGameClient)
SV_LocateGameData.
Parameters
[in] gEnts
[in] numGEntities
[in] sizeofGEntity_t
[in] clients
[in] sizeofGameClient
Definition at line 316 of file sv_game.c.
Referenced by SV_GameSystemCalls().
int SV_NumForGentity (sharedEntity_t * ent)
SV_NumForGentity.
Todo:
TODO: These functions must be used instead of pointer arithmetic, because the game allocates gentities with private information after the server shared part
Parameters
[in] ent
Returns
Note
Unused
Definition at line 53 of file sv_game.c.
void SV_RestartGameProgs (void)
Called on a map_restart, but not on a normal map change.
Definition at line 745 of file sv_game.c.
Referenced by SV_MapRestart_f().
static int SV_SendBinaryMessage (int cno, char * buf, int buflen) static
SV_SendBinaryMessage.
Parameters
[in] cno
[out] buf
[in] buflen
Returns
1 if message is in queue - 0 not sent (since 2.76)
Definition at line 348 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_SetBrushModel (sharedEntity_t * ent, const char * name)
Sets mins and maxs for inline bmodels.
Parameters
[in,out] ent
[in] name
Todo:
: remove
Definition at line 166 of file sv_game.c.
Referenced by SV_GameSystemCalls().
void SV_ShutdownGameProgs (void)
Called every time a map changes.
Definition at line 697 of file sv_game.c.
Referenced by Hunk_CheckMark(), Hunk_Clear(), SV_Shutdown(), and SV_SpawnServer().
svEntity_t* SV_SvEntityForGentity (sharedEntity_t * gEnt)
SV_SvEntityForGentity.
Parameters
[in] gEnt
Returns
Definition at line 89 of file sv_game.c.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_AdjustAreaPortalState(), SV_LinkEntity(), and SV_UnlinkEntity().
Variable Documentation
botlib_export_t* botlib_export
Definition at line 39 of file sv_game.c.