ET: Legacy: src/server/sv_ccmds.c File Reference
sv_ccmds.c File Reference
OPERATOR CONSOLE ONLY COMMANDS.
#include "server.h"
#include <time.h>
Functions
static client_t * SV_GetPlayerByName (void)
Returns the player with name from Cmd_Argv(1)
static void SV_Map_f (void)
Restart the server on a different map.
static qboolean SV_CheckTransitionGameState (gamestate_t new_gs, gamestate_t old_gs)
SV_CheckTransitionGameState.
static qboolean SV_TransitionGameState (gamestate_t new_gs, gamestate_t old_gs, int delay)
SV_TransitionGameState.
void MSG_PrioritiseEntitystateFields (void)
MSG_PrioritiseEntitystateFields.
void MSG_PrioritisePlayerStateFields (void)
MSG_PrioritisePlayerStateFields.
static void SV_FieldInfo_f (void)
SV_FieldInfo_f.
static void SV_MapRestart_f (void)
Completely restarts a level, but doesn't send a new gamestate to the clients. This allows fair starts with variable load times.
void SV_TempBanNetAddress (netadr_t address, int length)
SV_TempBanNetAddress.
qboolean SV_TempBanIsBanned (netadr_t address)
SV_TempBanIsBanned.
static void SV_Status_f (void)
SV_Status_f.
static void SV_ConSay_f (void)
SV_ConSay_f.
void SV_Heartbeat_f (void)
Also called by SV_DropClient, SV_DirectConnect, and SV_SpawnServer.
static void SV_Serverinfo_f (void)
Examine the serverinfo string.
static void SV_Systeminfo_f (void)
Examine the serverinfo string.
static void SV_DumpUser_f (void)
Examine all a users info strings.
static void SV_KillServer_f (void)
SV_KillServer_f.
static void SV_CompleteMapName (char *args, int argNum)
SV_CompleteMapName.
void SV_GameCompleteStatus_f (void)
SV_GameCompleteStatus_f.
void SV_UptimeReset (void)
SV_UptimeReset.
void SV_Uptime_f (void)
Prints the server uptime.
void SV_AddOperatorCommands (void)
SV_AddOperatorCommands.
void SV_RemoveOperatorCommands (void)
SV_RemoveOperatorCommands.
Variables
static time_t uptimeSince
Detailed Description
OPERATOR CONSOLE ONLY COMMANDS.
These commands can only be entered from stdin or by a remote operator datagram
Definition in file sv_ccmds.c.
Function Documentation
void MSG_PrioritiseEntitystateFields (void)
MSG_PrioritiseEntitystateFields.
Definition at line 1219 of file msg.c.
Referenced by SV_FieldInfo_f(), and SV_TransitionGameState().
void MSG_PrioritisePlayerStateFields (void)
MSG_PrioritisePlayerStateFields.
Definition at line 1964 of file msg.c.
Referenced by SV_FieldInfo_f(), and SV_TransitionGameState().
void SV_AddOperatorCommands (void)
SV_AddOperatorCommands.
Definition at line 692 of file sv_ccmds.c.
Referenced by SV_Init().
static qboolean SV_CheckTransitionGameState (gamestate_t new_gs, gamestate_t old_gs) static
SV_CheckTransitionGameState.
Parameters
[in] new_gs
[in] old_gs
Returns
Definition at line 169 of file sv_ccmds.c.
Referenced by SV_TransitionGameState().
static void SV_CompleteMapName (char * args, int argNum) static
SV_CompleteMapName.
Parameters
args - unused
[in] argNum
Definition at line 639 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_ConSay_f (void) static
SV_ConSay_f.
Definition at line 522 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_DumpUser_f (void) static
Examine all a users info strings.
Todo:
FIXME: move to game
Definition at line 597 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_FieldInfo_f (void) static
SV_FieldInfo_f.
Definition at line 231 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
void SV_GameCompleteStatus_f (void)
SV_GameCompleteStatus_f.
Definition at line 650 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static client_t* SV_GetPlayerByName (void) static
Returns the player with name from Cmd_Argv(1)
Returns
Definition at line 52 of file sv_ccmds.c.
Referenced by SV_DumpUser_f().
void SV_Heartbeat_f (void)
Also called by SV_DropClient, SV_DirectConnect, and SV_SpawnServer.
Definition at line 562 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands(), SV_DirectConnect(), SV_DropClient(), and SV_SpawnServer().
static void SV_KillServer_f (void) static
SV_KillServer_f.
Definition at line 628 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_Map_f (void) static
Restart the server on a different map.
Definition at line 103 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_MapRestart_f (void) static
Completely restarts a level, but doesn't send a new gamestate to the clients. This allows fair starts with variable load times.
Definition at line 241 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
void SV_RemoveOperatorCommands (void)
SV_RemoveOperatorCommands.
Definition at line 733 of file sv_ccmds.c.
Referenced by SV_Shutdown().
static void SV_Serverinfo_f (void) static
Examine the serverinfo string.
Definition at line 570 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_Status_f (void) static
SV_Status_f.
Definition at line 456 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
static void SV_Systeminfo_f (void) static
Examine the serverinfo string.
Definition at line 586 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
qboolean SV_TempBanIsBanned (netadr_t address)
SV_TempBanIsBanned.
Parameters
[in] address
Returns
Definition at line 435 of file sv_ccmds.c.
Referenced by SV_GetChallenge(), and SV_isValidClient().
void SV_TempBanNetAddress (netadr_t address, int length)
SV_TempBanNetAddress.
Parameters
[in] address
[in] length
Definition at line 400 of file sv_ccmds.c.
Referenced by SV_GameDropClient().
static qboolean SV_TransitionGameState (gamestate_t new_gs, gamestate_t old_gs, int delay) static
SV_TransitionGameState.
Parameters
[in] new_gs
[in] old_gs
delay - unused
Returns
Definition at line 201 of file sv_ccmds.c.
Referenced by SV_MapRestart_f().
void SV_Uptime_f (void)
Prints the server uptime.
Definition at line 666 of file sv_ccmds.c.
Referenced by SV_AddOperatorCommands().
void SV_UptimeReset (void)
SV_UptimeReset.
Definition at line 658 of file sv_ccmds.c.
Referenced by SV_Init().
Variable Documentation
time_t uptimeSince static
Definition at line 46 of file sv_ccmds.c.
Referenced by SV_Uptime_f(), and SV_UptimeReset().