ET: Legacy: src/server/sv_client.c File Reference
sv_client.c File Reference
Server code for dealing with clients.
#include "server.h"
Data Structures
struct ucmd_t
Functions
static void SV_CloseDownload (client_t *cl)
Clear/free any download vars.
void SV_GetChallenge (netadr_t from)
A "getchallenge" OOB command has been received.
static qboolean SV_isClientIPValidToConnect (netadr_t from)
Determines if a client is allowed to connect when sv_ipMaxClients is set.
static qboolean SV_IsValidUserinfo (netadr_t from, const char *userinfo)
Screening of userinfo keys and values.
static qboolean SV_isValidClient (netadr_t from, const char *userinfo)
Screening of user before 'real connection' and the client enters the world (using a slot)
void SV_DirectConnect (netadr_t from)
A "connect" OOB command has been received.
void SV_DropClient (client_t *drop, const char *reason)
Called when the player is totally leaving the server, either willingly or unwillingly. This is NOT called if the entire server is quiting or crashing – SV_FinalCommand() will handle that.
void SV_SendClientGameState (client_t *client)
Sends the first message from the server to a connected client. This will be sent on the initial connection and upon each new map load. It will be resent if the client acknowledges a later message but has the wrong gamestate.
void SV_ClientEnterWorld (client_t *client, usercmd_t *cmd)
SV_ClientEnterWorld.
static void SV_StopDownload_f (client_t *cl)
Abort a download if in progress.
static void SV_DoneDownload_f (client_t *cl)
Downloads are finished.
void SV_NextDownload_f (client_t *cl)
The argument will be the last acknowledged block from the client, it should be the same as cl->downloadClientBlock.
void SV_BeginDownload_f (client_t *cl)
SV_BeginDownload_f.
void SV_WWWDownload_f (client_t *cl)
SV_WWWDownload_f.
void SV_BadDownload (client_t *cl, msg_t *msg)
Abort an attempted download.
static qboolean SV_CheckFallbackURL (client_t *cl, msg_t *msg)
sv_wwwFallbackURL can be used to redirect clients to a web URL in case direct ftp/http didn't work (or is disabled on client's end)
static qboolean SV_CheckDownloadAllowed (client_t *cl, msg_t *msg)
Check if we are able to share the file.
static qboolean SV_SetupDownloadFile (client_t *cl, msg_t *msg)
We open the file here.
static qboolean SV_WriteDownloadToClient (client_t *cl, msg_t *msg)
Check to see if the client wants a file, open it if needed and start pumping the client.
int SV_SendQueuedMessages (void)
Send one round of fragments, or queued messages to all clients that have data pending.
int SV_SendDownloadMessages (void)
Send one round of download messages to all clients.
static void SV_Disconnect_f (client_t *cl)
The client is going to disconnect, so remove the connection immediately.
static void SV_VerifyPaks_f (client_t *cl)
SV_VerifyPaks_f.
static void SV_ResetPureClient_f (client_t *cl)
SV_ResetPureClient_f.
void SV_UserinfoChanged (client_t *cl)
Pull specific info from a newly changed userinfo string into a more C friendly form.
void SV_UpdateUserinfo_f (client_t *cl)
SV_UpdateUserinfo_f.
void SV_ExecuteClientCommand (client_t *cl, const char *s, qboolean clientOK, qboolean premaprestart)
Also called by bot code.
static qboolean SV_ClientCommand (client_t *cl, msg_t *msg, qboolean premaprestart)
SV_ClientCommand.
void SV_ClientThink (client_t *cl, usercmd_t *cmd)
Also called by bot code.
static void SV_UserMove (client_t *cl, msg_t *msg, qboolean delta)
SV_UserMove.
static void SV_ParseBinaryMessage (client_t *cl, msg_t *msg)
SV_ParseBinaryMessage.
void SV_ExecuteClientMessage (client_t *cl, msg_t *msg)
SV_ExecuteClientMessage.
Variables
static ucmd_t ucmds []
Detailed Description
Server code for dealing with clients.
Definition in file sv_client.c.
Function Documentation
void SV_BadDownload (client_t * cl, msg_t * msg)
Abort an attempted download.
Parameters
[in] cl
[in] msg
Definition at line 1018 of file sv_client.c.
Referenced by SV_CheckDownloadAllowed(), and SV_SetupDownloadFile().
void SV_BeginDownload_f (client_t * cl)
SV_BeginDownload_f.
Parameters
[in,out] cl
Definition at line 924 of file sv_client.c.
static qboolean SV_CheckDownloadAllowed (client_t * cl, msg_t * msg) static
Check if we are able to share the file.
Parameters
[in] cl
[in] msg
Returns
Definition at line 1060 of file sv_client.c.
Referenced by SV_SetupDownloadFile().
static qboolean SV_CheckFallbackURL (client_t * cl, msg_t * msg) static
sv_wwwFallbackURL can be used to redirect clients to a web URL in case direct ftp/http didn't work (or is disabled on client's end)
Parameters
[in] cl
[in] msg
Returns
return true when a redirect URL message was filled up when the cvar is set to something, the download server will effectively never use a legacy download strategy
Definition at line 1036 of file sv_client.c.
Referenced by SV_SetupDownloadFile().
static qboolean SV_ClientCommand (client_t * cl, msg_t * msg, qboolean premaprestart) static
SV_ClientCommand.
Parameters
[in,out] cl
[in] msg
[in] premaprestart
Returns
Definition at line 1847 of file sv_client.c.
Referenced by SV_ExecuteClientMessage().
void SV_ClientEnterWorld (client_t * client, usercmd_t * cmd)
SV_ClientEnterWorld.
Parameters
[in,out] client
[in] cmd
Definition at line 771 of file sv_client.c.
Referenced by SV_MapRestart_f(), and SV_UserMove().
void SV_ClientThink (client_t * cl, usercmd_t * cmd)
Also called by bot code.
Parameters
[in,out] cl
[in] cmd
Definition at line 1929 of file sv_client.c.
Referenced by SV_GameSystemCalls(), and SV_UserMove().
static void SV_CloseDownload (client_t * cl) static
Clear/free any download vars.
Parameters
[in,out] cl
Definition at line 821 of file sv_client.c.
Referenced by SV_BadDownload(), SV_BeginDownload_f(), SV_DropClient(), SV_NextDownload_f(), SV_StopDownload_f(), and SV_WWWDownload_f().
void SV_DirectConnect (netadr_t from)
A "connect" OOB command has been received.
Parameters
[in] from
Definition at line 301 of file sv_client.c.
Referenced by SV_ConnectionlessPacket().
static void SV_Disconnect_f (client_t * cl) static
The client is going to disconnect, so remove the connection immediately.
Parameters
[in] cl
Todo:
FIXME: move to game?
Definition at line 1405 of file sv_client.c.
static void SV_DoneDownload_f (client_t * cl) static
Downloads are finished.
Parameters
[in] cl
Definition at line 869 of file sv_client.c.
void SV_DropClient (client_t * drop, const char * reason)
Called when the player is totally leaving the server, either willingly or unwillingly. This is NOT called if the entire server is quiting or crashing – SV_FinalCommand() will handle that.
Parameters
[in,out] drop
[in] reason
Definition at line 598 of file sv_client.c.
Referenced by SV_AddServerCommand(), SV_CheckTimeouts(), SV_ClientCommand(), SV_DemoReadClientConfigString(), SV_DirectConnect(), SV_Disconnect_f(), SV_ExecuteClientMessage(), SV_GameDropClient(), SV_MapRestart_f(), SV_NextDownload_f(), SV_SendClientIdle(), SV_SendClientMessages(), SV_SendClientSnapshot(), SV_SetupDownloadFile(), SV_SpawnServer(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), and SV_WWWDownload_f().
void SV_ExecuteClientCommand (client_t * cl, const char * s, qboolean clientOK, qboolean premaprestart)
Also called by bot code.
Parameters
[in] cl
[in] s
[in] clientOK
[in] premaprestart
Definition at line 1789 of file sv_client.c.
Referenced by BotClientCommand(), SV_ClientCommand(), SV_ClientEnterWorld(), SV_DemoReadClientCommand(), SV_DemoReadClientUserinfo(), SV_DemoStartPlayback(), and SV_GameSystemCalls().
void SV_ExecuteClientMessage (client_t * cl, msg_t * msg)
SV_ExecuteClientMessage.
Parameters
[in,out] cl
[in] msg
Definition at line 2106 of file sv_client.c.
Referenced by SV_PacketEvent().
void SV_GetChallenge (netadr_t from)
A "getchallenge" OOB command has been received.
Parameters
[in] from
Returns
challenge number that can be used in a subsequent connectResponse command.
We do this to prevent denial of service attacks that flood the server with invalid connection IPs. With a challenge, they must give a valid IP address.
Todo:
: deal with restricted filesystem - done with sv_pure check ?
Definition at line 52 of file sv_client.c.
Referenced by SV_ConnectionlessPacket().
static qboolean SV_isClientIPValidToConnect (netadr_t from) static
Determines if a client is allowed to connect when sv_ipMaxClients is set.
Parameters
[in] from
Returns
qtrue for valid clients
Note
maybe we want to have more control over localhost clients in future. So we let localhost connect since bots don't connect from SV_DirectConnect where SV_IsFakeIpConnection is done.
Todo:
: see above note: We might use a free flag of sv_protect cvar to include local addresses
Definition at line 139 of file sv_client.c.
Referenced by SV_isValidClient().
static qboolean SV_isValidClient (netadr_t from, const char * userinfo) static
Screening of user before 'real connection' and the client enters the world (using a slot)
Parameters
[in] from
[in] userinfo
Todo:
: add some logging in for admins? we only do developer prints when a client is filtered
Definition at line 249 of file sv_client.c.
Referenced by SV_DirectConnect().
static qboolean SV_IsValidUserinfo (netadr_t from, const char * userinfo) static
Screening of userinfo keys and values.
Parameters
[in] from
[in] userinfo
Todo:
: add some logging in for admins? we only do developer prints when a client is filtered
Todo:
: check existence of all keys and do some sanity checks
Todo:
: check rate in between 0 and sv_maxrate?
Todo:
:
Todo:
: auth service?
Definition at line 200 of file sv_client.c.
Referenced by SV_isValidClient().
void SV_NextDownload_f (client_t * cl)
The argument will be the last acknowledged block from the client, it should be the same as cl->downloadClientBlock.
Parameters
[in,out] cl
Todo:
: this is bad... the client will never parse the disconnect message
Definition at line 893 of file sv_client.c.
static void SV_ParseBinaryMessage (client_t * cl, msg_t * msg) static
SV_ParseBinaryMessage.
Parameters
[in] cl
[in] msg
Definition at line 2080 of file sv_client.c.
Referenced by SV_ExecuteClientMessage().
static void SV_ResetPureClient_f (client_t * cl) static
SV_ResetPureClient_f.
Parameters
[out] cl
Definition at line 1609 of file sv_client.c.
void SV_SendClientGameState (client_t * client)
Sends the first message from the server to a connected client. This will be sent on the initial connection and upon each new map load. It will be resent if the client acknowledges a later message but has the wrong gamestate.
Parameters
[in,out] client
Definition at line 693 of file sv_client.c.
Referenced by SV_DoneDownload_f(), SV_ExecuteClientMessage(), SV_UserMove(), and SV_WWWDownload_f().
int SV_SendDownloadMessages (void)
Send one round of download messages to all clients.
Returns
Definition at line 1370 of file sv_client.c.
Referenced by SV_SendQueuedPackets().
int SV_SendQueuedMessages (void)
Send one round of fragments, or queued messages to all clients that have data pending.
Returns
The shortest time interval for sending next packet to client
Definition at line 1338 of file sv_client.c.
Referenced by SV_SendQueuedPackets().
static qboolean SV_SetupDownloadFile (client_t * cl, msg_t * msg) static
We open the file here.
Parameters
[in,out] cl
[in] msg
Returns
Todo:
: we need to abstract this to an independant module for maximum configuration/usability by server admins
Todo:
: I could rework that, it's crappy
Definition at line 1106 of file sv_client.c.
Referenced by SV_WriteDownloadToClient().
static void SV_StopDownload_f (client_t * cl) static
Abort a download if in progress.
Parameters
[in] cl
Definition at line 855 of file sv_client.c.
void SV_UpdateUserinfo_f (client_t * cl)
SV_UpdateUserinfo_f.
Parameters
[in] cl
Definition at line 1730 of file sv_client.c.
Referenced by SV_CheckClientUserinfoTimer(), and SV_DemoReadClientUserinfo().
void SV_UserinfoChanged (client_t * cl)
Pull specific info from a newly changed userinfo string into a more C friendly form.
Parameters
[in,out] cl
Definition at line 1619 of file sv_client.c.
Referenced by SV_DirectConnect(), and SV_UpdateUserinfo_f().
static void SV_UserMove (client_t * cl, msg_t * msg, qboolean delta) static
SV_UserMove.
The message usually contains all the movement commands that were in the last three packets, so that the information in dropped packets can be recovered.
On very fast clients, there may be multiple usercmd packed into each of the backup packets.
Parameters
cl
msg
delta
Definition at line 1955 of file sv_client.c.
Referenced by SV_ExecuteClientMessage().
static void SV_VerifyPaks_f (client_t * cl) static
SV_VerifyPaks_f.
If we are pure, disconnect the client if they do no meet the following conditions:
the first two checksums match our view of cgame and ui DLLs Wolf specific: the checksum is the checksum of the pk3 we found the DLL in
there are no any additional checksums that we do not have
This routine would be a bit simpler with a goto but i abstained
Parameters
[in,out] cl
Definition at line 1423 of file sv_client.c.
static qboolean SV_WriteDownloadToClient (client_t * cl, msg_t * msg) static
Check to see if the client wants a file, open it if needed and start pumping the client.
Parameters
[in,out] cl
[in] msg
Returns
Definition at line 1221 of file sv_client.c.
Referenced by SV_SendDownloadMessages().
void SV_WWWDownload_f (client_t * cl)
SV_WWWDownload_f.
Parameters
[in,out] cl
Definition at line 944 of file sv_client.c.
Variable Documentation
ucmd_t ucmds[] static
Initial value:
=
{
    { "userinfo",   SV_UpdateUserinfo_f,  qfalse },
    { "disconnect", SV_Disconnect_f,      qtrue  },
    { "cp",         SV_VerifyPaks_f,      qfalse },
    { "vdr",        SV_ResetPureClient_f, qfalse },
    { "download",   SV_BeginDownload_f,   qfalse },
    { "nextdl",     SV_NextDownload_f,    qfalse },
    { "stopdl",     SV_StopDownload_f,    qfalse },
    { "donedl",     SV_DoneDownload_f,    qfalse },
    { "wwwdl",      SV_WWWDownload_f,     qfalse },
    { NULL,         NULL,                 qfalse }
}
Definition at line 1768 of file sv_client.c.