ET: Legacy: src/server/sv_init.c File Reference
sv_init.c File Reference
#include "server.h"
Functions
void SV_SetConfigstringNoUpdate (int index, const char *val)
SV_SetConfigstringNoUpdate.
void SV_SetConfigstring (int index, const char *val)
SV_SetConfigstring.
void SV_UpdateConfigStrings (void)
Updates the configstring.
void SV_GetConfigstring (int index, char *buffer, unsigned int bufferSize)
SV_GetConfigstring.
void SV_SetUserinfo (int index, const char *val)
SV_SetUserinfo.
void SV_GetUserinfo (int index, char *buffer, unsigned int bufferSize)
SV_GetUserinfo.
void SV_CreateBaseline (void)
Entity baselines are used to compress non-delta messages to the clients – only the fields that differ from the baseline will be transmitted.
void SV_BoundMaxClients (int minimum)
SV_BoundMaxClients.
static void SV_SetNumSnapshotEntities (void)
Allocates new snapshot entities.
void SV_Startup (void)
Called when a host starts a map when it wasn't running one before. Successive map or map_restart commands will NOT cause this to be called, unless the game is exited to the menu system first.
void SV_ChangeMaxClients (void)
SV_ChangeMaxClients.
void SV_SetExpectedHunkUsage (const char *mapname)
Sets com_expectedhunkusage, so the client knows how to draw the percentage bar.
void SV_DemoChangeMaxClients (void)
Change sv_maxclients and move real clients slots when a demo is playing or stopped.
static void SV_ClearServer (void)
SV_ClearServer.
void SV_TouchCGameDLL (void)
Touch the cgame DLL so that a pure client (with DLL sv_pure support) can load do the correct checks.
void SV_SpawnServer (const char *server)
Change the server to a new map, taking all connected clients along with it. This is NOT called for map_restart.
void SV_WriteAttackLog (const char *log)
SV_WriteAttackLog.
void SV_InitAttackLog ()
SV_InitAttackLog.
void SV_CloseAttackLog ()
SV_CloseAttackLog.
void SV_BotInitBotLib (void)
Only called at main exe startup, not for each game.
void SV_Init (void)
SV_Init.
void SV_FinalCommand (const char *cmd, qboolean disconnect)
Used by SV_Shutdown to send a final message to all connected clients before the server goes down. The messages are sent immediately, not just stuck on the outgoing message list, because the server is going to totally exit after returning from this function.
void SV_Shutdown (const char *finalmsg)
Called when each game quits, before Sys_Quit or Sys_Error.
Variables
int attHandle = 0
Function Documentation
void SV_BotInitBotLib (void)
Only called at main exe startup, not for each game.
Only called at main exe startup, not for each game.
Definition at line 510 of file sv_bot.c.
Referenced by SV_CloseAttackLog(), and SV_Init().
void SV_BoundMaxClients (int minimum)
SV_BoundMaxClients.
Parameters
[in] minimum
Definition at line 304 of file sv_init.c.
Referenced by SV_ChangeMaxClients(), SV_DemoChangeMaxClients(), and SV_Startup().
void SV_ChangeMaxClients (void)
SV_ChangeMaxClients.
Definition at line 368 of file sv_init.c.
Referenced by SV_SpawnServer().
static void SV_ClearServer (void) static
SV_ClearServer.
Definition at line 605 of file sv_init.c.
Referenced by SV_Shutdown(), and SV_SpawnServer().
void SV_CloseAttackLog ()
SV_CloseAttackLog.
Definition at line 958 of file sv_init.c.
Referenced by SV_Shutdown().
void SV_CreateBaseline (void)
Entity baselines are used to compress non-delta messages to the clients – only the fields that differ from the baseline will be transmitted.
Definition at line 280 of file sv_init.c.
Referenced by SV_SpawnServer().
void SV_DemoChangeMaxClients (void)
Change sv_maxclients and move real clients slots when a demo is playing or stopped.
Definition at line 490 of file sv_init.c.
Referenced by SV_SpawnServer().
void SV_FinalCommand (const char * cmd, qboolean disconnect)
Used by SV_Shutdown to send a final message to all connected clients before the server goes down. The messages are sent immediately, not just stuck on the outgoing message list, because the server is going to totally exit after returning from this function.
added disconnect flag so map changes can use this function as well
Parameters
[in] cmd
[in] disconnect
Definition at line 1155 of file sv_init.c.
Referenced by SV_Shutdown(), and SV_SpawnServer().
void SV_GetConfigstring (int index, char * buffer, unsigned int bufferSize)
SV_GetConfigstring.
Parameters
[in] index
[out] buffer
[in] bufferSize
Definition at line 209 of file sv_init.c.
Referenced by SV_GameSystemCalls().
void SV_GetUserinfo (int index, char * buffer, unsigned int bufferSize)
SV_GetUserinfo.
Parameters
[in] index
[out] buffer
[in] bufferSize
Definition at line 261 of file sv_init.c.
Referenced by SV_GameSystemCalls().
void SV_Init (void)
SV_Init.
Definition at line 981 of file sv_init.c.
Referenced by Com_Init().
void SV_InitAttackLog ()
SV_InitAttackLog.
Definition at line 930 of file sv_init.c.
Referenced by SV_Init().
void SV_SetConfigstring (int index, const char * val)
SV_SetConfigstring.
Parameters
[in] index
[in] val
Definition at line 74 of file sv_init.c.
Referenced by SV_DemoReadClientConfigString(), SV_DemoReadConfigString(), SV_DemoStopPlayback(), SV_Frame(), SV_GameSystemCalls(), SV_MapRestart_f(), and SV_SpawnServer().
void SV_SetConfigstringNoUpdate (int index, const char * val)
SV_SetConfigstringNoUpdate.
Parameters
[in] index
[in] val
Definition at line 46 of file sv_init.c.
Referenced by SV_Frame().
void SV_SetExpectedHunkUsage (const char * mapname)
Sets com_expectedhunkusage, so the client knows how to draw the percentage bar.
Parameters
[in] mapname
Definition at line 445 of file sv_init.c.
Referenced by SV_SpawnServer().
static void SV_SetNumSnapshotEntities (void) static
Allocates new snapshot entities.
Definition at line 324 of file sv_init.c.
Referenced by SV_ChangeMaxClients(), SV_DemoChangeMaxClients(), and SV_Startup().
void SV_SetUserinfo (int index, const char * val)
SV_SetUserinfo.
Parameters
[in] index
[in] val
Definition at line 233 of file sv_init.c.
Referenced by SV_DropClient(), and SV_GameSystemCalls().
void SV_Shutdown (const char * finalmsg)
Called when each game quits, before Sys_Quit or Sys_Error.
Parameters
[in] finalmsg
Definition at line 1192 of file sv_init.c.
Referenced by CIN_PlayCinematic_f(), CL_Connect_f(), Com_Error(), Com_GetAutoUpdate(), Com_Quit_f(), SV_Frame(), SV_KillServer_f(), and Sys_SigHandler().
void SV_SpawnServer (const char * server)
Change the server to a new map, taking all connected clients along with it. This is NOT called for map_restart.
Parameters
[in] server
Definition at line 648 of file sv_init.c.
Referenced by SV_Map_f(), and SV_MapRestart_f().
void SV_Startup (void)
Called when a host starts a map when it wasn't running one before. Successive map or map_restart commands will NOT cause this to be called, unless the game is exited to the menu system first.
Definition at line 343 of file sv_init.c.
Referenced by SV_SpawnServer().
void SV_TouchCGameDLL (void)
Touch the cgame DLL so that a pure client (with DLL sv_pure support) can load do the correct checks.
Definition at line 624 of file sv_init.c.
Referenced by SV_SpawnServer().
void SV_UpdateConfigStrings (void)
Updates the configstring.
Note
It's nice to know this function sends several server commands when a configstring is greater than 1000 usually BIG_INFO_STRINGs
Definition at line 108 of file sv_init.c.
Referenced by SV_SendClientMessages(), and SV_SpawnServer().
void SV_WriteAttackLog (const char * log)
SV_WriteAttackLog.
Parameters
[in] log
Definition at line 909 of file sv_init.c.
Referenced by Com_UpdateInfoPacket(), SV_CheckDRDoS(), SV_CloseAttackLog(), SV_ConnectionlessPacket(), SV_DirectConnect(), SV_GetChallenge(), SV_InitAttackLog(), SV_SendServerCommand(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
Variable Documentation
int attHandle = 0
Definition at line 39 of file sv_init.c.
Referenced by SV_CloseAttackLog(), SV_InitAttackLog(), and SV_WriteAttackLog().