ET: Legacy: src/server/sv_demo.c File Reference
sv_demo.c File Reference
#include "server.h"
Macros
#define Q_IsColorStringGameCommand(p) ((p) && *(p) == Q_COLOR_ESCAPE && *((p) + 1))
Enumerations
enum demo_ops_e {
demo_endDemo, demo_EOF, demo_endFrame, demo_configString,
demo_clientConfigString, demo_clientCommand, demo_serverCommand, demo_gameCommand,
demo_clientUserinfo, demo_entityState, demo_entityShared, demo_playerState
}
Functions
static void SV_DemoWriteClientConfigString (int clientNum, const char *cs_string)
Write a client configstring to the demo file.
static void SV_DemoCvarsRestore ()
Restores all CVARs.
static char * SV_CleanStrCmd (char *string)
Same as Q_CleanStr but also remove any ^s or special empty color created by the engine in a gamecommand.
static qboolean SV_CheckClientCommand (client_t *client, const char *cmd)
Check that the clientCommand is OK (if not we either continue with a more specialized function, or drop it altogether if there's a privacy concern)
static qboolean SV_CheckServerCommand (const char *cmd)
Check that the serverCommand is OK to save (or if we drop it because already handled somewhere else or it's unwanted to store)
qboolean SV_CheckLastCmd (const char *cmd, qboolean onlyStore)
Check and store the last command and compare it with the current one, to avoid duplicates. If onlyStore is true, it will only store the new cmd, without checking.
static qboolean SV_CheckGameCommand (const char *cmd)
Check that the gameCommand is OK and that we can save it (or if we drop it for privacy concerns and/or because it's handled somewhere else already)
static qboolean SV_CheckConfigString (int cs_index, const char *cs_string)
Check that the configstring is OK (or if we relay to ClientConfigString)
void SV_DemoFilterClientUserinfo (char *userinfo)
Filters privacy keys from a client userinfo to later write in a demo file.
static char * SV_CleanFilename (char *string)
Attempts to clean invalid characters from a filename that may prevent the demo to be stored on the filesystem.
static char * SV_GenerateDateTime (void)
Generate a full datetime (local and utc) from now.
static void SV_DemoWriteMessage (msg_t *msg)
Write a message/event to the demo file.
static void SV_DemoWriteClientCommand (client_t *client, const char *cmd)
Write a client command to the demo file.
qboolean SV_DemoClientCommandCapture (client_t *client, const char *msg)
SV_DemoClientCommandCapture.
void SV_DemoWriteServerCommand (const char *cmd)
Write a server command to the demo file.
void SV_DemoWriteGameCommand (int clientNum, const char *cmd)
Write a game command to the demo file.
void SV_DemoWriteConfigString (int cs_index, const char *cs_string)
Write a configstring to the demo file.
void SV_DemoWriteClientUserinfo (client_t *client, const char *userinfo)
Write a client userinfo to the demo file (client_t fields can almost all be filled from the userinfo string)
static void SV_DemoWriteAllPlayerState (void)
Write all active clients playerState (playerState_t)
static void SV_DemoWriteAllEntityState (void)
Write all entities state (gentity_t->entityState_t)
static void SV_DemoWriteAllEntityShared (void)
Write all entities (gentity_t->entityShared_t)
void SV_DemoWriteFrame (void)
Record all the entities (gentities fields) and players (player_t fields) at the end of every frame (this is the only write function to be called in every frame for sure)
void SV_DemoAutoDemoRecord (void)
Generates a meaningful demo filename and automatically starts the demo recording.
static void SV_DemoStopPlayback (void)
Close the demo file and restart the map (can be used both when recording or when playing or at shutdown of the game)
static void SV_DemoPlaybackError (const char *message)
Call this to abort the demo play by error.
void SV_DemoRestartPlayback (void)
Just issue again the demo_play command along with the demo filename (used when the system will automatically restart the server for special cvars values to be set up, eg: sv_maxclients, fs_game, g_gametype, etc..)
static void SV_DemoStartPlayback (void)
Start the playback of a demo.
static void SV_DemoStartRecord (void)
Start the recording of a demo by saving some headers data (such as the number of clients, mapname, gametype, etc..)
static void SV_DemoStopRecord (void)
Stop the recording of a demo.
static void SV_DemoReadClientCommand (msg_t *msg)
Replay a client command.
static void SV_DemoReadServerCommand (msg_t *msg)
Replay a server command.
static void SV_DemoReadGameCommand (msg_t *msg)
Replay a game command (only game commands sent to all clients)
static void SV_DemoReadConfigString (msg_t *msg)
Read a configstring from a message and load it into memory.
static void SV_DemoReadClientConfigString (msg_t *msg)
Read a demo client configstring from a message, load it into memory and broadcast changes to gamecode and clients.
static void SV_DemoReadClientUserinfo (msg_t *msg)
Read a demo client userinfo string from a message, load it into memory, fills client_t fields by parsing the userinfo and broacast the change to the gamecode and clients.
static void SV_DemoReadAllPlayerState (msg_t *msg)
Read the usercmd_t for a democlient and restituate the movements.
static void SV_DemoReadAllEntityState (msg_t *msg)
Read all entities state (gentity_t or sharedEntity_t->entityState_t) from a message and store them in a demoEntities[num].s array (it will be loaded in memory later when SV_DemoReadRefresh() is called)
static void SV_DemoReadAllEntityShared (msg_t *msg)
Read all shared entities (gentity_t or sharedEntity_t->entityShared_t.
static void SV_DemoReadRefreshEntities (void)
Load into memory all stored demo players states and entities (which effectively overwrites the one that were previously written by the game since SV_ReadFrame is called at the very end of every game's frame iteration).
void SV_DemoReadRefreshPlayersHealth (void)
Update all demoplayers health (will be reflected on the HUD when spectated - for team overlay see tinfo clientcommand)
void SV_DemoReadFrame (void)
Play a frame from the demo file.
void SV_DemoStopAll (void)
SV_DemoStopAll.
static void SV_Demo_Record_f (void)
SV_Demo_Record_f.
static void SV_Demo_Play_f (void)
SV_Demo_Play_f.
static void SV_Demo_Stop_f (void)
SV_Demo_Stop_f.
static void SV_CompleteDemoName (char *args, int argNum)
SV_CompleteDemoName.
void SV_DemoInit (void)
SV_DemoInit.
void SV_DemoShutdown (void)
SV_DemoShutdown.
Variables
static byte buf [0x400000]
static int savedMaxClients = -1
static int savedFPS = -1
static int savedGametype = -1
static int savedDoWarmup = -1
static int savedAllowVote = -1
static int savedTimelimit = -1
static int savedFraglimit = -1
static int savedCapturelimit = -1
static char savedFsGameVal [MAX_QPATH] = ""
static char * savedFsGame = savedFsGameVal
static char savedPlaybackDemonameVal [MAX_QPATH] = ""
static char * savedPlaybackDemoname = savedPlaybackDemonameVal
static qboolean keepSaved = qfalse
Macro Definition Documentation
#define Q_IsColorStringGameCommand (p) ((p) && *(p) == Q_COLOR_ESCAPE && *((p) + 1))
Definition at line 41 of file sv_demo.c.
Referenced by SV_CleanStrCmd().
Enumeration Type Documentation
enum demo_ops_e
Enumerator
demo_endDemo
demo_EOF
demo_endFrame
demo_configString
demo_clientConfigString
demo_clientCommand
demo_serverCommand
demo_gameCommand
demo_clientUserinfo
demo_entityState
demo_entityShared
demo_playerState
Definition at line 49 of file sv_demo.c.
Function Documentation
static qboolean SV_CheckClientCommand (client_t * client, const char * cmd) static
Check that the clientCommand is OK (if not we either continue with a more specialized function, or drop it altogether if there's a privacy concern)
Parameters
[in] client
[in] cmd
Returns
Definition at line 208 of file sv_demo.c.
Referenced by SV_DemoWriteClientCommand().
static qboolean SV_CheckConfigString (int cs_index, const char * cs_string) static
Check that the configstring is OK (or if we relay to ClientConfigString)
Parameters
cs_index
cs_string
Returns
Definition at line 321 of file sv_demo.c.
Referenced by SV_DemoWriteConfigString().
static qboolean SV_CheckGameCommand (const char * cmd) static
Check that the gameCommand is OK and that we can save it (or if we drop it for privacy concerns and/or because it's handled somewhere else already)
Parameters
[in] cmd
Returns
Definition at line 289 of file sv_demo.c.
Referenced by SV_DemoWriteGameCommand().
qboolean SV_CheckLastCmd (const char * cmd, qboolean onlyStore)
Check and store the last command and compare it with the current one, to avoid duplicates. If onlyStore is true, it will only store the new cmd, without checking.
Parameters
[in] cmd
[in] onlyStore
Returns
Definition at line 258 of file sv_demo.c.
Referenced by SV_CheckGameCommand(), SV_DemoReadGameCommand(), and SV_GameSendServerCommand().
static qboolean SV_CheckServerCommand (const char * cmd) static
Check that the serverCommand is OK to save (or if we drop it because already handled somewhere else or it's unwanted to store)
Parameters
[in] cmd
Returns
Todo:
? possibly some print/cp are not handled by gameCommand? From my tests it was ok,
Definition at line 236 of file sv_demo.c.
Referenced by SV_DemoWriteServerCommand().
static char* SV_CleanFilename (char * string) static
Attempts to clean invalid characters from a filename that may prevent the demo to be stored on the filesystem.
Parameters
[in] string
Returns
Definition at line 357 of file sv_demo.c.
Referenced by SV_DemoAutoDemoRecord().
static char* SV_CleanStrCmd (char * string) static
Same as Q_CleanStr but also remove any ^s or special empty color created by the engine in a gamecommand.
Parameters
[in] string
Returns
Definition at line 177 of file sv_demo.c.
Referenced by SV_CheckLastCmd().
static void SV_CompleteDemoName (char * args, int argNum) static
SV_CompleteDemoName.
Parameters
args - unused
[in] argNum
Definition at line 2076 of file sv_demo.c.
Referenced by SV_DemoInit().
static void SV_Demo_Play_f (void) static
SV_Demo_Play_f.
Definition at line 2019 of file sv_demo.c.
Referenced by SV_DemoInit().
static void SV_Demo_Record_f (void) static
SV_Demo_Record_f.
Definition at line 1961 of file sv_demo.c.
Referenced by SV_DemoInit().
static void SV_Demo_Stop_f (void) static
SV_Demo_Stop_f.
Definition at line 2060 of file sv_demo.c.
Referenced by SV_DemoInit().
void SV_DemoAutoDemoRecord (void)
Generates a meaningful demo filename and automatically starts the demo recording.
This function is used in conjunction with the variable sv_autoDemo 1
Note
Be careful, if the hostname contains bad characters, the demo may not be able to be saved at all! There's a small filtering in place but a bad filename may pass through!
this function is called at MapRestart and SpawnServer (called in Map func), but in no way it's called right at the time it's set.
Definition at line 823 of file sv_demo.c.
Referenced by SV_InitGameVM(), and SV_SpawnServer().
qboolean SV_DemoClientCommandCapture (client_t * client, const char * msg)
SV_DemoClientCommandCapture.
Parameters
[in] client
[in] msg
Returns
Definition at line 462 of file sv_demo.c.
Referenced by SV_ExecuteClientCommand().
static void SV_DemoCvarsRestore () static
Restores all CVARs.
Definition at line 97 of file sv_demo.c.
Referenced by SV_DemoStopPlayback().
void SV_DemoFilterClientUserinfo (char * userinfo)
Filters privacy keys from a client userinfo to later write in a demo file.
Parameters
[in,out] userinfo
Definition at line 345 of file sv_demo.c.
Referenced by SV_DemoWriteClientUserinfo().
void SV_DemoInit (void)
SV_DemoInit.
Definition at line 2090 of file sv_demo.c.
Referenced by SV_AddOperatorCommands().
static void SV_DemoPlaybackError (const char * message) static
Call this to abort the demo play by error.
Parameters
[in]
Todo:
: reset static vars?!
Definition at line 918 of file sv_demo.c.
Referenced by SV_DemoReadAllPlayerState(), SV_DemoReadFrame(), and SV_DemoStartPlayback().
static void SV_DemoReadAllEntityShared (msg_t * msg) static
Read all shared entities (gentity_t or sharedEntity_t->entityShared_t.
Parameters
[in] msg
Note
sharedEntity_t = gentity_t != entityShared_t which is a subfield of gentity_t) from a message and store them in a demoEntities[num].r array (it will be loaded in memory later when SV_DemoReadRefresh() is called)
Definition at line 1704 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadAllEntityState (msg_t * msg) static
Read all entities state (gentity_t or sharedEntity_t->entityState_t) from a message and store them in a demoEntities[num].s array (it will be loaded in memory later when SV_DemoReadRefresh() is called)
Parameters
[in] msg
Definition at line 1656 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadAllPlayerState (msg_t * msg) static
Read the usercmd_t for a democlient and restituate the movements.
This is NOT needed to make democlients move, this is handled by entities management, but it should avoid inactivity timer to activate and can be used for demo analysis
Parameters
[in] msg
Todo:
FIXME: should set ucmd->serverTime = client->ps.commandTime + 2 to avoid the dropping of the usercmds_t packets, see g_active.c
Read all democlients playerstate (playerState_t) from a message and store them in a demoPlayerStates array (it will be loaded in memory later when SV_DemoReadRefresh() is called)
Parameters
[in] msg
Definition at line 1635 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadClientCommand (msg_t * msg) static
Replay a client command.
Client command management (generally automatic, such as tinfo for HUD team overlay status, team selection, etc.)
except userinfo command that is managed by another event
Parameters
[in] msg
Definition at line 1374 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadClientConfigString (msg_t * msg) static
Read a demo client configstring from a message, load it into memory and broadcast changes to gamecode and clients.
This function also manages demo clientbegin at connections and teamchange (which are normally totally handled by the gamecode, so we can't directly access nor store these events in the demo, we must use clever ways to reproduce them at the right time)
Parameters
[in] msg
Todo:
: This causes a crash
Definition at line 1452 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadClientUserinfo (msg_t * msg) static
Read a demo client userinfo string from a message, load it into memory, fills client_t fields by parsing the userinfo and broacast the change to the gamecode and clients.
Parameters
msg
Note
This function also manage the initial team of democlients when demo recording has started. Subsequent team changes will be directly handled by clientCommands "team"
Todo:
? If you are trying to port this patch and weirdly some democlients are visible in scoreboard but can't be followed, try to uncomment these lines
Definition at line 1550 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadConfigString (msg_t * msg) static
Read a configstring from a message and load it into memory.
Parameters
[in] msg
Todo:
: doesn't work, dunno why, but it would be better than a string to store a long int!
Definition at line 1428 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
void SV_DemoReadFrame (void)
Play a frame from the demo file.
This function will read one frame per call, and will process every events contained (switch to the next event when meeting the demo_EOF marker) until it meets the end of the frame (demo_endDemo marker).
Called in the main server's loop SV_Frame() in sv_main.c (it's called after any other event processing, so that it overwrites anything the game may have loaded into memory, but before the entities are broadcasted to the clients)
Todo:
: inspect!
Definition at line 1799 of file sv_demo.c.
Referenced by SV_DemoStartPlayback(), and SV_Frame().
static void SV_DemoReadGameCommand (msg_t * msg) static
Replay a game command (only game commands sent to all clients)
Game command management, such as prints/centerprint (cp) scores command, except chat/tchat (handled by clientCommand)
Basically the same as demo_serverCommand (because sv_GameSendServerCommand uses SV_SendServerCommand, but game commands are safe to be replayed to everyone, while server commands may be unsafe such as disconnect)
Parameters
[in] msg
Definition at line 1410 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadRefreshEntities (void) static
Load into memory all stored demo players states and entities (which effectively overwrites the one that were previously written by the game since SV_ReadFrame is called at the very end of every game's frame iteration).
Todo:
? shouldn't MAX_CLIENTS be sv_maxclients->integer?
Definition at line 1752 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
void SV_DemoReadRefreshPlayersHealth (void)
Update all demoplayers health (will be reflected on the HUD when spectated - for team overlay see tinfo clientcommand)
Note
This function should always be called after SV_DemoReadRefreshEntities() (or you can also change SV_GameClientNum(i) to sv.demoPlayerStates[i], but make sure the entity already has updated its health state...)
Definition at line 1779 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
static void SV_DemoReadServerCommand (msg_t * msg) static
Replay a server command.
Server command management - except print/cp (dropped at recording because already handled by gameCommand).
Parameters
[in] msg
Definition at line 1392 of file sv_demo.c.
Referenced by SV_DemoReadFrame().
void SV_DemoRestartPlayback (void)
Just issue again the demo_play command along with the demo filename (used when the system will automatically restart the server for special cvars values to be set up, eg: sv_maxclients, fs_game, g_gametype, etc..)
Definition at line 930 of file sv_demo.c.
Referenced by SV_Frame().
void SV_DemoShutdown (void)
SV_DemoShutdown.
Todo:
: don't remove these on server shutdown/demo end so listen servers can start another demo and server owners too
Definition at line 2100 of file sv_demo.c.
Referenced by SV_Shutdown().
static void SV_DemoStartPlayback (void) static
Start the playback of a demo.
sv.demo* have already been set and the demo file opened, start reading gamestate info.
This function will also check that everything is alright (such as gametype, map, sv_fps, sv_democlients, sv_maxclients, etc.), if not it will try to fix it automatically
Note
For developers: this is basically a mirror of SV_DemoStartRecord() but the other way around (there it writes, here it reads)
but only for the part about the headers, for the rest (eg: userinfo, configstrings, playerstates) it's directly managed by ReadFrame.
Todo:
: MAX_QPATH - only 64 chars ?!!!
Todo:
: if the timelimit is changed during the game, it won't be reflected in the demo (but the demo will still continue to play, or stop if the game is won).
Todo:
: if the limit is changed during the game, the new value won't be reflected in the demo (but the demo will continue to play to its integrality)
Todo:
: if the limit is changed during the game, the new value won't be reflected in the demo (but the demo will continue to play to its integrality)
Todo:
: THIS IS HACKED TO 1 for now (should be 0 or we need to make our own etgame mod bin)
Todo:
? why sv_cheats is needed? Just to be able to use cheats commands to pass through walls?
Todo:
: demo_play with sv_maxclients 64 doesn't start because of this and wants to set sv_mmaxclients 128?!
Change to the right map/maxclients/mod and restart the demo playback at the next SV_Frame() iteration
Todo:
: omnibot - this bot stuff isn't tested well (but better than before)
Todo:
: and/or check for bot player count, omnibot_enable is latched !!!
Todo:
: restore value and bot players after demo play
Definition at line 954 of file sv_demo.c.
Referenced by SV_Demo_Play_f().
static void SV_DemoStartRecord (void) static
Start the recording of a demo by saving some headers data (such as the number of clients, mapname, gametype, etc..)
sv.demo* have already been set and the demo file opened, start writing gamestate info
Todo:
? We could also use MSG_LookaheadByte() to read a byte, instead of a string, this would save a tiny bit of storage space
Definition at line 1262 of file sv_demo.c.
Referenced by SV_Demo_Record_f().
void SV_DemoStopAll (void)
SV_DemoStopAll.
Definition at line 1945 of file sv_demo.c.
Referenced by SV_Demo_Stop_f(), and SV_ShutdownGameProgs().
static void SV_DemoStopPlayback (void) static
Close the demo file and restart the map (can be used both when recording or when playing or at shutdown of the game)
Todo:
: Restore sv_maxclients value (force latched values to commit)
Todo:
: this is more than ugly
Definition at line 860 of file sv_demo.c.
Referenced by SV_DemoPlaybackError(), SV_DemoReadFrame(), SV_DemoStartPlayback(), and SV_DemoStopAll().
static void SV_DemoStopRecord (void) static
Stop the recording of a demo.
Write end of demo (demo_endDemo marker) and close the demo file
Definition at line 1345 of file sv_demo.c.
Referenced by SV_DemoStopAll().
static void SV_DemoWriteAllEntityShared (void) static
Write all entities (gentity_t->entityShared_t)
Note
This is called at every game's endFrame.
Contrary to the other DemoWrite functions, this one writes all entities at once in one message, instead of one entity/command per message.
Definition at line 738 of file sv_demo.c.
Referenced by SV_DemoWriteFrame().
static void SV_DemoWriteAllEntityState (void) static
Write all entities state (gentity_t->entityState_t)
Note
This is called at every game's endFrame.
Contrary to the other DemoWrite functions, this one writes all entities at once in one message, instead of one entity/command per message. This could be easily changed, but I'm not sure it would be beneficial for the CPU time and demo storage.
Definition at line 701 of file sv_demo.c.
Referenced by SV_DemoWriteFrame().
static void SV_DemoWriteAllPlayerState (void) static
Write all active clients playerState (playerState_t)
Note
This is called at every game's endFrame.
Contrary to the other DemoWrite functions, this one writes all entities at once in one message, instead of one entity/command per message.
Definition at line 665 of file sv_demo.c.
Referenced by SV_DemoWriteFrame().
static void SV_DemoWriteClientCommand (client_t * client, const char * cmd) static
Write a client command to the demo file.
Parameters
[in] client
[in] cmd
Definition at line 439 of file sv_demo.c.
Referenced by SV_DemoClientCommandCapture().
static void SV_DemoWriteClientConfigString (int clientNum, const char * cs_string) static
Write a client configstring to the demo file.
Parameters
[in] clientNum
[in] cs_string
Note
This is a bit redundant with SV_DemoWriteUserinfo, because clientCommand userinfo sets the new userinfo for a democlient, and clients configstrings are always derived from userinfo string. But this function is left for security purpose (so we make sure the configstring is set right).
Definition at line 574 of file sv_demo.c.
Referenced by SV_CheckConfigString().
void SV_DemoWriteClientUserinfo (client_t * client, const char * userinfo)
Write a client userinfo to the demo file (client_t fields can almost all be filled from the userinfo string)
Parameters
[in] client
[in] userinfo
Note
In practice, clients userinfo should be loaded before their configstrings (because configstrings derive from userinfo in a real game)
Definition at line 592 of file sv_demo.c.
Referenced by SV_CheckClientCommand(), SV_DemoStartRecord(), SV_SetUserinfo(), and SV_UpdateUserinfo_f().
void SV_DemoWriteConfigString (int cs_index, const char * cs_string)
Write a configstring to the demo file.
cs_index = index of the configstring (see bg_public.h) cs_string = content of the configstring to set
Parameters
[in] cs_index
[in] cs_string
Todo:
: try to replace by a WriteLong instead of WriteString? Or WriteData (with length! and it uses WriteByte)
Definition at line 544 of file sv_demo.c.
Referenced by SV_CheckGameCommand(), SV_DemoStartRecord(), and SV_SetConfigstring().
void SV_DemoWriteFrame (void)
Record all the entities (gentities fields) and players (player_t fields) at the end of every frame (this is the only write function to be called in every frame for sure)
Will be called once per server's frame Called in the main server's loop SV_Frame() in sv_main.c Note that this function could be called DemoWriteEndFrame, because it writes once at the end of every frame (the other events are written whenever they happen using hooks)
Definition at line 776 of file sv_demo.c.
Referenced by SV_DemoStartRecord(), and SV_Frame().
void SV_DemoWriteGameCommand (int clientNum, const char * cmd)
Write a game command to the demo file.
Parameters
[in] clientNum
[in] cmd
Note
Game commands are sent to server commands, but we record them separately because game commands are safe to be replayed to everyone (even if at recording time it was only intended to one player), while server commands may be unsafe if it was dedicated only to one player (such as "disconnect")
Definition at line 517 of file sv_demo.c.
Referenced by SV_GameSendServerCommand().
static void SV_DemoWriteMessage (msg_t * msg) static
Write a message/event to the demo file.
Parameters
[in,out] msg
Definition at line 422 of file sv_demo.c.
Referenced by SV_DemoStartRecord(), SV_DemoStopRecord(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DemoWriteAllPlayerState(), SV_DemoWriteClientCommand(), SV_DemoWriteClientConfigString(), SV_DemoWriteClientUserinfo(), SV_DemoWriteConfigString(), SV_DemoWriteFrame(), SV_DemoWriteGameCommand(), and SV_DemoWriteServerCommand().
void SV_DemoWriteServerCommand (const char * cmd)
Write a server command to the demo file.
Parameters
[in] cmd
Note
We record only server commands that are meant to be sent to everyone in the first place, that's why we don't even bother to store the clientnum. For commands that were only intended to specifically one player, we only record them if they were game commands (see below the specialized function), else we do not because it may be unsafe (such as "disconnect" command)
Definition at line 491 of file sv_demo.c.
Referenced by SV_SendServerCommand().
static char* SV_GenerateDateTime (void) static
Generate a full datetime (local and utc) from now.
Returns
Definition at line 390 of file sv_demo.c.
Referenced by SV_DemoStartRecord().
Variable Documentation
byte buf[0x400000] static
Definition at line 72 of file sv_demo.c.
Referenced by BG_AddPredictableEventToPlayerstate(), Bot_Interface_Update(), CG_Debriefing_FindWinningTeamForMap(), CG_Debriefing_FindWinningTeamForPos(), CG_Debriefing_Startup(), CG_DebriefingTitle_Draw(), CG_DPrintf(), CG_getBindKeyName(), CG_KickAngles(), CG_LocalizeServerCommand(), CG_NewClientInfo(), CG_ParseVoiceChats(), CG_Printf(), CG_printWindow(), CG_RegisterCharacter(), CG_TranslateString(), CL_ParseDemo(), CL_PeekSnapshot(), CL_ReadDemoMessage(), CL_Record(), CL_SetExpectedHunkUsage(), CL_TranslateStringBuf(), CL_UpdateLevelHunkUsage(), CL_WritePacket(), ClientName(), CM_LoadMap(), Cmd_AuthRcon_f(), CMod_LoadVisibility(), Com_Error(), Com_EventLoop(), Com_Filter(), FindClientByName(), FindIntermissionPoint(), FS_CopyFile(), FS_Read(), FS_ReadFile(), FS_Unzip(), FS_UnzipTo(), FS_Write(), func_constructiblespawn(), G_MatchString(), G_ParseCampaigns(), G_PushMapEntityToBuffer(), G_WriteConfigFileString(), GeoIP_seek_record(), GetMenuBuffer(), GLimp_DetectAvailableModes(), Hunk_Alloc(), Hunk_AllocateTempMemory(), Hunk_Log(), Hunk_SmallLog(), NET_OpenSocks(), NET_SendPacket(), PC_Int_Parse(), Q_UTF8_Encode(), Q_UTF8_Unstore(), R_CacheImageAlloc(), R_GetImageBuffer(), R_Hunk_Alloc(), R_LoadCacheImages(), R_LoadCacheModels(), R_LoadCacheShaders(), R_LoadJPG(), R_LoadLightmaps(), R_LoadLightmapsInternal(), R_LoadModelShadow(), R_LoadVisibility(), RE_RegisterModel(), ScoreIsTied(), SV_DemoReadFrame(), SV_DemoStartPlayback(), SV_DemoStartRecord(), SV_DemoStopRecord(), SV_DemoWriteAllEntityShared(), SV_DemoWriteAllEntityState(), SV_DemoWriteAllPlayerState(), SV_DemoWriteClientCommand(), SV_DemoWriteClientConfigString(), SV_DemoWriteClientUserinfo(), SV_DemoWriteConfigString(), SV_DemoWriteFrame(), SV_DemoWriteGameCommand(), SV_DemoWriteServerCommand(), SV_SetExpectedHunkUsage(), SV_UpdateConfigStrings(), trap_TranslateString(), UI_FileText(), UI_RunMenuScript(), UI_SetActiveMenu(), va(), WM_DrawClientScore(), WM_DrawClientScore_Small(), WM_DrawObjectives(), Z_LogZoneHeap(), and Z_Malloc().
qboolean keepSaved = qfalse static
Definition at line 92 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), SV_DemoStartPlayback(), and SV_DemoStopPlayback().
int savedAllowVote = -1 static
Definition at line 80 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
int savedCapturelimit = -1 static
Definition at line 84 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
int savedDoWarmup = -1 static
Definition at line 79 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
int savedFPS = -1 static
Definition at line 76 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
int savedFraglimit = -1 static
Definition at line 83 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
char* savedFsGame = savedFsGameVal static
Definition at line 87 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
char savedFsGameVal[MAX_QPATH] = "" static
Definition at line 86 of file sv_demo.c.
int savedGametype = -1 static
Definition at line 77 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
int savedMaxClients = -1 static
Definition at line 75 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().
char* savedPlaybackDemoname = savedPlaybackDemonameVal static
Definition at line 90 of file sv_demo.c.
Referenced by SV_DemoRestartPlayback(), and SV_DemoStartPlayback().
char savedPlaybackDemonameVal[MAX_QPATH] = "" static
Definition at line 89 of file sv_demo.c.
int savedTimelimit = -1 static
Definition at line 82 of file sv_demo.c.
Referenced by SV_DemoCvarsRestore(), and SV_DemoStartPlayback().