ET: Legacy: src/server/sv_net_chan.c File Reference
sv_net_chan.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "server.h"
Functions
static void SV_Netchan_Encode (client_t *client, msg_t *msg, char *commandString)
SV_Netchan_Encode.
static void SV_Netchan_Decode (client_t *client, msg_t *msg)
SV_Netchan_Decode.
void SV_Netchan_ClearQueue (client_t *client)
SV_Netchan_ClearQueue.
void SV_Netchan_TransmitNextInQueue (client_t *client)
SV_Netchan_TransmitNextInQueue.
int SV_Netchan_TransmitNextFragment (client_t *client)
SV_Netchan_TransmitNextFragment.
static void SV_WriteBinaryMessage (msg_t *msg, client_t *cl)
SV_WriteBinaryMessage.
void SV_Netchan_Transmit (client_t *client, msg_t *msg)
SV_Netchan_Transmit.
qboolean SV_Netchan_Process (client_t *client, msg_t *msg)
SV_Netchan_Process.
Function Documentation
void SV_Netchan_ClearQueue (client_t * client)
SV_Netchan_ClearQueue.
Parameters
[in,out] client
Definition at line 155 of file sv_net_chan.c.
Referenced by SV_DirectConnect(), SV_DropClient(), and SV_Shutdown().
static void SV_Netchan_Decode (client_t * client, msg_t * msg) static
SV_Netchan_Decode.
Parameters
[in] client
[in,out] msg
Note
first 12 bytes of the data are always: long serverId; long messageAcknowledge; long reliableAcknowledge;
Definition at line 108 of file sv_net_chan.c.
Referenced by SV_Netchan_Process().
static void SV_Netchan_Encode (client_t * client, msg_t * msg, char * commandString) static
SV_Netchan_Encode.
Parameters
[in] client
[in,out] msg
[in,out] commandString
Note
first four bytes of the data are always: long reliableAcknowledge;
Definition at line 48 of file sv_net_chan.c.
Referenced by SV_Netchan_Transmit(), and SV_Netchan_TransmitNextInQueue().
qboolean SV_Netchan_Process (client_t * client, msg_t * msg)
SV_Netchan_Process.
Parameters
[in] client
[in] msg
Returns
Definition at line 286 of file sv_net_chan.c.
Referenced by SV_PacketEvent().
void SV_Netchan_Transmit (client_t * client, msg_t * msg)
SV_Netchan_Transmit.
If there are some unsent fragments (which may happen if the snapshots and the gamestate are fragmenting, and collide on send for instance) then buffer them and make sure they get sent in correct order
Parameters
[in,out] client
[in] msg
Definition at line 255 of file sv_net_chan.c.
Referenced by SV_SendDownloadMessages(), and SV_SendMessageToClient().
int SV_Netchan_TransmitNextFragment (client_t * client)
SV_Netchan_TransmitNextFragment.
Parameters
[in] client
Returns
Definition at line 204 of file sv_net_chan.c.
Referenced by SV_SendQueuedMessages().
void SV_Netchan_TransmitNextInQueue (client_t * client)
SV_Netchan_TransmitNextInQueue.
Parameters
[in,out] client
Definition at line 173 of file sv_net_chan.c.
Referenced by SV_Netchan_TransmitNextFragment().
static void SV_WriteBinaryMessage (msg_t * msg, client_t * cl) static
SV_WriteBinaryMessage.
Parameters
[in] msg
[in,out] cl
Definition at line 225 of file sv_net_chan.c.
Referenced by SV_Netchan_Transmit().