ET: Legacy: src/sys/sys_win32.c File Reference
sys_win32.c File Reference
Contains windows-specific code for console.
#include <SDL2/SDL_video.h>
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "win_resource.h"
#include "sys_local.h"
#include "sys_win32.h"
#include <windows.h>
#include <lmerr.h>
#include <lmcons.h>
#include <lmwksta.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <direct.h>
#include <io.h>
#include <conio.h>
#include <wincrypt.h>
#include <shlobj.h>
#include <psapi.h>
#include <setjmp.h>
Macros
#define MEM_THRESHOLD 96 * 1024 * 1024
Functions
char * Sys_DefaultHomePath (void)
Get current home path.
int Sys_Milliseconds (void)
Sys_Milliseconds.
void Sys_SnapVector (float *v)
Sys_SnapVector.
qboolean Sys_RandomBytes (byte *string, int len)
Sys_RandomBytes.
char * Sys_GetCurrentUser (void)
Sys_GetCurrentUser.
qboolean Sys_LowPhysicalMemory (void)
Sys_LowPhysicalMemory.
const char * Sys_Basename (char *path)
Sys_Basename.
const char * Sys_Dirname (char *path)
Sys_Dirname.
FILE * Sys_FOpen (const char *ospath, const char *mode)
Sys_FOpen.
qboolean Sys_Mkdir (const char *path)
Sys_Mkdir.
char * Sys_Cwd (void)
Sys_Cwd.
void Sys_ListFilteredFiles (const char *basedir, const char *subdirs, const char *filter, char **list, int *numfiles)
Sys_ListFilteredFiles.
static qboolean strgtr (const char *s0, const char *s1)
strgtr
char ** Sys_ListFiles (const char *directory, const char *extension, const char *filter, int *numfiles, qboolean wantsubs)
Sys_ListFiles.
void Sys_FreeFileList (char **list)
Sys_FreeFileList.
void Sys_Sleep (int msec)
Block execution for msec or until input is received.
void Sys_ErrorDialog (const char *error)
Display an error message.
dialogResult_t Sys_Dialog (dialogType_t type, const char *message, const char *title)
Display a win32 dialog box.
void Sys_GLimpSafeInit (void)
Windows specific "safe" GL implementation initialisation.
void Sys_GLimpInit (void)
Windows specific GL implementation initialisation.
void Sys_SetEnv (const char *name, const char *value)
Set/unset environment variables (empty value removes it)
int Sys_PID (void)
Sys_PID.
qboolean Sys_PIDIsRunning (unsigned int pid)
Sys_PIDIsRunning.
void Sys_StartProcess (char *cmdline, qboolean doexit)
Sys_StartProcess.
void Sys_OpenURL (const char *url, qboolean doexit)
Sys_OpenURL.
void Sys_CreateConsoleWindow (void)
Sys_CreateConsoleWindow.
void Sys_SetProcessProperties (void)
Sys_SetProcessProperties.
void Sys_PlatformInit (void)
Windows specific initialization.
qboolean Sys_DllExtension (const char *name)
Check if filename should be allowed to be loaded as a DLL.
Variables
static char homePath [MAX_OSPATH] = { 0 }
int sys_timeBase
static qboolean SDL_VIDEODRIVER_externallySet = qfalse
WinVars_t g_wv
Detailed Description
Contains windows-specific code for console.
Definition in file sys_win32.c.
Macro Definition Documentation
#define MEM_THRESHOLD 96 * 1024 * 1024
Definition at line 177 of file sys_win32.c.
Referenced by Sys_LowPhysicalMemory().
Function Documentation
static qboolean strgtr (const char * s0, const char * s1) static
strgtr
Parameters
[in] s0
[in] s1
Returns
Definition at line 376 of file sys_win32.c.
Referenced by Sys_ListFiles().
const char* Sys_Basename (char * path)
Sys_Basename.
Parameters
path
Returns
Definition at line 195 of file sys_win32.c.
void Sys_CreateConsoleWindow (void)
Sys_CreateConsoleWindow.
Definition at line 876 of file sys_win32.c.
char* Sys_Cwd (void)
Sys_Cwd.
Get current working directory.
Returns
Definition at line 283 of file sys_win32.c.
Referenced by Sys_DefaultInstallPath().
char* Sys_DefaultHomePath (void)
Get current home path.
Returns
homepath pointing to "My Documents\\ETLegacy"
Todo:
: forcing SHGFP_TYPE_CURRENT because file creation fails
Definition at line 70 of file sys_win32.c.
Referenced by FS_Startup().
dialogResult_t Sys_Dialog (dialogType_t type, const char * message, const char * title)
Display a win32 dialog box.
Display an OS X dialog box.
Parameters
[in] type
[in] message
[in] title
Returns
Definition at line 664 of file sys_win32.c.
Referenced by Com_Init(), main(), and Sys_ErrorDialog().
const char* Sys_Dirname (char * path)
Sys_Dirname.
Parameters
path
Returns
Definition at line 225 of file sys_win32.c.
Referenced by main().
qboolean Sys_DllExtension (const char * name)
Check if filename should be allowed to be loaded as a DLL.
Parameters
name
Definition at line 1040 of file sys_win32.c.
Referenced by FS_CheckFilenameIsMutable(), and Sys_LoadDll().
void Sys_ErrorDialog (const char * error)
Display an error message.
Displays an error message and writes the error into crashlog.txt.
Parameters
[in] error
Definition at line 621 of file sys_win32.c.
Referenced by Sys_Error().
FILE* Sys_FOpen (const char * ospath, const char * mode)
Sys_FOpen.
Safe function to open a file and preventing TOCTOU attacks.
Parameters
[in] ospath
[in] mode
Returns
Definition at line 247 of file sys_win32.c.
Referenced by FS_CL_ExtractFromPakFile(), FS_CopyFile(), FS_FileInPathExists(), FS_FOpenDLLWrite(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_Unzip(), and FS_UnzipTo().
void Sys_FreeFileList (char ** list)
Sys_FreeFileList.
Parameters
[in,out] list
Definition at line 569 of file sys_win32.c.
Referenced by FS_AddGameDirectory(), FS_DeleteDir(), FS_GetModList(), and FS_ListFilteredFiles().
char* Sys_GetCurrentUser (void)
Sys_GetCurrentUser.
Get current user username.
Returns
Definition at line 159 of file sys_win32.c.
Referenced by Sys_Init().
void Sys_GLimpInit (void)
Windows specific GL implementation initialisation.
Unix specific GL implementation initialisation.
Definition at line 724 of file sys_win32.c.
Referenced by CL_InitRef(), and GLimp_Init().
void Sys_GLimpSafeInit (void)
Windows specific "safe" GL implementation initialisation.
Unix specific "safe" GL implementation initialisation.
Definition at line 709 of file sys_win32.c.
Referenced by CL_InitRef(), and GLimp_Init().
char** Sys_ListFiles (const char * directory, const char * extension, const char * filter, int * numfiles, qboolean wantsubs)
Sys_ListFiles.
List files in directory by filter.
Parameters
[in] directory
[in] extension
[in] filter
[out] numfiles
[in] wantsubs
Returns
Definition at line 412 of file sys_win32.c.
Referenced by FS_AddGameDirectory(), FS_DeleteDir(), FS_GetModList(), and FS_ListFilteredFiles().
void Sys_ListFilteredFiles (const char * basedir, const char * subdirs, const char * filter, char ** list, int * numfiles)
Sys_ListFilteredFiles.
Parameters
[in] basedir
[in] subdirs
[in] filter
[out] list
[in,out] numfiles
Definition at line 307 of file sys_win32.c.
Referenced by Sys_ListFiles().
qboolean Sys_LowPhysicalMemory (void)
Sys_LowPhysicalMemory.
Returns
Definition at line 183 of file sys_win32.c.
Referenced by CL_InitCGame().
int Sys_Milliseconds (void)
Sys_Milliseconds.
Returns
Definition at line 102 of file sys_win32.c.
Referenced by CL_CgameSystemCalls(), CL_DemoCompleted(), CL_DemoRun(), CL_GenerateETKey(), CL_InitCGame(), CL_ParseDemo(), CL_ScaledMilliseconds(), CL_ServerStatus(), CL_ServerStatusResponse(), CL_UISystemCalls(), Com_Error(), Com_Frame(), Com_GetSystemEvent(), Com_ModifyMsec(), Com_QueueEvent(), Com_RunAndTimeServerPacket(), Com_TimeVal(), Com_TouchMemory(), DB_Create(), DB_Init(), DB_SaveMemDB(), FindShaderInShaderText(), FS_Unzip(), IN_Frame(), IN_WindowResize(), main(), NET_SendPacket(), Netchan_Transmit(), Netchan_TransmitNextFragment(), S_AddLoopSounds(), S_Base_StartSoundEx(), S_ChannelMalloc(), S_FreeOldestSound(), S_LoadSound(), S_Update_(), SV_Frame(), SV_GameSystemCalls(), SV_RateMsec(), SV_SendQueuedPackets(), SV_SpawnServer(), SV_Status_f(), SV_Uptime_f(), SVC_BucketForAddress(), SVC_RateLimit(), and Sys_GameLoop().
qboolean Sys_Mkdir (const char * path)
Sys_Mkdir.
Create directory.
Parameters
[in] path
Returns
Definition at line 266 of file sys_win32.c.
Referenced by FS_CreatePath().
void Sys_OpenURL (const char * url, qboolean doexit)
Sys_OpenURL.
Open URL in system browser.
Parameters
[in] url
[in] doexit
Definition at line 833 of file sys_win32.c.
Referenced by CL_OpenURL(), CL_ParseDownload(), and Com_GetAutoUpdate().
int Sys_PID (void)
Sys_PID.
Returns
Definition at line 763 of file sys_win32.c.
Referenced by Com_Init().
qboolean Sys_PIDIsRunning (unsigned int pid)
Sys_PIDIsRunning.
Check if specified PID is running.
Parameters
[in] pid
Returns
Definition at line 773 of file sys_win32.c.
void Sys_PlatformInit (void)
Windows specific initialization.
Unix specific initialisation.
Definition at line 996 of file sys_win32.c.
Referenced by main().
qboolean Sys_RandomBytes (byte * string, int len)
Sys_RandomBytes.
Parameters
[in] string
[in] len
Returns
Definition at line 135 of file sys_win32.c.
Referenced by Com_RandomBytes().
void Sys_SetEnv (const char * name, const char * value)
Set/unset environment variables (empty value removes it)
Set/Unset environment variables.
Parameters
name
value
Definition at line 754 of file sys_win32.c.
Referenced by CL_InitRef(), Sys_GLimpInit(), and Sys_GLimpSafeInit().
void Sys_SetProcessProperties (void)
Sys_SetProcessProperties.
Todo:
: This could be enabled in the future
Definition at line 942 of file sys_win32.c.
Referenced by Sys_PlatformInit().
void Sys_Sleep (int msec)
Block execution for msec or until input is received.
Parameters
msec
Definition at line 590 of file sys_win32.c.
void Sys_SnapVector (float * v)
Sys_SnapVector.
Parameters
[in,out] v
Definition at line 122 of file sys_win32.c.
Referenced by CL_CgameSystemCalls(), and SV_GameSystemCalls().
void Sys_StartProcess (char * cmdline, qboolean doexit)
Sys_StartProcess.
Starts process.
Parameters
[in] cmdline
[in] doexit
Definition at line 803 of file sys_win32.c.
Referenced by Com_RunUpdateBinary().
Variable Documentation
WinVars_t g_wv
Definition at line 991 of file sys_win32.c.
char homePath[MAX_OSPATH] = { 0 } static
Definition at line 62 of file sys_win32.c.
Referenced by Sys_DefaultHomePath().
qboolean SDL_VIDEODRIVER_externallySet = qfalse static
Definition at line 703 of file sys_win32.c.
Referenced by Sys_GLimpInit(), Sys_GLimpSafeInit(), and Sys_PlatformInit().
int sys_timeBase
Definition at line 96 of file sys_win32.c.
Referenced by Sys_Milliseconds().