ET: Legacy: src/sys/sys_osx.m File Reference
sys_osx.m File Reference
This file is just some Mac-specific bits.
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "sys_local.h"
#include <dlfcn.h>
#import <Carbon/Carbon.h>
#import <Cocoa/Cocoa.h>
Functions
dialogResult_t Sys_Dialog (dialogType_t type, const char *message, const char *title)
Display an OS X dialog box.
const char * OSX_ApplicationSupportPath ()
Returns the path to the user's Application Support folder.
bool IsTranslocatedURL (CFURLRef currentURL, CFURLRef *originalURL)
Checks for OSX' App Translocation.
int needsOSXQuarantineFix ()
Check for OSX Quarantine, remove the attributes und restart the app.
Detailed Description
This file is just some Mac-specific bits.
Most of the Mac OS X code is shared with other Unix platforms in sys_unix.c
Definition in file sys_osx.m.
Function Documentation
bool IsTranslocatedURL (CFURLRef currentURL, CFURLRef * originalURL)
Checks for OSX' App Translocation.
Definition at line 122 of file sys_osx.m.
Referenced by needsOSXQuarantineFix().
int needsOSXQuarantineFix ()
Check for OSX Quarantine, remove the attributes und restart the app.
Returns
int: 0 = no action required, 1 = relaunch after dequarantine, >=2 = error, show modal
Definition at line 176 of file sys_osx.m.
Referenced by main().
const char* OSX_ApplicationSupportPath ()
Returns the path to the user's Application Support folder.
Definition at line 111 of file sys_osx.m.
Referenced by Sys_DefaultHomePath().
dialogResult_t Sys_Dialog (dialogType_t type, const char * message, const char * title)
Display an OS X dialog box.
Definition at line 54 of file sys_osx.m.
Referenced by needsOSXQuarantineFix().