ET: Legacy: src/sys/sys_local.h File Reference
sys_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
Functions
void IN_Init (void)
IN_Init.
void IN_Frame (void)
IN_Frame.
void IN_Shutdown (void)
IN_Shutdown.
void IN_Restart (void)
IN_Restart.
void * GLimp_MainWindow (void)
GLimp_MainWindow.
void GLimp_Minimize (void)
Minimize the game so that user is back at the desktop.
void GLimp_Init (glconfig_t *glConfig, windowContext_t *context)
This routine is responsible for initializing the OS specific portions of OpenGL.
void GLimp_Shutdown (void)
GLimp_Shutdown.
void GLimp_EndFrame (void)
Responsible for doing a swapbuffers.
void GLimp_SetGamma (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
GLimp_SetGamma.
void CON_Shutdown (void)
CON_Shutdown.
void CON_Init (void)
CON_Init.
char * CON_Input (void)
CON_Input.
void CON_Print (const char *msg)
CON_Print.
unsigned int CON_LogSize (void)
CON_LogSize.
unsigned int CON_LogWrite (const char *in)
CON_LogWrite.
unsigned int CON_LogRead (char *out, unsigned int outSize)
CON_LogRead.
void Sys_GLimpSafeInit (void)
Unix specific "safe" GL implementation initialisation.
void Sys_GLimpInit (void)
Unix specific GL implementation initialisation.
void Sys_PlatformInit (void)
Unix specific initialisation.
void Sys_SigHandler (int signal) __attribute__((noreturn))
Sys_SigHandler.
void Sys_ErrorDialog (const char *error)
Displays an error message and writes the error into crashlog.txt.
void Sys_AnsiColorPrint (const char *msg)
Transform Q3 colour codes to ANSI escape sequences.
void * Sys_LoadDll (const char *name, qboolean useSystemLib)
First try to load library name from system library path, from executable path, then fs_basepath.
void * Sys_LoadGameDll (const char *name, qboolean extract, intptr_t(**entryPoint)(int,...), intptr_t(*systemcalls)(intptr_t,...))
Loads a mod library. #1 look in fs_homepath #2 look in fs_basepath #3 try to revert to the default mod library.
void Sys_UnloadDll (void *dllHandle)
Sys_UnloadDll.
void Sys_ParseArgs (int argc, char **argv)
Sys_ParseArgs.
void Sys_BuildCommandLine (int argc, char **argv, char *buffer, size_t bufferSize)
Sys_BuildCommandLine.
void Sys_SetUpConsoleAndSignals (void)
Sys_SetUpConsoleAndSignals.
void Sys_GameLoop (void) __attribute__((noreturn))
Main game loop.
Function Documentation
void CON_Init (void)
CON_Init.
Definition at line 54 of file con_passive.c.
Referenced by CON_SigCont(), and Sys_SetUpConsoleAndSignals().
char* CON_Input (void)
CON_Input.
Returns
Definition at line 63 of file con_passive.c.
Referenced by Sys_ConsoleInput().
unsigned int CON_LogRead (char * out, unsigned int outSize)
CON_LogRead.
Parameters
[out] out
[in] outSize
Returns
Definition at line 121 of file con_log.c.
Referenced by Sys_ErrorDialog().
unsigned int CON_LogSize (void)
CON_LogSize.
Returns
Definition at line 49 of file con_log.c.
Referenced by CON_LogFree(), CON_LogRead(), CON_LogWrite(), and Sys_ErrorDialog().
unsigned int CON_LogWrite (const char * in)
CON_LogWrite.
Parameters
[in] in
Returns
Definition at line 75 of file con_log.c.
Referenced by Sys_Print().
void CON_Print (const char * msg)
CON_Print.
Parameters
[in] msg
Definition at line 73 of file con_passive.c.
Referenced by Sys_Print().
void CON_Shutdown (void)
CON_Shutdown.
Definition at line 45 of file con_passive.c.
Referenced by __attribute__().
void GLimp_EndFrame (void)
Responsible for doing a swapbuffers.
Todo:
: remove this nonesense
Definition at line 948 of file sdl_glimp.c.
Referenced by CL_InitRef().
void GLimp_Init (glconfig_t * glConfig, windowContext_t * context)
This routine is responsible for initializing the OS specific portions of OpenGL.
Parameters
[in,out] glConfig
[in] context
Definition at line 877 of file sdl_glimp.c.
Referenced by CL_InitRef().
void* GLimp_MainWindow (void)
GLimp_MainWindow.
Returns
Definition at line 131 of file sdl_glimp.c.
Referenced by IN_Init().
void GLimp_Minimize (void)
Minimize the game so that user is back at the desktop.
Definition at line 139 of file sdl_glimp.c.
Referenced by GLimp_InitCvars().
void GLimp_SetGamma (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
GLimp_SetGamma.
Parameters
[in] red
[in] green
[in] blue
Definition at line 1020 of file sdl_glimp.c.
Referenced by CL_InitRef().
void GLimp_Shutdown (void)
GLimp_Shutdown.
Definition at line 247 of file sdl_glimp.c.
Referenced by CL_InitRef().
void IN_Frame (void)
IN_Frame.
Definition at line 47 of file null_input.c.
Referenced by Com_Frame().
void IN_Init (void)
IN_Init.
Definition at line 40 of file null_input.c.
Referenced by CL_InitRef(), GLimp_Init(), and IN_Restart().
void IN_Restart (void)
IN_Restart.
Definition at line 81 of file null_input.c.
Referenced by CL_InitRef(), GLimp_EndFrame(), and Sys_In_Restart_f().
void IN_Shutdown (void)
IN_Shutdown.
Definition at line 54 of file null_input.c.
Referenced by CL_InitRef(), GLimp_Shutdown(), and Sys_Error().
void Sys_AnsiColorPrint (const char * msg)
Transform Q3 colour codes to ANSI escape sequences.
Parameters
[in] msg
Definition at line 267 of file sys_main.c.
Referenced by CON_Print().
void Sys_BuildCommandLine (int argc, char ** argv, char * buffer, size_t bufferSize)
Sys_BuildCommandLine.
Parameters
[in] argc
[in] argv
[out] buffer
[in] bufferSize
Definition at line 849 of file sys_main.c.
Referenced by main().
void Sys_ErrorDialog (const char * error)
Displays an error message and writes the error into crashlog.txt.
Parameters
[in] error Error String
Displays an error message and writes the error into crashlog.txt.
Parameters
[in] error
Definition at line 664 of file sys_unix.c.
Referenced by Sys_Error().
void Sys_GameLoop (void)
Main game loop.
Definition at line 934 of file sys_main.c.
Referenced by main().
void Sys_GLimpInit (void)
Unix specific GL implementation initialisation.
Unix specific GL implementation initialisation.
Definition at line 1072 of file sys_unix.c.
Referenced by CL_InitRef(), and GLimp_Init().
void Sys_GLimpSafeInit (void)
Unix specific "safe" GL implementation initialisation.
Unix specific "safe" GL implementation initialisation.
Definition at line 1064 of file sys_unix.c.
Referenced by CL_InitRef(), and GLimp_Init().
void* Sys_LoadDll (const char * name, qboolean useSystemLib)
First try to load library name from system library path, from executable path, then fs_basepath.
Parameters
[in] name
[in] useSystemLib
Returns
Definition at line 507 of file sys_main.c.
Referenced by CL_InitRef().
void* Sys_LoadGameDll (const char * name, qboolean extract, intptr_t(**)(int,...) entryPoint, intptr_t(*)(intptr_t,...) systemcalls)
Loads a mod library. #1 look in fs_homepath #2 look in fs_basepath #3 try to revert to the default mod library.
Parameters
[in] name
[in] extract
entryPoint
systemcalls
Returns
libHandle or NULL
Todo:
: use fs_searchpaths from files.c
Definition at line 691 of file sys_main.c.
Referenced by VM_Create().
void Sys_ParseArgs (int argc, char ** argv)
Sys_ParseArgs.
Parameters
[in] argc
[in] argv
Definition at line 823 of file sys_main.c.
Referenced by main().
void Sys_PlatformInit (void)
Unix specific initialisation.
Unix specific initialisation.
Definition at line 1080 of file sys_unix.c.
Referenced by main().
void Sys_SetUpConsoleAndSignals (void)
Sys_SetUpConsoleAndSignals.
Definition at line 918 of file sys_main.c.
Referenced by main(), and Sys_CreateConsoleWindow().
void Sys_SigHandler (int signal)
Sys_SigHandler.
Parameters
[in] signal
Definition at line 887 of file sys_main.c.
Referenced by CON_CtrlHandler(), Sys_PlatformInit(), and Sys_SetUpConsoleAndSignals().
void Sys_UnloadDll (void * dllHandle)
Sys_UnloadDll.
Parameters
[in] dllHandle
Definition at line 489 of file sys_main.c.
Referenced by VM_Clear(), and VM_Free().