ET: Legacy: src/renderer2/tr_growlist.c File Reference
tr_growlist.c File Reference
#include "tr_local.h"
Functions
void Com_InitGrowList (growList_t *list, int maxElements)
Com_InitGrowList.
void Com_DestroyGrowList (growList_t *list)
Com_DestroyGrowList.
int Com_AddToGrowList (growList_t *list, void *data)
Com_AddToGrowList.
void * Com_GrowListElement (const growList_t *list, int index)
Com_GrowListElement.
int Com_IndexForGrowListElement (const growList_t *list, const void *element)
Com_IndexForGrowListElement.
Function Documentation
int Com_AddToGrowList (growList_t * list, void * data)
Com_AddToGrowList.
Parameters
[in,out] list
[in] data
Returns
Definition at line 75 of file tr_growlist.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), AddTriangleToVBOTriangleList(), Com_AddToGrowList(), R_AllocImage(), R_BuildCubeMaps(), R_CreateClusters(), R_CreateIBO(), R_CreateIBO2(), R_CreateSubModelVBOs(), R_CreateVBO(), R_CreateVBO2(), R_inPVS(), R_LoadLightmapsExternal(), R_LoadLightmapsInternal(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteraction(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
void Com_DestroyGrowList (growList_t * list)
Com_DestroyGrowList.
Parameters
[in,out] list
Definition at line 62 of file tr_growlist.c.
Referenced by R_CreateClusters(), R_CreateSubModelVBOs(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteractions(), R_ShutdownImages(), R_ShutdownVBOs(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().
void* Com_GrowListElement (const growList_t * list, int index)
Com_GrowListElement.
Parameters
[in] list
[in] index
Returns
Definition at line 125 of file tr_growlist.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), BindLightMap(), GL_BindNearestCubeMap(), GL_TextureMode(), R_AddWorldSurfaces(), R_BuildCubeMaps(), R_CreateClusters(), R_CreateSubModelVBOs(), R_FindTwoNearestCubeMaps(), R_ImageList_f(), R_inPVS(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteractions(), R_ShutdownImages(), R_ShutdownVBOs(), R_SumOfUsedImages(), R_VBOList_f(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderLightOcclusionQueries(), RB_ShowImages(), RE_GetTextureId(), and RE_RenderToTexture().
int Com_IndexForGrowListElement (const growList_t * list, const void * element)
Com_IndexForGrowListElement.
Parameters
[in] list
[in] element
Returns
Note
Unused
Definition at line 143 of file tr_growlist.c.
void Com_InitGrowList (growList_t * list, int maxElements)
Com_InitGrowList.
Parameters
[out] list
[in] maxElements
Definition at line 51 of file tr_growlist.c.
Referenced by Com_AddToGrowList(), R_BuildCubeMaps(), R_CreateClusters(), R_CreateSubModelVBOs(), R_InitImages(), R_InitVBOs(), R_LoadMD5(), R_LoadMDM(), R_LoadPSA(), R_LoadPSK(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), R_PrecacheInteractions(), RB_RenderEntityOcclusionQueries(), and RB_RenderLightOcclusionQueries().