ET: Legacy: src/renderer2/tr_extra.h File Reference
tr_extra.h File Reference
#include "tr_local.h"
Data Structures
struct glconfig2_t
struct dgridPoint_t
Light grid.
struct memStream_s
Macros
#define Q_max(a, b) ((a) > (b) ? (a) : (b))
#define Q_min(a, b) ((a) < (b) ? (a) : (b))
#define Q_bound(a, b, c) (Q_max(a, Q_min(b, c)))
#define Q_clamp(a, b, c) ((b) >= (c) ? (a) = (b) : (a) < (b) ? (a) = (b) : (a) > (c) ? (a) = (c) : (a))
#define Q_lerp(from, to, frac) (from + ((to - from) * frac))
#define BSP_VERSION_Q3 46
#define REF_HARD_LINKED 1
#define RDF_NOCUBEMAP (1 << 7)
Don't use cubemaps.
#define RDF_NOBLOOM (1 << 8)
Disable bloom. useful for hud models.
#define Vector5Copy(a, b) ((b)[0] = (a)[0], (b)[1] = (a)[1], (b)[2] = (a)[2], (b)[3] = (a)[3], (b)[4] = (a)[4])
#define DotProduct4(x, y) ((x)[0] * (y)[0] + (x)[1] * (y)[1] + (x)[2] * (y)[2] + (x)[3] * (y)[3])
Typedefs
typedef struct memStream_s memStream_t
Helper struct for reading binary file formats.
Enumerations
enum shadowingMode_t {
SHADOWING_NONE, SHADOWING_BLOB, SHADOWING_ESM16, SHADOWING_ESM32,
SHADOWING_VSM16, SHADOWING_VSM32, SHADOWING_EVSM32, SHADOWING_STENCIL
}
cg_shadows modes
enum memInfo_t { MI_NONE, MI_NVX, MI_ATI }
enum textureCompressionRef_t { TCR_NONE = 0x0000, TCR_LATC = 0x0001, TCR_BPTC = 0x0002 }
enum planeSide_t { SIDE_FRONT = 0, SIDE_BACK = 1, SIDE_ON = 2, SIDE_CROSS = 3 }
Plane sides.
enum { MEMSTREAM_SEEK_SET, MEMSTREAM_SEEK_CUR, MEMSTREAM_SEEK_END }
enum { MEMSTREAM_FLAGS_EOF = BIT(0), MEMSTREAM_FLAGS_ERR = BIT(1) }
Functions
int NearestPowerOfTwo (int val)
NearestPowerOfTwo.
qboolean PlanesGetIntersectionPoint (const vec4_t plane1, const vec4_t plane2, const vec4_t plane3, vec3_t out)
PlanesGetIntersectionPoint.
void MatrixMultiplyScale (mat4_t m, vec_t x, vec_t y, vec_t z)
MatrixMultiplyScale.
void MatrixSetupTransformFromRotation (mat4_t m, const mat4_t rot, const vec3_t origin)
MatrixSetupTransformFromRotation.
void MatrixAffineInverse (const mat4_t in, mat4_t out)
MatrixAffineInverse.
void MatrixPerspectiveProjectionFovXYRH (mat4_t m, vec_t fovX, vec_t fovY, vec_t nearvec, vec_t farvec)
MatrixPerspectiveProjectionFovXYRH.
void MatrixLookAtRH (mat4_t m, const vec3_t eye, const vec3_t dir, const vec3_t up)
MatrixLookAtRH.
void PlaneIntersectRay (const vec3_t rayPos, const vec3_t rayDir, const vec4_t plane, vec3_t res)
PlaneIntersectRay.
void MatrixOrthogonalProjectionRH (mat4_t m, vec_t left, vec_t right, vec_t bottom, vec_t top, vec_t nearvec, vec_t farvec)
MatrixOrthogonalProjectionRH.
void MatrixCrop (mat4_t m, const vec3_t mins, const vec3_t maxs)
MatrixCrop.
void MatrixMultiplyTranslation (mat4_t m, vec_t x, vec_t y, vec_t z)
MatrixMultiplyTranslation.
void MatrixMultiplyZRotation (mat4_t m, vec_t degrees)
MatrixMultiplyZRotation.
void MatrixSetupZRotation (mat4_t m, vec_t degrees)
MatrixSetupZRotation.
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
BoundsIntersect.
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
BoundsIntersectSphere.
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
BoundsIntersectPoint.
void ZeroBounds (vec3_t mins, vec3_t maxs)
ZeroBounds.
void MatrixSetupTransformFromQuat (mat4_t m, const quat_t quat, const vec3_t origin)
MatrixSetupTransformFromQuat.
vec_t PlaneNormalize (vec4_t plane)
returns normal length
void MatrixTransformNormal (const mat4_t m, const vec3_t in, vec3_t out)
MatrixTransformNormal.
void MatrixTransformNormal2 (const mat4_t m, vec3_t inout)
MatrixTransformNormal2.
void MatrixTransformPlane (const mat4_t m, const vec4_t in, vec4_t out)
MatrixTransformPlane.
void MatrixTransformBounds (const mat4_t m, const vec3_t mins, const vec3_t maxs, vec3_t omins, vec3_t omaxs)
MatrixTransformBounds.
void MatrixPerspectiveProjectionFovXYInfiniteRH (mat4_t m, vec_t fovX, vec_t fovY, vec_t nearvec)
MatrixPerspectiveProjectionFovXYInfiniteRH.
void QuatTransformVector (const quat_t q, const vec3_t in, vec3_t out)
QuatTransformVector.
void MatrixSetupShear (mat4_t m, vec_t x, vec_t y)
MatrixSetupShear.
void MatrixMultiplyShear (mat4_t m, vec_t x, vec_t y)
MatrixMultiplyShear.
void MatrixFromPlanes (mat4_t m, const vec4_t left, const vec4_t right, const vec4_t bottom, const vec4_t top, const vec4_t nearvec, const vec4_t farvec)
MatrixFromPlanes.
void QuatMultiply0 (quat_t qa, const quat_t qb)
QuatMultiply0.
void QuatMultiply1 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply1.
void QuatMultiply2 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply2.
void QuatMultiply3 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply3.
void QuatMultiply4 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply4.
qboolean Q_strreplace (char *dest, size_t destsize, const char *find, const char *replace)
Replaces content of find by replace in dest.
static ID_INLINE int Vector4Compare (const vec4_t v1, const vec4_t v2)
Vector4Compare.
static ID_INLINE int Vector5Compare (const vec5_t v1, const vec5_t v2)
Vector5Compare.
static ID_INLINE float Q_recip (float in)
Q_recip.
static ID_INLINE void VectorToAngles (const vec3_t value1, vec3_t angles)
VectorToAngles.
static ID_INLINE void VectorLerp (const vec3_t from, const vec3_t to, float frac, vec3_t out)
VectorLerp.
static ID_INLINE void QuatClear (quat_t q)
QuatClear.
static ID_INLINE void QuatCalcW (quat_t q)
QuatCalcW.
memStream_t * AllocMemStream (byte *buffer, int bufSize)
AllocMemStream.
void FreeMemStream (memStream_t *s)
FreeMemStream.
qboolean MemStreamRead (memStream_t *s, void *buffer, unsigned int len)
MemStreamRead.
int MemStreamGetC (memStream_t *s)
MemStreamGetC.
int MemStreamGetLong (memStream_t *s)
MemStreamGetLong.
int MemStreamGetShort (memStream_t *s)
MemStreamGetShort.
float MemStreamGetFloat (memStream_t *s)
MemStreamGetFloat.
void printBits (size_t const size, void const *const ptr)
printBits
Variables
mat4_t matrixIdentity
quat_t quatIdentity
Macro Definition Documentation
#define BSP_VERSION_Q3 46
Definition at line 47 of file tr_extra.h.
Referenced by RE_LoadWorldMap().
#define DotProduct4 (x, y) ((x)[0] * (y)[0] + (x)[1] * (y)[1] + (x)[2] * (y)[2] + (x)[3] * (y)[3])
Definition at line 217 of file tr_extra.h.
Referenced by R_SetupLightProjection().
#define Q_bound (a, b, c) (Q_max(a, Q_min(b, c)))
Definition at line 43 of file tr_extra.h.
Referenced by GLimp_InitExtensionsR2(), R_AddNormals(), R_GetTag(), and R_LoadEntities().
#define Q_clamp (a, b, c) ((b) >= (c) ? (a) = (b) : (a) < (b) ? (a) = (b) : (a) > (c) ? (a) = (c) : (a))
Definition at line 44 of file tr_extra.h.
Referenced by R_SetupLightScissor(), RB_CalculateAdaptation(), RB_EvalExpression(), and RE_BuildSkeleton().
#define Q_lerp (from, to, frac) (from + ((to - from) * frac))
Definition at line 45 of file tr_extra.h.
#define Q_max (a, b) ((a) > (b) ? (a) : (b))
Definition at line 41 of file tr_extra.h.
Referenced by GLimp_InitExtensionsR2(), R_SetupProjection(), and RB_RenderInteractionsShadowMapped().
#define Q_min (a, b) ((a) < (b) ? (a) : (b))
Definition at line 42 of file tr_extra.h.
Referenced by QueryReasonable(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), Render_lightVolume(), and Tess_SurfacePolybuffer().
#define RDF_NOBLOOM (1 << 8)
Disable bloom. useful for hud models.
Definition at line 131 of file tr_extra.h.
Referenced by R_BuildCubeMaps(), and RB_RenderBloom().
#define RDF_NOCUBEMAP (1 << 7)
Don't use cubemaps.
Definition at line 130 of file tr_extra.h.
Referenced by R_BuildCubeMaps(), and RB_RenderDebugUtils().
#define REF_HARD_LINKED 1
Definition at line 48 of file tr_extra.h.
#define Vector5Copy (a, b) ((b)[0] = (a)[0], (b)[1] = (a)[1], (b)[2] = (a)[2], (b)[3] = (a)[3], (b)[4] = (a)[4])
Definition at line 213 of file tr_extra.h.
Referenced by GLSL_SetUniformFloat5().
Typedef Documentation
memStream_t
Helper struct for reading binary file formats.
Enumeration Type Documentation
anonymous enum
Enumerator
MEMSTREAM_SEEK_SET
MEMSTREAM_SEEK_CUR
MEMSTREAM_SEEK_END
Definition at line 335 of file tr_extra.h.
anonymous enum
Enumerator
MEMSTREAM_FLAGS_EOF
MEMSTREAM_FLAGS_ERR
Definition at line 342 of file tr_extra.h.
enum memInfo_t
Enumerator
MI_NONE
MI_NVX
MI_ATI
Definition at line 137 of file tr_extra.h.
enum planeSide_t
Plane sides.
Enumerator
SIDE_FRONT
SIDE_BACK
SIDE_ON
SIDE_CROSS
Definition at line 162 of file tr_extra.h.
enum shadowingMode_t
cg_shadows modes
Enumerator
SHADOWING_NONE
SHADOWING_BLOB
SHADOWING_ESM16
SHADOWING_ESM32
SHADOWING_VSM16
SHADOWING_VSM32
SHADOWING_EVSM32
SHADOWING_STENCIL
Definition at line 106 of file tr_extra.h.
enum textureCompressionRef_t
Enumerator
TCR_NONE
TCR_LATC
TCR_BPTC
Definition at line 148 of file tr_extra.h.
Function Documentation
memStream_t* AllocMemStream (byte * buffer, int bufSize)
AllocMemStream.
Parameters
[in] buffer
[in] bufSize
Returns
Definition at line 814 of file tr_extra.c.
Referenced by R_LoadPSA(), and R_LoadPSK().
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
BoundsIntersect.
Parameters
[in] mins
[in] maxs
[in] mins2
[in] maxs2
Returns
Definition at line 339 of file tr_extra.c.
Referenced by R_AddBrushModelInteractions(), R_AddLightInteractions(), R_AddMD5Interactions(), R_AddMDMInteractions(), R_AddMDVInteractions(), R_AddPolygonInteractions(), R_AddPolysToScene(), R_LightSurfaceGeneric(), R_PrecacheGenericSurfInteraction(), and RE_AddPolyBufferToScene().
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
BoundsIntersectPoint.
Parameters
[in] mins
[in] maxs
[in] origin
Returns
Note
Unused
Definition at line 382 of file tr_extra.c.
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
BoundsIntersectSphere.
Parameters
[in] mins
[in] maxs
[in] origin
[in] radius
Returns
Note
Unused
Definition at line 360 of file tr_extra.c.
void FreeMemStream (memStream_t * s)
FreeMemStream.
Parameters
[in] s
Definition at line 843 of file tr_extra.c.
Referenced by R_LoadPSA().
void MatrixAffineInverse (const mat4_t in, mat4_t out)
MatrixAffineInverse.
Parameters
[in] in
[out] out
Definition at line 145 of file tr_extra.c.
Referenced by R_CalcLightCubeSideBits(), R_RotateEntityForLight(), R_RotateEntityForViewParms(), R_RotateForViewer(), R_RotateLightForViewParms(), R_SetupLightView(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), and RenderEntityOcclusionVolume().
void MatrixCrop (mat4_t m, const vec3_t mins, const vec3_t maxs)
MatrixCrop.
Parameters
[out] m
[in] mins
[in] maxs
Definition at line 258 of file tr_extra.c.
Referenced by RB_RenderInteractionsShadowMapped().
void MatrixFromPlanes (mat4_t m, const vec4_t left, const vec4_t right, const vec4_t bottom, const vec4_t top, const vec4_t nearvec, const vec4_t farvec)
MatrixFromPlanes.
Parameters
[out] m
[in] left
[in] right
[in] bottom
[in] top
[in] nearvec
[in] farvec
Definition at line 735 of file tr_extra.c.
Referenced by R_SetupLightProjection().
void MatrixLookAtRH (mat4_t m, const vec3_t eye, const vec3_t dir, const vec3_t up)
MatrixLookAtRH.
Parameters
[out] m
[in] eye
[in] dir
[in] up
Definition at line 191 of file tr_extra.c.
Referenced by R_RotateForViewer(), RB_RenderDebugUtils(), and RB_RenderInteractionsShadowMapped().
void MatrixMultiplyScale (mat4_t m, vec_t x, vec_t y, vec_t z)
MatrixMultiplyScale.
Parameters
[in,out] m
[in] x
[in] y
[in] z
Definition at line 110 of file tr_extra.c.
Referenced by R_SetupUnprojection(), RB_CalcTexMatrix(), RB_CameraPostFX(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), and Render_lightVolume().
void MatrixMultiplyShear (mat4_t m, vec_t x, vec_t y)
MatrixMultiplyShear.
Parameters
[in,out] m
[in] x
[in] y
Definition at line 716 of file tr_extra.c.
Referenced by RB_CalcTexMatrix().
void MatrixMultiplyTranslation (mat4_t m, vec_t x, vec_t y, vec_t z)
MatrixMultiplyTranslation.
Parameters
[in,out] m
[in] x
[in] y
[in] z
Definition at line 285 of file tr_extra.c.
Referenced by R_SetupUnprojection(), RB_CalcTexMatrix(), and RB_CameraPostFX().
void MatrixMultiplyZRotation (mat4_t m, vec_t degrees)
MatrixMultiplyZRotation.
Parameters
[in,out] m
[in] degrees
Definition at line 321 of file tr_extra.c.
Referenced by RB_CalcTexMatrix(), and RB_CameraPostFX().
void MatrixOrthogonalProjectionRH (mat4_t m, vec_t left, vec_t right, vec_t bottom, vec_t top, vec_t nearvec, vec_t farvec)
MatrixOrthogonalProjectionRH.
Parameters
[out] m
[in] left
[in] right
[in] bottom
[in] top
[in] nearvec
[in] farvec
Note
same as D3DXMatrixOrthoOffCenterRH
http://msdn.microsoft.com/en-us/library/bb205348(VS.85).aspx
Definition at line 244 of file tr_extra.c.
Referenced by RB_RenderDebugUtils(), and RB_RenderInteractionsShadowMapped().
void MatrixPerspectiveProjectionFovXYInfiniteRH (mat4_t m, vec_t fovX, vec_t fovY, vec_t nearvec)
MatrixPerspectiveProjectionFovXYInfiniteRH.
Parameters
[out] m
[in] fovX
[in] fovY
[in] nearvec
Note
far plane at infinity, see RobustShadowVolumes.pdf by Nvidia
Definition at line 585 of file tr_extra.c.
Referenced by R_SetupProjection().
void MatrixPerspectiveProjectionFovXYRH (mat4_t m, vec_t fovX, vec_t fovY, vec_t nearvec, vec_t farvec)
MatrixPerspectiveProjectionFovXYRH.
Parameters
[out] m
[in] fovX
[in] fovY
[in] nearvec
[in] farvec
Definition at line 171 of file tr_extra.c.
Referenced by R_SetupProjection(), and RB_RenderInteractionsShadowMapped().
void MatrixSetupShear (mat4_t m, vec_t x, vec_t y)
MatrixSetupShear.
Parameters
[out] m
[in] x
[in] y
Definition at line 702 of file tr_extra.c.
Referenced by MatrixMultiplyShear().
void MatrixSetupTransformFromQuat (mat4_t m, const quat_t quat, const vec3_t origin)
MatrixSetupTransformFromQuat.
Parameters
[out] m
[in] quat
[in] origin
Definition at line 410 of file tr_extra.c.
Referenced by R_AddLightBoundsToVisBounds(), R_AddLightInteractions(), R_LoadMD5(), R_LoadPSK(), R_PrecacheInteractions(), Tess_SurfaceMD5(), and Tess_SurfaceVBOMD5Mesh().
void MatrixSetupTransformFromRotation (mat4_t m, const mat4_t rot, const vec3_t origin)
MatrixSetupTransformFromRotation.
Parameters
[out] m
[in] rot
[in] origin
Definition at line 132 of file tr_extra.c.
Referenced by R_CalcLightCubeSideBits(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), and Tess_SurfaceVBOMDMMesh().
void MatrixSetupZRotation (mat4_t m, vec_t degrees)
MatrixSetupZRotation.
Parameters
[out] m
[in] degrees
Definition at line 306 of file tr_extra.c.
Referenced by MatrixMultiplyZRotation().
void MatrixTransformBounds (const mat4_t m, const vec3_t mins, const vec3_t maxs, vec3_t omins, vec3_t omaxs)
MatrixTransformBounds.
Parameters
[in] m
[in] mins
[in] mins
[out] omins
[out] omax Achieves the same result as:
BoundsClear(omins, omaxs); for each corner c in bounds{imins, imaxs} { vec3_t p; MatrixTransformPoint(m, c, p); AddPointToBounds(p, omins, omaxs); }
With fewer operations
Pseudocode: omins = min(mins.x*m.c1, maxs.x*m.c1) + min(mins.y*m.c2, maxs.y*m.c2) + min(mins.z*m.c3, maxs.z*m.c3) + c4 omaxs = max(mins.x*m.c1, maxs.x*m.c1) + max(mins.y*m.c2, maxs.y*m.c2) + max(mins.z*m.c3, maxs.z*m.c3) + c4
Definition at line 520 of file tr_extra.c.
Referenced by R_CullLocalBox(), R_SetupEntityWorldBounds(), and R_SetupLightWorldBounds().
void MatrixTransformNormal (const mat4_t m, const vec3_t in, vec3_t out)
MatrixTransformNormal.
Parameters
[in] m
[in] in
[out] out
Definition at line 453 of file tr_extra.c.
Referenced by MatrixTransformPlane(), QuatTransformVector(), R_LocalNormalToWorld(), and Tess_SurfaceMD5().
void MatrixTransformNormal2 (const mat4_t m, vec3_t inout)
MatrixTransformNormal2.
Parameters
[in] m
[in,out] inout
Definition at line 465 of file tr_extra.c.
Referenced by R_RotateForViewer(), and RenderEntityOcclusionVolume().
void MatrixTransformPlane (const mat4_t m, const vec4_t in, vec4_t out)
MatrixTransformPlane.
Parameters
[in] m
[in] in
[out] out
Definition at line 482 of file tr_extra.c.
Referenced by MatrixTransformPlane2(), R_SetupLightFrustum(), and RB_RenderDebugUtils().
int MemStreamGetC (memStream_t * s)
MemStreamGetC.
Parameters
[in] s
Returns
Definition at line 881 of file tr_extra.c.
Referenced by GetChunkHeader(), and R_LoadPSK().
float MemStreamGetFloat (memStream_t * s)
MemStreamGetFloat.
Parameters
[in] s
Returns
Definition at line 947 of file tr_extra.c.
Referenced by GetBone(), R_LoadPSA(), and R_LoadPSK().
int MemStreamGetLong (memStream_t * s)
MemStreamGetLong.
Parameters
[in] s
Returns
Definition at line 903 of file tr_extra.c.
Referenced by GetChunkHeader(), R_LoadPSA(), and R_LoadPSK().
int MemStreamGetShort (memStream_t * s)
MemStreamGetShort.
Parameters
[in] s
Returns
Definition at line 925 of file tr_extra.c.
Referenced by R_LoadPSK().
qboolean MemStreamRead (memStream_t * s, void * buffer, unsigned int len)
MemStreamRead.
Parameters
[in,out] s
[out] buffer
[in] len
Returns
Definition at line 855 of file tr_extra.c.
Referenced by MemStreamGetC(), MemStreamGetFloat(), MemStreamGetLong(), MemStreamGetShort(), R_LoadPSA(), and R_LoadPSK().
int NearestPowerOfTwo (int val)
NearestPowerOfTwo.
Parameters
[in] val
Returns
Definition at line 49 of file tr_extra.c.
Referenced by GLSL_BuildShaderExtraDef(), R_CreateReadyFBO(), R_CreateRenderImage(), and R_InitFBOs().
void PlaneIntersectRay (const vec3_t rayPos, const vec3_t rayDir, const vec4_t plane, vec3_t res)
PlaneIntersectRay.
Parameters
[in] rayPos
[in] rayDir
[in] plane
[out] res
Definition at line 218 of file tr_extra.c.
Referenced by RB_RenderInteractionsShadowMapped().
vec_t PlaneNormalize (vec4_t plane)
returns normal length
returns normal length
Parameters
[in,out] plane
Returns
Definition at line 427 of file tr_extra.c.
Referenced by R_SetupLightFrustum(), and R_SetupLightProjection().
qboolean PlanesGetIntersectionPoint (const vec4_t plane1, const vec4_t plane2, const vec4_t plane3, vec3_t out)
PlanesGetIntersectionPoint.
Parameters
[in] plane1
[in] plane2
[in] plane3
[out] out
Returns
Definition at line 66 of file tr_extra.c.
Referenced by R_SetupLightFrustum(), R_SetupLightLocalBounds(), R_SetupLightScissor(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), and RenderLightOcclusionVolume().
void printBits (size_t const size, void const *const ptr)
printBits
Parameters
[in] size
[in] ptr
Note
Unused
Definition at line 973 of file tr_extra.c.
static ID_INLINE float Q_recip (float in) static
Q_recip.
Parameters
[in] in
Returns
Definition at line 254 of file tr_extra.h.
Referenced by GLSL_BuildShaderExtraDef(), and R_SetupUnprojection().
qboolean Q_strreplace (char * dest, size_t destsize, const char * find, const char * replace)
Replaces content of find by replace in dest.
Parameters
[out] dest
[in] destsize
[in] find
[in] replace
Returns
Definition at line 773 of file tr_extra.c.
Referenced by CreateShaderByGuide().
static ID_INLINE void QuatCalcW (quat_t q) static
QuatCalcW.
Parameters
[in,out] q
Definition at line 315 of file tr_extra.h.
Referenced by R_LoadMD5(), R_LoadMD5Anim(), and RE_BuildSkeleton().
static ID_INLINE void QuatClear (quat_t q) static
QuatClear.
Parameters
[out] q
Definition at line 303 of file tr_extra.h.
Referenced by RE_AddDynamicLightToScene(), RE_BuildSkeleton(), and resetRefLight().
void QuatMultiply0 (quat_t qa, const quat_t qb)
QuatMultiply0.
Parameters
[in,out] qa
[in] qb
Note
Unused
Definition at line 619 of file tr_extra.c.
void QuatMultiply1 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply1.
Parameters
[in] qa
[in] qb
[out] qc
Definition at line 633 of file tr_extra.c.
Referenced by QuatMultiply0(), R_LoadPSK(), and RE_BuildSkeleton().
void QuatMultiply2 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply2.
Parameters
[in] qa
[in] qb
[out] qc
Note
Unused
Definition at line 656 of file tr_extra.c.
void QuatMultiply3 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply3.
Parameters
[in] qa
[in] qb
[out] qc
Note
Unused
Definition at line 672 of file tr_extra.c.
void QuatMultiply4 (const quat_t qa, const quat_t qb, quat_t qc)
QuatMultiply4.
Parameters
[in] qa
[in] qb
[out] qc
Note
Unused
Definition at line 688 of file tr_extra.c.
void QuatTransformVector (const quat_t q, const vec3_t in, vec3_t out)
QuatTransformVector.
Parameters
[in] q
[in] in
[out] out
Definition at line 604 of file tr_extra.c.
Referenced by R_LoadMD5(), R_LoadPSK(), and RE_BuildSkeleton().
static ID_INLINE int Vector4Compare (const vec4_t v1, const vec4_t v2) static
Vector4Compare.
Parameters
[in] v1
[in] v2
Returns
Definition at line 225 of file tr_extra.h.
Referenced by GLSL_SetUniformVec4().
static ID_INLINE int Vector5Compare (const vec5_t v1, const vec5_t v2) static
Vector5Compare.
Parameters
[in] v1
[in] v2
Returns
Definition at line 240 of file tr_extra.h.
Referenced by GLSL_SetUniformFloat5().
static ID_INLINE void VectorLerp (const vec3_t from, const vec3_t to, float frac, vec3_t out) static
VectorLerp.
Parameters
[in] from
[in] to
[in] frac
[out] out
Definition at line 292 of file tr_extra.h.
Referenced by RE_BlendSkeleton(), and RE_BuildSkeleton().
static ID_INLINE void VectorToAngles (const vec3_t value1, vec3_t angles) static
VectorToAngles.
Parameters
[in] value1
[out] angles
Definition at line 278 of file tr_extra.h.
Referenced by RB_RenderDebugUtils(), and RB_RenderInteractionsShadowMapped().
void ZeroBounds (vec3_t mins, vec3_t maxs)
ZeroBounds.
Parameters
[out] mins
[out] maxs
Definition at line 398 of file tr_extra.c.
Referenced by R_CreateVBOShadowCubeMeshes().
Variable Documentation
mat4_t matrixIdentity
Definition at line 38 of file tr_extra.c.
Referenced by R_CoherentHierachicalCulling(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_SetGL2D(), RB_SetViewMVPM(), RB_ShowImages(), and RE_StretchRaw().
quat_t quatIdentity
Definition at line 42 of file tr_extra.c.