ET: Legacy: src/renderer/tr_model.c File Reference
tr_model.c File Reference
Model loading and caching.
#include "tr_local.h"
#include "../renderercommon/anorms256.h"
Macros
#define R_HUNK_MEGS 24
#define R_HUNK_SIZE (R_HUNK_MEGS *1024 *1024)
Functions
static qboolean R_LoadMDC (model_t *mod, int lod, void *buffer, const char *name)
R_LoadMDC.
static qboolean R_LoadMD3 (model_t *mod, int lod, void *buffer, const char *name)
R_LoadMD3.
static qboolean R_LoadMDS (model_t *mod, void *buffer, const char *name)
R_LoadMDS.
static qboolean R_LoadMDM (model_t *mod, void *buffer, const char *name)
R_LoadMDM.
static qboolean R_LoadMDX (model_t *mod, void *buffer, const char *name)
R_LoadMDX.
model_t * R_GetModelByHandle (qhandle_t hModel)
R_GetModelByHandle.
model_t * R_AllocModel (void)
[in] R_AllocModel
void R_LoadModelShadow (model_t *mod)
Loads a model's shadow script.
qhandle_t RE_RegisterModel (const char *name)
Loads in a model for the given name.
void RE_BeginRegistration (glconfig_t *glconfigOut)
RE_BeginRegistration.
void R_ModelInit (void)
R_ModelInit.
void R_Modellist_f (void)
R_Modellist_f.
static int R_GetTag (byte *mod, int frame, const char *tagName, int startTagIndex, md3Tag_t **outTag)
R_GetTag.
static int R_GetMDCTag (byte *mod, int frame, const char *tagName, int startTagIndex, mdcTag_t **outTag)
R_GetMDCTag.
int R_LerpTag (orientation_t *tag, const refEntity_t *refent, const char *tagNameIn, int startIndex)
R_LerpTag.
void R_TagInfo_f (void)
R_TagInfo_f.
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
R_ModelBounds.
void * R_Hunk_Begin (void)
R_Hunk_Begin.
void * R_Hunk_Alloc (int size)
R_Hunk_Alloc.
void R_Hunk_End (void)
This is only called when we shutdown GL.
void R_Hunk_Reset (void)
R_Hunk_Reset.
void * R_CacheModelAlloc (int size)
R_CacheModelAlloc.
void R_CacheModelFree (void *ptr)
R_CacheModelFree.
void R_PurgeModels (int count)
R_PurgeModels.
void R_BackupModels (void)
R_BackupModels.
static void R_RegisterMDCShaders (model_t *mod, int lod)
R_RegisterMDCShaders.
static void R_RegisterMD3Shaders (model_t *mod, int lod)
R_RegisterMD3Shaders.
qboolean R_FindCachedModel (const char *name, model_t *newmod)
Look for the given model in the list of backupModels.
void R_LoadCacheModels (void)
R_LoadCacheModels.
Variables
float r_anormals [NUMMDCVERTEXNORMALS][3]
byte * membase = NULL
int hunkmaxsize
int cursize
static model_t backupModels [MAX_MOD_KNOWN]
static int numBackupModels = 0
Detailed Description
Model loading and caching.
Definition in file tr_model.c.
Macro Definition Documentation
#define R_HUNK_MEGS 24
Definition at line 2253 of file tr_model.c.
#define R_HUNK_SIZE (R_HUNK_MEGS *1024 *1024)
Definition at line 2254 of file tr_model.c.
Referenced by R_Hunk_Begin().
Function Documentation
model_t* R_AllocModel (void)
[in] R_AllocModel
Returns
Definition at line 74 of file tr_model.c.
Referenced by R_ModelInit(), and RE_RegisterModel().
void R_BackupModels (void)
R_BackupModels.
Definition at line 2442 of file tr_model.c.
void* R_CacheModelAlloc (int size)
R_CacheModelAlloc.
Parameters
[in] size
Returns
Definition at line 2390 of file tr_model.c.
Referenced by R_BackupModels().
void R_CacheModelFree (void * ptr)
R_CacheModelFree.
Parameters
ptr - unused
Definition at line 2406 of file tr_model.c.
Referenced by R_FindCachedModel().
qboolean R_FindCachedModel (const char * name, model_t * newmod)
Look for the given model in the list of backupModels.
Parameters
[in] name
[in,out] newmod
Returns
Definition at line 2593 of file tr_model.c.
Referenced by RE_RegisterModel().
static int R_GetMDCTag (byte * mod, int frame, const char * tagName, int startTagIndex, mdcTag_t ** outTag) static
R_GetMDCTag.
Parameters
[in] mod
[in] frame
[in] tagName
[in] startTagIndex
[out] outTag
Returns
Definition at line 1982 of file tr_model.c.
Referenced by R_LerpTag().
model_t* R_GetModelByHandle (qhandle_t hModel)
R_GetModelByHandle.
Parameters
[in] hModel
Returns
Definition at line 53 of file tr_model.c.
Referenced by R_LerpTag(), R_ModelBounds(), RE_BoneIndex(), RE_LerpTagET(), and RE_LerpTagQ3A().
static int R_GetTag (byte * mod, int frame, const char * tagName, int startTagIndex, md3Tag_t ** outTag) static
R_GetTag.
Parameters
[in] mod
[in] frame
[in] tagName
[in] startTagIndex
[out] outTag
Returns
Definition at line 1939 of file tr_model.c.
Referenced by R_LerpTag().
void* R_Hunk_Alloc (int size)
R_Hunk_Alloc.
Parameters
[in] size
Returns
Definition at line 2302 of file tr_model.c.
Referenced by R_CacheModelAlloc().
void* R_Hunk_Begin (void)
R_Hunk_Begin.
Returns
Definition at line 2260 of file tr_model.c.
void R_Hunk_End (void)
This is only called when we shutdown GL.
Definition at line 2338 of file tr_model.c.
void R_Hunk_Reset (void)
R_Hunk_Reset.
Definition at line 2357 of file tr_model.c.
Referenced by R_PurgeModels().
int R_LerpTag (orientation_t * tag, const refEntity_t * refent, const char * tagNameIn, int startIndex)
R_LerpTag.
Parameters
[in,out] tag
[in] refent
[in] tagNameIn
[in] startIndex
Returns
The index of the tag it found, for cycling through tags with the same name
Todo:
: retval is reassigned before used, does it was intended ?
Todo:
: retval is reassigned before used, does it was intended ?
Definition at line 2031 of file tr_model.c.
void R_LoadCacheModels (void)
R_LoadCacheModels.
Definition at line 2681 of file tr_model.c.
Referenced by R_ModelInit().
static qboolean R_LoadMD3 (model_t * mod, int lod, void * buffer, const char * name) static
R_LoadMD3.
Parameters
[in,out] mod
[in] lod
[in,out] buffer
[in] name
Returns
Definition at line 1110 of file tr_model.c.
Referenced by RE_RegisterModel().
static qboolean R_LoadMDC (model_t * mod, int lod, void * buffer, const char * name) static
R_LoadMDC.
Parameters
[in,out] mod
[in] lod
[in,out] buffer
[in] name
Returns
Definition at line 883 of file tr_model.c.
Referenced by RE_RegisterModel().
static qboolean R_LoadMDM (model_t * mod, void * buffer, const char * name) static
R_LoadMDM.
Parameters
[in,out] mod
[in,out] buffer
[in] name
Returns
Definition at line 1548 of file tr_model.c.
Referenced by RE_RegisterModel().
static qboolean R_LoadMDS (model_t * mod, void * buffer, const char * name) static
R_LoadMDS.
Parameters
[in,out] mod
[in,out] buffer
[in] name
Returns
Definition at line 1320 of file tr_model.c.
Referenced by RE_RegisterModel().
static qboolean R_LoadMDX (model_t * mod, void * buffer, const char * name) static
R_LoadMDX.
Parameters
[in,out] mod
[in,out] buffer
[in] name
Returns
Definition at line 1767 of file tr_model.c.
Referenced by RE_RegisterModel().
void R_LoadModelShadow (model_t * mod)
Loads a model's shadow script.
Parameters
[in,out] mod
Definition at line 96 of file tr_model.c.
Referenced by RE_RegisterModel().
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
R_ModelBounds.
Parameters
[in] handle
[out] mins
[out] maxs
Definition at line 2200 of file tr_model.c.
void R_ModelInit (void)
R_ModelInit.
Definition at line 1872 of file tr_model.c.
void R_Modellist_f (void)
R_Modellist_f.
Definition at line 1896 of file tr_model.c.
void R_PurgeModels (int count)
R_PurgeModels.
Parameters
count - unused
Definition at line 2423 of file tr_model.c.
Referenced by R_BackupModels().
static void R_RegisterMD3Shaders (model_t * mod, int lod) static
R_RegisterMD3Shaders.
Parameters
[in] mod
[in] lod
Definition at line 2556 of file tr_model.c.
Referenced by R_FindCachedModel().
static void R_RegisterMDCShaders (model_t * mod, int lod) static
R_RegisterMDCShaders.
Parameters
[in] mod
[in] lod
Definition at line 2520 of file tr_model.c.
Referenced by R_FindCachedModel().
void R_TagInfo_f (void)
R_TagInfo_f.
Todo:
FIXME:
Definition at line 2158 of file tr_model.c.
void RE_BeginRegistration (glconfig_t * glconfigOut)
RE_BeginRegistration.
Parameters
[out] glconfigOut
Definition at line 1847 of file tr_model.c.
qhandle_t RE_RegisterModel (const char * name)
Loads in a model for the given name.
Zero will be returned if the model fails to load. An entry will be retained for failed models as an optimization to prevent disk rescanning if they are asked for again.
Parameters
[in] name
Returns
Todo:
: catch shader case earlier and avoid i/o (mod code?)
Definition at line 163 of file tr_model.c.
Referenced by R_LoadCacheModels().
Variable Documentation
model_t backupModels[MAX_MOD_KNOWN] static
Todo:
: convert the Hunk_Alloc's in the model loading to Com_Allocate's, so we don't have
Definition at line 2382 of file tr_model.c.
Referenced by R_BackupModels(), and R_FindCachedModel().
int cursize
Definition at line 2251 of file tr_model.c.
Referenced by CL_Netchan_Decode(), MSG_Copy(), R_Hunk_Alloc(), R_Hunk_Begin(), R_Hunk_Reset(), and SV_Netchan_Decode().
int hunkmaxsize
Definition at line 2250 of file tr_model.c.
Referenced by R_Hunk_Alloc(), and R_Hunk_Begin().
byte* membase = NULL
Definition at line 2249 of file tr_model.c.
Referenced by R_Hunk_Alloc(), R_Hunk_Begin(), R_Hunk_End(), and R_Hunk_Reset().
int numBackupModels = 0 static
Definition at line 2383 of file tr_model.c.
Referenced by R_BackupModels(), R_FindCachedModel(), R_LoadCacheModels(), and R_PurgeModels().
float r_anormals[NUMMDCVERTEXNORMALS][3]
Definition at line 408 of file tr_model.c.