ET: Legacy: src/renderercommon/tr_image_jpg.c File Reference
tr_image_jpg.c File Reference
#include "tr_common.h"
#include <jpeglib.h>
#include <setjmp.h>
Data Structures
struct my_jpeg_error_mgr
Override default libjpeg error manager in order to be able to jump back out to our routines during JPEG decoding. setjmp/longjmp buffer is added to make a custom JPEG manager struct.
struct my_destination_mgr
Expanded data destination object for stdio output.
Typedefs
typedef my_destination_mgr * my_dest_ptr
Functions
static void __attribute__ ((noreturn))
R_JPGErrorExit.
static void R_JPGOutputMessage (j_common_ptr cinfo)
R_JPGOutputMessage.
void R_LoadJPG (const char *filename, unsigned char **pic, int *width, int *height, byte alphaByte)
R_LoadJPG.
static void init_destination (j_compress_ptr cinfo)
Initialize destination — called by jpeg_start_compress before any data is actually written.
static boolean empty_output_buffer (j_compress_ptr cinfo)
Empty the output buffer — Called whenever buffer fills up.
static void term_destination (j_compress_ptr cinfo)
Terminate destination — called by jpeg_finish_compress after all data has been written. Usually needs to flush buffer.
static void jpegDest (j_compress_ptr cinfo, byte *outfile, int size)
Prepare for output to a stdio stream. The caller must have already opened the stream, and is responsible for closing it after finishing compression.
size_t RE_SaveJPGToBuffer (byte *buffer, size_t bufSize, int quality, int image_width, int image_height, byte *image_buffer, int padding)
Encodes JPEG from image in image_buffer and writes to buffer. Expects RGB input data.
void RE_SaveJPG (const char *filename, int quality, int image_width, int image_height, byte *image_buffer, int padding)
RE_SaveJPG.
Typedef Documentation
typedef my_destination_mgr* my_dest_ptr
Definition at line 296 of file tr_image_jpg.c.
Function Documentation
static void __attribute__ ((noreturn)) static
R_JPGErrorExit.
Parameters
[in] cinfo
Definition at line 63 of file tr_image_jpg.c.
static boolean empty_output_buffer (j_compress_ptr cinfo) static
Empty the output buffer — Called whenever buffer fills up.
In typical applications, this should write the entire output buffer (ignoring the current state of next_output_byte & free_in_buffer), reset the pointer & count to the start of the buffer, and return TRUE indicating that the buffer has been dumped.
In applications that need to be able to suspend compression due to output overrun, a FALSE return indicates that the buffer cannot be emptied now. In this situation, the compressor will return to its caller (possibly with an indication that it has not accepted all the supplied scanlines). The application should resume compression after it has made more room in the output buffer. Note that there are substantial restrictions on the use of suspension — see the documentation.
When suspending, the compressor will back up to a convenient restart point (typically the start of the current MCU). next_output_byte & free_in_buffer indicate where the restart point will be if the current call returns FALSE. Data beyond this point will be regenerated after resumption, so do not write it out when emptying the buffer externally.
Parameters
[in] cinfo
Returns
Definition at line 337 of file tr_image_jpg.c.
Referenced by jpegDest().
static void init_destination (j_compress_ptr cinfo) static
Initialize destination — called by jpeg_start_compress before any data is actually written.
Parameters
[in] cinfo
Definition at line 303 of file tr_image_jpg.c.
Referenced by jpegDest().
static void jpegDest (j_compress_ptr cinfo, byte * outfile, int size) static
Prepare for output to a stdio stream. The caller must have already opened the stream, and is responsible for closing it after finishing compression.
Parameters
[in] cinfo
[in] outfile
[in] size
Definition at line 375 of file tr_image_jpg.c.
Referenced by RE_SaveJPGToBuffer().
static void R_JPGOutputMessage (j_common_ptr cinfo) static
R_JPGOutputMessage.
Parameters
[in] cinfo
Definition at line 82 of file tr_image_jpg.c.
Referenced by R_LoadJPG(), and RE_SaveJPGToBuffer().
void R_LoadJPG (const char * filename, unsigned char ** pic, int * width, int * height, byte alphaByte)
R_LoadJPG.
Parameters
[in] filename
[out] pic
[out] width
[out] height
alphaByte - unused
Definition at line 101 of file tr_image_jpg.c.
void RE_SaveJPG (const char * filename, int quality, int image_width, int image_height, byte * image_buffer, int padding)
RE_SaveJPG.
Parameters
[in] filename
[in] quality
[in] image_width
[in] image_height
[in] image_buffer
[in] padding
Definition at line 487 of file tr_image_jpg.c.
size_t RE_SaveJPGToBuffer (byte * buffer, size_t bufSize, int quality, int image_width, int image_height, byte * image_buffer, int padding)
Encodes JPEG from image in image_buffer and writes to buffer. Expects RGB input data.
Parameters
[out] buffer
[in] bufSize
[in] quality
[in] image_width
[in] image_height
[in] image_buffer
[in] padding
Returns
Definition at line 412 of file tr_image_jpg.c.
Referenced by RB_TakeVideoFrameCmd(), and RE_SaveJPG().
static void term_destination (j_compress_ptr cinfo) static
Terminate destination — called by jpeg_finish_compress after all data has been written. Usually needs to flush buffer.
NB: not called by jpeg_abort or jpeg_destroy; surrounding application must deal with any cleanup that should happen even for error exit.
Parameters
cinfo - unused
Note
Empty function
Definition at line 362 of file tr_image_jpg.c.
Referenced by jpegDest().