ET: Legacy: src/renderer/tr_flares.c File Reference
tr_flares.c File Reference
LIGHT FLARES.
#include "tr_local.h"
Data Structures
struct flare_s
Macros
#define MAX_FLARES 128
Typedefs
typedef struct flare_s flare_t
Flare states maintain visibility over multiple frames for fading layers: view, mirror, menu.
Functions
void R_ClearFlares (void)
R_ClearFlares.
void RB_AddFlare (void *surface, int fogNum, vec3_t point, vec3_t color, float scale, vec3_t normal, int id, qboolean visible)
This is called at surface tesselation time.
void RB_AddDlightFlares (void)
RB_AddDlightFlares.
void RB_AddCoronaFlares (void)
RB_AddCoronaFlares.
void RB_TestFlare (flare_t *f)
RB_TestFlare.
void RB_RenderFlare (flare_t *f)
RB_RenderFlare.
void RB_RenderFlares (void)
Because flares are simulating an occular effect, they should be drawn after everything (all views) in the entire frame has been drawn.
Variables
flare_t r_flareStructs [MAX_FLARES]
flare_t * r_activeFlares
flare_t * r_inactiveFlares
Detailed Description
LIGHT FLARES.
A light flare is an effect that takes place inside the eye when bright light sources are visible. The size of the flare reletive to the screen is nearly constant, irrespective of distance, but the intensity should be proportional to the projected area of the light source.
A surface that has been flagged as having a light flare will calculate the depth buffer value that it's midpoint should have when the surface is added.
After all opaque surfaces have been rendered, the depth buffer is read back for each flare in view. If the point has not been obscured by a closer surface, the flare should be drawn.
Surfaces that have a repeated texture should never be flagged as flaring, because there will only be a single flare added at the midpoint of the polygon.
To prevent abrupt popping, the intensity of the flare is interpolated up and down as it changes visibility. This involves scene to scene state, unlike almost all other aspects of the renderer, and is complicated by the fact that a single frame may have multiple scenes.
RB_RenderFlares() will be called once per view (twice in a mirrored scene, potentially up to five or more times in a frame with 3D status bar icons).
Definition in file tr_flares.c.
Macro Definition Documentation
#define MAX_FLARES 128
Definition at line 93 of file tr_flares.c.
Referenced by R_ClearFlares().
Typedef Documentation
flare_t
Flare states maintain visibility over multiple frames for fading layers: view, mirror, menu.
Function Documentation
void R_ClearFlares (void)
R_ClearFlares.
Definition at line 101 of file tr_flares.c.
Referenced by RE_BeginRegistration().
void RB_AddCoronaFlares (void)
RB_AddCoronaFlares.
Definition at line 274 of file tr_flares.c.
Referenced by RB_RenderFlares().
void RB_AddDlightFlares (void)
RB_AddDlightFlares.
Definition at line 230 of file tr_flares.c.
Referenced by RB_RenderFlares().
void RB_AddFlare (void * surface, int fogNum, vec3_t point, vec3_t color, float scale, vec3_t normal, int id, qboolean visible)
This is called at surface tesselation time.
Parameters
[in] surface
[in] fogNum
[in] point
[in] color
[in] scale
[in] normal
[in] id
[in] visible
Definition at line 127 of file tr_flares.c.
Referenced by RB_AddCoronaFlares(), RB_AddDlightFlares(), RB_AddLightFlares(), and Tess_SurfaceFlare().
void RB_RenderFlare (flare_t * f)
RB_RenderFlare.
Parameters
[in] f
Todo:
: use quadstamp?
Definition at line 391 of file tr_flares.c.
Referenced by RB_RenderFlares().
void RB_RenderFlares (void)
Because flares are simulating an occular effect, they should be drawn after everything (all views) in the entire frame has been drawn.
Because of the way portals use the depth buffer to mark off areas, the needed information would be lost after each view, so we are forced to draw flares after each view.
The resulting artifact is that flares in mirrors or portals don't dim properly when occluded by something in the main view, and portal flares that should extend past the portal edge will be overwritten.
Definition at line 480 of file tr_flares.c.
Referenced by RB_RenderDrawSurfList(), and RB_RenderViewFront().
void RB_TestFlare (flare_t * f)
RB_TestFlare.
Parameters
[in,out] f
Definition at line 328 of file tr_flares.c.
Referenced by RB_RenderFlares().
Variable Documentation
flare_t* r_activeFlares
Definition at line 96 of file tr_flares.c.
Referenced by RB_AddFlare(), and RB_RenderFlares().
flare_t r_flareStructs[MAX_FLARES]
Definition at line 95 of file tr_flares.c.
flare_t * r_inactiveFlares
Definition at line 96 of file tr_flares.c.
Referenced by R_ClearFlares(), RB_AddFlare(), and RB_RenderFlares().