ET: Legacy: src/renderer2/tr_animation.c File Reference
tr_animation.c File Reference
All bones should be an identity orientation to display the mesh exactly as it is specified.
#include "tr_local.h"
Functions
static skelAnimation_t * R_AllocAnimation (void)
R_AllocAnimation.
void R_InitAnimations (void)
R_InitAnimations.
static qboolean R_LoadMD5Anim (skelAnimation_t *skelAnim, byte *buffer, int bufferSize, const char *name)
R_LoadMD5Anim.
static void GetChunkHeader (memStream_t *s, axChunkHeader_t *chunkHeader)
GetChunkHeader.
static void PrintChunkHeader (axChunkHeader_t *chunkHeader)
PrintChunkHeader.
static void GetBone (memStream_t *s, axBone_t *bone)
GetBone.
static qboolean R_LoadPSA (skelAnimation_t *skelAnim, byte *buffer, int bufferSize, const char *name)
R_LoadPSA.
qhandle_t RE_RegisterAnimation (const char *name)
RE_RegisterAnimation.
skelAnimation_t * R_GetAnimationByHandle (qhandle_t hAnim)
R_GetAnimationByHandle.
void R_AnimationList_f (void)
R_AnimationList_f.
static void R_CullMD5 (trRefEntity_t *ent)
R_CullMD5.
void R_AddMD5Surfaces (trRefEntity_t *ent)
R_AddMD5Surfaces.
void R_AddMD5Interactions (trRefEntity_t *ent, trRefLight_t *light)
R_AddMD5Interactions.
int RE_CheckSkeleton (refSkeleton_t *skel, qhandle_t hModel, qhandle_t hAnim)
Check if the skeleton bones are the same in the model and animation and copy the parentIndex entries into the refSkeleton_t.
int RE_BuildSkeleton (refSkeleton_t *skel, qhandle_t hAnim, int startFrame, int endFrame, float frac, qboolean clearOrigin)
RE_BuildSkeleton.
int RE_BlendSkeleton (refSkeleton_t *skel, const refSkeleton_t *blend, float frac)
RE_BlendSkeleton.
int RE_AnimNumFrames (qhandle_t hAnim)
RE_AnimNumFrames.
int RE_AnimFrameRate (qhandle_t hAnim)
RE_AnimFrameRate.
Detailed Description
All bones should be an identity orientation to display the mesh exactly as it is specified.
For all other frames, the bones represent the transformation from the orientation of the bone in the base frame to the orientation in this frame.
Definition in file tr_animation.c.
Function Documentation
static void GetBone (memStream_t * s, axBone_t * bone) static
GetBone.
Parameters
[in] s
[out] bone
Definition at line 434 of file tr_animation.c.
Referenced by R_LoadPSA().
static void GetChunkHeader (memStream_t * s, axChunkHeader_t * chunkHeader) static
GetChunkHeader.
Parameters
[in] s
[out] chunkHeader
Definition at line 399 of file tr_animation.c.
Referenced by R_LoadPSA().
static void PrintChunkHeader (axChunkHeader_t * chunkHeader) static
PrintChunkHeader.
Parameters
chunkHeader - unused
Note
Disable
Definition at line 418 of file tr_animation.c.
Referenced by R_LoadPSA().
void R_AddMD5Interactions (trRefEntity_t * ent, trRefLight_t * light)
R_AddMD5Interactions.
Parameters
[in] ent
[in] light
Definition at line 1070 of file tr_animation.c.
Referenced by R_AddEntityInteractions().
void R_AddMD5Surfaces (trRefEntity_t * ent)
R_AddMD5Surfaces.
Parameters
[in] ent
Definition at line 940 of file tr_animation.c.
Referenced by R_AddEntitySurfaces().
static skelAnimation_t* R_AllocAnimation (void) static
R_AllocAnimation.
Returns
Definition at line 51 of file tr_animation.c.
Referenced by R_InitAnimations(), R_LoadPSA(), and RE_RegisterAnimation().
void R_AnimationList_f (void)
R_AnimationList_f.
Definition at line 868 of file tr_animation.c.
Referenced by R_Register().
static void R_CullMD5 (trRefEntity_t * ent) static
R_CullMD5.
Parameters
[in,out] ent
Todo:
: * ent->e.skeleton.scale
Todo:
: * ent->e.skeleton.scale
Definition at line 893 of file tr_animation.c.
Referenced by R_AddMD5Surfaces().
skelAnimation_t* R_GetAnimationByHandle (qhandle_t hAnim)
R_GetAnimationByHandle.
Parameters
[in] hAnim
Returns
Definition at line 850 of file tr_animation.c.
Referenced by RE_AnimFrameRate(), RE_AnimNumFrames(), RE_BuildSkeleton(), and RE_CheckSkeleton().
void R_InitAnimations (void)
R_InitAnimations.
Definition at line 71 of file tr_animation.c.
Referenced by R_Init().
static qboolean R_LoadMD5Anim (skelAnimation_t * skelAnim, byte * buffer, int bufferSize, const char * name) static
R_LoadMD5Anim.
Parameters
[out] skelAnim
[out] buffer
bufferSize - unused
[in] name
Returns
Definition at line 91 of file tr_animation.c.
Referenced by RE_RegisterAnimation().
static qboolean R_LoadPSA (skelAnimation_t * skelAnim, byte * buffer, int bufferSize, const char * name) static
R_LoadPSA.
Parameters
[in,out] skelAnim
[out] buffer
[in] bufferSize
[out] name
Returns
Definition at line 463 of file tr_animation.c.
Referenced by RE_RegisterAnimation().
int RE_AnimFrameRate (qhandle_t hAnim)
RE_AnimFrameRate.
Parameters
[in] hAnim
Returns
Todo:
Unused ?
Definition at line 1654 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_AnimNumFrames (qhandle_t hAnim)
RE_AnimNumFrames.
Parameters
[in] hAnim
Returns
Todo:
Unused ?
Definition at line 1628 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_BlendSkeleton (refSkeleton_t * skel, const refSkeleton_t * blend, float frac)
RE_BlendSkeleton.
Parameters
[in] skel
[in] blend
[in] frac
Returns
Definition at line 1586 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_BuildSkeleton (refSkeleton_t * skel, qhandle_t hAnim, int startFrame, int endFrame, float frac, qboolean clearOrigin)
RE_BuildSkeleton.
Parameters
[out] skel
[in] hAnim
[in] startFrame
[in] endFrame
[in] frac
[in] clearOrigin
Returns
Todo:
: clear existing bones and bounds?
Definition at line 1348 of file tr_animation.c.
Referenced by GetRefAPI().
int RE_CheckSkeleton (refSkeleton_t * skel, qhandle_t hModel, qhandle_t hAnim)
Check if the skeleton bones are the same in the model and animation and copy the parentIndex entries into the refSkeleton_t.
Parameters
[out] skel
[in] hModel
[in] hAnim
Returns
Definition at line 1254 of file tr_animation.c.
Referenced by GetRefAPI().
qhandle_t RE_RegisterAnimation (const char * name)
RE_RegisterAnimation.
Parameters
[in] name
Returns
Definition at line 749 of file tr_animation.c.
Referenced by GetRefAPI().