ET: Legacy: src/renderer2/tr_vbo.c File Reference
tr_vbo.c File Reference
#include "tr_local.h"
Macros
#define VERTEXSIZE(memb) (sizeof(verts->memb) / sizeof(verts->memb[0]))
#define VERTEXCOPY(memb)
Functions
VBO_t * R_CreateVBO (const char *name, byte *vertexes, int vertexesSize, vboUsage_t usage)
R_CreateVBO.
VBO_t * R_CreateVBO2 (const char *name, int numVertexes, srfVert_t *verts, unsigned int stateBits, vboUsage_t usage)
R_CreateVBO2.
IBO_t * R_CreateIBO (const char *name, byte *indexes, int indexesSize, vboUsage_t usage)
R_CreateIBO.
IBO_t * R_CreateIBO2 (const char *name, int numTriangles, srfTriangle_t *triangles, vboUsage_t usage)
R_CreateIBO2.
void R_BindVBO (VBO_t *vbo)
R_BindVBO.
void R_BindNullVBO (void)
R_BindNullVBO.
void R_BindIBO (IBO_t *ibo)
R_BindIBO.
void R_BindNullIBO (void)
R_BindNullIBO.
static void R_InitUnitCubeVBO ()
R_InitUnitCubeVBO.
void R_InitVBOs (void)
R_InitVBOs.
void R_ShutdownVBOs (void)
R_ShutdownVBOs.
void R_VBOList_f (void)
R_VBOList_f.
Macro Definition Documentation
#define VERTEXCOPY (memb)
Value:
do { \
        vec_t *tmp = (vec_t *) (data + dataOfs); \
        for (i = 0; i < numVertexes; i++) \
        { \
            for (j = 0; j < VERTEXSIZE(memb); j++) { *tmp++ = verts[i].memb[j]; } \
            if (VERTEXSIZE(memb) < 3) { *tmp++ = 0; } \
            if (VERTEXSIZE(memb) < 4) { *tmp++ = 1; } \
        } \
        dataOfs += i * sizeof(vec4_t); \
    } while (0)
Referenced by R_CreateVBO2().
#define VERTEXSIZE (memb) (sizeof(verts->memb) / sizeof(verts->memb[0]))
Function Documentation
void R_BindIBO (IBO_t * ibo)
R_BindIBO.
Parameters
[in] ibo
Definition at line 463 of file tr_vbo.c.
Referenced by IssueMultiOcclusionQueries(), IssueOcclusionQuery(), R_inPVS(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_CheckOverflow(), Tess_StageIteratorSky(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFace(), Tess_SurfaceFlare(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), Tess_SurfaceTriangles(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), Tess_SurfaceVBOMesh(), Tess_UpdateVBOs(), and TraverseNode().
void R_BindNullIBO (void)
R_BindNullIBO.
Definition at line 487 of file tr_vbo.c.
Referenced by R_InitVBOs(), R_inPVS(), R_ShutdownVBOs(), RB_PostProcess(), RE_EndFrame(), RE_LoadWorldMap(), and RE_RegisterModel().
void R_BindNullVBO (void)
R_BindNullVBO.
Definition at line 446 of file tr_vbo.c.
Referenced by R_InitVBOs(), R_ShutdownVBOs(), RB_PostProcess(), RE_EndFrame(), RE_LoadWorldMap(), and RE_RegisterModel().
void R_BindVBO (VBO_t * vbo)
R_BindVBO.
Parameters
[in] vbo
Definition at line 415 of file tr_vbo.c.
Referenced by IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_CheckOverflow(), Tess_StageIteratorSky(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFace(), Tess_SurfaceFlare(), Tess_SurfaceFoliage(), Tess_SurfaceGrid(), Tess_SurfaceTriangles(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), Tess_SurfaceVBOMesh(), Tess_UpdateVBOs(), and TraverseNode().
IBO_t* R_CreateIBO (const char * name, byte * indexes, int indexesSize, vboUsage_t usage)
R_CreateIBO.
Parameters
[in] name
[in] indexes
[in] indexesSize
[in] usage
Returns
Definition at line 281 of file tr_vbo.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), and R_InitVBOs().
IBO_t* R_CreateIBO2 (const char * name, int numTriangles, srfTriangle_t * triangles, vboUsage_t usage)
R_CreateIBO2.
Parameters
[in] name
[in] numTriangles
[in] triangles
[in] usage
Returns
Definition at line 335 of file tr_vbo.c.
Referenced by R_CreateSubModelVBOs(), R_CreateVBOLightMeshes(), R_CreateVBOShadowCubeMeshes(), R_CreateVBOShadowMeshes(), R_CreateWorldVBO(), R_InitUnitCubeVBO(), R_LoadNodesAndLeafs(), R_MD3_CreateVBO_Surfaces(), R_MDC_CreateVBO_Surfaces(), and R_SetupLightFrustum().
VBO_t* R_CreateVBO (const char * name, byte * vertexes, int vertexesSize, vboUsage_t usage)
R_CreateVBO.
Parameters
[in] name
[in] vertexes
[in] vertexesSize
[in] usage
Returns
Definition at line 46 of file tr_vbo.c.
Referenced by AddSurfaceToVBOSurfacesList(), AddSurfaceToVBOSurfacesList2(), AddSurfaceToVBOSurfacesListMDM(), R_InitVBOs(), R_MD3_CreateVBO_Surfaces(), and R_MDC_CreateVBO_Surfaces().
VBO_t* R_CreateVBO2 (const char * name, int numVertexes, srfVert_t * verts, unsigned int stateBits, vboUsage_t usage)
R_CreateVBO2.
Parameters
[in] name
[in] numVertexes
[in] verts
[in] stateBits
[in] usage
Returns
Definition at line 118 of file tr_vbo.c.
Referenced by R_InitUnitCubeVBO().
static void R_InitUnitCubeVBO () static
R_InitUnitCubeVBO.
Definition at line 502 of file tr_vbo.c.
Referenced by R_InitVBOs().
void R_InitVBOs (void)
R_InitVBOs.
Definition at line 550 of file tr_vbo.c.
Referenced by R_Init().
void R_ShutdownVBOs (void)
R_ShutdownVBOs.
Definition at line 598 of file tr_vbo.c.
Referenced by RE_Shutdown().
void R_VBOList_f (void)
R_VBOList_f.
Definition at line 664 of file tr_vbo.c.
Referenced by R_Register().