ET: Legacy: src/renderer/tr_shade.c File Reference
tr_shade.c File Reference
This file deals with applying shaders to surface data in the tess struct.
#include "tr_local.h"
Functions
static void GLAPIENTRY R_ArrayElementDiscrete (GLint index)
R_ArrayElementDiscrete.
static void GLAPIENTRY R_ArrayElement (GLint index)
This is just because of the GLEW and Windows idiocy. Straight call to glArrayElement brakes the build on function type mismatch.
static void R_DrawStripElements (int numIndexes, const glIndex_t *indexes, void(GLAPIENTRY *element)(GLint))
R_DrawStripElements.
static void R_DrawElements (int numIndexes, const glIndex_t *indexes)
Optionally performs our own glDrawElements that looks for strip conditions instead of using the single glDrawElements call that may be inefficient without compiled vertex arrays.
static void R_BindAnimatedImage (textureBundle_t *bundle)
R_BindAnimatedImage.
static void DrawTris (shaderCommands_t *input)
Draws triangle outlines for debugging.
static void DrawNormals (shaderCommands_t *input)
Draws vertex normals for debugging.
void RB_BeginSurface (shader_t *shader, int fogNum)
We must set some things up before beginning any tesselation, because a surface may be forced to perform a RB_End due to overflow.
static void DrawMultitextured (shaderCommands_t *input, int stage)
DrawMultitextured.
static void DynamicLightSinglePass (void)
Perform all dynamic lighting with a single rendering pass.
static void DynamicLightPass_scalar (void)
DynamicLightPass_scalar.
static void DynamicLightPass (void)
DynamicLightPass.
static void RB_FogPass (void)
Blends a fog texture on top of everything else.
static void ComputeColors (shaderStage_t *pStage)
ComputeColors.
static void ComputeTexCoords (shaderStage_t *pStage)
ComputeTexCoords.
void R_Fog (glfog_t *curfog)
R_Fog.
void SetIteratorFog (void)
Set the fog parameters for this pass.
static void RB_IterateStagesGeneric (shaderCommands_t *input)
RB_IterateStagesGeneric.
void RB_StageIteratorGeneric (void)
RB_StageIteratorGeneric.
void RB_StageIteratorVertexLitTexture (void)
RB_StageIteratorVertexLitTexture.
void RB_StageIteratorLightmappedMultitexture (void)
RB_StageIteratorLightmappedMultitexture.
void RB_EndSurface (void)
RB_EndSurface.
Variables
static int c_vertexes
static int c_begins
shaderCommands_t tess
static qboolean setArraysOnce
Detailed Description
This file deals with applying shaders to surface data in the tess struct.
Note
THIS ENTIRE FILE IS BACK END
Definition in file tr_shade.c.
Function Documentation
static void ComputeColors (shaderStage_t * pStage) static
ComputeColors.
Parameters
[in] pStage
Definition at line 1097 of file tr_shade.c.
Referenced by RB_IterateStagesGeneric().
static void ComputeTexCoords (shaderStage_t * pStage) static
ComputeTexCoords.
Parameters
[in] pStage
Definition at line 1406 of file tr_shade.c.
Referenced by RB_IterateStagesGeneric().
static void DrawMultitextured (shaderCommands_t * input, int stage) static
DrawMultitextured.
Parameters
[in] input
[in] stage
Note
output = t0 * t1 or t0 + t1
t0 = most upstream according to spec t1 = most downstream according to spec
Definition at line 490 of file tr_shade.c.
Referenced by RB_IterateStagesGeneric().
static void DrawNormals (shaderCommands_t * input) static
Draws vertex normals for debugging.
Parameters
[in] input
Definition at line 384 of file tr_shade.c.
Referenced by RB_EndSurface().
static void DrawTris (shaderCommands_t * input) static
Draws triangle outlines for debugging.
Parameters
[in] input
Definition at line 274 of file tr_shade.c.
Referenced by RB_EndSurface().
static void DynamicLightPass (void) static
DynamicLightPass.
Definition at line 1031 of file tr_shade.c.
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void DynamicLightPass_scalar (void) static
DynamicLightPass_scalar.
Definition at line 881 of file tr_shade.c.
Referenced by DynamicLightPass().
static void DynamicLightSinglePass (void) static
Perform all dynamic lighting with a single rendering pass.
Definition at line 551 of file tr_shade.c.
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void GLAPIENTRY R_ArrayElement (GLint index) static
This is just because of the GLEW and Windows idiocy. Straight call to glArrayElement brakes the build on function type mismatch.
Parameters
[in] index
Definition at line 66 of file tr_shade.c.
Referenced by R_DrawElements().
static void GLAPIENTRY R_ArrayElementDiscrete (GLint index) static
R_ArrayElementDiscrete.
Parameters
[in] index
Definition at line 47 of file tr_shade.c.
Referenced by R_DrawElements().
static void R_BindAnimatedImage (textureBundle_t * bundle) static
R_BindAnimatedImage.
Parameters
[in] bundle
Definition at line 224 of file tr_shade.c.
Referenced by DrawMultitextured(), RB_IterateStagesGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void R_DrawElements (int numIndexes, const glIndex_t * indexes) static
Optionally performs our own glDrawElements that looks for strip conditions instead of using the single glDrawElements call that may be inefficient without compiled vertex arrays.
Parameters
[in] numIndexes
[in] indexes
Definition at line 182 of file tr_shade.c.
Referenced by DrawMultitextured(), DrawTris(), DynamicLightPass_scalar(), DynamicLightSinglePass(), RB_FogPass(), RB_IterateStagesGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void R_DrawStripElements (int numIndexes, const glIndex_t * indexes, void(GLAPIENTRY *element)(GLint)) static
R_DrawStripElements.
Parameters
[in] numIndexes
[in] indexes
Definition at line 79 of file tr_shade.c.
Referenced by R_DrawElements().
void R_Fog (glfog_t * curfog)
R_Fog.
Parameters
[in] curfog
Definition at line 68 of file tr_main.c.
Referenced by ComputeTexCoords(), and SetIteratorFog().
void RB_BeginSurface (shader_t * shader, int fogNum)
We must set some things up before beginning any tesselation, because a surface may be forced to perform a RB_End due to overflow.
Parameters
[in] shader
[in] fogNum
Definition at line 460 of file tr_shade.c.
void RB_EndSurface (void)
RB_EndSurface.
Definition at line 1967 of file tr_shade.c.
static void RB_FogPass (void) static
Blends a fog texture on top of everything else.
Definition at line 1047 of file tr_shade.c.
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void RB_IterateStagesGeneric (shaderCommands_t * input) static
RB_IterateStagesGeneric.
Parameters
[in] input
Definition at line 1566 of file tr_shade.c.
Referenced by RB_StageIteratorGeneric().
void RB_StageIteratorGeneric (void)
RB_StageIteratorGeneric.
Definition at line 1689 of file tr_shade.c.
void RB_StageIteratorLightmappedMultitexture (void)
RB_StageIteratorLightmappedMultitexture.
Definition at line 1858 of file tr_shade.c.
void RB_StageIteratorVertexLitTexture (void)
RB_StageIteratorVertexLitTexture.
Definition at line 1789 of file tr_shade.c.
void SetIteratorFog (void)
Set the fog parameters for this pass.
Definition at line 1514 of file tr_shade.c.
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
Variable Documentation
int c_begins static
Definition at line 72 of file tr_shade.c.
Referenced by R_DrawStripElements().
int c_vertexes static
Definition at line 71 of file tr_shade.c.
Referenced by R_DrawStripElements().
qboolean setArraysOnce static
Definition at line 218 of file tr_shade.c.
shaderCommands_t tess
Definition at line 217 of file tr_shade.c.
Referenced by R_ArrayElementDiscrete(), R_DrawStripElements(), RB_EndSurface(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorVertexLitTexture(), and Tess_DrawElements().