ET: Legacy: src/renderer/tr_backend.c File Reference
tr_backend.c File Reference
#include "tr_local.h"
Functions
void GL_Bind (image_t *image)
GL_Bind.
void GL_SelectTexture (int unit)
GL_SelectTexture.
void GL_Cull (int cullType)
GL_Cull.
void GL_TexEnv (int env)
GL_TexEnv.
void GL_State (unsigned long stateBits)
This routine is responsible for setting the most commonly changed state in Q3.
static void RB_Hyperspace (void)
A player has predicted a teleport, but hasn't arrived yet.
static void SetViewportAndScissor (void)
SetViewportAndScissor.
void RB_BeginDrawingView (void)
Any mirrored or portaled views have already been drawn, so prepare to actually render the visible surfaces for this view.
void RB_RenderDrawSurfList (drawSurf_t *drawSurfs, int numDrawSurfs)
RB_RenderDrawSurfList.
void RB_SetGL2D (void)
RB_SetGL2D.
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
RE_UploadCinematic.
const void * RB_SetColor (const void *data)
RB_SetColor.
const void * RB_StretchPic (const void *data)
RB_StretchPic.
const void * RB_Draw2dPolys (const void *data)
RB_Draw2dPolys.
const void * RB_RotatedPic (const void *data)
RB_RotatedPic.
const void * RB_StretchPicGradient (const void *data)
RB_StretchPicGradient.
const void * RB_DrawSurfs (const void *data)
RB_DrawSurfs.
const void * RB_DrawBuffer (const void *data)
RB_DrawBuffer.
void RB_GammaScreen (void)
RB_GammaScreen.
void RB_ShowImages (void)
Draw all the images to the screen, on top of whatever was there. This is used to test for texture thrashing.
const void * RB_SwapBuffers (const void *data)
RB_SwapBuffers.
const void * RB_RenderToTexture (const void *data)
RB_RenderToTexture.
const void * RB_Finish (const void *data)
RB_Finish.
void RB_ExecuteRenderCommands (const void *data)
RB_ExecuteRenderCommands.
Variables
backEndData_t * backEndData
the second one may not be allocated
backEndState_t backEnd
static float s_flipMatrix [16]
Convert from our coordinate system (looking down X) to OpenGL's coordinate system (looking down -Z)
Function Documentation
void GL_Bind (image_t * image)
GL_Bind.
Parameters
[in,out] image
Definition at line 57 of file tr_backend.c.
Referenced by BindCubeMaps(), BindLightMap(), BindTexture(), DrawNormals(), DrawSkySide(), DrawSkySideInner(), DrawTris(), DynamicLightPass(), DynamicLightPass_scalar(), DynamicLightSinglePass(), GL_BindNearestCubeMap(), GL_TextureMode(), R_BindAnimatedImage(), R_BuildCubeMaps(), R_CoherentHierachicalCulling(), R_CreateCubeImage(), R_CreateImage(), R_DebugGraphics(), R_ImageCopyBack(), R_LoadDDSImageData(), R_LoadLightmapsExternal(), R_ScreenGamma(), RB_CameraPostFX(), RB_FogPass(), RB_MDM_SurfaceAnim(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderToTexture(), RB_SafeState(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_ShowImages(), RB_StageIteratorLightmappedMultitexture(), RB_SurfaceAnim(), RB_SurfaceAxis(), RB_SurfaceBeam(), RE_StretchRaw(), RE_UploadCinematic(), Render_lightVolume(), Tess_MDM_SurfaceAnim(), and Tess_SurfaceBeam().
void GL_Cull (int cullType)
GL_Cull.
Parameters
[in] cullType
Definition at line 160 of file tr_backend.c.
Referenced by DrawSkySide(), R_CoherentHierachicalCulling(), R_DebugGraphics(), RB_CameraPostFX(), RB_IterateStagesGeneric(), RB_PostProcess(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_SetGL2D(), RB_ShowImages(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), Render_lightVolume(), and Tess_StageIteratorSky().
void GL_SelectTexture (int unit)
GL_SelectTexture.
Parameters
[in] unit
Definition at line 92 of file tr_backend.c.
Referenced by DrawMultitextured(), DrawSkySide(), DrawSkySideInner(), GL_SetDefaultState(), GLSL_SelectTexture(), R_BackupImages(), R_CreateImage(), R_DebugGraphics(), R_DeleteTextures(), R_PurgeImage(), RB_RenderViewFront(), RB_SafeState(), and RB_StageIteratorLightmappedMultitexture().
void GL_State (unsigned long stateBits)
This routine is responsible for setting the most commonly changed state in Q3.
Parameters
[in] stateBits
Definition at line 225 of file tr_backend.c.
Referenced by DrawMultitextured(), DrawNormals(), DrawSkyBox(), DrawTris(), DynamicLightPass(), DynamicLightPass_scalar(), DynamicLightSinglePass(), R_CoherentHierachicalCulling(), R_DebugPolygon(), RB_BeginDrawingView(), RB_CameraPostFX(), RB_FogPass(), RB_IterateStagesGeneric(), RB_MDM_SurfaceAnim(), RB_PostProcess(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_RenderViewFront(), RB_SafeState(), RB_SetGL2D(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), RB_SurfaceAxis(), RB_SurfaceBeam(), Render_lightVolume(), Tess_MDM_SurfaceAnim(), and Tess_SurfaceBeam().
void GL_TexEnv (int env)
GL_TexEnv.
Parameters
[in] env
Definition at line 192 of file tr_backend.c.
Referenced by DrawMultitextured(), DrawSkySideInner(), GL_SetDefaultState(), and RB_StageIteratorLightmappedMultitexture().
void RB_BeginDrawingView (void)
Any mirrored or portaled views have already been drawn, so prepare to actually render the visible surfaces for this view.
Definition at line 429 of file tr_backend.c.
Referenced by RB_RenderDrawSurfList().
const void* RB_Draw2dPolys (const void * data)
RB_Draw2dPolys.
Parameters
[in] data
Returns
Definition at line 1049 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
const void* RB_DrawBuffer (const void * data)
RB_DrawBuffer.
Parameters
[in] data
Returns
Definition at line 1290 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
const void* RB_DrawSurfs (const void * data)
RB_DrawSurfs.
Parameters
[in] data
Returns
Definition at line 1265 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
void RB_ExecuteRenderCommands (const void * data)
RB_ExecuteRenderCommands.
Parameters
[in] data
Definition at line 1526 of file tr_backend.c.
Referenced by R_IssueRenderCommands().
const void* RB_Finish (const void * data)
RB_Finish.
Parameters
[in] data
Returns
Definition at line 1511 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
void RB_GammaScreen (void)
RB_GammaScreen.
Definition at line 1309 of file tr_backend.c.
Referenced by RB_SwapBuffers().
static void RB_Hyperspace (void) static
A player has predicted a teleport, but hasn't arrived yet.
Definition at line 399 of file tr_backend.c.
Referenced by RB_BeginDrawingView().
void RB_RenderDrawSurfList (drawSurf_t * drawSurfs, int numDrawSurfs)
RB_RenderDrawSurfList.
Parameters
[in] drawSurfs
[in] numDrawSurfs
Todo:
: e.shaderTime must be passed as int to avoid fp-precision loss issues
Definition at line 632 of file tr_backend.c.
Referenced by RB_DrawSurfs().
const void* RB_RenderToTexture (const void * data)
RB_RenderToTexture.
Parameters
[in] data
Returns
Definition at line 1490 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
const void* RB_RotatedPic (const void * data)
RB_RotatedPic.
Parameters
[in] data
Returns
Definition at line 1105 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
const void* RB_SetColor (const void * data)
RB_SetColor.
Parameters
[in] data
Returns
Definition at line 955 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
void RB_SetGL2D (void)
RB_SetGL2D.
Definition at line 791 of file tr_backend.c.
Referenced by RB_Draw2dPolys(), RB_GammaScreen(), RB_PostProcess(), RB_RotatedPic(), RB_ShowImages(), RB_StretchPic(), RB_StretchPicGradient(), and RE_StretchRaw().
void RB_ShowImages (void)
Draw all the images to the screen, on top of whatever was there. This is used to test for texture thrashing.
Also called by RE_EndRegistration
Definition at line 1322 of file tr_backend.c.
Referenced by RB_PostProcess(), and RB_SwapBuffers().
const void* RB_StretchPic (const void * data)
RB_StretchPic.
Parameters
[in] data
Returns
Definition at line 972 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
const void* RB_StretchPicGradient (const void * data)
RB_StretchPicGradient.
Parameters
[in] data
Returns
Definition at line 1187 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
const void* RB_SwapBuffers (const void * data)
RB_SwapBuffers.
Parameters
[in] data
Returns
Definition at line 1431 of file tr_backend.c.
Referenced by RB_ExecuteRenderCommands().
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
Stretches a raw 32 bit power of 2 bitmap image over the given screen rectangle. Used for cinematics.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Todo:
FIXME: not exactly backend
Definition at line 832 of file tr_backend.c.
Referenced by GetRefAPI().
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
RE_UploadCinematic.
Parameters
w - unused
h - unused
[in] cols
[in] rows
[in] data
[in] client
[in] dirty
Definition at line 924 of file tr_backend.c.
Referenced by GetRefAPI(), and RE_StretchRaw().
static void SetViewportAndScissor (void) static
SetViewportAndScissor.
Definition at line 412 of file tr_backend.c.
Referenced by RB_BeginDrawingView().
Variable Documentation
backEndState_t backEnd
Definition at line 38 of file tr_backend.c.
Referenced by Autosprite2Deform(), AutospriteDeform(), BindCubeMaps(), clipPortalPlane(), ComputeColors(), ComputeTexCoords(), DoRailCore(), DoRailDiscs(), DrawMultitextured(), DrawNormals(), DrawSkySide(), DrawSkySideInner(), DrawTris(), DynamicLightPass(), DynamicLightPass_scalar(), DynamicLightSinglePass(), FillCloudySkySide(), GetOpValue(), GL_Cull(), GlobalVectorToLocal(), GLSL_BindProgram(), LerpCMeshVertexes(), LerpMeshVertexes(), LerpMeshVertexes_scalar(), LodErrorForVolume(), MakeSkyVec(), R_BindAnimatedImage(), R_BindIBO(), R_BindVBO(), R_FogOn(), R_Init(), R_InitSkyTexCoords(), R_PerformanceCounters(), RB_AddCoronaFlares(), RB_AddDlightFlares(), RB_AddFlare(), RB_AddLightFlares(), RB_AddQuadStampExt(), RB_BeginSurface(), RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcBulgeVertexes(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDeformVertexes(), RB_CalcDiffuseColor(), RB_CalcEnvironmentTexCoords(), RB_CalcFireRiseEnvTexCoords(), RB_CalcFogTexCoords(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_CalcSpecularAlpha(), RB_CalcTexMatrix(), RB_ClipSkyPolygons(), RB_DeformTessGeometry(), RB_DrawSun(), RB_EndSurface(), RB_FogOn(), RB_FogPass(), RB_IterateStagesGeneric(), RB_MDM_SurfaceAnim(), RB_ProjectionShadowDeform(), RB_ProjectRadius(), RB_RenderFlare(), RB_RenderFlares(), RB_ShadowTessEnd(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_SurfaceAnim(), RB_SurfaceBad(), RB_SurfaceBeam(), RB_SurfaceCMesh(), RB_SurfaceEntity(), RB_SurfaceFoliage(), RB_SurfaceLightningBolt(), RB_SurfaceMesh(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RB_SurfaceSplash(), RB_SurfaceSprite(), RB_TestFlare(), RE_EndFrame(), SetIteratorFog(), Tess_AddQuadStampExt(), Tess_AddQuadStampExt2(), Tess_Begin(), Tess_ClipSkyPolygons(), Tess_DeformGeometry(), Tess_DoRailCore(), Tess_DoRailDiscs(), Tess_DrawElements(), Tess_MDM_SurfaceAnim(), Tess_StageIteratorSky(), Tess_SurfaceAxis(), Tess_SurfaceBeam(), Tess_SurfaceEntity(), Tess_SurfaceFlare(), Tess_SurfaceFoliage(), Tess_SurfaceLightningBolt(), Tess_SurfaceMD5(), Tess_SurfaceMDV(), Tess_SurfaceRailCore(), Tess_SurfaceRailRings(), Tess_SurfaceSplash(), Tess_SurfaceSprite(), Tess_SurfaceVBOMD5Mesh(), Tess_SurfaceVBOMDMMesh(), Tess_SurfaceVBOMDVMesh(), and Tess_UpdateVBOs().
backEndData_t* backEndData
the second one may not be allocated
Definition at line 37 of file tr_backend.c.
Referenced by FixRenderCommandList(), R_AddPolysToScene(), R_AddWorldLightsToScene(), R_GetCommandBuffer(), R_Init(), R_InitNextFrame(), R_IssueRenderCommands(), RE_2DPolyies(), RE_AddCoronaToScene(), RE_AddDynamicLightToScene(), RE_AddLightToScene(), RE_AddPolyBufferToScene(), RE_AddPolysToScene(), RE_AddPolyToScene(), RE_AddRefEntityToScene(), RE_EndFrame(), RE_ProjectDecal(), and RE_RenderScene().
s_flipMatrix static
Initial value:
=
{
    0,  0, -1, 0,
    -1, 0, 0,  0,
    0,  1, 0,  0,
    0,  0, 0,  1
}
Convert from our coordinate system (looking down X) to OpenGL's coordinate system (looking down -Z)
Definition at line 45 of file tr_backend.c.
Referenced by RB_BeginDrawingView().