ET: Legacy: src/renderer2/tr_glsl.c File Reference
tr_glsl.c File Reference
#include "tr_local.h"
#include <shaders.h>
#include "tr_glsldef.h"
Data Structures
struct attrmap
struct GLShaderHeader_s
Macros
#define MACRO_NAME
#define UNIFORM_TYPE
#define ATTR_MAP
#define TEX_MAP
#define FILE_HASH_SIZE 4096
#define MAX_SHADER_DEF_FILES 1024
#define DEFAULT_SHADER_DEF NULL
#define GL_SHADER_VERSION 3
#define BUFFEXT(...) Q_strcat(shaderExtraDef, sizeof(shaderExtraDef), va(__VA_ARGS__))
#define GLSL_BUFF 64000
#define GLSL_BUFF_CHAR (sizeof(char) *GLSL_BUFF)
Typedefs
typedef struct GLShaderHeader_s GLShaderHeader_t
Functions
int GLSL_GetMacroByName (const char *name)
GLSL_GetMacroByName.
unsigned int GLSL_GetAttribByName (const char *name)
GLSL_GetAttribByName.
void GLSL_CopyStringAlloc (char **out, const char *in)
GLSL_CopyStringAlloc.
qboolean GLSL_CopyNextToken (char **text, char **out)
GLSL_CopyNextToken.
programInfo_t * GLSL_ParseDefinition (char **text, const char *defname)
GLSL_ParseDefinition.
static char * GLSL_FindDefinitionInText (const char *shadername)
GLSL_FindDefinitionInText.
programInfo_t * GLSL_FindShader (const char *name)
GLSL_FindShader.
void GLSL_LoadDefinitions (void)
GLSL_LoadDefinitions.
static void GLSL_PrintInfoLog (GLhandleARB object, qboolean developerOnly, qboolean isProgram)
GLSL_PrintInfoLog.
qboolean GLSL_LoadShaderBinary (programInfo_t *info, size_t programNum)
GLSL_LoadShaderBinary.
void GLSL_SaveShaderBinary (programInfo_t *info, size_t programNum)
GLSL_SaveShaderBinary.
static qboolean GLSL_HasConflictingMacros (int compilemacro, int usedmacros)
GLSL_HasConflictingMacros.
static qboolean GLSL_MissesRequiredMacros (int compilemacro, int usedmacros)
GLSL_MissesRequiredMacros.
static unsigned int GLSL_GetRequiredVertexAttributes (int compilemacro)
GLSL_GetRequiredVertexAttributes.
static void GLSL_BuildShaderExtraDef ()
GLSL_BuildShaderExtraDef.
static void GLSL_GetShaderHeader (GLenum shaderType, char *dest, size_t size)
GLSL_GetShaderHeader.
static int GLSL_CompileGPUShader (GLhandleARB program, GLhandleARB *prevShader, const GLcharARB *buffer, int size, GLenum shaderType, const char *name)
GLSL_CompileGPUShader.
static void GLSL_GetShaderText (const char *name, GLenum shaderType, char **data, size_t *size, qboolean append)
GLSL_GetShaderText loads shader text into data buffer.
static void GLSL_PreprocessShaderText (char *shaderBuffer, char *filetext, GLenum shadertype)
GLSL_PreprocessShaderText.
static char * GLSL_BuildGPUShaderText (programInfo_t *info, GLenum shadertype)
GLSL_BuildGPUShaderText.
static qboolean GLSL_GenerateMacroString (shaderProgramList_t *program, const char *macros, int permutation, char **out)
GLSL_GenerateMacroString.
static void GLSL_LinkProgram (GLhandleARB program)
GLSL_LinkProgram.
static void GLSL_ValidateProgram (GLhandleARB program)
GLSL_ValidateProgram.
static void GLSL_ShowProgramUniforms (GLhandleARB program)
GLSL_ShowProgramUniforms.
void GLSL_InitUniforms (shaderProgram_t *program)
GLSL_InitUniforms.
void GLSL_FinishGPUShader (shaderProgram_t *program)
GLSL_FinishGPUShader.
void GLSL_SelectTexture (shaderProgram_t *program, texture_def_t tex)
GLSL_SelectTexture.
void GLSL_SetUniformBoolean (shaderProgram_t *program, int uniformNum, GLboolean value)
GLSL_SetUniformBoolean.
void GLSL_SetUniformInt (shaderProgram_t *program, int uniformNum, GLint value)
GLSL_SetUniformInt.
void GLSL_SetUniformFloat (shaderProgram_t *program, int uniformNum, GLfloat value)
GLSL_SetUniformFloat.
void GLSL_SetUniformDouble (shaderProgram_t *program, int uniformNum, GLdouble value)
GLSL_SetUniformDouble.
void GLSL_SetUniformVec2 (shaderProgram_t *program, int uniformNum, const vec2_t v)
GLSL_SetUniformVec2.
void GLSL_SetUniformVec3 (shaderProgram_t *program, int uniformNum, const vec3_t v)
GLSL_SetUniformVec3.
void GLSL_SetUniformVec4 (shaderProgram_t *program, int uniformNum, const vec4_t v)
GLSL_SetUniformVec4.
void GLSL_SetUniformFloat5 (shaderProgram_t *program, int uniformNum, const vec5_t v)
GLSL_SetUniformFloat5.
void GLSL_SetUniformMatrix16 (shaderProgram_t *program, int uniformNum, const mat4_t matrix)
GLSL_SetUniformMatrix16.
void GLSL_SetUniformFloatARR (shaderProgram_t *program, int uniformNum, float *floatarray, int arraysize)
GLSL_SetUniformFloatARR.
void GLSL_SetUniformVec4ARR (shaderProgram_t *program, int uniformNum, vec4_t *vectorarray, int arraysize)
GLSL_SetUniformVec4ARR.
void GLSL_SetUniformMatrix16ARR (shaderProgram_t *program, int uniformNum, mat4_t *matrixarray, int arraysize)
GLSL_SetUniformMatrix16ARR.
static void GLSL_BindAttribLocations (GLuint program)
GLSL_BindAttribLocations.
static qboolean GLSL_InitGPUShader2 (shaderProgram_t *program, const char *name, const char *vpCode, const char *fpCode)
GLSL_InitGPUShader2.
static qboolean GLSL_FinnishShaderTextAndCompile (programInfo_t *info, int permutation, const char *vertex, const char *frag, const char *macrostring)
GLSL_FinnishShaderTextAndCompile.
static qboolean GLSL_GetProgramPermutation (programInfo_t *info, int permutation, const char *vertex, const char *frag, const char *macrostring)
GLSL_GetProgramPermutation.
static void GLSL_SetTextureUnitBindings (programInfo_t *info, int permutation)
GLSL_SetTextureUnitBindings.
static void GLSL_SetInitialUniformValues (programInfo_t *info, int permutation)
GLSL_SetInitialUniformValues.
void GLSL_GenerateCheckSum (programInfo_t *info, const char *vertex, const char *fragment)
GLSL_GenerateCheckSum.
static qboolean GLSL_CompilePermutation (programInfo_t *info, int offset)
GLSL_CompilePermutation.
qboolean GLSL_CompileShaderProgram (programInfo_t *info)
GLSL_CompileShaderProgram.
programInfo_t * GLSL_GetShaderProgram (const char *name)
GLSL_GetShaderProgram.
void GLSL_SetMacroStatesByOffset (programInfo_t *programlist, int offset)
GLSL_SetMacroStatesByOffset.
void GLSL_SetMacroState (programInfo_t *programlist, int macro, int enabled)
GLSL_SetMacroState.
void GLSL_SetMacroStates (programInfo_t *programlist, int numMacros,...)
GLSL_SetMacroStates.
void GLSL_SelectPermutation (programInfo_t *programlist)
GLSL_SelectPermutation.
void GLSL_SetRequiredVertexPointers (programInfo_t *programlist)
GLSL_SetRequiredVertexPointers.
void GLSL_DeleteGPUShader (shaderProgram_t *program)
GLSL_DeleteGPUShader.
void GLSL_DeleteShaderProgramList (shaderProgramList_t *programlist)
GLSL_DeleteShaderProgramList.
void GLSL_DeleteShaderProgramInfo (programInfo_t *program)
GLSL_DeleteShaderProgramInfo.
void GLSL_InitGPUShaders (void)
GLSL_InitGPUShaders.
void GLSL_CompileGPUShaders (void)
GLSL_CompileGPUShaders.
void GLSL_ShutdownGPUShaders (void)
GLSL_ShutdownGPUShaders.
void GLSL_BindProgram (shaderProgram_t *program)
GLSL_BindProgram.
void GLSL_BindNullProgram (void)
GLSL_BindNullProgram.
void GLSL_SetUniform_DeformParms (deformStage_t deforms[], int numDeforms)
GLSL_SetUniform_DeformParms.
void GLSL_SetUniform_ColorModulate (programInfo_t *prog, int colorGen, int alphaGen)
GLSL_SetUniform_ColorModulate.
void GLSL_SetUniform_AlphaTest (uint32_t stateBits)
GLSL_SetUniform_AlphaTest.
void GLSL_VertexAttribsState (uint32_t stateBits)
GLSL_VertexAttribsState.
void GLSL_VertexAttribPointers (uint32_t attribBits)
GLSL_VertexAttribPointers.
Variables
static char * complieMacroNames []
static uniformInfo_t uniformsInfo []
const attrmap attributeMap []
const int textureMap []
const int numberofAttributes = ARRAY_LEN(attributeMap)
static programInfo_t * hashTable [FILE_HASH_SIZE]
static char * definitionText
trPrograms_t trProg
static char shaderExtraDef [8000]
Macro Definition Documentation
#define ATTR_MAP
#define BUFFEXT (...) Q_strcat(shaderExtraDef, sizeof(shaderExtraDef), va(__VA_ARGS__))
Referenced by GLSL_BuildShaderExtraDef().
#define DEFAULT_SHADER_DEF NULL
Definition at line 81 of file tr_glsl.c.
Referenced by GLSL_FindShader().
#define FILE_HASH_SIZE 4096
Definition at line 79 of file tr_glsl.c.
Referenced by GLSL_FindShader(), and GLSL_ShutdownGPUShaders().
#define GL_SHADER_VERSION 3
Definition at line 86 of file tr_glsl.c.
Referenced by GLSL_LoadShaderBinary(), and GLSL_SaveShaderBinary().
#define GLSL_BUFF 64000
Definition at line 1364 of file tr_glsl.c.
Referenced by GLSL_BuildGPUShaderText().
#define GLSL_BUFF_CHAR (sizeof(char) *GLSL_BUFF)
Definition at line 1365 of file tr_glsl.c.
Referenced by GLSL_BuildGPUShaderText().
#define MACRO_NAME
#define MAX_SHADER_DEF_FILES 1024
Definition at line 80 of file tr_glsl.c.
#define TEX_MAP
#define UNIFORM_TYPE
Typedef Documentation
GLShaderHeader_t
Function Documentation
static void GLSL_BindAttribLocations (GLuint program) static
GLSL_BindAttribLocations.
Parameters
[in] program
Definition at line 1992 of file tr_glsl.c.
Referenced by GLSL_InitGPUShader2().
void GLSL_BindNullProgram (void)
GLSL_BindNullProgram.
Definition at line 2905 of file tr_glsl.c.
Referenced by GLSL_BindProgram(), GLSL_CompilePermutation(), and GLSL_ShutdownGPUShaders().
void GLSL_BindProgram (shaderProgram_t * program)
GLSL_BindProgram.
Parameters
[in] program
Definition at line 2884 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation(), GLSL_SelectPermutation(), R_DebugGraphics(), and RB_SafeState().
static char* GLSL_BuildGPUShaderText (programInfo_t * info, GLenum shadertype) static
GLSL_BuildGPUShaderText.
Parameters
[in] info
[in] shadertype
Returns
Todo:
: handle
Todo:
: handle
Todo:
: handle
Definition at line 1373 of file tr_glsl.c.
Referenced by GLSL_CompileShaderProgram().
static void GLSL_BuildShaderExtraDef () static
GLSL_BuildShaderExtraDef.
Todo:
: this was enabled for ati card.. Should not be needed anymore? Remove from GLSL code in that case
Definition at line 829 of file tr_glsl.c.
Referenced by GLSL_InitGPUShaders().
static int GLSL_CompileGPUShader (GLhandleARB program, GLhandleARB * prevShader, const GLcharARB * buffer, int size, GLenum shaderType, const char * name) static
GLSL_CompileGPUShader.
Parameters
[in] program
[in,out] prevShader
[in] buffer
[in] size
[in] shaderType
[in] name
Returns
Definition at line 1147 of file tr_glsl.c.
Referenced by GLSL_InitGPUShader2().
void GLSL_CompileGPUShaders (void)
GLSL_CompileGPUShaders.
Definition at line 2776 of file tr_glsl.c.
Referenced by GLSL_restart_f(), and R_Init().
static qboolean GLSL_CompilePermutation (programInfo_t * info, int offset) static
GLSL_CompilePermutation.
Parameters
[in,out] info
[in] offset
Returns
Definition at line 2259 of file tr_glsl.c.
Referenced by GLSL_CompileShaderProgram(), and GLSL_SelectPermutation().
qboolean GLSL_CompileShaderProgram (programInfo_t * info)
GLSL_CompileShaderProgram.
Parameters
[in,out] info
Returns
Definition at line 2299 of file tr_glsl.c.
Referenced by GLSL_GetShaderProgram().
qboolean GLSL_CopyNextToken (char ** text, char ** out)
GLSL_CopyNextToken.
Parameters
[in,out] text
[out] out
Returns
Definition at line 201 of file tr_glsl.c.
Referenced by GLSL_ParseDefinition().
void GLSL_CopyStringAlloc (char ** out, const char * in)
GLSL_CopyStringAlloc.
Parameters
[out] out
[in] in
Definition at line 186 of file tr_glsl.c.
Referenced by GLSL_CopyNextToken(), and GLSL_ParseDefinition().
void GLSL_DeleteGPUShader (shaderProgram_t * program)
GLSL_DeleteGPUShader.
Parameters
[in] program
Definition at line 2632 of file tr_glsl.c.
Referenced by GLSL_DeleteShaderProgramList().
void GLSL_DeleteShaderProgramInfo (programInfo_t * program)
GLSL_DeleteShaderProgramInfo.
Parameters
[in] program
Definition at line 2679 of file tr_glsl.c.
Referenced by GLSL_ShutdownGPUShaders().
void GLSL_DeleteShaderProgramList (shaderProgramList_t * programlist)
GLSL_DeleteShaderProgramList.
Parameters
[in] programlist
Definition at line 2663 of file tr_glsl.c.
Referenced by GLSL_DeleteShaderProgramInfo().
static char* GLSL_FindDefinitionInText (const char * shadername) static
GLSL_FindDefinitionInText.
Parameters
[in] shadername
Returns
Definition at line 372 of file tr_glsl.c.
Referenced by GLSL_FindShader().
programInfo_t* GLSL_FindShader (const char * name)
GLSL_FindShader.
Parameters
[in] name
Returns
Definition at line 409 of file tr_glsl.c.
Referenced by GLSL_GetShaderProgram().
void GLSL_FinishGPUShader (shaderProgram_t * program)
GLSL_FinishGPUShader.
Parameters
[in] program
Definition at line 1609 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation().
static qboolean GLSL_FinnishShaderTextAndCompile (programInfo_t * info, int permutation, const char * vertex, const char * frag, const char * macrostring) static
GLSL_FinnishShaderTextAndCompile.
Parameters
[in] info
[in] permutation
[in] vertex
[in] frag
[in] macrostring
Returns
Definition at line 2067 of file tr_glsl.c.
Referenced by GLSL_GetProgramPermutation().
void GLSL_GenerateCheckSum (programInfo_t * info, const char * vertex, const char * fragment)
GLSL_GenerateCheckSum.
Parameters
[out] info
[in] vertex
[in] fragment
Definition at line 2228 of file tr_glsl.c.
Referenced by GLSL_CompileShaderProgram().
static qboolean GLSL_GenerateMacroString (shaderProgramList_t * program, const char * macros, int permutation, char ** out) static
GLSL_GenerateMacroString.
Parameters
[in] program
[in] macros
[in] permutation
[out] out
Returns
Warning
This whole method is stupid, clean this shit up
Definition at line 1429 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation().
unsigned int GLSL_GetAttribByName (const char * name)
GLSL_GetAttribByName.
Parameters
[in] name
Returns
Todo:
FIXME: return -1 but type is unsigned !
Definition at line 164 of file tr_glsl.c.
Referenced by GLSL_ParseDefinition().
int GLSL_GetMacroByName (const char * name)
GLSL_GetMacroByName.
Parameters
[in] name
Returns
Definition at line 142 of file tr_glsl.c.
Referenced by GLSL_ParseDefinition().
static qboolean GLSL_GetProgramPermutation (programInfo_t * info, int permutation, const char * vertex, const char * frag, const char * macrostring) static
GLSL_GetProgramPermutation.
Parameters
[in] info
[in] permutation
[in] vertex
[in] frag
[in] macrostring
Returns
Definition at line 2116 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation().
static unsigned int GLSL_GetRequiredVertexAttributes (int compilemacro) static
GLSL_GetRequiredVertexAttributes.
Parameters
[in] compilemacro
Returns
Definition at line 783 of file tr_glsl.c.
Referenced by GLSL_SetRequiredVertexPointers().
static void GLSL_GetShaderHeader (GLenum shaderType, char * dest, size_t size) static
GLSL_GetShaderHeader.
Parameters
[in] shaderType
[out] dest
[in] size
Definition at line 1105 of file tr_glsl.c.
Referenced by GLSL_FinnishShaderTextAndCompile().
programInfo_t* GLSL_GetShaderProgram (const char * name)
GLSL_GetShaderProgram.
Parameters
[in] name
Returns
Definition at line 2399 of file tr_glsl.c.
Referenced by GLSL_CompileGPUShaders().
static void GLSL_GetShaderText (const char * name, GLenum shaderType, char ** data, size_t * size, qboolean append) static
GLSL_GetShaderText loads shader text into data buffer.
Parameters
[in] name
[in] shaderType
[out] data
[out] size
[in] append
Note
We don't ship glsl files anymore - GetFallbackShader() does the job
Definition at line 1198 of file tr_glsl.c.
Referenced by GLSL_BuildGPUShaderText(), and GLSL_PreprocessShaderText().
static qboolean GLSL_HasConflictingMacros (int compilemacro, int usedmacros) static
GLSL_HasConflictingMacros.
Parameters
[in] compilemacro
[in] usedmacros
Returns
Definition at line 724 of file tr_glsl.c.
Referenced by GLSL_GenerateMacroString().
static qboolean GLSL_InitGPUShader2 (shaderProgram_t * program, const char * name, const char * vpCode, const char * fpCode) static
GLSL_InitGPUShader2.
Parameters
[in,out] program
[in] name
[in] vpCode
[in] fpCode
Returns
Definition at line 2021 of file tr_glsl.c.
Referenced by GLSL_FinnishShaderTextAndCompile().
void GLSL_InitGPUShaders (void)
GLSL_InitGPUShaders.
Definition at line 2748 of file tr_glsl.c.
Referenced by GLSL_restart_f(), and InitOpenGL().
void GLSL_InitUniforms (shaderProgram_t * program)
GLSL_InitUniforms.
Parameters
[out] program
Definition at line 1553 of file tr_glsl.c.
Referenced by GLSL_GetProgramPermutation().
static void GLSL_LinkProgram (GLhandleARB program) static
GLSL_LinkProgram.
Parameters
[in] program
Definition at line 1480 of file tr_glsl.c.
Referenced by GLSL_InitGPUShader2().
void GLSL_LoadDefinitions (void)
GLSL_LoadDefinitions.
Todo:
: Also load from external files in the future...
Definition at line 461 of file tr_glsl.c.
Referenced by GLSL_InitGPUShaders().
qboolean GLSL_LoadShaderBinary (programInfo_t * info, size_t programNum)
GLSL_LoadShaderBinary.
Parameters
[in] info
[in] programNum
Returns
Definition at line 576 of file tr_glsl.c.
Referenced by GLSL_GetProgramPermutation().
static qboolean GLSL_MissesRequiredMacros (int compilemacro, int usedmacros) static
GLSL_MissesRequiredMacros.
Parameters
[in] compilemacro
[in] usedmacros
Returns
Definition at line 753 of file tr_glsl.c.
Referenced by GLSL_GenerateMacroString().
programInfo_t* GLSL_ParseDefinition (char ** text, const char * defname)
GLSL_ParseDefinition.
Parameters
[in,out] text
[in] defname
Returns
Todo:
: implement other formats
Definition at line 227 of file tr_glsl.c.
Referenced by GLSL_FindShader().
static void GLSL_PreprocessShaderText (char * shaderBuffer, char * filetext, GLenum shadertype) static
GLSL_PreprocessShaderText.
Parameters
[in] shaderBuffer
[in,out] filetext
[in] shadertype
Definition at line 1282 of file tr_glsl.c.
Referenced by GLSL_BuildGPUShaderText().
static void GLSL_PrintInfoLog (GLhandleARB object, qboolean developerOnly, qboolean isProgram) static
GLSL_PrintInfoLog.
Parameters
[in] object
[in] developerOnly
[in] isProgram
Definition at line 479 of file tr_glsl.c.
Referenced by GLSL_CompileGPUShader(), GLSL_LinkProgram(), and GLSL_ValidateProgram().
void GLSL_SaveShaderBinary (programInfo_t * info, size_t programNum)
GLSL_SaveShaderBinary.
Parameters
[in] info
[in] programNum
Definition at line 665 of file tr_glsl.c.
Referenced by GLSL_FinnishShaderTextAndCompile().
void GLSL_SelectPermutation (programInfo_t * programlist)
GLSL_SelectPermutation.
Parameters
[in] programlist
Definition at line 2546 of file tr_glsl.c.
void GLSL_SelectTexture (shaderProgram_t * program, texture_def_t tex)
GLSL_SelectTexture.
Parameters
[in] program
[in] tex
Definition at line 1621 of file tr_glsl.c.
static void GLSL_SetInitialUniformValues (programInfo_t * info, int permutation) static
GLSL_SetInitialUniformValues.
Parameters
[in] info
[in] permutation
Definition at line 2160 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation().
void GLSL_SetMacroState (programInfo_t * programlist, int macro, int enabled)
GLSL_SetMacroState.
Parameters
[in,out] programlist
[in] macro
[in] enabled
Definition at line 2453 of file tr_glsl.c.
Referenced by GLSL_SetMacroStates().
void GLSL_SetMacroStates (programInfo_t * programlist, int numMacros, ...)
GLSL_SetMacroStates.
Parameters
[in] programlist
[in] numMacros
Definition at line 2501 of file tr_glsl.c.
void GLSL_SetMacroStatesByOffset (programInfo_t * programlist, int offset)
GLSL_SetMacroStatesByOffset.
Parameters
[in,out] programlist
[in] offset
Definition at line 2419 of file tr_glsl.c.
Referenced by GLSL_SetMacroStates().
void GLSL_SetRequiredVertexPointers (programInfo_t * programlist)
GLSL_SetRequiredVertexPointers.
Parameters
[in] programlist
Todo:
: implement this
Definition at line 2590 of file tr_glsl.c.
Referenced by DrawTris(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderLightOcclusionQueries(), and Tess_StageIteratorSky().
static void GLSL_SetTextureUnitBindings (programInfo_t * info, int permutation) static
GLSL_SetTextureUnitBindings.
Parameters
[in] info
[in] permutation
Definition at line 2135 of file tr_glsl.c.
Referenced by GLSL_CompilePermutation().
void GLSL_SetUniform_AlphaTest (uint32_t stateBits)
GLSL_SetUniform_AlphaTest.
Parameters
[in] stateBits
Definition at line 3039 of file tr_glsl.c.
void GLSL_SetUniform_ColorModulate (programInfo_t * prog, int colorGen, int alphaGen)
GLSL_SetUniform_ColorModulate.
Parameters
[in,out] prog
[in] colorGen
[in] alphaGen
Definition at line 2984 of file tr_glsl.c.
Referenced by DrawTris(), R_CoherentHierachicalCulling(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_ShowImages(), and RE_StretchRaw().
void GLSL_SetUniform_DeformParms (deformStage_t deforms[], int numDeforms)
GLSL_SetUniform_DeformParms.
Parameters
[in] deforms
[in] numDeforms
Definition at line 2921 of file tr_glsl.c.
Referenced by DrawTris(), and RB_RenderBspOcclusionQueries().
void GLSL_SetUniformBoolean (shaderProgram_t * program, int uniformNum, GLboolean value)
GLSL_SetUniformBoolean.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1641 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformDouble (shaderProgram_t * program, int uniformNum, GLdouble value)
GLSL_SetUniformDouble.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1734 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformFloat (shaderProgram_t * program, int uniformNum, GLfloat value)
GLSL_SetUniformFloat.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1703 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformFloat5 (shaderProgram_t * program, int uniformNum, const vec5_t v)
GLSL_SetUniformFloat5.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1860 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformFloatARR (shaderProgram_t * program, int uniformNum, float * floatarray, int arraysize)
GLSL_SetUniformFloatARR.
Parameters
[in] program
[in] uniformNum
[in] floatarray
[in] arraysize
Definition at line 1923 of file tr_glsl.c.
Referenced by GLSL_SetUniform_DeformParms().
void GLSL_SetUniformInt (shaderProgram_t * program, int uniformNum, GLint value)
GLSL_SetUniformInt.
Parameters
[in] program
[in] uniformNum
[in] value
Definition at line 1672 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformMatrix16 (shaderProgram_t * program, int uniformNum, const mat4_t matrix)
GLSL_SetUniformMatrix16.
Parameters
[in] program
[in] uniformNum
[in] matrix
Definition at line 1891 of file tr_glsl.c.
void GLSL_SetUniformMatrix16ARR (shaderProgram_t * program, int uniformNum, mat4_t * matrixarray, int arraysize)
GLSL_SetUniformMatrix16ARR.
Parameters
[in] program
[in] uniformNum
[in] matrixarray
[in] arraysize
Definition at line 1971 of file tr_glsl.c.
void GLSL_SetUniformVec2 (shaderProgram_t * program, int uniformNum, const vec2_t v)
GLSL_SetUniformVec2.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1766 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformVec3 (shaderProgram_t * program, int uniformNum, const vec3_t v)
GLSL_SetUniformVec3.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1798 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformVec4 (shaderProgram_t * program, int uniformNum, const vec4_t v)
GLSL_SetUniformVec4.
Parameters
[in] program
[in] uniformNum
[in] v
Definition at line 1829 of file tr_glsl.c.
Referenced by GLSL_SetInitialUniformValues().
void GLSL_SetUniformVec4ARR (shaderProgram_t * program, int uniformNum, vec4_t * vectorarray, int arraysize)
GLSL_SetUniformVec4ARR.
Parameters
[in] program
[in] uniformNum
[in] vectorarray
[in] arraysize
Definition at line 1947 of file tr_glsl.c.
static void GLSL_ShowProgramUniforms (GLhandleARB program) static
GLSL_ShowProgramUniforms.
Parameters
[in] program
Definition at line 1524 of file tr_glsl.c.
Referenced by GLSL_FinishGPUShader().
void GLSL_ShutdownGPUShaders (void)
GLSL_ShutdownGPUShaders.
Definition at line 2849 of file tr_glsl.c.
Referenced by GLSL_restart_f(), and RE_Shutdown().
static void GLSL_ValidateProgram (GLhandleARB program) static
GLSL_ValidateProgram.
Parameters
[in] program
Definition at line 1505 of file tr_glsl.c.
Referenced by GLSL_FinishGPUShader().
void GLSL_VertexAttribPointers (uint32_t attribBits)
GLSL_VertexAttribPointers.
Parameters
[in] attribBits
Todo:
: this occures on maps for unknown reasons (uje_marketgarden + r_wolffog and
Definition at line 3260 of file tr_glsl.c.
Referenced by GLSL_VertexAttribsState().
void GLSL_VertexAttribsState (uint32_t stateBits)
GLSL_VertexAttribsState.
Parameters
[in] stateBits
Definition at line 3066 of file tr_glsl.c.
Referenced by GLSL_SetRequiredVertexPointers(), IssueMultiOcclusionQueries(), IssueOcclusionQuery(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RenderEntityOcclusionVolume(), RenderLightOcclusionVolume(), Tess_UpdateVBOs(), and TraverseNode().
Variable Documentation
const attrmap attributeMap[]
Definition at line 63 of file tr_glsl.c.
char* complieMacroNames[] static
Definition at line 42 of file tr_glsl.c.
Referenced by GLSL_GenerateMacroString(), and GLSL_GetMacroByName().
char* definitionText static
Definition at line 84 of file tr_glsl.c.
Referenced by GLSL_FindDefinitionInText(), GLSL_LoadDefinitions(), and GLSL_ShutdownGPUShaders().
programInfo_t* hashTable[FILE_HASH_SIZE] static
Definition at line 82 of file tr_glsl.c.
const int numberofAttributes = ARRAY_LEN(attributeMap)
Definition at line 77 of file tr_glsl.c.
Referenced by GLSL_GetAttribByName().
char shaderExtraDef[8000] static
Definition at line 823 of file tr_glsl.c.
Referenced by GLSL_BuildGPUShaderText(), and GLSL_BuildShaderExtraDef().
const int textureMap[]
Definition at line 70 of file tr_glsl.c.
Referenced by GLSL_SetTextureUnitBindings().
trPrograms_t trProg
Definition at line 135 of file tr_glsl.c.
Referenced by DrawTris(), R_CoherentHierachicalCulling(), RB_CameraPostFX(), RB_ColorCorrection(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderEntityOcclusionQueries(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), RB_ShowImages(), RE_StretchRaw(), Render_lightVolume(), and Tess_StageIteratorSky().
uniformInfo_t uniformsInfo[] static
Definition at line 50 of file tr_glsl.c.