ET: Legacy: src/renderer2/tr_fbo.c File Reference
tr_fbo.c File Reference
#include "tr_local.h"
Functions
qboolean R_CheckFBO (const FBO_t *fbo)
R_CheckFBO.
FBO_t * R_CreateFBO (const char *name, int width, int height)
R_CreateFBO.
void R_CreateFBOColorBuffer (FBO_t *fbo, int format, int index)
Framebuffer must be bound.
void R_CreateFBODepthBuffer (FBO_t *fbo, int format)
R_CreateFBODepthBuffer.
void R_CreateFBOStencilBuffer (FBO_t *fbo, int format)
R_CreateFBOStencilBuffer.
void R_CreateFBOPackedDepthStencilBuffer (FBO_t *fbo, int format)
R_CreateFBOPackedDepthStencilBuffer.
void R_AttachFBOTexture1D (int texId, int index)
R_AttachFBOTexture1D.
void R_AttachFBOTexture2D (int target, int texId, int index)
R_AttachFBOTexture2D.
void R_AttachFBOTexture3D (int texId, int index, int zOffset)
R_AttachFBOTexture3D.
void R_AttachFBOTextureDepth (int texId)
R_AttachFBOTextureDepth.
void R_AttachFBOTexturePackedDepthStencil (int texId)
R_AttachFBOTexturePackedDepthStencil.
void R_CopyToFBO (FBO_t *from, FBO_t *to, GLuint mask, GLuint filter)
R_CopyToFBO.
void R_BindFBO (FBO_t *fbo)
R_BindFBO.
void R_BindNullFBO (void)
R_BindNullFBO.
void R_SetDefaultFBO (void)
R_SetDefaultFBO.
static void R_CheckDefaultBuffer ()
R_CheckDefaultBuffer.
void R_AttachColorBufferToFBO (FBO_t *fbo, int format, int target, image_t *texture, int index)
R_AttachColorBufferToFBO.
FBO_t * R_CreateReadyFBO (const char *name, float size)
R_CreateReadyFBO.
void R_InitFBOs (void)
R_InitFBOs.
void R_ShutdownFBOs (void)
R_ShutdownFBOs.
void R_FBOList_f (void)
R_FBOList_f.
Function Documentation
void R_AttachColorBufferToFBO (FBO_t * fbo, int format, int target, image_t * texture, int index)
R_AttachColorBufferToFBO.
Parameters
[in,out] fbo
[in] format
[in] target
[in] texture
[in] index
Definition at line 519 of file tr_fbo.c.
void R_AttachFBOTexture1D (int texId, int index)
R_AttachFBOTexture1D.
Parameters
[in] texId
[in] index
Definition at line 314 of file tr_fbo.c.
void R_AttachFBOTexture2D (int target, int texId, int index)
R_AttachFBOTexture2D.
Parameters
[in] target
[in] texId
[in] index
Definition at line 331 of file tr_fbo.c.
Referenced by R_AttachColorBufferToFBO(), R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
void R_AttachFBOTexture3D (int texId, int index, int zOffset)
R_AttachFBOTexture3D.
Parameters
[in] texId
[in] index
[in] zOffset
Definition at line 354 of file tr_fbo.c.
void R_AttachFBOTextureDepth (int texId)
R_AttachFBOTextureDepth.
Parameters
[in] texId
Definition at line 369 of file tr_fbo.c.
Referenced by R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
void R_AttachFBOTexturePackedDepthStencil (int texId)
R_AttachFBOTexturePackedDepthStencil.
Parameters
[in] texId
Definition at line 378 of file tr_fbo.c.
void R_BindFBO (FBO_t * fbo)
R_BindFBO.
Parameters
[in] fbo
Definition at line 428 of file tr_fbo.c.
Referenced by R_CoherentHierachicalCulling(), R_CreateReadyFBO(), R_InitFBOs(), RB_CalculateAdaptation(), RB_RenderBloom(), RB_RenderInteractionsShadowMapped(), and RB_RenderViewFront().
void R_BindNullFBO (void)
R_BindNullFBO.
Definition at line 460 of file tr_fbo.c.
Referenced by R_BindFBO(), R_CoherentHierachicalCulling(), R_InitFBOs(), R_ShutdownFBOs(), RB_RenderBloom(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderViewFront(), and RB_SetGL2D().
static void R_CheckDefaultBuffer () static
R_CheckDefaultBuffer.
Definition at line 488 of file tr_fbo.c.
Referenced by R_InitFBOs().
qboolean R_CheckFBO (const FBO_t * fbo)
R_CheckFBO.
Parameters
[in] fbo
Returns
Definition at line 43 of file tr_fbo.c.
Referenced by R_InitFBOs(), and RB_RenderInteractionsShadowMapped().
void R_CopyToFBO (FBO_t * from, FBO_t * to, GLuint mask, GLuint filter)
R_CopyToFBO.
Parameters
[in] from
[in] to
[in] mask
[in] filter
Todo:
add non EXT_framebuffer_blit code
Definition at line 391 of file tr_fbo.c.
Referenced by RB_RenderViewFront().
FBO_t* R_CreateFBO (const char * name, int width, int height)
R_CreateFBO.
Parameters
[in] name
[in] width
[in] height
Returns
Definition at line 102 of file tr_fbo.c.
Referenced by R_CreateReadyFBO(), and R_InitFBOs().
void R_CreateFBOColorBuffer (FBO_t * fbo, int format, int index)
Framebuffer must be bound.
Parameters
[in,out] fbo
[in] format
[in] index
Definition at line 152 of file tr_fbo.c.
Referenced by R_AttachColorBufferToFBO(), and R_InitFBOs().
void R_CreateFBODepthBuffer (FBO_t * fbo, int format)
R_CreateFBODepthBuffer.
Parameters
[in,out] fbo
[in] format
Definition at line 198 of file tr_fbo.c.
Referenced by R_InitFBOs().
void R_CreateFBOPackedDepthStencilBuffer (FBO_t * fbo, int format)
R_CreateFBOPackedDepthStencilBuffer.
Parameters
[in,out] fbo
[in] format
Definition at line 276 of file tr_fbo.c.
Referenced by R_InitFBOs().
void R_CreateFBOStencilBuffer (FBO_t * fbo, int format)
R_CreateFBOStencilBuffer.
Parameters
[in,out] fbo
[in] format
Definition at line 236 of file tr_fbo.c.
FBO_t* R_CreateReadyFBO (const char * name, float size)
R_CreateReadyFBO.
Parameters
[in] name
[in] size
Returns
Definition at line 532 of file tr_fbo.c.
void R_FBOList_f (void)
R_FBOList_f.
Definition at line 948 of file tr_fbo.c.
Referenced by R_Register().
void R_InitFBOs (void)
R_InitFBOs.
Definition at line 558 of file tr_fbo.c.
Referenced by R_Init().
void R_SetDefaultFBO (void)
R_SetDefaultFBO.
Definition at line 475 of file tr_fbo.c.
Referenced by GL_SetDefaultState().
void R_ShutdownFBOs (void)
R_ShutdownFBOs.
Definition at line 902 of file tr_fbo.c.
Referenced by RE_Shutdown().