ET: Legacy: src/renderercommon/tr_noise.c File Reference
tr_noise.c File Reference
#include "tr_common.h"
Macros
#define NOISE_SIZE 256
#define NOISE_MASK (NOISE_SIZE - 1)
#define VAL(a) s_noise_perm[(a) & (NOISE_MASK)]
#define INDEX(x, y, z, t) VAL(x + VAL(y + VAL(z + VAL(t))))
Functions
static double GetNoiseValue (int x, int y, int z, int t)
GetNoiseValue.
void R_NoiseInit (void)
R_NoiseInit.
double R_NoiseGet4f (double x, double y, double z, double t)
R_NoiseGet4f.
Variables
static double s_noise_table [NOISE_SIZE]
static int s_noise_perm [NOISE_SIZE]
Macro Definition Documentation
#define INDEX (x, y, z, t) VAL(x + VAL(y + VAL(z + VAL(t))))
Definition at line 41 of file tr_noise.c.
Referenced by GetNoiseValue().
#define NOISE_MASK (NOISE_SIZE - 1)
Definition at line 38 of file tr_noise.c.
#define NOISE_SIZE 256
Definition at line 37 of file tr_noise.c.
Referenced by R_NoiseInit().
#define VAL (a) s_noise_perm[(a) & (NOISE_MASK)]
Definition at line 40 of file tr_noise.c.
Function Documentation
static double GetNoiseValue (int x, int y, int z, int t) static
GetNoiseValue.
Parameters
[in] x
[in] y
[in] z
[in] t
Returns
Definition at line 54 of file tr_noise.c.
Referenced by R_NoiseGet4f().
double R_NoiseGet4f (double x, double y, double z, double t)
R_NoiseGet4f.
Parameters
[in] x
[in] y
[in] z
[in] t
Returns
Definition at line 85 of file tr_noise.c.
Referenced by R_Init(), RB_CalcDeformNormals(), RB_CalcWaveAlpha(), and RB_CalcWaveColor().
void R_NoiseInit (void)
R_NoiseInit.
Definition at line 64 of file tr_noise.c.
Referenced by R_Init().
Variable Documentation
int s_noise_perm[NOISE_SIZE] static
Definition at line 44 of file tr_noise.c.
Referenced by R_NoiseInit().
double s_noise_table[NOISE_SIZE] static
Definition at line 43 of file tr_noise.c.
Referenced by GetNoiseValue(), and R_NoiseInit().