ET: Legacy: src/renderer2/tr_gl.c File Reference
tr_gl.c File Reference
#include "tr_local.h"
Functions
void GL_Bind (image_t *image)
GL_Bind.
void GL_Unbind ()
GL_Unbind.
void BindAnimatedImage (textureBundle_t *bundle)
BindAnimatedImage.
void GL_SelectTexture (int unit)
GL_SelectTexture.
void GL_BlendFunc (GLenum sfactor, GLenum dfactor)
GL_BlendFunc.
void GL_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_ClearColor.
void GL_ClearDepth (GLclampd depth)
GL_ClearDepth.
void GL_ClearStencil (GLint s)
GL_ClearStencil.
void GL_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_ColorMask.
void GL_CullFace (GLenum mode)
GL_CullFace.
void GL_DepthFunc (GLenum func)
GL_DepthFunc.
void GL_DepthMask (GLboolean flag)
GL_DepthMask.
void GL_DrawBuffer (GLenum mode)
GL_DrawBuffer.
void GL_FrontFace (GLenum mode)
GL_FrontFace.
void GL_LoadModelViewMatrix (const mat4_t m)
GL_LoadModelViewMatrix.
void GL_LoadProjectionMatrix (const mat4_t m)
GL_LoadProjectionMatrix.
void GL_PushMatrix ()
GL_PushMatrix.
void GL_PopMatrix ()
GL_PopMatrix.
void GL_PolygonMode (GLenum face, GLenum mode)
GL_PolygonMode.
void GL_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Scissor.
void GL_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Viewport.
void GL_PolygonOffset (float factor, float units)
GL_PolygonOffset.
void GL_Clear (unsigned int bits)
GL_Clear.
void GL_Cull (int cullType)
GL_Cull.
void GL_State (uint32_t stateBits)
This routine is responsible for setting the most commonly changed state in Q3.
Function Documentation
void BindAnimatedImage (textureBundle_t * bundle)
BindAnimatedImage.
Parameters
[in] bundle
Definition at line 87 of file tr_gl.c.
Referenced by Render_lightVolume().
void GL_Bind (image_t * image)
GL_Bind.
Parameters
[in,out] image
Definition at line 42 of file tr_gl.c.
Referenced by BindAnimatedImage().
void GL_BlendFunc (GLenum sfactor, GLenum dfactor)
GL_BlendFunc.
Parameters
[in] sfactor
[in] dfactor
Definition at line 210 of file tr_gl.c.
Referenced by GL_State().
void GL_Clear (unsigned int bits)
GL_Clear.
Parameters
[in] bits
Definition at line 493 of file tr_gl.c.
Referenced by GL_SetDefaultState(), R_CoherentHierachicalCulling(), RB_DrawBuffer(), RB_Hyperspace(), RB_RenderBloom(), RB_RenderInteractionsShadowMapped(), RB_RenderViewFront(), and RB_ShowImages().
void GL_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_ClearColor.
Parameters
[in] red
[in] green
[in] blue
[in] alpha
Definition at line 228 of file tr_gl.c.
Referenced by GL_SetDefaultState(), R_CoherentHierachicalCulling(), RB_DrawBuffer(), RB_Fog(), RB_Hyperspace(), RB_RenderBloom(), RB_RenderInteractionsShadowMapped(), and RB_RenderViewFront().
void GL_ClearDepth (GLclampd depth)
GL_ClearDepth.
Parameters
[in] depth
Definition at line 245 of file tr_gl.c.
Referenced by GL_SetDefaultState().
void GL_ClearStencil (GLint s)
GL_ClearStencil.
Parameters
[in] s
Definition at line 259 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and RE_BeginFrame().
void GL_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_ColorMask.
Parameters
[in] red
[in] green
[in] blue
[in] alpha
Definition at line 276 of file tr_gl.c.
Referenced by GL_State().
void GL_Cull (int cullType)
GL_Cull.
Parameters
[in] cullType
Definition at line 502 of file tr_gl.c.
void GL_CullFace (GLenum mode)
GL_CullFace.
Parameters
[in] mode
Definition at line 293 of file tr_gl.c.
Referenced by GL_Cull(), and GL_SetDefaultState().
void GL_DepthFunc (GLenum func)
GL_DepthFunc.
Parameters
[in] func
Definition at line 307 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and GL_State().
void GL_DepthMask (GLboolean flag)
GL_DepthMask.
Parameters
[in] flag
Definition at line 321 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and GL_State().
void GL_DrawBuffer (GLenum mode)
GL_DrawBuffer.
Parameters
[in] mode
Definition at line 335 of file tr_gl.c.
Referenced by RB_DrawBuffer().
void GL_FrontFace (GLenum mode)
GL_FrontFace.
Parameters
[in] mode
Definition at line 349 of file tr_gl.c.
Referenced by GL_Cull(), and GL_SetDefaultState().
void GL_LoadModelViewMatrix (const mat4_t m)
GL_LoadModelViewMatrix.
Parameters
[in] m
Definition at line 363 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_DrawSun(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderDrawSurfaces(), RB_RenderEntityOcclusionQueries(), RB_RenderFlares(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_SetGL2D(), RB_SetViewMVPM(), RenderEntityOcclusionVolume(), and RenderLightOcclusionVolume().
void GL_LoadProjectionMatrix (const mat4_t m)
GL_LoadProjectionMatrix.
Parameters
[in] m
Definition at line 378 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_DrawSun(), RB_RenderBloom(), RB_RenderBspOcclusionQueries(), RB_RenderDebugUtils(), RB_RenderEntityOcclusionQueries(), RB_RenderInteractionsShadowMapped(), RB_RenderLightOcclusionQueries(), RB_SetGL2D(), RB_SetViewMVPM(), and SetViewportAndScissor().
void GL_PolygonMode (GLenum face, GLenum mode)
GL_PolygonMode.
Parameters
[in] face
[in] mode
Definition at line 422 of file tr_gl.c.
Referenced by GL_SetDefaultState(), and GL_State().
void GL_PolygonOffset (float factor, float units)
GL_PolygonOffset.
Parameters
[in] factor
[in] units
Definition at line 478 of file tr_gl.c.
Referenced by RB_RenderDebugUtils().
void GL_PopMatrix ()
GL_PopMatrix.
Definition at line 406 of file tr_gl.c.
Referenced by RB_CameraPostFX(), RB_DrawSun(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), and Render_lightVolume().
void GL_PushMatrix ()
GL_PushMatrix.
Definition at line 392 of file tr_gl.c.
Referenced by RB_CameraPostFX(), RB_DrawSun(), RB_RenderBloom(), RB_RenderDebugUtils(), RB_RenderDepthOfField(), RB_RenderFlares(), RB_RenderGlobalFog(), RB_RenderHDRResultToFrameBuffer(), RB_RenderInteractionsShadowMapped(), RB_RenderRotoscope(), RB_RenderScreenSpaceAmbientOcclusion(), and Render_lightVolume().
void GL_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Scissor.
Parameters
[in] x
[in] y
[in] width
[in] height
Definition at line 440 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_RenderDebugUtils(), RB_RenderInteractions(), RB_RenderInteractionsShadowMapped(), RB_SetGL2D(), Render_lightVolume(), and SetViewportAndScissor().
void GL_SelectTexture (int unit)
GL_SelectTexture.
Parameters
[in] unit
Definition at line 184 of file tr_gl.c.
void GL_State (uint32_t stateBits)
This routine is responsible for setting the most commonly changed state in Q3.
Parameters
[in] stateBits
Todo:
Definition at line 549 of file tr_gl.c.
void GL_Unbind ()
GL_Unbind.
Definition at line 76 of file tr_gl.c.
void GL_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
GL_Viewport.
Parameters
[in] x
[in] y
[in] width
[in] height
Definition at line 460 of file tr_gl.c.
Referenced by R_CoherentHierachicalCulling(), RB_RenderDebugUtils(), RB_RenderInteractionsShadowMapped(), RB_SetGL2D(), Render_lightVolume(), and SetViewportAndScissor().