ET: Legacy: src/renderer/tr_image.c File Reference
tr_image.c File Reference
#include "tr_local.h"
Data Structures
struct textureMode_t
struct imageExtToLoaderMap_t
Macros
#define FILE_HASH_SIZE 4096
#define generateHashValue(fname) Q_GenerateHashValue(fname, FILE_HASH_SIZE, qfalse, qtrue);
#define R_IMAGE_BUFFER_SIZE (512 * 512 * 4)
#define DLIGHT_SIZE 16
#define FOG_S 16
#define FOG_T 16
#define DEFAULT_SIZE 16
Functions
void * R_GetImageBuffer (int size, bufferMemType_t bufferType, const char *filename)
R_GetImageBuffer.
void R_FreeImageBuffer (void)
R_FreeImageBuffer.
void R_GammaCorrect (byte *buffer, int bufSize)
R_GammaCorrect.
void GL_TextureMode (const char *string)
GL_TextureMode.
int R_SumOfUsedImages (void)
R_SumOfUsedImages.
void R_ImageList_f (void)
R_ImageList_f.
static void ResampleTexture (unsigned *in, int inwidth, int inheight, unsigned *out, int outwidth, int outheight)
Used to resample images in a more general than quartering fashion.
void R_LightScaleTexture (unsigned *in, int inwidth, int inheight, qboolean only_gamma)
Scale up the pixel values in a texture to increase the lighting range.
static void R_MipMap2 (unsigned *in, int inWidth, int inHeight)
Operates in place, quartering the size of the texture Proper linear filter.
static void R_MipMap (byte *in, int width, int height)
Operates in place, quartering the size of the texture.
static void R_BlendOverTexture (byte *data, int pixelCount, byte blend[4])
Apply a color blend over a set of pixels.
static void Upload32 (unsigned *data, int width, int height, qboolean mipmap, qboolean picmip, qboolean lightMap, int *format, int *pUploadWidth, int *pUploadHeight, qboolean noCompress)
Upload32.
image_t * R_CreateImage (const char *name, const byte *pic, int width, int height, qboolean mipmap, qboolean allowPicmip, int wrapClampMode)
This is the only way any image_t are created.
void R_LoadImage (const char *name, byte **pic, int *width, int *height)
Loads any of the supported image types into a cannonical 32 bit format.
image_t * R_FindImageFile (const char *name, qboolean mipmap, qboolean allowPicmip, int glWrapClampMode, qboolean lightmap)
Finds or loads the given image.
static void R_CreateDlightImage (void)
R_CreateDlightImage.
static void R_CreateFogImage (void)
R_CreateFogImage.
static void R_CreateDefaultImage (void)
R_CreateDefaultImage.
void R_CreateBuiltinImages (void)
R_CreateBuiltinImages.
void R_SetColorMappings (void)
R_SetColorMappings.
void R_InitImages (void)
R_InitImages.
void R_DeleteTextures (void)
R_DeleteTextures.
static char * CommaParse (char **data_p)
This is unfortunate, but the skin files aren't compatable with our normal parsing rules.
qboolean RE_GetSkinModel (qhandle_t skinid, const char *type, char *name)
RE_GetSkinModel.
qhandle_t RE_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
RE_GetShaderFromModel.
qhandle_t RE_RegisterSkin (const char *name)
RE_RegisterSkin.
void R_InitSkins (void)
R_InitSkins.
skin_t * R_GetSkinByHandle (qhandle_t hSkin)
R_GetSkinByHandle.
void R_SkinList_f (void)
R_SkinList_f.
void * R_CacheImageAlloc (int size)
This will only get called to allocate the image_t structures, not that actual image pixels.
void R_CacheImageFreeAll ()
R_CacheImageFreeAll.
void R_CacheImageFree (void *ptr)
R_CacheImageFree.
qboolean R_TouchImage (image_t *inImage)
Remove this image from the backupHashTable and make sure it doesn't get overwritten.
void R_PurgeImage (image_t *image)
R_PurgeImage.
void R_PurgeBackupImages (int purgeCount)
Can specify the number of Images to purge this call (used for background purging)
void R_BackupImages (void)
R_BackupImages.
image_t * R_FindCachedImage (const char *name, int hash)
R_FindCachedImage.
int R_GetTextureId (const char *name)
R_GetTextureId.
void R_LoadCacheImages (void)
R_LoadCacheImages.
Variables
static byte s_intensitytable [256]
static unsigned char s_gammatable [256]
int gl_filter_min = GL_LINEAR_MIPMAP_NEAREST
int gl_filter_max = GL_LINEAR
static image_t * hashTable [FILE_HASH_SIZE]
int imageBufferSize [BUFFER_MAX_TYPES] = { 0, 0, 0 }
void * imageBufferPtr [BUFFER_MAX_TYPES] = { NULL, NULL, NULL }
textureMode_t modes []
byte mipBlendColors [16][4]
static imageExtToLoaderMap_t imageLoaders []
Note that the ordering indicates the order of preference used when there are multiple images of different formats available.
static int numImageLoaders = sizeof(imageLoaders) / sizeof(imageLoaders[0])
static int numBackupImages = 0
static image_t * backupHashTable [FILE_HASH_SIZE]
Macro Definition Documentation
#define DEFAULT_SIZE 16
Definition at line 1268 of file tr_image.c.
Referenced by R_CreateBuiltinImages(), and R_CreateDefaultImage().
#define DLIGHT_SIZE 16
Definition at line 1168 of file tr_image.c.
Referenced by R_CreateDlightImage().
#define FILE_HASH_SIZE 4096
Definition at line 43 of file tr_image.c.
Referenced by R_CacheImageFreeAll(), and R_PurgeBackupImages().
#define FOG_S 16
Definition at line 1204 of file tr_image.c.
Referenced by R_CreateFogImage().
#define FOG_T 16
Definition at line 1205 of file tr_image.c.
Referenced by R_CreateFogImage().
#define generateHashValue (fname) Q_GenerateHashValue(fname, FILE_HASH_SIZE, qfalse, qtrue);
Definition at line 45 of file tr_image.c.
Referenced by R_CreateImage(), R_FindImageFile(), and RE_GetShaderFromModel().
#define R_IMAGE_BUFFER_SIZE (512 * 512 * 4)
Definition at line 52 of file tr_image.c.
Referenced by R_GetImageBuffer().
Function Documentation
static char* CommaParse (char ** data_p) static
This is unfortunate, but the skin files aren't compatable with our normal parsing rules.
Parameters
[out] data_p
Returns
Definition at line 1507 of file tr_image.c.
Referenced by RE_RegisterSkin().
void GL_TextureMode (const char * string)
GL_TextureMode.
Parameters
[in] string
Definition at line 145 of file tr_image.c.
Referenced by GL_SetDefaultState(), and RE_BeginFrame().
void R_BackupImages (void)
R_BackupImages.
Definition at line 2143 of file tr_image.c.
Referenced by RE_Shutdown().
static void R_BlendOverTexture (byte * data, int pixelCount, byte blend[4]) static
Apply a color blend over a set of pixels.
Parameters
data
pixelCount
blend
Definition at line 526 of file tr_image.c.
Referenced by Upload32().
void* R_CacheImageAlloc (int size)
This will only get called to allocate the image_t structures, not that actual image pixels.
Parameters
[in] size
Returns
Definition at line 1957 of file tr_image.c.
Referenced by R_CreateImage().
void R_CacheImageFree (void * ptr)
R_CacheImageFree.
Parameters
[in] ptr
Definition at line 2000 of file tr_image.c.
Referenced by R_CacheImageFreeAll(), and R_PurgeImage().
void R_CacheImageFreeAll ()
R_CacheImageFreeAll.
Note
Unused
Definition at line 1980 of file tr_image.c.
void R_CreateBuiltinImages (void)
R_CreateBuiltinImages.
Definition at line 1311 of file tr_image.c.
Referenced by R_InitImages().
static void R_CreateDefaultImage (void) static
R_CreateDefaultImage.
Definition at line 1273 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateDlightImage (void) static
R_CreateDlightImage.
Definition at line 1173 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
static void R_CreateFogImage (void) static
R_CreateFogImage.
Todo:
: the following lines are unecessary for new GL_CLAMP_TO_EDGE fog (?)
Definition at line 1210 of file tr_image.c.
Referenced by R_CreateBuiltinImages().
image_t* R_CreateImage (const char * name, const byte * pic, int width, int height, qboolean mipmap, qboolean allowPicmip, int wrapClampMode)
This is the only way any image_t are created.
Parameters
[in] name
[in] pic
[in] width
[in] height
[in] mipmap
[in] allowPicmip
[in] wrapClampMode
Returns
Definition at line 882 of file tr_image.c.
Referenced by R_CreateAttenuationXYImage(), R_CreateBuiltinImages(), R_CreateDefaultImage(), R_CreateDlightImage(), R_CreateFogImage(), R_CreateNoFalloffImage(), R_CreateRenderImageSize(), R_FindImageFile(), R_InitGamma(), R_LoadLightmaps(), R_LoadLightmapsExternal(), R_LoadLightmapsInternal(), and R_LoadScalableFont().
void R_DeleteTextures (void)
R_DeleteTextures.
Definition at line 1469 of file tr_image.c.
Referenced by RE_Shutdown().
image_t* R_FindCachedImage (const char * name, int hash)
R_FindCachedImage.
Parameters
[in] name
[in] hash
Returns
Definition at line 2181 of file tr_image.c.
Referenced by R_FindImageFile().
image_t* R_FindImageFile (const char * name, qboolean mipmap, qboolean allowPicmip, int glWrapClampMode, qboolean lightmap)
Finds or loads the given image.
Parameters
[in] name
[in] mipmap
[in] allowPicmip
[in] glWrapClampMode
[in] lightmap
Returns
NULL if it fails, not a default image.
Definition at line 1072 of file tr_image.c.
Referenced by LoadMap(), ParseSkyParms(), ParseStage(), R_FindLightmap(), R_FindShader(), R_InitImages(), R_LoadCacheImages(), and R_LoadLightmapsExternal().
void R_FreeImageBuffer (void)
R_FreeImageBuffer.
Definition at line 93 of file tr_image.c.
Referenced by R_RenderView(), and RE_Shutdown().
void R_GammaCorrect (byte * buffer, int bufSize)
R_GammaCorrect.
Parameters
[in,out] buffer
[in] bufSize
Definition at line 115 of file tr_image.c.
Referenced by R_LevelShot(), RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), RB_TakeScreenshotTGA(), and RB_TakeVideoFrameCmd().
void* R_GetImageBuffer (int size, bufferMemType_t bufferType, const char * filename)
R_GetImageBuffer.
Parameters
[in] size
[in] bufferType
[in] filename
Returns
Definition at line 64 of file tr_image.c.
Referenced by R_LoadBMP(), R_LoadJPG(), R_LoadPCX(), R_LoadPNG(), and R_LoadTGA().
skin_t* R_GetSkinByHandle (qhandle_t hSkin)
R_GetSkinByHandle.
Parameters
[in] hSkin
Returns
Definition at line 1914 of file tr_image.c.
Referenced by GetMDMSurfaceShader(), GetMDVSurfaceShader(), R_AddAnimSurfaces(), R_AddMD3Surfaces(), R_AddMD5Interactions(), R_AddMD5Surfaces(), R_AddMDCSurfaces(), and R_MDM_AddAnimSurfaces().
int R_GetTextureId (const char * name)
R_GetTextureId.
Parameters
[in] name
Returns
Definition at line 2222 of file tr_image.c.
Referenced by GetRefAPI().
void R_ImageList_f (void)
R_ImageList_f.
Definition at line 205 of file tr_image.c.
Referenced by R_Register().
void R_InitImages (void)
R_InitImages.
Definition at line 1453 of file tr_image.c.
Referenced by R_Init().
void R_InitSkins (void)
R_InitSkins.
Definition at line 1895 of file tr_image.c.
Referenced by R_Init().
void R_LightScaleTexture (unsigned * in, int inwidth, int inheight, qboolean only_gamma)
Scale up the pixel values in a texture to increase the lighting range.
Parameters
[in] in
[in] inwidth
[in] inheight
[in] only_gamma
Definition at line 364 of file tr_image.c.
Referenced by R_UploadImage(), and Upload32().
void R_LoadCacheImages (void)
R_LoadCacheImages.
Definition at line 2243 of file tr_image.c.
Referenced by R_InitImages().
void R_LoadImage (const char * name, byte ** pic, int * width, int * height)
Loads any of the supported image types into a cannonical 32 bit format.
Parameters
[in] name
[out] pic
[out] width
[out] height
Definition at line 1021 of file tr_image.c.
Referenced by ParseAddNormals(), ParseDisplaceMap(), ParseHeightMap(), ParseInvertAlpha(), ParseInvertColor(), ParseMakeAlpha(), ParseMakeIntensity(), R_CreateCubeImage(), R_FindCubeImage(), and R_FindImageFile().
static void R_MipMap (byte * in, int width, int height) static
Operates in place, quartering the size of the texture.
Parameters
[in] in
[in] width
[in] height
Definition at line 473 of file tr_image.c.
Referenced by Upload32().
static void R_MipMap2 (unsigned * in, int inWidth, int inHeight) static
Operates in place, quartering the size of the texture Proper linear filter.
Parameters
in
inWidth
inHeight
Definition at line 418 of file tr_image.c.
Referenced by R_MipMap().
void R_PurgeBackupImages (int purgeCount)
Can specify the number of Images to purge this call (used for background purging)
Parameters
[in] purgeCount
Definition at line 2097 of file tr_image.c.
Referenced by R_PurgeCache(), and R_RenderView().
void R_PurgeImage (image_t * image)
R_PurgeImage.
Parameters
[in] image
Definition at line 2073 of file tr_image.c.
Referenced by R_PurgeBackupImages().
void R_SetColorMappings (void)
R_SetColorMappings.
Definition at line 1350 of file tr_image.c.
Referenced by R_InitImages(), and RE_BeginFrame().
void R_SkinList_f (void)
R_SkinList_f.
Definition at line 1926 of file tr_image.c.
Referenced by R_Register().
int R_SumOfUsedImages (void)
R_SumOfUsedImages.
Returns
Todo:
FIXME: add this to R_ImageList_f output?
Definition at line 186 of file tr_image.c.
Referenced by R_PerformanceCounters().
qboolean R_TouchImage (image_t * inImage)
Remove this image from the backupHashTable and make sure it doesn't get overwritten.
Parameters
inImage
Returns
Definition at line 2013 of file tr_image.c.
Referenced by R_FindCachedImage(), and R_RegisterShaderImages().
qhandle_t RE_GetShaderFromModel (qhandle_t modelid, int surfnum, int withlightmap)
RE_GetShaderFromModel.
Parameters
[in] modelid
[in] surfnum
withlightmap set to '0' will create a new shader that is a copy of the one found on the model, without the lighmap stage, if the shader has a lightmap stage
Returns
A shader index for a given model's surface
Note
Only works for bmodels right now. Could modify for other models (md3's etc.)
Todo:
FIXME:
withlightmap is unused
Definition at line 1654 of file tr_image.c.
Referenced by GetRefAPI().
qboolean RE_GetSkinModel (qhandle_t skinid, const char * type, char * name)
RE_GetSkinModel.
Parameters
[in] skinid
[in] type
[in] name
Returns
Definition at line 1617 of file tr_image.c.
Referenced by GetRefAPI().
qhandle_t RE_RegisterSkin (const char * name)
RE_RegisterSkin.
Parameters
[in] name
Returns
Definition at line 1727 of file tr_image.c.
Referenced by GetRefAPI().
static void ResampleTexture (unsigned * in, int inwidth, int inheight, unsigned * out, int outwidth, int outheight) static
Used to resample images in a more general than quartering fashion.
This will only be filtered properly if the resampled size is greater than half the original size.
If a larger shrinking is needed, use the mipmap function before or after.
Parameters
[in] in
[in] inwidth
[in] inheight
[out] out
[in] outwidth
[in] outheight
Todo:
: never read
Definition at line 303 of file tr_image.c.
Referenced by Upload32().
static void Upload32 (unsigned * data, int width, int height, qboolean mipmap, qboolean picmip, qboolean lightMap, int * format, int * pUploadWidth, int * pUploadHeight, qboolean noCompress) static
Upload32.
Parameters
[in,out] data
[in] width
[in] height
[in] mipmap
[in] picmip
[in] lightMap
[out] format
[out] pUploadWidth
[out] pUploadHeight
[in] noCompress
Definition at line 573 of file tr_image.c.
Referenced by R_CreateImage().
Variable Documentation
image_t* backupHashTable[FILE_HASH_SIZE] static
Definition at line 1950 of file tr_image.c.
int gl_filter_max = GL_LINEAR
Definition at line 41 of file tr_image.c.
Referenced by GL_TextureMode(), R_LoadDDSImageData(), R_UploadImage(), and Upload32().
int gl_filter_min = GL_LINEAR_MIPMAP_NEAREST
Definition at line 40 of file tr_image.c.
Referenced by GL_TextureMode(), R_LoadDDSImageData(), R_UploadImage(), and Upload32().
image_t* hashTable[FILE_HASH_SIZE] static
Definition at line 44 of file tr_image.c.
void* imageBufferPtr[BUFFER_MAX_TYPES] = { NULL, NULL, NULL }
Definition at line 55 of file tr_image.c.
Referenced by R_FreeImageBuffer(), and R_GetImageBuffer().
int imageBufferSize[BUFFER_MAX_TYPES] = { 0, 0, 0 }
Definition at line 54 of file tr_image.c.
Referenced by R_FreeImageBuffer(), and R_GetImageBuffer().
imageLoaders static
Initial value:
=
{
    { "tga",  R_LoadTGA },
    { "jpg",  R_LoadJPG },
    { "jpeg", R_LoadJPG },
    { "png",  R_LoadPNG },
    { "pcx",  R_LoadPCX },
    { "bmp",  R_LoadBMP }
}
Note that the ordering indicates the order of preference used when there are multiple images of different formats available.
Definition at line 1001 of file tr_image.c.
byte mipBlendColors[16][4]
Initial value:
=
{
    { 0,   0,   0,   0   },
    { 255, 0,   0,   128 },
    { 0,   255, 0,   128 },
    { 0,   0,   255, 128 },
    { 255, 0,   0,   128 },
    { 0,   255, 0,   128 },
    { 0,   0,   255, 128 },
    { 255, 0,   0,   128 },
    { 0,   255, 0,   128 },
    { 0,   0,   255, 128 },
    { 255, 0,   0,   128 },
    { 0,   255, 0,   128 },
    { 0,   0,   255, 128 },
    { 255, 0,   0,   128 },
    { 0,   255, 0,   128 },
    { 0,   0,   255, 128 },
}
Definition at line 540 of file tr_image.c.
Referenced by R_UploadImage(), and Upload32().
textureMode_t modes[]
Initial value:
=
{
    { "GL_NEAREST",                GL_NEAREST,                GL_NEAREST },
    { "GL_LINEAR",                 GL_LINEAR,                 GL_LINEAR  },
    { "GL_NEAREST_MIPMAP_NEAREST", GL_NEAREST_MIPMAP_NEAREST, GL_NEAREST },
    { "GL_LINEAR_MIPMAP_NEAREST",  GL_LINEAR_MIPMAP_NEAREST,  GL_LINEAR  },
    { "GL_NEAREST_MIPMAP_LINEAR",  GL_NEAREST_MIPMAP_LINEAR,  GL_NEAREST },
    { "GL_LINEAR_MIPMAP_LINEAR",   GL_LINEAR_MIPMAP_LINEAR,   GL_LINEAR  }
}
Definition at line 131 of file tr_image.c.
Referenced by GLimp_DetectAvailableModes().
int numBackupImages = 0 static
Definition at line 1949 of file tr_image.c.
int numImageLoaders = sizeof(imageLoaders) / sizeof(imageLoaders[0]) static
Definition at line 1011 of file tr_image.c.
Referenced by R_LoadImage().
unsigned char s_gammatable[256] static
Definition at line 38 of file tr_image.c.
Referenced by R_GammaCorrect(), R_LightScaleTexture(), and R_SetColorMappings().
byte s_intensitytable[256] static
Definition at line 37 of file tr_image.c.
Referenced by R_LightScaleTexture(), and R_SetColorMappings().