ET: Legacy: src/renderer/tr_decals.c File Reference
tr_decals.c File Reference
Handles projection of decals (nee marks) onto brush model surfaces.
#include "tr_local.h"
Data Structures
struct decalVert_s
Macros
#define SIDE_FRONT 0
#define SIDE_BACK 1
#define SIDE_ON 2
Typedefs
typedef struct decalVert_s decalVert_t
Functions
static qboolean MakeTextureMatrix (vec4_t texMat[2], vec4_t projection, decalVert_t *a, decalVert_t *b, decalVert_t *c)
Generates a texture projection matrix for a triangle.
void RE_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t *points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
Creates a new decal projector from a triangle.
void R_AddModelShadow (const refEntity_t *ent)
Adds a simple shadow projector to the scene.
void RE_ClearDecals (void)
Clears decals from the world and entities.
void R_TransformDecalProjector (decalProjector_t *in, vec3_t axis[3], vec3_t origin, decalProjector_t *out)
Transforms a decal projector.
qboolean R_TestDecalBoundingBox (decalProjector_t *dp, vec3_t mins, vec3_t maxs)
R_TestDecalBoundingBox.
qboolean R_TestDecalBoundingSphere (decalProjector_t *dp, vec3_t center, float radius2)
R_TestDecalBoundingSphere.
static void ChopWindingBehindPlane (int numInPoints, vec3_t inPoints[MAX_DECAL_VERTS], int *numOutPoints, vec3_t outPoints[MAX_DECAL_VERTS], vec4_t plane, vec_t epsilon)
Clips a winding to the fragment behind the plane.
static void ProjectDecalOntoWinding (decalProjector_t *dp, int numPoints, vec3_t points[2][MAX_DECAL_VERTS], msurface_t *surf, bmodel_t *bmodel)
Projects decal onto a polygon.
static void ProjectDecalOntoTriangles (decalProjector_t *dp, msurface_t *surf, bmodel_t *bmodel)
Projects a decal onto a triangle surface (brush faces, misc_models, metasurfaces)
static void ProjectDecalOntoGrid (decalProjector_t *dp, msurface_t *surf, bmodel_t *bmodel)
Projects a decal onto a grid (patch) surface.
void R_ProjectDecalOntoSurface (decalProjector_t *dp, msurface_t *surf, bmodel_t *bmodel)
Projects a decal onto a world surface.
void R_AddDecalSurface (decal_t *decal)
Adds a decal surface to the scene.
void R_AddDecalSurfaces (bmodel_t *bmodel)
Adds decal surfaces to the scene.
void R_CullDecalProjectors (void)
Frustum culls decal projector list.
Variables
int r_numDecalProjectors
int r_firstSceneDecal
Detailed Description
Handles projection of decals (nee marks) onto brush model surfaces.
Definition in file tr_decals.c.
Macro Definition Documentation
#define SIDE_BACK 1
Definition at line 494 of file tr_decals.c.
Referenced by ChopWindingBehindPlane().
#define SIDE_FRONT 0
Definition at line 493 of file tr_decals.c.
Referenced by ChopWindingBehindPlane().
#define SIDE_ON 2
Definition at line 495 of file tr_decals.c.
Referenced by ChopWindingBehindPlane().
Typedef Documentation
typedef struct decalVert_s decalVert_t
Function Documentation
static void ChopWindingBehindPlane (int numInPoints, vec3_t inPoints[MAX_DECAL_VERTS], int * numOutPoints, vec3_t outPoints[MAX_DECAL_VERTS], vec4_t plane, vec_t epsilon) static
Clips a winding to the fragment behind the plane.
Parameters
[in] numInPoints
[in] inPoints
[out] numOutPoints
[out] outPoints
[in] plane
[in] epsilon
Definition at line 506 of file tr_decals.c.
Referenced by ProjectDecalOntoWinding().
static qboolean MakeTextureMatrix (vec4_t texMat[2], vec4_t projection, decalVert_t * a, decalVert_t * b, decalVert_t * c) static
Generates a texture projection matrix for a triangle.
Parameters
[out] texMat
[in] projection
[in] a
[in] b
[in] c
Returns
qfalse if a texture matrix cannot be created
Definition at line 57 of file tr_decals.c.
Referenced by RE_ProjectDecal().
static void ProjectDecalOntoGrid (decalProjector_t * dp, msurface_t * surf, bmodel_t * bmodel) static
Projects a decal onto a grid (patch) surface.
Parameters
[in] dp
[in] surf
[in] bmodel
Definition at line 797 of file tr_decals.c.
Referenced by R_ProjectDecalOntoSurface().
static void ProjectDecalOntoTriangles (decalProjector_t * dp, msurface_t * surf, bmodel_t * bmodel) static
Projects a decal onto a triangle surface (brush faces, misc_models, metasurfaces)
Parameters
[in] dp
[in] surf
[in] bmodel
Definition at line 772 of file tr_decals.c.
Referenced by R_ProjectDecalOntoSurface().
static void ProjectDecalOntoWinding (decalProjector_t * dp, int numPoints, vec3_t points[2][MAX_DECAL_VERTS], msurface_t * surf, bmodel_t * bmodel) static
Projects decal onto a polygon.
Parameters
[in] dp
[in] numPoints
[in] points
[in] surf
[in] bmodel
Definition at line 611 of file tr_decals.c.
Referenced by ProjectDecalOntoGrid(), and ProjectDecalOntoTriangles().
void R_AddDecalSurface (decal_t * decal)
Adds a decal surface to the scene.
Parameters
[in,out] decal
Definition at line 924 of file tr_decals.c.
Referenced by R_AddDecalSurfaces().
void R_AddDecalSurfaces (bmodel_t * bmodel)
Adds decal surfaces to the scene.
Parameters
[in] bmodel
Definition at line 987 of file tr_decals.c.
Referenced by R_AddBrushModelSurfaces(), and R_AddWorldSurfaces().
void R_AddModelShadow (const refEntity_t * ent)
Adds a simple shadow projector to the scene.
Parameters
[in] ent
Definition at line 326 of file tr_decals.c.
Referenced by RE_AddRefEntityToScene().
void R_CullDecalProjectors (void)
Frustum culls decal projector list.
Definition at line 1003 of file tr_decals.c.
Referenced by R_GenerateDrawSurfs(), and R_RenderView().
void R_ProjectDecalOntoSurface (decalProjector_t * dp, msurface_t * surf, bmodel_t * bmodel)
Projects a decal onto a world surface.
Parameters
[in] dp
[in] surf
[in] bmodel
Definition at line 834 of file tr_decals.c.
Referenced by R_AddWorldSurface().
qboolean R_TestDecalBoundingBox (decalProjector_t * dp, vec3_t mins, vec3_t maxs)
R_TestDecalBoundingBox.
Parameters
[in] dp
[in] mins
[in] maxs
Returns
qtrue if the decal projector intersects the bounding box
Definition at line 461 of file tr_decals.c.
Referenced by R_AddBrushModelSurfaces(), and R_RecursiveWorldNode().
qboolean R_TestDecalBoundingSphere (decalProjector_t * dp, vec3_t center, float radius2)
R_TestDecalBoundingSphere.
Parameters
[in] dp
[in] center
[in] radius2
Returns
qtrue if the decal projector intersects the bounding sphere
Definition at line 479 of file tr_decals.c.
Referenced by R_ProjectDecalOntoSurface().
void R_TransformDecalProjector (decalProjector_t * in, vec3_t axis[3], vec3_t origin, decalProjector_t * out)
Transforms a decal projector.
Parameters
[in] in
[in] axis
[in] origin
[out] out
Note
Non-normalized axes will screw up the plane transform
Definition at line 403 of file tr_decals.c.
Referenced by R_AddBrushModelSurfaces().
void RE_ClearDecals (void)
Clears decals from the world and entities.
Definition at line 367 of file tr_decals.c.
Referenced by GetRefAPI().
void RE_ProjectDecal (qhandle_t hShader, int numPoints, vec3_t * points, vec4_t projection, vec4_t color, int lifeTime, int fadeTime)
Creates a new decal projector from a triangle.
Projected polygons should be 3 or 4 points.
If a single point is passed in (numPoints == 1) then the decal will be omnidirectional omnidirectional decals use points[ 0 ] as center and projection[ 3 ] as radius pass in lifeTime < 0 for a temporary mark.
Parameters
[in] hShader
[in] numPoints
[in] points
[in] projection
[in] color
[in] lifeTime
[in] fadeTime
Todo:
: stale refdef time
Todo:
: support arbitrary projector st coordinates in trapcall)
Definition at line 151 of file tr_decals.c.
Referenced by GetRefAPI(), and R_AddModelShadow().
Variable Documentation
int r_firstSceneDecal
Definition at line 60 of file tr_scene.c.
Referenced by R_AddDecalSurface().
int r_numDecalProjectors
Definition at line 59 of file tr_scene.c.
Referenced by RE_ProjectDecal().