ET: Legacy: src/renderer2/tr_model_skel.h File Reference
tr_model_skel.h File Reference
#include "tr_local.h"
Functions
qboolean AddTriangleToVBOTriangleList (growList_t *vboTriangles, skelTriangle_t *tri, int *numBoneReferences, int boneReferences[MAX_BONES])
AddTriangleToVBOTriangleList.
void AddSurfaceToVBOSurfacesList (growList_t *vboSurfaces, growList_t *vboTriangles, md5Model_t *md5, md5Surface_t *surf, int skinIndex, int numBoneReferences, int boneReferences[MAX_BONES])
AddSurfaceToVBOSurfacesList.
void AddSurfaceToVBOSurfacesList2 (growList_t *vboSurfaces, growList_t *vboTriangles, growList_t *vboVertexes, md5Model_t *md5, int skinIndex, const char *materialName, int numBoneReferences, int boneReferences[MAX_BONES])
AddSurfaceToVBOSurfacesList2.
Function Documentation
void AddSurfaceToVBOSurfacesList (growList_t * vboSurfaces, growList_t * vboTriangles, md5Model_t * md5, md5Surface_t * surf, int skinIndex, int numBoneReferences, int boneReferences[MAX_BONES])
AddSurfaceToVBOSurfacesList.
Parameters
[in] vboSurfaces
[in] vboTriangles
[in] md5
[in] surf
[in] skinIndex
numBoneReferences - unused
[in] boneReferences
Definition at line 242 of file tr_model_skel.c.
Referenced by R_LoadMD5().
void AddSurfaceToVBOSurfacesList2 (growList_t * vboSurfaces, growList_t * vboTriangles, growList_t * vboVertexes, md5Model_t * md5, int skinIndex, const char * materialName, int numBoneReferences, int boneReferences[MAX_BONES])
AddSurfaceToVBOSurfacesList2.
Parameters
[in] vboSurfaces
[in] vboTriangles
[in] vboVertexes
[in] md5
[in] skinIndex
[in] materialName
numBoneReferences - unused
[in] boneReferences
Definition at line 472 of file tr_model_skel.c.
Referenced by R_LoadPSK().
qboolean AddTriangleToVBOTriangleList (growList_t * vboTriangles, skelTriangle_t * tri, int * numBoneReferences, int boneReferences[MAX_BONES])
AddTriangleToVBOTriangleList.
Parameters
[in] vboTriangles
[in] tri
[in,out] numBoneReferences
[in,out] boneReferences
Returns
Definition at line 142 of file tr_model_skel.c.
Referenced by R_LoadMD5(), R_LoadMDM(), and R_LoadPSK().