ET: Legacy: src/renderercommon/tr_common.c File Reference
tr_common.c File Reference
#include "tr_common.h"
#include "../renderer2/tr_local.h"
Macros
#define MSG_ERR_OLD_VIDEO_DRIVER
Functions
qboolean GL_CheckForExtension (const char *ext)
GL_CheckForExtension.
static qboolean GLimp_InitOpenGLContext ()
GLimp_InitOpenGLContext.
void GLAPIENTRY Glimp_DebugCallback (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *message, const GLvoid *userParam)
Glimp_DebugCallback.
static qboolean GLimp_CheckForVersionExtension (const char *ext, int coresince, qboolean required, cvar_t *var)
GLimp_CheckForVersionExtension.
static void GLimp_InitExtensionsR2 (void)
GLimp_InitExtensionsR2.
void Glimp_ClearScreen (void)
Glimp_ClearScreen.
int RE_InitOpenGlSubsystems (void)
RE_InitOpenGlSubsystems.
void RE_InitOpenGl (void)
RE_InitOpenGl.
void R_DoGLimpShutdown (void)
R_DoGLimpShutdown.
void R_PrintLongString (const char *string)
Workaround for ri.Printf's 1024 characters buffer limit.
Macro Definition Documentation
#define MSG_ERR_OLD_VIDEO_DRIVER
Value:
"\nET: Legacy with OpenGL 3.x renderer can not run on this "                             \
    "machine since it is missing one or more required OpenGL "                             \
    "extensions. Please update your video card drivers and try again.\n"
Definition at line 77 of file tr_common.c.
Referenced by GLimp_CheckForVersionExtension().
Function Documentation
qboolean GL_CheckForExtension (const char * ext)
GL_CheckForExtension.
Parameters
[in] ext
Returns
Definition at line 50 of file tr_common.c.
Referenced by GLimp_CheckForVersionExtension().
static qboolean GLimp_CheckForVersionExtension (const char * ext, int coresince, qboolean required, cvar_t * var) static
GLimp_CheckForVersionExtension.
Parameters
[in] ext
[in] coresince
[in] required
[in] var
Returns
Definition at line 180 of file tr_common.c.
Referenced by GLimp_InitExtensionsR2().
void Glimp_ClearScreen (void)
Glimp_ClearScreen.
Definition at line 547 of file tr_common.c.
Referenced by RE_InitOpenGl().
void GLAPIENTRY Glimp_DebugCallback (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * message, const GLvoid * userParam)
Glimp_DebugCallback.
Parameters
source - unused
type - unused
id - unused
severity - unused
length - unused
[in] message
userParam - unused
Definition at line 167 of file tr_common.c.
Referenced by GLimp_InitExtensionsR2().
static void GLimp_InitExtensionsR2 (void) static
GLimp_InitExtensionsR2.
Definition at line 223 of file tr_common.c.
Referenced by RE_InitOpenGl().
static qboolean GLimp_InitOpenGLContext () static
GLimp_InitOpenGLContext.
Returns
Definition at line 86 of file tr_common.c.
Referenced by RE_InitOpenGlSubsystems().
void R_DoGLimpShutdown (void)
R_DoGLimpShutdown.
Definition at line 640 of file tr_common.c.
Referenced by RE_Shutdown().
void R_PrintLongString (const char * string)
Workaround for ri.Printf's 1024 characters buffer limit.
Parameters
[in] string
Definition at line 654 of file tr_common.c.
Referenced by GfxInfo_f().
void RE_InitOpenGl (void)
RE_InitOpenGl.
Definition at line 599 of file tr_common.c.
Referenced by GetRefAPI().
int RE_InitOpenGlSubsystems (void)
RE_InitOpenGlSubsystems.
Returns
Definition at line 563 of file tr_common.c.
Referenced by GetRefAPI().