ET: Legacy: src/renderer2/tr_fog.c File Reference
tr_fog.c File Reference
#include "tr_local.h"
Functions
void RB_Fog (glfog_t *curfog)
RB_Fog.
void RB_FogOff (void)
Allow disabling fog temporarily.
void RB_FogOn (void)
RB_FogOn.
void RE_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
RE_SetFog.
void R_SetFrameFog (void)
R_SetFrameFog.
void RE_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
RE_SetGlobalFog.
Variables
static qboolean fogIsOn = qfalse
Function Documentation
void R_SetFrameFog (void)
R_SetFrameFog.
Todo:
: since this is the most common occurance, diff first and only set changes
Definition at line 259 of file tr_fog.c.
void RB_Fog (glfog_t * curfog)
RB_Fog.
Parameters
[in,out] curfog
Definition at line 44 of file tr_fog.c.
void RB_FogOff (void)
Allow disabling fog temporarily.
Definition at line 104 of file tr_fog.c.
Referenced by RB_Fog(), and RB_FogOn().
void RB_FogOn (void)
RB_FogOn.
Definition at line 121 of file tr_fog.c.
Referenced by RB_Fog().
void RE_SetFog (int fogvar, int var1, int var2, float r, float g, float b, float density)
RE_SetFog.
Parameters
[in] fogvar
[in] var1
[in] var2
[in] r
[in] g
[in] b
[in] density
Note
if fogvar == FOG_CMD_SWITCHFOG { fogvar is the command var1 is the fog to switch to var2 is the time to transition } else { fogvar is the fog that's being set var1 is the near fog z value var2 is the far fog z value rgb = color density is density, and is used to derive the values of 'mode', 'drawsky', and 'clearscreen' }
Todo:
: handle transition if there is no FOG_MAP fog
Definition at line 185 of file tr_fog.c.
Referenced by GetRefAPI(), ParseShader(), ParseShaderR1(), and RE_LoadWorldMap().
void RE_SetGlobalFog (qboolean restore, int duration, float r, float g, float b, float depthForOpaque)
RE_SetGlobalFog.
Parameters
[in] restore flag can be used to restore the original level fog
[in] duration can be set to fade over a certain period
[in] r colour
[in] g colour
[in] b colour
[in] depthForOpaque is depth for opaque
Definition at line 415 of file tr_fog.c.
Variable Documentation
qboolean fogIsOn = qfalse static
Definition at line 38 of file tr_fog.c.
Referenced by RB_FogOff(), and RB_FogOn().