ET: Legacy: src/renderer2/tr_model_psk.c File Reference
tr_model_psk.c File Reference
Unreal Engine 3 .psk model loading and caching.
#include "tr_local.h"
#include "tr_model_skel.h"
Macros
#define DeallocAll()
Functions
static void GetChunkHeader (memStream_t *s, axChunkHeader_t *chunkHeader)
GetChunkHeader.
static void PrintChunkHeader (axChunkHeader_t *chunkHeader)
PrintChunkHeader.
static void GetBone (memStream_t *s, axBone_t *bone)
GetBone.
static int CompareTrianglesByMaterialIndex (const void *a, const void *b)
CompareTrianglesByMaterialIndex.
qboolean R_LoadPSK (model_t *mod, void *buffer, int bufferSize, const char *modName)
R_LoadPSK.
Detailed Description
Unreal Engine 3 .psk model loading and caching.
Definition in file tr_model_psk.c.
Macro Definition Documentation
#define DeallocAll ()
Value:
Com_Dealloc(materials); \
    Com_Dealloc(points); \
    Com_Dealloc(vertexes); \
    Com_Dealloc(triangles); \
    Com_Dealloc(refBones); \
    Com_Dealloc(axWeights); \
    FreeMemStream(stream);
Referenced by R_LoadPSK().
Function Documentation
static int CompareTrianglesByMaterialIndex (const void * a, const void * b) static
CompareTrianglesByMaterialIndex.
Parameters
[in] a
[in] b
Returns
Definition at line 106 of file tr_model_psk.c.
Referenced by R_LoadPSK().
static void GetBone (memStream_t * s, axBone_t * bone) static
GetBone.
Parameters
[in] s
[out] bone
Definition at line 79 of file tr_model_psk.c.
Referenced by R_LoadPSK().
static void GetChunkHeader (memStream_t * s, axChunkHeader_t * chunkHeader) static
GetChunkHeader.
Parameters
[in] s
[out] chunkHeader
Definition at line 45 of file tr_model_psk.c.
Referenced by R_LoadPSK().
static void PrintChunkHeader (axChunkHeader_t * chunkHeader) static
PrintChunkHeader.
Parameters
[in] chunkHeader
Definition at line 63 of file tr_model_psk.c.
Referenced by R_LoadPSK().
qboolean R_LoadPSK (model_t * mod, void * buffer, int bufferSize, const char * modName)
R_LoadPSK.
Parameters
[in,out] mod
[in,out] buffer
[in] bufferSize
[in] modName
Returns
Todo:
?
Todo:
skinIndex
Definition at line 134 of file tr_model_psk.c.