ET: Legacy: src/renderer/tr_gamma.c File Reference
tr_gamma.c File Reference
Functions that are not called every frame.
#include "tr_local.h"
Data Structures
struct shaderProgram_s
Typedefs
typedef struct shaderProgram_s shaderProgram_t
shaderProgram_t represents a pair of one GLSL vertex and one GLSL fragment shader
Functions
static void R_BuildGammaProgram (void)
R_BuildGammaProgram.
void R_ScreenGamma (void)
R_ScreenGamma.
void R_InitGamma (void)
R_InitGamma.
void R_ShutdownGamma (void)
R_ShutdownGamma.
Variables
image_t * screenImage = NULL
shaderProgram_t gammaProgram
const char * simpleGammaVert
const char * simpleGammaFrag
Detailed Description
Functions that are not called every frame.
Definition in file tr_gamma.c.
Typedef Documentation
shaderProgram_t
shaderProgram_t represents a pair of one GLSL vertex and one GLSL fragment shader
Function Documentation
static void R_BuildGammaProgram (void) static
R_BuildGammaProgram.
Definition at line 67 of file tr_gamma.c.
Referenced by R_InitGamma().
void R_InitGamma (void)
R_InitGamma.
Todo:
: fatal?
Definition at line 180 of file tr_gamma.c.
Referenced by R_Init().
void R_ScreenGamma (void)
R_ScreenGamma.
Definition at line 137 of file tr_gamma.c.
Referenced by RB_GammaScreen().
void R_ShutdownGamma (void)
R_ShutdownGamma.
Definition at line 219 of file tr_gamma.c.
Referenced by RE_Shutdown().
Variable Documentation
shaderProgram_t gammaProgram
Definition at line 49 of file tr_gamma.c.
image_t* screenImage = NULL
Definition at line 48 of file tr_gamma.c.
const char* simpleGammaFrag
Initial value:
= "#version 110\n"
                              "uniform sampler2D u_CurrentMap;\n"
                              "uniform float u_gamma;\n"
                              "void main(void) {\n"
                              "gl_FragColor = vec4(pow(texture2D(u_CurrentMap, vec2(gl_TexCoord[0])).rgb, vec3(1.0 / u_gamma)), 1);\n"
                              "}\n"
Definition at line 57 of file tr_gamma.c.
Referenced by R_BuildGammaProgram().
const char* simpleGammaVert
Initial value:
= "#version 110\n"
                              "void main(void) {\n"
                              "gl_Position = gl_Vertex;\n"
                              "gl_TexCoord[0] = gl_MultiTexCoord0;\n"
                              "}\n"
Definition at line 51 of file tr_gamma.c.
Referenced by R_BuildGammaProgram().