ET: Legacy: src/renderer/tr_light.c File Reference
tr_light.c File Reference
#include "tr_local.h"
Macros
#define DLIGHT_AT_RADIUS 16
At the edge of a dlight's influence, this amount of light will be added.
#define DLIGHT_MINIMUM_RADIUS 16
Never calculate a range less than this to prevent huge light numbers.
Functions
void R_TransformDlights (int count, dlight_t *dl, orientationr_t *orientation)
Transforms the origins of an array of dlights.
void R_CullDlights (void)
Frustum culls dynamic lights.
void R_DlightBmodel (bmodel_t *bmodel)
Determine which dynamic lights may effect this bmodel.
static void R_SetupEntityLightingGrid (trRefEntity_t *ent)
R_SetupEntityLightingGrid.
static void LogLight (trRefEntity_t *ent)
LogLight.
void R_SetupEntityLighting (const trRefdef_t *refdef, trRefEntity_t *ent)
Calculates all the lighting values that will be used by the Calc_* functions.
Variables
cvar_t * r_ambientScale
cvar_t * r_directedScale
cvar_t * r_debugLight
Macro Definition Documentation
#define DLIGHT_AT_RADIUS 16
At the edge of a dlight's influence, this amount of light will be added.
Definition at line 38 of file tr_light.c.
#define DLIGHT_MINIMUM_RADIUS 16
Never calculate a range less than this to prevent huge light numbers.
Definition at line 41 of file tr_light.c.
Function Documentation
static void LogLight (trRefEntity_t * ent) static
LogLight.
Parameters
ent
Definition at line 325 of file tr_light.c.
Referenced by R_SetupEntityLighting().
void R_CullDlights (void)
Frustum culls dynamic lights.
Definition at line 69 of file tr_light.c.
Referenced by R_GenerateDrawSurfs().
void R_DlightBmodel (bmodel_t * bmodel)
Determine which dynamic lights may effect this bmodel.
Parameters
[in] bmodel
Definition at line 103 of file tr_light.c.
Referenced by R_AddBrushModelSurfaces().
void R_SetupEntityLighting (const trRefdef_t * refdef, trRefEntity_t * ent)
Calculates all the lighting values that will be used by the Calc_* functions.
Parameters
[in] refdef
[in,out] ent
Definition at line 363 of file tr_light.c.
Referenced by R_AddAnimSurfaces(), R_AddBSPModelSurfaces(), R_AddMD3Surfaces(), R_AddMD5Surfaces(), R_AddMDCSurfaces(), R_AddMDVSurfaces(), and R_MDM_AddAnimSurfaces().
static void R_SetupEntityLightingGrid (trRefEntity_t * ent) static
R_SetupEntityLightingGrid.
Parameters
[in,out] ent
Definition at line 185 of file tr_light.c.
Referenced by R_SetupEntityLighting().
void R_TransformDlights (int count, dlight_t * dl, orientationr_t * orientation)
Transforms the origins of an array of dlights.
Used by both the front end (for DlightBmodel) and the back end (before doing the lighting calculation)
Parameters
[in] count
[out] dl
[in] orientation
Definition at line 52 of file tr_light.c.
Referenced by R_DlightBmodel(), and RB_RenderDrawSurfList().
Variable Documentation
cvar_t* r_ambientScale
Definition at line 146 of file tr_init.c.
Referenced by R_DlightBmodel(), and R_SetupEntityLighting().
cvar_t* r_debugLight
Definition at line 148 of file tr_init.c.
Referenced by R_DlightBmodel(), and R_SetupEntityLighting().
cvar_t* r_directedScale
Definition at line 147 of file tr_init.c.
Referenced by R_DlightBmodel().