ET: Legacy: src/renderer/tr_cmesh.c File Reference
tr_cmesh.c File Reference
Compressed triangle model functions.
#include "tr_local.h"
Functions
static float ProjectRadius (float r, vec3_t location)
ProjectRadius.
static int R_CullModel (mdcHeader_t *header, trRefEntity_t *ent)
R_CullModel.
static int R_ComputeLOD (trRefEntity_t *ent)
R_ComputeLOD.
static int R_ComputeFogNum (mdcHeader_t *header, trRefEntity_t *ent)
R_ComputeFogNum.
void R_AddMDCSurfaces (trRefEntity_t *ent)
R_AddMDCSurfaces.
Detailed Description
Compressed triangle model functions.
This is ripped from tr_mesh.c, and converted to use the compressed mesh format
Definition in file tr_cmesh.c.
Function Documentation
static float ProjectRadius (float r, vec3_t location) static
ProjectRadius.
Parameters
[in] r
[in] location
Returns
Definition at line 46 of file tr_cmesh.c.
Referenced by R_ComputeLOD().
void R_AddMDCSurfaces (trRefEntity_t * ent)
R_AddMDCSurfaces.
Parameters
[in,out] ent
Definition at line 323 of file tr_cmesh.c.
Referenced by R_AddEntitySurfaces().
static int R_ComputeFogNum (mdcHeader_t * header, trRefEntity_t * ent) static
R_ComputeFogNum.
Parameters
[in] header
[in] ent
Returns
Todo:
: non-normalized axis issues
Definition at line 281 of file tr_cmesh.c.
Referenced by R_AddMDCSurfaces().
static int R_ComputeLOD (trRefEntity_t * ent) static
R_ComputeLOD.
Parameters
[in] ent
Returns
Definition at line 192 of file tr_cmesh.c.
Referenced by R_AddMDCSurfaces().
static int R_CullModel (mdcHeader_t * header, trRefEntity_t * ent) static
R_CullModel.
Parameters
[in] header
[in] ent
Returns
Definition at line 103 of file tr_cmesh.c.
Referenced by R_AddMDCSurfaces().