ET: Legacy: src/ui/ui_atoms.c File Reference
ui_atoms.c File Reference
User interface building blocks and support functions.
#include "ui_local.h"
Functions
void QDECL Com_DPrintf (const char *fmt,...)
Com_DPrintf.
void QDECL Com_Error (int code, const char *error,...)
Com_Error.
void QDECL Com_Printf (const char *msg,...)
Com_Printf.
char * UI_Argv (int arg)
UI_Argv.
char * UI_Cvar_VariableString (const char *varName)
UI_Cvar_VariableString.
static void UI_Cache_f (void)
UI_Cache_f.
qboolean UI_ConsoleCommand (int realTime)
UI_ConsoleCommand.
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
Adjusted for resolution and screen aspect ratio.
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
UI_DrawHandlePic.
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_DrawTopBottom (float x, float y, float w, float h)
UI_DrawTopBottom.
Detailed Description
User interface building blocks and support functions.
Definition in file ui_atoms.c.
Function Documentation
void QDECL Com_DPrintf (const char * fmt, ...)
Com_DPrintf.
A Com_Printf that only shows up if the "developer" cvar is set.
Parameters
[in] fmt
Definition at line 42 of file ui_atoms.c.
void QDECL Com_Error (int code, const char * error, ...)
Com_Error.
Parameters
code - unused
[in] error
Definition at line 66 of file ui_atoms.c.
void QDECL Com_Printf (const char * msg, ...)
Com_Printf.
Parameters
[in] msg
Definition at line 82 of file ui_atoms.c.
Referenced by Com_DPrintf().
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Adjusted for resolution and screen aspect ratio.
Parameters
[in] x
[in] y
[in] w
[in] h
Definition at line 211 of file ui_atoms.c.
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), Text_PaintChar(), Text_PaintCharExt(), UI_DrawHandlePic(), UI_DrawMapPreview(), UI_DrawTopBottom(), and UI_FillRect().
char* UI_Argv (int arg)
UI_Argv.
Parameters
[in] arg
Returns
Definition at line 99 of file ui_atoms.c.
Referenced by UI_ConsoleCommand().
static void UI_Cache_f (void) static
UI_Cache_f.
Definition at line 128 of file ui_atoms.c.
Referenced by UI_ConsoleCommand().
qboolean UI_ConsoleCommand (int realTime)
UI_ConsoleCommand.
Parameters
[in] realTime
Returns
Definition at line 138 of file ui_atoms.c.
Referenced by vmMain().
char* UI_Cvar_VariableString (const char * varName)
UI_Cvar_VariableString.
Parameters
[in] varName
Returns
Definition at line 113 of file ui_atoms.c.
Referenced by UI_ClanName_HandleKey(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawClanName(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawOpponentName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawSelectedPlayer(), UI_DrawServerRefreshDate(), UI_DrawTeamName(), UI_Load(), UI_NextOpponent(), UI_OwnerDrawWidth(), UI_PriorOpponent(), UI_RunMenuScript(), UI_SetActiveMenu(), UI_StartServerRefresh(), UI_StopCinematic(), UI_TeamName_HandleKey(), and UI_Update().
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
UI_DrawHandlePic.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] hShader
Definition at line 254 of file ui_atoms.c.
Referenced by UI_DrawCampaignMapPreview(), UI_DrawCampaignPreview(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawCrosshair(), UI_DrawEffects(), UI_DrawMapPreview(), UI_DrawMissionBriefingMap(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_Init(), and UI_Refresh().
void UI_DrawTopBottom (float x, float y, float w, float h)
UI_DrawTopBottom.
Parameters
[in] x
[in] y
[in] w
[in] h
Note
Unused
Definition at line 328 of file ui_atoms.c.
void UI_FillRect (float x, float y, float width, float height, const float * color)
Coordinates are 640*480 virtual values
Parameters
[in] x
[in] y
[in] width
[in] height
[in] color
Definition at line 309 of file ui_atoms.c.
Referenced by UI_DrawMapPreview(), UI_Init(), and UI_Refresh().