ET: Legacy: src/ui/ui_parse.c File Reference
ui_parse.c File Reference
String allocation/managment.
#include "ui_shared.h"
#include "ui_local.h"
Data Structures
struct keywordHash_s
Macros
#define KEYWORDHASH_SIZE 512
Typedefs
typedef struct keywordHash_s keywordHash_t
Functions
void Tooltip_ComputePosition (itemDef_t *item)
Tooltip_ComputePosition.
void Item_ValidateTypeData (itemDef_t *item)
Item_ValidateTypeData.
qboolean Item_ValidateTooltipData (itemDef_t *item)
Item_ValidateTooltipData.
qboolean Float_Parse (char **p, float *f)
Float_Parse.
qboolean Color_Parse (char **p, vec4_t *c)
Color_Parse.
qboolean Int_Parse (char **p, int *i)
Int_Parse.
qboolean Rect_Parse (char **p, rectDef_t *r)
Rect_Parse.
qboolean String_Parse (char **p, const char **out)
String_Parse.
qboolean PC_String_ParseTranslate (int handle, const char **out)
Same as PC_String_Parse except it uses a trap call to client's gettext translation function.
qboolean PC_Char_Parse (int handle, char *out)
PC_Char_Parse.
qboolean PC_Script_Parse (int handle, const char **out)
PC_Script_Parse.
int KeywordHash_Key (const char *keyword)
KeywordHash_Key.
void KeywordHash_Add (keywordHash_t *table[], keywordHash_t *key)
KeywordHash_Add.
keywordHash_t * KeywordHash_Find (keywordHash_t *table[], const char *keyword)
KeywordHash_Find.
qboolean ItemParse_name (itemDef_t *item, int handle)
ItemParse_name.
qboolean ItemParse_focusSound (itemDef_t *item, int handle)
ItemParse_focusSound.
qboolean ItemParse_text (itemDef_t *item, int handle)
ItemParse_text.
qboolean ItemParse_textfile (itemDef_t *item, int handle)
Read an external textfile into item->text.
qboolean ItemParse_group (itemDef_t *item, int handle)
ItemParse_group.
qboolean ItemParse_asset_model (itemDef_t *item, int handle)
ItemParse_asset_model.
qboolean ItemParse_asset_shader (itemDef_t *item, int handle)
ItemParse_asset_shader.
qboolean ItemParse_model_origin (itemDef_t *item, int handle)
ItemParse_model_origin.
qboolean ItemParse_model_fovx (itemDef_t *item, int handle)
ItemParse_model_fovx.
qboolean ItemParse_model_fovy (itemDef_t *item, int handle)
ItemParse_model_fovy.
qboolean ItemParse_model_rotation (itemDef_t *item, int handle)
ItemParse_model_rotation.
qboolean ItemParse_model_angle (itemDef_t *item, int handle)
ItemParse_model_angle.
qboolean ItemParse_model_animplay (itemDef_t *item, int handle)
ItemParse_model_animplay.
qboolean ItemParse_rect (itemDef_t *item, int handle)
ItemParse_rect.
qboolean ItemParse_origin (itemDef_t *item, int handle)
ItemParse_origin.
qboolean ItemParse_style (itemDef_t *item, int handle)
ItemParse_style.
qboolean ItemParse_decoration (itemDef_t *item, int handle)
ItemParse_decoration.
qboolean ItemParse_textasint (itemDef_t *item, int handle)
ItemParse_textasint.
qboolean ItemParse_textasfloat (itemDef_t *item, int handle)
ItemParse_textasfloat.
qboolean ItemParse_notselectable (itemDef_t *item, int handle)
ItemParse_notselectable.
qboolean ItemParse_wrapped (itemDef_t *item, int handle)
ItemParse_wrapped.
qboolean ItemParse_autowrapped (itemDef_t *item, int handle)
ItemParse_autowrapped.
qboolean ItemParse_bitflag (itemDef_t *item, int handle)
ItemParse_bitflag.
qboolean ItemParse_horizontalscroll (itemDef_t *item, int handle)
ItemParse_horizontalscroll.
qboolean ItemParse_type (itemDef_t *item, int handle)
ItemParse_type.
qboolean ItemParse_elementwidth (itemDef_t *item, int handle)
Used for listbox image elements.
qboolean ItemParse_elementheight (itemDef_t *item, int handle)
Used for listbox image elements.
qboolean ItemParse_feeder (itemDef_t *item, int handle)
ItemParse_feeder.
qboolean ItemParse_elementtype (itemDef_t *item, int handle)
Used to specify what type of elements a listbox contains.
qboolean ItemParse_columns (itemDef_t *item, int handle)
Sets a number of columns and an x pos and width per..
qboolean ItemParse_border (itemDef_t *item, int handle)
ItemParse_border.
qboolean ItemParse_bordersize (itemDef_t *item, int handle)
ItemParse_bordersize.
qboolean ItemParse_visible (itemDef_t *item, int handle)
ItemParse_visible.
qboolean ItemParse_ownerdraw (itemDef_t *item, int handle)
ItemParse_ownerdraw.
qboolean ItemParse_align (itemDef_t *item, int handle)
ItemParse_align.
qboolean ItemParse_textalign (itemDef_t *item, int handle)
ItemParse_textalign.
qboolean ItemParse_textalignx (itemDef_t *item, int handle)
ItemParse_textalignx.
qboolean ItemParse_textaligny (itemDef_t *item, int handle)
ItemParse_textaligny.
qboolean ItemParse_textscale (itemDef_t *item, int handle)
ItemParse_textscale.
qboolean ItemParse_textstyle (itemDef_t *item, int handle)
ItemParse_textstyle.
qboolean ItemParse_textfont (itemDef_t *item, int handle)
Forcing a font for a given item.
qboolean ItemParse_backcolor (itemDef_t *item, int handle)
ItemParse_backcolor.
qboolean ItemParse_forecolor (itemDef_t *item, int handle)
ItemParse_forecolor.
qboolean ItemParse_bordercolor (itemDef_t *item, int handle)
ItemParse_bordercolor.
qboolean ItemParse_outlinecolor (itemDef_t *item, int handle)
ItemParse_outlinecolor.
qboolean ItemParse_background (itemDef_t *item, int handle)
ItemParse_background.
qboolean ItemParse_cinematic (itemDef_t *item, int handle)
ItemParse_cinematic.
qboolean ItemParse_doubleClick (itemDef_t *item, int handle)
ItemParse_doubleClick.
qboolean ItemParse_onTab (itemDef_t *item, int handle)
ItemParse_onTab.
qboolean ItemParse_onEsc (itemDef_t *item, int handle)
ItemParse_onEsc.
qboolean ItemParse_onEnter (itemDef_t *item, int handle)
ItemParse_onEnter.
qboolean ItemParse_onPaste (itemDef_t *item, int handle)
ItemParse_onPaste.
qboolean ItemParse_contextMenu (itemDef_t *item, int handle)
ItemParse_contextMenu.
qboolean ItemParse_onFocus (itemDef_t *item, int handle)
ItemParse_onFocus.
qboolean ItemParse_leaveFocus (itemDef_t *item, int handle)
ItemParse_leaveFocus.
qboolean ItemParse_mouseEnter (itemDef_t *item, int handle)
ItemParse_mouseEnter.
qboolean ItemParse_mouseExit (itemDef_t *item, int handle)
ItemParse_mouseExit.
qboolean ItemParse_mouseEnterText (itemDef_t *item, int handle)
ItemParse_mouseEnterText.
qboolean ItemParse_mouseExitText (itemDef_t *item, int handle)
ItemParse_mouseExitText.
qboolean ItemParse_action (itemDef_t *item, int handle)
ItemParse_action.
qboolean ItemParse_accept (itemDef_t *item, int handle)
ItemParse_accept.
qboolean ItemParse_special (itemDef_t *item, int handle)
ItemParse_special.
qboolean ItemParse_cvarTest (itemDef_t *item, int handle)
ItemParse_cvarTest.
qboolean ItemParse_cvar (itemDef_t *item, int handle)
ItemParse_cvar.
qboolean ItemParse_maxChars (itemDef_t *item, int handle)
ItemParse_maxChars.
qboolean ItemParse_maxPaintChars (itemDef_t *item, int handle)
ItemParse_maxPaintChars.
qboolean ItemParse_cvarFloat (itemDef_t *item, int handle)
ItemParse_cvarFloat.
qboolean ItemParse_cvarStrList (itemDef_t *item, int handle)
ItemParse_cvarStrList.
qboolean ItemParse_cvarFloatList (itemDef_t *item, int handle)
ItemParse_cvarFloatList.
qboolean ItemParse_cvarListUndefined (itemDef_t *item, int handle)
ItemParse_cvarListUndefined.
qboolean ParseColorRange (itemDef_t *item, int handle, int type)
ParseColorRange.
qboolean ItemParse_addColorRangeRel (itemDef_t *item, int handle)
ItemParse_addColorRangeRel.
qboolean ItemParse_addColorRange (itemDef_t *item, int handle)
ItemParse_addColorRange.
qboolean ItemParse_ownerdrawFlag (itemDef_t *item, int handle)
ItemParse_ownerdrawFlag.
qboolean ItemParse_enableCvar (itemDef_t *item, int handle)
ItemParse_enableCvar.
qboolean ItemParse_disableCvar (itemDef_t *item, int handle)
ItemParse_disableCvar.
qboolean ItemParse_noToggle (itemDef_t *item, int handle)
ItemParse_noToggle.
qboolean ItemParse_showCvar (itemDef_t *item, int handle)
ItemParse_showCvar.
qboolean ItemParse_hideCvar (itemDef_t *item, int handle)
ItemParse_hideCvar.
qboolean ItemParse_execKey (itemDef_t *item, int handle)
ItemParse_execKey.
qboolean ItemParse_settingDisabled (itemDef_t *item, int handle)
Server setting tags.
qboolean ItemParse_settingEnabled (itemDef_t *item, int handle)
ItemParse_settingEnabled.
qboolean ItemParse_tooltip (itemDef_t *item, int handle)
ItemParse_tooltip.
qboolean ItemParse_tooltipalignx (itemDef_t *item, int handle)
ItemParse_tooltipalignx.
qboolean ItemParse_tooltipaligny (itemDef_t *item, int handle)
ItemParse_tooltipaligny.
qboolean ItemParse_voteFlag (itemDef_t *item, int handle)
ItemParse_voteFlag.
qboolean ItemParse_scrollColor (itemDef_t *item, int handle)
ItemParse_scrollColor.
qboolean ItemParse_sliderColor (itemDef_t *item, int handle)
ItemParse_sliderColor.
void Item_SetupKeywordHash (void)
Item_SetupKeywordHash.
qboolean Item_Parse (int handle, itemDef_t *item)
Item_Parse.
void Item_InitControls (itemDef_t *item)
Init's special control types.
qboolean MenuParse_name (itemDef_t *item, int handle)
MenuParse_name.
qboolean MenuParse_fullscreen (itemDef_t *item, int handle)
MenuParse_fullscreen.
qboolean MenuParse_rect (itemDef_t *item, int handle)
MenuParse_rect.
qboolean MenuParse_style (itemDef_t *item, int handle)
MenuParse_style.
qboolean MenuParse_visible (itemDef_t *item, int handle)
MenuParse_visible.
qboolean MenuParse_onOpen (itemDef_t *item, int handle)
MenuParse_onOpen.
qboolean MenuParse_onClose (itemDef_t *item, int handle)
MenuParse_onClose.
qboolean MenuParse_onESC (itemDef_t *item, int handle)
MenuParse_onESC.
qboolean MenuParse_onEnter (itemDef_t *item, int handle)
MenuParse_onEnter.
qboolean MenuParse_onPaste (itemDef_t *item, int handle)
MenuParse_onPaste.
qboolean MenuParse_onTimeout (itemDef_t *item, int handle)
Menu timeout.
qboolean MenuParse_border (itemDef_t *item, int handle)
MenuParse_border.
qboolean MenuParse_borderSize (itemDef_t *item, int handle)
MenuParse_borderSize.
qboolean MenuParse_backcolor (itemDef_t *item, int handle)
MenuParse_backcolor.
qboolean MenuParse_forecolor (itemDef_t *item, int handle)
MenuParse_forecolor.
qboolean MenuParse_bordercolor (itemDef_t *item, int handle)
MenuParse_bordercolor.
qboolean MenuParse_focuscolor (itemDef_t *item, int handle)
MenuParse_focuscolor.
qboolean MenuParse_disablecolor (itemDef_t *item, int handle)
MenuParse_disablecolor.
qboolean MenuParse_outlinecolor (itemDef_t *item, int handle)
MenuParse_outlinecolor.
qboolean MenuParse_background (itemDef_t *item, int handle)
MenuParse_background.
qboolean MenuParse_cinematic (itemDef_t *item, int handle)
MenuParse_cinematic.
qboolean MenuParse_ownerdrawFlag (itemDef_t *item, int handle)
MenuParse_ownerdrawFlag.
qboolean MenuParse_ownerdraw (itemDef_t *item, int handle)
MenuParse_ownerdraw.
qboolean MenuParse_popup (itemDef_t *item, int handle)
MenuParse_popup.
qboolean MenuParse_outOfBounds (itemDef_t *item, int handle)
MenuParse_outOfBounds.
qboolean MenuParse_soundLoop (itemDef_t *item, int handle)
MenuParse_soundLoop.
qboolean MenuParse_fadeClamp (itemDef_t *item, int handle)
MenuParse_fadeClamp.
qboolean MenuParse_fadeAmount (itemDef_t *item, int handle)
MenuParse_fadeAmount.
qboolean MenuParse_fadeCycle (itemDef_t *item, int handle)
MenuParse_fadeCycle.
qboolean MenuParse_itemDef (itemDef_t *item, int handle)
MenuParse_itemDef.
qboolean MenuParse_execKey (itemDef_t *item, int handle)
MenuParse_execKey.
qboolean MenuParse_execKeyInt (itemDef_t *item, int handle)
MenuParse_execKeyInt.
qboolean MenuParse_drawAlwaysOnTop (itemDef_t *item, int handle)
MenuParse_drawAlwaysOnTop.
qboolean MenuParse_itemHotkeyMode (itemDef_t *item, int handle)
Parse the command to set if we're looping through all items to find the current hotkey.
qboolean MenuParse_modal (itemDef_t *item, int handle)
MenuParse_modal.
void Menu_SetupKeywordHash (void)
Menu_SetupKeywordHash.
qboolean Menu_Parse (int handle, menuDef_t *menu)
Menu_Parse.
Variables
keywordHash_t itemParseKeywords []
keywordHash_t * itemParseKeywordHash [KEYWORDHASH_SIZE]
keywordHash_t menuParseKeywords []
keywordHash_t * menuParseKeywordHash [KEYWORDHASH_SIZE]
Detailed Description
String allocation/managment.
Definition in file ui_parse.c.
Macro Definition Documentation
#define KEYWORDHASH_SIZE 512
Definition at line 337 of file ui_parse.c.
Referenced by Item_SetupKeywordHash(), KeywordHash_Key(), and Menu_SetupKeywordHash().
Typedef Documentation
keywordHash_t
Function Documentation
qboolean Color_Parse (char ** p, vec4_t * c)
Color_Parse.
Parameters
[in] p
[out] c
Returns
Definition at line 160 of file ui_parse.c.
Referenced by Script_SetItemColor(), and Script_SetMenuItemColor().
qboolean Float_Parse (char ** p, float * f)
Float_Parse.
Parameters
[in] p
[out] f
Returns
Definition at line 138 of file ui_parse.c.
Referenced by Color_Parse(), Rect_Parse(), Script_Orbit(), Script_SetColor(), and Script_Transition().
qboolean Int_Parse (char ** p, int * i)
Int_Parse.
Parameters
[in] p
[out] i
Returns
Definition at line 184 of file ui_parse.c.
Referenced by GameType_Parse(), Script_ConditionalOpen(), Script_ConditionalScript(), Script_ExecWolfConfig(), Script_Orbit(), Script_SetTextStyle(), Script_Transition(), and UI_RunMenuScript().
void Item_InitControls (itemDef_t * item)
Init's special control types.
Parameters
[in,out] item
Definition at line 2344 of file ui_parse.c.
Referenced by MenuParse_itemDef().
qboolean Item_Parse (int handle, itemDef_t * item)
Item_Parse.
Parameters
[in] handle
[in] item
Returns
Definition at line 2297 of file ui_parse.c.
Referenced by MenuParse_itemDef().
void Item_SetupKeywordHash (void)
Item_SetupKeywordHash.
Definition at line 2280 of file ui_parse.c.
Referenced by String_Init().
qboolean Item_ValidateTooltipData (itemDef_t * item)
Item_ValidateTooltipData.
Parameters
[in,out] item
Returns
Definition at line 113 of file ui_parse.c.
Referenced by ItemParse_tooltip(), ItemParse_tooltipalignx(), and ItemParse_tooltipaligny().
void Item_ValidateTypeData (itemDef_t * item)
Item_ValidateTypeData.
Parameters
[in,out] item
Definition at line 70 of file ui_parse.c.
Referenced by ItemParse_asset_model(), ItemParse_columns(), ItemParse_contextMenu(), ItemParse_cvar(), ItemParse_cvarFloat(), ItemParse_cvarFloatList(), ItemParse_cvarListUndefined(), ItemParse_cvarStrList(), ItemParse_doubleClick(), ItemParse_elementheight(), ItemParse_elementtype(), ItemParse_elementwidth(), ItemParse_maxChars(), ItemParse_maxPaintChars(), ItemParse_model_angle(), ItemParse_model_animplay(), ItemParse_model_fovx(), ItemParse_model_fovy(), ItemParse_model_origin(), ItemParse_model_rotation(), ItemParse_notselectable(), and ItemParse_type().
qboolean ItemParse_accept (itemDef_t * item, int handle)
ItemParse_accept.
Parameters
[in] item
[in] handle
Returns
Definition at line 1555 of file ui_parse.c.
qboolean ItemParse_action (itemDef_t * item, int handle)
ItemParse_action.
Parameters
[in] item
[in] handle
Returns
Definition at line 1539 of file ui_parse.c.
qboolean ItemParse_addColorRange (itemDef_t * item, int handle)
ItemParse_addColorRange.
Parameters
[in] item
[in] handle
Returns
Definition at line 1924 of file ui_parse.c.
qboolean ItemParse_addColorRangeRel (itemDef_t * item, int handle)
ItemParse_addColorRangeRel.
Parameters
[in] item
[in] handle
Returns
Definition at line 1913 of file ui_parse.c.
qboolean ItemParse_align (itemDef_t * item, int handle)
ItemParse_align.
Parameters
[in] item
[in] handle
Returns
Definition at line 1091 of file ui_parse.c.
qboolean ItemParse_asset_model (itemDef_t * item, int handle)
ItemParse_asset_model.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 517 of file ui_parse.c.
qboolean ItemParse_asset_shader (itemDef_t * item, int handle)
ItemParse_asset_shader.
Parameters
[out] item
[in] handle
Returns
Definition at line 541 of file ui_parse.c.
qboolean ItemParse_autowrapped (itemDef_t * item, int handle)
ItemParse_autowrapped.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 827 of file ui_parse.c.
qboolean ItemParse_backcolor (itemDef_t * item, int handle)
ItemParse_backcolor.
Parameters
[out] item
[in] handle
Returns
Definition at line 1203 of file ui_parse.c.
qboolean ItemParse_background (itemDef_t * item, int handle)
ItemParse_background.
Parameters
[out] item
[in] handle
Returns
Definition at line 1292 of file ui_parse.c.
qboolean ItemParse_bitflag (itemDef_t * item, int handle)
ItemParse_bitflag.
Parameters
[in] item
[in] handle
Returns
Definition at line 839 of file ui_parse.c.
qboolean ItemParse_border (itemDef_t * item, int handle)
ItemParse_border.
Parameters
[in] item
[in] handle
Returns
Definition at line 1019 of file ui_parse.c.
qboolean ItemParse_bordercolor (itemDef_t * item, int handle)
ItemParse_bordercolor.
Parameters
[out] item
[in] handle
Returns
Definition at line 1252 of file ui_parse.c.
qboolean ItemParse_bordersize (itemDef_t * item, int handle)
ItemParse_bordersize.
Parameters
[in] item
[in] handle
Returns
Definition at line 1035 of file ui_parse.c.
qboolean ItemParse_cinematic (itemDef_t * item, int handle)
ItemParse_cinematic.
Parameters
[in] item
[in] handle
Returns
Definition at line 1311 of file ui_parse.c.
qboolean ItemParse_columns (itemDef_t * item, int handle)
Sets a number of columns and an x pos and width per..
Parameters
[in,out] item
[in] handle
Returns
Definition at line 967 of file ui_parse.c.
qboolean ItemParse_contextMenu (itemDef_t * item, int handle)
ItemParse_contextMenu.
Parameters
[in] item
[in] handle
Returns
Definition at line 1417 of file ui_parse.c.
qboolean ItemParse_cvar (itemDef_t * item, int handle)
ItemParse_cvar.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1603 of file ui_parse.c.
qboolean ItemParse_cvarFloat (itemDef_t * item, int handle)
ItemParse_cvarFloat.
Parameters
[in] item
[in] handle
Returns
Definition at line 1685 of file ui_parse.c.
qboolean ItemParse_cvarFloatList (itemDef_t * item, int handle)
ItemParse_cvarFloatList.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1782 of file ui_parse.c.
qboolean ItemParse_cvarListUndefined (itemDef_t * item, int handle)
ItemParse_cvarListUndefined.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1845 of file ui_parse.c.
qboolean ItemParse_cvarStrList (itemDef_t * item, int handle)
ItemParse_cvarStrList.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1713 of file ui_parse.c.
qboolean ItemParse_cvarTest (itemDef_t * item, int handle)
ItemParse_cvarTest.
Parameters
[in] item
[in] handle
Returns
Definition at line 1587 of file ui_parse.c.
qboolean ItemParse_decoration (itemDef_t * item, int handle)
ItemParse_decoration.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 760 of file ui_parse.c.
qboolean ItemParse_disableCvar (itemDef_t * item, int handle)
ItemParse_disableCvar.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1970 of file ui_parse.c.
qboolean ItemParse_doubleClick (itemDef_t * item, int handle)
ItemParse_doubleClick.
Parameters
[in] item
[in] handle
Returns
Definition at line 1327 of file ui_parse.c.
qboolean ItemParse_elementheight (itemDef_t * item, int handle)
Used for listbox image elements.
uses textaligny for storage
Parameters
[in] item
[in] handle
Returns
Definition at line 905 of file ui_parse.c.
qboolean ItemParse_elementtype (itemDef_t * item, int handle)
Used to specify what type of elements a listbox contains.
Uses textstyle for storage
Parameters
item
handle
Returns
Definition at line 942 of file ui_parse.c.
qboolean ItemParse_elementwidth (itemDef_t * item, int handle)
Used for listbox image elements.
Uses textalignx for storage
Parameters
[in] item
[in] handle
Returns
Definition at line 884 of file ui_parse.c.
qboolean ItemParse_enableCvar (itemDef_t * item, int handle)
ItemParse_enableCvar.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1953 of file ui_parse.c.
qboolean ItemParse_execKey (itemDef_t * item, int handle)
ItemParse_execKey.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2033 of file ui_parse.c.
qboolean ItemParse_feeder (itemDef_t * item, int handle)
ItemParse_feeder.
Parameters
[in] item
[in] handle
Returns
Definition at line 925 of file ui_parse.c.
qboolean ItemParse_focusSound (itemDef_t * item, int handle)
ItemParse_focusSound.
Parameters
[out] item
[in] handle
Returns
Definition at line 444 of file ui_parse.c.
qboolean ItemParse_forecolor (itemDef_t * item, int handle)
ItemParse_forecolor.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1227 of file ui_parse.c.
qboolean ItemParse_group (itemDef_t * item, int handle)
ItemParse_group.
Parameters
[in] item
[in] handle
Returns
Definition at line 501 of file ui_parse.c.
qboolean ItemParse_hideCvar (itemDef_t * item, int handle)
ItemParse_hideCvar.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2016 of file ui_parse.c.
qboolean ItemParse_horizontalscroll (itemDef_t * item, int handle)
ItemParse_horizontalscroll.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 854 of file ui_parse.c.
qboolean ItemParse_leaveFocus (itemDef_t * item, int handle)
ItemParse_leaveFocus.
Parameters
[in] item
[in] handle
Returns
Definition at line 1459 of file ui_parse.c.
qboolean ItemParse_maxChars (itemDef_t * item, int handle)
ItemParse_maxChars.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1631 of file ui_parse.c.
qboolean ItemParse_maxPaintChars (itemDef_t * item, int handle)
ItemParse_maxPaintChars.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1658 of file ui_parse.c.
qboolean ItemParse_model_angle (itemDef_t * item, int handle)
ItemParse_model_angle.
Parameters
[in] item
[in] handle
Returns
Definition at line 646 of file ui_parse.c.
qboolean ItemParse_model_animplay (itemDef_t * item, int handle)
ItemParse_model_animplay.
Parameters
[in] item
[in] handle
Returns
Definition at line 666 of file ui_parse.c.
qboolean ItemParse_model_fovx (itemDef_t * item, int handle)
ItemParse_model_fovx.
Parameters
[in] item
[in] handle
Returns
Definition at line 586 of file ui_parse.c.
qboolean ItemParse_model_fovy (itemDef_t * item, int handle)
ItemParse_model_fovy.
Parameters
[in] item
[in] handle
Returns
Definition at line 606 of file ui_parse.c.
qboolean ItemParse_model_origin (itemDef_t * item, int handle)
ItemParse_model_origin.
Parameters
[in] item
[in] handle
Returns
Definition at line 560 of file ui_parse.c.
qboolean ItemParse_model_rotation (itemDef_t * item, int handle)
ItemParse_model_rotation.
Parameters
[in] item
[in] handle
Returns
Definition at line 626 of file ui_parse.c.
qboolean ItemParse_mouseEnter (itemDef_t * item, int handle)
ItemParse_mouseEnter.
Parameters
[in] item
[in] handle
Returns
Definition at line 1475 of file ui_parse.c.
qboolean ItemParse_mouseEnterText (itemDef_t * item, int handle)
ItemParse_mouseEnterText.
Parameters
[in] item
[in] handle
Returns
Definition at line 1507 of file ui_parse.c.
qboolean ItemParse_mouseExit (itemDef_t * item, int handle)
ItemParse_mouseExit.
Parameters
[in] item
[in] handle
Returns
Definition at line 1491 of file ui_parse.c.
qboolean ItemParse_mouseExitText (itemDef_t * item, int handle)
ItemParse_mouseExitText.
Parameters
[in] item
[in] handle
Returns
Definition at line 1523 of file ui_parse.c.
qboolean ItemParse_name (itemDef_t * item, int handle)
ItemParse_name.
Parameters
[in] item
[in] handle
Returns
Definition at line 427 of file ui_parse.c.
qboolean ItemParse_noToggle (itemDef_t * item, int handle)
ItemParse_noToggle.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 1987 of file ui_parse.c.
qboolean ItemParse_notselectable (itemDef_t * item, int handle)
ItemParse_notselectable.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 796 of file ui_parse.c.
qboolean ItemParse_onEnter (itemDef_t * item, int handle)
ItemParse_onEnter.
Parameters
[in] item
[in] handle
Returns
Definition at line 1385 of file ui_parse.c.
qboolean ItemParse_onEsc (itemDef_t * item, int handle)
ItemParse_onEsc.
Parameters
[in] item
[in] handle
Returns
Definition at line 1369 of file ui_parse.c.
qboolean ItemParse_onFocus (itemDef_t * item, int handle)
ItemParse_onFocus.
Parameters
[in] item
[in] handle
Returns
Definition at line 1443 of file ui_parse.c.
qboolean ItemParse_onPaste (itemDef_t * item, int handle)
ItemParse_onPaste.
Parameters
[in] item
[in] handle
Returns
Definition at line 1401 of file ui_parse.c.
qboolean ItemParse_onTab (itemDef_t * item, int handle)
ItemParse_onTab.
Parameters
[in] item
[in] handle
Returns
Definition at line 1353 of file ui_parse.c.
qboolean ItemParse_origin (itemDef_t * item, int handle)
ItemParse_origin.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 718 of file ui_parse.c.
qboolean ItemParse_outlinecolor (itemDef_t * item, int handle)
ItemParse_outlinecolor.
Parameters
[in] item
[in] handle
Returns
Definition at line 1276 of file ui_parse.c.
qboolean ItemParse_ownerdraw (itemDef_t * item, int handle)
ItemParse_ownerdraw.
Parameters
[in] item
[in] handle
Returns
Definition at line 1074 of file ui_parse.c.
qboolean ItemParse_ownerdrawFlag (itemDef_t * item, int handle)
ItemParse_ownerdrawFlag.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1935 of file ui_parse.c.
qboolean ItemParse_rect (itemDef_t * item, int handle)
ItemParse_rect.
Parameters
[in] item
[in] handle
Returns
Definition at line 707 of file ui_parse.c.
qboolean ItemParse_scrollColor (itemDef_t * item, int handle)
ItemParse_scrollColor.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2141 of file ui_parse.c.
qboolean ItemParse_settingDisabled (itemDef_t * item, int handle)
Server setting tags.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2061 of file ui_parse.c.
qboolean ItemParse_settingEnabled (itemDef_t * item, int handle)
ItemParse_settingEnabled.
Parameters
[out] item
[in] handle
Returns
Definition at line 2079 of file ui_parse.c.
qboolean ItemParse_showCvar (itemDef_t * item, int handle)
ItemParse_showCvar.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 1999 of file ui_parse.c.
qboolean ItemParse_sliderColor (itemDef_t * item, int handle)
ItemParse_sliderColor.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2165 of file ui_parse.c.
qboolean ItemParse_special (itemDef_t * item, int handle)
ItemParse_special.
Parameters
[in] item
[in] handle
Returns
Definition at line 1571 of file ui_parse.c.
qboolean ItemParse_style (itemDef_t * item, int handle)
ItemParse_style.
Parameters
item
handle
Returns
Definition at line 744 of file ui_parse.c.
qboolean ItemParse_text (itemDef_t * item, int handle)
ItemParse_text.
Parameters
[in] item
[in] handle
Returns
Definition at line 463 of file ui_parse.c.
qboolean ItemParse_textalign (itemDef_t * item, int handle)
ItemParse_textalign.
Parameters
[in] item
[in] handle
Returns
Definition at line 1107 of file ui_parse.c.
qboolean ItemParse_textalignx (itemDef_t * item, int handle)
ItemParse_textalignx.
Parameters
[in] item
[in] handle
Returns
Definition at line 1123 of file ui_parse.c.
qboolean ItemParse_textaligny (itemDef_t * item, int handle)
ItemParse_textaligny.
Parameters
[in] item
[in] handle
Returns
Definition at line 1139 of file ui_parse.c.
qboolean ItemParse_textasfloat (itemDef_t * item, int handle)
ItemParse_textasfloat.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 784 of file ui_parse.c.
qboolean ItemParse_textasint (itemDef_t * item, int handle)
ItemParse_textasint.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 772 of file ui_parse.c.
qboolean ItemParse_textfile (itemDef_t * item, int handle)
Read an external textfile into item->text.
Parameters
[out] item
[in] handle
Returns
Definition at line 479 of file ui_parse.c.
qboolean ItemParse_textfont (itemDef_t * item, int handle)
Forcing a font for a given item.
Parameters
[in] item
[in] handle
Returns
Definition at line 1187 of file ui_parse.c.
qboolean ItemParse_textscale (itemDef_t * item, int handle)
ItemParse_textscale.
Parameters
[in] item
[in] handle
Returns
Definition at line 1155 of file ui_parse.c.
qboolean ItemParse_textstyle (itemDef_t * item, int handle)
ItemParse_textstyle.
Parameters
[in] item
[in] handle
Returns
Definition at line 1171 of file ui_parse.c.
qboolean ItemParse_tooltip (itemDef_t * item, int handle)
ItemParse_tooltip.
Parameters
[in] item
[in] handle
Returns
Definition at line 2097 of file ui_parse.c.
qboolean ItemParse_tooltipalignx (itemDef_t * item, int handle)
ItemParse_tooltipalignx.
Parameters
[in] item
[in] handle
Returns
Definition at line 2108 of file ui_parse.c.
qboolean ItemParse_tooltipaligny (itemDef_t * item, int handle)
ItemParse_tooltipaligny.
Parameters
[in] item
[in] handle
Returns
Definition at line 2119 of file ui_parse.c.
qboolean ItemParse_type (itemDef_t * item, int handle)
ItemParse_type.
Parameters
[in] item
[in] handle
Returns
Definition at line 866 of file ui_parse.c.
qboolean ItemParse_visible (itemDef_t * item, int handle)
ItemParse_visible.
Parameters
[in] item
[in] handle
Returns
Definition at line 1051 of file ui_parse.c.
qboolean ItemParse_voteFlag (itemDef_t * item, int handle)
ItemParse_voteFlag.
Parameters
[in] item
[in] handle
Returns
Definition at line 2130 of file ui_parse.c.
qboolean ItemParse_wrapped (itemDef_t * item, int handle)
ItemParse_wrapped.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 815 of file ui_parse.c.
void KeywordHash_Add (keywordHash_t * table[], keywordHash_t * key)
KeywordHash_Add.
Parameters
[in,out] table
[in,out] key
Definition at line 381 of file ui_parse.c.
Referenced by Item_SetupKeywordHash(), and Menu_SetupKeywordHash().
keywordHash_t* KeywordHash_Find (keywordHash_t * table[], const char * keyword)
KeywordHash_Find.
Parameters
[in] table
[in] keyword
Returns
Definition at line 399 of file ui_parse.c.
Referenced by Item_Parse(), and Menu_Parse().
int KeywordHash_Key (const char * keyword)
KeywordHash_Key.
Parameters
[in] keyword
Returns
Definition at line 356 of file ui_parse.c.
Referenced by KeywordHash_Add(), and KeywordHash_Find().
qboolean Menu_Parse (int handle, menuDef_t * menu)
Menu_Parse.
Parameters
[in] handle
[in] menu
Returns
Definition at line 3147 of file ui_parse.c.
Referenced by Menu_New().
void Menu_SetupKeywordHash (void)
Menu_SetupKeywordHash.
Definition at line 3130 of file ui_parse.c.
Referenced by String_Init().
qboolean MenuParse_backcolor (itemDef_t * item, int handle)
MenuParse_backcolor.
Parameters
[out] item
[in] handle
Returns
Definition at line 2636 of file ui_parse.c.
qboolean MenuParse_background (itemDef_t * item, int handle)
MenuParse_background.
Parameters
[out] item
[in] handle
Returns
Definition at line 2781 of file ui_parse.c.
qboolean MenuParse_border (itemDef_t * item, int handle)
MenuParse_border.
Parameters
[in] item
[in] handle
Returns
Definition at line 2600 of file ui_parse.c.
qboolean MenuParse_bordercolor (itemDef_t * item, int handle)
MenuParse_bordercolor.
Parameters
[out] item
[in] handle
Returns
Definition at line 2687 of file ui_parse.c.
qboolean MenuParse_borderSize (itemDef_t * item, int handle)
MenuParse_borderSize.
Parameters
[in] item
[in] handle
Returns
Definition at line 2618 of file ui_parse.c.
qboolean MenuParse_cinematic (itemDef_t * item, int handle)
MenuParse_cinematic.
Parameters
[in] item
[in] handle
Returns
Definition at line 2801 of file ui_parse.c.
qboolean MenuParse_disablecolor (itemDef_t * item, int handle)
MenuParse_disablecolor.
Parameters
[out] item
[in] handle
Returns
Definition at line 2738 of file ui_parse.c.
qboolean MenuParse_drawAlwaysOnTop (itemDef_t * item, int handle)
MenuParse_drawAlwaysOnTop.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 3045 of file ui_parse.c.
qboolean MenuParse_execKey (itemDef_t * item, int handle)
MenuParse_execKey.
Parameters
[in] item
[in] handle
Returns
Definition at line 2994 of file ui_parse.c.
qboolean MenuParse_execKeyInt (itemDef_t * item, int handle)
MenuParse_execKeyInt.
Parameters
[in] item
[in] handle
Returns
Definition at line 3021 of file ui_parse.c.
qboolean MenuParse_fadeAmount (itemDef_t * item, int handle)
MenuParse_fadeAmount.
Parameters
[in] item
[in] handle
Returns
Definition at line 2921 of file ui_parse.c.
qboolean MenuParse_fadeClamp (itemDef_t * item, int handle)
MenuParse_fadeClamp.
Parameters
[in] item
[in] handle
Returns
Definition at line 2903 of file ui_parse.c.
qboolean MenuParse_fadeCycle (itemDef_t * item, int handle)
MenuParse_fadeCycle.
Parameters
[in] item
[in] handle
Returns
Definition at line 2939 of file ui_parse.c.
qboolean MenuParse_focuscolor (itemDef_t * item, int handle)
MenuParse_focuscolor.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2712 of file ui_parse.c.
qboolean MenuParse_forecolor (itemDef_t * item, int handle)
MenuParse_forecolor.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2661 of file ui_parse.c.
qboolean MenuParse_fullscreen (itemDef_t * item, int handle)
MenuParse_fullscreen.
Parameters
[out] item
[in] handle
Returns
Definition at line 2407 of file ui_parse.c.
qboolean MenuParse_itemDef (itemDef_t * item, int handle)
MenuParse_itemDef.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2957 of file ui_parse.c.
qboolean MenuParse_itemHotkeyMode (itemDef_t * item, int handle)
Parse the command to set if we're looping through all items to find the current hotkey.
Parameters
[in] item
[in] handle
Returns
Definition at line 3058 of file ui_parse.c.
qboolean MenuParse_modal (itemDef_t * item, int handle)
MenuParse_modal.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 3076 of file ui_parse.c.
qboolean MenuParse_name (itemDef_t * item, int handle)
MenuParse_name.
Parameters
[in] item
[in] handle
Returns
Todo:
TODO: main windows ?
Definition at line 2383 of file ui_parse.c.
qboolean MenuParse_onClose (itemDef_t * item, int handle)
MenuParse_onClose.
Parameters
[in] item
[in] handle
Returns
Definition at line 2505 of file ui_parse.c.
qboolean MenuParse_onEnter (itemDef_t * item, int handle)
MenuParse_onEnter.
Parameters
[in] item
[in] handle
Returns
Definition at line 2541 of file ui_parse.c.
qboolean MenuParse_onESC (itemDef_t * item, int handle)
MenuParse_onESC.
Parameters
[in] item
[in] handle
Returns
Definition at line 2523 of file ui_parse.c.
qboolean MenuParse_onOpen (itemDef_t * item, int handle)
MenuParse_onOpen.
Parameters
[in] item
[in] handle
Returns
Definition at line 2487 of file ui_parse.c.
qboolean MenuParse_onPaste (itemDef_t * item, int handle)
MenuParse_onPaste.
Parameters
[in] item
[in] handle
Returns
Definition at line 2559 of file ui_parse.c.
qboolean MenuParse_onTimeout (itemDef_t * item, int handle)
Menu timeout.
Parameters
[in] item
[in] handle
Returns
Definition at line 2577 of file ui_parse.c.
qboolean MenuParse_outlinecolor (itemDef_t * item, int handle)
MenuParse_outlinecolor.
Parameters
[in] item
[in] handle
Returns
Definition at line 2763 of file ui_parse.c.
qboolean MenuParse_outOfBounds (itemDef_t * item, int handle)
MenuParse_outOfBounds.
Parameters
[in,out] item
handle - unused
Returns
Definition at line 2871 of file ui_parse.c.
qboolean MenuParse_ownerdraw (itemDef_t * item, int handle)
MenuParse_ownerdraw.
Parameters
[in] item
[in] handle
Returns
Definition at line 2839 of file ui_parse.c.
qboolean MenuParse_ownerdrawFlag (itemDef_t * item, int handle)
MenuParse_ownerdrawFlag.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2819 of file ui_parse.c.
qboolean MenuParse_popup (itemDef_t * item, int handle)
MenuParse_popup.
Parameters
[in,out] item
handle - unused
Returns
Note
decoration
Definition at line 2858 of file ui_parse.c.
qboolean MenuParse_rect (itemDef_t * item, int handle)
MenuParse_rect.
Parameters
[in] item
[in] handle
Returns
Definition at line 2432 of file ui_parse.c.
qboolean MenuParse_soundLoop (itemDef_t * item, int handle)
MenuParse_soundLoop.
Parameters
[in] item
[in] handle
Returns
Definition at line 2885 of file ui_parse.c.
qboolean MenuParse_style (itemDef_t * item, int handle)
MenuParse_style.
Parameters
[in] item
[in] handle
Returns
Definition at line 2445 of file ui_parse.c.
qboolean MenuParse_visible (itemDef_t * item, int handle)
MenuParse_visible.
Parameters
[in,out] item
[in] handle
Returns
Definition at line 2463 of file ui_parse.c.
qboolean ParseColorRange (itemDef_t * item, int handle, int type)
ParseColorRange.
Parameters
[in,out] item
[in] handle
[in] type
Returns
Definition at line 1877 of file ui_parse.c.
Referenced by ItemParse_addColorRange(), and ItemParse_addColorRangeRel().
qboolean PC_Char_Parse (int handle, char * out)
PC_Char_Parse.
Parameters
[in] handle
[out] out
Returns
Definition at line 273 of file ui_parse.c.
Referenced by ItemParse_execKey(), and MenuParse_execKey().
qboolean PC_Script_Parse (int handle, const char ** out)
PC_Script_Parse.
Parameters
[in] handle
[out] out
Returns
Definition at line 292 of file ui_parse.c.
Referenced by ItemParse_accept(), ItemParse_action(), ItemParse_disableCvar(), ItemParse_doubleClick(), ItemParse_enableCvar(), ItemParse_execKey(), ItemParse_hideCvar(), ItemParse_leaveFocus(), ItemParse_mouseEnter(), ItemParse_mouseEnterText(), ItemParse_mouseExit(), ItemParse_mouseExitText(), ItemParse_onEnter(), ItemParse_onEsc(), ItemParse_onFocus(), ItemParse_onPaste(), ItemParse_onTab(), ItemParse_showCvar(), MenuParse_execKey(), MenuParse_execKeyInt(), MenuParse_onClose(), MenuParse_onEnter(), MenuParse_onESC(), MenuParse_onOpen(), MenuParse_onPaste(), and MenuParse_onTimeout().
qboolean PC_String_ParseTranslate (int handle, const char ** out)
Same as PC_String_Parse except it uses a trap call to client's gettext translation function.
Parameters
[in] handle
[out] out
Returns
Definition at line 253 of file ui_parse.c.
Referenced by ItemParse_text(), and ItemParse_tooltip().
qboolean Rect_Parse (char ** p, rectDef_t * r)
Rect_Parse.
Parameters
[in] p
[in] r
Returns
Definition at line 207 of file ui_parse.c.
Referenced by Script_Transition().
qboolean String_Parse (char ** p, const char ** out)
String_Parse.
Parameters
[in] p
[out] out
Returns
Definition at line 232 of file ui_parse.c.
Referenced by GameType_Parse(), Item_EnableShowViaCvar(), Item_RunScript(), Script_AddListItem(), Script_ClearCvar(), Script_Close(), Script_ConditionalOpen(), Script_ConditionalScript(), Script_CopyCvar(), Script_Exec(), Script_ExecNOW(), Script_FadeIn(), Script_FadeInMenu(), Script_FadeOut(), Script_FadeOutMenu(), Script_GetClipboard(), Script_Hide(), Script_Open(), Script_Orbit(), Script_Play(), Script_playLooped(), Script_SetBackground(), Script_SetColor(), Script_SetCvar(), Script_SetEditFocus(), Script_SetFocus(), Script_SetItemColor(), Script_SetMenuFocus(), Script_SetMenuItemColor(), Script_SetPlayerHead(), Script_SetPlayerModel(), Script_SetTextStyle(), Script_Show(), Script_ToggleCvarBit(), Script_Transition(), and UI_RunMenuScript().
void Tooltip_ComputePosition (itemDef_t * item)
Tooltip_ComputePosition.
Parameters
[in,out] item
Definition at line 43 of file ui_parse.c.
Referenced by Item_InitControls().
Variable Documentation
keywordHash_t* itemParseKeywordHash[KEYWORDHASH_SIZE]
Definition at line 2275 of file ui_parse.c.
keywordHash_t itemParseKeywords[]
Definition at line 2183 of file ui_parse.c.
keywordHash_t* menuParseKeywordHash[KEYWORDHASH_SIZE]
Definition at line 3125 of file ui_parse.c.
keywordHash_t menuParseKeywords[]
Definition at line 3083 of file ui_parse.c.