ET: Legacy: src/ui/ui_gameinfo.c File Reference
ui_gameinfo.c File Reference
#include "ui_local.h"
Functions
static void UI_LoadArenasFromFile (const char *filename)
UI_LoadArenasFromFile.
int QDECL UI_SortArenas (const void *a, const void *b)
Sorting the map list.
void UI_LoadArenas (void)
UI_LoadArenas.
mapInfo * UI_FindMapInfoByMapname (const char *name)
UI_FindMapInfoByMapname.
static void UI_LoadCampaignsFromFile (const char *filename)
UI_LoadCampaignsFromFile.
const char * UI_DescriptionForCampaign (void)
UI_DescriptionForCampaign.
const char * UI_NameForCampaign (void)
UI_NameForCampaign.
int UI_FindCampaignInCampaignList (const char *shortName)
UI_FindCampaignInCampaignList.
int QDECL UI_SortCampaigns (const void *a, const void *b)
Sorting the campaign list.
void UI_LoadCampaigns (void)
UI_LoadCampaigns.
Function Documentation
const char* UI_DescriptionForCampaign (void)
UI_DescriptionForCampaign.
Returns
Definition at line 527 of file ui_gameinfo.c.
Referenced by UI_Init().
int UI_FindCampaignInCampaignList (const char * shortName)
UI_FindCampaignInCampaignList.
Parameters
[in] shortName
Returns
Definition at line 584 of file ui_gameinfo.c.
Referenced by UI_LoadCampaigns().
mapInfo* UI_FindMapInfoByMapname (const char * name)
UI_FindMapInfoByMapname.
Parameters
[in] name
Returns
Definition at line 295 of file ui_gameinfo.c.
Referenced by UI_DrawMissionBriefingObjectives(), and UI_DrawMissionBriefingTitle().
void UI_LoadArenas (void)
UI_LoadArenas.
Definition at line 253 of file ui_gameinfo.c.
Referenced by UI_Campaign_f(), UI_FindMapInfoByMapname(), UI_ListCampaigns_f(), UI_Load(), and UI_RunMenuScript().
static void UI_LoadArenasFromFile (const char * filename) static
UI_LoadArenasFromFile.
Parameters
[in] filename
Definition at line 41 of file ui_gameinfo.c.
Referenced by UI_LoadArenas().
void UI_LoadCampaigns (void)
UI_LoadCampaigns.
Definition at line 629 of file ui_gameinfo.c.
Referenced by UI_Campaign_f(), UI_ListCampaigns_f(), UI_Load(), and UI_RunMenuScript().
static void UI_LoadCampaignsFromFile (const char * filename) static
UI_LoadCampaignsFromFile.
Parameters
[in] filename
Definition at line 319 of file ui_gameinfo.c.
Referenced by UI_LoadCampaigns().
const char* UI_NameForCampaign (void)
UI_NameForCampaign.
Returns
Definition at line 555 of file ui_gameinfo.c.
Referenced by UI_Init().
int QDECL UI_SortArenas (const void * a, const void * b)
Sorting the map list.
Parameters
[in] a
[in] b
Returns
Definition at line 235 of file ui_gameinfo.c.
Referenced by UI_LoadArenas().
int QDECL UI_SortCampaigns (const void * a, const void * b)
Sorting the campaign list.
Parameters
a
b
Returns
Definition at line 611 of file ui_gameinfo.c.
Referenced by UI_LoadCampaigns().