ET: Legacy: src/ui/ui_menuitem.c File Reference
ui_menuitem.c File Reference
string allocation/managment
#include "ui_shared.h"
#include "ui_local.h"
Macros
#define NEWWAY
Functions
void Item_Tooltip_Initialize (itemDef_t *item)
Item_Tooltip_Initialize.
void Item_SetScreenCoords (itemDef_t *item, float x, float y)
Item_SetScreenCoords.
void Item_UpdatePosition (itemDef_t *item)
Item_UpdatePosition.
qboolean Item_EnableShowViaCvar (itemDef_t *item, int flag)
Item_EnableShowViaCvar.
qboolean Item_SettingShow (itemDef_t *item, qboolean fVoteTest)
Sisplay if we poll on a server toggle setting We want current settings, so this is a bit of a perf hit, but this is only during UI display.
qboolean Item_SetFocus (itemDef_t *item, float x, float y)
Will optionaly set focus to this item.
int Item_ListBox_MaxScroll (itemDef_t *item)
Item_ListBox_MaxScroll.
int Item_ListBox_ThumbPosition (itemDef_t *item)
Item_ListBox_ThumbPosition.
int Item_ListBox_ThumbDrawPosition (itemDef_t *item)
Item_ListBox_ThumbDrawPosition.
float Item_Slider_ThumbPosition (itemDef_t *item)
Item_Slider_ThumbPosition.
int Item_Slider_OverSlider (itemDef_t *item, float x, float y)
Item_Slider_OverSlider.
int Item_ListBox_OverLB (itemDef_t *item, float x, float y)
Item_ListBox_OverLB.
void Item_ListBox_MouseEnter (itemDef_t *item, float x, float y, qboolean click)
Item_ListBox_MouseEnter.
void Item_MouseEnter (itemDef_t *item, float x, float y)
Item_MouseEnter.
void Item_MouseLeave (itemDef_t *item)
Item_MouseLeave.
void Item_SetMouseOver (itemDef_t *item, qboolean focus)
Item_SetMouseOver.
qboolean Item_OwnerDraw_HandleKey (itemDef_t *item, int key)
Item_OwnerDraw_HandleKey.
qboolean Item_ListBox_HandleKey (itemDef_t *item, int key, qboolean down, qboolean force)
Item_ListBox_HandleKey.
qboolean Item_CheckBox_HandleKey (itemDef_t *item, int key)
Item_CheckBox_HandleKey.
qboolean Item_YesNo_HandleKey (itemDef_t *item, int key)
Item_YesNo_HandleKey.
int Item_Multi_CountSettings (itemDef_t *item)
Item_Multi_CountSettings.
int Item_Multi_FindCvarByValue (itemDef_t *item)
Item_Multi_FindCvarByValue.
const char * Item_Multi_Setting (itemDef_t *item)
Item_Multi_Setting.
qboolean Item_Multi_HandleKey (itemDef_t *item, int key)
Item_Multi_HandleKey.
void Item_ComboSelect (itemDef_t *item)
Item_ComboSelect.
void Item_ComboDeSelect (itemDef_t *item)
Item_ComboDeSelect.
void Item_CalcTextFieldCursor (itemDef_t *item)
Item_CalcTextFieldCursor.
void Item_HandleTextFieldSelect (itemDef_t *item)
Item_HandleTextFieldSelect.
void Item_HandleTextFieldDeSelect (itemDef_t *item)
Item_HandleTextFieldDeSelect.
void Item_HandleSaveValue (void)
Item_HandleSaveValue.
static qboolean Item_TextField_InsertToCursor (int *len, char *buff, int key, itemDef_t *item, editFieldDef_t *editPtr)
Item_TextField_InsertToCursor.
qboolean Item_Combo_HandleKey (itemDef_t *item, int key)
Item_Combo_HandleKey.
qboolean Item_TextField_HandleKey (itemDef_t *item, int key)
Item_TextField_HandleKey.
static void Item_Scroll_ListBox_AutoFunc (void *p)
Item_Scroll_ListBox_AutoFunc.
static void Item_Scroll_ListBox_ThumbFunc (void *p)
Item_Scroll_ListBox_ThumbFunc.
static void Item_Scroll_Slider_ThumbFunc (void *p)
Item_Scroll_Slider_ThumbFunc.
void Item_StartCapture (itemDef_t *item, int key)
Item_StartCapture.
qboolean Item_Slider_HandleKey (itemDef_t *item, int key, qboolean down)
Item_Slider_HandleKey.
void Item_Action (itemDef_t *item)
Item_Action.
rectDef_t * Item_CorrectedTextRect (itemDef_t *item)
Item_CorrectedTextRect.
void Item_SetTextExtents (itemDef_t *item, int *width, int *height, const char *text)
Item_SetTextExtents.
void Item_TextColor (itemDef_t *item, vec4_t *newColor)
Item_TextColor.
void Item_Text_AutoWrapped_Paint (itemDef_t *item)
Item_Text_AutoWrapped_Paint.
void Item_Text_Wrapped_Paint (itemDef_t *item)
Item_Text_Wrapped_Paint.
qboolean Item_HandleKey (itemDef_t *item, int key, qboolean down)
Item_HandleKey.
void Item_Text_Paint (itemDef_t *item)
Item_Text_Paint.
void Item_TextField_Paint (itemDef_t *item)
Item_TextField_Paint.
void Item_CheckBox_Paint (itemDef_t *item)
Item_CheckBox_Paint.
void Item_YesNo_Paint (itemDef_t *item)
Item_YesNo_Paint.
void Item_Multi_Paint (itemDef_t *item)
Item_Multi_Paint.
void Item_Combo_Paint (itemDef_t *item)
Item_Combo_Paint.
void Item_Slider_Paint (itemDef_t *item)
Item_Slider_Paint.
void Item_Bind_Paint (itemDef_t *item)
Item_Bind_Paint.
qboolean Item_Bind_HandleKey (itemDef_t *item, int key, qboolean down)
Item_Bind_HandleKey.
void Item_Model_Paint (itemDef_t *item)
Item_Model_Paint.
void Item_ListBox_Paint (itemDef_t *item)
Item_ListBox_Paint.
void Item_OwnerDraw_Paint (itemDef_t *item)
Item_OwnerDraw_Paint.
void Item_DoTransition (itemDef_t *item)
Item_DoTransition.
void Item_Paint (itemDef_t *item)
Item_Paint.
void Item_KeyboardActivate (itemDef_t *item)
This gets called on keyboard Enter and KP_Enter.
void Item_MouseActivate (itemDef_t *item)
This gets called on mouse1-3.
void Item_Init (itemDef_t *item)
Item_Init.
Detailed Description
string allocation/managment
Definition in file ui_menuitem.c.
Macro Definition Documentation
#define NEWWAY
Function Documentation
void Item_Action (itemDef_t * item)
Item_Action.
Parameters
[in] item
Definition at line 2081 of file ui_menuitem.c.
Referenced by Item_KeyboardActivate(), Item_MouseActivate(), and Menu_HandleKey().
qboolean Item_Bind_HandleKey (itemDef_t * item, int key, qboolean down)
Item_Bind_HandleKey.
Parameters
[in] item
[in] key
[in] down
Returns
Definition at line 3093 of file ui_menuitem.c.
Referenced by Item_HandleKey(), and Menu_HandleKey().
void Item_Bind_Paint (itemDef_t * item)
Item_Bind_Paint.
Parameters
[in] item
Definition at line 3028 of file ui_menuitem.c.
Referenced by Item_Paint().
void Item_CalcTextFieldCursor (itemDef_t * item)
Item_CalcTextFieldCursor.
Parameters
[in,out] item
Definition at line 1449 of file ui_menuitem.c.
Referenced by Item_HandleTextFieldSelect().
qboolean Item_CheckBox_HandleKey (itemDef_t * item, int key)
Item_CheckBox_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1173 of file ui_menuitem.c.
Referenced by Item_HandleKey().
void Item_CheckBox_Paint (itemDef_t * item)
Item_CheckBox_Paint.
Parameters
[in] item
Definition at line 2702 of file ui_menuitem.c.
Referenced by Item_Paint().
qboolean Item_Combo_HandleKey (itemDef_t * item, int key)
Item_Combo_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1564 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_Combo_Paint (itemDef_t * item)
Item_Combo_Paint.
Parameters
[in,out] item
Definition at line 2860 of file ui_menuitem.c.
Referenced by Item_Paint().
void Item_ComboDeSelect (itemDef_t * item)
Item_ComboDeSelect.
Parameters
item - unused
Definition at line 1440 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_ComboSelect (itemDef_t * item)
Item_ComboSelect.
Parameters
[in] item
Definition at line 1428 of file ui_menuitem.c.
Referenced by Item_MouseActivate().
rectDef_t* Item_CorrectedTextRect (itemDef_t * item)
Item_CorrectedTextRect.
Parameters
[in] item
Returns
Definition at line 2094 of file ui_menuitem.c.
Referenced by Item_MouseActivate(), Item_Paint(), Menu_HandleMouseMove(), and Menu_OverActiveItem().
void Item_DoTransition (itemDef_t * item)
Item_DoTransition.
Parameters
[in,out] item
Definition at line 3641 of file ui_menuitem.c.
Referenced by Item_Paint().
qboolean Item_EnableShowViaCvar (itemDef_t * item, int flag)
Item_EnableShowViaCvar.
Parameters
[in] item
[in] flag
Returns
Definition at line 139 of file ui_menuitem.c.
Referenced by Item_MouseEnter(), Item_OwnerDraw_Paint(), Item_Paint(), Item_SetFocus(), Item_TextColor(), Menu_HandleKey(), and Menu_HandleMouseMove().
qboolean Item_HandleKey (itemDef_t * item, int key, qboolean down)
Item_HandleKey.
Parameters
[in] item
[in] key
[in] down
Returns
Definition at line 2409 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_HandleSaveValue (void)
Item_HandleSaveValue.
Definition at line 1504 of file ui_menuitem.c.
Referenced by Item_RunScript(), and Item_TextField_HandleKey().
void Item_HandleTextFieldDeSelect (itemDef_t * item)
Item_HandleTextFieldDeSelect.
Parameters
[in] item
Definition at line 1488 of file ui_menuitem.c.
Referenced by Item_HandleSaveValue(), Item_TextField_HandleKey(), and Menu_HandleKey().
void Item_HandleTextFieldSelect (itemDef_t * item)
Item_HandleTextFieldSelect.
Parameters
[in] item
Definition at line 1475 of file ui_menuitem.c.
Referenced by Item_HandleSaveValue(), Item_KeyboardActivate(), Item_MouseActivate(), and Item_TextField_HandleKey().
void Item_Init (itemDef_t * item)
Item_Init.
Parameters
[in,out] item
Definition at line 3991 of file ui_menuitem.c.
Referenced by Item_ValidateTooltipData(), and MenuParse_itemDef().
void Item_KeyboardActivate (itemDef_t * item)
This gets called on keyboard Enter and KP_Enter.
Parameters
[in] item
Definition at line 3915 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
qboolean Item_ListBox_HandleKey (itemDef_t * item, int key, qboolean down, qboolean force)
Item_ListBox_HandleKey.
Parameters
[in,out] item
[in] key
down - unused
[in] force
Returns
Definition at line 829 of file ui_menuitem.c.
Referenced by Item_HandleKey(), Item_Scroll_ListBox_AutoFunc(), Item_Scroll_ListBox_ThumbFunc(), and Menu_ScrollFeeder().
int Item_ListBox_MaxScroll (itemDef_t * item)
Item_ListBox_MaxScroll.
Parameters
[in] item
Returns
Definition at line 336 of file ui_menuitem.c.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_ThumbPosition(), and Item_Scroll_ListBox_ThumbFunc().
void Item_ListBox_MouseEnter (itemDef_t * item, float x, float y, qboolean click)
Item_ListBox_MouseEnter.
Parameters
[in] item
[in] x
[in] y
[in] click
Definition at line 635 of file ui_menuitem.c.
Referenced by Item_ListBox_HandleKey(), Item_MouseEnter(), UI_FeederSelection(), and UI_FeederSelectionClick().
int Item_ListBox_OverLB (itemDef_t * item, float x, float y)
Item_ListBox_OverLB.
Parameters
[in] item
[in] x
[in] y
Returns
Definition at line 524 of file ui_menuitem.c.
Referenced by Item_ListBox_MouseEnter(), and Item_StartCapture().
void Item_ListBox_Paint (itemDef_t * item)
Item_ListBox_Paint.
Parameters
[in] item
Definition at line 3347 of file ui_menuitem.c.
Referenced by Item_Paint().
int Item_ListBox_ThumbDrawPosition (itemDef_t * item)
Item_ListBox_ThumbDrawPosition.
Parameters
[in] item
Returns
Definition at line 408 of file ui_menuitem.c.
Referenced by Item_ListBox_OverLB(), and Item_ListBox_Paint().
int Item_ListBox_ThumbPosition (itemDef_t * item)
Item_ListBox_ThumbPosition.
Parameters
[in] item
Returns
Definition at line 364 of file ui_menuitem.c.
Referenced by Item_ListBox_ThumbDrawPosition().
void Item_Model_Paint (itemDef_t * item)
Item_Model_Paint.
Parameters
[in] item
Definition at line 3211 of file ui_menuitem.c.
Referenced by Item_Paint().
void Item_MouseActivate (itemDef_t * item)
This gets called on mouse1-3.
Parameters
[in] item
Todo:
: make it set the insertion point correctly
Definition at line 3936 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_MouseEnter (itemDef_t * item, float x, float y)
Item_MouseEnter.
Parameters
[in] item
[in] x
[in] y
Definition at line 697 of file ui_menuitem.c.
Referenced by Menu_HandleMouseMove().
void Item_MouseLeave (itemDef_t * item)
Item_MouseLeave.
Parameters
[in,out] item
Definition at line 770 of file ui_menuitem.c.
Referenced by Menu_ClearFocus(), Menu_HandleMouseMove(), and Menu_ShowItemByName().
int Item_Multi_CountSettings (itemDef_t * item)
Item_Multi_CountSettings.
Parameters
[in] item
Returns
Definition at line 1249 of file ui_menuitem.c.
Referenced by Item_Multi_HandleKey().
int Item_Multi_FindCvarByValue (itemDef_t * item)
Item_Multi_FindCvarByValue.
Parameters
[in] item
Returns
Definition at line 1266 of file ui_menuitem.c.
Referenced by Item_Multi_HandleKey().
qboolean Item_Multi_HandleKey (itemDef_t * item, int key)
Item_Multi_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1367 of file ui_menuitem.c.
Referenced by Item_HandleKey().
void Item_Multi_Paint (itemDef_t * item)
Item_Multi_Paint.
Parameters
[in] item
Definition at line 2822 of file ui_menuitem.c.
Referenced by Item_Paint().
const char* Item_Multi_Setting (itemDef_t * item)
Item_Multi_Setting.
Parameters
[in] item
Returns
Definition at line 1312 of file ui_menuitem.c.
Referenced by Item_CheckBox_Paint(), Item_Combo_Paint(), and Item_Multi_Paint().
qboolean Item_OwnerDraw_HandleKey (itemDef_t * item, int key)
Item_OwnerDraw_HandleKey.
Parameters
[in,out] item
[in] key
Returns
Definition at line 811 of file ui_menuitem.c.
Referenced by Item_HandleKey().
void Item_OwnerDraw_Paint (itemDef_t * item)
Item_OwnerDraw_Paint.
Parameters
[in] item
Definition at line 3564 of file ui_menuitem.c.
Referenced by Item_Paint().
void Item_Paint (itemDef_t * item)
Item_Paint.
Parameters
item
Todo:
: should we do something here?
Definition at line 3766 of file ui_menuitem.c.
Referenced by Menu_Paint().
static void Item_Scroll_ListBox_AutoFunc (void * p) static
Item_Scroll_ListBox_AutoFunc.
Parameters
[in,out] p
Definition at line 1822 of file ui_menuitem.c.
Referenced by Item_StartCapture().
static void Item_Scroll_ListBox_ThumbFunc (void * p) static
Item_Scroll_ListBox_ThumbFunc.
Parameters
[in,out] p
Definition at line 1849 of file ui_menuitem.c.
Referenced by Item_StartCapture().
static void Item_Scroll_Slider_ThumbFunc (void * p) static
Item_Scroll_Slider_ThumbFunc.
Parameters
[in] p
Definition at line 1929 of file ui_menuitem.c.
Referenced by Item_StartCapture().
qboolean Item_SetFocus (itemDef_t * item, float x, float y)
Will optionaly set focus to this item.
Parameters
[in] item
[in] x
[in] y
Returns
Definition at line 231 of file ui_menuitem.c.
Referenced by Menu_HandleMouseMove(), Menu_SetNextCursorItem(), and Menu_SetPrevCursorItem().
void Item_SetMouseOver (itemDef_t * item, qboolean focus)
Item_SetMouseOver.
Parameters
[in,out] item
[in] focus
Definition at line 790 of file ui_menuitem.c.
Referenced by Menu_ClearFocus(), Menu_HandleMouseMove(), and Menu_ShowItemByName().
void Item_SetScreenCoords (itemDef_t * item, float x, float y)
Item_SetScreenCoords.
Parameters
[in,out] item
[in] x
[in] y
Todo:
: do the proper thing for the right borders here?
Definition at line 65 of file ui_menuitem.c.
Referenced by Item_SetScreenCoords(), Item_UpdatePosition(), and Menu_UpdatePosition().
void Item_SetTextExtents (itemDef_t * item, int * width, int * height, const char * text)
Item_SetTextExtents.
Parameters
[in,out] item
[in,out] width
[in,out] height
[in] text
Definition at line 2118 of file ui_menuitem.c.
Referenced by Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), and Item_Text_Wrapped_Paint().
qboolean Item_SettingShow (itemDef_t * item, qboolean fVoteTest)
Sisplay if we poll on a server toggle setting We want current settings, so this is a bit of a perf hit, but this is only during UI display.
Parameters
[in] item
[in] fVoteTest
Returns
Definition at line 199 of file ui_menuitem.c.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetFocus(), and Menu_HandleMouseMove().
qboolean Item_Slider_HandleKey (itemDef_t * item, int key, qboolean down)
Item_Slider_HandleKey.
Parameters
[in] item
[in] key
down - unused
Returns
Definition at line 2028 of file ui_menuitem.c.
Referenced by Item_HandleKey().
int Item_Slider_OverSlider (itemDef_t * item, float x, float y)
Item_Slider_OverSlider.
Parameters
[in] item
[in] x
[in] y
Returns
Definition at line 500 of file ui_menuitem.c.
Referenced by Item_StartCapture().
void Item_Slider_Paint (itemDef_t * item)
Item_Slider_Paint.
Parameters
[in] item
menuDef_t *parent = (menuDef_t *)item->parent;
Definition at line 2987 of file ui_menuitem.c.
Referenced by Item_Paint().
float Item_Slider_ThumbPosition (itemDef_t * item)
Item_Slider_ThumbPosition.
Parameters
[in] item
Returns
Definition at line 452 of file ui_menuitem.c.
Referenced by Item_Slider_OverSlider(), and Item_Slider_Paint().
void Item_StartCapture (itemDef_t * item, int key)
Item_StartCapture.
Parameters
[in] item
[in] key
Definition at line 1967 of file ui_menuitem.c.
Referenced by Item_HandleKey().
void Item_Text_AutoWrapped_Paint (itemDef_t * item)
Item_Text_AutoWrapped_Paint.
Parameters
[in,out] item
Definition at line 2225 of file ui_menuitem.c.
Referenced by Item_Text_Paint().
void Item_Text_Paint (itemDef_t * item)
Item_Text_Paint.
Parameters
[in,out] item
Todo:
: this is a fucking mess
Definition at line 2498 of file ui_menuitem.c.
Referenced by Item_Bind_Paint(), Item_CheckBox_Paint(), Item_Combo_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Paint(), Item_Slider_Paint(), Item_TextField_Paint(), and Item_YesNo_Paint().
void Item_Text_Wrapped_Paint (itemDef_t * item)
Item_Text_Wrapped_Paint.
Parameters
[in] item
Definition at line 2348 of file ui_menuitem.c.
Referenced by Item_Text_Paint().
void Item_TextColor (itemDef_t * item, vec4_t * newColor)
Item_TextColor.
Parameters
[in] item
[in] newColor
Definition at line 2180 of file ui_menuitem.c.
Referenced by Item_CheckBox_Paint(), Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), and Item_Text_Wrapped_Paint().
qboolean Item_TextField_HandleKey (itemDef_t * item, int key)
Item_TextField_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1595 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
static qboolean Item_TextField_InsertToCursor (int * len, char * buff, int key, itemDef_t * item, editFieldDef_t * editPtr) static
Item_TextField_InsertToCursor.
Parameters
[in,out] len
[in,out] buff
[in] key
[in,out] item
[in,out] editPtr
Returns
Definition at line 1523 of file ui_menuitem.c.
Referenced by Item_TextField_HandleKey().
void Item_TextField_Paint (itemDef_t * item)
Item_TextField_Paint.
Parameters
[in] item
Todo:
: we could cache the text length and offseting, but given the low count of edit fields, I abstained for now
Todo:
: this won't handle going back into the line of the editfield to the hidden area
Definition at line 2614 of file ui_menuitem.c.
Referenced by Item_Paint().
void Item_Tooltip_Initialize (itemDef_t * item)
Item_Tooltip_Initialize.
Parameters
[in,out] item
Definition at line 43 of file ui_menuitem.c.
Referenced by Item_ValidateTooltipData().
void Item_UpdatePosition (itemDef_t * item)
Item_UpdatePosition.
Parameters
[in] item
Todo:
FIXME: consolidate this with nearby stuff
Definition at line 110 of file ui_menuitem.c.
Referenced by Item_DoTransition(), Item_Paint(), Menu_OrbitItemByName(), and Menu_TransitionItemByName().
qboolean Item_YesNo_HandleKey (itemDef_t * item, int key)
Item_YesNo_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1225 of file ui_menuitem.c.
Referenced by Item_HandleKey().
void Item_YesNo_Paint (itemDef_t * item)
Item_YesNo_Paint.
Parameters
[in] item
Definition at line 2785 of file ui_menuitem.c.
Referenced by Item_Paint().