ET: Legacy: src/ui/ui_syscalls.c File Reference
ui_syscalls.c File Reference
#include "ui_local.h"
Functions
static intptr_t (QDECL *syscall)(intptr_t arg
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
dllEntry
int PASSFLOAT (float x)
PASSFLOAT.
void trap_Print (const char *fmt)
trap_Print
void trap_Error (const char *fmt)
trap_Error
int trap_Milliseconds (void)
trap_Milliseconds
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
trap_Cvar_Register
void trap_Cvar_Update (vmCvar_t *vmCvar)
trap_Cvar_Update
void trap_Cvar_Set (const char *varName, const char *value)
trap_Cvar_Set
float trap_Cvar_VariableValue (const char *varName)
trap_Cvar_VariableValue
void trap_Cvar_VariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_VariableStringBuffer
void trap_Cvar_LatchedVariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
void trap_Cvar_SetValue (const char *varName, float value)
trap_Cvar_SetValue
void trap_Cvar_Reset (const char *name)
trap_Cvar_Reset
void trap_Cvar_Create (const char *varName, const char *var_value, int flags)
trap_Cvar_Create
void trap_Cvar_InfoStringBuffer (int bit, char *buffer, int bufsize)
trap_Cvar_InfoStringBuffer
int trap_Argc (void)
trap_Argc
void trap_Argv (int n, char *buffer, int bufferLength)
trap_Argv
void trap_Cmd_ExecuteText (int exec_when, const char *text)
trap_Cmd_ExecuteText
void trap_AddCommand (const char *cmdName)
trap_AddCommand
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
trap_FS_FOpenFile
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
trap_FS_Read
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
trap_FS_Write
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
trap_FS_GetFileList
int trap_FS_Delete (const char *filename)
trap_FS_Delete
qhandle_t trap_R_RegisterModel (const char *name)
trap_R_RegisterModel
qhandle_t trap_R_RegisterSkin (const char *name)
trap_R_RegisterSkin
void trap_R_RegisterFont (const char *fontName, int pointSize, void *font)
trap_R_RegisterFont
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
trap_R_RegisterShaderNoMip
void trap_R_ClearScene (void)
trap_R_ClearScene
void trap_R_AddRefEntityToScene (const refEntity_t *re)
trap_R_AddRefEntityToScene
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
trap_R_AddPolyToScene
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
void trap_R_RenderScene (const refdef_t *fd)
trap_R_RenderScene
void trap_R_SetColor (const float *rgba)
trap_R_SetColor
void trap_R_Add2dPolys (polyVert_t *verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
void trap_UpdateScreen (void)
trap_UpdateScreen
int trap_CM_LerpTag (orientation_t *tag, const refEntity_t *refent, const char *tagName, int startIndex)
trap_CM_LerpTag
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
trap_S_RegisterSound
void trap_S_FadeBackgroundTrack (float targetvol, int time, int num)
trap_S_FadeBackgroundTrack
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
trap_Key_KeynumToStringBuf
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
trap_Key_GetBindingBuf
void trap_Key_KeysForBinding (const char *binding, int *key1, int *key2)
trap_Key_KeysForBinding
void trap_Key_SetBinding (int keynum, const char *binding)
trap_Key_SetBinding
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
void trap_Key_ClearStates (void)
trap_Key_ClearStates
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
void trap_GetClipboardData (char *buf, size_t bufsize)
trap_GetClipboardData
void trap_GetClientState (uiClientState_t *state)
trap_GetClientState
void trap_GetGlconfig (glconfig_t *glconfig)
trap_GetGlconfig
int trap_GetConfigString (int index, char *buff, size_t buffsize)
trap_GetConfigString
int trap_LAN_GetLocalServerCount (void)
trap_LAN_GetLocalServerCount
void trap_LAN_GetLocalServerAddressString (int n, char *buf, int buflen)
trap_LAN_GetLocalServerAddressString
int trap_LAN_GetGlobalServerCount (void)
trap_LAN_GetGlobalServerCount
void trap_LAN_GetGlobalServerAddressString (int n, char *buf, int buflen)
trap_LAN_GetGlobalServerAddressString
int trap_LAN_GetPingQueueCount (void)
trap_LAN_GetPingQueueCount
void trap_LAN_ClearPing (int n)
trap_LAN_ClearPing
void trap_LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
trap_LAN_GetPing
void trap_LAN_GetPingInfo (int n, char *buf, int buflen)
trap_LAN_GetPingInfo
qboolean trap_LAN_UpdateVisiblePings (int source)
trap_LAN_UpdateVisiblePings
int trap_LAN_GetServerCount (int source)
trap_LAN_GetServerCount
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
trap_LAN_CompareServers
void trap_LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
trap_LAN_GetServerAddressString
void trap_LAN_GetServerInfo (int source, int n, char *buf, int buflen)
trap_LAN_GetServerInfo
int trap_LAN_AddServer (int source, const char *name, const char *addr)
trap_LAN_AddServer
void trap_LAN_RemoveServer (int source, const char *addr)
trap_LAN_RemoveServer
int trap_LAN_GetServerPing (int source, int n)
trap_LAN_GetServerPing
int trap_LAN_ServerIsVisible (int source, int n)
trap_LAN_ServerIsVisible
int trap_LAN_ServerStatus (const char *serverAddress, char *serverStatus, int maxLen)
trap_LAN_ServerStatus
qboolean trap_LAN_ServerIsInFavoriteList (int source, int n)
trap_LAN_ServerIsInFavoriteList
void trap_LAN_LoadCachedServers (void)
trap_LAN_LoadCachedServers
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
trap_LAN_MarkServerVisible
void trap_LAN_ResetPings (int n)
trap_LAN_ResetPings
int trap_MemoryRemaining (void)
trap_MemoryRemaining
int trap_PC_AddGlobalDefine (char *define)
trap_PC_AddGlobalDefine
int trap_PC_RemoveAllGlobalDefines (void)
trap_PC_RemoveAllGlobalDefines
int trap_PC_LoadSource (const char *filename)
trap_PC_LoadSource
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
trap_PC_ReadToken
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
trap_PC_SourceFileAndLine
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
void trap_S_StartBackgroundTrack (const char *intro, const char *loop, int fadeupTime)
trap_S_StartBackgroundTrack
int trap_RealTime (qtime_t *qtime)
trap_RealTime
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle. arg0 is the name in the format "idlogo.roq", set arg1 to NULL, alteredstates to qfalse (do not alter gamestate)
e_status trap_CIN_StopCinematic (int handle)
stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
trap_R_RemapShader
qboolean trap_GetLimboString (int index, char *buf)
trap_GetLimboString
const char * trap_TranslateString (const char *fmt)
trap_TranslateString
void trap_CheckAutoUpdate (void)
trap_CheckAutoUpdate
void trap_GetAutoUpdate (void)
trap_GetAutoUpdate
void trap_openURL (const char *url)
trap_openURL
void trap_GetHunkData (int *hunkused, int *hunkexpected)
trap_GetHunkData
Function Documentation
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
dllEntry
Definition at line 42 of file ui_syscalls.c.
static intptr_t (QDECL * syscall) static
int PASSFLOAT (float x)
PASSFLOAT.
Parameters
[in] x
Returns
Definition at line 52 of file ui_syscalls.c.
Referenced by trap_Cvar_SetValue(), trap_R_AddCoronaToScene(), trap_R_AddLightToScene(), trap_R_DrawRotatedPic(), trap_R_DrawStretchPic(), trap_S_FadeAllSound(), and trap_S_FadeBackgroundTrack().
void trap_AddCommand (const char * cmdName)
trap_AddCommand
Parameters
[in] cmdName
Definition at line 230 of file ui_syscalls.c.
Referenced by CG_InitConsoleCommands(), and UI_Init().
int trap_Argc (void)
trap_Argc
Returns
Definition at line 200 of file ui_syscalls.c.
Referenced by _et_trap_Argc(), Bot_Interface_ConsoleCommand(), CC_loadconfig(), CC_svcvar(), CG_BuddyVoiceChat_f(), CG_Class_f(), CG_Fade_f(), CG_parseMapVoteListInfo(), CG_parseMapVoteTally(), CG_ReadHuds_f(), CG_scores_cmd(), CG_ServerCommand(), CG_TeamVoiceChat_f(), CG_TestModel_f(), CG_TimerSet_f(), CG_VoiceChat_f(), CG_vstrDown_f(), CG_vstrUp_f(), Cmd_CallVote_f(), Cmd_FireTeam_MP_f(), Cmd_Follow_f(), Cmd_Say_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_Voice_f(), Cmd_WeaponStat_f(), ConcatArgs(), G_Config_v(), G_GetPlayerByName(), G_GetPlayerByNum(), G_IntermissionMapVote(), G_makesc_cmd(), G_MapRestart_v(), G_MatchReset_v(), G_Nextmap_v(), G_ParseCampaigns(), G_PlaySound_Cmd(), G_ref_cmd(), G_Referee_v(), G_refMakeShoutcaster_cmd(), G_refRemoveShoutcaster_cmd(), G_removesc_cmd(), G_sclogin_cmd(), G_ShuffleTeamsXP_NoRestart_v(), G_ShuffleTeamsXP_v(), G_StartMatch_v(), G_statsPrint(), G_SwapTeams_v(), G_Unreferee_v(), G_voteDescription(), G_weaponRankings_cmd(), Svcmd_AddIP_f(), Svcmd_Burn(), Svcmd_CSInfo_f(), Svcmd_Die(), Svcmd_EntityList_f(), Svcmd_Fling(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Svcmd_Pip(), Svcmd_RemoveIP_f(), and Svcmd_Unfreeze().
void trap_Argv (int n, char * buffer, int bufferLength)
trap_Argv
Parameters
[in] n
[in] buffer
[in] bufferLength
Definition at line 211 of file ui_syscalls.c.
Referenced by _et_trap_Argv(), Bot_Interface_ConsoleCommand(), CC_loadconfig(), CC_svcvar(), CG_Argv(), CG_BuddyVoiceChat_f(), CG_Class_f(), CG_MessageMode_f(), CG_ParseMapEntity(), CG_ReadHuds_f(), CG_ServerCommand(), CG_SetWeaponCrosshair_f(), CG_TeamVoiceChat_f(), CG_TimerSet_f(), CG_VoiceChat_f(), ClientCommand(), Cmd_AuthRcon_f(), Cmd_CallVote_f(), Cmd_FireTeam_MP_f(), Cmd_Follow_f(), Cmd_Ignore_f(), Cmd_IntermissionWeaponStats_f(), Cmd_SelectedObjective_f(), Cmd_SetSpawnPoint_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_UnIgnore_f(), Cmd_Voice_f(), Cmd_Vote_f(), Cmd_WeaponStat_f(), ConcatArgs(), ConsoleCommand(), G_commandHelp(), G_IntermissionMapVote(), G_MakeReferee(), G_makesc_cmd(), G_MuteClient(), G_ParseCampaigns(), G_PlayerBan(), G_PlaySound_Cmd(), G_ref_cmd(), G_refMakeShoutcaster_cmd(), G_refMute_cmd(), G_refPlayerPut_cmd(), G_refRemove_cmd(), G_refRemoveShoutcaster_cmd(), G_refWarmup_cmd(), G_refWarning_cmd(), G_RemoveReferee(), G_removesc_cmd(), G_sclogin_cmd(), G_sclogout_cmd(), G_specinvite_cmd(), G_statsPrint(), G_UnMuteClient(), G_Voice(), G_voteDescription(), G_weaponRankings_cmd(), Svcmd_AddIP_f(), Svcmd_Burn(), Svcmd_Campaign_f(), Svcmd_CSInfo_f(), Svcmd_Die(), Svcmd_Fling(), Svcmd_ForceTeam_f(), Svcmd_Freeze(), Svcmd_Gib(), Svcmd_Kick_f(), Svcmd_KickNum_f(), Svcmd_Pip(), Svcmd_Ref_f(), Svcmd_RemoveIP_f(), Svcmd_RevivePlayer(), Svcmd_Unfreeze(), UI_Argv(), and UI_Campaign_f().
void trap_CheckAutoUpdate (void)
trap_CheckAutoUpdate
Definition at line 1151 of file ui_syscalls.c.
Referenced by UI_Init().
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
Parameters
[in] handle
Definition at line 1089 of file ui_syscalls.c.
Referenced by CG_DrawCinematic(), UI_DrawCampaignCinematic(), UI_DrawCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), and UI_DrawPreviewCinematic().
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle. arg0 is the name in the format "idlogo.roq", set arg1 to NULL, alteredstates to qfalse (do not alter gamestate)
This returns a handle.
Parameters
[in] arg0
[in] xpos
[in] ypos
[in] width
[in] height
[in] bits
Returns
Definition at line 1057 of file ui_syscalls.c.
Referenced by CG_PlayCinematic(), UI_DrawCampaignCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawPreviewCinematic(), UI_FeederSelection(), and UI_PlayCinematic().
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
Parameters
[in] handle
Returns
Definition at line 1080 of file ui_syscalls.c.
Referenced by CG_RunCinematicFrame(), UI_DrawCampaignCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawPreviewCinematic(), and UI_RunCinematicFrame().
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 1102 of file ui_syscalls.c.
Referenced by CG_DrawCinematic(), UI_DrawCampaignCinematic(), UI_DrawCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), and UI_DrawPreviewCinematic().
e_status trap_CIN_StopCinematic (int handle)
stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
Parameters
[in] handle
Returns
Definition at line 1069 of file ui_syscalls.c.
Referenced by CG_StopCinematic(), UI_ClanName_HandleKey(), UI_FeederSelection(), UI_RunMenuScript(), and UI_StopCinematic().
int trap_CM_LerpTag (orientation_t * tag, const refEntity_t * refent, const char * tagName, int startIndex)
trap_CM_LerpTag
Parameters
[in] tag
[in] refent
[in] tagName
[in] startIndex - unused
Returns
Definition at line 497 of file ui_syscalls.c.
void trap_Cmd_ExecuteText (int exec_when, const char * text)
trap_Cmd_ExecuteText
Parameters
[in] exec_when
[in] text
Definition at line 221 of file ui_syscalls.c.
Referenced by UI_Campaign_f(), UI_Init(), UI_RunMenuScript(), UI_StartServerRefresh(), and UI_Update().
void trap_Cvar_Create (const char * varName, const char * var_value, int flags)
trap_Cvar_Create
Parameters
[in] varName
[in] var_value
[in] flags
Definition at line 180 of file ui_syscalls.c.
void trap_Cvar_InfoStringBuffer (int bit, char * buffer, int bufsize)
trap_Cvar_InfoStringBuffer
Parameters
[in] bit
[in] buffer
[in] bufsize
Definition at line 191 of file ui_syscalls.c.
void trap_Cvar_LatchedVariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
Parameters
[in] varName
[in] buffer
[in] bufsize
Definition at line 150 of file ui_syscalls.c.
Referenced by G_UpdateCvars().
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
trap_Cvar_Register
Parameters
[in] vmCvar
[in] varName
[in] defaultValue
[in] flags
Definition at line 96 of file ui_syscalls.c.
Referenced by CG_RegisterCvars(), G_DebugOpenSkillLog(), G_RegisterCvars(), G_Script_ScriptLoad(), and UI_RegisterCvars().
void trap_Cvar_Reset (const char * name)
trap_Cvar_Reset
Parameters
[in] name
Definition at line 169 of file ui_syscalls.c.
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 115 of file ui_syscalls.c.
Referenced by _et_trap_Cvar_Set(), BeginIntermission(), BG_PanelButton_EditClick(), BG_setCrosshair(), Bot_Interface_Init(), Bot_Interface_Update(), CG_AdjustAutomapZoom(), CG_Debriefing_ChatEditFinish(), CG_Debriefing_Startup(), CG_DemoClick(), CG_DrawActiveFrame(), CG_DrawConnectScreen(), CG_DrawFlashFade(), CG_DrawTimedMenus(), CG_DrawTimerNormal(), CG_DrawTimersAlt(), CG_EventHandling(), CG_FinishWeaponChange(), CG_Init(), CG_KickAngles(), CG_LimboPanel_NameEditFinish(), CG_LimboPanel_Setup(), CG_LoadHudMenu(), CG_MapRestart(), CG_MessageMode_f(), CG_MessageSend_f(), CG_NewClientInfo(), CG_ParseServerinfo(), CG_ParseWolfinfo(), CG_PredictPlayerState(), CG_ProcessCvars(), CG_RegisterCvars(), CG_RestoreProfile(), CG_ScoresDown_f(), CG_setClientFlags(), CG_SetHud(), CG_Shutdown(), CG_TimerReset_f(), CG_TimerSet_f(), CG_UpdateCvars(), CheckCvars(), CheckExitRules(), CheckWolfMP(), ClientThink_real(), etpro_PlayerInfo(), ExitLevel(), G_BalancedTeams_v(), G_checkReady(), G_ClearMapXP(), G_configSet(), G_deleteStats(), G_InitGame(), G_LogExit(), G_ParseCampaigns(), G_ParseSettings(), G_ReadSessionData(), G_refWarmup_cmd(), G_RegisterCvars(), G_resetModeState(), G_resetRoundState(), G_Script_ScriptLoad(), G_ScriptAction_AlliedRespawntime(), G_ScriptAction_AxisRespawntime(), G_ScriptAction_Cvar(), G_ScriptAction_EntityScriptName(), G_ScriptAction_SetDebugLevel(), G_ScriptAction_SetRoundTimelimit(), G_ShutdownGame(), G_StoreMapXP(), G_UpdateCvars(), G_verifyMatchState(), G_voteFlags(), G_voteSetOnOff(), G_voteSetValue(), G_wipeCvars(), G_WriteClientSessionData(), G_WriteSessionData(), ETInterface::InterfaceSendMessage(), Script_ConditionalScript(), SP_worldspawn(), Svcmd_Campaign_f(), Svcmd_SwapTeams_f(), UI_BuildPlayerList(), UI_Campaign_f(), UI_CheckExecKey(), UI_ClanName_HandleKey(), UI_Crosshair_HandleKey(), UI_DrawCampaignCinematic(), UI_DrawCampaignMapDescription(), UI_DrawCampaignMapPreview(), UI_DrawCampaignName(), UI_DrawCampaignPreview(), UI_DrawLoadPanel(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_GetServerStatusInfo(), UI_GLCustom(), UI_Init(), UI_KeyEvent(), UI_LoadProfiles(), UI_NextOpponent(), UI_Pause(), UI_PriorOpponent(), UI_Refresh(), UI_RegisterCvars(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_ShowPostGame(), UI_StartServerRefresh(), UI_TeamMember_HandleKey(), UI_TeamName_HandleKey(), UI_Update(), and UpdateIPBans().
void trap_Cvar_SetValue (const char * varName, float value)
trap_Cvar_SetValue
Parameters
[in] varName
[in] value
Definition at line 160 of file ui_syscalls.c.
Referenced by UI_Effects_HandleKey(), UI_RunMenuScript(), and UI_Update().
void trap_Cvar_Update (vmCvar_t * vmCvar)
trap_Cvar_Update
Parameters
[in] vmCvar
Definition at line 105 of file ui_syscalls.c.
Referenced by BeginIntermission(), Bot_Interface_Init(), CG_ParseServerinfo(), CG_UpdateCvars(), CheckExitRules(), CheckWolfMP(), G_InitGame(), G_LogExit(), G_RegisterCvars(), G_ShutdownGame(), G_UpdateCvars(), UI_BuildServerDisplayList(), UI_LoadProfiles(), UI_RunMenuScript(), and UI_UpdateCvars().
void trap_Cvar_VariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_VariableStringBuffer
Parameters
[in] varName
[in] buffer
[in] bufsize
Definition at line 139 of file ui_syscalls.c.
Referenced by _et_trap_Cvar_Get(), BG_AddPredictableEventToPlayerstate(), BG_PanelButton_RenderEdit(), CG_AddToNotify(), CG_Cvar_Get(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_ChatEditFinish(), CG_KickAngles(), CG_LimboPanel_NameEditFinish(), CG_LimboPanel_Setup(), CG_LoadHudMenu(), CG_MessageSend_f(), CG_MouseEvent(), CG_ProcessCvars(), CG_RegisterCvars(), CG_SetInitialSnapshot(), CG_UpdateSvCvars(), Cmd_AuthRcon_f(), ExitLevel(), G_Campaign_v(), G_ConfigCheckLocked(), G_Gametype_v(), G_GetMapXP(), G_InitWorldSession(), G_Is_SV_Running(), G_LuaStartVM(), G_Map_v(), G_NextCampaign_v(), G_Nextmap_v(), G_ParseMapSettings(), G_ReadSessionData(), G_refWarmup_cmd(), G_RestartCampaign_v(), G_Script_ScriptLoad(), ETInterface::GetLogPath(), Item_SettingShow(), Script_ConditionalScript(), UI_BuildServerDisplayList(), UI_Cvar_VariableString(), UI_DrawMissionBriefingMap(), UI_DrawMissionBriefingObjectives(), UI_DrawMissionBriefingTitle(), UI_Init(), UI_LoadPanel_RenderHeaderText(), UI_LoadPanel_RenderLoadingText(), UI_RunMenuScript(), and UI_SetActiveMenu().
float trap_Cvar_VariableValue (const char * varName)
trap_Cvar_VariableValue
Parameters
[in] varName
Returns
Definition at line 125 of file ui_syscalls.c.
Referenced by Com_DPrintf(), UI_BuildPlayerList(), UI_DownloadInfo(), UI_DrawLoadPanel(), UI_Init(), UI_KeyEvent(), UI_LoadDemos(), UI_LoadPanel_RenderLoadingText(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_Refresh(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_StartServerRefresh(), UI_TeamMember_HandleKey(), and UI_Update().
void trap_Error (const char * fmt)
trap_Error
Parameters
[in] fmt
Definition at line 73 of file ui_syscalls.c.
Referenced by CG_Error(), Com_Error(), G_Error(), UI_LoadMenus(), and UI_RunMenuScript().
int trap_FS_Delete (const char * filename)
trap_FS_Delete
Parameters
[in] filename
Returns
Definition at line 296 of file ui_syscalls.c.
Referenced by Script_WriteProfile(), and UI_RunMenuScript().
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
Parameters
[in] f
Definition at line 273 of file ui_syscalls.c.
Referenced by _et_trap_FS_FCloseFile(), BG_LoadTraceMap(), CG_AddFlameToScene(), CG_dumpStats(), CG_LoadLocations(), CG_MapVoteList_Draw(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_SaveSpeakersToScript(), CG_scores_cmd(), CG_ServerCommand(), CG_Shutdown(), CG_SoundLoadSoundFiles(), FileExists(), G_configSet(), G_DebugCloseSkillLog(), G_InitGame(), G_isValidConfig(), G_LuaRunIsolated(), G_MapVoteInfoRead(), G_MapVoteInfoWrite(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_Script_ScriptLoad(), G_ShutdownGame(), GeoIP_open(), GetMenuBuffer(), Script_CheckProfile(), Script_ConditionalScript(), Script_WriteProfile(), UI_FeederSelection(), UI_FileText(), and UI_RunMenuScript().
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
trap_FS_FOpenFile
Parameters
[in] qpath
[in] f
[in] mode
Returns
Definition at line 242 of file ui_syscalls.c.
Referenced by _et_trap_FS_FOpenFile(), BG_LoadTraceMap(), CG_AddFlameToScene(), CG_dumpStats(), CG_Init(), CG_LoadLocations(), CG_MapVoteList_Draw(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_SaveSpeakersToScript(), CG_ServerCommand(), CG_SoundLoadSoundFiles(), FileExists(), G_configSet(), G_DebugOpenSkillLog(), G_InitGame(), G_isValidConfig(), G_LuaRunIsolated(), G_MapVoteInfoRead(), G_MapVoteInfoWrite(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_Script_ScriptLoad(), GeoIP_open(), GetMenuBuffer(), Script_CheckProfile(), Script_ConditionalScript(), Script_WriteProfile(), UI_FeederSelection(), UI_FileText(), and UI_RunMenuScript().
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
trap_FS_GetFileList
Parameters
[in] path
[in] extension
[in] listbuf
[in] bufsize
Returns
Definition at line 286 of file ui_syscalls.c.
Referenced by _et_trap_FS_GetFileList(), BeginIntermission(), CG_LocateCampaign(), CG_SpeakerEditor_NoiseEdit_KeyDown(), G_ParseCampaigns(), G_PrintConfigs(), UI_LoadArenas(), UI_LoadCampaigns(), UI_LoadDemos(), UI_LoadMods(), UI_LoadMovies(), and UI_LoadProfiles().
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
trap_FS_Read
Parameters
[in] buffer
[in] len
[in] f
Definition at line 253 of file ui_syscalls.c.
Referenced by _et_trap_FS_Read(), BG_LoadTraceMap(), CG_LoadLocations(), CG_ParseAnimationFiles(), CG_ParseGibModels(), CG_ParseHudHeadConfig(), CG_ParseVoiceChats(), CG_ParseWeaponConfig(), CG_SoundLoadSoundFiles(), G_LuaRunIsolated(), G_MapVoteInfoRead(), G_ParseAnimationFiles(), G_ParseMapSettings(), G_Script_ScriptLoad(), GeoIP_open(), GetMenuBuffer(), Script_CheckProfile(), UI_FileText(), and UI_RunMenuScript().
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
trap_FS_Write
Parameters
[in] buffer
[in] len
[in] f
Definition at line 264 of file ui_syscalls.c.
Referenced by _et_G_LogPrint(), _et_trap_FS_Write(), CG_AddFlameToScene(), CG_printFile(), CG_SaveSpeakersToScript(), CG_scores_cmd(), CG_WriteToLog(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DebugCloseSkillLog(), G_DebugOpenSkillLog(), G_InitGame(), G_LogPrintf(), G_MapVoteInfoWrite(), G_WriteConfigFileString(), Script_WriteProfile(), and UI_RunMenuScript().
void trap_GetAutoUpdate (void)
trap_GetAutoUpdate
Definition at line 1159 of file ui_syscalls.c.
Referenced by UI_Init().
void trap_GetClientState (uiClientState_t * state)
trap_GetClientState
Parameters
[in] state
Definition at line 666 of file ui_syscalls.c.
Referenced by UI_BuildPlayerList(), UI_BuildServerStatus(), UI_ConsoleCommand(), UI_LoadMenus(), UI_LoadPanel_RenderHeaderText(), UI_LoadPanel_RenderLoadingText(), UI_Refresh(), and UI_RunMenuScript().
void trap_GetClipboardData (char * buf, size_t bufsize)
trap_GetClipboardData
Parameters
[in] buf
[in] bufsize
Definition at line 657 of file ui_syscalls.c.
Referenced by UI_Init().
int trap_GetConfigString (int index, char * buff, size_t buffsize)
trap_GetConfigString
Parameters
[in] index
[in] buff
[in] buffsize
Returns
Definition at line 687 of file ui_syscalls.c.
Referenced by UI_BuildPlayerList(), UI_DescriptionForCampaign(), UI_Init(), UI_NameForCampaign(), and UI_RunMenuScript().
void trap_GetGlconfig (glconfig_t * glconfig)
trap_GetGlconfig
Parameters
[in] glconfig
Definition at line 675 of file ui_syscalls.c.
Referenced by CG_Init(), and UI_Init().
void trap_GetHunkData (int * hunkused, int * hunkexpected)
trap_GetHunkData
Parameters
[in] hunkused
[in] hunkexpected
Definition at line 1178 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), CG_LoadPanel_RenderLoadingBar(), and UI_Init().
qboolean trap_GetLimboString (int index, char * buf)
trap_GetLimboString
Parameters
[in] index
[in] buf
Returns
Definition at line 1124 of file ui_syscalls.c.
void trap_Key_ClearStates (void)
trap_Key_ClearStates
Definition at line 629 of file ui_syscalls.c.
Referenced by UI_KeyEvent(), UI_Pause(), UI_RunMenuScript(), and UI_SetActiveMenu().
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
trap_Key_GetBindingBuf
Parameters
[in] keynum
[in] buf
[in] buflen
Definition at line 570 of file ui_syscalls.c.
Referenced by CG_getBindKeyName(), CG_LoadHudMenu(), and UI_Init().
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
Returns
Definition at line 638 of file ui_syscalls.c.
Referenced by CG_Debriefing_Draw(), CG_EventHandling(), CG_MouseEvent(), UI_CheckExecKey(), UI_KeyEvent(), UI_Pause(), UI_RunMenuScript(), and UI_SetActiveMenu().
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
Returns
Definition at line 612 of file ui_syscalls.c.
Referenced by BG_PanelButton_EditClick(), BG_PanelButton_RenderEdit(), CG_Debriefing_ChatEdit_Draw(), CG_LoadHudMenu(), and UI_Init().
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
Parameters
[in] keynum
Returns
Definition at line 603 of file ui_syscalls.c.
Referenced by UI_Init().
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
trap_Key_KeynumToStringBuf
Parameters
[in] keynum
[in] buf
[in] buflen
Definition at line 559 of file ui_syscalls.c.
Referenced by CG_getBindKeyName(), CG_LoadHudMenu(), CG_SpeakerEditorDraw(), and UI_Init().
void trap_Key_KeysForBinding (const char * binding, int * key1, int * key2)
trap_Key_KeysForBinding
Parameters
[in] binding
[in] key1
[in] key2
Note
binding MUST be lower case
Definition at line 583 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), CG_SpeakerEditorDraw(), and UI_Init().
void trap_Key_SetBinding (int keynum, const char * binding)
trap_Key_SetBinding
Parameters
[in] keynum
[in] binding
Definition at line 593 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
Parameters
[in] catcher
Definition at line 647 of file ui_syscalls.c.
Referenced by CG_Debriefing_Draw(), CG_EventHandling(), CG_MouseEvent(), UI_KeyEvent(), UI_Pause(), UI_RunMenuScript(), and UI_SetActiveMenu().
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
Parameters
[in] state
Definition at line 621 of file ui_syscalls.c.
Referenced by BG_PanelButton_EditClick(), CG_LoadHudMenu(), and UI_Init().
int trap_LAN_AddServer (int source, const char * name, const char * addr)
trap_LAN_AddServer
Parameters
[in] source
[in] name
[in] addr
Returns
Definition at line 838 of file ui_syscalls.c.
Referenced by UI_FeederSelectionClick(), and UI_RunMenuScript().
void trap_LAN_ClearPing (int n)
trap_LAN_ClearPing
Parameters
[in] n
Definition at line 745 of file ui_syscalls.c.
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
trap_LAN_CompareServers
Parameters
[in] source
[in] sortKey
[in] sortDir
[in] s1
[in] s2
Returns
Definition at line 802 of file ui_syscalls.c.
Referenced by UI_BinaryServerInsertion(), and UI_ServersQsortCompare().
void trap_LAN_GetGlobalServerAddressString (int n, char * buf, int buflen)
trap_LAN_GetGlobalServerAddressString
Parameters
[in] n
[in] buf
[in] buflen
Definition at line 727 of file ui_syscalls.c.
int trap_LAN_GetGlobalServerCount (void)
trap_LAN_GetGlobalServerCount
Returns
Definition at line 716 of file ui_syscalls.c.
void trap_LAN_GetLocalServerAddressString (int n, char * buf, int buflen)
trap_LAN_GetLocalServerAddressString
Parameters
[in] n
[in] buf
[in] buflen
Definition at line 707 of file ui_syscalls.c.
int trap_LAN_GetLocalServerCount (void)
trap_LAN_GetLocalServerCount
Returns
Definition at line 696 of file ui_syscalls.c.
void trap_LAN_GetPing (int n, char * buf, int buflen, int * pingtime)
trap_LAN_GetPing
Parameters
[in] n
[in] buf
[in] buflen
[in] pingtime
Definition at line 757 of file ui_syscalls.c.
void trap_LAN_GetPingInfo (int n, char * buf, int buflen)
trap_LAN_GetPingInfo
Parameters
[in] n
[in] buf
[in] buflen
Definition at line 768 of file ui_syscalls.c.
int trap_LAN_GetPingQueueCount (void)
trap_LAN_GetPingQueueCount
Returns
Definition at line 736 of file ui_syscalls.c.
void trap_LAN_GetServerAddressString (int source, int n, char * buf, int buflen)
trap_LAN_GetServerAddressString
Parameters
[in] source
[in] n
[in] buf
[in] buflen
Definition at line 814 of file ui_syscalls.c.
Referenced by UI_RunMenuScript().
int trap_LAN_GetServerCount (int source)
trap_LAN_GetServerCount
Parameters
[in] source
Returns
Definition at line 788 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList(), UI_DoServerRefresh(), UI_DrawServerRefreshDate(), UI_ListFavourites_f(), and UI_StopServerRefresh().
void trap_LAN_GetServerInfo (int source, int n, char * buf, int buflen)
trap_LAN_GetServerInfo
Parameters
[in] source
[in] n
[in] buf
[in] buflen
Definition at line 826 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList(), UI_FeederItemText(), UI_FeederSelection(), UI_FeederSelectionClick(), UI_ListFavourites_f(), and UI_RunMenuScript().
int trap_LAN_GetServerPing (int source, int n)
trap_LAN_GetServerPing
Parameters
[in] source
[in] n
Returns
Definition at line 859 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList().
void trap_LAN_LoadCachedServers (void)
trap_LAN_LoadCachedServers
Definition at line 912 of file ui_syscalls.c.
Referenced by UI_Init(), and UI_RunMenuScript().
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
trap_LAN_MarkServerVisible
Parameters
[in] source
[in] n
[in] visible
Definition at line 923 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList(), and UI_StartServerRefresh().
void trap_LAN_RemoveServer (int source, const char * addr)
trap_LAN_RemoveServer
Parameters
[in] source
[in] addr
Definition at line 848 of file ui_syscalls.c.
Referenced by UI_FeederSelectionClick(), UI_RemoveAllFavourites_f(), and UI_RunMenuScript().
void trap_LAN_ResetPings (int n)
trap_LAN_ResetPings
Parameters
[in] n
Definition at line 932 of file ui_syscalls.c.
Referenced by UI_StartServerRefresh(), and UI_UpdatePendingPings().
qboolean trap_LAN_ServerIsInFavoriteList (int source, int n)
trap_LAN_ServerIsInFavoriteList
Parameters
[in] source
[in] n
Returns
Definition at line 893 of file ui_syscalls.c.
Referenced by UI_FeederItemText(), UI_FeederSelectionClick(), and UI_RunMenuScript().
int trap_LAN_ServerIsVisible (int source, int n)
trap_LAN_ServerIsVisible
Parameters
[in] source
[in] n
Returns
Definition at line 870 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList().
int trap_LAN_ServerStatus (const char * serverAddress, char * serverStatus, int maxLen)
trap_LAN_ServerStatus
Parameters
[in] serverAddress
[in] serverStatus
[in] maxLen
Returns
Definition at line 882 of file ui_syscalls.c.
Referenced by UI_BuildServerStatus(), and UI_GetServerStatusInfo().
qboolean trap_LAN_UpdateVisiblePings (int source)
trap_LAN_UpdateVisiblePings
Parameters
[in] source
Returns
Definition at line 778 of file ui_syscalls.c.
Referenced by UI_DoServerRefresh().
int trap_MemoryRemaining (void)
trap_MemoryRemaining
Returns
Definition at line 941 of file ui_syscalls.c.
int trap_Milliseconds (void)
trap_Milliseconds
Returns
Definition at line 84 of file ui_syscalls.c.
Referenced by _et_trap_Milliseconds(), CG_DemoClick(), CG_DemoHelpDraw(), CG_DrawActiveFrame(), CG_DrawFlashFade(), CG_DrawFPS(), CG_DrawInformation(), CG_DrawSpeed(), CG_getBindKeyName(), CG_ShowHelp_Off(), CG_ShowHelp_On(), CG_windowDraw(), CG_windowFree(), CG_windowReset(), CG_wstatsParse_cmd(), DoClientThinks(), G_RunFrame(), UI_LoadMenus(), and vmMain().
void trap_openURL (const char * url)
trap_openURL
Parameters
[in] url
Definition at line 1168 of file ui_syscalls.c.
Referenced by UI_RunMenuScript().
int trap_PC_AddGlobalDefine (char * define)
trap_PC_AddGlobalDefine
Parameters
[in] define
Returns
Definition at line 951 of file ui_syscalls.c.
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
Parameters
[in] handle
Returns
Definition at line 980 of file ui_syscalls.c.
int trap_PC_LoadSource (const char * filename)
trap_PC_LoadSource
Parameters
[in] filename
Returns
Definition at line 970 of file ui_syscalls.c.
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
trap_PC_ReadToken
Parameters
handle
pc_token
Returns
Definition at line 991 of file ui_syscalls.c.
int trap_PC_RemoveAllGlobalDefines (void)
trap_PC_RemoveAllGlobalDefines
Returns
Definition at line 960 of file ui_syscalls.c.
Referenced by UI_Init().
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
trap_PC_SourceFileAndLine
Parameters
[in] handle
[in] filename
[in] line
Returns
Definition at line 1003 of file ui_syscalls.c.
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
Parameters
[in] handle
Returns
Definition at line 1013 of file ui_syscalls.c.
void trap_Print (const char * fmt)
trap_Print
Parameters
[in] fmt
Definition at line 64 of file ui_syscalls.c.
Referenced by CG_AddPMItem(), CG_DPrintf(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_Obituary(), CG_ParseVoiceChats(), CG_Printf(), Com_Printf(), GetMenuBuffer(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadCampaigns(), and UI_LoadCampaignsFromFile().
void trap_R_Add2dPolys (polyVert_t * verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
Parameters
[in] verts
[in] numverts
[in] hShader
Definition at line 430 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
Parameters
[in] org
[in] r
[in] g
[in] b
[in] scale
[in] id
[in] visible
Definition at line 401 of file ui_syscalls.c.
Referenced by CG_Corona(), and CG_Coronas().
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
Parameters
[in] org
[in] radius
[in] intensity
[in] r
[in] g
[in] b
[in] hShader
[in] flags
Definition at line 385 of file ui_syscalls.c.
Referenced by CG_AddExplosion(), CG_AddFlameToScene(), CG_AddLightstyle(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddSpriteExplosion(), CG_DynamiteTrail(), CG_EntityEffects(), CG_MG42EFX(), CG_Missile(), and CG_MortarEFX().
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
trap_R_AddPolyToScene
Parameters
[in] hShader
[in] numVerts
[in] verts
Definition at line 365 of file ui_syscalls.c.
Referenced by CG_AddMarks(), CG_AddParticleToScene(), CG_AddSmokeSprites(), CG_AddTrailToScene(), CG_DrawTracer(), CG_Item(), and CG_PlayerSplash().
void trap_R_AddRefEntityToScene (const refEntity_t * re)
trap_R_AddRefEntityToScene
Parameters
[in] re
Definition at line 354 of file ui_syscalls.c.
Referenced by CG_AddConstRGB(), CG_AddDebrisElementsExtended(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddLineToScene(), CG_AddMoveScaleFade(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddSpriteExplosion(), CG_AddTestModel(), CG_AddViewWeapon(), CG_AddWeaponWithPowerups(), CG_Beam(), CG_Beam_2(), CG_Cabinet(), CG_Constructible(), CG_DamageBlendBlob(), CG_DrawMiscGamemodels(), CG_DrawPlayerHead(), CG_Explosive(), CG_General(), CG_Item(), CG_LoadHudMenu(), CG_MG42EFX(), CG_MortarEFX(), CG_MovePlane(), CG_Mover(), CG_Mover_PostProcess(), CG_PlayerFloatSprite(), CG_Portal(), CG_Prop(), CG_RenderScriptSpeakers(), CG_Trap(), and UI_Init().
void trap_R_ClearScene (void)
trap_R_ClearScene
Definition at line 345 of file ui_syscalls.c.
Referenced by CG_DrawActiveFrame(), CG_DrawPlayerHead(), CG_LoadHudMenu(), and UI_Init().
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] angle
Definition at line 465 of file ui_syscalls.c.
Referenced by CG_DrawRotatedPic().
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
Definition at line 447 of file ui_syscalls.c.
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), CG_DrawBottom_NoScale(), CG_DrawCrosshair(), CG_DrawExpandedAutoMap(), CG_DrawGrid(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawMap(), CG_DrawNoShootIcon(), CG_DrawPic(), CG_DrawPicST(), CG_DrawSides(), CG_DrawSides_NoScale(), CG_DrawSkillBar(), CG_DrawTopBottom(), CG_DrawTopBottom_NoScale(), CG_FillRect(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderCounterNumber(), CG_LoadHudMenu(), CG_SpeakerEditorDraw(), CG_Text_PaintChar(), CG_Text_PaintChar_Ext(), CG_TileClearBox(), Text_PaintChar(), Text_PaintCharExt(), UI_DrawHandlePic(), UI_DrawLoadPanel(), UI_DrawMapPreview(), UI_DrawTopBottom(), UI_FillRect(), and UI_Init().
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
Parameters
[in] model
[in] mins
[in] maxs
Definition at line 476 of file ui_syscalls.c.
Referenced by CG_DrawPlayerHead(), CG_Item(), CG_LoadHudMenu(), CG_RegisterGraphics(), CG_TouchTriggerPrediction(), SP_misc_gamemodel(), and UI_Init().
void trap_R_RegisterFont (const char * fontName, int pointSize, void * font)
trap_R_RegisterFont
Parameters
[in] fontName
[in] pointSize
[in] font
Definition at line 327 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
qhandle_t trap_R_RegisterModel (const char * name)
trap_R_RegisterModel
Parameters
[in] name
Returns
Definition at line 306 of file ui_syscalls.c.
Referenced by BG_RAG_ParseAnimation(), BG_RAG_ParseAnimFile(), CG_AddTestModel(), CG_ConfigStringModified(), CG_LoadHudMenu(), CG_ParseGibModels(), CG_RegisterAcc(), CG_RegisterCharacter(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RegisterSounds(), CG_RW_ParseClient(), CG_RW_ParseModModel(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLinkPart(), CG_SetupCabinets(), CG_TestModel_f(), G_RegisterCharacter(), SP_misc_gamemodel(), SP_worldspawn(), and UI_Init().
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
trap_R_RegisterShaderNoMip
Parameters
[in] name
Returns
Definition at line 337 of file ui_syscalls.c.
Referenced by Asset_Parse(), AssetCache(), BG_PanelButtonsSetup(), CG_AssetCache(), CG_ConfigStringModified(), CG_Debriefing_Mission_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_DrawInformation(), CG_Init(), CG_InitPMGraphics(), CG_LoadHudMenu(), CG_LoadRankIcons(), CG_MapVoteList_Draw(), CG_RegisterGraphics(), CG_RegisterPlayerClasses(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), UI_BuildServerDisplayList(), UI_DrawCampaignMapPreview(), UI_DrawCampaignPreview(), UI_DrawClanLogo(), UI_DrawMapPreview(), UI_DrawMissionBriefingMap(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_FeederItemImage(), UI_FeederSelection(), UI_Init(), and WM_DrawObjectives().
qhandle_t trap_R_RegisterSkin (const char * name)
trap_R_RegisterSkin
Parameters
[in] name
Returns
Definition at line 316 of file ui_syscalls.c.
Referenced by CG_ConfigStringModified(), CG_RegisterAcc(), CG_RegisterCharacter(), CG_RegisterGraphics(), CG_RW_ParseClient(), CG_RW_ParseViewType(), and CG_RW_ParseWeaponLinkPart().
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
trap_R_RemapShader
Parameters
[in] oldShader
[in] newShader
[in] timeOffset
Definition at line 1113 of file ui_syscalls.c.
Referenced by CG_RegisterGraphics(), CG_ServerCommand(), and CG_ShaderStateChanged().
void trap_R_RenderScene (const refdef_t * fd)
trap_R_RenderScene
Parameters
[in] fd
Definition at line 410 of file ui_syscalls.c.
Referenced by CG_DrawActive(), CG_DrawPlayerHead(), CG_DrawSkyBoxPortal(), CG_LoadHudMenu(), and UI_Init().
void trap_R_SetColor (const float * rgba)
trap_R_SetColor
Parameters
[in] rgba
Definition at line 419 of file ui_syscalls.c.
Referenced by _UI_DrawRect(), BG_PanelButtonsRender_Img(), CG_Debriefing_ChatBox_Draw(), CG_Debriefing_PlayerHitRegions_Draw(), CG_Debriefing_PlayerSkills_Draw(), CG_Draw2D(), CG_DrawBreathBar(), CG_DrawCenterString(), CG_DrawConnectScreen(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawCursorhint(), CG_DrawDemoControls(), CG_DrawFireTeamOverlay(), CG_DrawFlag(), CG_DrawFlashFire(), CG_DrawGrid(), CG_DrawLagometer(), CG_DrawLimboMessage(), CG_DrawMap(), CG_DrawMapEntity(), CG_DrawMortarMarker(), CG_DrawMortarReticle(), CG_DrawNoShootIcon(), CG_DrawObjectiveInfo(), CG_DrawPicShadowed(), CG_DrawPlayerHealthBar(), CG_DrawPlayerWeaponIcon(), CG_DrawPMItems(), CG_DrawPMItemsBig(), CG_DrawPowerUps(), CG_DrawRect(), CG_DrawRect_FixedBorder(), CG_DrawStaminaBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawWeapRecharge(), CG_FillRect(), CG_Init(), CG_LimboPanel_Draw(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderHead(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LoadHudMenu(), CG_MapVoteList_Draw(), CG_SpeakerEditorDraw(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), Text_Paint_Ext(), Text_Paint_Limit(), Text_PaintWithCursor_Ext(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawCrosshair(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_FillRect(), UI_Init(), UI_Refresh(), and WM_TeamScoreboard().
int trap_RealTime (qtime_t * qtime)
trap_RealTime
Parameters
[in] qtime
Returns
Definition at line 1042 of file ui_syscalls.c.
Referenced by CG_currentTime_f(), CG_DrawLocalTime(), CG_DrawTimersAlt(), CG_dumpStats(), CG_generateFilename(), CG_GetRealTime(), CG_scores_cmd(), G_DebugAddSkillLevel(), G_DebugAddSkillPoints(), G_DebugCloseSkillLog(), G_DebugOpenSkillLog(), and UI_StartServerRefresh().
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
Parameters
[in] targetvol
[in] time
[in] stopsounds
Definition at line 548 of file ui_syscalls.c.
Referenced by CG_Init(), CG_ServerCommand(), and UI_SetActiveMenu().
void trap_S_FadeBackgroundTrack (float targetvol, int time, int num)
trap_S_FadeBackgroundTrack
Parameters
[in] targetvol
[in] time
[in] num
Definition at line 537 of file ui_syscalls.c.
Referenced by CG_EventHandling(), and CG_ServerCommand().
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
trap_S_RegisterSound
Parameters
[in] sample
[in] compressed
Returns
Definition at line 518 of file ui_syscalls.c.
Referenced by Asset_Parse(), CG_ConfigStringModified(), CG_CustomSound(), CG_Debriefing_Startup(), CG_EntityEvent(), CG_GetSoundFx(), CG_LoadHudMenu(), CG_ParseVoiceChats(), CG_PrecacheFXSounds(), CG_RegisterGameSounds(), CG_RegisterGraphics(), CG_RegisterItemSounds(), CG_RegisterSounds(), CG_RW_ParseClient(), CG_RW_ParseWeaponSound(), CG_SoundPickOldestRandomSound(), CG_SoundScriptPrecache(), CG_SpeakerEditor_NoiseEditFinish(), SP_worldspawn(), and UI_Init().
void trap_S_StartBackgroundTrack (const char * intro, const char * loop, int fadeupTime)
trap_S_StartBackgroundTrack
Parameters
[in] intro
[in] loop
[in] fadeupTime
Definition at line 1032 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), CG_QueueMusic(), CG_ServerCommand(), CG_StartMusic(), and UI_Init().
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
Parameters
[in] sfx
[in] channelNum
Definition at line 507 of file ui_syscalls.c.
Referenced by CG_CheckLocalSounds(), CG_Debriefing_Startup(), CG_DrawPlayerWeaponIcon(), CG_DrawWarmup(), CG_LoadHudMenu(), CG_ParseWolfinfo(), CG_PlayGlobalSound(), CG_PlayScriptSpeaker(), CG_PlayVoiceChat(), and UI_Init().
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
Definition at line 1021 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
const char* trap_TranslateString (const char * fmt)
trap_TranslateString
Parameters
[in] fmt
Returns
Definition at line 1134 of file ui_syscalls.c.
void trap_UpdateScreen (void)
trap_UpdateScreen
Definition at line 484 of file ui_syscalls.c.
Referenced by CG_LoadHudMenu(), and UI_Init().