ET: Legacy: src/ui/ui_loadpanel.c File Reference
ui_loadpanel.c File Reference
#include "ui_local.h"
#include "ui_shared.h"
Macros
#define ESTIMATES 80
Functions
void UI_LoadPanel_RenderHeaderText (panel_button_t *button)
UI_LoadPanel_RenderHeaderText.
void UI_LoadPanel_RenderLoadingText (panel_button_t *button)
UI_LoadPanel_RenderLoadingText.
void UI_DrawLoadPanel (qboolean ownerdraw, qboolean uihack)
UI_DrawLoadPanel.
const char * UI_DownloadInfo (const char *downloadName)
UI_DownloadInfo.
Variables
qboolean bg_loadscreeninited = qfalse
panel_button_text_t missiondescriptionTxt
panel_button_text_t missiondescriptionHeaderTxt
panel_button_text_t campaignpheaderTxt
panel_button_text_t campaignpTxt
panel_button_t loadScreenMap
panel_button_t loadScreenBack
panel_button_t loadingPanelText
panel_button_t campaignPanelText
panel_button_t * loadpanelButtons []
static qboolean connect_ownerdraw
Macro Definition Documentation
#define ESTIMATES 80
Definition at line 223 of file ui_loadpanel.c.
Referenced by UI_DownloadInfo().
Function Documentation
const char* UI_DownloadInfo (const char * downloadName)
UI_DownloadInfo.
Parameters
[in] downloadName
Returns
Definition at line 230 of file ui_loadpanel.c.
Referenced by UI_LoadPanel_RenderLoadingText().
void UI_DrawLoadPanel (qboolean ownerdraw, qboolean uihack)
UI_DrawLoadPanel.
Parameters
[in] ownerdraw
[in] uihack
Definition at line 151 of file ui_loadpanel.c.
Referenced by UI_DrawConnectScreen(), UI_OwnerDraw(), and UI_Refresh().
void UI_LoadPanel_RenderHeaderText (panel_button_t * button)
UI_LoadPanel_RenderHeaderText.
Parameters
[in,out] button
Definition at line 202 of file ui_loadpanel.c.
void UI_LoadPanel_RenderLoadingText (panel_button_t * button)
UI_LoadPanel_RenderLoadingText.
Parameters
[in] button
Definition at line 340 of file ui_loadpanel.c.
Variable Documentation
qboolean bg_loadscreeninited = qfalse
Definition at line 38 of file ui_loadpanel.c.
Referenced by UI_DrawLoadPanel().
panel_button_t campaignPanelText
Initial value:
=
{
    NULL,
    NULL,
    { 470,                        33,   152, 232 },
    { 0,                          0,    0,   0, 0, 0, 0, 0},
    &campaignpTxt,
    NULL,
    NULL,
    UI_LoadPanel_RenderHeaderText,
    NULL,
    0,
}
Definition at line 119 of file ui_loadpanel.c.
panel_button_text_t campaignpheaderTxt
Initial value:
=
{
    0.2f,                                   0.2f,
    { 1.0f,                                 1.0f,1.0f,    0.6f },
    0,                                      0,
    &uiInfo.uiDC.Assets.bg_loadscreenfont2,
}
Definition at line 61 of file ui_loadpanel.c.
panel_button_text_t campaignpTxt
Initial value:
=
{
    0.35f,                                  0.35f,
    { 1.0f,                                 1.0f, 1.0f,  0.6f },
    0,                                      0,
    &uiInfo.uiDC.Assets.bg_loadscreenfont2,
}
Definition at line 69 of file ui_loadpanel.c.
qboolean connect_ownerdraw static
Definition at line 144 of file ui_loadpanel.c.
Referenced by UI_DrawLoadPanel(), and UI_LoadPanel_RenderLoadingText().
panel_button_t loadingPanelText
Initial value:
=
{
    NULL,
    NULL,
    { 460,                         72,   160, 244 },
    { 0,                           0,    0,   0, 0, 0, 0, 0},
    &missiondescriptionTxt,
    NULL,
    NULL,
    UI_LoadPanel_RenderLoadingText,
    NULL,
    0,
}
Definition at line 105 of file ui_loadpanel.c.
panel_button_t* loadpanelButtons[]
Initial value:
=
{
    &loadScreenMap,
    &loadScreenBack,
    &loadingPanelText,
    &campaignPanelText,
    NULL,
}
Definition at line 133 of file ui_loadpanel.c.
panel_button_t loadScreenBack
Initial value:
=
{
    "gfx/loading/camp_side",
    NULL,
    { 440,                    0,  200, 480 },
    { 0,                      0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0,
}
Definition at line 91 of file ui_loadpanel.c.
panel_button_t loadScreenMap
Initial value:
=
{
    "gfx/loading/camp_map",
    NULL,
    { 0,                      0,  440, 480 },
    { 0,                      0,  0,   0, 0, 0, 0, 0},
    NULL,
    NULL,
    NULL,
    BG_PanelButtonsRender_Img,
    NULL,
    0,
}
Definition at line 77 of file ui_loadpanel.c.
panel_button_text_t missiondescriptionHeaderTxt
Initial value:
=
{
    0.2f,                                   0.2f,
    { 0.0f,                                 0.0f,             0.0f,    0.8f },
    0,                                      ITEM_ALIGN_CENTER,
    &uiInfo.uiDC.Assets.bg_loadscreenfont2,
}
Definition at line 53 of file ui_loadpanel.c.
panel_button_text_t missiondescriptionTxt
Initial value:
=
{
    0.2f,                                   0.2f,
    { 0.0f,                                 0.0f,0.0f,    1.f },
    0,                                      0,
    &uiInfo.uiDC.Assets.bg_loadscreenfont2,
}
Definition at line 45 of file ui_loadpanel.c.