ET: Legacy: src/ui/ui_script.c File Reference
ui_script.c File Reference
string allocation/managment
#include "ui_shared.h"
#include "ui_local.h"
Macros
#define CLIPFAIL *bAbort = qtrue; return;
Functions
void Script_Show (itemDef_t *item, qboolean *bAbort, char **args)
Script_Show.
void Script_SetColor (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetColor.
void Script_SetBackground (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetBackground.
void Script_SetTeamColor (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetTeamColor.
void Script_SetItemColor (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetItemColor.
void Script_SetMenuItemColor (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetMenuItemColor.
void Script_Hide (itemDef_t *item, qboolean *bAbort, char **args)
Script_Hide.
void Script_FadeIn (itemDef_t *item, qboolean *bAbort, char **args)
Script_FadeIn.
void Script_FadeOut (itemDef_t *item, qboolean *bAbort, char **args)
Script_FadeOut.
void Script_Open (itemDef_t *item, qboolean *bAbort, char **args)
Script_Open.
void Script_FadeInMenu (itemDef_t *item, qboolean *bAbort, char **args)
Script_FadeInMenu.
void Script_FadeOutMenu (itemDef_t *item, qboolean *bAbort, char **args)
Script_FadeOutMenu.
void Script_ConditionalOpen (itemDef_t *item, qboolean *bAbort, char **args)
Script_ConditionalOpen.
void Script_ConditionalScript (itemDef_t *item, qboolean *bAbort, char **args)
Script_ConditionalScript.
void Script_Close (itemDef_t *item, qboolean *bAbort, char **args)
Script_Close.
void Script_CloseAll (itemDef_t *item, qboolean *bAbort, char **args)
Script_CloseAll.
void Script_CloseAllOtherMenus (itemDef_t *item, qboolean *bAbort, char **args)
Script_CloseAllOtherMenus.
void Script_Transition (itemDef_t *item, qboolean *bAbort, char **args)
Script_Transition.
void Script_Orbit (itemDef_t *item, qboolean *bAbort, char **args)
Script_Orbit.
void Script_SetFocus (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetFocus.
void Script_ClearFocus (itemDef_t *item, qboolean *bAbort, char **args)
Script_ClearFocus.
void Script_SetPlayerModel (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetPlayerModel.
void Script_SetPlayerHead (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetPlayerHead.
void Script_ClearCvar (itemDef_t *item, qboolean *bAbort, char **args)
Script_ClearCvar.
void Script_SetCvar (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetCvar.
void Script_CopyCvar (itemDef_t *item, qboolean *bAbort, char **args)
Script_CopyCvar.
void Script_Exec (itemDef_t *item, qboolean *bAbort, char **args)
Script_Exec.
void Script_ExecNOW (itemDef_t *item, qboolean *bAbort, char **args)
Script_ExecNOW.
void Script_Play (itemDef_t *item, qboolean *bAbort, char **args)
Script_Play.
void Script_playLooped (itemDef_t *item, qboolean *bAbort, char **args)
Script_playLooped.
void Script_AddListItem (itemDef_t *item, qboolean *bAbort, char **args)
Script_AddListItem.
void Script_CheckAutoUpdate (itemDef_t *item, qboolean *bAbort, char **args)
Script_CheckAutoUpdate.
void Script_GetAutoUpdate (itemDef_t *item, qboolean *bAbort, char **args)
Script_GetAutoUpdate.
void Script_SetMenuFocus (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetMenuFocus.
qboolean Script_CheckProfile (const char *profile_path)
Script_CheckProfile.
qboolean Script_WriteProfile (const char *profile_path)
Script_WriteProfile.
void Script_ExecWolfConfig (itemDef_t *item, qboolean *bAbort, char **args)
Script_ExecWolfConfig.
void Script_SetEditFocus (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetEditFocus.
void Script_Abort (itemDef_t *item, qboolean *bAbort, char **args)
Script_Abort.
void Script_GetClipboard (itemDef_t *item, qboolean *bAbort, char **args)
Script_GetClipboard.
void Script_ToggleCvarBit (itemDef_t *item, qboolean *bAbort, char **args)
This is for toggling integer cvars using bitflags.
void Script_SetTextStyle (itemDef_t *item, qboolean *bAbort, char **args)
Script_SetTextStyle.
void Script_Skip (itemDef_t *item, qboolean *bAbort, char **args)
Script_Skip.
void Item_RunScript (itemDef_t *item, qboolean *bAbort, const char *s)
Item_RunScript.
Variables
commandDef_t commandList []
size_t scriptCommandCount = sizeof(commandList) / sizeof(commandDef_t)
Detailed Description
string allocation/managment
Definition in file ui_script.c.
Macro Definition Documentation
#define CLIPFAIL *bAbort = qtrue; return;
Referenced by Script_GetClipboard().
Function Documentation
void Item_RunScript (itemDef_t * item, qboolean * bAbort, const char * s)
Item_RunScript.
Parameters
[in] item
[in,out] bAbort
[in] s
Definition at line 1463 of file ui_script.c.
Referenced by Item_Action(), Item_Combo_HandleKey(), Item_HandleKey(), Item_ListBox_HandleKey(), Item_MouseEnter(), Item_MouseLeave(), Item_SetFocus(), Item_TextField_HandleKey(), Menu_ClearFocus(), Menu_HandleKey(), Menu_Paint(), Menu_RunCloseScript(), Menus_Activate(), Script_ConditionalScript(), Script_SetEditFocus(), and Script_SetFocus().
void Script_Abort (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Abort.
Parameters
item - unused
[out] bAbort
args - unused
Definition at line 1277 of file ui_script.c.
void Script_AddListItem (itemDef_t * item, qboolean * bAbort, char ** args)
Script_AddListItem.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 1052 of file ui_script.c.
void Script_CheckAutoUpdate (itemDef_t * item, qboolean * bAbort, char ** args)
Script_CheckAutoUpdate.
Parameters
item - unused
bAbort - unused
args - unused
Definition at line 1073 of file ui_script.c.
qboolean Script_CheckProfile (const char * profile_path)
Script_CheckProfile.
Parameters
[in] profile_path
Returns
Definition at line 1116 of file ui_script.c.
Referenced by Script_ExecWolfConfig().
void Script_ClearCvar (itemDef_t * item, qboolean * bAbort, char ** args)
Script_ClearCvar.
Parameters
item - unused
bAbort - unused
[in] args
Note
The parser misreads setCvar "bleh" "" you have to use clearCvar "bleh"
Definition at line 936 of file ui_script.c.
void Script_ClearFocus (itemDef_t * item, qboolean * bAbort, char ** args)
Script_ClearFocus.
Parameters
[in] item
bAbort - unused
args - unused
Definition at line 889 of file ui_script.c.
void Script_Close (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Close.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 764 of file ui_script.c.
void Script_CloseAll (itemDef_t * item, qboolean * bAbort, char ** args)
Script_CloseAll.
Parameters
item - unused
bAbort - unused
args - unused
Definition at line 780 of file ui_script.c.
void Script_CloseAllOtherMenus (itemDef_t * item, qboolean * bAbort, char ** args)
Script_CloseAllOtherMenus.
Parameters
[in] item
bAbort - unused
args - unused
Definition at line 791 of file ui_script.c.
void Script_ConditionalOpen (itemDef_t * item, qboolean * bAbort, char ** args)
Script_ConditionalOpen.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 375 of file ui_script.c.
void Script_ConditionalScript (itemDef_t * item, qboolean * bAbort, char ** args)
Script_ConditionalScript.
Parameters
[in] item
[in] bAbort
[in] args
Definition at line 426 of file ui_script.c.
void Script_CopyCvar (itemDef_t * item, qboolean * bAbort, char ** args)
Script_CopyCvar.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 968 of file ui_script.c.
void Script_Exec (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Exec.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 987 of file ui_script.c.
void Script_ExecNOW (itemDef_t * item, qboolean * bAbort, char ** args)
Script_ExecNOW.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 1003 of file ui_script.c.
void Script_ExecWolfConfig (itemDef_t * item, qboolean * bAbort, char ** args)
Script_ExecWolfConfig.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 1190 of file ui_script.c.
void Script_FadeIn (itemDef_t * item, qboolean * bAbort, char ** args)
Script_FadeIn.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 295 of file ui_script.c.
void Script_FadeInMenu (itemDef_t * item, qboolean * bAbort, char ** args)
Script_FadeInMenu.
Parameters
item - unused
[in] bAbort
[in] args
Definition at line 343 of file ui_script.c.
void Script_FadeOut (itemDef_t * item, qboolean * bAbort, char ** args)
Script_FadeOut.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 311 of file ui_script.c.
void Script_FadeOutMenu (itemDef_t * item, qboolean * bAbort, char ** args)
Script_FadeOutMenu.
Parameters
item - unused
[in] bAbort - unused
[in] args
Definition at line 359 of file ui_script.c.
void Script_GetAutoUpdate (itemDef_t * item, qboolean * bAbort, char ** args)
Script_GetAutoUpdate.
Parameters
item - unused
bAbort - unused
args - unused
Definition at line 1084 of file ui_script.c.
void Script_GetClipboard (itemDef_t * item, qboolean * bAbort, char ** args)
Script_GetClipboard.
Parameters
item - unused
bAbort
[in] args
Todo:
FIXME: something need to be fixed here
Todo:
: handle
Definition at line 1289 of file ui_script.c.
void Script_Hide (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Hide.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 279 of file ui_script.c.
void Script_Open (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Open.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 327 of file ui_script.c.
void Script_Orbit (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Orbit.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 836 of file ui_script.c.
void Script_Play (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Play.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 1019 of file ui_script.c.
void Script_playLooped (itemDef_t * item, qboolean * bAbort, char ** args)
Script_playLooped.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 1035 of file ui_script.c.
void Script_SetBackground (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetBackground.
Parameters
[out] item
bAbort - unused
[in] args
Definition at line 109 of file ui_script.c.
void Script_SetColor (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetColor.
Parameters
[in] item
bAbort - unused
[in,out] args
Definition at line 61 of file ui_script.c.
void Script_SetCvar (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetCvar.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 952 of file ui_script.c.
void Script_SetEditFocus (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetEditFocus.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 1229 of file ui_script.c.
void Script_SetFocus (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetFocus.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 858 of file ui_script.c.
void Script_SetItemColor (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetItemColor.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 147 of file ui_script.c.
void Script_SetMenuFocus (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetMenuFocus.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 1095 of file ui_script.c.
void Script_SetMenuItemColor (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetMenuItemColor.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 213 of file ui_script.c.
void Script_SetPlayerHead (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetPlayerHead.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 916 of file ui_script.c.
void Script_SetPlayerModel (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetPlayerModel.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 900 of file ui_script.c.
void Script_SetTeamColor (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetTeamColor.
Parameters
[out] item
bAbort - unused
args - unused
Definition at line 126 of file ui_script.c.
void Script_SetTextStyle (itemDef_t * item, qboolean * bAbort, char ** args)
Script_SetTextStyle.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 1367 of file ui_script.c.
void Script_Show (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Show.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 45 of file ui_script.c.
void Script_Skip (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Skip.
Parameters
item - unused
bAbort - unused
args - unused
Definition at line 1401 of file ui_script.c.
void Script_ToggleCvarBit (itemDef_t * item, qboolean * bAbort, char ** args)
This is for toggling integer cvars using bitflags.
Parameters
item - unused
bAbort - unused
[in] args
Definition at line 1344 of file ui_script.c.
void Script_Transition (itemDef_t * item, qboolean * bAbort, char ** args)
Script_Transition.
Parameters
[in] item
bAbort - unused
[in] args
Definition at line 813 of file ui_script.c.
qboolean Script_WriteProfile (const char * profile_path)
Script_WriteProfile.
Parameters
[in] profile_path
Returns
Definition at line 1153 of file ui_script.c.
Referenced by Script_ExecWolfConfig().
Variable Documentation
commandDef_t commandList[]
Definition at line 1406 of file ui_script.c.
size_t scriptCommandCount = sizeof(commandList) / sizeof(commandDef_t)
Definition at line 1455 of file ui_script.c.
Referenced by Item_RunScript().