ET: Legacy: src/ui/ui_main.c File Reference
ui_main.c File Reference
#include "ui_local.h"
Data Structures
struct serverStatusCvar_t
struct cvarTable_t
Macros
#define UI_FPS_FRAMES 4
#define MISSING_FILES_MSG "The following packs are missing:"
Functions
static void UI_StartServerRefresh (qboolean full)
UI_StartServerRefresh.
static void UI_StopServerRefresh (void)
UI_StopServerRefresh.
static void UI_DoServerRefresh (void)
UI_DoServerRefresh.
static void UI_FeederSelection (int feederID, int index)
UI_FeederSelection.
static qboolean UI_FeederSelectionClick (itemDef_t *item)
UI_FeederSelectionClick.
static void UI_BuildServerDisplayList (int force)
UI_BuildServerDisplayList.
static void UI_BuildServerStatus (qboolean force)
UI_BuildServerStatus.
static int QDECL UI_ServersQsortCompare (const void *arg1, const void *arg2)
UI_ServersQsortCompare.
static int UI_MapCountByGameType (qboolean singlePlayer)
UI_MapCountByGameType.
static const char * UI_SelectedMap (qboolean singlePlayer, int index, int *actual)
UI_SelectedMap.
static const char * UI_SelectedCampaign (int index, int *actual)
UI_SelectedCampaign.
static int UI_CampaignCount (qboolean singlePlayer)
UI_CampaignCount.
qboolean UI_CheckExecKey (int key)
UI_CheckExecKey.
static void UI_ParseGameInfo (const char *teamFile)
UI_ParseGameInfo.
void Menu_ShowItemByName (menuDef_t *menu, const char *p, qboolean bShow)
Menu_ShowItemByName.
void UI_Init (int legacyClient, int clientVersion)
_UI_Init
void UI_Shutdown (void)
_UI_Shutdown
void UI_KeyEvent (int key, qboolean down)
_UI_KeyEvent
void UI_MouseEvent (int dx, int dy)
_UI_MouseEvent
void UI_Refresh (int realtime)
_UI_Refresh
qboolean _UI_IsFullscreen (void)
_UI_IsFullscreen
Q_EXPORT intptr_t vmMain (intptr_t command, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11)
vmMain This is the only way control passes into the module. This must be the very first function compiled into the .qvm file
void AssetCache (void)
AssetCache.
void _UI_DrawSides (float x, float y, float w, float h, float size)
_UI_DrawSides
void _UI_DrawTopBottom (float x, float y, float w, float h, float size)
_UI_DrawTopBottom
void _UI_DrawRect (float x, float y, float width, float height, float size, const float *color)
UI_DrawRect Coordinates are 640*480 virtual values.
void Text_SetActiveFont (int font)
Text_SetActiveFont.
int Text_Width_Ext (const char *text, float scale, int limit, fontHelper_t *font)
Text_Width_Ext.
int Text_Width (const char *text, float scale, int limit)
Text_Width.
int Multiline_Text_Width (const char *text, float scale, int limit)
Multiline_Text_Width.
int Text_Height_Ext (const char *text, float scale, int limit, fontHelper_t *font)
Text_Height_Ext.
int Text_Height (const char *text, float scale, int limit)
Text_Height.
int Multiline_Text_Height (const char *text, float scale, int limit)
Multiline_Text_Height.
void Text_PaintCharExt (float x, float y, float w, float h, float scalex, float scaley, float s, float t, float s2, float t2, qhandle_t hShader)
Text_PaintCharExt.
void Text_PaintChar (float x, float y, float w, float h, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
Text_PaintChar.
void Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
Text_Paint_Ext.
void Text_Paint (float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
Text_Paint.
void Text_PaintWithCursor_Ext (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style, fontHelper_t *font)
Text_PaintWithCursor_Ext.
void Text_PaintWithCursor (float x, float y, float scale, vec4_t color, const char *text, int cursorPos, const char *cursor, int limit, int style)
Text_PaintWithCursor.
static void Text_Paint_Limit (float *maxX, float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit)
Text_Paint_Limit.
void UI_ShowPostGame ()
UI_ShowPostGame.
char * GetMenuBuffer (const char *filename)
GetMenuBuffer.
qboolean Asset_Parse (int handle)
Asset_Parse.
void UI_Report (void)
UI_Report.
qboolean UI_ParseMenu (const char *menuFile)
UI_ParseMenu.
qboolean Load_Menu (int handle)
Load_Menu.
void UI_LoadMenus (const char *menuFile, qboolean reset)
UI_LoadMenus.
void UI_Load (void)
UI_Load.
static void UI_DrawClanName (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawClanName.
static void UI_DrawGameType (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawGameType.
static int UI_TeamIndexFromName (const char *name)
UI_TeamIndexFromName.
static void UI_DrawClanLogo (rectDef_t *rect, float scale, vec4_t color)
UI_DrawClanLogo.
static void UI_DrawClanCinematic (rectDef_t *rect, float scale, vec4_t color)
UI_DrawClanCinematic.
static void UI_DrawPreviewCinematic (rectDef_t *rect, float scale, vec4_t color)
UI_DrawPreviewCinematic.
static void UI_DrawTeamName (rectDef_t *rect, float scale, vec4_t color, qboolean blue, int textStyle)
UI_DrawTeamName.
static void UI_DrawEffects (rectDef_t *rect, float scale, vec4_t color)
UI_DrawEffects.
void UI_DrawMapPreview (rectDef_t *rect, float scale, vec4_t color, qboolean net)
UI_DrawMapPreview.
void UI_DrawNetMapPreview (rectDef_t *rect, float scale, vec4_t color, qboolean net)
UI_DrawNetMapPreview.
static void UI_DrawMapCinematic (rectDef_t *rect, float scale, vec4_t color, qboolean net)
UI_DrawMapCinematic.
static void UI_DrawCampaignPreview (rectDef_t *rect, float scale, vec4_t color, qboolean net)
UI_DrawCampaignPreview.
static void UI_DrawCampaignCinematic (rectDef_t *rect, float scale, vec4_t color, qboolean net)
UI_DrawCampaignCinematic.
static void UI_DrawCampaignName (rectDef_t *rect, float scale, vec4_t color, int textStyle, qboolean net)
UI_DrawCampaignName.
void UI_DrawCampaignDescription (rectDef_t *rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align, qboolean net)
UI_DrawCampaignDescription.
void UI_DrawGametypeDescription (rectDef_t *rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align, qboolean net)
UI_DrawGametypeDescription.
static void UI_DrawCampaignMapDescription (rectDef_t *rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align, qboolean net, int number)
UI_DrawCampaignMapDescription.
static void UI_DrawCampaignMapPreview (rectDef_t *rect, float scale, vec4_t color, qboolean net, int map)
UI_DrawCampaignMapPreview.
static void UI_DrawMissionBriefingMap (rectDef_t *rect)
UI_DrawMissionBriefingMap.
static void UI_DrawMissionBriefingTitle (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawMissionBriefingTitle.
static void UI_DrawMissionBriefingObjectives (rectDef_t *rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align)
UI_DrawMissionBriefingObjectives.
static void UI_DrawNetFilter (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawNetFilter.
static void UI_NextOpponent (void)
UI_NextOpponent.
static void UI_PriorOpponent (void)
UI_PriorOpponent.
static void UI_DrawPlayerLogo (rectDef_t *rect, vec3_t color)
UI_DrawPlayerLogo.
static void UI_DrawPlayerLogoMetal (rectDef_t *rect, vec3_t color)
UI_DrawPlayerLogoMetal.
static void UI_DrawPlayerLogoName (rectDef_t *rect, vec3_t color)
UI_DrawPlayerLogoName.
static void UI_DrawOpponentLogo (rectDef_t *rect, vec3_t color)
UI_DrawOpponentLogo.
static void UI_DrawOpponentLogoMetal (rectDef_t *rect, vec3_t color)
UI_DrawOpponentLogoMetal.
static void UI_DrawOpponentLogoName (rectDef_t *rect, vec3_t color)
UI_DrawOpponentLogoName.
static void UI_DrawOpponentName (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawOpponentName.
static int UI_OwnerDrawWidth (int ownerDraw, float scale)
UI_OwnerDrawWidth.
static void UI_DrawRedBlue (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawRedBlue.
static void UI_DrawCrosshair (rectDef_t *rect, float scale, vec4_t color)
UI_DrawCrosshair.
static void UI_BuildPlayerList (void)
UI_BuildPlayerList.
static void UI_DrawSelectedPlayer (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawSelectedPlayer.
static void UI_DrawServerRefreshDate (rectDef_t *rect, float scale, vec4_t color, int textStyle)
UI_DrawServerRefreshDate.
static void UI_DrawServerMOTD (rectDef_t *rect, float scale, vec4_t color)
UI_DrawServerMOTD.
static void UI_DrawKeyBindStatus (rectDef_t *rect, float scale, vec4_t color, int textStyle, float text_x, float text_y)
UI_DrawKeyBindStatus.
static void UI_ParseGLConfig (void)
UI_ParseGLConfig.
static void UI_OwnerDraw (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, int special, float scale, vec4_t color, qhandle_t shader, int textStyle)
UI_OwnerDraw.
qboolean UI_OwnerDrawVisible (int flags)
UI_OwnerDrawVisible.
static qboolean UI_Effects_HandleKey (int flags, int *special, int key)
UI_Effects_HandleKey.
static qboolean UI_ClanName_HandleKey (int flags, int *special, int key)
UI_ClanName_HandleKey.
static qboolean UI_GameType_HandleKey (int flags, int *special, int key, qboolean resetMap)
UI_GameType_HandleKey.
static qboolean UI_TeamName_HandleKey (int flags, int *special, int key, qboolean blue)
UI_TeamName_HandleKey.
static qboolean UI_TeamMember_HandleKey (int flags, int *special, int key, qboolean blue, int num)
UI_TeamMember_HandleKey.
static qboolean UI_NetFilter_HandleKey (int flags, int *special, int key)
UI_NetFilter_HandleKey.
static qboolean UI_OpponentName_HandleKey (int flags, int *special, int key)
UI_OpponentName_HandleKey.
static qboolean UI_RedBlue_HandleKey (int flags, int *special, int key)
UI_RedBlue_HandleKey.
static qboolean UI_Crosshair_HandleKey (int flags, int *special, int key)
UI_Crosshair_HandleKey.
static qboolean UI_SelectedPlayer_HandleKey (int flags, int *special, int key)
UI_SelectedPlayer_HandleKey.
static qboolean UI_OwnerDrawHandleKey (int ownerDraw, int flags, int *special, int key)
UI_OwnerDrawHandleKey.
static float UI_GetValue (int ownerDraw, int type)
UI_GetValue.
void UI_ServersSort (int column, qboolean force)
UI_ServersSort.
int QDECL UI_SortMods (const void *a, const void *b)
Sorting the mods list.
static void UI_LoadMods (void)
UI_LoadMods.
static void UI_LoadProfiles (void)
UI_LoadProfiles.
static void UI_LoadMovies (void)
UI_LoadMovies.
static void UI_LoadDemos (void)
UI_LoadDemos.
void UI_Update (const char *name)
UI_Update.
void UI_GLCustom ()
UI_GLCustom.
void UI_RunMenuScript (char **args)
UI_RunMenuScript.
static void UI_GetTeamColor (vec4_t *color)
UI_GetTeamColor.
static void UI_InsertServerIntoDisplayList (int num, int position)
UI_InsertServerIntoDisplayList.
static void UI_RemoveServerFromDisplayList (int num)
UI_RemoveServerFromDisplayList.
static void UI_BinaryServerInsertion (int num)
UI_BinaryServerInsertion.
static void UI_SortServerStatusInfo (serverStatusInfo_t *info)
UI_SortServerStatusInfo.
static int UI_GetServerStatusInfo (const char *serverAddress, serverStatusInfo_t *info)
UI_GetServerStatusInfo.
static int UI_FeederCount (int feederID)
UI_FeederCount.
static void UI_UpdatePendingPings (void)
UI_UpdatePendingPings.
static void UI_FeederAddItem (int feederID, const char *name, int index)
UI_FeederAddItem.
static const char * UI_FileText (const char *fileName)
UI_FileText.
const char * UI_FeederItemText (int feederID, int index, int column, qhandle_t *handles, int *numhandles)
UI_FeederItemText.
static qhandle_t UI_FeederItemImage (int feederID, int index)
UI_FeederItemImage.
void Item_ListBox_MouseEnter (itemDef_t *item, float x, float y, qboolean click)
Item_ListBox_MouseEnter.
static qboolean GameType_Parse (char **p, qboolean join)
GameType_Parse.
static void UI_Pause (qboolean b)
UI_Pause.
static int UI_PlayCinematic (const char *name, float x, float y, float w, float h)
UI_PlayCinematic.
static void UI_StopCinematic (int handle)
UI_StopCinematic.
static void UI_DrawCinematic (int handle, float x, float y, float w, float h)
UI_DrawCinematic.
static void UI_RunCinematicFrame (int handle)
UI_RunCinematicFrame.
uiMenuCommand_t UI_GetActiveMenu (void)
_UI_GetActiveMenu
void UI_SetActiveMenu (uiMenuCommand_t menu)
_UI_SetActiveMenu
void UI_ReadableSize (char *buf, int bufsize, int value)
UI_ReadableSize.
void UI_PrintTime (char *buf, int bufsize, int time)
UI_PrintTime.
void UI_DrawConnectScreen (qboolean overlay)
This will also be overlaid on the cgame info screen during loading to prevent it from blinking away too rapidly on local or lan games.
void UI_RegisterCvars (void)
UI_RegisterCvars.
void UI_UpdateCvars (void)
UI_UpdateCvars.
void UI_Campaign_f (void)
UI_Campaign_f.
void UI_ListCampaigns_f (void)
UI_ListCampaigns_f.
void UI_ListFavourites_f (void)
Prints favourite servers list to console.
void UI_RemoveAllFavourites_f (void)
Removes all favourite servers from cache.
Variables
uiInfo_t uiInfo
static const char * MonthAbbrev []
static const serverFilter_t serverFilters []
static const int numServerFilters = sizeof(serverFilters) / sizeof(serverFilter_t)
static const char * netnames []
static int gamecodetoui [] = { 4, 2, 3, 0, 5, 1, 6 }
static int uitogamecode [] = { 4, 6, 2, 3, 1, 5, 7 }
static char translated_yes [4]
static char translated_no [4]
char * defaultMenu = NULL
static qboolean updateModel = qtrue
serverStatusCvar_t serverStatusCvars []
static uiMenuCommand_t menutype = UIMENU_NONE
vmCvar_t ui_brassTime
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairInfo
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_drawCrosshairPickups
vmCvar_t ui_marks
vmCvar_t ui_autoactivate
vmCvar_t ui_selectedPlayer
vmCvar_t ui_selectedPlayerName
vmCvar_t ui_netSource
vmCvar_t ui_menuFiles
vmCvar_t ui_gameType
vmCvar_t ui_netGameType
vmCvar_t ui_joinGameType
vmCvar_t ui_dedicated
vmCvar_t ui_serverFilterType
vmCvar_t ui_currentNetMap
vmCvar_t ui_currentMap
vmCvar_t ui_mapIndex
vmCvar_t ui_browserShowEmptyOrFull
vmCvar_t ui_browserShowPasswordProtected
vmCvar_t ui_browserShowFriendlyFire
vmCvar_t ui_browserShowMaxlives
vmCvar_t ui_browserShowAntilag
vmCvar_t ui_browserShowWeaponsRestricted
vmCvar_t ui_browserShowTeamBalanced
vmCvar_t ui_browserShowHumans
vmCvar_t ui_browserModFilter
vmCvar_t ui_browserMapFilter
vmCvar_t ui_browserMapFilterCheckBox
vmCvar_t ui_browserOssFilter
vmCvar_t ui_serverStatusTimeOut
vmCvar_t ui_friendlyFire
vmCvar_t ui_userAlliedRespawnTime
vmCvar_t ui_userAxisRespawnTime
vmCvar_t ui_glCustom
vmCvar_t g_gameType
vmCvar_t cl_profile
vmCvar_t cl_defaultProfile
vmCvar_t ui_profile
vmCvar_t ui_currentNetCampaign
vmCvar_t ui_currentCampaign
vmCvar_t ui_campaignIndex
vmCvar_t ui_currentCampaignCompleted
vmCvar_t ui_blackout
vmCvar_t ui_cg_crosshairColor
vmCvar_t ui_cg_crosshairColorAlt
vmCvar_t ui_cg_crosshairAlpha
vmCvar_t ui_cg_crosshairAlphaAlt
vmCvar_t ui_cg_crosshairSize
vmCvar_t cl_bypassMouseInput
vmCvar_t ui_serverBrowserSettings
static cvarTable_t cvarTable []
static const unsigned int cvarTableSize = sizeof(cvarTable) / sizeof(cvarTable[0])
Macro Definition Documentation
#define MISSING_FILES_MSG "The following packs are missing:"
Definition at line 8315 of file ui_main.c.
Referenced by UI_SetActiveMenu().
#define UI_FPS_FRAMES 4
Definition at line 882 of file ui_main.c.
Referenced by UI_Refresh().
Function Documentation
void _UI_DrawRect (float x, float y, float width, float height, float size, const float * color)
UI_DrawRect Coordinates are 640*480 virtual values.
Parameters
[in] x
[in] y
[in] width
[in] height
[in] size
[in] color
Definition at line 238 of file ui_main.c.
Referenced by UI_Init().
void _UI_DrawSides (float x, float y, float w, float h, float size)
_UI_DrawSides
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Definition at line 204 of file ui_main.c.
Referenced by _UI_DrawRect(), and UI_Init().
void _UI_DrawTopBottom (float x, float y, float w, float h, float size)
_UI_DrawTopBottom
Parameters
[in] x
[in] y
[in] w
[in] h
[in] size
Definition at line 220 of file ui_main.c.
Referenced by _UI_DrawRect(), and UI_Init().
qboolean _UI_IsFullscreen (void)
_UI_IsFullscreen
Returns
Definition at line 8536 of file ui_main.c.
Referenced by vmMain().
qboolean Asset_Parse (int handle)
Asset_Parse.
Parameters
[in] handle
Returns
Definition at line 1011 of file ui_main.c.
Referenced by UI_ParseMenu().
void AssetCache (void)
AssetCache.
Definition at line 163 of file ui_main.c.
Referenced by UI_Init().
static qboolean GameType_Parse (char ** p, qboolean join) static
GameType_Parse.
Parameters
[in] p
[in] join
Returns
Definition at line 7793 of file ui_main.c.
Referenced by UI_ParseGameInfo().
char* GetMenuBuffer (const char * filename)
GetMenuBuffer.
Parameters
[in] filename
Returns
Definition at line 980 of file ui_main.c.
Referenced by UI_ParseGameInfo().
void Item_ListBox_MouseEnter (itemDef_t * item, float x, float y, qboolean click)
Item_ListBox_MouseEnter.
Parameters
[in] item
[in] x
[in] y
[in] click
Definition at line 635 of file ui_menuitem.c.
Referenced by Item_ListBox_HandleKey(), Item_MouseEnter(), UI_FeederSelection(), and UI_FeederSelectionClick().
qboolean Load_Menu (int handle)
Load_Menu.
Parameters
[in] handle
Returns
Definition at line 1245 of file ui_main.c.
Referenced by UI_LoadMenus().
void Menu_ShowItemByName (menuDef_t * menu, const char * p, qboolean bShow)
Menu_ShowItemByName.
Parameters
[in] menu
[in] p
[in] bShow
Definition at line 567 of file ui_menu.c.
Referenced by Script_Hide(), Script_Show(), UI_BuildServerStatus(), UI_GetServerStatusInfo(), and UI_RunMenuScript().
int Multiline_Text_Height (const char * text, float scale, int limit)
Multiline_Text_Height.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 455 of file ui_main.c.
Referenced by UI_Init().
int Multiline_Text_Width (const char * text, float scale, int limit)
Multiline_Text_Width.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 322 of file ui_main.c.
Referenced by UI_Init().
int Text_Height (const char * text, float scale, int limit)
Text_Height.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 441 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawCampaignMapDescription(), UI_DrawGametypeDescription(), UI_DrawMissionBriefingObjectives(), and UI_Init().
int Text_Height_Ext (const char * text, float scale, int limit, fontHelper_t * font)
Text_Height_Ext.
Parameters
[in] text
[in] scale
[in] limit
[in] font
Returns
Definition at line 394 of file ui_main.c.
Referenced by Text_Height(), and UI_Init().
void Text_Paint (float x, float y, float scale, vec4_t color, const char * text, float adjust, int limit, int style)
Text_Paint.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] adjust
[in] limit
[in] style
Definition at line 663 of file ui_main.c.
Referenced by UI_DrawCampaignMapDescription(), UI_DrawCampaignName(), UI_DrawClanName(), UI_DrawGameType(), UI_DrawKeyBindStatus(), UI_DrawMapPreview(), UI_DrawMissionBriefingObjectives(), UI_DrawMissionBriefingTitle(), UI_DrawNetFilter(), UI_DrawOpponentName(), UI_DrawRedBlue(), UI_DrawSelectedPlayer(), UI_DrawServerRefreshDate(), UI_DrawTeamName(), and UI_Init().
void Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char * text, float adjust, int limit, int style, fontHelper_t * font)
Text_Paint_Ext.
Parameters
[in] x
[in] y
[in] scalex
[in] scaley
[in] color
[in] text
[in] adjust
[in] limit
[in] style
[in] font
Definition at line 576 of file ui_main.c.
Referenced by Text_Paint(), UI_Init(), and UI_LoadPanel_RenderLoadingText().
static void Text_Paint_Limit (float * maxX, float x, float y, float scale, vec4_t color, const char * text, float adjust, int limit) static
Text_Paint_Limit.
Parameters
[in] maxX
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] adjust
[in] limit
Definition at line 806 of file ui_main.c.
Referenced by UI_DrawServerMOTD().
void Text_PaintChar (float x, float y, float w, float h, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
Text_PaintChar.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] scale
[in] s
[in] t
[in] s2
[in] t2
[in] hShader
Definition at line 555 of file ui_main.c.
Referenced by Text_Paint_Limit(), and Text_PaintWithCursor_Ext().
void Text_PaintCharExt (float x, float y, float w, float h, float scalex, float scaley, float s, float t, float s2, float t2, qhandle_t hShader)
Text_PaintCharExt.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] scalex
[in] scaley
[in] s
[in] t
[in] s2
[in] t2
[in] hShader
Definition at line 534 of file ui_main.c.
Referenced by Text_Paint_Ext().
void Text_PaintWithCursor (float x, float y, float scale, vec4_t color, const char * text, int cursorPos, const char * cursor, int limit, int style)
Text_PaintWithCursor.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] cursorPos
[in] cursor
[in] limit
[in] style
Definition at line 788 of file ui_main.c.
Referenced by UI_Init().
void Text_PaintWithCursor_Ext (float x, float y, float scale, vec4_t color, const char * text, int cursorPos, const char * cursor, int limit, int style, fontHelper_t * font)
Text_PaintWithCursor_Ext.
Parameters
[in] x
[in] y
[in] scale
[in] color
[in] text
[in] cursorPos
[in] cursor
[in] limit
[in] style
Definition at line 682 of file ui_main.c.
Referenced by Text_PaintWithCursor(), and UI_Init().
void Text_SetActiveFont (int font)
Text_SetActiveFont.
Parameters
[in] font
Definition at line 252 of file ui_main.c.
Referenced by UI_Init().
int Text_Width (const char * text, float scale, int limit)
Text_Width.
Parameters
[in] text
[in] scale
[in] limit
Returns
Definition at line 308 of file ui_main.c.
Referenced by Text_Paint_Limit(), UI_DrawCampaignMapDescription(), UI_DrawMapPreview(), UI_DrawMissionBriefingObjectives(), UI_DrawServerMOTD(), UI_Init(), and UI_OwnerDrawWidth().
int Text_Width_Ext (const char * text, float scale, int limit, fontHelper_t * font)
Text_Width_Ext.
Parameters
[in] text
[in] scale
[in] limit
[in] font
Returns
Definition at line 265 of file ui_main.c.
Referenced by Text_Width(), and UI_Init().
static void UI_BinaryServerInsertion (int num) static
UI_BinaryServerInsertion.
Parameters
[in] num
Definition at line 6124 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
static void UI_BuildPlayerList (void) static
UI_BuildPlayerList.
Definition at line 2886 of file ui_main.c.
Referenced by UI_DrawSelectedPlayer(), UI_FeederCount(), UI_SelectedPlayer_HandleKey(), and UI_SetActiveMenu().
static void UI_BuildServerDisplayList (int force) static
UI_BuildServerDisplayList.
Parameters
[in] force
Todo:
: check for ping and compute humans/bots number for vanilla server?
Todo:
: some servers do not send gamename cvar in "getinfo" request -> parse them again with extended info(getstatus)
Definition at line 6167 of file ui_main.c.
Referenced by UI_DoServerRefresh(), UI_FeederSelectionClick(), UI_NetFilter_HandleKey(), and UI_RunMenuScript().
static void UI_BuildServerStatus (qboolean force) static
UI_BuildServerStatus.
Parameters
[in] force
Definition at line 6821 of file ui_main.c.
Referenced by UI_Refresh(), and UI_RunMenuScript().
void UI_Campaign_f (void)
UI_Campaign_f.
Definition at line 9058 of file ui_main.c.
Referenced by UI_ConsoleCommand().
static int UI_CampaignCount (qboolean singlePlayer) static
UI_CampaignCount.
Parameters
[in] singlePlayer
Returns
Definition at line 6057 of file ui_main.c.
Referenced by UI_FeederCount().
qboolean UI_CheckExecKey (int key)
UI_CheckExecKey.
Parameters
[in] key
Returns
Definition at line 4223 of file ui_main.c.
Referenced by vmMain().
static qboolean UI_ClanName_HandleKey (int flags, int * special, int key) static
UI_ClanName_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3582 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static qboolean UI_Crosshair_HandleKey (int flags, int * special, int key) static
UI_Crosshair_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3832 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static void UI_DoServerRefresh (void) static
UI_DoServerRefresh.
Definition at line 8953 of file ui_main.c.
Referenced by UI_Refresh().
static void UI_DrawCampaignCinematic (rectDef_t * rect, float scale, vec4_t color, qboolean net) static
UI_DrawCampaignCinematic.
Parameters
[in] rect
[in] scale
[in] color
[in] net
Definition at line 1889 of file ui_main.c.
Referenced by UI_OwnerDraw().
void UI_DrawCampaignDescription (rectDef_t * rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align, qboolean net)
UI_DrawCampaignDescription.
Parameters
[in] rect
[in] scale
[in] color
[in] text_x
[in] text_y - unused
[in] textStyle
[in] align
[in] net
Definition at line 1977 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawCampaignMapDescription (rectDef_t * rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align, qboolean net, int number) static
UI_DrawCampaignMapDescription.
Parameters
[in] rect
[in] scale
[in] color
[in] text_x
[in] text_y
[in] textStyle
[in] align
[in] net
[in] number
Definition at line 2205 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawCampaignMapPreview (rectDef_t * rect, float scale, vec4_t color, qboolean net, int map) static
UI_DrawCampaignMapPreview.
Parameters
[in] rect
[in] scale - unused
[in] color - unused
[in] net
[in] map
Definition at line 2323 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawCampaignName (rectDef_t * rect, float scale, vec4_t color, int textStyle, qboolean net) static
UI_DrawCampaignName.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
[in] net
Definition at line 1939 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawCampaignPreview (rectDef_t * rect, float scale, vec4_t color, qboolean net) static
UI_DrawCampaignPreview.
Parameters
[in] rect
scale - unused
color - unused
[in] net
Definition at line 1848 of file ui_main.c.
Referenced by UI_DrawCampaignCinematic().
static void UI_DrawCinematic (int handle, float x, float y, float w, float h) static
UI_DrawCinematic.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 8024 of file ui_main.c.
Referenced by UI_Init().
static void UI_DrawClanCinematic (rectDef_t * rect, float scale, vec4_t color) static
UI_DrawClanCinematic.
Parameters
[in] rect
scale - unused
[in] color
Definition at line 1467 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawClanLogo (rectDef_t * rect, float scale, vec4_t color) static
UI_DrawClanLogo.
Parameters
[in] rect
scale - unused
[in] color
Definition at line 1441 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawClanName (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawClanName.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 1394 of file ui_main.c.
Referenced by UI_OwnerDraw().
void UI_DrawConnectScreen (qboolean overlay)
This will also be overlaid on the cgame info screen during loading to prevent it from blinking away too rapidly on local or lan games.
Parameters
overlay
Definition at line 8600 of file ui_main.c.
Referenced by vmMain().
static void UI_DrawCrosshair (rectDef_t * rect, float scale, vec4_t color) static
UI_DrawCrosshair.
Parameters
[in] rect
[in] scale - unused
[in] color - unused
Definition at line 2864 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawEffects (rectDef_t * rect, float scale, vec4_t color) static
UI_DrawEffects.
Parameters
[in] rect
scale - unused
color - unused
Definition at line 1547 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawGameType (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawGameType.
Parameters
rect
scale
color
textStyle
Note
ui_gameType assumes gametype 0 is -1 ALL and will not show
Definition at line 1407 of file ui_main.c.
Referenced by UI_OwnerDraw().
void UI_DrawGametypeDescription (rectDef_t * rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align, qboolean net)
UI_DrawGametypeDescription.
Parameters
[in] rect
[in] scale
[in] color
[in] text_x
[in] text_y - unused
[in] textStyle
[in] align
[in] net
Definition at line 2093 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawKeyBindStatus (rectDef_t * rect, float scale, vec4_t color, int textStyle, float text_x, float text_y) static
UI_DrawKeyBindStatus.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
[in] text_x
[in] text_y
Definition at line 3104 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawMapCinematic (rectDef_t * rect, float scale, vec4_t color, qboolean net) static
UI_DrawMapCinematic.
Parameters
[in] rect
[in] scale
[in] color
[in] net
Definition at line 1776 of file ui_main.c.
Referenced by UI_OwnerDraw().
void UI_DrawMapPreview (rectDef_t * rect, float scale, vec4_t color, qboolean net)
UI_DrawMapPreview.
Parameters
[in] rect
[in] scale
color - unused
[in] net
Todo:
: check if in path
Definition at line 1560 of file ui_main.c.
Referenced by UI_DrawMapCinematic(), and UI_OwnerDraw().
static void UI_DrawMissionBriefingMap (rectDef_t * rect) static
UI_DrawMissionBriefingMap.
Parameters
[in] rect
Definition at line 2371 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawMissionBriefingObjectives (rectDef_t * rect, float scale, vec4_t color, float text_x, float text_y, int textStyle, int align) static
UI_DrawMissionBriefingObjectives.
Parameters
[in] rect
[in] scale
[in] color
[in] text_x
[in] text_y
[in] textStyle
[in] align
Definition at line 2425 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawMissionBriefingTitle (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawMissionBriefingTitle.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 2399 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawNetFilter (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawNetFilter.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 2526 of file ui_main.c.
Referenced by UI_OwnerDraw().
void UI_DrawNetMapPreview (rectDef_t * rect, float scale, vec4_t color, qboolean net)
UI_DrawNetMapPreview.
Parameters
[in] rect
scale - unused
color - unused
net - unused
Definition at line 1757 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawOpponentLogo (rectDef_t * rect, vec3_t color) static
UI_DrawOpponentLogo.
Parameters
[in] rect
[in] color
Definition at line 2651 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawOpponentLogoMetal (rectDef_t * rect, vec3_t color) static
UI_DrawOpponentLogoMetal.
Parameters
[in] rect
[in] color
Definition at line 2672 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawOpponentLogoName (rectDef_t * rect, vec3_t color) static
UI_DrawOpponentLogoName.
Parameters
[in] rect
[in] color
Definition at line 2693 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawOpponentName (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawOpponentName.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 2716 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawPlayerLogo (rectDef_t * rect, vec3_t color) static
UI_DrawPlayerLogo.
Parameters
[in] rect
[in] color
Definition at line 2588 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawPlayerLogoMetal (rectDef_t * rect, vec3_t color) static
UI_DrawPlayerLogoMetal.
Parameters
[in] rect
[in] color
Definition at line 2609 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawPlayerLogoName (rectDef_t * rect, vec3_t color) static
UI_DrawPlayerLogoName.
Parameters
[in] rect
[in] color
Definition at line 2630 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawPreviewCinematic (rectDef_t * rect, float scale, vec4_t color) static
UI_DrawPreviewCinematic.
Parameters
[in] rect
scale - unused
color - unused
Definition at line 1505 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawRedBlue (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawRedBlue.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 2853 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawSelectedPlayer (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawSelectedPlayer.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 2965 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawServerMOTD (rectDef_t * rect, float scale, vec4_t color) static
UI_DrawServerMOTD.
Parameters
[in] rect
[in] scale
[in] color
Definition at line 3016 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawServerRefreshDate (rectDef_t * rect, float scale, vec4_t color, int textStyle) static
UI_DrawServerRefreshDate.
Parameters
[in] rect
[in] scale
[in] color
[in] textStyle
Definition at line 2982 of file ui_main.c.
Referenced by UI_OwnerDraw().
static void UI_DrawTeamName (rectDef_t * rect, float scale, vec4_t color, qboolean blue, int textStyle) static
UI_DrawTeamName.
Parameters
[in] rect
[in] scale
[in] color
[in] blue
[in] textStyle
Definition at line 1531 of file ui_main.c.
Referenced by UI_OwnerDraw().
static qboolean UI_Effects_HandleKey (int flags, int * special, int key) static
UI_Effects_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3547 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static void UI_FeederAddItem (int feederID, const char * name, int index) static
UI_FeederAddItem.
Parameters
feederID - unused
name - unused
index - unused
Todo:
FIXME: empty function
Definition at line 7018 of file ui_main.c.
Referenced by UI_Init().
static int UI_FeederCount (int feederID) static
UI_FeederCount.
Parameters
[in] feederID
Returns
Definition at line 6878 of file ui_main.c.
Referenced by UI_Init().
static qhandle_t UI_FeederItemImage (int feederID, int index) static
UI_FeederItemImage.
Parameters
[in] feederID
[in] index
Returns
Definition at line 7481 of file ui_main.c.
Referenced by UI_Init().
const char* UI_FeederItemText (int feederID, int index, int column, qhandle_t * handles, int * numhandles)
UI_FeederItemText.
Parameters
[in] feederID
[in] index
[in] column
[out] handles
[out] numhandles
Returns
Todo:
: need some cleanup
Todo:
: some servers do not send gamename cvar in "getinfo" request -> parse them again with extended info(getstatus)
Definition at line 7055 of file ui_main.c.
Referenced by UI_Init().
static void UI_FeederSelection (int feederID, int index) static
UI_FeederSelection.
Parameters
[in] feederID
[in] index
Definition at line 7559 of file ui_main.c.
Referenced by UI_FeederSelectionClick(), UI_Init(), and UI_RunMenuScript().
static qboolean UI_FeederSelectionClick (itemDef_t * item) static
UI_FeederSelectionClick.
Parameters
[in] item
Returns
Definition at line 7729 of file ui_main.c.
Referenced by UI_Init().
static const char* UI_FileText (const char * fileName) static
UI_FileText.
Parameters
[in] fileName
Returns
Note
added (whoops, this got nuked in a check-in...)
Definition at line 7028 of file ui_main.c.
Referenced by UI_Init().
static qboolean UI_GameType_HandleKey (int flags, int * special, int key, qboolean resetMap) static
UI_GameType_HandleKey.
Parameters
flags - unused
special - unused
[in] key
[in] resetMap
Returns
Definition at line 3624 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
uiMenuCommand_t UI_GetActiveMenu (void)
_UI_GetActiveMenu
Returns
Definition at line 8310 of file ui_main.c.
Referenced by vmMain().
static int UI_GetServerStatusInfo (const char * serverAddress, serverStatusInfo_t * info) static
UI_GetServerStatusInfo.
Parameters
[in] serverAddress
[in,out] info
Returns
Definition at line 6661 of file ui_main.c.
Referenced by UI_BuildServerStatus().
static void UI_GetTeamColor (vec4_t * color) static
UI_GetTeamColor.
Parameters
color - unused
Todo:
FIXME: empty function
Definition at line 6008 of file ui_main.c.
Referenced by UI_Init().
static float UI_GetValue (int ownerDraw, int type) static
UI_GetValue.
Parameters
ownerDraw - unused
type - unused
Returns
Todo:
FIXME: this does nothing (same as CG_GetValue)
Definition at line 3975 of file ui_main.c.
Referenced by UI_Init().
void UI_GLCustom ()
UI_GLCustom.
Definition at line 4339 of file ui_main.c.
Referenced by UI_RunMenuScript().
void UI_Init (int legacyClient, int clientVersion)
_UI_Init
Parameters
[in] legacyClient
[in] clientVersion
Definition at line 8044 of file ui_main.c.
Referenced by vmMain().
static void UI_InsertServerIntoDisplayList (int num, int position) static
UI_InsertServerIntoDisplayList.
Parameters
[in] num
[in] position
Definition at line 6081 of file ui_main.c.
Referenced by UI_BinaryServerInsertion().
void UI_KeyEvent (int key, qboolean down)
_UI_KeyEvent
Parameters
[in] key
[in] down
Definition at line 8228 of file ui_main.c.
Referenced by vmMain().
void UI_ListCampaigns_f (void)
UI_ListCampaigns_f.
Definition at line 9105 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_ListFavourites_f (void)
Prints favourite servers list to console.
FIXME: WIP - values (clients, mapname) are not in sync with real server status because of master server delay? -> get the values directly from the servers ...
add command /confav x for easy connects
Definition at line 9147 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_Load (void)
UI_Load.
Definition at line 1361 of file ui_main.c.
Referenced by UI_ConsoleCommand().
static void UI_LoadDemos (void) static
UI_LoadDemos.
Definition at line 4183 of file ui_main.c.
Referenced by UI_RunMenuScript().
void UI_LoadMenus (const char * menuFile, qboolean reset)
UI_LoadMenus.
Parameters
[in] menuFile
[in] reset
Definition at line 1284 of file ui_main.c.
Referenced by UI_Init(), and UI_Load().
static void UI_LoadMods (void) static
UI_LoadMods.
Definition at line 4027 of file ui_main.c.
Referenced by UI_RunMenuScript().
static void UI_LoadMovies (void) static
UI_LoadMovies.
Definition at line 4147 of file ui_main.c.
Referenced by UI_RunMenuScript().
static void UI_LoadProfiles (void) static
UI_LoadProfiles.
Definition at line 4060 of file ui_main.c.
Referenced by UI_RunMenuScript().
static int UI_MapCountByGameType (qboolean singlePlayer) static
UI_MapCountByGameType.
Parameters
[in] singlePlayer
Returns
Definition at line 6017 of file ui_main.c.
Referenced by UI_Campaign_f(), UI_FeederCount(), UI_GameType_HandleKey(), UI_ListCampaigns_f(), and UI_RunMenuScript().
void UI_MouseEvent (int dx, int dy)
_UI_MouseEvent
Parameters
[in] dx
[in] dy
Definition at line 8275 of file ui_main.c.
Referenced by vmMain().
static qboolean UI_NetFilter_HandleKey (int flags, int * special, int key) static
UI_NetFilter_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3757 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static void UI_NextOpponent (void) static
UI_NextOpponent.
Definition at line 2538 of file ui_main.c.
Referenced by UI_OpponentName_HandleKey().
static qboolean UI_OpponentName_HandleKey (int flags, int * special, int key) static
UI_OpponentName_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3791 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static void UI_OwnerDraw (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, int special, float scale, vec4_t color, qhandle_t shader, int textStyle) static
UI_OwnerDraw.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] text_x
[in] text_y
[in] ownerDraw
[in] ownerDrawFlags - unused
[in] align
[in] special - unused
[in] scale
[in] color
[in] shader - unused
[in] textStyle
Note
FIXME: table drive
Definition at line 3170 of file ui_main.c.
Referenced by UI_Init().
static qboolean UI_OwnerDrawHandleKey (int ownerDraw, int flags, int * special, int key) static
UI_OwnerDrawHandleKey.
Parameters
[in] ownerDraw
[in] flags
[in] special
[in] key
Returns
Definition at line 3918 of file ui_main.c.
Referenced by UI_Init().
qboolean UI_OwnerDrawVisible (int flags)
UI_OwnerDrawVisible.
Parameters
[in] flags
Returns
Definition at line 3329 of file ui_main.c.
Referenced by UI_Init().
static int UI_OwnerDrawWidth (int ownerDraw, float scale) static
UI_OwnerDrawWidth.
Parameters
[in] ownerDraw
[in] scale
Returns
Definition at line 2727 of file ui_main.c.
Referenced by UI_Init().
static void UI_ParseGameInfo (const char * teamFile) static
UI_ParseGameInfo.
Parameters
[in] teamFile
Definition at line 7895 of file ui_main.c.
Referenced by UI_Init(), UI_Load(), and UI_RunMenuScript().
static void UI_ParseGLConfig (void) static
UI_ParseGLConfig.
Definition at line 3119 of file ui_main.c.
Referenced by UI_Init().
qboolean UI_ParseMenu (const char * menuFile)
UI_ParseMenu.
Parameters
[in] menuFile
Returns
Definition at line 1192 of file ui_main.c.
Referenced by Load_Menu().
static void UI_Pause (qboolean b) static
UI_Pause.
Parameters
[in] b
Definition at line 7940 of file ui_main.c.
Referenced by UI_Init().
static int UI_PlayCinematic (const char * name, float x, float y, float w, float h) static
UI_PlayCinematic.
Parameters
[in] name
[in] x
[in] y
[in] w
[in] h
Returns
Definition at line 7966 of file ui_main.c.
Referenced by UI_Init().
void UI_PrintTime (char * buf, int bufsize, int time)
UI_PrintTime.
Parameters
buf
bufsize
time Assumes time is in sec
Definition at line 8577 of file ui_main.c.
Referenced by UI_DownloadInfo().
static void UI_PriorOpponent (void) static
UI_PriorOpponent.
Definition at line 2562 of file ui_main.c.
Referenced by UI_OpponentName_HandleKey().
void UI_ReadableSize (char * buf, int bufsize, int value)
UI_ReadableSize.
Parameters
[in] buf
[in] bufsize
[in] value
Definition at line 8547 of file ui_main.c.
Referenced by UI_DownloadInfo().
static qboolean UI_RedBlue_HandleKey (int flags, int * special, int key) static
UI_RedBlue_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3815 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
void UI_Refresh (int realtime)
_UI_Refresh
Parameters
[in] realtime
Definition at line 888 of file ui_main.c.
Referenced by vmMain().
void UI_RegisterCvars (void)
UI_RegisterCvars.
Definition at line 8873 of file ui_main.c.
Referenced by UI_Init().
void UI_RemoveAllFavourites_f (void)
Removes all favourite servers from cache.
Definition at line 9182 of file ui_main.c.
Referenced by UI_ConsoleCommand(), and UI_RunMenuScript().
static void UI_RemoveServerFromDisplayList (int num) static
UI_RemoveServerFromDisplayList.
Parameters
[in] num
Definition at line 6102 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
void UI_Report (void)
UI_Report.
Definition at line 1182 of file ui_main.c.
Referenced by UI_ConsoleCommand().
static void UI_RunCinematicFrame (int handle) static
UI_RunCinematicFrame.
Parameters
[in] handle
Definition at line 8034 of file ui_main.c.
Referenced by UI_Init().
void UI_RunMenuScript (char ** args)
UI_RunMenuScript.
Parameters
[in] args
Todo:
: make this copying handle all files in the profiles directory
Todo:
: if dumped because of cl_allowdownload problem, toggle on first (we don't have appropriate support for this yet)
Definition at line 4368 of file ui_main.c.
Referenced by UI_Init().
static const char * UI_SelectedCampaign (int index, int * actual) static
UI_SelectedCampaign.
Parameters
[in] index
[out] actual
Returns
Definition at line 6985 of file ui_main.c.
Referenced by UI_FeederItemImage(), UI_FeederItemText(), and UI_FeederSelection().
static const char * UI_SelectedMap (qboolean singlePlayer, int index, int * actual) static
UI_SelectedMap.
Parameters
[in] singlePlayer
[in] index
[out] actual
Returns
Definition at line 6932 of file ui_main.c.
Referenced by UI_FeederItemImage(), UI_FeederItemText(), and UI_FeederSelection().
static qboolean UI_SelectedPlayer_HandleKey (int flags, int * special, int key) static
UI_SelectedPlayer_HandleKey.
Parameters
flags - unused
special - unused
[in] key
Returns
Definition at line 3866 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static int QDECL UI_ServersQsortCompare (const void * arg1, const void * arg2) static
UI_ServersQsortCompare.
Parameters
[in] arg1
[in] arg2
Returns
Definition at line 3986 of file ui_main.c.
void UI_ServersSort (int column, qboolean force)
UI_ServersSort.
Parameters
[in] column
[in] force
Definition at line 3996 of file ui_main.c.
Referenced by UI_RunMenuScript().
void UI_SetActiveMenu (uiMenuCommand_t menu)
_UI_SetActiveMenu
Parameters
[in] menu
Definition at line 8321 of file ui_main.c.
Referenced by UI_ShowPostGame(), and vmMain().
void UI_ShowPostGame ()
UI_ShowPostGame.
Definition at line 875 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_Shutdown (void)
_UI_Shutdown
Definition at line 959 of file ui_main.c.
Referenced by vmMain().
int QDECL UI_SortMods (const void * a, const void * b)
Sorting the mods list.
Parameters
[in] a
[in] b
Returns
Definition at line 4016 of file ui_main.c.
Referenced by UI_LoadMods().
static void UI_SortServerStatusInfo (serverStatusInfo_t * info) static
UI_SortServerStatusInfo.
Parameters
[in,out] info
Todo:
: replace the gametype number by game type
Definition at line 6619 of file ui_main.c.
Referenced by UI_GetServerStatusInfo().
static void UI_StartServerRefresh (qboolean full) static
UI_StartServerRefresh.
Parameters
[in] full
Definition at line 9008 of file ui_main.c.
Referenced by UI_RunMenuScript().
static void UI_StopCinematic (int handle) static
UI_StopCinematic.
Parameters
[in] handle
Definition at line 7975 of file ui_main.c.
Referenced by UI_Init().
static void UI_StopServerRefresh (void) static
UI_StopServerRefresh.
Definition at line 8929 of file ui_main.c.
Referenced by UI_DoServerRefresh(), and UI_RunMenuScript().
static int UI_TeamIndexFromName (const char * name) static
UI_TeamIndexFromName.
Parameters
[in] name
Returns
Definition at line 1417 of file ui_main.c.
Referenced by UI_ClanName_HandleKey(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawTeamName(), UI_NextOpponent(), UI_OwnerDrawWidth(), UI_PriorOpponent(), UI_StopCinematic(), and UI_TeamName_HandleKey().
static qboolean UI_TeamMember_HandleKey (int flags, int * special, int key, qboolean blue, int num) static
UI_TeamMember_HandleKey.
Parameters
flags - unused
special - unused
[in] key
[in] blue
[in] num
Returns
Definition at line 3716 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
static qboolean UI_TeamName_HandleKey (int flags, int * special, int key, qboolean blue) static
UI_TeamName_HandleKey.
Parameters
flags - unused
special - unused
[in] key
[in] blue
Returns
Definition at line 3676 of file ui_main.c.
Referenced by UI_OwnerDrawHandleKey().
void UI_Update (const char * name)
UI_Update.
Parameters
[in] name
Definition at line 4261 of file ui_main.c.
Referenced by UI_RunMenuScript().
void UI_UpdateCvars (void)
UI_UpdateCvars.
Definition at line 8898 of file ui_main.c.
Referenced by UI_Refresh().
static void UI_UpdatePendingPings (void) static
UI_UpdatePendingPings.
Definition at line 7004 of file ui_main.c.
Referenced by UI_StartServerRefresh().
Q_EXPORT intptr_t vmMain (intptr_t command, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11)
vmMain This is the only way control passes into the module. This must be the very first function compiled into the .qvm file
Parameters
[in] command
[in] arg0
[in] arg1
[in] arg2
[in] arg3 - unused
[in] arg4 - unused
[in] arg5 - unused
[in] arg6 - unused
[in] arg7 - unused
[in] arg8 - unused
[in] arg9 - unused
[in] arg10 - unused
[in] arg11 - unused
Returns
Definition at line 113 of file ui_main.c.
Variable Documentation
vmCvar_t cl_bypassMouseInput
Definition at line 8688 of file ui_main.c.
Referenced by UI_CheckExecKey(), and UI_KeyEvent().
vmCvar_t cl_defaultProfile
Definition at line 8673 of file ui_main.c.
Referenced by UI_FeederItemText(), and UI_RunMenuScript().
vmCvar_t cl_profile
Definition at line 8672 of file ui_main.c.
Referenced by UI_FeederItemText(), UI_LoadProfiles(), and UI_RunMenuScript().
cvarTable_t cvarTable[] static
Definition at line 8692 of file ui_main.c.
const unsigned int cvarTableSize = sizeof(cvarTable) / sizeof(cvarTable[0]) static
Definition at line 8868 of file ui_main.c.
Referenced by UI_RegisterCvars(), and UI_UpdateCvars().
char* defaultMenu = NULL
Definition at line 973 of file ui_main.c.
Referenced by GetMenuBuffer().
vmCvar_t g_gameType
Definition at line 8670 of file ui_main.c.
Referenced by UI_SetActiveMenu().
int gamecodetoui[] = { 4, 2, 3, 0, 5, 1, 6 } static
Definition at line 62 of file ui_main.c.
Referenced by UI_Init().
uiMenuCommand_t menutype = UIMENU_NONE static
Definition at line 8304 of file ui_main.c.
Referenced by UI_GetActiveMenu().
const char* MonthAbbrev[] static
Initial value:
=
{
    "Jan", "Feb", "Mar",
    "Apr", "May", "Jun",
    "Jul", "Aug", "Sep",
    "Oct", "Nov", "Dec"
}
Definition at line 39 of file ui_main.c.
Referenced by UI_StartServerRefresh().
const char* netnames[] static
Initial value:
=
{
    "???",
    "UDP",
    "IPX",
    NULL
}
Definition at line 54 of file ui_main.c.
const int numServerFilters = sizeof(serverFilters) / sizeof(serverFilter_t) static
Definition at line 52 of file ui_main.c.
Referenced by UI_DrawNetFilter(), UI_NetFilter_HandleKey(), and UI_OwnerDrawWidth().
const serverFilter_t serverFilters[] static
Initial value:
=
{
    { "All", "" }
}
Definition at line 47 of file ui_main.c.
serverStatusCvar_t serverStatusCvars[]
Initial value:
=
{
    { "sv_hostname", "Name"      },
    { "Address",     ""          },
    { "gamename",    "Game name" },
    { "g_gametype",  "Game type" },
    { "mapname",     "Map"       },
    { "version",     ""          },
    { "protocol",    ""          },
    { "timelimit",   ""          },
    { NULL,          NULL        }
}
Definition at line 6602 of file ui_main.c.
char translated_no[4] static
Definition at line 85 of file ui_main.c.
Referenced by UI_Init().
char translated_yes[4] static
Definition at line 85 of file ui_main.c.
Referenced by UI_Init().
vmCvar_t ui_autoactivate
Definition at line 8629 of file ui_main.c.
vmCvar_t ui_blackout
Definition at line 8681 of file ui_main.c.
Referenced by UI_Refresh().
vmCvar_t ui_brassTime
Definition at line 8623 of file ui_main.c.
vmCvar_t ui_browserMapFilter
Definition at line 8657 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserMapFilterCheckBox
Definition at line 8658 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserModFilter
Definition at line 8656 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserOssFilter
Definition at line 8660 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowAntilag
Definition at line 8651 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowEmptyOrFull
Definition at line 8646 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowFriendlyFire
Definition at line 8648 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowHumans
Definition at line 8654 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowMaxlives
Definition at line 8649 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowPasswordProtected
Definition at line 8647 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowTeamBalanced
Definition at line 8653 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowWeaponsRestricted
Definition at line 8652 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_campaignIndex
Definition at line 8677 of file ui_main.c.
Referenced by UI_FeederSelection().
vmCvar_t ui_cg_crosshairAlpha
Definition at line 8684 of file ui_main.c.
vmCvar_t ui_cg_crosshairAlphaAlt
Definition at line 8685 of file ui_main.c.
vmCvar_t ui_cg_crosshairColor
Definition at line 8682 of file ui_main.c.
vmCvar_t ui_cg_crosshairColorAlt
Definition at line 8683 of file ui_main.c.
vmCvar_t ui_cg_crosshairSize
Definition at line 8686 of file ui_main.c.
Referenced by UI_DrawCrosshair().
vmCvar_t ui_currentCampaign
Definition at line 8676 of file ui_main.c.
Referenced by UI_DrawCampaignCinematic(), UI_DrawCampaignMapDescription(), UI_DrawCampaignMapPreview(), UI_DrawCampaignName(), UI_DrawCampaignPreview(), UI_FeederSelection(), UI_OwnerDrawVisible(), and UI_RunMenuScript().
vmCvar_t ui_currentCampaignCompleted
Definition at line 8678 of file ui_main.c.
Referenced by UI_FeederSelection().
vmCvar_t ui_currentMap
Definition at line 8643 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), and UI_StopCinematic().
vmCvar_t ui_currentNetCampaign
Definition at line 8675 of file ui_main.c.
Referenced by UI_DrawCampaignCinematic(), UI_DrawCampaignMapDescription(), UI_DrawCampaignMapPreview(), UI_DrawCampaignName(), UI_DrawCampaignPreview(), and UI_FeederSelection().
vmCvar_t ui_currentNetMap
Definition at line 8642 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), and UI_RunMenuScript().
vmCvar_t ui_dedicated
Definition at line 8638 of file ui_main.c.
Referenced by UI_RunMenuScript().
vmCvar_t ui_drawCrosshair
Definition at line 8624 of file ui_main.c.
vmCvar_t ui_drawCrosshairInfo
Definition at line 8625 of file ui_main.c.
vmCvar_t ui_drawCrosshairNames
Definition at line 8626 of file ui_main.c.
vmCvar_t ui_drawCrosshairPickups
Definition at line 8627 of file ui_main.c.
vmCvar_t ui_friendlyFire
Definition at line 8664 of file ui_main.c.
vmCvar_t ui_gameType
Definition at line 8635 of file ui_main.c.
Referenced by UI_DrawGameType(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederItemImage(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_MapCountByGameType(), UI_OwnerDrawWidth(), and UI_SelectedMap().
vmCvar_t ui_glCustom
Definition at line 8668 of file ui_main.c.
vmCvar_t ui_joinGameType
Definition at line 8637 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_mapIndex
Definition at line 8644 of file ui_main.c.
Referenced by UI_FeederSelection(), and UI_RunMenuScript().
vmCvar_t ui_marks
Definition at line 8628 of file ui_main.c.
vmCvar_t ui_menuFiles
Definition at line 8634 of file ui_main.c.
vmCvar_t ui_netGameType
Definition at line 8636 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawGametypeDescription(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederItemImage(), UI_FeederSelection(), UI_MapCountByGameType(), UI_RunMenuScript(), and UI_SelectedMap().
vmCvar_t ui_netSource
Definition at line 8633 of file ui_main.c.
Referenced by UI_BinaryServerInsertion(), UI_BuildServerDisplayList(), UI_DrawServerRefreshDate(), UI_FeederItemText(), UI_FeederSelection(), UI_FeederSelectionClick(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_RunMenuScript(), UI_ServersQsortCompare(), and UI_UpdatePendingPings().
vmCvar_t ui_profile
Definition at line 8674 of file ui_main.c.
Referenced by UI_LoadProfiles(), and UI_RunMenuScript().
vmCvar_t ui_selectedPlayer
Definition at line 8631 of file ui_main.c.
Referenced by UI_OwnerDrawVisible().
vmCvar_t ui_selectedPlayerName
Definition at line 8632 of file ui_main.c.
vmCvar_t ui_serverBrowserSettings
Definition at line 8690 of file ui_main.c.
Referenced by UI_BuildServerDisplayList(), UI_FeederItemText(), and UI_SetActiveMenu().
vmCvar_t ui_serverFilterType
Definition at line 8641 of file ui_main.c.
Referenced by UI_DrawNetFilter(), UI_NetFilter_HandleKey(), and UI_OwnerDrawWidth().
vmCvar_t ui_serverStatusTimeOut
Definition at line 8662 of file ui_main.c.
vmCvar_t ui_userAlliedRespawnTime
Definition at line 8666 of file ui_main.c.
vmCvar_t ui_userAxisRespawnTime
Definition at line 8667 of file ui_main.c.
uiInfo_t uiInfo
Definition at line 37 of file ui_main.c.
Referenced by Script_ConditionalScript(), UI_AdjustFrom640(), UI_ConsoleCommand(), UI_DescriptionForCampaign(), UI_DownloadInfo(), UI_DrawLoadPanel(), UI_DrawTopBottom(), UI_FillRect(), UI_FindCampaignInCampaignList(), UI_FindMapInfoByMapname(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadCampaigns(), UI_LoadCampaignsFromFile(), and UI_NameForCampaign().
int uitogamecode[] = { 4, 6, 2, 3, 1, 5, 7 } static
Definition at line 63 of file ui_main.c.
qboolean updateModel = qtrue static
Definition at line 2517 of file ui_main.c.