ET: Legacy: src/ui/ui_local.h File Reference
ui_local.h File Reference
Local definitions for UI module.
#include "../qcommon/q_shared.h"
#include "../qcommon/q_unicode.h"
#include "../renderercommon/tr_types.h"
#include "ui_public.h"
#include "keycodes.h"
#include "../game/bg_public.h"
#include "ui_shared.h"
Data Structures
struct _tag_menuframework
struct menucommon_s
struct mfield_t
struct menufield_s
struct menuslider_s
struct menulist_s
struct menuaction_s
struct menuradiobutton_s
struct menubitmap_s
struct menutext_s
struct scrollInfo_s
struct characterInfo
struct aliasInfo
struct teamInfo
struct gameTypeInfo
struct profileInfo_t
struct serverFilter_s
struct serverStatus_s
struct serverStatusInfo_t
struct modInfo_t
struct uiInfo_t
Macros
#define __(x) trap_TranslateString(x)
#define UI_BROWSER_ALLOW_REDIRECT BIT(0)
#define UI_BROWSER_ALLOW_HUMANS_COUNT BIT(1)
#define UI_BROWSER_ALLOW_MAX_CLIENTS BIT(2)
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
#define SLIDER_RANGE 10
#define MAX_EDIT_LINE 256
#define DOUBLE_CLICK_DELAY 300
#define SET_EDITITEM(x) g_editingField = qtrue; g_editItem = x;
#define CLEAR_EDITITEM() g_editingField = qfalse; g_editItem = NULL;
#define IS_EDITMODE(x) ((x->window.flags & WINDOW_HASFOCUS) && g_editingField)
#define COMBO_SELECTORCHAR "V"
#define GLINFO_LINES 256
#define K_CLIPBOARD(x) (tolower(x) == 'v' && (DC->keyIsDown(K_LCTRL) || DC->keyIsDown(K_RCTRL)))
#define MAX_HEADS 64
#define MAX_ALIASES 64
#define MAX_TEAMS 64
#define MAX_MAPS 512
#define MAX_ADDRESSLENGTH 64
#define MAX_DISPLAY_SERVERS 4096
#define MAX_SERVERSTATUS_LINES 128
#define MAX_SERVERSTATUS_TEXT 2048
#define MAX_MODS 64
#define MAX_DEMOS 256
#define MAX_MOVIES 256
#define MAX_PLAYERMODELS 256
#define MAX_SPAWNPOINTS 128
#define MAX_SPAWNDESC 128
#define MAX_PROFILES 64
#define SCROLL_TIME_START 500
#define SCROLL_TIME_ADJUST 150
#define SCROLL_TIME_ADJUSTOFFSET 40
#define SCROLL_TIME_FLOOR 20
#define EDITFIELD_TEMP_CVAR "ui_textfield_temp"
Typedefs
typedef struct _tag_menuframework menuframework_s
typedef struct scrollInfo_s scrollInfo_t
typedef struct serverFilter_s serverFilter_t
typedef struct serverStatus_s serverStatus_t
Functions
void Menu_Cache (void)
void UI_Report (void)
UI_Report.
void UI_Load (void)
UI_Load.
void UI_LoadMenus (const char *menuFile, qboolean reset)
UI_LoadMenus.
void UI_SetActiveMenu (uiMenuCommand_t menu)
_UI_SetActiveMenu
uiMenuCommand_t UI_GetActiveMenu (void)
_UI_GetActiveMenu
int UI_AdjustTimeByGame (int time)
void UI_ShowPostGame ()
UI_ShowPostGame.
void UI_LoadArenas (void)
UI_LoadArenas.
void UI_LoadCampaigns (void)
UI_LoadCampaigns.
mapInfo * UI_FindMapInfoByMapname (const char *name)
UI_FindMapInfoByMapname.
void UI_ReadableSize (char *buf, int bufsize, int value)
UI_ReadableSize.
void UI_PrintTime (char *buf, int bufsize, int time)
UI_PrintTime.
void Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char *text, float adjust, int limit, int style, fontHelper_t *font)
Text_Paint_Ext.
void UI_Campaign_f (void)
UI_Campaign_f.
void UI_ListCampaigns_f (void)
UI_ListCampaigns_f.
void UI_ListFavourites_f (void)
Prints favourite servers list to console.
void UI_RemoveAllFavourites_f (void)
Removes all favourite servers from cache.
void QDECL Com_DPrintf (const char *fmt,...)
A Com_Printf that only shows up if the "developer" cvar is set.
void UI_RegisterCvars (void)
UI_RegisterCvars.
void UI_UpdateCvars (void)
UI_UpdateCvars.
void UI_DrawConnectScreen (qboolean overlay)
This will also be overlaid on the cgame info screen during loading to prevent it from blinking away too rapidly on local or lan games.
void UI_DrawLoadPanel (qboolean ownerdraw, qboolean uihack)
UI_DrawLoadPanel.
qboolean UI_ConsoleCommand (int realTime)
UI_ConsoleCommand.
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
UI_DrawHandlePic.
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_DrawTopBottom (float x, float y, float w, float h)
UI_DrawTopBottom.
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
Adjusted for resolution and screen aspect ratio.
char * UI_Argv (int arg)
UI_Argv.
char * UI_Cvar_VariableString (const char *varName)
UI_Cvar_VariableString.
int Binding_IDFromName (const char *name)
Binding_IDFromName.
void Binding_Set (int id, int b1, int b2)
Binding_Set.
void Binding_Unset (int id, int index)
Binding_Unset.
qboolean Binding_Check (int id, qboolean b1, int key)
Binding_Check.
int Binding_Get (int id, qboolean b1)
Binding_Get.
int Binding_Count (void)
Binding_Count.
char * Binding_FromName (const char *cvar)
Binding_FromName.
void trap_Print (const char *fmt)
trap_Print
void trap_Error (const char *fmt) __attribute__((noreturn))
trap_Error
int trap_Milliseconds (void)
trap_Milliseconds
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
trap_Cvar_Register
void trap_Cvar_Update (vmCvar_t *vmCvar)
trap_Cvar_Update
void trap_Cvar_Set (const char *varName, const char *value)
trap_Cvar_Set
float trap_Cvar_VariableValue (const char *varName)
trap_Cvar_VariableValue
void trap_Cvar_VariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_VariableStringBuffer
void trap_Cvar_LatchedVariableStringBuffer (const char *varName, char *buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
void trap_Cvar_SetValue (const char *varName, float value)
trap_Cvar_SetValue
void trap_Cvar_Reset (const char *name)
trap_Cvar_Reset
void trap_Cvar_Create (const char *varName, const char *var_value, int flags)
trap_Cvar_Create
void trap_Cvar_InfoStringBuffer (int bit, char *buffer, int bufsize)
trap_Cvar_InfoStringBuffer
int trap_Argc (void)
trap_Argc
void trap_Argv (int n, char *buffer, int bufferLength)
trap_Argv
void trap_Cmd_ExecuteText (int exec_when, const char *text)
trap_Cmd_ExecuteText
void trap_AddCommand (const char *cmdName)
trap_AddCommand
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
trap_FS_FOpenFile
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
trap_FS_Read
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
trap_FS_Write
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
trap_FS_GetFileList
int trap_FS_Delete (const char *filename)
trap_FS_Delete
qhandle_t trap_R_RegisterModel (const char *name)
trap_R_RegisterModel
qhandle_t trap_R_RegisterSkin (const char *name)
trap_R_RegisterSkin
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
trap_R_RegisterShaderNoMip
void trap_R_ClearScene (void)
trap_R_ClearScene
void trap_R_AddRefEntityToScene (const refEntity_t *re)
trap_R_AddRefEntityToScene
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
trap_R_AddPolyToScene
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
void trap_R_RenderScene (const refdef_t *fd)
trap_R_RenderScene
void trap_R_SetColor (const float *rgba)
trap_R_SetColor
void trap_R_Add2dPolys (polyVert_t *verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
void trap_UpdateScreen (void)
trap_UpdateScreen
int trap_CM_LerpTag (orientation_t *tag, const refEntity_t *refent, const char *tagName, int startIndex)
trap_CM_LerpTag
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
trap_S_RegisterSound
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
trap_Key_KeynumToStringBuf
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
trap_Key_GetBindingBuf
void trap_Key_KeysForBinding (const char *binding, int *key1, int *key2)
trap_Key_KeysForBinding
void trap_Key_SetBinding (int keynum, const char *binding)
trap_Key_SetBinding
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
void trap_Key_ClearStates (void)
trap_Key_ClearStates
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
void trap_GetClipboardData (char *buf, size_t bufsize)
trap_GetClipboardData
void trap_GetClientState (uiClientState_t *state)
trap_GetClientState
void trap_GetGlconfig (glconfig_t *glconfig)
trap_GetGlconfig
int trap_GetConfigString (int index, char *buff, size_t buffsize)
trap_GetConfigString
int trap_LAN_GetServerCount (int source)
trap_LAN_GetServerCount
int trap_LAN_GetLocalServerCount (void)
trap_LAN_GetLocalServerCount
void trap_LAN_GetLocalServerAddressString (int n, char *buf, int buflen)
trap_LAN_GetLocalServerAddressString
int trap_LAN_GetGlobalServerCount (void)
trap_LAN_GetGlobalServerCount
void trap_LAN_GetGlobalServerAddressString (int n, char *buf, int buflen)
trap_LAN_GetGlobalServerAddressString
int trap_LAN_GetPingQueueCount (void)
trap_LAN_GetPingQueueCount
void trap_LAN_ClearPing (int n)
trap_LAN_ClearPing
void trap_LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
trap_LAN_GetPing
void trap_LAN_GetPingInfo (int n, char *buf, int buflen)
trap_LAN_GetPingInfo
int trap_MemoryRemaining (void)
trap_MemoryRemaining
qboolean trap_LAN_UpdateVisiblePings (int source)
trap_LAN_UpdateVisiblePings
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
trap_LAN_MarkServerVisible
void trap_LAN_ResetPings (int n)
trap_LAN_ResetPings
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
trap_LAN_CompareServers
void trap_LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
trap_LAN_GetServerAddressString
void trap_LAN_GetServerInfo (int source, int n, char *buf, int buflen)
trap_LAN_GetServerInfo
int trap_LAN_AddServer (int source, const char *name, const char *addr)
trap_LAN_AddServer
void trap_LAN_RemoveServer (int source, const char *addr)
trap_LAN_RemoveServer
int trap_LAN_GetServerPing (int source, int n)
trap_LAN_GetServerPing
int trap_LAN_ServerIsVisible (int source, int n)
trap_LAN_ServerIsVisible
int trap_LAN_ServerStatus (const char *serverAddress, char *serverStatus, int maxLen)
trap_LAN_ServerStatus
void trap_LAN_LoadCachedServers (void)
trap_LAN_LoadCachedServers
qboolean trap_LAN_ServerIsInFavoriteList (int source, int n)
trap_LAN_ServerIsInFavoriteList
void trap_R_RegisterFont (const char *fontName, int pointSize, void *font)
trap_R_RegisterFont
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
void trap_S_StartBackgroundTrack (const char *intro, const char *loop, int fadeupTime)
trap_S_StartBackgroundTrack
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle.
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
int trap_RealTime (qtime_t *qtime)
trap_RealTime
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
trap_R_RemapShader
qboolean trap_GetLimboString (int index, char *buf)
trap_GetLimboString
void trap_CheckAutoUpdate (void)
trap_CheckAutoUpdate
void trap_GetAutoUpdate (void)
trap_GetAutoUpdate
void trap_openURL (const char *url)
trap_openURL
void trap_GetHunkData (int *hunkused, int *hunkexpected)
trap_GetHunkData
const char * trap_TranslateString (const char *fmt)
trap_TranslateString
const char * UI_DescriptionForCampaign (void)
UI_DescriptionForCampaign.
const char * UI_NameForCampaign (void)
UI_NameForCampaign.
Variables
vmCvar_t ui_brassTime
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_drawCrosshairPickups
vmCvar_t ui_marks
vmCvar_t ui_autoactivate
vmCvar_t ui_selectedPlayer
vmCvar_t ui_selectedPlayerName
vmCvar_t ui_netSource
vmCvar_t ui_menuFiles
vmCvar_t ui_gameType
vmCvar_t ui_netGameType
vmCvar_t ui_joinGameType
vmCvar_t ui_dedicated
vmCvar_t ui_serverFilterType
vmCvar_t ui_currentNetMap
vmCvar_t ui_currentMap
vmCvar_t ui_mapIndex
vmCvar_t ui_browserShowEmptyOrFull
vmCvar_t ui_browserShowPasswordProtected
vmCvar_t ui_browserShowFriendlyFire
vmCvar_t ui_browserShowMaxlives
vmCvar_t ui_browserShowAntilag
vmCvar_t ui_browserShowWeaponsRestricted
vmCvar_t ui_browserShowTeamBalanced
vmCvar_t ui_browserShowHumans
vmCvar_t ui_browserModFilter
vmCvar_t ui_browserMapFilter
vmCvar_t ui_browserMapFilterCheckBox
vmCvar_t ui_browserOssFilter
vmCvar_t ui_serverStatusTimeOut
vmCvar_t g_gameType
vmCvar_t cl_profile
vmCvar_t cl_defaultProfile
vmCvar_t ui_profile
vmCvar_t ui_currentNetCampaign
vmCvar_t ui_currentCampaign
vmCvar_t ui_campaignIndex
vmCvar_t ui_currentCampaignCompleted
vmCvar_t ui_blackout
vmCvar_t ui_cg_crosshairAlpha
vmCvar_t ui_cg_crosshairAlphaAlt
vmCvar_t ui_cg_crosshairColor
vmCvar_t ui_cg_crosshairColorAlt
vmCvar_t ui_cg_crosshairSize
vmCvar_t cl_bypassMouseInput
vmCvar_t ui_serverBrowserSettings
vec4_t menu_text_color
vec4_t menu_grayed_color
vec4_t menu_dark_color
vec4_t menu_highlight_color
vec4_t menu_red_color
vec4_t menu_black_color
vec4_t menu_dim_color
vec4_t color_black
vec4_t color_halfblack
vec4_t color_white
vec4_t color_yellow
vec4_t color_blue
vec4_t color_orange
vec4_t color_red
vec4_t color_dim
vec4_t name_color
vec4_t list_color
vec4_t listbar_color
vec4_t listbar_color2
vec4_t text_color_disabled
vec4_t text_color_normal
vec4_t text_color_highlight
menuDef_t Menus [MAX_MENUS]
defined menus
int menuCount
how many menus
menuDef_t * modalMenuStack [MAX_MODAL_MENUS]
int modalMenuCount
qboolean g_waitingForKey
qboolean g_editingField
itemDef_t * g_editItem
itemDef_t * g_bindItem
void(* captureFunc)(void *p)
void * captureData
itemDef_t * itemCapture
int lastListBoxClickTime
qboolean debugMode
scrollInfo_t scrollInfo
uiInfo_t uiInfo
displayContextDef_t * DC
Detailed Description
Local definitions for UI module.
Definition in file ui_local.h.
Macro Definition Documentation
#define __ (x) trap_TranslateString(x)
Definition at line 47 of file ui_local.h.
#define CLEAR_EDITITEM () g_editingField = qfalse; g_editItem = NULL;
Definition at line 322 of file ui_local.h.
Referenced by Item_ComboDeSelect(), and Item_HandleTextFieldDeSelect().
#define COMBO_SELECTORCHAR "V"
Definition at line 324 of file ui_local.h.
Referenced by Item_Combo_Paint().
#define DOUBLE_CLICK_DELAY 300
Definition at line 316 of file ui_local.h.
Referenced by Item_ListBox_HandleKey().
#define EDITFIELD_TEMP_CVAR "ui_textfield_temp"
Definition at line 774 of file ui_local.h.
Referenced by Item_CalcTextFieldCursor(), Item_HandleTextFieldDeSelect(), Item_TextField_HandleKey(), Item_TextField_Paint(), and Script_SetEditFocus().
#define GLINFO_LINES 256
Definition at line 347 of file ui_local.h.
Referenced by UI_ParseGLConfig().
#define IS_EDITMODE (x) ((x->window.flags & WINDOW_HASFOCUS) && g_editingField)
Definition at line 323 of file ui_local.h.
Referenced by Item_Combo_Paint(), Item_TextField_Paint(), and Menu_Paint().
#define K_CLIPBOARD (x) (tolower(x) == 'v' && (DC->keyIsDown(K_LCTRL) || DC->keyIsDown(K_RCTRL)))
Definition at line 363 of file ui_local.h.
Referenced by Item_HandleKey(), Item_TextField_HandleKey(), and Menu_HandleKey().
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
Definition at line 115 of file ui_local.h.
#define MAX_ADDRESSLENGTH 64
Definition at line 371 of file ui_local.h.
#define MAX_ALIASES 64
Definition at line 367 of file ui_local.h.
#define MAX_DEMOS 256
Definition at line 377 of file ui_local.h.
Referenced by UI_LoadDemos().
#define MAX_DISPLAY_SERVERS 4096
Definition at line 372 of file ui_local.h.
#define MAX_EDIT_LINE 256
Definition at line 118 of file ui_local.h.
#define MAX_HEADS 64
Definition at line 366 of file ui_local.h.
#define MAX_MAPS 512
Definition at line 370 of file ui_local.h.
Referenced by UI_LoadArenasFromFile().
#define MAX_MODS 64
Definition at line 376 of file ui_local.h.
Referenced by UI_LoadMods().
#define MAX_MOVIES 256
Definition at line 378 of file ui_local.h.
Referenced by UI_LoadMovies().
#define MAX_PLAYERMODELS 256
Definition at line 379 of file ui_local.h.
#define MAX_PROFILES 64
Definition at line 383 of file ui_local.h.
Referenced by UI_LoadProfiles().
#define MAX_SERVERSTATUS_LINES 128
Definition at line 373 of file ui_local.h.
Referenced by UI_GetServerStatusInfo().
#define MAX_SERVERSTATUS_TEXT 2048
Definition at line 374 of file ui_local.h.
#define MAX_SPAWNDESC 128
Definition at line 381 of file ui_local.h.
#define MAX_SPAWNPOINTS 128
Definition at line 380 of file ui_local.h.
#define MAX_TEAMS 64
Definition at line 368 of file ui_local.h.
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
Definition at line 114 of file ui_local.h.
#define SCROLL_TIME_ADJUST 150
Definition at line 386 of file ui_local.h.
Referenced by Item_Scroll_ListBox_AutoFunc(), Item_Scroll_ListBox_ThumbFunc(), and Item_StartCapture().
#define SCROLL_TIME_ADJUSTOFFSET 40
Definition at line 387 of file ui_local.h.
Referenced by Item_Scroll_ListBox_AutoFunc(), and Item_Scroll_ListBox_ThumbFunc().
#define SCROLL_TIME_FLOOR 20
Definition at line 388 of file ui_local.h.
Referenced by Item_Scroll_ListBox_AutoFunc(), and Item_Scroll_ListBox_ThumbFunc().
#define SCROLL_TIME_START 500
Definition at line 385 of file ui_local.h.
Referenced by Item_StartCapture().
#define SET_EDITITEM (x) g_editingField = qtrue; g_editItem = x;
Definition at line 321 of file ui_local.h.
Referenced by Item_ComboSelect(), and Item_HandleTextFieldSelect().
#define SLIDER_RANGE 10
Definition at line 117 of file ui_local.h.
#define UI_BROWSER_ALLOW_HUMANS_COUNT BIT(1)
Definition at line 110 of file ui_local.h.
Referenced by UI_BuildServerDisplayList(), and UI_FeederItemText().
#define UI_BROWSER_ALLOW_MAX_CLIENTS BIT(2)
Definition at line 111 of file ui_local.h.
Referenced by UI_BuildServerDisplayList().
#define UI_BROWSER_ALLOW_REDIRECT BIT(0)
Definition at line 109 of file ui_local.h.
Referenced by UI_SetActiveMenu().
Typedef Documentation
menuframework_s
scrollInfo_t
serverFilter_t
typedef struct serverStatus_s serverStatus_t
Function Documentation
qboolean Binding_Check (int id, qboolean b1, int key)
Binding_Check.
Parameters
[in] id
[in] b1
[in] key
Returns
Definition at line 955 of file ui_shared.c.
Referenced by Item_Bind_HandleKey().
int Binding_Count (void)
Binding_Count.
Returns
Definition at line 1005 of file ui_shared.c.
Referenced by Item_Bind_HandleKey().
char* Binding_FromName (const char * cvar)
Binding_FromName.
Parameters
[in] cvar
Returns
Definition at line 1018 of file ui_shared.c.
int Binding_Get (int id, qboolean b1)
Binding_Get.
Parameters
[in] id
[in] b1
Returns
Definition at line 984 of file ui_shared.c.
Referenced by Item_Bind_HandleKey().
int Binding_IDFromName (const char * name)
Binding_IDFromName.
Parameters
[in] name
Returns
Definition at line 875 of file ui_shared.c.
Referenced by Item_Bind_HandleKey().
void Binding_Set (int id, int b1, int b2)
Binding_Set.
Parameters
[in] id
[in] b1
[in] b2
Definition at line 896 of file ui_shared.c.
Referenced by Item_Bind_HandleKey().
void Binding_Unset (int id, int index)
Binding_Unset.
Parameters
[in] id
[in] index
Definition at line 926 of file ui_shared.c.
Referenced by Binding_Set().
void QDECL Com_DPrintf (const char * fmt, ...)
A Com_Printf that only shows up if the "developer" cvar is set.
Parameters
[in] fmt A Com_Printf that only shows up if the "developer" cvar is set.
[in] fmt
Definition at line 312 of file common.c.
Referenced by __attribute__(), BotClientCommand(), Cbuf_ExecuteText(), CIN_FreeCinematic(), CIN_PlayCinematic_f(), CL_CgameSystemCalls(), CL_ConnectionlessPacket(), CL_GetServerCommand(), CL_ParseSnapshot(), CL_ServerInfoPacket(), CL_SystemInfoChanged(), CL_UISystemCalls(), CM_LoadMap(), CM_SetBorderInward(), Cmd_RemoveCommandSafe(), Com_AddToGrowList(), Com_GetAutoUpdate(), Com_QueueEvent(), Com_UpdateInfoPacket(), Com_WWWBadChecksum(), Com_WWWDownload(), CON_Input(), Cvar_Get(), Cvar_Register(), DB_BeginTransaction(), DB_EndTransaction(), DL_DownloadLoop(), FS_ClearPureServerPacks(), FS_FOpenFileRead(), FS_PureServerSetLoadedPaks(), FS_ReadFile(), FS_SV_FOpenFileWrite(), GLimp_SetGamma(), IN_ProcessEvents(), IRC_InitialiseUser(), R_PrintLongString(), ROQ_UpdateCinematic(), S_Base_GetSoundLength(), S_Base_RawSamples(), S_Base_RegisterSound(), S_ChannelSetup(), S_FindName(), S_FreeOldestSound(), S_GetSoundtime(), S_LoadSound(), S_StartStreamingSoundEx(), SCR_DrawScreenField(), SV_AddEntitiesVisibleFromPoint(), SV_BotAllocateClient(), SV_CheckTimeouts(), SV_ClientCommand(), SV_ClientEnterWorld(), SV_DemoReadFrame(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_Frame(), SV_isValidClient(), SV_IsValidUserinfo(), SV_LinkEntity(), SV_Netchan_Transmit(), SV_Netchan_TransmitNextInQueue(), SV_NextDownload_f(), SV_SendClientGameState(), SV_SendClientMessages(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), SV_WriteSnapshotToClient(), Sys_Chmod(), Sys_OpenURL(), Sys_SetProcessProperties(), Sys_StartProcess(), UI_LoadMenus(), and UI_ParseMenu().
void Menu_Cache (void)
void Text_Paint_Ext (float x, float y, float scalex, float scaley, vec4_t color, const char * text, float adjust, int limit, int style, fontHelper_t * font)
Text_Paint_Ext.
Parameters
[in] x
[in] y
[in] scalex
[in] scaley
[in] color
[in] text
[in] adjust
[in] limit
[in] style
[in] font
Definition at line 576 of file ui_main.c.
Referenced by Text_Paint(), UI_Init(), and UI_LoadPanel_RenderLoadingText().
void trap_AddCommand (const char * cmdName)
trap_AddCommand
Parameters
[in] cmdName
Definition at line 258 of file cg_syscalls.c.
int trap_Argc (void)
trap_Argc
Returns
Definition at line 153 of file cg_syscalls.c.
void trap_Argv (int n, char * buffer, int bufferLength)
trap_Argv
Parameters
[in] n
[out] buffer
[in] bufferLength
[in] n
[in] buffer
[in] bufferLength
Definition at line 164 of file cg_syscalls.c.
void trap_CheckAutoUpdate (void)
trap_CheckAutoUpdate
Definition at line 1151 of file ui_syscalls.c.
Referenced by UI_Init().
void trap_CIN_DrawCinematic (int handle)
Draws the current frame.
Parameters
handle
[in] handle
Definition at line 1479 of file cg_syscalls.c.
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
This returns a handle.
arg0 is the name in the format "idlogo.roq", set arg1 to NULL, alteredstates to qfalse (do not alter gamestate)
Parameters
[in] arg0
[in] xpos
[in] ypos
[in] width
[in] height
[in] bits
Returns
This returns a handle.
Parameters
[in] arg0
[in] xpos
[in] ypos
[in] width
[in] height
[in] bits
Returns
Definition at line 1447 of file cg_syscalls.c.
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it. Will return FMV_EOF if the end of the cinematic has been reached.
Parameters
[in] handle
Returns
Definition at line 1470 of file cg_syscalls.c.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
Parameters
[in] handle
[in] x
[in] y
[in] w
[in] h
Definition at line 1492 of file cg_syscalls.c.
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
Parameters
[in] handle
Returns
Stops playing the cinematic and ends it. should always return FMV_EOF cinematics must be stopped in reverse order of when they are started.
Parameters
[in] handle
Returns
Definition at line 1459 of file cg_syscalls.c.
int trap_CM_LerpTag (orientation_t * tag, const refEntity_t * refent, const char * tagName, int startIndex)
trap_CM_LerpTag
Parameters
[in] tag
[in] refent
[in] tagName
[in] startIndex - unused
Returns
Definition at line 497 of file ui_syscalls.c.
void trap_Cmd_ExecuteText (int exec_when, const char * text)
trap_Cmd_ExecuteText
Parameters
[in] exec_when
[in] text
Definition at line 221 of file ui_syscalls.c.
Referenced by UI_Campaign_f(), UI_Init(), UI_RunMenuScript(), UI_StartServerRefresh(), and UI_Update().
void trap_Cvar_Create (const char * varName, const char * var_value, int flags)
trap_Cvar_Create
Parameters
[in] varName
[in] var_value
[in] flags
Definition at line 180 of file ui_syscalls.c.
void trap_Cvar_InfoStringBuffer (int bit, char * buffer, int bufsize)
trap_Cvar_InfoStringBuffer
Parameters
[in] bit
[in] buffer
[in] bufsize
Definition at line 191 of file ui_syscalls.c.
void trap_Cvar_LatchedVariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_LatchedVariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
[in] varName
[in] buffer
[in] bufsize
Definition at line 144 of file cg_syscalls.c.
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
trap_Cvar_Register
Parameters
[in] vmCvar
[in] varName
[in] defaultValue
[in] flags
Definition at line 103 of file cg_syscalls.c.
void trap_Cvar_Reset (const char * name)
trap_Cvar_Reset
Parameters
[in] name
Definition at line 169 of file ui_syscalls.c.
void trap_Cvar_Set (const char * varName, const char * value)
trap_Cvar_Set
Parameters
[in] varName
[in] value
Definition at line 122 of file cg_syscalls.c.
void trap_Cvar_SetValue (const char * varName, float value)
trap_Cvar_SetValue
Parameters
[in] varName
[in] value
Definition at line 160 of file ui_syscalls.c.
Referenced by UI_Effects_HandleKey(), UI_RunMenuScript(), and UI_Update().
void trap_Cvar_Update (vmCvar_t * vmCvar)
trap_Cvar_Update
Parameters
[in] vmCvar
Definition at line 112 of file cg_syscalls.c.
void trap_Cvar_VariableStringBuffer (const char * varName, char * buffer, int bufsize)
trap_Cvar_VariableStringBuffer
Parameters
[in] varName
[out] buffer
[in] bufsize
[in] varName
[in] buffer
[in] bufsize
Definition at line 133 of file cg_syscalls.c.
Referenced by trap_GetCurrentSnapshotNumber(), trap_GetSnapshot(), and trap_GetUsercmd().
float trap_Cvar_VariableValue (const char * varName)
trap_Cvar_VariableValue
Parameters
[in] varName
Returns
Definition at line 125 of file ui_syscalls.c.
void trap_Error (const char * fmt)
trap_Error
Parameters
[in] fmt
Definition at line 80 of file cg_syscalls.c.
int trap_FS_Delete (const char * filename)
trap_FS_Delete
Parameters
[in] filename
Returns
Definition at line 240 of file cg_syscalls.c.
void trap_FS_FCloseFile (fileHandle_t f)
trap_FS_FCloseFile
Parameters
[in] f
Definition at line 217 of file cg_syscalls.c.
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
trap_FS_FOpenFile
Parameters
[in] qpath
[in,out] f
[in] mode
Returns
Parameters
[in] qpath
[in] f
[in] mode
Returns
Definition at line 186 of file cg_syscalls.c.
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
trap_FS_GetFileList
Parameters
[in] path
[in] extension
[out] listbuf
[in] bufsize
Returns
Parameters
[in] path
[in] extension
[in] listbuf
[in] bufsize
Returns
Definition at line 230 of file cg_syscalls.c.
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
trap_FS_Read
Parameters
[out] buffer
[in] len
[in] f
[in] buffer
[in] len
[in] f
Definition at line 197 of file cg_syscalls.c.
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
trap_FS_Write
Parameters
[in] buffer
[in] len
[in] f
[in] buffer
[in] len
[in] f
Returns
Definition at line 208 of file cg_syscalls.c.
void trap_GetAutoUpdate (void)
trap_GetAutoUpdate
Definition at line 1159 of file ui_syscalls.c.
Referenced by UI_Init().
void trap_GetClientState (uiClientState_t * state)
trap_GetClientState
Parameters
[in] state
Definition at line 666 of file ui_syscalls.c.
Referenced by UI_BuildPlayerList(), UI_BuildServerStatus(), UI_ConsoleCommand(), UI_LoadMenus(), UI_LoadPanel_RenderHeaderText(), UI_LoadPanel_RenderLoadingText(), UI_Refresh(), and UI_RunMenuScript().
void trap_GetClipboardData (char * buf, size_t bufsize)
trap_GetClipboardData
Parameters
[in] buf
[in] bufsize
Definition at line 657 of file ui_syscalls.c.
Referenced by UI_Init().
int trap_GetConfigString (int index, char * buff, size_t buffsize)
trap_GetConfigString
Parameters
[in] index
[in] buff
[in] buffsize
Returns
Definition at line 687 of file ui_syscalls.c.
Referenced by UI_BuildPlayerList(), UI_DescriptionForCampaign(), UI_Init(), UI_NameForCampaign(), and UI_RunMenuScript().
void trap_GetGlconfig (glconfig_t * glconfig)
trap_GetGlconfig
Parameters
[out] glconfig
[in] glconfig
Definition at line 1007 of file cg_syscalls.c.
void trap_GetHunkData (int * hunkused, int * hunkexpected)
trap_GetHunkData
Parameters
[out] hunkused
[out] hunkexpected
[in] hunkused
[in] hunkexpected
Definition at line 1862 of file cg_syscalls.c.
qboolean trap_GetLimboString (int index, char * buf)
trap_GetLimboString
Parameters
[in] index
[in] buf
Returns
Definition at line 1124 of file ui_syscalls.c.
void trap_Key_ClearStates (void)
trap_Key_ClearStates
Definition at line 629 of file ui_syscalls.c.
Referenced by UI_KeyEvent(), UI_Pause(), UI_RunMenuScript(), and UI_SetActiveMenu().
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
trap_Key_GetBindingBuf
Parameters
[in] keynum
[in] buf
[in] buflen
Definition at line 1533 of file cg_syscalls.c.
int trap_Key_GetCatcher (void)
trap_Key_GetCatcher
Returns
Definition at line 1289 of file cg_syscalls.c.
qboolean trap_Key_GetOverstrikeMode (void)
trap_Key_GetOverstrikeMode
Returns
Definition at line 1298 of file cg_syscalls.c.
qboolean trap_Key_IsDown (int keynum)
trap_Key_IsDown
Parameters
[in] keynum
Returns
Definition at line 1280 of file cg_syscalls.c.
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
trap_Key_KeynumToStringBuf
Parameters
[in] keynum
[out] buf
[in] buflen
[in] keynum
[in] buf
[in] buflen
Definition at line 1554 of file cg_syscalls.c.
void trap_Key_KeysForBinding (const char * binding, int * key1, int * key2)
trap_Key_KeysForBinding
Parameters
[in] binding
[in,out] key1
[in,out] key2
Note
binding MUST be lower case
Parameters
[in] binding
[in] key1
[in] key2
Note
binding MUST be lower case
Definition at line 1320 of file cg_syscalls.c.
void trap_Key_SetBinding (int keynum, const char * binding)
trap_Key_SetBinding
Parameters
[in] keynum
[in] binding
Definition at line 1543 of file cg_syscalls.c.
void trap_Key_SetCatcher (int catcher)
trap_Key_SetCatcher
Parameters
[in] catcher
Definition at line 1329 of file cg_syscalls.c.
void trap_Key_SetOverstrikeMode (qboolean state)
trap_Key_SetOverstrikeMode
Parameters
[in] state
Definition at line 1307 of file cg_syscalls.c.
int trap_LAN_AddServer (int source, const char * name, const char * addr)
trap_LAN_AddServer
Parameters
[in] source
[in] name
[in] addr
Returns
Definition at line 838 of file ui_syscalls.c.
Referenced by UI_FeederSelectionClick(), and UI_RunMenuScript().
void trap_LAN_ClearPing (int n)
trap_LAN_ClearPing
Parameters
[in] n
Definition at line 745 of file ui_syscalls.c.
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
trap_LAN_CompareServers
Parameters
[in] source
[in] sortKey
[in] sortDir
[in] s1
[in] s2
Returns
Definition at line 802 of file ui_syscalls.c.
Referenced by UI_BinaryServerInsertion(), and UI_ServersQsortCompare().
void trap_LAN_GetGlobalServerAddressString (int n, char * buf, int buflen)
trap_LAN_GetGlobalServerAddressString
Parameters
[in] n
[in] buf
[in] buflen
Definition at line 727 of file ui_syscalls.c.
int trap_LAN_GetGlobalServerCount (void)
trap_LAN_GetGlobalServerCount
Returns
Definition at line 716 of file ui_syscalls.c.
void trap_LAN_GetLocalServerAddressString (int n, char * buf, int buflen)
trap_LAN_GetLocalServerAddressString
Parameters
[in] n
[in] buf
[in] buflen
Definition at line 707 of file ui_syscalls.c.
int trap_LAN_GetLocalServerCount (void)
trap_LAN_GetLocalServerCount
Returns
Definition at line 696 of file ui_syscalls.c.
void trap_LAN_GetPing (int n, char * buf, int buflen, int * pingtime)
trap_LAN_GetPing
Parameters
[in] n
[in] buf
[in] buflen
[in] pingtime
Definition at line 757 of file ui_syscalls.c.
void trap_LAN_GetPingInfo (int n, char * buf, int buflen)
trap_LAN_GetPingInfo
Parameters
[in] n
[in] buf
[in] buflen
Definition at line 768 of file ui_syscalls.c.
int trap_LAN_GetPingQueueCount (void)
trap_LAN_GetPingQueueCount
Returns
Definition at line 736 of file ui_syscalls.c.
void trap_LAN_GetServerAddressString (int source, int n, char * buf, int buflen)
trap_LAN_GetServerAddressString
Parameters
[in] source
[in] n
[in] buf
[in] buflen
Definition at line 814 of file ui_syscalls.c.
Referenced by UI_RunMenuScript().
int trap_LAN_GetServerCount (int source)
trap_LAN_GetServerCount
Parameters
[in] source
Returns
Definition at line 788 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList(), UI_DoServerRefresh(), UI_DrawServerRefreshDate(), UI_ListFavourites_f(), and UI_StopServerRefresh().
void trap_LAN_GetServerInfo (int source, int n, char * buf, int buflen)
trap_LAN_GetServerInfo
Parameters
[in] source
[in] n
[in] buf
[in] buflen
Definition at line 826 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList(), UI_FeederItemText(), UI_FeederSelection(), UI_FeederSelectionClick(), UI_ListFavourites_f(), and UI_RunMenuScript().
int trap_LAN_GetServerPing (int source, int n)
trap_LAN_GetServerPing
Parameters
[in] source
[in] n
Returns
Definition at line 859 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList().
void trap_LAN_LoadCachedServers (void)
trap_LAN_LoadCachedServers
Definition at line 912 of file ui_syscalls.c.
Referenced by UI_Init(), and UI_RunMenuScript().
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
trap_LAN_MarkServerVisible
Parameters
[in] source
[in] n
[in] visible
Definition at line 923 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList(), and UI_StartServerRefresh().
void trap_LAN_RemoveServer (int source, const char * addr)
trap_LAN_RemoveServer
Parameters
[in] source
[in] addr
Definition at line 848 of file ui_syscalls.c.
Referenced by UI_FeederSelectionClick(), UI_RemoveAllFavourites_f(), and UI_RunMenuScript().
void trap_LAN_ResetPings (int n)
trap_LAN_ResetPings
Parameters
[in] n
Definition at line 932 of file ui_syscalls.c.
Referenced by UI_StartServerRefresh(), and UI_UpdatePendingPings().
qboolean trap_LAN_ServerIsInFavoriteList (int source, int n)
trap_LAN_ServerIsInFavoriteList
Parameters
[in] source
[in] n
Returns
Definition at line 893 of file ui_syscalls.c.
Referenced by UI_FeederItemText(), UI_FeederSelectionClick(), and UI_RunMenuScript().
int trap_LAN_ServerIsVisible (int source, int n)
trap_LAN_ServerIsVisible
Parameters
[in] source
[in] n
Returns
Definition at line 870 of file ui_syscalls.c.
Referenced by UI_BuildServerDisplayList().
int trap_LAN_ServerStatus (const char * serverAddress, char * serverStatus, int maxLen)
trap_LAN_ServerStatus
Parameters
[in] serverAddress
[in] serverStatus
[in] maxLen
Returns
Definition at line 882 of file ui_syscalls.c.
Referenced by UI_BuildServerStatus(), and UI_GetServerStatusInfo().
qboolean trap_LAN_UpdateVisiblePings (int source)
trap_LAN_UpdateVisiblePings
Parameters
[in] source
Returns
Definition at line 778 of file ui_syscalls.c.
Referenced by UI_DoServerRefresh().
int trap_MemoryRemaining (void)
trap_MemoryRemaining
Returns
Definition at line 1220 of file cg_syscalls.c.
int trap_Milliseconds (void)
trap_Milliseconds
Returns
Definition at line 91 of file cg_syscalls.c.
void trap_openURL (const char * url)
trap_openURL
Parameters
[in] url
Definition at line 1168 of file ui_syscalls.c.
Referenced by UI_RunMenuScript().
void trap_Print (const char * fmt)
trap_Print
Parameters
[in] fmt
Definition at line 71 of file cg_syscalls.c.
void trap_R_Add2dPolys (polyVert_t * verts, int numverts, qhandle_t hShader)
trap_R_Add2dPolys
Parameters
[in] verts
[in] numverts
[in] hShader
Definition at line 963 of file cg_syscalls.c.
void trap_R_AddCoronaToScene (const vec3_t org, float r, float g, float b, float scale, int id, qboolean visible)
trap_R_AddCoronaToScene
Parameters
[in] org
[in] r
[in] g
[in] b
[in] scale
[in] id
[in] visible
Definition at line 831 of file cg_syscalls.c.
void trap_R_AddLightToScene (const vec3_t org, float radius, float intensity, float r, float g, float b, qhandle_t hShader, int flags)
New dlight system.
Parameters
[in] org
[in] radius
[in] intensity
[in] r
[in] g
[in] b
[in] hShader
[in] flags
Definition at line 815 of file cg_syscalls.c.
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
trap_R_AddPolyToScene
Parameters
[in] hShader
[in] numVerts
[in] verts
Definition at line 778 of file cg_syscalls.c.
void trap_R_AddRefEntityToScene (const refEntity_t * re)
trap_R_AddRefEntityToScene
Parameters
re
[in] re
Definition at line 767 of file cg_syscalls.c.
void trap_R_ClearScene (void)
trap_R_ClearScene
Definition at line 758 of file cg_syscalls.c.
void trap_R_DrawRotatedPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader, float angle)
trap_R_DrawRotatedPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
[in] angle
Definition at line 930 of file cg_syscalls.c.
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
trap_R_DrawStretchPic
Parameters
[in] x
[in] y
[in] w
[in] h
[in] s1
[in] t1
[in] s2
[in] t2
[in] hShader
Definition at line 911 of file cg_syscalls.c.
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
trap_R_ModelBounds
Parameters
[in] model
[in] mins
[in] maxs
Definition at line 974 of file cg_syscalls.c.
void trap_R_RegisterFont (const char * fontName, int pointSize, void * font)
trap_R_RegisterFont
Parameters
[in] fontName
[in] pointSize
[in] font
Definition at line 1819 of file cg_syscalls.c.
Referenced by trap_TranslateString().
qhandle_t trap_R_RegisterModel (const char * name)
trap_R_RegisterModel
Parameters
[in] name
Returns
Definition at line 1774 of file cg_syscalls.c.
Referenced by trap_TranslateString().
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
trap_R_RegisterShaderNoMip
Parameters
[in] name
Returns
Definition at line 1807 of file cg_syscalls.c.
Referenced by trap_TranslateString().
qhandle_t trap_R_RegisterSkin (const char * name)
trap_R_RegisterSkin
Parameters
[in] name
Returns
Definition at line 1785 of file cg_syscalls.c.
Referenced by trap_TranslateString().
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
trap_R_RemapShader
Parameters
[in] oldShader
[in] newShader
[in] timeOffset
Definition at line 998 of file cg_syscalls.c.
void trap_R_RenderScene (const refdef_t * fd)
trap_R_RenderScene
Parameters
[in] fd
Definition at line 869 of file cg_syscalls.c.
void trap_R_SetColor (const float * rgba)
trap_R_SetColor
Parameters
[in] rgba
Definition at line 894 of file cg_syscalls.c.
int trap_RealTime (qtime_t * qtime)
trap_RealTime
Parameters
[out] qtime
Returns
Parameters
[in] qtime
Returns
Definition at line 1420 of file cg_syscalls.c.
void trap_S_FadeAllSound (float targetvol, int time, qboolean stopsounds)
trap_S_FadeAllSound
Parameters
[in] targetvol
[in] time
[in] stopsounds
Definition at line 712 of file cg_syscalls.c.
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
trap_S_RegisterSound
Todo:
: unique debug macros
Parameters
[in] sample
[in] compressed
Returns
Parameters
[in] sample
[in] compressed
Returns
Definition at line 1763 of file cg_syscalls.c.
Referenced by trap_TranslateString().
void trap_S_StartBackgroundTrack (const char * intro, const char * loop, int fadeupTime)
trap_S_StartBackgroundTrack
Parameters
[in] intro
[in] loop
[in] fadeupTime
Definition at line 687 of file cg_syscalls.c.
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
trap_S_StartLocalSound
Parameters
[in] sfx
[in] channelNum
Note
127 Default volume always for the moment
Parameters
[in] sfx
[in] channelNum
Definition at line 570 of file cg_syscalls.c.
void trap_S_StopBackgroundTrack (void)
trap_S_StopBackgroundTrack
Definition at line 1410 of file cg_syscalls.c.
const char* trap_TranslateString (const char * fmt)
trap_TranslateString
Parameters
[in] fmt
Returns
Definition at line 1134 of file ui_syscalls.c.
void trap_UpdateScreen (void)
trap_UpdateScreen
Definition at line 289 of file cg_syscalls.c.
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Adjusted for resolution and screen aspect ratio.
Parameters
[in] x
[in] y
[in] w
[in] h
Definition at line 211 of file ui_atoms.c.
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), Text_PaintChar(), Text_PaintCharExt(), UI_DrawHandlePic(), UI_DrawMapPreview(), UI_DrawTopBottom(), and UI_FillRect().
int UI_AdjustTimeByGame (int time)
char* UI_Argv (int arg)
UI_Argv.
Parameters
[in] arg
Returns
Definition at line 99 of file ui_atoms.c.
Referenced by UI_ConsoleCommand().
void UI_Campaign_f (void)
UI_Campaign_f.
Definition at line 9058 of file ui_main.c.
Referenced by UI_ConsoleCommand().
qboolean UI_ConsoleCommand (int realTime)
UI_ConsoleCommand.
Parameters
[in] realTime
Returns
Definition at line 138 of file ui_atoms.c.
Referenced by vmMain().
char* UI_Cvar_VariableString (const char * varName)
UI_Cvar_VariableString.
Parameters
[in] varName
Returns
Definition at line 113 of file ui_atoms.c.
Referenced by UI_ClanName_HandleKey(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawClanName(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawOpponentName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawSelectedPlayer(), UI_DrawServerRefreshDate(), UI_DrawTeamName(), UI_Load(), UI_NextOpponent(), UI_OwnerDrawWidth(), UI_PriorOpponent(), UI_RunMenuScript(), UI_SetActiveMenu(), UI_StartServerRefresh(), UI_StopCinematic(), UI_TeamName_HandleKey(), and UI_Update().
const char* UI_DescriptionForCampaign (void)
UI_DescriptionForCampaign.
Returns
Definition at line 527 of file ui_gameinfo.c.
Referenced by UI_Init().
void UI_DrawConnectScreen (qboolean overlay)
This will also be overlaid on the cgame info screen during loading to prevent it from blinking away too rapidly on local or lan games.
Parameters
overlay
Definition at line 8600 of file ui_main.c.
Referenced by vmMain().
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
UI_DrawHandlePic.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] hShader
Definition at line 254 of file ui_atoms.c.
Referenced by UI_DrawCampaignMapPreview(), UI_DrawCampaignPreview(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawCrosshair(), UI_DrawEffects(), UI_DrawMapPreview(), UI_DrawMissionBriefingMap(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_Init(), and UI_Refresh().
void UI_DrawLoadPanel (qboolean ownerdraw, qboolean uihack)
UI_DrawLoadPanel.
Parameters
[in] ownerdraw
[in] uihack
Definition at line 151 of file ui_loadpanel.c.
Referenced by UI_DrawConnectScreen(), UI_OwnerDraw(), and UI_Refresh().
void UI_DrawTopBottom (float x, float y, float w, float h)
UI_DrawTopBottom.
Parameters
[in] x
[in] y
[in] w
[in] h
Note
Unused
Definition at line 328 of file ui_atoms.c.
void UI_FillRect (float x, float y, float width, float height, const float * color)
Coordinates are 640*480 virtual values
Parameters
[in] x
[in] y
[in] width
[in] height
[in] color
Definition at line 309 of file ui_atoms.c.
Referenced by UI_DrawMapPreview(), UI_Init(), and UI_Refresh().
mapInfo* UI_FindMapInfoByMapname (const char * name)
UI_FindMapInfoByMapname.
Parameters
[in] name
Returns
Definition at line 295 of file ui_gameinfo.c.
Referenced by UI_DrawMissionBriefingObjectives(), and UI_DrawMissionBriefingTitle().
uiMenuCommand_t UI_GetActiveMenu (void)
_UI_GetActiveMenu
Returns
Definition at line 8310 of file ui_main.c.
Referenced by vmMain().
void UI_ListCampaigns_f (void)
UI_ListCampaigns_f.
Definition at line 9105 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_ListFavourites_f (void)
Prints favourite servers list to console.
FIXME: WIP - values (clients, mapname) are not in sync with real server status because of master server delay? -> get the values directly from the servers ...
add command /confav x for easy connects
Definition at line 9147 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_Load (void)
UI_Load.
Definition at line 1361 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_LoadArenas (void)
UI_LoadArenas.
Definition at line 253 of file ui_gameinfo.c.
Referenced by UI_Campaign_f(), UI_FindMapInfoByMapname(), UI_ListCampaigns_f(), UI_Load(), and UI_RunMenuScript().
void UI_LoadCampaigns (void)
UI_LoadCampaigns.
Definition at line 629 of file ui_gameinfo.c.
Referenced by UI_Campaign_f(), UI_ListCampaigns_f(), UI_Load(), and UI_RunMenuScript().
void UI_LoadMenus (const char * menuFile, qboolean reset)
UI_LoadMenus.
Parameters
[in] menuFile
[in] reset
Definition at line 1284 of file ui_main.c.
Referenced by UI_Init(), and UI_Load().
const char* UI_NameForCampaign (void)
UI_NameForCampaign.
Returns
Definition at line 555 of file ui_gameinfo.c.
Referenced by UI_Init().
void UI_PrintTime (char * buf, int bufsize, int time)
UI_PrintTime.
Parameters
buf
bufsize
time Assumes time is in sec
Definition at line 8577 of file ui_main.c.
Referenced by UI_DownloadInfo().
void UI_ReadableSize (char * buf, int bufsize, int value)
UI_ReadableSize.
Parameters
[in] buf
[in] bufsize
[in] value
Definition at line 8547 of file ui_main.c.
Referenced by UI_DownloadInfo().
void UI_RegisterCvars (void)
UI_RegisterCvars.
Definition at line 8873 of file ui_main.c.
Referenced by UI_Init().
void UI_RemoveAllFavourites_f (void)
Removes all favourite servers from cache.
Definition at line 9182 of file ui_main.c.
Referenced by UI_ConsoleCommand(), and UI_RunMenuScript().
void UI_Report (void)
UI_Report.
Definition at line 1182 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_SetActiveMenu (uiMenuCommand_t menu)
_UI_SetActiveMenu
Parameters
[in] menu
Definition at line 8321 of file ui_main.c.
Referenced by UI_ShowPostGame(), and vmMain().
void UI_ShowPostGame ()
UI_ShowPostGame.
Definition at line 875 of file ui_main.c.
Referenced by UI_ConsoleCommand().
void UI_UpdateCvars (void)
UI_UpdateCvars.
Definition at line 8898 of file ui_main.c.
Referenced by UI_Refresh().
Variable Documentation
void* captureData
Definition at line 42 of file ui_shared.c.
Referenced by Item_HandleKey(), Item_StartCapture(), Menu_HandleMouseMove(), and Menu_PaintAll().
void(* captureFunc) (void *p)
Definition at line 41 of file ui_shared.c.
Referenced by Item_HandleKey(), Item_StartCapture(), Menu_HandleMouseMove(), Menu_PaintAll(), and Menus_CaptureFuncActive().
vmCvar_t cl_bypassMouseInput
Definition at line 689 of file cl_input.c.
Referenced by CL_Init(), CL_KeyEvent(), UI_CheckExecKey(), and UI_KeyEvent().
vmCvar_t cl_defaultProfile
Definition at line 101 of file cl_main.c.
Referenced by UI_FeederItemText(), and UI_RunMenuScript().
vmCvar_t cl_profile
Definition at line 100 of file cl_main.c.
Referenced by CL_FirstSnapshot(), LAN_AddServer(), LAN_LoadCachedServers(), LAN_RemoveServer(), LAN_SaveServersToFile(), UI_FeederItemText(), UI_LoadProfiles(), and UI_RunMenuScript().
vec4_t color_black
vec4_t color_blue
vec4_t color_dim
vec4_t color_halfblack
vec4_t color_orange
vec4_t color_red
vec4_t color_white
vec4_t color_yellow
displayContextDef_t* DC
Definition at line 45 of file ui_shared.c.
Referenced by Display_GetContext().
qboolean debugMode
Definition at line 61 of file ui_shared.c.
Referenced by Item_Paint(), Menu_HandleKey(), Menu_Paint(), Menu_PaintAll(), and Window_Paint().
itemDef_t* g_bindItem
Definition at line 50 of file ui_shared.c.
qboolean g_editingField
Definition at line 48 of file ui_shared.c.
Referenced by Item_TextField_Paint(), Menu_HandleKey(), Menu_HandleMouseMove(), Menus_CloseByName(), Script_SetEditFocus(), and UI_CheckExecKey().
itemDef_t* g_editItem
Definition at line 51 of file ui_shared.c.
Referenced by Item_HandleSaveValue(), Menu_HandleKey(), Menus_CloseByName(), and Script_SetEditFocus().
vmCvar_t g_gameType
Definition at line 8670 of file ui_main.c.
Referenced by UI_SetActiveMenu().
qboolean g_waitingForKey
Definition at line 47 of file ui_shared.c.
Referenced by Display_KeyBindPending().
itemDef_t* itemCapture
Definition at line 43 of file ui_shared.c.
Referenced by Item_HandleKey(), Item_ListBox_ThumbDrawPosition(), Item_StartCapture(), and Menu_HandleMouseMove().
int lastListBoxClickTime
Definition at line 62 of file ui_shared.c.
Referenced by Item_ListBox_HandleKey(), and Item_Scroll_ListBox_ThumbFunc().
vec4_t list_color
vec4_t listbar_color
vec4_t listbar_color2
vec4_t menu_black_color
vec4_t menu_dark_color
vec4_t menu_dim_color
vec4_t menu_grayed_color
vec4_t menu_highlight_color
vec4_t menu_red_color
vec4_t menu_text_color
int menuCount
how many menus
Definition at line 54 of file ui_shared.c.
Referenced by Display_CacheAll(), Display_CaptureItem(), Display_CloseCinematics(), Display_CursorType(), Display_MouseMove(), Display_VisibleMenuCount(), Menu_Count(), Menu_Get(), Menu_GetFocused(), Menu_New(), Menu_PaintAll(), Menu_Reset(), Menus_Activate(), Menus_ActivateByName(), Menus_AnyFullScreenVisible(), Menus_CloseAll(), Menus_FindByName(), Menus_HandleOOBClick(), Script_CloseAllOtherMenus(), and String_Init().
menuDef_t Menus[MAX_MENUS]
defined menus
Definition at line 53 of file ui_shared.c.
Referenced by Menu_Get(), Menu_GetFocused(), Menu_New(), Menu_PaintAll(), Menus_Activate(), Menus_ActivateByName(), Menus_AnyFullScreenVisible(), Menus_CloseAll(), Menus_FindByName(), Menus_HandleOOBClick(), and Script_CloseAllOtherMenus().
int modalMenuCount
Definition at line 59 of file ui_shared.c.
Referenced by Menus_ActivateByName(), Menus_CloseByName(), and String_Init().
menuDef_t* modalMenuStack[MAX_MODAL_MENUS]
Definition at line 58 of file ui_shared.c.
Referenced by Menus_ActivateByName(), and Menus_CloseByName().
vec4_t name_color
scrollInfo_t scrollInfo
Definition at line 39 of file ui_shared.c.
Referenced by Item_StartCapture().
vec4_t text_color_disabled
vec4_t text_color_highlight
vec4_t text_color_normal
vmCvar_t ui_autoactivate
Definition at line 8629 of file ui_main.c.
vmCvar_t ui_blackout
Definition at line 8681 of file ui_main.c.
Referenced by UI_Refresh().
vmCvar_t ui_brassTime
Definition at line 8623 of file ui_main.c.
vmCvar_t ui_browserMapFilter
Definition at line 8657 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserMapFilterCheckBox
Definition at line 8658 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserModFilter
Definition at line 8656 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserOssFilter
Definition at line 8660 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowAntilag
Definition at line 8651 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowEmptyOrFull
Definition at line 8646 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowFriendlyFire
Definition at line 8648 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowHumans
Definition at line 8654 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowMaxlives
Definition at line 8649 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowPasswordProtected
Definition at line 8647 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowTeamBalanced
Definition at line 8653 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_browserShowWeaponsRestricted
Definition at line 8652 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_campaignIndex
Definition at line 8677 of file ui_main.c.
Referenced by UI_FeederSelection().
vmCvar_t ui_cg_crosshairAlpha
Definition at line 8684 of file ui_main.c.
vmCvar_t ui_cg_crosshairAlphaAlt
Definition at line 8685 of file ui_main.c.
vmCvar_t ui_cg_crosshairColor
Definition at line 8682 of file ui_main.c.
vmCvar_t ui_cg_crosshairColorAlt
Definition at line 8683 of file ui_main.c.
vmCvar_t ui_cg_crosshairSize
Definition at line 8686 of file ui_main.c.
Referenced by UI_DrawCrosshair().
vmCvar_t ui_currentCampaign
Definition at line 8676 of file ui_main.c.
Referenced by UI_DrawCampaignCinematic(), UI_DrawCampaignMapDescription(), UI_DrawCampaignMapPreview(), UI_DrawCampaignName(), UI_DrawCampaignPreview(), UI_FeederSelection(), UI_OwnerDrawVisible(), and UI_RunMenuScript().
vmCvar_t ui_currentCampaignCompleted
Definition at line 8678 of file ui_main.c.
Referenced by UI_FeederSelection().
vmCvar_t ui_currentMap
Definition at line 8643 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), and UI_StopCinematic().
vmCvar_t ui_currentNetCampaign
Definition at line 8675 of file ui_main.c.
Referenced by UI_DrawCampaignCinematic(), UI_DrawCampaignMapDescription(), UI_DrawCampaignMapPreview(), UI_DrawCampaignName(), UI_DrawCampaignPreview(), and UI_FeederSelection().
vmCvar_t ui_currentNetMap
Definition at line 8642 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), and UI_RunMenuScript().
vmCvar_t ui_dedicated
Definition at line 8638 of file ui_main.c.
Referenced by UI_RunMenuScript().
vmCvar_t ui_drawCrosshair
Definition at line 8624 of file ui_main.c.
vmCvar_t ui_drawCrosshairNames
Definition at line 8626 of file ui_main.c.
vmCvar_t ui_drawCrosshairPickups
Definition at line 8627 of file ui_main.c.
vmCvar_t ui_gameType
Definition at line 8635 of file ui_main.c.
Referenced by UI_DrawGameType(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederItemImage(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_MapCountByGameType(), UI_OwnerDrawWidth(), and UI_SelectedMap().
vmCvar_t ui_joinGameType
Definition at line 8637 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
vmCvar_t ui_mapIndex
Definition at line 8644 of file ui_main.c.
Referenced by UI_FeederSelection(), and UI_RunMenuScript().
vmCvar_t ui_marks
Definition at line 8628 of file ui_main.c.
vmCvar_t ui_menuFiles
Definition at line 8634 of file ui_main.c.
vmCvar_t ui_netGameType
Definition at line 8636 of file ui_main.c.
Referenced by UI_DrawCampaignDescription(), UI_DrawGametypeDescription(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederItemImage(), UI_FeederSelection(), UI_MapCountByGameType(), UI_RunMenuScript(), and UI_SelectedMap().
vmCvar_t ui_netSource
Definition at line 8633 of file ui_main.c.
Referenced by UI_BinaryServerInsertion(), UI_BuildServerDisplayList(), UI_DrawServerRefreshDate(), UI_FeederItemText(), UI_FeederSelection(), UI_FeederSelectionClick(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_RunMenuScript(), UI_ServersQsortCompare(), and UI_UpdatePendingPings().
vmCvar_t ui_profile
Definition at line 8674 of file ui_main.c.
Referenced by UI_LoadProfiles(), and UI_RunMenuScript().
vmCvar_t ui_selectedPlayer
Definition at line 8631 of file ui_main.c.
Referenced by UI_OwnerDrawVisible().
vmCvar_t ui_selectedPlayerName
Definition at line 8632 of file ui_main.c.
vmCvar_t ui_serverBrowserSettings
Definition at line 8690 of file ui_main.c.
Referenced by UI_BuildServerDisplayList(), UI_FeederItemText(), and UI_SetActiveMenu().
vmCvar_t ui_serverFilterType
Definition at line 8641 of file ui_main.c.
Referenced by UI_DrawNetFilter(), UI_NetFilter_HandleKey(), and UI_OwnerDrawWidth().
vmCvar_t ui_serverStatusTimeOut
Definition at line 8662 of file ui_main.c.
uiInfo_t uiInfo
Definition at line 37 of file ui_main.c.
Referenced by Script_ConditionalScript(), UI_AdjustFrom640(), UI_ConsoleCommand(), UI_DescriptionForCampaign(), UI_DownloadInfo(), UI_DrawLoadPanel(), UI_DrawTopBottom(), UI_FillRect(), UI_FindCampaignInCampaignList(), UI_FindMapInfoByMapname(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadCampaigns(), UI_LoadCampaignsFromFile(), and UI_NameForCampaign().