ET: Legacy: src/ui/ui_menu.c File Reference
ui_menu.c File Reference
String allocation/managment.
#include "ui_shared.h"
#include "ui_local.h"
Functions
void Menu_FadeMenuByName (const char *p, qboolean *bAbort, qboolean fadeOut)
Menu_FadeMenuByName.
void Menu_TransitionItemByName (menuDef_t *menu, const char *p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt)
Menu_TransitionItemByName.
void Menu_OrbitItemByName (menuDef_t *menu, const char *p, float x, float y, float cx, float cy, int time)
Menu_OrbitItemByName.
void Menu_Init (menuDef_t *menu)
Menu_Init.
menuDef_t * Menu_GetFocused (void)
Menu_GetFocused.
void Menu_ScrollFeeder (menuDef_t *menu, int feeder, qboolean down)
Menu_ScrollFeeder.
void Menu_SetFeederSelection (menuDef_t *menu, int feeder, int index, const char *name)
Menu_SetFeederSelection.
qboolean Menus_AnyFullScreenVisible (void)
Menus_AnyFullScreenVisible.
menuDef_t * Menus_ActivateByName (const char *p, qboolean modalStack)
Menus_ActivateByName.
void Menu_UpdatePosition (menuDef_t *menu)
Menu_UpdatePosition.
void Menu_PostParse (menuDef_t *menu)
Menu_PostParse.
itemDef_t * Menu_ClearFocus (menuDef_t *menu)
Menu_ClearFocus.
int Menu_ItemsMatchingGroup (menuDef_t *menu, const char *name)
Menu_ItemsMatchingGroup.
itemDef_t * Menu_GetMatchingItemByNumber (menuDef_t *menu, int index, const char *name)
Menu_GetMatchingItemByNumber.
itemDef_t * Menu_FindItemByName (menuDef_t *menu, const char *p)
Menu_FindItemByName.
void Menu_ShowItemByName (menuDef_t *menu, const char *p, qboolean bShow)
Menu_ShowItemByName.
void Menu_FadeItemByName (menuDef_t *menu, const char *p, qboolean fadeOut)
Menu_FadeItemByName.
menuDef_t * Menus_FindByName (const char *p)
Menus_FindByName.
void Menus_ShowByName (const char *p)
Menus_ShowByName.
void Menus_OpenByName (const char *p)
Menus_OpenByName.
void Menu_RunCloseScript (menuDef_t *menu)
Menu_RunCloseScript.
void Menus_CloseByName (const char *p)
Menus_CloseByName.
void Menus_CloseAll (void)
Menus_CloseAll.
itemDef_t * Menu_SetPrevCursorItem (menuDef_t *menu)
Menu_SetPrevCursorItem.
itemDef_t * Menu_SetNextCursorItem (menuDef_t *menu)
Menu_SetNextCursorItem.
void Menu_CloseCinematics (menuDef_t *menu)
Menu_CloseCinematics.
void Menus_Activate (menuDef_t *menu)
Menus_Activate.
qboolean Menus_CaptureFuncActive (void)
Menus_CaptureFuncActive.
void Menus_HandleOOBClick (menuDef_t *menu, int key, qboolean down)
Menus_HandleOOBClick.
void Menu_HandleKey (menuDef_t *menu, int key, qboolean down)
Menu_HandleKey.
void Menu_HandleMouseMove (menuDef_t *menu, float x, float y)
Menu_HandleMouseMove.
void Menu_Paint (menuDef_t *menu, qboolean forcePaint)
Menu_Paint.
void Menu_PaintAll (void)
Menu_PaintAll.
void Menu_New (int handle)
Menu_New.
int Menu_Count (void)
Menu_Count.
menuDef_t * Menu_Get (int handle)
Menu_Get.
void Menu_Reset (void)
Menu_Reset.
qboolean Menu_OverActiveItem (menuDef_t *menu, float x, float y)
Menu_OverActiveItem.
Detailed Description
String allocation/managment.
Definition in file ui_menu.c.
Function Documentation
itemDef_t* Menu_ClearFocus (menuDef_t * menu)
Menu_ClearFocus.
Parameters
[in] menu
Returns
Definition at line 411 of file ui_menu.c.
Referenced by Item_SetFocus(), Menus_CloseByName(), Script_ClearFocus(), Script_SetEditFocus(), Script_SetFocus(), and Script_SetMenuFocus().
void Menu_CloseCinematics (menuDef_t * menu)
Menu_CloseCinematics.
Parameters
[in] menu
Definition at line 870 of file ui_menu.c.
Referenced by Display_CloseCinematics().
int Menu_Count (void)
Menu_Count.
Returns
Definition at line 1470 of file ui_menu.c.
Referenced by UI_KeyEvent(), UI_LoadProfiles(), UI_MouseEvent(), UI_Refresh(), and UI_SetActiveMenu().
void Menu_FadeItemByName (menuDef_t * menu, const char * p, qboolean fadeOut)
Menu_FadeItemByName.
Parameters
[in] menu
[in] p
[in] fadeOut
Definition at line 609 of file ui_menu.c.
Referenced by Script_FadeIn(), and Script_FadeOut().
void Menu_FadeMenuByName (const char * p, qboolean * bAbort, qboolean fadeOut)
Menu_FadeMenuByName.
Parameters
[in] p
bAbort - unused
[in] fadeOut
Definition at line 45 of file ui_menu.c.
Referenced by Script_FadeInMenu(), and Script_FadeOutMenu().
itemDef_t* Menu_FindItemByName (menuDef_t * menu, const char * p)
Menu_FindItemByName.
Parameters
[in] menu
[in] p
Returns
Definition at line 541 of file ui_menu.c.
Referenced by Script_AddListItem(), Script_SetEditFocus(), and Script_SetFocus().
menuDef_t* Menu_Get (int handle)
Menu_Get.
Parameters
[in] handle
Returns
Definition at line 1480 of file ui_menu.c.
Referenced by UI_LoadProfiles().
menuDef_t* Menu_GetFocused (void)
Menu_GetFocused.
Returns
Definition at line 179 of file ui_menu.c.
Referenced by Display_HandleKey(), Display_MouseMove(), Menu_SetFeederSelection(), Menus_ActivateByName(), UI_CheckExecKey(), UI_KeyEvent(), and UI_Load().
itemDef_t* Menu_GetMatchingItemByNumber (menuDef_t * menu, int index, const char * name)
Menu_GetMatchingItemByNumber.
Parameters
[in] menu
[in] index
[in] name
Returns
Definition at line 494 of file ui_menu.c.
Referenced by Menu_FadeItemByName(), Menu_OrbitItemByName(), Menu_ShowItemByName(), Menu_TransitionItemByName(), Script_SetItemColor(), Script_SetMenuItemColor(), and Script_SetTextStyle().
void Menu_HandleKey (menuDef_t * menu, int key, qboolean down)
Menu_HandleKey.
Parameters
[in] menu
[in] key
[in] down
Definition at line 992 of file ui_menu.c.
Referenced by Display_HandleKey(), Menus_HandleOOBClick(), and UI_KeyEvent().
void Menu_HandleMouseMove (menuDef_t * menu, float x, float y)
Menu_HandleMouseMove.
Parameters
[in] menu
[in] x
[in] y
Todo:
: this is the whole issue of focus vs. mouse over..
Definition at line 1205 of file ui_menu.c.
Referenced by Display_MouseMove(), Menu_HandleKey(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), and Menus_HandleOOBClick().
void Menu_Init (menuDef_t * menu)
Menu_Init.
Parameters
[in] menu
Definition at line 140 of file ui_menu.c.
Referenced by Menu_New().
int Menu_ItemsMatchingGroup (menuDef_t * menu, const char * name)
Menu_ItemsMatchingGroup.
Parameters
[in] menu
[in] name
Returns
Definition at line 453 of file ui_menu.c.
Referenced by Menu_FadeItemByName(), Menu_OrbitItemByName(), Menu_ShowItemByName(), Menu_TransitionItemByName(), Script_SetItemColor(), Script_SetMenuItemColor(), and Script_SetTextStyle().
void Menu_New (int handle)
Menu_New.
Parameters
[in] handle
Definition at line 1451 of file ui_menu.c.
Referenced by UI_ParseMenu().
void Menu_OrbitItemByName (menuDef_t * menu, const char * p, float x, float y, float cx, float cy, int time)
Menu_OrbitItemByName.
Parameters
[in] menu
[in] p
[in] x
[in] y
[in] cx
[in] cy
[in] time
Definition at line 114 of file ui_menu.c.
Referenced by Script_Orbit().
qboolean Menu_OverActiveItem (menuDef_t * menu, float x, float y)
Menu_OverActiveItem.
Parameters
[in] menu
[in] x
[in] y
Returns
Definition at line 1507 of file ui_menu.c.
Referenced by Menus_HandleOOBClick().
void Menu_Paint (menuDef_t * menu, qboolean forcePaint)
Menu_Paint.
Parameters
[in] menu
[in] forcePaint
Todo:
: make sure we have a default shader if fullscreen is set with no background
Definition at line 1319 of file ui_menu.c.
Referenced by Menu_PaintAll().
void Menu_PaintAll (void)
Menu_PaintAll.
Definition at line 1412 of file ui_menu.c.
Referenced by CG_Draw2D(), and UI_Refresh().
void Menu_PostParse (menuDef_t * menu)
Menu_PostParse.
Parameters
[in,out] menu
Definition at line 390 of file ui_menu.c.
Referenced by Menu_New().
void Menu_Reset (void)
Menu_Reset.
Definition at line 1495 of file ui_menu.c.
Referenced by CG_LoadHudMenu(), and UI_LoadMenus().
void Menu_RunCloseScript (menuDef_t * menu)
Menu_RunCloseScript.
Parameters
[in] menu
Definition at line 682 of file ui_menu.c.
Referenced by Menus_CloseAll(), Menus_CloseByName(), Menus_HandleOOBClick(), and Script_CloseAllOtherMenus().
void Menu_ScrollFeeder (menuDef_t * menu, int feeder, qboolean down)
Menu_ScrollFeeder.
Parameters
[in] menu
[in] feeder
[in] down
Note
Unused
Definition at line 201 of file ui_menu.c.
void Menu_SetFeederSelection (menuDef_t * menu, int feeder, int index, const char * name)
Menu_SetFeederSelection.
Parameters
[in,out] menu
[in] feeder
[in] index
[in] name
Definition at line 225 of file ui_menu.c.
Referenced by UI_BuildServerDisplayList(), UI_BuildServerStatus(), UI_GameType_HandleKey(), UI_LoadProfiles(), UI_RunMenuScript(), and UI_SetActiveMenu().
itemDef_t* Menu_SetNextCursorItem (menuDef_t * menu)
Menu_SetNextCursorItem.
Parameters
[in,out] menu
Returns
Definition at line 821 of file ui_menu.c.
Referenced by Item_TextField_HandleKey(), and Menu_HandleKey().
itemDef_t* Menu_SetPrevCursorItem (menuDef_t * menu)
Menu_SetPrevCursorItem.
Parameters
[in,out] menu
Returns
Definition at line 779 of file ui_menu.c.
Referenced by Item_TextField_HandleKey(), and Menu_HandleKey().
void Menu_ShowItemByName (menuDef_t * menu, const char * p, qboolean bShow)
Menu_ShowItemByName.
Parameters
[in] menu
[in] p
[in] bShow
Definition at line 567 of file ui_menu.c.
Referenced by Script_Hide(), Script_Show(), UI_BuildServerStatus(), UI_GetServerStatusInfo(), and UI_RunMenuScript().
void Menu_TransitionItemByName (menuDef_t * menu, const char * p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt)
Menu_TransitionItemByName.
Parameters
[in] menu
[in] p
[in] rectFrom
[in] rectTo
[in] time
[in] amt
Definition at line 80 of file ui_menu.c.
Referenced by Script_Transition().
void Menu_UpdatePosition (menuDef_t * menu)
Menu_UpdatePosition.
Parameters
[in] menu
Definition at line 321 of file ui_menu.c.
Referenced by Display_MouseMove(), Item_ListBox_HandleKey(), and Menu_PostParse().
void Menus_Activate (menuDef_t * menu)
Menus_Activate.
Parameters
[in,out] menu
Definition at line 892 of file ui_menu.c.
Referenced by Menus_ActivateByName(), and Menus_ShowByName().
menuDef_t* Menus_ActivateByName (const char * p, qboolean modalStack)
Menus_ActivateByName.
Parameters
[in] p
[in] modalStack
Returns
Definition at line 286 of file ui_menu.c.
Referenced by Item_ListBox_HandleKey(), Menus_CloseByName(), Menus_OpenByName(), UI_Load(), UI_RunMenuScript(), and UI_SetActiveMenu().
qboolean Menus_AnyFullScreenVisible (void)
Menus_AnyFullScreenVisible.
Returns
Definition at line 266 of file ui_menu.c.
Referenced by _UI_IsFullscreen().
qboolean Menus_CaptureFuncActive (void)
Menus_CaptureFuncActive.
Returns
Definition at line 927 of file ui_menu.c.
Referenced by UI_FeederSelectionClick().
void Menus_CloseAll (void)
Menus_CloseAll.
Definition at line 741 of file ui_menu.c.
Referenced by Script_CloseAll(), UI_Init(), UI_Load(), UI_RunMenuScript(), and UI_SetActiveMenu().
void Menus_CloseByName (const char * p)
Menus_CloseByName.
Parameters
[in] p
Definition at line 697 of file ui_menu.c.
Referenced by CG_DrawTimedMenus(), Script_Close(), and UI_RunMenuScript().
menuDef_t* Menus_FindByName (const char * p)
Menus_FindByName.
Parameters
[in] p
Returns
Definition at line 639 of file ui_menu.c.
Referenced by Item_ListBox_HandleKey(), Menu_FadeMenuByName(), Menu_SetFeederSelection(), Menus_CloseByName(), Menus_ShowByName(), Script_SetMenuFocus(), Script_SetMenuItemColor(), UI_BuildServerStatus(), UI_GetServerStatusInfo(), and UI_RunMenuScript().
void Menus_HandleOOBClick (menuDef_t * menu, int key, qboolean down)
Menus_HandleOOBClick.
Parameters
[in,out] menu
[in] key
[in] down
Definition at line 945 of file ui_menu.c.
Referenced by Menu_HandleKey().
void Menus_OpenByName (const char * p)
Menus_OpenByName.
Parameters
[in] p
Definition at line 673 of file ui_menu.c.
Referenced by Script_ConditionalOpen(), Script_Open(), UI_ConsoleCommand(), UI_RunMenuScript(), and UI_SetActiveMenu().
void Menus_ShowByName (const char * p)
Menus_ShowByName.
Parameters
[in] p
Note
Unused
Definition at line 659 of file ui_menu.c.