ET: Legacy: src/ui/ui_shared.h File Reference
ui_shared.h File Reference
Shared between cgame and ui.
#include "../qcommon/q_shared.h"
#include "../renderercommon/tr_types.h"
#include "keycodes.h"
#include "../../etmain/ui/menudef.h"
Data Structures
struct windowDef_t
struct colorRangeDef_t
struct columnInfo_s
struct listBoxDef_s
struct editFieldDef_s
struct multiDef_s
struct modelDef_s
struct itemDef_s
struct menuDef_t
struct cachedAssets_t
struct commandDef_t
struct displayContextDef_t
struct panel_button_text_s
struct panel_button_s
Macros
#define MAX_MENUDEFFILE 4096
#define MAX_MENUFILE 32768
#define MAX_MENUS 256
#define MAX_MENUDEPTH 8
#define MAX_MENUITEMS 128
ioquake3 has 96
#define MAX_COLOR_RANGES 10
#define MAX_MODAL_MENUS 16
#define WINDOW_MOUSEOVER 0x00000001
mouse is over it, non exclusive
#define WINDOW_HASFOCUS 0x00000002
has cursor focus, exclusive
#define WINDOW_VISIBLE 0x00000004
is visible
#define WINDOW_GREY 0x00000008
is visible but grey (non-active)
#define WINDOW_DECORATION 0x00000010
for decoration only, no mouse, keyboard, etc..
#define WINDOW_FADINGOUT 0x00000020
fading out, non-active
#define WINDOW_FADINGIN 0x00000040
fading in
#define WINDOW_MOUSEOVERTEXT 0x00000080
mouse is over it, non exclusive
#define WINDOW_INTRANSITION 0x00000100
window is in transition
#define WINDOW_FORECOLORSET 0x00000200
forecolor was explicitly set (used to color alpha images or not)
#define WINDOW_HORIZONTAL 0x00000400
for list boxes and sliders, vertical is default this is set of horizontal
#define WINDOW_LB_LEFTARROW 0x00000800
mouse is over left/up arrow
#define WINDOW_LB_RIGHTARROW 0x00001000
mouse is over right/down arrow
#define WINDOW_LB_THUMB 0x00002000
mouse is over thumb
#define WINDOW_LB_PGUP 0x00004000
mouse is over page up
#define WINDOW_LB_PGDN 0x00008000
mouse is over page down
#define WINDOW_ORBITING 0x00010000
item is in orbit
#define WINDOW_OOB_CLICK 0x00020000
close on out of bounds click
#define WINDOW_WRAPPED 0x00040000
manually wrap text
#define WINDOW_AUTOWRAPPED 0x00080000
auto wrap text
#define WINDOW_FORCED 0x00100000
forced open
#define WINDOW_POPUP 0x00200000
popup
#define WINDOW_BACKCOLORSET 0x00400000
backcolor was explicitly set
#define WINDOW_TIMEDVISIBLE 0x00800000
visibility timing (NOT implemented)
#define WINDOW_IGNORE_HUDALPHA 0x01000000
window will apply cg_hudAlpha value to colors unless this flag is set
#define WINDOW_DRAWALWAYSONTOP 0x02000000
#define WINDOW_MODAL 0x04000000
window is modal, the window to go back to is stored in a stack
#define WINDOW_FOCUSPULSE 0x08000000
#define WINDOW_TEXTASINT 0x10000000
#define WINDOW_TEXTASFLOAT 0x20000000
#define WINDOW_LB_SOMEWHERE 0x40000000
#define CURSOR_NONE 0x00000001
#define CURSOR_ARROW 0x00000002
#define CURSOR_SIZER 0x00000004
#define TEXTFIELD(x) (x == ITEM_TYPE_EDITFIELD || x == ITEM_TYPE_NUMERICFIELD)
#define STRING_POOL_SIZE 384 * 1024
#define MAX_EDITFIELD 256
#define ART_FX_BASE "menu/art/fx_base"
#define ART_FX_BLUE "menu/art/fx_blue"
#define ART_FX_CYAN "menu/art/fx_cyan"
#define ART_FX_GREEN "menu/art/fx_grn"
#define ART_FX_RED "menu/art/fx_red"
#define ART_FX_TEAL "menu/art/fx_teal"
#define ART_FX_WHITE "menu/art/fx_white"
#define ART_FX_YELLOW "menu/art/fx_yel"
#define ASSET_GRADIENTBAR "ui/assets/gradientbar2.tga"
#define ASSET_SCROLLBAR "ui/assets/scrollbar.tga"
#define ASSET_SCROLLBAR_ARROWDOWN "ui/assets/scrollbar_arrow_dwn_a.tga"
#define ASSET_SCROLLBAR_ARROWUP "ui/assets/scrollbar_arrow_up_a.tga"
#define ASSET_SCROLLBAR_ARROWLEFT "ui/assets/scrollbar_arrow_left.tga"
#define ASSET_SCROLLBAR_ARROWRIGHT "ui/assets/scrollbar_arrow_right.tga"
#define ASSET_SCROLL_THUMB "ui/assets/scrollbar_thumb.tga"
#define ASSET_SLIDER_BAR "ui/assets/slider2.tga"
#define ASSET_SLIDER_THUMB "ui/assets/sliderbutt_1.tga"
#define ASSET_CHECKBOX_CHECK "ui/assets/check.tga"
#define ASSET_CHECKBOX_CHECK_NOT "ui/assets/check_not.tga"
#define ASSET_CHECKBOX_CHECK_NO "ui/assets/check_no.tga"
#define SCROLLBAR_SIZE 16.0f
#define SLIDER_WIDTH 96.0f
#define SLIDER_HEIGHT 10.0f
16.0
#define SLIDER_THUMB_WIDTH 12.0f
#define SLIDER_THUMB_HEIGHT 12.0f
20.0
#define NUM_CROSSHAIRS 16
#define MAX_LB_COLUMNS 16
#define MAX_MULTI_CVARS 32
#define CVAR_ENABLE 0x00000001
#define CVAR_DISABLE 0x00000002
#define CVAR_SHOW 0x00000004
#define CVAR_HIDE 0x00000008
#define CVAR_NOTOGGLE 0x00000010
#define SVS_DISABLED_SHOW 0x01
#define SVS_ENABLED_SHOW 0x02
#define UI_MAX_TEXT_LINES 64
#define UI_FONT_COUNT 6
#define IS_FUNC_SUPPORTED(x) (uiInfo.legacyClient >= x)
#define RegisterFont(fontName, pointSize, font) Q_UTF8_RegisterFont(fontName, pointSize, font, IS_FUNC_SUPPORTED(UNICODE_SUPPORT_VERSION), &trap_R_RegisterFont)
#define Q_UTF8_GlyphScale(font) ((fontInfo_t *)font->fontData)->glyphScale
#define Q_UTF8_GetGlyph(font, string) font->GetGlyph(font->fontData, Q_UTF8_CodePoint(string))
Typedefs
typedef windowDef_t Window
typedef struct columnInfo_s columnInfo_t
typedef struct listBoxDef_s listBoxDef_t
typedef struct editFieldDef_s editFieldDef_t
typedef struct multiDef_s multiDef_t
typedef struct modelDef_s modelDef_t
typedef struct itemDef_s itemDef_t
typedef struct panel_button_s panel_button_t
Button struct.
typedef struct panel_button_text_s panel_button_text_t
typedef qboolean(* panel_button_key_down) (panel_button_t *, int)
typedef qboolean(* panel_button_key_up) (panel_button_t *, int)
typedef void(* panel_button_render) (panel_button_t *)
typedef void(* panel_button_postprocess) (panel_button_t *)
Functions
void PC_SourceError (int handle, const char *format,...)
PC_SourceError.
qboolean PC_Float_Parse (int handle, float *f)
PC_Float_Parse.
qboolean PC_Color_Parse (int handle, vec4_t *c)
PC_Color_Parse.
qboolean PC_Int_Parse (int handle, int *i)
PC_Int_Parse.
qboolean PC_Rect_Parse (int handle, rectDef_t *r)
PC_Rect_Parse.
qboolean PC_String_Parse (int handle, const char **out)
PC_String_Parse.
qboolean PC_Script_Parse (int handle, const char **out)
PC_Script_Parse.
qboolean PC_Char_Parse (int handle, char *out)
PC_Char_Parse.
void Window_Init (Window *w)
Initializes a window structure (windowDef_t) with defaults.
void Window_CloseCinematic (windowDef_t *window)
Window_CloseCinematic.
void Window_Paint (Window *w, float fadeAmount, float fadeClamp, float fadeCycle)
Window_Paint.
void Init_Display (displayContextDef_t *dc)
Initializes the display with a structure to all the drawing routines.
int Display_VisibleMenuCount (void)
Display_VisibleMenuCount.
void Display_CloseCinematics (void)
Display_CloseCinematics.
displayContextDef_t * Display_GetContext (void)
Display_GetContext.
void * Display_CaptureItem (int x, int y)
Display_CaptureItem.
qboolean Display_MouseMove (void *p, int x, int y)
Display_MouseMove.
int Display_CursorType (int x, int y)
Display_CursorType.
qboolean Display_KeyBindPending (void)
Display_KeyBindPending.
void Display_CacheAll (void)
Display_CacheAll.
void Display_HandleKey (int key, qboolean down, int x, int y)
Display_HandleKey.
qboolean Float_Parse (char **p, float *f)
Float_Parse.
qboolean Color_Parse (char **p, vec4_t *c)
Color_Parse.
qboolean Int_Parse (char **p, int *i)
Int_Parse.
qboolean Rect_Parse (char **p, rectDef_t *r)
Rect_Parse.
qboolean String_Parse (char **p, const char **out)
String_Parse.
qboolean Script_Parse (char **p, const char **out)
void Menu_Init (menuDef_t *menu)
Menu_Init.
void Menu_PostParse (menuDef_t *menu)
Menu_PostParse.
menuDef_t * Menu_GetFocused (void)
Menu_GetFocused.
void Menus_OpenByName (const char *p)
Menus_OpenByName.
menuDef_t * Menus_FindByName (const char *p)
Menus_FindByName.
void Menus_ShowByName (const char *p)
Menus_ShowByName.
void Menus_CloseByName (const char *p)
Menus_CloseByName.
void Menu_HandleKey (menuDef_t *menu, int key, qboolean down)
Menu_HandleKey.
void Menu_HandleMouseMove (menuDef_t *menu, float x, float y)
Menu_HandleMouseMove.
void Menu_ScrollFeeder (menuDef_t *menu, int feeder, qboolean down)
Menu_ScrollFeeder.
int Menu_Count (void)
Menu_Count.
menuDef_t * Menu_Get (int handle)
Menu_Get.
void Menu_New (int handle)
Menu_New.
void Menu_PaintAll (void)
Menu_PaintAll.
menuDef_t * Menus_ActivateByName (const char *p, qboolean modalStack)
Menus_ActivateByName.
void Menu_Reset (void)
Menu_Reset.
qboolean Menus_AnyFullScreenVisible (void)
Menus_AnyFullScreenVisible.
void Menus_Activate (menuDef_t *menu)
Menus_Activate.
qboolean Menus_CaptureFuncActive (void)
Menus_CaptureFuncActive.
void Menu_UpdatePosition (menuDef_t *menu)
Menu_UpdatePosition.
itemDef_t * Menu_SetPrevCursorItem (menuDef_t *menu)
Menu_SetPrevCursorItem.
itemDef_t * Menu_SetNextCursorItem (menuDef_t *menu)
Menu_SetNextCursorItem.
void Menu_CloseCinematics (menuDef_t *menu)
Menu_CloseCinematics.
void Menu_FadeMenuByName (const char *p, qboolean *bAbort, qboolean fadeOut)
Menu_FadeMenuByName.
void Menu_TransitionItemByName (menuDef_t *menu, const char *p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt)
Menu_TransitionItemByName.
void Menu_OrbitItemByName (menuDef_t *menu, const char *p, float x, float y, float cx, float cy, int time)
Menu_OrbitItemByName.
void Menu_RunCloseScript (menuDef_t *menu)
Menu_RunCloseScript.
int Menu_ItemsMatchingGroup (menuDef_t *menu, const char *name)
Menu_ItemsMatchingGroup.
itemDef_t * Menu_GetMatchingItemByNumber (menuDef_t *menu, int index, const char *name)
Menu_GetMatchingItemByNumber.
void Menu_FadeItemByName (menuDef_t *menu, const char *p, qboolean fadeOut)
Menu_FadeItemByName.
itemDef_t * Menu_FindItemByName (menuDef_t *menu, const char *p)
Menu_FindItemByName.
itemDef_t * Menu_ClearFocus (menuDef_t *menu)
Menu_ClearFocus.
void Menu_ShowItemByName (menuDef_t *menu, const char *p, qboolean bShow)
Menu_ShowItemByName.
void Menu_SetupKeywordHash (void)
Menu_SetupKeywordHash.
qboolean Menu_OverActiveItem (menuDef_t *menu, float x, float y)
Menu_OverActiveItem.
void Menus_CloseAll (void)
Menus_CloseAll.
void Menu_Paint (menuDef_t *menu, qboolean forcePaint)
Menu_Paint.
void Menu_SetFeederSelection (menuDef_t *menu, int feeder, int index, const char *name)
Menu_SetFeederSelection.
qboolean Menu_Parse (int handle, menuDef_t *menu)
Menu_Parse.
void Item_Init (itemDef_t *item)
Item_Init.
qboolean Item_Bind_HandleKey (itemDef_t *item, int key, qboolean down)
Item_Bind_HandleKey.
qboolean Item_Combo_HandleKey (itemDef_t *item, int key)
Item_Combo_HandleKey.
void Item_ComboDeSelect (itemDef_t *item)
Item_ComboDeSelect.
qboolean Item_TextField_HandleKey (itemDef_t *item, int key)
Item_TextField_HandleKey.
void Item_HandleTextFieldDeSelect (itemDef_t *item)
Item_HandleTextFieldDeSelect.
qboolean Item_HandleKey (itemDef_t *item, int key, qboolean down)
Item_HandleKey.
void Item_Action (itemDef_t *item)
Item_Action.
qboolean Item_EnableShowViaCvar (itemDef_t *item, int flag)
Item_EnableShowViaCvar.
void Item_HandleTextFieldSelect (itemDef_t *item)
Item_HandleTextFieldSelect.
rectDef_t * Item_CorrectedTextRect (itemDef_t *item)
Item_CorrectedTextRect.
qboolean Item_SettingShow (itemDef_t *item, qboolean fVoteTest)
Sisplay if we poll on a server toggle setting We want current settings, so this is a bit of a perf hit, but this is only during UI display.
void Item_MouseEnter (itemDef_t *item, float x, float y)
Item_MouseEnter.
void Item_MouseLeave (itemDef_t *item)
Item_MouseLeave.
void Item_SetMouseOver (itemDef_t *item, qboolean focus)
Item_SetMouseOver.
void Item_Paint (itemDef_t *item)
Item_Paint.
void Item_SetupKeywordHash (void)
Item_SetupKeywordHash.
void Item_SetScreenCoords (itemDef_t *item, float x, float y)
Item_SetScreenCoords.
qboolean Item_SetFocus (itemDef_t *item, float x, float y)
Will optionaly set focus to this item.
void Item_HandleSaveValue (void)
Item_HandleSaveValue.
qboolean Item_ListBox_HandleKey (itemDef_t *item, int key, qboolean down, qboolean force)
Item_ListBox_HandleKey.
void Item_UpdatePosition (itemDef_t *item)
Item_UpdatePosition.
void Item_RunScript (itemDef_t *item, qboolean *bAbort, const char *s)
Item_RunScript.
void Item_Tooltip_Initialize (itemDef_t *item)
Item_Tooltip_Initialize.
void Item_MouseActivate (itemDef_t *item)
This gets called on mouse1-3.
void Item_KeyboardActivate (itemDef_t *item)
This gets called on keyboard Enter and KP_Enter.
const char * String_Alloc (const char *p)
String_Alloc.
void String_Init (void)
String_Init.
void String_Report (void)
String_Report.
qboolean IsVisible (int flags)
IsVisible.
void ToWindowCoords (float *x, float *y, windowDef_t *window)
ToWindowCoords.
void Fade (int *flags, float *f, float clamp, int *nextTime, int offsetTime, qboolean bFlags, float fadeAmount)
Fade.
qboolean FileExists (const char *filename)
FileExists.
void LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Lerp and clamp each component of a and b into c by the fraction t.
qboolean Rect_ContainsPoint (rectDef_t *rect, float x, float y)
Rect_ContainsPoint.
qboolean Rect_ContainsPointN (rectDef_t *rect, float x, float y)
Rect_ContainsPointN.
void * UI_Alloc (int size)
UI_Alloc.
void UI_InitMemory (void)
UI_InitMemory.
qboolean UI_OutOfMemory (void)
UI_OutOfMemory.
void Controls_GetConfig (void)
Controls_GetConfig.
void Controls_SetConfig (qboolean restart)
Controls_SetConfig.
void Controls_SetDefaults (qboolean lefthanded)
Controls_SetDefaults.
int trap_PC_AddGlobalDefine (char *define)
trap_PC_AddGlobalDefine
int trap_PC_RemoveAllGlobalDefines (void)
trap_PC_RemoveAllGlobalDefines
int trap_PC_LoadSource (const char *filename)
trap_PC_LoadSource
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
trap_PC_ReadToken
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
trap_PC_SourceFileAndLine
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
void BG_PanelButton_RenderEdit (panel_button_t *button)
BG_PanelButton_RenderEdit.
qboolean BG_PanelButton_EditClick (panel_button_t *button, int key)
BG_PanelButton_EditClick.
qboolean BG_PanelButtonsKeyEvent (int key, qboolean down, panel_button_t **buttons)
BG_PanelButtonsKeyEvent.
void BG_PanelButtonsSetup (panel_button_t **buttons)
BG_PanelButtonsSetup.
void BG_PanelButtonsRender (panel_button_t **buttons)
BG_PanelButtonsRender.
void BG_PanelButtonsRender_Text (panel_button_t *button)
BG_PanelButtonsRender_Text.
void BG_PanelButtonsRender_TextExt (panel_button_t *button, const char *text)
BG_PanelButtonsRender_TextExt.
void BG_PanelButtonsRender_Img (panel_button_t *button)
BG_PanelButtonsRender_Img.
panel_button_t * BG_PanelButtonsGetHighlightButton (panel_button_t **buttons)
BG_PanelButtonsGetHighlightButton.
void BG_PanelButtons_SetFocusButton (panel_button_t *button)
BG_PanelButtons_SetFocusButton.
panel_button_t * BG_PanelButtons_GetFocusButton (void)
BG_PanelButtons_GetFocusButton.
qboolean BG_RectContainsPoint (float x, float y, float w, float h, float px, float py)
BG_RectContainsPoint.
qboolean BG_CursorInRect (rectDef_t *rect)
BG_CursorInRect.
void BG_FitTextToWidth_Ext (char *instr, float scale, float w, size_t size, fontHelper_t *font)
BG_FitTextToWidth_Ext.
void AdjustFrom640 (float *x, float *y, float *w, float *h)
AdjustFrom640.
void Cui_WideRect (rectDef_t *rect)
Convert rectangle-coordinates for use with the current aspectratio.
float Cui_WideX (float x)
Convert an x-coordinate for use with the current aspectratio. (if the current aspectratio is 4:3, then leave the x-coordinate unchanged)
float Cui_WideXoffset (void)
The horizontal center of screen pixel-difference of a 4:3 ratio vs. the current aspectratio.
void C_PanelButtonsSetup (panel_button_t **buttons, float xoffset)
Adjusting panel coordinates so it is horizontally centered.
Detailed Description
Shared between cgame and ui.
Definition in file ui_shared.h.
Macro Definition Documentation
#define ART_FX_BASE "menu/art/fx_base"
Definition at line 100 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_BLUE "menu/art/fx_blue"
Definition at line 101 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_CYAN "menu/art/fx_cyan"
Definition at line 102 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_GREEN "menu/art/fx_grn"
Definition at line 103 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_RED "menu/art/fx_red"
Definition at line 104 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_TEAL "menu/art/fx_teal"
Definition at line 105 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_WHITE "menu/art/fx_white"
Definition at line 106 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ART_FX_YELLOW "menu/art/fx_yel"
Definition at line 107 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_CHECKBOX_CHECK "ui/assets/check.tga"
Definition at line 118 of file ui_shared.h.
Referenced by AssetCache().
#define ASSET_CHECKBOX_CHECK_NO "ui/assets/check_no.tga"
Definition at line 120 of file ui_shared.h.
Referenced by AssetCache().
#define ASSET_CHECKBOX_CHECK_NOT "ui/assets/check_not.tga"
Definition at line 119 of file ui_shared.h.
Referenced by AssetCache().
#define ASSET_GRADIENTBAR "ui/assets/gradientbar2.tga"
Definition at line 109 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SCROLL_THUMB "ui/assets/scrollbar_thumb.tga"
Definition at line 115 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SCROLLBAR "ui/assets/scrollbar.tga"
Definition at line 110 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SCROLLBAR_ARROWDOWN "ui/assets/scrollbar_arrow_dwn_a.tga"
Definition at line 111 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SCROLLBAR_ARROWLEFT "ui/assets/scrollbar_arrow_left.tga"
Definition at line 113 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SCROLLBAR_ARROWRIGHT "ui/assets/scrollbar_arrow_right.tga"
Definition at line 114 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SCROLLBAR_ARROWUP "ui/assets/scrollbar_arrow_up_a.tga"
Definition at line 112 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SLIDER_BAR "ui/assets/slider2.tga"
Definition at line 116 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define ASSET_SLIDER_THUMB "ui/assets/sliderbutt_1.tga"
Definition at line 117 of file ui_shared.h.
Referenced by AssetCache(), and CG_AssetCache().
#define CURSOR_ARROW 0x00000002
Definition at line 87 of file ui_shared.h.
Referenced by Display_CursorType().
#define CURSOR_NONE 0x00000001
Definition at line 86 of file ui_shared.h.
#define CURSOR_SIZER 0x00000004
Definition at line 88 of file ui_shared.h.
Referenced by Display_CursorType().
#define CVAR_DISABLE 0x00000002
Definition at line 280 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_OwnerDraw_Paint(), Item_SetFocus(), Item_TextColor(), ItemParse_disableCvar(), and Menu_HandleMouseMove().
#define CVAR_ENABLE 0x00000001
Definition at line 279 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_OwnerDraw_Paint(), Item_SetFocus(), Item_TextColor(), ItemParse_enableCvar(), and Menu_HandleMouseMove().
#define CVAR_HIDE 0x00000008
Definition at line 282 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetFocus(), ItemParse_hideCvar(), and Menu_HandleMouseMove().
#define CVAR_NOTOGGLE 0x00000010
Definition at line 283 of file ui_shared.h.
Referenced by Item_CheckBox_HandleKey(), Item_YesNo_HandleKey(), and ItemParse_noToggle().
#define CVAR_SHOW 0x00000004
Definition at line 281 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetFocus(), ItemParse_showCvar(), Menu_HandleKey(), and Menu_HandleMouseMove().
#define IS_FUNC_SUPPORTED (x) (uiInfo.legacyClient >= x)
Definition at line 774 of file ui_shared.h.
Referenced by trap_R_RegisterFont(), and trap_TranslateString().
#define MAX_COLOR_RANGES 10
Definition at line 50 of file ui_shared.h.
Referenced by ParseColorRange().
#define MAX_EDITFIELD 256
Definition at line 98 of file ui_shared.h.
Referenced by BG_PanelButton_EditClick(), BG_PanelButton_RenderEdit(), CG_Debriefing_ChatEdit_Draw(), CG_Debriefing_ChatEditFinish(), CG_LimboPanel_NameEditFinish(), Item_TextField_InsertToCursor(), and Item_ValidateTypeData().
#define MAX_LB_COLUMNS 16
Todo:
: combine flags into bitfields to save space
: consolidate all of the common stuff in one structure for menus and items
Todo:
: need to put a type ptr that points to specific type info per type
Definition at line 186 of file ui_shared.h.
Referenced by ItemParse_columns().
#define MAX_MENUDEFFILE 4096
Definition at line 45 of file ui_shared.h.
Referenced by UI_FileText().
#define MAX_MENUDEPTH 8
Definition at line 48 of file ui_shared.h.
#define MAX_MENUFILE 32768
Definition at line 46 of file ui_shared.h.
Referenced by GetMenuBuffer().
#define MAX_MENUITEMS 128
ioquake3 has 96
Definition at line 49 of file ui_shared.h.
Referenced by MenuParse_itemDef().
#define MAX_MENUS 256
Definition at line 47 of file ui_shared.h.
Referenced by Menu_New().
#define MAX_MODAL_MENUS 16
Definition at line 51 of file ui_shared.h.
Referenced by Menus_ActivateByName().
#define MAX_MULTI_CVARS 32
Definition at line 237 of file ui_shared.h.
Referenced by ItemParse_cvarFloatList(), and ItemParse_cvarStrList().
#define NUM_CROSSHAIRS 16
Definition at line 127 of file ui_shared.h.
#define Q_UTF8_GetGlyph (font, string) font->GetGlyph(font->fontData, Q_UTF8_CodePoint(string))
Definition at line 779 of file ui_shared.h.
Referenced by CG_Text_Height_Ext(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), CG_Text_Width_Ext(), Multiline_Text_Height(), Multiline_Text_Width(), Text_Height_Ext(), Text_Paint_Ext(), Text_Paint_Limit(), Text_PaintWithCursor_Ext(), and Text_Width_Ext().
#define Q_UTF8_GlyphScale (font) ((fontInfo_t *)font->fontData)->glyphScale
Definition at line 778 of file ui_shared.h.
Referenced by CG_Text_Height_Ext(), CG_Text_Paint_Ext(), CG_Text_PaintWithCursor_Ext(), CG_Text_Width_Ext(), Multiline_Text_Height(), Multiline_Text_Width(), Text_Height_Ext(), Text_Paint_Ext(), Text_Paint_Limit(), Text_PaintWithCursor_Ext(), and Text_Width_Ext().
#define RegisterFont (fontName, pointSize, font) Q_UTF8_RegisterFont(fontName, pointSize, font, IS_FUNC_SUPPORTED(UNICODE_SUPPORT_VERSION), &trap_R_RegisterFont)
Definition at line 777 of file ui_shared.h.
Referenced by Asset_Parse(), CG_DrawConnectScreen(), CG_RegisterGraphics(), and UI_DrawLoadPanel().
#define SCROLLBAR_SIZE 16.0f
Definition at line 122 of file ui_shared.h.
Referenced by Item_ListBox_MouseEnter(), Item_ListBox_OverLB(), Item_ListBox_Paint(), Item_ListBox_ThumbDrawPosition(), Item_ListBox_ThumbPosition(), and Item_Scroll_ListBox_ThumbFunc().
#define SLIDER_HEIGHT 10.0f
16.0
Definition at line 124 of file ui_shared.h.
Referenced by Item_Slider_Paint().
#define SLIDER_THUMB_HEIGHT 12.0f
20.0
Definition at line 126 of file ui_shared.h.
Referenced by Item_Slider_OverSlider(), and Item_Slider_Paint().
#define SLIDER_THUMB_WIDTH 12.0f
Definition at line 125 of file ui_shared.h.
Referenced by Item_Slider_HandleKey(), Item_Slider_OverSlider(), and Item_Slider_Paint().
#define SLIDER_WIDTH 96.0f
Definition at line 123 of file ui_shared.h.
Referenced by Item_Scroll_Slider_ThumbFunc(), Item_Slider_HandleKey(), Item_Slider_Paint(), and Item_Slider_ThumbPosition().
#define STRING_POOL_SIZE 384 * 1024
Definition at line 95 of file ui_shared.h.
Referenced by String_Alloc(), and String_Report().
#define SVS_DISABLED_SHOW 0x01
Definition at line 286 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetFocus(), Item_SettingShow(), ItemParse_settingDisabled(), and Menu_HandleMouseMove().
#define SVS_ENABLED_SHOW 0x02
Definition at line 287 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetFocus(), Item_SettingShow(), ItemParse_settingEnabled(), and Menu_HandleMouseMove().
#define TEXTFIELD (x) (x == ITEM_TYPE_EDITFIELD || x == ITEM_TYPE_NUMERICFIELD)
Definition at line 90 of file ui_shared.h.
Referenced by Item_HandleSaveValue(), Item_KeyboardActivate(), Item_MouseActivate(), Item_TextField_HandleKey(), Item_ValidateTypeData(), and Script_SetEditFocus().
#define UI_FONT_COUNT 6
Definition at line 394 of file ui_shared.h.
Referenced by Asset_Parse(), and UI_Shutdown().
#define UI_MAX_TEXT_LINES 64
Definition at line 289 of file ui_shared.h.
#define WINDOW_AUTOWRAPPED 0x00080000
auto wrap text
Definition at line 72 of file ui_shared.h.
Referenced by Item_Text_Paint(), Item_Tooltip_Initialize(), and ItemParse_autowrapped().
#define WINDOW_BACKCOLORSET 0x00400000
backcolor was explicitly set
Definition at line 75 of file ui_shared.h.
Referenced by Script_SetColor().
#define WINDOW_DECORATION 0x00000010
for decoration only, no mouse, keyboard, etc..
Definition at line 57 of file ui_shared.h.
Referenced by Item_SetFocus(), ItemParse_decoration(), Menu_OverActiveItem(), and Script_SetFocus().
#define WINDOW_DRAWALWAYSONTOP 0x02000000
Definition at line 78 of file ui_shared.h.
Referenced by Item_Tooltip_Initialize(), Menu_PaintAll(), and MenuParse_drawAlwaysOnTop().
#define WINDOW_FADINGIN 0x00000040
fading in
Definition at line 59 of file ui_shared.h.
Referenced by Fade(), Menu_FadeItemByName(), and Menu_FadeMenuByName().
#define WINDOW_FADINGOUT 0x00000020
fading out, non-active
Definition at line 58 of file ui_shared.h.
Referenced by Fade(), IsVisible(), Menu_FadeItemByName(), and Menu_FadeMenuByName().
#define WINDOW_FOCUSPULSE 0x08000000
Definition at line 80 of file ui_shared.h.
Referenced by Item_Bind_Paint(), Item_CheckBox_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Slider_Paint(), Item_TextColor(), Item_TextField_Paint(), Item_YesNo_Paint(), and MenuParse_focuscolor().
#define WINDOW_FORCED 0x00100000
forced open
Definition at line 73 of file ui_shared.h.
Referenced by Display_VisibleMenuCount(), Menu_HandleMouseMove(), Menu_OverActiveItem(), and Menu_Paint().
#define WINDOW_FORECOLORSET 0x00000200
forecolor was explicitly set (used to color alpha images or not)
Definition at line 62 of file ui_shared.h.
Referenced by ItemParse_forecolor(), MenuParse_forecolor(), Script_SetColor(), Script_SetItemColor(), Script_SetMenuItemColor(), and Window_Paint().
#define WINDOW_GREY 0x00000008
is visible but grey (non-active)
Definition at line 56 of file ui_shared.h.
#define WINDOW_HASFOCUS 0x00000002
has cursor focus, exclusive
Definition at line 54 of file ui_shared.h.
Referenced by Item_Bind_Paint(), Item_CheckBox_HandleKey(), Item_CheckBox_Paint(), Item_ListBox_HandleKey(), Item_Multi_HandleKey(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_SetFocus(), Item_Slider_HandleKey(), Item_Slider_Paint(), Item_TextColor(), Item_TextField_Paint(), Item_YesNo_HandleKey(), Item_YesNo_Paint(), Menu_ClearFocus(), Menu_GetFocused(), Menu_HandleKey(), Menus_Activate(), Menus_ActivateByName(), Menus_CloseAll(), Menus_CloseByName(), Menus_HandleOOBClick(), Script_CloseAllOtherMenus(), Script_SetEditFocus(), Script_SetFocus(), and Script_SetMenuFocus().
#define WINDOW_HORIZONTAL 0x00000400
for list boxes and sliders, vertical is default this is set of horizontal
Definition at line 63 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MaxScroll(), Item_ListBox_MouseEnter(), Item_ListBox_OverLB(), Item_ListBox_Paint(), Item_ListBox_ThumbDrawPosition(), Item_ListBox_ThumbPosition(), Item_Scroll_ListBox_ThumbFunc(), and ItemParse_horizontalscroll().
#define WINDOW_IGNORE_HUDALPHA 0x01000000
window will apply cg_hudAlpha value to colors unless this flag is set
Definition at line 77 of file ui_shared.h.
#define WINDOW_INTRANSITION 0x00000100
window is in transition
Definition at line 61 of file ui_shared.h.
Referenced by Item_DoTransition(), Item_Paint(), and Menu_TransitionItemByName().
#define WINDOW_LB_LEFTARROW 0x00000800
mouse is over left/up arrow
Definition at line 64 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), Item_ListBox_OverLB(), Item_MouseLeave(), and Item_StartCapture().
#define WINDOW_LB_PGDN 0x00008000
mouse is over page down
Definition at line 68 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), and Item_ListBox_OverLB().
#define WINDOW_LB_PGUP 0x00004000
mouse is over page up
Definition at line 67 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), and Item_ListBox_OverLB().
#define WINDOW_LB_RIGHTARROW 0x00001000
mouse is over right/down arrow
Definition at line 65 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), Item_ListBox_OverLB(), Item_MouseLeave(), and Item_StartCapture().
#define WINDOW_LB_SOMEWHERE 0x40000000
Definition at line 83 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), and Item_ListBox_OverLB().
#define WINDOW_LB_THUMB 0x00002000
mouse is over thumb
Definition at line 66 of file ui_shared.h.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), Item_ListBox_OverLB(), Item_Slider_OverSlider(), and Item_StartCapture().
#define WINDOW_MODAL 0x04000000
window is modal, the window to go back to is stored in a stack
Definition at line 79 of file ui_shared.h.
Referenced by MenuParse_modal(), Menus_ActivateByName(), and Menus_CloseByName().
#define WINDOW_MOUSEOVER 0x00000001
mouse is over it, non exclusive
Definition at line 53 of file ui_shared.h.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetMouseOver(), Menu_ClearFocus(), Menu_HandleMouseMove(), Menu_Paint(), Menu_ShowItemByName(), Menus_Activate(), Menus_ActivateByName(), Menus_CloseAll(), Menus_CloseByName(), Menus_HandleOOBClick(), and Script_CloseAllOtherMenus().
#define WINDOW_MOUSEOVERTEXT 0x00000080
mouse is over it, non exclusive
Definition at line 60 of file ui_shared.h.
Referenced by Item_MouseEnter(), and Item_MouseLeave().
#define WINDOW_OOB_CLICK 0x00020000
close on out of bounds click
Definition at line 70 of file ui_shared.h.
Referenced by MenuParse_outOfBounds(), and Menus_HandleOOBClick().
#define WINDOW_ORBITING 0x00010000
item is in orbit
Definition at line 69 of file ui_shared.h.
Referenced by Item_Paint(), and Menu_OrbitItemByName().
#define WINDOW_POPUP 0x00200000
popup
Definition at line 74 of file ui_shared.h.
Referenced by Display_MouseMove(), Menu_HandleKey(), and MenuParse_popup().
#define WINDOW_TEXTASFLOAT 0x20000000
Definition at line 82 of file ui_shared.h.
Referenced by Item_Text_Paint(), and ItemParse_textasfloat().
#define WINDOW_TEXTASINT 0x10000000
Definition at line 81 of file ui_shared.h.
Referenced by Item_Text_Paint(), and ItemParse_textasint().
#define WINDOW_TIMEDVISIBLE 0x00800000
visibility timing (NOT implemented)
Definition at line 76 of file ui_shared.h.
Referenced by Item_Paint().
#define WINDOW_VISIBLE 0x00000004
is visible
Definition at line 55 of file ui_shared.h.
Referenced by Display_VisibleMenuCount(), Fade(), IsVisible(), Item_Paint(), Item_SetFocus(), Item_Tooltip_Initialize(), ItemParse_visible(), Menu_FadeItemByName(), Menu_FadeMenuByName(), Menu_GetFocused(), Menu_HandleMouseMove(), Menu_OrbitItemByName(), Menu_OverActiveItem(), Menu_Paint(), Menu_RunCloseScript(), Menu_ShowItemByName(), Menu_TransitionItemByName(), MenuParse_visible(), Menus_Activate(), Menus_AnyFullScreenVisible(), Menus_CloseAll(), Menus_CloseByName(), Menus_HandleOOBClick(), Script_CloseAllOtherMenus(), and Tooltip_ComputePosition().
#define WINDOW_WRAPPED 0x00040000
manually wrap text
Definition at line 71 of file ui_shared.h.
Referenced by Item_Text_Paint(), and ItemParse_wrapped().
Typedef Documentation
columnInfo_t
editFieldDef_t
itemDef_t
listBoxDef_t
modelDef_t
multiDef_t
typedef qboolean(* panel_button_key_down) (panel_button_t *, int)
Definition at line 707 of file ui_shared.h.
typedef qboolean(* panel_button_key_up) (panel_button_t *, int)
Definition at line 708 of file ui_shared.h.
typedef void(* panel_button_postprocess) (panel_button_t *)
Definition at line 710 of file ui_shared.h.
typedef void(* panel_button_render) (panel_button_t *)
Definition at line 709 of file ui_shared.h.
panel_button_t
Button struct.
Definition at line 691 of file ui_shared.h.
panel_button_text_t
Window
Todo:
FIXME: do something to separate text vs window stuff
Definition at line 162 of file ui_shared.h.
Function Documentation
void AdjustFrom640 (float * x, float * y, float * w, float * h)
AdjustFrom640.
Parameters
[out] x
[out] y
[out] w
[out] h
Definition at line 591 of file ui_shared.c.
Referenced by Item_Model_Paint().
qboolean BG_CursorInRect (rectDef_t * rect)
BG_CursorInRect.
Parameters
[in] rect
Returns
Definition at line 1319 of file ui_shared.c.
Referenced by BG_PanelButton_EditClick(), BG_PanelButtonsGetHighlightButton(), BG_PanelButtonsKeyEvent(), CG_Debriefing_Scrollbar_KeyDown(), CG_DrawBorder(), CG_LimboPanel_BriefingButton_Draw(), CG_LimboPanel_ClassBar_Draw(), CG_LimboPanel_RenderClassButton(), CG_LimboPanel_RenderTeamButton(), CG_LimboPanel_SpawnPointButton_Draw(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_DrawWeapon(), CG_LimboPanel_WeaponPanel_KeyUp(), CG_PanelButtonsRender_Button_Ext(), CG_SpeakerEditor_Broadcast_KeyUp(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_Looped_KeyUp(), CG_SpeakerEditor_Ok_KeyUp(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), and UI_FeederSelectionClick().
void BG_FitTextToWidth_Ext (char * instr, float scale, float w, size_t size, fontHelper_t * font)
BG_FitTextToWidth_Ext.
Parameters
[in,out] instr
[in] scale
[in] w
[in] size
[in] font
Definition at line 1855 of file ui_shared.c.
Referenced by CG_LoadPanel_RenderMissionDescriptionText(), and UI_LoadPanel_RenderLoadingText().
qboolean BG_PanelButton_EditClick (panel_button_t * button, int key)
BG_PanelButton_EditClick.
Parameters
[in] button
[in] key
Returns
Definition at line 1389 of file ui_shared.c.
Referenced by CG_Debriefing_KeyEvent(), and CG_SpeakerEditor_NoiseEdit_KeyDown().
void BG_PanelButton_RenderEdit (panel_button_t * button)
BG_PanelButton_RenderEdit.
Parameters
[in] button
Definition at line 1328 of file ui_shared.c.
Referenced by CG_SpeakerEditor_RenderEdit().
panel_button_t* BG_PanelButtons_GetFocusButton (void)
BG_PanelButtons_GetFocusButton.
Returns
Definition at line 1833 of file ui_shared.c.
Referenced by BG_PanelButton_EditClick(), BG_PanelButton_RenderEdit(), BG_PanelButtonsKeyEvent(), CG_Debriefing_KeyEvent(), CG_Debriefing_MouseEvent(), CG_Debriefing_Scrollbar_KeyUp(), CG_LimboPanel_WeaponPanel(), CG_LimboPanel_WeaponPanel_KeyUp(), CG_SpeakerEditor_Broadcast_KeyUp(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_Looped_KeyUp(), CG_SpeakerEditor_NoiseEdit_KeyDown(), CG_SpeakerEditor_Ok_KeyUp(), CG_SpeakerEditor_RenderButton(), CG_SpeakerEditor_RenderDropdown(), and CG_SpeakerEditor_RenderEdit().
void BG_PanelButtons_SetFocusButton (panel_button_t * button)
BG_PanelButtons_SetFocusButton.
Parameters
button
Definition at line 1842 of file ui_shared.c.
Referenced by BG_PanelButton_EditClick(), CG_Debriefing_KeyEvent(), CG_Debriefing_Scrollbar_KeyDown(), CG_Debriefing_Scrollbar_KeyUp(), CG_LimboPanel_NameEditFinish(), CG_LimboPanel_WeaponPanel_KeyDown(), CG_LimboPanel_WeaponPanel_KeyUp(), CG_SpeakerEditor_Broadcast_KeyUp(), CG_SpeakerEditor_Cancel_KeyDown(), CG_SpeakerEditor_Cancel_KeyUp(), CG_SpeakerEditor_Delete_KeyDown(), CG_SpeakerEditor_Delete_KeyUp(), CG_SpeakerEditor_Dropdown_KeyDown(), CG_SpeakerEditor_KeyHandling(), CG_SpeakerEditor_Looped_KeyUp(), CG_SpeakerEditor_Ok_KeyDown(), and CG_SpeakerEditor_Ok_KeyUp().
panel_button_t* BG_PanelButtonsGetHighlightButton (panel_button_t ** buttons)
BG_PanelButtonsGetHighlightButton.
Parameters
[in] buttons
Returns
Definition at line 1716 of file ui_shared.c.
Referenced by CG_LimboPanel_Draw().
qboolean BG_PanelButtonsKeyEvent (int key, qboolean down, panel_button_t ** buttons)
BG_PanelButtonsKeyEvent.
Parameters
[in] key
[in] down
[in] buttons
Returns
Definition at line 1610 of file ui_shared.c.
Referenced by CG_Debriefing_KeyEvent(), CG_DemoClick(), CG_LimboPanel_KeyHandling(), CG_LoadPanel_KeyHandling(), and CG_SpeakerEditor_KeyHandling().
void BG_PanelButtonsRender (panel_button_t ** buttons)
BG_PanelButtonsRender.
Parameters
[in] buttons
Definition at line 1737 of file ui_shared.c.
Referenced by CG_Debriefing_Draw(), CG_DrawConnectScreen(), CG_DrawDemoControls(), CG_Fireteams_Draw(), CG_LimboPanel_Draw(), CG_Spawnpoints_Draw(), CG_SpeakerEditorDraw(), and UI_DrawLoadPanel().
void BG_PanelButtonsRender_Img (panel_button_t * button)
BG_PanelButtonsRender_Img.
Parameters
[in] button
Definition at line 1800 of file ui_shared.c.
void BG_PanelButtonsRender_Text (panel_button_t * button)
BG_PanelButtonsRender_Text.
Parameters
[in] button
Definition at line 1791 of file ui_shared.c.
Referenced by CG_LimboPanelRenderText_NoLMS(), CG_LimboPanelRenderText_SkillsText(), CG_SpeakerEditor_RenderButton(), and UI_LoadPanel_RenderHeaderText().
void BG_PanelButtonsRender_TextExt (panel_button_t * button, const char * text)
BG_PanelButtonsRender_TextExt.
Parameters
[in] button
[in] text
Definition at line 1757 of file ui_shared.c.
Referenced by BG_PanelButtonsRender_Text(), and CG_DebriefingXPHeader_Draw().
void BG_PanelButtonsSetup (panel_button_t ** buttons)
BG_PanelButtonsSetup.
Parameters
[in,out] buttons
Definition at line 1696 of file ui_shared.c.
Referenced by CG_ActivateEditSoundMode(), CG_ChatPanel_Setup(), CG_DrawConnectScreen(), CG_Fireteams_Setup(), CG_LimboPanel_Init(), CG_Spawnpoints_Setup(), and UI_DrawLoadPanel().
qboolean BG_RectContainsPoint (float x, float y, float w, float h, float px, float py)
BG_RectContainsPoint.
Parameters
[in] x
[in] y
[in] w
[in] h
[in] px
[in] py
Returns
Definition at line 1304 of file ui_shared.c.
Referenced by BG_CursorInRect(), CG_CommandCentreSpawnPointClick(), CG_DrawMapEntity(), and CG_DrawSpawnPointInfo().
void C_PanelButtonsSetup (panel_button_t ** buttons, float xoffset)
Adjusting panel coordinates so it is horizontally centered.
Parameters
[in,out] buttons
[in] xoffset
Definition at line 1912 of file ui_shared.c.
Referenced by CG_ChatPanel_Setup(), CG_DrawConnectScreen(), CG_LimboPanel_Init(), and UI_DrawLoadPanel().
qboolean Color_Parse (char ** p, vec4_t * c)
Color_Parse.
Parameters
[in] p
[out] c
Returns
Definition at line 160 of file ui_parse.c.
Referenced by Script_SetItemColor(), and Script_SetMenuItemColor().
void Controls_GetConfig (void)
Controls_GetConfig.
Definition at line 815 of file ui_shared.c.
Referenced by String_Init().
void Controls_SetConfig (qboolean restart)
Controls_SetConfig.
Parameters
[in] restart
Definition at line 830 of file ui_shared.c.
Referenced by Item_Bind_HandleKey(), and UI_RunMenuScript().
void Controls_SetDefaults (qboolean lefthanded)
Controls_SetDefaults.
Parameters
[in] lefthanded
Definition at line 858 of file ui_shared.c.
Referenced by UI_RunMenuScript().
void Cui_WideRect (rectDef_t * rect)
Convert rectangle-coordinates for use with the current aspectratio.
Parameters
[out] rect
Definition at line 78 of file ui_shared.c.
Referenced by Menu_UpdatePosition().
float Cui_WideX (float x)
Convert an x-coordinate for use with the current aspectratio. (if the current aspectratio is 4:3, then leave the x-coordinate unchanged)
Parameters
[in] x
Returns
Definition at line 98 of file ui_shared.c.
Referenced by Rect_ContainsPoint(), and UI_MouseEvent().
float Cui_WideXoffset (void)
The horizontal center of screen pixel-difference of a 4:3 ratio vs. the current aspectratio.
Definition at line 106 of file ui_shared.c.
Referenced by Menu_UpdatePosition(), and UI_DrawLoadPanel().
void Display_CacheAll (void)
Display_CacheAll.
Definition at line 1234 of file ui_shared.c.
Referenced by UI_Cache_f().
void* Display_CaptureItem (int x, int y)
Display_CaptureItem.
Parameters
[in] x
[in] y
Returns
Definition at line 1071 of file ui_shared.c.
Referenced by Display_HandleKey().
void Display_CloseCinematics (void)
Display_CloseCinematics.
Definition at line 665 of file ui_shared.c.
Referenced by Menus_Activate(), Menus_ActivateByName(), and Menus_HandleOOBClick().
int Display_CursorType (int x, int y)
Display_CursorType.
Parameters
[in] x
[in] y
Returns
Note
Unused
Definition at line 1136 of file ui_shared.c.
displayContextDef_t* Display_GetContext (void)
Display_GetContext.
Returns
Note
Unused
Definition at line 1060 of file ui_shared.c.
void Display_HandleKey (int key, qboolean down, int x, int y)
Display_HandleKey.
Parameters
[in] key
[in] down
[in] x
[in] y
Note
Unused
Definition at line 1164 of file ui_shared.c.
qboolean Display_KeyBindPending (void)
Display_KeyBindPending.
Returns
Definition at line 1049 of file ui_shared.c.
Referenced by UI_DrawKeyBindStatus(), and UI_OwnerDrawWidth().
qboolean Display_MouseMove (void * p, int x, int y)
Display_MouseMove.
Parameters
[in,out] p
[in] x
[in] y
Returns
Definition at line 1095 of file ui_shared.c.
Referenced by Menu_HandleKey(), and UI_MouseEvent().
int Display_VisibleMenuCount (void)
Display_VisibleMenuCount.
Returns
Definition at line 679 of file ui_shared.c.
Referenced by Menus_HandleOOBClick().
void Fade (int * flags, float * f, float clamp, int * nextTime, int offsetTime, qboolean bFlags, float fadeAmount)
Fade.
Parameters
[in,out] flags
[in,out] f
[in] clamp
[in,out] nextTime
[in] offsetTime
[in] bFlags
[in] fadeAmount
Definition at line 377 of file ui_shared.c.
Referenced by Item_OwnerDraw_Paint(), Item_TextColor(), and Window_Paint().
qboolean FileExists (const char * filename)
FileExists.
Parameters
filename
Returns
Definition at line 568 of file ui_shared.c.
Referenced by Script_WriteProfile().
qboolean Float_Parse (char ** p, float * f)
Float_Parse.
Parameters
[in] p
[out] f
Returns
Definition at line 138 of file ui_parse.c.
Referenced by Color_Parse(), Rect_Parse(), Script_Orbit(), Script_SetColor(), and Script_Transition().
void Init_Display (displayContextDef_t * dc)
Initializes the display with a structure to all the drawing routines.
Parameters
[in] dc
Definition at line 335 of file ui_shared.c.
Referenced by CG_LoadHudMenu(), and UI_Init().
qboolean Int_Parse (char ** p, int * i)
Int_Parse.
Parameters
[in] p
[out] i
Returns
Definition at line 184 of file ui_parse.c.
Referenced by GameType_Parse(), Script_ConditionalOpen(), Script_ConditionalScript(), Script_ExecWolfConfig(), Script_Orbit(), Script_SetTextStyle(), Script_Transition(), and UI_RunMenuScript().
qboolean IsVisible (int flags)
IsVisible.
Parameters
[in] flags
Returns
Definition at line 558 of file ui_shared.c.
Referenced by Menu_HandleMouseMove().
void Item_Action (itemDef_t * item)
Item_Action.
Parameters
[in] item
Definition at line 2081 of file ui_menuitem.c.
Referenced by Item_KeyboardActivate(), Item_MouseActivate(), and Menu_HandleKey().
qboolean Item_Bind_HandleKey (itemDef_t * item, int key, qboolean down)
Item_Bind_HandleKey.
Parameters
[in] item
[in] key
[in] down
Returns
Definition at line 3093 of file ui_menuitem.c.
Referenced by Item_HandleKey(), and Menu_HandleKey().
qboolean Item_Combo_HandleKey (itemDef_t * item, int key)
Item_Combo_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1564 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_ComboDeSelect (itemDef_t * item)
Item_ComboDeSelect.
Parameters
item - unused
Definition at line 1440 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
rectDef_t* Item_CorrectedTextRect (itemDef_t * item)
Item_CorrectedTextRect.
Parameters
[in] item
Returns
Definition at line 2094 of file ui_menuitem.c.
Referenced by Item_MouseActivate(), Item_Paint(), Menu_HandleMouseMove(), and Menu_OverActiveItem().
qboolean Item_EnableShowViaCvar (itemDef_t * item, int flag)
Item_EnableShowViaCvar.
Parameters
[in] item
[in] flag
Returns
Definition at line 139 of file ui_menuitem.c.
Referenced by Item_MouseEnter(), Item_OwnerDraw_Paint(), Item_Paint(), Item_SetFocus(), Item_TextColor(), Menu_HandleKey(), and Menu_HandleMouseMove().
qboolean Item_HandleKey (itemDef_t * item, int key, qboolean down)
Item_HandleKey.
Parameters
[in] item
[in] key
[in] down
Returns
Definition at line 2409 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_HandleSaveValue (void)
Item_HandleSaveValue.
Definition at line 1504 of file ui_menuitem.c.
Referenced by Item_RunScript(), and Item_TextField_HandleKey().
void Item_HandleTextFieldDeSelect (itemDef_t * item)
Item_HandleTextFieldDeSelect.
Parameters
[in] item
Definition at line 1488 of file ui_menuitem.c.
Referenced by Item_HandleSaveValue(), Item_TextField_HandleKey(), and Menu_HandleKey().
void Item_HandleTextFieldSelect (itemDef_t * item)
Item_HandleTextFieldSelect.
Parameters
[in] item
Definition at line 1475 of file ui_menuitem.c.
Referenced by Item_HandleSaveValue(), Item_KeyboardActivate(), Item_MouseActivate(), and Item_TextField_HandleKey().
void Item_Init (itemDef_t * item)
Item_Init.
Parameters
[in,out] item
Definition at line 3991 of file ui_menuitem.c.
Referenced by Item_ValidateTooltipData(), and MenuParse_itemDef().
void Item_KeyboardActivate (itemDef_t * item)
This gets called on keyboard Enter and KP_Enter.
Parameters
[in] item
Definition at line 3915 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
qboolean Item_ListBox_HandleKey (itemDef_t * item, int key, qboolean down, qboolean force)
Item_ListBox_HandleKey.
Parameters
[in,out] item
[in] key
down - unused
[in] force
Returns
Definition at line 829 of file ui_menuitem.c.
Referenced by Item_HandleKey(), Item_Scroll_ListBox_AutoFunc(), Item_Scroll_ListBox_ThumbFunc(), and Menu_ScrollFeeder().
void Item_MouseActivate (itemDef_t * item)
This gets called on mouse1-3.
Parameters
[in] item
Todo:
: make it set the insertion point correctly
Definition at line 3936 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_MouseEnter (itemDef_t * item, float x, float y)
Item_MouseEnter.
Parameters
[in] item
[in] x
[in] y
Definition at line 697 of file ui_menuitem.c.
Referenced by Menu_HandleMouseMove().
void Item_MouseLeave (itemDef_t * item)
Item_MouseLeave.
Parameters
[in,out] item
Definition at line 770 of file ui_menuitem.c.
Referenced by Menu_ClearFocus(), Menu_HandleMouseMove(), and Menu_ShowItemByName().
void Item_Paint (itemDef_t * item)
Item_Paint.
Parameters
item
Todo:
: should we do something here?
Definition at line 3766 of file ui_menuitem.c.
Referenced by Menu_Paint().
void Item_RunScript (itemDef_t * item, qboolean * bAbort, const char * s)
Item_RunScript.
Parameters
[in] item
[in,out] bAbort
[in] s
Definition at line 1463 of file ui_script.c.
Referenced by Item_Action(), Item_Combo_HandleKey(), Item_HandleKey(), Item_ListBox_HandleKey(), Item_MouseEnter(), Item_MouseLeave(), Item_SetFocus(), Item_TextField_HandleKey(), Menu_ClearFocus(), Menu_HandleKey(), Menu_Paint(), Menu_RunCloseScript(), Menus_Activate(), Script_ConditionalScript(), Script_SetEditFocus(), and Script_SetFocus().
qboolean Item_SetFocus (itemDef_t * item, float x, float y)
Will optionaly set focus to this item.
Parameters
[in] item
[in] x
[in] y
Returns
Definition at line 231 of file ui_menuitem.c.
Referenced by Menu_HandleMouseMove(), Menu_SetNextCursorItem(), and Menu_SetPrevCursorItem().
void Item_SetMouseOver (itemDef_t * item, qboolean focus)
Item_SetMouseOver.
Parameters
[in,out] item
[in] focus
Definition at line 790 of file ui_menuitem.c.
Referenced by Menu_ClearFocus(), Menu_HandleMouseMove(), and Menu_ShowItemByName().
void Item_SetScreenCoords (itemDef_t * item, float x, float y)
Item_SetScreenCoords.
Parameters
[in,out] item
[in] x
[in] y
Todo:
: do the proper thing for the right borders here?
Definition at line 65 of file ui_menuitem.c.
Referenced by Item_SetScreenCoords(), Item_UpdatePosition(), and Menu_UpdatePosition().
qboolean Item_SettingShow (itemDef_t * item, qboolean fVoteTest)
Sisplay if we poll on a server toggle setting We want current settings, so this is a bit of a perf hit, but this is only during UI display.
Parameters
[in] item
[in] fVoteTest
Returns
Definition at line 199 of file ui_menuitem.c.
Referenced by Item_MouseEnter(), Item_Paint(), Item_SetFocus(), and Menu_HandleMouseMove().
void Item_SetupKeywordHash (void)
Item_SetupKeywordHash.
Definition at line 2280 of file ui_parse.c.
Referenced by String_Init().
qboolean Item_TextField_HandleKey (itemDef_t * item, int key)
Item_TextField_HandleKey.
Parameters
[in] item
[in] key
Returns
Definition at line 1595 of file ui_menuitem.c.
Referenced by Menu_HandleKey().
void Item_Tooltip_Initialize (itemDef_t * item)
Item_Tooltip_Initialize.
Parameters
[in,out] item
Definition at line 43 of file ui_menuitem.c.
Referenced by Item_ValidateTooltipData().
void Item_UpdatePosition (itemDef_t * item)
Item_UpdatePosition.
Parameters
[in] item
Todo:
FIXME: consolidate this with nearby stuff
Definition at line 110 of file ui_menuitem.c.
Referenced by Item_DoTransition(), Item_Paint(), Menu_OrbitItemByName(), and Menu_TransitionItemByName().
void LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Lerp and clamp each component of a and b into c by the fraction t.
Parameters
[in] a
[in] b
[in] c
[in] t
Definition at line 311 of file ui_shared.c.
Referenced by Item_Bind_Paint(), Item_CheckBox_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Slider_Paint(), Item_TextColor(), Item_TextField_Paint(), Item_YesNo_Paint(), and UI_DrawServerRefreshDate().
itemDef_t* Menu_ClearFocus (menuDef_t * menu)
Menu_ClearFocus.
Parameters
[in] menu
Returns
Definition at line 411 of file ui_menu.c.
Referenced by Item_SetFocus(), Menus_CloseByName(), Script_ClearFocus(), Script_SetEditFocus(), Script_SetFocus(), and Script_SetMenuFocus().
void Menu_CloseCinematics (menuDef_t * menu)
Menu_CloseCinematics.
Parameters
[in] menu
Definition at line 870 of file ui_menu.c.
Referenced by Display_CloseCinematics().
int Menu_Count (void)
Menu_Count.
Returns
Definition at line 1470 of file ui_menu.c.
Referenced by UI_KeyEvent(), UI_LoadProfiles(), UI_MouseEvent(), UI_Refresh(), and UI_SetActiveMenu().
void Menu_FadeItemByName (menuDef_t * menu, const char * p, qboolean fadeOut)
Menu_FadeItemByName.
Parameters
[in] menu
[in] p
[in] fadeOut
Definition at line 609 of file ui_menu.c.
Referenced by Script_FadeIn(), and Script_FadeOut().
void Menu_FadeMenuByName (const char * p, qboolean * bAbort, qboolean fadeOut)
Menu_FadeMenuByName.
Parameters
[in] p
bAbort - unused
[in] fadeOut
Definition at line 45 of file ui_menu.c.
Referenced by Script_FadeInMenu(), and Script_FadeOutMenu().
itemDef_t* Menu_FindItemByName (menuDef_t * menu, const char * p)
Menu_FindItemByName.
Parameters
[in] menu
[in] p
Returns
Definition at line 541 of file ui_menu.c.
Referenced by Script_AddListItem(), Script_SetEditFocus(), and Script_SetFocus().
menuDef_t* Menu_Get (int handle)
Menu_Get.
Parameters
[in] handle
Returns
Definition at line 1480 of file ui_menu.c.
Referenced by UI_LoadProfiles().
menuDef_t* Menu_GetFocused (void)
Menu_GetFocused.
Returns
Definition at line 179 of file ui_menu.c.
Referenced by Display_HandleKey(), Display_MouseMove(), Menu_SetFeederSelection(), Menus_ActivateByName(), UI_CheckExecKey(), UI_KeyEvent(), and UI_Load().
itemDef_t* Menu_GetMatchingItemByNumber (menuDef_t * menu, int index, const char * name)
Menu_GetMatchingItemByNumber.
Parameters
[in] menu
[in] index
[in] name
Returns
Definition at line 494 of file ui_menu.c.
Referenced by Menu_FadeItemByName(), Menu_OrbitItemByName(), Menu_ShowItemByName(), Menu_TransitionItemByName(), Script_SetItemColor(), Script_SetMenuItemColor(), and Script_SetTextStyle().
void Menu_HandleKey (menuDef_t * menu, int key, qboolean down)
Menu_HandleKey.
Parameters
[in] menu
[in] key
[in] down
Definition at line 992 of file ui_menu.c.
Referenced by Display_HandleKey(), Menus_HandleOOBClick(), and UI_KeyEvent().
void Menu_HandleMouseMove (menuDef_t * menu, float x, float y)
Menu_HandleMouseMove.
Parameters
[in] menu
[in] x
[in] y
Todo:
: this is the whole issue of focus vs. mouse over..
Definition at line 1205 of file ui_menu.c.
Referenced by Display_MouseMove(), Menu_HandleKey(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), and Menus_HandleOOBClick().
void Menu_Init (menuDef_t * menu)
Menu_Init.
Parameters
[in] menu
Definition at line 140 of file ui_menu.c.
Referenced by Menu_New().
int Menu_ItemsMatchingGroup (menuDef_t * menu, const char * name)
Menu_ItemsMatchingGroup.
Parameters
[in] menu
[in] name
Returns
Definition at line 453 of file ui_menu.c.
Referenced by Menu_FadeItemByName(), Menu_OrbitItemByName(), Menu_ShowItemByName(), Menu_TransitionItemByName(), Script_SetItemColor(), Script_SetMenuItemColor(), and Script_SetTextStyle().
void Menu_New (int handle)
Menu_New.
Parameters
[in] handle
Definition at line 1451 of file ui_menu.c.
Referenced by UI_ParseMenu().
void Menu_OrbitItemByName (menuDef_t * menu, const char * p, float x, float y, float cx, float cy, int time)
Menu_OrbitItemByName.
Parameters
[in] menu
[in] p
[in] x
[in] y
[in] cx
[in] cy
[in] time
Definition at line 114 of file ui_menu.c.
Referenced by Script_Orbit().
qboolean Menu_OverActiveItem (menuDef_t * menu, float x, float y)
Menu_OverActiveItem.
Parameters
[in] menu
[in] x
[in] y
Returns
Definition at line 1507 of file ui_menu.c.
Referenced by Menus_HandleOOBClick().
void Menu_Paint (menuDef_t * menu, qboolean forcePaint)
Menu_Paint.
Parameters
[in] menu
[in] forcePaint
Todo:
: make sure we have a default shader if fullscreen is set with no background
Definition at line 1319 of file ui_menu.c.
Referenced by Menu_PaintAll().
void Menu_PaintAll (void)
Menu_PaintAll.
Definition at line 1412 of file ui_menu.c.
Referenced by CG_Draw2D(), and UI_Refresh().
qboolean Menu_Parse (int handle, menuDef_t * menu)
Menu_Parse.
Parameters
[in] handle
[in] menu
Returns
Definition at line 3147 of file ui_parse.c.
Referenced by Menu_New().
void Menu_PostParse (menuDef_t * menu)
Menu_PostParse.
Parameters
[in,out] menu
Definition at line 390 of file ui_menu.c.
Referenced by Menu_New().
void Menu_Reset (void)
Menu_Reset.
Definition at line 1495 of file ui_menu.c.
Referenced by CG_LoadHudMenu(), and UI_LoadMenus().
void Menu_RunCloseScript (menuDef_t * menu)
Menu_RunCloseScript.
Parameters
[in] menu
Definition at line 682 of file ui_menu.c.
Referenced by Menus_CloseAll(), Menus_CloseByName(), Menus_HandleOOBClick(), and Script_CloseAllOtherMenus().
void Menu_ScrollFeeder (menuDef_t * menu, int feeder, qboolean down)
Menu_ScrollFeeder.
Parameters
[in] menu
[in] feeder
[in] down
Note
Unused
Definition at line 201 of file ui_menu.c.
void Menu_SetFeederSelection (menuDef_t * menu, int feeder, int index, const char * name)
Menu_SetFeederSelection.
Parameters
[in,out] menu
[in] feeder
[in] index
[in] name
Definition at line 225 of file ui_menu.c.
Referenced by UI_BuildServerDisplayList(), UI_BuildServerStatus(), UI_GameType_HandleKey(), UI_LoadProfiles(), UI_RunMenuScript(), and UI_SetActiveMenu().
itemDef_t* Menu_SetNextCursorItem (menuDef_t * menu)
Menu_SetNextCursorItem.
Parameters
[in,out] menu
Returns
Definition at line 821 of file ui_menu.c.
Referenced by Item_TextField_HandleKey(), and Menu_HandleKey().
itemDef_t* Menu_SetPrevCursorItem (menuDef_t * menu)
Menu_SetPrevCursorItem.
Parameters
[in,out] menu
Returns
Definition at line 779 of file ui_menu.c.
Referenced by Item_TextField_HandleKey(), and Menu_HandleKey().
void Menu_SetupKeywordHash (void)
Menu_SetupKeywordHash.
Definition at line 3130 of file ui_parse.c.
Referenced by String_Init().
void Menu_ShowItemByName (menuDef_t * menu, const char * p, qboolean bShow)
Menu_ShowItemByName.
Parameters
[in] menu
[in] p
[in] bShow
Definition at line 567 of file ui_menu.c.
void Menu_TransitionItemByName (menuDef_t * menu, const char * p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt)
Menu_TransitionItemByName.
Parameters
[in] menu
[in] p
[in] rectFrom
[in] rectTo
[in] time
[in] amt
Definition at line 80 of file ui_menu.c.
Referenced by Script_Transition().
void Menu_UpdatePosition (menuDef_t * menu)
Menu_UpdatePosition.
Parameters
[in] menu
Definition at line 321 of file ui_menu.c.
Referenced by Display_MouseMove(), Item_ListBox_HandleKey(), and Menu_PostParse().
void Menus_Activate (menuDef_t * menu)
Menus_Activate.
Parameters
[in,out] menu
Definition at line 892 of file ui_menu.c.
Referenced by Menus_ActivateByName(), and Menus_ShowByName().
menuDef_t* Menus_ActivateByName (const char * p, qboolean modalStack)
Menus_ActivateByName.
Parameters
[in] p
[in] modalStack
Returns
Definition at line 286 of file ui_menu.c.
Referenced by Item_ListBox_HandleKey(), Menus_CloseByName(), Menus_OpenByName(), UI_Load(), UI_RunMenuScript(), and UI_SetActiveMenu().
qboolean Menus_AnyFullScreenVisible (void)
Menus_AnyFullScreenVisible.
Returns
Definition at line 266 of file ui_menu.c.
Referenced by _UI_IsFullscreen().
qboolean Menus_CaptureFuncActive (void)
Menus_CaptureFuncActive.
Returns
Definition at line 927 of file ui_menu.c.
Referenced by UI_FeederSelectionClick().
void Menus_CloseAll (void)
Menus_CloseAll.
Definition at line 741 of file ui_menu.c.
Referenced by Script_CloseAll(), UI_Init(), UI_Load(), UI_RunMenuScript(), and UI_SetActiveMenu().
void Menus_CloseByName (const char * p)
Menus_CloseByName.
Parameters
[in] p
Definition at line 697 of file ui_menu.c.
Referenced by CG_DrawTimedMenus(), Script_Close(), and UI_RunMenuScript().
menuDef_t* Menus_FindByName (const char * p)
Menus_FindByName.
Parameters
[in] p
Returns
Definition at line 639 of file ui_menu.c.
Referenced by Item_ListBox_HandleKey(), Menu_FadeMenuByName(), Menu_SetFeederSelection(), Menus_CloseByName(), Menus_ShowByName(), Script_SetMenuFocus(), Script_SetMenuItemColor(), UI_BuildServerStatus(), UI_GetServerStatusInfo(), and UI_RunMenuScript().
void Menus_OpenByName (const char * p)
Menus_OpenByName.
Parameters
[in] p
Definition at line 673 of file ui_menu.c.
Referenced by Script_ConditionalOpen(), Script_Open(), UI_ConsoleCommand(), UI_RunMenuScript(), and UI_SetActiveMenu().
void Menus_ShowByName (const char * p)
Menus_ShowByName.
Parameters
[in] p
Note
Unused
Definition at line 659 of file ui_menu.c.
qboolean PC_Char_Parse (int handle, char * out)
PC_Char_Parse.
Parameters
[in] handle
[out] out
Returns
Definition at line 273 of file ui_parse.c.
Referenced by ItemParse_execKey(), and MenuParse_execKey().
qboolean PC_Color_Parse (int handle, vec4_t * c)
PC_Color_Parse.
Parameters
[in] handle
[out] c
Returns
Definition at line 4283 of file bg_misc.c.
Referenced by Asset_Parse(), ItemParse_outlinecolor(), MenuParse_outlinecolor(), and ParseColorRange().
qboolean PC_Float_Parse (int handle, float * f)
PC_Float_Parse.
Parameters
[in] handle
[out] f
Returns
Definition at line 4244 of file bg_misc.c.
Referenced by Asset_Parse(), CG_RectParse(), CG_RW_ParseClient(), ItemParse_backcolor(), ItemParse_bordercolor(), ItemParse_bordersize(), ItemParse_cvarFloat(), ItemParse_cvarFloatList(), ItemParse_elementheight(), ItemParse_elementwidth(), ItemParse_forecolor(), ItemParse_model_fovx(), ItemParse_model_fovy(), ItemParse_model_origin(), ItemParse_scrollColor(), ItemParse_sliderColor(), ItemParse_textalignx(), ItemParse_textaligny(), ItemParse_textscale(), ItemParse_tooltipalignx(), ItemParse_tooltipaligny(), MenuParse_backcolor(), MenuParse_bordercolor(), MenuParse_borderSize(), MenuParse_disablecolor(), MenuParse_fadeAmount(), MenuParse_fadeClamp(), MenuParse_focuscolor(), MenuParse_forecolor(), ParseColorRange(), PC_Color_Parse(), PC_Point_Parse(), PC_Rect_Parse(), PC_Vec_Parse(), and UI_LoadArenasFromFile().
qboolean PC_Int_Parse (int handle, int * i)
PC_Int_Parse.
Parameters
[in] handle
[out] i
Returns
Definition at line 4349 of file bg_misc.c.
Referenced by Asset_Parse(), BG_RAG_ParseAnimation(), BG_SS_ParseSpeaker(), CG_FindArenaInfo(), CG_LoadObjectiveData(), CG_ParseHUD(), CG_ParseHudComponent(), CG_RW_ParseClient(), CG_RW_ParseModModel(), CG_RW_ParseWeaponLinkPart(), ItemParse_align(), ItemParse_bitflag(), ItemParse_border(), ItemParse_columns(), ItemParse_elementtype(), ItemParse_feeder(), ItemParse_maxChars(), ItemParse_maxPaintChars(), ItemParse_model_angle(), ItemParse_model_animplay(), ItemParse_model_rotation(), ItemParse_origin(), ItemParse_ownerdraw(), ItemParse_ownerdrawFlag(), ItemParse_settingDisabled(), ItemParse_settingEnabled(), ItemParse_special(), ItemParse_style(), ItemParse_textalign(), ItemParse_textfont(), ItemParse_textstyle(), ItemParse_type(), ItemParse_visible(), ItemParse_voteFlag(), MenuParse_border(), MenuParse_execKeyInt(), MenuParse_fadeCycle(), MenuParse_fullscreen(), MenuParse_itemHotkeyMode(), MenuParse_onTimeout(), MenuParse_ownerdraw(), MenuParse_ownerdrawFlag(), MenuParse_style(), MenuParse_visible(), and UI_LoadArenasFromFile().
qboolean PC_Rect_Parse (int handle, rectDef_t * r)
PC_Rect_Parse.
Parameters
[in] handle
[in] r
Returns
Definition at line 1271 of file ui_shared.c.
Referenced by ItemParse_rect(), and MenuParse_rect().
qboolean PC_Script_Parse (int handle, const char ** out)
PC_Script_Parse.
Parameters
[in] handle
[out] out
Returns
Definition at line 292 of file ui_parse.c.
Referenced by ItemParse_accept(), ItemParse_action(), ItemParse_disableCvar(), ItemParse_doubleClick(), ItemParse_enableCvar(), ItemParse_execKey(), ItemParse_hideCvar(), ItemParse_leaveFocus(), ItemParse_mouseEnter(), ItemParse_mouseEnterText(), ItemParse_mouseExit(), ItemParse_mouseExitText(), ItemParse_onEnter(), ItemParse_onEsc(), ItemParse_onFocus(), ItemParse_onPaste(), ItemParse_onTab(), ItemParse_showCvar(), MenuParse_execKey(), MenuParse_execKeyInt(), MenuParse_onClose(), MenuParse_onEnter(), MenuParse_onESC(), MenuParse_onOpen(), MenuParse_onPaste(), and MenuParse_onTimeout().
void PC_SourceError (int handle, const char * format, ...)
PC_SourceError.
Parameters
[in] handle
[in] format
Definition at line 4216 of file bg_misc.c.
Referenced by Item_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), Menu_Parse(), ParseColorRange(), PC_Float_Parse(), and PC_Int_Parse().
qboolean PC_String_Parse (int handle, const char ** out)
PC_String_Parse.
Parameters
[in] handle
[out] out
Returns
Definition at line 4407 of file bg_misc.c.
Referenced by Asset_Parse(), CG_FindArenaInfo(), G_LoadCampaignsFromFile(), ItemParse_asset_model(), ItemParse_asset_shader(), ItemParse_background(), ItemParse_cinematic(), ItemParse_contextMenu(), ItemParse_cvar(), ItemParse_cvarFloat(), ItemParse_cvarTest(), ItemParse_focusSound(), ItemParse_group(), ItemParse_name(), MenuParse_background(), MenuParse_cinematic(), MenuParse_name(), MenuParse_soundLoop(), PC_Int_Parse(), UI_LoadArenasFromFile(), and UI_LoadCampaignsFromFile().
qboolean Rect_ContainsPoint (rectDef_t * rect, float x, float y)
Rect_ContainsPoint.
Parameters
[in] rect
[in] x
[in] y
Returns
Definition at line 613 of file ui_shared.c.
Referenced by Display_CaptureItem(), Display_CursorType(), Item_Bind_HandleKey(), Item_CheckBox_HandleKey(), Item_Combo_Paint(), Item_ListBox_HandleKey(), Item_ListBox_OverLB(), Item_MouseActivate(), Item_MouseEnter(), Item_Multi_HandleKey(), Item_SetFocus(), Item_Slider_HandleKey(), Item_Slider_OverSlider(), Item_YesNo_HandleKey(), Menu_HandleKey(), Menu_HandleMouseMove(), and Menu_OverActiveItem().
qboolean Rect_ContainsPointN (rectDef_t * rect, float x, float y)
Rect_ContainsPointN.
Parameters
[in] rect
[in] x
[in] y
Returns
Definition at line 636 of file ui_shared.c.
Referenced by Item_ListBox_MouseEnter().
qboolean Rect_Parse (char ** p, rectDef_t * r)
Rect_Parse.
Parameters
[in] p
[in] r
Returns
Definition at line 207 of file ui_parse.c.
Referenced by Script_Transition().
qboolean Script_Parse (char ** p, const char ** out)
const char* String_Alloc (const char * p)
String_Alloc.
Parameters
[in] p
Returns
Definition at line 197 of file ui_shared.c.
void String_Init (void)
String_Init.
Definition at line 283 of file ui_shared.c.
Referenced by CG_Init(), UI_Init(), and UI_Load().
qboolean String_Parse (char ** p, const char ** out)
String_Parse.
Parameters
[in] p
[out] out
Returns
Definition at line 232 of file ui_parse.c.
Referenced by GameType_Parse(), Item_EnableShowViaCvar(), Item_RunScript(), Script_AddListItem(), Script_ClearCvar(), Script_Close(), Script_ConditionalOpen(), Script_ConditionalScript(), Script_CopyCvar(), Script_Exec(), Script_ExecNOW(), Script_FadeIn(), Script_FadeInMenu(), Script_FadeOut(), Script_FadeOutMenu(), Script_GetClipboard(), Script_Hide(), Script_Open(), Script_Orbit(), Script_Play(), Script_playLooped(), Script_SetBackground(), Script_SetColor(), Script_SetCvar(), Script_SetEditFocus(), Script_SetFocus(), Script_SetItemColor(), Script_SetMenuFocus(), Script_SetMenuItemColor(), Script_SetPlayerHead(), Script_SetPlayerModel(), Script_SetTextStyle(), Script_Show(), Script_ToggleCvarBit(), Script_Transition(), and UI_RunMenuScript().
void String_Report (void)
String_Report.
Definition at line 264 of file ui_shared.c.
Referenced by UI_Report().
void ToWindowCoords (float * x, float * y, windowDef_t * window)
ToWindowCoords.
Parameters
[out] x
[out] y
[in] window
Definition at line 700 of file ui_shared.c.
Referenced by Item_SetTextExtents(), and Item_Text_AutoWrapped_Paint().
int trap_PC_AddGlobalDefine (char * define)
trap_PC_AddGlobalDefine
Parameters
[in] define
Returns
Parameters
define - unused
Returns
Note
Empty function return 0
Definition at line 1349 of file cg_syscalls.c.
Referenced by UI_LoadMenus().
int trap_PC_FreeSource (int handle)
trap_PC_FreeSource
Parameters
[in] handle
Returns
Definition at line 1369 of file cg_syscalls.c.
Referenced by BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_PCF_ParseError(), BG_R_RegisterAnimationGroup(), BG_RAG_ParseError(), BG_SS_ParseError(), CG_execFile(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_HUD_ParseError(), CG_LoadObjectiveData(), CG_ReadHudFile(), CG_RegisterWeaponFromWeaponFile(), CG_RW_ParseError(), G_ConfigError(), G_configLoadAndSet(), G_LoadCampaignsFromFile(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadProfiles(), and UI_ParseMenu().
int trap_PC_LoadSource (const char * filename)
trap_PC_LoadSource
Parameters
[in] filename
Returns
Definition at line 1359 of file cg_syscalls.c.
Referenced by BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_R_RegisterAnimationGroup(), CG_execFile(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_LoadObjectiveData(), CG_ReadHudFile(), CG_RegisterWeaponFromWeaponFile(), G_configLoadAndSet(), G_LoadCampaignsFromFile(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadProfiles(), and UI_ParseMenu().
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
trap_PC_ReadToken
Parameters
[in] handle
[out] pc_token
Returns
Parameters
handle
pc_token
Returns
Definition at line 1380 of file cg_syscalls.c.
Referenced by Asset_Parse(), BG_LoadSpeakerScript(), BG_ParseCharacterFile(), BG_R_RegisterAnimationGroup(), BG_RAG_ParseAnimFile(), BG_SS_ParseSpeaker(), CG_FindArenaInfo(), CG_FindCampaignInFile(), CG_LoadObjectiveData(), CG_ParseHUD(), CG_ReadHudFile(), CG_RegisterWeaponFromWeaponFile(), CG_RW_ParseClient(), CG_RW_ParseImpactMark(), CG_RW_ParseSoundSurface(), CG_RW_ParseViewType(), CG_RW_ParseWeaponLink(), CG_RW_ParseWeaponLinkPart(), CG_RW_ParseWeaponSound(), G_configLoadAndSet(), G_LoadCampaignsFromFile(), G_ParseMapSettings(), G_ParseSettings(), Item_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarListUndefined(), ItemParse_cvarStrList(), ItemParse_textfile(), Load_Menu(), Menu_Parse(), PC_Char_Parse(), PC_Float_Parse(), PC_Int_Parse(), PC_Script_Parse(), PC_String_Parse(), PC_String_ParseNoAlloc(), PC_String_ParseTranslate(), UI_LoadArenasFromFile(), UI_LoadCampaignsFromFile(), UI_LoadMenus(), UI_LoadProfiles(), and UI_ParseMenu().
int trap_PC_RemoveAllGlobalDefines (void)
trap_PC_RemoveAllGlobalDefines
Returns
Definition at line 960 of file ui_syscalls.c.
Referenced by UI_Init().
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
trap_PC_SourceFileAndLine
Parameters
[in] handle
[out] filename
[out] line
Returns
Parameters
[in] handle
[in] filename
[in] line
Returns
Definition at line 1392 of file cg_syscalls.c.
Referenced by BG_PCF_ParseError(), BG_RAG_ParseError(), BG_SS_ParseError(), CG_HUD_ParseError(), CG_RW_ParseError(), G_ConfigError(), and PC_SourceError().
int trap_PC_UnReadToken (int handle)
trap_PC_UnReadToken
Parameters
[in] handle
Returns
Definition at line 1402 of file cg_syscalls.c.
void* UI_Alloc (int size)
UI_Alloc.
Parameters
[in] size
Returns
Definition at line 116 of file ui_shared.c.
Referenced by Item_ValidateTooltipData(), Item_ValidateTypeData(), MenuParse_itemDef(), and String_Alloc().
void UI_InitMemory (void)
UI_InitMemory.
Definition at line 141 of file ui_shared.c.
Referenced by String_Init(), and UI_Init().
qboolean UI_OutOfMemory (void)
UI_OutOfMemory.
Returns
Definition at line 151 of file ui_shared.c.
Referenced by UI_LoadCampaigns().
void Window_CloseCinematic (windowDef_t * window)
Window_CloseCinematic.
Parameters
[in,out] window
Definition at line 653 of file ui_shared.c.
Referenced by Menu_CloseCinematics().
void Window_Init (Window * w)
Initializes a window structure (windowDef_t) with defaults.
Parameters
[in,out] w
Definition at line 359 of file ui_shared.c.
Referenced by Item_Init(), and Menu_Init().
void Window_Paint (Window * w, float fadeAmount, float fadeClamp, float fadeCycle)
Window_Paint.
Parameters
[in,out] w
[in] fadeAmount
[in] fadeClamp
[in] fadeCycle
Todo:
: do right thing for right border type
Definition at line 415 of file ui_shared.c.
Referenced by Item_Paint(), and Menu_Paint().