ET: Legacy: src/qcommon/update.c File Reference
update.c File Reference
#include "../client/client.h"
Macros
#define upd cls.download
#define gamebin "etl"
#define UPDATE_BINARY "updater"
#define GAME_BINARY gamebin
#define CMDP "'"
#define UPDATE_PACKAGE "updater.zip"
#define UPDATE_CONFIG "updater.xml"
#define MIN_PACK_LEN 4
Functions
void Com_CheckAutoUpdate (void)
Com_CheckAutoUpdate.
void Com_GetAutoUpdate (void)
Com_GetAutoUpdate.
static void Com_RunUpdateBinary (const char *updateBinary, const char *updateConfig)
Com_RunUpdateBinary.
static qboolean Com_UnpackUpdatePackage (const char *pack, const char *bin, const char *config)
Com_UnpackUpdatePackage.
static void Com_CLeanUpdateFolder (const char *bin)
Com_CLeanUpdateFolder.
qboolean Com_CheckUpdateDownloads (void)
Com_CheckUpdateDownloads.
qboolean Com_InitUpdateDownloads (void)
Com_InitUpdateDownloads.
qboolean Com_UpdatePacketEvent (netadr_t from)
Com_UpdatePacketEvent.
void Com_UpdateInfoPacket (netadr_t from)
Com_UpdateInfoPacket.
void Com_CheckUpdateStarted (void)
Com_CheckUpdateStarted.
void Com_UpdateVarsClean (int flags)
Com_UpdateVarsClean.
void Com_Update_f (void)
Com_Update_f.
Variables
autoupdate_t autoupdate
Macro Definition Documentation
#define CMDP "'"
Definition at line 52 of file update.c.
Referenced by Com_RunUpdateBinary().
#define GAME_BINARY gamebin
Definition at line 51 of file update.c.
Referenced by Com_RunUpdateBinary().
#define gamebin "etl"
Definition at line 42 of file update.c.
#define MIN_PACK_LEN 4
Definition at line 56 of file update.c.
Referenced by Com_CheckUpdateDownloads(), Com_GetAutoUpdate(), and Com_InitUpdateDownloads().
#define upd cls.download
Definition at line 41 of file update.c.
Referenced by Com_CheckUpdateDownloads(), Com_InitUpdateDownloads(), and Com_RunUpdateBinary().
#define UPDATE_BINARY "updater"
Definition at line 50 of file update.c.
Referenced by Com_CheckUpdateDownloads().
#define UPDATE_CONFIG "updater.xml"
Definition at line 55 of file update.c.
Referenced by Com_CheckUpdateDownloads().
#define UPDATE_PACKAGE "updater.zip"
Definition at line 54 of file update.c.
Referenced by Com_CheckUpdateDownloads(), and Com_InitUpdateDownloads().
Function Documentation
void Com_CheckAutoUpdate (void)
Com_CheckAutoUpdate.
Definition at line 63 of file update.c.
Referenced by CL_RequestMasterData(), and Com_Update_f().
qboolean Com_CheckUpdateDownloads (void)
Com_CheckUpdateDownloads.
Returns
Definition at line 316 of file update.c.
Referenced by Com_DownloadsComplete().
void Com_CheckUpdateStarted (void)
Com_CheckUpdateStarted.
Definition at line 526 of file update.c.
Referenced by CL_ConnectionlessPacket(), and Com_GetAutoUpdate().
static void Com_CLeanUpdateFolder (const char * bin) static
Com_CLeanUpdateFolder.
Parameters
[in] bin
Definition at line 300 of file update.c.
Referenced by Com_CheckUpdateDownloads().
void Com_GetAutoUpdate (void)
Com_GetAutoUpdate.
Todo:
: this should be saved & restored after update
Definition at line 113 of file update.c.
Referenced by CL_UISystemCalls(), Com_Error(), Com_Update_f(), and Com_UpdateInfoPacket().
qboolean Com_InitUpdateDownloads (void)
Com_InitUpdateDownloads.
Returns
Todo:
: add file size, so UI can show progress bar
Todo:
: never executed
Definition at line 358 of file update.c.
Referenced by Com_InitDownloads().
static void Com_RunUpdateBinary (const char * updateBinary, const char * updateConfig) static
Com_RunUpdateBinary.
Parameters
[in] updateBinary
[in] updateConfig
Definition at line 211 of file update.c.
Referenced by Com_CheckUpdateDownloads().
static qboolean Com_UnpackUpdatePackage (const char * pack, const char * bin, const char * config) static
Com_UnpackUpdatePackage.
Parameters
[in] pack
[in] bin
[in] config
Returns
Definition at line 267 of file update.c.
Referenced by Com_CheckUpdateDownloads().
void Com_Update_f (void)
Com_Update_f.
Definition at line 569 of file update.c.
Referenced by Com_Init().
void Com_UpdateInfoPacket (netadr_t from)
Com_UpdateInfoPacket.
Parameters
[in] from
Definition at line 463 of file update.c.
Referenced by CL_ConnectionlessPacket(), and SV_ConnectionlessPacket().
qboolean Com_UpdatePacketEvent (netadr_t from)
Com_UpdatePacketEvent.
Parameters
[in] from
Returns
Definition at line 440 of file update.c.
Referenced by CL_PacketEvent().
void Com_UpdateVarsClean (int flags)
Com_UpdateVarsClean.
Parameters
[in] flags
Definition at line 548 of file update.c.
Referenced by CL_Disconnect(), CL_UI_Restart_f(), CL_Vid_Restart_f(), and Com_Init().
Variable Documentation
autoupdate_t autoupdate
Definition at line 58 of file update.c.
Referenced by CL_ConnectionlessPacket(), CL_MotdPacket(), CL_RequestMasterData(), CL_RequestMotd(), and Com_WWWDownload().