ET: Legacy: src/qcommon/vm.c File Reference
vm.c File Reference
Virtual machine intermix code and data symbol table.
#include "vm_local.h"
#include "../sys/sys_local.h"
Macros
#define MAX_VM 3
#define STACK_SIZE 0x20000
Functions
void VM_VmInfo_f (void)
VM_VmInfo_f.
void VM_VmProfile_f (void)
VM_VmProfile_f.
void * VM_VM2C (vmptr_t p, int length)
Converts a VM pointer to a C pointer and checks to make sure that the range is acceptable.
void VM_Debug (int level)
VM_Debug.
void VM_Init (void)
VM_Init.
const char * VM_ValueToSymbol (vm_t *vm, int value)
Assumes a program counter value.
int VM_SymbolToValue (vm_t *vm, const char *symbol)
VM_SymbolToValue.
int ParseHex (const char *text)
ParseHex.
void VM_LoadSymbols (vm_t *vm)
VM_LoadSymbols.
intptr_t QDECL VM_DllSyscall (intptr_t arg,...)
Dlls will call this directly.
vm_t * VM_Restart (vm_t *vm)
Reload the data, but leave everything else in place This allows a server to do a map_restart without changing memory allocation.
vm_t * VM_Create (const char *module, qboolean extract, intptr_t(*systemCalls)(intptr_t *), vmInterpret_t interpret)
If image ends in .qvm it will be interpreted, otherwise it will attempt to load as a system dll.
void VM_Free (vm_t *vm)
VM_Free.
void VM_Clear (void)
VM_Clear.
void * VM_ArgPtr (intptr_t intValue)
VM_ArgPtr.
void * VM_ExplicitArgPtr (vm_t *vm, intptr_t intValue)
VM_ExplicitArgPtr.
intptr_t QDECL VM_CallFunc (vm_t *vm, int callNum,...)
VM_CallFunc.
static int QDECL VM_ProfileSort (const void *a, const void *b)
VM_ProfileSort.
void VM_LogSyscalls (int *args)
Insert calls to this while debugging the vm compiler.
Variables
vm_t * currentVM = NULL
vm_t * lastVM = NULL
int vm_debugLevel
vm_t vmTable [MAX_VM]
const char * vmStrs [MAX_VM]
Detailed Description
Virtual machine intermix code and data symbol table.
A dll has one imported function: VM_SystemCall and one exported function: Perform
Definition in file vm.c.
Macro Definition Documentation
#define MAX_VM 3
Definition at line 46 of file vm.c.
Referenced by VM_Clear(), VM_Create(), and VM_VmInfo_f().
#define STACK_SIZE 0x20000
Definition at line 442 of file vm.c.
Referenced by VM_Create().
Function Documentation
int ParseHex (const char * text)
ParseHex.
Parameters
[in] text
Returns
Note
Unused
Definition at line 180 of file vm.c.
Referenced by VM_LoadSymbols().
void* VM_ArgPtr (intptr_t intValue)
VM_ArgPtr.
Parameters
[in] intValue
Returns
Definition at line 644 of file vm.c.
intptr_t QDECL VM_CallFunc (vm_t * vm, int callNum, ...)
VM_CallFunc.
Upon a system call, the stack will look like:
sp+32 parm1 sp+28 parm0 sp+24 return value sp+20 return address sp+16 local1 sp+14 local0 sp+12 arg1 sp+8 arg0 sp+4 return stack sp return address
An interpreted function will immediately execute an OP_ENTER instruction, which will subtract space for locals from sp
Parameters
[in] vm
[in] callNum
Returns
Definition at line 717 of file vm.c.
void VM_Clear (void)
VM_Clear.
Definition at line 623 of file vm.c.
Referenced by Hunk_Clear().
vm_t* VM_Create (const char * module, qboolean extract, intptr_t(*)(intptr_t *) systemCalls, vmInterpret_t interpret)
If image ends in .qvm it will be interpreted, otherwise it will attempt to load as a system dll.
Parameters
[in] module
[in] extract
systemCalls
[in] interpret
Returns
Definition at line 453 of file vm.c.
Referenced by CL_InitCGame(), CL_InitUI(), SV_InitGameProgs(), and VM_Restart().
void VM_Debug (int level)
VM_Debug.
Parameters
[in] level
Definition at line 77 of file vm.c.
Referenced by CL_CGameRendering(), and VM_CallInterpreted().
intptr_t QDECL VM_DllSyscall (intptr_t arg, ...)
Dlls will call this directly.
cg010206 The horror; the horror.
The syscall mechanism relies on stack manipulation to get it's args. This is likely due to C's inability to pass "..." parameters to a function in one clean chunk. On PowerPC Linux, these parameters are not necessarily passed on the stack, so while (&arg[0] == arg) is true, (&arg[1] == 2nd function parameter) is not necessarily accurate, as arg's value might have been stored to the stack or other piece of scratch memory to give it a valid address, but the next parameter might still be sitting in a register.
Quake's syscall system also assumes that the stack grows downward, and that any needed types can be squeezed, safely, into a signed int.
This hack below copies all needed values for an argument to a array in memory, so that Quake can get the correct values. This can also be used on systems where the stack grows upwards, as the presumably standard and safe stdargs.h macros are used.
As for having enough space in a signed int for your datatypes, well, it might be better to wait for DOOM 3 before you start porting. :)
The original code, while probably still inherently dangerous, seems to work well enough for the platforms it already works on. Rather than add the performance hit for those platforms, the original code is still in use there.
For speed, we just grab 15 arguments, and don't worry about exactly how many the syscall actually needs; the extra is thrown away.
Parameters
[in] arg
Returns
Definition at line 339 of file vm.c.
Referenced by VM_Create().
void* VM_ExplicitArgPtr (vm_t * vm, intptr_t intValue)
VM_ExplicitArgPtr.
Parameters
[in] vm
[in] intValue
Returns
Definition at line 672 of file vm.c.
Referenced by SV_DirectConnect(), SV_MapRestart_f(), and SV_SpawnServer().
void VM_Free (vm_t * vm)
VM_Free.
Parameters
[in,out] vm
Definition at line 593 of file vm.c.
Referenced by CL_ShutdownCGame(), CL_ShutdownUI(), SV_ShutdownGameProgs(), VM_Create(), and VM_Restart().
void VM_Init (void)
VM_Init.
Todo:
: doesn't print anything with +set developer 1
Definition at line 85 of file vm.c.
Referenced by Com_Init().
void VM_LoadSymbols (vm_t * vm)
VM_LoadSymbols.
Parameters
[in,out] vm
Note
Unused
Definition at line 212 of file vm.c.
Referenced by VM_Create().
void VM_LogSyscalls (int * args)
Insert calls to this while debugging the vm compiler.
Parameters
args
Definition at line 898 of file vm.c.
static int QDECL VM_ProfileSort (const void * a, const void * b) static
VM_ProfileSort.
Parameters
[in] a
[in] b
Returns
Definition at line 790 of file vm.c.
Referenced by VM_VmProfile_f().
vm_t* VM_Restart (vm_t * vm)
Reload the data, but leave everything else in place This allows a server to do a map_restart without changing memory allocation.
Parameters
[in,out] vm
Returns
Todo:
: Division of result of sizeof() on pointer type. This seems suspect.
Definition at line 368 of file vm.c.
Referenced by SV_RestartGameProgs().
int VM_SymbolToValue (vm_t * vm, const char * symbol)
VM_SymbolToValue.
Parameters
[in,out] vm
[in] symbol
Returns
Note
Unused
Definition at line 159 of file vm.c.
const char* VM_ValueToSymbol (vm_t * vm, int value)
Assumes a program counter value.
Parameters
[in,out] vm
[in] value
Returns
Definition at line 99 of file vm.c.
Referenced by VM_CallInterpreted(), and VM_Indent().
void* VM_VM2C (vmptr_t p, int length)
Converts a VM pointer to a C pointer and checks to make sure that the range is acceptable.
Parameters
[in] p
length - unused
Returns
Note
Unused
Definition at line 68 of file vm.c.
void VM_VmInfo_f (void)
VM_VmInfo_f.
Definition at line 861 of file vm.c.
Referenced by VM_Init().
void VM_VmProfile_f (void)
VM_VmProfile_f.
Definition at line 811 of file vm.c.
Referenced by VM_Init().
Variable Documentation
vm_t* currentVM = NULL
Definition at line 42 of file vm.c.
Referenced by VM_CallFunc().
vm_t* lastVM = NULL
Definition at line 43 of file vm.c.
Referenced by VM_VmProfile_f().
int vm_debugLevel
Definition at line 44 of file vm.c.
Referenced by VM_CallFunc(), VM_CallInterpreted(), and VM_Debug().
const char* vmStrs[MAX_VM]
Initial value:
=
{
    "GameVM",
    "CGameVM",
    "UIVM",
}
Definition at line 49 of file vm.c.
vm_t vmTable[MAX_VM]
Definition at line 47 of file vm.c.